### ISSUE TITLE
Dropdowns not working

### ISSUE THREAD

**Issue by bisht-richa** [bootstrap-vue/bootstrap-vue#1001]
I am using bootstrap-vue and trying to implement Dropdown but it is not working properly. I have also implemented Popper.js in my project.

**Comment by tmorehouse** [comment]
'Popper must b registered as a global, and for bootstrap-vue as "popper.js"

**Comment by tmorehouse** [comment]
Are you using the entire Bootstrap Vue suite, or only importing certain components?

**Comment by bisht-richa** [comment]
Yeah I am using entire Bootstrap-Vue suite

**Comment by bisht-richa** [comment]
Still not working as I am new for vue js Kindly Help
This is code 
import Popper from 'popper.js'
import BootstrapVue from 'bootstrap-vue'

Vue.use(Popper)
Vue.use(BootstrapVue)

**Comment by tmorehouse** [comment]
Popper is not a Vue plugin.  You shouldn't need `Vue.use(Popper)`.

When building Bootstrap-Vue, using the latest v1.0.0.beta.7, Popper.js will automatically get bundled with Bootstrap-Vue
