### ISSUE TITLE
Popups not closed with global event

### ISSUE THREAD

**Issue by milenon** [bootstrap-vue/bootstrap-vue#1002]
In the previous versions of bootstrap-vue it was posible to close popups emiting:

`this.$root.$emit('hide::popover');`

, but now it's not. I know that it can be closed with:

`this.$refs['refid'].$emit('close');`

but can't we have the old global event?

**Comment by tmorehouse** [comment]
PR #1003 swill add a new $root listener to handle hiding when a global $root event is fired.

For popover the event is `bv::hide::popover`, and for tooltip the event is `bv::hide::tooltip`.

Emitting either of these on $root will close all open popovers or tooltips respectively.

**Comment by milenon** [comment]
Thanks

**Comment by tmorehouse** [comment]
Should be available in v1.0.0.beta.8 when it is released.
