### ISSUE TITLE
Popups not opened if html inside buttons (Chrome/WebKit)

### ISSUE THREAD

**Issue by milenon** [bootstrap-vue/bootstrap-vue#1005]
If we have 

```
	<button id="del" type="button" class="btn btn-outline-secondary" title="Delete">
		<i class="icon-cancel"></i>
	</button>
	<b-popover target="del" placement="left">
		Confirm?
		<button class="btn btn-warning" @click="delete">Yes</button>
		<button class="btn btn-info" @click="closeConfirm">No</button>
	</b-popover>
```
	
... no popover will be opened. If I remove the html from the button  

```
	<button id="del" type="button" class="btn btn-outline-secondary" title="Delete">
		&times;
	</button>
```
	
... the popover will be shown.

I understand that this may be due to some issues with not detecting click events when there is html inside the buttons but this was working in the previous versions of bootstrap-vue(if that can be in any help).

**Comment by tmorehouse** [comment]
This could be due to a bubbling issue with the trigger event. (i.e. in the case of HTML inside of the button, the `<i>` tag would receive the event first)

I recall a similar issue with the Bootstrap V4.beta native code as well.

Popovers (and tooltips) have had a complete remake to follow Bootstrap V4.beta switch to popper.js for positioning, and the new popover/tooltip core code in Bootstrap-Vue is basically a full port of Bootstrap V4 core code.

Do you see a similar issue when using another trigger method, such as hover or focus?

**Comment by tmorehouse** [comment]
I just made a mockup of your code, but used font-awesome to place the HTML inside a popover, as was able to get the popover to open on click.

![image](https://user-images.githubusercontent.com/2781561/30166714-7d0f8bf6-93ba-11e7-9911-e62f99987f46.png)

Does your class `.icon-cancel` have any special CSS such as `pointer-events: none` set?

**Comment by milenon** [comment]
The problem is only with the click trigger. With hover or focus it is working fine.

**Comment by milenon** [comment]
I don't know how you managed to open it with font-awesome. 
I'm using http://fontello.com/ for the font icons.
I have to further investigate then. Maybe related to paddings, margins, :after or who knows what.

**Comment by tmorehouse** [comment]
I've also placed regular HTML markup inside the test (i.e. `<i>test</i>`) and have no issues.  Are you using the latest Bootstrap-Vue (v1.0.0.beta.7) ?

**Comment by milenon** [comment]
Yes: "bootstrap-vue": "1.0.0-beta.7"

**Comment by milenon** [comment]
This is definitely browser issue. Now I saw that it is working in FireFox, but I was testing in Chome the whole time :(

**Comment by tmorehouse** [comment]
Confirmed that this is related to chrome. Firefox works fine.

**Comment by tmorehouse** [comment]
Found a workaround. It appears to be  "bug/feature" in WebKit browsers.

add teh following style to your inner HTML:

```html
<button ...>
 <i class="icon-close" style="pointer-events: none;"></i>
</button>
```
Solution from an older issue on StackOverflow: https://stackoverflow.com/a/15698643

**Comment by milenon** [comment]
Thanks :)
