### ISSUE TITLE
[modal] Make it easier to replace Bootstraps default close button

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#1009]
Right now it's quite difficult to replace Bootstraps default close button.

For example for the `b-modal` you have to override the entire `modal-header` to make a tiny change to the close button:
```vue
<b-modal>
  <slot name="modal-header">
    <h5 :is="titleTag" class="modal-title">
      <slot name="modal-title">{{title}}</slot>
    </h5>

    <button type="button"
        v-if="!hideHeaderClose"
        class="close"
        aria-label="headerCloseLabel"
        @click="hide">
      <span aria-hidden="true">{{headerCloseLabel}}</span>
    </button>
  </slot>
</b-modal>
```

**Comment by tmorehouse** [comment]
PR #1024 adds a new prop to control the content of the close button (as well as other improvements to `b-modal`).

**Comment by jackmu95** [comment]
@tmorehouse I like the improvements of the PR on the `b-modal` but the prop for the close button title wouldn't still solve my problem. In my case I need to place a SVG icon, that gets generated by a component, inside or as the close button.

Wouldn't it make sense to create some sort of component for the Close icon/button itself, because its a [general Bootstrap util](https://getbootstrap.com/docs/4.0/utilities/close-icon/) used at different components?

**Comment by tmorehouse** [comment]
Ah, yeah a long SVG string would be hard to place directly in the prop (although you could use a reference to an SVG Icon).

It is true that the _close_ is used elsewhere (such as `b-alert)`,so it could be turned into a functional component.  We do, however, have to attach event listeners to the button.  

Would a header-close slot (for the content) suffice in your case?

**Comment by jackmu95** [comment]
@tmorehouse The combination of a functional component for `close` and and a slot for the content inside it wherever it get's used sounds good for me and would suit my needs.

**Comment by tmorehouse** [comment]
The modal update PR now includes a new FC for the close button which is used by both modal and alert.  Modal will now include a slot for the close buttons content
