### ISSUE TITLE
Correct gzipped package size info on "Getting Started" page

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#1010]
The "Getting Started" page currently says that it's not recommended to include components and directives individually because the whole package is only ~15Kb.

This is not longer the case because the whole package is ~42Kb (1.0.0-beta.7) gzipped and thats nearly 3x that much than what the docs mention currently.

**Comment by tmorehouse** [comment]
Bootstarp-Vue now includes Popper.js in it's distribution files, which has added some size

**Comment by jackmu95** [comment]
@tmorehouse That makes sense. It's a good change to mention this in the docs.

**Comment by tmorehouse** [comment]
I have updated the getting started page to mention that Popper.js is included in the build, and upped the rough approximation of the file size (we'll know more about the size once we have this next batch of commits rolled into the latest version.
