### ISSUE TITLE
Make it possible to open a Dropdown programally

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#1011]
Currently it's quite difficult to open a Dropdown from a parent component.

It would be nice to have a way to define additional togglers or a `v-model` to control the visible state itself.

**Comment by tmorehouse** [comment]
If you have a reference to the dropdown menu, you can call the `showMenu()` and `hideMenu()` methods on it:
```html
<b-dropdown ref="ddown" ...>
  <!-- items here -->
</b-dropdown>
```

```js
this.$refs.ddown.showMenu();
```

**Comment by jackmu95** [comment]
@tmorehouse That was exactly what I was trying to do but it isn't working for me.

The only way I got it working was to use the `toggle()` function but this limits the access to only toggle the Dropdown and not be able to explicit open/close it.

**Comment by tmorehouse** [comment]
Ah, right. showMenu/hideMenu are triggered by a watcher.  We will need to add a show() and hide() methods to set the visibility state.

**Comment by jackmu95** [comment]
@tmorehouse That sounds good :)

**Comment by tmorehouse** [comment]
Quick workaround, but wont guarantee it will stay working, is:

```js
this.$refs.ddown.visible = true // to show;
this.$refs.ddown.visible = false // to hide;
```

**Comment by klarkc** [comment]
This need to be documented [here](https://bootstrap-vue.js.org/docs/components/dropdown#component-reference)?

**Comment by tmorehouse** [comment]
It probably should.

We'll see what we can do.

**Comment by MaratEldarov** [comment]
show() method still not working in my case

**Comment by Osman-Rafi** [comment]
In solution for this problem now @tmorehouse ? `this.$refs.ddown.visible = true` & `this.$refs.ddown.showMenu();` not working for me.
