### ISSUE TITLE
'href' attribute is not set in anchors when I use `:to` property in 'b-btn' component to set route by name

### ISSUE THREAD

**Issue by nelson6e65** [bootstrap-vue/bootstrap-vue#1015]
I use the `:to` property with my route name, but still renders an `<a>` element with `href="#"`.

Link still works; seems to handle a kind of `onclic` event. No problem. 

But I expected `href` to be set to the exact route.

**Router config:**
```js
const routes = [
  //...
  { path: '/auth/login', name: 'auth.login', component: require('./pages/auth/login.vue') },
  { path: '/auth/register', name: 'auth.register', component: require('./pages/auth/register.vue') },
  // ...
]

const router = new Router({
    routes,
    scrollBehavior,
    mode: 'history'
})
```

**I use:**
```html
<b-btn variant="primary" :to="{ name: 'auth.register' }">Sign up</b-btn>
```

**Renders to:**
```html
<a href="#" class="btn btn-primary" target="_self">Sign up</a>
```
> It adds an event listener for `click`.

**I expect:**
```html
<a href="/auth/login" class="btn btn-primary" target="_self">Sign up</a>
```

### Versions
```
yarn list v0.27.5
├─ bootstrap-vue@1.0.0-beta.7
├─ bootstrap@4.0.0-beta
├─ vue-router@2.7.0
└─ vue@2.4.2
```

**Comment by alexsasharegan** [comment]
A fix on PR #1016 will get reviewed, but your example proves that assigning an `href` AND a `to` on a `<router-link>` will display the `href`, but route to the `to`. Quite a confusing mixup. Vue router will assign the `href` on its own, so we can omit setting this `href`.
