### ISSUE TITLE
Add typescript definitions

### ISSUE THREAD

**Issue by wedi** [bootstrap-vue/bootstrap-vue#1019]
It would be cool if you could add type definitions to https://github.com/DefinitelyTyped/DefinitelyTyped to use bootstrap-vue with typescript.

**Comment by alexsasharegan** [comment]
Do you have any example projects that supply this? Something we could examine and learn from a little bit. 

I occasionally use TypeScript, but don't personally like the Vue single file component workflow so I'm pretty unfamiliar with how it integrates.

**Comment by wedi** [comment]
Hi, thank you for your quick reaction!
Basically this is about creating a file exporting interfaces.

You can find many, many examples [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/) in the DefinitelyTyped repository, the more or less official source for typescript declaration files.
Here is an example for [jquery](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jquery) and here one for a [Bootstrap datepicker](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bootstrap-datepicker).

**Comment by alexsasharegan** [comment]
Oops! I meant to say a Vue project that exports typings, but I can search the list you provided. Thank you! 

One thing noteworthy: I suppose each components props are the interface to a given component. Generally the methods on a component are part of its internals, but for something like a modal, a show and hide method is important for public usage. Our doc pages do enumerate the component props, but I know that isn't as nice as having intellisense autocompletion.

**Comment by alexsasharegan** [comment]
@wedi, are you a vscode user? Do you use the vetur extension? I'm looking into getting custom intellisense support for bootstrap-vue via venture. The same generation process for that might be used for typings as well. Still poking around in my spare time.

**Comment by wedi** [comment]
Hi Alex,
yes I am. I am happy to help you if you have a special request but my knowledge of typescript is somewhat limited so far. Otherwise I would have provided a pull request right away...

**Comment by alexsasharegan** [comment]
You can follow along here for progress implementing vetur suggestions for bootstrap vue: https://github.com/vuejs/vetur/pull/428

**Comment by d1820** [comment]
this is really needed, else we have to roll out own hack version

**Comment by octref** [comment]
Support is already released in Vetur. @alexsasharegan you can close it.

**Comment by alexsasharegan** [comment]
@wedi, I'm going to add the "Workaround Available" since vetur has some basic intellisense for bootstrap-vue. If you or @d1820 have a concrete example of a vue component library with typings, I will look into that further. I personally did not find any other vue component libs with typings, so I'm unsure how to proceed. Maybe I can have a look at the TS vue class component for some ideas.

I did here that vue is improving it's typescript support in the next version. I believe we'll get better type inference from prop definitions.

**Comment by AccessViolator** [comment]
+1 for including typings
vetur is useless for full visual studio
[since 2.5 vue.js ships with official typings for itself, router and vuex](https://vuejs.org/v2/guide/typescript.html)

**Comment by silkentrance** [comment]
@alexsasharegan there is vuetify which includes a basic set of typings. it does not include typings for the individual components. and all components will be made readily available from the VApp component so there is no need to import them separately.

https://github.com/vuetifyjs/vuetify/blob/dev/index.d.ts

**Comment by alexsasharegan** [comment]
So general PSA, I've been slowly adopting typescript myself, and only now can say I have a better understanding of this topic. I think I can definitely see a way to add some basic typings like @silkentrance's example from vuetify, but frankly I'm really busy. If anyone has the time to get this started, ping me and I'll join the fray! Or would me getting a PR started on this organization be a better platform to help the community add some TS support? In short, I think I can contribute, but I don't have the time to own this feature request right now.

**Comment by alexsasharegan** [comment]
With Vue 2.5, a lot could possibly be generated by just declaring the BV components differently. Set Lang to TS and use Vue.extend might get some decent declaration files generated. It's just a pain configuring tooling to plug typescript into the build chain.

**Comment by pi0** [comment]
Basic TS hints have arrived in latest RC: https://github.com/bootstrap-vue/bootstrap-vue/pull/1721

**Comment by kenkopelson** [comment]
@alexsasharegan Vue works seamlessly with TypeScript, and all the other component libraries seem to already have their types in the DefinitelyTyped repository.  This is not just about Intellisense, it's about having the various components declared so they don't keep showing up as undefined in the IDE.  Also, from what I see in the other libraries, the components themselves can be called "VList" instead of "v-list", which is clearly not a valid TypeScript name.  I went through a careful analysis of the libraries out there, and decided to use "Vuetify" for various reasons.  I was a bit disappointed when I found out there were no type definitions for it, since this seems to quite the standard practice these days.  It would be great if you could provide this.  Thanks.

**Comment by jianwu** [comment]
I think typescript will soon become the mainstream language for vue development, especially for vuejs3, even with vuejs2, typescript support is pretty well. I can't see any reason not using typescript for new vuejs development.  So every vue component provider should consider typescript as the first-class citizen instead of afterthought.

**Comment by ux-engineer** [comment]
Yep, TS is the way to go...I was in VueConf Toronto 1.5 months ago and Vue's core team is much into Typescript...

**Comment by sergeych** [comment]
this is actually much needed feature. ts is going to be mainstream as spa prjects tends to become sophisticated and do grow off the js pants. We start all new vue projects in ts only. pls consider reopening.

**Comment by tmorehouse** [comment]
@sergeych BootstrapVue does provide Typescript definitions (`/src/index.d.ts`)

**Comment by sergeych** [comment]
Thanks! Good news, will se what’s wrong with our configuration then

**Comment by tmorehouse** [comment]
It is linked in our package.json file https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/package.json#L15

**Comment by scratchmex** [comment]
I have installed bootstrap-vue with nuxt and typescript support and I get `Property '$bvModal' does not exist on type 'CombinedVueInstance<Vue ...` when using `this.$bvModal`. 
Using the other way to access modal (by ref) `this.$refs['modal-ref']` does work but get the warning 
```
Property 'show' does not exist on type 'Vue | Element | Vue[] | Element[]'.
Property 'show' does not exist on type 'Vue'. Vetur(2339)
```
when using the `show()` method.
I don't know whats wrong, if you could help me would be awesome. The file @tmorehouse  mention it is indeed in my `node_modules` but doesn't work well for some reason.

**Comment by emarbo** [comment]
Hi @scratchmex, I had to add `bootstrap-vue` to the `tsconfig.json` types so Typescript knows about these definitions:

```js
{
  "compilerOptions": {
    "types": [
      "@nuxt/types",
      "@nuxtjs/axios",
      "@types/node",
      "bootstrap-vue",  // <--  here
      "jest",
      "webpack",
      "webpack-env"
    ],
   // More config options...
}
```

This wasn't necessary when working with a pure Vue project (i.e. without Nuxt). In a Vue project, I import the library from the `main.ts` but in a Nuxt project I just configure it in the `nuxt.config.js`. I suppose Typescript detects the types through a direct import but not when configured through Nuxt.

**Comment by hisuwh** [comment]
How come this is closed?  As far as I can tell typescript is only half implemented - doesn't seem to know about all the props:
```
No overload matches this call.
  Overload 1 of 3, '(options?: ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>): BBadge', gave the following error.
    Type '{ variant: string; class: string; }' is not assignable to type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
      Property 'variant' does not exist on type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
  Overload 2 of 3, '(options?: ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>): BBadge', gave the following error.
    Type '{ variant: string; class: string; }' is not assignable to type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
      Property 'variant' does not exist on type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
  Overload 3 of 3, '(options?: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>): BBadge', gave the following error.
    Type '{ variant: string; class: string; }' is not assignable to type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
      Property 'variant' does not exist on type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'
```

**Comment by Ruhshan** [comment]
> Hi @scratchmex, I had to add `bootstrap-vue` to the `tsconfig.json` types so Typescript knows about these definitions:
> 
> ```js
> {
>   "compilerOptions": {
>     "types": [
>       "@nuxt/types",
>       "@nuxtjs/axios",
>       "@types/node",
>       "bootstrap-vue",  // <--  here
>       "jest",
>       "webpack",
>       "webpack-env"
>     ],
>    // More config options...
> }
> ```
> 
> This wasn't necessary when working with a pure Vue project (i.e. without Nuxt). In a Vue project, I import the library from the `main.ts` but in a Nuxt project I just configure it in the `nuxt.config.js`. I suppose Typescript detects the types through a direct import but not when configured through Nuxt.

Hello @emarbo do you have any working sample of a bootstrap-vue project with typescript? Thanks in advance.

**Comment by emarbo** [comment]
Sorry @Ruhshan, I haven't any public project with this configuration. If you already have a project using typescript, it shouldn't be hard to add bootstrap-vue.

As far as I remember, if it's a pure Vue project importing it from the main.ts should be enough. If it's a Nuxt project you'll need to include the type definitions in the tsconfig.json.

If you haven't seen them yet, the [Nuxt TypeScript](https://typescript.nuxtjs.org/) and [Vue TypeScript](https://vuejs.org/v2/guide/typescript.html) pages might help you.

**Comment by hisuwh** [comment]
@emarbo did you not see my problem?  I seem to get the types but the types don't seem to be right.

**Comment by emarbo** [comment]
Hi @hisuwh, I have never worked with jsx, so I can't help you with that. Anyway, here you have the definition of [BBadge](https://github.com/bootstrap-vue/bootstrap-vue/blob/v2.17.3/src/components/badge/index.d.ts) that extends the [BvComponent](https://github.com/bootstrap-vue/bootstrap-vue/blob/v2.17.3/src/index.d.ts#L27).

In my case, I can instantiate an instance of BBadge, and Typescript does not complain. When I "go to definition", using the IDE, it browses to the definitions linked above (within my node_modules).

To discard a problem with jsx or not, I suggest creating this `test.ts` file and check if the problem persists. If the problem persists, there something wrong with your typescript configuration. If typescript does not complain, probably you need some additional configuration to make it work with jsx.

```
    // test.ts : a file with just these two lines
    import { BBadge } from 'bootstrap-vue';
    const x = new BBadge({ props: { variant: 'something', class: 'something' } });
```

**Comment by hisuwh** [comment]
I'm a little confused as to why you would want typescript definitions for these components if you are not using JSX.  I don't believe there is anything wrong with my typescript/jsx setup.  Indeed if I omit the props then I don't get any errors:

![image](https://user-images.githubusercontent.com/4470351/111175783-a7b74700-85a0-11eb-9683-04a6ffe1539a.png)

As soon as I add props I get errors:

![image](https://user-images.githubusercontent.com/4470351/111175920-c9183300-85a0-11eb-8fc3-76e21e300295.png)

**Comment by fbnlsr** [comment]
I'm currently working on a Vue 2.x project that's using Typescript in SFC and I'm running in the same problem regarding properties that do not exist. For instance this code `this.$refs['forgotPasswordModal'].hide()` triggers an error with Vetur (`Property 'hide' does not exist on type 'Vue'. Vetur(2339)`.

I tried @emarbo's solution (adding `bootstrap-vue` to my `tsconfig` file) but it doesn't seem to help.

Does anyone have another tip on this issue?

**Comment by hisuwh** [comment]
@fbnlsr if you are using class components and the `vue-property-decorator` decorators with typescript you can use the `@Ref()` dectorator and provide a type.  

```ts
import { Component, Ref, Vue } from "vue-property-decorator";
import { BModal } from "bootstrap-vue";

@Component
export default class MyComponent extends Vue {

    @Ref()
    forgotPasswordModal: BModal;

    onSomething() {
        this.forgotPasswordModal.hide()
    }
}
```

**Comment by fbnlsr** [comment]
Unfortunately I'm using the Options API. Is there a way to make such a reference using this?

**Comment by hisuwh** [comment]
I guess you would just have to do `(this.$refs.forgotPasswordModal as BModal).hide()`

**Comment by fbnlsr** [comment]
> I guess you would just have to do `(this.$refs.forgotPasswordModal as BModal).hide()`.

This works! I could not have guessed it alone, thanks a lot for your help! :grinning:

**Comment by brunowerneck** [comment]
It is well described in the manual. If you need "this" in return type, you need annotation.


```javascript
methods: {
    // need annotation due to `this` in return type
    greet (): string {
      return this.msg + ' world'
    }
  },
  computed: {
    // need annotation
    greeting(): string {
      return this.greet() + '!'
    }
  },
```


[https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types](https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types)
