### ISSUE TITLE
[feat] Programmatically open popover/tooltip

### ISSUE THREAD

**Issue by milenon** [bootstrap-vue/bootstrap-vue#1020]
Can you make it possible to programmatically open popover/tooltip via $refs.tooltip.show() or property?

**Comment by tmorehouse** [comment]
We are looking into this.  It is possible to do this in native bootstrap, but note that when opened manually, the tooltip/popover must be closed manually (the regular triggers would not close the tooltip/popover)

**Comment by SirLamer** [comment]
Just throwing this out there... when I rigged up Popover for the alpha, this was done with a boolean prop and worked fine. I see it was changed to an events method to close and that's fine, so I am working on adding an 'open' event response.

**Comment by tmorehouse** [comment]
Just note that Bootstrap Native Popovers/Tooltips, when triggered to open manually, must be triggered to close manually (as their base tooltip class library keep track of all active triggers).

**Comment by SirLamer** [comment]
Short term that's fine, long term likely something fixable. Before I was tracking focus on all elements within the Popover and closing when none had focus

**Comment by tmorehouse** [comment]
Here is a link to the BS V4.beta.2 JS the base BS-Vue`tooltip.class.js` class is based on: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js.  Code is pretty much identical with a fe3w extras thrown in to handle some Vue situations

**Comment by SirLamer** [comment]
Sorry, I meant that to affect manual display control external to Popover i was doing it that way. I also was intercepting the parent click event, cancelling it and then separately opening the Popover. I need a way to command open for that to work.

**Comment by tmorehouse** [comment]
Just thinking....  the component versions of popover/tooltip have a (non-reactive) reference to the toolltip/popover class instance via `this._toolpop`.  So it would be possible to call any of the instance methods (i.e. `show()`, `hide()`, `enter()`, `leave()`, etc, from within the component instance.

One then could use a watcher on a component prop (or an event $emitted on the component instance) to manually trigger the showing of the tooltip/popover. Although on the directive version this might only work event based (would somehow need to assign the popover a unique ID via config options)

We would need to add in the `'manual'` trigger state into the tooltip.class.js (it is missing, as I wasn't sure on how to set it up for triggering).

I'll see if I can get the manual trigger state added to the base class, and then we can figure out the best way to programatically trigger that state.

**Comment by tmorehouse** [comment]
@SirLamer I have a working prototype of being able to use a prop `show` on the  component version of tooltip and popover to programmatically show/hide the tooltip or popover by changing the value of the new `show` prop (used with the `.sync` modifier).

I'll create a PR for this shortly.

**Comment by tmorehouse** [comment]
PR #1366 Adds in methods for programmatically opening and closing tool tips and popovers.

**Comment by tmorehouse** [comment]
Available in release v1.2.0
