### ISSUE TITLE
b-form-select when selected an option with value '0', it returns an empty object.

### ISSUE THREAD

**Issue by exgphe** [bootstrap-vue/bootstrap-vue#1022]
For example:
```
<template>
    <b-form-select v-model="selectedId" :options="ids"></b-form-select>
</template>
<script>
    data() {
        return {
            ids: [0,1,2,3,4],
            selectedId: 1
        }
    }
</script>
```

When user selects 0, selectedId is expected to be '0', but it becomes an empty object {} instead.

**Comment by tmorehouse** [comment]
Selects (and radios/checkboxes) are getting a major revamp in the the near future (hopefully for v1.0.0.beta.8), and this should be addressed then. PR #994

**Comment by tmorehouse** [comment]
This should be fixed in the latest release
