### ISSUE TITLE
<b-nav-item> not show link when use "to" as object.

### ISSUE THREAD

**Issue by lyquocnam** [bootstrap-vue/bootstrap-vue#1023]
```html
<b-nav-item :to="{ name: 'account-register' }" exact>
	<i class="fa fa-user"></i> {{ $t("account.register") }}
</b-nav-item>
```
and result:
<img width="461" alt="screen shot 2017-09-09 at 11 05 15 pm" src="https://user-images.githubusercontent.com/8347826/30241733-6b9a264c-95b3-11e7-9edf-d950560091c6.png">

result true must be: '/account/register' !

this may happend to other  components too.

**Comment by alexsasharegan** [comment]
This is due to a current bug in the underlying `<b-link>` component, and has been fixed. Just awaiting the next release.

Related #1015
Fixed in #1016

**Comment by lyquocnam** [comment]
@alexsasharegan i use version `^1.0.0-beta.7`

**Comment by alexsasharegan** [comment]
Awesome, thank you @lyquocnam !
