### ISSUE TITLE
[Collapse] using multiple collapses with a filtered list does not work

### ISSUE THREAD

**Issue by AdrianBathurst** [bootstrap-vue/bootstrap-vue#1027]
Using multiple collapse items in a list works fine. As soon as you apply a filtered list, only the first item toggles, the others thereafter do not toggle.

I have a jsfiddle to demonstrate... https://jsfiddle.net/Zim70/u1a29py9/

I have outlined what happens in the html markup...

before filter/search:

![before-search](https://user-images.githubusercontent.com/9006517/30266708-2a547f5e-96d8-11e7-9e71-cf102027f30e.png)

after filter/search:

![after-search](https://user-images.githubusercontent.com/9006517/30266716-2d6a8e36-96d8-11e7-8fbb-01cf9630b0e2.png)

**Comment by tmorehouse** [comment]
This is a Vue.js "feature".  Vue is somewhat intelligent in it's re-use elements/components when they are in `v-for` loops.  You should always provide a `key` value in your `v-for` loop to make sure vue knows that each section is unique.

See this updated fiddle for the solution: https://jsfiddle.net/u1a29py9/9/

**Comment by AdrianBathurst** [comment]
Thank you!
