### ISSUE TITLE
Module not found: Error: Can't resolve 'lodash.startcase'

### ISSUE THREAD

**Issue by michalbujalski** [bootstrap-vue/bootstrap-vue#1028]
I've added BootstrapVue to my project. When trying to build i keep getting:
`Module not found: Error: Can't resolve 'lodash.startcase` error.

followed by:
` @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/bootstrap-vue/lib/components/table.vue 91:0-41
 @ ./~/bootstrap-vue/lib/components/table.vue
 @ ./~/bootstrap-vue/lib/components/index.js`

I'm using https://github.com/egoist/vuepack

**Comment by tmorehouse** [comment]
PR #1030 may address this issue.

**Comment by greg-harrison** [comment]
I'm seeing this issue, as well, even after it was addressed in the latest Beta release.

I notice the Lodash and Lodash.startcase are in the DevDependencies, what's the reasoning there?

**Comment by tmorehouse** [comment]
lodash is used by the docs, while lodash.startcase is used by b-table.  lodash.startcase has been added as a dependancies in PR #1030, which will be available in the next release (v1.0.0.beta.8)
