### ISSUE TITLE
Dropdown does not work on Heroku deployment

### ISSUE THREAD

**Issue by ducdev** [bootstrap-vue/bootstrap-vue#1029]
Hi guys, when I clicked the dropdown nothing opened. It works on localhost well.
I guess it's a problem with jquery ? Please help me correct it. Thanks.

**Comment by tmorehouse** [comment]
Bootstrap-Vue doesn't use jQuery. Make sure you are **not** including Bootrstrap's `bootstrap.min.js`

Also, which version of Bootstrap-Vue are you using?

**Comment by ducdev** [comment]
It's `"bootstrap-vue": "^0.18.0"`, though I'm not importing `bootstrap.min.js`
```
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
```

**Comment by tmorehouse** [comment]
Try updating to the latest Bootstrap-Vue v0.23.0 (Boostrap v4.alpha.6 release), or try using the newer v12.0.0.beta.7 release (which uses Bootstrap v4.beta.1)

**Comment by ducdev** [comment]
Well, I confirm when I update `bootstrap-vue` from `v0.18.0` to `v0.23.0` the issue is not here anymore, the update comes with new hover CSS state for `.dropdown-item`, good for now ! Thanks @tmorehouse !
