### ISSUE TITLE
RTL support!

### ISSUE THREAD

**Issue by vad11** [bootstrap-vue/bootstrap-vue#1031]
Can I use this framework with RTL?

**Comment by tmorehouse** [comment]
IN most cases you should be able to, but if you find any issues with respect to RTL, let us know and we can try to incorporate fixes.

**Comment by tmorehouse** [comment]
Since Bootstrap-Vue relies on Bootstrap V4 css for layout, you may want to join in on the conversation at Bootstrap Official at:
- https://github.com/twbs/bootstrap/issues/24662
- https://github.com/twbs/bootstrap/pull/23703

**Comment by tmorehouse** [comment]
Another option that **might** work is to run Bootstrap's (and BootstrapVue's) CSS through https://www.npmjs.com/package/postcss-rtl

**Comment by saeedkgr** [comment]
b-form-checkbox and b-form-checkbox-group need to support RTL
