### ISSUE TITLE
Not working show method for modal

### ISSUE THREAD

**Issue by bigperson** [bootstrap-vue/bootstrap-vue#1034]
I use once modal for add and edit data.
Example code: https://jsfiddle.net/7ztq8nzd/27/
Please click 'edit' btn, then hide modal, then click 'add new' btn,
method show not working
![screenshot_1](https://user-images.githubusercontent.com/4757391/30287132-9ac0cbfe-972c-11e7-82b7-15a9e053bbcd.jpg)

**Comment by tmorehouse** [comment]
We have a major revamp of modal happening via PR #1024 which may address this issue.

**Comment by bigperson** [comment]
Can I now temporarily fix this problem before the update is released?

**Comment by tmorehouse** [comment]
The updates are out.  Please try using the latest version `v1.0.0-beta.9`, and check the updated documentation at https://bootstrap-vue.js.org/docs/components/modal
