### ISSUE TITLE
Column breakpoint classes without size not working

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#1041]
It's currently not possible to apply the `col-[sm|md|lg|xl]`class without any size.

As an live example look at the [Docs](https://bootstrap-vue.js.org/docs/layout/#stacked-to-horizontal) where the `col-sm` class isn't added to the column.

**Expected**
```vue
<!-- Vue.js template -->
<b-container>
    <b-row>
        <b-col sm>col-sm</b-col>
        <b-col sm>col-sm</b-col>
        <b-col sm>col-sm</b-col>
    </b-row>
</b-container>

<!-- HTML output -->
<div class="container">
  <div class="row">
    <div class="col-sm">col-sm</div>
    <div class="col-sm">col-sm</div>
    <div class="col-sm">col-sm</div>
  </div>
</div>
```

**Currently**
```vue
<!-- Vue.js template -->
<b-container>
    <b-row>
        <b-col sm>col-sm</b-col>
        <b-col sm>col-sm</b-col>
        <b-col sm>col-sm</b-col>
    </b-row>
</b-container>

<!-- HTML output -->
<div class="container">
  <div class="row">
    <div class="col">col-sm</div>
    <div class="col">col-sm</div>
    <div class="col">col-sm</div>
  </div>
</div>
```

**Comment by alexsasharegan** [comment]
Thanks for finding this! I'll look into it today!

**Comment by alexsasharegan** [comment]
So here's the rub: when a prop is defined solely with a type of `Boolean`, Vue conveniently converts the props presence to `true` and it's absence to `false`. The `sm,md,lg,xl` props take `[String, Number, Boolean]` though, so they don't get this convenient treatment.

*Workaround: * `<b-col :sm="true">col-sm</b-col>`

I'll try to find a good way to trap our `true` case that doesn't require the full v-bind treatment.

**Comment by jackmu95** [comment]
@alexsasharegan Thanks for the workaround :)

**Comment by alexsasharegan** [comment]
@jackmu95 PR #1042 should fix this in our next release.
