### ISSUE TITLE
[tabs]: Tab focus issue

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#1044]
Its currently not possible to switch tabs with the keyboard.
See the [docs](https://bootstrap-vue.js.org/docs/components/tabs/) as live example or take a look at the screenshot below.

As far as I can see, the issue is caused because the `role="tablist"` element has `tabindex="0"` set and the `role="tab"` elements `tabindex="-1"`. Switching the `tabindex` values between the elements solves the problem for me.

![bootstrap-vue-tabs-focus-issue](https://user-images.githubusercontent.com/2737132/30364501-c2a37a66-9864-11e7-80d3-1557c5f45430.png)

**Comment by tmorehouse** [comment]
Tabs use left/right arrow keyboard navigation, as outlined in the W3C ARIA spec (they are classified as widget, so the widget is focusable (as you see in the above screen shot), and you use left/right to switch tabs

**Comment by jackmu95** [comment]
@tmorehouse Thanks for the clarification! Then works everything as expected.
