### ISSUE TITLE
[tabs]: Make a tabs title content more customizable

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#1045]
It's currently not possible to add additional elements (e.g. a badge with a count) to the tab title.
IMHO it would be a good ides to add a ´title´ slot to make it more  customizable.

**Comment by Sobient** [comment]
There is, use the `head-html` property:

`head-html="<span class='badge badge-secondary'>test</span> Welcome">`

**Comment by jackmu95** [comment]
@Sobient Thanks for the hint but what about dynamic content?
In my case a need a badge that shows a error count that needs to be updated and hidden if no errors exist.

**Comment by tmorehouse** [comment]
The title prop for each tab supports plain HTML.  You could dynamically update the `title` prop of the tab with basic HTML markup (as a string, which includes the basic badge HTML markup).
```js
data() [
  tabTitle: 'My Title <span class="badge badge-secondary">12</span>'
}
```

```html
<b-tabs>
  <b-tab :title="tabTitle" ..>
    Tab content
  </b-tab>
</b-tabs>
```

You could use a computed prop or a method to genrrate the tab title. A method might better suit your needs:

```js
methods {
  tabTitle(title, count) {
    return `${title} <span class="badge badge-secondary">${count}</span>`;
}
```

```html
<b-tabs>
  <b-tab :title="tabTitle('My Title', '12)" ..>
    Tab content
  </b-tab>
</b-tabs>
```

**Comment by jackmu95** [comment]
@tmorehouse I'am aware that this is possible but I think a slot would be a better solution for that kind of scenario because a badge could be implemented with the `b-badge` component.

**Comment by tmorehouse** [comment]
Unfortunately a slot will not work (if hte slot is inside th `b-tab` component).

The title tabs are rendered inside the `b-tabs` component, not inside the `b-tab` component.  The slot DOM would have to be "transferred" from the `b-tab` component to the `b-tabs` component, which would not work if the tab is in lazy mode (where the b-tab` component is not rendered until shown), hence the DOM doesn't always exist to transfer it...  you would end up with blank titles in lazy mode, not to mention the errors that Vue may generate due to the DOM moving from outside the component.

**Comment by jackmu95** [comment]
@tmorehouse Then we have to stick the the method solution for now.

**Comment by Sobient** [comment]
@jackmu95 Try using the ` character at the start and end of your mixed content. It allows for combining regular text and variables. Github automatically formats these so it's hard to show, but here's a jsfiddle.

Additionally, you simply use the title, but bind it with :title.

http://jsfiddle.net/mojvw303/2/

**Comment by TC20** [comment]
I believe this is no longer a workaround. The method mentioned by @tmorehouse doesn't work and the JSFiddle provided by @Sobient is not working either. Is there an alternative?

**Comment by Sobient** [comment]
Just use the tab slots. See the documentation here: https://bootstrap-vue.js.org/docs/components/tabs

**Comment by geni94** [comment]
The `<template slot='title'></template>` is not working, at least for the `b-tabs` component.

I have no dynamic component inside of it, just an icon and the text title, so I'm really confused why it doesn't work.

**Comment by seeratawan01** [comment]
This is working for me
``` javascript
<b-tabs >
      <b-tab active >
        <template slot="title">
          Overall
          <b-badge variant="light">545</b-badge>
        </template>
        <p>
          I'm the Overall tab
        </p>
      </b-tab>
</b-tabs>
```
