### ISSUE TITLE
b-form-file .custom-file-control text not overwritten with filename

### ISSUE THREAD

**Issue by sigmoidbigfoot** [bootstrap-vue/bootstrap-vue#1049]
This issue can be observed on the official documentation here: https://bootstrap-vue.js.org/docs/components/form-file/

To replicate, select a file in the first example file input control.

**Expected Behavior:** the content of the file input should change to show the contents of the data-selected property of the <span>

However, nothing happens.

It appears that the CSS is not being prioritized correctly. The content property from `_custom-forms.scss` is overriding the CSS from `form-file.vue`.

---

![capture23](https://user-images.githubusercontent.com/15150911/30400617-09594b9c-989d-11e7-94b1-bb775bf56c48.PNG)

---

![capture](https://user-images.githubusercontent.com/15150911/30400564-e69ba8de-989c-11e7-853f-191a2efdbd48.PNG)

**Comment by tmorehouse** [comment]
Bootstrap has introduced a more specific CSS for targetting the labels.

PR #1033 includes a fix for this (and a few other fixes, such as focus styling).  The PR hsaa been merged into teh DEV branch and will be available in release v1.0.0.beta.8

**Comment by sigmoidbigfoot** [comment]
Thanks for the clarification, I'll look forward to the next release for this
