### ISSUE TITLE
Alert display with two close buttons

### ISSUE THREAD

**Issue by FrancescoMussi** [bootstrap-vue/bootstrap-vue#1054]
I am using a dismissable alert. Everything works fine except the fact that the close button (X) is shown two times. One time as 'x' inside a span and the other time as ::before css property:

![screen shot 2017-09-14 at 15 21 35](https://user-images.githubusercontent.com/5312907/30429519-855eb024-9960-11e7-95c2-7a7c3c5a8a5b.png)

![screen shot 2017-09-14 at 15 21 55](https://user-images.githubusercontent.com/5312907/30429524-86a9207c-9960-11e7-8aff-1234fac508fd.png)
 
This is the alert component:

```
<b-alert variant="danger"
         dismissible
         :show="showUserRemovedAlert"
         @dismissed="showUserRemovedAlert=false">
  User successfully removed
</b-alert>

```

In any case is not a big deal. I can easily remove the `<span>x</span>`  with this style:

```
.alert .close span {
  display: none!important;
}
```

But I am wondering why there are two close buttons.
Am I doing something wrong?

**Comment by tmorehouse** [comment]
Which version of Bootstrap-Vue are you using, and which version of Bootstrap's CSS are you using?

**Comment by FrancescoMussi** [comment]
Bootstrap version: `4.0.0-beta`
Bootstrap-Vue version: `1.0.0-beta.7`

**Comment by tmorehouse** [comment]
I don't see the above issue in any of our example docs.

It almost looks like you might have an older bootstrap CSS also included, which creates the before psuedo-element (which is no longer in Bootstrap V4 CSS)

**Comment by FrancescoMussi** [comment]
Yes or probably some style collide and mess up the alert class.
Thanks anyway. Great component!
