### ISSUE TITLE
Docs Scrollspy

### ISSUE THREAD

**Issue by sosensible** [bootstrap-vue/bootstrap-vue#1056]
https://an136.infusionsoft.com/app/linkClick/120298/df642485ba92d701/125566002/f7a67d43041c029a

The scroll spy highlight is not happening.

**Comment by tmorehouse** [comment]
V-B-Scrollspy has been updated in PR #1063 which should address may of the anomalies in the beta version.

p.s., please don't post links that require users to download an executable to view a file.
