### ISSUE TITLE
NavBar not working

### ISSUE THREAD

**Issue by YuriySimakov** [bootstrap-vue/bootstrap-vue#1059]
Hello. I used example of docs of [NavBar](https://bootstrap-vue.js.org/docs/components/navbar/)
But this example not working with last update 1.0.0 beta 7. 

I

**Comment by alexsasharegan** [comment]
Could you provide some info for us?

- version of bootstrap
- component markup

**Comment by vandorjw** [comment]
I have a working code example here:

https://github.com/vandorjw/assessment-web/blob/master/yarn.lock#L959

The above is proof I used 1.0.0 beta 7

https://github.com/vandorjw/assessment-web/blob/master/src/components/blocks/HeaderBlock/Header.vue

Code example

https://vandorjw.github.io/assessment-web/#/

Running project

**Comment by alexsasharegan** [comment]
Haha I went through your links thinking, "But this is working!!!". Didn't realize your comment was a solution, not the original issue.
