### ISSUE TITLE
B-table param-binding breaking change

### ISSUE THREAD

**Issue by sschadwick** [bootstrap-vue/bootstrap-vue#1062]
Recently attempted to upgrade from v0.23.0 to v1.0.0b7 but testing broke. I am attempting to manually update the data upon a successful PATCH req so I don't have to reload the data with GET reqs.

As far as I can tell, the `<b-table>` element is not reactive when the object passed through `params` is updated downstream. This worked great in v0.23.0 but is no longer functional in v1.0.0b7. Bootstrap-vue was the only dependency I updated, causing my tests to fail. Reverting to the previous version caused them to pass again.

```Vue
// mainComponent.vue
<template>
  <div id='listObjs'>
    <b-table striped hover :items='main.objs' :fields='fields'>

      <template slot='boolean' scope='obj'>
        {{obj.item.boolean}}
      </template>

      <template slot='actions' scope='obj'>
        <b-btn size='sm' variant='info' @click='editObj(obj)' class='editObj'>Edit</b-btn>
      </template>

    </b-table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      fields: {....}
    };
  },
  methods: {
    editObj(obj) {
      this.$router.push({
        name:   'OtherComponent',
        params: {obj: obj.item}
      });
    }
  }
};
</script>
```

```Vue
// otherComponent.vue
<template>
  <div id='editobj'>
    <strong>Text:</strong>
    <b-form-input v-model='update.text'></b-form-input>

    <strong>Boolean:</strong>
    <input type='checkbox' v-model='update.boolean'></input>

    <b-btn variant='info' @click='saveChanges()' id='saveChanges'>Save Changes</b-btn>
</template>

<script>
export default {
  created() {
    this.obj = this.$route.params.obj;
    this.update.text    = this.obj.text;
    this.update.boolean = this.obj.boolean;
  },
  data() {
    return {
      obj:    {},
      update: {
        boolean: false,
        text:    ''
      }
    };
  },
  methods: {
    saveChanges() {
      this.$http.patch(/* PATCH route */, this.update).then(() => {
        this.obj.text    = this.update.text;
        this.obj.boolean = this.update.boolean;

        this.$router.push({name: 'MainComponent'});
      });
    }
  }
};
</script>
```

**Comment by alexsasharegan** [comment]
I don't see any reason the table would update based on your router `params`. If you update the `items` that feed your table, it will update. I'm not sure there's enough info in the snippet for me to see the reactive connection to `<b-table>`.

**Comment by sschadwick** [comment]
@alexsasharegan I didn't explicitly write anything that would create a reactive connection between `<b-table>` and the router `params`. My understanding was that since `this.obj` in `otherComponent.vue` was a reference to the param, that data property in the parent component would be updated. It works as expected when using v0.23.0 but not using v1.0.0v7 (upgrading `bootstrap-vue` is the only change I'm making). I would understand if this functionality was broken by a `vue` or `vue-router` dep bump but I don't understand how `bootstrap-vue` is changing the visible behavior here.

**Comment by alexsasharegan** [comment]
I understand the reasoning, but there's nothing I can do to really help you if you're using a reactive side-effect. Chances are this is just a case of JS object references matching somewhere in an old version, and now a new version copies that object. I would make a stronger reactive connection to ensure you don't run into this breakage via vue, or vue-router.
