### ISSUE TITLE
Modal does not open.

### ISSUE THREAD

**Issue by eamon-hguk** [bootstrap-vue/bootstrap-vue#1064]
When I try the example for modals on your website, it will not open, I just get a grey screen.
When I inspect the DOM I can see the modal is changing when I click the button, but remains invisible.

**Comment by alexsasharegan** [comment]
Double check to make sure you are including the correct css for your version.

Bootstrap-Vue beta requires Bootstrap beta
Bootstrap-Vue alpha (<=0.23.0) requires Bootstrap alpha

**Comment by eamon-hguk** [comment]
Yes that was it, thank you, I had accidentally CDNed in the wrong bootstrap version.
Finding bootstrap-vue really useful.

Thank you again
