### ISSUE TITLE
[feat] Disabling Tooltips

### ISSUE THREAD

**Issue by brightertools** [bootstrap-vue/bootstrap-vue#1065]
Hi, 

Is it possible to disable all tooltips, for instance if I have tooltips on toolbar buttons I don't want users on mobile devices to have to click the button twice?

If I detect the screen is smaller than a certain size, how would I disable the tooltips?

Thanks

**Comment by tmorehouse** [comment]
Currently it is not possible to disable tooltips or popovers.  It is possible to emit an event to close all open tooltips or popovers on a page though.

Are you using the directive or component version of tooltips?

The original bootstrap code has an option to disable tooltips/popovers (on an individual bases), which we have yet to implement.

It is difficult to detect the change in breakpoint programmatically, but you could implement your own browser detection code and set a global flag that instructs your app to not instantiate the component version (i.e. using `v-if` directive on the component version).

**Comment by brightertools** [comment]
Ok, thanks 👍

**Comment by tmorehouse** [comment]
PR #1387 partially addresses this issue by providing a `disabled` prop on the `<b-popover>` and `<b-tooltip>` components.

You would still need to figure out the display size to determine if the tooltips should be disabled.

Note this is only available in the component version of tooltip/popover, not the directive version.

**Comment by tmorehouse** [comment]
v1.3.0 has been released, and has options for programmatically disabling, opening, and closing tooltips/popovers.
