### ISSUE TITLE
Modal Header Color

### ISSUE THREAD

**Issue by mredman** [bootstrap-vue/bootstrap-vue#1066]
Hi,

Is it possible to set the background header colour as a property or create a slot and set a header background colour for the whole header?

Thanks

**Comment by alexsasharegan** [comment]
You can configure the entire header section using the named slot `modal-header`.

Here's a breakdown of the slots from the docs page for modal (end of page):
![image](https://user-images.githubusercontent.com/16269252/30512894-1c7961b8-9aae-11e7-8d97-cd2d6d3bd98c.png)

**Comment by mredman** [comment]
I have added a slot, but when I set a background colour it docent set the whole background colour?

**Comment by alexsasharegan** [comment]
You want to set the whole modal background color, or just the header?

**Comment by tmorehouse** [comment]
Next release v1.0.0.beta.8 allows for setting the background of the modal header, body and footer. The new release should be available in the week.

**Comment by brightertools** [comment]
Awesome 👍, thanks
