### ISSUE TITLE
b-form-radio buttons not firing the change event

### ISSUE THREAD

**Issue by chevol** [bootstrap-vue/bootstrap-vue#1070]
Using b-form-radio without the buttons works fine, but add the buttons prop and the events don't get fired. I am specifically trying to do something on the change event and its not being fired off.

**Comment by tmorehouse** [comment]
We have revamped form-radios (breaking cahnge) in the upcoming v1.0.0.beta.8 release, which might address this issue.

I will check the code.  I think in button mode the click event (which is used to trigger the change event) happens on the styled label and not the actual hidden radio input.

I will investigate.

**Comment by tmorehouse** [comment]
I've added a PR #1071 that should address this issue when release v1.0.0.beta.8 comes out.

**Comment by tmorehouse** [comment]
Please note that there is  breaking change with form-radio, as form-radio now will only generate a single radio input, while the new wrapper component form-radio-group supports the options prop, and the ability to place the b-form-radio inputs directly inside the wrapper component.

When in button mode, the b-form-radio component must be placed inside a b-form-radio-group component.

You can see the new usage at https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/docs/components/form-radios/README.md

**Comment by chevol** [comment]
Ok, thanks I will take a look at the new usage and update when it comes out. Thanks again!
