### ISSUE TITLE
Cannot use modal with sticky navbar

### ISSUE THREAD

**Issue by saeedvaziry** [bootstrap-vue/bootstrap-vue#1073]
When i use modal with sticky navbar , navbar comes in front of modal ( z-index problem ).
How can i fix this?

**Comment by tmorehouse** [comment]
Which browser are you using? Not all browsers implement `position: sticky` (i.e. Chrome). IF you are using a polyfill for `sticky` positioning, then it might be overriding the z-index notmally assigned by Bootstrap V4's CSS

**Comment by saeedvaziry** [comment]
with all browsers there is same problem

**Comment by tmorehouse** [comment]
The modal's Z-Index is defined via Bootstrap's CSS (as is the Z-index of the navbars).

It could be affected based on the order your navbar and modal are rendered in the dom.

**Comment by saeedvaziry** [comment]
When i add the modal in the root component alongside the navbar it works... but in this case the modals are useless. Because i want to have modal content inside my children components.

**Comment by tmorehouse** [comment]
You may need top address this issue with Bootstrap V4, as the positioning/z-index is handled by their CSS (we don't control the z-index settings).

In some cases, placing the modal inside a fixed container (which might have `overflow: hidden` set), it is not always possible to to use another fixed/absolute positioned element that is positions wrt the viewport, as the containing fixed element becomes the absolute position element that the inner absolute position element gets placed.

**Comment by tmorehouse** [comment]
If you are placing the modal compoent inside the navbar, you may need to create a wrapper div do contain both your navbar and modal (so that modal is outside your navbar, but still "close by".:

```html
<template>
  <div>
    <b-navbar ...>
      <!-- navbar content-->
    </b-navbar>
    <b-modal ...>
      <!-- modal content -->
    </bmodal>
  </div>
</template>
```

As per the officail Bootstrap V4 docs https://getbootstrap.com/docs/4.0/components/modal/#how-it-works
> - Modals use `position: fixed`, which can sometimes be a bit particular about its rendering. Whenever possible, place your modal HTML in a top-level position to avoid potential interference from other elements. **You’ll likely run into issues when nesting a `.modal` within another `fixed` element.**

**Comment by chumager** [comment]
I've got a solution to get around the problem... 

I've made a vuex store an set the sticky bit there, and define 2 actions to set it true or false, in the shown or show event, i use the action to set it to false, and the opposite to the hide or hidden event in the modal...

With that you can have the best of both... ;)

**Comment by saeedvaziry** [comment]
I used vue portal package to solve my problem.

https://github.com/LinusBorg/portal-vue

**Comment by GreatfortuneM** [comment]
l had the same issue, l just removed the sticky-top and it worked normally

**Comment by jessekafor** [comment]
$('#yourModalId').on('show.bs.modal', function () {
    $('.your-sidebar-selector').theiaStickySidebar('destroy');
});

$('#yourModalId').on('hidden.bs.modal', function () {
    $('.your-sidebar-selector').theiaStickySidebar({
        additionalMarginTop: 30
    });
});
