### ISSUE TITLE
The `placeholder` prop in the form-file component doesn't appear to work

### ISSUE THREAD

**Issue by robcresswell** [bootstrap-vue/bootstrap-vue#1079]
The `placeholder` prop in https://bootstrap-vue.js.org/docs/components/form-file/ seems like it would override the default "Choose file..." text, but at the moment seems to do nothing.

**Comment by tmorehouse** [comment]
This is a known issue, and should be fixed in the next release (coming out this week hopefully).

It is due to a change in specificity in Bootstrap V4.beta's CSS.

**Comment by robcresswell** [comment]
Awesome; I'll close the bug report. Thanks for the quick reply, as usual 😄
