### ISSUE TITLE
Error using b-popover

### ISSUE THREAD

**Issue by javiercbk** [bootstrap-vue/bootstrap-vue#108]
The following snippet triggers a type error
```html
<b-popover title="Enter the password used to login.">
  <span slot="content"><span class="fa fa-question-circle" id="currentPasswordHint"></span></span>
</b-popover>
```
This is logged in the console
`Cannot read property 'addEventListener' of undefined`

**Comment by pi0** [comment]
@javiercbk Just a quick look inside source code it seems the `undefined` thing is `this._trigger` which is defined [here](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/components/popover.vue#L350) :)) Anyway @SirLamer can help better than me as he was the author :))

**Comment by pi0** [comment]
Meanwhile would you pleas test this ? 
```js
<b-popover title="Enter the password used to login.">
  <span>Hover me</span>
  <span slot="content"><span class="fa fa-question-circle" id="currentPasswordHint"></span></span>
</b-popover>
```

**Comment by javiercbk** [comment]
Yup, Posted a bug when I should have read the code, sorry about that.

Basicaly popover need some kind of content, What I was doing is providing a content for the popover but nothing to append the event to. This did the trick:

```html
<b-popover triggers="hover">
   <span class="fa fa-question-circle" id="currentPasswordHint"></span>
   <span slot="content">Enter the password used to login.</span>
</b-popover>
```

**Comment by SirLamer** [comment]
I might add an error catcher for this case to explain it. I think this will happen a lot.
