### ISSUE TITLE
form-input lazy-formatter makes input event firing like change event

### ISSUE THREAD

**Issue by caskuplich** [bootstrap-vue/bootstrap-vue#1085]
When we pass `lazy-formatter` prop to `<b-form-input>` it makes the `input` event firing only when the field is blurred, like the `change` event. I think that the `lazy-formatter` shouldn't change the `input` event behavior, just the way the `formatter` function is called (when the field triggers the `change` event). What do you think?

**Comment by tmorehouse** [comment]
This should be fixed in the next release.

**Comment by caskuplich** [comment]
Thank you, @tmorehouse!
