### ISSUE TITLE
Docs: Webpack + SASS

### ISSUE THREAD

**Issue by rdytogokev** [bootstrap-vue/bootstrap-vue#1087]
Under the "Getting Started" > "Webpack" section of the docs:
Could you recommend or show how to use Bootstrap Vue alongside bootstrap-sass (or your preferred Bootstrap and Sass config.)

**Comment by alexsasharegan** [comment]
Bootstrap comes built in sass, with css dist files (v3 was built in LESS). Are you asking how to tie into the sass source files? Bootstrap used to have better examples of using their variables file to create overrides, but it seems to have gone MIA. Next best thing: https://getbootstrap.com/docs/4.0/getting-started/webpack/#importing-styles

**Comment by Yamakaky** [comment]
Yes, a tutorial with a simple way to override bootstrap's variables would be welcome. Maybe a webpack config which loads `src/bootstrap-overrides.scss`?

**Comment by mosinve** [comment]
You can simply include src/bootstrap-overrides.scss in your main file as you include BV and main BS stylesheets. It's necessary to import override file before main BS scss.
Also you must setup sass-loader in webpack config.

**Comment by mosinve** [comment]
or you can create your custom.scss and include there all needed stylesheets and then build it by gulp, or webpack

**Comment by mosinve** [comment]
I have this string in my projects's `webpack.config.js`:
````
{test: /\.scss?$/, loaders: ['style-loader', 'css-loader', 'sass-loader']},
`````

**Comment by rdytogokev** [comment]
@mosinve Thanks.  This kind of information would be a perfect inclusion to the documentation. Maybe, with a couple of code examples.

**Comment by Yamakaky** [comment]
See also https://github.com/bootstrap-vue/bootstrap-vue/issues/690#issuecomment-320434761

**Comment by mfr-itr** [comment]
For the record, this setup works for me:
src/main.js
```js
import BootstrapVue from 'bootstrap-vue'
import './bootconf.scss'
import 'bootstrap-vue/dist/bootstrap-vue.css'
Vue.use(BootstrapVue)
```
src/bootconf.scss
```scss
/* See https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss */
$body-bg: black

@import '~bootstrap/scss/bootstrap.scss'
```
```

**Comment by gadams999** [comment]
This is getting me too (new to webpack, ES, vue). @mfr-itr , I tried your approach but am running into a simple problem I cannot figure out where to address (using scaffold from vue-cli). Using similar main.js:

```json
import config from './config'
import Vue from 'vue'
import Vuex from 'vuex'
import cognitoAuth from './cognito'
import App from './App'
import store from './store'
import router from './router'
import BootstrapVue from 'bootstrap-vue'
import './bootconf.scss'
import 'bootstrap-vue/dist/bootstrap-vue.css'
import 'bootstrap/dist/css/bootstrap.css'

Vue.use(Vuex)
Vue.use(BootstrapVue)

Vue.config.productionTip = false
```
I get the following error during `yarn run dev`:

```
 ERROR  Failed to compile with 1 errors

This relative module was not found:

* ./bootconf.scss in ./src/main.js
```

I know I'm close :), but for the life of me cannot figure out where I need to address. Is it file location, webpack config, etc.? I've added the loaders and tried adding a test regex for .scss in `webpack.base.config.js` to no avail.

**Comment by Yamakaky** [comment]
Where is your `bootconf.scss`?

**Comment by mfr-itr** [comment]
Also, you added `import 'bootstrap/dist/css/bootstrap.css'`, which should be there since we import it in `bootconf.scss`.

**Comment by gadams999** [comment]
The `bootconf.scss` file is located in s`src/`, but I tried different locations also. I verified the path appears to be working by creating a `css` file in `src/` and that was able to import. That's why I'm thinking it's a webpack config on my side. I just don't know enough of all the components for a `vue init webpack` (not simple), to know how to get SASS support included.

I did have a question on your loads @mfr-itr . From reading the vue-bootstrap docs, my understanding is that `bootstrap-vue.css` should be loaded before `bootstrap.css`. In your working example above, wouldn't the load of the `bootconfig.scss`, which in turn imports the Bootstrap SCSS, reverse that order (e.g., have vue-bootstrap loading *after* the compiled bootstrap)?

**Comment by mfr-itr** [comment]
The declaration order in bootconf.scss matters since we override some bootstrap variables.
The import order of the .css files doen't matter.
You may have to modify webpack's config to properly load .scss files.

**Comment by tdbear** [comment]
I'm getting vue integrated into an existing old-school HTML+SASS+jQuery multi-page application. Getting wbpack set up for multi-page applications was not trivial, especially considering I want the output to be separate groups of CSS+JS files that I include into select HTML pages. I am still not sure I did it correctly.

**Comment by alexsasharegan** [comment]
You can always reference the configuration settings from our vue-cli templates:

- https://github.com/bootstrap-vue/webpack
- https://github.com/bootstrap-vue/webpack-simple

They won't cover everyone's use case, but they should prove helpful. Let me know if they fall out of date, @tmorehouse @mosinve , since I'm not able to actively stay up to date.

**Comment by tmorehouse** [comment]
Here is a good article on using webpack + SASS with bootstrap V4 (which applies to Bootstrap-Vue as well):

https://medium.com/@_Dreamstream/integrating-and-customising-bootstrap-4-in-vue-js-cbc29ba7688e

**Comment by bbugh** [comment]
I was having the same problem as @gadams999. I tried installing `node-sass` and `sass-loader` (with yarn), got a different error, then uninstalled them....... and then it suddenly started working. I didn't do anything else in between, so I haven't the slightest idea why. My working copy is clean of changes...

**Comment by CoolGoose** [comment]
@tmorehouse is this still needed for a 1.0 release ? There are some nice changes from rc11 , so I could try writing some basic setup if needed.

**Comment by nao360** [comment]
> https://medium.com/@_Dreamstream/integrating-and-customising-bootstrap-4-in-vue-js-cbc29ba7688e

Great guide, but not having worked with Webpack previously I experienced some confusion. For what it's worth, here's how I got it working using the link @tmorehouse provided. Assuming your project is called `my-project`:

Create the project boilerplate
`vue init bootstrap-vue/webpack my-project`

Change directory into the project
`cd my-project`

Install node-sass
`npm install node-sass --save --dev``

Install sass-loader
`npm install sass-loader --save --dev`

Edit the `module: { rules [ . . . ] }` configuration in `build/webpack.base.conf.js`, changing this bit:

`    {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },`

To this:

`{
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          vueLoaderConfig,
          loaders : {
            'scss': 'vue-style-loader!css-loader!sass-loader',
            'sass': 'vue-style-loader!css-loader!sass-loader?indentedSyntax',
          },
        },
      },
      {
        test: /\.scss$/,
        use: [{
            loader: 'css-loader'
          },
          {
            loader: 'sass-loader'
          }
        ]
      },`

Don't forget, you'll need to use the `lang="scss"` attribute to `style` tags in your `.vue` templates, for example:

`<template>...</template>
<style lang="scss" scoped>
.relatives {
  .yomama { 
    width: 99999999px;
  }
}
</style>`

**Comment by tmorehouse** [comment]
Bootstrap-Vue (the next coming 2.0.0 (not rc.x) release uses SCSS for custom styles, and has added some basic docs on using SCSS (although we don't go into details on node-sass and sass-loader)

Hopefully we will have the webpack templates updated

**Comment by chriszrc** [comment]
@tmorehouse will there also be an example of not importing all the bootstrap styles? If we're only using a few bootstrap components, it seems overkill to import all the styles which add up to almost ~200kb

**Comment by tmorehouse** [comment]
Yeah, we should include a way to import just the variables and the single component SCSS, although the minified CSS is only 17.4kb before gziping

**Comment by chriszrc** [comment]
Oh, yeah, the bootstrap-vue styles are almost nothing, I was referring to the accompanying bootstrap css file, my understanding is that we needed both of these files:

```
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-vue/dist/bootstrap-vue.min.css';
```

To have everything work?

**Comment by tmorehouse** [comment]
Yeah, you definitely need the bootstrap scss/css for it to work. I think bootstrap docs mention a way to include only certain parts of their SCSS, you just need to know which files to include, as some of the component styles are spread across multiple files.

**Comment by jackmu95** [comment]
With SCSS support in the build system this is also possible:
```js
import 'bootstrap/scss/_dropdown.scss';
import 'bootstrap-vue/src/components/_dropdown';
import { Dropdown } from 'bootstrap-vue/es/components'; 

Vue.use(Dropdown);
```

**Comment by tmorehouse** [comment]
Don't forget to include bootstrap's variables, functions and mixins, as well as bootstrap-vue's variable file.

**Comment by jackmu95** [comment]
@tmorehouse I think we can close this due to the progress of the current [Getting started](hhttps://deploy-preview-2315--bootstrap-vue.netlify.com/docs/#general) section of the docs.

**Comment by tmorehouse** [comment]
True.
