### ISSUE TITLE
b-form-radio-group: Using numeric values results in invalid prop type

### ISSUE THREAD

**Issue by sigmoidbigfoot** [bootstrap-vue/bootstrap-vue#1088]
This issue effects the latest version (1.0.0-beta.8/9), after the changes made to radio elements.

When supplying <b-form-radio-group> with an options array with numeric values, for example:

```
[
  { text: 'Last 7 days', value: 7 },
  { text: 'Last 14 days', value: 14 },
  { text: 'Last 30 days', value: 30 },
  { text: 'Last 90 days', value: 90 },
]
```

the b-form-radio-group Vue instance complains about an invalid type for prop "Checked":

```
vue.runtime.esm.js:472 [Vue warn]: Invalid prop: type check failed for prop "checked". Expected String, Object, got Number.

found in

---> <BFormRadioGroup>
```

Switching the values to strings resolves the warning, as expected, but it should also be possible to use radios to select between numeric values.

**Comment by hydraheim** [comment]
It seems this prop type should already be in master, as evidented by https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/form-radio-group.vue#L45

However, the result from beta-9 is the same, as stated by the original poster;

`[Vue warn]: Invalid prop: type check failed for prop "checked". Expected String, Object, got Number.`

**Comment by cpxPratik** [comment]
@hydraheim , MR may have been merged after beta-9 release so it's not tagged and released yet. See the label `Status: Coming Soon`.

**Comment by tmorehouse** [comment]
That is correct.  It will be available in release v1.0.0-beta.10

**Comment by JakePicton** [comment]
In a similar vein, should Boolean be added to the list of valid data types for the "checked" prop? I recently tried to use a <b-radio-group> to set up a Yes/No toggle where the model stored the value as true or false. I expected this to be fine, but obviously encountered the "type check failed" error.

`[Vue warn]: Invalid prop: type check failed for prop "checked". Expected String, Object, got Boolean. `

**Comment by tmorehouse** [comment]
For radio elements `true` and `false` would be tricky (although checkboxes work OK with `true` & `false` when using a single checkbox).

**Comment by JakePicton** [comment]
The UI element I'm trying to create is a Yes/No button group, which doesn't use a checkbox.

Why are Boolean values problematic? Ignoring the type check warning, my form seems to function as expected.

**Comment by tmorehouse** [comment]
Depending on how you are generating your checks/radios.  If manually placing them (using say b-form-radio), or using the options array/object of b-form-radios to generate your b-radio inputs.

The normalization routine converts options provided as objects, arrays, arrays of objects, into an internal array of object values.  It has to test various scenarios to normalize teh various accepted forms of options, so looking for Booleans explicitly adds a bit of complexity.

**Comment by JakePicton** [comment]
Aah, makes sense. I was manually placing the options with form-radio, but I can see how there could be added complexity if you're using the option array method.

I think I'll try to refactor my form model to avoid the Boolean values. It sounds like that's probably the best way forward. Cheers.

**Comment by RMoisiuk** [comment]
When this issue will be fixed ?

**Comment by tmorehouse** [comment]
We're just finalizing the latest release (v1.0.0), so hopefully soon.
