### ISSUE TITLE
pagination variant bug

### ISSUE THREAD

**Issue by excaliburhan** [bootstrap-vue/bootstrap-vue#109]
I set `pagination components` prop variant to `primary`, the expected active button background should be blue(primary).

I checked the devTools and find out it has `btn-secondary btn-primary` classes. And the `btn-secondary` covers the `btn-primary` style.

**Comment by pi0** [comment]
@excaliburhan Are you sure your are using latest `bootstrap-vue` package ? Online docs demo is using `danger` variant without any problems :)) ([See this page](https://bootstrap-vue.github.io/docs/components/pagination/))

**Comment by excaliburhan** [comment]
I use the bootstrap 4.0.0-alpha.6 style, and yep, `success`, `info`, `warning` and `danger`, I tested all those is ok, but `primary` wont work. That is because `.btn-secondary` is after `.btn-primary` and it will sure cover the primary style.

**Comment by pi0** [comment]
Hello @excaliburhan, This is now fully resolved in 0.8.0 release :) (Check out docs)

**Comment by excaliburhan** [comment]
@pi0 cool!

**Comment by master9270** [comment]
why bootstrap-vue paggination does not have vairant props
