### ISSUE TITLE
b-dropdown-item with 'to' prop always 'active' 

### ISSUE THREAD

**Issue by Alsciende** [bootstrap-vue/bootstrap-vue#1096]
In my project, I have the exact same navbar as here: https://jsfiddle.net/6boedp9t/

The dropdown items are active and I can't make them inactive. `:active="false"` doesn't change anything. I have no idea why, since the fiddle doesn't reproduce the problem. Any idea?

**Comment by tmorehouse** [comment]
https://jsfiddle.net/6boedp9t/1/

It might depend on your router settings and how the active route is matched to apply the active class.

If you view the rendered HTML in the browser inspector do you see any vue router active classes being applied?

**Comment by Alsciende** [comment]
I litterally copied the jsfiddle hmtl code in my project and the links were active (with an 'active' class). So there was nothing in my code that would have triggered the active class by mistake, or at least I don't see what.

**Comment by tmorehouse** [comment]
Are both dropdown items showing with the blue highlight?

**Comment by Alsciende** [comment]
Yes. But the interesting part is, when the dropdown-item is generated by a v-for, it's not active

Here is my actual code:

```
<b-dropdown-item :to="{name:'zfze'}">Toto</b-dropdown-item>
                    <b-dropdown-item :to="{name:'cards-by-default'}">All</b-dropdown-item>
                    <b-dropdown-item :to="{name:'cards-by-default'}">All</b-dropdown-item>
                    <b-dropdown-item href="#">All</b-dropdown-item>
                    <b-dropdown-item
                            v-for="pack in packs"
                            :key="pack.id"
                            :to="{name:'cards-by-pack-id',params:{id:pack.id}}">
                        {{ pack.name }}
                    </b-dropdown-item>
                    <b-dropdown-item :to="{name:'cards-by-default'}">All</b-dropdown-item>
```

Only the dropdown with a `:to` and not generated by `v-for` are active, and they are all active.

**Comment by tmorehouse** [comment]
Bootstrap-Vue doesn't directly apply the `active` class (unless you are using `v-b-scrollspy`), but Vue-Router is responsible for placing the active class based on the pages URL and the machting scheme of the route to the URL.

Try adding the router-link 'exact' prop to your dropdown items (https://bootstrap-vue.js.org/docs/reference/router-links)

**Comment by Alsciende** [comment]
Thanks, I'll try that. How is Vue-Router responsible for the active class?

**Comment by tmorehouse** [comment]
Yes, vue-router is normally responsible for applying the active classes when a `to` prop is set, and based on how route matching is applied (which triggers the active class).

**Comment by Alsciende** [comment]
Thank you, I didn't know about this feature of vue-router. All that was missing was the `exact` prop.

**Comment by hsowan** [comment]
Thank you, too
