### ISSUE TITLE
Popover does not work in IE 11

### ISSUE THREAD

**Issue by javiercbk** [bootstrap-vue/bootstrap-vue#110]
Popover uses the `includes` array method which is not supported in IE 11.

For browser compatibility it should be replaced by `indexOf`

**Comment by javiercbk** [comment]
I might be able to make a PR by monday, is it good enough?

**Comment by SirLamer** [comment]
Hi, I wrote this one so I'll address it.

pi0 - Is the base project compiler configured to perform a polyfill step? Or is ES6 not allowed in the project? Note I am aware (as of today) that Array.prototype.includes is from ES2016 and probably should be avoided in either case.

**Comment by SirLamer** [comment]
Fixed, pi0 when decide when to publish the next release but in the meantime if you want, you could use this specific commit instead: https://github.com/bootstrap-vue/bootstrap-vue/commit/d1c75acec68dd403a625de654f0c375075991554
