### ISSUE TITLE
Modal via modifier not working.  Via value is fine.

### ISSUE THREAD

**Issue by DavidRueter** [bootstrap-vue/bootstrap-vue#1100]
In beta 9:

Not working:  `<b-btn v-b-modal.myModal>Show Modal</b-btn>`
Works fine:  `<b-btn v-b-modal="'myModal'">Show Modal</b-btn>` 

See:  https://jsfiddle.net/drueter/t2fv4woy/3/

**Comment by tmorehouse** [comment]
I made a slight tweak and it does work, with one caveat.. the ID must be all lower case for the modifier to work

https://jsfiddle.net/t2fv4woy/4/

We'll have to investigate this a bit more

**Comment by tmorehouse** [comment]
Running this locally on my dev server, it works fine, so not quite sure what is going on.
