### ISSUE TITLE
Docs Form Radio Inputs

### ISSUE THREAD

**Issue by Alsciende** [bootstrap-vue/bootstrap-vue#1101]
Page https://bootstrap-vue.js.org/docs/components/form-radios

In the first code example, the second group of `b-form-radio-group` is using `b-form-radio` components, but it seems to me that it should be using `b-radio` components instead, as per the documentation above.

**Comment by tmorehouse** [comment]
`b-form-radio` is the "official" component name, but it is also available by the shorter alias `b-radio`

**Comment by tmorehouse** [comment]
I have updated the docs to reference full component name.  The updated docs will be available next release.
