### ISSUE TITLE
Modal cancel-title | close-title, Doc

### ISSUE THREAD

**Issue by angelowolf** [bootstrap-vue/bootstrap-vue#1104]
Hi folks, i try to use  prop the cancel-title as the documentation says and dont work, try with close-title and works. The documentation is fine or was not updated ?

**Comment by tmorehouse** [comment]
Which version of bootstrap-vue are you using?

**Comment by tmorehouse** [comment]
Version v1.0.0-beta.9 uses the prop `cancel-title`, which used to be `close-title` in older versions. Make sure you are using version v1.0.0-beta.9

**Comment by angelowolf** [comment]
My bad, i forgot to download the version 9, i was using v1.0.0-beta.7 instead
