### ISSUE TITLE
b-form-checkbox: react to click with modifier key

### ISSUE THREAD

**Issue by Alsciende** [bootstrap-vue/bootstrap-vue#1106]
I have a group of (button) checkboxes, and I want for them to act like radio buttons when a button is clicked with the alt key pressed: deselect all other options. I figured I would implement that myself, but I can't bind to `@click` on the `b-form-checkbox` element. Would you consider adding that feature to `b-form-checkbox-group` itself, or open a way to react to clicks at the `b-form-checkbox` level, before the value of `b-form-checkbox-group` is changed?

**Comment by tmorehouse** [comment]
So you are looking for a way to alter the behavior based on modifier keys (i.e. alt, meta, ctrl, etc)

Currently the `@change` event is fired when a user clicks/changes the checkboxes, with the first argument being the vale of the checkbox group (when listening on b-form-checkbox-group). When listening on individual checkboxes (b-form-checkbox component), the `@change` event contains the checkbox's value (or null if not checked anymore).

Unfortunately the native `change` event doesn't include any information about keypresses (unlike the click event)

We could see about implementing a click handler, and emit the native event on both the individual b-form-checkbox and bubble it to the b-form-checkbox-group

**Comment by tmorehouse** [comment]
If you listen to the `@click.native` on the b-form-checkbox-group, you would have access to the native event, although you will receive multiple click events (one for each element up the dom tree from the input element, to the label, to the group itself).  You would need to filter the event based on the target (i.e. `if (evt.target.tagName === 'INPUT') {...}`).  The click event gets fired before the `change` event does, so the value of the form-checkbox-group will not be set yet, but you do have access to `evt.target.checked` which will be true if the input is changing from unchecked to checked, and the internal value of the checkbox as evt.target._value, which will be the value you provided the the checkbox:

```html
    <b-form-checkbox-group id="checkboxes2" name="flavour2" v-model="selected">
      <b-form-checkbox @click.native="onClick" value="orange">Orange</b-form-checkbox>
      <b-form-checkbox @click.native="onClick" value="apple">Apple</b-form-checkbox>
      <b-form-checkbox @click.native="onCLick" value="pineapple">Pineapple</b-form-checkbox>
      <b-form-checkbox @click.native="onClick" value="grape">Grape</b-form-checkbox>
    </b-form-checkbox-group>
```

```js
methods: {
   onClick(evt) {
      // React only to the events fired from the `input`
      if (evt.target.tagName === 'INPUT') {
        if (evt.target.checked) {
           // Checkbox is being checked
           // the value that will be set is evt.target._value
        } else {
           // Checkbox is being un-checked
           // the value that will be unset is set is evt.target._value
        }
      }
   }
}
```

You could do something similar by listing to `@click.native` on b-form-checkbox-group, and just filter on vent targets that have `evt.target.tagName === 'INPUT'`

**Comment by Alsciende** [comment]
Thank you so much @tmorehouse . I was able to implement the feature in a very simple and elegant way by following your instructions.

**Comment by tmorehouse** [comment]
Glad you were able to get it working.
