### ISSUE TITLE
b-form-radio-group no events fired off on change

### ISSUE THREAD

**Issue by chevol** [bootstrap-vue/bootstrap-vue#1107]
I have been trying to get this to work since beta 7 and have opened a previous ticket. The change event seems to not be firing off when changing values on a radio group, or I am doing something wrong. Here is the code I am using:  
```
<b-form-radio-group id="rdoCal"
            buttons
            button-variant="primary"
            v-model="selCalView"
            @change="changeCalView" 
            v-on:change="changeCalView"
            :options="options"
            class="mb-4"></b-form-radio-group>
```

I tried using @change and @change.native as well as the vue v-on, and nothing is firing off the event.

**Comment by tmorehouse** [comment]
Have you tried v1.0.0.-beta.9?

This works for me:
```html
<template>
  <b-form-radio-group id="radios1"
                      buttons
                      @change="log"
                      v-model="selected"
                      :options="options"
                      name="radioOptions">
  </b-form-radio-group>
</template>

<script>
  export default {
    data: {
      selected: 'first',
      options: [
        { text: 'First', value: 'first' },
        { text: 'Second', value: 'second' },
        { text: 'Third', value: 'third' },
        { text: 'Fourth', value: 'fourth' }
      ]
    },
    methods:{
      log(arg) {
        console.log(arg);
      }
    }
  };
</script>
```
In the console, I see  the value logged as I click the radios.

**Comment by chevol** [comment]
Sorry, this is on v1.0.0.-beta.9. Just updated this morning to see if I can get the new radio groups working and no go so far.

**Comment by chevol** [comment]
Here is the code I am using for my Vue, everything seems to be correct.
```
<template>
  <div class="container-fluid page-content">
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              Adjust your settings
            </h4>
          </div>

          <div class="panel-body">

            <br>

            <h5>Select the default scheduer view</h5>
            <b-form-radio-group id="rdoCal"
            buttons
            button-variant="primary"
            v-on:change="changeCalView"
            @change="changeCalView"
            v-model="selCalView"
            :options="options"></b-form-radio-group>

            <br>

          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    staff:{
      type: Number,
      required: true
    },
  },
  data: function()
  {
    return {
      selCalView: '1',
      options: [
        { text: 'Month', value: '2' },
        { text: 'Agenda Week', value: '1' },
        { text: 'Basic Week', value: '4' },
        { text: 'Agenda Day', value: '3' },
        { text: 'Basic Day', value: '5' }
      ],
      settings: []
    }
  },
  mounted() {
    console.log('Staff Settings Vue component mounted.');
    axios.get('/settings/get').then(function(response){
      this.settings = response.data;
      this.selCalView = this.settings.defaultCalendarView.toString();
      console.log('Loaded user\'s settings');
    }.bind(this));
  },
  methods: {
    changeCalView: function(e){
      console.log('Changed cal setting ' + this.selCalView);
      axios.post('/settings/changeCalView',{'calViewId':this.selCalView}).then(function(response){
        new PNotify({
          title: 'Success',
          text: 'Your default scheduler view has been changed',
          icon: 'icon-checkmark3',
          type: 'success'
        });
      }.bind(this));
    }
  },
}
</script>

```

**Comment by tmorehouse** [comment]
Remove the duplicate listeners:

```html
            v-on:change="changeCalView"
            @change="changeCalView"
```

You should only need:
```html
            @change="changeCalView"
```
The first argument to `changeCalView` will the be value of your b-form-raidio-group

**Comment by chevol** [comment]
Sorry, I had both as I was debugging and going back and forth trying to see which one would work. Removing the v-on:change call and leaving the @change still results in no event being fired. I'm not sure whats going on but for the life of me and since beta 7, I have not been able to get any radio button event to fire. I can remove the buttons styling and it works, but looks ugly and I'd rather not go that route.

**Comment by chevol** [comment]
If I remove the buttons prop, then everything works fine and the event gets fired off as it should.

**Comment by tmorehouse** [comment]
I just did this mockup: https://jsfiddle.net/hpxz8k0w/
And using firefox, all works fine for me...

Which browser are you using?

**Comment by chevol** [comment]
I am using Chrome Version 61.0.3163.100

The mockup in jsfiddle works fine for me as well. Not sure what's going on but I did notice the color is different between the 2 so there might be some conflict somewhere in my project.

**Comment by haleksandre** [comment]
@chevol Have you figured it out?

I'm having the same issue. Everything works as it should if the radio-group is set to defaults or plain. As soon as I set it as buttons it breaks. v-model doesn't get bind as well as events aren't getting fired. I'm guessing events aren't getting fired since v-model isn't bind.

The components works fine in the jsfiddle but in my app something is conflicting with something else only when radio buttons are set as buttons.

**Comment by Qvatra** [comment]
same here. what causing these conflicts? any thought?

**Comment by guilhermejbranco** [comment]
`@change.native="changeCalView"`

**Comment by sokulski** [comment]
I'm still experiencing this, with radios set to the buttons style.

Any insight into what's going on?

**Comment by guccilive** [comment]
I'm facing the same issue as well.

**Comment by rassokhina-e** [comment]
> `@change.native="changeCalView"`

It's work and for https://buefy.org/documentation/radio events. Thank you!
