### ISSUE TITLE
b-card-img-lazy

### ISSUE THREAD

**Issue by bestpika** [bootstrap-vue/bootstrap-vue#1109]
Could `<b-card-img>` add lazy load support?
Thanks.

I use `<b-img-lazy class="card-img">` now.
But have some bug on mobile device.
Some image won't load when scroll.

**Comment by tmorehouse** [comment]
You could try and not use the "card-img" class, and just use b-img-lazy with the "fluid-grow", which causes the image to grow to 100% of the width (maintaining aspect) of the parent container. (i.e. <b-card no-body>`).

And see if it has the same issues as adding the class.

b-img-lazy has added overhead compared to the regular `b-img` (which is  functional component with no `this` context), so I would be hesitant to make it the default img component for b-card's

**Comment by tmorehouse** [comment]
Do you have similar issue on mobile with b-img-lazy when not placed inside a card?

**Comment by tmorehouse** [comment]
Try this:
```html
<b-img-lazy src="..." blank-coplor="#ccc" fluid-grow width="640" height="480" class="card-img">
```
Remember to set a width and height  (or blank-width amd blank-height) that matches your src image (or at least have similar aspect ratio).

**Comment by bestpika** [comment]
I set
```
<b-img-lazy class="card-img" fluid-grow :src="device.img" :alt="device.name" />
```
```
  .card-img {
    min-height: 100px;
  }
```
But some image still can't show.

**Comment by tmorehouse** [comment]
You should try to set an expected image size, either with the width & height (for the real image), or blank-height/blank-width for the placeholder image,

**Comment by bestpika** [comment]
I try this, but not work, too.
`<b-img-lazy class="card-img" :src="device.img" :alt="device.name" blank blank-color="#ccc" blank-width="100%" blank-height="100px" />`
![image](https://user-images.githubusercontent.com/5698157/31043717-a0b6a4b8-a5f3-11e7-8caf-5ae9dc7505ac.png)

**Comment by tmorehouse** [comment]
`blank-width` and `blank-height` should be numbers (without the `px`)

I've tried this markup and it works as expected (I av set the offset value to 0px so that the load is easier to see happening when scrolling):

```html
<template>
    <b-card no-body
            style="max-width: 20rem;"
>
        <h4 slot="header">Hello World</h4>
        <b-img-lazy src="https://placekitten.com/480/210"
                    blank-color="#fff"
                    blank-width="480" blank-height="210"
                    class="card-img card-img-top"
                    alt="Image" offset="0"
                    />
        <b-card-body>
            <p class="card-text">
                Some quick example text to build on the card title
                and make up the bulk of the card's content.
            </p>
        </b-card-body>
        <b-img-lazy src="https://placekitten.com/480/210"
                    blank-color="#fff"
                    blank-width="480" blank-height="210"
                    class="card-img card-img-bottom"
                    alt="Image" offset="0"
                    />
    </b-card> 
</template>
```

**Comment by digitalgym** [comment]
Does b card img-top support lazy loading? It's not mentioned in the docs 
<b-card
      title="Card title that wraps to a new line"
      img-src="https://placekitten.com/g/400/450"
      img-alt="Image"
      img-top
    >

**Comment by tmorehouse** [comment]
You need to manually place a `b-card-img-lazy` inside the `b-card`

**Comment by digitalgym** [comment]
How do we add the image as top? Adding the lazy component to <b-card add the image to the card body, not the outer element? 

<b-card :title="content.title" header-tag="header" footer-tag="footer">
<b-card-img-lazy top="true" :src="content.image" class="card-img-top">

**Comment by tmorehouse** [comment]
You would need to create the card structure as follows:

```html
<b-card no-body>
  <b-card-img-lazy :src="content.image" top></b-card-img-lazy>
  <b-card-header tag="header">Heading here</b-card-header>
  <b-card-body :title="content.title">Body Content Here</b-card-body>
  <b-card-footer tag="footer">Footing here</b-card-footer>
</b-card>
```
