### ISSUE TITLE
Tabs show/hide events

### ISSUE THREAD

**Issue by aaroniker** [bootstrap-vue/bootstrap-vue#1110]
Hi,
first of all thanks for this helpful project :)

Is there a way to get `hide.bs.tab` and `show.bs.tab` to work?
I just tried with jQuery at the `created() {}` block of vuejs.

Thanks!

**Comment by tmorehouse** [comment]
Bootstrap-Vue doesn't use jQuery, nor the jQuery namespaced events.

In the case of tabs, you can watch your v-model to see which tab is open, or listen to the `@input` event on the b-tabs  component.  The event received one argument, which is the index of the tab being shown.

**Comment by aaroniker** [comment]
ok thanks very much :)
would be cool if vue-bootstrap fires $emit event for show & hide

**Comment by tmorehouse** [comment]
We may implement show/shown/hide/hidden events in the future, emited both on the b-tab and b-tab component, as well as $root namespaced events.

**Comment by P4R4DiSi4C** [comment]
Hello,

Any news on this query ?

Regards
