### ISSUE TITLE
Navbar b-nav-item disabled

### ISSUE THREAD

**Issue by Soraia55** [bootstrap-vue/bootstrap-vue#1111]
Hi! I'm using bootstrap-vue on version 0.23.0 and bootstrap on version 4.0.0-alpha.6. I'm facing an issue in my code. 
So, I have a component with a navbar and a form input like this:

```
<b-navbar toggleable type="inverse" variant="success">
   <b-nav-toggle target="nav_collapse"></b-nav-toggle>
   <b-link class="navbar-brand">
      <span>&nbsp</span>
    </b-link>
    <b-collapse is-nav id="nav_collapse">
         <b-nav is-nav-bar class="ml-auto">
             <b-nav-item to='/' exact @click="change_layout"> Home </b-nav-item>
             <b-nav-item to='/about'> About </b-nav-item>
	     <b-nav-item to='/contacts'> Contacts </b-nav-item>
	     <b-nav-item v-b-modal.modallogin> Add Speech </b-nav-item>
         </b-nav>
    </b-collapse>
</b-navbar>

<b-form-input id="search-box" v-model="query" lazy-formatter @keyup.once="set" @keyup.enter="send_query" autofocus> </b-form-input>
```
What is happening is that when the event @keyup.once is emitted on the input, the b-nav-items don't work. Even if I set all of them to active, when the event is emitted it's not possible to click on them. Everything works fine if that event isn't emitted. The only thing I'm doing on "set" is setting a variable to true (that doesn't have anything to do with the navbar component).

Hope someone can help me! 
Thanks in advance

**Comment by tmorehouse** [comment]
Could you provide a sample of your code that goes along with the above markup?

**Comment by Soraia55** [comment]
It seems I was hiding the content of a container and it would get on top of the navbar, making it not to work.
Well, thank you anyway!
