### ISSUE TITLE
Tooltip & Popover doesn't handle numbers well

### ISSUE THREAD

**Issue by stranger26** [bootstrap-vue/bootstrap-vue#1117]
When using Tooltip & Popover (both directives and components) in v-for, I passed in Number instead of String, it only displayed the first Tooltip/Popover.

Problem fixed by converting Number to String.

Just thought I'll put it here in case anyone is facing the same problem.

**Comment by tmorehouse** [comment]
Could you provide a sample of your markup, and which property or value you are setting to a number?

**Comment by tmorehouse** [comment]
Closing this due to lack of details provided.
