### ISSUE TITLE
(breadcrump) Active = false is ignored for item

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#1118]
If you look at the live example on the docs page: https://bootstrap-vue.js.org/docs/components/breadcrumb and change the `active: true` to `active: false` I would expect that the `Library` item would become clickable. 
Unfortunately this is not the case, I can reproduce this in my own app with v1.0.0-beta.9.

**Comment by alexsasharegan** [comment]
Breadcrumb currently works under the assumption that there is one active link in every set of ordered breadcrumbs. This list item represents the current page, and is therefore not clickable. This aligns with the bootstrap "spec" shown here: https://getbootstrap.com/docs/4.0/components/breadcrumb/.

While I don't think we will be inclined to support alternative use-cases for breadcrumbs, we have built the breadcrumb components modularly to allow for this kind of customization. Take a look at this example:

```html
<template>
  <b-breadcrumb>
    <b-breadcrumb-item
      v-for="item in items"
      v-bind="item"
      :key="JSON.stringify(item)"
    />
  </b-breadcrumb>
</template>

<script>
  export default {
    data: {
      items: [{
        text: 'Admin',
        href: '#',
      }, {
        text: 'Manage',
        href: '#',
      }, {
        text: 'Library',
        active: false
      }]
    }
  }
  </script>
```

This can be pasted into the live editor to render your desired results.

**Comment by pimlie** [comment]
Thanks, can confirm the workaround works for me too
