### ISSUE TITLE
tabindex bug in b-button

### ISSUE THREAD

**Issue by jvukovich** [bootstrap-vue/bootstrap-vue#1119]
We need to be able to set the tabindex on inputs for a special case.

However, it doesn't look like this is possible?
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/button.js

Would it be possible to add something that would allow us to pass any HTML attribute we want, so we're not limited to the Vue component's attributes? We may likely need to support some non-standard HTML attributes to act as shim during a project conversion as well.

Maybe something like?
`<b-btn :customHtmlAttrs="[{name: 'tabindex', value: '11'}, {name: 'myShimAttr', value: 'myShimVal'}]"></b-btn>`

Renders:
`<button tabindex="11" myShimAttr="myShimVal"></button>`

**Comment by tmorehouse** [comment]
Any attribute that isn't a prop will be placed directly on the root element of the component (this is controlled by Vue)

To set tab index use the HTML attribute `tabindex="#"` (all lowercase)

**Comment by jvukovich** [comment]
Ahh okay, cool. Thanks!

It does not appear to be working for buttons right now, then:
`<b-btn size="sm" variant="primary" tabindex="99">Test</b-btn>`

Is rendering:
`<button type="button" class="btn btn-primary btn-sm">Test</button>`

**Comment by tmorehouse** [comment]
b-button uses b-link as it's base, so there might be an issue (and b-link will sometimes set tabindex="-1" when a link is rendered, to take it out of the tab sequence as links don't normally support the disabled prop)

Which version of Bootstrap-Vue are you using?

**Comment by tmorehouse** [comment]
I see where it is happening in the b-button code: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/button.js#L92-L103

It is setting tabIndex to either -1 (disabled) or null if not disabled.

We'll have to pull out the original tabindex from the passed data and use it rather than setting null.

**Comment by jvukovich** [comment]
1.0.0-beta.7. Looks like I should upgrade, did not notice it's at .9 now. Awesome, thanks much! Great project man!

**Comment by tmorehouse** [comment]
This has been fixed via PR #1120 and should be available in the next release.
