### ISSUE TITLE
How to use table with pagination after 0.8.0?

### ISSUE THREAD

**Issue by rheicide** [bootstrap-vue/bootstrap-vue#112]
The official example [here](https://bootstrap-vue.github.io/docs/components/tables) has stopped working:
```html
<b-table :items="items" :fields="fields" pagination :perPage="3">
...
</b-table>
```

Which seems to be expected as all pagination-related stuff has been removed from `table.vue` in commit 0d3f745.

What is the correct way now to add pagination to table?

**Comment by pi0** [comment]
@rheicide Hello, and sorry for inconveniences happened due changes. I tried to keep components as simple as possible and do only one thing, so one can customize and compose them anyway he likes. You can view [tables example source code](https://github.com/bootstrap-vue/bootstrap-vue/tree/master/docs/pages/docs/components/tables.vue) which demonstrates pagination too. 

**template**
```html
<b-table :items="items" :fields="fields" :current-page="currentPage" :per-page="perPage" />
<b-pagination :total-rows="items.length" :per-page="perPage" v-model="currentPage" />
```

**js**
```js
data() {
  return {
     items: [....],
     currentPage: 1,
     perPage: 5
 }

}

```

**Comment by rheicide** [comment]
Thanks a lot for your fast response @pi0 !

Yeah, I should have looked into the example source code before opening this issue.

Anyway, it would be great if you can update the documentation of table to reflect the change (the Usage section for example).
