### ISSUE TITLE
Problem with sub dependencies after doing npm install

### ISSUE THREAD

**Issue by art-mironoff** [bootstrap-vue/bootstrap-vue#1121]
Hi guys,
I have a problem. I'm doing `npm install` and after I try to start the project with `npm start` I get the following error:
```
Failed to compile with 2 errors                                                                                                                                          00:08:40

These dependencies were not found:

* vue-functional-data-merge/dist/lib.common.js in ./~/bootstrap-vue/lib/utils/index.js
* popper.js in ./~/bootstrap-vue/lib/mixins/dropdown.js

To install them, you can run: npm install --save vue-functional-data-merge/dist/lib.common.js popper.js
> Listening at http://localhost:8080
```

After the investigation, I found that the `node_modules/bootstrap-vue/node_modules` folder does not exist. If I go to the `node_modules/bootstrap-vue` folder and do `npm install` in this folder, I get an error: 
```
sh: 1: build/build: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bootstrap-vue@1.0.0-beta.9 build: `build/build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bootstrap-vue@1.0.0-beta.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
This error is not critical and the project can be started with `npm start`.

Can someone help me, why are sub dependencies not installed without manual installation?

My package.json dependencies:
```
"dependencies": {
  "bootstrap": "4.0.0-beta",
  "bootstrap-vue": "^1.0.0-beta.9",
  "chart.js": "^2.7.0",
  "vue": "^2.4.2",
  "vue-chartjs": "^2.8.7",
  "vue-moment": "^2.0.2",
  "vue-router": "^2.7.0"
}
```

My Node version: v8.5.0
My NPM version: 5.4.2
My OS: Linux Mint

**Comment by alexsasharegan** [comment]
Are you compiling from source? These dependencies are included in the build files. If you want to compile from the source files, you'll have to install the dependencies mentioned.

```bash
npm i vue-functional-data-merge popper.js
```

**Comment by art-mironoff** [comment]
@alexsasharegan Problem was in direct importing for each component

```
import { bContainer, bRow, bCol } from 'bootstrap-vue/lib/components'
```

After removing this row all began work perfect. Thanks.
