### ISSUE TITLE
onChange with b-form-select

### ISSUE THREAD

**Issue by ottz0** [bootstrap-vue/bootstrap-vue#1122]
I have a button that I need to disable every time a new value is passed with b-form-select

So i'm trying to run a function that disables the button by setting a data object to false, however it does not work with b-form-select. 

**This does not work**
```
<b-form-select v-model="selectName"
             @change="myFunc()" 
             :options="selectNameOptions"
            size="lg"
            class="mb-3">
</b-form-select>
```
**This works**
```
<select v-model="selectName" @change="myFunc()">
<option disabled value="">Please select one</option>
<option>A</option>
<option>B</option>
<option>C</option>
</select>
```

**Comment by ottz0** [comment]
I have just seen issue #660 

I have updated my code to which seems to work

```
<b-form-select v-model="selectName"
 @change.native="tt()" 
:options="selectNameOptions"
size="lg"
 class="mb-3">
</b-form-select>
```

**Comment by tmorehouse** [comment]
You shouldn't place parens on your function when passing it to `@change`. use `@change="tt"` in stead of `@change="tt()"`

**Comment by ottz0** [comment]
Should I have a computed property then instead of a method then?

**Comment by tmorehouse** [comment]
Computed wont work...  You need to pass the function reference to the event, so my not adding `()`, this way you will receive, as the first argument to your method, the value of the select.

**Comment by dhanyn10** [comment]
> Computed wont work... You need to pass the function reference to the event, so by not adding `()`, this way you will receive, as the first argument to your method, the value of the select.

@tmorehouse can you give example?
