### ISSUE TITLE
Bug in b-form-input with v-model.lazy

### ISSUE THREAD

**Issue by phil-eepos** [bootstrap-vue/bootstrap-vue#1125]
Hi,

using v-model.lazy has no impact when using it with b-form-input component.

The following code shows the problem:

`<b-form-input type="text" v-model.lazy="name" />`
`<input type="text" v-model.lazy="name" />`

Editing the text in the b-form-input updates on every input event. The normal input component works as expected.

**Comment by tmorehouse** [comment]
The `.lazy` modifier is intended for native input element events (triggering on the native `change` event rather than the native `input` event.

**Comment by phil-eepos** [comment]
Is it planned to support the lazy feature in the b-form-input component or would you suggest that I switch to the native input element?

**Comment by tmorehouse** [comment]
This would be a Vue issue, as it defines how the model is updated on custom components (which defaults to `input`).

We do $emit a `change` event on the component.  You can listen for that event and update your local copy of it.

```html
<template>
  <b-form-input type="text" :value="name"  @change="updateName" />
</template>
<script>
export default {
  data() {
    return {
      name: ''
    }
  },
  methods: {
    updateName(value) {
      this.name = value;
    }
  }
}
</script>
```
