### ISSUE TITLE
how to connect the method to get data

### ISSUE THREAD

**Issue by Jussiadev** [bootstrap-vue/bootstrap-vue#1126]
Sorry for the very stupid question, but how to connect the method `pageNext` to retrieve data

```html
<template>
    <div class="content_catalog">
        <div class="top_block">
            <div class="bread">Бренды</div>
        </div>
        <div class="brand_grid">
            <div class="brand middle" v-for="good in brends">
                <nuxt-link :to="'/brend/'+good.id">
                    <div class="img"><img class="goodsDetail" :src="good.logo" :alt="good.title"></div>
                    <div class="title">{{good.title}}/ {{good.id}}</div>
                    <div class="kol">{{good.product_count}}</div>
                </nuxt-link>
            </div>
            <b-pagination-nav :link-gen="linkGen" :number-of-pages="10" v-model="currentPage" />
            <br>
        </div>
    </div>


</template>

<script>
    import axios from 'axios'
    import $ from 'jquery';

    const api = 'http://core-rest.evgarik.ru/api/brends';
    let currentOffset = 6,
        limit = 1,
        lim = 6,
        step = 1;
    export default {
        name: 'Catalog',
        data() {
            return {
                brends: [],
                currentPage: 3
            };
        },
        methods: {
            pageNext (pageNum) {
                axios.get(api, {
                    params: {
                        town_id: 1,
                        offset: currentOffset,
                        limit: limit
                    },
                }).then((data) => {
                    currentOffset += lim;
                    if (data.data.data.length) {
                        this.brends = data.data.data;
                        $('#preview-buttons button').hide();
                    } else {
                        $('#preview-buttons button').show();

                    }
                });
            },
            linkGen(pageNum) {
                return {
                    path: '/brends/' + pageNum
                };
            }
        },
        beforeCreate: function () {
            this.$nextTick(function () {
                axios.get('http://core-rest.evgarik.ru/api/brends', {
                    params: {
                        town_id: 1,
                        offset: 0,
                        limit: 4
                    },
                }).then((res) => {
                    this.brends = res.data.data;
                })
            })
        },



    }
</script>
```

**Comment by tmorehouse** [comment]
Since it appears you are using nuxt as your platform, so use the `asyncData` feature in your `page/*.vue` files to retrieve that.

Pagination nav, since you are returning an object in your linkGen function, will generate router links.  Your routes will change when someone clicks one of ht pagination control buttons.

**Comment by Jussiadev** [comment]
@tmorehouse Yes, I use the `nuxt`, but apply the pagination to the component. Therefore I can not use `asyncData`. I use the store `vuex` for data. I correctly understand that I do not need to use the method, but everything that I have inside the method I have to put into the function `linkGen`?

**Comment by Jussiadev** [comment]
@tmorehouse Thanks, I figured that out. but there is another problem. Why then do not display the numbers of pagination. (the same code)
![2017-09-28 18 13 36](https://user-images.githubusercontent.com/26526753/31055042-1fb18f7a-a6c7-11e7-8b47-124e71b091fc.png)

**Comment by tmorehouse** [comment]
pagination-nav should create automatic page numbers (starting from one and working up to the value passed to `:number-of-pages` 

You can override the displayed page number generation via the `pageGen` function.  It it called for each displayed page button, and is passed a single argument with is a number from 1 to `number-of-pages`.

**Comment by Jussiadev** [comment]
@tmorehouse  But I do not need to override the value of pagination. I need to have just numbers. Here so at me now function looks

```
linkGen(pageNum) {
                return {
                    path: '/brends?page=' + pageNum
                };
            },
```

It is interesting that the number of pagination is displayed in the browser console.
![2017-10-02 14 15 13](https://user-images.githubusercontent.com/26526753/31075140-c3d77adc-a77c-11e7-9cc2-e5ee1e1dd28a.png)


And one more question. My API returns the number of products, I need to show them by 7. I created a variable that calculates the number of pages I need, but I do not know how to transfer it to the `number-of-pages` now

**Comment by tmorehouse** [comment]
Take a look at the `pagination` component source code for how the internal number of pages value is computed.

If the number is in the rendered DOM markup, but not showing on screen, then you most likely have a CSS styling conflict.

**Comment by Jussiadev** [comment]
@tmorehouse Thank you so much. And how to change the color of the page of the current page

**Comment by tmorehouse** [comment]
Setting :css="false" on components will most likely disable all native bootstrap styling, which will break layout.
