### ISSUE TITLE
API-URL

### ISSUE THREAD

**Issue by iagocavalcante** [bootstrap-vue/bootstrap-vue#1127]
Hey guys, i can't use api-url in b-template and i can't find any example teaching how to use it.

**Comment by tmorehouse** [comment]
API-URL is not directly used by b-table, it is simply passed to your provider function via the `context` (`ctx`) object passed to the provider function.

**Comment by iagocavalcante** [comment]
Thank you, this was very helpful!

**Comment by frencius** [comment]
Hi!..
Are there any examples that explain usage of api-url prop on b-table? Thanks in advance.

**Comment by tmorehouse** [comment]
It isn't used by b-table. It is transparently passed as a property in the context object to your item provider function.
