### ISSUE TITLE
Alerts dismissed lose their $refs value

### ISSUE THREAD

**Issue by xorbis** [bootstrap-vue/bootstrap-vue#1128]
I have a single file vue. And I call the alert() method of a custom child component based on b-alert.

Once the b-alert is automatically dismissed after a delay (ie: :show="5") the ref becomes undefined and subsequent calls to alert() fail with this message.

`TypeError: Cannot read property 'alert' of undefined`

Because this.$refs.clientAlert becomes undefined.
If I use the simpler :show="[boolean]" also happens if the user clicks the dismiss button.

I imagine the DOM is removed when the alert is dismissed and the ref is lost.
Your b-alert example somehow works.

My parent template:
`<lf-alert ref="clientAlert"/>`

Inside a parent method, I do:
`this.$refs.clientAlert.alert("Hello world"));`

The child component:
```
<template>
	<b-alert :variant="variant" dismissible :show="show" @dismissed="show = false">{{message}}</b-alert>
</template>

<script>
    export default {
        name: "alert",
		data() {
			return {
				id: "",
				show: false,
				variant: "success",
				message: null
			};
		},
		methods: {
			alert(message, icon = "info", variant = "info") {
				this.message = message;
				this.variant = variant;
				this.show = 3;
			}
		}
	};
</script>
```

**Comment by tmorehouse** [comment]
B-alert is `v-if`ed out of the DOM when not shown, which is why the $ref to it disappears.

You need to use the v-model to control showing of it.

Since b-alert is th root element of your template, your element (and all it's refs) will also disappear.

Wrap b-alert with a div in your template to make a new root element that doesn't get v-iff'ed out of the DOM.

**Comment by xorbis** [comment]
Yep wrapping the whole component in a div inside it's template did the trick.
Thanks.

**Comment by travisstaloch** [comment]
I was able to reuse mine by only changing `:show="alert.show"` to `v-model="alert.show"` and when I reset `alert.show`, to something > 0, it works as expected, auto-hiding after `alert.show` seconds.  

In my use case, i already had wrapped the alert in a div within my component and was noticing that I couldn't reuse it until I switched to using v-model.
