### ISSUE TITLE
b-tooltip: support "show" and "hide" delays

### ISSUE THREAD

**Issue by epicyclist** [bootstrap-vue/bootstrap-vue#1130]
"delay" functions as a single number that applies to both showing and hiding. Can you support these separately? Bootstrap allows a number or an object in the format of `delay: { "show": 500, "hide": 100 }`.

**Comment by tmorehouse** [comment]
If using the `v-b-tooltip` and `v-b-popover` directives, you can pass a config object that allows you to specify both show and hide delays.

**Comment by robinmacharg** [comment]
Google brought me here; just wanted to leave an explicit example of the syntax: `:delay="{show: 1000, hide: 100}"` is the attribute to add to the `<b-tooltip>` (or popover) tag.  `delay="{...}"` without the object binding colon syntax will be interpreted as a string and use the default values of zero for both.
