### ISSUE TITLE
navbar with visible collapse: opens/close twice on page load

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#1132]
If you load the following example in the docs playground, you will notice that the `I should start open!` paragraph will show two close/open animations after each other on page load. Dont think it is meant to do this. When you copy the example in the playground it probably animates just once (which is also wrong I guess), but if you reload the page it animates twice.

If you remove the `toggleable` property for `b-navbar` the animation is not shown.

```html
  <b-navbar toggleable="lg">
      <b-btn v-b-toggle.collapse3>Toggle Collapse</b-btn>
      <b-collapse is-nav visible id="collapse3">
        <p>I should start open!</p>
      </b-collapse>
  </b-navbar>
```

**Comment by tmorehouse** [comment]
The visible prop probably shouldn't really be used on `<b-collapse>` when used in navbars,, as `<b-collapse>` when `is-nav` is set will monitor the visibility state of itself (based on computed CSS style for the break-point).

We should probably disable/ignore this `visible` prop when in `is-nav` mode.
