### ISSUE TITLE
Docs > Navbar > Missing informations about "b-nav-toggle"

### ISSUE THREAD

**Issue by Masterchoc** [bootstrap-vue/bootstrap-vue#1133]
The `b-nav-toggle` is just missing a bit of informations about the order in the dom, to the position attribute is able to work. Indeed, it has to be after the `<b-navbar-brand>` if you use position "right" in order to work !

Weird behavior.

**Comment by tmorehouse** [comment]
We have updated the navbar docs a bit, which will be available in the next release.
