### ISSUE TITLE
[Question] Do we have future plan for non Twitter Bootstrap  component?

### ISSUE THREAD

**Issue by donPuerto** [bootstrap-vue/bootstrap-vue#1134]
bootstrap-vue is an awesome framework, but of course, there were other components is useful besides from conventional Bootstrap component.

**Comment by tmorehouse** [comment]
Bootstrap-Vue's main intent is to provide the standard Bootstrap V4 components as custom Vue components.

However, there is nothing stopping you from using other Vue 2.x custom components with Bootstrap-Vue.

See also: https://github.com/bootstrap-vue/bootstrap-vue/issues/417

**Comment by donPuerto** [comment]
@tmorehouse Thanks...
