### ISSUE TITLE
[bug] v-b-popover.click.blur doesn't work

### ISSUE THREAD

**Issue by askz** [bootstrap-vue/bootstrap-vue#1136]
Hi,
I'm using bs-vue with fullcalendar and portal-vue. I want to show more details when an user click on events with popovers. I'm kind of hacking fullcalendar & portal-vue for making this work.
The problem is that popovers do not hide when other are already visible...
You can see what's up there : https://github.com/askz/bootstrap-vue-bug

Any suggestions ?
Thanks !

**Comment by tmorehouse** [comment]
in your markup:

```html
      <div style=""
          class="event-description"
           v-b-popover.click.blur="event.title"
           container="calendar"
           title="Popover!"
           variant="primary">
        {{event.title}}
</div>
```

You are placing a popover on a non-focusable element (a `<div>`), which will not trigger a blur event.

Add a `tabindex` to your `<div>` to allow it to gain focus when clicked:

```html
      <div style=""
          tabindex="0"
          class="event-description"
           v-b-popover.click.blur="event.title"
           container="calendar"
           title="Popover!"
           variant="primary">
        {{event.title}}
</div>
```

**Comment by askz** [comment]
Please try it, I already tested that...

**Comment by tmorehouse** [comment]
Pasting the following code into the [Bootstrap-Vue playground](https://bootstrap-vue.js.org/play) works as expected:

```html
<div tabindex="0"
     class="event-description"
     v-b-popover.click.blur="'content'"
     title="Popover!">
  Foo
</div>
```

**Comment by jeanlamy** [comment]
@tmorehouse many thanks for it. It has saved my day :)

Maybe that's something that should be in the docs?
