### ISSUE TITLE
b-table :fields converts <th>'s to a-z

### ISSUE THREAD

**Issue by tarreislam** [bootstrap-vue/bootstrap-vue#1142]
Hello!

I noticed that if you use the custom `:fields="data"` binding on the `<b-table>` tag, the "special chars" are stripped, is that done for any special reason?

Example:

```
<script>
  export default {
    name: 'contacts',
    data: function () {
      return {
        contacts: {
          fields: ['teståäöèò'], /// testaaoeo
          items: [{...}]
        }
      }
    }
  }
</script>
```

/Tarre

**Comment by tmorehouse** [comment]
It appears that `lodash.startcase` converts all special chars to their base letter: https://github.com/lodash/lodash/issues/3242

`_.startcase` is used to normalize the field names (converting kebab-case, camelCase, etc, into more "human" friendly labels.

They are expecting release v5 of lodash/startcase to fix this issue.

**Comment by tarreislam** [comment]
Okay, then ill wait, thanks.

**Comment by tmorehouse** [comment]
We might be able to make a work-around in b-table, where startcase is only used if no explicit label is given in the fields definition.

**Comment by tmorehouse** [comment]
Actually, if you use the longer form field definition, you can avoid the startcase conversion:

```html
<script>
  export default {
    name: 'contacts',
    data: function () {
      return {
        contacts: {
          fields: [{ key: 'teståäöèò', label: 'teståäöèò' ], // Array of objects
          // or
          fields: { 'teståäöèò': { label: 'teståäöèò'} }, // Object of objects
          // or
          fields: { 'teståäöèò': 'teståäöèò' }, // Label shortcut object
          items: [{...}]
        }
      }
    }
  }
</script>
```

**Comment by tarreislam** [comment]
Thanks for the help.
