### ISSUE TITLE
Docs- Table - Row Template -value or item?

### ISSUE THREAD

**Issue by runxc1** [bootstrap-vue/bootstrap-vue#1143]
In the docs it shows how to create a table cell template and if you edit it to the following 
<template slot="name" scope="row">{{row}}</template>

you will see that the data for the row is in the row.value property however when I do the same using the released Beta.9 the data is in the row.item property.  Are the docs not using the .9 version or is this an update that is going to made?

**Comment by mosinve** [comment]
There's both `data` and `item` properties at scope slot variable (named `data` in example)
As written in docs:

> **item**  - The entire raw record data (i.e. items[index]) for this row (before any formatter is applied)
> **value** - The value for this key in the record (null or undefined if a virtual column), or the output of thr field's formatter function (see below for for information on field formatter callback functions)
