### ISSUE TITLE
b-button href inhibits @click

### ISSUE THREAD

**Issue by drzraf** [bootstrap-vue/bootstrap-vue#1146]
The DOM behavior is to always execute `onClick` and then possibly follow `href` (if `onClick` didn't return false).
Using a  `<b-button href="#" @click="foo">`, `foo()` is never executed. It is if `href` is removed.
Documentation is sparse about this and didn't let know how it's expected to behave.

**Comment by tmorehouse** [comment]
Don't specify `href` if you are wanting button functionality.  Buttons with an `href` of `#` will prevent scroll to top behavior (as they re rendered as an `a` tag rather than `button` tag.


.

**Comment by drzraf** [comment]
but that's the only way that I know have two things I'm looking for:
- hand cursor
- no scroll-to-top behavor
... or would you advise that I rather add a `style="cursor..."` attribute?

**Comment by tmorehouse** [comment]
I would suggest `style="cursor: pointer"`

Bootstrap V4.beta has removed all "hand cursors" from anything that isn't a link, to match native browser functionality

Buttons are best suited (specifically for W3C ARIA compliance) when navigation isn't involved.

**Comment by tmorehouse** [comment]
You can also listen for `@click.native`, which returns the native JavaScript event (rather than the Vue custom event).

https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components

**Comment by philBrown** [comment]
FYI, adding the `.native` modifier does not make any difference. The click event is not propagating outside the component due to the implementation of `Link`

**Comment by emanuelmutschlechner** [comment]
Check this link: [buttons shouldn’t have a hand cursor](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b)
