### ISSUE TITLE
b-collapse horizontal direction

### ISSUE THREAD

**Issue by arnoldtkl** [bootstrap-vue/bootstrap-vue#1148]
Is it possible to change the collapse direction to horizontal?

Example: https://www.codeply.com/go/UiteY92ke8/bootstrap-4-horizontal-collapse-animation

**Comment by tmorehouse** [comment]
Currently BS-Vue uses the Bootstrap V4.beta CSS.

It appears that code-pen i just adding additional CSS transition classes, and not altering the actual Transition collapse plugin.  So you could probably just use that CSS in your project to make a vertical collapse.

**Comment by arnoldtkl** [comment]
Thank you.

**Comment by goldenram** [comment]
I pulled the codepen code into my bootstrap-vue project, and I see the vertical working just like it is on the codepen example however the horizontal just does a show/hide without any smooth animation.  The only code changes I made were to the html to get the bootstrap-vue code.  Is it possible this is a JS issue?  Would you mind taking a quick look to see if you can reproduce?

Changes I made are below for the horizontal example:

<div class="col-md-6">
    <b-btn v-b-toggle.demo role="button" class="btn btn-danger" aria-expanded="true">horizontal collapsible</b-btn>
     <b-collapse id="demo" class="width collapse show" aria-expanded="true">
           <div class="list-group" style="width: 400px;">
                  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                   <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
      </b-collapse>
</div>
