### ISSUE TITLE
Tooltips events

### ISSUE THREAD

**Issue by KonradDeskiewicz** [bootstrap-vue/bootstrap-vue#1149]
Hi 
Not sure if this documentation error or implementation error but events are described as:

`bv::tooltip::[action]`

when in fact there is no "i" in "tip" and all events looks like this 

`bv::tooltp::[action]`

I've stumbled upon this issue when tried to close one stubborn tooltip trough emitting event.

**Comment by tmorehouse** [comment]
Which version of bootstrap-vue are you using?

**Comment by tmorehouse** [comment]
Events `bv::tooltip::[action]` are emitted by tooltips, while `bv::[action]::tooltip` are used to control tooltips via other components/apps.

To close all tooltips, emit the event `bv::hide::tooltip` on `$root` to force hide all opened tooltips.

**Comment by KonradDeskiewicz** [comment]
I'm using bootstrap-vue@1.0.0-beta.9

This is issue on both cases. 
I neded to emit 'bv::hide::tooltp' to force close tooltips.

![tooltp](https://user-images.githubusercontent.com/17060750/31130122-cb61d98e-a856-11e7-85c5-f91aa487bf9c.png)

**Comment by tmorehouse** [comment]
Ah, this was fixed in https://github.com/bootstrap-vue/bootstrap-vue/pull/1094, which hasn't been released yet. But will be available in the next release.
