### ISSUE TITLE
change css

### ISSUE THREAD

**Issue by Jussiadev** [bootstrap-vue/bootstrap-vue#1151]
how to change the color of the page of the current page. Also I made a css: false as if I do not do it, my styles do not work. However, after that, the pagination looks a bit wrong 
![2017-10-03 0 13 03](https://user-images.githubusercontent.com/26526753/31125434-f6bb6650-a850-11e7-8f7b-4862a0c0ec2a.png)

**Comment by tmorehouse** [comment]
The CSS used is the official Bootstrap V4.beta CSS.

You can customise their CSS: https://getbootstrap.com/docs/4.0/getting-started/options/

Setting `:css="false"` on components will most likely disable all native bootstrap styling, which will break layout.

**Comment by tmorehouse** [comment]
Also, if you view the generted HTML DOM in your browser's DEV tools, you will see that there is a class called `active` applies to the current page indicator.  You can write your own CSS to override this default styling.

**Comment by Jussiadev** [comment]
@tmorehouse And whether it is possible as that separately to load styles which concern only pagination. I also use a bootstrap on the project, that's why conflicts

**Comment by tmorehouse** [comment]
pagination components have the class `pagination` on their root element.

target the active page like this:

```css
.pagination .active {
  background-color: purple;
}
```
