### ISSUE TITLE
Minor inconsistency with input group state

### ISSUE THREAD

**Issue by wvh** [bootstrap-vue/bootstrap-vue#1152]
I just noticed `b-form-input` accepts `string` and `boolean` parameters for `state`, while `b-input-group` accepts only `string`:

`[Vue warn]: Invalid prop: type check failed for prop "state". Expected String, got Boolean.`

Not a problem, just surprised me when I moved some code around.

**Comment by tmorehouse** [comment]
This should be fixed in the next release.

**Comment by tmorehouse** [comment]
PR #1155 removes the `state` prop from `b-input-group`
