### ISSUE TITLE
Modal with heavy/long content "jumping/scrolls" to modal header with no-fade option

### ISSUE THREAD

**Issue by tjunussov** [bootstrap-vue/bootstrap-vue#1153]
If i remove animation with 
` <b-modal  no-fade >`
and have big height content, modal is annoynly dragging( jumping/shaking ) on modal show, 
`no-enforce-focus="true"` not helping here
i think it happens due to autoscrolling to modal header, 
.modal-dialog has top margin

**Comment by tmorehouse** [comment]
When modals open, there are quite a few computations that take place to handle adjusting the scroll bars, passing, margins, etc, which is definitely more noticeable with `no-fade` is set.

`enforce-focus` only controls keeping focus within the modal while it is open, and does not affect scrolling.

When a modal opens, the modal dialog container is initially focused, which will scroll the top of the modal into view, as per W3C ARIA accessibility recommendations.

One suggestion for long modals is to place an wrapper `div` around your modal content, which has a max-height set to, say `max-height: 90vh;` (90% of the viewport height)) and `overflow-y: auto;`. This will prevent the jumping, and allow the user to scroll the inner content of the modal.

**Comment by tjunussov** [comment]
Ok, but official Bootstrap 4' modal with large content not behaves to W3C ARIA , 
pls look at https://getbootstrap.com/docs/4.0/components/modal/ "modal with large content".

maybe we could introduce another prop "no-enforce-autoscroll" ?
p.s  it will be more democratic 💯

**Comment by tmorehouse** [comment]
We don't "scroll" the modal/page. we just focus the main modal content. It is up to the browser how it handles the focusing/scrolling of the modal content.

We also strive to be W3C ARIA compliant (as is the law in many countries now)  for keyboard (non-mouse) and screen reader (i.e. blind) users.

**Comment by tjunussov** [comment]
according to this `https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/modal.vue`
```
{
    onEnter() {
        this.is_block = true;
        this.$refs.modal.scrollTop = 0;  <--- This is evil
}
```
you autoscroll to top edge of the modal, i think this is good feature, but it would be nice to have option to disable it

**Comment by tjunussov** [comment]
ic, may be we could do this, when focusing ? 
```
var x = window.scrollX, y = window.scrollY;
  elem.focus();
  window.scrollTo(x, y);
```
or if it's modal, we could bravly set scrollTo = 0 ?
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/modal.vue#L507

```

// Focus control handlers
        focusFirst: function focusFirst() {
            // Don't try and focus if we are SSR
            if (typeof document === 'undefined') {
                return;
            }
            var content = this.$refs.content;
            var activeElement = document.activeElement;
            if (activeElement && content && content.contains(activeElement)) {
                // If activeElement is child of content, no need to change focus
                return;
            } else if (content) {
                // Focus the modal content wrapper
                content.focus();
                this.$refs.modal.scrollTop = 0; <========= this 
            }
        },

```
p.s This solves shaking if content of modal is heavy

**Comment by tmorehouse** [comment]
That might be an option.  We'll have to try it out, and see if it affects any accessibility issues

**Comment by tmorehouse** [comment]
Please try out the latest v1.0.0 release.
