### ISSUE TITLE
b-modal-group / fieldset label column size for SR

### ISSUE THREAD

**Issue by KonradDeskiewicz** [bootstrap-vue/bootstrap-vue#1154]
I'm doing some in-line editor stuff and one thing is bothering me:
I can hide label with `label-sr-only` but it still occupy space.
I can set `:label-cols="0"` but then there is a warning generated:

> Invalid prop: custom validator check failed for prop "labelCols".

It would be nice if "0" was accepted together with `label-sr-only`

**Comment by tmorehouse** [comment]
You should be able to leave the label prop blank (or not set), which will remove the label position completely.

And if you need accessibility, add a hidden `.sr-only` label in the default slot along side your input control.

**Comment by KonradDeskiewicz** [comment]
got it! Thanks 👍
