### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by AttSee** [bootstrap-vue/bootstrap-vue#1157]
hi all 
I have a problem.
example doesn't work  why ?

`   here example
[index.txt](https://github.com/bootstrap-vue/bootstrap-vue/files/1353880/index.txt)

https://bootstrap-vue.js.org/docs/components/navbar

**Comment by tmorehouse** [comment]
You must place the boot-strap-vue components **inside** your application mount element.

You have the navbar outside of your application.  Vue can't control any elements outside of your app element:

````html
<b-navbar>
 . . . 
</b-navbar>
<div id="app">
  <!-- move your navbar in here -->
  {{ message }}
</div>

**Comment by AttSee** [comment]
Thanks for your reply
can I have a simple example
I want to know how it works bootstrap-vue
I tried this way, but I have a problem.

**Comment by AttSee** [comment]
and css doesn't work

**Comment by AttSee** [comment]
It Works  Thank you
