### ISSUE TITLE
Responsive table: column hiding

### ISSUE THREAD

**Issue by jrysig** [bootstrap-vue/bootstrap-vue#1158]
Any chance to implement column hiding strategy for responsive table? Together with column priority it works very well on small screens.

Please see https://datatables.net/extensions/responsive/examples/styling/bootstrap4.html

**Comment by tmorehouse** [comment]
Actually you can do this today using the field definition's `class` property.

Bootstrap V4 has several CSS clases that can be used to hid and show table columns:

- `d-none` (hides from `xs` up), `d-sm-none` (hides on `sm`l and up), etc
- `d-table-cell` (shows element as a table cell on `xs` and up), `d-sm-table-cell` (shows on `sm` screen and up), etc

Using a class list of `d-none d-md-table-cell` on a `field` definition `class` property would hide a column on small `xs` and `sm` screens, and show on `md` and above,  This is all done without any JavaScript monitoring of screen siz/resizee (which data-tables uses).

**Comment by jrysig** [comment]
Do you have any idea how to indicated there are hidden columns with some icon symbol and display these columns on click? Something like this:

![datatables_1](https://user-images.githubusercontent.com/7038517/31157991-ed40bddc-a8be-11e7-8bb8-997e5ef40867.png)
![datatables_2](https://user-images.githubusercontent.com/7038517/31158011-102c3ec0-a8bf-11e7-9c58-09f08b28d00b.png)

In Datatables implementation it is also possible to define priority (or order) how are particular columns hidden: https://datatables.net/extensions/responsive/priority

**Comment by tmorehouse** [comment]
Currently is it not possible to display a "second" row of "expanded" data below the current row, although it is an idea we have been toying around with (a scoped slot for a row below the current row), but determining a way to display it (as scoped slots are unidirectional data flow) is a problem.  Possibly  new `_` prefixed row variable might be able to trigger the showing of the scoped slot (i.e. by setting. the `_expand` property in the item row data as `true`)

You could, however, use the same `d-${breakpoint}-none` class along with `d-${breakpoint}-inline-block` classes to hide/show a button or icon representing there is hidden data.  Then use either b-popover or a modal controlled by a method to show the data.

**Comment by tmorehouse** [comment]
@jrysig PR  #1165 Adds support for showing a "details" row below an item. 

It should be available in the next release (v1.0.0.beta.10) of Bootstrap Vue

**Comment by jrysig** [comment]
Thank you...

**Comment by xorbis** [comment]
I found out that the fields variable is reactive but not deep: true.
I instead insert and remove the field definition in the fields array in order to toggle a column.
This could be a feature request, field.hide: boolean

**Comment by anirudh-goyal** [comment]
@xorbis How do you insert/remove the field definition in the fields array based on a condition?

**Comment by xorbis** [comment]
> @xorbis How do you insert/remove the field definition in the fields array based on a condition?

I do something like that:
`<b-table :fields="displayedFields" />`

And displayedFields is an array of columns to show.
[Bootstrap Vue table documentation](https://bootstrap-vue.js.org/docs/components/table)

**Comment by AnjushaJoshi** [comment]
Is it possible to achieve column hiding with help of Vue,without using Vuetify data tables?
