### ISSUE TITLE
Disabled button & popover

### ISSUE THREAD

**Issue by ssc-hrep3** [bootstrap-vue/bootstrap-vue#1161]
I'm using a popover on a button, which appears on hover. The button disables itself, when clicking (for loading purposes). The tooltip however does not hide anymore. It just freezes until the button is enabled again. If the message changes, this is even a greater problem, because the user has to first hover-out on the button (to hide the previous message) and then re-hover over the button to display the new message.

Here is an example:

```
<button v-b-tooltip.hover.right title="test" :disabled="testDisabled" @click="testDisabled = true">Click me</button>
```
`testDisabled` would be a regular `data` attribute

---

I'm using "bootstrap": "4.0.0-beta" and "bootstrap-vue": "1.0.0-beta.9"

**Comment by tmorehouse** [comment]
Thus is expected behavior, which mimics bootstrap v4.beta (we basically use identical base code for tooltips and popovers.

Disabled buttons don't typically emit native focus, click or hover events, so it is not possible to detect a change in hover if the button is disabled.

**Comment by tmorehouse** [comment]
I would suggest issuing `this.$root.$emit('bv::hide::popover')` when you re-enable the button.  This will hide all currently open popovers.
