### ISSUE TITLE
"Hide all open popover" does not work

### ISSUE THREAD

**Issue by ssc-hrep3** [bootstrap-vue/bootstrap-vue#1162]
I would like to close/hide all popovers on my Vue instance. I'm emiting an event to the `$root` as described in the docs (https://bootstrap-vue.js.org/docs/components/popover#closing-popovers).

The described command is used as in the docs. Here is an example:

```
methods: {
   closeAllPopovers () {
      this.$root.$emit('bv::hide::popover');
   }
}
```
---
I'm using "bootstrap": "4.0.0-beta" and "bootstrap-vue": "1.0.0-beta.9"

**Comment by tmorehouse** [comment]
This should work, although their could be a bug (there is a bug that is fixed with the tooltip version, which will be available in the next release)

I'll check in the dev branch to see if this issue persists.

**Comment by tmorehouse** [comment]
I just created the following in the current [Bootstrap-Vue docs playground](https://bootstrap-vue.js.org/play):

```html
<b-card class="text-center">
  <b-btn v-b-popover.click.top="'popover 1'" title="Popover" class="m-3">Click Me</b-btn>
  <b-btn v-b-popover.click.top="'popover 2'" title="Popover" class="m-3">Click Me</b-btn>
  <b-btn v-b-popover.click.top="'popover 3'" title="Popover" class="m-3">Click Me</b-btn>
  <br>
  <b-btn @click="$root.$emit('bv::hide::popover')">Hide Popovers</b-btn>
 </b-card>
```

And after clicking each of the top three buttons to open each popover, then clicking the bottom button, all popovers close.

So you might be using a older version of Boostrap-Vue, or there is some other issue with your code.
