### ISSUE TITLE
Big <b-dropdown>s are unusable when used inside an `overflow:scroll` container, due to being constrained inside it

### ISSUE THREAD

**Issue by ronjouch** [bootstrap-vue/bootstrap-vue#1163]
This is a followup to https://github.com/twbs/bootstrap/issues/24251 .

## Problem

When using a [bootstrap-vue (1.0.0-beta.9) `<b-dropdown>`](https://bootstrap-vue.js.org/docs/components/dropdown) in an element that is a child of an `overflow:scroll` element, the dropdown is "stuck" inside the container, making it unusable if the dropdown contents are too big horizontally/vertically (see demo at [JSFiddle/ronj/t6z6Lnfb](https://jsfiddle.net/ronj/t6z6Lnfb/)):

![overflow-scroll_bootstrap-dropdown-fs8](https://user-images.githubusercontent.com/522085/31194832-54d24bda-a916-11e7-9ad3-85541dd35f62.png)

Contrarily, a vanilla HTML `<select>` will merrily bleed out of the `overflow:scroll` element as necessary:
![overflow-scroll_regular-select-fs8](https://user-images.githubusercontent.com/522085/31194823-50451b9c-a916-11e7-85be-41e113fc0895.png)

## Native Bootstrap workaround & need help for bootstrap-vue

Over at https://github.com/twbs/bootstrap/issues/24251#issuecomment-334271729 , @danijelGombac suggests to reparent the dropdown to `body`:

```js
$(document).on('show.bs.dropdown', '.scrolled-heighted-box', function(e) {
    var dropdown = $(e.target).find('.dropdown-menu');
    dropdown.appendTo('body');
    $(this).on('hidden.bs.dropdown', function () {
        dropdown.appendTo(e.target);
    })
});
```

... and it works great in pure non-Vue Bootstrap! Now, back to my `bootstrap-vue` project I'm able to successfully listen to the equivalent and documented `$root / bv::dropdown::shown`  event, but then I'm lost in Vue forum posts mentioning `$el` / `$mount()` / `$appendTo`.

→ 1. Can anyone help me port this workaround to `bootstrap-vue`? If not, forgetting this re-parenting trick, any other idea to fix the initial problem?

→ 2. If a solution to 1. above is found, it would be awesome if it was encapsulated behind a `<b-dropdown>` boolean property (name proposal: `reparent-to-body`?) to do that easily. I'll be happy to submit a PR with docs.

## Use case

A few words on the use case justifying this combination, as shown in the JSFiddle which mimics a webapp I'm working on:

- In the *left sidebar* live a set of filters. It may contain several filters that will consume undetermined vertical space, thus lives in an `overflow-y:scroll` div. Each filter has a dropdown which lets users modify filter options.
- In the *right pane* lives the content, filtered by the filters in the left sidebar.

→ As a user,

1. I *do need* that `overflow-y:scroll` sidebar scrolling behavior (because the list of filters is of undetermined and potentially large height, depending on the number of filters)
2. But filter dropdowns (which can be large, both in width due to length of options and height due to count of options) should be able "escape out of" / not be constrained by the sidebar.

And as shown in the demo/screenshots, vanilla HTML `<select>` don't suffer from this problem, but it's not always practical/possible to revert back to using them, e.g. due to using features specific to Bootstrap Dropdown, or for consistent styling.

## Details

- bootstrap-vue version: 1.0.0-beta.9
- OS/Browser: Ubuntu 16.04.3 / {Chrome 63, Firefox 58}

Thanks 🙂.

**Comment by tmorehouse** [comment]
Re-parenting live reactive components (such as the components inside a dropdown) is not the greatest thing to do with Vue, as it can start complaining that the parent element has changed, cause a re-render (back to the original spot, and cause elements to be "stuck" where ever they weer re-parented if for some reason the original container or component gets removed from the document (i.e. v-if, a route change, etc).

The biggest issue is the latter (i.e. dropdown menus that get stuck open on a page when their parent component goes away).  While you can try and use beforeDestroy/destroyed hooks to move the content back to where it was supposed to be, it doesn't always work (as the place where it is supposed to be in the DOM no longer exists..  Which can also lead to application memory leaks if event listeners have references to those DOM elements (so they may get removed from DOM, but are still in memory because someone else has a reference to it).

**Comment by ronjouch** [comment]
@tmorehouse alright, that's what I was expecting, thanks for the fast and detailed response 👍.

Back to the original problem (*"my `<b-dropdown>` shouldn't be constrained to its `overflow:scroll`-ed parent"*), any other idea to solve that in a different way?

**Comment by tmorehouse** [comment]
Even with the workaround for native bootstrap, if your menu is taller than the viewport, you are going to have issues reaching the full height of the menu, as Popper determines positioning/flipping by the placement of the original trigger element.  This is controlled by Popper.js, not Bootstrap nor Bootstrap-Vue.

Maybe you might need to re-think your approach, and switch to another method of selecting the filters that would b a bit more mobile friendly.  Like maybe using a modal to display the list of filters (you can remove the header and footer of the modal), and use a list-group to list your options. 

Then on click of the "option" you  call the hide method of the modal (or emit a close event), and then apply the filter based on which option was clicked.

You would need to place the modal container  outside of your scroll area, but you can still trigger it to open via a method call, which then control's the visibility state of the modal.  Your method could take a few prameters, such as the option list you want to render, then pass that to the content of your modal via data, and loop through it to render the options.

**Comment by tmorehouse** [comment]
Closing until a solution is found over at twbs/bootstrap.

Looks like re-parenting has been canned due to keyboard navigation issues (dropdown items taken out of current page taborder (which is bad for ARIA)

**Comment by tmorehouse** [comment]
We now have a working solution for this situation, via the addition of a new prop `boundary` (which default's to Popper's default value of `scrollParent`.  The boundary prop accepts the string values of `viewport` or `window`.  Setting `viewport` will change the boundary constraints to allow the dropdown to overflow it's scroll container, but remain within the viewport.  `window` is similar, but works better if the dropdown is taller than the window size (with the caveat that it will not autoflip)

This should be available in the next release (v1.4.0).

Re-opening this issue until the next release is out.

**Comment by tmorehouse** [comment]
This feature is now available in v1.4.0 via a new `boundary` prop.

**Comment by tmorehouse** [comment]
There i a minor issue with the feature added in v1.4.0, which will be addressed in the next release.

The `position-static` class was not always being added in the right context, although the boundary prop is working correctly.

**Comment by zeodtr** [comment]
@tmorehouse It does not work when the container element has 'position: absolute' style. It would be great if HTML spec itself had a solution for this.. (for example, 'clip-by-container: no' style)

**Comment by benjaminpussel** [comment]
@tmorehouse the issue remains... its still necessary to set position: static in the case described. Is this topic worked on in this issue (should be reopened) or anywhere else?
