### ISSUE TITLE
class css doesn't work

### ISSUE THREAD

**Issue by AttSee** [bootstrap-vue/bootstrap-vue#1164]
I'm trying to run class 
`

  <div>
      
      <b-btn v-b-modal.myModal>Show Modal</b-btn>
    
      
      <b-btn v-b-modal="'addPostModal'">Show Modal</b-btn>
    
      
      <b-modal id="addPostModal">
          <div class="b-modal-dialog modal-lg">
              <div class="b-modal-content">
                <div class="b-modal-header bg-primary text-white">
                  <h5 class="b-modal-title" id="addPostModalLabel">Add Post</h5>
                  <b-button class="close" data-dismiss="b-modal">
                    <span>&times;</span>
                  </b-button>
                </div>
                <div class="b-modal-body">
                  <b-form>
                    <div class="form-group">
                      <label for="title" class="form-control-label">Title</label>
                      <input type="text" class="form-control">
                    </div>
                    <div class="b-form-group">
                      <label for="category" class="form-control-label">Category</label>
                      <select class="form-control">
                        <option value="">Web Development</option>
                        <option value="">Tech Gadgets</option>
                        <option value="">Business</option>
                        <option value="">Health & Wellness</option>
                      </select>
                    </div>
                    <div class="b-form-group bg-faded p-3">
                      <label for="file">Image Upload</label>
                      <input type="file" class="form-control-file" id="file">
                      <small id="fileHelp" class="form-text text-muted">
                        Max Size 3MB
                      </small>
                    </div>
                    <div class="b-form-group">
                      <label for="body">Body</label>
                      <textarea name="editor1" class="form-control"></textarea>
                    </div>
                  </form>
                </div>
                <div class="b-modal-footer">
                  <b-button class="btn btn-secondary" data-dismiss="modal">Close</b-button>
                    <b-button class="btn btn-primary" data-dismiss="modal">Add Post</b-button>
                </div>
              </div>
            </div>
      </b-modal>
      </div>
`

 but it doesn't work ???

**Comment by tmorehouse** [comment]
Please check the documentation for b-modal at https://bootstrap-vue.js.org/docs/components/modal and follow the examples.  Your b-modal markup should be similar to the examples.  Use the names slots or props to set the headers/footers, etc.

**Comment by tmorehouse** [comment]
Take a look at this example: 
https://bootstrap-vue.js.org/docs/components/modal#variants

**Comment by tmorehouse** [comment]
```html
<b-btn v-b-modal="'addPostModal'">Show Modal</b-btn>

<b-modal id="addPostModal" size="lg" title="Add Post">
  <b-form>
    <b-form-group label="Title">
      <b-input name="title"></b-form-input>
    </b-form-group>
    <b-form-group label="Category">
      <b-form-select>
        <option value="1">Web Development</option>
        <option value="2">Tech Gadgets</option>
        <option value="3">Business</option>
        <option value="4">Health &amp; Wellness</option>
      </b-form-select>
    </b-form-group>
    <b-form-group label="Image Upload" description="Max Size 3MB" class="bg-faded p-3">
      <b-form-file></b-form-file>
    </b-form-group>
    <b-form-group label="Body">
      <b-form-textarea name="editor1"></b-formtextarea>
  </b-form>
</b-modal>
```

**Comment by AttSee** [comment]
Thanks for your reply
Why can't use  class ?

`<div  class ="b-modal"  id="addPostModal" size="lg" title="Add Post">`

**Comment by tmorehouse** [comment]
You don't need the classes.  Bootstrap-Vue works using Vue.JS, and implements Bootstrap V4 components as VueJS custom components.  Plain Bootstrap V4 markup will not work with Bootstrap-Vue, as Bootstrap-Vue builds the required markup for you.

**Comment by tmorehouse** [comment]
Another good starting point is looking at teh Vue.JS officail documentation at https://vuejs.org/ and specifically at how custom components work: https://vuejs.org/v2/guide/components.html

**Comment by tmorehouse** [comment]
`<b-modal>` is a custom Vue component not a CSS class.

If you want to use standard CSS/HTML markup, then you should just be using standard Bootstrap V4 (https://getbootstrap.com with jQuery) and not Bootstrap-Vue

**Comment by AttSee** [comment]
Points of the utmost importance, thank you, dear for the clarification
