### ISSUE TITLE
$refs on Modal with lazy prop, after show/hide become undefined

### ISSUE THREAD

**Issue by tjunussov** [bootstrap-vue/bootstrap-vue#1166]
In my project, i have two modals with lazy prop, when I invoke  `this.$refs.diagramModalRef.show();` on 
```
b-modal(
      id="modalDiagram" 
      ref="diagramModalRef" 
      lazy)
      Hello Diagram

 b-modal(
      id="modalProcess" 
      ref="processModalRef" 
      lazy)
      Hello Process
```
for the first time it ok, after closing modal, 
if invoke second time `this.$refs.diagramModalRef` become `undefined`
p.s I tried reproduce it in playgroud, it works whiout bugs, in my projects it becames undefined, 
if I remove lazy prop, it works

**Comment by tmorehouse** [comment]
Would there be something else that might `v-if` the modal out of the document temporarily? If so, then the element $ref will no longer be valid.

Have you tried to emit the event on root to show it?
```js
   this.$root.$emit(''bv::show::modal', 'modalDiagram')
```
See if that has the same issue.

**Comment by tjunussov** [comment]
no there is no v-if's, 
but these modals located inside <router-view>
maybe this affects somehow ?

**Comment by tmorehouse** [comment]
The modal, when in lazy mode, is v-if'ed out of the document when not shown (it becomes a vue `<!---->` placeholder comment).

**Comment by tjunussov** [comment]
Btw this works on root component
```
 this.$root.$emit('bv::show::modal', 'modalDiagram')
```
so basicly `lazy `prop wont work with `refs `? if it if'ed

**Comment by tmorehouse** [comment]
Correct

**Comment by tmorehouse** [comment]
Yes, we should probably update the docs regarding lazy and $refs on modal.
