### ISSUE TITLE
b-form-file cannot get filled when project is compiled

### ISSUE THREAD

**Issue by Glorf** [bootstrap-vue/bootstrap-vue#1169]
In my project I use default b-form-file like this:

`<b-form-file id="file_input" v-model="file"></b-form-file>`

The project is based on vuejs-templates/webpack with no major changes (except for adding vue-bootstrap, router, and vuex).
Form is working seamlessly when running using yarn dev build. But when I compile the code and run it in production, it allows me to select file, but does not show the file name, and does not fill file object to submit. The rest of framework (dropdowns, menus etc) is working well. Browser console produces no errors after the form is filled. Do you have an idea what the problem could be?

**Comment by tmorehouse** [comment]
Make sure the bootstrap-vue.css is being loaded into your production project. Additional override CSS is needed to get around a change in Bootstrap V4.beta's CSS (specificity issues with selectors)

**Comment by Glorf** [comment]
Resolved quite unexpectedly. The problem was webpack switching packages and overwriting bootstrap-vue.css by bootstrap.css.
I suggest changing import* to require* in getting started guide to omit a problem

**Comment by tmorehouse** [comment]
It might be the order the imports are happening (depending on your webpack setup).

**Comment by Glorf** [comment]
To make it in order and fully deterministic I had to update extract-text-webpack-plugin at least to 3.0.0-rc.1 There is a bug in versions 2.1.x

Thanks for your help!
