### ISSUE TITLE
[bug] form select RTL style

### ISSUE THREAD

**Issue by armin-mohammadi** [bootstrap-vue/bootstrap-vue#1170]
form select component has displaying problem in RTL direction.
![image](https://user-images.githubusercontent.com/15139191/31306976-05ece2e2-ab68-11e7-8ba9-03687c31622f.png)
Its selector icon should be on the left.

**Comment by tmorehouse** [comment]
This is controlled by the official bootstrap v4 css. You should open this issue at twbs/bootstrap on github.

**Comment by tmorehouse** [comment]
Another option that **might** work is to run Bootstrap's (and BootstrapVue's) CSS through https://www.npmjs.com/package/postcss-rtl
