### ISSUE TITLE
How can I make b-list-group to be horizontal?

### ISSUE THREAD

**Issue by maple3142** [bootstrap-vue/bootstrap-vue#1171]
As title
I want to make a list-group be horizontal, is there any approach?

**Comment by tmorehouse** [comment]
The layout is all defined by bootstrap v4's css. You could create your own custom css to override bootstraps, your you could create your own list group via basic html markup.

Check the official bootstrap documentation at https://getbootstrap.com/ and check the docs under components > list-group
