### ISSUE TITLE
Document how to use navbar and vue-router together

### ISSUE THREAD

**Issue by gquintana** [bootstrap-vue/bootstrap-vue#1175]
I'd like to use router-link in navbar, I wrote something like this:

```
    <b-navbar toggleable="md" type="primary" variant="info">
      <b-navbar-brand>Brand</b-navbar-brand>
      <b-nav>
        <b-nav-item to="/one">One</b-nav-item>
        <b-nav-item to="/two">Two</b-nav-item>
      </b-nav>
    </b-navbar>
```

It mostly looks and behaves as expected, I don't know whether it's the intent?
Yet the active route is not shown.

**Comment by tmorehouse** [comment]
Check out the documentation section on [Router Link Support](https://bootstrap-vue.js.org/docs/reference/router-links).

Basically any Bootstrap-Vue component that accepts the props `href` and `to` also accept the majority of `<router-link>` props.

You can set the props `exact` if you need an exact match on the link's route.  And you can set the `active-class` prop to `active` to use the standard bootstrap `active` highlighting

Bootstrap-Vue also provides (a yet undocumented) component called `<b-link>` which auto generates either a `<router-link>` (if `to` is provided) or regular `<a>` (if only `href` is provided).  It also handles properly disabling link functionality if the `disabled` prop is set.

All Bootstrap-Vue components that accept `href` and `to` props use `<b-link>` as their base.

**Comment by gquintana** [comment]
Awesome! Thanks for you help.
I still think that a short example on the Nav component or link to the Router Link Support page would have avoided my silly question.

**Comment by tmorehouse** [comment]
There is actually a link to the router link support page just before the component reference section on the `nav` documentation page (the [See also](https://bootstrap-vue.js.org/docs/components/nav#see-also) section)
