### ISSUE TITLE
b-nav-item-dropdown with dropup drops the menu down instead of up

### ISSUE THREAD

**Issue by gildas** [bootstrap-vue/bootstrap-vue#1176]
BootstrapVue version 1.0.0-beta.9

When using the option `dropup` for a `b-nav-item-dropdown`, the menu will drop down instead of up.

```html
<b-nav-item-dropdown dropup right>
  title
  <b-dropdown-item>value1</b-dropdown-item>
  <b-dropdown-item>value2</b-dropdown-item>
  <b-dropdown-item>value3</b-dropdown-item>
</b-nav-item-dropdown>
```

**Comment by tmorehouse** [comment]
This works in the current version (paste it into the [playground](https://bootstrap-vue.js.org/play) to see)

```html
<b-nav pills>
  <b-nav-item active>Active</b-nav-item>
  <b-nav-item>Link</b-nav-item>
  <b-nav-item-dropdown text="Dropdown"right>
    <b-dropdown-item>one</b-dropdown-item>
    <b-dropdown-item>two</b-dropdown-item>
    <b-dropdown-divider></b-dropdown-divider>
    <b-dropdown-item>three</b-dropdown-item>
  </b-nav-item-dropdown>
  <b-nav-item-dropdown text="Dropup" dropup right>
    <b-dropdown-item>one</b-dropdown-item>
    <b-dropdown-item>two</b-dropdown-item>
    <b-dropdown-divider></b-dropdown-divider>
    <b-dropdown-item>three</b-dropdown-item>
  </b-nav-item-dropdown>
</b-nav>
```

You are also specifying your title incorrectly.  It should be set via the prop `title` on <b-nav-item-dropdown>` or via the named slot `button-content`

**Comment by gildas** [comment]
Ok, maybe I am doing something very wrong.

Just tried this in the playground (and it does not work either):

```vue
<b-navbar toggleable fixed="bottom">
  <b-nav is-nav-bar>
    <b-nav-item>
      <b-nar-text>v. 1.0.0</b-nar-text>
    </b-nav-item>
  </b-nav>
  <b-nav is-nav-bar class="ml-auto">
    <b-nav-item-dropdown text="Choice 1" dropup right>
	  <b-dropdown-item>Choice 1</b-dropdown-item>
      <b-dropdown-item>Choice 2</b-dropdown-item>
      <b-dropdown-item>Choice 3</b-dropdown-item>
      <b-dropdown-item>Choice 4</b-dropdown-item>
    </b-nav-item-dropdown>
  </b-nav>
</b-navbar>
```

It would have been nice to wait for my confirmation before closing this...

**Comment by tmorehouse** [comment]
`b-nav` supports `dropup`, but` b-navbar` does not support dropup (only dropdown), as per the official Bootstrap V4.beta.1 CSS

It is not controlled by Bootstrap-Vue, but rather Bootstrap V4.beta CSS

It is expected that this will be addressed when Bootstrap V4.beta.2 ships

**Comment by gildas** [comment]
Ok, noted. Thanks a lot Troy for checking.
And sorry to be a pain. I should have given you better details.
