### ISSUE TITLE
b-carousel in nuxtjs does not slide properly + creates blue outlines on click

### ISSUE THREAD

**Issue by justinhodev** [bootstrap-vue/bootstrap-vue#1177]
Using carousel element as specified in [docs](https://bootstrap-vue.js.org/docs/components/carousel) in nuxtjs creates blue outlines when pressing any of the elements and slide transition is only shown transitioning between end slide and start slide or manually going back one slide.

**Comment by tmorehouse** [comment]
Make sure you are using the latest Bootstrap-Viue (v1.0.0-beta.9) and the latest Bootstrap V4 beta.1 CSS.

**Comment by tmorehouse** [comment]
And a side note...  the docs are generated using Nuxt.js
