### ISSUE TITLE
Why b-img-lazy didn't have "alt" prop

### ISSUE THREAD

**Issue by maple3142** [bootstrap-vue/bootstrap-vue#1179]
As title.
```html
<b-img-lazy :src="something" alt="image alt"/>
```
alt not work here, but works with `<b-img>`

**Comment by tmorehouse** [comment]
Thanks for the bug report.

This is fixed by commit https://github.com/bootstrap-vue/bootstrap-vue/commit/f2fb99c5e418543869d6611f201fc240d284b722 in the `dev` branch and will be available in the next release (v1.0.0-beta.10)
