### ISSUE TITLE
Problem with b-collapse transition

### ISSUE THREAD

**Issue by Doeke** [bootstrap-vue/bootstrap-vue#118]
I'm making use of the components for responsive navbar, but the b-collapse transition doesn't appear to be working. The height doesn't animate properly, perhaps because it is set to 100px regardless of content height?

    scrollHeight() {
      return 100;// this.$el.scrollHeight;
    }

**Comment by pi0** [comment]
Hey @Doeke yep that's a known issue. we may switch to native vue [transitions](https://vuejs.org/v2/guide/transitions.html) for smoother animations...

**Comment by Doeke** [comment]
Thanks for the quick response, I'll just implement my own navbar collapse for now.
