### ISSUE TITLE
Bootstrap "hidden" classes missing

### ISSUE THREAD

**Issue by fabiankaimer** [bootstrap-vue/bootstrap-vue#1180]
I have recognized, that neither the standard bootstrap hidden classes ("hidden-xs", "hidden-sm", etc.) nor the new Bootstrap 4 hidden classes ("hidden-*-up", "hidden-*-down") are currently supported. I would suggest adding them to future releases. By the way, you are doing great work and the project is very helpful! :)

**Comment by tmorehouse** [comment]
Bootstrap-Vue uses the standard Bootstrap V4.beta CSS  The `hidden-*` no longer exist in Bootstrap V4.beta CSS

As per the shiplist for Bootstrap V4.beta.1, the `hidden-*` classes have been removed in favor of the `d-*-done` classes.  See https://getbootstrap.com/docs/4.0/migration/#responsive-utilities and https://getbootstrap.com/docs/4.0/utilities/display/

**Comment by TCB13** [comment]
So and how is this implemented in `bootstrap-vue`?

**Comment by tmorehouse** [comment]
Bootstrap-Vue uses/required the Bootstrap V4 CSS, so you can use any of the bootstrap V4 utility classes on components and elements.

**Comment by TCB13** [comment]
@tmorehouse thank you for answering, so whats the advantage of using:
```````
<b-col lg="4" class="plan" v-for="plan in plans" :key="plan">
```````
over
```````
<div class="col-lg-4 plan" v-for="plan in plans">
```````
?

**Comment by tmorehouse** [comment]
You can use either way for columns.

Creating equal width columns can be done just like so:
```html
<b-row>
 <b-col>1</b-col>
 <b-col>2</b-col>
 <b-col>3</b-col>
</b-row>
```

But there is nothing stopping you from using native HTML+classes for things like columns/rows when using Bootstrap-Vue

These custom layout components were just created for convenience.  And when one has deep nesting, seeing a `</b-col>` instead of a `</div>` easily lets one know that that is the end of a column.

**Comment by tmorehouse** [comment]
Note in your last coment, you still need `key="plan"` with your `v-for` loop on the `<div>`  (otherwise Vue will complain)

**Comment by TCB13** [comment]
@tmorehouse just noticed you updated your original comment. Thanks for the quick explanation on the   usefulness of the `bootstrap-vue` components.

**Comment by tmorehouse** [comment]
If you are using Vetur as your editor, we do provide a helper JSON project for IDE autocomplete https://github.com/bootstrap-vue/bootstrap-vue-helper-json

**Comment by TCB13** [comment]
I’m actually using Webstorm.
