### ISSUE TITLE
b-table <template> how use?

### ISSUE THREAD

**Issue by robertorp** [bootstrap-vue/bootstrap-vue#1183]
following the documentation just put a template to customize the table line, so I made sure I'm letting something pass but I want to know what it is because the same is not having effects expected by the documentation

```
<b-table 
      @filtered="onFiltro"
      :filter="filtro" 
      :fields="colunas"
      show-empty
      :current-page="paginaCorrente" :per-page="porPagina"
      striped hover :items="listaProduto">
        <template slot="name" scope="row">{{row.value.descricao}}</template>
      </b-table>
```

**Comment by tmorehouse** [comment]
Without seeing an example of your items data (and your field definitions), we can only make a guess.

if `descricao` is a direct property of an item row, and the column key is also `descricao`, then try this:

```html
<template slot="descricao" scope="row">{{row.value}}</template>
```
or
```html
<template slot="descricao" scope="row">{{row.item.descricao}}</template>
```

**Comment by robertorp** [comment]
thx, row."item".descricao
