### ISSUE TITLE
Starter Example on the site doesn't work

### ISSUE THREAD

**Issue by sirideain** [bootstrap-vue/bootstrap-vue#1184]
I copied it into an html file and tried loading in a browser. It gives the error that **BootstrapVue is not defined**.

**Comment by tmorehouse** [comment]
Leave out the line `Vue.use(BootstrapVue)`.  It is not needed as bootstrap automatically plugs itself into Vue.

The docs have been updated, and will be available when release v1.0.0-beta.10 is published.

**Comment by sirideain** [comment]
Okay. I removed that line and now I get this error in the dev console. I can fix this error by removing label-cols, but I never see an alert after typing in the box.

```
[Vue warn]: Invalid prop: type check failed for prop "labelCols". Expected Number, got String.

found in

---> <BFormGroup>
       <Root>
```

**Comment by tmorehouse** [comment]
You need to type at least 5 characters
