### ISSUE TITLE
Issue during use table 

### ISSUE THREAD

**Issue by iagocavalcante** [bootstrap-vue/bootstrap-vue#1187]
I had an array of objects and inside this i hava another array with objects, how can i display the information of the second array in table?

`<template>`
  `<b-table striped hover :items="items" :fields="fields"></b-table>`
`</template>`

`<script>`
`export default {`
 ` data: {`
    `// Note 'isActive' is left out and will not appear in the rendered table`
   ` fields: [`
     ` {`
       ` key: 'last_name',`
       ` sortable: true`
     ` },`
    `  {`
       ` key: 'first_names',`
       ` sortable: false`
      `},`
     ` {`
        `key: 'age',`
        `label: 'Person age',`
       ` sortable: true,`
       ` // Variant applies to the whole column, including the header and footer`
        `variant: 'danger'`
    `  }`
  `  ],`
   ` items: [`
    `  { isActive: true,  age: 40, first_names: [{name: 'Dickerson'},{name: 'Dickerson'}], last_name: 'Macdonald' },`
    `  { isActive: false, age: 21, first_names: 'Larsen', last_name: 'Shaw' },`
     ` { isActive: false, age: 89, first_names: 'Geneva', last_name: 'Wilson' },`
      `{ isActive: true,  age: 38, first_names: 'Jami', last_name: 'Carney' }`
  `  ]`
`  }`
`};`
`</script>`

look this example!

**Comment by tmorehouse** [comment]
You would need to use a custom format slot for the field, and then loop through the 'value' with a v-for loop.

**Comment by iagocavalcante** [comment]
How can i get scoped data in v-for ? 
Something like this
 `<template slot="equipaments" scope="data" v-for="eq in data.item.equipaments">`
`{{ eq.name}}`
`</template>`

**Comment by tmorehouse** [comment]
As long as item.equipments is an array (or object), then you will be able to loop over it... But your loop needs to be inside the scoped slot:

```html
<template slot="equipaments" scope="data">
  <div v-for="eq in data.item.equipaments" :key="eq.name">
    {{ eq.name}}
  </div>
</template>
```

**Comment by iagocavalcante** [comment]
Thanks, i discover how to do this without use slot, just organized my data!
