### ISSUE TITLE
b-form-input type="hidden" not allowed

### ISSUE THREAD

**Issue by kaphert** [bootstrap-vue/bootstrap-vue#1188]
https://github.com/bootstrap-vue/bootstrap-vue/blob/7f7e6a72fb1c1d69830d9fc52579d4b6dcf6dd95/lib/components/form-input.vue#L51-L54

The type `hidden` is not allowed for the `b-form-input` component. It throws a warning _[Vue warn]: Invalid prop: custom validator check failed for prop "type"._

**Comment by tmorehouse** [comment]
Because `b-form-input` is designed to use bootstrap CSS styles/classes, 'hidden' is not one of the supported types, as it is not visible, nor provides user interaction which would trigger the formatter callback option.

You can add in regular hidden inputs quite simply:

```html
<input type="hidden" name="foo" :value="myHiddenValue">
```
