### ISSUE TITLE
Docs - https://bootstrap-vue.js.org/docs/reference/examples#basic-example

### ISSUE THREAD

**Issue by slavap** [bootstrap-vue/bootstrap-vue#1192]
Few minor issues:
label-cols="4" gives warning, should be changed to:
```html
        <b-form-group horizontal 
                      :label-cols="4"
                      description="Let us know your name."
                      label="Enter your name"
        >
```

Vue.use(BootstrapVue) gives error, not needed at all.

**Comment by mosinve** [comment]
> Vue.use(BootstrapVue) gives error, not needed at all.

what error? Usually it shoudn't give an error, even plugin already registered.

**Comment by mosinve** [comment]
Hi, thx for report. File already fixed at dev branch. Changes will be avalable with next release.
