### ISSUE TITLE
Using v-mask directive on `b-form-input` not transferring to `input` element

### ISSUE THREAD

**Issue by Steve525** [bootstrap-vue/bootstrap-vue#1194]
Hello team,

I'm working with the [v-mask](https://www.npmjs.com/package/v-mask) (v1.3.0) plugin and attempting to use the `v-mask` directive on the `b-form-input` component like so:

```html
<b-form @submit.stop.prevent="onSubmit">
    ... 
    <b-input-group left="Mobile*">
      <b-form-input
        type="text"
        v-model="mobile"
        v-mask="'###-###-####'"
        placeholder="___-___-____" />
    </b-input-group>
    ...
  </b-form>
```

The `v-mask` directive is turned into `data-mask` on the actual `input` element when everything gets compiled down and mounted to the DOM. I have been able to test this directive on a simple `input` element and it works and other custom input elements outside of bootstrap-vue work too (and they do not transform to `data-mask` property). I'm wondering if this could be a bug or if it's expected behavior. Any ideas on what could be going wrong would be greatly appreciated.

**Comment by tmorehouse** [comment]
Hmm, the directive __should_ work, as the `<input>` element is the root element of `<b-form-input>`, so the reference element (`this.$el` in the component, and `el` in directives) is the input.

Although I do see this "warning" on the NPM page:
> Notice: v-model is required starting from v1.1.0, because a lot of bugs with HTMLElement event listeners and sync with Vue internals.
> There is no reason to support using this lib for using without v-model **but open the door for using on custom inputs.**

The one thing about `<b-form-input>` is that it supports multiple types of inputs (i.e. `text`, `email`, etc.).

So internally inside `<b-form-input>` we couldn't `v-bind` to the input's value as Vue doesn't support `v-model` on inputs where the `type` attribute is a `v-bind`.   So we had to resort to listeners on the input to update a local data value.

Based on the above note from the `v-mask` readme (and without delving into the source code of `v-mask`), it might be related to the fact that the value of the inner input is not a direct v-model.

**Comment by Steve525** [comment]
@tmorehouse,

I think you're right and it's most likely an issue with `v-mask`. I'll start poking around over there and see what I can turn up. Thanks for pointing me in the right direction and the quick response!

**Comment by rickybrown** [comment]
Any new findings on this before i start digging around?

**Comment by tomcatchpole92** [comment]
did you guys find anything having the same problem

**Comment by adamhursey** [comment]
Did anyone find a solution to this?

**Comment by jonaswebdev** [comment]
+1

**Comment by DavidVinicius** [comment]
I have the same problem using the [Awesome Mask](https://github.com/wirecardBrasil/awesome-mask) but in my case, I import wrongly the directives in the main.js file. When I use `Vue.directive('mask', AwesomeMask);` every works.

**Comment by AlexcastroDev** [comment]
> Did anyone find a solution to this?

Yes, its easy!

in your b-form-input, set @focus="checkMask(id, mask)"

create this method and Voialá!

```
checkMask( mask, id ) {
                 let el = document.getElementById(id);
                el.setAttribute("v-mask", mask);
            },
```
