### ISSUE TITLE
Reusable Promsie based modal with dynamic components

### ISSUE THREAD

**Issue by tjunussov** [bootstrap-vue/bootstrap-vue#1198]
If we assume modal to be like window, then we need somthing like this  `https://gitlab.com/citygro/vue-modal`
It is Promise based aproach with params ( maybe props ) 

```
b-modal( id="modalProcess"   ref="processModalRef" )

this.$refs.processModalRef.show(params).then((resp)=>{
   ... do smthng after ok
}).catch((e)=>{
   ... do smthng after modal error
  return false <-- prevent closing modal, with event error or class error
})
```

or/and maybe we could MODALize any component with modal representation ?
```

MyComponent(v-modal ref="myCompModal")

this.$refs.myCompModal.show(params).then((resp)=>{
   ... do smthng after ok
}).catch((e)=>{
   ... do smthng after modal error
  return false <-- prevent closing modal, with event error or class error
})

```
p.s I think modals should behave like `router-view` ?

**Comment by tmorehouse** [comment]
Bootstrap-Vue follows bootstrap V4 component structures. Changing modal this way would break that 1:1 relationship between the two libraries.

I would suggest that your idea be made into an "extra component" that wraps b-modal.

b-modal currently provides an event based show//shown/hide./hidden (passing event's that look similar to native Event, but with additional properties that relate to Vue VM.

Not all Bootstrap V4 supported browsers support native promises, which would then make Boostrap-Vue need to include a promise library polyfill.

**Comment by tjunussov** [comment]
ic, but Bootstrap 4, is more from Jquery world, I think in Vue world, concept of modals more deep, 
in jquery we could innerHTML content of modal, and resuse it,
