### ISSUE TITLE
nested rows get incorrect column sizes

### ISSUE THREAD

**Issue by mhldtna** [bootstrap-vue/bootstrap-vue#1199]
I tried to nest rows like this, but then the size of the columns on the interior rows gets messed up.  Example:
```html
<div>
  <b-row>
          <b-row no-gutter>
              <b-col>File Name:</b-col><b-col class='data'>{{ fileName }}</b-col>
              <b-col>Last Updated:</b-col><b-col class='data'>{{ lastUpdated }}</b-col>
          </b-row>
    </b-row>
</div>
```

In this particular example, the text "Last Updated" breaks into two rows on the screen, I think because the column is too narrow.  Also, alignment of columns across rows gets messed up.  Similar problems happen if you make the column size explicit (e.g. "cols=2"), so it's not just the algorithm for automatic column size.

See also this [fiddle](https://jsfiddle.net/3rwtk58b/):

**Comment by tmorehouse** [comment]
As per Official Bootstrap V4 CSS, rows cannot be directly nested within each other.

a Row can only be a child of the following components:
- container
- col

You have a row directly nested in a row (direct child) which will mess up the Bootstrap V4 CSS styling selectors

**Comment by mhldtna** [comment]
Ah, thanks.  I wrapped my inner rows with <b-container> and that fixed it.

**Comment by tmorehouse** [comment]
Note that:
- only cols can be direct children of rows
- rows must be a direct child of a either a container (or container fluid), or a col
- cols must be a direct child of rows

**Comment by tmorehouse** [comment]
```html
<div>
  <b-container>
    <b-row no-gutter>
      <!-- note that these will be 4 equal sized columns -->
      <b-col>File Name:</b-col>
      <b-col class='data'>{{ fileName }}</b-col>
      <b-col>Last Updated:</b-col>
      <b-col class='data'>{{ lastUpdated }}</b-col>
    </b-row>
  </b-container>
  <b-container>
      <!-- this will make two rows of 2 equal sized columns -->
      <b-row no-gutter>
        <b-col>File Name:</b-col>
        <b-col class='data'>{{ fileName }}</b-col>
      </b-row>
      <b-row no-gutter>
        <b-col>Last Updated:</b-col>
        <b-col class='data'>{{ lastUpdated }}</b-col>
      </b-row>
  </b-container>
</div>
```
