### ISSUE TITLE
Tweaks for collapse to work.

### ISSUE THREAD

**Issue by michaelwoodson** [bootstrap-vue/bootstrap-vue#12]
I was able to get collapse working with the following tweaks:
In collapse.vue change:
`hub.$on('toggled::collapse', function (data) {`
to:
`hub.$on('toggled::collapse', (data) => {`

That way this.id returns the expected value.

Also in collapse-toggle.vue there are two calls to emit the "toggled::collapse" events.  I had to remove one of the calls.

Similar changes will be needed to the analogous accordion code that seems to be stubbed in.

**Comment by pi0** [comment]
@michaelwoodson Thanks for you point! Is there any chance opening a PR for that bugfix ? So we will able to review and merge it ASAP :)

**Comment by michaelwoodson** [comment]
Sure, I'll make one shortly, thanks!
