### ISSUE TITLE
The "stripped" property of <b-table> should be renamed to "striped"

### ISSUE THREAD

**Issue by lcrespom** [bootstrap-vue/bootstrap-vue#120]
The spelling is wrong: this property determines whether the table should be displayed with stripes. It is even obvious in line 2 of bootstrap-vue/components/table.vue:

```html
<table :class="['table',stripped?'table-striped':'',hover?'table-hover':'']">
```

You can see that Bootsrap spells its `table-striped` class correctly.

**Comment by pi0** [comment]
@lcrespom Thanks :) Will be renamed soon
