### ISSUE TITLE
Bootstrap@4.0.0-beta dependency is not installed

### ISSUE THREAD

**Issue by gswcm** [bootstrap-vue/bootstrap-vue#1200]
Following the installation procedure and running
```bash
npm i -D bootstrap-vue
```
doesn't install `bootstrap@4.0.0-beta` package which results in a build error caused by the lack of referenced `bootstrap.css` file.

I assume that the problem happens because `jquery` and `popper` packages are not installed but are required by `bootstrap`. Here is the warning message displayed after running `npm i -D bootstrap-vue`:
```
npm WARN bootstrap@4.0.0-beta requires a peer of jquery@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0-beta requires a peer of popper.js@^1.11.0 but none is installed. You must install peer dependencies yourself.
``` 

**Proposed (temporal) fix** would be to explicitly  install bootstrap:
```
npm i -D bootstrap@4.0.0-beta
```

**Comment by alexsasharegan** [comment]
I'd recommend checking out our vue-cli templates for a usage model.

https://github.com/bootstrap-vue/webpack
https://github.com/bootstrap-vue/webpack-simple

**Comment by gswcm** [comment]
Would it be a good idea to mention this in the guide, particularly the fact
that bootstrap package has to be explicitly installed.

It seems that the difference would be to replace

npm i -D bootstrap-vue

by

npm i -D bootstrap bootstrap-vue

in the getting started manual...

**Comment by tmorehouse** [comment]
It would also need mention of dealing with Custom Bootstrap CSS builds (if users what to customize the theme of Bootstrap)
