### ISSUE TITLE
Vue 2.5.1: Invalid value for option "components": expected an Object, but got Array.

### ISSUE THREAD

**Issue by sigmoidbigfoot** [bootstrap-vue/bootstrap-vue#1201]
After upgrading to Vue 2.5.1 I receive the following console warning:

![vue-bootstrap-warn](https://user-images.githubusercontent.com/15150911/31562646-d4ba943a-b021-11e7-9ac1-05d2c242c3f8.PNG)

Triggered by bootstrap-vue.esm.js:

```javascript
        // Register components
        for (var component in components) {
            Vue.component(component, components[component]);
        }
```

**Comment by nelson6e65** [comment]
I'm having this issue too when upgraded to vue 2.5.1.

**Comment by tmorehouse** [comment]
Interesting...  Might be something to do with the babel transpilation of the source code

**Comment by tmorehouse** [comment]
Or they changed how `Vue.component()` is called.

**Comment by aldrinmartoq** [comment]
I think it's that this code:

```js
components: { bFormCheckbox },
```

gets compiled into something like:
```
components: [bFormCheckbox],
```

which generates de warning. Not sure how to check what I'm saying.

**Comment by tmorehouse** [comment]
This (object key shortcut):

```js
components: { bFormInput }
```

is compiled from ES6 by babel to:

```js
components: {
  `bFormInput`: bformInput
}
```

So I don't think that is it.

**Comment by tmorehouse** [comment]
The original code snippit in the first comment is when Bootstrap-Vue plugs itself into Vue (registers all the components with Vue).  It does so one at a time as:

`Vue.component('bFormInput', bFormInput)`

the components variable is a has (object) keyed by component name (camelCased)

**Comment by nateslo** [comment]
![image](https://user-images.githubusercontent.com/5304468/31569185-d0447342-b02d-11e7-8285-bb80c6dbcb27.png)
I am seeing this error on bFormCheckboxGroup

**Comment by aldrinmartoq** [comment]
@tmorehouse this is what I see in the browser:

<img width="1001" alt="2017-10-13 07 44 39 pm" src="https://user-images.githubusercontent.com/388475/31569209-7fed4dde-b04f-11e7-964c-c92fe6671b39.png">

**Comment by nateslo** [comment]
https://github.com/bootstrap-vue/bootstrap-vue/commit/09187ead52ae3c4c781584593167a6a6c3d487f5

**Comment by humblecoder** [comment]
I'm still getting the error.  When should we expect the fix to be brought in?

**Comment by mihaben** [comment]
I'm also having the same problem.

Another component with the same problem is `form-radio-group.vue`

**Comment by tmorehouse** [comment]
Both of these have been fixed in the dev branch, and will be available when v1.0.0-beta.10 comes out (not sure when the release i going to happen, but hopefully soon).

**Comment by alexpilugin** [comment]
Have the same issue after upgrade vue cli today.
I use <b-container fluid>, <b-dropdown>, <b-dropdown-item> components in combination with vue-awesome (https://github.com/Justineo/vue-awesome)

**Comment by kriomant** [comment]
Until fix is released, I worked around it using:

```js
let originalVueComponent = Vue.component
Vue.component = function(name, definition) {
  if (name === 'bFormCheckboxGroup' || name === 'bCheckboxGroup' ||
      name === 'bCheckGroup' || name === 'bFormRadioGroup') {
    definition.components = {bFormCheckbox: definition.components[0]}
  }
  originalVueComponent.apply(this, [name, definition])
}
Vue.use(BootstrapVue)
Vue.component = originalVueComponent
```

**Comment by SReject** [comment]
Building off of @kriomant for browsers:

```html
        <script src="vue.js"></script>
        <script>((orig)=>{ // fix for boostrap-vue
           // store the original function globally
            _VueOriginalComponentFnc = orig;
            Vue.component = function(name, definition) {
                if ((
                    name === 'bFormCheckboxGroup' ||
                    name === 'bCheckboxGroup' ||
                    name === 'bCheckGroup' ||
                    name === 'bFormRadioGroup'
                ) &&
                    Array.isArray(definition.components) &&
                    definition.components.length === 1
                ) {
                    definition.components = {bFormCheckbox: definition.components[0]}
                }
                orig.apply(this, [name, definition])
            }
        })(Vue.component)</script>
        <script src="bootstrap-vue.js"></script>
        <script>(()=>{
            Vue.component = window._VueOriginalComponentFnc;
            delete window._VueOriginalComponentFnc;
        })()</script>
```

**Comment by tmorehouse** [comment]
If one includes the full Bootstrap-Vue library, the "workarounds" are not required (although the warnings will still show).

**Comment by imdunkind** [comment]
@kriomant, thx, its great!

**Comment by shtse8** [comment]
I have the same issue. Any help?

**Comment by tmorehouse** [comment]
The new release of Bootstrap-Vue v1.0.0-beta.10 (which also uses the new Bootstrap V4.beta.2 CSS) should be available soon.

**Comment by Sobient** [comment]
This, not surprisingly, also applies to Vue 2.5.2. 

![bilde](https://user-images.githubusercontent.com/706874/32039402-3df6f8e2-ba2e-11e7-8641-111b5177f90f.png)

**Comment by xtrimf** [comment]
same problem. waiting for beta.10

**Comment by tmorehouse** [comment]
beta.10 wont be released... we are removing the beta tag and releasing v1.0.0 mainline.

**Comment by xtrimf** [comment]
even better! are there any breaking changes?

**Comment by tmorehouse** [comment]
The only breaking change is if you are importing components individually.

we have a new file structure (as can be seen in the `dev` branch, and the distribution version (or if you run `yarn-build`) has all components/directives available as `es` transpiled builds in the `bootstrap-vue/es` directory.  Which should make importing individual components, and doing tree shaking (when importing the full library) much easier.

**Comment by Flygenring** [comment]
I do like the workaround by @kriomant and @SReject's additions until the fix is out!
But it's a little limited, so for the sake of completeness and people copying what they see, the substitution function shouldn't define the particular items to handle and should use the name for the key instead of always "bFormCheckbox"

    function(name, definition) {
        if(Array.isArray(definition.components) && definition.components.length === 1) {
            definition.components = {[name]: definition.components[0]};
        }
        originalVueComponent.apply(this, [name, definition])
    }

**Comment by alexsasharegan** [comment]
@Flygenring,

I suppose an even more complete monkey patch would be as follows:

```js
(function(v) {
  var componentFn = v.component
  v.component = function(name, definition) {
    if (Object.prototype.toString.call(definition.components) === "[object Array]") {
      var components = {}
      for (var i = 0; i < definition.components.length; i--) {
        var def = definition.components[i]
        components[def.name] = def.name
      }
      definition.components = components
    }
    componentFn.apply(this, [name, definition])
  }
})(window.Vue)
```

The one problem is that it assumes that all bootstrap vue components have defined their name property. I don't believe this is the case.

**Comment by tmorehouse** [comment]
This will all be cleared up once we get v1.0.0 release (soon I hope)

**Comment by 50l3r** [comment]
+1

**Comment by manasisharma** [comment]
+1

**Comment by lucasmike** [comment]
putting together @kriomant and @Flygenring code, here is a complete workaround for Node, works for me on the entire bootstrap-vue import:

`let originalVueComponent = Vue.component
Vue.component = function (name, definition) {
  if (Array.isArray(definition.components) && definition.components.length === 1) {
    definition.components = {[name]: definition.components[0]}
  }
  originalVueComponent.apply(this, [name, definition])
}

Vue.use(BootstrapVue)
Vue.component = originalVueComponent`
