### ISSUE TITLE
my output seems to be very large

### ISSUE THREAD

**Issue by pixelpaulaus** [bootstrap-vue/bootstrap-vue#1202]
my output bootstap-vue file seems to be 175KB under i minify it.
Is this right? i thought it was meant to be around 50KB.

i am kinda new to webpack so maybe i am doing it wrong. can someone please check, this is my config....

    var path = require("path");
    var CommonsChunkPlugin = require("webpack/lib/optimize/CommonsChunkPlugin");
    var ExtractTextPlugin = require('extract-text-webpack-plugin');
    var WebpackCleanupPlugin = require('webpack-cleanup-plugin');
    var UglifyJSPlugin = require('uglifyjs-webpack-plugin')
    var vendor = ['axios','vue','popper.js','tether'];
    var components = [path.resolve(__dirname, "resources/assets/bootstrap-vue/index")];

				module.exports = {
					entry: {
						//pages
						dashboard: path.resolve(__dirname, "resources/assets/js/dashboard"),
						blank: path.resolve(__dirname, "resources/assets/js/blank"), //stop pages like: activate, disabled
						test: path.resolve(__dirname, "resources/assets/js/test"),
						//vendor
						vendor: vendor,
						//additional
						components: components,
					},
					output: {
				    filename: "[name].bundle.js",
						path: path.resolve(__dirname, "public/assets"),
						publicPath: '/assets/',
						chunkFilename: "[id].chunk.js"
					},
					module: {
						rules: [
									{
										test: /\.vue$/,
										loader: 'vue-loader',
										options: {}
									},
									{
						         test: /\.js$/,
						         loader: "babel-loader"
						      },
				          {
					           test: /\.css$/,
					           loader: ExtractTextPlugin.extract("style-loader", "css-loader")
				          },
				          {
				              test: /\.scss$/,
											use: ExtractTextPlugin.extract({
												fallback: "style-loader",
												use:["css-loader","sass-loader"],
												publicPath: path.resolve(__dirname, "public/assets/css")
											})
				          }

									]
					},
					plugins: [

						new CommonsChunkPlugin({
							filename: "[name].bundle.js",
							name: ["vendor","components","commons"],
						}),
						new ExtractTextPlugin('css/[name].css',{
					      //allChunks: true
					   }),
						 new UglifyJSPlugin(),
						 new WebpackCleanupPlugin()
					]
				};

**Comment by tmorehouse** [comment]
175kb minified or 175kb minified+gziped?

The minified version of Bootstrap Vue is around 250kb, and 50kb when minified+griped
