### ISSUE TITLE
Minor doc typo

### ISSUE THREAD

**Issue by Alsciende** [bootstrap-vue/bootstrap-vue#1205]
at https://bootstrap-vue.js.org/docs/components/modal, first code example, `<p clas="my-4">` instead of `<p class="my-4">`.

**Comment by jonny-novikov** [comment]
It's already fixed https://github.com/bootstrap-vue/bootstrap-vue/commit/62916c14feb7774a02dd4b124cf7c8363cca6620 but not published yet
