### ISSUE TITLE
Popover div's are not removed after fast mouse-in and mouse-out

### ISSUE THREAD

**Issue by RobertDiebels** [bootstrap-vue/bootstrap-vue#1208]
**What happens?**
When normally moving the mouse in an out of a button element a connected pop-over is shown correctly. In the sense that the `div` which contains the pop-over is *removed* from the HTML `body` or any other container.

When moving the mouse in and out of a button at a fast pace, such that the hover event is triggered at a higher rate, the `div` element which contains the pop-over is *not removed* from the HTML `body` or any other container.

**What is my expectation**
That the pop-over `div` is removed regardless of the rate of hover events.

**Steps to reproduce**

1. Go to https://bootstrap-vue.js.org/docs/components/popover/#overview 
2. Open developer-tools and view the `body` element.
3. Find any button with a pop-over
4. Move the mouse in and out of the button at a fast pace.
5. Check the `body` element in the developer tools.
6. You will find that a `div` with an `id`-attribute like this `__BV_popover_1__` as been added to the `body` multiple times.

**Comment by tmorehouse** [comment]
Confirmed for both directive and component popovers, as well as tooltips

**Comment by tmorehouse** [comment]
It appears to have something to do with the transition timing. If a transition is still in progress during hide, and the tooltip/popover is triggered to open before the transition finishes.

**Comment by mert574** [comment]
Waiting for the new release.

[Example reproduction](https://gyazo.com/e1d210fe8cc8a159a20429ea22f235e2)

As you can see, definitely not usable in this state. It especially affects SPA with inner scrolling.

**Comment by devsnd** [comment]
BTW: you can use the `no-fade` option as a workaround for now, which just disables the animations that glitch like that.

So `<b-popover no-fade>something<b-popover` and  `<div v-b-popover.nofade.hover="'hello'"></div>` for the directive style.

**Comment by tmorehouse** [comment]
Release v1.0.0 (non-beta) will be coming soon (hopefully today or tomorrow), and will have the fix for this.

**Comment by landor** [comment]
I still get this happening with 1.0.2.
https://jsfiddle.net/rmtw5kpr/
Run the mouse into the button to let the tooltip fade in completely, then quickly move the mouse out, in, out, then you are left with an empty popover fragment.

**Comment by tmorehouse** [comment]
I've tried the fiddle and cat reproduce the issue.  I see the div linger sometimes (in firefox devtools), but it always goes away.

I even updated the fiddle to explicitly use `@1.0.2` (instead of `@latest`, which may have cached an older version) https://jsfiddle.net/rmtw5kpr/2/ and still do not see the issue occurring.

**Comment by landor** [comment]
This was recorded in FF57.0 at https://jsfiddle.net/rmtw5kpr/2/
![peek 2017-11-17 10-09](https://user-images.githubusercontent.com/1020135/32953927-b2616c0a-cb7f-11e7-8575-9fa717db4792.gif)
