### ISSUE TITLE
Doc: webpack: style-loader is not enough, also needs css-loader

### ISSUE THREAD

**Issue by feinstaub** [bootstrap-vue/bootstrap-vue#1209]
On https://bootstrap-vue.js.org/docs there is a note to add style-loader. What is missing is that for Webpack, the webpack.config.js must be adpated like this:

      {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      }

as I found here: https://github.com/shama/letswritecode/issues/8

**Comment by mosinve** [comment]
True, also webpack configuration to import `*.css` files from `*.js` described in official webpack guide:
https://webpack.js.org/guides/asset-management/#loading-css
