### ISSUE TITLE
<b-form inline> conflict with <b-form-group label-text-align>

### ISSUE THREAD

**Issue by ymoreiratiti** [bootstrap-vue/bootstrap-vue#1211]
When using the directive "inline" in "b-form" tag, the "b-form-group" inside is not aligned. Even if i used label-text-align

[Fiddle](https://jsfiddle.net/cdL5mo6f/1/)

The example above is the same of [docs](https://bootstrap-vue.js.org/docs/components/form), with directive inline

**Comment by tmorehouse** [comment]
b-form in inline mode is not mean to be used with b-form-group (currently), as b-form in inline mode is for placing all regular inputs (not form-groups) on a single line.
