### ISSUE TITLE
b-modal new slot "modal-content"

### ISSUE THREAD

**Issue by tjunussov** [bootstrap-vue/bootstrap-vue#1212]
It would be nice to have one global slot for whole "modal-content" on line https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/modal.vue#L37

> my usecase is : I have rest api request when i show modal ( request is handling more than 1s ) 
> when i click link, i would like to show modal dialog instantly with loading inside, when data loaded i would like to show my component inside this modal which simulates as modal header,body,footer view

**Comment by tmorehouse** [comment]
You can currently disable the modal header and footer via the `hide-header` and `hide-footer` props, leaving one with an empty modal-container, of which one could place any content, including a custom header and footer.

**Comment by tjunussov** [comment]
Thankx, I did like u said, with one addition, I have to add "negative margins" to modal-body
