### ISSUE TITLE
Scoped slot bottom-row. Possible bug

### ISSUE THREAD

**Issue by Zanobos** [bootstrap-vue/bootstrap-vue#1215]
Hello, while using scoped-slots "bottom-row" I always get an error (I'm trying to access a property on an undefined object). I think the problem comes from this line:

 `           <tr v-if="$scopedSlots['bottom-row']">
                <slot name="bottom-row"
                      :columns="computedfields.length"
                      :fields="computedFields"></slot>
            </tr>`

in this file: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/table.vue

because, as you can see, there is an error in the name "computedfields" (the F is not Camelcase).

In fact if you check "top-row" everything is correct.

Have a nice day,
Andrea

**Comment by mosinve** [comment]
Thx for reporting. Fixed, will be available with next release.

**Comment by Zanobos** [comment]
Thank you very much, awesome!
