### ISSUE TITLE
b-progress should apply the heigth prop to itself

### ISSUE THREAD

**Issue by Yamakaky** [bootstrap-vue/bootstrap-vue#1216]
Otherwise, it keeps its `1rem` default value.
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/progress.vue

**Comment by tmorehouse** [comment]
This is coming as Bootstrap V4.beta.2 changes how the heights will be applied.  Current Bootstrap V4.beta.1 applies height to the individual progress-bars, V4.beta.2 will be changing this and Bootstrap-Vue will adjust once V4.Beta.2 is released.

**Comment by Yamakaky** [comment]
Oh, OK. So "wait for it"? ^^

**Comment by tmorehouse** [comment]
This should be available in the next release of Bootstrap-Vue (v1.0.0.beta.10)

**Comment by Yamakaky** [comment]
Nice!

**Comment by xidedix** [comment]
Arbitrary setting default `height` to `1rem` for `b-progress` takes precedence over (and overwrites) class styling, or am I missing something here?

**Comment by mosinve** [comment]
you should set progress height by `height` prop, as shown here https://bootstrap-vue.js.org/docs/components/progress#width-and-height

**Comment by xidedix** [comment]
I see how it works, just wondering why is that. 
And how to set a `height` of b-progress using CSS class only?

**Comment by tmorehouse** [comment]
Originally the heights had to be set on the individual progress bars inside the progress container (and the default was 1rem in CSS) in Bootstrap V4.beta.1.  bets.2 has moved this to the parent progress container.

We'll see about removing the default `1rem` so that it can fall back to the new beta.2 CSS default.

**Comment by Yamakaky** [comment]
Just tested the fix, it works fine!
