### ISSUE TITLE
b-nav-item-dropdown toggles wrong class

### ISSUE THREAD

**Issue by Doeke** [bootstrap-vue/bootstrap-vue#122]
Currently the dropdown menu is not displayed without additional css, because It should toggle the class "show" and not "open" (bootstrap 4).

**Comment by Doeke** [comment]
Similar bug for tabs, it applies "in" class instead of "show", leaving tab content invisible without extra css:

`.fade.in { opacity: 1.0 }`

**Comment by pi0** [comment]
@Doeke it apeears this was changed in recent bootstrap alpha versions, as `alpha-6` (and like docs) `show` is the correct class.which version are you using ?

**Comment by Doeke** [comment]
Ah, yes, I did upgrade to `alpha-6`. Can you support both classes?

**Comment by pi0** [comment]
@Doek yes of course :) Feel free opening PR for that
