### ISSUE TITLE
<b-navbar> content width

### ISSUE THREAD

**Issue by mhldtna** [bootstrap-vue/bootstrap-vue#1227]
This simple template displays in what seems to be just one column, rather than full-width on my laptop screen.  The doc says that \<b-card/\> "... naturally fill(s) the full width of its parent element..." so I think \<b-navbar\> is setting the width incorrectly.

\<b-navbar\>
\<b-card border-variant="primary"\>
	some text
	\</b-card\>
\</b-navbar\>

I tried a number of variations, such as this one.  None make the card take the full-width of the screen.

\<b-navbar toggleable="lg"\>
    \<b-nav-toggle target="nav_collapse"\>\</b-nav-toggle\>
	\<b-collapse is-nav id="nav_collapse"\>
	    \<b-nav pills fill is-nav-ba\r>
			\<b-card border-variant="primary"\>
			some text
			\</b-card\>
		\</b-nav\>
  \</b-collapse\>
\</b-navbar\>

**Comment by mhldtna** [comment]
I noticed that the width of the card seems to depend upon the amount of text. So I tried forcing a full-width card by specifying a CSS width style. It doesn't help.

I also tried adding the \<b-card-body\> and "card-text" classes as mentioned in the doc -- none of which worked.

**Comment by mhldtna** [comment]
Using this OUTSIDE a <b-navbar> gives me a full-width card:

`			<b-card border-variant="primary">
				<b-card-body>
					<p class="card-text">
						some text that takes lots and lots and lots of space
					</p>
				</b-card-body>
			</b-card>`

**Comment by mhldtna** [comment]
(Wish this tool handled embedded \< ... \> text.  I tried to say "Using this OUTSIDE a \<b-navbar\> gives me a full-width card:")

(Also wish this tool didn't drop newline characters in inserted code.)

**Comment by tmorehouse** [comment]
Anything placed inside a navbar becomes a flexbox.

I am guessing that cards would also change to a flexbox when placed inside a navbar (regardless if you are using Bootstrap-Vue or plain Bootstrap V4).

You would need to provide your own over-ride CSS to control the width of a card inside a navbar (which I am guessing is not supported by default in Bootstrap V4 CSS)

**Comment by tmorehouse** [comment]
See the list of supported content types for navbar at: https://bootstrap-vue.js.org/docs/components/navbar#supported-content

**Comment by tmorehouse** [comment]
And at http://getbootstrap.com/docs/4.0/components/navbar/

**Comment by mhldtna** [comment]
This brings up an underlying confusion on my part or maybe incomplete doc:  I don't want the card to be part of the navbar.  I want to have tabs or pills in the navbar that show different tabs, each with their own content.  I have no problem doing this with plain \<b-tab\>, where the content of each tab is within the \<b-tab\> ... \</b-tab\> section.

The nav doc, under the title "Tabbed Content Support" says only "See the \<b-tabs\> component."  So my initial attempt was just to wrap my existing (and working) tabs with nav and navbar.  But then the tabs displayed in only about a third of the screen. So then I started playing around with cards just to simplify things.  I wish this part of the doc were clearer.

The navbar doc shows a \<b-nav-item\> tag, used to create tabs in the navbar.  But it doesn't show where to put the tab content.  When I put that tab content as a child of nav-item, it shows up in the nav bar.  When I put it outside the nav section, it shows up only on the first tab.

I simplified my example above so much that I dropped the tabs or nav-items from it and left the card in the nav area.  The attached example shows more clearly what I am trying to do.  (It should be a .vue file but this site won't let me attach that file type.)

[example.txt](https://github.com/bootstrap-vue/bootstrap-vue/files/1408480/example.txt)

**Comment by tmorehouse** [comment]
If you are looking for pill or tab styling in your navbar, just use regular `b-nav` inside your navbar and set teh `pills` or `tabs` props on `b-navbar`.  `b-tabs` and `b-tab` are a completely different beast compared to a navbar,

**Comment by tmorehouse** [comment]
What you need a variable in your apps `data` which specifies which tab (actually a card in this case) to show.

Then either use `v-if` to show the appropriate card, or make each card a separate custom component, and use `<component :is="whichCard" />` to show the appropriate sub card component.

See https://vuejs.org/v2/guide/components.html#Dynamic-Components for a basic example of dynamically showing components.

Another option is to use vue-router to control which component/tab/card is shown.

**Comment by mhldtna** [comment]
Thanks, this solved it for me.

(I had no clue that I needed to use a dynamically-mounted component. It would be nice if the doc showed how to do this.)

**Comment by tmorehouse** [comment]
`<b-tabs>` is really a presentational component (similar to collapse, but with a different user interface), where as `nav` is a navigational component

**Comment by mhldtna** [comment]
Well, the doc for b-nav, under "Tabbed Content Support", implies that you use b-tab with b-nav.  At the least, that is misleading.

**Comment by tmorehouse** [comment]
It is based on b-nav (the tabs).  It doesn't imply that it is used in conjunction with.  In the offiical bootstrap Docs (which people should be familiar with), has details about tabbed content under nav section (as one must manually build tabbed content with navs in regular bootstrap), but since we have to use a separate component to create tabs, the docs points to the b-tab documentation which doesn't talk about b-nav at all, and gives a complete example of how b-tabs/b-tab works.
