### ISSUE TITLE
Module build failed: TypeError: this._init is not a function at Object.Vue$2

### ISSUE THREAD

**Issue by neolite** [bootstrap-vue/bootstrap-vue#123]
![2017-03-01 19 42 52](https://cloud.githubusercontent.com/assets/576423/23464653/990cf11a-feb7-11e6-8a00-45f392b39e5f.png)

I created project using vue-cli, and after updating project to latest 0.9.2 i  see this bug.
Please help me to fix this bug.

**Comment by pi0** [comment]
@neolite Would you please provide more information about your webpack build script? (It seems you are importing directly components not commonjs version)

**Comment by pi0** [comment]
Closing due inactivity. feel free to re-open if problem exits.
