### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by costerhout** [bootstrap-vue/bootstrap-vue#1230]
Minor edit. In the docs for "Layout and Grid System" page (https://bootstrap-vue.js.org/docs/layout/), the following quote:
--------%<---------
Grid tiers are based on minimum widths, meaning they apply to that one tier and all those above it (e.g., <b-col-sm="4"> applies to small, medium, large, and extra large devices).
--------%<---------

Should read (no '-' between 'b-col' and 'sm="4"):
--------%<---------
Grid tiers are based on minimum widths, meaning they apply to that one tier and all those above it (e.g., <b-col sm="4"> applies to small, medium, large, and extra large devices).
--------%<---------

**Comment by tmorehouse** [comment]
This has been fixed in the dev branch and will be available in the next release of Bootstrap-Vue.
