### ISSUE TITLE
navbar fixed="top"  with b-nav-item causes navbar to overlap tab contents

### ISSUE THREAD

**Issue by mhldtna** [bootstrap-vue/bootstrap-vue#1232]
Using this example:

    <div>
	<b-navbar fixed="top">
		<b-nav>
			<b-nav-item active>Tab One</b-nav-item>
			<b-nav-item>Tab Two</b-nav-item>
		</b-nav>
	</b-navbar>
	some text
</div>

The navbar tabs and the text overlap each other.  Sure seems like a bug.

Adding "is-nav-bar" to the b-nav component just makes it worse: the tabs go down the left side instead of across the top.  See issue #1229 .

**Comment by mhldtna** [comment]
Workaround: adding a couple <br> tags before "some text" makes it look ok visually.

**Comment by mhldtna** [comment]
That "fixed=top" option is supposed to keep the navbar fixed at the top of the screen when you scroll.  But it doesn't work.

**Comment by tmorehouse** [comment]
Are you sure you are including the correct version Bootstrap CSS File?  IT should be (for release v1.0.0-beta.9) version V4.0.0.-beta.1 Bootstrap CSS.  V41.0.0-alpha.# has manyu differences, as does the new Bootstrap V4.0.0-beta.2 (which was just released).

Fixed navbars become absolutely positioned in the viewport, and hence do not "occupy" space in the body of the document (and does not push your content down).  You need custom CSS styles to push your body down (such as adding padding equal to the height of your navbar, or using a margin on a container that holds your main document content).

sticky navbars, however, do occupy space in the document, and will push your content down by their height.  But note that not all browsers support position:sticky.

**Comment by tmorehouse** [comment]
You may want to refer to the official Bootstrap V4 documentation regarding how fixed-top works: http://getbootstrap.com/docs/4.0/components/navbar/#placement

**Comment by mhldtna** [comment]
Hmm, "npm list bootstrap" shows:
   `vue-cli-specpro@1.0.0 C:\neonworkspaceOnC\vue-specpro`
    `-- bootstrap-vue@1.0.0-beta.9`
    `-- bootstrap@4.0.0-beta`

I believe that it was setup this way by vue-cli.  Should I replace the bootstrap version?  Will I be buying into migration problems with bootstrap-vue goes to the next version of bootstrap?  Where would I have found out which version of bootstrap I should be using?

Fixed versus sticky is not well explained in the bootstrap-vue doc.

**Comment by tmorehouse** [comment]
Fixed and sticky is a CSS terminology.  `position:fixed` & `position:sticky`.  These are not a bootstrap or bootstrap-vue terminology.  If one is familiar with CSS (which they should be when developing for the web) one should quite easily understand what they do.

Some people manually include the links in the top of their project vs. using a build system to include it.

The version is listed in the getting started documentation, and in the package.json file.

**Comment by mhldtna** [comment]
My solution is to use 'fixed="top"' on the b-navbar, "margin-top: 60px" on the content, and this style:

    .fixed-top {
	background-color: white;
    }

This works but it took an inordinate amount of research to get there.  I don't see anything in either the bootstrap or bootstrap-vue doc that discusses this.

**Comment by tmorehouse** [comment]
This google search returns many results with "solutions": [bootstrap fixed navbar top overlap](https://www.google.ca/search?dcr=1&q=bootstrap+fixed+navbar+top+overlap&oq=bootstrap+fixed+navbar+top+overlap&gs_l=psy-ab.3..0i22i30k1l2.24292.27048.0.27487.7.7.0.0.0.0.155.803.0j6.6.0....0...1.1.64.psy-ab..1.6.797....0.ZaAsR36sK1U)
