### ISSUE TITLE
I've read every issue and all the docs, but I can't figure out "unknown component.."

### ISSUE THREAD

**Issue by tobinmwalton** [bootstrap-vue/bootstrap-vue#1233]
I'm pretty new to Vue but I think I understand registering components, I'm using quite a few of my own custom components already. However, I don't understand BootstrapVue. I've followed the quick start instructions and imported into my main.js:

```
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'
import App from './App'
import router from './router'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'

new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})

Vue.use(BootstrapVue);
```

Then in one of my components, I attempt to use the "b-button" tag. The button renders, but only until I refresh the page or do some other action. Message in the console says: "[Vue warn]: Unknown custom element: <b-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option."  

Am I expected to somehow register every BootstrapVue component that I use, somehow?

A simple example project would be worth a thousand words here.

**Comment by JamieLottering** [comment]
Could be some race condition? Try putting `Vue.use(BootstrapVue);` before you create the Vue instance and see if that helps.

**Comment by tmorehouse** [comment]
Bootstrap-Vue must be registered before anything can use it.  Since it is called after your app instantiation (`new Vue({...})`), none of the components are available.

Remember that JavaScript is single threaded.  It runs from top down.

**Comment by tobinmwalton** [comment]
@tmorehouse Thanks, that's what I needed. Greatly appreciated.
