### ISSUE TITLE
Setting carousel interval to 0 does not disable interval.

### ISSUE THREAD

**Issue by jaesung2061** [bootstrap-vue/bootstrap-vue#1235]
I'm using the default example provided in the documentation. I've set `:interval="0"`.

I put a `console.log(this.interval)` statement at this line: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/carousel.vue#L231.

I'm getting an alternating number of 0 and 5000 (the default), based on the number of carousel items.

Also, manually changing the slide should reset the interval so it doesn't change the slide immediately after clicking one of the controls.

**Comment by tmorehouse** [comment]
I've just tried setting interval to `0` in the latest dev docs site and do not see the issue you are seeing with the interval value.

I will see what we can do to reset the interval when clicking on one of the controls (or manually setting a value through v-model)

**Comment by jaesung2061** [comment]
I was using the same model for 2 different carousels which was causing this.
