### ISSUE TITLE
How to write custom components?

### ISSUE THREAD

**Issue by dstN** [bootstrap-vue/bootstrap-vue#1238]
Hi, 

i started to use Bootstrap4 and vue few weeks ago and now found out that you guys are making this awesome bootstrapVue Library. 

i'd like to know how i could write custom bootstrap components on my own? maybe i'm too stupid to find your source files but everytime i look at some sources it just looks like plain jscript with no markup or anything templating wise. (e.g. <b-container> or some sort of that stuff) - where do you put those things together? am i missing something?

and if i use static file-delivery (e.g. without webpack / yarn etc.) is it even possible to add those custom components? and if yes - how? i tried to make some custom components just through vue (without bootstrap) and couldn't add them.

**Comment by tmorehouse** [comment]
Some components have templates (regular components which filenames end in `.vue`), and some use render functions instead o templates (usually files that end in `.js', which are "functional" components which do not have a 'this' context, nor have any state).

Bootstrap-Vue uses a JavaScript build environment, where the individual files are "compiled" into a single larger library.

If you haven't already, I would recomend reading over the VueJS documentation on custom components (and functional components/render function) at https://vuejs.org/v2/guide/components.html
