### ISSUE TITLE
@click.native executes two times on <b-form-checkbox>

### ISSUE THREAD

**Issue by nc-csl** [bootstrap-vue/bootstrap-vue#1240]
Hi,
I have an issue with b-form-checkbox and b-form-checkbox-group. When I use @click.native, the method I call, is executed two times. Also, if I write my selected (array) values directly into the DOM {{selected}}, I see the correct elements in the array. However if I console.log my selected array in the method I call on @click.native, when clicking a checkbox, it is empty. When I then click the checkbox again (so it is unchecked), my console.log displays the element in my selected array.

    {{selected}}

    <b-form-checkbox-group
      stacked
      :options="options"
      v-model="selected"
      @click.native ="filterTable"
    ></b-form-checkbox-group>

And my filtertable is just a console.log

    filterTable(){
        console.log(this.selected);
      }

If I use @mouseup.native filterTable is only called one time. However the selected array behaves the same. In the DOM it shows correct, but in my method the selected array is inverted.

I created a fiddle for it. https://jsfiddle.net/y998pLya/6/
Thank you.

**Comment by mosinve** [comment]
it would be better to attach to `onChange` event to track changes in input.

**Comment by nc-csl** [comment]
So what I am trying is to create filtering on the bootstrap-vue table. So in my th element I have added a dropdown with checkboxes for each unique element in the column. If I simply use @change or @input on the checkbox, it does not behave like it should. I can't check it, because it activates the sort method on the table header (standard functionality in bootstrap-vue table). Whenever I use @click.native.stop, the checkbox behaves correctly because I stop propagation. However the selected array is acting strange.
Do you mean @change when you write onChange?

**Comment by mosinve** [comment]
Speaking of who emits two click event..
![image](https://user-images.githubusercontent.com/20986566/31988349-6ff8047e-b977-11e7-89eb-c527a7f810ae.png)

**Comment by nc-csl** [comment]
Sorry that was a mistake. The @change should not be there.

**Comment by mosinve** [comment]
did you checked jsfiddle i write? is it work as you expected?

**Comment by mosinve** [comment]
In your example two click events emitted by checkbox itself and by it;s label..
You SHOULD use either @change="" or setup a watcher for v-model variable, to be able exec your desired function.

**Comment by nc-csl** [comment]
Okay thanks. I will try that. Do you know if it is possible to do stop propagation on @change ?

**Comment by mosinve** [comment]
i suppose, then v-model may stop work, as it's a syntax sugar for 
```
:value="selected" 
@change="selected = $event.target.value"
```
even @change work well,  I'd better use watchers.
