### ISSUE TITLE
<b-image src="/.svg">

### ISSUE THREAD

**Issue by maraal** [bootstrap-vue/bootstrap-vue#1245]
Hello. This is my issue: when my attribute `src` in my  `<b-img>` appoint for a svg, the console says 404. But if i set some url for the `src`, this works well. If i try with `<img>`, the svg load too.

Didn't work:

`<b-img src="../assets/SVG/logo-home.svg" fluid alt="logo-home.svg">`
 
Work: 

`<b-img src="http://verdao.net/imgs/noticias/moises_30_home.jpg" fluid alt="logo-home.svg" `

Work:

`  <img src="../assets/SVG/logo-home.svg"  alt="logo-home.svg">`

I am using the Nuxt.js.

I try  `<b-img src="assets\Ativo2.png"  alt="logo-home.svg">`  now and not works too, no error, but not render.

**Comment by tmorehouse** [comment]
Vue loader only understands (by default) native `<img>` and `<image>` tags when resolving images from your asset directories.

You need to configure vue-loader to understand the `<b-img>` component `src` attribute.

See the documentation a : https://bootstrap-vue.js.org/docs/reference/imgages for  few options on configuring the "transformToRequire"

**Comment by tmorehouse** [comment]
If for some reason you cannon configure the vue-loader `transformToRequire` option, you can use teh following webpack workaround:

```html
<b-img :src="require('~/assets/img/picture.jpg')" />
```

**Comment by nekdolan** [comment]
@maraal the solution is to change the build config in the nuxt.config.js @tmorehouse  I think this should be added to the BV documentation so that people may find it at: https://bootstrap-vue.js.org/docs/reference/images/

```
build: {   
    extend (config, ctx) {
      const vueLoader = config.module.rules.find((rule) => rule.loader === 'vue-loader')
      vueLoader.query.transformToRequire = {
        'img': 'src',
        'image': 'xlink:href',
        'b-img': 'src',
        'b-img-lazy': ['src', 'blank-src'],
        'b-card': 'img-src',
        'b-card-img': 'img-src',
        'b-carousel-slide': 'img-src',
        'b-embed': 'src'
      }
    }
  }
```

**Comment by tmorehouse** [comment]
@nekdolan We have just added your example above to the reference section.

**Comment by nekdolan** [comment]
@tmorehouse I have reinstalled my whole code an I noticed that the vueLoader I now have does not have the query attribute so I had to use the options attribute. See also:  https://github.com/nuxt/nuxt.js/issues/956 

```
{
  build: {   
    extend (config, ctx) {
      const vueLoader = config.module.rules.find((rule) => rule.loader === 'vue-loader')
      vueLoader.options.transformToRequire = {
        'img': 'src',
        'image': 'xlink:href',
        'b-img': 'src',
        'b-img-lazy': ['src', 'blank-src'],
        'b-card': 'img-src',
        'b-card-img': 'img-src',
        'b-carousel-slide': 'img-src',
        'b-embed': 'src'
      }
    }
  }
}
```

So it depends on the version, but I am not entirely sure which is which

**Comment by jonalxh** [comment]
Not working for me with `b-img-lazy`, I've tried by adding the piece of code you suggest [here](https://bootstrap-vue.org/docs/reference/images#configuring-transformasseturls-in-nuxtjs) and nothings happens:

```
 build: {
    extend(config) {
      const vueLoader = config.module.rules.find(rule => rule.loader === 'vue-loader')
      vueLoader.options.transformAssetUrls = {
        video: ['src', 'poster'],
        source: 'src',
        img: 'src',
        image: 'xlink:href',
        'b-avatar': 'src',
        'b-img': 'src',
        'b-img-lazy': ['src', 'blank-src'],
        'b-card': 'img-src',
        'b-card-img': 'src',
        'b-card-img-lazy': ['src', 'blank-src'],
        'b-carousel-slide': 'img-src',
        'b-embed': 'src'
      }
    }
  }
```

Tried with `transformAssetUrls` and `transformToRequire` but none of them work, I'm using Nuxt and BootstrapVue/nuxt, the docs say that working with the latest version does it automatically, but currently it is not working in SSR mode, everything works if I use just a plain `<img>` tag or `b-img`, but not working with `b-img-lazy`.
