### ISSUE TITLE
[b-tabs] Manually added tabs in the "tabs" slot don't resize well

### ISSUE THREAD

**Issue by Sobient** [bootstrap-vue/bootstrap-vue#1248]
When using the `small` attribute on b-tabs and adding a button in the template slot, the padding for the button (the + in the picture) is off as the picture below shows: 

![bilde](https://user-images.githubusercontent.com/706874/32054835-0a9564fc-ba60-11e7-8342-58fef59e9967.png)

`<b-tabs card lazy small v-model="tabIndex">`

One can easily replicate this issue on the[ live docs page for dynamic tabs](https://bootstrap-vue.js.org/docs/components/tabs/#dynamic-tabs) as well.

**Comment by tmorehouse** [comment]
Have you tried using any of the bootstrap utility classes on the `+` to adjust its position (i.e. the margin adjustment classes or passing adjustment classes, see https://bootstrap-vue.js.org/docs/reference/spacing and http://getbootstrap.com/docs/4.0/utilities/spacing/)?

**Comment by tmorehouse** [comment]
I have discovered what you need to do.  On your blank tab `<b-nav-item>`, you need to manually add the `small` class to it.  Only the `<nav-items>` added dynamically via `<b-tab>` components get the `small` class when the `small` prop is added to `<b-tabs>`.

```html
<b-card no-body>
  <b-tabs small card>
   <b-tab ...> ... </b-tab>
   <b-tab ...> ... </b-tab>
   <b-nav-item slot="tabs" class="small" @click.prevent="newTab" href="#">
    +
   </b-nav-item>
  </b-tabs>
</b-card>
```

Currently the `small` class gets added to each `<b-nav-item>` that is defined by a `<b-tab>`.  We may need to move the `small` to the parent `ul.nav` wrapper.  This will case the small size to be inherited by all of the tab controls.

**Comment by Sobient** [comment]
It doesn't make sense to manually re-work any additional buttons added to the toolbar with the correct size; they should automatically get the right one since they belong to the same parent anyway. 

Thanks for patching it in.
