### ISSUE TITLE
Add body-class for b-card

### ISSUE THREAD

**Issue by shtse8** [bootstrap-vue/bootstrap-vue#1249]
I can set header-class and footer-class, but I can't find any body-class property provided.
atm, I need to set no-body and create b-card-body myself for setting body-class.
any help? thanks.

**Comment by tmorehouse** [comment]
Currently you need to use use no-body option, and place your own b-card-body component inside b-card to get around this, as the regular variant classes apply to the full card (in indirectly get inherited by the internal card body.

We'll see if we can get body options in a near future release.
