### ISSUE TITLE
Navbar brand not working when inverse

### ISSUE THREAD

**Issue by sosensible** [bootstrap-vue/bootstrap-vue#125]
When setting the code as follows, the brand text remains dark when it should be light.

```
    <b-navbar toggleable fixed="top" type="inverse" variant="inverse">
      <b-nav-toggle target="nav_collapse"/>
        <a class="navbar-brand" to="/">
           <span>OLS</span>
        </a>
```

I pasted in the standard BS HTML and got the right result.

```
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse mb-4">
      <a class="navbar-brand" href="#">Navbar</a>
```

So something is not working. Chrome devtools shows the class being over powered by another class.

```
a:not([href]):not([tabindex]) {
    color: inherit;
    text-decoration: none;
}
```

So I tried this in my .vue file for styles.
```
<style scoped>
.navbar-brand span{
  color: #ffffff;
}
</style>
```

While that fix works for me, not sure how to fix that for others.

**Comment by pi0** [comment]
Hello @sosensible  Please double check that component's props are correct like this: (both _type_ and _variant_ should be set)

```<b-navbar toggleable type="inverse" variant="inverse">```

**Comment by sosensible** [comment]
I copied and pasted your code and without my CSS hack the navbar-brand is still invisible.

**Comment by mosinve** [comment]
changing this
` <a class="navbar-brand" to="/">`
to this
` <a class="navbar-brand" href="/">` solves trouble for me

**Comment by pi0** [comment]
Closing due inactivity. feel free to re-open if problem exits.
