### ISSUE TITLE
Bug: Form Feedback does not work correctly if you use an Input Group

### ISSUE THREAD

**Issue by rdytogokev** [bootstrap-vue/bootstrap-vue#1251]
I am trying to setup a login form that has an input group and a validation error message.

> NOTE: If you understand pictures better, I have included one below to explain this.

After looking thru the documentation I see that if I wrap a `< b-form-input >` inside of a `< b-input-group >` I can accomplish the Bootstrap Input Group.  I did and it works as expected.

Now I would like to make use of `< b-form-feedback >`. This is where my problem (which I suspect is a bug happens). 

(1) The `< b-form-feedback >` never displays my error message if I place it just after the closing `</ b-input-group >`. 

(2) If I place it inside the `< b-input-group >` it displays, but totally messes up the styling.

Please help!
![bootstrap-vue-error](https://user-images.githubusercontent.com/2678654/32078279-67d1ae32-ba74-11e7-8a8f-645ab82a3b3f.png)

**Comment by tmorehouse** [comment]
This is a well know documented bug/feature/limitation with Bootstrap V4 CSS (see several other duplicate issues).

Unfortunately it is not something we can control since it is governed by Bootstraps CSS, and how their new validation feedback works (based on sibling selectors and native browser validation)

Please give your voice/concerns over at twbs/bootstrap: https://github.com/twbs/bootstrap/issues/23454

**Comment by rdytogokev** [comment]
thanks.

**Comment by tmorehouse** [comment]
Lots of people are annoyed that there is no easy way to use the new invalid feeback system within input group (whcih out a bit of hackery), and that the input group/addons are not styled when invalid or valid.

I have some CSS that will style the input group if hte input group or a parent element has the `is-invalid` or `is-valid` classes, but unfortunately the colors are hardcoded and not tied to the boostrap SASS variables.

Was tempted to add it to the `b-input-group` component, but it wouldn't get styled correctly if someone uses a custom theme or bootstrap CSS build.

**Comment by rdytogokev** [comment]
You just gave me an idea for a simple workaround, what do you think about this:
`< b-form-feedback class="d-block" v-if="$v.email.$error" >`

With this solution, you still get bootstrap styling (even when sass is in play) and you can use v-if to some boolean that handles your validation. (In my example, I am using Vuelidate and now everything works as intended.)

**Comment by tmorehouse** [comment]
b-form-feedback onloy shows when it is a _post_ sibling of an input that is either `:invalid` or has the class `.is-invalid`

So v-if really wont help, as it is the CSS that shows or hide the resultant element with the `.invalid-feedback` class :(

**Comment by tmorehouse** [comment]
You could use `b-form-text`, which is always shown... just override the default `text-muted` class with say `text-danger` class.  You would just need to flag it is `role="alert"` and associate the input with it by using `aria-describedby` to point to the ID of the help text.

**Comment by rdytogokev** [comment]
> b-form-feedback only shows when it is a post sibling of an input that is either :invalid or has the class .is-invalid

I know that the way Bootstrap was intended to work requires them to be sibling elements. But the idea I came up with does work.

Here it is again:
`< b-form-feedback class="d-block" v-if="$v.email.$error" >` 

The `class="d-block"` part overrides bootstrap's built-in `display` property with a value of `block;`. This in turn makes `< b-form-feedback >` always visible (even when no validation error is present). But it has the correct Boostrap styling for an error (even if you are using SASS).

Then using `v-if` allows me to choose when it will display programmatically. I am using the Vuelidate validator package. This validator is going to be way more stringent than the built-in HTML5 validations. 

Vuelidate validates the **model** instead of the **input** and generates a $v object that I can check for validation errors.  (So for example `$v.email.$error` is a boolean value based on whether there is an error with `< b-form-input v-model="email" >`.) So, because I can check a variable to determine if there is an error, I can place `< b-form-feedback >` anywhere in my component's template (even if it is nowhere near the `< b-form-input > ` and it will still work - **only displaying when an actual error occurs**).

I know that this workaround is very specific to people using bootstrap-vue with vuelidate. It won't work for out-of-the-box HTML5 validations. But since I am using a Validation package, I don't need to rely on the built-in HTML5 `:invalid` or `.is-invalid` classes on the `< b-form-input >` component.

This is my thinking.  Am I missing anything?

**Comment by tmorehouse** [comment]
Hmmm this might work.

And if you are using b-form-group, you can skip supplying a value to the `feedback` prop, and just stick your own `b-form-feedback` after your input(s)/input-group (before the closing `<b-form-group>` tag)and display it when you want.

**Comment by rdytogokev** [comment]
Yep,

I just tested it and it is working.
<img width="420" alt="screen shot 2017-10-27 at 3 32 32 pm" src="https://user-images.githubusercontent.com/2678654/32121810-20cf60a2-bb2c-11e7-91d9-5f9e3e7c70c8.png">
<img width="488" alt="screen shot 2017-10-27 at 3 33 30 pm" src="https://user-images.githubusercontent.com/2678654/32121837-377e11fe-bb2c-11e7-9ccc-57f5057094cc.png">

**Comment by tmorehouse** [comment]
You can appl;y a state to teh b-form-group (we have special CSS for that case), which will display the built feedback specified via the feedback `prop`, which works only for hte so-called "server-validation".

We place an `is-invalid` (or `is-valid`) class on the form-group, and then use a child selector to display the form-feedback.  You sill need to set the state on the input as well to color it.

**Comment by tmorehouse** [comment]
i.e.

```html
<b-form-group 
  label="Input"
  description="Some Description"
  :state="false" feedback="Something is Wrong">
  <b-input-group left="Email">
    <b-input type="email" :state="false" />
  </b-input-group>
</b-form-group>
```

Will show the invalid feedback even though it is not a sibling of the input.

**Comment by rdytogokev** [comment]
I did not realize that you had that option.  That would work too.  I love that Bootstrap-Vue and Bootstrap are flexible enough to make things work so many different ways.

**Comment by tmorehouse** [comment]
Yeah, I added that special case CSS in to handle input-groups (and groups of checkboxes/radios), as lack of validation was annoying the heck out of me... lol.

It just wont color the inpuit group addons correctly.

**Comment by tmorehouse** [comment]
We should probably add an example showing use with an input group, and the need to set the state in two spots to get around the issue.

**Comment by rdytogokev** [comment]
I am sure it would help people like me.

I have been working hard to refine my integration with Vuelidate because the Bootstrap-Vue docs are kind sparse on information about integrating with a Validation package.

When I finally get it working cleanly, I am willing to send you the code for use as a sample for the validation section of the docs. (Just know that I don't consider myself to be a seasoned coder. And I am still somewhat new to Vue.)

**Comment by tmorehouse** [comment]
That would be excellent if you could do that.  You could also just create a PR on one of the docs pages, or just create an issue with some sample code we can copy/paste.

**Comment by edwh** [comment]
I came across this because I have a submit button as an input group addon.  A quick and dirty fix for the formatting issue is to hide the button using v-if if the input becomes invalid.

```
            <b-input-group>
              <b-form-input
                v-model.trim="invitemail"
                type="email"
                size="lg"
                placeholder="Enter their email address"
                :validation="$v.invitemail"
                :validation-enabled="validationEnabled"
                :validation-messages="{
                  required: 'That isn\'t a valid email address - can you check?'
                }"
              />
              <b-input-group-append>
                <b-button v-if="!validationEnabled || !$v.invitemail.$invalid" variant="success" size="lg" @click="invite">
                  <v-icon name="envelope" />&nbsp;Invite a friend
                </b-button>
              </b-input-group-append>
            </b-input-group>
```
