### ISSUE TITLE
Popover : can not give class name as target 

### ISSUE THREAD

**Issue by rut2** [bootstrap-vue/bootstrap-vue#1256]
I am trying to reuse code by assigning class name as target name in <b-popover>, but bootstrap-vue only work with id. 

My problem is I am having a single form for at multiple places (designing scrum board), for that, I do not want to duplicate popover component for each button I show. How can I give target as a class name in bootstrap pop-over?

**Comment by Sobient** [comment]
_This answer doesn't give you any info on how to add classes, but should give enough insight as to why you don't need to._

There isn't any class property in the [reference docs](https://bootstrap-vue.js.org/docs/components/popover#component-reference). Each popover however, has the class `popover`.

Take a look at the DOM when a pop-over is created. It creates 1 `DIV` that is attached to the suffix of the page, so at any given time there is only one `DIV` - not multiple. Albeit, you won't run into any performance issues here any time soon, unless you're doing some additional voodoo.

In general, your code will run through all your scrum board cards attaching the `v-b-popover` directive to each card. When your users hover on the card, only one item is created with a unique reference that matches whatever properties you sent to your popover.

To further illustrate, take the example of:

*Example pseudo*
```
<div v-for="(c, i) in cards">
  <div class="story" v-b-popover.hover.auto="`${c.title}`">
     <h3>{{ c.title }}</h3>
     <p>{{ c.description }}</p>
  </div>
</div>

Whenever a card is hovered on, only one DIV is ever created, with some unique IDs and references.

**Comment by rut2** [comment]
@Sobient  thank you for quick feedback. I understand for **v-b-popovers** we do not need to worry about duplication of DOM as you explained. Great.! 

But my problem is I wanted to hold a popover form. Please check out screen below. 

![image](https://user-images.githubusercontent.com/4327606/32131322-e42bfc4e-bbc8-11e7-97a8-4144c9fbee66.png)

this each plus button will be holding a form to add a child. and for that, I am using an independent component in **<popover>**. And when I user <popover> component for each card popover is being added to DOM. 

![image](https://user-images.githubusercontent.com/4327606/32131553-dfbefb24-bbce-11e7-8102-33ae099f8d34.png)

So how we can minimize that for <popover>?

**Comment by tmorehouse** [comment]
You can't, popover is a component that is bound when the html is created. Interactive content can only be tied to a single instance of popover, so if you have 4 things that trigger a popover, then you have 4 popovers. 

Vue is not jQuery. It can't bind a component to a set of elements based on class selectors. You need to use things like v-for and common component definitions, but separate instantiation.

Even in jQuery, using a selector to create multiple popovers actually allocates memory for each popover instance even though it may not be shown in the dom.. It is still in memory occupying space. In Vue's case it is occupying space in the dom.

If you are overly concerned about html markup in your html, you can use v-if statements to hide the content of the popover until it is shown. Although the wrapper divs will still be there (they have to be there for popover components to work). And even though the html might be v-if'ed... It is still going to be in ram in the virtual dom until v-if'ed into the DOM.

Your best bet...stop opening the dev tools inspector, and stop worrying about rendered markup. It is either going to occupy ram or occupy some html elements. Both consume memory, and neither is going to hurt you...

**Comment by rut2** [comment]
@tmorehouse thank you for detailed explanation. this will surely help me to move forward. I think I got my answers so closing this issue from here 👍
