### ISSUE TITLE
Nav link attribute not working in navbar.

### ISSUE THREAD

**Issue by sosensible** [bootstrap-vue/bootstrap-vue#126]
I tried setting a link on the <b-nav-item> tag but it did not work for me.

`<b-nav-item link="/" active>Home</b-nav-item>`

This link seemed to work. The active showed active even when the item was not active. This should operate in a similar fashion to the router libraries router-link tag as shown below to be consistent with an officially supported vue library standard.

```
<b-nav-item>
  <router-link to="/" class="nav-link" activeClass="active" exact>Home</router-link>
</b-nav-item>
```

**Comment by pi0** [comment]
Closing due inactivity. feel free to re-open if problem exits.
