### ISSUE TITLE
Disable transition Popover & Tooltip

### ISSUE THREAD

**Issue by feedgit** [bootstrap-vue/bootstrap-vue#1262]
Hello
I get an confused error with Tooltip and Popover. When I fastly hover multi-elements simultaneously, **transition fade is not fast enough** so it get this error like below photo.
![image](https://user-images.githubusercontent.com/19923843/32161044-c877016e-bd86-11e7-87a7-08ccc2fa4203.png)
How can I completely disable transition?

**Comment by tmorehouse** [comment]
There is a small bug where tooltips and popover can get left in the DOM on fast hover in-out, which will be fixed in the next release (v1.0.0) which is coming soon.

You can disable the fade animation using the `nofade` option of the directive version, or `no-fade` on the component version.

**Comment by feedgit** [comment]
Thanks. Waiting for the next release. Good luck!
