### ISSUE TITLE
Any plan for building a component of Dater Picker?

### ISSUE THREAD

**Issue by FrideCode** [bootstrap-vue/bootstrap-vue#1264]
when i use bootstrap-vue in the pc web project, I think we need a date picker always to filling the form.I hope we can build one.

**Comment by alexsasharegan** [comment]
As there is no datepicker supported by bootstrap v4, it falls out of scope for the project. 

I personally use this datepicker: https://github.com/charliekassel/vuejs-datepicker. I think it fits bootstrap's stye decently well.
