### ISSUE TITLE
Carousel, it is possible support for video?

### ISSUE THREAD

**Issue by RoryLin** [bootstrap-vue/bootstrap-vue#1268]
i want to slider with video,
i checked  [the source code](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/carousel/carousel-slide.vue), only for image tag  :(

**Comment by mosinve** [comment]
b-img in source is a default-value for slot. 
You can try to use any content you want in carousel

**Comment by RoryLin** [comment]
oh! got it @mosinve  thanks  so much.
