### ISSUE TITLE
b-progress animation on load

### ISSUE THREAD

**Issue by smgjreinieren** [bootstrap-vue/bootstrap-vue#1269]
What I would like to see in this repository is that when the page is loaded the progress bar is animated from left to an x%. 

So basically I now it only animates the striped progressbar but what is nice to have a prop to set the default progress to animate.

And the height is not getting picked up properly but I allready saw a couple of issues on this. But mentioning it again.

**Comment by tmorehouse** [comment]
Changing the progress value will trigger a CSS animation of hte width to the new value.

Use an on-load handler (or `mounted()` hook of your app) to change the progress value from, say a default of, 0, to the value you want. The CS animation will kick in and make it grow from 0 to your value.

**Comment by tmorehouse** [comment]
It appears that Bootstrap V4.beta.2 has removed the progress-bar transition, so one would have to provider their own CSS override to enable transitioning of the progress bar width. This can be done with the following CSS:

```css
.progress-bar {
  transition: width 0.6s ease;
}
```
