### ISSUE TITLE
b-table: The computed property "fields" is already defined in data.

### ISSUE THREAD

**Issue by opichon** [bootstrap-vue/bootstrap-vue#1270]
When using the b-table component, I get the following error messages:
```
The computed property "fields" is already defined in data.
``
and sometimes:
```
The computed property "fields" is already defined as a prop.
```

sometimes both.

**Comment by tmorehouse** [comment]
Could you provide a sample of your code and markup?

**Comment by tmorehouse** [comment]
Without knowing what your markup and code looks like, it almost sounds like you are binding the `fields` prop more than once on `b-table`

**Comment by mosinve** [comment]
more possible that in component definition script you do something like this:
```
    export default{
        data:{
            .....
           fields: ''
        },
       ......
        computed{
            fields() {
                  some calculation logic
             }
        }

```

**Comment by JakePicton** [comment]
This could also be caused by a third-party plugin that sets a global mixin containing a `fields` data/prop/computed value.

For example, `vee-validate` adds a `fields` computed value in a global mixin (I encountered this exact issue when using both `bootstrap-vue` and `vee-validate`). Luckily `vee-validate` allows you to rename this computed value (I assume to avoid this kind of conflict).

**Comment by tmorehouse** [comment]
And if you are using vee-validate, you can stop vee-validate's injection into all components.  See http://vee-validate.logaretm.com/advanced.html#inject for details

**Comment by phitran35** [comment]
Thank you @JakePicton and @tmorehouse for the solutions.
I followed @tmorehouse's guideline to stop lee-validate's injection into all components as bellow:
```
Vue.use(VeeValidate, { inject: 'false' });
```
Unfortunately, VueJs will throw error message like this:
"Property or method "errors" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property"

Instead, change the Vee fields from configuration and it should work
```
Vue.use(VeeValidate, { fieldsBagName: 'veeFields' });
```

**Comment by pavanmehta91** [comment]
@jpicton And how exactly do we do that?

**Comment by toadkicker** [comment]
@phitran35 that fixed it for me!

**Comment by do-adams** [comment]
I just had this very same problem happen during a live Google product demo 😔🔫

Renaming the VeeValidate field injections values definitely fixed it FWIW.

**Comment by alisonmoura** [comment]
Thanks @toadkicker! For me, it was the VeeValidade indeed. The VeeValidade's setup worked :smile:
