### ISSUE TITLE
Dropdown should behave like plain Bootstrap

### ISSUE THREAD

**Issue by zatziky** [bootstrap-vue/bootstrap-vue#1273]
Hello bootstrap-vue team!

I believe that bootstrap-vue.dropdown should behave the same way as the plain Bootstrap dropdown. Plain Bootstrap doesn't have any item highligted upon opening a dropdown. Yet after hitting an arrow you can select the state. On item hover, the item item is highlighted but **without** the blue outline. Checkout the [docs](https://getbootstrap.com/docs/4.0/components/dropdowns/). 

The current behavior with the pre-selected blue outlined 1st item is really ugly and **not** the intended bootstrap way.

**After dropdown opens**

![image](https://user-images.githubusercontent.com/2794365/32267664-5267198e-beec-11e7-9541-f0eca5ef156f.png)

**On item hover**

![image](https://user-images.githubusercontent.com/2794365/32267702-776fd1f8-beec-11e7-98bd-4ea32e8d2521.png)

**On arrow keys**

![image](https://user-images.githubusercontent.com/2794365/32267735-8cc22006-beec-11e7-9732-eff53b7d12cd.png)

**Comment by mosinve** [comment]
![image](https://user-images.githubusercontent.com/20986566/32268927-f5ac6a08-bf01-11e7-8270-157baf1cf420.png)
This is current dropdown from BootstrapVue4.beta9 docs page

I don't see this:
> The current behavior with the pre-selected blue outlined 1st item is really ugly and not the intended bootstrap way.

**Comment by Dani216** [comment]
Hi @mosinve,
I am colleague of @zatziky 

NPM version of `dropdown.vue` is the same as https://github.com/bootstrap-vue/bootstrap-vue/blob/alpha/lib/components/dropdown.vue but nicer version of dropdown is https://github.com/bootstrap-vue/bootstrap-vue/blob/6b543f8b2152f143a09d79d1b122a6a245572148/lib/components/dropdown.vue, which isn't in NPM.

**Comment by tmorehouse** [comment]
Please note the alpha branches of Bootstrap-Vue will e going away (as Bootstrap V4 alpha CSS is not for production) with the upcoming release of v1.0.0 of Bootstrap-Vue

**Comment by Dani216** [comment]
My `package.json` looks like this:
```
"dependencies": {
    ...
    "bootstrap": "4.0.0-beta.2",
    "bootstrap-vue": "^1.0.0-beta.9",
   ...
  },
```

I was following this tutorial: https://bootstrap-vue.js.org/docs
`npm install bootstrap-vue --save`

Is that right process or am I doing something wrong?

**Comment by tmorehouse** [comment]
That is correct,but you referenced an `alpha` URL in your previous comment (https://github.com/bootstrap-vue/bootstrap-vue/blob/alpha/lib/components/dropdown.vue)

**Comment by tmorehouse** [comment]
Also not the "focus" ring look and feel is different on different browsers.  Chrome uses a blue ring, while firefox uses a more subtle grey ring.

As per W3C ARIA best practices, the first menu item should **always be focused** when the dropdown is opened: https://www.w3.org/TR/wai-aria-practices-1.1/#menu

**Comment by chriscarpenter12** [comment]
I realize this is a closed issue, but is the focus on the first item the desired behavior? Bootstrap 4 doesn't do this by default. This seems to counter what they do by default as @zatziky has pointed out. I understand the W3C has a spec on the recommended behavior, but shouldn't it be mirrored from the library behavior?

**Comment by PierBover** [comment]
I agree with @chriscarpenter12 .

It doesn't make much sense that Bootstrap Vue would deviate from what Bootstrap does, regardless of what the W3C says.

This is what Bootstrap does:
![image](https://user-images.githubusercontent.com/226483/41512651-5b925cac-7252-11e8-989f-98a45f96808a.png)

This is what Bootstrap Vue does:
![image](https://user-images.githubusercontent.com/226483/41512648-483bfd48-7252-11e8-8700-0d2f9a7c2f14.png)

**Comment by tmorehouse** [comment]
What most people with eyes and control of a mouse don't like is a focus ring.

People without eyesight or are limited to keyboard only navigation need this type of feedback/behaviour.
