### ISSUE TITLE
Use hamburger icon for dropdown button

### ISSUE THREAD

**Issue by preston-mccumber** [bootstrap-vue/bootstrap-vue#1277]
Hi,

First of all, thanks for all of your work creating this library.  It has been helpful in my work with Bootstrap and Vue.

I'm trying to implement a "hamburger" icon (rather than the triangle) for dropdown buttons.  There doesn't appear to be a way to do that.  I'm looking for something square shaped (therefore, not the default wide rectangle shape).

I don't think I can do it with the current version.  How would you suggest I accomplish it?  Can I extend and enhance the b-dropdown component without having to rewrite it? 

By the way, I'm using the CDN version of the library, not Node/Webpack.

Thanks,
Preston

**Comment by tmorehouse** [comment]
The newest version of Bootstrap-Vue (v1.0.0 which will be released soon), has an option to remove the caret from the dropdown menu button (except in split mode) via the new `no-caret` prop.

You can then place any content inside the menu trigger button (via the named slot).

You could use an icon library (one that has a hamburger-like icon) to create the button content.

**Comment by preston-mccumber** [comment]
That's great news!  Also, thanks for the quick response.

I put an icon into the button content, however, it also displays the triangle next to it so it looks weird.  

I've been trying to make the button narrower (rather than smaller in all dimensions) and can't seem to do that either.  I think it's because the b-dropdown tag expands into multiple DIVs and BS classes.  My styling ends up on the outermost DIV rather than the button inside IIRC.

**Comment by tmorehouse** [comment]
You can target the content via custom CSS to adjust size/padding/etc.

**Comment by preston-mccumber** [comment]
Do you mean customize the Bootstrap CSS file classes for buttons?  I can't change the CSS styling for all buttons.

I don't quite understand.  I already tried passing CSS classes through the class attribute to b-dropdown.

Thanks

**Comment by tmorehouse** [comment]
Define your own parent class and apply it to the dropdown.

Then use that parent class to target the inner button (or the button with class `dropdown-toggle`):

```css
.my-class.dropdown  .dropdown-toggle {
    padding: 0px;
    /* etc */
}
```

**Comment by preston-mccumber** [comment]
Oh, I see!  Thanks so much!

**Comment by otolabqu** [comment]
I did this

`<b-nav-item-dropdown text="☰" right style="font-size: 32px;" no-caret>`

**Comment by Cantzon** [comment]
> Define your own parent class and apply it to the dropdown.
> 
> Then use that parent class to target the inner button (or the button with class `dropdown-toggle`):
> 
> ```css
> .my-class.dropdown  .dropdown-toggle {
>     padding: 0px;
>     /* etc */
> }
> ```



> Define your own parent class and apply it to the dropdown.
> 
> Then use that parent class to target the inner button (or the button with class `dropdown-toggle`):
> 
> ```css
> .my-class.dropdown  .dropdown-toggle {
>     padding: 0px;
>     /* etc */
> }
> ```

I know this is an old issue but I just wanted to express my gratitude. I was going crazy trying to figure out why my styling and padding weren't being applied to the button content template and none of the related search questions to b-dropdown were relevant except for this. Bless you.
