### ISSUE TITLE
conditionally render modal parts?

### ISSUE THREAD

**Issue by sudomabider** [bootstrap-vue/bootstrap-vue#128]
First of all thanks for the great package! I've just started to play around with it and am loving it quite a bit.

I noticed currently there's no way to hide the modal header/footer/body. I can leave the slot empty but the container always shows so I end up with an empty box.

How about setting up additional properties to control the visibility of each part and, say, have them default to visible?

**Comment by pi0** [comment]
@sudomabider  New modal  changes is on the way :) What's your idea having props like `no-footer` ?

**Comment by sudomabider** [comment]
Yea that is even simpler. I'm all up for it!

**Comment by pi0** [comment]
This feature is now available using `hide-header` and `hide-footer` props :)
