### ISSUE TITLE
b-popover on disabled b-tab

### ISSUE THREAD

**Issue by admax81** [bootstrap-vue/bootstrap-vue#1282]
I have such code:
```
<b-tabs ref="tabs" no-fade>
      <b-tab title="Select switch" active @click="activeSwitchesTab">
        <switches></switches>
      </b-tab>
      <b-tab title="Port Properties" @click="activePortsTab" id="propsTabBtn">
        <port-properties></port-properties>
      </b-tab>
    </b-tabs>
    <b-popover target="propsTabBtn___BV_tab_button__" placement="bottom" triggers="hover focus" content="Please select a switch first to view the switch port properties."></b-popover>
```
    
As you can see, user must to select switch before 2nd tab will be available, so i need to add disable attribute on 2nd tab. But if i adding the disable attribute, the popover stops working.
How to add b-popover message to disabled b-tab?

**Comment by tmorehouse** [comment]
Popovers (and tooltips) will not work on 'disabled' elements (i.e. links, buttons) until they are enabled, as click and other events (which are used for triggering the popover or tooltip) do not bubble up on disabled element.

Your best bet is to enable the tab, but use a watcher on the current tab index and if it changes, set it back to tab `0` until the switch is enabled.

**Comment by admax81** [comment]
I understand, thanks, this is how I am doing now. But I wanted to use the property because different styles.
