### ISSUE TITLE
Auto show popup and hide after click on label

### ISSUE THREAD

**Issue by xtrimf** [bootstrap-vue/bootstrap-vue#1283]
Hi, is it possible to show a popup by default and hide it once I click on the Label or enter an input field?
I tried to use the `open` property couldn't get it to work...

`<th width="30px" class="noBorder" v-b-tooltip title="Toxicity">Tx</th>`

**Comment by tmorehouse** [comment]
Currently Tooltips and Popovers must be  triggered by one or more of `hover`, `focus` or `click`.

You could try manually triggering an event (i.e. `el.click()`) on the trigger element in your app/component `mounted()` hook (wrapped in a $nextTick` to ensure the directive has finished initializing).
