### ISSUE TITLE
Missing DatePicker and TimePicker components. 

### ISSUE THREAD

**Issue by Gr33ny** [bootstrap-vue/bootstrap-vue#1286]
DatePicker and TimePicker at vue-bootstrap framework can be very useful for developers and users. 
That can be a feature.

**Comment by tmorehouse** [comment]
Bootstrap-Vue currently only provides the official Bootstrap components. Bootstrap V4 official does not provide Date Picker or Time Picker components.

However there are several Vue plugins that do provide data and time pickers.
