### ISSUE TITLE
"b-table" formatter function (call) not working when placed inside "b-collapse"

### ISSUE THREAD

**Issue by ddweber** [bootstrap-vue/bootstrap-vue#1293]
When the "**b-table**" component is used **inside** a "**b-collapse**" component the formatter function does not get called.
I tested this behaviour in my private project and in the live section of the collapse component found on the document page (shown below) where I inserted the b-table from its documentation example.
Or am I doing something totally wrong?

![b-table_issue](https://user-images.githubusercontent.com/33422037/32443414-4168744a-c2ff-11e7-9e3e-0c3718354e95.JPG)
![b-table_issue2](https://user-images.githubusercontent.com/33422037/32443588-ce60929c-c2ff-11e7-8b7b-7733f36f7750.JPG)

_I don´t know if this is the right place to ask (I´m new to github) but can you tell a date for the next release of a beta version?
I really need and would like to use the "Row details support" in my students project in the next few weeks.
Btw you guys are doing an awesome job!_

**Comment by mosinve** [comment]
there's one issue with formatter function (FF) - it won't work if table has wrapped in another component at it's parent template, because table try to call provided FF as `this.$parent.function()`. 
The only solution i can offer - is to make table to search FF at this.$root level, so it wont depend on hierarchy level of table...

**Comment by tmorehouse** [comment]
`b-table`, when provided a formatter by _name_ (i.e.  string), looks in the `$parent` component's context for a method with that name.  In this case the parent component of `b-table` is `b-collapse`, not the scope of where your formatter function is.

Change your field definition to provide a "reference" to your local formatter:

```js
fields: [
  {
    key: 'name',
    label: 'Full Name',
    formatter: this.fullName
  },
  // ...
]
```

**Comment by ddweber** [comment]
Wow, that was fast! Thanks a lot. This fixed my issue.

How about the second part of my comment (maybe below the images was not the best place to put it)

> I don´t know if this is the right place to ask (I´m new to github) but can you tell a date for the next release of a beta version?
> I really need and would like to use the "Row details support" in my students project in the next few weeks.
> Btw you guys are doing an awesome job!

**Comment by tmorehouse** [comment]
Not sure of the release date, but it should be soon. We'll be leaving the beta state.

**Comment by ddweber** [comment]
_Thanks for the information!_

I´m sorry, but I have to admit that the suggested answer does **not fix** my issue **completely**. I thought so, but it was not the case. (Or i´m too dump, i don´t know)

It looks like "this" is undefined when doing `"formatter: this.fullName"` in the fields definiton section.

This time I tried it in your playground section with the code below and it does not throw any errors.

![b-table_issue3](https://user-images.githubusercontent.com/33422037/32448073-3b23c620-c30e-11e7-9ccb-3cb7d795a48b.JPG)

**Comment by tmorehouse** [comment]
You could move the fullName method into the fields object:

```js
fields: [
  {
    key: 'name'
    label: 'Full Name',
    formatter(value) {
      return `${value.first} ${value.last}`;
    }
  },
  // ...
]
```

or try this:
```js
fields: [
  {
    key: 'name'
    label: 'Full Name',
    formatter: (value) =>  {
      return this.fullName(value)
    }
  },
  // ...
]
```

**Comment by ddweber** [comment]
The first attempt works but i don´t want to put the whole formatter function in the fields definition section.
And the second one works if i add the vueapp-name inbetween "this" and the function name like below:

`formatter: (value) =>  {
      return this.vueapp-name.fullName(value)`

Is this syntax ok or is it a bad coding style in your opinion?

Thank you for your help, all sorted now and works like a charm!

**Comment by bzapata-thr** [comment]
> `b-table`, when provided a formatter by _name_ (i.e. string), looks in the `$parent` component's context for a method with that name. In this case the parent component of `b-table` is `b-collapse`, not the scope of where your formatter function is.
> 
> Change your field definition to provide a "reference" to your local formatter:
> 
> ```js
> fields: [
>   {
>     key: 'name',
>     label: 'Full Name',
>     formatter: this.fullName
>   },
>   // ...
> ]
> ```
> 
> Note the lack of parens `()` when referencing the method, as we need to pass a reference to the method, not the result of a method call.



> `b-table`, when provided a formatter by _name_ (i.e. string), looks in the `$parent` component's context for a method with that name. In this case the parent component of `b-table` is `b-collapse`, not the scope of where your formatter function is.
> 
> Change your field definition to provide a "reference" to your local formatter:
> 
> ```js
> fields: [
>   {
>     key: 'name',
>     label: 'Full Name',
>     formatter: this.fullName
>   },
>   // ...
> ]
> ```
> 
> Note the lack of parens `()` when referencing the method, as we need to pass a reference to the method, not the result of a method call.

Tested 12/16/20, using `this.methodName`, does not work for b-table inside a b-modal.
