### ISSUE TITLE
formatter for b-select

### ISSUE THREAD

**Issue by wxs77577** [bootstrap-vue/bootstrap-vue#1299]
I use numerical keys object for `:options` of `<b-select>`, but it turns into String value when I change the selected option, so can you add `formatter` for it? And how about to add `formatter` for all `input` components?

**Comment by tmorehouse** [comment]
One thing to note is that object keys are always treated as strings:
```js
options = {1:"foo", 2:"bar"}
// => Object [ <1 empty slot>, "foo", <1 empty slot>, "bar" ]
Object.keys(options)
// => Array [ "1", "2" ]
// Note the quotes around the key names.  they are strings
```

Use the array of objects format to preserve them as numbers:
```js
options = [ {value:1, text:"foo"}, {value:2, text:"bar"} ]
```
This will return a numeric value for the current b-select option.
