### ISSUE TITLE
There is no indication to what type of object "form-select" component uses for options.

### ISSUE THREAD

**Issue by mcteo** [bootstrap-vue/bootstrap-vue#130]
The "usage" documentation shown for the [form-select component](https://bootstrap-vue.github.io/docs/components/form-select/) doesn't tell you what sort of object "options" and "defaultOption" takes (just that the defaults are [] and null, respectively).

The documentation site has minified the javascript, so I cannot example the code used to produce the sample either (nor use the Vue Devtools in Chrome).

Finally, when writing this issue, I looked to see was the docs site source available on github, and it is.

https://github.com/bootstrap-vue/bootstrap-vue/blob/master/docs/pages/docs/components/form-select.vue#L52

```javascript
{ text: 'This is another option', value: 'c' },
{ text: 'This one is disabled', value: 'd', disabled: true }
```

**Comment by pi0** [comment]
@mcteo Thanks for your feedback. Docs are now refactored so we can easily add more description for components. `form-select` and `form-radio` also have a more clear descriptions. Trying to make it even more complete.
