### ISSUE TITLE
Dropdown bug with initial position in IE 11

### ISSUE THREAD

**Issue by Dani216** [bootstrap-vue/bootstrap-vue#1300]
Hi everyone,

I have same issue as is in docs, do you have any advice how to solve this? After click on menu item it opens the dropdown, but initial position of dropdown is left and that cause stretching `body` tag and move screen to the left. 
It works in Chrome but in IE11 not, sadly  IE11 is important for us.

1. Open IE 11
2. Goto https://bootstrap-vue.js.org/docs/components/button-group/#dropdown-menu-support
3. Resize browser to approximatly 520px

![bootstrap-vue-bug](https://user-images.githubusercontent.com/14002753/32483968-7b72b25a-c39e-11e7-9c71-029a4ab6fa64.gif)

- Windows 10, IE11, 1.0.0-beta.9

Thanks
Dan

**Comment by mosinve** [comment]
have you tried to explicitly define opening position of dropdown menu by `right` prop, as described here https://bootstrap-vue.js.org/docs/components/dropdown#menu-left-and-right-alignment ?

**Comment by mosinve** [comment]
Checked at Windows 8.1 IE10 - all ok

**Comment by Dani216** [comment]
Here is my code:
https://jsfiddle.net/pow8fbsh/2/

Try multiple-times click to dropdown. You will see similar behavior as above.
!All menu items must be in one row.

Before click to dropdown menu item:
[![Screenshot from Gyazo](https://gyazo.com/f2fb36d60489adbe8dc36341aaa29474/raw)](https://gyazo.com/f2fb36d60489adbe8dc36341aaa29474)

After:
[![Screenshot from Gyazo](https://gyazo.com/269786099ed3ca4dd471113fdaa94521/raw)](https://gyazo.com/269786099ed3ca4dd471113fdaa94521)

**Comment by tmorehouse** [comment]
Do you see a similar issue in regular bootstrap V4.beta.2 markup/jQuery? just wondering if this might be an upstream issue with Bootstrap and Popper.js positioning.

**Comment by tmorehouse** [comment]
It appears that dropdown buttons in general inside button groups do not render correctly in IE11 (notice the middle dropdown button's caret is partially obscured by the button to the right of it).

**Comment by tmorehouse** [comment]
This also appears in native Bootstrap V4 CSS issue with IE
