### ISSUE TITLE
form-file "sizeFormClass" is not defined 

### ISSUE THREAD

**Issue by xidedix** [bootstrap-vue/bootstrap-vue#1303]
[Vue warn]: Property or method "sizeFormClass" is not defined on the instance but referenced during render.

Looks like missed `formSizeMixin`

https://github.com/bootstrap-vue/bootstrap-vue/blob/6cfcd545ccd362e8cc3a042be5e9f953d5f6a807/src/components/form-file/form-file.vue#L133

https://github.com/bootstrap-vue/bootstrap-vue/blob/6cfcd545ccd362e8cc3a042be5e9f953d5f6a807/src/components/form-file/form-file.vue#L137

**Comment by tmorehouse** [comment]
Actually bootstrap custom form-file does not support control sizing.

**Comment by tmorehouse** [comment]
The mixin shouldn't be imported, and the reference to sizeFormClass should be removed (as the custom form-file doesn't use the form-control classes, and file native inputs cant always be styled across browsers.)

**Comment by tmorehouse** [comment]
The `sizeFormClass` refrernce has been removed from form-file.  the fix is available in v1.0.2
