### ISSUE TITLE
Docs - Layout page is missing ( b-rows, b-cols )

### ISSUE THREAD

**Issue by tjunussov** [bootstrap-vue/bootstrap-vue#1306]
Docs - Layout page is missing, https://bootstrap-vue.js.org/docs/layout/ is 404 page
is it intentionaly ?  i ddint find any docs on that in latest (  1.0.0 version )

I think  b-rows, b-cols must be explained to new users

**Comment by pi0** [comment]
Hi. It is here:

https://bootstrap-vue.js.org/docs/components/layout

How did you reached the old link?

**Comment by tjunussov** [comment]
I didnt find in search on site, after a searched issue, and finaly i searched google, and it gave me old link

**Comment by tmorehouse** [comment]
PR #1307 adds a redirect from the old URL to the new one
