### ISSUE TITLE
[Tables] Pagination

### ISSUE THREAD

**Issue by yvandupre** [bootstrap-vue/bootstrap-vue#131]
i would like to know if table will support pagin client, server?

**Comment by pi0** [comment]
@yvandupre Unfortunately no as it may need external dependencies and we cannot add them to this repo.

**Comment by yvandupre** [comment]
seem to be a local pagin....

so we feed the table (50 data), if we display only 10 data, when we on other, there are not another call to server...

seem a litle bit less powerfull then
https://github.com/wenzhixin/vue-bootstrap-table

**Comment by pi0** [comment]
@yvandupre Thanks for your suggestion and also #158 table API is now exposing `items-provider` prop. With this one we can easily implement any ajax behavior. Currently i had not time for providing more guides but i'll add them soon. Functions blueprint is `provider(ctx)` which ctx is a reference to internal component. We have to apply pagination and sorting using `ctx.perPage` `ctx.currentPage`  `ctx.filter` `ctx.sortBy` and `ctx.sortDesc` then returning results items.

**Comment by mosinve** [comment]
While checking fieldset noticed a table pagination bug. It appears when the filter is set.
steps to reproduce:
1. open table docs or playground
2. set filter to show less than min perpage value (<5)
3. set different values of rows per page
4. check that pagination changes according to rows per page value , not taking in account filtered amount of rows

**Comment by tmorehouse** [comment]
For the provider routine, one could use promises within the `fetch(....)` to handle the async, and then return the result of the promise (say using a Promisifed `XmlHTTPRequest` (like axion or similar), although the user might need to load a Promise polyfill depending on the browser.

Sort of in this wein of pseudo code:

```js
methods: {
  fetch({perPage,currentPage,filter,sortBy,sortDesc}) {
    return get('/url',params).then(data => {
      // massage data and then return it
      return data;
    }
  }
}
```
