### ISSUE TITLE
b-form-select state is not behaving as it should.

### ISSUE THREAD

**Issue by BruceHem** [bootstrap-vue/bootstrap-vue#1324]
![screen shot 2017-11-10 at 10 49 36 am](https://user-images.githubusercontent.com/15667259/32642167-e38a77c0-c604-11e7-8335-80216e80c761.png)

```vue
<template lang="pug">
  .container
    b-card(
      title="Testing B-DropDown"
    )
      b-form(
        @submit.prevent="submit"
        :validated="form.validated"
        novalidate
      )
        b-form-group#country-group(
          horizontal
          label="Country"
        )
          b-input-group
            b-input-group-addon
              i.fa.fa-globe(aria-hidden="true")
            b-form-select(
              name="countryCode"
              v-model="form.countryCode"
              v-validate="'required|alpha'"
              :state="countryState"
              :options="getCountryOptions"
            )
        b-button.mr-2(type="submit" variant="success") Create Account
<template>
```

Below is part of script tag
```js
{
  data: () => ({
    form: {
      validated: false
    }
  }),
  computed: {
    countryState () {
      const { invalid, validated } = this.fields.countryCode
      return !validated ? null : !invalid
    }
  },
  methods: {
    async submit () {
      try {
        const result = await this.$validator.validateAll(this.form)
        console.log('fields', this.fields)
        this.form.validated = true
        if (!result) return
        console.log('Form submitted!', this.form)
      } catch (error) {
        console.error(error)
      }
    }
  }
}

```

So what is the issue?

The directive `state` in `b-form-select` is initially grey so when I change it to other values it goes GREEN as expect. And change back to `Select your country` it goes RED again. 

So far, it's ok.

Ok let's refresh and get a clean start, now i click submit without change anything.

The `state` in `b-form-select`  is green.

**Comment by tmorehouse** [comment]
Your form input values need to be reactive, they must be defined in your `data()`

 You only have the `validated` variable in your data, so Vue has no clue that form.countryCode exists as reactive data.  See: the official Vue docs on reactivity and change detection: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by BruceHem** [comment]
Still the same.

**Comment by rahul9874563210** [comment]
I didn't found any solution so is just use this in my component file which works fine but it's not the solution.

```html
<style scoped>
.is-valid {
  border-color:#c2cfd6;
}
</style>
```
