### ISSUE TITLE
Opening another Modal from a Modal breaks body scrolling

### ISSUE THREAD

**Issue by IlyaSemenov** [bootstrap-vue/bootstrap-vue#1325]
### Steps to reproduce

1. Create two `<b-modal>`.
2. Open first modal.
3. While the first modal is opened, trigger opening the second modal.

### Actual result

1. First modal hides
2. Second modal shows
3. Background body becomes scrollable

### Expected result

1. First modal hides
2. Second modal shows
3. Background body stays fixed

### Example

See this jsfiddle: https://jsfiddle.net/semenov/ngdr0gtk/

1. Click "Show Modal 1"
2. Ensure that the long background doesn't scroll
3. Click "Show Modal 2"
4. Observe that the long background becomes scrollable

### Environment

* Chrome 62 under macOS (latest)
* Vue 2.5.3 (latest)
* bootstrap-vue 1.0.2 (latest)
* bootstrap 4.0.0-beta.2 (latest)

### Workaround

The simple (but ugly) workaround is to manually hide the currently opened modal, and open the second modal with `setTimeout`. Note that the timeout must be reasonably large, in the sense that 0 (or `$nextTick`) or even 100 is not enough. Possibly, it has something to do with the animation.

**Comment by mosinve** [comment]
Bootstrap-Vue uses Bootstrap css, as you sure know.
So, please read this https://getbootstrap.com/docs/4.0/components/modal/#how-it-works, especially 3rd bullet

**Comment by IlyaSemenov** [comment]
Sure, I am aware of that. I am not trying to show two modals at the same time. I simply want to switch between the two modals (e.g. login and registration dialogs). Basically, it works almost perfectly with bootstrap-vue other than that background scroll issue.

**Comment by IlyaSemenov** [comment]
I understand that bootstrap-vue is mostly a thin wrapper, however I think everyone will win if it handles this use case automatically with some Javascript magic (after all, that's why we use Vue in the first place). I don't think switching between modals is a very rare case.

**Comment by tmorehouse** [comment]
Should be addressed in release v1.1.0
