### ISSUE TITLE
Bootstrap Dropdown XS (suggestion)

### ISSUE THREAD

**Issue by happilymarrieddad** [bootstrap-vue/bootstrap-vue#1328]
Is it possible to get this dropdown any smaller? It doesn't fit our layout at the moment. Thanks!

![selection_099](https://user-images.githubusercontent.com/6416323/32669431-c3aaddb6-c5fd-11e7-8208-ecad89aa87f9.png)

![selection_101](https://user-images.githubusercontent.com/6416323/32669557-2de7d5bc-c5fe-11e7-83a9-90badb9f1296.png)

![selection_100](https://user-images.githubusercontent.com/6416323/32669544-21f3545c-c5fe-11e7-80e5-0661604e2d7e.png)

**Comment by tmorehouse** [comment]
You can set the dropdown button size via the `size` prop (accepted values are `sm` and `lg` as currently defined in Bootstrap V4 CSS).

These values are defined by Bootstrap V4 as CSS as classes `.btn-sm` and `.btn-lg`.

You could create your own `.btn-xs` size (and pass `xs` to the `size` prop) which sets the font-size, padding, etc.

**Comment by tmorehouse** [comment]
Check out https://github.com/twbs/bootstrap/issues/21881#issuecomment-341972830

**Comment by happilymarrieddad** [comment]
@tmorehouse thanks so much man!
