### ISSUE TITLE
Support <router-link ... tag="b-nav-item">

### ISSUE THREAD

**Issue by Toilal** [bootstrap-vue/bootstrap-vue#1335]
I'm trying to create links using [router-link](https://router.vuejs.org/en/api/router-link.html) on b-nav-item inside the navbar, but it doesn't seem to be supported.

```
<b-navbar-nav>
  <router-link :to="{name: 'Bookings'}" tag="b-nav-item">Bookings</router-link>
  <router-link :to="{name: 'Products'}" tag="b-nav-item">Produits</router-link>
</b-navbar-nav>
```

In this case, b-nav-item components are used, but links doesn't work.

```
<b-navbar-nav>
  <router-link :to="{name: 'Bookings'}">Bookings</router-link>
  <router-link :to="{name: 'Products'}">Produits</router-link>
</b-navbar-nav>
```

Links are working properly with this code, but of course it doesn't use the b-nav-item component.

(bootstrap-vue@1.0.2)

**Comment by Toilal** [comment]
I just read the docs better, sorry for noise.

**Comment by dlfjj** [comment]
How did you solve this problem?

**Comment by juniarsofyan** [comment]
How did you solve this problem?

**Comment by juniarsofyan** [comment]
> How did you solve this problem?

use **_to_** attribute inside `<b-nav-item>` tag
example : `<b-nav-item to="/home">Home</b-nav-item>`
