### ISSUE TITLE
Input Date

### ISSUE THREAD

**Issue by happilymarrieddad** [bootstrap-vue/bootstrap-vue#1342]
Hey guys,

Is it possible to get the b-form-input(type='date') to open the calender on click? Thanks!

- Nick

![selection_103](https://user-images.githubusercontent.com/6416323/32751086-cb1768ae-c881-11e7-8454-15201954d59b.png)
![selection_104](https://user-images.githubusercontent.com/6416323/32751098-d4d6dd5c-c881-11e7-96be-886b03a00b08.png)

**Comment by tmorehouse** [comment]
This is controlled by the browser.  Some browsers will automatically open the native browser calendar picker (i.e. on mobile), and some will just let the user fill in the individual fields unless the user clicks the native dropdown caret (i.e. on desktop).

As the implementation is browser specific, it is almost impossible to trigger the native date-picker programmatically.

**Comment by happilymarrieddad** [comment]
Our customers are required to use chrome when using our web app. Is there a way I can force this programatically for just our app? @tmorehouse

**Comment by tmorehouse** [comment]
Ones used to be able to emulate hitting the 'F4' key on focus of the element:

https://stackoverflow.com/questions/15530850/method-to-show-native-datepicker-in-chrome/30895180#30895180

But it appears this no longer works in the latest Chrome.

**Comment by tmorehouse** [comment]
The date picker you re seeing is the native browser date-picker, not a custom Vue date picker.  You'll notice that desktop firefox doesn't support  input type date and doesn't show a datepicker at all (which mobile firefox wil show  datepicker)

**Comment by happilymarrieddad** [comment]
@tmorehouse Thanks man, I'll just create my own.
