### ISSUE TITLE
The "img" slot on <b-card> component doesn't render associated image

### ISSUE THREAD

**Issue by gswcm** [bootstrap-vue/bootstrap-vue#1349]
I am using `<b-card>` component with an image and some text. Here is my original markup:
``` html
<b-card
   ...
   img-src="some_url">
   <p>
      some text
   </p
</b-card>
```
it works fine, but when I try moving image into  a separate slot like this:
```html
<b-card
   ...>
   <div slot="img">
      <img src="some_url"/>
   </div>
   <p>
      some text
   </p
</b-card>
```
it doesn't render the image, only text and other content that I omitted in this example.

**Comment by tmorehouse** [comment]
Try this:

```html
<b-card  ...>
   <template slot="img">
      <img class="card-img img-fluid" src="some_url"/>
   </template>
   <p>
      some text
   </p
</b-card>
```
or 
```html
<b-card  ...>
   <img slot="img" class="card-img img-fluid" src="some_url"/>
   <p>
      some text
   </p
</b-card>
```

Remember to add the appropriate classes for the image (`card-img` is required at a minimum). you may need to add `card-img-top` or `card-img-bottom` to get the correct rounded corners

**Comment by gswcm** [comment]
I tried both, they didn't work. Here is my exact markup except text in paragraphs
```html
<b-card
	bg-variant="transparent"
	class="border-0"
	title="Welcome"
	sub-title="Thank you for using our registration portal">
	<img slot="img" src="logo_trimmed.png" class="card-img img-fluid"/>
	<p class="card-text mt-3 text-justify">
		some text
	</p>
	<hr>
	<p class="text-center">
		some other text
	</p>
	<b-btn variant="primary" to="/start" class="d-block">Let's Get Started</b-btn>
</b-card>
``` 
I was wondering if some props of the `<b-card>` component may conflict with "slot" assignments...

**Comment by tmorehouse** [comment]
I just remembered that the image slot was removed in favor of using the newer individual sub-components to build the cards.

You would need to build your card as follows:
```html
<b-card no-body bg-variant="transparent" class="border-0">
  <img src="logo_trimmed.png" class="card-img card-img-top img-fluid" />
  <b-card-body
        title="Welcome"
	sub-title="Thank you for using our registration portal">
    <p class="card-text mt-3 text-justify">
      some text
    </p>
    <hr>
    <p class="text-center">
      some other text
    </p>
    <b-btn variant="primary" to="/start" class="d-block">Let's Get Started</b-btn>
  </b-card-body>
</b-card>
```

**Comment by Branksy** [comment]
This should ideally be in the docs

**Comment by cythrauL** [comment]
+1, I've been trying to use as per the docs all day, only to find this 'closed' bug.

**Comment by tmorehouse** [comment]
The `img` slot was only in the alpha branch (pre version 1.0.0.beta)
