### ISSUE TITLE
Nuxt css: false should overwrite bootstrap-vue.css

### ISSUE THREAD

**Issue by gabel** [bootstrap-vue/bootstrap-vue#1351]
When using bootstrap-vue as nuxt package bootstrap.css can be disabled but this does not apply on bootstrap-vue.css.

https://github.com/bootstrap-vue/bootstrap-vue/blob/e024ae49ee1ead6ff8c3fb7f9627ccfe94ed4da9/nuxt/index.js#L18-L20

https://github.com/bootstrap-vue/bootstrap-vue/blob/e024ae49ee1ead6ff8c3fb7f9627ccfe94ed4da9/nuxt/index.js#L30

```
// example nuxt.config.js
modules: [
    '@nuxtjs/font-awesome',
    ['bootstrap-vue/nuxt', { css: false }]
  ],
  css: [
    '@/assets/scss/custom.scss'
  ]
```

I would propose to disable bootstrap-vue.css with `css: false` or to add an additional option to keep it backward compatible.

----

**Example use case:**

When I try to overwrite e.g. table sorting icons with the icon library of choice the bootstrap-vue.css gets applied after the scss files defined in nuxt.config.js.

![image](https://user-images.githubusercontent.com/242039/32827807-a6023a86-c9ed-11e7-8be4-74b362c592bd.png)

Workaround: `!important` 😢

**Comment by pi0** [comment]
@gabel Thanks for your report. What's your idea if we change `push` to `unshift` so user provided stylesheets will get more priority and thus there is no need to important rules. We may also introduce a new module option like `bvCSS` which can be set to false for disabling this custom css too.

**Comment by gabel** [comment]
@pi0 If bootstrap-vue does not requiry bootstrap to load in advance sure an  `unshift` would help

**Comment by gabel** [comment]
There might be a problem with the approach of `unshift`

With option `css: true` all is fine

* `option.css`
* `unshift bootstrap-vue` (would require to move the line up in index.js)
* `unshift bootstrap`

will result in the order:

1. bootstrap
2. bootstrap-vue
3. custom.css/scss defined in nuxt.config.js

With option `css: false`

* `option.css` (including self build bootstrap)
* `unshift bootstrap-vue`

the resulting order will be 

1. bootstrap-vue
2. bootstrap
3. custom.css/scss

And that may be a problem depending on the defined css within bootstrap-vue components.

**Comment by pi0** [comment]
Yep. I agree with this mentioned problem. So we have no choice than adding a new option to disable `bootstrap-vue.css`
