### ISSUE TITLE
Popover with :placement="'top'" is shown at the bottom

### ISSUE THREAD

**Issue by paglias** [bootstrap-vue/bootstrap-vue#1352]
If I use a popover with `:placement="'top'"` it gets rendered with bottom positioning, while `left` and `right` positioning works well

<img width="1075" alt="schermata 2017-11-15 alle 23 24 39" src="https://user-images.githubusercontent.com/589911/32863669-8e5fba10-ca5c-11e7-8fb6-6c189d1f3dc7.png">

^ was renderend with `:placement="'top'"`

Using the latest version

**Comment by paglias** [comment]
It doesn't happen always, but in some occasions the popover is forced to the bottom position

**Comment by tmorehouse** [comment]
This is by design.

Popovers (and tooltips) will auto "flip" if too close to the edge of the browser window.  This is identical to the implementation of native Bootstrap V4+jQuery as well.

Scrolling the window up will make the popover return to the original position.

**Comment by paglias** [comment]
This is actually happening inside a div fixed to the bottom of the page, in
the beta version of bootstrap-vue they showed towards the top correctly but
it seems like since v1 they are not able to go outside the fixed div
boundaries

Il 15 Nov 2017 23:46, "Troy Morehouse" <notifications@github.com> ha
scritto:

**Comment by paglias** [comment]
<img width="347" alt="schermata 2017-11-16 alle 00 00 21" src="https://user-images.githubusercontent.com/589911/32864935-4f41b180-ca61-11e7-8ad9-895cce5ae3ee.png">

<img width="1119" alt="schermata 2017-11-16 alle 00 00 36" src="https://user-images.githubusercontent.com/589911/32864951-62af9e6c-ca61-11e7-9421-40474d07d55d.png">


^ behavior and produced html in bootstrap-vue beta


<img width="390" alt="schermata 2017-11-16 alle 00 00 50" src="https://user-images.githubusercontent.com/589911/32864959-6c34746c-ca61-11e7-8893-59f149cae99c.png">
<img width="1111" alt="schermata 2017-11-16 alle 00 01 04" src="https://user-images.githubusercontent.com/589911/32864960-6c50e8ae-ca61-11e7-9f09-063b880a7863.png">

^ same popover using vue-bootstrap 1

The dark fixed div has this CSS props

<img width="326" alt="schermata 2017-11-16 alle 00 02 55" src="https://user-images.githubusercontent.com/589911/32864994-8ce368e4-ca61-11e7-8bdc-4ef823572759.png">

**Comment by tmorehouse** [comment]
This may be due to a newer version of Popper.js used in Bootstrrap-Vue.

Popper.js, not Bootstrap-Vue controls the positioning of the popovers and tooltip (as well as dropdown menus).  It controls how flipping occurs

**Comment by tmorehouse** [comment]
There may also be issues when placing popovers within fixed containers, and how popper determines the onscreen position of the trigger element.

**Comment by paglias** [comment]
yeah I think the problem is not the flipping, because changing the classes to `bs-popover-top` manually doesn't fix the problem, but that something changed (in Popper?) that's preventing the popover from overflowing the fixed div

**Comment by tmorehouse** [comment]
Popper has a similar issue for dropdowns inside elements with `overflow: hidden` set.

**Comment by paglias** [comment]
Oh it's that, thanks @tmorehouse ! Removing the overflow rules fixed the problem

**Comment by tmorehouse** [comment]
Excellent.

**Comment by paglias** [comment]
@tmorehouse I did some research today and the solutions seems two:

1. Move the `b-popover` declaration outside the element with `overflow: hidden` but in my case that's almost impossible as the popover is rendered for each element in a list so I would have to create a parallel list in a parent component just to hold the `b-popover`
2. Popper.js seems to have an option to disable the behavior where popovers get forced inside the element boundaries https://popper.js.org/popper-documentation.html#modifiers..preventOverflow, would it be possible to add an option to `bootstrap-vue` to pass a custom option to `modifiers.preventOverflow.enabled` here https://github.com/bootstrap-vue/bootstrap-vue/blob/94488c690a746bc958d5884e552bfa43d75a2e17/src/utils/tooltip.class.js#L785?

Thanks for your help

**Comment by paglias** [comment]
It will require to also change this modifier since it's enabled by default and requires preventOverflow to work https://popper.js.org/popper-documentation.html#modifiers..hide

**Comment by tmorehouse** [comment]
I'll take a look into this, and also see what Bootstrap V4 official is doing.

**Comment by ramakrishnamundru** [comment]
@tmorehouse The option to have a custom popover config seems like a good feature,
can you reopen this issue as a feature request?

**Comment by tmorehouse** [comment]
Let me see what can be done with the component version.  The directive version, you can pass a custom condif..  I'll see what Bootstrap Official has done, as they have the same issue.

**Comment by SacDin** [comment]
For anyone looking for solution, provide `min-height` to container.

**Comment by tmorehouse** [comment]
Use the `boundary` prop to specify `viewport` or `window` instead of the default of `scrollParent`
