### ISSUE TITLE
Modal hide handler called even if ok/cancel prevented hide

### ISSUE THREAD

**Issue by mzgajner** [bootstrap-vue/bootstrap-vue#1356]
I have a modal and I want to do something when it closes, so I'm using `@hide="modalClosed"`. At the same time, I have a form in the modal. If this form is invalid when the user clicks OK, I prevent the modal from hiding by calling `event.preventDefault()` in my `@ok` handler. This DOES prevent the modal from closing successfully, but `modalClosed` is still being called.

I'm currently working around this by checking if `event.defaultPrevented` is already true at the beginning of `modalClosed`, but it seems that it would be more reasonable not to call the `@hide` handler at all if the modal didn't actually hide.

- Operating system and version: Fedora 27
- Browser: Chrome 62
- Version of Bootstrap-Vue: 1.0.2
- [JSFiddle minimal reproduction case](https://jsfiddle.net/oo2ej8r7/2/)

**Comment by tmorehouse** [comment]
The `@hide` event is always fired, as it can be used instead of listening for `@ok`.  The `event.trigger` contains a string describing the button or trigger that caused the modal to initiate hiding (i.e. `'ok'`, `'cancel'`, `'esc'`, `'backdrop'`, etc, or null if no trigger was provided to the `hide()` method).

**Comment by tmorehouse** [comment]
I would suggest using the event `@hidden` instead of `@hide` which is fired when the modal is truly hidden.

**Comment by mzgajner** [comment]
Ohhh, ok, didn't fully get that from the documentation. Thanks for clearing it up! :)
