### ISSUE TITLE
Popover: close if focus moves on element in popover body 

### ISSUE THREAD

**Issue by m1neral** [bootstrap-vue/bootstrap-vue#1357]
Hello!
```
triggers="click blur"
```
https://jsfiddle.net/6haq0jvL/

When focus moves on element in popup body (`checkbox`), popup closes.
But in `hide` event I can't resolve real `activeElement` (`checkbox`), because `activeElement` - always propagate to `body`.

I want to know in `hide` event which element has taken focus, so that, if necessary, prevent closing. Thanks!

**Comment by tmorehouse** [comment]
Popovers are normally used for informational purposes and not form content.  form content needs special handling, as shown in the example in the documentation.

Here is an updated fiddle: https://jsfiddle.net/6haq0jvL/2/

**Comment by m1neral** [comment]
Thank you, I saw this use in examples. 

But what about some fixes for `click blur` triggers combination: if focus getting on some elements in popover body - don't close popover, if focus getting on any elements not in popover body - close popover? Or at least a workaround in the current implementation for my case?

**Comment by tmorehouse** [comment]
We have added better `blur` handling in release v1.1.0
