### ISSUE TITLE
form-checkbox button style does not work on BS4

### ISSUE THREAD

**Issue by techxax** [bootstrap-vue/bootstrap-vue#1358]
Label tag must be button instead label
when using button styled check/radio box on bootstrap 4

**Comment by techxax** [comment]
Label tag must be button instead label
when using button styled check/radio box on bootstrap 4

**Comment by tmorehouse** [comment]
Can you provide an example of your markup, and which version of Bootstrap-Vue you are using?

the button styling only works when the checkbox is placed inside of a `<b-form-checkbox-group>` which has the `buttons` prop set: http://localhost:3000/docs/components/form-checkbox#button-style-checkboxes

**Comment by tmorehouse** [comment]
Closing as details are needed as per to your markup.

**Comment by tmorehouse** [comment]
The output is supposed to be a label. What you are seeing is an issue with the JavaScript files (don't include jQuery, don't include Bootrap's JS) included in your fiddle as well as your markup.

Updated working fiddle: https://jsfiddle.net/9s5vchh0/1/

**Comment by techxax** [comment]
Our project needs them, so thats same library
Think no way, Ok you can Close-Issue
