### ISSUE TITLE
Fix: Alpha stability

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#1359]
There is currently an erroneous component array (rather than object) in alpha that has been fixed by #1206, but not tagged and distributed. I am currently incorporating this fix by installing BV alpha via github branch:

```json
{
  "dependencies": {
    "bootstrap-vue": "git://github.com/bootstrap-vue/bootstrap-vue.git#alpha"
  }
}
```

This is okay, but not ideal in the event that alpha gets updated (non deterministic build). If this alpha release has been frozen, it should receive a stability release, git tag, and npm release.

**Comment by alexsasharegan** [comment]
Naturally I would like to just update the dep to v1, but unfortunately I don't have work time allotted to updating the breaking changes yet.

**Comment by pi0** [comment]
Hi alex.

Just published a new fix under `@alpha` tag:

http://unpkg.com/bootstrap-vue@alpha (@bootstrap-vue@0.23.1)
