### ISSUE TITLE
Table computed items property rendering 

### ISSUE THREAD

**Issue by haleksandre** [bootstrap-vue/bootstrap-vue#1361]
There's seem to be an issue with the table rendering rows with dynamic items. I'm using Vuex actions / getters which populate the store via an API.

Even if I manually control its busy state it doesn't get rendered pass 1st page.

Here's a fiddle of mimicking what happens with Vuex actions / getters
https://jsfiddle.net/24s9pqz5/4/

You can see the items does get updated (below the table), but the table doesn't refresh. Any ideas why it isn't working?

**Comment by tmorehouse** [comment]
Since you are doing the pagination yourself (in your storeGetter), you need to **not** set any pagination control props on `<b-table>`, otherwise `<b-table>` whill try and locally paginate the item data provided to it.

See updated fiddle https://jsfiddle.net/24s9pqz5/5/
