### ISSUE TITLE
how to dynamically add options to b-form-select with axios get

### ISSUE THREAD

**Issue by talalzaki** [bootstrap-vue/bootstrap-vue#1364]
hello, i want use a request with axios to b-form-select option : text and value ??

**Comment by tmorehouse** [comment]
Since you can pass an array (or object) of options to `<b-form-select>`, such as from the `data` section of your app or component, your axios request can simply update the data (i.e. `this.myOptions`) and `<b-form-select :options="myOptions">` with automatically update the options list.

**Comment by talalzaki** [comment]
thanks
