### ISSUE TITLE
[b-tabs] lazy feature not working

### ISSUE THREAD

**Issue by lch8410** [bootstrap-vue/bootstrap-vue#1371]
os : ubuntu 16.04
booststrap-vue : 1.1.0
browser : chrome, firefox, edge

after 1.1.0 upgrade,
b-tabs lazy is not working.
1.0.2 is working.

You should test it.
Thank you.

**Comment by tmorehouse** [comment]
Fixed in PR #1372 and will be available in the next release.

**Comment by tmorehouse** [comment]
Fixed in release v1.2.0
