### ISSUE TITLE
[proposal] add generic inner component property access

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#1376]
A lot of the components are internally using other bootstrap-vue components themselves. But if we want the user to be able to change a prop on one of the inner components, we manually have to add a prop on the parent component and link that to the inner child. Although this method works it is not easy to maintain and will give inconsistent results about which properties you can change on inner components quite easily.

Take e.g. the modal component which uses `b-btn` internally as close, ok and cancel buttons. At the moment you have only access to the `b-btn` variant property but thats it. 
Now lets say you have a form in your dialog and need the ok-button to have `type="submit"` so you can use proper html5 form validation (instead of the example from the docs) before closing the modal, currently you have to implement the whole modal-footer. Besides that thats quite a lot of work, you also loose parts of the dynamic disabled property on the buttons as you dont have access to `t.is_transitioning`.

So what about adding the possibility to always be able to add/change the properties of (certain / most) inner components? We could prefix all the properties of inner components (eg `ok-variant`, `ok-type`, `ok-*`) but as (afaik) vue does not support wildcard props those lists will be quite long and might be an issue.
The best solution would probably be to add a `ok-props` property to the parent with type object and which is merged with the props when creating the okButton.

Eg: `<b-modal :ok-props="{type: 'submit'}">` 
with:
```js
okButton = h('b-btn', {
  props: Object.assign(
    {
      variant: t.okVariant,
      size: t.buttonSize
    },
    t.okProps || {}
  ) 
})
```
What do you think?

**Comment by tmorehouse** [comment]
This is an option, but we do have a few helper utility functions for pulling in props (and picking only ones that will work in the current situation).  There are instances where the parent component is setting particular props that shouldn't be over written, and excluding props that don't make sense.

A good example is the card and it's sub components, which merge in selective props from child components.

**Comment by pimlie** [comment]
> and picking only ones that will work in the current situation

If you do it like this it is still up to (y)our interpretation what will work, it's much easier to just allow everything. That way if you add a prop to a child component you also wont have to change all parent components to include that prop. Of course we would probably need to add a big :exclamation: in the docs that users are on their own when using it, but at least they'd have the possibility to hack the component a bit (like with the `no-gutters` case in tabs). 

Btw, how I used `Object.assign` in the example above would make you loose reactivity but thats why its just an example :wink:

**Comment by tmorehouse** [comment]
many components are now providing options to apply classes to inner elements, as an alternative to using targeted css ( tagertted css is still preferred)

closing for now as the topic is stale.
