### ISSUE TITLE
Button size issue

### ISSUE THREAD

**Issue by radostnomne** [bootstrap-vue/bootstrap-vue#1377]
How can I set size of button?

I tried `<b-button :size="sm">Click</b-button` as docs says. 
But got error:

> Property or method "sm" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

**Comment by pi0** [comment]
Hi. Please try using:

```vue
 <b-button size="sm">Click</b-button
```

**Comment by radostnomne** [comment]
it works, thank you. I think the docs needs to be fixed

**Comment by mosinve** [comment]
Doc examples are ok. Just remember that `:` is sugar for v-bind, and v-bind is used when you are providing a variable. If you want to pass just a string value to attribute - it doesn't need `v-bind`
