### ISSUE TITLE
[b-tabs] v-model is immutable with dynamic tabs

### ISSUE THREAD

**Issue by hydraheim** [bootstrap-vue/bootstrap-vue#1378]
![btabs](https://user-images.githubusercontent.com/29726093/33018672-9bdd4f60-cdf7-11e7-9daf-8064027c2768.gif)

In summary:
- Attach v-model to `<b-tabs>`. **I.e:** `<b-tabs v-model="selectedPage">`. 
- When creating a new tab (by i.e: clicking a button like in the [DOCS](https://bootstrap-vue.js.org/docs/components/tabs#dynamic-tabs)), update the `selectedPage` to the length of the tabs content in order to set the active tab to the page that was just created. 
- Expect the corresponding tab for the new page to be selected. However, it isn't.

Pseudo:
```
newPage () {
  this.tabs.push('Content')
  this.selectedPage = this.tabs.length - 1
}
```

However, if you hard code this.selectedPage to say 1, the active tab is indeed set. 

Here's a fiddle showcasing the issue:
http://jsfiddle.net/mojvw303/10/

**Comment by mosinve** [comment]
Hi, you forget about Vue updating it's vdom async. so this example should use nextTick.

**Comment by mosinve** [comment]
Here's your example working as expected http://jsfiddle.net/cihkem/3apaaz4n/1/

**Comment by hydraheim** [comment]
Thanks, but that's already been tried to no avail. There may be issues with the component when it gets complex.

**Comment by mosinve** [comment]
i'm sure, it's not the component issue, it's about how Vue deals with changes.

**Comment by hydraheim** [comment]
Have a look at this then. The selected page is within nextTick(), however, as seen the "selectedPage" is never changed (as seen on the left side). The page length is, however.

![btabs2](https://user-images.githubusercontent.com/29726093/33019047-1d26e09e-cdf9-11e7-8e23-00eca562eedf.gif)

**Comment by mosinve** [comment]
So what's the difference between your code and jsfiddle example?

**Comment by hydraheim** [comment]
For some reason it works with
```
setTimeout(() => {
  this.selectedPage = this.pageElements.length - 1
})
```

but nextTick() doesn't. It was natural to believe the component was at fault, and while it now works, I'm still not convinced it's completely innocent. More research is needed, but meanwhile you can close this. Thanks for your time.

**Comment by mosinve** [comment]
Just to check, try to use global nextTick... `Vue.nextTick`  instead of component's `vm.$nextTick`
