### ISSUE TITLE
Sorting fires when clicking on non-sortable column

### ISSUE THREAD

**Issue by nikolay-borzov** [bootstrap-vue/bootstrap-vue#1379]
Click on `Is Active` column [here](https://bootstrap-vue.js.org/docs/components/table#sorting).
It says "Sorting By: , Sort Direction: Ascending"
Non-sortable column isn't supposed to generate `sort-changed` event

**Comment by mosinve** [comment]
As written below the example at Sorting section

> As mentioned in the Fields section above, you can make columns sortable. Clicking on a sortable column header will sort the column in ascending direction (smallest first), while clicking on it again will switch the direction of sorting. **Clicking on a non-sortable column will clear the sorting.**

**Comment by mosinve** [comment]
It's not bug, it's feature. :)

**Comment by nikolay-borzov** [comment]
Okay, but why? When can it be useful?

**Comment by mosinve** [comment]
dunno, maybe to allow user reset selected sort order to default.

**Comment by nikolay-borzov** [comment]
It's like default sorting by record id, when it isn't visible on UI)

**Comment by mosinve** [comment]
In example it resets to 'natural' data array order.

**Comment by tmorehouse** [comment]
Yep, clicking on a non-sortable column will "clear" the sort and place the data (items array) back into the order it was provided to b-table. This is by design.

**Comment by tmorehouse** [comment]
Not at the moment.

**Comment by gmmarc** [comment]
Hi! 

I understand this is a feature. 

However, it becomes unuseful when having a "select all checkbox header". Despite using click.stop or click.native.stop on the checkbox, it's easy to click in the area surrounding the checkbox. That causes sorting to reset and checkbox is not selected.

I want to note that I'm using this in a production environment and several customers have reported that "there's an error with sorting" (I even had to do a screencast with one of them to understand the issue :P).

I think it would be nice to have an easy way to disable this feature or being able to control it somehow.

In the meantime, I've figured out a tricky way to prevent this using head-clicked event:
```js
onHeadClicked (key) {
  if (key === 'checkbox') {
    // keep current sorting
    const sortBy = this.sortBy
    const sortDesc = this.sortDesc
    this.$nextTick(() => {
      this.sortBy = sortBy
      this.sortDesc = sortDesc
    })
    // toggle checkbox
    this.allSelected = !this.allSelected
  }
}
```

Cheers!

**Comment by gmmarc** [comment]
Despite my previous solution works, it causes a bunch problems, as sorting is happening twice. 

At the end, I extended the bTable component:

```js
import bTable from 'bootstrap-vue/es/components/table/table'

var bTableCustom = {
  extends: bTable,
  methods: {
    headClicked (e, field) {
      if (this.stopIfBusy(e)) {
        // If table is busy (via provider) then don't propagate
        return
      }
      let sortChanged = false
      if (field.sortable) {
        if (field.key === this.localSortBy) {
          // Change sorting direction on current column
          this.localSortDesc = !this.localSortDesc
        } else {
          // Start sorting this column ascending
          this.localSortBy = field.key
          this.localSortDesc = false
        }
        sortChanged = true
      }
      this.$emit('head-clicked', field.key, field, e)
      if (sortChanged) {
        // Sorting parameters changed
        this.$emit('sort-changed', this.context)
      }
    }
  }
}
```

A final solution could be adding a new property:

```vue
<b-table :no-sort-reset="true" :items="items" :fields="fields"></b-table>
```

It only requires one change in the component:

```js
    headClicked (e, field) {
      if (this.stopIfBusy(e)) {
        // If table is busy (via provider) then don't propagate
        return
      }
      let sortChanged = false
      if (field.sortable) {
        if (field.key === this.localSortBy) {
          // Change sorting direction on current column
          this.localSortDesc = !this.localSortDesc
        } else {
          // Start sorting this column ascending
          this.localSortBy = field.key
          this.localSortDesc = false
        }
        sortChanged = true
      } else if (this.localSortBy && !this.noSortReset) { // check sort reset
        this.localSortBy = null
        this.localSortDesc = false
        sortChanged = true
      }
      this.$emit('head-clicked', field.key, field, e)
      if (sortChanged) {
        // Sorting parameters changed
        this.$emit('sort-changed', this.context)
      }
    }
```
