### ISSUE TITLE
Possible memory leak with dropdown and vue-router

### ISSUE THREAD

**Issue by tochoromero** [bootstrap-vue/bootstrap-vue#1391]
Hello guys, I have found a memory leak when using the drop-down component and switching between routes.
Here is a reproduction link https://jsfiddle.net/tochoromero/1tup51he/2/

If you use the link to move back and forth and take a look at the memory usage you will see that the VueComponents are not being garbage collected.

I initialize opened an issue against the Vue repo, but they suggested to open it here instead, here is the link to the other issue https://github.com/vuejs/vue/issues/7101.

I hope you guys have an idea of what is going on and can provide an isolated reproduction example without having to add bootstrap-vue.

**Comment by tmorehouse** [comment]
Thanks, we'll check into this to see what may be happening. It is probably that `Popper.js` instance may not be garbage collected when routes change.

Would you by change be happening to use the `<keep-alive>` Vue component?

**Comment by tochoromero** [comment]
Thanks for looking into this. And no, I'm not using the `<keep-alive>` component.

**Comment by tmorehouse** [comment]
I think we have discovered the possible culprit... doing some dropdown garbage collection on `destroyed()` rather than `beforeDestroy()`

**Comment by tmorehouse** [comment]
Fix should be available in next release.

**Comment by tochoromero** [comment]
Unfortunately, I'm still able to reproduce the issue on 1.3.0 :(

You can still see it on the same jsfiddle
https://jsfiddle.net/tochoromero/1tup51he/2/

**Comment by tmorehouse** [comment]
Hmmm, I am not sure what would be causing this, other than Popper.js itself, as we are removing  the Popper.js instance during the beforeDestroy() hook.

**Comment by tmorehouse** [comment]
What browser are you using?

**Comment by tochoromero** [comment]
I'm using Chrome 62.0.3202.94 on a Mac OS High Sierra

**Comment by tmorehouse** [comment]
Do you see similar issues in, say Firefox?

Also, popovers and tooltips are similar in that they also use Popper.js.  do you notice any memory issues with them?

**Comment by tochoromero** [comment]
It does happen in Firefox.

And it doesn't happen with tooltips

**Comment by tmorehouse** [comment]
Hmm, how about `b-nav-item-dropdown`?  It uses the same shared code as `b-dropdown` with the exception that it doesn't instantiate a Popper.js instance.

**Comment by tochoromero** [comment]
It can see the memory leak as well with `b-nav-item-dropdown`

**Comment by tmorehouse** [comment]
The only issue I can think of is that `<router-view>` is re-using some of the inner component elements when it swaps the components (and hence not actually removing all of the component inner elements).

try adding a `:key` to your router view, to let vue-router know not to re-use any of the vdom:

```html
<router-view :key="$route.fullPath"></router-view>
```

**Comment by tochoromero** [comment]
Adding `:key="$route.fullPath"` has no effects, the memory leak is still there :(

**Comment by tmorehouse** [comment]
This is quite puzzling

**Comment by tmorehouse** [comment]
The only other thing I can think of is the needed `onTouchStart` listeners, that get added to all the immediate children of `<body>` to get around an iOS bug. The listeners are removed when the dropdown is hidden, but if any of the body's immediate children change, then it might be possible that some get left behind.

**Comment by tochoromero** [comment]
> This is quite puzzling

I know, I spent 1 week tracking down the memory leak, it is possible there is a bug on Vue itself, but when I opened a bug against them they ask me to bring it up here first, they will not take reproduction jsfiddle with a dependency to any third party libraries.

**Comment by tmorehouse** [comment]
PR #1416 may address this issue by making the popper.js instance reference non-reactive.   If it doesn't then I am unsure of what the root may be.

**Comment by tochoromero** [comment]
I will test it as soon we have a build with the fix. Thank you for looking into this promptly.

**Comment by tmorehouse** [comment]
Then again, I am not sure this will fix the issue, as dropdowns inside a navbar do not have a popper instance instantiated.

**Comment by tmorehouse** [comment]
The latest `dev` branch has a few tweaks to dropdowns, which may address the issue.

**Comment by tmorehouse** [comment]
v1.4.0 is now available, which includes a few more "tweaks" to dropdowns, which might help address this issue.

**Comment by tochoromero** [comment]
I can still reproduce it with the JSFiddle I provided :(

**Comment by tochoromero** [comment]
What would be the next step, how can I help you? This memory leak makes the library unusable for us.

**Comment by tochoromero** [comment]
I believe I have found the root of the memory leak.
The leak affects any component that uses the `clickout` mixin.
The leak was caused because `removeEventListener` was being called on the wrong element.

**Comment by Chathula** [comment]
modal also has a memory leak.. when modal content is big it takes lot of time to build.. (with nuxt)
