### ISSUE TITLE
Table Responsive

### ISSUE THREAD

**Issue by shtse8** [bootstrap-vue/bootstrap-vue#1393]
By setting table :responsive="true", it should make the table responsive. That's true for the latest release. But I think the `table-responsive` class is added in wrong place. It should be added to the parent DOM of the table otherwise the table will be narrow down and cannot be fluid width.

Current:
```vue
<table class="table-responsive">
</table>
```

Expected:
```vue
<div class="table-responsive">
<table>
</table>
</div>
```

**Comment by tmorehouse** [comment]
The placement of the class is the recommended placement based on the official bootstrap docs: http://getbootstrap.com/docs/4.0/content/tables/#responsive-tables

As well, the root element of `<b-table>` is a `<table>` element. we do not wrap the inner table in any elements.

However, you are free to place b-table in  div, and add `table-responsive` class to that div.

**Comment by tmorehouse** [comment]
Note that you can also pass a breakpoint to the `responsive` prop (i.e. `sm`, `md`, `lg`, or `xl`), and at that breakpoint and up the table will switch back to `display:table` and `width:100%`
