### ISSUE TITLE
b-form-checkbox doesn't work in "HEAD_" slots in Table Component

### ISSUE THREAD

**Issue by ChugunovD** [bootstrap-vue/bootstrap-vue#1394]
I would like to use Form Checkbox Input in Head of table for quick sort by column value, But it is doesn't work.
I make a simple example:
https://jsfiddle.net/0hqdfLmz/
With default checkbox works well, with b-form-checkbox doesn't switch value or trigger change event.

**Comment by tmorehouse** [comment]
Because you are using a component in the second example, you need to use the `@click.native.stop` event (to trap the native click event, not the component c;lick event.  See updated fiddle at https://jsfiddle.net/0hqdfLmz/1/

**Comment by ChugunovD** [comment]
Thank you, very much! I'm newbie in vue and bootstrap-vue and it is not obviously without example.

**Comment by tmorehouse** [comment]
Yeah, it is a somewhat common happening, but depends on situation, and not always obvious when to use it.  But if you run into issues similar, just try adding and removing the `.native` modifier (trial and error).
