### ISSUE TITLE
Multiple menu items become active

### ISSUE THREAD

**Issue by sdr0x07b6** [bootstrap-vue/bootstrap-vue#1396]
Hi😃

- BootstrapVue v1.2.0
- Bootstrap v4b2
- Nuxt v1.0.0- rc11

Nuxt application,
For example...
Suppose there is a product, product history, cart page.

```
pages/
├── index.vue
├── cart/
│   └── index.vue
└── products/
    ├── index.vue
    └── history.vue
```

```html
<b-nav-item-dropdown text="Pages">
  <b-dropdown-item to="/products">Products</b-dropdown-item>
  <b-dropdown-item to="/cart">Cart</b-dropdown-item>
  <b-dropdown-item to="/products/history">History</b-dropdown-item>
</b-nav-item-dropdown>
```

Access the product page and open the menu.
https://monosnap.com/file/HqzPjfcC14537sHzmOYlc1KwEwLHIJ
As expected.

Access the cart page and open the menu.
https://monosnap.com/file/U66PmxP5IjPPu8fKvWRNZI69ksWF6E
As expected.

Access the product history page and open the menu.
https://monosnap.com/file/eJ5WnJS3PXhcQdV6NFFSf7otsBX7ZB
It is different from expectation.
"Products" item should not be active.
Should not the active class be an exact match rather than a partial match of the route URL?

**Comment by mosinve** [comment]
It seems that your problem in vue-route configuration as bootstrap-vue use router-link as underlying component

**Comment by tmorehouse** [comment]
You probably need to use the `exact` prop on your dropdown items (`exact` a Vue-Router `router-link` prop that controls how the active class is applied to router links, see https://bootstrap-vue.js.org/docs/reference/router-links)

**Comment by sdr0x07b6** [comment]
Thank you for reply.

Is this expected?

```html
<b-nav-item-dropdown text="Pages">
  <b-dropdown-item :to="{ path: '/products' }">Products</b-dropdown-item>
  <b-dropdown-item :to="{ path: '/cart' }">Cart</b-dropdown-item>
  <b-dropdown-item :to="{ path: '/products/history' }">History</b-dropdown-item>
</b-nav-item-dropdown>
```

I edited it, but it did not solve it...

I think the following meaning is the same in router-link.
- `to="/products"`
- `:to="{ path: '/products' }"`

---
The page transition itself is originally working properly.
What I point out is a menu item to which ".active" is given.
Match with "Products" route is halfway.

URL: `http://localhost/products/history`
Route match: `/products/history` <-- As expected.
Route match: `/products` <-- Only part of URL. But ".active" has been granted.

Is this a specification?

**Comment by mosinve** [comment]
There's a prop, named `exact` . This is what use should use.
Please, read following:
https://router.vuejs.org/en/api/router-link.html
https://bootstrap-vue.js.org/docs/components/dropdown#component-reference

Your example will be:

```html
<b-nav-item-dropdown text="Pages">
  <b-dropdown-item :to="{ path: '/products' }" exact>Products</b-dropdown-item>
  <b-dropdown-item :to="{ path: '/cart' }" exact>Cart</b-dropdown-item>
  <b-dropdown-item :to="{ path: '/products/history' }" exact>History</b-dropdown-item>
</b-nav-item-dropdown>
```

**Comment by sdr0x07b6** [comment]
I see. I understood `exact` prop. Thank you very much.
I'm sorry for troubling you. 🙇

**Comment by mosinve** [comment]
You're welcome! :)
