### ISSUE TITLE
Manually setting the busy prop in b-table seems to be broken 

### ISSUE THREAD

**Issue by robcresswell** [bootstrap-vue/bootstrap-vue#1398]
Simple JSFiddle showing that toggling the busy state between true and false leaves the table in its busy state (with faded styling etc).

JSFiddle: https://jsfiddle.net/8qx0syev/8/

Checked in Firefox Beta (58) and Chrome Beta (63)

**Comment by tmorehouse** [comment]
I've made a change to your fiddle, and set the default busy state to `false`, and don't see the issue (I switched to  dark table to see the difference easier). https://jsfiddle.net/8qx0syev/10/

So it looks like the busy state is slightly foobarred only if it is initially `true` on mounted.

**Comment by robcresswell** [comment]
Interesting observation! In my downstream code I call the load() function during the created() hook, which immediately sets loading to true and gives me the frozen table as above, even if data initally defined it as false. Thanks for confirming.

**Comment by tmorehouse** [comment]
I think we need to add an additional watcher to monitor the busy prop.

**Comment by tmorehouse** [comment]
Actually nope... we don't need a new watcher.  we just need to not populate 'localBusy` with  `this.busy` on mount/create, as `localBusy is used internally only by provider functions.

Should be a quick fix.

**Comment by tmorehouse** [comment]
v1.3.0 has been release, and the issue _should_ be fixed.
