### ISSUE TITLE
Examples on docs page don't work

### ISSUE THREAD

**Issue by marines** [bootstrap-vue/bootstrap-vue#14]
Title says it all.

**Comment by xori** [comment]
Yea I'm not sure if this was on purpose but they seemed to remove the `dist/` folder lately [(commit)](https://github.com/bootstrap-vue/bootstrap-vue/commit/6c4b718de14620b85064c9dcbd5318438a23d9f5#diff-b1e5d9ba842f46f26c6bbe2cbdbf016d) which is what the website is referencing.

**Comment by pi0** [comment]
@marines @xori Thanks for reporting that. we are aware of that (until library is added to a better CDN)

**Comment by pi0** [comment]
Issue now is resolved :) We are going to make docs even better in near future ...
