### ISSUE TITLE
[docs] slot-scope instead of scope

### ISSUE THREAD

**Issue by jonathanprl** [bootstrap-vue/bootstrap-vue#1403]
In regards to the `scope` attribute for table templates. `scope` is now deprecated, `slot-scope` should now be used. 

Example: https://bootstrap-vue.js.org/docs/components/table/#header-footer-custom-rendering-via-scoped-slots

VueJS docs regarding this: https://vuejs.org/v2/guide/components.html#Scoped-Slots

**Comment by tmorehouse** [comment]
We haven't yet bumped our peerDependencies to Vue `^2.5.0`, which is when the `slot-scope` was introduced.

But we'll definitely be updating the docs when we do.

**Comment by zychoo** [comment]
Hello, 
Not sure if writing in closed Issue is right thing to do. If I shouldn't, please advise. 

Is there any plan to migrate from `slot-scope` syntax to `v-slot` introduced in Vue 2.6.0?
Old syntax is now deprecated according to: https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax

**Comment by tmorehouse** [comment]
Creating a new issue would be better, so we can track it.

Both the new style and old style are supported (and depending on which Vue version you are using, will dictate which one to use).
