### ISSUE TITLE
Applying a class to table or tbody

### ISSUE THREAD

**Issue by tristanbes** [bootstrap-vue/bootstrap-vue#1405]
Hello,

After reading the doc and trying on my application I have two questions:

1/ How to apply a class on the table and **only** use that class ? because the `class` props will add the custom class to the "default" bootstrap4 and I don't want that. Ex: 
```html
<table class="my-custom-class c-table table b-table table-striped table-hover></table>
// instead of 
<table class="my-custom-class"></table>
```

2/ How to apply a class on the `tbody` node ? I don't see any options to achieve that.

Thank you

**Comment by tmorehouse** [comment]
Currently there isn't an option to add a specific class to the tbody, although you can target the tbody using standard CSS selectors. (i.e. `table.my-table > tbody { ... }`.

`<b-table>` will always add the Bootstrap `table` class (and the bootstrap-vue custom class `b-table`, mainly for targeting the sort styling).  THe other classes (such as `table-hover`, `table-striped` are controlled via the respective props.

**Comment by tristanbes** [comment]
thanks for the quick reply. so there's no way we have total control of the classes ? that's sad :(. The integration is already done, so having to adapt the already existing css code because of (any) library is not a great idea.

The table looks like

```
<table class="c-table">
        <thead class="c-table__header">
            <tr class="c-table__row">
                <th class="c-table__cell">Header</th>
            </tr>
        </thead>
    <tbody class="c-table__body">
        <tr class="c-table__row">
            <td class="c-table__cell">
                Example cell
            </td>
    </tbody>
</table>
```

The only thing I managed to do is the class on the cell itself :(. Is there any hacks involving not touching the css/selector itself.

Thank you ;-)

**Comment by tmorehouse** [comment]
As it generates a bootstrap V4 table, it will add the bootstrap v4 `table` class.

But if you are defining these custom table/row/cell classes in your app, then it shouldn't be too difficult to create selectors that override bootstrap's CSS when a specific class is applied to the outer `b-table`

**Comment by tmorehouse** [comment]
As a side note, you can apply additional custom classes to the outer table element (the root element of `<b-table>`.  Any attributes that are not props (plus class and style attributes) will be directly placed on the `<table>` element (although the bootstrap class `table` will always be applied),

You can also use the `fields` definition array of objects to apply custom classes to the data row cells (`<td>`), and to the header/footer `<th>` cells.

We just don't have an option for applying any classes to the `<thead>`, `<tbody>`, or `<tfoot>` elements.

**Comment by tristanbes** [comment]
> We just don't have an option for applying any classes to the <thead>, <tbody>, or <tfoot> elements.

Also `<tr>` for reference. :(

Anyway, thanks for the the hint. IMHO you should plan this for future release. Theming customisation is a must, and I don't want to create a library that will do the same thing than yours just to be able to add class on the rendered dom.

**Comment by tmorehouse** [comment]
We have added in 6 new props for placing custom classes or `thead`, `tbody`, `tfoot` `theader>tr`, tbody>tr` and `tfoot>tr`, which will be available in the next release.

**Comment by tristanbes** [comment]
Thank you for this :-)
