### ISSUE TITLE
Increased build size from 1.0.0 on

### ISSUE THREAD

**Issue by Trainmaster** [bootstrap-vue/bootstrap-vue#1406]
When updating from `1.0.0-beta.9` to `1.0.0` I observed a dramatic increase in build size. I've created an example repository so you can reproduce it: https://github.com/Trainmaster/vue-sandbox. Using the latest version (`1.2.0`) makes things better but is still worse compared to `1.0.0-beta.9`.

Clone the repository and run `yarn run build`. Compare the sizes of `build.js` by installing different versions of `bootstrap-vue`:
- `1.0.0-beta.9`: 183 kB
- `1.0.0`: 345 kB
- `1.2.0`: 317 kB

I also compared the sizes of `node_modules/bootstrap-vue/dist/bootstrap-vue.esm.min.js`:
- `1.0.0-beta.9`: 241 kB
- `1.0.0`: 252 kB
- `1.2.0`: 169 kB

How comes that the build size almost doubled? Is there something wrong with webpack config?

**Comment by tmorehouse** [comment]
We have switched to render functions from templates (to avoid SSR issues when using the `/es/*` files), which generates larger un-minified files, but the minified files, when gziped, are now smaller than before (<50kbytes)

There are also additional features, etc, that have been added which, unavoidably,  have increased the codebase. Any project, as features are added, will increase in size.

**Comment by tmorehouse** [comment]
Also, the non `esm.js` builds include the Popper.js library, whereas the `esm.js` build doesn't.

**Comment by tmorehouse** [comment]
For your webpack config, adding in the `mangle` option will decrease the build side.

**Comment by Trainmaster** [comment]
@tmorehouse The `build.js` files I compared were minified using `new webpack.optimize.UglifyJsPlugin`. The `mangle` option is `true` by default. So you're saying that gzip will make the difference?

**Comment by tmorehouse** [comment]
when gzipping the `*.min.js` (which would be done by most webservers when serving the files), you will notice the sizes being smaller.

**Comment by Trainmaster** [comment]
@tmorehouse That did the trick!

- `1.0.0-beta.9`: 183 kB
- `1.0.0`: 188 kB
- `1.2.0`: 175 kB

**Comment by tmorehouse** [comment]
beta.9 didn't have the `es/` build either.

You could also import the `/dist/bootstrap-vue.esm.min` build as well (which is pre-mangled)

**Comment by Trainmaster** [comment]
But shouldn't the best option be picked automatically? Especially after reading https://bootstrap-vue.js.org/docs/#build-variants.

I did some further tests and added vue to the `index.js`:
```javascript
import Vue from 'vue';
import BootstrapVue from 'bootstrap-vue/dist/bootstrap-vue.esm.min';
```

When running it with `webpack --display-modules`
```
build.js  240 kB       0  [emitted]  main                                                                                                                                                                                                       [0] (webpack)/buildin/global.js 488 bytes {0} [built]                                                                                                                                                                                        [1] ./index.js 325 bytes {0} [built]                                                                                                                                                                                                         [2] ./node_modules/vue/dist/vue.runtime.esm.js 207 kB {0} [built]                                                                                                                                                                            [3] ./node_modules/timers-browserify/main.js 1.36 kB {0} [built]                                                                                                                                                                             [4] ./node_modules/setimmediate/setImmediate.js 6.47 kB {0} [built]                                                                                                                                                                          [5] ./node_modules/process/browser.js 5.42 kB {0} [built]                                                                                                                                                                                    [6] ./node_modules/bootstrap-vue/dist/bootstrap-vue.esm.min.js 173 kB {0} [built]                                                                                                                                                            [7] ./node_modules/popper.js/dist/esm/popper.js 81 kB {0} [built]                                                                                                                                                                            [8] ./node_modules/lodash.startcase/index.js 18.3 kB {0} [built]       
```
it automatically uses the `esm.js` file. Imho `bootstrap-vue` should do the same.

**Comment by tmorehouse** [comment]
The `/es/` build allows your to take advantage of dead code removal

**Comment by Trainmaster** [comment]
Are you talking about tree-shaking? If so I can't get it to work, see https://github.com/Trainmaster/vue-sandbox/tree/test-tree-shaking. It's still including the whole package and the generated `bundle.js` has `304 kB`.

**Comment by tmorehouse** [comment]
I should have mentioned when importing individual components.
