### ISSUE TITLE
IE11 transpiling issue: SCRIPT1003: Expected ':'

### ISSUE THREAD

**Issue by noxoriaz** [bootstrap-vue/bootstrap-vue#1409]
After moving from bootstrap-vue beta to version 1.2.0 our application bundle is not working on IE11 anymore. I changed my configuration to transpile bootstrap-vue according to docs, but unfortunately the same error still persists. My configuration should be ok, but it seems that object shorthand property from bootstrap-vue is still not transpiling correctly.

- Detailed Error:
<pre>
SCRIPT1003: Expected ':'
/* harmony default export */ __webpack_exports__["a"] = ({
    mixins: [__WEBPACK_IMPORTED_MODULE_2__mixins__["i" /* idMixin */], __WEBPACK_IMPORTED_MODULE_2__mixins__["h" /* formStateMixin */]],
    components: { bFormRow: __WEBPACK_IMPORTED_MODULE_3__form_form_row__["a" /* default */], bFormText: __WEBPACK_IMPORTED_MODULE_4__form_form_text__["a" /* default */], bFormInvalidFeedback: __WEBPACK_IMPORTED_MODULE_5__form_form_invalid_feedback__["a" /* default */], bFormValidFeedback: __WEBPACK_IMPORTED_MODULE_6__form_form_valid_feedback__["a" /* default */] },
    render(h) {
</pre>

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
**Windows10**

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
**Internet Explorer 11**

- Version of Bootstrap-Vue that you are using
**1.2.0**

- Configuration:

**webpack.config.js**
<pre>
test: /\.js$/,
  loader: 'babel-loader',
  include: [ // use `include` vs `exclude` to white-list vs black-list
    path.resolve(__dirname, "src"), // white-list your app source files
    require.resolve("bootstrap-vue"), // white-list bootstrap-vue
 ],
</pre>

**.babelrc**
<pre>

{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}
</pre>

**app entry**
<pre>
import 'bootstrap-vue/dist/bootstrap-vue.css'
import '../../sass/Shared/main.scss'

import BootstrapVue from 'bootstrap-vue'
Vue.use(BootstrapVue)
</pre>

Please let me know if you need more details to help resolving this issue.

**Comment by tmorehouse** [comment]
It appears that the the few `.vue` files we have left are got getting transpiled correctly.

You can try this as a interim workaround (and see if it helps):
```js
import 'bootstrap-vue/dist/bootstrap-vue.css'
import '../../sass/Shared/main.scss'

import BootstrapVue from 'bootstrap-vue/dist/bootstrap-vue.esm'
Vue.use(BootstrapVue)
```

Which will force your app to use the fully compiled bundle.

**Comment by tmorehouse** [comment]
This should be addressed in the next release.

**Comment by noxoriaz** [comment]
Forcing the app to use fully compiled bundle worked for me!
