### ISSUE TITLE
can't create ratio-specific <b-img-lazy> blank images

### ISSUE THREAD

**Issue by drzraf** [bootstrap-vue/bootstrap-vue#1411]
When using `<b-img-lazy>` we expect a blank image to be shown a (short) amount of time before being replaced by the one in the `src` attribute.

The blank image can be given a specific **height** and a specific **width** in **pixels**.
But if the `<b-img>` is `fluid` (so that image's height will be adapt to width while respecting original ratio), then none of hardcoding `width` or `height` is desirable.

So far there is no way that I know to have lazy *and* adaptive images.
Ideally, I'd like to be able to pass `width:100%; height:auto;` to blank images in one way or another.

**Comment by drzraf** [comment]
On a slightly related note, there is no way to set a custom css to the blank image only:
Any class set to `b-img-lazy` in the template will remain even after the value of `src` is dynamically changed.

**Comment by tmorehouse** [comment]
B-img-lazy needs dimensions in order to create an image (the ratio is computed from the width and height),  the generated image is an avg which will scale up or down (maintaining its ratio) if the `fluid` prop is set.

Just like a regular image, the blank image needs dimension in order to determine the final space the image should take up. Setting one dimension to auto wouldn't provide this information, so the generated image wouldn't have any ratio.
Dimension is also required as it is impossible to know the lazy loaded image's dimension until it is actually lpaded.

B-img-lazy does support the fluid (and fluid-grow) prop, which makes it scale to fit within the width of its parent container.

**Comment by tmorehouse** [comment]
If you know the ratio your image is, such as 16:9, then you could set the blank image dimensions to say, 1600 x 900..

**Comment by tmorehouse** [comment]
A trick you can do to determine when the final image has been loaded is via a CSS attribute selector.

The placeholder image uses a data URI (`data:...`) as the rendered img `src`, while normally your lazily loaded image will start with either `http:`, `https:`, or `/`.  The following CSS rules check wither the `src` attribute _starts_ with a data URI or an external URI:

```css
img.my-img[src^="data:"] {
  /* This vill select hte image while the blank placeholder is present */
}
img.my-img[src^="http"],
img.my-img[src^="/"] {
  /* This will select the image when the final image is loaded */
}
```

**Comment by drzraf** [comment]
Thank you for confirming the use of this CSS selector for this task.
That way I put `.img-fluid[src^="data:"] { height:auto; }` (img-fluid already have a `max-width:100% !important`) and adding a `blank-height="73" blank-height="30"` did the trick (for these `730:300` images)

**Comment by tmorehouse** [comment]
The `img-fluid` class also already has the `height: auto;` set in CSS. (the `img-fluid` class is applied to the img when either the src is the blank image or the final image URL. So there shouldn't be a need to re-apply the `width: 100%` style.

The widths and height values are applied as attributes on the `img` tag (not as CSS width and height), to provide the browser a hint at what dimensions the source image is (i.e. the ratio). CSS then kicks in and uses `height: auto; max-width: 100%` when actually displaying the image (when the `fluid` prop is set) or `width: 100%; height: auto` (when the `fluid-grow` prop is set)

The `fluid-grow` prop triggers the following two CSS classes: `img-fluid` and `w-100` (width: 100%')
