### ISSUE TITLE
Disabling highlighting of b-dropdown when hovering or clicking 

### ISSUE THREAD

**Issue by leeren** [bootstrap-vue/bootstrap-vue#1417]
The following is the code I am currently using:

```
<b-navbar toggleable="md" type="dark" variant="info">
 <div>
   <b-dropdown variant="info" size="lg" class="m-md-0" no-caret>
   <template slot="button-content">
   &#x2630;<span class="sr-only" >Menu</span>
   </template>
      <b-dropdown-item href="#">A</b-dropdown-item>
      <b-dropdown-item href="#">B</b-dropdown-item>
    </b-dropdown>
  </div>
</b-navbar>
```

I am trying to emulate a navigation drop-down bar with a hamburger logo.  It seems like emulating the idea of using a span with the unicode character equivalent seems like the best bet. However, how can you disable the shadow that appears when hovering over it? Setting the variant of the `b-dropdown` to transparent does not work either as it does not assume the variant of the navbar encompassing it. What would the best workaround be?

**Comment by tmorehouse** [comment]
There is not `.btn-transparent` variant class (HTe variant is translated to `.btn-{variant}`).  You could use variant `link` (which uses the class `.btn-link`).

See the hidden caret example, which is using an icon as the menu toggle button  https://bootstrap-vue.js.org/docs/components/dropdown#hidden-caret

**Comment by tmorehouse** [comment]
Also note that is you disable and hover/focus styling of the trigger element of the dropdown, then it will be impossible for keyboard users to know that they have tabbed onto the dropdown trigger.

**Comment by leeren** [comment]
Right, it is the hidden caret example that inspired me to construct the example I posted. With the link variant, however, the unicode symbol is highlighted blue and underlined upon hovering. Is there a simple way of disabling this or just making it plain?

**Comment by tmorehouse** [comment]
You can use custom CSS to target the toggle button, and set `text-decoration: none !important;`, and set the `color:` to the desired value.  You may need to target with the `:hover` pseudo selector.

The default CSS is defined by bootstrap's CSS.

You could also create your own custom `.btn-{variant}` CSS as well.

**Comment by leeren** [comment]
Thanks a lot for the help! Is there any chance you could direct me to some examples on how to target the dropdown button and override its default bootstrap CSS? I can't find any examples for this on the documentation.

**Comment by leeren** [comment]
Ah, overriding `.btn-link` worked!

**Comment by tmorehouse** [comment]
Targeting as in making a CSS selector that "targets" the toggle button inside the dropdown component.  i.e. `.dropdown > button.btn-link { ... };` if you happen to have used the `link` variant.

Either way (CSS selector), or custom variant will work.
