### ISSUE TITLE
Set id on <li> in tabs

### ISSUE THREAD

**Issue by tvld** [bootstrap-vue/bootstrap-vue#1418]
Right now the ``<li>`` tabs only have a class ``<li role="presentation" class="nav-item">`` and the child ``<a>`` can get an id with index ``<b-tab  :id="'tab_nr_' + f"  [...]>``. However, if we need to scroll the tabs programatically, we would need to scroll to a _child_ of the row and not to a grandchild.

As css does not have _parent_ selector, there is a feature request: allow to set an ``id`` with an index for example  ``<li id="index_1">``

**Comment by tmorehouse** [comment]
Could you not programmatically find the parent of the `<a clas="nav-link">` via `Element.closest('.nav-item')`? https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

**Comment by tvld** [comment]
Sure... that is possible ;)  But it wont be very elegant and has room to fail if ever the structure changes after anupgrade.. Normally the rule is that the highest child that is _repeated_ should  get an index, as css is much better in dealing with children than searching poossible anchesters...

**Comment by tmorehouse** [comment]
The ID's that we generate are for relating the control (i.e. the `<a>` element) to the container it controls.  The markup generated (i.e. `<ul> >`<li>` > `<a>`) and the classes they use are standard Bootstrap V4 markup/classes.

**Comment by tvld** [comment]
Ok, then the work-around works. I will close the issue. Thank you )

**Comment by tvld** [comment]
As info, we now use ``:title-item-class="tab_nr_' + idx``. It's not as elegant as ``title-item-id``  but that is not implemented (yet?)

**Comment by tmorehouse** [comment]
No plans on adding a prop for `title-item-id`
