### ISSUE TITLE
Dynamic property for v-b-toggle

### ISSUE THREAD

**Issue by tvld** [bootstrap-vue/bootstrap-vue#1420]
When dynamically building  an accordion with a for-loop, we need to 
```html
<b-btn block href="#" v-b-toggle.accordion1 variant="info">Accordion 1</b-btn>
```
But ``v-b-toggle.accordion1`` can not be constructed dynamically, can it?  Would ``:v-b-toggle="'#accordion' + index"`` have been more logical? Or am I missing something ? ... ))

**Comment by tmorehouse** [comment]
`v-b-toggle` does accept a dynamic value to specify a single target ID.  Not do not include the `#` as it doesn't accept a CSS selector.  just pass the plain id as a string (not it must be a string, and ID's are not allowed to start with a digit):

```html
<div v-for="id in [1,2,3,4]">
  <b-btn block v-b-toggle="'accordion-' + id" variant="info">
    Accordion {{ id }}
  </b-btn>
</div>
```

Note here is no `#` in front of the generated ID

**Comment by tvld** [comment]
Excellent, thank you))  ...  >> Example to documentation ? ))

( Small typo for the docs: ``accordion`` instead of ``accordion-`` )

**Comment by tmorehouse** [comment]
Passing an ID via the value of the directive is documented at https://bootstrap-vue.js.org/docs/components/collapse#usage

**Comment by tvld** [comment]
Oops... sorry overlooked badly ... thanks again )

**Comment by joseali93** [comment]
me paso igual que @tvld pero igual muchas gracias :+1:

**Comment by alexander-bogomolov** [comment]
Hi @tmorehouse, 

I have some problems in combination with a table.  After the table items are refreshed (AJAX call, empty array and push new items) the v-b-toggle do not change. The ID of the b-collapse-Element changes as expected.

Same problem with the modal component.

Is there a trick to "refresh" the event listener?

`
            <template slot="requestId" slot-scope="data">
                {{data.item.id}}
                <b-btn v-b-toggle="'test-'+data.item.id" variant="primary">
                    Toggle Collapse
                </b-btn>
                <b-collapse :id="'test-'+data.item.id" class="mt-2">
                    {{data.item.id}}
                </b-collapse>
            </template>`

Many thanks in advance!

**Comment by alexander-bogomolov** [comment]
As a workaround I can use the row.index
is it a desired behavior?

**Comment by SandorZoltanHorvath** [comment]
Hi @tmorehouse ,

I would like to use v-b-toggle with multiple dynamic elements. Basically, I would like to trigger two elements on two different places with generated dynamic ID 

Many thanks!

**Comment by gmmarc** [comment]
@alexander-bogomolov you saved my day!

**Comment by tdurant72** [comment]
I know this is closed but this might help other who need a "dynamic id". I am doing an api call and creating the accordion based on the returned results. I also created a function to filter results based on a title so I can make one call but create separate accordions.
`        <div id="app">
                <div role="tablist">
                    <b-card no-body class="mb-1"  v-for="(faq, index) in filteredTraffic">
                        <b-card-header header-tag="header" class="p-1" role="tab">
                        <b-btn block href="#" v-b-toggle="'accordion'+index" variant="info">{{faq.question}}</b-btn>
                        </b-card-header>
                        <b-collapse v-bind:id="'accordion'+index" accordion="my-accordion" role="tabpanel">
                        <b-card-body>
                            <p class="card-text">
                            {{faq.answer}} <br>
                            <a v-if="faq.links !==null" :href="faq.links.Url">{{faq.links.Description}}</a>
                            </p>
                        </b-card-body>
                        </b-collapse>
                    </b-card>
                </div>
        </div>`
I hope this helps.

**Comment by chaudois** [comment]
@alexander-bogomolov hi, I am facing a similar problem, could you elaborate your workaround? i essentially iterate on my b-card on an array that i later append with new elements. the b-collapse's id update as expected but not the header's v-b-toggle.

**Comment by tdurant72** [comment]
Sure chaudios, my work around is pretty simple. Now for me I needed 3 accordions that pull from the same list so I used js filter. For both the v-b-toggle and the v-bind:id I used an accordion name with the index number appended to the end.  That's it. I included a gist so you can see all the code if you want. 
https://gist.github.com/tdurant72/773bc0a25e8194d6c336d7ec6b062d48

**Comment by andriyfm** [comment]
superb, thanks a lot!

**Comment by Tzahile** [comment]
Hi, sorry to bother in a closed issue but I'm facing a problem when removing an item from the v-for array.
I did something similar to what @tmorehouse suggested.
`v-for="id in myArray"` when `myArray` is a _computed_ function, getting an array from $store.
I created buttons to remove which member you choose from the array in $store, so that the _computed_ function _myArray_ updates the v-for rendering whenever there's a change in this array.

My problem is that the **aria-controls** doesn't change, meaning if I have 4 headers and I remove the first one, in the new accordion the first header still opens the second collapse, the second header still opens the third collapse ( and the last one has nothing to open, so clicking on it does nothing)

**Comment by tdurant72** [comment]
With $store I assume you are using vuex? If so we believe you have to
mutate the data then rerender it. Do you have it in a fiddle somewhere?

**Comment by Tzahile** [comment]
I tried to prepare something in codesandbox but it didn't work out well with bootstrap..
I'll show here briefly the main part of my code (sorry for the comment length):

the app.vue file consists the component ```<main-test />``` in it  (store and bootstrap exist too).
In ```mainTest``` component I have:
```<div id="mainTestsId">
    <div v-for="test in TestsList"> 
      <test-view :Test='test'></test-view>
    </div>
</div>
<script>
import {default as testView} from '../myDirectory/testView/testView.vue'
export default {
  computed: {
    TestsList () {
      return this.$store.getters.GetTestsList
    }
  },
  components: {
    testView
  }
}
</script> 
``` 
(*$store.getters.GetTestsList* gets a list of tests from store state.
This list is set by the server when in another place I press a button to update the list, not important for this case;)

In **testView** component I have the vue-bootstrap *Collapse* component.
In the collapse header I added a remove-button that initiates a deleteTest function:
```
<b-card>
  <b-card-header>
    <b-btn :id="'accordion-' + Test.Id" v-b-toggle="'col-' + Test.Id">
      <b-card-header>
        <md-button @click.stop="deleteTest()" class="md-icon-button md-dense">
          <i class="fas fa-times"></i>
        </md-button>
      </b-btn>
  </b-card-header>
  <b-collapse :id="'col-' + Test.Id">
    {{ Some_Content }}
  </b-collapse>
</b-card>
<script>
export default {
  props: ['Test'],
  methods: {
    deleteTest () {
      this.$store.dispatch('RemoveTestFromList', [this.Test.Id])
    }
  }
}
</script>
```
(*RemoveTestFromList* does what it says - removes this.Test from the list in store)
_______________________________________________________________________________________
As I stated in first place - after removing one of the tests (let's say, the top *collapse* out of 5), the accordion changes: each test moves one place upwards and eventually the bottom *collapse* disappears.
**BUT the aria-controls stay the same!**
Henceforth, clicking now on the top *collapse* will open the second *collapse*, clicking on the second will open the third one (and so on..), clicking the last *collapse* won't do anything.

**Comment by po4tovuj** [comment]
got the same issue with using vuex.(( could anyone help?

**Comment by bsmaran** [comment]
My simple contribution

<body>

	<div id="myDiv" class="container">
		<row-list 
			title="Notas musicais" 
			v-bind:items="[	  { text: 'Do' },  { text: 'Re' },
						  { text: 'Mi' },  { text: 'Fa' },
						  { text: 'Sol' }, { text: 'La' },
						  { text: 'Si' }  ]"
		 ></row-list>
		<row-list 
			title="Singers" 
			v-bind:items="[
						  { text: 'Janis Joplin' },
						  { text: 'Jararaca e Ratinho' },
						  { text: 'Jimmy Hendrix' },
						  { text: 'Maysa' },
						  { text: 'Gal Costa' },
						  { text: 'Tim Maia' }
						  ]"
		 >
		</row-list>		
	</div>
</body>	
<script > var x = new Vue({el: "#myDiv"});</script>

**### associated script:**
var row_listTemplate = 
	'<b-row align-h="center" >' +
		'<b-col class="col02 " cols="10">' +
			'<b-card v-b-toggle="idRow" variant="success">{{ title }}</b-card>' +
			'<b-collapse :id=idRow class="mt-2 mb-2 " >' +
				'<div v-for="item in items">' +
					'<b-card class="herdarCor ml-5 shadow" >' +
						'{{item.text}}' +
					'</b-card>' +
				'</div>' +
			'</b-collapse>' +
		'</b-col>' +
	'</b-row>' ;

Vue.component('row-list', {
	data: function(){
		var idRow = _.uniqueId("idrow"); // from underscorejs
		return {
			items : this.items, 
			title : this.title,
			idRow : idRow
		};
	},
	props : ['title', 'items'],
	template: row_listTemplate
});

**Comment by bsmaran** [comment]
My simple contribution:
`<body>

	<div id="myDiv" class="container">
		<row-list 
			title="Notas musicais" 
			v-bind:items="[
						  { text: 'Do' },
						  { text: 'Re' },
						  { text: 'Mi' },
						  { text: 'Fa' },
						  { text: 'Sol' },
						  { text: 'La' },
						  { text: 'Si' }
						  ]"
		 >
		</row-list>
		
		<row-list 
			title="Singers" 
			v-bind:items="[
						  { text: 'Janis Joplin' },
						  { text: 'Jararaca e Ratinho' },
						  { text: 'Jimmy Hendrix' },
						  { text: 'Maysa' },
						  { text: 'Gal Costa' },
						  { text: 'Tim Maia' }
						  ]"
		 >
		</row-list>		
	
	</div>

	
</body>	
<script > var x = new Vue({el: "#myDiv"});</script>`


_**Associated script:**_

`var row_listTemplate = 
	'<b-row align-h="center" >' +
		'<b-col class="col02 " cols="10">' +
			'<b-card v-b-toggle="idRow" variant="success">{{ title }}</b-card>' +
			'<b-collapse :id=idRow class="mt-2 mb-2 " >' +
				'<div v-for="item in items">' +
					'<b-card class="herdarCor ml-5 shadow" >' +
						'{{item.text}}' +
					'</b-card>' +
				'</div>' +
			'</b-collapse>' +
		'</b-col>' +
	'</b-row>' ;

Vue.component('row-list', {
	data: function(){
		var idRow = _.uniqueId("idrow"); // from underscorejs
		return {
			items : this.items, 
			title : this.title,
			idRow : idRow
		};
	},
	props : ['title', 'items'],
	template: row_listTemplate
});`

**Comment by bsmaran** [comment]
**My simple contribution**
![ex1](https://user-images.githubusercontent.com/4808721/51861294-fc48cb00-2322-11e9-92f2-d049f9936a2a.png)

**_Associated template & script:_**

![ex2](https://user-images.githubusercontent.com/4808721/51861618-d5d75f80-2323-11e9-8443-633d014215d6.png)

**Comment by Omarillo** [comment]
SUper, me pasaba lo mismo, Thanks
