### ISSUE TITLE
Issue regarding spacing between navigation bar components

### ISSUE THREAD

**Issue by leeren** [bootstrap-vue/bootstrap-vue#1426]
When following similar formatting for creating a bootstrap-vue based navigation bar as documented [here](https://bootstrap-vue.js.org/docs/components/navbar/), I am unable to similarly replicate placing separate nav components horizontally next to each other. 

Specifically, I want to have a `navbar-brand` component and a `b-dropdown` component side-by-side on the top-left of my navigation bar. To do so, I use the following:

```
<template>
<b-navbar variant="dark">
      <b-dropdown variant="link">
        <b-dropdown-item href="#">A</b-dropdown-item>
        <b-dropdown-item href="#">B</b-dropdown-item>
        <b-dropdown-item href="#">C</b-dropdown-item>
      </b-dropdown>
      <b-navbar-brand href="#">Logo</b-navbar-brand>
</b-navbar>
</template>
```

However, this places the brand logo on the opposite (right side) of the nav bar. How can they be grouped on the left-side one after another?

**Comment by mosinve** [comment]
1. Use `b-nav-item-dropdown` instead of `b-dropdown`

**Comment by leeren** [comment]
Thanks!
