### ISSUE TITLE
[feature] calendar & datepicker component

### ISSUE THREAD

**Issue by ddydeveloper** [bootstrap-vue/bootstrap-vue#1428]
It would be great if bootstrap-vue included the separate calendar component. It can be is useful in lots of apps. There are several implementations from different authors [https://github.com/vuejs/awesome-vue](url), but there is no a configurable and bootstrap stylized solution. 

Are there any plans to implement this component in library?

**Comment by tmorehouse** [comment]
Currently Bootstrap-Vue's goal is to implement native Bootstrap V4 components and markup as Vue components.

We are looking at implementing Bootstrap-Vue "extra" components, that wouldn't be part of the main library, but as optional add-ons:  https://github.com/bootstrap-vue/bootstrap-vue/issues/417

**Comment by tmorehouse** [comment]
I've been considering creating a date-picker component, as most others that I have found are lacking in ARIA accessibility features, but I probably wont get to it until next year.

**Comment by epileftro85** [comment]
HI, it would be great this component, any update on it.

**Comment by syffs** [comment]
another suggestion: a markdown component

**Comment by TheAndroidGuy** [comment]
+1
Yes guys. We really need datepicker component 🥇

**Comment by Azassinz** [comment]
Can someone help me? I really need to usea b-calendar component, yesterday i update to v2.5.0 but this appears in console.
![image](https://user-images.githubusercontent.com/22536397/74946363-c4de0e00-53be-11ea-86b4-42309d4b7ca8.png)

**Comment by tmorehouse** [comment]
@Azassinz that error doesn't look related to Bootstrap Vue.

**Comment by Azassinz** [comment]
Do you think i missing something? I'm using JHipster, so i updated bootstrap vue to use this component, do i need another dependency or a special way to import it?

**Comment by tmorehouse** [comment]
Could you provide an example of how you are importing BootstrapVue, and an example of hte markup for the template you are using?

**Comment by Azassinz** [comment]
Sorry, i solved it noe, the problem is that JHipster only partialy use bootstrap-vue, to use the components you need to manually import them in config-bootstrap-vue.ts
![image](https://user-images.githubusercontent.com/22536397/74952320-c3641400-53c5-11ea-88f1-6ce6257788fa.png)
