### ISSUE TITLE
Modal header has explicit "rounded-top" class

### ISSUE THREAD

**Issue by Muukuro** [bootstrap-vue/bootstrap-vue#1432]
When adding `headerBgVariant="dark"` to a modal, the rendered `<header>` elements has an explicit `rounded-top` class added to it. This is not compatible with using Bootstrap SCSS and setting `$enable-rounded: false;`.

This only happens when adding a variant (doesn't seem to matter which).

![bootstrap-vue-modal](https://user-images.githubusercontent.com/6520064/33655603-ccf9d2de-da73-11e7-8961-69d4d8d3454c.png)

A [default Bootstrap modal](https://getbootstrap.com/docs/4.0/components/modal/#examples) already has rounded corners (in accordance with `$enable-rounded: false;`, so I would think these added classes are either unnecessary, or should be configurable in Vue.

**Comment by tmorehouse** [comment]
When dding a background-variant to the header, using default bootstrap CSS, the background color "protrudes" out past the top rounded corners, which is why we added the `rounded-top` class (when a header-variant is applied) to compensate for this.

We'll check to see if we can adjust for this (either with a prop, or another style (such as `overflow: hidden`), or it is possible that Bootstrap V4 may be addressing this in V4.beta.3

**Comment by tmorehouse** [comment]
Actually, the original bug (modal header background variant poking out rounded corners) appears to be fixed in Bootstrap V4.beta.2 (see https://github.com/twbs/bootstrap/issues/23798 and https://github.com/twbs/bootstrap/pull/23799).

I'll modify `b-modal` to remove the extra class.

**Comment by tmorehouse** [comment]
This has been fixed in release v1.4.0

**Comment by dflock** [comment]
This seems to be back for me, with these versions:

```js
"bootstrap": "4.0.0",
"bootstrap-vue": "2.0.0-rc.1",
```

I think the correct workaround is to fix the element that's sticking out underneath the header - the `.modal-content` - not the header itself. If you apply this to the `.modal-content`, it fixes it:

```css
border-top-right-radius: 10px;
border-top-left-radius: 10px;
```

**Comment by Dual-Ice** [comment]
I have the same issue, using:
> "bootstrap": "^4.3.1",  
> "bootstrap-vue": "^2.8.0",

![modal](https://user-images.githubusercontent.com/9907352/79557182-3fdd4f80-80f6-11ea-8726-34d5309c7f71.png)

How remove this white corners ?

**Comment by Dual-Ice** [comment]
Anybody here ?

**Comment by dflock** [comment]
My comment above explains how I fixed this: https://github.com/bootstrap-vue/bootstrap-vue/issues/1432#issuecomment-364614802 - just do this:

```css
.modal-content {
  border-top-right-radius: 10px;
  border-top-left-radius: 10px;
}
```

**Comment by Dual-Ice** [comment]
> My comment above explains how I fixed this: [#1432 (comment)](https://github.com/bootstrap-vue/bootstrap-vue/issues/1432#issuecomment-364614802) - just do this:
> 
> ```css
> .modal-content {
>   border-top-right-radius: 10px;
>   border-top-left-radius: 10px;
> }
> ```
Ок ) But 2 years have passed, bootstrap and bootstrap-vue have been updated more than once, haven’t they decided this at the product level?

**Comment by dflock** [comment]
Apparently not? The workaround does still work, though, fwiw.

**Comment by tmorehouse** [comment]
Another quick fix is using:

```css
.modal-container {
  overflow: hidden;
}
``

To make the background colors clipped to the border box (modal-container is what has the rounded corners)

Once caveat is that this can affect overflowing modals (modals that need to scroll)
