### ISSUE TITLE
Popover position not changed

### ISSUE THREAD

**Issue by josespinal** [bootstrap-vue/bootstrap-vue#1434]
Hi,

Recently I updated after a couple of weeks not touching this project. Now the popovers show not on the side (left, right) of the target element but on top instead.

Also placement has changed, had to set "left" when previously I had "right" to show the popover on the right side.

Thanks.

Previously:
![image](https://user-images.githubusercontent.com/10059/33669350-9d051502-da78-11e7-9c3a-2f1c512a411c.png)

Now:
![image](https://user-images.githubusercontent.com/10059/33669286-68000d94-da78-11e7-896d-983a006f1829.png)

**Here are my options:**
```html
<b-popover :target="'popover-' + product.id"
            triggers="click"
            placement="left"
            container="order-list"
            ref="popover"
            @show="onShow(index, $event)">
</b-popover>
```
- Operating system: Mac OS X
- Browser: Chrome
- Version of Bootstrap-Vue: Latest

**Comment by tmorehouse** [comment]
The default placement for popovers is `right`, but note that popovers will "flip" to the opposite side if there is not enough room in the container for the requested placement (i.e. if it is too close to the edge of the viewport)

Placement is also affected by where the trigger element is located, and the positioning of the container that the trigger element is in (relative, absolute, etc, as well as any css `overflow` settings)

**Comment by tmorehouse** [comment]
Could you provide a sample fo the additional markup around your popover/trigger elements?

**Comment by josespinal** [comment]
Made a CodePen replicating some. You can see it full page here: [https://codepen.io/josespinal/full/EbzdXM/](https://codepen.io/josespinal/full/EbzdXM/)

I've noticed something, if I remove scroll/auto from 'overflow-y' it is positioned as it did before:
You can check it out here (line 53 of CSS):
[https://codepen.io/josespinal/full/mqYzxO](https://codepen.io/josespinal/full/mqYzxO)

.order-list-wrapper {
   overflow-y: auto;
}

**Version used before was 1.0.0, now it's 1.3.0**

**Comment by tmorehouse** [comment]
Popper.js has issues with elements placed inside elements with overflow settings (the popper version has changed since version 1.0.0)

Maybe not using the container option might work better. Or position it below the table.

**Comment by josespinal** [comment]
Not using the container option, didn't make any change. Not onto trying positioning below the container but I'm a little stuck on referencing the target from outside the v-for loop.

**Comment by tmorehouse** [comment]
I've also noticed this doesn't work overly well for small screens (plus they are not overly suited to larger interactive forms) .  Have  you considered using a modal for you form instead of a popover?   modals are easier to make reusable (i.e. using a single modal, and then fill in the details and then programmatically opening it with ether the #ref show method or events.

**Comment by josespinal** [comment]
Yes, I was just considering that. Guess I'll go that road better, It would mean a sacrifice in speed for the user, but I can live with it. Thanks for all the help!

**Comment by tmorehouse** [comment]
Dropdowns have a similar issue (see #1163).  PR #1439 adds a new prop to popovers and tooltips to set the element that constrains positioning of the tooltip or popover (by passing this parameter as an option to Popper.js)

**Comment by avilesasturias** [comment]
In latest version still got issue with parent having overflow property set to it, even though boundary is specified to window.
Any solution on how to use tooltips on the right but still have overflow-y set to auto?
Thanks.

**Comment by aaronguernsey** [comment]
Hey @avilesasturias, did you find a solution to your issue?

I'm currently still getting this issue with v2.1.0. If I have a popover within an `overflow: auto` or `overflow: hidden` container, the popover is forced inside the container even if the boundary prop is set to 'viewport' or 'window'.

If I remove the overflow property, the popover works as needed; however, the overflow property is needed.

Any solutions or suggestions? Thanks.
