### ISSUE TITLE
Avoid resolving slots multiple times for better performance

### ISSUE THREAD

**Issue by sqal** [bootstrap-vue/bootstrap-vue#1437]
For example here - https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/input-group/input-group.js#L34 (but i think you're doing the same thing in every component)

I would simply change this to:

```
const $slots = slots();

if ($slots.left) { ... }
```

**Comment by tmorehouse** [comment]
We've optimized this is quite a few of the larger components, but we'll definitely do this in the other components (plus it does help during minification of the final code)

**Comment by tmorehouse** [comment]
This is now incorporated into v1.4.0
