### ISSUE TITLE
How to use it with plain CDN way

### ISSUE THREAD

**Issue by sujeetbuddiga** [bootstrap-vue/bootstrap-vue#144]
Hi, I'm trying to use bootstrap-vue by just including that in the html file and it doesn't seem to be working right. 
# Is there something I'm missing??

<img width="682" alt="screen shot 2017-03-14 at 8 02 38 am" src="https://cloud.githubusercontent.com/assets/3041104/23883448/046ca4d0-088d-11e7-9bda-121b49e92189.png">
<img width="1026" alt="screen shot 2017-03-14 at 8 02 10 am" src="https://cloud.githubusercontent.com/assets/3041104/23883447/04687f40-088d-11e7-9610-ce1a1f39e769.png">

# But the output is something like this:

<img width="1198" alt="screen shot 2017-03-14 at 8 07 29 am" src="https://cloud.githubusercontent.com/assets/3041104/23883497/57d4e182-088d-11e7-8fc0-a209b3f4a0f1.png">

**Comment by mosinve** [comment]
http://codepen.io/cih/pen/EWXzeB - simple use of Button

**Comment by mosinve** [comment]
@sujeetbuddiga, please tell if you need some more info.

**Comment by pi0** [comment]
More instructions are now provided in both README and docs. please feel free reopening this if needed more help :)
