### ISSUE TITLE
Can not change image size in carousel using "img-width" and 'img-height".

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#1441]
Documentation states: "When using img-src or img-blank on `<b-carousel-slide>`, you can set the image width and height via the img-width and img-height props on `<b-carousel>` and have these values automatically applied to each carousel-slide image."

Maybe I improperly understand it, but it seems that in case of `<b-carousel>` and `<b-carousel-slide>` I can use `img-width` and `img-height` in order to force images to change the size according to the values provided.

I tried to [play with live editor at the carousel page](https://bootstrap-vue.js.org/docs/components/carousel/) changing the values of `img-width` and `img-height` and nothing happens except the case for the last slide with `img-blank` property.

The size of slides at the carousel documentation page I can change just via `style="width: 100px; height=50px"` applied to each slides individually (`<b-carousel-slide>`).

Did I miss anything? What is the purpose of `img-width` and `img-height` if they do not change image size?

**Comment by tmorehouse** [comment]
The  `img-width` and `img-height` props only control teh image with when using the `img-src` or `img-blank` props. if manually placing images inside the carousel (or usinghte img slot), you will need to set the images width/height manually.

**Comment by TitanFighter** [comment]
The first 3 slides from carousel doc page do use img-src. According to the doc and what you said these slides should change its size when values for img-width and img-height are changed, but for some reason this does not happen.

**Comment by tmorehouse** [comment]
Remember that carousels are responsive in width, and that the images are fluid and will grow - up to their maximum native size- or shrink to the width of the container that the carousel is in.

**Comment by flip111** [comment]
@TitanFighter did you get this to work? Event when i wrap my `<b-carousel>` in a `<div style="height: 100px">` container the images stay on full height. The img `width` and `height` attributes seem to have no effect and this css rule applies

```css
.img-fluid {
    max-width: 100%;
    height: auto;
}
```

**Comment by TitanFighter** [comment]
@flip111 , no, I did not.

**Comment by mtsbarbosa** [comment]
@flip111 I have the same issue, the css from boostrap is overriding the height I am setting on the component attribute

**Comment by flip111** [comment]
@mtsbarbosa try setting the height on `<img>` instead of the component like i showed above
