### ISSUE TITLE
Lazy load image does not hit cache in PWA

### ISSUE THREAD

**Issue by tvld** [bootstrap-vue/bootstrap-vue#1443]
As per the test with the #1210 it seems that images are not checked by cache properly in a progressive web app. The images always "flash" when vue renders a new page, even if the image is in cache. 
Should ``<b-img-lazy>`` not check against cache first? If image is already in cache, render a normal ``<img />``? We can use a simple check:

```js
function isCached (src) {
    /* global Image */
    var image = new Image()
    image.src = src
    return image.complete
  }
```

**Comment by tvld** [comment]
This works for me:
```js
/* Bootstrap Vue component for Lazy loading images in PWA's
 Example:
   <lzimg
     src="https://lorempixel.com/600/400/cats/1/"
     alt="[img]"
     center
     fluid-grow
     width="600"
     height="400"
     blank-color="#bbb"
     class="my-5" />

 Dont forget to include in your main.js:
  import './assets/lib/_lazy-image.js'
*/

import Vue from 'vue'

Vue.component('lzimg', {
  template: `
    <b-img
      v-if="isImgCached()"
      :src="src"
      :fluid="fluid"
      :fluid-grow="fluidGrow"
      :width="width"
      :height="height"
      :alt="alt"/>

    <b-img-lazy
      v-else
      :src="src"
      :fluid="fluid"
      :fluid-grow="fluidGrow"
      :width="width"
      :height="height"
      :alt="alt"/>
  `,
  name: 'lzimg',
  props: {
    src: {type: String},
    alt: {type: String, default: '[img]'},
    center: {type: Boolean, default: false},
    fluid: {type: Boolean, default: false},
    fluidGrow: {type: Boolean, default: false},
    width: {type: String},
    height: {type: String},
    'blank-color': {type: String}
  },
  methods: {
    isImgCached: function () {
      /* global Image */
      var image = new Image()
      image.src = this.src
      if (!image.complete) {
        console.log('Img ' + this.src + ' not in cache, so lazy loaded.')
      }
      return image.complete
    }
  }
})
```

**Comment by tmorehouse** [comment]
The only issue for this is it dispatches a network get for every image, regardless of if it is in view or not (which is the whole point of Lazy loading images, to prevent network gets until the page is scrolled)

**Comment by tmorehouse** [comment]
Technically `b-lazy-img` is hitting your cache (assuming the image is cached), but remember `b-img-lazy` throttles/debounces scroll/resize events (configurable on a per `b-img-lazy` instance), so the "flash" you are seeing is most likely due to throttling the scroll event, as it detects if hte image is indeed in view (or within the view threshold).

Decreasing the throttle timeout, and increasing the threshold offset will minimize this effect.

**Comment by tvld** [comment]
Indeed, a bit less throttle solved the flash. Still there seems some challenge at times with the PWA cache (not the browser cache). I went back to just using ``<b-img-lazy>`` and the scroll event fire on the App component for non IE10/11 browsers.

Thanks will close and reopen if I find something related to PWA cache in this regard.
