### ISSUE TITLE
Sorting date column

### ISSUE THREAD

**Issue by capiono** [bootstrap-vue/bootstrap-vue#1446]
Hi, 

How do I make a date column sortable? Is there a way to override the default sort-compare routine?
I want to add something like this if type is date:

` return moment(left, 'MM/DD/YYYY hh:mm:ss').isBefore(moment(right, 'MM/DD/YYYY hh:mm:ss'));`

Thanks.

**Comment by tmorehouse** [comment]
There is a prop that you can pass a function reference to augment or override the built in dirt compare. It is passed two rows of data and the key that is being sorted. It needs to return one of 4 values:
-  -1 (or any negative number) when the b record is greater than the a record 
- +1 (or any positive number) when the a record is greater than the b 
- 0 if the records are 
- null if the default sort compare should be 

You would need to subtract the b date from the a date (most likely using the date serial numbers)  and return that value.

**Comment by capiono** [comment]
thanks this helped:
```

sortCompare (a, b, key) {
       if (typeof a[key] === 'number' && typeof b[key] === 'number') {
         return a[key] < b[key] ? -1 : (a[key] > b[key] ? 1 : 0)
       } else if (!isNaN(Date.parse(a[key])) && !isNaN(Date.parse(b[key]))) {
         return Date.parse(a[key]) < Date.parse(b[key]) ? -1 : (Date.parse(a[key]) > Date.parse(b[key]) ? 1 : 0)
       } else {
         return toString(a[key]).localeCompare(toString(b[key]), undefined, {
           numeric: true
         })
       }
     }
```

**Comment by capiono** [comment]
I have an issue, I'm sorting the dates using the momentjs library. this sorts properly, but the sort function is called multiple times:

```
onSort (a, b, key) {
       console.log(key)
       if (moment(a[key], 'MM-DD-YYYY').isValid() && moment(b[key], 'MM-DD-YYYY').isValid()) {
         if (moment(a[key], 'MM-DD-YYYY').isBefore(moment(b[key], 'MM-DD-YYYY'))) {
           return 1
         } else if (moment(a[key], 'MM-DD-YYYY').isAfter(moment(b[key], 'MM-DD-YYYY'))) {
           return -1
         } else if (moment(a[key], 'MM-DD-YYYY').isSame(moment(b[key], 'MM-DD-YYYY'))) {
           return 0
         }
       }
       return null
     }
```

For instance, I have 122 rows of data, when I sort by date the onSort function is called 917 times. do you have any idea why? 

I thought maybe it was moment so I tried 

`return Date.parse(b[key]) - Date.parse(a[key])`

same issue.

**Comment by tmorehouse** [comment]
What you are seeing is correct.  _At a minimum_, the sort compare routine will be called `n log n` times.   where `n` is the number of rows to sort.  Worst case is `n^2`, depending on how out of order the data is.

Check out this information on how sorting works: https://en.wikipedia.org/wiki/Sorting_algorithm#Comparison_of_algorithms

**Comment by tmorehouse** [comment]
In your routine, if `key` is not your data column, you should return `null` and let the built in sort-compare routine kick in for columns that are not your date columns.

**Comment by tmorehouse** [comment]
Your `onSort` routine is called **each** time two rows are being compared for order.  The name `onSort` might be misleading your perception of what it does.  you should really call it `compareRows` or something like that.
