### ISSUE TITLE
img lazy load show 1×1 svg

### ISSUE THREAD

**Issue by bestpika** [bootstrap-vue/bootstrap-vue#1447]
Hello.
My code

```vue
<b-img-lazy :src="data.img" :alt="data.device.name" fluid />
```

The `data.img` is an image from google firebase cloud storage.

```javascript
let gsRef = Firebase.storage().ref('device/image/' + this.auth + '.png')
gsRef.getDownloadURL().then(uri => {
  this.$set(this.data, 'img', uri)
  this.$forceUpdate()
}).catch(ex => {
  console.info('Please upload image: ' + this.auth)
})
```

When I first visit page, I got many 1×1 svg.
Then I reload this page, it show normal image.

**Comment by tmorehouse** [comment]
As mentioned in the docs, if an explicit width and height are not set, the blank image will be rendered with width and height of 1px.

**Comment by bestpika** [comment]
But when image loaded, it still show 1×1 svg

**Comment by tmorehouse** [comment]
Don't use `this.$set(this.data, 'img', uri)`. use `this.img = uri`. (ensure that `img` exists in your data() with value of `null`

Per the Vue docs (https://vuejs.org/v2/api/#Vue-set):
> Note the object cannot be a Vue instance, **or the root data object of a Vue instance**.

**Comment by bestpika** [comment]
My data
```vue
data: function () {
  return {
    data: {
      img: null,
      device: {},
      unsubscribe: undefined,
      gauge: {}
    }
  }
}
```

**Comment by tmorehouse** [comment]
As I mentioned above... don't use `$set` to set top level values in data. it worn't work.  use `this.img = uri`.

**Comment by bestpika** [comment]
Before this code, I use `this.img = uri`.
But I still get 1×1 svg...

**Comment by bestpika** [comment]
![image](https://user-images.githubusercontent.com/5698157/33863386-6724cef6-df22-11e7-8c09-10ba97d450e8.png)

**Comment by tmorehouse** [comment]
Use `this.img = uri` not `this.data.img = uri`

Also, you should set a `blank-width` and `blank-height` on `b-img-laxy`, otherwise it has no clue what size image will be lazily loaded. Otherwise, as the docs mention (https://bootstrap-vue.js.org/docs/components/image#usage), the lazy placeholder image will be `1px x1px`.

**Comment by bestpika** [comment]
My `data` struct is `data.data`.

**Comment by tmorehouse** [comment]
Please also read this link of `Vue.$set` method: https://vuejs.org/v2/api/#Vue-set

You are **not** supposed to use `$set` to set any top level values (which includes data) on the Vue instance.  this.data is a top level value.

**Comment by bestpika** [comment]
Now my code
```vue
<b-img-lazy :src="data.img" :alt="data.device.name" blank-width="100" blank-height="50" fluid />
```
```javascript
this.data.img = uri
```
I still get
![image](https://user-images.githubusercontent.com/5698157/33863755-4b757f0a-df24-11e7-9752-6fd0caaad379.png)

**Comment by tmorehouse** [comment]
> In blank image mode, if width and height are not set, **both width and height will internally be set to 1.**

This applies both to blank b-img and  the placeholder image b-img-lazy

**Comment by tmorehouse** [comment]
Placeholders also default to transparent color.

**Comment by bestpika** [comment]
![image](https://user-images.githubusercontent.com/5698157/33863795-7eadcada-df24-11e7-8205-e5e67c40916f.png)

**Comment by tmorehouse** [comment]
Note, lazy loading images needs the window to scroll in order to trigger the check to see if the image is within view.

**Comment by bestpika** [comment]
But I reload page.
![image](https://user-images.githubusercontent.com/5698157/33863908-0efe8b7e-df25-11e7-887c-9a68ec15e06e.png)

**Comment by bestpika** [comment]
So I have to get `this.data.img` before load page?

**Comment by tmorehouse** [comment]
It needs to be set before `b-img-lazy` is mounted in your case.

What you really should be doing, is not use b-lazy-img, but b-img with `blank` set to true, and then v-if it out of the document and v-if a new b-img (or just img) when your request has completed.

**Comment by bestpika** [comment]
![image](https://user-images.githubusercontent.com/5698157/33864043-ba88147e-df25-11e7-9522-e516e0e361a5.png)
Then I still got at my first visit page (clean cache).
![image](https://user-images.githubusercontent.com/5698157/33864057-c914de32-df25-11e7-9e27-8c3487ae3175.png)

**Comment by bestpika** [comment]
Ok, this code can work.
```vue
<b-img-lazy :src="data.img" :alt="data.device.name" :blank-src="data.img" fluid />
```
