### ISSUE TITLE
How to integrate "bootstrap-vue" to "vue-cli webpack template" and using?

### ISSUE THREAD

**Issue by sumate-sdk** [bootstrap-vue/bootstrap-vue#145]
Can you clearly explain clearly in the way to integrate both of them, and the ways of using bootstrap for the beginner?

**Comment by sushant-j** [comment]
Would love to have explanation for the above.
Or at least link to resource which would.

**Comment by pi0** [comment]
@thomasfowler Is working on preparing vue-cli usage docs. You can track details on Slack channel :)

**Comment by FragsterAt** [comment]
```
npm install vue-cli -g
vue-init webpack-simple projectname
...
cd projectname
npm install --save bootstrap-vue
```

add this in main.js after import Vue from 'vue':

```
import BootstrapVue from 'bootstrap-vue';
Vue.use(BootstrapVue);

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
```

**Comment by kylemh** [comment]
The instructions above assume that people should know to do `npm install --save bootstrap`.

The instructions above AND the instructions on the website AND in the GitHub README, also place the CSS imports lower than AirBnB (and likely Standard) linting will allow.

For users of Webpack or Webpack-Simple from `vue-clli` these should be the official instructions:
1. Download the dependencies:
`npm install --save bootstrap-vue`
`npm install --save bootstrap`
`npm install --save-dev style-loader`

2. In `src/main.js`, add the following lines, in priority order:
```
import Vue from 'vue';
/* ( there may be other imports here ) */
import BootstrapVue from 'bootstrap-vue/dist/bootstrap-vue.esm';
import 'bootstrap-vue/dist/bootstrap-vue.css';
import 'bootstrap/dist/css/bootstrap.css';
/* ( there may be other imports here ) */

Vue.use(BootstrapVue);
```

Vue.use(BootstrapVue);
Import styles using style-loader:


If you are unable or do not want to add style-loader as a developer dependency, you have to manually include both [Bootstrap's](https://v4-alpha.getbootstrap.com/getting-started/download/) and [BootstrapVue's](https://unpkg.com/bootstrap-vue@0.18.0/dist/bootstrap-vue.css) css files in your bundle or reference them from `static/` via `index.html`.

**Comment by SwagMuffinMcYoloPants** [comment]
I followed the instructions @kylemh gave and the bundle increased from 87.5 kB to 270 kB.  That seems really large. Is this normal?

**Comment by TheAndroidGuy** [comment]
Why in the documentation the installation process is not described like this?

**Comment by innerspirit** [comment]
@kylemh This doesn't work on the latest version. `style-loader` doesn't seem to work properly anymore, but replacing it with `npm install vue-style-loader --save-dev` does work.
