### ISSUE TITLE
Event listeners from v-b-modal aren't removed when the virtual element is removed

### ISSUE THREAD

**Issue by ThomasHickman** [bootstrap-vue/bootstrap-vue#1454]
As seen here: https://jsfiddle.net/6u1zo9qe/, if you use the v-b-modal directive, the click event listener isn't removed when the component is removed an another placed in it's place.

This looks like it is a problem with https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/utils/target.js, it may be better to listen to the vue events (which don't get removed when the component changes) and not DOM events.

**Comment by tmorehouse** [comment]
The v-b-modal directive, when applied to an element (note: it can be any type element, not just a button or link), must listen to native click events on the trigger element... there is no way around this.

This is expected Vue behavior. What you are seeing is a documented Vue artifact (https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key).  Vue "efficiently" re-uses elements that are `v-if/v-else`'d in and out of the DOM.  You need to set a unique `key" on both of your buttons to signify that they are not to be re-used:

```html
<b-btn key="btn1" v-if="condition" v-b-modal.modal>Button 1</b-btn>
<b-btn key="btn2" v-else>Button 2</b-btn>
```

Updated fiddle: https://jsfiddle.net/6u1zo9qe/1/
