### ISSUE TITLE
how to bind an array to pagination nav?

### ISSUE THREAD

**Issue by talalzaki** [bootstrap-vue/bootstrap-vue#1456]
how can i setting pagination nav to work with an array with axios. 
Thanks in advance. because base-url throw me to another route

**Comment by tmorehouse** [comment]
You would need to keep a local copy of the array, and then use the `link-gen` link generator prop and the `page-gen` page number generator prop.

Store your page array in your app/compionent data (and update the array after your axios get)

```html
<template>
  <div>
    <b-pagination-nav :link-gen="linkGen"
                      :page-gen="pageGen"
                      :number-of-pages="numPages"
                      v-model="currentPage" />
  </div>
</template>
<script>
export default {
  data () {
    return {
      currentPage: 1,
      links: ['/foo', '/bar', '/baz', '/faz']
    }
  },
  computed: {
    numPages () {
      return this.links.length
    }
  },
  methods: {
    linkGen (pageNum) {
      // Lookup the link from the array
      return this.links[pageNum - 1]
    },
    pageGen (pageNum) {
      // Return a the page link button text
      return `page ${pageNum}`
    }
  }
}
</script>
```

Once you get your array from axios get, store it in `this.links`

When using the `link-gen` function, base url is **not** prepended to the generated link.

See the docs examples at: http://localhost:3000/docs/components/pagination-nav#link-generation

**Comment by talalzaki** [comment]
thank you

**Comment by talalzaki** [comment]
thanks for your answer but it doesn't works take a look to my code : 

new Vue({
  el: '#app',
   data () {
    return {
      currentPage: 1,
      links: ['/foo', '/bar', '/baz', '/faz']
    }
  },
  computed: {
    numPages () {
      return this.links.length
    }},
   mounted(){
   	this.select_marks;
   } ,  
  methods: {
    linkGen (pageNum) {
      // Lookup the link from the array
      return this.links[pageNum - 1]
    },
    pageGen (pageNum) {
      // Return a the page link button text
      return `page ${pageNum}`
    },
    select_marks(){
     const v = this;
     axios.get('/product/allmark/')
     .then(function (response) {
      v.links=response.data;
       })
     .catch(function (error) {
      alert(error);
     })
    },
  }
})

**Comment by tmorehouse** [comment]
What oes your data array response from your axios get look like?

**Comment by talalzaki** [comment]
[{"marque":"Aderma","product":"A-DERMA SOINS ORIGINELS BAUME LEVRES 15ML","price":"68"........}]

**Comment by tmorehouse** [comment]
You will need to adjust the pageGen and linkGen functions to match your expected data format.

**Comment by talalzaki** [comment]
can you show me how please

**Comment by tmorehouse** [comment]
Without knowing what your expected end result end result is, it will be hard to help you.  The data sample you provided doesn't have any link information in it, s it looks more like a product definition array of objects

You may want to ask this type of question (how-to or teach-me) on StackOverflow or Slack, as GitHub Issues re for reporting bugs and feature requests, not instruction.

**Comment by talalzaki** [comment]
what's others arguments like pageNum?

**Comment by tmorehouse** [comment]
It is covered in the documentation at https://bootstrap-vue.js.org/docs/components/pagination-nav

Basically pageGen and linkGen receive a page number (1 through N), and they should return, respectively, the page number representation (text, which defaults to the page number if no pageGen function is defined) and HREF link.

**Comment by talalzaki** [comment]
thank you ,ok i ll re-examine the documentation.

**Comment by talalzaki** [comment]
what i must do to show links content i was using v-for to fetch data i get it but without pagination? thanks in advance.

**Comment by talalzaki** [comment]
i get it in the docs thanks

**Comment by talalzaki** [comment]
i resolve it with, is this correct?
 data () {
    return {
      currentPage: 1,
      links: [],
      nbp:4,
  }
computed: {
    pageLink () {
      return this.linkGen(this.currentPage)
    },
    numPages () {
      return Math.ceil(this.links.length / this.nbp);
    }
      },
linkGen (pageNum) {
      // Lookup the link from the array
       var s=  (this.currentPage-1) * this.nbp; 
       var e= s + this.nbp;
       var v= this.links.slice(s,e);
      return {vv} ;
    },
pageGen (pageNum) {
      // Return a the page link button text
      return `${pageNum}`
    },
and in template v-for="(taskk, index) in pageLink.d
