### ISSUE TITLE
b-nav-item-dropdown

### ISSUE THREAD

**Issue by christianmalek** [bootstrap-vue/bootstrap-vue#146]
The dropdown changes the width of the viewport and causes the scrollbar. Also the text isn't visible without scrolling. I'm using `bootstrap 4.0.0-alpha.6` and `bootstrap-vue ^0.10.0-alpha.1`.

![image](https://cloud.githubusercontent.com/assets/2873986/23948341/e4bc6854-0982-11e7-97ba-57aab3791f8b.png)

**Comment by pi0** [comment]
@christianmalek Try changing `rightAlignment` property to true.

**Comment by christianmalek** [comment]
@pi0 Thanks!
