### ISSUE TITLE
[server error] Cannot load the stats for bootstrap-vue – please try again later

### ISSUE THREAD

**Issue by taozhaolib** [bootstrap-vue/bootstrap-vue#1461]
After I ran npm i bootstrap-vue:

[server error] Cannot load the stats for bootstrap-vue – please try again later

                      Thanks for installing bootstrap-vue 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.

       👉  Donate: https://opencollective.com/bootstrap-vue/donate

+ bootstrap-vue@1.3.0
added 17 packages, removed 8 packages and updated 1 package in 8.102s

**Comment by tmorehouse** [comment]
Sounds like there is an NPM server issue, not related to bootstrap-vue

**Comment by maddog666** [comment]
I got the same issue.

    [server error] Cannot load the stats for bootstrap-vue – please try again later

                      Thanks for installing bootstrap-vue 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.


       👉  Donate: https://opencollective.com/bootstrap-vue/donate

npm WARN vuex-persistedstate@2.0.0 requires a peer of vuex@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0-beta.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

+ bootstrap@4.0.0-beta.2
+ bootstrap-vue@1.4.0

**Comment by mihaipopescu0409** [comment]
Hello, i've got the same issue too.

```
[server error] Cannot load the stats for bootstrap-vue – please try again later

                      Thanks for installing bootstrap-vue 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.


       👉  Donate: https://opencollective.com/bootstrap-vue/donate
```

bootstrap-vue@1.4.0
bootstrap@4.0.0-beta.2
Node 8.9.1

**Comment by JekaKey** [comment]
I am also get this issue.
`> bootstrap-vue@1.4.0 postinstall /Users/evgen/Projects/vue/test/node_modules/bootstrap-vue
> opencollective postinstall || exit 0

[server error] Cannot load the stats for bootstrap-vue – please try again later

                      Thanks for installing bootstrap-vue 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.


       👉  Donate: https://opencollective.com/bootstrap-vue/donate

npm WARN bootstrap@4.0.0-beta.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

+ bootstrap-vue@1.4.0`

Node v8.9.0
NPM 5.6.0

**Comment by taozhaolib** [comment]
I used yarn installation and it worked fine.

**Comment by vjanssens** [comment]
I'm also having the same issue.
Node v8.9.0
NPM 5.6.0

**Comment by blattmann** [comment]
I also just experienced the same issue.

**Comment by NicegirlA** [comment]
I've also got the same issue too.

Node 9.8.0
npm 5.8.0
bootstrap-vue@2.0.0-rc.6

```
[server error] Cannot load the stats for bootstrap-vue – please try again later
                                 ..,::::::::::,..
                              .,::::::::::::::::::,.
                           .,:::::::::::::::::::::,.
                         .:::::::::::,,,,,,,,:::,.
                        ,::::::::,.                      .
                       ,:::::::,                       .,,.
                      ,:::::::.                      .,,,,,.
                     .:::::::.                       .,,,,,,
                     :::::::.                        .,,,,,,.
                     :::::::                          ,,,,,,,
                     :::::::                          ,,,,,,,
                     :::::::.                        .,,,,,,.
                     .:::::::.                       .,,,,,,
                      ,:::::::.                      .,,,,,.
                       ,:::::::,                       .,,.
                        ,::::::::,.                      .
                         .:::::::::::,,,,,,,,:::,.
                           .,:::::::::::::::::::::,.
                              .,::::::::::::::::::,.
                                 ..,::::::::::,..


                      Thanks for installing bootstrap-vue 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.


       👉  Donate: https://opencollective.com/bootstrap-vue/donate
```
