### ISSUE TITLE
Can not focus in modal popover input field 

### ISSUE THREAD

**Issue by rut2** [bootstrap-vue/bootstrap-vue#1464]
the scenario is a bit complex. I am using bootstrap-vue modal and popover. I want to display a form within **modal -> popover**. something like this. 

![image](https://user-images.githubusercontent.com/4327606/33990063-b33ea2fc-e0ef-11e7-881c-ada13089a3a0.png)

But because of `modal-content` element's `tabindex = -1`, I can not focus on input field ever. Even if I click on input field it is not working. 

It is working in perfectly after I remove `tabindex=-1` from DOM

**Comment by tmorehouse** [comment]
Removing the tabidex on modal-content will break accessibility (for screen reader users and keyboard only users).

Currently popovers and tooltips get appended to the `modal-dialog` div, if they detect that the trigger element is inside a modal.

We might need to change that to append to `modal-content` to ensure that the popover/tooltip is within the tab-constraint area.

**Comment by tmorehouse** [comment]
To currently get around this,  wrap your modal content in a `div` (if you haven't already), give it a unique id, and then use the `container` prop of `<b-tooltip>` to specify the div's ID:

```html
<b-modal ...>
  <div id="my-container">
    <!-- other modal content here -->
    <b-btn id="my-button">Add</b-btn>
    <b-popover target="my-button" container="my-container" title="Title">
      <label for="my-input">Input</label>
      <b-form-input id="my-input"></b-form-input>
    </b-popover>
  </div>
</b-modal>

**Comment by tmorehouse** [comment]
This fix will be available in the next release.

**Comment by rut2** [comment]
It is working perfectly good. 

thank you @tmorehouse 

vue-bootstrap is best :)

**Comment by tmorehouse** [comment]
v1.4.0 has been released, which now appends the tooltip/popover to the modal-content container rather than the modal outer container.
