### ISSUE TITLE
Breaks on Vue.js 2.5.11

### ISSUE THREAD

**Issue by markgajdosik** [bootstrap-vue/bootstrap-vue#1469]
First of all, thank you for your hard work!

Vue 2.5.11, released only a few hours ago, has added spelling check for the component props (https://github.com/vuejs/vue/commit/d02bb37efb3c4ee14b8cf9db22d1ab3340ba2c0f). This appears to break bootstrap-vue:

```
vue.esm.js:576 [Vue warn]: Invalid key "value" in validation rules object for prop "validated".
vue.esm.js:576 [Vue warn]: Invalid key "rqeuired" in validation rules object for prop "src".
vue.esm.js:576 [Vue warn]: Invalid key "value" in validation rules object for prop "label".
```

Thanks.

**Comment by alexss3** [comment]
I am experiencing the same issue as well.  I searched the source of bootstrap-vue in node_modules and couldn't even find a reference to "rqeuired" so I'm not sure where the bug exists, but it does.
<img width="1675" alt="screen shot 2017-12-15 at 12 24 01 am" src="https://user-images.githubusercontent.com/24757608/34027922-f5b0be8e-e12d-11e7-947e-0145a2e954b6.png">

**Comment by aTanCS** [comment]
Same issue with vue 2.5.9.

**Comment by alexss3** [comment]
Hi Jack,  thanks for adding the commit. However, I think you missed the update to the img-lazy.js files with the 'rqeuired' misspelling.
