### ISSUE TITLE
Modal fade-in/fade-out native bootstrap/Vue transition

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#147]
hi @pi0, i saw that you implement your own transition subroutine for modals.
I've made it by setting Vue's native transitions right.
How d'you think, should i made PR for this?

**Comment by pi0** [comment]
@mosinve Hey :) Sorry answering late. yep, i just was trying to get native vue `transitions` working, however main modal transition is not working right. Whats you idea? (And also feel free opening a PR for that : )
