### ISSUE TITLE
Minor typo in form docs

### ISSUE THREAD

**Issue by robcresswell** [bootstrap-vue/bootstrap-vue#1479]
In https://bootstrap-vue.js.org/docs/components/form-input the contextual state examples uses "inputLiveFeeback" instead of "inputLiveFeedback". Note the missing "d". I can put up a PR later but just making a note while I solve the other PR I signed up for :)

**Comment by tmorehouse** [comment]
Fixing in a second, and then off to catch a plane...

**Comment by tmorehouse** [comment]
All fixed up in `dev` branch and will be available in the next release.

**Comment by robcresswell** [comment]
Awesome. Enjoy the tequila 🍹
