### ISSUE TITLE
form-select multiple selected default values doesn't seem to work

### ISSUE THREAD

**Issue by samcgarry** [bootstrap-vue/bootstrap-vue#1480]
Bootstrap-Vue 1.4.0

I'm using Bootstrap-Vue to create a select form using <b-select-form>.
In multiple mode I have tried setting v-model to be an array of values, but only one item is selected in the list. Is it possible to have  multiple values selected based on the array in the v-model?

<b-form-select v-model="selected" multiple :options="options"></b-form-select>

data () {
    return {
      options: ['a', 'b', 'c', 'd'],
      selected: ['a','b']
    }
  }

**Comment by tmorehouse** [comment]
Are you setting the `multiple` prop on b-form-select?

**Comment by tmorehouse** [comment]
This works for me:

```html
<template>
  <div>
    <b-form-select multiple :select-size="4" v-model="selected" :options="options" class="mb-3">
    </b-form-select>
    <div>Selected: <strong>{{ selected }}</strong></div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      selected: ['a','b'], // Array reference
      options: [
        { value: 'a', text: 'This is First option' },
        { value: 'b', text: 'Default Selected Option' },
        { value: 'c', text: 'This is another option' },
        { value: 'd', text: 'This one is disabled', disabled: true },
        { value: 'e', text: 'This is option e' },
        { value: 'f', text: 'This is option f' },
        { value: 'g', text: 'This is option g' }
      ]
    }
  }
}
</script>
```

**Comment by samcgarry** [comment]
Yes it does. Sorry about that. My simpler case was OK. 
I was actually using it by calling a vue component and passing the selected data in as a property and that property wasn't being set correctly as it turned out so that was why the selection was not working as I had expected.
