### ISSUE TITLE
Style interpolation failed on 1.4.0

### ISSUE THREAD

**Issue by qkdreyer** [bootstrap-vue/bootstrap-vue#1482]
Before opening an issue:

- [x] [Search for duplicate or closed issues](https://github.com/bootstrap-vue/bootstrap-vue/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- [x] Read the [contributing guidelines](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/CONTRIBUTING.md)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
Mac OS X 10.13.3 (17D20a)

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Chrome 63.0.3239.108

- Version of Bootstrap-Vue that you are using
bootstrap-vue@1.4.0

- Reduced test cases and potential fixes using [CodePen](https://codepen.io/), [JS Bin](https://jsbin.com/), or [JsFiddle](https://jsfiddle.net/) (You can export markup from the [online playground](https://bootstrap-vue.js.org/play) to JS Fiddle)
https://jsfiddle.net/bw6ct4gm/1/

---

We've noticed a kinda weird regression of bootstrap-vue@1.4.0.
While trying to reproduce the problem, I've noticed that it is working as expected using non modular versions of vue/bootstrap-vue.

But, after upgrading bootstrap-vue from 1.3.0 to 1.4.0, I've noticed that neither b-col, nor b-row, nor b-button would correctly interpolate a ":style" attribute. I've went through the whole diff and cannot understand why. It also might be specific to my project case, but simply downgrading to 1.3.0 would allow vue to correctly interpolate the ":style" attribute on any of these elements.

**Comment by tmorehouse** [comment]
Interesting. The components code should be identical.

Do you see a difference between using /dist/bootstrap-vue.js compared to /es/index.js?

**Comment by qkdreyer** [comment]
Nevermind, we were using a weird string syntax in order to populate :style.
After switching to object syntax (as specified by the [documentation](https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax)), everything is working as expected.

Closing now.
