### ISSUE TITLE
Progress bar from web docs

### ISSUE THREAD

**Issue by Branksy** [bootstrap-vue/bootstrap-vue#1483]
When using the progress component, copy pasted from  https://bootstrap-vue.js.org/docs/components/progress, only the first progress bar renders (animated) and the one below does not.

Getting:
Unknown custom element: <b-progress-bar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Please help. Thank you.

**Comment by tmorehouse** [comment]
Sounds like you are using the alpha (pre 1.x) bkotstrap-vue.

**Comment by mosinve** [comment]
Closed due to inactivity. 
Please reopen if issue still acctual.
