### ISSUE TITLE
[optional feature] stepper component

### ISSUE THREAD

**Issue by ddweber** [bootstrap-vue/bootstrap-vue#1484]
I know "_Currently Bootstrap-Vue's goal is to implement native Bootstrap V4 components and markup as Vue components_" but wouldn´t it be neat to have a **stepper component** like in the following link but with bootstrap styling and the approved bootstrap-vue syntax (slots, etc.).
It would be a great way to implement a **wizard** like **assistant** into web applications.

[https://github.com/PygmySlowLoris/vue-stepper](https://github.com/PygmySlowLoris/vue-stepper)

**Comment by caylorme** [comment]
+1

Can we see an implementation of this? 

Vuetify: https://vuetifyjs.com/en/components/steppers
mdBootstrap https://mdbootstrap.com/components/bootstrap-steps-stepper/

**Comment by paolog22** [comment]
+1

**Comment by tmorehouse** [comment]
closing as stale. one could incorporate 3rd party components for now, and tweak styles as needed).
