### ISSUE TITLE
v-show does not work with b-tab. v-if works ok

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#1488]
Boostrap-vue 1.4.0

Here is example:
https://jsfiddle.net/x3o39acm/3/

1. When you open the page, you see that initially `v-show` is false, however the tab is shown.
2. When you click few times `Show` button (in order to make `v-show=false -> true -> false` again) the content of the tab becomes hidden, however both (the tab + its content) must be hidden.

v-if works as expected.

**Comment by mosinve** [comment]
Whole example works b design.
It demonsrates the difference between `v-if` and `v-show`
`v-if` removes node from DOM, so parent `b-tabs` updates it's state with new set of tabs.
`v-show` just set `display:none` on node, and in fact all the nodes remain in place. So `b-tabs` still show tab navi for hidden tab

**Comment by TitanFighter** [comment]
@mosinve , yes, the difference between `v-if` and `v-show` I understand.

I just thought `v-show` should apply `display:none` to one of the element of `<div class="card-header">`, such as `<li role="presentation" class="nav-item">` or `<a role="tab" tabindex="-1" href="#"...`, instead of the element of `<div class="card-content">`.

Is there a way how I can apply `v-show` for the element of `<div class="card-header">` without using raw js for `display:none`?

**Comment by mosinve** [comment]
In your example you should use v-if.

**Comment by devonblzx** [comment]
I would argue the nav should not be displayed if the tab is hidden.  What's the point of showing the navigation for a tab that is supposed to not be displayed?

v-if does not work well with a lot of jquery plugins without a lot of additional processing.

**Comment by tmorehouse** [comment]
this is becuse of how Vue efficiently reuses rendered elements when the DOM updates. so order of the this.children may change and not reflect the actual DOM order

**Comment by iamgmd** [comment]
@tmorehouse Troy, thanks for your reply, I understand, is there no way of implementing anything into b-tabs/b-tab that can provide this or are we just stuck with it? I might have to look into other ways of accomplishing this otherwise.

**Comment by tmorehouse** [comment]
b-tabs support a lazy prop, which v-if the content put, but leaves the nav tab in.

you might want to have all the tabs visible on mohnt, and nextTick v-if them out.  i would recommend maybe keeping them inside a keep alive element, so that they disappear visually and document wise, but are still located in the dom in the order they were created.

**Comment by tmorehouse** [comment]
@TitanFighter nope, `<keep-alive>` component needs to be around _each_ `<b-tab>` individually. `<keep-alive>` state only applies to the immediate child (first child/only child) of the keep alive component.

**Comment by TitanFighter** [comment]
As I checked it earlier, [in this case](https://codesandbox.io/s/8119l5v8q0) the 2nd tab does not react on `v-if`.

**Comment by tmorehouse** [comment]
tabs weren't originally designed for this reactive table title. Going back to non title slot and regular udage shoukd work. my inclination is to compeltely remove this feature (it should have never been added to b-tabs to begin with, as it was not designed for reactive tabs or sub components in titles, just plain html).

**Comment by tmorehouse** [comment]
I think I will remove this feature (reactive titles) completely and revert the PR that added it.

**Comment by tmorehouse** [comment]
it's been more of a headache than anything.

**Comment by tmorehouse** [comment]
was easier to just handle people bitching about not being able to use components inside a title than it is now with the fact that the component just fails miserably with reactive title content.
