### ISSUE TITLE
Bootstrap postcss configurations

### ISSUE THREAD

**Issue by benmccallum** [bootstrap-vue/bootstrap-vue#1490]
Hi all,

I've been digging around this repo and I haven't found anything that details setup of or does the setup automatically of the postcss plugins bootstrap v4 uses. Let me know if I'm missing something. 

Bootstrap [requires](https://getbootstrap.com/docs/4.0/getting-started/webpack/) precss and autoprefixer.

Firstly, should we include that somewhere in the getting started as a call out for users to install (npm install) the plugins, add them to config (using their preferred method) and setup their browsers support list in package.json to match bootstrap's?

Secondly, in my case I'm using Nuxt and according to the [documentation for nuxt.config.js > build](https://nuxtjs.org/api/configuration-build) > postcss, the default appears to only include postcss-import, postcss-url, postcss-cssnext. [Here's the source](https://github.com/nuxt/nuxt.js/blob/c55df0796832339f6c132fb76a266acc6b9f249b/lib/common/options.js#L94) that handles this and can merge any user-defined postcss config from all possible sources over the top. Nuxt recommends using an external postcss.config.js file. Again, we could call that out in setup steps for bootstrap-vue so it's in the users hands, or... alternatively it could be installed in the plugin installation method, but that might be a little too magic for my liking.

Cheers, Ben.

**Comment by pSchaub** [comment]
I agree with you. For me as "newbie" to this library it's not clear what additional libraries I need to include and which configurations I need to set to use `bootstrap-vue` with Bootstrap v4 on a default `webpack` vue template

**Comment by tmorehouse** [comment]
Currently Bootstrap-Vue doesn't use Sass/scss for it's custom component CSS.

We are looking into using scss files that would allow for custom Bootstrap V4 variables.
