### ISSUE TITLE
Feature: In nuxt, only import/register components/directives passed in module options

### ISSUE THREAD

**Issue by benmccallum** [bootstrap-vue/bootstrap-vue#1491]
I've been able to [setup](https://gist.github.com/benmccallum/33ff008660218a578fc27fd33f51d1c1) a custom scss build for bootstrap to only include what I need, but I'm lacking an easy way to include in the JS build only the bootstrap-vue components I need so I can keep the bundle small.

The vue-bootstrap [documentation](https://bootstrap-vue.js.org/docs/) > "Importing components and directives" shows how it's possible for people in control of their webpack builds, but there's no simple option for nuxt.

The only way I see right now is to remove module registration from nuxt.config.js (`['@nuxtjs/bootstrap-vue', { css: false }]`), and instead replicate the functionality of nuxt > [index.js](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/nuxt/index.js) and [plugin.js](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/nuxt/plugin.js) myself. I'd prefer the ability to do this declaratively by passing through the module options an array of components and another of directives by name to import and register globally. 

I've been scouring the [source](https://github.com/nuxt/nuxt.js/blob/9b8cbed51236d32372706be7c2381df032c3dd88/lib/core/module.js#L60) of nuxt to see how/if the options defined for the module get passed from index.js (addPlugin) to plugin.js so I could take the arrays, import components/directives and register them with Vue globally. I'm just not sure how that'd work. Docs [here > Template plugins](https://nuxtjs.org/guide/modules#template-plugins) seems to allude to needing lodash templates. 

Anyone think this is useful and if it's possible? 

Thanks, Ben

**Comment by benmccallum** [comment]
I've been trying to do this myself by just using my own index.js and plugin.js files. 

index.js (module entry, added under modules in nuxt.config.js):

     const { resolve } = require('path')

    module.exports = function nuxtBootstrapVueCustom (moduleOptions) {
      // Don't add standard boostrap css
  
      // Add library styles
      this.options.css.push('bootstrap-vue/dist/bootstrap-vue.css')

      // Register plugin
      this.addPlugin(resolve(__dirname, 'plugin.js'))
    }

  module.exports.meta = require('bootstrap-vue/package.json')

plugin.js

    import Vue from 'vue'

    import { Modal } from 'bootstrap-vue/es/components'
    Vue.use(Modal)

But failing miserably. I'm getting a "SyntaxError Unexpected token import" in the browser. I assume it's because I need to modify the webpack build to handle bootstrap-vue folder. 

I looked in the documentation and it mentions whitelisting the bootstrap-vue folder, so I tried this:

    build: {
      extend (config, ctx) {
        let babelLoader = config.module.rules.find(r => r.loader === 'babel-loader')
        babelLoader.include = [
          require.resolve('bootstrap-vue')
        ]
      }
    },

But then I get the following. It's weird because it's failing in a file I didn't include. It's failing in a file in the .nuxt built directory...
![image](https://user-images.githubusercontent.com/157336/34371987-461c3774-eb1d-11e7-92b5-17a63f99182f.png)

So that makes me think I need to adjust the presets/plugins of webpack, as Nuxt just uses 'vue-app' preset. But I wouldn't know what to make it. 

Any help would be greatly appreciated!

**Comment by benoitemile** [comment]
+1

**Comment by elamperti** [comment]
+1. I tried adding this to Bootstrap-Vue but got stuck [after trying to modify the nuxt plugin](https://github.com/elamperti/bootstrap-vue/tree/individual-components) to import only components listed in `nuxt.config.js`. As far as I understand, it's currently failing because the components make imports and being inside node_modules they won't be transpiled -unless the user changes their setup locally-, so even if it _could_ work it's not a good solution. I'll leave the code there in case someone finds it useful to continue looking into this.

(disclaimer: the code in that branch can be improved :see_no_evil: I was just trying to make it work)

**Comment by benmccallum** [comment]
Thanks for giving it a crack @elamperti. Looks like you ran into the same transpilation hurdles I did. Hopefully the core team of each project can get it sorted. Really can drop the size of bundles if we can keep out anything we don't need 👍

**Comment by benmccallum** [comment]
I have a feeling that the new Nuxt 2.0 release may fix this... would the below be beneficial to our problem?

https://medium.com/nuxt/nuxt-2-is-coming-oh-yeah-212c1a9e1a67#8266
Nuxt 💖 ES modules
Now you can useimport and export inside nuxt.config.js, server middleware and modules thanks to the std/esm. A fast, production ready, zero-dependency package to enable ES modules in Node 6+ by John-David Dalton.

**Comment by pi0** [comment]
@benmccallum Unfortunately this enhancement won't help. But it would be a really nice enhancement for bootstrap-vue/nuxt module. (We can achieve this using plugin lodash template)

**Comment by benmccallum** [comment]
Hi @pi0, thanks for jumping in here. Are you saying we can achieve importing only the bootstrap-vue components we need by following what was done in the lodash plugin? Got a link?

**Comment by benmccallum** [comment]
Sorry to bother you again @pi0, was hoping you could answer my question above 🙏

**Comment by alidcastano** [comment]
@benmccallum You'll likely have to override nuxt's webpack config to include (or not exclude) bootstrap-vue
This issue might help: https://github.com/webpack/webpack/issues/2031

**Comment by benmccallum** [comment]
Thanks @alidcastano , I'll take a look when I get a chance. I did go down a webpack customization path as you mention but will dig further.

**Comment by sw-double** [comment]
I had success setting up plugin like this

```js
import Vue from 'vue'

if (process.server) {
  // Use full compiled version for ssr
  Vue.use(require('bootstrap-vue'))
} else {
  // Include only what you need for client
  // Note that you need to get .default from required module
  Vue.component('b-modal', require('bootstrap-vue/es/components/modal/modal').default)
}
```
