### ISSUE TITLE
Add an option to resize table columns

### ISSUE THREAD

**Issue by avner-hoffmann** [bootstrap-vue/bootstrap-vue#1496]
I looked for a way to resize bootstrap vue table columns through user interaction and didn't find any way to do this. It's a basic feature of any table

It would be nice to have this feature, please add it

**Comment by tmorehouse** [comment]
This would add a large amount of overhead to an already complex component that does more than it should do.

Native bootstrap doesn't support this feature.

**Comment by akimlyubchenko** [comment]
add `mounted` method to your component like this:

    mounted: function () {
		var thElm;
	    var startOffset;

	    Array.prototype.forEach.call(
		document.querySelectorAll("table th"),
		function (th) {
			th.style.position = 'relative';

			var grip = document.createElement('div');
			grip.innerHTML = "&nbsp;";
			grip.style.top = 0;
			grip.style.right = 0;
			grip.style.bottom = 0;
			grip.style.width = '5px';
			grip.style.position = 'absolute';
			grip.style.cursor = 'col-resize';
			grip.addEventListener('mousedown', function (e) {
				thElm = th;
				startOffset = th.offsetWidth - e.pageX;
			});

			th.appendChild(grip);
		});

	    document.addEventListener('mousemove', function (e) {
		    if (thElm) {
			    thElm.style.width = startOffset + e.pageX + 'px';
		    }
	    });

	    document.addEventListener('mouseup', function () {
		    thElm = undefined;
	    });
	}
