### ISSUE TITLE
Why doesn't the vue-cli template include bootstrap?

### ISSUE THREAD

**Issue by GarlandM** [bootstrap-vue/bootstrap-vue#1497]
I've followed the steps to set up a new bootstrap-vue template project via vue-cli, however it doesn't actually include bootstrap. 

Why is this?

Secondly, why is there no documentation on how to actually properly add bootstrap to a new bootstrap-vue project?

**Comment by bharathvaj1995** [comment]
@GarlandM Using bootstrap is optional. Refer [#145](https://github.com/bootstrap-vue/bootstrap-vue/issues/145)

**Comment by donalmurtagh** [comment]
I don't understand the purpose of the `bootstrap-vue/webpack` template if it doesn't install the bootstrap and bootstrap-vue dependencies, i.e. how is it different to the vue.js [webpack template](https://github.com/vuejs-templates/webpack)?

**Comment by Foefirelord** [comment]
Can anyone explain this? #145 is just confusing. Why does a bootstrap-vue version of the webpack template exist if it doesn't contain everything needed to immediately start creating an app with bootstrap-vue components?

**Comment by flaurian45** [comment]
Hi,
Same problem. I followed the instructions. webpack-simple gives a quick and easy start-up of a vuejs project including bootstrap-vue but  bootstrap-vue/webpack is webpack and nothing more.

**Comment by rbrtmrtn** [comment]
Ditto. Why does the template not show you how to import any of the components?

**Comment by TheAndroidGuy** [comment]
I am also asking myself the same question.

**Comment by mosinve** [comment]
1. According templates repositories, they should install and import all needed files
**webpack-simple** template:
https://github.com/bootstrap-vue/webpack-simple/blob/master/template/package.json
https://github.com/bootstrap-vue/webpack-simple/blob/master/template/src/main.js

**Webpack** template:
https://github.com/bootstrap-vue/webpack/blob/develop/template/src/main.js
https://github.com/bootstrap-vue/webpack/blob/develop/template/package.json

2. I've right just now created new project from webpack-simple template, followed docs instructions - and project HAVE bootstrap css files included.

**Comment by mosinve** [comment]
So, IMHO, this issue doesn't reproduce currently.

**Comment by mosinve** [comment]
Closed due to inactivity. 
Feel free to open if needed.

**Comment by Foefirelord** [comment]
@mosinve The webpack-simple template works. The webpack template doesn't.

This:
```
vue init bootstrap-vue/webpack my-project
cd my-project
npm install
```

Results in this:
```
"dependencies": {
    "vue": "^2.4.2"
}
```

This is with the latest vue-cli.

**Comment by mosinve** [comment]
Now it should be OK. Please, check it out.
