### ISSUE TITLE
Usage not illustrated

### ISSUE THREAD

**Issue by windwardrail** [bootstrap-vue/bootstrap-vue#15]
The documentation does not illustrate component usage. I see that this is a port from vuestrap and that their docs do include usage instructions, however it is not clear to me how it maps to your package. Thanks in advance.

**Comment by pi0** [comment]
Hey @windwardrail  :) Docs will be ready soon.. until then you can use components by replacing `vs-` prefixes to `b-` .. for exaple `<vs-button>` becomes `<b-button>` . Some Vue2 Specific things may differ for usage. please let us know if any problems.

**Comment by windwardrail** [comment]
Awesome! That's what I needed. Thanks :)

**Comment by FerchoCarcho** [comment]
@pi0 , Before diving in the core, Is there a place to know about the props which are refered on e.g. Alert component?

**Comment by pi0** [comment]
@FerchoCarcho See [Here](https://bootstrap-vue.github.io/) :)

**Comment by FerchoCarcho** [comment]
hi @pi0  I know, but could you make a live example, like from yuche's. Thank you for the fast reply. And this amazing plugin.

**Comment by pi0** [comment]
@FerchoCarcho your welcome :) Sure we will add live examples soon
