### ISSUE TITLE
[feature] Key enter in modal

### ISSUE THREAD

**Issue by stephanebressani** [bootstrap-vue/bootstrap-vue#1509]
Hello

It's possible to have a event @/v-on with key-enter in modal ?

Thanks

**Comment by ironyee** [comment]
`<b-modal @keydown.native.enter="handleEnter">`

**Comment by stephanebressani** [comment]
thanks !

**Comment by mosinve** [comment]
Closed due to inactivity. 
Feel free to open if needed.

**Comment by rehan-sattar** [comment]
Hi all, what about the `msgBoxConfirm` modal? How I can close it with the enter key pressed?
