### ISSUE TITLE
[Popover] Re-position on content change?

### ISSUE THREAD

**Issue by tsneed290** [bootstrap-vue/bootstrap-vue#151]
Started prototyping in Vue a month ago and stumbled onto this awesome library! Thank you for providing this!

I was messing around with the Popover component and realized that when the content of the popover dynamically changes, the Popover itself does not get re-positioned.

<img width="312" alt="screen shot 2017-03-17 at 11 03 17 am" src="https://cloud.githubusercontent.com/assets/1613037/24049137/76749f94-0b01-11e7-9803-abafd544492e.png">

...then the content changes...

<img width="320" alt="screen shot 2017-03-17 at 11 03 22 am" src="https://cloud.githubusercontent.com/assets/1613037/24049136/7674773a-0b01-11e7-87e4-c7b5dbfa20e1.png">

Mind you I am using this Popover component within a Modal component, might be worth mentioning there.

Also, when the Modal is closed, the Popover component remains, should I be listening to the modal "close" event and hiding the popover manually?

Thanks for any help!
-Tim

**Comment by pi0** [comment]
@tsneed290 Thanks for your feedback. i'll check this and come back to you soon. (Also ping @sirlamer :D he may help us)

**Comment by pi0** [comment]
UPDATE. I can reproduce both bugs now with playground :) 
- `beforeDestroy` is not invoked in some conditions like route changes or modal show/hides (this problem may be with vue caching)
- placement is done lazily (when i slightly scroll page tether will re position itself)

**Comment by tsneed290** [comment]
Can confirm that stimulating a "scroll" event when the popover content changes (via watchers) does fix the position, but it is still lazily changed.

**Comment by pi0** [comment]
@tsneed290 Re-positioning can be easily done pragmatically thanks to Tether API. question is how we can detect that content chenges ? :)

**Comment by tsneed290** [comment]
I'm still a major Vue.js newbie at this point, but couldn't you place a watcher on the "content" property and re-call this.setOptions() like you are with the placement, offset, and constraints props?

**Comment by pi0** [comment]
@tsneed290 Actually it is not possible simply watching content because we are using `<slots>`. I'll work more on finding out a solution :)

**Comment by tsneed290** [comment]
Ah, right :)

Well I was able to call Tether's position() using a Vue $ref to re-position, but it's just as lazy as invoking a "scroll" event.

Also, was not aware that this library had its own CSS file. After I took 0.10.0-rc.1 today I realized my modals stopped working because I was missing the CSS file. Might need to update docs.

**Comment by pi0** [comment]
@tsneed290 Docs are updated but i will add a bolder announcement on README . thanks :)

**Comment by tsneed290** [comment]
Thanks @pi0!

Oh, quick update. Calling positon() wasn't lazy. I wasn't waiting for the DOM to update. Using Vue.nextTick() proved to be a good workaround:

```
  watch: {
    popoverContent () {
      const _tether = this.$refs.valPopover._tether
      Vue.nextTick(function () {
        _tether && _tether.position()
      })
    }
  },
```

**Comment by pi0** [comment]
Also changes are not limited to content change. ([check this](https://jsfiddle.net/pi0/Lweyrv47/) ) maybe we can use a dirty workaround : periodically call `position()` when tooltip is visible. (it may not be SO costly as tooltips are only visible small time)

**Comment by SirLamer** [comment]
Sorry for being distant, I am traveling for work.

The suggestions to hook and resposition on changes are good. I am starting with looking at using MutationObserver to watch the popover element in general, but then might look for a polyfill replacement for continued IE10 support.

My sense is that it will probably be better and more efficient to just say "if you want to have dynamic content, use the 'title' and 'content' property, and pre-format your HTML". Then put watchers on those.

**Comment by pi0** [comment]
@tsneed290  We have tried hard to make popovers more stable and reacting to content changes. More improvements will come fore sure in future. Closing this for housekeeping re-open please if needed.
