### ISSUE TITLE
How to modify the caret of the dropdown?

### ISSUE THREAD

**Issue by FrancescoMussi** [bootstrap-vue/bootstrap-vue#1511]
I have two questions regarding the caret of the dropdown:

1. Is it possible to modify its css? 
I need to set its color to #999. I have tried to dive into the css of the dropdown to achieve it but wasn't successfull. How can that be done?

2. Is it possible to use a different icon entirely?

Thank you!

**Comment by Diaskhan** [comment]
FrancescoMussi do u satisfied by solution that offered rob ? 

If yes u could close the issue !
