### ISSUE TITLE
Support "fade" class/property of Alerts

### ISSUE THREAD

**Issue by hmexx** [bootstrap-vue/bootstrap-vue#1512]
Self-explanatory. Bootstrap 4 allows you to add a "fade" class to alerts to make them go away in a more attractive fashion (fade-out). Can bootstrap-vue be made to support this?

Great work btw.

Thx

**Comment by AdsonCicilioti** [comment]
Yep!
Wrapping with a `transition` Vue tag i can animate only the enter. When Dismissing Timeout ends or click on close button the alert is Destroyed, dont allow any animatiom with transition effects... 
Nice work on htis feature!!
