### ISSUE TITLE
The data-selected does not work on Form File

### ISSUE THREAD

**Issue by wss610** [bootstrap-vue/bootstrap-vue#1514]
I used Nuxt.js and bootstrap-vue bootstrap@4.0.0-beta.2 
`<b-form-file accept="image/jpeg, image/png, image/jpg, video/mp4" v-model="form.videoOrCover" choose-label="Goods" data-selected="upload image"></b-form-file>`
![image](https://user-images.githubusercontent.com/16313118/34638347-97c60b88-f304-11e7-8e64-44263db4de64.png)

**Comment by tmorehouse** [comment]
closing as stale and component implementation has changed
