### ISSUE TITLE
file input used @change the result is null

### ISSUE THREAD

**Issue by wss610** [bootstrap-vue/bootstrap-vue#1516]
When I used @change on Form File Input and selected file to upload, the result is null.
and used setTimeout 1 millisecond  the result is  file.
`<pre>
<b-form-file id="file_input2" v-model="file2" choose-label="Attachment2" @change="uploadFile"></b-form-file>

data () {
   return {
      file2: null
   }
},
methods: {
    uploadfile () {
        console.log(this.file2)
   }
}
</pre>
`

**Comment by tmorehouse** [comment]
Duplicate #1515
