### ISSUE TITLE
Preselection in b-form-select does not work

### ISSUE THREAD

**Issue by pascalfriedrich** [bootstrap-vue/bootstrap-vue#1519]
Hello everybody,

`              <b-form-select id="department"
                      class="employeeInput"
                      :options="department"
                      required
                      v-model="form.department">
        </b-form-select>`

`department: [
        { value: null, text: 'Bitte auswählen', disabled: true },
        { value: 'Pflege', text: 'Pflege' },
        { value: 'Küche', text: 'Küche' },
        { value: 'Betreuung', text: 'Betreuung' },
        { value: 'Haustechnik', text: 'Haustechnik' }
      ],`

It's not possible (propably just for me...) to preselect "value: null" -> "Bitte auswählen", no matter of disabled true or false. The form-select contains every single value, but preselection does not work. Where is my fault?

Best regards,
Pascal

**Comment by veonline** [comment]
are you using the `:value` prop of `b-form-select`? I solved a similar issue by setting the preselected value to the binded model (`form.department` in your case)

**Comment by mosinve** [comment]
Try to use empty string in default option.
