### ISSUE TITLE
Feature: Tab Prefix/Suffix

### ISSUE THREAD

**Issue by khalidadil** [bootstrap-vue/bootstrap-vue#1520]
When using tabs with bootstrap 4, it's easy to include icons inside of a tab since you're modifying the HTML. When adding icons to tab components with the title as the name of the tab, you end up with elements such as:
```
<b-tab title="<i class='fa fa-list-ul tab-icon'></i> Available" active>
</b-tab>
```

I've seen this handled more cleanly elsewhere by adding prefixes and suffixes, such as:
```
<b-tab prefix="<i class='fa fa-list-ul tab-icon'></i>" title="Available"  suffix=" - my suffix" active>
</b-tab>
```

This isn't a huge deal, just would be nice to have :)

**Comment by zoopyserg** [comment]
+1

I'd say add `<span slot='title'>`. 
Then the tab syntax would look like this:
````
b-tabs(card, lazy, v-model="tabIndex")
  b-tab
    span(slot='title') 
      i.fa.fa-icon
      span Some text after the icon
    span(slot='content')
      p Tab Contents 1
````
(I'm using `pug`, but you get the idea)

**Comment by zoopyserg** [comment]
As without it, all alternatives (Nav or Buttons) require reinventing the wheel.

**Comment by Morgul** [comment]
Yeah, adding a slot seems to "Bootstrap Vue" way to go.

**Comment by mosinve** [comment]
Hi! Yup! the feature is implemented already, will be available with next release ;)
