### ISSUE TITLE
Special Character in the <b-form-select>

### ISSUE THREAD

**Issue by Ethan0007** [bootstrap-vue/bootstrap-vue#1521]
Hi,

I have an issue when displaying text inside the character. see example,

![image](https://user-images.githubusercontent.com/12542052/34751547-589d9a98-f5e8-11e7-86f2-7879e18f79a1.png)

I have other solution to display the full text I just used v-for inside the option. But i want it to map using :options.

please be guided.
thanks!

**Comment by tmorehouse** [comment]
HTML tags inside of a select's `<option>` are not suppoprted in HTML.
