### ISSUE TITLE
Alert cannot load b-button-close when imported as an individual component

### ISSUE THREAD

**Issue by mehdirande** [bootstrap-vue/bootstrap-vue#1522]
Hi,

When importing only b-alert, if the dismissed prop is set like this: 

```

<template>
  <b-alert :show="true" :dismissible="true">Message</b-alert>
</template>
<script>
  import bAlert from "bootstrap-vue/es/components/alert/alert";
  export default {
    name: 'Dummy',
    components: {
        bAlert
    }
}
```

An error is throwed :

> [Vue warn]: Unknown custom element: <b-button-close> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

This is because the button si imported as bBtnClose (from button/button) and used with b-button-close.

**Comment by pi0** [comment]
Should be fixed in v1.4.1.
