### ISSUE TITLE
b-pagination always sets v-model value to 1 on page reload

### ISSUE THREAD

**Issue by jamesmwangi55** [bootstrap-vue/bootstrap-vue#1524]
When using b-pagination with a v-model

`<b-pagination :total-rows="total" v-model="value"></b-pagination>`

and then update the value in the create lifecycle hook

`created: function () {
      this.value = 2
 }`

after reloading the page the value is always **1** instead of **2** despite being set to 2 by the create method.

**Comment by jamesmwangi55** [comment]
Found out that this was being caused by some asynchronous code.

**Comment by Slicksim** [comment]
How did you solve this?  Been having the same issue when navigating directly to a page using the navigation bar

**Comment by Reedo0910** [comment]
I have the same issue. How did you solve this?

**Comment by Reedo0910** [comment]
Same issue! How did you solve this?
