### ISSUE TITLE
Can't use event handler for carousel-item

### ISSUE THREAD

**Issue by phakphumi** [bootstrap-vue/bootstrap-vue#1525]
My template

`<b-carousel id="carousel" style="text-shadow: 1px 1px 2px #333;" controls background="#ababab" :interval="3000" v-model="slide" @sliding-start="onSlideStart" @sliding-end="onSlideEnd">`
`<div v-for='movie in newMovie' :key='movie.title'>`
`<b-carousel-slide :img-src="movie.bannerURL" v-on:click="handleCarouselClick"></b-carousel-slide>`
`</div>`
`</b-carousel>`

My method
`methods: {`
    `onSlideStart (slide) {`
      `this.sliding = true`
   ` },`
   ` onSlideEnd (slide) {`
      `this.sliding = false`
   ` },`
   `handleCarouselClick () {`
     ` console.log(123)`
    `}`
`  }`

when I click on a carousel item there is nothing happen, but it works fine for other components such as card component.

What did I miss?

**Comment by thanhdd** [comment]
@phakphumi 

You can try with the solution that I posted in the issue: https://github.com/bootstrap-vue/bootstrap-vue/issues/1712

**Comment by fuoridallarete** [comment]
what if I need to call next() by clicking the slide?
