### ISSUE TITLE
b-form-file issue with "accept" values - in "multiple" mode

### ISSUE THREAD

**Issue by mmieluch** [bootstrap-vue/bootstrap-vue#1526]
[Link to JSFiddle](https://jsfiddle.net/5Lcspc1m/1/)

I found what to me looks like a strange behaviour of `b-form-file` component. I set an instance of `b-form-file` to support selecting multiple files, and specified `accept` MIME types, exactly like it's shown in the docs (just skipped the `image/gif` type):

```
<b-file v-model="files" multiple accept="image/jpeg, image/png"></b-file>
```

But when dropping any files (single or multiple) on the input doesn't update the model - the component simply ignores all the files, even valid ones. When picking files manually, instead of dropping them, the non-accepted files are disabled in the browser file select dialog (in Chrome), so that's OK. But then again - choosing any JPG or PNG file doesn't update the model, and the event emitted by the component has an empty payload.

`b-form-file` still behaves as expected when not in "multiple" mode.

OS: macOS High Sierra
Browsers: Chrome 63, Firefox 57
Bootstrap: 4.beta-2
BootstrapVue: 1.4.0

**Comment by Spatlani** [comment]
+1

**Comment by mayank-shaan** [comment]
+1

**Comment by yuta-kawai** [comment]
+1

**Comment by Diaskhan** [comment]
I guesse the problem in 
https://github.com/bootstrap-vue/bootstrap-vue/blob/142d517ecad405c6fcb73c112ba82998ee23d63a/src/components/form-file/form-file.vue#L299

**Comment by iruizeguilaz** [comment]
I have the same problem with multiple b-file, when I select more than one format by extension (for instace: ".pdf, .png") , The element or elements selected are nod added to the model

have you found  a solution for this issue?

best regards

**Comment by narramadan** [comment]
+1 

...Have the same issue

**Comment by rdeveen** [comment]
+1 should be fixed.

**Comment by impowski** [comment]
Is someone working on this one?

**Comment by tomattos** [comment]
we can pass the regular expression into accept property and it will work properly

**Comment by JackEggie** [comment]
> I guesse the problem in
> [bootstrap-vue/src/components/form-file/form-file.vue](https://github.com/bootstrap-vue/bootstrap-vue/blob/142d517ecad405c6fcb73c112ba82998ee23d63a/src/components/form-file/form-file.vue#L299)
> 
> Line 299 in [142d517](/bootstrap-vue/bootstrap-vue/commit/142d517ecad405c6fcb73c112ba82998ee23d63a)
> 
>                      if (files[i].type.match(this.accept)) {

`String.prototype.match()` takes the parameter `this.accept` as [regex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match).

@mmieluch Therefore, the comma in your accept prop can't be parsed by regex.

And I agree to @Diaskhan‘s opinion, `String.prototype.match()` is a misusage here.

**Comment by Demitroi** [comment]
+1

**Comment by yaroslawww** [comment]
+1

**Comment by thomasgerard** [comment]
+1
