### ISSUE TITLE
Dropdown menu does not automatically hide when inside a modal and you click elsewhere on the modal

### ISSUE THREAD

**Issue by JonUK** [bootstrap-vue/bootstrap-vue#1528]
If you place a dropdown in a modal, the dropdown menu does not automatically hide when you click elsewhere in the modal. This is unlike the behaviour of a dropdown normally where it does automatically hide when you click elsewhere on the screen.

I have created a JSFiddle to reproduce this issue: https://jsfiddle.net/JonUK/su9t3cgz/

This issue occurs in the latest versions of Chrome and Firefox.

**Comment by yoldar** [comment]
+1 I have the same problem

**Comment by pi0** [comment]
Will be available soon :)

**Comment by JonUK** [comment]
Thanks. Good work.
