### ISSUE TITLE
bootstrap-vue.css

### ISSUE THREAD

**Issue by jvukovich** [bootstrap-vue/bootstrap-vue#1530]
Can we make this configurable via module options?
`this.options.css.push('bootstrap-vue/dist/bootstrap-vue.css')`

I'd like to have control over how the css is integrated in my app, so I'd like to turn it off and handle it manually.

Thanks!

**Comment by pi0** [comment]
Hey. You can actually disable it using [bvCSS](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/nuxt/index.js#L23) option.

**Comment by jvukovich** [comment]
Oh, shoot. My npm install of @nuxtjs/bootstrap-vue is not showing that. "@nuxtjs/bootstrap-vue": "^2.0.4"; looking into  it.

**Comment by jvukovich** [comment]
Okay, I see what I did wrong now.

I should not use the nuxtjs/bootstrap-vue package:
`['@nuxtjs/bootstrap-vue', {css: false, bvCSS: false}]`

And should be doing this instead:
`['bootstrap-vue/nuxt', {css: false, bvCSS: false}]`

Thanks!
