### ISSUE TITLE
Question: Close collapse programmatically

### ISSUE THREAD

**Issue by felixoi** [bootstrap-vue/bootstrap-vue#1534]
Is there a way to close a b-collapse programmatically?

**Comment by SupriyaSudhindra** [comment]
Yes...just define a class with condition in the button/icon or where ever u want the click event to be triggered as below..
<b-list-group-item @click="showFolders(index)" :class="user.status ? 'collapsed' : null" aria-controls="user.user" :aria-expanded="user.status ? 'true' : 'false'"></b-list-group-item>
<b-collapse  id="user.user" v-model="user.status" class="mt-2"></b-collapse>
then...at the click function toggle the status or change the status as per your functionality...
me.users[index].status = !me.users[index].status
FYI...this code I had written for v-for as it was list...

**Comment by martinnaughton** [comment]
more explaination on how to do it programmatically 
https://github.com/bootstrap-vue/bootstrap-vue/tree/dev/src/components/collapse#v-model-support

**Comment by VasilijeBursac** [comment]
> more explaination on how to do it programmatically
> https://github.com/bootstrap-vue/bootstrap-vue/tree/dev/src/components/collapse#v-model-support
> 
> It does not work if you use it with accordion grouping. The accordion will over write it so it will not work

Great! This one gets the job done! Thank you! 😄
