### ISSUE TITLE
Bootstrap version info

### ISSUE THREAD

**Issue by msharitasa** [bootstrap-vue/bootstrap-vue#1536]
Request to mention Bootstrap version info in the release note

**Comment by Lumore** [comment]
Agreed with @msharitasa, there are some issues with bootstrap: labels, button groups - that's what I've noticed in my project. But I'm sure there is still another ones :(

**Comment by pi0** [comment]
Hi. We are working on Bootstrap beta.3 integration right now. Currently, the latest release is compatible with beta.2. Beta.3 tracking list is here: #1408.

**Comment by asafyish** [comment]
Version 4 will be released soon (hopefully !)

https://github.com/twbs/bootstrap/pull/25353

**Comment by hojas** [comment]
v4.0.0 is released.

**Comment by pi0** [comment]
We have released the first rc for 4.0.0 support. In a nutshell:

- BootstrapVue 0.x ....... Bootstrap 4.alpha
- BootstrapVue 1.x ....... Bootstrap 4.beta.2
- BootstrapVue 2.x ....... Bootstrap 4

**Comment by Xosmond** [comment]
Bootstrap 3 is not supported?

**Comment by mosinve** [comment]
@Xosmond, nope, this project is for VueJS 2.x + Bootstrap 4

**Comment by Xosmond** [comment]
@mosinve sad to hear that, because this project is great, thanks by the way.
