### ISSUE TITLE
add inpu-group-button at right not work

### ISSUE THREAD

**Issue by xcchcaptain** [bootstrap-vue/bootstrap-vue#1542]
Operating system:Windows 10  
Browser:firefox 52.5.3  
Bootstrap-Vue:1.4.1
Bootstrap:bootstrap@4.0.0-beta.2
[testcase](https://codepen.io/xcchcaptain/pen/NXEvNK)  
when i have `<b-input-group>		      	
		        <b-form-input type="text" placeholder="search..." >
                        </b-form-input>
		        <b-input-group-button>
		          <b-btn>go</b-btn>
		        </b-input-group-button>
		      </b-input-group>`  
it will get work 
so i think the problem is about self-end tag.
the document should be updated

**Comment by aTanCS** [comment]
I'm not sure if it is the same issue but with Bootstrap 4.0.0 and Bootstrap-Vue 2.0.0 I get this error:
```
Unknown custom element: <b-input-group-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

**Comment by mosinve** [comment]
This is outdated issue, since Bootstrap-Vue current version is 2.0.0-rc1 and Bootstrap is 4.0.0
`<b-input-group-button>` - is deprecated currently, `<b-input-group-append>` and `<b-input-group-prepend>` should be used instead.
