### ISSUE TITLE
Click away from b-dropdown not working in b-modal

### ISSUE THREAD

**Issue by folmert** [bootstrap-vue/bootstrap-vue#1543]
Setup: Windows 10, Chrome 63.0.3239.132 (Official Build) (64-bit), Bootstrap Vue 1.4.1, Bootstrap 4.0.0-beta.3

Reduced test case: https://github.com/folmert/b-vue-dropdown-bug (just clone, install, run start)

Steps to reproduce, expected behavior:

1. Click "Dropdown Button"
2. Click on empty space around "Dropdown Button"
3. Dropdown is closed - it's fine  

Steps to reproduce, bug:

1. Click "Open modal"
2. Click "Dropdown Button"
3. Click on empty space around "Dropdown Button"
4. Dropdown is not closed - BUG

**Comment by KonradDeskiewicz** [comment]
See #1528

**Comment by pi0** [comment]
Will be available soon :)
