### ISSUE TITLE
Safari, macOS: when clicking on a popover, the popover is not showing.

### ISSUE THREAD

**Issue by junqdu** [bootstrap-vue/bootstrap-vue#1547]
Navigate to https://bootstrap-vue.js.org/docs/components/popover#-b-popover-component-basic-usage

In Chrome, if you click on the button, the popover would stay, but not in Safari.

When reporting a bug, include:

- Operating system and version: Mac OS X, iOS devices
- Browser and version: Safari
- Version of Bootstrap-Vue that you are using: 2.0.4

**Comment by robcresswell** [comment]
I'm unable to recreate this, specifically trying the button at the [Programmatically disabling popover](https://bootstrap-vue.js.org/docs/components/popover/#programmatically-disabling-popover) heading. I tried on FF 58.0.2 and Safari 11.0.3on MacOS High Sierra. On both browsers, clicking the button then moving the cursor away, the popover stays (as expected, since the default trigger is click). The demos at the very top of the page are all set to hover. This could potentially be related to how browsers apply focus, though.

One thing, you've mentioned using bootstrap-vue `2.0.4`, which doesn't exist. Could you verify that?

**Comment by junqdu** [comment]
yes, for the "Programmatically disabling popover", Chrome and Safari behave the same, but not for https://bootstrap-vue.js.org/docs/components/popover#-b-popover-component-basic-usage

**Comment by junqdu** [comment]
and for bootstrap-vue, i meant the Nuxt wrapper, https://www.npmjs.com/package/@nuxtjs/bootstrap-vue

**Comment by piperone** [comment]
I don't know why the title of this issue says the popover is "not showing" when the description says "the popover would stay, but not in Safari". The popover *does* show, but there is indeed a difference in behavior from Chrome to Firefox/Safari on macOS. This difference doesn't exist on Bootstrap's own pages.

The button in the example mentioned does not seem to take focus when it's clicked (it doesn't get the outline). Safari and Firefox behaves the same, whereas Chrome triggers the focused state and the popover remains on mouseout from the triggering button.

![t2](https://user-images.githubusercontent.com/351744/37560845-fc8b28ba-2a3f-11e8-9e6f-2cba52a670c6.gif)

macOS 10.13.3
FIrefox 59.01
Chrome 65.0.3325.162
Safari 11.0.3

**Comment by RSchwan** [comment]
I also played a bit with this and it seems that the focus trigger only works in Chrome.
Some days ago I opened a similar issue #1662. There is also a jsfiddle with an example.

**Comment by RSchwan** [comment]
I found something interesting. I looks like on macOS if you click a button in Safari or Firefox the focus event is not triggered: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus).
On the other side if you replace the button tag with an anchor tag the focus event is triggered by a click: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Clicking_and_focus](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Clicking_and_focus).

**Comment by piperone** [comment]
You **can** trigger focus on the buttons mentioned earlier on Firefox and Safari if you ```tab``` to the button elements. The focus-selector isn't applied if you just click the buttons.

This discussion sparked a memory from a few years back. I remember having a similiar problem with Bootstrap 3's popovers. I created an issue on the Bootstrap-repo and it was determined that focus **does** behave differently on macOS in Safari and Firefox than other browsers. I can't remember the details exactly, but I'll link it here in case it's of interest for b-vue's devs:

https://github.com/twbs/bootstrap/issues/11788#issuecomment-40009020

**Comment by RSchwan** [comment]
If you have a closer look at the [original bootstrap documentation](https://getbootstrap.com/docs/4.0/components/popovers/#dismiss-on-next-click) it is even mentioned to use an anchor tag if you use the focus trigger.
Maybe it's a good idea to also add this to the boostrap vue docs.
