### ISSUE TITLE
How to make sure styles apply to only a component

### ISSUE THREAD

**Issue by ultrasamad** [bootstrap-vue/bootstrap-vue#1549]
When I added these imports; ` import 'bootstrap/dist/css/bootstrap.css'`     and                                            `import 'bootstrap-vue/dist/bootstrap-vue.css'`, to a component I want to use, I realized that the styles got applied globally to other pages. How do  I make sure it applies only to markup of that component?

**Comment by ChrisCalculus** [comment]
Where do you import? Can't you define a <style scoped/> section in your component and include the import there?

**Comment by ultrasamad** [comment]
Yh the style is already scoped. This is the snippet of the specific component I want to use it on.
`<script>
	import BootstrapVue from 'bootstrap-vue'
	import 'bootstrap/dist/css/bootstrap.css'
	import bootstrap-vue/dist/bootstrap-vue.css
</script>

export default {
	components: {
		BootstrapVue,
	}
}`

<style scoped>
   ....
</style>

I'm working on a legacy project which is using bootstrap 3.3.7, and in fact I only needed the tabs component from bootstap-vue at least for now, but can't find something that does what bootstrap-vue offers for the tabs especially the vertical pills. So when I imported the component with the styles as above, it interferes with the bootstrap 3.3.7 panels, making it smaller and the text as well. I can confirm that by removing the imports and things work normal. So pulling down the bootstrap4  styles I think is what might be causing it. But since it is also component based, I was thinking they wont be conflict. So what can I do in this case?

Thanks.

**Comment by mosinve** [comment]
In my view, in this case its better to import styles at <styles> section. 
such as:
```scss
<styles lang="scss" scoped>
@import "bootstrap/dist/css/bootstrap.css";
@import "bootstrap-vue/dist/bootstrap-vue.css";
.....
</styles>
```
this shoud force all included styles bind to custom component scope

**Comment by ultrasamad** [comment]
@mosinve Ok. will surely try that. thanks.

**Comment by ultrasamad** [comment]
@mosinve Sorry for no updates on the issue. When I tried using those `@import` statement in the styles, I get errors relating to unexpected tokens so I stopped using the package altogether.

**Comment by candacerogue** [comment]
Does anyone have any updated information on this question? I implemented the same feedback, but received an error from Vue saying, 

"These dependencies were not found:
* -!../../node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!../../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../../node_modules/postcss-loader/src/index.js??ref--8-oneOf-1-2!./bootstrap-vue/dist/bootstrap-vue.css in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/WorkingWithMe.vue?vue&type=style&index=0&id=50b2740f&lang=scss&scoped=true&
* -!../../node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!../../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../../node_modules/postcss-loader/src/index.js??ref--8-oneOf-1-2!./bootstrap/dist/css/bootstrap.css in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/WorkingWithMe.vue?vue&type=style&index=0&id=50b2740f&lang=scss&scoped=true&" referencing the  css-loader"

Any help would be great. The Bootstrap CSS is bleeding into my application, which took hours and hours to customize. Thank you in advance.

**Comment by daniellopez0708** [comment]
Okay so what I did is just write a new css file, because the bootstrap one was overwriting my actual css or scss files that I am using globally in my application
