### ISSUE TITLE
Checkbox broke with BS4

### ISSUE THREAD

**Issue by T0miii** [bootstrap-vue/bootstrap-vue#1551]
After updateing to Bootstrap 4 from bootstrap 4.0.0-beta  Checkboxes wont display.

Merzedes benz checkbox missing:
```
                        <b-form-checkbox id="mercedes"
                                         v-model="form.mercedes_benz"
                                         value="1"
                                         unchecked-value="0">
                            Mercedes Benz
                        </b-form-checkbox>
```
while the code from bootstrap4 website is working.
```
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck1">
                        <label class="custom-control-label" for="customCheck1">Check this custom checkbox</label>
                    </div>
```

![chexbkox](https://user-images.githubusercontent.com/10532141/35221190-8c0f549e-ff79-11e7-9ba4-5ceccf0c10e2.png)

My guess is that they changed the class from:

FROM -> custom-control-description
TO -> custom-control-label

This is taken from the Boostrap-vue component code:

    const description = h(
      'span',
      { class: t.is_ButtonMode ? null : (t.is_Plain ? 'form-check-description' : **'custom-control-description'**) },
      [t.$slots.default]
    )

Not quit sure if its a bug or if i got something cheesy in my code.

**Comment by lmm-git** [comment]
Please see #1504
