### ISSUE TITLE
Wrapping b-table in a child component

### ISSUE THREAD

**Issue by ChrisCalculus** [bootstrap-vue/bootstrap-vue#1552]
I'm trying to reduce boilerplate code by wrapping a `b-table` in a component (including filter, pagination, etc.). 

Utilising this wrapper component, I want to still be able to make use of named slots to do some formatting on the fields of the table. 

However, the naive approach of 'elevating' the slots to the parent component doesn't seem to work. 

See this [jsfiddle](https://jsfiddle.net/chriscalculus/agz1h9gk/) for an example on what 'm trying to accomplish.

VueJS documentation on use of named/scoped slots doesn't seem to cover this use-case. 

How should I approach this best using bootstrap-vue?

**Comment by mosinve** [comment]
Hi, https://jsfiddle.net/cihkem/a7f9axcf/ - is this solves your case?

**Comment by Aukhan** [comment]
Hey Guys, I'm looking for the same behaviour that @ChrisCalculus has demonstrated in the fiddle.

Has anyone been able to achieve that ? the table vue does not seem to pick up external slots.

**Comment by mosinve** [comment]
@Aukhan, have you checked this https://jsfiddle.net/cihkem/a7f9axcf/ ?

**Comment by emersoncpaz** [comment]
We need wrap <template> tag too. In your example <template> tag is inside <b-table> but we need to wirte inside <twrapper> tag. We need a slot of slot.

**Comment by emersoncpaz** [comment]
It works for me:

In child component:
`
<template>
  <b-table striped hover bordered small responsive="sm" :id="idTable" 
      :items="items"
      :fields="fields"
      <template v-for="field in fields" :slot="field.key" slot-scope="data">
        <slot :name="field.key" v-bind="data">{{ data.item[field.key] }}</slot>
      </template>
    </b-table>
</template>

export default {
    props: {
      idTable: {
        type: String,
        default: 'appTable'
      },
      items: {
        type: Array
      },
      fields: {
        type: Array
      }
    }
}
`
In parent component

`
<template>
    <app-table idTabela="tblIntituicoes"
      :items="dataItems" /* from an api request */
      :fields="fields"
      <template slot="actions" slot-scope="data">
        <i class="fa fa-info-circle fa-lg icon-button" title="Detail" @click.stop="showId(data.item.placeId)"></i>
        <i class="fa fa-edit fa-lg icon-button" title="Update" @click.stop="showId(data.item.placeId)"></i>
      </template>
    </app-table>
  </b-card>
</template>

<script>
import TableComponent from './TableComponent'

export default {
  data: function () {
    return {
      dataItems: [],
      fields: [
       {
          key: 'placeId',
          label: 'Id'
        },
        {
          key: 'placeName',
          label: 'Place Name',
          sortable: true
        },
        {
          key: 'placeTag',
          label: 'Place Tag',
          sortable: true
        },
        {
          key: 'telephoneNumber',
          label: 'Telephone'
        },
        {
          key: 'actions',
          label: 'Actions'
        }
      ]
    }
  },
  methods: {
    showId(id) {
      alert(id)
    }
  }
  components: {
    appTable: TableComponent
  }
}
</script>
`

**Comment by SerVac** [comment]
@emersoncpaz YOU SAVE MY LIFE! THANK YOU! 👍

**Comment by Aukhan** [comment]
@emersoncpaz thanks man! 
that worked, I think it would be an overkill to create all slots for fields but on the other hand this seems to be the best non-hacky solution.

What we had so far was to override the render and insert `$parent.$scopedSlots` into `this.$scopedSlots`
I know very hacky, but we were able to transport slots from the parent to the wrapper

but @emersoncpaz solution is much better.

**Comment by nardnob** [comment]
In case anyone else ends up here and wants another example.. I answered [a question on StackOverflow](https://stackoverflow.com/questions/51040281/bootstrapvue-table-template-inside-vue-slot/52524710#52524710) with an approach very similar to @Aukhan's. There's also [a jsfiddle](https://jsfiddle.net/nardnob/30295y7e/) for it.

**Comment by Aukhan** [comment]
@mosinve how do we want to take this forward, I think a lot of people do expect to pass slots from the parent/wrapper component. I'd be willing to put in the effort if we have a direction, thanks

**Comment by ChrisCalculus** [comment]
For future reference: I was revisiting this issue after the change to v-slot syntax and found a thread discussing this as well on [SO](https://stackoverflow.com/a/52823029). Perhaps it is of use to anyone.
