### ISSUE TITLE
feat(b-nav-item) Applying Active Class to Outer Element

### ISSUE THREAD

**Issue by ghenry** [bootstrap-vue/bootstrap-vue#1553]
Hi all,

I want the active class to be on the parent li tag (beside nav-item) using:

```
  <b-nav-item router-tag="li" :to="{ name: 'PartnersDashboard' }" title="Manage all your SureVoIP Products and Services">
      <a><i class="fa fa-fw fa-dashboard"></i>
      <span class="nav-text">
        Dashboard</span></a>
   </b-nav-item>
```
but it produces another li tag within the original li tag with the a tag inside that. It's almost there. As per bottom of page:

https://router.vuejs.org/en/api/router-link.html

Thanks.

**Comment by ghenry** [comment]
Mind if I submit a PR for this this week?

**Comment by pi0** [comment]
@ghenry For sure :)

**Comment by ghenry** [comment]
What we're missing is this function:

https://github.com/vuejs/vue-router/blob/dev/src/components/link.js#L125

used here:

https://github.com/vuejs/vue-router/blob/dev/src/components/link.js#L87

What I'm also thinking is to have a boolean prop called **sync-active-class-on** and then when a route is matched it sets the **active** on that parent element like so:

```
  <!-- begin ADVANCED DROPDOWN -->
  <li class="nav-item" title="Advanced users only">
    <b-link class="nav-link nav-link-collapse" v-b-toggle.collapseAdvanced v-on:click="openSidebar">
     <i class="fas fa-fw fa-cogs"></i>
     <span class="nav-text">
       Advanced</span>
    </b-link>
    <b-collapse tag="ul" id="collapseAdvanced" class="sidebar-second-level">
      <li>
        <b-link :to="{ name: 'AdvancedAuditLog' }" title="View Audit logs of all actions">
         <i class="fas fa-fw fa-history"></i>
         <span class="nav-text">
           Audit Log</span>
        </b-link>
      </li>
    </b-collapse>
  </li>
  <!-- end ADVANCED DROPDOWN -->
```

In above, I want the active class applied to the first li element and the outer element of the `<li>` round `b-link` like the router docs say you can. Then when a route is active the menu is automatically opened (not collapsed) and the `active` class is applied to the outer element.

**Comment by ghenry** [comment]
I've been lazy here and just done:

`<li v-bind:class="{ active: $route.name === 'AdvancedAuditLog' }">`

above

`<b-link :to="{ name: 'AdvancedAuditLog' }" title="View Audit logs of all actions">`

I'll be back though.

**Comment by ghenry** [comment]
Will be back to this soon.

**Comment by tmorehouse** [comment]
Actually, I think there is a way to tell vue-router to apply classes to a parent element, although I can't recall offhand how to.

**Comment by Desuuuu** [comment]
The way to do this with vue-router links is documented here: https://router.vuejs.org/api/#applying-active-class-to-outer-element

**Comment by mosinve** [comment]
@tmorehouse here's https://router.vuejs.org/api/#applying-active-class-to-outer-element

**Comment by tmorehouse** [comment]
Yeah, the way it applies to outer elements requires that the outer element to also be a router-link.

This might require some conditional rendering on the outer tag to make it also a router-link (based on the truthyness of `parent.$router` and the `to` prop.
