### ISSUE TITLE
Popover placement not correct

### ISSUE THREAD

**Issue by libre-man** [bootstrap-vue/bootstrap-vue#1556]
The placement of the popovers is not correct, it seems to be slightly off center. See this screenshot taken from the docs:
![](https://attach.libremail.nl/StirnerGoldmanZerzanMost.png).

This happens across multiple browsers, the screenshot was taken with firefix nightly 59.0a1 (2018-01-22) (64-bit).

**Comment by libre-man** [comment]
Is there anymore needed to address this issue?

**Comment by mosinve** [comment]
hi, i've checked in Microsoft Edge 41.16299.15.0 and Chrome 64.0.3282.140. 
It this issue doesn't reproduce.

**Comment by mosinve** [comment]
So, it get lower priority that confirmed issues.
