### ISSUE TITLE
Use object's property as a key in b-table

### ISSUE THREAD

**Issue by gpassero** [bootstrap-vue/bootstrap-vue#1558]
I can't access an object's property in the row of a b-table. E.g. It doesn't work when I set the key of the field as "category.id", but works when I set "category_id" (and this field exists). 

You can see the problem in this brief example: https://jsfiddle.net/gpassero/jjuvpuvp/5/

This issue may probably be regarded as a suggestion for improvement in bootstrap-vue.

I solved the problem by using formatter, but I think should be nice to be able to use "object.property" at headers' key prop.

Windows 10
Chrome 63
Bootstrap-Vue 1.4.0

**Comment by gmmarc** [comment]
@mosinve thanks for fixing this!

However, sorting doesn't work when using object key.

You can see the problem here: https://jsfiddle.net/jjuvpuvp/11/

Testes on v2.0.0-rc.2
