### ISSUE TITLE
Question: how to create dynamic card/accordion?

### ISSUE THREAD

**Issue by jvukovich** [bootstrap-vue/bootstrap-vue#1559]
I would like to render a dynamic list of cards with accordion support. However, I am not sure how to do so.

In this case, how would I make 'accordion1' dynamic (i.e. accordion[number])

Button:
`<b-btn block href="#" v-b-toggle.accordion1>`

Collapse:
`<b-collapse id="accordion1" accordion="my-accordion" role="tabpanel">`

v-for example (how do you make v-b-toggle.accordion dynamic?):
https://pastebin.com/eptwQgff

Thanks!

**Comment by bobcat1** [comment]
`v-b-toggle="'accordion' + id"`

**Comment by jvukovich** [comment]
Perfect! Thanks so much!

**Comment by think2011** [comment]
Where is the doc detail?

**Comment by PavlosIsaris** [comment]
https://bootstrap-vue.js.org/docs/components/collapse#usage

**Comment by ualid** [comment]
I'm with a problem.  The aria-controls stay the same when v-b-toggle is dynamic.
