### ISSUE TITLE
Form-fieldset isn't working in examples

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#156]
https://bootstrap-vue.github.io/docs/components/form-fieldset
https://bootstrap-vue.github.io/docs/components/table

**Comment by mosinve** [comment]
I suppose that root of evil here is self-closed Label, because only it renders.
And again, in components all works as expected.

**Comment by pi0** [comment]
@mosinve Yep! [Here](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/form-fieldset.vue#L3) is the problem :)) Anyway i think `fieldset` needs an (almost) complete rewrite with two considerations : 
 - We can now implement provide/inject mechanism to pass state and variants down to input elements. ( currently it is done using a dirty and single level hack)
- Layout is not working currently in many use cases.

Whats your idea about other changes improvements ?

**Comment by jakobrosenberg** [comment]
I pushed a small fix for the broken labels. I was also wondering if v-html is the best way to go for label html.

**Comment by pi0** [comment]
@mosinve Last night I've pushed some fixes before release :) Can you confirm is it working now?

**Comment by mosinve** [comment]
Yep,  fieldset works well. Confirmed 👍
