### ISSUE TITLE
Using a Dropdown and Button in an Input Group Renders Incorrectly

### ISSUE THREAD

**Issue by xcjs** [bootstrap-vue/bootstrap-vue#1560]
Windows 7 x64 with Google Chrome and Vue 2.0.0-rc.0

The dropdown appears to have rounded corners where it shouldn't.

![2018-01-24 17_57_36-lmi intake](https://user-images.githubusercontent.com/5085205/35361661-27c3fcac-0130-11e8-963f-7015cc083bad.png)

**Comment by xcjs** [comment]
Another example:

![2018-01-24 17_59_52-lmi intake](https://user-images.githubusercontent.com/5085205/35361724-6f7cf724-0130-11e8-8555-0ad50189b7e8.png)

**Comment by pi0** [comment]
Workaround coming soon:

![image](https://user-images.githubusercontent.com/5158436/35406632-b7acd02a-021e-11e8-8455-9f339fdc52fe.png)

**Comment by uginroot** [comment]
![image](https://user-images.githubusercontent.com/2391460/36415836-7a48b284-1651-11e8-8702-df58d336dda6.png)
