### ISSUE TITLE
Checkbox does not work inside b-form-group

### ISSUE THREAD

**Issue by amgravem** [bootstrap-vue/bootstrap-vue#1561]
After upgrade to bootstrap-vue 2.0.0-rc.0, my checkboxes are no longer working. I am able to check it using the keyboard, but not by using the mouse.
Checkboxes do work inside a div, but not inside a b-form-group. 
See https://jsfiddle.net/amgravem/wpnayxzk/9/

I'm using:
Windows 10
Chrome  63.0.3239.132
bootstrap: 4.0.0
bootstrap-vue: 2.0.0-rc.0
vue: 2.5.2

**Comment by pi0** [comment]
Hi. This problem is happening only when `label-for` refers to a data key. renaming `label-for` and `id` resolves the problem. Will investigate more if we can do anything for this.

Working version: https://jsfiddle.net/pi0/wpnayxzk/10

**Comment by amgravem** [comment]
Aha, thank you!
