### ISSUE TITLE
Table stacked is using "default" breakpoints

### ISSUE THREAD

**Issue by KonradDeskiewicz** [bootstrap-vue/bootstrap-vue#1562]
When table is used with `stacked="breakpoint"` it change appearance at default Bootstrap breakpoint, ignoring user-defined breakpoints. 

My `"lg"` breakpoint is defined as `1024px` but table still is stacking at `992px`

**Comment by tmorehouse** [comment]
You could copy the `/src/components/table/table.css` and alter the breakpoints settings, and then include it after you include `bootstrap-vue.css`

We are looking into a way to make the custom CSS uses Sass/scss files, which would allow bootstrap custom variables to be used.
