### ISSUE TITLE
Floating labels (experiments)

### ISSUE THREAD

**Issue by ghenry** [bootstrap-vue/bootstrap-vue#1564]
Hi all,

What's the method or plans to access https://getbootstrap.com/docs/4.0/examples/floating-labels/ 

Thanks.

**Comment by pi0** [comment]
Hey! Thanks for the link. Actually, this example is using some custom styles which we cannot ship in core components. But we can make an extra components in BV to provide same functionality :)

**Comment by ghenry** [comment]
Brilliant! Anything I can do?

On 25 Jan 2018 19:33, "Pooya Parsa" <notifications@github.com> wrote:

Hey! Thanks for the link. Actually, this example is using some custom
styles which we cannot ship in core components. But we can make an extra
components in BV to provide same functionality :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bootstrap-vue/bootstrap-vue/issues/1564#issuecomment-360574972>,
or mute the thread

**Comment by ghenry** [comment]
Hi,

Can you show me some explains so I can may be help?

Thanks.

**Comment by ghenry** [comment]
Hi all,

Is there another example of an extra component I can reference for this contribution?

Thanks.

**Comment by ghenry** [comment]
Any pointers?

**Comment by ghenry** [comment]
Happy to help! Thanks.

**Comment by jackmu95** [comment]
@tmorehouse I think this is a bit out of scope. Or something for a example section in the docs...

**Comment by tmorehouse** [comment]
Yeah...  I was thinking about an examples section under reference or misc... kind of like a cookbook maybe.

**Comment by ghenry** [comment]
Shame.

**Comment by iBobik** [comment]
Have anyone found a good solution how to do this?
