### ISSUE TITLE
<b-modal> custom attribute not transmitted

### ISSUE THREAD

**Issue by drzraf** [bootstrap-vue/bootstrap-vue#1567]
Using this markup:
`<b-modal v-model="show" :id="'modal' + id" :data-ent-id="id">`

the output is:
```
<div data-ent-id="21979"><!----></div>
<div role="region" aria-busy="false" class="carousel slide" id="__BVID__151_" style="background: rgb(171, 171, 171); position: relative; text-shadow: rgb(51, 51, 51) 1px 1px 2px;">
...
</div>
```

I would expect `data-ent-id` to be set to the main `.slide.carousel` div.

**Comment by mosinve** [comment]
are you sure, that u want to talk about b-modal, and not b-carousel?

**Comment by drzraf** [comment]
I'm sorry, I can't reproduce my original issue. Closing for the moment. Sorry for the noise.
