### ISSUE TITLE
How to test documentation changes during editing?

### ISSUE THREAD

**Issue by SirLamer** [bootstrap-vue/bootstrap-vue#157]
I see there was a major rewrite to docs a few hours ago.

I can't figure out how to affect changes to the documents? I have been trying to edit demo.js and demo.html with "yarn run docs-dev" running but I am not see changes. Any tips?

**Comment by pi0** [comment]
Hey @SirLamer :) Yes i have spend many hours finding out best practices writing docs. The most major changes are : 
- Component doc pages can now be easily extended using simple markdown and we can now add complete details about each component. (docs/components/{alert,...}/README.md) 

- Code snippets are now being served on JSFiddle just like standard Vue.js docs :) This has helped us testing each component independently and finding bugs we have not noticed before that ( like #156 #151 ) examples directory is just a snapshot of that fiddles for now until jsfiddle allows us directly [embedding](http://jsfiddle.net/gh/get/library/pure/bootstrap-vue/bootstrap-vue/tree/master/examples/buttons) GitHub files (I've opened an issue) so if you want to test your changes on latest release you can fork one of them ,test code and commit working version to `examples`. 

- For development and easier testing, I've written a playground with BootstrapVue components ready. if you run docs locally and wring your code there changes to components will be automatically hot reloaded. (Caution: copy your code before reloading page! changes will be cleared :D I had no time implementing web-storage for playground yet)
I tried to document it at end of README but as always i'm weak at writing so please feel free to complete that section with better instructions.

BTW what's your idea about changes? Should we fallback to older docs or playground will help ?

**Comment by SirLamer** [comment]
Overall the changes are a good plan, I think more flexibility in the docs is good.

The playground concept is GREAT, I am using it to troubleshoot, well done.

**Comment by SirLamer** [comment]
By the way, I haven't figured out how to test docs development. I suspect that the dev environment is just loading the published JSfiddle page.

**Comment by pi0** [comment]
@SirLamer  About the example part, yep you are true. until js fiddle implements our requested feature then we can use examples folder directly. (if you want to change example, simply fork js fiddle and edit meta.js file with new fiddle id) but consider that examples are using latest released version not dev. (here is why playground was needed) Other parts of doc can be edition by changing README.md files in docs/components/{foobar}
