### ISSUE TITLE
unknown <b-input-group-button>

### ISSUE THREAD

**Issue by rubat** [bootstrap-vue/bootstrap-vue#1570]
Using `<b-input-group-button>`(from https://bootstrap-vue.js.org/docs/components/table#complete-example) output an `Unknown custom element`.

I'm imported `bootstrap-vue/nuxt` in the modules section of nuxt.conf (`modules: ['bootstrap-vue/nuxt']`).

Dependencies: 
    "bootstrap: "^4.0.0",
    "bootstrap-vue": "^2.0.0-rc.1",
    "nuxt": "^1.0.0",

**Comment by voidm4p** [comment]
Same thing here: 
![image](https://user-images.githubusercontent.com/33087100/35686100-c40d7552-076b-11e8-822e-ea5f58d2afca.png)

**Comment by robcresswell** [comment]
`<b-input-group-button>` removed during the 2.x release candidate of Bootstrap-Vue. See the [changelog](https://bootstrap-vue.js.org/docs/misc/changelog). The table example is just out of date. Take a look at https://bootstrap-vue.js.org/docs/components/input-group to see how the input groups are done now.

**Comment by robcresswell** [comment]
This should probably be left open: it's a valid issue that needs to be fixed in the docs. I was just leaving a comment to explain how you can proceed.
