### ISSUE TITLE
ability to keep b-dropdown opened when an item is clicked

### ISSUE THREAD

**Issue by drzraf** [bootstrap-vue/bootstrap-vue#1571]
Because #1569, I'm using such a markup:
```html
<b-button-group>
  <b-dropdown>
     <b-dropdown-item><b-button>Blah</b-button></b-dropdown-item>
     <b-dropdown-item><b-button>Foo</b-button></b-dropdown-item>
   </b-dropdown>
</b-button-group>
```

But I can't think of a way to keep `<b-dropdown>` opened after clicking one of the items.

**Comment by fdabek1** [comment]
I am also facing this same issue.  As per the standard way to do this in Javascript, I tried to do add an event:

`@click.stop`

or

`@click.prevent`

But that does not work.  This would be very helpful to allow people to select multiple items.

**Comment by tomlankhorst** [comment]
As a workaround, I'm replacing `<b-dropdown-item>` component with a plain anchor with event listener that stops propagation (`<a class="dropdown-item" @click.stop="doStuff" href="#">Do</a>`).

**Comment by fdabek1** [comment]
That is a good workaround for now.  It would obviously be nice to have a built in option, but thanks for this!

**Comment by marioamg03** [comment]
> As a temporary workaround, I'm replacing `<b-dropdown-item>` component with a plain anchor with event listener that stops propagation (`<a class="dropdown-item" @click.stop="doStuff" href="#">Do</a>`).

-> this solution worked for me, thanks 💪

**Comment by tmorehouse** [comment]
Use the `b-dropdown-form` or `b-dropdown-text` sub-components, as they do not trigger the menu to close.

See https://bootstrap-vue.js.org/docs/components/dropdown#dropdown-supported-sub-components

**Comment by omarjebari** [comment]
Use @click.native.capture.stop, eg:

<b-dropdown-item @click.native.capture.stop>text</b-dropdown-item>
