### ISSUE TITLE
Issues with Bootstrap-vue/webpack

### ISSUE THREAD

**Issue by spesvictus** [bootstrap-vue/bootstrap-vue#1573]
vue init bootstrap-vue/webpack  is not downloading the boilerplate. It doesn't work on Windows or Linux.  Git is installed on both. vue init bootstrap-vue/webpack-simple however does work.

**Comment by Anuga** [comment]
Have the same problem, didn't realize it until I checked the node_modules, `bootstrap-vue` doesn't even get installed.

It just installs Vue's own Webpack package.

**Comment by spesvictus** [comment]
Yeah happened to me too
