### ISSUE TITLE
Only require core-js, not babel-polyfill?

### ISSUE THREAD

**Issue by Arithmomaniac** [bootstrap-vue/bootstrap-vue#1574]
The [documentation](https://bootstrap-vue.js.org/docs) says
> You'll need babel-polyfill for BootstrapVue to work properly.

But [this comment](https://github.com/bootstrap-vue/bootstrap-vue/issues/228#issuecomment-293704022) suggests that the source is already compiled down to ES5, so we don't need babel-polyfill's runtime, only the [core-js polyfills](https://github.com/zloirock/core-js). This would save 20K from the dependency.

Even nicer would be to specify which core-js modules are necessary, so that people could choose to only include those in their custom core-js builds.

**Comment by mosinve** [comment]
There's much water has flowed since this comment, i'd recommend to follow docs as first source of truth ;)

**Comment by mosinve** [comment]
Closed due to inactivity. 
Feel free to open if needed.
