### ISSUE TITLE
Add table row with b-form-input element on click

### ISSUE THREAD

**Issue by UtkarshMishr** [bootstrap-vue/bootstrap-vue#1576]
Hi,

I have been trying to add a Table row with input text field dynamically when someone click on Add-Row button.

I can achieve this using Jquery and simple <input> element, but when it try to use <b-form-input> it is not working.

Is this a limitation, or am in missing some thing.

**Comment by mosinve** [comment]
Hi, @UtkarshMishr! 
My view of your task: 
1. As `b-table` shows contents of provided items array, to add additional row, you should add an item to this array
2. to show an input element in empty row, you should use scoped slot templates for columns, where you will check an empty value and draw an input if true.

**Comment by Diaskhan** [comment]
@UtkarshMishr, @mosinve  its more beeter to do it with dialog form!

The other options is use 
https://jsfiddle.net/wuc61e4c/
This option is use with state called isediting, But its not gona be cute and nice good looking !

**Comment by tmorehouse** [comment]
closing as stale
