### ISSUE TITLE
Dropdowns do not close on tab or shift+tab

### ISSUE THREAD

**Issue by justindmyers** [bootstrap-vue/bootstrap-vue#1577]
In the documentation it specifies that a dropdown should close on `tab` or `shift+tab`. 

The dropdown documentation page itself does not have this functionality. Tabbing simply moves between the dropdown items and it stays open if you tab off of the current dropdown.

To reproduce, click on the first dropdown and hit `shift + tab` in the [documentation](https://bootstrap-vue.js.org/docs/components/dropdown/). The dropdown will stay open.

I assume this is supposed to be default functionality and I don't have to specifically enabled it.

**Comment by justindmyers** [comment]
I did a bit of digging and found the problem. It looks like the tab keycode is missing in:

https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/utils/key-codes.js

I tested it locally and it works after adding it in. If I get some time I'll try to do a PR.

**Comment by Diaskhan** [comment]
justindmyers  could u provide ure fix or some code that the others could fix this bug ?

**Comment by tmorehouse** [comment]
After playing with this, and reviewing the BS V4 docs, I don't think this feature should be implemented for accessibility reason (especially if the dropdown is being used for navigation.
