### ISSUE TITLE
Checkbox on change shows old\previous state\value in a method

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#1578]
Bootstrap-Vue v2.0.0-rc1
Example: https://jsfiddle.net/409n7gmy/

Once checkbox is clicked I expect to get changed value in a method, but instead I receive the previous value. In the example we see, that the value is changed, but in console we see the previous value, ie in UI we see "State: accepted" but in console "not_accepted".

Why the values are unsynchronized? Is it a feature of VueJS or a bug? If this is a feature, is there any workaround, how I can get the changed state\value in a method right after the click on checkbox?

I tried to find anything related to this issue here, in docs and in internet, but no luck.

**Comment by AdrianBathurst** [comment]
Use nextTick() to get correct value...
https://vuejs.org/v2/guide/reactivity.html

Updated sample works: https://jsfiddle.net/409n7gmy/1/

**Comment by mattocchi** [comment]
Use of nextTick() is a good workaround but I think it is not a good solution, because v-on:input work differently, do you agree? It is possible to evaluate two distincts events, something like "beforeChange" and "changed"?

**Comment by mattocchi** [comment]
Checkbox on input shows new\actual state in a method
