### ISSUE TITLE
Custom classes on the table tag

### ISSUE THREAD

**Issue by mkudenko** [bootstrap-vue/bootstrap-vue#1579]
Hi there,

The `b-table` component works great, but I can't figure out how to add custom classes directly to the `table` tag.

Here's my template code:
```
<template>
    <div>
        <div class="form-group row">
            <div class="col-md-1">
                <input class="form-control"
                       v-model.trim="id"
                       placeholder="ID"
                       type="text"
                       autocomplete="off">
            </div>
            <div class="col-md-4">
                <input class="form-control"
                       v-model.trim="search"
                       placeholder="Email, First Name, Last Name"
                       type="text"
                       autocomplete="off">
            </div>
        </div>
        <b-table ref="table"
                 striped
                 show-empty
                 hover
                 responsive
                 :items="fetchUsers"
                 :busy="isBusy"
                 :current-page="currentPage"
                 :per-page="perPage"
                 :sort-by.sync="sortBy"
                 :sort-desc.sync="sortDesc"
                 :fields="fields">
        </b-table>
    </div>
</template>
```

It generates the following HTML:
![image](https://user-images.githubusercontent.com/2769639/35721010-08cf67b0-0855-11e8-818b-ceec456ef8f0.png)

If I add classes to the `b-table` tag, they appear on the outer div, like this:
![image](https://user-images.githubusercontent.com/2769639/35721161-a58beeac-0855-11e8-8ba1-4df517244b3d.png)
![image](https://user-images.githubusercontent.com/2769639/35721145-8d4c134e-0855-11e8-8fb3-b6e33f026f71.png)

Is there a way to add classes to `<table>`?

Thank you.

**Comment by mosinve** [comment]
Currently it's impossible. As a workaround you can target table by following selector
```css
.custom-class table {
some-prop: value;
}
```

**Comment by mosinve** [comment]
If you remove `responsive` prop, wrapper `div` won't render

**Comment by mkudenko** [comment]
Thank you @mosinve, removing the `responsive` prop did the trick.
