### ISSUE TITLE
Table sort issue regarding numbers

### ISSUE THREAD

**Issue by bjarnik** [bootstrap-vue/bootstrap-vue#158]
The sort in the table component uses String.localeCompare which by default does not use numeric collation resulting in wrongly sorted table data.

I would suggest making this the default functionality by adding the Unicode extension key as well as the option object since it doesn't seem to work without having both set.

So something like this:
```
// Apply Sort
  if (this.sort) {
      items = items.sort((a, b) => {
          const r = fix(a[this.sort]).localeCompare(fix(b[this.sort]), 'kn', { numeric: true });
          return this.sortDesc ? r : r * -1;
      });
}
```

Is it possible that I'm missing something and that it's possible to achieve this in the current version without modifying the source code?

**Comment by pi0** [comment]
Hey @bjarnik Thanks for your suggestion. Now with 0.10.1 many parts of table component can be customized using props. Besides of that numeric sorting is also fixed :)
