### ISSUE TITLE
Tooltip directives for delay show and delay hide

### ISSUE THREAD

**Issue by snuuve** [bootstrap-vue/bootstrap-vue#1580]
Would be nice if there will be two another directives, on for `delay.show` and one for `delay.hide`.
Maybe `ds###` and `dh###`.

**Comment by tmorehouse** [comment]
You can actually pass a config object to v-b-tooltip that specified the show and hide delays:

```html
<b-button v-b-tooltip.hover.top="{ delay: { show: 50, hide: 1000 } }" title="tooltip">button</b-button>
```

This will delay the showing by 50ms and the hiding by 1000ms.

See working example at https://jsfiddle.net/thrwejaz/
