### ISSUE TITLE
How can I set a dynamic class over a row?

### ISSUE THREAD

**Issue by Pulstarter** [bootstrap-vue/bootstrap-vue#1581]
Hi! 

I have the latest version and I wonder to know how can I get access to the row slot to apply a class when it’s been clicked based on rows id.

Something like <template slot=“row-group” :class=“{active : activeClass == row.id}”>

It is possible to archieve this? Any suggestions if not?

Best regards

**Comment by SmevSmevson** [comment]
You could use `_rowVariant` to add your own dynamic class to a row.
Your css class will have to start with `.table-` to work with `_rowVariant`.
You could then loop through the table records on a `row-click` event setting `_rowVariant`.

```
onRowClick(record) {
            for (var i = 0; i < this.items.length; i++) {
                this.items[i]._rowVariant="";
            }
            record._rowVariant="active";
}
```
```
.table-active {
    background-color: green;
}
```

**Comment by Diaskhan** [comment]
Pulstarter solution that offered SmevSmevson satisfied u ? 
If yes u could close issue ! Otherwise could u show all code! To make it clear ?

**Comment by Pulstarter** [comment]
The solution fit my needs, thanks!
