### ISSUE TITLE
Docs on the site

### ISSUE THREAD

**Issue by brunokunace** [bootstrap-vue/bootstrap-vue#1584]
Hi peoples,  i try to learn about yours componentes, but,  the Events describles on the site not equals to github source. 

Alert component for example,  have 2 events with not have on source file on github. 

Have a lazy on update docs or i not see right?  

I try to help with pr's,  if need. 

Thanks.

**Comment by mosinve** [comment]
Hi ;) Thx for findings :) BTW, help is very appreciated :)

**Comment by brunokunace** [comment]
ok, thanks, but "Component Reference" not on Readme.md files, how to help you with this?

**Comment by mosinve** [comment]
Events info compiles from component's package.json.
About `Alert` component - doc says that it has 2 events, and it really has them. 
`dismissed` event - https://github.com/bootstrap-vue/bootstrap-vue/blob/5b7ee09cb494b4c243929d8fbc28976e8330b420/src/components/alert/alert.js#L80
`dismiss-count-down` event - https://github.com/bootstrap-vue/bootstrap-vue/blob/5b7ee09cb494b4c243929d8fbc28976e8330b420/src/components/alert/alert.js#L112

**Comment by brunokunace** [comment]
👍
