### ISSUE TITLE
Form Select does not respond to external prop changes

### ISSUE THREAD

**Issue by fdlk** [bootstrap-vue/bootstrap-vue#159]
See JSFiddle https://jsfiddle.net/2rcvtv3t/2/

Select option `b` in any of the selects.
As expected, and as can be seen in the bottom label, the parent's `selected` property will get updated from `a` to `b`.

*But* the bootstrap-vue Form Selects only switch to `b` if they, themselves, are used to select the `b`.
If a different control is used to do the update, a bootstrap-vue Form Select will still stubbornly show the old option `a`.

I think this happens cause they internally have their own `localValue` data property. In controlled mode, where the `value` prop is set, they should prefer the `value` prop to the `localValue` data property.

I tried switching the Form Select from `v-model="selected"` to `:value="selected"` and `@input="setSelected"` where `setSelected` updates the selection. Doesn't make a difference, both versions show the same bug.

**Comment by pi0** [comment]
Thanks @fdlk for reporting :) Fix was done. Will be released on `0.10.1` soon :)

**Comment by pi0** [comment]
Done!
