### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by hdarmet** [bootstrap-vue/bootstrap-vue#1590]
In "table" component, there is a reference to $attrs attribute (there is only one in whole Bootstrap Vue) that is causing Vue to crash (undefined !). I just removed this reference and things did go fine thereafter. 

current code snippet:

            var table = h('table', {
                class: t.tableClasses,
                attrs: {
                    id: t.safeId(),
                    role: t.isStacked ? 'table' : null,
                    'aria-busy': t.computedBusy ? 'true' : 'false',
                    'aria-colcount': String(fields.length),
                    'aria-rowcount': t.$attrs['aria-rowcount'] || t.perPage && t.perPage > 0 ? '-1' : null
                }
            }, [caption, colgroup, thead, tfoot, tbody]);

fix:

            var table = h('table', {
                class: t.tableClasses,
                attrs: {
                    id: t.safeId(),
                    role: t.isStacked ? 'table' : null,
                    'aria-busy': t.computedBusy ? 'true' : 'false',
                    'aria-colcount': String(fields.length),
                    'aria-rowcount': /*t.$attrs['aria-rowcount'] ||*/ t.perPage && t.perPage > 0 ? '-1' : null
                }
            }, [caption, colgroup, thead, tfoot, tbody]);

**Comment by mosinve** [comment]
Can you show the error, which is the reason on this issue? 
I don't see any errors in console on documents site.

**Comment by mosinve** [comment]
t.$attrs['aria-rowcount'] is used following usecase:
```html
<b-table show-empty
             aria-rowcount="5"
             :items="items"
             :fields="fields"
             :current-page="currentPage"
             :per-page="perPage"
    >
```
this renders to something like that:

```html
<table id="__BVID__332" role="table" aria-busy="false" aria-colcount="4" aria-rowcount="5" class="table b-table>
.....
</table>
```

with your fix `aria-rowcount` always will be assinged either `-1` or `null`

https://www.w3.org/TR/wai-aria-1.1/#aria-rowcount

**Comment by hdarmet** [comment]
Here is a screenshot.
 I use the CDN URL.

[image: Images intégrées 1]

2018-02-04 16:50 GMT+01:00 Vitaly Mosin <notifications@github.com>:

**Comment by hdarmet** [comment]
In fact, $attrs is not defined in my case.
