### ISSUE TITLE
How to add a css file in Nuxtjs

### ISSUE THREAD

**Issue by duythang** [bootstrap-vue/bootstrap-vue#1592]
Hello
I am using bootstrap-vue inside NuxtJS
As mentioned in Getting Started of Bootstrap-Vue, we can custom CSS as follows in nuxt.config.js.

```
{
  modules: [
    'bootstrap-vue/nuxt',

    // Or if you have custom bootstrap CSS...
    ['bootstrap-vue/nuxt', { css: false }],
  ]
}
```
I am confusing how to add a css file to custom bootstrap.

Thank you for your help

**Comment by mosinve** [comment]
This means, that you can use custom css based on Bootstrap's classnames instead of original Bootstrap

**Comment by duythang** [comment]
@mosinve Thank you for your response. 
How can i add a custom css file which is based on Bootstrap's classnames instead of original Bootstrap ? 
In this case, should i configure like this ? 
```{
  modules: [
    'bootstrap-vue/nuxt',

    // Or if you have custom bootstrap CSS...
    ['bootstrap-vue/nuxt', { css: **true**}],
  ]
}```

**Comment by mosinve** [comment]
`['bootstrap-vue/nuxt', { css: false }],` - this string tells Nuxt to not load original css
to load custom you should add this to `nuxt.config.js`
```js
modules: [   
    ['bootstrap-vue/nuxt', { css: false }]
  ]
```
and read this https://nuxtjs.org/api/configuration-css/

**Comment by duythang** [comment]
@mosinve Thank you so much. I got it :)
