### ISSUE TITLE
Inline code snippets not complete enough

### ISSUE THREAD

**Issue by paul-hammant** [bootstrap-vue/bootstrap-vue#1596]
Page: https://bootstrap-vue.js.org/docs/components/form-input - the "Input type" (there's no anchor direct to that).

I'm getting ..

```
[Vue warn]: Property or method "checkbox" is not defined on the instance but referenced 
during render. Make sure that this property is reactive, either in the data option, or for 
class-based components, by initializing the property. See: 
https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```
.. as I attempt to use statically with a pre-existing page (no cli, no build).  I mean something that was working fine statically with vue before, and I just wanted to transition to bootstrap-vue.

If there was a codepen or fiddle that showed the same form as standalone, then I'd not be lost right now and abandoning a commit.  The inline forms are great to see the outcome, but there should really be a click through to "view in Codepen" (or equiv) for the least extraneous HTML/CSS/JS versions of the example.  Right now if I attempt to do view source https://bootstrap-vue.js.org/docs/components/form-input there's 10x more code than the example I'm wanting to learn, with plenty of extraneous line. The Double-click-to-edit 'live' thing is also impressive but unhelpful when I wanted to see **all** the HTML/etc for the tightest possible demo of the control in question.

**Comment by mosinve** [comment]
https://jsfiddle.net/cihkem/8k0skxdr/

**Comment by paul-hammant** [comment]
Thank you - I'm playing with it to make a reproduction ....

**Comment by robcresswell** [comment]
Can we close this, or did you need any further help?

**Comment by paul-hammant** [comment]
Checking how far I got in my app - will report back
