### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by krbaio3** [bootstrap-vue/bootstrap-vue#1597]
Hi,
I have updated my scaffold to Typescript with vue-cli-3.0.0-alpha.8. I am going to migrate my proyect, and I have problems because when I import BootstrapVue in main.ts, It shows me the error that the d.ts are missing

**Comment by pi0** [comment]
Baic typings are available now: https://github.com/bootstrap-vue/bootstrap-vue/pull/1721
