### ISSUE TITLE
Navbar doesn’t display links inline without toggleable / b-collapse

### ISSUE THREAD

**Issue by GeoffreyBooth** [bootstrap-vue/bootstrap-vue#1598]
Try taking the examples in https://bootstrap-vue.js.org/docs/components/navbar and removing `toggleable` and `b-collapse`. You’ll get output like this:

![image](https://user-images.githubusercontent.com/456802/35942505-b3216836-0c0a-11e8-831a-5a62fa1ac590.png)

Minimal case:
```vue
<b-navbar type="dark" variant="info">

  <b-navbar-nav>
    <b-nav-item href="#">Link 1</b-nav-item>
    <b-nav-item href="#">Link 2</b-nav-item>
    <b-nav-item href="#">Link 3</b-nav-item>
  </b-navbar-nav>

</b-navbar>
```
![image](https://user-images.githubusercontent.com/456802/35942630-2557b054-0c0b-11e8-92c3-0bcb4995968f.png)

Versus:
```vue
<b-navbar toggleable="md" type="dark" variant="info">

  <b-collapse is-nav id="nav_collapse">

    <b-navbar-nav>
      <b-nav-item href="#">Link 1</b-nav-item>
      <b-nav-item href="#">Link 2</b-nav-item>
      <b-nav-item href="#">Link 3</b-nav-item>
    </b-navbar-nav>

  </b-collapse>

</b-navbar>
```
![image](https://user-images.githubusercontent.com/456802/35942790-c80a8f1a-0c0b-11e8-92b7-0bc361f8fa1b.png)

Related to this, the class `.dropdown-menu-right` seem to be explicitly defined under `.navbar-expand-md` and its siblings, so that without `collapse` (which adds `navbar-expand-md`) all `b-nav-item-dropdown`s are left-aligned even with the `right` property.

**Comment by tmorehouse** [comment]
This is the fun with bootstrap V4 CSS... similar issues are present when using native bootstrap V4 markup and JS.

Try adding in some wrapper elements and bootstrap utility classes to align items.
