### ISSUE TITLE
Modal footer/header slots not being replaced?

### ISSUE THREAD

**Issue by hlohrenz** [bootstrap-vue/bootstrap-vue#1599]
This is the markup I have for my bootstrap modal:

```html
<!-- Manage item attributes modal -->
<b-modal id="attributes-modal" size="lg" title="Manage Attributes" ref="attributes-modal" :attributes="attributes">
    <form id="update-attributes-form" action="#" method="post">
        <ul class="list-group list-group-flush">
            <li class="list-group-item flex-column align-items-start" v-for="attribute in attributes">
                <div class="d-flex justify-content-between">
                    <h6 class="mb-1">@{{ attribute.display_name }}</h6>
                    <a href="#" class="text-muted"><i class="far fa-times"></i></a>
                </div>
                <p class="mb-0">Attribute value: @{{ attribute.pivot.attribute_value }}</p>
            </li>
            <li class="list-group-item pt-4">
                <h5>Add New Attribute</h5>
                <div class="row">
                    <div class="col">
                        <select name="attribute_id" id="attribute_id" class="form-control">
                            <option v-for="attr in all_attributes" :value="attr.id">@{{ attr.display_name }}</option>
                        </select>
                    </div>
                    <div class="col">
                        <input name="attribute_value" id="attribute_value" class="form-control" placeholder="Attribute value" />
                    </div>
                </div>
            </li>
        </ul>
        <input type="hidden" name="item_id" id="item_id" />

        <div slot="modal-footer">
            <b-btn variant="link">Cancel</b-btn>
            <b-btn variant="primary" @click="addNewAttribute">Save Changes</b-btn>
        </div>
    </form>
</b-modal>
```

However, putting `<div slot="modal-footer">` doesn't replace the default footer in this component. I'm getting the original modal-footer with this markup on top of it (it's not being converted or anything.

![image](https://user-images.githubusercontent.com/34523008/35949152-1184c606-0c3e-11e8-90de-0e5a956aba22.png)

Any reason why it's doing this? Am I doing this wrong? I looked at a lot of other issues on here and I saw in the examples that everybody was using it this way and it seemed to have worked for them just fine.

**Comment by robcresswell** [comment]
I think it's because your form element, which is in the default slot, is wrapping that modal-footer slot.

Also in the future; please read the bug report content and provide things like version information and a repeatable example in a codependent or some similar site. It makes it much easier for us to debug and help you.

**Comment by robcresswell** [comment]
Does this still need further work, or can it be closed?

**Comment by hlohrenz** [comment]
@robcresswell that was it :) I moved the footer outside of the form element and it worked as intended. Thank you so much!

**Comment by alirizaadiyahsi** [comment]
@hlohrenz, could you share working code?
