### ISSUE TITLE
Custom data in Modal

### ISSUE THREAD

**Issue by gabrielbuzziv** [bootstrap-vue/bootstrap-vue#16]
I think the way you design the modal is not the best since i can't manage the content in a custom way.

e.g. if i want a form and the body and footer between then, its not possible.

**Comment by pi0** [comment]
@gabrielbuzziv That is what exactly `named slots` do (and modals have named slots)
Please read more [here](https://vuejs.org/guide/components.html#Named-Slots)

**Comment by gabrielbuzziv** [comment]
@pi0 so i need to modify the Modal component ?

**Comment by pi0** [comment]
No :) Just inset you components inside appreciate place holders.
Check out [This example](https://bootstrap-vue.github.io#usage-21). 
You can simply wrap that `<b-modal>` Component with your form and adding your controls inside 3 different segments ...

**Comment by gabrielbuzziv** [comment]
Got it.
