### ISSUE TITLE
bNavItem is not importing bLink as a dependent component

### ISSUE THREAD

**Issue by tsneed290** [bootstrap-vue/bootstrap-vue#160]
As of 0.10.0-rc.1, I am able to import components individually by importing from 'boostrap-vue/lib/components':
```

import { bNavbar, bNav, bNavToggle, bCollapse, bNavItem } from 'bootstrap-vue/lib/components'

export default {
  name: 'app',
  components: { bNavbar, bNav, bNavToggle, bCollapse, bNavItem }
}
```

Though, when I run the application I see the following error:

> [Vue warn]: Unknown custom element: <b-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 

It appears that bNavItem is not defining bLink as a dependent component.

**Comment by pi0** [comment]
@tsneed290 I strongly suggest you using new `es` builds. Tree shaking is now supported for both webpack2 and rollup and will make optimizations automatically. Anyway if REALLY need this feature i can add dep for this special case :)

**Comment by tsneed290** [comment]
Ah, no worries. Maybe it's a non-issue for me. I started writing some unit tests for a local project and  found that bootstrap-vue wasn't loaded. I loaded bootstrap-vue once as part of my "main.js" bootstrap file. Should I simply being using `Vue.use(BootstrapVue)` within each component that makes use of a Vue component?

**Comment by pi0** [comment]
@tsneed290 I think we have to add Vue.use on specs main file as besides of components now we have some directives. Anyway i didn't started writing tests (yet) so have not exact idea about challenges :)) 
Closing this in flavor #161 so of  we can keep track of unit tests in a single place :)

**Comment by mosinve** [comment]
sorry for reopen. I'll try to answer.
@tsneed290 To use bootstrap-vue components you need to use `Vue.use(BootstrapVue)` only once in main.js. 
I currently writting a project heavily using bootstrap-vue library. Feel free to check it, maybe it will be usefull somehow [https://github.com/mosinve/reestrius_spa](https://github.com/mosinve/reestrius_spa)

**Comment by tsneed290** [comment]
Thanks @mosinve, I was looking for a solution on how to load bootstrap-vue in the context of testing an individual Vue component without loading the bootstrap "main.js" module.
