### ISSUE TITLE
Dropdown should only change focus when using the keyboard

### ISSUE THREAD

**Issue by justindmyers** [bootstrap-vue/bootstrap-vue#1601]
There's no W3 requirement to mix keyboard/mouse behavior for focus. Even the W3 examples do not show any behavior where mouse interaction changes the focus to the first item or that hover causes a focus change. This is an especially strange behavior considering no other component changes focus on hover.

In addition, it also makes it impossible to style a dropdown correctly as there's now no distinction between hover and focus states on the dropdown items.

React Bootstrap had this same discussion and came to a different conclusion than how bootstrap-vue handles the interaction.  Keyboard accessibility is still functional and mouse functionality works properly with separate focus and hover states.

At worst, an option to disable the hover focus/focus click should exist so that the user can decide if they want this feature as it's not an accessibility requirement.

https://github.com/react-bootstrap/react-bootstrap/issues/1233

**Comment by tdbear** [comment]
I was about to report it when I found this one. Indeed, the focus rect on menu items when hovering mouse over them looks **very** strange. Hovering is not supposed to change focus. This is also not what BS 4.0.0 does.

**Comment by Diaskhan** [comment]
justindmyers
Could u show gifs of prefferable behaviour? 
It,s or provide some screenshot ? 
There are more chances to fix this when information fully !
