### ISSUE TITLE
documentation doesn't mention we should import css for webpack

### ISSUE THREAD

**Issue by akarelas** [bootstrap-vue/bootstrap-vue#1603]
See page https://bootstrap-vue.js.org/docs/

Nowhere does it say that we should also write these lines:

`import 'bootstrap/dist/css/bootstrap.css';`

and also maybe

`import 'bootstrap-vue/dist/bootstrap-vue.css'`

How should we figure that out?

**Comment by mosinve** [comment]
Mentioned info will be in the next library release

**Comment by TheAndroidGuy** [comment]
@mosinve Why it was not included in the first place?

**Comment by mosinve** [comment]
It was, but someone deleted it. OSS, you know ...
