### ISSUE TITLE
input with @keyup.enter not working inside b-table

### ISSUE THREAD

**Issue by purvishah165** [bootstrap-vue/bootstrap-vue#1609]
How to implement the above functionality?
I have an input tag inside b-table and I need to call a method on pressing enter key.
 <b-table ref="member_table" :show-empty=true :fields="fields" :items="getMembers" :no-provider-sorting=true>
 <template slot="member_name" scope="data">     
<input class="form-control" v-model="data.item.member_name" @keyup.enter.stop="searchMemberName(data.item,data.index)">
</template>
</b-table>
I tried this but it is not calling the method.
Can anyone tell me how to achieve this?

**Comment by mosinve** [comment]
Hi, @purvishah165.
Please provide an example of your code.

**Comment by mosinve** [comment]
@purvishah165 please, checkout this https://jsfiddle.net/cihkem/2t3u7w6d/

**Comment by RockyF** [comment]
@mosinve 
if you change <input> to <b-form-input>, you demo doesn't work any more.

**Comment by emanuelmutschlechner** [comment]
@RockyF If you change `<input>` to `<b-form-input>` you must add the `.native` modifier to the `@keyup` event, as it is not a BootstrapVue component event

https://jsfiddle.net/sy2yb1ck/
