### ISSUE TITLE
vue init bootstrap-vue/webpack my-project        was not generated a right project

### ISSUE THREAD

**Issue by kuzhi1900** [bootstrap-vue/bootstrap-vue#1610]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/bootstrap-vue/bootstrap-vue/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/CONTRIBUTING.md)

When asking general "how to" questions:

- Please avoid opening an issue here
- Instead, ask for help on StackOverflow, IRC, or [Slack](https://bootstrap-vue.now.sh/), and also check out the [online documentation](https://bootstrap-vue.js.org)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Version of Bootstrap-Vue that you are using
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/), [JS Bin](https://jsbin.com/), or [JsFiddle](https://jsfiddle.net/) (You can export markup from the [online playground](https://bootstrap-vue.js.org/play) to JS Fiddle)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

Love bootstrap-vue? Please consider supporting our collective:
👉  https://opencollective.com/bootstrap-vue/donate

**Comment by pi0** [comment]
More details needed. Please recreate a new issue.
