### ISSUE TITLE
Compatibility with Rollup

### ISSUE THREAD

**Issue by rbrtmrtn** [bootstrap-vue/bootstrap-vue#1611]
First of all, this is an awesome project and thanks for everyone's work on it! I just wanted to give some general feedback on my experience trying to use BootstrapVue with Rollup, in the hopes that it might spark a discussion on how to the two could work together more easily.

The main issue I ran into was that: Rollup requires you to declare "external" modules, where the config would look something like:

```
// rollup.conf.js

export default {
  input: 'src/index.js',
  output: {
      file: 'dist/bundle.js',
  },
  external: [
    'bootstrap-vue',  // <-- this is the important part
  ],
};
```

The problem is that when I import a single component, for example:

    import bModal from 'bootstrap-vue/es/components/modal/modal';

Rollup throws a warning that it doesn't know how to resolve `bootstrap-vue/es/components/modal/modal` and suggests adding it to `external` in the Rollup config. It's just a warning, but I found that it led to some unpredictable behavior with Rollup's file-watching functionality. (Rollup would start up fine, but as soon as I made change to one of my files, it threw an error that `bootstrap-vue` could not be found, perhaps similar or related to rollup/rollup-watch#4.)

As a more general comment, the way things are imported in BootstrapVue, i.e. having to go several layers deep in submodules, feels a little verbose IMHO. Why not expose them directly from the main module like:

    import { bModal } from 'bootstrap-vue';

? Or maybe that exists already and I just missed it?

In any case, I just wanted to share my experience since I think this is an awesome project and makes life with Vue and Bootstrap a lot easier! If there's an easy fix for anything I described above, feel free to let me know too.

Thanks!

**Comment by rbrtmrtn** [comment]
Also, it would be fantastic to have an example in the docs on how to configure Rollup to use BootstrapVue, especially how to import Bootstrap's CSS.

**Comment by robcresswell** [comment]
If you've spent time getting rollup to work, would you consider make a PR? As far as I'm aware there is no huge aversion to specific build tools if we don't have to go out of our way, but webpack is usually the de-facto tool at the moment. I also think it would be worth breaking out your request about imports into a separate issue, as it's unrelated to the heading in this case 😇
