### ISSUE TITLE
Present data structure in b-table not working

### ISSUE THREAD

**Issue by zaqpiotr** [bootstrap-vue/bootstrap-vue#1612]
Hello Everyone!

I'm trying to present data structure in **b-table**.
For example I have:
```

position : {
   price: 200,
   material : {
      name:'My material',
      width:1000
   }
}

```
And I want to show this data from above as 3 separate columns: price, material name, material width.
I was trying to use it with slot like 'material.name' but this is not working.
Adding labels also didn't help.

**b-table** is creating only one column for material. 
How to force it to create two columns?

```

 <template>
                <b-table :fields="fields" :items="position">

                    <template slot="price" slot-scope="data">
                        {{data.value}}                       
                    </template>

                    <template slot="material" slot-scope="data">
                        {{data.value.name}}                       <--- not working
                    </template>

                    <template slot="material" slot-scope="data">
                        {{data.value.width}}                      <--- not working 
                    </template>

                </b-table>
</template>

```

**Comment by mosinve** [comment]
@zaqpiotr, I can offer you this solution https://jsfiddle.net/cihkem/8q5j21eg/

**Comment by mosinve** [comment]
With #1614, in next version it will be possible to define fields as `material.name`
