### ISSUE TITLE
v-b-modal problem with v-if

### ISSUE THREAD

**Issue by dmocho** [bootstrap-vue/bootstrap-vue#1613]
While I am not entirely sure if this is a Bootstrap Vue issue or a pure Vue issue please see the following:

# **Problem:**

When a <b-btn> with a v-b-modal directive is replaced with another <b-btn> without that directive using v-if/v-else in VDOM the effects of the directive are bound also to the second component.

Template code:

```
<div id="app">
  <b-btn @click="doModal = !doModal">Toggle modal</b-btn>

  <b-btn v-b-modal.modal v-if="doModal">Modal</b-btn>

  <b-btn v-else>No modal</b-btn>
  
  <b-modal id="modal">Modal text</b-modal>

</div>
```

JS code:
```
new Vue({
	el: '#app',
  data: {
  	doModal: true,
  }
})
```

Working example: https://jsfiddle.net/fv1mjnfa/7/

# **Current result**

Button named "Modal" triggers modal visibility.
After clicking button named  "Toggle modal" the above button is replaced by button named "No modal".
Clicking button "No modal" also triggers the modal.

# **Expected result**

Button with "No modal" text should not trigger the modal.

**Comment by mosinve** [comment]
I've slightly updated your examle to make it work
https://jsfiddle.net/cihkem/5y2fs62q/
The catch is to add keys to elements, so Vue will treat them as different vnodes.

**Comment by mosinve** [comment]
@dmocho, If you satisfied with the answer, please close the issue

**Comment by dmocho** [comment]
I am satisfied as it solves my case but I strongly believe such "tricks" should not be necessary :)

**Comment by mosinve** [comment]
It's not a trick. It's the way Vue works. Please, read this https://vuejs.org/v2/api/#key

**Comment by mosinve** [comment]
> Without keys, Vue uses an algorithm that minimizes element movement and tries to patch/reuse elements of the same type in-place as much as possible.

**Comment by dmocho** [comment]
Let me give you one more fiddle: https://jsfiddle.net/5y2fs62q/2/
The same thing put on regular buttons works perfectly without any keys.
b-button's without keys with different on-click listeners also work well.

There is something about modal binding to b-button that is not working as expected.

On second thought - this issue should remain open.

**Comment by mosinve** [comment]
As I said earlier, this is the way Vue works, it reuses components Vnode if they haven't `key` attribute, but not for pure HTML elements. 
You should use `key` in this case.

**Comment by dmocho** [comment]
With all respect you ignored the second part of the fiddle where @click was bound to the buttons and it worked.

In https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/directives/modal/modal.js the event listener is bound to the element and never unbound.
And here https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/utils/target.js there is no tracking of bound event listeners so the above can be done.

I allowed myself to play a bit with those two and achieved exactly the thing I was talking about.

1. modal.js

```
import target from '../../utils/target';
import { setAttr } from '../../utils/dom';

var listenTypes = { click: true };

export default {
  // eslint-disable-next-line no-shadow-restricted-names
  bind: function bind(el, binding, vnode) {
    binding.bind = true // <- **this probably not the proper way to do this**
    target(vnode, binding, listenTypes, function (_ref) {
      var targets = _ref.targets,
          vnode = _ref.vnode;

      targets.forEach(function (target) {
        vnode.context.$root.$emit('bv::show::modal', target, vnode.elm);
      });
    });
    if (el.tagName !== 'BUTTON') {
      // If element is not a button, we add `role="button"` for accessibility
      setAttr(el, 'role', 'button');
    }
  },
  unbind (el, binding, vnode) {
    binding.bind = false // <- **this probably not the proper way to do this**
    target(vnode, binding, listenTypes, () => null)
    if (el.tagName !== 'BUTTON') {
      // If element is not a button, we remove `role="button"`
      removeAttr(el, 'role', 'button')
    }
  }
};
```

2. target.js
```
import { keys } from '../utils/object';

var allListenTypes = { hover: true, click: true, focus: true };

export default function targets(vnode, binding, listenTypes, fn) {
  var targets = keys(binding.modifiers || {}).filter(function (t) {
    return !allListenTypes[t];
  });

  if (binding.value) {
    targets.push(binding.value);
  }

  var listener = function listener() {
    fn({ targets: targets, vnode: vnode });
  };

  keys(allListenTypes).forEach(function (type) {
    if (listenTypes[type] || binding.modifiers[type]) {
      if (binding.bind) {
        vnode.elm.addEventListener(type, listener)
        if (!vnode.elm['BV_boundEventListeners'])
          vnode.elm['BV_boundEventListeners'] = {}
        vnode.elm['BV_boundEventListeners'][type] = listener
      } else {
        const boundListener = vnode.elm['BV_boundEventListeners'] && vnode.elm['BV_boundEventListeners'][type]
        if (boundListener) {
          vnode.elm.removeEventListener(type, boundListener)
          delete vnode.elm['BV_boundEventListeners'][type]
        }
      }
    }
  });

  // Return the list of targets
  return targets;
}
```

**Comment by mosinve** [comment]
So, after these changes, your example works as expected?

**Comment by dmocho** [comment]
Yes

**Comment by mosinve** [comment]
Ok, I'll review your proposals a bit later.
