### ISSUE TITLE
Trigger multiple collapse elements dynamically

### ISSUE THREAD

**Issue by SandorZoltanHorvath** [bootstrap-vue/bootstrap-vue#1618]
Hi,

I would like to trigger multiple collapses with the same button.
I can make it work by using the `v-b-toggle.collapseA.collapseB` modifier. However, I need to generate the target ID names dynamically. I would like to do something like this: 
`v-b-toggle="'collapse' + id, collapse' + user.id"` 

I could manage to make it work by using events and another button but I am sure there is a better way. I am fairly new to Vue so any advice is welcome.

Thanks in advance.

**Comment by mosinve** [comment]
Using event's is the best way in your case, I think

**Comment by SandorZoltanHorvath** [comment]
Thank you for your help.
