### ISSUE TITLE
cannot build from repo: bootstrap-vue.css not found

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#162]
Need build local repo in order to test code changes before commit.
Got rollup error 

>  Error: ENOENT: no such file or directory, open 'D:\Dev\bootstrap-vue\dist\bootstrap-vue.css'

@pi0 may be will be better if you add css sources to repo? 
Although, workarounds are to comment css section in rollup.config.js or to get css file from npm repo :)

**Comment by pi0** [comment]
Hey :) Would you please check that dist folder exits ? If not just simply create one in root of project.

**Comment by pi0** [comment]
Also for local change testing if you simply start docs-dev local playground is hot reloading with latest css and vue changes...

**Comment by mosinve** [comment]
whoa! it's just magic! )))) thx :) 
Closing this issue :)
