### ISSUE TITLE
Safari+Chrome, iOS: when tapping on a tooltip, the tooltip is not showing.

### ISSUE THREAD

**Issue by DylanC** [bootstrap-vue/bootstrap-vue#1620]
Working in Samsung Android device and desktop browsers. Does not work in either Safari and Chrome on Apple iPad.

Bootstrap-vue - v2.0.0-rc.1
vue - v2.4.2

**Comment by robcresswell** [comment]
I couldn't recreate this with rc8 and vue 2.5.16. Are you able to reproduce with up to date versions?

**Comment by DylanC** [comment]
@robcresswell - Able to reproduce with vue 2.5.16 and rc11. iPad Air iOS10.

**Comment by robcresswell** [comment]
Ohh, iOS, *not* macOS?

**Comment by DylanC** [comment]
@robcresswell - Yes, iOS. :)

**Comment by DylanC** [comment]
@robcresswell - Just a quick update on the matter. Maybe this info will help you. 

**This works**
```
<th>
<a href="#" v-b-tooltip triggers="hover click" title="My awesome title">Click or tap me</a>
</th>
```

**This does not work**
`<th v-b-tooltip triggers="hover click" title="My awesome title">Click or tap me</th>`

**Comment by justin1364** [comment]
we are seeing this as well

**Comment by tmorehouse** [comment]
this might be related to the ios touch event bubbling issue, which we had to implement for dropdowns (as per B'S v4 native code).

Will habe to determine if we need to add the ugly hack of adding no-op touch event handlers to the document when a popover is present in the page.
