### ISSUE TITLE
Button pressed state not observed

### ISSUE THREAD

**Issue by mhldtna** [bootstrap-vue/bootstrap-vue#1626]
According to the [button doc](https://bootstrap-vue.js.org/docs/components/button), the "ring" around a button should track the state of the "pressed" prop when you use the :sync modifier.  But it doesn't work.

I noticed this on my own code, then went back and scrutinized the documentation page referenced above.  What I see with the "Toggle Me" example is what I observe in my code: the "ring" around the button shows up when you first click on the button and the pressed state shown below the button says "true". But then you can click on the button all you want, with the pressed state toggling between "true" and "false", but the ring around the button remains.

**Comment by robcresswell** [comment]
Which browser is this on? I think the ring just highlights that the button is "selected" (think accessibility, i.e. tab navigation). The "pressed" indicator is the darkening effect, which changes.

That was observed on Firefox 58.0.2

**Comment by mhldtna** [comment]
I'm using Google Chrome Version 64.0.3282.167 (Official Build) (64-bit).

I hadn't notice the darkening effect.  If that's the "pressed" indicator, I need to make it more effective.

So now my question is: how do I make the "selected" effect come and go like the "pressed" indicator?

**Comment by robcresswell** [comment]
Well, thats just a CSS question. Bootstrap applies the rule here: https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_buttons.scss#L19. This mixin is looped over and generates CSS rules based on the colours input. That loop is here: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_buttons.scss#L63

In your particular case, I *think* something like:

```scss
@each $color, $value in $theme-colors {
  .btn-#{$color}:hover {
     box-shadow: 0 0 0 $btn-focus-width rgba($value, .5);
  }
}
```

should work, as long as your `bootstrap/scss/_variables.scss` is in scope.

**Comment by robcresswell** [comment]
Hi, does this still need work, or can it be closed?

**Comment by mhldtna** [comment]
Sorry for not responding sooner.  I delayed because I'm very busy with other stuff and also  because I'm not sure what to do with this.  I'm not familiar with scss (or is it sass?), my webpack configuration is not setup to  compile scss, and I don't know where to put the code that you offered.  So I have to invest several hours of effort before I can make use of that code.  I don't object to putting in that effort, but it definitely has lower priority than other duties.

As a starting question, can this code go in a <style language="scss> section, or does I have to setup a custom.scss file as described in that theming guide?

Is there a simpler way to deal with this?  My thought (when I get a chance) is to experiment with css to change the classes used by bootstrap.

**Comment by robcresswell** [comment]
I don't really have the time to teach you about how SCSS works, and the Vue guides themselves explain scoped styles etc quite well 😄 We're kinda getting beyond the scope of Bootstrap-Vue here.

If you want something that will "just work for now", you can take the CSS directly from Bootstraps distributed CSS. All you need is to apply the focus styling when the button is active. So if you look at https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L2525 they have:

```css
.btn-primary:focus, .btn-primary.focus {
  box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.5);
}
```

which you could use as:

```css
.btn-primary:active, .btn-primary.active {
  box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.5);
}
```

That's for primary buttons, the others are in the same CSS file further down. I haven't tested this, but I think those are the styles you want.

**Comment by robcresswell** [comment]
Actually, setting the `active-class` property to "focus" should achieve the same thing, from looking through the docs. I'd forgotten about that property.

**Comment by mhldtna** [comment]
Rob, thanks for your help.

I experimented for an hour with your suggestions but got nowhere.  I tried many variations of the .css you proposed, and I also tried an @mouseout method to explicitly reset the box-shadow, but none of it worked.

In case it helps, I have a class called  "buttonLabel" assigned to my button, with this .css:

`
.buttonLabel {
  font-size: x-small;
  padding: 2px;
  text-align: center;
}

.buttonLabel:hover {
  color:yellow;
}
`

The effect I'm seeing looks more like something is setting the "visited" state of the button.  You can see this on Vue's  [button doc](button doc).   When you click on the blue "Toggle Me" button, the ring shows and then never goes away.

(I don't expect you to teach me .scss.  I just think this is a bug somewhere ....)

**Comment by robcresswell** [comment]
The larger ring is due to Chrome's `:focus` effect I think. It's just attaching that to a button when its clicked, so you can tab through them. This was what you mentioned in the first message, which I couldnt recreate in other browsers.

I think you'd need to explcitly disable the `:focus` effect with something like:

```css
.btn-primary:focus, .btn-primary.focus {
  box-shadow: 0 !important;
}
```

**Comment by mhldtna** [comment]
Thanks for the hint!  This worked for me:

```
.buttonLabel:focus, .buttonLabel.focus {
  box-shadow: none !important;
}
```
As did the same but applied to .btn-secondary.

What did not work is "box-shadow: 0"; it has to be "box-shadow: none", at least on Chrome.

**Comment by robcresswell** [comment]
Ah sorry about that. Most of my responses are just off the top of my head while I'm working, so it's more like rough ideas than accurate code. Plus it's ~midnight in my timezone :)

So what's next? Anything further I can help with?

**Comment by mhldtna** [comment]
All is good now.  Many thanks for your help.
