### ISSUE TITLE
Dropdown - prevent closing after click on dropdown-item

### ISSUE THREAD

**Issue by snuuve** [bootstrap-vue/bootstrap-vue#1628]
Is it possible to disable closing after dropdown-item click?

I want to implement something like dropdown-checklist.

**Comment by robcresswell** [comment]
I don't think so; you'd need a custom element for this, unless you wanted to do some hacking around, perhaps with blocking the click handler from propogating. A neater design would probably be to use https://bootstrap-vue.js.org/docs/components/form-select/#multiple-select-support or perhaps a collapsable element with a checkbox group. There are lots of options :)

I think if it was me, I'd probably just have a button that toggles bootstrap display class, on a card element. Something like ```html
<b-card :class="showChecklist ? 'd-block' : 'd-none' ">
...
</b-card>
```

But its hard to tell without seeing code. Hope the suggestions help :)

**Comment by robcresswell** [comment]
Is there any further work needed here, or can this bug be closed?

**Comment by snuuve** [comment]
Inside dropdown i have `<b-dd-item-btn>`, using `@click.stop` doesn't work :/

**Comment by robcresswell** [comment]
Did you try the other suggestions? Using collapse with a checkbox-group, or a multi select?

**Comment by emanuelmutschlechner** [comment]
I was able to create dropdowns with checkboxes:

1. Use `<b-dropdown>` only as a wrapper and place `<b-form-checkbox-group>` inside a `<div>` that uses the `<b-dropdown-item>` class for styling, or
1. Similar to 1. but without `<b-form-checkbox-group>`. Create separate `<div>`'s, each containing one `<b-form-checkbox>`, or
1. Create a custom dropdown component based on `<b-dropdown>` and only suppress close functionality when a item is clicked. 

Check my examples below for further details
https://codesandbox.io/s/l7wqoqpjv9

**Comment by Diaskhan** [comment]
Looks gergeous!

**Comment by CalebM1987** [comment]
@emanuelmutschlechner  thanks for the sample, this works nicely!

**Comment by Diaskhan** [comment]
@snuuve  solution that offered @emanuelmutschlechner  is workable!
I will close issue, if needed u could reopen it !

**Comment by travis5491811** [comment]
Dropdown with checkboxes.

The following works without any need for extra setup. I just took a `b-nav-item-dropdown` and replaced `b-dropdown-item` with `b-form-checkbox`.

```
<b-nav pills>
  <b-nav-item-dropdown id="nav7_ddown" text="Columns" extra-toggle-classes="nav-link-custom" right>
    <b-form-checkbox
      style="margin-left: 5px;"
      v-for="(field, index) in fields" 
      v-bind:key="index"
      v-model="field.hide"
    >{{field.label}}</b-form-checkbox>
  </b-nav-item-dropdown>
</b-nav>
```

**Comment by tmorehouse** [comment]
we are hopfully going to have full support for basic dropdown-item items in the near future

**Comment by srkt** [comment]
Thanks @emanuelmutschlechner .That solved the issue

**Comment by tmorehouse** [comment]
@srkt you can take advantage of the new dropdown form support for placing checkboxes and other form controls.

**Comment by srkt** [comment]
Thanks @tmorehouse

**Comment by DwarGrak** [comment]
<b-dropdown @hide="onDropdownHide">...</b-dropdown>
        
        methods: {
            onDropdownHide(bvEvent) {
                bvEvent.preventDefault();
            },
        },

**Comment by safiullahsarhandi** [comment]
> ```
>     <b-dropdown @hide="onDropdownHide">...</b-dropdown>
>     
>     methods: {
>         onDropdownHide(bvEvent) {
>             bvEvent.preventDefault();
>         },
>     },
> ```

you are the one who i found relevant

**Comment by suryakanigolla** [comment]
@emanuelmutschlechner for bootstrap-vue 2.15.0, the import doesn't work. Any workaround is possible?

**Comment by Namstel** [comment]
> I was able to prevent closing my dropdown with the following modifiers: `@click.capture.native.stop`, e.g.:
> 
> <b-dropdown-item @click.capture.native.stop="onClick">
>     Click here
> </b-dropdown-item>

Thanks! I also added `.prevent` to `@click` to prevent it from going to the top of the page.
