### ISSUE TITLE
Same value/key not displaying in Table.

### ISSUE THREAD

**Issue by Ethan0007** [bootstrap-vue/bootstrap-vue#1631]
Hi,

I just want to ask if how can i display same column name in table? 
Because I'm trying to implement same value/key in column 1 and column 2 but different label in each column.

![image](https://user-images.githubusercontent.com/12542052/36574250-b8213452-187f-11e8-95a1-5fee91dad1ff.png)

Thanks!

**Comment by robcresswell** [comment]
See the table docs section on [Custom Data Rendering](https://bootstrap-vue.js.org/docs/components/table/#custom-data-rendering). You could just a virtual column called "last_name_2" or something that returns "last_name". Kinda intrigued by what data needs to be shown twice with a different label; sounds like it might confuse users 😃

**Comment by Ethan0007** [comment]
@robcresswell yes sir i understand your point, but i want it to automatically map through same key, so that if ever column 1 updated the column 2 will react automatically, is there anyway to implement this solution?

Thanks!

**Comment by robcresswell** [comment]
It should still map automatically, as it does in the custom data rendering docs / example. You can't share keys, as they are unique identifiers. In your case, `Total` would be something like `days x rate` anyway, wouldn't it? If you do just need an identical field, either scoped field slots or a formatter callback will work.

**Comment by Ethan0007** [comment]
@robcresswell yes sir Thank you for your suggestion.

**Comment by robcresswell** [comment]
If this is resolved, would you mind closing the bug report?

**Comment by geryruslandi** [comment]
@robcresswell  is there any better suggestion, why we cant use same key ?
i encounter some case where returned data is:
`[
    {
        "id" : 1,
        "name": "milo",
        "owner": {
             "name": "gery",
             "address": "somestreetnamehere"
        }
    }
]`

i wanted to show owners name and address . how can i achieve that (without map my data);
