### ISSUE TITLE
How to change active tab on click?

### ISSUE THREAD

**Issue by Tarasovych** [bootstrap-vue/bootstrap-vue#1634]
I'm using Vue+Laravel, I want to make a modal window with 2 tabs. I have two buttons, each button must open certain connected tab.  
Buttons are places in `blade` template:

    <button @click="openModal('login')">
    <button @click="openModal('register')">
    
    //Vue component also is placed in blade template
    <auth-component :show="showModal" :active_tab="activeTab" @close="showModal = false"></auth-component>

`/resources/assets/js/app.js`:  
I want to pass `openModal()` ***parameter*** to a component...  

    const app = new Vue({
        el: '#app',
        data: {
            showModal: false,
            activeTab: '',
        },
        methods: {
            openModal(tab) {
                this.activeTab = tab;
                this.showModal = true;
            }
        },
    });

... and use that ***parameter*** as Vue `prop` to set certain [bootstrap-tab][1] as active inside Vue-component:

`AuthComponent.vue`:

    <b-tab title="Login" :active="active_tab === 'login'">
    <b-tab title="Register" :active="active_tab === 'register'">
    ...
    props: ['show', 'active_tab'],

But my current code does not work.
After click on "Login" button "Login" tab prop `active` becomes `true` and "Login" tab becomes active. BUT after click "Register" button "Register" tab prop `active` becomes `true` and "Login" tab is still active, not "Register"! Do I have also change some classes on click?

  [1]: https://bootstrap-vue.js.org/docs/components/tabs/

**Comment by imkimchi** [comment]
Did you solve this issue?

**Comment by Tarasovych** [comment]
@imkimchi I went another way without bootstrap-vue.

**Comment by imkimchi** [comment]
https://bootstrap-vue.js.org/docs/components/tabs/

actually you can achieve this using tabIndex. that's how I resolved this issue
