### ISSUE TITLE
b-table shows column "Row Variant" when first object has attribute _rowVariant

### ISSUE THREAD

**Issue by Keroxo** [bootstrap-vue/bootstrap-vue#1635]
Component: `<b-table>`

Description:
When using _rowVariant in the first object, a column named "Row Variant" is added to the table.

I use Mac OS High Sierra. 
Tested in Chrome 64, Firefox 58 and Safari 11

Bootstrap-Vue Version 2.0.0-rc.1

JSFiddle: https://jsfiddle.net/qy60r139/4/

**Comment by robcresswell** [comment]
I can recreate this. A workaround in the meantime is just to provide a `fields` prop.
