### ISSUE TITLE
b-input-append with b-form-radio-group buttons: incorrect corner rounding

### ISSUE THREAD

**Issue by Burstaholic** [bootstrap-vue/bootstrap-vue#1636]
Looks like the added `btn-group` breaks the `>` CSS combinator meant to un-round the corners in input group buttons:

```
<b-input-group>
    <b-form-input type="date"></b-form-input>
    <b-input-group-append>
        <b-form-radio-group buttons>
            <b-form-radio value="pp">PP</b-form-radio>
            <b-form-radio value="u">U</b-form-radio>
        </b-form-radio-group>
    </b-input-group-append>
</b-input-group>
```
![image](https://user-images.githubusercontent.com/2072033/36682953-fae372e6-1ae1-11e8-86fb-42abd0097453.png)

**Comment by Burstaholic** [comment]
Additional note: these buttons also fail to disable when an enclosing `<fieldset>` is marked `disabled`.

**Comment by robcresswell** [comment]
Button groups are not meant to be used in this way; if you need multiple buttons, just use individual `b-btn` components. I'm fairly certain upstream bootstrap doesn't support this either, as I could only see examples with single buttons.

**Comment by robcresswell** [comment]
Does this issue need further work, or can it be closed?
