### ISSUE TITLE
Popover 'show' event raised twice when using 'show' property

### ISSUE THREAD

**Issue by teedj** [bootstrap-vue/bootstrap-vue#1637]
Hi, 

I'm using the popover component and i noticed that whether I setting the 'show' property the show/shown events are raised twice.
It's a bug?

**Comment by robcresswell** [comment]
I can't recreate this; if I go to https://bootstrap-vue.js.org/docs/components/popover#-b-popover-component-basic-usage and add 

```show @show='console.log("show")```

then I only see a single log line.

Without any versions, browser information, or a recreation, I think this should be closed.

**Comment by teedj** [comment]
Try the following:

` &lt;b-btn id="myPopover"  variant="primary"  ref="button"&gt;
          open popover
  &lt;/b-btn&gt;

&lt;b-popover target="myPopover"
               triggers="click"
               :show.sync="popoverShow"
               placement="auto"
               ref="popover"
               @show="onShow"
              &gt;
...
&gt;/b-popover&gt;

&lt;acript&gt;
export default {
  data() }
}
&lt;/acript&gt;
`

**Comment by teedj** [comment]
I'm sorry,
I'm using bootstrap-vue 1.4.0 and vue 2.5.x.
The issue occurs when using .sync modifier.
Try the following:

``` javascript
<b-btn id="myPopover" variant="primary">
         open popover
</b-btn>

<b-popover target="myPopover"
       triggers="click"
       :show.sync="popoverShow"
       placement="auto"
       ref="popover"
      @show="onShow">

  <b-btn @click="onClose">
   close
  </b-btn>

</b-popover>

<script>
export default {
    data() {
       return { popoverShow: false }
    },

    methods: {
       onShow() {
            console.log("onShow");
       },
      onClose () {
           this.popoverShow = false;
      },
    }
}
</script>

**Comment by robcresswell** [comment]
Could you use a newer version of BV and see if the issue still occurs?

**Comment by catherinejv2** [comment]
I experience the same behavior with 2.0.0-rc.11.

**Comment by tmorehouse** [comment]
This is due to the v-binding and .sync modifier causing a slight race condition due to the sequence of event
