### ISSUE TITLE
adding new row to the table

### ISSUE THREAD

**Issue by kalibani** [bootstrap-vue/bootstrap-vue#1638]
![screenshot from 2018-02-27 16 58 50](https://user-images.githubusercontent.com/30065312/36723421-c591067e-1be2-11e8-813d-674056c41c68.png)
how can i adding new row like this picture?

**Comment by robcresswell** [comment]
It's not clear to me from your screenshot / question what you're trying to do, but it may not be something that Bootstrap provides. The only option I could think of is [Row Details Support](https://bootstrap-vue.js.org/docs/components/table/#row-details-support)

**Comment by kalibani** [comment]
@robcresswell i'm sorry, i mean how to change table structure from this screenshot to my first screenshoot, based on event when some button got clicked.. 
![screenshot from 2018-03-01 09 46 51](https://user-images.githubusercontent.com/30065312/36824550-8cd43a1e-1d35-11e8-8d19-1bd8c8285def.png)

this is my fields props : https://jsfiddle.net/Lobpkcba/
and this is my items props from state productList
![screenshot from 2018-03-01 10 00 03](https://user-images.githubusercontent.com/30065312/36825212-e1814324-1d38-11e8-8706-a1d9b5fe239e.png)
when i click some button, items props become like this : 
![example](https://user-images.githubusercontent.com/30065312/36825307-36637056-1d39-11e8-83b1-c11446b28cb8.png)
i have no idea for displaying data table like my first screenshot, i have try via row detail support but the result not looks like i want
![screenshot from 2018-03-01 10 22 09](https://user-images.githubusercontent.com/30065312/36825530-aa446ab0-1d3a-11e8-8e74-310e14593164.png)

**Comment by robcresswell** [comment]
It looks to me like row details is what you want, but you'll probably want a table in your row details instead of the default card.
