### ISSUE TITLE
Form Select select-size does not apply in single mode

### ISSUE THREAD

**Issue by SignalDancer** [bootstrap-vue/bootstrap-vue#1639]
Operating System: Windows
Browser: Chrome 64, Edge
Bootstrap-Vue Version: 2.0.0-rc1

I need a select list style, not a dropdown, in single mode. The documentation leads me to believe that using the select-size prop is the way to do this. It has no effect regardless of value.

Example : 
`  <b-form-select v-model="selected" :selected-size="20" :options="options" class="mb-3"></b-form-select>`

This problem is also view able in the example on the documentation page as not rendering correctly.

**Comment by robcresswell** [comment]
Yeah I can recreate this. Looks like a bug here: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/form-select/form-select.js#L45, where the code explicitly checks for it to be multiple before passing the size property. I'll put up a PR to fix it.

**Comment by jslewis90** [comment]
The docs list this property as not being required. And yet, after this change, the arrows on the right hand of single selects are no longer properly displayed without explicitly declaring their select-size value of 1.

Therefore, can this either be reverted or have the property use 1 as its default value?

**Comment by robcresswell** [comment]
@jslewis90 https://github.com/bootstrap-vue/bootstrap-vue/pull/1673
