### ISSUE TITLE
After upgrading Bootstrap-vue to 1.5.0 VeeValidate stopped to add automatic validation classes

### ISSUE THREAD

**Issue by yoldar** [bootstrap-vue/bootstrap-vue#1643]
I used before VeeValidate@2.0.4 with Bootstrap-vue@1.0.2. VeeValidate applies automatic classes on inputs or components root elements being validated. Everything worked fine. But after upgrading Bootstrap-vue to 1.5.0 validation and automatic classes stoped to work on Bootstrap-vue b-input. But it works fine with simple usual input. Here is an example of two fields https://jsfiddle.net/2krjuhcq/ where you can test such situation. There can problem be?

**Comment by mosinve** [comment]
https://jsfiddle.net/cihkem/a1fr0rb7/ here's your working example

**Comment by robcresswell** [comment]
Any further work needed here, or can this issue be closed?

**Comment by yoldar** [comment]
@mosinve Thanks!
