### ISSUE TITLE
[Vue warn]: Invalid value for option "components": expected an Object, but got Array.

### ISSUE THREAD

**Issue by KekeORSJ** [bootstrap-vue/bootstrap-vue#1644]
bootstrap -vuw.esm.js   7264,7386 line   components: [bFormCheckbox],     components: [bFormRadio], is error ,components: {bFormCheckbox}, components: {bFormRadio},is true

**Comment by mosinve** [comment]
What Bootstrap-Vue version you use?

**Comment by robcresswell** [comment]
Please read the New Issue content before posting; it helps make debugging much quicker and faster. It's there for a reason :)
