### ISSUE TITLE
On blur in form inputs.

### ISSUE THREAD

**Issue by rnjailamba** [bootstrap-vue/bootstrap-vue#1645]
Have tried @blur="checkURL(this)" and v-on:blur="myFunctionHere()"
Reference - https://github.com/vuejs/Discussion/issues/300

**Comment by rnjailamba** [comment]
I am working around with @input at the moment.

**Comment by mosinve** [comment]
Use `@blur.native  = "myFunctionHere"`

**Comment by rnjailamba** [comment]
Perfect!

**Comment by jnarowski** [comment]
why do we need to use @blur.native?

**Comment by mosinve** [comment]
@jnarowski,  not anymore,  at least in dev branch

**Comment by jnarowski** [comment]
@mosinve nice work

**Comment by Ichag** [comment]
I've tried to find v-on:blur directive in the documentation. Am I right that it is missed there?

**Comment by mosinve** [comment]
it's standard vue directive
and this change don't merged in master yet.

**Comment by gautamc1106** [comment]
Hi I am creating a checklist using a for loop of spans and input. For some reason I need to use on:blur in my span so it closes the entrie dropdown. But it does not trigger the event. Please help. Thanks

**Comment by chriszrc** [comment]
I'm having the same problem as @uriannrima, why is it that the vue-bootstrap form inputs don't emit a blur event?

**Comment by tmorehouse** [comment]
@chriszrc the latest dev branch version supports native events without the .native modifier.

**Comment by thegbom** [comment]
Try @change instead

**Comment by janekx21** [comment]
`@change` not working.
`@focus.native` not working.
`@blur.native` not working.
`@focus` not working.
`@blur` not working.
Im lost here.

**Comment by janekx21** [comment]
This did help: https://stackoverflow.com/questions/60450873/how-to-merge-2-third-party-components-in-vuejs
