### ISSUE TITLE
How to programmatically add checkbox inside table headers

### ISSUE THREAD

**Issue by tzenggy** [bootstrap-vue/bootstrap-vue#1647]
I want to add checkbox in all the headers, but I don't know what column there would be. I know that I can use <template slot="HEAD_colKey" slot-scope="data"> but I will only know the key of each column in run time. So I ended up using for loop to create multiple templates, which require me to have :key inside all the elements within this looped template. 
```
 <template v-for="(headerID, index) in headerIdentifiers" :slot="headerID" slot-scope="data">
        <p :key="index">{{ data.label }}</p>
        <b-button @click.stop="onBtnClicked(headerID)" @click.native.stop :key="headerID"></b-button>
      </template>
```
I don't think this is a good way of doing what I need, which is to add checkbox to all headers. Can someone teaches me how I might do this with Bootstrap-vue.

**Comment by Diaskhan** [comment]
Maybe U need to use v-if tag and store checkable model in data ????

Check https://bootstrap-vue.js.org/docs/components/table#fields-as-an-array-of-objects
it must helps !

**Comment by Diaskhan** [comment]
Issue will closed ! No reaction !
