### ISSUE TITLE
Incorrect modal button variables

### ISSUE THREAD

**Issue by RomeroMsk** [bootstrap-vue/bootstrap-vue#1650]
Check the code, please: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/modal/modal.js#L105-L138

It seems you mixed up the button variables: `okButton` uses `t.cancelVariant`, `t.hide('cancel')`, `$slots['modal-cancel']`, etc, and vise-versa.

**Comment by robcresswell** [comment]
Ha, this is a weird one; although the variables are named wrong, it seems correctly rendered due to the parameters being swapped perfectly. We just need to rename the variables so it makes sense.

**Comment by RomeroMsk** [comment]
> We just need to rename the variables so it makes sense.

Yep. But maybe not to change the buttons order 😃 So it is like in BS4 examples: "Cancel / OK".

**Comment by RomeroMsk** [comment]
Thank you.

**Comment by RomeroMsk** [comment]
@robcresswell, could you please publish the updated version to NPM?

**Comment by robcresswell** [comment]
I don't have that ability. Also there's a few other bugs to investigate before another tag, IMO.

**Comment by RomeroMsk** [comment]
Ok, will wait.
