### ISSUE TITLE
Assign class to body of b-table

### ISSUE THREAD

**Issue by andrewackerman** [bootstrap-vue/bootstrap-vue#1651]
I've been trying how to make this work. I posted about this issue on [StackOverflow](https://stackoverflow.com/questions/49056361/how-to-get-a-vue-b-table-to-scroll-the-body-with-a-fixed-header?noredirect=1#comment85130789_49056361) and they didn't seem to know the solution. Like I said in that post, I've tried several ways to go about this, using both what (little) I could find in the documentation and some suggestions from past issue threads, but no matter what I do, the `b-table` seems to ignore everything I throw at it. Is this a bug or am I missing the purpose of this feature?

**Comment by robcresswell** [comment]
Please follow the issue template. It's there for us to help you. What version of bootstrap vue, browser, code examples... etc. Thanks.

**Comment by andrewackerman** [comment]
I'm using Mac OS X on Safari and Chrome. Everything else was in that SO post.

**Comment by robcresswell** [comment]
I can't see the Bootstrap-Vue version, my apologies if I'm missing it

**Comment by andrewackerman** [comment]
I assumed that it was included with Vue. My project doesn't specifically list Bootstrap-Vue as a dependency anywhere, but the `b-table` tag still works.

**Comment by robcresswell** [comment]
No, it's not; we'll need to know what you're including before we can help. The Vue version you're using is also fairly outdated, though that's unrelated at the moment.

**Comment by andrewackerman** [comment]
After doing some digging, it seems that this `b-table` is in fact coming from Buefy rather than Bootstrap-Vue. (Incidentally, CoreUI and several other Vue-related libraries also use the `b-table` tag. That's not a source of confusion at all.)
