### ISSUE TITLE
Fields as an object

### ISSUE THREAD

**Issue by MarcelKendy** [bootstrap-vue/bootstrap-vue#1656]
Whats up guys, I'am here to express some problem that I've founded in a couple days ago.
I Have a foreign key to other table  that has its id recorded, but I want to display the name instead of the id in the table. I have followed all the procedures founded in forums and the methodologies on this link: https://bootstrap-vue.js.org/docs/components/table/
but it doesnt seem to work. However, more strange than that, is the items collection that comes with all the needed informations of that field, but the table comes in blank. 
Somebody has faced some problem with it and found a solution, or moved to another way? 
I'am very concerned because its a extremely simple thing and it was not supposed to be happening anyway.
![screenshot_1](https://user-images.githubusercontent.com/32130772/37109701-7d8c2830-2219-11e8-876a-86d886a5be50.png)
![screenshot_3](https://user-images.githubusercontent.com/32130772/37109703-7df6f1c4-2219-11e8-932f-c29b09869164.png)
![image](https://user-images.githubusercontent.com/32130772/37109722-8c6129b4-2219-11e8-838c-4589e293faed.png)

**Comment by danswiser** [comment]
Are you on version 2.0.0-rc.2 or earlier? I just had the same issue and updated to 2.0.0-rc.2 where it's working fine.

**Comment by robcresswell** [comment]
Please read the issue template when filing an issue; I don't understand why you would just delete it all, disregard it, then post your own script. We need information about browser, bootstrap-vue version, and examples or we cannot help you 😄

**Comment by MarcelKendy** [comment]
It seems that danwiser is damn wise, thank you, that was the problem. I was int the rc.1 version. I don't know why but it works fine now

**Comment by robcresswell** [comment]
If it's fixed, could you close the issue please?

**Comment by Diaskhan** [comment]
MarcelKendy  if its ok.  u could close issue !!
