### ISSUE TITLE
Cannot import single component with Nuxt

### ISSUE THREAD

**Issue by Okazari** [bootstrap-vue/bootstrap-vue#1657]
Operating system: Ubuntu
Browser and version: Node v8.9.4
Bootstrap-Vue: 2.0.0-rc2
Nuxt: 1.4.0
Repo reproducing the issue: https://github.com/Okazari/bootstrap-vue-nuxt/tree/master/bootstrap-vue-nuxt  

Hey, i'm runing into an issue when using Bootstrap-vue along with Nuxt :
As some of my page are only using few components, i want to import them directly instead of importing the whole vue module to profit from nuxt automatic page chunks.

But when i do this in my component
```js
import bButton from 'bootstrap-vue/es/components/button/button';

export default {
  components: {
    bButton,
  }
}
```

It works fine on the browser (if there is only hot-reload, or if i navigate to the concerned page through the browser) but i run into the following error when it run on the server (by refreshing the page that use the component) :
```js
import { mergeData } from 'vue-functional-data-merge';
^^^^^^

SyntaxError: Unexpected token import
```

Providing a built file for each component would solve the issue but this is not the best idea (since importing multiple built components would duplicate common javascript). Any workaround ? Should i totally forgot about doing such optimization (i have the same issue with importing a component as a module btw) ? 

Thanks in advance :) !

**Comment by jetrii** [comment]
FWIW I'm also experiencing issues with Nuxt.js and Bootstrap-Vue: 2.0.0-rc2. Things worked fine yesterday before the release.

**Comment by Okazari** [comment]
In my case I was using rc1 this afternoon and i was already running into
this issue.

Le 7 mars 2018 22:33, "Alexander Andino" <notifications@github.com> a
écrit :

**Comment by robcresswell** [comment]
@jetrii Would you mind posting what your error was, so others can solve it too? Also if you could close the issue report at the same time that would be great 😄

**Comment by jetrii** [comment]
@robcresswell My issue ended up being a docker configuration error, some files weren't being copied over correctly. Wasn't really related to nuxt / bootstrap. Also, which issue? I didn't report this one.

**Comment by robcresswell** [comment]
@jetrii Ah, sorry, wasn't paying enough attention.

@Okazari It looks like your SSR setup isn't parsing the ES6 imports properly. Node doesn't by default, so thats not too surprising. I think its just a config issue in your setup.

**Comment by Okazari** [comment]
Hmm yeah that's right. I may fill up an issue on Nuxt. Since the default configuration doesn't support ES6 modules from node_modules. Thanks anyway

**Comment by rafaelmagalhaes** [comment]
has this been resolved having same problem how can i fix it ?

**Comment by saintech** [comment]
This worked for me:

```javascript
// nuxt.config.js
module.exports = {
  mode: 'universal',
  '...',
  build: {
    '...',
    transpile: ['bootstrap-vue']
  }
}
```

**Comment by sogeniusio** [comment]
But what if you just wanted to pull in the css for that specific component. I ask this because I just need the bootstrap table, but can't find a clean way to import it without affecting tailwindcss.
