### ISSUE TITLE
Missing arrows in Form Select in v2.0.0-rc.2

### ISSUE THREAD

**Issue by x42y** [bootstrap-vue/bootstrap-vue#1658]
Version: 2.0.0-rc.2

As seen here: https://bootstrap-vue.js.org/docs/components/form-select/ the arrows in the select dropdowns are missing in rc 2.

**Comment by robcresswell** [comment]
Ack, I think this is something I've changed. I'll take a look later today.

**Comment by robcresswell** [comment]
Yeah, this is my fault, I've found the problem, fixing now.

**Comment by ChrisCalculus** [comment]
Hi @robcresswell, when will this be available in master? Thanks.

**Comment by robcresswell** [comment]
@ChrisCalculus When I get time to finish it? In the next couple of days I'd imagine 😄

**Comment by robcresswell** [comment]
That should fix a couple of issues with select. Sorry for breaking it, was fixing something else and derped.

**Comment by ChrisCalculus** [comment]
Great @robcresswel, thanks for your time and solving it.

**Comment by Morgul** [comment]
I'm currently getting his by this as well, it's blocking upgrading to rc.2 for me.

**Comment by robcresswell** [comment]
@Morgul: did you read the thread?

**Comment by Morgul** [comment]
@robcresswell Yes, I did, I'm aware of the open merge request. But it's often useful to know how many people are effected by an issue when planning releases, etc, and my comment was just an attempt to provide that. :)

**Comment by iruizeguilaz** [comment]
I have updated the version and getiing thiis solved, but someone else has come acrross a similar problem with the table columns in sorting??? I do not get the arrows there....

**Comment by Jodge** [comment]
I am currently experinceing the same problem on `"vue": "^2.5.2"`
