### ISSUE TITLE
Tooltip not hiding when calling $emit('disable')

### ISSUE THREAD

**Issue by molerat619** [bootstrap-vue/bootstrap-vue#1659]
Hey there,

I have read the [docs](https://bootstrap-vue.js.org/docs/components/tooltip/) and it says that when I run `this.$refs.tooltip.$emit('disable')` the tooltip **will first disappear and then be disabled**. But for some reason, it does not happen.

When I `console.log(this.$refs['tooltip'+item.id])` the first thing I realized is that I get an array of VueComponents (length 1) instead of 1 VueComponent (not in array). So I have to run this: `this.$refs['tooltip'+item.id][0].$emit('disable')`. When I look at the item in the console again, the disabled-field is still set to false.

I am using the tooltip on a button inside each table row. That's what the tooltip looks like:

```
<!-- Tooltip -->
<b-tooltip :ref="'tooltip'+item.id" target="add_tasks_button" placement="top">
	My text
</b-tooltip>
```

I am using chrome on Mac and bootstrap-vue version 2.0.0-rc.1.

**Comment by robcresswell** [comment]
Can you create a JSFiddle via https://bootstrap-vue.js.org/play to recreate it?

**Comment by molerat619** [comment]
I don't know how to get the code working on JSFiddle, but here it is at least. JSFiddle complains about braces or something, but I don't understand tbh.

https://jsfiddle.net/jb73po36/7/

**Comment by tmorehouse** [comment]
Are you using the `.sync` modifer on the `disabled` prop?  Props are normally one way (parent to child).

If you need to have the prop two way, then you need to use the `.sync` modifier. components can't change the value of a prop.  They have to inform the parent component to update it via a special `updated:xxxx` event.

```html
<b-tooltip :disabled.sync="myDiabled" ... >
```
