### ISSUE TITLE
Playground Issue.

### ISSUE THREAD

**Issue by Ethan0007** [bootstrap-vue/bootstrap-vue#1663]
Hi,

The playground is having issues, it will give an error then i cant allow to edit the said code , the browser freeze. Please see example below:

![image](https://user-images.githubusercontent.com/12542052/37191296-9fc7d72e-2399-11e8-9399-9d6a58331dad.png)

**Comment by robcresswell** [comment]
Ha, interesting, I can recreate this too.

**Comment by tmorehouse** [comment]
This is fixed in the latest dev code and will be available in the next release (coming soon)
