### ISSUE TITLE
[table] Need an example of datatable with checkable rows

### ISSUE THREAD

**Issue by punk1ecrabbz** [bootstrap-vue/bootstrap-vue#1664]
Hello.
Does table component have a ready-to-use rows checking/select feature? Something like this:
https://codepen.io/punkie/pen/OvJGOW

For example, Buefy provides "checkable"-option in b-table tag to enable this.

**Comment by robcresswell** [comment]
Take a look at the Row Details Support section; it already shows how to use a custom column with a checkbox. Just adjust it for your own use case.

**Comment by Diaskhan** [comment]
There workable solution by link
https://bootstrap-vue.js.org/docs/components/table/#row-details-support
punk1ecrabbz if this solution satisfied u, U could close the issue !

**Comment by skendermoglica** [comment]
I'm trying to use the row details support but I got this:

[Vue warn]: Property or method "row" is not defined on the instance but referenced during render.

I followed the example step by step. Any suggestion?
