### ISSUE TITLE
Injection in b-form-group valid/invalid feedback properties

### ISSUE THREAD

**Issue by fkaempfer** [bootstrap-vue/bootstrap-vue#1665]
I saw you were fixing a couple of html injections in the last build (for example #1554 and also in b-tab).

I just noticed it is still possible to inject html into form-groups valid/invalid feedback properties in 2.0.0-rc2. So if you have an error like "xy is not a valid email address" it is possible to inject html into the invalid email address.

Perhaps this is by design though. Feel free to close if this is the case.

Example:

`
 <b-form-group invalid-feedback="<h1 onclick=&quot;alert('injected');&quot;>Click me</h1>" class="was-validated">
            <b-form-input type="text" required/>
  </b-form-group>
`

**Comment by robcresswell** [comment]
I don't know that this is by design necessarily; I'll look at the code. I don't think it's a security issue in this case, since a user isn't going to be providing their own feedback.

**Comment by fkaempfer** [comment]
>  I don't think it's a security issue

I agree that it isn't most of the time. As I wrote above, it could happen though if you echo input back to the client ("xy is an invalid email address" or something like this).

**Comment by robcresswell** [comment]
Very true. We should fix the issue. There are better ways (slots) to provide feedback anyway.

**Comment by tmorehouse** [comment]
Closed via #2129
