### ISSUE TITLE
Please provide instructions  how to build bootstrap-vue-2.0.0-rc.2?

### ISSUE THREAD

**Issue by mrafea-sa** [bootstrap-vue/bootstrap-vue#1666]
Dear All
kindly , please provide guide , how to compile bootstrap-vue-2.0.0-rc.2 code to release Browser "bootstrap-vue.js"   ?

As executing command :  npm run build
results 
{
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle bootstrap-vue@2.0.0-rc.2~prebuild: bootstrap-vue@2.0.0-rc.2
6 info lifecycle bootstrap-vue@2.0.0-rc.2~build: bootstrap-vue@2.0.0-rc.2
7 verbose lifecycle bootstrap-vue@2.0.0-rc.2~build: unsafe-perm in lifecycle true
8 verbose lifecycle bootstrap-vue@2.0.0-rc.2~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\hd_mnt\vue171218\vue_project\bootstrap-vue-2.0.0-rc.2\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Users\m2\AppData\Local\Yarn\bin;C:\Users\m2\AppData\Roaming\npm
9 verbose lifecycle bootstrap-vue@2.0.0-rc.2~build: CWD: C:\hd_mnt\vue171218\vue_project\bootstrap-vue-2.0.0-rc.2
10 silly lifecycle bootstrap-vue@2.0.0-rc.2~build: Args: [ '/d /s /c', 'scripts/build' ]
11 silly lifecycle bootstrap-vue@2.0.0-rc.2~build: Returned: code: 1  signal: null
12 info lifecycle bootstrap-vue@2.0.0-rc.2~build: Failed to exec build script
13 verbose stack Error: bootstrap-vue@2.0.0-rc.2 build: `scripts/build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid bootstrap-vue@2.0.0-rc.2
15 verbose cwd C:\hd_mnt\vue171218\vue_project\bootstrap-vue-2.0.0-rc.2
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error bootstrap-vue@2.0.0-rc.2 build: `scripts/build`
22 error Exit status 1
23 error Failed at the bootstrap-vue@2.0.0-rc.2 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
}
Thanks , best regards

**Comment by robcresswell** [comment]
I can't recreate this unfortunately. I've got `node 8.9.4` and `npm 5.6.0` on macOS, and it works fine :(

**Comment by mrafea-sa** [comment]
@robcresswell  thanks,
Issue still exist , i think it is related windows OS as the following 
npm run build doesn't work on Windows because  (forward slash).
https://github.com/eclipsesource/jsonforms/issues/752
https://github.com/yarnpkg/yarn/issues/1729

i had tried on fresh windows installation with yarn , the result was:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v9.9.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle bootstrap-vue@2.0.0-rc.2~prebuild: bootstrap-vue@2.0.0-rc.2
6 info lifecycle bootstrap-vue@2.0.0-rc.2~build: bootstrap-vue@2.0.0-rc.2
7 verbose lifecycle bootstrap-vue@2.0.0-rc.2~build: unsafe-perm in lifecycle true
8 verbose lifecycle bootstrap-vue@2.0.0-rc.2~build: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\a_mnt\vue171220v\js\bootstrap-vue-dev\node_modules\.bin;C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\a_mnt\vue171220v\js\bootstrap-vue-dev\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\mh01\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Brackets\command;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\nodejs\;C:\Users\mh01\AppData\Roaming\npm
9 verbose lifecycle bootstrap-vue@2.0.0-rc.2~build: CWD: C:\a_mnt\vue171220v\js\bootstrap-vue-dev
10 silly lifecycle bootstrap-vue@2.0.0-rc.2~build: Args: [ '/d /s /c', 'scripts/build' ]
11 silly lifecycle bootstrap-vue@2.0.0-rc.2~build: Returned: code: 1  signal: null
12 info lifecycle bootstrap-vue@2.0.0-rc.2~build: Failed to exec build script
13 verbose stack Error: bootstrap-vue@2.0.0-rc.2 build: `scripts/build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid bootstrap-vue@2.0.0-rc.2
15 verbose cwd C:\a_mnt\vue171220v\js\bootstrap-vue-dev
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v9.9.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error bootstrap-vue@2.0.0-rc.2 build: `scripts/build`
22 error Exit status 1
23 error Failed at the bootstrap-vue@2.0.0-rc.2 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
