### ISSUE TITLE
Multiple filter in table

### ISSUE THREAD

**Issue by kirill-voronov** [bootstrap-vue/bootstrap-vue#1667]
Hello, I'd like to request a feature of multiple filters.
For example below there is a table with a search box and a predefined filter (select box).

<img width="600" alt="2018-03-10 22 26 51" src="https://user-images.githubusercontent.com/10974617/37246029-cd1d2ffc-24b2-11e8-9032-e7d1080796f6.png">

Filtering is processed by ajax, and It will be nice to have something like 

```
<input v-model="filter.search" />
<select v-model="filter.roleId"> ... </select>
<b-table :filter="filter" :items="itemsProvider">...</b-table>
```
and then get

```
filter: {
    search: 'john',
    roleId: 1
}
```

inside **ctx** of itemsProvider, so I could get users with both name like 'john' and roleId equals 1 from my api.

**Comment by Diaskhan** [comment]
I guesse it must be customizable chain functions that integrates in vue-table!
And seems to me filtering must be computed, and computed function must be a able from api !

**Comment by SergejsZerins** [comment]
Is it possible that we will see this feature in nearest future ?

**Comment by wetickets** [comment]
This feature would be really great, i hope we will see this very soon.. Busy with a project atm where i must use multiple filtering. Thanks!

**Comment by Kritzzz** [comment]
+1, would be immensely useful!

**Comment by wishe** [comment]
Is this something that is being looked at? Without this the table component is not so useful.

**Comment by bsgiovanini** [comment]
+1

**Comment by boriskogan81** [comment]
+1

**Comment by fats2005** [comment]
Hello!! I solved the problem with a computed method and [Array.prototye.filter()](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Array/filter)

```html
<b-table show-empty striped hover :items="invitationsFiltered">

</b-table>
```

```javascript
computed: {
    invitationsFiltered: function () {
      var filtered = this.getInvitations.filter((el) => {
        return el.email.toLowerCase().indexOf(this.filterEmail.toLowerCase()) > -1 &&
              el.sent.toLowerCase().indexOf(this.filterSent.toLowerCase()) > -1 &&
              el.expires.toLowerCase().indexOf(this.filterExpires.toLowerCase()) > -1 &&
              el.update.toLowerCase().indexOf(this.filterUpdate.toLowerCase()) > -1 &&
              el.status.toLowerCase().indexOf(this.filterStatus.toLowerCase()) > -1
      })

      return filtered
    },
    ...mapGetters([
      'getInvitations'
    ])
  }
```

**Comment by adhatama** [comment]
For an alternative, I've got it worked by `watch`-ing the model `filters` then `refresh` the table. The `refresh` will trigger the `itemsProvider`

```html
<input v-model="filters.search" />
<select v-model="filters.roleId"> ... </select>

<b-table ref="table" :items="itemsProvider">...</b-table>
```

```js
data () {
    return {
         filters: {
             search: null,
             roleId: null
         }
    }
},

watch: {
    filters: {
        handler: function () {
              this.$refs.table.refresh()
        }
    }
},

methods: {
    itemsProvider: function (ctx, callback) {
         console.log(this.filters.search)
         console.log(this.filters.roleId)
    }
}
```

**Comment by rsmithlal** [comment]
> For an alternative, I've got it worked by `watch`-ing the model `filters` then `refresh` the table. The `refresh` will trigger the `itemsProvider`

Thank you so much! This is exactly the solution for my issue. I was having trouble hooking in custom filter elements to the `itemsProvider` function, and couldn't figure out how to force the table to refresh. Thank you!

**Comment by yoerriwalstra** [comment]
@adhatama's solution works indeed! It does require you to take on some more responsibilities, however, if your table uses pagination (with the `<b-pagination/>` component). 

You have to handle creating the right subset of items for your paginated result. You can use the [itemProvider](https://bootstrap-vue.org/docs/components/table#provider-paging-filtering-and-sorting) its `ctx.perPage` and `ctx.currentPage` properties, or `perPage` and `currentPage` state properties (if you have those) and combine it with [Array.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) like @fats2005 suggested. You will also need to manually update the `total-rows` prop on the `<b-pagination/>` component.

I solved this in the following way for my personal case:
```
itemsProvider: function ({ perPage, currentPage }) {
    if (!this.filters.search && !this.filters.moduleId) {
        return this.paginate(this.lessons, currentPage, perPage);
    }

    return this.paginate(this.filteredItems(), currentPage, perPage);
},

filteredItems() {
    let filteredItems = this.lessons;
    if (this.filters.moduleId) {
        filteredItems = filteredItems.filter(lesson => lesson.module_id === this.filters.moduleId);
    }

    if (this.filters.search) {
        const regexp = new RegExp(this.filters.search, 'i');
        filteredItems = filteredItems.filter(lesson => lesson.title.match(regexp));
    }

    return filteredItems;
},

paginate(items, page, perPage) {
    this.totalRows = items.length;

    return items.slice((page - 1) * perPage, page * perPage);
},
```

**Comment by Allan-Nava** [comment]
> For an alternative, I've got it worked by `watch`-ing the model `filters` then `refresh` the table. The `refresh` will trigger the `itemsProvider`
> 
> ```
> <input v-model="filters.search" />
> <select v-model="filters.roleId"> ... </select>
> 
> <b-table ref="table" :items="itemsProvider">...</b-table>
> ```
> 
> ```js
> data () {
>     return {
>          filters: {
>              search: null,
>              roleId: null
>          }
>     }
> },
> 
> watch: {
>     filters: {
>         handler: function () {
>               this.$refs.table.refresh()
>         },
>         deep: true
>     }
> },
> 
> methods: {
>     itemsProvider: function (ctx, callback) {
>          console.log(this.filters.search)
>          console.log(this.filters.roleId)
>     }
> }
> ```

Doesn't work
