### ISSUE TITLE
Loading state for b-button

### ISSUE THREAD

**Issue by RomeroMsk** [bootstrap-vue/bootstrap-vue#1669]
Feature request: add a "loading" state (with the loading text support) to the `bButton` component, similar to [the Bootstrap v3.3 implementation](https://getbootstrap.com/docs/3.3/javascript/#buttons-stateful).

**Comment by robcresswell** [comment]
What's the argument for adding this? Kinda curious. Adding some unlocalised default text to something that is otherwise identical to a disabled state seems a bit redundant to me :)

**Comment by RomeroMsk** [comment]
Now, to implement this I have to extend the `bButton` component. Could be great to have this functionality out of the box.

There is no need to add a default text, this could work like in BS 3.3. When the text is set via a property, you just show it instead of the current button title (and reset the title back when the loading state is unset). If no text is provided, just show the spinner (by adding some class to a button), with no title changes.

**Comment by mosinve** [comment]
Requested feature was deprecated since Bootstrap 3.5. 
We wouldn't implement it in our library, as Bootstrap-Vue inherit Bootstrap4.
And there's no any difficulties to implement this in your own project.

**Comment by RomeroMsk** [comment]
I meant some CSS styling, doesn't matter how exactly it will be implemented (a spinner SVG or just `.disabled` class) if one can restyle the class you use.

**Comment by RomeroMsk** [comment]
> We wouldn't implement it in our library, as Bootstrap-Vue inherit Bootstrap4.

You implemented some features on top of default BS4 functionality (like table busy state or table sorting, for example), but don't want to add something else that can be useful for someone?

> I've just got a v-if on the button content that changes to a localised loading string and a spinner SVG icon

Thanks for the idea.

**Comment by robcresswell** [comment]
@RomeroMsk It's probably more related to how the authors / library have changed a little over time. Personally I'm a bit more conservative; I've more interested in reducing maintenance and raising stability of bootstrap-vue because of the high usage, than trying to keep adding potentially useful features. 

In this case specifically, there really is very little utility added since we don't do localisation or icons, so what you're asking for is basically already provided by the `disabled` prop, at least within the extent of BV.

**Comment by yakuthemes** [comment]
https://getbootstrap.com/docs/4.2/components/spinners/#buttons

**Comment by tmorehouse** [comment]
The latest dev branch, which is based on Bootstrap V4.2, supports two "spinners", which can be used with buttons to show a loading state, and you can just v-if them in or out of document.

**Comment by maverickpravin** [comment]
@tmorehouse @RomeroMsk @mosinve even if bootstrap-vue inherits Bootstrap, this should not stop you guys from evaluating new feature components that are provided by other UI frameworks. Probably a poll can be held for vue developers for what features they would love to see in the next release.
TIA

**Comment by robcresswell** [comment]
Yes they should hold a poll for everyone to demand extra work 🤣

I think it's quite reasonable to let people just maintain a layer over Bootstrap itself, and as Troy said, there are built in loading spinners you can use 😇

**Comment by tmorehouse** [comment]
We are considering a separate repo/monorepo of addon components that build on the base BootstrapVue components.

**Comment by suguoyao** [comment]
I think it can be like this 🤣
[loading button](https://element.eleme.cn/#/en-US/component/button)
