### ISSUE TITLE
Input directory

### ISSUE THREAD

**Issue by boshevski** [bootstrap-vue/bootstrap-vue#167]
The form-file component works great for files. How do we go about choosing a directory instead of a file?

**Comment by pi0** [comment]
@boshevski Multiple file uploading is now implement :) Will come to new release soon ..
![image](https://cloud.githubusercontent.com/assets/5158436/24239677/8848722a-0fcc-11e7-810d-8fc2b466e467.png)

**Comment by mosinve** [comment]
@pi0 it's not a directory feature ;)
There is experimental param to <input file>  - **webkitdirectory**
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory
http://jsfiddle.net/addyo/Ha979/
https://plus.google.com/+AddyOsmani/posts/Dk5UhZ6zfF3

**Comment by pi0** [comment]
@mosinve Thanks for tip i'm going to dig into them for more information :) 
> The HTMLInputElement.webkitdirectory is a property that reflects the webkitdirectory HTML attribute and indicates that the <input> element should let the user select directories instead of files. When a directory is selected, the directory and its entire hierarchy of contents are included in the set of selected 

As mentioned in MDN, it just allows user select entire directory instead of individual files. Seems handling both multiple and directory is same. The only different would be that each file in the array has `File.webkitRelativePath`  attr: 

> After the user makes a selection, each File object in files has its File.webkitRelativePath property set to the relative path within the selected directory at which the file is located

So I'll add another prop `directory` to allow enabling such behavour.

**Comment by mosinve** [comment]
Yep.... but i think we need to make notice in docs, that this feature has limited support in browsers.
In firefox we must set `allowdir=true `additional to `webkitdirectory` param

**Comment by pi0** [comment]
Sure I'll add notice. Will inform you after merge so we can check it before release :)

**Comment by boshevski** [comment]
That was quick! Thank you @pi0 and @mosinve 👍

**Comment by pi0** [comment]
@boshevski  0.10.2 released :)
