### ISSUE TITLE
Ability to set additional modal classes

### ISSUE THREAD

**Issue by RomeroMsk** [bootstrap-vue/bootstrap-vue#1674]
Please add an ability to set additional modal classes. Something like `modal-class` property (similar to `header-class`, `body-class`, and `footer-class`).

I can make a PR for this if you are ok.

**Comment by robcresswell** [comment]
```vue
<b-modal class="myModalClass">
...
</b-modal>
```

**Comment by RomeroMsk** [comment]
No, this code assigns a class to the root `div` element, not to the `div.modal`.

**Comment by robcresswell** [comment]
Ah, hadn't realised it was nested. I wonder if that's even necessary; it might be worth looking into removing some of the nesting rather than adding more props, although that may constitute a breaking change.

**Comment by RomeroMsk** [comment]
Well, even if we get rid of the root `div` element, the `div.modal` will not be on the top, as there is also a "modal outer" element there.

So, I will add a PR with `modalClass` property.

**Comment by robcresswell** [comment]
Right, thats why I said "some of the nesting" rather than "the root div"; I don't know if that modal outer is really required either. Anyway, modalClass probably works fine.

**Comment by RomeroMsk** [comment]
Tested, thanks.
