### ISSUE TITLE
Pagination component support for Laravel's simplePaginate

### ISSUE THREAD

**Issue by curtjenk** [bootstrap-vue/bootstrap-vue#1676]
With Laravel's simplePaginate, we don't get total rows and thus will not need the page number buttons.  Ideally, I'd like to see First, Prev and Next buttons.

**Comment by robcresswell** [comment]
This would likely need to be a separate component. All of the current pagination content is based on handling page numbers, so even the events would need reworking, as they output numbers (`1`, `,2`, etc.) rather than instructions (`next`, `previous`).

**Comment by robcresswell** [comment]
Perhaps in the future we could add a `simple-pager` component or something.

**Comment by curtjenk** [comment]
@robcresswell THANKS
