### ISSUE TITLE
Modal footer button order different from Bootstrap

### ISSUE THREAD

**Issue by mzgajner** [bootstrap-vue/bootstrap-vue#1679]
I have a general UX question. The order of OK and Cancel buttons dialogs is an interesting [topic for UX discussions](https://www.nngroup.com/articles/ok-cancel-or-cancel-ok/) with no clear answer.

Is there a particular reason for `bootstrap-vue` deliberately changing the default order of these buttons in the modal component compared to [default Bootstrap examples](http://getbootstrap.com/docs/4.0/components/modal/)?

**Comment by robcresswell** [comment]
This was fixed by https://github.com/bootstrap-vue/bootstrap-vue/pull/1660 and will be in the next release.

**Comment by mzgajner** [comment]
Thanks, missed it!

**Comment by robcresswell** [comment]
No worries, it wasn't immediately obvious by the patch intent. I only knew because I was the author 😄

**Comment by mikestu** [comment]
Unfortunately, this component just ordered the buttons the same way the bootstrap demos have their buttons in the modal markup samples.  I know the bootstrap guys had to choose an order for their samples (they chose the Mac order), but some apps have Cancel on the far right (like my app).  It probably means we have to either create our own mixin, or devs always define buttons in the footer in the order we want.  Even if there was a new option to reverse the order, I don't know that Vue has a way to set a global option for a component today.  If there are other options for my issue, please let me know.

**Comment by robcresswell** [comment]
@mikestu You can easily just make a modal component in your app that overrides the footer and passes through the rest of the content. Then you don't need every dev to redefine it.
