### ISSUE TITLE
Table showing row details will collapse after item change

### ISSUE THREAD

**Issue by infostatus** [bootstrap-vue/bootstrap-vue#1684]
When I'm showing details toggle on a table, if that item that is expanded is altered it will reset the showDetails property to false and hide the details.

Is this a issue or there's something I'm missing?

Thank you for your work.

**Comment by robcresswell** [comment]
Can you please follow the bug template? It's to help us debug. I don't understand why people just ignore / delete the bug template then expect us to be able to help properly. Without code or versions, I can only make educated guesses.

**Comment by infostatus** [comment]
Hi Rob. Sorry, didn't thought this was a bug, and didn't even bothered to read the template, my bad.
Will ask on StackOverflow.
Continue the good work.

**Comment by robcresswell** [comment]
There's a slack channel if you want to ask questions; check https://bootstrap-vue.now.sh/

**Comment by Diaskhan** [comment]
@infostatus We will close issue. U didnt provide code to reproduce problem!
