### ISSUE TITLE
Bootstrap navbar example does not work

### ISSUE THREAD

**Issue by joni8a** [bootstrap-vue/bootstrap-vue#1686]
Hello,

I installed a new project with the vue cli + bootstrap and tried the bootstrap navbar example which can be found here: https://getbootstrap.com/docs/4.0/components/navbar/
But the dropdown, as well as the toggle button does not work. I do not get any error warnings, any ideas what I might do wrong ?

**Comment by iruizeguilaz** [comment]
I have the same issue
