### ISSUE TITLE
b-table: Allow a fields label to be a function or computed property

### ISSUE THREAD

**Issue by dflock** [bootstrap-vue/bootstrap-vue#1687]
Currently (v2.0.0-rc.2), afaik the `label` property of a `field` needs to be a string. If I set it to a computed property, it just falls back to using the `key`:

```js
fields: [
        { key: 'id', label: 'Id', sortable: true },
        { key: 'name', label: 'Name', sortable: true },
        { key: 'description', label: 'Description', sortable: true },
        { key: 'priority', label: this.getPriority, sortable: true }
      ],
...
computed: {
    getPriority () {
      return this.$i18n.t('fields.priority.label')
    }
  }
```

This would be very useful to allow translating the column headers, for multi-language apps.

I imagine I could do this using custom header slots - but then I'd have to do a custom header slot for every column in every table. It would be much more concise and flexible if `label` would accept a function, that returned a string.

**Comment by dflock** [comment]
It's just occurred to me that I could probably make the `fields` property point to a computed property, that returns the complete fields object, with the translated strings already in there.
I'll try this next week and see if it works.

**Comment by dflock** [comment]
Ok, so making `fields` point to a computed property which returns the fields object works well:

```js
<b-table :fields="fields" />

...

methods: {
  tCol (colName) {
    return this.$i18n.t(this.$route.name + '.fields.' + colName + '.label')
  }
},
computed: {
  fields () {
    return [
      { key: 'id', label: this.tCol('id'), sortable: true },
      { key: 'name', label: this.tCol('name'), sortable: true },
      { key: 'description', label: this.tCol('description'), sortable: true },
      { key: 'priority', label: this.tCol('priority'), sortable: true }
    ]
  }
}
```

This gets you reactive translated column headers; you could also make any other property of the `field` object dynamic/reactive.

**Comment by ludo237** [comment]
@dflock came here to say thank you. Just saved hours of headache <3

**Comment by tmorehouse** [comment]
Using a computed prop is also more efficient as it will cache the results of the generated value util something triggers it to update (i.e. the language/locale value).

Otherwise the function defining the label would be called each time the table needs to re-render, which would decrease performance.
