### ISSUE TITLE
Bootstrap-Vue usage when utilising render() and JSX.

### ISSUE THREAD

**Issue by DaleMckeown** [bootstrap-vue/bootstrap-vue#1689]
Hi,

I've trauled the docs and I can't find anything in relation to using Vue's render() or JSX to generate any of these elements.

I'm having trouble even with the simplest scenario such as opening a modal on the click of a button.

```
const vue2 = new Vue({
    el: '#vue2',
    data: function() {
        return {
            show: false
        }
    },
    render() {
        return(
            <div>
                <b-btn v-b-modal="'myModal'">Show Modal</b-btn>
                <b-modal id="myModal">
                    Hello From My Modal!
                </b-modal>
            </div>
        )
    }
});
```

The elements are actually rendered in HTML:
![image](https://user-images.githubusercontent.com/1249673/37569516-6c63e1d6-2adb-11e8-9ebb-02c49d22cfc8.png)

But the 'click' event  on the button doesn't work.

If I log the Vue instance in the console there is no instance to the modal in this.$refs, either.

Does bootstrap-vue support Vue's render() & JSX functionality? If so, how is this kind of thing achieved?

**Comment by DaleMckeown** [comment]
This is still an ongoing issue that I'm running in to.
I'd really appreciate a comment from someone who has any experience with using Bootstrap-Vue and JSX.

**Comment by DaleMckeown** [comment]
So, I spent a fair bit of time looking into this. I could not get the above to work, It may be a bug in Bootstrap-Vue.

I ended up adding my own ref to the Vue object, and manually calling a function on click to show the modal.

Example below, for anyone else who comes across this.

```
const vue2 = new Vue({
    el: '#vue2',
    data: function() {
        return {
            modalShow: false
        }
    },
    methods: {
        showModal() {
            this.$refs.myModal.show()
        }
    },
    render() {
        return(
            <div>
                <b-btn on-click={this.showModal}>Show Modal</b-btn>
                <b-modal ref="myModal">
                    Hello From My Modal!
                </b-modal>
            </div>
        )
    }
});
```

**Comment by emanuelmutschlechner** [comment]
Hi @DaleMckeown 
the `render` function does not work this way, you should take a look at the documentation.

Use the `template` property like my example does
https://codesandbox.io/s/qkjj7x482q

**Comment by DaleMckeown** [comment]
Hi @emanuelmutschlechner 

Thanks for the information and the example. I've re-read the Vue `render` docs but I can't see anything to suggest that this wouldn't be possible in `render`. If you could point me in the right direction that would be greatly appreciated.
