### ISSUE TITLE
Need a better documentation of "How to override variables in bootstrap"? 

### ISSUE THREAD

**Issue by vairamsvsjdo** [bootstrap-vue/bootstrap-vue#1690]
using ttps://github.com/bootstrap-vue/webpack sample generated

added the following 
`<template>
  <div class="appmenu">
    <b-navbar toggleable="md" type="dark" variant="primary">

    <b-navbar-toggle target="nav_collapse"></b-navbar-toggle>

    <b-navbar-brand href="/index">Home</b-navbar-brand>

    <b-collapse is-nav id="nav_collapse">

      <b-navbar-nav>
        <b-nav-item href="/appwizard">Register Application in Azure AD </b-nav-item>
      </b-navbar-nav>

      
      <b-navbar-nav class="ml-auto">
        <b-nav-item-dropdown right>
          
          <template slot="button-content">
            <em>User</em>
          </template>
          <b-dropdown-item href="#">Signout</b-dropdown-item>
        </b-nav-item-dropdown>
      </b-navbar-nav>

    </b-collapse>
  </b-navbar>
    <span class="red">{{ menumsg }}</span>
    junk
  </div>
</template>

<style>
bg-primary {
  background-color: #3f3f3f!important;
} 
</style>
`
works but not

`
<style>
.bg-primary {
  background-color: #3f3f3f;
} 
</style>
`

How to do this without !important 

how to override primary such that all values of $primary in bootstrap are replaced since bootstrap-vue recommends to use css files and components and variant components

Also,
Need a better documentation with example of how to override variants than explained here:
https://bootstrap-vue.js.org/docs/reference/color-variants/

**Comment by warlord0** [comment]
If you're using something like webpack to compile your assets then you just need to change the values in your _variables.scss to your colours.

**Comment by robcresswell** [comment]
Can you fix the highlighting in your issue post? It's quite hard to read. 

In terms of theming, the easiest thing to do is import your variables globally in webpack. For me this looks like

```js
rules: [
  {
    test: /\.vue$/,
    loader: "vue-loader",
    options: {
      loaders: {
        scss: "vue-style-loader!css-loader!sass-loader?data=@import './src/scss/variables.scss';",
        preserveWhitespace: false
      }
    }
  }
  ...
]
```

**Comment by robcresswell** [comment]
No response in a month so I'm closing this.

**Comment by Glideh** [comment]
There is something I still don't understand here.
I'm guessing instead of doing that in our js:

**script.js**
```javascript
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';
```

We should import bootstrap sass files just after our variables overrides.
So I'm expecting something like that:

**script.js**
```javascript
import './bootstrap-custom.scss';
```

Our **bootstrap-custom.scss** containing our overrides then the required bootstrap sass

```sass
@import "bootstrap-custom-variables";
@import "~bootstrap-vue/scss/bootstrap";
@import "~bootstrap-vue/scss/bootstrap-vue";
```

However I don't see any sass file in the `bootstrap-vue` module.
Surely I'm getting it wrong.

How can we compile bootstrap without the original sass files ?

**Comment by Glideh** [comment]
Let me answer to myself:

If I import this way, here is what I can rather do:

**script.js**
```javascript
import './bootstrap-custom.scss';
import 'bootstrap-vue/dist/bootstrap-vue.css';
```

**bootstrap-custom.scss**
```sass
@import "bootstrap-custom-variables";
@import "~bootstrap/scss/bootstrap";
```

Since `bootstrap` is a dependency of `bootstrap-vue` we can still gather it's files directly from it

**Comment by SimonFricker** [comment]
+1
