### ISSUE TITLE
Tabs change order when using v-if on tabs

### ISSUE THREAD

**Issue by Keroxo** [bootstrap-vue/bootstrap-vue#1691]
Component: `<b-tab>`

Description:
The order of the tabs changes if you hide tabs with v-if and then show them again.

I use Mac OS High Sierra. 
Tested in Chrome 64, Firefox 58 and Safari 11

Bootstrap-Vue Version 2.0.0-rc.2

JSFiddle: https://jsfiddle.net/hw25s943/15/

Edit: Retested with Version 2.0.0-rc.6. Issue still exists

**Comment by Diaskhan** [comment]
You could use template tag !
This work for me !
<div id="app">
<b-button @click="toggleTabs">Toggle tabs</b-button>
  <b-tabs>
  <template v-if="showTabsOneAndTwo">
    <b-tab  title="Tab 1" >
      Tab Contents 1
    </b-tab>
    <b-tab v-if="showTabsOneAndTwo" title="Tab 2">
      Tab Contents 2
    </b-tab>
    </template>
<template v-else>    
    <b-tab  title="Tab 3">
      Tab Contents 3
    </b-tab>
    <b-tab title="Tab 4">
      Tab Contents 4
    </b-tab>
 </template>
  </b-tabs>
</div>

**Comment by Diaskhan** [comment]
I find a second solution U must use tag **key** to save order! 
```

<div id="app">
<b-button @click="toggleTabs">Toggle tabs</b-button>
  <b-tabs>
    <b-tab v-if="showTabsOneAndTwo" title="Tab 1" active key="1">
      Tab Contents 1
    </b-tab>
    <b-tab v-if="showTabsOneAndTwo" title="Tab 2" key="2">
      Tab Contents 2
    </b-tab>
    <b-tab v-if="!showTabsOneAndTwo" title="Tab 3" key="3">
      Tab Contents 3
    </b-tab>
    <b-tab v-if="!showTabsOneAndTwo" title="Tab 4" key="4">
      Tab Contents 4
    </b-tab>
  </b-tabs>
</div>
```

If the second solution is fixing youre issue U could close issue ?

**Comment by Keroxo** [comment]
Thank you for pointing that out. I knew you should use the key attribute for v-for. I didn't realize that for b-tab. 

Possibly one could refer to it in the documentation to b-tab more clearly. The only clue is in the example code for dynamic tabs. The attribute is also not listed as a property for b-tab in the component reference.

**Comment by Diaskhan** [comment]
Its not a feature that must implement the boostrap vue! Its functional of rendering vuejs! 
If its ok u could close issue!

The boostarp vue builded over vuejs ! 
And vuejs is new! Nobody know documentation fully! The key behaviour by default of vuejs functionality!

**Comment by kmshelke** [comment]
Hi,

I am facing same issue, when using <b-tabs>. The hidden tab is rendered as the last tab. It should be displayed as per the original index.

The solution provided by you is not working. 

the sample code is https://jsfiddle.net/c9k0p3jw/1/

Am I missing something here?

**Comment by Diaskhan** [comment]
@kmshelke 
Create new issue! and describe whole topic! It seems something broken in new version!

**Comment by tmorehouse** [comment]
It might be how b-tabs is checking for new tabs, and then creating the top tab list.  Are you using the title slot, or the title prop on your b-tabs?  It is possible that the order of the new taps is not being reported in document order (i.e. using `this.$children` rather than a DOM query).

**Comment by grtjn** [comment]
Please reopen, issue is described well above, but not solved. As pointed out, key solution does not work, and likely never did. None of the fiddles work correctly, not with latest (rc11), nor when retrofitting rc2..

**Comment by tmorehouse** [comment]
Tabs were never meant to have reactive titles (since they are child components, and the titles need to appear in the parent component). Nor to have any markup other than basic inline HTML elements (i.e. `<b>`, `<i>`, `<em>`.

IMHO, We might just have to undo all that for now.  Tab buttons (the links that control the which tab is currently showing) are just that... they are supposed to be links and nothing else... they are navigation components (navigating local in page content).

**Comment by grtjn** [comment]
@tmorehouse Not sure I follow. We are talking about the order of the tab buttons, not about them having inline elements. I personally think that, particularly for navigation, order needs to be predictable, and stable, otherwise end users would get really confused..

**Comment by grtjn** [comment]
Workaround: use v-show instead..

**Comment by tmorehouse** [comment]
The addition of the usage of the `title` slot (and trying to make it reactive) has introduced this issue of the tab order

**Comment by rrelmy** [comment]
Can this be reopened?

Neither `:key` nor `v-show` fix the problem.

**Comment by bernhardh** [comment]
I am on `"bootstrap-vue": "^2.0.0-rc.13"` from february now but still having the issue.
