### ISSUE TITLE
Typo in documentation (b-table)

### ISSUE THREAD

**Issue by punk1ecrabbz** [bootstrap-vue/bootstrap-vue#1692]
Hello.

I think I've found a typo on docs site.

https://bootstrap-vue.js.org/docs/components/table/#event-based-refreshing-of-data

In "Event based refreshing of data" sction it says:

> this.$root.$emit('**bv::table::refresh**', 'my-table');

But it is not working. Nothing happens on emit.

I've found this in your wiki:
https://github.com/bootstrap-vue/bootstrap-vue/wiki/Bootstrap-Vue-$root-events#listened-to-by-components

"Listened to by components" says we can emit **bv::refresh::table** on $root to refresh tables. 
And it is working as expected.

**Comment by Homas** [comment]
Faced the same issue.

**Comment by Diaskhan** [comment]
Friends there need documentation clearance ! It's better to drop down the documentation wiki ! There must be only one source of true! When there true in two places then gonna be problems !

**Comment by pi0** [comment]
Is wiki correct or docs?

**Comment by Diaskhan** [comment]
Oh sorry the wiki is right by the word of punk1ecrabbz! There gonna be desynchronization problem when have two sources of true ! I guesse need to disable wiki editing in future !

**Comment by pi0** [comment]
@Diaskhan if you could make a PR for correcting the docs that would be awesome! Will then deprecate the wiki.

**Comment by Diaskhan** [comment]
There many others isues that only needs some explanaytion! I think only 35 procents of issues have improvement key! Others issue is support and misunderstood!
