### ISSUE TITLE
Using custom directives with components

### ISSUE THREAD

**Issue by storageddd** [bootstrap-vue/bootstrap-vue#1693]
Hi, guys!

Can i use custom directives with bootstrap vue components?
For example i want: `<b-form-input my-directive />`, but it doesn`t work.

**Comment by robcresswell** [comment]
I thiiink this should work fine, although the Vue docs state that directives are generally for plain elements (I've not seen examples of them used on components, just HTML5 elements) and you've ignored the issue template so I can't really help you.

**Comment by storageddd** [comment]
> I thiiink this should work fine, although the Vue docs state that directives are generally for plain elements (I've not seen examples of them used on components, just HTML5 elements) and you've ignored the issue template so I can't really help you.

Maybe you right. Hovewer, how can i to add custom functional to bootstrap-vue components? :)

**Comment by storageddd** [comment]
@robcresswell, i found solution. It so simple — need use `v-` prefix when add directive to component or DOM-element. And all works fine. :)
