### ISSUE TITLE
HTML inside <b-tab> "title" attribute is rendered as if <pre>

### ISSUE THREAD

**Issue by humblecoder** [bootstrap-vue/bootstrap-vue#1694]
- OS:  MacOS 10.12.6
- Browser: Chrome Version 65.0.3325.162 (Official Build) (64-bit)
- Bootstrap-Vue: 2.0.0-rc.2

I can no longer place HTML inside the `title` attribute of `<b-tab>`s.  It simply renders the plain text.   I was hoping that [this](https://github.com/bootstrap-vue/bootstrap-vue/issues/740) issue would have helped, but it didn't.  Hopefully I'm missing something simple.

Downgrading to 1.5.1 still works.

**Comment by robcresswell** [comment]
Use the documented title slot: https://bootstrap-vue.js.org/docs/components/tabs#add-custom-content-to-tab-title

The feature you were using before was removed over security concerns IIRC.

**Comment by pi0** [comment]
Please reopen if necessary :)

**Comment by humblecoder** [comment]
Aaaaand months later (apologies) . . . .  I never got this working.  I actually downgraded to 1.x.x.  Trying 2.0.0-rc11 now, but running into the same issue.  Do I need to install something like `fortawesome/fontawesome-svg-core` to render them on the fly?  Otherwise, I'm still getting the `<pre>`-style rendering.  😖
