### ISSUE TITLE
how to get a ready-to-deploy css-js compliled

### ISSUE THREAD

**Issue by ppsirg** [bootstrap-vue/bootstrap-vue#1695]
how to get a ready-to-deploy css-js compliled, i need a folder of statics doing it without having to use npm or grunt or any javascript package manager, how do i get that without use npm or grunt or any other?

**Comment by robcresswell** [comment]
Use unpkg: https://unpkg.com/bootstrap-vue@2.0.0-rc.2/dist/

**Comment by robcresswell** [comment]
@ppsirg If this is solved, would you mind closing the bug?
