### ISSUE TITLE
Using with Nuxt causes errors with CSS sourcemaps

### ISSUE THREAD

**Issue by developius** [bootstrap-vue/bootstrap-vue#1698]
I wasn't sure where to open this issue, but I thought that here was probably the best place.

I'm using Bootstrap-Vue (thank you for creating it, awesome stuff!) with Nuxt and I'm encountering some behaviour which I don't really know how to resolve. When I load a page of the app such as `/club/my-club`, there are multiple requests sent because Chrome attempts to load a CSS source map from a relative location. Here is the Nuxt log:

```
  nuxt:render Rendering url /users/finnian +17ms
  nuxt:render Data fetching /users/finnian: 70ms +0ms
  nuxt:render Rendering url /users/bootstrap.css.map +808ms <-- oops!
```

This causes the entire page to break, because it's loaded in the same context (probably wrong terminology), and Nuxt throws a server error because it attempts to call an external API with `boostrap.css.map` as a user ID.

See [my comment on nuxt/nuxt.js#2710](https://github.com/nuxt/nuxt.js/issues/2710#issuecomment-365544852) for some more info.

My knowledge of webpack is very basic and therefore I'm not entirely sure how to fix this. If anyone has any suggestions I'd be very grateful!

**Comment by Steve525** [comment]
@developius I'm seeing the exact same issue. I'm on `1.4.0` and using `bootstrap-vue` version `1.3.0`.  Seems to only happen with nested children pages.

**Comment by developius** [comment]
Yeah it is, I wasn't sure where to open. Will close in favour of the nuxt one seeing as that's where the problem resides.

**Comment by aarcoraci** [comment]
While we wait we can disable source maps:
  cssSourceMap: false
In the build section of nuxt.config.js
