### ISSUE TITLE
<b-form-select>: prompt prop 

### ISSUE THREAD

**Issue by KonradHEXANT** [bootstrap-vue/bootstrap-vue#1699]
It would be grate to have prop for "prompt" option text, that (if filled) adds itself as first, disabled option (with value of null) to the select list.

Right now we need to "inject" prompt into options data every time:
`{ value: null, text: 'Choose your poison!', disabled: true}`

It could be done more efficient with your help :)

**Comment by Diaskhan** [comment]
Konrad could show what u want?
What did trying to achive ? 

Could tell the use case of this scenario!

If it popular scenario then it could be added in standart functional!

**Comment by tmorehouse** [comment]
Rather than injecting a value into your options data, add an `<option ...>...</option>` in the slot `first`:

```html
<b-form-select v-model="selected" :options="options">
  <template slot="first">
    <!-- this slot appears above the options from the 'options' prop -->
    <option :value="null">-- Please select an option --</option>
  </template>
</b-form-select>
```

Now you wont need to mangle your `options` array.
