### ISSUE TITLE
Feature Request: Ability to set set float on a button

### ISSUE THREAD

**Issue by brightertools** [bootstrap-vue/bootstrap-vue#1701]
Eg float-left and float-right.

For instance in a modal having some button float to each side helps with separating buttons

**Comment by robcresswell** [comment]
You should be able to do this with bootstraps existing utility classes; see https://getbootstrap.com/docs/4.0/utilities/spacing/

I don't think we should have anything specific in the buttons for doing this, since it's handled by columns or manual spacing already.

**Comment by robcresswell** [comment]
Closing as there has been no further response for over 3 weeks.
