### ISSUE TITLE
Dynamically disable/re-enable sorting

### ISSUE THREAD

**Issue by curtjenk** [bootstrap-vue/bootstrap-vue#1703]
I'm trying to create a custom header component that will provide column specific filtering.  This will require adding an input element in the HEAD_* slot.  The problem is I don't know how to disable sorting.  Currently if the user hits the enter key when focused on the input element, sorting is triggered.  I want to disable this behavior.

**Comment by tmorehouse** [comment]
add a `keydown.enter.stop=""` handler on your input element.
