### ISSUE TITLE
(b-table) Is there any way to wrap each <td> content to a custom wrapper?

### ISSUE THREAD

**Issue by punk1ecrabbz** [bootstrap-vue/bootstrap-vue#1707]
Hello.
I'm seeking for the way to wrap all <td>'s values into a custom wrapper element.
For example, current table html contains:
`<tr> <td>value</td>      <td>value</td>      <td>value</td> </tr>`

But I need this:
`<tr>  <td><span class="wrap">value</span></td>       <td><span class="wrap">value</span></td>
      <td><span class="wrap">value</span></td>   </tr>`

I understand that I can use slots or formatter callbacks, but they require me to describe every single field of all available fields in my fields object, which is not an option. I have a large amount of different fields and some off them have their own formatters depending on field type.

Maybe there is some option like "td-wrapper" or some wildcard-slot like below?
`<template slot="*any-field*" slot-scope="data">`

**Comment by tmorehouse** [comment]
This m,iht be an option, for fallback to a general scoped slot.  Possibly a scoped slot called `"DEFAULT"`

**Comment by tmorehouse** [comment]
you can also create scoped slots on the fly (by binding the slot name to a variable, i.e. the key from the fields array) such as `<template :slot="columnKeName" ... >`
