### ISSUE TITLE
Default `sort-compare` function in documentation is misleading

### ISSUE THREAD

**Issue by Morgul** [bootstrap-vue/bootstrap-vue#1709]
The default `sort-compare` function from https://bootstrap-vue.js.org/docs/components/table#sort-compare-routine is given as follows:

```javascript
if (typeof a[key] === 'number' && typeof b[key] === 'number') {
  // If both compared fields are native numbers
  return a[key] < b[key] ? -1 : (a[key] > b[key] ? 1 : 0)
} else {
  // Stringify the field data and use String.localeCompare
  return toString(a[key]).localeCompare(toString(b[key]), undefined, {
    numeric: true
  })
}
```

_However_, if you try to use that, it will run, but anything other than numbers will sort equal to each other. This is because, `window.toString()` is a function, and therefore valid, except it doesn't do what you would expect at all:

![image](https://user-images.githubusercontent.com/770655/38042129-1ecc665a-3279-11e8-9d6b-52a06aae9570.png)

The key here is that the documentation fails to include the `toString` function used in the code:

```javascript
function toString (v) {
  if (!v) {
    return ''
  }
  if (v instanceof Object) {
    return keys(v)
      .map(k => toString(v[k]))
      .join(' ')
  }
  return String(v)
}
```

It took me about an hour to work out that was the problem, when I was building a default case for my sort compare based off the default (but running through the `formatter` functions first, if they existed).

**Comment by bobzurad** [comment]
This tripped me up too. Thanks for posting.

**Comment by yugen** [comment]
Thanks.  This helped me out a lot.
