### ISSUE TITLE
Textarea with v-model.trim not allowing any whitespace between characters

### ISSUE THREAD

**Issue by jblotus** [bootstrap-vue/bootstrap-vue#1710]
Here is an example of the issue. Using a plain text area with v-model trim works as expected.

https://jsfiddle.net/c59x746s/3/

To reproduce just start typing in either box and add spaces between letters. You will see the bootstrap-vue component erases anywhitespace while the native textarea does not.

**Comment by emanuelmutschlechner** [comment]
Can confirm.

This issue applies to `b-form-input` as well. Trim does not work as expected:
https://jsfiddle.net/h8qnx4du/1/

Text in input field will not be modified by trim. Whitespaces in the component's `localValue` will be reduced to max. one space. However `v-model` propagates the correct trimmed value.

**Comment by emanuelmutschlechner** [comment]
I think `v-model` is completely broken in all form components. The official [modifiers](https://vuejs.org/v2/guide/forms.html#Modifiers) do not work as expected.

We need a fix for this.

**Comment by jpicton** [comment]
I have noticed the issue with `v-model.trim` on `b-input` too. Leading spaces are trimmed once a non-whitespace character is entered, but trailing spaces are **not** trimmed on input blur (this is what seems to happen for normal `<input>` tags with `v-model.trim`).

Are these bugs currently being looked at?

**Comment by nomarlo** [comment]
I confirm is still present and also in the b-form-input. v-model.trim doesn't work.

**Comment by assembledadam** [comment]
+1

**Comment by vallettea** [comment]
+1

**Comment by tmorehouse** [comment]
In the Vue repo, they suggest that the `v-model` modifiers do not work with custom components:
https://github.com/vuejs/vue/issues/8431#issuecomment-401318598

I just built the following bare-bones mockup in the playground, and can verify that trim modifier does have unexpected behaviours:

```html
<text-area id="foo" v-model.trim="value"></text-area>
<pre>"{{ value }}"</pre>
```
```js
{
  components: {
    textArea: {
      render: function(_h) {
        return _h('textarea', {
          directives: [{ name: 'model', rawName: 'v-model', value: this.value, expression: 'value' }],
          domProps: { value: this.value },
          on: { input: (e) => { this.$emit('input', e.target.value) } }
        })
      },
      model: { prop: 'value', event: 'input' },
      props: { value: '' }
    }
  },
  data: { value: '' }
}
```

Vue appears to do a bit of trickery to handle the v-model modifiers when placed on native inputs (compared to components), to minimize the amount of cursor jumping.

On a regular input bound to a v-model, `$el._vModifiers` will be an object comtaining keys for each modifier in use, while on customer components, the root element has an empty object in `_vModifiers` even though modifiers may be in use.  So basically it is almost impossible for a custom component to be able to detect what modifiers are currently in use.

So this is more of an upstream issue (with Vue), and not directly a Bootstrap-Vue issue.

**Comment by tmorehouse** [comment]
An alternative than using the `.trim` modifier, you could create a computed prop that returns the value trimmed so that the v-model value is not affected.

**Comment by tmorehouse** [comment]
Not really... depends on how you implement it.  If you create a form as a sub component, and the forms state is stored in the data, you could use a computed prop to trim that data entry bound to the textarea,

```html
<template>
  <div>
    <b-form-text-area v-model="text" @input="$emit('input', value)"></b-form-textarea>
    <b-form-checkbox v-model="checked" @change="$emit('input', value)">
      Check me
    </b-form-checkbox>
  </div>
</template>
<script>
export default {
  data () {
    return {
      text: '',
      checked: false
    }
  },
  computed: {
    textTrimed () {
      return this.text.trim()
    },
    value: {
      // Computed prop used as the v-model of this component
      get () {
        return {
          text: this.text.trim(),
          checked: checked
        }
      },
      set (val) {
        this.checked = Boolean(val.checked)
        this.text = val.text === this.textTrimmed ? this.text : val.text
      }
    }
  }
}
</script>
```

Maybe this is something we could incorporate in `<b-form-textarea>` and `<b-form-input>` as boolean modifier props (i.e. `as-trimmed` and `as-number`) as an alternative to the `v-model` modifiers.

**Comment by assembledadam** [comment]
Indeed you can apply a computed property to data, but the lack of re-usability here makes this unhelpful for real-world use cases, such as:
a) a situation where you need to trim v-model inputs on more than one component/element in your project
b) a situation where you are iterating (using v-for) and wish to trim an item of that object.

As such, what you propose would be much better!

**Comment by tmorehouse** [comment]
Ideally, this issue should be "fixed" in VueJS.  They do have a pull request for supporting `v-model.lazy` which has been partially approved. But it would be great if they supported `.number` and `.trim`

But as an interim fix, we could add in support for `trim` and `number` props for modifying how the result is returned to the `v-model` (although `.number` support would be a bit silly on textarea, but useful on input)

**Comment by superern** [comment]
i'm still having this issue in textarea. it erases whitespaces as soon as i type in the field.

**Comment by tmorehouse** [comment]
This should be addressed in the latest `dev` branch, but note do not use the `.trim` modifier in the new `dev`, but rather use the new `trim` **prop**.  VueJS does not support `.trim` or `.number` modifiers on custom components (only native inputs)

You can take a preview here:  https://deploy-preview-2213--bootstrap-vue.netlify.com/docs/components/form-textarea
