### ISSUE TITLE
2.0.0-rc.4 fix #1680, but breaks 'no-body' of cards

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#1713]
@pi0 Hi.

It seems that [63b35e3](https://github.com/bootstrap-vue/bootstrap-vue/commit/63b35e3) commit breaks cards.

[Kitchen sink Example](https://bootstrap-vue.js.org/docs/components/card/#kitchen-sink-example) shows `Hello World` twice.

[Here](https://jsfiddle.net/eywraw8t/6091/) is one more example where we can see 2 texts for header and footer.

Also I would add to Change Log 2.0.0-rc.4 a note that the above mentioned commit fix #1680 . I spent 1.5 hours to find out that after updating bootstrap-vue to rc4 I need to update vue from 2.5.15 to 2.5.16, because the commit above does not work with Vue 2.5.15.

**Comment by pi0** [comment]
Thank you @TitanFighter.  nobody problem should be resolved with rc.5.
