### ISSUE TITLE
form-textarea on input get an error "this is null" at the line "this.localValue=evt.target.value"

### ISSUE THREAD

**Issue by xcchcaptain** [bootstrap-vue/bootstrap-vue#1714]
the error appears in firefox for the latest version of bootstrap-vue.
the 2.0.0-rc.2 worked properly

**Comment by pi0** [comment]
Hi @xcchcaptain. Would you please share a reproduction with JSFiddle?

**Comment by pi0** [comment]
Fixed in rc.6.
