### ISSUE TITLE
feature request: change hash when changing tabs

### ISSUE THREAD

**Issue by vesper8** [bootstrap-vue/bootstrap-vue#1716]
Hi there! Currently in all my projects I'm using https://github.com/spatie/vue-tabs-component

The main reason I love this package is because it has the built-in feature to change the window.location.hash when you switch tabs, and then when you load a page with a hash already set in the url, it defaults to that tab automatically (demo here http://vue-tabs-component.spatie.be/)

what I don't like about it is that it it's compatible with bootstrap-responsive-tabs which makes the tabs into accordion on smaller devices, which is why I'd like to switch to a standard bootstrap implementation such as this one

is there any chance you might add this functionality or is it completely out of scope for what you're doing here?

**Comment by qkdreyer** [comment]
Any updates on this guys ?

**Comment by emanuelmutschlechner** [comment]
It could be a useful feature. We could implement it and only activate it when a special property is set

**Comment by vesper8** [comment]
if it helps, this is how I currently handle adding this functionality. Works with vue-bootstrap tabs

```
      Bus.$on('bootstrap_tab_support', () => {
        // show active tab on reload
        if (location.hash !== '') {
          setTimeout(() => {
            // console.log(`switching to tab ${location.hash}`);
            $(`a[href="${location.hash}"]`)[0].click();
          }, 100);
        }

        // remember the hash in the URL without jumping
        $('a[role="tab"]').on('click', (e) => {
          // console.log('tab clicked', `${$(e.target).attr('href').substr(1)}`);
          if (history.pushState) {
            history.pushState(
              null,
              null,
              `#${$(e.target)
                .attr('href')
                .substr(1)}`,
            );
          } else {
            location.hash = `#${$(e.target)
              .attr('href')
              .substr(1)}`;
          }
        });
      });
```

In my previous implementation (using bootstrap v3) I was doing a 
```
            $(`a[href="${location.hash}"]`).tab('show');
```

instead, but I found that this doesn't work anymore with v4

I'm also having to add a tiny timeout in order for this to work every time.. which is annoying.. so this is not the most elegant solution.. just something that might help you guys come up with the best way

```
  mounted() {
    setTimeout(() => {
      Bus.$emit('bootstrap_tab_support');
    }, 100);
  }
```

The other thing I want to add to this is "responsive bootstrap tab" support.. same as what https://github.com/vtimbuc/bootstrap-responsive-tabs used to provide.. basically turning tabs into accordions on mobile

I've identified code that should do the trick in this codepen https://codepen.io/dferenc/pen/YYyjYJ and will be trying to add it in shortly.. is this also something you guys would consider putting in as an optional ?

**Comment by Diaskhan** [comment]
By the way this feature must be optional, It could break a router component!

**Comment by lbineau** [comment]
Any news about this feature? I'm looking for it too 👍

**Comment by qkdreyer** [comment]
Using $root changed::tab event :

```js
this.$root.$on('changed::tab', (tabs, tabIndex, tab) => {
  if (window.history) {
    window.history.replaceState(null, null, tab.href);
  }
});
```

**Comment by lbineau** [comment]
@qkdreyer thanks for your anwser (I'll probably handle it with a hash since the component is used in a CMS). What about initial state e.g. http://mydomain.com/page.html#tab1 ?

**Comment by qkdreyer** [comment]
```html
<b-tab
  v-for="(tab, index) in tabs"
  :key="index"
  :title="tab.title"
  :active="hash ? hash === tab.href : index === 0"
  :href="tab.href"
>
```

```js
```

**Comment by lbineau** [comment]
@qkdreyer Neat thank you !

**Comment by tmorehouse** [comment]
`b-tabs` are meant for use on "on-page" content (local, no routing/URL change).  If routes are to change,it would be best to build your markup as cards with navs.

**Comment by DM2489** [comment]
@tmorehouse Do you know of an example implementation for this suggestion?

**Comment by tmorehouse** [comment]
@DM2489 

```html
<template>
  <b-card no-body>
    <b-card-header>
      <b-nav tabs class="card-header-tabs">
        <b-nav-item to="#" :active="$route.hash !== '#foo' && $route.hash !== '#bar'">
          Default
        </b-nav-item>
        <b-nav-item to="#foo" :active="$route.hash === '#foo'">
          Foo
        </b-nav-item>
        <b-nav-item to="#bar" :active="$route.hash === '#bar'">
          Bar
        </b-nav-item>
      </b-nav>
    </b-card-header>
    <b-card-body v-show="$route.hash !== '#foo' && $route.hash !== '#bar'" >
      Default Tab
    </b-card-body>
    <b-card-body v-show="$route.hash === '#foo'">
      Foo Tab
    </b-card-body>
    <b-card-body v-show="$route.hash === '#bar'">
      Bar Tab
    </b-card-body>
  </b-card>
</template>
```

Or if using `<router-view>` see this fiddle: https://jsfiddle.net/u2j9yevm/
