### ISSUE TITLE
Typescript support -feature request

### ISSUE THREAD

**Issue by ChristianRiedl** [bootstrap-vue/bootstrap-vue#1718]
In my opinion it is quite important to support Typescript. Unfortunately I am not experienced enough to create the Typescript definitions files.

**Comment by ChristianRiedl** [comment]
I was able to to integrate **bootstrap-vue** in a ASPNET/Core project using the **Webpack** based template as described in http://www.dotnetcurry.com/aspnet/1383/modern-web-dev-aspnet-core-webpack-vuejs. But I had to use an ugly type cast. 

I added this **index.d.ts** in the **bootstrap-vue/es directory** : 

```
import {PluginObject} from 'vue';
export declare const VuePlugin : PluginObject<{}>;

```
than I was able to integrate it in the boot.ts file ; 

```
import './css/site.css';
import Vue, { PluginObject } from 'vue';
import VueRouter from 'vue-router';
import VuePlugin from 'bootstrap-vue/es';
Vue.use(VueRouter);
var pi: PluginObject<{}> = <any>VuePlugin;
Vue.use(pi);
```
Maybe somebody is able to improve my type definition to work without the cast.

**Comment by pi0** [comment]
Basic typings are available now: https://github.com/bootstrap-vue/bootstrap-vue/pull/1721
