### ISSUE TITLE
Playground: CSS area

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#172]
@pi0 , how about to add CSS editor area to Playground?
Example use case: 
I wanted to test localisation by custom css in input-file and can't because i cant set css in playground, and can't export to JSFiddle as it use actual build of library.

**Comment by pi0** [comment]
@mosinve Yes we can do it by injecting `<css>` tags to template string before render..

**Comment by pi0** [comment]
Closing as seems no one is volunteer adding this feature :)) Feel free to reopen if has priority.
