### ISSUE TITLE
boostrap-vue in cordova app

### ISSUE THREAD

**Issue by devMls** [bootstrap-vue/bootstrap-vue#1722]
Hi.

I follow this guide for create smartphone app with vue and cordova.

https://itnext.io/make-hybrid-platform-cordova-vue-webpack-2fb7031c4f9b

all work fine but when i install boostrap vue with 

npm i bootstrap-vue

I find two issues:

first of all in npm run dev, static files not be found. (before to install bootrap-vue, there was fine.

at second when i change css loaders vue css and boostrap css tell me:

hese dependencies were not found:

* bootstrap-vue/dist/bootstrap-vue.css in ./src/main.js
* bootstrap/dist/css/bootstrap.css in ./src/main.js

To install them, you can run: npm install --save bootstrap-vue/dist/bootstrap-vue.css bootstrap/dist/css/bootstrap.css

any suggestion?

**Comment by robcresswell** [comment]
Its a little hard to tell what you're doing without showing code. It sounds to me like you're adding lines to your src/main.js to look for the bootstrap css files, and then not installing them. The error message tells you to install them. You should follow the error message 😀

**Comment by robcresswell** [comment]
Closing as there has been no further response from the bug author.
