### ISSUE TITLE
Table export array

### ISSUE THREAD

**Issue by cdmoro** [bootstrap-vue/bootstrap-vue#1724]
Hi, the Bootstrap Vue table is one of the best data table I've seen for Vue. The only thing that I love to do is the ability to export the data.
I don't want you to make this feature. I only ask if the table component could create an array with all the items formatted and ready to export to another formats.
Now, the table has one computer array called 'computedItems' that contains the visible items of one page. I think in an array called 'computedItemsRaw' with all the items formatted and with a ref attribute we can access.

I hope you can understand me,
thanks.

**Comment by Diaskhan** [comment]
The exporting of data is not functional of js-table!
U could do this functional by yourself!

What other formats do talking about?
the data of boostrap vue is simple json data!

there got two ways. Data on client ! simple table-page.
And data on server ! If u wanna export data u must realize it on serverside!

The paging of table is need on WEB for minimize data when fetching data from the server !
The functionallity of vue-table DO NOT MUST PROVIDE fetching all data from the server ! 
U could fetch all data, and set paging to none. But its not gonna be fast.

See the docs https://bootstrap-vue.js.org/docs/components/table#pagination

Good scenario is realize some api that fetch all data that u wanna export! Then js code send ajax query and saves to file, or by clicking on url php script returns to U  a file
see link https://www.the-art-of-web.com/php/dataexport/


**Topic could be closed for now!**

**Comment by cdmoro** [comment]
Hi, I already have the export functionallity. All I want to have is the json formatted. Let's see, I have a JSON data and I pass it to the table, and in the table I create a few slots, slots that transform my original data
Par exemple, a date, in my orignial json data I have the date with the format "YYYY-MM-DD..." and in the table I set it to "DD/MM/YYYY", if I wanna to export the table I have to make again the transform the date creating a new json data with all the formatting.
Do you see the problem? I already have the export, I made with pdfmake, what I don't have is the json data with the format I put in the slots. The only solution is to make a new json array with the data formatted when a user do a click on the export button.
The same thing happend when I change the sort of the table, I'm pushed to mantain two json data (the original and the new json array, with the formatted data).
The table it's simply awesome, is the best table for vue that I ever seen, and I now the export of data is not a core thing of table, but It would really good have, at least, a json formatted, if you know another solution I'm glare to read it.
Thanks

**Comment by pi0** [comment]
@cdmoro Thanks for your kind words. Although I'm sure we can achieve what you want with some dirty hacks I think the most "Vue"ish way would be using a computed property in the wrapper component (which is using `<b-table>`) and directly passing formatted JSON for both exporter and table component. 

Mixing internal component state which is used for rendering with other things is an anti-pattern. BootstrapVue may change it's internal behaviour and that will break your project.

**Comment by Diaskhan** [comment]
Ure talking about theese products ! 
https://en.m.wikipedia.org/wiki/SQL_Server_Reporting_Services

https://community.jaspersoft.com/project/jasperreports-library

http://www.oracle.com/technetwork/middleware/reports/overview/index.html

There overwhelms vue-table actually!
There need very many time to make universal solution! Try to use ready solution and tools for reporting! 

Table-vue is  just visual component! Not library that provides reporting services!

**Comment by cdmoro** [comment]
I understand you, guys. It's just a visual component. I'll figure out...
Thanks!
