### ISSUE TITLE
Textarea needs @changed property

### ISSUE THREAD

**Issue by SignalDancer** [bootstrap-vue/bootstrap-vue#1725]
Windows 10
Chrome 65
BootStrap Vue 2.0.0-rc6

Vue itself supports both change and input events (non native) that work identical to the input element for <textarea>
Bootstrap Vue should support the same thing (add @changed).

Currently the event isn't available and this is a bit of a pain when trying to integrate with vuelidate correctly and not pickup changes that are caused by code, only user input.

**Comment by SignalDancer** [comment]
Workaround is to use a change.native v-on listener.

**Comment by emanuelmutschlechner** [comment]
This issue can be closed as this is expected behavior and documented. See section "Events" in the [docs](https://bootstrap-vue.js.org/docs/components/form-textarea).
