### ISSUE TITLE
Add colspan support to b-table

### ISSUE THREAD

**Issue by Kevenvz** [bootstrap-vue/bootstrap-vue#1726]
Can't really describe it more than the title does.

**Comment by Diaskhan** [comment]
Yes !
There have colspan for headers and for rows ! What exactly do U need ?

There some litle information about 
https://bootstrap-vue.js.org/docs/components/table#table-colgroup

**Comment by robcresswell** [comment]
@Diaskhan is correct. It's not terribly well documented but I think that slot provides what you're asking for.

**Comment by Diaskhan** [comment]
Actually on this question good answer could give @tmorehouse  !

**Comment by Renari** [comment]
Does anyone have an example of how to do this? I've tried to following based on what was said here but this doesn't seem to work as intended.

```js
      <template slot="slot1 slot2 slot3" slot-scope="data">
        I span 3 columns
      </template>
```

Here's a codepen example of what I tried: https://codepen.io/Renari/pen/ejKdeL

**Comment by tmorehouse** [comment]
Colspan support inside b-table component would be awkward to implement (as b-table is expecting rows that have the same length of elements).

colgroup might be an option, but support varies from browser to browser.

**Comment by cbeloni** [comment]
Here is an example:

`<template slot="table-colgroup">
                    <col span="1" style="background-color:red">
                    <col style="background-color:yellow">
 </template>`
