### ISSUE TITLE
Events (keyup & change)

### ISSUE THREAD

**Issue by Hanyuusha** [bootstrap-vue/bootstrap-vue#1727]
**version - v2.0.0-rc.6** 
**change**

```
<template>
  <div>
    <b-form-select v-model="selected" :options="options" class="mb-3" />
    <b-form-select v-model="selected" :options="options" class="mb-3" size="sm" @change="log(selected)" />
    <div>Selected: <strong>{{ selected }}</strong></div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      selected: null,
      options: [
        { value: null, text: 'Please select an option' },
        { value: 'a', text: 'This is First option' },
        { value: 'b', text: 'Selected Option' },
        { value: {'C': '3PO'}, text: 'This is an option with object value' },
        { value: 'd', text: 'This one is disabled', disabled: true }
      ]
    }
  },
  methods: {
    log (val) {
      console.log(val)
    }
  }
 }
</script>
```
![default](https://user-images.githubusercontent.com/17995677/38607057-25ed96b6-3d91-11e8-84e6-33f72efab924.png)
As you see, model in template change correct, but in console log old value.

**keyup**

```
<template>
  <div>
    <b-form-input v-model="text1"
                  type="text"
                  placeholder="Enter your name"
                  @keyup.enter="log('b-form-input')"></b-form-input>
<input v-model="text1"
                  type="text"
                  placeholder="Enter your name"
                  @keyup.enter="log('simple input')"/> 
<p>Value: {{ text1 }}</p>
  </div>
</template>

<script>
export default {
  data () {
    return {
      text1: ''
    }
  },
  methods: {
    log (val) {
     console.log(val);
   }
  }
 }
</script>
```
**keyup** works only in simple input.

**Comment by Hanyuusha** [comment]
**@keyup.enter.native** - works perfectly, thx.
But what do with **@change** ?

**Comment by emanuelmutschlechner** [comment]
@Hanyuusha try this one:
```html
<b-form-select v-model="selected" :options="options" class="mb-3" size="sm" @input="log" />
```
You don't have to pass `selected` to the callback function because this event emits the selected value. This event is triggered emitted when `localValue` of the component changes. 

See `node_modules/bootstrap-vue/es/components/form-select/form-select.js` line 66 and 49 or `node_modules/bootstrap-vue/src/components/form-select/form-select.js` line 74 and 56.

**Comment by Hanyuusha** [comment]
**@input**  - works perfectly, thx.

**Comment by emanuelmutschlechner** [comment]
@Hanyuusha You're welcome. Please close the issue.

**Comment by edwh** [comment]
I'm seeing this on v2.0.4.  If I use the mouse to select a value, then events fire, but if I use the arrows and enter they don't.  The input event and keyup/down/press events don't work for me either.  Perhaps I'm missing something?
