### ISSUE TITLE
Popover component ignores second offset value when giving two values to offset prop

### ISSUE THREAD

**Issue by wintrykiddo** [bootstrap-vue/bootstrap-vue#1728]
MacOS 10.13.3
Google Chrome 65.0.3325.181
bootstrap-vue 2.0.0-rc.6

```
<button id="share" class="btn">Share</button>
<b-popover
    :no-fade="true"
    content="This is the share text."
    placement="top"
    offset="20 -20"
    target="share"
    triggers="click"
/>
```

This popover only receives +20px offset to its X position but not -20px to its Y position. I've also tried comma-separation like `offset="20,-20",` but the component consistently ignores the second value in the offset string, making it impossible to influence the Y offset position.

**Comment by jackmu95** [comment]
Closed by #1728.
