### ISSUE TITLE
Form select

### ISSUE THREAD

**Issue by Soraia55** [bootstrap-vue/bootstrap-vue#173]
Hi! 
How can I show a default text on the form before user selects any option? Instead of appearing empty?

**Comment by pi0** [comment]
Hey @Soraia55 :)
Thanks for noticing that i just forgot updating [JSFiddle Example](https://jsfiddle.net/pi0/b4bg7d24/) to do this we can simply add another option with value of `null`) + setting our initial model's value to `null`

**Comment by Soraia55** [comment]
Thanks for the quick answer @pi0!

**Comment by mosinve** [comment]
i'd make it disabled also :)

**Comment by pi0** [comment]
@mosinve  Sometimes disabled should not be used (ex user wants selecting nothing :D)
Anyway i agree we need adding more form-options props support including `selected` `hidden` and `class`

**Comment by tornography** [comment]
Hi,

I know this issue is closed for some time now, but I can't find the option for "hidden".
It's jut not handled inside the component. Would be very usefull for those first options that say
"select option" and the like.

Regards,
Manuel

**Comment by tmorehouse** [comment]
Best option, is to create the first option is your list as null+disabled:

```js
options: [
 { value: null, text: 'Select an option', disabled: true },
 { value:: 'a', text: 'Option a' },
 { value:: 'b', text: 'Option b' },
 { value:: 'c', text: 'Option c' }
]
```

http://vuejs.org/v2/guide/forms.html#Select
