### ISSUE TITLE
Problem with Tooltip position 

### ISSUE THREAD

**Issue by 50l3r** [bootstrap-vue/bootstrap-vue#1732]
Hi guys,

I have a problem with tooltip positions:

```
<div class="col">
    <div class="form-group">
        <label>IVA <span v-b-tooltip.hover title="I'm a tooltip!"><i class="zmdi zmdi-help"></i></span></label>
        <input type="text" class="form-control" v-model="config.IVA" placeholder="IVA">
    </div>

    <b-btn v-b-tooltip.hover title="I'm a tooltip!">Hover Me</b-btn>
</div>
```

[![https://gyazo.com/db5e587049a86a17d5a1e53d705f5385](https://i.gyazo.com/db5e587049a86a17d5a1e53d705f5385.gif)](https://gyazo.com/db5e587049a86a17d5a1e53d705f5385)

Tooltip not positioning at center at all. Other example:

```
<td class="actions text-center">
    <a @click="set_mailer(item)" v-b-tooltip.hover title="Enviar por email" class="m-r-10"><i class="fa fa-envelope"></i></a>

    <router-link :placement="'bottom'" id="edit" :to="{ name: 'facturas_view', params: { id: item._EntityId }}" class="m-r-10" v-b-tooltip.hover title="Editar"><i class="zmdi zmdi-edit zmdi-hc-lg"></i></router-link>

    <a :href="url[index]" target="_blank" v-b-tooltip.hover title="Descargar PDF" class="m-r-10"><i class="fa fa-file-pdf"></i></a>

    <a :href="url_word[index]" target="_blank" v-b-tooltip.hover title="Descargar Word" class="m-r-10"><i class="fa fa-file-word"></i></a>

    <a @click="reload(index)" target="_blank" v-b-tooltip.hover title="Actualizar" class="m-r-10"><i class="zmdi zmdi-refresh zmdi-hc-lg"></i></a>

    <a @click="status_factura(item)" v-b-tooltip.hover :title="item._EntityStatus==1 ? 'Suspender' : 'Activar'" class="m-r-10"><i class="zmdi" :class="item._EntityStatus==1 ? 'zmdi-lock' : 'zmdi-lock-open'"></i> </a>

    <a @click="del_factura(item._EntityId)" v-b-tooltip.hover title="Eliminar"><i class="zmdi zmdi-delete"></i></a>
</td>
```

[![https://gyazo.com/351ebecb7cfd2c1c8235e0cb602f2d89](https://i.gyazo.com/351ebecb7cfd2c1c8235e0cb602f2d89.gif)](https://gyazo.com/351ebecb7cfd2c1c8235e0cb602f2d89)

**Comment by 50l3r** [comment]
Same problem with right positioning:

[![https://gyazo.com/f1a8a600c205e637afc5d666153130fe](https://i.gyazo.com/f1a8a600c205e637afc5d666153130fe.gif)](https://gyazo.com/f1a8a600c205e637afc5d666153130fe)

**Comment by emanuelmutschlechner** [comment]
@50l3r 
This is a know issue ([bootstrap](https://github.com/twbs/bootstrap/issues/25013) and [popper](https://github.com/FezVrasta/popper.js/issues/457)) in Popper.js.

For details check comments of the linked issues. Possible fix via CSS:
```css
.tooltip { top: 0; }
```
> Background: The value of `top` will be overridden depending by the settings used by Popper.js, if `gpuAcceleration` is set to `false` it will be replaced with the top offset of the popper, if set to `true`, it will stay set to `0`.

**Comment by 50l3r** [comment]
Much thanks. Problem solved :)

**Comment by emanuelmutschlechner** [comment]
@50l3r You're welcome :) would you mind closing the issue?

**Comment by 50l3r** [comment]
Yes, it works

**Comment by vikrampariharcodereadr** [comment]
Use chaining methods
`v-b-tooltip.hover.bottom="'ToolTip!'"`

**Comment by nurulid** [comment]
> Use chaining methods
> `v-b-tooltip.hover.bottom="'ToolTip!'"`

Thanks

**Comment by webcoderkz** [comment]
With click it doesn't work properly, for example:

```
v-b-toolptip.click.top="'text!'"
```

It sometimes shows on top, sometimes on bot, is it intended?

**Comment by minaseem** [comment]
Below css hack worked for me 
`.b-tooltip:not([style*='transform']) {
  top: 0;
}`
