### ISSUE TITLE
bug or feature, the tabs panel have focus ?

### ISSUE THREAD

**Issue by Diaskhan** [bootstrap-vue/bootstrap-vue#1733]
I'am using last version !
```
<link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap/dist/css/bootstrap.min.css" />
<link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.css" />
<script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>
```
And see this screenshot
![image](https://user-images.githubusercontent.com/15046677/38764714-e82a7eec-3fd5-11e8-94cd-483858298915.png)

There a focus on tab, it is a bug, or feature! In standart tabs of boostrap4 no focus!
If this a feature how could disable, to make it not focusable.
For Design perspective is not good looking !
I'm using last chrome !

**Comment by Diaskhan** [comment]
I see this issue is duplicate 
https://github.com/bootstrap-vue/bootstrap-vue/issues/1044

https://stackoverflow.com/questions/9152096/how-to-make-an-html-element-non-focusable
Could tabindex be optional when creating component ??

**Comment by emanuelmutschlechner** [comment]
@Diaskhan 
The :focus style is defined in standard Bootstrap styles. Use this piece of CSS to suppress styling:
```css
.tabs ul.nav-tabs:focus {
    outline: none;
}
```

If you want to disable the focus feature completely use this directive to override `tabindex` of the tab component:
```html
<b-tabs v-no-tab-focus>
    <b-tab title="first">
        <br>I'm the first fading tab
    </b-tab>
    <b-tab title="second" active>
        <br>I'm the second tab content
    </b-tab>
    <b-tab title="disabled" disabled>
        <br>Disabled tab!
    </b-tab>
</b-tabs>
```
```js
Vue.directive('no-tab-focus', function(el) {
    const ul = el.querySelector('ul.nav[tabindex="0"]');
    if (typeof ul !== 'undefined') {
        ul.tabIndex = -1;
    }
});
```

**Comment by Diaskhan** [comment]
In standart tabs of boostrap 4 no focusable elements on ul tag! There only on li element! 
https://getbootstrap.com/docs/4.0/components/navs/

The focusable is feature of boostrap vue !
Thats why i'am telling its not standart functional of boostrap4. 

I guesse it's must be optional !
Boostrap4 it only css layout! Boostarp vue is very very big framework ,it is not a simple css layout!

**Comment by Diaskhan** [comment]
Emanuel what u offer, i some kind of hack, monkey patching is not good way  for frameworks ! We talking about 1 hack, what if gonna be 5-15 monkey patching!  The framework must be fully functional and solid ! Ruby and rails have the way of monkey patching, when standarts is few, there gonna be problems to support that techology!

**Comment by Diaskhan** [comment]
Look at https://github.com/bootstrap-vue/bootstrap-vue/issues/394
Tmorehouse created a standart for table vue fetching data by ajax!

**Comment by emanuelmutschlechner** [comment]
I created a pull request to restore the original Bootstrap behavior

**Comment by Diaskhan** [comment]
Emanuel how could I test new version ?
**I want to close issue !**

**Comment by emanuelmutschlechner** [comment]
Until it is available via unpkg or npm you can use this [bootstrap-vue.js](https://gist.github.com/emanuelmutschlechner/dbd646c97e718e55fe559f0d3d037e01) file.

In your template simply add `no-key-nav` to `<b-tabs>` e.g.
```html
<b-tabs no-key-nav>
  <b-tab title="first" active>
    <br>I'm the first fading tab
  </b-tab>
  <b-tab title="second" >
    <br>I'm the second tab content
  </b-tab>
  <b-tab title="disabled" disabled>
    <br>Disabled tab!
  </b-tab>
</b-tabs>
```

**Comment by Diaskhan** [comment]
Thank U. And the last questions.
1. When it gonna be release ?
2.Could U add **no-key-nav** to documentation ?

**Comment by emanuelmutschlechner** [comment]
I think in a few weeks the pre-release will be available at [unpkg](https://unpkg.com/bootstrap-vue@2.0.0-rc.7/dist/bootstrap-vue.js)

Documentation will look like this
![capture](https://user-images.githubusercontent.com/27734375/38794000-cecb5e9c-4153-11e8-87b3-694ba74df74a.PNG)
![capture](https://user-images.githubusercontent.com/27734375/38794058-0c616b34-4154-11e8-9c61-f42a6c02759e.PNG)

**Comment by Diaskhan** [comment]
Look gorgeous !

**Comment by pi0** [comment]
@emanuelmutschlechner @Diaskhan If nothing unusual happens will release next RC today.

**Comment by Diaskhan** [comment]
Friends this https://github.com/bootstrap-vue/bootstrap-vue/issues/1691 could be closed now!
