### ISSUE TITLE
TypeScript definitions in 2.0.0-rc.7

### ISSUE THREAD

**Issue by FantasticFiasco** [bootstrap-vue/bootstrap-vue#1741]
It seems that there is a problem with the TypeScript definitions in the 2.0.0-rc.7 release:

```
ERROR in .../searchlight/node_modules/bootstrap-vue/src/index.d.ts
[tsl] ERROR in .../searchlight/node_modules/bootstrap-vue/src/index.d.ts(9,41)
      TS1005: '{' expected.
```

You can see the complete build log [here](https://travis-ci.org/FantasticFiasco/searchlight/jobs/367075194).

**Comment by pi0** [comment]
@FantasticFiasco Please open a PR for fix.

**Comment by pi0** [comment]
Fixed in RC.8
