### ISSUE TITLE
disabled property in Button component accepts string value.

### ISSUE THREAD

**Issue by dany0502** [bootstrap-vue/bootstrap-vue#1750]
## System Information
OS: OS X El Capitan version 10.11.6
Browser: Google Chrome 65.0.3325.181（Official Build） （64 bit）
bootstrap-vue: 2.0.0-rc.8",

## Description
Hi
According to the [bootstrap-vue document](https://bootstrap-vue.js.org/docs/components/button) `disabled` property accepts only boolean values. But there is a case that `disabled` property accepts `string` value. 

### Test Code
```js
<template>
  <b-button
    :disabled="disable">Button</b-button>
</template>

<script>
import Vue from 'vue';
import bButton from 'bootstrap-vue/es/components/button/button';

Vue.component('b-button', bButton);

export default {
    data() {
        return {
            disable: 'disabled',
        };
    },
};
</script>
```
### Result
No errors in console
### Expected Result
Expect to output this kind of error message ?
```
[Vue warn]: Invalid prop: type check failed for prop "disabled". Expected Boolean, got String.
```

**Comment by emanuelmutschlechner** [comment]
We could set the prop type to accept anything, as Vue docs state:
```html
<button v-bind:disabled="isButtonDisabled">Button</button>
```
If `isButtonDisabled` has the value of `null`, `undefined`, or `false`, the `disabled` attribute will not even be included in the rendered `<button>` element.

**Comment by dany0502** [comment]
@emanuelmutschlechner 
Thanks for your reply. And I'm sorry I didn't explain very well. So I rewrite the issue. According to the bootstrap-vue document, I saw button component accepts only `Boolean` values. 
<details>
  <summary>
    bootstrap-vue document
  </summary>
  <img width="646" alt="2018-04-19 16 53 54" src="https://user-images.githubusercontent.com/3010139/38978463-751abcb6-43f2-11e8-8e5c-7af1d3fb2107.png">
</details>


So when I set `String` value in `disabled` property, I expected to see warnings in console. But actually the behavior looks a little strange. When I set `"disabled"` or `""` to the property no warnings are output in console. But when I set `"true"` or `"false"`, I saw some warnings in console. Following are my test code. It's not BootstrapVue related issue ?

## Case 1

```js
<template>
  <b-button
    :disabled="disable">Button</b-button>
</template>

<script>
import Vue from 'vue';
import bButton from 'bootstrap-vue/es/components/button/button';
Vue.component('b-button', bButton);
export default {
    data() {
        return {
            disable: 'disabled',
        };
    },
};
</script>
```
### Result
No warning in console

## Case 2

```js
<template>
  <b-button
    :disabled="disable">Button</b-button>
</template>

<script>
import Vue from 'vue';
import bButton from 'bootstrap-vue/es/components/button/button';
Vue.component('b-button', bButton);
export default {
    data() {
        return {
            disable: '',
        };
    },
};
</script>
```
### Result
No warning in console

## Case 3

```js
<template>
  <b-button
    :disabled="disable">Button</b-button>
</template>

<script>
import Vue from 'vue';
import bButton from 'bootstrap-vue/es/components/button/button';
Vue.component('b-button', bButton);
export default {
    data() {
        return {
            disable: 'true',
        };
    },
};
</script>
```
### Result
```
[Vue warn]: Invalid prop: type check failed for prop "disabled". Expected Boolean, got String.
```

## Case 4

```js
<template>
  <b-button
    :disabled="disable">Button</b-button>
</template>

<script>
import Vue from 'vue';
import bButton from 'bootstrap-vue/es/components/button/button';
Vue.component('b-button', bButton);
export default {
    data() {
        return {
            disable: 'false',
        };
    },
};
</script>
```
#### Result
```
[Vue warn]: Invalid prop: type check failed for prop "disabled". Expected Boolean, got String.
```

**Comment by dany0502** [comment]
@emanuelmutschlechner 
I appreciate your explanation. I understand this is Vue specification and it's not a bootstrap-vue related problem.
