### ISSUE TITLE
:min :max property on b-input type="number" is ignored when 0 is passed

### ISSUE THREAD

**Issue by tarreislam** [bootstrap-vue/bootstrap-vue#1751]
Hello.

If you set `:min` or `:max` is set to 0 it will have no effect on `type="number"`

Example:
 `<b-form-input type="number" :min="0" :max="23"></b-form-input>`  will allow a max of 23 and ignore :min=""

However if you pass `:min` or `:max` as strings, it will work as intended but then Vue will throw `[Vue warn]: Invalid prop: type check failed for prop "min". Expected Number, got String`

im @ `2.0.0-rc.8`

**Comment by emanuelmutschlechner** [comment]
Created a pull request for it #1752

**Comment by emanuelmutschlechner** [comment]
@Diaskhan this was fixed and can be closed
