### ISSUE TITLE
/oracledb/lib/oracledb.js - Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by snehaljoshi72** [bootstrap-vue/bootstrap-vue#1753]
When I try to use oracledb,  I am getting compile warning and not able to run the application

**Comment by mosinve** [comment]
and how this connected to Bootstrap-vue?

**Comment by snehaljoshi72** [comment]
When I run stand-alone  node function, It is running fine but not with Bootstrap-vue.

**Comment by robcresswell** [comment]
This is unrelated to Bootstrap-Vue. It seems to be a bug specific to your build.

**Comment by Diaskhan** [comment]
@snehaljoshi72  could U provide ure demo project ?
To reproduce ?
