### ISSUE TITLE
Carousel SetTimeout on sliding

### ISSUE THREAD

**Issue by Anis-EDT** [bootstrap-vue/bootstrap-vue#1754]
Hello ,
I've been trying to use bootstrap-vue carousel and it works perfectly but i'd like to disable sliding left and right for a few seconds ( the person wil have to stay on that slide for 10 secs for example )
is that possible ? thank you

**Comment by thanhdd** [comment]
@Anis-EDT 

You can set :interval="10000" in b-carousel tag.

**Comment by Diaskhan** [comment]
@Anis-EDT ure trying to sad that u want interval for each slide ? 
Or u just wanna disable sliding by timer ?

**Comment by Anis-EDT** [comment]
I'm trying to disable sliding So intervalle="10000" won't do it

**Comment by Anis-EDT** [comment]
I'm trying to disable sliding So intervalle="10000" won't do it

**Comment by Diaskhan** [comment]
**Set interval to Zero !**
This code works !
Friends issue could be closed!
Solution is working!

```
<template>
  <div> 
    <b-carousel id="carousel1"
                style="text-shadow: 1px 1px 2px #333;"
                controls
                indicators
                background="#ababab"
                :interval="minterval"
                img-width="1024"
                img-height="480"
                v-model="slide"
                @sliding-start="onSlideStart"
                @sliding-end="onSlideEnd"
    >

      <!-- Text slides with image -->
      <b-carousel-slide caption="First slide"
                        text="Nulla vitae elit libero, a pharetra augue mollis interdum."
                        img-src="https://lorempixel.com/1024/480/technics/2/"
      ></b-carousel-slide>

      <!-- Slides with custom text -->
      <b-carousel-slide img-src="https://lorempixel.com/1024/480/technics/4/">
        <h1>Hello world!</h1>
      </b-carousel-slide>

      <!-- Slides with image only -->
      <b-carousel-slide img-src="https://lorempixel.com/1024/480/technics/8/">
      </b-carousel-slide>

      <!-- Slides with img slot -->
      <!-- Note the classes .d-block and .img-fluid to prevent browser default image alignment -->
      <b-carousel-slide>
        <img slot="img" class="d-block img-fluid w-100" width="1024" height="480"
             src="https://lorempixel.com/1024/480/technics/5/" alt="image slot">
      </b-carousel-slide>

      <!-- Slide with blank fluid image to maintain slide aspect ratio -->
      <b-carousel-slide caption="Blank Image" img-blank img-alt="Blank image">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
          eros felis, tincidunt a tincidunt eget, convallis vel est. Ut pellentesque
          ut lacus vel interdum.
        </p>
      </b-carousel-slide>

    </b-carousel>

    <b-button variant="success" v-on:click="stop">Not Disabled</b-button>

    <p class="mt-4">
      Slide #: {{ slide }}<br>
      Sliding: {{ sliding }}
    </p>

  </div>
</template>

<script>
export default {
  data () {
    return {
      slide: 0,
      sliding: null,
      minterval:2000,
    }
  },
  methods: {
    onSlideStart (slide) {
      this.sliding = true
    },
    onSlideEnd (slide) {
      this.sliding = false
    },
    stop () {
      this.slide=1;
      this.minterval = 0;
    }
  }
}
</script>
<!-- carousel-1.vue -->
```

**Comment by Anis-EDT** [comment]
sorry i think i didn't explain my problem clearly
basicly the user is on slide 1 and it's impossible for him to go to slide 2 (until 10 seconds pass for example)

**Comment by Diaskhan** [comment]
@Anis-EDT  what kind information is it ?
U re trying to make test system?  with question and answers?
What role have slider in ure app ???

**Comment by Anis-EDT** [comment]
my client has delegates that present his products to different companies he wants him to stay at least a minutes in certain slides so that he doesn't forget important details

**Comment by emanuelmutschlechner** [comment]
@Anis-EDT see my example below
https://codesandbox.io/s/vv8jxnl9k7

**Comment by robcresswell** [comment]
@Anis-EDT Set `controls` to `false` and `interval` to `0` to make the carousel freeze on a slide. Then just use standard JS utilities like `setTimeout` to toggle them.

@Diaskhan Please don't demand an issue be closed until either some time has passed or the original author has said they are happy 😇

**Comment by robcresswell** [comment]
Ah @emanuelmutschlechner gave a more detailed example. Nice work.

**Comment by emanuelmutschlechner** [comment]
@robcresswell this will only work partially, as keyevents and indicators are still working

**Comment by robcresswell** [comment]
@emanuelmutschlechner Indicators are disabled by default, but you're correct about key events. I'd forgotten carousel even supported them, its not a component I use often. Good catch.

**Comment by robcresswell** [comment]
Oh, actually I think the key events are tied to the indicator rather than the arrow controls (just been testing), so it should work by just toggling controls on and off I believe.

**Comment by emanuelmutschlechner** [comment]
@robcresswell maybe we should disable key events when both indicators and controls are disabled? Documentation on key navigation is missing completely

**Comment by Anis-EDT** [comment]
@emanuelmutschlechner works perfectly thank you , you are a life savior

**Comment by bimalraj91** [comment]
is there a  way  to set different slide intervals in b-carousel vue.js
