### ISSUE TITLE
How to hide OK or Cancel buttons on Modal?

### ISSUE THREAD

**Issue by iamvitali** [bootstrap-vue/bootstrap-vue#1757]
Hi,
In the docs it says:
> You can customize the size of the buttons, disable buttons, hide the Cancel button (i.e. OK Only), choose a variant (e.g. danger for a red OK button) using the ok-variant and cancel-variant props, and provide custom button content using the ok-title and cancel-title props, or using the named slots modal-ok and modal-cancel.

The "hide the Cancel button (i.e. OK Only)" part gave me hope that I won't have to replace the footer slot with just one "Cancel" button and could just.... put something in the `ok-variant` ??? Like `ok-variant="hidden"`? Not sure, there doesn't seem to be anything on that page that says how to exactly hide one of the buttons. :man_shrugging:

**Comment by emanuelmutschlechner** [comment]
Currently there is no such option as `cancel-only`. But it is very easy to achieve this behavior by using the ok button as cancel button. See my example below
```html
<b-btn v-b-modal.modal1 variant="primary">Launch demo modal</b-btn>

<b-modal id="modal1" title="Bootstrap-Vue" ok-only ok-variant="secondary" ok-title="Cancel">
      <p class="my-4">Hello from modal!</p>
</b-modal>
```

**Comment by Diaskhan** [comment]
Actually there standart buttons for messagebox 
OkOnly         = &H000000
     OkCancel       = &H000001
     AbortRetryIgnore   = &H000002
     YesNoCancel    = &H000003
     YesNo          = &H000004
     RetryCancel    = &H000005
     CancelTryContinue  = &H000006

But for modal windows has no standart! 
I guesse the footerbar of dialog must provide custom buttons! 

The other problem is there somebody needs only ok-cancel! Other needs another buttons! But in all cases modal windows is to confirm something in the web! In desktop    usage could be other brhavior!

**Comment by robcresswell** [comment]
The okay and cancel buttons are just defaults; both are overriden if you use the modal-footer slot for custom behaviour. @Diaskhan @iamvitali Bootstrap-Vue can only cover so many cases :)

**Comment by sumrakx** [comment]
Add property in `b-modal` component.
`hide-footer="true"`

**Comment by BRVK** [comment]
just place this at b-modal
hide-footer

**Comment by jameskandau** [comment]
> Add property in `b-modal` component.
> `hide-footer="true"`

but as of version Currently v2.0.0-rc.25 it requires a boolean ie hide-footer

**Comment by tmorehouse** [comment]
or `v-bind:hide-footer="true"` (or `:hide-footer="true"`)

**Comment by akimlyubchenko** [comment]
You can create custom footer like this and manage 'close' & 'ok' buttons state
```html
<b-modal 
  :title="title"
  @ok="onSubmitClick"
>
  <slot></slot>
  <template #modal-footer="{ cancel, ok }">
    <b-button 
      :variant="cancelButton.variant"
      @click="cancel"
    >
      {{ cancelButton.title }}
    </b-button>
    <b-button
      v-if="okButton.isShown"
      :variant="okButton.variant"
      :disabled="!formData.isValid"
      @click="ok"
    >
      {{ okButton.title }}
    </b-button>
  </template>
</b-modal>
```

```javascript
export default class ButtonInfo {
	constructor(onClickHandler) {
		this.onClickHandler = onClickHandler;
	}

	get title() {
		return this._title;
	}
	set title(value) {
		this._title = value;
	}

	get isShown() {
		return this._isShown;
	}
	set isShown(value) {
		this._isShown = value;
	}

	get variant() {
		return this._variant;
	}
	set variant(value) {
		this._variant = value;
	}

	get isDisabled() {
		return this._isDisabled;
	}
	set isDisabled(value) {
		this._isDisabled = value;
	}

	onClickHandler() { }
}
```

**Comment by greeven** [comment]
> or `v-bind:hide-footer="true"` (or `:hide-footer="true"`)

This should be documented.

**Comment by akimlyubchenko** [comment]
@greeven it's already exist, check carefully properties:
https://bootstrap-vue.js.org/docs/components/modal

**Comment by greeven** [comment]
Oh.. I could swear that I checked that page exactly as I just did (STRG+F "hide-footer") and nothing showed up. Now I see it to.
My mistake. Sorry. And thanks for the quick response.

**Comment by m-demydiuk** [comment]
Hi guys. Do you plan to add prop to hide ok button? It would be usefull in my case, because when form in modal is submitted, I need to show success message and hide submit(ok) button, so only close button will be showed. And I don't want to override footer, do not see any sense to do it, because it will be the same code as default.

**Comment by tmorehouse** [comment]
You can change the text of the `ok` button dynamically (as well as it's variant).

I would just switch the text/variant as needed.

**Comment by JalanshMunshi** [comment]
We can hide the buttons by using their properties -  `cancelButtonProps` and `okButtonProps`.

If you do not want to display buttons in the footer at all, then it would be better to just set the `footer` prop to `null`.

```<Modal footer={null} />```

If you want to display just a single button, then you can use their properties and set the `display` to `none`. In my case, I wanted to hide the `Cancel` button. 

```cancelButtonProps={{ style: { display: 'none' } }}```

However, do keep the `onCancel` method so that you can hide the modal when you click on the `X` at the top right corner.

**Comment by okosodovictor** [comment]
:hide-footer="true"
