### ISSUE TITLE
Can we have tdAttr accept function parameter for dynamic attr value?

### ISSUE THREAD

**Issue by andrewpros** [bootstrap-vue/bootstrap-vue#1758]
The title says it all.
Yeah, i wanted a computed title based on row item data on td cell, but tdAttr doesn't allow it and i don't really see why it can't just work like tdClass, simple, elegant, consistent.

**Comment by Diaskhan** [comment]
1.Could U provide some code, and why U need this functional ??

2.Vuejs is 2-side binding library!
U could define behavior of components and bind them to data property ?
Why u not want to bring this logic to template ?

**Comment by andrewpros** [comment]
U are asking the wrong question, why do u need code for such simple thing, is there something not clear, it doesn't matter why i need it, it matters only that i need it and others might too, and every time there is a need to add some computed attribute on the td tag there is currently no direct way.

Do i really need to explain why i need to add dynamic attribute on td tag? It is basic stuff. Basic stuff should be supported out of the box. Asking me this is like asking why we need tdClass too.

Developers want and need to add dynamic classes on td tags, and the same goes for attributes.

I don't need a template, i need to add title attr on td tag, that changes based on data.

With vue this is no brainier <td :title="item.title">, but with <b-table> component there is no simple way, and why is that?

**Comment by Diaskhan** [comment]
1.Could U show what U want by screenshot ?

2.There have support of tdclass, why its not satisfy U ? See the doc !
https://bootstrap-vue.js.org/docs/components/table#field-definition-reference

**Comment by andrewpros** [comment]
1. Why there is a need for a screenshot, i don't get it? What u want see on it? As i stated already i want to add a title attribute to a td cell in b-table component for some fields and this is a value computed based on constantly changing data, items are constantly updated by ajax.
As we all know b-table component doesn't work like normal table, it generates it markup on its own so i cant do it as i have it done with html table and raw vuejs with v-for on tr and simple `<td :title="item.title">` inside it.

2. Well i have already read the docs, i wouldn't ask for it before that, i already also use tdclass on the same cells, it is not that it doesn't satisfy me, but a class is not a title attribute, class isn't supposed to be used as a text information container and only a title attribute have a hover ability so that a client can see the information on title attribute in a tooltip shown by browsers, that is the main point, to see that data on hover, but this is obvious.

Frankly i don't see a reason we have separate tdClass and tdAttr options, a class is also an attribute, so we could really just merge those to a single tdAttr option that returns attributes list, be it class or title or whatever attribute someone wants and with the functionality of current tdClass, to use String or Array or Function for every attribute, conditional classes, title changes, all i one place.

**Comment by emanuelmutschlechner** [comment]
@andrewpros Check my example below. `tdAttr` is working as expected for static data. If you want to customize the table markup for specific cells you should check out [scoped slots](https://bootstrap-vue.js.org/docs/components/table/#header-footer-custom-rendering-via-scoped-slots) in the docs. 

I created an example with a workaround for what you're trying to accomplish. Check the implementation of `first_name`:
https://codesandbox.io/s/k1ov2w2463

**Comment by andrewpros** [comment]
Yeah i know it works for static data and i know about scoped slots.

Thank u for the demo.
So basically u are proposing to wrap every field i want to have a dynamic title attribute in additional div or span with this attribute and not on that td directly?

Well ok, this is a working solution, cant say otherwise, i still think that giving tdAttr option the functionality of tdClass parameters would be better and more consistent, no need to wrap every field and everything could be configured in a single place, in fields definitions.

It looks somewhat strange that u need to setup basically very similar things with separate method in another place due to tdAttr option limitations that tdClass don't have. Maybe u will reconsider this some day.

But ok, this works.

**Comment by Diaskhan** [comment]
@andrewpros  if its ok u could close issue ))

**Comment by emanuelmutschlechner** [comment]
I created a feature request. Feel free to test it
https://codesandbox.io/s/w7mkpor815

**Comment by emanuelmutschlechner** [comment]
@andrewpros Feature is available in the new RC
