### ISSUE TITLE
Source map error in Firefox

### ISSUE THREAD

**Issue by ldantonov** [bootstrap-vue/bootstrap-vue#1759]
bootstrap-vue always inserts a source map comment (//#) in the compiled JS, which causes the Firefox error message in the Console. Chrome does not report the error.
To get the error, I simply include the b-row component and use it in my own component.
If I add source maps to the build, the error goes away.

I am using Firefox 59.0.2 on Windows 10. Vue is 2.5.16, bootstrap-vue is 2.0.0-rc.8
My project is using laravel-mix and webpack with the default webpack.config.js.

**Comment by robcresswell** [comment]
How are you including the b-row component? If its imported, it should obey your compile process. If its pre-compiled from BV source, then there's not much we can do I think.

**Comment by robcresswell** [comment]
You should be able to edit your webpack config to not generate source maps. I can't find anything in the source related to your issue, so it sounds to me like you may be building source maps yourself in webpack then manually removing them, which will cause a breakage.

**Comment by ldantonov** [comment]
Well, I used laravel-mix to generate my project scaffold, so I'm not writing my own webpack config. Source maps are off in the laravel-mix config (webpack.mix.js). This may be some weird interaction between laravel-mix and bootstrap-vue, but I'm not seeing this issue with any other plugins that I'm using.

**Comment by robcresswell** [comment]
That doesn't really clarify the situation to be honest; like I said in my last comment, I couldn't find anything in our source that looks like a lingering comment, so I've no idea where that's being inserted, and it's not something I've come across in my usage.

**Comment by ldantonov** [comment]
ok, I've set up and attached a plain vanilla project that shows the problem. It is completely empty, aside from including bootstrap-vue. You need to install laravel-mix, cross-env, vue and bootstrap-vue, then run it the see the source map error in the console in Firefox. If you comment out bootstrap-vue, the error goes away. I understand that the root cause of the issue is not clear, however the issue itself is easy to reproduce. I hope this helps.
[test-lar.zip](https://github.com/bootstrap-vue/bootstrap-vue/files/2116756/test-lar.zip)
![image](https://user-images.githubusercontent.com/8513774/41621968-2eebba50-73dc-11e8-9830-ccf3565f387d.png)

**Comment by ldantonov** [comment]
As a final comment, I only see this in the development build, and I assume that was the case with original project where I saw this - I don't remember anymore.

**Comment by tmorehouse** [comment]
Closing as stale
