### ISSUE TITLE
Button with icon

### ISSUE THREAD

**Issue by akubasa** [bootstrap-vue/bootstrap-vue#176]
Dear Team,

I am trying to use b-dropdown item.
But i cannot set an icon as its child. there is only text possible to set. It would be nice to have html or icon support for buttons. I am using vue-awesome icons

**Comment by mosinve** [comment]
Buttons as <b-button> have not-only-text support:
`<b-btn @click="addItem(type)"><i class="fa fa-plus" aria-hidden="true"></i></b-btn>`

**Comment by akubasa** [comment]
OK, Thank you, but how to use it with dropdown?

**Comment by mosinve** [comment]
And Dropdown too:
https://jsfiddle.net/cihkem/butydw3u/

**Comment by akubasa** [comment]
Thank you for your example but you got me wrong I need the dropdown button to be an icon
![unbenannt](https://cloud.githubusercontent.com/assets/6769786/24332880/7a0e85a8-124e-11e7-90f1-f60e6b603df8.PNG)

**Comment by mosinve** [comment]
Yep, sorry :))) Some misunderstanding :)

**Comment by akubasa** [comment]
So, is it possible or will it be implemented?

**Comment by mosinve** [comment]
I updated previous jsfiddle. Please look at it.
https://jsfiddle.net/cihkem/butydw3u/
 Is it what you want?

**Comment by akubasa** [comment]
Very close

There is just a little thing, I need this without the "dropdown-arrow" icon

see my pictures
![unbenannt](https://cloud.githubusercontent.com/assets/6769786/24333182/97e9f030-1253-11e7-9b1d-f17fb7783265.PNG)
![unbenannt2](https://cloud.githubusercontent.com/assets/6769786/24333183/97ec3714-1253-11e7-86a8-cb8790195340.PNG)

**Comment by mosinve** [comment]
"dropdown-arrow" icon depends on Bootstrap's `dropdown-toggle` class. So I'm afraid this all you can do without proper css hacking of Bootstrap style. BTW, you can make your own css based on Bootstrap's and use it instead. Our lib supports this. :)

**Comment by akubasa** [comment]
Okay, thank you. Great support! I will continue integration
