### ISSUE TITLE
How to use bootswatch themes with BoostrapVue

### ISSUE THREAD

**Issue by vairamsvsjdo** [bootstrap-vue/bootstrap-vue#1763]
I am looking for ways to use bootswatch themes with bootstrap-vue and switch theme dynamically during runtime

**Comment by robgallen** [comment]
Not sure how to switch themes dynamically (nor why you would want to), but for a single/set theme, try this.

Save the BootsWatch css locally and replace the main boostrap css import.
```
import Vue from "vue";
import BootstrapVue from "bootstrap-vue";
// import "bootstrap/dist/css/bootstrap.css";
import "@/css/bootstrap.min.css";
import "bootstrap-vue/dist/bootstrap-vue.css";
```

**Comment by robcresswell** [comment]
This is beyond the scope of BootstrapVue. It's here to provide some components with Bootstrap markup, not custom styling etc. 😄 You'll have to look elsewhere for help on dynamically changing CSS in your website.

**Comment by creativehamlet** [comment]
@vairamsvsjdo you may want to use this article as a guide if your still interested https://medium.com/maestral-solutions/coloring-your-app-implementing-live-theming-with-vue-js-and-styled-components-29e428900394
