### ISSUE TITLE
How to use nuxtjs with BootstrapVue

### ISSUE THREAD

**Issue by vairamsvsjdo** [bootstrap-vue/bootstrap-vue#1764]
I am looking for ways to use nuxtjs with bootstrap-vue and generate static site or dynamic server side page rendering.

**Comment by jetrii** [comment]
It's not perfect, but my setup is as follows:

Add the following line to `modules` In `nuxt.conf.js`:  `['bootstrap-vue/nuxt', { css: false }]`
Then in your main SCSS file add `@import "~bootstrap/scss/bootstrap";` to import the bootstrap styles.

**Comment by emanuelmutschlechner** [comment]
Have you checked the documentation?
https://bootstrap-vue.js.org/docs/#nuxt-js

**Comment by robcresswell** [comment]
Closing as there has been no response from bug author, and this is already documented.
