### ISSUE TITLE
Vue bootstrap fix context this

### ISSUE THREAD

**Issue by kostia7alania** [bootstrap-vue/bootstrap-vue#1768]
IF => @dismissed="dismissCountdown = 0" // i got next error:

vue.js:584 [Vue warn]: Property or method "dismissCountdown" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <AppInput>
       <TransitionGroup>
         <AppUpload>
           <Root>

FIX =>  @dismissed="this.dismissCountdown = 0"

===> VUDEO => https://youtu.be/d6xgwIlbECw

**Comment by Diaskhan** [comment]
@kostia7alania  ure not comparing equal to zero.
`"dismissCountdown = 0"`
U're setting to zero !

Try this code  "dismissCountdown == 0" !

**Comment by kostia7alania** [comment]
i want to change  variable dismissCountdown  to zero:)

**Comment by Diaskhan** [comment]
Could  provide code difference, with fix of code ??

**Comment by emanuelmutschlechner** [comment]
https://codesandbox.io/s/4rl0wl6nnx

**Comment by emanuelmutschlechner** [comment]
You have a typo in your code! `dismissCountDown` is not the same as `dismissCountdown`

**Comment by emanuelmutschlechner** [comment]
https://github.com/kostia7alania/vue_doc_uploader_portable/pull/1/files?diff=unified

**Comment by Diaskhan** [comment]
Dear comrad @kostia7alania ! Вы можете нормальным языком объяснить в чем проблема ??

**Comment by emanuelmutschlechner** [comment]
@Diaskhan I already answered and stated the problem https://github.com/bootstrap-vue/bootstrap-vue/issues/1768#issuecomment-383515740

**Comment by Diaskhan** [comment]
@kostia7alania  try check solution that @emanuelmutschlechner  offered !

**Comment by emanuelmutschlechner** [comment]
My demo works just fine. You don't even need `@dismissed` for it to work
https://codesandbox.io/s/4rl0wl6nnx

**Comment by Diaskhan** [comment]
@kostia7alania  у вас проблемы с кодом.

https://learn.javascript.ru/variables#variable-naming
Регистр букв имеет значение
Переменные apple и AppLE – две разные переменные.

**Исправьте проблемы с регистром переменных!**

**Comment by Diaskhan** [comment]
@kostia7alania  тикет закрываем, если что можете заново открыть его,
Но предоставьте рабочий код !
