### ISSUE TITLE
@keyup not working on <b-form-input> and <b-form-textarea>

### ISSUE THREAD

**Issue by emanuelmutschlechner** [bootstrap-vue/bootstrap-vue#1769]
`@keyup` does not work at all on those form components. The plain html equivalents work just fine.

```html
<script>
export default {
  name: 'App',
  data() {
    return {
      value: 'lorem ipsum'
    };
  },
  methods: {
    search: e => window.alert(JSON.stringify(e))
  }
};
</script>
<template>
  <b-form-input v-model="value" @keyup="search"/>
  <b-form-textarea v-model="value" @keyup="search"/>
</template>
```

### Demo
https://codesandbox.io/s/j451yq8685

**Comment by emanuelmutschlechner** [comment]
Initially reported by @RockyF in #1609

**Comment by emanuelmutschlechner** [comment]
@wwwork Yes, that would be possible. `@keyup` provides very useful modifiers.

I think the solution is setting the `.native` modifier in order for the key event to work.

https://codesandbox.io/s/zxynj3jwwp

**Comment by vuphuctho** [comment]
+1. With `@input` or `@change` some keyboard events might not be handled, e.g.  hitting enter on `b-form-input`

https://codesandbox.io/s/7yj14p9wyq

**Comment by emanuelmutschlechner** [comment]
@vuphuctho If you add the `.native` modifier to `@keyup` it should work as expected.

https://codesandbox.io/s/z272r9z4p4
