### ISSUE TITLE
Allow adding custom CSS classes to components like b-nav

### ISSUE THREAD

**Issue by Gallaecio** [bootstrap-vue/bootstrap-vue#177]
The current codebase does not allow to add custom class strings to components like `b-nav`. Hence, it is not possible to align `b-nav`.

If would be nice for you to add a `class` property that can be used to define arbitrary CSS classes to add to the ones that the components handle themselves.

**Comment by pi0** [comment]
@Gallaecio I agree. Will be added in soon :)

**Comment by Gallaecio** [comment]
My bad, it actually works the way it is currently implemented. Awesome!
