### ISSUE TITLE
How to change position nav mobile!

### ISSUE THREAD

**Issue by phucvo0709** [bootstrap-vue/bootstrap-vue#1770]
I want to switch the logo to the left and collapse to the right looking for help

![untitled](https://user-images.githubusercontent.com/35060381/39165160-33b9c5d2-47ad-11e8-9133-aa76be05dab9.png)

**Comment by emanuelmutschlechner** [comment]
@phucvo0709 Just change the order components in your `<b-navbar>`. `<b-navbar-brand>` must be declared before `<b-navbar-toggle>`.

```html
<b-navbar toggleable="md" type="dark" variant="info">
  <b-navbar-brand href="#">NavBar</b-navbar-brand>
  <b-navbar-toggle target="nav_collapse"></b-navbar-toggle>
  <b-collapse is-nav id="nav_collapse">
    <b-navbar-nav>
      <b-nav-item href="#">Link</b-nav-item>
      <b-nav-item href="#" disabled>Disabled</b-nav-item>
    </b-navbar-nav>
  </b-collapse>
</b-navbar>
```

https://codesandbox.io/s/7z752r91z1
