### ISSUE TITLE
Is there a Chinese document?

### ISSUE THREAD

**Issue by ZongDuCha** [bootstrap-vue/bootstrap-vue#1771]
有没有中文文档？

**Comment by ZongDuCha** [comment]
I'm sorry！ Do you have a Chinese document?

**Comment by emanuelmutschlechner** [comment]
@ZongDuCha No, I don't think so

**Comment by pi0** [comment]
@ZongDuCha Sorry we don't have at the moment. But you can fork this repository and start translating `.md` files. I provide you instructions to deploy the docs.

**Comment by Diaskhan** [comment]
I could to translate in russia. 
But bosstrap-vue is always changing ! And docs is changing! If youre translated, some documentation, u must actualize it in other languages! Its very hard support and trace actuall status of translated documents!

**Comment by pi0** [comment]
@Diaskhan This is a common problem with all multi lang docs indeed and that's why I've never started Persian translation myself :D BTW many prefer reading things in their native language. So the option is always available for doing translations :)

**Comment by pi0** [comment]
Closing this. Please ping us if there was any interest.
