### ISSUE TITLE
Getting old v-model object value after @change event in b-form-select 

### ISSUE THREAD

**Issue by iruizeguilaz** [bootstrap-vue/bootstrap-vue#1772]
I have a problem with the event Change. I launch a code that use the v-model that my b-form-select has binded but the value that is ised in the event is the old. I do not get the new value.

I have come accross this old link of another post that speaks about that same issue but without using vue-boostrap, just an example of a select

https://jsfiddle.net/ak51oxfg/2/

.....
<b-form-select @change="onCompanyChange" class="mb-2 mr-sm-2 mb-sm-0" name="size" v-model="idCompany" >
...

 onCompanyChange(){
          console.log(this.idCompany);
}
           

"bootstrap": "^3.3.7"   
"bootstrap-vue": "^2.0.0-rc.6"
"vue": "^2.5.13"
"vuex": "^3.0.0"

**Comment by emanuelmutschlechner** [comment]
I think this relates to https://github.com/bootstrap-vue/bootstrap-vue/issues/1710#issuecomment-383498042

**Comment by iruizeguilaz** [comment]
thank you for awswering so quickly

I have noticed that with a settimeout of only 0,1 I can go on with other things in the meantime (a timeout of 0,1 is barely noticiable but this kind of things are just a temporary stopgap)

 
setTimeout(() => {
                 // my code
              }, 100);

**Comment by whatl3y** [comment]
Noticing this as well, hate to implement a `setTimeout` but might have to in the meantime.

**Comment by iruizeguilaz** [comment]
I implemented the SetTimout with 100 millliseconds and I thought that it could be a temporal solution, and it was with chrome and firefox, but it does not work with explorer. The setimout delays the execution but the value of the variable v-model is not updated no matter the quantity of the timeout I choose...

do you know any other temporal gap or an alternative to use v_model and update the information of the screem with new queries which depends on the value of the v-mode and the onChange eventl?

**Comment by iruizeguilaz** [comment]
i have implemented another way to avoid the problem

i am still using the v-model with the onchage event in my listboxes

but in the onchange methods I reallised that i can get the value changed and asiign to the same variable used in the v-model to be sure that the variable is updated when I want

example:

<b-form-select required @change="onCompanyChange" class="mb-2 mr-sm-2 mb-sm-0" name="size" v-model="companyvalue" >

onCompanyChange(value){
            
               this.companyvalue= value;
               //my code
}
