### ISSUE TITLE
Select language of  a required input text

### ISSUE THREAD

**Issue by iruizeguilaz** [bootstrap-vue/bootstrap-vue#1773]
This is just a question

How can I change de language beetwen 'en' and 'es' of the automatic response messages when I click a submit in a form???

for instance the required and the type email messages:

`   <b-form-input required id="inputEmail"  type="email" v-model="email" ></b-form-input>`

thanks in advance

**Comment by emanuelmutschlechner** [comment]
@iruizeguilaz those messages are browser and operating system specific. Check this link for more information
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation#Customized_error_messages

**Comment by iruizeguilaz** [comment]
ok, thanks

With that I think that I can do a method that is launched in every page in the mounted method, using a mixin global method, where I can loop evey element, and changing all the messages. 

I see that very easy by using the following API and the example you sent me

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#the-constraint-validation-api

**Comment by iruizeguilaz** [comment]
I make it, 
I close the question
