### ISSUE TITLE
<b-table> filtering occurs when row details get toggled -> performance loss,  working with 16k rows

### ISSUE THREAD

**Issue by ddweber** [bootstrap-vue/bootstrap-vue#1774]
Is it a feature or a bug, that the filter-function gets called again for all items when the row details of one row gets toggled? I´m working with a fairly big amount of items (~16k rows) and this behavour slows down the user experience a lot.

I tested the behaviour in the playground area with the following code:

```html
<div id='app'>
  <b-table :items="items" :fields="fields" :filter="filterfct">
    <template slot="show_details" slot-scope="row">
      <!-- we use @click.stop here to prevent emitting of a 'row-clicked' event  -->
      <b-button size="sm" @click.stop="row.toggleDetails" class="mr-2">
       {{ row.detailsShowing ? 'Hide' : 'Show'}} Details
      </b-button>
      <!-- In some circumstances you may need to use @click.native.stop instead -->
      <!-- As `row.showDetails` is one-way, we call the toggleDetails function on @change -->
      <b-form-checkbox @click.native.stop @change="row.toggleDetails" v-model="row.detailsShowing">
        Details via check
      </b-form-checkbox>
    </template>
    <template slot="row-details" slot-scope="row">
      <b-card>
        <b-row class="mb-2">
          <b-col sm="3" class="text-sm-right"><b>Age:</b></b-col>
          <b-col>{{ row.item.age }}</b-col>
        </b-row>
        <b-row class="mb-2">
          <b-col sm="3" class="text-sm-right"><b>Is Active:</b></b-col>
          <b-col>{{ row.item.isActive }}</b-col>
        </b-row>
        <b-button size="sm" @click="row.toggleDetails">Hide Details</b-button>
      </b-card>
    </template>
  </b-table>
</div>
```

```js
  data () {
    return {
      fields: [ 'first_name', 'last_name', 'show_details' ],
      items: [
        { isActive: true, age: 40, first_name: 'Dickerson', last_name: 'Macdonald' },
        { isActive: false, age: 21, first_name: 'Larsen', last_name: 'Shaw' },
        { isActive: false, age: 89, first_name: 'Geneva', last_name: 'Wilson', _showDetails: true },
        { isActive: true, age: 38, first_name: 'Jami', last_name: 'Carney' }
      ]
    }
  },
    methods: {
      filterfct: function(row){
        console.log('filterfct');
        return true;
      }
    }
```

**Comment by ddweber** [comment]
`  <b-table :items="items" :fields="fields" :filter="filterfct">
    <template slot="show_details" slot-scope="row">
      
      <b-button size="sm" @click.stop="row.toggleDetails" class="mr-2">
       {{ row.detailsShowing ? 'Hide' : 'Show'}} Details
      </b-button>
      
      
      <b-form-checkbox @click.native.stop @change="row.toggleDetails" v-model="row.detailsShowing">
        Details via check
      </b-form-checkbox>
    </template>
    <template slot="row-details" slot-scope="row">
      <b-card>
        <b-row class="mb-2">
          <b-col sm="3" class="text-sm-right"><b>Age:</b></b-col>
          <b-col>{{ row.item.age }}</b-col>
        </b-row>
        <b-row class="mb-2">
          <b-col sm="3" class="text-sm-right"><b>Is Active:</b></b-col>
          <b-col>{{ row.item.isActive }}</b-col>
        </b-row>
        <b-button size="sm" @click="row.toggleDetails">Hide Details</b-button>
      </b-card>
    </template>
  </b-table>`

**Comment by ddweber** [comment]
{
  data () {
    return {
      fields: [ 'first_name', 'last_name', 'show_details' ],
      items: [
        { isActive: true, age: 40, first_name: 'Dickerson', last_name: 'Macdonald' },
        { isActive: false, age: 21, first_name: 'Larsen', last_name: 'Shaw' },
        { isActive: false, age: 89, first_name: 'Geneva', last_name: 'Wilson', _showDetails: true },
        { isActive: true, age: 38, first_name: 'Jami', last_name: 'Carney' }
      ]
    }
  },
    methods: {
      filterfct: function(row){
        console.log('filtered');
        return true;
      }
    }
}

**Comment by Diaskhan** [comment]
U must not use 16k rows. U must Use pagination for that!

**Comment by Diaskhan** [comment]
The main problem, that DOM could mutate, nobody tell us that mutation of dom gonna be fast!
The pagination of table is created to minimize transfering data from server  to client!

Why u Use 16k rows? U better use some reporting services to retrive 16k rows. Tables in web is not created to view 16k rows!

**Comment by ddweber** [comment]
I´m only displaying 5 - 50 rows at once (via pagination), thats not the problem. It´s wished that filtering is done on client side and not on the server. Nonetheless my question persits.

**Comment by Diaskhan** [comment]
Filtering is using RegExp. Its not fast ))) The better is realize serverside filtering !
Or try to implement yore custom filtering !

**Comment by ddweber** [comment]
Thanks for your answer but i think you still don´t get my point. In generall the performance is great for my needs, btw. i´m using custom filtering function which stringifies the row.items data for my requirements and its fast enough.

In my opinion the fact that **filtering is triggered when row-details of one row were toggled** is unnecessary because the row details do not affect/mutate the orignal items(array) at all.

**Comment by Diaskhan** [comment]
Is there posibillity to reproduce this on jsfiddle?

**Comment by emanuelmutschlechner** [comment]
@ddweber I can confirm this issue. 

@Diaskhan See my example below
https://codesandbox.io/s/q3onr4p749

**Comment by tmorehouse** [comment]
`_showDetails` is stored in the items array, and the array and all of its values are reactive to changes (including `_showDetails`).  So unfortunately, this will trigger anything that is reacting to the items array (including filtering)

**Comment by tmorehouse** [comment]
Adding a check to see if the only thing changed is `_showDetails` would incur a scan of the entire table data, which would be just as slow (if not slower) than calling the filter routine again. :(

**Comment by Pozee** [comment]
Is there anyway of getting around this? im having the same issue right now.
