### ISSUE TITLE
Add an additional Button type to DropdownItem.

### ISSUE THREAD

**Issue by cynecx** [bootstrap-vue/bootstrap-vue#178]
Hey,

According to the [bootstrap documentation](https://v4-alpha.getbootstrap.com/components/dropdowns/#menu-items) it is also possible to use buttons as dropdown child elements. Right now bootstrap-vue's Dropdown-Item does only support a links (`<a>`).

I was trying to add such button type to the dropdown-item but I wasn't sure how I should add this. The first approach would be to simply add another vue component which I will call `dropdown-item-button` and simply inherit the methods and such from bootstrap-vue's button component. The second idea would be to add a `type` prop to dropdown-item so we can conditionally render them by using v-if.

Any thoughts on this? (I am happy to create a pull request afterwards.)

**Comment by pi0** [comment]
Hey @cynecx, yep current implementation just inherits link component which is <a>. and only adds `dropdown-item` class. I think you want behavior like [buttons](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/button.vue) Which are `<button>` when not having a link to correctly display but are converted to <a> when have links. I suggest adding another computed prop to dropdown-item like : 
```js 
itemType() { 
 return (this.href || this.to)? this.componentType : `button` 
}
```

**Comment by cynecx** [comment]
@pi0 Great. I opened a pull-request just in case (https://github.com/bootstrap-vue/bootstrap-vue/pull/180).

**Comment by cynecx** [comment]
@pi0 merged the pr. I think we can close this.
