### ISSUE TITLE
Multi select cleared after select

### ISSUE THREAD

**Issue by darkiron** [bootstrap-vue/bootstrap-vue#1780]
Hi, 
In my component I pass via props data for multi-select when I tried to select other data my select whas cleared fully : 
```Javascript 
<template>
  <div>
    <b-form-group label="Rôle: ">
      <b-form-select
        @change="emit"
        class="mb-3"
         v-model="value"
         id="form_roles"
          aria-describedby="choicesLiveFeedback"
          :state="formState"
         :multiple="true">
        <option :value="null">Select options</option>
        <option v-for="(role, index) in roles" :key="index" :value="role" >{{ role }}</option>
      </b-form-select>
      <b-form-invalid-feedback id="choicesLiveFeedback" :style="formStyle">
        {{ state }}
      </b-form-invalid-feedback>
    </b-form-group>
  </div>
</template>
<script>
export default {
  name: 'UserRole',
  props: ['value', 'state'],
  data () {
    return {
      roles: [],
      selected: [],
    }
  },
  watch: {
    value () {
      // if (this.selected !== this.value){
       // this.selected = this.value
      // }
    }
  },
  computed: {
      formState () {
        if (this.state !== undefined && this.state.length > 0) {
          return false
        }
      },
      formStyle () {
        if (!this.formState){
          return 'display: block'
        }
      }
    },
  methods: {
    emit (event) {
      this.$emit('input', [event])
    }
  },
  created () {
    // console.log(this.value);
    this.$http.get('/api/rest/securtity/roles').then(
      response => {
        this.roles = response.body
      }
    )
  }
}
</script>
```
at every test select was empty in view ...

**Comment by emanuelmutschlechner** [comment]
@darkiron Multiple works this way:

- Hold <kbd>CTRL</kbd> and click to select/deselect one item at a time
- Hold <kbd>SHIFT</kbd> and click to select a range of items

**Comment by Diaskhan** [comment]
@darkiron 
https://www.w3schools.com/tags/att_select_multiple.asp

U must use another component for tags
https://sagalbot.github.io/vue-select/docs/Basics/Values.html#multiple

Issue shall closed!

**Comment by darkiron** [comment]
Nop standard issue try the code  !

**Comment by Diaskhan** [comment]
Could U provide jsfiddle demo ??

**Comment by darkiron** [comment]
https://codesandbox.io/s/k54xk5qrn3

**Comment by Diaskhan** [comment]
I deleted this code
 @change="emit"
And it works fine!

Why u need emit event when selecting ??

**Comment by darkiron** [comment]
to update parent object ? maybe ?

**Comment by Diaskhan** [comment]
Maybe ? 
I dont understand the component its working !
What problems Do u Have ???

**Comment by Diaskhan** [comment]
@darkiron  delete this code  @change="emit"
**And All gona be work!**

**Comment by darkiron** [comment]
You don't understand the use of component ... 

have a object with multiple props (name, email, roles ... ) 
I passe the value of the array to my component that my value (nldr :  v-model="user.roles") it's an array. When I change select I want to update this array...

**Comment by Diaskhan** [comment]
It sounds like when u send message u sending message to the same conponent! And state of ctrl button trigger fires! 

I guesse u dublicate event! And its brake multiple selection!

**Comment by Diaskhan** [comment]
I changed to  this.$emit('input2', [event])
and selection not droped !

**Comment by emanuelmutschlechner** [comment]
@darkiron Your implementation has some flaws. Make sure to check Vue documentation on how to create a custom component that works with `v-model` as you expect it.
https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model

Check my example below, hope this helps
https://codesandbox.io/s/9zj7943prr

**Comment by Diaskhan** [comment]
@darkiron  we wil close issue!
I guesse need more diving in vuejs to make work ure solution!
