### ISSUE TITLE
Tabs rendered with v-for not updating if order of underlying array changes

### ISSUE THREAD

**Issue by tpinne** [bootstrap-vue/bootstrap-vue#1781]
Hi,

I'm using RC8 of bootstrap-vue and experiencing an unexpected behaviour (on every browser and plattform). I have tabs rendered based on an array with `v-if` and the user is able the change the order of that array. But after reordering the array, the tabs do not rerender according to the new order what I had expected.

I've made a sandbox to demonstrate the behaviour completely isolated. https://codesandbox.io/s/r0vp7x0mnm

If you click the button "change order" you see list above the tabs updating to the new (in this case random) order, but the tabs remain in the default order.

**Comment by emanuelmutschlechner** [comment]
Vue [documentation](https://vuejs.org/v2/guide/list.html#key) states

> When Vue is updating a list of elements rendered with `v-for`, by default it uses an “in-place patch” strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index.

**Comment by Diaskhan** [comment]
Its dublicate 
https://github.com/bootstrap-vue/bootstrap-vue/issues/1691
Issue could be closed !
