### ISSUE TITLE
Tabs are missing an example/docs

### ISSUE THREAD

**Issue by asafyish** [bootstrap-vue/bootstrap-vue#179]
I can see that tabs are implemented, but missing an example/docs,
It will be really helpful to have either :pray:

**Comment by pi0** [comment]
@mosinve Could you help us on it?  We need only some jsFiddle example for this. (component docs are auto generated) 🙏

**Comment by mosinve** [comment]
Yeah,  I'll do)

**Comment by mosinve** [comment]
https://jsfiddle.net/cihkem/rk7w0f2b/ here it is:) 
BTW, tabs in need of further refactoring.

**Comment by pi0** [comment]
@mosinve Thanks :) I agree about refactoring, Do you will to contribute? I can open a PR with some basic refactors before release, or we just can add docs for current release if tabs are stable enough. (I've no idea because not using them in my projects currently)

**Comment by mosinve** [comment]
In general, they are quite stable, and IMHO the public part should not heavily change.  so we can make the documentation, and then refactor. 
i think main changes will be at transitions support, and some Vue programming style refactoring. I have a bedtime in my TZ now, so I can work on tabs tomorrow :)

**Comment by pi0** [comment]
@mosinve OK :) I will prepare docs till tomorrow :) Thanks

**Comment by pi0** [comment]
@asafyish Ready to use :) https://github.com/bootstrap-vue/bootstrap-vue/releases
