### ISSUE TITLE
contenteditable on inputs (or custom element) with same style

### ISSUE THREAD

**Issue by Extarys** [bootstrap-vue/bootstrap-vue#1792]
It would be nice to be able to do something like:

`<b-form-input contenteditable>` or `<b-editable style="height: 60px" >`

And it would have the same style as an input and bind to a variable. It is useful when inserting emoji for example. We could also maybe add autoheight so the content's height is automatically adjusted base d on how much text there is.

**Comment by emanuelmutschlechner** [comment]
@Extarys can you please elaborate? I don't get what `contenteditable` does.

**Comment by Extarys** [comment]
Sure! Contenteditable make a div editable to the user.
I found this component on the internet:
```
<template>
  <div
    contenteditable="true"
    class="form-control"
    @input="update"></div>
</template>
<script>
export default {
	props: {
		content: {
			type: String,
			default: '',
		},
	},
	mounted: () => {
		this.$el.innerText = this.content;
	},
	methods: {
		update (event) {
			this.$emit('update', event.target.innerText);
		},
	},
};
</script>
```

And where I want the user to type I do `<editable @update="editableRaw = $event"></editable>`.
Now on the side I have an emoji box and when the user click on one I can easily add it to the content.

Now the code above doesn't work because I don't know with what I can replace the `this.$el` with. I am not aware of another method to pass svg/png emojis if I don't want to use the browser' built-in font so I'm trying this approach.

**Comment by emanuelmutschlechner** [comment]
I don't think this will be implemented in standard BootstrapVue. The goal is to provide highly customizable components, allowing you to implement this type of stuff yourself.

Please see this issue https://github.com/bootstrap-vue/bootstrap-vue/issues/417

**Comment by Extarys** [comment]
Awww, ok then, thanks! (If you have time on your hand though, could you tell me how to fix the above code? :smile:
