### ISSUE TITLE
[extra component] vue-multiselect

### ISSUE THREAD

**Issue by MarZab** [bootstrap-vue/bootstrap-vue#1794]
I've started working on a vue-multiselect integration and I've figured this is the best place to share it.

My idea is to make a api/interface compatible version of vue-multiselect but using bootstrap-vue for event handling and size/variant and as much bootstrap as possible.

Here is the code: https://gist.github.com/MarZab/378e9f61d3009199f1ac5fcb1178c6e8
Here is a demo: https://0x608nxo10.codesandbox.io/
Here is a playground: https://codesandbox.io/s/0x608nxo10 

This is pretty much work in progress:
- [ ] finalize design for tags and groups
- [ ]  variants, form
- [x]  size
- [x]  input-group
- [ ] bootstrap-vue events (highjacking dropdown atm)
- [ ] responsive (popper.js needs some love on small screens)
- [ ] mobile and keyboard behaviour
- [ ] hints (vue-multiselect gives you hints on what selecting items would do, I don't have a good idea how to move that design into bootstrap atm)
- [ ] move the code into a permanent location

Since this is pretty much just glue for bootstrap-vue and vue-multiselect I don't have a good idea where and how to develop this going forward. 

I would like some thoughts from @shentao on general bootstrap compatibility and the plans for version 3.0 of vue-multiselect.

Any feedback is welcome!

Crossreferences:
https://github.com/bootstrap-vue/bootstrap-vue/issues/251
https://github.com/shentao/vue-multiselect/issues/718
https://github.com/shentao/vue-multiselect/issues/592
https://github.com/shentao/vue-multiselect/issues/513

**Comment by Diaskhan** [comment]
Perfrect. And awesome idea!

**Comment by derekphilipau** [comment]
I'm actually using both bootstrap-vue and vue-multiselect in a project.  The _only_ reason I need vue-multiselect is for search/autocomplete.  Perhaps it is beyond the scope of the bootstrap-vue project, but it would be really nice if search/autocomplete was built into the form select component.

**Comment by jbnv** [comment]
> I'm actually using both bootstrap-vue and vue-multiselect in a project. The _only_ reason I need vue-multiselect is for search/autocomplete. 

@derekphilipau Did you actually get that working? I need a multiselect with search/autocomplete and tagging. I'm just now trying Vue-Multiselect and out the gate it's not working.

> Perhaps it is beyond the scope of the bootstrap-vue project, but it would be really nice if search/autocomplete was built into the form select component.

Yes that would be nice, and I'm really surprised they haven't (as of v2.2) already done it.

**Comment by tmorehouse** [comment]
With the new `<b-form-tags>` input, you could modify the `select` example (https://bootstrap-vue.js.org/docs/components/form-tags#using-custom-form-components) to use a `<b-dropdown>` instead of `<b-form-select>` to create a "select"  that has a search filed at the top, and dynamically render the options (as menu items)

**Comment by tmorehouse** [comment]
@jbnv You can see an example of using a dropdown in `<b-form-tags>` here https://deploy-preview-4582--bootstrap-vue.netlify.com/docs/components/form-tags#advanced-custom-rendering-usage

**Comment by jbnv** [comment]
@tmorehouse Thanks. I'll check it out.

**Comment by tmorehouse** [comment]
The docs are now merged into DEV... so you should see them in the dev docs site at https://bootstrap-vue.netlify.com/docs/components/form-tags
