### ISSUE TITLE
Collapse: collapsed class not persistent

### ISSUE THREAD

**Issue by lianee** [bootstrap-vue/bootstrap-vue#1798]
See this [fiddle](https://jsfiddle.net/sLgj23zu/1/)

the v-b-toggle directive sets the "collapsed" class of the button, that works well, click on the button and its title will change accordingly.

but... close the collapse, the title then correctly read "Open Collapse", then change the value in the input field... The "collapsed" class disappears, and the button now read "Close Collapse".

**Comment by lianee** [comment]
in fact, anything changing the class will rip the "collapsed" class
this time changing the variant prop of the button:
[fiddle](https://jsfiddle.net/sLgj23zu/3/)

**Comment by RomeroMsk** [comment]
I'm experiencing the same issue. The `collapsed` class is not added back after changing the `:class` prop of a toggling element.
