### ISSUE TITLE
Support b-dropdown variant "image"

### ISSUE THREAD

**Issue by antoine-pous** [bootstrap-vue/bootstrap-vue#1799]
I don't find a good way to make a dropdown image with bootstrap-vue. Can you implement a way to do it easily and/or document it?

This kind of usage would be usefull
```html
<b-dropdown v-if="isAuthenticated" variant="image" src="../demo/profile-image.jpeg">
</b-dropdown>
```

Thank you

**Comment by lianee** [comment]
something like that? (image loading is a bit slow)
[fiddle](https://jsfiddle.net/11rv39rg/1/)

**Comment by antoine-pous** [comment]
Yeah, this is the idea, thank you !
