### ISSUE TITLE
Dropdown with images - how to replace?

### ISSUE THREAD

**Issue by focussing** [bootstrap-vue/bootstrap-vue#1805]
I have a dropdown with images, I would like to replace the "static" part after selecting.
Example is a language selector with flags like this.
```
<b-dropdown>
  <template slot="button-content">
    <img class="img-fluid p-2" src="../assets/nl.png" />
  </template>
  <b-dropdown-item><img class="img-fluid p-2" src="../assets/nl.png" /> NL </b-dropdown-item>
  <b-dropdown-item><img class="img-fluid p-2" src="../assets/de.png" /> DE </b-dropdown-item>
</b-dropdown>
```
How do I replace the template slot button-content?

**Comment by mosinve** [comment]
make it dynamic.
Something like that: https://jsfiddle.net/cihkem/ey6c5f0y/

**Comment by focussing** [comment]
Beautiful!! Thanks a lot. :)

**Comment by careerdimasprayoga** [comment]
> make it dynamic.
> Something like that: https://jsfiddle.net/cihkem/ey6c5f0y/

Thank you. I'ts work
