### ISSUE TITLE
How to overrule b-dropdown classes in .vue component?

### ISSUE THREAD

**Issue by focussing** [bootstrap-vue/bootstrap-vue#1808]
Hello!

I would like to overrule the border and caret of a b-dropdown classes within a component.
In Chrome-developer I see the .btn-secondary class from which I can alter for example color or border.
In my code I use for example but it has no effect. What am I doing wrong?

When I put this code in App.vue it works...

```
<style scoped>
.btn-secondary {
    color: red;
    border-color: yellow;
}
</style>
```

**Comment by focussing** [comment]
I removed some imports in my App.vue file; now css overrules in a .vue component work.
What is the explanation for this?

From:
```
<script>
import 'bootstrap-vue/dist/bootstrap-vue.css'

export default {
    name: 'app',
    components: {
        top,
        navBar
    }

}
</script>

<style>
@import "~bootstrap/dist/css/bootstrap.min.css";
@import "~font-awesome/css/font-awesome.min.css";
</style>
```

to:

```
<script>
export default {
    name: 'app',
    components: {
        top,
        navBar
    }

}
</script>

<style>
@import "~bootstrap-vue/dist/bootstrap-vue.css";
@import "~bootstrap/dist/css/bootstrap.min.css";
@import "~font-awesome/css/font-awesome.min.css";
</style>
```

**Comment by emanuelmutschlechner** [comment]
Scoped styles won't work in BV components

**Comment by tmorehouse** [comment]
The best way is to add your own class to dropdown component and target the inner classes using that outer class.

**Comment by focussing** [comment]
OKay, thanks... but how do I do that?

**Comment by focussing** [comment]
I am missing a working example...

**Comment by tmorehouse** [comment]
It is basic cascading styles (CSS)

Add a class to your `b-dropdown` component (i.e. '<b-dropdown class="my-dropdown" ... >'),

Then target the inner parts as such with your style overrides:

```css
.my-dropdown .dropdown-menu { /* some styles here */ }
.my-dropdown .dropdown-menu .dropdown-item { /* some styes here */ }
.my-dropdown > button { /* some styles here */ }
```

**Comment by fuoridallarete** [comment]
Hi @tmorehouse, I am having the same issue here. At first I solved it using global style instead of scoped. But when I needed to use the same vue-bootstrap component in another page and with different style, it became a problem. So I used your approach, attach a class to the outer element and try to reach its children through it, but it didn't work.  Example of my code, using <b-tabs>:
-in the template
```
<b-tabs content-class="mt-3" align="center">
     <b-tab active class="myTabs">
        ...
    </b-tab>
</b-tabs>
```
In the scoped css:
```
.myTabs .nav-tabs .nav-item .nav-link.active {
  color: #fff !important;
  background: orangered !important;
  border-color: orangered !important;
  border: none;
  margin-bottom: 0 !important;
  margin-right: .3rem;
  border-radius: 0 !important;
  border-top-left-radius: 5px !important;
  border-top-right-radius: 25px !important;
}
```
My class is ```.myTabs```, I've also tried using ```>``` for child selector but it doesn't work neither way. It works only setting the style globally, but it messed up other pages. I would avoid touching the sass staffs, if there's an alternative.
Thanks for your time and help.
x

**Comment by tmorehouse** [comment]
As with any component in Vue when using scoped styles, you need to use [vue loader's deep selector](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements):

```css
.myTabs /deep/ .nav-tabs .nav-item .nav-link.active {
  color: #fff !important;
  background: orangered !important;
  border-color: orangered !important;
  border: none;
  margin-bottom: 0 !important;
  margin-right: .3rem;
  border-radius: 0 !important;
  border-top-left-radius: 5px !important;
  border-top-right-radius: 25px !important;
}
```
