### ISSUE TITLE
The <b-btn> won't center the icon on the button

### ISSUE THREAD

**Issue by IFormiga** [bootstrap-vue/bootstrap-vue#1809]
When the tag b-btn is used with an icon inside the icon appears but when you make a square button the icon is not centered.

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <link href="/static/fontawesome/fontawesome-all.css" rel="stylesheet">
<b-btn class="far fa-edit" style="height: 30px; width: 30px; font-size: 30;" @click="showModal"></b-btn>

**Comment by mosinve** [comment]
Can you make an example?
you can use this as boilerplate https://codepen.io/cih/pen/aKoYyw
