### ISSUE TITLE
close-on-backdrop option in modal doesn't work.

### ISSUE THREAD

**Issue by NessunKim** [bootstrap-vue/bootstrap-vue#181]
After release v0.10.2, the modal doesn't close when click backdrop.

**Comment by pi0** [comment]
@NessunKim Thanks for reporting. I can confirm too. Will check it soon.

**Comment by mosinve** [comment]
Hmm.... it's because of this

    <div key="modal-backdrop"
       :class="['modal-backdrop',{fade: fade}]"
        v-if="visible"
        @click="onClickOut($event)"></div>

But i've tested this :(

**Comment by XionDelta** [comment]
Sorry to chime in if you already have a solution, but I've just experimented with this and it looks like it works when `@click="onClickOut($event)"` is moved to the main modal element _instead_ of the modal backdrop element.

I.e.
`<div key="modal" :id="id" v-show="visible" :class="['modal',{fade :fade}]" @click="onClickOut($event)">`

**Comment by pi0** [comment]
@XionDelta Seems working ;) 
@mosinve If you think this is an invalid approach please correct it. (sorry for changing without talking)

**Comment by mosinve** [comment]
It's OK,  I think this is the correct variant))
