### ISSUE TITLE
Carousel site

### ISSUE THREAD

**Issue by Saulius8** [bootstrap-vue/bootstrap-vue#1823]
https://bootstrap-vue.js.org/docs/components/carousel

It's hard to read, then image size always changing..

**Comment by emanuelmutschlechner** [comment]
[lorempixel.com](//lorempixel.com) is down right now. Let's wait and see if the issue gets resolved.

There is a list of other placeholder services
https://www.johanbostrom.se/blog/the-best-image-placeholder-services-on-the-web
