### ISSUE TITLE
No support for media-breakpoint-up mixin?

### ISSUE THREAD

**Issue by nicbavetta** [bootstrap-vue/bootstrap-vue#1827]
I have tried to implement responsive typography via scss mixin (as supported by Bootstrap 4): https://getbootstrap.com/docs/4.0/content/typography/#responsive-typography

Upon compilation, I receive an error stating no mixins exist with the name 'media-breakpoint-up'. Is this an unsupported mixin in Bootstrap Vue?

**Comment by emanuelmutschlechner** [comment]
Please provide a reproduction repo
