### ISSUE TITLE
Carouse image on Docs are not loading

### ISSUE THREAD

**Issue by unpana** [bootstrap-vue/bootstrap-vue#1828]
The carousek sample images are not showing on the documentation page. It looks like the image service LoremPixel.com is constantly down.

**Affected URL:** [https://bootstrap-vue.js.org/docs/components/carousel/](https://bootstrap-vue.js.org/docs/components/carousel/)
**Browser and OS:** Version 66.0.3359.139 (Official Build) (64-bit) Windows 10

**Comment by rinick** [comment]
this is a duplicated issue of #1823
