### ISSUE TITLE
Unable to pass children to `b-breadcrumb-link`

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#1832]
The `b-breadcrumb-link` component always passes the `text` prop as `innerHTML` DOM property to the `b-link` component. This force-overrides the childrens passed to `b-breadcrumb-link`.

https://github.com/bootstrap-vue/bootstrap-vue/blob/e4ad4997bb297c7b4074d1efa207a130339b91d4/src/components/breadcrumb/breadcrumb-link.js#L33

IMHO it would be better to check for given children and pass the value of the `text` prop as fallback to the `b-link` component. This would allow to pass e.g. a icon to the `b-breadcrumb-link`.

**Comment by emanuelmutschlechner** [comment]
You probably meant `<b-breadcrumb-link>`? there is no `<b-dropdown-link>` component.

The `text` prop accepts valid HTML. So icon support is given. Theoretically you can pass everything you want. If you want use `<div>`s inside a link, feel free to do so, but don't forget to set `display: inline` if you don't want to break Bootstrap style.

**Comment by jackmu95** [comment]
@emanuelmutschlechner Your right, I've updated title and text.

I'am aware that it's possible to pass HTML to the `text` prop but the `b-breadcrumb-link` component explicit passes the children to the `b-link` component which has no effect due to the `innerHTML` DOM property.

https://github.com/bootstrap-vue/bootstrap-vue/blob/e4ad4997bb297c7b4074d1efa207a130339b91d4/src/components/breadcrumb/breadcrumb-link.js#L42

In my case I use a component to generate the icon markup and it would be handy to use it inside the `b-breadcrumb-link` component.

**Comment by emanuelmutschlechner** [comment]
@jackmu95 Can you come up with a PR?

**Comment by jackmu95** [comment]
@emanuelmutschlechner see #1833.
