### ISSUE TITLE
Table shows already deleted entries / Table does not refresh

### ISSUE THREAD

**Issue by SHA-256** [bootstrap-vue/bootstrap-vue#1834]
- Operating system and version: Haiku 5.3
- Browser and version: Chromium 67
- Bootstrap-Vue Version: 2.0.0-rc.9 

Since none of the suggested test pages is allowed by my proxy, I will try to describe my problem.

I create a normal ```<b-table :items=""tableData>``` and feed it with data from an array. If I now delete an array entry using its index (for example: ```delete tableData[0]```), the table continues to display the data.

The table view is only updated when I sort the table or add an entry to the array.

The table's refresh function does not seem to work either.
```
this.$refs.exampleTable.refresh()
```

No errors are displayed, it just does not refresh.

**Comment by emanuelmutschlechner** [comment]
This is not a BootstrapVue issue. Check the section [array change detection](https://vuejs.org/v2/guide/list.html#Array-Change-Detection) in the Vue docs.

Minimal example
https://codesandbox.io/s/q4nmr9nwqw
