### ISSUE TITLE
passing a value to the modal

### ISSUE THREAD

**Issue by barrachri** [bootstrap-vue/bootstrap-vue#184]
Hello, I am trying to use the modal to confirm to delete something

```
<b-btn @click="$root.$emit('show::modal','modal1')" variant="danger" :data-cargoid="cargo.id">Remove</b-btn>

   submit() {
        console.log("Deleted!")
        
        // Ensure modal closes
        this.$root.$emit('hide::modal', 'modal1');
      }
```

How can I read data-cargoid inside submit?

**Comment by pi0** [comment]
Hey @barrachri :) You can simply keep id in callback function.(`ok` event)

```html 
<b-btn v-b-modal.modal1 variant="danger" @ok="deleteItem(cargo.id)">Remove</b-btn>
```

**Comment by barrachri** [comment]
Hi @pi0 thanks!, but how does it work?

deleteItem will be called after I press the ok button inside the modal?


```
 <b-btn v-b-modal.modal1 variant="danger" @ok="deleteItem(cargo.id)">Remove</b-btn>

<!-- Modal -->
<b-modal id="modal1" title="Are you sure?" ok-title="Yes" @ok="submit"></b-modal>

    submit() {
        // Ensure modal closes
        this.$root.$emit('hide::modal', 'modal1');
      },
      deleteItem(id) {
        console.log(id)
console.log("Deleted!")
      }
```

**Comment by pi0** [comment]
@barrachri Function which is defined in template is scoped to each item. That's a declaration not just a call.

**Comment by barrachri** [comment]
Thanks @pi0.

Do you know where can I find more info about this? Vue Docs?

Because I have more than 1 buttons on the same page, so that function is "declared" many times.

**Comment by pi0** [comment]
@barrachri That's ok if you use it as many times as you want. I can help you if provide more details / usage code snippets about your problem if have any. If you are new to vue i strongly recommend reading this two pages: 
https://vuejs.org/v2/guide/list.html
https://vuejs.org/v2/guide/class-and-style.html

**Comment by barrachri** [comment]
Sorry for being late, my use case is quite simple.

Generally I have more than one <tr>
```
<table>
<tr v-for="(cargo, index) in cargos">
<th scope=row>{{index+1}}</th>
<td>{{cargo.name}}</td>
<td>
<b-btn v-b-modal.modal1 variant="danger" @ok="deleteCargo(cargo.id)">Remove</b-btn>
<td>
</tr>
</table>

<!-- Modal -->
  <b-modal id="modal1" title="Are you sure?" @ok="deleteCargo" ok-title="Yes"></b-modal>


```
When I press the Remove button I will get the modal open and if I press yes I should run deleteCargo passing the id of cargo.
```
<script>

	var apiURL = '/api/v1.0/cargos'


export default {
  
  data () {
    return {
      cargos: null
    }
  },

  created () {
    // fetch the data when the view is created and the data is
    // already being observed
    this.fetchData()
  },
  watch: {
    // call again the method if the route changes
    '$route': 'fetchData'
  },
  methods: {
    fetchData () {
      var xhr = new XMLHttpRequest();
      var self = this;
      xhr.open('GET', apiURL);
			xhr.setRequestHeader('Authorization', 'Bearer ' + localStorage.getItem('Token'));
      xhr.onload = function () {
        self.cargos = JSON.parse(xhr.responseText).cargos
      }
      xhr.send();
    },
     deleteCargo(id) {
        console.log("Deleted!");
       // API call to delete the object
        // Ensure modal closes
        this.$root.$emit('hide::modal', 'modal1');
      }
  }
}

	</script>
```

In the meantime I am reading the links you shared :)

**Comment by pi0** [comment]
@barrachri I've just edited your last message. I think it should work

**Comment by pi0** [comment]
@barrachri I figured out real issue now :)) Edited your last comment it should work (using a dirty workaround) but will add a simpler way soon to do this.

**Comment by barrachri** [comment]
Thanks @pi0 this is what I wanted to have :)

**Comment by pi0** [comment]
Just made more investigations. Seems using parent to pass props is best way. Fell free to reopen is someone has better idea.

**Comment by farantesrodrigues** [comment]
@pi0 modal.show() could return a promise with success (if user gives ok) or fail (abandon or user rejects). In case of success an argument would be passed to the success callback containing the id to be removed.

**Comment by alexsasharegan** [comment]
@farantesrodrigues, I've been using this pattern to use modal delete confirmations:

```vue
<template>
    <div>
        <b-modal ref="modal"
                 @ok="acceptDelete"></b-modal>
        <b-btn v-for="thing in things"
               :key="thing.key"
               @click="requestDelete(thing.id)">{{ thing.name }}</b-btn>
    </div>
</template>

<script>
export default {
    data() {
        return {
            thingToDelete: null,
            things: []
        }
    },
    methods: {
        showModal() {
            this.$refs.modal.show()
        },
        hideModal() {
            this.$refs.modal.hide()
        },
        requestDelete(thingId) {
            this.thingToDelete = thingId
            this.modal.show()
        },
        acceptDelete() {
            if (this.thingId) {
                this.deleteThing(this.thingId)
            }
        },
    },
}
</script>
```

**Comment by farantesrodrigues** [comment]
@alexsasharegan thanks for sharing
I follow something similar only difference is I use the assertion on the isOK property sent on the hide event :
```
<template>
    <div>
        <b-modal ref="modal" @hide="closeDelete"></b-modal>
        ...
    </div>
</template>

<script>
export default {
    ...
    methods: {
        closeDelete: function (e) {
            if (e.isOK === true) {
              this.deleteThing(this.thingToDelete)
              this.thingToDelete = null
            } else {
              this.thingToDelete = null
            }
      }
    },
}
```

**Comment by alexsasharegan** [comment]
I see. That works too! But by using the `hide` event, you aren't guaranteed the user has taken an action. `hide` will be called in all these cases:

- User presses escape key _(no action)_
- User presses close "X" button _(no action)_
- User presses cancel button in footer _(action available as `cancel` event)_
- User presses ok button in footer _(action available as `ok` event)_

All you're sacrificing excess logic. In the case of promises, that is a interesting idea for us to keep in mind for `v1.0.0`. I want to have modal events to line up with BS4 events, but that is a breaking change. I would lean towards using `modal.open()` & `modal.close()` returning a promise that resolves once the UI transition is complete as that would be consistent and support new use cases (while the events already support the use case of confirmation). There is also talk of a standard synthetic event object to be used throughout the library in cases like this.

**Comment by tmorehouse** [comment]
The `ok` event is fired when the built in OK button is clicked

You can emulate this by calling the modals internal `.hide()` method by passing `true` to hide.

To access the `hide()` method you would need a referent to the modal (by placing a `ref="myModal"` on the modal, then doing `this.$refs.myModal.hide(true)` on your custom OK button. This will fire the builtin event 'ok'.  The value you pass to `hide()` is attached to the event object in the `isOk` property of the event.
