### ISSUE TITLE
navbar links in nuxt 

### ISSUE THREAD

**Issue by MartCube** [bootstrap-vue/bootstrap-vue#1840]
I'm using bootstrap-vue in my nuxt project.
I have created some navbar with some links of my pages.

`<b-navbar toggleable="md">
		
		<b-navbar-toggle target="nav_collapse" class="ml-auto"/>
		
		<b-collapse id="nav_collapse" is-nav>
			<b-navbar-nav class="mx-auto">
				<b-nav-item class="mx-auto" to="/">home</b-nav-item>
				<b-nav-item class="mx-auto" to="/booking">Booking</b-nav-item>
				<b-nav-item class="mx-auto" to="/gallery">Gallery</b-nav-item>
				<b-nav-item class="mx-auto" to="/faq">FAQ</b-nav-item>
				<b-nav-item class="mx-auto" to="/contact">Contact</b-nav-item>		
			</b-navbar-nav>
		</b-collapse>
	</b-navbar>`

I think there is a problem when using links who goes to="/"
they are **always selected**. You can see a picture on the fallowing link http://prntscr.com/jj2zlz

**Comment by emanuelmutschlechner** [comment]
Take a look at the router docs. Prop `exact` is what you want:
https://router.vuejs.org/en/api/router-link.html

**Comment by dcsan** [comment]
I have a perhaps similar issue in that the dropdown-items stay highlighted when navigating.

````
    <b-dropdown-item
      v-for="item in menu.items"
      :to="item.href"
      :key="item.text">
      {{ item.text }}
    </b-dropdown-item>
```

![image](https://user-images.githubusercontent.com/514002/48760250-5ce2d880-ece0-11e8-90ba-4e606b01fd96.png)

I'm using `nuxt.js` so not quite sure where to modify such things as router properties, or even if that is the problem here...

**Comment by tmorehouse** [comment]
Router props are applied directly to `<b-bropdown-item :to="href" router-active-class="foo">`, just like the `to` prop.

**Comment by dcsan** [comment]
thanks for the help @tmorehouse fixed the issue!

**Comment by tmorehouse** [comment]
Great that you got it fixed!
