### ISSUE TITLE
can not open a modal on a modal

### ISSUE THREAD

**Issue by kpeng2016** [bootstrap-vue/bootstrap-vue#1842]
Hi,
firstly I click the button A to open first modal 1, on this modal there is another button B,   click button B open another modal 2, but  modal 1 is closed, is that possible, keep modal 1 show than hide. as I hope I can see some information from modal 1 when I do something in modal 2.

- windows 7
- Chrome  66.0.3359.139（release） （32 位）
- v2.0.0-rc.10
Thanks 
William

Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/bootstrap-vue/bootstrap-vue/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/CONTRIBUTING.md)

When asking general "how to" questions:

- Please avoid opening an issue here
- Instead, ask for help on StackOverflow, IRC, or [Slack](https://bootstrap-vue.now.sh/), and also check out the [online documentation](https://bootstrap-vue.js.org)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Version of Bootstrap-Vue that you are using
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/), [JS Bin](https://jsbin.com/), or [JsFiddle](https://jsfiddle.net/) (You can export markup from the [online playground](https://bootstrap-vue.js.org/play) to JS Fiddle)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

Love bootstrap-vue? Please consider supporting our collective:
👉  https://opencollective.com/bootstrap-vue/donate

**Comment by mosinve** [comment]
From Bootstrap docs site 
> Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

https://getbootstrap.com/docs/4.0/components/modal/#how-it-works
