### ISSUE TITLE
b-popover does not work on safari

### ISSUE THREAD

**Issue by HKskn** [bootstrap-vue/bootstrap-vue#1846]
Hi, b-popover does not work on safari when the trigger property is 'focus'. Could you help me about it?
Also when I tried it on bootstrap official documentation, It didn't work. Other browsers are okey.

- os: mac OS X  10.13.4
- browser: Safari  11.1
- bootstrap-vue: 2.0.0-rc.9

**Comment by mosinve** [comment]
Hm...it seems that safari emits  focus only by keyboard. try to "tab" to button with `focus` popover

**Comment by HKskn** [comment]
@mosinve  Could we emit focus event when clicking on popover?
Actually, I want to trigger popover when I clicked and hide it when I clicked out of it. Focus was the only solution for me. But if you have better solution for me. I will pleased with it.
Great thanks.

**Comment by HKskn** [comment]
@mosinve O solved my problem with triggering focus event on button.

`document.getElementById('blabla').focus()`

**Comment by HKskn** [comment]
@robcresswell I tried but still does not work with it. I solved this problem with workaround solutions.
