### ISSUE TITLE
Question : browser refresh and bootstrap-vue

### ISSUE THREAD

**Issue by arcassar** [bootstrap-vue/bootstrap-vue#185]
Hi,
I encounter a problem with the "bootstrap-vue" plugin in my application.

I registered the module according to the guidelines and did the import. I use the latest version (0.11) and similarly for VueJS (2.2.6).

The problem is:

When I do a refresh in the browser (F5), my application seems to lose all links with the plugin.
For example, I made a menu based on the documentation. When I refresh my page, VueJS reports unknown custom elements: <b-navbar>, ... and asks me if I registered the component.

This is indeed the case (installation made by npm and declaration in the entry point as in the documentation). When I use the chrome extension for VueJS and I look at the state, I see the <BNavbar> component disappearing after the refresh (but my other custom components remain in place/are reloaded). 

So, according to you, I made a mistake elsewhere (I will look more in depth thus) or it is a bug?

**Comment by mosinve** [comment]
Hi,  can you provide a jsfiddle or codepen describing this case? Or just a piece of code which reproduces this case?

**Comment by arcassar** [comment]
Hi @mosinve ,

Here is a simple example on jsFiddle. It is quite representative of my code. I created a special component for the header of my app. There is the menu and that's all.

https://jsfiddle.net/ut1uakxm/17/

I inject the component in my general app object.

But as I can see in the jsfiddle, the css isn't applied...  It's the same problem in my app. I see the items of the menu but there is no style.

Is it a problem of external resources? I can investigate that way to see if I don't have a problem with my webpack/npm  configuration.

**Comment by pi0** [comment]
@arcassar I've forked your example (https://jsfiddle.net/pi0/ut1uakxm/21/) There was a problem in scripts order (vue SHOULD be included before any other js)
There is another bug (i think it should be resolved in bootstrap not here) that collapsing navs without brand are not displaying correctly when collapsed.

**Comment by arcassar** [comment]
Hi @pi0 ,

Thanks for your quickly response and your time ! The problem is solved !

So two things : 
1) You 're right for the brand problem. I also encouter the problem.
2) I'm new to VueJS, and you gave me an important hint with the js scheduling!  I change the place where I call "Vue.use(BootstrapVue);" and it works now in every situation.


Thanks for the help and thanks for your great work on this plugin!

**Comment by cnstlungu** [comment]
> Hi @pi0 ,
> 
> Thanks for your quickly response and your time ! The problem is solved !
> 
> So two things :
> 
>     1. You 're right for the brand problem. I also encouter the problem.
> 
>     2. I'm new to VueJS, and you gave me an important hint with the js scheduling!  I change the place where I call "Vue.use(BootstrapVue);" and it works now in every situation.
> 
> 
> Thanks for the help and thanks for your great work on this plugin!

Great point. Couldn't figure why I would use all styles on refresh. Turns out, Vue.use(BootstrapVue) needs to go before new Vue ({}), not after as I put it.
