### ISSUE TITLE
Warnings on b-form-select open/close in recent Chrome

### ISSUE THREAD

**Issue by chrismurf** [bootstrap-vue/bootstrap-vue#1858]
**To recreate:**
  Go to https://bootstrap-vue.js.org/play/ in Chrome v66 (I believe v51 or newer) and enter the following template:
```html
  <b-form-select>
      <option>Sample</option>
  </b-form-select>
```
Then open and close the resulting select input several times.

**Expected:**
Developer console free of warnings and errors.

**Actual:**
See the following warning in the JavaScript console: 

> [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by chrismurf** [comment]
See https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md for a better explanation of the cause.

**Comment by SkullFire** [comment]
Any news?

**Comment by tmorehouse** [comment]
I don't think we add any `mousewheel` events to `b-form-select`, but we will investigate

**Comment by Atiladanvi** [comment]
I have error in b-form-select: 
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by tmorehouse** [comment]
I'm still not sure what would be causing this.  `b-form-select` does not instantiate any 'mousewheel' listeners at all. It has to be something else adding them in.

Do you have any other plugins that may be installing listeners (such as validation)?

**Comment by Atiladanvi** [comment]
go to a website vue-bootstrap  anda see the saem error in doc of selects

**Comment by tmorehouse** [comment]
I think it might be docs use of `v-b-scroll-spy` directive... which monitors the page scrolling to highlight the current page section TOC (on the right hand side).

We'll have to update our `eventOn` handler to detect support of the `passive` option (not all browsers support it, and if present treat it as wanting to use capture mode).

Will see what we can do over the next week.

**Comment by jackmu95** [comment]
@tmorehouse I have all log-levels selected.

**Comment by tmorehouse** [comment]
Ok, maybe it is because v70 (I think) defaults most document listeners to passive by default.

**Comment by tmorehouse** [comment]
My work laptop still has chrome v60 (can't update it as it is controlled by work IT department), and I see the warning crop up once and a while.
