### ISSUE TITLE
Change Ok button text in b-modal

### ISSUE THREAD

**Issue by chaymag** [bootstrap-vue/bootstrap-vue#1862]
Hello, I want to change the text for the "ok" button.How can I do that ?

**Comment by chaymag** [comment]
I managed to change it using the property : ok-title

**Comment by arirah** [comment]
`:ok-title = "`Submit`"`  or `ok-title="Submit" :P`

**Comment by Vidhyanandcs** [comment]
it is `ok-title = "Submit"`

**Comment by islomrakhimkulov** [comment]
ok-title-html = "Submit"
