### ISSUE TITLE
Add a `_trClass` and / or `_trAttr` property to <b-table> items

### ISSUE THREAD

**Issue by kbirk** [bootstrap-vue/bootstrap-vue#1864]
Currently there are the `tdClass` and `tdAttr` properties for the table fields. It would be really nice to have something similar for the table items. Such as `_trClass` or `_trAttr` per item which would be injected in each row in the table.

My use case requires injecting a row-unique value into each row's DOM element to interface with another 3rd party library. This row-unique value is not displayed in the table so I can't acheive this in a roundabout way using the existing `tdClass` / `tdAttr` callback functions.

**Comment by tmorehouse** [comment]
Use the table `primary-key` option to enable a unique ID per row, which is based on the table's ID and the value of the field that is specified by the `primary-key`.  The primary key field needs to exist in your data, but doesn't need to be displayed in the table itself.

**Comment by tmorehouse** [comment]
BootstrapVue v2.2.0 has been released.
