### ISSUE TITLE
Open modal from modal

### ISSUE THREAD

**Issue by dalibor983** [bootstrap-vue/bootstrap-vue#1869]
Is there any way to open another modal with button in already opened modal.

New modal should be opened over already opened modal.

Example:
There is a button on the page. That button opens modal. Modal has button that opens another modal.

Now when second modal is opened previous one is closed.

```html
<div>
  <b-btn v-b-modal.modal1>Launch demo modal</b-btn>

  <!-- Modal 1 Component -->
  <b-modal id="modal1" title="Bootstrap-Vue">
    <p class="my-4">Hello from modal!</p>
    <b-btn v-b-modal.modal2>Launch demo modal 2</b-btn>
  </b-modal>

  <!-- Modal 2 Component -->
  <b-modal id="modal2" title="Bootstrap-Vue">
    <p class="my-4">Hello from modal!</p>
  </b-modal>
</div>
```

**Comment by mosinve** [comment]
Screenshot from Bootstrap Docs site. As this project built on BootstrapVue, it inherits all Bootstrap limitations.

![image](https://user-images.githubusercontent.com/20986566/41109748-e860e10c-6aa1-11e8-84a0-0bc296d4b435.png)
