### ISSUE TITLE
Pagination with slots for font-awesome

### ISSUE THREAD

**Issue by kyleweishaupt** [bootstrap-vue/bootstrap-vue#1870]
I'm trying to use the Pagination component but I was hoping to use font-awesome icons instead of just text. I looked through the code and couldn't figure out any way to use a scoped slot or anything else to make it work. If possible, I'd love to be able to do something like this:
```
<b-pagination :total-rows="total" :limit="5" :per-page="per_page">
    <template slot="first-text">
        <font-awesome-icon icon="fast-backward />
    </template>
    <template slot="last-text">
        <font-awesome-icon icon="fast-forward />
    </template>
</b-pagination>
```

If anyone knows a way please let me know. Thanks for the great package!

**Comment by toadkicker** [comment]
It's using a prop for these and not a slot. I was able to get it to render using `<i class="fa fa-angle-double-left"></i>`, but it won't accept the `font-awesome-icon` component.
