### ISSUE TITLE
Delayed update of variables within tab headers when using template tag

### ISSUE THREAD

**Issue by mrcl** [bootstrap-vue/bootstrap-vue#1871]
**Bug Report**

Delayed update of variables within tab headers when using 
```
<b-tab>
    <template slot="title">{{ tab.title }}</template>
</b-tab>
```

When editing the variables values via an input field bound with v-model, the title is updated normally when using `<b-tab :title="tab.title">` but has a delay of one character using the template tag. 

The Bug can be verified in this example.

https://codesandbox.io/s/2z1qppyk2j

Another verified problem occurs when inserting a v-model bound input field within the template tag.
```
<b-tab>
    <template slot="title">
        <input v-model="tab.title">
    </template>
</b-tab>
```

**Comment by mrcl** [comment]
Does anyone have a clue what is going on here?

**Comment by emanuelmutschlechner** [comment]
there is already an issue for this https://github.com/bootstrap-vue/bootstrap-vue/issues/1830

**Comment by mrcl** [comment]
@emanuelmutschlechner, That is really cool and using the prop `:title-link-class` it partially solves my problem. The only problem left here is that if I use an input field on the tab template, for some reason it is not possible to type spaces.

https://codesandbox.io/s/2z1qppyk2j

Any clue?

**Comment by emanuelmutschlechner** [comment]
Interesting, I can not imagine what could causing this weir behavior. It could be a side effect of the `title` slot update limitations.

At first I thought the problem was in the component `<b-form-input>` but replacing it with a plain `<input>` didn't solve the problem

I was able to come up with a simple and effective fix: using the `@keydown.space.native="tab.title+=' '"` modifier to replicate the normal behavior 😄 
https://codesandbox.io/s/lp77174577

**Comment by mrcl** [comment]
@emanuelmutschlechner , thanks for you help. I can live with that for now. It would be great to understand what the problem., should I leave this issue open?

**Comment by emanuelmutschlechner** [comment]
@mrcl yes, leave it open as it could be useful for other people having the sample problem

**Comment by emanuelmutschlechner** [comment]
I'm afraid it won't get fixed any time soon

**Comment by rizen** [comment]
Another way to demonstrate the problem: https://jsfiddle.net/aq9Laaew/97072/

**Comment by ivolkoff** [comment]
@rizen see this https://github.com/bootstrap-vue/bootstrap-vue/issues/1677

**Comment by rizen** [comment]
@ivolkoff I saw that thanks

**Comment by tmorehouse** [comment]
Closing in favour of #2148
