### ISSUE TITLE
404 When Navigating to https://bootstrap-vue.js.org/docs/reference/variants

### ISSUE THREAD

**Issue by fnoori** [bootstrap-vue/bootstrap-vue#1876]
Found a 404 link when looking through the b-dropdown page:
https://bootstrap-vue.js.org/docs/components/dropdown/

<img width="1280" alt="screen shot 2018-06-08 at 11 57 59 am" src="https://user-images.githubusercontent.com/16112234/41173227-57ddb836-6b13-11e8-9647-d8b42e1c6e5f.png">

**Comment by mosinve** [comment]
![2018-06-09 09 01 03](https://user-images.githubusercontent.com/20986566/41186626-cedd9784-6bc3-11e8-9b7a-0786c4e05e95.gif)

**Comment by fnoori** [comment]
Not sure why I was seeing 404.
