### ISSUE TITLE
Navbar binding for style attribute does not work

### ISSUE THREAD

**Issue by ypnos-web** [bootstrap-vue/bootstrap-vue#1878]
I would like to set the background color of my navbar based on a database value. However, `:style` seems not to work (it is being ignored) with the `b-navbar` component.

I exported this JS Fiddle from playground: https://jsfiddle.net/87wpvsrf/1/

I put various elements that show where it should work, in some it does.
Navbar elements can have a regular `style` attribute, but I need a binding.

**Comment by mosinve** [comment]
The common in components that fail is that they are functional components.

**Comment by jackmu95** [comment]
This is resolved by now using the following markup:
```vue
<b-navbar :style="{ 'background-color': 'orange' }">
  <b-navbar-brand href="#">NavBar</b-navbar-brand>
</b-navbar>
```
