### ISSUE TITLE
Filter support for b-form-select

### ISSUE THREAD

**Issue by kuyeduwu** [bootstrap-vue/bootstrap-vue#1879]
For a select input on modern web page, should allow users to just type some letters to filter the options, refer to the screenshot below:
![image](https://user-images.githubusercontent.com/12016781/41222394-4f71fa9e-6d99-11e8-9ff4-ff118037c4ea.png)

**Comment by tmorehouse** [comment]
`<b-form-select>` renders a native `<select>` elements. The features of the `<select>` (other than styling) are dictated by the browser.

What you are looking for is a truly custom select style component.

**Comment by kuyeduwu** [comment]
Yes, you are right, it should be a custom select style component, just found some other VUE based ui frameworks like iView and element UI, they provide this kind of handy functions, so I thought it might be better if bootstrap-vue also could provide this.
