### ISSUE TITLE
dist missing 

### ISSUE THREAD

**Issue by Jack85** [bootstrap-vue/bootstrap-vue#188]
If do 

` npm install --save bootstrap-vue`

I dont have any dist folder there
Cannot include acording to manual.

**Comment by pi0** [comment]
@Jack85 Thats odd i think your download is broken :)) (See latest package contents: https://unpkg.com/bootstrap-vue@0.11.0/dist/ ) Please check : 

- your downloaded contents in node_modules/bootstrap-vue/dist
- remove node_modules and reinstalling packages
- you are setting correct path 

BTW suggest to use [yarn](http://yarnpkg.com/) , npm was sucking so Facebook guys made that :))

**Comment by Jack85** [comment]
you re correct , I had it twice in depenedecies and dev dependecies. Thanks.
