### ISSUE TITLE
[Firefox] Can't select input type password inside a modal

### ISSUE THREAD

**Issue by aditioan** [bootstrap-vue/bootstrap-vue#1880]
Hello!

I got a problem when using b-form-input type="password" inside a modal on firefox (60.0.1, Ubuntu 64-bit). I can't select the input but it's not disabled. I think maybe it's a pointer-events problem, but the other type of inputs are works. So I have no idea what could be the problem.

Thank you

**Comment by dominusbelial** [comment]
i'm having the same issue with a b-form-file inside a b-modal, while toying with the modal i found the input actually works if i click somewhere else on the modals body, and the normal html input will show/render up in that position if i add the "plain" prop to the b-form-file while rendering a disabled bootstrapvue b-form-file component at the same time.

**Comment by tmorehouse** [comment]
Closing in favour of issue ##1908
