### ISSUE TITLE
b-link in table slot not creating link/interacting with vue-router

### ISSUE THREAD

**Issue by jswiss** [bootstrap-vue/bootstrap-vue#1884]
Hi all:

I've been struggling to create a link inside a table slot. I'm sure (/hoping) I'm just misconfiguring something. 

Here's my slots: 
`<template slot="birthdate" slot-scope="row">{{ row.value | date }}</template>
  <template slot="current-school" slot-scope="row">
      <b-link @click.stop="" :to="{ name: 'EditSchool', params: { id: row.route }}">{{ row.value }}</b-link>
  </template>`

Everything renders appropriately, except for the hyperlink. I've tried fiddling with it, even adding :href="https://google.com", and nothing seems to work. 

Any help would be much appreciated

**Comment by jeyemwey** [comment]
Hi, I'm experiencing the same problem.

My code is:
```html
<b-table striped :items="items" :fields="post_fields">
  <template slot="name" slot-scope="data">
    <b-link :href="data.value.editLink">{{data.value.name}}</b-link>
  </template>
</b-table>
```

This should give me a Link, however the DOM inspector returns this non-clickable `<td aria-colindex="2" class="">(and here comes the title)</td>`.

@jswiss If you have any new information on how to solve this, please post it here.

Any help would be gladly appreciated.
