### ISSUE TITLE
How can I disable click outside Modal  area and close the modal?

### ISSUE THREAD

**Issue by fagworio** [bootstrap-vue/bootstrap-vue#1886]
Nice work guys.

How can I disable click outside Modal  area and close the modal?

Want to create a modal with a form but I want to prevent the user click outside the modal area and lost the information.

Thanks.

**Comment by rimonmath** [comment]
@mosinve , this prevent hiding always. I want only prevent hiding when a user click outside of a modal. Not in all case.

**Comment by tmorehouse** [comment]
@rimonmath Use the `no-close-on-backdrop` prop on `<b-modal>`

https://bootstrap-vue.js.org/docs/components/modal#overview

**Comment by SpiritedHunter** [comment]
> Nice work guys.
> 
> How can I disable click outside Modal area and close the modal?
> 
> Want to create a modal with a form but I want to prevent the user click outside the modal area and lost the information.
> 
> Thanks.
> 
> I read the docs and found the solution
> 
> **`no-close-on-backdrop`**

where exactly do you put "no-close-on-backdrop" ? on the Form r a div? Bootstrap modal has various DIV...
