### ISSUE TITLE
Popover - TypeError: Cannot read property 'position' of undefined

### ISSUE THREAD

**Issue by tsneed290** [bootstrap-vue/bootstrap-vue#189]
As of 0.11.0.

With binded properties for "show" and "content" of the Popover component, there seems to be a race condition where `content` changes AND `show` is set to true. `content` changes calls `refreshPosition()` where `showState` is true but `_tether` is not defined yet.

Playground information (https://bootstrap-vue.github.io/play/):
JS:
```

data: {
	showPopover: false,
      content: 'Test'
},
methods: {
    clicked() {
      this.content = this.content + 'T'
      this.showPopover = !this.showPopover
    }
}
```

Template:
```
<b-btn class="mb-4" @click="clicked">Show Popover</b-btn>

<b-popover :content="content" triggers="false" :show="showPopover">
	<span>
      Test
	</span>
</b-popover>
```

**Comment by pi0** [comment]
@tsneed290 Thanks for reporting :) I was thinking of remove tether dependency it is forcing us to fix with ugly hacks. But anyway will be fixed soon. (Or feel free opening a PR for that)

**Comment by SirLamer** [comment]
I'll check this out, I think it can be fixed.

If we were to remove Tether, what would we replace it with? It handles the popup stuff quite well. I don't think this issue is really because of Tether, it has more to due with how Vue reacts to changes in bulk before the DOM refreshes, I think.

**Comment by SirLamer** [comment]
Fixed here: https://github.com/bootstrap-vue/bootstrap-vue/pull/191

Thanks!
