### ISSUE TITLE
tooltips stay open when element disabled and tooltip visible

### ISSUE THREAD

**Issue by nburlett** [bootstrap-vue/bootstrap-vue#1892]
Example here: https://jsfiddle.net/x5ukfe8L/8

In the example, there are two buttons:
- The red button has `v-b-tooltip` directly on the button
- The green button has it on a span surrounding the button

When clicking either button:
1. both buttons are disabled 
3. an alert is shown
2. after 1500ms both buttons are enabled

For the red button, the tooltip shown on hover won't disappear after the click. For the green button, it goes away when the mouse moves out of the button. (For Chrome Version 67.0.3396.87)

On Edge, the green button's tooltip doesn't disappear reliably. 

On Firefox, the red tooltip will go away if the mouse renters and leaves the button.

**Comment by doncatnip** [comment]
Tooltips also do not disappear when the the tooltipped element or any of its parent is hidden via v-if directive.

**Comment by tmorehouse** [comment]
They should dissappear for v-if (although might be an issue in a `keep-alive`), as they are (supposed to be) removed on beforeDestroy.

As per the disabled state, if the trigger happens before the button is disabled, and the button is then disabled while the tooltip or popover is still open... it will remain open (as by design).  See example: https://bootstrap-vue.js.org/docs/components/popover#advanced-b-popover-usage-with-reactive-content

But if the button is disabled before the popover/tooltip is open, then the tooltip/popover wont open on trigger.,

**Comment by tmorehouse** [comment]
Although I do notice on your fiddle that the tooltips don't move with the button (when the alert shows and pushes them down).  Which they should move... I'll have to see if there have been any changes to the tooltip/popover back-end code too see if there have been changes to it, as I know that this used to work.

**Comment by tmorehouse** [comment]
But as per your issue title "tooltips stay open when element disabled and tooltip visible", that functionality is as designed (i.e. staying opened when trigger element is disabled after open).

**Comment by tmorehouse** [comment]
The default trigger for tooltips is "focus hover", which means that a focus and/or hover will trigger the tip to open.  If both trigger events happen (i.e. focus and hover), then both triggers also have to happen (focus-out and un-hover) to trigger the close of the tooltip.

**Comment by doncatnip** [comment]
> But as per your issue title "tooltips stay open when element disabled and tooltip visible", that functionality is as designed (i.e. staying opened when trigger element is disabled after open).
Okay, but how would I go about this if I want the tooltip to behave like expected - i.E. it closes when I leave the element, regardless of its enabled/disabled state ?

https://codepen.io/anon/pen/QXNRVz

Right now, I have to do weird workarounds which cannot be the goal here.

**Comment by tmorehouse** [comment]
Place your tooltip on an outer wrapper element, rather than the disabled button element.

**Comment by doncatnip** [comment]
Weird workaround. It's fine though :) You're doing awesome work - Thank you !

**Comment by tmorehouse** [comment]
It is actually the recommended method in Bootstrap V4.3.x https://getbootstrap.com/docs/4.3/components/tooltips/#disabled-elements

**Comment by nburlett** [comment]
I ended up just using a button group as the wrapper anywhere I needed a disabled button with an explanation of why it's disabled. This can even be nested inside of another button group, which is super-handy.

https://jsfiddle.net/rnbzqhjf/2/

**Comment by Dual-Ice** [comment]
I have the same issue
Example: https://jsfiddle.net/zqe8ahwb/
If set popover on button in inputgroup - when you click on button it disabled and popover doesn't disappear.
If wrap button with div and set popover on div - when button is clicked, popover disappeared, but button doesn't look as part of input group.
What am I doing wrong

**Comment by tmorehouse** [comment]
@Dual-Ice you need to place the popover on the input-group-append or -prepend

See here an example here https://jsfiddle.net/c2pvsw61/
