### ISSUE TITLE
2.0.0-rc.11 Broke b-form-file

### ISSUE THREAD

**Issue by dominusbelial** [bootstrap-vue/bootstrap-vue#1894]
Os windows 10, browser chrome Version 67.0.3396.87 (same on firefox, opera), b-form file is disabled/hidden and functional, adding plain prop reveals its real position.

![bformfile](https://user-images.githubusercontent.com/2867577/41478118-2b4764f6-708c-11e8-88ba-7817c45cfbe4.png)

live example with no plain prop on b-form-file showing disabled input (click on sign is required)
[http://dominusbelial-002-site2.ftempurl.com/UserImage/1/edit](url)

**Comment by tmorehouse** [comment]
this should be fixed in the latest dev branch. Bootstrap has since changed how the custom file input is structured to get around an IE bug.
