### ISSUE TITLE
'checked' prop has no effect on <b-radio>

### ISSUE THREAD

**Issue by andrewsm80** [bootstrap-vue/bootstrap-vue#1897]
Reproduced on JSBin: http://jsbin.com/jucidup/1/edit?html,js,output

Setting the 'checked' property on a b-radio has no effect. 

For example:
```
<template>
  <div>
    <b-radio :checked="true">Option 1</b-radio>
    <b-radio :checked="false">Option 2</b-radio>
  </div>
</template>
```
results in two unchecked radios. 'Option 1' should be checked.

I'm aware that typical usage has `<b-radio>` as a child of some `<b-radio-group v-model="...">` but this shouldn't be necessary.

Additional details:
OS: Windows 10
Browser: Chrome 67
Bootstrap-Vue version: 2.0.0-rc11

**Comment by tmorehouse** [comment]
Radios don't have a default value. You need to assign a value to them. Not the checks prop is used as the v-model for radios (and checkboxes),  and is not a boolean prop for pre-checking the radios. You need 5o set the v-model to the value of the radio you 2ant pre-checked.
