### ISSUE TITLE
B-Table does not have an aria role unless stacked is defined

### ISSUE THREAD

**Issue by niklilland** [bootstrap-vue/bootstrap-vue#1898]
- Mac OS X (High sierra)
- All browsers
- Version of Bootstrap-Vue: 2.0.0-rc.11
- JSFiddle: https://jsfiddle.net/cqw4abto/

I found that the table created by `b-table` does not have an aria role unless the `stacked` property is defined. If it is not, then the table simply does not have an aria-role. Is this intentional? If so, why?

JSFiddle without stacked (and no role defined): https://jsfiddle.net/cqw4abto/
JSFiddle with stacked defined and subsequent aria role defined: https://jsfiddle.net/8b146se2/

Here is the relevant code:
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/table/table.js#L358

**Comment by tmorehouse** [comment]
For a default table, aria-role is not needed,as the table structure itself defines the role as a table.  When in stacked mode, the CSS `display` is changed from that of `table`, which necessitates the `aria-role` being applied only to stacked tables.
