### ISSUE TITLE
Component and enable to use tippyjs as tooltip

### ISSUE THREAD

**Issue by vairamsvsjdo** [bootstrap-vue/bootstrap-vue#1899]
Component and enable to use tippyjs as tooltip

**Comment by tmorehouse** [comment]
Not enough details provided regarding your issue or request.  Closing for now.

**Comment by vairamsvsjdo** [comment]
How to replace the default tooltip using a different component? When bundled, the default component  must not be included in the build
If this is already possible please let me know how to replace the default with tippyjs

**Comment by tmorehouse** [comment]
You would need to use a 3rd party custom component that uses tippyjs.

Bootstrap V4 uses popper.js for positioning and Bootstrap V4's tooltip component.
