### ISSUE TITLE
Tab - Prop "leaveclass" is not declared in component <Transition>.

### ISSUE THREAD

**Issue by tsneed290** [bootstrap-vue/bootstrap-vue#190]
As of 0.11.0.

Looks like my tabs are starting to throw errors about props (leaveclass/entertoclass) being lower-case.

> [Vue warn]: Prop "leaveclass" is not declared in component <Transition>. Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "leave-class" instead of "leaveClass". 
> [Vue warn]: Prop "entertoclass" is not declared in component <Transition>. Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "enter-to-class" instead of "enterToClass". 

I'm using the bootstrap-vue.esm.js, it's complaing about line 2830 (snippet below):

`return _c('transition',{attrs:{"entertoclass":"show","leaveclass":"show","mode":"out-in"},on:{"after-enter":_vm.afterEnter}}`

**Comment by pi0** [comment]
Already fixed by @mosinve  in 9b78ce478f560cbd72a14adbfea9b00e16cfc75c  will be released soon ;)

**Comment by tsneed290** [comment]
You rock!

**Comment by tsneed290** [comment]
Hey @pi0, when do you guys think you'll make your next release with these fixes?

**Comment by mosinve** [comment]
Already ;) Please checkout current version.
