### ISSUE TITLE
Nuxt and Bootstrap vue css in html head

### ISSUE THREAD

**Issue by mauxtin** [bootstrap-vue/bootstrap-vue#1902]
For some reason, when I push my project on heroku, bootstrap css in included in the head like so

```
<head>
<title></title>
(..)
<style data-vue-ssr-id="90433b46:0 8b4ab2e8:0 2c8d02e5:0 396e4108:0 01194ca0:0 203df954:0 0323c590:0 5ebbc628:0 7e87bec3:0">/*!
--
  | * Bootstrap v4.1.1 (https://getbootstrap.com/)
  | * Copyright 2011-2018 The Bootstrap Authors
  | * Copyright 2011-2018 Twitter, Inc.
  | * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
  | */*,:after,:before{box-sizing:border-box}html{font-family:sans-serif;line-height:1.15;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;-ms-overflow-style:scrollbar;-webkit-tap-highlight-color:transparent
(..)
```

Am I doing something wrong here?? 

I have NPM_CONFIG_PRODUCTION set to true and NODE_ENV set to production already.

The way I include it is same as the docs

```
modules: [
        'bootstrap-vue/nuxt',
        '@nuxtjs/axios',

(...)
```

I understand why this happens when using npm run watch for hot reloading, but I want to have the css in an external file which will be included like any other css (with the < link > )

Any ideas?

**Comment by paolodina** [comment]
I think you could try to configure the `build` section of `nuxt.conf.js` adding [extractCSS](https://nuxtjs.org/api/configuration-build/#extractcss).

```
extractCSS: {
  allChunks: true
}
```
