### ISSUE TITLE
b-table: context parameter is not up to date when using asynchronous item provider 

### ISSUE THREAD

**Issue by stalinone** [bootstrap-vue/bootstrap-vue#1904]
Reproducible fiddle: https://jsfiddle.net/kor98cgL/
Version: 2.0.0-rc.11
Browser: both Chrome 67 and Firefox 60 (macOS 10.13.5)

When the "reset" button is clicked, the context parameter is supposed to be `ctx.sortBy === 'first'`; however as the fiddle shown, it is `'last'`.

The presented fiddle is using async function, but the bug is persisted if provider explicitly return a promise. However, it seems normal when using synchronous provider function.

I guess this might caused by the table busy event is triggered before `sortBy` update event and thus blocked the provider update.

**Comment by henryklukasik** [comment]
I've hit a similar issue with same version  (2.0.0-rc.11) on chromium Version 66.0.3359.181 on Ubuntu (LinuxMint 18.3 - 64-bit). In my case I have a b-table hooked up with a b-pagination to change page and a b-form-select to change the per-page property. When I change the per-page in the b-form-select to increase the number of items per page and end-up with a current page number greater than the total number of pages as per the new per-page selection, the following method in b-table gets called twice, one for the per-page change event and one for the current  page reset by the b-pagination. The first call is processed with the previous page number and the second (which had the proper values) is blocked by the computedBusy property in the if statement. The end result is I have an empty table displayed but for a current page number which should have some rows.

```
    _providerUpdate () {
      // Refresh the provider items
      if (this.computedBusy || !this.hasProvider) {
        // Don't refresh remote data if we are 'busy' or if no provider
        return
      }
      // Set internal busy state
      this.localBusy = true
      // Call provider function with context and optional callback
      const data = this.items(this.context, this._providerSetLocal)
      if (data && data.then && typeof data.then === 'function') {
        // Provider returned Promise
        data.then(items => {
          this._providerSetLocal(items)
        })
      } else {
        // Provider returned Array data
        this._providerSetLocal(data)
      }
    },
```
