### ISSUE TITLE
modal closes when button is inside dropdown menu

### ISSUE THREAD

**Issue by kotfarepra** [bootstrap-vue/bootstrap-vue#1905]
Hi to all 

i have a button inside a dropdown that opens a modal. the problem is that if i click on the modal body it gets closed and also the dropdown gets closed

**Comment by allw1994** [comment]
This is a navbar issue, I got over this by using portal-vue, but the downside of this is that you cannot see the variables inside the modal as they change

**Comment by kotfarepra** [comment]
Thank you  for your input @allw1994 . I went for another way not using that .
