### ISSUE TITLE
Transparent border variant on b-modal

### ISSUE THREAD

**Issue by MystEre84** [bootstrap-vue/bootstrap-vue#1906]
Hi!

I'm pretty new to bootstrap-vue.
My environment is: Ubuntu 16.04.4 LTS, Chrome 64.0.3282.140 64 bits, Firefox 60.0.1 64 bits and Bootstrap vue 2.0.0-rc.2.

I was trying to customize a b-modal. [Here](https://bootstrap-vue.js.org/docs/components/modal/) I saw the footer-border-variant props and [here](https://bootstrap-vue.js.org/docs/reference/color-variants/) in the "Background and border variants" it says that there is a "transparent" variant for borders used by b-modal (and others). So I tried to put footer-border-variant="transparent" on my b-modal but it does nothing (I still have a grey border at top of the footer) while footer-border-variant="warning" works.

So I'm wondering if I'm doing something wrong? or is the documentation wrong? or is there a bug?

You can reproduce this [going here](https://bootstrap-vue.js.org/docs/components/modal/): click the button "Launch demo modal" and modify the modal style. If you add the "border-warning" class to the footer element it changes the border color, but "border-transparent" doesn't exist and display the grey border.

I hope I'm clear enough.

**Comment by MystEre84** [comment]
No I finally kept the grey border.
To get a transparent background on a modal I put "background-color: transparent" on the bootstrap vue class "modal-content"... not sure it's a good way to do it.

**Comment by demiavaliani** [comment]
Can this issue be reopened? I believe it has not been fixed and I am still experiencing the exact same problem. @MystEre84 @tmorehouse
