### ISSUE TITLE
Pagination component: ellipsis not working when limit <= 3

### ISSUE THREAD

**Issue by lbineau** [bootstrap-vue/bootstrap-vue#1912]
Hi,
I think I found a bug on Pagination component.

- Operating system: all (Mac OS X)
- Browser and version: all (Chrome)
- Version of Bootstrap-Vue that you are using: 2.0.0 RC11
- Reduced test cases and potential fixes using: https://codesandbox.io/s/1q2ov4yoxq

How to reproduce the bug: set :limit option to 3 or below
Expected behavior: the ellipsis (3 dots) should appear even if the limit is below or equal to 3.

**Comment by tmorehouse** [comment]
I believe this behaviour is as designed, and documented.

See https://bootstrap-vue.js.org/docs/components/pagination#customizing


> | Prop | Description
> | -- | --
> | limit | Limit the maximum number of displayed page buttons (including ellipsis if present, and excluding first/prev/next/last buttons)


> Ellipsis indicator(s) will only be ever shown at the front and/or end of the page number buttons. For limit values less than or equal to 3, the ellipsis indicator(s) will never be shown for practical display reasons.
