### ISSUE TITLE
Card integration in Tabs Component produces Undefined Error

### ISSUE THREAD

**Issue by lee-alderdice** [bootstrap-vue/bootstrap-vue#1913]
When integrating tabs with cards I am getting an undefined error that I can't seem to debug.

I am currently importing the library at a global level in main.ts in a Vue-Cli v3+ project.  I wanted to reproduce the error on CodePen for you but have little experience in there so it might take me sometime to make an exact replica.  Will update the issue when it is done.

Simple Tabbing works as below:
```
<div class="card-header text-center">
  <h3 class="card-title">
    Build Your Profile
  </h3>
  <h5 class="description">This information will let us know more about you.</h5>
  <b-tabs>
    <b-tab title="Tab 1" active>
      Tab Contents 1
    </b-tab>
    <b-tab title="Tab 2">
      Tab Contents 2
    </b-tab>
  </b-tabs>
</div>
```

![image](https://user-images.githubusercontent.com/11538808/41969232-a11c9c70-79fe-11e8-8559-c74f6d21292b.png)

Wrapping this within b-card produces an error as per the image.

```
<div class="card-header text-center">
  <h3 class="card-title">
    Build Your Profile
  </h3>
  <h5 class="description">This information will let us know more about you.</h5>
  <b-card no-body>
    <b-tabs card>
      <b-tab title="Tab 1" active>
        Tab Contents 1
      </b-tab>
      <b-tab title="Tab 2">
        Tab Contents 2
      </b-tab>
    </b-tabs>
  </b-card>
</div>
```

![image](https://user-images.githubusercontent.com/11538808/41969151-6a38452e-79fe-11e8-9cbb-40e66bc20a6c.png)

**Comment by tmorehouse** [comment]
I believe this is fixed in the latest dev branch via PR #2125
