### ISSUE TITLE
set you own custom color in vue bootstrap

### ISSUE THREAD

**Issue by johnzeus14** [bootstrap-vue/bootstrap-vue#1916]
hello how do you set your custom color in vue bootstrap not using the variant property

**Comment by jjohnson1994** [comment]
I think this is more of a Bootstrap question than a Bootstrap-vue question. See the theming guide [here](https://getbootstrap.com/docs/4.0/getting-started/theming/).

You pretty much just want to override the variables in this scss file https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss
