### ISSUE TITLE
Cannot Enable and then Switch to Tab

### ISSUE THREAD

**Issue by jjohnson1994** [bootstrap-vue/bootstrap-vue#1919]
In b-tab component when controlling tabs using v-model, if I enable a tab and then set the current tab index to the index of that tab to tab will be enabled but not displayed. If I do the above, but add a sligh delay then the tab is enabled and displayed.

```
<template>
  <div>
    <b-container fluid>
      <b-card no-body>
        <b-tabs v-model="tabIndex" card>
          <b-tab title="Tab 0" active>
            <Form @onSubmit="enableTab1"/>
          </b-tab>
          <b-tab :disabled="tab1Disabled" title="Tab 1">
            <Form @onSubmit="enableTab2"/>
          </b-tab>
          <b-tab :disabled="tab2Disabled" title="Tab 2">
            <Form />
          </b-tab>
        </b-tabs>
      </b-card>
    </b-container>
  </div>
</template>

<script>
export default {
  data: () => ({
    tabIndex: 0,
    tab1Disabled: true,
    tab2Disabled: true,
  }),
  methods: {
    enableTab1(callbackTime) {
      this.callbackTime = callbackTime;
      this.tab1Disabled = false;
      this.tabIndex = 1;
    },
    enableTab2(presentingProblem) {
      this.callbackTime = callbackTime;
      this.enableTab2 = false;
      this.tabIndex = 2;
    },
  },
};
</script>
```

Expected result of the above code:
The next tab is enabled and then disabled.

Actual result:
The next tab is enabled but not displayed

**Comment by arturs-buls** [comment]
It is not bootstrap bug, it is just how reactivity in Vue works. 
After `this.tab1Disabled = false;` state is not updated and therefore Bootstrap is blocking tab change. If you will check in Vue devtools, you will see that `this.tabIndex` is set back to 0;
For this case there is Vue.$nextTick(), which is taking callback as parameter.
So your enableTab1 will look something like this
`enableTab1(callbackTime) {
      this.callbackTime = callbackTime;
      this.tab1Disabled = false;
      this.$nextTick(() => {
           this.tabIndex = 1;
      }
    },`

**Comment by wvh** [comment]
I've got a similar problem; I try to switch to the last tab when a new one is created. I use `$nextTick()` but it only works in Chrome. In Firefox, the `tabIndex` always gets reset back to `0`. No matter how often you call `$nextTick()`, the tab only gets added after all those calls.

```javascript
focusOnLastTab: function() {
	// focus on last (new) tab when it's there
	this.tabIndex = Object.keys(this.value || {}).length - 1
	this.$nextTick(function() {
		console.log("focusOnLastTab: tabIndex before:", this.tabIndex)
		this.tabIndex = Object.keys(this.value || {}).length - 1
		console.log("focusOnLastTab: tabIndex after:", this.tabIndex)
	})
},
```

I created a loop and I got to 2000 `$nextTick()` calls (took about 20 seconds with logging). The tab only ever appears after.

Perhaps it's some sort of race issue, I think the `tabIndex` in the v-model somehow gets reset every time before the actual changes.
