### ISSUE TITLE
404 for bootstrap.css.map

### ISSUE THREAD

**Issue by Hamdan85** [bootstrap-vue/bootstrap-vue#1922]
Im getting 404 for the bootstrap.css.map...

**Comment by celston** [comment]
I'm also experiencing this.

**Comment by sschadwick** [comment]
Try adding importing the css files directly in `main.js`:
```javascript
// src/main.js
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';

import App         from './App';
import BoostrapVue from 'bootstrap-vue';
import router      from './staff-router';
import Vue         from 'vue';

Vue.use(BoostrapVue);

new Vue({
  components: {App},
  el:         '#app',
  router,
  template:   '<App/>'
});
```

**Comment by warlock** [comment]
I'm using NUXT.
I solved the problem by copying the ".map" in the "static" directory.
I thought that vue-bootstrap would compress the css code.

``sh
cp node_modules/bootstrap/dist/css/bootstrap.css.map static/
``

Best regards
