### ISSUE TITLE
Feature request: Dynamic stacking of <b-form-radio-group>

### ISSUE THREAD

**Issue by muratkemaldar** [bootstrap-vue/bootstrap-vue#1926]
Hi,

currently, it does not seem possible set the "stacked" prop for radio groups based on breakpoints.

The "stacked" prop is supposed to be boolean only:
https://bootstrap-vue.js.org/docs/components/form-radio

For tables, the "stacked" prop can be boolean or string (the breakpoint).
https://bootstrap-vue.js.org/docs/components/table

Request:
Make the "stacked" prop accept boolean or string, like in tables.

Why?
* We would like to change the stacking behavior based on the breakpoint, because of layouting reasons (We want to avoid "wrapping")
* We would like to avoid writing custom CSS for implementing a dynamic stacking behavior
* Consistency of "stacked" prop thoughout multiple components

Kind regards,
Murat

**Comment by tmorehouse** [comment]
This might be a better request at the official Bootstrap repository, to have the feature officially added to Bootstrap V4 CSS.

**Comment by tmorehouse** [comment]
you could also v-for your radios, and then wrap them in spans that use bootstraps responsive display classes (I.e. display-block-sm, display-inline-md, etc)

**Comment by tmorehouse** [comment]
also note, bootstrap v4 css only has stacked or not stacked radios/checks
