### ISSUE TITLE
Cannot focus <input> inside iFrame which is placed in Bootstrap modal in MS Edge

### ISSUE THREAD

**Issue by purvishah165** [bootstrap-vue/bootstrap-vue#1932]
With MS Edge, I cannot focus inputs inside iFrame inside modals.
I have inserted a sample iFrame in the reduced test case to show input fields do not work if they are in Iframe.
Observed behavior: When I click on the input entry, cursor appears but not able to type. Expected behavior: When I click on the input entry, a cursor appears and I can start typing.

See the following code or click here for a fiddle:
`<div id = "app">`
`<b-btn v-b-modal.modal-center>open modal</b-btn>`
` <b-modal id="modal-center" :no-auto-focus=true :no-close-on-backdrop=true :no-fade=true>`
    `<div slot="modal-header" class="justify-content-center d-flex w-100">`
    `  <h2 class="modal-title">Connect to Online Banking</h2>`
   ` </div>`
  `  <div>`
  ` <iframe src="http://www.samisite.com/test-csb2nf/id43.htm#frame6" frameborder="0" style="width: 100%; height: 50vh;"></iframe>`
   ` </div>`
 ` </b-modal>`
`</div>`
Operating system: Windows 10 Pro (64bit)
Browser and version: Microsoft Edge 42.17134.1.0 (it works with Chrome, Firefox and IE 11 !!!!!)
Version of Bootstrap-Vue: 2.0.0-rc.7 (was working in 0.17.1 in alpha mode )
Reduced test case: [http://jsfiddle.net/4cv7rqeo/16/](url)

**Comment by tmorehouse** [comment]
This is most likely due to the enforce focus feature of Modal.  an iframe is a new document "window".  Focus is leaving the modal and going into the new "window" (the iframe).

Disable the enforce-focus of the modal and see if that helps.

**Comment by tmorehouse** [comment]
You also may need to change the security settings when serving the content for the iframe (via HTTP headers) to allow the focus events to bubble up to the modal from the iframe.
