### ISSUE TITLE
[Tabs] don't support dynamic update

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#194]
Figured that our implementation of Tabs works only when tab-items hardcoded in template.
In my project I need to build tabs in a modal dialog according to what dialog is opened. So i need to update tab-items when modal opens. 
Spent all day to find solution, thought moving tabs init routine from `mounted()` to `updated()` will solve problem.. at playground it worked, but my proj hangs on opening... 
So i'm in need of some help ))

**Comment by pi0** [comment]
Hi vitaly :) I was exactly thinking of that after you last commit :))

First for easier and faster debugging you can use `yarn link` feature. (register local clone with `yarn link` and on real project link it with `yarn link bootstrap-vue`)

As a first attempt we can move mounted logic to a method like `updateTabs()` and just calling that on mounted too. this way we can at least manually call this method more times for example when children are changed for any reason.

**Comment by pi0** [comment]
For making this automatic i think Vue had an special even for child change notifications we can listen and call `updateTabs` on that event.

**Comment by mosinve** [comment]
Hmm...  worth yto try, thanks) 
I already started to look towards scoped slots )))
here some draft - https://jsfiddle.net/cihkem/uqdvksre/

**Comment by mosinve** [comment]
first approach seems to work ))) 
And i spend time to deal this webpack/babel symlink issue.....

**Comment by pi0** [comment]
@mosinve Tabs are now automatically updated without need to any function call :) Please just check example at 0.11.1 (things may be cached, if so you can try it on playground too)

**Comment by pi0** [comment]
@mosinve Is this issue resolved now?

**Comment by mosinve** [comment]
oh, forgot to close issue:)
Yeah, tabs works good. 
Closing...
