### ISSUE TITLE
Module build failed: BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by volkovmqx** [bootstrap-vue/bootstrap-vue#1940]
Hey, 
as reported here, the 4.1.2 released few hours ago from Bootstrap is failing to build. check this out https://github.com/browserslist/browserslist/issues/266 . a quick fix is to set the bootstrap version to 4.1.1, until they fix this.

**Comment by volkovmqx** [comment]
a quick fix for this is to add explicitly the 4.1.1: 
"bootstrap-vue": "^2.0.0-rc.11",
"bootstrap": "4.1.1",

**Comment by ai** [comment]
@pi0 seems like there is a outdated dependency which requires very old Browserslist 2.x.

Just call `npm ls` to find the dependency and update it.

**Comment by daniti** [comment]
Thank you so much @volkovmqx . I was stuck with this for a few days.

**Comment by mcclone2001** [comment]
Hi guys, im having this exact isue, but im a noob, im using laravel so i dont have a dependency listed on my package.json, i do have that dependency listed in pachage-lock.json, but i dont know what should i change here.

```
        "bootstrap": {
            "version": "4.1.2",
            "resolved": "https://registry.npmjs.org/bootstrap/-/bootstrap-4.1.2.tgz",
            "integrity": "sha512-3bP609EdMc/8EwgGp8KgpN8HwnR4V4lZ9CTi5pImMrXNxpkw7dK1B05aMwQWpG1ZWmTLlBSN/uzkuz5GsmQNFA=="
        },
        "bootstrap-sass": {
            "version": "3.3.7",
            "resolved": "https://registry.npmjs.org/bootstrap-sass/-/bootstrap-sass-3.3.7.tgz",
            "integrity": "sha1-ZZbHq0D2Y3OTMjqwvIDQZPxjBJg=",
            "dev": true
        },
        "bootstrap-vue": {
            "version": "2.0.0-rc.11",
            "resolved": "https://registry.npmjs.org/bootstrap-vue/-/bootstrap-vue-2.0.0-rc.11.tgz",
            "integrity": "sha512-LxR+oL8yKr1DVoWUWTX+XhiT0xaTMH6142u2VSFDm4tewTH8HIrzN2YIl7HLZrw2DIuE9bRMIdWJqqn3aQe7Hw==",
            "requires": {
                "bootstrap": "4.1.2",
                "lodash.get": "4.4.2",
                "lodash.startcase": "4.4.0",
                "opencollective": "1.0.3",
                "popper.js": "1.14.3",
                "vue-functional-data-merge": "2.0.6"
            }
        }
```

**Comment by volkovmqx** [comment]
hey @mcclone2001 
you don't have to change anything, just add that like in your package.json.

**Comment by mcclone2001** [comment]
Thanks @volkovmqx, added it to package.json, this is my dependencies list in there

    "dependencies": {
        "bootstrap-vue": "^2.0.0-rc.11",
        "bootstrap": "4.1.1",
        "webpack": "^3.12.0"
    }

Working like a charm, and waiting for a fix from bootstrap
