### ISSUE TITLE
Using with Tabler css

### ISSUE THREAD

**Issue by rlightner** [bootstrap-vue/bootstrap-vue#1941]
I notice when opening a Modal it adds the 'data-padding-right' attribute and adds 6px to the right padding, which jerks the ui over. Is there a particular reason for this?

**Comment by tmorehouse** [comment]
Model adds padding to compensate for the scroll bar on the right hand side of the page.

There have been some improvements in modal in the latest dev branch which may address your issue.

Not familiar with "tabler css".
