### ISSUE TITLE
Do not use built-in or reserved HTML elements as component id: header

### ISSUE THREAD

**Issue by FrancescoMussi** [bootstrap-vue/bootstrap-vue#1944]
The header of my `b-card` is not being displayed:

```
<div slot="header">
        ...content...
</div>
```

I get this error message instead:

`Do not use built-in or reserved HTML elements as component id: header`

![screen shot 2018-07-16 at 11 12 34](https://user-images.githubusercontent.com/5312907/42748581-6061ebdc-88e9-11e8-9b7b-1f0ac70a6499.png)

These are my current versions:
```
vue: 2.5.16
bootstrap-vue: 1.5.1
```

**Comment by mosinve** [comment]
`b-card` don't add any id's to `header` slot, so it could be an error in your code.
