### ISSUE TITLE
<pre> is rendered differently from Bootstrap

### ISSUE THREAD

**Issue by Torniojaws** [bootstrap-vue/bootstrap-vue#1948]
OS: Ubuntu 16.04
Browser: Firefox Quantum 61.0.1
Bootstrap-Vue version: 2.0.0-rc.11

```
<template>
  <b-row>
    <b-col>{{ text }}</b-col>
  </b-row>
</template>

<script>
export default {
  data () {
    return {
      text: 'Example <pre>message</pre>'
    }
  }
}
</script>
```

The ``<pre>message</pre>`` is rendered differently than in Bootstrap:

Bootstrap-Vue:
![image](https://user-images.githubusercontent.com/5442750/42873473-bfabd3ce-8a87-11e8-88a8-3603ef69e03e.png)
Inspector shows:
![image](https://user-images.githubusercontent.com/5442750/42873510-d9fb97c8-8a87-11e8-9b93-178d9adb208c.png)

Bootstrap:
![image](https://user-images.githubusercontent.com/5442750/42873557-f5b593b0-8a87-11e8-9006-b85db45c810b.png)
Inspector:
![image](https://user-images.githubusercontent.com/5442750/42873585-08bba6a2-8a88-11e8-80c1-770a59e40f66.png)

I didn't find any comments regarding style differences in the Bootstrap-Vue documentation, so I assume this is not yet implemented?

**Comment by mosinve** [comment]
Please provide working example capable to reproduce this issue

**Comment by tmorehouse** [comment]
Bootstrap-Vue uses Bootstrap V4's CSS, ensure that you are importing the correct version of hte CSS.
