### ISSUE TITLE
addons support for input groups

### ISSUE THREAD

**Issue by pixelbucket** [bootstrap-vue/bootstrap-vue#195]
I've modified my form-input.vue locally to allow input groups. No real testing has been done outside of my personal use case so no pull request.  I'm also pretty sure doing this with named slots would be better to allow for things like checkboxes. I only needed it to add some dollar signs, so this way works for me.

**form-input.vue template becomes:**

```html
<template>
<div class="input-group">
    <div v-if="addonLeft" v-html="addonLeft" class="input-group-addon"></div>
    <input :type="type" :value="value" :name="name" :id="id || ('b_'+_uid)" :disabled="disabled" ref="input" :is="textarea?'textarea':'input'" :class="['form-control',inputClass]"
        :rows="rows || rowsCount" :placeholder="placeholder" @input="onInput($event.target.value)" @change="onChange($event.target.value)" @keyup="onKeyUp($event)"
        @focus="$emit('focus')" @blur="onBlur()" />
    <div v-if="addonRight" v-html="addonRight" class="input-group-addon"></div>
</div>
</template>
```

**Add props for addonRight and addonLeft...**
```javascript
        addonRight: {
          type: String,
          default: null
        },
        addonLeft: {
          type: String,
          default: null
        },
```

**And then use like this:**
```html
<b-form-fieldset label="Price" :label-size="5" horizontal>
  <b-form-input v-model="item.price"addon-left="$"  />
</b-form-fieldset>
```

**Comment by pi0** [comment]
@pixelbucket Hi and thanks for suggestion, About slots yes i think it would be a better approach. We will add addons support soon in next releases :)

**Comment by tmorehouse** [comment]
V4 input groups allow for multiple left or right addons now.  So maybe a slot for left and slot for right, and introduce a new component for addon (which would use a default slot for the addon content)

**Comment by tmorehouse** [comment]
PR #266

**Comment by tmorehouse** [comment]
This PR created new components for `input-group`s and `input-group-addon`s

**Comment by pi0** [comment]
Thanks to @thomasfowler . Will be available soon.

**Comment by tmorehouse** [comment]
PR #267 adds support for `input-group-button` (although dropdown button is not supported)

**Comment by pi0** [comment]
Added in 0.14.0 :)

**Comment by MarZab** [comment]
Getting a warning while using the left slot:

> Duplicate presence of slot "left" found in the same render tree - this will likely cause render errors. 
(found in <BInputGroup>)

**Comment by pi0** [comment]
@MarZab Thanks for report of typo. Will be fixed in next release soon.
