### ISSUE TITLE
_rowVariant stops working after Select All / Unselect All scenario

### ISSUE THREAD

**Issue by alphatrust-dev** [bootstrap-vue/bootstrap-vue#1952]
The _rowVariant feature stops working after doing a Select All / Unselect All scenario.

Here's a sandbox example of the issue.  https://codesandbox.io/s/6jow47nqlr

The steps to recreate are as follows:

1. load project (data will take 1 second to load into the grid)
2. There will be 5 rows on the page, select and unselect all checkboxes for each of the 5 rows.  You will notice how they all highlight blue (info variant) and then return to the default variant.
3. check the "Select All" checkbox in the header to select all the rows at once.
4. uncheck the "Select All" checkbox in the header to unselect all the rows at once.
5. Select and unselect all checkboxes for each of the 5 rows.  You will notice how they all still highlight blue (info variant) and then return to the default variant.

The above works as desired.  Here's where the issue happens:

1. Reload the project/page
2. check the "Select All" checkbox in the header to select all the rows at once.
3. uncheck the "Select All" checkbox in the header to unselect all the rows at once.
4. There will be 5 rows on the page, select and unselect all checkboxes for each of the 5 rows.  You will notice how NONE of the rows highlight blue (info variant) like they did previously.

There are no console errors when this happens.

Windows 10, 
Chrome (latest), 
"vue": "^2.5.16"
bootstrap-vue": "^2.0.0-rc.11"

**Comment by mosinve** [comment]
It's not a table issue, but your code. You have problems with reactivity, when add new properties to records items

**Comment by alphatrust-dev** [comment]
Interesting - I didn't know about the caveat.  However, when I changed my code to the workaround they suggested, I still get the same behavior.  Here's an updated code sandbox: https://codesandbox.io/s/jp4xmmv1v

**Comment by mosinve** [comment]
https://codesandbox.io/s/ym84kymj49 - here's your working example

**Comment by alphatrust-dev** [comment]
Oh wow - sorry, I was way off. lol Thanks!!!
