### ISSUE TITLE
[Feature Request] Would love to see b-blockquote and b-callout as components

### ISSUE THREAD

**Issue by ggedde** [bootstrap-vue/bootstrap-vue#1953]
it would be really convenient to be able to use `<b-blockquote>` and `<b-callout>`
With props like "title", "variant", "align", etc.

Otherwise I am adding a lot of additional classes etc that is cluttering up my markup and additional time to my workflow.

Thanks

**Comment by tmorehouse** [comment]
`b-blockquote` would be an easy functional component to create, as it is a standard bootstrap markup. `callout` doesn't appear to be a native bootstrap V4 component/markup.

**Comment by tmorehouse** [comment]
There are so many options that people would want, that handling all the options (positioning, alignment, etc) that it would be better for people to generate their own custom component that suits their needs/style best.
