### ISSUE TITLE
Cursor jumps to end of string in form inputs in Safari

### ISSUE THREAD

**Issue by justin1364** [bootstrap-vue/bootstrap-vue#1956]
This bug occurs in mobile/iOS Safari.

Repro: 
- open https://bootstrap-vue.js.org/docs/components/form-input in Safari
- Type a long string into the form input at the top of the page
- With your mouse, select in the middle of the string, and try to type
- After the first keystroke, the cursor jumps to the end of the string

**Comment by mwickens** [comment]
This is a dupe of issue [1951](https://github.com/bootstrap-vue/bootstrap-vue/issues/1951).

**Comment by mosinve** [comment]
Duplicate of #1951

**Comment by eemsong** [comment]
I have issue with cursor jumping to the end of string in input field on Safari. Is this issue being fixed?
