### ISSUE TITLE
Feature Request: Add left\right image options for images in card

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#1958]
Currently an image can be added to top\bottom. It would be sweat to have left\right option from the box.
Example: https://getbootstrap.com/docs/4.0/examples/blog/

**Comment by toadkicker** [comment]
Did some digging into this and there are a couple of 'gotchas':

- Height of the parent `.card` container needs to be set
- `.card.flex-row` needs to be used
- height and width of image needs to be set
- border-radius of top and bottom needs to be set on the image

**Comment by tmorehouse** [comment]
merged into `dev` branch
