### ISSUE TITLE
b-dropdown split link

### ISSUE THREAD

**Issue by AdamMarsden** [bootstrap-vue/bootstrap-vue#1960]
Is there any possible way on `b-dropdown` `split` that the button that is split off to allows links like `to=""`.

Ways I've tried either nest inside `button` OR apply to the parent `div.dropdown`

Workaround at the moment involves this:

```
<b-dropdown right split @click="goToUrl" text="Split Button" size="sm">
    <b-dropdown-item to="/tomyurl">Link 1</b-dropdown-item>
    <b-dropdown-item to="/tomyurl">Link 2</b-dropdown-item>
    <b-dropdown-item to="/tomyurl">Link 3</b-dropdown-item>
</b-dropdown>

<script>
export default {
    methods: {
        goToUrl() {
            this.$router.push('/gotourl')
        }
    }
}
```

**Comment by petr0001** [comment]
Would be great to have attributes "to" and "href" as well.

Another thing I'd like to do is specify attribute "variant" separately for the button and for the toggle (currently they both have the same variant).

So would be great to have support for something like this (with optional "variant-toggle" prop):
```
<b-dropdown right split text="Split Button" size="sm" href="/hello" variant="success" variant-toggle="primary">
```

**Comment by roberto910907** [comment]
Same here. Using @AdamMarsden workarounf in the meantime!
