### ISSUE TITLE
table filter result is not accurate

### ISSUE THREAD

**Issue by dounai1306** [bootstrap-vue/bootstrap-vue#197]
you demo: https://jsfiddle.net/a5s95a3q/

There are two person full name field "djamil Carney" data,when filter"djamil Carney",but the results show only one,not two.

At the same time, when the filter, paging number does not change with results in real time.

So trouble you for this surface gives relevant solutions, thank you

**Comment by mosinve** [comment]
Hi!
First part of issue doesn't reproduce - in your example there are two 'Jami Carney' persons, when set filter 'Jami Carney', showed all of them ;)
second part, about pagination, is a confirmed bug. Thank you for participitation ;)

**Comment by dounai1306** [comment]
On the search, the problem is reproduced as follows
1, open https://jsfiddle.net/a5s95a3q/
2. **Click "Person Full name" to sort**
3, enter "Jami Carney" to filter
The results show one

Refresh the page, enter "Jami Carney",the results show two

**Comment by mosinve** [comment]
Yep, this way confirmed. 
Problem somehow linked to sort action.

**Comment by dounai1306** [comment]
I see u https://github.com/bootstrap-vue/bootstrap-vue/pull/198 fixed pagination when filtered table

but I updated to 0.11.1,the question remains

**Comment by mosinve** [comment]
It's not merged yet.
Found that filter proglem was in global key in regex. When we use it, in the case of 2 identical entries in succession, regex not return true for first test string. 
http://stackoverflow.com/questions/1520800/why-regexp-with-global-flag-in-javascript-give-wrong-results

**Comment by dounai1306** [comment]
I copy u demo https://jsfiddle.net/dounai/wofq6dwd/1/

you can see , i added a 'c' to the 'name' field of each data,when i enter "c" to filter table,the result is not accurate

**Comment by dounai1306** [comment]
These questions will be about when to repair and release?

Thank you very much for your prompt reply

**Comment by dounai1306** [comment]
Problem has been solve,thx

close issues
