### ISSUE TITLE
Table Header Slot with b-form-checkbox event suppressed

### ISSUE THREAD

**Issue by akhchan99** [bootstrap-vue/bootstrap-vue#1971]
- Version of Bootstrap-Vue : 2.0.0-rc.11

I was looking at issue # 719 [https://github.com/bootstrap-vue/bootstrap-vue/issues/719](url)

and I tried to modify the table's header's checkbox from **<input type="checkbox"** to **<b-form-checkbox** and all the events from the b-form-checkbox were suppressed, I couldn't get neither click or change event.  When I move the b-form-checkbox out of the table header slot, then all the events were detected.

Is it a bug? any workaround?  The reason I want to change it to use the b-form-checkbox is that I want to use the tri-state as shown in the documentation

**Comment by briandhill** [comment]
I'm having the same problem where I can stopPropagation with a `<input type="checkbox />` using the `.stop` event modifier, but it does not work for the `<b-form-checkbox />` when appending the `.stop` event modifier to the `@input` or `@change` event handler. It actually throws an error if I append the `.stop` event modifier.

Any help would be greatly appreciated!

**Comment by akhchan99** [comment]
This is what I uses, hope this help

```
<template slot="HEAD_selected" slot-scope="data">
  <b-form-checkbox v-b-tooltip title="Toggle Select All" @change="toggleSelectAll" v-model="allSelected" :indeterminate.sync="indeterminate"/>
</template>
```

**Comment by tmorehouse** [comment]
@briandhill the `input` and `change` events on b-form-checkbox/radio are custom events, not native events.

The latest version of BootstrapVue should automatically prevent the click from propagating up to a row-clicked or head-clicked event.

Make sure you are using the latest v2.0.0-rc.15 or greater.

**Comment by briandhill** [comment]
So what I'm trying to do is pass a wrapped `b-form-checkbox` to the header slot of a wrapped `b-table`.

```
// View
<wrappedBTableComponent>
  <template slot="HEAD_example_inner" slot-scope="data">
    <wrappedBCheckboxComponent />
  </template>
</wrappedTableComponent>

// wrappedBTableComponent
<b-table>
  <template slot="HEAD_example" slot-scope="column">
    <slot name="HEAD_example_inner" :column="column">
  </template>
</b-table>
```

But when I attempt to check the checkbox, it doesn't check the box or fire off any events for the checkbox component. It does however fire off the `head-clicked` event.

So I got it to work with a regular input checkbox with `@click.stop`, but I can't seem to get it to work with a `b-form-checkbox`.

**Comment by briandhill** [comment]
Apologies, I updated to v2.0.0-rc.15 that seemed to fix it. We were on v2.0.0-rc.11. Thanks for your help!
