### ISSUE TITLE
b-form-group breakpoint missing for bootstrap 4

### ISSUE THREAD

**Issue by Dam720** [bootstrap-vue/bootstrap-vue#1973]
Hello,

We can't set breakpoint empty in `b-form-group` props, for something like `col-6`. If we set ` breakpoint=""` it will output `col--6` but it should be `col-6`.

``` js
//src/components/form-group/form-group.js 
//lines 237-246

labelLayoutClasses () {
    return [
        this.horizontal ? `col-${this.breakpoint}-${this.labelCols}` : null
    ]
},
inputLayoutClasses () {
    return [
        this.horizontal ? `col-${this.breakpoint}-${12 - Number(this.labelCols)}` : null
    ]
},

```

**Comment by tmorehouse** [comment]
We may need to covert the use of the breakpoint to a computed property, which can handle converting a space (or non numeric value) to the default of 6.

**Comment by tmorehouse** [comment]
PR #2258 revamped `b-form-group` quite a bit (allowing multiple breakpoints), and should address this issue.
