### ISSUE TITLE
b-btn/b-button not spacing out

### ISSUE THREAD

**Issue by MikeJWms** [bootstrap-vue/bootstrap-vue#1977]
Hello,

I'm experiencing a problem with b-btn/b-button element and their default spacing not being inherited in my app.

Here's what I'm experiencing:
![image](https://user-images.githubusercontent.com/17638183/43488616-2d9f5c10-94cf-11e8-89e5-67f8d93a3cd0.png)

Tested on MacOS 10.13.4 and Win10 with chrome and firefox

App created with @vue/cli V3, problem replicated on default config.

Here's the desired behavior. Notice that the buttons are seperated.
![image](https://user-images.githubusercontent.com/17638183/43488896-068dd286-94d0-11e8-8688-a93261923557.png)

Thanks for your help.

**Comment by tmorehouse** [comment]
Vue removes excess whitespace from the rendered HTML.

Use the margin utility classes to add a left (or right) margin to one of your buttons.  Or place an `&nbsp;` between them.

**Comment by rr326** [comment]
Question: Why doesn't vue-bootstrap include this extra margin in it's css? It IS *vue*-bootstrap, after all.

oddity - it works without the extra space with nuxt, but not with plain vue.

**Comment by tmorehouse** [comment]
It depends on the settings for Vue template compiler via  Vue Loader (if using a module bundler), or if using DOM or string templates.  String templates preserve whitespace (the docs use string templates for the live examples)

Nuxt may have predefined vue-loader options for stripping out whitespace between element tags.

https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#api

i.e.
```html
<div>
  <div>Foo</div>
  <div>Bar</div>
</div>
```

becomes:
```html
<div><div>Foo</div><div>Bar</div></div>
```


BootstrapVue uses Bootstrap v4.4 CSS, we don;t override any of hte Bootstrap CSS.
