### ISSUE TITLE
b-checkbox label's for not working in SSR mode

### ISSUE THREAD

**Issue by varyen** [bootstrap-vue/bootstrap-vue#1978]
Hello, there's a problem with `b-checkbox` in SSR mode (it works as expected in SPA mode). If you don't pass id like that
```<b-form-checkbox>test</b-form-checkbox>```

label won't get `for` attribute. Can be easily checked in fresh nuxt-edge installation.
I suppose it also happens in `b-radio component` and other components using `this.safeId()` multiple times before `localId_` actually get computed.

**Comment by varyen** [comment]
I don't know why, but it can be fixed by adding empty `styles: {}` to `description` VNode.

**Comment by Nico264** [comment]
I guess this is the same issue as https://github.com/bootstrap-vue/bootstrap-vue/issues/1820

**Comment by tmorehouse** [comment]
I think an earlier change to the safeId mixin broke SSR rehydration (the ID gets generated before mount)

**Comment by tmorehouse** [comment]
@varyen This should be fixed in the latest `dev` branch.  Could you give it a try?
