### ISSUE TITLE
popover targets aren't working with $refs and "/play" locks up

### ISSUE THREAD

**Issue by InstanceOfMichael** [bootstrap-vue/bootstrap-vue#1979]
On both firefox and chrome, it seems really easy to lock up and break https://bootstrap-vue.js.org/play/ I can't copy any specific examples because it locks up the browser, and i can't undo anything because it remembers the html that locks it up if you choose to return after firefox/chrome warn about the page being locked up.

```html
  <div class="d-flex flex-column text-md-center">
    <div class="p-2">
      <b-btn ref="popoverButton" variant="primary">I have a popover</b-btn>
    </div>
    <div class="p-2">
      <b-popover :target="$refs.popoverButton" title="Popover">
        Hello <strong>World!</strong>
      </b-popover>
    </div>
  </div>
```

I'm trying to make the popover work with $ref instead of using id. The docs https://bootstrap-vue.js.org/docs/components/popover/ says it's allowed, but I can't get it to work.

```
[Bootstrap-Vue warn]: b-popover: 'target' element not found!
```

After reading the source code, I decided to try a wild expirement (as in, it was NOT clear this should work) https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/mixins/toolpop.js#L234

replacing:
```
      <b-popover :target="$refs.popoverButton" title="Popover">
```
with 
```
      <b-popover :target="() => $refs.popoverButton" title="Popover">
```
worked in both the sample I provided and in my code. Is this a bug or should the docs be updated?

It currently says:

> The target element must exist in the document before <b-popover> is mounted. If the target element is not found during mount, the popover will never open. Always place your <b-popover> component lower in the DOM than your target element.
>
> target: Element string ID, or a reference to an element or component, that you want to trigger the popover. Required
```

which is clearly wrong and misleading as written as my example demonstrates.

**Comment by natemartinsf** [comment]
I just ran into this same issue. Thanks for the workaround above.

**Comment by michaelzangl** [comment]
This should be added to to the popover docs. It is illustrated in the tooltip docs and works since popovers extend the tooltip code. See https://bootstrap-vue.js.org/docs/components/tooltip -> Component Usage

**Comment by tmorehouse** [comment]
The playground issues has been fixed in the latest dev branch (which will be released soon)

Regarding `$refs`, `$refs` is usually not available until after mounting.

If someone would like to make a PR on the docs, that would be great.
