### ISSUE TITLE
[Docs] image source resolving

### ISSUE THREAD

**Issue by xorbis** [bootstrap-vue/bootstrap-vue#1982]
https://bootstrap-vue.js.org/docs/reference/images/ refers to transformToRequire but it does not exist anymore. I think it's now transformAssetUrls.

It would also be nice if an example on how to do that with vue-cli and it's vue.config.js.

**Comment by tarazena** [comment]
Finally i was able to get it to work, transformAssetsUrls is what was wrong in the docs
here is what you need to do

1. create `vue.config.js` in the root directory (next to `package.json`.
2. put the following code
```javascript
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('vue')
      .use('vue-loader')
      .loader('vue-loader')
      .tap(options => {
        options["transformAssetUrls"] = {
          'img': 'src',
          'image': 'xlink:href',
          'b-img': 'src',
          'b-img-lazy': ['src', 'blank-src'],
          'b-card': 'img-src',
          'b-card-img': 'img-src',
          'b-carousel-slide': 'img-src',
          'b-embed': 'src'
        };

        return options;
      });
  }
}
```

**Comment by tarazena** [comment]
and I agree the docs need's to be updated

**Comment by xorbis** [comment]
Ok it works, I had to restart the vue-cli serve task.
Thanks!!
