### ISSUE TITLE
Custom classes for <b-popover> and <b-tooltip> components

### ISSUE THREAD

**Issue by haggins** [bootstrap-vue/bootstrap-vue#1983]
At the moment it's not possible to give the popover container a custom class. If you do a
`<b-popover class="info">...</b-popover>` right now, your class just won't be added.

Usecases:

- Popovers with different contexts and therefore different styles (e.g. 'info', 'action', 'important' etc)
- Popovers with dynamic class binding to states (e.g. class 'moving' to give the popover some opacity while its target is beeing dragged)

**Comment by tmorehouse** [comment]
You can provide a custom popover template to the popover (using the custom config option). not an ideal solution, but it is available,

**Comment by tmorehouse** [comment]
In the case of a popover trigger element (i.e. a button or link), you can currently play whatever custom class on the trigger element you like.

```html
<b-btn class="foo-bar" id="mybutton">Button Content</b-btn>
```

The OP was asking for this class to be "hard-coded" for them.

**Comment by haggins** [comment]
> The OP was asking for this class to be "hard-coded" for them.
No, I was asking to pass custom classes to `<b-popover/>` just as you did with `<b-btn/>`.
I haven't tried your proposal to use a custom template yet.

**Comment by tmorehouse** [comment]
Ah, right... I was confusing this with a similar issue for custom classes on a trigger element.

**Comment by haggins** [comment]
NP :-)

**Comment by tmorehouse** [comment]
You can provide a custom template string (html string) to popovers and tooltips via the config value object.  As long as the template string has the required classes, just add your custom class added to the appropriate place,

Note the config object can only be passed with the directive version of popover at the moment.

We could look into adding a popover template prop to the component version.

**Comment by lazehang** [comment]
For now i think we can specify `container` with a id value and it would append the popover to the element having the id. 
`<b-popover :target="targetID" triggers="focus" container="someID">`
I am not sure if thats exactly what you want but it helped me.
Again apologies, if i misunderstood your concern.

**Comment by michaelzangl** [comment]
Workaround:

```
<b-popover @show="onPopoverShow" ref="myPopover"/>

methods: {
  onPopoverShow() {
    this.$refs.myPopover._toolpop.getTipElement().classList.add('my-class')
  }
}
```

**Comment by tmorehouse** [comment]
I'm thinking we could add a prop `custom-class` to b-popover and b-tooltip components, which would get transferred to the underlying tooltip/popover JavaScript class instance. we can't use 'class as the prop, as it has special meaning to Vue... so would need a special prop name.

**Comment by tmorehouse** [comment]
We are going to be revamping tooltips, popovers, modal, and the forthcoming toast components once Portal-Vue 2.0.0 move out of beta, so we will be adding in this feature at that point in time.

**Comment by ggedde** [comment]
I agree that any component that renders a container should have the ability to set custom classes on that container.  I am fine with `custom-class` or since the component renders a container then maybe `container-class`

**Comment by tmorehouse** [comment]
Will be available in the stable release 2.0.0.

Hang tight we are working on it.

**Comment by ggedde** [comment]
@tmorehouse Awesome!
PS.  for consistency sake if a component already has a feature like [dropdown] has `menu-class` maybe `custom-class` or `container-class` is an alias.  Just a thought.

**Comment by tmorehouse** [comment]
will probably be `custom-class` (since both tooltip and popover share the same base code)

**Comment by michaelzangl** [comment]
I would prefer `container-class`

`custom-class` is too generic and it is difficult to directly see the difference between `class` and `custom-class`

**Comment by tmorehouse** [comment]
Or it might be a simple as `classes` (as it can be a string, array, or object; or an array of strings, objects and arrays)

**Comment by tmorehouse** [comment]
`container-class` might confuse people into thinking it is the class for the element specified via the `container` prop, not the tooltip/popover itself.

**Comment by tmorehouse** [comment]
@haggins @garhbod @lazehang @michaelzangl @ggedde 

BootstrapVue 2.0.0-rc.26 has been released.

It contains support for color variants on tooltips/popovers as well as a the ability to apply an arbitrary class to the root element of the rendered tooltip/popover.

Refer to the docs for more details https://bootstrap-vue.js.org
