### ISSUE TITLE
currentPage page's item dom no active

### ISSUE THREAD

**Issue by liangzeng** [bootstrap-vue/bootstrap-vue#1985]
```
<input type="number" v-model="currentPage"/>
<b-pagination class="col-sm-12" align="center" size="sm" :total-rows="total" v-model="currentPage" :per-page="10"></b-pagination>
```

change input's value , b-pagination component is change ,but no active css effect.

![image](https://user-images.githubusercontent.com/8503065/43692843-4381ef88-995d-11e8-83af-ebb3cff49652.png)

**Comment by 1207915357** [comment]
I have the same problem as you

**Comment by tmorehouse** [comment]
Duplicate of #1629
