### ISSUE TITLE
Chat group with developers

### ISSUE THREAD

**Issue by uharbachou** [bootstrap-vue/bootstrap-vue#199]
Hi, any chats where can ask/consult?

Thanks

**Comment by pi0** [comment]
Hi @uharbachou. Are you ok with Telegram groups? :) (Or any other idea)

**Comment by uharbachou** [comment]
May be better in slack?

**Comment by uharbachou** [comment]
Code highlight, notifications better.

**Comment by pi0** [comment]
@uharbachou hmm personally i'm a Telegram addict :)) However you are right, slack would be better for US :) Will create it soon.

**Comment by uharbachou** [comment]
Thanks 👍

**Comment by pi0** [comment]
Slack is now available :)
