### ISSUE TITLE
Dropdown event bus

### ISSUE THREAD

**Issue by xorbis** [bootstrap-vue/bootstrap-vue#1993]
Windows 10
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Bootstrap-Vue ^2.0.0-rc.11
--
I have a special case in my UI where I need to close all opened b-bropdown components (including b-nav-item-dropdown).

I haven't found how to do so in a similar way as b-tooltip offers.
this.$root.$emit('bv::hide::tooltip');

Something like this would be perfect:
this.$root.$emit('bv::close::dropdown');

**Comment by tmorehouse** [comment]
While not a documented feature, you can `this.$root.$emit` the event `bv::link::clicked` to close all dropdowns,

**Comment by xorbis** [comment]
Works great, thanks!
