### ISSUE TITLE
Launching a modal inside a modal closes the parent

### ISSUE THREAD

**Issue by oliwarner** [bootstrap-vue/bootstrap-vue#1997]
Simple enough. I'm trying to open a modal inside a modal. You could probably argue against the UI ramifications against this but in our use-case, it's worked well in the past under standard Bootstrap. 

When trying the following little test harness you'll click the button and whole thing closes.

```
let v = new Vue({
	template: `
	<b-modal id="visible_modal" title="visible modal" visible>
		<b-btn v-b-modal.modal1>Launch sub modal</b-btn>

		<b-modal id="modal1" title="Sub-modal!">
			<p class="my-4">Hello from sub-modal!</p>
		</b-modal>
	</b-modal>
	`,
})
v.$mount()
document.body.appendChild(v.$el)
```

This probably something to do with the events because if you set the child to be visible from the start, it displays fine.

```
let v = new Vue({
	template: `
	<b-modal id="visible_modal" title="visible modal" visible>
		<b-btn v-b-modal.modal1>Launch sub modal</b-btn>

		<b-modal id="modal1" title="Sub-modal!" visible>
			<p class="my-4">Hello from sub-modal!</p>
		</b-modal>
	</b-modal>
	`,
})
v.$mount()
document.body.appendChild(v.$el)
```

I've tried hooking on a almost every option to try and see if that fixes it but I just don't know enough about the event chains here to what what they're doing (or why).

**Comment by oliwarner** [comment]
Hmm. `show()` is explicitly closing other modals. I tried to remove the body class (which seems to be a prerequisite for that code firing but it didn't work. The events seem pretty un-labelled so I'm not sure if they're cross-contaminating.

Either way, what a mess. This should **not** be the default behaviour.

Finally worked around this by manually showing the inner modal with its (private) `doShow()` method. This bypasses the junk that `show()` is doing.

**Comment by tmorehouse** [comment]
Native Bootstrap V4 (and earlier) does not support multiple open modals at the same time.

See http://getbootstrap.com/docs/4.1/components/modal/

> - Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

**Comment by oliwarner** [comment]
Not supported, but still possible. Bootsrap's JS doesn't seek-and-destroy on show. It doesn't munge all the events through a common root handler rather than direct to the component. I'm still not sure what the advantage of that is supposed to be but BV does it all over the place.

It doesn't have to be this way.

**Comment by tmorehouse** [comment]
Opening a second modal would cause the adjustments to body for the scrollbar to get applied a second time, as there is no easy way to detect how many modals are open at once, and if a modal is the last modal to be closed (so that the adjustments can be removed).

**Comment by sonicmolson** [comment]
I just did this. You have to capture the _hide_ event on the _parent_ vue object and preventDefault - as well as manually removing the _model-open_ class on the body on the _child show_ event.

**Comment by ldurans** [comment]
Estou com a mesma necessidade. @sonicmolson consegues demonstrar como fez?

**Comment by georges49** [comment]
@sonicmolson solution (or hack to be exact) worked for me as well.

**Comment by oliwarner** [comment]
I hacked around this by adding a ref to the modal and calling its internal methods directly:

    this.$refs.modal.doShow();
    this.$refs.modal.hide();

I'm sure it's not perfect (esp re modal background) but it's easy.

I maintain it's shambolic that you have to bypass `.show()` to do this, but I'm still thankful it's wired in such a way that bypassing it is possible without rewriting the component.

**Comment by tmorehouse** [comment]
I think we may have an option in mind to support opening modals over modals (unlike native Bootstrap V4), by keeping track of how many modals are open at the same time.  Although the backdrop would appear  darker each time a new modal is opened over another modal. (backdrops over backdrops)

We're working on a bunch of improvements on various components for the next release.

**Comment by TitanFighter** [comment]
If someone needs a solution to open [Modal over Modal](https://github.com/bootstrap-vue/bootstrap-vue/issues/1513#issuecomment-426991707)

**Comment by luchorengo** [comment]
The @oliwarner solution worked for me. Thanks a lot!

`this.$refs.modal.doShow();`
