### ISSUE TITLE
Update CDN documentation: no tether in package

### ISSUE THREAD

**Issue by wvh** [bootstrap-vue/bootstrap-vue#200]
Hello,

Your documentation on how to include bootstrap-vue from CDN mentions a path of `/tether/dist/js/tether.min.js` path for the tether library, but it doesn't seem to be included in the bootstrap-vue package anymore and returns a 404.

It seems to work fine when directly including the latest tether version available on `unpkg` though.

Perhaps you could update the documentation.

Thanks!

**Comment by pi0** [comment]
Hi wvh. Are you sure? Latest version of both readme and docs should indicate this: 
```html
<script src="//unpkg.com/tether@latest/dist/js/tether.min.js"></script>
```

**Comment by wvh** [comment]
Hah, it got fixed and released just after my bug report and your reply, 3 days ago:

hash: 1772a40e7ca079b6c393191fe706ca0db368ad82

Thanks!
