### ISSUE TITLE
b-form-input type="number" not allowing to enter decimals(.) on Firefox

### ISSUE THREAD

**Issue by soichih** [bootstrap-vue/bootstrap-vue#2000]
I have a number field on my form

```
<b-form-input type="number" v-model.number="param.default" mousewheel.native="$event.preventDefault()"/>
```

I used to be able to enter decimals like "3.5" or "10.0", etc.. but it stopped working recently. I've confirmed that the same issue exists on the bootstrap-vue website - under "Type number:" section (https://bootstrap-vue.js.org/docs/components/form-input/) 

Strangely, I can still enter a decimal if I type it elsewhere, and copy / paste into the form field. b-form-input seems to be preventing me from entering "." character.

**Comment by tmorehouse** [comment]
You might need to add attributes to set the step values

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Allowing_decimal_values

> One issue with number inputs is that their step size is 1 by default — if you try to enter a number with a decimal, such as "1.0", it will be considered invalid. If you want to enter a value that requires decimals, you'll need to reflect this in the step value (e.g. step="0.01" to allow decimals to two decimal places). 

```html
<b-form-input type="number" ... step="0.01" min="0.00" max="1000.00" >
```

**Comment by tmorehouse** [comment]
Check the language/locale settings on your browser.

Number input behaviours change (on some browsers) based on the locale settings (i.e. using `,` instead of `.`)

**Comment by soichih** [comment]
I don't think this is caused by locale setting. I've updated the jsfiddle to include a native input element to show that this issue only happens for b-form-input (on firefox) but works fine for the native input.

**Comment by averied** [comment]
I'm also having this issue. Makes no sense that a user has to touch any locale settings, this should work out of the box. I'm in Spain, and I cannot use the numerical keyboard to enter decimals. The dot (.) key causes the numeric input to blank out. I can even reproduce this in the demo number type input: [https://bootstrap-vue.js.org/docs/components/form-input](url)

**Comment by mihai-macaneata** [comment]
I'm also having this issue and it doesn't seem to be language/locale settings related. 
The b-form-input type number doesn't accept (.) on Firefox. 
Adding step, min, max, lang attributes doesn't help

**Comment by tmorehouse** [comment]
Merged into dev.

**Comment by Branhub** [comment]
Does it work on Firefox 56?

**Comment by tmorehouse** [comment]
It should. You can try the preview version. See #2315

**Comment by ilhansubasi** [comment]
This issue still [exists](https://mil.hesaplama.app) with Firefox 66.0.3 on Windows 10.

![number field in Firefox](https://user-images.githubusercontent.com/762377/56750738-16147580-678d-11e9-99d8-16d60433661b.png)



There is no issue when Gogole Chrome is used:
![number field in Google Chrome](https://user-images.githubusercontent.com/762377/56751013-aeaaf580-678d-11e9-83d0-71f83c875f86.png)
Microsoft Edge 44 behaves as same as Google Chrome 74.


Note that both browsers (Google Chrome and Firefox) are USA English and their first preferred language is USA English too. My Windows is USA English too. The HTML code that I wrote has `<html lang="tr">`.

**Comment by tmorehouse** [comment]
Looking at the page source code I see that you are not even using BootstrapVue (just plain inputs):

```html
	<body>
		<h1>Mil Hesaplama</h1>
		<div id="milDonusturucu">
			<input type="number" v-model="kilometre"> km
			<br>
			<input type="number" v-model="mil"> mil
		</div>
		<script>
			var app = new Vue({
				el: "#milDonusturucu",
				data: {
					kilometre: 0
				},
				computed: {
					mil: {
						get: function() {
							console.log("get");
							return this.kilometre * 0.621371;
						},
						set: function(m) {
							this.kilometre = m * 1.609344;
							console.log("set");
						}
					}
				}
			});
		</script>
	</body>
```

**Comment by ilhansubasi** [comment]
@tmorehouse I'm sorry. I've submitted a new bug report to Vue https://github.com/vuejs/vue/issues/9926

**Comment by tmorehouse** [comment]
Note that even though the input is type `number`, it's value is returned as a string.  Try adding the `.number` modifier on the v-model (`v-model.number="..."`)

**Comment by ilhansubasi** [comment]
Thanks. I've added `.number`. Also `step="any"`.
