### ISSUE TITLE
b-form-file @change handler has the old file value

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#2003]
Using https://bootstrap-vue.js.org/docs/components/form-file/
with a @change handler:

```
<b-form-file v-model="fileCover" :state="Boolean(fileCover)" accept="image/*" @change="fileCoverChange()" placeholder="Choose a file..."></b-form-file>
<div class="mt-3">Selected file: {{fileCover && fileCover.name}}</div>

...
        fileCoverChange () {
            console.log("fileCoverChange", this.fileCover)
        }
```
console.log() shows the previous file value, eg null first time, and if changing the file again, the previous file. We need the current file value (after change, not before).
Is this behavior expected? 
If so, how to get the current file value without relying on v-model property?

Note: "Selected file" shows properly, but maybe fileCoverChange() triggers before the model is set.

- Operating system: Fedora
- Browser: Chrome latest
- Version of Bootstrap-Vue: 2.0.0-rc.11

Thanks!

**Comment by toadkicker** [comment]
AFAIK this would be the correct behavior because the @input event would be what you would want to use in this case. @change event wouldn't have the new file set because @input is what sets the file property.

> @change | original native change event on input
