### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by ejay010** [bootstrap-vue/bootstrap-vue#2004]
What is wrong with these pictures...?
![image](https://user-images.githubusercontent.com/6069216/44793487-5d9e1f80-ab74-11e8-847a-f550b950fb9f.png)

![image](https://user-images.githubusercontent.com/6069216/44793539-7eff0b80-ab74-11e8-9ae9-2b7ffa3bfb15.png)

So the question is am I missing something? Did I do something wrong?

**Comment by tmorehouse** [comment]
Could you provide a bit more detail as to your issue?

**Comment by toadkicker** [comment]
![shrug](https://user-images.githubusercontent.com/523330/45395020-f5206980-b66e-11e8-9056-dedfcec5c094.png)

**Comment by ejay010** [comment]
Honestly it’s the button group. They don’t resize/adjust to fit on mobile. However it resizes on bootstrap. That’s the confusion am having.

**Comment by ejay010** [comment]
But hey I don’t mind giving it a shot at trying to fix it. 😄😄

**Comment by tmorehouse** [comment]
A quick fix would be adding the following CSS to `/docs/assests/styles.css`

```css
.vue-example {
  overflow-y: auto;
}
```

This will allow the rendered example to be scrolled left and right if the content is wider than the available width.  It could be tweaked to be inside a media query to restrict this behaviour to smaller screens.

**Comment by tmorehouse** [comment]
Closing as stale
