### ISSUE TITLE
Dropdown should have same features as Twitter Bootstrap

### ISSUE THREAD

**Issue by lnufnu** [bootstrap-vue/bootstrap-vue#2007]
I’m running into issues similar to #1273 where I would expect Vue Bootstrap to behave more like Twitter Bootstrap.

In Twitter Bootstrap, dropdowns can be triggered from `<a>` or `<button>` elements. Text inside the dropdown can be selected by using an `<a>` element. `<a>` tags without button styling can provide flexibility in turning anything into a dropdown menu: https://codepen.io/lnufnu/pen/pONJpV

Vue Bootstrap limits the ability to use dropdown to buttons. With buttons, `user-select` is `none`. Most users can probably get around using anchor tags with the variants, slots, and by modifying styling, but when using this component heavily in an application, it's not ideal. Extending dropdown functionality to an anchor tag with a `b-dropdown` class would make the syntax more similar to Twitter Bootstrap and provide more flexibility.

Although Twitter Bootstrap does not officially support it, it is very simple to use jquery to create a context menu class that can be applied to any menu, such as this one: http://jsfiddle.net/dmitry_far/cgqft4k3/ 

It seems that not all global keyCodes are exposed on the dropdown module. Doing this would allow users to quickly create native click events similar to other Bootstrap Vue components.

**Comment by slidenerd** [comment]
Not only that I would also like to add that forms are also a part of dropdown items in the original bootstrap code, so adding support for them would be super awesome

**Comment by tmorehouse** [comment]
Re "context menu", as you notice it doesnt use any of the popper.js methods for positioning, and is basically just using the base markup for the menu style.

All other functionality is handled by jQuery: listening for contextclick, figuring out which TR was clicked, determining position of mouse on click.  Note it has no method for not using a mouse to open the context menu (a keyboard only user cannot tab to the row to then click the content menu button).

There is nothing stopping someone from creating their own custom content menu component using bootstrap styles... But I wouldnt want to try to add that to the current Bootstrap-Vue dropdown.

One could still use the helper componetns (b-dropdown-item, b-dropdown-header, etc), as they are not "logically" tied to the parent dropdown.  they just render the links/buttons/headers/etc.

For your original ask... ability to use different tags for dropdown triggers, that is available in the latest `dev` branch (not it will add ARIA roles attributes on non standard tags for accessibility reasons. It also adds click/enter/space handlers on non standard tags (as well as tab-index) for accessibility reasons.

The `dev` branch also has an option to "remove" the dropdown caret.

If one doesn't want the button styling on the toggle button, they can just set the variant to a non-existent one (i.e. `variant="foobar"`) or use the the `link` variant.  And/or one could add a custom class to the dropdown component to override additional styles if necessary, or one could create a theme subset for Bootstrap V4 adding in new "variants", etc.
