### ISSUE TITLE
Popovers do not work IE10

### ISSUE THREAD

**Issue by erisman20** [bootstrap-vue/bootstrap-vue#2010]
- Operating system and version (Windows 10)
- Browser and version (IE 10)
- Version of Bootstrap-Vue (v2.0.0-rc.11)

Get the following error in the console:

SCRIPT438: Object doesn't support property or method 'getAttachment'
tooltip.class.js (310,7)

Popovers work in IE11+, but cant seem to get past this error in IE10.

**Comment by tmorehouse** [comment]
IE10 is not an officially supported browser. Use IE11 or higher
