### ISSUE TITLE
Closing a modal with esc causes console error

### ISSUE THREAD

**Issue by Jamesvandenhoudt** [bootstrap-vue/bootstrap-vue#2011]
- Windows
- Chrome Version 68.0.3440.106 (works fine in Firefox 61.0.2)
- Bootstrap-Vue 2.0.0-rc.8

I am using multiple bootstrap-vue modals, some of which i use with default properties and some with:
:no-close-on-backdrop="true"
:no-close-on-esc="true"

When the modal is open and i press the esc key, the modal doesn't close, which is expected. However, i get an error in the console.
> Error in event handler for runtime.onMessage: TypeError: Cannot read property 'isVisible' of undefined

**Comment by tmorehouse** [comment]
Try with the latest version of Bootstrap-vue 2.0.0-rc.11

**Comment by Jamesvandenhoudt** [comment]
I've tried that and still no joy!

**Comment by tmorehouse** [comment]
Do you see the issue if you have only one modal on the page? Are you using the modal `lazy` prop?

**Comment by Jamesvandenhoudt** [comment]
I've just looked into the error further and found it its due to a the Evernote web clipper plug in i have installed, thanks for the help anyway
