### ISSUE TITLE
B-card body always undifined - typescript

### ISSUE THREAD

**Issue by Schewns** [bootstrap-vue/bootstrap-vue#2013]
Hello,

I am using bootstrap vue for my project. I have been changing my implementation to be done with typescript. 

Here is how I am importing bootstrap-vue:

```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import BootstrapVue from "bootstrap-vue";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-vue/dist/bootstrap-vue.css";
import VueRx from "vue-rx";

Vue.use(VueRx);
Vue.config.productionTip = false;

Vue.use(BootstrapVue);
new Vue({
  router,
  render: h => h(App)
}).$mount("#app");
```
I then i try to use the b-card component:
```
<b-card header="Images" header-tag="header">
            <b-carousel id="carousel1" class="rounded-2" style="text-shadow: 1px 1px 2px #333;" controls indicators background="#ababab" :interval="0" img-width="500" img-height="480">
              <b-carousel-slide v-for="(photo, index) in items" :key="index" :img-src="photo"></b-carousel-slide>
            </b-carousel>
        </b-card>
```
The Header is rendered correctly but the body is always undifined no matter what, I even copy pasted one of the examples from the documentation.
here is the result:
![image](https://user-images.githubusercontent.com/17760534/44984393-d8a07500-af7c-11e8-8538-5de5dc9fe20d.png)

anyone has an idea why is this happening?

best regards,
Schewns

**Comment by tmorehouse** [comment]
Try adding the prop `no-body` to your `<b-card>`

**Comment by Schewns** [comment]
@tmorehouse i did add, same result undifined. I added no-body and also the b-body-card tag as well.

**Comment by tmorehouse** [comment]
PR #2125 should fix this.

**Comment by tmorehouse** [comment]
PR merged into dev branch.
