### ISSUE TITLE
b-modal header-class not working

### ISSUE THREAD

**Issue by kingcw** [bootstrap-vue/bootstrap-vue#2016]
Hi, i'm trying to set header-class prop for b-modal, but it's not working

```
<b-modal id="registerModal" title="Register" header-class="modalHeader" size="md">

.modalHeader {
  color: black;
  text-align: center;
  font-weight: 600;
}
```

the class name is listed in html code output though, just the class is not being loaded

`<header id="registerModal___BV_modal_header_" class="modal-header modalHeader"></header>`

**Comment by tmorehouse** [comment]
If the class is being added to your modal header, but the styles are not applied leads me to believe that your CSS is not loaded, or is loaded before the bootstrap V4 styles and is being overwritten.

**Comment by kingcw** [comment]
i manually added class in `<style></style> ` tag in index.html and it worked, sames like modal classes can not be overriden or written in components
