### ISSUE TITLE
Document why v-b-modal directive is recommended

### ISSUE THREAD

**Issue by ClemMakesApps** [bootstrap-vue/bootstrap-vue#2018]
I'm currently working on integrating bootstrap vue's modal into my application and wanted to learn more about why `v-b-modal` directive is the recommended approach. If I can get some insight here, I'd be happy to update the documentation with that information.

**Comment by tmorehouse** [comment]
One of the main reasons is that the `v-b-modal` directive automatically adds/updates the `aria-*` attributes (for accessibility) to reflect that the trigger controls a "popup/dialog"  and what state the modal is in (on the trigger element).

**Comment by ClemMakesApps** [comment]
Sorry, I'm still having trouble following. Can you show me an example?

**Comment by tmorehouse** [comment]
You can see the `aria-*` attributes that re added/controled on the trigger element that has the `v-b-modal` directive applied, when you inspect the element.

**Comment by ClemMakesApps** [comment]
That doesn't seem to be the case in the documentation website. Unless I am missing something?

![2018-09-06 10 49 00](https://user-images.githubusercontent.com/3363898/45169133-8ea8d080-b1c2-11e8-8bc1-b0d8f4f31837.gif)

**Comment by tmorehouse** [comment]
Ah, right, not aria-attributes, but it does add the appropriate `role` (button) to non button triggers (i.e. link or DIV), and also automatically returns focus to the trigger element when the modal closes.

Notice when the modal closes that the trigger button has regained focus.  When not using the v-b-modal directive, you have to specify which element to return focus to (for accessibility reasons)

**Comment by tmorehouse** [comment]
See https://bootstrap-vue.js.org/docs/components/modal/#auto-return-focus in the section https://bootstrap-vue.js.org/docs/components/modal/#returning-focus-to-the-triggering-element
