### ISSUE TITLE
Dynamic carousels

### ISSUE THREAD

**Issue by robertnicjoo** [bootstrap-vue/bootstrap-vue#2021]
I've read some issues like mine in here but i couldn't get the right answer for my issue so i'm making new one.

I have my carousels table and I'm returning all data that I need but i don't know how to add it into bootstrap-vue carousel.

# Code

`controller`

```php
public function homepage()
    {
        $carousels = Carousel::orderBy('id', 'desc')->get(['caption', 'text', 'photo']);
        return response()->json($carousels, 200);
    }
```

`component`

```html
<div v-for="(carousel,index) in carousels" v-bind:key="index">
		<b-carousel id="carousel1"
                style="text-shadow: 1px 1px 2px #333;"
                controls
                indicators
                background="#ababab"
                :interval="4000"
                img-width="1024"
                img-height="480"
                v-model="slide"
                @sliding-start="onSlideStart"
                @sliding-end="onSlideEnd"
    >

      <!-- Text slides with image -->
      <b-carousel-slide :caption="carousel.caption"
                        :text="carousel.text"
		        :alt="`${carousel.caption}`"
			:img-src="`/images/${carousel.photo}`"
      ></b-carousel-slide>
		
    </b-carousel>
</div>
```

`component script`

```javascript
export default {
		data() {
	      return {
			carousels: {},
              }
              },
mounted(){
				axios.get("/api/carousels").then(response => {
            this.carousels = response.data;
        });
		},
}
```

### PS:
I am well aware that the div I made around my `<b-carousel>` isn't the way to do it but it was the only way i could test my data are returning.

# Question

How to fix my carousel in order to work with my dynamic data `carousels: {},` ?

**Comment by tmorehouse** [comment]
Are you trying to render multiple carousels, or multiple carousel items inside a single carousel?

If the latter, your `v-for` should be moved to the `b-carousel-item` component.

**Comment by robertnicjoo** [comment]
@tmorehouse  multiple carousel items

**Comment by robertnicjoo** [comment]
@tmorehouse well I did make what you suggested and it's working nicely, is there anyway to fix the height for all images? currently it changes the height when images are not same height.

**Comment by tmorehouse** [comment]
Carousels are designed to display images that all have the same width and height (or width/height ratio).
