### ISSUE TITLE
make list update after modal hide 

### ISSUE THREAD

**Issue by thuc101** [bootstrap-vue/bootstrap-vue#2025]
I test modal for my app crud, How can make my list update after hide the modal?
my plunker as below.
https://plnkr.co/edit/mLna8Y?p=preview

          on_update() {
            let hs = JSON.parse(JSON.stringify(this.hs));
            let index = this.list.findIndex(x => x.id == hs.id);
            this.on_cancel();
            this.list[index] = hs;
          }
my view not change!!!

**Comment by ddweber** [comment]
There are some restrictions concerning vuejs when mutating array items directly as described [here](https://vuejs.org/v2/guide/list.html#Caveats). 
It is not an issue of bootstrap-vue!

As another workaround (if the ones suggested by the vue docs do not fit your needs..) you could clone the list in your update function, do some mutations and the replace the original list with the clone...

**Comment by tmorehouse** [comment]
use `this.$set(...)` to update  the value of `this.list[index]`. vue doesnt monitor object mutations within arrays or object properties.

See the Vue docs at https://vuejs.org/v2/api/#vm-set
