### ISSUE TITLE
<b-form-input> does not work with type="number"

### ISSUE THREAD

**Issue by TypicalFooBar** [bootstrap-vue/bootstrap-vue#203]
I'm trying to use the <b-form-input> to edit a number, but an exception is thrown.

This is the line of code that fails:
```
computed: {
    rowsCount: function rowsCount() {
        return (this.value || '').split('\n').length;
    }
}
```

I don't know where the code is in this code base, but when my browser hits the `rowsCount()` function, `this.value` is set to the number I want to edit, however it will fail because there is no `.split()` on a number.

**Comment by TypicalFooBar** [comment]
I believe it is here:
https://github.com/bootstrap-vue/bootstrap-vue/blob/4fdc70340ee235bc8044251acd2069131efd4038/lib/components/form-input.vue#L31

**Comment by TypicalFooBar** [comment]
So, if I set `:rows="1"` on the `<b-form-input>`, then it displays correctly without any exceptions on the page. This works, but I don't think the user of this library should have to specify any input for the `:rows` property in order to use `type="number"`.

I'm not sure of what the right fix would be here, but I hope this helps someone figure out a good change!

**Comment by mosinve** [comment]
Hm.  I don't see any errors https://jsfiddle.net/cihkem/fg69h3j2/
Can you add link to jsfiddle or codepen snippet, reproducing this issue?

**Comment by TypicalFooBar** [comment]
Hmm, indeed there aren't any errors on what you did in jsfiddle.

Let me see if I can get something together.

Thanks!

**Comment by TypicalFooBar** [comment]
Oh, so if you change your `0` on your jsfiddle to a `-1`, you will see the errors in the console that I was talking about.

**Comment by mosinve** [comment]
in data init?
Yep, got an error)
I think if we convert value to string before splitting we got rid of this err...

**Comment by mosinve** [comment]
Fixed, will be available in next release.

**Comment by TypicalFooBar** [comment]
Awesome! Hey, thanks a bunch for helping me out and working on this! :)
