### ISSUE TITLE
Transition/Animation on b-modal

### ISSUE THREAD

**Issue by RajeevRanjanOneadvanced** [bootstrap-vue/bootstrap-vue#2030]
I'm trying to create a b-modal with some animation effect using [Animate.css](https://daneden.github.io/animate.css). I'm referring this  [Custom-Transition-Classes](https://vuejs.org/v2/guide/transitions.html#Custom-Transition-Classes)

and my code is like this :
```
<transition name="modal1" enter-active-class="animated slideInLeft" leave- 
   active-class="animated slideOutLeft">
   <b-modal ref="saveModal" transition id="modal1" title="Save" 
   @ok="handleOk" @cancel="handleCancel">
   <p class="my-4">Are you sure, you want to save?.</p>
   </b-modal>
   </transition>
```

**Comment by tmorehouse** [comment]
Bootstrap-Vue uses the transitions defined by Bootstrap V4 native CSS.  It is not possible to use the Vue `<transition>` component to alter the modal's transitions.

You would need to create some CSS overrides (possibly scoped to a particular modal by a parent class).
