### ISSUE TITLE
What is the current development status?

### ISSUE THREAD

**Issue by jmohler1970** [bootstrap-vue/bootstrap-vue#2031]
Is this project still being actively developed? RC-11 seems to be quite old.

**Comment by dflock** [comment]
It seems [somewhat active](https://github.com/bootstrap-vue/bootstrap-vue/commits/dev), but no-one has done a release in ~4 months, sadly.

**Comment by TitanFighter** [comment]
[Duplication](https://github.com/bootstrap-vue/bootstrap-vue/issues/2052)

**Comment by tmorehouse** [comment]
Closing as we are tracking in #2173
