### ISSUE TITLE
Progress component does not update view immediately after value changes

### ISSUE THREAD

**Issue by lvbeck** [bootstrap-vue/bootstrap-vue#2032]
When I update the progress value property too often or too quick in a recursion or a loop, the progress bar stand still. Dom only update after the whole loop is finished. It looks like a stutter effect.

Any one has some idea?

Please check my test case for more information: [JsFiddle](http://jsfiddle.net/lvbeck/rpf6y084/) 

- Operating system and version (Windows 10)
- Browser and version (Chrome Version 69.0.3497.92 (Official Build) (64-bit))
- Version of Bootstrap-Vue (2.0.0-rc.11)

**Comment by tmorehouse** [comment]
That might be due to the CSS animation for adjusting the width.

**Comment by lvbeck** [comment]
Firefox 63 works fine.
Failed with Google Chrome and Microsoft Edge.
@tmorehouse any suggestion or hint for a quick fix?

**Comment by mosinve** [comment]
for this use case you should disable .progress-bar transition css prop;
![image](https://user-images.githubusercontent.com/20986566/45945190-e050b800-c016-11e8-97e5-af3394751d26.png)
