### ISSUE TITLE
why my navbar can not responsive?

### ISSUE THREAD

**Issue by liuyuan0071** [bootstrap-vue/bootstrap-vue#2033]
i want a responsive navbar,just like the doucument:
![image](https://user-images.githubusercontent.com/37970603/45700615-99d70580-bb9f-11e8-984e-1f1eba47edfc.png)
but now i copy that code to my project,and it doesn't work:
![image](https://user-images.githubusercontent.com/37970603/45700685-c723b380-bb9f-11e8-937c-8697436a61f3.png)
The strange thing is，when i change my browser width,it can responsive:
![image](https://user-images.githubusercontent.com/37970603/45700781-005c2380-bba0-11e8-85a3-bccba7a2d18b.png)
but when i use my mobliephone watch it,it can not responsive.
why?????
i am a chinese and my english don't so good,help!!

**Comment by lmrarturo** [comment]
That's weird, I'm using the same navbar and is working in my mobile-phone. Did you check if your mobile is not forcing to load the website in "desktop version".

**Comment by tmorehouse** [comment]
Or maybe you are missing the correct viewport meta tag settings in your rendered HTML `<head>`.

```html
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
```
