### ISSUE TITLE
applying v-bind:style on row of table  (tbody-tr)

### ISSUE THREAD

**Issue by allaghi** [bootstrap-vue/bootstrap-vue#2036]
Hi,
I want to know if there is way to apply v-bind:style with tr of table ?

**Comment by tmorehouse** [comment]
Currently there is no option to bind style objects to table rows.

**Comment by tmorehouse** [comment]
As a workaround, you can apply custom class(es) to b-table and uses custom CSS to target the table t`table > tbody > tr`
