### ISSUE TITLE
b-table allow different key for sorting on

### ISSUE THREAD

**Issue by kyleweishaupt** [bootstrap-vue/bootstrap-vue#2038]
I'm trying to find a way to use the table component with server-side sorting, but using a different key to populate the sortBy field. I'm testing in Chrome and using version 2.0.0.-rc.11 of Bootstrap-Vue. 

Here's an example of what my table looks like:
`<b-table no-local-sorting :fields="fields" :items="data" @row-clicked="view" :sort-desc.sync="sortDesc" :sort-by.sync="sort" @sort-changed="sorted">...</b-table>`

In my component using the table, I provide the fields like so: 
```
fields: [
	{
		key: 'id',
		label: 'ID',
		sortable: true,
		isRowHeader: true
	},
	{
		key: 'user.full_name',
		label: 'User',
		sortable: true,
		isRowHeader: false
	},
]
```
Which works great and I'm able to use the `@sort-changed` to call axios and get the results based on the sort parameters. My only issue is that I'm using a PHP back-end that doesn't work when I try to pass in something like `user.full_name` to sort by. To be specific, it's CakePHP that wants a pluralized version of the key to sort on, which in this example would be `users.full_name`. 

It would help me a lot to have the ability to set a `sortByKey' under my field definitions and use that for sorting instead of just `key`. Even if the `sortable` key could take a string it would help a lot. 

An example of what I mean:
```
fields: [
	{
		key: 'id',
		label: 'ID',
		sortable: true,
		isRowHeader: true,
		sortByKey: 'id'
	},
	{
		key: 'user.full_name',
		label: 'User',
		sortable: true,
		isRowHeader: true,
		sortByKey: 'Users.full_name'
	},
]
```
I couldn't find anything in the docs pertaining to this, so I apologize if there's a way to do this already. Thanks!

**Comment by tmorehouse** [comment]
You could translate the key name before sending it via axios.

**Comment by kyleweishaupt** [comment]
Translating the key name is a decent workaround. Thanks for the suggestion.
