### ISSUE TITLE
Is there any method to show and hide specific column in table component ?

### ISSUE THREAD

**Issue by allaghi** [bootstrap-vue/bootstrap-vue#2040]
Hi,
Is there way to show and hide specific column in table component ?

Thanks In Advance

**Comment by toadkicker** [comment]
You should be able to do something like this snippet:

```
<template slot="mycolumn" slot-scope="data">
  <div :class="{'show": toggleThisThing}">Hi</div>
</template>
...
data() {
  return {
    toggleThisThing: true
  }
},
methods: {
  toggler() { return this.toggleThisThing = !this.toggleThisThing }
}
```

**Comment by tmorehouse** [comment]
You can also remove the heading key from your `fields` array.

**Comment by allaghi** [comment]
@tmorehouse and @toadkicker thanks for your replying . what I want is to hide the column dynamically.
like @toadkicker  idea

**Comment by toadkicker** [comment]
I'm curious if removing the key causes a repaint...e.g. which approach renders faster

**Comment by tmorehouse** [comment]
Removing a field key would cause a repaint.  But hiding the content of a column, doesn't hide the actual table column.  The table cell `<td>` is still there, just with a hidden `<div>` inside.

**Comment by allaghi** [comment]
Any updating for this issue . ?

**Comment by allaghi** [comment]
I found the solution by adding variant to the field key and then use this code

`
showHidePhotos(){
      
      var col = document.getElementsByClassName('table-danger');
      var index;
      for (let index = 0; index < col.length; index++) {
        if(col[index].style.display ==="none"){
          col[index].style.display = "block"; 
        }else{
          col[index].style.display = "none"; 
        }
      }
      
    },
`
