### ISSUE TITLE
Nested checkboxes

### ISSUE THREAD

**Issue by Miko8484** [bootstrap-vue/bootstrap-vue#2041]
I want to have sidebar that would represent filter and in there I would have checkboxes that would represent what should be shown to user. I found this: https://bootstrap-vue.js.org/docs/components/form-checkbox/#indeterminate-tri-state-support

But this only goes one level deep and I would need to go two levels. An example of what I am trying to achieve:

- All

   - Breakfest
 
         -Eggs
         -Bacon
         -Sandwich
     

  - Lunch
 
         -Salad
         -Chicken
         -Fish
    
 
  - Dinner

         -Pancakes
         -Tacos
         -Beef

Now I want something like example in documentation from link but that goes one level deeper.

**Comment by tmorehouse** [comment]
Basically, you would need to create three batches of tri-state groupings (tri-state +3 choices each), and then create another tri-state checkbox at the top that changes it's state based on the number of choices selected in each of the three groupings.

**Comment by Miko8484** [comment]
> 
> 
> Basically, you would need to create three batches of tri-state groupings (tri-state +3 choices each), and then create another tri-state checkbox at the top that changes it's state based on the number of choices selected in each of the three groupings.

Yeah that one that should be on top of those 3 in the middle is giving me a problem
