### ISSUE TITLE
b-carousel-slide img-src is not working with Nuxt

### ISSUE THREAD

**Issue by lmrarturo** [bootstrap-vue/bootstrap-vue#2042]
When reporting a bug, include:

- Operating system and version **Ubuntu 16.04**
- Browser and version **Chrome**
- Version of Bootstrap-Vue that you are using **2.0.0-rc.11**

Hello to everybody, 

I'm trying to use b-carousel with local images but is not working because nuxt doesn't "know" the "img-src" attribute and doesn't compile it correctly.

` <b-carousel id="carousel1"
                style="text-shadow: 1px 1px 2px #333;"
                controls
                indicators
                background="#ababab"
                :interval="4000"
                img-width="1024"
                img-height="480"
                v-model="slide"
                @sliding-start="onSlideStart"
                @sliding-end="onSlideEnd"
    >
     <b-carousel-slide img-src="../img/home/inside.jpg">
     </b-carousel-slide>
     <b-carousel-slide img-src="https://picsum.photos/1024/480/?image=58">
     </b-carousel-slide>
    </b-carousel>`
![image](https://user-images.githubusercontent.com/4065361/45897227-29490800-bd9c-11e8-9b9b-edd36d8e0076.png)

When Nuxt process a local image it look like this: http://localhost:3000/_nuxt/img/background-booking.6ef9c10.jpg

That is the problem with the attribute "img-src". The website is looking the nuxt path and not the local origin path, but nuxt didn't create it, so it returns a 404.

I hope to be clear with the problem. Thank you!

**Comment by tmorehouse** [comment]
See the following updated docs on image asset URL handling:

https://github.com/bootstrap-vue/bootstrap-vue/tree/dev/docs/markdown/reference/images
