### ISSUE TITLE
Docs - Inline form example probably has a typo

### ISSUE THREAD

**Issue by jonasjancarik** [bootstrap-vue/bootstrap-vue#2043]
In the first example under https://bootstrap-vue.js.org/docs/components/form/#inline-form, the `<b-input-group left="@" class="mb-2 mr-sm-2 mb-sm-0">` part doesn't seem right. I suppose this was supposed to provide an example of the "prepend" attribute - I don't think "left" is a valid attribute.

Suggested change:

`<b-input-group prepend="@" class="mb-2 mr-sm-2 mb-sm-0">`

**Comment by tmorehouse** [comment]
Fixed with #2017
