### ISSUE TITLE
Popover width

### ISSUE THREAD

**Issue by vpratfr** [bootstrap-vue/bootstrap-vue#2051]
How can we adjust the popover width?

I have a table in there which would rougthly require double width. Is there any way to strech the popover width to the content?

Tried to put a min-width inline style on the table element, but that does not behave as expected.

Putting that style on the popover itself has no effect. 

Any idea?

Kindly note that this is all happening within a modal, hence I would love to avoid modal inside modal if possible. This is why I picked the popover component.

**Comment by michaelzangl** [comment]
You can set the container to an element inside your modal with a fixed id.

Then you can put a style in your CSS for all popovers that are a child of that container.

**Comment by bakhti-uzb** [comment]
> You can set the container to an element inside your modal with a fixed id.
> 
> Then you can put a style in your CSS for all popovers that are a child of that container.

That didn't work for me. Here is my code 
```
<div id="myContainer">
	<b-popover
		:key="data.item.id + 'popover'"
	        :target="'popOverDelete'+data.item.id"
		placement="auto"
		container="myContainer"
		:ref="'popover'+data.item.id"
		class="refDeleteConfirm"
       >
	<template slot="title">
		<b-button @click="onClose(data.item.id)" class="close"
					 aria-label="Close"
				         style="margin-left: 5px">
		      <span class="d-inline-block" aria-hidden="true">&times;</span>
		</b-button>
		Вы уверены?
		</template>
		<div>
		   <div class="row mt-1">
			<div class="col-6">
		        <b-button variant="outline-danger" size="sm" block		 
                                        @click="onClose(data.item.id)">
                                    Нет
			</b-button>
		       </div>
		       <div class="col-6">
			<b-button variant="outline-success" size="sm" block																 
                                        @click="onOk(data.item.id)">Да
			</b-button>
		       </div>
	            </div>
                </div>
        </b-popover>
</div>
```
Style : 
```
#myContainer {
	.popover {
		width: 200px !important;
	}
}
```

**Comment by Symbolk** [comment]
As said in the [doc], "The maximum width of the popover is hard coded by Bootstrap v4 CSS to 276px."

[doc]: https://bootstrap-vue.js.org/docs/components/popover/

**Comment by tourbase** [comment]
It is possible. Just add `custom-class="wide-popover"` to `<b-popover>` and `.wide-popover { max-width: 400px; }` to `<style>`
