### ISSUE TITLE
Any scheduling for final release?

### ISSUE THREAD

**Issue by cyberiaa** [bootstrap-vue/bootstrap-vue#2052]
Hi,
It's a couple of months since bootstrap vue released as 2.0.rc11. Is there any scheduling for v2 final release?

**Comment by tmorehouse** [comment]
We've got quite a few fixes to push, and a few minor breaking changes (although hopefully backwards compatible in most cases via pop deprecation)

**Comment by tmorehouse** [comment]
Closing as we are tracking in #2173
