### ISSUE TITLE
How to refresh/reset a modal so that next time it is opened it is like I reset the page?

### ISSUE THREAD

**Issue by allw1994** [bootstrap-vue/bootstrap-vue#2053]
Having issues with a modal at the moment because it does not reset when hidden, could this be made as an optional feature on a modal? i.e. if enabled the any forms or other data stores are forced to be refreshed.

Any ideas on how to fix right now?

Thanks

**Comment by tmorehouse** [comment]
Form values are based on your underlying data model tied to the form elements.

Tap into the modal's `hidden` event, and reset your form elements once the modal is hidden, or optionally use the `lazy` modal option, which forces the modal content (i.e. your form) to be re-rendered from scratch when opened.  Note this section option will work only if your form data model re-initializes when opened.
