### ISSUE TITLE
b-form-radio-group - Not checking default value

### ISSUE THREAD

**Issue by arxpw** [bootstrap-vue/bootstrap-vue#2054]
Hello,

Running Bootstrap-Vue 2.0.0-rc.10
Windows 10
Chrome 69 ( Latest )

It seems that my default selected checkbox is not appearing as checked unless I update the data property afterwards. ( 'next-day' )

( Using PUG with Vue )
```pug
b-form-radio-group(
  v-model="booking_methods.selected",
  :options="booking_methods.options",
  name="bookingMethods",
 )
```

```js
export default {
  name: 'bookingscreate',
  data() {
    return {
      booking_methods: {
          selected: 'next-day',
          options: [
            { 
              text: 'Next Day', 
              value: 'next-day' 
            },
            { 
              text: 'Next Day ( Before Noon )', 
              value: 'next-day-before-noon' 
            },
            { 
              text: 'Next Day ( Before 10:30 AM )', 
              value: 'next-day-before-10' 
            },
            { 
              text: 'Next Day ( Before 9:00 AM )', 
              value: 'next-day-before-9' 
            },
            { 
              text: 'Next Day ( Before 7:00 AM )', 
              value: 'next-day-before-7' 
            },
            { 
              disabled: true, 
              text: 'International Delivery', 
              value: 'international' 
            },
            { 
              text: 'Sameday Delivery', 
              value: 'same-day' 
            }
          ]
      }
    }
  }
}
```

**Comment by tmorehouse** [comment]
This may have to do with how Vue handles reactivity, specifically with objects (and only looking at changes at the top level keys).

You may want create a computed property (with getter/setter) and use that as your v-model.  The getter would reference your `this.booking_methods.selected`, and the setter would use this.$set('booking_methods.selected', value to update the value).  Or, just move your `selected` to the top level of your data (getting rid of the dotted notation).

**Comment by celorodovalho** [comment]
I love BootstrapVue, but that is the worse issue that I've faced and the maintainers don't give a solution for the other similar issues [#2609, #1266, #1566].

It's a problem with Bootstrap 4? Yes, it is.
But the implementation should give a solution or at least explain this stuff in documentation.
The "invalid-feedback" is not in documentation also and doesn't seem to be a good alternative.

**Comment by huypxgear** [comment]
I have the same issue. Does anyone know how to fix it?

**Comment by SjorsVanGelderen** [comment]
The dotted notation doesn't seem to matter here. Computed property solution also does not seem to make a difference. I think it's a bug in Bootstrap-Vue, not in Bootstrap 4. A solution would be very welcome.

**Comment by raublekick** [comment]
I ran into this issue and discovered that it would work as expected when the b-form-radio-group is wrapped in a b-form. The docs don't seem to include this in the examples, but it did make everything work for me.
