### ISSUE TITLE
Make it possible to open a b-nav-item-dropdown programmatically

### ISSUE THREAD

**Issue by roelVerdonschot** [bootstrap-vue/bootstrap-vue#2058]
I have tried to open the nav dropdown programmatically but i'm unable to do this via refs 

i have tried:

`
<b-nav-item-dropdown right ref="navdropdown">
</b-nav-item>
`

`
this.$refs.navdropdown.show()
`
`
this.$refs.navdropdown.toggle()
`
`
this.$refs.navdropdown.visible = true
`
`
this.$refs.navdropdown.showMenu()
`

but non seem to work

**Comment by toadkicker** [comment]
You need to use `$emit` like so:

```
this.$refs.navdropdown.$emit('show)
this.$refs.navdropdown.$emit('toggle')
```

**Comment by roelVerdonschot** [comment]
It doesn't seem to work.

When I click on the `b-nav-item-dropdown` the following events are emitted
`
toggle by <bNavItemDropdown>
`
`
show by <bNavItemDropdown>
`
`
bv::dropdown::show by <App>
`
`
bv::dropdown::shown by <App>
`
`
shown by <bNavItemDropdown>
`

When I trigger `this.$refs.navdropdown.$emit('show')` I only see `show by <bNavItemDropdown>`

**Comment by jackmu95** [comment]
Here is a working example:
```vue
<template>
  <b-nav>
    <b-nav-item>Item 1</b-nav-item>
    <b-nav-item>Item 2</b-nav-item>
    <b-nav-item-dropdown
      ref="dropdown"
      text="Item 3"
    >
      <b-dropdown-item>Subitem 1</b-dropdown-item>
      <b-dropdown-item>Subitem 2</b-dropdown-item>
      <b-dropdown-item>Subitem 3</b-dropdown-item>
    </b-nav-item-dropdown>
  </b-nav>
</template>

<script>
export default {
  mounted() {
    setTimeout(() => {
      this.$refs.dropdown.show();
    }, 2000);
  }
};
</script>
```
