### ISSUE TITLE
Clicking on a b-form-group legend focuses first input element

### ISSUE THREAD

**Issue by satkunas** [bootstrap-vue/bootstrap-vue#2063]
When using a b-form-group element with a label, clicking on the label/legend causes the first element in the group body to be focused. This implicit behavior is not desired in some cases and it should either be disabled or an explicit property should be added to either disable or enable this behavior.

Fiddle demonstration: https://jsfiddle.net/satkunas/ezu3r9gx/8/

RHEL 64-bit (3.10.0-862.9.1.el7.x86_64), 
Chromium Version 69.0.3497.100 (Official Build) (64-bit),
bootstrap 4.1.3
bootstrap-vue 2.0.0-rc.11

**Comment by satkunas** [comment]
@tmorehouse how can one inhibit this click behavior?

**Comment by tmorehouse** [comment]
Currently we don't have an option to disable this feature, but it could be something we could look into adding

**Comment by tmorehouse** [comment]
Possibly, we could add in some logic that checks for multiple inputs inside the b-form-group, and if multiple, focus the container containing the inputs (which would have a `tab-index="0"` set on it), otherwise it would focus the sole input found (mimicking the action of a label)

**Comment by jackmu95** [comment]
#2258 has resolved this issue.
