### ISSUE TITLE
[Tabs] b-checkbox not working in template slot="title"

### ISSUE THREAD

**Issue by PriyaTurangi** [bootstrap-vue/bootstrap-vue#2065]
![code](https://user-images.githubusercontent.com/41181380/46672943-513ac700-cbf6-11e8-9690-1ab1dcd7f9cf.PNG)

  <b-tabs>
 <b-tab active>
 
   <template slot="title">
<b-checkbox></b-checkbox>
   </template>
    </b-tab>
</b-tabs>

**Comment by tmorehouse** [comment]
One also has to realize that the tab button is a link (with role="button".  Placing form controls in a link/buttons is not supported in HTML/HTML5.

tabs are mean for controlling which tab pane is visible, and really shouldn't have form controls embeded in them,

You should switch to using a navbar or other custom markup to do this.
