### ISSUE TITLE
b-form-input with keyUp event keep firing every few seconds

### ISSUE THREAD

**Issue by kingofhills** [bootstrap-vue/bootstrap-vue#2069]
When reporting a bug, include:

- Operating system Mac OS X
- Browser and version (Chrome 69.0.3497.100 (Official Build) (64-bit))
- Version of Bootstrap-Vue 2.0.0-rc.11

create a v-form-input tag with keyup like
 < . b- form-input type="text"  placeholder="Reference" v-model="form.reference" :keyup="registerChange()">< / . b-form-input> 
registerChange function keep hitting every few seconds...

**Comment by vuphuctho** [comment]
Should it be `@keyup` instead of `:keyup`?

**Comment by tmorehouse** [comment]
Use `@keyup.native="registreChange"`

Note there are no brackets on the event callback (you want to provide a reference to the callback, not the result of calling the callback).
