### ISSUE TITLE
b-form-input: please add pattern, title Properties to docs

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#2071]
b-form-input: please add pattern, title to docs Component Reference > Properties
https://bootstrap-vue.js.org/docs/components/form-input

These work fine if used, but aren't documented.

Thanks

**Comment by tmorehouse** [comment]
Any prop that is not part of the component will be applied to the component's input (as it is the root element of the component)

**Comment by mariusa** [comment]
Ok, that makes sense. That means only properties with special handling are documented? What's special about autocomplete or placeholder props?

**Comment by tmorehouse** [comment]
They are in there for legacy support, and probably could be removed.
