### ISSUE TITLE
Customizing table refresh() function

### ISSUE THREAD

**Issue by SanjayBanjade** [bootstrap-vue/bootstrap-vue#2074]
There's a bootstrap vue table in my project where user can add stuff. After the user adds something, I call `refresh()`. My API structure is like this: `https://example.com/users?from=1&to=10`! So, when `refresh()` is called after adding the data, it just fetches the same URL.

Instead, I want to add 1 to the `to` query params so that the URL will be like `https://example.com/users?from=1&to=11`! How can I do this?

**Comment by tmorehouse** [comment]
You might be able to alter this in your provider function, as it receives a copy of the `context` object (which include pagination information, of which you can alter as you pass it to your function, or use a set of data entries to control the start/end values).

**Comment by SanjayBanjade** [comment]
How do you pass a set of data entries? Would you please show me an example?

**Comment by tmorehouse** [comment]
Could you provide some sample code of how you are fetching and updating the table data?

**Comment by tmorehouse** [comment]
Closing as stale
