### ISSUE TITLE
b-tab's title slot doesn't update correctly.

### ISSUE THREAD

**Issue by dumptyd** [bootstrap-vue/bootstrap-vue#2077]
Here's the fiddle demonstrating the issue.
https://jsfiddle.net/dumptyd/v9h0y21g/1/

Not sure if this is a bootstrap-vue issue or a vue one.

**Comment by tmorehouse** [comment]
It's a combination of both, and having to copy over the title slot from the b-tab child component I to the parent b-tabs component. It's not overly reactive. We need to come up with a better solution.
