### ISSUE TITLE
Typeahead component missing

### ISSUE THREAD

**Issue by nerdoc** [bootstrap-vue/bootstrap-vue#2078]
Hi, appreciate your really great work here. 

I just asked myself why there is no **typeahead** component like the one in [Vue/Bootstrap3](https://uiv.wxsm.space/typeahead/) - I spotted a few "autocomplete" props in e.g. b-form-input - but this is completely undocumentated, and a [search in the code](https://github.com/bootstrap-vue/bootstrap-vue/search?q=autocomplete&unscoped_q=autocomplete) showed that that prop is not used at all - so is there a chance to support a typeahead/autocomplete feature in BootstrapVue?
The "autocomplete" prop was [added](https://github.com/bootstrap-vue/bootstrap-vue/commit/d6867878a0130e4ce24d505a0b9820a328f918db) to BootstrapVue, but does not seem to have any effect...

I can't be the only one in need of this ;-)

**Comment by tmorehouse** [comment]
The `autocomplete` prop is passed directly to the input as an attribute (standard HTML attribute), and is used to control how the browser handles autocomplete (i.e. filling in saved form values, and is not a "typeahead" feature.

Standard Bootstrap V4 (and V3) doesn't include a "typeahead" plugin, although TWBS does have a separate typeahead plugin (not part of the core Bootstrap V4).

**Comment by nerdoc** [comment]
ok, understood...
