### ISSUE TITLE
b-modal custom transitions

### ISSUE THREAD

**Issue by mijuskovic** [bootstrap-vue/bootstrap-vue#2079]
It would be very nice, that it is possible to specify and to use custom transition animations (animate.css e.g)  for bootstrap modal component. For example:

```vue
<b-modal entrance-transition="animated fadeIn"  leave-transition="animated bounceOut" ref="myModal" 
centered hide-footer>
    <div class="d-block text-center">
        <h3>Hello From My Modal!</h3>
    </div>
    <b-btn class="mt-3" variant="outline-danger" block @click="hideModal">Close Me</b-btn>
</b-modal>
```

**Comment by tmorehouse** [comment]
Bootstrap-Vue uses the standard Bootstrap V4 CSS, of which you can customize their CSS using Sass, or you can override their styles in  regular CSS file (and perhaps target specific modals using a class placed on the `b-modal` component).

**Comment by mijuskovic** [comment]
@tmorehouse Yeah, that is one of possible solutions, but I think it would be much more easier and elegant to specify already written animation classes as props instead of overriding bootstrap styles.

**Comment by tmorehouse** [comment]
We implement the modal using the classes defined by Bootstrap's CSS, which doesn't normally work well with the built in Vue component `<transition >` .

There are actually ttwo sets of transitions that happen, the one for the backdrop, and one for the modal itself.

**Comment by tmorehouse** [comment]
There are multiple theme packs (CSS) out there that can customize many of the bootstrap component look and feel.  Perhaps some of them might have transitions close to what you are looking for?

**Comment by jackmu95** [comment]
@tmorehouse I think we can close this as it's answered and not really related to BootstrapVue.
