### ISSUE TITLE
[Modal] Modal closes on return false

### ISSUE THREAD

**Issue by kyle-mccarthy** [bootstrap-vue/bootstrap-vue#208]
When attaching a listener to `@ok` the modal closes even if the method returns false.

This can reproduced in the [documentation example](https://bootstrap-vue.github.io/docs/components/modal/). 

To reproduce, open modal, click "Ok" without typing anything, an alert will be show, dismiss the alert, the modal will close.

**Comment by pi0** [comment]
@kyle-mccarthy Thanks for report. I think this problem is related to a global dismiss handler for overlay. Will work on it :)
