### ISSUE TITLE
Table flickers on refresh.

### ISSUE THREAD

**Issue by hifall** [bootstrap-vue/bootstrap-vue#2080]
I have a b-table, inside each of whose rows there is a button, which when clicked, removes that row, then refreshes the table. All is fine, except that when the table is refreshed, there is a noticeable 'flicker' due to the fact that the table is first emptied, then populated with incoming rows.

I've seen other plugins which implement sort of "non-disruptive" updating on tables. Here is one way to do non-disruptive updating:
1 call the server to return the rows;
2 compare incoming rows with existing in the table, add the new ones, and remove the deleted ones;
This way, the table updates really smoothly, without any flicker whatsoever.

Just some thoughts. Not sure if this matters to you or how involved it would be for such an implementation.

- Operating system and version macOS 10.11
- Browser and version Chrome 69
- Version of Bootstrap-Vue v2.0.0-rc.11

**Comment by tmorehouse** [comment]
Right now, I think b-table, when calling a the provider function sets its internal items array to an empty array, while it is awaiting reply from the server.

We might be able to optimize this my not clearing that local items array until the new data is received.  That way Vue could efficiently re-use any of previously rendered rows.

**Comment by tmorehouse** [comment]
@hifall the latest `dev` branch has some improvements to `b-table`.  Could you see if you have better results using it?

**Comment by hifall** [comment]
Thanks @tmorehouse -- I suppose these improvements are supposed to fix the flicker? Just would like to know what to expect when testing.

**Comment by tmorehouse** [comment]
The main improvement is the reduction of running filtering, sorting and pagination each time a prop changes.  Each of the steps is only run (via computed property) when needed., so itr should reduce the render time (depending on the circumstances).

The improvements weren't targeting this issue directly, but a few other issues, and this one may be related.

**Comment by slidenerd** [comment]
I believe ^2.0.0-rc.11 is the dev branch version you are talking about, I am calling refresh every second and the table still flickers, is there some key from the array of items that I can mark as the primary key for that row to avoid the flickering

**Comment by tmorehouse** [comment]
2.0.0-rc.11 is the latest npm release. `dev` is the latest non npm release.

**Comment by digitalmouse** [comment]
Greetings!   

Has this received any more attention?  

I've got a project with a large dataset of around 1000 records, broken up with pagination in sets of 15 to fit on the given screen real-estate.

Whenever I call a microservice to update the array containing the data for the table, the table doesn't really 'flicker' so much as momentarily 'grey-out' during the updating of the array, then returns to normal.  It's a very fast change, so I would consider this a kind of flicker.

I was wondering if there might be some underlying CSS change to the table during the prop/object/array updates?  And if so, could we override it to get rid of this 'flicker'.

Personally, I think it's a useful metric telling me when there is a microservice/database update happening, but my customers have pointed out that it gets annoying when it starts happening 15-20 times a minute.  😄
