### ISSUE TITLE
<b-form-file> not styling on any browser.

### ISSUE THREAD

**Issue by edxxgardo** [bootstrap-vue/bootstrap-vue#2082]
Hello guys,
I just installed Bootstrap-Vue step by step according to the procedure, fresh installation:
https://bootstrap-vue.js.org/docs

Ensure vue-cli is installed and up to date
npm i -g vue-cli
Initialize a bootstrap project in the directory 'my-project'
vue init bootstrap-vue/webpack-simple my-project
Change into the directory
cd my-project
Install dependencies
npm i
Fire up the dev server with HMR
npm run dev

Then I removed the <template> from the example code in App.vue and copied the  <b-form-file> example given in the official page but It is not styling the form for file upload. Please, check screenshots in the attachment. I didn't try all the components offered, but the styling works in general

Also, see the three dots message in the main.js file.

OSX 10.13.16
vue: 3.0.4
nom: 6.4.1

<img width="388" alt="screen shot 2018-10-17 at 21 24 02" src="https://user-images.githubusercontent.com/8612773/47111367-a5c3ef00-d253-11e8-8758-dbe6e326ee9e.png">
<img width="779" alt="screen shot 2018-10-17 at 21 24 24" src="https://user-images.githubusercontent.com/8612773/47111368-a5c3ef00-d253-11e8-9db8-bc247cf5b025.png">

**Comment by tmorehouse** [comment]
Closing as stale.
