### ISSUE TITLE
Automatic template converter Bootstrap 4 to Bootstrap-vue

### ISSUE THREAD

**Issue by maverickpravin** [bootstrap-vue/bootstrap-vue#2083]
i have been using bootstrap-vue in my 2 most important projects. The problem i am facing is migration. Sometimes i am forced to use bootstrap 4 html5 templates in my nuxt but i prefer bootstrapvue
Is there any tool for converting template from bootstrap4 to bootstrap-vue?

**Comment by tmorehouse** [comment]
I don't know of any tools that would support that, as it would be difficult to convert every layout style and component into the required Bootstrap-Vue markup.

**Comment by vesper8** [comment]
sounds like it wouldn't be that difficult to get it 90% right, would be a big time saver.. someone just has to tackle it
