### ISSUE TITLE
[feature request] [table] parameter to allow for fixed table header

### ISSUE THREAD

**Issue by addijhaq** [bootstrap-vue/bootstrap-vue#2085]
As it currently stands (https://github.com/bootstrap-vue/bootstrap-vue/issues/555) is the only viable option for creating a fixed header....

this creates responsiveness issues and doesn't provide a clean solution.

bootstrap, itself, supports this out of the box, yet vue-bootstrap only provides the difficult css workaround.

**Comment by tmorehouse** [comment]
The standard CSS `table-layout: fixed` behavour is defined by the browser in use.  Most use the first row to determine the widths of the columns, making for a faster render (and preventing multiple page re-flows as each `tr` is processed).

I don't see any mention of fixed tables within the official [Bootstrap V4.1 Table documentation](http://getbootstrap.com/docs/4.1/content/tables/), so I am unsure of what you mean by it supports it out of the box.

**Comment by tmorehouse** [comment]
Maybe you could suggest some markup that produces the result you want?
