### ISSUE TITLE
[Question] How to render a list data with pagination

### ISSUE THREAD

**Issue by Maxalos** [bootstrap-vue/bootstrap-vue#2086]
I cant understand how to use the pagination. Can someone make an example?

**Comment by Diaskhan** [comment]
For what component do u need pagination ?

**Comment by aorinevo** [comment]
Hi @Maxalos, there's several examples here: https://bootstrap-vue.js.org/docs/components/pagination/

**Comment by Diaskhan** [comment]
There no feedback! I guesse best is to close issue !

**Comment by tmorehouse** [comment]
closing due to lack of information
