### ISSUE TITLE
Install dev branch

### ISSUE THREAD

**Issue by Joebayld** [bootstrap-vue/bootstrap-vue#2094]
Are there any instructions on how to install the dev branch with NPM? 

I tried: `npm install bootstrap-vue/bootstrap-vue#dev`

but the dist folder is missing and I can't build my app.

**Comment by tmorehouse** [comment]
Only the master is available on npm.

You would need to use `git` to pull the `dev` branch onto your computer.

```sh
cd /some/directory
git clone https://github.com/bootstrap-vue/bootstrap-vue.git --branch dev
```

Or you can download the repo from github in ZIP format:

![image](https://user-images.githubusercontent.com/2781561/47441747-32f0d180-d787-11e8-8e38-c7c5ec2ade56.png)

**Comment by aorinevo** [comment]
@Joebayld if you need to use the dev branch in your app, you can publish and install a namespaced version of it.  

Here are the steps on how to do that:
  - Fork and clone the project from your Github account (i.e. `git clone https://github.com/aorinevo/bootstrap-vue.git --branch dev`).
  - In `package.json`:
      - Remove `vue-beta` and `vue-latest` from devDependencies.
      - Set `name` to `{{namespace}}/bootstrap-vue` (i.e. `@aorinevo/bootstrap-vue` in my case)
      - Set `respository.url` to the forked url (i.e. `git+https://github.com/aorinevo/bootstrap-vue.git`)
  - Install `babel-preset-env`: `npm install --save-dev babel-preset-env`.
  - In `scripts/build`, change `cd dist` to `cd dist/{{namespace}}`.
  - Run `npm install`.
  - Run `npm run build`.
  - Publish the project to npm (see https://docs.npmjs.com/getting-started/publishing-npm-packages): `npm publish --access=public`.
  - Within a few minutes, the package should be available to install using `npm install {{namespace}}/boostrap-vue`

<img width="242" alt="screen shot 2018-11-02 at 3 37 02 pm" src="https://user-images.githubusercontent.com/3240137/47936786-2e2dcb00-deb5-11e8-8404-a2530d714ed3.png">

**Comment by qkdreyer** [comment]
I've published an up to date release here : https://www.npmjs.com/package/@triotech/bootstrap-vue
