### ISSUE TITLE
It looks like no documentation is available for form-input type='date' and datepicker

### ISSUE THREAD

**Issue by fessacchiotto** [bootstrap-vue/bootstrap-vue#2095]
Hi! I've searched the list of issues here, and the web (google, etc.), but I've not been able to find any details about the form-input datepicker: 

- how to set the format of the user input? 
- is it possible to have a placeholder according to the input format? 
- how to select a non-english language? 

Any source of truth about this? BTW, is the datepicker source code available? If yes, where? 

Thank you!

**Comment by tmorehouse** [comment]
The input is not a datepicker, it renders a native browser `date`, `datetime`, `time`, etc, input.

It uses the browser built in date/time pickers (which will vary from browser to browser, if supported).

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by fessacchiotto** [comment]
Thank you. This was not clear enough to me.

**Comment by tmorehouse** [comment]
If a native browser date input is supported, it always returns in yyy-mm-dd format (not a native date object).  If a native date input is not supported, then a regular text input is used as fallback (by the browser), then the return value is whatever the user types in.
