### ISSUE TITLE
Is there any Left/Right panel that can be shown and hidden?

### ISSUE THREAD

**Issue by BenHayat** [bootstrap-vue/bootstrap-vue#2099]
I'd like to use Left/Right panels (very commonly used in Mobile) to show/hide menu bar or info depending on the screen size. Is there such a component there? 

Along the same note do we have header/footer area that we keep pinned that will not scroll?

Something like this.
https://quasar-framework.org/quasar-play/apple/index.html#/showcase/layout-demo/play-with-layout

**Comment by tmorehouse** [comment]
Bootstrap-Vue is a Vue implementation of the standard Bootstrap-V4 components, and does not include any other components that are not part of the standard Bootstrap V4.

**Comment by BenHayat** [comment]
> 
> 
> Bootstrap-Vue is a Vue implementation of the standard Bootstrap-V4 components, and does not include any other components that are not part of the standard Bootstrap V4.

@tmorehouse 
Ah I see. I thought they use BS as their UI foundation and then build components on the top of that based on BS system.
