### ISSUE TITLE
Error while building the project

### ISSUE THREAD

**Issue by valexiev** [bootstrap-vue/bootstrap-vue#210]
When i try to build the project with `npm run build`, i get an error:
> ENOENT: no such file or directory, open '/Users/jckmlkshng/playground/bootstrap-vue/dist/bootstrap-vue.css'

How to build it?

**Comment by pi0** [comment]
@valexiev Please ensure `dist` directory exists in root of project and create one if not exists

**Comment by valexiev** [comment]
Thanks!
It would be nice if it is written in the docs : )

**Comment by pi0** [comment]
Yes I'll

**Comment by SirLamer** [comment]
Probably 'build' should create the folder when it does not exist.

**Comment by pi0** [comment]
@SirLamer Yes, the problem is rollup was doing this with programming usage but it is not doing this with default commands and we need to create that manually...

**Comment by Mark-L6n** [comment]
I added a `dist` subdirectory, but now get another error:
`npm WARN enoent ENOENT: no such file or directory, open 'path/to/first-test-app/package.json'`
Additionally, there is:

```
npm WARN first-test-app No description
npm WARN first-test-app No repository field.
npm WARN first-test-app No README data
npm WARN first-test-app No license field.
```
Creating `package.json` just results in:

```
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
```
