### ISSUE TITLE
support vue-cli3 

### ISSUE THREAD

**Issue by jn66** [bootstrap-vue/bootstrap-vue#2101]
how to use vue-cli3 to import BootstrapVue

**Comment by chrishamm** [comment]
easy. install vue-cli3 first

1. vue create <your project>
2. cd <your project>
3. npm install bootstrap-vue
4. add the new imports as described here https://bootstrap-vue.js.org/docs in the webpack section
5. npm run build -or- npm run serve

**Comment by tmorehouse** [comment]
duplicate #2096
