### ISSUE TITLE
B -form-input tags input Chinese characters will bring out pinyin

### ISSUE THREAD

**Issue by zhang-hongzheng** [bootstrap-vue/bootstrap-vue#2104]
Under the apple reader, the input box of the b-form-input tag will automatically bring out a large number of pinyin

**Comment by tmorehouse** [comment]
Could you provide any additional information?  Possibly a screen shot of what you are experiencing?

**Comment by tmorehouse** [comment]
Hmmm I am not sure what might cause that issue.  It could be Safari issues (when in reader mode), or possibly locale settings on the web page or markup?

**Comment by zhang-hongzheng** [comment]
This seems to be because apple iphone's Chinese input method has been testing me, other Chinese input methods have no problem。

**Comment by zhang-hongzheng** [comment]
I think it is because apple's native Chinese input method does not trigger some javascript events, and I just don't know how to solve it, which makes me very annoyed

**Comment by tmorehouse** [comment]
I wonder if this is related to https://github.com/vuejs/vue/issues/8723 and https://github.com/vuejs/vue/issues/8231

**Comment by tmorehouse** [comment]
PR #2100 merged into dev branch.

**Comment by xcchcaptain** [comment]
I got this problem in WebKit with  ios-11.2.6  .
i  have not found the  _composing_ property on input event object
but the native input doesn't have this problem.

**Comment by tmorehouse** [comment]
Actually the 'composing' property on the input/change event is injected by Vue.

There are a few more changes coming to `b-form-input` in the coming weeks.

**Comment by xcchcaptain** [comment]
As what you prompt ,I tried  to give it a flag .  
don't expect to affect the 'composing' property injected by vue.  
add listeners for events _compositionstart_ and _compositionend,add  **bcomposing** to the event target. 
these just worked for me.

`var bFormInput = {
    mixins: [idMixin, formMixin, formSizeMixin, formStateMixin],
    render: function render(h) {
      return h('input', {
        ref: 'input',
        class: this.inputClass,
        attrs: {
          id: this.safeId(),
          name: this.name,
          type: this.localType,
          disabled: this.disabled,
          required: this.required,
          readonly: this.readonly || this.plaintext,
          placeholder: this.placeholder,
          autocomplete: this.autocomplete || null,
          'aria-required': this.required ? 'true' : null,
          'aria-invalid': this.computedAriaInvalid,
          value: this.value
        },
        on: {
          compositionstart:this.onCompositionStart,
          compositionend:this.onCompositionEnd,
          input: this.onInput,
          change: this.onChange
        }
      });
    },
......  
    methods: {
      format: function format(value, e) {
        if (this.formatter) {
          return this.formatter(value, e);
        }
        return value;
      },
      setValue: function setValue(value) {
        this.$emit('input', value);
        // When formatter removes last typed character, value of text input should update to formatted value
        this.$refs.input.value = value;
      },
      onCompositionStart:function(evt){
    	 evt.target.bcomposing=true;
      },
      onCompositionEnd:function(evt){
    	 evt.target.bcomposing=false;
    	 this.onInput(evt);
      },
      onInput: function onInput(evt) {
    	if(evt.target.bcomposing) return;
        var value = evt.target.value;

        if (this.lazyFormatter) {
          this.setValue(value);
        } else {
          var fValue = this.format(value, evt);
          this.setValue(fValue);
        }
      },
      onChange: function onChange(evt) {
    	if(evt.target.bcomposing) return;
        var fValue = this.format(evt.target.value, evt);
        this.setValue(fValue);
        this.$emit('change', fValue);
      },
      focus: function focus() {
        if (!this.disabled) {
          this.$el.focus();
        }
      }
    }
  };`
