### ISSUE TITLE
<b-table>: can you target the `tbody` element to apply an event handler?

### ISSUE THREAD

**Issue by addijhaq** [bootstrap-vue/bootstrap-vue#2105]
As it is, i can create a `slot` and `slot-scope` it to the `row` or `cell` and then add an event listener to an object inserted into that `cell` or `row` (most obviously is `@click` event on a `button` inside of a table `cell`) but how can i scope a `slot` to the `<tbody>` or target the `<tbody>` and add an event to it? 

in my application i'd want to add an `@scroll` event to the `<tbody>`... adding @scroll the the `<b-table>` doesn't work. trying to scope a slot to the `<tbody>` doesn't work since `'body`' is not an accepted argument for `<b-table>`  ``scoped-slot`` argument. (`row`, `cell`, `data` are however)

if this is not possible can i propose a change to scoped slots to allow for scoping to `'body'` or `'tbody'`? 

kind of interesting i can add events to `row` or to `cell` but not to the table itself.

**Comment by tmorehouse** [comment]
You could use native event delegation, or use CSS queries to find the body element and attach an event listener (but note the body may get trashed and re-rendered depending on changes to the table content)

With event delegation you can listen for events on an outer element, filtering for the `tbody` element.

You could also try using `@scroll.native="someMethod"` on the `b-table` component (the first argument will be the native event), and then filter the event for the `tbody` element.  But I think scroll events on elements do not bubble up. Maybe using the `wheel` event might work (but wouldn't capture someone moving the scroll bar with the mouse)

**Comment by addijhaq** [comment]
>  CSS queries to find the body element and attach an event listener (body may get trashed and re-rendered depending on changes to the table content)

it does, so this isn't ideal

> But I think scroll events on elements do not bubble up.

they do not, so i cannot get the scroll to register on the b-table since it's originating on `tbody`

really need a way for bootstrap-vue to allow us to not just apply css classes via attributes to child elements, but also target the child elements to add events, etc. 

it's easy enough for me to create a slot for a table cell and add an element to it and then add events to that element (e.g putting an `<img>` in a table cell and then adding `@click` to the `<img>`)

**Comment by tmorehouse** [comment]
Maybe we could emit an event `bodyscroll` (with the arg being the native event object)  whenever the `<tbody>` element receives a scroll event.

**Comment by addijhaq** [comment]
>  (with the arg being the native event object)
meaning the `<tbody>` element or the `<b-table>` element?

**Comment by tmorehouse** [comment]
Not the element itself, but the scroll event triggered from the tbody.

Basically we could do this inside of the `b-table` component:
```html
  <tbody @scroll="$emit('bodyscroll',$event)">
```

and you would do this when using it:
```html
<b-table @bodyscroll="onBodyScroll" ... >
```

```js {
 methods: {
   onBodyScroll(event) {
     // event.target === tbody element
     // do something on scroll
  }
}
```

**Comment by tmorehouse** [comment]
Also note slots are for inserting content into a section of a component.  It  wouldnt be possible to make the body a scoped (or named) slot, as that element is where `b-table` renders its rows and cells.

The scoped slots for fields and headers insert the content inside of the `b-table` rendered `td` and `th` elements (it doesn't replace them).

**Comment by tmorehouse** [comment]
BootstrapVue 2.0.0-rc.28 (released today) introduces a new component `<b-table-simple>` which gives you control over the rendering of the table. You will need to handle managing your items and fields manually... but it is an alternative option.
