### ISSUE TITLE
Add support for dropleft / dropright on Bootstrap dropdown

### ISSUE THREAD

**Issue by tommcclean** [bootstrap-vue/bootstrap-vue#2108]
The standard bootstrap drop down allows you to dropleft and dropright but the component in Bootstrap-Vue only allows dropup and dropdown.

Source: https://getbootstrap.com/docs/4.0/components/dropdowns/#dropleft-variation

It would be useful for this component to support the left and right variations, for instances where you are using the drop down on the right side of the screen on mobile. The dropdown's simply appear mostly off screen with the current set of variations.

Example shown here - https://imgur.com/a/d6fGYmG

I seem to be unable to feed the dropleft attribute into the current component to achieve the desired affect.

**Comment by tmorehouse** [comment]
That feature is definitely on our roadmap for `b-dropdown`
