### ISSUE TITLE
b-table:The computed property "fields" is already defined in data.

### ISSUE THREAD

**Issue by EtheriousNatsu** [bootstrap-vue/bootstrap-vue#2109]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/bootstrap-vue/bootstrap-vue/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/CONTRIBUTING.md)

When asking general "how to" questions:

- Please avoid opening an issue here
- Instead, ask for help on StackOverflow, IRC, or [Slack](https://bootstrap-vue.now.sh/), and also check out the [online documentation](https://bootstrap-vue.js.org)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Version of Bootstrap-Vue that you are using
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/), [JS Bin](https://jsbin.com/), or [JsFiddle](https://jsfiddle.net/) (You can export markup from the [online playground](https://bootstrap-vue.js.org/play) to JS Fiddle)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

Love bootstrap-vue? Please consider supporting our collective:
👉  https://opencollective.com/bootstrap-vue/donate

Operating system: macos
Browser:Chrome
Version of Bootstrap-Vue: 2.0.0-rc.11

problem：
when use b-table, there is a inner error happen

![image](https://user-images.githubusercontent.com/12187260/47603990-4a011f00-da26-11e8-81d3-3f7710736177.png)
![image](https://user-images.githubusercontent.com/12187260/47603996-5a18fe80-da26-11e8-8abb-eeadf9afb26f.png)
![image](https://user-images.githubusercontent.com/12187260/47604000-68ffb100-da26-11e8-968c-5bd5fc6b6dd0.png)

**Comment by tmorehouse** [comment]
Possible duplicate of #1270 

Sounds like you are using a plugin that injects non-name-spaced computed properties into all Vue components, such as a validator.

And if you are using vee-validate, you can stop vee-validate's injection into all components. See http://vee-validate.logaretm.com/advanced.html#inject for details

**Comment by tmorehouse** [comment]
These types of plugins should be name-spacing their injections (i.e. `$vvFields` instead of `fields`), as to avoid conflicts with other components.

**Comment by EtheriousNatsu** [comment]
thank you

**Comment by tmorehouse** [comment]
Does this solve your issue?

**Comment by EtheriousNatsu** [comment]
yes. thank you again

**Comment by TroyeXu** [comment]
thx

**Comment by brijeshladani** [comment]
When you use vee validate and b-table at same time then this error will appear.
 
You can rename vee validate prop name by:

import VeeValidate from 'vee-validate'
Vue.use(VeeValidate, {
  fieldsBagName: 'vee-fields',
})

then this name conflict will solve
