### ISSUE TITLE
Tree-shaking bootstrap-vue with webpack 

### ISSUE THREAD

**Issue by milenon** [bootstrap-vue/bootstrap-vue#211]
Probably the fault is not related to bootstrap-vue but just to ask:
 
I'm using the latest vue-cli with webpack@2.3.3. When I'm running the production build the way it is documented:

```
import Vue from 'vue'
// ES build is more efficient by reducing unneeded components with tree-shaking.
import BootstrapVue from 'bootstrap-vue/dist/bootstrap-vue.esm';
Vue.use(BootstrapVue); 
```

it is not being TreeShaken and the whole bootstrap-vue(~52KB) and tether.js(~24KB) is included in the build although I'm using only a Dropdown component. 

When I'm importing only the wanted component

`import Dropdown from 'bootstrap-vue/lib/components/dropdown.vue`

undestandably the build is much smaller.

The question is what should I do in order to have a tree shaken build?

**Comment by pi0** [comment]
@milenon You are right. For now, tree-shaking won't help us the reason is when we are globally registered components we need to reference all of them so they will be recursively added to the tree! (At least by far as I know) There is not a lazy global register mechanism for Vue components.

**Comment by pi0** [comment]
Will Update docs to remove that banner for now about tree shaking ability :))

**Comment by SirLamer** [comment]
The problem with this request is that the JS package bundler does not know what Bootstrap components you are using in your HTML elements, so it can't do as you are requesting in a magical way. It's pretty reasonable to expect that using ```Vue.use(BootstrapVue)``` will import all assets. However, I think if you import just the components you want using the ES6 method then it would work?

Example (have not tested, just doing approximate example on the fly):
```js
import {popover, table} from 'bootstrap-vue/dist/bootstrap-vue.esm';
Vue.component('bPopover', popover);
Vue.component('bTable', table);
```

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

**Comment by mosinve** [comment]
Bootstap-vue implemented as self-registering Vue plugin, so in ES6 enviroment we even don't have to register it with `Vue.use(boostrapVue)` in our code. 
ES6 partial import methods doesn't make a sense because of it self-registering feature. 
In order to use this method, library has to export all components, not resulting object VuePlugin

https://vuejs.org/v2/guide/plugins.html

**Comment by mosinve** [comment]
That's how export done in vuex.ems for example:
    
    var index_esm = {
      Store: Store,
      install: install,
      version: '2.2.1',
      mapState: mapState,
      mapMutations: mapMutations,
      mapGetters: mapGetters,
      mapActions: mapActions
    };
    export { Store, mapState, mapMutations, mapGetters, mapActions };export default index_esm;

**Comment by pi0** [comment]
@SirLame you are right about that kind of usage (`import { } from 'bootstrap-vue'`) will be shakable. The only problem is that we need to explicitly define dependencies between our components. 

@mosinve Yep that global install pattern which we are using currently is widely used by many other similar projects like [vue-mdl](https://github.com/posva/vue-mdl/blob/develop/src/vue-mdl.js) and is not a bad thing itself as ~20kb gzipped bundle is almost nothing and it allows using every component anywhere without even importing. Anyway there are two reasons we may add support for that partial imports:
- Many people have a different opinion and prefer using individual components, maybe they just want to mix some parts of bootstrap with their project. 
- If you have heard about Critical Path CSS it may be an essential step toward supporting that to be fully PWA compatible.

**Comment by pi0** [comment]
Just found this: https://vuejs.org/v2/guide/components.html#Async-Components

**Comment by SirLamer** [comment]
That has to do with it loading in to memory, as far as I understand this would not have an impact on the compiled package size.
