### ISSUE TITLE
Width of modal

### ISSUE THREAD

**Issue by paultofunmi** [bootstrap-vue/bootstrap-vue#2112]
Hi, what is the recommended way of increasing width sizes of modal.

**Comment by tmorehouse** [comment]
`<b-modal>` supports the three standard sizes (widths) defined by Bootstrap V4 CSS:

- `sm` for small
- `md` for medium (the default)
- `lg` for large

These map to CSS classes `modal-sm`, `modal-md`, and `modal-lg`. Bootstrap-Vue takes the size value (via the `size` prop) and prepends `modal-` to it and uses that as the class. This class is placed on the element that has the class `modal-dialog`.

You could define your own size, say `foo`, which would get mapped by Bootstrap-Vue to `modal-foo`.  Then in your project CSS build the appropriate CSS (with responsive breakpoints) that sets the size you would like. 

```css
.modal-foo : {
 width: 666px;
}
```

**Comment by paultofunmi** [comment]
Thanks. I need a bigger view than what modal-lg offers. I will use the latter option of foo you recommended.

**Comment by tmorehouse** [comment]
Maybe use a percentage width (allow room for margins), so that your modal will fit the width of the viewport.

**Comment by tmorehouse** [comment]
Bootstrap V4.2 (not yet released) has a new larger modal size available: `.modal-xl`

**Comment by HP-jackZhang** [comment]
how can I set className='modal-foo'? what i should do?

**Comment by tmorehouse** [comment]
@HP-jackZhang

If `.modl-foo` is a custom class for setting the modal width, then you can just set the prop `size="foo"`.

If you want an arbitrary class applied to the modal (or one of its internal parts), you need to pass the full class name to one of the appropriate props: `modal-class`, `content-class`,  `body-class`, `header-class`, or `footer-class`

**Comment by demiavaliani** [comment]
> @tmorehouse 
> 
> If `.modl-foo` is a custom class for setting the modal width, then you can just set the prop `size="foo"`.
> 
> If you want an arbitrary class applied to the modal (or one of its internal parts), you need to pass the full class name to one of the appropriate props: `modal-class`, `content-class`, `body-class`, `header-class`, or `footer-class`

This is a really really great syntax, thanks for sharing. Yet, 3 years has passed, and I found out about it only now. Just for curiosity, why such features are not mentioned in docs? I have found a lot of interesting features just by digging on forums, and nothing is mentioned about those in docs.
