### ISSUE TITLE
Range input isn't styled in Chrome

### ISSUE THREAD

**Issue by lwchkg** [bootstrap-vue/bootstrap-vue#2113]
As title, and the problem can be seen in the screenshot (left: Firefox, right: Chrome) below. You can also refer to https://jsfiddle.net/mfk1u9yz/ for the test case.

- Operating system and version: Windows 10 and Android
- Browser and version: Chrome 70  (works okay in Firefox)
- Version of Bootstrap-Vue that you are using: 2.00-rc.11
- Reduced test cases: https://jsfiddle.net/mfk1u9yz/

![2018-10-28_22-25-55](https://user-images.githubusercontent.com/4113719/47617365-78076180-db01-11e8-845a-f3eff707a3d7.png)

**Comment by tmorehouse** [comment]
This is probably a Bootstrap V4 CSS issue.  as they do not apply custom styling to the range component.

The range input uses the native browser styling, although Bootstrap-Vue applies some custom CSS to make the height and width match that of other input components.  It doesn't do any styling of the range knob (that is browser dependent).

**Comment by lwchkg** [comment]
Thanks for telling. Anyway, I've found that it's Firefox automatically styling the ranged input so well.

BTW, looks like I can just wait for your new code to get released, instead of doing the styling by my own. :-)

**Comment by Ascyt** [comment]
But it is styled in the [official documentation](https://bootstrap-vue.org/docs/components/form-input)? 

Here is my HTML: 
``` html
<b-form-group class="mb-2" label="Temperature">
    <b-row>
        <b-col cols="3">
        <b-form-input type="range" v-model="config[selectedConfig].temperature" min="0" max="2" step="0.1"></b-form-input>
        </b-col>
        <b-col cols="9">
        <b-form-input type="number" v-model="config[selectedConfig].temperature" min="0" max="2"></b-form-input>
        </b-col>
    </b-row>
</b-form-group>
```

The styling for the range doesn't work.
