### ISSUE TITLE
Arrow sorting direction is wrong

### ISSUE THREAD

**Issue by yudy-chen** [bootstrap-vue/bootstrap-vue#2126]
It seems that the arrow of sorting table is wrong. See it's example from https://bootstrap-vue.js.org/docs/components/table/. Change the sorting direction and see the arrow. The sorting direction is ascending but the arrow is for descending. It's vice versa

**Comment by tmorehouse** [comment]
Ascending on age (Arrow pointing down):
![image](https://user-images.githubusercontent.com/2781561/47948916-8cd86080-df18-11e8-886b-949ca6080ee3.png)

Descending on age (arrow pointing up):
![image](https://user-images.githubusercontent.com/2781561/47948921-9e216d00-df18-11e8-84c3-9263128be734.png)

The arrow refers to the direction (smallest to largest) the data is increasing in value, so is correct.

**Comment by yudy-chen** [comment]
Oh, I think most of the tables are opposite with this.
Take a look some of the example below

Jquery datatable:
![image](https://user-images.githubusercontent.com/44719951/48002966-0e620580-e148-11e8-8b88-b908fb063485.png)


Material-UI
![image](https://user-images.githubusercontent.com/44719951/48003060-4f5a1a00-e148-11e8-9a2f-ef559ab81681.png)

Material.angular.io
![image](https://user-images.githubusercontent.com/44719951/48003093-6862cb00-e148-11e8-8537-c648924e4737.png)

Well, I don't say that it needs to be the same, but it makes a confusing I think.

**Comment by tmorehouse** [comment]
Arrows should _point towards the largest values_, and signify the current direction (not the direction to be changed to).  Think of the phrases "I am sorting downwards" or " I am sorting upwards"

**Comment by yudy-chen** [comment]
Oh, ok if this is the case.

**Comment by MichaelMcCoyTech** [comment]
@tmorehouse I agree that you are semantically correct in your answer but I feel that @yudy-chen is correct.   My gut "feel" is that the arrows are the wrong way round.   I have used many grid components in development over the years and this has led me to a perception of how this should work.  I am not saying my perception is correct - this is purely how it feels and how I expect it to behave.    Perhaps the solution here is to add a property - allowing the developer to invert the default behaviour if they wish ?

**Comment by tmorehouse** [comment]
If the arrows were "triangles", then yes,  the wider portion of the triangle would mean the "bigger" data is in that direction".  But these are arrows, not triangles, pointing in the direction of sorting.

**Comment by MichaelMcCoyTech** [comment]
I accept that you can explain your rationale but it seems to be a very subjective decision and the fact that you need to explain it suggests there is room for misinterpretation.  Given this it would seem reasonable to support developer configuration of the sort icon orientation.

**Comment by tmorehouse** [comment]
Styling of the icons is via CSS/SCSS. You can change the content (from an arrow to whatever) via the CSS `::after` pseudo selector.
