### ISSUE TITLE
Please inherit relatedTarget from original event for modal.show

### ISSUE THREAD

**Issue by ColinTree** [bootstrap-vue/bootstrap-vue#2127]
As [Bootstrap.Modal](https://getbootstrap.com/docs/4.0/components/modal/#varying-modal-content) designed, data can be fetch from the trigger button to the modal.

But when I tried to do this in `bootstrap-vue`, `event.relatedTarget` seems being null when I need it. (And I'm sure that I trigger the modal via a button, a `b-btn`)

Modal show trigger:
![image](https://user-images.githubusercontent.com/22613139/47956279-f1f58a00-dfdc-11e8-9bd3-197515c031ed.png)

Related methods:
![image](https://user-images.githubusercontent.com/22613139/47956271-d25e6180-dfdc-11e8-8939-d58bd69bb9a7.png)

Browser Console:
![image](https://user-images.githubusercontent.com/22613139/47956259-aa6efe00-dfdc-11e8-940b-1a5a70c835cf.png)

**Comment by tmorehouse** [comment]
In this `BvEvent` _custom_ event object, `.relatedTarget` is not always know, as any number of things could have triggered the show/hide. i.e.
- another modal opening,
- buttons with click handlers we dont control,
- a method changing the modals modal visibility (i,e, v-model),
- someone calling the `.show()`, or `.hide()` methods,
- etc, etc, etc.

So in 99% of the cases, we never know what the related target is.

`BvEvent` is **not** the same as a native browser event,  nor does it inherit anything from a native event.  It just happens to _look_ similar.

**Comment by ColinTree** [comment]
Thanks for replying.
So I decided to add a method in the modal template component to handle modal data input instead.

**Comment by tmorehouse** [comment]
The modal `.hide()` method takes one argument (a string, typically, but it can be anything), which is placed into the `BvEvent` `.trigger` property. 

Normally this is used to signify which button was pressed (i.e. `'ok'` for the default OK button,  `'cancel'` for the default cancel button, `'modal-close'` for the upper right hand modal close (&times;) button, `'backdrop'` if clicking the back drop triggered the hide, `'esc`' if pressing the <kbd>Esc</kbd> key triggered the hide.

You can call the `.hide()` method via your own click/button handlers, and pass it a value to signify what event triggered the event (via the `evt.trigger` property.

**Comment by ColinTree** [comment]
@tmorehouse Thanks for this info.
What I'm facing here is that, I got two button, one is `Add` and another is `Edit`. Both these two buttons open a same modal, and the modal title & data to be load depend on which button is actually clicked, but I cant find a way to do this without passing a prop or adding a value.
(Originally I add `data-mode` prop for both button, and it with be read by the modal automatically by hook `show`.)

**Comment by tmorehouse** [comment]
Currently the `show()` method doesn't support passing a value to it, but it might be something we could do, and pass that value into the show events emitted. 

The other option is to have your button handlers set a flag in your app/component data, and then inspect that value on modal open to determine which button triggered the open.

**Comment by ColinTree** [comment]
No worries, that is what I think I should do.
