### ISSUE TITLE
Dropdown offset in navbar does nothing

### ISSUE THREAD

**Issue by skourismanolis** [bootstrap-vue/bootstrap-vue#2130]
- Operating system and version: Windows 10 1803
- Browser and version: Chrome 70, Firefox 63
- Version of Bootstrap-Vue: Latest (v2.0.0-rc.11)
- Reduced test case: [jsFiddle](https://jsfiddle.net/3d6tjm1g/)

When you have a `b-nav-dropdown` component inside a `b-navbar-nav` component, the `offset` prop of the `b-nav-dropdown` does nothing, having a `b-nav-dropdown` inside a `b-nav` component works fine with the `offset `prop.

Code from the jsFiddle (shortened):

```
<b-navbar type="dark" variant="primary" toggleable>
      <b-navbar-nav>
        <!-- These don't work -->
        <b-nav-item-dropdown text="offset 50 right" offset='50' right>
        </b-nav-item-dropdown>
        <b-nav-item-dropdown text="offset 0 right" right>
        </b-nav-item-dropdown>
        <b-nav-item-dropdown text="offset 50 left" offset='50'>
        </b-nav-item-dropdown>
        <b-nav-item-dropdown text="offset 0 left">
        </b-nav-item-dropdown>
      </b-navbar-nav>
</b-navbar>

<b-nav>
        <!--These work -->
        <b-nav-item-dropdown text="offset 50 right" offset='50' right>
        </b-nav-item-dropdown>
        <b-nav-item-dropdown text="offset 0 right" right>
        </b-nav-item-dropdown>
        <b-nav-item-dropdown text="offset 50 left" offset='50'>
        </b-nav-item-dropdown>
        <b-nav-item-dropdown text="offset 0 left">
        </b-nav-item-dropdown>
</b-nav>
```

**Comment by tmorehouse** [comment]
The `offset` prop is only appled to the `<b-dropdown>` component, not the dropdown items (they don't have an `offset` prop)

Offset control the relative positioning of the dropdown menu as a whole relative to the dropdown trigger element. See https://bootstrap-vue.js.org/docs/components/dropdown#menu-offset

**Comment by tmorehouse** [comment]
Also note that for navbars, dropdown positioning (offset) is controlled by CSS alone and not `Popper.js`

**Comment by tmorehouse** [comment]
Documentation has been updated to reflect this.

**Comment by Edmund1645** [comment]
I seem to be having difficulties in changing the offset of the dropdown menu,
here's how I did mine:
```html
            <b-dropdown
              toggle-class="text-reset"
              no-caret
              variant="link"
              :popper-opts="{modifiers: [{
                name: 'offfset',
                options: {
                  offset: [10, 20]
                }
              }]}"
            >
              <template v-slot:button-content>
                <b-img class="rounded-circle" width="40px" blank blank-color="#88f" alt="lame img"></b-img>
                <unicon name="angle-down" fill="currentColor"></unicon>
              </template>

              <b-dropdown-item>Hello</b-dropdown-item>
            </b-dropdown>

````

I looked at the poppper doc  [here](https://popper.js.org/docs/v2/modifiers/offset/)
