### ISSUE TITLE
b-form-input does not work well when Japanese IME is enabled

### ISSUE THREAD

**Issue by medaka** [bootstrap-vue/bootstrap-vue#2131]
# Abstract

b-form-input does not work well when Japanese IME is enabled

## in Japanese (for Search Engine)

日本語IMEで b-form-input を用いるとうまく入力できない。

# Conditions and Environments

* iOS
    * Safari and Chrome
* Desktop
    * occured in just only Safari

# Details

Have a watch this animation.

![capture mov](https://user-images.githubusercontent.com/1182770/47964399-f4a7bc00-e07c-11e8-95e1-a4742b8fadc1.gif)

A first input form is composed of <code>b-form-input</code>. Second one is naive <code>input</code> tag.
I've tried to type 't' 'e' 's' 'u' 't' 'o' to input 'てすと'. First trial failed and it turned to 'ｔててｓてすてすｔてすとてすと'. Duplication seems to be occured. Second one succeeded.

**Comment by tmorehouse** [comment]
This is a known issue, and should hopefully be fixed in the next release.

**Comment by tmorehouse** [comment]
PR Merged into dev branch
