### ISSUE TITLE
b-pagination not working with v-for only works with b-table

### ISSUE THREAD

**Issue by Codefa** [bootstrap-vue/bootstrap-vue#2133]
`b-pagination`  or `b-pagination-nav` not working with v-for only works with `b-table`
please give a example `b-pagination`  or `b-pagination-nav` works with 
`<div v-for="item in items>`

**Comment by tmorehouse** [comment]
Whenever you use `v-for`, make sure you set a unique `key` attribute.

See https://vuejs.org/v2/guide/list.html#key

**Comment by tmorehouse** [comment]
Ah, the `per-page` only applies to the pagination component.  You need to _slice_ your data when presenting it to your `v-for` loop (you are currently giving it the _entire list_)

```html
<template>
  <div  v-for="list in lists" :key="list.id">
    {{ list.name }}
  </div>
  <b-pagination
     :total-rows="totalRows" 
     v-model="currentPage"
     :per-page="perPage"
  />
</template>
<script>
export default {
  data () {
    return { 
      currentPage: 1,
      perPage: 5,
    }
  },
  computed: {
    lists () {
      const items = this.$store.getters.loadedLists
      // Return just page of items needed
      return items.slice(
        (this.currentPage - 1) * this.perPage,
        this.currentPage * this.perPage
      )
    },
    totalRows () {
      return this.$store.getters.loadedLists.length
    }
  }
}
</script>
```

**Comment by Codefa** [comment]
@tmorehouse Thank you very much i just forgot to use some logics and i did it with ` <b-pagination-nav` works fine (actually i want to link routes too ) 
working code here 👍 for who thinks its hard to implement pagination with router links
``` vue
<template>
<div id="lists">
  <div  v-for="list in lists" :key="list.id">
    {{ list.name }}
  </div>
</div>
<b-pagination-nav :link-gen="linkGen" :number-of-pages="5" v-model="currentPage" />
</template>

<script>
export default {
  data () {
    return { 
      currentPage: 1,
      perPage: 2
    }
  },
computed: {
    lists () {
      const items = this.$store.getters.loadedLists
      // Return just page of items needed
      return items.slice(
        (this.currentPage - 1) * this.perPage,
        this.currentPage * this.perPage
      )
    }
  },
  methods: {
    linkGen (pageNum) {
      return '#page=' + pageNum
    }
  }
}
</script>
```

**Comment by tmorehouse** [comment]
If you are using vue-router, then for your `linkGen` function, you could return:

```js
  return { path: '#page=' + pageNum }
```

Which is a router route object

Or set `user-router` on the `b-pagination-nav` component, to make the generated links use a `<router-link>` instead of a normal `<a>` tag.
