### ISSUE TITLE
Cannot Extend b-button without getting an error.

### ISSUE THREAD

**Issue by austinstudio** [bootstrap-vue/bootstrap-vue#2137]
I am trying to create my own button component and extend the b-button one.  I have the following code:

    <template>
        <b-button></b-button>
    </template>
    <script>
        import bButton from 'bootstrap-vue/es/components/button/button';

        export default {
            extends: bButton,
        };
    </script>

When I include this on my page and it runs, I get the following error in the console.  I haven't been able to find out how to fix this.

> TypeError: Cannot read property '$createElement' of null
>     at render (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"3c8e0560-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/dp-actions/dp-button.vue?vue&type=template&id=fae243e0& (app.js:3258), <anonymous>:6:16)
>     at createFunctionalComponent (vue.runtime.esm.js?2b0e:4056)
>     at createComponent (vue.runtime.esm.js?2b0e:4246)
>     at _createElement (vue.runtime.esm.js?2b0e:4416)
>     at createElement (vue.runtime.esm.js?2b0e:4353)
>     at vm._c (vue.runtime.esm.js?2b0e:4485)
>     at Proxy.render (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"3c8e0560-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/pages/FormControls.vue?vue&type=template&id=3a1e093e& (app.js:3342), <anonymous>:125:21)
>     at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:4540)
>     at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:2784)
>     at Watcher.get (vue.runtime.esm.js?2b0e:3138)

**Comment by tmorehouse** [comment]
The component `b-button` is a lightweight  _functional_ component, meaning it does not have a `this` context.

See https://vuejs.org/v2/guide/render-function.html#Functional-Components

So it is not possible to `extends` it into a regular component that has a `this` context.

You would need to "wrap" it rather than extend it.

**Comment by austinstudio** [comment]
Do you know if this would also not work with minxin?

If I wrap it, won't I have to define all of the props and pass them through?

**Comment by tmorehouse** [comment]
Mixins also rely on having a `this` context.

But you can do this to access the components prop definitions:

```html
<template>
 <b-button v-bind="$props">something here</b-button>
</template>
<script>
import  bButton from 'bootstrap-vue/es/components/button/button'
const btnProps = bButton.options.props // Treat this as read only!!

export default: {
  components: { bButton }
  props: {
    ...btnProps,
    myProp: {
      type: String,
      default: ''
    },
    myPropB: {
      type: String,
      default: 'b'
    }
  }
}
</script>
```

The special `v-bind="$props"` directive binds all props that hte parent has in common with the child component.

For `v-bind` reference see https://vuejs.org/v2/api/#v-bind

if you don't have hte bable transform for object-spread enabled (i.e. `...props`, then convert the props to the following:

```js
  props: Object.assign({}, btnProps, {
    myPropA: {
      type: String,
      default: ''
    },
    myPropB: {
      type: String,
      default: 'b'
    }
  }),

**Comment by austinstudio** [comment]
Awesome, I will give this a try.  Didn't know there was a quicker way to get all the props from the original component like that.  Will try and post back how it went.

**Comment by austinstudio** [comment]
Well, it sort of worked.

I had to modify a bit, but when I went to extend my extended control it doesn't pass the attributes through.  My modified version is the following:

    <template>
         <b-button v-bind="$props">
            <slot></slot>
        </b-button>
    </template>

    <script>
        import bButton from 'bootstrap-vue/es/components/button/button';
    
        const btnProps = Object.assign({}, bButton.props);

        export default {
            components: { bButton },
            props: {
                ...btnProps,
            }
        }
    </script>

This worked by itself and the props pass through.  So when I try to consume this by a specific project, extending it once again, it doesn't pass through the props.  I have tried the following:

    <template>
        <dpButton>
            <slot></slot>
        </dpButton>
    </template>
    <script>
        import dpButton from '@poire-io/dpatterns-vue';

        export default {
            extends: dpButton,
        };
    </script>

And I have also tried:

    <template>
        <dpButton v-bind="$props">
            <slot></slot>
        </dpButton>
    </template>
    <script>
        import dpButton from '@poire-io/dpatterns-vue';

        const btnProps = Object.assign({}, dpButton.$props);

        export default {
            components: { dpButton },
            props: {
                ...btnProps,
            },
        };
    </script>

They both render the button but neither of the methods pass the props from the original component.


Let me explain what I am doing a bit.  I have a pattern library that I am building.  This pattern library will extend the vue bootstrap controls.  Then I have a project that is going to consume the pattern library and will extend the pattern library controls to include any project-specific props and styling, code, etc.

**Comment by tmorehouse** [comment]
In your 3rd code sample above, use the following:

```js
    const btnProps = Object.assign({}, dpButton.options.props);
```

`$pops` is only populated after mount. `dpButton` is just a definition (no `this`) until it is mounted

**Comment by austinstudio** [comment]
Ok will try it.  The "options" thing from your first code sample didn't work so I had to remove it to make the first section of my code work.

**Comment by tmorehouse** [comment]
Ah, the options is only be available after the component (b-button) has been added to Vue.  My bad.

Since you are just importing a plain object (the component definition), then .props is what you want.

**Comment by austinstudio** [comment]
Ok cool, no worries.  Your code helped immensely.  Let me try this on extension of the extension.  Not sure if it makes sense what we are doing but I guess it allows us to change things in the pattern library and also change things globally in the solution itself as well.

**Comment by austinstudio** [comment]
So.. I tried a few things.  The first thing I tried was what you mentioned.

    <template>
        <dpButton v-bind="$props">
            <slot></slot>
        </dpButton>
    </template>
    <script>
        import dpButton from '@poire-io/dpatterns-vue';

        const btnProps = Object.assign({}, dpButton.props);

        console.log(btnProps);

        export default {
            components: { dpButton },
            props: {
                ...btnProps,
            },
        };
    </script>

This didn't work.  The only thing that was attached to the button was the $route and I got the following error:

    [Vue warn]: Failed to mount component: template or render function not defined.

Then I used the following:

    <template>
        <dpButton>
            <slot></slot>
        </dpButton>
    </template>
    <script>
        import dpButton from '@poire-io/dpatterns-vue';

        export default {
            extends: dpButton,
        };
    </script>

This works and it looks like, in the vue dev tools plugin, that it is passing all of the props, but when I actually use them on the button, the value doesn't actually pass to the component.

**Comment by austinstudio** [comment]
Just to follow up, if I manually define the prop, it works.  So if I do the following, the "variant" prop works but still none of the others do.  Do I need to define all of the props one at a time?

    <template>
        <dpButton :variant="variant">
            <slot></slot>
        </dpButton>
    </template>
    <script>
        import dpButton from '@poire-io/dpatterns-vue';

        export default {
            extends: dpButton,
            props: {
                variant: {
                    type: String,
                },
            },
        };
    </script>

**Comment by tmorehouse** [comment]
you can try setting inheritAttrs on your component, and then 'v-bind="$attrs"' on the button. this won't make the props appear on your component, but it will pass any attrs/props not defined on your component to the button component.

**Comment by austinstudio** [comment]
Thanks for your help.  Will close this for now.
