### ISSUE TITLE
Hide outdated GitHub Wiki page or refer to docs directly

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#2138]
The [Wiki page](https://github.com/bootstrap-vue/bootstrap-vue/wiki) is outdated and redundant because the  [Bootstrap-Vue docs](https://bootstrap-vue.js.org/) provide detailed information on how to use this project.

Refering to the docs directly or hiding the page completely would be good to not cause any confusion.

**Comment by tmorehouse** [comment]
Slight fixed now.

The wiki was mainly meant o be cor the team coding Bootstrap-Vue internals (coding standards, naming conventions, prop conventions, etc).

I've removed the no longer needed pages and edited the main wiki page.
