### ISSUE TITLE
Tooltip directive does not update tooltip content while tooltip is visible

### ISSUE THREAD

**Issue by gitlab-winnie** [bootstrap-vue/bootstrap-vue#2142]
When the title of a tooltip directive is reactive, the tooltip is not updated while it is visible.
The tooltip needs to be hidden and shown again before the content is refreshed.

video of the bug: https://gitlab.com/gitlab-org/gitlab-ui/uploads/08102a4888bce5e8004d9e880858088d/tooltip-update.mp4

> - Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
> - Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)

should not matter

> - Version of Bootstrap-Vue that you are using

Happens with v2.0.0-rc.11 on https://bootstrap-vue.js.org/docs/directives/tooltip.

> - Reduced test cases 

https://jsfiddle.net/winnie_gitlab/eywraw8t/447515/

> and potential fixes

at least a workaround: https://jsfiddle.net/winnie_gitlab/ne85j3u4/

**Comment by tmorehouse** [comment]
This is as designed.  Use the tool tip component instead if you need reactive content. This behaviour is documented.

**Comment by gitlab-winnie** [comment]
@tmorehouse Thank you for taking a look!

> This behaviour is documented.

Could you please point me to the documentation? I couldn't find it mentioned on https://bootstrap-vue.js.org/docs/directives/tooltip/. Happy to submit a pull request to make this more clear.

**Comment by tmorehouse** [comment]
Hmm it used to be in the tooltip docs.  It is in the popover docs (when talking reactive content), which inherits from tooltip.

**Comment by gitlab-winnie** [comment]
>  It is in the popover docs (when talking reactive content)

@tmorehouse I also cannot find anything about reactive content on https://bootstrap-vue.js.org/docs/directives/popover. 🤔

Could you provide me with a link to the part you are referring to?

**Comment by tmorehouse** [comment]
See the component version docs... not the directive.

**Comment by gitlab-winnie** [comment]
Thank you, found it: https://bootstrap-vue.js.org/docs/components/popover/

**Comment by tmorehouse** [comment]
Working on a few things to see if we can make directive versions more reactive to changes.

**Comment by gitlab-winnie** [comment]
That sounds great! 👍

Let me know if there is anything in particular (for example updating the docs) that you could need help with.

**Comment by tmorehouse** [comment]
@gitlab-winnie release v2.0.0 stable of BootstrapVue now has reactive directive versions of tooltips and popovers.  Changes to the `title` attribute (and config options/modifiers) are now also reactive.
