### ISSUE TITLE
How to customise the button text of "Browse" in b-form-file

### ISSUE THREAD

**Issue by ColinTree** [bootstrap-vue/bootstrap-vue#2143]
I used `vue-i18n` to internationalize my app, but got stuck by this:
![image](https://user-images.githubusercontent.com/22613139/48001980-28e6af80-e145-11e8-9879-c8a46de304cf.png)

**Comment by ColinTree** [comment]
Currently the possible way is to add css to it, but not elegant / standardized enough, especially with `vue-i18n`

**Comment by tmorehouse** [comment]
Yeah, this is basically a Bootstrap V4 issues (check their docs, they only allow the contnet to be specified via css). It sucks.

But we are working on a solution that may address this issues.

I would recommend also opening an issue on Bootstrap V4's repo asking for a way to set the title via `data-` attributes.

**Comment by jackmu95** [comment]
This should be resolved by https://github.com/twbs/bootstrap/pull/27651 in the upcoming Bootrap v4.2.

**Comment by tmorehouse** [comment]
We could put in a temporary fix+css for this until V4.2 is released (once released we can just remove the custom CSS)
