### ISSUE TITLE
B-table data loading very slow

### ISSUE THREAD

**Issue by amirakbulut** [bootstrap-vue/bootstrap-vue#2145]
I'm using Laravel and Vue for a project I'm working on. Within my dashboard I'm using BootstrapVue's datatable named B-table, which receives JSON data from my API.

The API currently only returns 1 user, however it takes quite some time to load it even though it's just 1 row. I created this GIF to show you it's loading time when refreshing the webpage:

![](https://i.stack.imgur.com/7aj9w.gif)

I'm using Axios to receive data from my API, I'm very curious what's causing it to be this slow. Here is my code:

```
<template>
    <div>
        <div id="main-wrapper" class="container">
            <div class="row">
                <div class="col-md-12">
                    <hr>
                    <b-table busy.sync="true" show-empty striped hover responsive :items="users" :fields="fields" :filter="filter" :current-page="currentPage" :per-page="perPage" @refreshed="verfris">
                        <template slot="actions" slot-scope="data">
                            <a class="icon" href="#"><i class="fas fa-eye"></i></a>
                            <a class="icon" href="#"><i class="fas fa-pencil-alt"></i></a>
                            <a class="icon"><i class="fas fa-trash"></i></a>
                        </template>
                    </b-table>
                    <b-pagination :total-rows="totalRows" :per-page="perPage" v-model="currentPage" class="my-0 pagination-sm" />
                </div>

            </div>

        </div>
    </div>
</template>
<script>
    export default {

        data() {
            return {
                users: [],
                filter: null,
                currentPage: 1,
                perPage: 10,
                totalRows: null,
                selectedID: null,
                fields: [
                    {
                        key: 'id',
                        sortable: true
                    },
                    {
                        key: 'name',
                        sortable: true
                    },
                    {
                        key: 'email',
                        sortable: true
                    },
                    {
                        key: 'actions'
                    }

                ],
            }
        },
        mounted() {
            this.getResults();
        },
        methods: {
            // Our method to GET results from a Laravel endpoint
            getResults(ctx, callback) {
                axios.get('/api/users')

                    .then(response => {
                        this.users = response.data;
                        this.totalRows = response.data.length;
                        return this.users;
                    });
            }
        },

    }
</script>
```

And the JSON data my API returns:

`
[
    {
        "id": 1,
        "name": "test",
        "email": "user@user.nl",
        "email_verified_at": null,
        "created_at": "2018-09-28 16:04:36",
        "updated_at": "2018-09-28 16:04:36"
    }
]
`

What can I do to solve this loadtime issue? I'm using an Ubuntu server in VirtualBox.

**Comment by tmorehouse** [comment]
How much time does your `axios.get(...)` taking to complete? This could be the reason your table updates slow

Try this:
```js
export default {
  data() {
    return {
      fetchTime: 0,
      busy: false,
      // rest of your data def here
    }
  },
  methods: {
    getResults(ctx, callback) {
      this.busy = true // set table busy state styling
      const start = Date.now()
      axios
       .get('/api/users')
       .then(response => {
        this.users = response.data
        this.totalRows = response.data.length
        this.busy = false // clear table busy state styling
        // calculate the time for the fetch to complete in seconds
        this.fetchTime = (start - Date.now()) / 1000
        return this.users
    })
  }
}
```
And then in your template show the fetch time
```html
<p>Response fetch time: {{ fetchTime }} seconds</p>
```

**Comment by amirakbulut** [comment]
> How much time does your `axios.get(...)` taking to complete? This could be the reason your table updates slow
> 
> Try this:
> 
> ```js
> export default {
>   data() {
>     return {
>       fetchTime: 0,
>       busy: false,
>       // rest of your data def here
>     }
>   },
>   methods: {
>     getResults(ctx, callback) {
>       this.busy = true // set table busy state styling
>       const start = Date.now()
>       axios
>        .get('/api/users')
>        .then(response => {
>         this.users = response.data
>         this.totalRows = response.data.length
>         this.busy = false // clear table busy state styling
>         // calculate the time for the fetch to complete in seconds
>         this.fetchTime = (start - Date.now()) / 1000
>         return this.users
>     })
>   }
> }
> ```
> 
> And then in your template show the fetch time
> 
> ```
> <p>Response fetch time: {{ fetchTime }} seconds</p>
> ```

This is the response time of the request to my API.

![](https://i.stack.imgur.com/3VXhR.png)

**Comment by tmorehouse** [comment]
So that is the reason your table is slow.. 1.25 seconds to fetch.

**Comment by amirakbulut** [comment]
> So that is the reason your table is slow.. 1.25 seconds to fetch.

Well, how do I know what's causing it? It's literally just one row.

**Comment by tmorehouse** [comment]
Your api endpoint (`/api/users`) took 1.25 seconds to generate the response (TTFB time to first byte)

So you will need to look at the code in your api endpoint. It is not a `b-table` issue.

**Comment by amirakbulut** [comment]
> Your api endpoint (`/api/users`) took 1.25 seconds to generate the response (TTFB time to first byte)
> 
> So you will need to look at the code in your api endpoint. It is not a `b-table` issue.

I'm not doing anything special in my API code. This is my resource:

![](https://i.imgur.com/fdzX140.png)

And here is how I return my users:

![](https://i.imgur.com/AnRWapx.png)

Something important, I noticed that when I'm running on localhost using Xampp, the fetching time (Waiting TTFB) is only 200-300ms.

**Comment by tmorehouse** [comment]
Its definitely something in your api code + server timing.

`localhost` would definitely take less time for name (DNS) resolution, etc.  When using remote host, you need to take into account the DNS resolution time, HTTPS (if used) handshaking, and then also the processing power of the remote server.

**Comment by amirakbulut** [comment]
> Its definitely something in your api code + server timing.
> 
> `localhost` would definitely take less time for name (DNS) resolution, etc. When using remote host, you need to take into account the DNS resolution time, network delay/roundtrip time, HTTPS (if used) handshaking, and then also the processing power of the remote server.

I made a git repository on https://github.com/amirakbulut/ledberg, do you have time to clone it and check it out? Would really appriciate that from the bottom of my heart yo.

**Comment by tmorehouse** [comment]
I'm not sure if I'll have any spare time in the immediate future, but will see what I can do, or hopefully someone else may come along and provide some tips/help.

**Comment by amirakbulut** [comment]
> I'm not sure if I'll have any spare time in the immediate future, but will see what I can do, or hopefully someone else may come along and provide some tips/help.

Thank you.

**Comment by sschadwick** [comment]
Not sure if this is within your scope of consideration, however Nuxt.js offers an attractive solution.

Fundamentally, Nuxt.js creates an `asyncData` method within components, which is resolved before the page renders. To the user, the data is always present in the table (once the page loads).

**Comment by tmorehouse** [comment]
There is also another nifty Vue plugin called `vue-async-computed` https://github.com/foxbenjaminfox/vue-async-computed (available on NPM as well)

Which allows you to create computed properties that can fetch data.

**Comment by TVDharma** [comment]
Hi @tmorehouse 

I am facing similar issue(taking time to add the data) not with the API but adding static data around 1000+ to the b-table.

sample example 
```
<template>
<div>
<b-table :items="computedData" />
</div>
</template>
<script>
export default {
return {
computed: {
computedData(){
return [{},{},,,,,{}]      -----------> 1000 + Data available.
}
}
}
}
</script>
```

**Comment by VividLemon** [comment]
How long do you expect a 1000 item table to take to load?

> Hi @tmorehouse
> 
> I am facing similar issue(taking time to add the data) not with the API but adding static data around 1000+ to the b-table.
> 
> sample example
> 
> ```
> <template>
> <div>
> <b-table :items="computedData" />
> </div>
> </template>
> <script>
> export default {
> return {
> computed: {
> computedData(){
> return [{},{},,,,,{}]      -----------> 1000 + Data available.
> }
> }
> }
> }
> </script>
> ```

**Comment by TVDharma** [comment]
@VividLemon Thanks for reply

Is it work as similar to when ever 100 data is available

**Comment by VividLemon** [comment]
> @VividLemon Thanks for reply
> 
> Is it work as similar to when ever 100 data is available

I'd assume 1000 items would be 10x slower to render than 100 items. Truly there is no magic that bootstrap vue can do to make Vue faster. A vfor is a vfor. I'm not sure of theres anything we could do anything to improve this

**Comment by aceofwings** [comment]
@VividLemon  Agreed. If you are trying to render 1000 items in any framework front end, you will see poor performance.  Our tables also do not support lazy loading or viewport-based rendering. I recommend paginating your content or SSR.

**Comment by TVDharma** [comment]
Thanks for reply @VividLemon and @VividLemon 
I resolved this issue through client side pagination.
