### ISSUE TITLE
Modal not displaying when using router

### ISSUE THREAD

**Issue by rwb7041** [bootstrap-vue/bootstrap-vue#215]
I'm having an issue with my modal not displaying. I've attached a zip file with my code, but here's the process I went through:

1. I created a baseline project with `vue-cli` using the following command:

`vue init webpack bootstraptest`

Through the prompts, I answered Yes for using router, and no for everything else.

2. Then I installed bootstrap and bootstrap-vue with

`npm install --save bootstrap bootstrap-vue`

3. I added the following to the `main.js` file:

```
import BootstrapVue from 'bootstrap-vue'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'

Vue.use(BootstrapVue)`

```
4. I modified the Hello.vue file to look like such:

```
<template>
  <div class="hello">
    <h1>Modal Test</h1>
    <b-btn @click="$root.$emit('show::modal', 'modal1')">Show Modal</b-btn>

    <b-modal id="modal1" title="Submit your name">
      <h3>Hello Modal</h3>
    </b-modal>
  </div>
</template>

<script>
export default {
  
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
```

Running this (while using the Chrome Vue dev tools) I can click the button and see the event being fired for the modal to display, but it's not displaying. I tried the same process without using router and it seems to work fine.

[bootstraptest.zip](https://github.com/bootstrap-vue/bootstrap-vue/files/906935/bootstraptest.zip)

**Comment by pi0** [comment]
@rwb7041 Hi. Would you please reproduce this on playground and exporting a js fiddle link?

**Comment by rwb7041** [comment]
@pi0 I'm not sure I can since it uses vue-router. I attached the code at the end of the post

**Comment by pi0** [comment]
Please just provide code used to fire that event.( Your button or ...) I thing you need to add `.stop.prevent` modifiers to click event too.

**Comment by rwb7041** [comment]
`<b-btn @click="$root.$emit('show::modal', 'modal1')">Show Modal</b-btn>`

**Comment by rwb7041** [comment]
Adding `.stop.prevent` did not fix the issue

**Comment by mosinve** [comment]
I download your code. Seems that you use Bootstrap 3 instead of supported 4

**Comment by rwb7041** [comment]
That's bizzare because it worked with bootstrap 3 without using router i thought.... oh well
