### ISSUE TITLE
Responsive Carousel Sizing

### ISSUE THREAD

**Issue by JackSteel97** [bootstrap-vue/bootstrap-vue#2150]
I recently needed to display a decent amount of text on a carousel. Using both the `caption` and `text` attributes of `b-carousel-slide` in addition to some custom elements inside the slide. This caused an issue with small width displays and when there is a lot of text used - the text would be pushed up out of the carousel and hidden as overflow.

I needed the carousel to expand in height to fit whatever content I put inside it. I couldn't find anything online to help, so I just started playing around with the CSS. From the look of it, the main problem is that `.carousel-caption` has `position: absolute`. If this is a design choice, I don't see the reason, but please do enlighten me.

Might be an idea to at least add an option to give the carousel this behaviour(?) 

If anyone else is googling about this issue, the below CSS fixed it for me, though I have only tested this for my specific use-case. 

    #myCarousel{
        height: auto;
    }
    
    #myCarousel> .carousel-inner > .carousel-item > img {
        object-fit: none;
        position:absolute;
        height:100%;
    }
    
    #myCarousel> .carousel-inner > .carousel-item > .carousel-caption {
        position: relative;
        right: auto;
        left: auto;
    }

    @media only screen and (max-width: 568px) {
        #myCarousel> .carousel-inner > .carousel-item > .carousel-caption {
            margin-bottom: 10%;
        }

        #myCarousel> .carousel-inner{
            overflow: visible;
        }
    }

**Comment by tmorehouse** [comment]
The caption position/CSS is dictated by Bootstrap V4's CSS.  Bootstrap-Vue is not setting any custom style or overriding their CSS.

See their repo at https://github.com/twbs/bootstrap/blob/v4-dev/scss/_carousel.scss#L184-L198

**Comment by patekuru** [comment]
@JackSteel97 Thank you that still seems useful in bootstrap-vue 2.1.
