### ISSUE TITLE
An error 'npm install'

### ISSUE THREAD

**Issue by xdenghui** [bootstrap-vue/bootstrap-vue#2152]
The project was downloaded, and the first "npm install" was executed in the root directory, with the error "Invalid dependency type requested: alias".
Version: "2.0.0 - rc. 11",

**Comment by xdenghui** [comment]
My node version: v10.13.0; and my npm version: 6.4.1

**Comment by xdenghui** [comment]
Does anyone have the same problem as me?

**Comment by aorinevo** [comment]
Hi @xdenghui,

I think this is related to https://github.com/bootstrap-vue/bootstrap-vue/issues/2158

To resolve the issue, I removed `vue-beta` and `vue-latest` from devDependencies.

**Comment by tmorehouse** [comment]
see #2158 for answer

**Comment by xdenghui** [comment]
That's great!Thank you @aorinevo.
I can delete these two terms, but why is that?

**Comment by tmorehouse** [comment]
or switch to `yarn` instead of `npm`

**Comment by xdenghui** [comment]
Thank you @tmorehouse.The problem has been bothering me for a long time.

**Comment by xdenghui** [comment]
Thank you @tmorehouse .The problem has been bothering me for a long time.
