### ISSUE TITLE
Form attribute

### ISSUE THREAD

**Issue by crashkonijn** [bootstrap-vue/bootstrap-vue#2154]
Hi there,

In our project we have to use the [input form attribute](https://www.impressivewebs.com/html5-form-attribute/) so we can be much more flexible with our HTML buildup. Unfortunately the form attribute isn't implemented and as such gets placed on the parent diff by vue instead of on the input element itself.

I've prepared a [JSFiddle](https://jsfiddle.net/bptLavov/440/) that should showcase the exact problem.

I did have a look at the core files of bootstrap vue to see if I could prepare a a PR to fix this, but I don't currently have the time to understand your core.

Anyway, awesome job on this project and thanks in advance!

**Comment by tmorehouse** [comment]
Thanks for pointing that out.  It looks like this issue only applies to checkbox, radios, form-file (in custom mode) (as they all have outer wrapper elements)
