### ISSUE TITLE
Load component inside <b-modal>

### ISSUE THREAD

**Issue by cielblog** [bootstrap-vue/bootstrap-vue#2155]
**Assalamualaikum,**
First of all my English is not that good, so I hope you can understand me.

I'm working on a dashboard for an application, and I'm trying to load a component inside a `<b-modal>`

This is my Modal:
```
<b-modal ref="actionModal" @ok="--- CHILD COMPONENT METHOD --">
                <template slot="modal-title">
                    <fa-icon v-if="actionModal.icon" :icon="actionModal.icon"></fa-icon>
                    {{ actionModal.title }}
                </template>
                <component v-bind:is="actionModal.component"></component>
</b-modal>
```

and this is how I call the Modal:
```
<b-button v-on:click="addPage()" variant="primary">{{ trans('title.create', {attribute: trans('title.new.page')}) }}</b-button>
```

**addPage()**
```            
addPage: function() {
     this.actionModal.component = PageAdd;
     this.actionModal.title = this.trans('title.new.page');
     this.actionModal.icon = 'plus-square';
     this.$refs.actionModal.show()
}
```

**data()**
```  
 actionModal: {
     title: null,
      icon: null,
      component: null
},
```

When I click the button the Modal is show and the component load. My problem is how to call a method that is inside a loaded component on `@ok=""`?

I tried with this:
```
<b-modal ref="actionModal" @ok="actionModal.component.onSubmit()">
```
but it didn't work.

**Comment by tmorehouse** [comment]
You need to set a `ref` on your component, and change your `ok` handler to use that reference.

```html
<component ref="modalcomponent" v-bind:is="actionModal.component"></component>

<b-modal ref="actionModal" @ok="$refs.modalcomponent.onSubmit()">
```

**Comment by cielblog** [comment]
> You need to set a `ref` on your component, and change your `ok` handler to use that reference.
> 
> ```
> <component ref="modalcomponent" v-bind:is="actionModal.component"></component>
> 
> <b-modal ref="actionModal" @ok="$refs.modalcomponent.onSubmit()">
> ```

Thank you ❤
