### ISSUE TITLE
b-form-input cursor changed on keypress

### ISSUE THREAD

**Issue by qkdreyer** [bootstrap-vue/bootstrap-vue#2157]
- Operating system and version : Mac OS X, iOS
- Browser and version : Safari 12.0.1, Safari for iOS
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15
  - Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1
- Version of Bootstrap-Vue that you are using : 2.0.0-rc.11
- Reduced test cases and potential fixes using : 
  - https://bootstrap-vue.js.org/docs/components/form-input/
  - http://g.recordit.co/3unVe7G3ce.gif

**Comment by tmorehouse** [comment]
Changed how?  Changed in color? changed in shape or size? Please include a description in the issue template.

I am guessing that you mean the cursor jumps position within the input?  If this is the case... this is a duplicate know issue.  Search the open/closed issues.

We have a fix for it in the latest `dev` branch.

**Comment by qkdreyer** [comment]
Indeed, this is a duplicate of #1951

**Comment by qkdreyer** [comment]
Can we hope to get a release for it soon ?

**Comment by shaneparsons** [comment]
How can I require the dev branch in my package.json? All attempts give me the following error: 

```
These dependencies were not found:

* bootstrap-vue/dist/bootstrap-vue.css in ./src/main.js
* bootstrap-vue in ./src/main.js
```

**Comment by tmorehouse** [comment]
You can follow along on our progress for the next release at issue #2173
