### ISSUE TITLE
Remove vue-beta and vue-latest from devDependencies?

### ISSUE THREAD

**Issue by aorinevo** [bootstrap-vue/bootstrap-vue#2158]
@tmorehouse, when running `npm install` off of dev branch, vue-beta and vue-latest fail to install.  To resolve the issue, I removed both from devDependencies.  

  - vue-beta
<img width="589" alt="screen shot 2018-11-09 at 9 38 12 am" src="https://user-images.githubusercontent.com/3240137/48268556-45b00b00-e403-11e8-838d-4607508c8ead.png">

  - vue-latest
<img width="586" alt="screen shot 2018-11-09 at 9 39 24 am" src="https://user-images.githubusercontent.com/3240137/48268590-64160680-e403-11e8-81da-f7a752f22088.png">

Is this expected?

# Notes
  - This came up while working on #2094

**Comment by tmorehouse** [comment]
`vue-beta` and `vue-latest` are use for the test suites. they run the tests against the latest release of Vue as well as the pending release candidate (dev branch) of Vue. @pi0 would know more about this setup then I would.

**Comment by aorinevo** [comment]
Looks like install works with `yarn` but not `npm`.

**Comment by tmorehouse** [comment]
interesting...

**Comment by aorinevo** [comment]
So looks like yarn supports this syntax but not npm. 

For more on yarn's on-demand aliasing see https://twitter.com/sebmck/status/873958247304232961?lang=en

Really cool feature!

**Comment by tmorehouse** [comment]
the dev branch is testing against two versions of vue (via circleci), and when dev is merged into master, these will probably be changes to test against the current vue release.

**Comment by jackmu95** [comment]
978e9877fc9010364479e5abca4f737b7b5294b8 should have resolved thi issue.
