### ISSUE TITLE
Adding tooltip into fields.label of <b-table>

### ISSUE THREAD

**Issue by lachezargrigorov** [bootstrap-vue/bootstrap-vue#2162]
Hi,
is it possible to add a tooltip on the labels of the tables's header ? 

```
fields: [
    {
        key: 'directive',
	label: '<span v-b-tooltip.hover title="tooltip as directive">directive</span>'
     },
{
        key: 'component',
	label: '<b-tooltip title="tooltip as component">component</span>'
     }]					
```

Nice day!

**Comment by tmorehouse** [comment]
label text supports only plain html (not components or directives).

use a scoped header slot to format your heading field(s) with markup and sub components.

**Comment by lachezargrigorov** [comment]
Nice, thank you!
