### ISSUE TITLE
Style borders in input validation not load default colors 

### ISSUE THREAD

**Issue by Atiladanvi** [bootstrap-vue/bootstrap-vue#2166]
See the image when the `state` property is `true`. That's right. but when you are going to render the form I need to get the edges with the main color of the entries. only after setting the value of state would you like to propagate the rendering of the borders. my suggestion for this is to be able to set state to `null` and ensure this behavior.
![image](https://user-images.githubusercontent.com/11599205/48423964-68faf300-e740-11e8-82bf-b3c46f386d81.png)
![image](https://user-images.githubusercontent.com/11599205/48424574-b4fa6780-e741-11e8-9d47-ea3128aea676.png)

The sugestion (`state = null`):

![image](https://user-images.githubusercontent.com/11599205/48424689-e2dfac00-e741-11e8-87ac-d3d68c946aba.png)

**Comment by tmorehouse** [comment]
state should default to `null`

states are -tri-state values:
- `null` no validation state rendered
- `true` (or the string `'valid'`) valid state rendered
- `false ` (or the string 'invalid`) invalid state rendered


Also note when input are rendered into a form, you may need to set `novalidate` on the form to prevent browser client side validation.

Could you provide markup as to your example?

**Comment by Atiladanvi** [comment]
Very well that works. I hope I do not take your time with trivial questions. li in documentation: state Boolean or String.

**Comment by tmorehouse** [comment]
Input should properly render with no validation state when `state=""`, fixed by PR #2166
