### ISSUE TITLE
Problems with popovers in tabs

### ISSUE THREAD

**Issue by milenon** [bootstrap-vue/bootstrap-vue#218]
I'm having issues when using popovers in tabs. Here is some code from the examples:

```
            <b-tabs>
                <b-tab title="first" active>
                    <b-popover placement="left">
                        <b-button variant="primary">Using slots</b-button>
                        <span slot="content">
                            Embedding content <span
                            style="color: red">using slots</span> affords you <em>greater <strong>control.</strong></em>
                        </span>
                    </b-popover>
                </b-tab>
                <b-tab title="second" >
                    <b-popover content="Embedding content using properties is easier as well as simpler to make dynamic.">
                        <b-button variant="primary">Using properties</b-button>
                    </b-popover>
                </b-tab>
                <b-tab title="disabled" disabled>
                    <b-card>I'm the card in tab</b-card>
                </b-tab>
            </b-tabs>
```

... and some steps for reproducing the problems I've noticed:
1. Load the page( First tab should be opened with button 'Using slots') 
2. Go to Second tab 
3. Click the Using properties button -> It is changed to 'Using slots' and the tab is switched to First tab
4. It no longer possible closing the popover by clicking on the page

**Comment by SirLamer** [comment]
Thanks, I'll look in to this.

**Comment by pi0** [comment]
@milenon I think this issue is partially related to #220 which is resolved.

**Comment by milenon** [comment]
@SirLamer Thanks for fixing it but I can't test it because now the dynamic tab adding(using + button) is not working:
https://bootstrap-vue.github.io/docs/components/tabs/

**Comment by SirLamer** [comment]
I think the implementation use here https://github.com/bootstrap-vue/bootstrap-vue/commit/4692c57b52c161e8b8b6b7498563df105d62f982 will make all Popover hides whenever any one tab changes. What if the popover is not inside the tab being hidden? Same with hide::modal - if the popover is in the background and not inside the modal, it will still hide.

I think there must be a lifecycle hook for show/hide of the component which I am trying to learn about. I feel like this should be grade 1 VueJS newbie stuff but I haven't faced this yet, so anyone let me know if they have a tip on how to hook the component just be removed from the rendered space in a general way.

**Comment by mosinve** [comment]
https://vuejs.org/v2/api/#vm-destroy
there's a note: 

> In normal use cases you shouldn’t have to call this method yourself. Prefer controlling the lifecycle of child components in a data-driven fashion using v-if and v-for.

So, I'm afraid this is only way in API to control rendering of component, the other way, i think, maybe, to define  own render function

**Comment by mosinve** [comment]
@milenon , really, tab interactivity broken somehow... :(

**Comment by SirLamer** [comment]
I think tabs get stuck in an infinite loop due to a recent change, I have to go get some sleep now but I might look in to it more tomorrow if @pi0 doesn't figure it out first.

As a hint, I was looking it to hook beforeUpdate and Update in Popover to react to being hidden, and found that before methods keep getting called in a loop, I THINK in reaction to something from the Tab enclosing it.

**Comment by pi0** [comment]
Problem is resolved by 40bc4f854e7f5c315cf8488233e17d47f71e38cc :) (#222)

**Comment by SirLamer** [comment]
Yeah that's the code I was going to target myself, good catch.

**Comment by SirLamer** [comment]
So I did some digging... reactivity is best affected in the "updated()" reactivity event in VueJS components. This is called every time the DOM is updated in any context which concerns your component. So.... when this is called, I just refresh the Tether position, which will cause itself to hide if the anchored element is not in the viewport.

I think this means that in the background the reposition call gets spammed whenever anything is happening like a page scroll and the Popover is shown, but... the cost for that is small, and this provides a universal solution for all cases.

See: https://github.com/bootstrap-vue/bootstrap-vue/pull/230
