### ISSUE TITLE
Activate Tab Programmatically

### ISSUE THREAD

**Issue by dsanders11** [bootstrap-vue/bootstrap-vue#2180]
Would be useful to be able to activate tabs programmatically. While there is [an example in the docs](https://bootstrap-vue.js.org/docs/components/tabs/#advanced-examples) of using `v-model` to change the active tab, this requires keeping track of the tab index, which makes it fragile. A nicer way would be a method on the `b-tab` component that can activate the tab:

```javascript
<b-tab ref="myTab" />

this.$refs.myTab.activate()
```

I have a quick and dirty implementation (e076e9ae8ccbe8ee31a1f8640e0d1e0e75fcb23b) for my own needs. `activate` was chosen over `show` as tab has `show` as a data key, so the method name would clash.

**Comment by garyzoar** [comment]
Yes this is badly needed as a popup in a tab does not close nicely as the popup gets destroyed to soon and glitches at the top left of the screen and does not play nicely.
