### ISSUE TITLE
 [b-radio-input] [suggestion] Expected checked to be a boolean property

### ISSUE THREAD

**Issue by kawazoe** [bootstrap-vue/bootstrap-vue#2182]
# Component
```
<template>
  <b-form-radio :value="42" name="foo" checked></b-form-radio>
</template>

<script>
export default {
  name: 'test',
};
</script>
```

# Expected
The radio button is checked.

# Actual
The radio button will only be checked if the `checked` property is set to the radio button's value: `checked="42"`.

# Notes
While this is probably caused by a naive implementation (forwarding the group value directly to the radios itself), to me, this behavior doesn't really make sense. I expected the checked property to behave like the native input element. This behavior is perfectly appropriate on a radio button group, though. I just think that the abstraction here could be better. If the event that this behavior is kept, it should be mentioned in the docs.

# Additional Info
- Operating System: Windows 10 (1803)
- Browser: Chrome (69)
- Bootstrap-Vue version: 4.1.3

**Comment by tmorehouse** [comment]
the big issue is that only one radio can be checked at a time when they are bound to the same v-model.

Will investigate some more to see what can be done

**Comment by tmorehouse** [comment]
one thing to note as well, in Vue with standard radios and checks and selects:

https://vuejs.org/v2/guide/forms.html#Basic-Usage
> `v-model` will ignore the initial `value`, `checked` or `selected` attributes found on any form elements. It will always treat the Vue instance data as the source of truth. You should declare the initial value on the JavaScript side, inside the data option of your component.

**Comment by tmorehouse** [comment]
The prop `checked` is the `v-model` prop tied to the inner value (either the checked or unchecked values).

So setting it to some other value that either the `value` (checked value) or `unchecked-valued` will result in the checkbox being in an undefined state.

To have a checkbox pre-checked, you must set the v-model (the `checked` prop) to the same value as the `value` prop.
