### ISSUE TITLE
Use b-dropdown-item-button for b-dropdown-item if no href provided

### ISSUE THREAD

**Issue by psimyn** [bootstrap-vue/bootstrap-vue#2185]
When no href is given to `<b-dropdown-item />`, it defaults to `href="#"`. These fake links are usually better represented as buttons with click handlers.

To match the behavior of [Button Element Type](https://bootstrap-vue.js.org/docs/components/button#button-element-type), it'd be good to detect tag type and set the component automatically. If `href` or `to` is provided, render `<a>` tag, otherwise render `<button>`.

**Comment by tmorehouse** [comment]
The styling between the two (button vs link) is slightly different (focus styles, etc), as well as how they are presented to assistive technology users (ARIA). 

Although this might be something we could consider in a near future release.

**Comment by jackmu95** [comment]
@tmorehouse I don't think we should/need to implement this. As you said above they are two different things.

When someone really needs this it's quite easy to build a component wrapper that does that.
