### ISSUE TITLE
auto place <b-pagination> after <b-tabel> using pagination=true

### ISSUE THREAD

**Issue by xxyyzz2050** [bootstrap-vue/bootstrap-vue#2186]
we use pagination data (ex: curreptPage , per-page ,...) in <b-table>, then we use the same data aain to create a <b-pagination> component
so I suggest to set pagination="true" prop in <b-tabel> to autocratically use the pagination data to create a <b-pagination> after the tabel

**Comment by tmorehouse** [comment]
the only issue with that, ks some people might like it at the top, some at the bottom, some both, and then some may want to center or right align, or control size, etc.. it brings way too many options on the table, and would complicate the already enormous code base we already have for b-table.

I would suggest making a simple wrapper  component using a render function that generates both the table an pagination, and pass all children to b-table (which includes slots)

**Comment by xxyyzz2050** [comment]
we can use pagination="top" or pagination="{options}"
if some one like to custom the pagination component so he can simply set pagination="false"

**Comment by tmorehouse** [comment]
one (i.e. myself, or one of the other team members) woukd still need to handle the comlex option parting when passed an object. the interface for the user would be somewhat simple, but for coding the actual paginator styles/positioning/alignment/etc would bloat the code to even more than it is today.

I would classify this as a low priority feature request, which can currently be solved using a wrapper component, designed with the users requirements in mind.

**Comment by auaa** [comment]
> the only issue with that, ks some people might like it at the top, some at the bottom, some both, and then some may want to center or right align, or control size, etc.. it brings way too many options on the table, and would complicate the already enormous code base we already have for b-table.
> 
> I would suggest making a simple wrapper component using a render function that generates both the table an pagination, and pass all children to b-table (which includes slots)

hi,can you provide an exmple for wrapper component?
i try more ways,but i cannot pass slots to `b-table`
