### ISSUE TITLE
[b-form-input] type="number" not allowing starting with negative (minus sign)

### ISSUE THREAD

**Issue by akhchan99** [bootstrap-vue/bootstrap-vue#2189]
version v2.0.0-rc.11

the input with type number doesn't allow the first character to be - (minus sign), if I want to enter -3 
(negative 3), i have to first enter 3, then move my mouse to the front then enter the "-" sign.

can test in input type section in https://bootstrap-vue.js.org/docs/components/form-input

**Comment by tmorehouse** [comment]
know issue with rc11. this should be fixed in the dev branch.

**Comment by tmorehouse** [comment]
related to #2061

**Comment by tmorehouse** [comment]
fixed in the latest `dev` branch
