### ISSUE TITLE
[Feature request] Popover 'disabled' prop to conditionally hide a popover without hiding its nested element

### ISSUE THREAD

**Issue by ronjouch** [bootstrap-vue/bootstrap-vue#219]
In [regular Bootstrap](https://v4-alpha.getbootstrap.com/components/popovers/), you *enable* popovers on elements:

```js
$(function () {
  $('[data-toggle="popover"]').popover()
})
```

In [bootstrap-vue](https://bootstrap-vue.github.io/docs/components/popover), you wrap a popover around an element:

```html
<b-popover content="Please enter name">
  <b-btn>Submit</b-btn>
</b-popover>
```

This feels great and natural, but looking at the docs I couldn't find a way to conditionally disable the popover without hiding the nested element. In the example above, suppose I `v-if="!formValid"` my popover. When `!formValid`, I get my button and popover, but when `formValid` my `<b-btn>` becomes hidden too.

Any workaround? Am I missing something?

**Comment by pi0** [comment]
@ronjouch Hi. For having the ability to conditionally disable popover (the parent) we may need a `disabled` prop.

**Comment by ronjouch** [comment]
> For having the ability to conditionally disable popover (the parent) we may need a disabled prop.

@pi0 would be 👍. Thanks for the fast feedback :)

**Comment by SirLamer** [comment]
You can also disable the built in triggers and then control the show/hide action with your own external logic which is watching the events, however a 'disabled' prop is not a big ask.

Disabled=true will make it hide, as opposed to freezing it in its current state, agreed?

**Comment by ronjouch** [comment]
> `disabled=true` will make it hide, as opposed to freezing it in its current state, agreed?

@SirLamer agreed, maybe `disabled` isn't a good name. `hidden` ?

**Comment by SirLamer** [comment]
...oh yeah, there is already a property "show" which shows it when true. I will revise that so that "false" forces it to hide, and "null" is its neutral state.

**Comment by SirLamer** [comment]
See: https://github.com/bootstrap-vue/bootstrap-vue/pull/230
