### ISSUE TITLE
 feat(modal): Close all modals at once (do it in the same way as popover does)

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#2191]
About Modals from the doc:
> You can emit ... bv::hide::modal event on $root with the first argument set to the modal's id.

Example:
> this.$root.$emit('bv::hide::modal','modal1')
----
About Popover from the doc:
> You can close (hide) all open popovers by emitting the bv::hide::popover event on $root

Example:
> this.$root.$emit('bv::hide::popover')
----
So the feature request is to add ability to use just `this.$root.$emit('bv::hide::modal')` (i.e. without modal's id) in order to close all modals.

This feature will be useful regarding this [PR#2164](https://github.com/bootstrap-vue/bootstrap-vue/pull/2164).

**Comment by tmorehouse** [comment]
I've got to make a few changes for PR #2164 (there is an issue with multiple modals and the enforce focus handler).

I'll see what we can do for this (although it still may be possible for some other handler who is hooked on a particular modal to cancel a hide.

**Comment by tmorehouse** [comment]
PR #2259 introduces an option to make a modal non-stackable, meaning if another modal opens, then the non-stackable modal will close first before the other modals open.

I'm a bit leary on allowing anyone close all open modals, specifically if there are 3rd party widgets that use modal as a base (i.e. date-pickers), etc.

**Comment by TitanFighter** [comment]
> I'm a bit leary on allowing anyone close all open modals, specifically if there are 3rd party widgets that use modal as a base (i.e. date-pickers), etc.

Regarding your fear... the simplest solution can be to add a new prop `forceClosable` or `globalEventClosable` or something like that. If a date-picker emits `this.$root.$emit('bv::hide::modal')` and closes a modal and our dev does not like it, he/she simply can add `:forceClosable="false"` to the modal.

In short, I prefer to give/have an option. How this option can be used - no one can predict. Another story - when there is no option at all :)

**Comment by jackmu95** [comment]
The `<b-modal>` logic is already too complex to allow this kind of feature.

**Comment by akhoury** [comment]
@TitanFighter a bit late to the party, but i ran into this today and wanted to close all modals no matter what when the route is changed...


```javascript
Array.from(window.document.querySelectorAll('.modal.show'))
    .map(el => el.id)
    .forEach((id) => {
        this.$root.$emit('bv::hide::modal', id)
    })
```
