### ISSUE TITLE
Add a note in the documentation that this package doesn't automatically "load" the bootstrap4 css

### ISSUE THREAD

**Issue by raff** [bootstrap-vue/bootstrap-vue#22]
Was going crazy trying to figure out why nothing was styled, until I realize I had to manually link/include Bootstrap 4.

It would be good if there was a note in the documentation and maybe an example of a small working app.

**Comment by fusiwei339** [comment]
Agree! It's necessary for layman like me.

**Comment by batdevis** [comment]
@raff could you write an example?
How do you link/include the css?

**Comment by pi0** [comment]
The reason why bootstrap is not included in dist package, is bootstrap 4 has many variants and bundling forces anyone to use some specific one.  There are two possible ways:

- Simple download and including bootstrap 4 in your page's html or css bundle using webpack/grunt/gulp ..
- Enabling webpack css loader and including like this:
```js 
import 'path/to/node_modules/dist/css/bootstrap.css'
// OR
import 'path/to/node_modules/dist/css/bootstrap-flex.css'
```
(bootstrap package should be installed using `npm install --save-dev bootstrap@@4.0.0-alpha.5` or `yarn add --dev bootstrap@4.0.0-alpha.5`

Any volunteer to documents that steps ins docs?
