### ISSUE TITLE
b-form-file input does not updating if I delete the file.

### ISSUE THREAD

**Issue by GergelyLakatos** [bootstrap-vue/bootstrap-vue#2200]
OP: Opensuse, Linux
Browser1: Chromium: Version 70.0.3538.67 (openSUSE Build) (64-bit)
Browser2: Firefox: Version 60.0.3 (64-bit)
bootstrap-vue: 2.0.0-rc.11

The problem is, when I want to upload a file with `b-form-file` its works well, however I made a function what sets the file `null`, if its size bigger then 100 Mb. The file variable changes everytime to null, but the name of the file remains (in the input field). Its annoying, because the user thinks that file is still there, but its not.

**Comment by jackmu95** [comment]
Currently you have to reset the file input manually by calling the `reset()` method on the inputs reference. This behavior changes in the next release.

For now take a look at the "Clearing the file selection" section [here](https://bootstrap-vue.js.org/docs/components/form-file).

**Comment by tmorehouse** [comment]
Not all browsers support setting a file inputs value (some let you set it to `''` to clear it, others fail and throw an error).

PR #2170 fixes this, and allows you to set the v-model to `null` or an empty string (or empty array for multiple mode), and is available in the `dev` branch.
