### ISSUE TITLE
feat(jumbotron): suport background image property Jumbotron

### ISSUE THREAD

**Issue by Paperasse** [bootstrap-vue/bootstrap-vue#2208]
Add a property on Jumbotron for a link to a background image. I.e.: a link from a headless CMS entry.

**Comment by Paperasse** [comment]
I don't a way to insert a value from the data object of Vue into the style definition. Do you? This works only if you have a 'static' link to an image.

**Comment by tmorehouse** [comment]
not off hand, 

well look into this and see if we can add support, althouhg it would require some additional trickery to get vue-loader to recognize the prop as an ing prop

**Comment by Paperasse** [comment]
Did some investigatng. Vuejs supports v-bind on style attribute. It should be possible to bind to  a computed property that returns a style string that is formatted with the image link from the data property. Going to try this as a work around. Let you know.

**Comment by Paperasse** [comment]
I'm thinking of something like this:

<b-jumbtron ... :style"imageStyle" ..>

imageStyle is a computed property that returns: "background-image: 'url("+ this.imgUrl + ")'"

**Comment by tmorehouse** [comment]
that will work if your image is a full url, and not part of your local app.

**Comment by jackmu95** [comment]
@tmorehouse IMHO using `:style={}` as with every other component is the goto solution here and it's not worth a custom implementation.

**Comment by tmorehouse** [comment]
Yeah.. I was just thinking about background placement options (like cover, fit, etc). Might add a bit of additional props, but one could place a style attribute directly on the component to place a background image (and set the background variant to transparent via the variant prop). we  use the prop name of style as it is a reserved attribute (but we could make a prop jumbotron-style).
