### ISSUE TITLE
Form Select Doesn't update as expected

### ISSUE THREAD

**Issue by ragingdave** [bootstrap-vue/bootstrap-vue#221]
Here is a jsfiddle example, where I tried to replicate as close as possible my situation:
https://jsfiddle.net/8yz8qbfj/4/

Here is the back story:
I supply an initial component with server provided data(`parent`), which then because modification of the obj will happen in the `parent`, it is copied to a local object (`obj_details`) ,which then an internal property is used to supply another child component (`child-component`), which is then passed in the end to the b-form-select whose options are provided by a promise (technically in mine axios get request), which isn't properly set once everything loads.

I'm wondering as I write this if this is the wrong approach or if this should actually be working.

UPDATE: corrected jsFiddle: https://jsfiddle.net/8yz8qbfj/7/

**Comment by pi0** [comment]
@ragingdave Would you please provide an example? (You can use playground and exporting to js fiddle)

**Comment by ragingdave** [comment]
@pi0 Added example JsFiddle with a bit of backstory in initial description

**Comment by ragingdave** [comment]
So I actually figured out what happened but I'm not clear on whether this is intended behavior or some bad by-product, or just my own stupid use case....but...
Moving the mounted logic into a created method (along with moving the logic that assigns the prop to a local data var into a computed setter instead of a watch function _because that's dumb in the first place_) allowed the lifecycle to be completed in the correct order where the v-models' all worked as expected. Below is the fixed example:
https://jsfiddle.net/8yz8qbfj/10/

Still not entirely sure why mounted wouldn't work instead of created though....

**Comment by mosinve** [comment]
Your first example doesn't work because you assign data `localValue: this.value,` at created step, and change value of reactive prop later at mounted step, so `localValue` in child-component doesn't recalculate.

**Comment by mosinve** [comment]
https://jsfiddle.net/Lstzr7f7/ here's your working example
