### ISSUE TITLE
b-nav-item-dropdown tab active state

### ISSUE THREAD

**Issue by vmihailenco** [bootstrap-vue/bootstrap-vue#2219]
I am using `b-nav(tabs)` and want to mark `b-nav-item-dropdown` as active/current tab, e.g.:

```pug
b-nav(tabs)
  b-nav-item(:to="{...}") // NOT active tab

  b-nav-item-dropdown(:active="true") // active tab
    template(slot="button-content")
      b-link(:to="{...}" :active="true") Active tab // active link
    b-dropdown-item(:to="{...}") One
    b-dropdown-item(:to="{...}") Two
    b-dropdown-item(:to="{...}") Three
```

It is possible to add support for `active` property? In my use case just applying `.active` class to the tab is enough. I already tried `b-nav-item-dropdown(class="active")` but it does not work...

**Comment by tmorehouse** [comment]
`nav-item-dropdown`, when rendered is inside an `<li>` element., so when adding a class it gets added to the `<li>` and not the `<a>`

We could see about adding a prop for `active`  on `nav-item-dropdown` that would apply the `.active` class to the inner `<a>` tag.

**Comment by tmorehouse** [comment]
You should be using `b-dropdown` in `split` mode, and set the split button `href`/`to` props (in the latest `dev` branch)

**Comment by tmorehouse** [comment]
You can set the global `linkActiveClass` in your vue-router (or nuxt) config (which is why we removed the default on the `active-class` prop, as the global setting was never applied).

**Comment by vmihailenco** [comment]
Thanks, linkActiveClass works.

Should I close this issue and open new issue for split mode in b-nav-item-dropdown? Or split mode will not be supported there?

**Comment by vmihailenco** [comment]
Thanks. Closing this issue since it looks like bootstrap-vue does everything that can be expected from it.
