### ISSUE TITLE
[Tabs] Interactive tabs adding fails

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#222]
Currently, tabs interactive adding doc example isn't work.

**Comment by pi0** [comment]
@mosinve  Thanks for report :) Bugs with tabs is resolved in new release (Please disable browser cache if not working:) )
Actually exact problem was with unnecessary $nextTick which is not happening anymore as child observation was improved :) (So update function was waiting for a new tick)
