### ISSUE TITLE
a big tooltip in b-table blinks

### ISSUE THREAD

**Issue by iruizeguilaz** [bootstrap-vue/bootstrap-vue#2226]
I use several tootltips in my tables. They seemed to work ok but I have realised that sometines, when the tooltip is big and it goes down more than the table size, it blinks constantly and it is imposible to see the tootltip...

I am using the last version of vue and boostrap.

the code of the tootltip 

```
  <template slot="title" slot-scope="data">
             <div v-b-tooltip.hover :title="data.item.description"> {{ data.item.title }} </div>
  </template>

```

I have also tested it with the tag em instaead of div

the definition of the tabla

```
  <b-table striped hover responsive
                              :current-page="table.currentPage"
                              :items="calculatedValues"
                              :per-page="table.perPage"
                              :fields="tableColumns"
                              :sort-desc.sync="table.sortDesc"
                              :sort-by.sync="table.sortBy">
```

thanks

**Comment by tmorehouse** [comment]
Is possible that something is causing your table data to be redrawn/repainted, which might cause the tooltip to disappear and reappear quickly?

Have you tried using the component version of tooltip instead of the directive version?

It also could be a Popper.js issue dealing with calculating the tooltip position in a deeply nested table.

Could you try adding the class `position-static` (or `position-relative`) to your `div` with the tooltip on it?

**Comment by iruizeguilaz** [comment]
I have another problem now, after changing to use the component.

The tooltip after filter or order is not update in relation of its target... in other words, the row is other after order but the tooltip that apperas is the tootltip which was in that row bofore order. despite the fact that every tootltip has a unique target (the column name + the id of the row....)

This issue I faced up with, when I used images in a column. But I was able to solve it by putting the images in a div with v-html tag.... then the images worked properly with the its row after ordering.... 

I have tryied to use v-html but for the moment, I see the tooltip in the html, but the tootlip does not work in this way... this trick does not work for tooltips

```
  <template slot="title" slot-scope="data">
div :id="'title' + data.item.idTicket" > {{ data.item.title }} </div>
 <div v-html="estiloTooltip(data.item.idTicket, acortar(data.item.description, 120), 'title')"> </div>
  </template>
```

```
estiloTooltip(id, value, target){
     return "<div><b-tooltip target='"+ target + id +"' title='" + value + "'>  </b-tooltip> </div>"
 }

```

is there any way to ensure that the new render of the table refresh the tootltip targets?

best regards

**Comment by iruizeguilaz** [comment]
I was able to solve the issue by using the first way and changin the position of the tooltip to the left, by this way, the mouse do not loose contact with the component that generates the tootilp, I think this was the problem.

Also by this way I do not have problems in ordering...

```
 <template slot="title" slot-scope="data">
               
        <div  container="body"  v-b-tooltip.html.right :title="acortar(data.item.description, 120)" :id="'title' + data.item.idTicket" > {{ data.item.title }} </div>

 </template>
```

**Comment by tmorehouse** [comment]
The latest dev branch optimizes rendering (and caching paginates/sorted items), so this might also help, and when using the component version you might need to set a unique key on the component so that vue knows not to re-render the component.

**Comment by iruizeguilaz** [comment]
Hi

what do you mean with a unique key on the component?

I put `:id="'title' + data.item.idTicket"` that is unique for that div por each row

is it better for the performance to do this for every cell of the table? because I do not have ids in every column/row...

**Comment by tmorehouse** [comment]
I was thinking of maybe just expand a key you have to place on the b-tooltip, using the `:key="..."` Vue attribute (i.e. `:key="rowIndex + '-tooltip'"`)

**Comment by tmorehouse** [comment]
Have you tried setting the `boundary` prop/option to `window`?

For the component version, set `boundary="window"`, and for the directive option, you can pass the boundary via the directive value `v-b-tooltip.hover="{ boundary: 'window' }"`.

See similar issue at https://github.com/twbs/bootstrap/issues/27965

**Comment by iruizeguilaz** [comment]
ok, thanks for the advice fopr the future but as I said in a previous comment I could handled the problem by using v-b-tooltip.html.right --> in this way the tooltip does not blinck.
It is ok right now in my production environtment so I prefer not chaging anything that is working :) Maybe I should have clossed this post when I put that comment, should't I?
