### ISSUE TITLE
Limited table fields

### ISSUE THREAD

**Issue by moracabanas** [bootstrap-vue/bootstrap-vue#2228]
When I use more than 9 fields or just their labels on a table they stop to be shown at 9th. So if I have 12 fields I can only see 9 of them.

Operating system - Mac OS X
Browser and version - Chrome
Version of Bootstrap-Vue - Latest

**Comment by moracabanas** [comment]
I did some checks and it seems that if the field has empty data it is not shown so, it is working as intended but you probably want some empty fields to see how is the layout. I suggest to fill that field with an empty array of data otherwise it won't be shown at all.

**Comment by tmorehouse** [comment]
Could you provide a sample of your fields definition and a sample of the first row of data?
