### ISSUE TITLE
[b-form-group] Probably unneeded horizontal column calculation 

### ISSUE THREAD

**Issue by rafasirotheau** [bootstrap-vue/bootstrap-vue#2230]
Hello,

There's this computed property:
```
inputLayoutClasses () {
  return [
    this.horizontal ? `col-${this.breakpoint}-${12 - Number(this.labelCols)}` : null,
    this.tooltip ? 'position-relative' : null
  ]
}
```

Is there any reason for this subtraction (`${12 - Number(this.labelCols)}`) to exist?

Since there is no property to customize this value and it will always occupy the remaining space, why not simply use `col`?

It should also solve the problem of users (my case) who are using a custom bootstrap with `$grid-column` other than 12.

**Comment by tmorehouse** [comment]
Yeah, I think this was a leftover from the beta version of Bootstrap V4.

It definitely could be left as just class `col`

Although I think we need to revamp this component to allow setting the width of the label for each breakpoint, by adding breakpoint props (label-sm, label-md, label-lg, and label-xl) to allow for more complex responsive layouts.
