### ISSUE TITLE
Standalone checkboxes/radios are always inline by default

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#2234]
Currently standalone `<b-form-checkbox>` and `<b-form-radio>` inputs are always inline by default. There is also no way ti change this by a property. The only way to get stacked inputs is to warp a group around them and set the `stacked` property to `true`.

My suggestion would be to add a `inline` property to the `<b-form-checkbox>` and `<b-form-radio>` components and set it to`false` by default. When the component detects it's inside a group it could look for the `stacked` property and set the inline class depending on that.

**Comment by tmorehouse** [comment]
I was just in the middle of revamping checkbox/radios to use provide/inject for better nesting inside check/radio groups (and the layout structure in BS V4.1 is a bit different than in V4.0, which is being updated)

So you might want to wait until I push those changes.

**Comment by jackmu95** [comment]
@tmorehouse I was expecting that - Good for me that I've created an issue and havn't submitted PR in the first place :D

**Comment by tmorehouse** [comment]
Heheh,

I'll definitely want you to eyeball the PR over before it gets merged.
