### ISSUE TITLE
[modal] modal is hidden with scrollable content on IE11

### ISSUE THREAD

**Issue by 4dn-oss** [bootstrap-vue/bootstrap-vue#2235]
On IE11, modal written before scrollable element is hidden with the scrollable content.
It is reproducible only with current `dev` branch.

## Example

```
  <div id="app">
    <b-modal ref="modal1">modal-1</b-modal>
    <div style="height:100px;overflow-y:auto;">
      <div style="background-color:yellow;height:600px;">content</div>
    </div>
    <b-modal ref="modal2">modal-2</b-modal>
    <b-button @click="$refs.modal1.show()">show modal-1</b-button>
    <b-button @click="$refs.modal2.show()">show modal-2</b-button>
  </div>
```

'modal-1' is shown on click 'show modal-1' button, but is hidden with 'content'.
'modal-2' is shown on click 'show modal-2' button, and is not hidden.
![bv-modal-issue-20181129](https://user-images.githubusercontent.com/4657547/49207442-459a9e00-f3f8-11e8-8423-36cc64ae7585.gif)

## Environment

OS: Windows 10 (1803)
Browser: IE11 (11.407.17134.0)
Bootstrap-Vue: HEAD of `dev` branch (8b8272bad45585389989064aa11e1fd622237493)

It does not reproduce with Firefox (63.0.3), Edge (42.17134.1.0), Chrome (70.0.3538.110).
It does not reproduce with Bootstrap-Vue 2.0.0-rc.11.
It does not reproduce on playground of `dev` build.

## Workaround

Writing all modals at the end of the content maybe avoid this issue.

**Comment by 4dn-oss** [comment]
> Writing all modals at the end of the content maybe avoid this issue.

The workaround not working on my app...
There might not be a reliable workaround.

**Comment by tmorehouse** [comment]
Try adding a position to your scrollable div (i.e. `position: relative;`), and see if that helps

**Comment by 4dn-oss** [comment]
Thanks for your advice. `position: relative;` works for the example above. But the issue recured when resizing the window with modal opened.

And I found that by placing the scrollable component inside the `b-container`, workarounds lose effect. My app fall under this condition. See example below.

## Example-2
```
<div id="app" style="position:relative">
  <b-modal ref="modal1">modal-1</b-modal>
  <b-container>
    <b-row>
      <b-col>
        <b-modal ref="modal2">modal-2</b-modal>
        <div style="height:100px;overflow-y:auto;">
          <div style="background-color:yellow;height:600px;position:relative">
            content
          </div>
        </div>
        <b-modal ref="modal3">modal-3</b-modal>
      </b-col>
    </b-row>
  </b-container>
  <b-modal ref="modal4">modal-4</b-modal>
  <b-button @click="$refs.modal1.show()">show modal-1</b-button>
  <b-button @click="$refs.modal2.show()">show modal-2</b-button>
  <b-button @click="$refs.modal3.show()">show modal-3</b-button>
  <b-button @click="$refs.modal4.show()">show modal-4</b-button>
</div>
```
Except for 'modal-3', all modals are hidden with 'content'.
On bootstrap-vue 2.0.0-rc.11, no modal is hidden.

**Comment by 4dn-oss** [comment]
I found that adding `position: relative` and `z-index: -1` to the scrollable content element avoid this issue (`z-index: 0` has no effect). But `z-index: -1` cause elements inside the content to stop accepting mouse events.

So, I tried to write `z-index: -1` into `body.modal-open .foo` selector. However, under certain conditions, `modal-open` class remains despite the modal has closed. See #2236.

**Comment by tmorehouse** [comment]
@4dn-oss could you try the following and see if it helps with the scrollable content overlap?

`<b-modal class="position-relative" ... >`

**Comment by 4dn-oss** [comment]
@tmorehouse The result of Example-2 + `class="position-relative"` as follows:
![bv-modal-issue-20181206](https://user-images.githubusercontent.com/4657547/49563915-2e623000-f965-11e8-87e0-08de745f5e1e.gif)
no effect: modal-1, modal-4
effective: modal-2
opposite effect: modal-3

**Comment by tmorehouse** [comment]
Interesting. 

One issue is that models should be placed after all other content as possible, although this is not always possible.

I'm looking into a way to move model content to be appended to the body, which may address this issue.

**Comment by tmorehouse** [comment]
@4dn-oss  There have been a few more tweaks to modal in the latest `dev` branch. Could you try another go-around on your tests?

**Comment by tmorehouse** [comment]
Just wondering if you placed your example inside the following (which would sort of mimic mimic the playground):

```html
<div class="container">
  <div class="row">
    <div class="col-12">
      <!-- place example text code here -->
    </div>
  </div>
</div>
```

Basically this would place your content inside a flex container

**Comment by 4dn-oss** [comment]
@tmorehouse
without `position: relative` workaround?

**Comment by tmorehouse** [comment]
yeah

**Comment by 4dn-oss** [comment]
## Example-1-A
```
<div id="app">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <b-modal ref="modal1">modal-1</b-modal>
        <div style="height:100px;overflow-y:auto;">
          <div style="background-color:yellow;height:600px;">content</div>
        </div>
        <b-modal ref="modal2">modal-2</b-modal>
        <b-button @click="$refs.modal1.show()">show modal-1</b-button>
        <b-button @click="$refs.modal2.show()">show modal-2</b-button>
      </div>
    </div>
  </div>    
</div>
```
modal-1: hidden with 'content'
modal-2: fine

## Exampel-2-A

```
<div id="app">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <b-modal ref="modal1">modal-1</b-modal>
        <b-container>
          <b-row>
            <b-col>
              <b-modal ref="modal2">modal-2</b-modal>
              <div style="height:100px;overflow-y:auto;">
                <div style="background-color:yellow;height:600px;">
                  content
                </div>
              </div>
              <b-modal ref="modal3">modal-3</b-modal>
            </b-col>
          </b-row>
        </b-container>
        <b-modal ref="modal4">modal-4</b-modal>
        <b-button @click="$refs.modal1.show()">show modal-1</b-button>
        <b-button @click="$refs.modal2.show()">show modal-2</b-button>
        <b-button @click="$refs.modal3.show()">show modal-3</b-button>
        <b-button @click="$refs.modal4.show()">show modal-4</b-button>
      </div>
    </div>
  </div>    
</div>
```
modal-1, modal-2, modal-4: hidden with 'content'
modal-3: fine

**Comment by 4dn-oss** [comment]
Yes. But... See this.
![bv-modal-issue-20181212](https://user-images.githubusercontent.com/4657547/49849298-38c87200-fe1c-11e8-9692-bced09c5f7ca.gif)
By resizing the window, the 'Template' area overlaps the 'modal-2'.

**Comment by tmorehouse** [comment]
Not that is weird. Not sure what that black bottom box is.

**Comment by tmorehouse** [comment]
Oh, that is the bottom border of the browser window... but still strange

**Comment by 4dn-oss** [comment]
mmm...
My IE11(11.407.17134.0 and 11.547.16299.0) reproduce that issue on your site.
Since there is no newer version of IE 11 now, I will get it later and confirm.

**Comment by tmorehouse** [comment]
Do you have any addons/plugins in your IE?

**Comment by 4dn-oss** [comment]
No addons/plugins in my IE.

**Comment by 4dn-oss** [comment]
11.547.16299.0: no addons/plugins.
11.407.17134.0: SnapCrab, Java plugin and Skype for Business Browser Helper (all disabled)

**Comment by 4dn-oss** [comment]
I tested playground and examples on IE11 of Windows 10 October 2018 Update (ver. 11.194.17763).
All the tests reproduce reported issues.

**Comment by tmorehouse** [comment]
@4dn-oss release v2.0.0-rc.14 was just published tonight.

Could you see if the issue still persists?

**Comment by 4dn-oss** [comment]
Sorry. I can not check it because I’m out of the office until Monday.

**Comment by 4dn-oss** [comment]
bootstrap-vue v2.0.0-rc.14 & IE11(11.590.17134.0)
```
  <div id="app">
    <h1>2.0.0-rc.14</h1>
    <b-modal ref="modal1">modal-1</b-modal>
    <b-container>
      <b-row>
        <b-col>
          <b-modal ref="modal2">modal-2</b-modal>
          <div style="height:100px;overflow-y:auto;">
            <div style="background-color:yellow;height:600px;">
              content
            </div>
          </div>
          <b-modal ref="modal3">modal-3</b-modal>
        </b-col>
      </b-row>
    </b-container>
    <b-modal ref="modal4">modal-4</b-modal>
    <b-button @click="$refs.modal1.show()">show modal-1</b-button>
    <b-button @click="$refs.modal2.show()">show modal-2</b-button>
    <b-button @click="$refs.modal3.show()">show modal-3</b-button>
    <b-button @click="$refs.modal4.show()">show modal-4</b-button>
  </div>
```
modal-1, modal-2, modal-3, modal-4: fine
This issue seems to be solved.

**Comment by tmorehouse** [comment]
Excellent.
