### ISSUE TITLE
b-form-select has not focus method

### ISSUE THREAD

**Issue by nvacca07** [bootstrap-vue/bootstrap-vue#2237]
b-form-select focus not works
b-form-select has not focus method
TypeError: _vm.$refs.inputReference.focus is not a function

b-form-input focus works

**Comment by tmorehouse** [comment]
Which version of Bootstrap-Vue are you using (2.0.0.-rc.11 or `dev` branch)?

**Comment by nvacca07** [comment]
I am using "bootstrap-vue": "^2.0.0-rc.11"

**Comment by tmorehouse** [comment]
We should be able to add a `.focus()` and `.blur()` methods to `b-form-select`.

To get around this, you can do the following, assuming `inputSelect` is your ref to the `b-form-select` component:

```js
this.$refs.inputSelect.$el.focus()
```

**Comment by nvacca07** [comment]
thanks you
