### ISSUE TITLE
<b-table> fields has a `tdAttr` but no `thAttr`

### ISSUE THREAD

**Issue by runxc1** [bootstrap-vue/bootstrap-vue#2244]
The b-table component has a a way to add custom properties to each table cell (td) but there is no way to add custom properties to the table header (th).   Seems like an oversight as most other properties on the Fields list have a th and td variant.

**Comment by tmorehouse** [comment]
Re you referring to the `th` elements in the table `head`, or in the `body` section of the table (i.e. row headers)?

**Comment by runxc1** [comment]
So I am talking about the table head.  Which I believe is where the only th elements are rendered inside the component. 

In the table Field reference there are the following fields tdClass, thClass, thStyle, tdAttr (https://bootstrap-vue.js.org/docs/components/table)

What is missing is a thAttr Field that would easily allow you to add an arbitrary attribute.   Seems that most of the plumbing is already done.

**Comment by tmorehouse** [comment]
`tbody` also supports cells being rendered as `th` (a row header) instead of `td`

**Comment by runxc1** [comment]
I didn't think the component supported that but yeah its the column headers in the thead that I was referring to.

**Comment by tmorehouse** [comment]
Well see about getting it added in a near future release.
