### ISSUE TITLE
<b-card>: "Tag" is displayed without escape in header, titlle and footer.

### ISSUE THREAD

**Issue by howmuch515** [bootstrap-vue/bootstrap-vue#2245]
Hello,

"Tag" is displayed without escape in b-card's header, titlle and footer.
"script-tag" is rejected. But "img-tag" can cause alert.
Is this correct specification?

```
OS: macOS Mojave 10.14.1
vue: 2.5.17
nuxt: 2.3.4
bootstrap-vue: vue-2.0.0-rc.11
```

```html
<template>
    <b-card :header="text1"
            :title="text1"
            :footer="text1">
        <h1>{{ text1 }}</h1>
        <b-form-input v-model="text1"></b-form-input>
    </b-card>
</template>

<script>
export default {
    data: function() {
        return {
            text1: 'hoge'
        }
    }
}
</script>
```

![b-vue_xss](https://user-images.githubusercontent.com/10630083/49448612-a1ac5a80-f81c-11e8-8e91-ff2f1f118d6e.gif)

**Comment by tmorehouse** [comment]
The props for title, header, etc, support basic HTML for things like simple styling. It is up to you as the author of an app to determine what fields you will allow to contain user data.

**Comment by 4dn-oss** [comment]
I think developers who need styling should use slot rather than property.

In the current specification, when using `b-card` in a reusable component, we must always escape the value to set to the property such as `title` etc. Otherwise the component has an XSS vulnerability.

Are there components other than `b-card` that have similar specifications? If so, I think that it is necessary to specify them in the document.

However, I think that it is desirable to treat all property values as plain text.

**Comment by 4dn-oss** [comment]
HTML tags are available for the following properties:

|  component        |  properties  |
|  ---------        |  ----------  |
|b-card             | `header`, `title`, `sub-title`, `footer` |
|b-carousel         | `caption`, `text` |
|b-checkbox-group   | `text` of `options` array element |
|b-form-group       | `label`, `description`, `feedback`, `valid-feedback`, `invalid-feedback` |
|b-form-radio-group | `text` of `options` array element |
|b-input-group      | `prepend`, `append` |
|b-navitem-dropdown | `text` |
|b-pagenation       | `first-text`, `prev-text`, `ellipsis-text`, `next-text`, `last-text`|
|b-pagination-nav   | `first-text`, `prev-text`, `ellipsis-text`, `next-text`, `last-text`, return value of `page-gen`'s function |
|b-table            | `caption`, `empty-text`, `empty-filtered-text`, `label` of `fields` array element |

HTML tags are <b>not</b> available for the following properties:

|  component        |  properties  |
|  ---------        |  ----------  |
|b-dropdown         | `text`       |
|b-form-file        | `placeholder`|
|b-form-input       | `placeholder`|
|b-form-select      | `text` of `options` array element |
|b-form-textarea    | `placeholder` |
|b-jumbotron        | `header`, `lead` |
|b-modal            | `title`, `ok-title`, `cancel-title` |
|b-popover          | `title`, `content` |
|b-table            | key and value of `items` arrey elemnt |
|b-tab              | `title` |
|b-tooltip          | `title` |

I have examined all the way, but there may be some missing.

**Comment by howmuch515** [comment]
Thank you for your research!

**Comment by tmorehouse** [comment]
I would prefer styled html to be used in slots only, but we har many requests to be able to pass basic html to the props.

Removing this "feature" would be a breaking change for many users though.

**Comment by tmorehouse** [comment]
`b-form-group` no longer accepts HTML for the props.

**Comment by tmorehouse** [comment]
For things like `b-form-select`, `b-form-radio-group` and `b-form-checkbox-group`, the option to use HTML in the `options` array is important to many users.   What we could do for those three components is default to rendering the option text as text, and then add an option to the component to enable rendering the text as html instead (i.e. an `options-html` boolean prop).

**Comment by jackmu95** [comment]
What about using a prop like `html` or `content` in `option` in the array to enable HTML and default to plain text for the `text` prop?

**Comment by tmorehouse** [comment]
Yeah, the options mixin could be updated to accept an html property, and if present, is used as inner html, and the plain text can be passed direct to create element as the content.

**Comment by tmorehouse** [comment]
There are a few npm modules that can sanitize html strings, but they are rather large in size, and many still have loopholes.

**Comment by jackmu95** [comment]
I think it is enough to give the user better control over this.

Default to the safe `text` prop and give the option to use the `html` with a notice in the docs that by using this the content need to be sanitized by the users themselves.

**Comment by tmorehouse** [comment]
Yeah. And a few other components should have similar limitations as well for when inner html is used.

**Comment by 4dn-oss** [comment]
3c6ba3e44de425120990f671436a7b163742b5cb seems to fix this issue.
