### ISSUE TITLE
bootstrap table won't refresh if table is busy

### ISSUE THREAD

**Issue by runxc1** [bootstrap-vue/bootstrap-vue#2246]
In the documentation it states that the table won't call the provider if the table is manually put in the busy state but it looks like regardless of whether or not it is in the busy state or even if I manually set busy to false to refresh the provider I am unable to force a refresh of the table provider.  I am on Windows 10 using Chrome/Firefox.

My use case is this, when the page loads I am fetching some of the options and default values for the user.  The provider gets called before I can load these options and makes a request.  The options load and I call table.refresh but it always fails as the table is in a busy state.   I would like to be able to abandon the previous refresh and tried using a CancellationToken with axios but found that even though I could cancel the call it still didn't have enough time to set the tables busy state to false.   There needs to be a way to refresh the table and cancel/abort any previous request.

Currently I have had to fall back to a non-optimal pattern shown below.

```
  triggerRefresh() {
            var self = this;

            if (self.$refs.listtable.busy) {
                var handle = window.setInterval(function () {
                    if (!self.$refs.listtable.busy) {
                        window.clearInterval(handle);
                        self.$refs.listtable.refresh();
                    }
                }, 30);
            }
            else {
                self.$refs.listtable.refresh();
            }
    
        }
```

**Comment by tmorehouse** [comment]
Are you using the `.sync` modifier to update your copy of the `busy` prop?

You could also have your provider function return an empty array `[]` initially and then after your options are set up, then have your provider to the actual fetch.

**Comment by tmorehouse** [comment]
We are going to be adding `lodash.debounce` support to the provider functions, which will probably help with this.

**Comment by tmorehouse** [comment]
In the latest `dev` branch, via PR #2393, when a refresh is triggered (either via event, `refresh()` method, or a context change), and if the table is currently in the middle of updating the items via the provider function, it will reschedule a refresh once the current refresh is complete.

Note however, if the table is manually placed in the `busy` state, then the provider function will not be called to update the table (as manual busy setting does not trigger a refresh when it is cleared).

**Comment by runxc1** [comment]
@tmorehouse is there any way to cancel the previous provider function.  If I call refresh 3 time in succession I wouldn't expect it to wait for the results of the first call before triggering it a second time and so on.  Granted some form of debounce would help but if the query is long running I want to abandon it and immediately start the 3rd.

**Comment by tmorehouse** [comment]
Currently it is not possible to cancel the provider within b-table, but you can cancel the provider yourself by rejecting the promise (if using promises).

When the provider refresh is called multiple times when the provider is busy, only a single provider refresh will be scheduled (using the latest context object) once ht current refresh is finished.

If you need more complex handling, I would suggest not using the internal provider features, and instead handle your async calls externally and setting the prop `items` to an array (rather than a function) when your async request completes.

**Comment by handhikadj** [comment]
> Are you using the `.sync` modifier to update your copy of the `busy` prop?
> 
> You could also have your provider function return an empty array `[]` initially and then after your options are set up, then have your provider to the actual fetch.

```
onst parseDoc = async (e) => {
            tableBusy.value = true;
            const formData = new FormData();
            formData.append('file', e.target.files[0]);
            const res = await Axios.post(`${process.env.API_BASEURL}/my-api`, formData, {
                headers: {
                    'Content-Type': 'multipart/form-data',
                },
            });

            tableBusy.value = false;

            refTable.value.refresh(); // won't refresh
        };
```

I'm experiencing this issue. the table is not refreshed. please provide code snippet on this

**Comment by lucianobosco** [comment]
> Currently it is not possible to cancel the provider within b-table, but you can cancel the provider yourself by rejecting the promise (if using promises).
> 
> When the provider refresh is called multiple times when the provider is busy, only a single provider refresh will be scheduled (using the latest context object) once ht current refresh is finished.
> 
> If you need more complex handling, I would suggest not using the internal provider features, and instead handle your async calls externally and setting the prop `items` to an array (rather than a function) when your async request completes.

Is this being considered for further releases? For a huge data load, this behaviour is not viable at all. I'm aware that using an async call will work in this scenario, but using the provider will be easier and cleaner. 
Thanks
