### ISSUE TITLE
Is it possible somehow to listen events globally? For example, when popover is shown/hidden

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#2253]
For example there is a popover with `ref="myPopover"`.
Is there any way to listen `myPopover` for such events as `shown`/`hidden` globally, something like `addEventListener` for `shown` and `hidden` methods?

From the source code seems that it is possible, but I do not understand how to connect to the internal event system in order to listen it.

I need to know if `myPopover` is shown/hidden far far away from a component where `myPopover` lives and I do not want to use `vuex` + `@shown="callSomeFunction"`.

Thank.

**Comment by tmorehouse** [comment]
You can listen for "global" events on the `$root` instance.

```js
this.$root.$on('bv::popover::shown', someHandler)
this.$root.$on('bv::popover::hidden', someHandler)
```

**Comment by TitanFighter** [comment]
Thank you.
Checked the code again. Is it correct, that just these components/directives can be listened: tooltip, popover, dropdown, modal, scrollspy, toggle? I ask because want to make a PR to update docs.

**Comment by tmorehouse** [comment]
Most of these _should_ be listed in the docs (although not always in the component reference at the bottom of the page).

But if you see any missing ones make a PR and we'll merge! :-)

**Comment by TitanFighter** [comment]
Yeah, I see...
Docs already has info, such as

bv::popover::show | bvEvent bvEvent object | Emitted on $root when popover is about to be shown. Cancelable. Call bvEvent.preventDefault() to cancel show.
-- | -- | --

but there is no word how to use it. 

I checked the doc and found that the next components can be listened: collapse, dropdown, modal, popover, tooltip.

I want to create an examples for all of them in order to show how to use events, which look like `bv::popover::show`

**Comment by tmorehouse** [comment]
Some sections of the docs have examples (or verbiage) on how to use the events, but it may not be obvious (or burried a bit).

In most cases, the first argument for _"public"_ root emitted events is the `ID` of the component, and many have a second argument which is the `BvEvent` object (same event object that is emitted on the instance version of the events, i.e. `@hidden`, etc).

**Comment by tmorehouse** [comment]
Take a peak at our programming style guide https://github.com/bootstrap-vue/bootstrap-vue/wiki/Bootstrap-Vue-$root-events for examples.

**Comment by tmorehouse** [comment]
And there _should_ be examples of the events on the directive versions of popover/tooltip docs pages.  I'll have to take a peak to see if there are.

**Comment by TitanFighter** [comment]
The directive versions of popover/tooltip docs pages do not have any info about root events. Also, if I understood the source code correctly and if I remember correctly, `scrollspy` also have root event. I will need to check the source code one more time.

**Comment by tmorehouse** [comment]
Maybe it was the component versions...

**Comment by TitanFighter** [comment]
Lets try to use an example, in order to let me catch everything correctly.

> Package json, you can use events to list what events the components emit (and not if it is local or if it is root).

If I understand correctly, you are talking about `this.$root.$on()`, something like

bv::popover::show | bvEvent bvEvent object | Emitted on $root when popover is about to be shown. Cancelable. Call bvEvent.preventDefault() to cancel show.
-- | -- | --

in case of popover. Right? 

I'm talking about the list of events which user can `this.$root.$emit()`.

Lets continue with popover as an example. In the doc we already have info about `Hiding and showing popovers via $root events` and `Disabling and enabling popovers via $root events`, which show how to emit different events (i.e. `this.$root.$emit('bv::hide::popover')`. What I would like is to create a separate section in `Component Reference` for such events. What is the best way to do that?

**Comment by tmorehouse** [comment]
The events entry in component's package.json is intended for events that the component emits itself, not for one's that the component listens for.

We don't have an official location, other than in the readme, for events the component may listen for (on root).
