### ISSUE TITLE
Modal: No ability to drop focus

### ISSUE THREAD

**Issue by Farbed** [bootstrap-vue/bootstrap-vue#2269]
It appears there isn't an ability to just drop focus or set noEnforceFocus to false when modal opens. I see plenty of options for focusing on something specific, but we need to be able to just not focus (to prevent bootstrap modal from essentially hijacking the screen).

Use case:

[Using swal when a modal is open.](https://github.com/sweetalert2/sweetalert2/issues/374)

**Comment by tmorehouse** [comment]
There is an option to disable enforce focus on modal. Just set the `no-enforce-focus` prop on `b-modal`

This prop is also (or should be) reactive, so you can change it dynamically when needed.

Without enforce focus, the model will become in accessible (or difficult to use) for keyboard only and screen reader users. So it would be best to 3nable disable it on demand depending on your situation.

**Comment by tmorehouse** [comment]
Hmmm... I see what you are talking about. You are referring to focusing the first element when opens.. although it should just be focusing the modal content wrapper, so that screen readers will announce the content properly, and allow keyboard only users to tab directly into the first control.

**Comment by tmorehouse** [comment]
I think this should be fixed in the latest dev branch (as we have altered how he enforce focus works).

Could you try with the latest dev branch?

**Comment by Farbed** [comment]
Wows, your `no-enforce-focus` prop definitely did the trick for me. Thank you!
