### ISSUE TITLE
IE11 not support Object.assign

### ISSUE THREAD

**Issue by kazusa-qooq** [bootstrap-vue/bootstrap-vue#228]
observe-dom.js use Object.assign.  
Unfortunately, IE11 dose not support this method.

Though , your tool works well on IE. Excellent!
Do you know what matter happen on IE?

In addition, I hope to fix this problem if you have a time.
Thanks!

**Comment by SirLamer** [comment]
The compiler performs an ES6-to-ES5 polyfill so it doesn't really matter, so long as a Javascipt feature is part of ES6 it will run on all browsers which support ES5, which includes Internet Explorer. This is very common in many Javascript projects these days.

**Comment by ohmygod12121212** [comment]
install babel-polyfill
import 'babel-polyfill'
in your entry file

**Comment by kazusa-qooq** [comment]
Sorry for not telling about I use this tool on CDN(browser) mode.
But babel-polyfil has a usage of browser and this works well! Great!
https://babeljs.io/docs/usage/polyfill/#usage-in-browser
I think that it is good to put this link on quick start with CDN.
Thanks for your advices!

**Comment by pi0** [comment]
@kazusa-qooq Happy hearing fixed your problem :) About usage, I'll merge your PR if you add instructions in [SETUP.md](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/docs/SETUP.md) CDN part.

**Comment by kazusa-qooq** [comment]
@pi0 I've tried it! Thanks!
