### ISSUE TITLE
Fix for dropdown menu for #1528 causes issues for event listeners outside modal

### ISSUE THREAD

**Issue by djzara** [bootstrap-vue/bootstrap-vue#2291]
Before opening an issue:

**OS**: MacOS 10.14.2
**Browser**: Firefox 64.0
**bootstrap-vue version**: 2.0.0-rc.11
**codepen**: https://codepen.io/djzara/pen/ZVWbva

There was a bug reported in issue #1528 whereby event propagation for clicks was stopped and a new event for dropdowns was fired instead when the modal was clicked. However, some objects and elements rely on the click event bubbling up to the top, but this fix prevents it from happening

from modal.js
```javascript
 on: {
        focusout: this.onFocusout,
        click: function click(evt) {
          evt.stopPropagation();
          // https://github.com/bootstrap-vue/bootstrap-vue/issues/1528
          _this.$root.$emit('bv::dropdown::shown');
        }
```

I can come up with some kind of workaround to get the click to finish moving up, but I think this fix needs to be fixed in order to prevent that kind of thing. I'm having to work on it along side anyone else.

**Comment by tmorehouse** [comment]
In the fix from the code snippet above, that was to ensure dropdowns inside the modal were closed.

Although we are using a new enforceFocus routine, so maybe this fix is no longer needed.

**Comment by tmorehouse** [comment]
Actually this fix is no longer in the latest `dev` branch.

https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/modal/modal.js

So you may want to try with the latest `dev` branch if possible.

**Comment by djzara** [comment]
Thanks, I'll definitely give that a shot just as soon as I can. Few more things to take care of here at the moment and then I'll give that bad boy a try.

Much appreciated!

**Comment by tmorehouse** [comment]
If it isn't fixed in the dev branch, feel free to open a new issues up!
