### ISSUE TITLE
As like Vuestrap this implementation isnt using Vuex, or Im mistaken

### ISSUE THREAD

**Issue by FerchoCarcho** [bootstrap-vue/bootstrap-vue#23]
@pi0 
Looking at the e.g Alert component I find:

1. `this.$emit('dismiss-count-down')`

// Emit an event from the current vm that propagates all the way up to its $root
    2. `   this.$root.$emit('dismissed::alert')`

1. So @ the  alert component I would have to declare 
`<b-alert v-on:dismiss-count-down="doSomething">Hello</b-alert>` 
I cant get the alert make to work. Because Im toggling the alert from another place and The alert component itself is at some different component. For that communication I need Vuex.
2. I Cant find a on 'dismissed::alert' function also.

Can you clarify how to use it please?

**Comment by pi0** [comment]
Events are improved now and it should be fixex :)
