### ISSUE TITLE
Incorrect Navbar items in 0.12.3

### ISSUE THREAD

**Issue by Dibro89** [bootstrap-vue/bootstrap-vue#231]
![image](https://cloud.githubusercontent.com/assets/16293890/25024005/e1305680-20a4-11e7-9179-22f284f29e0f.png)

**Comment by pi0** [comment]
Ops! This is related to 15180110d301a071c6439d8e299a278d94766026 :( I think we should force PRs to provide screenshots to provide this mistakes.) Will work on it.

**Comment by pi0** [comment]
@Dibro89 Thanks for report. fixed in v0.12.4 :)

**Comment by cynecx** [comment]
Oh, I didn't notice that because I've probably styled this with css already.
@pi0 Do you think adding this as a prop (isButton? or just button) would be a better idea?

**Comment by pi0** [comment]
@cynecx If you want to just detect links without href and correct cursor on them why not using css selectors ? 
```css
a:not([href]) {
    /* Styles for anchors without href */
}
```
Is there any other special use case ?

**Comment by cynecx** [comment]
@pi0 That's funny because I haven't thought of that. Thank you for the suggestion ;).
