### ISSUE TITLE
"this.$refs.fileinput.reset is not a function"

### ISSUE THREAD

**Issue by shaneparsons** [bootstrap-vue/bootstrap-vue#2319]
I can't seem to clear my `b-form-file` inputs.

I've tried everything, including `this.$refs.fileinput.reset()`, which returns **"this.$refs.fileinput.reset is not a function"** in firefox and chrome. Every other attempt simply does nothing.

Relevent code:
```html
<b-form-group v-b-tooltip.hover title="Files">
  <b-form-file multiple placeholder="Upload files" ref="fileinput" type="file" v-model="files"/>
  <b-button @click="clearFiles">Reset</b-button>
</b-form-group>
```
```js
export default {
  data() {
    return {
      files: [];
    };
  },
  methods: {
    clearFiles() {
      this.$refs.fileinput.reset();
    },
  },
};
```

**Comment by shaneparsons** [comment]
I'm using `2.0.0-rc.10` btw.

**Comment by tmorehouse** [comment]
You might need to wrap `this.$refs.fileinput.reset()` in a `this.$nextTick`

The dev branch now supports setting the value to null or an empty string, which will then internally reset the file input.

**Comment by shaneparsons** [comment]
Yeah I tried that too, same error.
```js
clearFiles() {
  this.$nextTick(() => {
    this.$refs.fileinput.reset();
   });
},
```
I saw the `b-form-file` notes in https://github.com/bootstrap-vue/bootstrap-vue/issues/2173, but I don't think there's a way for me to use that branch until 2.0.0 is released?

**Comment by tmorehouse** [comment]
The only way (that I know of) to use the dev branch is to change dir into your node_modules directory in your project and to a git clone of the dev branch, and then CD into that and run `yarn install && yarn build`

**Comment by vmihailenco** [comment]
With vue-cli 3 I am using dev branch with:

```
// js
import BootstrapVue from 'bootstrap-vue/src'

// css
@import "~bootstrap-vue/src/index";
```

But I guess that requires some support from build system.

**Comment by tmorehouse** [comment]
Yeah, for the js, you'll need to enable babel transpiliation, since the es modules are not available unless you run `yarn build` in the bootstrap-vue directory.

**Comment by shaneparsons** [comment]
@tmorehouse Thanks, the input is clearing now w/ `this.files = []`.

Would you consider it "dangerous" to use the dev branch until 2.0.0 is released? My project is currently somewhere in between the development and production stages...

**Comment by shaneparsons** [comment]
Perfect, I'll stick w/ the dev branch for the time being then.

Not a single thing has broken from what I can see so far... The only thing I had to change was `b-navbar toggleable` > `b-navbar toggleable="sm"` as it seems the default size was removed? Anyways, this is starting to become off topic.

Cheers!

**Comment by tmorehouse** [comment]
Hmm I'll have to check on the navbar and the default breakpoint.

**Comment by tmorehouse** [comment]
Ah, that is because we introduced the option to always have the navbar collapsed (acceptance of boolean true on toggleable prop). May need to update the docs.

**Comment by shaneparsons** [comment]
@tmorehouse Is there a way to prevent a root `npm i` from removing the cloned bootstrap-vue directory from node_modules?

**Comment by tmorehouse** [comment]
Probably not.  You may need to place the dev branch bootstrap-vue outside of node_modules, and do an import from that local directory (after building).
