### ISSUE TITLE
Feature: Allow disabling of modal close on Esc key.

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#232]
Similar to disable close on clicking the backdrop, it would be nice to be able to disable closing of the modal by pressing `ESC`.

As well, could you not use `@keyup.esc` on the modal `div` to detect if the ESC key was pressed in while the modal was open (rather than binding the esc key detection on the document element?

```html
<div key="modal" :id="id"
     v-show="visible"
     :class="['modal',{fade :fade}]"
     @click="onClickOut($event)"
     @keyup.esc="onEsc($event)"
>
```

```js
export default {
  ...
  props {
    ...
    closeOnEsc: { type: Boolean, default: true },
    ...
  },
  methods {
    ...
    onEsc(e) {
      if (this.visible && this.closeOnEsc) {
        this.hide();
      }
    },
    ...
  },
  ...
}
```

**Comment by pi0** [comment]
Hi @tmorehouse. Nice enhancement. Do you confirm `@keyup.esc` solution fully working  when focus is not on modal itself? (in input boxes inside of modal for example) ? If yes please open a PR, i will merge it :)

**Comment by tmorehouse** [comment]
I haven't tested when modal is not focused (although the modal `div` should have a `tabindex="-1"`).

There is a technique to make sure the modal does not loose focus, by basically listening for focus events and then checking if the element that triggered the event is not contained within the modal, and if not, then set focus to the modal div.  You would need to add a `ref="modal"` on the modal `div`

```js
if (this.visible && 
    document !== e.target && 
    this.$refs.modal !== e.target &&
    !this.$refs.modal.contains(e.target) {
  this.$refs.modal.focus();
}
```

**Comment by pi0** [comment]
So then any input box inside modal won't work anymore! I think this was the main reason to listen on document for that trigger (anyway not tested myself)

**Comment by SirLamer** [comment]
I'm pretty sure you can intercept the key event from children elements propagating up.

**Comment by tmorehouse** [comment]
@pi0 This focus snippet is actually from bootstrap's (v3) code for the modal (modified by me to use the ref's feature of Vue). It listens at document for any focus evento while the modal is open. If the focus event wasn't triggered within the modal (i.e. A button or input outside of the modal) then it triggers focus on the model itself. Any focus inside the modal is left alone. This is also needed for ARIA accessibility to keep screen readers form taking through the document while the modal is open. 

@SirLamer , yes, elements within the modal could intercept the esc key as well, but by default they don't. And will propagate up to the top modal division where the onEsc () handler is listening.

**Comment by tmorehouse** [comment]
@pi0 I believe the `@keyuup.esc` might  require Vue 2.2.0+

**Comment by tmorehouse** [comment]
I'll make a new fork and make the additions for handling `esc` as optional, and will add in the `enforceFocus` handler while the modal is visible

**Comment by tmorehouse** [comment]
Pull request #247

**Comment by tmorehouse** [comment]
Merged
