### ISSUE TITLE
current tab index is reset by click event during mount

### ISSUE THREAD

**Issue by bouchezb** [bootstrap-vue/bootstrap-vue#2327]
Hi,

I have a project in which I need to store the selected tab in a page and restore it when I come back.
I save the current tab index in a var store on the click event (only this one) of the tab, which works well, as far as I know.
When I go back to my page, the current tab index is forced to 0. I assume that the click event handler is called because it is the only way to overwrite the previously saved values.

I can see that this event has been emmited since issue #205 was closed.

https://github.com/bootstrap-vue/bootstrap-vue/blob/bd557edc6a4a46f2caacda2713019970e12e305c/src/components/tabs/tabs.js#L159-L166

I think the click event should not be emitted because there is no real click.

What do you think about this behavior?
Thanks,
Regards

**Comment by tmorehouse** [comment]
I'm not sure of the reasoning for emitting the event  at that point. Will have to dig into it further. It should technically be only emitted on under interaction.

**Comment by bouchezb** [comment]
Hi,

Thanks for your reply.
In issue #205, the initial request was to enabled click event on a `b-tab` inside `b-tabs`.
@pi0 added this event emission here, but i can't figure out why in the repository history.
Maybe he can enlighten us.

**Comment by bouchezb** [comment]
Hi,

Did you had time to have a look at this issue ?

I really think this event should'nt be emitted at this point.
I know this seems not truely important, but i need at least an answer which can help me to think about a solution to the feature i need to develop for my project.

Thanks.

**Comment by bouchezb** [comment]
Hi @tmorehouse,

Thanks for the big update on tabs component :+1: .
I can see you have merged your work in branch dev.
Do you know when this will be available in a RC version ?

Thanks.

**Comment by tmorehouse** [comment]
Not offhand... but soon...

**Comment by bouchezb** [comment]
Hi there !
Sorry to insist, but I still hoping an RC version.
Is it planned soon ?

**Comment by tmorehouse** [comment]
Soon I hope...
