### ISSUE TITLE
horizontal forms

### ISSUE THREAD

**Issue by dharmatv** [bootstrap-vue/bootstrap-vue#2329]
Hi,

I am using vue bootstrap in my project in that one i have a requirement horizontal form with 2 or more input fields in a single line 

i see form-group, in that  two or more labels/legends will be single line but there is no form-input will be two or more will be single line

Can any one please help how to solve this problem

i want output like this

https://snag.gy/W48qj1.jpg

**Comment by tmorehouse** [comment]
Use b-row (or form-row) and b-col to arrange your form-groups into a grid.

**Comment by dharmatv** [comment]
thanks for reply, but in my project no need to write row or column, i think form-input will be most suitable 
is there any chance to get horizontal input type by using b-form-input

Thanks

**Comment by dharmatv** [comment]
<b-card bg-variant="light">
  <b-form-group horizontal
                breakpoint="lg"
                label="Shipping Address"
                label-size="lg"
                label-class="font-weight-bold pt-0"
                class="mb-0">
    <b-form-group horizontal
                  label="Street:"
                  label-class="text-sm-right"
                  label-for="nestedStreet">
      <b-form-input id="nestedStreet"></b-form-input>
    </b-form-group>
    <b-form-group horizontal
                  label="City:"
                  label-class="text-sm-right"
                  label-for="nestedCity">
      <b-form-input id="nestedCity"></b-form-input>
    </b-form-group>
    <b-form-group horizontal
                  label="State:"
                  label-class="text-sm-right"
                  label-for="nestedState">
      <b-form-input id="nestedState"></b-form-input>
    </b-form-group>
    <b-form-group horizontal
                  label="Country:"
                  label-class="text-sm-right"
                  label-for="nestedCountry">
      <b-form-input id="nestedCountry"></b-form-input>
    </b-form-group>
    <b-form-group horizontal
                  label="Ship via:"
                  label-class="text-sm-right"
                  class="mb-0">
      <b-form-radio-group class="pt-2" :options="['Air', 'Courier', 'Mail']" />
    </b-form-group>
  </b-form-group>
</b-card>

Above example it shows 

https://snag.gy/vS7Qfb.jpg

but i need 

https://snag.gy/W48qj1.jpg


<b-card bg-variant="light">
  <b-form-group horizontal
                breakpoint="lg"
                label="Shipping Address"
                label-size="lg"
                label-class="font-weight-bold pt-0"
                class="mb-0">
    <b-form-group horizontal
                  label="Street:"
                  label-class="text-sm-right"
                  label-for="nestedStreet">
      <b-form-input id="nestedStreet">left alignement</b-form-input>
     <b-form-input id="nestedStreet">right alignement</b-form-input>
    <b-form-input id="nestedStreet">left alignement</b-form-input>
    </b-form-group>    
  </b-form-group>
</b-card>

**Comment by tmorehouse** [comment]
That bottom Iink you listed is rows and columns... each grid cell containing a non horizontal form group.

```html
<b-row>
 <b-col><form-group label="foo"><b-form-input></b-form-input></b-col>
 <b-col><form-group label="bar"><b-form-input></b-form-input></b-col>
</b-row>
<b-row>
 <b-col><form-group label="foo2"><b-form-input></b-form-input></b-col>
<b-col><form-group label="bar2"><b-form-input></b-form-input></b-col>
</b-row>
```

Its rows and columns of form groups...

**Comment by dharmatv** [comment]
what i am asking is without using <b-row><b-col> just i am using <b-form-input horizontal>

is it possible for in vue bootstrap

**Comment by tmorehouse** [comment]
Yes

**Comment by tmorehouse** [comment]
Use standard divs with class row and col-*
