### ISSUE TITLE
[feature request] <b-table> sytle formatter callback in fields definition

### ISSUE THREAD

**Issue by ddweber** [bootstrap-vue/bootstrap-vue#2336]
### Current situation:
**b-table component**
Custom rendering for each data field in a row is possible using (either scoped slots or) formatter callback function. Nice, that´s very convinient! :)

But applying styles to fields (like a cell-variant) requires the user of the component to pre-modify his data before giving it to the b-table-component. Hmm. :|

### Idea/requested feature:
Wouldn´t it be neat if the user has the ability to **apply** his custom **styles** (/variants/css-classes..) **via** a **sytle-formatter callback in the fields** (/column) **defintion** of the b-table?

**Comment by tmorehouse** [comment]
There is an option (in dev) for applying classes to the cells using a callback. It will be available next releasel
