### ISSUE TITLE
b-form-checkbox and b-form-radio buttons - add custom classes to individual buttons

### ISSUE THREAD

**Issue by DM2489** [bootstrap-vue/bootstrap-vue#2339]
It's great that the `b-form-checkbox` and `b-form-radio` components have the `buttons` prop, and that we can specify a `button-variant`.

What I'd like to be able to do is, in some cases, add additonal CSS classes to some inputs to change how the options are displayed.

It would be great if we could have a 'button-class' prop that could add classes to the button label.

Consider the following:

```
<b-form-checkbox-group
    v-model={this.category}
    checked={this.category}
    options={this.categories}
    class="row mx-0"
    buttons
    button-variant="outline-primary"
    button-class="col-6 px-0 mb-1" />
```

Here's the desired effect I'm going for in this particular example:

![image](https://user-images.githubusercontent.com/40390596/50342656-db1ede80-051b-11e9-8e85-0f24c42f5c72.png)

The `button-class` property would then give us greater control of the button label styling.

**Comment by DM2489** [comment]
Not sure if this is intended but I've just realised I can do this already by treating the `button-variant` as a class property.

```
<b-form-checkbox-group
    v-model={this.category}
    checked={this.category}
    options={this.categories}
    class="row mx-0"
    buttons
    button-variant="outline-primary col-6 px-0 mb-1" />
```
I'll close this issue!

**Comment by tmorehouse** [comment]
Not really intended to be used as a class prop, but I don't think there is any plans to change this u documented behaviour.  Just note that  this is not guaranteed to work in the future.

On individual radios/checkboxes, you can add classes to the root element, by adding them directly to the component.
