### ISSUE TITLE
Recommended modal usage with vuex?

### ISSUE THREAD

**Issue by ropeladder** [bootstrap-vue/bootstrap-vue#234]
Hi, thanks for your great work on this component.

I'm trying to use the modal component with Vuex so that I can trigger the modal from anywhere in my app. Right now I have it set up using a watcher on a computed property, like so:
```
...
computed: {
    showModal: function () { return this.$store.state.modal.show },
},
watch: {
    showModal: function(val) {
        if(val === true) this.$root.$emit('show::modal','modal1')
    }
}
```
Is this the recommended way to set this up?

**Comment by pi0** [comment]
@ropeladder Now more modal toggle methods are available. See [modal docs](https://bootstrap-vue.github.io/docs/components/modal) . Choose best one that fits your usage.

**Comment by ropeladder** [comment]
@pi0 Awesome, thanks!
