### ISSUE TITLE
Existing Bootstrap layout

### ISSUE THREAD

**Issue by toudidel** [bootstrap-vue/bootstrap-vue#2340]
Is it possible to apply bootstrap-vue css style only to bootstrap-vue components?

I already have layout prepared by boostrap developers using boostrap css classes and bootstrap name convention. When added bootstrap-vue many components don't work properly because of old boostrap styles. It'd be nice to point following css styles only for bootstrap-vue components:

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'

**Comment by toadkicker** [comment]
bootstrap-vue doesn't care about the css from Bootstrap. You can include whatever bootstrap CSS from any location.

**Comment by tmorehouse** [comment]
Bootstrap-vue doesn't include bootstrap's css. You  need to manually include bootstrap's css, and you need to make sure you are using the right version of bootstrap css for the version of bootstrap-vue you are using.
