### ISSUE TITLE
why not passing "show" prop to a component rather than using id?

### ISSUE THREAD

**Issue by ohmygod12121212** [bootstrap-vue/bootstrap-vue#235]
this provides more flexible control and avoid using id
for example
```
<template>
    <div>
        <v-modal show="show" />
        <button @click="click">button</button>
    </div>
</template>

<script>
export default {
    data() {
        return {
            show: false
        }
    },
    methods: {
        click(){ this.show = !this.show }
    }
}
</script>
```
and I can use it with external controls(eg. computed from data)
```
<template>
    <div>
        <v-modal show="show" />
        <button @click="click">button</button>
    </div>
</template>

<script>
export default {
    computed: mapState({
        show: state.some.state.some.property
    })
}
</script>
```

**Comment by mosinve** [comment]
is it usable with 2 or more modals?
user will need a variable for each modal dialog.... IMHO emitting show event with an ID of modal quite flexible already.

**Comment by ohmygod12121212** [comment]
@mosinve 
if I want to show a modal on other actions, such as user input change, rather a DOM event, emitting events is really a bad idea

**Comment by mosinve** [comment]
but you always can emit an event on input change, why not?

**Comment by pi0** [comment]
@ohmygod12121212 Now more modal toggle methods are available. See [modal docs](https://bootstrap-vue.github.io/docs/components/modal)
