### ISSUE TITLE
bootstrap-vue table with dynamic columns.  Column doesn't sort.

### ISSUE THREAD

**Issue by RotateAt60MPH** [bootstrap-vue/bootstrap-vue#2353]
I have a problem in a bootstrap-vue table that has dynamic number of columns.  For some reason, the data in the first column (person names) sorts in a weird order ( via the up/down icon in the header).  The data is not sorted to start with.  The other columns sort, as expected.

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
Windows 10 x64

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Firefox 64.0 x64

- Version of Bootstrap-Vue that you are using
+-- bootstrap@4.2.1
+-- bootstrap-vue@2.0.0-rc.11
+-- bootstrap@4.2.1 deduped

- Reduced test cases and potential fixes using [JsFiddle](https://jsfiddle.net/) 
https://jsfiddle.net/cardinal177/dowymfL0/

- Expected result
Data in first column sorts like the other columns.

**Comment by lianee** [comment]
In fact, even your other columns don't sort properly.

According to the docs:

> Note: The built-in sort-compare routine cannot sort virtual columns, nor sort based on the custom rendering of the field data...

You should use a custom sorting routine, here is a quick&dirty way (no checks, only string):
[Updated fiddle](https://jsfiddle.net/fcwkvorp/)

**Comment by RotateAt60MPH** [comment]
Much obliged.  Seasons greetings
