### ISSUE TITLE
Cannot access [Slack] https://bootstrap-vue.now.sh to ask about 'How to question'

### ISSUE THREAD

**Issue by YuryKorovko** [bootstrap-vue/bootstrap-vue#2356]
https://bootstrap-vue.now.sh the site doesn't open. 
Sorry for opening issue here :( 

P.S. How to add new row and make it row-details immediately ? 
I understand that table shows only current items and to add new element to show is not a problem but idk how to open its details without additional manual clicking 'toggleDetails' ?
I need to open details  immediately after new row has been added .

**Comment by tmorehouse** [comment]
We are migrating off of slack to Discord. Use the following link to join: https://discord.gg/j2Mtcny
