### ISSUE TITLE
cannot use @focus, <input @focus="inputIsFocus" type="text"/>

### ISSUE THREAD

**Issue by afandiyusuf** [bootstrap-vue/bootstrap-vue#2357]
i need to trigger function while focusing on text input.
with regular text input, i can use @focus

```
<input type="text" @focus="inputIsFocus()" />
```

i can't find any documentation about this function.
if vue-bootstrap remove this function, how to achieve this function with vue-bootstrap?

regards

**Comment by tmorehouse** [comment]
Use `@focus.native`

**Comment by tmorehouse** [comment]
Also, which version of bootstrap-vue are you using? (Please follow the issue template guidelines)

**Comment by tmorehouse** [comment]
This should be addressed in the latest `dev` branch and will be available next release.

**Comment by jsappme** [comment]
@focus.native works fine on my browser but not on mobile. any idea why?
