### ISSUE TITLE
nested collapse height problem

### ISSUE THREAD

**Issue by ropeladder** [bootstrap-vue/bootstrap-vue#236]
I'm trying to nest multiple 'collapse' elements but they do not work as expected: the grandparent of the expanding element does not expand when the parent of the element expands. It looks like this is due to `collapse.vue` using real values for height instead of `auto`?

https://jsfiddle.net/1j67eanq/1/

VueStrap's collapsing Accordion/Panel setup allows nesting without any problems so this should be possible: https://github.com/wffranco/vue-strap/blob/master/src/Panel.vue

**Comment by pi0** [comment]
@ropeladder Nice link! :) This is the trick they are using to spy real height:
```js
      el.style.height = 'auto'
      var endWidth = getComputedStyle(el).height
      el.style.height = '0px'
      el.offsetHeight // force repaint
      el.style.height = endWidth;
```

@ohmygod12121212 What's your idea?

**Comment by pi0** [comment]
@ropeladder Thanks for supported approach. Improvements will be available in next release soon.
