### ISSUE TITLE
Accordion caret not working when using accordion component within tab

### ISSUE THREAD

**Issue by warrence** [bootstrap-vue/bootstrap-vue#2371]
Hi, accordion caret is always pointed up no matter is a collapse in or out when using accordion component in Tab. Does anyone have the same experience with this? Been searching for 2 days but no solution found.

**Comment by tmorehouse** [comment]
Could you provide an example of your code? Accordion mode of the collapse component doesn't create a caret automatically.

**Comment by warrence** [comment]
I'm sorry, my mistake. I thought accordion caret was from boostrapvue, after check, it was actually from the theme that im using. I will contact the author instead. Thanks
