### ISSUE TITLE
add link to card title, subtitle, image

### ISSUE THREAD

**Issue by xxyyzz2050** [bootstrap-vue/bootstrap-vue#2372]
add the ability to add a link to title text and also subtitle and image, without the need to totally implement the body component

```
<b-card
 title="test"
 title-link="http://google.com"
 />
```

or:
```
<b-card
 title="<a href='#'>html allowed</a>"
/>
```

or:
```
<b-card>
 <title><a href="#">using title tag or title slot</a></title>
</b-card>
```

**Comment by tmorehouse** [comment]
One can add links via manual creating of title tag within card body (as the title prop is mainly a simple convenience feature)

**Comment by vesper8** [comment]
why not just create slots for the title and subtitle?

what is this workaround for adding links inside the title/subtitle? please an example

@tmorehouse adding a <title> tag inside the b-card body is ignored in my case.. this doesn't work? also tried using a title slot.. no go

**Comment by TitanFighter** [comment]
If somebody needs example...
This is what I had:
```
<b-card-body :title="memberObj.profile.firstName + ' ' + memberObj.profile.lastName">
  <b-card-text>Some Text</b-card-text>
</b-card-body>
```

This one is with added link via `<b-link>`:
```
<b-card-body>
  <b-card-title>
    <b-link :to="{ name: 'Profile', params: { profileUrl: memberObj.settings.profileUrl } }">
        {{ memberObj.profile.firstName + ' ' + memberObj.profile.lastName }}
    </b-link>
  </b-card-title>

  <b-card-text>Some Text</b-card-text>
</b-card-body>
```

**Comment by Slluxx** [comment]
I need a link to wrap the whole card and not just one part. Adding `<b-link>` link around the card breaks the card decks group though.

**Comment by TitanFighter** [comment]
You need to use [stretched-link](https://getbootstrap.com/docs/4.5/utilities/stretched-link/) class
