### ISSUE TITLE
Table custom sort  

### ISSUE THREAD

**Issue by morangil** [bootstrap-vue/bootstrap-vue#2379]
I'm using my own sort function but i still want to use sortable option for each field because it's adding a lot off accessible aria attributes and css.
so my function is called with `v-on:head-clicked="sort"` but because the field is `sortable: true` the table get sorted twice. i tried adding `no-provider-sorting ` but i don't see any difference. 

as you can see in this example: [https://jsfiddle.net/yf1bokxm/](https://jsfiddle.net/yf1bokxm/)
i'm trying NOT to sort items with no score. but having `sortable: true` on score field is ignoring my sort.

(here: [https://jsfiddle.net/xsaLjuq0/](https://jsfiddle.net/xsaLjuq0/) is working custom sorting when sortable is not set)

what else can i do?

**Comment by tmorehouse** [comment]
Use the `sort-changed` event on `b-table` rather than the `head-clicked`.

See https://bootstrap-vue.js.org/docs/components/table#detection-of-sorting-change

**Comment by morangil** [comment]
thanks @tmorehouse but it's not working: [https://jsfiddle.net/yf1bokxm/1/](https://jsfiddle.net/yf1bokxm/1/)

**Comment by tmorehouse** [comment]
You still have local sorting enabled, so you need to add `no-local-sorting` prop to your b-table to disable the internal sort routine

**Comment by tmorehouse** [comment]
@morangil did the above prop (`no-local-sorting`) help with your issue?

**Comment by morangil** [comment]
yes! thanks :)

**Comment by tmorehouse** [comment]
Cool.
