### ISSUE TITLE
v-on:change with b-form-select

### ISSUE THREAD

**Issue by TypicalFooBar** [bootstrap-vue/bootstrap-vue#238]
Is it possible to use v-on:change with a b-form-select component? My function does not seem to be fired when I try using v-on:change. Is there another way to capture this event, or is this not currently supported with the b-form-select component?

Thanks! :)

**Comment by TypicalFooBar** [comment]
@click doesn't seem to work for me, either.

**Comment by pi0** [comment]
@TypicalFooBar Sorry answering too late. `b-form-select` is using `form-options` mixin which uses `v-model` you can either use `v-model` or listen for `@input` events instead.

**Comment by ylahav** [comment]
I used watch instead of 'v-on'
