### ISSUE TITLE
Table Pagination Does Not Seem To Work As Documented

### ISSUE THREAD

**Issue by samielhini** [bootstrap-vue/bootstrap-vue#2389]
I am using OSX with Chrome and Safari.

Latest version of Bootstrap-Vue

When I use provider paging the table is blanked in between api calls.  This is not as smooth looking as paging when all data is loaded at once.

Am I doing something wrong?

**Comment by tmorehouse** [comment]
Without seeing a sample of your code it is hard to tell.

The table should show the previous results (although in the busy state/styling), while it fetches new data.

Note that the `dev` branch (not yet released) has several improvements.

**Comment by samielhini** [comment]
It seems to work as expected when I use the promise form of the provider.  The callback form refreshes the entire table which looks like a page reload.

**Comment by samielhini** [comment]
I would spend more time on this but I like the promise method better.  I'm going to close this issue.
