### ISSUE TITLE
Vue-loader transformToRequire to resolve img paths

### ISSUE THREAD

**Issue by samielhini** [bootstrap-vue/bootstrap-vue#2392]
Hello,

I have tried a few different ways to configure this but can't seem to find a good example. 

Is this proper in my webpack.config.js

```js
const path = require('path')
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = {
  entry: './src/main.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {},
          transformToRequire: {
            img: 'src',
            image: 'xlink:href',
            'b-img': 'src',
            'b-img-lazy': ['src', 'blank-src'],
            'b-card': 'img-src',
            'b-card-img': 'img-src',
            'b-carousel-slide': 'img-src',
            'b-embed': 'src'
          }
        }
      }
    ],
    plugins: [
      // make sure to include the plugin for the magic
      new VueLoaderPlugin()
    ]
  }
}
```

**Comment by tmorehouse** [comment]
You may need to add in loaders (`file-loader` or `url-loader`) to handle image files:

https://vue-loader.vuejs.org/guide/asset-url.html#related-loaders

**Comment by samielhini** [comment]
Please update your documentation to reflect that 

transformToRequire had been renamed to transformAssetUrls

https://vue-loader.vuejs.org/migrating.html

**Comment by tmorehouse** [comment]
The lastest dev branch has already been updated:

https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/docs/markdown/reference/images/README.md

**Comment by samielhini** [comment]
I am doing more research on this.  None of these options are working.  I think I need to use the changing syntax in vue.config.js.

**Comment by samielhini** [comment]
This is how you get this to work if you created your project with vie-cli.

If you don't already have a one create a file called vue.config.js in the root of your project and put the following in the file:

module.exports = {
  chainWebpack: config => {
    config.module
      .rule('vue')
      .use('vue-loader')
      .loader('vue-loader')
      .options({
        transformAssetUrls: {
          'b-img': 'src',
          'b-img-lazy': ['src', 'blank-src'],
          'b-card': 'img-src',
          'b-card-img': 'img-src',
          'b-carousel-slide': 'img-src',
          'b-embed': 'src'
        }
      })
  }
}
