### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by XpamAmAdEuS** [bootstrap-vue/bootstrap-vue#2394]
Hi.
When i set currentPage: 0 as first page i get Invalid prop: custom validator check failed for prop "value".

I am using SpringBoot for backend and pagination uses 0 for first page.

Thx.

**Comment by tmorehouse** [comment]
Both pagination components are `1` based (page 1, page 2, etc), rather than `0` based.  Think of it a page numbers in a book... the book starts at page `1`.
