### ISSUE TITLE
Dropdown Dividers

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#240]
How does one create a divider item for dropdowns?

**Comment by tmorehouse** [comment]
Just discovered that one can include the following in their `<b-dropdown>` markup:

```html
<b-dropdown text="Menu">
   <b-dropdown-item href="#">Item 1</b-dropdown-item>
   <b-dropdown-item href="#">Item 2</b-dropdown-item>
   <b-dropdown-item href="#">Item 3</b-dropdown-item>
   <div role="presentation" class="dropdown-divider"></div>
   <b-dropdown-item href="#">Separated Item</b-dropdown-item>
</b-dropdown>
```

even though the markup is simple, should there be a `<b-dropdown-divider>` component?

**Comment by mosinve** [comment]
Purpose of Bootstrap-vue is to bring and reactify Bootstrap's jQuery components with Vue.js
Divider is just a css class, so it doesn't need to be reactified. You can just use Bootstrap's css class very well.
I suppose this issue may be closed.

**Comment by tmorehouse** [comment]
I was just thinking that since bootstrap-vue hides most of the markup/classes to the user, that it might be handy to component-ize some of the other items, such as the `dropdown-divider`

**Comment by pi0** [comment]
I agree with @tmorehouse opinion, we already made lot's of markup easier. adding simple semantic component is not so bad. (only few more bits are added to bundle)

**Comment by tmorehouse** [comment]
I have a `b-dropdown-header` component as well. It uses a `slot`` to populate the content of the `<h6>...</h6>`.  And the default of `h6` tag can be changed via a prop.
