### ISSUE TITLE
how to remove b-tabs's border (focus ring)

### ISSUE THREAD

**Issue by guocdfeifei** [bootstrap-vue/bootstrap-vue#2403]
![qq 20190106165510](https://user-images.githubusercontent.com/3377194/50734090-0409c980-11d4-11e9-9c7b-19740e2e7f23.png)
how to remove?thinks

**Comment by guocdfeifei** [comment]
亲们？有大拿帮忙看看么？

**Comment by tmorehouse** [comment]
Which version of Bootstrap-Vue are you using, and which browser?

It looks like you are seeing the focus outline which is shown when you tab into the b-tabs tab header, which is needed for keyboard navigation user (using left/right to select which tab to display).  tabing out of the controls will remove the focus ring.

**Comment by guocdfeifei** [comment]
> Which version of Bootstrap-Vue are you using, and which browser?
> 
> It looks like you are seeing the focus outline which is shown when you tab into the b-tabs tab header, which is needed for keyboard navigation user (using left/right to select which tab to display). tabing out of the controls will remove the focus ring.

chrome 
last version
https://bootstrap-vue.js.org/docs/components/tabs
the first example

**Comment by guocdfeifei** [comment]
> > Which version of Bootstrap-Vue are you using, and which browser?
> > It looks like you are seeing the focus outline which is shown when you tab into the b-tabs tab header, which is needed for keyboard navigation user (using left/right to select which tab to display). tabing out of the controls will remove the focus ring.
> 
> chrome
> last version
> https://bootstrap-vue.js.org/docs/components/tabs
> the first example

click the blank area
![qq 20190108201427](https://user-images.githubusercontent.com/3377194/50830211-1c1f4b80-1382-11e9-8662-89706e782b00.png)

**Comment by tmorehouse** [comment]
What you are seeing the the focus ring around the tabs navigation "widget".  Once focused you can use the left and right cursor keys to select tabs.
