### ISSUE TITLE
Dropdowns should allow keyboard navigation with cursor up/down/left/right (ARIA)

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#241]
For ARIA accessibility, dropdowns should allow for keyboard navigation. 

Cursor up/left should select the previous menu item, and cursor down/right should select the next item. 

Each menu item should have a `tabindex="0"`, while the `.dropdown-menu`  `div` should have a `tabindex="-1"` which should gain `focus()` when the dropdown is opened.  When closed, the dropdown button should regain `focus()`

**Comment by tmorehouse** [comment]
A good example of an ARIA keyboard navigation: http://irama.org/web/dhtml/aria/key-nav/

**Comment by pi0** [comment]
@tmorehouse Some partial attempts was done in #8aa1a0f commit, but has no idea about keyboard binding. `key-nav` is not a simple solution and adding such functionality needs extending library size too much which is not ideal. One may extend drop-down component too add such functionality. If you know an easier one liner solution please feel free to re-open this issue.

**Comment by tmorehouse** [comment]
I've got a prototype version I am working on in a new branch.  Will play around with it (and I have a few visually impaired users that can test for me).

I'll re-open once I have the few links worked out.

**Comment by tmorehouse** [comment]
PR #274 addresses keyboard navigation based on new Bootstrap V4 code https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js
