### ISSUE TITLE
<b-table>: column filter dropdown feature

### ISSUE THREAD

**Issue by impowski** [bootstrap-vue/bootstrap-vue#2417]
Right now it's basically impossible to use components inside header slot of `b-table` due to #719 and I suppose it will be fixed sooner or later.

I would like to address for a new feature something similar to this: https://element.eleme.io/#/en-US/component/table#filter

It would be really convenient if filter could get data which could be filtered from the data inside column. (we will just need to get all unique values of column and set it as an array into filter)

Current state of implementing this is basically painful due to bugs and working with Dropdowns too.

**Comment by tmorehouse** [comment]
The latest `dev` branch should have this addressed (Where one previously needed to use `.stop` event modifiers`.  The `row-clicked` and `head-clicked` event listeners filter out clicks on inputs and dropdowns.
