### ISSUE TITLE
[b-dropdown] input field loses focus when the cursor is on another dropdown-item

### ISSUE THREAD

**Issue by BartekZienkiewicz** [bootstrap-vue/bootstrap-vue#2421]
![wqwhzvgjsm](https://user-images.githubusercontent.com/29097511/50892731-75799000-13ff-11e9-8ec5-5f66e77cf7c4.gif)

[Here](https://codesandbox.io/s/61jo220v23) is a working example based on @emanuelmutschlechner [solution](https://github.com/bootstrap-vue/bootstrap-vue/issues/1628#issuecomment-383746196) for another problem.

Is it possible to keep focus on the field?

**Comment by tmorehouse** [comment]
Currently `b-dropdown` does not support form controls, only the listed sub components mentioned in the docs are supported.

**Comment by tmorehouse** [comment]
Note that `dev` branch has changes to dropdown which doesn't move focus on hover (which version of Bootstrap Vue are you using?), and that PR #2434 adds support for form controls within dropdowns.

**Comment by tmorehouse** [comment]
Fixed in latest dev branch

**Comment by BartekZienkiewicz** [comment]
@tmorehouse 
>which version of Bootstrap Vue are you using?

2.0.0-rc.11

>Fixed in latest dev branch

Great! When are you planning to merge changes into master?
