### ISSUE TITLE
Typescript definitions: type the properties

### ISSUE THREAD

**Issue by bmtKIA6** [bootstrap-vue/bootstrap-vue#2423]
At the moment, the typescript type definitions only expose the functions, and not the properties of the components.

For example, Modal: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/index.d.ts#L80
In JS, it does have is_visible property that is available, however, TypeScript does not know about it.

Is it intentional or nobody never needed?

**Comment by tmorehouse** [comment]
The internal data properties of components are private and external manipulation of them may (or most likely will) cause issues, and the private data structures may change in the future.
