### ISSUE TITLE
Docs layout is broken

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#2424]
- Operating system and version: Ubuntu 18.10 x64
- Browser and version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Version of Bootstrap-Vue that you are using: Latest dev (the last commit is `74a1aee0b7325892ef37c4d793c0c35c07d7948e`)

Cloned `bootstrap-vue`. Accessing via `http://localhost:3000/docs` gives 2 problems:
1. When I scroll a central part of any docs page, the left and right blocks are scrolling also.
2. In the left block the names of components are mixed (not ordered).

![image](https://user-images.githubusercontent.com/12687911/50919814-84d2fa80-144c-11e9-9f37-0562920a5df8.png)

**Comment by TitanFighter** [comment]
Re-run of `yarn docs-dev` fixed the issues.

**Comment by tmorehouse** [comment]
Yeah, I have seen this issue before which was caused by incorrect (or inconsistent) load order of the css files. This was originally caused by a bug in Nuxt.JS not preserving the desired import order.
