### ISSUE TITLE
b-card image fluid property

### ISSUE THREAD

**Issue by samielhini** [bootstrap-vue/bootstrap-vue#2428]
it seems like b-card is ignoring the img-fluid property.

```
<template>
  <div v-if="person">
    <b-card
      img-bottom
      img-fluid
      :img-src="'data:image/jpeg;base64,' + person.FaceImage.Base64BinaryObject"
      :title="person.PersonName[0].PersonGivenName + ' ' + person.PersonName[0].PersonSurName"
    ></b-card>
    <b-card
      :title="person.PersonName[0].PersonGivenName + ' ' + person.PersonName[0].PersonSurName"
    >
      <b-card-img fluid :src="'data:image/jpeg;base64,' + person.FaceImage.Base64BinaryObject"/>
    </b-card>
    <b-card
      :title="person.PersonName[0].PersonGivenName + ' ' + person.PersonName[0].PersonSurName"
    >
      <b-img fluid :src="'data:image/jpeg;base64,' + person.FaceImage.Base64BinaryObject"/>
    </b-card>
  </div>
</template>
```

The third example works as described with the image only scaling to its maximum width.

The first two scale the image beyond its maximum width.

Is this the expected behavior?

[https://imgur.com/5ztHfk4](https://imgur.com/5ztHfk4)

**Comment by jackmu95** [comment]
The problem is that `<b-card>` and `<b-card-img>` both apply the `card-img` class to the image which set's the `width` to `100%`. When you use `<b-img>` itself the `card-img isn't applied and everything works as expected.

The `fluid` property for the `<b-card-img>` makes no sense IMHO.

**Comment by tmorehouse** [comment]
I'm trying to recall why it was added... I think it was meant to either make the image grow past native size, or restrict to maximum of native size.

I'll have to review the settings and classes to see what it is doing (or what it makes different).

**Comment by jongbonga** [comment]
Sorry to come more than a year later... how do I then use `img-width` on `card` if it always going to be 100%?
