### ISSUE TITLE
Share boostrap 4.0 and vue-bootstrap css files

### ISSUE THREAD

**Issue by sowinski** [bootstrap-vue/bootstrap-vue#2441]
Hi,

I have a website which is using bootstrap 4.0 with jquery. I started to rewrite some parts of the website with vue and would like to use vue-bootstrap. But at the current state I don't want to rewrite everything. Is it possible to share the same css file for both worlds?

Thank you

**Comment by tmorehouse** [comment]
BotstrapVue requires your pages/app to include BootstrapV4 CSS, so yes, you should be able to use both at teh same time.

**Comment by sowinski** [comment]
Currently I am using my bootstrap 4.0 stylsheets. But my modal's are looking broken.

Are you sure that the css files of bootstrap and vue-bootstrap are the same?
And can I see somehow which version of the css files vue-bootstrap is using?

**Comment by tmorehouse** [comment]
There are several versions of Bootstrap V4.x, all of wich have slight differences.

Are you using 4.0.beta, 4.0, or 4.1?

Note you also need to include Bootstrap-Vue's CSS after Bootstrap's CSS

**Comment by tmorehouse** [comment]
You should be using Bootstrap V4.1 or later CSS.
