### ISSUE TITLE
Better single component export convention

### ISSUE THREAD

**Issue by ur92** [bootstrap-vue/bootstrap-vue#2446]
When I import a single component, currently I can see that global registration or install as plugin are preferred over simple import as component and attaching into components object.
The way to import a single component is very inconvenient, not supported by JetBrains (for now) and I, personally, find it hard to use.
Current import practice: 
 ``` 
import bModal from 'bootstrap-vue/es/components/modal/modal';
import bForm from 'bootstrap-vue/es/components/form/form';

export default {
    name: 'myComponent',
    components: {
      'b-modal': bModal,
      'b-form': bForm
    }
}
```
I wish I could import in more clean and convenient way, like I use bootstrap in React or other frameworks.
```
import {bModal, bForm} from 'bootstrap-vue';

export default {
    name: 'myComponent',
    components: {
      bModal,
      bForm
    }
}
```

**Comment by tmorehouse** [comment]
We were thinking of improving the ways they can be imported, but the naming conventino would conflict with the current exported plugin name (i.e. we are using PascalCase for component names now, and the ComponentName conflicts with the exported PluginName).

This would introduce a breaking change for how people import Plugins vs Components vs Directives.  But might be a step in the right direction.

Webpack 4, introduces better tree shaking of modules, and we have marked most of the sub modules as Pure (with the exception of a few utility modules).

**Comment by ur92** [comment]
Thanks
