### ISSUE TITLE
webpack meta tag?

### ISSUE THREAD

**Issue by MatthewAlner** [bootstrap-vue/bootstrap-vue#245]
The required meta data isn't included in the head

It should contain this line

`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`

is there something I should be including? or should I be using something like [vue-meta](https://github.com/declandewet/vue-meta)

**Comment by pi0** [comment]
@MatthewAlner Yep, this is up to you setting up project. BootstrapVue just provides standard and stable  components :)
