### ISSUE TITLE
Unable to propagate delegate events

### ISSUE THREAD

**Issue by rainerborene** [bootstrap-vue/bootstrap-vue#2461]
Modal content has an event binding on click event that prevents propagation to other listeners. As you can see on the image, if I remove the `.modal-content` event directly on the Inspector it will work fine. I didn't find on the source the line responsible for this bug. How can I fix this issue?

![capture](https://user-images.githubusercontent.com/101501/51181628-caf7e600-18b2-11e9-8344-6c7d82903c55.PNG)

Edit: Here's the markup.

```erb
<b-modal id="notifications" ref="notificationsModal"
                            title="Notificações"
                            title-tag="h4"
                            modal-class="modal-dialog-vertical"
                            :hide-footer="true">

  <div class="list-group list-group-flush my--3">
    <div class="list-group-item px-0">
      <%= link_to "Marcar todos como lidos", mark_as_read_notifications_path,
                  class: "btn btn-block btn-light",
                  remote: true,
                  method: :patch %>
    </div>

    <%= render_notifications %>
  </div>
</b-modal>
```

**Comment by tmorehouse** [comment]
v2.0.0-rc.12 was just released today.
