### ISSUE TITLE
NPM dist `bootstrap-vue\es\components\modal\modal.js` stops propagation of events

### ISSUE THREAD

**Issue by galczo5** [bootstrap-vue/bootstrap-vue#2463]
Hi,
There is strange code in `bootstrap-vue\es\components\modal\modal.js:120`. 

```
      on: {
        focusout: this.onFocusout,
        click: function click(evt) {
          evt.stopPropagation();
          // https://github.com/bootstrap-vue/bootstrap-vue/issues/1528
          _this.$root.$emit('bv::dropdown::shown');
        }
      }
```

Can you provide solution that won't stop propagation of all events and stops only for `bv` events? 
It blocks other components, for example https://github.com/stfalcon-studio/stf-vue-select.
Emitting `bv::dropdown::shown` is quite confusing too when you don't have any dropdowns on modal.

**Comment by mosinve** [comment]
> Emitting bv::dropdown::shown is quite confusing too when you don't have any dropdowns on modal.
This is done for ensure closing all opened b-dropdowns on page.

**Comment by galczo5** [comment]
What about stoping propagation for all events? We use custom dropdown lib and there is problem when we want to hide dropdown clicking outisde.

**Comment by xShivan** [comment]
I'd also like to see this fixed or configured.

**Comment by tmorehouse** [comment]
This might be addressed in the latest `dev` branch.

**Comment by tmorehouse** [comment]
Duplicate #2461
