### ISSUE TITLE
Add RTL Support

### ISSUE THREAD

**Issue by aliyr** [bootstrap-vue/bootstrap-vue#2464]
I'm a Persian user of vue-bootstrap and I have the problem that each time I want to use this framework, I should repeatedly change styles to support RTL languages standards.

I strongly recommend you to add this feature to your template,

Or introduce a new package that gives us these deatures and standards

I'm glad to help to implement this feature

**Comment by jackmu95** [comment]
BootstrapVue depends on Bootstrap's CSS.
In order to add RTL here, it needs to be implemented there first.

There is already an issue for that https://github.com/twbs/bootstrap/issues/24807.

**Comment by tmorehouse** [comment]
Another option that **might** work is to run Bootstrap's (and BootstrapVue's) CSS through https://www.npmjs.com/package/postcss-rtl

**Comment by j209** [comment]
[bootstrap4 rtl sample](https://bootstrap.rtlcss.com/)
[bootstarp4 rtl repo](https://github.com/RTLCSS/bootstrap)
