### ISSUE TITLE
Use full lodash(-es) dependency (and not lodash.<method>)

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#2466]
Currently bootstrap-vue has dependencies on lodash.get and lodash.startcase. After distribution these dependencies are only needed when using the es build, as for umd and cjs they are included in the dist. When I bundle bootstrap-vue in my (nuxt) project, then according to webpack bundle analyzer these are both ~20KB in stat size and ~4KB in parsed size.

A side-effect of using lodash.get is that if someone already uses lodash in their project, then lodash.get (and mostly its internal dependencies) becomes duplicated. If I hack bootstrap-vue locally to use `from lodash/startCase` and `from lodash/get` instead, my vendors bundle size becomes 8KB smaller according to webpack.

By depending on the full lodash build we can rely on tree-shaking to only pick the parts of lodash we need for the whole project, without the need of duplicating internal lodash functions.

Btw, following this same logic I predict the bootstrap-vue dist sizes for umd and cjs builds will become ~4KB smaller as well if we do this.

Before:
![image](https://user-images.githubusercontent.com/1067403/51206149-b98cf900-1907-11e9-99b9-194d30278619.png)

After:
![image](https://user-images.githubusercontent.com/1067403/51206202-d0335000-1907-11e9-8a0f-721299c1fb45.png)

**Comment by tmorehouse** [comment]
Lodash get and startcase are used by b-table.

Note the original lodash lib is not tree shakeable.

**Comment by pimlie** [comment]
Fyi, I had a look at my prediction but it seems that the dist builds are actually only getting bigger when switching to lodash (~4KB) or lodash-es (~2KB). Not sure how that is possible, maybe someone more knowledgeable than me knows?

**Comment by pi0** [comment]
Lodash usage completely removed in #2523. You did an amazing discovery @pimlie :heart:
