### ISSUE TITLE
<b-form-*-feedback> pushing down append slot

### ISSUE THREAD

**Issue by ZeroThe2nd** [bootstrap-vue/bootstrap-vue#2470]
When creating a `<b-input>`, then adding a `<b-dropdown slot='append'>` together with a `<b-form-invalid-feedback>` in a `<b-input-group>`, the invalid feedback field pushes down the dropdown under it.

This can easily be seen [in this JSFiddle](https://jsfiddle.net/cm1y0kq2/1/).

I've managed to confirm the issue in:

- macOS 10.14.2 (18C54) | MacBook Pro 2015
    - Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
    - Safari Version 12.0.2 (14606.3.4)
- iOS 12.2.1 | Iphone 7
    - Safari (included version on this iOS version, can't find a version string)
- Android 9.0.0 | Xperia XZ1 Compact
    - Google Chrome Version 71.0.3578.99

It occurred on the current version of BootstrapVue ("2.0.0-rc.11" according to Yarn.lock), and the current unpkg version as can be seen in the JSFiddle.

**Comment by tmorehouse** [comment]
This is expected, as you have placed the feedback directly after the input. If you moved it after the dropdown then you'll have better results. Or use the feedback props or slots of b-form-group and use the state props to show it.

**Comment by ZeroThe2nd** [comment]
For future reference:

Moving the `<b-form-invalid-feedback>` tag below the dropdown did not work as intended. Using `<b-form-group invalid-feedback=''>` did work as intended.

This might be useful to add to the documentation somewhere.
