### ISSUE TITLE
Accordion sidemenu collapse after click on list group item

### ISSUE THREAD

**Issue by phlegx** [bootstrap-vue/bootstrap-vue#2473]
Hi!

I want to create a menu in my sidebar based on a _list-group_ with _list-group-items_. The first level list-group-items are accordion toggler. Inside an accordion collapse there are some list-group-items as sub-menu items. Here the code:

  <b-list-group role="tablist">

    <b-list-group-item tag="a" to="/" exact>
      Dashboard (First level)
    </b-list-group-item>

    <b-list-group-item tag="a" href="#" class="accordion-toggle" role="tab" v-b-toggle.organizations>
      Organizations (First level)
    </b-list-group-item>
    <b-collapse id="organizations" class="accordion-collapse" role="tabpanel" accordion="sidebar-accordion">
      <b-list-group-item tag="a" to="/organizations/categories">
        Organization categories
      </b-list-group-item>
      <b-list-group-item tag="a" to="/organizations">
        All organizations
      </b-list-group-item>
      <b-list-group-item tag="a" to="/organizations/new">
        Add organization
      </b-list-group-item>
    </b-collapse>
    ...

**Sidemenu**

- Dashboard (First level)
- Organizations (First level)
    - Organization categories
    - All organizations
    - Add organization
- ...other menu items

**The problem**

1. I click on **Dashboard (First level)**, all ok. Accordion closes if some accordion tab is active.
2. I click on **Organizations (First level)**, all ok. Accordion opens for this tab.
3. I click on **Organization categories**. Router does his work but the accordion collapse!

**What should be**

In 3. the accordion should be left open the tab **Organizations (First level)**. Why the accordion tab gets closed after click on **Organization categories** link? I have read the bootstrap-vue documentation but I cannot find a solution or reason. Can this be a bug?

**Versions**

**bootstrap-vue**: 2.0.0-rc.11
**vue**: 2.5.17
**vue-router**: 3.0.2

**Comment by tmorehouse** [comment]
If your collapse is inside a navbar, it will auto close when any link is clicked.
