### ISSUE TITLE
A lot of changes, but no new release?

### ISSUE THREAD

**Issue by sts-ryan-holton** [bootstrap-vue/bootstrap-vue#2476]
I'm wondering when the next version will be released as I'm keen to utilise the SCSS version of Bootstrap Vue, recently added upon one of my requests. I'm currenting using `rc.11` in my project as that last release was Q2 of 2018.

**Comment by sts-ryan-holton** [comment]
P.S: maybe it's time for a `rc.12`? or a full release

**Comment by sts-ryan-holton** [comment]
@tmorehouse  is it possible to get a release shipped earlier than this? I'm working on a production project and need certain features such as the SCSS support. I'm not keen on rewriting afterwards?

**Comment by vesper8** [comment]
also looking forward to next release.. there's been a ton of commits since the last one

but in the meantime, if you want to use the latest you can replace

```
    "bootstrap-vue": "^2.0.0-rc.11",
```

by

```
    "bootstrap-vue": "git://github.com/bootstrap-vue/bootstrap-vue.git#dev",
```

in your package.json

and you'll also need to replace

```
import BootstrapVue from 'bootstrap-vue';
```

by

```
import BootstrapVue from 'bootstrap-vue/src/index';
```

in your main.js

I'm not sure why this last change is needed but it's what I've been doing and it's working fine

**Comment by tmorehouse** [comment]
It is needed since the es directory is not built by default.

**Comment by huadong** [comment]
Typescript error:

> 'node_modules/bootstrap-vue/src/index.d.ts' is not a module.

`    "bootstrap-vue": "git://github.com/bootstrap-vue/bootstrap-vue.git#dev",`

`import BootstrapVue from 'bootstrap-vue/src/index';`

Looking forward to a new release.

**Comment by JamesB797** [comment]
+1 for new release, looking forward to the middle-click event on b-table

**Comment by dzcpy** [comment]
Keep your good work! I'm also looking forward to the new release with scss support!

**Comment by tmorehouse** [comment]
New v2.0.0-rc12 release will be coming out Feb 14, 2019
