### ISSUE TITLE
Error in example vee-validate with bootstrap-vue

### ISSUE THREAD

**Issue by sowinski** [bootstrap-vue/bootstrap-vue#2484]
Hi,

is this example still correct? I can not run this example:
[https://bootstrap-vue.netlify.com/docs/reference/validation/](https://bootstrap-vue.netlify.com/docs/reference/validation/)

`<b-button type="submit" variant="primary" :disabled="form.errors.any()">Submit</b-button>`
It seems like that this line is wrong, I get this error:
```
TypeError
_vm.form.errors.any is not a function
```

I am using nuxt and this is how I added vee-validator:

#nuxt.config.js
```
  plugins: [
   {src: '~/plugins/vee-validate.js'}
  ],
```
#/plugings/vee-validate.js
```
import Vue from 'vue'
import VeeValidate from 'vee-validate'

Vue.use(VeeValidate, {
  inject: true,
  fieldsBagName: 'veeFields'
})

```

I am not sure if my configuration is wrong or the exmaple.

**Comment by artn** [comment]
By Changing `form.errors.any()` to `errors.any()`, the error message you pointed can be fixed.

**Comment by mosinve** [comment]
If you look at example one more time, you'll see difference with your code:
`<b-button type="submit" variant="primary" :disabled="$v.form.$invalid">Submit</b-button>`
vs
`<b-button type="submit" variant="primary" :disabled="form.errors.any()">Submit</b-button>`
