### ISSUE TITLE
Please support custom switches

### ISSUE THREAD

**Issue by fancydev18** [bootstrap-vue/bootstrap-vue#2486]
Custom switches (and other custom form elements) 
https://getbootstrap.com/docs/4.2/components/forms/#switches

aren't listed at https://bootstrap-vue.js.org/docs/

Would you please add support for these, including how to set custom switch colors?
https://stackoverflow.com/questions/29575437/how-to-customize-bootstrap-switch-color
(aiming to use red/green instead of gray/blue for off/on)

Thanks

**Comment by tmorehouse** [comment]
Check the latest dev branch docs. Switch style checkboxes are supported.

**Comment by fancydev18** [comment]
Would you please document how to set custom switch colors?
https://stackoverflow.com/questions/29575437/how-to-customize-bootstrap-switch-color
(aiming to use red/green instead of gray/blue for off/on)

**Comment by tmorehouse** [comment]
That would be using custom SCSS theming of Bootstrap V4.3 (see the theming section from the get bootstrap.com site). And probably adding in a few custom classes to place on the switches.
