### ISSUE TITLE
Styles of Tooltip on official page

### ISSUE THREAD

**Issue by dbsimeonov** [bootstrap-vue/bootstrap-vue#2492]
I would like just to inform you that on your official page under [Tooltip component](https://bootstrap-vue.js.org/docs/components/tooltip/), you can see that they are not styled as expected. That's in section `Positioning `. Would be good to fix that small issue.

The styles in Bootstrap we are using its working all good.

**Comment by tmorehouse** [comment]
Fixed in latest dev branch.

![image](https://user-images.githubusercontent.com/2781561/52611530-53d75280-2e5c-11e9-97d5-494f12c528c0.png)
