### ISSUE TITLE
Invalid prop: type check failed for prop "value" in BFormInput

### ISSUE THREAD

**Issue by ypnos** [bootstrap-vue/bootstrap-vue#2493]
Works as expected in rc11, but not in current dev. I have a simple input, e.g.

```vue
<b-form-input :id="domId + '-amount'"
    type="number" v-model="amount" required min="0" max="100" step="any"
></b-form-input>
```

Amount is defined as (this is in a component):
```js
data: function () {
    return {
        amount: 0
    };
},
```

This, when using dev, leads to:
```
[Vue warn]: Invalid prop: type check failed for prop "value". Expected String with value "0", got Number with value 0.

found in

---> <BFormInput>
       <BModal>
         <Deposit>
           <Root>
```

This also happens when I use `v-model.number="amount"`. In that case, any user input will also trigger the Vue warning.

- Arch Linux, current Chromium and Firefox, Vue 2.5.22 (and older), Bootstrap-Vue dev
- Sorry no testcase just yet, as the playground kills my browser tab every time and for now I gave up.

**Comment by tmorehouse** [comment]
Note to cannot use the Vue `.number` modifier on v-model with custom components, it has weird side effects.

**Comment by clararichter** [comment]
@tmorehouse could you elaborate what it means to "use the `number` prop to convert to a native number object"? Thank you!

**Comment by tmorehouse** [comment]
The number prop for b-form-input works like the native .number modifier for v-model (although the native Vue modifier does not work on custom components)

Internally the value is maintained as a string on the input, but the value returned to your app is converted to a number. When you send a number to the v-model it will convert it back to a string for the input element.

**Comment by ypnos** [comment]
@tmorehouse What is the relation between this issue and #2582 / #2583?

**Comment by SamiUrias** [comment]
I was facing this issue in the version 2.0.0-rc.11 but I updated to **2.0.0-rc.14** and that issue was fixed

**Comment by jongbonga** [comment]
I'm still having the issue even with the `number` prop
