### ISSUE TITLE
[Question] jQuery dependency missing

### ISSUE THREAD

**Issue by treaves** [bootstrap-vue/bootstrap-vue#2494]
Is jQuery actually needed as a dependency?

I see this has been discussed in a couple of places, including #975.  In that thread the assertion is made the bootstrap does not actually require jQuery and that there is an issue with their packaging.  

However the current Bootstrap documentations says "Many of our components require the use of JavaScript to function. Specifically, they require jQuery, Popper.js, and our own JavaScript plugins. "  So if Bootstrap claims it's needed, I'd think it's needed.

I've just added bootstrap-vue, and packaging fails with the missing jQuery dependency transitively brought in from bootstrap@4.2.1 brought in from bootstrap-vue@2.0l0-rc11.

So I'm trying to understand why bootstrap-vue claims in the documentation and the threads here that jQuery is not needed.  Is the Bootstrap documentation wrong?

**Comment by tmorehouse** [comment]
BootstrapVue only depends on Bootstrap V4  Css/scss, and does not require jQuery to be part of your project (as jQuery is not used by BootstrapVue)

**Comment by treaves** [comment]
Thanks for the reply.

So you've reimplemented the modal and tooltip to not need jQuery?  Or, again, is Bootstraps documentation incorrect.

**Comment by treaves** [comment]
To be clear, myself and other users are put int he middle here; one site saying it's needed, and another saying it's not.  To package we must include it.

So there has to be a defect in either bootstrap-vue or in bootstrap.  And if it's the later, the users of bootstrap-vue shouldn't be the ones fighting the battle with the bootstrap team to fix their dependencies.

**Comment by tmorehouse** [comment]
BootstrapVue has rewritten modal, etc, using Vue.JS so that it uses Vue features.

Bootstrap Vue has some additional custom SCSS that needs bootstrap's scss variables.

**Comment by treaves** [comment]
Ah.  O.K.  That explains that. Of course, we're still left with the actual issue of the package managers all don't know that, and require jQuery because of Bootstrap.

I'm reluctant to use an 'ignore dependencies' approach, as what might be missed as a user adds additional dependencies.

**Comment by tmorehouse** [comment]
Unfortunately, there is no simple way to add just the Bootstrap V4.3 SCSS as a dependency.

**Comment by jackmu95** [comment]
Bootstrap V5 will fix this by dropping jQuery at all.
Util then we are stuck as jQuery as dependency.

**Comment by peterkajan** [comment]
There is an official bootstrap css only package https://www.npmjs.com/package/bootstrap-css-only
Shouldn't bootstrap-vue depend on that one instead?

**Comment by tmorehouse** [comment]
@peterkajan I wouldn't call it official as it is not under the https://github.com/twbs/ official repos.

It is created by a 3rd party https://github.com/fyockm/bootstrap-css-only , and would rely on that repo being updated when new Bootstrap versions are updated.

Since it is not official, we can't rely on it being up to date.

**Comment by tmorehouse** [comment]
v5 of bootstrap (when released) will not depend on jQuery.

**Comment by peterkajan** [comment]
Just for info, here is related issue from bootstrap https://github.com/twbs/bootstrap/issues/24078
