### ISSUE TITLE
b-button button-secondary

### ISSUE THREAD

**Issue by devstu** [bootstrap-vue/bootstrap-vue#2495]
`<b-button class="btn btn-outline-danger">Testing</b-button>`

is rendering like this: 

`<button type="button" class="btn btn btn-outline-danger btn-secondary">Testing</button>`

Note the btn-secondary.  I think this is a bug.

**Comment by tmorehouse** [comment]
Use the variant prop to set the button style. Remember that bootstrap-vue automatically places the base classes for you.

Set `variant="outline-danger"` and none of the other classes.
