### ISSUE TITLE
v-b-scrollspy:nav-scroller + NuxtJS. Can not read property scrollTop ... 

### ISSUE THREAD

**Issue by kyriediculous** [bootstrap-vue/bootstrap-vue#2499]
Hi,

I'm trying to use vue-bootstrap with nuxtJS.

As good as everything works as expected except for my navbar, which sets background from transparant to colored when the user scrolls as well as use scrollspy to detect active state. 

There's two main scenario's: 

When I use `v-b-scrollspy:nav-scroller` , I get errors like `"scrollToTop is undefined"`

When I use `v-b-scrollspy="70"`, it works. 

Probably because the first scenario needs to get the height offset from the window, so window might be undefined, despite both methods pointing at body as scroll element. 

However this should not be the case as vue-bootstrap scollspy is excluded from SSR and the navbar is wrapped in `<no-ssr>` tags

Vue-bootstrap is imported both as a module and v-b-scrollspy is imported seperately in plugins as a directive as well. 

How to use this correctly? 

nuxt.config.js
```
  plugins: [
    { src: '~/plugins/owl-carousel.js', ssr: false },
    { src: '~/plugins/scrollspy.js', ssr: false }
  ],
modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    // Doc: https://bootstrap-vue.js.org/docs/
   ['bootstrap-vue/nuxt', { css: false }],
    //'bootstrap-vue/nuxt',
    '@nuxtjs/pwa'
  ],
  build: {
    transpile: ['bootstrap-vue'],
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
```

scrollspy.js 
```
import Vue from 'vue'
import vBScrollspy from 'bootstrap-vue/es/directives/scrollspy/scrollspy'
Vue.directive('b-scrollspy', vBScrollspy)
```

**Comment by tmorehouse** [comment]
Note that no-ssr still "renders" the content internally (but doesn't render the html, not until the parent is mounted).

This might be why you are seeing the error.

**Comment by kyriediculous** [comment]
Do you have an tips for a not too hacky solution? 

I'm not that familiar with server side rendering. 

I'm thinking of someting like this, but I'm not sure how to add a directive to a component or element. I know it is possible for class bindings. 

inside Navbar.vue child component `mounted`hook :
```
        window.onNuxtReady(app => {
           //add v-b-scrollspy:nav-scroller directive to b-navbar component
        })
```

suggestions?

Thanks.

**Comment by kyriediculous** [comment]
Ah I'll figure it out using this: 
https://github.com/nuxt/nuxt.js/issues/188

**Comment by YannDanthu** [comment]
@kyriediculous could you explain how you solved it ?

I can't figure out how to make scrollspy work.
Where did you put the `v-b-scrollspy` attribute ? I'm using a `b-navbar`, what's your usecase ?

thanks for your feedback

**Comment by kyriediculous** [comment]
I didn't actually solve it, I iirc. Or at least I didn't figure out the scrollToTop is undefined part. 

The scroll spy active states work for me, but smooth scrolling does not. 

I'd have to pull the heroku repo to tell you more if it holds the canonical origin (I do not have a local copy)

**Comment by derevandal** [comment]
I resolve this issue using this code in my navbar:
```js
mounted() {
    this.$el.setAttribute('v-b-scrollspy:body.offset', '75')
}
```

**Comment by jay8t6** [comment]
@kyriediculous you have to use id="nav-scroller" instead of class
