### ISSUE TITLE
How to change the href in b-nav-item

### ISSUE THREAD

**Issue by oopp1800** [bootstrap-vue/bootstrap-vue#25]
I tried to edit like this: 
```
<b-nav-item :link="url"></b-nav-item>
```
But in the output html, the href is still `/#`
Is there any way I can edit the href? Or did I use it a wrong way?

**Comment by ben-lei** [comment]
https://bootstrap-vue.github.io/#nav

**Comment by pi0** [comment]
I'm closing this issue as seems to be inactive. Please feel free to reopen if was needed :)
