### ISSUE TITLE
from-group remove <div> wrapper if not required.

### ISSUE THREAD

**Issue by phlegx** [bootstrap-vue/bootstrap-vue#2500]
Hi!

Using this simple example I will show what **bootstrap-vue** renders with `<b-form-group>` ([see docs](https://bootstrap-vue.js.org/docs/components/form-group)):

```html
  <b-form-group id="test1" label="Test" label-for="input1">
    <b-form-input id="input1" v-model.trim="name"></b-form-input>
  </b-form-group>
```
Output is the following:

```html
<div id="test1" role="group" aria-labelledby="..." class="b-form-group form-group">
  <label id="..." for="input1" class="col-form-label pt-0">Test</label>
  <div class="">
    <input id="input1" type="text" value="" class="form-control"></div>
  </div>
</div>
```

But why render a `<div>` wrapper for `<input>` if not required? Reading the [docs of Bootstrap 4](https://getbootstrap.com/docs/4.0/components/forms/#overview) a `<div>` wrapper is not required! So, **bootstrap-vue** should remove this wrapper or let the developer choose with a property (and also the style class) if a wrapper should be set or not.

Here an example how Bootstrap defines a from group:

```html
<div id="test1" role="group" aria-labelledby="..." class="b-form-group form-group">
  <label id="..." for="input1" class="col-form-label pt-0">Test</label>
  <input id="input1" type="text" value="" class="form-control"></div>
</div>
```

I use the latest release of **bootstrap-vue**.

**Comment by tmorehouse** [comment]
BootstrapVue doesn't know if you are only placing a single input or not, so it has to render a wrapper element, as well it needs a wrapper when the form group switches from vertical to horizontal layout.

**Comment by tmorehouse** [comment]
You can always render your own form group with html elements, as form-group is just a universal helper component.
