### ISSUE TITLE
Error: [vuex] do not mutate vuex Table Component

### ISSUE THREAD

**Issue by periscuelo** [bootstrap-vue/bootstrap-vue#2501]
Windows 10
Fire Fox Developer Edition
Bootstrap-Vue v2.0.0-rc.11

When we use the component Table with Row details support with Vuex strict, this error is showed:

```
Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] do not mutate vuex store state outside mutation handlers."
```
To see this error in console, just click in detail button, using a vuex data by getters in :items of b-table.

[JSFiddle](https://jsfiddle.net/m7034jvx/)

Have one fix or workaround for this?
Thanks.

**Comment by TheoBP** [comment]
This happens because the table component is trying to update the Vuex state directly, which is not allowed in strict mode. You would have to use a mutation:

https://jsfiddle.net/t1fzL5s6/

**Comment by periscuelo** [comment]
It's a good workaround. But if you have data from one end point you will need make a forEach to add _showDetails: false in the data.

**Comment by TheoBP** [comment]
It's not a workaround though, it's how vue works. A property needs to be defined in order to be reactive. This is already mentioned in the docs.

> Note: _If manipulating the _showDetails property directly on the item data (i.e. not via the toggleDetails function reference), the _showDetails propertly must exist in the items data for proper reactive detection of changes to it's value. Read more about Vue's reactivity limitations._

**Comment by periscuelo** [comment]
> It's not a workaround though, it's how vue works. A property needs to be defined in order to be reactive. This is already mentioned in the docs.
I know how vue works and i read the docs. But in no time I set in my code something to directly change the store of my vuex. This was done by the b-table component. That's the motive why i said "workaround". If I had coded, it would certainly have changed the state of the application by mutation

**Comment by TheoBP** [comment]
> > This happens because the table component is trying to update the Vuex state directly, which is not allowed in strict mode. You would have to use a mutation:
> 
> Now i understand. Sorry for the late understanding. The b-table component try to automatic add `_showDetails` in the state of vuex and that's the motive to get a vuex error. Could not this be improved? Perhaps giving an option with a props for example, for it not to do this automatically or showing an example with vuex in docs? For me, it was not so intuitive that `this is how it works`. Not that my opinion matters....
> 
> Thank you for the solution and explanation.

Yeah, maybe an example with vuex would be good.

I wouldn't keep the table items in a vuex store though, just the parameters that allow you to recreate a table page: perPage, currentPage, filter, sortBy, sortDesc.

**Comment by periscuelo** [comment]
When you need share data coming from an endpoint, with multiple components, What you use? Ajax request for obtain same data ever as you need? LocalStorage? Vuex is good for this situations.
