### ISSUE TITLE
Can't use v-bind:value and v-on:input instead of v-model in b-form-input

### ISSUE THREAD

**Issue by tylrob** [bootstrap-vue/bootstrap-vue#2502]
Hi team,

I've run into a snag with v-model and b-form-input. I want to use the v-bind:value and v-on:input pattern instead of v-model so that I can use props from a parent component as the value and emit changes back to the parent, as described in the Vue docs (and as warned in the console when I try to change props directly).

But when I use v-bind:value and v-on:input with b-form-input, nothing seems to happen.

Here is a codepen that simplifies things without a parent/child component and it still doesn't work.

https://codepen.io/anon/pen/omBLPJ

Is there a known workaround for this scenario? Thanks!

**Comment by tmorehouse** [comment]
Which version of BootstrapVue are you using?

**Comment by tylrob** [comment]
Great, thank you @mosinve for the course-correction. I ended up with:

`<b-form-input v-bind:value="name" @input="$emit('update:name', $event)"></b-form-input>`

to emit my value back up to the parent, and I'm back on track. Thanks!
