### ISSUE TITLE
Form Textarea doesn't work without v-model

### ISSUE THREAD

**Issue by sts-ryan-holton** [bootstrap-vue/bootstrap-vue#2503]
Hi, I'm trying to use the Form Textarea without a v-model as my project doesn't require the v-model. However, without this I cannot type in the textarea, every time I enter a character the textarea appears to have some JS which then instantly removes the character. How can I get around this?

Ref: https://bootstrap-vue.js.org/docs/components/form-textarea

**Comment by tmorehouse** [comment]
This should be fixed in the latest `dev` branch.
