### ISSUE TITLE
Adding checked attribute to b-form-checkbox doesn't work?

### ISSUE THREAD

**Issue by sts-ryan-holton** [bootstrap-vue/bootstrap-vue#2504]
If I add any of the following to the `b-form-checkbox` the checkbox doesn't seem to become checked. How can I get this to become checked without a `v-model`:

Tried the following:

```
:checked="true"
v-bind:checked="true"
:checked="0"
:checked="1"
checked
```
non of these work

**Comment by tmorehouse** [comment]
`checked` is the v-model, and per Vue docs, the data model is the source of truth. Vue ignores the `checked` attribute (see: https://vuejs.org/v2/guide/forms.html#Basic-Usage)

> `v-model` will ignore the initial `value`, `checked` or `selected` attributes found on any form elements. It will always treat the Vue instance data as the source of truth. You should declare the initial value on the JavaScript side, inside the data option of your component.

You will need to set a `value` to do waht you are tying to do:

```html
 <b-form-checkbox value="1" checked="1">Checked</b-form-checkbox>
```

`value` will need to be identical to `checked`
