### ISSUE TITLE
JS.Downloader.Agent Maleware Found on all stable build

### ISSUE THREAD

**Issue by hardik797** [bootstrap-vue/bootstrap-vue#2505]
there is js.downloader.agent maleware in all the stable release of bootstrap-vue repository, kindly check and fix it asap.

**fix : -**

1. remove old bootstrap-vue folder from your node_modules or remove whole node_modules folder from your project clear npm cache.

2. switch your bootstap-vue version to `2.0.0-rc.11` in your package.json file

3. re install your packages using `npm install`  done.

**Note :  check error screenshot while uploading build using Cpanel, it might not giving you the same error because you using filezilla or any other method to transfer file, but it is affected check `npm audit` to verify it.**

![image](https://user-images.githubusercontent.com/17494662/52101722-f6910500-2602-11e9-84c1-276b8d38982e.png)

Regard,
Hardik Karmur

**Comment by hirenvadalia** [comment]
@hardik797 I don't think bootstrap-vue's build contains any virus based on the message on an attached image it looks like your zip file (chemist_live.zip) contains the virus.

**Comment by hardik797** [comment]
> @hardik797 I don't think bootstrap-vue's build contains any virus based on the message on an attached image it looks like your zip file (chemist_live.zip) contains the virus.

check the note and verify it using `npm audit`.
