### ISSUE TITLE
pagination-nav: when use `use-router="true"` then click nav button not working

### ISSUE THREAD

**Issue by nguyentrongthanh** [bootstrap-vue/bootstrap-vue#2506]
- Operating system and version: Window 10 Pro
- Browser and version: Chorome 71.0.3578.98
- Version of Bootstrap-Vue: 2.0.0-rc.11

**Comment by tmorehouse** [comment]
Could you provide an example of your markup/code?

**Comment by tmorehouse** [comment]
Closing as `stale` due to lack of example/reproduction
