### ISSUE TITLE
SSR mismatch using b-dropdown with slot 

### ISSUE THREAD

**Issue by tiphedor** [bootstrap-vue/bootstrap-vue#2510]
Hello, 

When using `b-dropdown` with a custom slot, like this (straight from the doc) : 

````
<b-dropdown variant="link" size="lg" no-caret>
	<template slot="button-content">
		Click Me !
	</template>
	<b-dropdown-item to="/whatever">
		Link 1
	</b-dropdown-item>
	<b-dropdown-item to="/nowhere">
		Link 2
	</b-dropdown-item>
</b-dropdown>
````

I get the following SSR error : 

`
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
`

Environment: 

- macOS 10.13
- nuxt 2.3.4
- bootstrap-vue 2.0.0-rc.11

Is there a workaround ? Thanks ! :)

**Comment by tmorehouse** [comment]
It sounds like something may be stripping out the extra whitespace around the text content inside your dropdown item.

**Comment by tmorehouse** [comment]
Could you verify the `view source` of the loaded page verses the `innerHTML` of the browser rendered content?

Do you happen to have an HTML minimizer running between the Vue server renderer and the client (i.e. http server module, or something like CloudFlare with HTML minification enabled)?

**Comment by jschoedt** [comment]
Hi I think @tiphedor is right. I have this issue with v 2.0.3. But it is a combination of elements and not the template (in my case).
This template:
```
<template>

        <b-list-group >
            <b-list-group-item button>
                    <b-dropdown variant="link" no-caret>
                        <b-dropdown-item-button >
                            Edit
                        </b-dropdown-item-button>
                    </b-dropdown>
            </b-list-group-item>
        </b-list-group>

</template>
```
Is rendered as:
```
    <div class="list-group" data-v-a3289284="">
        <button type="button" class="list-group-item list-group-item-action" data-v-a3289284="">
            <div class="dropdown btn-group b-dropdown" data-v-a3289284=""><!----></div>
        </button>
        <button aria-haspopup="true" aria-expanded="false" type="button" class="btn dropdown-toggle btn-link dropdown-toggle-no-caret"></button>
        <ul role="menu" tabindex="-1" class="dropdown-menu">
            <li role="presentation" data-v-a3289284="">
                <button role="menuitem" type="button" class="dropdown-item">
                    Edit
                </button>
            </li>
        </ul>
    </div>
    </div>
```
Note the extra closing div tag.

My workaround is to use a `</no-ssr>` around the dropdown.

**Comment by tmorehouse** [comment]
@jschoedt 

There are issues with your markup.

You are telling `list-group-item` to render as a button element (via the `button` prop), and then placing a dropdown inside of that button (which teh dropdown includes a button).  So it is creating invalid HTML markup (you can't have a `<button>` inside of another `<button>), which the browser is "fixing" when it tries to hydrate.

```html
<template>
  <b-list-group >
    <b-list-group-item class="p-0">
      <b-dropdown variant="link" no-caret text="DDown" class="w-100" toggle-class="text-left">
        <b-dropdown-item-button >
          Edit
        </b-dropdown-item-button>
      </b-dropdown>
    </b-list-group-item>
  </b-list-group>
</template>
```

**Comment by jschoedt** [comment]
You are right. Thanks for pointing that out. Removing the button attribute fixed it.
