### ISSUE TITLE
b-table Hoover Event

### ISSUE THREAD

**Issue by abhi-cognitivo** [bootstrap-vue/bootstrap-vue#2515]
Hi,

I am developing a minimalist table with bootstrap-vue, and I need to be able show the action buttons for a particular row only when that row is being hoovered. All other buttons belonging to other rows should be hidden from view.

Looking through the docs, I noticed that the Hoover is not a property but an event. How would I go about doing this? Any suggestions?

**Comment by ddweber** [comment]
I´m not as skilled as the authors of bootstrap-vue but i would do it like that:
- listen to the row-hovered event
-  store the hovered item
- trigger table refresh and only show button when the stored item equals the current row-item

Sample data is copied from the b-table docs.. Try it on jsfiddle, but you have to import the ressources first.

```html
<div id='app'>
  <b-table ref="table" striped hover :items="items" :fields="fields" @row-hovered="rowHovered">
  <template slot="controls" slot-scope="row">
    <b-button size="sm" v-show="isHovered(row.item)" @click="buttonClicked(row.item)">Click me</b-button>
  </template></b-table>
</div>
```

```javascript
window.onload = function() { new Vue({
	el: '#app',
  data () {
    return {
      // Note 'isActive' is left out and will not appear in the rendered table
      fields: {
        controls: {
          label: 'Controls'
        },
        last_name: {
          label: 'Person last name',
          sortable: true
        },
        first_name: {
          label: 'Person first name',
          sortable: false
        },
        foo: {
          // This key overrides `foo`!
          key: 'age',
          label: 'Person age',
          sortable: true
        },
        city: {
          key: 'address.city'
        },
        'address.country': {
          label: 'Country'
        }
      },
      items: [
        { isActive: true, age: 40, first_name: 'Dickerson', last_name: 'Macdonald', address: { country: 'USA', city: 'New York' } },
        { isActive: false, age: 21, first_name: 'Larsen', last_name: 'Shaw', address: { country: 'Canada', city: 'Toronto' }},
        { isActive: false, age: 89, first_name: 'Geneva', last_name: 'Wilson', address: { country: 'Australia', city: 'Sydney' } },
        { isActive: true, age: 38, first_name: 'Jami', last_name: 'Carney', address: { country: 'England', city: 'London' } }
      ],
      hoveredRow: null
    }
  },
  methods: {
    buttonClicked(item){
      alert("Clicked on item" + JSON.stringify(item));
    },
    rowHovered(item){
      this.hoveredRow = item;
      this.$refs.table.refresh();
    },
    isHovered(item){
      if(item == this.hoveredRow){
        return true;
      }
      return false;
    }
  }
})
}
```

**Comment by abhi-cognitivo** [comment]
thanks @ddweber ! It works, although I feel it can be implemented into future updates and exposed as a property as well as an event!

**Comment by tmorehouse** [comment]
It would be easier to use css to hide/show elements based on the `:hover` CSS selector:

```css
.b-table > body > tr:not(:hover)  .show-when-hovered {
  display: none;
}
```

Adding the class `show-when-hovered` to the action buttons/links will make the elements hidden until hovered.

**Comment by abhi-cognitivo** [comment]
thanks @tmorehouse , a better solution would be CSS as it can safely handle screen sizes or better yet pointer types. Here is my final approach:

```
@media (pointer:fine) {
    .b-table > tbody > tr:not(:hover) .show-when-hovered {
      display: none;
    }
}
```

This allows fine pointer devices such as a PC to hide the buttons and show upon hover, but show it at all times on all other devices that have corse or no pointers.
