### ISSUE TITLE
Bootstrap vue tooltips error in table after filter

### ISSUE THREAD

**Issue by MuhajirulFaqih** [bootstrap-vue/bootstrap-vue#2516]
I am use tooltips in button inside table. But if my table filtered and found one data, my button tooltips is error (pointer always blink). Is there someone experiencing the same problem?

**Comment by tmorehouse** [comment]
Try adding a unique `key` to your tooltip trigger element (or to a wrapper element around your cell content).

This should be addressed in the latest `dev` branch.
