### ISSUE TITLE
add `active-class` prop to <b-tabs>

### ISSUE THREAD

**Issue by allw1994** [bootstrap-vue/bootstrap-vue#2518]
Just like there is an ability to set nav-class on a b-tab could we not also have active-class with similar options.

e.g. at the moment I can use by default 
````
<b-tabs :nav-class="customvariant">
    <b-tab title="tab">Tab Content</b-tab>
</b-tabs>
````

Does it not make sense to also have something like:
````
<b-tabs :nav-class="customvariant" :active-class="customactive">
    <b-tab title="tab">Tab Content</b-tab>
</b-tabs>
````

Hope this makes sense?

**Comment by tmorehouse** [comment]
This might be something that could be added.

Since the active `tab` button has the Bootstrap class `active` applied to it (when active), you can use custom CSS to target the tab:

```html
<b-tabs class="foobar">
  <b-tab title="Tab 1">Tab One</b-tab>
  <b-tab title="Tab 2">Tab Two</b-tab>
</b-tabs>
```

```css
.tabs.foobar .nav .nav-item.active {
  /* custom styles here */
}
```

**Comment by Soviut** [comment]
This would bring the props in line with the fact that router links, displayed as tabs, have an `active-class` prop.

https://bootstrap-vue.js.org/docs/reference/router-links/#active-class
