### ISSUE TITLE
Make dropdown focus optional

### ISSUE THREAD

**Issue by tomlankhorst** [bootstrap-vue/bootstrap-vue#2520]
Currently, opening `<dropdown>` initiates a focus on `$nextTick` on the first menu element. 
I have different requirements for focus behaviour and wanted to focus on a different element. 

Is there support for adding a prop to the element that makes the focus behaviour optional? 

[Like this](https://github.com/bootstrap-vue/bootstrap-vue/compare/dev...tomlankhorst:focus-option?expand=1). 
```diff
diff --git a/src/mixins/dropdown.js b/src/mixins/dropdown.js
index 3dc1158b..152113c5 100644
--- a/src/mixins/dropdown.js
+++ b/src/mixins/dropdown.js
@@ -93,6 +93,11 @@ export default {
     popperOpts: {
       // type: Object,
       default: () => {}
+    },
+    focus: {
+      // Focus the menu when shown
+      type: Boolean,
+      default: true
     }
   },
   data() {
@@ -199,7 +204,9 @@ export default {
       this.$emit('shown')

       // Focus on the menu container on show
-      this.$nextTick(this.focusMenu)
+      if (this.focus) {
+        this.$nextTick(this.focusMenu)
+      }
     },
     hideMenu() {
       this.whileOpenListen(false)
```

**Comment by tmorehouse** [comment]
In the latest dev branch, rather than focusing the first item dropdown now focuses the menu container.

You can listen for the dropdown `shown` event and trigger focus on a a particular element if you wish.

**Comment by tomlankhorst** [comment]
Okay, that's better imho. But the focus is called after `$emit('shown')` on `$nextTick`, so any focus set in the `shown` listener will be overruled by `this.$nextTick(this.focusMenu)`.

**Comment by tmorehouse** [comment]
We may need to adjust the ordering. The nextTick is probably just a leftover from previous versions.

**Comment by tomlankhorst** [comment]
That would be very helpful.

Op vr 8 feb. 2019 om 17:41 schreef Troy Morehouse <notifications@github.com
