### ISSUE TITLE
b-form b-button-group b-button submit bug

### ISSUE THREAD

**Issue by TonBits** [bootstrap-vue/bootstrap-vue#2521]
onSubmit is called even when the button is not a submit type. This bug occurs ONLY when you use the combination of b-form, b-button-group, a b-button inline click statement (not a function).

	<template>
		<b-form @submit="onSubmit">
			<b-button-group v-if="edit == false">
				<b-button @click="edit = true">Edit</b-button>
			</b-button-group>
			<b-button-group v-else>
				<b-button type="submit" variant="primary">Save</b-button>
				<b-button @click="edit = false">Cancel</b-button>
			</b-button-group>
		</b-form>
	</template>
	<script>
	export default {
	  name: 'home',
	  data: () => ({
		edit: false,
		name: ''
	  }),
	  methods: {
		onSubmit () {
		  alert('onSubmit Called')
		},
		onButtonClick () {
		  alert('onButtonClick called')
		}
	  }
	}
	</script>

Though I am able to find a solution by either creating a function inside the click method instead of an inline assignment, or removing the b-button-group condition and move it to the button level 
e.g.

	<b-form @submit="onSubmit">
		<b-button-group>
			<b-button v-if="edit == false" @click="edit = true">Edit</b-button>
			<b-button v-if="edit == true" type="submit" variant="primary">Save</b-button>
			<b-button v-if="edit == true" @click="edit = false">Cancel</b-button>
		</b-button-group>
	</b-form>

This use to have a bug on rendering the edge buttons when some buttons are hidden in a b-button-group causing to render sharp edges, but it seems fixed on the recent version.

This occurred when I recently updated to the latest version. The code block with multiple b-button-group on a conditional if-else used to work before.

windows 7, chrome Version 72.0.3626.96
Package Details
    "axios": "^0.16.2",
    "bootstrap-vue": "^2.0.0-rc.11",
    "vue": "^2.6.4",
    "vue-router": "^2.3.1"

**Comment by jackmu95** [comment]
Preventing the event on the edit button should solve your problem.

```vue
<template>
  <b-form @submit="onSubmit">
    <b-button-group v-if="!edit">
      <b-button @click.prevent="edit = true">Edit</b-button>
    </b-button-group>
    <b-button-group v-else>
      <b-button type="submit" variant="primary">Save</b-button>
      <b-button @click="edit = false">Cancel</b-button>
    </b-button-group>
  </b-form>
</template>

<script>
export default {
  name: 'home',
  data: () => ({
    edit: false,
    name: ''
  }),
  methods: {
    onSubmit () {
      alert('onSubmit Called')
    }
  }
}
</script>
```

**Comment by tmorehouse** [comment]
`b-button` previously didn't have a deafult "type" attribute, which has been fixed in the latest `dev` branch (defaults to `type="button"`.

Some browsers, if no type provided, would treat a button as a submit button.

You could try adding attribute `type="button" to `b-button` and see if that fixes the issue.

**Comment by jackmu95** [comment]
@tmorehouse I tested it in the current playground and the issue exists.

**Comment by tmorehouse** [comment]
Interesting...

**Comment by tmorehouse** [comment]
What about adding unique `key` to each button (or button-group), so that Vue doesn't re-use the DOM nodes?

**Comment by jackmu95** [comment]
@tmorehouse Tried it in the [Playground](https://bootstrap-vue.js.org/play) and it works 👍 

```vue
<template>
    <b-form @submit="onSubmit">
    <b-button-group v-if="!edit" key="button-group-1">
      <b-button @click="edit = true">Edit</b-button>
    </b-button-group>
    <b-button-group v-else key="button-group-2">
      <b-button type="submit" variant="primary">Save</b-button>
      <b-button @click="edit = false">Cancel</b-button>
    </b-button-group>
  </b-form>
</template>

<script>
export default {
  name: 'home',
  data: () => ({
    edit: false,
    name: ''
  }),
  methods: {
    onSubmit () {
      alert('onSubmit Called')
    }
  }
}
</script>
```
