### ISSUE TITLE
Feature request: Raw HTML for breadcrumbs

### ISSUE THREAD

**Issue by krgaurav1992** [bootstrap-vue/bootstrap-vue#2522]
Can you please add support for raw html so that icons can be inserted with breadcrumbs ?

What I want is:
`{ text: '<span class="lnr lnr-home"></span>', to: '/' }`

**Comment by pi0** [comment]
Thanks for suggestion @krgaurav1992. Will be possible in next release.

**Comment by krgaurav1992** [comment]
Thank you so much :)
