### ISSUE TITLE
b-form-fieldset wrong class on feedback form-text  div

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#253]
The feedback text in the b-form-fieldset template has class `.text-muted`, but really should be `.form-control-feedback` to visually convey the `inputState`, and should have an ARIA role of `alert`

Current template:
```html
<template>
  <div :class="['form-group','row',inputState]">
    <label :for="target" v-if="label" :class="['col-form-label',labelLayout]" v-html="label"></label>
    <div :class="inputLayout" ref="content">
      <slot></slot>
      <div class="form-text text-muted" v-if="feedback" v-html="feedback"></div>
      <small class="form-text text-muted" v-if="description" v-html="description"></small>
    </div>
  </div>
</template>
````

Should be:
```html
<template>
  <div :class="['form-group','row',inputState]">
    <label :for="target" v-if="label" :class="['col-form-label',labelLayout]" v-html="label"></label>
    <div :class="inputLayout" ref="content">
      <slot></slot>
      <div class="form-text form-control-feedback" role="alert" v-if="feedback" v-html="feedback"></div>
      <small class="form-text text-muted" v-if="description" v-html="description"></small>
    </div>
  </div>
</template>
```

**Comment by tmorehouse** [comment]
Also, the label gets assigned a `for` of the first child of the content, which might not always be the first input

```js
this.target = content.children[0].id;
```

It might be better to look for the first input:
```js
this.target = content.querySelector('input, select, textarea').id;
```

The querySelector selector string could be a prop, in case the user has some other custom input element.

**Comment by tmorehouse** [comment]
I have added this in my fork.  I can issue a pull request if you like.

**Comment by pi0** [comment]
@tmorehouse Thanks for your recent bug reports. Sadly i'm fucking busy this days and haven't found 0any time helping to resolve your issues. But we will happily accept if you can prepare PRs :)

**Comment by tmorehouse** [comment]
I'lll generate a PR

**Comment by tmorehouse** [comment]
PR #254 created.
