### ISSUE TITLE
The disabled property value is not reflected correctly in display of `b-form-radio` on Microsoft Edge

### ISSUE THREAD

**Issue by 4dn-oss** [bootstrap-vue/bootstrap-vue#2532]
On Microsfot Edge, changing the `disabled` property of `b-form-radio` does not affect the display. It will be reflected correctly in other browsers. Also, native radio buttons are correctly reflected in any browser.

Example: https://codesandbox.io/s/o7xrrqxoky

Expected: Every time the 'disable/enable' button is clicked, 'native' and 'bootstrap-vue' radio buttons will be disabled/enabled.
Result: On Microsoft Edge, 'native' radio buttons behave as expeced, but 'bootstrap-vue' radio buttons are always displayed as if it is enabled.

On Firefox(65), Chrome(72.0.3626.96), all radio buttons behabe as expected.

OS: Windows 10 (1809)
Browser: Microsoft Edge (44.17763.1.0)
bootstrap-vue: 2.0.0-rc.11, dev(70ca4303442507ff34c1dc394b5354ee57683342)

**Comment by tmorehouse** [comment]
Could you verify that it is working correctly in vanilla Boostrap V4.2 and v4.3?  This sounds more like an upstream issue with Bootstrap V4 SCSS/CSS, since BootstrapVue uses Boostrap v4.x SASS (dev is now using V4.3).

**Comment by tmorehouse** [comment]
@4dn-oss do you see the issue at https://deploy-preview-2315--bootstrap-vue.netlify.com/ (preview of the next release)

**Comment by 4dn-oss** [comment]
This issue is reproduced in the following example.
I will report it to upstream.

```
<!DOCTYPE html>
<html>
  <head>
	<title>bootstrap4 radio button test</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
	<script>
	  var disabled = false;
	  function toggleRadio () {
	    disabled = !disabled
	    $("#customRadio1").prop('disabled', disabled);
	    $("#customRadio2").prop('disabled', disabled);
	  }
	</script>
  </head>
  <body>
	<button type="button" class="btn btn-primary" onclick="toggleRadio()">
	  disable/enable
	</button>
	<div class="custom-control custom-radio">
	  <input type="radio" id="customRadio1" name="customRadio"
			 class="custom-control-input">
	  <label class="custom-control-label" for="customRadio1">one</label>
	</div>
	<div class="custom-control custom-radio">
	  <input type="radio" id="customRadio2" name="customRadio"
			 class="custom-control-input">
	  <label class="custom-control-label" for="customRadio2">two</label>
	</div>
  </body>
</html>
```

**Comment by tmorehouse** [comment]
Could you add a link here to the upstream issue once you have it created?

**Comment by 4dn-oss** [comment]
Upstream issue I posted is: https://github.com/twbs/bootstrap/issues/28247

**Comment by 4dn-oss** [comment]
I changed `toggleRadio` as follows, but the issue did not fixed.

```
    toggleRadio() {
      this.radioDisabled = !this.radioDisabled
      this.$forceUpdate()
    }
```

**Comment by tmorehouse** [comment]
Is `this` a reference to your component, or a reference to the `b-radio` instance?  If the former, try adding a `ref` to your radio (i.e. `ref="theRadio"`) and then forcing update on it: `this.$refs.theRadio.$forceUpdate()`

**Comment by 4dn-oss** [comment]
I added the following CSS style introduced in the issue of 'carbon' (https://github.com/IBM/carbon-components/issues/1536). It worked fine.

```
[disabled] ~ _ {}
```

**Comment by 4dn-oss** [comment]
Calling $forceUpdate() of each radios did not fix this issue.

https://codesandbox.io/s/4qok22o414

**Comment by tmorehouse** [comment]
Ok.. good to know... hopefully twbs/bootstrap will incorporate the above css in the next patch release.

**Comment by tmorehouse** [comment]
Closing as upstream at Bootstrap.
