### ISSUE TITLE
Dropdown menu width too wide

### ISSUE THREAD

**Issue by cliffordh** [bootstrap-vue/bootstrap-vue#2533]
I'm using this markup but the resulting dropdown items are wider than the menu container. I'm not sure if this is Bootstrap 4 default appearance but I'd like to have my menu items not overlap the width of the menu. Here's the code and a screenshot:

```
<b-nav-item-dropdown right v-if="this.$store.getters.authenticated">
            <template slot="button-content">
              <em>Signed In</em>
            </template>
            <b-dropdown-item href="#">Profile</b-dropdown-item>
            <b-dropdown-item href="#">Signout</b-dropdown-item>
</b-nav-item-dropdown>
```
<img width="210" alt="screen shot 2019-02-12 at 6 11 44 am" src="https://user-images.githubusercontent.com/1755156/52631679-6ddd5900-2e8d-11e9-8f92-daed12330218.png">

Note, this only appears to be happening in Safari on OS X. Chrome is ok, see below:

<img width="199" alt="screen shot 2019-02-12 at 6 26 23 am" src="https://user-images.githubusercontent.com/1755156/52632299-25269f80-2e8f-11e9-9b73-3d1c11082664.png">

Thanks, Cliff.

**Comment by tmorehouse** [comment]
Which version of BootstrapVue and Booststrap CSS are you using?

This looks more like an upstream issue with Bootstrap CSS.

**Comment by cliffordh** [comment]
@tmorehouse here are my dependencies:

```
  "dependencies": {
    "aws-amplify": "^1.1.19",
    "bootstrap-vue": "^2.0.0-rc.11",
    "vue": "^2.6.2",
    "vue-icon": "^2.1.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },

```

I'm not attaching any CSS in my .vue files, not including Bootstrap via index.html (tried it, no change). I am only importing bootstrap in main.js:

`import "bootstrap/dist/css/bootstrap.min.css";
`

Cliff

**Comment by tmorehouse** [comment]
Could you try the `dev` branch, as it is using the latest Bootstrap V4.3 SCSS

**Comment by cliffordh** [comment]
@tmorehouse I installed using npm i bootstrap-vue... how do I switch to the dev branch? I tried nom install --save bootstrap-vue/bootstrap-vue#dev but that doesn't seem to be working

**Comment by tmorehouse** [comment]
You would need to do a `git clone`,

or alternatively, try your code in the playground on the dev branch preview at: https://deploy-preview-2315--bootstrap-vue.netlify.com/

**Comment by cliffordh** [comment]
@tmorehouse Confirmed, the code works on the Dev playground, but shows the menu problem in the RC11 playground.

**Comment by cliffordh** [comment]
For reference, here's the template for my Header.vue:

```
  <b-navbar type="light" toggleable="md">
    <div class="container">
      <b-navbar-brand class="text-success" :to="{ name: 'home' }"
        >Test
        <v-icon name="home" class="mb-1"></v-icon>
      </b-navbar-brand>
      <b-navbar-toggle class="ml-auto" target="nav_collapse"></b-navbar-toggle>
      <b-collapse is-nav id="nav_collapse">
        <b-navbar-nav class="ml-auto">
          <b-nav-item
            v-if="!true"
            :to="{ name: 'signin' }"
          >
            <v-icon name="log-in"></v-icon>
            Sign In
          </b-nav-item>
          <b-nav-item
            v-if="!true"
            :to="{ name: 'signup' }"
          >
            <v-icon name="star"></v-icon>
            Sign Up
          </b-nav-item>
          <b-nav-item-dropdown right v-if="true">
            <template slot="button-content">
              <em>Signed In</em>
            </template>
            <b-dropdown-item href="#">Profile</b-dropdown-item>
            <b-dropdown-item :to="{ name: 'signout' }">Signout</b-dropdown-item>
          </b-nav-item-dropdown>
        </b-navbar-nav>
      </b-collapse>
    </div>
  </b-navbar>
```

**Comment by tmorehouse** [comment]
So looks like it must have been an upstream issue with the older version of Bootstrap v4.1 SCSS, as the dev branch is now using the latest v4.3 Bootstrap SCSS.

**Comment by behzadim** [comment]
has anyone fixed this problem? cause i still have this issue with the dropdown width and it's not working in the playground too.

https://jsfiddle.net/behzadim/daw8hrs9/

**Comment by tmorehouse** [comment]
@behzadim I'dont see an issue with your JS Fiddle. Dropdowns look file:

![image](https://user-images.githubusercontent.com/2781561/57017817-30b87580-6bf7-11e9-9979-14d28341d6cb.png)

It does have a `min-width: 10rem` set by Bootstrap's SCSS:

![image](https://user-images.githubusercontent.com/2781561/57017855-5f365080-6bf7-11e9-8b8a-e4e52ddd501a.png)

**Comment by behzadim** [comment]
Thank you for your attention. I would like to shrink the width of content as you see in the picture below (the red border). Currently I have resolved my problem by using <b-form-select> but It would be great if I knew how to do this in dropdown too.

![decrease-width](https://user-images.githubusercontent.com/21251201/57018054-12726a00-6c37-11e9-94d4-dce502d0531d.png)

**Comment by tmorehouse** [comment]
You would need to override Bootstrap's CSS for the value of min-width.

**Comment by tmorehouse** [comment]
See here for an example: https://jsfiddle.net/mn8zrtos/

**Comment by behzadim** [comment]
Thank you so much!
