### ISSUE TITLE
BSpinner missing from RC and Dev

### ISSUE THREAD

**Issue by cliffordh** [bootstrap-vue/bootstrap-vue#2537]
The <b-spinner> element doesn't seem to be included with BV:

import BSpinner from 'bootstrap-vue/es/components/spinner/spinner'
Vue.component('b-spinner', BSpinner)

Looking at components/index.js I don't see the spinner referenced at all.

**Comment by tmorehouse** [comment]
It isn't available in the rc11 release, it is in the current dev branch though.

In components/index.js the plugin is imported.
