### ISSUE TITLE
[Question] Don't set active state on navigation

### ISSUE THREAD

**Issue by cliffordh** [bootstrap-vue/bootstrap-vue#2539]
I don't want the active state to be set on my buttons and nav links... any idea how to do this with BV?

Thanks.

**Comment by tmorehouse** [comment]
Are you using a router, or just plain links?

**Comment by tmorehouse** [comment]
The active state is used to let users know which link represents the current page (it is handy specifically for accessibility reasons)

**Comment by cliffordh** [comment]
I'm using this with VueRouter and :to links. The accessibility concern makes sense. I will look into styling solutions.

**Comment by tmorehouse** [comment]
You can customize the the router-link `active-class` and `exact-active-class` values to do style overrides.

Note in navs (tab style or pill style), the active class makes the tab (or pill) appear selected.
