### ISSUE TITLE
is it possible to disable values default classes?

### ISSUE THREAD

**Issue by zavvla** [bootstrap-vue/bootstrap-vue#2546]
Now the plot is hard to bootstrap classes, due to the fact there is a conflict between styles. Is there any way to disable them, or if you override them to keep only the new classes?

**Comment by jackmu95** [comment]
@zavvla Can you please describe your issue a bit more detailed or create an example.

**Comment by zavvla** [comment]
> @zavvla Can you please describe your issue a bit more detailed or create an example.
The project may already have classes "btn, btn-group, dropdown". A component has already sewn classes that need to be overridden. This is inconvenient, especially if you use BEM.

**Comment by tmorehouse** [comment]
BootstrapVue is based on Bootstrap V4.x SCSS/CSS.  The classnames would need to be changed initially in Bootstrap V4.x SCSS (along with variables names, etc).  This would not be a task for BootstrapVue.
