### ISSUE TITLE
Add `BvEvent` and `BvModalEvent` TypeScript definitions

### ISSUE THREAD

**Issue by 2-5** [bootstrap-vue/bootstrap-vue#2554]
I'm using bootstrap-vue together with TypeScript, and `BvEvent` is missing from the type declarations. This is required for example in modal `ok` events:

```javascript
ok(evt: BvModalEvent): void {
  evt.vueTarget ...
}
```

**Comment by tmorehouse** [comment]
Note that the base BvEvent object structure is consistent, but may have additional properties depending on which component triggers the event.

**Comment by jamesgeorge007** [comment]
@tmorehouse @jackmu95  I would love to take this up :clap: Can you point me to the required files to be worked upon?

**Comment by tmorehouse** [comment]
@jamesgeorge007 

BvEvent Class is defined here: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/utils/bv-event.class.js

I'm wondering for things that implement extras on BvEvent, if we should be subclassing a new event type (i.e. BvEventModal, BvEventTooltip, etc), where they add in additional properties).

Some of the properties in BvEvent can support multiple types (Any/Mixed)...  but the BvEvent typscript definitions would be a good start. and if we are not too strict about it, we can allow for extra undefined properties on the event structure.

**Comment by tmorehouse** [comment]
We should probably add a reference section on BvEvent under /docs/reference/bvevent as well.

**Comment by pingustar** [comment]
I think my error falls under the same issue:

```
ERROR in /home/.../.../file.vue
321:10 Property '$bvModal' does not exist on type 'UserPackages'.
    319 |       action: action
    320 |     }
  > 321 |     this.$bvModal.show('modal-staking')
        |          ^
    322 |   }
    323 | 
```

is there a workaround to fix this error? Thanks -J

**Comment by wdifruscio** [comment]
Having same problem as  @pingustar ,
just need to workaround this although it probably should be fixed since typescript is becoming so popular

**Comment by tmorehouse** [comment]
PRs and help are appreciated.

**Comment by tmorehouse** [comment]
PR #3209 Is an attempt at creating more typings in a better structured format.  But I admit I have had no experience is creating typescript definition files, and any assistance / help / pointers / testers (especially from people with TypeScript experience) would be greatly appreciated.

**Comment by pingustar** [comment]
@tmorehouse I really appreciate all your work and help. I am very new to TypeScript myself and unfortunately no help at this point, I am sorry. Still wrapping my head around it all.
