### ISSUE TITLE
Tooltip residue.

### ISSUE THREAD

**Issue by hifall** [bootstrap-vue/bootstrap-vue#2559]
Keeping hovering into/out of an element fast with a tooltip randomly leaves some residue. This is easily reproducible on the official demo at: https://bootstrap-vue.js.org/docs/components/tooltip/.

I have prepared a screenshot: 
<img width="800" alt="screen shot 2019-02-14 at 5 52 25 pm" src="https://user-images.githubusercontent.com/5734293/52778598-55359480-3081-11e9-8597-0beb9b4288e7.png">

The small black patches on the screenshot are what I called "residue".

**Comment by tmorehouse** [comment]
Related/Duplicate: #1990

**Comment by tmorehouse** [comment]
Tooltips and Popovers will be getting a makeover once POrtal-Vue 2.0.0 is released, which should address this issue.

**Comment by jackmu95** [comment]
Closed in favor of #1990.
