### ISSUE TITLE
"@babel/runtime": Missing rc12

### ISSUE THREAD

**Issue by XpamAmAdEuS** [bootstrap-vue/bootstrap-vue#2564]
When importing individual components have error about @babel/runtime/helpers missing

**Comment by tmorehouse** [comment]
We might have to add that to the sideEffects rule...

**Comment by tmorehouse** [comment]
Are you importing the components via the es directory?

If you import the component group plugin, do you see the same issue?

**Comment by tmorehouse** [comment]
You might need to clear your yarn lock, or do a yarn upgrade?

**Comment by XpamAmAdEuS** [comment]
I have cleaned all node directory and npm lock file and after npm install.
i still not try component group plugin,
after adding  @babel/runtime to devDeps all work ok.

Just found typos in docs about 'bootstrap-vue/es/directives/b-tooltip/b-tooltip'
there is no such directory b-tooltip it just tooltip.
Should i open new issue ?

**Comment by tmorehouse** [comment]
Yeah, if you can open an issue for the docs we can get a PR made

**Comment by jackmu95** [comment]
Closed in favor of #2566.
