### ISSUE TITLE
Table still shows empty slot even when busy slot is being shown

### ISSUE THREAD

**Issue by jackbondpreston** [bootstrap-vue/bootstrap-vue#2565]
# Problem
When a table has no data and is in the busy state with the busy slot displayed, the empty slot is still displayed. This is inconsistent with how the busy slot normally works - none of the current table data is displayed in the table when the busy slot is displayed.

Reproduction:
```vue
<template>
    <div>
        <b-table :items="getItems" :fields="fields" ref="table" show-empty>
            <template slot="table-busy">Busy</template>

            <template slot="empty">Empty</template>
        </b-table>

        <b-button @click="data = !data; $refs.table.refresh()">Toggle Data</b-button>
    </div>
</template>

<script>
export default {
    data: function() {
        return {
            fields: {
                col1: "Column 1",
                col2: "Column 2"
            },
            data: true
        };
    },
    methods: {
        getItems: function(contextm, callback) {
            // simulate loading that takes some time
            return new Promise(resolve => setTimeout(resolve, 1000)).then(
                () => {
                    if (!this.data) return [];

                    return [
                        {
                            col1: "Item 1 A",
                            col2: "Item 1 B"
                        },
                        {
                            col1: "Item 2 A",
                            col2: "Item 2 B"
                        }
                    ];
                }
            );
        }
    }
};
</script>
```
The two problematic situations in this example: 
- On the original component load, the table displays both busy and empty slot before any data has been loaded into the table.
- When switching from having no data to having the example data, both the busy and empty slot are displayed. However when switching from having the example data to no data, only the busy slot is displayed

# Solution 
The empty slot should not be displayed if the busy slot is being displayed.

**Comment by tmorehouse** [comment]
A work around would be to dynamically change the empty row prop to false when the busy state changes to false.
