### ISSUE TITLE
Include purgecss in the library

### ISSUE THREAD

**Issue by mauxtin** [bootstrap-vue/bootstrap-vue#2579]
**Problem**
We include **A LOT** of classes that are never used in our apps. Using `nuxt-purgecss` right now results in every class that is used in boostrap-vue components being removed (https://github.com/Developmint/nuxt-purgecss/issues/22).

**Feature request**
It would be awesome if there was a way to optionally include `purge-css` or `nuxt-purgecss` in the library. This would significantly reduce the size of the library and our websites size.

**Comment by jackmu95** [comment]
@mauxtin Both Bootstrap and BootstrapVue allow to import only the SCCS files for the components you really use.

**Comment by tmorehouse** [comment]
The custom Bootstrap-Vue CSS/SCSS is quite small, although Bootstrap SCSS/CSS can be quite large.

The Bootstrap Nuxt plugin allows you to exclude automatic inclusion of both Boostrap and BootstrapVue CSS. 

See: https://deploy-preview-2578--bootstrap-vue.netlify.com/docs/reference/theming

Maybe we should include a new reference section for the Nuxt plugin?

**Comment by mauxtin** [comment]
So there is a way of importing only certain components (and their css)?

Let's say I want to only import `b-modal` in my app there is a way of importing only its own css instead of the whole bootstrap core?

I suppose this would be a solution to my problem (although using purgecss would be more efficient ofc)

How would I go about that? [The docs](https://bootstrap-vue.js.org/docs/#nuxtjs-plugin-module) only mention importing certain vue components but couldn't find anything about there CSS.

**Comment by tmorehouse** [comment]
For CSS importing (using SCSS) refer to the themeing section of  bootstrap Vue docs, and the similar section in the bootstrap docs. The bootstrap docs show how to import only a few of the bootstrap SCSS files)

**Comment by tmorehouse** [comment]
In some cases purgecss might remove css that is needed on some components that dynamically apply css classes to the rendered html elements (specifically when running on client side, and state changes on the component.. such as adding or removing helper classes).
