### ISSUE TITLE
"active" class is no longer applied to nav items when navigating to route

### ISSUE THREAD

**Issue by TheoBP** [bootstrap-vue/bootstrap-vue#2584]
When navigating to '/routeA' the first b-nav-item should become active.

```html
<b-navbar-nav>
    <b-nav-item to="/routeA">View A</b-nav-item>
    <b-nav-item to="/routeB">View B</b-nav-item>
</b-navbar-nav>
```

**Comment by jackmu95** [comment]
For Vue Router the default active class is `router-link-active`, for Nuxt.js it's `nuxt-link-active`. You can change the active class with the `active-class` and `exact-active-class` props.

**Comment by jackmu95** [comment]
What changed with RC12 is that we no longer set `active`  as `active-class` by default rather than inheriting the default values from Vue Router and Nuxt.js.

**Comment by TheoBP** [comment]
Oh, OK. Thanks for clarifying, I must have missed that in the release log.

**Comment by tmorehouse** [comment]
Yeah, it wasn't mentioned as a "breanking" change, but there is a commit listed.

What was happening is that users who set a "global" active class and exact active class were getting overridden by the default values set by the props.  The commit fixed this issue.

**Comment by jackmu95** [comment]
@tmorehouse Maybe we should mention that somewhere in the docs that they are inherited from Vue Router/Nuxt.js?

**Comment by tmorehouse** [comment]
Yeah... probably in the router links reference section?

**Comment by tmorehouse** [comment]
Actually it is there:

> ### `active-class`
> type: string
> default: 'router-link-active' ('nuxt-link-active' when using Nuxt.js)
> Configure the active CSS class applied when the link is active. Note the default value can also be configured globally via the linkActiveClass router constructor option.

**Comment by jackmu95** [comment]
Oh, missed it.
