### ISSUE TITLE
Incorrect validation icon padding

### ISSUE THREAD

**Issue by buismaarten** [bootstrap-vue/bootstrap-vue#2599]
Since I've updated to Bootstrap 4.3, the validation icon is not correct aligned. The icon is too much aligned to the right side.

![image](https://user-images.githubusercontent.com/16333228/52898368-2c2a1680-31dd-11e9-8b5a-67f777bd209c.png)

**Comment by jackmu95** [comment]
@buismaarten Can you create a demo on [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/) or [JSFiddle](https://jsfiddle.net/) to confirm that this is directly related to BootstrapVue or if it is an issue with Bootstrap itself.

**Comment by tmorehouse** [comment]
Looking at the Bootstrap V4.3 docs I can see that the padding appears correctly: 

![image](https://user-images.githubusercontent.com/2781561/52901249-73ada400-31d7-11e9-8d5e-f59fab63da1d.png)

But it is not padding that positions the validation icon, it is background image positioning.

**Comment by tmorehouse** [comment]
Looking at the custom SCSS we have for form-input, it only applies to type color and custom ranges.

It might be something in the docs CSS that may be affecting this (docs only?)

**Comment by mosinve** [comment]
I checked BV docs site, and it seems to show icons correct way
![image](https://user-images.githubusercontent.com/20986566/52901537-73dd8c00-3237-11e9-9924-9493cbad70ad.png)

**Comment by mosinve** [comment]
So @buismaarten, please provide us your example, that reproduce the issue to continue further investigations :)

**Comment by buismaarten** [comment]
I've done some more research.

This problem only applies when I run `npm run prod` (yes, I'm using Laravel Mix)
This builds the CSS for production usage.

So I think the problem is not with bootstrap-vue. I thought this because I recently updated some packages related to Bootstrap and since then I have this problem.

**Comment by tmorehouse** [comment]
It appears to be only affecting DOCs site...  pasting code into playground (see issue) and exporting to JS Fiddle it works fine (no issue).

**Comment by tmorehouse** [comment]
In the docs site the validation icon positioning is:
```css
background-position: 100% calc(.375em + .1875rem);
```

But in source, it is:
```css
background-position: center right calc(.375em + .1875rem);
```

Something is changing this curing docs generation (prod, not dev).

**Comment by buismaarten** [comment]
Yes, I have noticed the same on my environment.

Could this problem be with Webpack or something?

**Comment by tmorehouse** [comment]
Nuxt.JS uses `cssnano` for post CSS processing/minification.  So it might be related to https://github.com/cssnano/cssnano/issues/701

**Comment by tmorehouse** [comment]
changing the bootstrap CSS from:

```css
background-position: center right calc(0.375em + 0.1875rem);
```
to:
```css
background-position: right calc(0.375em + 0.1875rem) center;
```

fixes the issue.

Not sure if it is a cssnano issue, or if it is a bootstrap issue.

**Comment by tmorehouse** [comment]
Opened a new issue at cssnano: https://github.com/cssnano/cssnano/issues/712

as it is confirmed that it is indeed a cssnano bug.
