### ISSUE TITLE
Accordions don't work

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [bootstrap-vue/bootstrap-vue#261]
Following the instructions to install bootstrap-vue, everything works fine apart from accordions which don't expand.

I ran npm install jquery which still didn't work.

Anyone else had an issues?

**Comment by pi0** [comment]
@MatthewJamesBoyle Would you please share code snippet you are using?

**Comment by pi0** [comment]
Please reopen if problem exists with latest release with additional info to reproduce bug.
