### ISSUE TITLE
Null Error Between 2.0.0-rc.11 and 2.0.0-rc.12 On Table Fields

### ISSUE THREAD

**Issue by StrangeWill** [bootstrap-vue/bootstrap-vue#2623]
When printing the following table:
```
<b-table ref="numbersTable" show-empty striped small bordered
		 :items="numbers"
		 :fields="fields"
		 :filter="filterList"
		 :current-page="currentPage"
		 :per-page="perPage"
		 @@filtered="onFiltered">
</b-table>
```

With the following field config:
```
fields: [
	{key: "number", sortable: true },
	{key: "trackingCode.friendlyName", sortable: true, label: "Friendly Name"},
	{key: "targetNumber", sortable: true, label: "Target" },
	{key: "ivr.recording.name", sortable: true, label: "Ivr"},
	{key: "record", sortable: true, label: this.clientRecord ? 'Do Not Record' : 'Record', 'class': 'text-center' },
	{key: "actions", sortable: false, label: ""}
],
```

When ivr is undefined we get:
```
TypeError: Cannot read property 'recording' of null
    at xa (get.js:21)
    at o.getFormattedValue (table.js:831)
    at table.js:1303
    at Array.map (<anonymous>)
    at table.js:1302
    at Array.forEach (<anonymous>)
    at o.render (table.js:1290)
    at o.fn._render (vue.min.js:6)
    at o.i (vue.min.js:6)
    at St.get (vue.min.js:6)
```

Because `ivr` is undefined (expected, field: ivr.recording.name), in RC 11 this renders fine by printing nothing.

**Comment by tmorehouse** [comment]
I can see where the issue would be occurring (by checking  `util/get.js` code), but I can't reproduce the error when running a mockup in the playground (exported to fiddle: https://jsfiddle.net/co90r37k/)

**Comment by tmorehouse** [comment]
@StrangeWill would you be able to create a minimal markup/fiddle that reproduces the issue?

**Comment by StrangeWill** [comment]
Yep, working on trying to find the missing piece to this puzzle.

**Comment by StrangeWill** [comment]
Sorry, the value is `null` not `undefined` as per the error provided, the JSON object has a null value.

https://jsfiddle.net/StrangeWill/70jtoe8g/

**Comment by tmorehouse** [comment]
OK... so PR #2624 should fix this then.
