### ISSUE TITLE
Support other `router-link` compatible components

### ISSUE THREAD

**Issue by ion1** [bootstrap-vue/bootstrap-vue#2627]
[Gridsome](https://gridsome.org/) has a [`g-link` component](https://gridsome.org/docs/linking/), equivalent to [`nuxt-link`](https://nuxtjs.org/api/components-nuxt-link/). As of now, BootstrapVue has built-in support for `nuxt-link`; it would be nice to have support for `g-link` as well.

Rather than having to [detect and support every Vue-based framework](https://github.com/bootstrap-vue/bootstrap-vue/blob/6aa6e92db23307ee0fd6c4c1700d061c10153741/src/components/link/link.js#L123-L129), maybe it would be reasonable to have the ability to configure BootstrapVue to use a specified `router-link`-compatible component. I apologize if this already exists and I missed it.

Thank you!

**Comment by jackmu95** [comment]
@tmorehouse Interesting idea but I don't think we can solve this by simply adding a `tag` or `link-tag` prop to each component that uses `<b-link>`. A global configuration option would be the better choice her, but we currently don't have something like that.

**Comment by tmorehouse** [comment]
Although we would need to find a way to add props dynamically (if Gridsome adds any new ones).  Currently the Gridsome docs only show 4 props for their `g-link` component (all of which are standard `router-link` props). And there is no mention of a injected object in the VMs for detection of Gridsome presence (like Nuxt.js` does)

It might be best to wait until Gridsome reaches a more stable/mature release before determining the best approach. The current use of `router-link` in BootstrapVue will work with Gridsome (minus any of the link prefetching features).

**Comment by eddybrando** [comment]
If you want to leverage the Gridsome linking features tho, you can create a NavItem component in the meantime, like this:

```
<template>
  <li class="nav-item">
    <g-link active-class class="nav-link" exact-active-class="active" target="_self" :to="to">
      <slot/>
    </g-link>
  </li>
</template>

<script>
export default {
  name: 'NavItem',
  props: { to: { required: true, type: String } },
};
</script>
```

**Comment by tmorehouse** [comment]
If gridsome exposed a `Vue.protototype` injection (i.e. so that `this.$gridsome` exists on all component VM instances), we could auto detect that the app is running under gridsome and change the use of `router-link` to `g-link`

**Comment by eddybrando** [comment]
> If gridsome exposed a `Vue.protototype` injection (i.e. so that `this.$gridsome` exists on all component VM instances), we could auto detect that the app is running under gridsome and change the use of `router-link` to `g-link`

Sounds like [feature request](https://github.com/gridsome/gridsome/issues/new?template=feature-request---.md) time 😬.

Would you do the honours or should I, @tmorehouse? I believe you could explain it better than me.
