### ISSUE TITLE
Bootstrap style files do not load after updating nuxt to v2.3.4

### ISSUE THREAD

**Issue by Javid-Izadfar** [bootstrap-vue/bootstrap-vue#2629]
Bootstrap style are not applied to project after updating nuxt to [v2.3.4](https://github.com/nuxt/nuxt.js/releases/tag/v2.4.3).

I've check it on bootstrapVue rc.11 and rc.12 and I'm on windows 10 using node v10.5.0

**Comment by tmorehouse** [comment]
Most likely fixed via #2593

**Comment by tvChan** [comment]
> Bootstrap style are not applied to project after updating nuxt to [v2.3.4](https://github.com/nuxt/nuxt.js/releases/tag/v2.4.3).
> 
> I've check it on bootstrapVue rc.11 and rc.12 and I'm on windows 10 using node v10.5.0

Hello, do your problem like this? 
Local operation is normal, is there a problem with the deployment on the server?

**Comment by Javid-Izadfar** [comment]
I cannot load bootstrap styles yet.

**Comment by Kordonme** [comment]
Same here. No bootstrap CSS added.

**Comment by SixBytesUnder** [comment]
I'm facing the same issue, however everything was fine on fresh project initiation, then I removed node_modules, run `npm install` and Bootstrap won't load anymore.
Note, Boostrap folders exist in node_modules and I get no errors that anything is missing.

**Comment by JDBlackman** [comment]
https://github.com/bootstrap-vue/bootstrap-vue/pull/2616

Still hasn't been released on NPM

**Comment by tmorehouse** [comment]
RC.13 has been available on NPM for a few days:

![image](https://user-images.githubusercontent.com/2781561/53269631-c5669a80-36bf-11e9-8815-7a356bfdd40f.png)

**Comment by Kordonme** [comment]
Thanks pi0. Seems like the issue has been resolved with the fix above. Reverted back to beta 13 and added the following to my `nuxt.config.js` until release of next beta:

```css
bootstrapVue: {
  bootstrapCSS: true,
  bootstrapVueCSS: true
}
```

**Comment by DaleMatthews** [comment]
Could the fix for this issue be causing double-includes of styles when following the theming guide?

**Comment by tmorehouse** [comment]
@DaleMatthews If you are including the SCSS multiple ways (i.e. via Vue CLI, etc), it is possible that you will have the resultant CSS included twice.

**Comment by DaleMatthews** [comment]
@tmorehouse in nuxt config:
```
  modules: [
    'bootstrap-vue/nuxt',
  ],
  css: [
    '@/assets/css/main.scss',
  ],
```

In main.scss:
```
$primary: #2c5050;

@import '~bootstrap/scss/bootstrap.scss';
@import '~bootstrap-vue/src/index.scss';
```

That's all I have

**Comment by tmorehouse** [comment]
@DaleMatthews the bootstrap-vue nuxt module automatically includes the compiled CSS files. You will need to add the option to disable that auto inclusion.

```js
  modules: [
    'bootstrap-vue/nuxt',
  ],
  bootstrapVue: {
    bootstrapCSS: false, // Or `css: false`
    bootstrapVueCSS: false // Or `bvCSS: false`
  },
  css: [
    '@/assets/css/main.scss',
  ],
```

https://bootstrap-vue.js.org/docs#using-custom-bootstrap-scss
