### ISSUE TITLE
[b-tabs] can´t be disabled via prop

### ISSUE THREAD

**Issue by ddweber** [bootstrap-vue/bootstrap-vue#2631]
**Expected behaviour:**
When i set the `disabled` property on the `<b-tabs>` component, the current tab gets locked and no other tab can be selected/switch to.

**Actual behaviour:**
`disabled` property ` has no effect anymore.

**Comment:**
I know the disabled prop on the b-tabs was never mentioned in the component reference, but until _v2.0.0-rc.11_ it work es expected. Would it be possible to provide such a prop officially?

**Comment by tmorehouse** [comment]
@ddweber

So you would expect the current tab to be still visible, and all other tabs would be disabled when the `b-tabs` component is disabled?

**Comment by jackmu95** [comment]
@tmorehouse Is this something we want to implement since you have the option on the `<b-tab>` component itself. When this worked in the past it was probably a bug.

**Comment by tmorehouse** [comment]
Yeah, I'm not sure why it worked before (which is why I tagged this as low priority)

**Comment by ddweber** [comment]
@tmorehouse
Yes, that is the behaviour the component had in the previous releases.

**Comment by ddweber** [comment]
Thanks @jackmu95 for your suggestion using `disabled `prop on `b-tabs` directly :)

I´ve now done it the right/official way by using `v-model` on `b-tabs`, `index` in the `v-for` loop and `:disabled ` prop on `b-tab`.

In my opinion this issue can be closed and there is no need for the feature request anymore.
