### ISSUE TITLE
[modal] hide() component method not working when prevent closing is used

### ISSUE THREAD

**Issue by ddweber** [bootstrap-vue/bootstrap-vue#2633]
**Expected behaviour:**
In the chapter [Prevent Closing](https://bootstrap-vue.js.org/docs/components/modal/#prevent-closing) of the modals docs, the modal should hide after entering a value in the form and clicking the  `OK` button, because `this.$refs.modal.hide()` gets called in the handleSubmit method.

**Actual behaviour:**
The modal remains open.

**Comment by jackmu95** [comment]
@tmorehouse I'am not sure if this a bug. Since we are calling the `handleSubmit()` method in the `ok` event handler the `this.$refs.modal.hide()` call gets abandoned by the `this.is_closing` check.

Wrapping the `this.handleSubmit()` call in a `this.$nextTick()` fixes the example in the docs.

**Comment by tmorehouse** [comment]
Yeah, it might need  `$nextTick` wrapper. It is probably a race condition.  In an older browser on a slower machine, it works fine, but on latest Chrome and a faster computer it fails.
