### ISSUE TITLE
Documentation relative image URLs for Parcel bundler 

### ISSUE THREAD

**Issue by jgrizou** [bootstrap-vue/bootstrap-vue#2637]
I am using bootstrap-vue in my project and 'compiling' my app with [Parcel](https://parceljs.org/).

I ran into the relative img path problem described here: https://bootstrap-vue.js.org/docs/reference/images/ and previously discussed in #1982 #2392 #1245.

All answers so far involve webpack configuration of vue-loader with the ```transformAssetUrls``` field. I cannot figure out a way to transpose that solution to Parcel bundler. Even the ```require``` method does not seem to work.

I am new to web dev and struggling finding an angle to approach the issue due to lack of experience. I will keep investigating but if one of you know the solution, or can point me in the right direction, please could you share it here or on the doc page?

Thanks for all your hard work on bootstrap-vue.

**Comment by tmorehouse** [comment]
This appears to be more than a BootstrapVue issue, as the same issue would apply to any other Vue component library that needs to specify project relative URLs to custom components.

You might want to open an issue at `parcel-bundler-vue` at https://github.com/parcel-bundler/parcel
