### ISSUE TITLE
Checkboxes lose focus outline and don't animate when inside a table

### ISSUE THREAD

**Issue by adlaws** [bootstrap-vue/bootstrap-vue#2646]
I've found that the checkboxes (standard and switch variants) don't seem to have the transition animation when they are inside a table - they just immediately "snap" to the new state.

They also lose the "focus outline" effect when they are active.

Note that this doesn't affect their basic functionality. They still work fine, it's just that the visual effect is somewhat jarring, particularly if other (correctly animating) checkboxes are around.

The following simple JS fiddle will demonstrate the issue:
https://jsfiddle.net/adlaws/Lp6onqd0/

The in the example, the checkboxes are linked via the underlying data, so clicking one of the switch/standard checkboxes will also update its counterpart, making it easier to see the difference (I hope).

As shown in this JS fiddle, an equivalent layout works fine with "raw" Bootstrap (v4.3.1), so the issue seems to appear at the Bootstraup-Vue level:
https://jsfiddle.net/adlaws/n8w6uzxj/11/

I assume that this basically just a CSS hierarchy issue, but I haven't been able to track it down myself.

- BootstrapVue v2.0.0-rc13
- OS: Windows 10 64bit
- Browsers and versions tested:
  - Chrome Version 72.0.3626.109 (Official Build) (64-bit)
  - Firefox 65.0.1 (64-bit)

**Comment by tmorehouse** [comment]
This appears to be working fine in the latest release of BootstrapVue

Also, one should set a `primary-key` field that can be used to generate a Vue `:key` for each table row (`<tr>`) generated, which will minimize re-renders of the row contents when directly modifying table data.

**Comment by adlaws** [comment]
Thanks, guys!
...and apologies for the late acknowledgment of the fix - great work!
