### ISSUE TITLE
font awesome fonts in 'first-text', 'prev-text' etc. props on b-pagination no longer work?

### ISSUE THREAD

**Issue by sugaractive** [bootstrap-vue/bootstrap-vue#2655]
using 2.0.0-rc.13

This worked on rc10:

`  <b-pagination align="right" :hide-goto-end-buttons="false" :limit="5" :total-rows="totalCount" :per-page="perPage" :number-of-pages="totalPages" first-text="<i class='far fa-angle-double-left'></i>" prev-text="<i class='far fa-angle-left'></i>" next-text="<i class='far fa-angle-right'></i>" last-text="<i class='far fa-angle-double-right'></i>" @input="pageChanged($event)" v-model="currentPage">
              </b-pagination>`

Sorry for bad formatting of code, github is fighting me on markup right now.

I'm passing in Font-Awesome 5 icons to customize the looks of the pagination buttons. It now renders as:

![image](https://user-images.githubusercontent.com/47503166/53030225-44897380-341f-11e9-99f7-fcb5aab511a5.png)

Any ideas on how to fix? Thanks.

**Comment by jackmu95** [comment]
v2.0.0-rc.12 introduced some XSS improvements and dropped HTML support for `<b-pagination>`' `*-text` props. This isn't reflected in the docs correctly.

Using slots is the way to go here. see the example below:
https://codesandbox.io/s/1330x19oo7

**Comment by sugaractive** [comment]
Ah thank you! I had not noticed that change. Appreciate the link to a solution, I'll check it out. Closing this as solved.
