### ISSUE TITLE
Regression in rc12: tabs v-model always resets to 0

### ISSUE THREAD

**Issue by niksite** [bootstrap-vue/bootstrap-vue#2656]
- MacOS Mojave
- Chrome 72
- BootstrapVue 2.0.0-rc.12 and 2.0.0-rc.13

```
<template>
  <b-tabs v-model="tab">
    <b-tab title="1">
      1
    </b-tab>
    <b-tab title="2">
      2
    </b-tab>
  </b-tabs>
</template>

<script>
export default {
  data () {
    return {
      tab: 1
    }
  }
}
</script>

<style>
</style>
```

On rc.11: tab 2 is active as expected
On rc.12 and rc.13 tab 1 is active and `this.tab` becomes `0`

**Comment by jackmu95** [comment]
@niksite I cannot reproduce this in the [Playground](https://bootstrap-vue.js.org/play).
Can you please create a live example.

**Comment by niksite** [comment]
Version 13: https://jsfiddle.net/3rxfc6h1/1/ (selected tab 1)
Version 11: https://jsfiddle.net/3rxfc6h1/3/ (selected tab 2 as expected)
