### ISSUE TITLE
<b-form-input> becoming out of sync with value if using formatter

### ISSUE THREAD

**Issue by kalvenschraut** [bootstrap-vue/bootstrap-vue#2657]
When a form-input has a formatter on it stripping out characters in the case of trying to only allowing numerial values in a text input, the input value can sometimes not match up with the emitted value.

codepen: https://codepen.io/Kalvens/pen/Lqabrj (type any nonnumerical character in the input)
browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
OS: linux

I believe the issue comes from 
https://github.com/bootstrap-vue/bootstrap-vue/blob/a14245cc27751e395f34b90fba20db16869a3484/src/mixins/form-text.js#L107-L123

the value is already formatted at that point so if the formatter strips out all of the characters leaving the value to be an empty string, nothing will happen even though the input still has a value set for it

I was playing around with your source code and doing
```javascript
if (this.localValue !== value) {
    ...
} else if (this.$el.value !== value)  {
  this.$el.value = value;
}
```
seems to fix my issue, but I am not sure if that would be affecting anything else using the mixin.

**Comment by tmorehouse** [comment]
Is this occurring on a browser that supports autocomplete or predictive text?

There is an issue with how some browsers handle these features. Some emit and I put for every character, while others will wait and emit a change once an autocomplete is completed or a space is entered (and inpput event may or may not be emitted with the change.

**Comment by kalvenschraut** [comment]
I am using chrome 69 right now, but I am typing into the input without using any autocomplete. The updateValue function is being fired correctly on key press. The localValue could potentially not be different then the value passed into updateValue due to the formatter function. If that is the case the input's value needs to be updated to match the localValue/value param so they stay in sync.

**Comment by jackmu95** [comment]
@tmorehouse I've looked into this a bit and I don't know why the input's value isn't changed.

**Comment by kalvenschraut** [comment]
@tmorehouse is my proposed fixed as outlined earlier not what you guys are want to do? I see you added a test that seems to be similar to this issue at 
https://github.com/bootstrap-vue/bootstrap-vue/blob/ec9178840914ae008b14d9eabce4e8b223f9ad28/src/components/form-input/form-input.spec.js#L483-L501

Where it is asserting that the value TEST is still set as the input value. Although I am not sure if that is something you are specifically handling for when formatters return false. My issue is mainly coming from when my formatter is returning an empty string, which I think should force the input's value to also be an empty string and not to keep any characters the user may have typed into the input.

**Comment by tmorehouse** [comment]
Yeah, there may need to be a few tweaks to the formatter.  Lazy formatting works best (as it doesn't cause issues with cursor positioning while the user types... even google libphonenumber has dropped as you type formatting).

Typically, one could use the non lazy formatter to prevent certain characters to be type, by preventing default on the passed `input` event (although `change` events are not preventable), and then returning false so that the v-model isn't updated.

**Comment by skourismanolis** [comment]
I just want to point out that this bug did not exist on version 2.0.0-rc.12, I updated from that yesterday and it broke, so I'm not exactly sure what version change caused it.

**Comment by nevadavid** [comment]
Isn't change the input's value on predictive text, right?

**Comment by tmorehouse** [comment]
@nevadavid Are you using v2.4.0?

**Comment by nevadavid** [comment]
@tmorehouse Yes, I use this version. The input's changes just when I push space. Can I set any other property on <b-form-input> component?

**Comment by tmorehouse** [comment]
@nevadavid can you create a minimal reproduction (jsFiddle, CodePen, or CodeSandBox - you can export from the docs playground) to issustrate what you are experiencing and open a new issue?

**Comment by nevadavid** [comment]
@tmorehouse this is what I experience on official website: https://bootstrap-vue.js.org/docs/components/form-input
(Huawei, Android 5.1, Chrome)

**Comment by tmorehouse** [comment]
I do not understand the issue you are having... can you explain more?  i can type without problem into the inputs.

**Comment by nevadavid** [comment]
@tmorehouse So when you enable the "Show correction suggestions" or similar function on your phone and type any characters on <b-form-input>, the input will changes after when I push space.

But here is my solution: https://codepen.io/nevadavid/pen/mdJbmgJ
(This is a very lightweight example, focus on the solution. For test I added a native input.)
It works well.

**Comment by tmorehouse** [comment]
@nevadavid could you please open a new ticket with your issue, so we can track it?

**Comment by nevadavid** [comment]
@tmorehouse I created a new issue: #4724
