### ISSUE TITLE
Best way to set to Modal busy

### ISSUE THREAD

**Issue by WillGoldstein** [bootstrap-vue/bootstrap-vue#2659]
Hi,

I was wondering what the best way is to make the buttons that are default to a modal get the busy setting? I know it's a prop, so you don't want to set it to true right before an ajax call, for example. I have tried this which seems to work but feels hacky:

_this.$refs.exampleModal.is_transitioning = true;

Thanks

**Comment by jackmu95** [comment]
@WillGoldstein Take a look at the example below:
https://codesandbox.io/s/mo5xv0wq39

**Comment by WillGoldstein** [comment]
Thank you @jackmu95 , that's exactly what I needed and sorry I didn't see that in the docs. Did you want me to close this issue?

**Comment by jackmu95** [comment]
@WillGoldstein Please do so.
