### ISSUE TITLE
BFormTextarea should allow 1 row

### ISSUE THREAD

**Issue by danielelkington** [bootstrap-vue/bootstrap-vue#2660]
In [this commit](https://github.com/bootstrap-vue/bootstrap-vue/commit/dc4d22687423acdb102827cedbd0db3823895112#diff-6af58e41436f375be8cbdeeaf9032c92), the default value for the `rows` prop of the BFormTextarea component was changed to '2', which is good. However it now ignores a prop value of '1', which was previously possible - the `computedMinRows` computed property forces a value of at least 2.

This makes it impossible to have a BFormTextarea display one row if the contents has 0 or 1 rows, and grow from there as the user enters text. Could the minimum rows please be decreased to 1?

**Comment by tmorehouse** [comment]
Unfortunately 1 is not a valid value for rows across browsers. Certain versions of firefox will crap out when set to 1, and other browsers will force it to 2 (el.rows === 2) even though you have set it to 1.

The minimum value of 2 is on purpose to work cross browser. Allowing other values may crap out on some browsers.

**Comment by mrkonovalov** [comment]
I’m working on a project that only supports Chrome and I’d like to point out somehow 1. How can I do this?

**Comment by tmorehouse** [comment]
Making exceptions on a browser by browser basis is not something we want to do in the project, as it adds to many extra conditionals and locgic that can end up breaking in certain situations.

**Comment by tmorehouse** [comment]
If you really need 1 row to start, then I would suggest rendering as a regular `b-form-input` type="text", and then once the content includes a newline or exceeds a number of characters, then change the component to a `b-form-textarea` dynamically (use the Vue `:is` attribute).

**Comment by vesper8** [comment]
> If you really need 1 row to start, then I would suggest rendering as a regular `b-form-input` type="text", and then once the content includes a newline or exceeds a number of characters, then change the component to a `b-form-textarea` dynamically (use the Vue `:is` attribute).

I am in a situation where I would really like to use the auto-expanding ability of your textarea but I also need to start off with only 1 row. I tried your suggestion and it kind of works.. the problem is that when the component changes from input to textarea then the focus is lost and the user can't continue typing.. @tmorehouse would you know how I could get around that?

```
      <component
        :is="messageText.length > 30 ? 'b-form-textarea' : 'b-form-input'"
        ref="messageComposer"
        v-model="messageText"
        placeholder="Type Your Message"
        rows="1"
        max-rows="4"
        @keydown="inputHandler"
      />
```

**Comment by vesper8** [comment]
Figured it out:

```
      <component
        :is="inputType"
        ref="messageComposer"
        v-model="messageText"
        placeholder="Type Your Message"
        rows="1"
        max-rows="4"
        @keydown="inputHandler"
      />
```

```
  computed: {
    inputType() {
      return this.messageText.length > 30 ? 'b-form-textarea' : 'b-form-input';
    },
  },

  watch: {
    inputType() {
      this.$nextTick(() => {
        this.$refs.messageComposer.focus();
      });
    },
  },
```

**Comment by vesper8** [comment]
It's almost perfect now but for example if you're pressing backspace to erase your message, then it will have a hiccup when it switches components on the fly... a real shame about this textarea requiring 2 rows minimum.. but I understand it's out of your hands.. perhaps forcing the textarea height to be smaller would be a better approach

**Comment by cvn** [comment]
I came up with a CSS solution.

```html
<b-form-textarea
  v-model="messageText"
  :class="{short: messageText.length < 30 && !messageText.includes('\n')}"
  max-rows="4"
/>
```
```css
.short {
  max-height: 38px;
}
```

Or, when I want a textarea to show up as one line by default, but grow when focused, I use a static css class: 

```css
.short:not(:focus) {
  max-height: 38px;
}
```

**Comment by LukasHirt** [comment]
> Making exceptions on a browser by browser basis is not something we want to do in the project, as it adds to many extra conditionals and locgic that can end up breaking in certain situations.

What about still allow the developer to set 1 row and document that it can break? Basically, it would be the responsibility of the dev then to use that value...
