### ISSUE TITLE
Undefined variable: "$dropdown-inner-border-radius"

### ISSUE THREAD

**Issue by electrocnic** [bootstrap-vue/bootstrap-vue#2663]
I am sorry that I do not have the time to make this bug report as detailed and pretty as possible.
It might be my own fault of wrongly configuring webpack and so on.

But here is what I had to do, in order to be able to build my project with webpack, using:

`"webpack": "^4.23.1",`
`"bootstrap": "^4.1.3",`
`"bootstrap-vue": "^2.0.0-rc.13",`
`"sass-loader": "^7.1.0",`

I had to:

1. Add 4 missing variables, which bootstrap-vue was not able to find, as they are NOT included in its own `_variables.scss`, nor in any of the official bootstrap files:

<pre>
$transition-fade:             opacity .15s linear !default;
$dropdown-inner-border-radius: 2px;
$font-weight-lighter: 300;
$enable-validation-icons: false;
</pre>

Only the first one, `transistion-fade` IS included in bootstrap, but I could not get it included with my second modifications, this time in my own webpack configuration:

2. Needed to modify my `webpack.base.conf.js` from this:

<pre>
module: {
  rules: [
    {
      test: /\.(sa|sc|le|c)ss$/,
      use: [
        MiniCssExtractPlugin.loader,
        'css-loader',
        'less-loader',
        'sass-loader'
      ]
    }
  ]
},
</pre>

 to this:

<pre>
module: {
  // ...,
  rules: [
    {
      test: /\.(sa|sc|le|c)ss$/,
      use: [
        MiniCssExtractPlugin.loader,
        'css-loader',
        'less-loader',
        {
          loader: 'sass-loader',
          options: {
            sourceMap: true,
            data: '@import "_functions.scss"; @import "_variables.scss";',
            includePaths: [
              resolve('src'),
              resolve('src/_assets/styles'),
              resolve('node_modules/bootstrap/scss'),
              resolve('node_modules/bootstrap-vue/src')
            ]
          }
        }
      ]
    }
  ]
},
</pre>

which resolved other problems.

I am not sure if it is my own mistake or if its something else, but may this help others with the same struggles.

Links which I followed:

https://github.com/webpack-contrib/sass-loader/issues/218
https://github.com/webpack-contrib/sass-loader#environment-variables

**Comment by jackmu95** [comment]
@electrocnic Make sure to use Bootstrap v4.3.1.

**Comment by cybercussion** [comment]
I just had this issue too after an update.  Verified Bootstrap 4.3.1 and I see I'm getting the error about Undefined variable: "$transition-fade".

**Comment by tmorehouse** [comment]
Make sure you are placing all the required SCSS `@import` statements into a single SCSS file which is imported into your app, as individual imports of SCSS files into your apps will not share variables between them.

See https://bootstrap-vue.js.org/docs#using-module-bundlers and https://bootstrap-vue.js.org/docs/reference/theming/#custom-scss

**Comment by cybercussion** [comment]
@tmorehouse thanks for the tips.  This is leading to a bit of a re-do for me so I'm gonna roll back for now.  I don't see <ul> or <li> in BS 4.1's examples currently and I think much of my SCSS was done w/o those tags so something is dorking up the display further.

I played with doing this instead:

```html
<template v-for="locale in activeLocales">
        <b-dropdown-item v-on:click="setLocale(locale.id, $event)" v-bind:key="locale.id">
            <span class="flag-icon" v-bind:class="locale.flag">{{ locale.name }}</span>
        </b-dropdown-item>
    </template>
```
To get rid of the v-html.  Thanks for that tip.

**Comment by electrocnic** [comment]
> Make sure you are placing all the required SCSS `@import` statements into a single SCSS file which is then imported into your app, as individual imports of SCSS files into your apps will not share variables between them (node-sass does not bundle/merge individual `import 'xx/yyy.scss`' in your app)

Finally this resolved it for me as well! Thank you so much! (Had hacky little workarounds in the meanwhile)
