### ISSUE TITLE
Form textarea with control sizing auto collapses on input

### ISSUE THREAD

**Issue by electrocnic** [bootstrap-vue/bootstrap-vue#2664]
Just try it out directly in the demo page:
https://bootstrap-vue.js.org/docs/components/form-textarea/

go to the section "Control sizing" and grab the bottom right handle to make the text area bigger.

As soon as I paste some text into it, it collapses to the default size, which I do not believe is what would be expected.

**Comment by tmorehouse** [comment]
Actually, user resizing is **not** supposed to be enabled (via CSS) when the text area is in auto-resize mode.

**Comment by tmorehouse** [comment]
As cutting text out of the text area should make the text area revert back to the minimum height needed to display the

@electrocnic, @jackmu95, This is working as intended/designed:

Besides growing to the content size, it also shrinks to the content size.... it goes both ways, and doesn't "stick" to the maximum size grown to.

**Comment by tmorehouse** [comment]
But there does appear to be an issue when no `max-rows` is specified.

This is because the computed style for the height is returning as `null`, which is overriding what the browser sets when the user drags the resize handle (when enabled).
