### ISSUE TITLE
BFormFile multiple files selected overflows label text

### ISSUE THREAD

**Issue by electrocnic** [bootstrap-vue/bootstrap-vue#2667]
OS: Windows,
Chrome,

When I use BFormFile, the content (user-selected Files) will not be trimmed to fit the form:

You can directly try it out in the demo: https://bootstrap-vue.js.org/docs/components/form-file
Just use chrome's debug mode and make the window width small enough that the filename is too long for the form.

The filename will be line-broken, which is not expected.

![vue-bootstrap-file-form-bug](https://user-images.githubusercontent.com/13003800/53101959-0ed1b100-352b-11e9-8252-964ba752a5f2.JPG)

**Comment by jackmu95** [comment]
@electrocnic Maybe this is an upstream bug from Bootstrap.

Can you please test it here too:
https://getbootstrap.com/docs/4.3/components/forms/#file-browser

**Comment by electrocnic** [comment]
@jackmu95 Confirmed.
Whatever, is it somehow possible to provide a prop for this element, where we could provide a lambda which gets the raw output string and one can modifiy it however they want?

:)

**Comment by jackmu95** [comment]
@electrocnic Can you please create an issue over at [Bootstrap](https://github.com/twbs/bootstrap/issues/new?template=bug_report.md) and reference this issue so we can close it when it get's fixed.

**Comment by tmorehouse** [comment]
This sounds like a css/scss issue with bootstrap v4.3

Basically missing the overflow ellipsis rules.

**Comment by tmorehouse** [comment]
We could also add maybe an optional formatter callback prop... which would be passed the array of file objects

**Comment by tmorehouse** [comment]
You could try adding the following utility classes to the `b-form-input`:

```html
<b-form-file class="text-nowrap text-truncate" ... ></b-form-file>
```

Note that due to the way that the the custom control "browse" is rendered with pseudo elements on the label, the `text-truncate` ellipsis will be hidden underneath the browse button.

**Comment by varunsingh87** [comment]
Adding those classes only seems to particular fix the issue:
![image](https://user-images.githubusercontent.com/31084854/181362738-38a87b2d-bde9-438b-b762-f1ad5e59dab7.png)

The text does not wrap to a new line, but it also does not stop behind the Browse button. I had to hardcode the width on the specific filename in order to fix this.

Here is my code (just the classes):
`<b-form-file class="text-truncate text-nowrap"></b-form-file>`
