### ISSUE TITLE
this.$root.$on('bv::modal::show', (bvEvent, modalId) => modalId is Emptry

### ISSUE THREAD

**Issue by sowinski** [bootstrap-vue/bootstrap-vue#2668]
Hi,

I am trying to read the modal open event for a specific modal. Unfortunately modalId is always undefined.

I have this peace of code from the code. Is this a bug? https://bootstrap-vue.js.org/docs/components/modal

```
  mounted() {
    this.$root.$on('bv::modal::show', (bvEvent, modalId) => {
      console.log(modalId);
      console.log(bvEvent);
    });
  },
```

**Comment by jackmu95** [comment]
@sowinski Do you have an ID (e.g. `id="modal1"`) defined on your `<b-modal>`?

I've tested it with the following markup on the [Playground](https://bootstrap-vue.js.org/play/) and it works as expected:
```vue
<template>
  <div>
    <b-button v-b-modal.modal1>Launch demo modal</b-button>

    <b-modal id="modal1" title="BootstrapVue">
      <p class="my-4">Hello from modal!</p>
    </b-modal>
  </div>
</template>

<script>
export default {
  mounted() {
    this.$root.$on('bv::modal::show', (bvEvent, modalId) => {
      console.log('Modal is about to be shown', bvEvent, modalId);
    });
  }
};
</script>
```

**Comment by sowinski** [comment]
@jackmu95 
Same for me. It is working.

I open the Modal like that:
`  methods: {
    open_add: function() {
        this.$root.$emit('bv::show::modal','modal-test-id')
    }
  }`
And my modal is not in the same component. Is this maybe the problem?

**Comment by jackmu95** [comment]
@sowinski This is also working as expected for me:
```vue
<template>
  <div>
    <b-button @click="openModal">Launch demo modal</b-button>

    <b-modal id="modal1" title="BootstrapVue">
      <p class="my-4">Hello from modal!</p>
    </b-modal>
  </div>
</template>

<script>
export default {
  mounted() {
    this.$root.$on('bv::modal::show', (bvEvent, modalId) => {
      console.log('Modal is about to be shown', bvEvent, modalId);
    });
  },
  methods: {
    openModal() {
      this.$root.$emit('bv::show::modal', 'modal1')
    }
  }
};
</script>
```

**Comment by sowinski** [comment]
@jackmu95 
I would like to build an example where the modal is within an different component. 
Do you know where I can build an example with different Components? (Because I guess this is causing the problem)

**Comment by sowinski** [comment]
This problem is solved in the last release (rc-13). Please close this issue (I don't know how)
