### ISSUE TITLE
<b-input-group-append> doesn't show in generated HTML

### ISSUE THREAD

**Issue by D-Marc1** [bootstrap-vue/bootstrap-vue#2669]
I'm using Chrome 72 on MacOS and using v2.0.0-rc.13 of BootstrapVue.

My code is as follows:

```
<b-input-group>
  <b-input-group-prepend>
    <b-button variant="outline-secondary">Button</b-button>
  </b-input-group-prepend>
  <b-form-input />
  <b-input-group-append>
    <b-button variant="outline-secondary">Button</b-button>
  </b-input-group-append>
</b-input-group>
```

In fact, anything I put after `<b-form-input />` is just removed from the DOM. Even just plain HTML. If i move `<b-input-group-append>` before it, then it works fine, but will obviously just prepend.

**Comment by jackmu95** [comment]
@D-Marc1 Can you please provide a live code example.

I've tried it with your exact markup at the [Playground](https://bootstrap-vue.js.org/play) and it's working as expected.

**Comment by D-Marc1** [comment]
@jackmu95 Thank you for the quick reply. Here's a [JSFiddle](https://jsfiddle.net/c6ugwoms/) showcasing the problem. Weirdly enough it does actually work on the Playground, but not on anything else.

**Comment by tmorehouse** [comment]
Appears to be an issue with how Vue is parsing the self closing tag for `<b-form-input />`.

See working version: https://jsfiddle.net/fbd4yh6o/

**Comment by D-Marc1** [comment]
@tmorehouse Great idea! Thanks for providing a solution that'll work meanwhile!
