### ISSUE TITLE
b-table doesn't update with array nested in object on version 2.0.0-rc.12 and 2.0.0-rc.13

### ISSUE THREAD

**Issue by williamtang007** [bootstrap-vue/bootstrap-vue#2671]
<b-table striped hover :fields="champsUpload" :items="r.files">

If r is an object containing an array accessible with r.files, the table with show objects in r.files when the page loads, but after when we try to push a new object to r.files, the table wouldn't upload. 
r.files.push({ filename: "blablabla.txt" });

However, if you do this:
r.files = [{ filename: "blablabla.txt" },{ filename: "blablabla.txt" },{ filename: "blablabla.txt" }];
It does update sometimes.

**Comment by tmorehouse** [comment]
This is a Vue reactivity issue. 

Try doing `r.files = [].concat(r.files, { filename: "blablabla.txt" })`

This will replace the array reference with a new array reference which will ensure Vue reactivity.

**Comment by williamtang007** [comment]
I tried installing bootstrap-vue@1.5.0 and 2.0.0-rc.0 and they seem to work, but 2.0.0-rc.12 and 2.0.0-rc.13 didn't work so far.

I also tried this to test if it's not r.files that is problematic, but the list works well. 
    <ul>
      <li v-for="item in r.files">
        *** {{ item.fileName }} ***
      </li>
    </ul>

**Comment by tmorehouse** [comment]
is the files array an array of actual `File` objects, or are they plain objects?

**Comment by williamtang007** [comment]
![image](https://user-images.githubusercontent.com/46502309/53118067-48e68700-351a-11e9-95cd-b9f6e6a7e0b8.png)

it's an array of ResumableFile objects (from resumable.js library), which I assume is plain object since in the source code it doesn't use File.call (so it's not a child of File).

**Comment by tmorehouse** [comment]
Could you provide a sample of your items array?

**Comment by tmorehouse** [comment]
@williamtang007 does this issue still persist in BootstrapVue v2.0.0-rc.15?

There have been udpates to the `looseEqual` comparison that is used by b-table.

**Comment by tmorehouse** [comment]
Closing as no response/stale.
