### ISSUE TITLE
Feature Request: Modals half page and full page

### ISSUE THREAD

**Issue by naveensnayak** [bootstrap-vue/bootstrap-vue#2672]
Can you please implement the half page and full page modals. They are really useful for mobile interfaces.
Modals should have he close button and be able to scroll. 
For half page modals, left or right position should be available. 
Modal animation options would also be great.

**Comment by tmorehouse** [comment]
Is this a feature supported/provided in Bootstrap V4.3 native (https://getbootstrap.com/docs/4.3/components/modal/)?

Have you noticed the new Scrollable modal content?  https://bootstrap-vue.js.org/docs/components/modal#scrolling-long-content 

Scrollable modals should resize in height to the currently displayed viewport height (which should account for the space occupied for the virtual keyboard).

**Comment by naveensnayak** [comment]
As far as I can tell, this is not supported in Bootstrap native. I did checkout the Scrollable modal and it works well for smaller screens. Was looking for something like this (See full screen option) https://vuetifyjs.com/en/components/dialogs 

I made a custom component for this, but it would be nice to have this available in the default modal component. This is why I submitted it as a feature request.  If the request is too trivial, please feel free to close it.
