### ISSUE TITLE
how to set true "if is active"?

### ISSUE THREAD

**Issue by nekooee** [bootstrap-vue/bootstrap-vue#2675]
I need to extended parent menu if one child is active. I use active-class="active" for active route when load page. but I need extended parent menu if this route is active. 
how can I use If is active?
please help me

**Comment by tmorehouse** [comment]
You could use the vue-router methods on this.$router and check the current route for an exact match (this.$route) and if it is true then set your active state.

**Comment by nekooee** [comment]
thank you. I wrote the following code :
```
 mounted: function () {
            if (this.$router.currentRoute.name === 'admin.dashboard') {
                alert('test');
            }
        }
```

But in this way, I have to define a condition for each route. Also, the routes are dynamical and I do not want to write one "if" for any one. can you help me?

**Comment by tmorehouse** [comment]
You could also use child `<router-view>` (or `<nuxt-child>` if using Nuxt) to render content based on route... or possibly named `<router-view name="...">` to target content based on route.
