### ISSUE TITLE
Modal representation breaks if I upgrade from v2.0.0-rc.11 to 12 or 13

### ISSUE THREAD

**Issue by sowinski** [bootstrap-vue/bootstrap-vue#2677]
Hi,

If I upgrade Bootstrap-vue from v2.0.0-rc.11 to 12 or 13 the representation of an open modal breaks.

If I write plain html code (Without Vue) it is working.
If I use bootstrap-vue component, then the representation of the modal breaks. The grey area of the modal is only in the div (Where I open the modal and also the modal itself it overlapped by my menu)

Any idea what could be wrong?

**Comment by sowinski** [comment]
Why is in the new release a static z-index of 2000 set to the modal?

https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/modal/modal.js#L46
This is one part of the problem

**Comment by tmorehouse** [comment]
The z-index is required for multiple stacked modal support.

Could you provide an example of the issue you are seeing? Maybe a screenshot or a jsfiddle?

**Comment by sowinski** [comment]
![modal](https://user-images.githubusercontent.com/1528746/53171040-ee186280-35e1-11e9-8083-ede35d05d3e9.jpg)
This is a screenshot. 

`style="position: relative; z-index: 2000;"` Is causing the problem

**Comment by sowinski** [comment]
I think the position has to be absolute instead of relative. What do you think?

**Comment by sowinski** [comment]
#2681

**Comment by sowinski** [comment]
Thank you for merging.

When is the next release planned? Is there any timeline or information on how often you create releases?

**Comment by tmorehouse** [comment]
We don't have an official release schedule, but rc.14 should be out this week.

**Comment by sowinski** [comment]
How can I install my own fork with npm?

I tried it like that:
npm install --save git+https://git@github.com/sowinski/bootstrap-vue.git

But it seems not work:
```
These dependencies were not found:

* bootstrap-vue in ./src/main.js
* bootstrap-vue/dist/bootstrap-vue.css in ./src/main.js
```
I would like to work with my own fork until you release the next version.
