### ISSUE TITLE
Use yarn to install bootstrap-vue v2.0.0-rc.13 fail

### ISSUE THREAD

**Issue by ycs77** [bootstrap-vue/bootstrap-vue#2679]
My Yarn version: v1.13.0

Reproduce step:
```
mkdir bootstrap-vue-yarn
cd bootstrap-vue-yarn
yarn add bootstrap-vue
```

As you can see, there is only one `node_modules` directory under `bootstrap-vue-yarn/node_modules/bootstrap-vue/`.

![bootstrap-vue v2 0 0-rc 13 fail - 1](https://user-images.githubusercontent.com/38133356/53172426-479f8200-3620-11e9-9f0e-32d81bb72031.jpg)

But it works fine when using NPM installation:
```
mkdir bootstrap-vue-npm
cd bootstrap-vue-npm
npm install bootstrap-vue
```

![bootstrap-vue v2 0 0-rc 13 fail - 2](https://user-images.githubusercontent.com/38133356/53172865-563a6900-3621-11e9-8df5-54b3b8f3eb66.jpg)

What is going on?

**Comment by ycs77** [comment]
To correct it, this is **not** a problem, it is a **error**. Please help solve it.

**Comment by tmorehouse** [comment]
`yarn add` always installs the module(s) in `node_modules` directory.  If you look inside the `node_modules` dir you will see a `bootstrap-vue` sub directory.

**Comment by ycs77** [comment]
As a result, clearing the yarn's cache is successful.
