### ISSUE TITLE
b-table nested keys in fields prop are not working after update

### ISSUE THREAD

**Issue by Brisstor** [bootstrap-vue/bootstrap-vue#2680]
Hello! 
After upgrading from  2.0.0-rc.10 to ^2.0.0-rc.13 it seems that <b-table> fields prop containing nested keys with array in it is not working anymore.

Before it used to works: 
` fields: [
            { label: 'Name', key: 'some.name' },
            { label: 'Id', key: 'some.id' },
            { label: 'Nested name', key: 'some.group.name' },     
            { label: 'Array name', key: 'array[0].some.name' },
            { label: 'Array Id', key: 'array[0].some.id' },
        ]`
Now the last 2 columns - Array name and Array Id won't be displayed.

And I'll be grateful for some tip how to use fields with such kind of structure.

Thank you!

**Comment by tmorehouse** [comment]
This is due to the change from lodash `get` to a non lodash `get` which works only with dotted notation and not array notation.

@pi0 we may need to get a new version of the `get` method that supports array notation like the previous lodash get.
