### ISSUE TITLE
SSR fails with checkbox @ 2.0.0-rc.13

### ISSUE THREAD

**Issue by varyen** [bootstrap-vue/bootstrap-vue#2682]
I'm using nuxt, page with `b-checkbox` on it fails with `Error in render: "ReferenceError: File is not defined"` error.

https://github.com/bootstrap-vue/bootstrap-vue/commit/401d3e974249c404df2d80282ccecae71baf57a7
I suppose this is the culprit, File isn't available in node.js environment.

**Comment by tmorehouse** [comment]
@jackmu95 we may need to do something similar to what was done for HTMLElement server side (polyfill for server side only) or add in a test for `!this.$isServer` before testing for is instanceof File.
