### ISSUE TITLE
Component table should there be virtual scrolls ?

### ISSUE THREAD

**Issue by boss225** [bootstrap-vue/bootstrap-vue#2684]
- When there is too much data to display when the table does not have paging, I searched for virtual scrolls but no.
- I'm using with this lib but it seems it doesn't work well
https://devexpress.github.io/devextreme-reactive/@next/vue/grid/docs/guides/virtual-scrolling/

**Comment by tmorehouse** [comment]
Partial Duplicate: https://github.com/bootstrap-vue/bootstrap-vue/issues/2777

The example provided above, while it works, it not overly accessible to screen reader users, as the table is broken into two tables (one of the header and one for the body), which means that the body row cells have no headers associated with them.

There are tricks one can do with CSS alone, styling the table sections as `display: block`, and `overflow: scroll; max-height: xxx;` on the tbody, but then the cells will need to have widths applied to each one to make sure the columns line up... quite a bit of work though.

See https://github.com/bootstrap-vue/bootstrap-vue/issues/2777#issuecomment-469915250 for example CSS to style a table (even `b-table`) with scrollable body, and a working example at https://jsfiddle.net/u7o4d3fe/ which uses `b-table`

**Comment by yoyoys** [comment]
@tmorehouse Virtual Scrolling is not sticky header,
It means make browser only render visual DOM.

example here: https://github.com/Akryum/vue-virtual-scroller
