### ISSUE TITLE
b-nav-item-dropdown: drop direction

### ISSUE THREAD

**Issue by ozakha** [bootstrap-vue/bootstrap-vue#2686]
Prop | Val
--- | ---
OS | Mac OS x
Browser | FF 65.0.1
BootstrapVue | 2.0.0-rc.13
Fiddle | [here](https://jsfiddle.net/j49aw2fe/1/)

There are no support of dropright/dropleft

**Comment by jackmu95** [comment]
`<b-dropdown>` supports `dropup`, `dropleft` and `dropright`.

Please see the docs:
https://bootstrap-vue.js.org/docs/components/dropdown#drop-right-or-left
