### ISSUE TITLE
Table: selectable programmatically

### ISSUE THREAD

**Issue by dorin-niscu** [bootstrap-vue/bootstrap-vue#2687]
**VueJS: 2.6.6**
**Bootstrap Vue: 2.0.0-rc.13**

Is it possible to preselect some rows from the start based on a parameter(**'_selectedRow'** for example like **'_rowVariant'**) or to select them programmatically?

The selected rows array is empty after refresh() method so I need a way to select the rows.

**Comment by lianee** [comment]
There is no way right now to select rows by code, but you can simulate clicks on rows: https://jsfiddle.net/p01fq27r/

I confess, it's a hack

**Comment by mhldtna** [comment]
I had to hack a way to do this because I have a use case where the table gets updated from an external source and the newly-added row should be selected automatically.

**Comment by dorin-niscu** [comment]
It would be helpful if we could append attributes to rows, I can add the id inside tbodyTrClass as workaround.

**Comment by tmorehouse** [comment]
Release 2.0.0-rc.14 will have a method for generating IDs for `tbody > tr` (using the `primary-key` field to generate the IDs. See PR #2694

**Comment by mhldtna** [comment]
Thanks, Troy.

**Comment by thejcannon** [comment]
If you're trying to select more than one row (in `select-mode="range"`), don't forget to simulate a "control-click"
```js
function rowID(item) { ... }

selectAll() {
  this.items.forEach(item => {
    if (!this.selectedItems.includes(item)) {
      document
        .getElementById(rowID(item))
        .dispatchEvent(new MouseEvent("click", { ctrlKey: true }));
    }
  });
}
```

**Comment by lucianobosco** [comment]
What about if rows aren't selected by click event? I'm selecting rows through a checkbox that dispatches a method.
```
selectRow (event, data) {
            if (event) {
                data.selectRow(data.index)
                this.selectedResources.push(data.item.id)
            } else {
                data.unselectRow(data.index)
                this.selectedResources = this.selectedResources.filter(item => item !== data.item.id)
            }
        },
```
Now I just want to select rows after Axios request is done. It's for pagination purposes so I want to select those rows that were previously selected.
Any advice will be appreciated.
