### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "sortDesc". Expected Boolean, got String with value "true".

### ISSUE THREAD

**Issue by mhldtna** [bootstrap-vue/bootstrap-vue#2692]
I see this error in the console when I add "sort-desc=true" as a b-table property:

`[Vue warn]: Invalid prop: type check failed for prop "sortDesc". Expected Boolean, got String with value "true".`

The attached example shows the problem. Note that the "sort-desc" property is set to the literal value _true_.  The same error message appears if I quote _"true"_.  The error goes away if I bind the sort-desc property to a variable that is set to true, as in:

`:sort-desc="sortOrder"`

Note: the documented property name is "sort-desc" but the error message says "sortDesc".

I am using Windows 10 with Chrome Version 72.0.3626.109 (Official Build) (64-bit), and bootstrap-vue@2.0.0-rc.13.

I've attached a file that shows the problem.  (The file extension should be .vue, not .txt, but GitHub won't let me upload a .vue file).

[Test.txt](https://github.com/bootstrap-vue/bootstrap-vue/files/2895531/Test.txt)

**Comment by tmorehouse** [comment]
Internally in Vue, props are referenced in their `camelCase` name (so prop `foo-bar` is referenced internally as `fooBar`).

In your example file:
```html
<template>
  <div>
    <b-table
      :items="items"
      :fields="fields"
      sort-by="field1"
      sort-desc=true
    >
    </b-table>
  </div>
</template>
```
you should be using:

```html
<template>
  <div>
    <b-table
      :items="items"
      :fields="fields"
      sort-by="field1"
      sort-desc
    >
    </b-table>
  </div>
</template>
```

Or:

```html
<template>
  <div>
    <b-table
      :items="items"
      :fields="fields"
      sort-by="field1"
      :sort-desc="true"
    >
    </b-table>
  </div>
</template>
```

**Comment by mhldtna** [comment]
Thank you Troy, for the quick answer.  That fixed it.  (I should have remembered that you specify boolean HTML prop values that are true by omitting the "=true". Sheesh.)
