### ISSUE TITLE
Feature request: add 'id' attribute to <tr> elements of table row

### ISSUE THREAD

**Issue by mhldtna** [bootstrap-vue/bootstrap-vue#2693]
Please add a prop like this to b-table: `:id=function`, where "function" is a function that returns an identifying value for the row.  Add a "id=function result" attribute to each <tr> element of the generated HTML table.

This provides a way for methods to correlate each row back to the original item that contains the data for the row.  Use cases for this include:

- Accessing some data that is associated with the table row but not actually displayed in the table row.
- Implementing some unusual form of scrolling or otherwise dynamically modifying the table.
- Developing some unusual variation of scrollspy.

See this [stackoverflow item](https://stackoverflow.com/questions/51541671/make-bootstrap-vue-b-table-id-column-invisible/54836148#54836148) for a similar request.

**Comment by tmorehouse** [comment]
How are you suggesting that the ID's be generated?  using the row index (i.e. starting from row 0, as rendered)? using the `primary-key` column values (and what if no primary key is provided)?  Should the IDs be unique per row item data, or just unique per displayed row (i.e. what happens to the ID when sorting or filtering)?

Can you explain (or provide a use case example) why this may be needed?

**Comment by mhldtna** [comment]
I am suggesting that the user-provided method (from the id="method" prop) would return the id value as a result.  bootstrap-vue would invoke this method once for each row in the table when re-rendering the row. The method would return some value which bootstrap-vue would attach to the <tr> element as an "id" attribute. The application could use this value to map back to the original item.

I would expect this id to be unique per row item data, but that would be up to the developer's code.

The only relationship this proposal has with the primary-key prop is that it would often be convenient to use the same value for both the id and the primary-key.

My use case is a requirement to be able to add a new entry to the items array and have it selected and scrolled into view if necessary.  In the case where the table is larger than the viewable area, and hence has a scroll bar, the "scrolled into view if necessary" requirement means figuring out whether the entry is or is not in the viewable area.

[A related missing feature is a way to force an item to be selected.  I implemented my own selection support months ago, before "selectable" and related features became available. The inability to programmatically set which item is selected prevents me from replacing my own implementation with the new builtin selection-related support.]

**Comment by tmorehouse** [comment]
I think using the `primary-key` value to set an `id` on the body's tr's would be the easiest and best solution (as one would need to have a unique ID in the items data in order to generate the id).

**Comment by mhldtna** [comment]
I think that would fulfill the basic requirement.  I am a little suspicious about tying these two different use cases to each other, but I admit it would be simpler to have one prop.
