### ISSUE TITLE
beforeRouteLeave and bootstrap-vue modal

### ISSUE THREAD

**Issue by fessacchiotto** [bootstrap-vue/bootstrap-vue#2702]
How I can show the bootstrap-vue modal, and wait for the user feedback (‘ok’ or ‘cancel’), and only then execute the next() clause? As per the below code, the modal is shown to the user only after this.answer has been evaluated. TIA

```html
    <b-modal ref="leaveModal" id="leaveModal" size="sm" centered :title="$t('title')" @ok="handleLeaveModalOk" ok-variant="primary" :ok-title="$t('go')" @cancel="answer='Cancel'" :cancel-title="$t('cancel')">
      <p class="my-4 text-center">{{ $t('confirm') }}</p>
    </b-modal>
```
``` js
  beforeRouteLeave (to, from, next) {
    this.showLeaveModal() 
    //const answer = window.confirm('Do you really want to leave? you have unsaved changes!')
    debugger; 
    if (this.answer == 'OK') {
      next()
    } else {
      next(false)
    }
  },
  data() {
    return {
      answer: null,
    }
   },
  methods: {
    showLeaveModal() { this.$refs.leaveModal.show() },
    handleLeaveModalOk() {
      this.answer = 'OK'
    },
  }
```

**Comment by tmorehouse** [comment]
Modals run asynchronously, unlike the native confirm dialog which blocks execution until an answer is clicked, and returns to your code.

MOdals are event based.  They emit a `hide()` event before being hidden, which receives a BV Event object (which contains the button or trigger that causes the hide to occur).

See the "prevent closing" example https://bootstrap-vue.js.org/docs/components/modal#prevent-closing

**Comment by tmorehouse** [comment]
You should also call `next()` on the modal `hidden` event, to make sure modal has completely closed/finished transitioning before allowing the route change to proceed.

```js
  beforeRouteLeave (to, from, next) {
    this.showLeaveModal() 
    if (this.answer == 'OK') {
      this.$refs.leaveModal.$once('hidden', () => {
        next()
      })
    } else {
      next(false)
    }
  }
```
