### ISSUE TITLE
b-nav-item-dropdown execute code when assembling component when it should not do

### ISSUE THREAD

**Issue by StalynHD** [bootstrap-vue/bootstrap-vue#2703]
This code must execute only when you click in Execute foo, but it runs when mounting component, Why is it executed? 

```
<b-nav-item-dropdown>
          <template slot="button-content">
          <em>Button</em>
        </template>
        <b-dropdown-item href="#">
<a href="" :click="foo()">Execute foo</a></b-dropdown-item>
        </b-nav-item-dropdown>
<script>
export default {
  methods: {
    foo() {
      console.log("executing methods");
    },
  }
}
</script>
```

**Comment by tmorehouse** [comment]
One issue, you are embedding an anchor (`a`) inside a `b-dropdown-item` which also has an `href`, which is invalid HTML.

Place the click handler on `b-dropdown-item`

```html
<b-nav-item-dropdown>
  <template slot="button-content">
    <em>Button</em>
  </template>
  <b-dropdown-item :click="foo">
    Execute foo
  </b-dropdown-item>
</b-nav-item-dropdown>
```

The other issue is that you are specifying the click handler as `foo()` (with no arguments), not `foo`.

When specified as `foo()`, Vue will execute the function, expecting it to return a handler function.
