### ISSUE TITLE
[question] bootstrap table 

### ISSUE THREAD

**Issue by vishnug1995** [bootstrap-vue/bootstrap-vue#2705]
after page reload, i get a error like this in bootstrap vue table  

[Vue warn]: Error in render: "TypeError: Cannot create property 'name' on boolean 'true'"

TypeError: Cannot create property 'name' on boolean 'true'

**Comment by jackmu95** [comment]
@vishnug1995 Can you please create an online demo of your issue or share some more details about your code.

**Comment by bezumkin** [comment]
I have the same problem with slots inside Table component, maybe it came after last update to 2.0.0-rc.13.

I see it every time when update something **not** in Table with hot reload in dev-server.

![screenshot 2019-02-25 at 15 32 49](https://user-images.githubusercontent.com/1257284/53324170-b1ff3d80-3912-11e9-9300-7dae2864b432.png)

If I comment out all slots in table there are no errors anymore.

**Comment by jackmu95** [comment]
@bezumkin Can you please create an online demo of your issue or share some more details about your code.

**Comment by bezumkin** [comment]
@jackmu95 I [recorded video for you](https://file.modx.pro/files/9/c/a/9caa2556f5ca1cc61228e3d5a0e3be34.mp4)

here is my code, if you need
```html
<template lang="html">
    <div>
        <b-table stacked="md" class="mt-5"
                 id="users-table"
                 :items="items"
                 :fields="fields"
                 :current-page="page"
                 :per-page="limit"
                 :sort-by.sync="sort"
                 :sort-direction.sync="dir"
                 show-empty
                 no-sort-reset>
            <template slot="role_id" slot-scope="row">{{roles[row.value] ? roles[row.value].title : row.value }}</template>
        </b-table>

        <b-row no-gutters class="justify-content-center justify-content-md-start mt-5">
            <b-pagination class="m-0" :total-rows="totalRows" :per-page="limit" :limit="7" v-model="page"/>
        </b-row>
    </div>
</template>

<script>
    export default {
        name: 'Users',
        data() {
            return {
                items: [{
                    "id": 1,
                    "username": "admin",
                    "fullname": "admin",
                    "active": true,
                    "role_id": 1
                }, {
                    "id": 2,
                    "username": "bezumkin",
                    "fullname": "bezumkin",
                    "active": false,
                    "role_id": 2
                }],
                roles: {
                    "1": {
                        "id": 1,
                        "title": "admin"
                    },
                    "3": {
                        "id": 3,
                        "title": "promoter"
                    },
                    "2": {
                        "id": 2,
                        "title": "supervisor"
                    }
                },
                fields: [
                    {key: 'username', label: 'Login', sortable: true},
                    {key: 'fullname', label: 'Fullname', sortable: true},
                    {key: 'role_id', label: 'Group'},
                ],
                page: 1,
                limit: 10,
                totalRows: 2,
                sort: 'username',
                dir: 'asc',
            }
        },
        created() {
            document.title = 'Admin / Users';
        }
    }
</script>
```

**Comment by jackmu95** [comment]
I've created a [demo](https://codesandbox.io/s/pmjjvlq5xj?fontsize=14) on CodeSandbox and I don't get your error with Vue.js v2.6.7 and BootstrapVue v2.0.0-rc.13.

**Comment by bezumkin** [comment]
@jackmu95 I have this error **only** with `webpack-dev-server` and only when I change something not in Table component (as you can see on my video). This problem totally disappear if I comment out or remove all `<template slot="">` from Table.

Error is only in browsers log, not in terminal. And it affect only hot reload of page, so it is not big deal. 
Maybe it something with my environment, and I will wait for responses from another users.

**Comment by tmorehouse** [comment]
Which version of Vue are you using? 2.5+ or 2.6+?

**Comment by bezumkin** [comment]
@tmorehouse `"vue": "^2.6.7",`

**Comment by tmorehouse** [comment]
@bezumkin could you click on the `index.js` link in the error:

![image](https://user-images.githubusercontent.com/2781561/53353228-a6a01800-38fa-11e9-8386-1df2d709d8ec.png)

And capture the code that it highlights as the error?  I'm not sure what index.js file it is erroring in.

**Comment by bezumkin** [comment]
@tmorehouse 
<img width="920" alt="screenshot 2019-02-25 at 23 46 01" src="https://user-images.githubusercontent.com/1257284/53353540-8c485780-3957-11e9-99ab-5db90fc07289.png">

**Comment by tmorehouse** [comment]
OK that code has nothing to do with b-table, as does the rest of the stack trace (which the majority is related to `vue.esm.js`).

It sounds like it is either something in your code (which is placing a Boolean into a variable that expects to have properties, or it is a bug in server-rednerer, or a bug in vue when working with hot-reload.

I would suggest deleting your yarn.lock (or package.lock) files, and then `yarn install && yarn upgrade` to update your packages to make sure you have the latest releases of everything.

**Comment by bezumkin** [comment]
@tmorehouse No, deleting of `.lock` is not helping.

I believe it is something with hot-reload, because I see the error only here, in browser log. There are no errors on regular build or watch, only in dev-server.

Anyway, it is not bother me, just shared my case for others. Thank you for your time and such a great product!

**Comment by chumager** [comment]
It happened the same to me, seems to be a Vue problem, I had the 2.6.6 version and everything was ok, then upgraded to 2.6.8 and got several problems with slots, even though I changed to the new way to use slots, after lots of debug downgrade to 2.6.6 and all worked out...
