### ISSUE TITLE
<b-tabs> loss of <b-tab> control as of rc12 when used in lazy load modals

### ISSUE THREAD

**Issue by vesper8** [bootstrap-vue/bootstrap-vue#2707]
I've been using https://github.com/euvl/vue-js-modal for my modals in all my projects and I've been using this in combination with bootstrap-vue for over a year without issue.. 

I noticed some breakage after upgrading to rc12, and now rc13. I forced the version back to rc11 just to confirm and indeed it works fine on rc11 but rc12 and rc13 introduces an issue

the issue is this:

If you put b-tabs inside of a modal, upon opening the modal for the first time everything works fine, but if you close the modal and reopen it, then the tabs don't work, it will be stuck on the content of the first tab, and switching tabs will not have any effect, instead the content of the first tab will remain visible. Reloading the page is the only way to get it to work again.

I'm probably going to switch to using bootstrap-vue's modals now, largely because I love the new stacking modals feature, but wanted to point out this "regression". No idea what might be causing it.

**Comment by vesper8** [comment]
oooh.. actually it appears I found a bug! After porting to bootstrap-vue's modal everything was working again.. but I noticed that unlike with https://github.com/euvl/vue-js-modal, all my modal's contents were being mounted immediately, not only once the modal was made visible

I then tried setting the lazy prop to true to avoid this.. and then the b-tabs problem started again!

I tested this on a stripped down example and sure enough the problem exists!

Here's a simple code sample that shows the bug

```

  <div>
    <b-button v-b-modal.modal1>
      Launch demo modal
    </b-button>

    <!-- Modal Component -->
    <b-modal
      id="modal1"
      title="BootstrapVue"
      :lazy="true"
    >
      <b-tabs content-class="mt-3">
        <b-tab
          title="first"
          active
        >
          I'm the first fading tab
        </b-tab>
        <b-tab title="second">
          <p>
            I'm the second tab content
          </p>
        </b-tab>
        <b-tab
          title="disabled"
          disabled
        >
          <p>
            Disabled tab!
          </p>
        </b-tab>
      </b-tabs>
    </b-modal>

  </div>

```

And here's the jsfiddle https://jsfiddle.net/tg8m1cdo/

Upon opening the modal the first time, the tabs work, then if you close the modal and open it again, they stop working

**Comment by tmorehouse** [comment]
Modals have a prop `lazy` which will prevent the content from being mounted until the modal is shown.

https://bootstrap-vue.js.org/docs/components/modal#lazy-loading

```html
<b-modal lazy ... >
  <some-component ...>
    <!-- content -->
  </some-component>
</b-modal>
```

In the future we will be using Portal-Vue for modal (as well as tooltips/popover, and the forthcoming toasts) for placement in the DOM, and modals will always be "lazy".

**Comment by tmorehouse** [comment]
Interesting.

We'll need to dive into this a bit.  It might be a timing issue when the `b-tabs` render and instantiate the tabs button listeners.

**Comment by tmorehouse** [comment]
It appears the tab buttons ware working, but they are not triggering the display of the corresponding tab.

**Comment by tmorehouse** [comment]
After playing with the code a bit, if I run `updateTabs()` (an internal method that updates the list of b-tab's inside b-tabs), the tab panes start working again.

So it is definitely related to when the internal list of tabs gets updated.

**Comment by vesper8** [comment]
awesome! nice to see a fix added so fast! i hope it makes it in time for rc14!

**Comment by tmorehouse** [comment]
Assuming I can figure out exactly what is going on... tried a few things which I though might work, but so far no luck.

**Comment by tmorehouse** [comment]
I'm wondering if this was a interrelated bug introduced in Vue 2.6.x due to how they revamped nextTick queue handling.  There is an updated Vue now, and will see if this issue still exists.

**Comment by tmorehouse** [comment]
Still having issues determining the root cause of this bug.

I guess the current workaround would be to not have the modal lazy, and then set the lazy prop set on the b-tabs component to hide the tab content when not active (to minimize the amount of DOM elements in document)

**Comment by wormen** [comment]
for nuxt@2.6.2 problem this problem still exists

**Comment by tmorehouse** [comment]
@wormen this is not a nuxt related issues.

**Comment by wormen** [comment]
@tmorehouse possible, but the problem is the same

**Comment by tmorehouse** [comment]
@vesper8 can you check to see if hte lateat releease 2.0.0-rc.19 has fixed you issue?

Your jsfiddle is now working https://jsfiddle.net/tg8m1cdo/

**Comment by vesper8** [comment]
@tmorehouse I just went back and checked all versions from rc12 (first breakage introduced) to rc19 one by one

I can confirm the issue I reported was no longer occurring as of rc17

good job guys!! been loving the pace of updates in the past few weeks!

**Comment by tmorehouse** [comment]
Excellent.

**Comment by rich25200** [comment]
Hi,

I have the same issue in RC20... Anyone have a solution ?

**Comment by vesper8** [comment]
dang.. indeed.. there's a regression! this was fixed!

You can see my jsfiddle demo is once again broken when using the latest RC20 https://jsfiddle.net/tg8m1cdo/

@tmorehouse
