### ISSUE TITLE
Feature Request - scrollspy - add support for to attribute in addition to href

### ISSUE THREAD

**Issue by kubowler99** [bootstrap-vue/bootstrap-vue#2722]
Per the bootstrap-vue scrollspy documentation, it only supports the href attribute. Per the vuejs documentation, the vue-router does support anchor tag routing after making a slight modification to the router scrollBehavior method, coupled with using the 'to' attribute on the router-link element. Unfortunately, with scrollspy's limited support (for only href), any routing using the anchor tags (for example /my-page#firstanchor) will not render correctly.

**Comment by tmorehouse** [comment]
ScrollSpy grabs the `HREF`s after the DOM has rendered (so doesn't know if the HREF is from a router link or not).

We would need to add in `$router` `$route` match testing (if router detected) to see if the _prefixed_ `HREF` is the current page or not.

**Comment by tmorehouse** [comment]
Are you referring to using vue-router's `hash` method of routing (rather than pushState)?

Such as `https://example.com/#/foo/bar#id-value`?

**Comment by kubowler99** [comment]
Yes.

**Comment by tmorehouse** [comment]
Hmmm... might be able to add in a check for `this.$router` presence, and then check for '/#\//` and `/#[^/]/` for matching the hash.

Do you have an example of a rendered router link with it's `href`, and the corresponding `id` on hte element that would place the link in the active state? (we would still need to match on the `href` attribute, as SrollSpy runs post render)
