### ISSUE TITLE
Missing CSS in 2.0.0-rc.12 and 2.0.0-rc.13?

### ISSUE THREAD

**Issue by commandtab** [bootstrap-vue/bootstrap-vue#2725]
I have a fairly simple Nuxt project that currently depends on bootstrap-vue `2.0.0-rc.11`, but when I upgrade to `2.0.0-rc.12` or `2.0.0-rc.13`, the Bootstrap CSS is absent, leaving my pages looking rather sparse. (I've also tried removing `node_modules/` completely between `package.json` changes.)

Has anyone else observed this?

**Comment by tmorehouse** [comment]
Duplicate of #2629 (and others).  

Will be fixed in 20.0.0-rc.14

**Comment by tmorehouse** [comment]
See https://github.com/bootstrap-vue/bootstrap-vue/issues/2629#issuecomment-466689199 for a workaround.

**Comment by commandtab** [comment]
Ah, thanks! I looked, but didn't see that issue.
