### ISSUE TITLE
checkbox indeterminate not honoured

### ISSUE THREAD

**Issue by akhchan99** [bootstrap-vue/bootstrap-vue#2726]
`<b-form-checkbox v-model="checked" :indeterminate="notCompleted"/>`

if set notCompleted to true and checked to false

When loaded, it will show the checkbox with a dash, this is good.
Then when I click on the checkbox, it will changed to a check mark, ignoring the state of indeterminate.

If this is by design, is there anyway to persist the state of indeterminate regardless of what the checked value is? so that the checkbox will toggle between "unchecked" and "indeterminate" state?

**Comment by tmorehouse** [comment]
When a value of a checkbox changes state (via user interaction), the browser will remove the indeterminate state, as it is no longer indeterminate. This is expected behaviour.

You would need to add your own logic to watch for changes in `checked` state (`v-model`) of the checkbox, and reset the `indeterminate` prop to `true`.

**Comment by akhchan99** [comment]
I tried
`<b-form-checkbox @changed="setIndeterminate" v-model="checked" :indeterminate="notCompleted"/>`

and in the setIndeterminate method, I set the "notCompleted" to true again, but the checkbox stays as a checkmark instead of a dash

**Comment by tmorehouse** [comment]
indeterminate is a syncable prop.  Vue isn't detecting the change in state.

Do this:
```html
<b-form-checkbox @changed="setIndeterminate" v-model="checked" :indeterminate.sync="notCompleted"/>
```

**Comment by akhchan99** [comment]
Additional info which might help other...

after adding .sync to the indeterminate, it still doesn't work, because the browser override the value of indeterminate which is set in setIndeterminate, so I uses nextTick to set the indeterminate value and that updated the prop in the next event, and the sync update the GUI.

Thanks @tmorehouse

**Comment by ravipatel6** [comment]
indeterminate.sync is not working for IE other browser can understand but IE doesn't do we have any other fix ?
