### ISSUE TITLE
Popovers are not destroyed

### ISSUE THREAD

**Issue by paglias** [bootstrap-vue/bootstrap-vue#273]
When i navigate to a different route or simply change the content of the page to display something different the popovers already in the HTML are not destroyed but simply hiddens.

Is this a bug or the wanted behavior?

<img width="1081" alt="schermata 2017-04-23 alle 15 55 12" src="https://cloud.githubusercontent.com/assets/589911/25314089/4414df56-283d-11e7-9fde-58678bdf3c62.png">

**Comment by SirLamer** [comment]
I have been considering options for how to improve that. What happens is that Tether moves them around after first display, and pulls the elements to the end of the body upon doing so. Not destroying them doesn't really hurt anything, but messing with them will likely make Vue reactivity more difficult.

**Comment by paglias** [comment]
I see, as long as all event listeners are destroyed it's not a big deal if the markup stays in the html, feel free to close the issue

**Comment by SirLamer** [comment]
For what it's worth, there is a good argument that this is more of a problem with Tether than anything else, and there is a three year old issue thread about it here, you'll notice that I commented there about this a few days ago.

https://github.com/HubSpot/tether/issues/36

**Comment by pi0** [comment]
Popovers migration plan in active in #287 . Please follow there :)
