### ISSUE TITLE
b-form-file multiple not working

### ISSUE THREAD

**Issue by perez0711** [bootstrap-vue/bootstrap-vue#2730]
Prop `multiple` not working.

I am trying to upload multiple files in a same <b-form-file>, but when sending more than one file, the component only keeps the last file.

Example: 
https://jsfiddle.net/perezga/g7szan6b/

OS: Ubuntu 18.04
Browsers: Chrome 71
Bbootstrap: 4.1.3
Bootstrap Vue: 2.0.0-rc.13

**Comment by demyan1411** [comment]
I have the same Issue

**Comment by tmorehouse** [comment]
@demyan1411 make sure you are using the latest BootstrapVue version 92.0.0-rc.19)

If you are using a validator plugin, make sure it is also updated to the latest version.

**Comment by Chuweiii** [comment]
@gabrielsperezz sorry to bother but have you found the solution to this problem?
