### ISSUE TITLE
b-form-checkbox switch question

### ISSUE THREAD

**Issue by sh4rk60800** [bootstrap-vue/bootstrap-vue#2736]
Hello,

the element is not working:
 <b-form-checkbox switch  v-model="myCheckbox" name="check-button"></b-form-checkbox>

I only have a blue/grey (true/false) square instead of a switch button

![image](https://user-images.githubusercontent.com/33662349/53566342-27aa1a00-3b5c-11e9-8f39-8af7010eb493.png)

regards, 

Kévin

**Comment by tmorehouse** [comment]
Could you provide more details... such as the versions of Bootstrap Vue and version of Bootstrap CSS/SCSS?

Also could you provide sample markup or a reduced test case jsFiddle?

**Comment by sh4rk60800** [comment]
the bootstrap-vue version is 2.0.0-rc.13 and the bootstrap version is 4.1.3

I have downloaded bootstrap version 4.3.1 and it's now OK.

thanks.

regards,

Kévin



Le jeu. 28 févr. 2019 à 14:47, Troy Morehouse <notifications@github.com> a
écrit :
