### ISSUE TITLE
Feature request: Generic HEAD slot for b-table

### ISSUE THREAD

**Issue by sylvinus** [bootstrap-vue/bootstrap-vue#2737]
Hello!

Custom headers via scoped slots are a great feature of `b-table`:
https://bootstrap-vue.js.org/docs/components/table#headerfooter-custom-rendering-via-scoped-slots

However, it would be great to have a generic `HEAD` slot that is valid for all fields to be able to customize all column headers at once.

thanks!

**Comment by tmorehouse** [comment]
Please see: #2653

Coming next release.

**Comment by sylvinus** [comment]
Ah great!! Thanks @tmorehouse
