### ISSUE TITLE
`size` and `stacked` don't work well together on `b-form-radio-group`

### ISSUE THREAD

**Issue by markrian** [bootstrap-vue/bootstrap-vue#2743]
When you supply the `size` and `stacked` props to a `b-form-radio-group`, the group's element is given a fixed height (incorrectly) by the `form-control-${size}` class, meaning that the child `b-form-radio`s are clipped, or they obscure any content below.

OS: Ubuntu 18.04.2 (although I'm sure it applies everywhere)
Browsers: tested on Firefox 65 and Chromium 71 (but, as above)
BootstrapVue version: 2.0.0-rc.13
Test case: https://jsfiddle.net/markrian/96Lbqwyx/10/

You can also see this happen if you go to the [docs](https://bootstrap-vue.js.org/docs/components/form-radio/#inline-or-stacked-radios) and add `size="sm"` or `size="lg"` to the stacked example.

**Comment by tmorehouse** [comment]
Officially, Bootstrap V4.x doesn't support sizes on radios and checkboxes, and the use of `form-control-{size}` on checkboxes and radios is an interim hack until V5.x of bootstrap Vue.

See https://github.com/twbs/bootstrap/issues/27803 and https://github.com/twbs/bootstrap/issues/27958

**Comment by markrian** [comment]
Sure, but the issue, I think, is that the `form-control-${size}` class is being applied twice: once to the per-input `div.form-check`, and again to its parent `div[role="radiogroup"]`. The latter is the problem, since that element wraps the entire group of inputs, and is having its height set assuming it's just one input.
