### ISSUE TITLE
b-pagination-nav ssr error

### ISSUE THREAD

**Issue by nezzard** [bootstrap-vue/bootstrap-vue#2744]
Hi, when i'm using b-pagination-nav  with nuxt, i'm getting an error, can someone explain what i'm doing wrong?

`<b-pagination-nav :use-router="true" :link-gen="linkGen" :number-of-pages="10" v-model="page" />`

**The client-side rendered virtual DOM tree is not matching server-rendered content.**

**Comment by tmorehouse** [comment]
Does both the server side and client side have the same `v-model` value, or does any value change between server side and client side?

p.s. you can shorten above to this:

```html
<b-pagination-nav use-router :link-gen="linkGen" :number-of-pages="10" v-model="page" />
<!-- or, if linkGen returns a route object { path: '....', name: '..., etc } -->
<b-pagination-nav :link-gen="linkGen" :number-of-pages="10" v-model="page" />
```

**Comment by tmorehouse** [comment]
Also, could you provide an example of your `linkGen` code?

**Comment by nezzard** [comment]
> Also, could you provide an example of your `linkGen` code?

`linkGen(pageNum) {
      return { path: '/', query: { page: pageNum }}
    }`

**Comment by tmorehouse** [comment]
OK, was just curious to see if you were using any special characters in your linkGen/pageGen functions (as they can sometimes cause SSR mismatch errors when the browser converts HTML entities into native unicode characters.

And if you remove the pagination-nav component, does the error go away?

What version of Bootstrap-Vue are you using (2.0.0-rc.13)?

**Comment by nezzard** [comment]
> OK, was just curious to see if you were using any special characters in your linkGen/pageGen functions (as they can sometimes cause SSR mismatch errors when the browser converts HTML entities into native unicode characters.
> 
> And if you remove the pagination-nav component, does the error go away?
> 
> What version of Bootstrap-Vue are you using (2.0.0-rc.13)?

B version ^2.0.0-rc.13
Nuxt ^2.0.0

And there is no errors when i'm removing b-pagination-nav

**Comment by tmorehouse** [comment]
Also have you tried just returning a string (with and without using `use-router` prop), i.e.:

```js
linkGen(pageNum) { return '/?'+pageNum }
```

Also you should try with the newest Nuxt version `2.4.5`

**Comment by nezzard** [comment]
> Also have you tried just returning a string (with and without using `use-router` prop), i.e.:
> 
> ```js
> linkGen(pageNum) { return '/?'+pageNum }
> ```
> 
> Also you should try with the newest Nuxt version `2.4.5`

Nothing help  (
Can i debug error in vue dev tools?

**Comment by tmorehouse** [comment]
You should be able to use DevTools if your app is running in `dev`  mode (not production).

**Comment by nezzard** [comment]
> You should be able to use DevTools if your app is running in `dev` mode (not production).

I'm in dev mode

**Comment by nezzard** [comment]
> You should be able to use DevTools if your app is running in `dev` mode (not production).

Maybe this can help? http://prntscr.com/mso5mn

**Comment by tmorehouse** [comment]
Hmmm it is the First Page text that is causing the SSR issue... (which also means the prev, next, last, and possibly ellipsis buttons.

We had a similar issue with `b-button-close` and the `&times;` character. (some browsers convert the entity to a test string and Vue complains that the characters are not the same).

What version of Vue are you using?

**Comment by nezzard** [comment]
> <meta charset="utf-8">

Yes

Vue veriosn, which Nuxt included

**Comment by tmorehouse** [comment]
In your screen shot:

![image](https://user-images.githubusercontent.com/2781561/53699520-7a374080-3dbf-11e9-8117-f6b865b0869a.png)

Could you expand the highlighted arrays and post another screen shot of that?

**Comment by nezzard** [comment]
> In your screen shot:
> 
> ![image](https://user-images.githubusercontent.com/2781561/53699520-7a374080-3dbf-11e9-8117-f6b865b0869a.png)
> 
> Could you expand the highlighted arrays and post another screen shot of that?

First: 
http://prntscr.com/msoev0
http://prntscr.com/msof39
http://prntscr.com/msof7x

Second:
http://prntscr.com/msoffe
http://prntscr.com/msofjk
http://prntscr.com/msofr9

**Comment by tmorehouse** [comment]
PR https://github.com/bootstrap-vue/bootstrap-vue/pull/2757 may address this issue (but not positive)

**Comment by edgarsn** [comment]
I had the same problem, but updating packages solved the problem.

Updated to:

- Vue: **2.6.8** (from _2.6.7_)
- Bootstrap-Vue: **2.0.0-rc.14** (from _2.0.0-rc.13_)

**Comment by tmorehouse** [comment]
Appears to have been an issue in Vue 2.6.7.
