### ISSUE TITLE
Tooltip in table with one row causes constant blinking

### ISSUE THREAD

**Issue by dbonness** [bootstrap-vue/bootstrap-vue#2753]
```html
                        <b-table
                                small
                                hover
                                responsive
                                :fields="fields"
                                :items="data"
                        >
                            <template slot="active" slot-scope="data">
                                <span v-html="activeFormatter(data.item.active)"></span>
                            </template>
                            <template slot="actions" slot-scope="data">
                                <b-button
                                        v-b-tooltip.hover
                                        title="Edit Roster"
                                        size="sm"
                                        @click="edit(data.item)"><i class="fa fa-edit"></i>
                                </b-button>
                                <b-button
                                        size="sm"
                                        variant="danger"
                                        @click="destroy(data.item)"><i class="fa fa-trash"></i>
                                </b-button>
                                <b-button
                                        size="sm"
                                        variant="success"
                                        @click="view(data.item)"><i class="fa fa-list"></i>
                                </b-button>
                            </template>
                        </b-table>
```

Using tooltip code inside of a table causes issues when there is only one row of data. Once I add a second row of data to the table it works properly. Just one row the tool tip blinks on and off constantly and the button it is attached to no longer works.

**Comment by tmorehouse** [comment]
This is because of how `Popper.js` is determining the boundary element that tooltip is trying to stay inside.

You will need to specify the `boundary` option in the tooltip "config" options:

```html
<b-button v-b-tooltip.hover="{boundary: 'viewport'}" ... >
<!-- or the shorthand way-->
<b-button v-b-tooltip.hover.viewport ... >
```

The `boundary` option accepts the string values `scrollParent` (the default), `window`, and `viewport`. `window` and `viewport` will also work as modifiers for the directive (as shon in the second example above).

See working fiddle here: https://jsfiddle.net/nygae1kr/

and a list of options for the tooltip: https://bootstrap-vue.js.org/docs/directives/tooltip#directive-syntax-and-usage

**Comment by tmorehouse** [comment]
Additional explanation:

tooltips (and popovers) default to containing their position based on the trigger element's scrolling parent. (the `scrollParent` boundary)

In tour case, the table is in responsive mode (meaning it can scroll left and right on small screens if the table overflows the wrapper `div.table-responsive` element.  When the table is not in responsive mode, the tooltip doesn't flicker, ans the scroll parent is higher up in the document (i.e. the body)

Using `viewport` or `window` as the boundary element tells `Popper.js` (the library that handles tooltip and popover, as well as dropdown positioning) to uses the visible page area as the boundary to keep the tooltip position within.

**Comment by dbonness** [comment]
Cool works well for me now. Thanks for the explanation
