### ISSUE TITLE
bTable does not render fields containing a . as key value

### ISSUE THREAD

**Issue by gbin94** [bootstrap-vue/bootstrap-vue#2762]
**Operating System:** Win10 1803
**Browser:** Chrome (72.0.3626.119), Firefox (60.5.1 esr)

After updating Bootstrap from _2.0.0.rc11_ to _2.0.0rc13_ b-table does not render items having a . as their key value. 

A items array looking like below works fine in _rc11_ in versions above only the cell "UserCompany" is rendered.
`items: [
        {
          "User.Name": "Test",
          "User.Active": true,
          UserCompany: "TestComp"
        }]`

See  working example in _2.0.0rc11_: [https://codesandbox.io/s/21l8l89jpj?fontsize=14](https://codesandbox.io/s/21l8l89jpj?fontsize=14)
For _2.0.0rc13_: [https://codesandbox.io/s/4zonnrp2k0](https://codesandbox.io/s/4zonnrp2k0)

In version _2.0.0rc13_ i do not get any errors or warnings in the browser console or any hint that something is broken.

Is this behaviour intended? I couldn't find any info about this in the docs.

Edit: fixed links

**Comment by tmorehouse** [comment]
B-Table allows users to select nested object values via keys:

```js
        fields: [
          { key: 'name.last', label: 'Last Name', sortable: true },
          { key: 'name.first', label: 'First Name' },
          { key: 'age', label: 'Age', sortable: true },
          { key: 'isActive', label: 'Active' }
        ],
        items: [
          { isActive: true, age: 40, name: { first: 'Dickerson', last: 'Macdonald' } },
          { isActive: false, age: 21, name: { first: 'Larsen', last: 'Shaw' } },
          { isActive: false, age: 89, name: { first: 'Geneva', last: 'Wilson' } },
          { isActive: true, age: 38, name: { first: 'Jami', last: 'Carney' } }
        ]
```

What you are seeing is b-table trying to find a value for `User.Name` as `User["name"]` (supports keys in dotted (`foo.bar.baz`) and array formats (`foo.bar.['bar' ]`)

One should avoid using `.` and `[..]` notation in their field keys.

**Comment by tmorehouse** [comment]
PR #2764 adds in a check to see if the key exists as is (with dots), and returns that value if found, otherwise it will split on the dots and then search within the item row object for the value based on the path.

**Comment by TheoBP** [comment]
This change introduced a bug, where the table fails to render when the parent object is null. Example here: https://codesandbox.io/s/qvmqw941ow

I'll raise a separate issue for the above, but just wanted to voice my opinion here on the subject.

I don't understand why anyone would use dots in property names. And if someone chooses to do this (for some crazy reason that I will never understand), why should this open/clean/modern library support such a non-standard/backwards way of coding? It's 2019, people use classes, you can't have dots in property names.

P.S.: sorry for the rant, just annoyed that this unnecessary change broke my code.
