### ISSUE TITLE
BFormFieldset - TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by AndrewBarba** [bootstrap-vue/bootstrap-vue#277]
After upgrading 0.12.x to 0.13.x and now 0.14.x I am seeing this error on all of my `<b-form-fieldset>` components

<img width="664" alt="screen shot 2017-04-24 at 8 55 04 am" src="https://cloud.githubusercontent.com/assets/1316152/25337988/bc5134e0-28cb-11e7-9c80-541815f325a0.png">

**Comment by AndrewBarba** [comment]
Okay I found the issue, I was using a `b-dropdown` inside the field set which doesn't have an input component. I guess this is incorrect usage

<img width="269" alt="screen shot 2017-04-24 at 10 28 31 am" src="https://cloud.githubusercontent.com/assets/1316152/25342096/e88ccdbe-28d8-11e7-9fcf-03c6c6b490a9.png">

**Comment by tmorehouse** [comment]
The fieldset looks for the first input/select/textarea to grab an ID for associated the `label`.

This PR #279 checks for the existence of the inputs before checking the ID.

**Comment by tmorehouse** [comment]
Also, If you know that your dropdown has an ID (if you assign one), then you can change the prop `inputSelector` on the fieldset to create a CSS selector that matches your dropdown (i.e. `'div.dropdown'`, or `'div#myid'`) to associate the label to your form control.

**Comment by AndrewBarba** [comment]
Ah makes sense, thanks!
