### ISSUE TITLE
active-class on nav-item not working

### ISSUE THREAD

**Issue by fr33ek** [bootstrap-vue/bootstrap-vue#2774]
Hello.

We have updated to latest `BootstrapVue` version (`rc13`) and noticed, that `active-class` for `b-nav-item` stopped working.
This is also reproducible on documentation pages and [https://jsfiddle.net/n4ekygf8/](jsfiddle).
I checked with `Firefox`(`65.0.2`) and `Chrome`(`72.0.3626.119`).
I am not a `Vue` or `bootstrap` expert, but before it worked as expected :)

Best,
Zakhar

**Comment by tmorehouse** [comment]
The behaviour has changed as it was overriding the global settings of vue-router (or nuxt-router).

You need to either set the active-class you want on the component, or change the default active class in the router config. There should be an example in the router link reference section of the BootstrapVue docs.

**Comment by tmorehouse** [comment]
Also note, the `active-class` is only applied if you are using `vue-router` and there is a `to` prop on the component (the docs are running under Nuxt, which uses vue-router under the hood).

See updated fiddle: https://jsfiddle.net/ozu2ny58/

**Comment by fr33ek** [comment]
Hello @tmorehouse ,

Okay, I see, thank you! Are there any notes about this in the changelog?
Did I understand correct, that if I am not using vue-router (for now), I need to style element manually like `.nav-item.is-active` and etc.?

Sorry, I was sure it's a bug, and I just want to clarify it to the end :)

**Comment by tmorehouse** [comment]
`nav-link` has a prop `active`, which when truthy, will add the BootstrapV4 class `active` to the rendered `a.nav-link`.

**Comment by fr33ek** [comment]
@tmorehouse yes, but ass you see there is no visible difference between active and non-active `nav-item`. So I need to add some background color and change font color. Previously, I was just doing it using `active-class="bg-primary"` f.e. but now, as we are not using vue-router, this is not working.

I will style it manually for now and migrate to vue-router later then.

**Comment by tmorehouse** [comment]
`active` class is really only applicable to style of `pills` or `tabs`, otherwise the nav-items render as basically plain links (even though the class `active` is applied to them).

**Comment by tmorehouse** [comment]
The reason it was working before was that you were taking advantage of a bug in `<b-nav-item>` in how the vue-router `active-class` prop was being used/applied.
