### ISSUE TITLE
Example of BFormCheckboxGroup document are not correct

### ISSUE THREAD

**Issue by malayvuong** [bootstrap-vue/bootstrap-vue#2778]
There's an issue on Documents, I don't know where to push so i'm push here, please forgive me if I push it at wrong place.

There's an example at the end of this url: https://bootstrap-vue.js.org/docs/components/form-checkbox

`import BFormCheckboxGroup from 'bootstrap-vue/es/components/form-checkbox-group/form-checkbox-group'`

This is correct import:
`import BFormCheckboxGroup from 'bootstrap-vue/es/components/form-checkbox/form-checkbox-group'`

**Comment by tmorehouse** [comment]
This will be fixed in the next release (it has been corrected in the dev branch docs)

**Comment by tmorehouse** [comment]
Closing as this will be coming soon in 2.0.0-rc.14
