### ISSUE TITLE
Button-close fires two click events

### ISSUE THREAD

**Issue by RipkensLar** [bootstrap-vue/bootstrap-vue#2779]
Hi.

I am using BootstrapVue version 2.0.0-rc.13.

When I use a button with a click event and include a button-close component which also has a click event, both click events get fired when I close the button. This behavior did not occur in version 1.4.1.

Expected behavior: When I close a button, only 'second' should be logged to the console, not 'second' and 'first'.

See fiddle below:
https://jsfiddle.net/9btjmz1o/

**Comment by tmorehouse** [comment]
What you are doing, placing a `<button>` inside of a `<button>`, which is not supported HTML5 markup (both `<b-button>` and `<b-button-close>` render button elements as their root element).

If you are just looking to get an <code>&times;</code> icon inside a button, use the `&times;` HTML entity (possibly wrapped inside a span so you can add a text variant such as `text-dark` and maybe sizing).

**Comment by tmorehouse** [comment]
If you want to have a button that does indeed have two click areas, then separate the two buttons inside a wrapper element:

```html
<span class="btn btn-primary">
  <b-button variant="link" class="text-decoration-none">Primary</b-button>
  <b-button-close />
</span>
```

**Comment by tmorehouse** [comment]
Your best bet:

```html
<div>
  <b-btn-group>
    <b-button variant="primary">Primary</b-button>
    <b-button variant="primary">&times;</b-button>
  </b-btn-group>
  <!-- or -->
  <b-button variant="primary">Primary &times;</b-button>
</div>
```

**Comment by RipkensLar** [comment]
Ah ok, so my previous version was kinda hacked.
Could you please provide an use-case example for the <b-button-close> component, cause I can't really figure out what it should be used for?

**Comment by tmorehouse** [comment]
It is used in the modal (top right close button), and in dismissable alerts (close button).

It just provides a transparent background, borderless button with an X (although you can specify alternative text in it's default slot).  It has the Bootstrap "close" class.
