### ISSUE TITLE
Table row select-mode for multi + range

### ISSUE THREAD

**Issue by thejcannon** [bootstrap-vue/bootstrap-vue#2782]
Howdy folks, love the library ❤️.

Small feature request: It'd be nice to either add shift support (like `range`) to the `multi` `select-mode` for tables, or introduce a new mode that combines the two.

Otherwise if I want to highlight a bunch in a row plus some others I have to click one-by-one.

**Comment by lianee** [comment]
The 3 select modes were inspired by this: https://www.datatables.net/extensions/select/
This is not to say that these are the best models we could implement, but at least they have the advantage of having been used for a long time, without major disadvantages.
Are you sure that the "range" mode is not suitable for you?
I mean, if you're ready to use the keyboard to "range select", there is not much penalty in using it for also "single select"

**Comment by thejcannon** [comment]
Actually looks like `range` works with Ctrl clicking. Don't know how I missed that one.
I still like idea of having a multi + range mode, since I would have to hold down Ctrl for singles in the range case. However, I don't feel strongly enough about it knowing range mode still allows other selections.

(Not sure if the linked library supports this, but your favorite spreadsheet editor likely does) I noticed that in range mode trying to Ctrl-Shift click an additional selection doesn't work. Happy to file a bug about it to track it separately.

**Comment by thejcannon** [comment]
And I just realized I was in multi mode.

Never mind, everything is seemingly excellent 👍

**Comment by lianee** [comment]
"single" mode is pretty much selft explanatory, "multi" can be explained/undestood simply, and "range", while a little more complex, mimicks the way most operating systems finder/explorer work, so it should be quite intuitive for users.

There is no linked library.

As for Ctrl-Shift click (starting to be for power users), it is not taken care of actually (the shift wins over the Ctrl), what would you think it should do about row selection?

**Comment by lianee** [comment]
We cross-posted the last replies.

Feel free to post any improvement you think about, there is always room for improvement

**Comment by thejcannon** [comment]
OK, after playing around with the tables for some more time, I think it might still make sense to have `single`/`multi` be orthogonal to `range`. `range` support pertains to "keyboard + mouse" support where `single`/`multi` pertains to just the "mouse" support. I think use-cases exist for each of the 4 possible combinations between mouse-style and keyboard-style.

Not sure how you'd split out those concepts into their own props though without compatibility headaches, so you'd probably stick to the one prop. If that's the case, I'd suggest then adding "single-range" and "multi-range" (or something similarly named) (where `range` is an alias for `single-range`).

**Comment by tmorehouse** [comment]
Single and multi work with keyboard only as well. As does range mode (tab onto a row, cursor up and down, and use enter to select a row or rows)

**Comment by thejcannon** [comment]
Oops, should've been more specific about what I meant by "keyboard" and "mouse".

Here's how I see it:
`single`/`multi` pertains to how to handle a selection without <kbd>Ctrl</kbd>/<kbd>Shift</kbd>
`range` pertains to how to handle a selection with with <kbd>Ctrl</kbd>/<kbd>Shift</kbd>

You could think of it as two props (long names for exposition):
`single-selection-mode`: `exclusive` or `additive`
`support-shift-and-ctrl-clicking`: `true` or `false`

Where `select-mode` implies the props (respectively):
  - `single`: `exclusive` and `false`
  - `multi`: `additive` and `false`
  - `range`: `exclusive` and `true`
  - ???: `additive` and `true`

Whether support is added via 2 props or a fourth `select-mode` doesn't matter to me.

**Comment by thejcannon** [comment]
Since I've started using a fork, I went ahead and changed "range" mode to just do what I want.
See commits f5f7f5b8aed26224aca1a4bfb2539bddc315c3d2 and 9669b1a3240a227a02f7c03f2a93af496f9091a1(lines 160 & 161)

Note: Missing unit tests though 😢
