### ISSUE TITLE
Tabs nested in elements are no longer detected

### ISSUE THREAD

**Issue by rrelmy** [bootstrap-vue/bootstrap-vue#2784]
With the release of r12 `b-tab` that are not directly inside the `b-tabs` are not detected anymore.

Should it be possible to nest tabs like that or is this a invalid usage?

``` vue
    <b-tabs :lazy="true">
      <b-container>
        <b-row>
          <b-col cols="3">
            Some static sidebar
          </b-col>
          <b-col cols="9">
            <b-tab title="hello">
              <p>Tab content</p>
            </b-tab>
          </b-col>
        </b-row>
      </b-container>
    </b-tabs>
```

I suspect that this change is causing this change
https://github.com/bootstrap-vue/bootstrap-vue/pull/2442/files#diff-1c9a815164bf8abc0ef6d326c5b3d2fbR248

**Comment by tmorehouse** [comment]
`<b-tab>` *must* be a direct descendant of the `<b-tabs>` component in order for it to detect the `<b-tab>` so it can generate the tab nav buttons.

You would need to place your static sidebar inside each `<b-tab>`), or place it outside of your `<b-tabs>`.
