### ISSUE TITLE
Form Radio Group error

### ISSUE THREAD

**Issue by chrisleyva** [bootstrap-vue/bootstrap-vue#2790]
Hello,

In my Nuxt 2.4.5 app, I am using the latest bootstrap and bootstrap-vue packages. All seems to be working well, except when I use the `<b-form-radio-group />` component. 

It was working well in **rc.11**. I reverted back to the previous bootstrap and bootstrap-vue packages but I still get the error. So I'm thinking it's an issue with the latest nuxt version.

But has anyone come across the same issue?
In my terminal, I get the following error:

```
 ERROR  [Vue warn]: Error in render: "ReferenceError: File is not defined"                                 

found in

---> <BFormRadio>
       <BFormRadioGroup>
         <BFormGroup>
           <BModal>
             <Pages/admin.vue> at pages/admin.vue
               <Nuxt>
                 <Layouts/default.vue> at layouts/default.vue
                   <Root>
```
Thank you for considering.

**Comment by tmorehouse** [comment]
This is fixed in the latest `dev` branch (PR #2651) and will be available in v2.0.0-rc.14 (which will hopefully be released by tomorrow)

Duplicated/Related: #2682
