### ISSUE TITLE
Modular

### ISSUE THREAD

**Issue by callumacrae** [bootstrap-vue/bootstrap-vue#28]
Hey! Would be nice if it were possible to only load one component at a time: I don't want all of them loaded.

**Comment by nddery** [comment]
Since version `v0.3.9` you can. The documentation hasn't yet been updated but it goes as follow:

```js
import { bModal } from 'bootstrap-vue'

export default {
  components: {
    bModal
  }
}
```

**Comment by callumacrae** [comment]
That only works if you have a bundler that supports tree shaking, though—which currently, is only rollup. Is it possible to do something like this?

```
import bModal from 'bootstrap-vue/bModal`;
```

Otherwise you lose half the benefit of a modular library.

**Comment by nddery** [comment]
If you have `vue-loader` all setup you can import individual components like:

```js
import bButton from 'bootstrap-vue/components/button'
```

**Comment by callumacrae** [comment]
awesome :)
