### ISSUE TITLE
<b-tabs> maintain tab state on page refresh

### ISSUE THREAD

**Issue by justindasilva** [bootstrap-vue/bootstrap-vue#2803]
Feature Request:

A directive to add onto `<b-tabs>` to maintain the current active tab on a page refresh.

Perhaps something like `maintain`.

**Comment by tmorehouse** [comment]
This would need to be handled by your apps persistent datastore (i.e. `vuex` or `localStorage`), as when the page is reloaded or navigated away from and back, the component gets re-rendered from scratch.

You can use the `v-model` to set which tab is active (and find out which tab is active.

You would need to tie the `v-model` to a key in your persistant storage.

**Comment by justindasilva** [comment]
I got everything working properly now, however, there seems to be an issue on the very first time the tabs are loaded (a page refresh).

I've tied my tabs using `v-model`.

If I set `this.tabIndex` to 1 in the `data()` method, the tabs will not be on the second tab on page refresh. If I then go to another page on my app and then come back, it will be on the second tab. There may be a bug in how the bootstrap vue tabs handle setting the active tab on page load. I feel like a `setTimeout` in the `created` function might do the trick.
Can this be looked into?

**Comment by tmorehouse** [comment]
`$nextTick()` would be better than `setTimeout`

In your component `mounted()` (or `created()`) hook, you could set your `this.tabIndex` to the value you want (use `$nextTick()` in the created hook)

**Comment by justindasilva** [comment]
So I've tried both the `mounted()` and `created()` hook.

```
created() {
      this.tabIndex = 1;
}
```

```
<b-tabs v-model="tabIndex" pills card vertical>
///
</b-tabs>
```

It won't work on page refresh. But if I go to another page and back, it works.

**Comment by tmorehouse** [comment]
Try:

```js
created() {
  this.$nextTick(() => {
    this.tabIndex = 1
  })
}
```

**Comment by justindasilva** [comment]
I've tried the above but doesn't work either unfortunately.

**Comment by justindasilva** [comment]
If I do the following, it works:
```
setTimeout(() => {
        this.tabIndex = 2;
      }, 100)
```

And I've tested with different time values including `1`, `10`, `50`. Seemed I had to go near `100` for it to work properly.

**Comment by qbunia** [comment]
> 
> 
> Try:
> 
> ```js
> created() {
>   this.$nextTick(() => {
>     this.tabIndex = 1
>   })
> }
> ```

@tmorehouse This looks like a hack. Will it be fixed to be working without using $nextTick?

**Comment by tmorehouse** [comment]
`nextTick` is not really a hack.  I has to do with transition timing, etc.  Also b-tab chidren are discovered in `created()` hook in a nextTick to allow the children to be rendered first before we can see what child b-tabs are there, and we use a nextTick as well after any "update" to allow time for children to finish rendering before updating them with their current state.

**Comment by qbunia** [comment]
Could you add this to docs so future developers wont have to look for it on issues?
