### ISSUE TITLE
b-form-group label escaping html

### ISSUE THREAD

**Issue by MaxPowerDarrel** [bootstrap-vue/bootstrap-vue#2811]
I recently updated from rc-11 to rc-14

```html
<b-form-group
  horizontal
  label-cols="3"
  label-for="username"
  label="&nbsp&nbspUsername"
  id="loginUserGroup"
  style="font-weight: bold; font-size: 16px;"
>
 <b-form-input
    class="mb-2 mr-sm-2 mb-sm-0 rounded-0"
    id="username"
    v-model="username"
    type="text"></b-form-input>
</b-form-group>
````

Would work, but now the label displays the label exactly as shown above, including the text &nbsp.

**Comment by tmorehouse** [comment]
This was introduced by security fixes over concerns of possible `XSS` attacks from user supplied content.

For `b-form-group`, use the `label` slot for HTML:

```
<b-form-group
  horizontal
  label-cols="3"
  label-for="username"
  id="loginUserGroup"
  style="font-weight: bold; font-size: 16px;"
>
 <template slot="label">&nbsp&nbspUsername</template>
 <b-form-input
    class="mb-2 mr-sm-2 mb-sm-0 rounded-0"
    id="username"
    v-model="username"
    type="text"></b-form-input>
</b-form-group>
````

**Comment by merigold** [comment]
I create parent Element:

`@Component({})
export default class FgComponent extends VueApp {

    render(createElement): VNode {
        let attributes = {
                
                props:{...this.$props}
                attrs:{...this.$attrs},


        };
        let slotLabel= createElement('span', { slot: 'label',domProps:{innerHTML:this.$attrs['label']}});
        let slots = this.$slots.default;
        slots.push(<any>slotLabel);
        return createElement('b-form-group', attributes, slots);
    }
}
`
