### ISSUE TITLE
table "currentPage" should allow Number/String

### ISSUE THREAD

**Issue by thejcannon** [bootstrap-vue/bootstrap-vue#2821]
`b-table` mimics some `b-pagination` props, (like `perPage` and `currentPage`) however doesn't mimic the types of these params (`b-pagination` allows `Number` or `String` and sanitizes the input, whereas `b-table` only allows number).

This means I can't use the current route's query parameters as-is: `:current-page="$route.query.page"` as I'll get "Invalid prop: type check failed ...". ([Interestingly enough, `b-table` calls `parseInt` on the value](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/table/table.js#L314), so the logic still works. Just the type check fails 😄)

**Comment by tmorehouse** [comment]
@thejcannon we should be able to have this fixed for the next release.

**Comment by thejcannon** [comment]
Sweet. Also worth mentioning for anyone else reading the workaround is trivial, but unsightly: `:current-page="Number.parseInt($route.query.page)"`
