### ISSUE TITLE
Popovers visible when component is removed are not hidden

### ISSUE THREAD

**Issue by paglias** [bootstrap-vue/bootstrap-vue#283]
I have some code like this inside a custom component

```
b-popover(
  :triggers="['hover']",
  v-if="condition",
)
```

If the popover is displayed and while it's being displayed the condition is the `v-if` becomes `false` the popover is not removed immediately but stays in place until the page is scrolled.

**Comment by SirLamer** [comment]
Thanks, I will work on it. In the meantime please use "v-show", it will behave as you are expecting.

**Comment by pi0** [comment]
Popovers migration plan in active in #287 . Please follow there :)
