### ISSUE TITLE
Rows parameter for textarea component switches between actual value and default (Vue loader)

### ISSUE THREAD

**Issue by wvh** [bootstrap-vue/bootstrap-vue#2830]
Hello,
The `rows` attribute on `b-form-textarea` doesn't always take effect when developing with hot reload enabled. Sometimes the textarea has 8 rows, sometimes it falls back to 2 – which I believe is the default.
I've tried with both a v-bind colon and without.

```javascript
<b-form-textarea id="publish-modal-error-json" class="p-0 text-monospace small" plaintext readonly :value="JSON.stringify(error.more, null, 2)" placeholder="no error" :rows="8" :max-rows="16"></b-form-textarea>
```
I think this might be an issue with the number argument to `rows`.

I'm running bootstrap-vue v2.0.0-rc.14 in a vue-cli dev server with the latest Vue release on the latest Chromium version.

**Comment by tmorehouse** [comment]
Hot reload will do this...  as the component gets torn-down, and then re-instantiated.

The routine that adjusts the height runs as a person types in characters.

We might have to add in an initial run of the routine on mount, to make sure the height is adjusted based on the current content of the text area.

**Comment by wvh** [comment]
Yes, it's likely the hot reload is not triggering the height adjustment, and since it's a {{readonly}} textarea, it's just tricky to update the contents of the component on the fly.

Not sure this is worth fixing, though it's good to know that {{mount}} and hot reload don't always play nice.

**Comment by tmorehouse** [comment]
We use a $nextTick() on mount to trigger the resizing, but maybe adding in a `requestAnimationFrame(..)` inside the `$nextTick` might help, as it gives the browser a chance to finish rendering.

**Comment by wvh** [comment]
It would also be nice if there were a way to actually set the `rows` attribute on the HTML element because it doesn't seem like anything is inserted, even if `no-resize` is set.

**Comment by tmorehouse** [comment]
@wvh just setting the `rows` props, and don't specify a `max-rows`.  the rendered `textarea` will then have the `rows` attribute on it.
