### ISSUE TITLE
filter-function on b-table not working in rc14

### ISSUE THREAD

**Issue by Ansim73** [bootstrap-vue/bootstrap-vue#2833]
i currently updated to bootstrap rc14 and it seems, that the filter-function is not working. When using the filter-property the table is filtered, but given a function both properties, filter and filter-function, are not working. the function is not called. On rc11 we used a function for filtering and it worked properly.

js-fiddle: https://jsfiddle.net/41rg3pnh/2/

Did i make a mistake or is this a bug?

**Comment by tmorehouse** [comment]
When using a filter function, the criteria passed to the filter function must be placed on the filter prop in order to trigger reactivity.

**Comment by tmorehouse** [comment]
@Ansim73, did this fix your issue?

**Comment by Ansim73** [comment]
ja, thank you. but is there a undocumented breaking change in this functionality? 
Using the filter-property and commit a function should work like in rc11. 
Maybe i missed the part in the changelog.
