### ISSUE TITLE
Dropdowns not closed

### ISSUE THREAD

**Issue by milenon** [bootstrap-vue/bootstrap-vue#284]
Dropdowns are not closed if dropdown item with 'to' properties are used:

```
                <b-dropdown text="Dropdown Button" variant="success" class="m-md-2">
                    <b-dropdown-item to="#">Not closed after click</b-dropdown-item>
                    <b-dropdown-item to="/real/uri">Not closed after click</b-dropdown-item>
                    <b-dropdown-item href="/some/link">Closed after click</b-dropdown-item>
                </b-dropdown>
```

**Comment by tmorehouse** [comment]
Are you using the vue-router with this?

**Comment by milenon** [comment]
Yes

**Comment by tmorehouse** [comment]
I've created a fiddle https://jsfiddle.net/tmorehouse/obagdgLg/1/ that can be played with, which reproduces the issue.

**Comment by tmorehouse** [comment]
So it appears for router-links (specified by the `to` prop), the click event is not propagating up to the `router-link`.  The resultant HTML looks fine though

```html
<div class="m-md-2 dropdown btn-group">
  <button class="btn btn-success dropdown-toggle" aria-haspopup="true">Dropdown Button</button>  
  <!---->
  <div tabindex="-1" class="dropdown-menu">
    <a href="#" class="dropdown-item" tabindex="0">to #</a>
    <a href="#" tabindex="0" class="dropdown-item">href #</a>
    <a href="/foo" class="dropdown-item" tabindex="0">to /foo</a>
    <a href="/bar" class="dropdown-item" tabindex="0">to /bar</a>
    <a href="/foo" tabindex="0" class="dropdown-item">href /foo</a>
    <a href="/bar" tabindex="0" class="dropdown-item">href /bar</a>
    <a href="/real/uri" class="dropdown-item" tabindex="0">Not closed after click</a>
    <a href="/some/link" tabindex="0" class="dropdown-item">/some/link</a>
  </div>
</div>
```

**Comment by tmorehouse** [comment]
looking in the latest `b-link` code, I think this might be fixed:

```js
        methods: {
            click(e) {
                if (this.disabled || this.href === '#') {
                    e.preventDefault();
                    e.stopPropagation();
                }
                if (!this.disabled) {
                    this.$emit('click', e);
                    this.$root.$emit('shown::dropdown', this);
                }
            }
        }
```

**Comment by tmorehouse** [comment]
Hmmm looking at this a little deeper, it appears he above b-link code doesn't fix this.

I mocked up a new fiddle with the latest `dropdown-item` code and `b-link` code, and added in a few console.log calls in the click events, and it appears that `router-link` is not propagating the click event up the component tree.

https://jsfiddle.net/tmorehouse/4gx1jsjk/1/

**Comment by tmorehouse** [comment]
And some more interesting information after some playing around.

`<router-link>` does not respect the `disabled` prop on the `<b-dropdown-item>`, and "routes away".  Might need to add in a check for this and change the `componentType` if disabled.

I also tried this when building the router:

```js
const routes = [{
  path: '/foo',
  component: Foo
}, {
  path: '/bar',
  component: Bar
}];

const router = new VueRouter({
  routes
});

router.afterEach((to, from) => {
  console.log('Signal Vue root to close dropdown');
  // false will cause any open dropdown to close
  router.app.$emit('shown::dropdown', false);
})

const app = new Vue({...});
```
And when clicking a `dropdown-item` with a `to` prop, the dropdown closes as expected, except it also closes when the `dropdown-item` is disabled, but the route is still executed :(

See fiddle https://jsfiddle.net/tmorehouse/4gx1jsjk/2/ and open the console up.

In reviewing the view-router `<router-link>` code, I see that they do call `e.PreventDefault()` on click, but I do not see them calling `e.stopPropagation()` https://github.com/vuejs/vue-router/blob/dev/src/components/link.js#L120

**Comment by tmorehouse** [comment]
Also tried using a watcher in `b-dropdown-item` code, instead of the `router.afterEach(...)`
```js
  watch: {
    $route(a,b) {
      this.$root.$emit('shown::dropdown', false);
    }
  }
```
And this will close the dropdown on click, except when the route stays the same.

This method might be the simple interim fix for now (not ideal, but close).

**Comment by tmorehouse** [comment]
related: https://github.com/vuejs/vue-router/issues/916

**Comment by tmorehouse** [comment]
After a bit more investigation, I may have found a better solution rather than watching `$route` for changes

The `@click.native="..."` will intercept the click on `<router-link>`, but will not for regular `a` or `button` tags.

Adding both `@click="..."` and `@click.native="..."` at the same time in the `b-dropdown-item` _does_ appear to work.

https://jsfiddle.net/tmorehouse/fv6btm53/

Disabled `to` items still change the route though.  `disabled` `href` do respect the disabled state.

**Comment by tmorehouse** [comment]
#290 fixes the dropdown not closing on click of `<router-link>`, But doesn't address `disabled` router-links.

To get around `disabled` not working, you can switch from `to="/bar"` to `href="#/bar"` and disabled route dropdown-items will be truly disabled as expected (when using `hash` mode in vue-router)
