### ISSUE TITLE
Set class to input tag for b-form-checkbox, b-form-radio and b-form-file.

### ISSUE THREAD

**Issue by phlegx** [bootstrap-vue/bootstrap-vue#2849]
At this moment (latest version), there is no possibility to set a class to the input tag for `b-form-checkbox`, `b-form-radio` and `b-form-file`.

This could be very useful! Can you please add a property e.g. `input-class` where it is possible to set a class to the input tag?

**Comment by tmorehouse** [comment]
For checkboxes, radios, and file input (in the custom style mode, which his default), the input is hidden from view as the label is used to display the custom styled inputs.

What is your use case?

**Comment by phlegx** [comment]
Different use cases... one is to add `is-required` status class. Another idea is to add an asterisk for required like for state valid and invalid.

**Comment by tmorehouse** [comment]
Although this wouldn't work well with the custom styled inputs for the above reason.

Any class you apply to the above components will be placed on the component's root element.  You can then use that class to target the sub elements (such as the input or labels, i.e. `.my-class > input` or `.my-class > label`) to add additional styles to those elements.

If you are defining a custom class, then you can augment that class to target the inner elements.

**Comment by phlegx** [comment]
Ok, I give it a try! Thx!

**Comment by phlegx** [comment]
But why `b-form-file` adds `is-valid` or `is-invalid` to the root and to the input tag element and `b-form-checkbox` and `b-form-radio` not?  `b-form-checkbox` and `b-form-radio` should also add state class to the root element for better handling and to do what you describe in the reply above.

**Comment by tmorehouse** [comment]
That is due to an issue with how the form-file validation works.

**Comment by tmorehouse** [comment]
If you would like to have the validation classes added to the outer wrappers for those components, please open a new issue with a new title.
