### ISSUE TITLE
Discusson: Replace Tether with Popper.js?

### ISSUE THREAD

**Issue by SirLamer** [bootstrap-vue/bootstrap-vue#287]
Tether is the JS package used to manage the Popover element placement. It is also used in Tooltip by extension. Probably some other components on here use Tether as well.

The Tether developers indicated on their GitHub page that the package will no longer be supported, despite some lingering bugs and a long list of GitHub issues and PRs.

I am thinking about looking at switching to Popper.js. I have no experience with it, except the Tether page recommends it.
https://popper.js.org/

This would probably help with correcting some of the bugs we are dealing with, and it could create new bugs. It might not interact with Bootstrap's CSS properly, which is the main reason why we're still using Tether here, but I am guessing that Bootstrap 4 will have to make the same change for the same reasons as us.

Any thoughts for or against are welcome, otherwise I'll get to experimenting with it.

**Comment by SirLamer** [comment]
Looks like Bootstrap project is doing the same.
https://github.com/twbs/bootstrap/pull/22444

**Comment by tmorehouse** [comment]
It does have some nice features for sure:

https://github.com/FezVrasta/popper.js#popperjs-1
- Position elements keeping them in their original DOM context (doesn't mess with your DOM!);
- Allows to export the computed informations to integrate with React and other view libraries;
- Supports Shadow DOM elements;
- Completely customizable thanks to the modifiers based structure;

The first and 3rd bullets above are ones that make it look attractive.

**Comment by tmorehouse** [comment]
BS4 is also considering using it to position their drop-down menus as well, based on some of the discussion.

I like the fact that you can leave the DOM where you generated it, and just rely on the dynamic CSS props for positioning.

There are a few features in Popper.js that don't work with IE10, but if you avoid them, then it would be good.

**Comment by tmorehouse** [comment]
Some existing Vue components:
- https://github.com/antongorodezkiy/vue-popper-component
- https://www.npmjs.com/package/vue-directive-tooltip

**Comment by pi0** [comment]
Also consider this: https://github.com/znck/bootstrap-for-vue/blob/master/src/directives/tooltip.js

The positive point with popper.js it that is just a computation engine. Other libraries are doing dirty DOM manipulation which makes problems with Vue. Anyway i'm still thinking of a pure inline solution to make bootstrap-vue independent of external libraries.

**Comment by pi0** [comment]
Also consider this: https://github.com/znck/bootstrap-for-vue/blob/master/src/directives/tooltip.js

The positive point with popper.js it that is just a computation engine. Other libraries are doing dirty DOM manipulation which makes problems with Vue. Anyway i'm still thinking of a pure inline solution to make bootstrap-vue independent of external libraries.

**Comment by FezVrasta** [comment]
Hey guys, if you are going to use Popper.js you may want to publish the wrapper as a standalone component, the current ones aren't well supported AFAIK. The Vue community would benefit a lot from such kind of component.

If you have concerns or questions about my library just ask them here and I'll be happy to reply!

**Comment by tmorehouse** [comment]
I kind of like the idea of being able to use tooltip both via a directive and component

**Comment by SirLamer** [comment]
Doing a popover as a directive isn't especially simple, it's kinda the opposite of how Vue is meantt o work because I think we'd require a json object as bulk input, or something like that.

There is a draft CSS addition which would make an element basically be ignored in the CSS inheritance tree, it would fix a lot of the issues with using elements as wrappers in Vue, but it will be years before it is safe to use in production.
https://www.w3.org/TR/css-display-3/#valdef-display-outside-contents

I think that I'll wait for Bootstrap to release with Popper replacing Tether, at which point I'll affect the conversion. The reason is because they seem to be making CSS class name changes at the same time.

**Comment by tmorehouse** [comment]
What about a directive similar to `v-b-modal` that can be used to trigger a tooltip/popover component that is located elsewhere in the app body?

**Comment by FezVrasta** [comment]
@tmorehouse do note that Popper.js doesn't have the limitations of Tether, in the sense that you don't need the tooltip/popover (=== popper) to be as direct child of `body`.

It will work fine if the parent doesn't have any `overflow: hidden` as parent

**Comment by SirLamer** [comment]
The problem with directives is that the interface for inputting properties is much more crude. It is contrary to the design philosophy of Vue. On the other hand, a directive is more accommodating of CSS inheritance. My personal opinion is that this a problem that the CSS standard needs to solve, and it appears to intend to.

**Comment by tmorehouse** [comment]
https://github.com/LinusBorg/portal-vue looks interesting for rendering in a different DOM location, but does require additional markup in your document to place the content in another location (either within the app or outside the app), which makes the usage a bit more difficult.

**Comment by FezVrasta** [comment]
Emh, sorry but I think I wasn't clear enough. With Popper you don't need portals *most of the times* 🙃

**Comment by tmorehouse** [comment]
I wasn't referring to using popper with portal-vue, but in general as a way to move render DOM in a different location. ;-)

**Comment by tmorehouse** [comment]
I have been using jQuery qtip plugin in previous projects.  It has some nice features, such as a lot of ARIA stuff (adding `aria-describedby` to the trigger element; `role="alert" and `aria-live="assertive` to the tooltip; etc).

Although it has the same issue of leaving the tooltips buried in the DOM when no longer needed (and requires on jQuery of course)

**Comment by SirLamer** [comment]
Because I want to support the Bootstrap CSS classes, I really want to copy whatever Bootstrap does. Once rendered it should behave the same as native Bootstrap with jQuery.

**Comment by tmorehouse** [comment]
Definitely.  But just pointing out some of the features of qtip (regarding ARIA mainly) that would be nice to incorporate.  Positioning, style, layout, etc would definitely have to follow BS4.

**Comment by SirLamer** [comment]
Yeah, the issue is that they have made CSS changes and if I try to support the Popper changes now, anyone who uses this package with the current Bootstrap release would have issues. Also, I don't want to make changes again and again so I am content to sit tight and wait for their beta release. The current Tether implementation here works at least as well as in native Bootstrap, the only problem is here people are pushing it way harder and so are exposing reactivity-related issues.

**Comment by tmorehouse** [comment]
For sure!

**Comment by romamilkovic** [comment]
Looks like Bootstrap already use Popper plugin (https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js) . Do you guys plan to update your component too?

**Comment by tmorehouse** [comment]
We have a resource working on migrating tether to popper.

Bootstrap is still in the midst of working with popper.js, and is planned to be released in Bootstrap V4.beta.1

**Comment by SirLamer** [comment]
The switch to Popper includes some CSS changes, so it would be super awkward to release here early with Popper while the latest Bootstrap CSS release expects Tether.

**Comment by tmorehouse** [comment]
Just thinking aloud about tooltips and popovers.  Currently one has to "wrap" an element or component with a tooltip, which works in most cases, but for some things that can break styling (i.e button groups, etc).

Would it be possible to add a `target-id` prop to tooltip/popover, which would allow one to bind it (eventwise) to a non-wrapped component or element (as long as that element has an ID)?

**Comment by asafyish** [comment]
Any updates on this ? I just checked out beta 3 and saw it's still using tether ... on a large list with we get a massive performance degradation :(

**Comment by tmorehouse** [comment]
It's coming soon to v1.0.0, still working on the changes.

**Comment by SirLamer** [comment]
Hi, I will get to work on this. Sorry for being slow, there is no warning on when the Bootstrap updates are gonna come out then BAM there ya go.

**Comment by tmorehouse** [comment]
I'll be working on the dropdown positioning bits and peices

**Comment by pi0** [comment]
@FezVrasta We have migrating using Popperjs using both directive and components :) (All thanks to @tmorehouse) Would be awesome hearing your feedback on this integration and thanks for your great library :)

**Comment by tmorehouse** [comment]
We still may have a few issues with the component version of tooltips and popovers (i.'m investigating the logic we use for the component version), but the directive versions are working well!
