### ISSUE TITLE
Can't use ~/assets/img on card image

### ISSUE THREAD

**Issue by sts-ryan-holton** [bootstrap-vue/bootstrap-vue#2873]
Hi, I'm having trouble getting the `img-src` to work with Nuxt JS, in particular if I specify `img-src="~/assets/img/myimage.png"` as per Nuxt JS's guide for including images it doesn't work for Bootstrap Vue. I have in fact noticed this on a couple of Bootstrap Vue components and have had to fallback to using original Bootstrap markup as divs, see: https://bootstrap-vue.js.org/docs/components/card#images

**Comment by tmorehouse** [comment]
There is a bit of config you need to pass to Vue-Loader in order to tell it which properties on custom components can take asset URLs.

See the docs at https://bootstrap-vue.js.org/docs/reference/images (specifically the section on `vueTransformAssetUrls`)

**Comment by sts-ryan-holton** [comment]
@tmorehouse Ah right! I did come across that page earlier but I wasn't too sure about whether it was needed, I'll add this tomorrow and see how it goes! Thanks for your help here :+1:
