### ISSUE TITLE
b-nav-item-dropdown active state

### ISSUE THREAD

**Issue by simioluwatomi** [bootstrap-vue/bootstrap-vue#2883]
In Bootstrap NavBar, an active class can be set on the `a` tag which is a direct sibling of the `li` tag in order to mark the dropdown as active (indicating that any of its sibling pages is currently in view). See image below

![image](https://user-images.githubusercontent.com/22191563/54683252-79b5de00-4b11-11e9-9102-925369b23c99.png)

Notice the `Lang` dropdown? The rendered markup is provided below

```
<li class="nav-item b-nav-dropdown dropdown">
  <a
    href="#"
    aria-haspopup="true"
    aria-expanded="false"
    class="nav-link dropdown-toggle active"
  >
    <span>Lang</span>
  </a>
  <div
    tabindex="-1"
    class="dropdown-menu dropdown-menu-right"
    aria-labelledby="__BVID__212__BV_button_"
  >
    <a role="menuitem" target="_self" href="#" class="dropdown-item">EN</a>
    <a role="menuitem" target="_self" href="#" class="dropdown-item">ES</a>
    <a role="menuitem" target="_self" href="#" class="dropdown-item">RU</a>
    <a role="menuitem" target="_self" href="#" class="dropdown-item">FA</a>
  </div>
</li>
```

How can this same behaviour be replicated using Bootstrap-Vue? Because I don't see this anywhere in the docs.

```
<b-nav-item-dropdown text="Profile" right>
  <b-dropdown-item :to="{ name: 'Timeline' }">
    Timeline
  </b-dropdown-item>
  <b-dropdown-item :to="{ name: 'Edit' }">Edit</b-dropdown-item>
</b-nav-item-dropdown>
```

**Comment by tmorehouse** [comment]
For the individual items, you can use the 'exact' router prop on the `<b-dropdown-item>` to make sure it matches the exact class (in fact you can use this on any `nav-item` as well, and in combination with the router prop `exact-active-class` or `active-class` to set which class should be placed on the items when the router matches the current `to` location.

To place a class on the dropdown toggle, you would need to check the current `$route` against a particular location (i.e. by checking the $route name, or path) and if truthy, apply the class to the menu toggle button via the prop `extra-toggle-classes`:

```html
<b-nav-item-dropdown
    text="Profile"
    right
    extra-toggle-class="$route.name === 'foobar' ? 'active' : ''>
  <b-dropdown-item :to="{ name: 'Timeline' }" active-class="active">
    Timeline
  </b-dropdown-item>
  <b-dropdown-item :to="{ name: 'Edit' }" active-class="active">
   Edit
  </b-dropdown-item>
</b-nav-item-dropdown>
```

**Comment by simioluwatomi** [comment]
Thanks for your quick response. For future reference, this was what worked for me

```
:extra-toggle-classes="$route.name === 'foobar' ? 'active' : ''"
```

This [`extra-toggle-classes="$route.name === 'foobar' ? 'active' : '"`] applied all the text as a class attribute.

But then, if more `b-dropdown-items` are added, this would become unwieldy as I would need to check for each route name. Is there a way to have an inclusive match that would apply the active class for any route under that dropdown? I set-up the routes like so `/b-nav-item-dropdown/b-dropdown-item`.

Once again, thanks for your time.

**Comment by tmorehouse** [comment]
You could compare the `$route.path` instead of the `$route.name`

**Comment by MoonCheung** [comment]
🙂 ` :extra-toggle-classes` was scrapped, now ` :toggle-class` is props instead of implementing ternary expressions

**Comment by Ajay537** [comment]
@tmorehouse 
Is there any better way to achieve this?
In my case the drop-down items paths are independent.
Example: 

- /abc
- /def
- /ghi

If this is the case the main `toggle-class` would look very weird.

**Comment by tmorehouse** [comment]
Just to make sure I am understanding your ask correctly, you are trying to add the active class to the toggle button (link in this case) when any of the child dropdown items is active?

You could use an array of route paths, and then check to see if the active route is in that array.  And then you push new paths on that array as you add new items, and use that same array to generate your dropdown items (in a v-for loop)

```js
export default {
  data() {
    return {
      items: ['/abc', '/def', '/ghi']
    }
  },
  computed: {
    toggleClass() {
      return this.items.indexOf(this.$route.path) > -1 ? 'active' : ''
      // or
      // return this.items.some(p => p === this.$route.path) ? 'active' : ''
    }
  }
}

**Comment by daniel007enirman** [comment]
How for nuxtjs?
