### ISSUE TITLE
[Feature Request] B-Carousel Option to disable pause on hover

### ISSUE THREAD

**Issue by Hiws** [bootstrap-vue/bootstrap-vue#2887]
https://getbootstrap.com/docs/4.3/components/carousel/#options

Bootstrap currently supports the option to disable/enable pausing the carousel when hovering.
Currently B-Carousel pauses it on hover by default, with no option to disable it.

Adding a prop 'pause' which could be set to 'hover' or null/false depending on what interaction you want would be great.

Another possibility could be to add an 'option' prop and allow the options from the bootstrap docs to be passed through it to make it more like native bootstrap.

**Comment by tmorehouse** [comment]
We should be able to add a prop `no-hover-pause`, which when set would disable the pause on hover.
