### ISSUE TITLE
Allow colspan=(all) items

### ISSUE THREAD

**Issue by thejcannon** [bootstrap-vue/bootstrap-vue#2889]
I know this one might be a bit controversial/difficult, but wanted to throw it out there and see what y'all thought.
I have the need to "group" things in a single table (single table so I get selectable support) and the most natural way of displaying the groupings I can think of would be to use a row where `colspan` is all the columns.

An quick-and-dirty example might be (of course, with much more beautiful styling)
<table>
  <thead>
    <th>Weapon</th>
    <th>Person</th>
  </thead>
  <tr>
    <th colspan="2">Study</th>
  </tr>
  <tr>
    <td>Rope</td>
    <td>Professor Plum</td>
  </tr>
  <tr>
    <td>Gun</td>
    <td>Colonel Mustard</td>
  </tr>
  <tr>
    <th colspan="2">Kitchen</th>
  </tr>
  <tr>
    <td>Knife</td>
    <td>Mrs. White</td>
  </tr>
</table>

Where the items coming in look like: 
```javascript
[
   {room: "Study", weapon: "Rope", person: "Professor Plum"},
   {room: "Study", weapon: "Gun", person: "Colonel Mustard"},
   {room: "Kitchen", weapon: "Knife", person: "Mrs. White"},
]
```
(although I'm more than happy to transform my items if the implementation is easier with a different representation)

My particular use case would include:
- the ability to use `tbody-tr-class` (or similar) to style said rows
- not have those rows selected in range mode ("skips" over them)

**Comment by tmorehouse** [comment]
You could try using row details support to show an extra row below a row item if the next item has a different field value (you would need to preparse you items array and set the `_showDetails` value appropriately).

The row details slot is a `TR` with a single `TD` that spans the width of the table.

**Comment by thejcannon** [comment]
Wow 😱, so the only thing missing then would be the ability to choose to put the details first.
Would you prefer a new issue?

**Comment by tmorehouse** [comment]
Not needed...

You could do the following:

```js
const items = [
  { category: 'a', foo: 1, bar: 2 },
  { category: 'a', foo: 3, bar: 4 },
  { category: 'b', foo: 5, bar: 6 },
  { category: 'b', foo: 7, bar: 8 },
  { category: 'c', foo: 9, bar: 0 }
]
```
and then loop through your items like so:

```js
items.forEach((item, index) => {
  if (items[index+1] !== undefined && item.category === items[index+1]) {
    item._showDetails = true
    item.nextCategory = items[index+1].category
  }
})
```

And then pass this modified items to `b-table`, and then use the following slots:

```html
<template slot="top-row" slot-scope="{ columns }">
  <td :colspan="columns">{{ items[0].category }}</template>
<template slot="row-details" slot-scope="{ item }">
  {{ item.nextCategory }}
</template>
```
Should get you close to what you want.

**Comment by thejcannon** [comment]
Ahh, using `top-row` is clever. I like it 👍.
Thanks for the help 😍

**Comment by tmorehouse** [comment]
`top-row`, `bottom-row` and `row-details` all do not participate in selctable rows as well (so they wont be selectable)

**Comment by tmorehouse** [comment]
Also note the `row-details` slot has the TD top border supressed. you might need to add a custom CSS style to target the TD and add the border back in (`1px solid #333`) (row details will have a class `b-table-details` on the TR.

**Comment by thejcannon** [comment]
To add for posterity, the `type` handed to the `tbody-tr-class` callable is `row-details`, so adding classes for styling should be trivial.

If adding the option for row details above the row is simple, I'd still suggest it, but if not I have a pretty good workaround here.

**Comment by thejcannon** [comment]
Fair enough, thanks again!
