### ISSUE TITLE
Table sort triggers [vuex] Do not mutate vuex store state outside mutation handlers

### ISSUE THREAD

**Issue by Mark-de-Haan** [bootstrap-vue/bootstrap-vue#289]
When sorting the a table rendered with the code below:
```
<template>
  <b-table striped hover :items="items" :fields="fields">
    <template slot="username" scope="item">
      {{item.item.username}}
    </template>
    <template slot="isActive" scope="item">
      {{item.item.active?'Yes :)':'No :('}}
    </template>
    <template slot="email" scope="item">
      {{item.item.Email}}
    </template>
  </b-table>
</template>

<script>
  export default {
    name: 'variant-table',
    props: ['items'],
    data: function () {
      return {
        fields: {
          username: {
            label: 'Username',
            sortable: true
          },
          isActive: {
            label: 'is Active'
          },
          email: {
            label: 'E-mail'
          }
        },
        filter: null
      }
    }

  }
</script>
```

My console throws a Vuex warning to not mutate the store state outside mutation handlers.
I don't feel that disabling strict: true in my store is the way to go.

Could it be a Vuex error inside the boostrap-vue package?

**Comment by piotrekfracek** [comment]
I have the same issue. Everything works until I try to sort

**Comment by piotrekfracek** [comment]
@Mark-de-Haan 
I've found solution. Try to duplicate array before you pass it to the table component

```
JSON.parse(JSON.stringify(this.data)),
```

**Comment by pi0** [comment]
@Mark-de-Haan @piotrekfracek Thanks for reporting.  6e1f0a2 should resolve this problem by cloning data when filtering/sorting using `slice()` and JSON trick is not needed anymore.

**Comment by toadkicker** [comment]
I'm seeing this problem with using the table details example.

**Comment by tmorehouse** [comment]
Table details needs to use Vue's `$set(...)` method in order to update the row's details flag in the record data, which triggers the display of the details scoped slot.

**Comment by ropeladder** [comment]
Does that mean we're just stuck with the Vuex errors when using table details (when our tables originate in the data store)?
