### ISSUE TITLE
#2801 broke table range select with SHIFT

### ISSUE THREAD

**Issue by thejcannon** [bootstrap-vue/bootstrap-vue#2891]
When you <kbd>SHIFT</kbd> click using a table in `range` mode, instead of rows being selected text is selected 😞.

Tiny fiddle with a table to play around with (with version at 2.0.0-rc15): https://jsfiddle.net/g13o7uht/

**Comment by tmorehouse** [comment]
This will be fixed in release v2.0.0-rc.16

See https://github.com/bootstrap-vue/bootstrap-vue/pull/2876
