### ISSUE TITLE
SSR Mismatch using <b-table>

### ISSUE THREAD

**Issue by ryaposov** [bootstrap-vue/bootstrap-vue#2895]
## What's happening

When using `b-table` component, warnings and errors appear in console saying there's a mismatch in table's `<th>`.

![image](https://user-images.githubusercontent.com/5815992/54811915-1dc29500-4c8a-11e9-9339-6eb7cbbfa38c.png)

## Reproduction link
https://codesandbox.io/s/5kzpyjlyox?fontsize=14

## Environment
- latest Nuxt.js `2.5.1`
- SSR in `universal` mode
- latest bootstrap-vue `2.0.0-rc.15`

**Comment by tmorehouse** [comment]
Could you try replacing the self closing tags in your templates?

i.e. `<b-table ... />` with `<b-table ...></b-table>`

**Comment by tmorehouse** [comment]
Could you try: https://codesandbox.io/s/5yqvv4pyy4

Upgraded Nuxt dep to 2.5.1 (which uses a newer Vue version)

**Comment by ryaposov** [comment]
Yeah, it's the same with you fork. Don't you see it in the console on the right?
![image](https://user-images.githubusercontent.com/5815992/54824777-35ab1080-4cac-11e9-9eee-b9f4cbb11492.png)

Actually locally in my project I use `2.5.1`, it's just for reproduction it was `2.4.3`.

**Comment by tmorehouse** [comment]
Weird... I didn't see any console errors in my browser.
