### ISSUE TITLE
b-input-group prepend changes

### ISSUE THREAD

**Issue by ghenry** [bootstrap-vue/bootstrap-vue#2898]
Hi all,

This used to work, but has stopped:

```
              <b-form-group horizontal class="mb-0">
                <b-input-group
                  title="Filter your data"
                  prepend="<i class='fas fa-filter'/>"
                >
                  <b-form-input v-model="filter" placeholder="Type to search" />
                  <b-input-group-append>
                    <b-btn :disabled="!filter" @click="filter = ''"
                      >Clear</b-btn
                    >
                  </b-input-group-append>
                </b-input-group>
              </b-form-group>
```

the font awesome would show, now I just see `<i class='fas fa-filter'/>`

Should I just use the label slot or prepend component like mentioned in https://github.com/bootstrap-vue/bootstrap-vue/issues/2070

Thanks.

**Comment by ghenry** [comment]
If I use the component approach, I get attached.
![Screenshot_2019-03-22 Customers - SureVoIP Portal](https://user-images.githubusercontent.com/159608/54836507-42376500-4cbc-11e9-8f55-fcd645df2ca8.png)

**Comment by ghenry** [comment]
This `<slot name="label"><i class="fas fa-filter fa-fw"></i></slot>` gives me:
![Screenshot_2019-03-22 Customers - SureVoIP Portal(1)](https://user-images.githubusercontent.com/159608/54836634-8dea0e80-4cbc-11e9-94cd-e2382681486e.png)

**Comment by ghenry** [comment]
However, this works:

```
                <b-input-group title="Filter your data">
                  <b-input-group-prepend>
                    <div class="input-group-text">
                      <i class="fas fa-filter" />
                    </div>
                  </b-input-group-prepend>
                  <b-form-input v-model="filter" placeholder="Type to search" />
                  <b-input-group-append>
                    <b-btn :disabled="!filter" @click="filter = ''"
                      >Clear</b-btn
                    >
                  </b-input-group-append>
                </b-input-group>
              </b-form-group>
```

![Screenshot_2019-03-22 Customers - SureVoIP Portal(2)](https://user-images.githubusercontent.com/159608/54836897-12d52800-4cbd-11e9-8a4c-df781f9c1134.png)


I guess prepend it not processed as HTML in the first version?

**Comment by tmorehouse** [comment]
all props that accept test no longer accept HTML (unless he prop is appended with `Html`, i.e. `labelHtml`), due to potential Cross Site Scripting (XSS) vulnerabilities when passing user supplied content to the component.

For Input Groups, use the slots, or individual helper components for prepend/append for HTML content.

**Comment by tmorehouse** [comment]
https://bootstrap-vue.js.org/docs/components/input-group#comp-ref-b-input-group-text

```html
<b-input-group>
  <b-input-group-text slot="prepend"><i class="fas fa-filter fa-fw"></i></b-input-group-text>
  <b-form-input v-model="filter" placeholder="Type to search"></b-form-input>
  <b-button slot="append" :disabled="!filter" @click="filter = ''">Clear</b-button>
</b-input-group>
```
