### ISSUE TITLE
IE11 `closest` polyfill with SVG elements

### ISSUE THREAD

**Issue by Alex--C** [bootstrap-vue/bootstrap-vue#2900]
Since IE11 does not support `Element.prototype.closest`, it falls back to the included polyfill. This polyfill fails if `element` happens to be an SVG since SVGs do not have the `parentElement` property in Internet Explorer. The polyfill then tries to access `undefined.parentElement`.

A possible fix would be to use `parentNode` instead of `parentElement` or check whether `element` is undefined in the `do...while` loop. I don't think that this would break anything, but I don't know enough about the inner workings of bootstrap-vue.

**Comment by tmorehouse** [comment]
You could pre-load a more robust polyfill at the top of your project, and the helper utility `closest` will use that version of the polyfill.

Using `parentNode` might break when encountering text nodes and other non HTML Element nodes.

**Comment by tmorehouse** [comment]
Although I do see the polyfill at MDN has been updated:

https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill

And they fallback using `el = el.parentElement || el.parentNode`

We can update our "polyfill" (which isn't really a polyfill, as we don't overide the prototype) to use the latest polyfill example from MDN.

**Comment by tmorehouse** [comment]
@Alex--C do you know if on IE 11 if an `<svg>` element satisfies the following?

```js
svg.nodeType === Node.ELEMENT_NODE // Node type= 1
```
