### ISSUE TITLE
Checkbox without label

### ISSUE THREAD

**Issue by redraw** [bootstrap-vue/bootstrap-vue#2911]
Using `bootstrap-vue@2.0.0-rc.15`.

`<b-form-checkbox>` requires a label to work properly. If label is empty, there's extra padding/margin around the checkbox.

A workaround is to add `plain` prop to `<b-form-checkbox>`.

Here's Bootstrap documentation on checkbox without labels: https://getbootstrap.com/docs/4.1/components/forms/#without-labels

**Comment by tmorehouse** [comment]
@redraw Currently there is already a `plain` prop to render a non-custom checkbox (or radio), but it always renders a label element next to it.

PR #2911 checks to see if the label content is empty in plain mode, and if so, adds the 'position-fixed' class to the input, and suppresses the rendering of the label element. a new prop `aria-label` is provided to place the `aria-label` on the input.

In non-plain mode (custom style, the default) the label is always rendered as the label is needed to render the custom check/radio indicator.

**Comment by tmorehouse** [comment]
For custom checkbox/radio without a label, you can add class `mr-0` to remove the right margin (in `inline` mode)

**Comment by redraw** [comment]
@tmorehouse thanks for the quick update! for non-plain mode, adding `mr-0` removes the right margin, but there's still a top space that makes the checkbox be placed like one line below the following inline elements. Not sure if you can reproduce it or you need an example

**Comment by tmorehouse** [comment]
checks and radios (individual ones), default to `stacked` mode, which will have vertical margins.  Try setting the `inline` prop

**Comment by redraw** [comment]
that's right
