### ISSUE TITLE
Why are Bootstrap-Vue types so bad?

### ISSUE THREAD

**Issue by baseprime** [bootstrap-vue/bootstrap-vue#2914]
The typings file at `src/index.d.ts` is out of date and only includes types for methods, but not properties, computed properties, etc. Since there is no `@types/bootstrap-vue`, wouldn't it make sense to improve the typings file included in the source?

**Comment by tmorehouse** [comment]
Not many of the core team use TypeScript, so we don't have expertise in defining the types, and rely on contributors to help.

I agree that the component props should be defined (although I don't think any of the computed properties or data should be made public types, with the exception of public methods - but not private methods).

**Comment by baseprime** [comment]
@nicolabosco87 Do you want to keep contributing Types or would it be best if we work out generating types in some automated way?

**Comment by iliveoncaffiene** [comment]
Just a note: starting to be partially addressed in #2867

**Comment by jackmu95** [comment]
The latest changes should have improved types.

**Comment by hisuwh** [comment]
What's happening with typings.  They don't seem to work at all:
![image](https://user-images.githubusercontent.com/4470351/109135767-54936680-774f-11eb-852f-0e1831d3b55e.png)
