### ISSUE TITLE
Documentation for old versions

### ISSUE THREAD

**Issue by feanor777** [bootstrap-vue/bootstrap-vue#2916]
Hello guys,
Sorry, is it possible to view documentation for old versions?
Because as I see on the website, it's just possible to see the latest version documentation.
https://bootstrap-vue.js.org/docs

Thanks a lot!

**Comment by tmorehouse** [comment]
We don't maintain previous versions of the docs online.  But you can get the docs for each version by downloading the specific version at https://github.com/bootstrap-vue/bootstrap-vue/tags and running the local docs server (or view the source README.md files for the docs).

**Comment by feanor777** [comment]
Thank you for the fast answer!

**Comment by ioweb-gr** [comment]
@tmorehouse Hi, could you explain briefly how to run the local docs server ? Thanks

**Comment by johnsba1** [comment]
@ioweb-gr I just had to do this to track down some old docs. I did this with one of the 2.0 release candidates, so things may not be exactly the same.

The CONTRIBUTING.md file has instructions for running the docs server. They recommended using yarn, but I got it working with npm.

`git clone git@github.com:bootstrap-vue/bootstrap-vue.git`
`cd bootstrap-vue/`
`git checkout v2.x.x`
`npm install`
`npm run docs-dev`

Docs will be accessible on port 3000.

Hope that helps!

**Comment by ioweb-gr** [comment]
@johnsba1 Thank you very much. All this can be very overwhelming when you're just starting something :D

**Comment by 1337erik** [comment]
getting this error when running "npm run docs-dev" for version 1.5.1. I removed node_modules, set the package.json version manually for both "highlightjs" & "highlight-loader" thinking maybe a newer version was causing an issue and nothing worked. Does anyone have a hosted version of the 1.5.1 docs or could help diagnose this issue? I'm not sure what to make of this at this point 
![image](https://user-images.githubusercontent.com/20347157/99415023-6601e280-28c5-11eb-9363-026eba9ee71c.png)

**Comment by codemma** [comment]
> getting this error when running "npm run docs-dev" for version 1.5.1. I removed node_modules, set the package.json version manually for both "highlightjs" & "highlight-loader" thinking maybe a newer version was causing an issue and nothing worked. Does anyone have a hosted version of the 1.5.1 docs or could help diagnose this issue? I'm not sure what to make of this at this point
> ![image](https://user-images.githubusercontent.com/20347157/99415023-6601e280-28c5-11eb-9363-026eba9ee71c.png)

Hi! I ran in to the same issue, and solved it by installing the module!

npm install highlight.js --save
