### ISSUE TITLE
Remove inline-style from collapse component

### ISSUE THREAD

**Issue by fregiese** [bootstrap-vue/bootstrap-vue#2919]
The collapse component has an inline-style **display:none** on the content when closed. The inline-style can be removed, because the bootstrap css already does the display:none property with the **.collapse** class.

You can reproduce the issue with the official vue-bootstrap doc: https://bootstrap-vue.js.org/docs/components/collapse

**Comment by tmorehouse** [comment]
That style is added by the Vue directive `v-show` and is used to trigger the transitions on the collapse element.  BootstrapVue doesn't add the style, it is the Vue directive that does.

**Comment by tmorehouse** [comment]
See https://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components

> Vue provides a transition wrapper component, allowing you to add entering/leaving transitions for any element or component in the following contexts:
> - Conditional rendering (using v-if)
> - Conditional display (using v-show)
> - Dynamic components
> - Component root nodes

**Comment by fregiese** [comment]
Thanks a lot for the quick answer!
