### ISSUE TITLE
Pagination and Pagination Nav do not have valid accessibility roles

### ISSUE THREAD

**Issue by salfej** [bootstrap-vue/bootstrap-vue#2921]
Roles for all elements within Pagination components are being set to "none presentation" when it should just be "presentation". Here's a screenshot of the demo on the bootstrap-vue.js.org webpage. 

![image](https://user-images.githubusercontent.com/10404888/55020189-56cd7300-4fc4-11e9-89f4-327cff513ec7.png)

Affected items are:

- li.page-item
- li.page-item.active
- li.page-item.bv-d-xs-down-none
- li.page-item.flex-fill
- li.page-item.flex-fill.bv-d-xs-down-none

The online playground says BV version is v2.0.0-rc.15

**Comment by tmorehouse** [comment]
Depending on which ARIA spec the user agent is following, it will be either `none` or `presentation`.  Providing both roles covers both cases.

**Comment by tmorehouse** [comment]
See https://www.w3.org/TR/wai-aria-1.1/#none

**Comment by salfej** [comment]
Thank you for the clarification! Would you agree then that this is an issue with Chrome DevTools Lighthouse audit categorizing "none presentation" as an invalid value? 

![image](https://user-images.githubusercontent.com/10404888/55026208-897d6880-4fd0-11e9-87fb-8f200fc7c4dd.png)

**Comment by tmorehouse** [comment]
Yeah.  Even the actual W3C ARIA validator has issues with it.

**Comment by tmorehouse** [comment]
But most screen readers are pretty much OK with it.

**Comment by salfej** [comment]
Seems to be an issue with the aXe accessibility extension as well. I'll write up an issue over there per Lighthouse instructions. Thanks!

**Comment by tmorehouse** [comment]
aXe is tailored around WCAG 2 spec, so it ignores the 1.1 spec.

They should probably give a warning instead of an error for `role="none presentation"`

**Comment by salfej** [comment]
Ahh, okay. Currently they categorize `role="none presentation"` as a critical error.

![image](https://user-images.githubusercontent.com/10404888/55027665-cdbe3800-4fd3-11e9-89f3-429e748041be.png)

**Comment by tmorehouse** [comment]
I wonder if they accept `role="presentation none"`

Maybe most of the screen reader browser extensions (JAWS, VoiceOver, etc) have finally migrated to V2 of the spec... if so we could migrate to `role="none"` if support is there.

**Comment by salfej** [comment]
Here's the issue I created over on the axe github. Thanks again for all of your help! https://github.com/dequelabs/axe-core/issues/1462

**Comment by mattgrande** [comment]
(Sorry for reviving an old issue)

From what I can tell, IE (and possibly Edge) don't support fallback roles like `none presentation`. I think we should just use `presentation`, since that seems to be supported everywhere.

See also:

* https://codepen.io/stevef/post/none-or-presentation
* https://github.com/dequelabs/axe-core/issues/1462#issuecomment-476859898
* https://github.com/w3c/aria-practices/issues/515#issuecomment-344009507

**Comment by tmorehouse** [comment]
The only issue with `role="presentation"` only is that it can also act like `aria-hidden="true"` which can hide all child content roles (i.e. the nested link)

**Comment by mattgrande** [comment]
Hmm, I'm not sure if that's accurate (or at least, I'm not sure that's only the case with `role="presentation"`).

https://www.w3.org/TR/using-aria/#ariapresentation

> `role=presentation`, **or its synonym** `role=none`, removes the semantics from the element it is on.

Although, I haven't verified, maybe browsers implement them differently even though they're supposed to be the same...

**Comment by tmorehouse** [comment]
> Although, I haven't verified, maybe browsers implement them differently even though they're supposed to be the same...

Browser implement them differently.
