### ISSUE TITLE
Website Documentation Formatting (on Table page) is broken

### ISSUE THREAD

**Issue by iliveoncaffiene** [bootstrap-vue/bootstrap-vue#2939]
When browsing the documentation (for example: https://bootstrap-vue.js.org/docs/components/table/)
The styling and side pane navigation is completely not working:
![image](https://user-images.githubusercontent.com/13472837/55188988-18c28180-5173-11e9-9cc7-03092bb8b5a0.png)

Further investigating and I have this console error:
![image](https://user-images.githubusercontent.com/13472837/55188699-596dcb00-5172-11e9-9733-78c9ef327a55.png)

Issue is present in both Chrome & Edge.

**UPDATE**
Issue only happens if I load my page onto the table documentation (ex: Ctrl + F5 when on the table documentation). If I browse to any other documentation page via navigation on the left, those pages are also not working.
If I reload the page on any other documentation (aside from table), the side pane navigation shows up, and then I can browse to the Table documentation and that shows with no issues.

**Comment by tmorehouse** [comment]
Is this only happening with IE/Edge, or do you see thus issue with other browsers as well?

**Comment by iliveoncaffiene** [comment]
I just realized I totally meant to say Chrome/Edge - will edit post.

**Comment by tmorehouse** [comment]
Might be a formatting issue in the table readme.md file. The right hand side table of contents is generated on the fly by paring the headings outof the readme.

**Comment by tmorehouse** [comment]
So it is only happening with that one docs page?

**Comment by iliveoncaffiene** [comment]
@tmorehouse I think it's a routing issue - the formatting works fine if I go to any other link and then click to the table documentation (ex: browse to https://bootstrap-vue.js.org/docs/components/button and click to Table)

**Comment by tmorehouse** [comment]
The docs site is pre-rendered into html files, and the once loaded switches to PWA mode once loaded.

**Comment by tmorehouse** [comment]
Found the issue.  was a bad closing HTML tag in the README.md file.

Docs site should be updated in a few minutes.
