### ISSUE TITLE
Programatically set the :style="computedProp" in a b-card

### ISSUE THREAD

**Issue by Doogiemuc** [bootstrap-vue/bootstrap-vue#2946]
I need to change the stlye of a b-card.  I cannot just simply assign a class, because I need to set some css value to a dynamically computed value. 

`<b-card>` does accept a static `style="..."` attribute. But it does not accept the vue dynamic `:style=".."`  with colon prefix.

Code Example:
```
    <b-card :title="title" class="someStaticClass"  :style="computedStyle">
   </b-card>

    Vue.component('card', {
	props: ['title'],
	computed: {
		computedStyle: function() {
			return "background-color: "+this.complicateCalculationOfBackgroundCol()
		}
        }
    }
```

Expeced:   The computedStyle is applied to the outermost card  div

Actual: The :stlye attribute is completely ignored. :-(

**Comment by jackmu95** [comment]
I've tried it in our [Playground](https://bootstrap-vue.js.org/play) and everything works as expected.
Can you please create a showcase of your problem in a online code editor of your choice.

```vue
<template>
  <b-card :title="title" :style="computedStyle"></b-card>
</template>

<script>
export default {
  data: () => {
    return {
      title: 'Card'
    }
  },
  computed: {
    computedStyle() {
      return {
        color: 'red'
      }
    }
  }
}
</script>
```

**Comment by tmorehouse** [comment]
The following:

```js
    Vue.component('card', {...}`)
```

registers a _new_ component called `card` with Vue (using the definition options passed as the second argument).

**Comment by Doogiemuc** [comment]
**SOLUTION**:  (if anybodey else stumbles over this)

The solution was, that one must return an **object** from the computed method. Not just a string with one CSS stlyle.

DOES NOT WORK
```
  computed: {
    computedStyle() {
      return "color: 'red'"
    }
  }
```

WORKS
```
  computed: {
    computedStyle() {
      return {
        color: 'red'
      }
    }
  }
```
