### ISSUE TITLE
ScrollSpy support?

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#295]
Should Bootstrap-vue have a directive for ScrollSpy (i.e. `v-scrollspy`)?

http://v4-alpha.getbootstrap.com/components/scrollspy/

I could look into seeing how it could be implemented without jQuery

**Comment by pi0** [comment]
@tmorehouse Yes that would be so awesome if you can work on it :)

**Comment by tmorehouse** [comment]
I'll see what I can do.

**Comment by tmorehouse** [comment]
I have a prototype started, but I will come back to it after I check out a few other issues.

**Comment by tmorehouse** [comment]
PR #355

**Comment by tmorehouse** [comment]
PR #355
