### ISSUE TITLE
b-dropdown no-caret not working

### ISSUE THREAD

**Issue by wildeee** [bootstrap-vue/bootstrap-vue#2951]
b-dropdown no-caret is not working. That's my code fragment

    <b-dropdown
      variant="link"
      size="sm"
      no-caret
      right
    >
      <template slot="button-content">
        <i class="fas fa-ellipsis-v ml-1"></i>
      </template>
      <slot name="controls"/>
    </b-dropdown>

And the arrow stills here
![image](https://user-images.githubusercontent.com/5889381/55239879-575d4800-5216-11e9-9394-3c218a9527da.png)

I'm using the version 2.0.0-rc.16
I'm also importing the bootstrap css files

**Comment by jackmu95** [comment]
@wildeee What version of BootstrapVue are you using?

**Comment by tmorehouse** [comment]
Make sure you are using the latest version of BootstrapVue

**Comment by wildeee** [comment]
Can I try to fix?
I'm almost sure it came with the #2909 fix

**Comment by jackmu95** [comment]
@wildee I couldn't reproduce your issue, so a testcase would be nice but contributions are always welcome.

**Comment by tmorehouse** [comment]
Tried in the Playground and it works fine:

![image](https://user-images.githubusercontent.com/2781561/55269467-6bcf2e00-5272-11e9-88ae-7af76d0c0e4b.png)

And exported to jsfiddle:

https://jsfiddle.net/xepwora8/

**Comment by Owumaro** [comment]
Had the same issue importing `BNav` & `BNavItemDropdown` as individual components.

The css styles to make the `no-cart` features work are located in this scss file: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/dropdown/_dropdown.scss
Which is not automatically loaded when using `BNavItemDropdown` as individual component.

I had to manually import the scss file with `@import 'node_modules/bootstrap-vue/src/components/dropdown/_dropdown.scss';` to make it work.

**Comment by DiazHub** [comment]
I am also experiencing this issue. The `no-caret` prop fails to do anything. I have observed that the prop is set to true using the Vue Browser tools. I am running 2.0.0-rc.19.

```
<b-dd variant="link" no-caret>
        <template slot="button-content">
          <font-awesome-icon id="ellipsis" icon="ellipsis-v"/>
        </template>
        <b-dd-item>link 1</b-dd-item>
        <b-dd-item>link 2</b-dd-item>
</b-dd>
```

**Comment by DiazHub** [comment]
> Had the same issue importing `BNav` & `BNavItemDropdown` as individual components.
> 
> The css styles to make the `no-cart` features work are located in this scss file: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/dropdown/_dropdown.scss
> Which is not automatically loaded when using `BNavItemDropdown` as individual component.
> 
> I had to manually import the scss file with `@import 'node_modules/bootstrap-vue/src/components/dropdown/_dropdown.scss';` to make it work.

I am not manually importing, but I tried importing that file, and it did not resolve the issue for me.

**Comment by tmorehouse** [comment]
@DiazHub have you tried importing the full BootstrapVue CSS or SCSS? (if using the SCSS yout will also need to import Bootstraps Variables, mixins, and functions (all imported into a single `custom.scss` file)

**Comment by DiazHub** [comment]
@tmorehouse I am importing the full BoostrapVue in my app. In my main.js file I have:

`import BootstrapVue from 'bootstrap-vue'`
...
`Vue.use(BootstrapVue)`

In my dependencies:
...
```
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.0-rc.19",
```
...

**Comment by tmorehouse** [comment]
You need to import BootstrapVue CSS (or SCSS) along with Bootstrap V4.3.1 CSS (or SCSS) into your app (or into your page's `<head>` section)

**Comment by DiazHub** [comment]
@tmorehouse My apologies, I forgot to mention that in our App.vue file, we have the following:

```
<style lang="scss">
  /*Overwrite the official bootstrap with custom properties*/
  @import '@/assets/scss/custom-bootstrap.scss';
  /*Import official bootstrap scss */
  @import '../node_modules/bootstrap/scss/bootstrap.scss';
...
</style>
```

After further investigation, I compared with the bootstrapvue documentation and saw that I was missing a line:

**Comment by boukeversteegh** [comment]
If you have a custom `index.scss` that selectively imports components, make sure the dropdown scss is imported.

```scss
//================= COMPONENTS ====================
// @import "~bootstrap-vue/src/components/avatar/index";
// @import "~bootstrap-vue/src/components/calendar/index";
// @import "~bootstrap-vue/src/components/card/index";
@import "~bootstrap-vue/src/components/dropdown/index";
```
