### ISSUE TITLE
table row detail is toggled even if row's item does not contain _showDetails

### ISSUE THREAD

**Issue by mysuf** [bootstrap-vue/bootstrap-vue#2960]
Clicked rows with missing row's item._showDetails does not toggle on direct click as expected, but toggles later on row click that contains _showDetails. Dunno what causes this behaviour..maybe previous focus?

**Steps to reproduce:**
1. set up 2row table, first item without _showDetails and second with _showDetails: false
2. click on row without _showDetails (nothing happens, only focus)
3. click on row with _showDetails present
=> both rows toggles

**Expected behaviour:**
Row which item is missing _showDetails does not toggle at all

Is there any temporary workaround?

Thanks

version: 2.0.0-rc.16

**Edit:**
fixed with following modification of rowDetails's handler:

handler registered on b-table as:
```
@row-clicked="toggleRowDetails"
```

wrong behaviour:
```javascript
toggleRowDetails(item) {
  item._showDetails = !item._showDetails;
}
```

fixed:
```javascript
toggleRowDetails(item) {
  if ('_showDetails' in item) {
    item._showDetails = !item._showDetails;
  }
}
```
Anyway, it looks like click event bubbles through multiple rows. Is this behaviour documented anywhere?

**Comment by tmorehouse** [comment]
This is due to Vue's reactivity limitations... if a property first doesn't exist on an object it won't be reactive.

change your method to this:

```js
toggleRowDetails(item) {
  this.$set(item, '_showDetails', !item._showDetails)
}
```

See docs at https://bootstrap-vue.js.org/docs/components/table#row-details-support

> **Note:** If manipulating the `_showDetails` property directly on the item data (i.e. not via the `toggleDetails` function reference), the `_showDetails` properly **must** exist in the items data for proper reactive detection of changes to it's value.

**Comment by tmorehouse** [comment]
The workaround is to use `this$set` to define the new item property as reactive (which is what the internal `toggleDetails` function does.

**Comment by mysuf** [comment]
@tmorehouse Thanks for explanation! The thing is that I want some rows to be inactive (not toggable) and keep it so. I guess that this.$set will make these rows toggable, doesnt it?

**Comment by tmorehouse** [comment]
Then what you should be doing, if you son't want some rows with details is to use a second property in your item data to signify that it shouldn't be toggled, and check for the truthiness of that item property in your row-clicked handler.

Or check to see if `_showDetails` is not `undefined` before toggling it:

```js
toggleRowDetails(item) {
  if (item._showDetails !== undefined) {
    item._showDetails = !item._showDetails
  }
}
```
