### ISSUE TITLE
Docs how to apply the pagination stuff in html

### ISSUE THREAD

**Issue by franktim77** [bootstrap-vue/bootstrap-vue#2972]
is there a demo to use it in html directly.

eg.: http://hootlex.github.io/vuejs-paginator/

**Comment by tmorehouse** [comment]
Check the pagination-nav docs out (if you are wanting to paginate between page URLs on a site)

https://bootstrap-vue.js.org/docs/components/pagination-nav

**Comment by franktim77** [comment]
I have no nodejs, npm.
develop it in text editor.

**Comment by tmorehouse** [comment]
I would recommend starting with some basic in-browser vue tutorials first (if you haven;t already started there)

https://vuejs.org/v2/guide/#Getting-Started
