### ISSUE TITLE
Pagination model not updated when per page is updated

### ISSUE THREAD

**Issue by atrunelle** [bootstrap-vue/bootstrap-vue#2987]
When using b-pagination component, if the number of item per page is updated, the current page is not updated. 

How to reproduce:
See https://codesandbox.io/s/7j017j3yy0
Click on page 3, change the number of page with the select to All. The current page is still 3 and no items are displayed in the table.

I found this after upgrading from RC 12 to RC 16.

- Operating system and version: Mac OS X
- Browser and version: Chrome
- Version of BootstrapVue that you are using: RC 16

**Comment by tmorehouse** [comment]
We may need to add in a watcher for the perPage prop.

**Comment by tmorehouse** [comment]
Actually there is a typo in your codesandbox on the current page binding on the b-table. It should be `currentPageValue`

**Comment by atrunelle** [comment]
@tmorehouse  Hum, I don't see any `currentPageValue` in my sandbox. Maybe it was not saved properly (as I had some before). Could you have another look?

**Comment by tmorehouse** [comment]
It must have been a previous version of the sandbox that I was looking at.

It looks like we aren't emitting the current page value via the model when the previous current page is no longer available.
