### ISSUE TITLE
SSR mismatch on using <b-card>

### ISSUE THREAD

**Issue by n-agi** [bootstrap-vue/bootstrap-vue#2999]
- Operating System: MacOS 10.14.2
- Browser: Chrome latest
- BootstrapVue version: 2.0.0-rc16
- Bug Reproduction: https://codesandbox.io/s/k08rlzv4lo

Inserting `<div>` tag inside `<b-card-text>` causes a mismatch between client and server.
![image](https://user-images.githubusercontent.com/11346770/55480029-4ff4cf00-565a-11e9-925f-b9d9978a3c50.png)

**Comment by tmorehouse** [comment]
`<b-card-text>` renders a `<p>` tag by default... which under HTML5 spec cannot contain another block-level element (unless it's display value is changed).  The browser is hoisting the `<div>` outside the `<p>` tag (as in HTML4, the `<p>` tag was allowed to be used without a closing tag (just like `<br>` has no closing tag).

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p

> Paragraphs are _block-level_ elements, and notably will automatically close if another _block-level_ element is parsed before the closing `</p>` tag.

If you want your `b-card-text` to be a `<div>`, set the `tag` prop to `div`:

```html
<b-card-text tag="div">Lorum Ipsum</b-card-text>
```

`<b-card-text>` is a helper that renders a paragraph of text, with the class `card-text` (which is used to remove the bottom margin on the _last_ occurrence of the tag)
