### ISSUE TITLE
[Vue warn]: "class" is a reserved attribute and cannot be used as component prop.

### ISSUE THREAD

**Issue by billlaw6** [bootstrap-vue/bootstrap-vue#300]
[Vue warn]: "class" is a reserved attribute and cannot be used as component prop.

found in

---> <BNavItemDropdown>
       <BNav>
         <BCollapse>
           <BNavbar>
             <Navigation> at /root/projects/snail-bootstrap-vue/src/components/AppNavigation.vue
               <Home> at /root/projects/snail-bootstrap-vue/src/views/Home.vue
                 <App> at /root/projects/snail-bootstrap-vue/src/views/App.vue
                   <Root> app.js line 850 > eval:430:1

**Comment by mosinve** [comment]
Closing due irrelevance
