### ISSUE TITLE
Z-index of Modal

### ISSUE THREAD

**Issue by cichy380** [bootstrap-vue/bootstrap-vue#3015]
Modal (element `.modal`) is appended to `<div id="modal-1___BV_modal_outer_" style="position: absolute; z-index: 2000;">` after opening. So.. Modal with correct z-index value (scss: `$zindex-modal: 1050 !default;`) is inside container with `z-index: 2000` and it is problem for me (Modals cover my toast notifications).

Tested with
bootstrap-vue: 2.0.0-rc.16
bootstrap: 4.3.1

**Comment by tmorehouse** [comment]
Each stacked modal gets a higher and higer base z-index to ensure the stacked modal (and it's backdrop) appears over top of the other modals.

One workaround is to override the toast's `z-index` value in CSS with some high value such as `999999999` to ensure it appears over the highest stacked modal.
