### ISSUE TITLE
Pagination has no click event?

### ISSUE THREAD

**Issue by alvirtuoso** [bootstrap-vue/bootstrap-vue#302]
I tried to add  v-on:click but the event never fires. How do I implement event on click?       
 <b-pagination size="md" :total-rows="100" v-model="currentPage" v-on:click="clicked" :per-page="10">
    </b-pagination>

**Comment by mosinve** [comment]
As quick possible solution, you can try `native `modifier: `v-on:click.native=""` to catch native click event, not pagination's own

**Comment by alvirtuoso** [comment]
As quick workaround, I made use of the custom input event that's being emitted like so: <b-pagination v-on:input="myClickedEventhandler" .... </b-pagination>

It's best to mention it in the documentation and perhaps not a bug?

Here's the part of the pagination component code that led me to this workaround.
`watch: {
            currentPage(newPage) {
                this.$emit('input', newPage); // custom input event emitted
            },
            value(newValue, oldValue) {
                if (newValue !== oldValue) {
                    this.currentPage = newValue;
                }
            }
        }`

**Comment by alik472** [comment]
It does have a click event.

`@page-click="handleClick"`
