### ISSUE TITLE
Cannot read property 'extend' of undefined - v2.0.0-rc.17

### ISSUE THREAD

**Issue by lareeth** [bootstrap-vue/bootstrap-vue#3038]
When upgrading from 2.0.0-rc.16 to 2.0.0-rc.17 my application fails to start, and gives the following error.

```
TypeError
Cannot read property 'extend' of undefined
```

I have confirmed this by creating a brand new site by running the following command, and choosing the bootstrap framework
```
npx create-nuxt-app example
```

Application is using nuxt 2.6.1 and bootstrap 4.3.1
Nodejs is 11.9.0 and npm 6.5.0
Test in Firefox 66.0.2 and Chrome 73.0.3683.103 running Windows 10 x64

![image](https://user-images.githubusercontent.com/1789694/55695734-d8080b00-59b1-11e9-9666-3d870f9477ba.png)

**Comment by hieuluong** [comment]
me too

**Comment by tmorehouse** [comment]
Are you using the BootstrapVue Nuxt plugin? Or are you including it in other ways?

What JS file are you importing for BootstrapVue?  The `/es/` files or from `/dist/` and if `/dist` which file? `bootstrap-vue.esm.js`, `bootstrap-vue.common.js` or `bootstrap-vue.js` (or their minified versions)?

Could you provide some code sample of what is being created for your app Entry Point?

It looks like `Vue` is not being included and it can't call `Vue.extend({...})` when the components are being created.

**Comment by lareeth** [comment]
I have tried it with a fresh nuxt project with the following dependencies

```
  "dependencies": {
    "@nuxtjs/pwa": "^2.6.0",
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "2.0.0-rc.16",
    "cross-env": "^5.2.0",
    "nuxt": "^2.4.0"
  }
```

Nuxt loads it through its config file

```
  modules: [
    // Doc: https://bootstrap-vue.js.org/docs/
    'bootstrap-vue/nuxt',
    '@nuxtjs/pwa',
  ],
```

Unfortunately I don't know any more about how its loaded under the covers there

It will only load when set to a version before rc.17

**Comment by hieuluong** [comment]
I reverted verion rc.15, it worked.

**Comment by tmorehouse** [comment]
Try adding in `vue` as a dependency

```json
 "dependencies": {
    "@nuxtjs/pwa": "^2.6.0",
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "2.0.0-rc.16",
    "cross-env": "^5.2.0",
    "nuxt": "^2.4.0",
    "vue": "^2.6.10"
  }
```

**Comment by lareeth** [comment]
Still the same error, I set bootstrap-vue to ```2.0.0-rc.17``` as it works with previous versions.

As I mentioned, if you run ```npx create-nuxt-app example``` and choose bootstrap, you can see the same error, I was able to replicate it with a fresh project.

**Comment by haric655** [comment]
![image](https://user-images.githubusercontent.com/24701253/55711233-fc390b80-59f4-11e9-95a7-643c09a8902d.png)
how to fix? Vue, Laravel 5.8

**Comment by nosehair** [comment]
had the same issue after an npm update - reverting to 2.0.0-rc.16 seems to resolve issue for now

**Comment by ptdev** [comment]
Hi, this is also happening on my end after upgrading.
Using nuxt with bootsrap-vue/nuxt module and the following configuration:
```
bootstrapVue: {
  bootstrapCSS: false,
  bootstrapVueCSS: false,
  componentPlugins: [
    'Navbar',
    'Nav',
    'Collapse',
    'Dropdown',
    'Breadcrumb',
    'Modal',
    'Tooltip',
    'Tabs'
  ],
  directivePlugins: ['Toggle', 'Modal', 'Tooltip']
}
```

**Comment by ludo237** [comment]
Confirm the issue with Vanilla vuejs and bootstrap-vue. In my case this error pops up

![image](https://user-images.githubusercontent.com/921500/55718290-ad42a480-59fb-11e9-828f-706bb17106c2.png)

This shows up only on one component where I have BTable imported.

My setup

- Laravel 5.8
- Laravel Mix
- VueJS latest
- Bootstrap-Vue Latest

Reverting to `2.0.0-rc.16` fix the issue

**Comment by wormen** [comment]
```
{
"bootstrap-vue": "^2.0.0-rc.2"
}
```

everything works great

**Comment by academici** [comment]
@ludo237 Im get same error with laravel mix 4.0.15 and bootstrap-vue rc14-17

**Comment by kyleweishaupt** [comment]
Having the same issue after updating to rc17.

**Comment by lareeth** [comment]
@tmorehouse Can you please leave this open until a fix is released, and then post the solution, even if it is just changing the version. Thanks

**Comment by tmorehouse** [comment]
We've also pinned the issue to the top of the issues page.

**Comment by raank** [comment]
Try use rc-15. Its work here.

```
{
"bootstrap": "^4.1.0",
"bootstrap-vue": "^2.0.0-rc.15",
"vue": "^2.5.16"
}
```

**Comment by leep0o** [comment]
my case:
```
{
  "bootstrap": "^4.3.1",
  "bootstrap-vue": "^2.0.0-rc.15",
  "vue": "^2.5.7",
}
```
same error  ![Снимок экрана 2019-04-08 в 21 56 30](https://user-images.githubusercontent.com/22923493/55749476-acd0fa80-5a49-11e9-9cca-8348f14eddc0.png)

**Comment by lareeth** [comment]
There's a fix on the way, please use the thumbs up reaction if you have the same error instead of commenting

**Comment by tmorehouse** [comment]
v2.0.0-rc.18 has been released.

**Comment by leep0o** [comment]
Thank! Works! 2.0.0-rc.18

**Comment by tmorehouse** [comment]
We've also introduced a new option for the Nuxt module that will help reduce bundle size for final prod build, which allows you to choose betwen using the `/es` modules or `/src` directly (at the expense of taking a few seconds longer for build for tanspilation).

Documented in the getting started section.
