### ISSUE TITLE
Feature: Docs in dev mode

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#304]
Would it be possible to have the documentation site be run in such a way that the vue devtools extension could parse the component tree? It would be handy to further examine the component examples.

Thanks for the awesome library!

**Comment by mosinve** [comment]
You may run docs site locally by `npm run docs-dev`, Vue Devtools succesfully detects Vue.js, but as all examples executed in jsfiddle, it shows only components of nuxt docs site.

**Comment by alexsasharegan** [comment]
Ah, that's a good point about jsfiddle. I built it locally, so I can play around there as well. Thank you!
