### ISSUE TITLE
$attrs is readonly / $listeners is readonly.

### ISSUE THREAD

**Issue by ya-tmch** [bootstrap-vue/bootstrap-vue#3040]
Errors in the console when entering in the input.

Nuxtjs 2.6.1

<img width="258" alt="Снимок экрана 2019-04-08 в 14 43 17" src="https://user-images.githubusercontent.com/6257517/55697369-e2a3be00-5a0c-11e9-9eb4-c5a1e59aab0c.png">

<img width="522" alt="Снимок экрана 2019-04-08 в 14 45 14" src="https://user-images.githubusercontent.com/6257517/55697382-fc450580-5a0c-11e9-93f0-81bca16c241a.png">

<img width="722" alt="Снимок экрана 2019-04-08 в 14 47 18" src="https://user-images.githubusercontent.com/6257517/55697449-3adac000-5a0d-11e9-8bf8-6d63297a846e.png">

**Comment by tmorehouse** [comment]
Which version of BootstrapVue are you using?

**Comment by ya-tmch** [comment]
2.0.0-rc.17

I deleted the folder, reinstalled the packages and the error disappeared!

**Comment by jaideepdasviadynamics** [comment]
Getting this same error with version 2.0.0-rc.18. Error message
<img width="318" alt="Screenshot 2019-04-15 at 1 44 01 PM" src="https://user-images.githubusercontent.com/42375377/56116894-90bae500-5f84-11e9-92c2-acf068960c3b.png">

**Comment by jm-asm** [comment]
I'm having the same Problem. I think i narrowed it down a bit. I use webpack as bundler and include Vue in my App.js with `import Vue from 'vue/dist/vue.esm.js';`. Since 2.0.0-rc.16 the components of bootstrap-vue using `require('vue')`. Looks like because of that webpack is bundling it twice and because of that we keep getting these warnings.

This happens with 2.0.0-rc.17 and up, 2.0.0-rc.16 and 2.0.0-rc.15 are working fine.

**Comment by tmorehouse** [comment]
We need to add in Vue as a `peerDependancy`

**Comment by tmorehouse** [comment]
See related issue https://github.com/LinusBorg/portal-vue/issues/201 for a solution.

Basically you need to set up an alias in your bundler config file to specify which Vue build you are using.

https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

**Comment by tmorehouse** [comment]
Example with webpack and using the esm build of Vue:

```js
{
  resolve: {
    alias: {
      vue: 'vue/dist/vue.esm'
    }
  }
}
```

**Comment by tmorehouse** [comment]
Please upgrade to 2.0.0-rc.19

**Comment by tmorehouse** [comment]
The warning is not available in RC.19.... it will be in RC.20 (See https://github.com/bootstrap-vue/bootstrap-vue/pull/3168)

**Comment by c4ss** [comment]
> I am still encountering this issue at RC19. I have the following alias set in my webpack config:
> 
> ```
>     alias: {
>       ...
>       'vue$': 'vue/dist/vue.esm.js'
>     },
>    ...
>   },
> ```
> 
> I also did not receive a warning that I have multiple instances of Vue, if that is already merged in in RC19.
> 
> To note, I'm not using nuxt nor server-rendered components, but I am using vue-electron together with this as I'm using Electron alongside Vue for my project. Is there something else I can tell you to help to find the source of the problem? Or should I open a new issue for this?

Are you treating vue as an external in your webpack config?

```
externals: [
  'vue', // remove this line
],
```

**Comment by msmsimondean** [comment]
I'm using `RC19` and I'm also getting this issue.  I've tried fixing the alias issue and it doesn't seem to have fixed this issue for me.

**Comment by b-jan** [comment]
in `webpack.renderer.config.js` add `bootstrap-vue` to the List of node_modules to include in webpack bundle:

`let whiteListedModules = ['vue', 'bootstrap-vue']`

**Comment by KennanChan** [comment]
> in `webpack.renderer.config.js` add `bootstrap-vue` to the List of node_modules to include in webpack bundle:
> 
> `let whiteListedModules = ['vue', 'bootstrap-vue']`

Save my hours

**Comment by buithehien1991** [comment]
It still happen on version 2.1.0

**Comment by buithehien1991** [comment]
> 
> 
> in `webpack.renderer.config.js` add `bootstrap-vue` to the List of node_modules to include in webpack bundle:
> 
> `let whiteListedModules = ['vue', 'bootstrap-vue']`

Could you please where I should put this file? I put it into root of Rails folder and try but it still happen this error. 
Please help me!!!

**Comment by scottrobertson** [comment]
Getting this when upgrading to `2.1.0` from `2.0.0-rc.11`

**Comment by tmorehouse** [comment]
@scottrobertson soulds like you need to set up an alias for Vue, as mentioned in the above comments, and in the getting started docs https://bootstrap-vue.js.org/docs#aliasing-vue-import

**Comment by scottrobertson** [comment]
@tmorehouse, unfortunately, it does not work. Same errors :( Had someone else verify that the alias was setup correctly too.

**Comment by breekoy** [comment]
> in `webpack.renderer.config.js` add `bootstrap-vue` to the List of node_modules to include in webpack bundle:
> 
> `let whiteListedModules = ['vue', 'bootstrap-vue']`

Thank you! :)

**Comment by yangjindong** [comment]
> > in `webpack.renderer.config.js` add `bootstrap-vue` to the List of node_modules to include in webpack bundle:
> > `let whiteListedModules = ['vue', 'bootstrap-vue']`
> 
> Could you please where I should put this file? I put it into root of Rails folder and try but it still happen this error.
> Please help me!!!

This should resole your problem.

> For anyone experiencing this problem with Rails and Webpacker if you are importing Vue with the compiler:

import Vue from 'vue/dist/vue.esm'
to resolve this issue add the following line to the config/webpack/environment.js file:

environment.config.resolve.alias = { 'vue$': 'vue/dist/vue.esm.js' };
just before this line:

module.exports = environment

[https://github.com/vuetifyjs/vuetify/discussions/4068#discussioncomment-24987](url)

**Comment by 27Fallen-Angel** [comment]
Hello everyone!
I have a problem with bootsrap-vue. I use vue cli 3  and an error appears $attr $listener readonly. 
Please help ^^

**Comment by 27Fallen-Angel** [comment]
this is my vue.config.js module.exports = {
    css: {
        loaderOptions: {
            sass: {
                prependData: `@import "@/assets/styles/styles.scss";`
            }
        }
    }
}

**Comment by 27Fallen-Angel** [comment]
in my main.js 

import Vue from 'vue'
import App from './App.vue'
import { BootstrapVue, IconsPlugin } from 'bootstrap-vue'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
import "./assets/styles/styles.scss"

Vue.use(BootstrapVue)
Vue.use(IconsPlugin)
Vue.config.productionTip = false

new Vue({
  render: h => h(App),
}).$mount('#app')

**Comment by 27Fallen-Angel** [comment]
i use single wepback and babel

**Comment by tariktuzlakovic** [comment]
The fix that worked for me was to install separately bootstrap-vue and then bootstrap.

`npm install bootstrap-vue`

then

`npm install bootstrap`

Hope it helps!

**Comment by yannicklescure** [comment]
> > > in `webpack.renderer.config.js` add `bootstrap-vue` to the List of node_modules to include in webpack bundle:
> > > `let whiteListedModules = ['vue', 'bootstrap-vue']`
> > 
> > 
> > Could you please where I should put this file? I put it into root of Rails folder and try but it still happen this error.
> > Please help me!!!
> 
> This has resolved my problem.
> 
> > For anyone experiencing this problem with Rails and Webpacker if you are importing Vue with the compiler:
> > `import Vue from 'vue/dist/vue.esm'`
> > to resolve this issue add the following line to the config/webpack/environment.js file:
> > `environment.config.resolve.alias = { 'vue$': 'vue/dist/vue.esm.js' };`
> > just before this line:
> > `module.exports = environment`
> 
> [https://github.com/vuetifyjs/vuetify/discussions/4068#discussioncomment-24987](url)

Many thanks !

**Comment by CarlosZoft** [comment]
if you are using vue 2.7 and vite, try to use :

```ts
resolve: {
 alias: {
   vue: path.resolve(__dirname, './node_modules/vue/dist/vue.esm.js'),
 },
}
```
