### ISSUE TITLE
How could I use glyphicon in bootstrap-vue?

### ISSUE THREAD

**Issue by billlaw6** [bootstrap-vue/bootstrap-vue#305]
Hi, thanks for your fantastic work first, this help me kept learning vuejs and bootstrap. Now I found out  glyphicon in bootstrap does not work in bootstrap-vue, would anybody point out a way for me? Thanks a lot!
<i class="glyphicon glyphicon-home"></i> 

does not show up, b-nav and some others works fine for me.

**Comment by JoabMendes** [comment]
I the last version of bootstrap (v4) doesn't support glyphicons anymore, the same way it also switched from Less to Sass. However, you can use both [Font Awesome](http://fontawesome.io/) and [Github Octicons](https://octicons.github.com/) as a free alternative for Glyphicons.

**Comment by Diaskhan** [comment]
Yes its dropped
Proof link!
https://getbootstrap.com/docs/4.0/migration/#components

Friends this issue could be closed!
