### ISSUE TITLE
Show empty (or similar) for all-disabled tabs

### ISSUE THREAD

**Issue by thejcannon** [bootstrap-vue/bootstrap-vue#3052]
I have a `b-tabs` where each tab may/may not be disabled. In the event they are all disabled, I'd like to show some content (much like `slot="empty"` for not tabs).

I'm guessing the workaround is checking if all tabs are disabled, and rendering them via `slot="tabs"` and using `slot="empty"`, but that doesn't sound very fun.

**Comment by tmorehouse** [comment]
You could create a conditional `b-tab` (using `v-if` to show the tab when all tabs are disabled.

**Comment by thejcannon** [comment]
Well the tabs are static (each tab has some semantic meaning).

I've found if I just put a `<div>` inside `b-tabs` it renders exactly how I want it to:
```html
<b-tabs>
   <b-tab v-for="phase in phases" :key="phase" :disabled>{{ phase }}</b-tab>
   <div v-if="...">Content if all are disabled!</div>
</b-tabs>

```
