### ISSUE TITLE
Allow "justified" or "fill" <b-tabs>

### ISSUE THREAD

**Issue by thejcannon** [bootstrap-vue/bootstrap-vue#3053]
`b-nav` has "justified" and "fill" which are lovely. Any love for `b-tabs` having a similar properties?

**Comment by tmorehouse** [comment]
You can use the `nav-class` prop to add classes to the `ul.nav` wrapper... which is set as 'display: flex;`, and use the [bootstrap flex utilities](https://getbootstrap.com/docs/4.3/utilities/flex/):

For centering, or alignment:
```html
<b-tabs nav-class="justify-content-center" ...>
```

Or for fill try this:

```html
    <b-card no-body>
      <b-tabs card>
        <b-tab title="Tab 1" title-item-class="flex-fill">Tab Contents 1</b-tab>
        <b-tab title="Tab 2" title-item-class="flex-fill">Tab Contents 2</b-tab>
        <b-tab title="Tab 3" title-item-class="flex-fill">Tab Contents 3</b-tab>
      </b-tabs>
    </b-card>
```

**Comment by tmorehouse** [comment]
The latest release now has support for this.

**Comment by pfeatherstone** [comment]
Could this also be applied to vertical tabs?

**Comment by pfeatherstone** [comment]
So that the vertical tabs column extends the height of the page.
