### ISSUE TITLE
No way to calculate sum of column

### ISSUE THREAD

**Issue by hassanshuja** [bootstrap-vue/bootstrap-vue#3065]
I am stuck at calculating sum of column to show at the end of the row

here is my code 

    <template>
      <div>
        <b-card>
          <template slot="header">
            <h3 class="card-title">{{ $t('labels.backend.reports.titles.index') }}</h3>
          </template>
          <template class="pull-right">
            <div id="hideprint" class="pull-right">
              <b-btn class="btn-show pull-right" id="download" variant="secondary" @click="printFacture()">Download Pdf<i class="fe fe-file fe-lg"></i></b-btn>
            </div>
          </template>
          <b-datatable
            ref="datasource"
            @context-changed="onContextChanged"
            search-route="admin.jobcard.jobcardreports"
            delete-route="admin.reports.destroy"
            action-route="admin.reports.batch_action"
            :actions="actions"
            :selected.sync="selected"
          >
            <b-table
              ref="datatable"
              striped
              bordered
              show-empty
              stacked="md"
              no-local-sorting
              :empty-text="$t('labels.datatables.no_results')"
              :empty-filtered-text="$t('labels.datatables.no_matched_results')"
              :fields="fields"
              :items="dataLoadProvider"
              sort-by="reports.created_at"
              :sort-desc="true"
              id="expenses-report"
            >
              <template slot="created_at" slot-scope="row">
                <span>{{ row.item.created_at }}</span>
              </template>
              <template slot="expenses" slot-scope="row">
                {{  addService(row.value) }}

                <span>$ {{ row.item.expenses }}</span>

              </template>
              <template slot="quote_amount" slot-scope="row">
                <span>$ {{ row.item.quote_amount }}</span>
              </template>
              <template slot="profit" slot-scope="row">
                <span>$ {{ parseFloat(row.item.expenses) - parseFloat(row.item.quote_amount) }}</span>
              </template>
              <template slot="status" slot-scope="row">
                <span v-if="row.item.status == 'received'">Received</span>
                <span v-if="row.item.status == 'assigned'">Assigned</span>
                <span v-if="row.item.status == 'on hold'">On Hold</span>
                <span v-if="row.item.status == 'completed'">Completed</span>
                <span v-if="row.item.status == 'submitted for vetting'">Submitted for Vetting</span>
                <span v-if="row.item.status == 'invoiced'">Invoiced</span>
                <span v-if="row.item.status == 'paid'">Paid</span>
                <span v-if="row.item.status == 'cancelled'">Cancelled</span>
              </template>
              <template slot="bottom-row" slot-scope="row" >
              <td>Total</td>
              <td></td>
              <td>{{total}}</td>
              <td></td>
            </template>
            </b-table>
          </b-datatable>
        </b-card>
      </div>
    </template>

    <script>
    import html2pdf from 'html2pdf.js'
    import { setTimeout } from 'timers'

    export default {
      name: 'ReportsList',
      data () {
        return {
          model: {
            expenses: [],
            services: [],
          },
          selected: [],
          totalexp: 0,
          quotedAmount: [],
          fields: [
            { key: 'created_at', label: 'Date' },
            { key: 'jobcard_num', label: 'Jobcard #' },
            { key: 'expenses', label: 'Expenses' },
            { key: 'quote_amount', label: 'Quoted Amount' },
            { key: 'profit', label: 'Profit' },
            { key: 'status', label: 'Status' },
          ],
          actions: {
            destroy: this.$t('labels.backend.reports.actions.destroy'),

          }
        }
      },
      computed: {
        total: function() {
          return this.$store.state.totals.expense
        }
      },
      updated: {

      },
      methods: {
        addService(row) {
          // var newArr = new Array();
          // newArr.push(row.value)
          var total = parseFloat(row) + parseFloat(this.$store.state.totals.expense);
          this.$store.dispatch('TOTALS', total)
          // if(row)$store{
          //   this.model.expenses.push(row)
          // }
          //  this.model.services.push({});
          // return this.$refs.datasource.loadData()
          // this.model.service.push({});
        },
        dataLoadProvider (ctx) {
          return this.$refs.datasource.loadData(ctx.sortBy, ctx.sortDesc)
        },
        onContextChanged () {
          return this.$refs.datatable.refresh()
        },
        onDelete (id) {
          this.$refs.datasource.deleteRow({ report: id })
        },
        printFacture: function () {
          this.HideButtons()
          var elementor = document.getElementById('expenses-report')
          html2pdf(elementor, {
            margin: 1.5,
            filename: 'expensesReport.pdf',
            // image: { type: 'png' },
            html2canvas: { dpi: 900, letterRendering: false },
            jsPDF: { unit: 'cm', format: 'a3', orientation: 'l' }
          })
          setTimeout(() => {
            $('.card-body .row').show()
            $('#download').show()
          }, 2000)
        },
        HideButtons: function () {
          $('.card-body .row').hide()
          $('#download').hide()
        }
      }
    }
    </script>
here i am calling addService method to calculate the sum of the expenses and setting the state for expense total then i am calling total method in bottom-row template but i am getting error for infinite loop. is there any solutioin to calculate sum of each column. I have not found any documentation related to sum of columns. I use to make datatables from jquery datatables and i use footercallback function in jquery datatable but there is nothing in your documentation about this. please tell me how can i acheive sum of each column.

**Comment by tmorehouse** [comment]
Are you referring to a running total type sum column (with an accumulated value on each row), or to the value shown at the bottom of the table?

If the latter, use the b-table v-model to access the currently displayed rows (treat as readonly):

```html
<template>
  <b-table
    :fields="fields"
    :items="dataLoadProvider"
    v-model="shownRows"
  >
    <!-- could also be a footer field slot instead -->
    <template slot="bottom-row">
      <td>Total</td>
      <td></td>
      <!-- this is a computed prop that adds up all the expenses in the visible rows -->
      <td>{{ totalExpenses }}</td>
      <td></td>
    </template>
  </b-table>
</template>
<script>
export default {
  data() {
    shownRows: []
  },
  computed: {
    totalExpenses() {
      return this.shownRows.reduce((accum, item) => {
        return accum + item.expenses
      }, 0.00)
    }
  }
}
</script>
```

**Comment by tmorehouse** [comment]
You should avoid doing anything inside a render function (the slots) that will touch the state of your component, as that will trigger it to re-render and cause the state to be updated again and again, infinity.

**Comment by hassanshuja** [comment]
Yes thanks tmorehouse, v-model solved my problem. Thanks a lot for your help.

**Comment by allaghi** [comment]
What about more than one column ?
