### ISSUE TITLE
<b-dropdown-item> to is going to the server instead of using `vue-router`

### ISSUE THREAD

**Issue by WayneHiller** [bootstrap-vue/bootstrap-vue#3066]
Version 2.0.0-rc.18

When clicking the dropdown link the browser reloads the page from the server instead of using the vue-router ( :to="ii.url").

```
<b-navbar toggleable="md" type="dark" variant="info" fixed="top">
  <b-navbar-toggle target="nav_collapse"></b-navbar-toggle>
     <b-collapse is-nav id="nav_collapse">
       <b-navbar-nav>
          <b-nav-item v-for="i in items" v-if="!i.items" :key="i.caption" :to="i.url">
               {{ i.caption }}
           </b-nav-item>
           <b-nav-item-dropdown v-for="i in items" v-if="i.items" :key="i.caption" :text="i.caption">
              <b-dropdown-item v-for="ii in i.items" :key="ii.id" :to="ii.url">
                   {{ ii.caption }}
               </b-dropdown-item>
             </b-nav-item-dropdown>
          </b-navbar-nav>
       </b-collapse>
       <b-navbar-brand href="#">{{ title }}</b-navbar-brand>
</b-navbar>
```

In version 2.0.0-rc.11 it correctly uses the vue-router.

**Comment by tmorehouse** [comment]
If you change the `to` to the object form, does it work?

```html
<b-dropdown-item v-for="ii in i.items" :key="ii.id" :to="{ path: ii.url }">
  {{ ii.caption }}
</b-dropdown-item>
```

**Comment by tmorehouse** [comment]
Also, is it only `<b-dropdown-item>` or is `<b-nav-item>` also exhibiting the same issue?

**Comment by WayneHiller** [comment]
I changed it to the object form and it is still not working. I have not tried the b-nav-item

**Comment by tmorehouse** [comment]
I've just tried this in the playground with a b-dropdown-item and found that it was using the $router

**Comment by tmorehouse** [comment]
Are you running under Nuxt.js or plane Vue with vue-router?

**Comment by WayneHiller** [comment]
Plain Vue with vue-router.  
```
"vue": "2.6.10",
"vue-router": "3.0.3"
"bootstrap": "4.3.1",
"bootstrap-vue": "2.0.0-rc.18",
```

**Comment by tmorehouse** [comment]
I still can't reproduce the issue... Are your URLs relative or fully qualified (i.e. including the protocol and host)?

**Comment by WayneHiller** [comment]
I am using relative URLs like /abs/installations.
Mode is history.

I have a small project where I was testing the vue router lazy loading with pacrcel, I will try it there.

**Comment by c4ss** [comment]
Have the issue described by Wayne above.

Also getting the following error

```
node_modules\vue\dist\vue.runtime.common.dev.js:621 [Vue warn]: $attrs is readonly.

found in

---> <BDropdownItem>
       <Navigation> at src/renderer/components/Navigation.vue
         <App> at src/renderer/App.vue
           <Root>
```

**Comment by tmorehouse** [comment]
@c4ss the second error you are seeing might be due to stale lockfile.  Delete the lockfile and and run `yarn install` or `yarn upgrade` to make sure you have all the correct up-to-date dependencies (you may need to delete `./node_modules/` directory as well).

**Comment by c4ss** [comment]
> @c4ss the second error you are seeing might be due to stale lockfile. Delete the lockfile and and run `yarn install` or `yarn upgrade` to make sure you have all the correct up-to-date dependencies (you may need to delete `./node_modules/` directory as well).

Thanks, just tried this. It still emits the error above, but only on versions >= 2.0.0-rc.17. The error also corresponds with the <b-dropdown-item> issue.

**Comment by WayneHiller** [comment]
>Have the issue described by Wayne above.
Also getting the following error

I am not seeing any errors.

**Comment by tmorehouse** [comment]
There may have been changes to the `b-link` component in RC.17... let me check the history on the file to see if it is not detecting the router properly.  I know it is definitely working when detecting `<nuxt-link>` (which is derived from `<router-link>`), as the docs site uses Nuxt.

**Comment by jaideepdasviadynamics** [comment]
This issue is still there in version `2.0.0-rc.18`. I am using the component like this
```
<b-dropdown-item :to='{name: "Document", params: {id: "xyz"}}'><i class="fa fa-user" aria-hidden="true"></i> Profile</b-dropdown-item>
```

**Comment by jackmu95** [comment]
You have to wait for RC19 for the fix to be available.

**Comment by WayneHiller** [comment]
This is still happening in version 2.0.0-rc.19. Plus I am now getting a number of Errors.

```
vue.runtime.esm.js:619 [Vue warn]: $attrs is readonly.

found in

---> <BNavbarToggle>
       <MainMenu>
         <Root>

[Vue warn]: $listeners is readonly.

found in

---> <BNavbarToggle>
       <MainMenu>
         <Root>
```

**Comment by tmorehouse** [comment]
Are you sure you are on rc.19 and not rc.18?

for the other errors, see the following note in the documentation: https://bootstrap-vue.js.org/docs#using-module-bundlers (and the duplicate issue #3040)

**Comment by WayneHiller** [comment]
Thanks you very much @tmorehouse fixing the bundling issue (vue alias) also seemed to fix this issue, everything is working fine now.

**Comment by msmsimondean** [comment]
I'm using `RC19` and I'm still getting this issue.  I've tried fixing the alias issue and it doesn't seem to have fixed this issue for me.  

I've tried setting the `:to` to both a route path and a route name, and neither approach works.  

# Route Path
``` html
    <b-navbar-nav>
      <b-nav-item-dropdown
          id="nav-tasks"
          text="Tasks"
      >
        <b-dropdown-item :to="/new-task">New Task</b-dropdown-item>
      </b-nav-item-dropdown>
    </b-navbar-nav>
```

# Route Name
``` html
    <b-navbar-nav>
      <b-nav-item-dropdown
          id="nav-tasks"
          text="Tasks"
      >
        <b-dropdown-item :to="'NewTask'">New Task</b-dropdown-item>
      </b-nav-item-dropdown>
    </b-navbar-nav>
```

Would it be possible to re-open the issue or do I need to raise a new issue?  Thanks

**Comment by tmorehouse** [comment]
@msmsimondean Named routes must be passed as a vue-router [`Location Object`](https://router.vuejs.org/api/#to):

```html
<b-dropdown-item :to="{ name: 'NewTask' }">New Task</b-dropdown-item>
```

**Comment by msmsimondean** [comment]
Thanks @tmorehouse.  That's fixed it for me: 

``` html
    <b-navbar-nav>
      <b-nav-item-dropdown
          id="nav-tasks"
          text="Tasks"
      >
        <b-dropdown-item :to="{ name: 'NewTask' }">New Task</b-dropdown-item>
      </b-nav-item-dropdown>
    </b-navbar-nav>
```
