### ISSUE TITLE
Modal makes the page scroll back when closing

### ISSUE THREAD

**Issue by StygianTraveler** [bootstrap-vue/bootstrap-vue#3067]
Since version v2.0.0-rc.17, if you re-use a `<b-modal>` in multiple places on the page, when you close the modal, the page will scroll back to the position it was in when you opened that modal for the first time.

See: https://codepen.io/anon/pen/axpxwq

1. Click the "1" button
2. Close the modal
3. Scroll down the page
4. Click one of the other buttons
5. Close the modal
6. Note that the page scrolls back up to the first button

Tested on Windows on the latest Chrome and Firefox.

**Comment by tmorehouse** [comment]
This might be due to the modal automatically setting the return focus element based on the last active element on the page (and we do not clear that value when the modal is closed, which we should).

**Comment by tmorehouse** [comment]
Will be fixed in the next release.

**Comment by tmorehouse** [comment]
This should be fixed in v2.0.0-rc.19
