### ISSUE TITLE
<b-form-radio-group> fires 2 click events for each button click

### ISSUE THREAD

**Issue by fikkatra** [bootstrap-vue/bootstrap-vue#3088]
When clicking a button in a b-form-radio-group, two click events are fired for each button click. One for the input element, and one for the span containing the label. 

Expected behavior: only one click event should fire.

See fiddle:
https://jsfiddle.net/zpe8v6ub/1/

**Comment by tmorehouse** [comment]
Is the duplicate click event being fired on the group or the individual radios?

**Comment by fikkatra** [comment]
On the individual radios. If you inspect the target of the click events, one of them is the `<input>` and the other is the `<span>` containing the button label.

```
<label class="btn btn-secondary active">
  <input
    type="radio"
    autocomplete="off"
    class
    value="A"
    id="__BVID__2__BV_option_0_"
    name="__BVID__2"
  >
  <span>A</span>
</label>
```

**Comment by tmorehouse** [comment]
Ah, must be an event bubbling issue.

**Comment by fikkatra** [comment]
Don't think so... a bubbling click event is still the same event. This one is a completely separate event. Could it be that the bootstrap-vue code emits a click event (separately from the actual click event executed by the user)?

**Comment by tmorehouse** [comment]
It should override it... but let me check

**Comment by tmorehouse** [comment]
What you are seeing is actually expected behaviour when listening higher up the DOM.

See this fiddle with plain radio input with wrapped labels.  I've added in the event target to the click log
