### ISSUE TITLE
<b-carousel>: multi items carousel 

### ISSUE THREAD

**Issue by maverickpravin** [bootstrap-vue/bootstrap-vue#3097]
**I want to know how can i achieve multi items carousel as shown in the picture with vue-bootstrap carousel ?**
TIA

![multiple-item-product-carousel](https://user-images.githubusercontent.com/11708491/56092557-29952600-5edb-11e9-8cde-fed4513ca737.png)

**Comment by tmorehouse** [comment]
Currently this is not possible with `<b-carousel>`, nor with the carousel in default Boostrap v4.x.

**Comment by maverickpravin** [comment]
@tmorehouse a component like this would be cool. Kindly consider :)

**Comment by tmorehouse** [comment]
It is currently based on the supported features of Bootstrap V4's carousel component, which doesn't have the correct styles/classes to make a slider style carousel (and especially to make it responsively scale/transform the slides to fit different size viewports)

**Comment by tmorehouse** [comment]
I would suggest opening a feature request issue with Bootstrap at https://github.com/twbs/bootstrap.
