### ISSUE TITLE
Lazy formatter is not working when first load

### ISSUE THREAD

**Issue by yudy-chen** [bootstrap-vue/bootstrap-vue#3098]
Hi, I have b-form-input using lazy-formatter. When first loading, the input should apply the formatter. This is used for formatting number.

I was using BV version v2.0.0-rc.11 and Vue version 2.5.17 and it was working properly.
Until today I upgrade BV to version v2.0.0-rc.18 and Vue to version 2.6.10. Suddenly it stop working at first loading. Still the formatter is working when typing / blur.

Here is the codepen https://codepen.io/anon/pen/rbGOpr

**Comment by tmorehouse** [comment]
Lazy formatting, implies after user input has completed, and that if pre-supplied with a value on mount/hide/show/activated/deactivated/reset etc, then the value will have been fixed/formatted before being put in the input.

Just pass your value through your formatter function before assigning it to your freshly mounted input.

**Comment by yudy-chen** [comment]
Ok, it works now. Thanks for the answer.
