### ISSUE TITLE
Tabs component not working?

### ISSUE THREAD

**Issue by MehrCurry** [bootstrap-vue/bootstrap-vue#31]
While playing around with the tabs/tab components i get an exception that the tab could not add themself to the parent component:

VM1167:1Uncaught TypeError: this.$parent.$get is not a function(…)

I copied example from the documentation

**Comment by MehrCurry** [comment]
Ok, i see, the issue has been fixed 4 days ago. Trying to update my version

**Comment by pi0** [comment]
@MehrCurry Thanks for mentioning that, we've just released `0.3.10` please be patient CI is building and publishing new version ;)
