### ISSUE TITLE
b-nav-item-dropdown uses "class" as property

### ISSUE THREAD

**Issue by rdgout** [bootstrap-vue/bootstrap-vue#310]
Hi,

When I run bootstrap-vue (v0.15) I get a warning in my console telling me:

```
[Vue warn]: "class" is a reserved attribute and cannot be used as component prop.

found in

---> <BNavItemDropdown>
       <BNav>
```

And indeed in the code I can see 
https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/nav-item-dropdown.vue

```        
        props: {
            caret: {
                type: Boolean,
                default: true
            },
            class: ['class']
        },
```

However, vue does not like it when this is used, can this be fixed? The warning does not show on production mode but it's still annoying to get it during development.

**Comment by tmorehouse** [comment]
actually I am not sure the `class` prop is even needed after reviewing the code.
