### ISSUE TITLE
<b-form-textarea>: not resizing reactively

### ISSUE THREAD

**Issue by peterjaric** [bootstrap-vue/bootstrap-vue#3103]
When using `rows` and `max-rows` to make a b-form-textarea resize automatically, it does so when typing, but not when updating the model programmatically. 

See this codepen: https://codepen.io/anon/pen/KYXxLY 

When clicking the "Add text" button, the model of the b-form-textarea is updated with a long string, but the textarea isn't resized. If you then type something in the textarea, it resizes correctly.

Some workarounds are available, such as using a key-attribute on the b-form-textarea that is updated on each change, forcing a rerender of the component, or setting a bogus value in the model, and updating it again with this.$nextTick. 

It would be preferable if the component resized itself upon changes in the model, though.

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
Windows 10
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Firefox, Chrome
- Version of BootstrapVue that you are using
2.0.0-rc.18
- Reduced test case
https://codepen.io/anon/pen/KYXxLY 

*Edit*:
I updated the codepen to use the latest version of BootstrapVue (see comment below, https://github.com/bootstrap-vue/bootstrap-vue/issues/3103#issuecomment-483243915)

**Comment by tmorehouse** [comment]
It actually looks for changes in the value to trigger resizing, and not the input event.

So it should be reacting to changes in the v-model value.

Updated code pen to use latest BootstrapVue (it was using an older version, plus had older CSS as well):

https://codepen.io/anon/pen/ROLXVo

**Comment by peterjaric** [comment]
The older version was because I was testing if that was the problem, sorry that I didn't change that back to "latest".

But you also changed `commentLong = commentLong2` into `commentLong += ' ' + comment`.

If I change it back into `commentLong = commentLong2` in your codepen, it stops working again. This is the use case I have. Are you saying that it shouldn't work?

**Comment by tmorehouse** [comment]
It should work....
