### ISSUE TITLE
I'm unable to make <b-spinner> work

### ISSUE THREAD

**Issue by alexbourdon** [bootstrap-vue/bootstrap-vue#3110]
### Describe the bug

every component until now has worked very well, b-spinner does not seem to work in my project. Do I need to update version? Is there a particularity to this component?

### Steps to reproduce the bug

1. Go to [...]
2. Click on [...]
3. Scroll down to [...]

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are
[CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/)
or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.js.org/play) to
_CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
Spinners require Bootstrap V4.3.1 CSS, are you using the latest version of BootstrapVue and Bootstrap? (the information should have be filled in in the issue template above)

**Comment by tmorehouse** [comment]
Without knowing the versions you are using, it is hard to help answer your question.

**Comment by alexbourdon** [comment]
indeed I was not using the latest version of bootstrap-vue. update done. Thanks !!
