### ISSUE TITLE
[question] blur <b-pagination> buttons

### ISSUE THREAD

**Issue by il421** [bootstrap-vue/bootstrap-vue#3113]
I use Bootstrap for Vue in an app for mobile devices with a barcode scanner. I've faced a problem when you paginate table pages, and a btn is pressed (focused). The scanner doesn't work.  

Is it possible to app a prop to disable the focusing?

Thank you

**Comment by tmorehouse** [comment]
Could you provide a sample markup/reproduction/codepen?

Whenever you click a pagination button it will focus (like any other button in a webpage)

**Comment by il421** [comment]
yep, you right, probably I need to listen to the event and blur the exact btn after clicking
