### ISSUE TITLE
<b-modal>: clicking backdrop doesn't close in IE11

### ISSUE THREAD

**Issue by Hiws** [bootstrap-vue/bootstrap-vue#3115]
### Describe the bug

Clicking on the backdrop of a modal in Internet Explorer 11 doesn't close it.
Working correctly in the latest versions of Chrome, Firefox and Edge.

Works correctly in IE11 at https://getbootstrap.com/docs/4.3/components/modal/

### Steps to reproduce the bug

1. Open Internet Explorer 11
2. Go to https://bootstrap-vue.js.org/docs/components/modal/
3. Click on the first 'Launch demo Modal' button
4. Click on the backdrop of the modal.

### Expected behavior

For the modal to close down when clicking the backdrop.

### Versions

- BootstrapVue: 2.0.0-rc.17
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC Desktop
- OS: Windows 10
- Browser: Internet Explorer
- Version: 11.706.17134.0
- Updateversion: 11.0.120

**Comment by jackmu95** [comment]
@Hiws Can you please confirm that #3117 fixes the issue for you:
https://deploy-preview-3117--bootstrap-vue.netlify.com/docs/components/modal

**Comment by Hiws** [comment]
That seems to have fixed the issue.
Appreciate the quick response.

**Comment by tmorehouse** [comment]
This should be fixed in v2.0.0-rc.19
