### ISSUE TITLE
<b-modal> events leaking to parent

### ISSUE THREAD

**Issue by thejcannon** [bootstrap-vue/bootstrap-vue#3119]
I have a clickable div that has a button to launch a modal and the modal itself (both inside the div as they are rendered from a child component). I can use `@click.stop` to launch the modal and have the button click not register on the parent, but any time I click in the modal (or outside to dismiss) the click listener fires for the containing div.

In the following example, clicking anywhere after the modal is opened is incrementing the `clickCount`
```html
<div id="app">
  <modal-tester inline-template>
    <div>
      <b-jumbotron header="Big box" lead="Which is clickable too" @click="clickCount+=1">
        <div>I've been clicked {{ clickCount }} times </div>
        <hr>
        <b-button @click.stop="$refs['modal1'].show()">open modal</b-button>
        <b-modal ref="modal1" title="Mr. Modal">
          <p class="my-4">Hello from modal!</p>
        </b-modal>
      </b-jumbotron>
    </div>
  </modal-tester>
</div>
```
https://codepen.io/anon/pen/rbpjOW

If this a feature of modals (and not a bug), then there should be some guidance in the docs on how to prevent this behavior.

**Comment by tmorehouse** [comment]
What you are seeing it native event browser event bubbling.  Just like clicking on the DIV just above the HR, or the HR itself, that will bubble up to the parent listener.  Since you have paced the modal inside your element (and the modal itself is physically inside there), any click inside it will bubble up.

Change your component to the following markup to move the modal outside:

```html
<div id="app">
  <modal-tester inline-template>
    <div>
      <b-jumbotron header="Big box" lead="Which is clickable too" @click="clickCount+=1">
        <div>I've been clicked {{ clickCount }} times </div>
        <hr>
        <b-button @click.stop="$refs['modal1'].show()">open modal</b-button>
      </b-jumbotron>
      <b-modal ref="modal1" title="Mr. Modal">
        <p class="my-4">Hello from modal!</p>
      </b-modal>
    </div>
  </modal-tester>
</div>
```

**Comment by thejcannon** [comment]
Unfortunately the modal is pretty nested (through several single-file components) underneath the component that has the `@click` so moving it outside the `@click` component isn't really an option.

Are you able to shed any light on why "catching" the click at the modal and stopping the bubbling isn't a valid option? 

In the example the `click` listener on the modal never fires 😞.
```html
<div id="app">
  <modal-tester inline-template>
    <b-jumbotron header="Big box" lead="Which is clickable too" @click="clickCount+=1">
      <div>I've been clicked {{ clickCount }} times </div>
      <hr>
      <b-button @click.stop="$refs['modal1'].show()">open modal</b-button>
      <b-modal @click.stop="modalClick+= 1" ref="modal1" title="Mr. Modal">
        <p class="my-4">Hello from modal! {{ modalClick }}</p>
      </b-modal>
    </b-jumbotron>
  </modal-tester>
</div>
```
https://codepen.io/anon/pen/NmXpoy

**Comment by tmorehouse** [comment]
People may actually want to use event delegation higher up on the document tree (i.e. if htey are using other plugins that require it).

what you are seeing is expected browser event handling behavior.

Modal has a backdrop click listener that traps click events on the modal wrapper (the click listener looks for specific element clicks and stops propegation on those events)... But other click events can bubble up through.

For modal, you are not telling it to listen to native click events (it is a component which emits custom events, not an element which emits native events).

```html
      <b-modal @click.native.stop="modalClick+= 1" ref="modal1" title="Mr. Modal">
        <p class="my-4">Hello from modal! {{ modalClick }}</p>
      </b-modal>
```

**Comment by thejcannon** [comment]
Ahh! The `native` modifier was what I was missing. (It isn't on Vue "events" [page](https://vuejs.org/v2/guide/events.html), it's later in the "custom events" [page](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components))

Thanks!
