### ISSUE TITLE
<b-modal> @change event not triggering if the modal visible closed immediately

### ISSUE THREAD

**Issue by chenxeed** [bootstrap-vue/bootstrap-vue#3126]
### Describe the bug

There is a changed behavior in `<b-modal>` after the release of `v2.0.0-rc.12` and perhaps specifically because of [this PR](https://github.com/bootstrap-vue/bootstrap-vue/pull/2270/files#diff-2f6544a135bbefb71664d04f6e67d3d0R555).

When we need to directly hide the modal on `@change` event, it was working before. For example:

(note: You can try this script on the [modal example](https://bootstrap-vue.netlify.com/docs/components/moda)

```
<template>
  <div>
    <b-button @click="modalShow = true">Open Modal {{modalShow}}</b-button>
    <b-modal :visible="modalShow" @change="modalShow = false">Hello From Modal!</b-modal>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        modalShow: false
      }
    }
  }
</script>
```

On first click the button, it will set the `modalShow` to `true` and directly back to `false`. On the second click and next after, it will set `modalShow` to `true` and never set back to `false` anymore.

By right, the `modalShow` should always be `false` whenever we click the button, because when the modal show and `@change` event triggered, it will directly set to `false`. This is working back in `v2.0.0-rc.11` before.

I found out the culprit is because on the 2nd click, the flag `is_closing` is still true therefore it prevents the show function from running further.

![Screen Shot 2019-04-17 at 2 47 57 PM](https://user-images.githubusercontent.com/3530355/56266883-df50b680-611f-11e9-8dda-794824f0f255.png)

### Steps to reproduce the bug

1. Copy paste the script I add above to the modal example
2. Click the "Open Modal" button.
3. On first click, the `showModal` flag will be set back to `false`
4. On second click, the `showModal` will be set to `true` and never be `false` anymore.

### Expected behavior

The flag `showModal` should be back to `false`, as the `@change` event should be triggered.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.12
- Bootstrap: 4.3.1
- Vue: 2.6.0

**Environment:**

- Device: Mac
- OS: MacOS
- Browser: Chrome
- Version: 73

### Demo link

Try the script pasted above in the [bootstrap vue website modal example](https://bootstrap-vue.netlify.com/docs/components/modal)

**Comment by tmorehouse** [comment]
It should be scheduling a new show() event once it receives a `hidden` event.

The `change` event is meant for updating the `v-model`, and not really for triggering any other events.

Is there any reason (or specific use case) you are using it over one of the other events such as `hide`/`hidden`/`show`/`shown`?

**Comment by tmorehouse** [comment]
You can a also place your setting of the v-model in a $nextTick on change to allow Vue time to update its reactive data.

```html
   <b-modal :visible="modalShow" @change="prevent">Hello From Modal!</b-modal>
```
```js
methods: {
  prevent() {
    this.$nextTick(() => {
      modalShow = false
    })
  }
}
```

**Comment by tmorehouse** [comment]
But you should really be doing this:

```html
   <b-modal :visible="modalShow" @show="preventShow">Hello From Modal!</b-modal>
```
```js
methods: {
  preventShow(bvModalevt) {
    bvModalEvt.preventDefault()
  }
}
```

**Comment by chenxeed** [comment]
@tmorehouse thank you for the thoughts!

I would agree and follow your suggestion that in `@change` event we should only handle the `v-model` event.

As for your suggestion above, I tried this script on the bootstrap-vue example:

```vue
<template>
  <div>
    <b-button @click="modalShow = true">Open Modal {{modalShow}}</b-button>

    <b-modal :visible="modalShow" @show="onShow">Hello From Modal!</b-modal>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        modalShow: false
      }
    },
    methods: {
      onShow(bvModalevt) {
        bvModalEvt.preventDefault()
      }
    }
  }
</script>
```

The `onShow` event doesn't stop the modal from appearing. Is this the expected output?

**Comment by tmorehouse** [comment]
There is a typo in your event handler... try this:

```js
    methods: {
      onShow(bvModalEvt) { // <-- make sure this variable name matches the one below
        bvModalEvt.preventDefault()
      }
    }
```

**Comment by chenxeed** [comment]
Oops my bad, thanks for the correction and fast response @tmorehouse .

Following up with this example, the prevention is working but the flag `modalShow` is still set to `true`  therefore the flag is invalid now because the modal is not showing but the `visible` flag is `true`.

**Comment by tmorehouse** [comment]
You still need to make visible a v-model so that it will update with the change event:

```html
<b-modal v-model="modalShow" @show="onShow">Hello From Modal!</b-modal>
```

**Comment by chenxeed** [comment]
@tmorehouse yes I have updated the code by using the `v-model`, and pasted it to the bootstrap-vue example:

```vue
<template>
  <div>
    <b-button @click="modalShow = true">Open Modal {{modalShow}}</b-button>

    <b-modal v-model="modalShow" @show="onShow">Hello From Modal!</b-modal>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        modalShow: false
      }
    },
    methods: {
      onShow(bvModalEvt) {
        bvModalEvt.preventDefault()
      }
    }
  }
</script>
```

As I've tested it, the flag is still not toggle back to `false` on prevent. IMO, perhaps preventing the modal to open on `@show` is not a really good idea. What do you think? @tmorehouse 

<img src="https://gyazo.com/686e1499463e09fb869b5575b8891371.gif">

**Comment by tmorehouse** [comment]
Hmmm we might not be resetting the v-model on prevent.

The best way to prevent the button from opening the modal would be to disable the button.
