### ISSUE TITLE
<b-form-file> with VeeValidate causes an files.every function error

### ISSUE THREAD

**Issue by wecler** [bootstrap-vue/bootstrap-vue#3128]
Hello everybody.

Today while working on a form I have noticed an unexpected behaviour between Bootstrap-Vue and VeeValidate. This behaviour can be seen at the link below.

https://jsfiddle.net/wecler/4p3of9sb/

After choosing the file there appears an error **files.every is not a function** in the console.

I could reproduce it on jsfiddle as on my local project. What should be mentioned that when using default html <input> and not <b-form-file> the error does not appear.

Greetings, wecler.

**Comment by SzymonLisowiec** [comment]
PR with single file support: https://github.com/baianat/vee-validate/pull/2031
Temporary solution: https://jsfiddle.net/5bvxp1rz/
