### ISSUE TITLE
TypeError in Tooltip when the slot content isn't an element

### ISSUE THREAD

**Issue by KuroThing** [bootstrap-vue/bootstrap-vue#313]
The error as per chrome: `TypeError: Cannot read property 'addEventListener' of undefined`
The error as per firefox: `TypeError: e._trigger is undefined`

A [jsfiddle](https://jsfiddle.net/1q7bp6v9/) that reproduces the error, just check your browsers console after running the example.

From what i can gather, it appears the problem stems from the fact that [`this._trigger`](https://github.com/bootstrap-vue/bootstrap-vue/blob/72a03bf1eebea79dd0c9a090b8b1bb8733b665ba/lib/components/popover.vue#L425) assumes that the child is a html element, and it continues until [`addListener`](https://github.com/bootstrap-vue/bootstrap-vue/blob/72a03bf1eebea79dd0c9a090b8b1bb8733b665ba/lib/components/popover.vue#L412) is called, which will then throw an error.

If this is the intended behaviour, could this please be documented somewhere on at least Tooltip, and also Popover if it is also impacted by this along with a sanity check to see if the child is a html element and a custom error being thrown with an improved error message that clearly indicates the problem.

**Comment by pi0** [comment]
@KuroThing In next release it is possible without wrapping inside `<span>`  : 
`<b-tooltip content="Foo">Bar Baz</b-tooltip>`
