### ISSUE TITLE
Checkbox switch mode issue

### ISSUE THREAD

**Issue by Joris-Fonck** [bootstrap-vue/bootstrap-vue#3132]
Checkbox switch mode not work in the latest version (2.0.0-rc.18).

Example of code : https://jsfiddle.net/urw6894v/

**Comment by ztomaz** [comment]
you have not imported bootstrap.min.css correctly.
Try with:
https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css

**Comment by Joris-Fonck** [comment]
Oh, thank you !
