### ISSUE TITLE
<b-table> mark rows as unselectable

### ISSUE THREAD

**Issue by thejcannon** [bootstrap-vue/bootstrap-vue#3134]
In my application the table serves both to display data and allow the "owner" of the data to the change the state of the rows by selecting them and then clicking a button. However some rows are in a state which allowing them to be changed doesn't make sense.

It would be great if the row object could specify a `_selectable` boolean (like `_showDetails`) which enable/disable the ability to select the row. (If the row is in a range being selected, it is just omitted from the range).

You'd also have to decide how to handle the row being clicked with `range` mode (do nothing? select all the rows up to but not including the row?).

I'm sure there's a workaround where I listen for clicks and then conditionally deselect the row immediately, so consider this low priority.

I also understand if this is too niche to justify the complexity.

**Comment by thejcannon** [comment]
In my fork, I do this by supporting  `_selectable` as a valid property of each item.
See 1c8e3f63df9f2d7842ea393754803fa0ca5f5d91.

Note: Haven't added unit tests to test this 😢

**Comment by tmorehouse** [comment]
One could watch for the row-selected event, scan the selected results, and then use the new programmatic features of 2.0.0-rc.28 to deselect the row that shoudn't be selected.

**Comment by tmorehouse** [comment]
This is definitely a niche requirement, which also poses questions on how does one notify the user that a row is not selectable when all others may be, and could pose issues with screen reader users, etc.

Marking as out-of-scope for now.

**Comment by sandrovw64** [comment]
For those who needs a disabled row in a `<b-table>`, here is my implementation:

```html
<b-table ref="table"
              :fields="table.fields"
              hover
              :items="items"
              select-mode="multi"
              selectable
              thead-class="d-none"
              @row-selected="onRowSelected">
```

```js
...
computed: {
    items() {
      var items = [];
      if (this.list.items.length > 0) {
        items = Object.assign([], this.list.items);
        items.forEach((item) => {
          if (this.getDisabled(item)) {
            item = this.setRowVariant(item);
          }
        });
      }
      return items;
    },
...
methods: {
    onRowSelected(items) {
      var selected = [];
      items.forEach((element, index) => {
        if (this.getDisabled(element)) {
            this.$refs.table.unselectRow(index);
        } else {
          selected.push(element);
        }
      });
      this.selected = selected;
    },
    setRowVariant(item) {
      return (item._rowVariant = "row-disabled");
    },
}
...
```

And then, in my custom `table.scss` file I added

```css
.table-hover .table-row-disabled:hover {
  background-color: var(--gray-2);
  cursor: not-allowed !important; 
}
```

Notice the `.table-hover` class. My b-table is set to hover. If yours is not, then just use `.table`

**Comment by siddiqian-developer** [comment]
I did a very short solution based on @sandrovw64 's solution above.

After adding the _rowVariant, which will appear as a class in each <tr> which is to be unselectable, make it unselectable in CSS as following:

  .table-row-disabled {
    pointer-events: none !important;
  }
