### ISSUE TITLE
<b-table>: add `table-class` as a new prop

### ISSUE THREAD

**Issue by tradingstratagem** [bootstrap-vue/bootstrap-vue#3138]
Hi,
I need to add a custom class to the table element, but there's no option to do this.
Can you please add a prop in order to add additional classes to the table tag?

Thank you.

**Comment by tmorehouse** [comment]
Just add `class="my-class"` to the  `<b-table>` component.

**Comment by tradingstratagem** [comment]
No, it doesn't work, because a div is the root element of `<b-table>` as you can see in the screenshot.

`<b-table bordered striped responsive class="text-nowrap card-tablclass="text-nowrap card-table">`

<img width="818" alt="Screenshot 2019-04-20 at 07 39 15" src="https://user-images.githubusercontent.com/38089167/56448147-747dc600-633f-11e9-8963-9f7a78803a21.png">

**Comment by tmorehouse** [comment]
Ah.. when not responsive it gets applied to the table.

**Comment by tradingstratagem** [comment]
so... is it a bug?

**Comment by tmorehouse** [comment]
I wouldn't call it a bug. It is more of an expected behaviour of Vue to place all attributes that aren't props to the root element of a component. In this case the root element can change from one type of element to another, depending on settings.

**Comment by tradingstratagem** [comment]
ok, are you going to find a solution for this?

**Comment by tmorehouse** [comment]
We will, but not right now as we are all away for the long weekend vacation.

**Comment by tradingstratagem** [comment]
Sure, not a big deal. Thank you!
