### ISSUE TITLE
Compability issue with Vue 2.3.0

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#314]
Got updated deps in my project and catch a bug:

 opening a DropDown 

> bootstrap-vue.esm.js:formatted:1 Uncaught TypeError: t[0].focus is not a function
>     at VueComponent.toggle (bootstrap-vue.esm.js:formatted:1)
>     at Proxy.boundFn (bootstrap-vue.esm.js:formatted:1)
>     at click (bootstrap-vue.esm.js:formatted:1)
>     at HTMLAnchorElement.invoker (bootstrap-vue.esm.js:formatted:1)

Error-causing code: not located yet.

**Comment by mosinve** [comment]
rechecked with git version - all ok. Issue with current release only.

**Comment by meta0102** [comment]
i've the same problem but i'm using  vue@2.2.6

**Comment by mosinve** [comment]
This fixed by #327

**Comment by pi0** [comment]
Thanks @mosinve for inspection. Will make a new release soon :)
