### ISSUE TITLE
Highlight is appeared when I press on <b-tab> area. How to remove it?

### ISSUE THREAD

**Issue by dblinov** [bootstrap-vue/bootstrap-vue#3146]
### Describe the bug

Highlight is appeared when I press on <b-tab> area.

### Steps to reproduce the bug

It is by default ...

### Expected behaviour

No highlight around the <b-tab> area.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.18
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: Mac OS 10.14.4
- Browser: Chrome
- Version: 73.0.3683.103

**Comment by tmorehouse** [comment]
If you are referring to the focus ring that appears when tabbing into the tabs.. that is there for accesibility reasons.

**Comment by tmorehouse** [comment]
Tabs are meant to be (and act like) a widget as described in the WAI ARIA best practices examples.

If you don't want this focus ring... you can build a simple tabs interface using b-card, and b-nav.
