### ISSUE TITLE
Form-file bug on Edge 14

### ISSUE THREAD

**Issue by hvalcourtSerdy** [bootstrap-vue/bootstrap-vue#315]
Hi, yesterday our QA tested the bootstrap-vue components on https://bootstrap-vue.github.io/docs (we want to see if we will use bootstrap-vue).

We share the result with you in fews ticket, hope this will help you for your developpement.

a) Go to https://bootstrap-vue.github.io/docs/components/form-file on Edge (Windows 8.1 - Edge 14)
b) Select a file.
c) Bug : The windows always re-open when we click the "X", or "Cancel". The QA had to close Edge with ctrl-alt-delete.
d) Screenshot: 
![2_edge14](https://cloud.githubusercontent.com/assets/25179767/25619067/8363be76-2f17-11e7-9364-d1c65cd7660b.png)

**Comment by pi0** [comment]
#322

**Comment by hvalcourtSerdy** [comment]
Hi, this one is on Edge, not on android webview

**Comment by pi0** [comment]
@hvalcourtSerdy Do you confirm that this one works correctly with pure bootstrap file inputs?

**Comment by hvalcourtSerdy** [comment]
Edge is a supported browser for bootstrap 4 : https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#desktop-browsers

And the problem is not in Bootstrap wall of browser bug here : http://getbootstrap.com/browser-bugs/

The problem is this one :
"When using a <input type="file"> inside a <label> on MS Edge, the file explorer window keeps reopening. When this happens, the only way to close Edge is by killing the process."
as in https://github.com/facebook/react/issues/7683

And this one : https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8282613/

In the source code here, https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/form-file.vue , the input is inside label

**Comment by tmorehouse** [comment]
This issue should e fixed in the next release.  the `label` wrapper has been changed to a `div`

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
