### ISSUE TITLE
Checkbox click closes dropdown

### ISSUE THREAD

**Issue by mikkelbfriis** [bootstrap-vue/bootstrap-vue#3152]
### Describe the bug
When you put a form element (input, textarea, checkbox to be specfic in my case) in a dropdown-item class, and click the checkbox, the dropdown'll close.

### Steps to reproduce the bug
1. Click on dropdown
2. Click on checkbox
3. Dropdown closes.

### Expected behavior
The dropdown to not close.

### Versions

**Libraries:**

- BootstrapVue: v2.0.0-rc.19
- Bootstrap: 4.2.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Mozilla Firefox
- Version: 66.0.3

### Exact code that I'm using
```
<b-dropdown id="dropdown-form" text="Dropdown with form" ref="dropdown">
    <b-dropdown-item>
        <b-form-checkbox>Remember me</b-form-checkbox>
    </b-dropdown-item>
</b-dropdown>
```

**Comment by jackmu95** [comment]
Please see the dropdown with a form example in the docs:
https://bootstrap-vue.js.org/docs/components/dropdown#b-dropdown-form

**Comment by mikkelbfriis** [comment]
This is without <b-dropdown-item>, which renders the example unusable to me.

**Comment by tmorehouse** [comment]
`b-dropdown-item` automatically closes the dropdown when clicked, regardless of content (it renders a anchor wrapper elements `<a>` tag).  Place the `b-form-checkbox` inside a `b-form-dropdown-form` container element instead.

**Comment by tmorehouse** [comment]
```html
<b-dropdown id="dropdown-form" text="Dropdown with form" ref="dropdown">
    <b-dropdown-form>
        <b-form-checkbox>Remember me</b-form-checkbox>
    </b-dropdown-form>
</b-dropdown>
```

**Comment by mikkelbfriis** [comment]
but then it isn't bootstrap anymore, this seems more like a hotfix than a proper fix @tmorehouse

**Comment by tmorehouse** [comment]
@mikkelbfriis I'm not sure how you come to that conclusion, as even in the bootstrap documentation for dropdowns, the show forms **not inside an element with class `"dropdown-item"`**

See the Bootstrap V4.3 docs at https://getbootstrap.com/docs/4.3/components/dropdowns/#forms

`b-dropdown-item-form` builds a form wrapper just like their examples.

**Comment by mikkelbfriis** [comment]
Shit my bad, move on
