### ISSUE TITLE
Toasts do not appear in search

### ISSUE THREAD

**Issue by patrickblackjr** [bootstrap-vue/bootstrap-vue#3159]
### Describe the bug

Toasts do not appear when searching the docs.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs
2. Type "toast" into the search bar
3. See no results

**Comment by patrickblackjr** [comment]
This is obviously low priority, and maybe even intentional since toasts are in beta.

**Comment by tmorehouse** [comment]
It takes up 24 hours for Algolia Search to re-index the site, and as we just published the new release 15 hours ago  they should appear in search later today (in about 9 hours).

**Comment by patrickblackjr** [comment]
Got it! Thanks!

**Comment by tmorehouse** [comment]
@patrickblackjr Toasts should now be appearing in the docs search.
