### ISSUE TITLE
jsfiddle problem on IE11

### ISSUE THREAD

**Issue by hvalcourtSerdy** [bootstrap-vue/bootstrap-vue#316]
Hi, yesterday our QA tested the bootstrap-vue components on https://bootstrap-vue.github.io/docs (we want to see if we will use bootstrap-vue).

We share the result with you in fews ticket, hope this will help you for your developpement.

This one, the QA blame JSFiidle, I was not able to verify this, I dont have IE11.

a) Go to https://bootstrap-vue.github.io/docs/ on Internet Explorer 11
b) JSFiddle dont load correctly, so the other element of the page dont load
c) Screenshot: 
![3_internetexplorer11](https://cloud.githubusercontent.com/assets/25179767/25619242/2251e92c-2f18-11e7-8e2c-ac8d1b182adc.jpg)

**Comment by pi0** [comment]
It may be problem with lack of IE 11 polyfills we can add them to docs bundle so that it would work better on IE. 
/cc @dev team about this.

**Comment by tmorehouse** [comment]
@hvalcourtSerdy Are you still seeing these issues using the latest release v0.17.2?

**Comment by tmorehouse** [comment]
This is definitely an issue with IE 11, as after reviewing the MDN docs for various object prototypes and methods, IE 11 is severely lacking in many of them (i.e. Object..assign being a major one).

One option might be to suggest the ES6.js polyfills when targetting I 11 users.

**Comment by tmorehouse** [comment]
PR #658 may address this issue by providing some helper functions for missing methods in IE 11
