### ISSUE TITLE
v-select unable to set id as value and name as text

### ISSUE THREAD

**Issue by hassanshuja** [bootstrap-vue/bootstrap-vue#3161]
<v-select
                        id="user"
                        name="user"
                        @search-change="getusers"
                        :options="userList"
                        v-model="userList.id"
                        required
                        autocomplete="on"
                    ></v-select>
in this I am getting an object in userLIst how can i set userList.id as value and userList.name as text to show to users.

**Comment by tmorehouse** [comment]
`v-select` is not a BootstrapVue component. `b-select` is though.

**Comment by hassanshuja** [comment]
How can we make b-select searchable

**Comment by tmorehouse** [comment]
`b-select` is just a native browser `<select>` element that has Bootstrap V4.x styles applied to it.
