### ISSUE TITLE
How to make <b-form-select> searchable

### ISSUE THREAD

**Issue by hassanshuja** [bootstrap-vue/bootstrap-vue#3162]
I want a select box with search functionality , is it available in b-select or in b-form-select

**Comment by tmorehouse** [comment]
`b-form-select` (which is also known as `b-select`, is just a regular native browser `<select>` element that has Bootstrap V4.x styles applied to it.

You will need to find a 3rd party custom select element/component or build one yourself.

**Comment by suguoyao** [comment]
Are there any 3rd party plugins available? Thanks

**Comment by xoctopus** [comment]
Hi @tmorehouse , do we have any progress on this? Maybe some independent component?
