### ISSUE TITLE
v-b-toggle isn't properly reactive

### ISSUE THREAD

**Issue by Mach12** [bootstrap-vue/bootstrap-vue#3165]
### Describe the bug

Changing the value given to v-b-toggle dynamically does not have the intended effect.
Granted, that's quite the edge case, but I believe it would make sense to react if this property changes.

### Steps to reproduce the bug

1. Create a first element (e.g a button) with a dynamic `v-b-toggle` value
4. Create several `b-collapse` elements (one of which is pointed at by the button)
5. Change the value inside the `v-b-toggle`
6. Toggling button will still toggle the first `b-collapse` it was pointed at

### Expected behavior

Changing the `v-b-toggle` dynamically should let one retarget a button, making it collapse/expand whichever `b-collapse` one sees fit even if it changes.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc19
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Desktop
- OS: Ubuntu Bionic
- Browser: Chrome
- Version: 73.0.3683.103

### Demo link

[Here's a codepen](https://codepen.io/Pixelmod/pen/wZEevW) where `v-b-toggle` changes periodically but doesn't affect behavior beyond initial value.

**Comment by jackmu95** [comment]
@Mach12 I've created a simple demo and can't reproduce your behavior.
Can you create s similar one to show your problem.

https://codesandbox.io/s/nkq6pz5144

**Comment by Mach12** [comment]
@jackmu95 You were showing the wrong variables in your collapses.

See [my fork](https://codesandbox.io/s/pj7vxkqo80) of your demo. The button cycles but always expands block #1.

**Comment by jackmu95** [comment]
@Mach12 Yeah, using the global index variable in my demo made the issue not visible.
