### ISSUE TITLE
Setting custom <b-toast> defaults

### ISSUE THREAD

**Issue by EPinci** [bootstrap-vue/bootstrap-vue#3169]
### Is your feature request related to a problem? Please describe...

When using toats on demand (using the ```this.$bvToast.toast()```), I always use my same custom behavior that is different from the defaults (such as position, title , duration...) but currently there's no way to set them initially and I have to re-set them in every call.

### Describe the solution you'd like

I would like to be able to make a call in my application loading code in order to set my deaults.

### Describe alternatives you've considered

If this is actually possible, I haven't found it in the documentation page.

### Additional context

This toast are soooo cool! :)

**Comment by tmorehouse** [comment]
We are planing on adding additional toast config values/defaults in the new config setting for BootstrapVue (https://bootstrap-vue.js.org/docs/misc/settings#default-configuration).  `b-toast` and `this.$bvToast.toast()` will be use the config settings.  Currently only the default toaster target is configurable.

**Comment by tmorehouse** [comment]
Note `title` will never be able to have a default value (other than `null`)

**Comment by ngockhanhbl** [comment]
how can i fire toast when i click register button.
if success fire toast.else no fire
tks u

**Comment by soichih** [comment]
How can I set default configuration for `this.$bvToast.toast`? I want to make all bvToast.toast() to close in 5 seconds. I tried this but it didn't work..

```
Vue.use(BootstrapVue, {
    bvToast: {
        title: "Alert",
        autoHideDelay: 1000, 
    }
});
```

**Comment by tazimmadre-saharsh** [comment]
i need the same @soichih , were you able to solve it ?
