### ISSUE TITLE
Select <b-table> row with function?

### ISSUE THREAD

**Issue by travis5491811** [bootstrap-vue/bootstrap-vue#3171]
Hello. I'm using the table selected like this

```
<template>
  <div>
    <b-table
      selectable
      select-mode="single"
      :items="items"
      @row-selected="rowSelected"
    ></b-table>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        items: [
          { isActive: true, age: 40, first_name: 'Dickerson', last_name: 'Macdonald' },
          { isActive: false, age: 21, first_name: 'Larsen', last_name: 'Shaw' },
        ],
      }
    },
    methods: {
      rowSelected(items) {
      }
    }
  }
</script>
```

But in my table I have a custom slot with a clickable button inside it. When clicked, it opens something in sidemenu. if a user clicks that button, the row isn't selected.

I can capture the "row" element but `row.rowSelected = true;` doesn't work. If I refer to `this` but `this` is everything and i'm not sure how to find the way to set the row to selected.

The following makes me think i can't use the `rowSelected = true` for this 

> When a table is selectable and the user clicks on a row, <b-table> will emit the row-selected event, passing a single argument which is the complete list of selected items. Treat this argument as read-only.

Is there a `this.$refs.table1.something.selected = true` or a `this.$something.asasf.selected = true;` i can use to set the row as selected?

**Comment by tmorehouse** [comment]
Any interactive non-disabled component/element inside a rendered row will not trigger a `row-selected`, `row-clicked` (or other `row-*` events).

**Comment by tmorehouse** [comment]
Your best bet is to make sure each row record item data includes a unique primary key column, and set the `primary-key` prop to this item key.  You can then use the primary key to find the row element (`<tr>`) in the table and emit a click event on that element.

The row will have an ID attribute assigned to it, based on the table's ID and the primary key's value.

**Comment by travis5491811** [comment]
@tmorehouse thanks. I added the `primary-key` like suggested and made it the `_id` of the the record

```
            <b-table
              ref="table1"
              selectable
              select-mode="single"
              @row-selected="rowSelected"
              primary-key="_id"     
            >
```

Then dispatched the click event after find by id
```JAVASCRIPT
      document
        .getElementById(`__BVID__73__row_${task.row.item._id}`)
        .dispatchEvent(new MouseEvent("click", { ctrlKey: false }));
```

This part `__BVID__73__row_` has me a little concerned. I found it looking through chrome dev tools. It's working now but seems like it could change anytime. I don't know where `73` came from. Is there a better way?

**Comment by tmorehouse** [comment]
That is the auto-generated ID (which will/can change), which means you haven't set the b-table's `id` prop

**Comment by snehansh** [comment]
@travis5491811 i have a similar problem. how were you able to get the selected row. what is task.row in your comment above.
