### ISSUE TITLE
<b-table> virtual column sort not working

### ISSUE THREAD

**Issue by Jerome1337** [bootstrap-vue/bootstrap-vue#3178]
### Describe the bug

I have created a virtual column and the sorting system is not working well, the sort just invert column data display (first become last and last become first)

### Expected behavior

The virtual column should be sorting values alphabetically.

### Versions

**Libraries:**

- BootstrapVue: 2..0.0-rc.19
- Bootstrap: 4.3.1
- Vue: 2.6.6

**Environment:**

- Device: iMac 27 inch
- OS: Arch linux core
- Browser: Firefox
- Version: 66.0.2

### Additional context

Here is some code I use to create my slot

```
<template
  slot="source"
  slot-scope="data"
>
  <p v-if="data.item.source.name === 'nmail'">
    N-Mail
  </p>
  <a
     v-else
     :href="hostingLink(data.item.source.slug)"
   >
     {{ data.item.source.name }}
  </a>
</template>
```

My fields definition

```
fields: [
  {
    key: 'email',
    label: this.$t('columnTitle.mailbox'),
  },
  {
    key: 'size',
    label: this.$t('columnTitle.size'),
  },
  {
    key: 'source',
    label: this.$t('columnTitle.source'),
  },
],
```

The virtual column with desc sorting

![image](https://user-images.githubusercontent.com/7968649/56648498-bed6ae00-6683-11e9-84db-204bca7c5138.png)

The same column with the asc sorting

![image](https://user-images.githubusercontent.com/7968649/56648576-e2015d80-6683-11e9-9ca4-2058cc47c9ab.png)

**Comment by tmorehouse** [comment]
As mentioned in the docs, it is not possible for the internal sort routine to sort by virtual columns.  you will need to create your own sort compare routine that handles the virtual column.

> **Note:** The built-in sort-compare routine cannot sort virtual columns, nor sort based on the custom rendering of the field data (formatter functions and/or scoped slots are used only for presentation only, and do not affect the underlying data). Refer to the Sort-compare routine section below for details on sorting by presentational data.

https://bootstrap-vue.js.org/docs/components/table#sort-compare-routine

**Comment by Jerome1337** [comment]
@tmorehouse Ah my bad I didn't see this note :smile: Thanks for your answer

**Comment by soullivaneuh** [comment]
@tmorehouse Even if it's not a bug, it's a lack to me.

Would you be interested to a PR providing sorting on virtual columns?

Regards

**Comment by BigShanJohn** [comment]
I created my sortCompare function but it bringing undefined error while clicking on virtual columns

```vue
sortCompare: function(a, b, key) {
            if (typeof a[key] === 'number' && typeof b[key] === 'number') {
                return a[key] < b[key] ? -1 : a[key] > b[key] ? 1 : 0;
            } else {
                return a[key].toString().localeCompare(b[key].toString());
            }
        },
```

**Comment by tmorehouse** [comment]
@BigShanJohn since the columns are virtual, they do not exist in the `a` and `b` items references. you must generate the formatted values for the virtual column key and then compare the formatted values.
