### ISSUE TITLE
Toasts not inheriting variants from base theme

### ISSUE THREAD

**Issue by EPinci** [bootstrap-vue/bootstrap-vue#3184]
### Describe the bug

I'm running a site with a custom bootstrap theme ([this](https://bootswatch.com/flatly)).
It is not clear to me if bvToasts should be able to "inherit" the variant color definitions of a custom theme. Looking at the _toast.scss seems to me that the bvToast classes should inherit from alerts mixins but, when I actually used. 

### Steps to reproduce the bug

1. Pick a basic bootstrap site and replace the boostrap.css with a custom one (in my case, see link above)
2. Put an info alert on a page and an info toast
3. Notice that the hue of the alert is a different one from the toast (not just different lightness, but different "blue")

### Expected behavior

Am I correct in expecting the toast to pickup the same variant colors?

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc19
- Bootstrap: 4.1.3
- Vue: 2.6.10

**Environment:**

- Device: Desktop PC
- OS: Windows 10
- Browser: Edge, Chrome

### Demo link

Trying to build one...

**Comment by tmorehouse** [comment]
BootstrapVue can't pick up custom variants if using a standard CSS file. you need to use SCSS overrides for customization.

See https://deploy-preview-3183--bootstrap-vue.netlify.com/docs/reference/theming on how to use SCSS overrides

**Comment by EPinci** [comment]
Yeah, apologies, I am actually using a few SCSS files (from the theme and mines), not a straight CSS: nothing fancy, just overridden the standard variants and a few unrelated custom classes.

What I can see is that alerts, navbars and other stuff get my custom colors fine but toasts do not.

I'm trying to build a demo link, with codesandbox but I'm new to that (...and not that only...). ;)

(man, you are... fast... in answering! :)

**Comment by tmorehouse** [comment]
You need to make sure you are including all the SCSS files and overrides in a single SCSS file which is then imported into your app.  They can't be imported separately, as the variables will not be passed between files.

Create a custom SCSS file (i.e. custom.scss):
```scss
// Your variable overrides go here, e.g.:
// $h1-font-size: 3rem;

// Import Bootswatch theme variables SCSS
@import "~bootswatch/dist/flatly/variables";
// Import bootstrap source SCSS
@import "~bootstrap/scss/bootstrap";
// Import the other Bootswwatch stuff
@import "~bootswatch/dist/flatly/bootswatch";

// Then import BootstrapVue SCSS source
@import "~bootstrap-vue/src/index.scss";
```

An then in the root of your app:
```js
import 'path/to/custom.scss'
```

This assumes your have [sass-loader](https://github.com/webpack-contrib/sass-loader) in your webpack config so that it knows how to import SCSS files into your app.

**Comment by EPinci** [comment]
I should be good with that (although I importing the last one from the main after that SCSS...?).

I got the code sandbox working at https://codesandbox.io/s/qlr89xq0jj

**Comment by EPinci** [comment]
Oh! I got it. :)

I had my custom.scss without the final ```include "~bootstrap-vue/src/index"``` because I got from an initial sample this in my main.js:
```
import "./bootstrap.scss";
import "bootstrap-vue/dist/bootstrap-vue.css";
```
And the end result was that the toast specific definition where coming from the dist file, itself coming from the default bootstrap (not my custom built one).
Now the hue are matching... :)

Thank you! :D
