### ISSUE TITLE
form-file bug on android webview 4.4

### ISSUE THREAD

**Issue by hvalcourtSerdy** [bootstrap-vue/bootstrap-vue#319]
Hi, yesterday our QA tested the bootstrap-vue components on https://bootstrap-vue.github.io/docs (we want to see if we will use bootstrap-vue).

We share the result with you in fews ticket, hope this will help you for your developpement.

a) Go to https://bootstrap-vue.github.io/docs/components/form-file on Webview Android 4.4 (use application WebView Tester http://bit.ly/2qlN8t7)
b) No field are visible
c) Screenshot: 
![6_android_webview](https://cloud.githubusercontent.com/assets/25179767/25619597/7935a9c6-2f19-11e7-9519-87e0cdcd5d61.png)

**Comment by tmorehouse** [comment]
This is most likely a problem with Bootstrap 4 incompatibility itself. See #322.
