### ISSUE TITLE
Switch to using Open Collective postinstall package

### ISSUE THREAD

**Issue by moltar** [bootstrap-vue/bootstrap-vue#3191]
### Is your feature request related to a problem? Please describe...

Right now there is no way to opt out from Open Collective messages. This pollutes CI pipelines with long and undesirable output.

### Describe the solution you'd like

[Open Collective postinstall](https://github.com/opencollective/opencollective-postinstall) script is a light version of `opencollective-cli` that only handles `postinstall`.

The reason it is better to use that:

1. It is more lightweight on the install
1. It provides ability to opt out from messages in CI and via `DISABLE_OPENCOLLECTIVE` header.

### Describe alternatives you've considered

N/A

### Additional context

Message that is output:

```
> bootstrap-vue@2.0.0-rc.15 postinstall /app/node_modules/bootstrap-vue
> opencollective || exit 0


                     .,,,,,,,:;;;;;;:        :;;;;;;:,,,,,,,.
                      ,;;;;;;;siiiiii;      ;iiiiiis;;;;;;;,
                       ,;;;;;;;riiiiii;.  .;iiiiiir;;;;;;;,
                        .;;;;;;;rsiiiiir..riiiiisr;;;;;;;.
                         .;;;;;;;siSSSSSssSSSSSis;;;;;;;.
                          .:;;;;sii522252252225iis;;;;:.
                            :;;;siiiirrrrrrriSiiis;;;:
                             ,;;iiiir:;iiis::siiii;;,
                              ,;iiiir,:sssr:;iiiii;,
                               ,siiir,:siir;:riiis,
                                ;iiir,:ssss;,riii;
                                ;riSs;;;;;;;riSir;
                                :;riSSSSSSSSSSir;:
                                 .,,;rrrrrrrr;,,.
                                     ,;;;;;;,
                                      ,;;;;,
                                       .;;.
                                        ..

                       Thanks for installing bootstrap-vue
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 219
                              Number of backers: 27
                               Annual budget: $739
                             Current balance: $1,090

              Donate: https://opencollective.com/bootstrap-vue/donate

```

**Comment by tmorehouse** [comment]
BootstrapVue uses the [nuxt-community/opencollective](https://github.com/nuxt/opencollective) package.

You can set environment variables to disable the message. See:
https://github.com/nuxt/opencollective#disable-message

**Comment by moltar** [comment]
I don't think that documentation is correct. They probably assume that consumer package use `opencollective-postinstall`.

Anyways, I do set the envs, and yet this is the only package that outputs OC stuff.

Also, I grepped opencollective cli code and there is no mentioned envs at all, and only postinstall has those envs defined.

So maybe we can consider this to be an issue with postinstall main package and that it needs to respect the envs?

**Comment by moltar** [comment]
There are very mentions of `process.env`:

https://github.com/opencollective/opencollective-cli/search?q=process.env&unscoped_q=process.env

Same here:

https://github.com/nuxt/opencollective/search?utf8=%E2%9C%93&q=process.env&type=

**Comment by moltar** [comment]
Meanwhile:

https://github.com/opencollective/opencollective-postinstall/blob/a1c6bf95c7716f229512fed905af614fc8c33ea1/index.js#L7

**Comment by tmorehouse** [comment]
https://github.com/nuxt/opencollective/blob/24eaec1e35bd9545ddb18b18da92e911ff2a26a1/src/utils/misc.js#L15-L37

**Comment by tmorehouse** [comment]
Set the ENV variable `OPENCOLLECTIVE_HIDE` to a truthy value to disable the message.

**Comment by moltar** [comment]
Thanks!

**Comment by tmorehouse** [comment]
I've created a PR at https://github.com/nuxt/opencollective/pull/8 to include checking the env var `DISABLE_OPENCOLLECTIVE`
