### ISSUE TITLE
b-dropdown-item does not works with v-text in 2.0.0-rc.19

### ISSUE THREAD

**Issue by last-partizan** [bootstrap-vue/bootstrap-vue#3192]
### Describe the bug

After updating from 2.0.0-rc.18 to 2.0.0-rc.19 b-dropdown-item does not works as expected with v-text. Instead of rendering `<li><a>...</a></li>` it renders only `<li>..</li>`

### Steps to reproduce the bug

1. Go to https://jsfiddle.net/last_partizan/7a3x4o8e/7/
2. Click on dropdown
![Screenshot from 2019-04-26 12-35-39](https://user-images.githubusercontent.com/301015/56798876-62f55c00-6820-11e9-9a85-c52e3b58f814.png)

### Expected behavior

Second b-dropdown-item is rendering just like first

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.19
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Comment by Grollicus** [comment]
Same with `v-html`. A possible Workaround would be to add a dummy `<span>` and `v-text`/`v-html` it instead, or use `{{text}}` instead of `v-text`.

**Comment by tmorehouse** [comment]
Working as expected.  See https://github.com/bootstrap-vue/bootstrap-vue/issues/3072 and comment https://github.com/bootstrap-vue/bootstrap-vue/issues/3072#issuecomment-486832818  and https://github.com/bootstrap-vue/bootstrap-vue/issues/3072#issuecomment-486837544

You should avoid using `v-text` and `v-html` on custom components, and restrict their use to only native HTML elements.
