### ISSUE TITLE
Add a key alias for table fields

### ISSUE THREAD

**Issue by impowski** [bootstrap-vue/bootstrap-vue#3212]
### Is your feature request related to a problem? Please describe...

Currently when you have an object with objects inside you need to write it like that inside your `fields` object: `key: 'user.username`

Sometimes when we get the objects from database and use ORMs or GraphQL we want to pass a field with which we want to order our database and we can't pass a key which would look like that `user.username`.

### Describe the solution you'd like

It would be a really amazing and neat feature to have an alias for field key like so:
```
key: 'user.username',
as: 'username'
```

**Comment by tmorehouse** [comment]
Workaround would be to massage the keys in your provider function before passing to your API.

**Comment by impowski** [comment]
@tmorehouse Yeah, did that with `@sort-changed` but an alias would be better and basically with no overhead.

**Comment by tmorehouse** [comment]
Actually the overhead would move into `b-table`

**Comment by impowski** [comment]
Yes and no at the same time, because with a `@sort-changed` I will need to check all of my fields and with just an `alias` which we will utilize inside `@sort-changed`, instead of making say like 10 `includes` or else to understand which key we should use.

**Comment by tmorehouse** [comment]
This is relatively case specific, and one could make a map of aliases to keys (even in the `fields` definition array), and have the provider function handle the mapping/translation. Or specify the field key as teh DB field, and use the `label` field property to display a human readable version.
