### ISSUE TITLE
Trouble extending Vue instance when trying to use modules locally.

### ISSUE THREAD

**Issue by CrashyBang** [bootstrap-vue/bootstrap-vue#3213]
### Describe the bug

I am trying to import modules like so:

```js
import Layout from "bootstrap-components/layout"

export default {
    //... Other vue instance stuff here
    components: {
        Layout
    }
}
```

But I am getting this error:

```
Cannot read property 'extend' of undefined
```

I also tried more explicit imports like `bootstrap-components/layout/row` and `bootstrap-components/layout/col` but got similar issues.

I believe it is because I am trying to use the components in isolated modules without adding `bootstrap-vue` to the global instance with `Vue.use()`, the only thing is I don't have a global instance because I am trying to build isolated modules...

NOTE as per the [introduction section](https://bootstrap-vue.js.org/docs#vue-cli-3) I have added the following to my `vue.config.js`:

```js
// https://bootstrap-vue.js.org/docs#vue-cli-3
resolve: {
    alias: {
        'bootstrap-components': path.resolve(__dirname, 'node_modules/bootstrap-vue/es/components'),
        'bootstrap-directives': path.resolve(__dirname, 'node_modules/bootstrap-vue/es/directives'),
    }
},
```

### Steps to reproduce the bug

1. `import Layout from "bootstrap-components/layout"` and add it to `components`
2. Try to use `<b-row>` or `<b-col>`
3. Open console

### Expected behavior

That importing the module will setup the correct components and that I can use them without a `Vue.use()`

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.19
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Desktop
- OS: Ubuntu 18.10
- Browser: Chrome
- Version: 73.0.3683.103

### Demo link

I will set one up on CodeSandbox if required.

### Additional context

I am using the following command to build the component before I load it in the browser:
```
npx vue-cli-service build --target lib --formats umd-min --no-clean --dest dist/ --name "component-name" src/components/ComponentName.vue
```

**Comment by tmorehouse** [comment]
A few mistakes.

You are importing the Plugin version (i.e. Layout is a plugin which installs components).

Your import path is incorrect:

```js
import Layout from "bootstrap-vue/components/layout"

Vue.use(Layout)
```
or
```js
import BContainer from "bootstrap-vue/components/layout/container"
import BRow from "bootstrap-vue/components/layout/row"
import BCol from "bootstrap-vue/components/layout/col"

export default {
    //... Other vue instance stuff here
    components: {
        BContainer,
        BRow,
        BCol
    }
}
```

**Comment by CrashyBang** [comment]
Hey @tmorehouse,

Okay I was not aware that this was the plugin version that makes a lot of sense!

As for the path issue as I mentioned in the original brief I have added the respective alias to my webpack config to use the path I am using (I can confirm this is working to because I can see that webpack is finding the appropriate source files).

As for importing the components individually, I also mentioned that I have tried that, but I could have been more clear, I have update my code to reflect your example (which is the same as what I had tried before) and I am receiving the same error.

Code: 
```js
// Tried using full path as well as alias to double check, same issue either way
import BRow from "bootstrap-vue/es/components/layout/row"
import BCol from "bootstrap-vue/es/components/layout/col"

export default {
    //...
	components: {
        BRow,
        BCol
    },
}
```

According to the console it is failing here:
```js
var _default = _vue.default.extend({
  name: 'BRow',
  functional: true,
  props: props,
  render: function render(h, _ref) {
    var _class;

    var props = _ref.props,
        data = _ref.data,
        children = _ref.children;
    return h(props.tag, (0, _vueFunctionalDataMerge.mergeData)(data, {
      staticClass: 'row',
      class: (_class = {
        'no-gutters': props.noGutters
      }, _defineProperty(_class, "align-items-".concat(props.alignV), props.alignV), _defineProperty(_class, "justify-content-".concat(props.alignH), props.alignH), _defineProperty(_class, "align-content-".concat(props.alignContent), props.alignContent), _class)
    }), children);
  }
});
```

**Comment by tmorehouse** [comment]
You may also need to set up an alias in Webpack to the `vue` package. See teh note at the end of this section https://bootstrap-vue.js.org/docs#using-module-bundlers

**Comment by tmorehouse** [comment]
You shouldn't need to build the individual components from the `/es` directories, as they are pre-transpiled.

**Comment by CrashyBang** [comment]
Hey @tmorehouse,

It will be the global Vue instance that is causing issues, right now there isn't one because of how I am packaging up these modules.

Cheers!
