### ISSUE TITLE
Displaying raw HTML and non html content in same column

### ISSUE THREAD

**Issue by aakashbashyal21** [bootstrap-vue/bootstrap-vue#3215]
I wanted to display raw HTML with `v-html` and normal text element in the same row.  When using the `template` slot it does not display the html element, when using the `<span>` it only display the html.

Is there any workaround for this? 

What i wanted to achieve is. 

![Html and Text](https://user-images.githubusercontent.com/18410549/56941762-5df11f00-6b36-11e9-9043-6287b03a8ca9.png)

```
<template>
  <div>
    <b-table :fields="fields" :items="items">
      <span slot="html" slot-scope="data" v-html="data.value"></span>
    </b-table>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        fields: ["html"],
        items: [
          {
            text: 'This is <i>escaped</i> content',
            html: 'This is <i>notice for student</i>',
            created_at: '4/30/2019'
          }
        ]
      }
    }
  }
</script>
```

**Comment by tmorehouse** [comment]
There are two options:
- Use `{{ value }}` in a scoped slot to text-interpolate the content (which will escape the HTML characters)
- Use `<span v-text="value"></span>` in a scoped slot to show the HTML converted to text  (which will also escape the HTML characters)

**Comment by aakashbashyal21** [comment]
Sorry! if there are workaround but i could not solve still the issue. I have reproduce in fiddle. Can you help?
Fiddle](https://jsfiddle.net/p81bs64z/1/l)

**Comment by tmorehouse** [comment]
See this updated fiddle: https://jsfiddle.net/0g9wc1aj/

**Comment by aakashbashyal21** [comment]
Sorry. I think am not able to explain my question properly. As in the fiddle in the `Html` column, i wanted to display the row with value from `created_at` and value from `Html`.  

Similar to this.

![image](https://user-images.githubusercontent.com/18410549/56980300-bb6b8700-6b9b-11e9-84ef-3bbd73a7ae5c.png)

**Comment by tmorehouse** [comment]
https://jsfiddle.net/5epw30of/

**Comment by aakashbashyal21** [comment]
Worked perfectly on my code as well, learned complete new thing today. Thank you.
