### ISSUE TITLE
Toast on demand without title/templating?

### ISSUE THREAD

**Issue by EPinci** [bootstrap-vue/bootstrap-vue#3216]
Ok, the following is "opinionated" so I'm rising this... accordingly... more to get an official stance that to rant... ;)

I've dropped the previous toast library I was using when toasts got into bootstrap-vue and I know that the styles are inherited by bootstrap. But I'm now leaning to rethink this.

When you use `<b-toast>`, you control it all, but focus here is when using toast on demand.
I issue attention catching quick messages to my users and, as such, they do not really need a title but they need to be "catchy".
When I issue a toast on demand without title, the heading is actually included, empty, and actually with more color relevance than the actual content.

Now question is: should toast on demand skip the header when there's no title?
And backup question is: should toast on demand render the toast content as header in order to get more impact (based on the fact that there's no header)?

Is there a way to control this kind of stuff with bootstrap-vue (aka: controlling the template of a toast on demand)?

**Comment by tmorehouse** [comment]
The header is retained for the close button.  But if you don't specify a title, and set `noHeaderClose` to true, then the title/header bar will not be rendered.

**Comment by tmorehouse** [comment]
See here for an example: https://jsfiddle.net/cjghuset/

**Comment by tmorehouse** [comment]
If you need HTML content in the toast body, when using `this.$bvToast.toast()`, you can pass VNodes as the title.

use [`this.$createElement(...)`](https://vuejs.org/v2/guide/render-function.html#createElement-Arguments) to return Vue vNodes.

An example can be found here https://jsfiddle.net/rd8pqb74/

**Comment by EPinci** [comment]
Hey thanks! Custom style example was super helpful!

**Comment by andresuchitra** [comment]
Hi @tmorehouse,

I'm new to VNode concept. May I know why we can't make slot template on on-demand bvToast please?
Does it have to be putting <b-toast> on each page/layout ? (I'm using Nuxt in this case).

Thanks.
