### ISSUE TITLE
Docs Lack Description of New Features

### ISSUE THREAD

**Issue by joelhickok** [bootstrap-vue/bootstrap-vue#3218]
The documentation for Bootstrap-Vue is generally excellent, however, I wanted to point out that it doesn't make sense to show that a component is "enhanced" in the sidebar if there is nowhere else you can see the "enhanced" documentation.  For example, on May 1, 2019 I see that Tabs are "enhanced," but when I click Tabs there is no reference to enhanced or new information anywhere on that page.  

Not sure if it helps people by putting a label for enhanced if there is not additional information anywhere else.  "New" or "beta" seems to make much more sense, because that page wasn't there before, or you indicate beta status (e.g. Toasts were just added).

Maybe there could be a very short section at the top of the page listing the enhancements?

![Screenshot 2019-05-01 08 10 18](https://user-images.githubusercontent.com/6742308/57021325-1aa3b880-6be9-11e9-95af-38c491093f11.png)

Thanks for considering the logic to this labeling approach.

**Comment by tmorehouse** [comment]
We'll be adding in badges under the section headings where new/enchanged/changed features are documented.

For now, you can always refer to the changelog for a list of new features/enhancements: https://bootstrap-vue.js.org/docs/misc/changelog

**Comment by joelhickok** [comment]
Great!  That will help draw attention when browsing the docs.  Thank you.
