### ISSUE TITLE
<b-form-select>: Add the variable to make a tree

### ISSUE THREAD

**Issue by ab2d3e8** [bootstrap-vue/bootstrap-vue#3222]
Is it possible to use ' b-form-select ' for a ' optgroup ' from variable:

options: [
{ value: 'A', text: 'Option A' },
{ value: 'B', text: 'Option B' ,
children: [
{ value: 'BA', text: 'Option BA' },
{ value: 'BB', text: 'Option BB' }
]
}
],

**Comment by tmorehouse** [comment]
Currently, no, but you can loop through your own options list and generate the apropriate `<option>` and `<optgroup>` elements to place inside the default slot of `<b-form-select>`.  Note that the heading of an `<optgroup>` is not selectable nor can have a value.

**Comment by mat813** [comment]
It would be nice to have a way to do this, instead of having to iterate over my values and craft the option group and options inside them myself.
I do not see the fact that the array processing function is shared as a problem, if it is not used with a select, simply give out an error ;)

**Comment by tmorehouse** [comment]
We will see if we can get this into release v2.1.0 possibly

**Comment by tmorehouse** [comment]
BootstrapVue v2.2.0 has been released.
