### ISSUE TITLE
Override `tabIndex` setter for <b-tabs>

### ISSUE THREAD

**Issue by vesper8** [bootstrap-vue/bootstrap-vue#3223]
### Is your feature request related to a problem? Please describe...

In my application I've stored tabIndex in a vuex store. One of the things this has allowed me to do is to use a centrally defined keyboard navigation system using the keyboard numbers 1 to 9 to set the tabIndex. There are other reasons too. In any case, as a result of this doing `this.tabIndex = X;` results in an error since there is no setter that allows this in my vuex implementation.

Instead changing the tabIndex needs to be done like this:

```
store.set('layout/tabIndex', X);
```

### Describe the solution you'd like

I would like to override the setter method so that when a tab is changed, either manually or programatically, it calls my own setter rather than try to change the value of tabIndex directly as it is doing now

I've tried using the @input event for this purpose, it would be perfect, except that this event allows you to react when a tab has changed but isn't a means to overriding the setter

**Comment by tmorehouse** [comment]
Create a getter/setter computed prop that you use as the v-model for tabs. the getter/setter can be created to access/set the store value.

See https://vuejs.org/v2/guide/computed.html#Computed-Setter

**Comment by vesper8** [comment]
thank you! that does the trick very nicely
