### ISSUE TITLE
Dropdown wont close on the first click with 'to' properties 

### ISSUE THREAD

**Issue by EstagiarioAnphis** [bootstrap-vue/bootstrap-vue#3225]
Dropdown doesnt close when is clicked for the first time using ':to'. Similar to #284

```
<b-nav-item-dropdown
 <b-dropdown-item :to="switchLocalePath('pt')"> PT </b-dropdown-item>
</b-nav-item-dropdown

//switchLocalePath – Returns a link to the current page in another language
```
I'm trying to do it differently, but seems the following code doesnt work either

`
<nuxt-link :to="switchLocalePath('pt')">
          <b-dropdown-item > PT </b-dropdown-item>
</nuxt-link>
`
First time posting, pls dont hate me

**Comment by tmorehouse** [comment]
Have you tried with setting `to` to a plain location object or path string, instead of the result of a function?

**Comment by EstagiarioAnphis** [comment]
You need this? :to="'/fr/crm/entidades'">
yes still, doesnt close when is clicked for the first time

**Comment by tmorehouse** [comment]
I am unable to re-produce.  I created the following in the docs playground (which has access to the docs $router instance):

```html
<div>
  <b-navbar variant="info" type="dark">
    <b-navbar-nav>
      <b-nav-item-dropdown text="Dropdown">
        <b-dropdown-item to="/play">One</b-dropdown-item>
        <b-dropdown-item to="/play#foo">Two</b-dropdown-item>
        <b-dropdown-item to="/play#bar">Three</b-dropdown-item>
      </b-nav-item-dropdown>
    </b-navbar-nav>
  </b-navbar>
</div>
```

**Comment by tmorehouse** [comment]
Which versions of BootstrapVue and Nut are you using?

**Comment by EstagiarioAnphis** [comment]
Nuxt 2.6.1
bootstrap-vue@2.0.0-rc.18

Sorry, my bad :to="'/'+ locale.code +'/crm/entidades'" actully works

**Comment by tmorehouse** [comment]
You can also pass an object to `to`:

```html
<b-dropdown-item :to="{ name: 'route-name', params: { locale: locale.code } } }">
  Foo
</b-dropdown-item>
```

**Comment by EstagiarioAnphis** [comment]
Unfortunately i dont know if thats going to work but works in this way:
`
<b-dropdown-item @click="test(locale.code)">
  Foo
</b-dropdown-item>
. . .
methods: {
      test(ev) {
          this.$router.push(this.switchLocalePath(ev))
      }
},
`
Now, if it is the right way, i dont know
Thank for you time @tmorehouse

**Comment by tmorehouse** [comment]
What is the output of your method switchLocalePath('pt')?

**Comment by EstagiarioAnphis** [comment]
/de/crm/entidades

**Comment by tmorehouse** [comment]
Is it a string or an object? (i.e. object with `path` property)?

**Comment by EstagiarioAnphis** [comment]
String

**Comment by EstagiarioAnphis** [comment]
`
function switchLocalePathFactory (i18nPath) {
  const LOCALE_DOMAIN_KEY = '<%= options.LOCALE_DOMAIN_KEY %>'
  const LOCALE_CODE_KEY = '<%= options.LOCALE_CODE_KEY %>'

  return function switchLocalePath (locale) {
    const name = this.getRouteBaseName()
    if (!name) {
      return ''
    }

    const { params, ...routeCopy } = this.$route
    const baseRoute = Object.assign({}, routeCopy, {
      name,
      params: { ...params, '0': params.pathMatch }
    })
    let path = this.localePath(baseRoute, locale)

    // Handle different domains
    if (this[i18nPath].differentDomains) {
      const lang = this[i18nPath].locales.find(l => l[LOCALE_CODE_KEY] === locale)
      if (lang && lang[LOCALE_DOMAIN_KEY]) {
        let protocol
        if (!process.browser) {
          const { req } = this.$options._parentVnode.ssrContext
          protocol = req.secure ? 'https' : 'http'
        } else {
          protocol = window.location.href.split(':')[0]
        }
        path = protocol + '://' + lang[LOCALE_DOMAIN_KEY] + path
      } else {
        console.warn('[<%= options.MODULE_NAME %>] Could not find domain name for locale ' + locale)
      }
    }
    return path
  }
}
`

**Comment by tmorehouse** [comment]
Note that `<router-link>` and `<nuxt-link>` (which is a wrapper for `<router-link>` do not support receiving a path with a full URL (i.e. including `https://hostname`)
