### ISSUE TITLE
$bvToast.toast won't accept string 'toastContent' prop, only accepts array of VNodes

### ISSUE THREAD

**Issue by piboistudios** [bootstrap-vue/bootstrap-vue#3227]
### Describe the bug
using:
```
this.$bvToast('My Toast Message', options)
```
results in an error (Cannot read property '_rendered' of 'My Toast Message' thrown from vue.esm.js @ vm.render, called from makeToast @ source: bootstrap-vue/components/toast/helpers/bv-toast.js)

### Steps to reproduce the bug
1. `npm i bootstrap-vue` to get latest
2. Use this.$bvToast.toast

### Expected behavior

Should transform the string into array of VNodes to continue rendering toast for this hungry boy

### Versions

**Libraries:**

- BootstrapVue: bootstrap-vue@^2.0.0-rc.11
- Vue: vue@2.5.17

**Environment:**

- Device: Desktop
- OS: Windows 10
- Browser: Chrome 
- Version: Version 72.0.3626.81

### Additional context

Workaround:
```
this.$bvToast.toast([this.$parent.$createElement("span", {}, "My Toast Message"])

```

ETA:

Sorry, I'm at work, don't have much time to make a PR but I'm pretty sure this would fix it given the workaround:
[This](https://github.com/bootstrap-vue/bootstrap-vue/blob/1bfdde6b7d22e3347de3ef627e4916d59bfa0653/src/components/toast/helpers/bv-toast.js#L117) should be this:
```
keys(propsToSlots).forEach(prop => {
    let value = props[prop]
    if (!isUndefined(value)) {
      // Can be a string, or array of VNodes
      // Alternatively, user can use HTML version of prop to pass an HTML string
      if (prop === 'title' && isString(value)) {
        // Special case for title if it is a string, we wrap in a <strong>
        value = [$parent.$createElement('strong', { class: 'mr-2' }, value)]
      } else if(isString(value)) {
        value = [$parent.$createElement("span", {}, value)]
      }
      toast.$slots[propsToSlots[prop]] = value
    }
  })
```

**Comment by tmorehouse** [comment]
Ensure you are using the latest bootstrap and Vue versions

- BootstrapVue: bootstrap-vue@^2.0.0-rc.19
- Vue: vue@2.6.10

**Comment by piboistudios** [comment]
> Ensure you are using the latest bootstrap and Vue versions
> 
> * BootstrapVue: bootstrap-vue@^2.0.0-rc.19
> * Vue: vue@2.6.10

Ah, will give that a shot. Thanks.

**Comment by piboistudios** [comment]
Confirmed; issue was old vue version.
