### ISSUE TITLE
Nav component on android 4.4

### ISSUE THREAD

**Issue by hvalcourtSerdy** [bootstrap-vue/bootstrap-vue#323]
a) Go to https://bootstrap-vue.github.io/docs/components/nav on Webview Android 4.4 (use application WebView Tester http://bit.ly/2qlN8t7)
b) The tabs dont show correclty
c) Screenshot: 
![9_android_webview](https://cloud.githubusercontent.com/assets/25179767/25620372/287ff6fa-2f1c-11e7-971a-19201261da1e.png)

**Comment by pi0** [comment]
This is a problem with Bootstrap 4 incompatibility itself. See #322.
