### ISSUE TITLE
Carousel component bun on Webview Android 4.4

### ISSUE THREAD

**Issue by hvalcourtSerdy** [bootstrap-vue/bootstrap-vue#324]
a) Go to https://bootstrap-vue.github.io/docs/components/carousel on Webview Android 4.4 (use application WebView Tester http://bit.ly/2qlN8t7)
b) Bug when you use arrow to go on another slide (freeze)
c) Screenshot: 
![10_android_webview](https://cloud.githubusercontent.com/assets/25179767/25620448/680dbf46-2f1c-11e7-96af-2ea54a576f56.png)

**Comment by tmorehouse** [comment]
This is most likely a problem with Bootstrap 4 incompatibility itself. See #322.
