### ISSUE TITLE
<b-table> Truncate text with ellipsis alternatively instead of text-wrap

### ISSUE THREAD

**Issue by ddweber** [bootstrap-vue/bootstrap-vue#3249]
### Is your feature request related to a problem? Please describe...

When `b-tables` width gets crunched together the text wraps into new lines. In cases where there is no much horizontal space left this isn´t ideal and sometimes looks a bit weird.

### Describe the solution you'd like

I would like the text inside b-table cells to be truncated with an ellipsis like the following if it does not fit in one row:

_This text fits
This text is to long and..._

### Additional context

I got the idea from @alexsasharegan [tweet ](https://twitter.com/AlexSashaRegan/status/1124129210270867457) on twitter.

**Comment by tmorehouse** [comment]
Unfortunately that solution only works for flex box (i.e. the `min-width` setting), and not on table cells.

You would need to use item scoped slots, and create a div wrapper for your text content, and set the widths and text-overflow setting on the wrapper div.

**Comment by tmorehouse** [comment]
For tables, you can see a potential solution here: https://stackoverflow.com/questions/5239758/css-truncate-table-cells-but-fit-as-much-as-possible

basically either set the table to `fixed` (which renders all cells equal width), or use `table-colgroup` slot to set col widths, and then wrap your cell content in a div with 100% width and text-truncate (i.e. use classes `w-100 text-truncate` on the div.

**Comment by ddweber** [comment]
Thanks @tmorehouse ! I really appreciate your effort to provide a solution to the issue :)

I tried to implement it the suggested way but with no luck. I could not get the scoped `table-colgroup` slot to work properly (it only rendered an empty colgroup). An example (in the docs section as well) would be great.

**Comment by tmorehouse** [comment]
I was able to get tet to truncate using the `fixed` table prop, and hten using an item scoped slot:

```html
<b-table fixed :items="items" :fields="fields" ....>
  <template slot="someField" slot-scope="{ value }">
    <div class="w-100 text-truncate">{{ value }}</div>
  </template>
</b-table>
```

Where the someField value is a very long text string.

Unfortunately the `fixed` prop of table makes each column roughly equal width.

**Comment by ddweber** [comment]
The fixed prop solutions seems to work. But in my case the table-columns need to have individual width.

**Comment by MRVDH** [comment]
@ddweber @tmorehouse I ran into the same issue and simply fixed it by adding this css:

```css
td {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    max-width: 1px;
}
```

The `max-width: 1px;` does the trick here. Maybe this could be added to the documentation?

**Comment by MRVDH** [comment]
The problem with my code snipper is that all columns are still the same size. Would be great if this could be reopened and would work with variable column widths.

**Comment by ardhie1032** [comment]
The best solution I've found:

```vue
<template>
  <table class="table">
    <tbody>
      <tr v-for="item, index in items">
        <td>{{ index + 1 }}</td>
        <td class="cursor-default">
          <input class="form-control-plaintext text-truncate" :value="item.content" readonly>
        </td>
        <td>{{ item.views }}</td>
      </tr>
    </tbody>
  </table>
</template>

<style scoped>
input.form-control-plaintext {
  pointer-events: none; /* can't select or scroll */
}
</style>
```

**Comment by ardhie1032** [comment]
The best solution I've found: https://gist.github.com/ardhie1032/d24de9b496b4458f55756ab4f6038a37
