### ISSUE TITLE
mixins/dropdown.js - items[0].focus() is not a function

### ISSUE THREAD

**Issue by cosmophile** [bootstrap-vue/bootstrap-vue#325]
Hello, great library!

Just wanted to bring to your attention that [mixins/dropdown.js#L123](https://github.com/bootstrap-vue/bootstrap-vue/blob/ef12f23d85be92f5a4735025c58baf48a97f6863/lib/mixins/dropdown.js#L123) returns an array that contains a single Nodelist, instead of an array that contains nodes (as you wanted, by using the spread operator).

Either:
`return Array.prototype.slice.call( this.$refs.menu.querySelectorAll(ITEM_SELECTOR) )`

or

`return [].concat.apply( [], this.$refs.menu.querySelectorAll(ITEM_SELECTOR) )`

...would give you the items in array format.

Thank you for all the work!

**Comment by tmorehouse** [comment]
Yeah, I noticed this last night too.

I'll fix this up later tonight.

**Comment by tmorehouse** [comment]
Hmmm `[...document.querySelectorAll(SELECTOR)]` should work, unless Babel isn't converting the `nodeList` correctly.

http://www.jstips.co/en/javascript/converting-a-node-list-to-an-array/
https://davidwalsh.name/spread-operator

**Comment by tmorehouse** [comment]
In some browsers, `NodeList` doesn't have an iterator, which is needed by the spread operator.  Fix on it's way.
