### ISSUE TITLE
Programatically accessible slots for Toasts

### ISSUE THREAD

**Issue by rizen** [bootstrap-vue/bootstrap-vue#3254]
### Is your feature request related to a problem? Please describe...

Most of the time when I create a toast I'm doing it programmatically (aka via this.$bvToast) rather than an inline <b-toast> component. However, I also need to be able to include buttons and links and other content in the body of the toast. I cannot see a way to do that right now.

### Describe the solution you'd like

I'd like to be able to inject content into the slot programatically. One way would be to allow me to do an inline template. Another way would be to give me a reference to the component created by $bvToast so that I could manipulate the slot via:

component.$slots.default = `put content here`

### Describe alternatives you've considered

I can't think of any work arounds for this other than just not using toasts. If I had a work around I likely wouldn't even have filed a feature request.

### Additional context

Here's a simple contrived example.

![simple contrived example](https://user-images.githubusercontent.com/170009/57328297-ae3c2400-70d6-11e9-8a87-2cba81322ff5.png)

**Comment by tmorehouse** [comment]
You can  use [`this.$createElement(...)`](https://vuejs.org/v2/guide/render-function.html#createElement-Arguments) to pass VNodes to the message/title instead of strings..

See: https://jsfiddle.net/jsxrL0ea/

**Comment by tmorehouse** [comment]
You can also make the body of your toast a link (using `href` or `to` props) to link to the cart.

**Comment by rizen** [comment]
Thank you for this answer! I got it working as you suggested. I would recommend that this be documented somewhere in that page. But either way, this was amazing help, thank you so much!

**Comment by tmorehouse** [comment]
We mention it in the docs ( that VNodes can be passed), but don't provide an example for it (yet).

Just remember to make sure you pass the VNodes as an array (even if there is only one VNode). It works with a single root VNode currently, but we may require that VNodes always be passed as an array, so that we can add additional calling signatures to `$bvToast.toast(...)`

**Comment by tmorehouse** [comment]
As a side note, the modal Message boxes (`$bvModal.msgBoxOK(...)` and `$bvModal.msgBoxConfirm(...)`) also accept arrays of VNodes for title and message.

**Comment by rizen** [comment]
Yeah this is a game changer of a feature. I feel like there are light bulbs exploding above my head right now.

**Comment by tmorehouse** [comment]
For modal, we'll be introducing some new msgBox methods for adding things like inputs, etc, and a way to pass data to a predifined modal (via the `this.$bvModal.show(...)` method), which will be available via scoped slots for binding to inputs), and have that method return a Promise when passed a second argument, which will return the BvModalEvent object with the data as a property.

**Comment by unre4l** [comment]
> ...so that we can add additional calling signatures to `$bvToast.toast(...)`, i.e. adding ability for message or title to be a scoped slot function (so you have access to the `hide()` method to close the toast)...

@tmorehouse hi, i am looking for this exactly case, to be able to invoke hide()  wihtin render functions. Are there any news regarding this?

**Comment by pitahbread** [comment]
Is there a way to update the nodes once the toast has been created/shown?
