### ISSUE TITLE
Grid list

### ISSUE THREAD

**Issue by digitalgym** [bootstrap-vue/bootstrap-vue#3257]
I need to display, filter and page a dataset in a card style grid list layout.

I need the same functionality as the table component but fora grid list.

I’d like the table component extended to work with grid lists

Considering using Vuetifyjs

**Comment by digitalgym** [comment]
Thanks for the help, I was hoping to avoid DIY but it looks like its the only option at this stage. I was hoping there might be an easy way to reuse the paging and filter functionality from the table component.

**Comment by tmorehouse** [comment]
Paging and sorting are probably the smallest code parts of table.  most of the code deals with rendering.

You can see the code here:

- [Filtering](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/table/helpers/mixin-filtering.js)
- [Sorting](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/table/helpers/mixin-sorting.js)
- [Pagination](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/table/helpers/mixin-pagination.js)

Filtering is probably the most complex of three, with pagination being the simplest code. The above sections are written as mixins that are applied to table, and feed off of each other (as computed props) in the order listed above.

**Comment by tmorehouse** [comment]
So you should be able to borrow the code parts needed from the above sections (and remove some of the complexities not needed for your particular application).

**Comment by Blanen** [comment]
@digitalgym Heard of ag-grid-vue?
