### ISSUE TITLE
<b-tab> Extending component causes b-tab to stop working

### ISSUE THREAD

**Issue by Pidz-b** [bootstrap-vue/bootstrap-vue#3260]
Heya,

I am trying to create a custom tab component to incorporate extra components and reduce duplicate code.

Sadly, whenever I try to use `extends` or `mixins` with the tab component, the tab navigation stops working.

### Steps to reproduce the bug

1. Create a custom component:

```vue
<template>
  <b-tab v-bind="$props">
    <slot></slot>
    <pagination v-if="pagination"
                :total-rows="pagination.totalRows"
                :per-page="pagination.limit">
    </pagination>
  </b-tab>
</template>

<script>
import Tab from 'bootstrap-vue/es/components/tabs/tab';
import Pagination from '@/components/Pagination.vue';

export default {
  name: 'Tab',
  extends: Tab,
  components: {
    Pagination,
  },
  props: {
    ...Tab.props,
    pagination: false
  }
}
</script>
```

2. Create a component that incorporates our element within a `<b-tabs>` element.
3. Click on the tab header
4. No `tab-content` is visible

### Expected behavior

That the tab works just like a normal tab and makes the correct `tab-content` visible.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.19
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- OS: Any (Fedora, Mac OS, Windows)
- Browser: Chrome
- Version: Chrome 74.0.3729.131 

### Additional context

I have used the example of the `b-button` from [here](https://github.com/bootstrap-vue/bootstrap-vue/issues/2137)

**Comment by tmorehouse** [comment]
What is happening is that `b-tab` is no longer a logical direct component child of `t-tabs` (as there is technically now a new upper wrapper component).  We may need to investigate on a better way to detecting tabs at a deeper level (but also ignoring nested tabs).

**Comment by Pidz-b** [comment]
I was expecting that this was the issue.
Any way to manually add emits on click or is there maybe a way I can help?

**Comment by tmorehouse** [comment]
One option you might be able to do for now is create a custom component that gets placed into b-tab.  that custom component would have, say a plain outer wrapper div, and then your default slot and pagination as children of that div.  It would require you to use the following when creating the content for your b-tabs:

```html
<b-tab ...>
  <my-tab-content :pagination="pagination">
    Content for default slot
  </my-tab-content>
</b-tab>
```

**Comment by tmorehouse** [comment]
Something else you could try is this with your extended component:

```html
<template>
  <b-tab v-bind="$props" v-on="$listeners">
    <slot></slot>
    <pagination v-if="pagination"
                :total-rows="pagination.totalRows"
                :per-page="pagination.limit">
    </pagination>
  </b-tab>
</template>
```

This will ensure any listeners are transferred to the inner component.

**Comment by tmorehouse** [comment]
@Pidz-b did the last suggestion work for you (the one with `$listeners`)?

**Comment by Pidz-b** [comment]
@tmorehouse 
Sadly not.
I have tried the following:

### Parent component
```vue
<b-tabs>
        <tab :title="`${$t('general.actions')} (${actionCount})`"
             :pagination="{ totalRows: 5, limit: 3 }"
             @change="paginateActions">
             <span> test </span> 
        </tab>
</b-tabs>
```

### Child
```vue
<template>
  <b-tab v-bind="$props" v-on="$listeners">
    <slot></slot>
    <pagination v-if="pagination"
                :total-rows="pagination.totalRows"
                :per-page="pagination.limit">
    </pagination>
  </b-tab>
</template>

<script>
import Tab from 'bootstrap-vue/es/components/tabs/tab';
import Pagination from '@/components/Pagination.vue';

export default {
  name: 'Tab',
  extends: Tab,
  components: {
    Pagination,
  },
  listeners: {
    ...Tab.listeners
  },
  props: {
    ...Tab.props,
    pagination: false
  }
}
</script>
```

But sadly, the `tab-content` is not becoming visible.

I also tried without the listeners property on the export object, to no avail.

**Comment by tmorehouse** [comment]
You don't need to re-define the listeners or the b-tab props in your extended component definition (as that is what `extends` (and/or `mixins`) is for:

```html
<template>
  <b-tab v-bind="$props" v-on="$listeners">
    <slot></slot>
    <pagination v-if="pagination"
                :total-rows="pagination.totalRows"
                :per-page="pagination.limit">
    </pagination>
  </b-tab>
</template>

<script>
import BTab from 'bootstrap-vue/es/components';
import Pagination from '@/components/Pagination.vue';

export default {
  name: 'Tab',
  extends: BTab,
  components: {
    Pagination,
  },
  props: {
    pagination: false
  }
}
</script>
```

**Comment by Pidz-b** [comment]
@tmorehouse Yeah, I tried that as well.
I also written that down in my last comment, but maybe I should've added code for better clarification.

Even with your example. It does not triggers the correct event to show a content tab.

**Comment by folmert** [comment]
Also after updating bootstrap-vue from 2.0.0-rc.17 to 2.0.0-rc.22 passing `:id` to `<b-tab>` breaks displaying tabs, i.e. if I had 2 tabs only 1 is now displayed. There are no console errors or warnings. After removing `:id` prop from all `<b-tab>` both tabs are displayed again.

**Comment by tmorehouse** [comment]
@folmert PR https://github.com/bootstrap-vue/bootstrap-vue/pull/3442 addresses your issue re the IDs

**Comment by tmorehouse** [comment]
@Pidz-b Here is a solution that _may_ work, although the detection routine that scans the DOM after mount for tabs tries to get the b-tab instances from the element reference (i.e. `el.__vue__`), so thre is a chance it may not detect the b-tab instances after mount (since you are adding an extra layer in the component parent stack)

```html
<template>
  <b-tab v-bind="$props" v-on="$listeners">
    <slot></slot>
    <pagination v-if="pagination"
                :total-rows="pagination.totalRows"
                :per-page="pagination.limit">
    </pagination>
  </b-tab>
</template>

<script>
import BTab from 'bootstrap-vue';
import Pagination from '@/components/Pagination.vue';

export default {
  name: 'Tab',
  components: {
    Pagination,
  },
  props: {
    ...BTab.props,
    pagination: false
  }
}
</script>
````

This might be close, but we may need to alter the detection routine a bit to handle the case of the tab being nested inside another component.

**Comment by tmorehouse** [comment]
@Pidz-b Version 2.0.0-rc.23 has been released.
