### ISSUE TITLE
B-Tab No longer works in IE 11 due to find() method

### ISSUE THREAD

**Issue by ShaynCornwell** [bootstrap-vue/bootstrap-vue#3267]
### Describe the bug
In IE11 B-Tabs produces this error

> Error in nextTick: "TypeError: Object doesn't support property or method 'find'"
>     found in
>         BTabs

### Steps to reproduce the bug
**My Code utilizing B-Tabs**
```
<b-tabs class='mx-4'>
                <b-tab title="test 1"
                       key="1"
                       active
                       v-on:click="SetFocus(0)">
--- Components in different <b-row></b-row>
      </b-tab>
                <b-tab title="test 2"
                       key="2"
                       v-on:click="SetFocus(0)">
--- Components in different <b-row></b-row>
      </b-tab>
                <b-tab title="Activity"
                       key="3"
                       v-on:click="SetFocus(0)">
--- Components in different <b-row></b-row>
      </b-tab>
</b-tabs>

```
### Expected behavior

This is a recent issue and my assumption is with a recent release? I updated from rc14 to rc19

### Versions

**Libraries:**
    "axios": "^0.18.0",
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.0-rc.19",
    "vue": "^2.6.8",
    "vue-class-component": "^7.0.1",
    "vue-property-decorator": "^7.3.0",
    "vue-router": "^3.0.1",
    "vue-session": "^1.0.0",
    "vuex": "^3.1.0",
    "vuex-class": "^0.3.1",
    "vuex-module-decorators": "^0.8.0"

**Comment by tmorehouse** [comment]
Make sure you are loading a polyfill for IE11 browsers.

**Comment by ShaynCornwell** [comment]
> Make sure you are loading a polyfill for IE11 browsers.

So I am now polyfilling using
>  jspolyfill-array.prototype.find
the next error that comes up when clicking is another polyfill issue for the method .from()

I am curious why these polyfill issues are now coming up with the updated version of Boostrap-vue? Were these being done automatially in the previous versions?

**Comment by tmorehouse** [comment]
A few versions back we removed some of the embedded polyfills in favour of uses providing their own (as in most cases they would be for IE 11)

https://bootstrap-vue.js.org/docs#browser-support

**Comment by tmorehouse** [comment]
If using Babel, and `babel/preset-env`, in your project you can get Babel to provide polyfils for browsers based on your browserlist config.

**Comment by ShaynCornwell** [comment]
> If using Babel, and `babel/preset-env`, in your project you can get Babel to provide polyfils for browsers based on your browserlist config.

Yes, I have that set and tried the polyfills mentioned above but they didnt work to resolve the From() issue, however they did solve the find(). I reverted back to version rc14 and the tabs work again.

I will continue to work with the polyfills so I can use the updated version

**Comment by tmorehouse** [comment]
If serving your app over the web, you can use https://polyfil.io, which only delivers polyfills needed by the browser (based on the browsers User-Agent string).

**Comment by ShaynCornwell** [comment]
> If serving your app over the web, you can use https://polyfill.io, which only delivers polyfills needed by the browser (based on the browsers User-Agent string).

Thank you, BTW the link is https://polyfill.io, you're missing an "l". By using that  and gathering the Find() and From() polyfills, rc19 works for me now. Thank you.

In case anyone wants the exact polyfill link used its:
https://polyfill.io/v3/polyfill.min.js?features=Array.from%2CArray.prototype.find 

This fixed my upgrades from rc14 to rc19

**Comment by tmorehouse** [comment]
Fixed the typo above...

Here is the polyfill.io we reccomend:

//polyfill.io/v3/polyfill.min.js?features=es2015%2CMutationObserver

Which also includes MutationObserver polyfill needed (if the browser does not support it) for some components.
