### ISSUE TITLE
b-form-select display in npm run prod with autoprefixer: true

### ISSUE THREAD

**Issue by fabolousfrances** [bootstrap-vue/bootstrap-vue#3268]
### Describe the bug

Hello, I use bootstrap vue in laravel framework.
I have a problem with b-form-select.
With npm run dev / watch, the display is ok,
but with npm run prod, there is a bug.
I have the browser standard grey arrow in the select and the boostrap two arrows too.
So 3 arrows on the select.

the bug is provoqued in npm run prod by autoprefixer: true in webpack.mix.js
if I comment autoprefixer, the bug is not here.

### Steps to reproduce the bug

1. put a b-form-select in .vue file
2. autoprefixer: true in webpack.mix.js in mix.inProduction()
3. npm run prod
4. view it in the browser

### Expected behavior

Do not display the standard browser arrow with the bootstrap arrows in the select.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.19
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC with 24" screen
- OS: windows 10 Pro
- Browser: Firefox & Chrome
- Version: 66.0.5 & 74.0.3729.131

<b-form-select> with npm run dev / watch :
![select-npm-run-dev](https://user-images.githubusercontent.com/2512386/57537458-9965c780-7346-11e9-8f92-65f24651ce86.JPG)

<b-form-select> with npm run prod and autoprefixer: true in webpack.mix.js in mix.inProduction () :
![Capture-select](https://user-images.githubusercontent.com/2512386/57536248-0c217380-7344-11e9-8077-7bca4264d985.JPG)

**Comment by tmorehouse** [comment]
This would be an issue wth running auto-prefier again on Bootstrap V4.3's pre-compiled CSS (which has already had auto-prefixer run on it).

I would suggest either removing auto-prefixer from your config, or switch to using Bootstrap SCSS and BootstrapVue's SCSS source files.
