### ISSUE TITLE
since rc12 vue test utils returns empty wrapper for some elements

### ISSUE THREAD

**Issue by Qvatra** [bootstrap-vue/bootstrap-vue#3270]
### Describe the bug

I have noticed that since rc12 vue-test-utils are not longer able to find some elements using  name selector:
`wrapper.find({ name: 'bFormRadioGroup' })` returns empty wrapper.
the same is for `bFormSelect` and `bFormInput` when using findAll by name

### Steps to reproduce the bug

For me it is easy to reproduce - run npm i bootstrap-vue which will update bv to the rc19 and my unit tests will stop working but for the community I'm afraid I don't have much... Just hope this bug might be caught by reviewing changes in rc12.

in rc11 these selectors work but in rc12 they return empty wrappers.

### Expected behavior

vue-test-utils still should be able to locate elements by using find by name selectors

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc12 and up
- Bootstrap: 4.1.3
"nuxt": "^2.3.4",
"@vue/test-utils": "^1.0.0-beta.29"

**Environment:**
- macOS Mojave

**Comment by tmorehouse** [comment]
Per the Vue style guide, we have named all components in <samp>PascalCase</samp> instead of <samp>camelCase</samp>.
