### ISSUE TITLE
<b-img> as picture

### ISSUE THREAD

**Issue by derevandal** [bootstrap-vue/bootstrap-vue#3275]
### Describe the solution you'd like

- Enable choose `<picture>` or `<img>` to handle image.
- With `<picture>`, we can use `<source>` to improve responsiveness with `media` and `srcset`.

### Additional context

[`<picture>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)

**Comment by tmorehouse** [comment]
Currently `picture` is not supported in some older browsers

**Comment by tmorehouse** [comment]
You can also set `srcset` attribute on `<b-img>` if you just want different density images (compression, etc) and let the browser decide what should be used: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset

Vue will pass down any non-prop attributes set on `<b-img>` as attributes on the root `<img>` element.

**Comment by tmorehouse** [comment]
But note that if anything causes the `<b-img>`, Vue will most-likely reset the `src` attribute on the underlying `<img>` tag to what is set in the `src` prop.

**Comment by derevandal** [comment]
> Currently `picture` is not supported in some older browsers
In this case, it will be render as div with `<img>` inside.

> It might be better to create a new custom component than try to integrate `<picture>` into `<b-img>` (since `<picture>` requires children, and `<img>` does not)

It could be like `<b-embed>, coulnd't?`

**Comment by derevandal** [comment]
> But note that if anything causes the `<b-img>`, Vue will most-likely reset the `src` attribute on the underlying `<img>` tag to what is set in the `src` prop.

I'll do this, but, I want use `webp` as alternative. :S

**Comment by tmorehouse** [comment]
Yeah `<b-picture>` would probably be wat it would be called (and created and documented in the image page/directory)

**Comment by tmorehouse** [comment]
The src prop would probably need to be non-reactive, and used only during the `create` lifecycle hook.

Or the component would need to be a functional component (no `this` context)

**Comment by derevandal** [comment]
When it will be released?

Em seg, 1 de jul de 2019 15:56, Troy Morehouse <notifications@github.com>
escreveu:

**Comment by tmorehouse** [comment]
We have no plans currently to implement `b-picture`, but it may appear in a minor release version in 2.x.0 stable.

Our current goal is to finalize the last few fixes for 2.0.0 stable release.
