### ISSUE TITLE
<b-img-lazy>: IntersectionObserver

### ISSUE THREAD

**Issue by derevandal** [bootstrap-vue/bootstrap-vue#3276]
### Describe the solution you'd like

Use `IntersectionObserver` as observer to control if a image is seeing by user or not.
This will improve performance in modern browsers.

### Describe alternatives you've considered

In `v-img-lazy`, this is already in [use](https://github.com/alexjoverm/v-lazy-image/blob/2566eae7aef62c52b8d2dd3a22f35f59d3ba671c/src/index.js#L60):
```js
mounted() {
    if ("IntersectionObserver" in window) {
      this.observer = new IntersectionObserver(entries => {
        const image = entries[0];
        if (image.isIntersecting) {
          this.intersected = true;
          this.observer.disconnect();
          this.$emit("intersect");
        }
      }, this.intersectionOptions);
      this.observer.observe(this.$el);
    } else {
      console.error(
        "v-lazy-image: this browser doesn't support IntersectionObserver. Please use this polyfill to make it work https://github.com/w3c/IntersectionObserver/tree/master/polyfill."
      );
    }
  },
```
### Additional context

[Intersection Observer AP](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

**Comment by tmorehouse** [comment]
Not all browsers support Intersection Observer, and switching to it would be a breaking change (and the above code would need tweaking to handle offsets away from the viewport to load the image before it comes into view).

It would need a fallback to scroll checks if Intersection Observer is not supported by the browser, rather than leaving some users out in the cold.

**Comment by academici** [comment]
@tmorehouse chrome 75+ supports loading attribute for image tag
```html
<img src="lazy.jpg" loading="lazy" alt="Lazy image">
```
Can affix this attribute. 
If it is not supported by the browser, then initialize IntersectionObserver
```js
if ('loading' in HTMLImageElement.prototype)
```

**Comment by tmorehouse** [comment]
I think we'll stick with `IntersectionObserver` and fallback to `scroll`/`resize` events, until the `loading` attribute becomes more standard across browsers (and I am not sure if it even supports placeholder images)

**Comment by tmorehouse** [comment]
Version 2.0.0-rc.21 has been released
