### ISSUE TITLE
Modal styling

### ISSUE THREAD

**Issue by odo48** [bootstrap-vue/bootstrap-vue#3277]
I try to add some style to header using: header-class="headerModal" or /deep/ .modal-header or >>> .modal-header and it doesn't take my css(style scoped)
![Screenshot from 2019-05-13 15-57-54](https://user-images.githubusercontent.com/22925011/57623187-ee4c4c80-7597-11e9-95e3-7a11a883692b.png)
![Screenshot from 2019-05-13 15-57-25](https://user-images.githubusercontent.com/22925011/57623189-eee4e300-7597-11e9-8316-fcfd287b3582.png)
![Screenshot from 2019-05-13 15-57-14](https://user-images.githubusercontent.com/22925011/57623191-eee4e300-7597-11e9-978f-ae700b4d4167.png)

**Comment by tmorehouse** [comment]
Avoid using `scoped` styles to style inner parts of a sub-component (Vue doesn't add the scoping attribute to elements inside a sub-component).
