### ISSUE TITLE
<b-input-group> slots behaves weirdly

### ISSUE THREAD

**Issue by bruceCzK** [bootstrap-vue/bootstrap-vue#3284]
### Describe the bug

Input group slots doesn't work as expected.

![image](https://user-images.githubusercontent.com/8399711/57677564-b6a5d900-7659-11e9-9772-1a688be40cb9.png)
![image](https://user-images.githubusercontent.com/8399711/57677570-bb6a8d00-7659-11e9-825b-282d314bff07.png)

### Steps to reproduce the bug

1. Add button to append slot in b-input-group
2. With the new syntax (v-slot:append), the button text is not showing
3. With the old syntax (slot="append"), the button is not showing

### Expected behavior

Slots works like previous version.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0. RC20
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome
- Version: 75

### Demo link

[JSFiddle](https://jsfiddle.net/3jw07d4e/12/).

**Comment by doncatnip** [comment]
This also breaks a couple of examples in the official docs using input groups. I.e. this one:
https://bootstrap-vue.js.org/docs/components/table#complete-example
(sort direction drop down is missing)

**Comment by tmorehouse** [comment]
In your example above, you are setting two different things to the same slot name (there can be only one). either use the following example when placing multiple buttons in the same append/prepend:

```html
  <b-input-group prepend="Title">
    <b-form-input></b-form-input>
    <b-input-group-append>
      <b-button>Button</b-button>
      <b-button>Button</b-button>
    </b-input-group-append>
  </b-input-group>
```

**Comment by bruceCzK** [comment]
I'm sorry the demo wasn't meant to be like that. Actually with only one button, the slot still doesn't work as expected as well. The button just not showing.
![image](https://user-images.githubusercontent.com/8399711/57701377-76148280-768e-11e9-8d87-a99ba20cc1d0.png)
![image](https://user-images.githubusercontent.com/8399711/57701331-5da46800-768e-11e9-99b4-675a11aa3cce.png)

**Comment by tmorehouse** [comment]
Yeah, I noticed that too... will need to investigate.  For now you can wrap your button in a `<b-input-group>` append (and ditch using the slot)

**Comment by bruceCzK** [comment]
Noted. Thanks for the quick response.

**Comment by tmorehouse** [comment]
Found the issue... was a typo in the `b-input-group` code

**Comment by tmorehouse** [comment]
Version 2.0.0-rc.21 has been released
