### ISSUE TITLE
Small file chooser (b-form-file)

### ISSUE THREAD

**Issue by AnReZa** [bootstrap-vue/bootstrap-vue#3285]
I want to integrate a file chooser b-form-file into a table with small input fields (size="sm"). However, this property is being ignored for the file input. How can I make it appear in the same size als the regular small text input fields?

**Comment by tmorehouse** [comment]
Unfortunately Bootstrap V4.x CSS/SCSS does not define/support sizing on the custom file inputs.

**Comment by tmorehouse** [comment]
You may want to open an issue at https://github.com/twbs/bootstrap/issues

**Comment by jackmu95** [comment]
Closes by #3794.

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0-rc.28 has been released.
