### ISSUE TITLE
b-form-file component browse-text prop has no effect

### ISSUE THREAD

**Issue by technofreak** [bootstrap-vue/bootstrap-vue#3296]
### Describe the bug

Setting the browse-text prop on b-form-file component does not set the label to the string passed via the prop, it sets to default value

### Steps to reproduce the bug

`<b-form-file
          multiple
          v-model=supporting_documents"
          ref="supporting-docs"
          placeholder="Choose one or more files.."
          browse-text="Select files"
        ></b-form-file>`

[screenshot](https://imgur.com/wA8cnZE)

### Expected behavior

The string passed via browse-text prop should be shown in the label.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.12
- Bootstrap: ~4.1.1
- Vue: 2.6.6

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome 
- Version: 73.0.3683

**Comment by tmorehouse** [comment]
Upgrade to a newer release of BootstrapVue (we are now at 2.0.0-rc.20), and make sure you are using Bootstrap v4.3.1 CSS/SCSS (you have referenced 4.1.1 which is missing the CSS required)
