### ISSUE TITLE
[pagination-nav] Docs

### ISSUE THREAD

**Issue by Edduard** [bootstrap-vue/bootstrap-vue#3301]
While using <b-pagination-nav> "input" event will work but will be triggered even on first mount. So I read the docs and found that "change" event will only be triggered when I need it. 

But found out that "change" event doesn't not fire at all.

I'm using this syntax on vue:

This is working:

`            <b-pagination-nav v-model="currentPage" :linkGen="linkGen" @input="changePage" :number-of-pages="totalPages"></b-pagination-nav>
`

This is not

`            <b-pagination-nav v-model="currentPage" :linkGen="linkGen" @change="changePage" :number-of-pages="totalPages"></b-pagination-nav>
`

**Comment by tmorehouse** [comment]
The `change` event is fired only when a user clicks the a page button (and it would cause the current page to change).  the `input` event is used to ensure the v-model is always up to date.

We could add in a check for the input event to see if the currentPage is not equal to the v-model value and only emit if not the same (value or type)

**Comment by Edduard** [comment]
It's not firing neither when a user clicks a page button

**Comment by tmorehouse** [comment]
Are you using `b-pagination` or `b-pagination-nav`?

**Comment by tmorehouse** [comment]
Also which version of BootstrapVue are you using? Make sure you are on the latest 2.0.0-rc.20 release.

**Comment by Edduard** [comment]
> Are you using `b-pagination` or `b-pagination-nav`?

I'm using b-pagination-nav , you can see the code in the first post.

I'm using     "bootstrap-vue": "^2.0.0-rc.11",

**Comment by tmorehouse** [comment]
Ah, right, re which component.

You should probably upgrade to version 2.0.0-rc.20

**Comment by tmorehouse** [comment]
I believe the `change` event was added after rc.11

**Comment by tmorehouse** [comment]
@Edduard I would suggest upgrading to v2.0.0-rc.20 and see if that helps your issue.
