### ISSUE TITLE
Editable column in b-table doesn't bind to the view model

### ISSUE THREAD

**Issue by AnReZa** [bootstrap-vue/bootstrap-vue#3302]
I'm having a b-table control, where all columns are defined by using scoped templates. In some coulmns, the user should be able to edit the value of a specific column by using a b-form-input control.

However, this doesn't work, because even though I bind the inputs via v-model, it seems to create a copy of each data set in the background and bind the table's data model to that. No matter how I change the data inside the table, it's never applied to the actual view model.

Here's a mimimized example

```vue
<b-table class="mt-3 mb-0" :fields="fields" :items="complaint.articles" striped show-empty>
  <template slot="article" slot-scope="data">
    <b-form-input size="sm" type="text" v-model="data.value" placeholder="Part no" />
  </template>
</b-table>
```

It doesn't apply the changed from the text field to my original data model.

How can I work around that? Or is it a bug?

**Comment by tmorehouse** [comment]
B-table makes a copy of the source item's array (although it retains reference to the individual row item data.

the scoped var `data.value` is a copy of the data (after passing through possible formatting), and is passed as the value, not a reference to the value.  use `data.item[key]` where key is the field value you are working with (in your case it would be `article`).

**Comment by AnReZa** [comment]
@tmorehouse Thank you! It works now. Can I somehow see, when or if it re-renders the grid? I can't see any hints for that, even without specifying a key.

Just to make it clear for everyone: You would have to bind it to `data.item['article']` in my example.

**Comment by tmorehouse** [comment]
If you didn't have a key, and as you were typing in the input, your cursor may jump as you type.  that would be an indication of a re-render.

**Comment by AnReZa** [comment]
It didn't do that. I added a key anyways just to make sure, that no such problems might arise in the future.
