### ISSUE TITLE
table SCSS: warning with autoprefixer `grid: true` option - IE11

### ISSUE THREAD

**Issue by hidekatsu-izuno** [bootstrap-vue/bootstrap-vue#3307]
I use bootstrap-vue with nuxt. One of the target browsers for my app is IE11.
So I have to write "grid: true" in a postcss autoprefixer option section. 

```javascript
postcss: {
    preset: {
        autoprefixer: {
            grid: true;
        }
    }
},
```

I see a below message in this case.

> (7492:5) grid-gap only works if grid-template(-areas) is being used

I think we have to fix like a next code in a src\components\table\_table.scss

```css
- grid-template-columns: 40% auto;
+grid-template: none / 40% auto;
```

**Comment by tmorehouse** [comment]
Yeah, there are known issues with IE11 and grid layout (and some props not being the same compared to other modern browsers).

We would have to visually test this across various browsers to see if it works.

**Comment by tmorehouse** [comment]
It appears that IE 11 does not apply the grid styling to psuedo elements (which is how we generate the cell heading on the left)

**Comment by tmorehouse** [comment]
So in order to support "grid" layout, we have to forgo using `grid` layout and fallback to using `float: left` for the cell header.
