### ISSUE TITLE
b-nav-item / b-link problem with HMR

### ISSUE THREAD

**Issue by KuroThing** [bootstrap-vue/bootstrap-vue#331]
While testing out the `b-navbar` component and messing with vue-router's `:to` attribute, i noticed a really weird behaviour.

At first i noticed that trying to do an object based link via the name property (like `:to="{name: 'home'}"`), it produced a link like `localhost/[object Object]`. From there i just assumed that it was failing to pass the object to the internal `router-link` correctly, so i just switched to a simple string (Like `to="/"`).

However, when messing around seeing how hard it would be to replicate the behaviour of the `b-nav-item` component using the `router-link` component, i noticed that the link started working properly when i copied the configuration from `router-link` to `b-nav-item`, but only when the component was injected via HMR...

I'm not entirely sure on what the exact reproduction steps are, however it appears to be a combination of Hot Module Reloading, and editing the `:to` property of the `b-nav-item`

**Comment by pi0** [comment]
@KuroThing Thanks. Seems positive bug. It would be so nice if you could share us a *playground* snippet. as we can then use it to test HMR behavior too.

**Comment by KuroThing** [comment]
I assume you mean the JS Fiddle from exporting it in the playground?

If so, here you go: https://jsfiddle.net/y4bfo5da/

**Comment by tmorehouse** [comment]
Hmm THis might be how BS-vue is detecting the "to" destination.

I think the in the code it checks for `to` being a string (link), or if `to` is an object it uses `to.path`.

The `b-link` code might need to be refactored to check for named paths.

**Comment by KuroThing** [comment]
The change made in https://github.com/bootstrap-vue/bootstrap-vue/commit/dd9425bb6b346241f3572e8c692cdc1f0422d605 is resulting in `<a href ...>` being generated?

The click event still works, but it requires the javascript event to operate correctly.

**Comment by pi0** [comment]
@KuroThing Yep, router-link will automatically add href prop. There are two conditions:

- If you are using SSR then hrefs are already generated before JS loading
- If you are not, then JS still needs to generate first html markup which also includes proper href :))

**Comment by KuroThing** [comment]
but you are setting the href to an empty string by [default](https://github.com/bootstrap-vue/bootstrap-vue/blob/dd9425bb6b346241f3572e8c692cdc1f0422d605/lib/components/link.vue#L35-L38)? This means that it'll never generate the proper href?

**Comment by pi0** [comment]
You are right. fixed.

**Comment by mosinve** [comment]
May be it will be better to bring back href and make `href `and `to` an alternatives to each other, i.e, if defined href, then to=undefined, and vice versa?

**Comment by pi0** [comment]
@mosinve The main idea behind using hrefString fallback was SSR problems with older vue-router. There are more than problems than its benefits forcing href or deduction it's value based on to prop. (For example it causes invalid links when we are prefixing urls)
