### ISSUE TITLE
Table empty text is not showing

### ISSUE THREAD

**Issue by jatarga** [bootstrap-vue/bootstrap-vue#3311]
### Describe the bug

Table custom empty text is not showing.

### Steps to reproduce the bug

1. Go to [...]
2. Click on [...]
3. Scroll down to [...]

### Expected behavior

Show custom empty text in <b-table>.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.16
- Bootstrap: 4.3.1
- Vue: 2.6.19

**Environment:**

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: 

### Additional context

The code that renders table:

```html
<b-table
      show-empty
      :items="getFilteredItems"
      :fields="fields"
      :current-page="currentPage"
      :per-page="perPage"
      class="mb-1"
      :busy="busy"
      empty-text="asd"
      empty-filtered-text="asd2"
    >
......
</table>
```

I'd expect to see "asd" but I'm showing "There are no records to show". What can be the problem?

Thanks!

**Comment by tmorehouse** [comment]
Could you provide a minimal reproduction with JSFiddle or similar?  you can export an example from the [docs playground](https://bootstrap-vue.js.org/docs/components/table)

You should also try upgrading to a newer version of BootstrapVue (i.e. 2.0.0-rc.20)

**Comment by jatarga** [comment]
First I'll try to update, thanks for your suggestion.

**Comment by jatarga** [comment]
It was an issue in my side, sorry and thanks again!
