### ISSUE TITLE
The change to use portal-vue in b-modal should be marked as a breaking change

### ISSUE THREAD

**Issue by aryehsanders** [bootstrap-vue/bootstrap-vue#3314]
By rendering in a different position in the DOM, existing CSS can break.

We have an app in which the user can switch languages. When the user uses a right-to-left language, a lot of layout changes. In RTL mode, we set a class on the top <div> in App.vue, and write our CSS to use that class. For instance:
```
.some-class { margin-left: 20px }

.rtl .some-class { margin-left: 0; margin-right: 20px }
```

Our layout suddenly changed for one developer, because our package.json specified "^2.0.0-rc.19", and when they ran npm install, they received rc.20. The modals are no longer descendants of the top element of our Vue instance, so the `.rtl` class no longer applies to the modals. While there are many ways to work around the problem, it would be better if this were treated as a breaking change.

**Comment by tmorehouse** [comment]
We might be able to find a way to append the modal target to the app's $root.el, but that can cause issues if the app re-renders and trashes the portal-target.

Open option would be to place your `rtl` class on the `<body>` element instead of the app root element (`document.body.classList.add('rtl')`.  as your issue would also affect the likes of tooltips/popovers and toasts, which are all appended to the document body.

One option we might be able to add is to allow the user to place the modal-target component (which is currently an internal only component) in their app, to specify where modal's will be appended.

**Comment by tmorehouse** [comment]
Also, to get the previous behaviour (rendering in place in the DOM where the `<b-modal>` component is placed), just set the `static` prop on `<b-modal>`, and portal-vue will not be used.

**Comment by tmorehouse** [comment]
Usage of modal hasn't changed (all the functionality is there and prop usage hasn't changed, with a few new props added), so it's technically not a true "breaking change" (and it is mentioned in the release notes and documentation that it now renders appended to body via portal-vue).

Rendering appended to body has been an request that has been asked for quite a while, and gets rid of some of the rendering issues associated with being placed inside relatively positioned containers, or containers that scroll.

**Comment by aryehsanders** [comment]
Thanks for the quick response, and thanks for all your work in general!

I agree that the new functionality is a better default. It just took a fairly long time debugging what had happened, since we hadn't expected that we'd need to pin to a specific version of bootstrap-vue in the series of rc releases - I had expected that upgrading would be "safe", and it wasn't. Now that we figured out what happened, you're right, we can simply put `static` in each of our `<b-modal>`s, and everything is fixed. I am mostly advocating for semver-style changes in version numbers so that I'd know to expect that an upgrade might not be safe.

Also, I really like the suggestion you made to allow us to place the modal-target component - that would give us all the benefits of the new portal design and still have the component within the DOM controlled by Vue.

**Comment by tmorehouse** [comment]
Currently the modal-target (`<b-modal-target>`) is not exported, but it shouldn't be too difficult to get it exported and add some documentation about it.  It works similar to the `<b-toaster>` component, except doesn't accept a name (there can only be one modal target in the DOM).  It does check for existence of another modal-target and wont render if one is detected.  and normally it is only created when the first modal is opened, so manually placing one in the app root should work (as long as it doesn't get destroyed during a route change)

**Comment by tmorehouse** [comment]
Re, versioning... once we have this marked as stable, we'll be following full semver versioning, and hopefully have a quicker release cycle as well for fixes (patch), and new features/changes in a minor release

**Comment by tmorehouse** [comment]
The one last major change before 2.0.0 stable will be the migration of tooltips/popovers to use portal-vue (one on-demand, self destructing, portal-target per tooltip/popover)
