### ISSUE TITLE
<b-alert> not showing inside <b-modal>

### ISSUE THREAD

**Issue by felix-voicehub** [bootstrap-vue/bootstrap-vue#3317]
### Describe the bug

An alert inside a modal does not get rendered.

### Steps to reproduce the bug

Put an alert inside a modal. The modal will be empty when it shows.

### Expected behavior

The alert should show in the modal.

### Versions

**Libraries:**

- BootstrapVue: latest
- Bootstrap: latest
- Vue: latest

**Environment:**

- Device: Mac
- Browser: Chrome
- Version: RC20

### Demo link

Can't get a modal to show at all on Codepen/Jsfiddle. Not sure why.

**Comment by tmorehouse** [comment]
It is working for me... here is a fiddle: https://jsfiddle.net/b7coaj0t/
