### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by RupertAvery** [bootstrap-vue/bootstrap-vue#3318]
b-spinner is no longer available in the latest package

There is no mention of this on the relevant page

https://bootstrap-vue.js.org/docs/components/spinner/

**Comment by tmorehouse** [comment]
I'm not sure what you mean by "not available"

Make sure you are using the latest version of BootstrapVue and Bootstrap 4.3.1 CSS

Here is a fiddle showing spinners: https://jsfiddle.net/ow0cr6kq/

**Comment by tmorehouse** [comment]
@RupertAvery Could you provide some sample markup for how you are importing/using the component?
