### ISSUE TITLE
Size of button-group not affecting contained buttons

### ISSUE THREAD

**Issue by tornography** [bootstrap-vue/bootstrap-vue#332]
```
<b-button-group size="small">
    <b-button>text</b-button>
</b-button-group>
```

generates

```
<div role="group" class="btn-group btn-group-small">
    <button class="btn btn-secondary btn-md">text</button>
</div>
```

Expectation:
Buttons get `btn-sm` as well. Additionally `size` options of `b-button-group` should be `sm`, `md `or `lg `to be consistent.

**Comment by tmorehouse** [comment]
Hmmm.  Based on the V4 BS Docs, size only needs to be placed on the `btn-group` (and no size on the inner buttons).  The inner buttons should inherit the size from the `btn-group`.

See https://v4-alpha.getbootstrap.com/components/button-group/#sizing

 In the current version, this should work:

```html
<b-button-group size="sm">
    <b-button>text</b-button>
    <b-button>text</b-button>
    <b-button>text</b-button>
</b-button-group>
```

which generates:

```html
<div role="group" class="btn-group btn-group-sm">
    <button class="btn btn-secondary">text</button>
    <button class="btn btn-secondary">text</button>
    <button class="btn btn-secondary">text</button>
</div>
```

See fiddle https://jsfiddle.net/tmorehouse/6fjodwrp/

**Comment by pi0** [comment]
I've removed hardcoded `md` default. So generated html will be more clear.
