### ISSUE TITLE
Is there a sidebar component?

### ISSUE THREAD

**Issue by jose-pr** [bootstrap-vue/bootstrap-vue#3324]
Is there a sidebar component or what would be the recommended way to create a side navbar? that can also show/hide?

**Comment by derevandal** [comment]
I think you can use [list group](https://bootstrap-vue.js.org/docs/components/list-group/#list-group) or [nav with vertical-variation](https://bootstrap-vue.js.org/docs/components/nav/#vertical-variation).

**Comment by tmorehouse** [comment]
And then use positioning (i.e. sticky or absolute) on an outer wrapper element (i.e. a `div`) around the `b-nav`, and conditionally show it (`v-if`, or `v-show`) based on some state variable

**Comment by jose-pr** [comment]
Will look into it wanted tor recreate a sidenav like https://startbootstrap.com/previews/sb-admin-2/ or https://keenthemes.com/keen/preview/demo1/

**Comment by andreascai** [comment]
> I think you can use [list group](https://bootstrap-vue.js.org/docs/components/list-group/#list-group) or [nav with vertical-variation](https://bootstrap-vue.js.org/docs/components/nav/#vertical-variation).

How about `type` and `variation` like navbar? I'm new to this

**Comment by aventrax** [comment]
I'd like having a toggable sidebar too.

**Comment by FreddyCrugger** [comment]
Any news on this please?

**Comment by platoputhur** [comment]
I would love to have this

**Comment by imakeinternet** [comment]
+1
