### ISSUE TITLE
<b-progress-bar> seems to stop working with html entity number

### ISSUE THREAD

**Issue by nabilzhafri** [bootstrap-vue/bootstrap-vue#3333]
### Describe the bug

This used to work, but with recent changes, `b-progress-bar` seems to stop working properly with html entity number. It's still working fine with html entity name. Current workaround is to use `label-html` prop instead.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/progress/#custom-progress-label
2. Double click on the editor
3. Update the 2nd progress bar's value to contain some html entity name. For example: `&#37;` (%), `&#38;` (&)
4. See the progress bar value, instead of showing the html character i.e. % or &, it's showing the html entity number instead i.e. `&#37;` or `&#38;`

### Expected behavior

It should display the actual html character instead of the html entity number

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.20
- Bootstrap: 4.3.1
- Vue: 2.6.10

### Additional context

![image](https://user-images.githubusercontent.com/6986883/58015752-a2b51800-7b2e-11e9-9b83-dada6295d380.png)

**Comment by jackmu95** [comment]
@nabilzhafri When using the `label` prop the content is set as `textContent` which escapes HTML entities. Please use the `label-html` prop instead which set's the content via `innerHTML`.

**Comment by jackmu95** [comment]
We introduced major security adjustments with **v2.0.0-rc.12** to prevent XSS attacks.
See #2479.

**Comment by nabilzhafri** [comment]
That explains, thanks! @jackmu95 but might need to update the documentation instead since the documentation says label prop does support html (https://bootstrap-vue.js.org/docs/components/progress/#custom-progress-label) A lil confusing there.
