### ISSUE TITLE
modal : not working when upgrading from 2.0.0-rc.13

### ISSUE THREAD

**Issue by tristanbes** [bootstrap-vue/bootstrap-vue#3334]
### Describe the bug

The modal is no longer showing. I even tried installing your version with this patch (https://github.com/bootstrap-vue/bootstrap-vue/pull/3326) but the modal still doesn't show. It was working well in 2.0.0-rc.13

The console shows no error, and the event in vue tab on the debugger has no event.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.20
- Bootstrap: 4.3.1
- Vue: 2.6.6

### Context

I stripped down the code to

```js
<template>
    <button v-b-modal="'my-modal'">Show Modal</button>

    <b-modal id="my-modal" hide-footer>
    <template slot="modal-title">
      Using <code>$bvModal</code> Methods
    </template>
    <div class="d-block text-center">
      <h3>Hello From This Modal!</h3>
    </div>
    <button class="mt-3" block @click="$bvModal.hide('bv-modal-example')">Close Me</button>
  </b-modal>
</template>

<script>

  import axios from 'axios';
  import { BModal } from 'bootstrap-vue/es/components'
  import { BFormInput } from 'bootstrap-vue/es/components'
  import { vBModal } from 'bootstrap-vue/es/directives'

  export default {
    directives: {
      'b-modal': vBModal,
    },
    components: {BModal, BFormInput},

    // ... irrevelant code
   }

```

I tried to update because I was using the following hack and i read that you now use portal vue to fix that problem.
```js
mounted() {
  document.body.appendChild(this.$refs.confirmationModaleRef.$el);
},
```

**Comment by jackmu95** [comment]
@tristanbes The docs show the wrong import name for the directive which should be `VBModal` instead of `vBModal`.

**Comment by tristanbes** [comment]
Thank you.
