### ISSUE TITLE
B-TABS SELECTION BLUE.

### ISSUE THREAD

**Issue by renanbarbalho** [bootstrap-vue/bootstrap-vue#3337]
Hello folks.
I'm using b-tabs component and I saw a behavior strange when I clicked in b-tab the bootstrap created a blue selection in my item, how to do disable this selection/blue marker around my tab-item?

**Comment by tmorehouse** [comment]
That is the focus ring, there for screen reader users so that they can focus the content to have it read out.

**Comment by renanbarbalho** [comment]
It's possible disable?

**Comment by tmorehouse** [comment]
You can turn off keyboard nav for tabs, or set some custom CSS for `outline: none;`

**Comment by renanbarbalho** [comment]
Thanks, this solve my case.
