### ISSUE TITLE
Error adding plugin

### ISSUE THREAD

**Issue by OblivionSY** [bootstrap-vue/bootstrap-vue#3338]
### Describe the bug

As soon as I include the Vue.Use(BootstraVue) I get TypeError: can't assign to property "installed" on true: not an object in my webpack vendor bundle. 

### Steps to reproduce the bug

1. I have installed Vue js and confirmed working OK
2. Come to addBootstrap Vue in and get the error. 
3. Installed via npm install Bootstrap
4. Configure the Webpack 
vendor: [ 
...
"bootstrap/dist/css/bootstrap.min.css",
  "bootstrap-vue",
]

### Versions

**Libraries:**

- Bootstrap-Vue: 2.0.0-rc.20
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Surface Pro - Visual Studio 2017
- OS: Windows
- Browser: Firefox
- Version: 66.0.4

**Comment by OblivionSY** [comment]
Webpack Configuration: 
`const path = require("path");
const webpack = require("webpack");
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = env => {
  const isDevBuild = !(env && env.prod);
  const extractCSS = new ExtractTextPlugin("vendor.css");

  return [
    {
      stats: { modules: false },
      resolve: { extensions: [".js"] },
      entry: {
        vendor: [
          "event-source-polyfill",
          "isomorphic-fetch",
          "vue",
          "vue-router",
          "bootstrap/dist/css/bootstrap.min.css",
          "bootstrap-vue",
          "nprogress/nprogress.css"
        ]
      },
      module: {
        rules: [
          {
            test: /\.css(\?|$)/,
            use: extractCSS.extract({
              use: isDevBuild ? "css-loader" : "css-loader?minimize"
            })
          },
          {
            test: /\.(png|woff|woff2|eot|ttf|svg)(\?|$)/,
            use: "url-loader?limit=100000"
          }
        ]
      },
      output: {
        path: path.join(__dirname, "wwwroot", "dist"),
        publicPath: "dist/",
        filename: "[name].js",
        library: "[name]_[hash]"
      },
      plugins: [
        extractCSS,
        new webpack.ProvidePlugin({ $: "jquery", jQuery: "jquery" }), // Maps these identifiers to the jQuery package (because Bootstrap expects it to be a global variable)
        new webpack.DefinePlugin({
          "process.env.NODE_ENV": isDevBuild ? '"development"' : '"production"'
        }),
        new webpack.DllPlugin({
          path: path.join(__dirname, "wwwroot", "dist", "[name]-manifest.json"),
          name: "[name]_[hash]"
        })
      ].concat(isDevBuild ? [] : [new webpack.optimize.UglifyJsPlugin()])
    }
  ];
};
`
Package JSON:
`{
  "name": "PresentsList",
  "private": true,
  "version": "0.0.0",
  "devDependencies": {
    "aspnet-webpack": "^2.0.1",
    "css-loader": "^0.25.0",
    "event-source-polyfill": "^0.0.7",
    "extract-text-webpack-plugin": "^2.0.0-rc",
    "file-loader": "^0.9.0",
    "isomorphic-fetch": "^2.2.1",
    "node-sass": "^4.12.0",
    "sass-loader": "^7.1.0",
    "scss-loader": "0.0.1",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "vue": "^2.2.2",
    "vue-loader": "^11.1.4",
    "vue-router": "^2.3.0",
    "vue-template-compiler": "^2.2.2",
    "webpack": "^2.7.0",
    "webpack-hot-middleware": "^2.12.2"
  },
  "dependencies": {
    "bootstrap-vue": "^2.0.0-rc.20",
    "nprogress": "^0.2.0"
  },
  "scripts": {
    "vendor": "webpack --config webpack.config.vendor.js && webpack"
  }
}
`
![image](https://user-images.githubusercontent.com/3511993/58050404-2d097600-7b47-11e9-8a61-0ae9753260c7.png)

**Comment by OblivionSY** [comment]
Thank you for addressing the issue so rapidly. As a workaround, I used:

```
//import BootstrapVue from "bootstrap-vue";
import BootstrapVue from "bootstrap-vue/dist/bootstrap-vue.esm";
```

rather than the commented out line. This seemed to work. I assume that when rc21 is released, I can revert to the initial import?

**Comment by tmorehouse** [comment]
Version 2.0.0-rc.21 has been released
