### ISSUE TITLE
I can't select element by class which bootstrap generate 

### ISSUE THREAD

**Issue by kangchals** [bootstrap-vue/bootstrap-vue#3344]
### Describe the bug

It might be not bug but the situation is very inconvenient.

I cann't style elements using class when the ones generated by bootstrap.

I am using nuxt most recent version with scss.

### Steps to reproduce the bug

1. set class on b-form-checkbox
2. select label in b-form-checkbox ( bootstrap auto generating )
3. styles on label not applied

below is the example codes
```
//on html
<b-form-checkbox
        v-for="option in optionsMaterial"
                  :key="option.value"
                  v-model="selectedMaterial"
                  :value="option.value"
                  name="flavourMaterial"
                  class="col-4 materialCheckbox"
                  inline
  >
              {{ option.text }
</b-form-checkbox>
```
```
// on scss
.materialCheckbox {
   label { // auto generated ones
     // it won't work
   }

}
```

### Expected behavior

style should be applied

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.15
- Bootstrap: 4.#.# ,,,
- Vue: 2.6.10

**Environment:**

Mac chrome...

**Comment by jackmu95** [comment]
@kangchals I've created an example and it's working as it should:
https://codesandbox.io/s/modest-germain-sfoqw

**Comment by jackmu95** [comment]
Make sure to update BootstrapVue to the latest version.

**Comment by kangchals** [comment]
@jackmu95 
`<style lang="scss" scoped>`
I found that when the style is scoped, it is not working....

Can you give me some reason? why is scoped style cannot applied??

**Comment by tmorehouse** [comment]
Scoped styles insert a special HTML attribute on the HTML elements within your custom component, and modifies your style rules to be targeted to the special attribute value.

 Vue doesn't add these 'scope' attributes to the sub-elements of components inside your template (this is the same with any nested custom component you may use, even your own custom components).

It is an upstream (i.e. Vue) thing.
