### ISSUE TITLE
Alert - alerts unexpectedly transitioned and removed

### ISSUE THREAD

**Issue by DM2489** [bootstrap-vue/bootstrap-vue#3346]
### Describe the bug

When an alert begins with a countdown, but it's `show` property is changed to `true` before the countdown expires, the alert is transitioned and then removed unexpectedly.

### Steps to reproduce the bug

1. Go to https://codesandbox.io/s/qeghj
2. Observe the countdown timer reduce a few times
3. Before the countdown expires, press the button to make `show === true`
4. Watch as the alert transitions away and is then removed from the dom

### Expected behavior

The alert should remain visible when `show` is changed from an integer value to `true`.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.20
- Bootstrap: 4.3.1
- Vue: 2.6.10

https://codesandbox.io/s/qeghj

**Comment by tmorehouse** [comment]
PR #3347 addresses this, and will be available in the next release

**Comment by DM2489** [comment]
Awesome, thank you so much @tmorehouse!
