### ISSUE TITLE
Popover flip disable option

### ISSUE THREAD

**Issue by PeterPorzuczek** [bootstrap-vue/bootstrap-vue#3348]
Is there a way to disable popover flipping? I couldn't find it in source code, why you didn't implement it?

**Comment by tmorehouse** [comment]
You can use the `fallbackPlacement` property in the config object when using the directive version:

```html
<b-button
  v-b-popover.top.click="{
    title: 'Popover',
    content: 'This is the content of popover',
    fallbackPlacement: ['top']
  }"
  variant="success"
 >
   Config Object
</b-button>
```

**Comment by PeterPorzuczek** [comment]
Thank you for quick fix :)
