### ISSUE TITLE
Docs update: compatible components with vue-router

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#335]
### Docs

After working through building a nav, I decided I needed to use vue-router. I was struggling with how to compose the `<router-link />` component, so I searched the docs and issues for info.

It looks like the `<b-link />` component is fully compatible with vue-router (awesome! 🎉 ), but there is very little documenting using these components in that context. I'd be happy to take a stab at documenting that, but it would be nice to know what exactly bootstrap-vue supports.

**Comment by tmorehouse** [comment]
Basically any component that provides a `to` prop will support `router-link`
