### ISSUE TITLE
toasts don't show with an empty content string

### ISSUE THREAD

**Issue by kaipaysen** [bootstrap-vue/bootstrap-vue#3359]
### Describe the bug
When I [request a toast on demand](https://bootstrap-vue.js.org/docs/components/toast/#toasts-on-demand) with an empty content string no toast shows up.

### Steps to reproduce the bug

1. Go to [https://jsfiddle.net/byu8n5s7/1/](https://jsfiddle.net/byu8n5s7/1/)
2. Click on Button "Click Me" see toast appearing
3. Clear Inputbox
4. Click on Button "Click Me" see no toast appearing

### Expected behavior
A Toast should appear even when the content is an empty String. There's a title!

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.20
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: [Mac]
- OS: [latest]
- Browser: [Chrome]
- Version: [latest]

### Demo link
[https://jsfiddle.net/byu8n5s7/1/](https://jsfiddle.net/byu8n5s7/1/)

**Comment by tmorehouse** [comment]
That is as designed.  The toast message is required (title is optional)

**Comment by kaipaysen** [comment]
It might be worth to add this design decision to the docs. As a workaround I just created a wrapper like this:

```
   appendMessageSuccess: function(title, text) {
            // https://github.com/bootstrap-vue/bootstrap-vue/issues/3359
            text  = text  || " ";
            this.$bvToast.toast(text, {
                title: title,
                variant: "success",
                autoHideDelay: 15000,
                appendToast: true
            });
        },
```

**Comment by tmorehouse** [comment]
You could do it this way as well:

```js
            this.$bvToast.toast(text || ' ', {
                title: title,
                variant: "success",
                autoHideDelay: 15000,
                appendToast: true
            });
```
