### ISSUE TITLE
Allow clearing multi select values

### ISSUE THREAD

**Issue by Biktorgj** [bootstrap-vue/bootstrap-vue#3360]
When using <b-form-select> with the Multiple attribute, you can select one or more choices, but it seems there's no way to clear the selection completely (or at least I didn't find it in the documentation)

When only one item is selected in a b-form-select multi, and the user clicks the selected option, it would be nice if it removed the selection, effectively clearing the v-model array

Right now the only way I've found to achieve this is placing a button next to the form field to clear the array, but it is counter intuitive and doesn't look very well.

**Comment by tmorehouse** [comment]
`b-form-select` is actually a native browser `<select>` element, with styles applied to it.

What you are seeing is native browser `<select>` behaviour.

If you want a `null` value, provide an option at the top of the list with a value of `null` with text such as `-- please select one or more optons --`
