### ISSUE TITLE
<b-tabs> loss of <b-tab> control as of rc20 when used in  modals

### ISSUE THREAD

**Issue by rich25200** [bootstrap-vue/bootstrap-vue#3361]
### Describe the bug

If you put b-tabs inside of a modal, upon opening the modal for the first time everything works fine, but if you close the modal and reopen it, then the tabs don't work, it will be stuck on the content of the first tab, and switching tabs will not have any effect, instead the content of the first tab will remain visible. Reloading the page is the only way to get it to work again.

### Steps to reproduce the bug

https://jsfiddle.net/gh9y7zLs/2/

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.20
- Bootstrap: 4.0.0
- Vue: 2.6.10

**Environment:**

- Browser: All

**Comment by F-Node-Karlsruhe** [comment]
Just experienced the same. Here is some easy replication code.

```
<div>
<b-button v-b-modal.modal-1>Click</b-button>
<b-modal id="modal-1">
  <b-tabs content-class="mt-3">
    <b-tab title="First" active><p>I'm the first tab</p></b-tab>
    <b-tab title="Second"><p>I'm the second tab</p></b-tab>
  </b-tabs>
</b-modal>
</div>
```

**Comment by tmorehouse** [comment]
Hmm... strange that this issue is back. will have to investigate.  Confirmed in the latest `dev` branch as well 

https://deploy-preview-3289--bootstrap-vue.netlify.com/

**Comment by F-Node-Karlsruhe** [comment]
Yes, I can confirm the same behavior in the latest version.

Am 23.05.2019 um 14:38 schrieb T Morehouse <notifications@github.com<mailto:notifications@github.com>>:


Hmm... strange that this issue is back. will have to investigate. Confirmed in the latest dev branch as well

https://deploy-preview-3289--bootstrap-vue.netlify.com/

**Comment by tmorehouse** [comment]
For a workaround, set the `static` prop on `<b-modal>` and do not use the `lazy` prop.

**Comment by F-Node-Karlsruhe** [comment]
Works with static, but now the modal pops up again right after you close it^^

Am 23.05.2019 um 15:45 schrieb T Morehouse <notifications@github.com<mailto:notifications@github.com>>:

static

**Comment by tmorehouse** [comment]
@F-Node-Karlsruhe I didn't see that issue (modal popping up again on close) when I confirmed the issue and tried the `static` prop

**Comment by rich25200** [comment]
Static prop is working.
