### ISSUE TITLE
Get multiple b-modal dynamically created with different IDs

### ISSUE THREAD

**Issue by akelesis** [bootstrap-vue/bootstrap-vue#3365]
Hi,
I need to get a list of clients with axios and display some info in a table, in order to make it I'm using b-table. each line has a button (I inserted with a 'field') I need to show a modal with all the info about the client when I click it. I can't make it work with multiple registers in the page. I've already tried doing <b-button variant="warning" @click="loadUser(data.item)" v-b-modal="'id'+client.id"></b-button> and <b-modal :id="'id'+client.id" :title="..."> but doesn't work  😭 

Please, if someone can help I'd be really glad! 😄

**Comment by tmorehouse** [comment]
Rather than creating multiple modals, you should create one single modal (with an ID), whose content is tied to some data value.

Then your button click handler would load the data, and once loaded and data is updated, then show the modal using `this.$bvModal.show(id)` (where `id` is the ID of the modal).

```html
<template>
  <b-table :items="items" .:fields="fields" ...>
    <template slot="actions" slot-scope="{ item }">
      <b-button @click="showClientDetails(item.clientId)">Client Details</b-button>
    </template>
  </b-table>
  <b-modal id="client-details-modal" @hidden="clearClientData">
    <ul>
      <li>ID: {{ client.id }}</li>
      <li>Name: {{ client.name }}</li>
      <li>Address: {{ client.address }}</li>
    </ul>
  </b-modal>
</template>

<script>
export default {
  data() {
    // Object where we store client info from Axios
    client: {}
  },
  methods: {
    clearClientData() {
      this.client = {}
    },
    showClientDetails(id) {
      axios.get('/customer', { params: { ID: id } })
      .then(response => {
        // Store the response data
        this.client = response.data
        // Show the modal
        this.$bvModal.show('client-details-modal')
      })
      .catch(function (error) {
        alert('Error retrieving client information');
      })
    }
  }
}
</script>
```

**Comment by akelesis** [comment]
So... I tried this solution, in fact I delayed my answer because I was testing it in many different ways in order to come here with a positive result and unfortunately it didn't work... Now the modal appears but no info inside and I have no idea whats happening... I'll send my complete code and if someone sees anything I'm not seeing I'll be grateful.

<template>
  <div class="client-adm">
    <b-table hover striped :items="clients" :fields="fields">
      <template slot="details" slot-scope="{ item }">
        <b-button variant="warning" @click="loadClientInfo(item)">
          <i class="fas fa-search"></i>
        </b-button>
      </template>
    </b-table>
    <b-modal :id="'modal-1'" @hidden="clearClientInfo">
      <p>Nome: {{client.id}}</p>
      <p>E-mail: {{client.email}}</p>
      <p>Telefone: {{client.telephone}}</p>
      <p>CPF: {{client.cpf}}</p>
      <p>Endereço: {{client.city}}, bairro {{client.neighborhood}}, {{client.street}} nº {{client.number}}</p>
    </b-modal>
  </div>
</template>

<script>
import { baseApiUrl } from "@/global.js";
import axios from "axios";
export default {
  name: "ClientsAdmin",
  data() {
    return {
      client: {},
      clients: [],
      fields: [
        { key: "id", label: "Código", sortable: true },
        { key: "name", label: "Nome", sortable: true },
        { key: "email", label: "Email", sortable: false },
        { key: "telephone", label: "Telefone", sortable: false },
        { key: "details", label: "Detalhes" }
      ]
    };
  },
  methods: {
    loadClients() {
      const url = `${baseApiUrl}/users`;
      axios.get(url).then(res => {
        this.clients = res.data;
      });
    },

    loadClientInfo(item) {
      
      this.client = item.client;
      this.$bvModal.show("modal-1");
    },

    clearClientInfo() {
      this.client = {};
    }
  },
  mounted() {
    this.loadClients();
  }
};
</script>

**Comment by tmorehouse** [comment]
Oops, I accidentally deleted your comment (was just fixing the code formatting and hit the wrong button).

**Comment by akelesis** [comment]
So... I tried this solution, in fact I delayed my answer because I was testing it in many different ways in order to come here with a positive result and unfortunately it didn't work... Now the modal appears but no info inside and I have no idea whats happening... I'll send my complete code and if someone sees anything I'm not seeing I'll be grateful.
```html
<template>
  <div class="client-adm">
    <b-table hover striped :items="clients" :fields="fields">
      <template slot="details" slot-scope="{ item }">
        <b-button variant="warning" @click="loadClientInfo(item)">
          <i class="fas fa-search"></i>
        </b-button>
      </template>
    </b-table>
    <b-modal :id="'modal-1'" @hidden="clearClientInfo">
      <p>Nome: {{client.id}}</p>
      <p>E-mail: {{client.email}}</p>
      <p>Telephone: {{client.telephone}}</p>
      <p>Register: {{client.cpf}}</p>
      <p>Address: {{client.city}}, neighborhood {{client.neighborhood}}, {{client.street}} number {{client.number}}</p>
    </b-modal>
  </div>
</template>
```
```javascript
import { baseApiUrl } from "@/global.js";
import axios from "axios";
export default {
  name: "ClientsAdmin",
  data() {
    return {
      client: {},
      clients: [],
      fields: [
        { key: "id", label: "Code", sortable: true },
        { key: "name", label: "Name", sortable: true },
        { key: "email", label: "Email", sortable: false },
        { key: "telephone", label: "Telephone", sortable: false },
        { key: "details", label: "Details" }
      ]
    };
  },
  methods: {
    loadClients() {
      const url = `${baseApiUrl}/users`;
      axios.get(url).then(res => {
        this.clients = res.data;
      });
    },

    loadClientInfo(item) {
      
      this.client = item.client;
      this.$bvModal.show("modal-1");
    },

    clearClientInfo() {
      this.client = {};
    }
  },
  mounted() {
    this.loadClients();
  }
};
```

**Comment by tmorehouse** [comment]
@akelesis  try this example:  https://jsfiddle.net/3kayb7t1/

**Comment by akelesis** [comment]
> 
> 
> @akelesis try this example: https://jsfiddle.net/3kayb7t1/

It works! haha
Thanks man!! 😄
