### ISSUE TITLE
show() for b-dropdown appears to not work

### ISSUE THREAD

**Issue by nstuyvesant** [bootstrap-vue/bootstrap-vue#3366]
### Steps to reproduce the bug
```
<template lang='pug'>
div
  b-button(@click='loginShow') Show Dropdown
  b-dropdown(id='login-dropdown', ref='dropdown', text='Login')
    b-dropdown-item(to='/login') Login
    b-dropdown-item(to='/signup') Sign up
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator';
import { BDropdown } from 'bootstrap-vue';

@Component
export default class Login extends Vue {

  private loginShow(e: any): void {
    const dropdown = this.$refs.dropdown as BDropdown;
    dropdown.show();
  }
}
</script>
```
Click on "Show Dropdown" button.

### Expected behavior

Dropdown should appear.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.20
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: [Mac]
- OS: [macOS Mojave]
- Browser: [Safari]
- Version: [12.1.1]

### Demo link

See code above.

### Additional context

Thought [feat #1012](https://github.com/bootstrap-vue/bootstrap-vue/pull/1012) was supposed to enable the show() method.

**Comment by tmorehouse** [comment]
You are experiencing a race condition where you are trying to open teh menu, but hte menu sees teh click event of the button first and closes itself.

Wrap your call to `show()` in either a `requestAnimationFrame` or a `setTimeout` (with 0ms delay) to allow time for processing the button click before the menu opens.

https://jsfiddle.net/2tkaym5d/
