### ISSUE TITLE
B-Table set selected rows programmatically

### ISSUE THREAD

**Issue by bomanti** [bootstrap-vue/bootstrap-vue#3370]
Hi,

A feature request;
It will be nice to set selectedRows programmatically.

When i try to set this.$refs.table.selectedRows = [this.selectedItem]; always setting first element of rows

Thank you

**Comment by tmorehouse** [comment]
`selectedRows` is an internal sparse array and should not be used by humans (plus it may change in the future)

Duplicate of #2687 and partially #3064

**Comment by omnigodepot** [comment]
Is there any way to set a selected row in the table?

**Comment by tmorehouse** [comment]
@omnigodepot see https://github.com/bootstrap-vue/bootstrap-vue/issues/2687#issuecomment-466395945 for a way to "click" a row to select it.
