### ISSUE TITLE
Documentation is missing link for latest stable release

### ISSUE THREAD

**Issue by jfadich** [bootstrap-vue/bootstrap-vue#3371]
The version selector does not have the option to select the latest stable version. It just lists "v2.0.0-rc.20" and "Latest". We are not using v2 due to it still being a release candidate. There is no way to view the documentation for the latest stable version which is 1.5.1.

**Comment by tmorehouse** [comment]
1.5.x is no longer maintained (nor do we have the website for it unfortunately)

**Comment by jfadich** [comment]
Is there a timeline for v2 to be released? Presumably even if 1.5 is no longer maintained the documentation should still exist somewhere.

**Comment by tmorehouse** [comment]
You can download v1.5.1 and run the docs locally: https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/v1.5.1

**Comment by tmorehouse** [comment]
We are hoping 2.0.0 stable will be released within a month,

**Comment by jfadich** [comment]
Is there a reason behind the decision to not host the documentation for the **current** version of this package?

**Comment by tmorehouse** [comment]
It would require a separate URL/host, which we don't have.

**Comment by nnmer** [comment]
It seems, that it never gonna be changed to "stable".
Still **adding and changing functionality in the RC**, what in my opinion should not be happening.
If we would follow https://en.wikipedia.org/wiki/Software_release_life_cycle#Release_candidate functionality in RC should not be changed.

**Comment by tmorehouse** [comment]
2.0.0-rc.28 will probably be the last RC release.  Then will be v2.0.0 stable
