### ISSUE TITLE
modal not rendering in unit tests after upgrade to rc.20

### ISSUE THREAD

**Issue by aj-ee** [bootstrap-vue/bootstrap-vue#3373]
### Describe the bug

bModals are not being rendered in our unit tests with shallowMounting with vue-test-utils.

### Steps to reproduce the bug

Demo app created with vue cli:

https://github.com/aj-ee/bv-rc.20

**master** branch uses rc.20 - tests fail.
**rc.19** branch uses rc.19 - tests pass.

You'll need to do an npm install when switching branches.

I'm logging out the wrapper.html() to see what's actually being rendered and there's nothing there for the modal in rc.20.

Is this a bug or have I missed something?

Thanks for the great work so far!

**Comment by aj-ee** [comment]
scratch that - went back & read the docs for b-modal - I see that we now need to add the static prop in order to render the modal even when not visible!

**Comment by yooouuri** [comment]
@aj-ee can you tell me what prop to set?

**Comment by aj-ee** [comment]
> @aj-ee can you tell me what prop to set?

https://bootstrap-vue.js.org/docs/components/modal/#lazy-loading-and-static-modals

you need to set "static" to true

i.e:

<b-modal id="modal-xl" size="xl" title="Extra Large Modal" **:static="true"**>

**Comment by tmorehouse** [comment]
Or simply just:

```html
<b-modal id="modal-xl" size="xl" title="Extra Large Modal" static>
```
