### ISSUE TITLE
Problems with Vee-Validate injection since 2.0.0-rc.20

### ISSUE THREAD

**Issue by JeffBlais418** [bootstrap-vue/bootstrap-vue#3374]
### Describe the bug
Hi!
I'm having issues since we updated the bootstrap-vue package to 2.0.0-rc.20. It seems like vee-validate injection no longer work on b-modal component called from anything else than App.vue. The child get an injected validator but it can't pass the validation errors to the parent like it used to do. Looks like the injected validator is not the one wanted?

It's still working for example like this : the child component validator injected is the one from my ModalComponent, ModalComponent can show the right errors generated by it's child :

![image](https://user-images.githubusercontent.com/47637869/58335901-a25b9c00-7e10-11e9-930b-c8051bd29b83.png)

but not when used like that : the child component validator injected is the one from App.vue, so ModalComponent is never aware of the Child errors.

![image](https://user-images.githubusercontent.com/47637869/58335934-b0a9b800-7e10-11e9-8108-5743dc1c1350.png)

All of this was working prior RC20, Does anyone know what changes in this release could created this issue?

**Libraries:**

- BootstrapVue: 2.0.0-rc.20
- Bootstrap: 4.1.1
- Vue: 2.6.8
- Vee-Validate 2.1.7

**Comment by tmorehouse** [comment]
This will be fixed in 2.0.0-rc.21 (coming soon). It is a side-effect of using Portal-Vue, which we have fied in PR https://github.com/bootstrap-vue/bootstrap-vue/pull/3326

As a workaround, you can set the `static` prop on `<b-modal>` which will retain the parent-child hierarchy.

**Comment by JeffBlais418** [comment]
Awesome thank you for answering me so fast!

**Comment by tmorehouse** [comment]
Version 2.0.0-rc.21 has been released
