### ISSUE TITLE
<b-card>: difficult to use header slot

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#338]
I'm using the card component to create a header with a title and a button, so I want to use the header slot rather that inline too much html in the header prop attribute.

I'm finding the setup to be a little messy. Ideally, I would just be able to use the slot to add more complex markup and be done. I don't mind passing a boolean in for the header to register though, but requiring a string makes it a little awkward. I believe Vue lets you union prop types, so perhaps you could switch this up to `[String, Boolean]`.

I'll include a fiddle to look at. I don't believe you can see the prop validation warnings in the fiddle, but while I'm developing in strict mode, they are quite glaring 😃 

[jsFiddle](https://jsfiddle.net/yu07om1d/5/)

**Comment by tmorehouse** [comment]
Maybe this needs some `v-if` trickery in the `card` component on the header and slot

**Comment by tmorehouse** [comment]
Or... We can test for `$slots['header']` truthiness and use that to determine if a slot has been defined by the user.

I did this trick in the `b-table` enhancements for the scoped footer slots (and if not defined, tries using the scoped header slot instead).

**Comment by tmorehouse** [comment]
Actually, looking ath te `card` component template:

```js
        <!-- Card Header-->
        <component v-if="header || showHeader" :is="headerTag" class="card-header">
            <slot name="header">
                <div v-html="header"></div>
            </slot>
        </component>
```

you could just set `show-header` on the card, and then provide your `header` slot template.

**Comment by tmorehouse** [comment]
Or it could be simplified (and no need for the `showHeader` prop:

```html
<component v-if="header || Boolean($slots['header'])" :is="headerTag" class="card-header">
    <slot name="header">
        <div v-html="header"></div>
    </slot>
</component>
```

And if the user has defined a `header` slot, (but left `header` prop empty/null) then it will show it.

**Comment by tmorehouse** [comment]
I could add this to PR #463

**Comment by tmorehouse** [comment]
https://jsfiddle.net/yu07om1d/6/

**Comment by tmorehouse** [comment]
We could also do something similar to the card footer slot:

```html
<component v-if="footer || $slots['footer']"
           :is="footerTag"
           :class="['card-footer', footerVariant?('bg-'+footerVariant):'', footerClass]"
>
    <slot name="footer">
        <div v-html="footer"></div>
    </slot>
</component>
```

And not have a need for the prop `show-footer`.

**Comment by alexsasharegan** [comment]
Up in the mountains this weekend, so spotty internet. The `show-header` prop works well! I do think that ideally utilizing the header/footer slow triggers the show.

**Comment by tmorehouse** [comment]
slow triggers?

**Comment by tmorehouse** [comment]
I'll create a PR that switched to looking for the header and/or footer slots
