### ISSUE TITLE
ref stops working inside <b-modal>

### ISSUE THREAD

**Issue by nabilzhafri** [bootstrap-vue/bootstrap-vue#3380]
### Describe the bug

Prior to 2.0.0-rc.20, putting `ref` to a component inside `<b-modal>` used to work fine. But when using 2.0.0-rc.20, the `ref` inside `b-modal` seems to be not available

```javascript
<template>
  <div class="hello">
    <b-modal ref="modal">
      <HelloOtherWorld ref="otherWorld"/>
    </b-modal>
  </div>
</template>
```

Based on example, the ref to the `<HelloOtherWorld />` won't be available i.e. `this.$refs.otherWorld` is undefined

### Steps to reproduce the bug

1. Go to https://codesandbox.io/s/vue-template-do1xs
2. Click on the "Open Other World" button
3. See the message that says it's not working
4. Check for console error, you can see `this.$refs` doesn't contain the component
5. If you change to BootstrapVue 2.0.0-rc.19, it'll work

### Expected behavior

The ref to a component inside `<b-modal>` should work and available in `this.$refs`

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.20
- Bootstrap: 4.3.1
- Vue: 2.5.22

### Demo link

https://codesandbox.io/s/vue-template-do1xs

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-do1xs?fontsize=14)

**Comment by jackmu95** [comment]
With RC20 we changed the way how modals are rendered.
They are only attached to the DOM when they get shown, so the `$refs` are only accessible then.

If you want the old behavior and want the modal to be rendered all the time, use the `static` prop.
