### ISSUE TITLE
Typings bug from rc20 to rc21

### ISSUE THREAD

**Issue by JFGHT** [bootstrap-vue/bootstrap-vue#3390]
### Describe the bug

Bug with typings after upgrading from `2.0.0-rc20` to `rc21`:

```
Cannot extend an interface 'BvComponent'. Did you mean 'implements'?
    10 | 
    11 | // Component: b-alert
  > 12 | export declare class BAlert extends BvComponent {
```

This is happening with a lot of components.

**Comment by tmorehouse** [comment]
@JFGHT, when you say "This is happening with a lot of components", is it all components, or particular ones?

**Comment by tmorehouse** [comment]
Since the core team doesn't have any great epereince with TypeScript, suggestions are welcomed.

Maybe in `src/index.d.ts` / `es/index.d.ts` we need to alter this:

```ts
// Component base definition
export interface BvComponent extends Vue {
  // Simple catch-all to allow any prop/type
  [key: string]: any
}
```

to this

```ts
// Component base definition
export class BvComponent extends Vue {
  // Simple catch-all to allow any prop/type
  [key: string]: any
}
```

**Comment by tmorehouse** [comment]
or possibly:

```ts
// Component base definition
export class BvComponent implements Vue {
  // Simple catch-all to allow any prop/type
  [key: string]: any
}
```

**Comment by JFGHT** [comment]
Sorry for answering this late. I'll try whenever I can but can't promiss too much.

**Comment by tmorehouse** [comment]
I looked at another project that is similar, and they did  the above changing `interface` to `class` for their component base declaration.

```ts
// Component base definition
export class BvComponent extends Vue {
  // Simple catch-all to allow any prop/type
  [key: string]: any
}
```

**Comment by demianh** [comment]
I have the same problem, and it seems the change from `interface` to `class` does the trick.

**Comment by tmorehouse** [comment]
@demianh thanks for helping out! will adjust the PR accordingly.

**Comment by rrittwag** [comment]
I confirm both fixes, the change to `class BvComponent` and the added type argument for `BvPlugin`.

**Comment by tmorehouse** [comment]
Other than those two issues, does all else appear to work OK re types?

**Comment by demianh** [comment]
i only tested with the modal component, but so far i have not encountered other issues 👍

**Comment by tmorehouse** [comment]
Fix will be available in v2.0.0-rc.22 when released.

**Comment by nstuyvesant** [comment]
Here are all the ones I've imported that were fixed by changing BvComponent to a class and adding `<BvConfigOptions>` to the end of `export interface BvPlugin extends PluginObject`:

```ts
import Badge from 'bootstrap-vue/es/components/badge';
import Button from 'bootstrap-vue/es/components/button';
import ButtonGroup from 'bootstrap-vue/es/components/button-group';
import Carousel from 'bootstrap-vue/es/components/carousel';
import Collapse from 'bootstrap-vue/es/components/collapse';
import Dropdown from 'bootstrap-vue/es/components/dropdown';
import Form from 'bootstrap-vue/es/components/form';
import FormInput from 'bootstrap-vue/es/components/form-input';
import FormCheckbox from 'bootstrap-vue/es/components/form-checkbox';
import FormGroup from 'bootstrap-vue/es/components/form-group';
import FormRadio from 'bootstrap-vue/es/components/form-radio';
import FormTextarea from 'bootstrap-vue/es/components/form-textarea';
import Image from 'bootstrap-vue/es/components/image';
import InputGroup from 'bootstrap-vue/es/components/input-group';
import Link from 'bootstrap-vue/es/components/link';
import Modal from 'bootstrap-vue/es/components/modal';
import Nav from 'bootstrap-vue/es/components/nav';
import NavBar from 'bootstrap-vue/es/components/navbar';
Vue.use(Badge);
Vue.use(Button);
Vue.use(ButtonGroup);
Vue.use(Carousel);
Vue.use(Collapse);
Vue.use(Dropdown);
Vue.use(Form);
Vue.use(FormCheckbox);
Vue.use(FormInput);
Vue.use(FormGroup);
Vue.use(FormRadio);
Vue.use(FormTextarea);
Vue.use(Image);
Vue.use(InputGroup);
Vue.use(Link);
Vue.use(Modal);
Vue.use(Nav);
Vue.use(NavBar);
```

**Comment by cybercussion** [comment]
Those imports appear deprecated in the docs.  Though I do not know what the tree-shaking equiv would be without them.  https://bootstrap-vue.js.org/docs/components/table/#comp-ref-b-table-events

**Comment by tmorehouse** [comment]
In release 2.0.0-rc.22 (coming out today hopefully), the above import methods will still work (for now, but have been deprecated in favour of a new simpler approach).

The new method for importing will be just simply:
```js
import {
  // Plugin imports
  ModalPlugin,
  LinkPlugin,
  NavbarPlugin,
  // Directive plugin imports
  VBTooltipPlugin,
  // Individual component imports
  BButton,
  BAlert,
  // Directive imports (if not using the directive's plugin 
  VBScrollspy
} from 'bootstrap-vue'

Vue.use(ModalPlugin)
Vue.use(LinkPlugin)
Vue.use(NavbarPlugin)
Vue.use(VBTooltipPlugin)
Vue.component('b-button', BButton)
Vue.directive('b-scrollspy', VBScrollspy)
```

Your bundler will either choose the ESM module entryoint (`"module": "esm/index.js"`) which is tree shakeable, or the commonjs entrypoint ("main": "dist/bootstrap-vue.common.js") which is not tree shakeable.  The `es/` build (which is actually a bunch of smaller commonjs bundles) will still be around, but we plan on deprecating that build as it is a pain to keep typed)

The nice thing about this is that the types will automatically be picked up as everything is now a top-level named export.

**Comment by cybercussion** [comment]
ok, yeah I just did a test and the Plugin version was coming in at 367KB but the default export version was 180KB on the parts I was using.  I'll check my setup.  Thanks for the tip.

**Comment by tmorehouse** [comment]
The plugin will include a bit more than just the components.

Making sure your imports are all in a single statement (with the new shorter format coming net release) will provide for better bundle sizes.

**Comment by tmorehouse** [comment]
v2.0.0-rc.22 has been released.
