### ISSUE TITLE
Error in npm build 

### ISSUE THREAD

**Issue by Yogi-p** [bootstrap-vue/bootstrap-vue#3393]
Cannot extend an interface 'BvComponent'. Did you mean 'implements'?

Error keeps firing for all bootstrap-vue/src/components when i updated my package.json through npm update. Previous version was 2.0.0-rc.19 and currently i am facing this issue on update to 2.0.0-rc.21

Before npm update build process was working correct and expected 
can anybody please help me with this.

**Comment by tmorehouse** [comment]
Duplicate: #3390

**Comment by Yogi-p** [comment]
@tmorehouse Even after taking updates issue is not resolved
it is still showing same error for multiple component

**Comment by tmorehouse** [comment]
@Yogi-p the issue is still open, yours is a duplicate of it #3390.

We have closed yours in favour of #3390

**Comment by Yogi-p** [comment]
Great.. Thanks :)
