### ISSUE TITLE
Doc: please add an hint to doc how to change placeholder color in the b-input

### ISSUE THREAD

**Issue by realtebo** [bootstrap-vue/bootstrap-vue#3401]
As from title, please add an hint to doc how to change placeholder color in the b-input

**Comment by tmorehouse** [comment]
That is controlled by Bootstrap V4.3 SCSS.  It would be changed via "theming"

https://bootstrap-vue.js.org/docs/reference/theming

https://getbootstrap.com/docs/4.3/getting-started/theming/

And the bootstrap V4.3 SCSS variables that control bootstrap CSS: 

https://github.com/twbs/bootstrap/blob/f72d2511ba195fc50ce47061a2313567ad667744/scss/_variables.scss#L484-L487

There are over 1000 variables to control Bootstrap SCSS styling, so it would be impossible to document every one of these.
