### ISSUE TITLE
Update b-table column labels when switching display language

### ISSUE THREAD

**Issue by AnReZa** [bootstrap-vue/bootstrap-vue#3409]
The solution provided in #1687 doesn't seem to work anymore. I've put `fields` as a function into the `computed` area and I'm calling a `method`, which returns the column name. When I change the language by calling `this.$i18n.i18next.changeLanguage(locale)`, it changes everything but the table header. Sometimes, they don't change at all, and sometimes they get replaced with the translation path. The error sometimes fixed itself after hitting F5.

When adding a `console.log` to the `getColLabel` method, I can see, that it is _not_ called when updating the language.

I'm using vue-i18next in combination with backend loading:

```js
computed: {
  fields() {
	return [
	  {
		key: 'article',
		label: this.getColLabel('article')
	  },
	  {
		key: 'typeCode',
		label: this.getColLabel('typeCode')
	  },
	  // ...
	];
  }
},
methods: {
  getColLabel(colName) {
    return this.$i18n.t('yourApplication.affectedProducts.table.columns.' + colName);
  }
}
```

```js
import i18next from 'i18next';
import VueI18Next from '@panter/vue-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import XHR from 'i18next-xhr-backend';
import YAML from 'js-yaml';

Vue.use(VueI18Next);

i18next
  .use(XHR)
  .use(LanguageDetector)
  .init({
    ns: ['main', 'order'],
    defaultNS: 'order',
    fallbackLng: 'en',
    backend: {
      loadPath: '/locales/{{lng}}/{{ns}}.yaml',
      parse: data => YAML.safeLoad(data)
    }
  });

const i18n = new VueI18Next(i18next);

/* eslint-disable no-new */
new Vue({
  el: '#app',
  i18n,
  router,
  template: '<App/>',
  components: {
    App
  }
})
```

**Comment by tmorehouse** [comment]
Convert your computed property to method to force it to be called each render (as long as changing the language will cause your app/component to re-render). Vue caches the results of computed properties, and only updates them when *reactive* data changes them.  Methods typically are not a reactive element when used inside a computed prop.

Another solution is to read in a reactive prop (that specifies your language has changed) at the top of the computed prop (i.e. assign it to a const).  This will ensure that the computed prop is re-evaluated by Vue each time the language changes.  i.e.:

```js
{
  // ...
  computed: {
    fields() {
      // Accessing this.$i18n.locale in this computed prop tells Vue that
      // this computed prop should update whenever this.$i18n.locale
      // changes it value, even though we don't use the value.
      const lang = this.$i18n.locale
      // We add the following just so that minification optimizers
      // dont remove the above statement because the return value isn't used 
      if (!lang) { return [] }
      // Return the array of translated values
      return [
        { key: 'article', label: this.getColLabel('article') },
	{ key: 'typeCode', label: this.getColLabel('typeCode') },
	  // ...
	]
    }
  }
```

**Comment by tmorehouse** [comment]
Another solution would be to use scoped HEAD slots to generate the messages (instead of doing hte translation in the computed fields prop:

```html
<b-table :fields="fields" :items="items" ... >
   <template slot="HEAD_article" scope="{ column }">
    {{ $t('yourApplication.affectedProducts.table.columns.' + column) }}
  </template>
   <template slot="HEAD_typeCode" scope="{ column }">
    {{ $t('yourApplication.affectedProducts.table.columns.' + column) }}
  </template>
</b-table>
```
If you don't know what fields are defined (or just don't like repeating yourself you can generate the above slots in a v-for loop:

```html
<b-table :fields="fields" :items="items" ... >
   <span v-for="f in fields" :key="f.key" :slot="'HEAD_' + f.key" scope="{ field }">
    {{ $t('yourApplication.affectedProducts.table.columns.' + field.key ) }}
  </span>
</b-table>
```

**Comment by AnReZa** [comment]
Thank you very much! Which of the two provided solutions would be the preferable one in your opinion? Or is it just a matter of taste?

**Comment by tmorehouse** [comment]
Either of the two... although the second method (scoped slots) is probably safer from minification (in case a minifier removes the unused assignment in the computed prop method).

**Comment by AnReZa** [comment]
I've tried to implement the first method, but it still doesn't update. `this.$i18n.locale` doesn't seem to exist in i18next. I tried to modify the code, but it doesn't work. The "re-render" debug print only appears in the console once after loading the page. Changing the language doesn't seem to re-call the computed:

	const lang = this.$i18n.i18next.language;
	
	if (!lang) return [];
	
	const getColLabel = colName => this.$i18n.t('yourApplication.affectedProducts.table.columns.' + colName);
	
	console.log('re-render');
	
	return [
	  {
	    key: 'article',
	    label: getColLabel('article')
	  },
	  /* ... */
	];

**Comment by tmorehouse** [comment]
They must have not set `this.$i18n.i18next.language` to be an observable (i.e. reactive) in `i18next`.

**Comment by AnReZa** [comment]
I've opened a ticket for this issue on the vue-i18next project. In the mean time, is there a simple way to build kind of a wrapping observable around the language setting of i18next? The only way to change the language is through a dropdown, where I have full control over it,

**Comment by tmorehouse** [comment]
If using Vue 2.6.x, there is a new helper utility ]`Vue.observable(...)`](https://vuejs.org/v2/api/#Vue-observable) that might help (although how it works when Vue 3. comes out will be a bit different)

**Comment by tmorehouse** [comment]
You would have to pass this "observable" around between uses of it (to make it work with Vue 3, as it returns a proxy), but for Vue 2.6.x it makes the original object observable
