### ISSUE TITLE
navbar cursor

### ISSUE THREAD

**Issue by haoxingwang** [bootstrap-vue/bootstrap-vue#341]
0.15.0![old_1](https://cloud.githubusercontent.com/assets/16429312/25731577/edac64fe-3179-11e7-93be-2bc3b48e5822.png)
0.15.2![new_1](https://cloud.githubusercontent.com/assets/16429312/25731579/eddc9f52-3179-11e7-8e4a-038b9aa490f1.png)
0.15.0![old_2](https://cloud.githubusercontent.com/assets/16429312/25731578/edcec79c-3179-11e7-9b45-0b865600ccd0.png)
0.15.2![new_2](https://cloud.githubusercontent.com/assets/16429312/25731580/edefef62-3179-11e7-87e5-d66f7dc7fa25.png)
[jsfiddle](https://jsfiddle.net/pi0/gfqucs0z/)
don't speak Engilsh 
sorry

**Comment by tmorehouse** [comment]
I don't see this issue in the latest version (on chrome).  Are you including the latest `bootstrap.css` from V4.alpha.6?

**Comment by haoxingwang** [comment]
0.15.6 is ok
think you
