### ISSUE TITLE
Something for style property ！！

### ISSUE THREAD

**Issue by caishijian2008** [bootstrap-vue/bootstrap-vue#3410]
Why not provide the style or class property for every components, such as `<b-dropdown style="...">`, `<b-link class="...">` etc, so we can customize style by ourself.

**Comment by tmorehouse** [comment]
Bootstrap Vue is based on Bootstrap V4 SCSS classes.

All components allow the `class` and `style` attributes, which will get applied to the root element of the component

**Comment by caishijian2008** [comment]
Can support `<b-dropdown :style="{...}">` or `<b-dropdown :style="[...]">` ?

**Comment by tmorehouse** [comment]
Yes.   `style` is controlled by Vue, and supports string, object and array formats.

Just remember that `style` (and `class`) are always placed on the root element of any Vue component

**Comment by caishijian2008** [comment]
OK，I see，thanks very much！
