### ISSUE TITLE
[question] Dropdown extending site height

### ISSUE THREAD

**Issue by Zaftri** [bootstrap-vue/bootstrap-vue#3412]
I couldn't find any similar issue. 

Hi, i'm having a little problem. On my project, i created table with options for each row. On the bottom of table, when i'm clicking on button, it extends site height.
How can i make it drop up, when it's on bottom of site?

Here is jsfiddle example of problem:
https://jsfiddle.net/Zaikare/we1azr4q/1/

**Comment by ddweber** [comment]
Seems to be a problem with the `dropleft `prop.
When you remove it, the dropover behaves as aspected, thats means it drops up when there is not enough space available at the bottom.

**Comment by Zaftri** [comment]
Thank you very much for you answer. So it's more problem with bootstrap 4 than this library?
Can i do some workaround? Like calculate button position and changing attributes for it?

**Comment by tmorehouse** [comment]
A few issues with the fiddle.  Bootstrap CSS is loaded after BootstrapVue CSS (they need to be swapped).

The v-for generating the `<tr>` elements needs to set a `:key="..."` on the row.

And table cells can affect dropdown's positioning via Popper.js.  Set the `boundary` prop on `<b-dropdown>` to `'viewport'` or `'window'`.

See: https://jsfiddle.net/y806cdw7/
