### ISSUE TITLE
vue-bootstrap table sort icon not working

### ISSUE THREAD

**Issue by sanathoi93** [bootstrap-vue/bootstrap-vue#3415]
Hi, I am following your example [complete example](https://bootstrap-vue.js.org/docs/components/table#complete-example) for vue bootstrap table. I get everything working except sorting icons. The sorting function seems to be working but it doesn’t show any icons.

**Comment by tmorehouse** [comment]
Make sure you are including the BootstrapVue CSS after Bootstrap's CSS

**Comment by sanathoi93** [comment]
Thanks..! Please update this in vue-bootstrap website.

**Comment by tmorehouse** [comment]
It is documented in the getting started docs:
 - https://bootstrap-vue.js.org/docs#using-module-bundlers
 - https://bootstrap-vue.js.org/docs#browser
