### ISSUE TITLE
types: v2.0.0-rc.21 causes errors

### ISSUE THREAD

**Issue by DonaldMarsh** [bootstrap-vue/bootstrap-vue#3416]
I started getting compilation errors with v2.0.0-rc.21 which go away when I revert to v2.0.0-rc.20.  The errors complain about extending the BvComponent interface instead of implementing it.  I'm not sure why this started happening, but for me, reverting to the previous version is a good short-term fix.

**Comment by tmorehouse** [comment]
Duplicate: #3390

Has been fixed in PR #3391 and will be available when 2.0.0-rc.22 is released.

**Comment by tmorehouse** [comment]
v2.0.0-rc.22 has been released.
