### ISSUE TITLE
fill and justified do not work for items inside <b-navbar-nav>

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#3419]
### Describe the bug
According to [this](https://bootstrap-vue.js.org/docs/components/navbar#comp-ref-b-navbar-nav) documentation `<b-navbar-nav>` has `fill` and `justified` properties, but they do not work - items inside `<b-navbar-nav>` are not filled or justified.

### Expected behavior
Expect to have filled or justified items inside `<b-navbar-nav>`, but instead all items aligned to the left.
### Versions

**Libraries:**

- BootstrapVue: 2.0.0.rc11
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Ubuntu 19.04
- Browser: Chrome 74.0.3729.169 (Official Build) (64-bit) and FireFox 67.0 (64-bit)

### Demo link
https://codesandbox.io/s/bootstrap-vue-navbar-jusify-issue-oekpz

P.S. Probably `right` property within `<b-nav-item-dropdown>` should align items to the right. If so, seems it also does not work.

**Comment by tmorehouse** [comment]
You may need to set a width for your navbar-nav, as I believe bootstrap CSS/SCSS sets it as an inline-block/flex element.

**Comment by TitanFighter** [comment]
`<b-navbar-nav style="width: 100%" justified>` works.
Thank you.

**Comment by tmorehouse** [comment]
Also there is a markup mistake in your example:

```html
    <b-navbar toggleable="lg" type="dark" variant="info">
      <b-navbar-nav justified>

          <b-dropdown-item href="#">EN</b-dropdown-item>
          <b-dropdown-item href="#">ES</b-dropdown-item>
          <b-dropdown-item href="#">RU</b-dropdown-item>
          <b-dropdown-item href="#">FA</b-dropdown-item>

        <b-nav-item-dropdown right>
          <!-- Using 'button-content' slot -->
          <template slot="button-content"><em>User</em></template>
          <b-dropdown-item href="#">Profile</b-dropdown-item>
          <b-dropdown-item href="#">Sign Out</b-dropdown-item>
        </b-nav-item-dropdown>
      </b-navbar-nav>
    </b-navbar>
```

you have `<b-dropdown-item href="...">` elements not inside a `<b-nav-item-dropdown>` did you mean to use `<b-nav-item href="...">` for those four ones at the top?

**Comment by tmorehouse** [comment]
You can also add the class `flex-grow-1` to `<b-navbar-nav justified class="flex-grow-1">`

Since navbar is a flexbox, class `flex-grow-1` will instruct the flexbox to take up as much width as possible (similar to class `w-100` which sets style `width: 100%`).

**Comment by TitanFighter** [comment]
> Also there is a markup mistake in your example:....
> did you mean to use <b-nav-item href="..."> for those four ones at the top?

Yes, forgot to change when was preparing the demo. Fixed.
