### ISSUE TITLE
Integration v-table with vee-validate

### ISSUE THREAD

**Issue by aayaresko** [bootstrap-vue/bootstrap-vue#342]
we are using vee-validate, to validate forms and trying to use v-table.
wen user tries to access component with v-table - app throws an error:
```

[Vue warn]: The computed property "fields" is already defined in data.

found in

---> <Hello> at /srv/aayaresko/public_html/www/vuejs/adaptation/src/components/Hello.vue
       <App> at /srv/aayaresko/public_html/www/vuejs/adaptation/src/App.vue
         <Root> app.js line 721 > eval:432:1

[Vue warn]: Property or method "msg" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Hello> at /srv/aayaresko/public_html/www/vuejs/adaptation/src/components/Hello.vue
       <App> at /srv/aayaresko/public_html/www/vuejs/adaptation/src/App.vue
         <Root> app.js line 721 > eval:432:1

[Vue warn]: The computed property "fields" is already defined as a prop.

found in

---> <BTable>
       <Hello> at /srv/aayaresko/public_html/www/vuejs/adaptation/src/components/Hello.vue
         <App> at /srv/aayaresko/public_html/www/vuejs/adaptation/src/App.vue
           <Root>
```
example [here](https://github.com/aayaresko/bootstrap-vue-table-and-vee-validate/)

**Comment by pi0** [comment]
PR is open on #337

**Comment by PierBover** [comment]
A solution is to tell `vee-validate` to use a different property than `fields`.

This can be done in the configuration by using `fieldsBagName` as stated in [the docs](http://vee-validate.logaretm.com/).

I imagine if your project is quite advanced this will be a hassle but we caught it early on so for us it wasn't a big deal.

**Comment by aayaresko** [comment]
**PierBover** thank you. I'll give it a try :)

**Comment by arivera12** [comment]
const config = {
  errorBagName: 'errors', // change if property conflicts.
  fieldsBagName: 'fields', //Change this to something else like inputs or whatever
  delay: 0, 
  locale: 'en', 
  dictionary: null, 
  strict: true, 
  enableAutoClasses: false, 
  classNames: {
    touched: 'touched', // the control has been blurred
    untouched: 'untouched', // the control hasn't been blurred
    valid: 'valid', // model is valid
    invalid: 'invalid', // model is invalid
    pristine: 'pristine', // control has not been interacted with
    dirty: 'dirty' // control has been interacted with
  },
  events: 'input|blur',
  inject: true
};

Vue.use(VeeValidate, config);
