### ISSUE TITLE
Showing b-tab after initial render no longer works in rc.21

### ISSUE THREAD

**Issue by postalservice14** [bootstrap-vue/bootstrap-vue#3427]
### Describe the bug

If you have a <b-tab> component on render, and then a computed prop changes to allow for a second <b-tab> component to show, that second <b-tab> component will never show.  This used to work, and no longer works in rc.21

### Steps to reproduce the bug

See CodePen Example: https://codepen.io/anon/pen/KLrjpZ
Click increase count to cause computed prop to return true and second tab will not show.

### Expected behavior

After clicking increase count, the second tab should show.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.21
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: 10.14.5
- Browser: Chrome
- Version: 74

### Demo link

https://codepen.io/anon/pen/KLrjpZ

**Comment by tmorehouse** [comment]
Related issue #3395

This has been fixed by PR #3396 and will be available in BootstrapVue V2.0.0-rc.22 which is being released later today.

**Comment by postalservice14** [comment]
Ahh yeah, just found that - thanks and sorry for the duplicate

**Comment by tmorehouse** [comment]
v2.0.0-rc.22 has been released.
