### ISSUE TITLE
String `:style` notation not working in `<b-col>` (at least)

### ISSUE THREAD

**Issue by andrei-gheorghiu** [bootstrap-vue/bootstrap-vue#3431]
### Describe the bug

In `<b-col>` components (at least), the `:style` attribute is limited to `object` notation. This might be the case with more Bootstrap Vue components but it should be considered a bug, since it's a clear limitation from `:style` normal behavior on Vue components.

### Steps to reproduce the bug

Please see [this question](https://stackoverflow.com/questions/56401806/how-to-bind-custom-style-in-b-col-bootstrap-vue-element) and [this answer](https://stackoverflow.com/a/56402537/1891677).

### Expected behavior

String `:style` properties passed to Bootstrap Vue components should apply correctly.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: [MacBook Pro]
- OS: [Windows 10]
- Browser: [Chrome]
- Version: [74.0.3729.169]

It should be expected this bug is Bootstrap Vue specific and would be encountered across any device + OS + browser combo.

### Demo link

https://stackoverflow.com/questions/56401806/how-to-bind-custom-style-in-b-col-bootstrap-vue-element

**Comment by tmorehouse** [comment]
We use [`vue-functional-data-merge`](https://github.com/alexsasharegan/vue-functional-data-merge) to merged the data provided by Vue to the functional component's root element (normally [Vue does not do automatic merging](https://github.com/vuejs/vue/issues/6895) of attributes `class`, `style`, or any non-prop attribute.

This might be an upstream bug in `vue-functional-data-merge` where it is not handling a function reference returning a string value for styles.  Or maybe Vue is not parsing the returned string _first_ before passing it to the data in a component.

The best bet, when using complex styles is to always [return the style as an object](https://vuejs.org/v2/guide/class-and-style.html#Binding-Inline-Styles) per the Vue docs.

**Comment by tmorehouse** [comment]
It probably has something to do with these lines in `vue-functional-data-merge`

https://github.com/alexsasharegan/vue-functional-data-merge/blob/master/src/index.ts#L22-L31

```js
        case "class":
        case "style":
        case "directives":
          if (!Array.isArray(mergeTarget[prop])) {
            mergeTarget[prop] = [];
          }
          // Repackaging in an array allows Vue runtime
          // to merge class/style bindings regardless of type.
          mergeTarget[prop] = mergeTarget[prop].concat(arguments[i][prop]);
          break;
```

At this point, when the data is merged for `style`, Vue may assume it has been converted from a function ref to an object or string already.

`vue-functional-data-merge` may need to check of the argument is a function ref first, and if so execute it before adding to the concatenated array.

cc/ @alexsasharegan

**Comment by tmorehouse** [comment]
I just tried a test of passing a string as an array member to a `<div>` and it doe not apply the styles:

```html
<template>
  <div :style="['color: red;', { fontWeight: 'bold' }]">Foobar</div>
</template>
```

and only the object entry was respected.  The string array entry is not retained.

So this appears it might be an upstream bug with Vue (cc/ @yyx990803)

It might be something we can get around with modifications to `vue-functional-data-merge` (cc/ @alexsasharegan), when the prop is type `style` and a string is detected:

```js
        case "class":
        case "style":
        case "directives":
          if (!Array.isArray(mergeTarget[prop])) {
            mergeTarget[prop] = [];
          }
          // Repackaging in an array allows Vue runtime
          // to merge class/style bindings regardless of type.
          if (prop === 'style' && typeof arguments[i][prop] === 'string') {
            // except style of type string, so convert it to object notation
            const styles = arguments[i][prop].split(/;\s*/)
            arguments[i][prop] = styles.map((obj, style) => {
              const parts = style.split(/\s*:\s*/)
              obj[camelCase(parts[0].trim())] = parts[1].trim()
              return obj
            }, Object.create(null))
          }
          mergeTarget[prop] = mergeTarget[prop].concat(arguments[i][prop]);
          break;
```

**Comment by alexsasharegan** [comment]
I'm trying to catch up here, but did I understand correctly that there's an issue passing a function and/or a string to the styles? I don't see anywhere that functions are supported. The styles, classes, and directives are all transformed to an array that vue core flat maps. It looks like Troy was able to demonstrate this as vue's native behavior.

**Comment by tmorehouse** [comment]
yeah, it appears to be a Vue issue when a string is passed in array format to styles.

It is mainly an issue with strings (not function, as I found out after trying the above array format).

One workaround would be check in `vue-functional-data-merge` to check if the `style` being merged is a string, and if it is, convert it to object style notation, since `vue-functional-data-merge` always converts to arrays (if it wasn't an array, and just a single string, Vue is happy).

**Comment by alexsasharegan** [comment]
Yeah, that's an option, but one I don't really want to introduce. I don't think adding string parsing into the merge pipeline is really an ideal option for a function that runs on every render. One of the design goals for VFDM is to be relatively zero cost. Granted, this path would only run when conditions are matched, but it encourages using this slower merge strategy.

With the changes coming for Vue 3.x, the need for VDFM will be gone. My stance is more don't fix what ain't broken until then.

**Comment by tmorehouse** [comment]
See edited example above.  pasting into the playground you can see that it works for full components vs functional components.

**Comment by alexsasharegan** [comment]
Also worth noting, this is problem is consistent through the example.

![image](https://user-images.githubusercontent.com/16269252/58751999-1f63c280-845c-11e9-9ff4-f177cdc170a4.png)

**Comment by alexsasharegan** [comment]
It looks like I can make this as fast as before. Trying to work out the edge cases of string parsing still.

**Comment by alexsasharegan** [comment]
Have a look at the changes and tests to see if this covers the use case.

**Implementation**
https://github.com/alexsasharegan/vue-functional-data-merge/blob/master/src/index.ts#L60-L74

**Tests**
https://github.com/alexsasharegan/vue-functional-data-merge/blob/master/__test__/array-merge.test.ts

**Comment by tmorehouse** [comment]
@alexsasharegan looks good.   you may want to add in a test with a style string missing the trailing `;`

And I just thought of  a weird case where split on `:` may not work, if users pass a style string such as `background: url(http://foo.bar/baz.png"`

But this will split only on the first `:`, e.g. `let [key, val] = s.split(":(.*)")`

**Comment by alexsasharegan** [comment]
Handled in 3.0.1

https://github.com/alexsasharegan/vue-functional-data-merge/blob/master/__test__/array-merge.test.ts#L13

**Comment by tmorehouse** [comment]
Excellent!

**Comment by alexsasharegan** [comment]
Create an issue on VFDM if there are any more edge cases. The impact this has on execution time is pretty minimal, so I think this maintains the zero cost usage of VFDM. Win win! Thanks for the implementation guide--made it easy to get it working!

**Comment by tmorehouse** [comment]
I will create an issue on Vue, re: passing an array of styles which has an entry which is a string.
