### ISSUE TITLE
Nested modals

### ISSUE THREAD

**Issue by cjd118** [bootstrap-vue/bootstrap-vue#3436]
### Is your feature request related to a problem? Please describe...

I'm aware in the docs it specifically states nested modals are not supported: 

"Avoid nesting a <b-modal> inside another <b-modal>, as it may get "constrained" to the boundaries of the parent modal dialog (specifically when static modals are used)."

However our use case would really benefit from this and I wondered if there was a work around? We have a media library component where a user can click on an image to edit it. That edit view is within a modal. The media library component itself is nested as a modal within other components when a user needs to pick an image.

Page Component -> embeds modal: Media Library -> embeds modal: Edit Image

### Describe the solution you'd like

A workaround, hacky fix, or feature to support nested modals. 

### Describe alternatives you've considered

We've tried using Vue Portal to move the modals into the document body, but this prevents various events from triggering correctly.

**Comment by tmorehouse** [comment]
Have you tried the latest version of BootstrapVue (v2.0.0-rc.22)? it now _portals_ the modal to be appended to the document body.
