### ISSUE TITLE
[Dromdown-item] undefined hrefString

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#344]
As i can see from commit history at some point `hrefString` was changes to `href`? 
dropdown-item.vue threw an error

> [Vue warn]: Property or method "hrefString" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
> 
> found in
> 
> ---> <BDropdownItem> at D:\Dev\reestrius_spa\node_modules\bootstrap-vue\lib\components\dropdown-item.vue
>        <BNavItemDropdown> at D:\Dev\reestrius_spa\node_modules\bootstrap-vue\lib\components\nav-item-dropdown.vue
>          <BNav> at D:\Dev\reestrius_spa\node_modules\bootstrap-vue\lib\components\nav.vue
>            <BCollapse> at D:\Dev\reestrius_spa\node_modules\bootstrap-vue\lib\components\collapse.vue
>              <BNavbar> at D:\Dev\reestrius_spa\node_modules\bootstrap-vue\lib\components\navbar.vue
>                <App> at D:\Dev\reestrius_spa\src\App.vue
>                  <Root>

**Comment by mosinve** [comment]
Linked to #343

**Comment by pi0** [comment]
thanks!
