### ISSUE TITLE
On change event for select inside a form returns the previous value

### ISSUE THREAD

**Issue by Magenta94** [bootstrap-vue/bootstrap-vue#3440]
### Describe the bug

I have a select and a slider range inside a `b-form`. The `b-form` calls a method on change event, which prints the selected value of the select. On Chrome and Firefox the printed value is not the current selected, but the previous one. On Edge it works.

### Steps to reproduce the bug

See demo link.

### Expected behavior

In the alert we should see the current selected value, not the previous one. The flow works if we make a change on the slider or if we're using Edge.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Windows
- Browser: Chrome, Firefox
- Version: Chrome 74, Firefox 67

### Demo link

https://jsfiddle.net/q31674kr

**Comment by tmorehouse** [comment]
In your fiddle, you have the `change` handler applied to the `form`, not the `select`, so you are detecting the native select change event, not the custom select component's custom `change` event.

Move your change handler to the `b-form-select` and you will see the intended behavior: https://jsfiddle.net/x546wq8h/
