### ISSUE TITLE
Spinner in a button ?

### ISSUE THREAD

**Issue by VConsulting** [bootstrap-vue/bootstrap-vue#3441]
Spinner in a button

I do not understand how to hide the Spinner in the button and display it only at the moment of the click then make it disappear as soon as the action is over ...

Thank you for your clarification / example?

```
<button class="btn btn-success">
<b-spinner small type="grow" style="margin-bottom: 3px;"></b-spinner> Save
</button>
```

**Comment by tmorehouse** [comment]
Use `v-if" to show and hide the spinner, based on a condition in your app/component.  Such as setting a variable to true in a button click handler (then possibly disabling the button to prevent more clicks), and then once your async action is complete, reset the variable.

```html
<template>
  <b-button variant="success" :disabled="busy" @click="handleClick">
   <b-spinner v-if="busy" small type="grow" style="margin-bottom: 3px;"></b-spinner> Save
  </b-button>
</template>

<script>
export default {
  data() {
    return {
      busy: false
    }
  },
  methods {
    handleClick() {
      this.busy = true
      // Do something that takes some time
      setTimeout(() => { this.busy = false }, 1000)
    }
  }
}
</script>
