### ISSUE TITLE
<b-pagination-nav> fails to update the active page when "pages" gets larger

### ISSUE THREAD

**Issue by mtlynch** [bootstrap-vue/bootstrap-vue#3443]
### Steps to reproduce the bug

1. Create a `<b-pagination-nav>` element with `:pages` set to a `computed` attribute that returns `['10', '12', '14']`
1. Select the third element in the pagination component (`'14'`)
1. Perform an action on another part of the page that changes the `pages` model to `['10', '11', '12', '13', '14', '15']`

### Expected behavior

Page `14` continues showing as active after `pages` changes.

### Actual behavior

Page `12` shows as active after `pages` changes.

![bootstrap-vue-pagination](https://user-images.githubusercontent.com/7783288/58889848-8a5d0580-86b7-11e9-9ed2-a5dcf1ebba6e.gif)

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: 74.0.3729.169

### Demo link

https://github.com/mtlynch/bootstrap-pagination-debug

### Additional context

This seems to be related to the initial size of `pages`. When the initial size of the page array is 3 and you select the second element, then increase the number of pages, everything works as expected. The issue only manifests when you select elements in the list whose position is > initial size of the page array.

I tried setting `v-model` and `no-page-detect`. I can see from console output that my `v-model` function returns the correct value, but `<b-pagination-nav>` does not update to match it.

**Comment by tmorehouse** [comment]
Related issue: https://github.com/bootstrap-vue/bootstrap-vue/issues/3372

**Comment by tmorehouse** [comment]
We may need to re-trigger the current page detection routine on change of the array of pages.

Are you using the v-model to control the pages?  auto-detection does not work when v-model is used, as it takes precedence over page detection.

**Comment by mtlynch** [comment]
I've tried both with auto-detection and with `v-model` and I get the same behavior in either case. Here's the specific Vue component:

https://github.com/mtlynch/bootstrap-pagination-debug/blob/master/src/views/Home.vue

**Comment by tmorehouse** [comment]
Side note: when passing an array to `pages` prop, you don't need to set the `number-of-pages` prop as `<b-pagination-nav>` will get the number of pages from the `pages` array (ignoring the `number-of-pages` prop)

**Comment by tmorehouse** [comment]
Version 2.0.0-rc.23 has been released.
