### ISSUE TITLE
b-table does not react on apiUrl prop change

### ISSUE THREAD

**Issue by yuriy-zhilovets2** [bootstrap-vue/bootstrap-vue#3445]
b-table ignores changing of the **apiUrl** property and does not call **item** function at this moment.

Use case:

**apiUrl** includes query string for searching some items

**Comment by tmorehouse** [comment]
Which version of BootstrapVue are you using?

**Comment by tmorehouse** [comment]
The `api-url` prop is included in the context that triggers a provider refresh, so it should be working.

The provider trigger context: 
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/table/helpers/mixin-provider.js#L31-L58

and the watcher that monitors changes in the provider trigger context:
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/table/helpers/mixin-provider.js#L67-L72

**Comment by tmorehouse** [comment]
See fiddle https://jsfiddle.net/bmorkuh7/ which shows b-table reacting to api-url changes.
