### ISSUE TITLE
Request: Textarea Max Rows

### ISSUE THREAD

**Issue by KuroThing** [bootstrap-vue/bootstrap-vue#345]
I would like to request that a "max-rows" attribute be added to the text area that will cap out how many rows the textarea can have

**Comment by tmorehouse** [comment]
Would that be physical rows, or the maximum height of the text area?  If the latter, you can use CSS to target the text area and limit the height.

**Comment by KuroThing** [comment]
Physical rows of text is what i'm interested in

**Comment by tmorehouse** [comment]
So would this be just to limit the height of the text area or to limit the number of rows the user has entered?

**Comment by KuroThing** [comment]
limiting the height of the text area via the physical amounts of rows entered

So if the max rows was set to 10, after 10 rows, it wouldn't increase anymore.

**Comment by tmorehouse** [comment]
That could be set on CSS with a `max-height` set in either `em` or `rem` units (i.e. `max-height: 10em;`)

**Comment by KuroThing** [comment]
That seems kind of overkill if you want various heights for text areas, or for it to change based on a condition, wouldn't the computed properties of Vue.js be the perfect match for this?

I guess i can always just use a custom computed property and the html element itself if you don't want to implement it into the form input component instead.

**Comment by tmorehouse** [comment]
`b-form-input` does have an optional `rows` property which sets the `rows` attribute on the `textarea`. You can tie this to a computed value. It defaults to the number of rows in the `value` (or 1 if no content in value). Providing a value to the `rows` prop will override this value
