### ISSUE TITLE
Clarification on modal docs `bvModal`

### ISSUE THREAD

**Issue by Lechindianer** [bootstrap-vue/bootstrap-vue#3452]
The docs for the new modals state 
```
Note: It is recommended to use the this.$bvModal.show() and this.$bvModal.hide() methods (mentioned in the previous section) instead of using $ref methods.
```

Could you please clarify why the new way to show/hide modals is the preferred one? From the outside it looks the same, no advantage in using it.

**Comment by tmorehouse** [comment]
It is much more convenient that writing out a long `this.$root.$emit('some long string event name', id)` method, or needing to retain a `ref` to the modal component to access the methods.
