### ISSUE TITLE
BootstrapVue on typescript

### ISSUE THREAD

**Issue by jose-pr** [bootstrap-vue/bootstrap-vue#3453]
### Describe the solution you'd like

With the move in Vue to rewrite it all on typescript could the same be done for bootstrap-vue.
That way there would be no need to keep .d.ts file up to date as they would be produced by the compiler and everything can be managed from one code base. 

I started to work on it to see how much work it would take and although it would take some time it doesnt look complicated. At the moment I am working on this to learn typescript but i can continue it to the end if it would be desired.

https://github.com/jose-pr/bootstrap-vue-ts

**Comment by tmorehouse** [comment]
We would need ESLint and prettier to work with the new `.ts` files, as well as the modular builds (i.e. the `/esm` build directory)

**Comment by jose-pr** [comment]
Started from scratch to make a working build (only link component at the momment) at https://github.com/jose-pr/bootstrap-vue-ts and using rollup to produce a umd build and typescript for the es build. 
It has eslint / prettier enabled. 
It has some functions under script to produce the index files for component and directives and to produce the config type so it has full BvConfigOptions is fully type for the options of each component.

**Comment by tmorehouse** [comment]
Note by making an index for utils will cause them not to be tree shakable (and some utils have conflicting export names)

**Comment by tmorehouse** [comment]
Also not the `es/` build is being deprecated... and replaced by the `esm/` modular build

**Comment by jose-pr** [comment]
> Note by making an index for utils will cause them not to be tree shakable (and some utils have conflicting export names)

Fixed the conflicting names  by only exporting them from their own modules array and object functions. 
I though it would follow the modules for tree shacking and only use the exports called directly.
 the es name is not really accurate it is just a 1 to 1  conversion of the ts to js.
Dont really know the difference between es and esm but in this case is really js output folder.
Just push an update with esm output, with the indexmaker.ts creating the rollup.inputs.js with all the plugin/components/directives it finds.

**Comment by jose-pr** [comment]
> Note by making an index for utils will cause them not to be tree shakable (and some utils have conflicting export names)

Just verified that exporting all through utils wont affect tree shaking if done correctly .
https://github.com/jose-pr/bootstrap-vue-ts/tree/91b77070eab44e503373e8d34e336cf18ff40823
At least with rollup code will only be used if it is actually used as can be seen with in the index.browser.ts with TestPartial1 and wont be used if it not actually imported like on TestPartial2 (the default and named export of utils/partiallyuse.ts and none of utils/notuse.ts exports are on any of the code in the dist. (umd or esm) they are only on the es folder that is just the javascript from typescript.

As long as they are no circular import/exports (utils should only import from other utils or external code and no util should import another that also imports it) which rollup tells you about it should work fine. and would allow the importing of any util with just import {  utiltoimport } from './utils'

**Comment by tmorehouse** [comment]
There are a couple of helpers in object and array that are re-exported in the inspect modules.

We hae to be careful of re-ecporting re-exports, as webpack 4 has issues traking what is used an not used when multiple layers of re-exports are used.

As well, it is possible to get babel to compile from TS when building the `esm/` dir (which should eliminate needing a special build routine to transpile to `esm/`

**Comment by jose-pr** [comment]
Rollup is actually compiling directly to js from ts using @wessberg/rollup-plugin-ts  and it also generates types outputs for all the chunks / types it produces. 
The only reason for the es folder at the moment is to verify what happens from ts to js  and because it doesnt take anything special to produce just typing tsc but it can be disabled/removed pretty easily
I removed the exports from array and object on inspect to mitigate duplicate exports, as all can now be access from util directly.

**Comment by tmorehouse** [comment]
In a future major release, we may convert to using typescript
