### ISSUE TITLE
Issue with copying HTML content of a modal on IE11

### ISSUE THREAD

**Issue by xtenpeben** [bootstrap-vue/bootstrap-vue#3457]
### Describe the bug

Unable to copy html content of a modal and pasting it into another application (i.e. Word) except for another browser (i.e. Chrome). 

### Steps to reproduce the bug

1. Go to Modal page in bootstrap-vue.js.org (https://bootstrap-vue.js.org/docs/components/modal)
2. Click on the very first "Launch Modal Demo" button
3. Select the HTML content inside the modal (paragraph)
4. Paste into Word
5. Nothing gets pasted

### Expected behavior

It should paste the formatted content. 

### Versions

**Libraries:**

- BootstrapVue: 2.0.0.-rc19
- Vue: 2.6

**Environment:**

- Device: Laptop
- OS: Windows10
- Browser: IE11

**Comment by tmorehouse** [comment]
@xtenpeben Try upgrading to BootstrapVue 2.0.0.-rc.22 and see if the issue persists.

**Comment by xtenpeben** [comment]
@tmorehouse The issue still persists in bootstrap-vue.js.org site. I just assumed that's on 22. I'll update my local dev to 22 and see.

**Comment by tmorehouse** [comment]
I just tested with IE 11, and see that pasting into Word 2010 does not work, while pasting the same thing into Notepad and Notepad++ and Excel 2010 works (as well as a few other applications I have tried).  Pasting as text does work in Word 2010 though.

Visually when pasting into Word, the text does not show up, but if clicking the reveal codes button, the text does now up:

![image](https://user-images.githubusercontent.com/2781561/58975832-527bbe00-879c-11e9-98c4-54773b01851f.png)

![image](https://user-images.githubusercontent.com/2781561/58975861-61fb0700-879c-11e9-9e14-1fd062fa62a6.png)

**Comment by xtenpeben** [comment]
Thanks. 

Also, not sure if this would help, bootstrap 4 by itself that I have on a separate non-vue project. Copy / paste works just fine for all browsers including IE11.

**Comment by tmorehouse** [comment]
We do have a text-selection detection routine, which is mainly used to prevent a backdrop-click from happening during text selection.  I wonder if that might be interfering with how Word is picking up the full copy information.

**Comment by xtenpeben** [comment]
Thanks!

**Comment by tmorehouse** [comment]
Will be available in release 2.0.0-rc.23
