### ISSUE TITLE
Wrong package name for pagination-nav

### ISSUE THREAD

**Issue by danielvy** [bootstrap-vue/bootstrap-vue#3458]
package.json of pagination-nav incorrectly sets the name as:

`"name": "@bootstrap-vue/popover"`

This confuses the typescript compiler and prevents importing the PopoverPlugin.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Comment by tmorehouse** [comment]
Fix will be available in 2.0.0-rc.24

**Comment by tmorehouse** [comment]
Version 2.0.0-rc.23 has been released.
