### ISSUE TITLE
[Discussion] Strange piece of logic

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#346]
at lib/components/breadcrumb.vue found this piece of logic:
```

                  if (item.active !== true && item.active !== false) {
                         item.__active = item === last;
                     } else {
                         item.__active = item.active;
                     }
```

Can somebody explain me why to use such complex statement?
`item.active !== true && item.active !== false` => true when item.active undefined or null?
`item.active !== true && item.active !== false` => false  when item.active is set ?

why dont just use `item.active == null` instead?

**Comment by mosinve** [comment]
some jsfiddle example to play https://jsfiddle.net/cihkem/pux2k5a5/

**Comment by pi0** [comment]
@mosinve Latest's item active state is automatically set if not explicitly provided. (Using either `true` or `false`) `item.active` may be `undefined` if not set or `null` so maybe it would be better check this two states.

**Comment by tmorehouse** [comment]
What about checking if `item.active` is a `true` boolean? or something like this:
```js
if (item.active === true || item.active === false) {
    item.__active = item.active;
} else {
    item.__active = item === last;
}
```

**Comment by mosinve** [comment]
@tmorehouse you variant is just inverse logic 

@pi0  
(item.active !== true && item.active !== false) and item.active == null  -  theesse expressions give absolutely same results... but second much clearer and shorter

**Comment by tmorehouse** [comment]
@mosive, yeah it is inverse logic, but it looks less "negative" ;)

**Comment by mosinve** [comment]
My point at this issue, it that there is more laconic and clearer variant)))))

**Comment by tmorehouse** [comment]
How about:
```js
if (tyepof item.active === 'boolean') {
    item.__active = item.active;
} else {
    item.__active = item === last;
}
```

**Comment by mosinve** [comment]
so what wrong with my example? ))))))

**Comment by tmorehouse** [comment]
Heheh.

Would CircleCI comaplin about this:
```js
item.last == null
```

Where is always insists on equality being `===`?

**Comment by mosinve** [comment]
Hm,  so its all about ESLint.... 
and found another intersting resource https://jsperf.com/comparison-of-comparisons

**Comment by mosinve** [comment]
=== -  is faster that ==  :) 
I give up....

**Comment by tmorehouse** [comment]
Hehe, could always place an eslint ignore comment command on the previous line to allow `==`
