### ISSUE TITLE
Value of getter not passed to scoped field slot in <b-table>

### ISSUE THREAD

**Issue by davidaanderson** [bootstrap-vue/bootstrap-vue#3463]
I am using a `<b-table>` with scoped slots for custom rendering of fields. I am developing in TypeScript and many of the `items` passed to the table contain getters for the purpose of formatting an existing property (such as a `moment`) for display.

The value of these getters is not being passed to the scoped slot's value property (e.g. `data.value`).

I was using 2.0.0-rc11 and have just moved beyond rc15. I've traced the issue to the implementation of `get` and [this commit](https://github.com/bootstrap-vue/bootstrap-vue/commit/c656fa3), specifically the use of `hasOwnProperty` which does not detect getters. Accessing the getter with bracket notation worked both in bootstrap-vue's implementation of `get` and the lodash implementation in rc11.

Here's a [JsFiddle ](https://jsfiddle.net/1mzL0k4w/) containing the transpiled method's implementation of a getter and the use of `hasOwnProperty`.

I'm happy to see about implementing a fix, but as this relates to the implementation of a core utility, I'll wait for your guidance on how to progress a fix.

**Comment by tmorehouse** [comment]
We added in the `hasOwnProperty` check for situations where users have dots in their property names:

```js
{
  id: 1,
  'first.name': 'John',
  'last.name': 'Doe'
}
```

Otherwise, the detection of such named properties in an item row return null/undefined (as get would look for `item['first']['name']` instead of `item['first.name']`.

Perhaps checking for 'isDefined(item[key])' instead of `hasOwnProperty` may be a workaround

**Comment by tmorehouse** [comment]
Although in our fiddle you are modifying the prototype of **all** objects:

```js
Object.defineProperty(Object.prototype, "getter", {
  get: function get() {
    return "does not work"
  },
  enumerable: true,
  configurable: true
});
```

Which should be avoided, as it could have side-effects on other items.

**Comment by davidaanderson** [comment]
Yeh don't worry, I'm using Object for brevity. In our actual use case it is the prototype of the relevant object on which the getter exists. 

What about or-ing `hasOwnProperty` with a getter specific check ('typeof property.get === "function")?

**Comment by tmorehouse** [comment]
Or we could switch to `in`:

```js
if(key in obj) { ... }
``

Which does check the prototype chain, but can take approximately twice as long as testing for `undefined`, but has about the same execution time as `hasOwnProperty` when the prototype chain isn't checked.  https://ourcodeworld.com/articles/read/166/how-to-check-if-an-object-has-a-property-properly-in-javascript
