### ISSUE TITLE
Problem with enabled components

### ISSUE THREAD

**Issue by WarGot-by** [bootstrap-vue/bootstrap-vue#347]
Good day. 
In project I don't use npm. I install bootstrap-vue with bower
`bower install https://github.com/bootstrap-vue/bootstrap-vue.git#master --save`

May be you help me, how enable components ?

Part from my js file 
`var homeFrontend = new Vue({

    el: '#home-page-block',

    delimiters: ['${', '}'],

    components: {

        bAlert: bAlert,

        bBtn: bBtn,

        bPopover: bPopover
    },`

This not working -( May be anyone help me

**Comment by mosinve** [comment]
Js part in quick start is common for all cases

import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue';

Vue.use(BootstrapVue);

**Comment by WarGot-by** [comment]
@mosinve 
I collect a js files via gulp. 
`
    "my-choices": [
      "assets/bower_components/vue/dist/vue.js",
      "assets/bower_components/vue-resource/dist/vue-resource.js",
      "assets/bower_components/bootstrap-vue/index.js",
      "assets/js/my-choices.js"
    ],
`
In my-choices.js I write code. 
When I added your code to js file I get error:
SyntaxError: import declarations may only appear at top level of a module

my-choisces.js code part
http://dl4.joxi.net/drive/2017/05/05/0017/0504/1114616/16/777617453f.png

**Comment by WarGot-by** [comment]
@mosinve When using Vue I never indicated import for Vue
