### ISSUE TITLE
Link onClick not called [Including solution]

### ISSUE THREAD

**Issue by matanshukry** [bootstrap-vue/bootstrap-vue#3474]
### Describe the bug

I've created a menu using `dropdown-item`, and inside of it 2 spans (icon and text). They also have `:to` prop on them. When clicking on the menu item on the text span it self, the menu stays open (the page is routed though).

I tracked the bug to here:
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/link/link.js#L124

where `evt.target.__vue__` is null if I'm clicking on the span it self.
On the other hand, `evt.currentTarget.__vue__` seems to always exist, so I think the solution would be to use it. Currently I've changed the file locally to make it work, and it works for me.

### Steps to reproduce the bug

1. Create a menu as described above (with items and routing)
2. Click on the menu item, but on the span it self, not the area around it. You might want to add background-color to the span to make it clear where to press.
3. You'll notice the page routes, but the menu stays open.

### Expected behavior

The menu should be closed in step 3 above.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Windows
- OS: Windows 10
- Browser: Chrome
- Version: 74.0.3729.169

### Demo Link

https://codepen.io/anon/pen/ZNgNNw?editors=1010

I'm not sure why the content of the router-view isn't actually showing us, but that's not the point. I'm printing the current path anyway so you can see the route is changing.

And as said, when clicking on dropdown -> one or two (the text it self, not the area around it) - the menu stays open.

**Comment by tmorehouse** [comment]
Technically this would also be an issue with `b-link` and `b-button` when either has a `to` prop as well.

**Comment by tmorehouse** [comment]
Version 2.0.0-rc.23 has been released.
