### ISSUE TITLE
v-b-tooltip: tooltip title not reactive to title attribute

### ISSUE THREAD

**Issue by akhchan99** [bootstrap-vue/bootstrap-vue#3480]
I have a button which toggle the title between "show password" and "hide password"
If the title is not being used with v-b-tooltip directive, it'll toggle between them.  But when its used with v-b-tooltip directive, the text doesn't change (unless I move my mouse away and move back onto the button)

Is it a bug? or are there any workaround?

**Comment by tmorehouse** [comment]
This is a known limitation with the current tooltip implementation and using the `title` attribute to get the title (as it is read from the rendered element).  You can pass a title value as the argument to the directive (see https://bootstrap-vue.js.org/docs/directives/tooltip#title-content) and not use the title attribute.  Or switch to the `b-tooltip` component and pass it the title via a prop or slot.

**Comment by tmorehouse** [comment]
PR #3908 should have this fixed (once it is completed and merged into 2.0.0 stable branch)

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0 stable has been released. See https://bootstrap-vue.js.org/docs/misc/changelog
