### ISSUE TITLE
b-form-select not updating selected value correctly

### ISSUE THREAD

**Issue by arthurmcgregor** [bootstrap-vue/bootstrap-vue#3482]
### Describe the bug

- I have a b-form-select
- It has v-model on "selected"
- Selected is a computed property with get() and set()
    - In the codepen, it gets/sets component data
    - In my context, it gets/sets $router
- The set only updates if some conditions are met
    - In the codepen, it only updates if the value is not 2
    - In my context, it calls $router.push() but there are various navigation guards that may prevent the route actually changing
- For debugging, I have `<p>{{selected}}</p>` beneath the `<b-form-select v-model="selected" `
- The p tag displays the correct value but the b-form-select does not
    - In the codepen, the p displays "2" while the select changes to whatever you selected
    - In my context, the route does not change but the selected dropdown does
- Expected behaviour would be the b-form-select displaying the correct "selected"

### Steps to reproduce the bug

1. Go to [codepen demo](https://codepen.io/arthurmcgregor/pen/ewYpKw?&editable=true&editors=101)
2. Choose any of Option1, Option3, Option4 and observe that the selected and dropdown change
3. Choose Option2 and observe that the selected and dropdown change
4. Choose another option and observe that the selected remains as 2 (correct) but the dropdown changes (incorrect)

### Expected behavior

When the user selects option2, it should remain selected even if they attempt to choose another option.

### Versions

**Libraries:**

- BootstrapVue: 2..0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

NB We think this happened when updating from rc13 to rc22 recently as it was working previously

### Demo link

https://codepen.io/arthurmcgregor/pen/ewYpKw?&editable=true&editors=101

### Additional context

In actual context, the select is controlling the route. When the user is at Option2, there are route guards in place to prevent navigation away from that route until criteria are met. The route guards are working and the underlying "selected" value is correct, but the b-form-select is displaying the wrong option.

**Comment by tmorehouse** [comment]
Sine your v-model is a computed value with getter and setter, and Vue works in batch cycles (the tick),
you are changing the value of the computed property after the get was accessed, but before the tick cycle has completed (before Vue lets the render happen).  Try setting your `mySelected` in your setter in a `$nextTick()`.

**Comment by tmorehouse** [comment]
Note that users of assisted technologies will have issues understanding that a select is triggering navigation (as they rely on semantic markup for correct announcements with screen readers).

**Comment by tmorehouse** [comment]
You may also want to switch to a watcher instead of a get/set computed prop.   The watcher would watch the v-model change, and if the change should not happen, then set the v-model back.

Or, use the `@input.native` event, and check `evt.target.value` and if the value doesn't meet the criteria, then use `evt.preventDefault()` to prevent the select from changing value.

**Comment by tmorehouse** [comment]
Here is your codepen coverted to using a native `<select>`, which is exhibiting the same issues with your code logic.

**Comment by tmorehouse** [comment]
I would suggest switching to using a dropdown for route changes, and update the trigger button text to reflect the current selected route, and use the `active` prop on the `dropdown-item` taht reflects teh current choice, (or use the router `active-class="active"` setting to let vue-router mark the appropriate item as active).
