### ISSUE TITLE
How to use it in RTL?

### ISSUE THREAD

**Issue by ahmdqader** [bootstrap-vue/bootstrap-vue#3483]
Hey guys, you're doing great work, just I wanted to ask, how to use RTL version because you didn't mentioned it on the documentation, and thank you

**Comment by iziynaser** [comment]
i have the same problem,can i change it dynamically by selecting with user decision?

**Comment by tmorehouse** [comment]
Unfortunately Bootstrap V4.3 SCSS/CSS wasn't designed with RTL support built in

https://github.com/twbs/bootstrap/issues/24807
https://github.com/twbs/bootstrap/issues/28238
https://github.com/twbs/bootstrap/issues/28797

**Comment by tmorehouse** [comment]
You might have some minor luck by adding the `dir="rtl"` attribute to the `<html>` or `<body>` tags.

**Comment by iziynaser** [comment]
thanks , tmorehouse
your comment and this https://github.com/ashour/vuejs-i18n-demo project was useful

**Comment by tmorehouse** [comment]
Another option that **might** work is to run Bootstrap's (and BootstrapVue's) CSS through https://www.npmjs.com/package/postcss-rtl
