### ISSUE TITLE
Modals in Custom Components result in a Black Screen

### ISSUE THREAD

**Issue by gmuehl** [bootstrap-vue/bootstrap-vue#3485]
I am not sure if this is a Bootstrap-Limitation or a BootstrapVue-Issue:

I  have globally included Bootstrap-Vue so it is working in all custom Components. I added this Code from the Doc to the Custom Component:

```
<b-button v-b-modal.modal-1>Launch demo modal</b-button>
<b-modal id="modal-1" title="BootstrapVue">
    <p class="my-4">Hello from modal!</p>
</b-modal>
```
Pressing the Button results in a Black Screen and Chrome goes to 100% CPU usage.

As soon as i copy the 

`<b-modal>`

 to the end of the Template in App.vue everything works fine. I think i once had this Issue in Vanilla Bootstrap. Though, if i inspect the Code the Modal is injected at the right Place of the DOM !?

**Comment by Hiws** [comment]
By blackscreen do you mean that the modal backdrop appears over the modal?

If so, I experienced that issue a few weeks back and the accepted answer in [this thread](https://stackoverflow.com/questions/10636667/bootstrap-modal-appearing-under-background) helped me solve my issue.

Though the 100% CPU usage does sound odd. Never experienced that before.

**Comment by gmuehl** [comment]
Nope, it's not the Backdrop, there is no Opacity on it. The screen is really dark black.

**Comment by Hiws** [comment]
The custom component which has the Modal in it wouldn't happen to be present multiple times on the page?
Meaning 1 click could possible trigger all the modals in each component. layering backdrops and making it appear black, which could also explain why the CPU is going crazy trying to render a bunch of modals at once. 

Sadly if that's not the case I don't have any other ideas without some sort of reproduction. Sorry :(

**Comment by gmuehl** [comment]
Damned, you are right, this could be the Problem. I have it twice on the Page both with the same Id because of Copy&Paste from the Docs

**Comment by gmuehl** [comment]
You were right, after some fight to get the Id's dynamic it is working now. So the Problem shows up, if you use two Modals with the same Id

**Comment by tmorehouse** [comment]
Modal IDs must be unique in the same document.

You can do this with the latest version of Vue:

```html
<template>
  <div>
    <b-button v-b-modal.[modalIid]>Launch demo modal</b-button>
    <b-modal :id="modalId" title="BootstrapVue">
      <p class="my-4">Hello from modal!</p>
    </b-modal>
  </div>
</template>
<script>
export default {
  data() {
    return {
      modalId: 'modal'
    }
  },
  beforeMount() {
    // use this component's unique client-side Vue ID
    this.modalId = `modal-${this._uid}`
  }
}
</script>
```
