### ISSUE TITLE
Customize radio-group with slots

### ISSUE THREAD

**Issue by MaratEldarov** [bootstrap-vue/bootstrap-vue#3486]
Please add an opportunity to add custom elements, such as links, to radio-group labels. It will be nice if checkbox disabled for some reason and in a text you can specified link to some page, that will lead you to reason, why it is off

**Comment by tmorehouse** [comment]
When placing individual radios inside a radio-group, you can use the default slot of `b-form-radio` to place any content inside the label

**Comment by tmorehouse** [comment]
```html
<template>
  <div>
    <b-form-group label="Individual radios">
      <b-form-radio-group id="the-radios" v-model="selected" name="radios" stacked>
        <b-form-radio value="A">Option B <a href="#bar">info</a></b-form-radio>
        <b-form-radio value="B" disabled>Option B <a href="#foo">info</a></b-form-radio>
      </b-form-radio-group>
    </b-form-group>
  </div>
</template>
```

But note placing interactive elements inside a `<label>` can cause accessibility issues: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Accessibility_concerns

**Comment by tmorehouse** [comment]
If using the `options` array, you can use `html` insteaad of `text` to render plain HTML inside of the label:

```js
        options: [
          { html: 'Toggle this <a href="#foo">custom</a> radio', value: 'first' },
          { text: 'Or toggle this other custom radio', value: 'second' },
          { text: 'This one is Disabled', value: 'third', disabled: true },
          { text: 'This is the 4th radio', value: { fourth: 4 } }
        ]
```

**Comment by MaratEldarov** [comment]
@tmorehouse thanks a lot!
