### ISSUE TITLE
Carousel crossfade animation doesn't work on iphoneX

### ISSUE THREAD

**Issue by Qvatra** [bootstrap-vue/bootstrap-vue#3497]
### Describe the bug

Carousel crossfade animation doesn't work on iphoneX. instead no animation applied at all.

### Steps to reproduce the bug

1. on iphoneX go to https://bootstrap-vue.js.org/docs/components/carousel/#crossfade-animation
2. try to slide carousel

### Expected behavior

user sees crossfade animation

**Environment:**

- Device: iPhone X
- Browser: Safari

** details **
I also tried the same for bootstrap and it works:
https://getbootstrap.com/docs/4.1/components/carousel/

**Comment by jackmu95** [comment]
@Qvatra I have tested it on Safari on iPhone X and it is working as expected.
