### ISSUE TITLE
input autocomplete got undefined error when upgrated from rc.19

### ISSUE THREAD

**Issue by Waynezhi** [bootstrap-vue/bootstrap-vue#3498]
### Describe the bug

In my project, I have a user authentication system, which redirects to a login page if not yet signed in (which contains username and password with browser autocomplete support), else redirects to another page

First time user signed in successfully, and then when i refresh the page, since no need to sign in again, the login page redirect to another page, but the username and password are saved in browser and the 2 input fields are filled automatically. Then when I click anywhere, that triggered 

> input onChange event in form-text.js

 and tried to update value by using `this.$refs.input.value`, but here `this.$refs.input` is undefined since the login page's gone.

### Expected behavior

may be better to work like rc.19 version 

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- OS:  Windows 10
- Browser: Chrome
- Version: 75

**Comment by psimyn** [comment]
Probably related to https://github.com/bootstrap-vue/bootstrap-vue/pull/3172

@Waynezhi do you have an example repo showing the form fields? if there's no input element then I don't think form-text mixin shouldn't be called either

**Comment by Waynezhi** [comment]
Difficult to show the whole code, but I just call `this.$route.push({ path: '/welcome' )` to do redirection if already signed in.
`<form ref="formSignin" @submit.prevent>
                  <b-row form>
                    <b-col md="6">
                      <b-form-group>
                        <Label for="email">Email</Label>
                        <b-form-input
                          type="email"
                          v-model="loginForm.username"
                          :state="!$v.loginForm.username.$invalid"
                          name="email"
                          id="email"
                          :disabled="user.loading"
                          placeholder="Your email..."
                          @keyup.enter.native="handleLogin"
                        />
                      </b-form-group>
                    </b-col>
                    <b-col md="6">
                      <b-form-group>
                        <Label for="password">Password</Label>
                        <b-form-input
                          type="password"
                          v-model="loginForm.password"
                          :state="!$v.loginForm.password.$invalid"
                          :disabled="user.loading"
                          name="password"
                          id="password"
                          placeholder="Your password..."
                          @keyup.enter.native="handleLogin"
                        />
                      </b-form-group>
                    </b-col>
                  </b-row>
                  <b-form-checkbox name="check" id="chk_remember" v-model="loginForm.remember">Keep me logged in</b-form-checkbox>
                  <div class="divider"/>
                  <div>
                    <b-alert :show="loginSuccess !== undefined && !loginSuccess" variant="warning">Oops, something wrong</b-alert>
                    <b-alert :show="loginSuccess" variant="success">Signed in successfully, redirecting ...</b-alert>
                  </div>
                  <div class="d-flex align-items-center">
                    <div class="ml-auto">
                      
                      <b-button ref="btnSignin" variant="primary" size="lg" :disabled="$v.loginForm.$invalid || this.user.loading" @click="handleLogin">Sign in</b-button>
                    </div>
                  </div>
                </form>`

**Comment by tmorehouse** [comment]
You would need to check your application state / user-token / store, and conditionally render the login form or issue a browser redirect (router push).

**Comment by tmorehouse** [comment]
You should also use `this.$router.replace({ path: '/welcome' })` instead of `push`, which takes the login page out of the browser history (i.e. back button or page refresh won't re-render the login page).

**Comment by Waynezhi** [comment]
@tmorehouse you're right, replace would be better, so I use the conditionally rendering for login form and the error's gone, but still curious to know why that working in the previous version. thanks

**Comment by tmorehouse** [comment]
You could have been taking advantage of a bug or some other anomaly.

**Comment by tmorehouse** [comment]
Depending on the browser, sometimes autocomplete doesn't trigger an input and/or change event (firefox is notorious for that when pressing the back button to a page with a form on it)
