### ISSUE TITLE
<b-nav-item> Applies wrong class when active property is setted to True

### ISSUE THREAD

**Issue by maxell4o** [bootstrap-vue/bootstrap-vue#3499]
### Describe the bug
This bug comes when on <b-nav-item> you have property **active-class** and **:active="true"**
and the class added on element is 'active' not the class specified in **active-class** property

### Steps to reproduce the bug
`<b-nav-item active-class="custom-class" :active="true" to="/">Link</b-nav-item>`
result of this is 
`<a href="#/" class="nav-link active" target="_self">Link</a>`

### Expected behavior
Expected result for me need to be
`<a href="#/" class="nav-link custom-class" target="_self">Link</a>`

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Comment by tmorehouse** [comment]
the `active-class` prop is used by `<router-link>` (when supplying a `to` prop) and is applied when the current route matches the `to` prop.  https://bootstrap-vue.js.org/docs/reference/router-links#active-class

The `active` prop applies the bootstrap V4 `.active` class on the item.
