### ISSUE TITLE
Toast quem be emmited by vuex module

### ISSUE THREAD

**Issue by derevandal** [bootstrap-vue/bootstrap-vue#3502]
### Describe the bug

When I use `this.$bvToast` inside a vuex module, I get this error:
`TypeError: Cannot read property 'toast' of undefined`
But I can use toast from any component.

### Expected behavior

I think it should trigger the toast.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Nuxt: 2.8.1

**Comment by tmorehouse** [comment]
Vuex is not extended from the `Vue.prototype`, and hence doesn't have the same `this` instance that components and apps do.

**Comment by tmorehouse** [comment]
However, I believe Vuex may have access to the Vue VM via `this._vm` 

https://github.com/vuejs/vuex/issues/1399

**Comment by derevandal** [comment]
@tmorehouse thanks, man!
It resolved!
`this._vm.$bvToast.toast()`
