### ISSUE TITLE
[b-table] Sorting clears selected rows

### ISSUE THREAD

**Issue by Arquiel** [bootstrap-vue/bootstrap-vue#3508]
Hi,

I found when the sort-changed callback is triggered (by clicking on a sortable column), all selected rows are deselected. There isn't anything in the documentation about how to turn this off.

Is this resolvable on my end?

Thanks,
Chris

**Comment by tmorehouse** [comment]
Any change to sorting, pagination or filtering (or refreshing the items array) will clear the currently selected rows.

See the notes section at https://bootstrap-vue.js.org/docs/components/table#row-select-support

**Comment by allaghi** [comment]
you can put checkbox in field of the table, and then insert each selected row id into array like this

`
onRowSelected (value, index, item) {
      var loadedArray = []
      if (parseInt(value) === 1) {
        if (!(value in loadedArray)) {
          loadedArray.push(item.id)
        }
        // select = parseInt(value)
      }
      if (parseInt(value) === 0) {
        loadedArray.splice(loadedArray.indexOf(item.id), 1)
      }
      console.log(loadedArray)
    },
`
