### ISSUE TITLE
Please add info, success colors to checkboxes - currently there is no way to do it

### ISSUE THREAD

**Issue by nigel-dewar** [bootstrap-vue/bootstrap-vue#3509]
### Is your feature request related to a problem? Please describe...

with the checkboxes, the color is only blue. primary. There seems to be no way to set the checked color to info or success (green) colors

### Describe the solution you'd like

please add additional variant to checkboxes so can use info, success, warning colors etc

**Comment by tmorehouse** [comment]
Currently the custom style checkboxes are defined via Bootstrap V4.3 SCSS/CSS.

You would need to open an issue at https://github.com/twbs/bootstrap/issues

**Comment by tmorehouse** [comment]
If you are looking to change the default color used, you can set the `$custom-control-indicator-checked-color` Bootstrap SCSS variable and recompile the SCSS to CSS.
