### ISSUE TITLE
<b-table> no-local-filtering prop missing

### ISSUE THREAD

**Issue by mirorauhala** [bootstrap-vue/bootstrap-vue#3511]
### Describe the bug

A prop is missing that is listed in the documentation. 

### Steps to reproduce the bug

1. Go to [**DEMO LINK**](https://codesandbox.io/embed/bootstrapvue-local-filtering-bug-gendw)
2. Type anything to the input
3. See that the table has filtered
4. See in code that the table has `no-local-filtering` prop set to true

### Expected behavior

Nothing.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.23
- Bootstrap: 4.3.1
- Vue: ^2.5.22

**Environment:**

- Device: Windows PC
- OS: Windows 10
- Browser: Firefox 
- Version: 67.0.2 (latest as of writing)

### Demo link

https://codesandbox.io/embed/bootstrapvue-local-filtering-bug-gendw

**Comment by tmorehouse** [comment]
I'm thinking that the docs were not updated to remove this no-longer used prop `no-local-filtering` as there are no built in controls for controlling filtering.
