### ISSUE TITLE
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'focus' of undefined"

### ISSUE THREAD

**Issue by ndabAP** [bootstrap-vue/bootstrap-vue#352]
> [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'focus' of undefined"

Get this occasionally when I switch between components and reopen a modal. When I reload the page with the modal there is no warning. I'm using:

`this.$root.$emit('show::modal', 'my-modal')`

and

`this.$root.$emit('hide::modal', 'my-modal')`

I use 0.15.5. When I downgrade to bootstrap-vue to 0.15.0 there is no warning at all.

Similar issue: https://github.com/bootstrap-vue/bootstrap-vue/issues/19

**Comment by tmorehouse** [comment]
Hmm, let me check on this one.

**Comment by tmorehouse** [comment]
@ndabAP, is the modal element itself part of the component being switched in/out, or is it a direct child of the app instance?

**Comment by alexbrand** [comment]
Running into this as well. After switching between `<b-tabs>`, I am unable to open a modal and get that error message logged in the console.

**Comment by tmorehouse** [comment]
@alexbrand, similar question, is the modal inside the b-tab or outside of the b-tabs?

**Comment by alexbrand** [comment]
@tmorehouse Actually, I take it back. I am not using `<b-tabs>`. I am switching between nested components using the router's `<router-view>`.

**Comment by tmorehouse** [comment]
OK, so the modal is part of the component that is being switched in/out when the route changes?

**Comment by alexbrand** [comment]
Correct

**Comment by tmorehouse** [comment]
That gives me a few ideas as to which situations to check for the issue.

**Comment by ndabAP** [comment]
Same here as @alexbrand.

**Comment by tmorehouse** [comment]
I'll have a look t this tomorrow.  I think I might have a fix for this.

**Comment by tmorehouse** [comment]
I have created a PR that changes when the focus event happens, which now waits for the show transition to end before setting focus inside the modal.

**Comment by alexbrand** [comment]
Thanks @tmorehouse!

**Comment by tmorehouse** [comment]
This should be available in the next release.

**Comment by ndabAP** [comment]
Wow, awesome :1st_place_medal:! When the next release is dropped I will write feedback here, cheers!

**Comment by tmorehouse** [comment]
Fixed in release 0.15.6

https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/v0.15.6

Please provide any feedback here, and if any problems, we'll re-open this issue

**Comment by pi0** [comment]
(0.15.6 is going to be released in few minutes some changes required :D)

**Comment by ndabAP** [comment]
Works now. Thanks to all!
