### ISSUE TITLE
Slot disappear in one of two tables

### ISSUE THREAD

**Issue by MaratEldarov** [bootstrap-vue/bootstrap-vue#3531]
I'm using two tables in my component. One table contains already added items (channels), and second contains those items that can be added to element of the list (it calls 'package' in my case). Both tables have their own slots with icons for add/delete item from it.
When there is some package that have items in both tables - everything works fine:

![b0YHAeiAwv0](https://user-images.githubusercontent.com/35111740/59599435-8eedd900-910f-11e9-92c2-a5f49dedda9f.jpg)

But when there is no such element something weird start happening.
1. Package with added items table is selected, all good:
![JUSJTV80lTk](https://user-images.githubusercontent.com/35111740/59599708-47b41800-9110-11e9-805d-67e39cc3fcd5.jpg)
2. Right after that I select element with only second table, and there is no slot with icon for add:
![ecTz6rJhapY](https://user-images.githubusercontent.com/35111740/59599851-a5e0fb00-9110-11e9-96d2-e15805aa5651.jpg)
3. And it will work in another direction, if element with only second table will be selected in first place - it will be OK, but if next element will have first table - slot with delete icon will be lost
4. Bug resets when selected element haven't any of two tables
5. Both tables has different fields and items and have only one slot - for their icon (add or delete)

Expected behavior is that both tables will be rendered correctly with their slots

- BootstrapVue: 2.0.0-rc.16
- Bootstrap: 4.3.1
- Vue: 2.5.2

- Device: PC
- OS: Windows 10
- Browser:  Latest Chrome and Firefox

**Comment by tmorehouse** [comment]
Are you defining a fields object or allowing b-table to determine the names by inspecting the items array?

Also, try upgrading to a newer release of BootstrapVue (2.0.0-rc.23) and Vue 2.6.10

Could you provide a minimal reproduction jsfiddle or codepen? you can eport a template from the docs playground.

**Comment by MaratEldarov** [comment]
@tmorehouse bug is gone after I update Vue.js and Bootstrap-Vue to the latest versions, thanks
