### ISSUE TITLE
Inconsistency in Table item provider `sortBy` context.

### ISSUE THREAD

**Issue by tvanriel** [bootstrap-vue/bootstrap-vue#3532]
### Describe the bug

There is an inconsistency in table provider context. When initially requesting items without a sorting preference `ctx.sortBy` is an empty string. but when resetting the sort order (by clicking a non-sortable column). I have however, not tested this with a synchronous function. my provider is asynchronous. 

### Steps to reproduce the bug

1. Create a b-table with one sortable column and one non-sortable column.
2. Use a provider function for the items collection.
3. `console.log(ctx)` as the top line of the provider function.
4. observe how `ctx.sortBy` is in fact an empty string. 
5. Click the sortable column.
6. observe how `ctx.sortBy` now contains the key of the sorted column. 
7. Click the sortable column.
8. observe how `ctx.sortBy` now contains `null`. 
### Expected behavior

I expected `ctx.sortBy` to contain an empty string, as was the default before sorting. 

I believe the current behavour is problematic because the browser serializes `null` to `"null"`. Resulting in my case in the server looking up a column named null when left unchecked.

### Versions

**Libraries:**

- BootstrapVue: bootstrap-vue@2.0.0-rc.22
- Bootstrap: bootstrap@4.3.1
- Vue: vue@2.6.10

**Environment:**

- Device: intel nuc i7-8809G
- OS: Debian GNU/Linux Buster (10)
- Browser: Opera Stable
- Version: 60.0.3255.95

### Demo link

https://jsfiddle.net/5hcg8r32/

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
2.0.0=rc.24 has been released

**Comment by tvanriel** [comment]
Thanks!
