### ISSUE TITLE
b-dropdown-header within b-list-group

### ISSUE THREAD

**Issue by JoergFechner** [bootstrap-vue/bootstrap-vue#3535]
### Describe the bug

Browsers li-tag is renderd within a b-list-group when using b-dropdown-header

### Steps to reproduce the bug

```
                      <b-list-group >
                          <b-dropdown-header style=" text-align: center; font-size: medium; font-style: italic">Filter
                          </b-dropdown-header>
                          <b-button
                                
                                  type="button"
                                  variant="outline-primary"
                                  class="mt-1">
                              Test
                          </b-button>
                      </b-list-group>
```

### Expected behavior

No li-tag rendered

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.1.3
- Vue: 2.5.13

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Chromium
- Electron

### Demo link
https://jsfiddle.net/w7xyonr0/

### Additional context

It worked in release 2.0.0-rc.11

**Comment by tmorehouse** [comment]
`b-dropdown-header` is not a supported child of `b-list-group`. It should only be used as a child of `b-dropdown` or `b-dropdown-group`

**Comment by tmorehouse** [comment]
Dropdowns now render semantic `<ul>`/`<li>` markup for accessibility reasons. https://bootstrap-vue.js.org/docs/misc/changelog#features-v200-rc19

**Comment by JoergFechner** [comment]
And <button> ?

**Comment by tmorehouse** [comment]
I don't see why someone would want to place a dropdown header inside a list-group-item.  Dropdown headers are for dropdowns, not list-groups.

**Comment by JoergFechner** [comment]
OK

**Comment by tmorehouse** [comment]
`b-list-group` has one supported direct child component which is `b-list-group-item`: https://bootstrap-vue.js.org/docs/components/list-group
