### ISSUE TITLE
<b-modal> black background without transparency.

### ISSUE THREAD

**Issue by ivd** [bootstrap-vue/bootstrap-vue#3540]
On trigger of modal window I got black background instead of transparent.
Computed bg div contains only **modal-backdrop** class.
`<div id="modal-add-detail___BV_modal_backdrop_" class="modal-backdrop"></div>`
But in original bootstrap, this div additionally contains **fade** and **show** classes.
`<div class="modal-backdrop fade show"></div>`
If I add this classes in debugger I got transparent bg, as it should be.

**Comment by tmorehouse** [comment]
classes `fade` and `show` are only applied during the transitioning.

Make sure you are including the BootstrapVue CSS.

Duplicate: https://github.com/bootstrap-vue/bootstrap-vue/issues/3438

**Comment by zemunkh** [comment]
Add this line to style.scss in case of you make sure you are importing a right scss file.

@import "bootstrap-vue/src/components/modal/index.scss";

**Comment by kdenaeem** [comment]
@tmorehouse hey, I read your other issues but couldnt find a solution.
My bootstrap vue is imported after 
`@import` '../../node_modules/bootstrap/dist/css/bootstrap.css';
@import '../../node_modules/bootstrap-vue/dist/bootstrap-vue.css';`
I've tried adding `.modal-backdrop {display: none; z-index : -1; opacity : $modal-backdrop-opacity;}`

**Comment by jonalxh** [comment]
It happen to me when i render a modal from a child component. Any solution?

**Comment by MalvinJay** [comment]
Getting the same error. Any solution yet?

**Comment by devzom** [comment]
Bump this issue up. Have same issue as @jonalxh pointed. Happend only when modal is called from child component.

**Comment by devzom** [comment]
@jonalxh great , thanks for answer :) 
 just thinking if it should be **static** if I am using synced slider, 1st on a page and 2nd on BS modal, which have to by synced by $refs.

**Comment by jonalxh** [comment]
@devzom What I did was adding the static prop and setting a v-if in the modal content container when data is available, maybe it'll work for you, it was the only solution I found.

I remember one of the problems was that having modals inside a component will generate the modal opens the same amount of times that child component exists, i.e, if you have a `product` component in your store project and you have 5 products, then 5 modals will be opened when calling the open order, what I preferred to do was just having one modal in parent component and open it with an event.

**Comment by vedmant** [comment]
I have the same issue after upgrading bootstrap-vue from rc, fixed by including bootstrap vue css, previously I didn't need it.

**Comment by ccdredzik** [comment]
@vedmant I am glad I am not the only one doing the upgrade from rc in 2021. Adding the vue css solved for me as well.

**Comment by mafemaybe** [comment]
Hi, I fixed this issue with the property hide-backdrop .

**Comment by Ariful-hasan** [comment]
yes,  It' working with "hide-backdrop" property.
[BootstrapVueModal](https://bootstrap-vue.org/docs/components/modal)

**Comment by APeng215** [comment]
I solve this by import css files in main.js
`import 'bootstrap/dist/css/bootstrap.css'`
`import 'bootstrap-vue/dist/bootstrap-vue.css'`
Obviously, I forgot to import before. Now my main.js:
```import { createApp } from 'vue'
import App from './App.vue'
import { router } from './router'
import { BootstrapVue, IconsPlugin } from 'bootstrap-vue'
// Import our custom CSS
import '../scss/styles.scss'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
// Import only the Bootstrap components we need
import { Popover } from 'bootstrap';

createApp(App).use(router).use(BootstrapVue).use(IconsPlugin).mount('#app')

// Create an example popover
document.querySelectorAll('[data-bs-toggle="popover"]')
  .forEach(popover => {
    new Popover(popover)
  })
```
