### ISSUE TITLE
<b-pagination> not updating when programmatically updating value

### ISSUE THREAD

**Issue by briandhill** [bootstrap-vue/bootstrap-vue#3541]
### Describe the bug

I'm trying to update the <b-pagination> by updating the value binded by v-model programmatically, but it doesn't seem to work.

### Steps to reproduce the bug

Set up b-pagination with valid values for v-model, perPage, and totalRows, and then try setting the v-model value programmatically. I tried doing it with a button on click.

### Expected behavior

It should update the pagination to the value you set it to.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.15
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: hp
- OS: Windows 10
- Browser: Chrome
- Version: 75

### Additional context

**Comment by briandhill** [comment]
Sorry, accidentally posted before I was ready.

**Comment by tmorehouse** [comment]
Could you provide a minimal reproduction jsfiddle or code-pen?

**Comment by briandhill** [comment]
Yeah, if you need to set one of those up, I can.

**Comment by tmorehouse** [comment]
I tried setting the value of `b-pagination` and had no issues using `v-model`.

**Comment by briandhill** [comment]
So it's updating the value to whatever you set? For example, setting the v-model from 1 to 3.

**Comment by briandhill** [comment]
And then it goes to three on the component.

**Comment by briandhill** [comment]
```
<b-pagination class="my-0" v-model="currentTablePage" :per-page="perPage" :total-rows="perPage * totalPages" @input="onPageChange" />
<UCMSButton @click="currentTablePage = 3"></UCMSButton>
```

**Comment by tmorehouse** [comment]
See https://jsfiddle.net/fpxLdjn2/

**Comment by briandhill** [comment]
Yeah, it is working for you. Even when I change it to a button it works. Was there an update between rc15 and rc24 that might have fixed this?

**Comment by tmorehouse** [comment]
There have been several fixes since rc.15

Just released rc.24 a few minutes ago.

**Comment by briandhill** [comment]
Yeah, I'll investigate it further to see it was something in between those that fixed my problem. Thanks for the quick help. 👍

**Comment by briandhill** [comment]
So the problem I was having was that the value being used with v-model wasn't reflecting the currently set value. We have a case where we're using a confirm and if cancel is selected, the pagination shouldn't be updated. What I was trying to do is just set the v-model back to the page it was originally at, but due the event cycle and component life cycle, it wasn't picking up the original value on the first go around. Using `this.$nextTick` got it working. I promise I'll write a better bug report next time.
