### ISSUE TITLE
Filter on only visible columns

### ISSUE THREAD

**Issue by austinstudio** [bootstrap-vue/bootstrap-vue#3543]
I would like to filter my table on only the data that is visible.  It doesn't make much sense to filter on an entire data set.  For instance, I have a column that is an ID for the row.  That ID isn't shown to the user as it is a large number that is used by the service.  I don't want a user to type in 12 for the year December but instead get the rows that have an ID starting with or containing 12.  Any ideas?

**Comment by tmorehouse** [comment]
You can provide your own filter function that can inspect only certain fields

https://bootstrap-vue.js.org/docs/components/table#custom-filter-function

The filter function receives two arguments:

- `item`: the row being inspected
- `filter`: the content of the `filter` prop

And would return `true` if the item (row) is to be shown or `false` if the item (row) should not be shown.

```js
export default {
  data() {
    return {
      items: [...], // your items data for table
      fields: [...] // the fields your table will display
    }
  },
  methods: {
    myFilterFn(item, filter) {
      // Assuming 'this.fields` is a simple array of field keys for this example
      // Using `some` to see if any visible field value contains the string specified by `filter`
      // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some
      return = this.fields.some( key => {
        return item[key].indexOf(filter || '') > -1)
      })
    }
  }
}
```

and then pass the filter function to b-table:

```html
<b-table :items="items" :fields="fields" :filter-function="myFilterFn"></b-table>
```

If `fields` is an array of field objects, then you can create a computed prop that returns the array of key names and run `some` against it

```js
  computed: {
    fieldKeys() {
      return this.fields.map(field => field.key)
    }
  }
```

**Comment by austinstudio** [comment]
Thank you for the help.  We will give this a try.
