### ISSUE TITLE
pop-over stops showing inside b-modal

### ISSUE THREAD

**Issue by xtenpeben** [bootstrap-vue/bootstrap-vue#3544]
### Describe the bug

A `<b-popover>` inside a `<b-modal>` with triggers 'click blur' have stopped showing in 2.0.0.-rc23

### Expected behavior

<b-popover> to show / open up. 

**Environment:**

- Device: Laptop
- OS: Windows10
- Browser: Chrome
- Version: 74.0.3729.169

**Comment by tmorehouse** [comment]
@xtenpeben It is working in this fiddle: https://jsfiddle.net/dwr3hbja/

Could you create a minimal reproduction of the issue?

**Comment by xtenpeben** [comment]
Looks like a build issue on my end.
