### ISSUE TITLE
b-form-file and b-form-invalid-feedback

### ISSUE THREAD

**Issue by tradingstratagem** [bootstrap-vue/bootstrap-vue#3545]
### Describe the bug
The b-form-file doesn't show the b-form-invalid-feedback element when the validation fails

### Steps to reproduce the bug

This is the code
 ```
<b-form-group label="File">
    <b-form-file
            v-model="$v.form.file.$model"
            :state="$v.form.file.$dirty ? !$v.form.file.$invalid : 'null'"
            @change="processFile">
    </b-form-file>
    <b-form-invalid-feedback>
        This is a required field
    </b-form-invalid-feedback>
</b-form-group>
    <b-form-group label="Name">
    <b-form-input
            type="text"
            v-model.trim="$v.form.name.$model"
            :state="$v.form.name.$dirty ? !$v.form.name.$invalid : 'null'"
            placeholder="Enter preset name">

    </b-form-input>
    <b-form-invalid-feedback>
        This is a required field
    </b-form-invalid-feedback>
</b-form-group>
```

and this is the result:
<img width="818" alt="Screenshot 2019-06-19 at 07 29 07" src="https://user-images.githubusercontent.com/38089167/59728600-f79a9a00-9264-11e9-8077-4c27d331c573.png">

### Expected behavior

When the validation fails the b-form-invalid-feedback should be visible

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.24
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome
- Version: 77

### Additional context

The code seems correct to me. It is a bug?

**Comment by tmorehouse** [comment]
This is a known Bootstrap V4.3 issue with how their CSS works (and the need for sibling selectors)

https://github.com/twbs/bootstrap/issues/27164

You can however, use the `state` prop on both `b-form-file` and `b-for-invalid-feedback` to mark them as invalid (which force shows the invalid-feedback. If the custom form input has invalid feedback as a sibling (after the input) you only need to set state on the custom file input (as it will have the `is-invalid` class)

**Comment by tradingstratagem** [comment]
Thank you
