### ISSUE TITLE
b-tabs component is not working internet explorer 11

### ISSUE THREAD

**Issue by yurticikargoit** [bootstrap-vue/bootstrap-vue#3546]
I am using  b-tabs component in my page.Component is working correctly in chrome and firefox but when i tried to run my page on internet explorer 11 i got the errors below

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: localhost:8080
HTML1300: Navigation occurred.
File: localhost:8080
[HMR] Waiting for update signal from WDS...
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
[Vue warn]: Error in render: "TypeError: Object doesn't support property or method 'find'"

found in

---> <BTabs>
       <Dashboard> at src/views/Dashboard.vue
         <DefaultContainer> at src/containers/DefaultContainer.vue
           <App> at src/App.vue
             <Root>
TypeError: Object doesn't support property or method 'find'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'find'",
      message: "Object doesn't support property or method 'find'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'find'
   at render (eval code:635:5)
   at Vue.prototype._render (eval code:3545:7)
   at updateComponent (eval code:4063:7)
   at get (eval code:4476:5)
   at Watcher (eval code:4463:3)
   at mountComponent (eval code:4070:3)
   at Vue.prototype.$mount (eval code:9047:3)
   at Vue.prototype.$mount (eval code:11941:3)
   at init (eval code:3124:7)
   at createComponent (eval code:5973:9)"
   }

[Vue warn]: Error in mounted hook: "TypeError: Object doesn't support property or method 'find'"

found in

---> <BTabs>
       <Dashboard> at src/views/Dashboard.vue
         <DefaultContainer> at src/containers/DefaultContainer.vue
           <App> at src/App.vue
             <Root>
TypeError: Object doesn't support property or method 'find'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'find'",
      message: "Object doesn't support property or method 'find'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'find'
   at updateTabs (eval code:476:7)
   at mounted (eval code:370:5)
   at invokeWithErrorHandling (eval code:1862:5)
   at callHook (eval code:4216:7)
   at insert (eval code:3145:7)
   at invokeInsertHook (eval code:6341:9)
   at patch (eval code:6560:5)
   at Vue.prototype._update (eval code:3945:7)
   at updateComponent (eval code:4063:7)
   at get (eval code:4476:5)"
   }

[Vue warn]: Error in nextTick: "TypeError: Object doesn't support property or method 'find'"

found in

---> <BTabs>
       <Dashboard> at src/views/Dashboard.vue
         <DefaultContainer> at src/containers/DefaultContainer.vue
           <App> at src/App.vue
             <Root>
TypeError: Object doesn't support property or method 'find'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'find'",
      message: "Object doesn't support property or method 'find'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'find'
   at updateTabs (eval code:476:7)
   at Anonymous function (eval code:363:7)
   at Anonymous function (eval code:1988:9)
   at flushCallbacks (eval code:1914:5)
   at run (eval code:75:13)
   at Anonymous function (eval code:92:30)
   at flush (eval code:18:9)"
   }

SEC7118: XMLHttpRequest for http://10.1.105.23:8080/sockjs-node/info?t=1560926415750 required Cross Origin Resource Sharing (CORS).
File: localhost:8080

**Comment by Hiws** [comment]
You're missing the required Polyfills for IE11.

You can checkout this section to read more about it.
https://bootstrap-vue.js.org/docs#browser-support

You can also simply add this script to your site to provide the required polyfills.
`<script src="//polyfill.io/v3/polyfill.min.js?features=es2015%2CMutationObserver" crossorigin="anonymous"></script>`

**Comment by tmorehouse** [comment]
Several components use `Array.find(...)` (and similar methods), which need polyfills for IE11.
