### ISSUE TITLE
PostCSS Config file not found?

### ISSUE THREAD

**Issue by ansonfoong** [bootstrap-vue/bootstrap-vue#3554]
Module build failed: Error: No PostCSS Config found in: C:\Users\Anson\node_modules\bootstrap-vue\dis
    at config.search.then (C:\Users\Anson\Documents\Laundry\client\node_modules\postcss-load-config\s

 @ C:/Users/Anson/node_modules/bootstrap-vue/dist/bootstrap-vue.css 4:14-208 13:3-17:5 14:22-216
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

I am NOT using SASS or SCSS, yet I keep getting this error. I looked everywhere, and there isn't any solution.

**Comment by tmorehouse** [comment]
BootstrapVue doesn't import any SCSS file directly, as it compiles them in to CSS files during our build/dist publish process.

What version of BootstrapVue are you using?

**Comment by rvbarreto** [comment]
I have the same problem, did you solve it?

**Comment by rvbarreto** [comment]
> @ansonfoong BootstrapVue doesn't import any SCSS files directly, as it compiles them in to CSS files during our build/dist publish process.
> 
> What version of BootstrapVue are you using? and are you using yarn/npm to install?

Can we reopen the issue?

**Comment by rvbarreto** [comment]
I solved it by running

`npm install bootstrap-vue bootstrap axios`

in the directory of the project, instead of installing it globally
