### ISSUE TITLE
Clickable pagination ellipsis

### ISSUE THREAD

**Issue by corentindechomet** [bootstrap-vue/bootstrap-vue#3555]
I would like to catch user's click on pagination ellipsis to call a method. The goal is to display more pages under the pagination. 
I tried to use @click on ellipsis slot with no result.
I also tried to add a class on ellipsis slot but it isn't set on parent element and I can't access it easily in vanilla js to detect the click.

Any ideas ?

Thank you !

**Comment by tmorehouse** [comment]
ellipsis is (accessibility-wise) set as `role="separator"` (and is not in the tab sequence) which is not conducive to clicking (especially for keyboard only users and screen reader users, as it is not a link or button element).

**Comment by corentindechomet** [comment]
Thank you for your answer. However I really need to access it. Is there a way to do it ?

**Comment by tmorehouse** [comment]
You would need to set up a native click event listener on an outer wrapper element, and then inspect `evt.target` to see if it was triggered by an ellipsis or not.
