### ISSUE TITLE
<b-table> Apply .sr-only class to specific table cells

### ISSUE THREAD

**Issue by briandhill** [bootstrap-vue/bootstrap-vue#3556]
### Describe the solution you'd like

We sometimes receive table data that doesn't have certain field values set (they're `undefined`). There are also times when we receive data where some fields aren't set in any object of that payload. If we could apply `.sr-only` or some class to set the `visibility: hidden` to the `div` inside the `td` if the value is `undefined`. I was able to fill in those td cells if a default value, but the application we're migrating over requires us to hide the value. And we need a value to pass the accessibility rule of `All th elements and elements with role=columnheader/rowheader must have data cells they describe`. Which is why I'm inserting a default value.

### Describe alternatives you've considered

Realize it currently can't be done with the `<b-table>`.

**Comment by tmorehouse** [comment]
You can use scoped slots to check if the value is undefined, and render a `div.sr-only`, else render the value.

**Comment by briandhill** [comment]
Essentially create a slot for each column and render conditionally?

**Comment by tmorehouse** [comment]
Or pass a formatter function to each field you define (in the fields array)  The formatter function could be the same function ref.  The formatter function would return either a default value or the original value:

```
const formatter = (value, key, item) => {
  return value === undefined ? 'Default Value' : value
}
```

**Comment by briandhill** [comment]
I'll try that. Thanks!

**Comment by tmorehouse** [comment]
But to get a conditional div, you will need to use a scoped slot for the field.

**Comment by briandhill** [comment]
Yeah, I'm wondering if I should automatically create all those slots for the accessibility angle.

**Comment by tmorehouse** [comment]
named slots can be built using a v-for loop, and pass the `slot` as `:slot="someVariable"`

**Comment by briandhill** [comment]
Yeah, we're doing that as a way for our developers to dynamically create them, but I might just go ahead and create them all using the fields array if set, or the data array.
