### ISSUE TITLE
b-input-group: prepend-html not working, but prependHTML does

### ISSUE THREAD

**Issue by felix-voicehub** [bootstrap-vue/bootstrap-vue#3565]
### Describe the bug

If I use `prepend-html` on my `b-input-group` it does not show any prepended content. However `prependHTML` does work.

### Steps to reproduce the bug

Does work:
```
			<b-input-group
				size="sm"
				:prependHTML="getPrependHTML('Title')">
				<b-input
					v-model="title"
					type="text" />
			</b-input-group>
```
![image](https://user-images.githubusercontent.com/49151885/60084569-10f58780-9738-11e9-8625-0430d80437b1.png)

Does not work:
```
			<b-input-group
				size="sm"
				:prepend-html="getPrependHTML('Title')">
				<b-input
					v-model="title"
					type="text" />
			</b-input-group>
```
![image](https://user-images.githubusercontent.com/49151885/60084607-1f43a380-9738-11e9-8a3b-54147369373e.png)

The function:
```
		getPrependHTML(value) {
			if (this.required) {
				return `${value} <h6 class="red inline mb-0">*</h6>`;
			}
			return value;
		},
```

### Expected behavior

`prepend-html` as described in the docs should work.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.24,

**Comment by tmorehouse** [comment]
Version 2.0.0-rc.25 has been released.
