### ISSUE TITLE
cannot assign object as value in select

### ISSUE THREAD

**Issue by sprocket99** [bootstrap-vue/bootstrap-vue#3566]
I was using:
```
          <select id="company" class="form-control" v-model="site.company">
            <option v-for="c in companies" :key="c.id" :value="c">
              {{c.name}}
            </option>
          </select>
```

I wanted to convert this to bootstrap-vue but don't know how to specify that the current object is the value itself.

`<b-form-select id="company" v-model="site.company" :options="companies" text-field="name" value-field="???" required>`

**Comment by tmorehouse** [comment]
is `companies` an array of objects, or an object?

If an array of objects with the following (or similar) format:

```js
companies: [
  { id: 1, name: 'Foo Inc' },
  { id: 2, name: 'Bar Co' }
]
```

Use the following to massage into the correct format:

```js
computed: {
  options() {
    return this.companies.map(company => {
      return {
        text: company.name,
        value: company
      }
    })
  }
}
```

which will produce the following array:

```js
[
  { text: 'Foo Inc', value: { id: 1, name: 'Foo Inc' } },
  { text: 'Bar Co', value: { id: 2, name: 'Bar Co' } }
]
```

**Comment by sprocket99** [comment]
It is an array but the solution is just a workaround, I would rather not have to map it as I can do by just using simple bootstrap.

**Comment by tmorehouse** [comment]
The other option is to use `<option>` (also mentioned in the docs):

```
<b-form-select v-model="site.company">
  <option v-for="c in companies" :key="c.id" :value="c">
    {{c.name}}
  </option>
</b-form-select>
```

**Comment by sprocket99** [comment]
Yep. I am doing that, but that gives me a green squiggly in VS 2019. "Element option cannot be nested inside element div".

Anyways, thanks for the quick responses!

**Comment by tmorehouse** [comment]
VS 2019 may assume custom elements to have a root of `div` (in this case the root element of `<b-form-select>` is `<select>`
