### ISSUE TITLE
checkbox "check all" with array reference behaving oddly

### ISSUE THREAD

**Issue by sprocket99** [bootstrap-vue/bootstrap-vue#3569]
This used to work:

```
    <table class="table table-hover table-bordered">
      <thead class="thead-light">
        <tr>
          <th scope="col" style="width: 40px">
            <input type="checkbox" v-model="selectAll">
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="obj in companies" :key="obj.id">
          <td>
            <input type="checkbox" v-model="selected" :value="obj.id" number>
          </td>
        </tr>
      </tbody>
    </table>

    data: function () {
      return {
        selected: []
      };
    },
    computed: {
      ...mapState(['companies']),
      selectAll: {
        get: function () {
          return this.companies ? this.selected.length === this.companies.length : false;
        },
        set: function (value) {
          var selected = [];
          if (value) {
            this.companies.forEach(function (obj) {
              selected.push(obj.id);
            });
          }

          this.selected = selected;
        }
      }
    }
```
Now I am using a different checkbox and its giving odd results:

```
          <th scope="col" style="width: 40px">
            <b-form-checkbox v-model="selectAll" />
          </th>
...
<b-form-checkbox v-model="selected" :value="obj.id" />
```

![odd checkbox](https://user-images.githubusercontent.com/52204959/60115499-fccc7d00-976d-11e9-858e-c7259147a784.gif)

The JS code has not changed. I have noticed the attribute `number` does not affect anything.

**Comment by tmorehouse** [comment]
`b-form-checkbox` doesn't have a `number` prop (nor does a plain `<input type="checkbox">`)

I don't quite see the issue in your screen shot GIF

**Comment by sprocket99** [comment]
Checking the row checkbox calls the "set" on `selectAll` computed property. I don't think it should do that. That should only be called from the header being clicked.

**Comment by sprocket99** [comment]
The issue is, that when all three are selected, when I unselect one the others should stay put, its quite clear.

**Comment by tmorehouse** [comment]
Try putting your set in a nextTick:

```js
    computed: {
      ...mapState(['companies']),
      selectAll: {
        get: function () {
          return this.companies ? this.selected.length === this.companies.length : false;
        },
        set: function (value) {
          var selected = [];
          if (value) {
            this.companies.forEach(function (obj) {
              selected.push(obj.id);
            });
          }
          this.$nextTick(() => {
            this.selected = selected;
          })
        }
      }
    }
```

**Comment by tmorehouse** [comment]
`b-form-select` is a component, so it runs through Vue's batch update cycles.  Since you are modifying state in a computed prop, you will need to wait for Vue's batch update cycle to complete before modifying state.

**Comment by sprocket99** [comment]
@tmorehouse sorry till does the same thing.

**Comment by tmorehouse** [comment]
Here is a working fiddle solution: https://jsfiddle.net/hs6u0Lek/

It adds in a check in the setter to only clear if the selected length is equal to the items (companies) length.

**Comment by tmorehouse** [comment]
A slightly better fiddle with better conditional logic (no need to update all if all are selected):

https://jsfiddle.net/hs6u0Lek/1/

**Comment by sprocket99** [comment]
@tmorehouse Perfect thank you, could not have asked for more. I think the original may have worked because I was used HTML check boxes and not a component perhaps?

**Comment by tmorehouse** [comment]
It was probably because of the extra layer of logic/update-cycle wrapping the component version compared to a plain checkbox. that extra bit of time needed to process the selectAll checkbox was enough to bring the race condition out during Vue's update cycle
