### ISSUE TITLE
progress bar animation does not work

### ISSUE THREAD

**Issue by sprocket99** [bootstrap-vue/bootstrap-vue#3573]
The animation is not working, even on the demo page:

https://bootstrap-vue.js.org/docs/components/progress

I think this may be also not working in the underlying bootstrap, but I would like a suggestion for fix.

**Comment by tmorehouse** [comment]
I see the gradient animations happening in the docs. (using latest Chrome on windows)

Make sure you are using the latest Bootstrap V4.3.1 SCSS/CSS (and load it before loading the BootstrapVue CSS)

It also depends on if your browser supports CSS gradient animations.

**Comment by sprocket99** [comment]
Not sure what is going on, I am also using latest chrome:

![animation not working](https://user-images.githubusercontent.com/52204959/60190894-521a9400-982b-11e9-929e-58570d88c8de.gif)

**Comment by tmorehouse** [comment]
Here is what I see:

![progress-anim](https://user-images.githubusercontent.com/2781561/60194294-6b154c00-980f-11e9-9423-6d2fd9c90c1a.gif)

`Prefers Reduced motion` can usually be enabled/disabled in your Operating System control panel (usually under accessibility settings)

Chrome 74+ will respect the settings specified by the OS.  It is possible that you may have enabled this feature on your OS?

**Comment by sprocket99** [comment]
@tmorehouse yes you were right:

![image](https://user-images.githubusercontent.com/52204959/60194710-c0faeb80-9831-11e9-82f2-07bb8261263a.png)

I had the windows setting turned off. Maybe it would be nice to make a note of this next to the animation section.

**Comment by tmorehouse** [comment]
It is part of Bootstrap V4.3 CSS. all their transitions and animations are wrapped in media queries tragetting prefers-reduced-motion (be default and can be turned off when compiling the Bootstrap V4.3.x SCSS)

It is documented under the accessibility section of hte Bootstrap V4.3 docs: https://getbootstrap.com/docs/4.3/getting-started/accessibility/#reduced-motion
