### ISSUE TITLE
[b-tabs] Cannot dynamically switch to a newly pushed b-tab by b-tabs v-model

### ISSUE THREAD

**Issue by tinbtb** [bootstrap-vue/bootstrap-vue#3575]
### Describe the bug
Cannot dynamically switch to a newly pushed b-tab by b-tabs v-model.

### Steps to reproduce the bug
1. Have a b-tabs with v-model tabIndex binding
2. Render b-tab in a v-for loop from an array
3. Have a b-button that dynamically push a new tab to that array and switch to the last tab

### Example code
```
<div id="app">
  <div>
    <b-tabs v-model="tabIndex">
      <b-tab v-for="i in tabArr" :key="i" :title="i"></b-tab>
    </b-tabs>
    <b-button @click="newTab">New tab</b-button>
  </div>
</div>

window.onload = () => {
  new Vue({
    el: '#app',
    data() {
      return {
        tabIndex: -1,
        tabArr : [-1]
      }
    },
    watch: {
    	tabIndex(){
      	console.log(this.tabIndex)
      }
    },
    methods: {
    	newTab() {
      	this.tabArr.push(this.tabArr.length)
        this.$nextTick(()=>{this.tabIndex = this.tabArr.length - 1})        
      }
    }
  })
}
```
### Expected behaviour
On a button click the new tab is added, the tab then immediately becomes active.

### Actual behaviour
The tab that is next to the currently active becomes active. Jitter in the tabIndex value (can be seen by watching for tabIndex).

### Versions
- BootstrapVue: 2.0.0-rc.24
- Vue: 2.6.10

**Environment:**
not relevant

### Demo link
https://jsfiddle.net/tinbtb/dy5Lrfvu/4/

**Comment by tmorehouse** [comment]
The tab will not become "immediately" available, as b-tabs has to run a cycle to detect the tabs and their rendered order (using a DOM query).

Once you have pushed the new tab onto your array, set the active tab index in a `this.$nextTick(() => {.. })`

Alternatively, set the `active` prop on the newly inserted tab.

**Comment by tinbtb** [comment]
Thank you for the quick reply. Please take a look at the code or the jsfiddle. I'm already switching the tab in a nextTick, but it doesn't help at all.

**Comment by tmorehouse** [comment]
yeah... looked after I replied.

because of the update cycle that B-Tabs needs to do when detecting new tabs (and not to trigger an endless update loop), we use nextTicks and requestAnimationFrame (to handle the default transition timing).

Here is an example fiddle that works, using a double nextTick and RequestAnimationFrame:

https://jsfiddle.net/to0vL4wu/

What is happening is that b-tabs tries to respect previously active b-tab's _localAvtive_ state when new tabs are added (unless they are explicitly added with the `active` prop set)

**Comment by tinbtb** [comment]
Thank you! 
RequestAnimationFrame did the trick and more than that it's enough to call it even without $nextTick. 
```

      newTab() {
        const newIndex = this.tabArr.length
        this.tabArr.push(this.tabArr.length -1)
        requestAnimationFrame(() => {
          this.tabIndex = newIndex
        })
      }
```
https://jsfiddle.net/tinbtb/vd7s94f1/

I wonder if there is a way to know when it's mandatory to have a $nextTick for sure. For example, in my app there is a lot of computed properties and watchers and some of them are cound to tabs. I assume that they can also be triggered after the tab push and can delay the actual rendering. Should I do more of the nested $nextTick in this case? 
It would be great if there was some kind of callback after tabs render to wait for instead of relying on a $nextTick.

**Comment by tmorehouse** [comment]
We might be able to find a way to emit an event when the detected tabs change (additions/removals)

**Comment by tinbtb** [comment]
That would be golden. I'm looking forward to see this feature in future releases.

**Comment by tmorehouse** [comment]
We will be introducing a `changed` event, which will be emitted whenever child tabs are added, removed, or re-ordered. It will fire off once the render/state update cycle has completed.
