### ISSUE TITLE
Table sorting 

### ISSUE THREAD

**Issue by ravipatel6** [bootstrap-vue/bootstrap-vue#3576]
### Steps to reproduce the bug

1. Go to [https://bootstrap-vue.js.org/docs/components/table/#comp-ref-b-table]
2. Click on [Sorting]
3. Scroll down to [Table]
  click on Last Name(sortable: true) column and then click on isActive (sortable: false) column
  after click on isActive column sorting is still happened 
### Expected behavior

sorting should not happen on click on isActive column because sortable: false 

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Demo link

https://bootstrap-vue.js.org/docs/components/table/#comp-ref-b-table

**Comment by tmorehouse** [comment]
When you click on a non-sortable column, it clears any previous sorting, returning to the original order.
