### ISSUE TITLE
How to handle v-slot with vue 2.6 +

### ISSUE THREAD

**Issue by Grandizer** [bootstrap-vue/bootstrap-vue#3580]
Seeing that the `slot-scope` is deprecated and this is used extensively (for us at least in `<b-table>` like the following:

```
return {
  fields: [
    { key: 'PatientName', label: 'Patient', sortable: true },
    ...
};

<b-table …>
  <template slot="PatientName" slot-scope="data">
    {{ data.item.PatientName }}
  </template
  ...
</b-table>
```
And with the new 2.6 syntax for the `v-slot` directive it should be:

```
<template v-slot:PatientName="{ data }">
  {{ data.PatientName }}
</template>
```

I get the following error:
`Property or method "data" is not defined on the instance but referenced during render`

I also assume that `v-slot:PatientName` should be `v-slot:patient-name` or `v-slot:patientname` but then that will not find the field because the data has `PatientName`.

So what is the deal with this new `v-slot` directive?

**Comment by tmorehouse** [comment]
The new method can be used with any of the slots now.

In your second example you are destructuring teh variable, and `data` doesn't exist.

try this:

```html
<template v-slot:PatientName="{ item, value }">
  {{ item.PatientName }}
  <!-- or -->
  {{ value }}
</template>
```

**Comment by Grandizer** [comment]
Ooh - I like that.  Thank you very much!
