### ISSUE TITLE
<b-radio> aria-label isn't being set on radio element

### ISSUE THREAD

**Issue by briandhill** [bootstrap-vue/bootstrap-vue#3582]
### Describe the bug

`aria-label` is not being set on radio input element.

### Steps to reproduce the bug

1. Setup `<b-radio aria-label="test">`.
2. Inspect element.

### Expected behavior

Should set `aria-label` on radio input element.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.15
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: hp
- OS: Windows 10
- Browser: Chrome
- Version: 75

### Demo link

https://jsfiddle.net/pztgj657/2/

**Comment by tmorehouse** [comment]
Upgrade to the latest version of BootstrapVue.

When trying this in the docs the [playground](https://bootstrap-vue.js.org/play):

```html
<div>
  <b-form-radio aria-label="foo">test</b-form-radio>
</div>
```

I see:

![image](https://user-images.githubusercontent.com/2781561/60297070-ccb3e400-98fd-11e9-8d1a-a28a35ec3815.png)

See fiddle using the latest version: https://jsfiddle.net/0ktfyowe/

**Comment by briandhill** [comment]
Will do. I just needed you to tell me that so I can tell the managers on my project that you said to. 😆
