### ISSUE TITLE
Table sorting with "special characters" (e.g. Ä, Ö, Å)

### ISSUE THREAD

**Issue by ttkulm** [bootstrap-vue/bootstrap-vue#3584]
B-Table component does recognize special characters when sorting data, not even the simple ones (e.g. Ä, Ö, Å).

### Steps to reproduce the bug
1. Go to B-TABLE documentation -> sorting (https://bootstrap-vue.js.org/docs/components/table#sorting)
2. Update data, set first names: "Larsen" -> "Ääää" and "Dickerson" -> "Öööö"
3. Sort data ascending by first name and see the data in wrong order: Ääää - Geneva - Jami - Öööö

### Expected behavior
When sorting data ascending by first name the order should be: Geneva - Jami - Ääää - Öööö

**Environment:**
- Bootstrap Vue documentation
- Browser: Firefox 67.0.4

**Comment by ttkulm** [comment]
Tested outside documentation page with Vue 2.6.10 and Bootstrap-vue 2.0.0-rc.24. Same behaviour.

**Comment by tmorehouse** [comment]
The build in sort-compare routine uses the browsers [`String.prototype.localeCompare()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) method, which uses the browser's locale setting (with option 'numeric' enabled).

The default settings are used (with `numeric` enabled):

- `localeMatcher` = `'best fit'`
- `usage` = `'sort'`
- `sensitivity` = `'variant'`
- `ignorePunctuation` = `false`
- `numeric` = `true` (we have enabled this vs the default of `false`)
- `caseFirst` = `'false'` (uses the browsers setting)

**Comment by tmorehouse** [comment]
Release 2.0.0-rc.25 adds in support for passing a `locale` and `options` to be used with the internal sort-compare routine.

https://bootstrap-vue.js.org/docs/components/table#sort-compare-routine
