### ISSUE TITLE
[scrollspy] create jsfiddle examples

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#359]
Scrollspy should have a couple of fiddle example (scrolling on body and scrolling on element).

I'll create a couple of fiddles which @pi0 can fork over to the official fiddle repository.

**Comment by tmorehouse** [comment]
Scrolling on `body` example: https://jsfiddle.net/1r06jsrn/

Scrolling on `div` https://jsfiddle.net/aotuku23/

**Comment by tmorehouse** [comment]
note updated fiddle links...

**Comment by pi0** [comment]
That's so nice @tmorehouse . Will work on integrating into docs.
