### ISSUE TITLE
How to use options array in input-group with radio addons

### ISSUE THREAD

**Issue by Dual-Ice** [bootstrap-vue/bootstrap-vue#3598]
Could you explain how i can set a v-model and an options array to get, for example, 2 inputs with radio addon and switch from one to other?

**Comment by tmorehouse** [comment]
`switch` is a checkbox. you cannot mix checkboxes and radios in the same radio-group.

**Comment by tmorehouse** [comment]
In your case, you just need to use regular `b-form-radio` / `b-form-checkbox`.  And make sure each "group" has a `name` and is bound to the apropriate v-model. 

https://jsfiddle.net/hLu5kdmo/

**Comment by Dual-Ice** [comment]
Thanks for your explanation,  it suits me.
But I have another small problem with it: when I set size="sm" to b-input-group with radio\check addon - result is not nice
The example - https://jsfiddle.net/5rn7ghze/

**Comment by tmorehouse** [comment]
Custom radios and checks currently do not truly support sizes. It is an issue wit Bootstrap V4.3.1 SCSS, which might be addressed in Bootstrap V4.3.2 (and definitely will be in Bootstrap v5 when it is released).

See upstream issue I opened a while back: https://github.com/twbs/bootstrap/issues/27803
