### ISSUE TITLE
Sorting issue in a table

### ISSUE THREAD

**Issue by askorad** [bootstrap-vue/bootstrap-vue#3599]
**Bug description**
I am using `<b-form-checkbox>` in a column of a `<b-table>`. When I check a box and sort the table, the checked box stays on the line number it was set instead of staying on the row it was set...

What am I doing wrong ?

**How to reproduce the bug**
1. Go to this page : https://jsfiddle.net/askorad/3xv5rt92/15/
2. Check the checkbox on the second line (Larsen Show row)
3. Sort by Firstname : the checked box stays on the second line instead of following Larsen Show row

**Comment by tmorehouse** [comment]
Vue tries to efficiently re-use dom elements.

If you have a unique id per row (say field is `id`) then set the primary-key prop to the string `id`. This will generate a Vue key for each tr.

**Comment by askorad** [comment]
That was it! I have updated the fiddle and it’s now working as I was expecting.
Thank you Troy for your help

De : Troy Morehouse <notifications@github.com>
Envoyé : lundi 1 juillet 2019 10:16
À : bootstrap-vue/bootstrap-vue <bootstrap-vue@noreply.github.com>
Cc : Vincent DAVID <vincent@askorad.fr>; Author <author@noreply.github.com>
Objet : Re: [bootstrap-vue/bootstrap-vue] Sorting issue in a table (#3599)


Vue tries to efficiently re-use dom elements.

If you have a unique id per row (say field is id) then set the primary-key prop to the string id. This will generate a Vue key for each tr.
