### ISSUE TITLE
`dismissAfterSeconds` property of b-alert component not working

### ISSUE THREAD

**Issue by cmbankester** [bootstrap-vue/bootstrap-vue#36]
Looking at the code, it appears that setting the `dismissAfterSeconds` property of a b-alert component to `null` should make it so that going from `show == false` to `show == true` doesn't set off the dismissal timer, but that doesn't seem to be working. [See example jsfiddle](https://jsfiddle.net/yk8omsg8/)

Perhaps I'm doing something wrong?

**Comment by mathlet0x** [comment]
You have to do like this : https://jsfiddle.net/yk8omsg8/1/

> HTML attributes are case-insensitive, so when using non-string templates, camelCased prop names need to use their kebab-case

Regards.

**Comment by cmbankester** [comment]
@mathlet0x Gah, thanks so much. Sorry for littering the issues with a dumb question like that. If it's not obvious, I'm still new to Vue.js.

Thanks again!
