### ISSUE TITLE
unknown custom element <b-link> found in <DropdownItem>

### ISSUE THREAD

**Issue by bskimball** [bootstrap-vue/bootstrap-vue#360]
version 0.15.6

I am using the b-dropdown-item component which throws a warning about an unknown element b-link. I am using it in the navbar. 

I see in the source you are trying to extend b-link

**Comment by tmorehouse** [comment]
Is it just a warning, or do you see any errors in functionality happening as well?

**Comment by bskimball** [comment]
Link inside the dropdown doesn't do anything but it doesn't seem to affect other components.

**Comment by tmorehouse** [comment]
Could you provide a quick jsfiddle with an example?

**Comment by bskimball** [comment]
I'm using vue-router. 
In the playground on the website it works fine.
``` javascript
<b-navbar class="navbar-light" toggleable>
  <a href="#"><span>Test</span></a>
  <b-collapse is-nav id="nav-collapse">
    <b-nav is-nav-bar class="mr-auto">
      <b-nav-item-dropdown text="Dropdown">
        <b-dropdown-item to="#">
          Dropdown Item
        </b-dropdown-item>
      </b-nav-item-dropdown>
    </b-nav>
  </b-collapse>
</b-navbar>
```
I'm working on getting it running properly in jsfiddle. 

I'm using it in an SPA using single file components, and importing the components individually.

**Comment by bskimball** [comment]
I've got it working and can generate a PR, it looks like the only thing required is to register b-link as a component. This error probably only occurs when you pull in the components individually, as when you register bootstrap-vue at your entry point, b-link is already a registered component.

**Comment by bskimball** [comment]
I see you have already created and merged the PR. Thank you very much.

**Comment by tmorehouse** [comment]
@bskimball  Yep, there is a pending PR for this :)

**Comment by tmorehouse** [comment]
@bskimball merged into master treet.  Should probably be available in the next release.

**Comment by dipapazacharias** [comment]
I have a similar issue:

"[Vue warn]: Unknown custom element: <b-input-group-append> - did you register the component correctly? For recursive components, make sure to provide the "name" option."

despite having injected bootstrap-vue globally with:  Vue.use(BootstrapVue)   on my main.js. This is the only element that causes a warning. I use other elements without individual import and they are fine.

Any thoughts?

**Comment by yethael** [comment]
I have the exact same issue that @dipapazacharias
