### ISSUE TITLE
Toast is not working when launched from code

### ISSUE THREAD

**Issue by sprocket99** [bootstrap-vue/bootstrap-vue#3600]
This is not working:

```
methods: {
      async doStuff(evt) {
        this.$bvToast.show(`This is toast number`, {
          title: 'BootstrapVue Toast',
          autoHideDelay: 5000,
          appendToast: append
        });
}
}
```

Says:

> vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler (Promise/async): "ReferenceError: append is not defined"

This works however:

```
    <button type="button" @click="$bvToast.show('example-toast')">

    <b-toast id="example-toast" title="BootstrapVue" solid>
      Hello, world! This is a toast message.
    </b-toast>
```

**Comment by tmorehouse** [comment]
In your code you are passing the value value of `append` which is an undefined variable. Replace `append` with either `true` or `false` (or declare the variable `append` to equal `true` or  false`)
