### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by bruxr** [bootstrap-vue/bootstrap-vue#3601]
### Describe the bug

Typo in Validation state feedback section of the <b-form-group> docs.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/form-group#validation-state-feedback
2. On the "Feedback will be shown" paragraph, see typo on the "along with the **vadidated** prop set" part.

### Expected behavior

`vadidated` should be `validated`

### Versions

`v2.0.0-rc.25` docs

**Comment by tmorehouse** [comment]
Thanks.  This will be fixed in the next release.

**Comment by tmorehouse** [comment]
@bruxr BootstrapVue 2.0.0-rc.26 has been released.
