### ISSUE TITLE
Static b-modal not rendered in-place

### ISSUE THREAD

**Issue by Altiire** [bootstrap-vue/bootstrap-vue#3603]
### Describe the bug

When a b-modal is rendered with the props static and visible to true, it is displayed on top of the DOM instead to be in-place

### Steps to reproduce the bug

```
<b-modal :static="true" :visible="true">
<p>Hello</p>
</b-modal>
```

### Expected behavior

Modal is supposed to be rendered in-place

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.24 and 2.0.0-rc.25
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: MacBook Pro 2012
- OS: ArchLinux 64bit
- Browser: Chromium 75.0.3770.100 Arch Linux and Mozilla Firefox 67.0.4

**Comment by tmorehouse** [comment]
static refers to the placement within the DOM.  meaning the rendered elements are where you place the `b-modal` component.  Modals will still be rendered as a modal, overlayed on top of the document (absolutely positioned)

When the `static` prop is not set, the rendered modal elements will be appended to the bottom of hte DOM (i.e. appended to `<body>` )

**Comment by Altiire** [comment]
@tmorehouse Hi, sorry for my misunderstanding. How can I reproduce the static modal from bootstrap documentation ? https://getbootstrap.com/docs/4.3/components/modal/#modal-components
I tried the same settings as their under the b-modal component without success...

**Comment by tmorehouse** [comment]
They are using special styles in their documentation to show the modal inline for illustrative purposes only.

**Comment by Altiire** [comment]
Yes, I did something else because I could not reproduce by using special style overrides.
It may be fun to have a props for displaying a modal without a z-index (so you can have a component that can act like a modal or like a card)

**Comment by tmorehouse** [comment]
You could style a card like a modal...
