### ISSUE TITLE
Memory Leak b-collapse

### ISSUE THREAD

**Issue by camper6** [bootstrap-vue/bootstrap-vue#3607]
### Describe the bug

We have a single page app that I've been diving deep in testing to find the multiple causes of poor performance, one of them I've stumbled across is this.

Including b-collapse results to accumulation of VueComponents when lazy-rendering (e.g. using v-if or vue-router).

### Steps to reproduce the bug

1. Go to [https://codesandbox.io/s/kp5v4](https://codesandbox.io/s/kp5v4)
2. Open chrome devtools - Memory tab
3. Select codesandbox.io in the VM Instance
4. Click on collect garbage (the garbage icon on the top left beneath Elements tab)
5. Click on the 'Mimic Router Switch' buttons 6 times
6. Take a heap snapshot
7. Refresh and repeat step 4. to 6. again, except on step 5. make it 12 times
8. You will see in the heap snapshots the VueComponent number slowly increasing the more you switch views

### Expected behavior

VueComponents recycled properly and the numbers to stay consistent and not grow as the view gets updated.

### Versions

**Libraries:**

- BootstrapVue: ^2.0.0-rc.24
- Bootstrap: ^4.3.1
- Vue: ^2.6.10

**Environment:**

- OS: Windows 10
- Browser: Chrome
- Version:  75.0.3770.100

### Demo link

[https://codesandbox.io/s/kp5v4](https://codesandbox.io/s/kp5v4)

### Additional context

Happens in a clean vue project as well.

**Comment by tmorehouse** [comment]
Thanks for finding this.

It will be fixed in the next release (hopefully out later next week).

**Comment by tmorehouse** [comment]
@camper6 BootstrapVue 2.0.0-rc.26 has been released.
