### ISSUE TITLE
How add font-awesome icon to b-nav-item-dropdown

### ISSUE THREAD

**Issue by tolyanor** [bootstrap-vue/bootstrap-vue#3614]
I try following:

```
<b-nav-item-dropdown v-if="username" :text="username" right class="py-0 fa fa-check">
  <b-dropdown-item @click.prevet="logoutClick" >Exit</b-dropdown-item>
</b-nav-item-dropdown>
```
but it not worked for me. I need font awesome user icon at left of username.
Thanks!

**Comment by akarel** [comment]
You can use the `button-content` slot.

[E.g. From Docs](https://bootstrap-vue.js.org/docs/components/navbar) / [Slot definition for b-dropdown-item](https://bootstrap-vue.js.org/docs/components/nav#comp-ref-b-nav-item-dropdown-slots)
```html
<b-nav-item-dropdown v-if="username" :text="username" right>
    <!-- Using 'button-content' slot -->
    <template slot="button-content">
        <i class="py-0 fa fa-check"></i>
        <em>User</em>
    </template>
    <b-dropdown-item @click.prevet="logoutClick" >Exit</b-dropdown-item>
</b-nav-item-dropdown>
```

Hope that helps.

**Comment by tolyanor** [comment]
Thanks, it worked for me!

**Comment by AkshayLokur** [comment]
How to add an icon inside of `<b-nav-item>` element?
(Above answer is for `<b-nav-item-dropdown>`)
