### ISSUE TITLE
Add "auto" option to left-right menu alignment

### ISSUE THREAD

**Issue by xaviarnl** [bootstrap-vue/bootstrap-vue#3617]
Currently, the menu alignment of a dropdown can be set to either left (default) or right (via "right" prop). It would be very handy if the alignment could be set to (or made) "auto", just like the auto-flipping that you have for the **vertical** placement of the menu.

**Comment by tmorehouse** [comment]
It might be possible, but currently the left/right alignment is control though CSS positioning only (and is not controlled by Popper.JS positioning, unlike the auto-flipping feature).

**Comment by tmorehouse** [comment]
Closing as this is an upstream issue
