### ISSUE TITLE
Problem with electron-webpack integration

### ISSUE THREAD

**Issue by mudlee** [bootstrap-vue/bootstrap-vue#3623]
I have some [very similar](https://github.com/bootstrap-vue/bootstrap-vue/issues/3351) problems with integrating bootstrap-vue with electron-webpack.

The interesting this is that this error only happens if I use the code with electron-webpack. I use bootstrap-vue without any problem in my vue project, but as soon as I put the code under electron-webpack, I get this error.

If I switch back the version to 2.0.0-rc.15, then the error disappears.

However, in both cases with electron-webpack the styles somewhy do not get applied. Again, in a simple vue project, everything is fine. Under electron-webpack, I get the error with the latest version AND I got not styling.

I have a webpack config in package.json:
```json
...
"electronWebpack": {
    "main": {
      "webpackConfig": "webpack.config.js"
    }
}
```

and in the webpack.config.js:
```json
module.exports = {
  "resolve": {
    "alias": {
      "vue": "vue/dist/vue.runtime.esm.js" // yes, I need the runtime
    }
  }
}
```

Any idea?

If I check the electron's html in the debugger, I see no styles for bootstrap inserted.

**Comment by mudlee** [comment]
It looks the problem is that in the end, in the styles.css bundle all the class names are replaced with hashes such as `._2E3BSS9Zyq6QKf-YIbZ_zM[data-v-4c213a9c]`.

**Comment by tmorehouse** [comment]
The error message was introduced after 2.0.0-rc.15 (even though the issue it points to existed in prior versions... we just added it to help people understand the problem)

Electron may have it's own webpack config which points to another different instance of Vue.

**Comment by mudlee** [comment]
Is that possible that the CSS modules (hashing the classes) come from this multiple vue instance?
So basically the css is there in the packed style.css, but all the classes are hashed into a random hash (as I see this is called CSS modules) but the classes on the components are the original, thats why the style is not applied.

**Comment by tmorehouse** [comment]
The CSS issue isn't related to the multiple vue instances.

I think electron makes some assumptions about libraries and that all styles associated with a component are scoped styles (part of a SFC file), which is not the case with BootstrapVue

**Comment by tmorehouse** [comment]
This might help: https://github.com/SimulatedGREG/electron-vue/issues/463

**Comment by tmorehouse** [comment]
And this might be related (depending on how electron sets up vue-loader/css-loader): https://top10webjs.com/2019/03/28/vue-js-vue-not-applying-style-class/

**Comment by tmorehouse** [comment]
And this maybe: https://simulatedgreg.gitbooks.io/electron-vue/content/en/using_css_frameworks.html

(I admit I have zero experience with electron)

**Comment by tmorehouse** [comment]
If a solution is found, we can add it to the docs reference section

**Comment by loopmode** [comment]
@mudlee 
```
"electronWebpack": {
    "main": {
      "webpackConfig": "webpack.config.js"
    }
}
```

shouldn't that be the "renderer" config instead of the the "main"? i guess Vue is only used in the renderer process..?

**Comment by mudlee** [comment]
@tmorehouse: The solution is confirmed from my side, using electron-webpack 2.7.2 solves the problem!
