### ISSUE TITLE
b-nav-item: Option for plain link when using vue-router

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#363]
How do I use the navbar component's `<b-nav-item>` to generate a non-router-link component? Before I was able to use the `href` attr instead of the `to` attr to get plain links vs. router-links (respectively).

My project mixes router-controlled links with real links regularly, so this is a must for me. I'm pretty sure some of the last changes switched this up on me. I've been looking for a vue-router solution, but everyone just says use a normal `<a>` tag. I'm trying to avoid rewriting all the bootstrap markup that this lib does for me so well though!

Here's the gist of the navbar:

```vue
<template>
    <b-navbar toggleable fixed="top" type="inverse" variant="inverse">
        <b-nav-toggle target="hd-navbar-content"></b-nav-toggle>
        
        <b-link class="navbar-brand">
            <a href="https://artisanhd.com">
                <img src="/hd-assets/images/artisanhd-logo-light.svg" alt="ArtisanHD" height="40">
            </a>
        </b-link>
        
        <b-collapse is-nav id="hd-navbar-content">
            <b-nav is-nav-bar>
                <b-nav-item to="/customer/">My Account</b-nav-item>
                <!-- These links need to defer to the browser navigator -->
                <!-- ignore the url prefixing... it's for a reverse proxy, not a vue-router thing -->
                <b-nav-item :href="'/uploadconfigure/' | applyUrlPrefix">Start Order</b-nav-item>
                <b-nav-item :href="'/customer/login' | applyUrlPrefix">
                    <span v-if="isLoggedIn">Logout</span>
                    <span v-else>Login</span>
                </b-nav-item>
            </b-nav>
        </b-collapse>
    </b-navbar>
</template>
```

**Comment by tmorehouse** [comment]
This looks like it might be related to #362

**Comment by alexsasharegan** [comment]
Yeah, does look related. As the link component sits now, either `to || href` props and the presence of `this.$router` will turn it into a `<router-link>`.  There's no escape hatch for a standard link tag.

**Comment by tmorehouse** [comment]
Yeah, that is what I was thinking.  It should only be a router link if `to` is present I would think.

And if neither are present it should not provide any href or two (although not sure how the browser will treat an anchor tag with out an href (as it becomes an anchor rather than a link, so it might require role="link" and explicit click/enter/space handlers when no href or to are supplied.).

**Comment by alexsasharegan** [comment]
Maybe the default href when no attributes are provided can be the plain hash '#'. I think I saw that in the code either before the update or currently. But I certainly agree with that assessment.

**Comment by tmorehouse** [comment]
I'll fiddle around with the b-link code that is pulled into the `b-nav-item` (which is also used for `b-dropdown-item` which also appears to be having a related issue).

**Comment by tmorehouse** [comment]
@alexsasharegan, This should be addresses in next release.

**Comment by alexsasharegan** [comment]
Awesome! Thank you so much!

**Comment by alexsasharegan** [comment]
P.S. This was a solid fix. 👍

**Comment by congtoanle** [comment]
SOLVED: Use either HREF and TO
Example: <b-nav-item href="/explore" to="/explore">Explore</b-nav-item>

**Comment by MarkSky** [comment]
I would like to know, if using vue-router in `<b-nav-item>` has been solved?

**Comment by vandorjw** [comment]
A working example:

https://github.com/vandorjw/assessment-web/blob/master/src/components/blocks/HeaderBlock/Header.vue#L11

demo:
https://vandorjw.github.io/assessment-web/#/

`<b-nav-item :to="{ name: 'SurveyList'}">Survey List</b-nav-item>`

It didn't work for me without the `:` colon in front of `to`

Correct: `:to=`
Incorrect `to=`

**Comment by tmorehouse** [comment]
Yeah, whenever you provide a javascript literal as a prop value, you must use the `v-bind:` (or `:`) syntax.

**Comment by alexsasharegan** [comment]
Also note that there is a known bug when using named routes that has been fixed and slated for the next release.

Essentially the link generated will show `href="#"`, yet navigate to the correct route. Like I said, all fixed and coming soon.

**Comment by abinhho** [comment]
Add `tag="router-link"` then
`<b-navbar-item tag="router-link" :to="{ path: '/home' }">Go to Home</b-navbar-item>`

**Comment by tmorehouse** [comment]
@abinhho `<b-nav-item>` supports the `href` prop which renders a plain link, the `to` prop will render a router-link

**Comment by BartusZak** [comment]
` :to="{ path:  ``${nav.path}`` ` working for me 
```
 <b-nav-item
            v-for="nav in mainMenu"
            v-bind:key="nav.name"
            :to="{ path: `${nav.path}` }"
            >{{ nav.name }}</b-nav-item
          >
```

**Comment by tmorehouse** [comment]
`to` also accepts a plain string path.
