### ISSUE TITLE
Table does not respect Col directive

### ISSUE THREAD

**Issue by iwalucas** [bootstrap-vue/bootstrap-vue#3630]
### Describe the bug

I have a table that should stay inside col-9 but its not staying.

I am migrating some stuff from bootstrap+jquery to only bootstra-vue, and this table is giving me a hard time....

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.1.3
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: Mojave
- Browser: Safari
- Version: 12.1.1

### Demo link

https://jsfiddle.net/walucas/v32L14bf/3/

**Comment by Hiws** [comment]
Simply add the `responsive` prop, will make the table scroll horizontally.

https://bootstrap-vue.js.org/docs/components/table/#responsive-tables

**Comment by tmorehouse** [comment]
@iwalucas There are a few issue with your fiddle.

You have intermediary elements between your rows and cols.  cols must be immediate children of rows (you have `<template>` and `<div>` between them which break layout).

And as @Hiws mentioned, you need to make table `responsive`, as tables have an intrinsic min-width based on their content's width.
