### ISSUE TITLE
b-dropdown performance problem since RC12

### ISSUE THREAD

**Issue by U3R1YXJ0** [bootstrap-vue/bootstrap-vue#3634]
### Describe the bug

I have a b-table with 27 rows. Within each row I have a b-dropdown, which contains 18 b-dropdown-items (486 items in total). I have a completely independent b-form-group containing a b-form-input on the vue page. Note that the table is not relevant, the issue persists if I simply create 27 b-dropdowns with 18 items in each.

Since rc12, when I type (keydown) in the input box, the input is very laggy (the text only in appears in the box with significant latency after hitting the keys).

If I remove or significantly reduce the number of dropdown-items on the page, this issue goes away. On rc11 the input box performs perfectly with no issues.

### Steps to reproduce the bug

1. Create a page using my example, which I will paste at the bottom of this ticket
2. Open/load page
3. Type into the input box, note the lag
4. Revert to 2.0.0rc11, observe that there is no lag

### Expected behavior

The number of drop-down items on the page should not effect the keydown performance of the input box

### Versions

**Libraries:**

- BootstrapVue: 2.0.0.rc12
- Vue: 2.5.17

**Environment:**

- Device: Windows laptop
- OS: Windows
- Browser: Chrome
- Version: 75

### Additional context

Example vue page to recreate problem:

[dropdownPerformance.txt](https://github.com/bootstrap-vue/bootstrap-vue/files/3367916/dropdownPerformance.txt)

**Comment by jackmu95** [comment]
I've created a CodeSandbox example with the given example code.

https://codesandbox.io/s/boostrapvue-b-table-with-b-dropdown-performance-4ro5g

**Comment by tmorehouse** [comment]
This sounds like it might be a rendering issue... something causing the dropdowns to be re-rendered after every keystroke (update of the data model of the app)

**Comment by tmorehouse** [comment]
@jackmu95 I've reduced the test case down to just a v-for loop rendering `b-link`s (the root component of `b-dropdown-item`) and a native iput element, and the issue persists (although not as bad).

It may be the re-rendering of `b-link`, and it setting up new click handlers, etc. As it is a functional component, we may need to convert it to a regular component so that it doesn't have to recreate the handlers on every render.

**Comment by tmorehouse** [comment]
@U3R1YXJ0 

PR #3639 adds a new `lazy` prop to dropdowns, so that their content (menu items) are only rendered when the menu is open, which improves performance.

PR #3637 provides some minimal performance updates to `b-blink` (the base component that `b-dropdown-item` wraps)... but still shows a bit of lag when typing in an input in the reduced test case.

Combining the two (setting the new `lazy` prop on the dropdowns) does show greater performance increase.

Both PR's will be available in the next release 2.0.0-rc.26

**Comment by tmorehouse** [comment]
@U3R1YXJ0 @jackmu95 As a side note, I just tried using an older version of Vue (2.5.22) and performance is greatly improved over Vue 2.6.10

So I think there might also  be an upstream issue that also contributes to affecting performance.

**Comment by U3R1YXJ0** [comment]
@tmorehouse thanks!

I wonder if the issue manifests for other components, for example buttons rather than dropdowns? This might indicate an underlying issue with input keydown causing rerender as you suggested.

**Comment by tmorehouse** [comment]
If you don't put `v-model` on the input, then there is no issue (but it makes it kind of useless without a v-model).

We tested with a few other components and found similar varying issues (when many many components are rendered in the app/component).  We also tried on a few locally defined custom components in the reduced test case (non BV components), and see varying degrees of laggy-ness... which depends on the number of props the component has... the more props the laggy-er it gets.

**Comment by tmorehouse** [comment]
The new `lazy` prop reduces the number of component instances rendered (for dropdown), and we do see a better performance when many, many, dropdowns rendered.

**Comment by tmorehouse** [comment]
With the two PRs merged, and using the new `lazy` prop (when we release 2.0.0-rc.26), you should see a performance increase with the input.

**Comment by tmorehouse** [comment]
@U3R1YXJ0 BootstrapVue 2.0.0-rc.26 has been released.

It contains the minor optimization tweaks to the base `b-link` component (used by `b-dropdown-item`), and the new `lazy` prop for dropdowns (where the dropdown menu contents are not rendered in the DOM/instantiaded, except when the menu is visible).  You will probably find the `lazy` prop provides the most performance boost.

**Comment by U3R1YXJ0** [comment]
@tmorehouse I have rolled this out onto my Production application. It has improved the issue somewhat but there is still very noticeable lag. My Production table has pages of 100 rows, each row has an action drop-down with 8 actions. I therefore under estimated the sizes on the original post. I may reduce the number of rows per page but this will have knock on negative effects.

**Comment by tmorehouse** [comment]
I would suggest adding the new `lazy` prop to your `b-dropdown` instances (if you haven't already)

As well, if you haven't already, make sure you set the `primary-key` prop to a fieldname that has a unique value per row.

See updated fiddle with `lazy` and `primary-key`:

https://codesandbox.io/s/boostrapvue-b-table-with-b-dropdown-performance-c249n

**Comment by U3R1YXJ0** [comment]
@tmorehouse Thanks. I am using `lazy `but not `primary-key`. I have to leave for the day and I am out tomorrow, so will give this a go on Friday.

**Comment by tmorehouse** [comment]
Just thinking about other possible solutions.... one could be a lazy custom renderer wrapper component or custom directive that only renders the compent (i.e. dropdown) when it is in view (or about to be in view)... kind of like v-if, but triggered if the element is in-view or out of view.

**Comment by U3R1YXJ0** [comment]
I tried out primary-key on the table and saw no further improvement.

I have now worked around this issue by removing v-model from the input. I have assigned a ref to the input. When the form is submitted I run a local method, which extracts the input value by ref, and then executes my query.

Solutions suggested so far focus on improving the re-rendering speed. The other way to approach this is to prevent the re-render on every keydown (as above). I note that [vue has a lazy modifier](https://vuejs.org/v2/guide/forms.html#lazy) on form input bindings which changes the input event listener from input to change. This functionality is [not implemented in bootstrap-vue](https://bootstrap-vue.js.org/docs/components/form-input/#input-type)

> v-model.lazy is not supported by <b-form-input> (nor any custom Vue component).

Is this something that could be implemented? Would it help? I have not tested the lazy modifier from Vue so I'm not entirely sure what the effect would be.

**Comment by tmorehouse** [comment]
The lazy modifier changes which event the parent component listens to, and custom components can only be created with one event that controls the v-model (https://github.com/vuejs/vue/issues/6914)

However, if you are just using the input as a plain input (no validation states, no extra fetures), you can use a plain input with the `.lazy` modifier, and just add the class `form-control` to get the bootstrap styling:

```html
<input v-model.lazy="search" type="text" class="form-control">
```
