### ISSUE TITLE
How to avoid double requests when paginating on the server?

### ISSUE THREAD

**Issue by micaelmmendes** [bootstrap-vue/bootstrap-vue#3642]
I'm using an API call to get the table items. The server also handles the pagination. When I first request data, I have to update the per page and total rows properties (because they are used by the pagination component) which causes the table to run the provider function again.

What is the pattern to avoid this double call? Example code follows.

```js
 provider() {
        const promise = axios.get('/test', { params: this._params() });

        return promise.then(
            ({ data }) => {
                this.paginator.perPage = data.per_page;
                this.paginator.totalRows = data.total;

                return data.data;
            },
            () => {
                return [];
            }
        );
    }
```

Thanks!

**Comment by tmorehouse** [comment]
If you do not define your `fields` for b-table, it will need to request the data in order to generate the fields definition on the fly.

**Comment by tmorehouse** [comment]
And, depending on your DB type, you could modify your API call to also return the total rows, current page, page size in addition to your items.

**Comment by micaelmmendes** [comment]
Thanks. My response already includes the pagination data.

What is happening is that when I receive that data (perPage, totalRows), I have to assign them to my Vue component data, because they are used by the b-pagination component.

Since these properties are reactive, they trigger a call to the provider function again, so each time a choose a page, for example, the API call is made twice.

**Comment by tmorehouse** [comment]
If the page data changes (not the same values), and these values are tied to b-table, then it will trigger a refresh by b-table.  are you setting no-provider-paging?  If so, it will definitely trigger a refresh.

An alternate it ot not use provider functions in b-table, and handle the item get API externally in your component, then update b-table's values

**Comment by micaelmmendes** [comment]
Thanks, I was forgetting that I do not have to use the provider function!
