### ISSUE TITLE
docs: A small suggestion

### ISSUE THREAD

**Issue by JackingLuo** [bootstrap-vue/bootstrap-vue#3647]
There is no denying that Bootstrap is a good component library for fast building PC and mobile code, and I also like to use Bootstrap. But compared with other VUE component libraries (such as elementUI), Bootstrap VUE documentation is not friendly to developers. It is hoped that the document will be optimized in later iterations. Convenient for more developers to use!

**Comment by jackmu95** [comment]
@JackingLuo Thanks for your feedback. We always try to make the documentation as developer-friendly as possible.

Would be good if you can give us some more details where you think we can improve or lack details in comparison with the docs of other libraries as Element UI.

**Comment by JackingLuo** [comment]
I think the most unfriendly place is that only type and default values are provided in `Properties', and there is no corresponding function description. In the development project, if you need to add a function, you need to go to the above examples to find, especially the first time to use the Vuer of this component library! Although the naming of attributes is semantic, a word cannot fully describe a function.

**Comment by tmorehouse** [comment]
Currently the component definition is automatically generated by the docs via inspection of the props defined on the component from `componentDef.$options.props`,  Vue currently doesn't provide a prop option property for additional information (which would end up bloating the components with plain text strings not used by the component itself).

There is an interesting discussion at the VueJS repo on this: https://github.com/vuejs/vue/issues/7186

**Comment by JackingLuo** [comment]
Okay, thank you.
