### ISSUE TITLE
b-list-group-item does not support named routes

### ISSUE THREAD

**Issue by stiofanoriain** [bootstrap-vue/bootstrap-vue#3650]
### Describe the bug

If I have HTML as follows:

`<b-list-group-item to="{ name: 'my-named-route' }">Hey!</b-list-group-item>`

The named route won't work, and my router's wildcard (catch-all) route will pick up the request.

Using URLs works fine:

`<b-list-group-item to="/some/path">Hey!</b-list-group-item>`

Note the router does have the corresponding entries, e.g.

```
        path: '/some/path',
        name: 'my-named-route',
```

### Expected behavior

b-list-group-item should support named routes.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.19
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- OS: macOS Mojave
- Browser: Chrome (62.0.3202.94)

**Comment by tmorehouse** [comment]
When passing ab object literal to the prop, you need to use the `v-bind` syntax, otherwise it is interpreted as a string.

```html
<b-list-group-item :to="{ name: 'my-named-route' }">Hey!</b-list-group-item>
<!-- or -->
<b-list-group-item v-bind:to="{ name: 'my-named-route' }">Hey!</b-list-group-item>
```

**Comment by stiofanoriain** [comment]
Ahhh. I'm sorry. Thanks.

I can confirm Troy's response works as expected.
