### ISSUE TITLE
Add Custom Classes to Components

### ISSUE THREAD

**Issue by fdabek1** [bootstrap-vue/bootstrap-vue#3655]
### Is your feature request related to a problem? Please describe...

I need to append custom classes to the BootstrapVue components.  For example, all "b-form-select" should have the classes "n-dropdown" and "n-select" appended to the current list of classes.

### Describe the solution you'd like

A way to update the BootstrapVue default config with a list of classes to append.

### Describe alternatives you've considered

1. Extending each component that I need to add classes onto.
2. In Nuxt.js I could add a hook onto "generate:page" and manually search for elements and append them.

### Additional context

I need to generate HTML templates to place into an existing server/framework.  This existing framework is quite old and looks for elements on the page to contain certain classes.  For example, each <select> element is expected to have two classes on them "n-dropdown" and "n-select".  Then the system uses these to find the <select> elements.

(Yes this is an old and broken system, but I cannot touch or update that part.)

**Comment by tmorehouse** [comment]
Many of BootstrapVue's components have props for placing custom classes on various component sub elements, as well you an apply a class to a component root elements simply by adding the `class="some-class"` attribute to the component.

**Comment by fdabek1** [comment]
> Many of BootstrapVue's components have props for placing custom classes on various component sub elements, as well you an apply a class to a component root elements simply by adding the `class="some-class"` attribute to the component.

Yes, I understand that.  But I was looking for a way to avoid having to continuously have to add that class attribute with those specific classes.  I am going to be creating a lot of templates so that will be hundreds of select components, etc.  Something that would simplify that and make it be less repetitive.  (Or even a way to have a global variable of the classes.)

**Comment by tmorehouse** [comment]
One option is that you could create reusable wrapper components for things that need the special classes added.

**Comment by tmorehouse** [comment]
Are there any specific components that you need this feature for?

**Comment by fdabek1** [comment]
Just for input, checkbox, and select.  I am reading that I would use the extends to wrap it, right?

**Comment by tmorehouse** [comment]
Extends takes a bit of special care to use.  But instead, you can do something like this:

```html
<template>
  <b-form-input class="n-input" v-bind:$attrs v-on:$listeners></b-form-input>
</template>
<script>
import { BFormInput } from 'bootstrap-vue
export default {
  name: 'NInput',
  inheritAttrs: false,
  components: { BFormInput }
}
</script>
```

All attributes will be passed onto the child components, as well as any listeners.

**Comment by fdabek1** [comment]
That actually gave me an error:

> The value for a v-bind expression cannot be empty. Found in "v-bind:$attrs"

**Comment by tmorehouse** [comment]
Had a mistake in the example above.  I have updated it.

**Comment by fdabek1** [comment]
Works perfectly and going to close this now.  Thanks!

Also, for anybody copying the above code: there's a missing quote at the end of the import statement, so make sure to add that.

**Comment by tmorehouse** [comment]
Edited the example and added the missing quote

**Comment by fdabek1** [comment]
I was able to add these components into my templates and import them globally in Nuxt.js, but I am having the issue that any data within them is not appearing.  I believe that this is related to this issue here:  https://github.com/bootstrap-vue/bootstrap-vue/issues/3260

Example:

```
<b-custom-form-select
					size="sm"
					:value="null">
				<option slot="first" :value="null">Choose an item</option>
				<option>1 hour</option>
				<option>1.5 hours</option>
				<option>2 hours</option>
			</b-custom-form-select>
```

The options are not displaying at all.  Do you have a suggestion on how to handle this?

**Comment by fdabek1** [comment]
I was able to resolve this on my own with the following code:

```
<template>
	<BFormSelect class="n-dropdown n-choice" v-bind="$attrs" v-on="$listeners">
		<slot name="first"></slot>
		<slot></slot>
	</BFormSelect>
</template>
<script>
	import {BFormSelect} from 'bootstrap-vue';

	export default {
		name: 'BCustomFormSelect',
		inheritAttrs: false,
		components: {BFormSelect}
	}
</script>
```
