### ISSUE TITLE
Optionally prevent <b-table>'s "sort-changed" event from triggering provider function  

### ISSUE THREAD

**Issue by jake-harris** [bootstrap-vue/bootstrap-vue#3656]
Let me start out by saying a huge thank you for the efforts on this package. I am a few days in the weeds with this issue, so if there's something simple I'm overlooking, I do apologize for the noise, and please feel free to point me in the correct direction.

### Is your feature request related to a problem? Please describe...

In order to handle deeply nested links, I am triggering a `$router.push()` when the sort direction is changed via a listener on `@sort-changed`.  Additionally, I am watching the `$route` object on the parent component and refreshing the table when `$route` changes.

I'd like some way to prevent the `sorting-changed` event from triggering the provider method, because this leads to duplicate provider calls, once when the event triggers, and once when the route changes, calling the `vm.watch()` method which refreshes the table.

### Describe the solution you'd like

Some mechanism to determine what event triggered the provider call: perhaps either an event modifier (e.g. `@sort-changed.prevent`) or an additional context prop or a parameter passed to the data provider function itself.

### Describe alternatives you've considered

I've also considered syncing the sort props on the parent component and then checking in the  callback function mapped to the `@sort-changed` event to see if the values match the `context` object, but it appears at first glance the synced props are already mutated by the time that event fires.

**Comment by tmorehouse** [comment]
Since `@sort-changed` is a custom Vue event, the normal event modifiers (i.e. `.native`, `.prevent`, etc) will not work, as they are expecting native browser Event objects.

You might be able to temporarily set the `no-provider-sorting` prop to `true` before the route change, and then set it back to `false` after the change (although that might trigger a refresh as well).

**Comment by jake-harris** [comment]
After writing out this issue, I was playing around with some ideas, and it doesn't seem to initiate the double call any longer. I'm going to chalk this up to mis-reading the console on very little sleep and or some errant refresh that I was missing previously.

Either way, I'll close this out; thanks so much for the quick response!

**Comment by jake-harris** [comment]
Nope, I lied, I had removed the refresh on route change... so sorry for the spam.

**Comment by tmorehouse** [comment]
Have you tried the no-provider-sorting prop?

Are you sorting on server side or client side?

**Comment by tmorehouse** [comment]
Another option is to move your ajax requests outside of b-table, and just pass the items as an array to b-table

**Comment by jake-harris** [comment]
Yes, I'm sorting on the server side, and I am not using the `no-provider-sorting` prop; should I be?

I got around things by adding a state prop, `isBeingSorted`, to the parent component and then setting it to `false` after the `$route` watcher, which feels pretty janky. I'll sit with it a bit and if it still feels wrong, I'll take a stab at refactoring to the `items` prop, although I do love the inherent value the provider function gives with loading state, etc.

**Comment by tmorehouse** [comment]
You can control the busy state externally as well... its just a bit more work unfortunately.

**Comment by jake-harris** [comment]
Right-o. Had hoped to avoid as much custom implementation as possible, as for 90% of my use case, things are covered.

**Comment by tmorehouse** [comment]
There is also an "issue" when not specifying the field definitions and b-table needs to fetch the data in order to inspect the first row to find the field names.  this can also cause duplicate initial fetches when using provider functions.

**Comment by tmorehouse** [comment]
Just thinking...

The sort-changed event is fired initially on mount.   are you re-rendering the table each route change (i.e. is it tied to the `<router-view>` or similar?)

If you have multiple nested router-views (child router views), you could move the table up one level, but still inspect the `$route` for the full path to get the URL bits you need.

**Comment by jake-harris** [comment]
? The sort-changed event is fired initially on mount. 

Is that only if there is a value given for the `sort-by` prop or something? I hadn't noticed that was the case.

> are you re-rendering the table each route change (i.e. is it tied to the <router-view> or similar?)

It's nested a few levels into the component bound to the router object, so it gets re-used which quite a bit, which was leading to some stale state issues (although I may just be misusing props in all fairness). In any case, the app is _highly_ dynamic and  re-organizing the component structure at this point would be a pretty massive undertaking.

In any case, the quick and dirty prop you suggested seems to get the job done, so please feel free to close this issue out if you'd like, or leave it open for community suggestions. Appreciate all your energy :clinking_glasses:

**Comment by tmorehouse** [comment]
Yeah if the sort params are initially set.

We'll close this for now (but it can still have conversations).  If you find/discover anything else let us know.
