### ISSUE TITLE
Display server side rendered modal on initial page render

### ISSUE THREAD

**Issue by ozguruysal** [bootstrap-vue/bootstrap-vue#3666]
This is a question or maybe a feature request rather than an issue.

On an SSR app I'm willing to display a modal on initial page render before the hydration. Here's how I add the modal to the page.

```vue
<b-modal
    visible
    static
    no-fade
    :lazy="false"
>
    <p>Modal Content</p>
</b-modal>
```

I see the modal is rendered on server side and this is the html.
```html
<div style="position:absolute;z-index:1040;">
  <div
    role="dialog"
    tabindex="-1"
    aria-hidden="true"
    class="modal d-block"
    style="padding-left:;padding-right:;display:none;"
  >
    <div class="modal-dialog modal-md">
      <div role="document" class="modal-content">
        <header class="modal-header">
          <h5 class="modal-title"></h5>
          <button type="button" aria-label="Close" class="close">
            &times;
          </button>
        </header>
        <div class="modal-body"><p>Modal Content</p></div>
      </div>
    </div>
  </div>
</div>
```

Modal has an inline style `display:none;` and there's no backdrop. So modal is displayed only after JavaScript is loaded.

However I want to display the modal immediately. Any way to do this?

**Comment by tmorehouse** [comment]
Modal requires access to the `<body>` element in order to display.  It needs to be able to add classes to it, and adjust padding (based on viewport width, if there is a scrollbar showing on page, etc). None of these "exist" during server side rendering so it would be impossible to show the modal, not until the javascipt has loaded and the page hydrated.

**Comment by ozguruysal** [comment]
I guess the main problem would be adjusting the padding with scrollbar. I believe other stuff can be performed during hydration like you do now.

Thank you for your super quick response!

**Comment by tmorehouse** [comment]
And adding `modal-open` class on the `<body>` element is needed as well...

You could render just a base page with the modal on it (with nothing else that the user can interact with) (i.e. render a dark page).

Like maybe wrap your page content (other than the modal) in the `<no-ssr>` tag.

**Comment by ozguruysal** [comment]
Thanks for ideas. What I currently do is just hide the page content until the modal triggers `show` event. Of course that slightly increases the time the user sees some content.
