### ISSUE TITLE
Possibility to add custom classes to individual cells in <b-table>

### ISSUE THREAD

**Issue by jevgenigavrilov** [bootstrap-vue/bootstrap-vue#3671]
Would be great to have an option to add class/classes to individual cells. I know that we have 
`_cellVariants` property but it prefixes class with `table-`, which works but in our case isn't the best approach because it doesn't fit in our CSS naming convention.

The solution I was thinking of is to add `_cellClasses` prop which will accept a class name/names the same way `_cellVariants` does but without prefixing those.

Here is a screenshot of what I am trying to achieve:
![Screenshot 2019-07-11 at 10 22 17](https://user-images.githubusercontent.com/39730167/61030634-75fedd80-a3c6-11e9-9499-6b3ef1f2846e.jpg)

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0-rc28 introduces a new component `<b-table-simple>` and helper child components `<b-thead>`, `<b-tbody>``<b-tfoot>`, `<b-tr>`, `<b-th>`, and `<b-td>`, which allow you complete control over the table rendering (although it does not have direct `item` and `fields` support... you must handle the rendering yourself). It is basically a wrapper component for `<table>` that provides all the basic Bootstrap table styling, and automated ARIA accessibility markup.

It may not directly solve your issue, but it might help.

**Comment by tmorehouse** [comment]
If you are just trying to apply, say, text color classes to values in a column, you could use the scoped slot for that fields data cells and apply the classes as needed to the content of the scoped slot.

**Comment by tmorehouse** [comment]
Related/duplicate: #3063

Closing in favour of #3063

**Comment by SteffenHebestreit** [comment]
My workaround is the following:

Write a mappingFunction 'mappingFunction.js'

```
export default (tableFields = {}, tableData = []) => {
  const getDataType = key => {
    const field = tableFields.find(item => item.key === key)
    return field ? field.dataType : null
  }

  const cellVariants = {}
  tableFields.forEach(field => {
    cellVariants[field.key] = `cell__data_type--${getDataType(field.key)}`
  })

  return tableData.map(item => ({ ...item, _cellVariants: cellVariants }))
}
```

define the dataType inside the tableFields-Definition and use the mappingFunction

```
<b-table
 ...
 :items="mappingFunction(tableFields,tableData) || []"
 :fields="tableFields"
>
<script setup>
...
import mappingFunction from '...'
...
const tableFields = ref([
{
 key: 'valid_from', dataType: 'date',
 ...
}])
</script>
```

And declare the classes in your styles-css

e.g:
```
tr[role="row"] td.table-cell__data_type {
  &--date {
    ...
  }
}
```
