### ISSUE TITLE
Devtools: <b-form-group> is not nested in <b-form>

### ISSUE THREAD

**Issue by ludo237** [bootstrap-vue/bootstrap-vue#3672]
### Describe the bug

I wrote a component that leverages `<b-form>` and `<b-form-group>` but I can't understand why `<b-form-group>` is rendered outside `<b-form>` inside Vue Inspector

### Steps to reproduce the bug

Basically this is the code 
![image](https://user-images.githubusercontent.com/921500/61038448-5d45f600-a3cd-11e9-83fd-78622fe63c20.png)

And this is the inspector
![image](https://user-images.githubusercontent.com/921500/61038505-6fc02f80-a3cd-11e9-8472-a0554de25475.png)

### Expected behavior

`<b-form-group>` should be nested inside `<b-form>`

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc26
- Bootstrap: 4.3
- Vue: 2.6.10

**Environment:**

- Device: [e.g. Mac or iPhone X] PC
- OS: [e.g. macOS Mojave or iOS 12] Windows 10 using Docker
- Browser: [e.g. Chrome] Chromium
- Version: [e.g. 70] Edge v 0.77

### Demo link

//

### Additional context

//

**Comment by jackmu95** [comment]
@ludo237 Can you confirm that the generated markup is correctly nested? Maybe it's a bug of the inspector.

Can you also make sure that this issue exists with the newest version of BootstrapVue.

**Comment by ludo237** [comment]
Hi @jackmu95 

The generated markup seems correctly nested 
![image](https://user-images.githubusercontent.com/921500/61056091-0b17cb80-a3f3-11e9-8040-411875b6da2f.png)

So probably [vue tools](https://github.com/vuejs/vue-devtools/issues) is broken.

**Comment by tmorehouse** [comment]
@ludo237 are you using `BootstrapVue: 2.0.0-rc6` or is that a type-o and it is `BootstrapVue: 2.0.0-rc26`?

**Comment by ludo237** [comment]
@tmorehouse yes totally a typo I'm on [this release](https://bootstrap-vue.js.org/docs/misc/changelog/#v200-rc26)

**Comment by tmorehouse** [comment]
One thing about Vue Devtools is that it shows the parent hierarchy based on the scope of app/component.

i.e. a child component exists in the component/app scope that it was created in.  `b-form` is functional (has no `this` context), as is `b-card` and `b-card-body`.  Transition is an abstract component.  So if you were to inspect the `b-form-group` (which is not functional) root element in chrome inspector, and check it's `this.$parent`, the first real non-functional component `$parent` is tour custom component.

In chrome inspector, highlight the first b-form-group root element (the `fieldset`), then in the console type `$0.__vue__.$parent` you will see that your app is it's parent.

Vue devtools doesn't show components in their DOM hierarchy, but rather by  their `this.$parent` hierarchy.

**Comment by ludo237** [comment]
That's interesting thanks for sharing
