### ISSUE TITLE
[Component] Datepicker

### ISSUE THREAD

**Issue by rbqdev** [bootstrap-vue/bootstrap-vue#3676]
### Describe the solution you'd like

Would be great to DatePicker component. Usually always need to use third libs or create own for work with Dates on bootstrap.

What you think about it? Do you already have that kind of component in mind?

**Comment by tmorehouse** [comment]
We've thought about it (and I have a rudimentary one built using BootstrapVue components), but we may release these "etrxa" components in a companion library to keep this library bundle size smaller.

**Comment by jevgenigavrilov** [comment]
@tmorehouse defo will be looking forward for this. You mentioned "components", wondering what the others are?

**Comment by rbqdev** [comment]
@tmorehouse Thanks for the detailed explanation.

**Comment by tmorehouse** [comment]
Thinking of creating: BootstrapVueExtras:

- Datepicker (looks similar in style to the android datepicker, based on modal)
- Tags input
- Responsive constrained aspect container (i.e. provide aspect ratio like `16:9`, `4:3`, plus arbitrary contstraints)
- An "in-view" directive (like v-if, but only renders the element when the parent scrolls into view)
- Loader (like spinners, but with the appearance of progress bar)
- A custom select based on dropdown (which allows styling of the options, unlike native select)

**Comment by patrickblackjr** [comment]
I like the idea of having them seperate

**Comment by tmorehouse** [comment]
Some of these might be small enough that they could be included in BootstrapVue, but definitely the date picker will be separate
