### ISSUE TITLE
Is it correct to use bootstrap "order-*" class in order to fix order of b-tab's when slot="tabs" is used?

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#3678]
In case when I "[Add tabs without content](https://bootstrap-vue.js.org/docs/components/tabs/#add-tabs-without-content)" the slot `<template slot="tabs">` becomes the last element (after `<b-tab>'s`) even if in the code the slot is the 1st element. I found that it can be fixed by "order-*" class. Just want to ask, is there any "native" (ie bootstrap-vue) instrument to pin slot at a fixed position (the 1st, the 2nd... but not the last one)?

[Demo as currently is + ordered version.](https://codesandbox.io/s/bootstrap-vue-b-tabs-slot-ordering-r8ooy)

**Comment by tmorehouse** [comment]
Currently, the extra tabs are added last.  we could add a new slot for adding them before.

using CSS `order-*` will work, but it can be confusing for keyboard only users when tabing through (depending on the browser)

**Comment by TitanFighter** [comment]
Probably for "keyboard only users" case it would be good if you "could add a new slot for adding them before".

Thank you for the response.

**Comment by tmorehouse** [comment]
PR #3679 adds in support for a new slot `tabs-start`, and deprecated `tabs` slot in favour of new `tabs-end` slot

**Comment by tmorehouse** [comment]
Bootstrap v2.0.0-rc.27 has been released

New slots for placing extra tabs
