### ISSUE TITLE
Table provider cannot return null since RC12

### ISSUE THREAD

**Issue by U3R1YXJ0** [bootstrap-vue/bootstrap-vue#3683]
### Describe the bug

The b-table documentation describes how to use [provider functions to return data to a table](https://bootstrap-vue.js.org/docs/components/table/#using-items-provider-functions). There is an example 'Using callback to return data (asynchronous)', which has the comment 'Must return null or undefined to signal b-table that callback is being used'.

I have a table with a provider function that has a callback signature. The provider returns null in some circumstances. Since RC12 this provider function was failing silently.

I found that replacing `return null` with `return []` fixed the issue.

The provider function should be allowed to return null, or at least should return an error message when the provider function fails.

### Steps to reproduce the bug

Write a table provider with callback that returns null, it fails. Update the provider to return an empty array, it works. Sandbox provided below

### Expected behavior

Provider function should be allowed to return null. Or else documentation should be updated and a error message thrown on failure.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0.RC12
- Bootstrap: 4.3.1
- Vue: 2.6.10

### Demo link

https://codesandbox.io/s/boostrapvue-b-table-with-b-dropdown-performance-ox50j

Click button to simulate gathering data for the table. Look in the console, the provider function does not execute. If you revert to RC11, the provider function executes successfully.

In RC11, a provider function with callback signature returning `null `works fine. In RC26 the provider fails silently.

If the provider is updated to return an empty array, it works fine in RC26.

**Comment by jackmu95** [comment]
After some investigation I noticed that you mentioned:
> The provider returns null in some circumstances

A provider function with callback should always return `undefined` or `null` to **indicate** that a callback is used. In order to resolve the busy state that is set by the `refresh()` method you need to call the callback.

**Comment by tmorehouse** [comment]
True, if the callback is never called, then the table will remain in the busy state internally.

**Comment by U3R1YXJ0** [comment]
The problem was that I had a condition on whether to execute the callback (checking that the query was valid before executing it). In this case, the provider never worked, even when a query was valid. This behaviour has changed since RC12. If I ensure I execute the callback in all cases, I can return null.

So basically seems fine, although there is not indication in the docs that the behaviour has changed.

**Comment by jackmu95** [comment]
@U3R1YXJ0 The behavior was always meant like this but the implementation was not as strict as now.

**Comment by tmorehouse** [comment]
basically you were taking advantage of a bug in previous versions.

**Comment by U3R1YXJ0** [comment]
@jackmu95 @tmorehouse makes sense, thanks guys!
