### ISSUE TITLE
[Mobile] Table filter does not work until Enter is pressed

### ISSUE THREAD

**Issue by gauravmak** [bootstrap-vue/bootstrap-vue#3684]
### Describe the bug

Table filtering works as expected in the Desktop but when it is opened from a mobile device, "Enter" or "Space" has to be pressed to filter records after typing the search text.

### Steps to reproduce the bug

1. From your mobile, Go to https://bootstrap-vue.js.org/docs/components/table/#complete-example
2. Search for something
3. It doesn't trigger the search until "Enter" or "Space" is pressed.

### Expected behavior

Just like Desktop, it should filter records as the search text is typed.

**Comment by jackmu95** [comment]
I've tested this on a iOS on Chrome and Safari an it works as expected.
Please fill out the environment information.

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

**Comment by gauravmak** [comment]
Thanks for the quick update @jackmu95 

Device: Samsung
OS: Android 9
Browser: Chrome
Version: 75.0

**Comment by jackmu95** [comment]
@gauravmak Run a quick simulation on LambdaTest and it also worked as expected.
Maybe it is a bug/issue with the current Chrome since it's just a simple `<b-form-input>` that is responsible for the input.

Can you please test it out with the default browser of you phone?

**Comment by gauravmak** [comment]
@jackmu95 There is not default browser in the phone. I just downloaded Firefox (version 68.0) and the issue is happening in Firefox as well.

**Comment by tmorehouse** [comment]
Just tested on Android 8.0.0 with chrome & firefox, and do see the issue. Samsung internet appears to work a _bit_ better

It probably has to do with how they keybaord "composition" works (there are issues at Vue.js repo about this), as the keyboard doesn't trigger an input event until you have typed a space or selected a suggested autocomplete word or paused typing for a period of time

**Comment by tmorehouse** [comment]
This wouldn't be table specific, but rather input element specific.

**Comment by tmorehouse** [comment]
I would suggest trying to use a plain input with class `form-component` and seeing if it has similar issues.

```html
<input type="text" v-model-"myModel" class="form-control">
```
And see if there is a similar issue.

**Comment by gauravmak** [comment]
I tried but no luck with that.

**Comment by tmorehouse** [comment]
So this must have to be a browser bug, if you are seeing the same issue with a native browser `input`,

Which keyboard are you using on Android?  The default Samsung keyboard or GBoard? Maybe (as a test) turning off auto-complete/auto-suggest/auto-correct in the keyboard setting may fix the problem.

If so, then you may need to bring an issue up at Vue's repo.

**Comment by tmorehouse** [comment]
A couple of other things you could try:

```html
<input type="search" v-model-"myModel" class="form-control">

<input type="text" inputmode="search" v-model-"myModel" class="form-control">

<input type="search" inputmode="search" v-model-"myModel" class="form-control">
```

(this could also be tried with `b-form-input`)

Search mode is supposed to show a `go` button, which would act as the enter key.

**Comment by gauravmak** [comment]
Thanks, Troy. You're right that this is more of a Vue thing than this repo.

The issue is happening with Samsung keyboard as well as GBoard.
