### ISSUE TITLE
Direct link to ScrollSpy docs doesn't work

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#369]
https://bootstrap-vue.github.io/docs/directives/scrollspy

But if you go to

https://bootstrap-vue.github.io/docs/

Then you can select ScrollSpy under directive and get there OK.

**Comment by tmorehouse** [comment]
I'm not quite sure how the docs work yet, so not sure how to fix at the moment.

**Comment by pi0** [comment]
Ops! Will fix it for next release, Nuxt.js statically renders and creates generates HTML pages. We need to add directives to generate list too.
