### ISSUE TITLE
Is it possible to have subheaders for groups in a b-table?

### ISSUE THREAD

**Issue by Tywele** [bootstrap-vue/bootstrap-vue#3690]
I want to show grouped data in a b-table like this (basically like groups in a ListView in Winforms):

- TableHeader
  - Category1 <-- styled differently
    - Item1 <-- normal table row
    - Item2
    - Item3
  - Category2
    - Item4
    - Item5
    - Item6

Is something like this possible? If yes, how do I do this? If no, could this be implemented

**Comment by tmorehouse** [comment]
Current;y it is not possible to group rows in b-table.

One workaround: https://github.com/bootstrap-vue/bootstrap-vue/issues/2889

The other is to manually create tables (using bootstrap styles) and render the rows and cells as you please:  https://getbootstrap.com/docs/4.3/content/tables/

**Comment by Tywele** [comment]
Could this be implemented? Because the workaround doesn't seem ideal with the top-row slot when the table should still be able to be sorted and filtered.

And creating multiple tables is not the best solution when you want to keep the selectable functionality.
