### ISSUE TITLE
child collapse inside Navbar is closing the parent collapse element on click

### ISSUE THREAD

**Issue by igor-duspara** [bootstrap-vue/bootstrap-vue#3692]
### Describe the bug

I wanted to create a Collapsed menu within the Navbar.

### Steps to reproduce the bug

1. Create a Navbar with a NavItem which is triggering a collapsed menu inside the Navbar.
2. Click on the NavItem
3. Collapsed menu inside the NavBar is shown, but the NavBar itself is closing

### Expected behavior

NavBar should not close.

### Demo link

https://jsfiddle.net/39oLt1pc/

**Comment by tmorehouse** [comment]
`<b-collapse is-nav>` listens for clicks in order to close itself (when the b-navbar is responsively collapsed) . Since you have a collapse within a collapse, the inner collapse, the outer collapse is seeing a click and closing.

**Comment by tmorehouse** [comment]
One workaround (possibly, haven't tested), would be to place an empty `@click.stop` handler on the child `b-collapse`

**Comment by igor-duspara** [comment]
Have tried but with no success. If i use the same structure with native Bootstrap, then it works. I hope you will implement it in the next versions.

**Comment by tmorehouse** [comment]
@igor-duspara Here is a fiddle with a workaround: https://jsfiddle.net/bjL0s1eu/

Normally collapses in a navbar listen for child clicks on child elements that match the class `nav-link`

By not using `b-nav-item` and using `b-nav-text` and placing a link inside that child with the toggle directive, you will get the results you are looking for.

**Comment by tmorehouse** [comment]
Another alternative approach: https://jsfiddle.net/03ft6ma1/

**Comment by tmorehouse** [comment]
@igor-duspara this is probably your best bet:  https://jsfiddle.net/dyezu73w/

This ensures that the collapse toggle (`v-b-toggle` directive) is on the _inner link_ (the `a.nav-link`), and not the outer `li.nav-item` wrapper.  `@click.stop` is placed on the outer-wrapper (the `li.nav-item`) to prevent the click event from bubbling up to the parent collapse element (which is what triggers the parent collapse to collapse).
