### ISSUE TITLE
<b-form-checkbox> not emitting events inside custom table header slot in IE 11

### ISSUE THREAD

**Issue by briandhill** [bootstrap-vue/bootstrap-vue#3693]
### Describe the bug

When slotting `<b-form-checkbox>` into a custom table header slot, the custom checkbox events are not emitted when clicking on the checkbox in IE 11. It works correctly in Chrome.

### Steps to reproduce the bug

Setup a `<b-form-checkbox v-model="test">` inside a custom `HEAD_` slot on `<b-table>` and try checking the box in IE 11. You can also setup a method to attempt to log to the console on the `change` or `input` event, and you will see nothing logged.

### Expected behavior

Should be able to check the box in IE 11.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.26
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: hp
- OS: Windows 10
- Browser: IE
- Version: 11

**Comment by tmorehouse** [comment]
Are you using HTML templates (i.e. compiled on browser side)?

If so, remember that IE 11 doesn't support ES6 syntax in the templates (like `slot-scope="{ label, key }"`), unless they have been pre-compiled

pasting this into the playground in IE 11 works:

HTML:
```html
<div>
  <b-table :fields="fields" :items="items">
    <template slot="HEAD_a" slot-scope="data">
      <b-form-checkbox v-model="checked">{{ data.label }}</b-form-checkbox>
    </template>
  </b-table>
  <p>
    Checked: {{ checked }}
  </p>
</div>
```

JS:
```js
{
  data() {
    return {
      checked: false,
      fields: ['a', 'b'],
      items: [
        {a: 1, b: 2},
        {a: 3, b: 4}
      ]
    }
  }
}
```

And it works:

![image](https://user-images.githubusercontent.com/2781561/61234138-b634c780-a708-11e9-9448-c3cb38b5bbcb.png)

![image](https://user-images.githubusercontent.com/2781561/61234157-c2b92000-a708-11e9-91b4-83b22689c0ef.png)

**Comment by briandhill** [comment]
We're not destructing the slot-scope object in our code, but we are dynamically generating the slots and I'm wondering if that has something to do with it. Investigating a little further.

**Comment by briandhill** [comment]
After further investigation, I believe it has something to do with binding the fields on `<b-table>` to a computed property. I'm not sure why, but that's where it stops working for me.

**Comment by tmorehouse** [comment]
Strange... maybe the computed property isn't always being triggered to refresh.

Or maybe you need to set a unique `key` on the `<b-form-checkbox>`

**Comment by briandhill** [comment]
Yeah, if I change it to a method, it works fine. I'll try setting the `key`.

**Comment by briandhill** [comment]
I believe what's happening is my computed is returning an empty array until I get the data back from the server to load the table. The checkbox then gets render, but for some reason, it doesn't function as your expect. Like it's disconnected.

**Comment by tmorehouse** [comment]
Are you setting `fields` before you are setting `items` when you get your data? or vice versa.

**Comment by briandhill** [comment]
Adding `key` to the checkbox didn't do anything, but returning an array with the computed fields property already set worked fine.

**Comment by briandhill** [comment]
I have the `<b-table :fields="fields" :items="items">` set with computed properties to return an empty array for either if certain conditions aren't met. One of those conditions would be no data existing on the initial load.

**Comment by tmorehouse** [comment]
Is your checkbox v-model tied to data in the fields definition, or to data in your app?

**Comment by briandhill** [comment]
I was just trying to get the checkbox to check. I didn't even set it to a `v-model`.

**Comment by briandhill** [comment]
Do you see anything wrong with this fields structure?
```
[
  {
    "key": "select",
    "class": "text-nowrap",
    "label": ""
  },
  {
    "key": "taskType",
    "label": "Task"
  },
  {
    "key": "identifier",
    "sortable": "true"
  },
  {
    "key": "displayPriority",
    "sortable": "true",
    "label": "Priority"
  },
  {
    "key": "ownerId",
    "sortable": "true",
    "label": "Owner"
  },
  {
    "key": "displayStatus",
    "label": "Status",
    "sortable": "true"
  },
  {
    "key": "taskDate",
    "label": "Create Date",
    "sortable": "true"
  },
  {
    "key": "dueDate",
    "sortable": "true"
  },
  {
    "key": "actions",
    "class": "text-nowrap",
    "label": "Actions"
  }
]
```

**Comment by briandhill** [comment]
It's the `sortable` property.

**Comment by briandhill** [comment]
Just to note, the computed `fields` value works fine.

**Comment by tmorehouse** [comment]
Hmmm.

Sortable sets a `head-clicked` listener.  I wonder if it is the head clicked listener?

the head click listener filters out clicks on actionable items (inputs, labels, buttons, dropdowns, etc), so that it doesn't trigger a head-clicked event.  Although it shouldn't be preventing default on that though.

**Comment by briandhill** [comment]
Yeah, I saw your documentation on that and I didn't make sense to me either that would be affecting it, but I didn't dive into the code find out yet.

**Comment by tmorehouse** [comment]
I just did a quick test setting up a head-clicked event listener (no sorting), and can see the issue in IE 11 (other browsers are fine though)

Switching the custom checkbox for a plain checkbox, everything works in IE.  It must be something to do with the clicking on the label (although the head-clicked handler is supposed to handle clicks on labels, as long as they have a `for` attribute.

After a bit more digging, and adding a label for a plain checkbox, I discovered that IE doesn't have a property `controls` on the label (where as all other browsers do).  So this is the culprit.

Will have to modify the event filter to handle this case a bit differently (perhaps looking for the element by ID from the `for` attribute.

**Comment by tmorehouse** [comment]
I should be able to have a fix for the next release.

**Comment by tmorehouse** [comment]
As an interim workaround, you can add a null `click.stop` handler on the custom checkbox:

```html
<b-form-checkbox @click.stop ...> ... </b-form-checkbox>
```

**Comment by tmorehouse** [comment]
PR https://github.com/bootstrap-vue/bootstrap-vue/pull/3697 definitely fixes the issue

**Comment by briandhill** [comment]
@tmorehouse Thanks man! I'll go ahead and use the workaround until the next release.

**Comment by briandhill** [comment]
I'm still can't check the box even with `@click.stop` set and a `sortable` field set on the table. In case someone else was planning to use that solution in the meantime as well.

**Comment by tmorehouse** [comment]
Hmmm... maybe you might need to wrap the checkbox in a span and put the `@click.stop` on it.

**Comment by tmorehouse** [comment]
Bootstrap v2.0.0-rc.27 has been released

**Comment by briandhill** [comment]
Awesome! I'll give it a whirl today.

**Comment by briandhill** [comment]
Working like a charm! Thanks again for the quick fix! 👏
