### ISSUE TITLE
b-dropdown: The ability to set attributes and properties for b-button object

### ISSUE THREAD

**Issue by drakej** [bootstrap-vue/bootstrap-vue#3694]
### Is your feature request related to a problem? Please describe...

b-dropdown provides only variant as a way to set attributes and style on the b-button it creates

### Describe the solution you'd like

Some way to set properties and attributes on the b-button that's created.

### Describe alternatives you've considered

I have not found one which is why I'm filing this request. 

### Additional context

You need to make sure you don't generate markup and bootstrap components with no flexibility. I'm very concerned that this isn't the only case this plugin breaks or doesn't provide a way to actually use the flexibility of bootstrap itself.

**Comment by tmorehouse** [comment]
Which button's are you referring too, the generated toggle button (which is rendered either as a button, or a link when in navbar), or the `b-dropdown-item-button`?

**Comment by drakej** [comment]
The generated toggle button. Sorry should have made that clear. I haven't found a way I can actually set for example type="reset" instead of type="button" on that generated markup.

**Comment by tmorehouse** [comment]
You can specify `toggle-class` prop to add custom classes to the dropdowns trigger button.

When you want to set `type = 'reset'`, I am assuming you are referring to a split dropdown button?

**Comment by tmorehouse** [comment]
If you are looking to reset a `form` using a split button, you can add a click listener which then invokes the `reset()` method of a `<form>` element (https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset)

**Comment by drakej** [comment]
Good idea, I didn't think of that workaround, but ya that's what I'm trying to do. Was hoping to find a way to set an attribute that would affect the generated markup directly.

**Comment by tmorehouse** [comment]
We might be able to add in a `split-button-type` prop which defaults to `button` (as long as there is no `split-to` or `split-href` prop set). And allows only types `button`, `submit`, `reset`

**Comment by drakej** [comment]
`$el.ownerDocument.getElementById('filter_form').reset()`
^ This worked putting this in @click on the _b-dropdown_ tag

**Comment by tmorehouse** [comment]
Bootstrap v2.0.0-rc.27 has been released
