### ISSUE TITLE
<b-nav-item-dropdown>: Flickers when trying to close with click on dropdown

### ISSUE THREAD

**Issue by McSneaky** [bootstrap-vue/bootstrap-vue#3707]
When trying to close navbar dropdown with clicking on dropdown again it just flickers. Events are triggering twice and you can't close dropdown with clicking on dropdown again, you have to click on some dropdown items or out of dropdown.

How to reproduce:
1) Go to https://bootstrap-vue.js.org/docs/components/navbar/#b-nav-item-dropdown
2) Click on "Lang"
3) Click on "Lang" again to close dropdown. (Only flickering happens) 

How it should work:
Like regular dropdown: https://bootstrap-vue.js.org/docs/components/dropdown

**Comment by tmorehouse** [comment]
Bootstrap v2.0.0-rc.27 has been released
