### ISSUE TITLE
[question] hide BTable and replace it by no items text

### ISSUE THREAD

**Issue by sleleko** [bootstrap-vue/bootstrap-vue#3722]
Hello!
How hide BTable with header and fields names, when count items in 0 ,for example after filtration ?

**Comment by tmorehouse** [comment]
Have you tried the `show-empty` prop?  Adding the prop to `b-table` will show a message when the table has no row or a filter returned 0 rows

https://bootstrap-vue.js.org/docs/components/table#custom-empty-and-emptyfiltered-rendering-via-slots

**Comment by sleleko** [comment]
Yes, but it prop it ony enable message about no items. It prop don,t hide table with no item , its only show message, but in table

**Comment by tmorehouse** [comment]
You would need to listen to the filtered event, or watch the `v-model` to check the length of the items and use `v-show` directive to hide the table (v-if won't work in this case)

**Comment by sleleko** [comment]
> You would need to listen to the filtered event, or watch the `v-model` to check the length of the items and use `v-show` directive to hide the table (v-if won't work in this case)

Yes, v-show its better variant for this, but can you say, how correct call to this event? I,m tryed to use totalRows from method "onFiltered", but its was wrong way..

**Comment by tmorehouse** [comment]
Don't use the filtered event.  use the `v-model`  https://bootstrap-vue.js.org/docs/components/table#v-model-binding

And then check the length of that array

```html
<template>
  <b-form-input v-model="filterValue"></b-form-input>
  <b-button @click="filterValue = ''">Clear Filter</b-button>
  <b-table
    :items="items"
    :fields="fields"
    v-model="displayedItems"
    v-show="displayedItems.length > 0"
  ></b-table>
  <div v-if="filterValue && displayedItems.length === 0">
    No filtered records
  </div>
  <div v-else-if="!filterValue && displayedItems.length === 0">
    No records
  </div>
</template>

<script>
export default {
  data() {
    filterValue: '',
    displayedItems: [],
    items: [ ... ],
    fields: [ ... ]
  }
}
</script>
```

**Comment by sleleko** [comment]
Thank you very much for  provided example, but this solution works only partially, like the solution that I tried before. Because, it works only if the data matching the filter is not at all in one table. If at least there is data in one table, then empty tables are also not removed as with my solution.

**Comment by tmorehouse** [comment]
You would need to do this for each table, each with different variables for conditions.

**Comment by sleleko** [comment]
> You would need to do this for each table, each with different variables for conditions.
The tables are in my loop. Are you talking about this?
`<div v-for="(items, index) in items" v-bind:key="items.index">
                <div>
                    <h3>{{ index }}</h3>
                
                    <b-table
                        
                        :busy.sync="isBusy"
                        show-empty
                        empty-text="Нет доступных данных для показа"
                        empty-filtered-text="Нечего не найдено"
                        :items="items"
                        :fields="fields"
                        v-model="displayedItems"
                        v-show="displayedItems.length > 0"
                        :current-page="currentPage"
                        :per-page="perPage"
                        :filter="filterValue"
                        @filtered="onFiltered"
                    >
                    <template slot="Index" slot-scope="data">
                        {{ data.index + 1 }}
                    </template>

                    
                    <template slot="empty" slot-scope="scope">
                    <h4>{{ scope.emptyText }}</h4>
                    </template>
                    <template slot="emptyfiltered" slot-scope="scope">
                    <h4>{{ scope.emptyFilteredText }}</h4>
                    </template>
                    
                    
                    
                    <div slot="table-busy" class="text-center text-danger my-2">
                        <b-spinner class="align-middle"></b-spinner>
                        <strong>Идёт загрузка данных...</strong>
                    </div>
                    
                    
                    
                    
                    
                    </b-table>
                    <div v-if="filterValue && displayedItems.length === 0">
                        No filtered records
                    </div>
                    <div v-else-if="!filterValue && displayedItems.length === 0">
                        No records
                    </div>
                </div>
                
            </div>`

**Comment by tmorehouse** [comment]
You would need `filterValue` and `displayeditems` to be arrays, indexed by the index of your for loop (or similar), as you would need a separate filter and v-model for each table.

**Comment by sleleko** [comment]
But `filterValue` is a TextInput , and should be a string type or no ? And how `filterValue` and `displayeditems` can be indexed ?

**Comment by sleleko** [comment]
I apologize for many questions, just want to really figure out how to set up correctly

**Comment by tmorehouse** [comment]
An array of sting values... 

And then use the index to pick which string on the array you are using.

`v-model="filterValue[index]"` etc
