### ISSUE TITLE
Add tabindex attribute to <b-dropdown>

### ISSUE THREAD

**Issue by michaelzangl** [bootstrap-vue/bootstrap-vue#3729]
### Is your feature request related to a problem? Please describe...

Currently, there is no way to add the tabindex attribute to the button that opens the dropdown menu.

Current Problem I am having is with a dropdown menu I added to a custom form, which should not be included in the tab flow (tabindex=-1)

### Describe the solution you'd like

A new attribute to define the tabindex of the button that opens the dropdown:
```html
<b-dropdown tabindex="-1"/>
<b-dropdown toggle-tabindex="-1"/>
```
The menu can have one or two buttons, the tabindex attributes should probably both be set independently

### Describe alternatives you've considered

Workaround I use at the moment:

```js
import { BDropdown } from 'bootstrap-vue';

export default {
  mixins: [BDropdown],
  mounted() {
    this.patchTabindex();
  },
  updated() {
    this.patchTabindex();
  },

  methods: {
    patchTabindex() {
      // Fix dropdown button tabindex. We can't do this using bootstrap vue API. 
      // set tabindex="-1"
      this.$nextTick(() => {
        this.$el.querySelectorAll('.btn[aria-haspopup="true"]').forEach(btn => {
          btn.setAttribute('tabindex', '-1');
        });
      });
    }
  }
};
```

**Comment by tmorehouse** [comment]
setting tab-indexes to values other than `0` and `-1` are not overly accessible (specifically to keyboard only users it can be confusing), as any positive value will push the tabbable item to be _last_ on the page.

Can you provide a use case for having tabindex changed on dropdowns?

**Comment by tmorehouse** [comment]
Also, removing an element out of the tab sequence, and that provides functionality will make your form unusable by keyboard-only and screen reader users.

Your best bet would be to disable the dropdown when your form is active.

**Comment by michaelzangl** [comment]
@tmorehouse

The place I want to use this: Adding a <b-dropdown> next to a text field. Inside the dropdown a canvas for entering Hand-written notes / Controls optimized for touch.

Since the controls redundant and should only make the work with finger / pencil easier, they do not need to be accessible. And an input area for hand written notes does not need to be accessible by keyboard as well.

**Comment by tmorehouse** [comment]
That would still be confusing for keyboard users, as they would see the dropdown but not be able to get to it.

**Comment by michaelzangl** [comment]
For this software, we don't expect people to get confused, since there are only few people using it and they all get several days of training ;-)

But yes, setting tabindex=-1 is always a tradeof between not annoying keyboard users with unneeded buttons and not confusing them / not preventing them from using some functionality.

**Comment by tmorehouse** [comment]
An alternative it so detect if the browser has touch support, and only render the dropdown (or the canvas element inside it) if the device is touch enabled.

This can be done either with media queries in CSS, or feature sniffing:

```js
const hasTouchSupport =
  typeof document !== 'undefined' &&
  ('ontouchstart' in document.documentElement || navigator.maxTouchPoints > 0)
```

That way it is only presented to users who have touch support (mobile, or desktop with touch screen)

**Comment by michaelzangl** [comment]
Just tested it: 
```js
'ontouchstart' in document.documentElement => false
navigator.maxTouchPoints => 0
document.addEventListener('touchstart', evt => console.log(evt), true) => logs events
```

Touch enabled device, current Firefox version

**Comment by tmorehouse** [comment]
I've tried the above with Chrome on a touch desktop and works fine.  Appears that Firefox doesn't reflect touch status on desktop's with touch support.

Firefox mobile detection is fin though (as is chrome mobile)

**Comment by michaelzangl** [comment]
Even if i could detect touch support in a reliable way, this won't help me, since I do not know if the user is using touch mode or if he is using the keyboard (which can change even while the user is inside a form, e.g. if the user needs to walk to fill in the next values)

**Comment by tmorehouse** [comment]
Then it is probably best to leave the `tabindex` as default (default tab sequence)

**Comment by thiemeljiri** [comment]
Why was this closed? There are cases when tabindex="-1" is very useful! Plese reopen and give us the possibility to specify the attributes we need. Thanks.

**Comment by michaelzangl** [comment]
@thiemeljiri  The workaround in the first post should still be working.

**Comment by jakedolan** [comment]
An accessible use case for this when using the b-dropdown within a toolbar for use with a wysiwyg. 

[WAI-ARIA toolbar](https://www.w3.org/TR/wai-aria-practices/#toolbar) recommendations involve a [roving tabindex](https://www.w3.org/TR/wai-aria-practices/#kbd_roving_tabindex) so the user is able to tab/shift-tab beyond the toolbar and then return to the most recent button when tabbing back to the toolbar.
