### ISSUE TITLE
Stacked Table seems broken

### ISSUE THREAD

**Issue by felix-voicehub** [bootstrap-vue/bootstrap-vue#3739]
### Describe the bug

The `b-table` with `:stacked="true"` seems to be broken. It is not showing fields below each other, but instead next to each other and without their corresponding labels.

What it looks like:
![image](https://user-images.githubusercontent.com/49151885/61699091-886c0600-ad3a-11e9-8349-79a3bf7912f0.png)

### Steps to reproduce the bug

```
<b-col cols-6>
	<h5>User Base Data</h5>
	<b-table
		stacked
		:items="user" />
</b-col>

// user object
const user = {
    'Created': "May 21, 2019 5:35 PM (2 months ago)"
    'Internal ID': "5ce41ad1a7348d42b3672235"
    'Last Updated': "May 21, 2019 5:35 PM (2 months ago)"
};
```

### Expected behavior

How it should look like:
![image](https://user-images.githubusercontent.com/49151885/61699062-7ee29e00-ad3a-11e9-9821-a38de7ab320c.png)

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc27
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: Mojave
- Browser: Chrome

**Other Info:**

The only thing I changed is switching to the [direct source import method from your documentation](https://bootstrap-vue.js.org/docs#using-bootstrapvue-source-code-for-smaller-bundles), with setting the alias and so on.
The template and data for the tables did not change at all. So either must have something to do with me now importing the `TablePlugin` from the `src` folder, or it is actually a bug.

**Comment by tmorehouse** [comment]
Are you importing the BootstrapVue CSS/SCSS into your project? The stacked table features require BootstrapVue's custom CSS.

When aliasing `bootstrap-vue` ensure you set it as `"bootstrap-vue$": "bootstrap-vue/src/index.js`" (don't forget the trailing `$`)

**Comment by felix-voicehub** [comment]
@tmorehouse Copied from my `vue.config.js`:

```
...
resolve: {
			alias: {
				// Alias to use source of BootstrapVue
				'bootstrap-vue$': 'bootstrap-vue/src/index.js',
                         },
},
```

**Comment by tmorehouse** [comment]
Are you including the Bootstrap+BootstrapVue CSS into your project? Switching to source doesn't change how the CSS is used.

**Comment by felix-voicehub** [comment]
Ahh I get what you mean and it's now working:
In my App.vue entry point I was missing `@import '~bootstrap-vue/dist/bootstrap-vue.css';`.

I was confused because everything else worked perfectly.

**Comment by tmorehouse** [comment]
BootstrapVue specific features (i.e. stacked tables, table sorting, toasts, tooltip/popover variants) all require BootstrapVue's custom SCSS/CSS

**Comment by tmorehouse** [comment]
If you are doing your own CSS minification (which usually happens when using bundlers), then importing the non minified version is best, as you will get better CSS map files (as usually bundlers will bundle multiple CSS files together)
