### ISSUE TITLE
What's the optimize way to use a lot if popovers/tooltips?

### ISSUE THREAD

**Issue by lavezzi1** [bootstrap-vue/bootstrap-vue#374]
Hello there, thanks for great lib. 

I have a huge table with 50-200 items, I need to show menu (inside popover) and tooltips. Now it renders a lot of popovers initially so DOM is huge. Is there a way to have one popover and insert data for it?

Thanks, Ricardo.

**Comment by pi0** [comment]
Hi @lavezzi1 . We are aware of that and planning to migrate from tether to popper.js (#287) as  bootstrap 4 project is also doing the same decision.

**Comment by lavezzi1** [comment]
@pi0 migrate to another lib solve my problem?

**Comment by pi0** [comment]
No not you this is an internal enhancement :)) I will keep this Issue open until that migration is done.

**Comment by asafyish** [comment]
Hi,

Just wanted to update that it's implemented on 1.0.0.beta-6 and it's working awesome! no more thousands of tether divs, and the performance is much much better.

Thanks Allot !

**Comment by tmorehouse** [comment]
We still have issues with the component version to tooltips and popovers (v1.0.0.bta.6), but the directive versions are working well.
