### ISSUE TITLE
transition/animation works with IE 11 but not working with chrome

### ISSUE THREAD

**Issue by markfranchi** [bootstrap-vue/bootstrap-vue#3746]
Hi guys,

today I realized that the transition/animations, for the b-modal component for example. It works correctly in IE 11 but does not work in chrome (75).
I tried the configuration of the component checked and it seems to be installed correctly, what can be the cause of the problem?

Regards

**Comment by tmorehouse** [comment]
Are you using the Bootstrap/BootstrapVue css or source SCSS?

What version of BootstrapVue, Bootstrap, and Vue are you using?

Are modals working for you in the docs https://bootstrap-vue.js.org/docs/components/modal ?

**Comment by markfranchi** [comment]
Hi,

I am using these versions 

"bootstrap": "^4.3.1",
"bootstrap-vue": "^2.0.0-rc.27",
"vue": "^2.6.10",

I'm using boostrap css this way
in main.js 
import Vue from "vue";
....
import BootstrapVue from "bootstrap-vue";

import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-vue/dist/bootstrap-vue.css";

Vue.use(BootstrapVue);

Yes! in this example https://bootstrap-vue.js.org/docs/components/modal the modal works correctly! this is the strange thing.

Regards!

**Comment by tmorehouse** [comment]
Strange.. do you have css-loader set up?

**Comment by markfranchi** [comment]
no, I don't use any css loader

**Comment by tmorehouse** [comment]
Importing CSS into javascript modules requires setting up css-loader/extract-css to get the CSS extracted into it's own modules.
