### ISSUE TITLE
Allow b-table internal filtering to ignore specific keys in an item

### ISSUE THREAD

**Issue by jmason03** [bootstrap-vue/bootstrap-vue#3749]
### Is your feature request related to a problem? Please describe...

There is currently no way to have the default filtering functionality ignore specific keys in an item object. All of the data, except for what is in "_rowVariant", "_cellVariants", and "_showDetails", is compared to the filter text provided by the user. There should be a way to specify additional keys that can be ignored during the filtering process without having to write a custom filter function.

### Describe the solution you'd like

A prop that allows for an array of strings that reference specific keys in an item object that are ignored in the same way the default list, IGNORED_FIELD_KEYS, is treated.

### Describe alternatives you've considered

There are no good alternatives. The best option is to move the logic for displaying the relevant value to the <template></template> tag of that row so the value is no longer in the item object. But this isn't always feasible and introduces unnecessary complexity to the design of the table.

**Comment by tmorehouse** [comment]
This is something we have been thinking of introducing.

**Comment by tmorehouse** [comment]
It would be probably implemented as a new prop `filter-ignored-fields`

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0-rc.28 has been released.
