### ISSUE TITLE
pagination component without page numbers (first/prev/next/last only)

### ISSUE THREAD

**Issue by belusky** [bootstrap-vue/bootstrap-vue#3751]
I would like to display only first/prev/next/last buttons (no page numbers).
But for pagination component there is minimum supported value for limit prop set to 3 according to docs.

      <b-pagination
        v-model="currentPage"
        :limit="0"
        :total-rows="totalRows"
        :per-page="perPage"
        size="sm"
        class="float-sm-right mb-0"
      ></b-pagination>

[BootstrapVue warn]: pagination: prop "limit" must be a number greater than 0
[Vue warn]: Invalid prop: custom validator check failed for prop "limit".

Is there any reason for this validation ?
https://github.com/bootstrap-vue/bootstrap-vue/blob/2fb5ce823a577fcc2414d78bd43ed9e5351cb1c0/src/mixins/pagination.js#L69-L81

**Comment by tmorehouse** [comment]
Pagination without actual numbers can generate accessibility issues, as there would be no feedback for screen reader users as to what page number they are on.

 `limit` also includes in it's count the ellipsis indicators (when they are visible).

The docs need to be updated to reflect that limit can be set to 1 or greater, except than ellipsis will not be shown on small limit values for practical display reasons.

**Comment by tmorehouse** [comment]
To get pagination-like controls that do not show page numbers, you may want to create a custom component that only shows the 4 controls, and add click handlers to each to control your value.
