### ISSUE TITLE
Can't set tabindex attribute for checkbox or radio

### ISSUE THREAD

**Issue by hidekatsu-izuno** [bootstrap-vue/bootstrap-vue#3752]
### Describe the bug

I need to control the tab index ordering. So I added a tabindex attribute to b-form-checkbox, b-form-checkbox-group, b-form-radio and b-form-radio-group.

But I found the tabindex attribute showed on a enclosed div element instead of the input element.  I hope that the tabindex attribute shows on the input element. And it's better to be ablet to set a tabindex property in options object of b-form-checkbox-group and b-form-radio-group. 

### Steps to reproduce the bug

1. Define b-form-checkbox, b-form-checkbox-group, b-form-radio and b-form-radio-group.
2. Add a tabindex attribute to the each component.

### Expected behavior

A tabindex attribute must show on a input element instead of a enclosed div element for b-form-checkbox, b-form-checkbox-group, b-form-radio and b-form-radio-group.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.27
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Windows Laptop
- OS; Windows
- Browser: Chrome
- Version: Windows 10

### Demo link

https://codepen.io/hidekatsu-izuno/pen/aeZXRy

### Additional context

Nothing

**Comment by tmorehouse** [comment]
MDN recommends never using tabindex values greater than `0`, as it can be confusing to keyboard-only users as the tab sequence doesn't follow the visual layout:

> Avoid using tabindex values greater than 0. Doing so will make it difficult for people who rely on assistive technology to navigate and operate page content.

> It is not recommended to give positive values to your elements. You will end up jumping between them, and it will be confusing to manipulate between your element's tabindex attribute values. Instead, focus on writing them in a suitable DOM sequence.

Also, values greater than 0 will make the values appear last on a page, after any regular tabable items (i.e. links, buttons, etc).

For radio-groups and checkbox groups, it wouldn't make sense to set the tabindex on the group

**Comment by hidekatsu-izuno** [comment]
You may not need to use a explicit tabindex. But I need to use it for a user request.
I recognize the bootstrap-vue is a tool. So we should not limit a use case. And a raw bootstrap has this feature.

> For radio-groups and checkbox groups, it wouldn't make sense to set the tabindex on the group

Group items that have a same number tabindex can work in a natural order. 

Or

>  it's better to be ablet to set a tabindex property in options object of b-form-checkbox-group and b-form-radio-group.

**Comment by tmorehouse** [comment]
PR #3754 makes the nested input for b-form-checkbox, b-form-radio and b-form-file (the three form-control components that have wrapper elements) inherit any non-prop attributes applied to the component.  It does not include b-form-radio-group or b-form-checkbox-group.  In the latter two cases, you can render individual b-form-radio or b-form-checkboxes inside the group component and set the tabindex on them.

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0-rc.28 has been released.
