### ISSUE TITLE
Duplicate Data Attributes

### ISSUE THREAD

**Issue by aminnairi** [bootstrap-vue/bootstrap-vue#3753]
### Describe the bug

There are duplicate `data-v-xxxxx` attributes on the generated server-side code when using Nuxt with Bootstrap Vue. These trigger a warning when using the W3C validator.

### Steps to reproduce the bug

See [here](https://github.com/aminnairi/bootstrap-vue-duplicate-data-attributes).

### Expected behavior

There should not be duplicates `data-v-xxxxx` attributes.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.11
- Bootstrap: 4.1.3
- ~~Vue~~ Nuxt: 2.0.0

**Environment:**

- Device: Laptop
- OS: GNU/Linux Arch
- Browser: Chromium
- Version: 75.0.3770.142 (Official Build) Arch Linux (64-bit)

### Demo link

See above.

### Additional context

N/A.

**Comment by tmorehouse** [comment]
`data-v-xxxxx` attributes are generated by `vue-loader` when using scoped CSS/SCSS in Single File Templates. BootstrapVue does not add these attributes itself.

**Comment by aminnairi** [comment]
That's even more strange. Because all other components that are not Bootstrap-Vue related does not have duplicate attributes.

![image](https://user-images.githubusercontent.com/18418459/61883936-974de680-aefb-11e9-9859-bd29748b20a1.png)

**Comment by tmorehouse** [comment]
You also probably want to upgrade to the latest versions of Vue (2.6.10), Nuxt (2.8.1), and BootstrapVue (2.0.0-rc.27).

Also note that BootstrapVue uses Bootstrap v4.3.1 (not v4.1.3)

**Comment by tmorehouse** [comment]
How are you importing Bootstrap and Bootstrap CSS into your project?

**Comment by aminnairi** [comment]
Thanks for the insight. I'll update all dependencies and try to reproduce the bug. Note that these dependencies are installed by the `nuxt-create-app` and have not been updated/upgraded.

**Comment by tmorehouse** [comment]
You might have an older version of `nuxt-create-app` (especially if you are using an older version of Nuxt)

**Comment by aminnairi** [comment]
I use Bootrstap Vue with the Nuxt modules indeed. See [here](https://github.com/aminnairi/bootstrap-vue-duplicate-data-attributes/blob/master/nuxt.config.js) for more details.

**Comment by aminnairi** [comment]
I used `npx` to create the application:

```console
$ npx create-nuxt-app my-app
```

**Comment by tmorehouse** [comment]
The older version of BootstrapVue have an older version of the BootstrapVue Nuxt module. the 2.0.0-rc.27 version is more robust, and provides for better tree shaking.

**Comment by aminnairi** [comment]
I just upgraded to the latest versions of `bootstrap`, `bootstrap-vue` & `nuxt`. See [here](https://github.com/aminnairi/bootstrap-vue-duplicate-data-attributes/commit/3f74ae75e822a828d54d3043b7d3a1e732f9b3d1).

**Comment by tmorehouse** [comment]
https://github.com/aminnairi/bootstrap-vue-duplicate-data-attributes/blob/3f74ae75e822a828d54d3043b7d3a1e732f9b3d1/pages/index.vue#L11-L15

If removing the `scoped` attribute on your style, do you still see dual data attributes?

If so, then this may be an upstream issue with Nuxt, vue-ssr, and/or vue-loader

**Comment by aminnairi** [comment]
Yes indeed, removing the `scoped` attribute on the `<style>` tag inside the `index.vue` page will disabled all `data-v-xxxx` attributes. Thus invalidating this issue.

I'll open an issue to Nuxt. Thanks for your assistance.
