### ISSUE TITLE
Table Component - Row Selection - Double Click: Subsequent click after double click does not fire click event

### ISSUE THREAD

**Issue by Arquiel** [bootstrap-vue/bootstrap-vue#3757]
### Describe the bug

Click event is not fired for the 1st subsequent click after a double click is handled.

### Steps to reproduce the bug

1. Go to the table row select demo page
2. Double click on the first row (row should be selected now)
3. Wait a second, then click once
4. At this point, the selected row should be deselected from the 3rd click, but nothing happens until the 4th click.

### Expected behavior

Upon execution of the 3rd click (distinctly seperated), the click handler should be fired.

### Versions

**Environment:**

- Browser: Chrome (Windows 10)

### Demo link

https://bootstrap-vue.js.org/docs/components/table#row-select-support

### Additional context

I've been running into all sorts of hurdles because the BS-V API doesn't keep track of selections after sorting or page changes:
allow for programmatic selection:
 -  Rows cannot be programmatically selected/deselected
 - Click events have to be manually fired on each row to select/deselect
 - Double click events 
 - Double clicks are handled at a different speed than native JS handles them

**Comment by tmorehouse** [comment]
Selection is triggered by a single click, not double clicks.

Clicking the row a single time will select it, clicking again will deselect it.

**Comment by Arquiel** [comment]
I know selection is triggered by a single click. I’m saying after a double click the next single click doesn’t work.

**Comment by tmorehouse** [comment]
What is probably happening during hte double click (single click is always fired even for double clicks) is that a test selection is becoming active, which b-table will ignore clicks (to allow copy to happen).

You can visually see this effect by double clicking on text within a row (i.e. double click on the last name).  You will see that the first click triggers the row selection, while the second click of the double click activates the browser's selection of the text A single click after that will clear the text selection (and that click is not bubbled up to b-table).

**Comment by Arquiel** [comment]
If I’m not clicking on text (just the td area), that is unexpected (and unwanted) behavior. The double click handler has a pretty slow threshold, so it’s easy to accidentally trigger. If you don’t select text, you’ll see it in action.

**Comment by tmorehouse** [comment]
We do not use any special double click handling, as we use the native browser `dblclick` event to trigger the `row-dblclicked` event:

https://github.com/bootstrap-vue/bootstrap-vue/blob/722f9db371634d5185db0f7fef99cc1c735b6e8d/src/components/table/helpers/mixin-tbody-row.js#L306-L330

**Comment by tmorehouse** [comment]
Added a tweak (via PR #3763) to the detection of an active text-selection, which appears to fix your issue.

You can test it out at https://deploy-preview-3763--bootstrap-vue.netlify.com/docs/components/table#row-select-support

**Comment by Arquiel** [comment]
That does fix the issue! Much appreciated! When will it go live?

**Comment by tmorehouse** [comment]
Probably Monday (if I can finish the issues with `b-form-file` and the required prop when using drag-drop)

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0-rc.28 has been released.
