### ISSUE TITLE
b-table sort arrows reversed

### ISSUE THREAD

**Issue by cvn** [bootstrap-vue/bootstrap-vue#3761]
### Describe the bug

When sorting b-table, the sort icon for ascending is ↓, and descending is ↑. This is opposite of the convention that ascending is an up arrow ↑, and descending is a down arrow ↓.

### Versions

- BootstrapVue: 2.0.0-rc.27

### Demo link

https://bootstrap-vue.js.org/docs/components/table/#sorting
<img width="776" alt="Screenshot 2019-07-26 00 46 57" src="https://user-images.githubusercontent.com/774864/61926526-ea955880-af3e-11e9-8566-074fbccf4d55.png">

### Additional context

I understand that this is subjective, and that it can be configured by overriding CSS, but I believe it's a counterintuitive default. Please consider swapping the arrows.

Some examples of the convention:

- **iTunes/NSTableView**
  ![table-view](https://user-images.githubusercontent.com/774864/61926632-642d4680-af3f-11e9-96e7-1fee6a7323aa.jpg)
- **Wordpress**
  <img width="1031" alt="Screenshot 2019-07-26 00 27 17" src="https://user-images.githubusercontent.com/774864/61925932-72c62e80-af3c-11e9-8afd-80fb1543d392.png">
- **[Material Design for Bootstrap](https://mdbootstrap.com/docs/jquery/tables/sort/)**
  <img width="842" alt="Screenshot 2019-07-25 06 04 21" src="https://user-images.githubusercontent.com/774864/61865886-144c7200-aea2-11e9-8abf-f100b9543187.png">
- **[Movable Type](https://www.movabletype.org/)** (it's a pretty old convention)
  <img width="1028" alt="Screenshot 2019-07-26 00 43 48" src="https://user-images.githubusercontent.com/774864/61926414-75c21e80-af3e-11e9-9a8c-34b4f666d7f6.png">

**Comment by tmorehouse** [comment]
Duplicate: #2126

**Comment by tmorehouse** [comment]
We will probably be moving to using SVG backgrounds (and away from "arrows") when 2.0.0 stable is released.

**Comment by tmorehouse** [comment]
Probably to triangles similar to:
![image](https://user-images.githubusercontent.com/2781561/61954449-45ef3700-af8f-11e9-90fa-d2f0075095f7.png)

Where it infers biggest to smallest (wide end to small end => larger value to smaller value), better than arrows (which infer a direction only)
