### ISSUE TITLE
Import only the Tooltip component/directive with scoped CSS

### ISSUE THREAD

**Issue by feliperaul** [bootstrap-vue/bootstrap-vue#3764]
First of all, congrats to everyone involved in this project, it's awesome.

I see the library supports importing only the desired components/directives. By that I mean it's officially supported to import just the `v-b-tooltip` directive (https://bootstrap-vue.js.org/docs/components/tooltip/#importing-individual-directives):

```
import { VBTooltip } from 'bootstrap-vue'
// Note: Vue automatically prefixes the directive name with 'v-'
Vue.directive('b-tooltip', VBTooltip)
```

Of course, for this to work you also need CSS:

```
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-vue/dist/bootstrap-vue.css";
```

But it's overkill to import the entire bootstrap AND bootstrap-vue CSS files just for tooltips to work. Also, even if that was not an issue, importing CSS like that means it will pollute the global space. So I tried using scoped styles in my component:

```
<style scoped src="bootstrap/dist/css/bootstrap.css" />
<style scoped src="bootstrap-vue/dist/bootstrap-vue.css" />
```

For this to work with the Tooltip, you have to pass an `element` for it to mount to, because otherwise it will be mounted on `body`, which will be outside the scope of the component.

But even if doing so, I get a broken tooltip like this (note the white text on the right, that's the tooltip):

![image](https://user-images.githubusercontent.com/743879/61957133-eeec6080-af94-11e9-9978-e0fe2ab87bd7.png)

Debugging this further, I noticed that even tough my page is loading the correct styles AND it's scoping them, the tooltip element in itself doesn't have the `data-*` attribute to make it work with the scoped CSS... (note the outer element has the `data-` attribute, but the tooltip div doesn't):

![image](https://user-images.githubusercontent.com/743879/61957213-1b07e180-af95-11e9-9ec3-775ee792471e.png)

So, this is the CSS being included in the page (note it's scoped):
````
.tooltip[data-v-c2ed4f50] {
  position: absolute;
  z-index: 1070;
  display: block;
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  font-style: normal;
  font-weight: 400;
  line-height: 1.5;
  text-align: left;
  text-align: start;
  text-decoration: none;
  text-shadow: none;
  text-transform: none;
  letter-spacing: normal;
  word-break: normal;
  word-spacing: normal;
  white-space: normal;
  line-break: auto;
  font-size: 14px;
  font-size: 0.875rem;
  word-wrap: break-word;
  opacity: 0;
}
.tooltip.show[data-v-c2ed4f50] {
  opacity: 0.9;
}
.tooltip .arrow[data-v-c2ed4f50] {
  position: absolute;
  display: block;
  width: 12.8px;
  width: 0.8rem;
  height: 6.4px;
  height: 0.4rem;
}
.tooltip .arrow[data-v-c2ed4f50]::before {
  position: absolute;
  content: "";
  border-color: transparent;
  border-style: solid;
}
.bs-tooltip-top[data-v-c2ed4f50], .bs-tooltip-auto[x-placement^="top"][data-v-c2ed4f50] {
  padding: 6.4px 0;
  padding: 0.4rem 0;
}
.bs-tooltip-top .arrow[data-v-c2ed4f50], .bs-tooltip-auto[x-placement^="top"] .arrow[data-v-c2ed4f50] {
  bottom: 0;
}
.bs-tooltip-top .arrow[data-v-c2ed4f50]::before, .bs-tooltip-auto[x-placement^="top"] .arrow[data-v-c2ed4f50]::before {
  top: 0;
  border-width: 6.4px 6.4px 0;
  border-width: 0.4rem 0.4rem 0;
  border-top-color: #000;
}
.bs-tooltip-right[data-v-c2ed4f50], .bs-tooltip-auto[x-placement^="right"][data-v-c2ed4f50] {
  padding: 0 6.4px;
  padding: 0 0.4rem;
}
.bs-tooltip-right .arrow[data-v-c2ed4f50], .bs-tooltip-auto[x-placement^="right"] .arrow[data-v-c2ed4f50] {
  left: 0;
  width: 6.4px;
  width: 0.4rem;
  height: 12.8px;
  height: 0.8rem;
}
.bs-tooltip-right .arrow[data-v-c2ed4f50]::before, .bs-tooltip-auto[x-placement^="right"] .arrow[data-v-c2ed4f50]::before {
  right: 0;
  border-width: 6.4px 6.4px 6.4px 0;
  border-width: 0.4rem 0.4rem 0.4rem 0;
  border-right-color: #000;
}
.bs-tooltip-bottom[data-v-c2ed4f50], .bs-tooltip-auto[x-placement^="bottom"][data-v-c2ed4f50] {
  padding: 6.4px 0;
  padding: 0.4rem 0;
}
.bs-tooltip-bottom .arrow[data-v-c2ed4f50], .bs-tooltip-auto[x-placement^="bottom"] .arrow[data-v-c2ed4f50] {
  top: 0;
}
.bs-tooltip-bottom .arrow[data-v-c2ed4f50]::before, .bs-tooltip-auto[x-placement^="bottom"] .arrow[data-v-c2ed4f50]::before {
  bottom: 0;
  border-width: 0 6.4px 6.4px;
  border-width: 0 0.4rem 0.4rem;
  border-bottom-color: #000;
}
.bs-tooltip-left[data-v-c2ed4f50], .bs-tooltip-auto[x-placement^="left"][data-v-c2ed4f50] {
  padding: 0 6.4px;
  padding: 0 0.4rem;
}
.bs-tooltip-left .arrow[data-v-c2ed4f50], .bs-tooltip-auto[x-placement^="left"] .arrow[data-v-c2ed4f50] {
  right: 0;
  width: 6.4px;
  width: 0.4rem;
  height: 12.8px;
  height: 0.8rem;
}
.bs-tooltip-left .arrow[data-v-c2ed4f50]::before, .bs-tooltip-auto[x-placement^="left"] .arrow[data-v-c2ed4f50]::before {
  left: 0;
  border-width: 6.4px 0 6.4px 6.4px;
  border-width: 0.4rem 0 0.4rem 0.4rem;
  border-left-color: #000;
}
.tooltip-inner[data-v-c2ed4f50] {
  max-width: 200px;
  padding: 4px 8px;
  padding: 0.25rem 0.5rem;
  color: #fff;
  text-align: center;
  background-color: #000;
  border-radius: 0.25rem;
}
```

But the dom elements of the tooltip itself, as you saw before, even if specifically targeting an mount element inside the component (and not `body`), lack the `data-*` attribute to make them a target for the scoped css. 

It would be nice if this could work out of the box. If the library already has support for importing individual components or directives, it would be great if we could load only the necessary CSS for those components, AND even better if that worked with the scoped CSS so it doesn't pollute the global CSS namespace.

**Comment by tmorehouse** [comment]
Scoped CSS wont work (by default) on Vue custom components (see https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements)

BootstrapVue CSS is quite small (a few kbytes when compressed). Bootstrap v4. css can be quite large though.  You can, using SCSS, import just the SCSS files from Bootstrap v4 that you need (you still need to import _variables.scss, mixins and functions from Bootstrap v4):

https://github.com/twbs/bootstrap/tree/v4-dev/scss

All SCSS `@import`s need to be placed into as single SCSS file that you include in your app.

**Comment by tmorehouse** [comment]
Also note that many of teh bootstrap styles (i.e. utility classes, grid layout classes, etc) are needed by many of Bootstrap / BootstrapVue components (and you are not relegated to using BootstrapVue components to use Bootstrap CSS... remember Bootstrap CSS is a framework and not restricted to use with components only)

Trying to convert BotstrapVue to re-scope all Bootstrap SCSS would be a nightmare (due to the requirements of shared SASS variables and classes), and would require major re-work for each major Bootstrap upgrade.

**Comment by feliperaul** [comment]
@tmorehouse Thanks for the quick reply! 

I now understand both why the tooltip component is not receiving scoped, and also why it would be nightmare for the lib to provide the CSS it in that modular way.

Last night I spent over one hour trying to import only the required files from bootstrap to make it work, and failed miserably. But even if I managed to do it so, I would only solve problem 1 (not loading the entire bootstrap CSS), but I would still affect the layout of my page because the CSS would not be scoped, right?

Based on this, maybe the only solution is to fork an isolated Tooltip directive, and import the required CSS using scoped styles, so that the styles stays scoped. Would you agree that's the only way to go?

**Comment by tmorehouse** [comment]
If only using tooltip, then you could just import the required tooltip SCSS from Bootstrap (along with the mixins, function, variables, which control how the CSS is generated, but don't bloat the CSS) and in that same file import our custom tooltip SCSS (for the variants, which use mixins/variables/functions from bootstrap to generate the colors, etc).  BootstrapVue custom tooltip SCSS is found at `/src/components/tooltip/index.scss`

**Comment by feliperaul** [comment]
@tmorehouse Ok, that was exactly what I was trying to do yesterday, but the dependencies were not very clear and I kept failing at it :/

I'll give it another try over the weekend. Thank you.

**Comment by tmorehouse** [comment]
```scss
// custom.scss file

// This order is important
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";

// Import Bootstrap Tooltip SCSS
@import "bootstrap/scss/tooltip"

// Import Bootstrap Vue custom Tooltip SCSS
@import "bootstrap-vue/src/variables"
@import "bootstrap-vue/src/components/tooltip/index"
```

**Comment by feliperaul** [comment]
Thank you, will try this later on and report back!

Em sex, 26 de jul de 2019 às 13:11, Troy Morehouse <notifications@github.com>
escreveu:

**Comment by tmorehouse** [comment]
You may need a few additiona Bootstrap SCSS files (i.e. reboot.scss, etc) to ensure `box-sizing: border-box` is used for sizing computations.

**Comment by feliperaul** [comment]
Worked flawlessly. Thank you so much.

For anyone reading this in the future, using Rails / Webpacker, this is what I did:

```
VueTooltip.scss

@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";

@import "~bootstrap/scss/tooltip";

@import "~bootstrap-vue/src/variables";
@import "~bootstrap-vue/src/components/tooltip/index";
```

In my component.vue:
```
import './VueTooltip.scss';
import { VBTooltip } from 'bootstrap-vue';

export default {
  ...
  directives: {
    'b-tooltip': VBTooltip,
  },
```

The css imports didn't change the layout of my page, which was happening when I imported the entire bootstrap CSS file. 

Thank you again @tmorehouse

**Comment by lukenofurther** [comment]
@tmorehouse these days it's pretty trivial to prevent duplication of CSS via Webpack chunking and there are tools for removing unwanted CSS like purify CSS. In light of this, might you reconsider repackaging Bootstrap-Vue so it's easier to import individual components?

Not packaging up the CSS with your components makes it difficult to use this library in a componentised way.

**Comment by tmorehouse** [comment]
@lukenofurther We do have options, via SASS variables to disable certain parts of BootstrapVue SCSS/CSS generation (secfically the parts that generate a lot of CSS, such as tables, tooltips and popovers):

https://bootstrap-vue.js.org/docs/reference/theming#bootstrapvue-sass-variables
