### ISSUE TITLE
Missing documentation for  $bvModal.msgBox

### ISSUE THREAD

**Issue by lukas-tr** [bootstrap-vue/bootstrap-vue#3765]
To my understanding, I can use [$bvModal.msgBox](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/modal/helpers/bv-modal.js#L192) to open a modal with any vue component on demand (eg with webpack code splitting) rather than mounting dozens of modals that aren't even used most of the time. 

I tried passing a component, but it doesn't get rendered. 

If this is the intended use, how would I pass data on modal creation, prevent closing if the input was invalid and get back the result after closing the modal if I passed a component containing a input field (as alternative to calling window.prompt())?   

```vue
<script>
import HelloWorld from "./components/HelloWorld";

export default {
  data() {
    return {
      boxOne: ""
    };
  },
  methods: {
    showMsgBoxOne() {
      this.boxOne = "";
      this.$bvModal
        .msgBox(
          HelloWorld /* display this component as body */,
          {},
          event => event /* Somehow get component data */
        )
        .then(value => {
          this.boxOne = value;
        })
        .catch(err => {
          // An error occurred
        });
    }
  }
};
</script>
```

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-g222o?fontsize=14)

![image](https://user-images.githubusercontent.com/36337818/61959207-34278700-afc3-11e9-80ec-6eb3c9cbdf2d.png)

**Comment by tmorehouse** [comment]
Currently message boxes are meant to be used as small confirmation dialogs, and do not accept a component reference as content.

The content can be specified as a string, or passed as an array of _rendered_ vNodes.

If your component emits an event (say the change event, with a value of a text box):

```js
    showMsgBoxOne() {
      this.boxOne = "";
      const content = this.$createElement(
        HelloWorld,
        {
          props: { value: this.boxOne }
          on: {
           change: (val) => { this.boxOne = val }
          }
        }
      )
      this.$bvModal
        .msgBox(
          [content],
          {},
        )
        .then(trigger => {
          if (trigger === 'ok) {
            // this.boxOne value will be your result
          } else {
            // user clicked cancel button or closed modal
            this.boxOne = '';
          }
        })
        .catch(err => {
          // An error occurred
        });
    }
  }
```

Note the `contents` is a static array of vNodes, and is not reactive (i.e. contents wont change), but it will respect the events fired by the content (i.e. if component HelloWorld emits the change event when the input is updated)

We are going to be adding a prompt version of message box that will be a basic input that will return a value of an standard input.

**Comment by lukas-tr** [comment]
Thanks. I changed my code a bit based on your suggestions and it works as expected. 

It would also be great if `this.$bvModad.show(modalID, { data })` supported webpack code splitting like so: `import("./MyComponent.vue").then(MyComponent => this.$bvModad.show(MyComponent, { data }))`.


(updated code sandbox in case anyone also needs this)
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-4fcx1?fontsize=14)

**Comment by tmorehouse** [comment]
The webpack thing would assume all people are using webpack... which is not always the case.  some use BootstrapVue via script tags (UMD build).

**Comment by tmorehouse** [comment]
Also note that `$bvModal` only appears on component instances, so `this` would not point to the correct `this` in your code-split suggestion above.

**Comment by lukas-tr** [comment]
`import("./MyComponent.vue").then(MyComponent => {...}` is specific to webpack, while `this.$bvModad.show(MyComponent, { data })` can be used without webpack.

Since the callback to `import` is a arrow function, it doesn't have its own `this`.

**Comment by tmorehouse** [comment]
`this` wouldn't be a component instance, unless the import is called from within the context of a custom component, such as during the mount() hook. (`$bvModal` is global Vue mixin, so it only appears on Vue instances)

**Comment by lukas-tr** [comment]
Yes. 

```
  methods: {
    openEditModal(){
      import("./MyComponent.vue").then(MyComponent => this.$bvModad.show(MyComponent, { data: this.data }));
    }
  }
```

My point is that `this.$bvModad.show` should also be able to show components directly, before mounting them since this is way more convenient (especially when using code splitting) than `this.$bvModad.show(modalID, { data })`, which would require the modal with the id `modalID` to be present in the DOM already.

**Comment by tmorehouse** [comment]
The `$bvModal.show(...)` method uses events to trigger a modal, of which the modal is listening for its ID to be emitted, hence it needs to be in document in order for it to hear the events.

**Comment by tmorehouse** [comment]
What you are looking for is a `$bvModal.msgBoxZZZ` method (where ZZZ is to be determined) that renders a particular component in the on-demand modal message box body

**Comment by lukas-tr** [comment]
Oh, my bad. Is such a feature planned?

**Comment by tmorehouse** [comment]
We are looking into adding more msgBox methods in the (somewhat) near future

**Comment by tmorehouse** [comment]
Also note that `this.$bvModal.msgBox()` is an internal command (not documented for a reason).

You should be using `this.$bvModal.msgBoxOk()` or `this.$bvModal.msgBoxConfirm()`

**Comment by TuringJest** [comment]
> As well, we are planning on adding "parameterized" modals where you can trigger a modal to open via `this.$bvModad.show(modalID, { data })` which returns a promise which is resolved when the modal closes. the promise will return the results of the `data` object.

@tmorehouse That would be a really useful feature. Is there any process on this? 
I'm looking for a way to restrict button actions to logged in users. If not logged in, open a login modal check the response and return it, so the button action can be finally called.

Is there anyway I can achieve this with the msgBox by manually triggering the returned promise for ok/cancel (and hiding the default buttons)?
