### ISSUE TITLE
b-table add new size

### ISSUE THREAD

**Issue by ufocool** [bootstrap-vue/bootstrap-vue#3766]
Could you add one more size, super small.
Many users want a smaller table.

`current <b-table> padding: .75rem;`
`current <b-table small> padding: .3rem;`
`<b-table xsmall> padding: .1rem;`

Thx

**Comment by tmorehouse** [comment]
The sizes are dictated by Bootstrap v4.3 SCSS (we don't define the sizes).

You could open an issue at Bootstrap official repo at https://github.com/twbs/bootstrap/issues
