### ISSUE TITLE
IE11: Script Error on col.js between 2.0.0-rc.26 and 2.0.0-rc.27

### ISSUE THREAD

**Issue by rich25200** [bootstrap-vue/bootstrap-vue#3781]
### Describe the bug

Now on my website, I have an error on IE11 in col.js file (webpack:///node_modules/bootstrap-vue/esm/components/layout/col.js) on 

`breakpointPropMap = Object(_utils_object__WEBPACK_IMPORTED_MODULE_5__["assign"])(Object(_utils_object__WEBPACK_IMPORTED_MODULE_5__["create"])(null), {
    col: Object(_utils_object__WEBPACK_IMPORTED_MODULE_5__["keys"])(breakpointCol),
    offset: Object(_utils_object__WEBPACK_IMPORTED_MODULE_5__["keys"])(breakpointOffset),
    order: Object(_utils_object__WEBPACK_IMPORTED_MODULE_5__["keys"])(breakpointOrder)
  }); // Return the generated props`

This problem appears only in RC.26 and RC.27.

If I upgrade bootstrap-vue with RC.25 version my website is working fine.

### Versions

**Libraries:**

- BootstrapVue: 2..0.0-rc.27
- Bootstrap: 4.0.0
- Vue: 2.6.10

**Environment:**

- Browser: IE
- Version: 11
![2019-07-30 09_57_42-Window](https://user-images.githubusercontent.com/18281822/62111199-5e719100-b2b0-11e9-91b0-c67e2a6a7f19.png)

**Comment by jackmu95** [comment]
@rich25200 We dropped all default polyfills in RC 26 to safe bundle size for users who don't need legacy browser support.

Please see the update [Browser support](https://bootstrap-vue.js.org/docs/#browser-support) section in the docs for help.

**Comment by rich25200** [comment]
@jackmu95 Amzing. It's working. Thanks!
