### ISSUE TITLE
Need beautiful multi select support

### ISSUE THREAD

**Issue by bagaskarala** [bootstrap-vue/bootstrap-vue#3782]
### Is your feature request related to a problem? Please describe...

Bootstrap-vue still use old native multiple select. It is so old style.

### Describe the solution you'd like

We need beautiful multiple select support like select2 or anything. It will be very useful in everyday forms.

### Describe alternatives you've considered

Try look other plugin like vue-select, vue-multiselect, or select2. Please make this feature native support on bootstrap-vue

### Additional context

I think it is very useful component, we need them in every usecase. thanks

**Comment by tmorehouse** [comment]
There are quite a few 3rd party plugins that provide custom multi-select elements.

It is also possible to build a custom multi-select/select based on dropdowns with checkmark stylings to indicate the selected value (or using checkboxes in a dropdown `b-dropdown-form` sub-component), and updating the button text to reflect the selections.
