### ISSUE TITLE
<b-form-select> native ui cannot be closed on iOS

### ISSUE THREAD

**Issue by ShinZ6** [bootstrap-vue/bootstrap-vue#3783]
Test on a simulator and iphone 7 with lates iOS version. 
Bootstrap-vue version 2.0.0-rc27

![Screen Shot 2019-07-30 at 1 46 18 PM](https://user-images.githubusercontent.com/17706285/62126907-0c8d3300-b2d1-11e9-9da9-ae3ce3f8f68a.png)

As you can see from the screenshot there is no way to close the native form select ui as no select or cancel button appears. Also clicking on a option does not close it. Only way the user can close it is by touching a other ui element which takes the focus for i.e a input field.

**Comment by tmorehouse** [comment]
`b-form-select` is a native browser HTML `<select>` element.

iOS is known to have a few issues with selects and Vue:

https://vuejs.org/v2/guide/forms.html#Select

> If the initial value of your v-model expression does not match any of the options, the <select> element will render in an “unselected” state. On iOS this will cause the user not being able to select the first item because iOS does not fire a change event in this case. It is therefore recommended to provide a disabled option with an empty value.
