### ISSUE TITLE
$bvToast not getting injected into vue component object

### ISSUE THREAD

**Issue by luckylooke** [bootstrap-vue/bootstrap-vue#3784]
Hello, thank you for your work, really appreciate. 
I have difficulties to manage toast via vue component methods because I am not getting injected $bvToast object.

### Describe the bug

$bvToast not getting injected into component

**Error:**
```
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'hide' of undefined"
```

### Steps to reproduce the bug

1. Go to https://codesandbox.io/embed/bootstrap-vue-missing-bvtoast-j3umo
2. Click on button
3. See error in console

### Expected behavior

Closing opened toast

### Versions

**Libraries:**

- BootstrapVue: 2.0.0.rc27
- Bootstrap: 4.3.1
- Vue: 2.5.22

**Environment:**

online editor

### Demo link

https://codesandbox.io/embed/bootstrap-vue-missing-bvtoast-j3umo

Thank you very much! :)

**Comment by tmorehouse** [comment]
You are missing the import for BootstrapVue, and the subsequent `Vue.use(BootstrapVue)`

```js
import Vue from "vue";
import BootstrapVue from 'bootstrap-vue';
import App from "./App.vue";

Vue.config.productionTip = false;

Vue.use(BootstrapVue);

new Vue({
  render: h => h(App)
}).$mount("#app");
```

**Comment by luckylooke** [comment]
Thanks for explanation! Your fix works: https://codesandbox.io/embed/solved-bootstrap-vue-missing-bvtoast-y06xv

👏 👏 👏

**Comment by bakztfuture** [comment]
I've tried the above, but it's still not injecting the toast component.

`main.js` file
```es6
import { 
  LayoutPlugin, 
  ModalPlugin,
  BVModalPlugin,
  BNavbar,
  BNavbarNav,
  BNavItem,
  BNavbarBrand,
  BNavbarToggle,
  BNavForm,
  BCollapse,
  BForm,
  BAlert,
  BModal,
  BButton,
  BProgress,
  BVToastPlugin
} from 'bootstrap-vue'

Vue.use(
  LayoutPlugin, 
  ModalPlugin,
  BVModalPlugin,
  BVToastPlugin
)
```

inside `methods` in my view, I'm calling it like so:
```es6
    errorToast(){
      this.$bvToast.toast("Special Message Here", {
        title: 'Special Title Goes Here',
        variant: "danger",
        toaster: 'b-toaster-top-full',
        solid: true,
        noAutoHide: true,
        appendToast: true
      })
    },
```

Inside my console, I'm seeing this error:
`warn.js?686b:11 [BootstrapVue warn]: config: unknown config property "install"`

Stack expands to:
```
[BootstrapVue warn]: config: unknown config property "install"
warn @ warn.js?686b:11
(anonymous) @ config-set.js?e331:54
setConfig @ config-set.js?e331:51
setConfig @ config-set.js?e331:137
install @ plugins.js?3790:50
Vue.use @ vue.runtime.esm.js?2b0e:5101
(anonymous) @ main.js?56d7:29
./src/main.js @ app.js:7944
__webpack_require__ @ app.js:724
fn @ app.js:101
1 @ app.js:8630
__webpack_require__ @ app.js:724
(anonymous) @ app.js:791
(anonymous) @ app.js:794
```

Inside `mounted` when I try to print the `bvToast` object, it simply returns `undefined` in my console:
```es6
let $vm = this;
console.log($vm.$bvToast);
```

Can't seem to figure out where I've gone wrong.  Would sincerely appreciate any ideas

**Comment by tmorehouse** [comment]
You can only pass one plugin to `Vue.use(...)` at a time.  You need to `Vue.use(...)` each plugin on a separate line.

If you are including the `ModalPlugin`, it automatically includes the `BVModalPlugin`. Similar for `ToastPlugin` which automatically includes `BVToastPlugin`.

**Comment by bakztfuture** [comment]
Thanks so much @tmorehouse appreciate you walking me through it :D excited for leveraging toast capabilities
