### ISSUE TITLE
Table - Add Page Change Event

### ISSUE THREAD

**Issue by Arquiel** [bootstrap-vue/bootstrap-vue#3787]
Hi,

The pagination change handler triggers when a pagination button is clicked, but the respective table hasn't yet rendered the new page. If I want to do an operation to the current page, I have to do so within a setTimeout() within the pagination's change handler to ensure the page has finished rendering. For my test data, a timeout of 50ms is adequate, but I don't know how scalable that is.

Can you add an event hook for page change to the table component itself?

Thanks,
Chris

**Comment by tmorehouse** [comment]
I would suggest using `this.$nextTick()` instead of `setTimeout()`, as that will let Vue finish its rendering cycle.

**Comment by Arquiel** [comment]
Alrighty, that works. Thanks!
