### ISSUE TITLE
b-nav-item -> router-tag

### ISSUE THREAD

**Issue by dragomirweb** [bootstrap-vue/bootstrap-vue#3792]
b-nav-item doesn't support router-tag props

**Comment by tmorehouse** [comment]
Which router props are you you referring to on b-nav-item?

Also which version of BootstrapVue are you using, as well as Vue Router?

**Comment by tmorehouse** [comment]
Note that any router props on `b-nav-item` will not apply unless you are using the `to` prop instead of the `href` prop

**Comment by tmorehouse** [comment]
I just tried in the playground and was table to set `router-tag="span"` on a nav-item with a `to` prop, and it rendered a `<span>` instead of an `<a>`
