### ISSUE TITLE
Changing row class after bound of items

### ISSUE THREAD

**Issue by canperk** [bootstrap-vue/bootstrap-vue#3795]
### Describe the bug

I want to add / remove class from table rows after bounding items from an AJAX call. However `tbody-tr-class` function gets w parameter on its function and bound items are coming from a Promise and i can not feed the parameters to manipulate the row class. Do you any proper way to handle this situation?

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.16
- Bootstrap: 4.3.1
- Vue: 2.6.6

**Environment**
- OS: Windows 10
- Browser: Chrome
- Version: 75

**Comment by tmorehouse** [comment]
B-table calls the `tbody-tr-class` function is called any time the underlying data or state changes in b-table.

So you could update your function reference, or set a few variables in your component/apps data before you update your items data array.

**Comment by tmorehouse** [comment]
Also you should upgrade to the latest version of BootstrapVue (2.0.0-rc.27) and Bootstrap (4.3.1)

**Comment by canperk** [comment]
Tnaks for your response. I am able to call `tbody-row-class` function when i provider items manually. However if i provide items over an async operation, i can not manipulate class names

**Comment by tmorehouse** [comment]
In your provider update function, before resolving your array you can update the params for `tr-tbody-class`
