### ISSUE TITLE
b-nav > b-nav-item router-tag not appling tag even when specifing to/hrefI

### ISSUE THREAD

**Issue by dragomirweb** [bootstrap-vue/bootstrap-vue#3796]
### Describe the bug

Router tag doesn't apply even when I supply the to props.
Also the documentation doesn't specify that to props needs to be applied in order for the router-tag to work.
active-class doesn't apply on active items.

### Steps to reproduce the bug
On the https://bootstrap-vue.js.org/play i've added the code and props and it works correctly. but when i export the code to a sandbox or my application it doesn't work correctly.
exported sandbox url: https://codesandbox.io/s/ucne2

fresh installed sandbox that has the same issue.
https://codesandbox.io/s/bootstrap-vue-sandbox-bwjod

I noticed that b-nav-item uses b-link as a base for all this functionality . that is not working for me, sandbox url https://codesandbox.io/s/vue-template-tjyrk

**Comment by tmorehouse** [comment]
Router props only work when you are using Vue-router.

Neither of your codesandbox examples are using Vue router. (i.e. `import Router from 'vue-router'; Vue.use(new Router(...))`.

**Comment by dragomirweb** [comment]
Thanks, so on the playground here the router is enabled, that's why it works.

**Comment by dragomirweb** [comment]
I want to create a nav , and be able to change the tag of the list item, Or set an active item class. Why do I need the vue router for that ?

**Comment by dragomirweb** [comment]
this one does https://codesandbox.io/s/vue-template-tjyrk

**Comment by tmorehouse** [comment]
If you want to set the `active` class use the `active` prop.

You cant set the tag type when it is not a router as it needs to render a regular `<a href="...">` tag.

**Comment by dragomirweb** [comment]
I'm using the b-nav to trigger filters or other functionality and therefore I don't need the router. As a component it need it to be used in various places sometimes it could be anchors or buttons and i need active classes. But i understand now that the b-nav is more of navbar. Thanks @tmorehouse

**Comment by tmorehouse** [comment]
b-nav-item is a navigational item.  you can place other items in navbars such as form controls (in a nav form) which would provide better semantic meaning to screen reader users (actions instead of route/URL changes)
