### ISSUE TITLE
Sorting with 'original' (non-formatted) values

### ISSUE THREAD

**Issue by Arthesian** [bootstrap-vue/bootstrap-vue#3798]
So in the documentation I read in the Notes that :
```
NEW in v2.0.0-rc.25 Fields that have a formatter function (virtual field or regular field) will be sorted by the value returned via the formatter function.
```
But I would like to sort based on the original values.

For example, I have a table with Currency values, 
the original values are Numbers (12345,67)

but after formatting they become a string like : €12,345.67 (which doesn't sort correctly)

Same with Dates, I want a specific string format for the Date, 
let's say ```dddd, d MMM, yyyy``` (= Thursday, 1 Aug, 2019)

This again sorts wrongly for me.

Any way to fix the sorting? Either based on the original values, or some other way to prevent sorting based on the formatted string?

Thanks

**Comment by tmorehouse** [comment]
Version 2.0.0-rc.28 makes a few changes to how sorting will work.  sorting by formatted value will be optional (on a per field basis). It also adds i nsimilar support for filtering on formatted values (also optional).


PR https://github.com/bootstrap-vue/bootstrap-vue/pull/3778 makes sorting by formatted value opt-in (defaults to false).

PR https://github.com/bootstrap-vue/bootstrap-vue/pull/3786 adds in support for optional filtering by formatted value, as well as options to filter on specific fields.

You can see a preview at https://bootstrap-vue.netlify.com/docs/components/table

Hoping to have rc.28 release by tomorrow.

**Comment by tmorehouse** [comment]
As a workaround, you can provide a custom sort compare routine that handles sort-comparison for particular fields https://bootstrap-vue.js.org/docs/components/table#custom-sort-compare-routine

**Comment by Arthesian** [comment]
Since I'm not under time pressure at the moment, I will just be patient and wait for the new release (rc.28)

Thanks for the response @tmorehouse

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0-rc.28 has been released.
