### ISSUE TITLE
Unsortable column click issue

### ISSUE THREAD

**Issue by canperk** [bootstrap-vue/bootstrap-vue#3803]
Columns that have not sortable feature are trying to sort at first attempt. Thankfully it is not going on with second and later attempts.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.27
- Bootstrap: 4.3.1
- Vue: 2.6.6

**Environment:**

- OS: Windows 10
- Browser: Chrome 75

**Comment by ErcinDedeoglu** [comment]
What a shame.

**Comment by tmorehouse** [comment]
Un-sortable columns, when clicked, will "clear" the sorting on the table. this is as expected.

If you don't want sorting to clear when a non-sortable header is clicked, set the `no-sort-reset` prop on `b-table`
