### ISSUE TITLE
Wrong role value for tab's link

### ISSUE THREAD

**Issue by lavezzi1** [bootstrap-vue/bootstrap-vue#381]
Hi there, just found this:

<img width="751" alt="screen shot 2017-05-11 at 13 19 57" src="https://cloud.githubusercontent.com/assets/10686894/25933828/b299012e-364c-11e7-80db-6f648d0e4be4.png">

**Comment by tmorehouse** [comment]
A PR (#382) has been issued for this.  expect it to be merged shortly.

**Comment by pi0** [comment]
Thanks!
