### ISSUE TITLE
TypeError: Cannot read property 'tabindex' of undefined

### ISSUE THREAD

**Issue by alexwijoyo** [bootstrap-vue/bootstrap-vue#3812]
Hi,

I just add bootstrap-vue to my vue project and add b-navbar to test the bootstrap-vue on App.vue:
[App.vue.txt](https://github.com/bootstrap-vue/bootstrap-vue/files/3464149/App.vue.txt)

Every time I run it. I get this error:
[localhost-1564852062581.log](https://github.com/bootstrap-vue/bootstrap-vue/files/3464145/localhost-1564852062581.log)

My package.json contents:

{
  "name": "DotNetVue",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "webpack": "webpack --config webpack.config.vendor.js && webpack"
  },
  "devDependencies": {
    "aspnet-webpack": "^2.0.1",
    "css-loader": "^0.25.0",
    "event-source-polyfill": "^0.0.7",
    "extract-text-webpack-plugin": "^2.0.0-rc",
    "file-loader": "^0.9.0",
    "isomorphic-fetch": "^2.2.1",
    "node-sass": "^4.12.0",
    "prettier": "^1.18.2",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "vue": "^2.2.2",
    "vue-loader": "^11.1.4",
    "vue-router": "^2.3.0",
    "vue-template-compiler": "^2.2.2",
    "webpack": "^2.7.0",
    "webpack-cli": "^1.5.3",
    "webpack-hot-middleware": "^2.12.2"
  },
  "dependencies": {
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.0-rc.27",
    "nprogress": "^0.2.0",
    "sass-loader": "^7.1.0",
    "save-dev": "^2.0.0"
  }
}

I only use bootstrap package for bootstrap.min.css.
 
**Environment:**

- Device: HP Elitebook
- OS: Windows 10
- Browser: Chrome
- Version: 75.0.3770.142

Since I'm new to learn Vue and bootstrap-vue. Please forgive me if the issue is on my side. Thanks.

**Comment by tmorehouse** [comment]
Shouldn't `vue-router` be in your `dependencies`, rather than `devDependencies`, since it is required to run in production mode?

**Comment by alexwijoyo** [comment]
Thanks @tmorehouse I will try your suggestion and inform the result.

**Comment by alexwijoyo** [comment]
Thanks a lot @tmorehouse . Follow your instruction and the problem solve. 
package.json:
{
  "name": "DotNetVue",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "webpack": "webpack --config webpack.config.vendor.js && webpack"
  },
  "devDependencies": {
    "aspnet-webpack": "^2.0.1",
    "css-loader": "^0.25.0",
    "event-source-polyfill": "^0.0.7",
    "extract-text-webpack-plugin": "^2.0.0-rc",
    "file-loader": "^0.9.0",
    "isomorphic-fetch": "^2.2.1",
    "node-sass": "^4.12.0",
    "prettier": "^1.18.2",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "vue-loader": "^11.1.4",
    "vue-template-compiler": "^2.6.10",
    "webpack": "^2.7.0",
    "webpack-cli": "^1.5.3",
    "webpack-hot-middleware": "^2.12.2"
  },
  "dependencies": {
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.0-rc.27",
    "nprogress": "^0.2.0",
    "sass-loader": "^7.1.0",
    "save-dev": "^2.0.0",
    "vue": "^2.6.10",
    "vue-router": "^2.8.1"
  }
}
