### ISSUE TITLE
Close all collapse elements programmatically

### ISSUE THREAD

**Issue by simioluwatomi** [bootstrap-vue/bootstrap-vue#3813]
So I have about 3 collapse elements in a sidebar. At a certain width, I want to close all open collapse elements in that sidebar but couldn't find a nice and clean way to do it.

As a workaround, I used a ```v-model``` on each of the collapse elements, then set the ```v-model```s to false. That feels kinda hacky for me and I'm wondering if there is a better way. Thank you!

```
data() {
            return {
                showAccordion1: false,
                showAccordion2: false,
                showAccordion3: false,
            }
        },
        methods: {            
            handleResize(event) {
                if (window.innerWidth < 768) {
                    this.$nextTick(function () {
                        this.showAccordion1 = this.showAccordion2 = this.showAccordion3 = false;
                    });
                }
            },
        },
```

**Comment by tmorehouse** [comment]
Currently, what you have shown is the easiest way programmatically.

Collapses  also listen for resize/orientationchange events (when `is-nav` is set to true) that checks to see if the computed style is `display: block` (also checks on mount), and if it is it sets the internal show state to `true`.

https://github.com/bootstrap-vue/bootstrap-vue/blob/e885d6dcd76531a3ac7dbc0b48d97469bdee8dd3/src/components/collapse/collapse.js#L92-L112

https://github.com/bootstrap-vue/bootstrap-vue/blob/e885d6dcd76531a3ac7dbc0b48d97469bdee8dd3/src/components/collapse/collapse.js#L138-L142

https://github.com/bootstrap-vue/bootstrap-vue/blob/e885d6dcd76531a3ac7dbc0b48d97469bdee8dd3/src/components/collapse/collapse.js#L235-L238

So you can use CSS styles (based on media queries) when the display is less than a certain size to set the `display` to `none`.

**Comment by simioluwatomi** [comment]
Your turn-around time is goals! Will weigh my options. Thanks!!!!!

**Comment by tmorehouse** [comment]
You would create a custom class and apply it to `<b-collapse>`
