### ISSUE TITLE
aria-controls not shown in b-tab

### ISSUE THREAD

**Issue by jenemde** [bootstrap-vue/bootstrap-vue#3814]
The tab component (<b-tab>) doesn't show the attribute `aria-controls`. This also happens on the documentation page (https://bootstrap-vue.js.org/docs/components/tabs/) which makes me think it is a bug.
To me it looks like a problem with line 617 in bootstrap-vue/src/components/tabs/tabs.js:

controls: this.tab && this.tab.safeId ? this.tab.safeId() : null,

where this.tab and this.tab.safeId are undefined - changing code to:

tab && tab.safeId ? tab.safeId() : null,

is working, the attribute `aria-controls` is shown in the link in the tab.

- BootstrapVue: 2.xx

**Comment by jackmu95** [comment]
Closes by #3832.
