### ISSUE TITLE
Return empty values last in table sorting

### ISSUE THREAD

**Issue by eddybrando** [bootstrap-vue/bootstrap-vue#3816]
### Is your feature request related to a problem? Please describe...

When empty data (for example an empty String `""`) is present in table rows, the sorting function presents this first when sorted in ascending order.

### Describe the solution you'd like

Empty fields should be returned last.

### Describe alternatives you've considered

As I see it, there may be a couple of ways to present the results:

1. Empty fields are always returned last (both in ascending and descending order)
2. Empty fields are returned last when ascending order is selected

This may also be a configurable property to pass.

### Additional context

I'm aware that the empty string comes technically before "a" for instance, but presenting a lot of empty data first when sorting is bad UX.

**Comment by eddybrando** [comment]
I believe this may be a feature that more people could find useful.

For my personal usage, I've created a simple sorting method that I pass to `b-table` via the `sort-compare` property:

```javascript
methods: {
    sortCompare: function(aRow, bRow, key) {
      const a = aRow[key];
      const b = bRow[key];
      if (
        (typeof a === "number" && typeof b === "number") ||
        (a instanceof Date && b instanceof Date)
      ) {
        return a < b ? -1 : a > b ? 1 : 0;
      } else if (this.toString(a) === "") {
        return 1;
      } else if (this.toString(b) === "") {
        return -1;
      } else {
        return this.toString(a).localeCompare(this.toString(b), undefined, {
          numeric: true
        });
      }
    },
    toString: function(value) {
      if (value === null || typeof value === "undefined") {
        return "";
      } else if (value instanceof Object) {
        return Object.keys(value)
          .sort()
          .map(key => this.toString(value[key]))
          .join(" ");
      } else {
        return String(value);
      }
    }
  }
```

**Comment by tmorehouse** [comment]
PR #3808 adds in an option for sorting null/undefined values last.

We could augment that to also allow sorting empty strings the same as nulls/undefined.

**Comment by eddybrando** [comment]
> PR #3808 adds in an option for sorting null/undefined values last.
> 
> We could augment that to also allow sorting empty strings the same as nulls/undefined.

Awesome. Would you suggest to try and continue the discussion in PR #3808, or should we continue here and try to improve on that once it gets merged?

**Comment by tmorehouse** [comment]
The new `sort-null-last` now also handles the empty string case as well.  setting the prop to `true` will sort `null`, `undefined`, and `''` last.

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0-rc.28 has been released.
