### ISSUE TITLE
v-for menu dynamic, href :to vue-router, name and link loop

### ISSUE THREAD

**Issue by italopm** [bootstrap-vue/bootstrap-vue#3818]
Hello,

I have a problem with two v-for, i have a menu, with  vue-router, name and val href. 
I can't do it show name link with val href in :to=""

I needed show name or description link, and href val.

link to code : https://jsfiddle.net/owaz0hgf/1/

  
```
<div class="sidebar vue">
    <ul class="list-unstyled">
      <li>
        
        <div v-for="(groupmenu, namemenu) in groupsmenu">
          <a @click="groupmenu.open = !groupmenu.open" v-text="groupmenu.namemenu"></a>          
          <ul v-show="groupmenu.open" class="list-unstyled">
 
  <!--  LOOP 1 -->
  
            <li>
              <b-link v-for="linknew in groupmenu.linksnew" v-html="linknew" :to="`${linknew}`" ></b-link>
            </li>


 <!-- LOOP 2 -->
 
 
            <li>
              <b-link v-for="linknamenew in groupmenu.linksnamenew" v-html="linknamenew"></b-link>
            </li>
            
            
          </ul>

        </div>        
        
      </li>
    </ul>
</div>

```

```
var groupsmenu = [
  {
    namemenu:"MENU A",
    open: true,
    linksnamenew: [
      "link1 A name",
      "link2 A name"
    ],
    linksnew: [
      "link1A",
      "link2A"
    ]
  }, 
  {
    namemenu:"MENU B",
    open: true,
    linksnamenew: [
      "link1 B name",
      "link2 B name"
    ],
    linksnew: [
      "link1B",
      "link2B"
    ]
  }
]

var vm = new Vue({

  el: ".vue",
  data: {
    groupsmenu: groupsmenu
  }
  
})
```

![image](https://user-images.githubusercontent.com/53281005/62493622-dd475c00-b7d1-11e9-99d3-adcafea86cb3.png)

in LOOP 1 view only link, but not a name "link" or "description", href it's OK

in LOOP 2 view only name or description link, but link href not it's view.

the target for me, is one loop with just href link, and show name or description link.

some advice, please.

thanks.

**Comment by Hiws** [comment]
If you just want one loop that contains both the href link and a name/description for the link.
You can simply make an array of objects instead of strings, where each object contain the href and name/description like in the fiddle below.

https://jsfiddle.net/r9he83ta/1/
