### ISSUE TITLE
Datalist with form-input displays Id Value

### ISSUE THREAD

**Issue by albertolo** [bootstrap-vue/bootstrap-vue#3819]
### Describe the bug

When using the datalist with a form input to filter an array, when selecting one of the array options, the form input displays the datalist selected value. 

 
 ### Expected behavior
I will like to be able to choose what to display in the form-input, whether is the text or the value. 
### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Desktop 
- OS:  Win 10 
- Browser: Chrome, Opera
 

### Demo link

https://codepen.io/albertolo/pen/qepROY

**Comment by tmorehouse** [comment]
Datalists are a native browser feature, and not a custom BootstrapVue feature (although BootstrapVue creates a helper component for generating datalists). As such, the behaviour is controlled by the browser and not BootstrapVue
