### ISSUE TITLE
Make `modalContent`'s tag configurable

### ISSUE THREAD

**Issue by oskar1233** [bootstrap-vue/bootstrap-vue#3821]
### Is your feature request related to a problem? Please describe...

We want to have a form in our modal where inputs are in content and submit button is in footer.

### Describe the solution you'd like

We'd want to make `modalContent`'s tag configurable. Then we can set the tag to `form` and place inputs and submits wherever we like them, be it header, content or footer.

**Comment by tmorehouse** [comment]
When you place buttons or input outside of a form element, you can use the `form` attribute that points to the ID of the form you want the control to be part of.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#form

**Comment by oskar1233** [comment]
Wow, thank you! Didn't know this attribute.
