### ISSUE TITLE
Binding inline style with rows of the table

### ISSUE THREAD

**Issue by allaghi** [bootstrap-vue/bootstrap-vue#3822]
Hello everyone,
Have a nice day,
I am wondering if we could bind inline style as new feature of rows in table. so each row can be styled based on certain value , for instance we might need to color row based on value which is store in database like (#b84743). 

Many Thanks & Best Regards,

**Comment by tmorehouse** [comment]
You could create a custom table class variant, such as `table-b84743` that sets teh background color to `#b84743`, and apply that class as the row's `_rowVariant`, or via the `tbody-tr-class` prop (via a callback function) that applies the class based on information 9or criteria) contained within the row's data.

**Comment by allaghi** [comment]
the value of color comes from database , so if we change it into another value , we need to change the table class manually , which is not convenient way

**Comment by tmorehouse** [comment]
Here is a nifty trick to create dynamic style classes using Vue's `<component>` component:

https://stackoverflow.com/a/57331310/2744776

You can dynamically create `<style>` elements which have reactive style rules.

**Comment by allaghi** [comment]
I did it by using primary-key which generates unique id for each row and then use document.getElementById to style background each row using Loop.

**Comment by allaghi** [comment]
I still believe there is has to be way to apply inline style for every row on the table
