### ISSUE TITLE
IE 11 SCRIPT5002: Function expected

### ISSUE THREAD

**Issue by JFGHT** [bootstrap-vue/bootstrap-vue#3823]
### Describe the bug
IE 11 is showing `SCRIPT5002: Function expected` error pointing to this line:
https://github.com/bootstrap-vue/bootstrap-vue/blob/2fb5ce823a577fcc2414d78bd43ed9e5351cb1c0/src/utils/dom.js#L110

### Steps to reproduce the bug

1. Create Vue project.
2. Use bootstrap-vue
3. `Yarn serve`
4. Open in IE11.

### Expected behavior

Working with no errors.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.26
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Ubuntu
- Browser: IE
- Version: 11

**Comment by tmorehouse** [comment]
Which component/feature are you using when this error is generated?

**Comment by tmorehouse** [comment]
Also for IE 11 support you need to make sure you are loading the required polyfills.

**Comment by Szu-mi** [comment]
To me LayoutPlugin is not working in IE11
`breakpointPropMap = Object(_utils_object__WEBPACK_IMPORTED_MODULE_5__["assign"])(Object(_utils_object__WEBPACK_IMPORTED_MODULE_5__["create"])(null), {
    col: Object(_utils_object__WEBPACK_IMPORTED_MODULE_5__["keys"])(breakpointCol),
    offset: Object(_utils_object__WEBPACK_IMPORTED_MODULE_5__["keys"])(breakpointOffset),
    order: Object(_utils_object__WEBPACK_IMPORTED_MODULE_5__["keys"])(breakpointOrder)
  })`
 `SCRIPT5002: Function expected File: col.js, Line: 94, Column: 3`

**Comment by tmorehouse** [comment]
Are you using an appropriate polyfill for IE11? In later version of BootstrapVue we have removed most of the polyfills from the code in favour of using user provided polyfils.

https://bootstrap-vue.js.org/docs#browser-support

https://bootstrap-vue.js.org/docs#browser

**Comment by JFGHT** [comment]
It could be that. I'll be reporting next week.

**Comment by tmorehouse** [comment]
Are you importing individual plugins or using the whole BootstrapVue lib? And if importing individual plugins, are you following the new import syntax:

```js
import { LayoutPlugin, TabsPlugin } from 'bootstrap-vue'
```

**Comment by Szu-mi** [comment]
Yes in my case it was import syntax not updated... thanks for the help.

**Comment by plucile** [comment]
Hi, I'm having a similar issue with a Vue component using Bootstrap Vue BPopover and BButton. The component is working well but on IE 11 it's not rendering and showing the error: `SCRIPT5002: Function expected` in `bv-event.class.js (25,5)`.
My code is as follows: 
```
<template>
    <div>
        <div class="social-links">
          <b-button id="wechat-popover"><svg class="icon"><use xlink:href="/assets/svg/icon.svg#wechat" /></svg></b-button>
        </div>

        <b-popover ref="popover" target="wechat-popover" placement="topright">
            <b-button class="close-btn" @click="onClose"><svg class="icon"><use xlink:href="/assets/svg/icon.svg#close" /></svg></b-button>
            <img :src="qr" style="display:block;margin: 0 auto;"/>
        </b-popover>
    </div>
</template>

<script>
import {BPopover, BButton} from 'bootstrap-vue';

export default {
    components: {
        BPopover,
        BButton
    },
    props: {
        qr: {type: String, required: true}
    },
    methods: {
        onOpen() {
            this.$refs.popover.$emit('open')
        },

        onClose() {
            this.$refs.popover.$emit('close')
        }
    }
}
</script>
```

**Comment by tmorehouse** [comment]
Make sure you are loading the latest polyfills for IE11

What polyfills are you including in your code?  `core-js`? `polyfill.io`? `@babel/polyfill`?

The docs site uses BootstrapVue, and it runs fine on IE11 (note we are including the polyfill.io polyfills)

https://bootstrap-vue.js.org/docs#browser-support

**Comment by plucile** [comment]
Thank you so much for your reply, I included @babel/polyfill and it works now!

**Comment by audetcameron** [comment]
<script src="//polyfill.io/v3/polyfill.min.js?features=es2015%2CIntersectionObserver" crossorigin="anonymous"></script>   is empty for me.

**Comment by tmorehouse** [comment]
@audetcameron Polyfill.io only delivers the polyfills if the browser requires it (based on the browser type header

**Comment by audetcameron** [comment]
> @audetcameron Polyfill.io only delivers the polyfills if the browser requires it (based on the browser type HTTP header

nice to know :) thanks for the heads up

**Comment by tmorehouse** [comment]
It's great rather than always sending polyfills to all browsers, even if they don't need them.
