### ISSUE TITLE
Numeric fields are placed before other fields in a <b-table>

### ISSUE THREAD

**Issue by schajee** [bootstrap-vue/bootstrap-vue#3833]
### Describe the bug

Table column order is expected to be the same in which the fields are present in the items array. E.g. if items array contains `{field1: "a", field2: "b"}` then b-table columns are ordered `field1|field2`. However if the item contains fields that are numeric, i.e. `{field1: "a", 1: "b"}` then the b-table columns are ordered `1|field1`.

### Steps to reproduce the bug

1. Define the items array...
`items: [ {field1: "a", 1: "b"}, {field1: "c", 1: "d"} ]`
2. Create a b-table...
`<b-table :items="items"></b-table>`
3. Output looks like the table below...

1 | field 1
-- | -------
a | b
c | d

### Expected behavior
The output should look like...

field1 | 1
------ | -
b | a
d | c

### Versions

**Libraries:**

- BootstrapVue: 2.0.0 RC.27
- Bootstrap: 4.3
- Vue: 2.x

**Comment by jackmu95** [comment]
@schajee This is a limitation of JavaScript itself. With ES5+ the order of the keys in an object is guaranteed but not in the order of the source.

See: https://stackoverflow.com/a/54670669

If you want the exact order you have to use the `fields` property (e.g. `feilds: ['field1', 1]`).

**Comment by schajee** [comment]
Understood. For now I've reverted to using a custom **table** instead of **b-table**.
