### ISSUE TITLE
Dist lib does not strip template comments

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#384]
I believe this may be a bug more directly related to your lib bundler (Rollup?), but comments inside template blocks seem to be stripping out the comment, but leaving the comment token. The component I noticed this on was the Card component.

This is more of a heads up than an issue. Probably something you can use to open an issue with the bundler plugin for the `.vue` files.

Source: 
![image](https://cloud.githubusercontent.com/assets/16269252/25975241/0bbda8ee-3662-11e7-8a3f-472a871e4e8e.png)

Rendered markup:
![image](https://cloud.githubusercontent.com/assets/16269252/25975294/4b26d438-3662-11e7-84a4-b73dc827d57f.png)

I'm running v0.15.6

**Comment by tmorehouse** [comment]
The <----> comments are actually from Vue, where you use the `v-if` ans are "placeholder" elements that Vue tracks for inserting the the content if `v-if` is `true`

**Comment by alexsasharegan** [comment]
Crazy! Good to know! Is there a doc section on this? I'm curious to know how you even query comments from the dom.

**Comment by tmorehouse** [comment]
All things the the DOM are "nodes", HTMLElement are a subclass of Nodes, comments are  subclass of Nodes, and bare text are also Nodes.

https://developer.mozilla.org/en/docs/Web/API/Node

**Comment by tmorehouse** [comment]
Example:
```html
<div id="foo"><div id="baz>Baz</div><!----><div id="bar">Hello world</div></div>
```
```js
bar = document.getElementById('bar');
// bar => '<div id="bar">Hello world</div>'

bar.previousElementSibling
//  => <div id="baz>Baz</div>
bar.previousElementSibling.nodeName
// => "DIV"
bar.previousElementSibling.toString()
// => "[object HTMLDivElement]"

bar.previousSibling
// => <!---->
bar.previousSibling.nodeName
// => "#comment"
bar.previousSibling.toString()
// => "[object Comment]"

**Comment by alexsasharegan** [comment]
Thank you! You can definitely close this.
