### ISSUE TITLE
b-modal - Tabbing thru a modal scrolls the page down to bottom

### ISSUE THREAD

**Issue by jamart2005** [bootstrap-vue/bootstrap-vue#3842]
### Describe the bug
When you are tabbing thru a modal (like accessibility users). After the focus goes from the last button to the whole modal. the page behind the modal get scrolled to bottom.

### Steps to reproduce the bug
1. Go to https://bootstrap-vue.js.org/docs/components/modal/
2. Click on **Launch demo modal**
3. Tab thru the modal until you hit **OK** button
4. Tab one more time

### Expected behavior
Page should not scrolled down in the background.

### Versions
**Environment:**
- OS: Windows 10
- Browser: Chrome
- Version: 74

### Additional context
This seems to be more an annoyance/weird behavior than a usability issue cause focus goes back to button that triggers the modal after closing it anyway

**Comment by tmorehouse** [comment]
I haven't seen this behaviour using chrome (Windows 7 though).

It also depends on the size of the modal (height) and the browser default behaviour. We have a "tab trap" at the bottom of each modal content which when focused will transfer focus to the modal container. If the modal content is "tall", then it will cause a scroll to handle the bottom of the modal container.

Which version of BootstrapVue are you using?

**Comment by tmorehouse** [comment]
Also note that each browser manufacturer has there own way of moving the content being focused to within the Vewport

**Comment by jamart2005** [comment]
Its the latest one: v2.0.0-rc.27

Modal area itself is not tall in this case... but the whole overlay is part of the modal so the focus do shift to the whole page pretty much.

Was just playing around with the "tab trap" in chrome.  It seems its physically in the bottom of the page.  I tried adding contents to the tab trap div and I don't see it while the page is still scrolled up but once I tab thru it and page scrolls down. I see the contents. I think this explains why its scrolls down cause its focuses on an element in bottom of page

**Comment by tmorehouse** [comment]
I think I have found the solution for this.... will be creating a PR shortly
