### ISSUE TITLE
[b-tabs] not able to active a new tab added on fly 

### ISSUE THREAD

**Issue by darkman97i** [bootstrap-vue/bootstrap-vue#3845]
### Describe the bug
The problem was also indicated in this closed ticket https://github.com/bootstrap-vue/bootstrap-vue/issues/1378 but I suspect never was solved ( if it might be solved? ).

Basically after adding a new tab dynamically is not possible to activate this tab on fly. 

I'm using v-model="groups" what is a list of elements

I have tested with :
```javascript
this.$nextTick(() => {
          this.tabIndex = this.groups.length - 1;
        });
```
and also with 
```javascript
Vue.nextTick().then(() => {
          this.tabIndex = this.groups.length - 1;
        });
```

### Expected behavior
I success get it working with a timeout, but seems a not safe way for doing it:
```
setTimeout(() => {
          this.tabIndex = this.groups.length - 1;
        }, 400);
```
I would like to know if it is another version to get it running

### Versions

**Libraries:**
- BootstrapVue: 2.0.0-rc.24
- Bootstrap: 4.3.1
- Vue: 2.6.6

**Environment:**
- Browser: Chrome 
- Version: 75.0.3770.100 (Build oficial) (64 bits)

### Demo link
Here is an old sample of the issue what is not working as expected: http://jsfiddle.net/cihkem/3apaaz4n/1/

**Comment by tmorehouse** [comment]
Try upgrading to BootstrapVue 2.0.0-rc.27 (and ugrade Vue to 2.6.10)

**Comment by tmorehouse** [comment]
Also note that tabs uses a transition (when prop `no-fade` is not set), and need to watch for changes in the DOM to detect when tabs are added/removed, and to determine the visual order of the tabs), which requires an additional delay to be introduced before attempting to activate a newly added tab.

try this:

```js
this.$nextTick(() => {
  requestAnimationFrame(() => {
    this.tabIndex = this.groups.length - 1;
  })
});
```

**Comment by darkman97i** [comment]
Not working for me. I have also added a watch for tabIndex. In my sample I have only a single tab and then I add a new one.  This is the console log:

applying change to 1 ( here is called by nextTick... requestAnimationFrame )
tabIndex watch:1
tabIndex watch:0 ( b-tabs inself comes to tab 0 )

**Comment by tmorehouse** [comment]
When you diagrammatically add a tab (i.e. with v-if, or similar), you can have the b-tab's `active` prop set, which will activate the tab once it is discovered (assuming the new tab appears last)

And after reviewing the code, I think you need a double nextTick + Request animation frame to set the new active tab index (via the v-model), to get around the delays introduced into the tab probing process:

```js
this.$nextTick(() => {
  this.$nextTick(() => {
    requestAnimationFrame(() => {
      this.tabIndex = this.groups.length - 1;
    })
  })
});
```

Or if using the promise version of $nextTick (with async support):
```js
await this.$nextTick();
await this.$nextTick();
requestAnimationFrame(() => {
  this.tabIndex = this.groups.length - 1;
});
```

**Comment by darkman97i** [comment]
Both worked. I'm decided to go for the async version of the Promise.

Thanks for your time

**Comment by tmorehouse** [comment]
The async version makes your code much cleaner (less callback hell).

To make `requestAnimationFrame` also async, you can make a utility method:

```js
const waitRAF = () => new Promise(resolve => requestAnimationFrame(resolve));
```

and use it like this:

```js
await waitRAF();
```

**Comment by tmorehouse** [comment]
@darkman97i I just remembered about another way you could know when the tab is ready to be activated.  `<b-tabs>` emits the event `changed` when tabs are added, changed, or re-ordered.  You could listen to that event and update the v-model then.

https://bootstrap-vue.js.org/docs/components/tabs#comp-ref-b-tabs-events
