### ISSUE TITLE
How to show empty state if table array is empty when filter?

### ISSUE THREAD

**Issue by lavezzi1** [bootstrap-vue/bootstrap-vue#385]
Hi there!

In my case I want to show empty state if user search something with `input v-model="filter"` and found nothing. I see `_items` is private. Thanks!

**Comment by tmorehouse** [comment]
I wonder if a named slot for `empty` and a slot for `emptyFiltered` could be created (and conditionally shown based on the length of `this._items` and `this.items` ?

The slot could be set to have a `td`  with `colspan` set to of the number of fields available.

It would also be nice to have a named slot for  `tfoot` element (or conditional `tfoot`)

**Comment by lavezzi1** [comment]
> I wonder if a named slot for empty and a slot for emptyFiltered could be created (and conditionally shown based on the length of this._items and/or this.items ?

Sounds like a good idea!

**Comment by tmorehouse** [comment]
I have a prototype that I will be testing.  and will generate a PR later.

**Comment by tmorehouse** [comment]
Now available in the latest developments release.

**Comment by lavezzi1** [comment]
@tmorehouse `:colspan="fields.length"` you can't get length of an object. You should do something like `:colspan="Object.keys(fields).length"`

**Comment by tmorehouse** [comment]
Oops,  true, used to dealing with the items length.

**Comment by tmorehouse** [comment]
I have fixed this in the PR #389

**Comment by tmorehouse** [comment]
Should be all fixed is latest master branch.
