### ISSUE TITLE
about Tree shaking 

### ISSUE THREAD

**Issue by TrumanGu** [bootstrap-vue/bootstrap-vue#3852]
Sorry to open an issue to ask questions
I just read the code of the project and noticed some interesting places.
About \#__PURE\__, #3462, the commit message is approximately 'this annotation helps the project's tree shaking'
![image](https://user-images.githubusercontent.com/32283973/62848934-35211e00-bd10-11e9-94fa-6d580594b85c.png)
I noticed that the project uses Rollup for tree shaking
But when I opened package.json, I found that all files were marked as sideEffects,
![image](https://user-images.githubusercontent.com/32283973/62849117-f9d31f00-bd10-11e9-9612-6549c088af2b.png)
However, the project does not use webpack for build, is this configuration redundant?

**Comment by tmorehouse** [comment]
The `sideEffects` property in `pakage.json` is used by webpack (and others) to determine which files have sidde effects.  If you note, we have not marked any of our `*.js` files as having sideEffects.  So your conclusion that all files have side effects is incorrect.  This field is actually for **other** users of BootstrapVue, when they include BootstrapVue in their project.

The `/*#__PURE__*/` annotation is for tree shaking with the `/dist/bootstrap-vue.esm/.js` bundle build (which rolls up all the BootstrapVue components and plugins into a single file), and users want some tree shaking if they are using that esm.js bundle build (actually it would be DCE - Dead Code Elimination) and are only importing certain components.
