### ISSUE TITLE
How to open a popover when a dropdown is also open?

### ISSUE THREAD

**Issue by azdanov** [bootstrap-vue/bootstrap-vue#3853]
For example, each click on a `dropdown-item` would open a popover attached to the `dropdown`. This behavior worked in `2.0.0-rc.26`.

Is there a way to override the new logic (that prevents popovers from opening) of https://github.com/bootstrap-vue/bootstrap-vue/pull/3704 that was introduced in `2.0.0-rc.27`?

**Comment by tmorehouse** [comment]
Wrap your dropdown in a wrapper element, and apply the popover to that wrapper element.

Note that you may still run into the issue where the popover obscures the dropdown, specifically on smaller screens.  It is not the best UI mix (popover + dropdown) when it comes to usability and accessibility.

**Comment by azdanov** [comment]
Thank you for your answer!
