### ISSUE TITLE
b-form-input formatter cannot work properly with type date 

### ISSUE THREAD

**Issue by JackEggie** [bootstrap-vue/bootstrap-vue#3855]
### Describe the bug

b-form-input formatter cannot work properly with type date 

### Expected behavior

The input should parse the utc date string with formatter method but not 

### Demo link

[CodePen](https://codepen.io/JackEggie/pen/RXqpEj)

**Comment by jackmu95** [comment]
@JackEggie This is not a problem of the `<b-form-input>` component. It is a limitation of the date input itself. Each browser vendor implements a a different UI for it.

The `formatter` itself is working fine.

**Comment by tmorehouse** [comment]
`b-form-input` is a wrapper for a standard `<input>` element.  The `<input>` element always (and only) returns/accepts  a string value (not a number, not a date object, etc), regardless of input type.

**Comment by JackEggie** [comment]
Sorry for not describing this issue clearly. I met this issue when updating bootstrap-vue from v2.0.0-rc.11 to the latest. In version v2.0.0-rc.11, it works. As you explained, does it mean bootstrap-vue will not support `b-form-input` with type `date` even in latest chrome?

Here is the comparison between v2.0.0-rc.11 and the latest version:

[b-form-input formatter not working with type date with latest](https://codepen.io/JackEggie/pen/RXqpEj)
with dependency: `https://unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.js`
![image](https://user-images.githubusercontent.com/8253572/62917977-e2f40180-bdd0-11e9-83a1-691ed8d16ec7.png)

[b-form-input formatter not working with type date with v2.0.0-rc.11](https://codepen.io/JackEggie/pen/wvwKPaR)
with dependency: `https://unpkg.com/bootstrap-vue@v2.0.0-rc.11/dist/bootstrap-vue.min.js`
![image](https://user-images.githubusercontent.com/8253572/62917999-f2734a80-bdd0-11e9-8133-a70577cfc57d.png)

**Comment by tmorehouse** [comment]
Formatter is for formatting the _content_ of the input (what is presented inside the input to the user), not for formatting the returned value of the input. The date type input expects a very specific formatted string.

It appears you may have been taking advantage of a bug on an earlier release.  

If you are looking to format what is returned, use a computed prop with a getter/setter as your input's v-model. https://vuejs.org/v2/guide/computed.html#Computed-Setter

The getter would return the date in the format the type `date` input expects, while the setter would take the format provided by the input and covert it into the format you want to preset as a value (outside of the input).

**Comment by tmorehouse** [comment]
> And in addition, in my example, the b-from-input accepts a string and the formatter dose also.

Yes, but the input of type `date` expects the value in a specific format:  'YYYY-MM-DD'. If your formatter is returning anything other than that, it will be considered and invalid date by the input. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by JackEggie** [comment]
I understand how you implement this now. I just need a way to ensure the value of the input to be `YYYY-MM-DD`. I will try to get value with this format before injecting into `b-form-input`.

Many thx 😄

**Comment by tmorehouse** [comment]
An input of type `date`, on modern browsers (excludes IE11), all expect, and return, the date in the `YYYY-MM-DD` format.  On browsers that do not support the `date` type input, they fall back to rendering a plain text input.  To make the browser support only the fomrat the date input expects, you can do the following:

```html
<b-form-input type="date" pattern="\d\d\d\d-(0[1-9]|1[1-2])-(0[1-9]|[1-2][0-9]|3[0-1])"></b-form-input>
```

the pattern attribute (available on native browser inputs), expects a regular expression, which the input value must match to be considered valid.

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Validation-related_attributes
