### ISSUE TITLE
table toggleDetails lost after update

### ISSUE THREAD

**Issue by estani** [bootstrap-vue/bootstrap-vue#3865]
When using toggleDetails on an entry that get's replaced (completely replaced e.g. by using splice as is vue requirement ofr handling arrays) the row lose it's "details being shown" state.

bootstrap-vue@^2.0.0-rc.24:
  version "2.0.0-rc.25"

(also interesting that the versioning schema used by bootstrap-vue does not allow to pin a version in yarn, other issue though)

So, the problem is that an extra attribute is added to the object for this functionality, `_showDetails`. My workaround is to copy this value on the mutation while swapping the object with the new one retrieved from the backend. This is quite bad to be honest.

Is there a better workaround?

Another way of implementing this in bootstrap would have been to rely on `primary-key` (at least if set). I think it will be much better to store internally a "set" of `primary-key`s depicting those elements being shown.

**Comment by tmorehouse** [comment]
Vue 2.x cannot detect when a property is being added to an object. https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

The `_showDetails` special data prop must exist the row's item object.  Internally BootstrapVue uses `this.$set(items[index], `_showDetails`, true/false)` to ensure the property is known about reactively by Vue.

Without seeing an example of how you are splicing data into the array, and your html markup, it is hard to give you a pointer.

Re yarn:

In your package json, you can pin a version of a library using the following syntax:

```json
{
  "dependencies": {
    "bootstrap-vue": "2.0.0-rc.24"
  }
}
```

**Comment by estani** [comment]
That wasn't that easy to get an example, but kudos to the playground! It helped a lot...

So this is the example with the current rc-28 version: https://jsfiddle.net/u6oaptjc/

I also tried with the rc-24 (since I made a mistake and it seemed to work with rc-28): https://jsfiddle.net/u6oaptjc/1/

if you add the _showDetails:true (or copy the value) when mocking the backend response, then it works. (my awful workaround)

**Comment by estani** [comment]
By the way this is the same with the primary-key set: https://jsfiddle.net/mgu1cfwr/
I would expect it to preserve the detail view open after the values are "saved" since the primary key never changed.

**Comment by tmorehouse** [comment]
the `_showdetails` property is set in each item's row. you would need to ensure this field is set when replacing the row.
