### ISSUE TITLE
Rendering custom labels via scoped slots using array instead of function does not work

### ISSUE THREAD

**Issue by spaceemotion** [bootstrap-vue/bootstrap-vue#3871]
### Describe the bug

I've created a functional component that renders Form Group elements. When I try to specify my custom label content using the "scopedSlot" feature, stuff breaks if I return an array instead of a render function. 

### Steps to reproduce the bug

Call createElement like so:

```js
createElement(
  'b-form-group',
  {
    scopedSlots: {
      // This works:
      label: () => createElement('label', {}, 'A label'),
             
      // This doesn't:
      // label: [createElement('label', {}, 'A label')],
    }
  },
  'Some content'
)
```

### Expected behavior

[According to the render function docs](https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth), returning an array in the scopedSlots setting should work.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Vue: 2.6.10

### Demo link

https://jsfiddle.net/av8z0tso/

**Comment by tmorehouse** [comment]
The render _function_ can return either an _array of v-nodes_, or a _single root v-node_.

https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth

>   ```js
>   // Scoped slots in the form of
>   // { name: props => VNode | Array<VNode> }
>   scopedSlots: {
>    default: props => createElement('span', props.text)
>   }
> ```

scopedSlots are always functions. In your example you are returning an array that returns the content of a function inside it.

**Comment by spaceemotion** [comment]
Ouch, so I just misread the comment about the typehint then. Thanks!
