### ISSUE TITLE
docs: Tabs documentation page is broken

### ISSUE THREAD

**Issue by jumisz** [bootstrap-vue/bootstrap-vue#3873]
### Describe the bug

The tabs documentation page is broken in the docs website.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/tabs
2. See error

### Expected behavior

I expect the Tabs documentation page to display appropriate documentation.

**Comment by tmorehouse** [comment]
it is working for me:

![image](https://user-images.githubusercontent.com/2781561/62953774-7ffc6d80-bdc4-11e9-8dfc-ffdc169da2c0.png)

What browser are you using?

**Comment by jumisz** [comment]
Yes it works now. It must have been related to instabilities related to the latest release. Bad timing. Apologies!
