### ISSUE TITLE
link.js:168 with this.$attrs.tabindex - this.$attrs is undefined

### ISSUE THREAD

**Issue by Vaflan** [bootstrap-vue/bootstrap-vue#3875]
### Describe the bug

[Vue warn]: Error in render function: "TypeError: Cannot read property 'tabindex' of undefined"
TypeError: Cannot read property 'tabindex' of undefined

In: src/components/link/link.js:168 with this.$attrs.tabindex

this.$attrs is undefined

### Steps to reproduce the bug

Use simple example from documentation https://bootstrap-vue.js.org/docs/components/navbar
With packeg versions:
    vue: 2.4.2
    bootstrap: 4.3.1
    bootstrap-vue: 2.0.0-rc.28
    vue-resource :1.3.4
    vue-router: 2.7.0

### Expected behavior

Doesn't show menu elements `b-nav-item` in `b-navbar-nav`

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Bootstrap: 4.3.1
- Vue: 2.4.2

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version: 76.0.3809.100

**Comment by tmorehouse** [comment]
You should be using Vue 2.5 or greater. Vue 2.6.10 or higher is recommended. Vue 2.4 is missing many of the features required, and has several bugs.

**Comment by Vaflan** [comment]
Yeah, i tested with:

    Vue: 2.6.10

work great, sorry for issue
