### ISSUE TITLE
b-form-checkbox disobeys normal v-model rules

### ISSUE THREAD

**Issue by SignalDancer** [bootstrap-vue/bootstrap-vue#3877]
### Describe the bug

All vue.js documentation clearly states that v-model is supposed to be an alias for v-bind:value which can be expressed as :value

The b-form-checkbox component breaks this rule (I assume to follow the "value" html spec for checkbox) which is confusing. 

### Steps to reproduce the bug

See documentation/implementation

### Expected behavior

For sanity sake of developers in vue.js I would propose that b-form-checkbox needs to obey the vue.js rules.
v-model and :value should become equivalent with only one used.
A different property (such as checkbox-value perhaps) of any other name should be used for what :value is currently representing. 

### Versions

**Libraries:**

BootstrapVue:2.0.0-rc27

**Environment:**
All

### Additional context

Add any other context about the bug here.

**Comment by SignalDancer** [comment]
I wasn't sure if this was a "bug" but i didn't think it was a feature request - it's a framework rule break. Apologies if this is not where this should go.

**Comment by tmorehouse** [comment]
`:value` will not be dynamically updated, as it needs to be in sync with the event that updates the model.

using `v-bind:value` alone on a custom component will not work, as it will never be synced to the underlying component model.

https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model

https://vuejs.org/v2/guide/render-function.html#v-model

> All vue.js documentation clearly states that v-model is supposed to be an alias for v-bind:value which can be expressed as :value

That statement is incorrect.

**Comment by SignalDancer** [comment]
ah @tmorehouse  thanks for the info that v-model isn't always tied to the prop value. I was under the impression it was.  apologies.
