### ISSUE TITLE
It gets messy when I try to add bootstrap manually

### ISSUE THREAD

**Issue by frbuceta** [bootstrap-vue/bootstrap-vue#3878]
### Describe the bug

When trying to change the variables for example `$ primary` does not apply the same css as by default in nuxt

Applying bootstrap css from custom.scss:
![Captura de pantalla 2019-08-13 a las 23 06 04](https://user-images.githubusercontent.com/13822438/62978594-f1b6d480-be21-11e9-83cd-1c66ec3951d3.png)

### Steps to reproduce the bug

1. Add to nuxt config
```
  bootstrapVue: {
    bootstrapCSS: false,
    bootstrapVueCSS: false
  }
```
2. Create `custom.scss` in `assets`
```
$primary: #fff; // For example
$bg-color: #fefefe; // For example

@import '~bootstrap/scss/bootstrap.scss';
@import '~bootstrap-vue/src/index.scss';
```

3. Implement in nuxt config
```
  styleResources: {
    scss: ['~/assets/main.scss', '~/assets/custom.scss']
  }
```

### Expected behavior

This is how it looks without applying bootstrap css apart

![Captura de pantalla 2019-08-13 a las 23 02 47](https://user-images.githubusercontent.com/13822438/62978681-22970980-be22-11e9-98c3-52b020955070.png)

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Bootstrap: 4.3.1
- Nuxt: 2.8.1

**Environment:**

- Device: [e.g. Mac or iPhone X] Mac
- OS: [e.g. macOS Mojave or iOS 12] MacOS 10.14.6
- Browser: [e.g. Chrome] Google Chrome
- Version: [e.g. 70] Versión 76.0.3809.100 (Build oficial) (64 bits)

**Comment by tmorehouse** [comment]
The SCSS variables (+ SCSS mixins and functions)  need to be imported into all SCSS files.

By default Nuxt does not share the variables between files.

```js
  styleResources: {
    scss: ['~/assets/main.scss', '~/assets/custom.scss']
  }
```
Nuxt imports the SCSS file indivdually, compiles them with sass-loader individually, so you get two distinct CSS files that have nothing shared between them.

**Comment by frbuceta** [comment]
but the only thing I try is to overwrite those bootstrap variables, not share them with css

**Comment by tmorehouse** [comment]
The CSS is generated based on the values of the SCSS variables. The browser doesn't understand SCSS/SASS... so Nuxt is compiling them into CSS.

You need to import both '~/assets/main.scss' and '~/assets/custom.scss' into a single SCSS file (specifically if they are using the same variables)

**Comment by frbuceta** [comment]
Yes, I understand how Nuxt works with respect to scss

Those two files are not related. It was just as an example to see that I have more than one scss and that custom.scss bootstrap is loaded through imports
