### ISSUE TITLE
Navbar toggle-breakpoint doesn't allow for extra small breakpoint

### ISSUE THREAD

**Issue by pkat** [bootstrap-vue/bootstrap-vue#388]
`<b-navbar>` defaults to `sm` for the `toggle-breakpoint` property. In order to have the navbar collapse at the extra small breakpoint (576px), the class should simply be `navbar-toggleable`.

Currently there is no way to achieve this without adding the class youself, and even so you end up with the `navbar-toggleable-` class on the element if you specify empty string for `toggle-beakpoint`, otherwise it defaults to `sm`.

Can this be updated to either be `navbar-toggleable` by default, or allow a null or empty string value to add the `navbar-toggleable` without the `-*`?

[Boostrap docs reference](https://v4-alpha.getbootstrap.com/components/navbar/#how-it-works)

**Comment by tmorehouse** [comment]
Commit https://github.com/bootstrap-vue/bootstrap-vue/commit/31b866610b48f87082ada70171a7530b2f29c365 should help with this

**Comment by alexsasharegan** [comment]
Yes! I literally had this problem yesterday @pkat , and we just merged a PR for supporting this!

**Comment by pkat** [comment]
Perfect. Thanks all!
