### ISSUE TITLE
deselecting rows with this.$refs['tableName'].clearSelected()

### ISSUE THREAD

**Issue by vaxo101** [bootstrap-vue/bootstrap-vue#3882]
### Describe the bug

I am currently utilising the `@row-selected` function on b-table to launch a b-modal. Once b-modal is closed it is not de-selecting the table item that was initially selected to launch the modal (which is expected). However when using the new `this.$refs.clearSelected()` function on the cancel or save buttons of the bootstrap modals it re-launches the modal when the function is run, however the table item becomes deselected.

### Steps to reproduce the bug

1. Go to [...]
2. Click on [...]
3. Scroll down to [...]

### Expected behavior

this.$refs['tblName'].clearSelected() should deselect the table and b-modal should not re-open.

### Versions
v2.0.0-rc.28
**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.1.3
- Vue: 2.5.17
- CoreUI: 2.0.4

**Environment:**

- Device: [e.g. Mac or iPhone X] Mac
- OS: [e.g. macOS Mojave or iOS 12] MacOS Latest
- Browser: [e.g. Chrome] Safari & Chrome
- Version: [e.g. 70]

**Comment by tmorehouse** [comment]
The `row-selected` event fires whenever the array of selected rows changes.  Including when it changes to no rows selected (which is why you are probably seeing your modal open again).

**Comment by vaxo101** [comment]
@tmorehouse Thanks for your response and clarification. How would i prevent my modal from re-opening?

**Comment by vaxo101** [comment]
@tmorehouse thanks for you help. I added clearSelected() to my row-selected function, seems to do the trick.
