### ISSUE TITLE
Header-row disappeared - Different behavior of stacked option in the 2.0.0-rc.27 vs 2.0.0-rc.28-release

### ISSUE THREAD

**Issue by JanBolmeson** [bootstrap-vue/bootstrap-vue#3886]
### Describe the bug
I upgraded to 2.0.0-rc.28 today and noticed the header-row stopped showing up on all my tables that had a stacked-option, e.g. stacked="md". I downgraded to rc.27 and everything worked fine. 

### Steps to reproduce the bug
See: 
https://codesandbox.io/s/bootstrap-vue-table-bug-rc28-r31q3

### Expected behavior
A header row is expectead as in the rc27-version

See:
https://codesandbox.io/s/bootstrap-vue-table-bug-rc27-xl2se

**Comment by JanBolmeson** [comment]
Hmm... just noticed: 
https://github.com/bootstrap-vue/bootstrap-vue/pull/3862

🤦‍♂

**Comment by tmorehouse** [comment]
Thanks for finding this bug.

We will have it fixed in the 2.0.0 stable release coming soon.

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0 stable has been released. See https://bootstrap-vue.js.org/docs/misc/changelog
