### ISSUE TITLE
b-collapse requires id

### ISSUE THREAD

**Issue by billy1380** [bootstrap-vue/bootstrap-vue#3894]
### Describe the bug

When the b-collapse control is used without and id property a warning appears in the console suggesting that an id is required. Not sure why that should be the case.

The warning is:
[Vue warn]: Missing required prop: "id"

### Steps to reproduce the bug

1. Create a template that uses b-collapse without the id property
2. render the template
3. open the inspector on Chrome

### Expected behavior

Not sure why there is a warning at all for this specific control

### Versions

**Libraries:**

- bootstrap: 4.3.1,
- bootstrap-vue: 2.0.0-rc.27
- Vue: 2.6.10

**Environment:**

- OS: Linux
- Browser: Chrome
- Version: 76

**Comment by tmorehouse** [comment]
The ID is required for the `v-b-toggle` directive to know which collapse to toggle state on. 

It is a required prop on the component. All signalling of state between the control and teh collapse is keyed by the ID.

Per the docs, prop `id` is flagged as being required: https://bootstrap-vue.js.org/docs/components/collapse#comp-ref-b-collapse

![image](https://user-images.githubusercontent.com/2781561/63099407-6d607080-bf4b-11e9-9cd3-1b83f81c9c4e.png)

**Comment by tmorehouse** [comment]
ID is no longer a required prop on `<b-collapse>`
