### ISSUE TITLE
form-group label size to huge

### ISSUE THREAD

**Issue by trueleader** [bootstrap-vue/bootstrap-vue#3897]
Applying "bg-light" as "label-class" property of "form-group" component results in a background which exceeds the outer html form. We try to create a form with a full-size label-column background color.

I first thinked about a bug of bootstrap and created a [ticket](https://github.com/twbs/bootstrap/issues/29243). They responded that this is intended result of "form-row" and "col*" usage: A background should be applied to the inner element.

In bootstap-vue this can only be done with "label" slot, but not a "label" property. When using the slot the element will require additional styling because of the classes of the legend element: bootstrap-vue adds both "col*" and "col-form-label"

I think for correct sizeing a form-group:
```
<b-form-group 
	label="label" 
	description="description"
	valid-feedback="success"
	invalid-feedback="error"
	label-class="bg-light"
>
	Content
</b-form-group>
```
Should generate something like the following html:
```html
<fieldset class="form-group">
	<!-- form-row automatically adds negative left and right margins  -->
	<div class="form-row">
		<!-- container required to only apply bootstraps size and padding information ("col*") which corrects the margin of form-row -->
		<div class="col">
			<!-- container required to support full size backgrounds -->
			<div class="bg-light">
				<!-- legend which applies the label behaviors -->
				<legend class="col-form-label">label</legend>
			<div>
		<div>
		<div class="col">
			Content
			<div class="invalid-feedback">error</div>
			<div class="valid-feedback">success</div>
			<small class="form-text text-muted">description</small>
		</div>
	</div>
</fieldset>
```

This seems to be a little awkward. Maybe someone has an alternative?

**Comment by tmorehouse** [comment]
legends are a bit harder to style then labels, which is why there is some stange markup on b-form-group depending on what is used (and also to get around a few issues with the current Bootstrap v4.3 CSS  (label sizing doesn't quite work as good with the legend element)

**Comment by tmorehouse** [comment]
Could you provide a screen shot of what you are seeing, and which browser?

And maybe an example of your outer form markup around the form-group?

This is what I am seeing:
![image](https://user-images.githubusercontent.com/2781561/63115614-f12b5480-bf6d-11e9-83bd-5b3a42ee3b93.png)

**Comment by tmorehouse** [comment]
The form-group markup with the `<label>` element is the recommended markup (with the col classes on the label)

**Comment by tmorehouse** [comment]
With wrapping in a `<form>` element.  you should either add the class `container` to the form, or wrap your form-groups in a `<b-container>` to adjust for the margins on horizontal forms (form-row)

**Comment by trueleader** [comment]
https://jsfiddle.net/qnub093j/
![image](https://user-images.githubusercontent.com/7026107/63166165-d91b0a00-c02d-11e9-8525-570cc1cd0087.png)

Neither wrapping form-group alone nor together with the "element marker" results in a uniform background line.

**Comment by tmorehouse** [comment]
Your screen shot / fiddle doesn't use the container class or element (containers are used to get around the negative margins of `row` and `form-row`. try this:

```html
<div>
  <div class="bg-warning mb-3">DIV</div>
  <b-form class="bg-dark">
    <b-container fluid>
      <b-form-group
        id="fieldset-horizontal"
        label-cols-sm="4"
        label-cols-lg="3"
        label-class="bg-info"
        description="Let us know your name."
        label="Enter your name"
        label-for="input-horizontal"
      >
        <b-form-input id="input-horizontal"></b-form-input>
      </b-form-group>
    <b-container>
  </b-form>
  <div class="bg-warning">DIV</div>
</div>
```

Which results in this:

![image](https://user-images.githubusercontent.com/2781561/63183837-59d90680-c02c-11e9-9c0b-efd0397b23a8.png)

**Comment by trueleader** [comment]
Yes - I only wanted to provide a single playground starting with the simple problem. I tried the container wrapping different parts as explained above.

Your screenshot shows the problem: the container creates a full-width background but the label still does not fit: now it is smaller, not larger than the parent element. If I duplicate the row, then we see not only the difference in with, but also an additional space in height

**Comment by tmorehouse** [comment]
As noted [above](https://github.com/bootstrap-vue/bootstrap-vue/issues/3897#issuecomment-521740468), `b-form-group` generates the suggested markup from Bootstrap v4.3

**Comment by trueleader** [comment]
And the official answer for backgrounds inside the initial linked ticket is
> The behavior you're seeing is intentional because of the use of padding in our grid classes. Use the nested elements as suggested to avoid interacting with the predefined grid classes.

An inner element created via the label-slot is restricted by the additional paddings of the col-form-label class (as initial wrote).

So I can sum up: full size backgrounds on a form-group label are not supported ootb (yet)?

**Comment by tmorehouse** [comment]
It depends on what you refer to as "full size"

**Comment by trueleader** [comment]
The red arrows of the last screenshot: This two dark spaces should be also the color of bg-info.

**Comment by tmorehouse** [comment]
https://jsfiddle.net/5n964s8x/

**Comment by trueleader** [comment]
Yes: Width is fixed because of size-related col-* class. but the col-form-label class adds top- and bottom- padding, so the height of the slot-label can not easily (h-100) take the full height.

As solution seems to be an additional `legend.col-form-label { margin-top: calc((.375rem + 1px)*-1); margin-bottom: calc((.375rem + 1px)*-1); }`

**Comment by tmorehouse** [comment]
You could try adding prop `label-class="mb-0 mt-0"` which removes the label's top and bottom margin.

**Comment by trueleader** [comment]
Ah, thx: adding of "pt-0 pb-0" to remove the padding, instead of creating a new selector with margins to negate the same effect, seems to be a much cleaner way
