### ISSUE TITLE
ShowHeader: false not supported on tables

### ISSUE THREAD

**Issue by michalhudecek** [bootstrap-vue/bootstrap-vue#3899]
### Describe the bug

Following parameter from Bootstrap is not supported in Bootstrap-Vue: https://bootstrap-table.com/docs/api/table-options/#showheader

### Expected behavior

There should be a parameter like hideHeader that would hide the header row in a table.

**Comment by tmorehouse** [comment]
The showHeader parameter is not a standard Bootstrap v4 (it is a feature of _Bootstrap Tables_, which is a 3rd party jQuery plugin).

However this may be a feature (to visually hide the header), but it would need some additional work to ensure each data cell has an appropriate ARIA accessibility attribute to convey the cells heading.

You can alternatively use `<b-table-simple>`  to render your own header, body, footers.
