### ISSUE TITLE
Unknown custom element: <b-badge>

### ISSUE THREAD

**Issue by chrisyip** [bootstrap-vue/bootstrap-vue#39]
Version: ^0.3.10

I saw there's an introduction about `<b-badge>` on documentation page, but got `Unknown custom element: <b-badge>` error.

![image](https://cloud.githubusercontent.com/assets/189559/21102100/8d467dda-c0b7-11e6-8048-1021be3a0b01.png)

I uses `bootstrap-vue` as a global plugin:

```js
import BootstrapVue from 'bootstrap-vue'
Vue.use(BootstrapVue)
```

**Comment by mathlet0x** [comment]
It's a documentation mistake. The badge component does not exists because according to the bootstrap4 migration documentation :

> Dropped the .badge component as it was nearly identical to labels/tags. Use the .tag-pill modifier together with the label component instead for that rounded look.

You should try to use tags component.

**Comment by chrisyip** [comment]
👌 Thanks!
