### ISSUE TITLE
Stacked attribute with a breakpoint lets the header disappear

### ISSUE THREAD

**Issue by RCVZ** [bootstrap-vue/bootstrap-vue#3903]
Stacked attribute with a breakpoint lets the header en footer disappear, while the screen hasn't reach the breakingpoint. This happened when I upgraded  to rc28.

As seen in the sandbox below.

https://codesandbox.io/s/vue-template-7vwqe

**Comment by tmorehouse** [comment]
Duplicate https://github.com/bootstrap-vue/bootstrap-vue/issues/3886. 

fixed  by PR #3887
