### ISSUE TITLE
"Object expected" Error in Internet explorer 11.

### ISSUE THREAD

**Issue by Giwayume** [bootstrap-vue/bootstrap-vue#3904]
### Describe the bug

When loading the bootstrap-vue library on to the page in IE11, it throws an error **"SCRIPT5007: Object expected File: bootstrap-vue.min.js, Line: 10, Column: 95516"** and the library does not load.

### Steps to reproduce the bug

Add `<script src="//unpkg.com/bootstrap-vue@2.0.0-rc.28/dist/bootstrap-vue.min.js"></script>` to any page and run the page in IE11. No further setup is necessary.

### Expected behavior

The library loads in IE11. The last working version is 2.0.0-rc.25.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- OS: Windows 7
- Browser: Internet Explorer 11
- Version: 11.0.9600.19266

**Comment by tmorehouse** [comment]
IE11 requires polyfills in order to work.

Are you loading the appropriate polyfills as mentioned in the getting started docs?

https://bootstrap-vue.js.org/docs#browser-support

**Comment by mattsteve** [comment]
Hmm... just a few versions ago this used to not be the case.

**Comment by jackmu95** [comment]
@mattsteve See #3781 for more information.

**Comment by tmorehouse** [comment]
See also https://bootstrap-vue.js.org/docs/misc/changelog#v200-rc26

**Comment by Ju66ernaut** [comment]
I solved this exact issue with adding in polyfills for IE as mentioned by @tmorehouse
