### ISSUE TITLE
NuxtJS tree shake BToast & BToaster Component

### ISSUE THREAD

**Issue by ram231** [bootstrap-vue/bootstrap-vue#3909]
### Steps to reproduce the bug

1. Go to `nuxt.config.js` file
2. Scroll down to `bootstrapVue` object

I did not use the BToast and BToaster component in the html tag, but rather, in javascript way.
I have imported the BToast and Toaster and it seems that the `this.$bvToast.toast()` is being ignored and thus, it does not show any warning/errors after tree shaking.

```javascript
export default{
bootstrapVue:{
    components:["BToast","BToaster"]
      }
}
```

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**
"bootstrap-vue": "^2.0.0-rc.27",
"nuxt": "^2.0.0",
"boostrap": "^2.0.0",
- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.js.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
If you are not importing the `ToastPlugin`, but rahter the `BToast` and `BToaster` components, the `BVToastPlugin` will **not** be automatically installed.

`this.$bvToast` is only available via plugins (as it has to install on the global `Vue.prototype`).  Components do not have this option for installing anything on the global Vue app instance.

From the docs: https://bootstrap-vue.js.org/docs/components/toast#toasts-on-demand

> **Notes:**
> - The this.$bvToast injection is only available when using the full `BootstrapVue` plugin or the `ToastPlugin` plugin. It is not available if importing just the `b-toast` or `b-toaster` components. To just import the injection, use the `BVToastPlugin` plugin.

So add `BVToastPlugin` to your nuxt.config.js` in the `BootstrapVue.plugins` array.
