### ISSUE TITLE
The "click" event doesn't work with the "b-nav-item" component

### ISSUE THREAD

**Issue by cynecx** [bootstrap-vue/bootstrap-vue#391]
Demo: https://jsfiddle.net/atb4cnjg/20/

The "click" event doesn't work with the "b-nav-item" component.

**Comment by pi0** [comment]
Should be fixed by 650799f961d357a70d317bf2181c8d1bd3cbfcdb @0.15.8

**Comment by cynecx** [comment]
Thank You. It seems fixed.
