### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by timster** [bootstrap-vue/bootstrap-vue#3911]
### Describe the bug

The link to "Twitter: Vetur + BootstrapVue" goes to a tweet that no longer exists

https://bootstrap-vue.netlify.com/docs/#vs-code--vetur

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.netlify.com/docs/#vs-code--vetur
2. Click on "Twitter: Vetur + BootstrapVue"
3. See error

### Expected behavior

The link should go somewhere that explains how to use Vetur with BootstrapVue.

**Comment by jackmu95** [comment]
@tmorehouse I think we can just remove the link at all.

**Comment by tmorehouse** [comment]
@jackmu95 yeah
