### ISSUE TITLE
failed to set selectionStart and selectionEnd of a text field when it is created in a modal

### ISSUE THREAD

**Issue by luckymanyau** [bootstrap-vue/bootstrap-vue#3914]
### Describe the bug

Setting selectionStart and selectionEnd of a text field to a certain value will fail with no error, when it is created in a modal

### Steps to reproduce the bug

1. create a modal with an input and a button 
2. set the behaviour of the button such that
2.1 it will insert certain characters, say 'bar', at the selectionStart of the input created in step 1, and 
2.2 it will set the selectionStart and selectionEnd to a new value, say selectionStart + insertedValue.length
3. open the modal
4. initialize the input field
5. change the cursor position to the start of the field
6. click the button twice

### Expected behavior

'bar' should be inserted at the cursor position twice

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc28
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: [Linux desktop]
- OS: [Mint 19 Tara]
- Browser: [Chrome]
- Version: [70]

### Demo link

https://jsfiddle.net/xn56g0sd/

**Comment by tmorehouse** [comment]
It appears that the first click inserts the selection at the correct spot, but the cursor then jumps to the end of the input and the second insert then happens at the end for some reason.

**Comment by tmorehouse** [comment]
If you add the prop `static` to the modal (so that it renders in-pace in the dom, rather than being portalled to the end of document body) the issue goes away.

It has to be related to the Portalling, or the fact that the ref may update as the modal is portalled.

**Comment by tmorehouse** [comment]
After a further bit of investigation... the issue is with the delay introduced by the portalling.

You need to use either a double `$nextTick` or use a `requestAnimationFrame` before updating the selection.

See this updated fiddle using `requestAnimationFrame` instead of `$nextTick`: https://jsfiddle.net/xyf82aoL/

**Comment by luckymanyau** [comment]
Thanks you tmorehouse for your workaround. 

`requestAnimationFrame` works nicely in my case but there is a limitation in Edge and IE support. It seems I have no luck using using double `$nextTick` which probably has better browser compatiblity.

If I have to put 2 cents in, it would be nice to have the workarounds in the documentation.
