### ISSUE TITLE
<b-form-select> trigger muliple events

### ISSUE THREAD

**Issue by varun761** [bootstrap-vue/bootstrap-vue#3915]
I am creating dynamic 5 select components and the input is bind to an array containing object like
arrayInput:[{value:null},{value:null},{value:null}]
While changing the one input, multiple events got triggered and that causes the other to change
![Screenshot_4](https://user-images.githubusercontent.com/15170824/63336146-48f60100-c35c-11e9-812d-55e3bb7cd2c1.png)
![Screenshot_5](https://user-images.githubusercontent.com/15170824/63336148-498e9780-c35c-11e9-9157-052c9dd1d67a.png)
![Screenshot_6](https://user-images.githubusercontent.com/15170824/63336149-498e9780-c35c-11e9-8372-f2def86dcfa9.png)
![Screenshot_7](https://user-images.githubusercontent.com/15170824/63336238-6dea7400-c35c-11e9-85c0-639f9243dedc.png)

**Comment by tmorehouse** [comment]
I would avoid using `index` as the `:key`, and switch to some unique identifier in the `item` as the `:key'`
