### ISSUE TITLE
popover blur

### ISSUE THREAD

**Issue by 2017jw** [bootstrap-vue/bootstrap-vue#3917]
popover look blur on windows 10 latest chrome with a systen scale of 125%. I have checked the same issue in Bootstrap V4's github. they say it is the issue with propper. Since Bootstrap-vue does not use proper. wondering what's the problem here and how to figure it out.

**Comment by 2017jw** [comment]
This is a issue with CSS transform, not the fault of bootstrap and bootstrap-vue. Thanks.

**Comment by tmorehouse** [comment]
BootstrapVue actually uses Popper.js (the same as Bootstrap) for positioning the tooltips and popovers (as well as dropdowns).

**Comment by 2017jw** [comment]
> BootstrapVue actually uses Popper.js (the same as Bootstrap) for positioning the tooltips and popovers (as well as dropdowns).

OK, thanks. I use the way they posted in [bootstrap/issues/22610](https://github.com/twbs/bootstrap/issues/22610) . And there is no problem anymore.

**Comment by bernhardberger** [comment]
@2017jw can you post a solution for this here? Not sure how I can get any of those proposed fixes in the linked thread to work..
