### ISSUE TITLE
<b-card> add class only for header or footer

### ISSUE THREAD

**Issue by MfeaR** [bootstrap-vue/bootstrap-vue#392]
I have add class `bg-info` only for header or footer. 
I need create this block
```
<div class="card">
    <div class="card-header bg-info text-white">text</div>
     hello world
</div>
```
I tired

```
<b-card show-header>
   <div class="bg-info" slot="header" variant="info">test</div>
   hello world
 </b-card>
```

But this code transform in

```
<div class="card">
     <div class="card-header">
          <div class="bg-info text-white">text</div> 
    </div>
    hello world
</div>
```

How to do it?

**Comment by tmorehouse** [comment]
Try this:

```html
<b-card show-header>
  <template slot="header">
    <div class="bg-info">test</div>
  </template>
      hello world
</b-card>
````

It might not be exactly the result you want.

**Comment by losblancos113** [comment]
I have same problem as you. Have you found the solution for this issue?
@MfeaR

**Comment by alexsasharegan** [comment]
Can anyone confirm they tried @tmorehouse's solution and it didn't work? @losblancos113 @MfeaR

**Comment by losblancos113** [comment]
@alexsasharegan ,
yes, I tried and it did't work.

@tmorehouse 
I want to add class bg-info into div.card-header but your solution still effect .card-header childs only

**Comment by tmorehouse** [comment]
We may need to add in a few extra props for adding classes to various portions of the card

**Comment by alexsasharegan** [comment]
+ 1 on this enhancement. I've wanted to have a simpler way to set header and footer backgrounds. I did it with CSS before, but BS4 saves a lot of unnecessary CSS and handles inverting the text color for you.

**Comment by losblancos113** [comment]
Hi guys,
I have created a new props call headerClass to <b-card> component and now it work.
You can check this out my lastest commit on my forked repository.
Code:
`            headerClass: {
                type: String,
                default: null
            },
`

`        computed: {
            headerClasses() {
                let header = {
                    'card-header' : true
                };
                if(this.headerClass != null && this.headerClass.length > 0){
                    let formattedHeaderClass = this.headerClass.replace(/\s+/g,' ').trim();
                    let classes = formattedHeaderClass.split(' ');
                    classes.forEach((clazz) => {
                        header[clazz] = true;
                    });
                }
              return header;
            },
`

**Comment by alexsasharegan** [comment]
@losblancos113, I think you might want to consider making the `headerClass` prop accept a string or an array. Then you won't need to set every object value to true or deal with any value sanitation (the regex replace and trim shouldn't be necessary).

Also, I think we should extend this to the footer. Maybe you can even leave the `class="card-header"`, but just add the plain `:class="headerClass"` since Vue can handle interpolating all the string, object, or array values to classes.

**Comment by tmorehouse** [comment]
Something like this in the vue component:
```html
<template>
  <div class="card">
     <div :class="['card-header', headerClass]">
          <div class="bg-info text-white">text</div> 
    </div>
   ....
  </div>
</template>

<script>
props: {
    headerClass: {
        type: [String, Array],
        default ''
    }
}
</script>
```

**Comment by losblancos113** [comment]
@alexsasharegan thanks you, I'm new to Vue so I didn't know that 👍 
@tmorehouse Your code looks good. It's simple but do the same thing. 👍

**Comment by tmorehouse** [comment]
Yep, the bound classes can be a string, array, or object, or any combination of each :)

**Comment by tmorehouse** [comment]
Should this be headerVariant (to control the background only), or should we allow the user to place any classes they like onto the header/footer/etc?  Or maybe both?

**Comment by losblancos113** [comment]
I think both of them would be better. headerVariant for basic usage and headerClass for someone who really need to re-style card component.

**Comment by tmorehouse** [comment]
PR #463 should address this issue.

**Comment by tmorehouse** [comment]
And, yet another option would b to apply the card variant type, and then use the default slot (with `no-block` set)and place a `div` in the default slot with a white background..

```html
<b-card show-header variant="info" no-block>
   <template slot="header">test</template>
   <div style="background-color:#fff;color:initial;" class="p-3">
       hello world
   </div>
</b-card>
```
Which would look thile this:
![image](https://cloud.githubusercontent.com/assets/2781561/26525777/8139253e-4338-11e7-8eee-618b90f939a2.png)

**Comment by tmorehouse** [comment]
This features should be available in the next release.

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
