### ISSUE TITLE
Weird border on table outlined with dark head variant

### ISSUE THREAD

**Issue by serpi90** [bootstrap-vue/bootstrap-vue#3923]
Version: 2.0.0-rc.28
Example shown from the [documentation](https://bootstrap-vue.js.org/docs/components/table/#table-styling)
It's easier to show than to explain with words, but there's a white border when using an outlined table with dark head variant.

I think the outline should apply to all the table, not just the body.

![image](https://user-images.githubusercontent.com/5396311/63406226-a2dbe280-c3bf-11e9-877f-a3629f94e754.png)
![image](https://user-images.githubusercontent.com/5396311/63406294-d61e7180-c3bf-11e9-9325-e9d8b687d0d8.png)

**Comment by tmorehouse** [comment]
The `outlined` prop set the border width to `1` on the table element (using the bootstrap utility class `border-1`).  It is probably because the Bootstrap v4.3 CSS doesn't account for this in their `thead-dark` classes.

Might have to add a bit of additional custom SCSS to BootstrapVue to handle this case (and make the border dark on the header cells)

**Comment by serpi90** [comment]
Thanks for the quick response, for now i just added quick and dirty a ` border 1px solid (color)` to the whole table instead of the outline prop.

**Comment by tmorehouse** [comment]
We might just have to switch which utility class we are using... but I think we need to add a special case for thead dark

**Comment by Hiws** [comment]
Looks like adding the `no-border-collapse` prop (which was added in 2.0.0) fixes the border. 
This could be used as another temporary workaround.

**Comment by tmorehouse** [comment]
This will be fixed in Bootstrap v5, as they will have changed how border colors on tables are inherited.

**Comment by tmorehouse** [comment]
Bootstrap v5 is changing how table border, background, and color inheritance works (for the better), we'll close this issue as we anticipate this will be fixed in the Bootstrap v5 release.
