### ISSUE TITLE
TypeAhead

### ISSUE THREAD

**Issue by vikrampariharcodereadr** [bootstrap-vue/bootstrap-vue#3925]
As we know every most UI framework has Autocomplete feature.
So i would request you to add new Autocomplete or Typehead officially library in vue bootstrap with multi-select options

**Comment by tmorehouse** [comment]
If created, it probably would need to be a directive, which could be applied to an input.

One could create a `b-datalist` with dynamic options that are updated as the input value changes (note that data list doesn't work on IE 11)

**Comment by spontaliku-softaria** [comment]
I'd argue `datalist` is a workaround:
* Browsers filter options themselves based on form input text. If you put options ["vue", "bootstrap"] for form input containing "v", "bootstrap" option will not be rendered at all.
* Little or no control over options - general HTML inside options is not supported. Chrome renders some HTML in specific way, you have no control over it.
* No proper events - no `change` or whatever, even no `click` on `option`s.

**Comment by tmorehouse** [comment]
Also, there is a 3rd party component, using BootstrapStyles that provides typeahead support:

https://github.com/alexurquhart/vue-bootstrap-typeahead

**Comment by vikrampariharcodereadr** [comment]
I do not want to go with third party component. i will wait until bootstrap-vue does not introduce this tool self.
third party tools makes by build size bigger, and does not have frequently updates.
