### ISSUE TITLE
Error in v-on handler: "TypeError: Function expected"

### ISSUE THREAD

**Issue by kjuro** [bootstrap-vue/bootstrap-vue#3926]
### Describe the bug

I have problem with b-form-select in IE 11. In Chrome or Firefox it works fine.
On selecting some value from select I get error in console:

[Vue warn]: Error in v-on handler: "TypeError: Function expected"
```
found in
---> <BFormSelect>
            <App> at src/App.vue
                 <Root>
```

### Steps to reproduce the bug

1. Test code is:

```
<template>
    <div id="app">
        <b-form-select v-model="selected" :options="options"></b-form-select>
        <b-form-select v-model="selected" :options="options" size="sm" class="mt-3"></b-form-select>
        <div class="mt-3">Selected: <strong>{{ selected }}</strong></div>
    </div>
</template>
<script>
    export default {
        data() {
            return {
                selected: null,
                options: [
                    { value: null, text: 'Please select an option' },
                    { value: 'a', text: 'This is First option' },
                    { value: 'b', text: 'Selected Option' },
                    { value: { C: '3PO' }, text: 'This is an option with object value' },
                    { value: 'd', text: 'This one is disabled', disabled: true }
                ]
            }
        }
    }
</script>
```
2. Open page in IE. 
3. Select some value from first select 
4. Check exception in console

### Expected behavior

Exception should not be thrown, both selects should have the same value and selected value should be shown.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Windows 7
- Browser: Internet Explorer 11
- Version: 11.0.9600.19431

### Additional context

I tried to install:

`npm install core-js regenerator-runtime intersection-observer`

and add to the top of main.js file:

```
import 'core-js'
import 'regenerator-runtime/runtime'
import 'intersection-observer' // Optional
```

It didn't help.

**Comment by kjuro** [comment]
I debugged demo application. Exception is thrown in node_modules/bootstrap-vue/esm/components/form-select/form-select.js on line 121:

var selectedVal = arrayFrom(target.options).filter(function (o) {

IE says that "arrayFrom" is undefined. 

How to solve this?

**Comment by jackmu95** [comment]
@kjuro This is definitely related to missing polyfills. Make sure to follow suggested steps in the [docs](https://bootstrap-vue.js.org/docs/#browser-support).

See also: https://babeljs.io/docs/en/babel-polyfill

**Comment by kjuro** [comment]
I added to the <head> in index.html:
`<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=Array.from"></script>`
It seems to work now. Thanks.

**Comment by WvanDam** [comment]
@kjuro Thanks! That fixed it. 

The suggested babel polyfill didn't.

**Comment by WvanDam** [comment]
ok, thanks for the clarification. 

`.browserlistrc` is (and was) set to `> 1%`, which should have included IE11 as per https://browserl.ist/?q=%3E+1%25.

Using a 3rd party service is not ideal, but considering we're planning to drop support for IE11 soon enough anyhow it's acceptable.

**Comment by tmorehouse** [comment]
Also note babel polyfill is now no longer maintained.  `core-js` polyfill is probably a better bet.
