### ISSUE TITLE
Passing computed prop to child in g-image

### ISSUE THREAD

**Issue by Zyles** [bootstrap-vue/bootstrap-vue#3927]
### Describe the bug

I made a custom component that uses g-image as child but I can't seem to pass on the "src" prop from my main Vue file.

Setup looks like this Main.vue:

```
<InformationBlock imageUrl="~/assets/foobar.png">
      <h2>Headline</h2>
      <p>Content</p>
</InformationBlock>
```

InformationBlock.vue:

```
<template>
  <b-container>
    <g-image v-bind:src="imageUrl" />
  </b-container>
</template>

<script>
export default {
props: {
    imageUrl: String
  },
</script>
```

I tried multiple ways to get this to work but it will give an error 404 not found for the image url:

I also tried a computed prop but it still won't resolve the assets url correctly.

```
GET http://localhost:18819/~/assets/foobar.png 404 (Not Found)
````

I'm using this with Gridsome ^0.6.0

### Versions

**Libraries:**

- BootstrapVue: ^2.0.0-rc.28
- Gridsome  ^0.6.0
- Bootstrap: ^4.3.1
- Vue: ^2.6.10

**Environment:**

- OS: wINDOWS 10
- Browser: Chrome

**Comment by tmorehouse** [comment]
Vue loader needs to know that your `src` prop on the component is a local asset.

You need to update the `transformAssetUrls` config, similar to: https://bootstrap-vue.js.org/docs/reference/images but with the addition of your custom component and prop name.

**Comment by tmorehouse** [comment]
Also note that our image component is `b-img` not `g-image`
