### ISSUE TITLE
Input prefix/suffix

### ISSUE THREAD

**Issue by Zyles** [bootstrap-vue/bootstrap-vue#3929]
Is there a way to add input prefix or suffix?

If there is not I would like to see this feature.

Example:
![suffix](https://user-images.githubusercontent.com/1741593/63518595-aff8ee80-c4f1-11e9-8a4d-2b3ba8c74284.png)

Thanks.

**Comment by tmorehouse** [comment]
You can make a bit of markup to generate something similar, although focus styling will not highlight the whole outline (just the input) using a few Bootstrap utility classes:

```html
<b-input-group>
  <b-form-input class="border-right-0"></b-form-input>
  <b-input-group-append>
    <b-input-group-text class="bg-transparent">
      USD
    </b-input-group-text>
  </b-input-group-append>
</b-input-group>
```

See fiddle: https://jsfiddle.net/9s7L3dgp/

**Comment by Zyles** [comment]
Thank you, that is great.

**Comment by tmorehouse** [comment]
Class `border-right-0` is used to remove the border on the right of the input, and class `bg-transparent` is used on the addon text to make its background color transparent (instead of the default of light grey)
