### ISSUE TITLE
[Laravel] Issue with transpiling

### ISSUE THREAD

**Issue by rdgout** [bootstrap-vue/bootstrap-vue#393]
When I try to create a build version of my app I run into the following issue:

```
/js/app.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/bootstrap-vue/lib/mixins/form.js:3,0][/js/app.js:23,18]
```

The problem as noted here: [Issue on another repo](https://github.com/sagalbot/vue-select/issues/71) seems to be happening here too. In short:
> essentially babel doesn't get applied to the mixins in src/mixins/, so they are not transpiled to ES5. The next release will be precompiled so that dev's don't have to modify the build process.

Could you make sure these files are transpiled to ES5 and distributed that way on the next build?
This will result in less issues for production builds and it doesn't hurt anyone.

**Comment by pi0** [comment]
Hi @rdgout  it seems you are importing bootstrap-vue in a wrong way :)) We already have Commonjs and esm builds. (https://unpkg.com/bootstrap-vue@0.15.8/dist) 
What is your webpack version/configuration ? Also how are you importing library?

**Comment by rdgout** [comment]
hi @pi0,

I'm using [Laravel mix](https://github.com/JeffreyWay/laravel-mix) to compile it.
It's using webpack 2.3.3. My config file is the default one: [config file](https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js)

Importing is done with: 

```
import BootstrapVue from 'bootstrap-vue' 
```
I've also used the loading of individual files since I'm using vue-router. But I reverted that in an attempt to fix my issue. I didn't have this issue earlier on with 0.14 I believe.

Should I be loading a different version from the distribution folder instead of making webpack choose one?

**Comment by pi0** [comment]
Here is a modified version of `bootstrap.js` which is should be already included in your laravel 5.4+ project.
https://gist.github.com/pi0/c30d99425f6f2ad5ab65ca895cc99819

Require bootrap-vue seems to be enough. 
```js
/**
 * BootstrapVue Provides Vue.js 2 ready bootstrap components
 */
require('bootstrap-vue');
```

**Comment by rdgout** [comment]
Unfortunately, that was not the fix.

I still have to use the following:

```
import BootstrapVue from 'bootstrap-vue';

Vue.use(BootstrapVue);
```

When I remove all separate imports, it does work without issues. 
(Apparently I forgot a few). 
This makes me load the entire library though whilst I don't really use all of it.

It does compile though, so the issue must be somewhere when you try to load separate components inside your components. For example:

```
import { bInputGroup, bInputGroupAddon, bFormInput, bInputGroupButton, bDropdown, bNav, bNavItem, bNavItemDropdown, bDropdownItem, bModal, bButton, bLink } from 'bootstrap-vue/lib/components'
```

The issue I noted in the first message of the issue still seems to be related to this. These components load ES6 mixins and babel does not seem to understand these need to be transpiled to ES5.

**Comment by pi0** [comment]
@rdgout This problem is related to default shipped webpack config of laravel mix and you may to prepare a customized build. BTW total bundle size is just **16KB** gzipped and such usage is just over-optimizing! (You at most will save up to 6-7 KB)
If REALLY REALLY needed you can add a clone of bootstrap-vue source code inside your project (actually outside of `node_modules` which is ignoring babel transforms) It would be working.

**Comment by rdgout** [comment]
Okay, I'll load the entire library for now!

Thanks for the quick help!

**Comment by variegated** [comment]
when using boostrapvue beta5 I am getting this error "Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option."
I am not using vue-router

**Comment by mosinve** [comment]
is there a name of unknown element within error? usually it is
