### ISSUE TITLE
Bold/Highlight Matching Text From Filter

### ISSUE THREAD

**Issue by jmason03** [bootstrap-vue/bootstrap-vue#3930]
### Is your feature request related to a problem? Please describe...

There is no way to highlight or visually convey where the text is in a column when it is matched in a filter. It would be helpful if the text displayed that matches the text entered in the filter could be bolded.

### Describe the solution you'd like

As text is entered into a table's corresponding filter input, any text visible in a table cell that matches the value provided is bolded

### Describe alternatives you've considered

Due to limitations of how the table handles HTML strings, I'm not aware of any workaround to accomplish this behavior.

**Comment by tmorehouse** [comment]
You could use scoped slots to handle formatting the text within the data cells, matching your filter criteria.

Matching will vary based on the type of filter criteria (if users have their own filter-function, the criteria could be any JavaScript primitive or object, so baking this into b-table would be difficult, as it would be impossible to cover all cases).
