### ISSUE TITLE
Set a Bootstrap Vue input using native JS value property

### ISSUE THREAD

**Issue by cjd118** [bootstrap-vue/bootstrap-vue#3933]
Hi,

We have an application with a child window that posts certain data back into the parent window. 

This data needs to be inputted in the Bootstrap Vue input field but the calling component and responding inputs are separate and unrelated components.

I tried:

```
document.getElementById('foo').value = 'bar';
```
and this updates the value in the actual input, however that value never saves. It's like Bootstrap Vue needs an extra method or event to fire for it to update its internal structure for that input. 

Any advice?

Thanks

**Comment by tmorehouse** [comment]
Vue cant detect direct manipulation of inputs without an event being triggered.  The Vue way to do this would be to use a store (such as Vuex, or a shared Vue instance, https://vuejs.org/v2/guide/state-management.html).

The other way is to trigger (dispatch) a native input (or change) event on the element after updating it's value (see https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent).  This is what Vue test utils does/suggests for testing inputs (https://vue-test-utils.vuejs.org/guides/#testing-key-mouse-and-other-dom-events)
