### ISSUE TITLE
Toast disappears on route change

### ISSUE THREAD

**Issue by long-zhen** [bootstrap-vue/bootstrap-vue#3934]
### Describe the bug

When toast is created on demand, it disappears as you reload page or change route (vue routing).

It's even happening on bootstrap vue doc site as well.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/toast#toasts-on-demand
2. Click on any link on the sidebar to navgiate
3. See toast disappears as soon as page is loaded.

### Expected behavior

The toast should persist since it's rendered outside of page tree, as a portal.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: MacOS Mojave
- Browser: Chrome
- Version: 75.0.3770.142 (Official Build) (64-bit)

### Demo link

https://bootstrap-vue.js.org/docs/components/toast#toasts-on-demand

**Comment by tmorehouse** [comment]
This is expected behaviour.

Toasts are parented to the Vue vm instance that that created them (they appear in the component hierarchy).  When the parent is destroyed (which happens during a route change), the parent triggers a destroy on all of it's descendant instances (children).

**Comment by long-zhen** [comment]
@tmorehouse Thanks for your quick reply. How'd you handle persist toast in that case?

**Comment by tmorehouse** [comment]
You would need to run the `$bvToast.toast(...)` method up higher in the component hierarchy.

Rather than `this.$bvToast.toast(...)`, try `this.$root.$bvToast.toast(...)`, which would make `$root` (your app root) become the parent (as router-view's are always descendants of root).

**Comment by long-zhen** [comment]
👍 That did the trick! Thanks!

**Comment by tmorehouse** [comment]
We should probably note that in the documentation (about toast parenting)

**Comment by muhammad-sewts** [comment]
router.push({ name: 'ProjectsView' }).then(() => notifySuccess('Project added successfully!'))

It works for me like this (:
