### ISSUE TITLE
b-table no header with stacked mode

### ISSUE THREAD

**Issue by MWStudio4** [bootstrap-vue/bootstrap-vue#3938]
### Describe the bug

Using stacked prop as string value breaks header display. Table header default behavior is like stacked=true at all resolutions

### Steps to reproduce the bug

https://codepen.io/MWStudio4/pen/BaBpeGg?&editable=true&editors=101

### Expected behavior

As in the documentation using string value in stacked prop should make table stacked in certain resolutions. So if resolution more then in prop table should be original with header

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: HP laptop
- OS: Linux KDE Neon (Ubuntu 18.04)
- Browser: Chrome
- Version: 76.0.3809.100

### Demo link

[CodePen](https://codepen.io/MWStudio4/pen/BaBpeGg?&editable=true&editors=101)

**Comment by tmorehouse** [comment]
Duplicates: #3932 #3903
Fixed via PR #3887
Will be available in 2.0.0 stable release coming this week.

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0 stable has been released. See https://bootstrap-vue.js.org/docs/misc/changelog
