### ISSUE TITLE
Table Serveside fetch pagination

### ISSUE THREAD

**Issue by Diaskhan** [bootstrap-vue/bootstrap-vue#394]
Hie
There have a server side pagination ??
I have tried items-provider function but it does n work for me !!
My ajax returns [{"id":2,"name":"When died napaleon","text":null,"parent":0,"type":1,"typename":"число"}]
If it works, Could U provide some example ?

        <b-table class="table table-striped table-bordered"  :items="items"  :items-provider="fetch" :fields="fields" :current-page="currentPage" :per-page="perPage" :filter="filter">
            <template slot="isfolder" scope="item">
                <i v-if="item.value==true" class="fa fa-folder"></i>
                <i v-if="item.value==false" class="fa fa-question-circle"></i>
            </template>
            <template slot="name" scope="item">
                <a v-on:click="navigate(item.item)">{{item.value}} </a></i>
            </template>
            <template slot="actions" scope="item">
                <b-btn size="sm" @@click="details(item.item)">Details</b-btn>
            </template>
        </b-table>

    <script>

    var appq = new Vue({
        el: '#apptable',
        data: {
            items: [],
            fields: {
                id: {
                    label: 'ID' //,                     sortable: true
                },
                name: {
                    label: 'Наименование',
                    sortable: true
                },
                actions: {
                    label: 'Действия'
                }
            },
            currentPage: 1,
            perPage: 10,
            filter: null
        },
        mounted: function () {
        },
        methods: {
            details(item) {
                alert(JSON.stringify(item));
            },

            fetch({ perPage, currentPage, filter, sortBy, sortDesc }) {
                var self = this;
                return axios.get('/question/getquestions/6')
                    .then(function (response) {
                        return response.data;
                   });
            },

        }
    })

    </script>

**Comment by tmorehouse** [comment]
For server side pagination, it is possibly best to handle pagination outside of the `b-table` component (and pass the paging parameters to your provider function via variables scoped to your module or data on your app.

Then pass your apps method (which takes advantage of your app's paging state stored in your data) and pass it as the `itemsProvider`  function.

**Comment by Diaskhan** [comment]
Actually I did it As U sad !!
Tnhks for feedback !!!
If I provide Some Example into documentation, Could U apply commit  ??

**Comment by Diaskhan** [comment]
[Example.zip](https://github.com/bootstrap-vue/bootstrap-vue/files/1019227/Example.zip)
I did it that way ! 

But there are some ussue, 

To do serverside pagination We actuaaly must Override  "SORT CLICK"
But I hadn't really thought about it.

**Comment by tmorehouse** [comment]
To override the sort click, we would need to fire off a `table::sort::click` event (or similar) and provide a cancel() method on the event to prevent the local sorting from happening. 

Or provide a new prop that allows you to provide an override function when clicking a sortable field heading.

**Comment by Diaskhan** [comment]
Actually Items-provider not compatible with ajax call
```
 <b-table class="table table-striped table-bordered" :items-provider="itemprov" :fields="fields" :current-page="current" :per-page="perPage" :filter="filter">
        <template slot="name" scope="item">
            <a v-on:click="details(item.item)">{{item.value}} </a></i>
        </template>

    </b-table>

methods: {
            itemprov() {
                var self = this;
                return [{ "id": 6, "name": "sdf", "text": null, "parent": 0, "numberanswer": null, "type": 2, "typename": "", "Answers": null }];
                @*return axios.get('/question/getquestionspage/@ViewBag.id')
                    .then(function (response) {
                        return response.data.items;
                        //self.count = response.data.count;
                    });*@
            }
}
```

**Comment by tmorehouse** [comment]
I'm working on an update to better handle server provided sorting/pagination/filtering.

**Comment by alexsasharegan** [comment]
Looking at the source, I'm pretty sure you need to respond (or should) synchronously with the `itemsProvider`. This would be easier with Vuex, but if you're comfortable with more state in that parent component it could be done.

I think you could skip using `itemsProvider` for doing the ajax fetch, but instead start with your empty array of items. You could make an initial fetch with the `created` hook (hit the backend as early as possible), or just do the fetch based on a user interaction.

In any case, just wipe out the items array on ajax success with your new data and things should update.

```vue
 <b-table :fields="fields" :items="items">
        <template slot="name" scope="item">
            <a v-on:click="details(item.item)">{{item.value}} </a></i>
        </template>

    </b-table>

methods: {
            fetchItems() {
                var self = this;

                axios.get('/question/getquestionspage/@ViewBag.id')
                    .then(function (response) {
                        self.items = response.data.items;
                    });
            }
}
```

**Comment by Diaskhan** [comment]
Nobody told me, that table-vue bostrap has writing with union of Vuex.
Actually I  did that way, that U wrote, But it still remains problem of Sorting and filtering !

**Comment by tmorehouse** [comment]
Currently, when an `itemsProvider` function is supplied, clicking on the `thead` cells (for sorting) doesn't trigger the `itemsProvider` function.  Only changes (reactivity) to props (i.e `perPage, `currentPage`, etc) will trigger the call of the `itemsProvider` function.

This is what I will be addressing in an upcoming PR.

**Comment by Diaskhan** [comment]
Thats kind of components need Deep integration with async fetch libs like axios !
Or I am wrong??? It will be the best if will be an example with table ajax, sorting paging !
Maybe I shall donate for this feature ????

**Comment by tmorehouse** [comment]
You should be able to use an async library within `itemsProvider` functions, as long as you return the result of the resolved promise.

**Comment by Diaskhan** [comment]
Sorry, but not good knoledge to use that kind liabrary !

**Comment by alexsasharegan** [comment]
Async actions are where Vuex can really shine in any Vue project. Bootstrap-vue is just a component library based on the BS4 system, so it's truly agnostic to your state management pattern (be that Vuex, Redux, MobX, or good ol' spaghetti).

In your original example you didn't provider a filter function. The BV docs example uses a form input to get a string by which to filter items. You can build any input device to allow for user filtering. Sorting is done by default with a string locale compare sort. That's probably good enough to start.

As far as getting record sets back from the server, this is the fun of windowing data on the client. Generally speaking, you should be able to query your backend API with some kind of limit offset to provide your front-end with the desired record set.

**Comment by tmorehouse** [comment]
I have a rough prototype set up at https://jsfiddle.net/asc82spc/

This one supports both synchronous and asynchronous itemProviders, by use of a callback function placed on the context passed to the provider function.

If the provider function returns nothing, then it assumes the provider will call the callback function with the data as the only argument.  If the provider function returns data, then it will use that.

It still has a few glitches with respect to the "busy" state.  The table should drop in opacity while data is waiting to be returned, but it doesn't always do so, I think it has to do with the timing on the update of the aria-attribute (which is used to set the opacity value. 

You can switch the provider from async to syn via a dropdown.

**Comment by Diaskhan** [comment]
Tnks **tmorehouse**, I guess codebase and mechanics of vue-table growing up, Maybe we shal divide on two components, 1 for the serverside pagination and 2 for client side pagination !

In the evening I ' will se a solution That U provide.
And write litle bit later.
Tnks one more time **tmorehouse**

**Comment by tmorehouse** [comment]
I have a revised fiddle of the proposed changes to `b-table` which allows for async `itemProvider`

https://jsfiddle.net/p9zyx5wd/

The example allows you to switch from regular `:items="items"` to a to variants (sync and async) of `itemProvider`.  To emulate async in the demo I am using native promises (so only available on some browsers). 

The `item-provider` works in one of two ways.  if your data is coming from a store (local on browser, say), then you would return your items directly from your `itemsProvider` function.  If you want async, the context passed to the itemsProvider function provides a callback (`providerCallback`), which takes an array of items as its only argument, and the items provider function should return nothing (`undefined` or `null`). 

As a bonus, I have added in scoped slots for header fields.

**Comment by tmorehouse** [comment]
Another option, rather than callback, is if  you are using promises (or have loaded a polyfill), then we could test the itemProvider return value to see if it has a 'then' function. (`if items.then && typeof items.then === 'function'`), and use that to resolve the items (in this demo, I use a data variable `this.localItems` to store a copy of the remote items data for the _items function)

**Comment by alexsasharegan** [comment]
I won't have time to peruse the source tonight, but cheers, mate! This sounds like awesome work! 

`setTimeout(alexReview, 24 * 60 * 60 * 1000)`

On the async side of things, naturally callbacks are the safe fallback. My personal stance on testing for Promises is to do a simple, native `window.Promise && $return instanceof Promise`. Polyfills typically cover that check just fine, and given the fact that BV is targeting BS4 alpha, I think we have a fairly progressive set of clients. Why not just keep it simple and plan for the ever-approaching Promise support?

**Comment by tmorehouse** [comment]
Yeah.   That would be one test for sure.  `IE <= 11` is the only current desktop browser that doesn't have native Promises. (http://caniuse.com/#feat=promises)

when testing the provider return value, we can also try:

`items instance of 'Promise'` (but that would assume IE 11 has a promise Polyfill pre-loaded)

`items.then && typeof items.then === 'function'` which would work without full browser sniffing and checking for Polyfills.

Then to load the items we just do:
```js
items = this.itemsProvider(this);
if (items && items.then && typeof items.then === 'function') {
 items.then((data) => {
    this.localItems = data || [];
  });
} elsif (items && items.length > 0) {
    this.localItems = items;
}
```

**Comment by tmorehouse** [comment]
One other optimisation, would be to ditch the `itemsProvider` prop all together, and allow items to be either `Array` or `Function`.  And if  function, then we call it, and deal with the response appropriately.

**Comment by alexsasharegan** [comment]
That's much more elegant sounding!

**Comment by tmorehouse** [comment]
I now  basically finalized version of the partial re-write of `b-table`, and an extended example.

https://jsfiddle.net/o6vfggu5/

The demo allows you to switch provider from none (i.e. items is an Array), to three provider types
- synchronous, where the provider returns an array)
- Async with callback (provider returns nothing, and calls the callback when data is ready)
- Async via Promise (provider returns a promise which resolves to an array of items)

The `items-provider` prop is no longer needed (but still supported)

As a bonus, this also demonstrates using header/footer scoped slots for placing controls in the header, or custom formatting of label, or any other data).

The `is-busy` prop on `b-table` can be used to place the table in a "busy" looking state (opacity 0.5) which is controlled by CSS on the table (via the CSS selector `table.table[aria-busy="true"]`)

Watching the console you can see the various stages of the provider stages.

**Comment by tmorehouse** [comment]
PR #460 may help address some of this issues original question(s)

**Comment by tmorehouse** [comment]
Latest master now has the new features via PR #460

**Comment by tmorehouse** [comment]
This will be available in release v0.17.0, which is coming soon

**Comment by Diaskhan** [comment]
tmorehouse tnks. 
Boostrap Vue the best and U to ))

**Comment by Nivo-react** [comment]
> [Example.zip](https://github.com/bootstrap-vue/bootstrap-vue/files/1019227/Example.zip) **I did it that way ! I overided watch event ! tmorehouse how do U tnink I'ts Right way? **
> 
> ```
> watch: {
>            currentPage(newPage, oldPage) {
>                this.items = [];
>                var self = this;
>                 axios.get('/question/getquestionspage/', {  params: { id: this.categoryid, page: newPage } })
>                    .then(function (response) {
>                        self.items = response.data.items;
>                        self.count = response.data.count;
>                    });
>                this.$emit('input', newPage);
>            },
>        },
> ```
> 
> But there are some ussue,
> 
> To do serverside pagination We actuaaly must Override "SORT CLICK" But I hadn't really thought about it. Issue could be closed !!





https://stackdev.space/questions/customizing-bootstrapvue-styles-by-overriding-default-bootstrap-styles-encountering-an-error-due-to-undefined-variable
