### ISSUE TITLE
Adding more components

### ISSUE THREAD

**Issue by PierBover** [bootstrap-vue/bootstrap-vue#395]
`bootstrap-vue` lacks certain components such as a date picker which are essential for any application.

Is there an interest by the repo owners to add more components to the repo?

Would linking to other compatible components in the README be a better approach?

**Comment by janat08** [comment]
autocomplete wouldn't be bad either, with typeahead.

**Comment by RyanMulready** [comment]
The lack of date picker is holding me back from doing anything more than testing this library.  Any modern site needs that functionality and although it is possible to use a different vue component the large benefit of this library is consistency.

**Comment by tmorehouse** [comment]
bootstrap-vue is mainly intended to provide the official Bootstrap V4 functionality (datepickers and typeahead are not direct parts of Bootstrap V4), 

But having complementary libraries/components would be of a benefit. I am working on a date picker (no time picker) component that would complement bootstrap-vue, but would be a separate module.

**Comment by tmorehouse** [comment]
See #417 for proposal for handling enhanced/extra components.
