### ISSUE TITLE
Table header not showing using fields element in v2.0.0-rc.28

### ISSUE THREAD

**Issue by sforce-bst-ecu** [bootstrap-vue/bootstrap-vue#3956]
Check the complete example in both table pages:
https://bootstrap-vue.js.org/docs/components/table/#complete-example
https://bootstrap-vue.netlify.com/docs/components/table/#complete-example

`    
    <b-table
      show-empty
      small
      stacked="md"
      :items="items"
      :fields="fields"
      :current-page="currentPage"
      :per-page="perPage"
      :filter="filter"
      :filterIncludedFields="filterOn"
      :sort-by.sync="sortBy"
      :sort-desc.sync="sortDesc"
      :sort-direction="sortDirection"
      @filtered="onFiltered"
    >`

**Comment by sforce-bst-ecu** [comment]
![image](https://user-images.githubusercontent.com/47968523/63840581-e59b4d00-c9b3-11e9-9746-ab3f0c38e68c.png)

**Comment by Hiws** [comment]
This is an issue with using the `stacked` prop in RC28, it is fixed in the next version 2.0.0 which might come out later this week.
