### ISSUE TITLE
<b-toast> events not working except 'show'

### ISSUE THREAD

**Issue by saroshali4** [bootstrap-vue/bootstrap-vue#3958]
### Describe the bug

I want to call an event when the **toast** is **hidden**.
From the docs, only **show** is working.

I'm doing something like this in my component:

`mounted () {
   this.$root.$on('bv::show::toast', () => {
   console.log('Toast is about to be shown')
 })
}`

But if I change the event from **show** to any other mentioned in the document, it doesn't work like:

`mounted () {
   this.$root.$on('bv::hidden::toast', () => {
   console.log('Toast is hidden')
 })
}`

### Expected behavior

As mentioned in the docs other events should work.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- OS: Windows
- Browser: Chrome

**Comment by Hiws** [comment]
The following events are all firing fine for me.
I'd suggest downloading the Vue Dev tools for chrome and looking at the event page there.
That should show all events being fired, including the toast ones.  That's where i found the info underneath

```
this.$root.$on('bv::toast:show', event => { console.log(event) })    
this.$root.$on('bv::toast:shown', event => { console.log(event) })
this.$root.$on('bv::toast:hide', event => { console.log(event) })
this.$root.$on('bv::toast:hidden', event => { console.log(event) })
```

**Comment by saroshali4** [comment]
The Vue Dev tools shows all the events, it's confusing why the syntax is changed from what is showing in the Dev Tools, even If I try the Dev Tools syntax it doesn't work.

![img](https://user-images.githubusercontent.com/21079476/63859910-a3790800-c9c1-11e9-9189-c6ca88e6749c.PNG)

**Case 1:**
`mounted () { this.$root.$on('bv::hidden::toast', () => { console.log('Toast is hidden') }) }`

**Case 2:**
`mounted () { this.$root.$on('bv::toast::hidden', () => { console.log('Toast is hidden') }) }`

**It prints nothing in the console in both cases.**

**Comment by Hiws** [comment]
There's only a single `:` after toast, you have two in `Case 2`

**Comment by saroshali4** [comment]
sorry, my mistake, working now!
