### ISSUE TITLE
`<b-table>`: allow full custom footer via slot

### ISSUE THREAD

**Issue by mysuf** [bootstrap-vue/bootstrap-vue#3960]
Atm, there is no example how to solve custom footer on table with provider func.

I have multiple kinds of results(sums) that I want to place to footer and I dont know how. Basically I want to append multiple custom rows (colspan/rowspan option).

### Describe the solution you'd like

If I understand properly, only foot-clone activates footer and FOOT[whatever] rewrites it. Provider generates sortable header and data in tbody, but footer is untouched. Why not to allow simply b-tfoot also in provider's table (without foot-clone prop)? It resolves all issues around custom footer cells and rows. Now this tag is ignored. b-tfoot should be visible in stacked mode because it lacks header functionality.

### Describe alternatives you've considered

I tried FOOT[] and bottom-row slots so far, but it resolves only one row of footer

### Additional context

Also when stacked="md" (or any breakpoint) is set, newer version (>25) hides header on all resolutions so I am not able to upgrade. Probably a bug?

Thanks

**Comment by tmorehouse** [comment]
For a custom footer (other than the FOOT slots, you can use a bottom-row slot, which you can place TH or TD cells in).

**Comment by tmorehouse** [comment]
Also not sure what you mean by provider generates sortable header?  b-table generates the header, based on the fields in the data.

**Comment by tmorehouse** [comment]
Regarding the stacked header bug, it has been fixed in the dev branch and will be available in the v2.0.0 stable release.

**Comment by mysuf** [comment]
> @tmorehouse: For a custom footer (other than the FOOT slots, you can use a bottom-row slot, which you can place TH or TD cells in).

Quotes from request:

> ... Basically I want to append **multiple custom rows** ..

> I tried FOOT[] and **bottom-row** slots so far, but it **resolves only one row** of footer

> @tmorehouse: Also not sure what you mean by provider generates sortable header? b-table generates the header, based on the fields in the data.

I mean that foot-clone clones header to footer which can be sortable.

**Comment by tmorehouse** [comment]
Have you tries `<b-table-simple>` which lets you build the table as you like?

You can disable sorting on the footer cells via the `no-footer-sorting` prop

**Comment by mysuf** [comment]
I saw simple and lite versions in doc, but I dont think that it fits my needs(unless it works with provider).  I need generated thead/tbody. Only tfoot custom.

**Comment by tmorehouse** [comment]
b-table-simple doesn't do any state/item management (and no providers), but you can basically call your api to generate the table data and use v-for loops to generate the rows.

**Comment by mysuf** [comment]
Ok. There is no paging. Is there way how to make that v-for solution sortable?

**Comment by tmorehouse** [comment]
You would need to implement your own sorting.  You could use the `aria-*` attributes to enable the sorting styles/icons, and place click handlers on the header cells

**Comment by tmorehouse** [comment]
b-table is massively huge because of all the features stuffed into it. we want to avoid making it even larger with new niche needed features.  Which is why we introduced `b-table-lite` and `b-table-simple`

**Comment by mysuf** [comment]
I thought that allowing b-tfoot (which you already supports in b-simple) in b-table wouldnt be huge change.. Thanks anyway. Feel freee to close it.

**Comment by tmorehouse** [comment]
Only one `<tfoot>` element can be placed in a `<table>`

**Comment by mysuf** [comment]
Yea. But I dont have any tfoot when there is no foot-clone. That was the point. Either foot-clone or custom b-tfoot. Choose up to developer.

**Comment by tmorehouse** [comment]
I think what is confusing, is hat you keep mentioning `provider` in your original issue, which (to me) refers to items provider functions. your request doesn't really have anything to do directly with items provider functions then.

**Comment by mysuf** [comment]
Maybe I described it wrong. Sorry for that. Im relatively new to Vue.

**Comment by tmorehouse** [comment]
We possibly could add in the ability to have a `tfoot` slot, which renders the contents of the slot inside a `<b-tfoot>` element (user would be required to provide their own `<b-tr>` and `<b-th>` markup). If the `foot-clone` prop was set, then the `tfoot` slot would be ignored.

It would have to wait until after v2.0.0 is released (just getting ready to release it shortly)
