### ISSUE TITLE
<b-modal>: Set dynamically the exact width

### ISSUE THREAD

**Issue by darkman97i** [bootstrap-vue/bootstrap-vue#3961]
I have been looking in current and closed issues but I have not able to find them.

I'm using a `<b-modal>` to show a thumbnail. The size of the thumbnail changes in terms of width based on the document. After the image loaded I have the exact width of the image and I would like the width of the modal to be exactly the same as the image. 

I load the image from the server with Axios -> then convert to Base64 -> set into the src.

I discovered that into div associated with dialog-class is set dialog-modal what contains **max-width** and **min-width** based in b-modal size ( sm, lg, xl ). I was trying in several way to overwriting these styles without success.

This is my modal definition:
```javascript
<b-modal centered hide-footer hide-header scrollable :ref="modalId" :id="modalId"
             body-bg-variant="white p-0"
             content-class="okm-modal"
             v-model="thumbnailModalVisible">
        <div class="w-100 d-flex justify-content-center align-items-center">
          <img v-show="thumbnailLoaded" ref="thumbnail" src="" @load="loaded"/>
        </div>
    </b-modal>
```

Method used to get the width of the image
```javascript:
loaded() {
        let imageWidth = this.$refs.thumbnail.width;
        let element = this.$refs[this.modalId].$el;
        console.log(element);
      }
```

I have tried something like:
```javascript
v-bind:dialog-class="{maxWidth: '800px'}"
```
And also trying to accessing to element directly, but always when I'm using ref I'm getting undefined element ?
```javascript
// modalId is a property, when I'm doing this.$refs[this.modalId].show() or hide() it works.
let element = this.$refs[this.modalId].$el
```

Is there a way to dynamically to inject a style on fly?

### Versions
**Libraries:**
- BootstrapVue: 2.0.0-rc.27
- Bootstrap: 4.3.1
- Vue: 3.1.*

**Environment:**
- Device: Desktop
- OS: Linux Mint
- Browser: Chrome
- Version: Versión 75.0.3770.100 (Build oficial) (64 bits)

An screenshot what might help:
![Selección_245](https://user-images.githubusercontent.com/958703/63863281-3c058d00-c9ae-11e9-8dbc-3de6c1f5239d.png)

Thanks for your time.

**Comment by jackmu95** [comment]
@darkman97i You need to make sure to apply the `width`/`max-width` styles on the the `modal-dialog` element and not the `modal` element itself.

The `<b-modal>` component has a `dialog` ref defined to access it.
```js
let element = this.$refs[this.modalId].$el
