### ISSUE TITLE
Sort arrow misalignment in th of table

### ISSUE THREAD

**Issue by wrobbinz** [bootstrap-vue/bootstrap-vue#3966]
### Describe the bug

In a sortable table, on a narrow window size, when a column (col A) contains a cell with a long string of text, `<th>`s to the right of col A lose their sort-arrow alignment.

### Steps to reproduce the bug

1. Go to [this CodeSandbox](https://codesandbox.io/s/vue-template-mxipj)
2. Narrow your the view until you notice the sort-arrows jump out of alignment.
![Screen Shot 2019-08-28 at 12 16 25 PM](https://user-images.githubusercontent.com/7999878/63885663-b1149a80-c98d-11e9-9619-0dbdc8b4e322.png)

### Expected behavior

The sort-arrow icons should remain aligned with the text of the `<th>`.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Bootstrap: 4.3.1
- Vue: 2.5.22

**Environment:**

- Device: Macbook Pro
- OS: macOS Mojave
- Browser: Chrome
- Version: 75

### Demo link

https://codesandbox.io/s/vue-template-mxipj

### Additional context

I did find this open issue https://github.com/bootstrap-vue/bootstrap-vue/issues/3696, which is similar but appears to be different. (overlap vs misalignment)

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0 stable has been released. See https://bootstrap-vue.js.org/docs/misc/changelog
