### ISSUE TITLE
SublimeText autocomplete

### ISSUE THREAD

**Issue by joshkpeterson** [bootstrap-vue/bootstrap-vue#3973]
I'm interested in improving tooling support for sublime.

What would be really helpful to me is a **_list of all bootstrap-vue components' tag names_**, eg b-collapse, b-row, etc.

I'll be able to make something for sublime that adds the same autocomplete behavior as is currently available with regular html tags.

I've looked for an easy way to make this list from the bootstrap-vue repo but can't see a quick way.

fyi the link to the tweet here in the docs is broken: 
https://bootstrap-vue.js.org/docs/#vs-code--vetur

**Comment by tmorehouse** [comment]
Re:

> fyi the link to the tweet here in the docs is broken:
> https://bootstrap-vue.js.org/docs/#vs-code--vetur

This has been removed from the latest dev branch docs

**Comment by joshkpeterson** [comment]
For anyone that finds this, I've also just learned that with the sublime package Emmet, if you press ctrl+e then it will autocomplete a tag similar to the default 'tab' behavior'

**Comment by tmorehouse** [comment]
To get a list of all components, one could do:

```js
import * as exports from 'BootstrapVue'

// All components are exported with name `B*****`
// All directives are exported with name `VB*****`
// All plugins will end in the word `****Plugin`
const components = {}
Object.keys(exports).forEach(entry => {
  if (!/Plugin$/.test(entry) && !/^VB/.test(entry)) {
    components[entry] = exports(entry)
  }
})
// The components object will now have a complete list of the
// BootstrapVue components, keyed by PascalCase name
// To get the tag names, you wold need to kebab-case the PascalCase name
```
