### ISSUE TITLE
beforedestroy hook , memory leaks b-table

### ISSUE THREAD

**Issue by jo20172017** [bootstrap-vue/bootstrap-vue#3978]
The b-table remains in the DOM even if i navigate to another router view. I suspect this is due to memory leaks. How can i destroy the Dom/ b-table in the beforeDestroy hook?

**Comment by tmorehouse** [comment]
What version of BootstrapVue, Vue, and vue-router are you using?

**Comment by jo20172017** [comment]
Boostrap-vue "2.0.0-rc.28", vue 2.6.10, vue-router 2.7.0. It is a SPA

**Comment by jo20172017** [comment]
It is a single page app so each page has a unique <b-table>

**Comment by tmorehouse** [comment]
So the the `<table class="table b-table ...">` element appearing in your DOM after a route change? it sounds like your table is not rendered inside your `<router-view>`.

We would need to see some example markup from your app.

**Comment by jo20172017** [comment]
Yes, the <table class="table b-table ..."> element appear in the DOM after a route change. Is there a way we can destroy the table in the beforeDestroy hook?

**Comment by tmorehouse** [comment]
The `<b-table>` component should be destroyed on it's own if it is rendered in side of your `<router-view>` and the route changes.

Please provide some example markup of your app.

**Comment by tmorehouse** [comment]
The BootstrapVue docs site is an SPA, and all of the tables are removed from DOM when switching routes.

**Comment by jo20172017** [comment]
<template>
  <div>
    <b-table striped hover :items="items" :fields="fields" ref="table"></b-table>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        items: [],
        fields: [
          { key: 'name', label: 'Name' },
          { key: 'age', label: 'Age' },
          { key: 'status', label: 'Status' },
          { key: 'id', label: 'Id' }
        ]
      }
    }
  }
methods: { 
      mounted () {
        if (!authenticated) {
          router.push('/home')
        } else{
          vm.getData()
        }
      },
      getData () {
        axios
      .get('api')
      .then(response => (this.item = response))
      }
      beforeDestroy () {
     // can we destroy the DOM from here to prevent memory leaks
    },
    }
</script>

**Comment by tmorehouse** [comment]
You shouldn't need to "destroy the DOM" if your app layout page properly renders the above inside a `<router-view>`.

`<router-view>`, when the route changes, destroys any of the content placed in the `<router-view>` and replaces it with new content.

I think your problem is further up in your app.  Please provide your layout page which uses the above component.

Replace `<b-table>` with jsut a basic element and see if it "remains in the DOM" on a route change:

```html
<template>
  <div>FOO BAR</div>
</template>
```

If you see `FOO BAR` then your app is set up incorrectly, and you should seek help from `vue-router`

**Comment by tmorehouse** [comment]
You should also be using the latest version of Vue Router (3.1.2)

**Comment by tmorehouse** [comment]
Insufficient information provided. Appears to be a user application issue. Closing.
