### ISSUE TITLE
Custom navigation controls for b-carousel

### ISSUE THREAD

**Issue by benitokb4** [bootstrap-vue/bootstrap-vue#3980]
### Describe the bug

We need to be able to implement either the left/right controller individually based on some condition but it seems this functionality has not yet been ported to Vue Bootstrap.

### Expected behavior
Be able to add these elements into the b-carousel to allow custom controls.
```
<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
```

### Versions

**Libraries:**

- BootstrapVue: 2.0.0 RC 27
- Bootstrap: 4.3.1
- Vue: 3.1.1

**Comment by tmorehouse** [comment]
We might be able to implement a scoped slots for the previous and next controls, passing down a method as scoped props that allows you  to call next or previous on click of the element.

Note you can customize the image used for the controls via SASS/SCSS variables:

https://github.com/twbs/bootstrap/blob/269e5351aa3c17775c1846c76e1f87854e115c16/scss/_variables.scss#L1082-L1087

The icons used are SVG images (background image)

The variables are:

- `$carousel-control-icon-width` (to control the width of the icons)
- `$carousel-control-prev-icon-bg` (SVG image or URL to use for the previous icon)
- `$carousel-control-next-icon-bg` (SVG image or URL to use for the nexticon)

**Comment by benitokb4** [comment]
Thanks that would be great. We are currently using scss to override the styles but the problem is that we are trying to hide/show each control individually. We have a workaround so there is no rush.

**Comment by tmorehouse** [comment]
You could create scoped styles (using the [Vue Loader `/deep/` selector](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements) to target the controls, and apply the class to the `<b-carousel>` based on which icon you want to show/hide.

**Comment by tmorehouse** [comment]
The other option, when using the `no-wrap` prop, is for us to disable/hide the previous or next indicator based on which end the carousel stops at.

**Comment by benitokb4** [comment]
Hiding the controls would make sense when using `no-wrap`. I am going to try the with the deep selector quickly. Might be the "safer" option at the moment.

**Comment by benitokb4** [comment]
Worked perfectly. Do you want me to close the feature request?

**Comment by tmorehouse** [comment]
Sure, if it works for you.
