### ISSUE TITLE
bvModal (message in html)

### ISSUE THREAD

**Issue by helioelias** [bootstrap-vue/bootstrap-vue#3982]
I trying write messages in html, but not working, it´s a bug or need a new feature.

**Comment by tmorehouse** [comment]
We do not have an option for direct HTML as the message, but you can easily create enhanced markup with `this.$createElement(..)` and pass the resulting generated vNodes as an array:

https://bootstrap-vue.js.org/docs/components/modal#message-box-notes
> - The Message Box message currently does not support HTML strings, however, you can pass an array of VNodes as the `message` for fine grained control of the markup. You can use Vue's `this.$createElement` method to generate VNodes. This can also be done for the modal title (by passing VNodes to the `title` option), OK button text (via the `okTitle` option), and the CANCEL button text (via the `cancelTitle` option).

For an example of using `$createElement` see teh toast advanced usage https://bootstrap-vue.js.org/docs/components/toast#advanced-usage

**Comment by helioelias** [comment]
Thanks, for your help, works for me
