### ISSUE TITLE
First item in dropdown is selected by default

### ISSUE THREAD

**Issue by paglias** [bootstrap-vue/bootstrap-vue#399]
When you open the dropdown the first item is selected (or focused, I'm not sure) by default.

<img width="382" alt="schermata 2017-05-16 alle 11 43 05" src="https://cloud.githubusercontent.com/assets/589911/26100012/e32630ee-3a2c-11e7-8a94-b53b278d7f8f.png">

This doesn't seem to happen when an header is the first item in the dropdown
<img width="298" alt="schermata 2017-05-16 alle 11 45 00" src="https://cloud.githubusercontent.com/assets/589911/26100071/1b8b2c5a-3a2d-11e7-9df1-c1e8e82a9405.png">

Hovering other elements doesn't remove the active status but clicking and holding the dropdown toggle button does so my guess is that the first element in the dropdown gets incorrectly focused.

The screenshots are taken from the documentation site so I don't think it's necessary to provide a JSFiddle. Let me know if you need more informations

**Comment by paglias** [comment]
Hmm it looks like it could be the expected behavior https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/mixins/dropdown.js#L89 but I have to say I find it a bit confusing. Especially if you have the same css style for the focus and active state of the dropdown item in which case the first element always look the active one

**Comment by tmorehouse** [comment]
The heading is focus able,  to allow screen readers announce it, otherwise the heading is invisible to screen readers and the user may loose context of what the following items relate to.

**Comment by tmorehouse** [comment]
Maybe if we add additional css to the component to style the headers slightly different when focused. Although, this might change based on when bootstrap v4 moves into beta stage from alpha.

**Comment by mosinve** [comment]
maybe to force a focus only if there is a heading?

**Comment by tmorehouse** [comment]
ARIA best practices states that first item in a dropdown menu should be focuses when the menu opens (and that all items should be accessible, otherwise they become invisible).

Imagine a case like this:

![image](https://cloud.githubusercontent.com/assets/2781561/26154105/91638500-3ae4-11e7-99a2-7ff31fb2a43a.png)

If headings were not "visible/readable" by screen reader, then user wouldn't know context of the "Add" and 'delete" menu actions.

**Comment by tmorehouse** [comment]
The blue box around the focused item is the default for focus (which is different then the hover styling provided by bootstrap (and the hover styling is very subtle)

**Comment by mosinve** [comment]
Ok, in case when headings used it's worth to be.
But what will you say about use case with simple dropdown menu without extra headings in it?
this issue just right about this use case. and at this case focusing first item unnecessary IMHO

**Comment by tmorehouse** [comment]
See https://www.w3.org/TR/wai-aria-practices-1.1/#menu

> When a menu opens, or when a menubar receives focus, keyboard focus is placed on the first item. All items are focusable as described in [4.6 Keyboard Navigation Inside Components](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_general_within).

**Comment by pi0** [comment]
Actually the only problem is that blue border is a little annoying as most of sites don't have such behavior. Can't we just hide/light that border?

**Comment by mosinve** [comment]
Maybe... but it's a bootstrap's css. 

I've checked bootstrap behavior: BS4 doesn't support keyboard navigation in dropdown right after opening menu, but only after moving focus to menu by TAB; 
BS3 - supports, and haven't that annoying blue border by default, it seems that it focuses the dropdown menu opener itself.

**Comment by tmorehouse** [comment]
I see in BS4 css they have anything with `[tabindex="-1"]` turn off the focus ring.

Adding this to the CSS will add the blue ring to the header when focused (at least in chrome):
```css
.dropdown-menu .dropdown-header:focus {
    outline: -webkit-focus-ring-color auto 5px !important;
}
```

I suppose we could add in CSS to disable the ring, but then sighted users who use keyboard navigation wouldn't  know which item is selected.

**Comment by tmorehouse** [comment]
Another option, would be to allow the heading to receive focus (like today), but when opening the menu, the first non-disabled menu action item is focused (and the user can keyboard up to read the heading, although visually impaired users wouldn't know the heading was there unless they moved to it).

**Comment by tmorehouse** [comment]
The current menu item focus ring is similar to that used by buttons and links that receive focus.

Try tabbing around this github page and you will see the focus ring move to each actionable link/button/menu.

**Comment by mosinve** [comment]
Yes, but try to open watch dropdown at this page, do you see any blue border?

**Comment by mosinve** [comment]
We have nothing to do with case when headings are used, but there must be some solution to remove annoying border when there is no heading. I don't insist that it must be a code change, but somehow it should be solved :)

**Comment by tmorehouse** [comment]
Github isn't fully AIA compliant with their dropdown menus (they cant be accessed via keyboard up/down), although they are TAB accessible when opened (which is not correct in the ARIA 1.1 standards/practices)

**Comment by tmorehouse** [comment]
In latest BS4 master, you will see they are adding keyboard navigation:
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L315
which the bootstrap-vue menu keyboard navigation code is based on

**Comment by pi0** [comment]
The problem is not with keyboard navigation but always focusing on first item which is somehow abnormal design. I'm not familiar with ARIA standards :)) Is the reason of that auto focus hinting screen reader to read first item?

**Comment by tmorehouse** [comment]
Removing the annoying border would make keyboard navigation for sighted users (but may not be able to use mouse or hands for that matter) greatly impaired when trying to use a dropdown menu.

**Comment by tmorehouse** [comment]
@pi0 the practices say to focus the first item in the dropdown menu (regardless if it is a heading or a menu).

This is very similar to how a `<select>` menu works (see https://bootstrap-vue.github.io/docs/components/form-select and open the select and the first item is focused)

**Comment by mosinve** [comment]
There is one difference between select and dropdown behavior - focus follows mouse cursor

**Comment by mosinve** [comment]
maybe to implement this in dropdown? 
move focus to hovered item

**Comment by tmorehouse** [comment]
Select appears to use same styling for focus and hover.

**Comment by tmorehouse** [comment]
@mosinve that might be a good idea.  Adding a listener for "mouseenter/mouseover" on the menu root element, and then setting focus on that item (if it isn't disabled)

**Comment by tmorehouse** [comment]
We could also emulate the select hover styling (i.e. solid blue background and no outline).  Or we could wait and see that BS4 will be doing with their new CSS.

**Comment by mosinve** [comment]
first variant more universal and doen't depends on BS4 CSS changes. :)

**Comment by tmorehouse** [comment]
Check out PR #408 for hover focusing

**Comment by tmorehouse** [comment]
Now to just deal with how the `dropdown-header` is highlighted/focused.

**Comment by tmorehouse** [comment]
@mosinve when the dropdown opens, should I make it so that the first actionable item is focused (rather than the first item (which could be a heading)? But still leave the heading as reachable via keyboard navigation?

I could also add a scoped style to handle the highlighting of the header item (and change the cursor to a not-permitted/allowed, similar to a disabled item).

**Comment by tmorehouse** [comment]
I'll see about tweaking the `focusFirst` to select the first non-disabled non-header item. (lthough it will have to handle the rare case where all actionable dropdown-items are disabled)

**Comment by alexsasharegan** [comment]
I just want to chime in and second @mosinve on @tmorehouse's ARIA guru-ness! 💯 🎉 💯 🎉 
That's something we all benefit from by just using this lib!

**Comment by tmorehouse** [comment]
You just have to watch out for my typos (my friends call them troy-o's) ;-)
