### ISSUE TITLE
Cannot get imports - returns undefined

### ISSUE THREAD

**Issue by ozergul** [bootstrap-vue/bootstrap-vue#3994]
### Describe the bug

I am not be able to import individual component from bootstrap-vue package.
Throws error: 

`vue.runtime.esm.js?2b0e:5100 Uncaught TypeError: Cannot read property 'install' of undefined
`

### Expected behavior

```
import { DropdownPlugin } from 'bootstrap-vue'
console.log(DropdownPlugin) // undefined
Vue.use(DropdownPlugin)
```

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.22

**Comment by tmorehouse** [comment]
Try using version `2.0.0-rc.27` or `2.0.0-rc.28`

**Comment by ozergul** [comment]
Thanks for reply. Now I am getting this error:

```
./node_modules/bootstrap-vue/es/index.js
Module build failed: Error: EPERM: operation not permitted, open 'C:\Users\ozer\Desktop\projects\epos.web.vue\node_modules\bootstrap-vue\es\index.js'
```

**Comment by tmorehouse** [comment]
Sounds like you might have file permission issues (different user created the files, compared to the user trying to read them).

**Comment by tmorehouse** [comment]
I would suggest clearing your yarn.lock file and installing fresh.

**Comment by ozergul** [comment]
But before 10 min ago there was no probşem with file permissions. I installed the plugin on my computer with same user.

**Comment by tmorehouse** [comment]
Could you review the file permissions and see if they are open for your user?

**Comment by ozergul** [comment]
Deleted node_modules, re-installed all packages. Right now no permission problem.

Tested with `2.0.0-rc.27` and **2.0.0-rc.28**

Gives error again. I cannot use spesific plugin or component.

```
import {BModal, BDropdown, BDropdownItem, BButton, BCarousel, BCarouselSlide, BTable, BPagination} from 'bootstrap-vue'
Vue.component("b-modal", BModal);
Vue.component("b-dropdown", BDropdown);
Vue.component("b-dropdown-item", BDropdownItem);
Vue.component("b-carousel", BCarousel);
Vue.component("b-button", BButton);
Vue.component("b-carousel-slide", BCarouselSlide);
Vue.component("b-table", BTable);
Vue.component("b-pagination", BPagination);
console.log(BModal); // undefined
```

**Comment by tmorehouse** [comment]
Are you possibly using an outdated version of Node.js?

**Comment by ozergul** [comment]
It worked with rc25. I hope you will fix it in new releases :)

**Comment by jackmu95** [comment]
@ozergul The is no problem with 2.0.0-rc.27 and 2.0.0-rc.28.
See: https://codesandbox.io/s/vue-template-zgjbe

**Comment by ozergul** [comment]
It is really interesting but not only me, in our team everybody got this error. But now I see its working. Anyways. We solved at least :) Today I am gonna try with 27 again. Thanks.
