### ISSUE TITLE
b-nav: Is it possible to use it as b-tab (native boostrap example inside)?

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#3999]
### Is your feature request related to a problem? Please describe...
Here is [bootstrap example](https://getbootstrap.com/docs/4.3/components/navs/#javascript-behavior) what I need (different versions of navs which work as tabs).

### Describe the solution you'd like

Is it possible to implement this using b-nav?

If I do something like:
```
<div class="row">
  <div class="col-3">
    <b-nav vertical pills id="v-pills-tab" role="tablist">
      <b-nav-item href="#v-pills-home">home</b-nav-item>
      <b-nav-item href="#v-pills-profile">profile</b-nav-item>
    </b-nav>
  </div>

  <div class="col-9">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">This is HOME</div>
      <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">This is PROFILE</div>
    </div>
  </div>
</div>
```
it does not work.

I know how to make it with `b-tabs` but I need `v-nav` because it has `show` event where I can cancel "tab" change.

**Comment by tmorehouse** [comment]
I would suggest using a `<router-view>` (or `<nuxt-child>`) for the tab content, and using b-navs with `active-class="active"` and the `exact` props set and let Vue router do all the grunt work for you.

**Comment by tmorehouse** [comment]
See the dev docs https://bootstrap-vue.netlify.com/docs/components/nav#card-integration (note the new `card-header` prop will be available in 2.0.0 stable)

**Comment by tmorehouse** [comment]
And see PR #4000 docs at:

https://deploy-preview-4000--bootstrap-vue.netlify.com/docs/components/nav/#using-with-vue-router

**Comment by TitanFighter** [comment]
I understand your idea but vue-router changes url and I do not need such behavior.
What I need is to have tabs which onClick event can check some statement and can cancel onClick (to block tab change) when needed.

In my case I have few profiles (for example one Parent Company -> many Subsidiary companies) shown on the same page. Parent and Subsidiaries have identical structure of menu which looks like tabs with "Profile", "News", "Photo", "Media" buttons.

The top profile (Parent) uses `b-nav` + `vue-router` (so when user clicks "News", it changes URL and renders respective component). The rest profiles (subsidiaries) are shown below the Parent no matter which Profile's tab is selected. In this case subsidiaries can not use vue-router because click on a menu button will change the URL (ie redirect user to a different page). Currently for Subsidiaries I use `b-tabs` and I need to implement a feature that tab change should be prevented in some cases and `b-tabs` does not have such functionality. Then I checked what events `b-nav` has and found `show | bvEvt - BvEvent object. Call bvEvt.preventDefault() to cancel show.` what is exactly what I need and then found code example that native bootstrap can be used as tabs.  I tried to combine `b-nav` and bootstrap's `nav` in order to get access to `b-nav` events, but no luck and this is the reason why I opened feature request.

**Comment by tmorehouse** [comment]
What about using named views `<router-view name="profile-tabs"/>` ? and place your b-tabs component in that.  Have it inspect the `$route` params and disable/hide tabs based on conditions?

Detection of hash change in `b-tabs` would be a pain in the butt.  Vue router doesn't always trigger a route change on hash change, and if users are _not using_ Vue router not all browsers support popstate changes on the URL (to trigger the active tab).
