### ISSUE TITLE
Change scoped field slots name syntax

### ISSUE THREAD

**Issue by mehran-prs** [bootstrap-vue/bootstrap-vue#4001]
Due to new [Dynamic Arguments](https://vuejs.org/v2/guide/syntax.html#Dynamic-Arguments) feature of Vue when we want to define new field slot in table, should add two `\` to field name :
e.g   
```
<template #\[field_name\]="row">Some thing...</template>
```
I think field slots name syntax can be better, something like `__field_name` or `_field_name_`.

**Comment by tmorehouse** [comment]
See https://github.com/bootstrap-vue/bootstrap-vue/pull/3862

**Comment by tmorehouse** [comment]
Note that `\` are not allowed in attribute names.

**Comment by mehran-prs** [comment]
> See #3862

Yes, after seeing this issue, I closed this issue.

**Comment by mehran-prs** [comment]
> Note that `\` are not allowed in attribute names.

You got it wrong, I don't using `\` as attribute name, just  escaping `[ ` & ` ]` in attribute name and Vue allow this.

**Comment by tmorehouse** [comment]
When used in document DOM templates there can be issues with `\`.  But not when using Vue-loader
