### ISSUE TITLE
Field slots ignore "empty" templates

### ISSUE THREAD

**Issue by umbertooo** [bootstrap-vue/bootstrap-vue#4007]
Field slots ignore "empty" templates. The demo has a template for slot "name" that is always empty (`<div v-if="false">...</div>`). This behaviour can be seen in version 2.0.0-rc.27 but is broken in version 2.0.0-rc.28.

### Steps to reproduce the bug
See Codesandbox: https://codesandbox.io/s/vue-template-4qygx

1. Use dependency "bootstrap-vue@2.0.0-rc.27"
2. Browser view shows empty table with header "Name"
3. Change bootstrap-vue version to "2.0.0-rc.28"
4. Browsr view shows table with header and 4 records.

### Expected behavior
Table is expected to be empty as seen on version 2.0.0-rc.27

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Vue: 2.5.22

**Environment:**

Codesandbox

### Demo link
https://codesandbox.io/s/vue-template-4qygx

**Comment by tmorehouse** [comment]
This will be fixed in the 2.0.0 stable release.

See PR https://github.com/bootstrap-vue/bootstrap-vue/pull/3862/commits/a39205940f6ccf777e92c54d680e9ed0008abd77

and https://github.com/bootstrap-vue/bootstrap-vue/pull/3862

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.0 stable has been released. See https://bootstrap-vue.js.org/docs/misc/changelog
