### ISSUE TITLE
<b-table>: Select performance issue

### ISSUE THREAD

**Issue by pibi** [bootstrap-vue/bootstrap-vue#4008]
### Describe the bug

select rows on a large btable introduce a ton of cell re-rendering even for unrelated rows, resulting in poor performance.

### Steps to reproduce the bug

1. Go to https://jsfiddle.net/wk8zd50e/
2. Click on one or more rows
3. See the sloppiness of the select update 

### Expected behavior

I would expect the selected row to be shown instantly, I would expect to see in the vue dev-tools the re-rendering of the affected rows only, not the whole table

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28 (latest)
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- OS: Windows
- Browser: Chrome, Firefox
- Version: latest

**Comment by tmorehouse** [comment]
To improve rendering, use the `primary-key` prop and set it to a field name that has a guaranteed unique value across all rows.

**Comment by pibi** [comment]
Thanks a lot for the quick response, but unfortunately setting the 'primary-key' doesn't help. See the updated fiddle: https://jsfiddle.net/y5uh2fLz/.

Aside, I would expect the primary-key to be important to track changes in the row content, not the row state. I mean, the selected state should not be affected by the data, or am I missing something?

**Comment by tmorehouse** [comment]
Also note that setting `this.this.selected = items` will cause your component to update, and trigger a re-render on itself plug any child components in your component.

**Comment by tmorehouse** [comment]
Also paginating your table, so that, say, only 100 rows of data are visible at a time will help wth performance.

B-table, when any bit of data is updated, still has to run through a for-loop to generate the content. even if it is only a single row that updates.

**Comment by pibi** [comment]
thanks again, I really appreciate your suggestions. I see your point with `this.this.selected = items` , but please note that this element is not part of the table, but an external property. Table should be unaffected by any change on it. 

About pagination: while it could surely help, I wouldn't expect a re-render of the whole table just for a selection on a single row. This is way I'm submitting this bug, I know the table is big, but still Vue is surely capable to handle it as it is handling mostly static data in the current scenario.

**Comment by tmorehouse** [comment]
A lot goes on in behind the scenes when the table rows need to be rendered... looking up slots (if any) for reach row/cell rendered, looking up/calling row/cell attributes/classes, formatter functions, etc. they all each add overhead to the b-table render function

**Comment by pibi** [comment]
Ok, so to improve the performance of the above fiddle we should "cache" the render results and  recompute from bottom to top on a child component change, am I right? (a sort of virtual-bTable to skip the overhead of already computed unchanged data)

**Comment by tmorehouse** [comment]
You would still need a loop to determine what has changed.

**Comment by pibi** [comment]
yeah it seems that in this case the bottleneck is in the render functions themself. this is why I'm wondering how to skip them.

**Comment by tmorehouse** [comment]
You can't skip them is the thing.

**Comment by tmorehouse** [comment]
We might be able to improve performance a small but, by caching the slots names as tehy are found, and caching the reference to the formatter callbacks (if any).

But even though, with 1000 rows displayed, it is always going to take longer to render the virtual DOM, compared to 100 rows.

**Comment by pibi** [comment]
Ok, maybe I'm going thru a dumb path, but let me ask you what would happen if we change [this](https://github.com/bootstrap-vue/bootstrap-vue/blob/332b79fe8511c0f2b8401c34c80abfb0f4138920/src/components/table/helpers/mixin-tbody-row.js#L219) code this way:
```
renderTbodyRow(item, rowIndex) {
     // compute the rowKey 
      const primaryKey = this.primaryKey
      const hasPkValue = primaryKey && !isUndefinedOrNull(item[primaryKey])
      const rowKey = hasPkValue ? toString(item[primaryKey]) : String(rowIndex)
     // just check if the item changed, the simplest way. If yes and it is cached, return the old result
     if ( v-bTable[rowKey] && JSON.stringify(item) === v-bTable[rowKey].item && v-bTable[rowKey].rowIndex === rowIndex) return v-bTable[rowKey].h

     // render the component the old way here .....

      // cache the result
      v-bTable[rowKey] = { h: $rows, item: JSON.stringify(item), rowindex}
      // Return the row(s)
      return $rows
}
```

`v-bTable` is the cache of the previous renders. 
wouldn't this skip the renders of all the unchanged items?

**Comment by tmorehouse** [comment]
You can't re-use vNodes. they need to be generated fresh each time.  This would cuase possible key conflict issues if other data in the table changes (which changes the row's Vue `key`)

**Comment by tmorehouse** [comment]
And it is not just the items that change a rendered row... it could be changes to formatter functions, field definitions, slots that may be `v-if`'ed in our out, and much more more.

**Comment by tmorehouse** [comment]
The JSON stringification comparison would probably add more overhead to the render loop.

**Comment by pibi** [comment]
Ok, thanks a lot for your patience. Seems the only way I could use to improve it is just by avoiding to touch the vue state and add the selected classes directly into the dom: https://jsfiddle.net/0cxytn2s/2/

What about virtual-scroll? Any plan to support it or any way to plug it in?

**Comment by tmorehouse** [comment]
Virtual scroll would be implemented by placing a contentless `div` (wth a 1px height) below the table, and place an ]`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) on it, and when it comes into view (or about to come into view), append more rows to the items array (or change the pagination page size)

Note this will still cause the table to re-render.

**Comment by pibi** [comment]
Yeah, your suggestion is a sort of infinite-loader, right? I was talking about something like this: https://akryum.github.io/vue-virtual-scroller/#/dynamic

**Comment by tmorehouse** [comment]
You could combine that with the new sticky headers... or wrap a table in a vertically scrollable div, in which you set the height to some large value that might be the correct height when all rows are shown (calculating the height is difficult as rows could have cell content that wraps lines)

**Comment by tmorehouse** [comment]
Alternatively you can use the new `<b-table-simple>` to render the table parts you need to render. Note you must provide your own item's handling, sorting, filtering, etc.

**Comment by tjaadvd** [comment]
I am running into this issue as well. It's kind of a bummer realize table selection is slow áfter implementing Bootstrap Vue table selection. Maybe this can be mentioned in the documentation?
