### ISSUE TITLE
b-nav-item-dropdown expand on hover

### ISSUE THREAD

**Issue by Zyles** [bootstrap-vue/bootstrap-vue#4009]
I could not find anything in the docs regarding menus and mouse hover.

I would like to be able to expand a dropdown menu on hover. Like a mega menu.

I used the b-nav-item-dropdown component. Setting the CSS class to "shown" on @mouseover.native seems to not be enough.

Thanks.

**Comment by tmorehouse** [comment]
From the docs: https://bootstrap-vue.js.org/docs/components/dropdown

> They're toggled by clicking (or pressing space or enter when focused), not by [hovering](http://markdotto.com/2012/02/27/bootstrap-explained-dropdowns/); this is an intentional design decision.

Hover menus would have a wide array of accessibility issues.

**Comment by Zyles** [comment]
Right. The usability issue on a desktop is debatable.

However I found the solution, it was `menu-class` I needed, not `class`.

**Comment by tmorehouse** [comment]
Note that by manually placing the `show` class on the menu, the dropdown will not know it is opened, not properly signal/communicate with the dropdown's items, or emit events
