### ISSUE TITLE
how to announce the progress bar percentage.

### ISSUE THREAD

**Issue by jasonlin2316** [bootstrap-vue/bootstrap-vue#4010]
is there any attributes or something I could add for announcing the progress percentage when I use the b-progress tag?

**Comment by tmorehouse** [comment]
I would use the `label` slot, and then render the label in an `aria-live="polite"` attribute on a wrapper `<span>`, assuming you are referring to screen readers announcing the changes in percentage.

**Comment by tmorehouse** [comment]
OR simply adding the attribute `aria-live="polite"` to the outer `<b-progress>` component, and ensure you have `show-progress`  to generate the label (as a percentage).
