### ISSUE TITLE
b-nav b-nav-item active class not applied

### ISSUE THREAD

**Issue by truesilver92** [bootstrap-vue/bootstrap-vue#4012]
### Describe the bug

In 2.0.0-rc.28 clicking on a `b-nav` s `b-nav-item` does not change the active selection visually on the tabs

### Steps to reproduce the bug

1. Create a `b-nav` with at least 2 `b-nav-item`s
2. Make the b-nav `<b-nav tabs justified>`
3. Run
4. Click on the nav tabs/links

### Expected behavior

Adding the `active` class to the `<a>` tag  when navigating to the link and removing the class from the other tags if applicable

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Computer
- OS: Archlinux
- Browser: Chromium
- Version:  75.0.3770.142

**Comment by truesilver92** [comment]
If it is not clear enough what to do to reproduce the problem or what I am trying to explain then I can make a little demo project.

**Comment by tmorehouse** [comment]
The active class is not automatically applied.  You must either set the `active` prop on the nav item to be active (which will place the `active` class), or if using Vue Router, set the `active-class="active"` or `exact-active-class="active"` so that the class `active` is placed on the nav item when the current route matches the `to` prop.

**Comment by tmorehouse** [comment]
By default, when using Vue Router, it uses the Vue router global config properties `linkActiveClass` and `linkExactActiveClass` (which default to `router-link-active` and `router-link-exact-active` classes respectively).

https://bootstrap-vue.js.org/docs/reference/router-links

**Comment by truesilver92** [comment]
It seems that the assumed default in either bootstrap-vue or bootstrap css is that the `active` class is used for styling. If we are moving away from this as the mechanism why not change the css to match?

**Comment by tmorehouse** [comment]
We used to default to `active` class way back, but then people could not use the global router config if they were using a global class or list of classes.  So no way to override globally if we default the active-class or exact-active-class to `active`.  The current method provides the most flexibility while still allowing global vue-router / nuxt.js config settings.

**Comment by truesilver92** [comment]
Thank you for the time and assistance

**Comment by truesilver92** [comment]
I wouldn't say that it was way back. In 2.0.0-rc.11 it worked as I described

**Comment by tmorehouse** [comment]
That is well over a year ago.
