### ISSUE TITLE
<b-table> breaks sort order when adding an object with property of number

### ISSUE THREAD

**Issue by ram231** [bootstrap-vue/bootstrap-vue#4014]
### Describe the bug
Refer to the example
### Steps to reproduce the bug

1. Go to [Bootstrap-table](https://bootstrap-vue.js.org/docs/components/table/#tables)
2. Click on [Sorting table](https://bootstrap-vue.js.org/docs/components/table/#complete-example)

### Expected behavior
I want to sort the name only and not to include number in the table,
I was using b-link to the table to redirect a specific item in that page. the client wants to sort the items by name...

the problem arises when a number is included in the `name` of an object property.
### Versions
BootstrapVue:v2.0.0-rc.28
> Refer to the documentation page

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).
https://codepen.io/ram231/pen/xxKPwJO

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
B-table checks the type of the two values being compared. If they are of type `number` (typeof = 'number'), then it compares the fields by subtracting them.  Similar for Dates. otherwise it compares the values as strings (if htey are not native strings, it stringifies the values first).  In your case, the value, which happens to have a number as part of the stringified value, is compared as strings..

Separate out your "url" number field into a separate column in your table data (it doesn't need to be shown in the table fields).

As for your person first names that are numbers. they are beig compared to strings first names, hence htey will be converted to strings first before comparison.

This is expected when comparing different variable types (numbers vs strings, vs dates, vs objects)

**Comment by ram231** [comment]
Thanks for the reply. This might be problematic for me because I have to use b-link that uses a name and an id(as url for route parameters).

the example above is just an example in the bootstrap-vue documentation. I will try to reproduce a concrete example why I need to have an object inside of a table.

say that I have an object called "name" and an ID to pass down the url link for route parameters in an array.

```vue
<template>
<b-table  ...>
        <template slot="name" slot-scope="data">
          <b-link :to="`/members/${data.value.id}`" id="url-id-link">{{data.value.name}}</b-link>
        </template>
</b-table>
</template>

<script>
export default{
 data(){
      return{
       items:[{
                  users:{
                    id:1234,
         name:"John Doe"
          }, //add some dummy data below
               }
          }]
      }
}
</script>
```
For now, I will separate the id and the name of the table just to sort them correctly. Really appreciate your work.

**Comment by tmorehouse** [comment]
When you use a scoped slot for a field you can dip into **any** of the fields values to generate the presentational value.

The scoped field slot has access to the fields value, the row number, and access to the **entire row's data object**.

With the value and "item" data, you have access to the entire row data in a single scoped field slot.  You can easily grab from one field (via the `item.name`), and from another (`item.url`) to generate what is presented to the user.   If you want the field `name` to sort based on name... create the scoped slot for the `name` field, and then dip into `item.url` (in that same scoped slot name field) to get the data to make the URL wrapper element for the `name` field.;

```html
<!-- value is the field's value, item is the entire row -->
<template slot="name" slot-scope="{ value, item }">
  <a href="#item.id">{{ value.last }}, {{ value.first }}</a>
  <!-- this also produces the same result -->
  <a href="#item.id">{{ item.name.last }}, {{ item.name.first }}</a>
</template>
```
