### ISSUE TITLE
Add install command in an accessible place

### ISSUE THREAD

**Issue by CaddyDz** [bootstrap-vue/bootstrap-vue#4018]
I don't use this package, just stumbled upon an SO question that required me to install it

Would be great if you people had an install command on the readme file or the "Getting Started" section of your site

One shouldn't be expected to guess the package name from the repo name or to go all over and read the `package.json` file to figure it out

**Comment by tmorehouse** [comment]
https://bootstrap-vue.js.org/docs#using-module-bundlers

```bash
# With npm
npm install vue bootstrap-vue bootstrap

# With yarn
yarn add vue bootstrap-vue bootstrap
```

**Comment by CaddyDz** [comment]
Oops my bad! my apologies
Really not visible tho

**Comment by tmorehouse** [comment]
There are multiple ways BootstrapVue can be installed... Module Bundlers, Nuxt, Browser `<script>` tags, Vue CLI 3, etc.   each has there own section.  Not everyone uses a module bundler to build an app.
