### ISSUE TITLE
Documentation is unclear about custom data-binding

### ISSUE THREAD

**Issue by Joebeazelman** [bootstrap-vue/bootstrap-vue#4035]
I've spent the past couple of hours trying to get my head around how to perform custom data binding on the radio group control. I want to bind a list of radio button to an array of objects. Unfortunately, it's unclear how to customize the data binding or wether it is even possible. I've modified the stock example for reference:

https://jsfiddle.net/joelrodgers/5cv3Lbty/21/

As you can see in the options array,  I changed the field name of the `value` to `bob` and set the `value` attribute in the `b-form-radio-group` to `bob` and it doesn't change the default binding. I also tried to change the bindings of a few other fields.

It appears there's no way of changing the data binding mapping. If I have to create an alternate model for the sole purpose of data binding, then this library is useless.

**Comment by tmorehouse** [comment]
See: https://jsfiddle.net/rcmozpsy/

If your options value is **not** in the `value` property of hte options object, then you must provide the name of the field (in the options array) to use as the value via the `value-field` prop.

Also note you cannot use interpolation brackets (`{{ }}`) in the values of Vue props (it was possible in Vue 1.x, but it is not supported in Vue 2.x)

**Comment by Joebeazelman** [comment]
Thanks for the response. The solution makes sense, but the documentation should have at least one example showing this very common use case. I did see the `form-select` but it was unclear how it applies to the `b-form-radio-group`. Understanding it requires delving into the architecture of how the twp interrelate. I still don't grasp how to specify an entire object instance, say `options[0]` as a selected value.

I suggest using at least one example of the options custom binding in `b-form-radio-group` instead of fowarding the innocent developer to another document section for more cognitive punishment. The goal of this library, if I am correct, is to ease integrating bootstrap with VUE.js, but if it requires a significant learning curve to grasp and get working for the most common use case that would be otherwise easily implemented with plain Boostrap, then this library has failed its job.  I've toyed with ng-boostrap and while Angular is way over my head, custom data binding was fairly easy.

**Comment by tmorehouse** [comment]
the `options` processing is a shared module used by `<b-form-select>` , `<b-form-checkbox-group>`, `<b-form-radio-group>` and `<b-form-datalist>`, of which all four work the same way.  Rather than repeating ourselves multiple times in the docs, we link to other sections where the features are identical (especially when users complain that the docs are repetitive, and not to mention making sure all pages are updated when a change in made in the shared functional module).
