### ISSUE TITLE
BTable: scoped field slots no longer working with JSX/TSX

### ISSUE THREAD

**Issue by TheoBP** [bootstrap-vue/bootstrap-vue#4039]
#### Description
I'm using TSX/JSX and this used to work before the 2.0.0 release. I know there have been some breaking changes with the v-slot syntax, but I'm unsure how this translates to JSX. I'm not sure if this is a bug or if I'm just doing something wrong, so apologies in advance if it's the latter.

#### Expected behaviour
The "actions" cell should be rendered

#### Actual behaviour
The "actions" cell isn't rendered

#### Example params
```typescript
const items: [
    {
        id: 1
        name: 'test 1'
    },
    {
        id: 2
        name: 'test 2'
    }
]
const fields = [
    { key: 'name', label: 'Name' }
    { key: 'actions', label: '' }
]
```
#### Example TSX/JSX code
```typescript
<BTable items={this.items} fields={this.fields} scopedSlots={{
    actions: (row: any) => {
        return (
            <BButton to={`/items/${row.item.id}`}>View</BButton>
        )
    }
}} />
```

**Comment by tmorehouse** [comment]
The slot names have changed.  if `actions` is the name of the field you want to render in teh body, you need to now use the name `cell(actions)`:

```jsx
<BTable items={this.items} fields={this.fields} scopedSlots={{
    'cell(actions)': (row: any) => {
        return (
            <BButton to={`/items/${row.item.id}`}>View</BButton>
        )
    }
}} />
```

**Comment by TheoBP** [comment]
@tmorehouse Thank you and sorry for raising an issue for this. I didn't realise `cell(field)` is the actual name of the slot, I thought it is a new syntax for namespacing slots and wasn't sure how it translated to JSX.
