### ISSUE TITLE
b-img Not rendering in table slot

### ISSUE THREAD

**Issue by digitalgym** [bootstrap-vue/bootstrap-vue#4043]
Since v2 was released we're having issue with data table rendering images, the data displayed but the image tag does not render. Reverting to v2.0.0-rc.28 resolves the issue.

```
<template slot="image" slot-scope="data">
<b-img :src="data.value" class="img-fluid" ></b-img>
</template>

**Comment by tmorehouse** [comment]
Note the cell slot names have changed in v2.0.0:

Using the new Vue `v-slot` syntax:

```html
<template v-slot:cell(image)="data">
  <b-img :src="data.value" fluid></b-img>
</template>
```

Or using the old Vue `slot` syntax

```html
<template slot="cell(image)" slot-scope="data">
  <b-img :src="data.value" fluid></b-img>
</template>
```
