### ISSUE TITLE
v-b-tooltop.hover broken in v2.0.0

### ISSUE THREAD

**Issue by thislooksfun** [bootstrap-vue/bootstrap-vue#4044]
### Describe the bug

After updating from v2.0.0-rc.28 to v2.0.0, my tooltips started [bugging out](https://imgur.com/a/arSAi1p).

### Steps to reproduce the bug

1. Clone [this branch](https://github.com/thislooksfun/earthdawn/tree/update-bootstrap-vue) of my app (sorry, this is the best context I have).
2. Run `npm install`
3. Run `npm run electron:serve`
4. Hover over the "New Character" button on the left

### Expected behavior

When hovering, the tooltip should appear and stay there until the element is no longer hovered, not disappear after a fraction of a second.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS 10.14.6 (18G87)
- Browser: Electron (Chromium)
- Version: 6.0.7

### Demo link

I was unable to reproduce this on the Online Playground or in CodePen, but I am able to reliably reproduce it by placing the `v-b-tooltip` directive on any element in my app.

### Additional context

N/A

**Comment by tmorehouse** [comment]
Make sure you are using the latest BootstrapVue CSS files, as there is some custom CSS to make Bootstrap's transition CSS to work with Vue's `<transition>` component.

**Comment by tmorehouse** [comment]
In your repo, I don't see where you are importing Bootstrap's CSS/SCSS nor BootstrapVue's CSS/SCSS

**Comment by thislooksfun** [comment]
Ah, that would explain it. I hadn't been importing them because one of the other plugins I was using was supplying its own theme, which conflicted (theme colors got overwritten). Guess it's time for a theme refactor!

**Comment by tmorehouse** [comment]
If your eternal theme is using SCSS/SASS variables to configure Bootstrap's SCSS, you could import all three into a single SCSS file then import that into your app (or place into the index.html)

**Comment by thislooksfun** [comment]
I wish it were that easy, but the way that theme is currently being integrated into the app is less than ideal and doesn't currently allow me to do that, hence the need for a refactor.

**Comment by tmorehouse** [comment]
If you know the base theme colors values (or names), you could set up the SASS variables to match...

BootstrapVue just needs Bootstrap's variables, functions, and mixins.

**Comment by tmorehouse** [comment]
Depends on how crazy they changed the settings
