### ISSUE TITLE
Module parse failed: Unexpected token 

### ISSUE THREAD

**Issue by ycgambo** [bootstrap-vue/bootstrap-vue#4046]
ERROR in ./node_modules/bootstrap-vue/src/utils/object.js
Module parse failed: Unexpected token (43:32)
You may need an appropriate loader to handle this file type.
|   keys(obj)
|     .filter(key => props.indexOf(key) === -1)
|     .reduce((result, key) => ({ ...result, [key]: obj[key] }), {})
| 
| export const readonlyDescriptor = () => ({ enumerable: true, configurable: false, writable: false })

 @ ./node_modules/bootstrap-vue/src/utils/target.js 1:0-31

**Comment by ycgambo** [comment]
❯ npm -v
6.9.0

❯ node -v
v10.16.3

❯ webpack -v
3.12.0

**Comment by tmorehouse** [comment]
Which version of BootstrapVue and Vue are you using?

**Comment by ycgambo** [comment]
Some package depends on webpack v3, so I'm not upgrading wabpack.

This is how l load this module.

```
// @see: http://element.eleme.io/#/en-US/component/quickstart#import-element
import ElementUI from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';
Vue.use(ElementUI);

// @see: https://github.com/davestewart/vee-element
// @see: https://github.com/davestewart/vee-element/issues/10
// import VeeValidate from 'vee-validate'
// import VeeElement from 'vee-element'
// Vue.use(VeeElement, new VeeValidate.Validator())
```

I'm not very familiar with babel, what should I show you?

Yes, it's caused by the spread syntax.

**Comment by ycgambo** [comment]
If any package is required, why don't put it in the `package.json`?

**Comment by tmorehouse** [comment]
How are you importing BootstrapVue?

**Comment by tmorehouse** [comment]
The BootstrapVue distribution files (`/dist/*` and `/esm/*`) are pre-transpiled via Babel (transpiled for the browser that BootstrapVue supports).  The files in `/src/*` are not.

**Comment by ycgambo** [comment]
```
window.Vue = require('vue');

import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';

// @see: http://element.eleme.io/#/en-US/component/quickstart#import-element
import ElementUI from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';
Vue.use(ElementUI);

// @see: https://bootstrap-vue.js.org/docs/
import BootstrapVue from "bootstrap-vue"
import 'bootstrap-vue/dist/bootstrap-vue.css'
Vue.use(BootstrapVue);
```

**Comment by tmorehouse** [comment]
You should move:

```js
import 'bootstrap-vue/dist/bootstrap-vue.css';
```
to just below the import of Bootstrap's CSS

And

```js
window.Vue = require('vue');
```

Should be:

```js
import Vue from 'vue';
if (typeof window !== 'undefined') {
  window.Vue = Vue;
}
```

Are you using WebPack? or another module bundler such as rollup.js or Parcel?

**Comment by ycgambo** [comment]
I'm not very sure.

when I run `$ webpack`, I got this:

```
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "yarn" to install the CLI via "yarn add -D".
Do you want to install 'webpack-cli' (yes/no): 
```

when I type yes to install, I got this warning:

```
yarn add v1.17.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "bootstrap-vue > portal-vue@2.1.6" has incorrect peer dependency "vue@^2.5.18".
warning " > webpack-cli@3.3.8" has incorrect peer dependency "webpack@4.x.x".
```

**Comment by ycgambo** [comment]
yes, I'm using Webpack v3.3.0 in my project and latest v4.39.3 globally.

I'm not using rollup.js and Parcel.

Can I have spread syntax support in Webpack v3?

**Comment by tmorehouse** [comment]
You shouldn't need object spread support if your app is importing from 'bootstrap-vue' (which defaults to `esm/index.js` for Webpack 4, and `dist/bootstrap-vue.common.js` for Webpack 3).  Both files have been pre-transpiled to work for all browsers IE 11 + modern browsers (spreads have been converted to functions)

The only time you will see an issue is if your module bundler is importing from `src/index.js` (which is written with modern ES6 javascript).

What version of BootstrapVue is listed in your `package.json` `dependencies`?

**Comment by ycgambo** [comment]
I tried BootstrapVue 2.0.0-rc11 and 2.0.0,

I also tried 

      import BootstrapVue from "bootstrap-vue"

and 

      import BootstrapVue from "bootstrap-vue/dist/bootstrap-vue.common.js"

Both throws the same error in `./node_modules/bootstrap-vue/src/utils/object.js`

yes, I can see `dist/bootstrap-vue.common.js` has  been pre-transpiled.

**Comment by tmorehouse** [comment]
I still can't figure out why you see the error on `/node_modules/bootstrap-vue/src/utils/object.js`, as your bundler should not be using the `src/*` directory.

**Comment by ycgambo** [comment]
finally. I find this line in my code:

    import {bindTargets, unbindTargets} from "bootstrap-vue/src/utils/target";

I don't know why I pasted this line. 🙈

Thanks a lot.

**Comment by ycgambo** [comment]
I checked the git log and IDE file history, I'm sure this line came with mistake.
