### ISSUE TITLE
Tabs title render 

### ISSUE THREAD

**Issue by nezzard** [bootstrap-vue/bootstrap-vue#4047]
Hi, is this a bug? when page is loaded, i can catch moment when tabs dont have title, and after one sec they are shown.
Can i render tabs title manually? I'm looked in docs, but nothing found

**Comment by tmorehouse** [comment]
Tab titles are piled from the slots of `b-tab` into `b-tabs` (requires the use of a `$nextTick` to transfer the scoped slot function to the parent `b-tab`).

Could you provide a reduced test case fiddle that reproduces the issue?

**Comment by nezzard** [comment]
@tmorehouse https://jsfiddle.net/6bteL0p9/
You can see, how name of tabs popping when you push run button

**Comment by tmorehouse** [comment]
I'm not seeing the issue on latest desktop chrome.

Perhaps it is a loading time for the scripts? a bit of unstyled/not-yet-updated content which doesn't appear until the scripts have loaded?

**Comment by nezzard** [comment]
@tmorehouse 
here is my local example
http://prntscr.com/p3vpwc
I tried several browsers, in all i have this problem.

Can i render manually header for tabs?

**Comment by tmorehouse** [comment]
B-tabs need to grab the titles from the child components (either from the slot, or the title prop on `<b-tab>`).

Alternative is to use `<b-nav>` card integration: https://bootstrap-vue.js.org/docs/components/nav/#card-integration

**Comment by tmorehouse** [comment]
Are you using SSR to generate the page markup?

**Comment by nezzard** [comment]
@tmorehouse yes

**Comment by tmorehouse** [comment]
Hmmm... and how is the content provided to the child b-tabs? is it dynamically updated during mount?

**Comment by nezzard** [comment]
@tmorehouse for now it's just makeup, but it'll be async returned data

**Comment by tmorehouse** [comment]
If you just create a bare-bones page with just the tabs, do you see the issue?

**Comment by nezzard** [comment]
@tmorehouse yes, it was first, what i checked

**Comment by tmorehouse** [comment]
Strange...  I still can't reproduce the issue from your jsfiddle.

**Comment by nezzard** [comment]
@tmorehouse https://nimb.ws/uQhmrF
i recorded video, i just press run and you can see how names of tab is load

**Comment by nezzard** [comment]
@tmorehouse as i understand https://bootstrap-vue.js.org/docs/components/nav/#card-integration 
i need to implement tab functionality?

**Comment by tmorehouse** [comment]
I see the issue in your video (where it flashes a bit before tab titles are populated).  But still unable to reproduce the issue on latest chrome on both Windows 7 and Windows 10, nor on latest firefox browser.

What OS are you using, and which version of the browser are you using?

**Comment by nezzard** [comment]
Windows 10 
- Chrome 76.0.3809.132 
- Firefox 69.0
- Edge

IOS 12
- Safari
- Chrome
