### ISSUE TITLE
Dropdown item rendering with vue-i18n v-t directive wrong

### ISSUE THREAD

**Issue by wald-tq** [bootstrap-vue/bootstrap-vue#4048]
When using the v-t directive from vue-i18n the dropdown item is not displayed correctly and the click-handler doesn't work.

### Steps to reproduce the bug

1. https://codepen.io/wald-tq/pen/gOYvEBg
2. Click on the dropdown button
3. See the first dropdown item is working, the second dropdown item is not working

### Expected behavior

The dropdown should render correctly with v-t and $t translations

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- OS: Windows 10
- Browser: Chrome

### Demo link

https://codepen.io/wald-tq/pen/gOYvEBg

**Comment by Hiws** [comment]
That's because `v-t` replaces all content of the element with the text, so you wont be able to use it like that.

You can do this instead if you really want to use the directive
```
<b-dropdown-item>
  <span v-t="'hello'"></span>
</b-dropdown-item>
```
