### ISSUE TITLE
Documentation - how to add Spinners to a button during an axios post.

### ISSUE THREAD

**Issue by canvasandcode** [bootstrap-vue/bootstrap-vue#4049]
### Is your feature request related to a problem? Please describe...

I'm having trouble figuring out how to use your Spinner Component in a button only when an axios post is made/ when a method is called.

When I use the markup from the Bootstrap-Vue website:

```
<b-button variant="primary" disabled>
    <b-spinner small type="grow"></b-spinner>
    Loading...
 </b-button>
```

It's not clear in the documentation how to have this show when clicking on Submit on my form.

**Comment by leo95works** [comment]
Hi.. I have the same question.. can u resolve it?

**Comment by tmorehouse** [comment]
```html
<b-button variant="primary" :disabled="someCondition" @click="doSomething">
  <template v-if="someCondition">
    <b-spinner small type="grow"></b-spinner>
    <span>Loading...</span>
  </template>
  <template v-else>
    <span>Do something</span>
  </template>
</b-button>
```
