### ISSUE TITLE
unsightly icon for table sorting

### ISSUE THREAD

**Issue by sprocket99** [bootstrap-vue/bootstrap-vue#4051]
I just upgraded from rc-28 to v2.0, which should have been a small incremental change but broke all my tables because of the new slot syntax. Anyhow, I have fixed all those but I very much dislike the new sorting icon. Why did the old one have to change?

Things like this should not be introduced at the last minute. If a new icon is needed then why not use the one currently used in the combos, which looks much nicer:

![image](https://user-images.githubusercontent.com/52204959/64538900-609a2700-d315-11e9-823d-8640bc5d67bd.png)

Also notice the spacing, its better in the combos, the table header spacing is all messed up, its too close to the edge and the icon is too big. Which looks super ugly when the table itself is in compact mode.

**Comment by tmorehouse** [comment]
The original sorting icons were one of the larger complaints/bugs with tables.  The new Icons can be controlled with SASS variables (width, height, svg), and are closer to the edge (1/2 padding) for better alignment when used on narrow screens.  The difference in look compared to the `select` was intentional to differentiate them from selects.

**Comment by sprocket99** [comment]
What is the correct procedure for using the old icon or a custom icon with bigger spacing?

**Comment by tmorehouse** [comment]
You would need to create an SVG background image (one for each of the three sorting states, plus three duplications bu colored for dark backgrounds) and set the appropriate variables in SCSS

https://github.com/bootstrap-vue/bootstrap-vue/blob/1eda4fe8b13690a12735404924295c8be4800e05/src/_variables.scss#L67-L78

To add more "spacing" to the left/right of the icon image you would need to incorporate that into the view-box of the SVG
