### ISSUE TITLE
<b-media> has wrong vertical align class

### ISSUE THREAD

**Issue by Jexordexan** [bootstrap-vue/bootstrap-vue#4052]
### Describe the bug

The `b-media` components "aside" slot has a default vertical align class of `align-self-top` which does not exist in bootstrap CSS. I believe `align-self-start` is what was meant.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/media#vertical-align
2. It says possible values are `top`, `center` and `end`, with `top` as default.
3. `top` maps to using the `align-self-top` class which has no styles

### Expected behavior

Replace `top` with `start` in docs and code.

### Versions

**Libraries:**

- BootstrapVue: 2.0
- Bootstrap: 4.3
- Vue: 2.6

**Environment:**

N/A

**Comment by tmorehouse** [comment]
Will be fixed in the 2.0.1 release.

In the meantime, you can switch to use `end` and `start` on the `vertical-align` prop

**Comment by Jexordexan** [comment]
Awesome! thanks for the quick fix 👍

**Comment by tmorehouse** [comment]
Will be available in 2.0.1 patch release....
