### ISSUE TITLE
checked prop on b-form-radio does not work correctly

### ISSUE THREAD

**Issue by adamwall** [bootstrap-vue/bootstrap-vue#4054]
### Describe the bug

The `checked` property on `<b-form-radio>` does not check the radio button

### Steps to reproduce the bug

1. Create a `<b-form-radio>` component
2. Set the checked property to `true`

### Expected behavior

The radio button is checked on screen

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version: 76

### Demo link
https://jsfiddle.net/tmc0h715/1/

### Additional context

It works correctly with `b-form-checkbox`

**Comment by tmorehouse** [comment]
`checked` is the v-model property.  As with any input bound to a v-model in Vue, the property (i.e. data) tied to the v-model should be set to the value you want pre-selected.

See https://vuejs.org/v2/guide/forms.html#Basic-Usage

> `v-model` will ignore the initial `value`, `checked` or `selected` attributes found on any form elements. It will always treat the Vue instance data as the source of truth. You should declare the initial value on the JavaScript side, inside the `data` option of your component.
