### ISSUE TITLE
<b-table> not rendering in production [Nuxt.js]

### ISSUE THREAD

**Issue by acrolink** [bootstrap-vue/bootstrap-vue#4058]
I am using `b-table` like this:

`<b-table striped hover :items="entities"></b-table>`

and:

```
  data() {
    return {
      entities: null
    }
  },
  mounted() {
    axios.get('/api/items').then(response => {
      this.entities = response.data.data
    })
  }
```
All works fine and the table gets rendered when running `nuxt` task i.e. development with hot-reloading. However the table is no where to be seen when running for production using `nuxt build` and `nuxt start` (the API backend is called to fetch the data but the table doesn't get rendered at all).

What might be going on here?

**Comment by tmorehouse** [comment]
Could you provide a sample of your `<b-table>` markup?

**Comment by tmorehouse** [comment]
Also, for axios, are you doing any special handling between `dev` mode and `prod` mode?

Also, you should set `items` to an empty array (`[]`) instead of `null` initially

**Comment by acrolink** [comment]
@jackmu95 

Even if I use `asyncData `like this, the table is not rendered in production (despite that the API gets called on the backend):

```
  async asyncData({ params }) {
    let res = await axios.get(`https://my-domain.com/api/items`)
    return { entities: res.data.data }
  }
```

Normal `<li v-for="item in entities">` works but `<b-table>` doesn't.

Here is my `nuxt.config.js` used for production:
```
export default {
  server: {
    socket: '/srv/phx/acrolink/dir/nx/prod.socket'
  },
/*
  generate: {
    routes: function () {
      return [
        '/online-tools'
      ];
    }
  },
  */
  mode: 'universal',
  /*
   ** Headers of the page
   */
  head: {
    title: process.env.npm_package_name || '',
    meta: [{
        charset: 'utf-8'
      },
      {
        name: 'viewport',
        content: 'width=device-width, initial-scale=1'
      },
      {
        hid: 'description',
        name: 'description',
        content: process.env.npm_package_description || ''
      }
    ],
    link: [{
      rel: 'icon',
      type: 'image/x-icon',
      href: '/favicon.ico'
    }]
  },
  /*
   ** Customize the progress-bar color
   */
  loading: {
    color: '#fff'
  },
  /*
   ** Global CSS
   */
  css: [],
  /*
   ** Plugins to load before mounting the App
   */
  plugins: [],
  /*
   ** Nuxt.js dev-modules
   */
  buildModules: [],
  /*
   ** Nuxt.js modules
   */
  modules: [
    // Doc: https://bootstrap-vue.js.org/docs/
    'bootstrap-vue/nuxt',
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    'nuxt-payload-extractor',
    'nuxt-custom-headers',
  ],
  /*
   ** Axios module configuration
   ** See https://axios.nuxtjs.org/options
   */
  axios: {},
  /*
   ** Build configuration
   */
  build: {
    /*
     ** You can extend webpack config here
     */
    extractCSS: true,
    extend(config, ctx) {}
  }
}
```

**Comment by tmorehouse** [comment]
Do you see _any_ table markup in your rendered HTML (i.e. if you look in chrome inspector)?

**Comment by acrolink** [comment]
@tmorehouse 

Yes, this:
`<b-table striped="" hover="" items="[object Object],[object Object],[object Object],[object Object]"></b-table>`

**Comment by tmorehouse** [comment]
Hmmm... since it is rendering an element `<b-table ...>` (an unknown HTML element) it is almost like your production build is not including the BootstrapVue library (and installing the components/plugins properly).

**Comment by acrolink** [comment]
@tmorehouse 
The issue was caused because I used a custom `nuxt.config.js` for production with the name `nuxt.config.prod.js`.
On build I was not using the `-c nuxt.config.prod.js` switch.
I must use it on both tasks `nuxt build` and `nuxt start`

Works as expected.
