### ISSUE TITLE
How to string strings in collapse dynamic rendering?

### ISSUE THREAD

**Issue by caihuattkl** [bootstrap-vue/bootstrap-vue#406]
`<b-btn v-b-toggle.collapse{{index}} variant="primary">Toggle Collapse</b-btn>
<b-collapse id="collapse{{index}}">
<b-card>
Collapse contents Here
</b-card>
</b-collapse>`

**It'll make a mistake. The version is vue2.0**

**Comment by caihuattkl** [comment]
**<b-btn v-b-toggle.collapse{{index}}>Toggle Collapse</b-btn>**

**<b-btn v-b-toggle="collapse{{index}}">Toggle Collapse1</b-btn>**

**Comment by caihuattkl** [comment]
ID cannot spell string

**Comment by caihuattkl** [comment]
@pi0 The question is simple, but can you help me?

**Comment by tmorehouse** [comment]
```html
<template v-for"index in indexes">
  <b-btn :v-b-toggle="'collapse' + index" variant="primary">Toggle Collapse</b-btn>
  <b-collapse :id="'collapse' + index">
    <b-card>Collapse contents Here</b-card>
  </b-collapse>
</template>
```

**Comment by caihuattkl** [comment]
@tmorehouse thank you very much!

**Comment by tmorehouse** [comment]
No problem.
