### ISSUE TITLE
[b-form-select] Uses wrong class

### ISSUE THREAD

**Issue by MrKuzio** [bootstrap-vue/bootstrap-vue#4063]
### Describe the bug

As per Bootstrap documentation the `<select>` element should use the class `form-control`. 
The `b-form-select` component is using the class `custom-select` instead. 

The class `custom-select` should be used ONLY when the `<select>` is used in combination with other buttons, as shown in the "Custom Select" documentation: https://getbootstrap.com/docs/4.3/components/input-group/#custom-select

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/form-select/#form-select
2. Inspect the select component
3. See the classes attached to it

### Expected behavior

The class should be `form-control`, but is instead `custom-select`

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: any
- OS: any
- Browser: any
- Version: any

**Comment by tmorehouse** [comment]
When you want a regular select with `form-control` class, use the `plain` prop to not render the custom select.
