### ISSUE TITLE
Using v-b-tooltip without setting a title shows empty tooltip

### ISSUE THREAD

**Issue by FabianAlbrecht** [bootstrap-vue/bootstrap-vue#4064]
### Describe the bug

If you add a v-b tooltip to an element without setting a title, an empty tooltip is displayed above the element. I think in earlier versions, the tooltip was hidden until the title was set.

Example:
![image](https://user-images.githubusercontent.com/2827227/64593413-56783700-d3ae-11e9-801a-cb31daccfe14.png)

### Steps to reproduce the bug

Create a button with an empty tooltip:
`<b-button v-b-tooltip>Test</b-button>`
or
`<b-button v-b-tooltip="undefined">Test</b-button>`
or
`<b-button v-b-tooltip="null">Test</b-button>`

### Expected behavior

The tooltip is only displayed if a title has been set

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome
- Version: 76

**Comment by tmorehouse** [comment]
This is new expected behaviour.   Tooltips and popovers will show even without content.

v2.0.1 will have the `disabled` property for directive versions (it was missing in the 2.0.0 release).

If you do not want a tooltip to be shown, then you will need to set `disabled` on the tooltip/popover

**Comment by FabianAlbrecht** [comment]
Ok i will try this solution when v2.0.1 is out although I'd like it better if it would show no tooltip instead of an empty one when there is no title. Doesn't make much sense to me to have an empty tooltip here. But probably you can decide that better because of your knowledge of the code.

**Comment by tmorehouse** [comment]
I think we have a solution for the directive versions.

**Comment by tmorehouse** [comment]
A fix will be available in release v2.0.1 coming later this week.
