### ISSUE TITLE
Why isn't the alert in bootstrap-vue a pop-up box? Does it feel like you don't need it?

### ISSUE THREAD

**Issue by caihuattkl** [bootstrap-vue/bootstrap-vue#407]
Why isn't the alert in bootstrap-vue a pop-up box? Does it feel like you don't need it?

**Comment by caihuattkl** [comment]
You can refer to the alert component in VueStrap

**Comment by pi0** [comment]
That's because we reference to standard bootstrap terms not VueStrap,... ;) Alerts are alerts i think that box you are talking about is Modal.

**Comment by caihuattkl** [comment]
But I think VueStrap alert still has reference value;
Don't you think about adding a similar one?

**Comment by tmorehouse** [comment]
This might be better added to a complementary library of add-ons.  

I have been toying with the idea of creating a bootstrap-vue-extras repository for housing special non-native bootstrap add-ons (i.e. date pickets, spinners, modal style alerts, etc).

**Comment by tmorehouse** [comment]
See #417 for proposal for handling enhanced/extra components.
