### ISSUE TITLE
Form File Input Spills over on long file names

### ISSUE THREAD

**Issue by lennycode** [bootstrap-vue/bootstrap-vue#4070]
I deal with log files that have long underscored filenames. The overflow region becomes a hotspot to open the directory browser as well. It is easy to reproduce, just select a long file and/or reduce window width.

![image](https://user-images.githubusercontent.com/845855/64636968-cd262c00-d3d0-11e9-86e2-6f116b55c9d2.png)

**Comment by tmorehouse** [comment]
This is partially a limitation with how Bootstrap designed their CSS and structure for the custom-file input (it will be fixed in Bootstrap v5).

A couple of options:

- Use `class="overflow-hidden"` on the b-form-file component

- Use `class="text-truncate"` on the b-form-file component

**Comment by lennycode** [comment]
Thanks!
`class="text-truncate"`
worked for me.
