### ISSUE TITLE
Html support for message body in msxBoxConfirm and msxBoxOk

### ISSUE THREAD

**Issue by vesper8** [bootstrap-vue/bootstrap-vue#4073]
```
The Message Box message currently does not support HTML strings, however, you can pass an array of VNodes as the message for fine grained control of the markup. You can use Vue's this.$createElement method to generate VNodes. This can also be done for the modal title (by passing VNodes to the title option), OK button text (via the okTitle option), and the CANCEL button text (via the cancelTitle option).
```

In my application I display html which is sent from the server-side in a message box. Currently I use SweetAlert2 which does support html for title/body.

In many cases the html is as simple as adding a few line breaks using `<br>` for confirmation messages that are a little longer. Or adding `<span>` to bold or colourize text.. Very simple html but required nonetheless

Currently msxBoxConfirm and msxBoxOk only supports html for the title but not the body, unless you create VNodes as mentioned above. But in my case since the html is generated on the server-side, there doesn't seem to be an easy way to use VNodes. I've looked for a string-to-vnode converter script but I've yet to find one that works.

This prevents me from switching over from sweetalert2 for the time being. I'm looking for a workaround (such as a string-to-vnode converter in JS).. or simply hoping that this addition might be around the corner? I imagine if you can already support html for the title.. then supporting it for the body can't be that far off?

**Comment by tmorehouse** [comment]
One way you can convert HTML to vNodes is the following:

```js
export default {
  // ...
  methods: {
    htmlToVNode(html) {
      return [
       this.$createElement('div', { domProps: { innerHTML: html } })
      ]
    }
  },
  // ...
}
```

**Comment by vesper8** [comment]
awesome! that works :) thanks!
