### ISSUE TITLE
Console error while using BVTooltips in IE11 - Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by ekilin** [bootstrap-vue/bootstrap-vue#4074]
### Error while using tooltips

In IE11 "document.contains" is not supported. Should be replaced with "document.body.contains". Could you please correct this? 

### Code snippet

In bv-tooltip.js the following code is causing the console error: 

```
    this.$nextTick(() => {
      const target = this.getTarget()
      if (target && document.contains(target)) {
        // Copy the parent's scoped style attribute
        this.scopeId = getScopId(this.$parent)
        // Set up all trigger handlers and listeners
        this.listen()
      } else {
        /* istanbul ignore next */
        warn(`${this.templateType} unable to find target element in document`)
      }
    })
```

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.3.1
- Vue: 2.5.2

**Environment:**

- Browser: IE11

**Comment by tmorehouse** [comment]
Thanks for finding this...  we should have it fixed in v2.0.1 (hopefully coming out later this week)

**Comment by ekilin** [comment]
Thanks a lot!

**Comment by ReneS1991** [comment]
Great to hear a fix will be included soon. We use it in one of our projects for which we have a release next week so would be more than great if v2.0.1 can be released this week 😄

**Comment by ReneS1991** [comment]
All worked in 2.0.1, thanks! 😄 👍

**Comment by jaeming** [comment]
I think this bug must have entered back in at some point. I had to manually polyfill to get tooltips working on IE11:

```
  document.contains = Element.prototype.contains = function contains(node) {
    do {
      if (this === node) return true
    } while ((node = node && node.parentNode))
    return false
  }
```

**Comment by tmorehouse** [comment]
@jaeming are you using the latest version of BootstrapVue (v2.1.0)?  If so, can you create a new issue?
