### ISSUE TITLE
b-popover component and v-b-popover directive fail in a shadow-root

### ISSUE THREAD

**Issue by crouton21** [bootstrap-vue/bootstrap-vue#4085]
I'm trying to use either the b-popover component or the v-b-popover directive in a Vue web component, but I'm seeing the 'warning': 'popover unable to find target element in document.'  I can see that it's failing in src/components/tooltip/helpers/bv-tooltip.js, line 207 (if (target && document.contains(target)) {...}) because the shadow root isn't 'in' the document.  Although even when I alter the if statement to look in the shadow root as well, the popover still doesn't work, so now I'm not sure what I'm missing.

To reproduce:
1. Clone repo: https://github.com/crouton21/bv-test
2. Follow readme
3. Go to localhost:5000
4. See both popovers don't work (one is done with the directive the other is with the component)
In the inspect tab you can see:  (Activity-Stream is the custom web component)
<Activity-Stream>
# shadow-root
<--target elements here-->
</Activity-Stream>

I would expect both popovers to work.

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: [Mac]
- OS: [macOS High Sierra]
- Browser: [Chrome]

Thanks for looking :)

**Comment by israelfloresdga** [comment]
It is possible to create tooltips now? Lion Web Components also works with Popper.js
