### ISSUE TITLE
unchecked-value behavior unclear

### ISSUE THREAD

**Issue by lsmith77** [bootstrap-vue/bootstrap-vue#4089]
### Describe the bug

By default a checkbox is only submitted in the form when its checked and then it sends the given value. I expected the `unchecked-value` setting to then dynamically the value but always send the checkbox as if it as checked.

### Steps to reproduce the bug

```
<b-form-checkbox
    v-else
    switch
    v-model="checked"
    value="1"
    unchecked-value="0"
    name="mycheckbox"
>
    foo
</b-form-checkbox>
```

### Expected behavior

`mycheckbox` is either 0 (unchecked) or 1 (checked) after submission

### Actual behavior

`mycheckbox` is 1 (checked) after submission or not set at all (unchecked)

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Laptop
- OS: Linux
- Browser: Brave
- Version: [e.g. 70]

### Additional context

Add any other context about the bug here.

**Comment by lsmith77** [comment]
BTW I do see that `checked` is being updated with the `unchecked` value.
Does this mean I need to add my own hidden field?

Meaning `unchecked-value` is only useful in the `Vue` scope but it has no effect on the submitted value?

**Comment by lsmith77** [comment]
ie.

```
<input type="hidden" v-model="checked" name="mycheckbox" />
<b-form-checkbox
    switch
    v-model="checked"
    value="1"
    unchecked-value="0"
    name="mycheckbox"
>
    foo
</b-form-checkbox>
```

**Comment by tmorehouse** [comment]
The `unchecked-value` is only applicable to the `v-model` binding.  When using native form submits, if the checkbox is not checked, it will not submit a value.

**Comment by lsmith77** [comment]
so I guess the hidden hack needs to be added manually.
maybe this would be a nice feature request to add?

if not I guess it would be nice to clarify this aspect in the docs.

**Comment by tmorehouse** [comment]
Witb Vue/BootstrapVue, the value can be anything (not just a string, but could be an object, Date, array, etc), which wouldn't submit correctly (it would appear in the native submit a `[ object object ]`, `[ object Array ]`, etc.)

This is the same behaviour as documented by Vue when using a native `<input type="checkbox" v-model="checked" true-value="1" false-value="0">`:

https://vuejs.org/v2/guide/forms.html#Checkbox-1

> The `true-value` and `false-value` attributes don’t affect the input’s `value` attribute, because browsers don’t include unchecked boxes in form submissions. To guarantee that one of two values is submitted in a form (e.g. “yes” or “no”), use radio inputs instead.

**Comment by lsmith77** [comment]
Understood .. I didn't pick a radio because I wanted a single "switch". Might be worth considering offering such a behavior with the automatic hidden field for scalar types.

**Comment by tmorehouse** [comment]
The hidden input could actually affect possible layout (due to how Bootstrap v4 CSS uses sibling selectors for styling), and currently a Vue component cannot return two elements as it's root (Vue v3 will allow this though)

**Comment by tmorehouse** [comment]
An alternative, would be to **not give a `name`** to the single checkbox (so that it doesn't get submitted), and have a hidden input (with the required form `name`) bound to the same `v-model`.  Similar to your workaround above, but minus the `name` on the checkbox.

**Comment by lsmith77** [comment]
thx for your feedback and doc improvement
