### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by BenHayat** [bootstrap-vue/bootstrap-vue#4091]
### Is your feature request related to a problem? Please describe...

Users need to upload images, PDFs and files

### Describe the solution you'd like

I would like to see a File Upload component that matches the style of this framework.

**Comment by tmorehouse** [comment]
The `b-form-file` component supports drag and drop, and native browser file picker.  Note that BootstrapVue doesn't handle the actual upload to a server, as that is left to the developer to choose the methods that work best for them (i.e. Axios, XMLHTTPRequest v2, native form submits, iframe submits, etc), and which work with whatever back end they are using (Node, PHP, .NET, PERL, etc).

**Comment by BenHayat** [comment]
Awesome Troy;
Today is my first time looking at this. Looks real good.

**Comment by vesper8** [comment]
I understand that the file upload is out of scope, however it would be nice to have a very simple example as I'm sure I'm not the only one struggling with figuring that out

**Comment by tmorehouse** [comment]
Here is a simple example for uploading a single file object:

```js
function upload(postUrl, fileObj) {
  var formData = new FormData()
  // 'file' is the "name" of the form input being uploaded
  formData.append('file', fileObj)

  var req = new XMLHttpRequest()
  req.open("POST", postUrl);
  req.onload = function(event) {
    // this is just the status of the upload when it finishes
    alert(event.target.responseText)
  }
  // Send the "Form"
  req.send(formData)
}
```

Something similar can be used to upload multiple files in a single POST request:

```
  fileArray.forEach(fileObj => {
   formData.append('file', fileObj)
  }
```

**Comment by vesper8** [comment]
Thank you, yea I got it to work after a while.. the key was using `const form = new FormData()`. I've never had to do that as this seems only necessary when uploading files, for passing regular text fields to an API it's not necessary

**Comment by tmorehouse** [comment]
yeah... File upload is trickier with AJAX

**Comment by tmorehouse** [comment]
Note I made a slight modification to the above example to include passing the filename as the 3rd argument (to get around an IE11 bug)
