### ISSUE TITLE
Auto-generate web-types during build

### ISSUE THREAD

**Issue by piotrtomiak** [bootstrap-vue/bootstrap-vue#4107]
### Is your feature request related to a problem? Please describe...

JetBrains have developed an open-source format for sharing metadata about web libraries - https://github.com/JetBrains/web-types . It is open and we are working on having a wider IDE support for it (including VSCode). 

### Describe the solution you'd like

Please include a generation of the `web-types` file into your build system to have a better code completion experience of `bootstrap-vue` developers in their IDEs. 

### Additional context

The format has been/is being included into build systems of Vuetify (https://github.com/vuetifyjs/vuetify/pull/7906) and quasar (https://github.com/quasarframework/quasar/pull/4749)

**Comment by tmorehouse** [comment]
There is a published version of BootstrapVue webtypes at:

https://github.com/JetBrains/web-types/tree/master/packages/bootstrap-vue

But it is slightly out of date

**Comment by tmorehouse** [comment]
There would be a few issues with defining directives (specifically the modifiers for directives) using the current schema: https://github.com/JetBrains/web-types/issues/6

**Comment by piotrtomiak** [comment]
@tmorehouse Thanks for looking into this so quickly! I am creating those `webtypes` myself using a generator, but the information is incomplete in some areas, so having `web-types` shipped with the library and generated with all information available during compile-time would be really great improvement. Please note, that not all of the features specified in schema are supported yet in WebStorm (i.e. filters, documentation, etc.).

**Comment by tmorehouse** [comment]
I have a base script that I ma testing this evening to pull in our meta files (each component/directive group has a JSON meta file) for listing the events and slots, while importing the individual component to get access to it's `$options.props` object for the props definition, and then massage and spew it out to a JSON file.

**Comment by piotrtomiak** [comment]
@tmorehouse Sounds great :) I am going offline now, but if you find any difficulties with the format please let me know and I'll try to answer tomorrow.

**Comment by piotrtomiak** [comment]
@tmorehouse Thank you for including `web-types` support!

**Comment by tmorehouse** [comment]
@piotrtomiak it will be available in release v2.1.0 (coming later this week hopefully)

**Comment by piotrtomiak** [comment]
Awesome :)

**Comment by tmorehouse** [comment]
@piotrtomiak BootstrapVue `v2.1.0` has been released, which now includes web-types.json in the dist folder.
