### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Javierjt** [bootstrap-vue/bootstrap-vue#4111]
No me aparece los botones 
![15686981860348408549197770692054](https://user-images.githubusercontent.com/23397478/65013835-ac873600-d8ea-11e9-881a-71c3e69afb0e.jpg)
![15686982115638185854479701127727](https://user-images.githubusercontent.com/23397478/65013852-bb6de880-d8ea-11e9-93f6-364dc58bc84e.jpg)
![15686982463245428234137519388998](https://user-images.githubusercontent.com/23397478/65013879-caed3180-d8ea-11e9-9cd8-237355e07cbe.jpg)

**Comment by Javierjt** [comment]
Todo esta actualizado

**Comment by tmorehouse** [comment]
Si usa BootstrapVue 2.0.x (versión estable), los nombres de las ranuras han cambiado para las celdas de la tabla. https://bootstrap-vue.js.org/docs/misc/changelog#v200

Use el nombre de la ranura `cell(action)`.

**Comment by Javierjt** [comment]
Muchas gracias si me funciono ya no tengo ningún problema
