### ISSUE TITLE
unexpected nav-item-dropdown opening behavior in vertical navbar

### ISSUE THREAD

**Issue by fourcube** [bootstrap-vue/bootstrap-vue#4113]
### Describe the bug

It's not possible to open a nav-bar dropdown with relatively positioned content items, when another nav-bar dropdown, above the targeted dropdown, is already open.

![demo](https://media.giphy.com/media/jPHUr72VFORwb1mrEX/giphy.gif)

### Steps to reproduce the bug

1. Go to https://jsfiddle.net/28dr50bk/
2. Click on "Lang"
3. Try to click on "User"

### Expected behavior

The "User" dropdown opens.

### Versions

**Libraries:**

- BootstrapVue: 2.0.1
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: All devices
- OS: macOS Mojave
- Browser: Firefox 69

### Demo link

https://jsfiddle.net/28dr50bk/

### Additional context

This works as intended in native bootstrap.

**Comment by Hiws** [comment]
Just adding that i tested this in one of the [bootstrap example templates](https://getbootstrap.com/docs/4.3/examples/starter-template/). I simply duplicated the dropdown in the dom to test it and looks to work as intended

![zqCBT8O 1](https://user-images.githubusercontent.com/7057431/65024441-2c39f280-d935-11e9-84b4-5cdcf0d005b2.gif)
](url)

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.3 has been released, which should fix this issue.

**Comment by fourcube** [comment]
@tmorehouse works like a charm! Thank you!
