### ISSUE TITLE
[b-tabs] - Bootstrap typehead autosuggest list is hover, after swipe the list

### ISSUE THREAD

**Issue by jakubstankowski** [bootstrap-vue/bootstrap-vue#4115]
I have problem with suggest list, which is hidden, after when i want swipe suggest list, it's only available in tabs likein code
```
<b-tabs>
 <b-tab title="Autosuggest">
   <vue-bootstrap-typeahead v-model="query" :data="['Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada', 'USA', 'Mexico']" />
 </b-tab>
</b-tabs>
```
 
![Zrzut ekranu (89)](https://user-images.githubusercontent.com/36790120/65026502-f7c83580-d938-11e9-95db-eb6246010735.png)
 ![Zrzut ekranu (90)](https://user-images.githubusercontent.com/36790120/65026510-fac32600-d938-11e9-9327-670b1b7de2d6.png)

 i use this package:
 
 * https://alexurquhart.github.io/vue-bootstrap-typeahead/#/
 
 thanks for answer!

**Comment by tmorehouse** [comment]
I'm not quire sure what your issue exactly is.  could you provide a minimal reproduction via CodeSandBox or CodePen (or possibly JsFiddle)?
