### ISSUE TITLE
[Question]Where can i find the documentation archive for v2.0.0-rc.28?

### ISSUE THREAD

**Issue by THINREDLINE** [bootstrap-vue/bootstrap-vue#4116]
As the title, i'm currently using the v2.0.0-rc.28 version of bootstrap-vue, having trouble trying to implement the table row details for each row but couldn't find the correct example for version v2.0.0-rc.28 since everything just changed to the newest 2.0.0 version.

Can anyone help me by point me to the Doc archive or show me a code snippet how things should work in past version?

Thanks ahead.

**Comment by THINREDLINE** [comment]
So i asked around in discord and someone kindly pointed me a way out by clone/download the past release on github, run the npm commands in the package.json file and finally host the output resource on any hosting site.

But still it will be nice if we can just select the past version of docs from the current official website.

A little bit too much to ask?

**Comment by tmorehouse** [comment]
Currently we don't have a way to have multiple versions of the docs sites online.

We do have a branch snapshot of v2.0.0-rc.28 https://github.com/bootstrap-vue/bootstrap-vue/tree/2.0.0-rc

Which has all the readme markdown files available to view

**Comment by jackmu95** [comment]
Another option is the deploy preview of the last PR merged into v2.0.0-rc.28:
https://deploy-preview-3742--bootstrap-vue.netlify.com/
