### ISSUE TITLE
Bootstrap-vue form validation based on laravel backend: Error message shows but form input still is in valid state. Any ideas?

### ISSUE THREAD

**Issue by Gertjan-Goetynck** [bootstrap-vue/bootstrap-vue#4117]
Hey all!

I am working on a project that requires me to do some backend validation for VAT numbers.

First I use client side Vue Bootstrap form validation to make sure all required fields are filled in. If this succeeds, I make a post request to the database.

When backend VAT validation fails, a json is returned with the error.

When my front end receives the error message, I want to change the VAT input that was previously labeled as succesfully validated, to failed.

To do this, I use the :state prop as mentioned in https://bootstrap-vue.js.org/docs/components/form#validation .

When I do this, the errormessage shows up as expected but the border around the input is still green, as if it was a correct input.

Does anyone have an ideas of what may cause this and how to fix it?

Below you can see a link to images of both the errormessage showing below a green bordered form input (it should be red since it's an error), and a few snippets of relevant code.https://imgur.com/a/TudNTji

Thanks in advance!

**Comment by tmorehouse** [comment]
It sounds like you are mixing browser native validation with javascript logic validation (what Bootstrap v4 calls "Server Validation")

From your images I can't see what tags/attributes you are using on your outer form wrapper.

**Comment by tmorehouse** [comment]
If your inputs are inside a `<form>` (or `<b-form>`), make sure you have the `novalidate` prop set on the form, to prevent the browser from doing native validation, if you are performing all of your validation logic (i.e. required, format of input, etc)

**Comment by MaurizioRicci** [comment]
> If your inputs are inside a `<form>` (or `<b-form>`), make sure you have the `novalidate` prop set on the form, to prevent the browser from doing native validation, if you are performing all of your validation logic (i.e. required, format of input, etc) in code or via the back end.
> 
> If the browser is doing native validation, then the only constraint on the input is `required`, which is satisfied if the input has some value (even if it is not the right format)

I have the same issue, I correctly set the novalidate attribute in my b-form. But when the form receives the validated prop as true then all input (which are not required) turns green even if the input has the state prop set to false. I don't know I am missing.
