### ISSUE TITLE
b-table component slot-scope not working

### ISSUE THREAD

**Issue by narai420** [bootstrap-vue/bootstrap-vue#4121]
When I first install bootstrap-vue with coreui/vue , everything worked fine. But today I created another project with same packages. And without copying the node_modules, I just run npm install. Then all components except, the b-table worked fine. The b-table component's slot and slot-scope didn't work . 
Here is my package.json 
```
{
    "name": "@coreui/coreui-free-vue-admin-template",
    "version": "2.1.3",
    "description": "Open Source Bootstrap Admin Template",
    "author": "Łukasz Holeczek",
    "homepage": "http://coreui.io",
    "copyright": "Copyright 2018 creativeLabs Łukasz Holeczek",
    "license": "MIT",
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "dependencies": {
        "@coreui/coreui": "^2.1.12",
        "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.2.0",
        "@coreui/icons": "0.3.0",
        "@coreui/vue": "^2.1.2",
        "@deveodk/vue-toastr": "^1.0.4",
        "bootstrap": "^4.3.1",
        "bootstrap-vue": "^2.0.0-rc.28",
        "chart.js": "^2.8.0",
        "core-js": "^2.6.5",
        "css-vars-ponyfill": "^1.17.2",
        "flag-icon-css": "^3.3.0",
        "font-awesome": "^4.7.0",
        "moment-locales-webpack-plugin": "^1.1.0",
        "perfect-scrollbar": "^1.4.0",
        "simple-line-icons": "^2.4.1",
        "vue": "^2.6.10",
        "vue-chartjs": "^3.4.2",
        "vue-json-viewer": "^2.1.4",
        "vue-moment": "^4.0.0",
        "vue-multiselect": "^2.1.4",
        "vue-perfect-scrollbar": "^0.1.0",
        "vue-print-nb": "^1.4.0",
        "vue-router": "^3.0.2",
        "vue-select": "^3.1.0",
        "vue-upload-component": "^2.8.20",
        "vue2-animate": "^2.1.0",
        "webpack-dev-server": "^3.8.0"
    },
    "devDependencies": {
        "@vue/cli-plugin-babel": "^3.5.5",
        "@vue/cli-plugin-e2e-nightwatch": "^3.5.1",
        "@vue/cli-plugin-eslint": "^3.5.1",
        "@vue/cli-plugin-unit-jest": "^3.5.3",
        "@vue/cli-service": "^3.5.3",
        "@vue/test-utils": "^1.0.0-beta.29",
        "axios": "^0.18.1",
        "babel-core": "^7.0.0-bridge.0",
        "babel-jest": "^24.7.1",
        "bootstrap": "^4.0.0",
        "browser-sync": "^2.26.7",
        "browser-sync-webpack-plugin": "^2.0.1",
        "cross-env": "^5.1",
        "growl": "^1.10.5",
        "https-proxy-agent": "^2.2.1",
        "jquery": "^3.4.1",
        "laravel-mix": "^4.0.7",
        "lodash": "^4.17.15",
        "node-sass": "^4.11.0",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10",
        "webpack-cli": "^3.3.7"
    },
    "browserslist": [
        "> 1%",
        "last 2 versions",
        "not ie <= 9"
    ],
    "engines": {
        "node": ">= 8.10.x",
        "npm": ">= 5.6.0"
    }
}
```

`<template>
    <div>
        <b-card header="Question Form">
            <b-form>
                <b-row>
                    <b-col md="6">
                        <b-form-group label="Question *">
                            <b-form-input :required="true" placeholder="Question Title / Name"
                                          v-model="Question.name"></b-form-input>
                        </b-form-group>
                        <h5>Options</h5>
                        <b-table striped hover small bordered :items="Question.options" head-variant="dark"
                                 :fields="QFields">
                            <template slot-scope="row" slot="label">
                                <b-form-input placeholder="Option Label" v-model="row.item.label"
                                              :required="true"></b-form-input>
                            </template>
                            <template slot-scope="row" slot="label">
                                <b-form-input placeholder="Option Name" v-model="row.item.name"
                                              :required="true"></b-form-input>
                            </template>
                            <template slot-scope="row" slot="action">
                                <b-button variant="primary"><i class="fa fa-eye"></i></b-button>
                            </template>

                        </b-table>

                    </b-col>
                </b-row>
                <pre v-html="Question"></pre>
            </b-form>
        </b-card>
        <b-card :title="title">
            <template slot="header">
                <b-row>
                    <b-col md="3">
                        <b-form-group label-cols-md="3" label="Perpage : ">
                            <v-select v-model="datatable.per_page"
                                      :options="_.range(settings.app_dt_starts_from,settings.app_dt_limit || 201,settings.app_dt_step || 1)"></v-select>
                        </b-form-group>
                    </b-col>
                    <b-col md="5">
                        <b-form-group>
                            <b-form-input v-model="search" @change="datatable.current_page=1"
                                          placeholder="Type and Hit Enter to Search the table"></b-form-input>
                        </b-form-group>
                    </b-col>
                    <b-col nd="4" class="text-right">
                        <b-button-group>
                            <b-button v-b-modal.addModal variant="primary">Add</b-button>
                        </b-button-group>
                        <b-dropdown text="Columns" right>
                            <b-dd-text style="border:0;padding:0;">
                                <b-list-group>
                                    <b-list-group-item v-for="(field,key) in fields" class="list-group-item"
                                                       :key="key">
                                        <b-form-checkbox v-model="field.visible" :value="true"
                                                         :uncheched-value="false"
                                                         @change="changeVisibility(field,key)"
                                        >
                                            {{_.startCase(field.key)}}
                                        </b-form-checkbox>
                                    </b-list-group-item>
                                </b-list-group>
                            </b-dd-text>
                        </b-dropdown>

                    </b-col>
                </b-row>
            </template>
            <b-table ref="datatable" head-variant="dark" responsive="md" hover bordered small striped :items="getItems"
                     :fields="fields" id="datatable" :filter="search" tableClass="scrollable"
                     :per-page="datatable.per_page" :current-page="datatable.current_page"
            >
                <template slot="photo" slot-scope="row">
                    <b-img style="max-height: 40px;" v-if="row.item.photo" thumbnail rounded
                           :src="row.item.photo.replace('public/','storage/')"></b-img>
                    <b-img v-else
                           v-bind="{blank: true, blankColor: '#777', width: 50, height: 25, class: 'm1' }"
                           rounded alt="Rounded image"></b-img>
                </template>
                <template slot="action" slot-scope="row">
                    <b-button-group size="sm">
                        <b-button variant="primary" @click="currentItem=row.item" v-b-modal.viewModal><i
                            class="fa fa-eye"></i></b-button>
                        <b-button variant="warning" @click="form=JSON.parse(JSON.stringify(row.item))"
                                  v-b-modal.addModal><i
                            class="fa fa-edit"></i></b-button>
                        <b-button variant="danger" @click="trash(row.item.id)"><i class="fa fa-trash"></i></b-button>
                    </b-button-group>
                </template>
            </b-table>
            <template slot="footer">
                <b-row>
                    <b-col>
                        Showing {{datatable.from}} to {{datatable.to}} = {{datatable.data.length}} items of
                        {{datatable.total}} items.
                    </b-col>
                    <b-col>
                        <b-pagination
                            align="right"
                            size="sm"
                            v-model="datatable.current_page"
                            :total-rows="datatable.total"
                            :per-page="datatable.per_page"
                            aria-controls="datatable"
                        ></b-pagination>
                    </b-col>
                </b-row>
            </template>
        </b-card>
        <b-modal id="addModal" title="Add / Edit Supplier" size="lg" header-bg-variant="info">
            <b-form @submit.prevent="onSubmit">
                <b-form-group label-cols-md="4" label="Name *">
                    <b-form-input v-model="form.name" placeholder="Name" required="required"></b-form-input>
                </b-form-group>
                <b-form-group label-cols-md="4" label="Photo">
                    <b-form-file
                        v-model="form.photo"
                        :state="Boolean(form.photo)"
                        placeholder="Choose a file or drop it here..."
                        drop-placeholder="Drop file here..."
                    ></b-form-file>
                </b-form-group>

                <b-form-group label-cols-md="4" label="Company">
                    <b-form-input v-model="form.company" placeholder="Company"></b-form-input>
                </b-form-group>
                <b-form-group label-cols-md="4" label="Phone">
                    <b-form-input v-model="form.phone" placeholder="Phone"></b-form-input>
                </b-form-group>
                <b-form-group label-cols-md="4" label="Email">
                    <b-form-input v-model="form.email" placeholder="Email Address"></b-form-input>
                </b-form-group>
                <b-form-group label="Description">
                    <b-form-textarea v-model="form.description" placeholder="Description"></b-form-textarea>
                </b-form-group>
                <b-button variant="primary" hidden ref="add_form_submit" type="submit">SUBMIT</b-button>

                
                
            </b-form>
            <div slot="modal-footer" class="w-100">
                <b-button-group class="float-right">
                    <b-button variant="primary" @click="$refs.add_form_submit.click()">SUBMIT</b-button>
                    <b-button @click="$bvModal.hide('addModal')">Close</b-button>
                </b-button-group>
            </div>
        </b-modal>
        <b-modal id="viewModal" title="View Supplier" size="lg" header-bg-variant="info" no-body>
            <b-table head-variant="dark" bordered small hover striped
                     :fields="[{key:'key',sortable:true},{key:'value',sortable:true}]"
                     :items="obj2Table(currentItem,[])">
                <template slot="key" slot-scope="row">{{_.startCase(row.item.key)}}</template>
                <template slot="value" slot-scope="row">
                    <div v-if="row.item.key=='photo' && row.item.value">
                        <b-img style="width: 100%" :src="row.item.value.replace('public/','storage/')" fluid></b-img>
                    </div>

                    
                </template>
            </b-table>
        </b-modal>
    </div>
</template>

<script>

    export default {
        name: "SuppliersList",
        data() {
            return {
                settings: window.settings,
                title: 'Suppliers List',
                _: null,
                search: '',
                Question: {
                    name: '',
                    options: [
                        {label: 'A', name: ''},
                        {label: 'B', name: ''},
                        {label: 'C', name: ''},
                        {label: 'D', name: ''},
                    ]
                },
                QFields: [
                    // {key: 'id', sortable: true},
                    {key: 'label', sortable: true},
                    {key: 'name', sortable: true},
                    // {key: 'action', sortable: false, thClass: 'text-right', tdClass: 'text-right'},
                ],

                currentItem: {},
                form: {},
                datatable: {
                    per_page: 10,
                    current_page: 1,
                    data: []
                },
                fields: [
                    {key: 'id', sortable: true},
                    {key: 'photo', sortable: false},
                    {key: 'name', sortable: true},
                    {key: 'company', sortable: true},
                    {key: 'phone', sortable: true},
                    {key: 'email', sortable: true},

                    {key: 'description', sortable: true, visible: false},
                    {key: 'created_at', sortable: true, visible: false},
                    {key: 'updated_at', sortable: true, visible: true},
                    {key: 'action', sortable: false, searchable: false, thClass: 'text-right', tdClass: 'text-right'},
                ]
            }
        },
        created() {
            this._ = window._;
            this.datatable.per_page = window.settings.app_perpage || 10;
            for (let x in this.fields) {
                if (!_.isBoolean(this.fields[x].visible)) {
                    this.$set(this.fields[x], 'visible', true);
                }
                if (_.isBoolean(this.fields[x].visible) && !this.fields[x].visible) {
                    this.$set(this.fields[x], 'thClass', 'd-none');
                    this.$set(this.fields[x], 'tdClass', 'd-none');
                }
            }
        },
        mounted() {
            this.$root.$on('bv::modal::hide', (bvEvent, modalId) => {
                if (modalId === 'addModal') {
                    this.form = {};
                } else if (modalId == 'viewModal') {
                    this.currentItem = {};
                }
            })
        },
        methods: {
            /**
             * @example obj2Table(object, ['column1','column2'])
             * @param row Object of the Data
             * @param skip Array Columns to be skipped / rejected
             * @returns {Array}
             */
            obj2Table(row, skip) {
                skip = skip || [];
                return _.compact(_.map(row, (value, key) => {
                    if (skip.indexOf(key) < 0)
                        return {
                            key: key,
                            value: value,
                        }
                }));
            },
            changeVisibility(field, index) {
                if (!_.isString(this.fields[index].thClass)) {
                    this.fields[index].thClass = '';
                }
                if (!_.isString(this.fields[index].tdClass)) {
                    this.fields[index].tdClass = '';
                }
                if (field.visible) {
                    this.fields[index].thClass += ' d-none';
                    this.fields[index].tdClass += ' d-none';

                } else {
                    this.fields[index].thClass = this.fields[index].thClass.replace('d-none', '').trim();
                    this.fields[index].tdClass = this.fields[index].tdClass.replace('d-none', '').trim();
                }
            },
            onSubmit() {
                let fd = new FormData();
                for (let x in this.form) {
                    fd.append(x, this.form[x]);
                }
                axios.post(routes['admin.SuppliersAdd'], fd, {
                    headers: {
                        'Content-Type': 'multipart/form-data'
                    }
                }).then(res => {
                    console.log(res.data)
                    this.$bvModal.hide('addModal');
                    this.$toastr(res.data.type, res.data.msg, res.data.title);
                    this.$refs.datatable.refresh();
                }).catch(err => {
                    console.log(err.response.data)
                });
            },
            getItems(ctx) {
                //this columns are for query only.
                console.log(ctx)
                let columns = [];
                if (ctx.filter) {
                    for (let x in this.fields) {
                        if (_.isBoolean(this.fields[x].visible) && this.fields[x].visible) {
                            if (!_.isBoolean(this.fields[x].searchable) || this.fields[x].searchable) {
                                columns.push(this.fields[x].key)
                            }
                        }
                    }
                }

                return axios.post(routes['admin.SuppliersList'] + "?page=" + (ctx.currentPage ? ctx.currentPage : 1), {
                    per_page: this.datatable.per_page,
                    orderBy: ctx.sortBy ? ctx.sortBy : 'id',
                    order: ctx.sortDesc ? 'desc' : 'asc',
                    filter: ctx.filter,
                    columns: columns
                }).then(res => {
                    this.datatable = res.data;
                    return res.data.data;
                }).catch(err => {
                    console.log(err.response)
                    return [];
                });
            },
            trash(id) {
                this.$bvModal.msgBoxConfirm('Are you sure?', {
                    title: 'Please Confirm',
                    size: 'sm',
                    buttonSize: 'sm',
                    okVariant: 'danger',
                    okTitle: 'YES',
                    cancelTitle: 'NO',
                    footerClass: 'p-2',
                    hideHeaderClose: false,
                    centered: false,
                    headerBgVariant: 'dark'
                }).then(value => {
                    if (value) {
                        console.log(id)
                        axios.post(routes['admin.SuppliersDelete'], {
                            id: id,
                        }).then(res => {
                            console.log(res)
                            this.$toastr(res.data.type, res.data.msg, res.data.title);
                            this.$refs.datatable.refresh();
                        }).catch(err => {
                            this.$toastr(res.data.type, res.data.msg, res.data.title);
                            console.log(err.response)
                        });
                    }
                }).catch(err => {
                    console.log(err)
                });
            }
        }
    }
</script>

<style lang="scss">
</style>
`

**Comment by tmorehouse** [comment]
Note in v2.0.0-rc.28  the slot names for fields changed, and have changed once again in v2.0.0 stable (for better ompatability with the new `v-slot` syntax.

in rc.28 you need to use the slot names `[fieldName]` (with square brackets), `HEAD[fieldName]` (with square brackets), and `FOOT[fieldName]` (with square brackets).

in v2.0.0 stable, the slot names now use a round bracket syntax: `cell(fieldName)`, `head(fieldName)` and `foot(fieldName)`.

See the change log for details: https://bootstrap-vue.js.org/docs/misc/changelog/
