### ISSUE TITLE
row is visible behind sticky table header

### ISSUE THREAD

**Issue by sprocket99** [bootstrap-vue/bootstrap-vue#4123]
### Describe the bug

When using the sticky header I can see when scrolling part of the background row, and it looks kind of bad.

My table is defined as: 

`<b-table primary-key="id" :fields="fields" :items="nodes" :filter="filter" head-variant="light" sticky-header="77.3vh" show-empty hover bordered>`

![image](https://user-images.githubusercontent.com/52204959/65144612-9cb54200-da0f-11e9-9dac-7538205ecc61.png)

~~Also, setting the height to something like `calc(100vh-100px)` does not work.~~

### Expected behavior

The background row should be completely hidden behind the header. I only found this to be an issue on chrome.

### Versions

**Libraries:**

- BootstrapVue: ^2.0.0-rc.28
- Bootstrap: ^4.3.1
- Vue: ^2.6.10

**Environment:**

- OS: Windows 10
- Browser: Chrome 76.0.3809.132

**Comment by Hiws** [comment]
Add the `no-border-collapse` prop to your table to solve this issue.

**Comment by sprocket99** [comment]
> Apply the `no-border-collapse` prop to your `b-table` to solve this issue.
> 
> https://bootstrap-vue.js.org/docs/components/table#sticky-headers
> From the notes:
> 
> > Bootstrap v4 uses the CSS style border-collapse: collapsed on table elements. This prevents the borders on the sticky header from "sticking" to the header, and hence the borders will scroll when the body scrolls. To get around this issue, set the pop no-border-collapse on the table (note that this may cause double width borders when using features such as bordered, etc).

Yeah sorry I should have mentioned that I tried that and it did not work:

`<b-table primary-key="id" :fields="fields" :items="nodes" :filter="filter" head-variant="light" sticky-header="calc(100vh - 172px)" show-empty hover bordered no-border-collapse>`

Behaves the same in chrome for me.

**Comment by tmorehouse** [comment]
`no-border-collapse` was added in BootstrapVue v2.0.0 stable:  https://bootstrap-vue.js.org/docs/misc/changelog#features-v200

> Features v2.0.0
> ...
> **b-table, b-table-lite, b-table-simple:** add `no-border-collapse` prop and SCSS (#3987) (253b4f6)

For versions prior... you need to add CSS:

```css
.b-table {
  border-collapse: collapsed;
  border-spacing: 0;
}

**Comment by sprocket99** [comment]
`no-border-collapse` does fix the issue on v2.0.1 but it also makes the borders double as thick... taking the `bordered` off is not an option. Any workaround?

**Comment by tmorehouse** [comment]
No easy option then otherwise re-defining how Bootstrap's SCSS/CSS defines the bordering (since it was designed for `border-collapse: collapsed`.

You could make your own class that targets, say, the right edge and bottom edge of table cells only and adds a border of 1px.

**Comment by alexandreDavid** [comment]
Hi, the bug is still there.
Why don't just remove the border top on the header ? It works perfectly

**Comment by tmorehouse** [comment]
That would make an assumption that all people are using the same default styles for the tables. You may need to target the header cell's bottom border, not just the thead. Bootstrap v5 will be making some changes to how styles are applied to tables.

- https://github.com/twbs/bootstrap/issues/28480
- https://github.com/twbs/bootstrap/issues/29244
