### ISSUE TITLE
[Question] Is there a way to programatically scroll a modal to the top?

### ISSUE THREAD

**Issue by vesper8** [bootstrap-vue/bootstrap-vue#4124]
I've tried so many things. I tried setting a ref on the b-modal and then doing `this.$refs.myModal.scrollTop = 0`

I've tried using other vue libraries such as vue-scrollTo

Finally I got it to work by using jQuery: 

```
          this.$nextTick(() => {
            $('.modal-content > .modal-body').scrollTop(0);
          });
```

But I am thinking there must be a better way.. would appreciate a little help with this!

Thanks!

**Comment by tmorehouse** [comment]
It depends on when you want to scroll the modal to the top.

The `$refs` reference won't be immediately available until after the show transition completes (`shown` event).

If you have a reference ($ref) to something inside the modal (say inside the modal content):

```js
// If the "thing" that you have a ref of is a Vue component :
const modalBody = this,$refs.myThing.$el.closest('.modal-body')
// If the "thing" that you have a ref of is an element:
const modalBody = this,$refs.myThing.closest('.modal-body')

modalBody.scrollTop(0)
```

**Comment by vesper8** [comment]
thank you!! that works very nicely

**Comment by vesper8** [comment]
Actually I seem to have spoken too soon

It seemed that it was working yesterday but today I can't get it to work at all. 

If I try to do
```
this.$refs[`modal-${this.id}`].$el.closest('.modal-body').scrollTop = 0;
```

I get `TypeError: _this2.$refs["".concat(...)].$el.closest is not a function"`

And if I console.log `this.$refs[`modal-${this.id}`].$el` I get `<!---->`

My ref is directly on the b-modal like so:

```
  <b-modal
    :id="id"
    :ref="`${id}-modal`"
    v-model="shown"
    :size="modalOptions.size"
    scrollable
    :hide-header="true"
    :hide-footer="true"
    @show="beforeShown"
    @shown="onShown"
    @hide="beforeHidden"
    @hidden="onHidden"
  >
```

And I'm attaching a Bus listener on the @shown event, so the ref should be available by then, in any case it definitely should be available by the time I emit that Bus event which is much later after the modal has been opened for a while. Specifically when I submit a long form that's housed inside the modal.

After a bit of inspection however I noticed that the VueComponent has refs of its own, and this here does work: 

```
this.$refs[`${this.id}-modal`].$refs.body.scrollTop = 0;
```

**Comment by tmorehouse** [comment]
```
this.$refs[`modal-${this.id}`]
```

How are you attaching this ref to the model content?  If it is the modal itself, it will always be a `<!---->` entry (remember the modal is portalled to the body).

You need a ref of something _inside_ your modal (content that you have placed).

**Comment by vesper8** [comment]
Ahh.. right.. well as I mentioned above, I am adding the ref directly on the b-modal element.. so I guess that's why your initial code wasn't working for me

**Comment by tmorehouse** [comment]
You need to get a ref of something inside the modal (i.e. a div, or other element that you have in the modal).
