### ISSUE TITLE
bTable in v2 - How to render dynamic column templates?

### ISSUE THREAD

**Issue by mattgrande** [bootstrap-vue/bootstrap-vue#4125]
Hi there, in v1, I was able to render dynamic columns like this:

```
<template :slot="summaryField.key" slot-scope="data" v-for="(summaryField) in summaryFields">
  <!-- Some complicated rendering logic here -->
</template>
```

I've attempted to migrate to v2, and have updated the slots to this:

```
<template v-slot:cell()="data" v-for="(summaryField) in summaryFields">
  <!-- Some complicated rendering logic here -->
</template>
```

however, it seems that `summaryField`, within the `<template>` is always the last item in the array.

Is there a way to either
a) render one template per array item, or
b) bind something (in this case, `summaryField.key`) into the `v-slot:cell()` statement?

**Comment by tmorehouse** [comment]
You need to use Vue 2.6.x's new [dynamic slot name syntax](https://vuejs.org/v2/guide/components-slots.html#Dynamic-Slot-Names)

```html
<template v-slot:[`cell(${summaryField})`]="data" v-for="summaryField in summaryFields">
  <!-- Some complicated rendering logic here -->
</template>
```

See this answer on StackOverflow https://stackoverflow.com/a/57958889/2744776

**Comment by mattgrande** [comment]
That's perfect, thank you @tmorehouse!
