### ISSUE TITLE
Unexpected behaviour in b-form-select class

### ISSUE THREAD

**Issue by panquela** [bootstrap-vue/bootstrap-vue#4126]
### Describe the bug

b-form-select class has an unexpected behaviour with the default value. It shows the default value as a normal options, not as the default option. I've just copied the example provided in the bootstrap-vue documentation related in the following link:

https://bootstrap-vue.js.org/docs/components/form-select

I've managed to show the default option including the tag <option> as it is shown in the following code

```
<b-form-select v-model="selected" :options="options">
   <option value="undefined">Please select an option</option>
</b-form-select>
```
Please find attached below the link to a sandbox with the code that provokes  the unexpected behaviour explained above.

https://codesandbox.io/s/vue-template-ni9oz

### Expected behavior

I expect to receive the default text assigned with the binding value="null" as the default text. 
I expect to maintain the default text when I include any directive in the b-form-select tag

### Versions

**Libraries:**

- BootstrapVue: 2.0.1
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: any
- OS: any
- Browser: Chrome, Firefox
- Version: Chrome 76.0.3809.132  , Firefox 69.0

### Demo link

https://codesandbox.io/s/vue-template-ni9oz

**Comment by tmorehouse** [comment]
In your sandbox:

```html
<b-form-select v-model="selected" :options="options">
   <option value="undefined">Please select an option</option>
</b-form-select>
```

Value needs to be bound when passing a primitive type:

```html
<b-form-select v-model="selected" :options="options">
   <option :value="undefined">Please select an option</option>
</b-form-select>
```

Also note this adds that option to the last of the list (any options placed in size `<b-form-select>` will appear after any options provided via the `options` prop.

To have that option appear above the options in prop `options` do:
```html
<b-form-select v-model="selected" :options="options">
  <template v-slot:first>
    <option :value="undefined">Please select an option</option>
  </template>
</b-form-select>
```

**Comment by panquela** [comment]
Ok thanks for your support, with your solution it works properly.

Thanks again for your support and kind regards
