### ISSUE TITLE
boundaryPadding not working anymore on Popover

### ISSUE THREAD

**Issue by aguingand** [bootstrap-vue/bootstrap-vue#4131]
### Describe the bug

After 2.0 update, boundaryPadding prop is not taken in account when `<b-popover>` is displayed. Sorry, I don't have time to provide a reproduction.

### Steps to reproduce the bug

N.A.

### Expected behavior

Expect boundaryPadding to work.

### Versions

**Libraries:**

- BootstrapVue: 2.0
- Bootstrap: 4.3
- Vue: 2.6

**Environment:**

- Device: Mac
- OS: Mojave
- Browser: Chrome
- Version: 77

### Demo link

N.A.

**Comment by tmorehouse** [comment]
This should be fixed in the 2.02 release coming out later today.

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.2 has just been released, which includes a fix for this.
