### ISSUE TITLE
b-form-file does not capture event.target.files[0] coming from drag and drop

### ISSUE THREAD

**Issue by rodelpocfemia** [bootstrap-vue/bootstrap-vue#4134]
### Describe the bug

Hi, I have been using b-form-file control before and it was working perfectly both browse and drag and drop. Just recently, when I upload file via drag and drop it does not capture the event.target.files[0]. It was returning null/undefined. When I upload file via browse, it's still working correctly.

Here is the code:
<template>
<b-form-file @change="this.readfile" accept=".xls, .xlsx" v-model="file" :state="Boolean(file)" placeholder="Browse or drag your upload here..."></b-form-file>
</template>
<script>
export default {
    data () {
      return {
         file: null
      }
    },
   methods: {
       readfile(event) {
           console.log(event.target.files[0])
       }
   }
}
</script>

### Expected behavior

The event.target.files[0] should not return null/undefined

### Versions

**Libraries:**

- BootstrapVue: v2.0.1
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Dell laptop
- OS: Windows 10 pro
- Browser: Chrome
- Version: 76.0.3809.132 

### Demo link

I've simulated it in https://bootstrap-vue.js.org/play
Please copy the code below.
<template>
  <div>
    
    <b-form-file
      @change="readFile"
      v-model="file"
      :state="Boolean(file)"
      placeholder="Choose a file or drop it here..."
      drop-placeholder="Drop file here..."
    ></b-form-file>
    <div class="mt-3">Selected file: {{ file ? file.name : '' }}</div>
  </div>
</template>

Javascript:
{
  data() {
    return {
      file: null
    }
  },  
  methods: {
   readFile(e) {
     console.log(e.target.files[0])
   }
  }
}

**Comment by rodelpocfemia** [comment]
I fixed it using event.dataTransfer.files[0] instead of event.target.files[0]

**Comment by MichaelMansourati** [comment]
> I fixed it using event.dataTransfer.files[0] instead of event.target.files[0]

I had the same problem. This fixed it. Thank you @rodelpocfemia!

**Comment by tlyau62** [comment]
for those who are struggling event.dataTransfer.files is empty,
do not trust the chrome debugger,
if you access to event.dataTransfer.files[0],
it will give you the file.

**Comment by raadsaeed445** [comment]
![image](https://user-images.githubusercontent.com/36119288/150947526-73d79cda-472e-4047-a10e-cc894ecee818.jpg)
