### ISSUE TITLE
Add class to b-table row-details

### ISSUE THREAD

**Issue by amokrunner** [bootstrap-vue/bootstrap-vue#4135]
### Is your feature request related to a problem? Please describe...
There appears to be no way to add a class to the row-details scoped slot

### Describe the solution you'd like
I'd like to be able to add a class to the table row-details scoped slot. Possibly like this:
<template v-slot:row-details="row" **v-bind:class="myClass"**>
Maybe this applies to templates in general.

### Describe alternatives you've considered
I've tried the above approach with no success.
Specifically I am trying to add the Bootstrap "Display Property" classes to show/hide the row details under certain screen widths.
I could do this programatically by checking screen width before setting _showDetails=true, but it would be much cleaner to just use classes.

**Comment by tmorehouse** [comment]
It is not possible to pass styles or classes on a `<template>` element with Vue.

There are a couple of ways to do this:

Custom CSS: The details row has class `b-table-details`:

```html
<style>
.my-table tr.b-table-details > td {
  padding: 0
}
</style>
<!-- if using scoped style -->
<style scoped>
.my-table /deep/ tr.b-table-details > td {
  padding: 0
}
</style>

Pass a function to the `tbody-tr-class` prop of `<b-table>` that returns a class when the row type is 'row-details':

```html
<template>
  <b-table ... tbody-tr-class="detailsClassFn">
    <!-- ... -->
  </b-table>
</template>
<script>
export default {
  methods: {
    detailsClassFn(item, rowType) {
      if (rowType === 'row-details') {
        // If it is a row-details row, add the class |my-details-class"
        // to the `<tr>` element
        return "my-details-class"
      }
    }
  }
}
</script>
```

In the latter example using hte function, if your style class is scoped, you will need to use the `/deep/` (or `::v-deep` or `>>>`) Vue-loader deep selector.
