### ISSUE TITLE
b-form-textarea allow resize handle with auto height and plaintext

### ISSUE THREAD

**Issue by WayneHiller** [bootstrap-vue/bootstrap-vue#4138]
In the docs it states: Note that the resize handle of the textarea (if supported by the browser) will automatically be disabled in auto-height mode.

Can it be allowed if plaintext is true?

**Comment by tmorehouse** [comment]
The plaintext styling is controlled by Bootstrap v4's SCSS (remove's the borders and sets the textarea to readonly).

By default the plaintext version does have a resize handle, except if you have rows and max-rows set.

Are you setting the rows and ma-rows props in plaintext mode?

**Comment by WayneHiller** [comment]
Yes I am setting the rows and max-rows, to get auto sizing. I am curious why the resize handle is not shown? Being that it is set to plaintext I use it to show large blocks of text and it would be nice if the user could size the box bigger for better reading if they wanted to. Without the auto sizing I have to pick a default height

**Comment by tmorehouse** [comment]
The resizing is disabled because anything that causes the textarea to be re-rendered (even if the content doesn't change), will trigger the auto-resize calculation and update to occur.  So if the user manually re-sizes the textarea, but something in the parent component triggers it to update (either in the parent component), then the resize the user did manually will get reset, making for a flakey user interface eperience.

**Comment by tmorehouse** [comment]
Your current best bet (for now) is to just use `rows` for now (without `max-rows`) which would allow the user to resize the plaintext textarea, until we can figure out a way to handle this (for plain-text only)

**Comment by WayneHiller** [comment]
Ya that's what I am doing now. Would the possibility of re-rendering be an issue if the no-auto-shrink was set. Might help when the user sizes the box bigger.

**Comment by tmorehouse** [comment]
The `no-shrink` just maintains the max of the current calculated height (based on content) vs the last calculated height.  The actual height of the textarea is not taken into account (just the height of the content inside it)

**Comment by WayneHiller** [comment]
Ah ya that would not work then. In my case it would work perfectly if the box resized when the content changed because I only need the box to resize so the user can read a large block of text, When they move to the next record it would be fine to auto adjust the size again. Might be confusing for you to document how it would work if you just allowed resize with auto height as it is designed today tho.

**Comment by tmorehouse** [comment]
It would be difficult to add that functionality in, requiring additional logic and maintaining state of manual resizing.

I would suggest just adding a class that sets a max-height and min-height, and not using auto-height feature when using plaintext mode

**Comment by WayneHiller** [comment]
min & max heights via a class would probably be the simplest, I will try that.
