### ISSUE TITLE
Reorder columns in table

### ISSUE THREAD

**Issue by D-Marc1** [bootstrap-vue/bootstrap-vue#4140]
### Is your feature request related to a problem? Please describe...

I'd like to be able to reorder columns in tables

### Describe the solution you'd like

Allow ability to reorder columns in tables.

### Describe alternatives you've considered

It doesn't exist in Bootstrap Vue.

**Comment by tmorehouse** [comment]
One can change the order of the columns by altering the order of the fields in the fields array:

As a quick example:

```js
this.fields = this.fields.slice().reverse()
```

Will reverse the order of the displayed columns

**Comment by D-Marc1** [comment]
Hi, thank you for the very fast reply!

What I'm looking for is something similar to Kendo UI Grid, where you can actually [drag and drop the columns](https://www.telerik.com/kendo-vue-ui/components/grid/columns/reordering/).

**Comment by tmorehouse** [comment]
Ah, that is not supported (yet) with `b-table` or `b-table-lite`.

However, you could use vue-dragable on header cells within `b-table-simple`.

**Comment by D-Marc1** [comment]
That's true, shouldn't be too hard to combine it with vue-draggable to achieve this functionality. 

Thanks again for the extremely prompt replies.

**Comment by D-Marc1** [comment]
Sorry, why was this closed? I would actually like for this feature to be added. I think it's a popular enough feature that it would be worth it.

**Comment by 13thbit** [comment]
Would also very much like to see this implemented!

**Comment by puschie286** [comment]
https://codepen.io/zupkode/pen/VgbRdQ

**Comment by Tadeu17** [comment]
I opened a ticket recently with the same question, only now found this.
I'd also really appreciate this being added
