### ISSUE TITLE
How to show toast after redirect using nuxtjs?

### ISSUE THREAD

**Issue by d4rkr3pt0r** [bootstrap-vue/bootstrap-vue#4141]
Hi
I'm using nuxt-js and I wanna show a toast message after redirecting to another page.
Can anyone help me with this?

Thanks

**Comment by tmorehouse** [comment]
Could you provide a sample of how your redirect is performed?  With Vue router, you can pass meta data in the route being redirected to, and on mount of the page that is the target you can check for the existence of that meta date in the $route.

**Comment by tmorehouse** [comment]
Note that toasts being popped up on mount of a page is not overly great for scree nreader users as the toast interrupts the announcement of the page the user has just landed on.

**Comment by d4rkr3pt0r** [comment]
> 
> 
> Could you provide a sample of how your redirect is performed? With Vue router, you can pass meta data in the route being redirected to, and on mount of the page that is the target you can check for the existence of that meta date in the $route.

I'm just using `window.location = "/page"` for now. `redirect(301, `/page`)` is also possible.
I'm sending POST request using axios and after a succefull result I want to redirect to another page and show a succussful message.

**Comment by tmorehouse** [comment]
Showing a toast is easy on page show during the `mount()` hook of the page (or component).  However, you probably still need to pass either some query params, a temp cookie, or similar to let that page know what message to show (and to not show it if someone bookmarks that result page)
