### ISSUE TITLE
B-table Custom Binding Changed in v2

### ISSUE THREAD

**Issue by Arquiel** [bootstrap-vue/bootstrap-vue#4151]
Hello,

Current using v2.0.1... I noticed the format to bind a custom column changed to "v-slot:cell(fieldname)". How do I use this if the cell template is in a v-for? The following does not map the data properly:

Attempt #1:
`<template v-for="field in config.customColumns" v-slot:cell(field.key)="row">`
Attempt #2:
`<template v-for="field in config.customColumns" v-slot:cell([field.key])="row">`

Previously, I was able to do it like this:
`<template v-for="field in config.customColumns" :slot="field.key" slot-scope="row">`

Any suggestions?
Chris

**Comment by tmorehouse** [comment]
Duplicate: #4125
