### ISSUE TITLE
custom directive does not return mask with b-form-input

### ISSUE THREAD

**Issue by aldisseia** [bootstrap-vue/bootstrap-vue#4154]
Does not return the mask, look:
HTML
```
<b-form-input id="birth" type="text" v-model="frmCli.birth" v-maskdate>
            </b-form-input>
```
JS
  ```
data: function () {
    return {
      frmCli: {
        birth: ''
      }
    }
  },
directives: {
    maskdate: {
      update: function (el) {
        const d = el.value
        .replace(/\D+/g, '')
        .replace(/(\d{0,2})(\d{0,2})(\d{0,4})(.*)/, (match, day, month, year) => {
          return [day, month, year].filter(value => value.length).join('/');
        });
      // OK in console.log
       //  console.log(d)
        el.value = d
      }
    }
  }
```

**Comment by tmorehouse** [comment]
Vue can't detect when you directly manipulate the input's DOM property value.  You must trigger a native `input` event on the element after you change the value via `inputElement.value = 'new value'`

**Comment by aldisseia** [comment]
Sorry for the delay, could you give a practical example?

**Comment by tmorehouse** [comment]
It varies on vintage of browser (on how to trigger an event on an element).

But basically, in your directive, after you set `el.value`, you fire an input event on `el` so that the v-model can be updated.

```js
el.value = 'new value'
el.dispatchEvent(new InputEvent())
```

**Comment by tmorehouse** [comment]
You may want to check out how `v-mask` (https://v-mask-demo.netlify.com/) does it in their directive: https://github.com/probil/v-mask/blob/master/src/directive.js

Specifically their `trigger` utility method and `triggerInputUpdate` method.
