### ISSUE TITLE
Directory ../es

### ISSUE THREAD

**Issue by eliasjak** [bootstrap-vue/bootstrap-vue#4158]
I am using vesion 2.0.0-rc.28, when I install version 2.0.2 I have a problem with directory ../es, so I can't compile.
I didn't find anything about this in the docs.
Could you help me?
Best regards

**Comment by tmorehouse** [comment]
Please check the change log: https://bootstrap-vue.js.org/docs/misc/changelog/

The `/es` build has been removed as of v2.0.0 stable, and you should be using the new top-level named import syntax for importing components, directives, and plugins.

The `/es` build was deprecated in v2.0.0-rc.22 (as noted in the changelog https://bootstrap-vue.js.org/docs/misc/changelog#v200-rc22, and re-noted in every release thereafter)

**Comment by eliasjak** [comment]
I've tryed but it returns a warning: "export 'default' (imported as 'BProgress') was not found in 'bootstrap-vue/esm/components/progress/progress'.
So I returned to version 2.0.0-rc.28 and the problem solve.
Could you tell me what is wrong?

**Comment by tmorehouse** [comment]
The new import syntax is:

```js
import { BProgress } from 'bootstrap-vue'
```

**Comment by eliasjak** [comment]
Sorry, It's alright, It was my fault.
Thanks
