### ISSUE TITLE
b-pagination-nav ARIA default value

### ISSUE THREAD

**Issue by kieran-github** [bootstrap-vue/bootstrap-vue#4160]
Hello,

when using the b-component with ARIA attribute label-page it always appends the page number to the string in that attribute as per https://bootstrap-vue.js.org/docs/components/pagination-nav. For example if I wanted screenreader to read the software as Page {pagenumber} selected. It would then generate an aria attribute that the screenreader software would then read as Page {pagenumber} selected pagenumber. Is there anyway to remove the default values so I dynamically use the ARIA labels the v-model?

Thanks.

**Comment by kieran-github** [comment]
This may be a seperate issue, but is there an attribute that allows me to add if the screenreader software has navigated to the pagination button has not selected it? For example if the page 6 button is selected but not yet selected and I can get the screenreader software to say "Page 6, not selected" but when it is selected I can get it to say "Page 6 selected". Any help is greatly appreciated, thanks.

**Comment by tmorehouse** [comment]
Currently no, but the current page button does have the `aria-current` attribute set on it for screen readers.

**Comment by tmorehouse** [comment]
In release v2.1 we will be re-visiting ARIA for pagination-nav (currently it uses teh same ARIA markup as pagination... but needs to be tweaked a bit)
