### ISSUE TITLE
I'm unable to disable slide wrapping on b-carousel

### ISSUE THREAD

**Issue by Anandivdm** [bootstrap-vue/bootstrap-vue#4171]
### Describe the bug

I want to disable carousel slide wrapping by setting the no-wrap boolean to true, but it doesn't seem to work.

### Here is how I set the no-wrap prop on my b-carousel

```
b-carousel(id="carousel-1"
      fade
      controls
      indicators
      no-wrap)

 ```
### Expected behavior

If I set no-wrap to true, the carousel should no longer scroll infinitely but should stop after it's looped through the slides once.

### Versions

**Libraries:**

- BootstrapVue:^2.0.0-rc.27

**Comment by jackmu95** [comment]
@Anandivdm The `no-wrap` prop for `<b-carousel>` was introduced with the v2.0.0 release of BootstrapVue, so make sure to use at least this version.

**Comment by tmorehouse** [comment]
See: https://bootstrap-vue.js.org/docs/misc/changelog#v200
