### ISSUE TITLE
[b-tooltip] Expected HTMLElement, got SVGSVGElement error

### ISSUE THREAD

**Issue by janswist** [bootstrap-vue/bootstrap-vue#4173]
### Describe the bug

`[Vue warn]: Invalid prop: type check failed for prop "target". Expected HTMLElement, got SVGSVGElement`

### Steps to reproduce the bug

```
font-awesome-icon.align-self-center(
  id="copyReflink"
  :icon="copyIcon"
  style="cursor: pointer; color: #42bff4; font-size: 16px"
  @click="copyLinkToClipboard"
)
b-tooltip(target="copyReflink" placement="top" @hidden="reflinkClicked ? reflinkClicked = false : ''") Copy
```

### Expected behavior

Error shouldn't happen. 

### Versions

**Libraries:**

- BootstrapVue: 2.0.2
- Bootstrap: 4.3.1
- Vue: 3.1.1

**Environment:**

- Device: MacBook Pro
- OS: HighSierra
- Browser: Chrome
- Version: 76.0.3809.132

### Additional context

Didn't happen before. I just updated to `vue-cli 3` and got this.

**Comment by jackmu95** [comment]
@tmorehouse Maybe we should make the check more general and check for `Element` which bot `HTMLElement` and `SVGSVGElement` inherit.

**Comment by tmorehouse** [comment]
`Element` might be a bit too generic (as it includes things that wouldn't work with the trigger event listeners).

We can add in SVGElement which would cover this case.

**Comment by janswist** [comment]
You guys are fast! When it will be available in production?

**Comment by tmorehouse** [comment]
In the future ;-)

**Comment by janswist** [comment]
Oh, okay :) FIrst time posting issue so just not sure what happens next to it. Cheers!

**Comment by tmorehouse** [comment]
Should be available in v2.0.3 coming later this week.

**Comment by tmorehouse** [comment]
Note when applying tooltips/popovers to non-interactive elements, make sure you add `tabindex="0"` attribute so that keyboard-only users and screen reader users can access the element (and the tooltip/popover)

**Comment by janswist** [comment]
Good catch! Will do that - thank you

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.3 has been released
