### ISSUE TITLE
[BootstrapVue warn]: config: unknown config property "BToast.solid"

### ISSUE THREAD

**Issue by dflock** [bootstrap-vue/bootstrap-vue#4175]
### Describe the bug

Despite the changes in #3170, when I try to set a default for "BToast.solid", I get a warning in the browser console:

![image](https://user-images.githubusercontent.com/47756/65928030-23273780-e3b1-11e9-8ab5-d557c2137592.png)

### Steps to reproduce the bug

```js
Vue.use(BootstrapVue, {
  BToast: {
    solid: true
  }
})
```

### Expected behavior

I would like this to set the default, without any warnings in the console.

### Versions

**Libraries:**

- BootstrapVue: 2.0.2
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Comment by tmorehouse** [comment]
`solid` is not a prop that can be set in the config. We don't allow Boolean props in the config... as it changes their meaning when users actually try to use the props.

Only string props and numerical props are in the config.

The error you are seeing is expected. #3170 did not add in the solid prop to the config. Only props that appear in https://bootstrap-vue.js.org/docs/misc/settings/ are allowed/configurable.

**Comment by tmorehouse** [comment]
You can, however, use  SASS variables to control teh default toast background color, or which BootstrapVue pulls the Alpha channel value from:

```scss
$toast-background-color: rgba($white, .85) !default;
```

And override it:

```scss
$toast-background-color: rgba($white, 1);
```

See https://bootstrap-vue.js.org/docs/reference/theming/
