### ISSUE TITLE
Question: Replace upper-right bootstrap-modal close button globally.

### ISSUE THREAD

**Issue by pascbeck** [bootstrap-vue/bootstrap-vue#4177]
Hey everyone, is there a way to replace that upper-right close button globally? (See attachment)

![upper-right-close](https://user-images.githubusercontent.com/55634271/65963072-4c4fd280-e45a-11e9-944d-c678c7d2495d.png)

**Comment by tmorehouse** [comment]
Currently, no.

But you can make a wrapper component that wraps b-modal, and replaces the header contents.

**Comment by pascbeck** [comment]
Thanks for the fast response, are there any future plans for that?

**Comment by pascbeck** [comment]
Might not be the best solution but it works.

```
  button {
    &.close {
      color: transparent !important;
      &:after {
        content: '\0058';
        font-family: 'Our Icon Font';
        border-radius: 50%;
        font-size: 13px;
        padding: 10px 11px;
        margin-right: 10px;
        background-color: #d8d9d9;
        color: #313336 !important;
      }
    }
  }
```

<img width="443" alt="upper-right" src="https://user-images.githubusercontent.com/55634271/65972435-1f0b2080-e46a-11e9-8771-5621889533dc.PNG">

**Comment by scottadamsmith** [comment]
@pascbeck Worth noting that while this works for most cases, making the content within the button transparent won't hide it from a screen reader. Unless perhaps the presence of the aria-label on the button element will supersede the content within the button, making this approach acceptable for screen readers as well?

**Comment by pascbeck** [comment]
@scottadamsmith 

> Edit: I found what appears to be pretty good evidence that the updated versions of most screen will announce the aria-label and ignore the content within. So perhaps this is safer than I thought. One thought I had would be that it would be nice to be able to provide a custom class that gets applied to all close buttons (similarly to what some other components in this library support), so that we can use this approach with a bit more specific selector than "button.close".


```
.modal-header button {
  &.close {...}
}
```

This will scope the selector to the modal-header and make it more specific.
