### ISSUE TITLE
Tooltip not respecting triggers

### ISSUE THREAD

**Issue by limeandcoconut** [bootstrap-vue/bootstrap-vue#4179]
### Describe the bug

It appears to me that the problem is with tooltip acting as though `triggers="hover click"` is set even when `triggers="hover"` is the only one set. 

I'm seeing this error specifically when using a modal inside a tooltip. 

### Steps to reproduce the bug

1. Make a modal a child of a tooptip's target and use only `triggers="hover"`
2. Hover the target (should see the tooltip)
3. Click the target (modal opens and tooltip disappears)
4. Click the X to hide the modal. (modal closes and tooltip re-shows)
5. Tooltip remains active (erroneously) even when not hovered. 
6. Fix bug.
7. Profit!

### Expected behavior

The tooltip should only show on hover, not click. The tooltip should not be shown when closing the modal.

### Versions

**Libraries:**

"bootstrap-vue": "^2.0.2", (also 2.0.0-rc.19)
"vue": "^2.6.10",

**Environment:**

- Device: Macbook pro, various windows devices
- OS: macOS 10.14.6 and others
- Browser: Chrome, FF
- Version: Various (long standing bug)

**Comment by tmorehouse** [comment]
Are you using the directive version or component version of tooltip?

https://jsfiddle.net/xd0v3ug1/

**Comment by tmorehouse** [comment]
@limeandcoconut could you create a JSFiddle or CodeSandbox recreating the issue?

You can export a sample to JSFiddle/CodePen/CodeSandbox via the docs playground: https://bootstrap-vue.js.org/play

**Comment by tmorehouse** [comment]
Unable to reproduce this issue.
