### ISSUE TITLE
Table become empty when upgrade to version newer than 2.0.0-rc

### ISSUE THREAD

**Issue by ColinTree** [bootstrap-vue/bootstrap-vue#4180]
### Describe the bug

My project used to use version bootstrap-vue@2.0.0-rc.24, and it works fine like this:
![image](https://user-images.githubusercontent.com/22613139/66023995-154eef00-e536-11e9-992b-1cadddc3ebd3.png)

But since I upgraded bootstrap-vue to newer version like 2.0.1, it become:
![image](https://user-images.githubusercontent.com/22613139/66023849-b7baa280-e535-11e9-873d-7a57de67cf1d.png)

**And I'm sure that this version upgrade is the reason of this change**

### Demo link

https://github.com/ColinTree/tinywebdb-php-vue/blob/03b200bf0bb585987582b8fd6cad7497e3e35975/frontend/tinywebdb-php-vue/src/components/manage/functional/DataTable.vue#L14

**Comment by ColinTree** [comment]
This may not be a bug, but a usage mistake by my code. Please just point it out if anybody found it.

**Comment by Hiws** [comment]
The slot naming [changed for version 2.0.0](https://bootstrap-vue.js.org/docs/misc/changelog#v200) for custom slots in the table.
Right now you probably have something like
```
<b-table>
  <template slot="active" slot-scope="data">
    // some custom markup
  </template>
<b-table>
```

In 2.0.0 that should be changed to
```
<b-table>
  <template slot="cell(active)" slot-scope="data">
    // some custom markup
  </template>
  /* or the prefered new v-slot syntax */
  <template v-slot:cell(active)="data">
    // some custom markup
  </template>
<b-table>
```

**Comment by ColinTree** [comment]
Thank you very much @Hiws
