### ISSUE TITLE
Drag and dropped files with b-form-file do not submit file data

### ISSUE THREAD

**Issue by deweller** [bootstrap-vue/bootstrap-vue#4182]
### Describe the bug

Drag and dropped files with b-form-file do not submit the file data to the browser.

### Steps to reproduce the bug

1. Use the following form:
```
<form method="POST" action="http://mysite.com/upload" accept-charset="UTF-8" enctype="multipart/form-data">
    <div class="form-group">
        <b-form-file name="import_file" accept=".csv,.txt"></b-form-file>
    </div>
    <div>
        <button type="submit" class="btn">
            Upload
        </button>
    </div>
</form>
```
2. Drag a file onto the file upload component
3. Submit the form

### Expected behavior

I expect the browser to submit the file data.  Instead, the file is blank.

![image](https://user-images.githubusercontent.com/51414/66044519-55d34c00-e4e7-11e9-8e1c-fbe2b1bce379.png)

Note that if I browse the file instead of using drag and drop, this works as expected and the browser does upload the file contents.

### Versions

**Libraries:**

- BootstrapVue: 2.0.2
- Bootstrap: 4.1.0
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome
- Version: 77.0.3865.90

**Comment by tmorehouse** [comment]
This is expected, as browser's do not allow javascript to set the selected files on a file input.

You would need to trap the submit event on your form, and process the array of files from the v-model into a format you back end can handle.

**Comment by deweller** [comment]
Got it.  Thanks for the info.
