### ISSUE TITLE
Using PascalCase for component names

### ISSUE THREAD

**Issue by hackel** [bootstrap-vue/bootstrap-vue#4189]
Is there any reason not to use PascalCase for BootstrapVue components, as recommended in the Vue style guide?  I'm just wondering why all of the documentation (and therefore also bug reports and such) use kebab-case.  Is this just a legacy artefact that no one has bothered updating yet, or is there a functional or philosophical reason for choosing kebab-case?  (Not trying to start any flame wars!)  PascalCase makes importing individual components easier too, since we can just use the shorthand property names.

In my (very limited) initial testing, I haven't noticed any issues using PascalCase in my code.

**Comment by tmorehouse** [comment]
Internally all components are PascalCase, and are registered with Vue (when using the plugins) as PascalCase.

In the docs/example, we use kebab-case, but one could use PascalCase.  The reason we use kebab-case in the examples is if a user is using in DOM template, where tag names are always lower cased by the browser (which would loose their PascalCase beinging pascalcase).

**Comment by hackel** [comment]
Thank you for the explanation!

**Comment by tmorehouse** [comment]
For more details:

- https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential

- https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended
  > In most projects, component names should always be PascalCase in single-file components and string templates - **but kebab-case in DOM templates**
  > ...
  > Unfortunately, due to HTML’s case insensitivity, DOM templates must still use kebab-case.
