### ISSUE TITLE
Navbar: supported content

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#419]
Just looking for feature parity on the BS4 docs for navbar supported content, I see this lib here:

- ✅  `.navbar-brand` for your company, product, or project name.
- ✅  `.navbar-nav` for a full-height and lightweight navigation (including support for dropdowns).
- ✅  `.navbar-toggler` for use with our collapse plugin and other navigation toggling behaviors.
- ❌  `.form-inline` for any form controls and actions.
- ❌  `.navbar-text` for adding vertically centered strings of text.
- ✅  `.collapse.navbar-collapse` for grouping and hiding navbar contents by a parent breakpoint.

Are there ways to implement the two content forms I don't see documented? I can hand-write the html, but it gets weird when you're trying to switch between components that build the BS4 nested structure and your hand-written markup.

**Comment by tmorehouse** [comment]
Would you see these as two new `b-nav-` components?

**Comment by alexsasharegan** [comment]
The navbar-text could be an addition to `b-nav-item` perhaps in the form of a `is-nav-text` attribute. The form might even be doable with the current components, but we should add an example to show the proper way to do it.

**Comment by alexsasharegan** [comment]
Maybe just a simple `v-if="isNavText"` for a `div.navbar-text` and a slot, then `v-else` with the `b-link`?
