### ISSUE TITLE
<b-form-select> options wrap text

### ISSUE THREAD

**Issue by alqa-dash** [bootstrap-vue/bootstrap-vue#4190]
This is more question than PR.

I use <b-form-select> to show allowed options to choose and it works fine. 

Recently I've been provided by long text for option values (about 300 characters) and I cannot find a way to wrap text. Especially this is actual for small screens. 

Is it possible to wrap long text description in multiple rows? The only thing I found - wrap text for chosen item with white-space style parameter. 

```
<b-form-select v-model="service.id" :options="options" plain></b-form-select>
```

But I need to wrap each option in dropdown list.

**Comment by Hiws** [comment]
Selects are generally hard to style because each browser seems to handle them differently. Mobile browsers especially. I think your best bet to do this would be to use a normal dropdown and "emulate" it as a select.

**Comment by tmorehouse** [comment]
Yeah, `<b-form-select>` is just a styled native `<select>` element.

When using `<b-dropdown>` as a "select", you can have the currently selected value set as the dropdown's toggle text, and use the `active` class on the dropdown-item-button to indicate that the item is the selected value.

**Comment by alqa-dash** [comment]
Thank you all. I've tried vue-select and complete my task. So I close this issue.
