### ISSUE TITLE
Selectable rows without row-clicked event

### ISSUE THREAD

**Issue by trouttdev** [bootstrap-vue/bootstrap-vue#4191]
### Is your feature request related to a problem? Please describe...

I have a `selectable` table  that when a row is clicked, it opens a modal with information about the row. I'm mainly handling the row selection with custom checkboxes that let you check/uncheck a row to select that row.

I'm leveraging the `this.$refs.selectableTable` `selectRow` and `unselectRow` methods to handle the selecting when the checkboxes are toggled.

The problem I'm running into is that clicking the row selects the row as well as opens the modal, which is not desirable in my application. I would like the row to only be selectable by the checkboxes I've added to the table.

### Describe the solution you'd like

I would like to be able to use all of the functionality of the `selectable` table without the row-clicked event triggering selecting the row.

### Describe alternatives you've considered

I've tried stopping the events on the row-clicked event, but by that point it's too late to stop the emitter.

### Additional context

Here is my table configuration right now:
```html
<b-table
    ref="selectableTable"
    selectable
    @row-selected="onRowSelected"
    select-mode="multi"
    hover
    selected-variant="active"
    @row-clicked="openModal"
    :items="localItems"
    :fields="columns"
    responsive
    outlined
    :busy="loading"
    :filter="filters"
    :filter-function="filterInput"
    :show-empty="true"
>
```

**Comment by tmorehouse** [comment]
Selectable listens to the row-clicked handler for handling the row selection.

Your best bet would be to implement your row selection handling outside of b-table (i.e. using checkboxes or buttons) to enable selection, and apply a row class if it is selected.

Give all your checkboxes in each row the same v-model (and same name), and then use the row's item data as the value of the checkbox.  The resulting v-model will be an array of selected row items.

**Comment by trouttdev** [comment]
@tmorehouse I was trying to avoid that when the selectable table feature is very close to the functionality I'm looking for (select/deselect/active row highlighting/selected rows array), minus the clickable row. It seems like something that could/should be build in to be able to intercept/handle the row click event before it gets emitted out to other components.

I will try out your suggestion though. Thanks for that.

**Comment by tmorehouse** [comment]
The majority of selectable table logic is based around the row-clicked handler, and it would be hard to decouple that (making b-table even more bloated than it is code wise)

**Comment by trouttdev** [comment]
It looks like I'm still able to use the `selectRow`/`unselectRow` methods even when the table is not `selectable` which is nice. Rolling my own select/unselect mechanisms via checkboxes + using the builtin methods for selecting the rows seems to work. Thanks for the suggestion.

**Comment by tmorehouse** [comment]
Hmmm the selection helper methods shouldn't work when the table is not selectable... there might be a bug in there.

**Comment by tmorehouse** [comment]
If you use the `tbody-tr-class` prop with a function ref (see https://bootstrap-vue.js.org/docs/components/table#row-styling) you can inspect the row item data and see if it is in our selectedRows array and if so, return the class `'active'` to get the active styling set on the row. The `type` argument (second argument) passed to your function ref will always be `'row'` for item rows (and `'row-details'` if it is the details row)

**Comment by trouttdev** [comment]
Yep, that worked great. Thanks!
If anyone comes across this in the future, this is what I did:
Add `:tbody-tr-class="determineActive"` to your table and then add the method:

```javascript
determineActive(item, type) {
    if (item && type == 'row') {
        if (this.selectedRows.some(row => row.id == item.id)) {
            return 'table-active';
        }
    }
},
```

**Comment by fuoridallarete** [comment]
@tmorehouse I used your way in my code, but I am not able to control the ui while navigating across pages using pagination. The array I created for storing the selected items (users), stays across pages, but I 'loose the tick' on the checkbox... It looks like the v-model binding get lost while surfing the pages..
Here the inherent parts of the code, hoping someone could help.
In the template: 
```
<b-table
            v-if="users && users.length > 0 && !isLoading"
            id="table-transition-userList"
            :key="users.id"
            responsive
            :tbody-transition-props="transProps"
            :fields="fields"
            :items="users"
            hover
            class="mx-2 py-1 tbl-user-list"
            :per-page="perPage"
            :filter="filter"
            :filterIncludedFields="filterOn"
            @filtered="onFiltered"
          > 
          <template
            v-slot:head(checkbox)="data">
            <b-form-checkbox
              size="lg"
              v-model="isSelectedAll"
              @change="selectAll(data)"
            />
          </template>
          <template
            v-slot:cell(checkbox)="data"
          >
            <b-form-checkbox
              v-model="data.item.selected"
              @change="select(data.item)"
            />
          </template>
```
In the script data:
```
fields: [
        { key: 'checkbox', label: ''},
        { key: 'fullName', label: 'Utente' },
        { key: 'user.username', label: 'Username' },
        { key: 'user.email', label: 'Email' },
        { key: 'buttons', label: 'Operazioni' }
      ],
      totalRows: 1,
      currentPage: 1,
      perPage: 5,
      pageOptions: [5, 10, 15, 20, 25],
      filter: null,
      filterOn: [],
      users: [],
      selectedUsers: [],
      isSelectedAll: false
```
In the methods:
```
selectAll() {
      this.isSelectedAll = !this.isSelectedAll
      this.users.forEach(user => user.selected = this.isSelectedAll)
      
      const notSelected = this.users.filter(user => !user.selected)
      const selected = this.users.filter(user => user.selected)

      // new selected users array without current page selected users
      let selectedUsersCopy = this.selectedUsers.slice().filter(user =>
        !notSelected.find(e => e.id === user.id)
      )
      if(notSelected.length > 0) {
        this.isSelectedAll = true
      }
      else {
        this.isSelectedAll = false
      }
      this.selectedUsers = [
        ...selectedUsersCopy,
        ...selected.filter(user => !selectedUsersCopy.find(e => e.id === user.id))
      ];
      
      console.log('selected', selected, 'this.sele', this.selectedUsers, 'copy', selectedUsersCopy, 'notSele', notSelected)
    },
    select(user) {
      user.selected = !user.selected
      this.isSelectedAll = false
      const selected = this.users.filter(user => user.selected)
      if(selected.length === this.users.length) {
        this.isSelectedAll = true
      }
      else {
        this.isSelectedAll = false
      }
      let isDouble = false
      if(this.selectedUsers.find(v => v.user.id === user.id)) isDouble = true
      if(user.selected) {
        if(isDouble) {
          console.log('double if user selected and isDouble', isDouble)
          console.log("object already exists", this.selectedUsers)
          return
        }
        else {
          this.selectedUsers.push(user)
          console.log("pushed", this.selectedUsers)
          return this.selectedUsers
        }
      }
      else {
        const index = this.selectedUsers.indexOf(user);
        this.selectedUsers.splice(index, 1);
        console.log("removed, new array: ", this.selectedUsers)
      }
    },
    async pagination(page) {
      const payload = {
        limit: this.perPage,
        offset: (page - 1) * this.perPage
      }
      this.isLoading = true
      this.isSelectedAll = false
      await this.$store.dispatch('user/setUsers', payload)
      const response = this.$store.getters.users
      this.users = response.results
      this.isLoading = false
      this.currentPage = page
    }
```
My pagination is calling different apis with different limits and offsets.
I think the problem is to be found in the built-in checked property of the form checkbox...
Thanks to anyone who could give me a hint.
xx

**Comment by tmorehouse** [comment]
When your data rows paginate (if using server side pagination, etc), you will need to re-set the row's (item's) checkbox v-model value, based on your selected items array that you are maintaining.

**Comment by fuoridallarete** [comment]
Isn't it already bound to the selected items?
```
v-model="isSelectedAll"
v-model="data.item.selected"
```
Or they are in the first page...

**Comment by tmorehouse** [comment]
When you paginate, the rows are refreshed (from the server), which does not contain `selected: true`

**Comment by fuoridallarete** [comment]
Is there then a kind of work around to solve it? Sorry to bother...
