### ISSUE TITLE
Carousel with multiple visible slides

### ISSUE THREAD

**Issue by michael-hillmann** [bootstrap-vue/bootstrap-vue#4198]
### Is your feature request related to a problem?
I would like to use the carousel for providing reference logos as a auto-sliding component, which shows 3, 5 or 7 logos (depending on device) out of a total of 12 in a row.

Currently, I see no option to realize this with bootstrap. For now I use hooper, but I would like to solve the website with a single frontend library.

### Describe the solution you'd like

Interface inspired by hooper is fine.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by tmorehouse** [comment]
The current carousel is based on Bootstrap v4's carousel CSS and markup, which currently doesn't provide the ability (CSS wise) to show multiple slides at once.

However, you can/could place multiple logos/images into a single slide (i.e. use a card group), placed into the ill-names slot `img` (which you can actually place any content in).

```html
<b-carousel ...>
  <b-carousel-slide>
    <template v-slot:img>
      <b-card-group>
        <b-card img-src="/some/image.jpg" overlay></b-card>
        <b-card img-src="/some/image.jpg" overlay></b-card>
        <b-card img-src="/some/image.jpg" overlay></b-card>
      </b-card-group>
    </template>
  </b-carousel-slide>
  <b-carousel-slide>
    <template v-slot:img>
      <b-card-group>
        <b-card img-src="/some/image.jpg" overlay></b-card>
        <b-card img-src="/some/image.jpg" overlay></b-card>
        <b-card img-src="/some/image.jpg" overlay></b-card>
      </b-card-group>
    </template>
  </b-carousel-slide>
  <b-carousel-slide>
    <template v-slot:img>
      <b-card-group>
        <b-card img-src="/some/image.jpg" overlay></b-card>
        <b-card img-src="/some/image.jpg" overlay></b-card>
        <b-card img-src="/some/image.jpg" overlay></b-card>
      </b-card-group>
    </template>
  </b-carousel-slide>
</b-carousel>
```

**Comment by snajjar** [comment]
why is this feature request closed? I'd need this as well :/
