### ISSUE TITLE
file-name-formatter in <b-form-file> gets triggered prematurely 

### ISSUE THREAD

**Issue by HenryQW** [bootstrap-vue/bootstrap-vue#4204]
### Describe the bug

Not sure if this is intended, file-name-formatter gets triggered before files are dropped (releasing mouse left button).

### Steps to reproduce the bug

1. Visit [the demo](https://codesandbox.io/s/drag-drop-gd2x5)
1. Drag the first file and drop into b-form-file, the placeholder is updated to '1'
2. Drag another file and move in and out b-form-file's boundary, but without dropping it (releasing mouse left button)
3. The placeholder will get updated

### Expected behavior

file-name-formatter should only get triggered when the files are dropped.

### Versions

**Libraries:**

- BootstrapVue: 2.0.3
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: [Mac]
- OS: [macOS Mojave]
- Browser: [Chrome]
- Version: [78]

### Demo link

https://codesandbox.io/s/drag-drop-gd2x5

**Comment by tmorehouse** [comment]
What is happening, is that the formatted gets called _whenever_ the file names are shown.

This is not a bug and is expected.  The drop placeholder is shown when hovering over the file input when you are draging (but not dropping the file).  Then when you move the dragded file away (with out dropping it onto the file input), the formatter is run again to update the list of file names (to replace the drop placeholder that was shown).
