### ISSUE TITLE
How to build a global media modal

### ISSUE THREAD

**Issue by r94ever** [bootstrap-vue/bootstrap-vue#4205]
Hi all,

I am building a global media library using bootstrap-vue modal, which could be called from anywhere in my application. But I meet a trouble and I think I need help from community.

Okey, let me describe more. My media library modal has 2 common button. One is normal closing modal button, and one is "Action Button". I won't say anything about Closing button, but I will say about its "Action Button". Why? Imagine I have a settings page with many input fields. Some of them are normal input, textarea, checkbox.... But some of them are "group-input" which have a secondary button help user click to it to open my media library modal then choosing photos. And my trouble start from here...

That is: when user choosed their photo, user need to click to "Action Button" to DO-SOME-THING. But each of "group-input" field need a different callback, eg, one field need `insertMediaId()`, one field need `insertAllSelectedMediaUrls()`, one field use `insertToTinyMCE()` etc., while creating one media modal for each input is not a good way.

If you have any solution pleas help me to solve this trouble. Any help would be appreciated. Thanks,

**Comment by TitanFighter** [comment]
You can have one modal inside of which you can implement different logic and execute different logic based on some global state. For example when you click "Action Button-1" you set global state to "Action Button-1" + open modal which reads this state and shows logic you need. You can even `watch` this global state from modal component.

**Comment by r94ever** [comment]
thank you very much. I think this approach is pretty good. I will try it
