### ISSUE TITLE
modal is z-index: 1050,modal is z-index: 1050,popover is z-index: 1060

### ISSUE THREAD

**Issue by caihuattkl** [bootstrap-vue/bootstrap-vue#421]
modal is z-index: 1050,modal is z-index: 1050,popover is z-index: 1060

The Popover Z-index greater than modal Z-index causes me to click on the Popover information in the modal box!

Is this a bug?

**Comment by tmorehouse** [comment]
This is defined by bootstrap V4 css.

This is to allow popovers and tooltips to be used within a modal.
