### ISSUE TITLE
<b-carousel> slides overlap if they change too fast

### ISSUE THREAD

**Issue by Hiws** [bootstrap-vue/bootstrap-vue#4210]
### Describe the bug

If you rapidly switch slides in `b-carousel` the slides start to overlap, and doesn't look visually smooth as shown in the video below.

https://i.imgur.com/pEr9Z6x.mp4

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/carousel
2. Rapidly click the next/prev slide `arrows`

### Expected behavior

The carousel should wait for the previous slide animation to finish before allowing the next one to start like in the native bootstrap examples seen here:
https://getbootstrap.com/docs/4.3/components/carousel/#with-controls

### Versions

**Libraries:**

- BootstrapVue: 2.0.3
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Comment by tmorehouse** [comment]
Bootstrap v2.0.4 has been released.
