### ISSUE TITLE
thead-variant primary, info, ... don't work with b-table

### ISSUE THREAD

**Issue by oussama-he** [bootstrap-vue/bootstrap-vue#4215]
I use b-table in an application that I'm building and want to change the table head using thead-variant. When I set the value dark or light to thead-variant it works fine, but when I use the other variants like primary, info, danger, ... they don't work for me.

the versions that I use are:

Bootstrap: 4.3.1
Bootstrap-vue: 2.0.3
Vue: 2.6.10

**Comment by tmorehouse** [comment]
head-variant `light` or `dark` are teh only supported Bootstrap variants on the `<head>` and `<foot>` elements, which are mainly used for controling the text of the header.

To get a header row variant applied, you currently need to set `thead-tr-class` to `table-info` (etc).

**Comment by oussama-he** [comment]
Thank you for your help. Could you please tell me how can I change text color in the table head?
Thank you in advance.

**Comment by tmorehouse** [comment]
Set `thead-tr-class` to have `text-danger` etc., or use the `thClass` property in the field's definition (https://bootstrap-vue.js.org/docs/components/table#field-definition-reference) to set the `<th>` class to, say, `text-danger`.

**Comment by tmorehouse** [comment]
BootstrapVue `v2.1.0` has been released, which has added support for this feature.
