### ISSUE TITLE
Help with style loader

### ISSUE THREAD

**Issue by Khachatour** [bootstrap-vue/bootstrap-vue#422]
Hey there folks!! I am fairly new to webpack, so I can't figure out how to inport css for bootstrap-vue and bootstrap. Thanks in advance!

**Comment by pi0** [comment]
Hi @Khachatour. The simplest approach is just including `bootstrap-vue.css` just like including `bootstrap.css` into your project. For using with webpack you may need to configure special loader. You can [learn more](https://webpack.js.org/guides/code-splitting-css/) here.

**Comment by Khachatour** [comment]
@pi0 Thanks for the quick reply. So in whatever view (.vue file)I want to use bootstrap-vue, in script section I need to import `bootstrap-vue.css and bootstrap.css` ?

**Comment by pi0** [comment]
You only to import them one time globally :) (For example in entry point js file)

**Comment by Khachatour** [comment]
@pi0 Can you please verify if this is the right way:)
`import Vue from 'vue'
import { sync } from 'vuex-router-sync'
import App from './components/App.vue'
import router from './router'
import store from './store'
import BootstrapVue from 'bootstrap-vue'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'


Vue.use(BootstrapVue);

sync(store, router)

const app = new Vue({
  router,
  store,
  ...App
})

export { app, router, store }`

**Comment by pi0** [comment]
Yep it should work fine as long as webpack config is correct ;) If you are new to vue and webpack strongly suggest starting your project with [nuxt.js](https://nuxtjs.org) it will provide base project with base practices & grow up with your needs :)

**Comment by Khachatour** [comment]
@pi0 Okay thanks !! And one more question by the webpack config is correct what you mean ?  That this file is the entrypoint yes ?

**Comment by pi0** [comment]
Yep, basically this imports should be done just before creating Vue instance.

**Comment by Khachatour** [comment]
Okay thanks ! Not yet resolved, but working on in !

**Comment by Mark-L6n** [comment]
Thanks for the info @pi0.  
For future readers: I had this problem after using `vue-cli` with the `webpack-simple` template (responding either y/n to the Sass option). 
Followed @pi0 link above to https://webpack.js.org/guides/code-splitting-css/ , which has 2 options for specifying CSS loaders.  Couldn't get the second method, "Using ExtractTextWebpackPlugin" to work, but the first option "Using css-loader and style-loader" loaded the CSS files.

**Comment by alexsasharegan** [comment]
@Mark-L6n I had some trouble getting my css to extract to a generated file too. Not sure how helpful my webpack config might be, but have a look: https://gist.github.com/alexsasharegan/b7489d4c1e9ae969f66fe807b5dea6ef

**Comment by Mark-L6n** [comment]
I just tried getting this to work with the `webpack` template instead of the `webpack-simple` template.  It's completely different, and after a couple of hours of figuring it out, it looked like CSS files should already be being loaded using the 2nd method from the https://webpack.js.org/guides/code-splitting-css/ page.
Turns out the solution is simple. Instead of writing in `main.js`:

``` js
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
```

…put in the correct relative path:

``` js
import '../node_modules/bootstrap/dist/css/bootstrap.css'
import '../node_modules/bootstrap-vue/dist/bootstrap-vue.css'
```
:Doh:

**Comment by Mark-L6n** [comment]
A later FYI: there seems to be some magical caching going on with this, and I can't re-create the problem.  Doesn't seem to be browser cache.  Doesn't seem to be npm cache, either.  In case it helps anyone, copying over notes I made for myself:

`npm cache ls | grep -i "bootstrap"` shows you all the files containing the term "bootstrap" in the cache, ie:

``` bash
~/.npm/bootstrap/3.3.7/package/package.json
~/.npm/bootstrap-vue/0.16.1/package.tgz
```

To remove a directory from cache, specify it `rm` + directory name (actually, `rm`, `clean` & `clear` are all synonyms; see `npm help cache` or [web](https://docs.npmjs.com/cli/cache)). Don't use the `~/.npm/` from the `npm cache ls` output, for ex do:
`npm cache rm "bootstrap"`
`npm cache rm "bootstrap-vue"`
Strangely, I still seem to get weird caching; tried `npm cache clear`, different browsers, and even `npm uninstall bootstrap-vue` and re-installing.  [Could webpack be caching some path?](https://webpack.js.org/guides/caching/)

**Comment by alexsasharegan** [comment]
Does this issue persist for any involved? Skimming over this quickly, it appears mostly solved. Will probably close in the next couple of weeks if no further comments.
