### ISSUE TITLE
Spacing of b-dropdown-form inside b-nav-item-dropdown

### ISSUE THREAD

**Issue by janmichaelwalther** [bootstrap-vue/bootstrap-vue#4220]
### Describe the bug

I'm currently working on a dropdown-form in a nav-item-dropdown. The spacing of my form-group doesn't work and my searchbar is stretched to the side of the dropdown unlike text which is spaced correctly.

### Steps to reproduce the bug

See codepen linked below!

### Expected behavior

The spacing on the left und right side of my searchbar is similiar to the spacing of my text below.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.19
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Windows 10 (64_bit)
- Browser: Mozilla Firefox
- Version: 69.0.1 (64-Bit)

### Demo link

https://codepen.io/JayToZeDoubleU/pen/QWWwxxp?editors=1010

### Additional context

So far the only workaround is to add class="b-dropdown-text" to the dropdown-form or to wrap a dropdown-text around the dropdown-form.

**Comment by tmorehouse** [comment]
This appears to be a bug in our custom SCSS with dropdown forms.

**Comment by tmorehouse** [comment]
Fix will be available in v2.0.4

Temporary work-around would be to add class `b-dropdown` to the `<b-nav-item-dropdown>` component.

**Comment by tmorehouse** [comment]
Bootstrap v2.0.4 has been released.
