### ISSUE TITLE
Can't add actions to rows of b-table

### ISSUE THREAD

**Issue by oussama-he** [bootstrap-vue/bootstrap-vue#4221]
I use b-table in an application that I'm building and want to add actions to rows to the table that displays some data. But I can't achieve this. 

This is a portion of my code:
``` vue
<template>
    <div class="container">
        <b-table thead-tr-class="bg-info text-white" hover striped bordered :items="books" :fields="fields" class="rtl-table">
        <template v-slot:cell(edit)="row">
        <b-button size="sm" @click="info(row.item, row.index, $event.target)" class="mr-1">
          Info modal
        </b-button>
      </template>
        </b-table>
    </div>
</template>

<script>
export default {
    name: "Archive",
    data () {
        return {
            fields: [
          { key: 'title', label: 'عنوان الكتاب', sortable: true, sortDirection: 'desc' },
          { key: 'author', label: 'المؤلف', sortable: true, class: 'text-center' },
          { key: 'nbr_pages', label: 'عدد الصفحات', sortable: true, class: 'text-center' },
          { key: 'volumes', label: 'عدد المجلدات', sortable: true, class: 'text-center' },
          { key: 'url', label: 'الرابط', sortable: true, class: 'text-center' },
          { key: 'edit', label: 'تعديل' }
        ]
        }
    },
    computed: {
        books () {
            return this.$store.getters['books/books']
        }
    },
    created () {
        this.$store.dispatch('books/getArchivedBooks')
    }
}
```
I get the column edit 'تعديل' but there is no button. I don't know why. Does any help please? And thank you in advance.

the versions that I use are:
Bootstrap: 4.3.1
Bootstrap-vue: 2.0.3
Vue: 2.6.10

**Comment by Hiws** [comment]
Your code works in the [playground](https://bootstrap-vue.js.org/play/). 

Make sure your version of vue-bootstrap is 2.0.0 and above. Try reinstalling.

**Comment by tmorehouse** [comment]
Where is your method "info" defined?

**Comment by oussama-he** [comment]
It doesn't work for me. I removed bootstrap-vue and reinstalled and I remove the method info, but nothing change. Also, I would like to say that I copied the example titled Complete example from the documentation ([here](https://bootstrap-vue.js.org/docs/components/table/#complete-example)) and it doesn't work for me.
The versions that I use are:
Bootstrap: 4.3.1
Bootstrap-vue: 2.0.3
Vue: 2.6.10

**Comment by tmorehouse** [comment]
See this fiddle: https://jsfiddle.net/p8kg6nLo/

**Comment by oussama-he** [comment]
I saw the links provided in the last comment, is the same code I have. Really I don't know where is the problem.

**Comment by tmorehouse** [comment]
When installing Bootstrap/BootstrapVue/Vue, check in your node_modules directory and verify that you have the latest version of each by checking the version string in their package.json files.

If using yarn to install your dependencies, try deleting node_modules directory and yarn.lock files, then do a fresh install. make sure your package.json dependencies request the correct versions

**Comment by oussama-he** [comment]
Thank you very much.
