### ISSUE TITLE
Tooltip not being correctly toggled on hover

### ISSUE THREAD

**Issue by WifiDubt** [bootstrap-vue/bootstrap-vue#4222]
### Describe the bug

Tooltips aren't being toggled correctly. The tooltip is shown and hidden right afterwards.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19328374/66407861-d7464500-e9e5-11e9-968d-39e6bbca3cfb.gif)

Here's my Template and generated tooltip.
<img width="808" alt="Captura de ecrã 2019-10-08, às 14 52 04" src="https://user-images.githubusercontent.com/19328374/66407632-71f25400-e9e5-11e9-8dc9-f1235588f3b5.png">
![Captura de ecrã 2019-10-08, às 14 54 07](https://user-images.githubusercontent.com/19328374/66407633-71f25400-e9e5-11e9-8828-eb00b6ce6be7.png)

.

### Steps to reproduce the bug

1. Create a tooltip toggled on hover
2. Hover the object

### Expected behavior

It should just show the tooltip without closing it right after.

### Versions

**Libraries:**

- BootstrapVue: 2.0.3
- Vue: 2.6.10

**Environment:**
- Device: Mac
- OS: macOS
- Browser: Chrome
- Version: 77

**Comment by tmorehouse** [comment]
Ensure you are including the BootstrapVue custom CSS/SCSS.

We had to add additional styling to make Bootstrap's tooltip/popover styles work with Vue's `<transition>` component.

**Comment by add1ct3dd** [comment]
Did this change between version 2.0.0-rc.19 and the latest 2.0.3 version?

I only ask because rc.19 works (we have the scss imported), however updating to rc.28 and subsequently 2.0.3 it is still broken for us.

Thanks!

**Comment by atilacamurca** [comment]
I had the same issue and solved importing a scss file from tooltip component folder.

```scss
@import 'node_modules/bootstrap/scss/bootstrap';
/* other imports ... */
@import 'node_modules/bootstrap-vue/src/components/tooltip/_tooltip.scss';
```

Do that if you are importing only some scss files instead of the whole `node_modules/bootstrap-vue/src/index.scss` file.

**Comment by tmorehouse** [comment]
Note, one can set SASS variables to disable generating of some of the larger portion of BootstrapVue's custom SCSS/CSS (i.e. i you don't need  certain table features, etc)

https://bootstrap-vue.js.org/docs/reference/theming#sass-options
