### ISSUE TITLE
Só passo raiva com esta merda

### ISSUE THREAD

**Issue by izifinancespider** [bootstrap-vue/bootstrap-vue#4225]
### Steps to reproduce the bug

1. Go to [...]
2. Click on [...]
3. Scroll down to [...]

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.js.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
Lamentamos que você esteja com problemas para entender como o Vue funciona.

Consulte o Guia Vue: https://vuejs.org/v2/guide/
