### ISSUE TITLE
b-form-checkbox with w3c validation error

### ISSUE THREAD

**Issue by jenemde** [bootstrap-vue/bootstrap-vue#4230]
### Describe the bug

When implementing <b-form-checkbox> there appears the attribute "autocomplete" with the value "off" in the generated html. The w3c validator (https://validator.w3.org) throws the error that the attribute autocomplete is not allowed with the input type="checkbox".

**Libraries:**

- BootstrapVue: 2.0.3
- Vue: 2.6.10
### Additional context

I'm not sure if it is a bug or if I miss something to avoid the autocomplete attribute in the input type="checkbox" tag.

**Comment by tmorehouse** [comment]
This is to prevent a bug with some older versions FireFox.  The bug is when you have a form on one page (with checkboxes or radios) and then link to a new page, and then the user uses the browser back button to return to the previous page. Firefox would retain the previous values but wouldn't  issue a change event.

**Comment by jenemde** [comment]
Thanks, I see, but this way you get an html validation error which should not happen. Is there a way to decide on my own if I'd rather accept the firefox bug? I can't find a solution to remove the attribute in the checkbox input.

**Comment by tmorehouse** [comment]
I wouldn't worry too much about the W3C validation of that attribute. It won't cause any issue with usage (actually it fixes a browser bug).

**Comment by jenemde** [comment]
The problem is that our site has to undergo an accessibility test (WCAG 2.1) - and any error in the w3c validation is a total failure for the whole test. Is it possible for you to provide the opportunity to add or remove the `autocomplete` attribute (as for example `required` or `name`) with a value of choice?

**Comment by tmorehouse** [comment]
W3C HTML validation is not the same as WAI-ARIA accessibility testing.

You will probably end up with bugs with Firefox users without that attribute, if they use the back button on their browser (checkboxes out of sync with the v-model).

**Comment by jenemde** [comment]
I know the validations are not the same, but the accessibility testing (WCAG 2.1) includes W3C HTML validation.
I see the problem, but I think it's a good idea to let the developer decide which issue (validation error or browser bug) he wants to avoid. And he would have the chance to do so if `autocomplete` would be treated the same way as `required` or `name`.

By the way, thanks for the very fast response.
