### ISSUE TITLE
Tooltip on an SVG element works, but prop validation errors out

### ISSUE THREAD

**Issue by moltar** [bootstrap-vue/bootstrap-vue#4234]
### Describe the bug

It is possible to attach a tooltip via `v-b-tooltip.hover` directive to an SVG element.

But when hovering, prop validation fails with:

> Invalid prop: type check failed for prop "target". Expected HTMLElement, got SVGCircleElement 

### Steps to reproduce the bug

1. Create an SVG element with a simple circle path
2. Put a `v-b-tooltip.hover` directive on it
3. Add a `title` attribute with a value for the tip
4. Hover over the SVG element you put the directive on
5. Observe console log error

### Expected behavior

No errors.

### Versions

**Libraries:**

- BootstrapVue: 2.0.2
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS
- Browser: Chrome
- Version: N/A

**Comment by moltar** [comment]
I am seeing here that it is not including all of the possible SVG element types:

https://github.com/bootstrap-vue/bootstrap-vue/blob/37149d2d1b51b8e8374958838fe126a4b90f8ebb/src/components/tooltip/tooltip.js#L27

There are many other potential elements, and I am not sure if it is even realistic to include a full list.

https://developer.mozilla.org/en-US/docs/Web/API/SVGCircleElement

Thoughts?

**Comment by moltar** [comment]
I think we could add `SVGElement` at least, which is a generic element, from which other elements inherit.

**Comment by moltar** [comment]
Oh, wait, that is already on the list 😆

**Comment by tmorehouse** [comment]
SVGElement (which all other SVG elements inherit from) allowed prop type was added in BootstrapVue release v2.0.3

**Comment by moltar** [comment]
Oh this has been fixed!!!

https://github.com/bootstrap-vue/bootstrap-vue/commit/fab7fea0a69b36b95f0c9606122140fe771e8ac8
