### ISSUE TITLE
Table small not working.

### ISSUE THREAD

**Issue by happilymarrieddad** [bootstrap-vue/bootstrap-vue#424]
Hey guys, for some reason table(small) doesn't work for me but table.table-sm works just fine. The weird part is the other options like table(responsive) works just fine.. Here are some images.

![selection_198](https://cloud.githubusercontent.com/assets/6416323/26260494/af1f108a-3c8a-11e7-83ca-5bfd2cb42385.png)
![selection_197](https://cloud.githubusercontent.com/assets/6416323/26260497/b0cb8d96-3c8a-11e7-90cc-6bd14588db4a.png)

**Comment by tmorehouse** [comment]
That is strange.  Looking at the code, it would be `table-responsive` that is not working (has a decimal in front of the class name by mistake).

Are you using the latest release?

**Comment by happilymarrieddad** [comment]
Umm, I pulled yesterday. I will update now and take another look.

**Comment by alexsasharegan** [comment]
@tmorehouse, are you talking about this: https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/table.vue#L189 ?

**Comment by happilymarrieddad** [comment]
@alexsasharegan @tmorehouse  No, I'm talking about .table-sm. The responsive class as far as I can tell works great.

**Comment by tmorehouse** [comment]
@alexsasharegan yeah, that linke.  working on a PR for that, as well as adjusting the sort arrows for table-sm.

@happilymarrieddad when I use the current table docs fiddle, small is working for me.

**Comment by happilymarrieddad** [comment]
@tmorehouse I know this is a different issue but is there a way to call a custom sort function? I want to change the way it's doing it. THanks!

**Comment by tmorehouse** [comment]
@happilymarrieddad there is a prop for specifying a custom sort routine.

**Comment by tmorehouse** [comment]
PR #425 addresses the erroneous `.` in  class `table-responsive` and addes CSS for handling the sort arrows on `table-sm`

**Comment by tmorehouse** [comment]
@happilymarrieddad ah.  Hmmm, it might be possible to have the clicking of head cells emit an event on $root which specifies the field being clicked and the order that it is being switched to (asc or desc), along with meta info about the field. (nd maybe exposing a `cancel()` method on the event (similar to what `b-modal` does).

What were you thinking of happening when handling the sort?

**Comment by happilymarrieddad** [comment]
Well, the problem I'm having is I have one page with over 10,000 results and I would rather search the search on my server and resend a data set. When I write it out myself it makes the table MUCH faster. As it stands right now, the sort is almost unusable because it's so slow.

**Comment by tmorehouse** [comment]
What would be best is to dynamically change the table items from your DB query (i.e. returning only the page you want), and handle pagination outside of table.

**Comment by tmorehouse** [comment]
Although sorting would only work on the displayed page.

But if we were to emit an event when a field was clicked for sorting you could tap into that for adjusting your query.  and then set the sort direction to make the arrows line up (would also require a new prop that you could use to set the direction (or maybe a two-way v-model prop that reflects the current sorting direction).

**Comment by tmorehouse** [comment]
I would suggest opening a new issue for this sorting/server need, which will make it easier to track.

**Comment by happilymarrieddad** [comment]
I'm going to handle it out of the table element. Thanks for your time!

**Comment by alexsasharegan** [comment]
@happilymarrieddad If you're enjoying bootstrap-vue, let us know with a ⭐️ ! We appreciate your feedback!

**Comment by happilymarrieddad** [comment]
@a
Already did man!

**Comment by died** [comment]
BTW, table-sm still didn't work now.

**Comment by tmorehouse** [comment]
@died which versin of BS Vue are you using?  if it is the current version or dev branch, can you open a new issue?

**Comment by tmorehouse** [comment]
From the screen shot, it looks like the `small` prop (which adds the `table-sm` class) is working.  The cell padding has been reduced (which is the only change that class `table-sm` introduces).

If you inspect the table cells, you will see that the `table-sm` applies to `.table.table-sm tr td, .table.table-sm tr th`, and does nothing to the table element (even though it is applied to the table).

**Comment by died** [comment]
@tmorehouse Thank for explain it, I got it, sorry I am not good with CSS.

**Comment by cybercussion** [comment]
I'll follow up since I'm seeing this too.  I know this is closed but when I check how its computed it looks like `.table td` padding is winning over `.table-sm td`.

![image](https://user-images.githubusercontent.com/94954/57548270-63f4b600-7315-11e9-9798-75531acd7d85.png)
