### ISSUE TITLE
Is it possible to customize template for multiple scoped field slot?

### ISSUE THREAD

**Issue by hifall** [bootstrap-vue/bootstrap-vue#4244]
For example, this snippet customizes the rendering of field1:

`<template slot="field1" slot-scope="data">`

If I want to customize multiple fields, I'd need to have a snippet like this:

`<template slot="fieldn" slot-scope="data">`

for each one of them.

Is it possible to specify multiple fields all at once like this?

`<template slot="field1, field2, field3" slot-scope="data">`

Thanks!

**Comment by tmorehouse** [comment]
I am assuing you are refering to tables.

In general Vue doesn't allow multiple slot names for a slot template.

For table, there is a fallback slot for cells (that don't have an explicitly named slot): `cell()` (you will need to use BootstrapVue v2.0.0 or greater)

```html
<b-table ... >
  <template v-slot:cell(field1)="data">
    <!-- field1 will use this slot -->
  </template>
  <template v-slot:cell()="data">
    <!-- all other fields will use this slot -->
  </template>
</b-table>
```

**Comment by Hiws** [comment]
Another way would be to use a `v-for` on the scoped slot and create a fieldGroup with the fields you want to have the slot same logic

```
<b-table :fields="fields" ...  >
  <template v-for="field in fieldGroup" v-slot:[`cell(${field})`]="data">
    <!-- field1, field2 and field4 will use this slot -->
  </template>
</b-table>

<script>
{
  ...
  data() {
    return {
      fields: ['field1', 'field2', 'field3', 'field4', 'field5']
      fieldGroup: ['field1', 'field2', 'field4']
    }
  }
  ...
}
</script>
```
