### ISSUE TITLE
Can't vertically center text inside b-form-group

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#4245]
### Describe the bug

Having a form group which in some cases has plain text rather than a form-input.
That text should be vertically centered:
```
 <b-form-group label-cols="4" label-cols-lg="2" label="Default" label-for="input-default">
    Password goes here
  </b-form-group>
```

With plain Bootstrap 4, it is possible by setting ``align-self-center`` for the parent node:
https://stackoverflow.com/questions/58353571/bootstrap-4-vertical-center-text-inside-horizontal-form-row

but in bootstrap-vue markup above there's no such node.

The generated markup has the node, and applying the  ``align-self-center`` class in Inspector works:
```
<div class="col">Password goes here</div>
```

How to generate this markup?
```
<div class="col align-self-center">Password goes here</div>
```

### Expected behavior

A way to apply a class to container node which holds the <b-form-group> content after the label. 

### Versions
2.0.4

Thanks!

**Comment by tmorehouse** [comment]
`<b-form-group>` is intended to contain interactive inputs. (as it will generate a `<fieldset>` which expects form controls as content).  Having no interactive form controls in the form group will be confusing to screen reader users.

Since you are not using any of the features of form-group (other than the column width), use regular `b-row`/`b-form-row` and `b-col` markup (or plain HTML markup)

**Comment by tmorehouse** [comment]
The other option is instead of plain text, use `<b-form-input plaintext value="Password goes here"></b-form-input>` Which will make the "plain text" align up with the label

**Comment by tmorehouse** [comment]
See this fiddle: https://jsfiddle.net/fwmgarvz/

**Comment by mariusa** [comment]
Thanks Troy!

Both solutions are good for the simplified request as posted. We need to display HTML, not just plain text though, and also a form control in same cases.

So I just went with a class applied on b-form-group:
```
.form-align-self-center {
  div {
    div {
      align-self: center !important;
    }
  }
}
```

Thanks for your support!

**Comment by tmorehouse** [comment]
If you are using scoped styles, you can adjust your solution as follows:

```scss
.form-align-self-center ::v-deep {
  div {
    div {
      align-self: center !important;
    }
  }
}
```

The `::v-deep` selector allows you to target child component structure when using scoped styles.

https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements

**Comment by mariusa** [comment]
Thanks so much!
