### ISSUE TITLE
Tooltip instantly disappears

### ISSUE THREAD

**Issue by afuno** [bootstrap-vue/bootstrap-vue#4248]
Everything is fine on your site in the documentation.
But I have a problem on my site - Tooltip disappears almost instantly.

I wanted to ask you, maybe you know why?

I have Bootstrap installed on my site (including JS) regardless of your library. That is, there is a full-fledged rails application that has its own life with Bootstrap.

But there are also Vue components for beauty. In these components, I use your library. And in these components happens that is shown in the gif that I attached.

This problem occurs wherever `v-b-tooltip.hover` is present. If `hover` is replaced on `click` or `focus`, then it will be the same.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2853419/66720823-584c7480-ee0a-11e9-9b6e-d766b40d5929.gif)

**Comment by tmorehouse** [comment]
It looks like you are not including BootstrapVue's custom css as mentioned in the docs.

BootstrapVue's custom css is required to make bootstrap's css work with Vue's transition component.

**Comment by afuno** [comment]
@tmorehouse I also want to add that I have been using your library since RC 20. And then everything was fine. But after some update some kind of conflict began to appear.

**Comment by afuno** [comment]
@tmorehouse Yes you are right! Thank you for your prompt reply.

**Comment by Pablo-Araya** [comment]
Another solution would be to include a $nextTick loader after the dom has loaded
```
var vm = new Vue({
	el: '#elm'
});

global.vm = vm;

// onload VueJs Component:
                        vm.$nextTick(function () {
                            $('[data-toggle="class-for-tooltip"]').tooltip();
                        });
```

**Comment by riseoflex88** [comment]
> It looks like you are not including BootstrapVue's custom css **as mentioned in the docs**.

Can you post a link to this, I can't find any reference to custom css files in the docs

**Comment by svamja** [comment]
> It looks like you are not including BootstrapVue's custom css as mentioned in the docs.
> 
> BootstrapVue's custom css is required to make bootstrap's css work with Vue's transition component.

Thanks, @tmorehouse!. This worked.

Those who are wondering, it is provided [here](https://bootstrap-vue.org/docs/reference/theming).

I was compiling (through Laravel), so just added the second line given below, as per above reference.

@import '~bootstrap/scss/bootstrap.scss';
**@import '~bootstrap-vue/src/index.scss';**

**Comment by RobKlock** [comment]
If for whatever reason you don't want to include BootstrapVue's custom css you can use BootstrapVue's [Popover Component](https://bootstrap-vue.org/docs/components/popover) with a hover trigger to accomplish a similar feature as a tooltip

`v-b-popover.hover.top="<data>" `
