### ISSUE TITLE
"mouseover" / "mouseleave" do not work with "b-img-lazy". "b-img" is ok.

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#4249]
### Describe the bug

`mouseover` / `mouseleave` do not work with `b-img-lazy`.
`b-img` is ok.
As a workaround `b-img-lazy` can be wrapped by `div` with `@mouseover` / `@mouseleave`. 

### Versions

**Libraries:**

- BootstrapVue: 2.0.4
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Ubuntu 19.04
- Browser: Firefox 69.0.2 x64 / Chrome 77.0.3865.120 x64

### Demo link
[Demo](https://codesandbox.io/s/bootstrap-vue-mouseoverleave-issue-lx658)

**Comment by tmorehouse** [comment]
B-img-lazy is a full (statefull) component, while b-ing is a functional component.

You need to use the `.native` modifier on b-img-lazy

**Comment by TitanFighter** [comment]
Yesterday I checked VueJS docs for the list of modifiers and did not found this modifier (at the same time I simply forgot that this one exists). Today I found the right [page](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components).

Thanks.
