### ISSUE TITLE
<b-form-checkbox> event sequence

### ISSUE THREAD

**Issue by jun3838** [bootstrap-vue/bootstrap-vue#4250]
### Describe the bug
Event usage such as `input` and `change` is different from what you would expect from an native input checkbox.

As suggested from [mdn](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) 
> For <input> elements with type=checkbox or type=radio, the input event should fire whenever a user toggles the control, per the HTML5 specification. However, historically this has not always been the case. Check compatibility, or use the change event instead for elements of these types.

## Issue

**Native checkbox**
Rely on `@change` event to get the latest committed value

**Bootstrap vue checkbox**
Rely on `@input` event to get the latest committed value

### Steps to reproduce the bug
```html
<template>
  <div>
    <b-form-checkbox
      v-model="checkbox"
      @input="onInput"
      @change="onChange"
    >
      Bootstrap vue form checkbox
    </b-form-checkbox>    
    <input 
      type="checkbox" 
      v-model="nativeCheckbox" 
      @change="onNativeChange" 
      @input="onNativeInput"/> 
      Native checkbox
  </div>
</template>

<script>
  export default {
    data() {
      return {
        checkbox: false,
        nativeCheckbox: false
      }
    },
    methods: {
      onChange () { console.error('bs @change', this.checkbox) },
      onInput () { console.error('bs @input', this.checkbox) },
      onNativeChange () { console.error('native @change', this.nativeCheckbox) },
      onNativeInput () { console.error('native @input', this.nativeCheckbox) }  
    }
  }
</script>
```

Notice that, native checkbox fire `@input` event follow by `@change` event where `@change` would carry the committed value

As for bootstrap vue form checkbox, `@change` was fired first followed by `@input`, expecting committed value from a `@change` would be different compare to what you would have expected from a native checkbox

### Expected behavior
Bootstrap vue form checkbox should provide same expectation for `@change` and `@input`

### Versions
v2.0.4

**Libraries:**

**Environment:**

- Device: Mac
- OS: El Capitan
- Browser: Chrome
- Version: 77

### Demo link
Paste the code above into https://bootstrap-vue.js.org/docs/components/form-checkbox/#form-checkbox-inputs and you will see

**Comment by tmorehouse** [comment]
Due to supporting the optional formatter and emulation  of Vue's lazy, trim and number modifieds (which vue does not natively support on components)... b-form-input uses custom events... `@updated` for the v-model event) which could be triggered by input change or blur. `@input` is per character but after formatting, and `@change` is native change event or blur event.

If you need native events, use the `.native` event modifier to tell Vue to use the underlying native events... ignoring the functionality of b-form-input... or just use an HTML5 `<input>` element and add on class `form-control`... if you are looking for true native input behavior.

**Comment by tmorehouse** [comment]
This is not a bug.... but how the inputs evolved over time.  They initially used a single event only whenever the v-model updated . There was no differentiation between user interaction updating the model and the model being programmatically updated... which is where the second event came in.

If you are truly worried about which event you should listen to (it should be the documwnted v-model event) then switch to a native input element.
