### ISSUE TITLE
Drag drop file does not result in correct content-type

### ISSUE THREAD

**Issue by arpitlov09** [bootstrap-vue/bootstrap-vue#4251]
I am using b-form-file for uploading files.
When I select a and excel file by clicking on the browse button, the content-type of the file I get on the server side is "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", but when I drag-and-drop the same file, the content-type of the file on the server side is  "application/octet-stream".
Based on the content-type of the file I have different processes processing the file, but now I can't decide the process as the content type of the file is not proper.

**Comment by tmorehouse** [comment]
Drag and drop doesn't u[date the native `<input type="file">` (Drag and drop is handled via Javascript, and javascript isn't allowed to update the `files` array associated with the file input.  This is probably why there is a discrepancy.
