### ISSUE TITLE
Form input type=number behaves erratically while selecting (in chrome)

### ISSUE THREAD

**Issue by mverdaguer** [bootstrap-vue/bootstrap-vue#4254]
### Describe the bug

When you try to select a part of a `FormInput` having `type=number` it does not select the text properly. (Only in Chrome).

Example gif:
![actual-chrome](https://user-images.githubusercontent.com/12875080/66807619-fef45a80-ef5b-11e9-86a6-8024f39c8824.gif)

### Steps to reproduce the bug
0. Using Chrome 77.0.3865.90.
1. Go to [https://bootstrap-vue.js.org/docs/components/form-input/#input-type](https://bootstrap-vue.js.org/docs/components/form-input/#input-type)
2. Enter some numbers in the `Type number` row.
3. Try to select part of the numbers. You'll notice that it does not do it properly.

You can also test it in this [codesandbox](https://codesandbox.io/s/jkp18) where I've added a native `input` and the `b-form-input`.

### Expected behavior

It should be possible to select easily part of the text or move the caret to any position by clicking it.
Example (Firefox):
![expected-firefox](https://user-images.githubusercontent.com/12875080/66807755-5e526a80-ef5c-11e9-94a0-d4ed14a79ed5.gif)

### Versions
I've used your own website.

**Libraries:**
- BootstrapVue: v2.0.4

**Environment:**

- Device: MSI laptop using .
- OS: Ubuntu 18.04.3 LTS  (The same happens using a macOS with el Capitan).
- Browser: Chrome
- Version: 77.0.3865.90

**Comment by jackmu95** [comment]
@mverdaguer I've forked your your CodeSandbox and applied the `form-control` class to the native input and noticed the same behavior: https://codesandbox.io/s/withered-worker-21h0v

**Comment by tmorehouse** [comment]
A similar issue appears with type search as well, where one can't place the cursor (with the mouse) at the very start of the input value (but one can move the cursor to the start through via keyboard).

Definitely an upstream issue + browser bug (quirk)

**Comment by tmorehouse** [comment]
You might want to open an upstream issue at https://github.com/twbs/bootstrap/issues and provide a basic reproduction (using native input and bootstrap classes).

**Comment by mverdaguer** [comment]
FYI: I've opened an issue there: https://github.com/twbs/bootstrap/issues/29528

**Comment by tmorehouse** [comment]
This appears fixed with Chrome 78
