### ISSUE TITLE
b-table组件

### ISSUE THREAD

**Issue by tj771889579** [bootstrap-vue/bootstrap-vue#4256]
b-table组件field 中的formatter是否可以支持html?不想用v-slot,因为代码会增多

Can the formatter in the b-table component field support html? Don't want to use v-slot because the code will increase

**Comment by tmorehouse** [comment]
The formatter can return HTML strings, but it will render as plain text (the HTML special characters will be escaped) by Vue.

You can use the example shown in the docs using a slot to convert the HTML string into true HTML (using v-html).  You can use the special fallback slot `'cell()'` to be used for all cells without an explicit slot:

```html
<b-table ... >
  <template v-slot="cell()"="scope">
    <div v-html="scope.value"></div>
  </template>
</b-table>
```

**Comment by mosinve** [comment]
@tmorehouse shouldn't it be 
```js
  <template v-slot:cell="scope">
```

**Comment by tmorehouse** [comment]
@mosinve oops... yeah... fingers were too quick.  Corrected the example above
