### ISSUE TITLE
tooltip inside transition problem

### ISSUE THREAD

**Issue by mike-kelly** [bootstrap-vue/bootstrap-vue#4257]
I have an element with a tooltip inside a transition, which in turn is inside another transition:

```
<transition name="cardInOut" enter-active-class="animated fadeInDown" leave-active-class="animated fadeOutLeft">
    <div :id="'card_' + id" class="card" :class="{'highlight-animation': isHighlighted}"
         v-on:animationend.self="resetHighlightedCard"
         v-show="isVisible"
         v-on:mouseenter="setIsUnderMouse(true, $event)"
         v-on:mouseleave="setIsUnderMouse(false, $event)">
      <div class="card__drag-card" v-show="isUnderMouse"></div>
      <div class="card__main">
        <transition name="fadeInOut" enter-active-class="animated fadeIn" leave-active-class="animated fadeOut">
          <div class="card__controls animated" v-show="isUnderMouse">
            <span v-for="(control, index) in controls" :key="'control'+index"
                  v-b-tooltip.hover v-bind:title="control.title"
                  class="card__control" :class="control.classObject"
                  v-on:click.prevent="controlAction(control)">
            </span>
          </div>
        </transition>
.
.
.
</transition>
```

### Error reproduction

When I mouse out from one of the elements which have tooltips on them (see element with class `card__control`), a `mouseleave` event is triggered on the grandparent element (see element with class `card`).
This happens consistently in the top card in a series of cards displayed in rows, but not on the other cards.

### Expected behavior

`mouseleave` event should only be triggered when moving the mouse outside of the grandparent element, not outside of the child.

### Versions

**Libraries:**

"bootstrap": "^4.3.1",
"bootstrap-vue": "^2.0.4",
"vue": "^2.6.10",

**Environment:**
OSX 10.14.5, Firefox and Chrome

**Comment by tmorehouse** [comment]
Note `mouseleave` is a non bubbling event (unlike `mouseout` https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event)

Could you create a minimila reproduction of the issue with JSFiddle/CodePen/CodeSandbox? you can  export from the docs playground if needed.

**Comment by mike-kelly** [comment]
I realised what the problem is. When the mouse is moved over the tooltip itself, a `mouseleave` event is triggered in the grandparent, because the tooltip is not a child of the grandparent. 

So not really a bug in the tooltip but it may affect other users if they, like me, change the visibility of the element with the tooltip, based on `mouseenter` / `mouseleave` events in an ancestor element.

My workaround was to add this css rule: 
```
  .tooltip {
    pointer-events: none;
  }
```

This codepen illustrates the problem: 
https://codepen.io/mike-kelly-the-selector/pen/vYYGowX

**Comment by tmorehouse** [comment]
You could also instruct the tooltip to append to a different container than the default of body (i.e. set container to the card div)

**Comment by mike-kelly** [comment]
Thanks, I will look into that.

**Comment by tmorehouse** [comment]
For the directive version, the `container` is specified via a config object passed to the directive:

https://bootstrap-vue.js.org/docs/directives/tooltip#directive-syntax-and-usage
