### ISSUE TITLE
Tooltip position error inside container with 100% height

### ISSUE THREAD

**Issue by jonathan-faulch-flexya** [bootstrap-vue/bootstrap-vue#4264]
### Describe the bug

When using a tooltip within a container with a height of 100%, the tooltip is incorrectly positioned.

Upon moving the mouse over the tooltip target element, the tooltip is shown and positioned slightly off center to the left as shown:
![image](https://user-images.githubusercontent.com/39695573/66923956-097d2580-f02a-11e9-8f7c-97b5a1254251.png)

Upon moving the mouse off of the tooltip target element, the tooltip begins to fade and its position snaps to the center:
![image](https://user-images.githubusercontent.com/39695573/66924060-3cbfb480-f02a-11e9-92c5-4550b22aedee.png)

### Steps to reproduce the bug

1. Open the demo below
2. Alternate between moving the mouse over and off the button
3. See error

### Expected behavior

The tooltip should be consistently positioned in the center while moving the mouse over and off the target element.

### Versions

**Libraries:**

- BootstrapVue: 2.0.4
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: MSI MS-179E
- OS: Windows 10 Version 1903 Build 18362.418
- Browser: Google Chrome
- Version: 77.0.3865.120 (Official Build) (64-bit)

### Demo link

[JSFiddle](https://jsfiddle.net/w0f4qjag/)

```html
<!DOCTYPE html>
<html>
  <head>
    <link type="text/css" rel="stylesheet" href="https://unpkg.com/bootstrap@4.3.1/dist/css/bootstrap.min.css"/>
    <link type="text/css" rel="stylesheet" href="https://unpkg.com/bootstrap-vue@2.0.4/dist/bootstrap-vue.css"/>
    
    <script src="https://unpkg.com/vue@2.6.10/dist/vue.js"></script>
    <script src="https://unpkg.com/bootstrap-vue@2.0.4/dist/bootstrap-vue.js"></script>
    
    <style>
      html, body, #app, .container {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="app">
      <div class="container">
        <b-button id="button">button</b-button>
        <b-tooltip target="button" title="tooltip" placement="bottom"></b-tooltip>
      </div>
    </div>
    
    <script>
      new Vue({el: '#app'});
    </script>
  </body>
</html>
```

### Additional context

While attempting to figure out whether this was a bug in normal bootstrap or in bootstrap-vue, I've found a different, but likely related bug in normal bootstrap. While attempting to create a comparable demo, I've come up with the following:

[JSFiddle](https://jsfiddle.net/9cfLthkz/)

```html
<!DOCTYPE html>
<html>
  <head>
    <link type="text/css" rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <style>
      html, body, .container {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="bottom" title="tooltip">button</button>
    </div>
    
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      });
    </script>
  </body>
</html>
```

It has a similar issue, in which the tooltip is incorrectly positioned (off center) when initially displayed. However the issue differs, in that it remains in its initial incorrectly displayed position when fading out.

Clearly there is a bug in normal bootstrap for this reason. However, my inability to successfully recreate the original bug in normal bootstrap suggests evidence (though of course doesn't prove) that there is also a bug in bootstrap-vue as well.

It may very well be possible that a fix to the related but slightly different normal bootstrap bug will inadvertently fix the bootstrap-vue bug. If you think this warrants opening up a separate bug in normal bootstrap's issue tracker, I would be happy to do so.

This bug is being posted here because it is more "noticeable" than the normal bootstrap bug (since it "wiggles" rather than staying still), and also does seem to be at least somewhat distinct.

**Comment by jonathan-faulch-flexya** [comment]
While it may be a bug in popper.js, I feel it's worth noting that this issue doesn't appear to be present when using the popover component instead of the tooltip component. Since both use popper.js for displaying their content, this at least offers some evidence that it may still be an issue with bootstrap-vue and/or normal bootstrap.

### Working popover demos

#### Bootstrap-vue example

[JSFiddle](https://jsfiddle.net/0wcmueqn/)

```html
<!DOCTYPE html>
<html>
  <head>
    <link type="text/css" rel="stylesheet" href="https://unpkg.com/bootstrap@4.3.1/dist/css/bootstrap.min.css"/>
    <link type="text/css" rel="stylesheet" href="https://unpkg.com/bootstrap-vue@2.0.4/dist/bootstrap-vue.css"/>
    
    <script src="https://unpkg.com/vue@2.6.10/dist/vue.js"></script>
    <script src="https://unpkg.com/bootstrap-vue@2.0.4/dist/bootstrap-vue.js"></script>
    
    <style>
      html, body, #app, .container {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="app">
      <div class="container">
        <b-button id="button">button</b-button>
        <b-popover target="button" triggers="hover" placement="bottom">popover</b-popover>
      </div>
    </div>
    
    <script>
      new Vue({el: '#app'});
    </script>
  </body>
</html>
```

#### Normal bootstrap example

[JSFiddle](https://jsfiddle.net/p97183m2/)

```html
<!DOCTYPE html>
<html>
  <head>
    <link type="text/css" rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <style>
      html, body, .container {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <button type="button" class="btn btn-secondary" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-content="popover">button</button>
    </div>
    
    <script>
      $(function () {
        $('[data-toggle="popover"]').popover();
      });
    </script>
  </body>
</html>
```

**Comment by tmorehouse** [comment]
What is weird is that the only differences between popover and tooltip is the structure of the tip/popover content, as everything else is shared code (approx 98% is shared code)

**Comment by RuneHanssens** [comment]
Any update on this issue? I also have this problem but I don't use custom css where I put height 100%. I use the tooltip on a button in a b-tab element. I tried testing out with min-height but that workaround doesn't seem to work in my case.

**Comment by RipkensLar** [comment]
I am experiencing this error as well, but I don't set height to 100%.

**Comment by tmorehouse** [comment]
Related issue with workaround: #5277

**Comment by tmorehouse** [comment]
See issue #5277 for a workaround.

Closing in favour of issue #5277
