### ISSUE TITLE
edge of button not working

### ISSUE THREAD

**Issue by EiloBlack** [bootstrap-vue/bootstrap-vue#4265]
In my `b-modal` I got two div elements with` slot='modal-ok' ` and ` slot='modal-cancel' ` that serve as Buttons. Both work fine, except that the 'OK-Button' seems to have something like a dead frame/edge arount it.  So if you don't click the center of the Button but the edge, the click-event will not fire. 

![button](https://user-images.githubusercontent.com/48051652/66935424-3cc8b000-f03c-11e9-87db-3007df1bb0f8.PNG)

this is my modal 

```
<b-modal
              id="showExportDialog"
              title="Exportattribute wählen"
              cancel-variant="outline-primary"
            >
              Ihr gewähltes Format: <strong> {{ exportFormat.toUpperCase() }} </strong> <br>
              Bitte wählen sie die gewünschten Exportattribute für die Datensätze <br>
              Sie haben folgende Attribute gewählt {{ selectedCheckboxValues }}
              <div id="selectAllCheckboxes">
                <b-form-checkbox
                  v-model="allCheckboxesSelected"
                  :indeterminate="indeterminate"
                  aria-describedby="exportCheckbox"
                  aria-controls="exportCheckbox"
                  @change="toggleAllCheckboxes()"
                >
                  {{ allCheckboxesSelected ? 'Alle Abwählen' : 'Alle Auswählen'}}
                </b-form-checkbox>
                <b-form-checkbox-group
                  id="exportCheckbox"
                  v-model="selectedCheckboxValues"
                  :options="tableHeader"
                  stacked>
                </b-form-checkbox-group>
              </div>
              <div slot="modal-ok" @click="exportSearchresults()">
                <i class="fa fa-check"></i> OK
              </div>
              <div slot="modal-cancel" @click="cancel()">
                <i class="fa fa-times"></i> Abbrechen
              </div>
            </b-modal>
```

I already tried to change the div element to `button ` or `b-button` but neither seems to work.

It would be great if the button would trigger the click() event, even if you miss the middle of it

**Comment by tmorehouse** [comment]
The slots `modal-ok` and `modal-cancel` are for the _content placed inside_ the built in footer buttons. They do not replace the built in buttons.

The built in buttons have the events `ok` and `cancel` (triggering the `ok()` and `cancel()` methods respectively).

In your case, you are placing click handlers on the _content of the buttons_, and not be buttons themselves.

Either:

- remove the click handlers on your slot content, and listen for hte built in events `ok` and `cancel` to run your handler methods,
- or use the `modal-footer` slot to place your own buttons in the footer with your own click handlers

**Comment by EiloBlack** [comment]
Thanks a lot for this super fast reply!
I removed the click handlers and listen to the built in events now and it works great!
Awesome :)
