### ISSUE TITLE
Adding multiple buttons with dropdowns results in a btn-group class being added

### ISSUE THREAD

**Issue by rjacques** [bootstrap-vue/bootstrap-vue#4266]
Hi,

Please check the fiddle: https://jsfiddle.net/7axtqc8y/

When I add three dropdown buttons, the HTML will render automatically with a  class of `btn-group `which results in a horizontal layout of the buttons (because `inline-flex` is rendered).

How can I have the 3 buttons as per above fiddle but prevent the additional `btn-group` class added?

Thanks!

**Comment by tmorehouse** [comment]
Dropdown trigger buttons are always rendered as an inline element (just like a button is an inline element). Button group class is always added to each wrapper element.

Are you looking to have each dropdown on a separate line?

If so, then add a wrapper div around each dropdown.  The div will force each dropdown to be on a new line.

**Comment by rjacques** [comment]
Thank you very much. I think wrapping the button in a <div> is a good workaround!
