### ISSUE TITLE
Tooltip does not hide immediately when triggering element is hidden

### ISSUE THREAD

**Issue by mike-kelly** [bootstrap-vue/bootstrap-vue#4268]
### Describe the bug

When clicked, an element with a `v-b-tooltip` has a class applied to it which causes it to be hidden (e.g. `d-none`). The tooltip which was displayed when the mouse was over the element is not immediately hidden. The tooltip is displayed briefly at browser co-ords 0,0 before disappearing.

### Steps to reproduce the bug

1. Go to https://codepen.io/mike-kelly-the-selector/pen/dyypowv
2. Mouse over grey div
3. Click on 'Edit Card' pencil icon
4. Tooltip moves to top left of screen before disappearing.

### Expected behavior

Tooltip should be hidden at the same time as the element.

### Versions

**Libraries:**

"bootstrap": "^4.3.1",
"bootstrap-vue": "^2.0.4",
"vue": "^2.6.10",

**Environment:**

- Macbook Pro
- macOS: 10.14.5
- Chrome
- Version 77.0.3865.90

**Comment by Hiws** [comment]
If you instead of hiding the element using `d-none`, use a `v-if` you get the expected behavior
https://codepen.io/Hiws/pen/rNNMOXz

**Comment by tmorehouse** [comment]
Testing for visibility (i.e. display none) is not a simple task... we had to add in an interval (which runs at 100ms intervals) that periodically checks to see if the trigger element is still visible.  this is the delay you are seeing.

As @hiws mentioned, `v-if` would be your best bet as the directive knows immediately when the element is on is removed from the DOM

**Comment by mike-kelly** [comment]
OK, thanks both!
