### ISSUE TITLE
Table custom slot problem

### ISSUE THREAD

**Issue by happilymarrieddad** [bootstrap-vue/bootstrap-vue#427]
Hey guys, I'm trying to iterate over my objects in the table. It works but I get this weird error in the console. Everything works great though. I'm assuming it's looping over the "field" in the v-for and there is something going on in the background that's trying to access a property/item that is not there.

Here is my code
![selection_203](https://cloud.githubusercontent.com/assets/6416323/26267266/6ba5493e-3ca6-11e7-9e6d-ecde1af1f888.png)
![selection_204](https://cloud.githubusercontent.com/assets/6416323/26267269/754b80ac-3ca6-11e7-8f9e-b20ca5f4c828.png)
![selection_205](https://cloud.githubusercontent.com/assets/6416323/26267278/80196846-3ca6-11e7-8613-6c05dd1261a5.png)

**Comment by tmorehouse** [comment]
It looks like you re using `field` (which is an object) to define your slot name on line 12.  Use the `key` variable (which is a string)

**Comment by tmorehouse** [comment]
Also are you using the latest release or the current master?

**Comment by tmorehouse** [comment]
Also, if you are providing the items array list to `b-table` you don't need to make  slot filler for each, so most likely you don't need to `templat(v-for...` part at all.  The slots are basically for "virtual items" that aren't in your items array (i.e. computed columns), which are identified in your fields object.

**Comment by tmorehouse** [comment]
Check out PR #433

I've added some clarity and improved example for scope slots. I know the documentation (and scoped slots) confused me a bit, so I've updated it to make usage more clear.

**Comment by tmorehouse** [comment]
@happilymarrieddad how is the custom field slot rendering working for you now?

**Comment by tmorehouse** [comment]
@happilymarrieddad check out the lates doc updates for table https://github.com/bootstrap-vue/bootstrap-vue/blob/master/docs/components/table/README.md

This might help clarify a few things.

**Comment by happilymarrieddad** [comment]
Thanks man!
