### ISSUE TITLE
 <b-table> loaded event

### ISSUE THREAD

**Issue by edgar949** [bootstrap-vue/bootstrap-vue#4270]
I'm trying to add some custom validation to  input fields inside table rows, the rows are generated dynamically after selecting and ID somewhere else. 

the problem is the custom validation will not work because the rows are not created yet.

is there and event that I can check after the to a dd some validation after the data loads?

thanks

**Comment by tmorehouse** [comment]
If using scoped field slots, use a custom component as the slot content and hook into that custom component's `mounted()` hook.
