### ISSUE TITLE
Add a way to prevent tabs switching

### ISSUE THREAD

**Issue by vincentdh** [bootstrap-vue/bootstrap-vue#4273]
### Is your feature request related to a problem? Please describe...

I have a b-tabs with form in b-tab.  If the form isn't saved before the tab is switch, I would like to prevent the tabs from switching to an other tab

### Describe the solution you'd like

An event could be fired before changing the tab and preventDefault() or return false could stop the tab switching process

**Comment by vincentdh** [comment]
I've though using v-model and verify if the form is saved and return to the tab if not, but if the tabs are "lazy" the component is destroyed and the form will be lost before you returned to the tab.

**Comment by tmorehouse** [comment]
You can set the `disabled` prop to true on tabs that users shouldn't be able to access until certain criteria is met.

For accessibility reasons, it is best to present the user with a disabled tab button then one that is clickable but doesn't do anything (as `event.preventDefault()` is not relayed back to the user via any feedback).

**Comment by vincentdh** [comment]
For convenience, I would like to alert my user that the form isn't saved and ask if they want to save/continue editing/discard changes and depending the choice they made, let them switch tabs.

**Comment by tmorehouse** [comment]
BootstrapVue `v2.1.0` has been released, which has added the ability to prevent tabs from changing.

**Comment by timoteo7** [comment]
Can you show any example, please ?

how i call `bvEvent.preventDefault()` ?

What do I do after this?

`<b-tabs @activate-tab.prevent >`

and do not receive this:
`$event.preventDefault is not a function`

I did not understand by the documentation, I'm obviously doing something wrong

**Comment by rubebop** [comment]
> For convenience, I would like to alert my users that the form isn't saved and ask if they want to save/continue editing/discard changes and depending the choice they made, let them switch tabs.

I have the exact same use case and had the exact same questions as @timoteo7.
Did someone figured this out?

**Comment by rubebop** [comment]
I found a working example here:
https://stackoverflow.com/a/60369824/7894940

**Comment by cmyk-bedraggled** [comment]
Check this https://theophilus-penicillin.github.io/python-appium/ explanation
