### ISSUE TITLE
b-input-group-button's tooltip shows when mouse hovering over b-dropdown.

### ISSUE THREAD

**Issue by hifall** [bootstrap-vue/bootstrap-vue#4279]
### Describe the bug

I use b-input-group-button to create a dropdown panel, and assign a tooltip to the button.

The code looks like:

```
<b-input-group-button
                    class="input-group-append"
                    slot="right"
                    v-b-tooltip.hover
                    :title="$t('ShowFilters')"
            >
              <b-dropdown right>
                <div class="filter-panel">
...
```

The tooltip shows fine when I hover over b-input-group-button. However, after the dropdown appears, whenever I hover over it, the tooltip appears as well, possibly due to the dropdown being a child of the b-input-group-button.

### Steps to reproduce the bug

1. create the page;
2. click to reveal the dropdown;
3. hover over the dropdown;
4. the tooltip appears.

### Expected behavior

I expect the tooltip to NOT show up when I hover over the dropdown.

### Versions

**Libraries:**

- BootstrapVue: 1.4.1
- Bootstrap: 4.0.0
- Vue: 2.5.13

**Environment:**

- Device: Macbook Pro
- OS: macOS Sierra
- Browser: Chrome
- Version: 77

**Comment by tmorehouse** [comment]
I'm not sure what `<b-input-group-button>` is, as it is not one of our components.

**Comment by tmorehouse** [comment]
Also note that BootstrapVue 1.4.1 is a very old release that is no longer supported.

You should be upgrading to 2.0.4 of BootstrapVue and 4.3.1 of Bootstrap
