### ISSUE TITLE
multiple toggle buttons in the same row <b-table>

### ISSUE THREAD

**Issue by tomjdickson** [bootstrap-vue/bootstrap-vue#4282]
### Describe the bug
When using multiple buttons in a row of a b-table the buttons are not acting on their own and they instead get synced with each other.
For example when you click "Show Details" on one column it will also toggle the button in the next column.

### Steps to reproduce the bug
```
<template>
    <div>
        <b-table :items="blah" :fields="blahFields">
                    <template slot="column2" slot-scope="compartmentrow">
                        <b-button size="sm" @click="compartmentrow.toggleDetails" class="mr-2">
                        {{ compartmentrow.detailsShowing ? 'Hide' : 'Show'}} Details
                        </b-button>
                     </template>
                     <template slot="row-details" slot-scope="compartmentrow">
                         <b-table striped hover :items="compartmentrow.item.column2" class="table-fix">
                             <template slot="show_details" slot-scope="r">
                                 {{ r.compartment }}
                             </template>
                         </b-table>
                    </template>

                    <template slot="column3" slot-scope="loadSummaryRow">
                        <b-button size="sm" @click="loadSummaryRow.toggleDetails" class="mr-2">
                        {{ loadSummaryRow.detailsShowing ? 'Hide' : 'Show'}} Details
                        </b-button>
                     </template>
                     <template slot="row-info" slot-scope="loadSummaryRow">
                         {{loadSummaryRow.item}}
                    </template>
        </b-table>
    </div>
</template>
<script>
export default {
    name: 'example',
    data () {
        return {
            blah: [
                column1: "blah",
                column2: [
                    {
                        subcolumn1: 'data',
                        subcolumn2: 'data'
                    {
                ],
                column3: [
                    {
                        subcolumn1: 'data',
                        subcolumn2: 'data'
                    {
                ],
            ],
            blahFields: [
                "column1", "column2", "column3"
            ]
        }
    }
}
```

### Expected behavior

Multiple buttons in the same row but seperate column can toggle different things.

### Versions

**Libraries:**

- BootstrapVue: ^2.0.0-rc.28
- Bootstrap: ^4.1.3
- Vue: ^2.5.17

**Environment:**

- Device: [e.g. Mac or iPhone X] Macbook Pro
- OS: [e.g. macOS Mojave or iOS 12] MacOS 10.15
- Browser: [e.g. Chrome] Chrome
- Version: [e.g. 70] Latest

**Comment by tmorehouse** [comment]
There can only be one "row-details" slot.  The same slot is used for the row, and regardless of how it is triggered (or from which cell), the same slot will be opened and it will receive the same `items` object (all data from that row).

This is expected behaviour.

You would need to use some state variable to instruct your `row-details` slot to show different data.  either via setting a variable on the row data when clicking the button, or storing the state in an extrenal array so each row's details slot know what sub data you would like to show.

**Comment by tomjdickson** [comment]
Thanks
