### ISSUE TITLE
Can't resolve 'bootstrap-vue/es/components/popover/popover'

### ISSUE THREAD

**Issue by alexeydg** [bootstrap-vue/bootstrap-vue#4291]
ERROR  Failed to compile with 1 errors                                                                                               10:40:56 AM

This dependency was not found:

* bootstrap-vue/es/components/popover/popover in ./node_modules/click-confirm/dist/click-confirm.common.js

To install it, you can run: npm install --save bootstrap-vue/es/components/popover/popover
    
ERROR in ./node_modules/click-confirm/dist/click-confirm.common.js
Module not found: Error: Can't resolve 'bootstrap-vue/es/components/popover/popover' in '/home/vagrant/code/ticket/node_modules/click-confirm/dist'
 @ ./node_modules/click-confirm/dist/click-confirm.common.js 7:31-85
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/order.scss ./resources/sass/app_public.scss

**Comment by ktechmidas** [comment]
How did you fix this?

**Comment by amerioca** [comment]
Same Issue, still at a loss
