### ISSUE TITLE
Passing fields into b-table as object

### ISSUE THREAD

**Issue by kirill-voronov** [bootstrap-vue/bootstrap-vue#4292]
Hello! 
Can't find any reason this feature was removed in 2.0 stable release

> b-table: passing an object as a fields definition will no longer work. Use the array of strings or array of objects (or a combination of the two) fields definition format instead.

Can you please explain? 
Passing fields as object is much more convenient then using "key" property of certain field object

**Comment by tmorehouse** [comment]
The order the keys re returned from an object is not guaranteed... which can cause SSR hydration errors  if the field order computed on the server is different than on the client.
