### ISSUE TITLE
./build issue

### ISSUE THREAD

**Issue by mathlet0x** [bootstrap-vue/bootstrap-vue#43]
Hi,

I encounter an issue when i use ./build script. I tested on Linux / Windows and i get the same result for each components : 

`
ERROR in ./components/components.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./tooltip.vue in [PATH]\bootstrap-vue\components
resolve file
[PATH]\bootstrap-vue\components\tooltip.vue.js doesn't exist
[PATH]\bootstrap-vue\components\tooltip.vue.vue doesn't exist resolve directory
[PATH]\bootstrap-vue\components\tooltip.vue\package.json doesn't exist (directory description file)
[PATH]\bootstrap-vue\components\tooltip.vue is not a directory (directory default file)
[[PATH]\bootstrap-vue\components\tooltip.vue.js]
[[PATH]\bootstrap-vue\components\tooltip.vue.vue]
` 

I made some research, and i found a solution here : [https://github.com/webpack/webpack/issues/981](https://github.com/webpack/webpack/issues/981)

As other people, i just changed `extensions: ['.js', '.vue'],` by `extensions: ['', '.js', '.vue'],` in the webpack.js file and it solve this little issue.

Do other people encounter this issue ? And if it is, don't we have to put temporaly this little fix into our webpack.js file ?

**Comment by nddery** [comment]
What's your local version of Webpack ? Adding an empty string may also cause [Getting error: configuration.resolve.extensions[0] should not be empty](https://github.com/webpack/webpack/issues/3043).

Do you get the error if you run `yarn build` (or `npm run build`) from the root directory ? Running the script directly would try and use a global webpack if available (and fail otherwise).

**Comment by mathlet0x** [comment]
My local version is 1.14.0, when i use npm run build i get another error : 

`ERROR in Entry module not found: Error: Can't resolve 'babel' in '/home/mbaran/github/bootstrap-vue'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders. You need to specify 'babel-loader' instead of 'babel'.`

**Comment by nddery** [comment]
You won't be able to compile with webpack 1.x.x, using the build command from package.json will ensure you're using the right version. However, seems there's been a breaking change in [webpack 2.1.0-beta.26](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.26). We just need to add `-loader` to all loaders in the webpack configs.

**Comment by mathlet0x** [comment]
@nddery Thanks mate, you're right ! it seems to come from my webpack version. I close this issue ;)
