### ISSUE TITLE
Stacked table: can't vertically align [data-label] with b-select

### ISSUE THREAD

**Issue by garymcm** [bootstrap-vue/bootstrap-vue#4303]
Is it possible to vertically align the data label with the `b-select`? I think it would look better with `vertical-align: middle`. 

https://jsfiddle.net/08mpnzoh/10/

**Comment by tmorehouse** [comment]
You would need to target the `td[data-label]::before` pseudo element with custom CSS to change the alignment or padding-top

**Comment by tmorehouse** [comment]
Or use a few Bootstrap utility padding and margin-classes to compensate:

https://jsfiddle.net/b1zuLe60/

**Comment by garymcm** [comment]
Thank you.

**Comment by Hiws** [comment]
You can also apply the classes `d-flex align-items-center` to your td to achieve the same result.

https://jsfiddle.net/exz4bgvc/

**Comment by tmorehouse** [comment]
But note if using `d-flex` on a native `<td>` (instead of on a `<b-td>`) you will need to add the appropriate ARIA `role` (i.e. `cell`) on the `<td>` as the css `display` will change the semantic meaning of the `<td>` for screen reader users.
