### ISSUE TITLE
<b-form-checkbox> 

### ISSUE THREAD

**Issue by ravipatel6** [bootstrap-vue/bootstrap-vue#4308]
### Describe the bug

**<b-form-checkbox @changed="setIndeterminate" v-model="checked" :indeterminate.sync="notCompleted"/>**

is not working for IE and other browser is working fine.

can you please help me out for this.

**Comment by tmorehouse** [comment]
You may need to use a nextTick to handle changing the indeterminate state, due to how Vue batches updates in data/state (and the interval can be a bit different with older browsers like IE).

```js
{
  data() {
    notCompleted: true
  },
  methods: {
    setIndeterminate() {
      this.$nextTick(() => {
        this.notCompleted = true
      })
    }
  }
}
```

**Comment by ravipatel6** [comment]
Thanks @tmorehouse 

Now, i can see Indeterminate is display perfectly fine in IE but while you click on checkbox its become blank checkbox and checkbox is not taking @chnage event while click on first time but second time its working fine.

**Comment by tmorehouse** [comment]
Could you create a JSFiddle to reproduce the issue?  You can export to JSFiddle from the [docs playground](https://bootstrap-vue.js.org/play)
