### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by ravipatel6** [bootstrap-vue/bootstrap-vue#4310]
Component : Form Checkbox Inputs , Table ...
Issue : I am trying to access https://bootstrap-vue.js.org/docs/components but in IE so many live example are not working

**Comment by tmorehouse** [comment]
This is because many of the live examples are using ES6 syntax in the templates (the HTML portion). we transpile the `<script>` sections (using babel runtime compiler), but unfortunately we can't transpile the inline javascript in the HTML portion of the example templates.

**Comment by ravipatel6** [comment]
I am trying to confirm this bug we are experiencing on IE is version specific. i will tested locally with updated version let you know.
