### ISSUE TITLE
b-form-select - add placeholder prop

### ISSUE THREAD

**Issue by profispojka** [bootstrap-vue/bootstrap-vue#4311]
### Is your feature request related to a problem? Please describe...
The default way of creating "placeholder" for b-form-select is to use option with null value. I cant use this, because I would have to retype my typescript interfaces.

### Describe the solution you'd like
The ideal solution would be to add placeholder prop that would be visible if the property i am changing is undefined. Under the hood it could work similarly to current option(value="null")

### Describe alternatives you've considered
I have considered making the option with value undefined, that doesnt work. But it would also be feasible solution for my problem. I have also considered changing the select component specifically for my project, but I think I am not the only one who has this problem, so multiple people could benefit from implementing this inside bootstrap vue.

### Additional context
I am using the latest bootstrap vue on my project.

**Comment by tmorehouse** [comment]
The main issue would be that `<b-form-select>` is just a wrapper for the native `<select>` element, and is subject to it's limitations, as well as how Vue handles `<select>` elements tied to a v-model.

As well, with the case of selects with the `multiple` attribute would pose a problem to handle (as multiple selects are always tied to an array for the v-model.

Thirdly, mobile browsers show the select list differently (when opened).

The suggested method is to create a `disabled` `<option>` as the _first_ option, with the option's value set as `''`  (the empty string) as recommended by the [Vue guide](https://vuejs.org/v2/guide/forms.html#Select).  Note that we suggest setting the value to match the default value of your v-model value (in our examples we are using `null`, as the v-model default value is `null` (which can be easily checked for non-truthiness).

**Comment by tmorehouse** [comment]
with the upcoming b-dropdown-select (not sure of the name at the moment), which will not be a native select element, will will be possible to provide a "placeholder".  But for `<b-form-select>` this probably will not be possible since its root element is a native HTML `<select>` element (and as such is limited to the features of a native `<select>`)

**Comment by tmorehouse** [comment]
Closing in favour of the new custom select component coming in a future release.
