### ISSUE TITLE
Add variant to b-form-checkbox and b-form-checkbox-group

### ISSUE THREAD

**Issue by ianfoulds** [bootstrap-vue/bootstrap-vue#4312]
I need to display checkbox components in other variant colours than just primary.

I would like the checkbox components to support the 'variant' attribute as well as the currently implemented 'button-variant' attribute.

Currently there is no clean way of doing this unless I implement some non-standard CSS rules and add a class attribute to the components.

Hack CSS to implement a 'success' variant:
```
div.custom-checkbox.success label::before,
div[role="group"].success div.custom-checkbox label::before {
    color: #fff!important;
  background-color: #28a745!important;
  border-color: #28a745!important;
}
```

And in the component definition:
```
<b-form-checkbox-group
    v-model="myDataItem"
    :options="myItemList"
    class="success">
</b-form-checkbox-group>
<b-form-checkbox class="success" :checked="true">YACB</b-form-checkbox>
```

**Comment by tmorehouse** [comment]
Try applying the text variant utility classes to the component... such as `text-info` to change the color of the text in the labels.

Unfortunately the custom checkboxes/radios/switches use Bootstrap SVG backgrounds which are defined in Bootstrap's CSS, and are not controlled by BootstrapVue.
