### ISSUE TITLE
Alien attributes are not passed to the checkbox element in b-form-checkbox-group

### ISSUE THREAD

**Issue by ianfoulds** [bootstrap-vue/bootstrap-vue#4313]
You cannot pass alien attributes to the checkbox element within a b-form-checkbox-group component. The following component definition applies the 'class' attribute to the 'group' div and not the underlying checkbox inputs. This may or may or may not be by design but there is no way of passing attributes to the input elements.

To reproduce the problem, define a checkbox group thus:
`<b-form-checkbox-group class="success" v-model="selectedItems" :options="items"></b-form-checkbox-group>
`

I would have expected any alien attributes, class in this instance, to be applied to the checkbox elements. These are, after all, the elements that are visible and have a user impact. 
### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Comment by tmorehouse** [comment]
The child checkboxes automatically use the v-model of the parent `<b-form-checkbox>` group, so it is not really that :wild" of an idea.  This is the reason we provided this feature (the default slot of the group), to allow greater control over the rendered child checkboxes.

**Comment by tmorehouse** [comment]
```js
export default {
  data() {
    return {
      // Pre-check the values
      value: [ 1, 2, 3, 4 ],
      // Options array
      options: [
        { value: 1, text: 'One', attrs: { foo: 'bar' } },
        { value: 2, text: 'Two', attrs: { } },
        { value: 3, text: 'Three', attrs: { foo: 'baz' } },
        { value: 4, text: 'Four', attrs: { } }
      ]
    }
  }
}
```

```html
<template>
  <b-form-checkbox-group v-model="value">
    <b-form-checkbox
      v-for="option in options"
      :key="option.value"
      :value="option.value"
      v-bind="option.attrs"
    >{{ option.text }}</b-form-checkbox>
  </b-form-checkbox-group>
</template>
```

**Comment by tmorehouse** [comment]
In some user use cases, the users may want the "foreign" attributes to be applied to the component's (group's) root element. So blindly passing all no-prop attributes to the child input elements (rendered by the built in options array) may not always desirable.

**Comment by ianfoulds** [comment]
Hi Troy, I still think the following is a lot more succinct and intuitive. I agree the slot provides a great deal of flexibility but for most simple operations, such as applying a class to the checkboxes, it is way over the top.

Do you not agree that this is far easier to implement and understand?
`<b-form-checkbox-group v-model="value" :options="options" class="myCHeckboxClass">`

**Comment by tmorehouse** [comment]
Note `class` and `style` attributes will only apply to the root element of the component they are applied to and cannot be transfered to a child element/component. This is a Vue limitation (https://vuejs.org/v2/api/#inheritAttrs)

**Comment by ianfoulds** [comment]
inheritAttrs=false; on the root element

$attrs on the checkbox.

**Comment by tmorehouse** [comment]
Applying `class` to the root element of a component will only apply the class(es) to the root element of the component.

**Comment by ianfoulds** [comment]
OK, we are going off on a tangent here which, although connected, is distracting form my original point.  I probably should have been a little more specific in that I indeed wanted to apply a class attribute to the checkboxes, which I fully understand will not get passed through. My original point was that I would have expected foreign attributes to have been applied to the visible elements of the checkbox group - the checkboxes. I understand that some people may want them applying to the group but personally it seems more intuitive that they be applied to the visible elements.

Given that you have some sort of deep seated objection to this idea, is this because of a standard you have applied throughout? How about adding a checkbox-class attribute, you already have a button-class attribute for the side case of rendering buttons, why not the mainstream use class? This would make the usage of the checkbox group far more succinct in a majority of usage cases. Having to do weird stuff in slot just to apply a class to the checkboxes is not nice.

**Comment by tmorehouse** [comment]
One cannot create a prop called `class` as it would conflict with the standard attribute `class` within Vue (similar for the `style` attribute).

Your use case is exactly why we added in the option (via the default slot) to to place checkbox components within the checkbox-group component... to handle these specific use cases, and to be very flexible.

In situations were it is difficult to replace inner element functionality with slots, we have provided special props for placing classes on specific inner elements of components (typically only for class attributes an not generic "unknown" attributes).

Adding special props for these edge use cases ends up bloating the library code base size (this is what happened to tables, which now occupies around _1/3 of our total_ code base, not to mention reducing performance), when there is an easy alternative to handle these edge cases.

**Comment by tmorehouse** [comment]
>  I understand that some people may want them applying to the group but personally it seems more intuitive that they be applied to the visible elements.

Imagine the case of the attribute `id`.  should it be duplicated and applied to all child components? What if users want to apply a generic class to the root element?  Now users would require a special prop to handle that (where as most users would expect when using `class` or `style` that they values are applied to the root element (as per the standard Vue behaviour).

**Comment by ianfoulds** [comment]
OK, we are not getting anywhere are we. I understand and agree some elements of my original question are bad and I agree attributes such as id would not work.

Maybe I should start a new question regarding adding a `checkbox-class` attribute to make life simpler for IMHO a majority of usage cases. Applying a consistent style to the contained checkboxes seems like something a lot of people would want to do. Yes I agree the slot is wonderful and you can do whatever you want with it, but for simple use cases it make it unnecessarily complex.

I do disagree with what you say about a `checkbox-class` attribute being a side case, `button-variant` certainly is a side case but you have applied that! I still maintain that being able to add a class to the main visible elements of the checkbox group should be intuitive and simple, currently it is not.

The options prop is really nice and allows a simple list to be generated with ease, I really like it, usage with ease is the key here. What do most users want to do with displayed elements? Make them have a consistent look and feel!

**Comment by tmorehouse** [comment]
That is what scoped styles and deep selectors are for. I still can't understand why people are so scared of writing deep selector styles.

Re button-variant... it is a special use case that translates a theme color name to a class... I.e. `danger` is translated to class `btn-danger`. It is not the same as a prop `button-class`

**Comment by ianfoulds** [comment]
OK, I give up.
