### ISSUE TITLE
CSS minification error: postcss-svgo

### ISSUE THREAD

**Issue by icefee** [bootstrap-vue/bootstrap-vue#4319]
I got a error while building my project after I upgrade BootstrapVue to the latest version.
Error: CSS minification error: postcss-svgo: TypeError: Cannot set property 'multipassCount' of undefined.File: css/chunk-vendors.a34c12fb.css
    at g:\~\node_modules\@intervolga\optimize-cssnano-plugin\index.js:106:21

### Versions

**Libraries:**

- BootstrapVue: 2.0.4
- Bootstrap: 4.3.1
- Vue: 2.6.10

- Device: Windows 10
- OS: Windows 10

**Comment by tmorehouse** [comment]
The latest version of BootstrapVue is v2.0.4. try upgrading to the latest release (you may need to delete `node_modules` directory and `yarn.lock` (if using `yarn`)

**Comment by tmorehouse** [comment]
Also, are you using the precompiled BootstrapVue CSS or source SCSS?

**Comment by icefee** [comment]
> Also, are you using the precompiled BootstrapVue CSS or source SCSS?

No scss. I upgrade BootstrapVue to v2.0.4, and then I got the same error of "CSS minification".

**Comment by tmorehouse** [comment]
After googling the error ode, it looks like it is an upstream issue with SVGO https://github.com/svg/svgo/issues/1174

**Comment by icefee** [comment]
Thanks, I will take attention to this problem.

**Comment by nongtiny** [comment]
@icefee I encountered the same problem. Do you know the way to fix this?

I use yarn, and already followed this comment [https://github.com/svg/svgo/issues/1174#issuecomment-547658450](svg/svgo#1176), but I couldn't fix it.

Thank you.

**Comment by AnkurL1703** [comment]
> Hardcoding to SVGO version 1.3.0 appears to be a temporary fix for now.


This doesn't seem to work for me. Sadly can't get around this.

**Comment by tmorehouse** [comment]
When including Bootstrap/BootstrapVue CSS are you using the pre-minified CSS or the non-minified CSS?

**Comment by icefee** [comment]
> @icefee I encountered the same problem. Do you know the way to fix this?
> 
> I use yarn, and already followed this comment [https://github.com/svg/svgo/issues/1174#issuecomment-547658450](svg/svgo#1176), but I still couldn't fix it.
> 
> Thank you.



> @icefee I encountered the same problem. Do you know the way to fix this?
> 
> I use yarn, and already followed this comment [https://github.com/svg/svgo/issues/1174#issuecomment-547658450](svg/svgo#1176), but I still couldn't fix it.
> 
> Thank you.

https://github.com/svg/svgo/issues/1174#issuecomment-547643398
