### ISSUE TITLE
Stacked Table: cutom header/translations

### ISSUE THREAD

**Issue by aloiki** [bootstrap-vue/bootstrap-vue#4320]
For mobile devices we want to use bootstraps-vue's stacked tables because it looks much better at mobile devices and provides a better usability. 

The data fields label is used as data-label attribute and set as it's content in CSS. 
Thats fine, but how to deal with custom headers, like translations? 

It would be nice if there is a smooth way to include our translations or custom header in the data-label field.

**Comment by Hiws** [comment]
I'm not sure what you're using for translations however it's possible to dynamically change the table headers but providing a `fields` prop to the table with your header definitions.

Here's a way to do it using `vue-i18n`
https://codepen.io/Hiws/pen/oNNGdJb
