### ISSUE TITLE
BButtonClose uses different markup than Bootstrap

### ISSUE THREAD

**Issue by Trainmaster** [bootstrap-vue/bootstrap-vue#4321]
### Describe the bug

The markup of the close buttons (modal, alert) differs from the Bootstrap markup.

### Steps to reproduce the bug

The markup used in `BButtonClose` is

```html
<button type="button" aria-label="Close" class="close">&times;</button>
```

### Expected behavior

In Bootstrap it's slightly different for [modal](https://getbootstrap.com/docs/4.3/components/modal/#modal-components) and [alert](https://getbootstrap.com/docs/4.3/components/alerts/#dismissing)

```html
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
</button>
```

```html
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
</button>
```

### Versions

**Libraries:**

- BootstrapVue: 2.0.4
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Comment by jackmu95** [comment]
@Trainmaster We don't need the `data-dismiss` attribute since it's only needed for Bootstrap's JS to know which button to use to close the alert/modal.

**Comment by tmorehouse** [comment]
@Trainmaster is there any specific issue this is causing you?

**Comment by Trainmaster** [comment]
@tmorehouse No, there is no issue. I was just wondering why it differs.

So would you say that the Bootstrap markup can be simplified?

**Comment by tmorehouse** [comment]
Yeah, also depends on if people want to replace the default content of the button (via the default slot).
