### ISSUE TITLE
b-tabs with prop no-key-nav Jaws support

### ISSUE THREAD

**Issue by fabo15x** [bootstrap-vue/bootstrap-vue#4323]
When using Jaws Screen reader, a focused tab is announced as "to activate tab page press SPACEBAR" but the supported key to activate the current focused tab in the component is "ENTER" instead.
The b-tabs component should support "SPACEBAR" to select a focused tab.

**Comment by tmorehouse** [comment]
@fabo15x is this only when `no-key-nav` is set? or does it happen with key nav is enabled as well?

**Comment by tmorehouse** [comment]
Looking a the code, it appears that the issue was with no-key-nav enabled.

**Comment by tmorehouse** [comment]
BootstrapVue `v2.1.0` has been released, which has a fix for this issue.
