### ISSUE TITLE
Allow setting "cols" on horizontal form group

### ISSUE THREAD

**Issue by spaceemotion** [bootstrap-vue/bootstrap-vue#4324]
### Is your feature request related to a problem? Please describe...

I have a few form elements that don't need a lot of input. For those I'd like to specify their width in "columns". The class assigned to the content is "col", based on the `b-col` component as it seems, but there's no way to specify these properties when using the `b-form-group` component.

### Describe the solution you'd like

Maybe expose a few props from `b-col` to `b-form-group`?

### Describe alternatives you've considered

Wrapping it around nested columns, but then I have to specify custom widths per label per form group

**Comment by tmorehouse** [comment]
Prop [`label-cols` (and the respective breakpoint specific versions)](https://bootstrap-vue.netlify.com/docs/components/form-group#comp-ref-b-form-group-props) allows you to specify the number of columns that the label takes up, and the area (column) for the form-control(s) is an auto-width column that takes up the remaining space.

For the form-controls that only need to be a narrow width, you can add [Bootstrap v4.3 utility classes](https://getbootstrap.com/docs/4.3/utilities/sizing/) like `w-25` (25% of the available width) or `w-50` (for 50% of the available width) on the `b-form-input`.
