### ISSUE TITLE
Missing class show when tooltip displaying

### ISSUE THREAD

**Issue by quangdnptit** [bootstrap-vue/bootstrap-vue#4330]
Hi team, I tried to find class show when tooltip displaying but not found anything !!, this is the difference between boostrap-vue and bootstrap? if true, how can I **add class show** when the tooltip is displaying? please help!!

My current version
    "bootstrap": "^4.2.1",
    "bootstrap-vue": "^2.0.0-rc.20",
please see below:
boostrap-vue
![image](https://user-images.githubusercontent.com/31880059/67919271-53414080-fbd2-11e9-9e2c-01ba4851f232.png)
boostrap: 
![image](https://user-images.githubusercontent.com/31880059/67919378-ae733300-fbd2-11e9-9aed-aec9479b3168.png)

**Comment by tmorehouse** [comment]
This is a know "issue"/"workaround" in BootstrapVue.  

We had to implement a bit of custom SCSS/CSS to make Bootstrap v4.3.x's classes work with Vue's `<transition>` component.  The show class is only applied during the transition period.

Make sure you are using BootstrapVue v2.0.4 (or greater), Bootstrap v4.3.1 CSS/SCSS or greater, and ensure that you are including BootstrapVue's custom CSS in your project (after loading Bootstrap's CSS).

**Comment by quangdnptit** [comment]
yeah, thank for your support !!

**Comment by tmorehouse** [comment]
@quangdnptit does upgrading and including BootstrapVue CSS fix your issue?

**Comment by Joontae-Kim** [comment]
Hi everyone! Thank you for all bootstrap-vue team! 
I have a same problem. i followed [the above tmorehouse 's advice](https://github.com/bootstrap-vue/bootstrap-vue/issues/4330#issuecomment-548213677), but, it doesn't fixed. My current version is already fitted. 

![image](https://user-images.githubusercontent.com/12801238/67921678-cacf9980-fbeb-11e9-97c3-e95c58e6fb87.png)

but it didn't work. then, i added the `show` class to **tooltip** class myself. i attach the before & after adding `show` class.

before added,
![image](https://user-images.githubusercontent.com/12801238/67921768-269a2280-fbec-11e9-9051-318623c97bd4.png)

after,
![image](https://user-images.githubusercontent.com/12801238/67921784-331e7b00-fbec-11e9-83f4-8c4862c94f56.png)

**Comment by tmorehouse** [comment]
@Joontae-Kim make sure you are including BootstrapVue's custo CSS (or SCSS) in your project after you load Bootstrap v4.3.1's CSS (or SCSS)

**Comment by Joontae-Kim** [comment]
@tmorehouse Thanks! wait a minute! I look forward to fixing it!

**Comment by Joontae-Kim** [comment]
@tmorehouse I'm so sorry. bootstrap-vue `index.scss` 's importing order was wrong. I solved!
Thank you @tmorehouse !

![image](https://user-images.githubusercontent.com/12801238/67922596-87c2f580-fbee-11e9-9d35-928007557147.png)
