### ISSUE TITLE
Popover directive as a method does not receive argument

### ISSUE THREAD

**Issue by d4mn** [bootstrap-vue/bootstrap-vue#4331]
### Describe the bug

In documentation it says that a directive as a function should receive argument with reference to element: "A function reference to generate the content of the popover (receives one argument which is a reference to the DOM element triggering the popover)"
But none is received i got undefined

### Steps to reproduce the bug

`<b-img :key="index" v-b-popover.hover="zoomImage" v-bind="thumbProps" left :src="item" alt="Image 1"></b-img>`

`methods:{
        zoomImage(el) {
            console.log(el);
            return '<img src="'+el.src+'">';
        }
    }`

### Expected behavior

Should receive reference to get content from hovered element

### Versions
**Libraries:**

- BootstrapVue: 2.0.4
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Comment by tmorehouse** [comment]
This might have been changed with the re-write of tooltips/popovers for version 2.0.0 (and the docs not correctly updated).

Also note, when returning the content as an HTML string, you need to set the `.html` modifier on the directive.

**Comment by d4mn** [comment]
Yes, i found another solution with events but for code sanity will use this fix as I intended:) Thanx!

**Comment by tmorehouse** [comment]
BootstrapVue `v2.1.0` has been released, which has a fix for this issue.
