### ISSUE TITLE
Question: which Bootstrap Sass for BDropdown and BDropdownItem?

### ISSUE THREAD

**Issue by lukenofurther** [bootstrap-vue/bootstrap-vue#4338]
Hi,

First off let me say this is a great project and I admire the work put into it.

I'm trying to use the BDropdown and BDropdownItem components in my own Vue components and only want to import what's necessary for those components specifically and individually rather than the entirety of the Bootstrap (and BoostrapVue) Sass. Which individual Sass files does each of the BDropdown and BDropdownItem components need for proper styling?

**Comment by jackmu95** [comment]
Use the following imports:
```scss
// Bootstrap styles
@import 'node_modules/bootstrap/scss/bootstrap';

// General BootstrapVue stuff
@import "node_modules/bootstrap-vue/src/variables";
@import "node_modules/bootstrap-vue/src/utilities";

// Dropdown stuff
@import 'node_modules/bootstrap-vue/src/components/dropdown/index';
```

**Comment by lukenofurther** [comment]
I don't want to import all bootstrap styles into my component. 

How can I only import the styles needed for BDropdown or BDropdownItem?

**Comment by tmorehouse** [comment]
@lukenofurther You would need to dive into the individual files of Bootstrap SCSS.  They are somewhat modular (you do need to import all of variables, functions, mixins (and some utilities) from Bootstrap, along with their dropdown SCSS.

You can see the list of SCSS/SASS fiels for Bootstrap at: https://github.com/twbs/bootstrap/tree/v4-dev/scss

And a brief rundown of importing what you need at: https://getbootstrap.com/docs/4.3/getting-started/theming/#importing

**Comment by lukenofurther** [comment]
@tmorehouse I am importing the variables, functions and mixins already, that's fine - only what's needed is included at compile time. Do you have no idea which of the modular Bootstrap imports are needed for each of your components?

**Comment by tmorehouse** [comment]
BDropdown (an child components) need Bootstrap's `scss/_dropdown.scss` and `scss/_utilities.scss` (along with BootstrapVue's  `/src/components/dropdownindex.scss`

If you look at the directory listing at https://github.com/twbs/bootstrap/tree/v4-dev/scss you will see that Bootstrap has their SCSS organized by component

**Comment by lukenofurther** [comment]
@tmorehouse it also needs _buttons.scss. Does BDropdown really need all bootstrap utilities (450 lines of Sass)? 

How likely are you to act on a feature request to add explicit scss imports/exports to your components? Perhaps they could be added to the BootstrapVue scss file for each component, then consumers could import the one scss file to obtain all the required Sass without anything redundant.

**Comment by tmorehouse** [comment]
It uses a few margin utilities, but they probably can be left out.

Since we do not control Bootstrap's SCSS layout or definition, we do not do direct import of Bootstrap SCSS/CSS, not do we want to dissect it ourselves into smaller chunks as users may be using 3rd party Bootstrap themes, etc.  If we did, then we would get users complaining that they couldn't use the themes due to us including the default bootstrap styling in each component...

**Comment by lukenofurther** [comment]
You could provide it as an option somewhere and those other problems you mention can be solved or worked around (e.g. purify-css, not scoping, including only utilities globally). But I understand that would be some undertaking and it's your choice whether to take your library in that direction.
