### ISSUE TITLE
i am getting double tag visualization

### ISSUE THREAD

**Issue by epileftro85** [bootstrap-vue/bootstrap-vue#4342]
### Describe the bug
i am getting double tag visualization
I am creating simple forms, but visually i get double items on the screen, the code is a normal form.
### Steps to reproduce the bug
I do not know why it is.
1. Go to [...]
2. Click on [...]
3. Scroll down to [...]

### Expected behavior
Cleaner UI
No double visualization of items on screen
### Versions
"bootstrap-vue": "^2.0.0-rc.19",
"vue": "^2.6.10",

**Environment:**

- Device: [Mac]
- OS: [macOS Catalina]
- Browser: [Chrome (78.0.3904.70), Firefox (70.0.1)]

Add any other context about the bug here.

This is the Image:
https://i.stack.imgur.com/APNUD.png

**Comment by jackmu95** [comment]
@epileftro85 Please try upgrading to the latest version of BootstrapVue (v2.0.4) and when your issue is still there it would be helpful if you could create a minimal demo with your markup/code to reproduce it.

**Comment by tmorehouse** [comment]
We would need to see sample markup of you application

**Comment by epileftro85** [comment]
Nevermind, turns out my component was mounted three times and that makes the form gets weird. Sorry for this false positive.
