### ISSUE TITLE
b-table with transition not playing nice with pagination

### ISSUE THREAD

**Issue by BWagener** [bootstrap-vue/bootstrap-vue#4345]
### Describe the bug

A b-table with a -move transition applied does not look great with pagination enabled.

### Steps to reproduce the bug

1. Go to
https://stackblitz.com/edit/vuejs-starter-q6ejiq

2. Jump around using the pagination

3. The Error
You'll see twice as many rows as set in the "Per Page" setting for a very short moment whenever you change the page

### Expected behavior

Maybe prevent the transition in case of pagination? Maybe pagination is not supposed to play nice with transitions in the b-table, considering sorting won't look good either.

### Versions

**Libraries:**

 "bootstrap": "^4.3.1",
 "bootstrap-vue": "2.0.4",
 "vue": "^2.6.10"

**Environment:**

StackBlitz

### Demo link
https://stackblitz.com/edit/vuejs-starter-q6ejiq

The demo is just a combination of the 
https://bootstrap-vue.js.org/docs/components/table#table-body-transition-support example
and the 
https://bootstrap-vue.js.org/docs/components/table#complete-example example
The only addition is an ID field for the primary-key prop to make the transition work.

**Comment by tmorehouse** [comment]
This is because the transition is a `move`, and the keys for the rows are changing completely.

You would need to add in enter/leave transition classes to your transition props (and define the actions to occur on enter/leave, such as a fade or similar)

**Comment by BWagener** [comment]
Thanks. Can you check out the demo again, I've added what I think are appropriate classes and it still doesn't look well.

**Comment by tmorehouse** [comment]
You may just want to set `.flip-list-leave-to` to `display: none` and forgo the enter/leave transition duration (or set it to `0s`)

**Comment by BWagener** [comment]
Thank you!
