### ISSUE TITLE
tooltip hidden but still in document

### ISSUE THREAD

**Issue by bibodeng** [bootstrap-vue/bootstrap-vue#435]
When I use tooltip, it works, but it cover on the input, make the input can not be focused. Guess it is cause by the style of tooltip
![snip20170521_10](https://cloud.githubusercontent.com/assets/1180416/26280679/ffa2153e-3e10-11e7-91b1-6395cd2c4ef2.png)
pop up
![snip20170521_11](https://cloud.githubusercontent.com/assets/1180416/26280682/047720ea-3e11-11e7-9353-ba8dbd9adee8.png)
pop hidden but still in document
![snip20170521_14](https://cloud.githubusercontent.com/assets/1180416/26280683/07089c76-3e11-11e7-92e3-d7272565d9fb.png)
pop hidden style, display none didn't work

**Comment by tmorehouse** [comment]
So it appears that the opacity is set to 0, but the display:block!important is overriding the display:none being set on the element by the component.

**Comment by tmorehouse** [comment]
Currently tooltips are in "transition" as Bootstrap V4 and Bootstrap-vue are migrating away from `tether.js` to `popper.js`

**Comment by tmorehouse** [comment]
I'm not sure why the `!important` is required on `display`.

By adding the following CSS **after** the bootstrap-vue.css, it appears to work in some instances, but not all the time.
```css
.tooltip {
    display: initial !important;
}
```

I think we can safely remove the `display:block!important` from the component CSS
