### ISSUE TITLE
b-tabs: be able to get active tab title

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#4352]
### Is your feature request related to a problem? Please describe...

Hi, we need to load a component only when a b-tab is active.
A solution to do this would be

```
<b-tabs v-model="tabIndex" >
<b-tab title="abc">...</b-tab>
...
<b-tab title="xyz">
<my-component v-if="tabIndex == 7"></my-component>
</b-tab>
```

Problem: The number of tabs vary dynamically, and we can't tell at runtime which number is the proper tabIndex. But we know the title is "xyz"

Request: Be able to get the active tab title from tabIndex, or have another way to determine the current tab title.

### Describe the solution you'd like

```
<b-tabs @change="tabChange" >
```
tabChange(e) never triggers. Would expect that to trigger and have the index & title in event properties.

OR

```
<b-tabs ref="tabs" >
```
and have something like ```this.$refs.tabs.getTitle(tabIndex)```

**Comment by tmorehouse** [comment]
Tab titles could also be HTML or component markup, and therefore might not be simple text (i.e. if using the `b-tab` title slot).

**Comment by tmorehouse** [comment]
Perhaps you should be conditionally add `<b-tab>` components based on some condition.

```html
<b-tabs v-model="tabIndex" >
  <b-tab title="abc">...</b-tab>
  ...
  <b-tab title="xyz" v-if="someCondition" key="xyz">
    <my-component </my-component>
  </b-tab>
</b-tab
```

**Comment by mariusa** [comment]
Thanks. We need to display tabs, but load the component inside each tab only when active (to avoid, among others, triggering mounted() on all components for each tab).
User might open page, click on tab 3 and be done. No need to load all tab components and their data.

The solution suggested in other place was to use v-if on components.

**Comment by tmorehouse** [comment]
Once can also make individual `<b-tab>` components lazy via the `lazy` prop which doesn't mount the content of the `<b-tab>` until it is shown/activated.

**Comment by mariusa** [comment]
@tmorehouse This is the perfect solution! Thanks so much, I've missed this from the docs.

**Comment by tmorehouse** [comment]
we should probably add a bit more documentation on the lazy props for `<b-tabs>` and `<b-tab>`

**Comment by mariusa** [comment]
@tmorehouse I made a pull request. It's mainly with your explanatory comment :)
