### ISSUE TITLE
b-table sticky-columns don't work properly unless both `responsive` & `sticky-header` props are set

### ISSUE THREAD

**Issue by dflock** [bootstrap-vue/bootstrap-vue#4354]
### Describe the bug

b-table sticky-columns don't work properly unless both `responsive` & `sticky-header` props are set

### Steps to reproduce the bug

Here's a codepen that shows this happening: https://codepen.io/duncanlock/pen/gOOzJXO

### Expected behavior

The docs say that either will work, but both seem to be required:

> ### Sticky columns
>
> Columns can be made sticky, where they stick to the left of the table when the table has a horizontal scrollbar. To make a column a sticky column, set the stickyColumn prop in the field's header definition. Sticky columns will only work when the table has __either__ the sticky-header prop set and/or the responsive prop is set.

### Versions

**Libraries:**

- BootstrapVue: 2.0.4
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Ubuntu Linux 16.04.6 LTS x86_64 
- Browser: Chrome
- Version: 75

### Demo link

https://codepen.io/duncanlock/pen/gOOzJXO

**Comment by tmorehouse** [comment]
It appears that the classes are not being applied to the tbody sticky column cells.

There might have been a regression since this feature was introduced.

**Comment by tmorehouse** [comment]
BootstrapVue `v2.1.0` has been released, which has a fix for this issue.
