### ISSUE TITLE
<b-table> new template not working 

### ISSUE THREAD

**Issue by PaulBouisset** [bootstrap-vue/bootstrap-vue#4358]
Hello everybody,

since I update from v2.0.0-rc.22 to v2.0.4 I have issues with custom data rendering in b-table.

Before I was using :
```vue
<template slot="custom_key" scope="row">
    {{ row.item.custom_key }}
</template>
```
Now when I use the new syntax like explained in the document: 
```vue
<template v-slot:cell(custom_key)="data">
    {{ data.item.custom_key }}
 </template>
```

But I keep getting an error saying that "data" in not defined. I tried everything but keep getting the same error. This syntax seems not to work for me and I am not sure where the problem comes from. 

- BootstrapVue: 2.0.4
- Bootstrap: 4.3.1
- Vue: 2.5.22

**Comment by miladazhdehnia** [comment]
i have same issue here
i want to pass the field.key dynamically with a v-for loop like the above
`<template v-for="field in fields" v-slot:cell(field.key)="row"> 
    //anything here
    </template>`
`<template v-slot:[`cell({field.key)`]="data">
`
but its not work

**Comment by Hiws** [comment]
@miladazhdehnia 
Take a look at 
https://github.com/bootstrap-vue/bootstrap-vue/issues/4343

@PaulBouisset 
`v-slot` is a new syntax introduced in Vue `2.6.0`, so you need to upgrade your vue to use it.
`bootstrap-vue 2.0.0+` also requires vue `2.6.0` and `2.6.10` is recommended.

**Comment by PaulBouisset** [comment]
Thanks ! I did not catch that. That resolves my issue
