### ISSUE TITLE
[question] b-dropdown as regular label/link, not button

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#4359]
With bootstrap one can create a dropdown which is NOT a button:
```
<div class="dropdown">
  <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown link
  </a>
...
```

There's no example for doing this with 
https://bootstrap-vue.js.org/docs/components/dropdown/#dropdowns

I did try
```
    <b-dropdown
        toggle-tag='a'
class="myclass"
>
```
but it still renders markup with classes 'btn' and 'btn-group' (and also adds 2 class properties when I specificy a custom class)

How can one get rid of the button, please?

Thanks!

**Comment by Hiws** [comment]
You could take a look at https://bootstrap-vue.js.org/docs/components/dropdown/#hidden-caret

It will still have the btn classes, but will look like a normal link

**Comment by mariusa** [comment]
Thanks! From that example, ```variant='link'``` does the job! 

We simply want a drop-down menu similar to this v2.0.4
![Screenshot from 2019-11-08 15-06-25](https://user-images.githubusercontent.com/1283842/68478770-62ab3400-0239-11ea-8c1c-a7d16d09148f.png)

**Comment by mariusa** [comment]
Actually, this seems more suited for that:
```
<b-navbar>
        <b-navbar-nav class="ml-auto">
            <b-nav-item-dropdown ...
```
https://bootstrap-vue.js.org/docs/components/navbar
