### ISSUE TITLE
Did the bootstrap-vue have a gird system as what the bootstrap@* have?

### ISSUE THREAD

**Issue by MackieLee** [bootstrap-vue/bootstrap-vue#437]
Did the bootstrap-vue have a gird system as what the bootstrap@* have?

**Comment by alexsasharegan** [comment]
When using bootstrap-vue, you'll need to include the bootstrap 4 css in your page. You'll be able to access all the grid layout tools that bootstrap offers you: https://v4-alpha.getbootstrap.com/layout/grid/
