### ISSUE TITLE
b-popover not working in 2.0.4[was working with *.rc versions]

### ISSUE THREAD

**Issue by kinjaltMob** [bootstrap-vue/bootstrap-vue#4373]
### cant able to see popover in latest version.

It was working with older versions.

**Comment by tmorehouse** [comment]
Make sure you are including BootstrapVue's custom CSS/SCSS in your project.  It is required in order to allow Bootstrap transition css to work with Vue's `<transition>` component.

**Comment by markko1** [comment]
I didn't manage to find any hints on how to use this custom SCSS/CSS to make popover work for me. Would be grateful for any hints! :)

**Comment by tmorehouse** [comment]
Make sure you include BootstrapVue's CSS after you include Bootstrap's CSS
