### ISSUE TITLE
NPM warning when running lastest bootstrap-vue

### ISSUE THREAD

**Issue by mdr0414** [bootstrap-vue/bootstrap-vue#4374]
Got this warning when running npm script: "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"

WARNING in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/components/ScheduleTableComponent.vue
59:25-30 "export 'default' (imported as 'Table') was not found in 'bootstrap-vue/src/components/table/table'

Not sure what I need to do
Got this will after running npm update on all packages
here my package.json
"devDependencies": {
        "axios": "^0.18.1",
        "bootstrap": "^4.3.1",
        "cross-env": "^5.2.1",
        "jquery": "^3.4.1",
        "laravel-mix": "^2.1.14",
        "lodash": "^4.17.15",
        "popper.js": "^1.16.0",
        "vue": "^2.6.10"
    },
    "dependencies": {
        "@fullcalendar/core": "^4.3.1",
        "@fullcalendar/daygrid": "^4.3.0",
        "@fullcalendar/interaction": "^4.3.0",
        "@fullcalendar/moment": "^4.3.0",
        "@fullcalendar/moment-timezone": "^4.3.0",
        "@fullcalendar/vue": "^4.3.1",
        "bootstrap-vue": "^2.0.4",
        "jquery-ui": "github:jquery/jquery-ui",
        "laravel-echo": "^1.6.1",
        "moment": "^2.24.0",
        "moment-timezone": "^0.5.27",
        "portal-vue": "^2.1.6",
        "pusher-js": "^4.4.0",
        "smartmenus": "^1.1.0",
        "smartmenus-bootstrap-4": "^0.1.0",
        "vue-template-compiler": "^2.6.10"
    }

**Comment by tmorehouse** [comment]
It appears your omponent `/resources/js/components/ScheduleTableComponent.vue` is importing `BTable` incorrectly.

**Comment by mdr0414** [comment]
Thanks for the quick response..
But what is the correct import?  I haven't changed anything from the
working version that used the previous bootstrap-vue. Using webpack w/
laravel 5.7. I simply ran npm update and it broke.  Tia for reply

**Comment by tmorehouse** [comment]
@mdr0414 See the above comment

**Comment by mdr0414** [comment]
Thx... I guess I'll have to figure it out. The import did not change from
previous Vue instance import bootstrap-vue version to your latest version.

**Comment by tmorehouse** [comment]
All we can do is make a few guesses as we do not know what your code looks like.

Maybe provide a sample of `/resources/js/components/ScheduleTableComponent.vue`?
