### ISSUE TITLE
Create eslint plugin for bootstrap-vue components

### ISSUE THREAD

**Issue by dietergeerts** [bootstrap-vue/bootstrap-vue#4375]
### Is your feature request related to a problem? Please describe...

The docs state best practices, and sometimes require a prop to be given when another prop is being used. Developers tend to forget these, and we end up with usage of components that is not optimal, introduces bugs, ...

### Describe the solution you'd like

These best practices and requirements could be linted, so developers don't forget to use them during implementation.

### Describe alternatives you've considered

None, as I believe linting is the most 'correct' solution here.

### Additional context

None.

**Comment by tmorehouse** [comment]
Version 2.1.0 (coming soon), will include IDE auto-complete helper files for Vetur and Webstorm (and other IDE's that may use the `web-types.json` standard).
