### ISSUE TITLE
Question: how to make b-table abstract, slot the cell fields

### ISSUE THREAD

**Issue by cjaoude** [bootstrap-vue/bootstrap-vue#4377]
Been having a hard time with this. Still learning these more advanced Vue concepts, so excuse noob mistakes.

We want to have base-table that has filters, pagination, etc all configured so we can just re-use it. We want to be able to customize the fields though. But can't quite figure out how to make it work because of the slotting.

eg.
```
// BaseTable.vue

<b-table props...>
   <slot name="custom-fields"></slot>
</b-table>

// CustomTable.vue
<template>

    <base-table>
        <template #custom-fields>
             <template #cell(foo-field)>Customize Field</template>
        </template>
    <base-table>
</template>
```

This results in the following issue
"<template v-slot> can only appear at the root level inside the receiving the component."

 Insight to make this work appreciated. Thanks.

**Comment by tmorehouse** [comment]
Try something like this:

```html
// BaseTable.vue

<b-table props...>
   <template v-for="( slotFn, slotName ) in $scopedSlots" v-slot[slotName]="data">
     <slot :name="slotName" v-bind="data"></slot>
   </template>
</b-table>

// CustomTable.vue
<template>
    <base-table>
       <template #cell(foo-field)>Customize Field Foo</template>
       <template #cell(bar-field)>Customize Field Bar</template>
    </base-table>
</template>
```

This will pass down **all slots** of `<base-table>`  to `<b-table>`

**Comment by cjaoude** [comment]
Thanks, that worked.
