### ISSUE TITLE
Nested Accordion Support

### ISSUE THREAD

**Issue by rmad17** [bootstrap-vue/bootstrap-vue#4378]
I was trying to create a nested accordion and when I click on the child accordion it collapses the parent accordion. I am just confused if this library supports nested accordion or I am doing something wrong.

**Comment by rmad17** [comment]
It was a mistake on my part. The parent and child accordions had same name. Closing this,

**Comment by Geeta-Singh** [comment]
@rmad17 Can you please help me to implement nested collapse.
