### ISSUE TITLE
Documentation for customizing

### ISSUE THREAD

**Issue by torstenzander** [bootstrap-vue/bootstrap-vue#438]
Could please provide some documentation on what ist the recommended way to customize bootsrap-vue,

**Comment by alexsasharegan** [comment]
What kind of customizations are you looking to do? Any examples in particular?

**Comment by torstenzander** [comment]
just simple things like changing colors, margins and paddings.

**Comment by tmorehouse** [comment]
That would be using bootstrap v4 css modifier classes, or using a bootstrap css theme file.

**Comment by alexsasharegan** [comment]
Well, most of the components don't really have predefined settings there (apart from what is already native to bootstrap 4).

For spacing, refer to [this section of the BS4 docs](https://v4-alpha.getbootstrap.com/utilities/spacing/). You can just add those utility classes to your components like so:

```vue
<!-- .h-100 for height: 100%; -->
<!-- .my-3 for margin-top & margin-bottom (y-axis) 1rem -->
<!-- .p-0 for padding: 0; -->
<b-card :header="'true'" show-footer class="h-100 my-3 p-0">
    <!-- content -->
</b-card>
```

For colors, [here is the BS4 colors guide](https://v4-alpha.getbootstrap.com/utilities/colors/). This lib generally uses the prop name `variant` to toggle between those primary, secondary, info, warning, & danger colors. To customize those, I recommend grabbing the BS4 **sass** files, and using their [customization options guide](https://v4-alpha.getbootstrap.com/getting-started/options/) for some tips on how to set up your own colors via those variant names.

**Comment by torstenzander** [comment]
ok thanks for the fast reply. I didn't know that the customization is via bootstrap.

**Comment by alexsasharegan** [comment]
Yeah, think of this as Vue implementation of the Bootstrap 4 component library. The boilerplate markup for BS components is abstracted into the vue components. You get a lot of great features too—common use case patterns are supported for things like tables, alerts, modals, and more. AND the whole thing removes the need for jQuery (which BS4 normally relies upon). Tether.js is still needed though.

That kind of came off like a sales pitch, but as someone who used to author bootstrap 3 components in Backbone.js, this is a dream.

**Comment by neovive** [comment]
I was experimenting today with a vue-cli project and was able to customize color settings via Sass as follows:

* install webpack sass-loader and node-sass
```npm install sass-loader node-sass --save-dev```

* You can remove the Bootstrap CSS import from main.js (```import 'bootstrap/dist/css/bootstrap.css'```) since it will be recompiled from the Sass source.

* Import custom Sass variables and complete Bootstrap Sass source into App.vue for compiling. You can also import your custom Sass files after the Bootstrap import or import in your Vue components directly (if needed).
```scss
<style lang="scss">
  $body-bg: green;  // find these variables in docs and in Bootstrap _variables.scss
  @import "~bootstrap/scss/bootstrap";  // import complete bootstrap.scss source from node_modules using ~ alias
</style>
```

**Comment by alexaandru** [comment]
The above comment should be added to the docs. Worked like a charm :) Thank you @neovive !

**Comment by alexmeia** [comment]
Great work @neovive , thank you!

**Comment by rachaelnelson** [comment]
Wow, @neovive's "You can remove the Bootstrap CSS import from main.js" <-- key step. Amazing little note--thank you.
