### ISSUE TITLE
form helper component: getting duplicate attribute data-v-xxxxxx

### ISSUE THREAD

**Issue by jenemde** [bootstrap-vue/bootstrap-vue#4380]
### Describe the bug

If I add a form helper component (b-form-invalid-feedback or b-form-text) the rendered html gets a duplicate attribute data-v-xxxxxx which causes a W3C validation error

### Steps to reproduce the bug

The code looks like this (template for an input field):

```html
<template>
    <div class="form-group">
        <label for="firstname"First name</label>
        <b-form-input
            id="firstname"
            v-model="firstname"
            class="u-size-korea"
            type="text"
            name="firstname"
            state=null
            required="required"
        />
        <b-form-text>
            Helptext
        </b-form-text>
        <b-form-invalid-feedback
            Error message
        </b-form-invalid-feedback>
    </div>
</template>
```

If I replace the helper components with tags like div or small, the error does not appear, the rendered tag gets one attribute data-v-xxxxx only. I don't know if it is a bug or if something is wrong with the code.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Bootstrap: 4.1.3
- Vue: 2.6.10

**Environment:**

- Device: Desktop-PC
- OS: Windows 10
- Browser: Firefox
- Version: 70.0.1
- Browser: Chrome
- Version: 78.0.3904.97

**Comment by tmorehouse** [comment]
There appears to be a typo in your code above...

```html
        <b-form-invalid-feedback
            Error message
        </b-form-invalid-feedback>
```

Is missing a `>`:

```html
        <b-form-invalid-feedback>
            Error message
        </b-form-invalid-feedback>
```

**Comment by jenemde** [comment]
Sorry, that was a copy-paste error. The closing bracket is existing :)

**Comment by tmorehouse** [comment]
Also, try updating to BootstapVue v2.1.0 (the latest version), as there were some bugs in the `2.0.0-rc##` releases.

**Comment by jenemde** [comment]
Thanks for the tip, but unfortunately an update to v2.1.0 doesn't help, the validation error/duplicate attribute still occurs.

**Comment by tmorehouse** [comment]
Possible upstream issue:

- https://github.com/vuejs/vue/issues/10837
