### ISSUE TITLE
:busy and :tbody-tr-class as b-table params at the same time

### ISSUE THREAD

**Issue by livexaj664** [bootstrap-vue/bootstrap-vue#4381]
### Describe the bug

When using parameters :tbody-tr-class and :busy in b-table, :busy stage will be ignored and the table will be completely loaded without indication from this parameter.

`<b-table :busy="isBusy" :items="tableData" :fields="tableFields" :tbody-tr-class="rowClass">`

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.3.1
- Vue: 2.5.2

**Comment by Hiws** [comment]
https://codepen.io/Hiws/pen/rNNZbQX

Made a quick test, and it seems like `isBusy` is working fine when used with `tbody-tr-class`

However, this potentially have to do with your outdated version of `vue`.
As stated [here](https://bootstrap-vue.js.org/docs) the required version of `vue` is `v2.6` and above

**Comment by livexaj664** [comment]
Sorry, you're right. There was an error in function "rowClass" that prevented the table from being rendered until the data was updated. I.e. the problem was not in a combination of these parameters.
