### ISSUE TITLE
When using b-form-file to upload an image, is it possible to preview the image prior to uploading it?

### ISSUE THREAD

**Issue by vesper8** [bootstrap-vue/bootstrap-vue#4382]
I'm making an 'avatar upload' using `b-form-file` and would like to show a preview of the selected image before it's sent to the server.

https://stackoverflow.com/questions/4459379/preview-an-image-before-it-is-uploaded provides some possible answers but I was hoping there may be an easier way, perhaps this functionality is already baked-in but I couldn't find a mention of it in the docs

**Comment by jackmu95** [comment]
@vesper8 This example should help you out: https://codesandbox.io/s/bootstrapvue-image-preview-before-upload-xgj8s

**Comment by vesper8** [comment]
thanks! that's great!

**Comment by tmorehouse** [comment]
@vesper8 Note you might have issues with really large images and some browsers which have a limit on the length of a data  URI in the `<img>` `src` attribute.

But basically you can use the same method @jackmu95 provided to read the image file, but then pass the image to a `<canvas>` to process the file and scale it down in dimensions to get a "thumbnail" image as a data URI.

**Comment by dosstx** [comment]
@tmorehouse Would you be able to take @jackmu95's code example from above and then provide an example of passing the image to a `<canvas>` to process the file and scale it down in dimensions to get a "thumbnail" image as a data URI? I'm having the issue of too large of a data URI.

**Comment by Allislove** [comment]
> @ vesper8 Tenga en cuenta que puede tener problemas con imágenes realmente grandes y algunos navegadores que tienen un límite en la longitud de un URI de datos en el `<img>` `src`atributo.
> 
> Pero básicamente puede usar el mismo método que @ jackmu95 proporcionó para leer el archivo de imagen, pero luego pasar la imagen a un `<canvas>`para procesar el archivo y reducirlo en dimensiones para obtener una imagen en "miniatura" como un URI de datos.



> @vesper8 Note you might have issues with really large images and some browsers which have a limit on the length of a data URI in the `<img>` `src` attribute.
> 
> But basically you can use the same method @jackmu95 provided to read the image file, but then pass the image to a `<canvas>` to process the file and scale it down in dimensions to get a "thumbnail" image as a data URI.

How to do it with Canvas?
