### ISSUE TITLE
b-form-select text-field does not support nesting

### ISSUE THREAD

**Issue by sprocket99** [bootstrap-vue/bootstrap-vue#4385]
Not sure if this is classed as a bug or feature request. But I cannot get this to work:

`<b-form-select :options="students" text-field="name.first" value-field="id" />`

It displays "undefined" in the drop down. The reason is because the `text-field` of `first` is not a direct property of a firmware object. Is the only way of making this to somehow make new objects with the properties at the top level? That would be very inconvenient.

In this example, `students` is an array, with a property `name` with sub props `first` and `last`.

I am using version 2.0.4

**Comment by Hiws** [comment]
As a workaround you can create the options yourself using a `v-for`

```html
<b-select v-model="selected">
  <option v-for="student in students" :value="student.id">{{ student.name.first }}</option>
</b-select>
```

**Comment by sprocket99** [comment]
Thanks @Hiws Ill use that workaround for now, I have been avoiding it because VS shows a green sqiggly:

![image](https://user-images.githubusercontent.com/52204959/68858550-3120e580-06dd-11ea-9ff0-26fb1ea23b86.png)

**Comment by tmorehouse** [comment]
BootstrapVue v2.2.0 has been released.
