### ISSUE TITLE
[button] Undefined css class `.btn-inactive`

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#439]
I'm working on putting together test coverage for the button component, and I came across [the `inactive` prop](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/button.vue#L56-L59) and it's [accompanying class](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/button.vue#L28). I've searched through the BS4 css and docs, but I don't see this `.btn-inactive` class defined.

Is it safe to remove and PR along with the test coverage?

**Comment by pi0** [comment]
Hi alex. It seems being deprecated so i think is safe as it not exists even in alpha6 release!
