### ISSUE TITLE
b-nav-item to doesn't work with subdirectories

### ISSUE THREAD

**Issue by cliffordh** [bootstrap-vue/bootstrap-vue#4390]
### Describe the bug

I am using b-nav-item and the :to property for routing. This works perfectly fine for most cases, however, I've discovered that if I have a route with a folder/directory then the route is not generated. I am using this with Nuxt.

### Steps to reproduce the bug

            <b-nav-item
              class="d-none d-md-block"
              :to="{ 'name': '/folder/page' }"
            >
              <span class="btn pr-0 text-dark">Does Not Work</span>
            </b-nav-item>

### Expected behavior

The b-nav-item should generate a link to /folder/page.

### Versions

Latest

**Comment by tmorehouse** [comment]
Is your route named `/folder/page`?

Perhaps you are looking for:

```html
        <b-nav-item
          class="d-none d-md-block"
          :to="{ path: '/folder/page' }"
        >
          <span class="btn pr-0 text-dark">Folder / Page</span>
        </b-nav-item>
```
Named routes must be defined in your route object passed to Vue-router
