### ISSUE TITLE
Models not synced on conditional stuff inside v-model

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [bootstrap-vue/bootstrap-vue#4393]
### Is your feature request related to a problem? Please describe...

![GIF](https://user-images.githubusercontent.com/9306996/69011681-af53e500-0986-11ea-93aa-bd027992af03.gif)

### Describe alternatives you've considered

Maybe add validator function, which should be called before update local value inside component?

### Additional context

```js
<template>
  <b-container fluid>
    <b-form-input v-model="newValue" type="number" min="0" max="5"></b-form-input>
    <input type="number" v-model.number="newValue"></input>
 </b-container>
</template>

<script>
  export default {
    data() {
      return {
        currentPage: 1
      }
    },
    computed:{
         newValue:{
           get: function(){return this.currentPage;},
           set: function(value){
             if(!Number.isInteger(value)){
                /*  let old = this.currentPage;
                  this.currentPage=0;
                  this.currentPage=old; */
                  return;
             }
             this.currentPage=value
            }
         }
    }
 }
</script>
```
https://bootstrap-vue.js.org/docs/components/form-input

I think it's general issue with proxying v-model stuff.

**Comment by afwn90cj93201nixr2e1re** [comment]
@jackmu95

**Comment by afwn90cj93201nixr2e1re** [comment]
So, seems like vue bootstrap never gonna support this?
![изображение](https://user-images.githubusercontent.com/9306996/69011742-34d79500-0987-11ea-971e-66a9ab6a0875.png)

**Comment by tmorehouse** [comment]
Use the `number` modifier prop on `<b-form-input>` to emulate the behaviour of hte v-model number modifier:

```html
<b-form-input v-model="newValue" type="number" number min="0" max="5"></b-form-input>
```

**Comment by afwn90cj93201nixr2e1re** [comment]
It's not fixing issue. Sorry.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, the only one way is using default inputs
![изображение](https://user-images.githubusercontent.com/9306996/69013070-8be46680-0995-11ea-8928-1e7f5c1cecc3.png)

**Comment by tmorehouse** [comment]
One can type in non numerical characters in plain `<input type="number">`

Note your example has the number modifier on the plain input but i not using the number prop on b-input.

**Comment by afwn90cj93201nixr2e1re** [comment]
I get u, but the main issue was about desync on v-model with conditions(setters/getters): 
![изображение](https://user-images.githubusercontent.com/9306996/69013242-5771aa00-0997-11ea-84fd-198f0a1e866a.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
@tmorehouse now you can port it into bootstrap.

https://github.com/vuejs/vue/issues/5847#issuecomment-557664964
