### ISSUE TITLE
Tooltip memory leaks

### ISSUE THREAD

**Issue by horvayev** [bootstrap-vue/bootstrap-vue#4400]
### Describe the bug

Hi, I have found a memory leak caused by tooltip directive.

### Steps to reproduce the bug

1. Create buttons with tooltip directive
2. Delete buttons from DOM
3. Take snapshot - detached HtmlInputElement and others remain in memory

Bug is probably in https://github.com/bootstrap-vue/bootstrap-vue/blob/f1ed0177c20f9d7e7e340a8815d1b6bc66f7cb76/src/components/tooltip/helpers/bv-tooltip.js#L722

### Versions

**Libraries:**

- BootstrapVue: 2.0.4
- Vue: 2.6.10

### Demo link
[CodeSandbox](https://codesandbox.io/s/boostrapvue-table-refresh-urhid?fontsize=14&hidenavigation=1&theme=dark)

<img width="1105" alt="mem_prof" src="https://user-images.githubusercontent.com/4464147/69098263-83a12f80-0a58-11ea-9769-8f75af69e2a4.png">

I would appreciate if you could take a look, as we  heavily use tooltips and popovers in our production app. 

Thank you.

**Comment by jackmu95** [comment]
@horvayev Can you please try to recreate your CodeSandbox in the Playground of the deployment preview and confirm that the memory leak is fixed?
https://5dd39f9c82c27d000c4e3c57--bootstrap-vue.netlify.com/play

**Comment by horvayev** [comment]
Thank you, memory leak seems to be resolved. When do you expect new version to be released?

**Comment by jackmu95** [comment]
@horvayev Have to talk with @tmorehouse  about ist but I think at the least by the end of the week.

**Comment by kebus01** [comment]
Hi, when do you expect to release new version with this fix? We would really appreciate if the patch came out as soon as possible because the memory leak causes great inconvenience in our production app.

**Comment by jackmu95** [comment]
@kebus01 We hope to have v2.2.0 out by the end of the week!

**Comment by tmorehouse** [comment]
BootstrapVue v2.2.0 has been released.
