### ISSUE TITLE
b-table field visibility

### ISSUE THREAD

**Issue by ddzobov** [bootstrap-vue/bootstrap-vue#4406]
### Is your feature request related to a problem? Please describe...

I want to display shorter variant of table. 
Now i need to create different component or create different fields array.

### Describe the solution you'd like

New internal property in object at fields array named "_visible"

**Comment by Hiws** [comment]
While having it built-in would be nice, you can easily create it yourself using a computed property without having to create a new component or fields array.

https://codepen.io/Hiws/pen/WNNPVve

**Comment by tmorehouse** [comment]
An easier way is to to set the [field's `class` property](https://bootstrap-vue.js.org/docs/components/table#field-definition-reference) to `d-none`

https://codepen.io/tmorehouse/pen/RwwdNQd

**Comment by Hiws** [comment]
@tmorehouse 
Doesn't using `d-none` mean the columns still get inserted into the dom lowering performance on actions like filtering, pagination and such?

**Comment by tmorehouse** [comment]
True, but it maintains semantic column indexes for screen readers

**Comment by Hiws** [comment]
Makes sense. I've never worked with screen readers before, so my knowledge there is limited.
Would this solution be the "best" of both then, or is it simply over complicating things for no reason?

https://codepen.io/Hiws/pen/xxxBbea

**Comment by tmorehouse** [comment]
The only thing not quite right is that the `aria-colcount` attribute on the `<table>` element needs to remain at `4` (and it currently decrements each time a field is hidden)

Re filtering: b-table always looks at the content of the entire row

**Comment by Hiws** [comment]
That makes sense. I don't have an experience working with screen readers, so my knowledge there is limited.
However, would this solution be the best of both examples then? Or is it simply over complicating things for no reason.

https://codepen.io/Hiws/pen/xxxBbea

**Comment by tmorehouse** [comment]
The only thing not quite right is that the `aria-colcount` attribute on the `<table>` element needs to remain at `4` (and it currently decrements each time a field is hidden)

Re filtering: b-table always looks at the content of the entire row (except when filter-exclude-fields is used)
