### ISSUE TITLE
Don't know how to use items provider for table with vuex

### ISSUE THREAD

**Issue by oussama-he** [bootstrap-vue/bootstrap-vue#4407]
I'm building an app using VueJS with bootstrapVue for frontend and Django for backend. I'm using v-table and I would like to use pagination and I don't know how to achieve this. Below are portions of code:
```vue
<template>
<b-pagination
        v-model="currentPage"
        :totalRows="totalRows"
        :per-page="perPage"
    ></b-pagination>
    <b-table
      current-page="currentPage"
      per-page="perPage"
      :items="itemsProvider"
    >
    </b-table>
</template>
<script>
export default {
data() {
    return {
      perPage: 10,
      totalRows: 200,
      pageOptions: [5, 10, 22],
      currentPage: 1,
}
  },
  computed: {
    books() {
      return this.$store.getters["books/books"].filter(item => {
        return item.status == 'AR'
      });
    }
  },
  methods: {
    ...mapActions({
      getArchivedBooks: "books/getArchivedBooks"
    }),
    itemsProvider(ctx) {
      let page =  ctx.currentPage
      this.getArchivedBooks(page).then(()=> {
        const items = this.books
        callback(items)
      })
      return null
    },
...
}
</script>
```
Store
```js
const actions = {
...
getArchivedBooks ({commit}, page) {
      return bookService.fetchArchivedBooks(page)
      .then((data) => {
        commit('setArchivedBooks', data.results)
      })
    },
...
}
const mutaions = {
...
setArchivedBooks (state, books) {
      state.books = books
    },
...
}

...
```
Service
```js
...
export default {
fetchArchivedBooks (page) {
    return axios.get(`books/archived-books/?page=${page}`)
    .then(response => response.data)
  },
...
}
```
In the terminal I get
```
[BootstrapVue warn]: b-table provider function didn't request callback and did not return a promise or data

Uncaught (in promise) ReferenceError: callback is not defined
```
Can anyone help me, please?

**Comment by tmorehouse** [comment]
Your items provider function is calling `callback`, but it does not have callback listed as the 2nd argument.

Undefined Error: `Uncaught (in promise) ReferenceError: callback is not defined`

And since the provider didn't have the 2nd argument (callback) defined, and returns null, you get the error: `[BootstrapVue warn]: b-table provider function didn't request callback and did not return a promise or data`

Add callback as the second argument:

```js
    itemsProvider(ctx, callback) { // <- callback needs to be added here
      let page =  ctx.currentPage
      this.getArchivedBooks(page).then(()=> {
        const items = this.books
        callback(items)
      })
      return null
    }
```

**Comment by oussama-he** [comment]
Thank you for your answer, now I haven't errors in the console, but the items don't appear in the table.

**Comment by tmorehouse** [comment]
It is most likely that `const items = this.books` is returning old data and the store hasn't updated yet.

```js
    itemsProvider(ctx, callback) { // <- callback needs to be added here
      let page =  ctx.currentPage
      this.getArchivedBooks(page).then(()=> {
        this.$nextTick(() => {
          const items = this.books
          callback(items)
        })
      })
      return null
    }
```

**Comment by oussama-he** [comment]
still doesn't work.

**Comment by tmorehouse** [comment]
Perhaps you should add a few console log statements in your code to see if the store getter is actually returning data along the various points.

**Comment by oussama-he** [comment]
I added a console log in getters in my store, and I have one in itemsProvider. I get the items in the console when the page reloaded or first opened.

**Comment by oussama-he** [comment]
Thank you, I fixed it. I change this `callback(items)` to `return items || []` and delete this line `return null`

**Comment by oussama-he** [comment]
@tmorehouse when I click buttons of pagination component the `currentPage` changes, should the `itemsProvider` function recalled automatically?

**Comment by tmorehouse** [comment]
It should be (unless you have `no-provider-paging` enabled)

**Comment by oussama-he** [comment]
I didn't enable it. And the function didn't recalled.
