### ISSUE TITLE
Remove caret from form select

### ISSUE THREAD

**Issue by xerroxcopy** [bootstrap-vue/bootstrap-vue#4410]
I have a form select of which the selected value is refreshed every n-seconds. What i would like to do is to blend the form select in to the text, without distracting the reader. 
To achieve that, I want to remove the caret, padding, and the border edge. I could achieve the latter two with css, but the caret still stays. I would like to remove it just as I can with dropdown menus (`no-caret`). 
How can I achieve this?

**Comment by tmorehouse** [comment]
`<b-form-select>` is a native browser `<select>` element, and as such, has limitations on how it can be styled via CSS across browsers. (note dropdown is based on buttons and uses CSS to create the caret).

Perhaps you should change your select to a `<span>` when not focused or hovered by the user?

**Comment by xerroxcopy** [comment]
Thank you so much for your help. I worked around this issue by wrapping the `<select>` as shown in https://gist.github.com/joaocunha/6273016#gistcomment-1249243. Hope this could be also implemented as `no-caret` for `<b-form-select>` in the future.

**Comment by tmorehouse** [comment]
One other option you could try is to create a custom class to apply to the select, which remove's Bootstrap's background SVG:

```css
select.custom-select.no-select-caret {
  background: none;
}
```

And then apply the class as needed like so:

```html
<b-form-select class="no-select-caret">
```

**Comment by xerroxcopy** [comment]
Ah great, it worked and it's much easier! thank you.
