### ISSUE TITLE
Popover triggers focus occasionally throws error

### ISSUE THREAD

**Issue by thrazu** [bootstrap-vue/bootstrap-vue#4411]
### Describe the bug

The environment:

Vue.js 2.6.10
Electron 2.0.18
Node 8.9.3
Platform linux

In my scenario I have a button which triggers a popover:
```
<b-nav-item id="popover-button-variant">Options</b-nav-item>
```
And this is the popover:
```
        <b-popover 
            target="popover-button-variant"
            triggers="focus"
        >
            <!-- show some text here -->
            <!-- button which triggers a modal -->
            <b-btn @click.stop="showConfig = true">Config</b-btn>
        </b-popover>
```
Everything works good sometimes: when the modal button is pressed, the modal shows and the popover disappear. So from time to time, after doing some clicks on the modal trigger button, then close the modal, close the popover and replay the procedure I'm getting this error:

```

[Vue warn]: Error in v-on handler: "TypeError: Cannot read property '$el' of undefined"

found in

---> <BTr>
       <BTbody>
         <BTable>
           <SystemInformation> at src/renderer/components/Main/SystemInformation.vue
             <BVPopoverTemplate>
               <BVPopover>
                 <BPopover>
                   <Ev> at src/renderer/App.vue
                     <Root>
warn @ vue.esm.js?a026:628
logError @ vue.esm.js?a026:1893
globalHandleError @ vue.esm.js?a026:1888
handleError @ vue.esm.js?a026:1848
invokeWithErrorHandling @ vue.esm.js?a026:1871
invoker @ vue.esm.js?a026:2188
original._wrapper @ vue.esm.js?a026:7559


```

**Comment by tmorehouse** [comment]
Could you create a minimal reproduction JSFiddle or CodePen? you can create a JSFiddle/Codepen from the docs playground.

Also what version of BootstrapVue are you using?

**Comment by thrazu** [comment]
`"bootstrap-vue": "^2.1.0"`
Cannot reproduce this right now. but will try it in the next days.

**Comment by thrazu** [comment]
It seems like the problem is elsewhere. When the popover shows it also renders another component which imports some libraries like os, vue/package.json etc. The problem is precisely in this component, named SystemInformation.vue.
I also reproduced the scenario in CodePen and works well. Sorry for this report. This issue can be closed.

**Comment by thrazu** [comment]
Pff. After doind more tests I'm coming up again with the same problem :). Please take a look at this.

[https://codepen.io/razvan-theodor/pen/OJJqewZ?editors=1011](url)

If you click Options, Config, then close the modal, do again the same thing for 1-5 times, you will get an error. It seem that the problem is with **the table** inside the popover.

**Comment by tmorehouse** [comment]
Ah, this is the table hover event issue (issue #4384).  Which was fixed in PR #4388 and will be available in release 2.2.0 which is coming soon.

**Comment by thrazu** [comment]
Oh. Thank you! What a headache with this bug. Spend a lot of time with it :1234:

**Comment by tmorehouse** [comment]
A workaround option is to replace the table with either b-table-simple (which doesn't have the row hover events), or  something like a list group (which would be much more lightweight):

```html
<b-list-group class="small">
  <b-list-group-item class="d-flex border-0 p-1">
    <span>Path</span><span class="ml-auto">1</span>
  </b-list-group-item>
  <b-list-group-item class="d-flex border-0 p-1">
    <span>Route Name</span><span class="ml-auto">2</span>
  </b-list-group-item>
  <b-list-group-item class="d-flex border-0 p-1">
    <span>Vue.js</span><span class="ml-auto">3</span>
  </b-list-group-item>
  <!-- Etc, etc... -->
</b-list-group>
```

**Comment by thrazu** [comment]
Thank you. I've already switched to a list-group approach.
