### ISSUE TITLE
can't modify form select background color for focus object in dropdown menu

### ISSUE THREAD

**Issue by piLeoni** [bootstrap-vue/bootstrap-vue#4413]
### Describe the bug

Hi, can't get rid of the blue background on the form-select dropdown menu on the hover choice.
It always stay blue.

### Expected behavior

I would like to control that color.

### Versions
2.1.0
**Libraries:**

"@tweenjs/tween.js": "^18.4.2",
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.1.0",
    "canvas": "^2.6.0",
    "core-js": "^3.3.2",
    "perlin-noise-3d": "^0.5.0",
    "three": "^0.110.0",
    "tumult": "^3.0.14",
    "vue": "^2.6.10",
    "vue-router": "^3.1.3",
    "vuedraggable": "^2.23.2",
    "vuex": "^3.0.1"

### Demo link

custom.scss
```
/* Color Theme Swatches in RGBA */
$telephoon-1-rgba: rgba(5, 5, 15, 1);
$telephoon-2-rgba: rgba(58, 173, 150, 1);
$telephoon-3-rgba: rgba(3, 163, 123, 1);
$telephoon-4-rgba: rgba(22, 170, 108, 1);
$telephoon-5-rgba: rgba(54, 247, 170, 1);

$font-size-base: 0.7rem;
$input-btn-padding-y: 0.1rem;
$input-btn-padding-x: 0.1rem;
$input-btn-focus-width: 0;
$input-btn-focus-color: 0;
$input-btn-focus-box-shadow: 0;

$white: $telephoon-1-rgba;
$gray-100: $telephoon-1-rgba;
$gray-200: $telephoon-1-rgba;
$gray-300: $telephoon-2-rgba;
$gray-400: $telephoon-2-rgba;
$gray-500: $telephoon-3-rgba;
$gray-600: $telephoon-3-rgba;
$gray-700: $telephoon-4-rgba;
$gray-800: $telephoon-4-rgba;
$gray-900: $telephoon-5-rgba;
$black: $telephoon-5-rgba;

$primary: $telephoon-2-rgba;
$secondary: $telephoon-2-rgba;
$success: $telephoon-2-rgba;
$info: $telephoon-2-rgba;
$warning: $telephoon-2-rgba;
$danger: $telephoon-2-rgba;
$light: $telephoon-2-rgba;

@import "node_modules/bootstrap/scss/bootstrap";
@import "node_modules/bootstrap-vue/src/index.scss";
```

**Comment by tmorehouse** [comment]
The dropdown hover/active colors are controled by:

- ` $dropdown-link-active-color` (for text)
- `$dropdown-link-active-bg` (for background)

https://github.com/twbs/bootstrap/blob/6b7ca1234bb5c699804d09126585f317000d1c78/scss/_variables.scss#L758-L788

https://github.com/twbs/bootstrap/blob/6b7ca1234bb5c699804d09126585f317000d1c78/scss/_dropdown.scss#L120-L170
