### ISSUE TITLE
IE 11 + Bootstrap vue focusable elements in b-modal gets multiple lines around it

### ISSUE THREAD

**Issue by SridhanyaG** [bootstrap-vue/bootstrap-vue#4422]
### IE 11 / Edge browser we can see multiple lines around the input elemet
As when we move focus around the elements an animation effect is shown and the lines reside for ever around the component and make it unusable
### Steps to reproduce the bug
1) save this sample html code in your machine as html file (https://raw.githubusercontent.com/SridhanyaG/bootstrapvueissue/master/VueBootstrapVue.html)
or download the attachment file [(VueBootstrapVue.html)]and open in IE 11
2) Open it in IE 11
3) Open modal and start moving focus using mouse or hover and can see the issue
![IE Issue](https://user-images.githubusercontent.com/17043940/69520038-88e30a80-0f81-11ea-94da-0584948d53dc.png)

### Expected behavior

If a temporary workaround is given to turn of these animations would help
### Versions

**Libraries:**

- BootstrapVue: https://unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js (2.x)
- Bootstrap: https://unpkg.com/bootstrap/dist/css/bootstrap.min.css (4.x)
- Vue: https://unpkg.com/vue@latest/dist/vue.js (2.x)

**Environment:**
IE 11

### Demo link
https://raw.githubusercontent.com/SridhanyaG/bootstrapvueissue/master/VueBootstrapVue.html and save it as html to open in IE11

**Comment by Hiws** [comment]
I tried testing it locally in IE11, but doesn't appear to have any issues with effects staying.

Version: 11.476.18362.0

https://i.imgur.com/yKWQOY4.mp4

**Comment by SridhanyaG** [comment]
The above screenshot was from IE 11 windows 7 (11.0.9)
Below is the screenshot of issue replicated in windows 10 (IE => 11.64) and (Edge => 
![IE11(windows10)](https://user-images.githubusercontent.com/17043940/69539095-ce1b3280-0fa9-11ea-89bb-b8963482dfa7.png)
![Edge](https://user-images.githubusercontent.com/17043940/69539096-ce1b3280-0fa9-11ea-906d-7872793b27f5.png)

41.16)
I think you need to use tabs 
Re iterating steps to replicate the problem
focus on textbox click tabs and can see multiple lines like the screenshot

**Comment by tmorehouse** [comment]
I cannot recreate the issue in IE11/Win7.  Tried with multiple tabs as well.

Do you have any 3rd party extensions in IE that may interfere?

**Comment by SridhanyaG** [comment]
This issue is replicable in multiple machines in our organization. Further now i did try Reset Internet Explorer settings in IE and i was able to replicate easily
Please download this sample file https://raw.githubusercontent.com/SridhanyaG/bootstrapvueissue/master/VueBootstrapVue.html and try once
steps
1) open and click on the text field and then use tab button to navigate.

**Comment by tmorehouse** [comment]
What is the content of `css/nux/css/nux.min.css`?

**Comment by tmorehouse** [comment]
And you are missing a closing `>` in your HTML:

```html
	<style>
	body {
    font-size: 14px; // Base font size is overriden as it is more of static content
}
	</style
```

It should be:

```html
	<style>
	body {
    font-size: 14px; // Base font size is overriden as it is more of static content
}
	</style>
```

**Comment by SridhanyaG** [comment]
I don't have any app specific css. It was copy paste mistake like style tag. nux.css is not present in the sample where i am able to replicate this issue. After looking into your screenshot i found our zoom percentages are different.
In our Edge and IE 11 our zoom is 150%. Can you please check yours too and let us know if your are able to replicate the issue. 
Steps to replicate
make zoom % to 150%
Please download this sample file https://raw.githubusercontent.com/SridhanyaG/bootstrapvueissue/master/VueBootstrapVue.html and try rendering that browser (IE/Edge)

**Comment by Hiws** [comment]
It does look to be an issue with browser zoom, however my results weren't quite as severe as the example above, mostly just a black line.

I tested it in IE and Edge on the bootstrap docs and it appears to have the issue as well. Both version 4.3 and 4.4
![image](https://user-images.githubusercontent.com/7057431/69709863-88bc4980-10fe-11ea-8e1d-712cab066b3b.png)

**Comment by SridhanyaG** [comment]
In the above screenshot only one div exist so we see a box border . Where as in our sample inside modal we have multiple focusable items / popovers and hence we see multiple lines. If we can get a patch css to turn off this border would help

**Comment by tmorehouse** [comment]
This might be an upstream issue with Bootstrap SCSS/CSS (or a browser bug).

Does this happen on the Bootstrap official docs?
