### ISSUE TITLE
b-img or b-img-lazy "@error" support

### ISSUE THREAD

**Issue by enesien** [bootstrap-vue/bootstrap-vue#4424]
I am currently not able to use **b-img-lazy** or **b-img** for my needs because I also need to use @error for the image, so if an image doesn't load properly, I can handle it cleanly.

Is there any way I can use @error within these b-img components? Or is there a way I can use the lazy-loading functionality within the basic img element?

This is an example of what I'm currently doing:
`<img :src="item.image" @error="noImage(item)" class="rounded img-fluid" />`

**Comment by tmorehouse** [comment]
You should be able to access the native event via `@error.native="noImage(item)"`

**Comment by enesien** [comment]
Indeed I can - thank you. @error.native works as expected.

**Comment by Dean-Christian-Armada** [comment]
What about `<b-avatar>`? I tried both `@error` and `@error.native` and did not work

**Comment by tmorehouse** [comment]
Avatar has the image nested inside a wrapper element.

I don't believe the `error` event on images bubbles.

**Comment by Dean-Christian-Armada** [comment]
> Avatar has the image nested inside a wrapper element.
> 
> I don't believe the `error` event on images bubbles.

Ok. The I guess I will just have to use either `<b-img>` or `<b-img-lazy>`

**Comment by tmorehouse** [comment]
You can put an image inside the default slot of avatar....

And then add the error handler directly on it. you might need to add a few utility classes to the image to make it fluid width (or use b-img with the fluid prop)

**Comment by Dean-Christian-Armada** [comment]
> You can put an image inside the default slot of avatar....
> 
> And then add the error handler directly on it. you might need to add a few utility classes to the image to make it fluid width (or use b-img with the fluid prop)

Can you give me an example on the **add the error handler directly on it**.. I am yet a beginner

**Comment by tmorehouse** [comment]
```html
<b-avatar>
  <img src="foobar" class="img-fluid" @error="handleError">
</b-avatar>
```

**Comment by Dean-Christian-Armada** [comment]
@tmorehouse Thanks!!

**Comment by lonevetad** [comment]
The `.native` requirement is counter-intuitive, the component itself should "bounce back" the event (via a re-throw or something else) so that there will be no "weird" differences between `img`, `b-img` and `b-img-lazy`
