### ISSUE TITLE
tdClass is applied to entire row in stacked table

### ISSUE THREAD

**Issue by Soviut** [bootstrap-vue/bootstrap-vue#4427]
### Describe the bug

The `tdClass` field attribute is applied to the entire row in a stacked table.

I have a `<b-list-group>` inside a `<b-table>` cell. I needed to remove the vertical padding from the cell so that the list-group could sit flush width the edges of the cell. I did this using a `tdClass: 'py-0'`

However, when switching to a stacked table on mobile, the `tdClass` is applied to the entire row. This appears to be due to the row rendering as a `<td>`. Additionally, the `thClass` gets ignored since the labels in the stacked tables use a `:before` pseudo-selector.

![image](https://user-images.githubusercontent.com/226882/69649556-37975180-103b-11ea-8acb-bef781e1919c.png)

```javascript
  data () {
    return {
      auditFields: [
        { key: 'timestamp', tdClass: 'text-nowrap' },
        { key: 'user' },
        { key: 'changes', tdClass: 'py-0' }
      ]
    }
  }
```

### Expected behavior

The `tdClass` and `thClass` should apply to their related elements in a stacked table.

### Versions

- BootstrapVue: 2.0.0.-rc.11

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Chrome
- Version: 78

**Comment by tmorehouse** [comment]
Staked tables work via changing the display attributes of the various table elements (i.e. `<tbody>`, `<thead>`, `<table>`, `<tr>`, `<td>`, etc).

In stacked mode a row is a group of cells (which are stacked one over the other).

If you need to just control the the content of the "cell", and want to remove padding around it, wrap the cell content in a div and apply negative margins.

You could set tdClass to say "p-2" for all cells, and then on your cell data wrapper div set class="m-n2" to compensate of the padding. (in your case you can set the negative margin class on the list group):

```html
<template v-slot:change="{ value }">
   <b-list-group flush class="m-n2">
      <b-list-group-item v-for="item in value" :key="item">
         {{ item }}
      </b-list-group-item>
   </b-list-group>
</template>
```
