### ISSUE TITLE
Size Property of Pagination Component has no effect

### ISSUE THREAD

**Issue by ChrisBarriere** [bootstrap-vue/bootstrap-vue#443]
I try <b-pagination size="sm" .......></b-pagination>, <b-pagination size="lg" .......></b-pagination> or <b-pagination size="md" .......></b-pagination>
and it's the same result....

**Comment by tmorehouse** [comment]
Which version of the library are you using? and which version of Bootrstrap V4 CSS?

there should be a `pagination-sm`class applied to the pagination container `div`

**Comment by tmorehouse** [comment]
Hmm it appears that Bootstrap V4 is not using `button`s for pagination purposes anymore, and uses `li`s with `a` links.

We may need to revisit `b-pagination` to bring it back in line with the latest V4 bootstrap.

**Comment by tmorehouse** [comment]
It also appears that variants (contextual classes) are not supported on V4 bootstrap pagination either.

**Comment by ChrisBarriere** [comment]
Yes, it's exactly that: the pagination class is ok (pagination-sm, pagination-md or pagination-lg) but nothing happens because of `<button>` items instead of `<li>` items

Bootstrap4 and boostrap-vue 0.16.1

**Comment by tmorehouse** [comment]
This will require a re-write of the component to align more closely with the latest bootstrap V4.  Give me a couple of days and I should have a revised version.

**Comment by ChrisBarriere** [comment]
ok, no problem.
this is not urgent

**Comment by tmorehouse** [comment]
Should be fixed by PR #477
