### ISSUE TITLE
[b-tabs] Possibility to activate tabs programmatically via id

### ISSUE THREAD

**Issue by ddweber** [bootstrap-vue/bootstrap-vue#4431]
I don´t know if it´s allready possibile but I would like to programmatically activate tabs via their id instead of the index.
The index may change sometimes, but via the id the order does not matter anymore.

I thought of the following but i don´t have access to the tabs array from the outside:
`tabs.find(tab => tab.id == "myId").activate();`

In the docs it´s stated: "You will need a reference to the b-tab in order to use these methods." But how do i get these references outside the tabs itself?

**Comment by ddweber** [comment]
Update:
I think i got one possible solution myself:
Getting tabs array via `changed` event on the `<b-tabs>` component.

Maybe this could be helpful for everybody and should be included in the docs as a hint?

**Comment by Endoma** [comment]
You can use the v-model in tabs. Updating the value will activate another tag. 
Example here: https://bootstrap-vue.org/docs/components/tabs#external-controls-using-v-model
