### ISSUE TITLE
How to add html to the root card component?

### ISSUE THREAD

**Issue by marbuser** [bootstrap-vue/bootstrap-vue#4433]
So I wasn't really sure where else to ask this, so sorry if this is the wrong place. Basically I want to put some slotted content on `b-card` directly rather than inside the `card-body` class.

Basically I want to be able to provide some slot content to this position here (Where the img tag is highlighted);
![image](https://user-images.githubusercontent.com/34422459/69777653-33ef0080-11dc-11ea-9ade-e02ed6378698.png)

I'm not sure if this is already possible but if not then consider it a feature request!

**Comment by tmorehouse** [comment]
Use the `no-body` prop to disable wrapping the default slot in a card body

```html
<b-card no-body>
  <b-card-img top src="..."></b-card-img>
  <b-card-body>
    <!-- body content here -->
  </b-card-body>
</b-card>
```

**Comment by marbuser** [comment]
@tmorehouse That's the issue, I do still need the card-body as well!

**Comment by tmorehouse** [comment]
@marbuser I'm not quite sure what you mean.
