### ISSUE TITLE
b-dropdown  + b-dropdown-item >> on click b-dropdown-item it should not focus on b-dropdown

### ISSUE THREAD

**Issue by renaudham** [bootstrap-vue/bootstrap-vue#4437]
Latest version of bootstrap-vue from 28th nov 19.
I use <b-dropdown with childs <b-dropdown-item, and a v-b-tooltip on the b-dropdown

when I click on b-dropdown-item it's focusing on the b-dropdown and then show again the tooltip,
when it should not focus on parent dropdown and therefore should not activate again the tooltip..

following code below.

```html
 <b-dropdown  right  variant="success" class="" v-b-tooltip.left title="ADD PROJECT'S ITEMS" boundary="viewport"  no-caret lazy="true">
  <template v-slot:button-content>
    <i class="fa fa-plus"></i> <label> ITEM</label>
  </template>  
  <b-dropdown-item href=""><i class="fa fa-tasks"></i> Add Tasks</b-dropdown-item>
  <b-dropdown-item href=""><i class="fa fa-circle-thin"></i> Add Milestone</b-dropdown-item>
  <b-dropdown-item href="" ><i class="fa fa-bug"></i> Add Bug</a></b-dropdown-item>
  <b-dropdown-item href="" ><i class="fa fa-comments-o"></i> Add Discussion</a></b-dropdown-item>
  <b-dropdown-item href="" ><i class="fa fa-file"></i> Add File</b-dropdown-item>
  <b-dropdown-item href="" ><i class="fa fa-envelope-o"></i> Add Message</b-dropdown-item>
</b-dropdown>
```

**Comment by renaudham** [comment]
Extra note: this is exactly the same bug here
https://bootstrap-vue.js.org/docs/components/dropdown/
If we add a tooltip

<div>
  <b-dropdown id="dropdown-1" text="Dropdown Button" class="m-md-2" **v-b-tooltip.left title="ADD PROJECT'S ITEMS"**>
    <b-dropdown-item>First Action</b-dropdown-item>
    <b-dropdown-item>Second Action</b-dropdown-item>
    <b-dropdown-item>Third Action</b-dropdown-item>
    <b-dropdown-divider></b-dropdown-divider>
    <b-dropdown-item active>Active action</b-dropdown-item>
    <b-dropdown-item disabled>Disabled action</b-dropdown-item>
  </b-dropdown>
</div>

**Comment by tmorehouse** [comment]
This is because the default triggers for tooltip are `hover` and `focus`.  The dropdown when it closes returns focus to the dropdown toggle button, which then triggers the tooltip.

Try `v-b-tooltip.hover.left` to trigger the tooltip to only open on hover.

**Comment by renaudham** [comment]
Thanks ! Working well.
You should add this in the docs, many people will see this also
