### ISSUE TITLE
[b-table] allow to use colspan/rowspan

### ISSUE THREAD

**Issue by akaJes** [bootstrap-vue/bootstrap-vue#4442]
It's possible to add this attributes using tdAttr and thAttr, but there is some issues:
1. This feature is not implemented
2. When i try to extend mixing-table-row with additional field property 'rowNum' and simple code for splitting fields and adding another 'tr' tag - then appears some additional issues with selection and highlighting of rows
3. Then I found solution with grouping rows with 'tbody' tag - but there are another issues with events and rows identification

Anybody has a simple solution for this issue, maybe working code etc?

**Comment by tmorehouse** [comment]
Currently it is not possible to control `rowspan` and `colspan` in `<b-table>` (as it would add additional levels of complexity to the code base, and many "what if" conditions when combined with pagination, sorting and filtering)

If you need to have `rowspan` and `colspan`, you will need to use `<b-table-simple>` along with the helper components `<b-thead>`, `<b-tbody>`, `<b-tfoot>`, `<b-tr>`, `<b-th>` and `<b-td>`

**Comment by TotallyInformation** [comment]
The following works but the Vue devtools complain about it:

```
                <!-- Custom Footer scoped slot -->
                <template v-slot:custom-foot="data"><b-tr><b-td :colspan="data.columns">
                    <b-button class="float-left"
                        @click="tblItemAdd(data, $event.target)"
                    >
                        Add New Entry
                    </b-button>
                    <b-pagination
                        v-model="devs.currentPage"
                        :total-rows="devs.totalRows"
                        :per-page="devs.perPage"
                        first-number last-number
                        class="float-right"
                    ></b-pagination>
                </b-td></b-tr></template>
```

![image](https://user-images.githubusercontent.com/1591850/74769654-b559aa80-5282-11ea-9218-47f7c10ea030.png)
