### ISSUE TITLE
Modal doesn't show any opening/closing animations

### ISSUE THREAD

**Issue by ptrsvlkls0** [bootstrap-vue/bootstrap-vue#4443]
Even in the docs, where they supposed to be shown.

Update: Only when using Chrome (Version 78), when I tried Edge and IE, it works fine.

**Comment by Hiws** [comment]
Animation seems fine to me in the docs on Chrome V78.

Maybe you have some extensions interfering?

**Comment by ptrsvlkls0** [comment]
No, disabled all of them with no avail.

**Comment by tmorehouse** [comment]
If you have "reduced motion" set in your OS settings, the animations for most components will be disabled (via the reduced motion media query of Bootstrap CSS).  One example would be the animated progress bars.

Do you see similar issues at https://getbootstrap.com/docs/4.4/components/modal/

**Comment by ptrsvlkls0** [comment]
In bootstrap's docs it works perfectly, very confusing...

**Comment by tmorehouse** [comment]
Oops I gave the wrong link... it should be https://getbootstrap.com/docs/4.3/components/modal/

**Comment by tmorehouse** [comment]
Also, what OS are you using?

**Comment by ptrsvlkls0** [comment]
Win 10,
4.0 Bootstrap Docs work,
4.4 and 4.3 doesn't just like Bootstrap-vue docs..

**Comment by ptrsvlkls0** [comment]
Enabling "Animate controls and elements inside windows" in Performance settings solves the problem.

**Comment by tmorehouse** [comment]
4.3 was when they introduced the reduced motion media queries to disable the animations.

In the BootstrapVue docs, do you see the progress bar animations?

**Comment by ptrsvlkls0** [comment]
Yes :]
