### ISSUE TITLE
[b-alert] Preventable dismiss event

### ISSUE THREAD

**Issue by rrelmy** [bootstrap-vue/bootstrap-vue#4444]
### Describe the solution you'd like

We would like to be able to prevent a dismiss on an alert component in certain situations (API errors or user consent on the taken action).
Much like the `hide` event on a `b-modal`

### Describe alternatives you've considered

We implemented a new alert component that builds the bootstrap alert with a custom button we can control.

**Comment by tmorehouse** [comment]
As an interim workaround, you could set the  `dismissible` prop to `false` until some condition is met, then set it to `true` if the alert can then be dismissed.
