### ISSUE TITLE
how can showing(unshowing) b-table fields?

### ISSUE THREAD

**Issue by djshox** [bootstrap-vue/bootstrap-vue#4446]
can I  not show one fields in b-table when checkbox true and showing when checkbox false?

**Comment by tmorehouse** [comment]
One of two ways:

1) Create a computed prop to filter out the "hidden" fields from the `fields` definition array passed to `<b-table>`
2) Set the field definition's `class` property to `d-none` (Utility class that sets `display: none`) to hide all `<td>` and `<th>` elements in a column. https://bootstrap-vue.js.org/docs/components/table#field-definition-reference

**Comment by djshox** [comment]
thanks

**Comment by TheAndroidGuy** [comment]
@tmorehouse Is it possible to use the 2nd approach for showing/hiding dynamically?

**Comment by tmorehouse** [comment]
@TheAndroidGuy yes, the `fields` prop is reactive, so you can just update the `class` property.  Just make sure the class property exists (i.e. `class: ''`) to ensure that it is reactive.

**Comment by TheAndroidGuy** [comment]
@tmorehouse That's awesome.

If anyone is beginner and having trouble implementing showing/hiding dynamically, here is how i did it:
```html
<b-form-checkbox v-model="advanced_view" switch @change="showColumn"> Advanced view</b-form-checkbox>
```
```js
// in methods:
showColumn: function(show) {
    if(show)
         this.fields[4].class = 'some_class'
    else
         this.fields[4].class = 'd-none'
}
```
