### ISSUE TITLE
Modals A11Y Screen Reader reads out content twice

### ISSUE THREAD

**Issue by robertung** [bootstrap-vue/bootstrap-vue#4448]
### Describe the bug

When you are using a screen reader with a Mac (default reader) the modal is being read out twice.

### Steps to reproduce the bug

1. Go to modal page  https://bootstrap-vue.js.org/docs/components/modal/
2. Activate Screen Reader
3. Tab to **Launch demo Modal** or Click on it
4. Listen to the reader.

### Expected behavior

Screen reader should only read the content 1 time.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.3.1
- Vue: 2.5.22

**Environment:**

- Device: Mac 
- OS: macOS Mojave 10.14.5
- Browser: Chrome
- Version: 78

**Comment by tmorehouse** [comment]
Is it reading the entire modal twice (header, content, footer), or just the title (header) twice and the content once?

**Comment by robertung** [comment]
It is reading the entire modal twice.

**Comment by tmorehouse** [comment]
So that is including the title+content+footer being read twice?

Have you tried any other screen readers/browsers?

We have been pondering changing the modals `aria-describedby` (which points to the modal body) to `aria-details` (and point that to the modal body). Which may assist, as `aria-describedby` reads the content of the modal as one big flat string (ignoring semantic markup, basically reads `modalBodyEl.text()`)

**Comment by robertung** [comment]
Yes, that does include the title+content+footer being read twice.

I have not tried any other ones but the default Mac Voice Over. 

I would be happy to test the mock.

**Comment by tmorehouse** [comment]
@robertung could you try out this mockup: https://deploy-preview-4449--bootstrap-vue.netlify.com/docs/components/modal/

Also could you compare to how native bootstrap v4.4 reads out the modal at https://getbootstrap.com/docs/4.4/components/modal/#live-demo

**Comment by robertung** [comment]
Looks like the mock is still reading twice. The native bootstrap does read it only once. What I do see is that the the vue bootstrap does focus on the modal, and the native does not.

**Comment by tmorehouse** [comment]
The focus on modal after open is a WIA accessibility recommendation.

If you check `document.activeElement` once modal is opened in the Bootstrap v4.x docs, you will see they too are focusing the modal `role="dialog" container as well.

**Comment by tmorehouse** [comment]
Actually, I just noticed we are focusing the `role="document"`container instead of the `role="dialog"` container.

Perhaps that is the issue.

**Comment by tmorehouse** [comment]
@robertung could you re-test at https://deploy-preview-4449--bootstrap-vue.netlify.com/docs/components/modal/ (you may need to reload the page if already open)

**Comment by robertung** [comment]
@tmorehouse this one did not read twice. But the modal title and footer were not read. Just the body was read.

**Comment by tmorehouse** [comment]
Interesting again.... As the aria-labelledby points to the header/title. Perhaps aria-details is preferred by the MAC screen reader?  I could remove aria-details and see if that makes a difference.

**Comment by robertung** [comment]
Sounds good to me. Thank you @tmorehouse .

**Comment by tmorehouse** [comment]
@robertung Can you try https://deploy-preview-4449--bootstrap-vue.netlify.com/docs/components/modal/ again?

**Comment by robertung** [comment]
@tmorehouse same results as before. But I did scroll down to the other modals using the b-model-directive. They didn't have a title but the buttons we're read out. Not sure if that helps or not.

**Comment by tmorehouse** [comment]
I wonder if the issue might be related to Vue's transition system (and possibly our portalling) is interfering which the screen reader.

One the first example in the docs, could you try adding the prop `static` to `<b-modal static ...>` which renders the modal in place (and doesn't use lazy rendering)?

**Comment by robertung** [comment]
@tmorehouse that one worked!

**Comment by tmorehouse** [comment]
Interesting...   Now if you try both `static` along with `lazy` (`<b-modal static lazy ...>`), is issue still present?

Just wondering if it is the portalling or lazy rendering of the modal content.  If the latter, then we may need to delay the showing of the modal once it is inserted into DOM.

**Comment by robertung** [comment]
@tmorehouse `<b-modal static lazy ...>` worked.

**Comment by tmorehouse** [comment]
So it must be related to to the delay added by portalling

**Comment by tmorehouse** [comment]
@robertung I've added an extra nextTick delay to the focusing of the modal dialog.

Could you try again without `static/lazy` and with `static`, and `static lazy`?

**Comment by robertung** [comment]
@tmorehouse I tried it without the `static lazy`, no success. Still works when I added it back.

**Comment by tmorehouse** [comment]
Strange....

**Comment by tmorehouse** [comment]
@robertung After a bit of reading... I found out the double read of the modal is a side-effect/bug in some screen readers.

In the WAI-ARIA 1.1 [modal dialog examples](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html), they note this:

> The first paragraph is also contained inside the element that provides the dialog description, i.e., the element that is referenced by `aria-describedby` . With some screen readers, this may have one negative  but relatively insignificant side effect when the dialog opens -- the first paragraph may be announced twice. Nonetheless, making the first paragraph focusable and setting the initial focus on it is the most broadly accessible option.

**Comment by robertung** [comment]
@tmorehouse if that's the case, I am ok with that. It's still accessibility and it does work. I greatly appreciate the time!
