### ISSUE TITLE
b-nav-item-dropdown with class ml-auto is off screen

### ISSUE THREAD

**Issue by silver8ack** [bootstrap-vue/bootstrap-vue#445]
I'm trying to use the navbar with a menu on the right... as shown in the example.  However, even in the example menu, it opens off the screen.  I can't seem to override the class to make anything work.

JS Fiddle here shows the 'User' menu opening off screen: https://jsfiddle.net/pi0/gfqucs0z/?utm_source=website&utm_medium=embed&utm_campaign=gfqucs0z

**Comment by makkrnic** [comment]
That example is broken. Instead of `right-alignment` use just `right`

https://jsfiddle.net/gfqucs0z/54/

**Comment by pi0** [comment]
Thanks :) I've update examples as well. (Still waiting for github embedding feature of JSFiddle to avoid such broken examples!)

**Comment by silver8ack** [comment]
Awesome... thanks!!!

**Comment by alexsasharegan** [comment]
@silver8ack If you're enjoying bootstrap-vue, let us know with a ⭐️ ! We appreciate your feedback!
