### ISSUE TITLE
I want the "dropdown" component to get a value

### ISSUE THREAD

**Issue by liangwenjie08** [bootstrap-vue/bootstrap-vue#4451]
```
<b-dropdown  @click="getTheValue" boundary="viewport" variant="link" right no-caret>
          <template v-slot:button-content>
            <svg-icon size="30px" file-name="language"></svg-icon>
          </template>
          <b-dropdown-item-button value="zh">中文</b-dropdown-item-button>
          <b-dropdown-item-button value="en">English</b-dropdown-item-button>
</b-dropdown>

// ======================
getTheValue(value) {
  console.log(value)
}
```
Can I get the value in a way similar to the above (just set a click event). What I do now is set a click event for each <b-dropdown-item-button>. But I think it's too much trouble.

**Comment by tmorehouse** [comment]
Could your provide a bit more info on what you are attempting to achieve?  Is it to determine which dropdown item was clicked?

**Comment by tmorehouse** [comment]
Since attributes are transferred to the inner element of dropdown items (i.e buttons in your case) you could switch to `@click.native` event:

```
<b-dropdown  @click.native="getTheValue" boundary="viewport" variant="link" right no-caret>
          <template v-slot:button-content>
            <svg-icon size="30px" file-name="language"></svg-icon>
          </template>
          <b-dropdown-item-button value="zh">中文</b-dropdown-item-button>
          <b-dropdown-item-button value="en">English</b-dropdown-item-button>
</b-dropdown>

// ======================
getTheValue(evt) {
  if (evt && evt.target && evt.target.hasAtribute('value')) {
    console.log(evt.target.getAttribute('value'))
  }
}
```

**Comment by liangwenjie08** [comment]
> 
> 
> Since attributes are transferred to the inner element of dropdown items (i.e buttons in your case) you could switch to `@click.native` event:
> 
> ```
> <b-dropdown @click.native="getTheValue" boundary="viewport" variant="link" right no-caret>
>           <template v-slot:button-content>
>             <svg-icon size="30px" file-name="language"></svg-icon>
>           </template>
>           <b-dropdown-item-button value="zh">中文</b-dropdown-item-button>
>           <b-dropdown-item-button value="en">English</b-dropdown-item-button>
> </b-dropdown>
> 
> // ======================
> getTheValue(evt) {
>   if (evt && evt.target && evt.target.hasAttribute('value')) {
>     console.log(evt.target.getAttribute('value'))
>   }
> }
> ```
> 
> The alternative is (since you are setting an attribute `value` on each dropdown item anyways):
> 
> ```
> <b-dropdown boundary="viewport" variant="link" right no-caret>
>           <template v-slot:button-content>
>             <svg-icon size="30px" file-name="language"></svg-icon>
>           </template>
>           <b-dropdown-item-button @click="getTheValue('zh')">中文</b-dropdown-item-button>
>           <b-dropdown-item-button @click="getTheValue('en')">English</b-dropdown-item-button>
> </b-dropdown>
> 
> // ======================
> getTheValue(value) {
>   console.log(value)
> }
> ```

Thank you.  It can solve my problem.
