### ISSUE TITLE
Button spacing issue

### ISSUE THREAD

**Issue by skolasbn** [bootstrap-vue/bootstrap-vue#4452]
I'm having issues with default button spacing - my button's are smashed together like this:
![Screen Shot 2019-12-04 at 10 37 43 AM](https://user-images.githubusercontent.com/3790023/70161700-1f9a8000-1682-11ea-91dd-3e9fa48edf7b.png)

but i'd like them to look like the examples on this site 

![Screen Shot 2019-12-04 at 10 36 56 AM](https://user-images.githubusercontent.com/3790023/70161667-101b3700-1682-11ea-9476-69c75fe5ba5f.png)

Not sure what's causing this. Thanks!

**Comment by tmorehouse** [comment]
Buttons do not have margins.  You can do one of two things.  Add a space between the buttons (but Vue may remove the white-space when compiling the template), or add a [margin spacing utility class](https://getbootstrap.com/docs/4.3/utilities/spacing/) to the buttons"

```html
<div>
  <b-button class="mr-1">Button</b-button>
  <b-button class="mr-1">Button</b-button>
  <b-button class="mr-1">Button</b-button>
  <b-button>Button</b-button>
</div>
```

**Comment by tmorehouse** [comment]
The docs are using the full version of Vue (with the built in Vue template compiler).  Where as I am guessing you are using Single File Components and Vue loader (which, by default, removes white-space between tags).

**Comment by skolasbn** [comment]
Ah! Thank you :)
