### ISSUE TITLE
Selecting the same row in a table after it has already been selected results in empty items array

### ISSUE THREAD

**Issue by markcarver** [bootstrap-vue/bootstrap-vue#4453]
The title really summarizes the issue here. This is a really weird bug and I thought it was just my implementation, but I've since been able to reproduce with stock bootstrap-vue.

Note: clicking a different row after selecting a row doesn't produce this issue, it only happens when selecting the same row again.

### Steps to reproduce the bug

1. Create a table with selectable rows.
2. Select a row which does something like open a modal
3. Close modal and then select the same row
4. Notice nothing happens
5. Select the same row again (2nd click) and see the modal open again

### Expected behavior

Selecting the same row would produce the same result each time it's selected.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.27
- Bootstrap: 4.4.1
- Vue: 2.6.10

**Environment:**

- Device: iMac
- OS: macOS Catalina
- Browser: Chrome
- Version: 78.0.3904.108

### Demo link

https://codepen.io/markcarver/pen/QWwwPPM/left/?editors=1011

**Comment by tmorehouse** [comment]
What you want is not row selection, but row-clicked.

Ignoring the part about opening a modal... clicking a selectable table row "selects it", clicking the row again "unselects" the row.  This is what is happening.

If you just want a row to open a modal when clicked, listen for the `row-clicked` event instead. (and maybe add the `hover` option to the table for visual effect.

**Comment by markcarver** [comment]
Hm... ok, that does make more sense now.

That being said, I didn't even realize that was an event considering the only section in the documentation that comes close to this topic is https://bootstrap-vue.js.org/docs/components/table/#row-select-support. I didn't check the actual events at the bottom.

**Comment by markcarver** [comment]
This specific issue can be closed I guess... but I think the documentation needs some updating to clarify the above as it's not entirely immediately obvious.
