### ISSUE TITLE
How to make Collapse dynamically open if the active route-link is inside of it?

### ISSUE THREAD

**Issue by marbuser** [bootstrap-vue/bootstrap-vue#4455]
I'm using https://bootstrap-vue.js.org/docs/components/collapse/ to nest some Vue Router links and was wondering if it was possible for me to dynamically open the correct collapse based on what route was accessed via URL?

**Comment by tmorehouse** [comment]
You would need to compare `this.$route` to our desired path/name and use that to control the `visible` prop:

```html
<template>
  <b-collapse :visible="$router.path.indexOf('/path/a') === 0">
    <b-link :to="{ path: '/path/a/1' }">One</b-link>
    <b-link :to="{ path: '/path/a/2 '}">Two</b-link>
    <b-link :to="{ path: '/path/a/3' }">Three</b-link>
  </b-collapse>
</template>
```

**Comment by marbuser** [comment]
@tmorehouse Thanks for that! Didn't realise it was that easy. Small correction on the code you posted, should be `$route.path` not `$router` but other than that it works perfect. Might want to update that small typo for others that come across this.

Thanks for the quick response.

**Comment by tmorehouse** [comment]
@marbuser fixed the typo in the example.
