### ISSUE TITLE
b-form-checkbox doesn't work with v-html (checkbox not rendered)

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#4458]
### Describe the bug

`b-form-checkbox` works fine if the label is specified like this
```
  <b-form-checkbox v-model="agree">{{ agreement }}</b-form-checkbox>
```

However, we need the label to include HTML markup in the 'agreement' label, so we'd like to use this
```
  <b-form-checkbox v-model="agree" v-html="agreement"></b-form-checkbox>
```

This renders the label, but no checkbox. 

bootstrap-vue-2.1.0

Thanks

**Comment by Hiws** [comment]
Don't think that'll do-able with the way `v-html` works.

However, you can create a span inside the `b-checkbox` tags and use `v-html` on that instead

```html
<b-checkbox v-model="agree">
  <span v-html="agreement "></span>
</b-checkbox>
```

**Comment by tmorehouse** [comment]
v-html "clobbers" the content of the component root element, and checkboxes render multiple elements inside it's root element, so when you try to use v-html, you destroy the nested structure of the component's rendered content. It is never a good idea to use v-html on any component.

Hiws' suggestion above is the best if you must use v-html.
