### ISSUE TITLE
b-table for its fields

### ISSUE THREAD

**Issue by KobeBeyond** [bootstrap-vue/bootstrap-vue#4462]
Can I use b-table with chinese headers? I found that I have to use headers in items as args, but we can't set chinese words as args, right? Thank you so much! Please pardon my poor English.😂

**Comment by KobeBeyond** [comment]
concrete to say, chinese words can't be a key in key value pair.

**Comment by tmorehouse** [comment]
You can define cell headers via the fields definition array:

```js
fields = [
  {  key: 'hello', label: '你好' },
  {  key: 'world', label: '世界' }
]
```

**Comment by KobeBeyond** [comment]
yeah! I got it!  Thank you so muchhhh!
