### ISSUE TITLE
Bootstrap-Vue custom styling relative paths.

### ISSUE THREAD

**Issue by simonalarie** [bootstrap-vue/bootstrap-vue#4463]
Hello guys,

Following on a  previous issue (see link). From within a **_custom.scss** file, how can I target background-image(s) using relative paths to **assets** folder ? Working on a standard VUE-CLI 3 generated project.

Easily done from within a component.vue -> background: url('../assets/xxxx.png'), but need to work from sass file.

Thanks for ideas.

Previous reflexion here: https://github.com/bootstrap-vue/bootstrap-vue/issues/690#issuecomment-320434761

**Comment by tmorehouse** [comment]
I assume you are using sass-loader for SCSS files.  BY default sass-loader passes `@import` statements to webpack to resolve the paths:

- for `@import`: https://github.com/webpack-contrib/sass-loader#resolving-import-at-rules
- for `url(...)` path resolving: https://github.com/webpack-contrib/sass-loader#problems-with-url
- - and related https://github.com/bholloway/resolve-url-loader

**Comment by simonalarie** [comment]
> I assume you are using sass-loader for SCSS files. By default sass-loader passes `@import` statements to webpack to resolve the paths, but does not do this for `url(...)` entries. See the following for details:
> 
> * for `@import`: https://github.com/webpack-contrib/sass-loader#resolving-import-at-rules
> * for `url(...)` path resolving: https://github.com/webpack-contrib/sass-loader#problems-with-url
>   
>   * and related https://github.com/bholloway/resolve-url-loader (https://symfonycasts.com/screencast/javascript-webpack/bootstrap-sass)
> 
> You could also place all your SASS imports in a `<style lang="scss">` section in your main app.vue template file (the one that has your main `<router-view />` component), which will normally handle project relative `url(...)` entries

Thanks for follow-up Troy! Will complete my solution on sass-loader.

**Comment by simonalarie** [comment]
**Resolved**

Many thanks for the provided links, got me in the right direction.

For those that it can help, I like to do a generic @import of my _custom.scss (bootstrap-vue) that is made available to all Vue Components:

https://cli.vuejs.org/guide/css.html#css-modules > Passing Options to Pre-Processor Loaders

Hence, inside custom.scss, must use this notation to relative assets: background-image: url('**~@**/assets/open-in-new-dark.svg');
