### ISSUE TITLE
b-list-group-item router links no longer working in 2.1.0

### ISSUE THREAD

**Issue by scottrobertson** [bootstrap-vue/bootstrap-vue#4464]
### Describe the bug

Previously I have been using `2.0.0-rc.11`. However, when upgrading to `2.1.0`, using `:to` has stopped working. Here is an example of the code:

```
<b-list-group>
  <b-list-group-item :to="{ name: 'setup_select_account', params: { budget_id: budget.id } }" :key="budget.id" v-for="budget in filtered_budgets">
    {{ budget.name }}
  </b-list-group-item>
</b-list-group>
```
In `2.0.0-rc.11` when i check the source href, it has the correct link. In `2.1.0` the link is just `/`

**Comment by scottrobertson** [comment]
I am also getting https://github.com/bootstrap-vue/bootstrap-vue/issues/3040 all over the place (b-navbar, basically all form elements, which may be related?)

**Comment by tmorehouse** [comment]
What version of Vue and vue-router are you using?

**Comment by scottrobertson** [comment]
```
{
  "name": "syncforynab",
  "private": true,
  "dependencies": {
    "@babel/polyfill": "^7",
    "@fortawesome/fontawesome-free": "^5.11.2",
    "@rails/webpacker": "^4",
    "axios": "^0.19.0",
    "bootstrap-vue": "^2.1.0",
    "bootstrap4-card-tables": "^1",
    "csv-parse": "^4",
    "lodash": "^4",
    "raven-js": "^3",
    "tailwindcss": "^1.1.4",
    "vue": "^2.6.10",
    "vue-awesome": "^4",
    "vue-axios": "^2.1.4",
    "vue-clipboard2": "^0.3",
    "vue-loader": "^15",
    "vue-moment": "^4.0.0",
    "vue-router": "^3",
    "vue-template-compiler": "^2.6.10",
    "vue-truncate": "^1.0.0"
  },
  "devDependencies": {
    "webpack-dev-server": "^3"
  }
}
```

Here is the list of dependencies I am using.

**Comment by tmorehouse** [comment]
In your app, are you importing vue-router before Bootstrap Vue?  BootstrapVue needs to detect Vue router first in order to render router-links, If it can't detect vue-router (`this.$router`) when you haave a `to` prop, it tries to convert the `to` object to a `path` (which assembles from the `path` and `query`).  It sounds like it can't detect `this.$outer`, so it tries to parse your `to` object and can't re-build the URL since you are using only `name` and `params`.

**Comment by scottrobertson** [comment]
@tmorehouse hmm nope, not that i can see. Import router is at the top. Wouldn't that stop it working in `2.0.0-rc.11` too?

**Comment by tmorehouse** [comment]
A lot has changed since v2.0.0-rc.11.

**Comment by scottrobertson** [comment]
Ok, thank you for your help. I will just stick with rc.11, as i cannot for the life of me get 2.1.0 working.

**Comment by tmorehouse** [comment]
I would suggest breaking it down to the bare minimum, and then add things back in to see what might be causing the issue for you.
