### ISSUE TITLE
Scrolling to programmatically selected row

### ISSUE THREAD

**Issue by xolkin** [bootstrap-vue/bootstrap-vue#4471]
### The problem
The use case is a table listing the cue items for a video. As the video plays, timing events identify the cue applicable to the current point in the video. The corresponding row can be selected (and therefore highlighted) in the table. 
When this row is not presently visible in the table, we want to scroll it into view. This can be done using javascript, as described in the comments [here]( https://github.com/bootstrap-vue/bootstrap-vue/issues/1390).
However - there seems to be no easy way to identify the container element for the row for this purpose. The event handler for row select provides the row item data, but what we need is the $el for that row.

### Potential solution

I'm open to any solution but e.g. a method `rowEl (pk)` to retrieve the DOM element for the row with key `pk` would do the trick.

**Comment by tmorehouse** [comment]
```html
<template>
  <b-table ref="table" ...>`
</template>

<script>
export default {
  methods: {
    scrollToRow(index) {
      const tbody = this.$refs.table.$el.querySelector('tbody')
      const row = tbody.querySelectorAll('tr')[index]
      row.scrollIntoView()
    }
  }
}
</script>
```

**Comment by xolkin** [comment]
Thank you for a rapid response that works perfectly. I'm very grateful.
