### ISSUE TITLE
$bvModal.msgBox* usage with Vue composition API

### ISSUE THREAD

**Issue by bbugh** [bootstrap-vue/bootstrap-vue#4472]
### Is your feature request related to a problem? Please describe...

Hi! 👋 We are switching some components to the [@vue/composition-api](https://github.com/vuejs/composition-api), and use `$bvModal.msgBoxConfirm` in many places. There does not seem to be a way to call msgBoxConfirm in the `setup` method, since plugins are not part of the context passed in to `setup`.

### Describe the solution you'd like

Some way to import the `msgBoxConfirm` and `msgBoxOk`. Currently it appears that only the plugin context is exported. 

### Describe alternatives you've considered

We thought about using another modal system, or doing something complex with event bus and/or portals, but nothing has seemed like a very good solution in comparison to the fantastic and simple `$bvModal` tools.

### Additional context

𝖄𝖔𝖚'𝖗𝖊 𝖆𝖜𝖊𝖘𝖔𝖒𝖊!

**Comment by tmorehouse** [comment]
The composition API `setup` function is called in the `beforeCreate` hook, which is before `this` is available. https://vue-composition-api-rfc.netlify.com/api.html#setup

However, `setup` receives two arguments: `props` and `context`.  The latter is an object with a few properties that will allow you to use the `$bvModal` property:

- `context.parent` (the parent component of your component, note may be `null`)
- `context.root` (the root component... i.e. your app)

So you could use: `context.root.$bvModal.show('modal-id')`

You should just make sure you test for `context.root` truthiness.

**Comment by bbugh** [comment]
Ahhhh, you're right, I should have thought of that. I appreciate you taking the time to answer. `context.root.$bvModal` works great. Thank you again for all of the great work that you do!

**Comment by raulrincon14** [comment]
could you share the code please?

**Comment by Camille019** [comment]
On my side `context.root.$bvModal` does not work.

To solve this problem, I followed the solution proposed in the comment https://github.com/bootstrap-vue/bootstrap-vue/issues/7005#issuecomment-1245836595.

This is only applicable to Vue 2.7. This comment https://github.com/bootstrap-vue/bootstrap-vue/issues/7111#issuecomment-1397891247 provides further information.

src/composables/useBvModal.ts:
```ts
import { getCurrentInstance } from "vue"; // getCurrentInstance is an internal function, use with caution

export default () => {
  const app = getCurrentInstance();

  if (app) {
    return app.proxy.$root.$bvModal;
  }
};
```

src/composables/index.ts:
```ts
export { default as useBvModal } from "./useBvModal";
```

src/views/Foo.vue:
```vue
<script setup lang="ts">
import { useBvModal } from './composables';
const bvModal = useBvModal();

function bar() {
  bvModal.hide("modalRef");
}
</script>
```

Vue: 2.7
BootstrapVue: 2.23
