### ISSUE TITLE
Toasts shrink on route change

### ISSUE THREAD

**Issue by cvn** [bootstrap-vue/bootstrap-vue#4473]
### Describe the bug

When changing routes, Toasts shrink and overlap before disappearing.

During the route change, toasts get the class "b-toaster-leave-active", which sets `position: absolute`.

I can workaround the issue by setting `.b-toaster-leave-active { position: static !important; }` in my CSS, but this introduces a side effect of removing the sliding animation that happens when the top toast is closed.

### Steps to reproduce the bug

1. Go to https://codepen.io/cvn/pen/GRgogQz
2. Click on Route 2
3. The toasts shrink and overlap.

### Expected behavior

Toasts maintain their size and position when disappearing.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.4.1
- Vue: 2.6.10

**Environment:**

- OS: macOS Mojave
- Browser: Chrome 78

**Comment by tmorehouse** [comment]
To get around this, if you are using `this.$bvToast`, is to instead use `this.$root.$bvToast` so that the toast's parent is your app component, rather than the route component.  The toasts will then persist across route changes (normally toasts are destroyed when their parent is destroyed).

**Comment by cvn** [comment]
I want the toasts to be destroyed on route change, but I don't want them to reposition when they do.

This is what I'm seeing on route change, two toasts overlapping:

![Screenshot 2019-12-10 11 05 45](https://user-images.githubusercontent.com/774864/70546352-1d7e6880-1b3d-11ea-8d79-a0bc9b5b0652.png)

Surely, this is not desirable for anyone.

**Comment by tmorehouse** [comment]
But Vue is destroying the toast DOM when the toast's parent is destroyed (toasts are child components of their parent). 

I am not sure there is a way to "pause" the destroy to allow for the transition to complete.

The other option is to place a custom b-toaster in your router view, and target the toasts to that toaster.  When the route changes, the toaster will be immediately removed from the DOM (along with the toasts in it)

**Comment by cvn** [comment]
Thank you for considering this issue. I figured out a workaround that I like now.

```css
.b-toaster-leave-active {
  width: 100%;
}
```

This stops the toasts from shrinking. They still overlap, but, that I think is actually part of a larger issue with some toast animation not working. I'm making a new issue for that.
