### ISSUE TITLE
Setting the form-class on b-dropdown-form

### ISSUE THREAD

**Issue by bbugh** [bootstrap-vue/bootstrap-vue#4474]
### Is your feature request related to a problem? Please describe...

We have a `b-dropdown-form` that needs to be a `flex-wrap: nowrap`, among other settings. There is currently no way to set the class on the form of the `b-form-dropdown`. Using `class="special-form"` adds the class to the wrapper `li`.

### Describe the solution you'd like

The common pattern in these scenarios seems to be having a new property that affects the specific component, like `form-class`. 

Happy to PR this if it's an acceptable idea.

### Describe alternatives you've considered

We could use a selector to say `.special-form > form` but that's getting into library implementation details. 

### Additional context

https://bootstrap-vue.js.org/docs/components/dropdown/#comp-ref-b-dropdown-form-props

**Comment by tmorehouse** [comment]
The current workaround would be a custom style that targets the form element, but with scoped styles you would need the deep selector:

```html
<style scoped>
  .special-form /deep/ form {
    flex-wrap: nowrap;
  }
</style>
```

But a new prop `form-class` would allow you to place bootstrap utility classes on the form element.
