### ISSUE TITLE
Add custom collapse/not-collapsed classes to collapse button

### ISSUE THREAD

**Issue by Flothus** [bootstrap-vue/bootstrap-vue#4476]
It would be very helpful if it was possible to give custom classes to collapse buttons for the collapse/non-collapsed state via attributes. At the moment only the class "collapse" is added/removed. 

This makes it very tedious to rewrite animations if you use an animation library that relies on active/non-active classes.

**Comment by Hiws** [comment]
I'm not 100% sure if this is what you're looking for.
However you can bind a property to the collapse v-model which is the state the collapse is in.
Either false for hidden or true for open.

You can then use this property to conditionally add/remove classes from other elements.

```html
<b-btn 
       variant="light"
       class="border-dark"
       :class="!isShowing ? 'text-danger' : 'text-primary'" 
       v-b-toggle.collapse-1
>
  Open Collapse 1
</b-btn>
<b-collapse v-model="isShowing" id="collapse-1">
  <b-card>
    <div v-for="i in 10">Hello my name is...</div>
  </b-card>
</b-collapse>

<script>
data() {
  return {
    isShowing: false,
  }
}
</script>
```

**Comment by Flothus** [comment]
@Hiws actually did that for one component. 
But I'd say that's only a partial solution. E.g. for an accordion you'd have to write your own logic based on unique variables bound to each v-model. If it's an accordion with dynamic items that gets kind of messy fast. Using v-b-toggle with built-in classes for both states seems cleaner and shorter. 

Or am I missing something?

**Comment by tmorehouse** [comment]
Are you looking for classes on the trigger element (i.e. where `v-b-toggle` is bound) or the actual `<b-collapse>` component?

**Comment by tmorehouse** [comment]
PR #5336 adds additional `not-collapsed` class to the trigger element (when using `v-b-toggle`) when the target collapse is not closed, in addition to the already available `collapsed` class (when the target collapse is closed)

**Comment by tmorehouse** [comment]
We are also looking at the ability to specify addition custom collapsed/not-collapsed classes via the use of `data-class-collapsed` and `data-class-not-collapsed` attributes on the element that `v-b-toggle` is applied to.  This will be available via a future PR.

**Comment by Flothus** [comment]
That's exactly what I felt was missing. Thanks!
