### ISSUE TITLE
Broken styles when using next generate

### ISSUE THREAD

**Issue by mikkokut** [bootstrap-vue/bootstrap-vue#4477]
### Describe the bug

Styles got broken when generating nuxt static assets. This can be seen for example in dropdown component's broken outline style. Dropdown components should not have outline when focused. Weird thing is that it works if used with "yarn dev" command.

### Steps to reproduce the bug

1. Create empty nuxt project with bootstrap-vue@^2.1.0 and bootstrap@^4.4.0
2. Add dropdown element to index page
3. Run yarn generate
4. Test result from dist folder to see that if the dropdown is clicked the menu has outline

### Expected behavior

No outline in dropdown menu.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.4.0

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Chrome
- Version: 78.0.3904.108

### Demo link
[https://bs-outline-bug.now.sh/](https://bs-outline-bug.now.sh/)
[https://github.com/mikkokut/bs-outline-bug](https://github.com/mikkokut/bs-outline-bug)

**Comment by mikkokut** [comment]
Works with bootstrap 4.3.0

**Comment by Hiws** [comment]
In Bootstrap `4.4.x` they changed whether or not elements with `tabindex="-1"` should have an outline or not. In `4.3.x` it's hidden, however that was removed in `4.4.x`.

This is properly what is causing the outline to appear.

https://github.com/twbs/bootstrap/issues/28425
https://github.com/twbs/bootstrap/pull/28437


Just a headsup that `bootstrap-vue` isn't updated to be properly compatible with bootstrap 4.4.x, so it's probably more safe to stay in `4.3.x` to avoid issues.

**Comment by mikkokut** [comment]
Thanks for information. Very interesting it works on development environment using `yarn dev` but not in the build using `yarn generate`.

I will stick to bs 4.3.x until proper support.

**Comment by tmorehouse** [comment]
Dropdown styling has been fixed by https://github.com/bootstrap-vue/bootstrap-vue/pull/4440

And form-group/form-checkbox-group/form-radio-group styling has been fixed by https://github.com/bootstrap-vue/bootstrap-vue/pull/4479

Will be available in release v2.2
