### ISSUE TITLE
Usage of b-dropdown or b-nav-item-dropdown throws TypeError: Invalid calling object in IE11

### ISSUE THREAD

**Issue by sjtipton** [bootstrap-vue/bootstrap-vue#4483]
### Describe the bug

I am setting up a menu navigation bar that contains a dropdown, and it requires support of IE11. When rendering in IE11, it is throwing a `[Vue warn]: Error in v-on handler: "TypeError: Invalid calling object"` when clicking on the top-level dropdown item in the menu. This does not occur in Chrome.

I have all the polyfills installed (core-js, regenerator-runtime) and imported in my index.js. I am using Webpack.

![image](https://user-images.githubusercontent.com/437989/70539849-3c2b3200-1b32-11ea-9d18-962839f4221c.png)

### Steps to reproduce the bug

1. Use BootstrapVue in a new Vue component
2. Ensure `core-js` and `regenerator-runtime/runtime` are imported
3. For a simple reproduction, grab the example dropdown nav markup from the docs (https://bootstrap-vue.js.org/docs/components/nav/#comp-ref-b-nav-item-dropdown)

```js
// in main entry point
import 'core-js'
import 'regenerator-runtime/runtime'

import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'

new Vue({
  el: '#app'
}

// in menu component
<template>
  <div>
  <b-nav pills>
    <b-nav-item active>Active</b-nav-item>
    <b-nav-item>Link</b-nav-item>
    <b-nav-item-dropdown
      id="my-nav-dropdown"
      text="Dropdown"
      toggle-class="nav-link-custom"
      right
    >
      <b-dropdown-item>One</b-dropdown-item>
      <b-dropdown-item>Two</b-dropdown-item>
      <b-dropdown-divider></b-dropdown-divider>
      <b-dropdown-item>Three</b-dropdown-item>
    </b-nav-item-dropdown>
  </b-nav>
</div>
</template>
```

### Expected behavior

The dropdown is fully interactive and navigable in IE11 without any console errors.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.4.1
- Vue: 2.6.10
- Webpack: 4.40.2

**Environment:**

- Device: Windows
- OS: Windows 10
- Browser: IE 11
- Version: 11.476.18362.0 (Update version 11.0.160)

**Comment by sjtipton** [comment]
Digging into the `dropdown.js` src, there is a `requestAF` function from a `utils` mixin that does not seem to be firing. It was added with [this commit](https://github.com/bootstrap-vue/bootstrap-vue/commit/1604022f9866456e9da3c627e3613f56cca1f700)

If we set `this.visible = true` immediately vs. trying to invoke `requestAF` with the callback, the dropdown behaves appropriately in IE.

**Comment by tmorehouse** [comment]
requestAF is a convenience method to the browser's `requestAnimationFrame` method, which allows the delay in hte event so that the click handling has a chance to process.

IE 11 supports `requestAnimationFrame`.  Perhaps there is something missing from core-js polyfill? or perhaps javasript minification or dead code elimination is removing parts of core-js?

If you switch to a script in your main index.html that includes polyfill.io (https://bootstrap-vue.js.org/docs#browser) does the issue go away? (we use polyfill.io for the docs)

**Comment by tmorehouse** [comment]
Also, which version of core-js are you using? 2 or 3?

**Comment by sjtipton** [comment]
> Also, which version of core-js are you using? 2 or 3?

We are using `core-js@3.4.8`

**Comment by sjtipton** [comment]
>> Strangely, I tried to switch to the polyfill.io approach in our index.html, and temporarily commented out the imports of the individual polyfills in the main entrypoint for Webpack, and it is still throwing the error. As for the `core-js` polyfilll, I have tried both importing all of `core-js` as well as `core-js/stable`.

**Comment by sjtipton** [comment]
FWIW, this error is also being thrown when a `b-modal` pops up a few minutes later after a session timeout.

**Comment by AlexLu202** [comment]
I assume you are using babel 7. For some reason, babel 7 stops transpiling imported module. That's probably the reason why

**Comment by jgsestrich** [comment]
> FWIW, this error is also being thrown when a `b-modal` pops up a few minutes later after a session timeout.

I have run into this exact problem; did you every resolve the issue?
