### ISSUE TITLE
Allow hiding b-table sort icons when not sorted yet

### ISSUE THREAD

**Issue by sebastian-raubach** [bootstrap-vue/bootstrap-vue#4486]
### Is your feature request related to a problem? Please describe...

There is currently no option to hide the `b-table` sort icons when no sorting has taken place yet. Ideally, I want to save horizontal space by not showing the sort icons until a column has actually been sorted.

### Describe the solution you'd like

An option to hide the sort icons when the table isn't sorted

### Describe alternatives you've considered

I tried overriding the SCSS variables like this:
```css
$b-table-sort-icon-bg-not-sorted:      url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' width='0' height='0' view-box='0 0 0 0' preserveAspectRatio='none'></svg>") !default; 
$b-table-sort-icon-bg-dark-not-sorted: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' width='0' height='0' view-box='0 0 0 0' preserveAspectRatio='none'></svg>") !default;
```
But the icons still show up.

**Comment by Hiws** [comment]
You shouldn't use `!default` when overriding variables in SCSS, removing it should make it work.

**Comment by sebastian-raubach** [comment]
I have removed it and they are still visible.

**Comment by Hiws** [comment]
@sebastian-raubach Edited my first reply with some extra info.

**Comment by sebastian-raubach** [comment]
I can't seem to find the right place to put this to make it work. I've at the start of different .scss files and currently they're here in `App.vue`:

```

**Comment by sebastian-raubach** [comment]
I managed to override it with plain CSS in the component now. That's good enough for me. Also allows me to remove the extra padding. Thanks anyway, though!
