### ISSUE TITLE
Animation modal on hide event is not smooth

### ISSUE THREAD

**Issue by handhikadj** [bootstrap-vue/bootstrap-vue#4491]
### Describe the bug

I'm using animate css to add some animation to the modal. Actually, I don't know whether this is a bug or not. But I conclude this as a bug.
I need a workaround to smooth out the on hide event

### Steps to reproduce the bug

1. open and close the modal
2. You can see the modal is not animated well on hide

### Expected behavior

the modal is animated well on hide

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Vue: 2.5.22
- animate.css: 3.7.2

**Environment:**

- Device: Macbook
- OS: Mac Mojave
- Browser: Chrome
- Version: 79

### Demo link

https://codesandbox.io/s/summer-river-yjuvx

### Additional context

nothing

**Comment by handhikadj** [comment]
update: solved after walking a very exhausted journey. https://codesandbox.io/s/summer-river-yjuvx
is there any simpler workaround?

**Comment by tmorehouse** [comment]
Modal CSS animations are defined via SCSS in Bootstrap v4.3.x, and can be controlled with SASS/SCSS variables: 

https://github.com/twbs/bootstrap/blob/dca1ab7d877bc4b664b43604657a2b5fbe2b4ecb/scss/_variables.scss#L940-L980

```scss
$modal-fade-transform:      translate(0, -50px) !default;
$modal-show-transform:      none !default;
$modal-transition:          transform .3s ease-out !default;
$modal-scale-transform:     scale(1.02) !default;
```

**Comment by rifton007** [comment]
I haved same problem :
So If you don't load all components Bootstrap's like me, don't forget to load `@import '~bootstrap/scss/transitions';`
