### ISSUE TITLE
Is it possible to use Vue filters in b-table field formatter?

### ISSUE THREAD

**Issue by sebastian-raubach** [bootstrap-vue/bootstrap-vue#4492]
### Is your feature request related to a problem? Please describe...

Is it possible to use globally defined `filter`s in the `formatter` of a `field` inside a `b-table`?

### Describe the solution you'd like

```javascript
{
  key: 'date',
  formatter: 'toDate' // <- This is the name of the filter
}
```

Where the filter is defined as:

```javascript
Vue.filter('toDate', value => {
  var moment
  if (value.indexOf('-') !== -1) {
    moment = window.moment(value)
  } else {
    moment = window.moment(value, 'MMM D, YYYY')
  }
  return moment.format(i18n.t('formatDate'))
})
```

### Describe alternatives you've considered

Using a scoped slot to format it:

```
<template v-slot:cell(date)="data">
  {{ data.item.date | toDate }}
</template>
```

**Comment by Hiws** [comment]
You should be able to access your global filters in `this.$options.filters`

Try doing this in your field
```js
{
  key: 'date',
  formatter: this.$options.filters.toDate
}
```

**Comment by sebastian-raubach** [comment]
Yep, working fine, thanks!
