### ISSUE TITLE
"bv::collapse::sync::state" gets fired too many times.

### ISSUE THREAD

**Issue by saroshali4** [bootstrap-vue/bootstrap-vue#4494]
### Describe the bug
I have a modal with a form in it. Form have few collapses. Whenever I open/close the modal/collapses or type in the inputs, this event gets fired a lot of times.

What is this event "bv::collapse::sync::state" and I can't see this mentioned in the docs as well.
Does this affect the performance of the app, because my form inputs are lagging. I'm using vee-validate for the validation purpose.

![Capture](https://user-images.githubusercontent.com/21079476/70727359-75f96580-1cf7-11ea-94de-429b09859ed4.PNG)

![Capture2](https://user-images.githubusercontent.com/21079476/70727382-83aeeb00-1cf7-11ea-968b-1a7c19ff79a2.PNG)

### Versions

**Libraries:**

- BootstrapVue: 2.0.4
- Bootstrap: 4.3.1
- Vue: 2.6.10
-VeeValidate: 2.2.15

**Environment:**

- OS: Windows
- Browser: Chrome

**Comment by tmorehouse** [comment]
The `bv::collapse::sync::state` is an interal event that is emitted whenever the component the collapse is in updates (the updated hook), to ensure that the element with `v-b-toggle` on it has the correct state of the collapse (to control the aria-epanded attribute and the collapsed class)

**Comment by saroshali4** [comment]
> The `bv::collapse::sync::state` is an interal event that is emitted whenever the component the collapse is in updates (the updated hook), to ensure that the element with `v-b-toggle` on it has the correct state of the collapse (to control the `aria-expanded` attribute and the collapsed class). The element with v-b-toggle will periodically also emit a sync request event to the collapse requesting a sync event (just in case the toggle element gets updated and ovewrites the attributes and classes)

Thanks for the explanation. Can this be the reason for input lag as it fires a lot of events on typing?

**Comment by tmorehouse** [comment]
Possible fix for lagging input: #4825
