### ISSUE TITLE
Nuxt generate does not include bootstrap-vue plugins

### ISSUE THREAD

**Issue by JuliaUsanova** [bootstrap-vue/bootstrap-vue#4495]
### Describe the bug

I want to use Carousel plugin from bootstrap-vue, and it works fine in dev mode, but in production it is not loaded. There are no errors in browser console.

### Steps to reproduce the bug

1. In nuxt.config.js 
```
modules: [
        'nuxt-i18n',
        '@nuxtjs/axios',
        '~/modules/hooks',
        'bootstrap-vue/nuxt',
        '@nuxtjs/style-resources',
    ],
bootstrapVue: {
        bootstrapCSS: false, // Or `css: false`
        bootstrapVueCSS: false, // Or `bvCSS: false`
        componentPlugins: ['CarouselPlugin']
    },
```
2. In page.vue
```
<template>
        <b-carousel id="whatsNextCarouselCmp" ref="whatsNextCarouselCmp" indicators>
                <b-carousel-slide
                    v-for="step in steps"
                    :key="step.index"
                    class="carousel-item text-center mt-5"
                >
                    <template v-slot:img>
                        <div class="next-step-icon d-flex justify-content-center align-items-end">
                            <img :src="step.imgSrc" alt="" />
                        </div>
                        <h3 class="mb-4 mt-3">{{ step.header }}</h3>
                        <p>{{ step.content }}</p>
                    </template>
                </b-carousel-slide>
        </b-carousel>
</template>
```

3. In .nuxt/bootstrap-vue.js 
```
import Vue from 'vue';

import {
  CarouselPlugin
} from 'bootstrap-vue';

Vue.use(CarouselPlugin);

```
4. I run `yarn run generate` and manually put the `dist` folder to the AWS S3 bucket 
5. I open the page in mobile view and there is no carousel 

### Expected behavior

There is carousel on mobile view (768 X 590)
### Versions

**Libraries:**

"bootstrap-vue": "^2.1.0"
"nuxt": "2.10"

**Environment:**

- Device: [Mac Book 2018]
- OS: [macOS Catalina- 10.15.2]
- Browser: [Chrome]
- Version: [78.0.3904.108 (Official Build) (64-bit)]

### Demo link

deployed page https://public-web-coople.s3.amazonaws.com/en/coople-manage/info/index.html
source code https://github.com/JuliaUsanova/test-public-web/blob/master/pages/coople-manage/info.vue

### Additional context

Will appreciate your help

**Comment by tmorehouse** [comment]
I can see that the carousel item is being rendered (note you are adding lass `carousel-item` which is duplicating the class on the item.

It also appears that you are trying to scope the Bootstrap SCSS which is probably interfering.

**Comment by JuliaUsanova** [comment]
It doesn't seem that the problem is in styles. I removed scoping and duplication of the classes, and pushed everything in https://github.com/JuliaUsanova/test-public-web/tree/test-bootstrap-vue

It still doesn't work, I assume that js is not loaded, even though everything is set up as in Bootstrap-Vue guides

**Comment by tmorehouse** [comment]
I was looking at your code/rendered index.html and I can see BootstrapVue present in one of the defered _nuxt/xxxxx.js files (and BCarousel/BCarouselSlide are included).

I noticed that you are only showing the carousel on screens below the `md` breakpoint in your SCSS.

I am wondering if this has something to do with it not cycling.

Server side, the carousel is definitely being rendered correctly, but when I inspect the root element of the carousel, I do not see any vue instance bound to it.

**Comment by tmorehouse** [comment]
I see one issue:

https://github.com/JuliaUsanova/test-public-web/blob/55ab8e54f60d1fa93570868ceb24bb10d877db72/nuxt.config.js#L35-L39

```js
    bootstrapVue: {
        bootstrapCSS: false, // Or `css: false`
        bootstrapVueCSS: false, // Or `bvCSS: false`
        componentsPlugin: ['CarouselPlugin'] // <== here
    },
```

```js
    bootstrapVue: {
        bootstrapCSS: false, // Or `css: false`
        bootstrapVueCSS: false, // Or `bvCSS: false`
        componentPlugins: ['CarouselPlugin'] // <== should be this
    },
```

**Comment by JuliaUsanova** [comment]
Sorry for `componentPlugins: ['CarouselPlugin']`, it is a mistake and is fixed already
However, fixing this and removing breakpoint also haven't worked
Here is the updated s3 instance https://public-web-coople.s3.amazonaws.com/en/coople-manage/info/index.html
and here is the github branch https://github.com/JuliaUsanova/test-public-web/tree/test-bootstrap-vue

**Comment by JuliaUsanova** [comment]
I also uploaded here https://public-web-coople.s3.amazonaws.com/en/coople-manage/info/index.html js with source-maps in case it can help

**Comment by JuliaUsanova** [comment]
And it still seems to me that bootstrap-vue js is not there

**Comment by tmorehouse** [comment]
It might be related to the nuxt plugin.

Currently the plugin triggers on `build;before` hook. Perhaps it does not get run during `generate` hook.

Perhaps @pi0 or @Atinux may have a better understanding of which hooks are called for `nuxt generate`.

**Comment by JuliaUsanova** [comment]
Hi  @pi0 !
Is there any update on bootstrap-vue and nuxt?

**Comment by tmorehouse** [comment]
@JuliaUsanova if you try this, does it work:

```sh
yarn run build && yarn run generate
```

**Comment by tmorehouse** [comment]
@JuliaUsanova See https://github.com/bootstrap-vue/bootstrap-vue/issues/4929

I think you may be having a similar issue, if the URL contains `/dist` on your server.
