### ISSUE TITLE
animated b-progress-bar causes high cpu usage 

### ISSUE THREAD

**Issue by soichih** [bootstrap-vue/bootstrap-vue#4496]
I am using boostrap-vue v2.1.0 with vue 2.6.10 on Chrome v78.0

using b-progress-bar with :animated="true" causes extremely high cpu usage.

Without :animated="true"
![image](https://user-images.githubusercontent.com/923896/70734930-2e64e080-1cdb-11ea-9fd1-1ce494f0673d.png)

With :animated="true"
![image](https://user-images.githubusercontent.com/923896/70734728-c7dfc280-1cda-11ea-8ebd-af5090e20364.png)

**Comment by tmorehouse** [comment]
The progress bar animation effect is a CSS transition/animation defined by Bootstrap v4.3.1 CSS/SCSS.

You will probably see the same issue with native bootstrap progress bars, as this would be an upstream issue with Bootstrap SCSS. https://github.com/twbs/bootstrap/issues/5148

**Comment by vesper8** [comment]
don't want to create a new issue just for this but wanted to mention that the docs appear to mention that I should be seeing some kind of animation here: https://bootstrap-vue.js.org/docs/components/progress/

but on Chrome 80 there is no animation to be seen

**Comment by tmorehouse** [comment]
It sounds like you might have `reduced motion / animation` set either in your browser or OS settings.

This will trigger the `prefers-reduced-motion` media query to kick in and disabled most animations throughout Bootstrap CSS:  https://getbootstrap.com/docs/4.4/getting-started/accessibility/#reduced-motion
