### ISSUE TITLE
Pagination component does not accept an initial value > 1

### ISSUE THREAD

**Issue by bobmulder** [bootstrap-vue/bootstrap-vue#4499]
### Description

When using the [Pagination component']](https://bootstrap-vue.js.org/docs/components/pagination/) you can use the `v-model` for a link to your page number. 

However, when I initialize my `v-model` with a number > 1, still page 1 is shown from start.

### Steps to reproduce the bug

1. Initialize the component
2. Assign a `v-model` with a value > 1
3. See page 1 is selected

### Expected behavior

I expect the current (given) page should be selected by default.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.x.x
- Vue: 2.6.10

**Environment:**

- Device: Mac
- Browser: Crhome
- Version: latest

**Comment by Hiws** [comment]
Seems to be an issue with your project. 
Are you sure your `v-model` has the correct value? 

https://codepen.io/Hiws/pen/WNbxVza

**Comment by Hiws** [comment]
If you're loading in data after the pagination has been initialized, that might cause issues for you.
If you set the pagination to `currentPage: 5`, `perPage: 10` and `totalRows: 0`, and then the `totalRows` change a bit later (after maybe calling an API), the `currentPage` will be set to 1.

In this case you'll need to set your `currentPage` after the data has been successfully loaded.

**Comment by bobmulder** [comment]
Thank you for your example! I'm trying to implement, but I get some reloads. However, that's on my side, your solution proves my bug report is invalid!

Thank you again, @Hiws :)
