### ISSUE TITLE
Vue.js 2.1 render trouble

### ISSUE THREAD

**Issue by LuckUp** [bootstrap-vue/bootstrap-vue#45]
Hi,

there is some troubles with vue.js in 2.1 version. I got the error: 
`Vue warn]: Error when rendering component <bNavbar>: 
vue.js?3de6:2963 Uncaught ReferenceError: _h is not defined(…)`

I rollback to vuejs 2.0.8 for now and everything works fine.

**Comment by sn0rcha** [comment]
I have the same problem as well

**Comment by pterk** [comment]
This is related to #44. @pi0 just merged it so I think it will be fixed in the next release. In the mean time you can add the dependency yourself and then rebuild bootstrap-vue (if you use webpack v2)

**Comment by mathlet0x** [comment]
I just tested, and i've got the same error with the last version of bootstrap-vue, i'll investigate

**Comment by cagartner** [comment]
same here, wainting for yours pull-request 👍

**Comment by gabyrusu** [comment]
+1

**Comment by yasirhantoush** [comment]
same here, I just used vue-cli lwith bootstrap-vue but failed for same error, what is the fix for this?

**Comment by InTwoDisease** [comment]
加油 解BUG

**Comment by mathlet0x** [comment]
我今天纠正 !

**Comment by InTwoDisease** [comment]
赞👍

**Comment by mathlet0x** [comment]
Hey mates, i fixed the issue in my last commit, so please try to rebuild and give me your feedback

**Comment by fabien-lg** [comment]
Hello,
I've rebuild and tested and it works for me.
The «`Uncaught ReferenceError: _h is not defined(…)`» is gone.
Thanks!

**Comment by mathlet0x** [comment]
Great ! Thanks @fabien-lg i can close the issue

**Comment by OmgImAlexis** [comment]
If you haven't could you please update npm and bump the version number.

**Comment by andrzejkupczyk** [comment]
@fabien-lg , @mathlet0x , I tried to rebuild but UglifyJS caught these errors:

```
yarn run v0.18.1
$ cd scripts && ./build 
Building commonjs version
Hash: c3e74280605a7a6ca3e0                                                             
Version: webpack 2.1.0-beta.25
Time: 6155ms
                     Asset    Size  Chunks             Chunk Names
    bootstrapVue.common.js  190 kB       0  [emitted]  bootstrapVue
bootstrapVue.common.js.map  250 kB       0  [emitted]  bootstrapVue
    + 113 hidden modules

ERROR in bootstrapVue.common.js from UglifyJs
SyntaxError: Unexpected token: name (text) [./utils/helpers.js:5,0][bootstrapVue.common.js:79,6]
Building browser version
Hash: 834ffdd4567a81cc64ab                                                             
Version: webpack 2.1.0-beta.25
Time: 6024ms
              Asset    Size  Chunks             Chunk Names
    bootstrapVue.js  190 kB       0  [emitted]  bootstrapVue
bootstrapVue.js.map  250 kB       0  [emitted]  bootstrapVue
    + 113 hidden modules

ERROR in bootstrapVue.js from UglifyJs
SyntaxError: Unexpected token: name (text) [./utils/helpers.js:5,0][bootstrapVue.js:78,6]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by OmgImAlexis** [comment]
@andrzejkupczyk already have an issue about that. 👍 
https://github.com/bootstrap-vue/bootstrap-vue/issues/48

**Comment by kushalpandya** [comment]
I'm still facing this issue (with v0.3.12) while trying to register `BootstrapVue` globally.

This is error I get while trying to use Alerts.

```
[Vue warn]: Error when rendering component <bAlert>:
Uncaught ReferenceError: _h is not defined
```

I tried it with a webpack configuration generated using [Vuepack](https://github.com/egoist/vuepack) (which is based on Webpack 2.2 RC) as well as with [vue-webpack-boilerplate](https://github.com/vuejs-templates/webpack). Is there something that I'm missing here?

**Comment by pi0** [comment]
@kushalpandya New version is not released yet however your problem seems not related to that... would you please provide your entry point script ?

**Comment by kushalpandya** [comment]
@pi0 Sure, here's my `main.js`

```javascript
import Vue from 'vue';
import VueRouter from 'vue-router';
import BootstrapVue from 'bootstrap-vue';

import App from './App';
import Routes from './routes';

Vue.use(VueRouter);
Vue.use(BootstrapVue);

const router = new VueRouter(Routes);

const app = new Vue({
  router,
  ...App
});

app.$mount('#app');
```

And here's usage within a template (it is also a router outlet)

```
<template lang="html">
  <div class="container-fluid page-body">
    <b-alert :show="true" state="success" dismissible>
      This is an alert
    </b-alert>
    <router-view></router-view>
  </div>
</template>
```

**Comment by pi0** [comment]
@kushalpandya Sorry for delay. I've created a dummy workingexample using Vuepack and latest version of this repo. Please see [vuepack-bootstrap-example](https://github.com/bootstrap-vue/vuepack-bootstrap-example).
Good luck ;) and feel free to open another issue if problem exists with latest version.

**Comment by kushalpandya** [comment]
@pi0 Thanks a lot for a quick example to test :smiley: that did fix my problem, I probably had incorrect property mappings in `new Vue()` call, as well as I had `tether` and `promise-polyfill` missing in dependencies (I guess `tether` is still required for Bootstrap to work) while promises support is only needed if I use `vuex` (which I'm not, currently).

Thanks a ton for saving me hours of frustration! :tada:

**Comment by Jonas-buriti** [comment]
I'm facing the same issue (ReferenceError: _h is not defined). I'm looking forward to the "Vue 2.1 -ready" vesion. Tks Guys!

**Comment by mathlet0x** [comment]
Hey @Jonas-buriti, what is your webpack version ?

**Comment by sn0rcha** [comment]
Does anyone know if this issue is fixed?

**Comment by mathlet0x** [comment]
Yes it is !
