### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by KobeBeyond** [bootstrap-vue/bootstrap-vue#4502]
I use b-modal tag like this:

```html
      <b-button v-b-modal.my_modal>my_button</b-button>
      <b-modal
          id="my_modal"
          title="something"
          @ok="doSomething">
        some tips
      </b-modal>
```
but when I click  my_button,  I got this: 

![modal_issue](https://user-images.githubusercontent.com/41274333/70849836-a808f400-1ebe-11ea-809a-fc3575c80cbf.png)

I clicked cancel got: 
![then](https://user-images.githubusercontent.com/41274333/70849837-a93a2100-1ebe-11ea-922b-45bab0254989.png)

I clicked cancel button several times, it returned to my original page finally.
I'd like to  know how to figure it out 😭. Please pardon my poor English, thanks so much!

**Comment by tmorehouse** [comment]
Are you including BootstrapVue's CSS after Bootstrap's CSS in your project?

**Comment by KobeBeyond** [comment]
Thank you for your apply! I have included BootStrapVue's CSS and BootStrap's CSS like this:
![image](https://user-images.githubusercontent.com/41274333/70857124-0d430080-1f24-11ea-9bdd-1e9fee04c07c.png)
In fact, I used b-v-modal tag correctly before, 
![image](https://user-images.githubusercontent.com/41274333/70857175-b689f680-1f24-11ea-910b-225d2e4a4d29.png)
nothing went wrong. 
I followed this method but...the modal doesn't seem to disappear, until I click cancel button for five or six times

**Comment by Hiws** [comment]
Do you have multiple modals on the same page?
In that case be careful to provide them with unique ID's.  Otherwise you'll open all of them when clicking your button and they'll all get stacked on top of eachother.

**Comment by KobeBeyond** [comment]
Thank you for you reply! I'll be careful with the case you have motioned. But I didn't have multiple modals on the same page.
![image](https://user-images.githubusercontent.com/41274333/70907253-5e95e180-2043-11ea-944b-d58636d94c26.png)

**Comment by Hiws** [comment]
And that component/code isn't being called multiple times in a `v-for` for example or maybe you're using it inside a `b-table`?

**Comment by KobeBeyond** [comment]
What a great pleasure for me to get your reply again! I changed 
  id="ensureDeleteSubPaper"  to  id="ensure-delete-sub-paper" and it worked. Thanks a million!!

**Comment by tmorehouse** [comment]
When using in document templates, ID attributes are converted to lower-case by the browser (SFC templates do not have this issue)

**Comment by KobeBeyond** [comment]
Yes! I forgot this when I am coding. I'll brand it on my mind🧐Thank you very much!
