### ISSUE TITLE
<b-nav-item-dropdown> does not support event.target.value

### ISSUE THREAD

**Issue by SvenMeyer** [bootstrap-vue/bootstrap-vue#4505]
I thought I would have a simple requirement : I just want to have a drop-down / form-select in the `<b-navbar>` with a list of values, pre-select that value and get event/function call + selected value out of it ... but can't find a solution anywhere.
There is also no `<b-nav-form-select>` which would support a `v-model`

**Comment by jackmu95** [comment]
@SvenMeyer Please take a look at this example: https://codesandbox.io/s/bootstrapvue-b-nav-item-dropdown-select-wrinp

It uses `<b-nav-item-dropdown>` and adds some simple custom logic to behave like a select.

**Comment by SvenMeyer** [comment]
Works great ! That's what I was looking for. Thanks a lot !
