### ISSUE TITLE
Application wide component settings

### ISSUE THREAD

**Issue by scottadamsmith** [bootstrap-vue/bootstrap-vue#4507]
### Is your feature request related to a problem? Please describe...

Many components have properties that are meant to provide strings that a user either sees or hears and as a result, needs to be translated.

### Describe the solution you'd like

I see we have the ability to configure some props via the plugin settings, but is there a pattern to how we choose which are included? Or is it just need-based? 

I wonder if there is a way we can make the available settings dynamic so that any prop on any component can be configured application wide without the need to code for it. Add a prop and it becomes available. My use case primarily centers around settings translated strings once for the application, but I feel that if being addressed, there is no reason not to address it for any prop.

### Describe alternatives you've considered

If this is not feasible, are PRs to add more settings typically accepted or are there specific requirements as to which props or types of props would be accepted?

### Additional context

None

**Comment by jackmu95** [comment]
@scottadamsmith Interesting idea.

> If this is not feasible, are PRs to add more settings typically accepted or are there specific requirements as to which props or types of props would be accepted?

PRs are always welcome! Currently the settings focus mostly about texts, sizes, variants and some general behavior of some components. If a PR contains one of this categories its safe to be merged, otherwise we need to think about it and try to come up with a good solution.

**Comment by tmorehouse** [comment]
Note that currently the prop defaults are pulled in on initial component instantiation (i.e. initial render), and changing the prop's default after the fact will not be reflected in the component until it has been destroyed and re-instantiated.

Another option for easing dynamic translation is to create an object with the desired props and values. and v-bind the object to the component:

```html
<template>
  <b-modal v-bind="translatedProps" size="sm" ...></b-modal>
</template>

<script>
export default {
   computed {
     translatedProps() {
        return {
          title: this.$t('Modal title'),
          okTitle: this.$t('OK'),
          cancelTitle: this.$t('Cancel'),
          closeTitle: this.$t('Close')
        }
     }
   }
}
</script>
```
