### ISSUE TITLE
Can we have a feature to add custom attribute to every row

### ISSUE THREAD

**Issue by RagavendhranN** [bootstrap-vue/bootstrap-vue#4510]
Can we have a feature to add custom attribute to every row like tbodyTrClass in b-table.
We can have something like tbodyTrAttr-onFocus="somefunction()". 
It will add onFocus="someFunction()" to every row.

 It would be very useful

**Comment by RagavendhranN** [comment]
Can we have a feature to add custom attribute to every row like tbodyTrClass. We can have something like tbodyTrAttr-onFocus="somefunction()". It will add onFocus="someFunction()" to every row. It would be very useful

**Comment by tmorehouse** [comment]
See https://github.com/bootstrap-vue/bootstrap-vue/pull/4481

Will be available in release v2.2.0

**Comment by tmorehouse** [comment]
BootstrapVue v2.2.0 has been released.
