### ISSUE TITLE
Mount popover component in test

### ISSUE THREAD

**Issue by yooouuri** [bootstrap-vue/bootstrap-vue#4514]
How can I open the popover in my jest test?

In `bootstrap-vue 2.0.0-rc.24` it renders the component, but when I upgrade to the latest version `v2.1.0` it doesn't.

Fixed the error where no target was found:

```
 document.body.innerHTML = '<div id="target"></div>';
```

Changed `show` property to `true`, no luck...

But the wrapper HTML keeps being empty

**Comment by tmorehouse** [comment]
Are you using vue-test-utils beta.30?  If so, downgrade to beta.29.

Version 2.0.0 stable introduced revamped popover and tooltip components.

Also, without seeing an example test, we can only make a guess at what is wrong with your test suite.

You can take a look at how we test popover component at https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/popover/popover.spec.js
