### ISSUE TITLE
<b-nav-item> is not consistent with the to attribute rendering of the <router-link> component

### ISSUE THREAD

**Issue by long-woo** [bootstrap-vue/bootstrap-vue#4518]
### Describe the bug

`<b-nav-item>` The` to` attribute of the component does not have a `#` sign, and the route is invalid
`<router-link>` component works

### Steps to reproduce the bug

![image](https://user-images.githubusercontent.com/3394035/71259109-9c13ab00-2372-11ea-8e3b-32a92af618c7.png)

![image](https://user-images.githubusercontent.com/3394035/71259177-c6fdff00-2372-11ea-9a7f-3d081a1d425f.png)

### Expected behavior

Same result as `to` attribute of` <router-link> `.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.4.1
- Vue: 2.6.11
- VueRouter: 3.1.3

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Electron
- Version: 2.0.18

**Comment by tmorehouse** [comment]
`<b-nav-item>` passes the `to` prop as-is to `<router-link>` (`<b-nav-item>` is just a wrapper for <router-link>`) when `this.$router` is detected.

**Comment by long-woo** [comment]
Same question.

![image](https://user-images.githubusercontent.com/3394035/71261749-22cb8680-2379-11ea-9622-2df4df66d51e.png)

**Comment by tmorehouse** [comment]
It almost sounds like BootstrapVue is not detecting `vue-router` in your app and is converting the `to` prop to a plain `<a>` tag.

**Comment by tmorehouse** [comment]
How are you installing Vue router?  Are you injecting the router into your top level app?:

```js
const router = new VueRouter({
  routes: [
    { path: '/foo', component: Foo },
    { path: '/bar', component: Bar }
  ]
})

const app = new Vue({
  router
}).$mount('#app')
```

**Comment by long-woo** [comment]
The pre-upgrade version `" bootstrap-vue ":" ^ 2.0.0-rc.6 "` is normal.

The routing configuration is as follows:
```js
export default new Router({
  routes: [
    {
      path: '/',
      component: Main,
      children: [
        {path: '', name: 'NewTask', component: () => import('@/views/NewTask')},
        {path: 'taskmanager', name: 'TaskManager', component: () => import('@/views/TaskManager')},
        {path: 'myorder', name: 'MyOrder', component: () => import('@/views/MyOrder')}
      ]
    }
  ]
})
```
