### ISSUE TITLE
Collapse component should have an option to stay open

### ISSUE THREAD

**Issue by rdgout** [bootstrap-vue/bootstrap-vue#452]
Hi guys,

I noticed there is no way to make sure the collapse component is open on init. Could it be possible to implement this?
It would be even better if we could manage the initial state with a prop.

AFAIK with regular bootstrap, it should be possible to keep it open.

**Comment by alexsasharegan** [comment]
After looking at the source, it looks like you might be right about not being able to set the initial state to open. For now, you could use the parent component's `mounted` hook to call `toggle` on the `collapse` child via a ref.

@tmorehouse @pi0 , could this be enabled via `v-model` kind of like the modal component?

**Comment by tmorehouse** [comment]
@alexsasharegan that might be an option, or a Boolean prop (read once on init to set the collapsed state)

**Comment by alexsasharegan** [comment]
It's certainly simpler. Maybe the prop name should convey that. Something like `showOnInit`? So many other components use `show` in a more interactive way, so it might be beneficial to distinguish things.

**Comment by tmorehouse** [comment]
Yeah, `showOnInit` would be more clear (and non-reactive)

**Comment by tmorehouse** [comment]
This would be as simple as:

```js
        data() {
            return {
                show: this.showOnInit
            };
        },
        props: {
            showOnInit: {
                type: Boolean,
                default: false
            },
            isNav: {
                type: Boolean,
                default: false
            },
            id: {
                type: String,
                required: true
            }
        },

**Comment by alexsasharegan** [comment]
Vue won't baulk at that right? You know the message about not manipulating props? That should just copy by value plain and simple.

**Comment by tmorehouse** [comment]
Yeah, since `data()` is a function, it is only returned once when the component is instantiated.

**Comment by tmorehouse** [comment]
@alexsasharegan do you want to take a stab at a PR for this?

**Comment by alexsasharegan** [comment]
Sure! I'll take some low-hanging fruit 😉

**Comment by alexsasharegan** [comment]
How come the example file looks different than the fiddle on the docs site?

**Comment by tmorehouse** [comment]
The examples currently do not propagate to JSfiddle, which is why it probably looks different.

The docs are based on current release as well, rather than master.

**Comment by alexsasharegan** [comment]
@rdgout This should be solved in the next release via `v-model` (v0.16.2). There will be an example in the component doc page.

**Comment by rdgout** [comment]
@alexsasharegan Looks good!

**Comment by rdgout** [comment]
@tmorehouse  Any ETA when the next release is going to be? I see a lot of issues are labeled 'coming soon'!

**Comment by tmorehouse** [comment]
No set date yet that I know of.  We have a few more PRs that need to be merged, and then there should be a new release soon thereafter.

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
