### ISSUE TITLE
Could bootstrap dependency be replaced with bootstrap-scss?

### ISSUE THREAD

**Issue by andrei-gheorghiu** [bootstrap-vue/bootstrap-vue#4523]
I noticed `bootstrap-vue` has `bootstrap` as a dependency. In turn, `bootstrap` _"requires a peer of `jquery@1.9.1 - 3`, **but none is installed"**_. Since my project doesn't use or need jQuery, I would like not to see a warning in console saying I need it, every time I run `npm i`.

Does `bootstrap-vue` require anything else from `bootstrap` than [`bootstrap-scss`](https://www.npmjs.com/package/bootstrap-scss)? Because if it doesn't (which I think is the case), `bootstrap` dependency should be replaced with `bootstrap-scss` dependency.

**Comment by tmorehouse** [comment]
It is possible, but we have noticed delays in the publishing `bootstrap-scss` when new versions of Bootstrap are released (as the `bootstrap-scss` is not maintained by the Bootstrap authors).
