### ISSUE TITLE
It is possible to config globally bootstrap-modal close button to be without any content inside?

### ISSUE THREAD

**Issue by 7iomka** [bootstrap-vue/bootstrap-vue#4527]
Hi.
It is possible to config globally bootstrap-modal close button to be without any content inside?
I want to use bootstrap-modal plugin for modals and message info-boxes on my site widget-app.
Site uses bootstrap.
Vue app uses your bundle.
On my site I get used customized layout for modals, and for close buttons I will used font icon version applied with pseudo-selector with css. For this case I removed any content inside close button (just used custom button with data-dismiss="modal").
Demo: https://keenthemes.com/metronic/preview/demo1/components/base/modal.html

My app used same styles, but I don't know how to remove content of close buttons globally on my Vue app.
![image](https://user-images.githubusercontent.com/18473137/71381176-1e060d00-25db-11ea-877d-641f8430e4f7.png)
Thanks for any ideas.

**Comment by tmorehouse** [comment]
There isn't a global way to change the content of the modal close button (which is really `<b-button-close>`).

You can however, use the `modal-header-close` slot to place any arbitrary HTML/Text/Component markup inside the header close button.

Note as well, you can't use the native bootstrap `data-*` API HTML markup (which is jQuery based).

**Comment by 7iomka** [comment]
> You can however, use the `modal-header-close` slot to place any arbitrary HTML/Text/Component markup inside the header close button.

How to do this if I use currently only this type of usage:
`this.$bvModal.msgBoxConfirm('some question')`
?

**Comment by jackmu95** [comment]
@7iomka No, there is currently no possibility to do that with `this.$bvModal.msgBoxConfirm()`.

**Comment by jackmu95** [comment]
@tmorehouse Maybe we would add a `content` prop to `<b-button-close>` which defaults to `'&times;'` and make this configurable in settings?

**Comment by tmorehouse** [comment]
@jackmu95 yeah, we might be able to provide a new prop (and maybe slot for b-modal) for the header close content.  It would default to `undefined` to fallback to the default content of the `b-button-close`
