### ISSUE TITLE
Downgrade doesn't work

### ISSUE THREAD

**Issue by bddexter** [bootstrap-vue/bootstrap-vue#4528]
In upgraded to v2.1.0. Realized that some features (after I checked) where falling down. Wanted to go back to v2.0.0-rc.28 but after I run npm install, things still arent working..

**Comment by bddexter** [comment]
I'm having specific issues with tables and slots. My old code (with v2.0.0-rc.28) was:

```
                        <template slot="details" slot-scope="row">
                            <b-button size="sm" @click="row.toggleDetails" :variant="themeVariant.colPrimary">
                                <icon :name="row.detailsShowing ? 'search-minus' : 'search-plus'" /> {{ row.detailsShowing ? 'Hide details' : 'Show details'}}
                            </b-button>
                        </template>
```

Bu this doesn't work anymore with v2.0.0-rc.28

**Comment by Hiws** [comment]
Looks like you didn't have rc.28 installed before either. Since that's no the correct syntax for that version.

The following should work.
`<template slot="[details]" slot-scope="row">`

**Comment by bddexter** [comment]
Tnx. But my route was a bit inverse. I sticked with version 2.1.0 and just updated my components with the new `v-slot` aproach. Thanks anyway!
