### ISSUE TITLE
Popover boundary in Modal

### ISSUE THREAD

**Issue by MasterBopoH** [bootstrap-vue/bootstrap-vue#4529]
### Describe the bug

Popover in Modal couldn't go over Modal boundaries

![Screen Shot 2019-12-24 at 4 46 00 PM](https://user-images.githubusercontent.com/5174683/71417725-83a3d900-266f-11ea-89af-998825a29fb2.png)

### Steps to reproduce the bug

https://bootstrap-vue.js.org/docs/components/modal/#tooltips-and-popovers example with modified to `v-b-popover.left="'Popover inside a modal!'"`
Or explicitly stated `<b-popover>` with any type of boundaries - window, viewport, etc.

### Expected behavior

There should be a way to go over Modal boundaries and have your popover shown fully in the direction you want.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.3.1
- Vue: 2.6.11

**Environment:**

- Device: MacBook Pro 2018
- OS: macOs High Sierra
- Browser: Chrome / Safari latest
- Version: 79.0.3945.88/ 13.0.4

I might've missed something and there is a way... but couldn't find it.
I would gladly appreciate any help.
Thanks.

**Comment by tomjdickson** [comment]
I am unable to reproduce the problem on example you provided.
![image](https://user-images.githubusercontent.com/44155439/71563329-faaef680-2ae1-11ea-8804-643e60bfe717.png)

**Comment by tmorehouse** [comment]
It sounds like you might have a class/css that sets `overflow: hidden` on the modal, or a browser extension that is altering overflow visibility.

**Comment by MasterBopoH** [comment]
@tmorehouse, hi.
Sorry for posting late. The issue was as you stated(styles altering modal overflow).
Thanks.
