### ISSUE TITLE
b-form-radio does not emit click

### ISSUE THREAD

**Issue by jd1378** [bootstrap-vue/bootstrap-vue#4530]
### Describe the bug

b-form-radio component does not emit click event

### Steps to reproduce the bug

1. Go to https://jsfiddle.net/4hyvwqza/
2. Open console and click on the second radio button
3. You should see log but you don't

### Expected behavior

Radio button should emit click event

**Comment by Hiws** [comment]
You might need to add the `native` modifer to the click event `@click.native`

**Comment by tmorehouse** [comment]
See https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components
