### ISSUE TITLE
[chore]: configure pre-commit hook for better DX

### ISSUE THREAD

**Issue by jamesgeorge007** [bootstrap-vue/bootstrap-vue#4532]
`pre-commit` hooks can come in handy while in the Dev workflow. The `lint` script can be made to execute automatically before making a commit (and staging updated files).

**Comment by jamesgeorge007** [comment]
I would be happy to shoot a PR on receiving a green signal :+1:

**Comment by jackmu95** [comment]
I would be fine with that if it doesn't effect the speed of commiting to much.
We need to make sure only relevant files are linted/prettified.

@jamesgeorge007 PR's are always welcome :)
