### ISSUE TITLE
`<b-pagination>` show total pages

### ISSUE THREAD

**Issue by liangwenjie08** [bootstrap-vue/bootstrap-vue#4533]
It would be nice if  `Pagination ` could show total pages and totals.

![1577342003(1)](https://user-images.githubusercontent.com/47054353/71462331-f63ac300-27ed-11ea-8687-02d27d2ad43e.jpg)

Let's say I have 100 pages of data. And left or right displays the totals of data.

**Comment by tmorehouse** [comment]
One simple workaround would be to set the text of the `>>` (last page) button to the total number of pages.
