### ISSUE TITLE
b-form-input slot for placeholder?

### ISSUE THREAD

**Issue by gtzures** [bootstrap-vue/bootstrap-vue#4535]
### Is your feature request related to a problem? Please describe...

It could be nice to customize the `placeholder` in `b-form-input`, e.g. change the font, perhaps add an icon.

### Describe the solution you'd like

Consider exposing a `v-slot:placeholder`

### Describe alternatives you've considered

For customizing the placeholder text, an valid alternative would be if the `placeholder` prop inherited the parent component style.

**Comment by jackmu95** [comment]
The `placeholder` prop of the `<b-form-input>` only sets the `placeholder` attribute of the HTML input.

You can make changes to the placeholder styling by using the `::placeholder` selector:
https://www.w3schools.com/cssref/sel_placeholder.asp
