### ISSUE TITLE
Tinymce-vue dialog unable to edit in bootstrap-vue modal.

### ISSUE THREAD

**Issue by asika32764** [bootstrap-vue/bootstrap-vue#4537]
See https://codesandbox.io/s/tinymce-vue-bootstrap-vue-modal-focusin-zxfjn

Use [official workaround](https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog) for bootstrap-vue modal not works. The Tinymce dialog are not editable.

```js
// Prevent Bootstrap dialog from blocking focusin
$(document).on('focusin', function(e) {
  if ($(e.target).closest(".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root").length) {
    e.stopImmediatePropagation();
  }
});
```

Seems works with native Bootstrap 4 https://codesandbox.io/s/bootstrap-tinymce-mxi9f

The issue also post at https://github.com/tinymce/tinymce-vue/issues/116

**Comment by gettingclouded** [comment]
Here's the pure Javascript version of the workaround.
```javascript
document.addEventListener('focusin', function (e) {
     let closest = e.target.closest(".tox-tinymce-aux, .tox-dialog, .moxman-window, .tam-assetmanager-root");
     if (closest !== null && closest !== undefined) {
          e.stopImmediatePropagation();
     }
});
```

**Comment by tmorehouse** [comment]
You could also try wrapping the MCE editor in a div with a `focusin` listener that stop upwards bubbling:

```html
<div @focusin.stop>
  <!-- MCE editor placed here -->
</div>
```

**Comment by jackmu95** [comment]
Setting the `no-enforce-focus` option works:
https://codesandbox.io/s/bootstrapvue-tinymce-vue-modal-focusin-kxhvm
