### ISSUE TITLE
Add slot to b-breadcrumb-item for custom content

### ISSUE THREAD

**Issue by RedShift1** [bootstrap-vue/bootstrap-vue#4540]
### Is your feature request related to a problem? Please describe...

Sometimes you want to add more advanced elements to a breadcrumb-item, for example a select box or another Vue component.

### Describe the solution you'd like

Add a slot to b-breadcrumb-item to freely place any content.

### Describe alternatives you've considered

Using the b-breadcrumb-item's html prop. However that only allows static HTML code, too restrictive.

**Comment by tmorehouse** [comment]
You can use the default slot of `<b-breadcrumb-item>`:

```html
<div>
  <b-breadcrumb>
    <b-breadcrumb-item href="/">Home</b-breadcrumb-item>
    <b-breadcrumb-item href="/foo">Foo</b-breadcrumb-item>
    <b-breadcrumb-item href="#bar">Bar</b-breadcrumb-item>
    <b-breadcrumb-item active>Baz</b-breadcrumb-item>
  </b-breadcrumb>
</div>
```

![image](https://user-images.githubusercontent.com/2781561/71624140-762ea780-2bb7-11ea-83ec-2277a1ae07b3.png)

**Comment by jinniw43805** [comment]
@tmorehouse 
Is anyway we can set the content via props? Like default for the content is : "/"
