### ISSUE TITLE
individual form-group elements are highlighting upon click

### ISSUE THREAD

**Issue by salfej** [bootstrap-vue/bootstrap-vue#4543]
### Describe the bug
I upgraded from `2.0.0-rc.19` to `2.1.0`, and now using the `form-group` element on radio buttons is causing every element within the form group to be highlighted with a focus outline. This only happens for radio buttons and checkboxes, but not for text input fields IF using `label-for`. 

![image](https://user-images.githubusercontent.com/10404888/71632073-0ed22100-2bd2-11ea-95c1-bb1faa3443f1.png)

![image](https://user-images.githubusercontent.com/10404888/71632059-f9f58d80-2bd1-11ea-82c4-c839b151e07f.png)

![image](https://user-images.githubusercontent.com/10404888/71632069-037ef580-2bd2-11ea-9402-f74836672c5e.png)

If `label-for` is not used, the highlight focus targets the text before hitting the inputbox.

![image](https://user-images.githubusercontent.com/10404888/71632680-602fdf80-2bd5-11ea-9446-2fc487889029.png)

### Steps to reproduce the bug

Upgrade from 2.0.0-rc.19 to 2.1.0

### Expected behavior

I would expect the focus to target the radio buttons or not happen at all, but it splits to effect every element contained in the <b-form-group> tag

### Versions

**Libraries:**

- BootstrapVue: 2.1.0 / 2.0.0-rc.19
- Bootstrap: 4.#.#
- Vue: 2.6.11

**Environment:**

- Device: N/A
- OS: N/A
- Browser: Chrome, Firefox
- Version: Chrome - 79.0.3945.88 (Official Build) (64-bit)

### Demo link
(I could not recreate the bug in the playground.)
https://codepen.io/salfej/pen/PowJEey

### Additional context
It's worth noting that the documentation says `label-for` is not to be used with checkboxes and radio buttons. That is the only thing preventing the `form-input` from the same behavior.

**Comment by tmorehouse** [comment]
Sounds like you are using Bootstrap v4.4.x CSS (not v4.3.1).

They made some changes in the `reboot.css` and no longer hide the focus ring for items that have `tab-index="-1"`, which is causing hte focus rings to appear.  Downgrade to Bootstrap v4.3.1 CSS.

BootstrapVue 2.2.0 will have support for Bootstrap v4.4.1

**Comment by salfej** [comment]
Ah! That is exactly my problem! Thank you!
