### ISSUE TITLE
<input> focused  bug when <b-row> has a class such as <b-row class="my-row-class">

### ISSUE THREAD

**Issue by lvbirui** [bootstrap-vue/bootstrap-vue#4544]
### Describe the bug
The input element can not get fouced after I do some saving data by clicking save button. 
After I click the other place like the desktop of my computer, the input can get fouced again.

HTML code
<template>

    <div>
        <b-container fluid class="my-container-class">
            <b-row class="my-row-class">
                <b-col>
                    <input type="text" name="" id="" v-model="inputData" v-if="!inputSatus">
                    <p v-if="inputSatus">{{inputData}}</p>
                    <button @click="editOrsaved">save</button>
                    <button @click="editOrsaved">edit</button>
                    <input type="text" name="inputForTest">
                </b-col>

            </b-row>
        </b-container>
    </div>
</template>

### Steps to reproduce the bug

1. click "edit" button to edit the "inputData"
2. Click "save" button to save the "inputData" to backend
3. click the <input> which named "inputForTest" andt it can not get focused
4. click other place such as other app or Desktop
5. click the "inputForTest" <input>, it can be get focused

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.3.1
- Vue: 2.5.6

**Environment:**

- Device: Dell PC
- OS: Windows 10
- Browser:Chrome

**Comment by Hiws** [comment]
I don't really think the row having a class is what's causing the issue.

https://codepen.io/Hiws/pen/XWJVedK
A simple copy/paste of your code (except the @click logic) doesn't have the issue you're describing.

What are you doing in the `editOrsaved` method, and could you make a reproduction of the problem in a codepen?

**Comment by lvbirui** [comment]
> I don't really think the row having a class is what's causing the issue. However, it could be that the CSS you're applying the provided class is potentially causing the issues. What CSS does the class add?
> 
> https://codepen.io/Hiws/pen/XWJVedK
> A simple copy/paste of your code (except the @click logic and class CSS) doesn't have the issue you're describing.
> 
> What are you doing in the `editOrsaved` method, and could you make a reproduction of the problem in a codepen?

Yes,I find a very strange bug that is the "alert()" makes the input can not get focused.
