### ISSUE TITLE
b-popover click blur trigger not closing popover on next click

### ISSUE THREAD

**Issue by jwells967** [bootstrap-vue/bootstrap-vue#4548]
This issue is reproducible in the bootstrap vue playground https://bootstrap-vue.js.org/play/

by pasting the following code block in the template section

```
<div>
  <a style="cursor: pointer; border: 1px solid black; padding: 5px;" title="Additional Actions" id="moreActions">
    <span>Click for actions</span>
  </a>
  <b-popover target="moreActions" triggers="click blur" placement="bottom">
    <div>
      <a style="cursor: pointer;" title="Test">Test</a>
    </div>
  </b-popover>
</div>
```

with the triggers="click blur" property set, documentation reads as though it should close the popover when you click in the whitespace

**Comment by jackmu95** [comment]
See this section in the docs which explains why the behavior is correct:
> If a popover has more than one trigger, then all triggers must be cleared before the popover will close. I.e. if a popover has the trigger focus click, and it was opened by focus, and the user then clicks the trigger element, they must click it again and move focus to close the popover.

**Comment by jwells967** [comment]
@jackmu95 I was attempting to replicate the behavior described in this part of the documentation, under "Dismiss on next click (self-dismissing)"

> You can, however, specify your trigger as click blur, which will make only a click activate the popover, and either a click on the element, or losing focus to another element or part of the document will close the popover.
>
> The special blur trigger must be used in combination with the click trigger.

even when adding another element to the dom, e.g. <b-button> and clicking the button so it takes the focus, the popover remains open. Is there a different way I can accomplish this behavior where the popover is opened only with the target click, but it is closed with a click anywhere outside the popover?

**Comment by tmorehouse** [comment]
Also, make sure you are using the latest BootstrapVue (2.1.0) and Bootstrap CSS/SCSS 4.3.1 (and of course BootstrapVue CSS/SCSS)

**Comment by jwells967** [comment]
the playground is using the correct version and css and still the issue appears there. 

should the documentation be altered?

**Comment by tmorehouse** [comment]
@jwells967 The main issue is that in he example you have the `<a>` without an `href`, so it is not an interactive element by default and cannot receive focus when it is clicked (`click blur` relies on the fact that the clicked element becomes the document active element and can therefore be blurred).

Either switch to an interactive element, like `<button>` or `<a href="#">`, or add a `tabindex="0"` (or `-1`) to the non-interactive element so that it is able to receive focus when clicked.

**Comment by jwells967** [comment]
@tmorehouse thank you
