### ISSUE TITLE
Can't use v-text with b-form-checkbox

### ISSUE THREAD

**Issue by rothskeller** [bootstrap-vue/bootstrap-vue#4549]
### Describe the bug

`<b-form-checkbox v-text="label"></b-form-checkbox>` does not work, even though `<b-form-checkbox>{{label}}</b-form-checkbox>` does.  When v-text is used, the child input and label elements of the div are overwritten by the text node added for v-text.

### Steps to reproduce the bug

1. Create a page using <b-form-checkbox> with a v-text attribute.
2. Notice that space is left for the checkbox, but no actual checkbox appears.
3. Look at the DOM and notice that the b-form-checkbox is rendered as a div containing a text node but not containing any input or label children.

### Expected behavior

Either (a) v-text should work correctly for b-form-checkbox, or (b) the documentation for b-form-checkbox should clearly call out this limitation.  Note this probably applies to b-form-radio as well.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.3.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome 
- Version: 79

**Comment by jackmu95** [comment]
See #4458 for an explanation why this isn't working, similar to the `v-html` slot.
Just use the default slot instead to render your label/text.

**Comment by rothskeller** [comment]
That's fine, but it took me hours to figure out what was happening and how to work around it.  This limitation needs to be clearly documented.  (I do see that you've added the appropriate label for that; thank you.)

**Comment by tmorehouse** [comment]
In general is is taboo to use `v-html` or `v-text` on a vue component (from any library). Those directives are really meant for use on native HTML elements.
