### ISSUE TITLE
Documentation for validation using VeeValidate v3

### ISSUE THREAD

**Issue by mcshaz** [bootstrap-vue/bootstrap-vue#4550]
Thanks for awesome library.

The current [documentation describes using vee-validate 2.x](https://bootstrap-vue.js.org/docs/reference/validation/#veevalidate)

At the time of writing veeValidate is at version 3.2.1

differences in the 3.x rewrite are described [here](https://www.baianat.com/articles/veevalidate-3-0)

in summary, the `v-validate` attributes are gone and scoped slots are used like so:
```HTML
<ValidationProvider rules="required" v-slot="{ errors }">
      <input type="text" v-model="input">
      <span>{{ errors[0] }}</span>
</ValidationProvider>
```

Would it be possible to update current docs such that:
1. the current example in the documentation be clearly marked as veeValidate 2.x
2. an example using veeValidate 3.x be added
3. if (2) above is not possible, a note to that effect be added

Thank you.

**Comment by mcshaz** [comment]
I just saw that vee-validate has a link to https://codesandbox.io/s/validation-components-bootstrapvue-usdwv?from-embed

**Comment by tmorehouse** [comment]
v2.2.1 has been released.

**Comment by mcshaz** [comment]
would it be worth changing the example to use vee-validate's auto generated error messages as per [this codesandbox](https://codesandbox.io/s/boostrapvue-veevalidate-v3-example-ysyz3)

**Comment by jackmu95** [comment]
@mcshaz I've updated both example to use VeeValidate's error messages.
