### ISSUE TITLE
how to hide tooltip with directive usage in an attempt to hover over its title? (like in original bootstrap)

### ISSUE THREAD

**Issue by 7iomka** [bootstrap-vue/bootstrap-vue#4556]
Hi!
Please, help me;
How to achieve default behavior for a tooltip when it is hiding in an attempt to hover over its title (content of tooltip)?
I prefer this behavior: http://jsfiddle.net/vdzvvg6o/
With bootstrap-vue I used directive variant  `v-b-tooltip.hover = { title: someTitle, container: relativeContainerId }`
Thanks!

**Comment by jackmu95** [comment]
@7iomka You are right; the behavior between Bootstrap and BootstrapVue is different.
IMHO we should make the behavior configurable since I see a need for both cases.

**Comment by Hiws** [comment]
A temporary workaround for this could be to apply a class with the style `pointer-events: none;` to each tooltip where you want that behaviour.

```html
<b-btn v-b-tooltip.hover="{ customClass: 'my-tooltip-class' }" title="Good job!">
  Hover me
</b-btn>

<style>
.my-tooltip-class {
  pointer-events: none;
}
</style>
```

**Comment by 7iomka** [comment]
> A temporary workaround for this could be to apply a class with the style `pointer-events: none;` to each tooltip where you want that behaviour.

Thanks for the solution. For compatibility, since bootstrap-vue adds a separate `b-tooltip` class to tooltip, I added `pointer-events: none;` to `.b-tooltip` to achieve compatibility, and only in rare cases when there is a need for the availability of mouse events on the tooltip content would I make suggestions to add `interactive` mod for directive or option for plugin, with false value by default.

**Comment by tmorehouse** [comment]
BootstrapVue v2.2.0 has been released.
