### ISSUE TITLE
Form File Input Doesn't Update with V-Model programmatically?

### ISSUE THREAD

**Issue by marbuser** [bootstrap-vue/bootstrap-vue#4557]
### Describe the bug
I'm making a CRUD application, and when I'm editing a resource I send a request to the file (in this case an image), convert the blob into a File and then set it on the File Input (https://bootstrap-vue.js.org/docs/components/form-file/). Problem is, even though under the hood the state is reactive, the component itself doesn't update to reflect this.

E.G It still says this;
![image](https://user-images.githubusercontent.com/34422459/71803564-18f59300-309c-11ea-89b4-22552d143838.png)
Instead of this;
![image](https://user-images.githubusercontent.com/34422459/71803591-26ab1880-309c-11ea-81b6-aeddacfebdeb.png)

### Steps to reproduce the bug
1. Make a v-model File Input.
2. Make a request with a `responseType` of `blob` in `created()` and set the v-model attribute to be equal to `new File([res.data], 'filename');`

### Expected behavior
When setting a file programmatically the component should visually reflect this. The functionality of the component itself is fine and works perfectly, but the visual aspect of the component doesn't seem to work all too well.

**Comment by jackmu95** [comment]
@marbuser What you wan't so archive isn't possible for a file input due to security reasons.

**Comment by tmorehouse** [comment]
The native HTML5 `<input type="file">`  attribute `value` (and dom prop `files`) cannot be set on most (if not all) browsers due to security limitations on the file type input..
