### ISSUE TITLE
Props not correctly updated when using modal and vuex

### ISSUE THREAD

**Issue by Titoine** [bootstrap-vue/bootstrap-vue#4562]
### Describe the bug

When I encapsulate my parent component in a modal, the prop it pass to the child doesn't get updated correctly.

#### Parent component:
Has two buttons:
**save** : grab the counter data property from the child and save it to the store.
**reset** : emit and event that reset the store counter value to a default value (0).
#### His child component:
The child component has:
a props 'defaultValue' 
a counter data property
**increment** button that increment his counter data property.
a reset method to set back his counter data property back to the 'defaultValue' props.

Also his counter data property is set by default to the 'defaultValue' props. 

### Steps to reproduce the bug

1. Increment
2. Save
3. Reset 
4. Child doesn't reset his counter data property back to the 'defaultValue' at the first reset event.

### Expected behavior

Correctly update his counter data property with the updated defaultValue props.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Vue: 2.6.10
- Vuex: 3.1.2

**Environment:**

- Browser: Chrome
- Version: 79.0

### Demo link

Here you can see the child component correctly working when the parent isn't encapsulated in a modal : https://codesandbox.io/s/computed-props-to-child-0uukh
And where the bug appear :
https://codesandbox.io/s/computed-props-to-child-in-modal-ruxch

**Comment by Hiws** [comment]
I can't very well explain why this is happening.

But if you utilize `setTimeout` instead of `nextTick` it appears to function as intended

```js
async reset() {
  this.resetStore();
  setTimeout(() => {
    this.$refs.child.reset();
  })
}
```

**Comment by tmorehouse** [comment]
Modals are portalled to be appended to the bottom of the screen, and also are rendered lazily to trigger the animations.  Both add delays to when the content is actually available via `this.$refs`. Portalling adds a `nextTick` delay as to when the content is updated, and the transition triggering adds in a `requestAnimationFrame` delay.
