### ISSUE TITLE
Form textarea component // rows attribute doesn't work if set to 1 

### ISSUE THREAD

**Issue by Nincha** [bootstrap-vue/bootstrap-vue#4568]
Hi there,

Using the Form textarea component : https://bootstrap-vue.js.org/docs/components/form-textarea

When **rows** attribute is set to 1 like the following:

`<b-form-textarea id="textarea" v-model="message" placeholder="..." rows="1" max-rows="3"></b-form-textarea>`

It appears that the minimum of rows is 2 rows no matter what. I thought about what if it was intentionnal, but the way I see it using rows="1" is a simple way to simulate a single line input that would autosize if needed.

Or maybe did I miss something?

Cheers,
Charlie

**Comment by Hiws** [comment]
Looking at the [properties](https://bootstrap-vue.js.org/docs/components/form-textarea/#comp-ref-b-form-textarea-props) section of the `b-textarea` docs state that the minimum number of rows bust be greater than 1.

Looking at the source code i found the following computed method that handles the minimum rows. Note the comment.
https://github.com/bootstrap-vue/bootstrap-vue/blob/b3ad7264d9b10fb1b8dfba70c62eed11a56519d6/src/components/form-textarea/form-textarea.js#L77-L82

**Comment by Nincha** [comment]
Oh okay, thanks for the quick answer!

Maybe a small info precision about that should be added to the doc? :)

**Comment by jackmu95** [comment]
> Maybe a small info precision about that should be added to the doc? :)

See: https://bootstrap-vue.js.org/docs/components/form-textarea/
