### ISSUE TITLE
B-form-input type=date and Safari support

### ISSUE THREAD

**Issue by dblinov** [bootstrap-vue/bootstrap-vue#4575]
### Describe the bug

It seems there is no support go <b-form-input type="date"> by Safari despite there is only comment in Docs about date time type. It works perfectly on iOS Safari, Chrome, but no on MacOS Safari :(

### Steps to reproduce the bug

It is visible even if to use official BV Documentation: https://bootstrap-vue.js.org/docs/components/form-input
Field with date type is not working on Safari. I reluctant to use external library for that. Could you please recommend a solution?

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: iMac
- OS: MacOS Catalina v.10.15.2
- Browser: Safari v.13.0.4

### Demo link

```
              <b-form-input
                  type="date"
                  v-if="selectedTaskLoaded"
                  v-model="selectedTask.planned_date"
                  size="sm"
                  :disabled="!selectedTaskEditStatus"
              ></b-form-input>
```

Thank you very much in advance

**Comment by tmorehouse** [comment]
It appears that MacOS Safari does not support the browser native HTML5 date input picker: https://caniuse.com/#feat=input-datetime

**Comment by dblinov** [comment]
> It appears that MacOS Safari does not support the browser native HTML5 date input picker: https://caniuse.com/#feat=input-datetime

Thank you, Troy! What can you recommend to replace with?

**Comment by tmorehouse** [comment]
There are some 3rd party datapicker components available (most are not very accessibility friendly though)

https://bootstrap-vue.js.org/docs/misc/third-party
