### ISSUE TITLE
Readonly issues when using vue externally (CDN)

### ISSUE THREAD

**Issue by CrashyBang** [bootstrap-vue/bootstrap-vue#4577]
### Describe the bug

I am receiving multiple `readonly` errors form `bootstrap-vue` modules when loading Vue from a CDN, the errors in question were discussed extensively in [#3040](https://github.com/bootstrap-vue/bootstrap-vue/issues/3040).  

### Steps to reproduce the bug

1. Load in vue via https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.runtime.js
2. Import some `bootstrap-vue` components: `import { BCard, BCollapse, VBToggle } from 'bootstrap-vue';`
3. Build a component (`UMD` format).
4. Open browser
5. Components work as expected (more or less) but console is full of errors.

### Expected behavior

No console errors.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.4.1
- Vue: 2.6.10

**Environment:**

- Device: Desktop
- OS: Ubuntu 18.10
- Browser: Chrome
- Version: 79.0.3945.88

### Demo link

It is difficult to put together because I have a fairly custom build process, I am hoping it is obvious based on the description, if not I can try to put a demo together by just copy/pasting a built component.

### Additional context

This has only become an issue in recent versions of `bootstrap-vue` I think it may be to do with [`portal-vue`](https://github.com/LinusBorg/portal-vue).

**Comment by tmorehouse** [comment]
This is because BootstrapVue also imports `Vue`, so you are getting two different instances of Vue in your project.

Is there any particular reason your are loading Vue from a CDN, since it appears you are using a build tool (such as webpack)?

**Comment by CrashyBang** [comment]
Hey @tmorehouse,

Yeah unfortunately there is we bundle a whole bunch of vue components in UMD format and then load them on demand in the browser and use the global `vue`  instance (from the CDN) to instantiate them (it's a long story).

Is there anyway to tell `bootstrap-vue` about the global instance? Perhaps with an alias in rollup? I am just not sure what the value would be for it?

Cheers.

**Comment by tmorehouse** [comment]
You can tell rollup that `Vue` is a global variable.  Something similar to the following rollup.config.js:

https://github.com/bootstrap-vue/bootstrap-vue/blob/704d89a3d63b1bc6f20c26a940c8bd228d8378fb/scripts/rollup.config.js#L38-L54

**Comment by CrashyBang** [comment]
Hey @tmorehouse ,

Awesome thank you! I will try that now, sorry I probably could have got there myself it only really become clear as we were talking!

Cheers!

**Comment by CrashyBang** [comment]
Hey @tmorehouse,

I have tried both using `alias` and `globals`, can I just confirm I am understanding this right.

I have the following config (which gets applied to each rollup entry) which essentially just applies my plugins:

```js
import path from "path";

import alias from '@rollup/plugin-alias';
import resolve from '@rollup/plugin-node-resolve';
import url from '@rollup/plugin-url';
import babel from 'rollup-plugin-babel';
import commonjs from '@rollup/plugin-commonjs';
import vue from 'rollup-plugin-vue';
import replace from '@rollup/plugin-replace';

const enviroment = process.env.NODE_ENV;

const development = enviroment === "development";

const augment = configs => {

    const generateAlias = (symbol, location) => {
        return {
            find: symbol,
            replacement: path.resolve(process.cwd(), location)
        };
    }

    const entries = [
        generateAlias("@", "src/"),
        generateAlias("~", "src/assets/scss/"),
        generateAlias("#", "src/assets/img/"),
        generateAlias("%", "config/"),
    ];

    const plugins = [
        alias({
            'vue$': 'Vue',
            entries
        }),
        resolve({ browser: true }),
        url({ /* url config */ }),
        babel({
            exclude: 'node_modules/**'
        }),
        commonjs(),
        vue(),
        replace({
            'process.env.NODE_ENV': JSON.stringify(enviroment)
        }),
    ];

    return configs.map(entry => {
        return {
            ...entry,
            plugins
        }
    });
}

export {
    augment
}
```

And then I have a config file like this:

```js
import { augment } from '../utilites';

const components = [{
        input: 'src/components/ExampleComponent.vue',
        output: {
                name: 'example_component',
                file: 'dist/example_component.umd.min.js',
                format: 'umd',
                globals: {
                        vue: 'Vue'
                }
        }
}];

export default augment(components);
```

Now neither the `alias` nor the `globals` config seem to resolve this issue.

So from what I understand the `bootstrap-vue` modules are using their *own* version of Vue and then I am loading it a second time (via the CDN) and the 2 instances of Vue are conflicting? And essentially I am *trying* to tell `bootstrap-vue` to use the global Vue instance when bundling?

**Comment by tmorehouse** [comment]
BootstrapVue components do:

```
import Vue from 'vue'`

export const CmpName = Vue.extend({
  // component definition here
})
```

You shouldn't need an alias for `Vue` if you are telling rollup that `Vue` is a variable in the global scope (i.e. `window.Vue`)

**Comment by CrashyBang** [comment]
Hey @tmorehouse,

Bizzare, I will keep looking into this and post if I find a solution.

Cheers!

**Comment by CrashyBang** [comment]
Got it!

Needed to be:

```js
{
        input: 'src/components/ExampleComponent.vue',
        external: ['vue'],
        output: {
                name: 'example_component',
                file: 'dist/example_component.umd.min.js',
                format: 'umd',
                globals: {
                        vue: 'Vue'
                }
        }
}
```
