### ISSUE TITLE
Update table row color after API call

### ISSUE THREAD

**Issue by antoinecsk** [bootstrap-vue/bootstrap-vue#458]
Hi, how can i refresh my table row state after an asynchronous operation ? 

HTML:
` <b-table striped hover :items="books" :fields="fields" :per-page="10" :filter="filter">`

JS : 
```
 saveBook(book).then(() => {
            book.state = 'success'
            this.saveBook(i+1)
          }).catch(err => {
            if (err) {
              const status = err ? err.response.status : undefined
              book.state = status === 409 ? 'warning' : 'danger'
            }
```
i need to define row color when API call failed or succeed, and the color only appears when i modify the table directly (checking a box for example)

**Comment by alexsasharegan** [comment]
I'm sure @tmorehouse will have an idea, but I think we're talking about one of Vue's main reactivity gotcha's—[mutating arrays & objects reactively](https://vuejs.org/2016/02/06/common-gotchas/).

Assuming that `book` represents a data object in your items array, how are you accessing `book`?
 It could be the book you have a variable of is a different object reference than the reactive book in your items array. Alternatively, you might not have a state property initialized on your book item.

Maybe include a little more code for a fuller context?

**Comment by alexsasharegan** [comment]
I'm thinking you'll have to loop through your book collection initially and do something like `const items = bookCollection.map( book => Object.assign(book, { state: null }) )`. This will allow vue to make every book item reactive.

**Comment by antoinecsk** [comment]
Just added 
`   for(let i = 0; i < results.length; i++) {
         results[i].isSelected = false
        ->    results[i].state = null
          }`
in my fetching function and it worked ! Thanks for the help !

Regards
