### ISSUE TITLE
<b-form-file> v-model is not readable

### ISSUE THREAD

**Issue by dragoono** [bootstrap-vue/bootstrap-vue#4580]
### Describe the bug

I am using the form file component in multiple mode and try to upload them to my backend. But the array is always null if I use v-model for it. Somehow the data is not going automatically in the model. 

But when I display the name of each file it works. I looked for some explanation why this happen and what is the best solution to just use the model instead of creating the file objects myself but didn't found any

Implementation:

![Bildschirmfoto 2020-01-09 um 09 41 25](https://user-images.githubusercontent.com/16446467/72054173-c351fe00-32c8-11ea-8189-a303789d1891.png)

Result: 

![Bildschirmfoto 2020-01-09 um 09 41 42](https://user-images.githubusercontent.com/16446467/72052286-2e99d100-32c5-11ea-839d-cd59d321edaa.png)

### Expected behavior

The v-model is filled automatically with the file data

**Comment by tmorehouse** [comment]
The v-model value is an array of `File` objects, which can't be serialized by Vue into text via `{{ form.files }}`.

How are you attempting to upload the data (native form submit or an Axios call)? Could you provide some of your JavaScript code for your component?

**Comment by dragoono** [comment]
> The v-model value is an array of `File` objects, which can't be serialized by Vue into text via `{{ form.files }}`.
> 
> How are you attempting to upload the data (native form submit or an Axios call)? Could you provide some of your JavaScript code for your component?

I send everything with axios. I wanted to send it with my other data 
`form: {
        selectedCategoryId: null,
        description: '',
        supportedByCompany: null,
        preWorkDone: null,
        otherInformation: '',
        street: '',
        plz: '',
        place: '',
        files: []
      }`
Where files is the model for the input. But when i send it to my laravel backend I can't read it.

At first I was not able to read the v-model itself so i'm using the change method now:
`<b-form-file
              @change="onChangeFiles"
              multiple
              id="project-application-attachments-files"
            >`

`onChangeFiles(evt) {
      this.form.files = evt.target.files
    }`

Somehow it's only readable if I put it into a FormData Object.

So now I send the files on another api call with a FormData attribute. Also I had to add each file as one item in the FormData (but this could be some Problems with laravel and spatie/laravel-medialibrary).

`let formData = new FormData()
      let i = 0
      Array.from(this.form.project.files).forEach((file) => {
        i++
        formData.append('files[' + i + ']', file)
      })
      formData.append('id', newValue.data.id)

      this.$store.dispatch('projects/saveFiles', formData)`

And in my backend:

`public function saveFiles(Request $request){
        error_log("Want to save files: ". json_encode($request->all()));
        $project = MacherbusProject::query()->find($request->input('id'));

        if($request->hasFile('files.*')) {
            error_log("images found");
            $fileAdders = $project
                ->addMultipleMediaFromRequest(['files.*'])
                ->each(function ($fileAdder) {
                    $fileAdder->toMediaCollection('gallery');
                });
        }
    }`

It works now. It would be nice to be able to just read the v-model itself but there were much more problem.

Who thought it's so complicated to just upload multiple files.

**Comment by tmorehouse** [comment]
Files are always complex when uploading via JavaScript (i.e. instead of native form submit action).

https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications#Example_Uploading_a_user-selected_file
