### ISSUE TITLE
[question] Dropdown: adjust dropdown menu height and content overflow

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#459]
I'm working to accommodate mobile devices in my application, and we have various large dropdown lists to render. From pretty much any point on the page, our dropdown menus exceed the page size. Unfortunately, this isn't a scrollable page, but more of the mobile-app style with full screen content.

Is there a good way to apply some styling to control menu size and overflow? I imagine I could just apply some more nested css selectors (although I've been going strong with flat classes thus far):

```sass
.my-component .dropdown-menu {
  max-height: $really-tiny-mobile-menu-height;
  overflow-y: scroll;

  @media (min-width: $not-tiny-mobile){
    // media query stuff
  }
}
```

But beyond that, any ideas for calculating height based on the position of the element on the page and the size of the page? Maybe just use a `mounted` hook to grab an element position, and yada-yada some size calc logic? Seems a bit manual. Thoughts?

**Comment by alexsasharegan** [comment]
I'm finding some interesting data by using `element.getBoundingClientRect()`. Among the object props returned are the x, y, w, & h of the element relative to the viewport.

**Comment by tmorehouse** [comment]
There are some changes coming to native Bootstrap V4 dropdowns.

One option I used to do, is control the menu CSS positioning/size for small screen (media query) and make the menu basically full screen (minus a bit so people could click out of it).

**Comment by tmorehouse** [comment]
I'll see if i can find my old CSS for small screen dropdowns.  It is based on BS V3 though.

**Comment by alexsasharegan** [comment]
Thank you! I'm realizing now that a dropdown isn't the most ergonomic UX tool for my needs here, but if you can find that CSS, paste it into here for posterity and I suppose we'll close this. It's another one of those _"shelf it until BS4 is more mature"_ things.

**Comment by tmorehouse** [comment]
The CSS trick isn't that bad... basically just positioning of the dropdown (using `!important` on `position:fixed` and `top/left/right/bottom`, and `overflow-y:auto`), and just rely on the rest of native BS CSS to display it..

Basically it make the dropdown work like native selects on some mobile browsers.

**Comment by alexsasharegan** [comment]
Ah, I think I follow! That's a good one to keep in my back pocket!

Any objections to me just closing this? If anyone finds this again, we can reopen after BS4 has made their updates to the dropdown component styling.

**Comment by tmorehouse** [comment]
No objections.

I'll post the CSS here once I find it

-Troy
