### ISSUE TITLE
b-pagination with custom classes for numbers, first and last item

### ISSUE THREAD

**Issue by okatsuralau** [bootstrap-vue/bootstrap-vue#4597]
### Is your feature request related to a problem? Please describe...

There is currently no option to provide a custom class for the `.page-item` element to customize the appearance of these items.

### Describe the solution you'd like

There should be a option to add a custom class to the `.page-item` element referring to numbers, first-page, previous, next and last-page.

**Comment by tmorehouse** [comment]
A partial workaround is using scoped styles and [Vue-loader's deep selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements):

```html
<template>
  <b-pagination class="my-class" ...></b-pagination>
</template>

<style scoped>
.my-class /deep/ .page-item {
  /* style overrides here */
}
.my-class /deep/ .page-item .page-link{
  /* style overrides here */
}
</style>
```
