### ISSUE TITLE
v-b-tooltip with trigger `hover` works like `click` on mobile

### ISSUE THREAD

**Issue by cwansart** [bootstrap-vue/bootstrap-vue#4599]
### Describe the bug

When using the `v-b-tooltip` with the trigger `hover` it works as clicked on mobile -- at least on Firefox and Safari on iOS. I expected there nothing to happen. The issue with that behavior is, that the tooltip won't close until you tap somwehere else.

### Steps to reproduce the bug

1. Checkout my example project https://github.com/cwansart/bootstrap-vue-tooltip-trigger
2. Run `yarn install` and `yarn serve` and open the network address printed in the log on your mobile device.
2. Click on _Projects_ and on _Start_ again. Start won't open at all whereas the link that is equipped with the trigger `hover` opens.

Or check this recording I did: https://www.youtube.com/watch?v=kUK2N05koY8

### Expected behavior

I expected the tooltip not to be opened at all on mobile devices.

### Versions

**Libraries:**

- BootstrapVue: 2.2.0
- Bootstrap: 4.4.1
- Vue: 2.6.11
- core-js: 3.4.4

**Environment:**

- Device: iPhone Xs
- OS: iOS 13
- Browser: Firefox and Safari
- Version: Firefox 21.0 (16918) and Safari the most recent one

### Demo link

Since I had to test it on mobile and run it somewhere I created a demo project locally. But you can find the code here: https://github.com/cwansart/bootstrap-vue-tooltip-trigger

### Additional context

I am not sure how this is supposed to work. We had an older version of bootstrap-vue in use but the behavior has changed. To be specific, check the behavior on https://beta.foodsharing.de and on https://foodsharing.de
On the top there are icons. On beta we have the recent version of bootstrap-vue, on the normal page we currently use 2.0.0-rc.28.

**Comment by tmorehouse** [comment]
Some mobile browsers will trigger both hover and click when tapping on an element, depending on the element type  (i.e. a button or link versus a non interactive element such as a span)

**Comment by cwansart** [comment]
Okay, I was not aware of that. Then I guess I have to test different elements I guess.
I wonder, why the behavior is different on 2.0.0-rc.28.

**Comment by tmorehouse** [comment]
v2.0.0 stable introduced new code for tooltips and popovers, which is different than the code in the RC releases.

I'll take a look at the code to make sure something isn't awry with the trigger event handlers.

Do you see a similar issue if using the component version of tooltips?

**Comment by tmorehouse** [comment]
I just checked the trigger handling code an all looks correct (hover is `mouseenter/leave`, and click is `click`).

**Comment by cwansart** [comment]
> Do you see a similar issue if using the component version of tooltips?
I did not check that yet. I thought both are the same.

So I guess there is only try and test left over?

**Comment by tmorehouse** [comment]
In some mobile browsers, hover is triggered on a long press of the element, while click is triggered on a short press (some mobile browsers have a delay of 300ms before triggering click, unless certain CSS is applied to the element to change the behaviour)

**Comment by cwansart** [comment]
Okay. Thank you so far. Then I guess this is not a bug and this issue can be closed.
