### ISSUE TITLE
Preloading content inside collapse - transition problems

### ISSUE THREAD

**Issue by 7iomka** [bootstrap-vue/bootstrap-vue#4601]
### Is your feature request related to a problem? Please describe...

1) Create collapse
```
<b-button v-b-toggle.collapse-1-inner size="sm">Load content and show</b-button>
<b-collapse id="collapse-1-inner" class="mt-2">
        <b-card v-if="isLoading">content loading ...</b-card>
        <div v-else>
          ... some large content
        </div>
</b-collapse>
```
2) When user click to button trigger, collapse was shown with preloader text. When response from server is received, isLoading will be false, then div with content will be immediately showed without any animation or transition.
I have a list of items in my application, each of which is a group of sub-items that, when clicked, must first be loaded from the server and then rendered inside collapse.
I want it done smoothly
Perhaps there is a workaround for this?
### Describe the solution you'd like
I don’t know what the solution might look

### Describe alternatives you've considered
When I wrote something like this in vanilla javascript, I calculated the heights of the new content before pasting and animated the current height to a new one.

**Comment by tmorehouse** [comment]
`b-collapse` transitions the `height` css property, and computes the height before the transition starts (sets height to 0, then gets the scroll height of the current content, and then sets the height to that value... which CSS kicks in and transitions the container).  Once the transition completes the height value is removed (back to auto).

This is why the height does not animate when you change the content after the fact.

**Comment by 7iomka** [comment]
> This is why the height does not animate when you change the content after the fact.

I just understand why, but I don’t know how to get around this so that UX does not suffer.
If not use for this case collapse, then what to use?

**Comment by tmorehouse** [comment]
maybe trigger a `this.$forceUpdate()` after the content is changed... although i do not think it will help, as the transition needs to compute the height before the content is expanded. If the content changes during the transition, it can't be computed.

Perhaps, use the v-model to show the collapse, and before triggering the show, update the content

**Comment by tmorehouse** [comment]
Closing as a can't fix (it would add too much additional JS code to handle this edge case).
