### ISSUE TITLE
b-table not accept array of Proxys

### ISSUE THREAD

**Issue by miladazhdehnia** [bootstrap-vue/bootstrap-vue#4603]
### Describe the bug

for b-table we must pass key and label for every fields, but for some reasons we have fn instead of key and dn instead of label
for that we create every field as a Proxy object , there is the Proxy handler of fiel : 

```js
  get: function (obj, prop) {
    if (prop == 'key') return obj.fn
    if (prop == 'label') return obj.dn
    if (prop == 'thStyle') return {
      width: obj.dp + '%'
    }
    if (prop in obj) return obj[prop]
    else {
      return
    }
  }
```

but b-table throw an error : 

> Error in getter for watcher "isSortable": "TypeError: Cannot read property 'replace' of undefined"

any solution?

### Versions

**Libraries:**

- BootstrapVue: 2.0.4
- Bootstrap: 4.#.#
- Vue: 2.6.11

**Environment:**

- Device: pc
- OS: windows 10
- Browser: chrome
- Version: 79

**Comment by tmorehouse** [comment]
B-table normalizes the fields array (or creates one if none provided). Note that Vue also sets reactive watchers on the properties of the object, and the above getter may be interfering with Vue's reactivity getters and setters (and it looks like you might be missing the setter).

Perhaps you should be mapping your fields array object to an expected format:

```js
return myFields.map(obj => {
  obj.key = obj.fn
  obj.label = obj.dn
  obj.thStyle = { width: obj.dp + '%' }
  return obj
})
```
