### ISSUE TITLE
Add custom classes to individual options and callbacks to disable field on <b-form-select> component

### ISSUE THREAD

**Issue by Garanaw** [bootstrap-vue/bootstrap-vue#4611]
### Is your feature request related to a problem? Please describe...

Not explicitly related to an issue, although it'd be a nice feature to have.
Previously, while using a normal `select` field, I could do this to add a specific class to an individual `option`:

```
<select class="form-control" v-model="selected" :disabled="isSelectDisabled()">
	<option disabled>--- Select Something ---</option>
	<option
		v-for="option in myOptions"
		:value="option "
		:disabled="isOptionSelected(option)"
		:class="{'strikethrough':isOptionSelected(option)}"
	>
		{{ option.text }}
	</option>
</select>
<b-btn @click="selectOptionFromModel">Select Option</b-btn>
```
being `isOptionSelected(option)` a method in my component returning a boolean whether the option has been selected.

Now I'm using the `BFormSelect` component to pass an array of options so I don't have to create the select myself.
I have noticed that passing a callback to `{disabled: myCallback}` only evaluates when building the options object. It'd be great if that callback could be re-evaluated on an event.
Also, I cannot pass a custom class anymore depending on the option being selected.

### Describe the solution you'd like

For the `disabled` field, it'd be a good solution to allow a custom event being caught by the component so the callback assigned to this property can be re-evaluated when the even is fired (passing the option value as an argument).

For the custom classes, I'd suggest a `optionClass` property in the object that could accept the same values that can be passed to the `:class="[...]"` property. In the case of a callback being passed as condition to apply the class, the option value should be passed

### Describe alternatives you've considered

Currently I am re'evaluating those callbacks when needed so I can enable/disable the options acordingly by finding them in the array of options and setting the `disabled` property to what I need. As for the custom classes, there isn't much that can be done other than modifying the DOM with vanilla JS, which is a bad idea when using Vue, so I can live without those classes as long as the option is disabled.

**Comment by tmorehouse** [comment]
`<b-form-select>` doesn't restrict you to using only an array of options, you can place `<option>` (or b-form-select-option) elements within the select, where you can place classes etc on the individual options. This (the default slot) is provided for greater control over the rendering of individual options.

When passing an array of options to `<b-form-select>`, the options are first "normalized" (via a computed prop) into a format needed internally.

**Comment by ux-engineer** [comment]
I need to implement nested options text based on nesting level value. Doing it with options groups would add up to a complex logic, and unselectable group titles when I need every row to be selectable. Using custom classes would be so much simpler!

**Comment by tmorehouse** [comment]
Noting is preventing you from placing custom classes on `<option>` or `<b-form-select-option>` components.

**Comment by ux-engineer** [comment]
> Noting is preventing you from placing custom classes on `<option>` or `<b-form-select-option>` components.

That's true, but as I've implemented a custom wrapper component for a form select group, I'm wary of introducing significant additional complexity on that component. Where as having an optional "customClasses" property on options objects handled by the library itself would be so much simpler.

Would it be hard to for you to implement, or affect performance with handling large options datasets even when that feature would not be used?

**Comment by tmorehouse** [comment]
It would make the b-form-select more complex, just like it would make your own wrapper component more complex.

And doing a v-for to get you the layout you like is maybe two extra lines of template markup

```html
<b-form-select v-bind="{ ...$props, options: null }" v-on="$listeners">
  <option v-for="opt in options" :key="opt.text" :class="opt.class" :value="opt.value">
    {{ opt.text}}
  </option>
</b-form-select>
```
