### ISSUE TITLE
close-only for modal

### ISSUE THREAD

**Issue by tristanbes** [bootstrap-vue/bootstrap-vue#462]
Hello,

Right now, there is an option for `ok-only` to display action button. Would it be possible to add a `cancel-only` prop, so we can show only the cancel button ? 

Simple use case would be: modal containing a call to action, but the user cannot meet the requirement, so the only choice is to close the modale.
ex: 
```vue
    <b-modal
      @ok="submit"
      @shown="fetchContent"
      :ok-title="trans('submit')"
      :cancel-only="errors.length > 0"
    ></b-modal>
```

**Comment by tmorehouse** [comment]
You can cheat. Use the okOnly and change the OK Text to something else (like 'cancel').

Or just use the footer slot to put your own buttons in there.

**Comment by tmorehouse** [comment]
But another option might be to use `noOk` and `noCancel` props (defaulting to `false`.  This would mean removing `okOnly`.   As it would be weird if one used `cancelOnly` and `okOnly` at the same time (which one should take precedence?).

**Comment by tmorehouse** [comment]
@alexsasharegan and @pi0 

What do you think of ability to disable either Ok or Cancel?  or should this be done using footer slot?

**Comment by alexsasharegan** [comment]
I think the functionality already offered by BV is handy for the most common use case. More than that, I think using the slot for custom logic is better. Maybe the docs should include an example of that though.

**Comment by tmorehouse** [comment]
Yeah, the footer slot can allow greater flexibility, and the click logic can be in your parent app or component too, making it easier to control the logic flow.

Extra docs/examples would be good for modal, showing various use cases for be great for sure.

**Comment by tmorehouse** [comment]
Here is an example of using custom buttons in the footer:

**Template:**
```html
<div class="mb-4">
  <b-btn v-b-modal="'mymodal'">Show Modal</b-btn>
  <b-form-select v-model="selected" :options="options">
  </b-form-select>
</div>
<b-alert dismissible :show="Boolean(message)">{{ message }}</b-alert>
<b-modal hide-header-close id="mymodal" v-model="modalShow" title="My Modal">
  <p class="lead">Hello From Modal!</p>
  <p>I have button(s): {{ selected }}</p>
  <template slot="modal-footer">
    <b-btn v-if="selected!=='cancel'" variant="primary" @click="clickModalBtn('OK')">
      OK
    </b-btn>
    <b-btn v-if="selected!=='ok'" variant="danger" @click="clickModalBtn('CANCEL')">
      Cancel
    </b-btn>
  </template>
</b-modal>
```
**JS:**
```js
data: {
   modalShow: false,
   message: null,
   selected: 'both',
   options: [
     {value:'both', text:'Both'},
     {value:'ok', text:'OK Only'},
     {value:'cancel', text:'Cancel Only'}
   ]
},
watch: {
	modalShow(newVal, oldVal) {
      if (newVal) {
        this.message = null;
      }
    }
},
methods: {
  clickModalBtn(btn) {
    this.modalShow = false;
    this.message = 'You Clicked: ' + btn;
  }
}
```

Just go over to https://bootstrap-vue.github.io/play/ and paste the above in to the respective section and try it out.

**Comment by tristanbes** [comment]
Thanks for the examples, i'll play along with the footer slot then.

**Comment by tristanbes** [comment]
Also, when overriden, it seems that I don't recieve any event anymore:
```

<template slot="modal-footer">
        <b-btn v-if="selected !== 'ok'" variant="danger" @click="cancel">
          {{ 'cancel'|trans }}
        </b-btn>
        <b-btn v-if="selected !== 'cancel'" variant="primary" @click="submit">
          {{ 'ok'|trans }}
        </b-btn>
</template>
...

methods: { 
  save(e) {
    return e.cancel();
  } 
}
```

`e.cancel is not a function`

**Comment by tmorehouse** [comment]
When overriding the footer, you are removing the "built in" OK & Cancel buttons, so you are also removing the "built-in" event handlers, as all the logic is now moved into your own app or component.  So you'll have to write your own handler that checks for a condition and prevents the `showModal' variable from being set to `false`:

```js
methods: {
  cancel() {
    // Close hte modal
    this.showModal = false;
  },
  save() {
     if (someTest == true) {
       // Close the modal
       this.showModal = false;
     } else {
        alert("You didn't do something");
     }
   }
}
```

**Comment by tristanbes** [comment]
Thank you

**Comment by tmorehouse** [comment]
You can also work around this by firing the components `hde()` method and pass the boolean primitives `true` or `false` to `hide()` (note they must be booleans, not truthy/falsey values).  This will trigger the `ok` and `cancel` events on the component:

```html
<b-modal ref="my_modal" @ok="save" @cancel="cancel">
  <!-- modal content here ->
  <template slot="modal-footer">
    <b-btn v-if="selected !== 'ok'" variant="danger"
       @click="$refs.my_modal.hide(false)"
     >{{ 'cancel'|trans }}</b-btn>
    <b-btn v-if="selected !== 'cancel'" variant="primary"
       @click="$refs.my_modal.hide(true)"
    >{{ 'ok'|trans }}</b-btn>
  </template>
</b-modal>
...

```js
methods: { 
  save(e) {
    return e.cancel();
  } 
  cancel(e) {
    return e.cancel();
  } 
}
```
