### ISSUE TITLE
Problem with slot in a b-table

### ISSUE THREAD

**Issue by JoanPedro** [bootstrap-vue/bootstrap-vue#4626]
### Describe the bug

I am currently developing an application with some older Bootstrapvue functionality, however my Bootstrapvue is up to date and I would not like to roll back version. Thus, I'm having trouble placing 2 buttons inside a column created by me "actions". There are 2 buttons to delete and update data.
It is important to note that the table is functional until the backend data push (Database).

### Expected behavior

It is expected that from the generated column it would be possible to dynamically include two buttons on each row.

### Versions

**Libraries:**

- BootstrapVue: 2.2.0
- Bootstrap: 4.4.0
- Vue: 2.5.17

**Environment:**

- Device: I5
- OS: Windows10
- Browser: Chrome
- Version: 79

### Demo link

        <b-table hover striped :items="users" :fields="fields">
            <template slot="actions" slot-scope="data">
                <b-button variant="warning" @click="loadUser(data.item)" class="mr-2">
                    <i class="fa fa-pencil"></i>
                </b-button>
                <b-button variant="danger" @click="loadUser(data.item, 'remove')">
                    <i class="fa fa-trash"></i>
                </b-button>
            </template>
        </b-table> 

### Additional context

So far everything works as expected, however, I can't use button insertion within the specific column.

      fields: [
                { key: 'id', label: 'Código', sortable: true},
                { key: 'name', label: 'Nome', sortable: true},
                { key: 'email', label: 'E-mail', sortable: true},
                { key: 'adminMaster', label: 'Administrador', sortable: true,
                    formatter: value => value ? 'Sim' : 'Não'},
                {key: 'adminEnterprise', label: 'Chefe de Empreendimento', sortable: true,
                    formatter: value => value ? 'Sim' : 'Não'},
                { key: 'manager', label: 'Gerente', sortable: true,
                    formatter: value => value ? 'Sim' : 'Não'},
                { key: 'customer', label: 'Cliente', sortable: true,
                    formatter: value => value ? 'Sim' : 'Não'},
                { key: 'actions', label: 'Ações'}
            ],

**Comment by tmorehouse** [comment]
Closing, as no detail provided in issue template

**Comment by JoanPedro** [comment]
> Closing, as no detail provided in issue template

As reported, the problem was more detailed.

**Comment by tmorehouse** [comment]
Reopening now that details have been provided

**Comment by tmorehouse** [comment]
You are using an older Vue (`2.5.17`) that is not compatable with BootstrapVue.  Upgrade to Vue `2.6.11`

**Comment by tmorehouse** [comment]
Also note that the table cell field slots have changed as of v2.0.0:

```html
    <b-table hover striped :items="users" :fields="fields">
        <!-- note new slot name convention -->
        <template v-slot:cell(actions)="data">
            <b-button variant="warning" @click="loadUser(data.item)" class="mr-2">
                <i class="fa fa-pencil"></i>
            </b-button>
            <b-button variant="danger" @click="loadUser(data.item, 'remove')">
                <i class="fa fa-trash"></i>
            </b-button>
        </template>
    </b-table>
```

**Comment by JoanPedro** [comment]
> Also note that the table cell field slots have changed as of v2.0.0:
> 
> ```
>     <b-table hover striped :items="users" :fields="fields">
>         
>         <template v-slot:cell(actions)="data">
>             <b-button variant="warning" @click="loadUser(data.item)" class="mr-2">
>                 <i class="fa fa-pencil"></i>
>             </b-button>
>             <b-button variant="danger" @click="loadUser(data.item, 'remove')">
>                 <i class="fa fa-trash"></i>
>             </b-button>
>         </template>
>     </b-table>
> ```
> 
> See:
> 
> * https://bootstrap-vue.js.org/docs/misc/changelog#v200
> * https://bootstrap-vue.js.org/docs/misc/changelog#migration-guide-v200
> * https://bootstrap-vue.js.org/docs/components/table#custom-data-rendering

I tried with the new suggested method and it didn't work. So I need to upgrade Vue and at the same time use the new slot mode?

**Comment by tmorehouse** [comment]
The new Vue `v-slot` directive was introduced in Vue 2.6.

**Comment by tmorehouse** [comment]
@JoanPedro did that fix your issues?

**Comment by JoanPedro** [comment]
> @JoanPedro did that fix your issues?
I haven't tested the previous suggestion yet. In this step, I will check tomorrow. 
But, thank you in advance.

**Comment by JoanPedro** [comment]
> @JoanPedro did that fix your issues?

Test performed and functional. The answer to the problem was as follows: 

> The new Vue v-slot directive was introduced in Vue 2.6.

> You can still use <template slot="cell(actions)" scope="data"> slot syntax, but just note the name of the slot (in BootstrapVue 2.0.0+) has changed from actions to cell(actions).


I didn't need to update the version I'm using vue. Changing from slot = "actions" to slot = "cell (actions)" was enough.

**Comment by tmorehouse** [comment]
Glad it is working.

But I do recommend that you update to Vue 2.6.x (from 2.5.), as there are some features of BV that will not work correctly with 2.6.
