### ISSUE TITLE
Rows in table not selectable or intermittently selectable

### ISSUE THREAD

**Issue by mwishum** [bootstrap-vue/bootstrap-vue#4629]
### Describe the bug

In my project a Table set to be selectable is not selectable - rows don't emit events when clicked but can be selected by methods (selectAllRows, etc.). Sometimes rows can be selectable after toggling the select state of the table (but not usually).

### Steps to reproduce the bug

1. Go to https://codesandbox.io/s/bootstrap-vue-table-select-issue-fkqns
2. Click on either "purchase" or "select rows"
3. Attempt to select a row - it shouldn't work (you don't see SELECTED)
4. Hit exit mode. Click on either button again
5. Attempt to select a row - it may work (SELECTED may appear)

GIF of Issue in full project: https://imgur.com/Y2hqQ7M

### Expected behavior

I can select rows on the table on the first try.

### Versions

**Libraries:**

- BootstrapVue: 2.2.1
- Bootstrap: 4.4.1
- Vue: 2.6.10

**Environment:**

- Device: Windows 10 latest
- Chrome 80.0.3987.42 and Firefox 72.0.1, others on phones etc

### Demo link

https://codesandbox.io/s/bootstrap-vue-table-select-issue-fkqns

### Additional context

My demo is a stripped down part from a project which uses CoreUI which may be related. In the project selecting never works (where in the demo it starts to after exiting a select mode). In the code sandbox it worked as expected originally but when I started adding more to figure out the issue it broke. When I added these libraries it stopped working (not even imported in main.js just added to the dependencies):  
@coreui/coreui-pro: 3.0.0-beta.3,
@coreui/vue: ^3.0.0-beta.7,
Removing them did not fix the issue so maybe something else is at fault. 

I attempted to work around this buy having two tables (one you can select one is view-only) that use v-if and else that also result in un-selectable rows. I finally added keys to both and that seems to work but is ugly...

**Comment by tmorehouse** [comment]
I tried in chrome (on windows) and your codesandbox example appears to be working for me.

Note when removing libraries from your package.json, always remember to delete `node_modules` and `yarn.lock`, and run `yarn install` again

**Comment by mwishum** [comment]
@tmorehouse I was only referring to adding libraries to CodeSandbox which I couldn't figure out how to remove `node_modules` or if that is even a thing.

Additionally, I tried that sandbox in other browsers (where it has never been opened) and it didn't work (Edge and Chromium Edge Beta)

I have now added those libraries back into that example.

**Comment by jackmu95** [comment]
@tmorehouse Tried the example and noticed the issue described above.
Watch for the `SELECTED` text at the right end of the row. It only shows up in the second try.

I'am currently not sure if its a code related problem or a bug in `<b-table>`.

**Comment by mwishum** [comment]
My current workaround is to have two tables one for display only and one for selection only. It only works if I give them keys otherwise it is broken like it is a single table.

So I would say it is either the `<b-table>` or some weird interaction is the cause.

(some display props omitted)

```
<b-table :busy="busy"
         :fields="fields"
         :items="po.rows"
         @row-selected="selectedRows"
         key="SELECT"
         ref="row_table"
         selectable
         show-empty
         v-if="rowsAreSelectable"
>
     <!--SNIP-->
</b-table>

<b-table :busy="busy"
         :fields="fields"
         :items="po.rows"
         key="VIEW"
         show-empty
         v-else
>
     <!--SNIP-->
</b-table>
```

**Comment by tmorehouse** [comment]
What if you provide a `primary-key` field name via the `primary-field` prop? the primary key will ensure unique Vue `:key` is created for each row (end ensure elements are not re-used when they shouldn't be during the Vue render patch cycle)

**Comment by tmorehouse** [comment]
Actually, I see an issue now:

`to_purchase` is not pre-defined in the rows objects, and Vue is not initially detecting the change.

Vue can't detect when new properties are added to objects, unless you use `this.$set(...)` (https://vuejs.org/v2/api/#vm-set)

**Comment by mwishum** [comment]
@tmorehouse I agree I should have provided `primary-key` (and now have), but that did not fix the issue.

`to_purchase` is only set when the row selected which is the issue because it doesn't happen... But I have changed it to use `this.$set()`.

**Comment by tmorehouse** [comment]
What I think might be happening is a race condition when switching to selectable mode from non selectetable mode (the first time), win which the internal row-clicked handler is set up (the handlers are only set up when listeners are detected (which is checked each render cycle)

**Comment by Dual-Ice** [comment]
I have a same issue, if selectable flag by default set as false, I need switch it two times to set table selectable. Does solution exist ?

**Comment by mwishum** [comment]
@Dual-Ice As I said earlier I ended up making two tables that show/hide when needed. It does send two `row-selected` events per click though.

**Comment by Dual-Ice** [comment]
@mwishum , really ? There are 2 variants: switch mode 4 times false->true->false->true or use 2 same tables - one with selectable and other without it ? :(

**Comment by Dual-Ice** [comment]
There is "hack"  - )) in data set selectable flag in true, after in mounted, for example, set it in false. When we try to switch on selectable - it will be work as expected. But i think it is doubtful solution.

**Comment by tmorehouse** [comment]
We currently only instantiate the row clicked handlers when the table is selectable or has a row-clicked listener... we might have to switch back to always having the row-clicked handler present.
