### ISSUE TITLE
B-dropdown clear URL adress, and change site position

### ISSUE THREAD

**Issue by jakubstankowski** [bootstrap-vue/bootstrap-vue#4634]
### Steps to reproduce the bug

1. Go to b-dropdown
2. Click on b-dropdown item

### Expected behavior

When i click to b-dropdown item, page automaticly scroll up to point (0,0), and change routing url

```html
      <div style="margin-top: 1000px"></div>
        <b-dropdown id="dropdown-1" text="Dropdown Button" class="m-md-2">
            <b-dropdown-item>First Action</b-dropdown-item>
            <b-dropdown-item>Second Action</b-dropdown-item>
            <b-dropdown-item>Third Action</b-dropdown-item>
            <b-dropdown-divider></b-dropdown-divider>
            <b-dropdown-item active>Active action</b-dropdown-item>
            <b-dropdown-item disabled>Disabled action</b-dropdown-item>
        </b-dropdown>
```

**Comment by tmorehouse** [comment]
I just created the above markup in the docs playground, an do not see the issue you are having.

What version of BootstrapVue and Vue are you using?

**Comment by jakubstankowski** [comment]
Yes, sorry you are right, it's not a problem with vue-bootstrap, but with UI component which i use :)
