### ISSUE TITLE
Bootstrap-Vue icons breaking hot reload despite not imported

### ISSUE THREAD

**Issue by ryanelian** [bootstrap-vue/bootstrap-vue#4636]
### Describe the bug

Excuse me, I'm importing only the Alert plugin but this appears in my browser console during hot reload.

```
VM22232 log.js:26 [HMR] Cannot apply update. Need to do a full reload!
module.exports @ VM22232 log.js:26
eval @ VM22231 dev-server.js:39
Promise.catch (async)
check @ VM22231 dev-server.js:36
eval @ VM22231 dev-server.js:55
emit @ VM22234 events.js:152
reloadApp @ VM22222 reloadApp.js:23
ok @ VM22203 localhost:28080:120
eval @ VM22206 socket.js:48
sock.onmessage @ VM22207 SockJSClient.js:63
EventTarget.dispatchEvent @ VM22208 sockjs.js:170
eval @ VM22208 sockjs.js:888
SockJS._transportMessage @ VM22208 sockjs.js:886
EventEmitter.emit @ VM22208 sockjs.js:86
WebSocketTransport.ws.onmessage @ VM22208 sockjs.js:2962



VM22232 log.js:26 [HMR] Error: Aborted because ./node_modules/bootstrap-vue/esm/icons/index.js is not accepted
Update propagation: ./node_modules/bootstrap-vue/esm/icons/index.js -> ./node_modules/bootstrap-vue/esm/index.js -> ./client/js/vue-project.ts -> ./client/js/index.ts
    at https://localhost:28080/ipack.js:820:32
    at https://localhost:28080/ipack.js:540:21
    at Array.map (<anonymous>)
    at internalApply (https://localhost:28080/ipack.js:539:54)
    at https://localhost:28080/ipack.js:516:24
    at waitForBlockingPromises (https://localhost:28080/ipack.js:471:55)
    at https://localhost:28080/ipack.js:514:22
```

### Steps to reproduce the bug

1. Add this to the project: 

```ts
import Vue from 'vue';
import { AlertPlugin } from 'bootstrap-vue';

// https://bootstrap-vue.js.org/docs/#component-groups-and-directives-as-vue-plugins
Vue.use(AlertPlugin);
```

2. Run hot reload.

3. Above error message gets displayed in browser console...

4. Hot reload will suddenly work again if you change anything in the file which renders the vue Root component, but only while webpack-dev-server is running. (The next time WDS is run again, the warning message will appear again)

### Expected behavior

Hot reload works and without warnings or errors.

### Versions

**Libraries:**

- BootstrapVue: 2.2.1
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: ASUS GU502GV
- OS: Microsoft Windows [Version 10.0.18363.535]
- Browser: Chrome 
- Version: 80.0.3987.53

### Demo link

TODO after finished speaking at my seminar

> If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

> You can also export markup from the [Online Playground](https://bootstrap-vue.js.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Am using Webpack versions:

```
    "webpack": "5.0.0-beta.11",
    "webpack-dev-server": "3.10.1",
    "vue-loader": "15.8.3",
```

**Comment by tmorehouse** [comment]
If webpack is not in production mode, then tree shaking is not performed (and hence the full library is loaded into memory).

Do you see the issue if using webpack 4.x.x stable?

**Comment by ryanelian** [comment]
> If webpack is not in production mode, then tree shaking is not performed (and hence the full library is loaded into memory).

Btw the issue also happened if I `import BootstrapVue from 'bootstrap-vue';` also. So I don't think this is specific to tree shaking.

> Do you see the issue if using webpack 4.x.x stable?

Team reported yes but I haven't tested myself

**Comment by tmorehouse** [comment]
`import BootstrapVue from 'bootstrap-vue';` gets the same reference as `import { BootstrapVue } from 'bootstrap-vue';` (it is exported as both the default export and a named export)

**Comment by tmorehouse** [comment]
Actually, I think I see the issue.  and should be able to have a fix shortly in v2.2.3

**Comment by tmorehouse** [comment]
Hmmm I don't think it is what  I thought it might be.

**Comment by tmorehouse** [comment]
What if you try importing this way:

```js
import { AlertPlugin } from 'bootstrap-vue/dist/bootstrap-vue.esm.js'
```

the esm bundle doesn't tree shake as well as the ESM modular build (although it will tree shake to some extent), but curious to know if you see a similar error.

**Comment by ryanelian** [comment]
It worked.

**Comment by tmorehouse** [comment]
Interesting.
