### ISSUE TITLE
Documentation v2.2.2 Form Tag clarification on events @new-tags @tag-events

### ISSUE THREAD

**Issue by jmrlib** [bootstrap-vue/bootstrap-vue#4638]
### Describe the bug

In the section 'Detecting new, invalid, and duplicate tags', the paragraph mentions the event `new-tags`, but the example shows the event `@tag-state`

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/form-tags/
2. Click on [...]
3. Scroll down to Detecting new, invalid, and duplicate tags

### Expected behavior

Confusing; see above.

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.js.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
Thanks for pointing this out.

Just did a hotfix on the docs site.  It should be visible in the docs site shortly.
