### ISSUE TITLE
Invalid Dropdown Structure BS4

### ISSUE THREAD

**Issue by MalithHatananchchige** [bootstrap-vue/bootstrap-vue#4641]
### Describe the bug

Bootstrap Vue DOM structure has li and ul which is been removed long time ago by 

### Expected behavior
It should be
```
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
````

### Versions

**Libraries:**

- BootstrapVue: 2.2.2
- Bootstrap: 4.3
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Mojave 
- Browser: Chrome
- Version: 79.0.3945.117

**Comment by jackmu95** [comment]
We switched back to semantic `<ul>` and `<li>` markup with #3087.
Bootstrap v5 will also revert back to.
