### ISSUE TITLE
B-pagination not able to past the second page.

### ISSUE THREAD

**Issue by minty-pawel** [bootstrap-vue/bootstrap-vue#4642]
## B-pagination not able to past the second page.

I am trying to load a list of 39 attendees of an event in a b-table. The table is set to 10 rows per page.
But im unable to go past the second page. Even if click on the last page button if wont go past the second page. I made a method that forces the currentPage to 3 but 
when currentPage gets assigned the value it almost instantly jumps back to value 2.
The b-table and the b-pagination able to correctly  read the current page, rows per page and the items.

**The b-table:**

```
< b-table
        id="event_attendees"
        v-if="attendees.length"
        :sort-by="'event'"
        responsive
        hover
        striped
        :filter="filter"
        :items="attendees"
        :fields="fields"
        :per-page="rowsPerPage"
       :current-page="currentPage"
       @filtered="onFiltered"
 >
```

**The b-pagination**

```
< b-pagination
      align="center"
      size="md"
      :total-rows="totalRows"
      v-model="currentPage"
      :per-page="rowsPerPage" >
</b-pagination>
```

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.11
- Bootstrap: 4.4.1
- Vue: 2.5.7

**Environment:**

- Device: Windows 10 computer
- Browser: Chrome 79.0.3945.117

**Comment by jackmu95** [comment]
Please upgrade to the latest stable BootstrapVue release (requires Vue 2.6.x) and see if your issue still exists.
