### ISSUE TITLE
b-form-tags input type is always text

### ISSUE THREAD

**Issue by bezumkin** [bootstrap-vue/bootstrap-vue#4644]
### Describe the bug

Looks like input type of `b-form-tags` is hardcoded to `text`. I can't change it via `input-props`.

### Expected behavior

`input-props` should have ability to change `type`.

### Versions

**Libraries:**

- BootstrapVue: 2.2.2
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome
- Version: 79.0.3945.117

**Comment by tmorehouse** [comment]
As stated in the docs:

https://bootstrap-vue.js.org/docs/components/form-tags#form-tags

> Tags are arrays of short **strings**, used in various ways such as assigning categories.

**Comment by tmorehouse** [comment]
If you need, say a type `number`, then you can use the scoped default slot to provide your own custom interface (https://bootstrap-vue.js.org/docs/components/form-tags#custom-rendering-with-default-scoped-slot).

**Comment by bezumkin** [comment]
> What types of inputs are you looking for?

`email`, `time`, `url` - they are strings but I can't use them now

> then you can use the scoped default slot to provide your own custom interface

Of course I can do this, but I don't want to repeat the whole component only for changing input type.

**Comment by tmorehouse** [comment]
`email`, `url`, `tel`, and possibly `number`, we should be able to do. `date` and `time` may be difficult since their behaviour changes due to varied support on different browsers (keydown.enter isn't always available)
