### ISSUE TITLE
Unexpect behaviopurs when sorting:false in a table column

### ISSUE THREAD

**Issue by realtebo** [bootstrap-vue/bootstrap-vue#4646]
### Describe the bug

If a column is not sortable I expect that user _cannot click_ on its header cell. Actually, if the user clicks  on the header of a non-sortable column, the data is fetched again, using as sortBy an empty string. 

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/table
2. Click on "Age"
3. Data is sorted ascending by Age
4. Click on "Is Active"
5. The table is altered, data is now sorted on 'what' ?" Of course, it is not ordere by "Is active' and so causing confusion on the user

### Expected behavior

At 4th point, table header must NOT trigger any sort/refetch if sorting is disable

### Versions

**Libraries:**

- BootstrapVue: 2.2.2
- Bootstrap: 4.4.1
- Vue: 2.5.17

**Environment:**

- Device: any
- OS: any
- Browser: any

### Demo link

The behaviour is actually present even of official bootstrap-vue docs demo

https://bootstrap-vue.js.org/docs/components/table

**Comment by tmorehouse** [comment]
When clicking a non sortable column header, the current sort state will be cleared, as mentioned in the docs https://bootstrap-vue.js.org/docs/components/table#sorting

> Clicking on a sortable column header will sort the column in ascending direction (smallest first), while clicking on it again will switch the direction of sorting to descending (largest first). **_Clicking on a non-sortable column will clear the sorting_** (the prop `no-sort-reset` can be used to disable this feature).

So to stop this behaviour, set the `no-sort-reset` prop on `<b-table>`:

```html
<b-table no-sort-reset ... >
</b-table>
```

**Comment by realtebo** [comment]
I can confirm that this options realized my goal.
