### ISSUE TITLE
BTable - Col template - functional component

### ISSUE THREAD

**Issue by randyhoulahan** [bootstrap-vue/bootstrap-vue#4648]
### Describe the bug

When using BTable.  I import Col components.  Most of which are functional components.  If the functional component imports and registers a component for use. I get an error that resembles circular component reference. 

### Steps to reproduce the bug

```html
<BTable class="mb-0 table-outline list" responsive="md" hover :items="tableItems" :fields="tableFields"  head-variant="light">
    <template v-slot:cell(user)="row">
      <UserCol v-bind="row.item.user" />
    </template>

    <template v-slot:cell(country)="row">
      <CountryCol v-bind="row.item.country" />
    </template>
</BTable>
```

```html
<template functional>
  <CountryFlag :country="props.code" />
</template>

<script>
import CountryFlag from 'vue-country-flag'

const inject = { components: { default: { CountryFlag } } }

export default {
  props: { code: { type: String, required: true } },
  inject
}
</script>
```

> [Vue warn]: Unknown custom element: `<CountryFlag>` - did you register the component correctly? For recursive components, make sure to provide the "name" option. found in ....

### Expected behavior

No errors

### Versions

**Libraries:**

- BootstrapVue: 2.2.2
- Bootstrap:  4.4.1
- Vue:  2.6.11
- nuxt: 2.11.0

**Environment:**

- Device: mac
- OS: latest
- Browser:chrome
- Version: latests

### Demo link

soon if needed

### Additional context

Working if non functional ... I suspect if I reg the components global it will be fine too.

**Comment by tmorehouse** [comment]
Your `UserCol` component needs to be registered in the component that is rendering `BTable`
