### ISSUE TITLE
Issues with triggering ok event in modal after updating to vue test utils 30

### ISSUE THREAD

**Issue by Loremaster** [bootstrap-vue/bootstrap-vue#4656]
### Describe the bug

I am having issues with testing ok event in bootstrap modal after upgrade to vue test utils (version 30). I have code with modal and button. It tests that action is called on ok event. It worked in version 29 but stopped in 30. 

### Steps to reproduce the bug

1. Clone https://github.com/Loremaster/bootstrap-vue-modal-submit-vtu-30
2. Run `$ yarn`
3. Run `$ yarn test:unit`
4. See error:

```js
    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: Anything, "Reminder message"

    Number of calls: 0

      30 |     await flushPromises();
      31 | 
    > 32 |     expect(actions.createReminder).toHaveBeenCalledWith(expect.anything(), "Reminder message");
         |                                    ^
      33 |   });
      34 | });
```

### Expected behavior

I can see that clicking on button doesn't trigger submit for some reason. 

### Versions

**Libraries:**

- BootstrapVue: 2.2.2
- Bootstrap: 4.4.1
- Vue: 2.6.11

### Demo link

Repo: https://github.com/Loremaster/bootstrap-vue-modal-submit-vtu-30

**Comment by tmorehouse** [comment]
Version beta.30 of Vue-test-utils has removed synchronous testing, which makes it difficult to test things triggered via transition events.

We have pinned our testing to vue-test-utils beta.29 for this reason.

**Comment by Loremaster** [comment]
@tmorehouse thanks but is there workaround now to fix this specific issue for me? I want to migrate to vue-test-utils-30

**Comment by Loremaster** [comment]
I see. Personally I found fix for me by using `await Vue.nextTick()` together with [transitionStub](https://vue-test-utils.vuejs.org/guides/common-tips.html#using-a-transitionstub-helper). I will close the issue as I resolved it for me.

**Comment by tmorehouse** [comment]
Interesting, they must have updated the `beta.30` docs sine we last checked.

**Comment by Loremaster** [comment]
@tmorehouse hope it helps you guys :)
