### ISSUE TITLE
Selectable table with form elements mouse release problem [Chrome]

### ISSUE THREAD

**Issue by TheAndroidGuy** [bootstrap-vue/bootstrap-vue#4661]
When i use selectable table with form elements when the row is selected, if i release the mouse outside the form element it deselects the row. 

`Vue version: 2.6.10`
`Bootstrap-Vue version: 2.2.2`

Here is a GIF illustrating the issue.

![primerok](https://user-images.githubusercontent.com/17319245/72849006-1f902700-3ca6-11ea-9328-caa96e1cd71e.gif)

**Comment by tmorehouse** [comment]
Interesting, we may need to add test selection checking on the click event handler.

What if you use plain `@row-clicked` event to enable editing of the row? Does it show the same issues?

**Comment by TheAndroidGuy** [comment]
@tmorehouse I don't know if I am doing it correctly but it also doesn't seem to work properly

**Comment by DM2489** [comment]
Just to add, I'm seeing this too. Did anyone figure out a solution?

**Comment by TheAndroidGuy** [comment]
@DM2489 I ended up using primitive workaround:

inside data:
```js
my_row_selected: null
```

inside methods:
```js
myRowSelect: function(index){
  this.my_row_selected = index
}
```

inside component:
```js
<div v-if="my_row_selected == row.index">
  <!-- some form element when row is selected -->
</div>
<div v-else @click="myRowSelect(row.index)">
  <!-- data when row is not selected -->
</div>
```

Another even worse workaround would be to use modal when the row is clicked and display the form elements inside the modal.

**Comment by DM2489** [comment]
@TheAndroidGuy Thanks, seems like a sensible solution. I'll adopt the same external tracker approach.
