### ISSUE TITLE
The items property of a table is not reactive. 

### ISSUE THREAD

**Issue by pstaabp** [bootstrap-vue/bootstrap-vue#4668]
### Describe the bug

I am using bootstrap-vue's table element that will hopefully grow/shrink as needed. 

I would like to eventually use a Map to store data (ultimately from a vuex store, but not relevant to this problem).  I have also tried with an array as in this code sandbox: [https://codesandbox.io/s/funny-matsumoto-951r5](https://codesandbox.io/s/funny-matsumoto-951r5) 

I know that if I used the push/pop methods of an array (as described in https://vuejs.org/v2/guide/list.html#Array-Change-Detection)  that everything reacts as it should, however if you notice in the example cited the computed property is updating correctly, but the table is not reacting.  _I did this to mimic a Set, which I want to use later._ 

Note: the method to force an updated Set change is a hack from: [https://github.com/vuejs/vue/issues/2410](https://github.com/vuejs/vue/issues/2410) and it appears that this will become built-in to Vue-3.0.

### Steps to reproduce the bug

1. Visit [https://codesandbox.io/s/funny-matsumoto-951r5](https://codesandbox.io/s/funny-matsumoto-951r5) 
2. Click on Add Item a few times.

The items array is updating as the output below the table shows, but the table is not reacting. 

### Expected behavior

As the Add Item button is clicked, the new items should tacked onto the table. 

### Versions

**Libraries:**

- BootstrapVue: 2.2.2
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Catalna
- Browser: Chrome
- Version: 79

### Demo link

[https://codesandbox.io/s/funny-matsumoto-951r5](https://codesandbox.io/s/funny-matsumoto-951r5)

**Comment by tmorehouse** [comment]
Perhaps you should change your computed prop `all_items` to the following:

```js
  computed: {
    all_items() {
      return this.item_tracker ?  this.items.slice() : []
    }
  }
```

To ensure a new array reference is returned to trigger the reactive updates

**Comment by tmorehouse** [comment]
Also your method:

```js
    addItem() {
      const name = this.getName();
      this.item_tracker += 1;
      this.items[this.items.length] = {
        Name: name,
        Age: Math.round(75 * Math.random())
      };
      //this.items.push()
    }
```

Will not trigger reactive updates in Vue.  Use the `push(...)` method, or concat the new entry and return a new array reference.

**Comment by pstaabp** [comment]
@tmorehouse  First, I know I can get this to be reactive using `this.items.push` or `this.items.slice`, but I'm trying to find a workaround to get this to work with a `Map`.

Above, you say that `this.items` hasn't changed in Vue's eyes,...  then why (from the example at codesandbox), does the line {{all_items}} below the table change?  To me, that's the puzzling thing and why I filed this as a possible bug.

**Comment by pstaabp** [comment]
Also, I just removed the line `{{all_items}}` and it's clear that each time the _Add Item_ button is clicked that the `all_items` getter is run (from the console.log line) and the return value changes each time.

**Comment by tmorehouse** [comment]
What you are seeing is the output of JSON.stringify of all_items (`{{ all_items }}`), which strigifs the object each time your component's state changes.

But note that the Array _reference_ that all_items returns (which is this.items) has not chagned, not has any reactive watchers added to the new item(s) you have added to the array (you an see this when you inspect the state of your component item that there are no getters/setters on the last item in the array).  This array reference is in turn passed to b-table (a separate component instance).  The array has reactive watchers on it (from your parent component), so b-table's instance doesn't instantiate new reactive watchers on the elements within the array.  Hence BTable's Vue instance is _not detecting any changes_ to the `this.items` array reference passed via the `items` prop from the parent.

Vue optimizes how things are updated/rendered.  If a child compoent (BTable in this case) props do not change values, then Vue does not re-render the component, even though hte parent component may re-render.

This is why, if you want your method of passing `this.items` to BTable via `all_items`, you will need to reactivity set the value in `this.items`, or in your all_items compued prop, use `this.items.slice()` to return a _new_ array reference, which will then trigger reactive updates on the child compoent (BTable).

This is not a BTable issue, but just the way Vue's reactivity works.

**Comment by pstaabp** [comment]
Just to clarify: Since `this.item_tracker` has updated, there is a call to `this.all_items`, which is why there is a dump to the console which reflects the update, however, since the reference didn't change, which is the output from `return this.item_tracker && this.items` there is no update to the table.  

I thought that hack in https://github.com/vuejs/vue/issues/2410#issuecomment-318487855 wasn't working, but I notice the `Array.from(....)` creates a new array and thus does update. 

I think this should solve my problem and clarify what's going on.

**Comment by tmorehouse** [comment]
array.slice() also returns a new array reference.  But Array.from(array) will also work (but note you may need a polyfill for it for some browsers)
