### ISSUE TITLE
A "b-modal" is destroyed as many times as count of "v-b-tooltip" used inside.

### ISSUE THREAD

**Issue by bArraxas** [bootstrap-vue/bootstrap-vue#4671]
If you use a "v-b-tooltip" inside a "b-modal" for example, the modal is destroyed as many times as count of "v-b-tooltip" used.
It's not normal.

### Steps to reproduce the bug

1. Create component containing a `<b-modal>`
2. Add the "`beforeDestoy() { console.log('beforeDestoy:myModal') }`" in this component
2. Use some "v-b-tooltip" inside de `<b-modal>` body.
3. Destroy the component `<b-modal>`
4. See in the console all unexpected 'beforeDestoy:myModal' appear.

### Expected behavior

I xpected see only one time 'beforeDestoy:myModal' in the console

### Versions

- vue : 2.6.10
- bootstrap: 4.4.1
- bootstrap-vue: 2.1.0

**Environment:**

- Device: PC
- OS: window 7, 10
- Browser: Chrome
- Version: latest

**Comment by tmorehouse** [comment]
Tooltips (and popovers, and toasts, etc) tap into their parent's `beforeDestroy` hook to know when they should destroy themselves (to ensure the portalled content is removed from DOM).  What you are probably seeing is multiple components triggering the `destroy` hook call (beforeDestroy may get called before Vue has a chance to set the `this._beforeDestroy`, this_isBedingDestroyed` , etc, flags on the component.

How are you destroying the b-modal?  via `v-if`. or by calling `$destroy()`?

**Comment by bArraxas** [comment]
My b-modal is include into a vue and it's destroyed automaticly by changing of route (vue router).
The component where I had put the b-modal is defined like this <template><b-modal ...>...</b-modal></template>. I don't hook b-modal beforeDestroy, I use the beforeDestroy of my component.

**Comment by mooshallski** [comment]
This is a problem for every component that has tooltips apllied via directive. Whenever this component is destroyed (by v-if, router etc.), the destroy hook will be triggered as many times as the number of tooltips in this component.

**Comment by effnnn** [comment]
Can we re-open this issue?

We have created a plunker sample application that shows it:

[https://plnkr.co/edit/aKxajAIbUdZbhtqC](url)

To test, open the console and switch tabs. Note the amount of times a console log of 'beforeDestroy' and 'destroyed' is printed, essentially being related to the amount of rows in the table, all of which could include 'v-b-tooltip'. Now remove 'v-b-tooltip.right.hover' and re-test and you will see the issue is no longer there.
