### ISSUE TITLE
I think somebody want a sidebar in Mobile Device become a canvas，i write a demo with bootstrap-vue

### ISSUE THREAD

**Issue by nejinn** [bootstrap-vue/bootstrap-vue#4674]
offcanvas
sidebar collapse
sidebar nav accordion support
sidebar hover collapse
Mobile Device support
In Mobile Device, sidebar Sidebar will become canvas
left content and right content has own scroll bar

https://github.com/nejinn/bootstrap4-flex-sidebar

just like this!,  if you want,you can clone it
![aside](https://user-images.githubusercontent.com/31615794/73088208-c0811b00-3f0e-11ea-8e7e-6287f48cbcc3.gif)

**Comment by tmorehouse** [comment]
related issue: #4618
