### ISSUE TITLE
Help with event on b-table

### ISSUE THREAD

**Issue by Soraia55** [bootstrap-vue/bootstrap-vue#468]
Hi! 

I'm trying to catch when a user clicks on a row from the table, I'm using: 
`<b-table hover :items="items" :fields="fields" :current-page="currentPage" :per-page="perPage" :filter="filter" v-on:row-clicked="test(item.item,index)">
</b-table>`

and I'm declaring "test" like this: 
`methods: {
	  		test(item, index){
	  			console.log("WORKS!");
	  		}`

but that doesn't seem to work, what am I doing wrong?

**Comment by tmorehouse** [comment]
when specifying the event handler, don't include a calling sequence, just specify a reference to the row-clicked handler:

```html
<b-table hover :items="items" :fields="fields" :current-page="currentPage"
              :per-page="perPage" :filter="filter" @:row-clicked="test">
</b-table>
```

**Comment by Soraia55** [comment]
@tmorehouse  thanks for your answer! 
I've already corrected it as you said but I'm still getting nothing :/

**Comment by tmorehouse** [comment]
Check out fiddle https://jsfiddle.net/n035zm2p/

I have created a method `rowClicked` in the app and applied it to the b-table as  `@row-clicked="rowClicked"`.

When a row is clicked, an alert is shown showing the index number and the item data

**Comment by Soraia55** [comment]
I don't know what's going on, if I paste the code from the fiddle to my computer the row-clicked (and also head-clicked) event doesn't work

**Comment by tmorehouse** [comment]
`head-clicked` in't available in the current release (only the master branch at the moment)

**Comment by Soraia55** [comment]
Right, sorry. But then row-clicked should work... It's weird that on the fiddle it works and on my computer it doesn't, any ideas why?

**Comment by tmorehouse** [comment]
Check to make sure you are using the same version of bootstrap-vue and vue.js that the fiddle is using.

**Comment by Soraia55** [comment]
Thank you so much, it's working! I was using an older version of bootstrap-vue

**Comment by saeedegh** [comment]
Is it possible to handle a click event on a special Field on a  b-table?how?

**Comment by tmorehouse** [comment]
@saeedegh you would need to use a custom data render slot for the field, and wrap your content in a div that has a click listener... but not screen reader or keyboard only users wouldn't be able to click that div.

Alternatively, using the custom formatting slot for that field, wrap your content in an un-styled `<button>` which has a click handler on it.  This would prove to be the most accessible method.

**Comment by saeedegh** [comment]
It works.
thank you.
