### ISSUE TITLE
b-button cursor is not unset when disabled

### ISSUE THREAD

**Issue by mcshaz** [bootstrap-vue/bootstrap-vue#4687]
### Describe the bug
if viewing the docs for a disabled b-button:
[https://bootstrap-vue.js.org/docs/components/button/#disabled-state](https://bootstrap-vue.js.org/docs/components/button/#disabled-state)
hover over the button (tested FF & Chrome) the cursor changes to a pointer as if hovering over an active button.

when going to the bootstrap docs:
[https://getbootstrap.com/docs/4.0/components/buttons/#disabled-state](https://getbootstrap.com/docs/4.0/components/buttons/#disabled-state)
hovering over the button does not change the cursor (expected behavior for a disabled button).

**Comment by Hiws** [comment]
That's because you're looking at old `bootstrap 4.0` docs. If you go to the current one https://getbootstrap.com/docs/4.4/components/buttons/#disabled-state they act the same
