### ISSUE TITLE
B-Pagination, a tag with href="#" change url adress

### ISSUE THREAD

**Issue by jakubstankowski** [bootstrap-vue/bootstrap-vue#4689]
### Describe the bug

B-Pagination element have default a tag with `href="#"`, and automaticly clear url adress in my aplication
It possible to change the **a** tag in b-pagination, or implement withou **a** tag ? 

![Zrzut ekranu (218)](https://user-images.githubusercontent.com/36790120/73250980-4b387300-41b8-11ea-9e5c-30649b678830.png)

### Expected behavior

Click in b-pagination element, should not change url adress

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

**Comment by tmorehouse** [comment]
Clicks on the page numbers in `b-pagination` are captured by javascript to be handled. as part of that, the click event is `preventDefault()`.  It sounds like Vue/BootstrapVue javascript is not loaded on your page for some reason.

**Comment by jakubstankowski** [comment]
it's **swagger UI** reason, please be carefull to use in your aplication, in our destroy a lot of thinks

but thanks for response! :)
