### ISSUE TITLE
Issue with scoped scss in a vue tempate

### ISSUE THREAD

**Issue by cksachdev** [bootstrap-vue/bootstrap-vue#4694]
### Issue description
Scoped scss is not applying when its defined in vue template. Please refer to the code snippet below:
```
<template>
  <div>

    <h1>B-MODAL</h1>

      <div>
        <b-button id="show-btn" @click="showModal">Open Modal</b-button>

        <b-modal class="mymodal" title="BootstrapVue"
                    ref="my-modal"
                    @shown="showModal()">

            <b-card no-body>
                <b-tabs content-class="mt-3" justified small card   >
                    <b-tab title="Tab1" active>
                        <div class="item select list-items math-lib">
                            <div class="middle aligned content">
                                <div class="math-lib-header">Title 1</div>
                            </div>
                        </div>
                    </b-tab>
                    <b-tab title="Tab2" active>
                        <div class="item select list-items math-lib">
                            <div class="middle aligned content">
                                <div class="math-lib-header">Title 2</div>
                            </div>
                        </div>
                    </b-tab>
                    <b-tab title="Tab3" active>
                        <div class="item select list-items math-lib">
                            <div class="middle aligned content">
                                <div class="math-lib-header">Title 3</div>
                            </div>
                        </div>
                    </b-tab>
                </b-tabs>
            </b-card>
        </b-modal>
      </div>
  </div>
</template>

<script>

export default {
  name: 'HelloWorld',
  methods: {
    showModal () {
      this.$refs['my-modal'].show()
    },
    hideModal () {
      this.$refs['my-modal'].hide()
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
@import 'node_modules/bootstrap/scss/bootstrap';
@import 'node_modules/bootstrap-vue/src/index.scss';

.mymodal {
  width: 500px;
}
</style>
```

All the bootstrap and bootstrap-vue scss gets compiled successfully and unique attribute id gets added with css class name.
Issue is that whatever unique attribute generated for scoped scss, that attribute is not applying to b-modal or b-tabs components and child elements. To show the steps, I have created a sample application, which can be viewed on the link below:
https://cksachdev.github.io/bootstrap-vue-scoped-scss-issue/

Code for the same can be found in the repo link below:
https://github.com/cksachdev/bootstrap-vue-scoped-scss-issue

### Steps to reproduce the bug

1. Include bootstrap and bootstrap vue scss in vue template

### Expected behavior
Apply styles to bootstrap vue components as expected. Refer to screenshot below:
![image](https://user-images.githubusercontent.com/37770/73351943-0e52a600-42b6-11ea-8756-62fd94e5bd35.png)

### Actual behavior
Styles are not applied to bootstrap vue components. Refer to screenshot below:
![image](https://user-images.githubusercontent.com/37770/73351792-c92e7400-42b5-11ea-89ac-3b9a2b65bbba.png)

### Versions
```
 "bootstrap": "^4.4.1",
 "bootstrap-vue": "^2.3.0",
```
**Libraries:**

- BootstrapVue: 2.3.0
- Bootstrap: 4.4.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome
- Version: 79

### Demo link
https://cksachdev.github.io/bootstrap-vue-scoped-scss-issue/

### Additional context
Trying to create a vue widget application. This widget will be included in a large angular application. Currently if bootstrap vue is added in main application, the css loaded in vue app, impacts the overall style of main application. Thus exploring option to scope the styles in vue template to ensure it doesn't impact any of the styles in the main application.
Trying to avoid using Iframe and make use of scoped scss feature.

**Comment by Hiws** [comment]
I created a file in `assets/scss/` called `main.scss`.
In this file i had 
```scss
// main.scss
@import '~bootstrap';
@import '~bootstrap-vue';
```
and then imported that file in the `HelloWorld.vue` component from your example project like
```html
<!-- HelloWorld.vue -->
<style scoped lang="scss">
  /deep/ {
    @import '../assets/scss/main'
  }
</style>
```

**Result**
![chrome_7vG9jTYZvT](https://user-images.githubusercontent.com/7057431/73354093-22d27680-4295-11ea-805f-291c41ad2325.png)



You'll probably notice that the font is different on the modal. This is because the modal is rendered at the bottom of `body` by default in `BoostrapVue`, and since you're scoping all your css to that component it wont reach the modal.

The following CSS is usually added to `body` in boostrap, so you'll need to find a workaround to add that to your modal to make it look like normal bootstrap.

```css
body {
    margin: 0;
    font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    text-align: left;
    background-color: #fff;
}
```

An alternative would be to add the `static` to your modal. Which will render the modal where it's place in the document.

**Comment by cksachdev** [comment]
Thanks for the solution @Hiws It's working as expected. Could you help me understand why my solution wasn't working? And what do you mean by adding **static to the model**?

**Comment by tmorehouse** [comment]
@cksachdev See the `<b-modal>` docs section on the `static` prop: https://bootstrap-vue.js.org/docs/components/modal#lazy-loading-and-static-modals

**Comment by Hiws** [comment]
@cksachdev 
You might also be interested in reading about deep-selectors (`/deep/`) to better understand why it's needed.

https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

**Comment by cksachdev** [comment]
Thank you @Hiws @tmorehouse 👍
