### ISSUE TITLE
Simple way to populate/filter/order a b-card-group with lots of cards

### ISSUE THREAD

**Issue by laurent-brisbois** [bootstrap-vue/bootstrap-vue#4700]
### Is your feature request related to a problem? Please describe...

I want to display some information in `b-card` but I don't know how much I'll have so I'd like it to be more dynamic.
Also `:filter` & `:order` Would be great ! 

### Describe the solution you'd like

Would it be possible to use something like `:items` mixed with slots so that it looks like `b-table` and others similar components ?

### Describe alternatives you've considered

 Maybe the only solution is to use a `v-for` in a `b-card-group` ?
No idea for the `:filter` and `:order`

### Additional context

/

**Comment by tmorehouse** [comment]
You can use a `v-for` loop over an array to generate a list of b-cards, and you can use a computed prop based on your original array to filter and sort the array before passing it to v-for:

```js
export default {
  // ...
  data() {
    return {
      filter: 'f',
      items: [
        { title: 'B', content: 'Foo' },
        { title: 'A', content: 'Bar' },
        { title: 'C', content: 'Baz' }
      ]
    }
  },
  computed: {
    computedItems() {
      // make a shallow copy of the array, so we don't mutate the original array
      const items = this.items.slice()
      // return a filtered and sorted array
      return items.sort((a, b) => {
        // Sort by title
        return a.title < b.title ? -1 : a.title > b.title ? 1 : 0
      }).filter(item => {
        // Then filter by content
        return item.content.toLowerCase().indexOf(this.filter) !== -1
      })
    }
  }
}
```

**Comment by laurent-brisbois** [comment]
I see. But it would be cleaner and easier to provide at least a `:filter` and a `:order` no ?

**Comment by tmorehouse** [comment]
`b-card` is a generic wrapper component that can be used in a multitude of ways.  It is not a list style component per se.

What you are looking for is better created as a custom compound component (which renders b-card, and possibly its sub-components as children) for a specific use case, tailored to your data structure.

**Comment by laurent-brisbois** [comment]
I see. Thanks for your answer.
