### ISSUE TITLE
Make Vue use local ./node_modules build?

### ISSUE THREAD

**Issue by wolf-ben** [bootstrap-vue/bootstrap-vue#4706]
Hi guys,
thanks for helping me with this issue!

**Background:**
So while using BootstrapVue with Webpack I eventually came across the `[Vue warn]: $listeners//attrs is readonly.` message. BootstrapVue also gives me the warning `[BootstrapVue warn]: Multiple instances of Vue detected!` and redirects me to this page: [https://bootstrap-vue.js.org/docs#using-module-bundlers](url). I set an alias for vue like the example says under "Alisasing Vue Import" in my `webpack.config.js` and even changed the path to my Vue build (`vue.esm.js`) to an absolute path.
Still the warning wouldn't disappear, because I had a global Vue build under `Users/<usr>/node_modules`. This folder contained the exact same packages as my local `node_modules` in my project directory. So I deleted all global packages, including the Vue build. Now my web project won't build at all, because it still references the global Vue build instead of using the local one.

**Question:**
How can I set the configuration for Vue to use the local node_modules Vue build?

Thanks,
wolf-ben

**Code:**
_./webpack.config.js_
```
const path = require('path')
const { VueLoaderPlugin } = require('vue-loader')

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  resolve: {
    alias: {
      vue$: './node_modules/vue/dist/vue.esm.js'
    }
  },
  plugins: [
    new VueLoaderPlugin()
  ]
}
```

_./src/main.js_
```
import 'bootstrap/dist/css/bootstrap.css'; // eslint-disable-line import/no-extraneous-dependencies
import BootstrapVue from 'bootstrap-vue'; // eslint-disable-line import/no-extraneous-dependencies
import Vue from 'vue';
import 'bootstrap-vue/dist/bootstrap-vue.css'; // eslint-disable-line import/no-extraneous-dependencies
import App from './App.vue';
import router from './router';

Vue.use(BootstrapVue);

Vue.config.productionTip = false;

new Vue({
  router,
  render: h => h(App),
}).$mount('#app');
```

**Comment by jackmu95** [comment]
Have you tried `vue$: 'vue/dist/vue.esm.js' ` (without an relative or absolute path to `node_modules`)?

**Comment by wolf-ben** [comment]
Yes, that was my first attempt, but the Vue warnings then were thrown out of the `vue.esm.js` in `Users/<usr>/node_modules/vue/dist/`, which to me indicates that the project uses this Vue build instead of the local one.

**Comment by tmorehouse** [comment]
have you tried the full absolute path: 

```
  resolve: {
    alias: {
      vue$: '/Users/<usr>/node_modules/vue/dist/dist/vue.esm.js'
    }
  },
```

**Comment by wolf-ben** [comment]
No, I didn't try that.
But anyways, I reinstalled the whole project with only local installations of Vue, Bootstrap, BootstrapVue and all other packages. **It now seems to work just fine.** No more `[Vue warn]:` or `[BootstrapVue warn]:`, so I won't need the `webpack.config.json` alias anymore.

Idk why the alias wouldn't work in my case (or what I might have done wrong during setup). So anyone with the same issue just keep in mind to have either a _global_ Vue/Bootstrap/BootstrapVue installation (such installed via `npm install -g <package>` or a _local_ one (without `-g`) in your project directory. For me it helped to check if the Vue package originating the `[Vue warn]:` double-exists in the local and global `node_modules` folder.
