### ISSUE TITLE
double arrow icons in b-form-select if scss is imported

### ISSUE THREAD

**Issue by kzw** [bootstrap-vue/bootstrap-vue#4716]
### Steps to reproduce the bug

1. git clone git@github.com:kzw/vuetest.git
2. npm i && npm run dev
3. See double arrows in form select
4. In `css` and `override` branches you will not see double arrows

### Versions

**Libraries:**

- BootstrapVue: 2.3.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: mac
- OS: 10.15
- Browser: chrome, ff, safari
- Version: latest

### Additional context

In branch `css`
I use 
 https://bootstrap-vue.js.org/docs/#vue-cli-3 
to import css files into main.js

In branch `override`
I use a style as recommended in 
  https://stackoverflow.com/questions/48287610/bootstrap-4-beta-options-menu-has-double-dropdown-icons/48288103

In branch `master`
I use instructions in 
  https://bootstrap-vue.js.org/docs/#using-module-bundlers
to import `custom.scss` into main.js

I had also been creating `custom.css` from  `custom.scss` using `sass` command line utility and then importing `custom.css` with the same double arrow bug.    This approach is not in any branches though.

I believe that there is something wrong with merging `bootstrap` and `bootstrap-vue` in scss first.

**Comment by tmorehouse** [comment]
I see you are defining two sets of custom SCSS files... both importing the same sources.

Could you provide a minimal reproduction example via Codepen or Codesandbox?

**Comment by kzw** [comment]
I only use one of the files (`custom.scss`) file at 

`https://github.com/kzw/vuetest/blob/master/code/src/custom.scss `

That file contain only 2 lines of loading `bootstrap` and `bootstrap-cue` and nothing else.

There may be other scss file in the repo but only that `custom.scss`  file is used in the minimal reproduction example in the GitHub repo I submitted.

**Comment by tmorehouse** [comment]
If you inspect the elements you should see what is overriding the styles on the element.

Bootstrap v4.4.1 CSS should have the correct style overrides for hte select component.

If you are using the source SCSS files, make sure you include auto-prefixer with node SASS to ensure the appropriate browser dependent prefixed values are set.

As you can see in the source SCSS for custom forms for hte custom select, they use only `appearance: none` in the style.

https://github.com/twbs/bootstrap/blob/0d1aee6a2fecc865066c90e85422e192ca69ba34/scss/_custom-forms.scss#L219-L278

**Comment by kzw** [comment]
I also just removed unused `scss` file in the repo so as not cause confusion.  Also managed to reproduce the same situation.

You can also see the `git diff` between 3 branches to see how they differ.

Here is the diff between master and css branches

https://github.com/kzw/vuetest/compare/master..css

Here is the diff between `master` and `override`

https://github.com/kzw/vuetest/compare/master..override

**Comment by tmorehouse** [comment]
When auto-prefixer is used when compiling the SCSS, you should see:

![image](https://user-images.githubusercontent.com/2781561/73617008-d36fab80-45f0-11ea-9696-73cf001ccc65.png)

If you only see `appearance: none` and not the prefixed versions as well, then you are missing auto-prefixer in your SASS compile pipeline.

In our postcss.config.js we have:
```js
module.exports = ctx => ({
  map: {
    inline: false,
    annotation: true,
    sourcesContent: true
  },
  plugins: {
    autoprefixer: {
      cascade: false
    }
  }
})
```

**Comment by tmorehouse** [comment]
And when compiling teh SCSS we do:

```sh
node-sass --output-style expanded \
          --source-map true \
          --source-map-contents true \
          --precision 6 \
          scripts/build.scss \
          dist/bootstrap-vue.css
postcss --config scripts/postcss.config.js \
        --replace dist/bootstrap-vue.css
```
