### ISSUE TITLE
When opening a modal (bv::show::modal), other opened modals won't hide

### ISSUE THREAD

**Issue by ex1t3** [bootstrap-vue/bootstrap-vue#4717]
I encountered a problem with hiding modals on show events.
Let's imagine we have an opened modal. When I hit the following link (in example), the opened login modal should be immediately closed. But it doesn't act as described. The `remindPassword` modal just pops over the opened one. 

Am I missing something or what?

Example:
`<a @click="$root.$emit('bv::show::modal', 'remindPassword')" href="#">I don't remember my password</a>`

**Comment by Hiws** [comment]
Sounds like you're looking for this https://bootstrap-vue.js.org/docs/components/modal#multiple-modal-support section of the docs.

**Comment by tmorehouse** [comment]
Also, it is probably better to use `this.$bvModal.show(id)` to open a modal instead of emitting the event name.

**Comment by ex1t3** [comment]
> Sounds like you're looking for this https://bootstrap-vue.js.org/docs/components/modal#multiple-modal-support section of the docs.

No, I just want to trigger hide event when I open a modal

**Comment by tmorehouse** [comment]
Listen for the modals `show` event, and then emit a hide event (or use `this.$bvModal.hide(id)`) to close the other modal.  Setting `no-stacking` on the first modal will also automatically close the first modal when the second modal opens (as shown in the docs example https://bootstrap-vue.js.org/docs/components/modal#multiple-modal-support)

**Comment by ex1t3** [comment]
> Listen for the modals `show` event, and then emit a hide event (or use `this.$bvModal.hide(id)`) to close the other modal. Setting `no-stacking` on the first modal will also automatically close the first modal when the second modal opens (as shown in the docs example https://bootstrap-vue.js.org/docs/components/modal#multiple-modal-support)

Yeap, I've read the documentation and it has successfully solved my problem. Thank you for paying attention, my friend :)
