### ISSUE TITLE
<b-alert visible when using empty string for :show prop

### ISSUE THREAD

**Issue by daaavvve** [bootstrap-vue/bootstrap-vue#4719]
### Describe the bug

According to the b-alert documentation, the :show prop takes a boolean, number, or String.  If I v-bind onto an empty string the alert should be hidden, but it is visible.

### Steps to reproduce the bug

1. Create a b-alert, and v-bind to an empty string
2. See that the b-alert is visible

### Expected behavior

The b-alert should be hidden, since I'm v-binding to an empty string.

### Versions

**Libraries:**

- BootstrapVue: 2.3.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Desktop
- OS: [Ubuntu 18.04 and Windows 10]
- Browser: Firefox, Chrome, and Edge
- Version: [72.0.2, 79.0.3945.130, 44.17763.831.0]

### Demo link

https://codepen.io/daavve/pen/gObVEjX

### Additional context
```
<template>
<div id="app">
    <b-alert
      :show=emptyString         
    >
      Should be hidden because of empty string. Likely a bug
    </b-alert>
</div>
</template>

<script>
export default {
  data(): {
    return {
      emptyString: '''
    }
  }
}
</script>
```

**Comment by tmorehouse** [comment]
Vue treats empty string as `true` for props that support `Boolean` values.  This is expected.

**Comment by daaavvve** [comment]
Thanks for the quick feedback.  Could you give me a little more clarification?

Inside the https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/alert/alert.js,

I see the following code:
```
// Convert `show` value to a boolean
const parseShow = show => {
  if (show === '' || show === true) {
    return true
  }
  if (toInteger(show) < 1) {
    // Boolean will always return false for the above comparison
    return false
  }
  return !!show
}
```
...
```
  data() {
    return {
      countDownTimerId: null,
      countDown: 0,
      // If initially shown, we need to set these for SSR
      localShow: parseShow(this.show)
    }
  },
```

If I understand the code correctly, it's testing the incoming prop to see if it is an empty string, and then setting localShow to true.

**Comment by tmorehouse** [comment]
When a prop supports multiple types, and one of those is Boolean and one is String, and when doing this:

```html
<b-alert show> .... </b-alert>
```

Where `show` is being used in a Boolean context, Vue (depending on the version) will set the prop value to an empty string instead of `true`.  That check handles this case.  Type String is only there to support passing a number as a string, not to support arbitrary strings.

**Comment by daaavvve** [comment]
Thank you again for the quick clarification tmorehouse.  I'm closing this issue.  Have a good day.
