### ISSUE TITLE
Iterative tabs +constant tab issue

### ISSUE THREAD

**Issue by milenon** [bootstrap-vue/bootstrap-vue#472]
If we have the following tabs:

```
<b-tabs card>
    <b-tab :title="`${tabz[key].nativeName}`" v-for="(lang, key, i) in tabz" :key="i">
        Tab Contents: {{tabz[key].name}}
    </b-tab>
    <b-tab title="+">
        Plus tab content
    </b-tab>
</b-tabs>
```
.. everything is fine if the tab's data is already loaded on the page like this:

```
        data () {
            return {
                tabz: {
                    bg: {
                        name: "Bulgarian",
                        nativeName: "Български"
                    },
                    en: {
                        name: "English",
                        nativeName: "English"
                    }
                },
                ....
```

... but if the data comes later(from server) the result is that two tabs will be selected (the first one(Bulgarian) and the '+' tab) and we will see the content of the both selected tabs together. This can be simulated like this:

```
        data () {
            return {
                tabz: null,
                ...


        created () {
            setTimeout(() => {
                this.tabz = {
                    bg: {
                        name: "Bulgarian",
                        nativeName: "Български"
                    },
                    en: {
                        name: "English",
                        nativeName: "English"
                    }
                }
            }, 1000);
```

**Comment by tmorehouse** [comment]
This might be because the tabs component is not detecting the change to the content of the tab's.

**Comment by milenon** [comment]
Here it is:
https://jsfiddle.net/b4po25y4/

**Comment by tmorehouse** [comment]
Perfect.

I think I know where the issue is in b-tabs.  It is the routine that deactivated the last active tab.

In this case the initial active tab index is 0 (the '+' tab), and then the new tabs are added, the current tab is still index 0, but the tab that was active is now index 2 (the '+').

Would you expect the '+' tab to stay active when the new tabs are inserted before? or change to the first new tab?

**Comment by milenon** [comment]
Change to the first new tab, because they appear in front of the '+' tab in the DOM.

**Comment by tmorehouse** [comment]
OK, I think I can fix this relatively easily for next release.

**Comment by milenon** [comment]
Thanks :)

**Comment by tmorehouse** [comment]
What might happen is that the same tab index will be selected on update of the tabs content (to keep current functionality when adding tabs to the end).  Of which you could then issue a set active tab to reset it to index 0 after your update.

**Comment by tmorehouse** [comment]
Fix should be available in next release.

**Comment by milenon** [comment]
Thanks :)

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
