### ISSUE TITLE
Tooltip css glitch with placement

### ISSUE THREAD

**Issue by luhaolu** [bootstrap-vue/bootstrap-vue#4721]
### Describe the bug

Create a tooltip with any placement of: topleft, topright, righttop, rightbottom, bottomleft, bottomright, lefttop, and leftbottom and observed there is a small gap between "tooltip-inner" and "arrow"

### Steps to reproduce the bug

1. Create a tooltip
2. Set placement property as "topleft"
3. Open the tooltip
4. See there is a gap between the arrow and tooltip-inner. This is likely due to the broader radius of tooltip-inner
![image](https://user-images.githubusercontent.com/6394168/73701062-2bfc8280-469d-11ea-9cfb-4ad728e785fd.png)

### Expected behavior

Position of the arrow is adjusted (likely with an offset of the border radius) so there isn't a gap.

### Versions

**Libraries:**

- BootstrapVue: 2.3.0
- Bootstrap: 4.4.1
- Vue: 2.6.10

**Environment:**

- Device: Desktop
- OS: Win 10
- Browser: Chrome
- Version: 79.0.3945.130

**Comment by tmorehouse** [comment]
We are in the process of upgrading to Popper.js v2,x, which should hopefully fix a few of these issues.

**Comment by jackmu95** [comment]
Closed by #4727.
