### ISSUE TITLE
Modal header/footer transitions

### ISSUE THREAD

**Issue by lllopo** [bootstrap-vue/bootstrap-vue#4722]
I'm using the b-modal in combination with custom footer and tabs inside the modal and I want to hide the footer when a certain tab is selected. This works quite well binding the tabs v-model to the modal's hide-footer property. The problem is, that all other interactions of such type I'm doing are very well transitioned and elegant and for that, the instant show/hide of the footer looks rather choppy. So, my question/request is adding  the option to define transitions for showing/hiding the header and footer.

**Comment by Hiws** [comment]
While not the ideal solution, you could recreate the modal structure yourself and add in `<transition>` and use `v-if` on your header and footer to apply what transition you want.

Doing this you lose most of the standard `b-modal` props, but you could create your own wrapper component to add it back and make it easier to use.

Another option would be to utilize something like `Animate.css` and conditionally add their classes to apply animations to the header and footer before hiding them.
I have an example of this in the codepen at the bottom.

```html
<b-modal id="modal" body-class="p-0" hide-header hide-footer>
  <transition name="fade">
    <header class="modal-header" v-if="!hideHeader">
      <h5>
        Modal Title
      </h5>
      <b-button-close></b-button-close>
    </header>
  </transition>
  <div class="modal-body">
    <b-checkbox v-model="hideHeader" switch>Hide Header</b-checkbox>
    <b-checkbox v-model="hideFooter" switch>Hide Footer</b-checkbox>
  </div>
  <transition name="fade">
    <footer class="modal-footer" v-if="!hideFooter">
      <b-btn>Close</b-btn>
      <b-btn variant="primary">Ok</b-btn>
    </footer>
  </transition>
</b-modal>
```

Example of above code.
https://codepen.io/Hiws/pen/qBdWaqr

**Comment by lllopo** [comment]
Yeah, thanks for the idea. I'd probably go the "recreate footer structure" route, but would be nice if this is available out of the box somehow.
