### ISSUE TITLE
popover directive hide issue (bv::hide::popover) when button becomes disabled

### ISSUE THREAD

**Issue by nat1597** [bootstrap-vue/bootstrap-vue#4725]
### Describe the bug

I am having trouble with canceling (hiding) a popover on a button that becomes disabled on click and the popover persisting until another element is clicked or the button itself becomes un disabled and hovered over again.

This only occurs when the delay (show) property is applied to the directive and when the button is clicked within the delay time.

### Steps to reproduce the bug

1. Mouse over button
2. Click button before the delay interval (500 ms in sample below).
3. Notice popover persists even when mousing off/clicking outside of button.

### Expected behavior

The popover should retain normal behavior on enabled button (should become hidden upon mouse out/click off button).

Ideally, there would be a reliable way to stop or cancel popover behavior on "@click" event regardless of button state (disabled/not disabled) as this behavior manifests itself even when button does not become disabled where I would like the popover to hide on "@click" so the popover does not show after the button is clicked.

### Versions

**Libraries:**

- BootstrapVue: 2.4.0
- Bootstrap: 4.1.1
- Vue: 2.6.11

**Environment:**

- Device: N/A
- OS: N/A
- Browser: Chrome/Firefox
- Version: 80.0.3987.87 (Official Build) (64-bit)

### Demo link
https://jsfiddle.net/g2j0vctn/6/

**Comment by tmorehouse** [comment]
To get around this, listen for the popover/tooltip events and disable the input then, or cancel the popover/tooltip show event.  Or optionally when disabling the button emit a hide event.

**Comment by nat1597** [comment]
Thanks for your prompt reply.  I am having a hard time listening for the show event.  Can you tell me what the listener is or is it listed somewhere in the docs?

**Comment by tmorehouse** [comment]
Ah, with the directive version, the ID is auto-generated.  Will have to think about this a bit. You may need to switch to the component version which allows for manual control over the popover/tooltip.

**Comment by nat1597** [comment]
OK, thanks for your help.

**Comment by nat1597** [comment]
I was able to find a solution for this issue while still using the directive version by hooking into the 'bv::popover::show' event and canceling the popover show event (bvEvent.preventDefault()) - https://bootstrap-vue.js.org/docs/components/popover/#comp-ref-b-popover.

Thanks for leading me down the right path.

Demo Link: https://jsfiddle.net/vuw2cq9x/

**Comment by a-salimkhanov** [comment]
I solved it just adding
 
`this.$root.$emit('bv::hide::popover');`

 to the function that is bound to the button's click event.
