### ISSUE TITLE
Remove the validation status when the text field is correct

### ISSUE THREAD

**Issue by leo95works** [bootstrap-vue/bootstrap-vue#4726]
Hello! I am currently using [Bootstrap-Vue](https://bootstrap-vue.js.org/), I am trying to validate a form, I want that when the validation is not fulfilled, I mark the text field as having errors, but when I have no errors, I just leave it normal. Example
This is my text field, at least it must contain 6 characters to pass the validation

![image](https://user-images.githubusercontent.com/60673955/73790884-40a94b00-476f-11ea-8d98-807d77c38243.png)

when it reaches 6 characters it shows me that the text field is fine, and that it meets the expected requirements, but I want that when this happens, I leave the text field without any style

![image](https://user-images.githubusercontent.com/60673955/73790935-5fa7dd00-476f-11ea-92b5-d7d3391fbe59.png)

I mean, this way

![image](https://user-images.githubusercontent.com/60673955/73791043-97168980-476f-11ea-9067-468ca84d270a.png)

This is the structure of how I have defined this text field

```
<validation-provider v-slot="errors" name="password" :rules="min:6">
 <b-form-input type="password" v-model="password" :state="state(errors)" :placeholder="Password"></b-form-input>
</validation-provider>

```

and in the scripts section
```
export default {
methods: {
            state({ dirty, validated, valid = null }) {
                return dirty || validated ? valid : null;
            },
        },
...
}
```

**Comment by tmorehouse** [comment]
Set the state to `null` instead of `true` to remove the valid styling (`valid = valid === true ? null : valid`).

If you just want to remove the icon, you will need to use custom CSS/SCSS to remove the background image.

**Comment by leo95works** [comment]
@tmorehouse 
Thank you very much .. now it works
```
methods: {
            state({ dirty, validated, valid = null }) {
                return dirty || validated ? (valid = valid === true ? null : valid) : null;
            }
        },
```

**Comment by tmorehouse** [comment]
You could probably just simplify to:

```js
methods: {
            state({ dirty, validated, valid = null }) {
                return dirty || validated ? (valid ? null : valid) : null;
            }
        },
```
