### ISSUE TITLE
b-form-checkbox shows checked state even though value is false

### ISSUE THREAD

**Issue by spaceemotion** [bootstrap-vue/bootstrap-vue#4731]
### Describe the bug

We have a use case for only enabling check boxes when a modal has been filled out (it opens after checking the checkbox). In case the modal is being closed prematurely, the checkbox should stay unchecked.

### Steps to reproduce the bug

1. https://codepen.io/spaceemotion/pen/yLNBGGY
2. Check the checkbox
3. Expect it to not change its visual state

### Expected behavior

The checkbox should stay unchecked.

### Versions

**Libraries:**

- BootstrapVue: 2.4.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: Mojave
- Browser: Chrome
- Version: 76

### Demo link

https://codepen.io/spaceemotion/pen/yLNBGGY

### Additional context

If you uncomment the `return;` inside the setter, the provided workaround does work. It's just tedious to copy and paste it all over.

**Comment by tmorehouse** [comment]
Your best bet is to use the "disabled" prop, which would provide better meaning back to screen reader users that value can't be  selected/unselected until a certain condition is met.

As well, it is needed to have the `$nextTick` to change the value sent by the v-model event, as the change is happening within vue's micro task queue so it can't detect that the value is being changed back (the child component does not see the change).
