### ISSUE TITLE
b-form-select: v-model and on change

### ISSUE THREAD

**Issue by steeldimon** [bootstrap-vue/bootstrap-vue#4732]
### Describe the bug

for bootstrap select v-model, I'm take option value, but, in same time I want to call callback function. If I'm use v-model, @change not working. If I delete v-model, all work fine, except I don't know in my function, what is options has been selected.

### Expected behavior

v-model and v-on:change work together

### Versions

**Libraries:**

"bootstrap": "^4.3.1",
"bootstrap-vue": "^2.4.0",

**Environment:**

- Device: MacBook Pro 13 2017
- Browser: Chrome

**Comment by tmorehouse** [comment]
Could you create a minimal reproduction of your issue?  you can export code easily from the documentation playground to JsFiddle, CodePen or CodeSandbox

**Comment by steeldimon** [comment]
> Could you create a minimal reproduction of your issue? you can export code easily from the documentation playground to JsFiddle, CodePen or CodeSandbox

Interesting, on jsfiddle with same version, that code work fine:
https://jsfiddle.net/2ja1b5f3/.

**Comment by steeldimon** [comment]
> > Could you create a minimal reproduction of your issue? you can export code easily from the documentation playground to JsFiddle, CodePen or CodeSandbox
> 
> Interesting, on jsfiddle with same version, that code work fine:
> https://jsfiddle.net/2ja1b5f3/.

"We need to go deeper", my select form work with objects in table rows, with hard logic behavior...

**Comment by steeldimon** [comment]
> > > Could you create a minimal reproduction of your issue? you can export code easily from the documentation playground to JsFiddle, CodePen or CodeSandbox
> > 
> > 
> > Interesting, on jsfiddle with same version, that code work fine:
> > https://jsfiddle.net/2ja1b5f3/.
> 
> "We need to go deeper", my select form work with objects in table rows, with hard logic behavior...



> > > Could you create a minimal reproduction of your issue? you can export code easily from the documentation playground to JsFiddle, CodePen or CodeSandbox
> > 
> > 
> > Interesting, on jsfiddle with same version, that code work fine:
> > https://jsfiddle.net/2ja1b5f3/.
> 
> "We need to go deeper", my select form work with objects in table rows, with hard logic behavior...
> 
> update 1:
> same code, as in jsfiddle link, worked in my project too.
> possibly a problem in the tables.
> update2: No, simple variant, worked in tables too.

this is code:
`<template v-slot:cell(user_request)="{ item }">
                    <div v-if="not_used_user_requests.length && !item.user_request">
                        <b-form-select v-model="item.user_request" class="mb-3" @change="say">
                            <b-form-select-option v-for="(o, index) in not_used_user_requests" :value="o"
                                    :key="index">
                                {{o}}
                            </b-form-select-option>
                        </b-form-select>
                        <div class="mt-2">Selected: <strong>{{ selected }}</strong></div>
                    </div>
                    <div v-else>
                        {{item.user_request}}
                    </div>
                </template>`
if I'm change "item.user_request" for cell item, to global variable, @change call function, if v-model work with table row item, like this: "item.user_request", @change do nothing
