### ISSUE TITLE
Skip icons misnamed

### ISSUE THREAD

**Issue by donqstepper** [bootstrap-vue/bootstrap-vue#4733]
### Describe the bug

The icons for the names "skip-backward-fill" and "skip-end-fill" have been swapped.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/icons/
2. Search for 'skip'
3. Look at the differences between "skip-backward" and "skip-backward-fill", and "skip-end" and "skip-end-fill".

### Expected behavior

Expected "skip-backward" and "skip-backward-fill" to resemble each other, same with "skip-end" and "skip-end-fill".

### Versions

**Libraries:**

Locally:
- BootstrapVue: 2.2.2
- Bootstrap: 4.4.1
- Vue: 2.6.10

But also whatever versions are used for the official bootstrap-vue website.

**Environment:**

- Device: Laptop
- OS: Linux
- Browser: Firefox
- Version: 72

### Demo link

https://bootstrap-vue.js.org/docs/icons/

### Additional context

None that I can think of

**Comment by donqstepper** [comment]
My apologies; I have just realised this is an upstream issue.

https://github.com/twbs/icons/issues/84

**Comment by tmorehouse** [comment]
If you could give the upstream issue a thumbs up, that would be great. it would help with getting bootstrap icons alpah.3 released

**Comment by tmorehouse** [comment]
It appears that this will be fixed in Boootstrap Icons [v1.0.0-alpha3](https://github.com/twbs/icons/projects/2)
