### ISSUE TITLE
[Docs] Confusing statements about BFormRadioGroup props

### ISSUE THREAD

**Issue by nickforddesign** [bootstrap-vue/bootstrap-vue#4736]
### Describe the bug

The language in the docs around `b-form-radio-group` and `v-model` is very confusing.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/form-radio/

> `<b-form-radio>` and `<b-form-radio-group>` do not have a value by default. You must explicitly supply a value (to which the `v-model` is set to when the radio is checked) via the `value` prop.

VS next paragraph:

> The `v-model` of both `<b-form-radio>` and `<b-form-radio-group>` binds to the `checked` prop. To pre-check a radio, you must set the v-model value to the radio's value. Do not use the `checked` prop directly.

These 2 paragraphs are very confusing. First it is stated that you must supply a value to the `value` prop, then it is stated that in fact, `v-model` is bound to the ` checked` prop, and finally that you should not use that prop directly anyway.

One **might** walk away with an understanding of what to do, but not after jumping through a bunch of hoops. 

### Expected behavior

If the `value` prop is not bound to `v-model`, don't say that it must be passed. Why even mention the `checked` prop if we should not pass it directly anyway? Also I've tested this out, and passing `checked` seems to work just fine...

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: N/A
- OS: N/A
- Browser: Chrome
- Version: 80

Thanks!

**Comment by tmorehouse** [comment]
The `value` is the value of the radio button when it is _checked_  (radios do not have a value by default which is why a value must be specified)

The `checked` prop is what the v-model binds to, which is the same as how v-models and values are set on native radio type inputs works with Vue: https://vuejs.org/v2/guide/forms.html#Radio

**Comment by jackmu95** [comment]
Closed by #4736.
