### ISSUE TITLE
Variable Source Path

### ISSUE THREAD

**Issue by ChrisHarveyHub** [bootstrap-vue/bootstrap-vue#4741]
Hi, is there a way to include the video source path as a variable?  Hoping to be able to load most of the path in my config and then pull the filename from other data in my component.

So instead of:

```html
<b-embed type="video" controls>
        <source src="../../../../path/to/myproject/filename.mp4" type="video/mp4" />
</b-embed>
```

I'd like to be able to do:

config.json:
```js
        "pathToOutputMedia": "../../../../path/to/myproject/",
```

vuePage.vue:
```html
        <b-embed type="video" controls>
                 <source src="assetPath" />
        </b-embed>
        <script>
                 var assetPath = config.pathToOutputMedia + "filename.mp4";
        </script>
```

**Comment by tmorehouse** [comment]
Check out this section:  https://bootstrap-vue.js.org/docs/reference/images (it applies to b-embed as well)

For you script section, the variable `assetPath` needs to be bound to your component instance:

 ```html
<template>
  <b-embed type="video" controls>
    <source src="assetPath" />
  </b-embed>
</template>

<script>
export default {
  computed() {
    assetPath() {
      return config.pathToOutputMedia + "filename.mp4";
    }
  }
}
</script>
```

**Comment by ChrisHarveyHub** [comment]
Hey @tmorehouse, thanks for the response!  I see how my original post was incorrect but I still can't quite get your suggestion to work (I get a formatting error when I use "computed()" instead of "computed:" but either way the function doesn't fire.  In my original script tag I didn't communicate it but I did have it bound to the component instance by:
<template>
    <b-embed type="video" controls>
           <source src="embedSource" type="video/mp4" aspect="16by9" />
    </b-embed>
</template>
<script>
export default {
  data: function() {
      embedSource: ""
  }
  methods:
      computePath() {
           ....
           this.embedSource = resultOfAPICall;
           ....
      }
</script>

And I can see the path to the file when I inspect the element but the video won't play.

**Comment by tmorehouse** [comment]
I had a typo in my example above.  it should have been `computed:` (I've updated the example above)

Is the src path available to your web server? it might be that it is not accessible (as most servers restrict the path to the root of the web server). Do you have an assets folder defined?

**Comment by ChrisHarveyHub** [comment]
Ok that's what I'd figured so I tried using "computed:" as well but I couldn't see any evidence of the function firing when I had a breakpoint in there so the value wasn't updating.

The src path is available and works when the path is hard-coded to that attribute.  The issue is only arising when I use a variable definition but I'm extra confused because when I inspect the path I see the same path as the one I've hard-coded.

Now I've got:
<b-embed type="video" controls>
      <source src="assetPath" />
</b-embed>
<script>
export default {
  data: function() {
      embedSource: ''
  },
  computed: {
      assetPath () {
          return this.embedSource;
      }
  },
  methods: {
     *calculate embedSource here based on data that's grabbed when a table row is clicked
  }
</script>

**Comment by tmorehouse** [comment]
When you look at the result that is rendered, what do you see as a URL for the `src`?  Is it a path that is accessible via a web browser on the server?

Using a variable will not copy the asset to the webserver public dirs.

**Comment by ChrisHarveyHub** [comment]
I believe the path is accessible on the browser but I can't see the full path when using a variable tied to a computed element.  When I inspect the element this is what I see:
![AssetPath](https://user-images.githubusercontent.com/14862980/74197447-8a8da780-4c2d-11ea-9457-a41ea28fff2e.PNG)

And when I hover over AssetPath it shows me the URL http://localhost:8081/AssetPath

But when I had the source configured to reference an item from the data object:
<b-embed type="video" controls>
      <source :src="sourcePath" />
</b-embed>
export default {
  data: function() {
      sourcePath: ''
  },
  methods: {
     *calculate embedSource here based on data that's grabbed when a table row is clicked
  }

I could inspect the element and directly see the path listed as "../../../../aeutil/fileDir/filename.mp4" which is the same path that worked when hard-coded (and is the same path being calculated for the assetPath function)

**Comment by ChrisHarveyHub** [comment]
And sorry I missed answering your question directly before but these files I'm referencing are being stored outside of the project folder.

**Comment by tmorehouse** [comment]
I just realized on of your issues (once seeing your rendered output):

```html
<b-embed type="video" controls>
      <!-- src needs to be v-bind to accept a variable -->
      <source :src="assetPath" />
</b-embed>
```

**Comment by ChrisHarveyHub** [comment]
Ok sweet, that makes sense and with that I get the function assetPath to fire.  That also clarifies your earlier question about whether I can view the file in a browser (I can't).

The path I see when I inspect the element now is "../../../../aeutil/fileDir/filename.mp4" which when I hover over translates to "http://localhost:8081/aeutil/fileDir/filename.mp4".

The issue I'm seeing now is that when I paste the above url into a browser, I see the landing point for my site on localhost rather than the video.

**Comment by tmorehouse** [comment]
That is because web server will only serve documents/files that fall under the root path of the server (for security reasons) The root of your URL is `http://localhost:8081/`, so no matter how many `../` you prepend you can never get above that.

Imagine someone attempting to do this:

```
http://localhost:8081/../../../../etc/password
```

or similar to extract password files off of a server.

**Comment by ChrisHarveyHub** [comment]
Ok that makes sense for sure, and I was able to get a single file working within the same folder as my .vue file that is embedding it so thank you very much for all your help! Now when I click another row in the table to select a different file to embed, the older file stays rendered instead but I'm much closer than before.

I've come across people using "require.context" to help with my earlier issue.  Do you know if this might have any bearing here?

**Comment by ChrisHarveyHub** [comment]
One thing that still has me confused though is how I would serve files from any other location in my project that's a parent of the .vue file that's referencing them without using "../"

**Comment by tmorehouse** [comment]
Depending on your loader configs, prefixing path strings with `~` or `@` (aliases) can reference different locations within your project structure..

You can also use `:src="require(somePath)"` in certain situations.

https://stackoverflow.com/questions/37671342/how-to-load-image-files-with-webpack-file-loader

**Comment by ChrisHarveyHub** [comment]
Amazing.  Because of when the webpack is bound, the require bit is what did the final trick. Thank you so much for your help @tmorehouse !

**Comment by ChrisHarveyHub** [comment]
Hey @tmorehouse, thanks for all your help earlier this week! I'm now realizing that the way I have this set up (using require() for the path) is making my project reload every time a new proxy video is dropped at my :src="require(somePath)".

Do you know how to disable hotreload for something like this? It's ok for development but will basically break the project once in production with all that reloading.
