### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by scottadamsmith** [bootstrap-vue/bootstrap-vue#4743]
One of the biggest draws of this library was the incredible effort that is put into making everything accessible and documenting things that should be done outside of the bounds of the components themselves. I want to become an expert in this area and I am learning so much more about it as I use these tools and see the techniques being used. So thanks!

**Comment by tmorehouse** [comment]
Glad you are enjoying BootstrapVue!

**Comment by camelG** [comment]
Thank you for the release of datepicker.
Super convenient

**Comment by japalvia-fi** [comment]
Thanks for the whole bootstrap-vue - I love it! Adding calendar/datepicker components was super-cool! Keep up the good work! :)
