### ISSUE TITLE
Components that renders <a> produces error log

### ISSUE THREAD

**Issue by jirehnimes** [bootstrap-vue/bootstrap-vue#4745]
### Describe the bug

Components created by this that renders <a> produces error log with this message:

"The .native modifier for v-on is only valid on components but it was used on \<a\>."

### Steps to reproduce the bug

1. Use the b-tabs > b-tab components.
2. Errors will log with the message mentioned above.

### Versions

**Libraries:**

"vue": "^2.6.11"
"vue-loader": "^15.7.1"
"vue-template-compiler": "^2.6.11"
"bootstrap-vue": "^2.0.0-rc.28"

**Environment:**

- Device: Laptop
- OS: Windows 10
- Browser: Chrome

**Comment by jirehnimes** [comment]
Issue fixed when updating the plugin to "bootstrap-vue": "^2.4.0",

**Comment by es5es5** [comment]
@jirehnimes
Hello,
I faced same issue.
**Is the solution only VERSION UP?**

my dependencies
"vue": "^2.6.10",
"bootstrap-vue": "=2.0.0-rc.26",
