### ISSUE TITLE
TypeError: Assignment to constant variable. in esm.min.js

### ISSUE THREAD

**Issue by kskalski** [bootstrap-vue/bootstrap-vue#4748]
Starting at 2.2.0 (compared to 2.1.0) importing bootstrap-vue/dist/bootstrap-vue.esm.min.js causes following exception

TypeError: Assignment to constant variable.
    at s (D:\rep\Kogut\src\ElectronUI\node_modules\bootstrap-vue\dist\bootstrap-vue.esm.min.js:10:369)
    at d (D:\rep\Kogut\src\ElectronUI\node_modules\bootstrap-vue\dist\bootstrap-vue.esm.min.js:10:532)
    at D:\rep\Kogut\src\ElectronUI\node_modules\bootstrap-vue\dist\bootstrap-vue.esm.min.js:10:9522
    at Object.<anonymous> (D:\rep\Kogut\src\ElectronUI\node_modules\bootstrap-vue\dist\bootstrap-vue.esm.min.js:10:10523)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (D:\rep\Kogut\src\ElectronUI\renderer\admin\admRenderer.js:1)
    at Generator.next (<anonymous>)

note that importing bootstrap-vue/dist/bootstrap-vue.esm.js is fine and doesn't cause the error

### Steps to reproduce the bug

import BootstrapVue from 'bootstrap-vue/dist/bootstrap-vue.esm.min.js';

see exception error in console

### Expected behavior

No error

### Versions

**Libraries:**

- BootstrapVue: 2.2.0-2.4.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**
Electron, ESM loaded file compiled from Typescript

- Device: x64 latop
- OS: Windows 10
- Browser: Chrome 80 (Electron 8.0)
- Version: 80

**Comment by tmorehouse** [comment]
When using a module bundler, it is best to use the un-minified versions of the library, and allow your bundler to handle the final minification of the modules (as well the minified versions are not tree shakeable).

But there might have been a bug introduced with the updated JS compression lib (terser) and options.

**Comment by jackmu95** [comment]
I've created a CodeSandbox and the `bootstrap-vue.esm.min.js` and `bootstrap-vue.esm.js` imports both work fine:
https://codesandbox.io/s/beautiful-hooks-4v9sy

**Comment by tmorehouse** [comment]
Unless there is something that electron is doing in trying to assign to an existing variable.

**Comment by kskalski** [comment]
One maybe related detail, my scripts are loaded up using standard-things/esm module (can't get electron to load it in module mode otherwise), thus the error is caught from within esm:
```
D:\rep\Kogut\src\ElectronUI\node_modules\esm\esm.js:1 Uncaught D:\rep\Kogut\src\ElectronUI\node_modules\bootstrap-vue\dist\bootstrap-vue.esm.min.js:10
```
