### ISSUE TITLE
b-popover: focus not work in firefox and safari

### ISSUE THREAD

**Issue by zWingz** [bootstrap-vue/bootstrap-vue#4749]
see in document [https://bootstrap-vue.js.org/docs/components/popover/#variants-and-custom-class](https://bootstrap-vue.js.org/docs/components/popover/#variants-and-custom-class)

`b-popover` focus trigger not work in firefox and safari, but work in chrome

![image](https://user-images.githubusercontent.com/13031838/74138062-d8a1ab80-4c2b-11ea-8a7b-67a26beeb8ab.png)

**Comment by tmorehouse** [comment]
Strange. It works in Firefox for me. I don't have safari to test through.

**Comment by zWingz** [comment]
@tmorehouse not work in MACOS 10.15  work in windows

**Comment by jackmu95** [comment]
@tmorehouse I can confirm that it is working for Chrome on MacOS but isn't for Firefox and Safari.
I will look into this.

**Comment by jackmu95** [comment]
Wether a button can have a focus state is depending on browser and OS.
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus

**Comment by tmorehouse** [comment]
@jackmu95 interesting.

I wonder fi this may affect other things that rely on `focusin`/`focusut`/`focus`/`blur` handling.

**Comment by tmorehouse** [comment]
On click, if the trigger is `focus` only, we could maybe add in `try { element.focus() } catch {}` to trigger focus on the button when the trigger element is clicked

**Comment by jackmu95** [comment]
@tmorehouse Yeah that could be a possible workaround.

**Comment by tmorehouse** [comment]
Or the other option is to just document that MacOS doesn't trigger focus on buttons.

**Comment by jackmu95** [comment]
Yeah, maybe it's just a limitation we and the users have to accept.
We cant work properly around it anyway.

**Comment by austriker27** [comment]
Also `triggers="focus"` does not work on iOS in Chrome, Safari or Firefox (Apple uses Safari as the rendering engine for all browsers on iOS). 

If I remove that focus or change it to the click, it works however then a user must click the popover again to close it. It does not minimize when clicked anywhere else or on new popovers.

**Comment by tmorehouse** [comment]
Does Bootstrap v4.x native have the same issue?  It sounds like they might:

https://getbootstrap.com/docs/4.4/components/popovers/#dismiss-on-next-click

> ### Dismiss on next click
>
> Use the `focus` trigger to dismiss popovers on the user’s next click of a different
> element than the toggle element.
>
> > #### Specific markup required for dismiss-on-next-click
> >
> > For proper cross-browser and cross-platform behavior, you must use the `<a>`
> > tag, not the `<button>` tag, and you also must include a `tabindex` attribute.

**Comment by tmorehouse** [comment]
Maybe we need to add a bit of text about this in the docs, and suggest to use:

```html
<b-button href="#" v-b-popover.focus ... ></b-button>
```

Which will render a a link that behaves and acts like a button (with appropriate ARIA role and event listeners)

**Comment by zWingz** [comment]
so i have to use `<b-button href="#" tabindex="0" v-b-popover.focus ... ></b-button>`  to make `focus` work ?

**Comment by tmorehouse** [comment]
@zWingz on MacOS and iOS would need to
