### ISSUE TITLE
Option to allow label to be positioned on the left of checkboxes and radios

### ISSUE THREAD

**Issue by Soviut** [bootstrap-vue/bootstrap-vue#4752]
### Is your feature request related to a problem? Please describe...

There are certain cases with checkboxes/radios where a left-aligned label is useful. For example, when dealing with switches that are right aligned to a card.

![image](https://user-images.githubusercontent.com/226882/74282111-9640a300-4ced-11ea-9cc5-3170b4a0d4a6.png)

### Describe the solution you'd like

Add a `label-position` prop to `<b-form-checkbox>`, `<b-form-checkbox-group>`, `<b-form-radio>`, `<b-form-radio-group>`. This prop could be set to `left` or `right` but defaults to `right`. This would do exactly what it says and render the label to either the left or right hand side of the checkbox/radio.

### Describe alternatives you've considered

We might be able to get away with a flexbox `order` css trick if the checkbox and label lived inside a flex container.

This can be done manually in HTML but requires abandoning most of the work that the Bootstrap Vue components are doing.

Additionally, the prop could just be a boolean called `label-position-opposite` or something. This would be potentially beneficial for localization reasons with right-to-left languages. However, this would require considerable awareness from the bootstrap library to make this seamless to toggle between different localizations.

**Comment by tmorehouse** [comment]
The position of the "switch" is controlled by Bootstrap V4's  CSS.  It uses a `::before` and `::after` pseudo elements to create the switch (and toggle button) on the label element

You would need to override this CSS to change the position to be at the end of the label rather than the start.  https://github.com/twbs/bootstrap/blob/v4-dev/scss/_custom-forms.scss#L170-L210

Bootstrap v5 will be changing how the customized switches, checkboxes, and radios will be generated (as modifications to the actual input SCSS rather than the label wrapped on the input.

**Comment by tmorehouse** [comment]
An alternative is to do this:

```html
<div class="d-flex">
  <h4 class="mb-0">LIABILITIES</h4>
  <label for="switch_1" class="ml-auto mb-0">Itemize</label>
  <b-form-checkbox id="switch_1" v-model="itemize" switch class="ml-2 mr-n2"></b-form-checkbox>
</div>
```

![image](https://user-images.githubusercontent.com/2781561/74290686-f8f36800-4d08-11ea-8d6b-1030ca5ff82b.png)

See working fiddle here: https://jsfiddle.net/8od9zucb/

**Comment by Soviut** [comment]
We did a similar manual approach. Bummer to hear it's on the label but I guess that makes sense since that's how most checkbox overrides work.

**Comment by tmorehouse** [comment]
Bootstrap v5 will be changing how the "custom" checks and radios are rendered (using custom styles on the input rather than the label).

Closing as this should be available in bootstrap v5 when released (BootstrapVue v3.x)

**Comment by sam-araiza** [comment]
would be nice to have text descriptions on the left and right of the switch like Element UI does it:
https://element.eleme.io/#/en-US/component/switch#switch

it's not always an on/off checkbox.

**Comment by Radulepy** [comment]
> ```
> <label for="switch_1" class="ml-auto mb-0">Itemize</label>
> ```

No, no update on left or right, perhaps they don't care.. 👎

**Comment by miicah** [comment]
> Has this been updated for BS5? I am still not finding a solution for this.

https://getbootstrap.com/docs/5.2/forms/checks-radios/#reverse

.form-check-reverse class
