### ISSUE TITLE
Dropdown menu content types

### ISSUE THREAD

**Issue by davidsneighbour** [bootstrap-vue/bootstrap-vue#4755]
### Is your feature request related to a problem? Please describe...

Bootstrap dropdowns offer subtypes like header or divider. 
https://getbootstrap.com/docs/4.4/components/dropdowns/#menu-content

### Describe the solution you'd like

Add the subtypes, see link above

```
<h6 class="dropdown-header">Dropdown header</h6>
<div class="dropdown-divider"></div>
```

Right now I am implementing it as HTML, but it would be nice if the component would deliver typing (like link, header, divider).

**Comment by Hiws** [comment]
These already exists are [dropdown subcomponents](https://bootstrap-vue.js.org/docs/components/dropdown/#dropdown-supported-sub-components) unless I'm misunderstanding what you want.

**Example**
```html
<b-dd>
  <b-dd-header>Dropdown header</b-dd-header>
  <b-dd-divider></b-dd-divider>
  <b-dd-item>Action</b-dd-item>
  <b-dd-item>Another action</b-dd-item>
</b-dd>
```

**Comment by davidsneighbour** [comment]
Yep. I am sorry. I was fixated at the wrong side of documentation.
