### ISSUE TITLE
Table server-side sorting?

### ISSUE THREAD

**Issue by silver8ack** [bootstrap-vue/bootstrap-vue#476]
Is there currently a way I can do server-side sorting?  

I see that the 'sortBy' and 'sortDesc' properties being set on the table object, but I'm not sure how I can get at those properties on my view.  It would nice if they could emit a property or something that lets me know what I need to sort on.  I have a ton of pages in my app, and sorting on the current page is kinda useless.  I need to sort the entire data set on the server.

Thanks

**Comment by alexsasharegan** [comment]
@silver8ack, PR #460 is a WIP by @tmorehouse that should update the table to emit sort events with exactly that information.

**Comment by silver8ack** [comment]
Awesome... great work.  Thanks!

**Comment by alexsasharegan** [comment]
There is also additional support for async providers in that PR. Should be easier to set your table `items` prop to the result of an ajax call (promise compliant or plain callback).

**Comment by tmorehouse** [comment]
Latest master now has the new features via PR #460

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
