### ISSUE TITLE
[enhancement] List group components don't default to semantic markup

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#477]
It looks like the list group components all default to div's. The BS4 docs canonical example uses the more semantic structure `ul>li`. I see that list group items can also use the link component, but I would think that component should still nest itself inside an `<li>` or whatever the user provides.

Thoughts?

**Comment by tmorehouse** [comment]
Semantics are always good (and great for ARIA).  The only issue in this case is that the wrapper component (`list-group`) and the inner components (`list-group-item`) are decoupled, not knowing which type of tag is being used by each.

The `list-group-item` could be a link, `div`, `li`, or anything really. so it makes it a bit difficult, although if you just want a regular list, then `ul>li` is good, but if you want  other types (links, say), then the structure of the whole composite component needs to change.

Maybe the `list-group-item` could check the tag type of it's parent (`list-group` prop `$parent.tag`) and make an educated guess on what the child component structure should be.

If the parent is an `ol` or `ul`, then the child must be an `li`, and any links mist be placed inside an `li`, Whereas if the outer tag isn't one of those two, then the inner tag can be anything other than an `li` (mix and match even).

**Comment by tmorehouse** [comment]
And as a safety measure, we could add the correct ARIA `role` to the `list-group` and `list-group-item` just in case the component tags aren't `ul` and `li`.

**Comment by tmorehouse** [comment]
I suppose the other option might be to have the `list-group` component scan through its children looking for `list-group-items` to determine what they they are (i.e do they have a `to` or `href`, etc,) and if not, actionable then make the parent a `ul` and then set the child props to `li`).  But that might be too much logic inside a simple component.
