### ISSUE TITLE
Cannot access $bvToast in Nuxt plugin

### ISSUE THREAD

**Issue by Soviut** [bootstrap-vue/bootstrap-vue#4774]
### Describe the bug

I want to display API errors as toast messages. I have to use a Nuxt plugin to work with Axios error interceptors. The plugin has access to the Vue instance `app` from the Nuxt `context`. However, the `app` instance is missing the `$bvToast` injection. So calls like `app.$bvToast.toast('some toast message')` fail.

### Steps to reproduce the bug

1. Create a Nuxt plugin called `/plugins/axios-toast.js`

```javascript
export default function ({ $axios, app }) {
  $axios.onError(error => {
    app.$bvToast.toast(error)
  })
}
```

2. Reference the plugin in `nuxt.config.js`

```javascript
  plugins: [
    '~plugins/axios-toast.js'
  ],
```

3. Intentionally trigger an invalid route

```html
<b-button @click="$axios.$get('badroute')">Do it</b-button>
```

4. Observe the error in the browser

> TypeError: Cannot read property 'toast' of undefined

### Expected behavior

The Vue instance `app` in the Nuxt plugin context should have the `$bvToast` injected.

### Versions

**Libraries:**

- BootstrapVue: 2.4.1
- Bootstrap: 4.4.1
- Nuxt 2.11.0
- Nuxt Axios 5.9.5

**Comment by tmorehouse** [comment]
The injections are added to the Vue.prototype, so as long as the same Vue module is used when creating the app, the injection should appear.

**Comment by Soviut** [comment]
I'm installing using the entire library. No `componentPlugins` or `directivePlugins` specified.

**nuxt.config.js**

```javascript
  modules: [
    ['bootstrap-vue/nuxt', {
      bootstrapCSS: false, // Or `css: false`
      bootstrapVueCSS: false // Or `bvCSS: false`
    }]
  ]
```

**Comment by tmorehouse** [comment]
The `app` key on the nuxt context object is not the `$root` Vue instance, rather it is the options _object_ used to _define_ the app: https://nuxtjs.org/api/context#universal-keys

**Comment by Soviut** [comment]
Interesting, so I should technically be able to "rehydrate" a Vue instance with the following?

```javascript
const instance = new Vue(app)
```

Is the solution to some kind of global error message to add a b-alert in the layout and have it called by ID with `$bvToast.show(id)` ?

**Comment by tmorehouse** [comment]
I wouldn't instantiate a new copy of the instantiated app, as that would double your memory footprint and potentially have adverse affects with your app.

**Comment by Soviut** [comment]
@tmorehouse would it be a good idea to get $bvToast and $bvModal injected into that Nuxt app context when using the Nuxt module? The `@nuxtjs/toast` plugin does this.

**Comment by tmorehouse** [comment]
`$bvToast` needs to have access to the `$root` instance context (as well as the current component's `this` context`).

It can't be done unless there is a way to access the true Vue instance from the plugin/middlware context, as `context.app` is just a bunch of options and not an instance.

Perhaps you could ask on the Nuxt repo how to access the VM instance (be it the page, root app, etc) via nuxt plugins.

**Comment by Soviut** [comment]
That's the plan. I'm going to ask about the viability of the exposing the nuxt/vue instance in the context passed to middleware and plugins.

I do wonder how `@nuxtjs/toasted` accomplishes without access to the $root. Perhaps it just guesses and appends to the body.

In the mean time, the solution I came up with was to build a component with a watcher that listens to a Vuex store. The plugin listens for axios errors and writes them to the store. The watch then processes any notifications it finds and calls `this.$bvToast.toast()` for each one. This may wind up being a more wholistic approach to doing notifications and error messaging anyways.

**Comment by tmorehouse** [comment]
Yeah, the interim solution you propose sounds quite robust for re-usability.

In our case, we need access to the $root instance to emit toast events, and the `this` context to determine if the toast should be destroyed when the parent component gets destroyed (so that we can ensure any transported elements are properly removed from the DOM).

**Comment by ashwinkshenoy** [comment]
I used this:
`$nuxt.$bvToast.toast(error)`
in my Axios interceptor and works fine!

**Comment by VarunBatraIT** [comment]
> $nuxt.$bvToast.toast

How are you accessing $nuxt? This is in context with ~/plugin/axios.js

**Comment by TimofeyBiryukov** [comment]
Tried @ashwinkshenoy solution, but that doesn't seam work. No simple solution to this simple problem so far.

**Comment by TimofeyBiryukov** [comment]
There actually was a limited debugging offered for errors in plugins and my code had an error in it. Due to this it didn't work when I tried. It looks like you can do this via $nuxt available in the plugins:

```
export default function ({app, $axios}) {
  $axios.onError(err => {
    if (err.response.status === 400) {
      $nuxt.$bvToast.toast(
        err.response.data.message,
        {
          title: app.i18n.t('error'),
          variant: 'danger',
          autoHideDelay: 5000
        }
      );
    }
  });
}
```

**Comment by pickTD** [comment]
it works:
```
export default function({ store, app: { $axios } }) {
  $axios.onError(error => {
    store._vm.$bvToast.toast('There is an error', {
      variant: 'danger',
      autoHideDelay: 5000,
    })
  })
}
```

**Comment by yehyaumar** [comment]
This is also working for me, $nuxt.$bvToast.toast(). Seems like $nuxt is already avaliable in plugins. Hope someone elaborates on this.

**Comment by ravgeetdhillon** [comment]
In case someone is using Client-Side Rendering only, this issue can be solved by using `window.$nuxt`

For e.g.

```js
export default function ({ $axios }) {
  $axios.onError(error => {
    window.$nuxt.$bvToast.toast(error)
  })
}
```
