### ISSUE TITLE
Display detailed slot in multiple <td>

### ISSUE THREAD

**Issue by JGrimbert** [bootstrap-vue/bootstrap-vue#4778]
I would like to show a rowDetails under a precise column. 
I did this simplistically change in mixin-tbody-row.js :

### From 
```
var $details = h(BTd, {
          props: {
            colspan: fields.length
          }
        }, [this.normalizeSlot(detailsSlotName, detailsScope)])
```

### To
```
        var $details = !detailsScope.fields.some( e => e.details ) ? h(BTd, {
          props: {
            colspan: fields.length
          }
        }, [this.normalizeSlot(detailsSlotName, detailsScope)]) :
          detailsScope.fields.map( e => h(BTd, {}, e.details ? [this.normalizeSlot( e.details === true ? detailsSlotName : e.details, detailsScope)] : null ) )
```

If a specific "details" slot is found in the fields, use the row-detail slot or specified slot (if need multiple column). Else continue the normal way.

**Comment by tmorehouse** [comment]
Interesting,

But accessibility-wise, this would need additional ARIA markup to associate the individual details cells to the appropriate cell in the previous row.

An alternative would be to render a child table in the details slot (the details slot is passed a copy of the entire fields definition object, as well as the entire row object)

**Comment by JGrimbert** [comment]
I did a change to associate cells and their respective details, using "aria-owns" and "id".

Are they the right attributes ?

Is it worth a PR ?

Thanks

**Comment by tmorehouse** [comment]
`aria-details` is also needed, as well a id's on each rendered cell

Note that this might be a bit confusing for screen reader users, as when clicking on the row to show details, there are multiple details elements

**Comment by tmorehouse** [comment]
Also, there should be a slot naming convention devised for this (ie. `row-details({key})`)

**Comment by JGrimbert** [comment]
Ok, added this. 

Do you mean using something like 
`this.safeId("_col_details_".concat(rowIndex, "_").concat(colIndex, "_") )`

**Comment by tmorehouse** [comment]
That might work., although adding in the field key as part of the ID is probably better
