### ISSUE TITLE
bootstrap-vue/lib/components/nav-item.vue

### ISSUE THREAD

**Issue by w550** [bootstrap-vue/bootstrap-vue#478]
:target="target"

```
<li class="nav-item" data-v-57d4a2a4="" target="_blank">
    <a aria-disabled="false" href="http://www.mi.com/mj-carcorder/" class="nav-link">
          xxxxxx
    </a>
</li>
```

**Comment by tmorehouse** [comment]
This is addressed in the latest master and should be available next release

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
