### ISSUE TITLE
Validation feedback on textarea half-covers tick when scrollbar visible.

### ISSUE THREAD

**Issue by barryspearce** [bootstrap-vue/bootstrap-vue#4781]
When a textarea contains enough content that the scrollbar appears the  validation feedback tick is half covered.

Given a straight forward text input:

`<b-form-group label-for="inputMessage" label="Message">
<b-form-textarea id="inputMessage" type="text" maxLength="4096" v-model.trim="form.message" :state="true" aria-describedby="input-message-live-feedback" rows="6">
</b-form-textarea>
<b-form-invalid-feedback id="input-message-live-feedback">Required. Must contain at least 20 characters.</b-form-invalid-feedback>
</b-form-group>`

add multiple lines until the scrollbar occurs. 

The feedback should take account of the scrollar display. 

**Libraries:**
- BootstrapVue: 2.4.2
- Bootstrap: 4.4.1
- Vue: 2.6.11
![screencapture-localhost-8084-contact-2020-02-17-20_55_50](https://user-images.githubusercontent.com/18211861/74686267-e2e21d80-51c8-11ea-825b-80000b367445.jpg)

**Environment:**
- Device: PC
- OS: Manjaro Linux 4.19.101-1-MANJARO #1 SMP
- Browser: Chromium
- Version: 80.0.3987.87

**Comment by tmorehouse** [comment]
This is a known upstream issue with Bootstrap V4.x CSS/SCSS: https://github.com/twbs/bootstrap/issues/27142

Currently there are no CSS rules to detect when a scrollbar is shown (and scroll bars will vary in width across devices/browsers).

**Comment by tmorehouse** [comment]
Side note: you should avoid using hte `.trim` modifier on the `v-model` on custom components.  In this case, use the `trim` prop on `<b-form-textarea>` https://bootstrap-vue.js.org/docs/components/form-textarea#v-model-modifiers

**Comment by barryspearce** [comment]
Thx for the comments @tmorehouse. I had missed the trim issue - thx! 
Guess Ill just accept the visual issue....there is additional feedback through the border colouring system so at least feedback isn't reliant on the tick itself.

**Comment by tmorehouse** [comment]
Unfortunately it looks like this can't be accomplished with current CSS, not without additional javascript to detect overflow scroll and scroll bar width.

Closing as a can't fix for now... :(
