### ISSUE TITLE
b-form-input: extra \ adding for each escape character for value(if we give v-model prop from object)

### ISSUE THREAD

**Issue by divya-500** [bootstrap-vue/bootstrap-vue#4786]
![Screenshot from 2020-02-18 12-32-59](https://user-images.githubusercontent.com/47383377/74712762-19fa1280-524d-11ea-9692-b4e9329fb4c2.png)

**Comment by tmorehouse** [comment]
`<b-form-input>` supports test strings only as a value.  Passing an object will be JSON stringified by Vue.
