### ISSUE TITLE
Bundle loading tooltip/helper even if tooltip is not used

### ISSUE THREAD

**Issue by mfrascati** [bootstrap-vue/bootstrap-vue#4789]
### Describe the bug

Bundle analyzer shows that tooltip/helper is the build, even if the tooltip directive has not been loaded
![image](https://user-images.githubusercontent.com/2734747/74725861-c54f9b00-523e-11ea-9eb7-0cca6466b6a3.png)

### Steps to reproduce the bug

This is my config (using Nuxt,js)
![image](https://user-images.githubusercontent.com/2734747/74726008-05af1900-523f-11ea-974b-da140f178832.png)

### Expected behavior

tooltip/helper not included in the build

### Versions

**Libraries:**

- BootstrapVue: 2.4.2
- Bootstrap: 4.4.1
- Vue: 2.#.#

**Comment by Hiws** [comment]
That's because the popover is made by extending the tooltip, so it'll be included when you import the popover directive.

https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/popover/helpers/bv-popover.js
