### ISSUE TITLE
Could you please write the document of table component in more details?

### ISSUE THREAD

**Issue by weaming** [bootstrap-vue/bootstrap-vue#479]
And I would like to add class for `<td>` varied on the data. 😃

**Comment by tmorehouse** [comment]
You can apply a custom class on the column (TH and TD) when defining the fields.  Note that this class applies to all cells in the column.

New documentation is forthcoming for table.  There is a pending PR #460

**Comment by weaming** [comment]
@tmorehouse But I want change every cell's (TH or TD) class , according to the value of it.

**Comment by tmorehouse** [comment]
This is currently not "directly" possible at the moment.

The only way to currently get around this would be to use a custom slot for the field, and then include a wrapper div on the content, applying the class to the wrapper DIV (i.e. negative margins or absolute positioning and appl;y a class (or style) to the DIV (say the bootstrap background contextual classes), based on the cell's data (or data from the row).

**Comment by tmorehouse** [comment]
@weaming I have added in support for applying bootstrap contextual variants on a per cell basis, via the new _cellVariants property on an item record object. See PR #460

**Comment by tmorehouse** [comment]
Latest master now has the new features via PR #460
