### ISSUE TITLE
Jest initial configuration 

### ISSUE THREAD

**Issue by JGrimbert** [bootstrap-vue/bootstrap-vue#4792]
Hello, 

Not sure this is the best place to post this issue, 
I try to play with spec.js, but impossible to launch tests suits
It's only the second time I use Jest in a project, and never installed it myself : maybe I miss something important.

So I wonder if any special configuration is needed or documented somewhere.

Thanks 

### Description of the bug

Error when I try to launch Jest : 
`Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Users\jgrimber\contributions\bootstrap-vue\src\components\table\table-row-details.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { mount } from '@vue/test-utils';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../../node_modules/jest-runtime/build/index.js:1059:14)`

### Steps to reproduce the bug

Fresh install 

### Versions

**Libraries:**

Git clone from today (18 February)

**Environment:**

- OS:  Windows 10 
- IDE: PHPStorm

**Comment by jackmu95** [comment]
@JGrimbert So you installed the dependencies by running `yarn install` and then run the tests with `yarn test`?

**Comment by JGrimbert** [comment]
Re, Yes I did yarn install and yarn serve, but something get wrong with my IDE / computer /multiple projects / brain 

This morning it works like a charm.
