### ISSUE TITLE
[BMsgBoxConfirm]: Async operation on confirmed and showing loading state

### ISSUE THREAD

**Issue by albertpratomo** [bootstrap-vue/bootstrap-vue#4796]
### Is your feature request related to a problem? Please describe...

I want to show a `msgBoxConfirm` when a user click a delete button. If he chooses 'Cancel', the message box hides. If he chooses 'OK', a HTTP request is sent to server, and the message box **shouldn't hide** until the HTTP response is received.
 
Currently I'm having problem to:
1. Prevent the hide of the `msgBoxConfirm` if 'OK' is clicked.
2. Showing a loading spinner in the `msgBoxConfirm` indicating the HTTP request made.

### Describe the solution you'd like

1. Being able to prevent hide of the `msgBoxConfirm` until the HTTP request is resolved.
2. Being able to show a loading spinner, preferably inside the 'OK' button.

### Describe alternatives you've considered

In Vue devtools I can see that `<BMsgBox>` emits `ok` event, which might be able to prevent hiding the message box. But I couldn't find a way to listen to this event.

Nevertheless, great package. Thank you in advance!

**Comment by tmorehouse** [comment]
Your best bet is to use the `b-modal` compoent, where you have complete control over the buttons and have easy access to the events.

The message boxes are just quick convenience methods that pre-set certain modal characteristics and uses a Promise that resolves when the `ok`, `cancel` and `hide` events fire.

**Comment by albertpratomo** [comment]
Yeah, true.. Okay then 👍
