### ISSUE TITLE
BCalendar and BFormDatepicker should have date format option

### ISSUE THREAD

**Issue by saulens22** [bootstrap-vue/bootstrap-vue#4797]
### Is your feature request related to a problem? Please describe...

Currently, BCalendar shows formated date variant. It is not possible to customize it

### Describe the solution you'd like

It should be possible to change format (or at least use BCalendar's context event formats - YMD, Date or Formated). 
Some suggestions: 

- format="YYYY-MM-DD" - you pass format string (not very ECMA)
- format="YMD" / "Formatted" - same as Context event
- format="someFunc()" - custom formatter

### Describe alternatives you've considered

Previously I used HTML native date inputs, then I switched to tempus-dominus (using moment.js). Both options allows custom formatting. It would be nice to have it in bootstrap-vue, too.

### Additional context

- In some locales (lt-LT, in my case) long date format is not widely used, therefore harder to read
- Standart ISO YYYY-MM-DD format is shorter and (in some cases) easier to read

**Comment by tmorehouse** [comment]
One thing to keep in mind, is that the formatted date is also an `aria-live` region which speaks the value out to non sighted users, so it must be in a human readable format.

However, we might be able to provide an optional formatter-fn prop to show a different value (and `sr-only` hide the `Intl.DateTimeFormat` human readable format.

The other option, might be to allow passing of optional options to control `Intl.DateTimeFormat` (i.e. short, long, etc).

**Comment by tmorehouse** [comment]
There are options in Intl.DateTimeFormat for controlling the style of each part of the formatted date (we could add a prop that accepts an object with the following properties/values)

`weekday` The representation of the weekday. Possible values are:
- "long" (e.g., Thursday)
- "short" (e.g., Thu)
- "narrow" (e.g., T). Two weekdays may have the same narrow style for some locales (e.g. Tuesday's narrow style is also T).

`year` The representation of the year. Possible values are:
- "numeric" (e.g., 2012)
- "2-digit" (e.g., 12)

`month` The representation of the month. Possible values are:
- "numeric" (e.g., 2)
- "2-digit" (e.g., 02)
- "long" (e.g., March)
- "short" (e.g., Mar)
- "narrow" (e.g., M). Two months may have the same narrow style for some locales (e.g. May's narrow style is also M).

`day` The representation of the day. Possible values are:
- "numeric" (e.g., 1)
- "2-digit" (e.g., 01)

And the following, which is not supported on all browsers:

`dateStyle` The date formatting style to use when calling format(). Possible values include:
- "full"
- "long"
- "medium"
- "short"

This is basically a shortcut the the above settings.

**Comment by clarkestephen** [comment]
@tmorehouse I am using v2.10.0 and dateStyle formatter suddenly stopped working. Kept getting this error (Invalid option : dateStyle)

**Comment by exikyut** [comment]
@clarkestephen: This may be due to a browser upgrade. Try in ~Chrome 83.

Ref: https://github.com/tc39/ecma402/pull/347#issuecomment-691620811

**Comment by yondkoo** [comment]
How do I change MM-DD-YYYY to YYYY-DD-MM?
