### ISSUE TITLE
Infinite loop with v-on:click on b-list-group-item

### ISSUE THREAD

**Issue by jericho-music** [bootstrap-vue/bootstrap-vue#4799]
I am trying to switch from:

```
<ul>
  <li v-for="(item, index) in items" v-bind:key="item.id" v-on:click="clickedOn(index)">
        {{ item.id }}
  </li>
</ul>
```

to

```
<b-list-group flush>
  <b-list-group-item v-for="(item, index) in items" v-on:click="clickedOn(index)" :key="item.id" action>
      {{ item.id }}, {{ index }}
    </b-list-group-item>
</b-list-group>
```
clickedOn(index) mutates the state of the component and that is causing an "infinite update loop in render" issue with the new template code. That does not happen with the old template.

I am confused on why the function is being called during render. Should it not just be registered and called only when an item is clicked?

The versions I am using (subset):

```
    "axios": "^0.19.1",
    "bootstrap": "^4.4.1",
    "bootstrap-vue": "^2.4.2",
    "core-js": "^3.4.4",
    "verovio": "^2.5.0",
    "vue": "^2.6.10",
    "vue-axios": "^2.1.5",
    "vue-router": "^3.1.5",
```

**Comment by tmorehouse** [comment]
Try adding the `button` prop to `<b-list-group-item>`

**Comment by jericho-music** [comment]
That did it. Thanks a lot.

Curious on why the function is called without the button prop?

**Comment by tmorehouse** [comment]
I am not sure about that. the `action` prop just adds the hover styling to the item (similar to the hover rows on table)
