### ISSUE TITLE
bug: table sort error when the number is negative, and the value type I give is `Number`

### ISSUE THREAD

**Issue by weaming** [bootstrap-vue/bootstrap-vue#480]
bug: table sort error when the number is negative, and the value type I give is `Number`

example:

- -0.1
- -0.2
- -0.3
- 0.1
- 0.2
- 0.3

The negative numbers above are sorted incorrectly.

**Comment by tmorehouse** [comment]
I believe The default sort compare routine converts the record/value into a string,. You can provide a custom sort routine to handle different sorting criteria.

**Comment by weaming** [comment]
@tmorehouse I think should try to convert to Number first.

**Comment by tmorehouse** [comment]
Converting to a number first may not always work, especially if you have a field that contains numbers and text as a string.

**Comment by tmorehouse** [comment]
Here is the default sort-compare routine:

```js
const defaultSortCompare = (a, b, sortBy) => {
 return toString(a[sortBy]).localeCompare(toString(b[sortBy]), undefined, {numeric: true});
};
```

It uses the browser's builtin `localeSortCompare(...)` routine, which will, in some browsers, support sorting numerically.

You can provide your own sort function to `b-table`.  It takes the same calling signature as above, where `a` and `b` are the record objects, and `sortBy` is the field key (i.e. name, age, etc) that is being sorted. It should return `-1`, `0`, or `+1`

**Comment by weaming** [comment]
@tmorehouse what's the browser's builtin compare function `localeSortCompare`? I can't found it in chrome console.

**Comment by tmorehouse** [comment]
From my devtools console on chrome:
![image](https://user-images.githubusercontent.com/2781561/27007874-379ae0b0-4e38-11e7-9f77-fc4775af1e05.png)

See details at MDN: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

**Comment by weaming** [comment]
I found the key point, using `window.toString()` will turn type `Number` to object...
![1](https://user-images.githubusercontent.com/10275711/27008622-20e51ae0-4ea9-11e7-82f1-606d6739b7ba.png)

**Comment by tmorehouse** [comment]
Table has a custom "toString" function, which converts objects to a stringified version of it's value., which is not the same as `window.toString` function.

See https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/table.vue#L66-L76 for the implementation, which tests for an object, and if so recursively stringifies the object's key values.

**Comment by weaming** [comment]
But:
```
String(Number(-3)).localeCompare(String(Number(-2)))
1
String(Number(3)).localeCompare(String(Number(2)))
1
```
The results are same.

**Comment by weaming** [comment]
But:
```
String('3').localeCompare('2', undefined, {numeric: true})
1
String('-3').localeCompare('-2', undefined, {numeric: true})
1
```
The results are same.

**Comment by tmorehouse** [comment]
Add in the two extra calling paeameters:

```js
'-3'.localeCompare('-2', undefined, {numeric: true})
```
To enable sorting numbers numerically rather than alphabetically.

**Comment by tmorehouse** [comment]
Are you sure? My chrome reports the second one as being result -1

**Comment by weaming** [comment]
![1](https://user-images.githubusercontent.com/10275711/27016678-1bf139c2-4f55-11e7-8e67-424d8aae882c.png)

**Comment by alexsasharegan** [comment]
I can confirm that localeCompare isn't quite cutting it:

![image](https://user-images.githubusercontent.com/16269252/27019446-6d23d4ca-4eed-11e7-815b-a659f33e465c.png)

Can anyone tell me why we aren't just using a numeric comparator? The only reason for trying to sort numbers in strings is natural sort—which is a pain unto itself. I believe javascript requires a lib to do it.

![image](https://user-images.githubusercontent.com/16269252/27019469-a160621c-4eed-11e7-8951-f7e496c5d2cc.png)

**Comment by tmorehouse** [comment]
We might need to re-jig the sorting to check if a column is just a plain value (i.e. string or number) or an object.  And stort differently.  I think the `toString` was used to handle the possibility of columns being objects.

**Comment by tmorehouse** [comment]
Latest master now has the new features via PR #460

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
