### ISSUE TITLE
 b-pagination config

### ISSUE THREAD

**Issue by AmazingMoon** [bootstrap-vue/bootstrap-vue#4811]
I have a small suggestion, can `page-link` render into non-a tags?
Provide a configurable property, render as `div.page-link`, etc.
This is to solve the SEO problem of `Link anchor text is trivial`.

**Comment by tmorehouse** [comment]
Accessibility wise, it would need to stay as an `<a>` tag for `<b-pagination-nav>`, but for `<b-pagination>` we might be able to switch to `<button>` (it is best to use semantic HTM5 elements where possible to preserve proper roles for a11y), assuming that Bootstrap's SCSS/CSS can handle styling the buttons correctly.  Using `<a>` is Bootstrap v4's recommended structure, but we would be willing to look into switching the `<a>` for button's in `<b-pagination>`

**Comment by tmorehouse** [comment]
`<b-pagination>` renders as an ARIA menuitemradio bar (the page numbers have role `menuitemradio`), so it sounds like the SEO tool you are using doesn't take accessibility into account when looking at the markup.

**Comment by AmazingMoon** [comment]
@tmorehouse  Yes! So I want to avoid this problem.
