### ISSUE TITLE
Form Datepicker in Modal

### ISSUE THREAD

**Issue by Ilyas23** [bootstrap-vue/bootstrap-vue#4814]
The buttons for moving to the next month in the modal window do not work

**Comment by Hiws** [comment]
They appear to be working for me in Chrome.
https://codepen.io/Hiws/pen/JjdEXOZ

Which browser are you using?

**Comment by Ilyas23** [comment]
Firefox

**Comment by Ilyas23** [comment]
In firefox do not work also https://codepen.io/Hiws/pen/JjdEXOZ

**Comment by Hiws** [comment]
Just tested it on Firefox 73 and the buttons appear to be working fine here as well.

Which version are you on?

**Comment by Ilyas23** [comment]
Firefox Developer Edition version is 74.0
Operating System: Mac OS (10.15) | Browser Engine: Gecko (74.0)
In chrome works, but on firefox no

**Comment by Hiws** [comment]
Tested it in Firefox Developer Edition 74.0b7 and working fine.

This might be a MacOS related issue, which i sadly can't test.
@jackmu95

**Comment by Ilyas23** [comment]
Checked on windows and everything works. So it doesn't work on Mac OS

**Comment by jackmu95** [comment]
@Hiws I can confirm that it closes the modal on Firefox and safari on MacOS.
I will look into this soon.

**Comment by tmorehouse** [comment]
This might be due to licking on an inner element within the button (i.e. the SVG).

Perhaps we should switch the `click` event listener to `!click` (capture mode).

**Comment by jackmu95** [comment]
@tmorehouse Yeah, that was my first idea. Will try it soon.

**Comment by tmorehouse** [comment]
I wonder if the `b-form-spinbutton`'s  `+` and `-`  buttons have the same symptom.

**Comment by tmorehouse** [comment]
Also, try checking on the `dev` docs, and PR #4783 deploye preview docs to see if the symptom still persists.
