### ISSUE TITLE
Add a property on b-pagination to be able to change the active bg color or active text color

### ISSUE THREAD

**Issue by ksromero** [bootstrap-vue/bootstrap-vue#4815]
Given a situation. I have cards that has a header background color of dark and a text variant of light.
and I have a pagination, this pagination is the default therefore the active color is blue. It can be very helpful to make the design more consistent especially on colors if there is another  property for b-pagination to change the active color.

It can be applied as
```
<b-pagination active-bg-color="#ffffff" active-text-color="#000000">

</b-pagination>
```

where the :
**active-bg-color** -> is the active background color of pagination
**active-text-color** -> is the text color of pagination

again it can be very helpful just to make the design more consistent and clean.

**Comment by Hiws** [comment]
There are `SCSS` variables you can use to customize your pagination, including the colours. 
https://github.com/twbs/bootstrap/blob/648bceadd84014a8957f2367566c57930e77c2af/scss/_variables.scss#L885-L912

If you want to customize it on a case-by-case basis you can apply CSS to solve this as seen here:
https://stackoverflow.com/a/60235077/8397974

**Comment by ksromero** [comment]
I'm using sugarss

and I followed your answer

```
.customPagination > li > a 
    color: red;

.customPagination > li.active > a,
.customPagination > li > a:hover
    color: white;
    background-color: green!important;
```
and

  <b-pagination
    :total-rows="50"
    :per-page="5"
    class="customPagination mb-0"
  >
  </b-pagination>

seems like it is not working. i cannot reproduce your output on stack

**Comment by Hiws** [comment]
If you're placing your CSS in a scoped style stag (`<style scoped>`) tag. 
You will need to use a [deep selector](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) to target the subcomponents correctly.

```css
.customPagination /deep/ > li > a 
    color: red;

.customPagination /deep/ > li.active > a,
.customPagination /deep/ > li > a:hover
    color: white;
    background-color: green!important;
```

**Comment by ksromero** [comment]
thank you for your response ! it worked now!
