### ISSUE TITLE
Form Datepicker Width

### ISSUE THREAD

**Issue by mikebrandl** [bootstrap-vue/bootstrap-vue#4817]
Hi, 

Is there a way to override the width of this datepicker? 

Currently this means that the Sunday, is pushed onto a new line. 

It's set to 270px on the style of it. 

Thanks

Mike

**Comment by mikebrandl** [comment]
Fixed by importing SCSS From Source.

**Comment by tmorehouse** [comment]
Calendar has a `width` prop... perhaps that did not get added onto the datepicker.

**Comment by tmorehouse** [comment]
Are you referring to the date labels over the calendar grid (i.e. Sun, Mon, Tue, ... etc)
