### ISSUE TITLE
feat: add `useUtilityClasses` prop

### ISSUE THREAD

**Issue by andrewvasilchuk** [bootstrap-vue/bootstrap-vue#4818]
### Is your feature request related to a problem? Please describe...

Many people actually use `bootstrap-vue` without `bootstrap` styles. There are some utility classes already applied to rendered component (`p-0`, `mx-1` etc.). All of them contain `!important` statement, and complicate custom design system implementation.

### Describe the solution you'd like

Maybe, `useUtilityClasses` prop could solve the problem. To save backward compatibility its default value should be `true`. But when developer do not want to apply them, just pass `false`. Is it somehow possible?)

**Comment by Hiws** [comment]
Bootstrap v5 will have a SCSS variable `$enable-important-utilities` which will remove the `!important` part from utilities if set to `false`.

For now (if you're using sccs) you can import each module individually and simply not import the utilities.

```scss
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";

@import "~bootstrap/scss/root";
@import "~bootstrap/scss/reboot";
@import "~bootstrap/scss/type";
@import "~bootstrap/scss/images";
@import "~bootstrap/scss/code";
@import "~bootstrap/scss/grid";
@import "~bootstrap/scss/tables";
@import "~bootstrap/scss/forms";
@import "~bootstrap/scss/buttons";
@import "~bootstrap/scss/transitions";
@import "~bootstrap/scss/dropdown";
@import "~bootstrap/scss/button-group";
@import "~bootstrap/scss/input-group";
@import "~bootstrap/scss/custom-forms";
@import "~bootstrap/scss/nav";
@import "~bootstrap/scss/navbar";
@import "~bootstrap/scss/card";
@import "~bootstrap/scss/breadcrumb";
@import "~bootstrap/scss/pagination";
@import "~bootstrap/scss/badge";
@import "~bootstrap/scss/jumbotron";
@import "~bootstrap/scss/alert";
@import "~bootstrap/scss/progress";
@import "~bootstrap/scss/media";
@import "~bootstrap/scss/list-group";
@import "~bootstrap/scss/close";
@import "~bootstrap/scss/toasts";
@import "~bootstrap/scss/modal";
@import "~bootstrap/scss/tooltip";
@import "~bootstrap/scss/popover";
@import "~bootstrap/scss/carousel";
@import "~bootstrap/scss/spinners";
// @import "~bootstrap/scss/utilities";
@import "~bootstrap/scss/print";
```

I don't know if doing this will break any components, so you'll have to test this yourself.

**Comment by andrewvasilchuk** [comment]
@Hiws, I do not include `bootstrap` styles at all, design I need to implement is completely different and `bootstrap` styles will be just overhead. Moreover I use `tailwindcss` and its utility classes partially coincide with `bootstrap`'s. These classes just add undesirable styles, that i need to override all the time. `bootstrap-vue` components can be used without `bootstrap` styles at all, but for now it's tightly coupled.

**Comment by tmorehouse** [comment]
There is a reason it is called `BootstrapVue` :wink:

**Comment by andrewvasilchuk** [comment]
@tmorehouse, 😅

**Comment by tmorehouse** [comment]
You can always edit a local copy of Bootstrap v4 SCSS and remove the `!important` flags off the class definitions

**Comment by tmorehouse** [comment]
For custom bootstrap vue components, we have removed the user of Bootstrap utility classes (such as `p-2`, `m-4`, etc) in favour of custom SCSS/CSS (with the exception of `p{?}-0` and `m{?}-0` classes)
