### ISSUE TITLE
Popover never show up, keeping opacity to 0

### ISSUE THREAD

**Issue by razerraz** [bootstrap-vue/bootstrap-vue#482]
Read & apply get started ::
main.js
```
import Vue from 'vue';
import BootstrapVue from 'bootstrap-vue';
Vue.use(BootstrapVue);
new Vue({
  el: '#app',
  template: '<App/>',
  components: { App }
});
```

App.vue
```
<template>
  <div>
    <b-popover placement="bottom" content="Heya!">
      <b-btn variant="primary">Bottom</b-btn>
    </b-popover>
  </div>
</template>
<script>
</script>
<style>
</style>
```

The popover never show up until I set opacity to 100 (was 0) in the fade class. Plus the arrow never show up in any case..

I spend 3 hours trying to understand what's going on, no success
Moving to another module, hopping to have something working out of the box : vue-strap seems to, but ok if more details needed on this issue

Chears

PS : just on precision, maybe relevant, get error message on install::
fsevents@1.1.1: The platform "linux" is incompatible with this module
"fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.

**Comment by alexsasharegan** [comment]
Could you provide a little background on the following:
- version of bootstrap-vue
- version of bootstrap (and how you're including it in your app)
- version of Tether (and how you're including it in your app)

The popover component relies heavily on Tether (and obviously bootstrap) so I just want to make sure that everything is setup properly first. Also, opacity only has a valid range of `0-1` ([see the MDN page for reference](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity)). For full opacity you can simply use `1`.

**Comment by razerraz** [comment]
Guess what, it just works right now.
I just made a new vue project from scratch, with only bootstrap-vue : just worked fine
I have added dependencys one after one, import my old code, testing each time. At the end I should have a perfect copy of the first, but only the new one is working...
I keep the old one and will play with "diff" soon and try to understand that mess
Seems to me css related..

Thanks

**Comment by alexsasharegan** [comment]
Glad it's working! If you do find the culprit, please share the problem/solution here! Someone else might run into your same issue down the road.
