### ISSUE TITLE
Display problem with b-nav-item-dropdown

### ISSUE THREAD

**Issue by laurent-brisbois** [bootstrap-vue/bootstrap-vue#4821]
I have a b-card in which I want to customize the title.
I do so by using the <b-card-title> tag so that I can do whatever I want in it.
I'm trying to do something like :

"Title"   ...spaces....      font-awesome-icon ellipsis-v in the top right corner

![image](https://user-images.githubusercontent.com/48165976/75160791-f6d2d580-571a-11ea-904c-6d28f9ea0ccf.png)

You can see that for some unknown reason, it displays my font-awesome-icon in a list.. What am I doing wrong ? I don't see the problem (maybe I've been stuck too long into this and I don't see the problem anymore)

> My template :
```html
      <b-card-group deck>
        <b-card
          v-for="thing in things"
          :key="thing.id"
          class="shadow">
          <b-card-title>
              {{ thing.name }}
              <b-nav-item-dropdown no-caret right>
                <template v-slot:button-content>
                  <font-awesome-icon :icon="['fas', 'ellipsis-v']" class="fa-xs"/>
                </template>
                <b-dropdown-item
                  to="#">
                  Details
                </b-dropdown-item>
              </b-nav-item-dropdown>
          </b-card-title>
          <b-card-sub-title>...</b-card-sub-title>
          <template v-slot:footer>
            ...
          </template>
        </b-card>
      </b-card-group>
```
You can see what it does in my browser :

![image](https://user-images.githubusercontent.com/48165976/75161242-c7709880-571b-11ea-8f76-242154dc09d1.png)

Thanks in advance for your help

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Comment by Hiws** [comment]
You're using a nav dropdown outside of a nav.  I would guess that's the issue.

Try using a [standard dropdown](https://bootstrap-vue.js.org/docs/components/dropdown)

**Comment by laurent-brisbois** [comment]
Okay that solves the problem of the list, thanks.
However, my font-awesome-icon is now displayed inside of something like a b-button.
That's why I initially used a b-nav-item-dropdown.

But I see there is the `variant="link"` which removes the button styling.

Perfect, thanks !
