### ISSUE TITLE
<b-form-datepicker> cannot use <b-calendar> dateInfoFn

### ISSUE THREAD

**Issue by juliusvdijk** [bootstrap-vue/bootstrap-vue#4826]
### Is your feature request related to a problem? Please describe...

I expect the dateInfoFn prop, which is present in <b-calendar>, to also be available in <b-form-datepicker>

### Describe the solution you'd like

Add dateInfoFn to the props of <b-form-datepicker> and pass it through to <b-calendar>

### Describe alternatives you've considered

None.

### Additional context

-

**Comment by tmorehouse** [comment]
Currently, we do not have a means of providing feedback to users of screen readers to signify meaning to the class being applied by `dateInfoFn` to specific dates, which is why `dateInfoFn` was specifically left out of the datepicker component (for now)
