### ISSUE TITLE
state attr is override by form-control:valid

### ISSUE THREAD

**Issue by jeriveromartinez** [bootstrap-vue/bootstrap-vue#4829]
The "valid" property in the input elements overwrites the is-invalid class, if we add the attribute ": state" to a b-form-input, this is not reflected, since the predominant css is ".was-validated. form-control:valid" instead of being "form-control is-invalid".

A simple test is to set the attribute ": state = 'false'" without the attribute "pattern".
<b-form-input v-model="fieldToSave" :state="false"></b-form-input>

### Expected behavior
Invalid field.

### Versions

**Libraries:**

- BootstrapVue: 2.5.0

**Environment:**
- Device: Desktop
- OS: Linux manjaro
- Browser: Chrome
- Version:  80.0.3987.122 (Official Build) (64-bit)

**Comment by tmorehouse** [comment]
Which version of Bootstrap are you using? v4.4.1?

The CSS for validation states is part of Bootstrap v4.x

**Comment by tmorehouse** [comment]
Also, make sure you do not place a space between the colon and the prop name (`: state = 'false'` should be `:state="false"`)

**Comment by jeriveromartinez** [comment]
Bootstrap v4.4.1
bootstrap-vue v2.5.0

<b-form-input :state="false"></b-form-input>
the field is marked as valid

**Comment by jeriveromartinez** [comment]
'<b-form-input v-model="route.domainOrigin" :state="false"></b-form-input>'

**Comment by tmorehouse** [comment]
Do you have the wasvalidated class on a parent component? does your form have novalidate set on it?

**Comment by tmorehouse** [comment]
See https://bootstrap-vue.js.org/docs/components/form#validation

**Comment by jeriveromartinez** [comment]
![Screenshot](https://user-images.githubusercontent.com/15343436/75279607-77540d80-57d1-11ea-933e-7e5fb7cf2701.png)

**Comment by tmorehouse** [comment]
The `validated` prop trigger the native browser validation to kick in.
