### ISSUE TITLE
[enhancement] Add features to pagination

### ISSUE THREAD

**Issue by stefan-angelov** [bootstrap-vue/bootstrap-vue#483]
I use your pagination but it missing some features. Would you consider to add different HTML output, to be more flexible like https://github.com/sant123/vuejs-uib-pagination ?

**Comment by alexsasharegan** [comment]
I believe the goal of Bootstrap-Vue is to adhere closely to the component library defined by Bootstrap 4. Functionality for common use-cases are often supported, but non-standard bootstrap components are not something intended to be part of bootstrap-vue core. 

Extra/enhanced components is an ongoing topic opened up at #417 . I think your suggestion might fit well into that conversation.

**Comment by tmorehouse** [comment]
While we strive to no bloat most components with overwhelming number of options (there are a few exceptions), we have added some enhancements to pagination with PR #528 which should be available in the next release, coming soon.

**Comment by tmorehouse** [comment]
@stefan-angelov check out the fiddle for the new features coming in the next release: https://jsfiddle.net/5gfjkdfy/

And the update docs at https://github.com/bootstrap-vue/bootstrap-vue/blob/master/docs/components/pagination/README.md

Will some of these changes help you?

**Comment by stefan-angelov** [comment]
In fact, these features are exactly what i need. Thank you

**Comment by tmorehouse** [comment]
Excellent.   This will be available soon.  We don't have an exact date yet for the release, but it i not far off into the future)

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
