### ISSUE TITLE
Crash on iOS when resetting b-form-file

### ISSUE THREAD

**Issue by davars** [bootstrap-vue/bootstrap-vue#4837]
### Describe the bug

This [line](https://github.com/bootstrap-vue/bootstrap-vue/blob/a3e37ec0531e2c46b7b2590b6f98a5698802800f/src/components/form-file/form-file.js#L177) triggers this [bug](https://bugs.webkit.org/show_bug.cgi?id=208244) on iOS.  Recommend only changing the input type inside the catch since, based on the comments, it is only needed if resetting the value fails.

### Steps to reproduce the bug

1. On iOS, call reset inside the 'input' handler of a b-form-file component.
2. Observe that the page reloads because WebKit crashed.

### Versions

**Libraries:**

- BootstrapVue: dev

**Environment:**

- Device: iPhone X
- OS: iOS 13
- Browser: Safari
- Version: 13

**Comment by jackmu95** [comment]
@davars I've created a [demo](https://codesandbox.io/s/bootstrapvue-b-form-file-reset-error-mzz7z) on CodeSandbox but could not reproduce it there.
Can you please come up with a minimal demo.
