### ISSUE TITLE
B-form-spinbutton (and components using it) have double detection of click

### ISSUE THREAD

**Issue by naletups** [bootstrap-vue/bootstrap-vue#4838]
### Steps to reproduce the bug

1. Go to, e.g. https://deploy-preview-4783--bootstrap-vue.netlify.com/docs/components/form-spinbutton
2. Click on smartphone browser on spin button
3. In/decrements by two

### Expected behavior

In/decrement by one

### Versions

**Libraries:**

Netlify version of PR 4783

- BootstrapVue: >2.5.0
- Bootstrap: 4.4.*
- Vue: 2.#.#

**Environment:**

- Device: Android 9 smartphone
- Browser: Chrome
- Version: 80.0.3987.119

### Demo link

https://deploy-preview-4783--bootstrap-vue.netlify.com/docs/components/form-spinbutton

Or time picker component

**Comment by tmorehouse** [comment]
This could be because we are listening for both touchstart and mousedown events.  Maybe we will need to add in detection of touchstart events and switch from mousedown if available

**Comment by tmorehouse** [comment]
I'll create a PR shortly that we can test out on on mobile.  Just finishing up a call with work.

**Comment by naletups** [comment]
Thanks for your quick reply. 

Holding one of the buttons for longer time makes it spin continuously (as intended), but there in single increments. It seems it's only the single touch/click. Double touch/click increments by four.

**Comment by tmorehouse** [comment]
I might need to move the check for the "mouse already down" a bit higher

**Comment by tmorehouse** [comment]
OK I found the issue... should hopefully have a solution later today

**Comment by tmorehouse** [comment]
@naletups could you check out https://deploy-preview-4842--bootstrap-vue.netlify.com/docs/components/form-spinbutton/

**Comment by naletups** [comment]
Yepp, works on my smartphone! Good job

**Comment by gabresende** [comment]
Hello
When will it go to production?

**Comment by tmorehouse** [comment]
Hopefully tonight

**Comment by tmorehouse** [comment]
BootstrapVue 2.6.0 has been released
