### ISSUE TITLE
Tooltip initial show: no animation

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#484]
Is there some kind of prop for animation on tooltips that I'm missing? The tooltip flies in from the top-left corner on both my app (see below) and on the docs demo page (just try toggling in and out of the result view). The funny thing is that it only does that initially.

I know everybody is on hold for BS4 & popover.js, but wanted to see if there are any current solutions for getting the tooltip to behave more closely to BS4 (on initial show, the tooltip appears in place rather than being moved into place).

![b-tooltip](https://cloud.githubusercontent.com/assets/16269252/26794891/53d21bfe-49d8-11e7-945e-5eaf2ae376d1.gif)

**Comment by alexsasharegan** [comment]
Looks like Tether uses an absolute position of `0,0` with transforms to place elements. Is there a way to init the tooltip so calculations can set the transform before mouseover?

**Comment by alexsasharegan** [comment]
It looks like Tether doesn't wrap the element until show, and then calculates position. This could be done at the mounted hook (possible perf hit though?).

I also see a lot of underscore props added after vue creation time. Is this because Vue appears to strip references to undercored props? They are still available in `this.$data['_' + prop]` if that's the issue.

**Comment by tmorehouse** [comment]
See also PR #470, which is re-organizing how popover and tooltip inherit base tether stuff.  Maybe this could be mixed in with that?

**Comment by alexsasharegan** [comment]
I'll try and check that out and maybe PR your PR?

**Comment by alexsasharegan** [comment]
Inception PR

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
