### ISSUE TITLE
Form submit using "Enter" key throws Uncaught TypeError 

### ISSUE THREAD

**Issue by praneethpr** [bootstrap-vue/bootstrap-vue#4840]
### Describe the bug

Using the b-form tag, throws an error if Enter key is used to submit the form. It doesn't happen if you click on the submit button. It still submits the form, but the error really got me confused if something was wrong with my code.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/form
2. Fill out the form fields
3. Open the browser console
4. Press Enter key to submit form
5. See error
`onloadwff.js:71 Uncaught TypeError: Cannot read property 'type' of undefined
    at setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)`

### Code

```
<template>
  <div>
    <b-form @submit.prevent="onSubmit"  v-if="show">
      <b-form-group
        id="input-group-1"
        label="Email address:"
        label-for="input-1"
        description="We'll never share your email with anyone else.">
        <b-form-input
          id="input-1"
          v-model="form.email"
          type="email"
          required
          placeholder="Enter email">
       </b-form-input>
      </b-form-group>
      <b-button type="submit" variant="primary">Submit</b-button>
    </b-form>
  </div>
</template>
<script>
  export default {
    data() {
      return {
        form: {
          email: '',
        },
        show: true
      }
    },
    methods: {
      onSubmit() {
        alert(JSON.stringify(this.form))
      }
    }
  }
</script>
```

### Versions

**Libraries:**

- BootstrapVue: 2.5.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: MacBook Pro
- OS: macOS Catalina
- Browser: Chrome
- Version: 79

**Comment by tmorehouse** [comment]
I just copy/pasted your example in the playground and do not see the issue.

What is `'onloadwff.js'`?

Are you hiding the form during submit?

**Comment by praneethpr** [comment]
Hello Troy,

I'm able to reproduce this error on the bootstrap vue sandbox (
https://bootstrap-vue.js.org/docs/components/form/). I haven't edited the
code on the sandbox, It only happens when I submit the form using the Enter
key, it doesn't happen if I click on the Submit button.

After further digging into this bug, I found a similar issue on Vuejs
Github regarding the '*onloadwff.js'* (
https://github.com/vuejs/vue-cli/issues/236). I don't think it is a
bootstrap vue bug. Thanks for the quick response.

Regards,
Praneeth

**Comment by tmorehouse** [comment]
Looks like an issue with the [LastPass](https://www.lastpass.com/) plugin for managing passwords.
