### ISSUE TITLE
Input focus only works once in combination with a dropdown

### ISSUE THREAD

**Issue by RuneHanssens** [bootstrap-vue/bootstrap-vue#4845]
### Describe the bug
I am trying to create a textarea that allows you to insert predefined variables by selecting them from a dropdown. When you select a variable it gets added to the input but it should also refocus on the input field. This works only the first time and after that it looks like the dropdown keeps the focus. 
I already tried working with nextTick but had the same result.

### Expected behavior

Focus the input everytime I insert a variable.

### Versions

**Libraries:**

- BootstrapVue: 2.5.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

### Demo link

Here is a short demo of the issue
https://codepen.io/runehanssens/pen/jOPBgze

**Comment by jackmu95** [comment]
@RuneHanssens This still is a timing related issue.
I tried it with `setTimeout()` and it worked perfectly fine.

**Comment by RuneHanssens** [comment]
Thanks it works!
