### ISSUE TITLE
b-form-datepicker label-no-date-selected problem

### ISSUE THREAD

**Issue by camelG** [bootstrap-vue/bootstrap-vue#4846]
Thank you for the release of datepicker component. It is very helpful.

un...I met one problem,
When setting label-no-date-selected props to null, input height changes

I tried the following code,
```js
<template>
  <div>
    <label for="example-datepicker">Choose a date</label>
    <b-form-datepicker id="example-datepicker" v-model="value" class="mb-2" label-no-date-selected=""></b-form-datepicker>
    <p>Value: '{{ value }}'</p>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        value: ''
      }
    }
  }
</script>
```
If set label-no-date-selected = "　", there is no problem, 
but if set label-no-date-selected = "", the input height changes

There should be other good ways.
But i try to write css like berow.
```css
label #example-datepicker__value_{
  min-height: 36px;
}
```

**Comment by tmorehouse** [comment]
This should be fixed in the next release 2.6.0 coming soon.

**Comment by tmorehouse** [comment]
But you really _should have a label_ when there is no date selected, so that screen reader users will know that there is no value selected (since the date picker is not a native HTML input).

**Comment by camelG** [comment]
> But you really _should have a label_ when there is no date selected, so that screen reader users will know that there is no value selected (since the date picker is not a native HTML input).

Thank you for the advice.
Maybe i am a character hater.

**Comment by tmorehouse** [comment]
BootstrapVue 2.6.0 has been released

**Comment by tmorehouse** [comment]
BootstrapVue 2.6.0 has been released
