### ISSUE TITLE
b-table provider functions using async/await

### ISSUE THREAD

**Issue by mat813** [bootstrap-vue/bootstrap-vue#4849]
As there was no example on how to do this, I wondered if it was possible.

As a matter of fact it is, the "Example: Using callback to return data (asynchronous):" example can be written as an async function like this:

```js
async function myProvider(ctx) {
  try {
    const resp = await axios.get('/some/url?page=' + ctx.currentPage + '&size=' + ctx.perPage);

    return resp.items
  } catch (error) {
    return []
  }
}
```

Maybe you could add it to the doc so that others can find it :-)

**Comment by tmorehouse** [comment]
Unfortunately you can't use async/await directly, but you can return a Promise as mentioned in the docs.

**Comment by mat813** [comment]
Mmmm, well, maybe I can't, but this works.
