### ISSUE TITLE
What is your versioning contract for css classes?

### ISSUE THREAD

**Issue by kirchner-trevor** [bootstrap-vue/bootstrap-vue#4850]
Hi,

I am using a micro-ui framework and some micro-uis are using bootstrap vue. I want to apply a single theme/set of css classes (bootstrap) to all of the micro-uis in my application but I'm not sure how compatible different version of bootstrap vue are with one another. Each of these micro-uis are built and deployed separately, and loaded into the container application dynamically.

Will the classes applied to bootstrap vue components ever change in a minor / patch version update, or is that considered a major breaking change?

Asked another way, if one of my micro-uis uses bootstrap vue version 2.4.x and another one uses 2.5.x, what are the chances that the classes applied to those components change in an incompatible way?

I appreciate any insight / guidance you can provide,

Trevor

**Comment by tmorehouse** [comment]
Our main CSS is Bootstrap V4.4.1 (4.3.x works in most cases too).  The custom CSS we use for some components (and fixes) is minimal and dosn't change too often, except when there is a bug found of we have added new features.

So you should be pretty safe for minor version changes.  Just make sure you use the most recent version of BootstrapVue CSS.
