### ISSUE TITLE
Custom b-calendar Icon

### ISSUE THREAD

**Issue by cnelson-ma** [bootstrap-vue/bootstrap-vue#4851]
### Is your feature request related to a problem? Please describe...

I use FontAwesome in most of my projects, and being able to keep the icon set I use consistent in my project is important to its UX and Design.

### Describe the solution you'd like

I think adding a slot for a custom icon would solve this problem. A prop on the element I think would be less flexable depending on the icon system someone is using.

### Describe alternatives you've considered

Right now the only way I would be able to replace the icon is by hiding it via CSS then adding my own SVG icon in its place via CSS. Which seems hacky to me.

**Comment by tmorehouse** [comment]
See PR https://github.com/bootstrap-vue/bootstrap-vue/pull/4835 and https://github.com/bootstrap-vue/bootstrap-vue/pull/4808

**Comment by cnelson-ma** [comment]
@tmorehouse Sorry if I am being dense, but I took a look at those PR's and there is nothing in them about icon customization options, just date formatting options.

Please let me know if I am missing that somewhere.

**Comment by tmorehouse** [comment]
PR 4808 is the next release, and the second feature listed is custom button content for datepicker and.

PR 4759 is the actual PR that introduces the slot for the datepicker button content.

**Comment by cnelson-ma** [comment]
Wow definitely was being dense. My bad. Thanks.
