### ISSUE TITLE
indented or tree table

### ISSUE THREAD

**Issue by iruizeguilaz** [bootstrap-vue/bootstrap-vue#4853]
I would like to now if there is a way to implement a tree or a indented table.

what I need is to show from a parent a large amount of children data, that comes from diferent levels. This information has different columns to show, that is why I need to draw something similar to a table. 

Example
Nane                   Type     Revision      Description     Owner    CurrentState    Date 
+Product1             Product   A.1       a Wheel          Peter        In_Work         12-02-20
  &nbsp;&nbsp;  +Product 2         Product   A.1       xxxxxxx          xxxxx         In_Work         12-02-20
       &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;   Part 1        Part        A.1       xxxxxxx          xxxxx         In_Work         12-02-20
+Product1             Product   A.1       a Wheel          Peter        In_Work         12-02-20
    &nbsp;&nbsp;+Product 2         Product   A.1       xxxxxxx          xxxxx         In_Work         12-02-20
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    Part 1        Part        A.1       xxxxxxx          xxxxx         In_Work         12-02-20
+Product3            Product   A.1       xxxxxxx            Peter        In_Work         12-02-20
  &nbsp;&nbsp;  +Product 4        Product   A.1       xxxxxxx          xxxxx         In_Work         12-02-20
      &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;    Part 2        Part        A.1       xxxxxxx          xxxxx         In_Work         12-02-20
    &nbsp;&nbsp;+Product 4        Product   A.1       xxxxxxx          xxxxx         In_Work         12-02-20
      &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;    Part 2        Part        A.1       xxxxxxx          xxxxx         In_Work         12-02-20
  &nbsp;&nbsp; +Product 5        Product   A.1       xxxxxxx          xxxxx         In_Work         12-02-20
     &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;     Part 23        Part        A.1       xxxxxxx          xxxxx         In_Work         12-02-20
       &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;   Part 23        Part        A.1       xxxxxxx          xxxxx         In_Work         12-02-20

Do you have any recomendations to solve this? any example?

I coould forgot about the tree and the on demand expand functionality. I could try to make only a indentation in the information (an indentation in the column nane) in order to show that something is in different level in a normal table. But I think that the pagination, the sorting would be a problem in order to manage the indented information

**Comment by tmorehouse** [comment]
Try using nested b-tables, placing the indented table stuff in the details slot and pre-setting `_showDetails` to true.

**Comment by iruizeguilaz** [comment]
I came back to this last friday and following your advice I make it

What I did is a table of tables, if I have the field children I draw a image  button that uses toggleDetails and the details is a recursive calll to the table itself
the subtables hide their headers with css

I will put the example code to show how could it have be done

 (I do not know why I do see my html code in the preview)


`<template>
<div>
          <b-table :items="valores" :fields="campos" responsive="sm" :class="cabecera">
            <template v-slot:head(show_details)="data">
                    <em></em>
            </template>
            <template v-slot:cell(show_details)="row">
               <div v-if="row.item.children">
                   <div class="btn" @click="row.toggleDetails">
                      <div  v-html="estiloExpand(row.detailsShowing)" >
                      </div>
                    </div>
                </div>
                  <div v-else>
                    <div class="btn"><div ><div ><i class='fas fa-align-left fa-2x' style='color:grey;'></i></div></div></div>
                    </div>
                 </template>
                 <template v-slot:row-details="row">
                     <div v-if="row.item.children">
                        <tableIndented :valores="row.item.children" :campos="campos" :cabecera='hiddenHeader'></tableIndented>
                    </div>
                 </template>
             </b-table>
      </div>
</template>`

`<script>
define(["vue"], function(Vue) {
  return Vue.component("tableIndented", {
    template: template,
    props: ['valores', 'campos', 'cabecera'],
    data: function(){
        return {
          hiddenHeader:'hidden_header',
          showHeader:'show_header'
        };
    },   mounted: function mounted(){
        console.log("Entrando en mounted tableIndented");
    } , methods: {
     estiloExpand: function estiloExpand(expanded){
           if (!expanded){
                  return "<div ><i class='fas fa-plus fa-2x' style='color:grey;'></i></div>"
          }else{
                  return "<div><i class='fas fa-minus fa-2x' style='color:grey;'></i> </div>"
                }
           }
     }
    });
  });
</script>`


and I call this from other component

`  <tableIndented :valores="valores" :campos="campos" :cabecera='showHeader'></tableIndented>`

with this example data

`  campos: [
            { key: 'show_details' ,  class:'anchoColumnaTabla'},
            { key: 'type' ,  class:'anchoColumnaTablaMid'},
            { key: 'name' ,  class:'anchoColumnaTablaMid'},
          ],
          valores: [
            { type: 'CatProduct', name: '1', children: [
                                                          {type: 'CatProduct', name: '1.1'},
                                                         {type: 'CatProduct', name: '1.2', children: [
                                                                                                      {type: 'CatProduct', name: '1.2.1'}
                                                                                                      ]
                                                        }]
              },
            { type: 'CatProduct', name: '2', children: [{type: 'CatProduct', name: '2.1'}] },
            { type: 'CatProduct', name: '3', children: [{type: 'CatProduct', name: '3.1'}] }
          ],`

and  this is the result

<a href="https://ibb.co/CWqgzf5"><img src="https://i.ibb.co/wYTVRfN/table-Indented.png" alt="table-Indented" border="0"></a>

**Comment by tmorehouse** [comment]
Note, you should probably use an actual `button` rather than making a div with class `btn`, as currently screen reader and keyboard-only users will bot be able to "click" your `<div class="btn">` elements:

```html
<button class="btn" @click="row.toggleDetails">
  <span  v-html="estiloExpand(row.detailsShowing)"></span>
</button>
```
