### ISSUE TITLE
Where do "scope.emptyText" and "scope.emptyFilteredText" come from

### ISSUE THREAD

**Issue by AnReZa** [bootstrap-vue/bootstrap-vue#4854]
In your documentation about tables, you reference these two variables. However, I can't find any reference, where they are defined. However, they seem to work magically.

Can you tell me, where they are defined and if there are any language-specific variants or settings?

**Comment by zoomla** [comment]
you must Familiar with bootstrap v4，for work.

**Comment by Hiws** [comment]
They provide a way to access the `empty-text` and `empty-filtered-text` properties that are available on `b-table`. 
By default these has a value, but can be changed via the props.
```
<b-table :items="items" empty-text="This text will be shown in the H4" show-empty>
  <template v-slot:empty="scope">
    <h4>{{ scope.emptyText }}</h4>
  </template>
</b-table>
```
