### ISSUE TITLE
Can I change b-dropdown menu html tag?

### ISSUE THREAD

**Issue by umut-firat** [bootstrap-vue/bootstrap-vue#4856]
We can change html toggle tag to custom tag with "toggle-tag" property as stated in documentation. However I couldn't find a way to change dropdown menu html tag.

Temporary solution I found:

In "node-modules/bootstrap-vue/src/components/dropdown/dropdown.js" I changed following code
`
   return h(
      'div', // this was 'ul'
      {
        staticClass: 'dropdown b-dropdown',
        class: this.dropdownClasses,
        attrs: { id: this.safeId() }
      },
      [split, toggle, menu]
    )
`

Then imported in my components as
`import { BDropdown } from "bootstrap-vue/src/components/dropdown/dropdown.js";`

**Comment by tmorehouse** [comment]
Note the root tag of the menu is `ul` for accessibility reasons, as all the dropdown items are wrapped in `li`. This presents the menu items as a list to screen reader users.

**Comment by umut-firat** [comment]
I understand but in bootstrap's documentation dropdown root tag is div. I am developing a web application for special needs that doesn't need screen read and seo etc. Can't I just change root tag of dropdown without source code?

What am I trying to achieve is dropdown like menu in navbar but it needs to be closed on clicking outside of element. I am going to use other components init. Not ul li

https://getbootstrap.com/docs/4.4/components/dropdowns/

**Comment by tmorehouse** [comment]
Bootstrap v5 is actually moving back to use UL/LI semantic markup

**Comment by tmorehouse** [comment]
just wrap your menu content components in  an li
