### ISSUE TITLE
Default route always "active" in navbar

### ISSUE THREAD

**Issue by ccamarat** [bootstrap-vue/bootstrap-vue#486]
Not sure if this is an issue or if I just don't know what I'm doing :)

If I create a navbar with links like so:
```html
        <b-nav is-nav-bar class="mr-auto">
          <b-nav-item to="/">Home</b-nav-item>
          <b-nav-item to="/dummy">Dummy</b-nav-item>
        </b-nav>
```

The first link (Home) is always decorated with the `active` class, even if I'm at /dummy. I'm guessing that's because it's assuming "dummy" is a child route of "/". Anything I can do about this?

**Comment by alexsasharegan** [comment]
You may need to add the `exact` attribute. I believe `/dummy` is a loose match for `/`.

```html
<b-nav is-nav-bar class="mr-auto">
    <b-nav-item to="/" exact>Home</b-nav-item>
    <b-nav-item to="/dummy">Dummy</b-nav-item>
</b-nav>
```

**Comment by ccamarat** [comment]
Yeppers, that did it. Much appreciated!
