### ISSUE TITLE
Checkbox indeterminate state doesn't work with v-model and arrays

### ISSUE THREAD

**Issue by reediculous456** [bootstrap-vue/bootstrap-vue#4861]
### Describe the bug

When using v-model on a checkbox with an array, the indeterminate state is ignored

### Steps to reproduce the bug

1. Create a `<b-form-checkbox>` element
1. Add `v-model="someArray"`
1. Give the checkbox a value (`value="foo"`)
1. Add the indeterminate prop (`:indeterminate="true"`)

### Expected behavior

If I use v-model on a checkbox and pass in an array, then it should still accept the indeterminate prop as normal

### Versions

**Libraries:**

- BootstrapVue: 2.5.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: 2018 Mac Mini
- OS: macOS Catalina
- Browser: Chrome, Firefox, Safari
- Version: 80.0.3987.122 (chrome), 73.0.1 (Firefox), 13.0.4 (Safari)

### Demo link

This CodePen is exported from the Bootstrap-Vue Playground
[See this issue on CodePen](https://codepen.io/reediculous456/pen/oNXwmOG)

**Comment by tmorehouse** [comment]
https://bootstrap-vue.js.org/docs/components/form-checkbox#indeterminate-tri-state-support

> Note: indeterminate styling is not supported in button or switch mode, nor is it supported in `<b-form-checkbox-group>` (multiple checkboxes).

Indeterminiate is only supported on single checkboxes, and a checkbox v-model tied to an array assumes a series of checkboxes (each having an element in the array when selected).  If using a single checkbox, you will need to map the checkbox value to an object that contains an array as it's value.

**Comment by reediculous456** [comment]
> you will need to map the checkbox value to an object that contains an array as it's value.

Can you give me an example of this? I'm not quite sure what you're saying.

If bootstrap-vue doesn't support v-model arrays and the indeterminate prop, can we convert this to a feature request?

**Comment by tmorehouse** [comment]
Chackboxes can be grouped togehter, and when they are grouped together they are tied to the same v-model, and the v-model has to be an array.

When trying to bind the v-model to an array on a single checkbox, it assumes it is part of a group (that is how b-form-checkbox` knows that it should return the results as an array.  One can create a group of checkboxes without using b-form-checkbox-group just by setting the v-model to the same array.

Since you are assigning an array to your checkbox v-model, the indeterminate state is not available (as mentioned in the docs), because it is assuming the checkbox is part of a group.

**Comment by tmorehouse** [comment]
If you only have the one checkbox bound to that v-model, then use a non-array as the v-model, and then use a computed prop to convert it to an array (if needed as an array of one item)

```html
<template>
  <b-form-checkbox v-model="checkbox" value="foo" unchecked-value="">
    Checkbox
  </b-form-checkbox>
</template>

<script>
export default {
  data() {
    return {
      checkbox: ''
    }
  },
  computed: {
    valueAsArray() {
      // returns either an arrau with ['foo'] or an empty array []
      return [this.checkbox].filter(v => !!v)
    }
  }
}
</script>
```

**Comment by reediculous456** [comment]
Thank you for the clarifications, based on your description I am using a group of checkboxes. (From the docs I thought indeterminate was only unavailable if using the `<b-form-checkboxgroup>` component)

Can we convert this issue to a feature request to allow the indeterminate state for `<b-form-checkbox>` with v-model arrays?

My use case is RBAC permission assignment where a check indicates an assigned permissions, an indeterminate show an implicit/related permission (a permission that is required by one of the explicit permissions) and no state is no permission

**Comment by tmorehouse** [comment]
You might need to break out your checkboxes to individual checkboxes, and then use a computed prop to generate the resultant array.

Note that indeterminate is just a visual representation, and doesn't affect the model (a checkbox can either be checked or un-checked when submitted), and is usually used to signify that a set of child checkboxes are not all checked (or all unchecked).  Screen reader users may not even "see" that a checkbox is in the indeterminate state. They will just hear that it is either checked or un-checked.
