### ISSUE TITLE
Docs Input type Number 

### ISSUE THREAD

**Issue by Omarillo** [bootstrap-vue/bootstrap-vue#4862]
Not Work the Max and Min Properties

**Comment by tmorehouse** [comment]
`min` and `max` are passed as attributes to the native browser `<input type="number" ...>`.

These are only used by browser for validation (or 3rd party validation). It does not prevent a user from typing in a number that is out of range.

**Comment by tmorehouse** [comment]
See fiddle https://jsfiddle.net/2d1hx697/
