### ISSUE TITLE
Question: how to change the _rowVariant property in the row-clicked event

### ISSUE THREAD

**Issue by RuneHanssens** [bootstrap-vue/bootstrap-vue#4863]
When I click on a row in the table I want to change the rowVariant to active and set the other rows to the default variant. 

Currently I have this:
```vue
<b-table
   ref="my-table"
   :items="items"
   @row-clicked="rowClick"
/>
```

```typescript
private rowClick(item) {
    this.$refs["my-table"].items.forEach(element => {
      this.$set(element, "_rowVariant", "");
    });
    this.$set(item, "_rowVariant", "active");
}
```

This works but it adds the _rowVariant property to my original items which I don't want because this causes issues when I interact with my back-end and I also don't want to remove this property everytime I have to use the back-end. I was wondering if there is another way of achieving this?

**Comment by tmorehouse** [comment]
Why not just use selectable rows in single mode?  it uses the `active` class to style the selected row.

**Comment by RuneHanssens** [comment]
Good point. Thanks! Works as expected.
