### ISSUE TITLE
Using &shy; in b-table fields labels

### ISSUE THREAD

**Issue by AnReZa** [bootstrap-vue/bootstrap-vue#4864]
The title says it all: If i add the &shy; HTML entity, it renders it literally. How can I make vue interpret it as HTML code?

````js
{
  "key": "activity",
  "sortable": true,
  "label": "Ak&shy;ti&shy;vi&shy;tät"
},
// ...
````

**Comment by RuneHanssens** [comment]
I think you can use a template for this and it looks something like this: 

```vue
<template v-slot:head(activity)="data">
   <div v-html="data.label"></div>
</template>
```
Make sure to check out the documentation about tables https://bootstrap-vue.js.org/docs/components/table

**Comment by AnReZa** [comment]
Thank you! It works!
