### ISSUE TITLE
b-form-file error messages onMouseMove

### ISSUE THREAD

**Issue by Mark-L6n** [bootstrap-vue/bootstrap-vue#487]
Using `b-form-file` as in the [example](https://bootstrap-vue.github.io/docs/components/form-file/):

``` html
<b-form-file v-model="file"></b-form-file>
<br> Selected file: {{file && file.name}}
```

``` js
  data: {
    file: null,
    …
```

Results in console error messages in Chrome 58 (but not Firefox 53) when the mouse is moved over the file-selector area:

```
cperacontent.js:641 Uncaught TypeError: Cannot read property 'startContainer' of null
    at Object._onMouseMove (cperacontent.js:641)
    at onMouseMove (cperacontent.js:636)
```

In fact, you can see these errors on the https://bootstrap-vue.github.io/docs/components/form-file/ page itself, when moving the mouse over the example.

**Comment by alexsasharegan** [comment]
I don't see this error on my chrome browser (version `58.0.3029.110`). I've dug around searching for anything, and it seems like it could be more related to iframe content. Do you receive this error on your project, or just on the jsfiddle example pages?

**Comment by Mark-L6n** [comment]
Strange...it occurred in a small test project of my own, and also the https://bootstrap-vue.github.io/docs/components/form-file/ page (moving the mouse over the component in the `Result` tab under "Example".   Also had Chrome `58.0.3029.110`, on the Mac.
Closed and re-opened Chrome, which was waiting for restart to update, and now it is `59.0.3071.86`, and the problem is not there anymore.  So looks like it was local browser issue. Apologies & thanks for looking into this.

**Comment by alexsasharegan** [comment]
No worries! That was a weird one!

**Comment by Mark-L6n** [comment]
FYI, tracked down what this is related to:  a Chrome plugin, [Perapera Chinese Popup Dictionary](https://chrome.google.com/webstore/detail/perapera-chinese-popup-di/hlcddplhfenagbaipfjhhcjmebhkkaif), which displays Chinese dictionary info when you hover over a Chinese character.  When I restarted Chrome, the plugin defaulted to disabled.  After enabling the plugin again, the strange interaction occurred again and the console messages reappeared when moving the mouse over the `<b-form-file>` component.
Interestingly, this interaction doesn't occur when hovering over other `bootstrap-vue` components in my test app, including `<b-button>`.

**Comment by alexsasharegan** [comment]
Nice detective work!
