### ISSUE TITLE
Add a `trigger` parameter to `$bvModal.hide(id)` to hide modals

### ISSUE THREAD

**Issue by shimikano** [bootstrap-vue/bootstrap-vue#4873]
Would it make sense to add a `trigger` parameter to the `$bvModal.hide(id)` instance method, in analogy to the `$bvModal.hide(trigger)` component method?

My use case: I'd like to intercept the hiding of a modal (no matter what trigger, be it a backdrop click, a button, etc.) using the `hide` event and conditionally prevent the hiding.

Because I'm using `$bvModal.msgBoxConfirm` inside the event handler, I have to preemptively use `event.preventDefault()`, show the confirm msgbox and then manually hide the modal (similarly to the [example in the docs](https://bootstrap-vue.js.org/docs/components/modal#prevent-closing)).

To distinguish this manual hide from other ones, I'd be nice if I could pass a unique trigger instead of the [default `'event'`](https://github.com/bootstrap-vue/bootstrap-vue/blob/280dec807a715ff268f48c5b232dd18bf1d872cc/src/components/modal/modal.js#L757).

Here's my `hide` event handler:
```js
  async onHide(event: BvModalEvent) {
    if (event.trigger == 'event') { // 'event' is the default trigger when using $bvModal.hide
      return; // let the modal be hidden
    }

    event.preventDefault();

    const confirmed = await this.$bvModal.msgBoxConfirm('Are you sure?');

    if (confirmed === true) {
      this.$nextTick(() => {
        this.$bvModal.hide('my-dialog-id'); // here, I'd like to add my unique trigger
      })
    }
  }
```
Or is there any other way to force closing of a modal (i.e., skip the `hide` event handler)?

Thank you for your work!

**Comment by tmorehouse** [comment]
`this.$bvModal.hide(...)` is just a shortcut for emitting the `$root` modal hide event.

But, if you inspect the `bvEvent` object you receive, it contains a reference to the Modal's Vue instance (`bvEvent.vueTarget` https://bootstrap-vue.js.org/docs/components/modal#prevent-closing), which will let you call the modal's `hide()` method (https://bootstrap-vue.js.org/docs/components/modal#using-show-hide-and-toggle-component-methods), which allows you to pass the trigger string of your choice.

```js
  async onHide(bvEvent: BvModalEvent) {
    if (bvEvent.trigger === 'customTrigger') {
      return; // let the modal be hidden
    }
    bvEvent.preventDefault();

    const confirmed = await this.$bvModal.msgBoxConfirm('Are you sure?');

    if (confirmed === true) {
      this.$nextTick(() => {
        bvEvent.vueTarget.hide('customTrigger')
      })
    }
  }
```

**Comment by shimikano** [comment]
Thank you very much for your quick reply. This works for me. Sorry about the noise.

**Comment by tmorehouse** [comment]
No problem.
