### ISSUE TITLE
[Bug] b-tooltip CSS conflicts

### ISSUE THREAD

**Issue by ttpham0111** [bootstrap-vue/bootstrap-vue#488]
b-tooltip has `display: block !important` which interferes with the styling on the same element for `display: none`. On Chrome, `display: block !important`  takes precedence so the tooltip shows up as an invisible box (with `opacity: 0`) that covers elements below it.

**Comment by alexsasharegan** [comment]
Would you be able to include your vue component source code or, even better, a working jsfiddle of the bug?

**Comment by ttpham0111** [comment]
Hi @alexsasharegan, here is a jsfiddle of the bug. I've only added `opacity: 1` to the `.tooltip`. As shown, the tooltip is visible even when it's suppose to be hidden. With `opacity: 0`, it might not be visible but the div still blocks the elements under it.

**Comment by alexsasharegan** [comment]
Did you save the fiddle? It looks like a copy of the doc example. To save, click **Update** and copy the url again.

**Comment by ttpham0111** [comment]
@alexsasharegan just updated: https://jsfiddle.net/gjzvatu3/12/

**Comment by alexsasharegan** [comment]
Looks like opacity is part of the Tether process to show and hide the tooltip. What are you trying to accomplish that requires opacity? There are many other ways to show and hide the tooltip without conflicting with the component CSS.

**Comment by ttpham0111** [comment]
@alexsasharegan The opacity is only there to show that the tooltip is not being set to `display: none` when it's suppose to. I've updated the jsfiddle to show the problem that this causes.

https://jsfiddle.net/gjzvatu3/13/

**Comment by alexsasharegan** [comment]
Thanks for the updated illustration! I'll get another look at it later tonight.

**Comment by alexsasharegan** [comment]
So it looks like there are two issues here. One is a placement issue that I opened at #484 with a PR fix at #485. The other is a css issue (and I'm no CSS expert). The `.tooltip-inner` is still a visible element when the show state is false. Here's the template code:

```vue
<template>
    <div>
        <span ref="trigger"><slot></slot></span>
        <div tabindex="-1" :class="['tooltip','tooltip-' + this.placement]"
             ref="popover" @focus="$emit('focus')" @blur="$emit('blur')"
             :style="{opacity:showState?1:0}"
        >
            <!-- this div needs display:none when not shown to be removed from the document flow -->
            <div class="tooltip-inner">
                <slot name="content"><span v-html="content || title"></span></slot>
            </div>
        </div>
    </div>
</template>
```

I'll try to amend my PR to include this issue.

**Comment by alexsasharegan** [comment]
Switching the display to none seems to have another side effect of "animating" the transform on the tooltip.

**Comment by ttpham0111** [comment]
From my tests, it seems that removing `important!` in `boostrap-vue.css` for the `.tooltip` class fixes this issue. That causes another issue which might be fixed by your PR. The tooltip keeps resetting to the initial location and moving towards it's correct location on trigger.

**Comment by alexsasharegan** [comment]
Some other contributors have put the time into working on the Tether-based components, so I'm not as familiar. It's been the lib's biggest sore spot, and for Bootstrap 4 too. BS4 is moving to popper.js, so we're just trying to make the best of it in the mean time. Hopefully other contributors can weigh in here as well.

**Comment by tmorehouse** [comment]
See PR #450 which is a fix for the problem in #435 

It should be available in the next release.

**Comment by tmorehouse** [comment]
YOu might have to just make sure this CSS is loaded after Bootstraps CSS.

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
