### ISSUE TITLE
b-spinner replaces another element, retaining size

### ISSUE THREAD

**Issue by naletups** [bootstrap-vue/bootstrap-vue#4883]
### Problem and preferred solution

If you have a larger component, say a table with 20 rows, and a longer-lasting selection/filter event happens, then I want to show instead of this component a spinner, either completely replacing or transparently overshadowing the "old" state of the table.

If you use `v-show` or `v-if` on the element to be refreshed/processed to exchange it with a `b-spinner`, the page starts to flicker if the loading is somewhere between 50ms and 500ms (below 50ms a change is barely noticable, above 500ms the change is expected behavior), as the content is temporarily replaced with the spinner that has a different size, especially in vertical direction.

### Describe alternatives you've considered

There are additional vue plugins that provide this functionality, but I guess BootstrapVue could also be able to provide it out-of-thebox. Moreover, these external plugins are difficult to theme correctly.

An option like in the docs, where a spinner appears in the button is only possible if the button text/icon is replaced (size-constrained). This would be the non-preferred fallback.

**Comment by Hiws** [comment]
You could create your own `loading-button` component to implement it yourself.

Here's an example of how it could be made:
https://codepen.io/Hiws/pen/WNvZzqb

Since I'm just hiding the button text, it retains it's width and shouldn't move anywhere.
The spinner is also using `position: absolute`, so it should never change the buttons height or width on it's own.

**Comment by tmorehouse** [comment]
To prevent changes in `size`` in a button when using loading spinners, one can use the `invisible` class to visually hide the spinner, but retain the space it occupies.

**Comment by naletups** [comment]
The button is really only a fallback, as for example the initial page load also consists of three such tables (that are loaded in parallel). For the moment I have there `v-if` b-spinners that are replaced after fetch. But if the page was loaded and something is refreshed, the whole page "flickers" or "jumps". Is there maybe a better solution? I cannot see any nice solution, apart from getting current height/width from the table before refreshing and showing a container with exactly these dimensions, and after load let the new table with potentially different height/width replace the spinner.

**Comment by tmorehouse** [comment]
Also, you may want to take a look at the new `<b-overlay>` component

https://bootstrap-vue.js.org/docs/components/overlay#use-case-examples
