### ISSUE TITLE
b-form-timepicker: decrement does not follow minutes-step

### ISSUE THREAD

**Issue by naletups** [bootstrap-vue/bootstrap-vue#4884]
### Describe the bug

Decrement (click or btnDown) does not respect "minutes-step" when current val is empty or "00"

### Steps to reproduce the bug

```
<template>
  <div>
    <label for="timepicker-placeholder">Time picker</label>
    <b-form-timepicker id="timepicker-placeholder" minutes-step="15"></b-form-timepicker>
  </div>
</template>
```

### Expected behavior

Also respect minutes-step on decrement from empty or "00".

### Versions

**Libraries:**

- BootstrapVue: 2.6.0
- Bootstrap: 4.4.1
- Vue: 2.6

**Environment:**

- Device: PC
- OS: Win
- Browser: Firefox
- Version: 73

**Comment by naletups** [comment]
Minor thing related to docs of b-form-timepicker: the prop should be `no-close-button` instead of the documented `close-button` (inverted meaning)

**Comment by tmorehouse** [comment]
The wrapping on decrement will be fixed in the next release via PR #4885 

> the prop should be no-close-button instead of the documented close-button (inverted meaning)

Which part of the docs?  I couldn't find the mistake you mentioned

**Comment by naletups** [comment]
Great, thanks for the fix. Regarding docs: strange.. maybe I was on a cached page or problem is sitting in front of PC. I cannot find it anymore.

**Comment by tmorehouse** [comment]
`b-form-datepicker` uses `close-button`, as that one is opt-in vs opt-out for `b-form-timepicker`

**Comment by naletups** [comment]
Maybe.

One more minor question: I have `b-form-timepicker` encapsulated in an own component, and emit an own `input` signal with a truncated time string, if the timepicker has a valid value. However, it seems that the timepicker itself is also catching this emitted input signal and reraises it. Is that normal for the component to pick up events emitted by itself?

**Comment by tmorehouse** [comment]
Are you extending the timepicker or just using it as a child component in a wrapper component?

**Comment by tmorehouse** [comment]
the component listens for the inner b-time component's input, and updates the model by emitting it's own input.

If you are altering the time string (say from `01:02:00` to `01:02`, and set the value to that, then the timepicker will re-emit the value as `01:02:00` (as it always includes the seconds in the v-model value)

**Comment by naletups** [comment]
I define it as an own SFC as follows (sorry cannot manage to replicate it in the playground, but in my codebase as soon as the emitted signal is renamed I do not see a triple input event with selectedValue>truncatedValue>selectedValue)
```
<template>
    <b-form-timepicker :id="id"
      :value="value" @input="updateVal($event)" @keydown.native.enter="close">
  </b-form-timepicker>
</template>
<script>
export default {
  methods: {
    updateVal(v) {
      console.log(v)
      this.$emit('input', v.substr(0,5));
    },
    close() {
      this.$refs[`time`+this.id].onCloseButton(); // does not seem to work
    }
  },
  props: {
    state: {},
    id: {
      type: String
    },
    required: {
      type: Boolean,
      default: false
    },
    value: {},
    formid: {
      type: String
    }
  }
}
</script>
```

**Comment by tmorehouse** [comment]
But if the parent component is tied to your component's v-model, then the child picker will see the truncated value as a new value (different than the original including seconds) and update its internals and then re-emit the value because it is different.

Also `onCloseButton()` is an internal handler method that reacts to the built in close button. You cant use it externally.

**Comment by naletups** [comment]
Ah, ok! Got it. Thanks for clarification!

**Comment by tmorehouse** [comment]
BootstrapVue v2.6.1 has just been released with a fix for this issue.
