### ISSUE TITLE
b-modal specify class for modal outer

### ISSUE THREAD

**Issue by fl-frontend** [bootstrap-vue/bootstrap-vue#4886]
# Current Issue

Currently there is a way of specifying `modal-class` but not to specify its outer element `_modal_outer_` (the element with the z-index and position absolute on it)

This is an issue if you'd like to add a specific wrapper class to encapsulate stylings when embedding in a 3rd party page. 

# Possible solution

One solution would be add a prop name called `modal-outer-class`that can be used to specify a class name.

Only two code changes would be needed. One to add the class as a property on b-modal vue component:

https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/modal/modal.js

Above Line number 160: 

```
  modalOuterClass: {
    type: [String, Array, Object],
    default: null
  },
```
Then add it to the component

Line number 379:

```
    modalOuterStyle() {
      // Styles needed for proper stacking of modals
      return {
        class: this.modalOuterClass,
        position: 'absolute',
        zIndex: this.zIndex
      }
    },
```

**Comment by tmorehouse** [comment]
`modalOuterStyle()` returns a css style object.  You can't put a class (or classes) in a style object.

**Comment by tmorehouse** [comment]
You can do encapsulation of styles via the `modal-class` prop.  You just need to target `myclass.modal` (and children) instead of `.myclass .modal` (and children)

**Comment by gfoliver** [comment]
@fl-frontend You can add an id to the `<b-modal id="example">` and the _modal_outer_ id will be replaced to `<div id="example___BV_modal_outer_" style="position: absolute; z-index: 1040;">`. You can reference it in css with `#example___BV_modal_outer_`
