### ISSUE TITLE
<b-alert> dismissible issue with v-html

### ISSUE THREAD

**Issue by bellissi1u** [bootstrap-vue/bootstrap-vue#489]
Hey,

I've got an issue with the <b-alert> component, and with the "dismissible" property. 
Actually, it works with a text message in, but not with a html message, using v-html from vue2.
The cross doesn't appear. I mind if the problem is that this cross is interpreted in html, and so not showing...
Do you have any solution ? I need for exemple to use <br> in a error message. Maybe there's another way I don't know ?

Thanks a lot

**Comment by alexsasharegan** [comment]
Would you be able to include your component source code for us? Preferably set up in a js fiddle (you can hack away at [this one] (https://jsfiddle.net/pi0/src29p6L/?utm_source=website&utm_medium=embed&utm_campaign=src29p6L), hit update and paste the URL back here).

**Comment by bellissi1u** [comment]
The js fiddle isn't working with my code..
But i got this : 

<b-alert v-html="error" dismissible show variant="danger"></b-alert>

and in the data : 
error: 'My problem : <br> Where is the cross ??'

Just try it and you'll see

**Comment by alexsasharegan** [comment]
Without source code, a fiddle, or even a screen shot, I'm kind of guess at what you're seeing. All I can really say is that I can use html inside the alert component, and with the `dismissible` attribute, the close button X is present. Here's some template code from a project of mine:

```vue
<b-alert v-show="alert.shouldShow"
         :state="alert.state"
         dismissible
         :show="alert.dismissCountDown"
         @dismissed="onAlertDismissed">
    <strong v-if="alert.state === 'success'">Success:</strong>
    <strong v-if="alert.state === 'danger'">Error:</strong>
    {{ alert.message }}
</b-alert>
```
![image](https://user-images.githubusercontent.com/16269252/26881393-224eeda8-4b4c-11e7-9ba6-3285e0c28ff7.png)

**Comment by alexsasharegan** [comment]
I just noticed your issue title (it's before-coffee early here still). `v-html` is not how you want to insert content with most of the bootstrap-vue components. The components largely use `slots` ([have a look at the vue docs on slots](https://vuejs.org/v2/guide/components.html#Content-Distribution-with-Slots)). Slots allow you to add template content inside the component tag, and the component will distribute your content in its _slot_. There are default and named slots. The docs explain it better than I can though.

**Comment by bellissi1u** [comment]
I finally got the js fiddle to work, [here](https://jsfiddle.net/src29p6L/29/)
Ok I'm gonna watch that and see what I can do

**Comment by bellissi1u** [comment]
Ok I finally got a simple solution : put a span with the v-html property in the b-alert. This way the cross appears and the text is html formatted.

Thanks for help !

**Comment by alexsasharegan** [comment]
Yeah, that's a good solution for dynamic html content. Here are the two ways to do it:
https://jsfiddle.net/src29p6L/30/

**Comment by alexsasharegan** [comment]
Glad you got it working! 🎉 🎉 🎉
