### ISSUE TITLE
Error in documentation.

### ISSUE THREAD

**Issue by chelentos** [bootstrap-vue/bootstrap-vue#4892]
Hello, here in [docs](https://bootstrap-vue.js.org/docs/components/modal/#custom-rendering-with-slots) it is said, that slots for "Ok" and "Cancel" buttons are `modal-ok` and `modal-cancel`, respectively. But I've managed to change buttons' labels only with slots `ok-title` and `cancel-title`.

Please, change this information in the docs.

**Comment by tmorehouse** [comment]
You must be using an older version of the library.

As the current code uses `modal-ok` and `modal-cancel`:

https://github.com/bootstrap-vue/bootstrap-vue/blob/bffb6a2df439e719f5f2476161ffade4761f98ac/src/components/modal/modal.js#L899-L953

```js
L919: this.normalizeSlot('modal-cancel')
```

```js
L937: this.normalizeSlot('modal-ok')
```

**Comment by chelentos** [comment]
I have `"bootstrap-vue": "^2.0.0-rc.27"` in my `package.json`.

**Comment by tmorehouse** [comment]
You  will probably want to upgrade to the latest v2.6.1 (`"^2.6.1"`)

But note there are some breaking changes from the `rc##` releases compare to 2.x.x stable.  See https://bootstrap-vue.js.org/docs/misc/changelog#v200
