### ISSUE TITLE
Datepicker should auto-navigate to max date (month) if set, not to current date (month)

### ISSUE THREAD

**Issue by japalvia-fi** [bootstrap-vue/bootstrap-vue#4899]
### Describe the bug

If max date is set, datepicker should "auto-navigate" to that month. Now (2020-03-06) it opens current month even if the last enabled date (and set max date) is in the past months (e.g. 2020-02-20). 

### Steps to reproduce the bug

1. set :date-disabled-fn to return days from previous months
2. set max="2020-02-20"
3. Open the datepicker
4. See error: current month (2020-03) is opened even though there isn't anything to select and it's past set max-date

### Expected behavior

If set, datepicker should auto-navigate to max date, not to current date if it's out-of-range.

### Versions

**Libraries:**

- BootstrapVue: 2.6.0
- Bootstrap: 4.4.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Windows 10 Pro
- Browser: Chrome
- Version: 80.0.3987.132 (Official Build) (64-bit)

**Comment by tmorehouse** [comment]
Yeah, the initial-date prop could be used to show the appropriate year/month (but not have a value selected).

And when setting the "today" date, we could clamp the value to between min and max value.
