### ISSUE TITLE
Missing Components

### ISSUE THREAD

**Issue by OmgImAlexis** [bootstrap-vue/bootstrap-vue#49]
Are there plans to implement all of the Bootstrap v4 components? The main one I'm interested in is the [dropdown for the navbar](https://v4-alpha.getbootstrap.com/components/navbar/#supported-content) as it seems the `<b-dropdown>` isn't the same thing.

**Comment by pi0** [comment]
@OmgImAlexis New release is coming soon ;)

**Comment by pi0** [comment]
Changes planned in upcoming #50 (0.5.0) release.
