### ISSUE TITLE
breadcrumb error on Vue/ SSR 

### ISSUE THREAD

**Issue by hvalcourtSerdy** [bootstrap-vue/bootstrap-vue#490]
Hi,

I use Vue, with Server Side Rendering and Bootstrap-vue 0.14.0.

When I reproduce the exemple here on your website https://bootstrap-vue.github.io/docs/components/breadcrumb , I get a warning from SSR with b-breadcrumb :

```[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.```

Maybe the problem is this one, the code look like this :

```
<section id="breadcrumb" class="row no-gutters align-items-center">
    <div class="container extra-padding">
        <div class="row">
            <div class="col">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a **active-class="active"** href="#">Admin</a></li>
                    <li class="breadcrumb-item"><a **active-class="active"** href="#">Manage</a></li>
                    <li class="breadcrumb-item active"><span>Library</span></li>
                </ol>
            </div>
        </div>
    </div>
</section>
```

Like you see, the attribute on <a> is **active-class="active"**.

The  **active-class="active"** is not a valid attribute, maybe the problem is there ?
`Error: Attribute active-class not allowed on element a at this point.`

Is your code is compatible with SSR ? 

Thanks for the help,

Hugo

**Comment by jmharveys** [comment]
I've got the same problem @hvalcourtSerdy !

**Comment by tmorehouse** [comment]
`active-class="active"` is used by Vue-router `<router-link>`

Are you using vue router?

**Comment by tmorehouse** [comment]
Does the issue still appr in the current release https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/v0.16.1 ? Some changes have occurred with the b-link component since 0.14.0

**Comment by tmorehouse** [comment]
@hvalcourtSerdy @jmharveys 

The `active-class` attribute should only appear on `b-link` when vue-router is installed (and you are using the `to` prop). Can you confirm if you are using vue-router?

**Comment by hvalcourtSerdy** [comment]
Yes we are using vue-router, and we are on "bootstrap-vue": "^0.14.0". I will make a test on 0.16.1, and edit this post with the result

**Comment by tmorehouse** [comment]
OK. we have to check with the new release that is coming out.

**Comment by alexsasharegan** [comment]
@hvalcourtSerdy & @jmharveys, what is odd is that the router-link component doesn't generate an anchor tag with that attribute in it on the client-side. I'm haven't done SSR myself, but is there any way this could be an upstream issue of some kind? Can you test out another component like a plain `<b-link>` to see if you get the same error?

**Comment by alexsasharegan** [comment]
You know what, I think I fixed this. The problem appears to be around proxying the correct props from breadcrumb to the link component. PR #520 addresses this and appears to fix it.

**Comment by hvalcourtSerdy** [comment]
Ok, I will wait for merge, and test if the issue is fixed. Thanks!

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
