### ISSUE TITLE
Own class in <b-nav-item> children

### ISSUE THREAD

**Issue by sowinski** [bootstrap-vue/bootstrap-vue#4901]
Hi,

```
<b-nav-item
  link-classes="btn btn-primary btn-block"
>
  My Item
</b-nav-item>
```
link-classes is only appending the classes to the child element. In my case I would like to apply only my provided classes. How can I do this?

Thank you

**Comment by tmorehouse** [comment]
The inner `nav-link` will always have the `nav-link` class, as that is what bootstrap uses to style the inner link.

If you do not want that inner class, you can create your own nav-item quite easily:

```html
<li class="nav-item">
  <b-link :to="some/path" class="btn btn-primary btn-block" role="button">My Item</blink>
</li>
```
