### ISSUE TITLE
How to change all default component name to PascalCase ?

### ISSUE THREAD

**Issue by Jamaludin-Sanur** [bootstrap-vue/bootstrap-vue#4903]
Hi, thank you guys for the awesome BootstrapVue Library.

I have a question,
It is possible to change all default components name to PascalCase without change the source code and have different custom build?

**Comment by tmorehouse** [comment]
All components are registered n PascalCase (i.e. BAlert, BButton, etc).  you can use either PascalCase or kebab-case in your templates.

Note if you are using in broswer templates, you can't use PascalCase as the browser parser will lowercase the tags.
