### ISSUE TITLE
Setting a select option from data() return form

### ISSUE THREAD

**Issue by pacmac** [bootstrap-vue/bootstrap-vue#4911]
I have a form that has a lot of elements, I can set the value of other fields, but can't figure out how to select a select option using returned data:

    <form data-v-469af010="" id="demo" class="container b-form">
        <div data-v-469af010="" class="form-group">
        	<label data-v-469af010="" for="">Combobox</label>
        	<select data-v-469af010="" type="select" name="mycombo" class="form-control">
        		<option data-v-469af010="" disabled="disabled" value="">Please select one</option>
        		<option data-v-469af010="" value="2">User</option>
        		<option data-v-469af010="" value="3">Admin</option>
        	</select>
        </div>
    
        <div data-v-469af010="" class="form-group">
        	<label data-v-469af010="" for="mytext">Text</label>
        	<input data-v-469af010="" type="text" id="mytext" name="mytext" class="form-control">
        </div>
    </form>

    <script>
      data() {
        return {
          form: {
            mytext: 'Hello World',  
            mycombo: {options:{selected:2}},
          }
        }
      }
    </script>

I have also tried:

    mycombo: 'User'
    mycombo: '2'
    mycombo: {selected:'2'}

But nothings appears to work, have looked at the docs page and can't find any example of setting form data for a select.

**Comment by tmorehouse** [comment]
Could you how your Vue template markup, not the rendered HTML markup?  As we cannot tel how you are binding values and v-models from the above sample.

**Comment by pacmac** [comment]
This is simplified, I am using pug to generate my templates as I have a LOT of existing code defined in pug / jade that I need to reuse.

This is just the SELECT, I am using both v-model in the SELECT (using the field name) and a key in the OPTIONS which is also the OPTION value, I believe that this approach is correct ?

```
<template>
  <div class="container">
    <br>
    <form id="demo">
        <div class="form-group">
        	<select v-model="form.mycombo" name="mycombo" class="form-control">
        		<option key="" disabled="disabled" value="">Please select one</option>
        		<option key="2" value="2">User</option>
        		<option key="3" value="3">Admin</option>
        	</select>
        </div>
    </form>
  </div>
</template>
```

**Comment by tmorehouse** [comment]
Note that using `value-"#"` it will interpret the value as a string. You may need to switch to `::value="#"` to unsure Vue sees the value as a number

**Comment by pacmac** [comment]
Thanks, but what is the correct method to select a OPTION in the data() function ??

**Comment by pacmac** [comment]
OK, just figured it out, the problem is with the use of a numeric values, if I set my values to text then I can simply return the OPTION.value from the data() function and the item is selected.

Thanks :-
