### ISSUE TITLE
component not render

### ISSUE THREAD

**Issue by wwshunan** [bootstrap-vue/bootstrap-vue#4916]
### Describe the bug
I installed bootstrap-vue using command vue add bootstrap-vue. b-alert is not rendered in vue cli 3, displaying a “<! ---->”

**Comment by tmorehouse** [comment]
Note, `<b-alert>` will not show unless the `show` prop is true:

```html
<b-alert show>
  Allert text
</b-alert>
```

Or

```html
<b-alert :show="true">
  Allert text
</b-alert>
```

See the docs at: https://bootstrap-vue.js.org/docs/components/alert#visible-state
