### ISSUE TITLE
Filter prop and empty slot on b-card-group ?

### ISSUE THREAD

**Issue by laurent-brisbois** [bootstrap-vue/bootstrap-vue#4919]
I know there are other ways to do that but I wondered whether it's a good idea or not to add customization elements such as :

`filter` prop
`filter-ignored-fields` to work with the filter
`filter-included-fields` to work with the filter

Note that it would look into `b-card` elements of the `b-card-group`. For instance, it could be possible to filter on the `title` of the `b-card`s. It would be nicely integrated !

Also, having a slot `empty` for the `b-card-group` could be cool too. It would look if there are visible `b-card` in it or not.

What do you think about that ?

**Comment by tmorehouse** [comment]
b-card-group doesn't maintain state about it's child descendants.  Nor does it provide an "items" property to reder a list of cards from.... as there are almost infinate ways that cards could be rendered by the user, and infinite properties that users would want in their cards...

This is why it is up to the user to decide how to render the card in a card group... either by direct placement of card components or via a v-for loop iterating over an array or object of the users choice.

**Comment by laurent-brisbois** [comment]
Yes in my project I populate the `b-card-group` with a `v-for` loop. Indeed if it doesn't know anything about its children it won't be possible to at least be able to filter among its default props/slots such as `title` and so on.
Okay  thanks for the information.
I'll implement custom filter functions with computed ones then.
