### ISSUE TITLE
Table column max width

### ISSUE THREAD

**Issue by Zyles** [bootstrap-vue/bootstrap-vue#492]
How do you specify a max width for a specific table column?

**Comment by tmorehouse** [comment]
You can specify a "class" on your field definition, and have that class define the width:

```js
fields: {
  foo: {
    'class': 'my-class',
    sortable: true
  },
  bar: {
    sortable: true
  },
}
```

and in your CSS:
```css
.my-class { max-width: 100px; }
```

You can also pass an array of class names to the `class` property.

**Comment by Zyles** [comment]
Thank you.

**Comment by CrixuAMG** [comment]
It would be much better if you could provide a width and set that for the fields.

**Comment by tmorehouse** [comment]
For specifying a width,  then one would need to determine which units to use (%, px, rem, em, vw, etc), which would also impede responsive settings, so classes are the easiest way for now.  It might be something we revisit in the future.

You could also use custom slots and put the CSS on a wrapper div around the data to force a specific width of a column.

**Comment by tmorehouse** [comment]
@Zyles  I have added a new quick PR that allows you to add CSS styles (in javascript object format) to the table TH cells on a per field basis.

**Comment by damaimrs** [comment]
i've added a class inside of my <th> properties, but i cant set the width of it by css :(

this is my source code:

fields: {
        'no': {
          class: 'no'
        },
        'airwaybill_number': {
          class: 'awb_number',
          sortable: true
        },
        'message': {
          class: 'message',
          sortable: true
        }

.no {
  width : 100px !important;
}

**Comment by jrudnik** [comment]
@damaimrs this approach was not working for me as well. However, now there is a neet solution available:
`fields:{
'no':{thStyle: {width: '100px !important'}}
}`
Please refer to https://github.com/bootstrap-vue/bootstrap-vue/pull/531

**Comment by sevsev9** [comment]
I know this is old but it might still help someone.

This approach won't work in a scoped style because the data tag inside the HTML tag won't be written by the Vue framework due to no association.

For this to work you'd have to unscope the style so the style class takes effect on not only specific HTML tags.

So instead of:
```
<style scoped>
    .foo {
          overflow: hidden;
    }
    ...
</style>
```

remove the scoped from the style tag:
```
<style>
    .foo {
          overflow: hidden;
    }
    ...
</style>
```

Or just simply use the solution specified in [#531](https://github.com/bootstrap-vue/bootstrap-vue/pull/531).

**Comment by tmorehouse** [comment]
@sevsev9 You can use scoped styles, but you need to use the [Vue loader deep selector](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements):

```html
<style scoped>
    /deep/ .foo {
          overflow: hidden;
    }
    ...
</style>
```

**Comment by sevsev9** [comment]
Oh, I didn't know this existed thanks!

**Comment by ad99526** [comment]
How do you specify max-width for a table
