### ISSUE TITLE
Introduce `loading` prop for buttons

### ISSUE THREAD

**Issue by gmw-web** [bootstrap-vue/bootstrap-vue#4921]
### Is your feature request related to a problem? Please describe...

If a user clicks a button that triggers a long async action, there is no easy way to provide feedback.

### Describe the solution you'd like

I would like to set a loading state on a button, that can be enabled/disabled by setting a 'loading' prop. Enabling the loading prop will automatically show a loading indicator on the button (prepend before the label?) and disable the button from further user action.

### Describe alternatives you've considered

We can use the `spinner` in combination with a button and some additional setting to get the same result, but this feels verbose.

### Additional context
Perhaps other actionable elements can also receive the `loading` prop.

**Comment by Hiws** [comment]
Might be similar to what i talked about here https://github.com/bootstrap-vue/bootstrap-vue/issues/4883#issuecomment-595266438

Could potentially have a `loading` slot for the button to decide the content for when it's in a loading/busy state.

**Comment by tmorehouse** [comment]
One could simple v-if a b-spinner in a `b-button, and then the user would have complete control of where the loading spinner is placed, what loading spinner (or feedback) they want, etc.

```html
<b-button :disabled="busy">
  <b-spinner v-if="busy"></b-spinner>
  <span v-if="busy">Loading...</span>
  <span v-if="!busy">Do something</span>
</b-button>
```

**Comment by gmw-web** [comment]
I like the `<b-overlay>` component that's on it's way. Nice and flexible. The only downside of the proposed (existing) approaches is that one has to set the `busy` property on multiple elements (it's not terrible, but still...).

Thanks for the quick reply. Nice work overall! We look forward to v2.7.0 :)

**Comment by tmorehouse** [comment]
The reason that you need to set the busy (or whatever data prop or computed prop you are using) on the inner components is to remove them from the document tab sequence to prevent someone from tabbing to them with the keyboard.  For Mouse users only, you don't need to do this, but if you have a pesron that likes navigating with the <kbd>Tab</kbd> key then it  would still be possible for them to reach the obscured content (if that content was not disabled).

**Comment by tmorehouse** [comment]
BootstrapVue 2.7.0 has been released, with the new `<b-overlay>` component.
