### ISSUE TITLE
vue-cli3通过v-for循环绑定src加载本地的图片失败，我按照官网给的配置了，还是不行，这个是bug吗？？？

### ISSUE THREAD

**Issue by tianrenlin** [bootstrap-vue/bootstrap-vue#4924]
[我参照了你们给的配置写法](https://bootstrap-vue.js.org/docs/reference/images/)，下面是我想问的。
```
<div v-for="item in data" :key="item.id">
   <b-img-lazy width="30" height="30" alt="ico" :src="item.logo"></b-img-lazy>
</div>
```
如本地图片：src/assets/img/logo.png
本地编写的数据：
```
data : [{
    "id": "001",
    "title": "person",
    "logo":"assets/img/logo.png"
}]
```
如果按以上循环绑定本地的图片就会显示失败，如果图片为网络地址就会成功，如：
```"logo":"https://picsum.photos/600/400/?image=94"```
我开始以为是我本地数据的地址写错了，但无论我怎么改还是没有显示出来。
难道不能循环绑定src吗？我看你们给的[示例](https://bootstrap-vue.js.org/docs/components/image/#comp-ref-b-img)是绑定网络上的地址：
```
<b-img-lazy v-bind="mainProps" :src="getImageUrl(80)" alt="Image 1"></b-img-lazy>
getImageUrl(imageId) {
        const { width, height } = this.mainProps
        return `https://picsum.photos/${width}/${height}/?image=${imageId}`
}
```
我也使用过这种写法来绑定本地的数据，但仍旧不行。
希望给个回复吧。先谢谢了

**Comment by tianrenlin** [comment]
好吧，我的错。
把资源放在public里面

**Comment by tmorehouse** [comment]
加载项目相关URL时，您需要确保已使用 `vue-loader` 设置了 `transformAssetUrls`，并且您的路径是项目相关URL。

(When loading project relative URLs, you will need to make sure you have `transformAssetUrls` set up with `vue-loader`, and that your path is a project relative URL.)

https://bootstrap-vue.js.org/docs/reference/images

另一种方法是使用使用 `require`：

(An alternative would be to use to use `require`)

```html
<div v-for="item in data" :key="item.id">
   <b-img-lazy width="30" height="30" alt="ico" :src="require(item.logo)"></b-img-lazy>
</div>
```

**Comment by tmorehouse** [comment]
> 好吧，我的错。
把资源放在public里面

该`public`文件夹也是另一种选择
