### ISSUE TITLE
(Non native) Input event on debounced form-input is not debounced

### ISSUE THREAD

**Issue by gmw-web** [bootstrap-vue/bootstrap-vue#4925]
### Describe the bug

The `form-input` has debounce support ([link](https://bootstrap-vue.js.org/docs/components/form-input/#debounce-support)) on the `v-model`. This works brilliantly.

However, if I try try to trigger an event on the (debounced) input via `@input="handleInput"`, this event is not triggered after the debounce period but immediately. 

### Steps to reproduce the bug

Try the following fiddle:
https://jsfiddle.net/6wo7e8z4/2/

### Expected behavior

Since `v-model` is syntactic sugar for combining a `value` prop and an `input` event, I would expect the input to be debounced.
I would expect the `native` event modifier to result in a regular event (that is not debounced).

### Versions

**Libraries:**
- BootstrapVue: 2.6.1
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**
- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version: 80

### Demo link

https://jsfiddle.net/6wo7e8z4/2/

### Additional context
none

**Comment by jackmu95** [comment]
The `input` event is emitted on user update. You have to use the `update` event which is triggered to update the `v-model` to get your expected result.

**Comment by gmw-web** [comment]
Thanks @jackmu95 , missed that completely.

**Comment by dosstx** [comment]
> The `input` event is emitted on user update. You have to use the `update` event which is triggered to update the `v-model` to get your expected result.

Thanks for this! Fixed my debounce issue,too. I was originally relying on `input` instead of `update`.
