### ISSUE TITLE
<b-form-timepicker>: Bottom of dropdown is too short for it's content

### ISSUE THREAD

**Issue by SgtMurv** [bootstrap-vue/bootstrap-vue#4926]
### Description of bug
The dropdown produced from the <b-form-timepicker> does not display as outlined in the docs. The bottom of the dropdown cuts off some of the content of the dropdown when the close button is not displayed. This is not the case when the close button is displayed but the close button overlays the time picker elements.

#### With a close button
1. Insert a <b-form-timepicker> into a vue component
2. Add any v-model object and the locale to 'en'
3. Click on the time picker
4. Behold the error
#### Without a close button
1. Insert a <b-form-timepicker> into a vue component
2. Add the no-close-button prop to the <b-form-timepicker> component
3. Add any v-model object and the locale to 'en'
4. Click on the time picker
5. Behold the error

### Expected behavior

I expected the dropdown menu to display as outlined in the documentation [here](https://bootstrap-vue.js.org/docs/components/form-timepicker). I expected the close button not to overlay the contents of the dropdown.

### Versions

**Libraries:**

- BootstrapVue: 2.6.1
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Firefox
- Version: 74.0b9

**Comment by tmorehouse** [comment]
Are you including BootstrapVue's custom CSS after Bootstrap's CSS?

**Comment by SgtMurv** [comment]
Ahh I was not including bootstrap's css only Bootstrap Vue's css. Thanks for the help, my issue has been fixed 👍  ! Have a good day 😄
