### ISSUE TITLE
bootstrap-vue.esm.js:969 Uncaught SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by AshokRaj29** [bootstrap-vue/bootstrap-vue#4928]
bootstrap-vue.esm.js:969 Uncaught SyntaxError: Unexpected token '.'
    at Object../node_modules/bootstrap-vue/dist/bootstrap-vue.esm.js (app.js:1429)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (main.js?1c90:1)
    at Object../src/main.js (app.js:5742)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at Object.0 (app.js:5767)
    at __webpack_require__ (app.js:679)
    at app.js:725

If we use the latest version of nodejs and npm, its failing to run in the localhost. Though the build is fine, we are getting this console error. 

Node - 6.13.4
Node - 12.16.1
bootstrap-vue - 2.5.0

**Comment by tmorehouse** [comment]
Do you see a similar issue when using BootstrapVue `2.6.1`?

**Comment by AshokRaj29** [comment]
Yes. I used the latest version but still getting that error. 

Note : If we used the old node version it worked fine. In my old machine(2 months old probably node version 10 ) it worked fine. But once we update it and revert back to old version the error is not going away.

**Comment by AshokRaj29** [comment]
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    babel-helper-vue-jsx-merge-props: ^2.0.3 => 2.0.3
    babel-plugin-jsx-vue-functional:  2.1.0
    babel-plugin-transform-vue-jsx: ^3.5.0 => 3.7.0
    babel-preset-vue:  1.2.1
    babel-preset-vue-app:  1.3.2
    bootstrap-vue: ^2.4.0 => 2.6.1
    eslint-plugin-vue: ^4.7.1 => 4.7.1
    jest-serializer-vue: ^0.3.0 => 0.3.0
    portal-vue:  2.1.7
    vue: ^2.5.17 => 2.6.10 (2.6.11)
    vue-cookies: ^1.5.6 => 1.5.13
    vue-eslint-parser:  2.0.3
    vue-functional-data-merge:  3.1.0
    vue-hot-reload-api:  2.3.0
    vue-jest: ^1.0.2 => 1.4.0
    vue-loader: ^13.7.3 => 13.7.3
    vue-resource: ^1.5.0 => 1.5.1
    vue-router: ^3.1.3 => 3.1.6
    vue-style-loader: ^3.0.1 => 3.1.2
    vue-template-compiler: ^2.5.17 => 2.6.10
    vue-template-es2015-compiler:  1.6.0
    vue-typeahead: ^2.3.2 => 2.3.2
    vue2-filters: ^0.3.0 => 0.3.0
    vue2-typeahead: ^1.1.0 => 1.3.1
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by tmorehouse** [comment]
This might be a bug in rollup.js that we use to generate the esm.js bundle (as well as the common.js bundle).

Rollup.js has just released v2.0.x (which we have upgraded to in the upcoming next release (v2.7.0).

**Comment by AshokRaj29** [comment]
import BootstrapVue from 'bootstrap-vue/dist/bootstrap-vue.esm';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';

Is there any other way we can overcome this issue till 2.7.0 is released.

**Comment by tmorehouse** [comment]
```js
import BootstrapVue from 'bootstrap-vue/esm/';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';
```

**Comment by AshokRaj29** [comment]
env.js:65 Uncaught SyntaxError: Unexpected token '.'
    at Object../node_modules/bootstrap-vue/esm/utils/env.js (app.js:3357)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (safe-types.js?44a9:1)
    at Object../node_modules/bootstrap-vue/esm/utils/safe-types.js (app.js:3533)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (inspect.js?f12c:1)
    at Object../node_modules/bootstrap-vue/esm/utils/inspect.js (app.js:3405)
    at __webpack_require__ (app.js:679)

After updating to bootstrap-vue/esm, this is the error am getting.

**Comment by tmorehouse** [comment]
Weird... it is complaining about line 65 is `/esm/utils/env.js` but there are only 61 lines in that file.

**Comment by AshokRaj29** [comment]
After looking at the at webpack_require (app.js:679), its something to deal with the configuration. Changed the          contentBase: './dist', to       contentBase: '"./dist"' in the dev.env config file and that solved the issue.
