### ISSUE TITLE
Bootstrap Vue Navbar Dropdown Not Working After Nuxt Generate But Works In Nuxt Dev

### ISSUE THREAD

**Issue by humbertoT2** [bootstrap-vue/bootstrap-vue#4929]
### Describe the bug

Building a webpage with Nuxt JS and Bootstrap Vue—Navbar dropdown functionality works as expected in dev mode but does not work when generated to static files. Clicking a dropdown item does nothing in the static files but drops down properly in development mode. 

Running npm run generate outputs expected static files with 0 errors but functionality is missing in navbar dropdown. 

### Steps to reproduce the bug

1. Clone my demo project: https://github.com/humbertoT2/bootstrap-gen-test.git

`cd /bootstrap-gen-test/
npm install
npm run generate
`
2. Open index.html in bootstrap-gen-test/dist
3. Click dropdown items in the bootstrap vue nav - they do not dropdown but html and css is loaded.

If you do not want to clone the project you can do the following. 

1. I generated this project from nuxtjs get started page with:
npx create-nuxt-app <project-name>

2. Simply choose bootstrap as your UI framework in the setup process

3. Add example dropdown nav code from bootstrap vue component docs in index.vue: 
4. npm run generate
5. open index.html in your-project-name/dist/

### Expected behavior

Navbar dropdown item functionality to work (dropdown) in static file setting

### Versions

nuxt: ^2.0.0
bootstrap-vue: ^2.0.0
bootstrap: ^4.1.3

**Environment:**

- Device:  Macbook
- Browser: Chrome

### Demo link

https://t2hwp.t2marcom.com/bootstrapvue/dist/index.html

**Comment by tmorehouse** [comment]
Are the JS files being loaded? or are they being blocked by the browser security that prevents local javascript file from executing when loading HTML files from the local drive?

**Comment by tmorehouse** [comment]
Also, you should update:

- Nuxt: `^2.11.0`
- bootstrap-vue: `^2.6.1`
- bootstrap: `^4.4.1`

**Comment by tmorehouse** [comment]
I have discovered your issue(s).

You are viewing the dist folder (https://t2hwp.t2marcom.com/bootstrapvue/dist/index.html)

And Nuxt is not configured to run on mountpoint `/dist` (the base dir).

If you inspect the files trying to be loaded:

![image](https://user-images.githubusercontent.com/2781561/76481575-9c12cc80-63f0-11ea-8c05-c9aa7055bc60.png)

You will notice taht they are loading from `/_nuxt/xxxxxxx.js` not `/dist/_nuxt/xxxxxxx.js`, which is creating the following errors in the browser console:

![image](https://user-images.githubusercontent.com/2781561/76481700-fc097300-63f0-11ea-9765-596091b1153c.png)

You will either need to copy the `/dist/*` files to the root of your webserver, or configure nuxt's `base` property (https://nuxtjs.org/api/configuration-router#base)

**Comment by tmorehouse** [comment]
What is happening with dev mode server is that the launched webserver root is set to be inside dist (the URL does not have the `/dist/` added to it.

**Comment by humbertoT2** [comment]
Thank you for your replies - moving the contents of dist did not work. 

I have found an article that is suggesting to me complications of bootstrap vue and static generated sites may cause issues and to just use bootstrap cdn and html components instead of bootstrap vue and its vue components. 

https://medium.com/javascript-in-plain-english/generate-static-websites-with-nuxt-4fd0491340e

A quote from the article: 

"In the head object, we changed the title so that we display the title we want instead of the default title. In the link section, we add the Bootstrap CSS, and in the script section, we add the Bootstrap JavaScript files and jQuery, which is a dependency of Bootstrap. Since we want to build a static site, we cannot use BootstrapVue because it is dynamic."

**Comment by tmorehouse** [comment]
The issue you are seeing is related to your Nuxt configuration, as you can see from above it is related to where nuxt thinks you are mounting your pages on the web server.

This has nothing to do with BootstrapVue or Bootstrap.

The quote you have is misinformed, and incorrect.  Bootstrap + JQuery is dynamic.  Our Docs site is a static generated site (although set up to be a PWA), using Nuxt and BootstrapVue. created using `nuxt generate`.  You can see the generated files at https://github.com/bootstrap-vue/bootstrap-vue.github.io
