### ISSUE TITLE
Problem on reset form file

### ISSUE THREAD

**Issue by meyt** [bootstrap-vue/bootstrap-vue#493]
When setting `null` value to model of `b-form-file`, filename not changed, 
there is example of my behavior for reset a form file value.
https://jsfiddle.net/3dw5djb1/6/

**Comment by tmorehouse** [comment]
This appears to be how the v-model is internally bound,  It is currently bound as a one way. File inputs are a bit different than other inputs, as they only allow you to programmatically set the value to an empty string, which makes the two-way v-model not work correctly in some cases.

I might be able to modify the behaviour to handle two way binding to allow you to set it to null or an empty string, or introduce a `reset()`method that could be called.

**Comment by tmorehouse** [comment]
Because of the limitation of file inputs in Vue, the PR adds a reset() method to the component that you can call to clear the file from the input.  You will need a reference to the file component:

```html
<div id="app">
  <b-form-file
    ref="fileinput"
    v-model="file"
    choose-label="SELECT"
    placeholder="NO FILE"
  ></b-form-file>
  <br> Selected file: {{file && file.name}}
  <br>
  <b-btn @click="del()">DELETE</b-btn>
```
```js
window.app = new Vue({
  el: '#app',
  data: {
    file: null
  },
  methods:{
    del: function(){
    	this.$refs.fileinput.reset();
    }
  }
});
```

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Please refer to the update docs for details.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
