### ISSUE TITLE
Cannot toggle order in table

### ISSUE THREAD

**Issue by CrixuAMG** [bootstrap-vue/bootstrap-vue#494]
These are the fields I've set: 
`        data() {
            return {
                fields: {
                    name: {
                        label: 'Title',
                        sortable: true
                    },
                    connectivity: {
                        label: 'Connectivity',
                        sortable: true
                    },
                    last_updated: {
                        label: 'Last updated',
                        sortable: true
                    },
                    author: {
                        label: 'Author',
                        sortable: true
                    },
                    status: {
                        label: 'Status',
                        sortable: true
                    }
                }
            }
        },`

When I want to order the table, I see the icons switching, but nothing else is happening. No errors/warnings are shown in the devtools. Am I doing something wrong?

**Comment by tmorehouse** [comment]
Could you provide a fiddle of your example?

**Comment by CrixuAMG** [comment]
I don't think I can provide a fiddle, since it uses data from an api, but I'll send you some screenshots of test data.

[Imgur link](http://imgur.com/a/9QWbU)

**Comment by tmorehouse** [comment]
Ah, you have sorting on a "virtual" column (`connectivity`)

Does sorting work when you sort on other columns (i.e. name)?

**Comment by CrixuAMG** [comment]
Nope, none of them work. I would've thought that the Last updated column would be sortable, but apparently none of them just work. Any idea what it could be?

**Comment by tmorehouse** [comment]
Try removing the `item_key` property on the b-table

**Comment by CrixuAMG** [comment]
I tried removing it, clicked every column and reloaded a couple of times, but no result. Nothing was changed after clicking any of the column titles.

**Comment by tmorehouse** [comment]
Its hard to tell without a working example we can look at.

Could you provide a fiddle with some hard coded data as your items?

**Comment by CrixuAMG** [comment]
I'll get on creating a working example, I'll post the link here when it's done 👍

**Comment by CrixuAMG** [comment]
I got it to work by changing the title for a record in the database, now I can sort by the title column at least.
However, and no matter what format it is in, I cannot order by the Last updated column. This is rather important for the project. As you could see in the screenshots, the difference is exactly one day, which should be enough to order by the date.
The only thing I do to the date is using a mixin to format it to the format as seen in the screenshot.

**Comment by tmorehouse** [comment]
Could you provide a sample of you item data structure?

**Comment by CrixuAMG** [comment]
I've added a screenshot of the data. This collection is one of the item.item's.
[http://imgur.com/a/9QWbU](http://imgur.com/a/9QWbU)

**Comment by tmorehouse** [comment]
What I think it happening, is that some of your columns are objects.  Remember that columns are sorted by the raw underlying data (not the presentational or formatted data).  When sorting a column that is an object, the object is serialized into a string (each key/value is flattened into the value string and concatenated with other values in the column object.

See lines https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/table.vue#L66-L76:
```js
    const toString = v => {
        if (!v) {
            return '';
        }
        if (v instanceof Object) {
            return Object.keys(v).map(k => toString(v[k])).join(' ');
        }
        return String(v);
    };
```

The generated string that is sorted on will depend on the order the keys were defined on the object.

You might need to create your own sortCompare routine that handles each column specifically, or massage your data before passing it to b-table.

**Comment by CrixuAMG** [comment]
I just fixed it with some help from a colleague.
The issue was that Vue apparently it doesn't like me doing item.item.{x}, instead I now use item.value.{x}, where {x} represents the value in the response data, and value equals what is set in the scope. 
Thanks for the help!
