### ISSUE TITLE
Control alignment/Justification of Checkbox group items

### ISSUE THREAD

**Issue by lennycode** [bootstrap-vue/bootstrap-vue#4940]
### Is your feature request related to a problem? Please describe...

Kind of. I have about 20 mixed length English strings in an array, and it made a decision to center them in the browser them instead of left justify. The strings may contain \ but no fancy characters.  My code is as follows:
`<b-form-group label="Please Carefully Verify The Following:">

              <b-form-checkbox-group

                id="checkbox-group-1"

                v-model="checklistSelected"

                :options="checklist"

                name="ckg-1"

                stacked

                size="lg"

                switches

              ></b-form-checkbox-group>`

### Describe the solution you'd like

A way to set alignment? Unless it does not like a character embedded in my strings!

**Comment by tmorehouse** [comment]
Have you tried the [flex display and alignment utility classes](https://bootstrap-vue.js.org/docs/reference/utility-classes)?

```html
<b-form-checkbox-group
  id="checkbox-group-1"
  v-model="checklistSelected"
  :options="checklist"
  name="ckg-1"
  stacked
  size="lg"
  switches
  class="d-flex flex-wrap justify-content-center"
></b-form-checkbox-group>
```

Which results in the following:

![image](https://user-images.githubusercontent.com/2781561/76582815-1b1e0880-64b6-11ea-9a71-d82b69f28e39.png)

**Comment by lennycode** [comment]
Did you notice it is  **stacked** :)
I think if the strings are equal length, everything works out left justified.

**Comment by tmorehouse** [comment]
Ah...  so this:

![image](https://user-images.githubusercontent.com/2781561/76585845-32f98a80-64be-11ea-9f9d-bd80ec67ac9c.png)

or this:

![image](https://user-images.githubusercontent.com/2781561/76586188-ed898d00-64be-11ea-94ff-49c517dcdc1f.png)

?

**Comment by lennycode** [comment]
Thanks!
The former is exactly how it it comes out. The two of them "merged" would be perfect!
Boxes and labels left aligned.

**Comment by tmorehouse** [comment]
Boxes and labels left align is the default (assuming the container they are placed in has default text-left alignment):

![image](https://user-images.githubusercontent.com/2781561/76626043-2c4b3180-6517-11ea-920c-1d19ac4ecb79.png)

**Comment by tmorehouse** [comment]
If then you want that centered on the age, you wrap it in a container that is centered

```html
<template>
  <div class="d-flex">
    <b-form-checkbox-group
      v-model="selected"
      :options="options"
      stacked
      class="mx-auto"
    ></b-form-checkbox-group>
  </div>
</template>
```

![image](https://user-images.githubusercontent.com/2781561/76626704-6a952080-6518-11ea-843a-2757879be729.png)

**Comment by lennycode** [comment]
Played around a bit, and got the entire container to justify, but still can't get children to justify:
This exists in a `b-tab` if it matters
```
<div class="d-flex align-content-start">
              <b-form-checkbox-group
                id="checkbox-group-1"
                v-model="checklistSelected"
                :options="checklistb"
                name="checklist-1"
                stacked
                size="lg"
                switches
                //class "tried a bunch of flexbox options"
                >
             </b-form-checkbox-group>
</div>
```
![image](https://user-images.githubusercontent.com/845855/76630939-35d49980-6517-11ea-9f96-5962d35a65cf.png)

**Comment by tmorehouse** [comment]
Perhaps you need to render individual options to get the centered

```html
<div class="d-flex">
  <b-form-checkbox-group
    id="checkbox-group-1"
    v-model="checklistSelected"
    name="checklist-1"
    size="lg"
    switches
    class="d-flex flex-column mx-auto"
  >
    <b-form-checkbox
      v-for="opt in checklistb"
      :key="opt.text"
      :value="opt.value"
      class="mx-auto"
    >
      {{ opt.text }}
    </b-form-checkbox>
  </b-form-checkbox-group>
</div>
```

![image](https://user-images.githubusercontent.com/2781561/76632855-9f0dda00-6522-11ea-9e5a-ff07ab4535d7.png)

**Comment by lennycode** [comment]
I was hoping to do it with the compact notation but this worked (I actually have a requirement for both styles). Thanks for all your help.
 ```
 
            <div class="d-flex align-content-start" style="margin-left:50px">
              <div class="d-flex">
                <b-form-checkbox-group
                  id="checkbox-group-1"
                  v-model="checklistSelected"
                  name="checklist-1"
                  size="lg"
                  switches
                  class="d-flex flex-column mx-auto"
                >
                  <b-form-checkbox
                    v-for="opt in checklistb"
                    :key="opt.text"
                    :value="opt.value"
                    class="d-inline-flex"
                  >{{ opt.text }}
                  </b-form-checkbox>
                </b-form-checkbox-group>
              </div>
            
            </div>
```

![image](https://user-images.githubusercontent.com/845855/76637116-8b617400-6520-11ea-8f7f-6fe97102c193.png)
