### ISSUE TITLE
Document how to use the b-dropdown scrollable and boundary option for html elements

### ISSUE THREAD

**Issue by ccleve** [bootstrap-vue/bootstrap-vue#4941]
### Is your feature request related to a problem? Please describe...

I'm using a b-dropdown inside a scrollable element and it doesn't fit in the container. Per the documentation (https://bootstrap-vue.org/docs/components/dropdown#boundary-constraint) I need to set the boundary="something". Also, the dropdown is very large and needs to be scrollable.

I tried the boundary="viewport" and "window" options and it just doesn't constrain the dropdown or make it scrollable. I tried creating an absolutely-positioned div where the dropdown should appear, but I don't think I've got the syntax right:

```
< b-dropdown boundary="#dropcontainer" > ...

<div id="dropcontainer"></div>

.drop-container {
  position: absolute;
  top: 100px;
  left: 100px;
  height: 100px;
  width: 200px;
}
```
All it does is position the dropdown as if it is a dropup.

### Describe the solution you'd like

Just add an example to the docs of a scrollable dropdown in a scrollable div..

**Comment by tmorehouse** [comment]
If you are wanting the content of the menu to scroll, you will need to apply some custom CSS

```html
<template>
  <div>
    <b-dropdown class="my-class" text="Dropdown">
       <b-dropdown-item-button>Item 1</b-dropdown-item-button>
       <b-dropdown-item-button>Item 2</b-dropdown-item-button>
       <b-dropdown-item-button>Item 3</b-dropdown-item-button>
       <b-dropdown-item-button>Item 4</b-dropdown-item-button>
       <b-dropdown-item-button>Item 5</b-dropdown-item-button>
    </b-dropdown>
  </div>
</template>

<style>
  .my-class .dropdown-menu {
    max-height: 100px;
    overflow-y: auto;
  }
</style>
```

If using scoped styles:

```html
<style scoped>
  .my-class /deep/ .dropdown-menu {
    max-height: 100px;
    overflow-y: auto;
  }
</style>
```

**Comment by ericdrobinson** [comment]
@tmorehouse Thanks for providing a solution. Would it perhaps make sense to add a component property to the dropdown that enabled this?

I've come across the need for this myself: we have a dropdown that has so many options that it extends beyond the height of the default viewport. I'm addressing the issue by setting `max-height: 100vh; overflow-y: auto;`, but it occurs to me that that might be a reasonable default (at least when the `boundary` property is set to "viewport")...

**Comment by ericdrobinson** [comment]
@tmorehouse Before this issue disappears, any final thoughts on this? Searching the current dropdown docs for "scroll" only shows boundary-related stuff. Understanding how to scroll the innards of the dropdown list is, I think, valuable. If explicit functionality isn't added, perhaps updating the documentation with a brief explanation (e.g. "In event of very long option lists") would be helpful?

Would [have been] for me...

**Comment by andresuchitra** [comment]
> If you are wanting the content of the menu to scroll, you will need to apply some custom CSS
> 
> ```
> <template>
>   <div>
>     <b-dropdown class="my-class" text="Dropdown">
>        <b-dropdown-item-button>Item 1</b-dropdown-item-button>
>        <b-dropdown-item-button>Item 2</b-dropdown-item-button>
>        <b-dropdown-item-button>Item 3</b-dropdown-item-button>
>        <b-dropdown-item-button>Item 4</b-dropdown-item-button>
>        <b-dropdown-item-button>Item 5</b-dropdown-item-button>
>     </b-dropdown>
>   </div>
> </template>
> 
> <style>
>   .my-class .dropdown-menu {
>     max-height: 100px;
>     overflow-y: auto;
>   }
> </style>
> ```
> 
> If using scoped styles:
> 
> ```
> <style scoped>
>   .my-class /deep/ .dropdown-menu {
>     max-height: 100px;
>     overflow-y: auto;
>   }
> </style>
> ```

Alternatively you may also use:

```scss
::v-deep .dropdown-menu {
max-height: 200px;
overflow-y: auto;
}
```

**Comment by damonroberts95** [comment]
https://github.com/bootstrap-vue/bootstrap-vue/issues/4941

**Comment by evavargas** [comment]
in SCSS scoped:
`.form-container {
  padding-block: 4rem;
  padding-inline: 4.8rem;
  .my-dropdown ::v-deep
    .dropdown-menu {
    max-height: 60vh;
    overflow-y: scroll;
  } 
}`

**Comment by Boris-creator** [comment]
You can also use the `menu-class` prop.
