### ISSUE TITLE
b-form-input doesn't accept basic input native property

### ISSUE THREAD

**Issue by alexbruno** [bootstrap-vue/bootstrap-vue#4946]
**b-form-input** component covers a lot of utilities to input fields, but I just noticed it doesn't accept **maxlength** input native property. (Neither **minlength**, **pattern** and maybe others!)

Please, could you fix it?

**Comment by tmorehouse** [comment]
They are note defined as properties on the component, but the attributes will get added (inherited) to the inner input.

By default, Vue will transfer any attributes that are not props to the root element of the component.

```html
<div>
 <b-form-input maxlength="10" pattern="\d{1,10}"></b-form-input>
</div>
```

Results in this being rendered:

![image](https://user-images.githubusercontent.com/2781561/76653875-6da80500-6548-11ea-8aee-6bd90e066a15.png)

**Comment by alexbruno** [comment]
Really? So I'm doing somethig wrong in my implementation!
I will check it again.

**Comment by alexbruno** [comment]
Yep, sorry!
I was doing it wrong by coding my derivative component in my app.
It's OK.
Thanks for help!
