### ISSUE TITLE
Make Pagination Control Element Used Selectable

### ISSUE THREAD

**Issue by SlvrEagle23** [bootstrap-vue/bootstrap-vue#4949]
### Is your feature request related to a problem? Please describe...

With one of the more recent updates to the BootstrapVue library, the buttons in the pagination control are switched from links to buttons.

In the very newest versions of Bootstrap, this represents no issue for styling as buttons are styled the same way as links. However, in older versions (even fairly recent older versions, i.e. 4.1.1) this isn't the case.

Because of a dependency we have on a third-party Bootstrap theme, we're basically "locked" onto version 4.1.1 at the moment, which means that the very latest update of BootstrapVue causes very bizarre styling problems with the Pagination control.

As far as I can tell, this is the _only_ issue across all of BootstrapVue that prevents it from being "back-compatible" with slightly older versions of Bootstrap.

Rather than lock my used version of BootstrapVue to an older version, I'd like to be able to continue to take advantage of bug fixes and other improvements.

### Describe the solution you'd like

The lowest-friction option for me as a designer would be a boolean property flag (like `pills` already is) that indicates that the pagination should use `<a>` tags (with corresponding `aria-role=button` for accessibility) instead of `<button>` tags. This would provide full back-compatibility with older Bootstrap versions while preserving the default functionality for new users moving forward.

### Describe alternatives you've considered

I am looking into the practicality of building a custom component that wraps around the new pagination control and injects link elements in to replace the button ones to preserve compatibility, but this is looking to be somewhat more tedious than I expected because of needing to latch onto internal pagination functionality with each click event. It's probably not the hardest problem to solve, but it would be _really_ nice if the existing control offered it.

**Comment by tmorehouse** [comment]
Pagination in Bootstrap v4.x doesn't use the `.btn` class on the pagination links/buttons.

But there are ways you can make binding a bunch of props at once easier:

```js
export const paginationClassProps = {
  firstClass: 'foo',
  prevClass: 'foo',
  pageClass: 'foo',
  nextClass: 'foo'
  lastClass: 'foo'
}
```

And then in your template markup:

```html
<b-pagination
  v-model="currentPage"
  v-bind:paginationClassProps
  :per-page="perPage"
  :total-rows="totalRows"
></b-pagination>
```

**Comment by SlvrEagle23** [comment]
I actually have done further research on this, and it turns out the differentiating factor is that earlier versions of Bootstrap used `<a>` tags instead of `<button>` tags for the pagination buttons, and it's just not styling the `button` tags. This is likely something I can patch in on my end.

**Comment by tmorehouse** [comment]
A few releases ago, we switched b-pagination to use buttons instead of links, for accessibility reasons. b-pagination-nav still uses links (as that component is used to change the URL, where the former is used to control a component)

Both still use the same pagination classes for styling the UX

**Comment by SlvrEagle23** [comment]
I'm reopening this issue with an updated description in the first comment, because I've done some further research into what's causing this styling disconnect with slightly older versions of Bootstrap. I can likely work around this with a custom component, but I think it's worthwhile nonetheless to ask for something to this effect to be added upstream, because it would allow me to continue to update BootstrapVue and take advantage of new components without much hassle.

**Comment by tmorehouse** [comment]
Which version of Bootstrap CSS are you usig?  we only support v4.3.x and above

**Comment by tmorehouse** [comment]
You might need to compare the Bootstrap SCSS between the version you are using and Bootstrap 4.4 for pagination and perhaps add the missing/changed values (most likely padding, margins, or line-height values) as a custom SCSS/CSS loaded after your themed Bootstrap SCSS.

Allowing customization of the button elements would pose additional Accessibility issues as there would need to be additional handlers, etc to make the element act like a button for screen reader users.

**Comment by SlvrEagle23** [comment]
Yep, it turns out this was fixed with a really simple modification to the SCSS on my end.
