### ISSUE TITLE
Get access to the field in template in table

### ISSUE THREAD

**Issue by happilymarrieddad** [bootstrap-vue/bootstrap-vue#495]
Hey guys,

Is it possible to access the field inside a template inside of a b-table. Here is an example.

![selection_211](https://user-images.githubusercontent.com/6416323/26987001-155a7a88-4d07-11e7-9355-283c6d8b8922.png)
![selection_210](https://user-images.githubusercontent.com/6416323/26987005-186a4546-4d07-11e7-8e2d-61757bd01db2.png)

I hope that makes sense.

**Comment by happilymarrieddad** [comment]
Basically, what I want to do is loop through the fields that are passed in and handle them specially.

![selection_213](https://user-images.githubusercontent.com/6416323/26987479-ec84646e-4d08-11e7-9001-6ee053a970fe.png)
![selection_214](https://user-images.githubusercontent.com/6416323/26987483-ee7ab8fe-4d08-11e7-9453-d5048c9bf6d0.png)

I hope that makes sense.

**Comment by happilymarrieddad** [comment]
I want to use the b-table as a template and pass in different tables from a database with differing number of properties.

**Comment by tmorehouse** [comment]
Use the two parameter option for `v-for`:

```html
<template v-for"(field, key) in fields" :slot="key" scope="item">
   <!-- Do your stuff here -->
</template>
```

As what you have currently is binding the slot name to the field object, not the field key name.

**Comment by alexsasharegan** [comment]
Fun fact I just learned, you can destructure in there too:

```vue
<template v-for"({ label }, fieldName) in fields" :slot="key" scope="item">
   <!-- Do your stuff here -->
</template>
```

**Comment by happilymarrieddad** [comment]
Excellent!!! Thanks so much guys! It works great!
