### ISSUE TITLE
Set the max-width of popover

### ISSUE THREAD

**Issue by Symbolk** [bootstrap-vue/bootstrap-vue#4950]
I am using the popover to wrap a long content, however, the popover seems too narrow to display the content property.

### Describe the solution you'd like

 I noticed that in the [doc] it says: 
> The maximum width of the popover is hard coded by Bootstrap v4 CSS to 276px. 

[doc]: https://bootstrap-vue.js.org/docs/components/popover/

So I tried solutions from StackOverflow to override the width and the max-width in css:
```vue
          <b-nav-item active href="#" id="repo-commit">{{repoName}}:{{commitID}}</b-nav-item>
          <b-popover
            :content="originalMsg"
            placement="bottom"
            style="max-width: 500px !important;"
            target="repo-commit"
            title="Original Commit Message"
            triggers="hover focus"
          ></b-popover>
```
```
.popover {
  max-width: 600px !important;
  width: 600px !important;
}
```

![image](https://user-images.githubusercontent.com/14107297/76696721-75db7e00-66c9-11ea-8df2-6b0e9448a9b7.png)

However, it seems not working.

### Describe alternatives you've considered

I searched and noticed that #165 and #2051 are related to this issue, but no clear solution provided.

**Comment by tmorehouse** [comment]
You need to use custom CSS to override the max width/width.

Note that anything above 320px will not fit on mobile screens (which is why it is best to use max-width instead of width)

**Comment by tmorehouse** [comment]
Popover max-width can be controlled via the SASS variable `$popover-max-width`

**Comment by tmorehouse** [comment]
SASS variabled must be set before `@import`ing Bootsttrap SCSS.

CSS overrides (your examples above) must be loaded after.

If using scoped SCSS you will need to use the Vue loader deep selector `/deep/` (or `>>>` )

**Comment by Symbolk** [comment]
> You need to use custom CSS to override the max width/width, or SCSS variables (theming)
> 
> Note that anything above 320px will not fit on mobile screens (which is why it is best to use max-width instead of width)

Thanks, I am just making a website that does not allow mobile access.

**Comment by Symbolk** [comment]
> SASS variabled must be set before `@import`ing Bootstrap SCSS.
> 
> CSS overrides (your examples above) must be loaded after.
> 
> If using scoped SCSS you will need to use the Vue loader deep selector `/deep/` (or `>>>` )

By just importing the css file after `import 'bootstrap/dist/css/bootstrap.css'` instead of setting it in `<style scoped>`, it works like a charm!

![image](https://user-images.githubusercontent.com/14107297/76704087-8d3e5980-6711-11ea-975d-0305cc94ef5e.png)
