### ISSUE TITLE
Ability to change the increase/decrease (+/-) buttons in the Form SpinButton component

### ISSUE THREAD

**Issue by bencelaszlo** [bootstrap-vue/bootstrap-vue#4958]
### Is your feature request related to a problem? Please describe...

I can't find an option to change the +/- characters in the Form SpinButton component's buttons:

### Describe the solution you'd like

I would like to have a `slot` to customize the component. Change the `+` to `>` or the `-` to `DEC` or something like that.

### Describe alternatives you've considered

The current solution is to use third-party components, which is not optimal, because the Bootstrap-Vue SpinButton only lacks these options to swap these under-maintained third party components.

### Additional context

![icons](https://user-images.githubusercontent.com/19412564/76856303-4a849a80-6853-11ea-9020-db604efdba4c.png)

**Comment by tmorehouse** [comment]
Currently these are bootstrap icons that are rendered (not characters) inside buttons, but it should be possible to add slots for the content in a future release.

**Comment by bencelaszlo** [comment]
> Currently these are bootstrap icons that are rendered (not characters) inside buttons, but it should be possible to add slots for the content in a future release.

I would be more than happy with this.
