### ISSUE TITLE
How to bind to Form Radio change?

### ISSUE THREAD

**Issue by gornostal** [bootstrap-vue/bootstrap-vue#496]
I can't figure out what's the proper way to declare a function that is triggered when user changes state of radio buttons.

This seems to work, but not really as I want: https://jsfiddle.net/ozhmj480/2/
`@input` triggers my callback on the initial set up too. I want it to be triggered only on a user action.
Is there a way to do that?

BTW, it's pretty straightforward how to do that for inputs and checkboxes. I would simply use `@change`, but it doesn't work with radio buttons.

Thanks.

**Comment by tmorehouse** [comment]
I'll take a look at this, and might be able to add in a firing of `change` event, based on clicking the radios.

**Comment by gornostal** [comment]
That would be great!
Thanks for the quick response.

**Comment by gornostal** [comment]
@tmorehouse Could you take a look at the PR that fixes this issue?
Please let me know if it needs any changes.

**Comment by tmorehouse** [comment]
The only thing with change events on Radio is that they are not always triggered by every browser in hte same way for input type="radio".,

Some browsers fire it when the radio is "unselected" and also for the newly selected one, while other only fire change on the clicked radio button.  So this might not work in all browsers.

It would be best to handle this by listing for click, which is supported by all browsers, and then inspect the value to see if it has changed, and if so then emit a change event only if it has changed.

**Comment by gornostal** [comment]
Got it. Will change

**Comment by alexsasharegan** [comment]
Have you tried adding `@change.native="callback"`?

**Comment by gornostal** [comment]
No, I have not.

**Comment by alexsasharegan** [comment]
You can use the `.native` modifier to listen to a native html event on a component instance's root element. It gets like one line in the Vue docs, but I have found it to be super useful!

**Comment by gornostal** [comment]
Just read what `.native` is. Looks like I overlooked that very useful feature of Vue.
Thanks for pointing out.

**Comment by alexsasharegan** [comment]
Like I said, barely gets an honorable mention in the docs, but it's a necessity!

**Comment by tmorehouse** [comment]
Check out https://jsfiddle.net/ozhmj480/3/ for example of using `@change.native`

**Comment by gornostal** [comment]
@tmorehouse thanks for the example.

**Comment by tmorehouse** [comment]
THe changes have been merged into the master and will be available in the next release (v0.17.0)
