### ISSUE TITLE
vue-form-widard tab shifts in the modal window

### ISSUE THREAD

**Issue by young-altair** [bootstrap-vue/bootstrap-vue#4964]
### Describe the bug

I'm using vue-form-wizard [https://github.com/BinarCode/vue-form-wizard](https://github.com/BinarCode/vue-form-wizard)
Version up to bootstrap-vue@2.0.0-rc.19 working like it should.
Version after bootstrap-vue@2.0.0-rc.19 produce this kind of Bug
[https://github.com/BinarCode/vue-form-wizard/issues/330](https://github.com/BinarCode/vue-form-wizard/issues/330)
The first index tab shifts to the last position, when modal is opened for a second time and so on.

### Steps to reproduce the bug
please see the demo link for more clear detail

HTML
```<div id="app">
<div>
<b-btn v-b-modal.modal1>Launch demo modal</b-btn>

  <!-- Modal Component -->
  <b-modal id="modal1" title="Bootstrap-Vue">
   <form-wizard @on-complete="onComplete" 
                      shape="square"
                      color="#3498db">
            <tab-content title="Personal details"
                         icon="ti-user">
              My first tab content
            </tab-content>
            <tab-content title="Additional Info"
                         icon="ti-settings">
              My second tab content
            </tab-content>
            <tab-content title="Last step"
                         icon="ti-check">
              Yuhuuu! This seems pretty damn simple
            </tab-content>
        </form-wizard>
  </b-modal>
        
 </div>
</div>
```
SCRIPT
```Vue.use(VueFormWizard)
new Vue({
 el: '#app',
 methods: {
  onComplete: function(){
      alert('Yay. Done!');
   }
  }
})
```
### Expected behavior

Why the tab is shifting inside a modal?

### Versions

**Libraries:**

 "bootstrap": "^4.4.1",
 "vue": "^2.6.11",
 "vue-form-wizard": "^0.8.4",
 "bootstrap-vue": "^2.7.0",

**Environment:**

-Windows 10 64bit
-Node v12.16.1 

### Demo link
Working One
[https://jsfiddle.net/bt5dhqtf/1954/](https://jsfiddle.net/bt5dhqtf/1954)

Not working with the latest version
[https://jsfiddle.net/2wx5rdg6/](https://jsfiddle.net/2wx5rdg6/)

**Comment by tmorehouse** [comment]
This might be due to how modal's are now portalled an always lazy (by default).

Try setting the `static` prop on b-modal to disable portaling, and see if that helps.

**Comment by tmorehouse** [comment]
This is due to how vue-form-wizard detects the child tabs. With Vue 2.6.x, all slots are now functions and `this.$slots` can return stale vNodes.  To access the correct vnodes they need to run `this.$scopedSlots[slotName](scope)` to grab a fresh list of generated vNodes.

Because of portalling, and the modal content is now lazy, the issue is now croping up in `vue-form-wizard`'s tab detection routine. They are relying on old behaviour of Vue 2.5 where `this.$slots[slotName]` always had fresh copies of the vNodes.

**Comment by bahuubali** [comment]
@tmorehouse i love you, i save my life.LOL
