### ISSUE TITLE
Problem with table sorting

### ISSUE THREAD

**Issue by WifiDubt** [bootstrap-vue/bootstrap-vue#4971]
### Describe the bug

The first row of my header is a select box, that allows to select all rows of the table.
For this, the select column has the `sortable: false` property.
Despite this, when the column is clicked for the first time only, it still "re-orders" the table, emitting the `@sort-changed` event with "empty" params (as shown in the ps attached bellow)

### Expected behavior

As the column is not sortable, nothing should happen when clicking the cell

### Versions

**Libraries:**

- BootstrapVue: 2.7.0
- Bootstrap: 4.4
- Vue: 2.6.6

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Demo link/Additional context

This is a private platform, so I can't give access or demo it, but here's the print of the debug info.
<img width="800" alt="Captura de ecrã 2020-03-19, às 19 08 03" src="https://user-images.githubusercontent.com/19328374/77105462-9c751e00-6a15-11ea-90f4-e51fe220ce11.png">
You can also see this video showing the wrong sorting, as explained:
https://gofile.io/?c=26txny

**Comment by Hiws** [comment]
You probably want to add the `no-sort-reset` prop to your `b-table`.

**no-sort-reset description**
> When a table is sortable, clicking on any non-sortable column heading will clear the current sort values. Set this prop to disable this feature

**Comment by WifiDubt** [comment]
Yup, that's it! Thanks for the fast answer!
Just an idea, but wouldn't it make more sense for this to be the default?

**Comment by tmorehouse** [comment]
@WifiDubt then there would be no default way for keyboard only users or screen reader users to clear the sorting on the table.
