### ISSUE TITLE
Maybe release a new version ?

### ISSUE THREAD

**Issue by asafyish** [bootstrap-vue/bootstrap-vue#498]
There is plenty of good stuff committed since 0.16.1 was cut.
I for example, waiting for https://github.com/bootstrap-vue/bootstrap-vue/commit/b61d2adfdbdd3a172c163bda6d8d1d248a91c2d9 which is 21 days old :(

Thanks for the great work !

**Comment by pi0** [comment]
Hi @asafyish . I'll talk to dev team to make sure everything is ready for next release ;) Stay tuned.
