### ISSUE TITLE
Using items provider functions update every 5 seconds

### ISSUE THREAD

**Issue by mpimentel04** [bootstrap-vue/bootstrap-vue#4980]
I'm using the b-table component and every 5 seconds, I'm calling an API to keep the table updated.

To improve performance, I limited the number of lines to 100 using the paging feature.

the **"Using items provider functions"** feature would suit me well.

How can I use "provider functions" updating every 5 seconds without showing the user that the table is loading?

**Comment by mpimentel04** [comment]
I just checked that if I call the function manually, busy won't come true and it works as expected.

Sorry

**Comment by tmorehouse** [comment]
Provider functions are triggered by changes in table sorting, filtering, and pagination.

It sounds like you probably need to run a fetch in a `setInterval` or `setTImeout` and update the item's array passed to `b-table`.

**Comment by mpimentel04** [comment]
Ok, 

Thank you very much for the answer.
