### ISSUE TITLE
BTabs lazy - do not un-mount on deactivate (actual lazy)

### ISSUE THREAD

**Issue by matanshukry** [bootstrap-vue/bootstrap-vue#4982]
### Is your feature request related to a problem? Please describe...

While using tabs together with lazy, a tab will be mounted once activated, and un-mounted once deactivted.

However I want a tab to be mounted once activated, and stay that way (only be unmounted once parent is also unmounted, as usual).

### Describe the solution you'd like

add another property such as `lazy-once`

### Describe alternatives you've considered

Creating my own wrapper around tab with my own implementation of lazy, passing all other attributes and events to vue-bootstrap's tab component.

**Comment by tmorehouse** [comment]
It would probably be better to handle your own logic and `v-if` the tab-content into place when you heed it (i.e. when a certain condition has been met in the previous tabs).

As there could be various different scenarios that could drive the `lazy-once`... re-ordering of tabs, dynamic tabs, parent forced re-renders, tabs from loops, etc, all would have different effects on the "once" condition.

**Comment by matanshukry** [comment]
@tmorehouse Could you elaborate on the different scenarios you're talking about and why they matter?

Just to be clear, below is my component (briefly tested).
To test it I created a component that prints a log on mounted.

Tested it on 3 tabs (when they're not the 1st tab so they won't appear initially):
- When using it inside a botostrap-vue tab: it will be called once initially, even if you never see it, and never again
- When using it inside a bootstrap-vue lazy tab: it will be called every time we switch to it from a different tab
- When using it inside my wrapper: it will be called only once, but only once you switch to it first - not initially

```
<template>
  <b-tab
    ref="tab"
    v-bind="$attrs"
    v-on="$listeners"
  >
    <slot v-if="isActive" />
  </b-tab>
</template>

<script>
import { BTab } from "bootstrap-vue";

export default {
  components: {
    BTab,
  },
  inheritAttrs: false,
  data() {
    return {
      isActive: false,
    };
  },
  mounted() {
    if (this.$refs.tab.localActive) {
      this.activate();
    } else {
      const remove = this.$watch(
        "$refs.tab.localActive",
        (newValue) => {
          if (newValue) {
            remove();
            this.activate();
          }
        }
      );
    }
  },
  methods: {
    activate() {
      this.isActive = true;
    }
  },
}
</script>
```

**Comment by tmorehouse** [comment]
Placing the tabs in a modal, or other element where the entire content is lazy, or potentially portalled, where they get re-mounted/created, will re-set the behavior you are looking for.

**Comment by matanshukry** [comment]
@tmorehouse just tested it with a modal, and I understand what you're saying now but I don't see why it matters..

it make sense the entire component (including the lazy tab or wrapper) is deactivated once you switch from it, but the lazy effect when switching tabs is still in play.

Imagine 2 use case:
- user 1 go to the tab control with 3 tabs. He only view tab 1, and then leave
- user 2 go to the tab control with 3 tabs. He view all 3 tabs, back and forth multiple times each tab.
In either case, going to each tab will make an api call to load the relevant data

Using the current behavior:
- if tabs aren't lazy, user 1 will make 3 calls, 1 for each tab, although he will only view the 1st one
- if tabs are lazy, user 2 will make a call each time he will revisit the same tab.

Using my behavior (my lazy):
- There will be 1 api call for each tab viewed, only if viewed at all

**Comment by tmorehouse** [comment]
Perhaps you should be setting the `lazy` prop on each tab individually, and `v-bind`ing that to a data variable (Boolean).  Have the variable set to `true` initially, and once your API is called set the variable to `false`.

**Comment by matanshukry** [comment]
@tmorehouse sounds exactly like the behavior of the lazy tab I was suggesting and created, only instead of it being part of the tab you're suggesting to make it part of the parent component.

1 - I think it's a bad design to make it part of the parent component; the laziness behavior (both what I'm talking about and the one that currently exist) is a property of the tab, and logically should be there.
2 - Not only logically, but your idea also mean every time there's a new tab more code than necessary will be written just to support the laziness behavior; which is exactly what components are for - re-usability

**Comment by tmorehouse** [comment]
You could extend `<b-tab>` (or wrap it in a Higher Order Component - HOC) to add in that functionality of turning lazy off once shown, which would make it re-usable for your use case.

```html
<template>
  <b-tab v-bind="{ ...$attrs,  lazy: myLazy }" @click="myLazy = false">
    <template v-slot:title><slot name="title">$attrs.title</slot></template>
    <slot></slot>
  </b-tab>
</template>

<script>
  export default {
    data() {
      return {
        myLazy: true
      }
    }
  }
</script>
```

**Comment by matanshukry** [comment]
It's not that different from my component, only you're using `@click` to detect once it's seen (and also creating the title your self rather than using the property, although I'm not really sure why).
While it's shorter it still has the same "flaw" of my component - it's in my project.

I'm aware I can "bypass" this feature request and do it on my one with a wrapper, but I believe it's a useful feature.

Personally I'm not even sure why one would want the current lazy behavior - what is a use of a lazy that keeps deactivating/re-mounting? ...

**Comment by tmorehouse** [comment]
the lay prop prevents the DOM from being cluttered with a multitude of Vue component instances when not "shown", improving memory footprint of the application, specifically when the lazy content has many child component instances.

Another alternative option for you is to wrap your lazy once content in the tab with `v-b-visible.once` directive (with a callback).  And when the tab is shown (and the wrapper div with directive becomes visible, you call your api.

**Comment by matanshukry** [comment]
I think the comparison between v-if/v-show and current-lazy/my-lazy is a bit lacking, but I understand your point regarding the current behavior of lazy - although I wouldn't call it lazy.

Regarding the alternative: I'm not really looking for an alternative, the wrapping component is the 2nd best option in my opinion (1st being it will be inside BTab, like it should).
I think this feature should be inside of BTab- I'd love to hear and discuss why you think it shouldn't though.

Regardless, if the bootstrap-vue team think it's not a good fit we can close this issue - I also wrote an alternative so if anyone in the feature will want it and he find this issue and take it.

**Comment by SlyDave** [comment]
Totally in need of this feature right now! - thanks for the workaround even though they're annoying more complex for my use case - which is where these tabs are dynamically being included in via a b-table's v-slot:row_details where the table(s) itself is created by a v-for loop - thus the number of b-tables and b-tabs is unknown, so binding becomes a bit of a challenge...

Being able to lazy-load-once would be awesome.

For that matter, it'd be awesome if that could also be done for b-table v-slot:row-details too...
