### ISSUE TITLE
Understing how to use b-dropdown with API

### ISSUE THREAD

**Issue by verilog15** [bootstrap-vue/bootstrap-vue#4983]
In vue-strap I had the following code:
```
<v-select  v-model="custom.value"
        v-bind:disabled="!custom.key"
        v-bind:url="getURL('customs.value', custom)"
        placeholder="value"
        style="width:100%"
        search multiple show-count></v-select>
```
It lists the customs. The `getURL` returns a URL. From the Vue-strap docs, url is for a datalist. I'm trying to convert it to b-dropdown of Bootstrap-Vue. But I can't seem to understand how `b-dropdown` works. I feel like I should use `b-dropdown-item` but I tried both `to` and `href` props and it didn't list the array in the URL API. How can I achieve it?

**Comment by tmorehouse** [comment]
Could you show  screen short of the result you are expecting?  Is it a menu of items that when clicked on the item, change to that URL (goes to another page)?

**Comment by verilog15** [comment]
Hi @tmorehouse, thanks for the reply. I probably should have added the full code. The full code is: 
```
<div>
	<div v-for="(custom, index) in customsQuery" class="row">
		<div class="col-md-5 col-lg-5 col-xl-5 top5">
			<tooltip trigger="focus" placement="top" content="key">
				<typeahead  v-model="custom.key"
							v-bind:async="getURL('customs.key', custom)"
							style="width:100%"
							placeholder="key"></typeahead>
			</tooltip>
		</div>

		<div class="col-md-5 col-lg-5 col-xl-5 top5">
			<tooltip trigger="focus" placement="top" content="value">
				<v-select  v-model="custom.value"
						v-bind:disabled="!custom.key"
						v-bind:url="getURL('customs.value', custom)"
						placeholder="value"
						style="width:100%"
						search multiple show-count></v-select>
			</tooltip>
		</div>
		<div class="col-md-1 col-lg-1 col-xl-1 top5">
			<small>
				<a class="pointer" v-on:click="removeCustom(index)">
					<span class="glyphicon glyphicon-remove"></span>
				</a>
			</small>
		</div>
	</div>
</div>
```
The output:
![image](https://user-images.githubusercontent.com/39248005/77238182-bf026500-6bd6-11ea-948d-febfe41fcca6.png)
As you can see, user inserts some string (the key) in the left box. Then it will find all the values for this key. The `getURL` functions returns an URL to the API. This URL contains an array of all the elements that match the query. When user starts trying in the left box (for example `pro`), the `getURL` function will return an URL that contains all the keys that contain `pro` . After user have chosen the key, the `getURL` function will return another URL that contains all the values for that key (In that case in contains only one - `data`). It looks like bootstrap-vue does not support typeahead yet, then I'll try to find a third party library for that.  My question is how to replace `v-select` with `b-dropdown`. That is why I focused on this part in my first comment.

**Comment by tmorehouse** [comment]
Ah, you probably need to use a 3rd party component for type-ahead/search/auto-complete.

Such as https://github.com/alexurquhart/vue-bootstrap-typeahead

Otherwise you will need to manually handle calling your getUrl when the value of an input updates, and then pass the results into a `<b-form-datalist>` element. https://bootstrap-vue.js.org/docs/components/form#datalist-helper

You would pass the results of the ajax/axios call to the datalist options.

**Comment by verilog15** [comment]
Hi @tmorehouse, yes I agree. I do need typeahead for the left box, but I don't need typeahead for the right box (dropdown). My question is only for the right box. Imagine you already have the key and you want to get the values. I only need to use `b-dropdown` but how do I call `getURL` with that component?

**Comment by verilog15** [comment]
Can someone please point me to the right direction in order to achieve this behavior? 🙏 
Thanks in advance 😄

**Comment by tmorehouse** [comment]
What does `getURL` do?  does it return an array of options?

**Comment by verilog15** [comment]
@tmorehouse  No, as I said it returns a URL string. That URL contains an array of options. The method is as following:
```
getCustomsURL: function(param, custom) {
    var queryArray = [];
    // More logic
    return '/' + this.collection_name + '/params/' + param + '?' + queryArray.join('&');
}
```
For example it returns: `/my_db_collection/params/customs.value?customs.key=project`
For my previous example, the **URL** contains `[data]`.

**Comment by tmorehouse** [comment]
And what does the URL return when you call/get it?

**Comment by verilog15** [comment]
@tmorehouse I said, the URL contains an array `[data]`.
I'll explain the control flow again:
1. Assume we have a key `project`, we want to find all of the values for this key.
2. The method `getURL` gets executed, it returns a **string** that represents a URL of format `/my_db_collection/params/customs.value?customs.key=project`. This function does not return an array! it returns a URL (string).
3. The `url` attribute of `v-select` gets this URL (string), enters into this link and gets the data from that URL. The data that is saved in the URL is an **array** that contains all the values of they key. So for `project` we get `[data]`.

Hope it's more clear now 😄

**Comment by tmorehouse** [comment]
So `[data]` is a value displayed in the select dropdown?

i.e. when rendered as a select it would create:

```html
<select>
  <option>data</option>
</select>
```

**Comment by verilog15** [comment]
@tmorehouse Yes, it is shown in the image above. I'll post it again:

![image](https://user-images.githubusercontent.com/39248005/77452723-f18ea680-6dfe-11ea-8f14-afbed1d712c4.png)

**Comment by tmorehouse** [comment]
OK... what you need to do it use [`axios`](https://www.npmjs.com/package/axios) to fetch the result of `getURL` (when the URL changes, based on when you input changes), and then when passing that array as the `options` array on `<b-form-select>`.

You will probably want to debounce the input to prevent the axios get/fetch from being called on every keystroke in the text input.  `<b-form-input>` provides a debouncing feature.
