### ISSUE TITLE
Wrong output of <b-nav-form>

### ISSUE THREAD

**Issue by z0ng33** [bootstrap-vue/bootstrap-vue#4984]
### Describe the bug

`<b-nav-form>` wraps itself into `<li class="form-inline">`:

```html
<li class="form-inline">
    <form class="form-inline">
        <input type="text" placeholder="Search" class="mr-sm-2 form-control" id="__BVID__1023">
        <button type="submit" class="btn my-2 my-sm-0 btn-outline-success">Search</button>
    </form>
</li>
```

### Steps to reproduce the bug

1. Just add `<b-nav-form>` element into navbar.

### Expected behavior

Output without `<li>` element:

```html
<form class="form-inline">
    <input type="text" placeholder="Search" class="mr-sm-2 form-control" id="__BVID__1023">
    <button type="submit" class="btn my-2 my-sm-0 btn-outline-success">Search</button>
</form>
```

### Versions

**Libraries:**

- BootstrapVue: 2.7.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Comment by tmorehouse** [comment]
`<b-nav-form>` is a _child_ component of `<b-nav>` (or `<b-navbar-nav>`), and should be placed in a `<b-nav>` (or `<b-navbar-nav>`), and not as a direct descendant of `<b-navbar>`

**Comment by tmorehouse** [comment]
If you need a form as a direct descendant of `<b-navbar>` just use `<b-form inline>`

**Comment by z0ng33** [comment]
I just followed documentation of bootstrap-vue, and I got confused when I saw 2 nested elements with the same class `form-inline`, which are not in the official bootstrap documentation (first example for navbar). Thank you!
