### ISSUE TITLE
Possible to separate b-tab into tab and content?

### ISSUE THREAD

**Issue by marbuser** [bootstrap-vue/bootstrap-vue#4985]
I'm trying to wrap my tabs in a library called Draggable (https://github.com/SortableJS/Vue.Draggable), but from what I've read on the docs this doesn't really seem possible since there is no way for me to only wrap it around the tabs and not the content as well.

If this isn't possible currently can this be a feature request? Thanks!

**Comment by tmorehouse** [comment]
You can create your own tabs using `<b-nav>+<b-nav-item>` and `<b-card>`, as shown in the docs https://bootstrap-vue.js.org/docs/components/nav#card-integration

**Comment by marbuser** [comment]
@tmorehouse Thanks for the quick reply. However, I'm struggling to see how `b-nav` and `b-nav-item` have the same functionality as https://bootstrap-vue.js.org/docs/components/tabs/#tabs

It seems like `b-nav` and `b-nav-item` were made for URL changes, where as I'm just looking to make local tabs for something that doesn't communicate with a server and purely relies on a local array to render. So I'm not sure how to achieve this with `b-nav` and `b-nav-item` since it seems like they don't have this functionality to click and have something else render instantly like `b-tabs` does if that makes sense? Unless I'm missing something?

**Comment by Hiws** [comment]
@marbuser 
If you add `nav-class="d-none"` to your `b-tabs` it will hide the tabs nav, but still show the tab content.
Then you can create whatever you want that toggles the tabs by using the `b-tabs` v-model.

https://codepen.io/Hiws/pen/mdJGXJR
