### ISSUE TITLE
Bootstrap Vue dropdown creates a button without the data-v-XXX attribute

### ISSUE THREAD

**Issue by coolfarmer** [bootstrap-vue/bootstrap-vue#4986]
### Describe the bug
I am using Bootstrap Vue to create a dropdown but I can't apply scoped style on it because the main button is being created without the "data-v-XXX" attribute.

Is this normal? Everything else have a data-v-XXX attribute.

### Steps to reproduce the bug

Here is the code:
```
<b-nav-item-dropdown left id="notification-dropdown" no-caret>
	<template v-slot:button-content>
		<font-awesome-icon :icon="['fas', 'bell']"/>
		<b-badge variant="danger">2</b-badge>
	</template>

	<b-dropdown-group class="group">
		<b-dropdown-item>
			BLABLA
		</b-dropdown-item>
	</b-dropdown-group>
</b-nav-item-dropdown>
```

And the generated code (I though that the tag "a" with the id "notification-dropdown__BV_button_" should have receive the same data-v than his parent (data-v-d220bf30) :
```
<li data-v-d220bf30="" id="notification-dropdown" class="nav-item b-nav-dropdown dropdown" left="">
	<a id="notification-dropdown__BV_button_" aria-haspopup="true" aria-expanded="false" target="_self" href="#" class="nav-link dropdown-toggle dropdown-toggle-no-caret">
		<svg data-v-d220bf30 ... ></svg>
		<span data-v-d220bf30="" class="badge badge-danger">2</span>
	</a>
	
	<ul tabindex="-1" aria-labelledby="notification-dropdown__BV_button_" class="dropdown-menu">
		<li data-v-d220bf30="" role="presentation" class="group"><!---->
			<ul data-v-d220bf30="" role="group" class="list-unstyled">
				<li data-v-d220bf30="" role="presentation">
					<a role="menuitem" target="_self" href="#" class="dropdown-item">
                                            BLABLA
                                        </a>
				</li>
			</ul>
		</li>
	</ul>
</li>
```

### Versions

**Libraries:**

- BootstrapVue: 2.6.1
- Bootstrap: 4.3.1
- Vue: 2.6.11

I don't know if that is normal, if yes it would be nice to know why that behavior happen.

Thanks! :)

**Comment by tmorehouse** [comment]
Scoped style attributes (the `data-v-xxxx`) is only applied to the root element of components (or elements placed inside slots that are passed to the compnent).

See https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements for more details on this.

**Comment by coolfarmer** [comment]
/deep seems to fix my problem, thanks!
