### ISSUE TITLE
Layout automatically stacking on mobile

### ISSUE THREAD

**Issue by Ajiva-D** [bootstrap-vue/bootstrap-vue#4989]
### Breakpoint widths for mobile not working

.col-sm-6 and .col-sm-6 for example are not side by side. Instead they are stacking ontop of each other on mobile. On inspection, it seems the classes to make them half don't exist.

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: [ HP Laptop]
- OS: [ Windows 10]
- Browser: [Chrome]
- Version: [80]

**Comment by tmorehouse** [comment]
`sm` is screens larger than `576px` in width.  `xs` is typical mobile size (less than 576px).

`.col-sm-6` will occupy 6 columns on `sm` and up, and will be full width on screens smaller than `576px`

https://bootstrap-vue.js.org/docs/components/layout#grid-options

**Comment by Ajiva-D** [comment]
Okay, thanks!
