### ISSUE TITLE
Alt tag in new component Avatar

### ISSUE THREAD

**Issue by Ozkaa** [bootstrap-vue/bootstrap-vue#4990]
### Is your feature request related to a problem? Please describe...

There is no way to add an ALT tag to the new Avatar Component resulting in a lower SEO ranking when using :src or src attribute in the component

### Describe the solution you'd like

Please add :alt or alt in the Avatar component for images, like :src 

### Describe alternatives you've considered

I have added an alt tag in avatar component, but it adds it to the <span tag 

### Additional context

<img width="518" alt="avatar-component" src="https://user-images.githubusercontent.com/5662329/77335327-4d393100-6d26-11ea-8360-14d5b16dd1e0.png">

**Comment by Ozkaa** [comment]
@tmorehouse Thank you so much and keep up the great work, Bootstrap-Vue is AWESOME ! :-)

**Comment by tmorehouse** [comment]
@Ozkaa BootstrapVue v2.9.0 has been released.

**Comment by Ozkaa** [comment]
@tmorehouse Thank you so much, you guys rock!
Stay safe, Oscar
