### ISSUE TITLE
b-form-checkbox weird behavior

### ISSUE THREAD

**Issue by niksite** [bootstrap-vue/bootstrap-vue#4992]
### Describe the bug

In some cases, I've observed that one b-form-checkbox could affect nearby b-form-checkbox while not supposed to.

### Steps to reproduce the bug

1. Go to https://codesandbox.io/s/stoic-boyd-1ekqz
<img width="97" alt="image" src="https://user-images.githubusercontent.com/99423/77348681-1d266980-6cf7-11ea-8e4b-59b19ba9d3dd.png">
2. Click on `isA`
<img width="77" alt="image" src="https://user-images.githubusercontent.com/99423/77348717-2adbef00-6cf7-11ea-8f96-c9ab12d65c4c.png">
3. Click on `isB`
<img width="96" alt="image" src="https://user-images.githubusercontent.com/99423/77348740-329b9380-6cf7-11ea-8f21-d01cfda8670c.png">
4. Click on `isB` again
<img width="117" alt="image" src="https://user-images.githubusercontent.com/99423/77348757-3d562880-6cf7-11ea-924e-465b40867cda.png">

### Expected behavior

I expect `isA` to remain checked while in fact I see the `isA` become visually unchecked.

### Versions

**Libraries:**

- BootstrapVue: 2.8.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Safari
- Version: 13.1

**Comment by tmorehouse** [comment]
Try this: https://codesandbox.io/s/kind-glade-id1hp

Because of the `v-if`, and how Vue tries to re-use rendered dom, it is getting mixed up.

Adding a `key` to the `v-if` elements gets around Vue re-using existing DOM elements.

See https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key for more detail on this topic.

**Comment by niksite** [comment]
Thanks, it works! 

Would it make sense for `b-form-checkbox` to have some unique `key` by default? What do you think?

**Comment by tmorehouse** [comment]
The key has to be provided by the parent component (as it is rendered in that component's render context)
