### ISSUE TITLE
Form Datepicker: Infinite update loop in a component render function

### ISSUE THREAD

**Issue by m-demydiuk** [bootstrap-vue/bootstrap-vue#4999]
### Describe the bug

I need to wrap Form Date Picker in custom component and integrate with vee validate.

```html
<template>
  <validation-provider :rules="rules" v-slot="validationContext">
    <b-form-group :state="getValidationState(validationContext)">
      <b-input-group>
        <b-form-input
          :value="value"
          type="text"
          placeholder="dd-mm-yyyy"
          :state="getValidationState(validationContext)"
          @input="$emit('input', $event)"
        ></b-form-input>
        <b-input-group-append>
          <b-datepicker
            right
            start-weekday="1"
            button-only
            :value="pickerValue"
            @input="handlePickerValue"
          ></b-datepicker>
        </b-input-group-append>
      </b-input-group>
      <b-form-invalid-feedback>{{ validationContext.errors[0] }}</b-form-invalid-feedback>
    </b-form-group>
  </validation-provider>
</template>
```

```js
export default {
  name: 'ValidatableDatePicker',
  data: () => ({
    datePickerFormat: 'YYYY-MM-DD'
  }),
  props: {
    dateFormat: {
      type: String,
      default: 'DD-MM-YYYY'
    },
    rules: {
      type: Object | String,
      default: () => ({
        required: true,
        regex: /((0[1-9]|[12]\d|3[01])-(0[1-9]|1[0-2])-[12]\d{3})$/
      })
    },
    value: null
  },
  methods: {
    getValidationState({ dirty, validated, valid = null }) {
      return dirty || validated ? valid : null;
    },
    handlePickerValue(val) {
      const date = this.$moment(val, this.datePickerFormat).format(
        this.dateFormat
      );
      this.$emit('input', date);
    }
  },
  computed: {
    pickerValue() {
      return !this.value
        ? null
        : this.$moment(this.value, this.dateFormat).format(
            this.datePickerFormat
          );
    }
  }
};
```

This causes render infinite loop in the browser and browser hangs.
![image](https://user-images.githubusercontent.com/2910327/77408855-077d7680-6dc1-11ea-90f8-2cb93cc9c712.png)

It is not possible to set picker date format. 
Props.value format is `dd-mm-yyyy`.
So I need to convert it to `yyyy-mm-dd` before pass to the date picker. This is done in pickerValue computed property.
And also, when date is selected in picker, value should be converted from `yyyy-mm-dd` to `dd-mm-yyyy`. This is done in handlePickerValue function.

Nothing special, and this pattern is describe in vue documentation, and it works for my other components.
https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

### Expected behavior

It should work, and not cause infinite loop.

### Versions

**Libraries:**

- BootstrapVue: 2.8.0
- Bootstrap: 4.4.1
- Vue: 2.6.11
- VeeValidate: 3.2.5

**Environment:**

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: Latest

**Comment by tmorehouse** [comment]
You probably want to use standard v-model on Datepicker, and have an internal data value dedicated for the Datepicker v-model, and then use a computed prop to convert to desired format (use a watcher on the computed prop to emit `input`, and a watcher on your the prop `value` and format to YYYY-MM-DD and update the datepicker model when it changes.

**Comment by tmorehouse** [comment]
Here is a simplified example that uses a getter/setter computedProp to tanslate between the input format (DD-MM-YYYY format) to the format expected by the datepicker (YYYY-MM-DD)

https://jsfiddle.net/hz5kmynr/

In this case, I am just using a data value as the v-model of the input, and the computed prop as teh model for the datepicker.

You would need to add a watcher on the input model and emit your input event.
