### ISSUE TITLE
Interpolation inside component attribute

### ISSUE THREAD

**Issue by giacomocerquone** [bootstrap-vue/bootstrap-vue#500]
Hi everyone, thanks for the amazing work!
I have the following problem: I'm using the jumbotron component of this library inside a component activated by a dynamic route. So I should show the parameter of this route in the header of the jumbotron (and it's an attribute), but I can't show it because interpolation inside attribute has been removed.

I tried to do so: `v-bind:header="{{ $route.params.id }}"` and it doesn't work. What should I do?

**Comment by tmorehouse** [comment]
Have you just tried: `:header="$route.params.id"` without the mustaches?

**Comment by giacomocerquone** [comment]
Aaaaand it works! Thank you very much for the fast answer.

As of now I'm doing this (since I wanted to have text before the param):
` :header="'Query ' + $route.params.id"`
