### ISSUE TITLE
Bootstrap vue icon as class instead a tag

### ISSUE THREAD

**Issue by hgc2002** [bootstrap-vue/bootstrap-vue#5000]
Sometimes the icon I have to show is not known at compile time, but on runtime, but also you can't add components dynamically without loading them first and using a `<component :is='someComponent'>` tag, so this means that you already know all possible components before, which, in term of having hundreds of icons is not easy.

What I'm looking for is, having bootstrap-vue library already loaded into my project (and not wanting to load any more additional [overlapping!!!] icon library) a the way to show a bootstrap-vue icon as pure html/css code like 

`
<i class="v-icon-alarm"/>
`

and been able to set it dynamically at customer browser using simple javascript like

`
dom_object.inner_html = '<i class="v-icon-alarm"/>'
`

**Comment by Hiws** [comment]
This request might be more suited for the icon https://github.com/twbs/icons/issues repo.

Is there any reason you can't use the `b-icon` component and just dynamically change the `icon` prop in runtime?
Example:
https://codepen.io/Hiws/pen/eYNPgQB

**Comment by tmorehouse** [comment]
You just need to make sure you load the full icons plugin. (`BoootstrapVueIcons` or `IconsPlugin`) when the icon name is not known until runtime.

**Comment by tmorehouse** [comment]
@hgc2002 for reference:

- https://bootstrap-vue.js.org/docs/icons#icon-components
- https://bootstrap-vue.js.org/docs/icons#usage
