### ISSUE TITLE
b-modal spawns outside of mounted element

### ISSUE THREAD

**Issue by ioweb-gr** [bootstrap-vue/bootstrap-vue#5001]
### Describe the bug

I've created a modal and a button that triggers the modal. The problem is that the modal box div spawns before body-end instead of spawning inside the element where my app is mounted. 

### Steps to reproduce the bug

Create a component like this

```
<template lang="html">
    <div class="myclass" ref="main">
        <b-button @click="toggleModal" class="icon-toolbox">
            <b-icon-tools></b-icon-tools>
        </b-button>
        <b-modal scrollable centered dialog-class="myclass" :busy="true" size="xl" :id="modalId" :title="modalTopText">
            <p>my content</p>

            <template v-slot:modal-footer>
                <b-container fluid class="iglobal-actions">
                    <b-row>
                        <b-col cols="12">
                            <div class="row">
                                <b-button class="col-6 col-sm-3 btn btn-success">{{acceptButtonText}}
                                    <b-icon-check></b-icon-check>
                                </b-button>
                                <b-button class="col-6 col-sm-3 btn btn-danger">{{declineButtonText}}
                                    <b-icon-x></b-icon-x>
                                </b-button>
                                <b-button class="col-12 col-sm-3 btn btn-info">{{saveButtonText}}
                                    <b-icon-upload></b-icon-upload>
                                </b-button>
                            </div>
                        </b-col>
                    </b-row>
                </b-container>
            </template>
        </b-modal>
    </div>
</template>

```

Mount the element in a div e.g.  

`<div class="app-wrapper"><div id="myapp"></div></div>`

Trigger the modal 

Notice that the ___BV_modal_outer_ div is created outside of the mounted element and just before the end body tag. 

### Expected behavior

Everything is contained in the mounted element space. 

### Versions

    "bootstrap": "^4.4.1",
    "bootstrap-vue": "^2.7.0",
    "js-cookie": "^2.2.1",
    "lodash": "^4.17.15",
    "vue": "^2.6.11",
    "vue-i18n": "^8.15.5"

**Environment:**

- Windows 10 x64
- Browser: Firefox
- Version: 75.0b5 (64-bit)

### Additional context
This behaviour has certain implications when integrating in other applications. For example bootstrap-vue requires bootstrap in order for everything to work, however sometimes it's impossible to add the entire bootstrap framework in your core app because they're conflicting. 

In this case you can namespace bootstrap and include the styles under a specific class only to minimize the side-effects.

However the modal, since it's created outside of the mounted element, does not use the same css context  forcing us to integrate bootstrap into the entire app.

**Comment by Hiws** [comment]
@ioweb-gr 
This is default behavior. It's portal'd/rendered at the end of body.
If you don't want this behavior, and instead need to render it where it's placed in your component/document use the `static` prop.

https://bootstrap-vue.js.org/docs/components/modal/#lazy-loading-and-static-modals

**Comment by ioweb-gr** [comment]
Oh I missed that in the documents sorry. It seems it's exactly what I need. Thank you very much.

**Comment by tmorehouse** [comment]
Modals, even when portalled, should respect scoped styles (the modal root element will have the `data-v-xxxxx` scope attribute)

**Comment by Hiws** [comment]
I think the issue is that they're only including Bootstrap to a certain part of their application.

In the below case, the bootstrap styles are only available inside the div with the id `bootstrap-namespace`, so since the modal was being portaled outside of that div, it would have the bootstrap classes, but would receive any styling. Even if it has `data-v` applied.

```html
<body>
  <div>
    Some non-bootstrap content
    <div id="bootstrap-namespace">
      Some bootstrap content
    </div>
  </div>
  <!-- Modal will be portaled here -->
</body>

<style>
  #bootstrap-namespace {
    @import('bootstrap.css')
  }
</style>
```

**Comment by ioweb-gr** [comment]
Yes exactly as @Hiws says, it's very common practice to limit bootstrap in a part of your application for the grid capabilities or a few bootstrap structural elements that you need. But it's more like in your `app.scss` file you include the `bootstrap-component.scss` files that you need under the namespace element. I'm not sure if it would work by importing it in the scoped attributes. It would be fun to test 

Scoped styles seem to work for bootstrap-vue elements as @tmorehouse in custom components as long as you use the `/deep/` modifier in your custom components

**Comment by tmorehouse** [comment]
Perhaps:

```css
//app.scss
#boostrap-namespace /deep/ {
  @import('boostrap-component.scss')
}
```
