### ISSUE TITLE
DateTimePicker

### ISSUE THREAD

**Issue by csicky** [bootstrap-vue/bootstrap-vue#5002]
I was looking to replace the DateTimePicker `("vue2-datepicker": "2.13.2")` component with the DatePicker and TimePicker from here. However, it is not a comfortable thing to do. 
I was thinking to hook them up to the same `Date` object and let the user see them one next to the other, but DatePicker has a `Date` object and TimePicker a `string` as `value`.

Would be great if you would make the time picker to work also with a Date object as value, and for the future, would be even better to make one component to select both date and time.

**Comment by tmorehouse** [comment]
The problem with Date objects for time is when Daylight Savings starts and stops, and timezones (unless all times are returned in GMT), as the time portion could potentially push the date (when combined with datepicker) back or forward a day.

Once could use a computed prop that returns a date object combining the Datepicker and Timepicker values.  And one could also take a date object and split it into the two parts (date and time), and then set the individual models of Datepicker and Timepicker from those parts.

**Comment by csicky** [comment]
I will close this as an issue, it is not a problem in itself. I will create this combination now on my side. I just wanted to bring this up in your attention, so maybe you make a date time picker when you can concentrate the effort on it, if there is request for it.
