### ISSUE TITLE
bv::modal::show $root event fires faster than prop of nested object is set

### ISSUE THREAD

**Issue by Fubinator** [bootstrap-vue/bootstrap-vue#5005]
### Describe the bug

When you wrap a modal into a separate component and toggle the modal, the `this.$root.$on`-event seems to fire before the prop is updated. If i wait for 1 ms on my local machine, the prop seems to be set.

### Steps to reproduce the bug

1. Open Console
2. Click on Open Modal
3. It logs "BEFORE"

### Expected behavior

It should log "TEST" because i've set the new prop value before i fired the event

### Versions

**Libraries:**

- BootstrapVue: 2.8.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: PC
- OS: Arch Linux x64
- Browser: Chromium
- Version:  79.0.3945.130

### Demo link
https://codesandbox.io/s/damp-platform-wjovi

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
You are seeing the effects of Vue's reactivity render/event loop (the "tick").

Try this:

```js
  methods: {
    openModal() {
      this.test.prop = "TEST";
      // Allow time for Vue to update any reactive dependents
      // when changing the above data model
      this.$nextTick(() => {
        this.$bvModal.show("modal-1");
      }
    }
  }
```

**Comment by tmorehouse** [comment]
Side note, the root modal show event fires before the modal even starts to open (as it can be used to prevent the modal from opening)

**Comment by Fubinator** [comment]
Alright, thanks @tmorehouse !
