### ISSUE TITLE
Wizard Component

### ISSUE THREAD

**Issue by ricktate** [bootstrap-vue/bootstrap-vue#5017]
### Is your feature request related to a problem? Please describe...

My company uses several BootstrapVue Components, but recently implemented a custom Wizard UI that consists of a combo of the Bootstrap List Group component, Vue Dynamic Routing between list items, and Bootstrap Buttons for the "Previous" and "Next" standard wizard toggling. We tried using the Vertical Tabs but that wasn't exactly what we were looking for either. It would be awesome if someone created a standard BootstrapVue Wizard Component. 

### Describe the solution you'd like

I'd like to see a Wizard Component that offers: 
- Sequential steps with Previous and Next buttons. 
- Horizontal and vertical "step tracker". 
- Variant props for completed steps and Previous/Next buttons so teams can set their choice of color for indication of steps completed and buttons.
- Ability to render a different Vue Component within the container of each step.

### Describe alternatives you've considered

Please see the first paragraph for the current alternative we're using.

### Additional context

We're big fans of BootstrapVue and hope this suggestion helps the community solve their problems as well.

**Comment by ddweber** [comment]
Also requested a long time ago in #1484 ;)
