### ISSUE TITLE
Editable Grid Component

### ISSUE THREAD

**Issue by ricktate** [bootstrap-vue/bootstrap-vue#5018]
### Is your feature request related to a problem? Please describe...

Our users currently use the below Excel-like package for quickly adding data in small bulk chunks. This replaces the need for the to use Excel outside of our software platform. It also eliminates the need for us to implement a Bulk XLS Upload feature that used to constantly require our team to troubleshoot user error issues with spreadsheet formatting or invalid data entry.
Jexcel: https://bossanova.uk/jexcel/v3/examples/vue

### Describe the solution you'd like

This package addresses tons of our needs and has received the most praise from users of any other component we've implemented. I'd love to see this in BootstrapVue because I know others would use it and my team would rather use a BootstrapVue supported component.
https://bossanova.uk/jexcel/v3/examples/vue

### Describe alternatives you've considered

The hyperlink above and NPM excel uploader are the alternatives. Jexcel works but I really want the comfort of knowing that my component is supported by the BootstrapVue community.

**Comment by tmorehouse** [comment]
As long as the 3rd party components support Bootstrap v4.x CSS, or encapsulate it's styles in scoped CSS, you should be fine.

**Comment by ricktate** [comment]
Thanks @tmorehouse, we will look into styling the 3rd party component. Are you ok with keeping this ticket open as a feature request for a BootstrapVue editable grid/table component? 

Please let me know if BootstrapVue Components for inline or bulk editing of tables already exist.

**Comment by ricktate** [comment]
Commenting as this was marked as stale due to inactivity. Our team would still love to see this feature.
