### ISSUE TITLE
Click events not working and missing tabs - Nuxt generate

### ISSUE THREAD

**Issue by bc010101** [bootstrap-vue/bootstrap-vue#5019]
I'm using Nuxt and I've added boostrap-vue (per the Nuxt section instructions). Under localhost (npm run dev) the click events work and b-tab/b-tabs show. When I do _npm run generate_ nothing works except for css. Please help I'm rather new to Nuxt and how to get boostrap-vue working fully.

navbar-toggler event listeners: 
- localhost (npm run dev): click -> button.navbar-toggler webpack:///./node_modules/vue/dist/vue.runtime.esm.js?2b0e
- generate (npm run generate): click is not showing under event listener and tabs are missing.

**Comment by tmorehouse** [comment]
If loading the HTML files created by nuxt generate, you need to copy them to the root folder, as Nuxt creates references to the javascript as `/_nuxt/232d53c90813070008eb.js` (or similar).  You can see this at the bottom of the generated HTML files.

Nut assumes you are going to pace the contents of the `dist` folder (which includes the `_nuxt` directory) at the root of your web server.

**Comment by bc010101** [comment]
That makes sense. When I use netfliy the /_nuxt/ paths work correctly but it's the same outcome with the click events and tabs. Any thoughts?

**Comment by tmorehouse** [comment]
Are you including the full BootstrapVue plugin, or select plugins/components?

**Comment by bc010101** [comment]
I'm doing the full plugin currently.

**Comment by tmorehouse** [comment]
Strange then.   Perhaps you may need to clear your browser cache, or perhaps Netlify isn't detecting changes in the generated JS files.

In dev mode (`run dev`) Nuxt will use the pre-transpiled (/esm/*) files, while in prod mode (_nuxt generate_) it will use the `/src/*` files instead to generate smaller bundles.  This requires babel transpilation by Nuxt to occur...

Out of curiosity, you could try this:

```js
modules: [
  // Doc: https://bootstrap-vue.js.org
  'bootstrap-vue/nuxt',
  // ...
],
bootstrapVue: {
  usePretranspiled: true
}
```

Which will instruct Nuxt to _always_ use the pre-transpiled modules in `/esm/*`.  It will result in slightly larger bundles (due to repeated inclusion of some babel helpers).  If this works, then there might be some issue with the browserlist.rc that Nuxt is transpiling to.

**Comment by bc010101** [comment]
That's great. I'll look into this. Thanks!

**Comment by tmorehouse** [comment]
Also note that Nuxt generate will use the minified version of Vue (without vue dev tools integration enabled), as it is production mode.

**Comment by tmorehouse** [comment]
Also, when you load the page in question that is having issues, do you see any error in the console, or failed to load files (404's) in the network tab? (you might need to force reload the page to see the errors, if any)

**Comment by bc010101** [comment]
I addd usePretranspiled: true and ran on netlify but still having issues. No 404s in the network tab. I am seeing /_nuxt/759e89bbaf8841c6d626.js Uncaught TypeError: Expected parameter accessToken in the console but it's pulling from contentful still (data is populated)...

**Comment by bc010101** [comment]
OK, I've started fresh again with npx create-nuxt-app <project-name> and click even is now working on generate. Thanks for your help!

**Comment by tmorehouse** [comment]
@bc010101 so everything is working fine now?

**Comment by bc010101** [comment]
Yes, thanks! Sorry, I didn't see the response alert earlier.
