### ISSUE TITLE
Tree shaking for CSS

### ISSUE THREAD

**Issue by focussing** [bootstrap-vue/bootstrap-vue#5023]
According documentation three shaking only applies to the JavaScript code and not CSS/SCSS.
This means ending up with a lot of redundant stuff from bootstrap and bootstrap-vue (around 700kB).

Could tree shaking be implemented for CSS as well?

**Comment by Hiws** [comment]
I'm not sure how much of that CSS `Bootstrap-Vue` makes up for.

But you can treeshake Bootstrap to a degree by using `SCSS` and only importing the CSS for the components you use.

So let's say you only use the bootstrap Grid, Tables and Navbar.
You can then choose to only import that into your project like below.

```scss
// Required
@import "node_modules/bootstrap/scss/functions";
@import "node_modules/bootstrap/scss/variables";
@import "node_modules/bootstrap/scss/mixins";
@import "node_modules/bootstrap/scss/utilities";

// Import optional 
@import "node_modules/bootstrap/scss/grid";
@import "node_modules/bootstrap/scss/tables";
@import "node_modules/bootstrap/scss/navbar";
```

Reference: https://getbootstrap.com/docs/4.4/getting-started/theming/

**Comment by focussing** [comment]
@Hiws thank you, this is very helpful!
