### ISSUE TITLE
b-overlay option for no-wrap not working

### ISSUE THREAD

**Issue by tom31415** [bootstrap-vue/bootstrap-vue#5026]
### Description
on b-overlay setting the property "no-wrap" is not functioning, not even on the documentation example located at https://bootstrap-vue.js.org/docs/components/overlay/#non-wrapping-mode

### Steps to reproduce the bug
1. create a overlay using `<b-overlay></b-overlay>`
2. add 'no-wrap' propert so you now have `<b-overlay no-wrap></b-overlay>`

### Expected behavior
The default spinner should not be visible

### Versions
2.9.0
**Libraries:**

- BootstrapVue: 2.9.0
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: all
- OS: all
- Browser: Chrome

sample: https://bootstrap-vue.js.org/docs/components/overlay/#non-wrapping-mode

**Comment by tmorehouse** [comment]
You are misinterpreting the `no-wrap` functionality

The normal behaviour is to wrap the content of the default slot of `<b-overlay>` with a position relative `<div>`, which allows the inner absolutely positioned overlay backdrop to cover the content of `<b-overlay>`

The `no-wrap` option disables `position: relative` on the b-overlay root div, which then allows the absolutely positioned backdrop to cover an ancestor element that has relative or  absolute positioning.

`no-wrap` does not disable the default overlay spinner.  Use the `overlay` slot to replace the spinner.

**Comment by tom31415** [comment]
Thank you for the clarification.
