### ISSUE TITLE
b-card header-html doesn't work

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#5038]
### Describe the bug

According to
https://bootstrap-vue.js.org/docs/components/card/#comp-ref-b-card-header

this should render a card with header:
```
<b-card header-html='<b>strong</b> title'>
test
</b-card>
```

### Steps to reproduce the bug

1. see code above
2. result: card without a header

### Expected behavior

Render a card with header

### Versions

**Libraries:**

- BootstrapVue: 2.2.2
- Bootstrap: 4.4.1
- Vue: 2.6.11

### Additional context

I also tried ```headerHTML```, per
https://github.com/bootstrap-vue/bootstrap-vue/commit/3c6ba3e44de425120990f671436a7b163742b5cb
and
```headerHtml```, per
https://github.com/bootstrap-vue/bootstrap-vue/search?q=headerHTML&type=

None of these work.

```<div slot="header">...</div>``` does work.

Thanks

**Comment by Hiws** [comment]
Looks like both the `footer-html` and `header-html` tags require the `header` or `footer` props to be present before working.
Quite an odd bug.

The content placed inside the `header` or `footer` props will be overridden by their HTML counterparts.

This **wont** render the header or footer
```html
<b-card
        header-html="<b>strong</b> title" 
        footer-html="<b>strong</b> footer">
test
</b-card>
```

This **will** render the header or footer
```html
<b-card 
        header=" "
        footer=" "
        header-html="<b>strong</b> title" 
        footer-html="<b>strong</b> footer">
test
</b-card>
```
