### ISSUE TITLE
Tabs not fading

### ISSUE THREAD

**Issue by greeven** [bootstrap-vue/bootstrap-vue#504]
It is stated in the docs that fade is enabled by default but the tabs don't fade. This can be seen in the corresponding [docs page](https://bootstrap-vue.github.io/docs/components/tabs) itself.

Maybe something changed in bootstrap that broke the fading? (Is something like that even possible?)

**Comment by tmorehouse** [comment]
It appears there is a light difference in how tab panes are shown..  Bootstrap-vue is using `display: none;` to hide inactive tabs.  This isn't needed, as the default bootstrap css has the panes hidden by default. Although I am not sure if this is the culprit

**Comment by greeven** [comment]
I got bootstraps navs to work by not changing the classes to "show" and/or "active" but instead handling the active state via v-if.
```
<div class="tab-content">
    <transition name="fade">
        <div class="tab-pane active" v-if="activeItem==key" v-for="(item, key) in items" :key="key">
            {{ item }}
        </div>
    </transition>
</div>
```
The examples in the docs are all working with v-if. I'm not sure if switching a `display: block/none` class is even working with transitions.

**Comment by tmorehouse** [comment]
In the current implementation in BS-vue, the tab pane are v-if'ed if not lazy and v-show if lazy is true.

But the v-show isn't really needed since class `.tab-pane` by itself has `display:none` set.

**Comment by mosinve** [comment]
v-show needed as Vue transitions seems to fire when component v-if-ed or v-show-ed

**Comment by tmorehouse** [comment]
Now available in the .alpha and beta releases.
