### ISSUE TITLE
Paragraph content within a toast

### ISSUE THREAD

**Issue by leo95works** [bootstrap-vue/bootstrap-vue#5041]
Hello, I have just started using this project, it seems incredible to me, thank you very much for the excellent work you have accomplished. I have started testing the [toast component](https://bootstrap-vue.js.org/docs/components/toast), and have managed to display notifications, but when the notification body contains a lot of text, it is not displaying correctly. What I've got as a result so far is the following:

![image](https://user-images.githubusercontent.com/60673955/77860789-1e680280-71df-11ea-81f9-a436eb4705ae.png)

 The string shown there is very long, but I cannot show it in several lines. How could I solve this problem? Thank you very much in advance.

**Comment by tmorehouse** [comment]
You might need to set `body-class` (if using the component), or property `bodyClass` (if using `this.$bvToast`) to the utility class  `text-break`

Which will "break" long "words"

**Comment by leo95works** [comment]
Oh! great .. now it works .. thank you very much
