### ISSUE TITLE
Dropdown boundary="window" fails within table header when sticky-header set.

### ISSUE THREAD

**Issue by dflock** [bootstrap-vue/bootstrap-vue#5047]
This is pretty similar to #3563 - basically, that bug comes back if you have `sticky-header` set on the table. It's really noticeable when the dropdown is longer than the table. The dropdown menu clips inside the table area, which gets a vertical scrollar when the dropdown appears:

![image](https://user-images.githubusercontent.com/47756/77966989-081e7d00-7299-11ea-829e-ceec7d3ba958.png)

But it happens even if the table is longer - note that the top of the dropdown is clipped when it goes outside the first column:

![image](https://user-images.githubusercontent.com/47756/77967043-21bfc480-7299-11ea-9eba-146be52ceb7b.png)

### Expected behavior

If you set the boundary to `window`, I would expect the dropdown to be placed above the table content and not be clipped within the table area.

### Versions

**Libraries:**

- BootstrapVue: 2.5.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Desktop Workstation
- OS: Ubuntu Linux
- Browser: Chrome
- Version: 82.0.4085.12 (Official Build) dev (64-bit)

### Demo link

https://jsfiddle.net/yjh712sk/1/

**Comment by tmorehouse** [comment]
This has to do with relative positioning on the sticky-header/responsive wrapper, and the scrollable body

You might need to wrap your dropdown in a `class="position-static"` wrapper div.

Does setting boundary to `viewport` make any difference?

Popper V2 is supposed  to handle this situation better... we are slowly getting it ready yo migrate to.

**Comment by dflock** [comment]
> Does setting boundary to viewport make any difference?

No.

> You might need to wrap your dropdown in a class="position-static" wrapper div.

This doesn't seem to help either, sadly. I fiddled around with positioning on various elements in lots of combinations, to no avail.

**Comment by tmorehouse** [comment]
Maybe set overflow: visible? although that will affect sticky headers

**Comment by dflock** [comment]
> Maybe set overflow: visible? although that will affect sticky headers

Not sure where to apply that, so I tried various places, to no avail.

Best I could come up as a workaround, was to not use sticky headers where the list is likely to be shorter than the menu:

```vue
:sticky-header="totalItems < 10 ? null : stickyHeader"
```

That'll do for me, for now.

**Comment by dflock** [comment]
> Maybe set overflow: visible? although that will affect sticky headers

Not sure where to apply that, so I tried various places, to no avail.

Best I could come up as a workaround, was to not use sticky headers where the list is likely to be shorter than the menu:

```vue
:sticky-header="totalItems < 10 ? null : stickyHeader"
```

That'll do for me, for now.

**Comment by dflock** [comment]
> Maybe set overflow: visible? although that will affect sticky headers

Not sure where to apply that, so I tried various places, to no avail.

Best I could come up as a workaround, was to not use sticky headers where the list is likely to be shorter than the menu:

```vue
:sticky-header="totalItems < 10 ? null : stickyHeader"
```

That'll do for me, for now.

**Comment by dflock** [comment]
Not sure what details @jackmu95 would like to see here - there's already a demo link that replicates the issue?
