### ISSUE TITLE
table custom header 

### ISSUE THREAD

**Issue by neildchen** [bootstrap-vue/bootstrap-vue#505]
I am sorry if I am asking in a wrong place... I am at my very beginning with vue, and I have browsed all issues and I couldn't find an answer.... Thanks in advance if any tips.

This is what I want to do, to place a checkbox in the table header so that it can be used to toggle select all / unselect all:

![2017-06-15_how_to_add_a_cb](https://user-images.githubusercontent.com/8392135/27175324-673317cc-51f1-11e7-893c-d968beff9008.PNG)

I tried to put the following in the field json:

```myfields: {
        cbSelected: {
          label: `<span><b-form-checkbox v-model="selectAll" value="checked" unchecked-value="unchecked">All / 全選
        </b-form-checkbox></span>`
        },
...
```

obviously it is not working as I thought it would, but you can tell that the 'All / 全選' string does get printed out on web (just not the checkbox)

hmmm. can you help me to get a checkbox shown beside the tag string? Thank you so much.

**Comment by neildchen** [comment]
just talked to my supervisor and he suggested give this a try:

```
 myfields: {
        cbSelected: {
          label: `<span><input type="checkbox" v-model="selectAll" value="checked" unchecked-value="unchecked" /w>All / 全選
        </span>`
        },
...
```
Here is the outcome:

![2017-06-15_how_to_add_a_cb_2](https://user-images.githubusercontent.com/8392135/27177299-7272ec8c-51f8-11e7-82b8-a05e048e1be8.PNG)

well, it works, but I like `<b-form-checkbox></b-form-checkbox>` more....

any ideas? thank you.

**Comment by tmorehouse** [comment]
Checkout PR #460 

Which allows for custom formatted scoped slots for header (and footers)

**Comment by neildchen** [comment]
Yeah! Thank you! Can't wait to try it out.

**Comment by tmorehouse** [comment]
Latest master now has the new features via PR #460

**Comment by neildchen** [comment]
Thanks for the note. I will try it out and come back if any questions. Thank you.

**Comment by tmorehouse** [comment]
You can check the latest master docs out at https://github.com/bootstrap-vue/bootstrap-vue/blob/master/docs/components/table/README.md

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
