### ISSUE TITLE
Pagination - first and last page do not show next and previous page links

### ISSUE THREAD

**Issue by b-zee** [bootstrap-vue/bootstrap-vue#506]
When either on the first or last page when paginating, the next or previous page link is not visible.

When on page 1, page link to page 2 is not there, for example:
![image](https://user-images.githubusercontent.com/6576760/27176753-24ebe1a0-51c4-11e7-82ea-eb125405653e.png)

Same case for last page:
![image](https://user-images.githubusercontent.com/6576760/27176790-448c482e-51c4-11e7-930f-1d9ed3e45ff2.png)

This seems confusing, as you'd expect the behaviour to be similar through all pages. Like in this scenario:
![image](https://user-images.githubusercontent.com/6576760/27177192-c9963b32-51c5-11e7-9d50-592e0c055f6a.png)

**Comment by tmorehouse** [comment]
Depending on you screen size, some buttons will be "hidden". (i.e. on small mobile screens)

You can also set a limit (`limit` prop on the pagination component) on the maximum number of buttons shown (i.e. set it to 12 in the example above)

**Comment by b-zee** [comment]
The examples shown are on a `lg` viewport.

The `limit` prop is static. I would say a `limit` above 20 is not ever practical either. So with a dynamic amount of pages, or with an amount of pages above 20, the pagination does not work correctly.

Also, with setting a limit, the pagination will break too, e.g. with a limit of 4:
![image](https://user-images.githubusercontent.com/6576760/27186958-36d78a2e-51ea-11e7-86f1-178cb6b262c8.png)

As you can see the first page (1) is not shown (again on `lg`).

**Comment by tmorehouse** [comment]
the `<<` links to the first page in the above.

**Comment by tmorehouse** [comment]
There is a lot of weirdness in how the pagination buttons are rendered.  We're hoping to work on this before release 0.17.0 comes out.

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
