### ISSUE TITLE
caret-up/down icons does not work

### ISSUE THREAD

**Issue by Fream** [bootstrap-vue/bootstrap-vue#5062]
### Describe the bug

Alot of icons does not work when using bootstrap-vue.
For example:
<b-icon icon="caret-down"></b-icon> - does not work, any icon "caret" does not work and shows nothing

But other icons like "cursor" works fine 

### Steps to reproduce the bug
Try to display b-icon icon="caret-down" icon

### Expected behavior

Caret icon should be displayed

### Versions

**Libraries:**

- BootstrapVue: 2.6.1
- Bootstrap: 4.4.1
- Vue: 2.5.17

**Comment by tmorehouse** [comment]
Upgrade bootstrap Vue to 2.9.0, when the new icons were introduced and some names were changed by Bootstrap Icons alpha.3
