### ISSUE TITLE
b-table ctx.currentPage is always equal to ctx.page

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue/bootstrap-vue#5065]
### Describe the bug

1. b-table with provider function.
2. set current-page property to 1
3. set per-page property to 15

ctx object in provider function gives currentPage = 15

### Versions

**Libraries:**

- BootstrapVue: 2.10.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: PC
- OS: Linux
- Browser:  Chrome, Firefox latest

### Additional context

BootstrapVue: 2.9.0 works fine

**Comment by tmorehouse** [comment]
@makroxyz BootstrapVue `v2.10.1` has been released with the fix.
