### ISSUE TITLE
b-buttons with wrapper element inside b-input-group slots not styled properly

### ISSUE THREAD

**Issue by ddweber** [bootstrap-vue/bootstrap-vue#5066]
### Describe the bug

I´m using `b-button` inside of a `b-input-group` append `slot`. This button has to be wrapped in an element which uses the `v-b-tooltip` directive (to prevent tooltips stay open when button is disabled).
But when i put the button in the wrapper element the button does not get styled properly.

![image](https://user-images.githubusercontent.com/33422037/78223985-0be41680-74c8-11ea-82dc-4853b6ebe80f.png)

### Steps to reproduce the bug

Use this in markup in playground or so:
```html
<div>
  <!-- Using slots -->
  <b-input-group class="mt-3" size="sm">
    <template v-slot:append>
      <div v-b-tooltip="'Hello'">
          <b-button disabled variant="danger">I´m not styled properly</b-button>
      </div>
    </template>
    <b-form-input></b-form-input>

  </b-input-group>
  <b-input-group class="mt-3" size="sm">
    <template v-slot:append>
          <b-button disabled variant="success">I´m ok</b-button>
    </template>
    <b-form-input></b-form-input>
  </b-input-group>
</div>
```

### Expected behavior

Button is styled properly.

**Comment by Hiws** [comment]
This is an issue with bootstrap's CSS.
Input group's look at direct children. Like `.input-group>.input-group-append>.btn`, which wont style any children if they're nested like you have.

Your best bet might be to manually style it accordingly.


```html
<b-input-group class="mt-3" size="sm">
  <template v-slot:append>
      <div v-b-tooltip="'Hello'">
        <!-- Add 'size="sm" and our custom class 'rounded-left-0' to fix the styling -->
        <b-button disabled variant="danger" size="sm" class="rounded-left-0">
          I´m not styled properly
        </b-button>
      </div>
    </template>
  <b-form-input></b-form-input>
</b-input-group>

<style>
.rounded-left-0 {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
</style>
```

**Comment by tmorehouse** [comment]
The other option is to use the input group child components, and not to use the append slot:

```html
<b-input-group class="mt-3" size="sm">
  <b-form-input></b-form-input>
  <b-input-group v-b-tooltip="'Hello'">
    <b-button disabled variant="danger">
      Disabled Button
    </b-button>
  </b-input-group-append>
</b-input-group>
```
