### ISSUE TITLE
b-modal is mounted all the time

### ISSUE THREAD

**Issue by m-demydiuk** [bootstrap-vue/bootstrap-vue#5069]
### Is your feature request related to a problem? Please describe...

I have b-modal on the page. b-modal has property v-model="show" and b-modal is shown when related button is clicked. The problem is that b-modal got render, created and mounted, even if button was not clicked. It causes to specific api calls from modal to load modal content.  Also, computed properties got evaluated and watch got evaluated.

I think b-modal should be added to the dom only when it is called.

### Describe the solution you'd like

I am thinking to wrap each b-modal in `<template v-if="show">` to prevent rendering b-modal at all. But for me it is very bad solution. 

This may be similar to #3969 but I am curious, why b-modal is not wrapped in the parent element out of the box. Are there any constraints, so you can't wrap b-modal and use v-if, and make it real lazy?

**Comment by Hiws** [comment]
Have you thought about using the suggested solution in the related issue you posted?

Instead of hooking your API call to the modals `mounted` hook. 
Hook it up to the `show` or `shown` events on the modal?

**Comment by m-demydiuk** [comment]
In my case, the problem is next. I have a modal with small form, that loads data depending on form values. When a page is loaded - b-modal `created` and `mounted` hooks are called, after that its computed properties start to evaluate, after that watchers (that watch computed properties) start to execute. Watchers start to load data. Data fails to load, because form fields are not set, so errors are shown.

**Comment by tmorehouse** [comment]
Try using the `static` prop (`<b-modal static v-model="show" ...>`), which will always have the modal in DOM
