### ISSUE TITLE
Pagination - Styling strongly disconnected from documented styling

### ISSUE THREAD

**Issue by b-zee** [bootstrap-vue/bootstrap-vue#507]
BootstrapVue uses buttons instead of anchor elements, which are documented by Bootstrap 4.

BootstrapVue (from [documentation](https://bootstrap-vue.github.io/docs/components/pagination/)):
![image](https://user-images.githubusercontent.com/6576760/27176936-ea2c284e-51c4-11e7-99ed-16ab0e19ea82.png)

Bootstrap 4 (from [documentation#Pagination)](https://v4-alpha.getbootstrap.com/components/pagination/#disabled-and-active-states):
![image](https://user-images.githubusercontent.com/6576760/27176941-f1362bf8-51c4-11e7-9cf7-91d3a2d334bb.png)

I'd expect the styling to be largely similar to the official Bootstrap documentation.

**Comment by tmorehouse** [comment]
The current master has aligned with BS4 buttons.  This will be available in next release.
