### ISSUE TITLE
b-table headers with stacked are unselectable

### ISSUE THREAD

**Issue by yulObraz** [bootstrap-vue/bootstrap-vue#5070]
### Describe the bug

Stacked table looks good, but when one tries to copy data from it it does not copy headers with  data.

I received such copy in a notepad:
21
Larsen
Shaw

Its a bad enduser experience.

### Steps to reproduce the bug

1. Go to [https://bootstrap-vue.js.org/docs/components/table#stacked-tables](https://bootstrap-vue.js.org/docs/components/table#stacked-tables) 
2. Scroll down to Example: Always stacked table
3. Select table data and copy

### Expected behavior
Age 21
First Name Larsen
Last Name Shaw
### Versions

**Libraries:**

Current demo
- BootstrapVue: 2.10.0

**Environment:**

- Browser: Chrome

**Comment by tmorehouse** [comment]
This is a caveat of the table headers being made "position: sticky", which the browser moves them "out" of the table.
