### ISSUE TITLE
b-avatar button border size is too big when avatar size is set

### ISSUE THREAD

**Issue by m-demydiuk** [bootstrap-vue/bootstrap-vue#5073]
### Describe the bug

I have b-avatar button with size set to 150px
`<b-avatar button @click="change" :src="currentUserImage" size="150px"></b-avatar>`

And it looks tooo odd:
![image](https://user-images.githubusercontent.com/2910327/78269251-03183280-7512-11ea-8d92-7254300dc3e7.png)

Why avatar border is increased?

BTW, when avatar is in normal mode (not button), it looks ok:
![image](https://user-images.githubusercontent.com/2910327/78269215-f5fb4380-7511-11ea-8811-2894a672199b.png)

**Comment by tmorehouse** [comment]
Ah, we'll need to override the button padding.  For now you can do this:

```html
<b-avatar button @click="change" :src="currentUserImage" size="150px" class="p-0"></b-avatar>
```

**Comment by tmorehouse** [comment]
@m-demydiuk BootstrapVue `v2.10.1` has been released with the fix.
