### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by leo95works** [bootstrap-vue/bootstrap-vue#5074]
Hello, I have been using this project for a few days and as I said earlier ... I think I have done an excellent job. I am extremely new to Vue.js, I have just started a project and I have decided to use this project since I have experience with Bootstrap. I am using Laravel.. I have been organizing the structure of my project, and I find the following problem:

Let's say I have 2 very basic components
```
1-Navbar
2-Confirmation
```

***Navbar***
```
(js/components/NavBar.vue)

<template>
  <div>
    <b-navbar type="light" variant="light" class="border-bottom">
      <b-collapse id="nav-collapse" is-nav>
        <b-navbar-nav class="ml-auto">
          <b-nav-item-dropdown right>
            <template v-slot:button-content>
              User
            </template>
            <b-dropdown-item href="#" @click="logout">
             Logout
            </b-dropdown-item>
          </b-nav-item-dropdown>
        </b-navbar-nav>
      </b-collapse>
    </b-navbar>
  </div>
</template>

<script>
export default {
  name: 'NavBar',
  methods: {
    async logout() {

    }
  }
};
</script>

<style scoped>

</style>
```

***Confirmation***
```
(js/components/Confirmation.vue)

<template>
  <b-modal>
    Confirmation Body
  </b-modal>
</template>

<script>
export default {
  name: 'Confirmation',
};
</script>

<style scoped>

</style>
```

How can I make the confirmation message that I am going to configure in the ```Confirmation``` component from the ```NavBar``` component. I would like to call it as follows:

```
... NavBar
<script>
export default {
  name: 'NavBar',
  methods: {
    async logout() {
       confirmation({ pass config here });
    }
  }
};
</script>
```

I want to have a global method that allows me to launch a confirmation message from anywhere in my application. That it uses the template that I have in ```Confirmation.vue``` with some pre-established parameters and that allows me to pass an object with the configurations that I want to overwrite in that component.

For example, I want confirmations to be named Confirmation by default, but if I call the confirmation method with a parameter called ```title```, I want the confirmation to display with that title.

Like:
```
confirmation({
    title: 'Title'
});
```

***What have I done?***

Inside my project I have created a ```mixins``` directory and inside this directory I have created a file called ```confirmation.js``` with the following content:

```
(js/mixins/confirmation.js)

import Vue from 'vue';

export function confirmation(opts = {}) {
  const vm = new Vue();

  vm.$bvModal.msgBoxConfirm(opts);
}

```

so I import it into my ```NavBar``` component and call it, but I don't know how, to tell it to use the ```Confirmation.vue``` component as a template file.

```
(js/components/NavBar.vue)

<script>

import {confirmation} from '~/mixins/confirmation';

export default {
  name: 'NavBar',
  methods: {
    async logout() {
        confirmation({
            title: 'Example Confirmation
        });
    }
  }
};
</script>
```

Please if you could help me with this problem I would appreciate it. Thank you very much in advance

**Comment by tmorehouse** [comment]
See the modal message boxes: https://bootstrap-vue.js.org/docs/components/modal#modal-message-boxes

**Comment by leo95works** [comment]
Hi, sorry for not responding earlier, I have been away from my computer for a few days. I have read the documentation but cannot find a solution to my problem. What I have tried so far is the following:

I have created a ```classes``` directory on the ```src``` path

**/src/classes/MessageBox.js**
```
import Vue from 'vue';

export default class MessageBox extends Vue {
  static confirmation() {
    const vm = new Vue();

    vm.$bvModal.msgBoxConfirm('Sure?');
  }

  static information() {
    const vm = new Vue();

    vm.$bvModal.msgBoxOk('Information');
  }
}

```

This allows me to use these methods inside and outside of Vue components as follows:

```
import MessageBox from '~/classes/MessageBox';

MessageBox.confirmation();
```

Is this really the most practical way to achieve the result you expect?

**Comment by tmorehouse** [comment]
The major issue with the above is that your `vm` has no `$parent` or `$root`, and does not share events between other modals, tooltips, and dropdowns (tooltps/popovers/dropdowns listen for `$root` events from modal to close themselves when the modal starts to close)

It is best to use `this.$bvModal.msgBoxOk()` (etc) to ensure the proper event management is set up in your app.

**Comment by leo95works** [comment]
Hello, @tmorehouse , thanks for interested in my question, you mean use it as follows?:

```
import Vue from 'vue';

export default class MessageBox extends Vue {
  static information() {
      this.$bvModal.msgBoxOk('Info');
  }
}
```

**Comment by MaurizioRicci** [comment]
I would suggest to use the Vue event bus. I mean you send a particular event let's say 'launchConfirmatiotion' with some args to your App.vue (which is the global component container by default). Then App.vue when it creates register a listener for that particular event and inside his template he have the modal for the confirmation. I did something very similar with a modal which displays text.
