### ISSUE TITLE
Pagination - Ellipsis while no pages in between

### ISSUE THREAD

**Issue by b-zee** [bootstrap-vue/bootstrap-vue#508]
In the following scenario, ellipsis are shown between the page links of 1 and 2:
![image](https://user-images.githubusercontent.com/6576760/27177040-585a2456-51c5-11e7-9ef1-20a5ae59bbd1.png)

There should be no ellipsis, as it makes one think there is a page in between.

**Comment by tmorehouse** [comment]
Yeah, there is a lot of weirdness in how the pagination buttons are rendered.  We're hoping to work on this before release 0.17.0 comes out.

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
