### ISSUE TITLE
Year and month pick for new Date Picker

### ISSUE THREAD

**Issue by JayanUd** [bootstrap-vue/bootstrap-vue#5084]
There is a usability issue in the new Datepicker control as it doesnt allow to select month or the year seperately. This results in applying a lot of clicks to go up or down for months and years. It would be ideal to have some method like drop downs to select year and month, so that it would become very convenient to select years way in the past and in future.

**Comment by mariusa** [comment]
The problem is correct, but I don't agree with the solution. Cons:
1. It still requires many clicks
2. It would complicate the control too much. 
Look at https://bootstrap-vue.js.org/docs/components/form-timepicker/ , we find it worse than the native ```input type="time"```, as one can simply enter the time AND use the small non-intrusive up/down controls to change hour/minute/AM.

This would be a better solution: https://github.com/bootstrap-vue/bootstrap-vue/issues/5087

**Comment by tmorehouse** [comment]
Related: #4976

**Comment by JayanUd** [comment]
Hi!
Yes I agree it will complicate the control a bit with addition of 2
dropdowns for year and month.
But I cant agree about number of clicks. Because then its two clicks to
select a month instead of 6 in worst case, and 2 clicks to select year
against 50 when some one 50 years old is going to enter a birthday :D
You can calculate the number of click saving here.
Thanks!
BR

**Comment by mariusa** [comment]
Let users type. We have this invention called keyboard. Not everything has to be click-only.

**Comment by tmorehouse** [comment]
Which, as I have mentioned before, you can do so as shown in this example in the docs: https://bootstrap-vue.js.org/docs/components/form-datepicker#button-only-mode

**Comment by JayanUd** [comment]
Hi!
Sure it is one solution :)
But we have this specific requirement and we cant decide our selves about
which way to use it. The end user thinks they dont need to type by any
means.
I wonder why its so difficult to implement this suggested option and let
the developers switch it through some prop option like simple or complex
mode.
We are helpless but if this option is not in the queue, we might need to
find another solution. Still we like to use this control as it looks nice
and works nicely with vuelidate :)

Thanks and regards!

**Comment by tmorehouse** [comment]
@JayanUd see https://github.com/bootstrap-vue/bootstrap-vue/issues/4976#issuecomment-608454941

**Comment by JayanUd** [comment]
Hi!
I think I'll give up here and look for some other solution :) there must be
your reasons to stick to this curent solution, I can understand it. But
unfortunately We cant use the solution you proposed as well.

Thanks and regards@

**Comment by tmorehouse** [comment]
The reasoning is making it WAI-ARIA accessible, and codebase size to handle all of the special cases.  That is what happened to `<b-table>`... all these features people wanted for specific use-cases, and now it is close to 1/4 of our codebase, and becoming a nightmare A11Y-wise to maintain.
