### ISSUE TITLE
b-form-datepicker doesn't work with @change

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#5085]
### Describe the bug

All form controls emit a change event, but not the datepicker / timepicker.

### Steps to reproduce the bug

```
 <b-form-datepicker
                                    v-model="item"
                                    required
                                    @change="dateChange"
                                ></b-form-datepicker>
...

        dateChange() {
            console.log('dateChange', this.item)
        }
```
### Expected behavior

Have 'dateChange' method triggered when date changes

### Versions

- BootstrapVue: 2.10.1
- Bootstrap: 4.4.1
- Vue: 2.6.11

### Demo link

https://codepen.io/mariuscode/pen/zYGQBNW?editable=true&editors=101_.

### Additional context

https://bootstrap-vue.js.org/docs/components/form-timepicker/ also doesn't seem to support ```@change```

**Comment by Hiws** [comment]
You can use the `@input` event instead, or add a watch method to your `item` property

**Comment by mariusa** [comment]
Thanks, Hiws! That does work.
However, to be consistent with all other inputs, could ```@change``` support be added as well?

**Comment by tmorehouse** [comment]
`change` and `input` would end up being the same event... as they would be triggered by the same user interaction.

**Comment by mariusa** [comment]
Found this explanation at https://vuejs.org/v2/guide/forms.html

v-model internally uses different properties and emits different events for different input elements:
* text and textarea elements use value property and input event;
* checkboxes and radiobuttons use checked property and change event;
* select fields use value as a prop and change as an event.

So ```input``` makes sense for this control. Thanks!
