### ISSUE TITLE
b-form-datepicker support for manual date input, if enabled via property

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#5087]
### Is your feature request related to a problem? Please describe...

b-form-datepicker works great for picking dates around today.
However, some dates are way in the past, eg birth day. It is too cumbersome to navigate to a specific day using the calendar month/year next/prev.

### Describe the solution you'd like

![Screenshot from 2020-04-03 14-48-32](https://user-images.githubusercontent.com/1283842/78368169-dfb1be00-75cb-11ea-823c-1ba49970a262.png)

The box at the top should be an input field. Now it simply repeats the information already visible both in calendar and the datepicker field (when calendar is closed).
Maybe the input format could be customized (YYYY-MM-DD vs DD.MM.YY)

Please do not add up/down arrows for day/month/year, leave as a simple text input. 

Thanks!

**Comment by mariusa** [comment]
![Screenshot from 2020-04-03 14-48-32](https://user-images.githubusercontent.com/1283842/78357713-97d66b00-75ba-11ea-8808-eef74459196f.png)

The box at the top should be an input field. Now it simply repeats the information already visible both in calendar and the datepicker field (when calendar is closed).

Please do not add up/down arrows for day/month/year, leave as a simple text input. Maybe the input format could be customized (YYYY-MM-DD vs DD.MM.YY)

**Comment by tmorehouse** [comment]
Related: #4976 

We will be adding skip back/forward by decade (+/-10 years) in the date navigation toolbar section.

Note you can use button only mode, and place the datepicker in an input group, and link to an input field where the user can alternatively enter the date in the format.  The top date showing at the top is mainly for accessibility, to read out the full date in human format.  It can be visually hidden with the `hide-header` prop (but still present for screen reader users as an aria-live region)

**Comment by peetboy** [comment]
I would also appreciate either input for quick enter of date value or quick selector for month and year. Similarly like on many other UI frameworks. 
Why not following material design spec?
https://material.io/components/pickers#desktop-pickers

**Comment by tmorehouse** [comment]
@peetboy 

Screen readers use the date header at the top to announce the selected date when the date changes (and when the date picker is opened, and to also announce when no date is selected).  

Note that one can disable the closing on clicking of a date ([via the `no-close-on-select` prop](https://bootstrap-vue.js.org/docs/components/form-datepicker#optional-controls)), and one can visually hide the "header" on the calendar [via the `hide-header` prop](https://bootstrap-vue.js.org/docs/components/form-datepicker#comp-ref-b-form-datepicker-props).

**Comment by tmorehouse** [comment]
Note the Material Vuetify datepicker requires the author to bind the datepicker to an input.  Similar to how we offer the button only mode, which the user can bind (either directly or indirectly) to an input.  The user can then use what ever library they like to parse the user supplied date (i.e. days.js or moment.js)

**Comment by peetboy** [comment]
@tmorehouse Thanks for your reply. I will try button-only mode. But still...

I understand that accessibility is no longer considered as a "nice to have" but basic feature, but what I don't understand is why it should dictate the UX for the majority of users (without any disability).
Re the top box - I really don't get how it works in reality. Let's assume disabled person (blind) has to fill in the form (or has open prefilled form) . The picker is either empty or has some date. If it's empty then screen reader reads "no value selected" and if it's already filled then screen reads the value in a picker. The picker is closed and the value is read from the closed picker. User is not forced to open picker to read the date, right? The only option when he needs to open picker is when he wants to change the value. When picker is open, he will probably navigate using arrow keys to select different date but date value is not changing in the header. How does screen reader knows what to read to user? How the user knows which date he picked? Is it a bug? Also when he picks date with mouse (or pressing space) the picker will immediately close so which value is read to user? Again it's value from closed picker, not from the header of open picker. IDK but to me it looks like the header is not used that much or perhaps it's just me not understanding how screen readers work?

Re material design - you can inspire for the year selection at least. I saw in other thread that people asked for better/quicker selection of the year and month. I think the idea of having clickable year which opens range of years is very common in date pickers these days.

**Comment by mariusa** [comment]
Maybe date parsing can be avoided by using `input type="date"` and let the browser parse it?

**Comment by peetboy** [comment]
Using button-mode doesn't work for my requirement which is - to be able manually enter date in short (GB locale) format dd/MM/yyyy. Setting `:date-format-options="{ year: 'numeric', month: 'numeric', day: 'numeric' }"` for `<b-form-datepicker>` works only for display value but doesn't work opposite way. Perhaps some formatter between input and datepicker would help.

**Comment by tmorehouse** [comment]
@peetboy

> Using button-mode doesn't work for my requirement which is - to be able manually enter date in short (GB locale) format dd/MM/yyyy. Setting :date-format-options="{ year: 'numeric', month: 'numeric', day: 'numeric' }" for <b-form-datepicker> works only for display value but doesn't work opposite way. Perhaps some formatter between input and datepicker would help.

That is why I suggested using a library such as [days.js](https://github.com/iamkun/dayjs) or [moment.js](https://github.com/moment/moment) to handle parsing.  Currently the browser `Intl` does not handle _parsing_ of arbitrary locale date strings... 

Note the b-form-datepicker returns a date string value in the format of `YYYY-MM-DD` (the _identical format_ returned by a native HTML5 date input), or optionally a Date object instance.

Re:

> the only option when he needs to open picker is when he wants to change the value. When picker is open, he will probably navigate using arrow keys to select different date but date value is not changing in the header. How does screen reader knows what to read to user? How the user knows which date he picked? Is it a bug? Also when he picks date with mouse (or pressing space) the picker will immediately close so which value is read to user? I assume it reads value from closed picker, not from the header of open picker. IDK but to me it looks like the header is not used that much or perhaps it's just me not understanding how screen readers work?

There is a thing called `aria-activedescendant` which updates as the user uses the cursor keys, each "date" has an aria-label which states the full date of the day.  Each keypress of the cursor keys causes the datepicker to "speak".  When the user presses enter or space, the date is selected and the header updates (an aria-live region) which is spoken.

Updates to aria-live regions are "queued", so even when the datepicker is closing, the live region has been updated before we trigger the datepicker to close, so the speech has been queued up and is spoken even after the datepicker closes.  Also note, there is an option to _not close_ the picker when the date is selected (when using the optional footer buttons)

I would suggest, as an exercise, to open the Chrome devtools inspector and checking out all the additional ARIA markup that is present.  And then, if using Chrome, enable the `ChromeVox` extension and try out navigation of the datepicker to better understand how it works for non-sighted users.  And perhaps then compare to other date pickers using the ChromeVox screen reader extension.

**Comment by peetboy** [comment]
@tmorehouse Thanks for explanation. Luckily I was able to implement it using button mode and suggested [dayjs ](https://github.com/iamkun/dayjs) library for transformation of date value between picker and input field. :)

**Comment by tmorehouse** [comment]
`dayjs` is a good choice as it is not as heavy as `moment.js`

**Comment by tmorehouse** [comment]
You can also take advantage of the datepicker `context` event to grab the resolved locale if needed to pass to `day.js`. The event is emitted on `created` hook (as well as when anything changes in the datepicker).

**Comment by ryanmbn** [comment]
> @tmorehouse Thanks for explanation. Luckily I was able to implement it using button mode and suggested [dayjs ](https://github.com/iamkun/dayjs) library for transformation of date value between picker and input field. :)

interested in seeing your implementation
