### ISSUE TITLE
b-form-tags request for better example/implementation with pre-defined set of tags

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#5088]
### Is your feature request related to a problem? Please describe...
https://bootstrap-vue.js.org/docs/components/form-tags/#comp-ref-b-form-tags
has 2 examples of working with pre-defined set of tags:
1. _The following is an example of using a custom select component for choosing from a pre-defined set of tags_
2. _Tagged input using dropdown (has search)_

However, the solution we use now is more usable:
https://vue-multiselect.js.org/#sub-tagging

There's no example there with some specific options set which makes it better for this usecase. It can be experimented at https://admin.juvmed.com/#/org/settings/staff/
in the Permissions control (requires a quick account creation).

Attached some screenshots below.

Advantages:
1. Single input field, that can be clicked to activate the dropdown to select more tags
(vs current example, where 2 lines are used, one for readonly input and another to click to choose tags)
2. Start typing to have results filtered 
(vs current 2nd example, with a separate search input)

### Describe the solution you'd like

When ' pre-defined set of tags' is enabled, have the same control at the top > Basic usage 
https://bootstrap-vue.js.org/docs/components/form-tags/
with this behaviour:

1. clicking in the input text should open a list with available tags 
(without a separate select input, just the dropdown. Maybe this requires a popover?)
2. starting to type in the same input text would filter the values in the dropdown
3. pressing enter would select the 1st tag in the filtered dropdown

### Additional context
![Screenshot from 2020-04-03 15-11-53](https://user-images.githubusercontent.com/1283842/78359545-efc2a100-75bd-11ea-9f95-2e9778208dd0.png)
![Screenshot from 2020-04-03 15-11-34](https://user-images.githubusercontent.com/1283842/78359540-ee917400-75bd-11ea-887d-55bf38bd2903.png)
![Screenshot from 2020-04-03 15-11-41](https://user-images.githubusercontent.com/1283842/78359543-ef2a0a80-75bd-11ea-9e83-aa61fb57025b.png)

Thanks!

**Comment by Hiws** [comment]
You could accomplish this (somewhat), by supplying the input with a `datalist`.
Styling and support will be limited to the browser however.

https://codepen.io/Hiws/pen/gOpJgrV

**Comment by mariusa** [comment]
Thanks Hiws! That's nice, didn't know about ```datalist```. I'll use your example as a base and iterate on it.
