### ISSUE TITLE
Multiple Lines

### ISSUE THREAD

**Issue by ttodua** [bootstrap-vue/bootstrap-vue#5090]
### Describe the bug

We should have an ability to have multiple lines in popup messages.

### Steps to reproduce the bug

i.e. when making
`<div v-b-tooltip.hover title="First Line \n Second Line"></div> `

the "\n" separator (or you can create an alternative) should be making new line separation. At this moment, it doesnt do anything. neither `<br/>` works there.

Neither in documentation I've found anything related to that.

**Comment by Hiws** [comment]
You can use the `html` modifer on the `v-b-tooltip` directive.
```html
<div v-b-tooltip.hover.html title="First Line<br/>Second Line">Test</div>
```

or use the component version
```html
<div id="myDiv"></div>

<b-tooltip target="myDiv">
  First Line<br/>
  Second Line
</b-tooltip>
```

**Comment by ttodua** [comment]
many thanks!
