### ISSUE TITLE
Sidebar page broken

### ISSUE THREAD

**Issue by shaneparsons** [bootstrap-vue/bootstrap-vue#5093]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.js.org/docs/components/sidebar

### Additional context or description

Loading chunk 43 failed. (error: https://bootstrap-vue.js.org/_nuxt/66ab77ed76eed5a84c32.js)

**Comment by tmorehouse** [comment]
Refresh the page.... if the site was published (i.e. a new version, such as 2.10.1) when you had the docs already open, new page chunks get created with new hashes, which foobars the manifest data (it is related to an issue with how Nuxt.js handles the background webworker when the chunk manifest changes and hasn't updated its route to chunk file mappings).

The old chunks are removed from the webserver and the stale manifest attempts to access those no-longer existing JS files.
