### ISSUE TITLE
Cannot add a border-radius to the header of b-table

### ISSUE THREAD

**Issue by AyazBulls** [bootstrap-vue/bootstrap-vue#5096]
### Describe the bug

I have applied a `border-radius: 15px` to my `b-table`, but only to bottom corners are rounded. I have the impression that the top corners are covered by the `thead` but even if i apply the `border-radius` to the `thead` it doesn't change. 

Here is my code VueJs code:
```<template>
  <b-col id="reportstab_block">
    <b-table :items="reports" :fields="fields" thead-class="thead-block">
    </b-table>
  </b-col>
</template>
```
And my Sass stylesheet:
```
#reportstab_block
  .table
    box-shadow: 0px 5px 5px $light_blue;
    border-radius: 15px;
    .thead-block
      background-color: $red
      tr
        th
          color: $light
```
Here is the result:
![Capture_vuejs_bug](https://user-images.githubusercontent.com/24913980/78457421-61781900-76aa-11ea-973d-a5ea9c6cd4e8.PNG)
### Expected behavior

Rounded corners on all the corners of the `b-table`.

### Versions

**Libraries:**

- BootstrapVue: 2.9.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- OS: Windows
- Browser: Mozilla Firefox
- Version: 74.0.1

**Comment by tmorehouse** [comment]
You will need to target the `th` cells in `thead` (I beleive).  Best bet is to use the inspector to see where the borders are applied.

Or You may also need to set background clipping to have the borders show though.

**Comment by AyazBulls** [comment]
Thanks your answer. I did target the `th` in `thead` but still not working... And i also used the web inspector to see where the borders are applied, and it shows that it applies to the table, but the background color of the `thead` goes on top of the table rounded borders. 

This is a strange behavior since i basically developed it in pure Bootstrap and it was working fine until i use bootstrap-vue...

**Comment by tmorehouse** [comment]
Depends on which version you were using before... all styles, except any custom component styles/features, are defined by the standard Bootstrap v4.x CSS

Use the CSS style `background-clip: border-box;` on your `thead` and/or `th`

**Comment by AyazBulls** [comment]
Just tried it, not working... I just don't get how come is so "complex" to apply a simple border-radius to a `thead` ? Isn't it supposed to inherit from the table ? Or at least not cover the table borders ?

**Comment by tmorehouse** [comment]
Borders/backgrounds don't inherit by default.

try the background-clip style on the table element

**Comment by AyazBulls** [comment]
Hello,
So i tried adding the `background-clip` to the table element and it doesn't fix the bug.

What i also did is that i have put a transparent `background-color` on my `thead`. And we can notice that the borders are rounded but also that there is border (which i didn't add). So the conclusion of this is that the `thead` does add on the top of the table borders.

![image](https://user-images.githubusercontent.com/24913980/78539782-67c5dc80-77f3-11ea-91c9-219e6930b64d.png)


Any solution for this ? Other than the `background-clip` which unfortunately isn't working?

**Comment by tmorehouse** [comment]
try targeting your background colors to the thead TH cells?

**Comment by AyazBulls** [comment]
I tried many combinations and got it worked by doing this:
```
.thead-block
  tr
    th
      background-color: $red
      border: none
      color: $light
    th:first-child
      border-top-left-radius: 15px
    th:last-child
      border-top-right-radius: 15px
```
Thanks for your help :)

**Comment by richardolan** [comment]
Te comparto las clases de mi tabla.
<table id="exampleVanilla" class="table table-striped table-bordered table-hover rounded rounded-3 overflow-hidden dataTable no-footer align-middle table-nowrap display" style="width:100%">

![image](https://github.com/bootstrap-vue/bootstrap-vue/assets/12519962/880a1c7a-1348-443b-8716-5ad35394eb88)
