### ISSUE TITLE
b-avatar contents off-center when in b-card

### ISSUE THREAD

**Issue by nikkocampbell** [bootstrap-vue/bootstrap-vue#5097]
### Describe the bug

When placed inside of a b-card element, the contents of the b-avatar are off-center (slightly to the top-left)

### Expected behavior

Contents of b-avatar component should be properly centered

### Versions

**Libraries:**

- BootstrapVue: 2.10.1
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Chrome
- Version: 80

### Demo link

https://codesandbox.io/s/bootstrap-vue-sandbox-rym5r

**Comment by tmorehouse** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/2781561/78462348-7b642c80-76a7-11ea-886b-f0ecee7f03d9.png)

Which shows the Avatars in the card pushed to the right and down due to the card body padding.

**Comment by nikkocampbell** [comment]
Sorry, should have included a screenshot:
![image](https://user-images.githubusercontent.com/1914937/78463153-920a8380-76a7-11ea-8873-16b8da39072a.png)

The issue being with the inner contents of the avatar

**Comment by tmorehouse** [comment]
Do you have screen zoom enabled?

**Comment by nikkocampbell** [comment]
Yes, I was zoomed in to more clearly show the issue. It's still present at 100% zoom:
![image](https://user-images.githubusercontent.com/1914937/78463353-b2d3d880-76a9-11ea-82f1-e1ace5018751.png)


I just tested on Safari and it seems to be working as expected.

**Comment by tmorehouse** [comment]
It might be due to pixel rounding in the browser

**Comment by nikkocampbell** [comment]
I think that may be it. Tried with `size="100px"` so that the computed size would be an integer and it appears centered
