### ISSUE TITLE
Popover dismiss fails on touchscreens

### ISSUE THREAD

**Issue by stevelacey** [bootstrap-vue/bootstrap-vue#5099]
### Describe the bug

The `v-b-popover.click.blur` solution for dismiss on next click (self dismissing) works fine on desktop but fails on touchscreen.

### Expected behavior

Tapping another popover trigger, or away from the popover should dismiss the popover.

### Versions

**Libraries:**

- BootstrapVue: 2.10.1
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: iPhone
- Browser: Chrome

**Screenshot:**

This screenshot demonstrates the behaviour occurring on the demo in the documentation at https://bootstrap-vue.js.org/docs/directives/popover/#dismiss-on-next-click-self-dismissing

![DA879330-92BF-4DDB-8857-6BC90B5079AA](https://user-images.githubusercontent.com/289531/78500802-ca32c480-7782-11ea-9ab3-86abca79500c.png)

**Comment by tmorehouse** [comment]
Do you find the same issue happens with iOS Safari (as Chrome on iOS uses Safari as it's rendering engine)

**Comment by tmorehouse** [comment]
It might be because iOS versions of the browsers do not "focus" buttons when they are clicked, and hence the blur (focusout) event doesn't get fired on the trigger element (button) https://bugs.webkit.org/show_bug.cgi?id=22261

**Comment by tmorehouse** [comment]
@stevelacey could you see if PR #5103 fixes your issue? https://deploy-preview-5103--bootstrap-vue.netlify.com/docs/directives/popover#dismiss-on-next-click-self-dismissing

**Comment by stevelacey** [comment]
@tmorehouse yep can confirm that fix works 🙌🏼

![1065E7B7-BCB8-4FAC-A5DE-8CEB9B536FED](https://user-images.githubusercontent.com/289531/78517545-de5cdd00-77e7-11ea-912c-21babad8b302.png)
