### ISSUE TITLE
Carousel - The prop value set to 0 after I add a new slide

### ISSUE THREAD

**Issue by Silbad** [bootstrap-vue/bootstrap-vue#5100]
Hi,

### Describe the bug

The prop value set to 0 (default) after I add a new slide (change with vuex). The previous value is not kept. I force the ancien value with this : self.$refs.carousel.setSlide(last_value), but the animation isn't very pretty.

### Versions

**Libraries:**

- BootstrapVue: 2.10.1
- Bootstrap: 4.4.1
- Vue: 2.6.11
- Vuex: 3.1.2

**Environment:**

- Device: PC
- OS: Win10
- Browser: Electron 7

### Extra

Thanks for your great work by the way ;)

**Comment by tmorehouse** [comment]
Are you using a loop (v-for) to generate your slides?  If so, are you applying a unique `key` that identifies each slide?  Try to use a value that uniquely identifies the slide (perhaps the title or some other value that uniquely identifies the slide), rather than the loop index number.

**Comment by Silbad** [comment]
Yep, I'm already doing that : 
```
<b-carousel-slide
v-for="image in dataUser.user_images"
:key="image.img_id"
```
When I add a new slide I give it a new key.

**Comment by jackmu95** [comment]
@Silbad I've created a demo on CodeSandbox where you can dynamically add/remove slides.
https://codesandbox.io/s/bootstrapvue-b-carousel-addremove-slides-kv0cs

I don't see an issue with the current index there.
