### ISSUE TITLE
asset size limit warning

### ISSUE THREAD

**Issue by cocomo** [bootstrap-vue/bootstrap-vue#5101]
Please: When I try to build a simple project I created fom vue-cli 4.2.3 webpack complains about the filesize of my bundle:

`warning
asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/chunk-vendors.6ca19c37.js (785 KiB)`

`warning
entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.01 MiB)
      css/chunk-vendors.73152c73.css
      js/chunk-vendors.6ca19c37.js
      css/app.6f3e4460.css
      js/app.5ff9e9e4.js`

`warning
webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
  File                                   Size              Gzipped
  dist/js/chunk-vendors.6ca19c37.js      785.28 KiB        194.53 KiB
  dist/js/app.5ff9e9e4.js                5.13 KiB          2.23 KiB
  dist/css/chunk-vendors.73152c73.css    237.67 KiB        31.77 KiB
  dist/css/app.6f3e4460.css              1.58 KiB          0.63 KiB
  Images and other types of assets omitted.`

I tried to follow webpacks recommendation and separated a component using bootstrap-vue with import() calls in the components script (applying the solution given [here](https://vuejsdevelopers.com/2017/07/03/vue-js-code-splitting-webpack/)).

It seems i cannot Vue.use() BootstrapVue inside that component, apart from the vue instance created in App.vue? 

Questions: Is that size limit a common problem in bootstrap-vue? Is my lazy loading / code splitting idea a viable solution to conquer size limitations? Are there other / better ways to split an application into smaller chunks? My naive idea is to show a spinner/animation while the users device is still loading the bootstrap-vue chunks.

**Comment by tmorehouse** [comment]
Doing this in page/route-component/etc:

```js
import { BootstrapVue } from 'bootstrap-vue'
Vue.use(BootstrapVue)
```
Will _always_ import the entire library.

Whenever you import an entire library (any library), you are going to create a chunk that is the size of the library. And if anything in that library is needed for your main page, then it will be part of your main app entrypoint size.

To do tree shaking, or use selective loading, import just the components or plugins you need for each page. 

i.e. for Plugins:

```js
import { LayoutPlugin, CardPlugin } from 'bootstrap-vue'
Vue.use(LayoutPlugin)
Vue.use(CardPlugin)
```

For components that are needed only for a particular page:
```js
import { BFormInput, BButton, BCard } from 'bootstrap-vue'

// Page/Route component definition
export default {
  components: {
    BFormInput,
    BButton,
    BCard
  },
  // ...
}
```

If there is something needed by all pages, import that in your main app entrypoint

```js
import { LayoutPlugin, BButton, BCard } from 'bootstrap-vue'

Vue.use(LayoutPlugin)
Vue.component('BButton', BButton)
Vue.component('BCard', BCard)
```

**Comment by cocomo** [comment]
Works great. Thank you very much for the explanation.
