### ISSUE TITLE
Carousel - Animation lag when you use array navigation very fast

### ISSUE THREAD

**Issue by Silbad** [bootstrap-vue/bootstrap-vue#5102]
Hi,

Me again with the carousel ^^

### Describe the bug

You can try here : [https://bootstrap-vue.org/docs/components/carousel](https://bootstrap-vue.org/docs/components/carousel), the animation lag sometimes when you click on the left and right keys very quickly. It's not a big issue but it's not pretty so see.

### Versions

**Libraries:**

- BootstrapVue: 2.10.1
- Bootstrap: 4.4.1
- Vue: 2.6.11
- Vuex: 3.1.2

**Environment:**

- Device: PC
- OS: Win10
- Browser: Firefox

Thanks,

**Comment by tmorehouse** [comment]
This happens because the animation needs to complete before the next slide can be shown

**Comment by Silbad** [comment]
Sorry, only on the right key very fast...

**Comment by Silbad** [comment]
Yes but why on the left key it's ok ?

**Comment by tmorehouse** [comment]
It is due to how Bootstrap v4.x's animation classes work for carousel.
