### ISSUE TITLE
Escape doesn't close a modal after it has already been closed

### ISSUE THREAD

**Issue by Benjamin-Lee** [bootstrap-vue/bootstrap-vue#5111]
### Describe the bug

On Safari, clicking the title of a modal, hitting escape, reopening the modal, and hitting escape again fails to close the modal.

### Steps to reproduce the bug

1. Open a modal
2. Click the title
3. Hit <kbd>esc</kbd>
4. Repeat

### Expected behavior

The modal closes.

### Versions

**Libraries:**

- BootstrapVue: 2.10.1
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Catalina 10.15.3
- Browser: Safari
- Version: 13.0.5

### Demo link

https://jsfiddle.net/ok6L5heg/

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
Does it work on Chrome for Mac OK?

**Comment by Benjamin-Lee** [comment]
Yep, it works on Chrome.

**Comment by tmorehouse** [comment]
Interesting....

When you pres ESC, does the trigger button regain focus once closed?

**Comment by tmorehouse** [comment]
@jackmu95 could you take a look at this one and see what you might think is going on in Safari?

**Comment by Benjamin-Lee** [comment]
Yes, it does. When reproducing, sometimes clicking on the title once is causing the escape key to fail, whereas sometimes it is only happening after three rounds. Would a GIF be useful?

**Comment by jackmu95** [comment]
@tmorehouse For me it's working perfectly fine all the time.
The focus is always returned properly back to the button.

@Benjamin-Lee A video/GIF to proof your issue would be great.

**Comment by jackmu95** [comment]
@Benjamin-Lee I'am running MacOS 10.15.4 and Safari 13.1.

**Comment by tmorehouse** [comment]
@jackmu95 is <kbd>ESC</kbd> reliably working for you?

**Comment by jackmu95** [comment]
@tmorehouse Yeah. Repeated it 10+ times.

**Comment by tmorehouse** [comment]
Perhaps it is a Safari browser version bug?

**Comment by jackmu95** [comment]
@tmorehouse I think so.

**Comment by jackmu95** [comment]
@Benjamin-Lee Can you please check if you get any console errors when the issues occurs.

**Comment by tmorehouse** [comment]
@Benjamin-Lee can you upgrade your version of Safari to the latest release and see if the issue persists?
