### ISSUE TITLE
b-form-datepicker: can't clear a selected date

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#5114]
### Describe the bug

After selecting a date in b-form-datepicker it's impossible to clear it (set to blank/null)

### Steps to reproduce the bug

1. select a date in b-form-datepicker form field
https://bootstrap-vue.js.org/docs/components/form-datepicker/

2. change your mind and set that field to empty

### Expected behavior

Be able to change to blank/empty/null state.

Example:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_date
Once can clear the date since it allows manual input. There's also an 'x' button on hover and when field has focus.

### Versions

**Libraries:**

- BootstrapVue: 2.10.0
- Bootstrap: 4.4.1
- Vue: 2.6.2

**Comment by tmorehouse** [comment]
There is a prop to enable the reset date button for `<b-form-datepicker>` called `reset-button`, which is a Boolean prop. when present/`true` will show the reset button.

Refer to the docs: https://bootstrap-vue.js.org/docs/components/form-datepicker#optional-controls

**Comment by mariusa** [comment]
Right, sorry for missing that! Thanks

**Comment by tmorehouse** [comment]
You can also place datepicker in an input group that has an append button that clears the date:

```html
<b-input-group>
  <b-form-datepicker v-model="value"></b-formdatepicker>
  <template v-slot:append>
    <b-button aria-label="Clear date" @click="value = null">
       <b-icon icon="x"></b-icon>
    </b-button>
  </template>
</b-form-input>
```

**Comment by mariusa** [comment]
@tmorehouse Would it be possible to make that button less intrusive by showing an 'x' icon in the b-form-datepicker field (not in the calendar browser), similar to the 'x' in the native input type='date' ?
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_date

**Comment by tmorehouse** [comment]
It is possible, but would require a bit of extra markup to make it accessible, and different use-cases may want different stylings, making the component code a bit more bloated... so we leave it up to he user to provide a solution that best fits their overall app style

**Comment by mariusa** [comment]
Ok, thanks for considering

**Comment by tmorehouse** [comment]
It all depends on the end users use case... Some people want the reset-button, some don't.  Some may want both the reset button, plus an `x` button.  Some may not like the default `x` icon styling... 

It opens up a big bag-o-worms :wink:

**Comment by sebastian-raubach** [comment]
Is it possible to set the reset value to `null`? Currently, I've only found options to set it to an empty string, but not null.

**Comment by jackmu95** [comment]
@sebastian-raubach Let's continue the discussion in #6322 why you wan't to return `null` when empty.
