### ISSUE TITLE
Bootstrap Customization breaks component UI

### ISSUE THREAD

**Issue by jd-0001** [bootstrap-vue/bootstrap-vue#5117]
### Describe the bug

Hi, It's been 2 weeks I am using bootstrap vue for my project. It's very good. However, recently I came up with few issues.

**Spacing Utilities:**
In bootstrap-vue, we get some spacing utilities used in components like `mx-1` or `p-1`. This is good for users but adding this to framework will break component styles if someone customizes bootstrap's spacer according to their needs. Below is some examples:
  
*Toast*
![rsz_toast](https://user-images.githubusercontent.com/47495003/78772469-6d682180-79af-11ea-845a-577740c868bf.png)
*calendar*
![rsz_calendar-full](https://user-images.githubusercontent.com/47495003/78772473-6f31e500-79af-11ea-8401-9003c1928105.png)

**Icons:**
As I have just started exploring bootstrap-vue I haven't explored all components and flexibility they provide. But I have an issue with changing icon of calendar component's action buttons. So, providing an option for using custom icons will be beneficial for everyone.

### Steps to reproduce the bug

Change bootstrap **spacer** utility.
e.g.
```
$spacer: 1rem;
$spacers: ();
$spacers: map-merge(
  (
    0: 0,
    25: (
      $spacer * 0.25,
    ),
    50: (
      $spacer * 0.5,
    ),
    75: (
      $spacer * 0.75,
    ),
    1: (
      $spacer,
    ),
    2: (
      $spacer * 1.5,
    ),
    3: (
      $spacer * 3,
    ),
    4: (
      $spacer * 3.5,
    ),
    5: (
      $spacer * 4,
    ),
  ),
  $spacers
);
```

### Expected behavior

I have checked other library before creating this issue and I found that [reactstrap](https://reactstrap.github.io/) don't use any spacing utilities. So, even if someone changes bootstrap's customization UI doesn't look weird.

### Versions

**Libraries:**

- BootstrapVue: 2.11.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

Not required

### Demo link

None

### Additional context

None

**Comment by jackmu95** [comment]
@jd-0001 Solid point. Using the utilities saves us a lot of custom CSS but I think we have to makes sure we don't use the ones that with user-customization support.

Good: `mr-0`, `p-0`, `d-none`
Bad: `mr-1`, `p-2`

**Comment by tmorehouse** [comment]
For calendar/datepicker, we will be switching the navigation buttons to either a button-group layout or row/col layout (which will remove the need for the padding)

For `<b-toast>`, the layout of the header is based on the BootstrapV4.4 example header layout

**Comment by jd-0001** [comment]
Hi @tmorehouse before you close this issue, I just want to confirm that will I be able to change each icon according to another library(I am using [BoxIcons](https://boxicons.com/))?

**Comment by tmorehouse** [comment]
The first PR will remove the margin/padding utility classes (in exchange for making the custom SCSS a little bigger)

There will be a second PR that will create slots for each of the top nav button content (so you can replace the icons)
