### ISSUE TITLE
b-form-checkbox styled wrong

### ISSUE THREAD

**Issue by dlnsk** [bootstrap-vue/bootstrap-vue#5118]
Label of checkbox should styled using 'form-check-label'
https://getbootstrap.com/docs/4.1/components/forms/#checkboxes-and-radios

**Comment by tmorehouse** [comment]
Class `'form-check-label'` is used in `plain` mode checkboxes, while `'custom-control-label'` is used on the custom styled checkboxes/radios

From Bootstrap v4.4 docs:

- Plain style radios/checks: https://getbootstrap.com/docs/4.4/components/forms/#checkboxes-and-radios
- Custom style radios/checks:  https://getbootstrap.com/docs/4.4/components/forms/#checkboxes-and-radios-1


BootstrapVue renders the custom style radios/checks by default.  to get the non-custom styled, set the `plain` prop on the radio/check: https://bootstrap-vue.js.org/docs/components/form-checkbox#non-custom-check-inputs-plain

**Comment by dlnsk** [comment]
Thanks!
