### ISSUE TITLE
Cant control b-collapse with :visible prop

### ISSUE THREAD

**Issue by FragsterAt** [bootstrap-vue/bootstrap-vue#512]
works only with v-b-collapse and buttons. But i need to control collapse with my app state.

**Comment by tmorehouse** [comment]
Duplicate issue #452 

Fixed by PR #453 and will be available in the next release.

**Comment by FragsterAt** [comment]
@tmorehouse Ok! When next release will be ready on NPM?

**Comment by tmorehouse** [comment]
We do not have a fixed date for the next release (there are still a fw minor things we need to add).  But it will be very soon.

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
