### ISSUE TITLE
Adding :prefetch="true|false" to all links

### ISSUE THREAD

**Issue by Guito** [bootstrap-vue/bootstrap-vue#5125]
As seen in https://nuxtjs.org/api/components-nuxt-link/, prefetch can be enabled or disabled using the prefetch attribute.

Currently we only have no-prefetch, however, this is not enough if you want to disable prefetching globally and only having it locally (You can disable the global prefetching with: `router.prefetchLinks: false`)

**Comment by tmorehouse** [comment]
This would need to be a `true`, `false` or `null` prop (tri-state) where `null` means to use the global Nuxt setting.

**Comment by Guito** [comment]
Hello @tmorehouse,

Can I help implementing this? Is there any guide to start developing for the module?
