### ISSUE TITLE
Allow slot rendering button-style b-form-radio-group

### ISSUE THREAD

**Issue by thejcannon** [bootstrap-vue/bootstrap-vue#5127]
### Is your feature request related to a problem? Please describe...

I'd love to put pills on my form-radio-buttons, but using an html field means I need rendered HTML from Vue components or I need to roll a radio-button-like button group implementation.

### Describe the solution you'd like

Ideally, a slot I can use for the rendered button text. (I know b-form-radio-group is more than buttons, so likely the slot would work for _any_ radio group type, but I don't want the scope of this feature request to be larger than my needs)

### Describe alternatives you've considered

- Have Vue render the HTML for the pills and put that in the html field on my options
- Roll my own radio-button-group like solution with button-group

**Comment by tmorehouse** [comment]
The button styling of `b-form-checkbox-group` renders as a `btn-group`.

Your best bet is to do something similar to below to get pill styles:

```html
<b-form-group label="Pill button style radios">
  <b-form-radio-group
    v-model="selected"
    buttons
    button-variant="primary"
    class="mx-n1"
  >
    <template v-for="option in options">
      <b-form-radio :value="option.value" class="rounded-pill mx-1">
        {{ option.text }}
      </b-form-radio>
    </template>
  </b-form-radio-group>
</b-form-group>
```

Which will render something like:

![image](https://user-images.githubusercontent.com/2781561/78924347-ff376380-7a6f-11ea-8eb8-67783b26b886.png)

**Comment by thejcannon** [comment]
Oops, I meant I want pill badges on my buttons 😄. I should've been more specific.
I want something like: https://bootstrap-vue.js.org/docs/components/badge#overview

I think I can swing it with your example though. Feel free to close if you think the workaround is sufficient.

**Comment by tmorehouse** [comment]
Ah, OK. :smile: 

Then try something like this:

```html
<b-form-group label="Button style radios with badges">
  <b-form-radio-group v-model="selected" buttons>
    <template v-for="option in options">
      <b-form-radio :value="option.value">
        {{ option.text }}
        <b-badge variant="light">{{ option.foobar }}</b-badge>
      </b-form-radio>
    </template>
  </b-form-radio-group>
</b-form-group>
```
