### ISSUE TITLE
Use transition on row-details

### ISSUE THREAD

**Issue by dochoss** [bootstrap-vue/bootstrap-vue#5129]
I can't seem to find a way to implement this, so I wanted to ask here.  I want to show the row details with a "slide down" transition, so it looks like a little drawer opening below the row, then closing when _showDetails is removed.  I have the CSS transition built already, and I have it working fine with a regular table.  Everything displays properly when I toggle _showDetails, just no transition.  

Here's what I have in my code right now:

```
<b-table  
        :items="items"
        hover
        class="small"
      >
        <template v-slot:row-details="row">
          <transition name="slide-down" appear>
            <div v-if="isWarmingUp(row.item)" class="d-flex w-100">
              <div class="mx-auto text-center pt-2">
                <i class="fas fa-lightbulb fa-2x" />
                <p>Warming up</p>
              </div>
            </div>
            <div v-else class="d-flex w-100">
              <div class="mx-auto">
                Confirming hits
                <p class="text-center">{{ row.item.foundCount || row.item.messageCount }}</p>
              </div>
              <div class="mx-auto">
                Aggregating
                <p class="text-center">{{ row.item.messageCount }}</p>
              </div>
            </div>
          </transition>
        </template>
      </b-table>
```

**Comment by tmorehouse** [comment]
The issue is that the `<transition>` is inside of the details `<tr>` which is v-if'ed when showing. so it is not triggering the transition.

**Comment by dochoss** [comment]
I see.  Any way to accomplish what I'm trying to do?

**Comment by tmorehouse** [comment]
You may need to find a way to delay the transition trigger via a `requestAnimationFrame` or `$nextTick` delay.

Perhaps convert your details slot to a custom component which you pass the slot scope to, and in that component, it it's mounted hook used a nextTick or requestAnimationFrame delay to trigger rendering your content (using a data variable to v-if your content)

**Comment by dochoss** [comment]
Gotcha.  So something like this?

```
<template v-slot:row-details="row">
  <animation-component :row="row" />
</template>

...
AnimationComponent.vue
<transition v-if="show"> 
...code from above here...
</transition>

data() {
  return {
    show: false
  }
}
created() ){
  Vue.nextTick(() => this.show = true; )
}
```

**Comment by tmorehouse** [comment]
Yeah....   I've never tried this with row-details before, but it might help

**Comment by dochoss** [comment]
Cool, I'll give it a shot and report back.  Thanks for the help!

**Comment by tmorehouse** [comment]
Or you may need to v-if the content inside the transition component

**Comment by dochoss** [comment]
You were right.  v-if on the content inside the transition worked.  Had to do some fiddling with it to get it to work with my model, but definitely did the trick.

For reference, here's the final pseudocode for it:

```
<template v-slot:row-details="row">
  <animation-component :row="row" />
</template>

...
AnimationComponent.vue
<transition> 
  <div  v-if="show">
...code from above here...
  </div>
</transition>

data() {
  return {
    show: false
  }
}
created() ){
  this.$nextTick(() => this.show = true);
}
```

**Comment by TuringJest** [comment]
If there was a table option to not hide all row-details as a default we could wrap the content into a collapse and just trigger that one. 
It already works by toggling the detail and then the collapse but we will loose the animation on close of course. 
So it would need a timeout on close which is a bit unelegant.
