### ISSUE TITLE
Is it possible my make an accordion with bootstrap-vue?

### ISSUE THREAD

**Issue by FragsterAt** [bootstrap-vue/bootstrap-vue#513]
https://v4-alpha.getbootstrap.com/components/collapse/#accordion-example

**Comment by tmorehouse** [comment]
It is possible.  You would need to have a unique visible/show state for each collapsible component, and listen/watch for changes to the values and close any other open collapse components.

**Comment by tmorehouse** [comment]
@FragsterAt I have crated PR #519 which adds accordion support to `collapse`.

**Comment by tmorehouse** [comment]
@FragsterAt I have crated PR #519 which adds accordion support to collapse.
