### ISSUE TITLE
BFormSelect not rendering dropdown selection

### ISSUE THREAD

**Issue by ndianabasi** [bootstrap-vue/bootstrap-vue#5134]
### Describe the bug

I'm getting an error: `Error in render: "TypeError: Cannot convert undefined or null to object"`. It was rendering some days ago. However, when I returned to the form yesterday, I noticed that all the select fields were not rendering.

### Steps to reproduce the bug

1. The options prop is set to a Vuex getter.
2. Vuex state is populated with data via an axios called made before route is entered.

### Expected behavior

BFormSelect should render. Other input field such as BInput are rendering.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.24
- Bootstrap: 4.3.1
- Vue: 2.6.11

**Environment:**

- OS: Windows 10
- Browser: Chrome
- Version: 80.0.3987.163 (Official Build) (64-bit)

```
<b-input-group
  class="inputGroup"
  id="nameOfOrgInputGroup"
>
  <b-input-group-prepend>
    <b-input-group-text>
      <i
        class="icon-user"
      ></i>
    </b-input-group-text>
  </b-input-group-prepend>
  <b-input-group-prepend>
    <b-input-group-text
      >Gender</b-input-group-text
    >
  </b-input-group-prepend>
  <b-form-select
    class="form-control"
    placeholder="Gender"
    :options="getGendersForSelect"
    id="gender"
    v-model="$v.form.gender.$model"
    :state="chkState('gender')"
  ></b-form-select>
</b-input-group>
```
```
import { mapGetters, mapActions, mapMutations } from "vuex";
...
...mapGetters("genders", ["getGendersForSelect"]),
...
 ...mapActions("genders", ["loadGendersForSelect"]),
```

Bootstrap-Vue is loaded via main.js
```
import BootstrapVue from "bootstrap-vue";
Vue.use(BootstrapVue);
```

**Comment by tmorehouse** [comment]
You are using a rather old version of BootstrapVue (2.0.0-rc.24)

Have you tried updating to BootstrapVue v2.11.0+ and Bootstrap v4.4.1?

**Comment by ndianabasi** [comment]
I upgraded to the latest version and it didn't solve the problem. While debugging today, I discovered that BFormSelect tried to read the options even before the mounted lifecycle hook. I think this is a bit too aggressive. Since a lot of times, options are loading from Ajax calls, BFormSelect should, at least, wait until the component is mounted. At this stage most of the Ajax calls made during or before the created lifecycle hook have resolved.

I solved this by adding v-if conditions in all BFormSelect fields in order to force the selects not to render.

```
<b-input-group class="inputGroup" id="countryOfOrgInputGroup">
                      <b-input-group-prepend>
                        <b-input-group-text>
                          <i class="icon-location-pin icons"></i>
                        </b-input-group-text>
                      </b-input-group-prepend>
                      <b-input-group-prepend>
                        <b-input-group-text>Country</b-input-group-text>
                      </b-input-group-prepend>
                      <b-form-select
                        v-if="getCountriesForSelect"
                        class="form-control"
                        placeholder="Country of Organisation"
                        autocomplete="country"
                        @change="debouncedLoadCountriesState"
                        :options="getCountriesForSelect"
                        id="country_of_organisation"
                        v-model="$v.form.country_of_organisation.$model"
                        :state="chkState('country_of_organisation')"
                      ></b-form-select>
                    </b-input-group>
```

````
<b-input-group class="inputGroup" id="statofOrgInputGroup">
                      <b-input-group-prepend>
                        <b-input-group-text>
                          <i class="icon-location-pin icons"></i>
                        </b-input-group-text>
                      </b-input-group-prepend>
                      <b-input-group-prepend>
                        <b-input-group-text>State/ Region</b-input-group-text>
                      </b-input-group-prepend>
                      <b-form-select
                        class="form-control"
                        placeholder="State of Organisation"
                        autocomplete="state"
                        :options="
                          getCountriesStatesForSelect
                            ? getCountriesStatesForSelect
                            : [{ value: null, text: 'Select country first', disabled: true }]
                        "
                        id="state_of_organisation"
                        v-model="$v.form.state_of_organisation.$model"
                        :state="chkState('state_of_organisation')"
                      ></b-form-select>
                    </b-input-group>
````

For the State field, I added a disable option as default since the `state` array is loading when a `country` is selected.

I hope this will help someone else in my situation.

**Comment by ndianabasi** [comment]
I think this should be treated a bug. BFormSelect could accept a prop which delays the rendering of the field pending the truthiness of the prop. This will help in many situations where the `options` prop depends on an array populated via Ajax.

**Comment by tmorehouse** [comment]
If your options are not available at creation time, pass the empty array `[]` as the initial value.  Note that the mounted hook is never called for server side rendering, which is why the initial array is used during create (in the `data()` hook). Also note that AJAX calls can be made during SSR (in the created hook)

```html
<template>
  <b-form-select v-model="selected" :options="selectOptions"></b-form-select>
</template>

<script>
export default {
  data() {
    return {
      selected: null,
      selectOptions: []
    }
  },
  mounted() { // or beforeMount()
     // do some ajac call here
     this.$axios.get('/some/api')
       .then(data => {
         this.selectOptions = data.options
       })
  }
}
</script>
```

**Comment by tmorehouse** [comment]
It is not a bug.

**Comment by ndianabasi** [comment]
Thank you for your prompt responses @tmorehouse. I will implement your suggestion as an alternative solution.

**Comment by tmorehouse** [comment]
Let us know how it goes....

**Comment by ndianabasi** [comment]
So I added empty arrays to the options props as fallbacks and I think the form is still rendering well. 

```
<b-form-select
                        class="form-control"
                        placeholder="Country of Organisation"
                        autocomplete="country"
                        @change="debouncedLoadCountriesState"
                        :options="getCountriesForSelect || []"
                        id="country_of_organisation"
                        v-model="$v.form.country_of_organisation.$model"
                        :state="chkState('country_of_organisation')"
                      ></b-form-select>
                    </b-input-group>
```

Thank you @tmorehouse.
