### ISSUE TITLE
Table does not emit events

### ISSUE THREAD

**Issue by CrixuAMG** [bootstrap-vue/bootstrap-vue#514]
I think the table would be greatly improved by adding emits.
For example:

- Hover over row/column
- On table order change

Also, being able to set onclicks for a column or even an entire row would be awesome!

**Comment by tmorehouse** [comment]
Check out PR #460 

Which adds in additional events and features, on of them being `head-clicked` (for clicking of table headers), and `sort-changed` (when the sorting criteria has changed).

This should be available in the next release.

**Comment by tmorehouse** [comment]
@CrixuAMG I have added in support for `row-hovered` event in PR #460

**Comment by tmorehouse** [comment]
Latest master now has the new features via PR #460

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)

**Comment by m1neral** [comment]
`row-hovered` still not working

**Comment by tmorehouse** [comment]
This should be fixed in the next release
