### ISSUE TITLE
B-dropdown : events in template button-content not working on Firefox

### ISSUE THREAD

**Issue by jdflaugergues** [bootstrap-vue/bootstrap-vue#5144]
### Describe the bug

On b-dropdown component, events (eg: click and tooltip hover) are not working with Firefox.
This works well on Chrome.

### Steps to reproduce the bug

Demo link: https://jsfiddle.net/yjr1adLu/1/

1. Use b-dropdown component and add in template button-content slot a div with a b-tooltip and a div with a click event
2. Hover on hoverable div 
3. Click on clickable div
4. No tooltip and no log in console appear

### Expected behavior

It should displays a tooltip on "hover me" text
It should displays a log on "click me" text

### Versions

**Libraries:**

- BootstrapVue: 2.7.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- OS: Windows 10
- Browser: Firefox
- Version: 52.5.3 (32 bits)

### Demo link

 https://jsfiddle.net/yjr1adLu/1/

**Comment by tmorehouse** [comment]
You are placing interactive content inside a button (the button-content slot renders in a `<button>` element), which will not work across browsers, and is not valid markup for interactivity.

You can place the `v-b-tooltip` directly on `<b-dropdown>` (and it will get applied to the dropdown  toggle button).

What is the reasoning for the click event on the inner text of the button?  You can determine when the button is clicked via the dropdown's emitted `show` event.

**Comment by jdflaugergues** [comment]
Hi @tmorehouse, thanks for your answer.
I've customized the dropdown button with:
 - a label (which open the dropdown content on click)
 - a badge with a contextual number inside depends on dropdownlist item selected
 - a cross button 

I'd like to display the tooltip only on badge hover and not on the whole button hover.

And to have a specific behavior on cross button click which shouldn't open the dropdown content (I want to remove all items selected inside the dropdown item list)

**Comment by tmorehouse** [comment]
But the content is still being rendered in a `<button>` element (labels are not allowed content in buttons)

Perhaps you should be using the split dropdown mode

**Comment by jdflaugergues** [comment]
Yes I see, but it works on Chrome and on the last version of Firefox (75). So I think it's juste a matter of polyfill. I've tried with split dropdown mode but its render it's also a button tag.
Maybe I have to use toggle-tag property to use a different tag instead of default button.

**Comment by tmorehouse** [comment]
Note that when you use `toggle-tag` the element will have the ARIA role `role="button"` applied to it, So in your situation Screen Reader users will still have issues seeing the tooltip or the other "click" area.
