### ISSUE TITLE
Modal not showing content

### ISSUE THREAD

**Issue by richlove1** [bootstrap-vue/bootstrap-vue#515]
Hi 

I'm having an issue with the modal in that it's activating the dark overlay but not showing the content of the modal (though it's there in the DOM). I'm not getting any console errors. Are you able to offer any help as I'm a bit stuck with getting it resolved (and can't recreate in a JSFiddle)

**Comment by alexsasharegan** [comment]
Check out Issue #276 for an in-depth dive on this, but in short, you may need to add a css rule after the bootstrap css you have in your page.

```css
.modal { display: block; }
```

First double check that you're including the bootstrap-vue stylesheet (which does contain this rule), and it's being loaded after BS4. The path looks something like this: `bootstrap-vue/dist/bootstrap-vue.css`

**Comment by richlove1** [comment]
OK great, will check it out, thanks.

**Comment by richlove1** [comment]
Awesome thanks, that sorted it. 

Didn't realise I had to include Bootstrap-Vue specific stylesheet as I thought it would use Bootstrap default styles!? (Assume I need to be importing standard Bootstrap scss and Bootstrap-Vue css files?)

**Comment by alexsasharegan** [comment]
The bootstrap-vue stylesheet is small and handles the style overrides needed because of the `v-show` directive and other things. It's the generated output from all the style blocks of the component lib.

**Comment by richlove1** [comment]
Ah ok, just had a look and noticed it's pretty minimal. Thanks for the feedback

**Comment by alexsasharegan** [comment]
You're welcome!

**Comment by anistplenitud** [comment]
I know this is closed , but a silly mistake would be if you set .body {color :#fff} , of course in this case the content is there , you just can't see it coz the font is the same as the modal background-color. So just change it to .modal {color : #000} or .body {color : #000}
