### ISSUE TITLE
Match heights in v-for carousel slider

### ISSUE THREAD

**Issue by jrpersico** [bootstrap-vue/bootstrap-vue#5153]
Hi,

Do you know how to define the height of the carousel according to the size of the slides in a v-for.

I tried with view-match-heights but it only applies the height of the first element to the others

**Comment by tmorehouse** [comment]
Carousels are responsive in width (and the images use `img-fluid` class to control the widths).  But if your slides do not have a backgound image, you can use the `img` slot (which can have more than just an image), and use the `<b-aspect>` component to maintain the aspect ratio.

```html
<b-carousel-slide ...>
  <template v-slot:img>
    <b-aspect aspect="16:9">
       <!-- content in here -->
    </b-aspect>
  </template>
</b-carousel-slide>
```

**Comment by jrpersico** [comment]
Thank you very much for your reply. 

This solution only works if a fixed height is defined. If my content is dynamic and sometimes longer than the height passed in the aspect tag it no longer works ... this is the case when switching from desktop to mobile. 

You do not know a way where each slide is at the same height and where this height is calculated automatically according to the longest content ?

I tried with vue-match-heights but it doesn't work in my v-for. It’s only calculated on the height of the first element.

Thanks for your time !

**Comment by tmorehouse** [comment]
The problem with `vue-match-heights` is probably because the other slides are set to `display:none` when not shown, so it can't calculate the maximum slide height.

**Comment by snowjaguar625** [comment]
> The problem with `vue-match-heights` is probably because the other slides are set to `display:none` when not shown, so it can't calculate the maximum slide height, as it can only "see" the first slide (and all others would have an intrinsic height of 0)

So what is solution?
