### ISSUE TITLE
[list-group-item] "to" prop should accept [String, Object] as of mixins/link ?

### ISSUE THREAD

**Issue by elb** [bootstrap-vue/bootstrap-vue#516]
Hello, i would expect to be able to pass an object too but i may miss something.

```
<b-list-group flush>
  <b-list-group-item tag="b-link"  v-for="(method, i) in service.methods" :key="i" :to="{name: 'method', params: {id: method.id }}">
    ...
  </b-list-group-item>
</b-list-group>
```

```
[Vue warn]: Invalid prop: type check failed for prop "to". Expected String, got Object.
```

* [components/list-group-item.vue](/bootstrap-vue/bootstrap-vue/blob/master/lib/components/list-group-item.vue#L62)
* [mixins/link.js](/bootstrap-vue/bootstrap-vue/blob/master/lib/mixins/link.js#L61)

Should i open a PR ?

Thanks for your work.

**Comment by tmorehouse** [comment]
Sure, open a PR with the change.

Thanks!

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
