### ISSUE TITLE
Make b-table able to render more than one row at once

### ISSUE THREAD

**Issue by realtebo** [bootstrap-vue/bootstrap-vue#5161]
### Is your feature request related to a problem? Please describe...

I have the need to render a complex table with a huge amount of data

### Describe the solution you'd like

I commonly show only main columns, and add an icon to 'show more'. This shows a row under the current row with a full width list of items. This way I can show a lot of data in the secondary row

I'd like in the <b-table> to can insert 

<b-row> ... some templates for cells ...</b-row>
<b-row> ... some templates for other cells ...</b-row>

and the secondary rows should be full-width, single column,

### Describe alternatives you've considered

An alternative could be like DataTable.js does. When you progressively narrow the viewport, it automatically move one column at time under each row. Is something I call "progressively stacked"

Or you can provide a system for master-detail visualization (very usefull for 1-n relations)

**Comment by tmorehouse** [comment]
Have you looked at `row-details` feature? You can easily add nested tables in the row-details slot.

https://bootstrap-vue.js.org/docs/components/table#row-details-support

**Comment by realtebo** [comment]
Thanks ! `row-details` is exactly what I need.

I'll open an issue for problem about a vue warning related to `row-details`.

I close this feature request.

**Comment by tmorehouse** [comment]
Also, check out the stacked option, which can be set to a responsive breakpoint (stacked until the breakpoint is reached): https://bootstrap-vue.js.org/docs/components/table#stacked-tables
