### ISSUE TITLE
b-table detail row: opening & closing throws a vuex state warning

### ISSUE THREAD

**Issue by realtebo** [bootstrap-vue/bootstrap-vue#5162]
### Describe the bug

I'm using b-table with the detail row support. 
So I've added a button to trigger `toggleDetail`.
It works, for opening & closing the detail row.
But when clicked, in both cases, opended and closed, the javascript console tell me this

```
vue.common.dev.js?4650:630 [Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] do not mutate vuex store state outside mutation handlers."

(found in <Root>)
warn @ vue.common.dev.js?4650:630
logError @ vue.common.dev.js?4650:1889
globalHandleError @ vue.common.dev.js?4650:1884
handleError @ vue.common.dev.js?4650:1844
run @ vue.common.dev.js?4650:4565
update @ vue.common.dev.js?4650:4537
notify @ vue.common.dev.js?4650:741
reactiveSetter @ vue.common.dev.js?4650:1066
set @ vue.common.dev.js?4650:1087
eval @ mixin-tbody-row.js?c324:84
invokeWithErrorHandling @ vue.common.dev.js?4650:1859
invoker @ vue.common.dev.js?4650:2180
original._wrapper @ vue.common.dev.js?4650:7543
vue.common.dev.js?4650:1893 Error: [vuex] do not mutate vuex store state outside mutation handlers.
    at assert (vuex.esm.js?2f62:90)
    at Vue.store._vm.$watch.deep (vuex.esm.js?2f62:793)
    at Watcher.run (vue.common.dev.js?4650:4563)
    at Watcher.update (vue.common.dev.js?4650:4537)
    at Dep.notify (vue.common.dev.js?4650:741)
    at Object.reactiveSetter [as _showDetails] (vue.common.dev.js?4650:1066)
    at VueComponent.set [as $set] (vue.common.dev.js?4650:1087)
    at eval (mixin-tbody-row.js?c324:84)
    at invokeWithErrorHandling (vue.common.dev.js?4650:1859)
    at HTMLButtonElement.invoker (vue.common.dev.js?4650:2180)

```
### Steps to reproduce the bug

in a `b-table` add some columns and an action column, like the following

```
                        <template
                            v-slot:cell(actions)="data"
                            no-sort-reset="true"
                        >
                            <b-button size="sm" @click="data.toggleDetails" class="mr-2">
                                {{ data.detailsShowing ? 'Hide' : 'Show'}} Details
                            </b-button>
                        </template>
```

Then add a (eventually empty) detail row

```
                       <template v-slot:row-details="data">
                            <b-card>
                               some data here
                            </b-card>
                        </template>
```

Then you can click on the button to show/hide details

### Expected behavior

I expect to do not see warning in js console

### Versions

**Libraries:**

- bootstrap-vue: 211.0
- Bootstrap: 4.4.4
- Vue: 2.6.11

**Environment:**

- Device: indipendent, but Desktop Pc
- OS: indipendente, but Windows 10
- Browser: Chrom
- Version: 80]

**Comment by tmorehouse** [comment]
Showing/hiding row-details alters the underlying data row object.

You will need to ensure that you have a getter and setter for the row data.

**Comment by realtebo** [comment]
Please explain, or point me to the documentation

**Comment by tmorehouse** [comment]
When you show details, a property called `_showDetails` will be set on the row data (altering the rows data to include this new property, if it already doesn't exist, and will set it to `true` or `false` depending on the state of the details row)

**Comment by realtebo** [comment]
I tried to add the property to the column where i placed the button
```

{
                    key: "actions",
                    label: this.$t("actions"),
                    sortable: false,
                    _showDetails: true
                },
```

Nothing changes

**Comment by tmorehouse** [comment]
You may need to do a medium clone of the data before passing it to `<b-table>`:

```js
const items = vueGetter.map(item => ({...item })
```

**Comment by realtebo** [comment]
Thanks for helping me 

Actually my items are effectively read from store as
```

computed: {
        records() {
            return this.$store.getters["remote/getItems"];
        },
...
```

I tried to change as 
```
return this.$store.getters["remote/getItems"].map(item => ({ ...item }));
```

But I obtain only a error because `.map is not a function`

**Comment by tmorehouse** [comment]
`.map` is an instance method of `Array`, and if the getter returns anything other than an Array it will fail

**Comment by realtebo** [comment]
Now I understand my issue  ...  so I will close this issue because is NOT related to your package

I was retrying data as a complex object, and so I must not `map` the feteched objected directly, but the `.data` property of it.

> For precision, for future googlers, I was fecthing paginated data from a Laravel Api.

I added a computed property

```
       recordData() {
            if (!this.record) return [];
            if (!this.record.data) return [];
            return this.record.data.map(item => ({ ...item }));
        },
```

and then I am using now this computed prop as source for the table

```
:items="recordData"
```

A lot of thanks for your help and patience

**Comment by tmorehouse** [comment]
Glad you found a solution.
