### ISSUE TITLE
b-pagination - initial value of currentPage is always 1

### ISSUE THREAD

**Issue by vkozelka** [bootstrap-vue/bootstrap-vue#5163]
### Describe the bug
If i use b-pagination component standalone and provide v-model, with hot reload plugin it works well, but when i refresh whole page the active page displayed is always 1.

### Steps to reproduce the bug

1. Create pagination component with v-model="currentPage"
2. Update variable will work well (Vue Debug in Chrome)
3. Set initial value to 2 (hot reload will show change)
4. Refresh page. You will see active page 1

### Expected behavior

Expected is displayed active page after refresh same like in ina-app change

### Versions

**Libraries:**

- BootstrapVue: 2.11.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: MacBook Pro (Late 2018)
- OS: MacOS Catalina
- Browser: Chrome
- Version: 80.0.3987.163

### Demo link

Cannot reproduce, becuase internal and highly secured app

### Additional context

The v-model for b-pagination goes from mixin

**Comment by tmorehouse** [comment]
Hot reload maintains state (in most cases), while a page reload will rest all states.

**Comment by vkozelka** [comment]
> Hot reload maintains state (in most cases), while a page reload will rest all states.

Yes, understand that, but i am sure, that variable is valid in created hook always and is valid
If i do v if and after full reload make the if condition valid, it always shows me first page active until i change to other value

**Comment by tmorehouse** [comment]
Could you provide any sample code that reproduces the error?

**Comment by vkozelka** [comment]
I am sorry, but no.. 

maybe one info can be important, that initial value of currentPage is in localStorage saved but is valid in index.js before mounting vue root

**Comment by tmorehouse** [comment]
Perhaps when restoring the value, use beforeMount() rather than mount()

**Comment by vkozelka** [comment]
> Perhaps when restoring the value, use beforeMount() rather than mount()

It is same.. always first page is active

**Comment by tmorehouse** [comment]
We would need to see a minimal reproduction of the issue before we can help.

**Comment by vkozelka** [comment]
Okay, i think i got it.. 

Example: https://codepen.io/kesavcz/pen/VwveNWK

if you take a look on it.. 
when i save variable to localStorage and make full refresh, i see page 1 instead of configured from localstorage

**Comment by Hiws** [comment]
You're currently doing 
`this.currentPage = Number(currentPage.page);`, but you're saving it to localStorage as `currentPage`.
Meaning it should be `this.currentPage = Number(currentPage.currentPage);` instead.

https://codepen.io/Hiws/pen/wvKGwVB
