### ISSUE TITLE
b-dropdown-Item not showing on specific href-binding (Firefox)

### ISSUE THREAD

**Issue by afshad1** [bootstrap-vue/bootstrap-vue#5164]
### Describe the bug
https://wa.me/?text=fdgfd

b-dropdown-item is dissappearing and not showing on Firefox when set a specific href binding (WhatsApp Sharelink):
- `https://wa.me/?text=MyTextToShare`

The b-dropdown-item is reappearing when changing the text to
- `https://wa.me/?text1=MyTextToShare` or
- `https://www.wa.me/?text1=MyTextToShare` or
- `https://we.me/?text=MyTextToShare`

Unfortunately I cannot identify the root cause for this issue.

### Steps to reproduce the bug

1. Go to https://codesandbox.io/s/sweet-kare-pwg4t?file=/App.vue with Firefox
2. See b-dropdown-item is not showing
2. Change text in getLink() method to strings stated above.
3. See b-dropdown-item is showing

Try the same on Chrome - there seems to be no issues here.

### Expected behavior

Same behaviour on all browsers.

### Versions

**Libraries:**

- BootstrapVue: 2.11.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 75 (64-bit)

### Demo link

https://codesandbox.io/s/sweet-kare-pwg4t?file=/App.vue

**Comment by tmorehouse** [comment]
It looks like firefo is not respecting the redirect (and passing the GET query params) from the `wa.me` domain.

This appears to be a browser issue, and not an issue with BootstrapVue.

Creating a plain link:

```html
<a :href="getLink()" target="_blank">test Link</a>
```

returns this error:

```
The address wasn’t understood

Firefox doesn’t know how to open this address, because one of the following protocols (whatsapp) isn’t associated with any program or is not allowed in this context.

    You might need to install other software to open this address.
```

The resultant redirected URL is:

```
whatsapp://send/?phone&text=MyTextToShare&source&data&app_absent
```

**Comment by afshad1** [comment]
Wow, wasnt expecting an answer this fast. 
I was just doing some more testing and was about to write as I also found out this appears to happen on b-link (or general plain link) as you have described.
So this seems to be not bootstrap-vue related and I am closing this issue.

Thank you.
