### ISSUE TITLE
Formatter settings for input and textarea

### ISSUE THREAD

**Issue by kohichikoyama** [bootstrap-vue/bootstrap-vue#5165]
### Describe the bug

When formatter is set to textarea, the cursor position is moved to the end of the sentence.
Getting the cursor position and setting it does not work well.
But if you go back to "event.target.value" and put a character in it, it will work.

### Steps to reproduce the bug

1. Set the formatter to b-form-textarea
2. Get the cursor position in the formatter code.
3. Putting the code to capitalize the formatter code
4. Set the cursor position to the formatter code.
5.The cursor position of the textarea is moved to the end of the sentence.

### Expected behavior

Can set the cursor position without inputting 'event.target.value'.

### Versions

**Libraries:**

 -  BootstrapVue: 2.11.0
 -  Bootstrap: 4.4.1
 -  nuxt: 2.12.2

**Environment:**

- Device: PC
- OS: Windows10
- Browser: firefox
- Version: 75

### Demo link

NG:demo : https://jsfiddle.net/d3e5194f/1/
OK:demo:  https://jsfiddle.net/d3e5194f/2/

### Additional context

b-form-input works the same way

**Comment by tmorehouse** [comment]
This is an issue with the formatter, which should only be used for simple things (like capitalization, etc) when not lazy.

**Comment by tmorehouse** [comment]
It is best suggested to use a 3rd party library for formatting such as `v-mask`, etc, which are tailored to special case formating

**Comment by kohichikoyama** [comment]
Thank you
