### ISSUE TITLE
Preset property "BTooltip.noninteractive" in Vue.use(BootstrapVue, ...)

### ISSUE THREAD

**Issue by stefanpartheym** [bootstrap-vue/bootstrap-vue#5166]
Currently I'm not able to preset the value for the `noninteractive` option for the `BTooltip` component and the `v-b-tooltip` directive.

When trying to set it with this:
```
Vue.use(BootstrapVue, {
  BTooltip: {
    noninteractive: true
  }
});
```
... my browser throws a warning: 
```
[BootstrapVue warn]: BvConfig - Unknown config property "BTooltip.noninteractive"
```

Well this makes sense, since the documentation states the following available options on module initialization (https://bootstrap-vue.js.org/docs/misc/settings/#default-bootstrapvue-configuration):
```
  "BTooltip": {
    "boundary": "scrollParent",
    "boundaryPadding": 5,
    "customClass": null,
    "delay": 50,
    "variant": null
  }
```

However I'd like to set the noninteractive option by default. This would save me providing the `.noninteractive` option everytime I use the directive.

Is this currently possible? My current workaround is to set `delay` to `0`, which is a bit ugly but kinda works.

Thanks a lot in advance!

**Comment by tmorehouse** [comment]
Currently we do not allow Boolean props to be set in the configuration, as it changes the "meaning" of the prop name (specifically for the `no-` and `hide-` type props).  If you are using any 3rd party bootstrap vue libraries with your project, and they expect their tooltips/popover to be `interactive` by default, they wont be.  So in short, any on/off boolean props cannot be defaulted int he configuration.

**Comment by stefanpartheym** [comment]
Thanks for the fast response!
Would it be possible to create a custom directive, that wraps the `v-b-tooltip` directive and presets the `noninteractive` property there?

**Comment by tmorehouse** [comment]
Directive definitions are just objects with `bind`, `unbind`, `updated`, and `componentUpdated` properties, so it should be possible to import them, and extend those objects.  Just be casefull not to overwrite the properties...

```js
import { VBTooltip } from 'bootstrap-vue'

export const myNewDirective = {
  ...BVTooltip,
  bind(el, binding, vnode) {
     // do something here to massage the options in `binding`
     // Pass onto VBTooltip to do the rest of the work
     VBTooltip.bind(el, binding, vnode)
  }

**Comment by stefanpartheym** [comment]
Thanks! I think this will help. Feel free to close this issue.
