### ISSUE TITLE
b-table selection behavior

### ISSUE THREAD

**Issue by dshulzhenko** [bootstrap-vue/bootstrap-vue#5172]
Currently on single selection mode, after select row at next click/space/enter on **same row** it will be deselected.  
It would be nice to have an option to do not deselect current selected same row, seems like at start on range selection (without "shift" pressing).

**Comment by tmorehouse** [comment]
This is the expected behaviour in single select mode, which mimics the single select of most operating systems (click one to select, click a second time to deselect). Changing this behaviour would be confusing to screen reader users (as they expect the standard select/deselect behaviour)
