### ISSUE TITLE
datalist support on b-form-tags

### ISSUE THREAD

**Issue by smithtonson** [bootstrap-vue/bootstrap-vue#5174]
### Is your feature request related to a problem? Please describe...

the list attribute (for datalist options) isn't supported on b-form-tags component. The "list" attribute and value are set on the wrapper div instead of the input element.

### Describe the solution you'd like

if a "list" attribute is set on b-form-tags pass the value down to the input element

**Comment by tmorehouse** [comment]
You can pass arbitrary attributes via `input-attrs` prop, which will be applied to the nested input element:

```html
<template>
  <div>
    <b-form-tags v-model="tags" :input-attrs="{ list: 'tags-list' }">
    </b-form-tags>
    <b-form-datalist id="tags-list" :options="tagsOptions">
    </b-form-datalist>
  </div>
</template>
```

`<b-form-tags>` props reference: https://bootstrap-vue.js.org/docs/components/form-tags#comp-ref-b-form-tags-props

`<b-form-datalist>` helper component: https://bootstrap-vue.js.org/docs/components/form#datalist-helper


Alternatively, you can use the standard `<datalist id="tags-list">` markup with child `<option>` elements

**Comment by smithtonson** [comment]
Thanks, didn't even think of that even though I saw it in the docs.
