### ISSUE TITLE
don't render empty b-input-group-append or prepend

### ISSUE THREAD

**Issue by chumager** [bootstrap-vue/bootstrap-vue#5176]
### Is your feature request related to a problem? Please describe...
Hi, I've a base component to display and acquire data, if the **state** of the component is "input", then it renders an input or I can change the slot to other component... it has a input-group structure, but I don't know before if the extended component will use append or prepend slots... 
To solve this I use other slot from my base component to inject data into the append or prepend slot of input-group.
The problem is if I use your slot it'll render a `<div>` anyway and you have a conditional class to define the border-radius.

A clear and concise description of what the problem is.

the problem is you render the slots for append or prepend even id they are empty so your conditional class match and loose the rounded borders.

### Describe the solution you'd like

if those slots are empty they shouldn't be rendered.
 
### Describe alternatives you've considered

Maybe add an attribute to wrap the content or no-wrap, so if the subcomponent has this attribute then is not wrapped and the empty content will keep empty.

**Comment by tmorehouse** [comment]
Could you provide a sample of your component markup?

You can do something similar to the following to conditionally pass slots to a child component:

```html
<template>
  <b-form-group>
    <template v-if="$slots.prepend" v-slot:prepend>
      <slot name="prepend"></slot>
    </template>
    <slot>
      <b-form-input></b-form-input>
    </slot>
    <template v-if="$slots.append" v-slot:append>
      <slot name="append"></slot>
    </template>
  </b-form-group>
</template>
```

**Comment by chumager** [comment]
Hi, thanks for the answer, my problem is I don't have a slot. I'm using a special loader so I can use extended components with extended templates. I had it that way before, but now I can't, that's why I don't know if the extended component have that vNode or not.

Can you tell me if you wrap the slot? If you don't wrap, it's the loader who wraps the empty tag so it doesn't matter what you do the tag will exists even if you don't wrap it.

Best regards.

**Comment by tmorehouse** [comment]
If the slot is present (appears defined in `this.$slots/$scopedSlots`), the content will appropriately be wrapped in `<b-input-group-prepend>` or `<b-input-group-append>` (depending on the slot used).

You don't need the slots, and can use the actual child components:

```html
<template>
  <b-input-group>
    <b-input-group-prepend v-if="showPrepend">
      <!-- place content here -->
    </b-input-group-prepend>
    <slot>
      <b-form-input></b-form-input>
    </slot>
    <b-input-group-append v-if="showAppend">
      <!-- place content here -->
    </b-input-group-append>
  </b-input-group>
</template>
```

**Comment by chumager** [comment]
that's my problem I can't know if it'll be a prepend nor append, if I put a condition to know it I'll loose all the work to decrease the complexity of the component... 

I don't know if I'm clear enough, so let me show you one example.

This is the base component:

```vue
<template extendable>
  <div :class="GIClass" :style="GIStyle">
    <extension-point name="Extra" />
    <template v-if="inputSwitch === 'tableView'">
      <template v-if="altView">
        <extension-point name="altView">
          <span>Debe agregar el extensión point altView, ya que la variable altView tiene valor {{altView}}</span>
        </extension-point>
      </template>
      <template v-else>
        <extension-point name="View">
          <span v-if="!localLink">{{ localLeft }}{{ formatter(tableViewValue) }}{{ localRight }} </span>
          <b-link
            v-else
            @click="
              row.toggleDetails();
              localClick();
            "
            v-text="
              row.detailsShowing
                ? $attrs['hide-text'] || 'Ocultar'
                : $attrs['show-text'] || (tableViewValue ? tableViewDisplay : '')
            "
          />
        </extension-point>
      </template>
    </template>
    <template v-if="inputSwitch === 'tableDetail'">
      <h2>{{ field.detail || field.label || field.key }}</h2>
      <template v-if="altDetail">
        <extension-point name="altDetail">
          <span>Debe agregar el extensión point altDetail, ya que la variable altDetail tiene valor {{altDetail}}</span>
        </extension-point>
      </template>
      <template v-else>
        <extension-point name="Detail">
          <pre v-html="localValue" />
        </extension-point>
      </template>
    </template>
    <template v-if="inputSwitch === 'Input'">
      <template v-if="altInput">
        <extension-point name="altInput">
          <span>Debe agregar el extensión point altInput, ya que la variable altInput tiene valor {{altInput}}</span>
        </extension>
      </template>
      <template v-else>
      <extension-point name="Input">
        <b-input-group :prepend="localLeft" :append="localRight" :size="localSize">
          <b-input-group-prepend>
            <extension-point name="prepend" />
          </b-input-group-prepend>
          <component
            :is="localTag"
            ref="input"
            class="input"
            v-model="localValue"
            :type="localType"
            :plaintext="plaintext"
            v-bind="{
              ...input,
              state: typeof $attrs.state === 'boolean' ? $attrs.state : input && input.state,
              ...attrs,
            }"
            :lazy-formatter="lazyFormatter"
            :formatter="formatter"
            :lazy="localLazy"
            :size="localSize"
            @keypress.native="keypress($event)"
            @focus.native="$emit('focus', $event)"
            @blur.native="$emit('blur', $event)"
            v-on="listeners"
            :disabled="localDisabled"
            :readonly="localReadonly"
            :autocomplete="$attrs.autocomplete || 'off'"
          />
          <b-input-group-append v-if="!plaintext">
            <extension-point name="append" />
          </b-input-group-append>
        </b-input-group>
        <extension-point name="postInput" />
      </extension-point>
      </template>
    </template>
  </div>
</template>
```

a extended component with just a little logic changed:

```vue
<script>
/*global numeral*/
import GenericInput from "./GenericInput";
export default {
  extends: GenericInput,
  data() {
    return {
      left: "$"
    };
  },
  methods: {
    initVal: v => (["number", "string"].includes(typeof v) && numeral(v).format("0,0")) || 0,
    emitter: v => numeral(v).value(),
    formatter: v => v && numeral(v).format("0,0"),
    keypress(e) {
      !this.isNumber(e.key) && e.preventDefault();
    }
  }
};
</script>
```
this component doesn't change anything but adding a text prepend "$", but others may add buttons, selects or anything... and some others like for string or number adds nothing. the Base component doesn't have info about it because in the transpilation process the "extension" and "extension-point" tags are merged, so there is no way I can know before what's going to happen in the extended component. If I add the conditional rendering then it misses all the purpose to do it that way.

If I use the ```<template #prepend>``` it creates the div either way. 

I'm not a CSS expert but I'll try to see if it's possible to check the previous sibling to see if it's empty so I can help with this.

Best regards.

**Comment by tmorehouse** [comment]
I am not familiar with the `<extend-point>` component (nor the `extendable` option on the template root).  Is this some 3rd party vue-loader plugin and component?

**Comment by tmorehouse** [comment]
```html
          <b-input-group-prepend>
            <extension-point name="prepend" />
          </b-input-group-prepend>
```

What triggers content for `<extension-point name="prepend" />`? is it a slot passed to the extended component? is it a method or data/computed property on the extended component?

**Comment by chumager** [comment]
yes... it allows you to use the template as extension besides the component itself, so you don't need to use the base component as extends and as component to extend the layout and inner logic...

I was investigating and maybe you can change the conditional class to something like:
```css
.input-group > .input-group-prepend:not(:empty) ~ .form-control {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
}
```
what do you think?

I'm still searching for a selector for previous sibling, but it seems there is no such selector.

**Comment by tmorehouse** [comment]
I would rather not override the current Bootstrap v4.4 styles (that most likely will tick other users off).  It might be better if you provided your own scoped styles to override Bootstrap's styles as part of your base extendable component.

**Comment by chumager** [comment]
> ```
>           <b-input-group-prepend>
>             <extension-point name="prepend" />
>           </b-input-group-prepend>
> ```
> 
> What triggers content for `<extension-point name="prepend" />`? is it a slot passed to the extended component? is it a method or data/computed property on the extended component?

If my extendable component has an ```<extension-point name="xxx">``` tag, the extended component can change it for the content in ```<extension point="xxx">``` so the component can be completely extendable...

**Comment by tmorehouse** [comment]
But I do not see an example of that usage....  as i said  I am unfamiliar with that template loader.  Perhaps provide an example of how the extended component is used in an app (i.e. the markup used)?

**Comment by chumager** [comment]
> I would rather not override the current Bootstrap v4.4 styles (that most likely will tick other users off). It might be better if you provided your own scoped styles to override Bootstrap's styles as part of your base extendable component.

You are right, my first try to change the prepend worked out well, I've to search how to modify the append behavior...

Thanks a lot.

Regards.

**Comment by chumager** [comment]
Hi, I've made this modifications, just in case it'll help someway to others.

This works also with async components...

Add this css for the case the prepend is empty:
```css
.input-group > .input-group-prepend:empty ~ .form-control, .input-group > .input-group-prepend:empty ~ .custom-select {
    border-top-left-radius: 0.25rem;
    border-bottom-left-radius: 0.25rem;
}
```

Add this JS to the component:
```js
  mounted() {
    //check for no children in append
    const target = this.$refs.append; //remember to add the ref to b-input-group-append
    if(target.childElementCount===0){
      target.previousElementSibling.style.borderTopRightRadius="0.25rem";
      target.previousElementSibling.style.borderBottomRightRadius="0.25rem";
    }
  },
  updated(){
    //check for children in append
    const target = this.$refs.append;//remember to add the ref to b-input-group-append
    if(target.childElementCount){
      target.previousElementSibling.style.borderTopRightRadius="0";
      target.previousElementSibling.style.borderBottomRightRadius="0";
    }
  },
```

Regards...
