### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by Zyles** [bootstrap-vue/bootstrap-vue#518]
I tried the tabs example in the docs but I can't get it to work.

I see the tabs "first" "second" etc.

But not the content itself.

Not sure what is wrong or how to debug.

**Comment by tmorehouse** [comment]
If you use your browser developer tools/console, can you see the elements rendered in the DOM?  It might be a matter of the order your CSS is imported.

**Comment by tmorehouse** [comment]
Check issue #515, as it might be a similar issue.

**Comment by Zyles** [comment]
Yes the content is there and when I click the tabs it changes the classes to `tab-pane show fade active`

For example:

```
<div role="tabpanel" aria-hidden="false" aria-expanded="true" class="tab-pane show fade active">
        I'm the second tab content
      </div>
```

It is the "fade" class which makes it invisible.

**Comment by tmorehouse** [comment]
Which version of bootstrap-vue are you using? v0.16.1 is the latest (and v0.17.0 is coming soon)

**Comment by tmorehouse** [comment]
The following fiddle works: https://jsfiddle.net/sy3oz4zv/

**Comment by tmorehouse** [comment]
@Zyles 

Release v0.18.0 is now available.  Can you try it out to see if you still have the issues?

**Comment by tmorehouse** [comment]
Closing due to no feedback.

**Comment by mykytak** [comment]
`2.0.0-rc.11`, problem is still here.
I think there's some conflict with default Laravel styles. Because it works good without app.css included. And stop showing content with it (can be solved with `.fade.show {opacity: 1}`).

Laravel Framework 5.5.40, in npm only default packages + bootstrap-vue.

**Comment by pascalfriedrich** [comment]
Same problem here, without laravel.
