### ISSUE TITLE
Loading chunk 8 failed.

### ISSUE THREAD

**Issue by meceway** [bootstrap-vue/bootstrap-vue#5183]
### Documentation issue

Mixed Content: The page at 'https://bootstrap-vue.js.org/sw.js' was loaded over HTTPS, but requested an insecure resource 'http://bootstrap-vue.js.org/docs/components/carousel/'. This request has been blocked; the content must be served over HTTPS.

The FetchEvent for "https://bootstrap-vue.js.org/docs/components/carousel" resulted in a network error response: the promise was rejected.

workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://bootstrap-vue.js.org/docs/components/carousel"}]
    at a.makeRequest (https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-strategies.prod.js:1:2145)
n   @ workbox-core.prod.js:1
makeRequest   @ workbox-strategies.prod.js:1

**Comment by tmorehouse** [comment]
You may have and older version of the docs cached.

Do a shift+reload to clear your cache for the website.

**Comment by joelschuster** [comment]
Have tried again, get 404 trying to get to https://bootstrap-vue.js.org

![image](https://user-images.githubusercontent.com/538027/79696779-f7c84500-823b-11ea-967c-6d178ce42975.png)

**Comment by jackmu95** [comment]
Closes in favor of #5186.
