### ISSUE TITLE
quebrou o site doidão

### ISSUE THREAD

**Issue by hafael** [bootstrap-vue/bootstrap-vue#5185]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

### Additional context or description

Provide any additional details here as needed.

**Comment by thhan** [comment]
Do you mean, the website is offline?

**Comment by macias67** [comment]
Yes it is, https://bootstrap-vue.js.org/

**Comment by jarayabozo** [comment]
https://bootstrap-vue.js.org/   offline

**Comment by craigmpeters** [comment]
Yeah looks like it is down currently

**Comment by tomlankhorst** [comment]
https://bootstrap-vue.netlify.app

**Comment by thhan** [comment]
Thank you @tomlankhorst

**Comment by jackmu95** [comment]
Closed in favor of #5186.
