### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Mokesh-official** [bootstrap-vue/bootstrap-vue#5186]
### Documentation issue

https://bootstrap-vue.js.org/ 
The site is down

**Comment by dacoto97** [comment]
![image](https://user-images.githubusercontent.com/16915053/79696912-d0936700-827f-11ea-91e4-d58aebafb849.png)

**Comment by pasenidis** [comment]
The docs are indeed down, someone removed the deployment from ZEIT.
As far as I can understand they are moving to Netlify from ZEIT or something like that.
This works for me: [https://bootstrap-vue.netlify.app/](https://bootstrap-vue.netlify.app/)

**Comment by dacoto97** [comment]
@pasenidis Thank you very much, it works perfectly

**Comment by pasenidis** [comment]
Glad I helped you.

**Comment by jackmu95** [comment]
We are in the process of moving our website to a new hosting provider and currently struggle with DNS related issues. We try to get this sorted out as quickly as possible!

In the meantime you can view the website at:
https://bootstrap-vue.now.sh/

**Comment by bitaxis** [comment]
Verified that both links work.  Will both continue to work?

- https://bootstrap-vue.netlify.app/
- https://bootstrap-vue.now.sh/

**Comment by tmorehouse** [comment]
https://bootstrap-vue.netlify.app/ is the dev documentation site (includes features not yet released)

https://bootstrap-vue.now.sh/ is the current released version documentation.

**Comment by jackmu95** [comment]
The website is back up again :tada:
