### ISSUE TITLE
Docs: Reference > Form Validation > Vee Validate 3 Example

### ISSUE THREAD

**Issue by rbndm** [bootstrap-vue/bootstrap-vue#5190]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.js.org/docs/reference/validation

### Additional context or description

In Vee Validate, since 3.1.0, `passes()` was renamed to `handleSubmit()` .  See https://logaretm.github.io/vee-validate/migration.html#renamed-validationobserver-passes-slot-prop-method

**Comment by jackmu95** [comment]
Example is now updated.
