### ISSUE TITLE
Please add support for html in b-table formatter method. 

### ISSUE THREAD

**Issue by wovosoft** [bootstrap-vue/bootstrap-vue#5195]
We can currently use slots to customize the output for a certain cell using slot scopes. But it would be really great if we can output html using formatter method. The formatter method currently outputs only text. 

For example , 
```html
<template v-slot:cell(image)="row">
         <b-img-lazy :src="row.item.image"></b-img-lazy>
 </template>
```
the above one is easy and helpful. But we can't output the img using formatter. I am not sure if I am wrong.

**Comment by tmorehouse** [comment]
You can do this indirectly with combination of formatter and scoped slots. the scope `value` will be the output of the formatter, and then you can use a slot to `v-html`

```html
<b-table ... >
  <template v-slot:cell(somefield)="scope">
    <div v-html="scope.value"></div>
  </template>
</b-table>
```

This is discussed in the docs at https://bootstrap-vue.js.org/docs/components/table#displaying-raw-html

**Comment by tmorehouse** [comment]
Note as well, `v-html` supports only HTML, and not components.  Vue does not compile the content passed to `v-html` (`v-hmtl` translates directly to the DOM method `element.innerHTML`)
