### ISSUE TITLE
Time picker doesn't display 12:00 correctly (in hour12 mode)

### ISSUE THREAD

**Issue by glennschmidt** [bootstrap-vue/bootstrap-vue#5199]
### Describe the bug

Using `<b-form-timepicker hour12>`, it doesn't display 12am and 12pm the way i would expect (in a region that uses 12-hour time).

* Midnight should be displayed as `12:00 am`; instead it's displayed as `0:00 am`
* Midday should be displayed as `12:00 pm`; instead it's displayed as `0:00 pm`

![Screen Shot 2020-04-21 at 12 37 14 pm](https://user-images.githubusercontent.com/1758170/79819396-3fcaa180-83cd-11ea-8a0a-96e6fa2fcbde.png)

### Versions

**Libraries:**

- BootstrapVue: 2.11.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS 10.15.4
- Browser: Chrome
- Version: 81

**Comment by tmorehouse** [comment]
Yeah, I noticed when creating the component, and trying to force 12hour mode.  Some implementations of `Intl.DateTimeFormatter` do not handle the `hour12` override on some locales.

What locale are are you using?

**Comment by glennschmidt** [comment]
My machine is set to `en-AU`, although `window.navigator.language` in Chrome returns `en-US`

**Comment by tmorehouse** [comment]
Could you try adding `@context="console.log($event)"` to the timepicker to see what locale is being resolved?

**Comment by glennschmidt** [comment]
The context event returns `en-GB` for some reason

**Comment by tmorehouse** [comment]
Strange.  you may need to set `locale="en-AU"`

**Comment by tmorehouse** [comment]
When I set `local="en-AU"` I see:

![image](https://user-images.githubusercontent.com/2781561/79820448-9ea70100-8362-11ea-91b3-2cf3914aeb20.png)

**Comment by tmorehouse** [comment]
and when i set `local="en-GB" hour12`:

![image](https://user-images.githubusercontent.com/2781561/79820732-52a88c00-8363-11ea-8c6b-5de4a4edb158.png)

Notice the resolved `hourCycle` is `h11`

**Comment by glennschmidt** [comment]
Yep, manually setting `locale` (instead of setting `hour12`) resolves the problem. In fact even just setting `locale="en"` (like the [demo does](https://bootstrap-vue.js.org/docs/components/form-timepicker/)) seems to cause it to work fine and be in 12-hour mode. I guess I'll just do that for the time being
