### ISSUE TITLE
Datepicker styling is broken (wrong width?)

### ISSUE THREAD

**Issue by digitalcortex** [bootstrap-vue/bootstrap-vue#5210]
### Describe the bug

In our project we are trying to use datepicker but it keeps having broken layout. Please see the screenshots attached for details. Increasing style width of the element with id: "__BVID__73__calendar-wrapper_" seems to be solving the issue but it can't be done via Vue code without dirty hacks.

### Steps to reproduce the bug

Add a datepicker vue component to your view.
`<b-form-group label="Date of Birth" label-for="edit-input-dateofbirth" class="mr-2">
          <b-form-datepicker
            id="edit-input-dateofbirth"
            v-model="form.dateOfBirth"
          ></b-form-datepicker>
        </b-form-group>`

### Expected behavior

Layout supposed to be correct (like in examples)

### Versions

**Libraries:**

- BootstrapVue: 2.11.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Brave
- Version: Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)

### Additional context

I'm attaching the screenshots with details:
<img width="678" alt="calendar-broken" src="https://user-images.githubusercontent.com/62620810/79906339-af21af00-8428-11ea-891e-5bda6a934e1a.png">
<img width="1092" alt="incorrect width" src="https://user-images.githubusercontent.com/62620810/79906429-cd87aa80-8428-11ea-86c7-e7684324f80c.png">
<img width="1091" alt="solution" src="https://user-images.githubusercontent.com/62620810/79909901-cd8aa900-842e-11ea-9971-c342c8f57328.png">

**Comment by tmorehouse** [comment]
try upgrading to BootstrapVue version 2.12.0, which has some fixes for Datepicker styles.

It sounds like you might have custom padding/margin SCSS variables (the base `$spacer` value).

**Comment by digitalcortex** [comment]
> Try upgrading to BootstrapVue version 2.12.0, which has some fixes for Datepicker styles.
> 
> It sounds like you might have customized padding/margin SCSS variables (the base `$spacer` value).
> 
> Related issue: #5117
> Related Fix PR: #5121
> Fix Released in BootstrapVue v2.12.0
> 
> Also note that there is a `calendar-width` prop on `<b-form-datepicker>` (introduced in v2.6.0) that defaults to `270px`

Thank you tmorehouse, I updated to 2.12.0 and used calendar-width property. It works fine now. However after update the field itself started looking weird (icon is below the field, field is bigger than others). It happened just after update. How to fix it?
<img width="1001" alt="offset" src="https://user-images.githubusercontent.com/62620810/79917900-77246700-843c-11ea-91b8-ed2c276c479b.png">

**Comment by digitalcortex** [comment]
> Try upgrading to BootstrapVue version 2.12.0, which has some fixes for Datepicker styles.
> 
> It sounds like you might have customized padding/margin SCSS variables (the base `$spacer` value).
> 
> Related issue: #5117
> Related Fix PR: #5121
> Fix Released in BootstrapVue v2.12.0
> 
> Also note that there is a `calendar-width` prop on `<b-form-datepicker>` (introduced in v2.6.0) that defaults to `270px`

By the way, I did not touch $spacer value at all.

**Comment by tmorehouse** [comment]
Make sure you are using the latest BootstrapVue v2.12.0 CSS as well (and that it is included _after_ Bootstrap v4.4 CSS is imported).

**Comment by digitalcortex** [comment]
> Make sure you are using the latest BootstrapVue v2.12.0 CSS as well (and that it is included _after_ Bootstrap v4.4 CSS is imported).

I'm thankful, it worked!

**Comment by nikeza** [comment]
put in main.js :
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
