### ISSUE TITLE
b-form-select-option missing :title attribute support

### ISSUE THREAD

**Issue by sam-araiza** [bootstrap-vue/bootstrap-vue#5214]
### Describe the bug

Context: b-form-select and b-form-select-option.
When I select an option with a specified :title attribute, the text in the title attribute is not displayed and remains showing what is in the "text" attribute.

### Steps to reproduce the bug

```
<b-form-select v-model="selected">
      <b-form-select-option v-for="option in options" :key="option.key" :title="option.label" :value="option.value">
        {{ option.label }} - Recommended Option
      </b-form-select-option>
    </b-form-select>
```

### Expected behavior

The selected option text should show the text specified in the title attribute and not be 1:1 with the dropdown option text provided in the :text attribute.

Example: https://developer.snapappointments.com/bootstrap-select/examples/
in the "Selected text" Combo example.

### Versions

**Libraries:**

- BootstrapVue: 2.2.1
- Bootstrap: 4.4.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Chrome v80.0.3987.163

**Comment by tmorehouse** [comment]
`:title="option.label"` is being applied to the rendered `<option>` as an attribute. e.g.:

```html
<option title="some title">some value</option>
```

Note `<b-form-select>` is just a wrapper around a styled native `<select>` element, and is not a custom select/combo-box component.  You can see this by inspecting the rendered output.

**Comment by sam-araiza** [comment]
@tmorehouse Ah, so it's not even a supported "feature," by either bootstrap or bootstrap-vue (wrapper). Sorry for the misunderstanding. Thanks!
