### ISSUE TITLE
How to add .invalid-feedback div on input field?

### ISSUE THREAD

**Issue by RyanSacks** [bootstrap-vue/bootstrap-vue#5215]
### Describe the bug
Hi, I'm trying to add required .invalid-feedback div with message "The name field is required" etc. but when I put a div or a span with class .invalid-feedback in or under my form group, of course it should be hidden by default, but I can't even see the HTML when I inspect the code. Is there a special tag or way to do this?

- BootstrapVue: ^2.11.0
- Bootstrap: ^4.4.1
- Vue: ^2.5.17

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome

### Additional context

What would be great would be to make the required fields have a red outline as oppose to the text underneath the input, but either way is fine.

**Comment by tmorehouse** [comment]
Could you provide an example of your markup you are currently trying?

Also not the `.invalid-feedback` needs to be an immediate sibling to an input.  Placing it outside of the form-group makes the feedback no longer a sibling of the input.  either place the feedback inside the form-group after the input, or take advantage of the built in features of `b-form-group` which handles the invalid and valid feedback for you.

**Comment by RyanSacks** [comment]
I'm so sorry, I thought I did.

<b-form-group label="Experience" label-for="experience">
    <b-form-textarea
        id="experience"
        v-model="editProfileData.experience"
        placeholder="Tell us a little about your experience..."
        :rows="10"
        :max-rows="12"
    >
    </b-form-textarea>
    <div class="invalid-feedback" v-if="errors.experience">{{
errors.experience[0] }}</div>
</b-form-group>

This code for example, when I inspect the code, the <div> isn't there. I'm
not sure how the b-form-group handles validation, I will have to look into
it, but I need to display my server side validation somehow and I think the
server side validation is more important than the client side. I'm just not
sure, why the div isn't there.

**Comment by tmorehouse** [comment]
Check out hte form group docs re validation states and feedback examples: https://bootstrap-vue.org/docs/components/form-group

The first example shown includes the use of validation feedback, in combination with the `state` prop to show the feedback

**Comment by RyanSacks** [comment]
Can I input my error validation variables in there? State or prop?

**Comment by tmorehouse** [comment]
I'm not sure why the div is not present in the DOM.  Does it show in the inspector?

In general, invalid feedback will not visible show in the rendered page until the input is validated (by the browser), or the input has it's prop `:state="false"` (which forces the invalid state)

**Comment by tmorehouse** [comment]
The `state` prop found on most `b-form-*` inputs (and also on the `b-form-group`) is a tri-state prop which accepts the boolean values `true` (valid) or `false` (invalid), or the value `null` (no validation state).

The form validation helpers also have a `state` prop which will force the validation state to trigger the feedback to show or hide.

**Comment by RyanSacks** [comment]
Okay, thank you. Yeah it's weird, it doesn't show in the inspector. I have server side validation present and I've set .invalid-block class to display: inline-block; This gets it to show when an error occurs. It's weird it's working in most of my pages, except it's in a <b-modal>. I don't know if that has anything to do with it. I know it shouldn't effect it...
