### ISSUE TITLE
Issues with popovers used alongside modals.

### ISSUE THREAD

**Issue by steneva** [bootstrap-vue/bootstrap-vue#5216]
### Describe the bug

I've noticed the following things while trying to use popovers alongside modals:
1. **Popovers are shown above open modals.**
*I don't know if this is the correct repository for this question since it is more related to `bootstrap`.*
This was obviously intended as it is documented [here](https://getbootstrap.com/docs/4.0/layout/overview/#z-index).
I've changed this by setting `z-index: 1035;` to popovers, but I can't seem to figure out why popovers/tooltips should be shown above modals by default.
2. **Popovers with `triggers="manual"` are not shown in modals.**
Changing the value of the property that `show` binds to or setting `show` to `true` directly does not trigger popover show.
3. **All opened (visible) popovers in modals are hidden after a child modal is opened and then closed.**
I tried to use `e.preventDefault()` in the callback of the `hide` event of the popover when hiding was unnecessary, but it didn't work.

I'm not sure if these are actual issues or I'm simply missing something.

### Expected behavior

1. Modals should be shown above popovers/tooltips?
2. Popovers with `triggers="manual"` should be shown in modals.
3. Opened (shown) popovers in modal should still be opened after a child modal is closed.

### Versions

**Libraries:**

- BootstrapVue: 2.12.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

### Demo link

[codesandbox](https://codesandbox.io/s/bootstrap-vue-popovers-modals-pbtmp)

**Comment by tmorehouse** [comment]
Normally, when a modal opens, all popovers/tooltips will automatically close. But in your case, you have a manually opened popover which wont close when a modal opens.

Bootstrap v4 has the following z-indexes defined by default (controlled via SASS variants in their SCSS):

https://getbootstrap.com/docs/4.4/layout/overview/#z-index

> ```scss
> $zindex-dropdown:          1000 !default;
> $zindex-sticky:            1020 !default;
> $zindex-fixed:             1030 !default;
> $zindex-modal-backdrop:    1040 !default;
> $zindex-modal:             1050 !default;
> $zindex-popover:           1060 !default;
> $zindex-tooltip:           1070 !default;
> ```

As you can see they have tooltips and popovers at a higher z-index compared to modals.

If you are using SCSS instead of the pre-compiled CSS, you can bump the modal z-index to a value higher than 1070.

**Comment by steneva** [comment]
Thank you for your reply, but I think you misunderstood me.
Let me elaborate further on the questions:

1. **Popovers are shown above open modals.**
As I said in the issue, I've already figured out how to show modals above popovers/tooltips by setting a custom z-index.
The problem is that it just feels strange to me that by default modals have lower z-index than popovers/tooltips in `bootstrap`. I think this is a very common scenario (showing modals above popovers/tooltips) and should not require overriding bootstrap styles at all.
Also, I can't come up with a scenario where you'd actually need to show popovers above modals.

2. **Popovers with `triggers="manual"` are not shown in modals.**
As demonstrated in the reproduction repo, popovers with `triggers="manual"` are not shown in modals. Click-triggered popovers, on the other hand, do not seem to have this problem and work as expected.
It is possible that I'm missing something in the popover declaration, but the exact same code works fine if placed in the page (not in a modal).

3. **All opened (visible) popovers in modals are hidden after a child modal is opened and then closed.**
Here you said:

> As for tooltips and popovers that are created inside of modals, they will be closed/destroyed when the modal closes (we automatically append the tooltip/popover to a modal when they are also in a modal.

This is absolutely what I would expect, but my issue is actually different.
The problem is that opened popovers in **parent** modal are hidden once a **child** modal is closed. I don't think that this is an intended behavior and sadly I haven't been able to find a workaround for this issue.

Now about nested modals. You said that:

> Side note: One should also avoid placing another modal inside the body of a parent modal.

Is there a reason/limitation (other than user experience on small screens) not to use nested modals?
The app that I'm working on is intended to be used primarily on PC and in my case nested modals are a necessity.

Thanks in advance.

**Comment by tmorehouse** [comment]
Re nested modals:

It is possible to still have "stacked" modals (ones that open on top of each other), but avoid placing the modal markup inside of another modal's markup.

Do this:

```html
<b-button v-b-modal.modal1>Open Modal 1</b-button>
<b-modal id="modal-1" title="Modal 1">
  <b-button v-b-modal.modal2>Open Modal 2</b-button>
</b-modal>
<b-modal id="modal-2" title="Modal 2" size="sm">
  Hello World
</b-modal>
```

Rather than placing the markup of modal 2 inside modal 1

**Comment by tmorehouse** [comment]
Popovers/tooltips with trigger `manual` are shown when the show prop is set, but if the "trigger" element is not yet visible in the document DOM, then they won't open up (Popper.js needs access to a visible element for positioning).  For a manual popover/tooltip inside a modal, you may need to wait for the modal's `shown` event, which guarantees the modal content is in the DOM and the transition has completed. before setting the manual popover show state.
