### ISSUE TITLE
href on b-link is always rendered as # instead of the value

### ISSUE THREAD

**Issue by tristanbes** [bootstrap-vue/bootstrap-vue#522]
Hello,

I might have done something wrong but the `href` value is never rendered on`b-link`. Instead default value `#` is displayed.

Example on an `b-table` item (notice the `route` attribute) :
<img width="403" alt="metadata_title_account_list_cv" src="https://user-images.githubusercontent.com/346010/27254357-1308a3f0-5387-11e7-9315-1d3bb7ea255d.png">

Then on the table template itself : 
```vue
<template slot="actions" scope="item">
    <b-link :href="item.route" :disabled="false" class="btn btn-primary" size="sm" variant="primary" >
      {{ 'thread.read'|trans }}
    </b-link>
</template>
```

is rendered as 
```html
<a aria-disabled="false" href="#" class="btn btn-primary" size="sm" variant="primary">
   thread.read
</a>
```

When I dump the `item` it gives me: 
```
{ "item": { "status": true, "name": "joueur", "team": "dumb name", "cv": "dumb cv.", "route": "/app_dev.php/thread/147739/read", "createdAt": "a month ago", "isRead": false }, "index": 0 }
``` 

Is this a bug or something on my end ?

(Vue 2.3.3, boostrap-vue ^0.16.1)

**Comment by tmorehouse** [comment]
Ah, you have a slight issue in how you are referencing the row data in the scoped slot.

Change your slot to the following:

```html
<template slot="actions" scope="item">
    <b-link :href="item.item.route" :disabled="false" class="btn btn-primary" size="sm" variant="primary" >
      {{ 'thread.read'|trans }}
    </b-link>
</template>
```

`scope="item"` sets the "scoped" variable name that contains the props passed to the slot.  For me, I find using the following syntax makes it more clear:

```html
<template slot="actions" scope="slotProps">
    <b-link :href="slotProps.item.route" :disabled="false" class="btn btn-primary" size="sm" variant="primary" >
      {{ 'thread.read'|trans }}
    </b-link>
</template>
```

The slot's scope variable (`slotProps` in the above example) will have the following properties:

| Property | Type | Description
| -------- | ---- | -----------
| `value` | Any | The value for this key in the record (`null` or `undefined` if a virtual column)
| `item` | Object | The entire record (i.e. `items[index]`) for this row
| `index` | Number | The row number (zero based)

**Note** that `index` will not always be the actual row's index number, as it is computed after pagination and filtering have been applied to the original table data. The `index` value will refer to the displayed row number. This number will align with the indexes from the optional `v-model` bound variable.

**Comment by tmorehouse** [comment]
We also have some new features for `b-table` coming in the next release (currently available in the master branch), which includes enhanced documentation for `b-table`:

https://github.com/bootstrap-vue/bootstrap-vue/tree/master/docs/components/table

**Comment by tristanbes** [comment]
Thanks ! This problem was giving me a really hard time. Good job the enhanced version of documentation :-)

**Comment by tmorehouse** [comment]
Yeah, the use of the scoped variable name `item` always confused me too!
