### ISSUE TITLE
Dropdown - Add option for CSS on hover

### ISSUE THREAD

**Issue by dochoss** [bootstrap-vue/bootstrap-vue#5222]
### Is your feature request related to a problem? Please describe...

Adding a hover class to dropdown items requires investigating the DOM and attempting to add CSS to the rendered items.  In practice, this doesn't seem to work all the time, and it would be nice to have it be a prop that could be passed to enable hover effects.

### Describe the solution you'd like

A simple hoverClass prop that applies effects to the rendered li's would solve the issue, and wouldn't be terribly difficult to implement (I believe).

### Describe alternatives you've considered

I'm no frontend whiz, so my attempts have not given me the results I would like.  I recognize the design decision and appreciate the thought put into it.  However, since the framework has grown, in my opinion, flexibility should be a larger concern.  The caveat could be phrased, "We don't recommend you do this, but if you need to, we allow it."

### Additional context

If there is already a way to accomplish this, I'm certainly open to suggestions.  I've tried applying scoped CSS to the li, dropdown-item li, and several other combinations.  It's possible I'm simply missing something, so I'd be interested to hear if anyone else has gotten it to work through workarounds.

**Comment by tmorehouse** [comment]
Hover effects use the `:hover` psuedo selector, which can't be added via inline style attributes.

You could use the `v-b-hover` directive, which calls a method when the element is hovered, and have that method trigger the addition of a class to the element.

Alternatively, you create custom SCSS/CSS that targets the element:

```css
.dropdown-menu .dropdown-item:not(disabled):not(.disabled):hover {
  font-wight: bold;
  color: purple;
}
```

Note that the `<li>` elements are there for purely semantic markup and have no specific "style", and that the `.dropdown-item` class (and its associated hover and focus styles) do all the magic when it comes to the look of the menu item.
