### ISSUE TITLE
How to prepend an icon to a b-form-input?

### ISSUE THREAD

**Issue by RyanSacks** [bootstrap-vue/bootstrap-vue#5229]
Hi, I'm trying to add an icon to some of my form inputs. I saw in the docs that there is something called prepend-html where you can add custom html, so I'm trying to use that. This is my code:
```
<b-form-group>
                                            <b-form-select
                                                size="sm"
                                                id="country"
                                                v-model="employerProfileData.country"
                                                :options="employerProfileData.optionsTwo"
                                                class="form-control"
                                                prepend-html='<i class="fa fa-pencil"></i>'
                                            >
                                            </b-form-select>
</b-form-group>
```

But it's not working. When I inspect the element it actually just says
```prepend-html='<i class="fa fa-pencil"></i>``` on the element itself, so it's not being converted to html it's just treating it as a string. And in the docs, in the prepend examples there's know js code like state or anything, so I'm not sure how to acheive this. Any idea?

### Versions

- BootstrapVue: ^2.11.0
- Bootstrap: ^4.0.0
- Vue: ^2.5.17

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome

**Comment by tmorehouse** [comment]
`<b-input-group>` is used for prepending and/or appending items to form controls.

See: https://bootstrap-vue.org/docs/components/input-group

**Comment by tmorehouse** [comment]
Here is another link showing the use of BootstrapVue icons with input groups:

https://bootstrap-vue.org/docs/icons#input-groups

**Comment by RyanSacks** [comment]
What I was looking for thank you.

**Comment by mikeerickson** [comment]
@tmorehouse why doesn’t the icon append format not work? I am trying to get a dropdown on left and search icon on right.  All is cool until I add the icon 

```
<div>
  <b-input-group size="sm">
    <template #prepend>
      <b-dropdown size="sm" text="Dropdown" variant="outline-secondary">
        <b-dropdown-item>Action A</b-dropdown-item>
        <b-dropdown-item>Action B</b-dropdown-item>
      </b-dropdown>
    </template>

    <b-form-input></b-form-input>

  <b-input-group>
        <b-icon icon="search"></b-icon>
      </b-input-group-append>
</b-input-group>
</div>
```
