### ISSUE TITLE
Pagination bad UX: n+1 page should always be visible

### ISSUE THREAD

**Issue by tristanbes** [bootstrap-vue/bootstrap-vue#523]
Hello,

Some users navigate through the pagination by clicking on the number of the page instead of using the `>` and `<`. Currently, it feels weird because page number 2 is never shown on the pagination. It force you to position your mouse to `>` and then to go back with your mouse on item `3`

<img width="237" alt="metadata_title_account_list_cv" src="https://user-images.githubusercontent.com/346010/27254668-724a9afc-538d-11e7-8285-a47ae8fcbe71.png">

And as soon as i'm on page 2, the page 3 button appears, which is the right & by default behaviour we should have (even on page 1)

<img width="310" alt="metadata_title_account_list_cv" src="https://user-images.githubusercontent.com/346010/27254671-9bcb586c-538d-11e7-887c-6a0d084be0b7.png">

Can you consider always showing `n+1` page as a button please ? (or provide an option to allow us to do this if you don't want to change your default behaviour).

Thank you :-)

**Comment by tmorehouse** [comment]
Yeah, pagination does have some strangeness in how it renders the buttons.  We're definitely getting ready to work on this issue.  Improvements might be available in release 0.17.0

**Comment by tmorehouse** [comment]
There are already a few enhancements available in the current master, but most do not apply to the issue you bring up.

**Comment by tmorehouse** [comment]
PR #528 should address some of the UX experience.

**Comment by tmorehouse** [comment]
PR #528 now addresses N-1 & N+1 buttons always being present (where applicable)
