### ISSUE TITLE
b-form-datepicker value format

### ISSUE THREAD

**Issue by Dual-Ice** [bootstrap-vue/bootstrap-vue#5232]
Is it possible to pass value for datepicker in this format: '2020-04-09 00:00:00' ?
Example:
https://codepen.io/FeonoR/pen/oNjBwwW

Server sends date in this format and i don't want to create computed properties for correcting date. Now I am using another datepicker (https://github.com/mengxiong10/vue2-datepicker) and it show this date correctly, but I want to reduce project dependencies and use all components of BV.

**Comment by tmorehouse** [comment]
Currently it supports the format supported by native HTML5 date type input (YYYY-MM-dd).

But we might be able to modify the input check regular expression to ignore anything after the first whitespace character.

**Comment by Dual-Ice** [comment]
Thanks for answer, if you are improve this moment it will be great. As for the workaround, I'll think about it.
