### ISSUE TITLE
Country select with search functionality

### ISSUE THREAD

**Issue by digitalcortex** [bootstrap-vue/bootstrap-vue#5235]
### Is your feature request related to a problem? Please describe...

Would be great to have a country dropdown selector with country flags and search functionality. Other open source solutions for that use outdated bootstrap and seem totally out of style.

**Comment by digitalcortex** [comment]
> We are working on a generic dropdown based multi-select component that will allow for custom formatting of the items, optional search field, and external API loading. It will not have built in country flags, but you can use any 3rd party flag set (images, icons, SVG, etc) to show a flag in the custom formatted item listing.

That would be great!

**Comment by m-demydiuk** [comment]
@tmorehouse great news! When do you expect to publish it?

**Comment by tmorehouse** [comment]
Probably in a month-ish

**Comment by guilhermeaiolfi** [comment]
> Probably in a month-ish

was it published? I couldn't find it. If not, can I see the WIP anywhere?
