### ISSUE TITLE
Auto sizing Textarea not allowing 1row height

### ISSUE THREAD

**Issue by Ragnar-Oock** [bootstrap-vue/bootstrap-vue#5236]
When enabling the autosizing feature on a `b-form-textarea` by providing a rows' value of 1 and a max-rows of 2 or higher, the textarea will not shrink to less than 2 rows of height

### Steps to reproduce the bug

1. create a `b-form-textarea` with the following attributes : `rows="1" max-rows="3"`
2. the generated textarea will have a minimum height of 2 rows

### Expected behavior

An autosizing textarea should be able to shrink down to 1row (maybe 0 for some edge cases?)

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: ^4.3.1
- Vue: ^2.6.11

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Firefox v75.0, Chrome v81.0.4044.113

**Comment by tmorehouse** [comment]
Duplicate #2660

**Comment by tmorehouse** [comment]
Many browsers do not allow for the `rows` attribute on `<textarea>` to be any value less than `2`. Some older browsers will crap out on `1`, and many others will just ignore the `1` and internally set it to `2`.

**Comment by Ragnar-Oock** [comment]
thanx for the answer, i did saw that line xD
