### ISSUE TITLE
Duplicate check icons after validation of datepicker

### ISSUE THREAD

**Issue by digitalcortex** [bootstrap-vue/bootstrap-vue#5237]
### Describe the bug

Duplicate check icons after validation of datepicker

### Steps to reproduce the bug

1. Add datepicker
2. Setup validation

### Expected behavior

There should be only 1 validation check icon inside datepicker field.

### Versions

**Libraries:**

- BootstrapVue: 2.12.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Brave
- Version: Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)

### Screenshot

<img width="345" alt="validation" src="https://user-images.githubusercontent.com/62620810/80106256-b1038380-858a-11ea-91a6-24ea0aca4040.png">

**Comment by tmorehouse** [comment]
It sounds like you might not be including BootstrapVue's custom CSS after Bootstrap v4.4 css

**Comment by tmorehouse** [comment]
Actually this does appear to be a bug in the custom SCSS

**Comment by digitalcortex** [comment]
Glad I could help

**Comment by tmorehouse** [comment]
BootstrapVue v2.13.0 has been released

**Comment by jongbonga** [comment]
I updated but still have the duplicate validation issue

**Comment by tmorehouse** [comment]
@jongbonga Make sure you are using the latest BootstrapVue CSS (and that it is imported _after_ Bootstrap v4.4 CSS)

**Comment by jongbonga** [comment]
package.json

`"bootstrap-vue": "2.13.0"`

main.js

```
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-vue/dist/bootstrap-vue.css";
```

Bootstrap v4.4.1

**Comment by tmorehouse** [comment]
@jongbonga you might need to clear your package/yarn lock cache

If using yarn, try `yarn upgrade`

Or remove package.lock or yarn.lock and re run yarn install

**Comment by jongbonga** [comment]
No luck! 
I created a new app, tested it and everything works fine. 
Not sure what's wrong with my setup... deleted .lock, node_modules folder, hit yarn install, and hard reloaded browser but :(

Thanks for your assistance

**Comment by jongbonga** [comment]
I just found my problem, I had a bad dream about it.
My custom css was importing bootstrap.

I'm sorted now.

Thanks
