### ISSUE TITLE
Formatter not working automatically

### ISSUE THREAD

**Issue by ArthurShlain** [bootstrap-vue/bootstrap-vue#5239]
I have readonly field with number separated by spaces every four digits.
The input value is, for example "11112222333344445555".

The `formatter` function of `<b-form-input>` calls only when `blur` event fired.

So i see original value, instead of "1111 2222 3333 4444 5555"

[CodePen](https://codepen.io/ArtZ91/pen/LYpxXeW)

**Comment by tmorehouse** [comment]
Are you using a keyboard with predictive text support?

**Comment by tmorehouse** [comment]
Ah, you are pre-setting the v-model.   The formatter only runs on user input. Preset values are assumed to be already formatted (as they are provided by the system/app and not the user)

**Comment by ArthurShlain** [comment]
Need to use computed values instead, yes?

**Comment by tmorehouse** [comment]
I would either use a computedProp, or a method to massage any initial value provided by the server or back end.
