### ISSUE TITLE
Form Select doesn't work in input-group

### ISSUE THREAD

**Issue by seitbekir** [bootstrap-vue/bootstrap-vue#524]
```html
      <b-input-group left="Category">
        <b-form-select
          v-model="currentCategory"
          :options="currentScope.categories"
          calss="mb-3"
        ></b-form-select>
      </b-input-group>
```

I expected, to this code will work, but it doesn't.

**Comment by tmorehouse** [comment]
Could you provide an example of the generated output you are seeing?  Also which version of bootstrap-vue are you using?

**Comment by tmorehouse** [comment]
It appear that this happens to be due to how tooltips are applied to elements/components, and the wrapper element needed (in this case a `span`) around the component.  It is this wrapper that is affecting the CSS layout that you are experiencing.

**Comment by tmorehouse** [comment]
You could set custom to false, (`;custom="false"`) and then try adding the class `form-control` to the `b-form-select`, and see if that generates the output you are expecting.

**Comment by tmorehouse** [comment]
@seitbekir Is still an issue when you use the new latest release v0.17.0?

**Comment by tmorehouse** [comment]
It appears that `b-form-select` is working within `input-groups` using the latest release:

![image](https://user-images.githubusercontent.com/2781561/27766239-4eb7213c-5ea0-11e7-8786-01397e57d07f.png)
