### ISSUE TITLE
Support click handler on <b-overlay /> shade.

### ISSUE THREAD

**Issue by viglucci** [bootstrap-vue/bootstrap-vue#5243]
### Is your feature request related to a problem? Please describe...

I am looking for a way to be able to trigger a callback when a  `<b-overlay />` is clicked. This is useful when using the overlay to cover the entire screen to have the user focus on a specific piece of content.

### Describe the solution you'd like

I would like to be able to add a click handler to the overlay using `@click="..."`.

```vue
<b-overlay
    @click="closeOverlay"
>
    ...
</b-overlay>
```

### Describe alternatives you've considered

I've considered adding a close button to the content shown in the overlay, however it is a common UX pattern to allow a user to close an overlay by clicking on the shaded portion.

### Additional context

I'm new to Vue so adding such a click handler may already be supported without changes to the library. Please let me know if this is possible, thanks :).

**Comment by tmorehouse** [comment]
You can do the following (this assumes you are wrapping content):

```html
<template>
  <b-overlay :show="showOverlay" @click.native="onOverlayClick">
    <b-card>
      Some content
      <b-button @click="showOverlay = true">
    </b-card>
  </b-overlay>
</template>

<script>
export default {
  data() {
    return {
      showOverlay: false
    }
  },
  methods: {
    onOverlayClick(evt) {
      // Only respond to the click when the overlay is open
      if (this.showOverlay) {
        this.showOverlay = false
      }
    }
  }
}
</script>
```

If obscuring say the entire screen, the template would be something like this

```html
<template>
  <div
    class="position-fixed d-flex align-items-center justify-content-center"
    style="top:0; left: 0; bottom: 0; right: 0"
  >
    <b-card>
      Some content
      <b-button @click="showOverlay = true">
    </b-card>
    <b-overlay :show="showOverlay" no-wrap @click.native="onOverlayClick">
    </b-overlay>
  </div>
</template>
```

**Comment by tmorehouse** [comment]
One side note is that even though the overlay is clickable, it is not accessible as a clickable element to screen reader or keyboard-only users.

So it would be a good idea to also place a button inside the overlay to close it so that users of assistive technologies can close the overlay.

**Comment by viglucci** [comment]
That worked great, thanks! In regards to accessibility I've included a close button as well as leveraged https://github.com/posva/focus-trap-vue to allow for easier keyboard navigation.

End result:

![image](https://user-images.githubusercontent.com/6305490/80163463-dea4f880-859b-11ea-9e38-29299492e340.png)

**Comment by viglucci** [comment]
I'm happy with this implementation, however I'll leave it up to the maintainers/contributors of this project to determine if they want to keep this issue open and support click on the component itself. AKA, feel free to close this issue if you also feel this workaround is sufficient for this use-case.

**Comment by tmorehouse** [comment]
Overlay's were't intended to be modals (originally), and in non-fixed mode the focus constraint wouldn't make sense, but the overlay click event (probably named `overlay-click`) might be something we can add it easily (with some caveats in the documentation about A11Y and constrained focus)
