### ISSUE TITLE
How can I show or hide a div on certain devices or breakpoints?

### ISSUE THREAD

**Issue by RyanSacks** [bootstrap-vue/bootstrap-vue#5244]
Hi, I was just wondering if Bootstrap Vue had any special classes for Showing and Hiding content like inside a div on certain devices or breakpoints. For example I might want something to show 768px breakpoint and up but remove 767 and below. Is this possible with Bootstrap Vue? If not would you know how to do this with Vue js?

- [x] General question about Bootstrap Vue

**Comment by tmorehouse** [comment]
Check out the Bootstrap v4.4 responsive display utility classes:  https://getbootstrap.com/docs/4.4/utilities/display/

**Comment by RyanSacks** [comment]
Will they work with only Bootstrap Vue installed or do I also need to have Bootstrap installed?

**Comment by tmorehouse** [comment]
BootstrapVue uses Bootstrap's SCSS/CSS

**Comment by tmorehouse** [comment]
With BootstrapVue, you need to include Bootstrap's CSS followed by BootstrapVue's custom CSS

**Comment by RyanSacks** [comment]
Oh so just the css, there’s no JQuery involved.

**Comment by tmorehouse** [comment]
No jQuery at all

**Comment by Hiws** [comment]
Here's a quick example for you to get started.

```html
<div class="d-none d-md-block">
  This text will only be visible above 768px
</div>

<div class="d-md-none">
  This text will only be visible under 768px
</div>
```

**Comment by RyanSacks** [comment]
Okay got it.

**Comment by FerchoCarcho** [comment]
d-xxxx Involves using DISPLAY:BLOCK right? and If I want to DISPLAY:FLEX instead how to do it ????

**Comment by Hiws** [comment]
> d-xxxx Involves using DISPLAY:BLOCK right? and If I want to DISPLAY:FLEX instead how to do it ????

By using the utility class for `display: flex`, which is `d-flex` as shown on the Bootstrap docs.
