### ISSUE TITLE
Custom validator check failed on prop alignH

### ISSUE THREAD

**Issue by kamikazechaser** [bootstrap-vue/bootstrap-vue#5246]
### Describe the bug

Custom validator [here](https://github.com/bootstrap-vue/bootstrap-vue/blob/833b028a2d6101d01b7012a7378359db1c801695/src/components/layout/row.js#L63) doesn't seem to take into account props like `center`. Documentation [here](https://bootstrap-vue.org/docs/components/layout#comp-ref-b-row-props) says otherwise.

This results in:

```bash
[Vue warn]: Invalid prop: custom validator check failed for prop "alignH".
```

### Steps to reproduce the bug

```html
<b-row align-h="center" class="pb-5">
```

### Expected behavior

No warn should be given since center is a valid prop.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.1.3
- Vue: 2.#.# (Nuxt 2.0.0)

**Comment by tmorehouse** [comment]
Could you update to a newer version of BootstrapVue? i.e. 2.11.1 (or 2.12.0 is the latest).

Also upgrade to Bootstrap v4.4.1

**Comment by tmorehouse** [comment]
Also note the validator is:

```js
const COMMON_ALIGNMENT = ['start', 'end', 'center']
// ...
props: {
  // ...
  alignH: {
    type: String,
    default: null,
    validator: str => arrayIncludes(COMMON_ALIGNMENT.concat(['between', 'around']), str)
  },
  // ...
}
```

The common alignment values (`start`, `end`,  and `center`) are concatenated with `between`, `around`, so `center` is included in the validation check.

**Comment by kamikazechaser** [comment]
Updating the libraries seems to solve the issue.
