### ISSUE TITLE
Can't apply style directly to Bootstrap Card Header

### ISSUE THREAD

**Issue by Tabrizian** [bootstrap-vue/bootstrap-vue#525]
I can't apply styles directly to the header of the card. Consider the code below:

```html
  <b-card header="Card header text"
            class="mb-2"
            title="Card title"
            sub-title="Card subtitle"
            show-footer
    >
        <small slot="footer" class="text-muted">
            Last updated 3 mins ago
        </small>
    </b-card>
```

One possible solution is using ```variants``` but the problem with it is that it changes the whole color of the card not the header only.

**Comment by tmorehouse** [comment]
The latest `b-card` in master supports a few new features for dealing with headers, which will be available in release v0.17.0 when it come out.

https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/card.vue#L8-L16

There is a `header-class` prop that can be used to apply a class name, or array of class names), and you can specify the element type for the header with `header-tag` (defaults to `div`).

**Comment by Tabrizian** [comment]
Oh, thanks. When do you release this version?

**Comment by tmorehouse** [comment]
We don't have a set date yet, but it will becoming very soon.

**Comment by Tabrizian** [comment]
Thanks :+1:
