### ISSUE TITLE
datepicker and timepicker in button only mode: horizontal padding missing

### ISSUE THREAD

**Issue by shimikano** [bootstrap-vue/bootstrap-vue#5251]
### Describe the bug

b-form-datepicker and b-form-timepicker in 'button only' mode seem to lack horizontal padding. The issue is present in the official documentation (https://bootstrap-vue.org/docs/components/form-datepicker#button-only-mode):

![screenshot_11](https://user-images.githubusercontent.com/3526886/80227254-ac53d380-864d-11ea-9807-7a2c4f4356ec.png)

### Expected behavior

The padding should match the non 'button only' mode.

### Versions

**Libraries:**

- BootstrapVue: 2.12.0
- Bootstrap: 4.4.1
- Vue: 2.6.22

**Comment by tmorehouse** [comment]
Are you including the BootstrapVue custom CSS after Bootstrap v4.4 CSS?

**Comment by tmorehouse** [comment]
You can get around this issue by setting the prop `menu-class` to `'p-2'`
