### ISSUE TITLE
Alphabetical pagination

### ISSUE THREAD

**Issue by digitalcortex** [bootstrap-vue/bootstrap-vue#5253]
### Describe the solution you'd like

Would be great to have an ability to use pagination component with alphabetical ordering.

### Example 

https://codepen.io/Gruber/pen/bEXXWQ

**Comment by tmorehouse** [comment]
You can actually do this using scoped slots:

```html
<template>
  <b-pagination v-model="currentPage" :per-page="1" :total-rows="26" ...>
    <template v-slot:page="{ page }">
      // page is from 1 to number of pages
      {{ alphabet[page - 1] }}
    </template>
  </b-pagination>
</template>

<script>
export default {
  data() {
    return {
      currentPage: 1,
      numPages: 26
    }
  },
  computed: {
    alphabet() {
      return [
        'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
        'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'
      ]
    }
  }
}
</script>
```

Note we have set the per-page to `1` and number of pages to `26` (the number of letters in the alphabet).  Your paginate items would be handled a little different than with typical pages pagination (which would slice an array), in that you would have an arbitrary number of rows, basically filtering your dataset by the first letter matching the `alphabet[currentPage - 1]`

See https://bootstrap-vue.org/docs/components/pagination#button-content
