### ISSUE TITLE
Feature Request - BTable 'row-details' styling controls

### ISSUE THREAD

**Issue by DM2489** [bootstrap-vue/bootstrap-vue#5254]
### Feature Request - BTable 'row-details' styling controls

I'd like to be able to access styling options for the `row-details` slot more easily.

Example use case:
![image](https://user-images.githubusercontent.com/40390596/80250921-9e617b00-866c-11ea-8414-fd283c4b7569.png)

### Proposed Solution

Ideally, either a way to target the class of the `b-table details > td` element via exposed props (like `thead-class`, or access to a row scope item similar to `scope._rowVariant` but for the `row-details` (such as `scope._rowDetailsVariant`).

### Alternatives

I can achieve the desired effect using the following css, but the proposed solution(s) would be much more usable.

```
.b-table-details > td {
    padding: 0;
    border-color: var(--danger);
}
```

**Comment by tmorehouse** [comment]
There is a prop `details-td-class` which will let you apply arbitrary class or classes to the details rows' `<td>` element (there is only one `<td>` element in the details slot, and hte details `<tr>` has no styling applied to it).


Note if using scoped styles, you will need to add the `/deep/` selector in front of your style definition:

```html
<style scoped>
  /deep/ .my-details-class {
    padding: 0;
    border-color: var(--danger);
  }
</style>
```

**Comment by DM2489** [comment]
@tmorehouse Argh, thank you! I've been staring at the component reference for hours but somehow I managed to miss this! That will teach me to CTRL + F for 'row-details'!

**Comment by tmorehouse** [comment]
Hehe, actually CTRL+F 'row-details' probably wouldn't have found it, but CTRL+F 'details' would have...

**Comment by DM2489** [comment]
Indeed, would have. But 'details' appears **a lot** in that section of the docs! I think that tweak to the meta would be really helpful!
