### ISSUE TITLE
i18n v-t directive not works with b-button and some other components

### ISSUE THREAD

**Issue by moredure** [bootstrap-vue/bootstrap-vue#5255]
### vue-i18n v-t directive not works with b-button and some other components

Directive not works with b-button and some other components, because of innerText settings internally 

### Steps to reproduce the bug

1. Create <b-button v-t="blabla" />
2. No text rendered

### Expected behavior

Text should exists

### Versions

Latest stable of vue and bootstrap-vue

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: macOS
- OS: macOS
- Browser: Chrome
- Version: latest

**Comment by tmorehouse** [comment]
In general, one should never use `v-text`, `v-html` and similar directives that overwrite the inner content on a component.  These types of directives are for HTML elements only.   Components control their internal structure, and can update when they react to changes (i.e. hovers, focus, prop changes, clicks, etc) which will cause them to re render their content/structure overriding the `v-text/v-html` style directives

Use `<b-button>{{ $t(...) }}</b-button>` interpolation when using `i18n` in components, or props for provided for text content (i.e. `<b-card :title="$t(...)" ...>`)

From the i18n docs:

> The translated content with `v-t` is inserted into the `textContent` of the **element**.

Note that they state **element** and not **component**

You may find `v-t` works on some *functional components* (components with no `this` Vue instance), which plainly render a simple element with some classes.
