### ISSUE TITLE
B-table row drag and drop

### ISSUE THREAD

**Issue by m-demydiuk** [bootstrap-vue/bootstrap-vue#5259]
Are there any plans to add support for drag and drop to b-table? This might be very helpful for us because we need to manage order of items and we want to use drag and drop for this.
Or maybe you can suggest how to achieve this?

Thanks!

**Comment by tmorehouse** [comment]
There are several 3rd party drag and drop libraries that can be used with `<b-table-simple>` and it's child components.

`<b-table>` as it is now, is way to bloated with features (and consuming close the 1/4 of the total BootstrapVue library size), and adding more to handle every possible feature is not in the roadmap.
