### ISSUE TITLE
Target property types not explained

### ISSUE THREAD

**Issue by h4gen** [bootstrap-vue/bootstrap-vue#5262]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

Specific page of the documentation:

[Tooltips and everything with a target property](https://bootstrap-vue.org/docs/components/tooltip/)

### Additional context or description

The pages of components with target property state `String or HTMLElement or SVGElement or Function or Object` as valid target but there are no examples given besides the option for `String` in the docs. Would be great to see examples how to access a target by `HTMLElement or SVGElement or Function or Object` in Vue.

Thank you.

**Comment by Hiws** [comment]
There's actually an example of using a function (sort of).
The last `<b-tooltip>` in [this](https://bootstrap-vue.org/docs/components/tooltip#b-tooltip-component-usage) snippet, uses both a shorthand function and a ref to return a HTMLElement.

But i agree, that maybe a dedicated section to various ways to target could be beneficial.

For now I've created this codepen with a few examples.
https://codepen.io/Hiws/pen/vYNmvqV

Note that `$refs` can actually return different types.
If it's placed on a `b-btn` it will return a `HTMLElement`, if you place it on a `b-datepicker` it will return an `Object` and if you place it on a `b-icon` it will return a `SVGElement`.

So in the codepen, these actually cover all the different types.

**Comment by h4gen** [comment]
Thank you very much for this reply. Indeed this explanation helped me personally a lot. And thanks for the great examples :)
