### ISSUE TITLE
Official Website offline?

### ISSUE THREAD

**Issue by leo95works** [bootstrap-vue/bootstrap-vue#5269]
Hello, for weeks I have been trying to access the official site of the [project](https://bootstrap-vue.js.org/) ... but it answers me with the following code 503 Unable to connect... is the site down? am i the only one with this problem?

**Comment by Hiws** [comment]
There were some problems a week or so ago when they swapped provider, which lasted about a day.
But since then there hasn't been any issues.

The URL has also changed from https://bootstrap-vue.js.org/ to https://bootstrap-vue.org/

If you still can't access the site you can generate the docs locally by cloning down the git repository.

**Comment by leo95works** [comment]
I get the same answer from both directions ```500 Unable to connect```. In any case, I will try to clone the documentation to use it offline. Thank you.

**Comment by tmorehouse** [comment]
You might need to clear your browser cache (or do a SHIFT+reload)

**Comment by leo95works** [comment]
@tmorehouse  I have not had any positive results with that advice. I do not know if it is a problem of my location, many service providers have blocked requests from my country, I am from Cuba

**Comment by tmorehouse** [comment]
@leo95works can you access this site?: https://vercel.com/edge-network

**Comment by leo95works** [comment]
@tmorehouse no, I receive the same response ```500 Unable to connect```

**Comment by tmorehouse** [comment]
Hmmm interesting.  So it must be blocking happening somewhere in the network... either at the edge cache or at ingress to Cuba

**Comment by leo95works** [comment]
There is no other option then ... I have to use the documentation offline.. Thank you @tmorehouse

**Comment by tmorehouse** [comment]
You can access (slightly) older documenation at https://bootstrap-vue.netlify.app/ perhaps?

**Comment by leo95works** [comment]
To that site if I can access without any problems .. Thank you very much

![image](https://user-images.githubusercontent.com/60673955/80511055-92fea000-8949-11ea-902e-6a6444c0dc3a.png)
