### ISSUE TITLE
Is it possible to get the current breakpoint ? 

### ISSUE THREAD

**Issue by cutenarwhal** [bootstrap-vue/bootstrap-vue#5284]
### Would like to be able to detect the current breakpoint 

I know that the visibility of Bootstrap-vue components on different breakpoints can be controlled with attributes and [utilities](https://getbootstrap.com/docs/4.4/utilities/display/#hiding-elements)

However, I need to change some CSS classes and hide the sidebar when the window changes, according to the current breakpoint. 

Is there any way to programmatically get the current breakpoint from Bootstrap-vue?   

### Desired solution

I'm using the sidebar as the navigation for the site on desktop and mobile. 

Ideally, I just want the sidebar to be open **by default** on the desktop view, and for it to have pushed the content  on the page to the right.   (not overlaid the content)

If the browser is shrunk from desktop to mobile viewport, I then want the sidebar to go off-screen and only appear when a button is pressed.  My current approach (below) requires the need to detect changes to the browser size & to know the current breakpoint. 

### Current approach 

Currently, I have the sidebar open by default on desktop view when the page loads using the v-model:  

```html
<div id="app">
    <b-sidebar v-model="sidebarVisibility" width="260px" shadow no-header>
        <div class="px-4 py-4">
           <!-- navigation --> 
        </div>
    </b-sidebar>

  <b-container fluid>
    <b-row>
        <b-col id="content" class="py-3 mt-4 mr-3">
            
        </b-col>
    </b-row>
  </b-container>
</div>

<script>
  window.app = new Vue({
    el: '#app',
    data: {
        sidebarVisibility: true,
    },
  });
</script>

<style>
/** Shift the content when sidebar showing */
#content {
  margin-left: 285px;
}
</style>
```

(Note that the content area is pushed right using the left-margin in the CSS) 

Now when the browser is shrunk to mobile-view I want the sidebar to go offscreen and only appear when a navigation button is pressed by the user. 

i.e. with a listener like this:

```
<script>
  window.app = new Vue({
    el: '#app',
    data: {
        sidebarVisibility: true,
    },
    created() {
        window.addEventListener("resize", this.resizeHandler);
    },
    methods: {
        resizeHandler(e) {
              if (breakpoint is 'sm' or 'xs' ) { 
                   this.sidebarVisibility = false,
                   // also add a class to '#content' to over-ride the margin-left 
              } 
             else { 
                   this.sidebarVisibility = true,
                   // reinstate the margin-left on #content div
             } 
        }
     }
  });
</script>
```

Thank you very much.

**Comment by tmorehouse** [comment]
Currently BootstrapVue doesn't provide a programatic means to detect the current breakpoint name.

You can use [`matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) to detect when the viewport changes and which media queries are active.

An alternative approach would be to create a `<div>` with the appropriate display utility classes, and use the [`v-b-visible` directive](https://bootstrap-vue.org/docs/directives/visible)

```html
<template>
  <div
    v-b-visible="handleVisible"
    class="position-fixed d-block d-md-none"
    style="z-index: 20000; height: 1px;"
  ></div>
</template>

<script>
export default {
  data() {
    return {
      isXsSm: false
    }
  },
  methods: {
    handleVisible(isVisible) {
      this.isXsSm = isVisible
    }
  }
}
</script>
```

`isXsSm` will be true on `xs` and `sm` screens (as the `<div>` has `d-md-none` class which hides the div on medium and larger screens)
