### ISSUE TITLE
Can't exactly control popover position

### ISSUE THREAD

**Issue by dflock** [bootstrap-vue/bootstrap-vue#5285]
I want to be able to position a popover over a canvas element, at a certain X,Y position over the canvas.

I have a hover event from the canvas library (visjs-network) which gives me the XY co-ordinates in various different ways:

```js
{
  "pointer": {
    "DOM": {
      "x": 376,
      "y": 294
    },
    "canvas": {
      "x": -88.46833933084167,
      "y": 93.71136062054023
    }
  },
  "event": {
    "isTrusted": true
  },
  "node": 3
}
...
event: {
  altKey: false
  bubbles: true
  button: 0
  buttons: 0
  cancelBubble: false
  cancelable: true
  clientX: 696
  clientY: 827
  composed: true
  ctrlKey: false
  currentTarget: null
  defaultPrevented: false
  detail: 0
  eventPhase: 0
  fromElement: null
  isTrusted: true
  layerX: 696
  layerY: 827
  metaKey: false
  movementX: 0
  movementY: 2
  offsetX: 696
  offsetY: 827
  pageX: 696
  pageY: 827
}
```

However, I can't _actually_ use any of these co-ordinates to tell the popover where to put itself. There are no options on b-popover to set x/y/left/top/etc... directly, and there isn't actually a real DOM node to use to trigger it from - it's just an arbitrary position on the canvas.

I've tried playing around with setting the `style` directly on the popup element to alter the `transform` top/left, but it seems to get overwritten and/or doing it at the correct time is hard.

**Comment by Hiws** [comment]
Instead of positioning the tooltip itself, why not position its target instead.
This target could simply be a 1x1 div with no content, that's position absolute.
That way you can move it using `top` and `left` to position it.

Example:
https://codepen.io/Hiws/pen/yLYzMyE

**Comment by dflock** [comment]
That is a really good idea, thanks - I wish I'd thought of that! I'll try it tomorrow and update here.

**Comment by dflock** [comment]
Ok, that  works, thanks!
