### ISSUE TITLE
b-avatar is not presented in circle but as square

### ISSUE THREAD

**Issue by gajoc** [bootstrap-vue/bootstrap-vue#5287]
defined avatar in vue component as

```
<template>
  <div>
    <b-avatar button @click="loadHierarchyNetwork" src="icons/hierarchy-tree.png"></b-avatar>
    <b-avatar button @click="loadPersonalNetwork" src="icons/person-tree.png"></b-avatar>
  </div>
</template>
``` 

gives result in presentation not circle avatar but square avatar and picture is not centered (gets out of scope of square).

both images have size 32x32px.

**Comment by Hiws** [comment]
Make sure you're import both `Bootstrap` and  `Bootstrap-Vue` CSS.

**Comment by gajoc** [comment]
Big thanks, that does the trick. In docs is mentioned to import these CSS but somehow I missed that!
