### ISSUE TITLE
Aspect not working correctly with images + manual fix

### ISSUE THREAD

**Issue by matanshukry** [bootstrap-vue/bootstrap-vue#5288]
### Describe the bug

When using b-aspect with images that don't match the aspect ratio, the images height will become larger and won't match the desired aspect

### Steps to reproduce the bug

1. Create an aspect ratio element with an aspect (e.g. 1.8)
2. Put an img inside the b-aspect. Make sure the image doesn't match the aspect ratio, to see the effect it has.
3. Make sure the `img` has `width: 100%` and `height: 100%` to match the container size
4. See the size (which won't match the desired aspect ratio)

### Expected behavior

The div containing the image (and hence the img as well) to match the aspect ratio

### Versions

**Libraries:**

- BootstrapVue: 2.12.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Windows
- OS: Windows 10
- Browser: Chrome
- Version: 81

### Demo link

https://codesandbox.io/s/bootstrap-vue-sandbox-8zgrw

In the demo there are 2 images blocks:
(1) With the aspect. This one doesn't work.

(2) A manual aspect box which I found how to do online; it's the workaround I'm currently using an I'm working, although I would prefer to use `b-aspect`

**Comment by tmorehouse** [comment]
Instead of using `w-100 h-100` classes (which will cause distortion), use the `img-fluid` class instead, which will make the image width the same as the aspect container (height will be auto).

Note that if the image ends up being taller than the aspect container, it will enlarge the height of the aspect container.

**Comment by matanshukry** [comment]
@tmorehouse The container should have the aspect ratio, so using w-100 h-100 shouldn't cause a distortion in this case.

Anyway using `b-img` with `fluid` instead of `w-100 h-100` doesn't seem to do anything in this case.

Also, I thought `b-aspect` should guarantee an exact aspect with a maximum size (assuming container has a size, which in this case it does).

If that's not the case, I think it should at least be in the documentation about it.
Using an image with an aspect ratio (and a max size) sounds like a common case to me.

**Comment by tmorehouse** [comment]
It is mentioned in the docs, that the content will overflow and show if it the content is larger than the aspect container:  

> This will always be an aspect of "16:9", except when the content is too tall.

But we can add additional clarification in the docs.

The implementation of `<b-aspect>` is very similar to Vuetify's `<v-responsive>` component (allowing content to overflow if the content is too tall for the container)

**Comment by matanshukry** [comment]
I guess I just missed it. If you can add it in the docs sure, I think it would be helpful.
If you want you should also add my solution, or some other solution that does maintain max height.

Thanks.

**Comment by tmorehouse** [comment]
We might be able to add a new prop to b-aspect to force the constraint (and apply different CSS classes)

**Comment by albertpratomo** [comment]
@tmorehouse can you give a tip on how to make b-aspect force the constraint? What CSS should be applied?
