### ISSUE TITLE
Table column max/min width

### ISSUE THREAD

**Issue by CrixuAMG** [bootstrap-vue/bootstrap-vue#529]
I would like to see a max/min width option for the table columns, as this would put more table customisation on the table component instead of throughout the project.

**Comment by tmorehouse** [comment]
See issue #492 for a solution using classes in the field definition object.

**Comment by tmorehouse** [comment]
@CrixuAMG I have added a new quick PR that allows you to add CSS styles (in javascript object format) to the table TH cells on a per field basis.

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
