### ISSUE TITLE
Ability to set a default for no-auto-hide for BToasts

### ISSUE THREAD

**Issue by dflock** [bootstrap-vue/bootstrap-vue#5291]
### Is your feature request related to a problem? Please describe...

I want to switch off auto-hide for all toasts, but I currently have to do this using the `no-auto-hide` prop on each `b-toast` individually, afaik.

### Describe the solution you'd like

I'd like to be able to default auto-hide to off using a setting.

### Describe alternatives you've considered

My current workaround is this:

```js
BToast: {
    // Can't default to no-auto-hide, so...
    // 99999999/1000/60/60 = 27.7777775 hours
    autoHideDelay: 99999999
  }
```

...which works, but it's a bit of a kludge?

**Comment by tmorehouse** [comment]
Currently we we do not allow Boolean props to be defaulted in the global config, as it changes the meaning of the `no-*` props.   If you use any third party components that expect the BootstrapVue component to work as if the `no-*` prop was not set, then it may break functionality of those 3rd party components (i.e. it would require the authors of those components to explicitly set `:no-auto-hide="false"`.

The global config is mainly for defaulting variants, tet strings/labels and delays.

**Comment by dflock** [comment]
OK, thanks!
