### ISSUE TITLE
Customizing primary color has no effect on tooltip

### ISSUE THREAD

**Issue by bobbl** [bootstrap-vue/bootstrap-vue#5293]
When changing the primary color, most components are affected, but not tooltips.

I am changing the primary color to green with:

    <style lang="scss">
      $primary: #008000;
      @import "~bootstrap/scss/bootstrap.scss";
      @import '~bootstrap-vue/dist/bootstrap-vue.css';
    </style>

Now a primary button is green:

    <b-button id="my-button" variant="primary">
      Button with modified primary color
    </b-button>

However, when adding a tooltip with ``variant="primary"`` it will be blue (default primary color), not green:

    <b-tooltip target="my-button" triggers="hover" variant="primary">
      Tooltip with default primary color
    </b-tooltip>

Do I have to change the tooltip color map separately or is this a bug?

I am using BootstrapVue 2.1.0, Bootstrap 4.3.1, Vue 2.6.11.

Thanks in advance!

**Comment by Hiws** [comment]
You code looks to be working as intended in a fresh vue-cli project.

https://i.imgur.com/zp1T1gf.png

My best guess is it's the way you're importing it.

In what file are you placing code?
```html
<style lang="scss">
  $primary: #008000;
  @import "~bootstrap/scss/bootstrap.scss";
  @import '~bootstrap-vue/dist/bootstrap-vue.css';
</style>
```

**Comment by Hiws** [comment]
You're importing `bootstrap-vue` CSS and not SCSS.

So change the following line
```css
@import '~bootstrap-vue/dist/bootstrap-vue.css';
```

to 

```css
@import '~bootstrap-vue/dist/bootstrap-vue.scss';
```

**Comment by bobbl** [comment]
Oh. Sorry for wasting your time. But thanks a lot, I never would have found that mistake without you.
