### ISSUE TITLE
B-table row slot to be able to add custom component as row

### ISSUE THREAD

**Issue by DragosPeta** [bootstrap-vue/bootstrap-vue#5295]
### Is your feature request related to a problem? Please describe...

If it's possible, i would like to use a custom component as a table row. The reason i need this is because it makes code organizing and testing more efficient and provides lesser duplicate code in some views.

### Describe the solution you'd like

I think a row slot that provides row item, index and what other details you consider it's ok.

### Describe alternatives you've considered

The temporary solution was to use a b-table-simple, but i have to implement features like switching icons on header for server side sorting by hand, etc.

### Additional context

Ex:

```
<b-table ....>
  <template v-slot:row="data">
    <custom-component :row="data.item" :index="data.index" ... />
  </template>
</b-table>
```

**Comment by tmorehouse** [comment]
<b-table>` uses `<b-tr>` to generate the `<tr>` elements of table, as an "intelligent" row is needed to properly handle propagating variant information (among other things) to the generated `<b-td>`/`<b-th>` elements.  Replacing the `<b-tr>` component would break several features of `<b-table>`.
