### ISSUE TITLE
Importing bs-collapse in gridsome from other folder gives error in console

### ISSUE THREAD

**Issue by jd-0001** [bootstrap-vue/bootstrap-vue#5296]
### Describe the bug

Hi, I am using bootstrap-vue for my project and for docs I am using gridsome. I want to show some components I made in gridsome docs & one of them uses bs-collapse component. When I import my custom component from outside of gridsome package folder it throws error but when I paste same component in gridsome package folder and toggle collpase it works fine. IDK why :thinking: 

### Steps to reproduce the bug

1. Clone repo: [Visit](https://github.com/jd-0001/issue-gridsome-bs-collpase)
2. Follow steps
3. See error

### Expected behavior

I think it should work no matter from where I import my component

### Versions

**Libraries:**

- BootstrapVue: 2.13.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: PC
- OS: Linux Mint 19.3 Cinnamon
- Browser: Chrome
- Version: 81.0.4044.122 (Official Build) (64-bit)

### Demo link

You can check demo GIF in my repo README

### Additional context

I have asked for the same in gridsome community because I don't know from where I am getting this error.

**Comment by Hiws** [comment]
Did you find the solution to this issue?

**Comment by jd-0001** [comment]
@Hiws nope

**Comment by jd-0001** [comment]
I moved to vuePress now.
