### ISSUE TITLE
A better datatable select support

### ISSUE THREAD

**Issue by rachitpant** [bootstrap-vue/bootstrap-vue#5297]
The data table feature provided in bootstrap is half baked.

### Describe the solution you'd like

The selected rows should stay selected even after you paginate , sort , or filter.

### Describe alternatives you've considered

A full-fledged data table ( with select and action ) is one of the most common use cases. I can bet every developer needs it, and hence most UI libraries including Vuetify have a good working data table. The datatable in Vue is good, However the select functionality is so bad, it unusable.

When rows are selected, the selection is not retained when you filter, or sort of paginate. This is also acknowledged in the documentation. Even a 10 year old Jquery Datatable does that , Vuetify and every other data table allow that. Check this link to see what I mean.( Ctrl click to select multiple) 
https://jsfiddle.net/zv69avz5/

Plus there should be an option to specify how you want to select rows , Right now clicking on a row selects it. What if the developer wants selection to happen only on clicking a checkbox on the right. A row click triggers something else, eg. open a modal to edit that row, etc. There should be a mode property to specify the selection mode.

If 5000 developers who use bootstrap-vue, need a working datatable and they all require 1 hour to implement these features , imagine the developer hours wasted.

### Additional context

If you don't mind having jquery dependency , you can wrap the datatable in the jsfiddle link with vue.

**Comment by tmorehouse** [comment]
As b-table supports server side pagination, and provider functions which can return arbitrary data (beyond control of b-table), it is impossible to be able to maintain state when pagination or sorting occurs as the data returned maybe not even be from the same back end data sources.

There are several Bootstrap compatible data tables (some Vue based) which provide different features compared to b-table. (i.e. fully in-place editable cells).

Currently b-table consumes over 1/4 of BootstrapVue's code base.

**Comment by Hiws** [comment]
While having more features is always nice, there's also the issue of bloat.

I believe right now that `b-table` is about 1/4 of the codebase, because of all the edge-cases that was implemented.
The select functionality you're looking is possible to implement, with examples how to do this out there. 

You can see one of them here:
https://codepen.io/Hiws/pen/xxxqGVJ

**Comment by rachitpant** [comment]
The point I am trying to make is that this should be the default behavior most users would expect and not a use-case scenario. ( If you select a row , and go to next page , to select more , wouldn't you be surprised if the elements in current page have lost selection.  ).

Plus , it would take anyone atleast a few hours to come up with this example ( and that would require digging into the source code - simply going through documentation wouldn't help arrive at the solution linked above. ) .

**Comment by rachitpant** [comment]
> As b-table supports server side pagination, and provider functions which can return arbitrary data (beyond control of b-table), **it is impossible to be able to maintain state** when pagination, filtering, or sorting occurs as the data returned maybe not even be from the same back end data sources.
> 
> There are several Bootstrap compatible data tables (some Vue based) which provide different features compared to b-table. (i.e. fully in-place editable cells).
> 
> Currently b-table consumes over 1/4 of BootstrapVue's code base.

Its alright if B-table doesn't support all the features , but the features that are purported to be supported should be done correctly. I do not see why it would be impossible to maintain state if you are using provider function to fetch the list for next page. You can generate a primary key , or use user-defined primary key to keep track of rows that has been previously selected. There could be numerous ways. Its anything but **IMPOSSIBLE**. The fact this is using 1/4th of the code base should be enough reason to look into the codebase and possibly refactor it.

**Comment by rachitpant** [comment]
I also want to point out that in the example linked above, the developer is adding a new property to the data-row , and then changing the css class. The `selectRow(index)` is not being called , so `isRowSelected(index)` would also fail. The developer has completely bypassed the select feature. To be honest , the solution in the above example is so much better than the over-engineered but broken select feature provided. The above solution also ensures that  parent component can simply look at data-item and determine if its selected.

The solution is smart , simple and most importantly it works. IMHO the select feature can simply be removed from documentation ( and code) and can be replaced with a working example like above.

**Comment by tmorehouse** [comment]
> Its alright if B-table doesn't support all the features , but the features that are purported to be supported should be done correctly. I do not see why it would be impossible to maintain state if you are using provider function to fetch the list for next page. You can generate a primary key , or use user-defined primary key to keep track of rows that has been previously selected.

Now that would need additional logic to determine if there is a primary key... (one cant use the serialized row data as a key as the data could be edited by the user or changed in the background). We cant use the row index, as that could be changed (i.e. row inserted in the data).  The backend API could even return a completely different dataset....  This would need a pile of additional logic to handle all the edge cases to work correctly (if even possible without breaking other features), and if those edge cases aren't all handled we would end up getting more comments raised saying "is half baked" because it doesn't do exactly what someone wants.

We have stated in the the table docs:

> **Row select notes:**
> - **Sorting**, **filtering**, or **paginating** the table will **clear the active selection**.

So b-table is working as documented.

> There could be numerous ways. Its anything but IMPOSSIBLE. The fact this is using 1/4th of the code base should be enough reason to look into the codebase and possibly refactor it , or atleast the row selection part.

It is using 1/4 of the code base because of all the features that have been added to it over the years, not to mention all the additional markup required for making these features ARIA accessible.

I spent the last year cleaning up and refactoring b-table's code, to add in all the accessibility features that were needed to make it usable by screen reader and keyboard only users, and to make it more modular.  I'm quite intimate with the inner workings of b-table, and I can say without a doubt that there is currently no way to maintain state of selected rows and handle all possible situations, particularly when server side pagination, sorting and filtering a used.

**Comment by rachitpant** [comment]
> > Its alright if B-table doesn't support all the features , but the features that are purported to be supported should be done correctly. I do not see why it would be impossible to maintain state if you are using provider function to fetch the list for next page. You can generate a primary key , or use user-defined primary key to keep track of rows that has been previously selected.
> 
> Now that would need additional logic to determine if there is a primary key... (one cant use the serialized row data as a key as the data could be edited by the user or changed in the background). We cant use the row index, as that could be changed (i.e. row inserted in the data). The backend API could even return a completely different dataset.... This would need a pile of additional logic to handle all the edge cases to work correctly (if even possible without breaking other features), and if those edge cases aren't all handled we would end up getting more comments raised saying "is half baked" because it doesn't do exactly what someone wants.
> 
> We have stated in the the table docs:
> 
> > **Row select notes:**
> > 
> > * **Sorting**, **filtering**, or **paginating** the table will **clear the active selection**.
> 
> So b-table is working as documented.
> 
> > There could be numerous ways. Its anything but IMPOSSIBLE. The fact this is using 1/4th of the code base should be enough reason to look into the codebase and possibly refactor it , or at least the row selection part.
> 
> It is using 1/4 of the code base because of all the features that have been added to it over the years, not to mention all the additional markup required for making these features ARIA accessible.
> 
> We spent the last year cleaning up and refactoring b-table's code, to add in all the accessibility features that were needed to make it usable by screen reader and keyboard only users, and to make it more modular. I'm quite intimate with the inner workings of b-table, and I can say without a doubt that there is currently no way to maintain state of selected rows and handle all possible situations/combinations, particularly when server side pagination, sorting and filtering a used. Which is why we have the note above in the selectable rows section of the docs.

I would still say it would be possible. Lets say user edits the row , as a result the serialized key changes. He would notice right away that the selection has changed. The chances of a backend API changing data, while the user is paginating is really small. ( This wouldn't happen unless someone else has changed the data , and in that case  its actually a good thing that the selected row got unselected before user performed an action on the selected row.).

All these scenarios you mentioned would apply to any framework and I do not think any framework handles those edge-cases. Its more important to meet the users-expectation than to provide a by the book perfect product. And I am sure , any one would agree users are used to selecting rows between multiple pages in any data table, or filtering and then selecting, irrespective of the framework they use. I haven't looked at the code , but from the documentation the issue seems to be that selection is being managed by index , rather than an actual row.

**Comment by tmorehouse** [comment]
`<b-table>` does not know the source of data.  And having edge cases where there is selected row data that no longer exists will cause larger issues (i.e. possibility of adding data that was deleted and should not be added back, etc, depending on what users are doing with the selected row data).

Think of multiple users with read-write access to the back end data.

Without a guaranteed primary key for the row data, it is extremely difficult to maintain state over server-side pagination, sorting, or filtering. We cannot serialize the row data or hash it) to generate a unique key for the row if one is not provided (especially if the data changes server side before the next back end call). Adding in special cases to handle this would bloat the code to the extreme and be prone to more bugs and `what-if` scenarios.

Closing as a wont-fix/wont-implement.
