### ISSUE TITLE
How to call BToast from outside Vue

### ISSUE THREAD

**Issue by leo95works** [bootstrap-vue/bootstrap-vue#5299]
Hi, I want to use the ```BToast``` component outside of Vue.js, is there any way I can call it? For example, I want to launch a ```toast``` whenever a request I make with ```axios``` results in an error. So I define my interceptors:

```
const service = axios.create({
  baseURL: '/api',
  timeout: 10000,
});

service.interceptors.response.use(
  response => {
    return response.data;
  },
  error => {
    // How can I call a Toast from here? <----
    return Promise.reject(error);
  }
);
````

Thank you very much in advance

**Comment by tmorehouse** [comment]
`$bvToast` needs a Vue instance `this` or `this.$root`.  You can create an isolated Vue instance, and use that, but note that the events toast emits will be be accessible from your app.

```js
const vm = new Vue({})

service.interceptors.response.use(
  response => {
    return response.data;
  },
  error => {
    vm.$bvToast.toast('Something went wrong');
    return Promise.reject(error);
  }
)
```

**Comment by leo95works** [comment]
Hello @tmorehouse , thank you very much for your response, but your solution returns the following message:

```
[BootstrapVue warn]: BToast - "$bvToast" must be accessed from a Vue instance "this" context.
```

I show you the complete file with which I am catching ```axios``` errors.


```
import Vue from 'vue';
import axios from 'axios';

const vm = new Vue({});

const service = axios.create({
  baseURL: /api,
  timeout: 10000,
});

service.interceptors.request.use(
  config => {
    return config;
  },
  error => {
    return Promise.reject(error);
  }
);

service.interceptors.response.use(
  response => {
    return response.data;
  },
  error => {
    vm.$bvToast.toast('Something went wrong');

    return Promise.reject(error);
  }
);

export default service;
```

**Comment by gmw-web** [comment]
I have a somewhat similar setup and do the following:

In your main file, export your app instance:
```
import Vue from "vue";
import { BootstrapVue } from "bootstrap-vue";

[...]
Vue.use(BootstrapVue);

export const app = new Vue({
  store,
  router,
  i18n,
  render: h => h(App)
}).$mount("#app");
```

And in my Axios setup file, I have the following:
```
import axios from "axios";
import { app } from "@/main";

const config: AxiosRequestConfig = {
  baseURL: "/api/v1/"
};

const api = axios.create(config);

// response interceptor
api.interceptors.response.use(
  function(response) {
    // Successful response, return data
    return response;
  },
  function(error) {
    app.$bvToast.toast(`An error occurred. API unreachable.`, {
      title: `Server unreachable`,
      variant: "danger"
    });

    return Promise.reject(error);
  }
);

[...]
```

**Comment by sertunc** [comment]
> I have a somewhat similar setup and do the following:
> 
> In your main file, export your app instance:
> 
> ```
> import Vue from "vue";
> import { BootstrapVue } from "bootstrap-vue";
> 
> [...]
> Vue.use(BootstrapVue);
> 
> export const app = new Vue({
>   store,
>   router,
>   i18n,
>   render: h => h(App)
> }).$mount("#app");
> ```
> 
> And in my Axios setup file, I have the following:
> 
> ```
> import axios from "axios";
> import { app } from "@/main";
> 
> const config: AxiosRequestConfig = {
>   baseURL: "/api/v1/"
> };
> 
> const api = axios.create(config);
> 
> // response interceptor
> api.interceptors.response.use(
>   function(response) {
>     // Successful response, return data
>     return response;
>   },
>   function(error) {
>     app.$bvToast.toast(`An error occurred. API unreachable.`, {
>       title: `Server unreachable`,
>       variant: "danger"
>     });
> 
>     return Promise.reject(error);
>   }
> );
> 
> [...]
> ```

thanks bro, you save my life
