### ISSUE TITLE
Release Schedule?

### ISSUE THREAD

**Issue by nijikokun** [bootstrap-vue/bootstrap-vue#530]
I noticed that the table has had significant updates, and the current version has bugs that are fixed in master but not published.

One noticable issue is that in `0.16.1` is that the `colspan` for empty text is applied to `tr` causing the row to only spread across a single column.

In master it is applied to a `td` fixing the issue.

**Comment by tmorehouse** [comment]
Weare hoping to have the release out very soon.  The repository owner has been tied up with another project major release.

I think we have just two more PRs to apply, and then we should be able to release the next version.

**Comment by nijikokun** [comment]
Alright, I may have jumped the gun on opening an issue.

I've found: https://github.com/bootstrap-vue/bootstrap-vue/milestone/1

However, that's a large task list, smaller releases could really benefit it seems, not sure about how you are approaching patch releases (miniature milestones) though.

**Comment by tmorehouse** [comment]
A lot of the tasks in the milestone are open issues that have been addressed in the latest master. We will close the 'coming soon' issues once the new version is released.  We just didn't want to close the issues as some people might think they are now available in the current release.

**Comment by fourpixels** [comment]
I just opened (and closed) another issue about that. It's been over a month and there are tons of things I could use.

You should think of some way that the owner doesn't block the pipeline of releases, as this is slowing everyone!

**Comment by alexsasharegan** [comment]
@fourpixels, with so many updates in this release, we just wanted to make sure we dot all the i's and cross all the t's! Things should move in smaller chunks after this. The owner has been busy, and the rest of the team has been catching up figuring out all the awesome things he does 😄

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0).

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
