### ISSUE TITLE
Add "right" class for "close" class (button close)

### ISSUE THREAD

**Issue by matanshukry** [bootstrap-vue/bootstrap-vue#5301]
### Is your feature request related to a problem? Please describe...

I'm implementing RTL in my app. 
I know RTL isn't supported, but many options in bootstrap vue exist with right/left aligned, so I can simply set the correct property

### Describe the solution you'd like

For the css:
```
.close.right {
  float: left;
}
```

Personally that's all I need (and I'm doing it manually on me), but a property to `<b-button-close>` is probably a good idea too.

### Describe alternatives you've considered

Creating the .css in my own app - which works, but should still exist in BootstrapVue

**Comment by Hiws** [comment]
You could just use the Bootstrap utility class which does the same. 
https://getbootstrap.com/docs/4.4/utilities/float/

```html
<b-button-close class="float-left">
</b-button-close>
```

**Comment by matanshukry** [comment]
@Hiws yeah it's the same workaround just with bootstrap class rather than my own.

I still think it should be provided as part of the close button it self

**Comment by Hiws** [comment]
I dont' really see much reason to add a specific prop to `b-button-close` in this case. 
but I'll leave that decision up to the maintainers.
