### ISSUE TITLE
B-form-checkbox-group required attribute makes all boxes required

### ISSUE THREAD

**Issue by janswist** [bootstrap-vue/bootstrap-vue#5303]
### Describe the bug

B-form-checkbox-group required makes all boxes required.

### Steps to reproduce the bug

Put `required` attribute on `b-form-checkbox-group` in a `form` tag. Unless you select all boxes you can't submit form because of validation error.

### Expected behavior

Select one of the options and be able to submit form.

### Versions
**Libraries:**

- BootstrapVue: 2.13.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS
- Browser: Chrome
- Version: 80.0

**Comment by Hiws** [comment]
That's how `<input type="checkbox">` work natively. The `required` props

**Comment by Hiws** [comment]
That's how `<input type="checkbox">` works natively.
The `required` prop adds the `required` attribute to all the generated checkboxes.

From my research there's no way to do this with pure HTML, and needs custom javascript.

The easiest way to workaround this, would be to check if the `b-form-checkbox-group` v-model is above the length of 0 on submit.

**Comment by janswist** [comment]
Yes, seems like your solution is the only applicable here. Yet, I'm surprised that I can't require just any of the boxes checked - seemed basic to me. Thanks.

**Comment by Hiws** [comment]
Yeah, i surprised too.
But i guess it makes sense since they aren't actually a group HTML wise, unlike radio buttons which you *can* group together in HTML.

**Comment by tmorehouse** [comment]
Note checkboxes that are in a group (i.e. have the same `name` attribute), are treated by the browser as a single compound input.  It is similar to `required` on a select in multiple mode.

To make individual checkboxes required, you need to make each checkbox it's own "input" by not using inside a checkbox group

**Comment by janswist** [comment]
> Note checkboxes that are in a group (i.e. have the same `name` attribute), are treated by the browser as a single compound input. It is similar to `required` on a select in multiple mode.
> 

Correct. My question though is why I have to select them all to have it validated? If I only select one checkbox out of the whole group I get validation error.

Look at the example below. I just want user to select any answer, but when I do select one then I'm asked to select next one:
![image](https://user-images.githubusercontent.com/5583954/81078194-30c81100-8eee-11ea-86f9-7b4189848379.png)

and then when I select the second one then I'm required to select the third one:
![image](https://user-images.githubusercontent.com/5583954/81078340-679e2700-8eee-11ea-959f-365f9bcde54c.png)

It's only validated when ALL checkboxes are checked. That doesn't make sense to me in that fashion.

**Comment by tmorehouse** [comment]
In that type of situation, you wouldn't use required, and instead use a custom validation to check that at least  boxes are checked.

The `required` attribute would be used in the situation where someone has to click all checkboxes to proceed (i.e. "I have read the terms and conditions" + "I agree to the privacy policy" + "I agree to cookies")

**Comment by Hiws** [comment]
You could potentially do something like this, this should remove the required attribute from the checkboxes once one option have been selected.

```html
<b-checkbox-group v-model="selected" :required="selected.length === 0">
</b-checkbox-group>
```

**Comment by janswist** [comment]
> In that type of situation, you wouldn't use required, and instead use a custom validation to check that at least boxes are checked.
> 
> The `required` attribute would be used in the situation where someone has to click all checkboxes to proceed (i.e. "I have read the terms and conditions" + "I agree to the privacy policy" + "I agree to cookies")

Got it. Well, so there you have a potentially new feature to think about - I think many users would appreciate html-based any-checkbox validation. Or even something like `:required="numberOfRequiredChecks"` (basically the same as @Hiws solution). Anyway, thanks for fast reply!
