### ISSUE TITLE
Allow scale to be applied horizontally and vertically on icons

### ISSUE THREAD

**Issue by Wolfwalker96** [bootstrap-vue/bootstrap-vue#5309]
### Is your feature request related to a problem? Please describe...

Icons are not scalable horizontally and vertically with different values.

### Describe the solution you'd like

Allow scale to be applied horizontally and vertically on icons when used with b-iconstack.

For example : 
```vue
<b-iconstack>
    <b-icon-circle stacked></b-icon-circle>
    <b-icon-circle stacked scale-h="0.5"></b-icon-circle>
    <b-icon-dash scale="1.8"></b-icon-dash>
    <b-icon-dash scale="1.8" rotate="90"></b-icon-dash>
</b-iconstack>
```

Excepted result :
![image](https://user-images.githubusercontent.com/23233407/81159885-c19ffa80-8f89-11ea-8724-4dd9530f7f47.png)

**Comment by tmorehouse** [comment]
So basically you are looking to be able to distort icon aspect ration from `1;1` to an arbitrary value? (i..e wider than height, or taller than width?

**Comment by Wolfwalker96** [comment]
Yes, that's what I'm looking for. It will be useful to creating some icons that are missing in the icons library (e.g. a globe).

**Comment by tmorehouse** [comment]
Perhaps an aspect ration prop (where 1 whould be square, and 0.5 would be  1/5 the  width compared to height).

Currently the SVGs have an inherent do not distort setting (as that is defined by BootstrapIcons source), so it might take a bit of additional custom css/scss (or more) to allow for aspect distortions (height would have to remain always consistent relative to 1em though)
