### ISSUE TITLE
Set a template as the default template for all my toasts

### ISSUE THREAD

**Issue by leo95works** [bootstrap-vue/bootstrap-vue#5312]
How can I define a template as default for all calls to the ```toast``` component? I would like to create a file with extension ```vue```, where I can define the structure of what my toast would look like. After this, I would like to define that structure as the default structure of all the toast I call. I wonder if there is any mechanism to achieve this? .. I have read the documentation and cannot find anything like it. Thank you very much in advance.

**Comment by Hiws** [comment]
I don't believe you can do this by default with the on-demand toasts.

However, you could create your own on-demand toasts, which would use the structure of your own `b-toast`.
You could store an array of toast messages in your vuex store.
This would allow you to push toasts into this array from anywhere in your app.

You could create your own store actions to handle pushing toasts into this array.

Then inside your custom toast component, you put a `v-for` on your `b-toast`, which would loop through the store array, and display toasts as they're added.
Then add a method to remove the toasts again once they're hidden using the `@hidden` event. 

Here's an example (without the store part):
https://codepen.io/Hiws/pen/YzyeREa
