### ISSUE TITLE
B-table to have hidden columns

### ISSUE THREAD

**Issue by nazmulislam** [bootstrap-vue/bootstrap-vue#5315]
### Is your feature request related to a problem? 

For the table component, it would be great to have the following features
Ability to make any column, hidden but searchable

### Describe the solution you'd like

For columns which are hidden a drop menu, which on click should display the hidden columns with a checkbox to make them visible on demand and the state to be saved on localstorage, so when user reloads the page the state is maintained.

We should be able to define the columns in the fields property eg.
{visible:false,searchable:true}

### Describe alternatives you've considered

This feature is available in Jquery Data Tables

**Comment by Hiws** [comment]
You can create this feature yourself fairly easily.
This also gives you full control over how it's displayed and saved.

All fields in an item object (the item that is passed to the table), is searchable by default. Even if that field is not being shown, so you don't need anything extra to get this working.

Example:
https://codepen.io/Hiws/pen/LYpQgjV

**Comment by nazmulislam** [comment]
Hiws,

Thank you very much, the feature does indeed exist.
Perhaps, it should be added in the documentation hidden columns, i was not able to find it there.

**Comment by tmorehouse** [comment]
We will probably be adding a new `hidden` property to the fields definition, which if true, hides the column.

In the documentation it is implied that only the fields listed in the `fields` array are shown.

**Comment by anishkhotgithub** [comment]
Hello everyone, I have found a workaround so we won't have to wait for B-Bootstrap's table column hidden functionality.
Use dynamic array fields to hide the column this.field by simply pushing and popping the array field through conditional.
Guys, this is functional.

![solution 1 ](https://github.com/bootstrap-vue/bootstrap-vue/assets/82097179/09e22f0d-25cb-4b09-9cd6-5be94ed393da)
![solution 2](https://github.com/bootstrap-vue/bootstrap-vue/assets/82097179/ecdf4b42-2e4d-4ec4-b9a1-ccfa27d2083d)
