### ISSUE TITLE
Pivot tables?

### ISSUE THREAD

**Issue by whillas** [bootstrap-vue/bootstrap-vue#5317]
More of a feature request. I have some data like this:
```json
{
  "results": {
    "test1": {
      "correct": 0.007, 
      "errors": 0.081, 
      "missing": 0.912
    }, 
    "test2": {
      "correct": 0.008, 
      "errors": 0.098, 
      "missing": 0.894
    }
  }
}
```
Would be handy to have column headings as `test1` and `test2` and row headings `correct`, `errors`, `missing`.

**Comment by Hiws** [comment]
I'm just taking a guess here, but is this what you wanted?
https://codepen.io/Hiws/pen/XWmZxQW

**Comment by whillas** [comment]
Yes!
