### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by giaca95** [bootstrap-vue/bootstrap-vue#5319]
Sidebar component

On componente sidebar would be very useful to have the prop "is-nav" like in collapse component
to let use sidebar like collapse of navbar

**Comment by tmorehouse** [comment]
The `is-nav` on b-collapse is used to trigger the close dropdown menus, and to force dropdowns to show in block format (inline) when opened on small screens.  The sidebar component doesn't use the same mechanism as b-collapse, and the `is-nav` wouldn't make much sense in this situation... Unless you can give a few more details on what you expect it to react.
