### ISSUE TITLE
Question: Recommendation to focus first invalid field in a form?

### ISSUE THREAD

**Issue by scottadamsmith** [bootstrap-vue/bootstrap-vue#5320]
I would like to implement a mechanism for us to always set focus to the first invalid field in a form when someone presses submit on a form with invalid fields. So far, I have been trying to work off the aria-invalid attribute that gets applied to the form-group and trying to look at the children from there. I originally thought I could just target the class "form-control", but quickly realized this doesn't work for other form field types like select, radio, datepicker, etc. 

Do you have a recommendation beyond just figuring out the appropriate selector for each possible element and including them all? Alternatively, I could just bring the "aria-invalid" item into viewport, but we prefer the behavior of actually getting the user into the field to begin correcting mistakes.

**Comment by tmorehouse** [comment]
You idea of doing a search for the element with aria-invalid="true" would work best

```js
const invalid = this.$refs.theForm.querySelector('[aria-invalid="true"]')
if (invalid) {
  invalid.focus()
}
```

Just make sure (if not using b-form-group and it's built in invalid-feedback), that you have `aria-describedby="input-id"` on the invalid input pointing to the invalid-feedback, so that screen reader users who have focus moved on them will know what is incorrect about the input.

**Comment by scottadamsmith** [comment]
I think targeting aria-invalid as you described is a start, but that would only focus the form-group div around the field, which likely isn't a focusable element. The intent is to target the actual "input" (select, textarea, radio, etc.) within the form-group.

**Comment by tmorehouse** [comment]
In the case of radio's, focusing a radio will also select it (if not already selected on some browsers), so that may not work as expected (focusing the outer wrapper of the radio group is better in this case)

To get down to the form-control level:
```js
const invalid = this.$refs.theForm.querySelector(
  'input[aria-invalid="true"], textarea[aria-invalid="true"], select[aria-invalid="true"]'
)
if (invalid) {
  invalid.focus()
}
```

**Comment by scottadamsmith** [comment]
I'm under the impression the "aria-invalid" attribute is applied to the div.form-group, but not to the form control itself. For this approach to work, I think it would need to be:

```
const invalid = this.$refs.theForm.querySelector(
  '[aria-invalid="true"] input, [aria-invalid="true"] textarea, [aria-invalid="true"] select'
)
if (invalid) {
  invalid.focus()
}
```
We might end up down this path, but it doesn't account for the more custom controls. For example, the datepicker, where I think you'd want to focus the button. We'd have to add an additional selector that is built for each custom control that we would want to support. This works, we were just trying to see if there was a cross-cutting approach that wouldn't require revisiting this each time a new custom control or element was added to the library. Perhaps there isn't a way though.

**Comment by tmorehouse** [comment]
If you new the ID(s) for the form control(s), the `id="ID"` attribute will always be placed on the focusable control(s).
