### ISSUE TITLE
[Feature Request] b-navbar-toggle - event on toggle

### ISSUE THREAD

**Issue by matanshukry** [bootstrap-vue/bootstrap-vue#5323]
### Is your feature request related to a problem? Please describe...

I needed to put `min-height` property on my navbar, but for some reason when the navbar is open (on small devices, where the nav bar is collapsed at all), min-height is actually limiting the height.

I wanted to then set `min-height` only if the navbar is open

### Describe the solution you'd like

To have an event with the flag when the menu is toggled

### Describe alternatives you've considered

I tried to use a local boolean value and flip it on `click` event.
However, if I click on one of the items in the menu, it will also close, while the event won't trigger.

**Comment by tmorehouse** [comment]
You could add a click handler to the nav-toggle

**Comment by matanshukry** [comment]
@tmorehouse I mentioned that in the alternatives I've considered ? Or are you talking about something else?

**Comment by tmorehouse** [comment]
Ah yeah...... Hmmm

navbar doesn't maintain state all the time since the collapse is handled via CSS (i.e. if you resize the window).

Perhaps the portion that remains in the navbar when collapsed should have the min-height (or height) set on it (i.e. maybe navbar-brand, or navbar-toggle)

**Comment by matanshukry** [comment]
@tmorehouse I'm a bit confused about what you're saying.

(1) I waas talking about navbar-toggle the entire team. Looking at the code, it does maintain state, a property called `toggle-state` : https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/navbar/navbar-toggle.js#L36

(2) as you can see, the field changes based on an event from some event bus (I didn't dig too deep). I'm just looking to get that exact value

**Comment by tmorehouse** [comment]
Could you provide a screen shot mock up of what you are trying to acheive?

**Comment by Hiws** [comment]
You could bind a boolean property to the `b-collapse` inside the navbar,
This property will be true when the navbar is open on small devices, and false otherwise.

**Comment by tmorehouse** [comment]
Although that is not always the case as CSS can override that value in some circumstances.

**Comment by matanshukry** [comment]
@tmorehouse I can't seem to replicate it, it seems to be a case on my site only (I had to make a lot of changes, for RTL for example).

But the idea is I was trying to set the navbar to a fixed height using `height` property.
I then realized I need to use `min-height`, since when it's open the height will be bigger.
However:
- "Regular" (closed) height is 80px
- Open height is around 300px
- If I set the navbar `min-height: 80px`, it's fine when close. But when opened, the height is set to `163px`.

There is something on my side that I can't fully explain yet - but is supporting the state from b-toggle really such a bad idea?

I'm assuming it's like what @Hiws mentioned, only it's also relevant for the "special cricumstances" you're talking about

**Comment by matanshukry** [comment]
@Hiws Can you show a quick example on how to do that btw? Might be better than what I have now

**Comment by tmorehouse** [comment]
Perhaps something like:

```html
<template>
  <b-navbar :style="computedStyle">
    <b-navbar-toggle target="nav-collapse">
    <b-collapse id="nav-collapse" v-modal="isCollapsed" is-nav>
       <!-- stuff here -->
    </b-collapse>
  </b-navbar>
</template>

<script>
export default {
  data() {
    return {
      isCollapsed: false
    }
  },
  computed: {
    computedStyle: {
      if (this.isCollapsed} {
        // No min-height applied
        return {}
      } else {
        return {
           minHeight: '300px'
        }
      }
    }
  }
}
</script>
```

**Comment by matanshukry** [comment]
Oh just using v-model cool, thanks.

@tmorehouse can you explain some of the circumstances you were talking about regarding css overrides?

**Comment by tmorehouse** [comment]
If using a desktop browser, and have a narrow browser window, and then you resize the browser so that the window is above the collapse threshold, it is possible (for a brief period of time) that the state of the collapse will be out of sync with the visual state (until the next check on the DOM visibility of the collapse).
