### ISSUE TITLE
b-form-file not validates extension when dropping file

### ISSUE THREAD

**Issue by ddzobov** [bootstrap-vue/bootstrap-vue#5329]
### Describe the bug

When «required» is set and i'm dropping file into field it shows me error

### Steps to reproduce the bug

1. Set «accept=".zip"» to b-form-file
2. Drop .rar file into dropzone
3. Submit form
4. Form submitted

### Expected behavior

Form shows me error about incorrect file type

### Versions

**Libraries:**

- BootstrapVue: 2.13.0

**Environment:**

- Device: Mac
- OS: macOS 10.15.4
- Browser: Safari
- Version: 13.1

**Comment by tmorehouse** [comment]
See the answer in #5328, as this is similar in that the dropzone does not update the array of files on the native `<input type="file">` and therefore cannot use the native browser file input `accept` mechanism.
