### ISSUE TITLE
Icons show before rendered in dropdown nav, v-cloak not working as expected

### ISSUE THREAD

**Issue by Grandizer** [bootstrap-vue/bootstrap-vue#5330]
I am using the `b-navbar` with `b-dropdown` items within it. in my header/menu area.  I am also using fontawesome for the icons.  The backend is rendered by Microsoft .Net Core/Razor Pages.

```
<body>
  <header class="header fixed-top" id="headerApp">
    <div class="container">
      <b-navbar toggleable="sm">
        <b-navbar-brand class="pt-0 pb-1">
          <img src="~/images/AvantiaLogo40x40.png" height="40" alt="Avantia Kalyke" />
          <span class="header-title">Avantia Kalyke</span>
        </b-navbar-brand>
        <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>
        <b-collapse id="nav-collapse" is-nav>
          <b-navbar-nav style="margin-top: -0.6rem;">
            <b-nav-item-dropdown text="User" class="pr-2">
              <b-dropdown-item href="/User/Dashboard" @Html.ViewContext.SetActiveIf("/User/Dashboard")><i class="fad fa-dolly-flatbed-alt"></i>Dashboard</b-dropdown-item>
```
This is the result while the page is seems to be loading things.

![kbv1](https://user-images.githubusercontent.com/2191356/81409645-79114a00-910d-11ea-8fc8-c5481150e68d.png)

As you can see, the icons are smashed with the dropdown items and such. Once it seems everything is done loading, it displays as expected.

![kbv2](https://user-images.githubusercontent.com/2191356/81409846-da391d80-910d-11ea-845c-73957b2c3142.png)

I have tried adding `v-cloak` to the `<header>` element above (where I have a Vue component attaching) but that did nothing.

### Versions

**Libraries:**

- BootstrapVue: 2.12.0
- Bootstrap: 4.4.1
- Vue: 2.6.11
- FontAwesome: 5.13.0

**Environment:**
Visual Studio 2019 and Visual Studio Code - using Edge Chromium

- Device: Laptop/Anyhting
- OS: Windows 10
- Browser: Edge Chromium
- Version: 81.0.416.72

**Comment by tmorehouse** [comment]
It sounds like your Bootstrap+BootstrapVue CSS is loading late in the page markup.  Make sure the CSS is loaded in the `<head>` section of your pages

**Comment by Grandizer** [comment]
Awesome.  My css was but the js was not in the head.  Later down the page.  That took care of it.  Thanks!
