### ISSUE TITLE
Add Grouping row support to Table

### ISSUE THREAD

**Issue by ericmagalhaes** [bootstrap-vue/bootstrap-vue#5331]
### Is your feature request related to a problem? Please describe...

Sometimes would be nice to have a grouped view of the data

### Describe the solution you'd like

I would like to be able to set a field to be grouped

### Describe alternatives you've considered

https://www.ag-grid.com/javascript-grid-grouping/

### Additional context

I'm trying to implement my own this feature and I'd like to receive a suggestion on how to create this feature.

So far I have created:

helpers/mixin-group.js
 mixin-group 
 - responsible to identify the fields with group attribute.
 - arrange the data to be displayed on items 
 [Question]
  How can I arrange the data to be used here?
 - Suggestion 1. I created a recursive groupBy function and used on the computedItems but it will broke the pagination mixin because it is not an array is an object.
 - Suggestion 2. Arrange the data like in a group format.

Country    | LastName | Name
----------- |------------|---------------------------
BR (2) ||                          
_|Silva (2)|_|
_|_|Jose|          
_|_|Mario|
_|Pereira(2)|_|
_|_| Fernanda|
_|_| Silvia|

To accomplish this arrange I need to dynamic create the rows and keep the other fields empty.
This approach will follow the existing pattern for renderRow and renderCell on mixin-tbody and mixin-tbody-row.

 mixin-tbody-row
 - for showDetails we have a flag to create the showDetails row. Should I use something like that?

**Comment by tmorehouse** [comment]
This would assume b-table has all the data for the table in memory, which is not always the case (i.e. server-side pagination, server-side filtering, server-side sorting, items provider functions).

A simpler option might be to just have b-table's table row renderer check the previous row data to see if the value is the same, and if so then suppress printing of the cell value. This would assume the same field that is being "grouped" is sorted.  Cells that are grouped would be set as table row headers

| Country    | LastName | Name
| ----------- |------------|---------------------------
| **BR** | **Silva** | Jose |          
| - | - | Mario |
| - | **Pereira** | Fernanda |
| - | - | Silvia |

**Comment by tmorehouse** [comment]
The alternate solution would be to create your own custom component using `<b-table-simple>` and the helper child components.

**Comment by ericmagalhaes** [comment]
Thanks

> This would assume b-table has all the data for the table in memory, which is not always the case (i.e. server-side pagination, server-side filtering, server-side sorting, items provider functions).
> 
> A simpler option might be to just have b-table's table row renderer check the previous row data to see if the value is the same, and if so then suppress printing of the cell value. This would assume the same field that is being "grouped" is sorted (i.e. already ordered by groupings). Cells that are grouped would be set as table row headers (i.e. `<th>`)
> 
> Country	LastName	Name
> **BR**	**Silva**	Jose
> -	-	Mario
> -	**Pereira**	Fernanda
> -	-	Silvia
> And if one wanted the group headers on a separate line, you would pre-massage your data before passing to b-table with extra rows inserted (with the non group fields with null values)

Thanks, looks the best solution...
