### ISSUE TITLE
b-link: preventDefault is not work with props 'to', but work with 'href'

### ISSUE THREAD

**Issue by zWingz** [bootstrap-vue/bootstrap-vue#5337]
### Describe the bug

b-link: `preventDefault` is not work with props `to`, but work with `href`,

maybe caused by https://github.com/vuejs/vue-router/issues/916
```html
<b-link href="example" append @click.prevent>work</b-link>
<b-link to="example" append @click.prevent>not work</b-link>
```

### Steps to reproduce the bug

click `prevent` and then click `not prevent`, it should preventDefault all, but `not prevent` will change route

### Versions

**Libraries:**

- BootstrapVue: latest

**Environment:**

- Device: [Mac]
- OS: [macOS Mojave]
- Browser: [Chrome]
- Version: [81]

### Demo link

[https://codesandbox.io/s/epic-ritchie-e5nni?file=/src/App.vue:32-164](https://codesandbox.io/s/epic-ritchie-e5nni?file=/src/App.vue:32-164)

**Comment by Hiws** [comment]
When using the `href` prop, it will render a normal `<a>` tag.
However, when using the `to` prop, `b-link` will render a `router-link` (or a nuxt variant if used in nuxt) instead. and from what i can find `<router-link>` does not support preventDefault.

You can use the `disabled` prop if you want to disable clicking a link.

or you can capture the click event on a parent element and prevent it that way.

```html
<div @click.capture.prevent>
  <b-link to="example">Link Text</b-link>
</div>
```
Based on the answer given here: https://github.com/vuejs/vue-router/issues/1275#issuecomment-419395124

**Comment by zWingz** [comment]
@Hiws ok, i used `href` props
