### ISSUE TITLE
responsive <b-table> scrollbar overlaps modal

### ISSUE THREAD

**Issue by bLind17** [bootstrap-vue/bootstrap-vue#5338]
### Describe the bug

The horizontal scrollbar of a responsive `<b-table>` overlaps a modal, leaving the table still scrollable and the user confused.

### Steps to reproduce the bug

This is a little weird. I wanted to write a sample page for reproducing the bug, but whatever I tried the scrollbar did not look like in the picture anymore. It was a plain old scrollbar.

I did not change the code of the page since I discovered the bug. I don't know why the scrollbar had changed. Now I'm not sure whether any of you know how to get the scrollbar to look like that, but if you do, please tell me so that I can properly reproduce this bug and post a sample page here.

### Expected behavior

The scrollbar should not overlap the modal.

### Versions

**Libraries:**

- BootstrapVue: 2.12.0
- Bootstrap: 4.1.1
- Vue: 2.6.11

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Firefox
- Version: 76.0

### Additional context

Here's the table in the `<template>`

      <b-table
        responsive
        striped
        head-variant="dark"
        :items="tableItems"
        :fields="tableFields"
        :sort-by.sync="sortBy"
        :sort-desc.sync="sortDesc"
      >
      </b-table>

I've styled the cells to prevent wrapping.

    <style scoped>
      ::v-deep th {
        white-space: nowrap;
      }
      ::v-deep td {
        white-space: nowrap;
      }
    </style>

Here's a screenshot:
![overlapping screenshot](https://user-images.githubusercontent.com/4369345/81494481-90853a00-92a9-11ea-8bc1-0d9d5c3d8788.png)

Hope this helps even though I cannot reproduce it.
Cheers, bLind

**Comment by tmorehouse** [comment]
Does your modal have the `static` prop set? is this modal a "common" modal used or one for each cell/row?

Is the modal in a slot cell or outside of the table?

**Comment by bLind17** [comment]
The modal does not have the `static` prop. 
It is a component outside the table two levels up the DOM tree. I defined a "DialogInfo" component for convenience, I reuse that alot. The code for the component looks like this:

    <template>
      <b-modal
        v-bind:visible="visible"
        v-bind:title="title"
        v-bind:no-close-on-backdrop="mNoClose"
        v-bind:hide-header-close="mNoClose"
        v-bind:no-close-on-esc="mNoClose"
        v-bind:no-enforce-focus="mNoClose"
        :size="size"
        centered
        ok-only
        ok-variant="primary"
        @ok="emitOk"
        @hidden="updateVmodel"
      >
        <template v-slot:modal-footer="{ ok }">
          <slot name="leftOfButton"></slot>
          <b-button variant="primary" @click="ok()">{{ positiveText }}</b-button>
        </template>
        <p class="my-2">
          <slot></slot>
        </p>
      </b-modal>
    </template>

    <script>
    export default {
      name: "DialogInfo",
      props: {
        title: {
          default: "Info"
        },
        positiveText: {
          default: "OK"
        },
        // to user the noClose prop, set it to a truthy value and then use ev.preventDefault on the 'ok' event to prevent closing
        noClose: {
          default: false
        },
        visible: {
          default: false
        },
        size: {
          default: ""
        }
      },
      model: {
        prop: "visible",
        event: "hidden"
      },
      computed: {
        mNoClose() {
          return this.noClose == true;
        }
      },
      methods: {
        updateVmodel() {
          this.$emit("hidden", false);
        },
        emitOk(ev) {
          this.$emit("ok", ev);
        }
      }
    };
    </script>

And I am using it like this:

    <DialogInfo title="Manage teams" :visible="visible" size @hidden="hidden">
    ... filling slots here
    </DialogInfo>

**Comment by tmorehouse** [comment]
Do you have a custom horizontal scroll bar (via CSS/SCSS), or is it using the system/browser default scrool bar?

**Comment by bLind17** [comment]
As you can see in the picture, the scrollbar was not the default scrollbar. But I did not set it up that way. I did not style the scrollbar or set any settings. It just appeared that way...

That's why I couldn't reproduce the bug. When I setup a sample page for the bug everything was back to normal. No fancy scrollbar, no overlap.

I can't explain this, but the screenshot proves that it has indeed happened^^

**Comment by tmorehouse** [comment]
Is it possible you are using a theme CSS that might override the style? or perhaps a browser extension?

**Comment by bLind17** [comment]
As I have said, I can't explain it.
I am not using any css files except the ones provided by bootstrap and bootstrap-vue and some very small ones I wrote myself, none of which touch the scrollbar. And while I can't say that I know that none of my extensions are overriding any CSS, I'm pretty sure they don't.

If you have no explanation for the scrollbar, then I guess the bug is not connected to bootstrap-vue and this issue can be closed. If I ever stumble across this again, I will write again for sure :)

**Comment by Jexordexan** [comment]
This could be from the MacOS system scrollbar for touchpad users. try setting `System Preferences > General > Show scrollbars: Always` and see fi the problem is reproducible. This is probably a browser/system bug

**Comment by bLind17** [comment]
Very good guess! It seems like I was using the `Responsive Design Mode` of Firefox to test another layout. I activated that and could reproduce the bug.

![grafik](https://user-images.githubusercontent.com/4369345/81608165-1dc5ad00-93d6-11ea-8fe5-3fb0cef8620d.png)

**Comment by tmorehouse** [comment]
Must be a browser bug, where it overlays the scrollbar too high up in the z-index (similar to how `<select>` in earlier versions of Internet Exploder was always on "top")

**Comment by tmorehouse** [comment]
I wonder if setting an explicit `z-index` on `<b-table responsive>` will get around this issue?

Perhaps:

```html
<b-table responsive style="z-index: 1;">
```

or 

```html
<b-table responsive style="z-index: 0;">
```

**Comment by bLind17** [comment]
Nope, I tried that, and also setting the z-index of the overlapped element (modal in this case) to the max value, it still overlaps.

I guess it's a simple browser bug, that only exists in the simulated developer test world. Checked on Firefox Android, no bug there ;)
