### ISSUE TITLE
Clicking dropdown item doesn't close the dropdown

### ISSUE THREAD

**Issue by dre1080** [bootstrap-vue/bootstrap-vue#534]
Hi, I'm using bootstrap-vue together with Nuxt.js.
My dropdown items are RouterLink's. When the link is clicked & route changes, the dropdown is still open on the new page.
How do I get it to close when a link is clicked?

**Comment by tmorehouse** [comment]
Which version of bootstrap-vue are you using?

**Comment by tmorehouse** [comment]
There are a fw new enhancements fixes coming out in bootstrap-vue next release (soon), which address some of the issues with `router-link` not propagating a click event upwards.

**Comment by dre1080** [comment]
Using version 0.16.1

**Comment by tmorehouse** [comment]
This should be fixed in the next release.

**Comment by tmorehouse** [comment]
I'll close this issue for now, but we can re-open if the bug persists once release 0.17.0 comes out.
