### ISSUE TITLE
Configure responsive font size (rfs) variables

### ISSUE THREAD

**Issue by BWagener** [bootstrap-vue/bootstrap-vue#5340]
### Describe the bug

I can't seem to customize rfs variables.
Example: Changing $rfs-base-value has no effect.

### Steps to reproduce the bug

Working without bootstrap-vue:
https://stackblitz.com/edit/vuejs-rfs?file=styles.scss L1

Not working with bootstrap-vue:
https://stackblitz.com/edit/vuejs-bootstrap-vue-rfs?file=styles.scss L3

### Versions

**Libraries:**
    "bootstrap": "^4.4.1",
    "bootstrap-vue": "^2.13.1",
    "jquery": "^3.5.1",
    "popper.js": "^1.16.1",
    "vue": "^2.6.11"

**Environment:**

Stackblitz

### Demo link
See above

### Additional context

Maybe I'm just missing something, but I would expect to be able to override these variables. As of now I can't find a way to use bootstrap-vue in combination with customized rfs.

**Comment by tmorehouse** [comment]
`$rfs-base-value` does not appear to be a variable defined by the Bootstrap v4.4.1 SCSS implementation of responsive font size:

https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss
https://github.com/twbs/bootstrap/blob/v4-dev/scss/vendor/_rfs.scss

**Comment by BWagener** [comment]
Great! The second file you linked contains the variable I want. It seems they haven't carried over a variable name change from RFS https://github.com/twbs/rfs/releases/tag/v9.0.0

I was only aware of the latest variable name and the older name doesn't appear in any of the docs.
