### ISSUE TITLE
Calendar selected event does not fire

### ISSUE THREAD

**Issue by ccarstens** [bootstrap-vue/bootstrap-vue#5350]
### Describe the bug

The `selected` event of the calendar does not fire when the user selects a date.

### Steps to reproduce the bug

1. hook a test function that expects at least one argument to `@selected` on the calendar or Datepicker component. The function should log the passed argument
1. open calendar and select a date that isn't disabled
1. no console log appears
1. change `@selected` to `@input` and you'll see the log output

### Expected behavior

I'd expect the `@selected` event to pass a YMD string along with a date object

### Versions

**Libraries:**

- BootstrapVue: 2.13.1
- Bootstrap: 4.#.#
- Vue: 2.6.11

**Environment:**
- OS: macOs Catalina
- Browser: Chrome
- Version: latest-ish

**Comment by tmorehouse** [comment]
Could you create a JsFiddle, CodePen or CodeSandbox minimal reproduction of the issue? you can export an example from the docs playground via https://bootstrap-vue.org/play

**Comment by ccarstens** [comment]
Behaviour can be reproduced in the playground https://codepen.io/ccarstens/pen/Yzyveeo?editors=1011

Btw, how awesome is the playground with the export options 😮 ❤️

**Comment by tmorehouse** [comment]
Note the `<b-form-datepicker>` does not emit the `selected` event, while `<b-calendar>` does have a selected event.

The datepicker component (which is a wrapper for `<b-calendar>`) uses the `selected` event of `<b-calendar>` to know when the user has clicked a date and is to update the model. `<b-form-datepicker>` emits the `input` event, as it is a form control, while `<b-calendar>` is a "widget"

**Comment by ccarstens** [comment]
Oh I see, that makes perfect sense! Thank you for looking into this and for being so fast at it!

**Comment by tmorehouse** [comment]
No problem.. and glad you like the playground export features!
