### ISSUE TITLE
Accordion Component Not Collapsing or Expanding

### ISSUE THREAD

**Issue by digitalgym** [bootstrap-vue/bootstrap-vue#5352]
The accordion component seems to be broken, no longer expands or collapses broken in online documents https://bootstrap-vue.org/docs/components/collapse#accordion-support

reverted to  v2.13.1 working again

**Comment by tmorehouse** [comment]
Hmmm...

this appears to be when the toggle button is an `<a href="#">`, switching to a non href button works, or setting the `href` to the ID of the collapse (i.e. `href="#accordion-1"`).

`v-b-toggle` now checks to see if the click event was `evt.defaultPrevented` (which `<b-link>` does do a `evt.preventDefault()` on links with `href="#"` to prevent scroll-to-top of window behavior).

We will need to update the docs to switch the example to use buttons (i.e. remove the `href` attribute).

**Comment by tmorehouse** [comment]
The docs have been updated to remove the not-needed `href="#"` from the accordion buttons.
