### ISSUE TITLE
Docs - Validation examples appearing blank

### ISSUE THREAD

**Issue by Hiws** [bootstrap-vue/bootstrap-vue#5354]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs/reference/validation
The validation examples all appear to be showing up blank.
Tried opening it up on codesandbox, but still had the same issue.

Browser: Chrome
OS: Win10

**Comment by jackmu95** [comment]
This seems to be an Problem with CodeSandbox in general.

**Comment by jackmu95** [comment]
The examples were updated and are working properly again!
