### ISSUE TITLE
[modal] Issue show/hide with v-model

### ISSUE THREAD

**Issue by stefan-angelov** [bootstrap-vue/bootstrap-vue#536]
I try to use modal component with v-modal in my project, but the modal doesn't show and there is no error message.I have tried to debug it in many different ways, but couldn't pinpoint it.
Then i made a new fresh project with the same setup - using vue-cli with webpack template and there the modal worked with v-model.
Then in my project i changed the bootstrap-vue's modal component according to Vue documentation: [https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events](url) (declare prop 'visible' explicitly) and it worked as expected.
Should the modal component be edited according to Vue documentation?
Or is there something else i can do to solve the problem?

**Comment by tmorehouse** [comment]
Which version of Bootstrap-vue are you using? THis should work in version 0.16.1:

https://jsfiddle.net/pi0/orjf0g75/

**Comment by stefan-angelov** [comment]
I didn't see that I was using an old version. I was with 0.15.6 but when updated to 0.16.1 everything worked perfectly. My bad, sorry, you can close the issue

**Comment by tmorehouse** [comment]
Glad it is working for you now!
