### ISSUE TITLE
<b-form-select> to have ability to filter

### ISSUE THREAD

**Issue by nazmulislam** [bootstrap-vue/bootstrap-vue#5367]
### Is your feature request related to a problem? Please describe...

Is there a way to to filter the b-form-select to have filter capability

### Describe the solution you'd like

The ability to enable via prop to enable search / filter similar to https://vue-select.org/

Thank you

**Comment by tmorehouse** [comment]
`<b-form-select>` is just Bootstrap v4 styled native HTML5 `<select>`, and as such has all teh limitations of a native `<select>` element.

**Comment by nazmulislam** [comment]
Tmorehouse,

Thank you for the clarification, is there any plans on creating a separate bootstrap-vue component similar to the v-select?

**Comment by tmorehouse** [comment]
There are plans for a dropdown-based select component (a well as an auto-suggest input, based on dropdown) that will be in a near-future release
