### ISSUE TITLE
Dropdown not working inside of the shadow root

### ISSUE THREAD

**Issue by jwayne2** [bootstrap-vue/bootstrap-vue#5369]
### Describe the bug

If build target is web component then dropdown is not working. With Chrome clicking the button doesn't open the dropdown menu. With Firefox menu seems to open sometimes.

### Steps to reproduce the bug

1. Create default Vue project with the command _vue create hello-world_ and install BootstrapVue
2. Edit Helloworld.vue. Import BootstrapVue. Copy first example from Dropdown documentation
3. Edit package.json and change build script to: _vue-cli-service build --target wc --name my-element src/App.vue_
4. Run yarn build
5. Open dist/demo.html in browser
6. Try to open dropdown menu

### Expected behavior

Menu shoud open when clicking the button.

### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- Device: Laptop
- OS: Linux
- Browser: Chrome and Firefox
- Version: Latest

### Demo link

Example template is here https://codesandbox.io/s/c4rph
This example works because it is not web component. You must manually build web component to reproduce the problem.

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
Dropdown (and other components) check for visibility of certain elements, and it does so by checking if the element is in the DOM (a descendant of `<body>`), among other tests (offsetParent, etc).  In Shadow DOM, the children elements are sandboxed and not descendants of the document `<body>` element.

**Comment by jwayne2** [comment]
I got it working. Had to edit whileOpenListen -function in the file mixins/dropdown.js:
```
 whileOpenListen(isOpen) {
   if (typeof this.$refs.menu.getRootNode !== 'undefined') {
        this.focusInElement = this.$refs.menu.getRootNode();
  }
....
```
Keyboard navigation didn't yet work so I had to modify isVisible -function in dom.js :
```
export const isVisible = el => {
  if (!isElement(el) || !el.parentNode) {
    return false
  }
  
  if (!contains(d.body, el) && !(!el.shadowRoot || !contains(el.shadowRoot, el))) {
    return false
  }
  if (el.style.display === 'none') {
....
```
Would you consider making these changes to support dropdown also in shadow DOM?

**Comment by shash7** [comment]
Is there a solution to this apart from diving in the source and making this change?

**Comment by paulwer** [comment]
The solution above worked for me. 
Is there an oportunity, that someone could implement this into the live-version of the library?

**Comment by DinosaurDad** [comment]
> I got it working. Had to edit whileOpenListen -function in the file mixins/dropdown.js:
> 
> ```
>  whileOpenListen(isOpen) {
>    if (typeof this.$refs.menu.getRootNode !== 'undefined') {
>         this.focusInElement = this.$refs.menu.getRootNode();
>   }
> ....
> ```

Thanks for this @jwayne2. I know this issue is closed, but in case anyone runs across this in the future...

We use Vue3 and a different UI library mostly now, but one of our projects is still Vue2 and BootstrapVue. We created an extension of the Dropdown to include your fix in a relatively clean way:

FixBDropdown.js:

```javascript
import {BDropdown} from "bootstrap-vue"

export default {
  extends: BDropdown,
  methods: {
    whileOpenListen(isOpen) {
      if (typeof this.$refs.menu.getRootNode !== 'undefined') {
        this.focusInElement = this.$refs.menu.getRootNode();
      }
      BDropdown.options.methods.whileOpenListen.call(this, isOpen)
    },
  }
}
```

Then you can just `import FixBDropdown from "./FixBDropdown"` and use it where you would have used BDropdown, without having to rebuild the BootstrapVue project.
