### ISSUE TITLE
[modal] Close on Esc key doesn't work with tabs inside

### ISSUE THREAD

**Issue by stefan-angelov** [bootstrap-vue/bootstrap-vue#537]
I use modal with tabs and when i hide the tabs' heads (display: none) and press Esc key the modal doesn't close. JS Fiddle: [https://jsfiddle.net/94rt6vhL/2/](url)

**Comment by tmorehouse** [comment]
Modal focuses the first input/button/link that it finds in the modal content.  In this example you have hidden the tabs tab buttons.  Revealing the tab buttons makes the close on ec work.

See: https://jsfiddle.net/94rt6vhL/3/

Hiding the tab buttons break tab functionality.

**Comment by tmorehouse** [comment]
I have created  PR #538  that may help with this issue.

**Comment by stefan-angelov** [comment]
Thank you for the fast response!!!!

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
