### ISSUE TITLE
Ability to select year in <b-form-datepicker>

### ISSUE THREAD

**Issue by samturrell** [bootstrap-vue/bootstrap-vue#5370]
### Is your feature request related to a problem? Please describe...

When using a datepicker input, sometimes the user needs to select a date that's years in the past. To do this you would quickly click the `<<` button to go back a year. The problem is when clicking repeatedly the calendar changes size and you end up clicking "no date selected" which resets the selected month to the current month.

Also, depending on how far they need to go back, this isn't a great user experience.

### Describe the solution you'd like

I'm thinking an easier way to select the year would be a dropdown of some sort when clicking on the year so you can instantly select the year you're wanting.

### Describe alternatives you've considered

Previous projects have had to ditch the date picker completely and move more towards and input-mask type of field. Other projects have had a hybrid combination of both for different types of input, but would be good to have a unified solution.

**Comment by tmorehouse** [comment]
Duplicate: #4976

Set the `show-decade-nav` prop on the datepicker to enable the decade navigation buttons.

See https://bootstrap-vue.org/docs/components/form-datepicker#optional-decade-navigation-buttons

Also see the button only feature for providing your own text input field (you will need your own date parsing methods, and you could use the 3rd party `v-mask` on your input)

https://bootstrap-vue.org/docs/components/form-datepicker#button-only-mode

**Comment by samturrell** [comment]
I don't think they solve the UX issue in my second example, and the decade buttons definitely clutter up the UI.

I understand it's a tricky one though with respect to a11y as the linked issues suggest.

**Comment by Hiws** [comment]
One way to help the problem a little, could be to set a fixed height on the datepicker's body, which is what's causing the shift in height. Since some months have 5 rows and some 6 rows.

The CSS i found to work is the following. 
The height is how big the body is with 6 rows, and vertically centers the content when there's only 5.

```css
.b-calendar-grid-body {
  height: 228px;
  display: flex;
  flex-direction: column;
  justify-content: center;
}
```

**Comment by a-kriya** [comment]
Ability to select a month and year directly is arguably a better UX than moving by decades and years, at least in some cases.

Try entering your birth date in [BV's datepicker](https://bootstrap-vue.org/docs/components/form-datepicker), and [in Buefy's](https://buefy.org/documentation/datepicker/):

![image](https://user-images.githubusercontent.com/26761352/122219082-b62d3b80-cecc-11eb-82cd-46b90a1233e2.png)

Buefy's datepicker also allows selecting date ranges, multiple random dates, inline display, and customizing header/footer of the picker, which are some of the other feature requests that are seen here. Perhaps BV can take some inspiration from it?

**Comment by Hiws** [comment]
Keyboard navigation seems very lacking in `Element+`.

I generally like Buefy's method of having two dropdowns, and the keyboard navigation seems pretty good as well. 
Except for the fact that it crashes the entire page when going "up" in the date selection. But I'm sure that's something that can be fixed.

**Comment by a-kriya** [comment]
@Hiws Yeah, they lack in terms of accessibility. It's cool to be open to improvements in BootstrapVue's datepicker. Do you think this issue should be re-opened?
