### ISSUE TITLE
Weird behaviour using v-slot in b-collapse and .when-close/.when-open

### ISSUE THREAD

**Issue by Gantorys** [bootstrap-vue/bootstrap-vue#5371]
### Describe the bug

When you have some button with the hiding and showing "trick" based on the docs' css, if you use v-slot on collapse, the moment you change some reactive data on the component, the "trick" starts failing.

### Steps to reproduce the bug

1. Go to https://jsfiddle.net/h6pv3jLs/1/
2. Click on "Count" button.
3. You'll see that [Open] changes to [Close].
4. If you change the fiddle, removing the v-slot="{ visible }" part, the problem is gone.

### Versions

**Libraries:**

- BootstrapVue: 2.13.0
- Vue: 2.6.11
- Bootstrap: 4.4.1

**Comment by tmorehouse** [comment]
Upgrade to Bootstrap v2.14.0+

https://jsfiddle.net/ckLhemqp/1/

The new CSS class `not-collapsed` was introduced in v2.14 with additional `v-b-toggle` features

https://bootstrap-vue.org/docs/directives/toggle#hiding-and-showing-content-in-the-toggle-trigger-element
