### ISSUE TITLE
export 'SidebarPlugin' was not found in 'bootstrap-vue' [nuxt]

### ISSUE THREAD

**Issue by chris-aeviator** [bootstrap-vue/bootstrap-vue#5375]
### Describe the bug
When adding `SidebarPlugin` to my nuxt config, nuxt throws a warning serverside:

 `export 'SidebarPlugin' was not found in 'bootstrap-vue'`

And the browser window debugger errors on ` Cannot read property 'install' of undefined `

```
   if (typeof plugin.install === 'function') {
      plugin.install.apply(plugin, args);
```

This is my config which works fine without `SidebarPlugin`:

```
  modules: [
    ['bootstrap-vue/nuxt', {
      bootstrapCSS: true,
      bootstrapVueCSS: true,
      componentPlugins: [
        'SidebarPlugin',
        'VBTogglePlugin',
        'NavbarPlugin',
        'LayoutPlugin',
        'ProgressPlugin',
        'AlertPlugin',
      ],
      directivePlugins: [
        'Tooltip',
        'Popover'
      ]
    }],
...
```

I have tried also manually adding `VBTogglePlugin` which does not lead to any success. 

### Steps to reproduce the bug

1. Setup nuxt with bootstra-vue
2. import `SidebarPlugin` via modules-> bootstrap-vue/nuxt options -> componentPlugins
3. build 
4. browse to your nuxt apps `/`

### Versions

**Libraries:**

- BootstrapVue: 2.4.0
- Bootstrap: 4.4.1
- Nuxt 2.0.0

**Environment:**

- Device: X1 Carbon
- OS: Arch
- Browser: Mozilla Firefox
- Version: e.g. 70

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
The sidebar component was added in version `v2.10.0` of BootstrapVue (you are using `v2.4.0`).

https://bootstrap-vue.org/docs/components/sidebar

> Available in BootstrapVue since v2.10.0

Upgrade to `v2.10.0` or greater (latest is `v2.14.0`)
