### ISSUE TITLE
b-table unit test v-slot with function call

### ISSUE THREAD

**Issue by HamidNE** [bootstrap-vue/bootstrap-vue#5380]
I use bootstrap-vue for the vue.js css framework and decided to test the desired component. This component uses b-table and has a v-slot with a call function.

```html
<template>
	<b-table
		striped
		bordered
		:items="items"
		:fields="$t('pages.events.show.users.fields')"
	>
		<template v-slot:cell(name)="{ item }">
			<b-avatar :src="item.avatar" class="mr-2" />
			<span v-text="item.name" />
		</template>
	</b-table>
</template>
```

and I'm writing a simple test for this component:

```js
import { shallowMount } from "@vue/test-utils";
import EventUsersTable from "./EventUsersTable.vue";

/* #region  Test setup */
const factory = () => {
	return shallowMount(EventUsersTable, {
		mocks: {
			$t: jest.fn()
		},
		stubs: {
			BTable: true
		}
	});
};
/* #endregion */

describe("EventUsersTable.vue", () => {
	let wrapper;
	beforeEach(() => (wrapper = factory()));

	test("should render component", () => {
		expect(wrapper.html()).toMatchSnapshot();
	});
});
```

and i have error with this content: `[Vue warn]: Error in render: "TypeError: Cannot read property 'item' of undefined"`

for write test for this component i need fix this problem.

And I have a problem with the vue unit test document, they are very limited and with few examples.
If anyone knows a source that has more examples and scenarios for vue language tests, thank you for introducing it.

**Comment by Hiws** [comment]
I don't know the answer, but the best place to look would probably be in this repo.
`Bootstrap-Vue` uses `@vue/test-utils` internally to test all the components, and you can find all these tests looking through the source code.

[Here](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/table/table.spec.js) is the one for `b-table`.

**Comment by HamidNE** [comment]
And I apologize, I know I have to ask my questions at stackOverflow, and I've done that, but I haven't found the answer, and because I needed to answer that question, I had to ask it in issues.

**Comment by tmorehouse** [comment]
Note `shallowMount` does not mount/render child components (i.e. b-table, and its child components).  Try using `mount` instead.

**Comment by hamidne-raimun** [comment]
Thank you very much @tmorehouse, using mount and adding the main component was able to solve my problem.

```js
import { mount } from "@vue/test-utils";
import { BTable } from "bootstrap-vue";
import EventUsersTable from "./EventUsersTable.vue";

/* #region  Test setup */
const factory = () => {
	return mount(EventUsersTable, {
		mocks: {
			$t: jest.fn()
		},
		stubs: {
			BTable
		}
	});
};
/* #endregion */

describe("EventUsersTable.vue", () => {
	let wrapper;
	beforeEach(() => (wrapper = factory()));

	// FIXME: fix this bug for render component
	test("should render component", () => {
		expect(wrapper.html()).toMatchSnapshot();
	});
});
```

**Comment by HamidNE** [comment]
Thank you very much @tmorehouse, using mount and adding the main component was able to solve my problem.

```js
import { mount } from "@vue/test-utils";
import { BTable } from "bootstrap-vue";
import EventUsersTable from "./EventUsersTable.vue";

/* #region  Test setup */
const factory = () => {
	return mount(EventUsersTable, {
		mocks: {
			$t: jest.fn()
		},
		stubs: {
			BTable
		}
	});
};
/* #endregion */

describe("EventUsersTable.vue", () => {
	let wrapper;
	beforeEach(() => (wrapper = factory()));

	// FIXME: fix this bug for render component
	test("should render component", () => {
		expect(wrapper.html()).toMatchSnapshot();
	});
});
```
