### ISSUE TITLE
No scss variable for b-nav-item inside b-nav

### ISSUE THREAD

**Issue by thebspin** [bootstrap-vue/bootstrap-vue#5394]
### Describe the bug

The color on an a href inside the b-nav-item component gets it value from _reboot.scss. This makes me believe there is no scss variable for it. I looked for it in the bootstrap docs and in this repo (https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/_variables.scss)

### Steps to reproduce the bug

```
  <b-nav vertical>
    <b-nav-item>Home</b-nav-item>
  </b-nav>
```

### Expected behavior

I expected the color to be set by a scss var, and not by _reboot.scss

### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.5.0
- Nuxt: 2.12.2

### Additional context

![image](https://user-images.githubusercontent.com/203133/82254126-9686b500-9952-11ea-9a9b-13d8ee4d19d4.png)

**Comment by thebspin** [comment]
Might actually be a bootstrap thing.. I made an issue on the github of bootstrap.

https://github.com/twbs/bootstrap/issues/30847

**Comment by jackmu95** [comment]
Nav items (`<b-nav-item>`) are just links - a list item (`<li>`) containing a links to be precise.
Since it's Bootstrap's goal to provide unified styles across components, there is no special variable for changing the link color of navigation items.

If you really want to do it anyway you can write your own styles:

```scss
$nav-link-color: #6f42c1;

.nav-link {
  color: $nav-link-disabled-color;
}
```

**Comment by thebspin** [comment]
I expected there to be some scss vars.. I understand that they are .nav-links but in my opinion that is still something else then a normal a href somewhere on my page. I'll have to do with the workaround then unless the bootstrap team also agrees with me.
