### ISSUE TITLE
[Feature Request} b-nav-header - Nav menu header

### ISSUE THREAD

**Issue by Max98** [bootstrap-vue/bootstrap-vue#5399]
### Is your feature request related to a problem? Please describe...

Instead of having multiple `b-nav` tags and between each, a header to separate different menus, it would be nice to just include a `b-nav-header` tag inside `b-nav` that just outputs a non selectable `b-nav-item` with a slightly different styling.

P.S: This would affect only he vertical `b-nav` menu

### Describe the solution you'd like

```
<b-nav vertical pills fill>
  <b-nav-header>Menu 1</b-nav-header>

  <b-nav-item active>Active</b-nav-item>
  <b-nav-item>Link</b-nav-item>
  <b-nav-item>Another Link</b-nav-item>
  <b-nav-item disabled>Disabled</b-nav-item>

  <b-nav-header>Menu 2</b-nav-header>

  <b-nav-item>Link</b-nav-item>
  <b-nav-item>Another Link</b-nav-item>
  <b-nav-item disabled>Disabled</b-nav-item>
</b-nav>
```

Example: 
![image](https://user-images.githubusercontent.com/4823878/82292868-84813280-99a3-11ea-8b08-99910c82d3c2.png)

### Describe alternatives you've considered

-

### Additional context

I might give it a try and do it myself and end up with a pull-request but i'm not sure I would do it soon.

**Comment by tmorehouse** [comment]
You should be able to use `<b-nav-text>` component for this.

**Comment by Max98** [comment]
> You should be able to use `<b-nav-text>` component for this.

Yes, it's possible, but the result is not as expected.
![image](https://user-images.githubusercontent.com/4823878/82293486-8697c100-99a4-11ea-87c9-7481999e5d17.png)
``` <b-nav vertical pills fill>
                        <b-nav-text>Header</b-nav-text>
                        <b-nav-item active>Active</b-nav-item>
                        <b-nav-item>Link</b-nav-item>
                        <b-nav-item>Another Link</b-nav-item>
                        <b-nav-item disabled>Disabled</b-nav-item>
                    </b-nav>
```
I would have to do css styling for it to work correctly. What i was asking for was a already built in house faster way.

**Comment by tmorehouse** [comment]
BootstrapVue is not about forcing a particular style upon users, which means CSS is your friend :wink:

**Comment by Max98** [comment]
> BootstrapVue is not about forcing a particular style upon users, which means CSS is your friend 😉 Don't be scared of CSS.

I'm not scared of css, I just thought this could be a nice small feature.
You can close this if you think it is irrelevant.

**Comment by SelfhostedPro** [comment]
A vertical nav menu for a sidebar shouldn't be considered out of scope. This is a standard thing in semantic-ui, I don't see why you shouldn't at least consider adding this.
