### ISSUE TITLE
Bootstrap nested rows with collapsible feature

### ISSUE THREAD

**Issue by praveen-wal** [bootstrap-vue/bootstrap-vue#5405]
### Is your feature request related to a problem? Please describe...

I need to know if there is a way to create a table that has nested rows i.e. On expanding a row, more rows should open and vice versa.

### Describe the solution you'd like

Something like this https://naughty-hugle-cca02d.netlify.app/guide/examples/search.html

**Comment by tmorehouse** [comment]
Check out `details rows` and placing a nested child table in the details slot.

https://bootstrap-vue.org/docs/components/table#row-details-support
