### ISSUE TITLE
Submenu/Subdropmenu for Navbar and Dropdownmenu

### ISSUE THREAD

**Issue by xiaohuilam** [bootstrap-vue/bootstrap-vue#5406]
### Is your feature request related to a problem? Please describe...
No.

### Describe the solution you'd like
Submenu/Subdropmenu for Navbar and Dropdownmenu
![image](https://user-images.githubusercontent.com/6964962/82421999-7838ca80-9ab4-11ea-8dfb-333443f6994d.png)

**Comment by Hiws** [comment]
Think this might be a duplicate of:
https://github.com/bootstrap-vue/bootstrap-vue/issues/3435

**Comment by Hiws** [comment]
Closing this in favor of the other issue.
