### ISSUE TITLE
vue component in b-table cell

### ISSUE THREAD

**Issue by fessacchiotto** [bootstrap-vue/bootstrap-vue#5407]
hello! is it possible to have a vue component, for example a contextual menu, as content in a b-table cell? thank you!

<img width="634" alt="Screenshot 2020-05-20 at 10 23 15" src="https://user-images.githubusercontent.com/97323/82423670-64757000-9a84-11ea-8ee2-ab2fbe691144.png">

**Comment by tmorehouse** [comment]
Yes.   See the custom data rendering section (using scoped slots):

https://bootstrap-vue.org/docs/components/table#custom-data-rendering

**Comment by fessacchiotto** [comment]
Thank you!
