### ISSUE TITLE
getting b-pagination-nav to work with a dynamically populated b-card-group using asyncData in Nuxt.js 

### ISSUE THREAD

**Issue by Hitoshura12** [bootstrap-vue/bootstrap-vue#5412]
Hello,
I am working on a markdown blog in Nuxt.js (getting started with it) with a group of bootstrap-vue b-cards nested inside a `b-card-group` to show a list of blog posts. So far the b-pagination works in the console and based on the documentation instruction for a list, it does indeed show the sliced array of posts in the console as intended.  The problem is, using a normal list and `div` tag, this would easily work, but I am trying to get it to work and find the right and correct way to bind it with the `b-card-group` as it does not show the sliced array per pagination number given that the posts are already returned in asyncdata(prefetched).
 **expected :**
 to show a sliced list of 3 posts per pagination index according to the perPage computed property (console results work for computed).
**got :**
 all the posts appear in all paginations due to v-for repeating.
I am clueless to how to bind this situational case as the documentation, while comprehensive, doesn't show a similar case. 
Thank you for your time.
here is the code below :
```
<template>
  <div class="post-box">
    <h1 class="title">All the posts</h1>
    <ul id="posts" class="posts">
      <b-card-group
        v-for="post in posts"
        :key="post.attributes.id"
        v-bind="slicedposts"
      >
        <nuxt-link :to="getPermalink(post)">
          <b-card
            :img-src="
              require(`@/assets/images/blog/${post.attributes.id}/thumbnail.jpg`)
            "
            img-height="350rem"
            :title="post.attributes.title"
            tag="article"
            alt="blog picture"
          >
            <p class="description">{{ post.attributes.description }}</p>

            {{ post.attributes.year }}
          </b-card>
        </nuxt-link>
      </b-card-group>
    </ul>
    <b-pagination-nav
      v-model="currentPage"
      :link-gen="linkGen"
      :number-of-pages="numPages"
      align="center"
    ></b-pagination-nav>
  </div>
</template>

<script>
export default {
  // eslint-disable-next-line require-await
  async asyncData() {
    const resolve = require.context('~/content/', true, /\.md$/)
    const imports = resolve.keys().map((key) => {
      // eslint-disable-next-line no-unused-vars
      const [, name] = key.match(/\/(.+)\.md$/)
      return resolve(key)
    })
    return {
      posts: imports
    }
  },
  data() {
    return {
      prefix: 'posts',
      currentPage: 1,
      perPage: 3
    }
  },
  computed: {
    slicedposts() {
      console.log('hello from posts')
      const items = this.posts
      console.log(this.currentPage)
      return console.log(
        items.slice(
          (this.currentPage - 1) * this.perPage,
          this.currentPage * this.perPage
        )
      )
    },
    numPages() {
      console.log(' current pagination: ' + this.currentPage)
      console.log('total rows:' + Math.ceil(this.posts.length / this.perPage))
      return Math.ceil(this.posts.length / this.perPage)
    }
  },

  methods: {
    linkGen(pageNum) {
      console.log('pageNum' + pageNum)
      return '#page=' + pageNum
      // return pageNum === 1 ? '?' : `?page=${pageNum}`
    },

    getPermalink(post) {
      // eslint-disable-next-line no-prototype-builtins
      if (post.attributes.hasOwnProperty('permalink')) {
        return `${this.prefix}/${post.attributes.permalink}`
      } else {
        return `${this.prefix}/${
          post.meta.resourcePath
            .split('\\')
            .pop()
            .split('/')
            .pop()
            .split('.')[0]
        }`
        // return  `${this.prefix}/${path.basename(post.meta.resourcePath, ".md")}`;
      }
    }
  }
}
</script>
```

**Comment by tmorehouse** [comment]
Shouldn't your `v-for` loop be iterating over your `slicedposts` computed prop?

```html
      <b-card-group
        v-for="post in slicedposts"
        :key="post.attributes.id"
        v-bind="slicedposts"
      >
```

You may also want to enable `use-router` on `b-pagination-nav` (or return a location object instead of a string: `{ query: { page: pageNum } }`) so that the router is used, rather than doing full page reloads.

**Comment by Hitoshura12** [comment]
Hello,
> Shouldn't your `v-for` loop be iterating over your `slicedposts` computed prop?

I have already tried that firsthand and it returned a blank page. The thing is inside asyncData function, the returned posts array takes from the imports of webpack require, as shown here
```
async asyncData() {
    const resolve = require.context('~/content/', true, /\.md$/)
    const imports = resolve.keys().map((key) => {
      // eslint-disable-next-line no-unused-vars
      const [, name] = key.match(/\/(.+)\.md$/)
      return resolve(key)
    })
    return {
      posts: imports
    }
```
 the returned result is then stored inside of `posts` then passed to `v-for` to iterate through the resulting array to distribute to the b-card component. when I tried passing  the results of `this.posts` to a const in order to avoid conflict and use it as a computed property for v-for after I introduced the pagination component, it returns a blank page, but the console still shows the desired results. joined here is the stack trace of the console.log showing the slice arrays.
![post](https://user-images.githubusercontent.com/27700302/82493499-982db580-9ad7-11ea-97a3-638cf403f1bc.jpg)

as for use-router, yes, you are right that it helps avoid page reloads, it's just during tests it keeps scrolling up for the results (as it's supposed to be) when I wanted to keep watching the changes below. I will use.
Thank you for your time.

**Comment by tmorehouse** [comment]
Just realized your computed prop is not returning the data:

```
  computed: {
    slicedposts() {
      const items = this.posts || []
      return items.slice((this.currentPage - 1) * this.perPage, this.currentPage * this.perPage)
    },
 ```

**Comment by Hitoshura12** [comment]
Hello,
Thank you.
It was indeed that. I used console.log for testing purposes and once removed it, it showed the results as intended.
Thanks.
