### ISSUE TITLE
b-skeleton-loader component

### ISSUE THREAD

**Issue by thebspin** [bootstrap-vue/bootstrap-vue#5413]
### Is your feature request related to a problem? Please describe...

There currently is no skeleton loader component build in into the framework.
Now i am aware bootstrap itself also has no solution for it!
There are packages like: https://www.npmjs.com/package/vue-loading-skeleton that do provide a loader.
However i would rather depend on a components that are provided by the framework provider i am using. Not too long ago the good folks at Vuetify also introduced an skeleton loader that integrates nicely with the framework itself. ( https://vuetifyjs.com/en/components/skeleton-loaders/ )

### Describe the solution you'd like

A component that suits the bootstrap feel visually, and is flexibel for short, longer texts, avatars or blocks.

### Describe alternatives you've considered

Using the vue loading skeleton package linked earlier

### Additional context

If the answer is, just use the package i could understand that. I do hope however you will consider providing this. Even if it might take a while.

**Comment by Hiws** [comment]
There's an entry for a skeleton component on the roadmap.

https://github.com/bootstrap-vue/bootstrap-vue/projects/9#card-34984320
