### ISSUE TITLE
Lazy load videos

### ISSUE THREAD

**Issue by amoralesdesign** [bootstrap-vue/bootstrap-vue#5414]
I use the `<b-img-lazy>` component a lot, it's very useful.

Can you create one like it for lazy load video? Like **`<b-video-lazy>`**

More and more videos are used in html:

```html
<video role="presentation" preload="auto" playsinline="" crossorigin="anonymous" style="width:100%;" loop="" muted="" class="bgVideovideo" autoplay="" src="https://randomurl.com/video.mp4"></video>
```

**Comment by tmorehouse** [comment]
You can do this with a combination of [`<b-embed>` component](https://bootstrap-vue.org/docs/components/embed) (for responsive size video embeds), and the [`v-b-visible.once` directive](https://bootstrap-vue.org/docs/directives/visible) applied to `<b-embed>`. Just provide `v-b-visible` with a callback method that updates (or v-if's) your `<b-embed>` `src` prop (or `<source>` elements).

```html
<template>
  <b-embed
    v-b-visible.once="callback"
    type="video"
    aspect="16by9"
    poster="poster.png"
    crossorigin="anonymous"
    loop
    muted
    autoplay
  >
    <source v-if="visible" src="https://randomurl.com/video.mp4" type="video/mp4">
  </b-embed>
</template>

<script>
export default {
  data() {
    return {
      visible: false
    }
  },
  methods: {
    callback(visible) {
      if (visible) {
        this.visible = true
      }
    }
  }
}
</script>
```
