### ISSUE TITLE
nested collapse does not work with 2.14.0

### ISSUE THREAD

**Issue by foxmask** [bootstrap-vue/bootstrap-vue#5417]
### Describe the bug

Collapse was working from 2.7.0 to 2.13.0 but not with 2.14.0

### Steps to reproduce the bug

When using 2 nested collapse the 1 first does not work at all, here is how I use them

```
          <b-card no-body class="mb-1">
            <b-card-header header-tag="header" class="p-1" role="tab">
              <b-button block href="#" v-b-toggle.folders variant="info"><i class="fas fa-folder-open"></i>  Folders</b-button>
            </b-card-header>
            <b-collapse id="folders" visible accordion="my-folders" role="tabpanel">
              <b-card-body>
                <b-btn v-b-toggle.newfolder variant="primary" size="sm"><i class="fas fa-plus-circle"></i> New folder </b-btn>
                   <b-collapse id="newfolder" class="mt-2">
                    <form @submit.prevent="newFolder">
                       <div class="form-group">
                         <input type="text" v-model="folder" class="form-control" id="folder" placeholder="Folder name">
                        </div>
                    </form>
                  </b-collapse>
                <b-card-text><folders></folders></b-card-text>
              </b-card-body>
            </b-collapse>
          </b-card>
```

### Expected behavior

Being able to collapse ^^

### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.#.#
- Vue: 2.6.11

**Environment:**

- OS: Linux Ubuntu 20.02
- Browser: Firefox
- Version: 76.0.1

**Comment by tmorehouse** [comment]
Remove the `href="#"` from your button's with the `v-b-toggle` directive:

```html
<b-button block v-b-toggle.folders variant="info">
```

**Comment by tmorehouse** [comment]
This will be fixed in release `v2.15.0`, but in general avoid using `href="#"` when using `v-b-toggle` on `<b-button>`.

**Comment by foxmask** [comment]
ok, thanks

**Comment by foxmask** [comment]
I could test without `href="#"` and that works. 
thanks

**Comment by tmorehouse** [comment]
BootstrapVue 2.15.0 has been released which includes a fix.  But I would still recommend not adding `href="#"` to `<b-button>` when using for a collapse toggle
