### ISSUE TITLE
return a promise from a modal open

### ISSUE THREAD

**Issue by rgeerts** [bootstrap-vue/bootstrap-vue#5423]
### Is your feature request related to a problem? Please describe...

I would like a way to get a promise or callback when a modal is opened. 

### Describe the solution you'd like

this.$bvModal.show(id).then((args) => {
//do some thing here
})

OR

this.$bvModal.showWithCallback(id).then((args) => {
//do some thing here
})

### Describe alternatives you've considered

 I understand you can listen for events.  But if I am reusing a modal for different situations it can get a little crazy to listen for a modal close and figure out what situation it got closed in.

You can also emit events back to the parent.  But sometimes the modal definition isn't in the parent where you opened the modal from.  It could be defined in the grandparent or great-great-great grandparent or even a child.

**Comment by tmorehouse** [comment]
Related to feature request #2206

**Comment by Hiws** [comment]
You might be interested in the third option listed in this answer:
https://stackoverflow.com/a/60547547/8397974

**Comment by rgeerts** [comment]
@Hiws - yeah the third option is custom wrapper that I could implement and I may do so yet(Thanks!).  Been using this framework for a year and quite pleased with it. I keep running into this issue. Just thought I would see if I could give some ideas to help improve the framework for all instead of trying to roll my own.

**Comment by Hiws** [comment]
Yeah, i definitely think this would be a awesome thing to have built in, and it looks to be on the roadmap.

Another related issue: https://github.com/bootstrap-vue/bootstrap-vue/issues/3246

Just wanted to offer a possible workaround for you to make a more generic solution until it gets added.

**Comment by tmorehouse** [comment]
We might have to make a few options for this, i.e. returning a promise when opened, or when closed, or taking an object of callbacks (i.e. `onShow`, `onShown`, `onHide`, `onHidden`), or passing a data object to pass to the modal's scoped slots to use, and an option to return a promise.

The thing with `this.$bvModal.show(id)` is that it knows nothing about the modal instance (it just fires an event with the modal's ID... which the modal listens for).  We would have to set up $once root listeners for the show event to get a reference to the modal Vue instance (which requires modals and the `$bvModal` to be parented to the same Vue app instance.  Perhaps, we could use the `modalManager` instance (which manages modal stacking) as a go-between for this type of communication.

**Comment by websanova** [comment]
Also really need this....

I think something as simple as passing in a secondary set of options as mentioned with `onX` events would be fine.

Also on a side note, the `no-stacking flickers the background which is kind of annoying. Actually if I just do a hide followed by a show it works perfectly, so bit strange for that flicker.

**Comment by Hiws** [comment]
@websanova 
Regarding the flickering, it's because when applying `no-stacking`, it will wait for the hide transition to finish, before opening the new one.
and for a few ms, the old one disappear before the new one appears.

This issue isn't there if you manually use `$bvModal.hide` and `$bvModal.show` since you open the new one immediately instead of waiting.

If you combine `no-stacking` and `no-fade` you wont see the flickering, but will lose the transition.
So you can use that if that isn't an issue for you.
