### ISSUE TITLE
Overlay Component Issue

### ISSUE THREAD

**Issue by DavidScicluna** [bootstrap-vue/bootstrap-vue#5426]
### Describe the bug

I am trying to use the overlay component but an error is showing up in the console: 

" Unknown custom element: <b-overlay> - did you register the component correctly? For recursive components, make sure to provide the "name" option. "

Can you please help with this issue?

### Expected behavior

Since it's in the documentation I expect that the component should be working fine.

### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- Device: Lenovo X1 Carbon
- OS: Windows 10 Pro
- Browser: Chrome
- Version: 83.0.4103.61

**Comment by Hiws** [comment]
Could you provide some sort of reproduction?
Without seeing any code it can be difficult to help out.

**Comment by DavidScicluna** [comment]
I am importing all of the components in main.js the root file and the issue is that somehow vue is not recognizing that this is a bootstrapVue component.

**Comment by jackmu95** [comment]
I've created a simple CodeSandbox using `<b-overlay>` and everything is working fine:
https://codesandbox.io/s/cranky-tesla-cusx3
