### ISSUE TITLE
[Problem] Tooltips over Modal

### ISSUE THREAD

**Issue by algoz098** [bootstrap-vue/bootstrap-vue#543]
When exist a tooltip, it will be selectable even if is HIDDEN or a Modal is over,

Making any clickable element not working.

**Comment by tmorehouse** [comment]
Would this be a similar issue to #435 ?

If so, this should be fixed in the release v0.17.0 which is coming out soon, as fixed by PR #450

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)
