### ISSUE TITLE
docs: No es accesible desde cuba 🇨🇺

### ISSUE THREAD

**Issue by Omarillo** [bootstrap-vue/bootstrap-vue#5433]
Desde hace unos meses dejo de ser accesible, con VPN funciona, puede q se trate de algo relacionado con el hosting, ahora ni el dev. Abre, antiguamente, con starling si abría, después q empezará a suceder esto, gracias

**Comment by tmorehouse** [comment]
Nuestro nuevo proveedor de alojamiento (Vercel) utiliza Amazon AWS, que parece no ser accesible en países sancionados por el gobierno de EE. UU. :disappointed:

**Comment by Omarillo** [comment]
tienen alguna otra via de acceso, boostrap-vue es mi framawork de cabecera para casi cualquier proyecto, se pudiese montar la documentacion de forma local????? clonando el proyecto de gitHub

**Comment by tmorehouse** [comment]
Puede clonar el repositorio y ejecutar el comando `yarn docs-dev`

Y configure su navegador en `http://localhost:3000/`

**Comment by Omarillo** [comment]
Ok, lo voy a intentar!!!!! Muchas gracias por su tiempo
