### ISSUE TITLE
Target attribute support in split mode with link of dropdown

### ISSUE THREAD

**Issue by unrefan** [bootstrap-vue/bootstrap-vue#5434]
Hi
Thanks for you work 
I wonder can i change default target `_self` at `target` attribute with link in split mode of dropdown? Did i miss something in documentation?

so i do like that now, which not so pretty.   
```
<b-dropdown
    split
    split-variant="outline-primary"
    variant="primary"
>
   <template #button-content>
      <a
         class="custom"
         href="<some_url>"
         target="_blank"
      >
          ....
      </a>
   </template>
  .....
</b-dropdown>
```

It would be great to do like so
```
<b-dropdown
    split
    split-variant="outline-primary"
    split-href="<some_url>"
    split-target="_blank"
    variant="primary"
>
   <template #button-content>
          ....
   </template>
  .....
</b-dropdown>
```

**Comment by jaymoh** [comment]
hi @unrefan just landed on this issue while trying to solve a similar issue, did you find a solution to this?

**Comment by unrefan** [comment]
> hi @unrefan just landed on this issue while trying to solve a similar issue, did you find a solution to this?

hi @jaymoh
you can use scoped slot `button-content` with raw `a` tag

**Comment by bruceCzK** [comment]
A similar effect can be achieved with the following code
```
<b-btn-group>
  <b-btn href="." target="_blank">Dropdown</b-btn>
  <b-dropdown menu-class="dropdown-toggle-split" right>
    <b-dropdown-item>A</b-dropdown-item>
    <b-dropdown-item>B</b-dropdown-item>
    <b-dropdown-item>C</b-dropdown-item>
  </b-dropdown>
</b-btn-group>
```
