### ISSUE TITLE
Updating class for date without redrawing calendar

### ISSUE THREAD

**Issue by johandalabacka** [bootstrap-vue/bootstrap-vue#5435]
I use the calendar widget and an admin user should be able to mark some dates as blocked so other users can't book on this date. The dates which are blocked have a grey or red background depending on them being blocked just this year or for any year. Which class for the background is returned by a function specified from date-info-fn attribute.

However if the admin adds another date isn't the class updated until the calender is redrawn. User is moving to another month and back. I have solved this by putting a key attribute on the calender which is updated and the calendar redrawn then user makes a date blocked/unblocked

However redrawing the calendar as a whole isn't very nice. For example is the keyboard controlls lost.

I would like to force just updating the classes for all dates. To call the function for date-info-fn again

**Comment by tmorehouse** [comment]
Use a computed prop to return a new method reference when your blocked dates change:

```html
<template>
  <b-calendar :date-info-fn="computedInfoFn" ... ></b-calendar>
</template>

<script>
export default {
  data() {
    blockedDates: []
  },
  computedInfoFn() {
    // We reference the data here, before returning the function reference
    // so that it will be reactive to changes in the array
    const blocked = this.blockedDates
    return function(ymd, date) {
       return blocked.indeOf(ymd) === -1 ? null :  'table-danger'
    }
  }
}
</script>
```

This will trigger the calendar to re-draw when the date-info-fn changes.

**Comment by johandalabacka** [comment]
Thanks alot
