### ISSUE TITLE
Datepicker required prop is not preventing submission

### ISSUE THREAD

**Issue by janswist** [bootstrap-vue/bootstrap-vue#5436]
### Steps to reproduce the bug

1. Put `required` on `b-form-datepicker` within a form
2. Leave calendar with no date selected
3. Click on a submit
4. Validation will pass

### Expected behavior

Validation shouldn't pass and should prevent submission.

### Versions

**Libraries:**

- BootstrapVue: 2.1.14
- Bootstrap: 4.4.1
- Vue: 2.#.#

**Environment:**

- Device: Mac
- OS: MacOS
- Browser: Chrome
- Version: latest

### Demo link

https://codesandbox.io/s/bootstrap-vue-sandbox-udr8q?file=/src/components/HelloWorld.vue

**Comment by Hiws** [comment]
> When set, adds the `aria-required="true"` attribute on the component. Required validation needs to be handled by your application

From the description of the `required` prop
https://bootstrap-vue.org/docs/components/form-datepicker#comp-ref-b-form-datepicker-props

**Comment by janswist** [comment]
I thought I missed something, because other form elements had validation built-in (idea for future release?). Thanks for clarifying.

**Comment by Hiws** [comment]
Other form components are mostly just a wrapper for native HTML inputs, and use their built-in validation.

There's a bit more going on with the datepicker component, which is why i guess it was left to the user to do the validation.
