### ISSUE TITLE
b-overlay over openned b-modal

### ISSUE THREAD

**Issue by Dual-Ice** [bootstrap-vue/bootstrap-vue#5437]
Hello.
Is it possible to cover all the app, when b-modal is openned, by b-overlay with [no-wrap fixed] props without setting a huge z-index value ?
Overlay used when any async request is happen and shown using interseptors for axios.
Something like this:  
```
 <template>
   <div
     id="app"
     class="app">
     <navigation @show-login-modal="$refs.loginModal.show()" />
     <login ref="loginModal" />
     <keep-alive
       include="Sessions">
       <router-view v-if="$auth.ready()" />
     </keep-alive>
     <b-overlay :show="loading" no-wrap fixed />
   </div>
 </template>
```
And some modal also has some async request, and I want to use global overlay when modal is openned. 
Can you help?

**Comment by Hiws** [comment]
You need to set the `z-index` prop to something higher than what the modal has.
If you want it to always be on-top when visible, you can set the `z-index` on the `b-overlay` to a high value like `9999`.

**Comment by Hiws** [comment]
Any reason why you don't want a set a high `z-index`?

**Comment by tmorehouse** [comment]
The z-index can be set via the `z-index` prop: https://bootstrap-vue.org/docs/components/overlay#overlay-z-index

**Comment by Dual-Ice** [comment]
If there is no other way, I’ll set a high z-index. I thought maybe I’m missing something or there are other ways.
