### ISSUE TITLE
<b-img-lazy> in horizontal scroll

### ISSUE THREAD

**Issue by amoralesdesign** [bootstrap-vue/bootstrap-vue#5438]
Currently when using <b-img-lazy> within a horizontal scroll or within a slider, for example: <slick-carousel>... all images are loaded immediately. There is no lazy load.
I tried to change the throttle values, but it only works when the scroll is vertical.

Can you do something with this?

**Comment by tmorehouse** [comment]
Which version of BootstrapVue are you using?

**Comment by tmorehouse** [comment]
BootstrapVue `2.0.0` and above (_not_ the `2.0.0-rc.##` releases) uses `IntersectionObserver` to determine when the image is visible, which handles horizontal scrolling.  `<b-img-lazy>` uses the [`v-b-visible`](https://bootstrap-vue.org/docs/directives/visible) directive internally to handle detecting visibility.

**Comment by tmorehouse** [comment]
This fiddle works for me.... https://jsfiddle.net/n874ped2/

If you inspect the images (with chrome devtools), before scrolling the horizontal scroller, you will see that the images out of view, within the default threshold) are all rendered with placeholders.

**Comment by amoralesdesign** [comment]
> This fiddle works for me.... https://jsfiddle.net/n874ped2/
> 
> If you inspect the images (with chrome devtools), before scrolling the horizontal scroller, you will see that the images out of view, within the default threshold) are all rendered with placeholders.

Sorry, apparently the lazy was not working because it was using the <picture> tag.
For that I created another issue here: https://github.com/bootstrap-vue/bootstrap-vue/issues/5442

Thank you
