### ISSUE TITLE
Treeshaking in minified ESM

### ISSUE THREAD

**Issue by naletups** [bootstrap-vue/bootstrap-vue#5439]
### Describe the bug

I want to reduce the resulting JS package size by using treeshaking. I created a minimum example (can send it if required) that only imports `BButton` from BSVue with ESM. However, I see a strange behavior when I switch from my dev bootstrap-vue.esm.js to the bootstrap-vue.esm.min.js: It goes up from 150KB to 630KB, even on webpack's `production` mode. I confirmed that importing `BootstrapVue` from bootstrap-vue.esm.min.js also results in 630KB size.

Is it expected that using a minified version includes again everything, preventing a successful treeshaking? If so, what is the purpose/advantage of bootstrap-vue.esm.min.js?

**Comment by tmorehouse** [comment]
The minified version of `bootstrap-vue.esm.min.js` has all the comments removed, so the `PURE` markings are not present (plus everything is mangled during JS minifcation)

You should use the `bootsttrap-vue.esm.js` module, which will tree shake (as JS minifiers will remove any dead code once imported).  You will get better tree shaking with the `/esm/index.js` module, as module loaders and minifiers will be better at unused module elimination and dead code elimination.

**Comment by tmorehouse** [comment]
We really should remove the minified version of `bootstrap-vue.esm.js`, as it removes the tree shaking ability.. but we have it there for legacy purposes.  Most users will be running minifiers on their own bundles when in production mode, which will also minify any imports.

**Comment by naletups** [comment]
Thanks for your quick reply, and especially for the hint on using `/esm/index.js` directly. 
I haven't yet realized that his is even WAY more effective, but as you stated it makes completely sense.

I was relying on VueUI's dashboard summary to judge on the effectiveness, but it seems there is something odd happening when using `/esm/index.js`: while the bundled bootstrapvue size goes down to only 76KB (of BButton only), the dashboard strangely reports a complete bundle size of 1.6MB, so I dropped this option early on.

**Comment by tmorehouse** [comment]
Most module bundlers will automatically use the `/esm` modular build (as we have that set in our `package.json`), but you can alias which file you want to use.  Just make sure you have JS minification enabled to reduce your production bundle size.  Module bundlers alone will only import the sub-modules needed, but it needs the JS minifier to remove un-used exports.

**Comment by naletups** [comment]
ok. thanks. can be closed.

**Comment by naletups** [comment]
Sorry, another follow-up. I could successfully load components and reduce the package size. However, I struggle to lazy-load components. There were two issues regarding that (one of which f.e. dealt with a function as a return value instead of a promise), but they were fixed according to logs. I could also not recreate them in the playground as BSV is loaded already.

Here is a simplified example (or more complicated, load only if a certain v-if guard is enabled after some user interaction):
```
<template>
  <b-container>
  </b-container>
</template>
<script>
import { BContainer } from 'bootstrap-vue/esm/components/layout/container';
export default {
  components: {
    // 'b-container': () => import('bootstrap-vue/esm/components/layout/container'), // DOES NOT WORK
    // 'b-container': BContainer, // WORKS
  }
}
</script>
```
and in a central location I am loading `@import 'node_modules/bootstrap/scss/bootstrap.scss';` and `@import 'node_modules/bootstrap-vue/src/index.scss';`

**Comment by tmorehouse** [comment]
Lazy loading needs to be handled in a particular way, by creating an intermediary import, as dynamic imports will pull in the fill library  (if importing from `bootstrap-vue`). Although the method you had above (importing from the `/esm` directory) should work, although not designed for dynamic imports (It is a true ES6 module, and dynamic imports are converted to `require(...)` by webpack, which assumes the module is in CJS &mdash; commonjs &mdash; format)

Create an intermediary module:

```js
// file: my-b-container.js
import { BContainer } from 'bootstrap-vue';
export default BContainer;
```
This will tree shake just the b-container component (and any modules it may require)

And then do this in your Vue component/page:

```html
<template>
  <b-container>
  </b-container>
</template>

<script>
export default {
  components: {
    BContainer: () => import('/path/to/my-b-container')
  }
}
</script>
```

The dynamic `import(...)` also assumes the default export is the component, but in BootstrapVue's case all components are _named_ exports (no default export)

So to make a named export work dynamically, you have to resolve the named export from the returned module:

```js
components: {
  BContainer: () => (await import('bootstrap-vue/esm/components/layout/container')).BContainer
}
```

You may also want to include the [`esm` package](https://www.npmjs.com/package/esm) in your dependencies to handle both CJS and ES6 export formats

**Comment by naletups** [comment]
So for the intermediary import, I got it to work. Thanks to your hint, I was able to prevent loading the entire library. However, in the intermediary file I am not including from `'bootstrap-vue'` but from `'bootstrap-vue/esm/components/layout/container'` directly.

Regarding the second hint: I was not able to add `.BContainer` at the end of the import in the components section. Once I do that, the entire component disappears, but no error is thrown?! I tested with the esm package and without.

**Comment by naletups** [comment]
So for the intermediary import, I got it to work. Thanks to your hint, I was able to prevent loading the entire library. ~~However, in the intermediary file I am not including from `'bootstrap-vue'` but from `'bootstrap-vue/esm/components/layout/container'` directly. My setup is not applying treeshaking if I include `'bootstrap-vue'` directly.~~ In production mode, it applied treeshaking nicely.

Regarding the second hint: I was not able to add `.BContainer` at the end of the import in the components section. Once I do that, the entire component disappears, but no error is thrown?! I tested with the esm package and without.

**Comment by tmorehouse** [comment]
> Regarding the second hint: I was able to use the import without `.BContainer` at the end:
`'b-container': (async () => await import('./library/my-container'))` but also with. Is there a difference?

In the case of the `my-container.js`, the component is the `default` export, where as `/esm/components/layout/container` the component is a named export  `BContainer` (not `default`)
