### ISSUE TITLE
bvModal both msgBoxOk and msgBoxConfirm are undefined

### ISSUE THREAD

**Issue by nongtiny** [bootstrap-vue/bootstrap-vue#5441]
### Describe the bug

In the .vue file, it can not use bvModal on both msgBoxOk and msgBoxConfirm.
Error message: "TypeError: Cannot read property 'then' of undefined".
The `$bvModal.msgBoxOk` is undefined.

Why it is undefined in vue single file component. But when I called from a router using, `router.app.$bvModal.msgBox` blablalba. It works normally. Please help. Thank you.

### Steps to reproduce the bug

1. Fetch data from API
2. Error catched
3. Use  `$bvModal.msgBoxOk` to display error mesage.
4. Error prompted: "TypeError: Cannot read property 'then' of undefined".

### Versions

**Libraries:**

- BootstrapVue: 2.1.5
- Bootstrap: 4.4.1
- Vue: 3.1.2

**Environment:**

- Device: Windows10
- OS: Windows10
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

**Comment by tmorehouse** [comment]
How are you installing BootstrapVue? are you using the full library, or just importing certain components or plugins?

**Comment by nongtiny** [comment]
Hello sir. I import everything in BootstrapVue the same as the document. At first, it was working, but I don't know why it's unexpectedly not working like before.

It works fine in `router.js`. But when I use Vue single file component. It didn't work.
I don't know that it might be affected by my other libraries or not, because it was working before.

Have you ever experienced something like this before?

Thank you.

**Comment by cata-libuy** [comment]
I'm experimenting the same issue. This code was working ok until last week, maybe some version update.

`     this.$bvModal.msgBoxConfirm(message, {
          title: 'Información',
          size: 'md',
          okVariant: 'success',
          cancelVariant: 'danger',
          okTitle: 'Aceptar',
          cancelTitle: 'Cancelar',
          centered: true,
          noCloseOnBackdrop: true,
        })
          .then(async (value) => {
            if (value === true) {
              this.show = false;
              await this.changeWarehouseState({ state: 'Reparado', orden: this.ot.ot, user: this.user.user.id });
              this.saveDiagnostic();
            }
          });`

Error:

```
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'then')
    at o.showMessageModal (ActionIngresarReparacion.vue:114:30)
    at click (ActionIngresarReparacion.vue?37db:5:104)
    at nt (vue.runtime.esm.js:1854:26)
    at HTMLButtonElement.n (vue.runtime.esm.js:2175:9)
    at Za.i._wrapper (vue.runtime.esm.js:6917:25)
```
