### ISSUE TITLE
v-b-toggle callbacks on showing/hiding content

### ISSUE THREAD

**Issue by dikkini** [bootstrap-vue/bootstrap-vue#5448]
### Is your feature request related to a problem? Please describe...

v-b-toggle collapse content and i want to execute some code when content hiding and when content is showing. i need callback. because showing/hiding content changes DOM - i want to resize/reposition content on my page

### Describe the solution you'd like

make v-b-toggle callback for showing/hiding content

### Additional context

May be it is possible, but i did not fund any clues in documentation,

**Comment by Hiws** [comment]
You can use the `show`, `shown`, `hide`, `hidden` events on `b-collapse`, to run some code when the state changes.

<https://bootstrap-vue.org/docs/components/collapse#comp-ref-b-collapse-events>

**Comment by dikkini** [comment]
@Hiws `shown` and `hidden` works, but how to use event `bv::toggle::collapse`? Just do `@bv::toggle::collapse="function"` - does not work.

**Comment by Hiws** [comment]
**bv::collapse::state**
> Emitted on $root when collapse has changed its state

So you need to listen for the event on `$root` and no the element.

**Comment by dikkini** [comment]
> **bv::collapse::state**
> 
> > Emitted on $root when collapse has changed its state
> 
> So you need to listen for the event on `$root` and no the element.

Can you please provide an example of using `bv::toggle::collapse` event?

Or can you advice some other way to listen and `shown` and `hidden`, because my code looks like this for now:
```html
                        <b-collapse id="info-body"
                                    @show="reposition_all_lines"
                                    @hide="reposition_all_lines"
                                    @hidden="reposition_all_lines"
                                    @shown="reposition_all_lines"
                                    visible>
```

**Comment by tmorehouse** [comment]
The element that has`v-b-toggle` directive will have the class `collasped`  or `no-collasped` applied to it based on the state of the target collaspe/sidebar.  You can use this class, in conjunction with custom CSS to hide or show content in the toggle element:

```css
.collasped .when-open { display: none; }
.not-collapsed .when-closed { display: none; }
```

`when-open` and `when-closed` would be your custom classes to use to hide content.

**Comment by dikkini** [comment]
i found how to use it. thx

**Comment by SauravSahPS** [comment]
@dikkini 
I know it is very long you added this issue , but if possible can you let me know how you made it work ?

**Comment by iziynaser** [comment]
<b-collapse id="searchCollapse" visible @hide="hideCollapse" @show="showCollapse">
///
      methods: {
            hideCollapse() {
                 //do sth
            },
            showCollapse() {
                 //do sth
            }
}
