### ISSUE TITLE
Nuxt tree missmatch

### ISSUE THREAD

**Issue by JFGHT** [bootstrap-vue/bootstrap-vue#5453]
### Describe the bug

Happening since 2.15.0.

```html
<b-card no-body class="text-center">
  <div class="bg-secondary text-light">
      This is some content without the default <samp>&lt;b-card-body&gt;</samp> section. Notice the
      lack of padding between the card's border and this gray <samp>&lt;div&gt;</samp>.
  </div>
</b-card>
```

Vue throws:

> [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

### Expected behavior

You can also see that the SSR content is empty but then hydrates later.

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.5.0
- Vue: 2.6.11
- Nuxt: 2.12.2

**Environment:**

- OS: Ubuntu
- Browser: Chrome
- Version: 83.0.4103.61

### Demo link

https://codesandbox.io/s/admiring-fast-tdx6c?file=/pages/index.vue

**Comment by Hiws** [comment]
I don't think the issue is the card that you posted, but the `<b-dropdown>` in your codesandbox.

If i comment out the `<b-dropdown>`, the error goes away.
Specifically the `text` prop on `<b-dropdown>`. 
Removing it removes the error, and adding it back makes the error appear again.

**Comment by JFGHT** [comment]
@Hiws I had to try something else in codesandbox because I could not reproduce the error I was having localy with the card only. I was able to trigger the bug with `<b-dropdown>`, so this probably leads to a major issue.

**Comment by nachogarcia** [comment]
I have had this issue as well with dropdowns in 2.15 but haven't been able to reproduce it in a sandbox outside my project. Mentioned it in https://github.com/bootstrap-vue/bootstrap-vue/issues/4834#issuecomment-633108264

**Comment by JFGHT** [comment]
@Hiws any confirmation on this?

**Comment by ashwinkshenoy** [comment]
I kinda fixed this issue:

**My code Before fix:**
```
<b-dropdown id="dropdown-1" class="header-menu__dropdown" text="Features">
    <b-dropdown-item to="/social-media-campaigns">Social Media</b-dropdown-item>
</b-dropdown>
```

**My code After fix:**
```
<b-dropdown id="dropdown-1" class="header-menu__dropdown">
    <template v-slot:button-content>
        Features
    </template>
   <b-dropdown-item to="/social-media-campaigns">Social Media</b-dropdown-item>
</b-dropdown>
```

Not sure why the `text` prop on `b-dropdown`, is creating the issue.

**Comment by Ornii** [comment]
I can confirm the same issue happening for me since bootstrap-vue@2.15.0. And I can also confirm the above fix works, thanks @ashwinkshenoy .
