### ISSUE TITLE
Bugging dropdown with active b-list-group-item

### ISSUE THREAD

**Issue by dikkini** [bootstrap-vue/bootstrap-vue#5457]
### Describe the bug

Dropdown menu flashes and goes to foreground when below `b-list-group-item` with `active` attribute.

### Steps to reproduce the bug

Create `b-list-group` with 2 elements`b-list-group-item`, inside first `b-list-group-item` create `b-dropdown` and second `b-list-group-item` add `active` attribute

### Versions

**Libraries:**

package.json:
- "bootstrap": "^4.5.0",
- "bootstrap-vue": "^2.15.0",
- "vue": "^2.6.11",

**Environment:**

- Device: macbook
- OS: macOS Catalina 10.15.4 (19E287)
- Browser: Google Chrome
- Version: Version 79.0.3945.130 (Official Build) (64-bit)

### Demo link

https://jsfiddle.net/dikkini/gycqn4hp/3/

**Comment by Hiws** [comment]
When adding the `button` prop to your `b-list-group-item`, it will render as a button.
While is fine, the issue comes when you place another `<button>` (`<b-dropdown>`) inside it, which is invalid HTML markup.

Remove the `button` prop and the flickering will go away.

**Comment by dikkini** [comment]
Hmmm. Problem appears only when i add `active` attribute to `b-list-group-item`. 
So dropdown menu renders without problems within `b-list-group-item` element with button attribute, but if add `active` attributes - it starts to flicker.

**Comment by Hiws** [comment]
Yes. That's because the `active` increases the `z-index` of the group-item, which causes the dropdown to bug out since it's placed inside a button.

If you *really* want to keep your current markup (though i don't advise it), you can add the following CSS to solve the issue
.
```css
.list-group-item.active {
    z-index: auto!important;
}
```

**Comment by Hiws** [comment]
Additionally regarding the markup.

Here's a snippet from the [W3 spec](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element) for `<button>`.
> Phrasing content, but there must be no **interactive content** descendant and no descendant with the tabindex attribute specified.

Interactive content includes:

- a
- audio (if the controls attribute is present)
- button
- embed
- iframe
- img (if the usemap attribute is present)
- input (if the type attribute is not in the hidden state)
- keygen
- label
- object (if the usemap attribute is present)
- select
- textarea
- video (if the controls attribute is present)
