### ISSUE TITLE
Is it possible to have global settings for boolean props?

### ISSUE THREAD

**Issue by usernamehw** [bootstrap-vue/bootstrap-vue#5459]
### Is your feature request related to a problem? Please describe...

For instance, Modal supports global settings:
```js
"BModal": {
    "titleTag": "h5",
    "size": "md",
    "headerBgVariant": null,
    "headerBorderVariant": null,
    "headerTextVariant": null,
    "headerCloseVariant": null,
    "bodyBgVariant": null,
    "bodyTextVariant": null,
    "footerBgVariant": null,
    "footerBorderVariant": null,
    "footerTextVariant": null,
    "cancelTitle": "Cancel",
    "cancelVariant": "secondary",
    "okTitle": "OK",
    "okVariant": "primary",
    "headerCloseContent": "&times;",
    "headerCloseLabel": "Close"
},
```

But values like `noFade` or `hideBackdrop` do not work

> BvConfig - Unknown config property "BModal.noFade"

### Describe the solution you'd like

Being able to set properties like that in global config.

### Describe alternatives you've considered

Creating an extra object for config and passing it for each modal `v-bind="modalProps"`. Easy to forget.

**Comment by Hiws** [comment]
https://github.com/bootstrap-vue/bootstrap-vue/issues/5291#issuecomment-622533976
>Currently we do not allow Boolean only props to be defaulted in the global config, as it changes the meaning/functionality of the no-* type props. If you use any third party components that expect the BootstrapVue component to work as if the no-* prop was not set, then it may break functionality of those 3rd party components (i.e. it would require the authors of those components to explicitly set :no-auto-hide="false".
