### ISSUE TITLE
Is it possible to size the time picker and give it a color?

### ISSUE THREAD

**Issue by L-HommeSage** [bootstrap-vue/bootstrap-vue#5460]
It would be nice if it was possible to give a color to the time component and also give it an other size like one smaller and one bigger.

**Comment by Hiws** [comment]
There's a few variant props you can use to change the color of certain parts of the component.

https://bootstrap-vue.org/docs/components/form-timepicker#comp-ref-b-form-timepicker-props
```
close-button-variant
reset-button-variant
now-button-variant
button-variant
```

There's also the `size` prop to change the size of the input field.
If you need customization outside of these, you will need to use custom CSS.
