### ISSUE TITLE
[B-Table] v-model in conjunction with sort-compare-options causes browser crash

### ISSUE THREAD

**Issue by dancarasco** [bootstrap-vue/bootstrap-vue#5461]
### Describe the bug

Using the '**sort-compare-options**' prop in conjunction with a **v-model** on B-Table causes chrome to crash/become unresponsive. The only way to exit the web page is to kill the tab process.

### Steps to reproduce the bug

1. Go to https://codepen.io/trickster223/pen/bGEbBYP
2. Add **v-model="model"** to the b-table component
3. Codepen output will become blank, browser page will lock up, table never gets rendered.

### Expected behavior

Table renders with sorting options applied and v-model available for a list of read-only data.

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- Device: Laptop
- OS: Ubuntu 20.04
- Browser: Chrome
- Version: 83.0.4103.61 (Official Build) (64-bit)

### Demo link

https://codepen.io/trickster223/pen/bGEbBYP

**Comment by IwalkAlone** [comment]
I've created a PR #5554 that could fix this issue, but it can be worked around by moving the value of sort-compare-options into `data` instead of writing it inline.
