### ISSUE TITLE
Infinite tables

### ISSUE THREAD

**Issue by ccleve** [bootstrap-vue/bootstrap-vue#5465]
### Is your feature request related to a problem? Please describe...

I have a very large table to display using b-table. The table stretches vertically to fill available space, which means that the number of visible rows varies. I could use an item provider function and a pagination control, but the whole thing is awkward if the number of rows being displayed does not match the number of rows in my table's perPage value. Sometimes there's a scroll bar and sometimes there aren't enough rows to fill the page. 

### Describe the solution you'd like

A better solution, from a UX perspective, is an infinite scrolling table. There would be a scroll bar on the side, and as you drag it or click it, the table would fetch rows from the server in the background. Perhaps you would tell the table in advance how many total rows there were, or perhaps as you scroll down the system would fetch more rows and the scroll bar thumb would shift up.

### Describe alternatives you've considered

The pagination control is very similar to a scrollbar except that it's horizontal. We could create a vertical pagination control that looked just like a scrollbar. The only trick would be to detect the number of rows displayed and adjust the perPage parameter to match, and then scroll incrementally as well as page-at-a-time.

**Comment by Hiws** [comment]
You could create something similar, without too much trouble.
https://codepen.io/Hiws/pen/bGEGLzy

The above example wait until the table is scrolled all the way down and display a loading indicator.
However, you can easily modify to better fit your description by adding an offset to the "is the table scrolled to the button" check, and simply remove the overlay if you don't want a visual indicator that the table is loading.
The example also hides the scrollbar when loading, this was just personal preference and can again freely be removed based on your needs.
