### ISSUE TITLE
Support v-show on b-tab element

### ISSUE THREAD

**Issue by trush44** [bootstrap-vue/bootstrap-vue#5477]
It's not possible to make a tab hidden while still loading the tab content. Request to support v-show on tabs (b-tab).

We have a tabbed form where some users should be able to see a tab whereas the tab should be hidden from others. Regardless of whether it can be seen though, we have JavaScript that accesses non-vue element data in that tab so the content must always be rendered.

**Comment by Hiws** [comment]
You can already do this by utilizing the `title-item-class` prop on `b-tab`. Where you can add the `d-none` class which will hide the tab button, but still render the content of the tab.

```html
<b-tabs>
	<b-tab title="Tab 1">
  	Tab 1
  </b-tab>
  <b-tab title="Tab 2" title-item-class="d-none">
  	Tab 2
  </b-tab>
  <b-tab title="Tab 3">
  	Tab 3
  </b-tab>
</b-tabs>
```

**Comment by trush44** [comment]
@Hiws, thank you for this!

As for your note, can you expand on that a bit please and the best way to hide/show the tab based on logic? I was thinking of doing :title-item-class="someMethod" then have someMethod() return either d-none or empty string. Is this what you would recommend?

**Comment by trush44** [comment]
> 
> 
> You can already do this by utilizing the `title-item-class` prop on `b-tab`. Where you can add the `d-none` class which will hide the tab button, but still render the content of the tab.
> 
> ```
> <b-tabs>
>   <b-tab title="Tab 1">
>     Tab 1
>   </b-tab>
>   <b-tab title="Tab 2" title-item-class="d-none">
>     Tab 2
>   </b-tab>
>   <b-tab title="Tab 3">
>     Tab 3
>   </b-tab>
> </b-tabs>
> ```
> 
> Quick note.
> This will only hide the tab, and it can still he shown by changing the `v-model` of `b-tabs`, so there can be scenarios where a hidden tab's content will be shown based on the implementation.

@Hiws, thank you for this!

As for your note, can you expand on that a bit please and the best way to hide/show the tab based on logic? I was thinking of doing :title-item-class="someMethod" then have someMethod() return either d-none or empty string. Is this what you would recommend?

**Comment by Hiws** [comment]
A method would be fine.

What i mean with the note is, is that internally, `b-tabs` doesn't know the tab content shouldn't be shown.

So if you hide the first tab and do nothing else, it will show the first tab's content, but the tab button will be hidden.

If you paste the below code onto the [playground](https://bootstrap-vue.org/play), you should see what i mean.
So you might need some extra stuff to swap away from those tabs if they showhow get shown. These scenarios could be the first tab being shown like below, or tabs being dynamically added/removed. Possibly a few more.
```
<b-tabs>
  <b-tab title="Tab 1" title-item-class="d-none">
    Tab 1
  </b-tab>
  <b-tab title="Tab 2">
    Tab 2
  </b-tab>
  <b-tab title="Tab 3">
    Tab 3
  </b-tab>
</b-tabs>
```

**Comment by trush44** [comment]
> 
> 
> A method would be fine.
> 
> What i mean with the note is, is that internally, `b-tabs` doesn't know the tab content shouldn't be shown.
> 
> So if you hide the first tab and do nothing else, it will show the first tab's content, but the tab button will be hidden.
> 
> If you paste the below code onto the [playground](https://bootstrap-vue.org/play), you should see what i mean.
> So you might need some extra stuff to swap away from those tabs if they showhow get shown. These scenarios could be the first tab being shown like below, or tabs being dynamically added/removed. Possibly a few more.
> 
> ```
> <b-tabs>
>   <b-tab title="Tab 1" title-item-class="d-none">
>     Tab 1
>   </b-tab>
>   <b-tab title="Tab 2">
>     Tab 2
>   </b-tab>
>   <b-tab title="Tab 3">
>     Tab 3
>   </b-tab>
> </b-tabs>
> ```

Thanks! Following is what I ended up doing and it works great...

``` 
<b-tab title="Debug" :title-item-class="debugMode">
</b-tab>
```
```
computed: {
            // show/hide the tab dependent on DEBUG_MODE variable
            debugMode: function () {
                return DEBUG_MODE ? '' : 'd-none';
            }
        }
```
