### ISSUE TITLE
B-Card with no-body undefined

### ISSUE THREAD

**Issue by syboltbakker** [bootstrap-vue/bootstrap-vue#5479]
`<b-card no-body class="m-2 shadow-sm">
                    <b-card-header>HEADER</b-card-header>
                    <b-card-body>
                        CONTENT
                    </b-card-body>
                </b-card>`

Renders "undefined", when I leave out the "no-body" property it works fine.

**Comment by Hiws** [comment]
I'm unable to reproduce the issue on the [playground](https://bootstrap-vue.org/play).

Could you create a reproduction of the issue?
