### ISSUE TITLE
 No examples of toast events

### ISSUE THREAD

**Issue by vciloglu** [bootstrap-vue/bootstrap-vue#5480]
```
this.$bvToast.toast("Example Text", {
          toaster: "b-toaster-top-center",
          title: `Example title`,
          variant: "success",
          solid: true,
          autoHideDelay: 3000,
          hide:() => alert('hide'),
          hidden:()=>alert('hide')
        });
```

in this code example; I want to run an event when the message is closed and it closes automatically. I couldn't find an example of this

**Comment by Hiws** [comment]
I don't believe events are available for toasts on demand (`this.$bvToast`).

You can access events if you use the `b-toast` component.

**Comment by tiagoroldao** [comment]
For toasts on demand, you can use the global events, and use ids (don't forget to remove listener when/if needed):
```javascript
toastsHolder.$root.$on('bv::toast:hidden', (event: any) => {
      // event.componentId is accessible here, can be used to check which toast was hidden
});
```

**Comment by vciloglu** [comment]
thanks.

**Comment by m2bit** [comment]
Within event mounted put: 

this.$root.$on('bv::toast::hidden', (event) => {
      // event.componentId is accessible here, can be used to check which toast was hidden
});
