### ISSUE TITLE
how can i use v-b-popover.hover.html="'I am popover <b> directive</b> content!'" in table row

### ISSUE THREAD

**Issue by MuhammadAliEcho** [bootstrap-vue/bootstrap-vue#5481]
### here a code example
	<b-table
	show-empty
	small
	stacked="sm"
	responsive="sm"
	:items="Items.data"
	:fields="fields"
	:no-local-sorting="true"
	:sort-by.sync="form.sortBy"
	:sort-desc.sync="form.sortDesc"
	:tbody-tr-attr="(row, type)=>{ return {'v-b-pophover.hover': 'data'} }"
	>

	<template v-slot:cell(image)="row">
	<img v-if="row.item.image" class="img-rounded" style="width: 35px; height: 25px;" :src="URL+'storage/images/'+row.item.image" />
	<i v-else class="far fa-image fa-2x"></i>
	</template>

	<template v-slot:cell(qty)="row">
	{{ row.value+' '+row.item.unit.short_name }}
	</template>

	<template v-slot:cell(weighted_bp_avg)="row">
	{{ row.value | formatMoney }}
	</template>

	<template v-slot:cell(min_sp)="row">
	{{ row.value | formatMoney }}
	</template>

	<template v-slot:cell(created_at)="row">
	{{ row.value | moment('YYYY-M-D') }}
	</template>

	<template v-slot:cell(actions)="row">
	<router-link tag="button" :to="{ name: 'item.edit', params: {id: row.item.id} }" v-b-tooltip.hover title="Edit" class="btn btn-primary btn-xs elevation-2"><i class="fa fa-edit"></i></router-link>
	<b-button tag="button" @click="Delete({url: 'item/'+row.id+'/delete', id: row.item.id}).then(()=>GetItems())" v-b-tooltip.hover title="Delete" class="btn btn-danger btn-xs elevation-2"><i class="fa fa-trash"></i></b-button>
	</template>

	</b-table>

**Comment by Hiws** [comment]
You can't use directive like that, it needs to be directly applied to an element.

You can instead use `b-tooltip` and the `@row-hovered` event to dynamically add tooltips to your rows.

Example:
https://codepen.io/Hiws/pen/rNxWEwp

The other alternative is to use `<b-table-simple>` and apply the directive directly to `b-row`.
