### ISSUE TITLE
Multiple form input in modal cause enter key not working

### ISSUE THREAD

**Issue by asabaki** [bootstrap-vue/bootstrap-vue#5483]
### Describe the bug

Form cannot be submitted via Enter key in Modal if having multiple form inputs. (with single form input is working)

### Steps to reproduce the bug

1) Open modal
2) Enter text in any input, and press enter (submit via Enter key not OK button)
Result: Form is not submitted, Modal is not closed (not trigger OK event)

### Expected behavior

Form is submitted with modal trigger OK event

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.15.0
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Microsoft Edge, Chromium
- Version: 83.0.478.45 

### Demo link

Demo link [CodePen](https://codepen.io/asibaka/pen/XWXmrPv)

**Comment by Hiws** [comment]
This isn't a specific issue with either the modal or Bootstrap-Vue.

If a form has more than one input field, it requires a submit button to be submitted via a `enter` press. It is like this with native controls too.

Simply add a `<b-btn type="submit">` to your form to allow users to submit it with an `enter` press. If you don't want it shown you can hide it with the class `d-none`.
