### ISSUE TITLE
Support transition duration on b-collapse

### ISSUE THREAD

**Issue by lexicalunit** [bootstrap-vue/bootstrap-vue#5485]
### Is your feature request related to a problem? Please describe...

Currently the `b-collapse` component eats any props a user passes to it: https://github.com/bootstrap-vue/bootstrap-vue/blob/102aefe90b0931aa93da5eaa9ac19349929eafc2/src/components/collapse/collapse.js#L242

Whereas the `bv-collapse` utility component seems to pass them along nicely: https://github.com/bootstrap-vue/bootstrap-vue/blob/cfc85affff83511c8f8cf4e071dd507eabebc226/src/utils/bv-collapse.js#L74

This means that some of the functionality of Vue's `transition` element isn't available to users of `b-collapse`. For example, there's no way to change the `duration` property, which is new in versions 2.2.0+ of Vue: https://vuejs.org/v2/guide/transitions.html#Explicit-Transition-Durations

### Describe the solution you'd like

Allow properties to flow from `b-collapse` through `bv-collapse` and ultimately to `transition`. Or at the very least add support for the `duration` property alone.

**Comment by abdulaziz-mohammed** [comment]
+1
