### ISSUE TITLE
 In b-modal can't the *-class attribute introduce custom classes?

### ISSUE THREAD

**Issue by miao-liu** [bootstrap-vue/bootstrap-vue#5486]
### example:
`   <b-modal id="modal-1" 
              title="登录" 
              title-class='col-10 text-center' 
              hide-footer="true" 
              modal-class='lm_bg'>
          //todo...
     </b-modal>`
Custom class(I'm going to write my custom class under app.vue):
` .lm_bg{background-color:#6AC4DF !important;}`
Custom classes don't work.
Can only bring in classes in bootstrap or did I have a problem with what I wrote?

**Comment by Hiws** [comment]
`b-modal` doesn't know what is "bootstrap" classes, and what is not.
It's all just CSS.

Meaning there's something wrong with the CSS you wrote.
My guess would be you've written your CSS inside a scoped style tag (`<style scoped>`), which can require you to use a [deep selector](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) to target subcomponents correctly.

**Comment by miao-liu** [comment]
> `b-modal` doesn't know what is "bootstrap" classes, and what is not.
> It's all just CSS.
> 
> Meaning there's something wrong with the CSS you wrote.
> My guess would be you've written your CSS inside a scoped style tag (`<style scoped>`), which can require you to use a [deep selector](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) to target subcomponents correctly.

Thanks.I tried writing my own CSS file and introducing it into main.js.The style has been added
