### ISSUE TITLE
Td tags for tables with colspan

### ISSUE THREAD

**Issue by zsemenyuk** [bootstrap-vue/bootstrap-vue#5491]
### Is your feature request related to a problem? Please describe...

I tried to add `colspan 2` in `thAttr` in field's object for `b-table` (not `b-simple-table`). I want to make smth like this one [example](https://www.w3schools.com/tags/att_th_colspan.asp)

But I did't find how to add an additional `td` tag, so my table looks weird. 

### Describe the solution you'd like
I'd like to get smth like [example](https://www.w3schools.com/tags/att_th_colspan.asp)
the solution may be to add an additional option like
```
fields: [
  {
    key: 'name',
    thAttr: {
      colspan: 2
    },
    numberOfTds: 2 // or render the number of td actual for colspan
  }
]
```

**Comment by Hiws** [comment]
`<b-table>` will always render a `th` + `td` for each field provided. If you want one `th` to have a `colspan`, you will need to hide one (or more) of the other headers. You can do this by adding `thClass: "d-none"`, to the field header you no longer want displayed, but want to keep the `td`.

https://codepen.io/Hiws/pen/wvMGwmg
