### ISSUE TITLE
tdClass function does not receive the value of the formatter function in the table

### ISSUE THREAD

**Issue by frbuceta** [bootstrap-vue/bootstrap-vue#5492]
### Describe the bug

I have a formatting function defined in a table column but when I create the tdClass function it does not receive that value, if not the original one

### Steps to reproduce the bug

```js
// Virtual Column
{
  key: 'diff',
  label: 'Diff',
  class: 'text-right',
  formatter: (_, __, item) => {
    if (!item.duration || !item.estimatedDuration) return

    const operation = item.duration - item.estimatedDuration
    const decimals = 4

    // Round Decimals
    return (
      Math.round(operation * Math.pow(10, decimals)) /
      Math.pow(10, decimals)
    )
  },
  tdClass: (value) => {
    if (Math.sign(value) === 1 && value >= 1) return 'table-danger'
    if (Math.sign(value) === 1 && value < 1) return 'table-warning'

    return 'table-success'
  },
},
```

### Expected behavior

In my opinion, the tdClass function should return the value of the formatter function and not force me to write the contents of the formatter function again

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.5.0
- Nuxt: 2.12.2

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome
- Version: 83.0.4103.97

### Demo link

Not applicable

### Additional context

Add any other context about the bug here.

**Comment by frbuceta** [comment]
I suppose the rest of the function attributes also behave the same way as tdClass

**Comment by Hiws** [comment]
You could just move your formatter to `methods`.
This will allow you to use it as your formatter, and use it inside `tdClass` without having to write the function twice.

https://codepen.io/Hiws/pen/ExPKyjz

**Comment by frbuceta** [comment]
> You could move your formatter to `methods`.
> This will allow you to use it as your formatter, and use it inside `tdClass` without having to write the function twice.
> 
> https://codepen.io/Hiws/pen/ExPKyjz

It works, even there I will leave this open. Thank you
