### ISSUE TITLE
Supporting different calendar systems in datepicker [ hijri ]

### ISSUE THREAD

**Issue by 639dev** [bootstrap-vue/bootstrap-vue#5496]
### Is your feature request related to a problem? Please describe...

A clear and concise description of what the problem is.
-- Yes. I'm working on a big Vue application and need both Gregorian and Hijri Calendar Systems
### Describe the solution you'd like

-- adding a button to toggle between the different calendars systems

**Comment by m-demydiuk** [comment]
Hello. Are there any plans to support hijri? Our system works with multiple countries including Saudi Arabia, in which hijri is main calendar system.
