### ISSUE TITLE
Creates duplicate id when b-form-input type is password

### ISSUE THREAD

**Issue by arifmahmudrana** [bootstrap-vue/bootstrap-vue#5497]
When I add this in my template

```
 <b-form-input
        id="input-8"
        v-model="form.user.password"
        required
        :placeholder="$t('Please enter a password to login into your account later on')"
        type="password"
      ></b-form-input>
```
I get this error ```Found 2 elements with non-unique id``` but when I change type to **`text`** the warnings are gone.

I am using
Node => v12.9.1
Yarn => 1.22.4
bootstrap-vue => 2.8.0

**Comment by arifmahmudrana** [comment]
In fact as it creates duplicate IDs components that are used using IDs breaks e.g Toast it shows multiple times.

**Comment by jackmu95** [comment]
@arifmahmudrana Can you please try to replicate this issue in a CodeSandbox, CodePen or JSFiddle?

**Comment by arifmahmudrana** [comment]
@jackmu95 I tried https://codesandbox.io/s/sad-bush-6tn4j but can't reproduce however I see duplicate elements in my elements panel 
![image](https://user-images.githubusercontent.com/2046796/84566326-02adda80-ad92-11ea-89d8-285d7f354942.png)

**Comment by jackmu95** [comment]
@arifmahmudrana That must be related to your application logic and not the input itself.

**Comment by arifmahmudrana** [comment]
@jackmu95 it was a problem in my application logic I was rendering `router-view` conditionally with `v-show` directive & as a result the template was injected with display none now as I used `v-if` now it 's working as intended. It was a bad mistake from my side & waste of time for you sorry & thanks.
