### ISSUE TITLE
Navbar Sticky prop is not working.

### ISSUE THREAD

**Issue by viclotana** [bootstrap-vue/bootstrap-vue#5506]
<img width="864" alt="Screen Shot 2020-06-16 at 6 42 28 PM" src="https://user-images.githubusercontent.com/12007436/84814582-37739900-b001-11ea-9439-60b58dbcb6b8.png">
### Steps to reproduce the bug

1. Go to [https://bootstrap-vue.org/docs/components/navbar#placement]
2. Click on [...]
3. Scroll down to [...]

### Expected behavior

I expected the navbar to become sticky to the top after adding the prop

### Versions

**Libraries:**

- BootstrapVue: 2.1.5
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: [Mac]
- OS: [e.g. macOS High Sierra]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
Looks like you might've written `<b-navbar sticky="true">` and not `<b-navbar :sticky="true">`. (notice the colon). 

You also don't have to write `=true` at all for boolean props. Simply adding it is enough `<b-navbar sticky>`.

**Comment by viclotana** [comment]
Oh thanks.
I just changed it, and the Navbar is still not sticky

**Comment by Hiws** [comment]
Could you create a reproduction of the issue?
You can export a template to codepen on the docs [playground](https://bootstrap-vue.org/play/)
