### ISSUE TITLE
Icon not found

### ISSUE THREAD

**Issue by quaresmateo** [bootstrap-vue/bootstrap-vue#5515]
### Describe the bug
Eslint says `BIconCalendarCheck` icon does not exist in Bootstrap-Vue.
I'm importing the icons as a component in a NuxtJs project.

### Steps to reproduce the bug

1. Try import icon as component:
```javascript
import { BIconCalendarCheck } from 'bootstrap-vue'
```
2. Eslint shows message saying that  icon does not exist in the Bootstrap-Vue folder (in node_modules)
The message:
```
BIconCalendarCheck not found in 'bootstrap-vue' eslint (import/named)
```
### Expected behavior

Import icon, just like the others.

### Versions

**Libraries:**

- BootstrapVue: 2.11.0
- Bootstrap: 4.1.3
- Nuxt: 2.0.0

**Environment:**

- Device: Notebook HP
- OS: Manjaro KDE Plasma 5.18.5
- Browser: Chrome
- Version: 83.0.4103.61 64 bits

**Comment by Hiws** [comment]
<https://bootstrap-vue.org/docs/icons>
> Icon components were added in BootstrapVue release v2.2.0.
Bootstrap Icons v1.0.0-alpha3 icons were added in BootstrapVue release v2.8.0.
Bootstrap Icons v1.0.0-alpha4 icons were added in BootstrapVue release v2.15.0.

So if it can't find the icon, it probably isn't available in your current version, and you need to upgrade.

**Comment by quaresmateo** [comment]
Thanks! Just update it.
