### ISSUE TITLE
Progress bar text not showing correctly

### ISSUE THREAD

**Issue by jsbroks** [bootstrap-vue/bootstrap-vue#5516]
### Describe the bug

Progressbar text is not going to a new line. This screenshot is from the docs.
![image](https://user-images.githubusercontent.com/24920936/85206407-fffe3880-b2ef-11ea-8474-059d4757a2db.png)

### Steps to reproduce the bug

1. Create a progress bar with multiple lines of text

### Expected behavior

All text should be visible

### Versions

**Libraries:**

- BootstrapVue: 2.15.0

**Environment:**

- Device: Desktop
- OS: Ubuntu 20.04
- Browser: Chrome

**Comment by Hiws** [comment]
This looks to be an issue a change made in bootstrap `v4.5.0` that added `line-height: 0` to the `progress` class.

To fix it you can add the following CSS, to get it back to pre `4.5.0` styling.
```css
.progress {
  line-height: inherit;
}
```

**Comment by Hiws** [comment]
PR that introduced the change: https://github.com/twbs/bootstrap/pull/29413

So if IE11 support is something your app needs, you might want to check what the workaround above does, to make sure it doesn't cause any issues.

**Comment by jsbroks** [comment]
Thanks! How would I remove the line break in the first place?

**Comment by Hiws** [comment]
> Thanks! How would I remove the line break in the first place?

You want it to say "Progress: 50/100" on one line instead of two?
