### ISSUE TITLE
BootstrapVue pre-compressed with Brotli:11 on open source CDN

### ISSUE THREAD

**Issue by praisedpk** [bootstrap-vue/bootstrap-vue#5517]
### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs#browser

### Additional context or description

I have added BootstrapVue on PageCDN, pre-compressed it with brotli:11 to reduce file size, and enabled immutable caching for extreme results. The files are available on CDN here: https://pagecdn.com/lib/bootstrap-vue

With Brotli:11 pre-compression, file size gets much smaller compared to normal. Here is a comparison:

                                    PageCDN        Current        Saving
                                  --------------------------------------------
    bootstrap.min.css              17.71 KB       21.48 KB       3.77 KB
    bootstrap-vue.min.css           7.88 KB        8.82 KB       0.94 KB
    vue.min.js                     30.63 KB       33.17 KB       2.54 KB
    bootstrap-vue.min.js           82.80 KB       93.08 KB      10.28 KB
    bootstrap-vue-icons.min.js     50.72 KB       60.06 KB       9.34 KB
                                  --------------------------------------------
                        Total     189.74 KB      216.61 KB      26.87 KB

Adding these CDN links for [BootstrapVue](https://pagecdn.com/lib/bootstrap-vue), [Bootstrap](https://pagecdn.com/lib/bootstrap) and [Vue](https://pagecdn.com/lib/vue) on 'Getting Started' docs page may be helpful for some users looking to reduce JavaScript size.

If you allow, I can proceed with a pull request to add a small note for library users.

Thanks.

**Comment by jackmu95** [comment]
@praisedpk We could add a section on how to use BootstrapVue via CDN to the "Getting started" page. When we will do that we will definitely mention PageCDN!
