### ISSUE TITLE
Contradictory note

### ISSUE THREAD

**Issue by alexsonnay** [bootstrap-vue/bootstrap-vue#5518]
### Documentation issue

https://bootstrap-vue.org/docs/components/form-input

`Note: When using a non-text-like input (i.e. color, range, date, number, email etc), ensure that your formatter function returns the value in the expected format for the input type. The formatter must return the value as a string.`

This part of the documentation says one thing and then the opposite.

**Comment by Hiws** [comment]
The way i interpret the message, is that the formatter needs to return the expected format *as* a string.

Type `number` return the string '2.5' where as the string 'abc.123' would be invalid.
Type `email` returns the string 'user@example.com'
Type `color` returns the string `#ffffff`

... And so on.

**Comment by jackmu95** [comment]
Maybe we could adjust the note a bit to make it more clear. But @Hiws interpretation is correct.
