### ISSUE TITLE
BTab and BTabs nav-link classes

### ISSUE THREAD

**Issue by naletups** [bootstrap-vue/bootstrap-vue#5519]
I would like to get access to nav-item in `b-tabs` to style them properly. Currently I can only access the `active-nav-item-class`. In `b-card` the `link-classes` prop allows to be to style the rendered `nav-link`s.

### Describe the solution you'd like
`nav-item-class` prop to style the `nav-link` element

**Comment by Hiws** [comment]
If you want to apply a class to the generated `.nav-link` element, you can use the `title-link-class` prop on the `b-tab`.

**Comment by naletups** [comment]
Ah! It somehow slipped by attention when going over the props of `b-tab`
