### ISSUE TITLE
How to use head-variant in table?

### ISSUE THREAD

**Issue by PierBover** [bootstrap-vue/bootstrap-vue#552]
I've tried all sort of values but nothing changes.

For example:
```
head-variant="inverse"
head-variant="thead-inverse"
```

**Comment by tmorehouse** [comment]
The `head-variant` prop` has a bug in the current v0.16.1 release.  It has been fixed in the master, and will be available in release v0.17.0 which should be available this week.

**Comment by PierBover** [comment]
Awesome thanks for the fast reply!
