### ISSUE TITLE
b-form-tags: async format method

### ISSUE THREAD

**Issue by mysuf** [bootstrap-vue/bootstrap-vue#5522]
### Is your feature request related to a problem? Please describe...

I'm missing (or cant find) method that could possibly format tag string on addTag(). Let's say that I store large set of existing categories and I want to use their names as tag. I would like to request db and make a lookup for given tag. Some examples:
1) User enters "apple", I request db and find out that there is already such tag, but capitalized so returned new formatted value would be "Apple".
2) There are tags that could be error prone for input (f.e. company names) so user enters some unique id instead and format method will get related appropriate tag name.

Btw there is also missing property to limit number of tags.

### Describe the solution you'd like

I believe it has straighforward solution. Just to add awaited format method into addTag method before parsing and expose it like property. By default it could be null or return tag string as is.

Atm I am using custom locally monkey patched module containing [these changes](https://github.com/bootstrap-vue/bootstrap-vue/compare/dev...mysuf:feat-form-tags-format-limit) (note: it is not PR, there are missing tests and so on)

### Describe alternatives you've considered

I thought about datalist, but it is really bad idea for very large data sets.

**Comment by Hiws** [comment]
Just thought I'd throw a workaround out there.
Which is to write your own `addTag` function that calls your API before adding it to the tags array.

However, doing that means you might have to add in some of the validation that the native `addTag` does, depending on your setup.

A quick example without any local validation:
https://codepen.io/Hiws/pen/dyGzoKo
