### ISSUE TITLE
Conditional-element custom directive

### ISSUE THREAD

**Issue by naletups** [bootstrap-vue/bootstrap-vue#5530]
### Is your feature request related to a problem? Please describe...
Sometimes it is helpful to conditionally render one component in an entire tree of components, e.g. if the viewport allows for it. I know that there is the possibility with `v-if` to check for size and switch the entire DOM subtree from this node onwards to a "better suited" one. However, sometimes, a lot of code is duplicated this way. This also increases the page size.

One typical example: `b-button-group`, filled with 6 buttons in a table row, which renders nicely until MD breakpoint. Then there is simply no space left, causing an overflow of that column or very strange wrapping or empty vertical space. Vertically rendering the button group is "ugly", switching to a completely different layout breaks the workflow. Direct idea would be to wrap the buttons into a dropdown (or even have no `b-button` but  a `component` child whose type is also changed to switch from `b-button` to `b-dropdown-item`, but keeping all the other attributes and classes). This dropdown however, should only be rendered if a condition is fulfilled. If not, all the sub elements are moved "out" as if you comment the dropdown element in the source code.

Using [this idea](https://stackoverflow.com/questions/43293401/conditionally-rendering-parent-element-keep-inner-html) works fine for all those BSV elements whose children are directly attached to the node where you put your custom directive. However, dropdown for example has another node in between, complicating things a lot.

### Describe the solution you'd like
It would be helpful to have a special marker-class or attribute to search for when going with aforementioned approach. Or even better, a better integrated custom directive.

**Comment by Hiws** [comment]
Wouldn't this code (which seems to be similar to your alternative method) work for the b-btn-group/b-dropdown example you're talking about.

```html
<component :is="isDropdown ? 'b-dd' : 'b-btn-group'" text="Items">
  <component :is="isDropdown ? 'b-dd-item' : 'b-btn'">Item 1</component>
  <component :is="isDropdown ? 'b-dd-item' : 'b-btn'">Item 2</component>
  <component :is="isDropdown ? 'b-dd-item' : 'b-btn'">Item 3</component>
  <component :is="isDropdown ? 'b-dd-item' : 'b-btn'">Item 4</component>
  <component :is="isDropdown ? 'b-dd-item' : 'b-btn'">Item 5</component>
  <component :is="isDropdown ? 'b-dd-item' : 'b-btn'">Item 6</component>
</component>
```

Personally I'm also not sure where this directive fits in the scope of Bootstrap-Vue.
Seems like something that should belong in a different package, or something the developer should implement himself.

**Comment by naletups** [comment]
I solved it for the moment in a similar fashion. This works as you can exchange one component for another. If you want to just strip out one component this approach does not work.

I put this approach already into an own directive in my code. The reason for raising this topic here at BSV was because it is tricky to fetch the children because of potential intermediary components. Hence, the question for a "marker-class" or attribute for the DOM element into whose "vue slot" the child components are actually rendered. That would allow for a central custom directive.

But I guess, at the moment there are more important bugs around :-)

**Comment by sokulski** [comment]
@naletups Can you elaborate on what you're using to trigger the change in components? I'm a similar situation where different form controls make sense at different breakpoints. But what creates the boolean for, as @Hiws put it the `isDropdown` boolean?

**Comment by naletups** [comment]
I have added in a central component (for me the base App.vue) a listener that updates a VueX value since I need this value in multiple components:
```js
  mounted() {
    window.addEventListener('resize', () => {
      this.$store.commit('setWindowWidth', window.innerWidth);
    });
  },
```

In the VueX store, I added a convenience-getter:
```js
    state: {
      iface: {
        width: window.innerWidth,
      },
    },
    getters: {
      isXs: state => { return state.iface.width < 576; },
    },
```

In the actual component, I am monitoring this getter in a computed prop (like the `isDropdown` by Hiws). If you need to react to a certain element width, then you need to apply the width check to that particular element, but for me it was sufficient to make it relative to overall `window.innerWidth`.

Another easier solutions would be to have it in a single component if you only need it once or twice. Or you could probably also use CSS media queries.
