### ISSUE TITLE
<b-form-datepicker> and </b-modal> CSS not applying correctly after deploying to the server

### ISSUE THREAD

**Issue by gevinduM** [bootstrap-vue/bootstrap-vue#5532]
I am using datepicker and modal in my project and everything looks goods in my local development environment. But once I deployed to the server they are having some CSS issues. 

**Libraries:**

- "bootstrap-vue": "^2.15.0",
- Bootstrap v4.5.0
- "vue": "^2.6.10",

![image](https://user-images.githubusercontent.com/32522094/85755617-1b948500-b6dc-11ea-9e8a-73beb990013b.png)
![image](https://user-images.githubusercontent.com/32522094/85755762-3830bd00-b6dc-11ea-8673-0c1dcfbdf74e.png)

I applied the suggestions from https://github.com/bootstrap-vue/bootstrap-vue/issues/3540 and https://github.com/bootstrap-vue/bootstrap-vue/issues/5210. But its not working for me, Please not these issues exist only when deployed to the production server.

**Comment by Hiws** [comment]
Looks like `Bootstrap-Vue` CSS isn't being bundled correctly in your app.
Are you running any CSS minifier like CSS-Purge for production?
