### ISSUE TITLE
Plugin doesn't import all sub-components

### ISSUE THREAD

**Issue by sebastian-raubach** [bootstrap-vue/bootstrap-vue#5536]
### Describe the bug

According to the documentation on [plugins](https://bootstrap-vue.org/docs#component-groups-and-directives-as-vue-plugins), importing a plugin should import all sub-components as well.

>When importing as plugins, all subcomponents and related directives are imported in most cases. i.e. When importing &lt;b-nav&gt;, all the &lt;nav-*&gt; sub components are also included, as well all dropdown sub components.

I've added the following import:

```
import { FormPlugin } from 'bootstrap-vue'
Vue.use(FormPlugin)
```
However, when using form components like `b-form-input` or `b-form-checkbox`, I get error messages:

> Unknown custom element: &lt;b-form-input&gt; - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Did I misinterpret the documentation? Or does it simply not apply to `b-form` and I have to import every single form component I want to use individually?

### Steps to reproduce the bug

1. Use the above mentioned import
2. Add a `<b-form-input>` to the page
3. Check error console

### Expected behavior

The form sub-components should be imported automatically.

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 83.0.4103.116

**Comment by Hiws** [comment]
As mentioned here: https://bootstrap-vue.org/docs/components/form#importing-as-a-plugin
>This plugin includes all of the above listed individual components. Plugins also include any component aliases.

This means it will import `<b-form>`, `<b-form-text>`, `<b-form-invalid-feedback>`, `<b-form-valid-feedback>` and `<b-form-datalist>`.

So if you want to import `<b-form-input>`, you will need to import `BFormInput` or `FormInputPlugin`.
And for `<b-form-checkbox>`, you will need to import `BFormCheckbox` or `FormCheckboxPlugin` (which includes `<b-form-checkbox>` and `<b-form-checkbox-group>`.

**Comment by sebastian-raubach** [comment]
Ok, thank you. I assume there is no nice overview table that shows all plugins and the contained components?

**Comment by Hiws** [comment]
All plugins? No.

Best you'll get to my knowledge is the **individual components** overview on each component page, paired with the plugin name underneath.

**Comment by sebastian-raubach** [comment]
Ok, thanks again. I was just wondering if there's a less granular way of importing components.

**Comment by Hiws** [comment]
Someone made this loader <https://www.npmjs.com/package/bootstrap-vue-loader>, which goal was to automatically import only the components used, removing the need to manually importing them.

I haven't tested it, and i don't know how well it works. But you can try it if you want.
