### ISSUE TITLE
Table functions break when contained by an overlay

### ISSUE THREAD

**Issue by supermandrew** [bootstrap-vue/bootstrap-vue#5538]
### Describe the bug

When moving a `b-table` to a `b-overlay`, the formatting and tdClass (and possibly other) functions break.

### Steps to reproduce the bug

1. Create a `b-table` with some data.
2. Create a formatting function, and apply it to the table field.
3. Create a `b-overlay`.
4. Move the `b-table` so that it is contained by the `b-overlay`.
5. Notice that the formatting of the items has been broken.

### Expected behavior

The data would remain formatted (and if tdClass used a function to style the field, the field would remain styled correctly).

### Versions

- BootstrapVue: 2.15.0
- Vue: 2.6.11

**Environment:**

- Device: Windows PC
- Browser: Chrome

### Demo link

Link: https://codepen.io/supermandrew/pen/QWyqBPz

Simply uncomment the `b-overlay`'s opening and closing tags, and notice that the formatting of the amount field breaks.  

This can be worked around in codepen by changing the formatter to `this.currencyFormat`, however this does not work in my local environment, and thus to do something like that forces me to move the currencyFormat function outside of the scope of Vue.

**Comment by jackmu95** [comment]
The problem is that you provide the method as a string (`{ ... formatter: "currencyFormat" }`) but you have to provide the function reference (`{ ... formatter: this.currencyFormat }`).

See: https://codepen.io/jackmu95/pen/RwaMGyY
