### ISSUE TITLE
Is Troy still on board? Maybe any help ($) required?

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#5542]
Hi guys.

I see that development has stopped. Possibly it is due to the current world situation. Maybe any help ($) required?

**Comment by bddexter** [comment]
I was actually wondering the same thing.

**Comment by TitanFighter** [comment]
@tmorehouse ping

**Comment by leo95works** [comment]
@tmorehouse ping

**Comment by Hiws** [comment]
No need to constantly ping him :/

**Comment by jackmu95** [comment]
No need to worry - BootstrapVue development will continue!
I personally was quite stuck into work and will have more in the coming weeks.

Currently I'am looking through all open PR's and most critical issues and v2.16.0 will be released in a few days.
