### ISSUE TITLE
[table] should have a fixed header and columns

### ISSUE THREAD

**Issue by yukilau99** [bootstrap-vue/bootstrap-vue#555]
as title.

**Comment by tmorehouse** [comment]
Are you referring to CSS `table-layout: fixed`?

**Comment by tmorehouse** [comment]
Currently `b-table` supports all the features as defined by Bootstrap v4.alpha.6.

**Comment by tmorehouse** [comment]
It appears that one can do fixed headers via custom CSS  only.  This would be out of scope of our alignment with Bootstrap V4 CSS.  But you could create your own CSS class and apply it to your table component.  See https://codepen.io/tjvantoll/pen/JEKIu

**Comment by yukilau99** [comment]
Got it, thank you, I will close this issue.
