### ISSUE TITLE
Prior doc versions

### ISSUE THREAD

**Issue by jcalfee** [bootstrap-vue/bootstrap-vue#5555]
### Documentation issue

![image](https://user-images.githubusercontent.com/204121/86486668-815abf80-bd21-11ea-9e25-4e2fa4ed1e38.png)

I'm looking for v2.8.0 ... Can you please advise the best way for me to access those docs?  Thank you..

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs

**Comment by Hiws** [comment]
Clone/download the GitHub repo of that version and run/build the docs locally.

**Comment by jcalfee** [comment]
Thank you

**Comment by Hiws** [comment]
Just thought I'd mention that you should be safe to update to the latest release.
There haven't been any breaking changes between the version you're using and `v2.15.0`.

**Comment by jcalfee** [comment]
Thanks for the tip .. I'll look to upgrade then.  I had some issues in the accordion.  I was fortunate to notice in a deployment and still have my local "working" version to reference.  I fixed it by locking that version in my package.json .. I don't recall the details but that is why I needed to stay locked on a prior version.

**Comment by Hiws** [comment]
Might be related to using `v-b-toggle` along with a click event or having `href="#"` on the element with the directive.
Both should be fixed in the latest version, but if you experience issues feel free to open an issue or ask on [discord](https://discord.gg/j2Mtcny).
