### ISSUE TITLE
Dropdown menu scrollable with corners

### ISSUE THREAD

**Issue by naletups** [bootstrap-vue/bootstrap-vue#5556]
### Describe the bug

The `b-dropdown` and `b-nav-item-dropdown` do not support a lot of items in it nicely. For longer lists, a scrollable dropdown menu would be nice. To achieve this, I have added this:
```css
.scrollable-menu {
  height: auto;
  max-height: 30vh;
  overflow-y: auto;
  overflow-x: hidden;
}
```
This works as so far that I now get a nicely scrollable dropdown. 
![corners](https://user-images.githubusercontent.com/56796035/86494410-500bdf00-bd75-11ea-822c-898275bbe49b.png)

However, my current styling of the menu is that the corners are rounded. Unfortunately, the scrollbar overlaps with the corners,  see top right (even more pronounced when radius would be bigger). This also applies to normal Bootstrap, but someone here as an idea :-)

### Steps to reproduce the bug
1. create a dropdown with like 10 items
2. apply above CSS class as `menu-class`

### Expected behavior

A convenient way to properly style the elements would be nice. An option would be to wrap the dropdown content in a container/div that has `overflow:hidden`, or replace it altogether with a custom component (selection of div/spans with js that synchs content to hidden formfields and applies scrolling properly)?

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: Laptop and Phone
- OS: Linux and Win
- Browser: Chromium and Firefox

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
You can workaround this by (in a less than pretty way), to solve this issue.
You can wrap the items in your own `ul`, which will have the scrollbar applied, while the normal `ul` will have overflow hidden and the border-radius applied.
This should prevent the scrollbar from overflowing.

https://codepen.io/Hiws/pen/oNbEQar

I'm not sure how accessible this hacky workaround is, so i would consider just removing the border-radius instead and just having a square dropdown.
