### ISSUE TITLE
Dropdown DOM Error

### ISSUE THREAD

**Issue by MobinSamani** [bootstrap-vue/bootstrap-vue#5557]
Hello :)
In new version of BootstrapVue (v.2.15.0), When i use dropdown, i get DOM Error.

![Screenshot from 2020-07-04 12-48-00](https://user-images.githubusercontent.com/53183860/86508374-d0255980-bdf4-11ea-9d97-95c229a55f78.jpg)

**Versions**

- BootstrapVue: 2.15.0

- Bootstrap: 4.5.0

- Vue.js: 2.6.11

**Comment by Hiws** [comment]
Could you share your code or a reproduction of the issue?

**Comment by MobinSamani** [comment]
@Hiws 
Yeah sure. its just a simple dropdown like the BootstrapVue document first example:
![Screenshot from 2020-07-04 14-19-39](https://user-images.githubusercontent.com/53183860/86510018-91e26700-be01-11ea-8760-b6fd8662389a.jpg)

**Comment by MobinSamani** [comment]
@Hiws 
Do you want to change the status of this issue report?

**Comment by nachogarcia** [comment]
I had this issue using the prop 
```
:text="var1 || var2"
```

As a workaround I just replaced it with

```
<template v-slot:button-content>
 {{ var1 || var2 }}
</template>
```

**Comment by MobinSamani** [comment]
> I had this issue using the prop
> 
> ```
> :text="var1 || var2"
> ```
> 
> As a workaround I just replaced it with
> 
> ```
> <template v-slot:button-content>
>  {{ var1 || var2 }}
> </template>
> ```
