### ISSUE TITLE
dropdown is covered by navbar

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#5558]
### Describe the bug

![Screenshot from 2020-07-06 11-00-02](https://user-images.githubusercontent.com/1283842/86570035-f9222780-bf77-11ea-80cc-265c8ab390fd.png)

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.org/docs/components/dropdown
2. Scroll page to have some space between "Drop-Up" button and navbar, as in screenshot. Too less space will open dropdown down instead of up.
2. Click on "Drop-Up"
4. See drop-up covered by navbar

### Expected behavior

Drop-up should be on top of navbar.
Changing z-index of dropdown from 1000 to 10000 fixes this, but I don't see any z-index set on navbar. I'm not sure of the best way to make it future-proof, including Bootstrap 5.
Also, does this bug belong to Bootstrap?

### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.5.0

**Environment:**

- Browser: Chrome 83

**Comment by Hiws** [comment]
A fixed navbar has a default z-index of `1030`, while a dropdown has `1000` as you mentioned.
So the navbar will be on top of the dropdown, you can change this using SCSS if you want to in your project.

Here's the list of default `z-index`, that you can change as you see fit.
```scss
$zindex-dropdown:                   1000 !default;
$zindex-sticky:                     1020 !default;
$zindex-fixed:                      1030 !default;
$zindex-modal-backdrop:             1040 !default;
$zindex-modal:                      1050 !default;
$zindex-popover:                    1060 !default;
$zindex-tooltip:                    1070 !default;
```

**Comment by mariusa** [comment]
Thanks Hiws,

It makes sense to have better defaults in Bootstrap / Bootstrap-vue, so users don't have to adjust CSS to make bugfixes.

**Comment by Hiws** [comment]
If that's the case you should report it on the Bootstrap repo.

Personally I'd want the navbar to always be on top, but other might not.

**Comment by Hiws** [comment]
and based on this comment (https://github.com/twbs/bootstrap/issues/24920#issuecomment-628865986) from May, I don't think it's something that is going to change as it appears to be the intended way dropdowns and a fixed navbar works together.

**Comment by mariusa** [comment]
> If that's the case you should report it on the Bootstrap repo.

Done, thanks:
https://github.com/twbs/bootstrap/issues/31244
