### ISSUE TITLE
Support for Nuxt's auto component import

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#5559]
### Is your feature request related to a problem? Please describe...

Since v2.13 Nuxt supports auto importing components using https://github.com/nuxt/components

### Describe the solution you'd like

That I can use bootstrap-vue components without having to worry about individual imports

### Describe alternatives you've considered

Manually manage imports & plugin usage

### Additional context

- This repo could be helpful as an example: https://github.com/Krutie/Kru-Components
- Users probably still need to be able to indicate somehow they want to use a Plugin instead of importing individual components, eg because they want to use `$bvModal`

**Comment by Hiws** [comment]
Is this something you could take a look at, @pi0?
