### ISSUE TITLE
b-button click event works on desktop, fails to also catch touch events like native button

### ISSUE THREAD

**Issue by namello-zmtp** [bootstrap-vue/bootstrap-vue#5562]
### Describe the bug

If you use:
```html
<b-button @click="share">
  <b-icon icon="box-arrow-up"></b-icon>
</b-button>
```

it will work on desktop via mouse click but doesn't respond to clicks at least on iOS (latest).

### Steps to reproduce the bug

```html
<b-button @click="share">
  <b-icon icon="box-arrow-up"></b-icon>
</b-button>
```

Click on it using an event called share (no event called)

### Expected behavior

```html
<button @click="share">
  <b-icon icon="box-arrow-up"></b-icon>
</button>
```

When you use a normal button control, the event works on both desktop & iOS.

### Versions

Latest

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: any iphone
- OS: iOS
- Browser: Safari/PWA
- Version: Latest/Any

**Comment by jackmu95** [comment]
@namello-zmtp I've created a [CodeSanbox](https://codesandbox.io/s/xlvku) to reproduce the issue.
I wasn't able to reproduce the issue in neither iOS or Chrome on iOS.
