### ISSUE TITLE
Bootstrap vue website is being used to advertise gambling websites.

### ISSUE THREAD

**Issue by muster-mark** [bootstrap-vue/bootstrap-vue#5565]
### Describe the bug

Sponsors' websites are shown on bootstrap-vue.org without being properly vetted. Of the 17 bronze sponsors, 11 are gambling websites, mostly Finnish.

### Steps to reproduce the bug

Visit https://bootstrap-vue.org/

### Expected behavior

The bootstrap vue website should not promote socially irresponsible websites.

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

n/a

### Demo link

Visit https://bootstrap-vue.org/

**Comment by Hiws** [comment]
Don't really think we have an control over who shows up, as long as they furfil the bronze requirement on Open Collective.
https://opencollective.com/bootstrap-vue#sponsor

Unless there's a way to decline sponsors, I'm not sure there's a way to fix it.

@jackmu95 Do you have any idea?

**Comment by jackmu95** [comment]
I don't think we can do anything about this and I don't see that much of an issue here.
We don't "promote" them, we just list them as a sponsor.
