### ISSUE TITLE
b-navbar-nav center items not working

### ISSUE THREAD

**Issue by rlee1990** [bootstrap-vue/bootstrap-vue#5566]
The b-navbar-nav docs state that: Align the nav items in the nav: 'start' (or 'left'), 'center', 'end' (or 'right'). When I try to align the items in center they do not align. I also see that in the navbar-nav.js file 
```
const computeJustifyContent = value => {
  // Normalize value
  value = value === 'left' ? 'start' : value === 'right' ? 'end' : value
  return `justify-content-${value}`
}

```
```
<b-navbar-nav v-if="isUserAuth" align="center">
          <b-nav-item :to="{name: 'Home'}">
            <b-icon icon="house" style="color: #ffffff"></b-icon>
          </b-nav-item>
          <b-nav-item-dropdown>
            <template v-slot:button-content>
              <b-icon icon="gear" style="color: #ffffff"></b-icon>
            </template>
            <b-dropdown-item @click="signOut">Sign Out</b-dropdown-item>
          </b-nav-item-dropdown>
        </b-navbar-nav>
```

**Comment by Hiws** [comment]
`<b-navbar-nav>` only has the width of its items by default. So there's no "space" to center them in.
Add `class="w-100"` to `<b-navbar-nav>` to get it to stretch and you should see your items centering accordingly to the new space.

Alternatively you can center `<b-navbar-nav>` by adding the class `mx-auto` to it, and remove the align prop since it's not needed after that.

```html
<b-navbar variant="dark">
  <b-navbar-nav align="center" class="w-100">
  <!-- <b-navbar-nav class="mx-auto"> -->
    <b-nav-item :to="{name: 'Home'}">
      <b-icon icon="house" variant="white"></b-icon>
    </b-nav-item>
    <b-nav-item-dropdown no-caret>
      <template v-slot:button-content>
        <b-icon icon="gear" variant="white"></b-icon>
      </template>
      <b-dropdown-item>Sign Out</b-dropdown-item>
    </b-nav-item-dropdown>
  </b-navbar-nav>
</b-navbar>
```

or

**Comment by rlee1990** [comment]
> `<b-navbar-nav>` only has the width of its items by default. So there's no "space" to center them in.
> Add `class="w-100"` to `<b-navbar-nav>` to get it to stretch and you should see your items centering accordingly to the new space.
> 
> Alternatively you can center `<b-navbar-nav>` by adding the class `mx-auto` to it, and remove the align prop since it's not needed after that.
> 
> ```
> <b-navbar variant="dark">
>   <b-navbar-nav align="center" class="w-100">
>   
>     <b-nav-item :to="{name: 'Home'}">
>       <b-icon icon="house" variant="white"></b-icon>
>     </b-nav-item>
>     <b-nav-item-dropdown no-caret>
>       <template v-slot:button-content>
>         <b-icon icon="gear" variant="white"></b-icon>
>       </template>
>       <b-dropdown-item>Sign Out</b-dropdown-item>
>     </b-nav-item-dropdown>
>   </b-navbar-nav>
> </b-navbar>
> ```

Thanks that worked.
