### ISSUE TITLE
Nav item to named route?

### ISSUE THREAD

**Issue by CrixuAMG** [bootstrap-vue/bootstrap-vue#557]
I've got a (vertical) navbar, in which I have six nav items. These would lead to named child routes,  so: foo/bar, foo/user, foo/foobar, etc.
In the source of the [link component](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/link.vue) I can see that you support creating router links.
Is there any mainstream way of creating a named router link in a nav item? If not, could we get support for (named) router links in more elements? 

Thanks in advance!

**Comment by tmorehouse** [comment]
You can pass a router link route object to the `to` prop.

Although I m not sure if the bootstrap-vue `b-link` internal component supports the named route property.

**Comment by CrixuAMG** [comment]
For now I've switched to a normal router link, and pass the bootstrap class as the active class.
Looking forward to the update!

**Comment by alexsasharegan** [comment]
@tmorehouse, what are we missing to support this? Is this another component that needs link properties extended on it?

**Comment by tmorehouse** [comment]
the `to` prop supports a variety of object properties, one being href, route, and name. for router-linkis.

I recall that the b-link looks only for a few sub properties of `to`, but might need to pass the entire `to` over to router-link.

I will need to read up more on router-link props.  It might be a simple fix, but not sure.

**Comment by alexsasharegan** [comment]
The `to` is passed along unchanged as far as I can see: https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/link.vue

**Comment by tmorehouse** [comment]
Hmm there was one section of code I recall that looked for a child param in `to` that was passed (maybe over to href?).

**Comment by alexsasharegan** [comment]
I feel like I remember that in breadcrumbs maybe.

**Comment by alexsasharegan** [comment]
@CrixuAMG, can you drop in a code sample of what you're working with?

**Comment by tmorehouse** [comment]
And also what your `to` object looks like?

**Comment by CrixuAMG** [comment]
Apologies for the late reply, I had to shift my focus to other parts of the project and had forgotten completely about the issue...

Basically, I've solved this back then by just using 
```
            <b-nav vertical tabs>
                <router-link class="nav-item"
                             active-class="active"
                             v-for="(item, index) in list"
                             :key="index"
                             :to="{ name: item.name }">{{ item.title }}
                </router-link>
            </b-nav>
```

Though I first tried to (at the time of creating this issue) use the `nav-item` from this package.

**Comment by technofreak** [comment]
> class="nav-item"

I had to use "nav-link" instead of retain the styling of a b-nav-item in the above snippet.

**Comment by tmorehouse** [comment]
If your nav link uses the `to` prop (and you have vue-router or compatable), your `to` prop can be set to a regular router to object.  i.e. `:to="{ name: 'foobar' }"`

Make sure you use the binding sysntax (i.e. `:to="{...}` or `v-bind:to="{...}"`)

If a string is passed to `to`, then vue-router will interpret that as a standard link `href` value.
