### ISSUE TITLE
[BTable] Duplicate @row-selected events when there are two tables

### ISSUE THREAD

**Issue by frbuceta** [bootstrap-vue/bootstrap-vue#5570]
### Describe the bug

I have two tables on one page, one with the _row-selected_ event and one without it. When I select a row in the select table, it emits **two _@row-selected_ events one with an array of objects and the other with an empty array**. If I drop the table without the row-selected event, the table with the row-selected event only emits one event with an array of objects.

### Steps to reproduce the bug

1. Having two tables (BTable), one with the row-selected event and one without it.
2. Click on the table row with the event
3. Observe that two events of type row-selected are emitted, one with an array of objects and the other with an empty array

### Expected behavior

It should emit only one event like it does when there is only one table

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.5.0
- Nuxt: 2.13.3

**Environment:**

- Device: Mac
- OS: **macOS** Catalina
- Browser: Chrome
- Version: 83.0.4103.116 (Official Build) (64-bit)

### Demo link

https://codepen.io/frbuceta/pen/vYLrKPb

**Comment by Hiws** [comment]
I'm unable to reproduce the issue with the code below.
Is this happening in production or in dev?
It might also be something specific to do with mac.

Could you try to reproduce the issue in a codepen/codesandbox?
You can export a ready-to-use template at the [playground](https://bootstrap-vue.org/play/)

```html
<template>
    <b-row>
      <b-col>
        <b-table :items="items" selectable @row-selected="onRowSelected"></b-table>
      </b-col>
      <b-col>
        <b-table :items="items" selectable></b-table>
      </b-col>
    </b-row>
</template>

<script>
export default {
  data() {
    return {
      items: [{ id: 1 }, { id: 2 }, { id: 3 }]
    };
  },
  methods: {
    onRowSelected(selectedItems) {
      console.log(selectedItems);
    }
  }
};
</script>
```

#### Libraries:
- BootstrapVue: 2.15.0
- Bootstrap: 4.5.0
- Nuxt: 2.13.3


#### Environment:
- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by frbuceta** [comment]
> I'm unable to reproduce the issue with the code below.
> Is this happening in production or in dev?
> It might also be something specific to do with mac.
> 
> Could you try to reproduce the issue in a codepen/codesandbox?
> You can export a ready-to-use template at the [playground](https://bootstrap-vue.org/play/)
> 
> ```
> <template>
>     <b-row>
>       <b-col>
>         <b-table :items="items" selectable @row-selected="onRowSelected"></b-table>
>       </b-col>
>       <b-col>
>         <b-table :items="items" selectable></b-table>
>       </b-col>
>     </b-row>
> </template>
> 
> <script>
> export default {
>   data() {
>     return {
>       items: [{ id: 1 }, { id: 2 }, { id: 3 }]
>     };
>   },
>   methods: {
>     onRowSelected(selectedItems) {
>       console.log(selectedItems);
>     }
>   }
> };
> </script>
> ```
> 
> #### Libraries:
> * BootstrapVue: 2.15.0
> * Bootstrap: 4.5.0
> * Nuxt: 2.13.3
> 
> #### Environment:
> * Device: Desktop
> * OS: Windows 10
> * Browser: Chrome
> * Version: 83.0.4103.116 (Official Build) (64-bit)

Sorry, I was writing the example. Update the post above

**Comment by Hiws** [comment]
I think it's because you're reusing the same provider function.

If you comment out the `this.twoTableOptions.filter.id = rows[0]?.id || null` in your `onRowSelected` function, it only logs once.

So what's happening is, that apparently table 1 detect a change in a filter, which triggers the provider function to run again.
And all selections are un-done when the provider function runs, meaning when you click. You select the one, and then immediately after it clears the selection, running the event again.

If i split it up into two seperate provider functions, it looks to work as intended.
https://codepen.io/Hiws/pen/BajVLpK

**Comment by frbuceta** [comment]
In my code none of those options works for me, I have tried everything. As soon as I put this on it doesn't work.
```js
getCustomTravelsFilter() {
  return {
    filter: this.isEmptyKeysOf(this.travelsTableOptions.filter)
      ? this.workingDaysTableOptions.filter
      : this.travelsTableOptions.filter,
    }
},
```

```js
isEmptyKeysOf(obj) {
  return _.values(obj).every(_.isEmpty)
},
```
