### ISSUE TITLE
b-form-checkbox-group and b-form-checkbox RTL support issue

### ISSUE THREAD

**Issue by saeedkgr** [bootstrap-vue/bootstrap-vue#5572]
### Describe the bug
setting dir="rtl" in these two component don't affect the rendered element.

### Steps to reproduce the bug

1. place a     <b-form-checkbox  dir="rtl">  Rtl Checkbox  </b-form-checkbox >       in template

### Expected behavior

in dir="rtl" text of checkboc must place left and the box itself must place at right,

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.3.1
- Vue: 2.6.11

**Environment:**

- Device: PC
- OS: windows 10
- Browser: Chrome
- Version: 83.0.413

**Comment by jackmu95** [comment]
Bootstrap v4 doesn't have full RTL support.

There is an ongoing discussion wether Bootstrap v5 will have it:
https://github.com/twbs/bootstrap/issues/30918
