### ISSUE TITLE
FormFile multiple doesn't seem to be working on Android device

### ISSUE THREAD

**Issue by TheCrafter** [bootstrap-vue/bootstrap-vue#5573]
### Describe the bug

I am using the [FormFile ](https://bootstrap-vue.org/docs/components/form-file)input component with the `multiple` option to upload files. When I'm opening my app from my desktop it works fine.

However, when I open it from my Android device it will only let me select 1 file.

### Steps to reproduce the bug

1. Create a simple app with bootstrap-vue and add one `FormFile` input field
2. Serve the app
3. Open the app from a mobile phone
4. Try to select multiple files
5. You cannot select multiple files

### Expected behavior

I expected to be able to select multiple files.

### Versions

**Libraries:**

- BootstrapVue: ^2.15.0
- Bootstrap: ^4.5.0
- Vue: ^2.6.11

**Environment:**

- Device: Redmi Note 8 Pro
- OS: Android 10 (QP1A.190711.020)
- Browser: The native MIUI browser. Not sure what it's name is.
- Browser Version: 12.2.6-g

**Comment by TheCrafter** [comment]
For reference here is my form file snippet:

```
<b-col md="8" sm="6">
  <b-form-file
          v-model="files_pro"
          :state="Boolean(files_pro)"
          multiple
          accept="image/*"
          :placeholder="$t('choose_files')"
          :drop-placeholder="$t('drop_placeholder')"/>
</b-col>
```

**Comment by Hiws** [comment]
Could you try using a normal `<input type="file">` and see if the issue exists there as well?

**Comment by TheCrafter** [comment]
Yeap you are right. It works on Chrome. It must be browser bug. Thank you.
