### ISSUE TITLE
b-table sorting and custom data rendering problem

### ISSUE THREAD

**Issue by jonasdegener** [bootstrap-vue/bootstrap-vue#5574]
### Describe the bug

We want to create a table with input, which works as follows: We want to have the possibility to select from several elements, single elements in the table. But if you want to sort the table by e.g. name and then select elements, the selection gets mixed up and wrong values get changed. To concretise the problem: values of the Bootstrap switch check boxes and their values won´t get differentiated correctly. 
The selection doesn´t work properly anymore.  

### Steps to reproduce the bug

1. Go to the table
2. Click on sorting the items
3. click on different switch check boxes a couple of time.
4. See that several boxes be adjusted simultaneously.

### Expected behavior

We want only one box to be changed when you click on it, not several at once.

### Versions

**Libraries:**

- BootstrapVue: 2.13.0
- Vue: 2.6.11

**Environment:**

- Device: PC
- OS: Windows
- Browser: Chrome, Firefox
- Version: Chrome:  83.0.4103.116

### Demo link

youtube:  https://youtu.be/25pZGP8z_VA

https://codesandbox.io/s/exciting-cache-exdq3?file=/src/App.vue

**Comment by Hiws** [comment]
I removed the `key` from the checkbox and added `primary-key="id"` to `<b-table>`. *
Which looks to fix the issue.

**Comment by jonasdegener** [comment]
Thank you very much, that has helped us a lot
