### ISSUE TITLE
Prevent closing Toast when closing Modal in BootstrapVue

### ISSUE THREAD

**Issue by chhumsina** [bootstrap-vue/bootstrap-vue#5577]
I would like to prevent closing Toast when closing Modal in BootstrapVue.

Scenario:

1. Open the Modal and Toast on the page
2. Close the modal
3. then Modal and Toast closed at the same time

> **Question: how to keep Toast stays**

I have tried adding this to Toast:
 **autoHideDelay: 10000** or  **'no-auto-hide': true**

> _But it still closed with Modal_

  ```
created() {
       this.$bvModal.show('modal-form-id')

       const errorToaster = {
          title: 'Success',
          toaster: 'b-toaster-top-center',
          variant: 'success'
        }
       this.$bvToast.toast('Success', errorToaster)
    },
    methods: {
       closeModal() {
         this.$bvModal.hide('modal-form-id')
       }
    }
```

Appreciate for helping :)

**Comment by Hiws** [comment]
Looks to work fine here.
https://codepen.io/Hiws/pen/LYGBoNK

Are you changing route when the modal closes?

**Comment by chhumsina** [comment]
> tLooks to work fine here.
> https://codepen.io/Hiws/pen/LYGBoNK
> 
> Are you changing route when the modal closes?
> If not, can you reproduce the issue in a codepen?

it's cause a problem because I put it in Modal component?

**Comment by Hiws** [comment]
What do you mean with "In modal component"?
Is the component destroyed when the modal closes?

You could try using the `$root` instance to launch your toast.
```js
this.$root.$bvToast.toast("Success", errorToaster);
```
