### ISSUE TITLE
Sidebar does not display correctly when using scoped css

### ISSUE THREAD

**Issue by adholland** [bootstrap-vue/bootstrap-vue#5578]
### Describe the bug

I need to use scoped css to avoid the bootstrap vue css 'polluting' the rest of the page. This is achieved using v-deep to ensure the styling is scoped correctly.

However this means that I cannot use a sidebar, as it does not render correctly. Removing scoping and it displays as expected.

### Steps to reproduce the bug

Add bootstrap vue styling as follows: -

```html
<style lang="scss" scoped>
::v-deep {
    @import '~bootstrap/scss/bootstrap.scss';

    /* Default body styles */
    margin: 0;
    font-family: $font-family-base;
    @include font-size($font-size-base);
    font-weight: $font-weight-base;
    line-height: $line-height-base;
    color: $body-color;
    text-align: left;
    background-color: $body-bg;

    @import '~bootstrap-vue/dist/bootstrap-vue.css';
}
</style>
```

And add a sidebar and it renders incorrectly. 

Remove the scoping (incuding the v-deep): -

```html
<style lang="scss">
    @import '~bootstrap/scss/bootstrap.scss';
    @import '~bootstrap-vue/dist/bootstrap-vue.css';
</style>
```
and the sidebar displays as expected.

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Vue: 2.6.1

**Comment by adholland** [comment]
![incorrect_render](https://user-images.githubusercontent.com/27013642/87441149-ad602580-c5ea-11ea-9553-786df009183a.png)

**Comment by adholland** [comment]
![correct_render](https://user-images.githubusercontent.com/27013642/87441495-1051bc80-c5eb-11ea-8d68-5a924818ae75.png)

**Comment by Hiws** [comment]
The above setup works fine for me, both with the sidebar in the same component as the scoped CSS and in a child.

Where are you placing the sidebar? Did you make sure it's inside the same scope as the CSS?

**Comment by adholland** [comment]
I really cant get it to work scoped.

*** App.vue ***

`<template>
  <div id="app">
        <b-btn>Home</b-btn>
        <hr />

        <div id="scoped-styles">
            <b-btn
                v-b-popover="{ container: 'scoped-styles', content: 'FooBar' }"
                title="Hello World"
                variant="primary"
            >
                Home
            </b-btn>
            <hr />
            <Test />
            <div id="scoped-styles2">
                <b-btn id="popover-reactive-1"
                    title="Hello World"
                    variant="primary"
                >
                Home
                </b-btn>
            </div>
            <b-popover 
                :delay="{show: 1250, hide: 0}"
                container="scoped-styles2"
                target="popover-reactive-1"
                placement="auto"
                triggers="hover"
            >
                <b-card class="border-0"
                    :header="attachment.name"
                    header-tag="header"
                    body-class="widget-popup-card-body"
                    >
                    <div class="file-popover-details">
                        id: {{ attachment.id }} <br />
                        up: {{ attachment.uploaded_by }}<br />
                        time: {{ attachment.uploaded_timestamp }}<br />
                        type: {{ attachment.type }}<br />
                    </div>
                </b-card>
            </b-popover>
        </div>
  </div>
</template>

<script>
import Test from "@/components/Test.vue";
export default {
    components: {
        Test
    },
    data() {
        return {
            attachment: {
                id: 1001,
                name: 'test',
                type: 'video',
                uploaded_by: 'Username1',
                uploaded_timestamp: '25/11/2019',
            }
        };
    }
};
</script>

<style lang="scss" scoped>
#scoped-styles::v-deep {
  @import '~bootstrap/scss/bootstrap.scss';

  /* Default body styles */
  margin: 0;
  font-family: $font-family-base;
  @include font-size($font-size-base);
  font-weight: $font-weight-base;
  line-height: $line-height-base;
  color: $body-color;
  text-align: left;
  background-color: $body-bg;

  @import '~bootstrap-vue/dist/bootstrap-vue.css';
}


</style>`


Test.vue 

`<template>
  <div>
      <b-btn variant="success">
          Child Button
      </b-btn>
      <b-avatar 
          badge="1"
          button
          v-b-toggle.sidebar-no-header
          class="mr-sm-1"
      >
      </b-avatar> 
      <b-sidebar id="sidebar-no-header" sidebar-class="border-right border-danger">
        <div class="px-3 py-2">
          <p>
            Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis
            in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
          </p>
          <b-img src="https://picsum.photos/500/500/?image=54" fluid thumbnail></b-img>
        </div>
      </b-sidebar>
    </div>
</template>`

**Comment by adholland** [comment]
Sorry the code comments dont seem to be working - but the code is contained within the ` chars

**Comment by Hiws** [comment]
I fixed it. You need to use 3x ` for code blocks.

**Comment by adholland** [comment]
Also, as well as the sidebar not working, the avatar badge does not render correctly - due to the scoping.

![badge_render_issue](https://user-images.githubusercontent.com/27013642/87449546-39774a80-c5f5-11ea-9765-00863c43227b.PNG)

**Comment by Hiws** [comment]
Copied your code into my local project and it still runs correctly.

https://streamable.com/egt6h7

My best guess is that your parent CSS (the one outside the scope) is messing with the sidebar.

**Comment by adholland** [comment]
Yes looks like you are right. Just created a new project and added the files and all is well. Really odd its affecting the sidebar and avatar badge (the new parts I'm adding) - everything else seems fine.

So yes something must be trashing the css. 

Thanks for your time.

**Comment by Hiws** [comment]
Best bet would be to open up dev tools and see what's going on by inspecting the sidebar elements.
