### ISSUE TITLE
b-modal vertical center screen after opening from a vue-tabulator @row-click event

### ISSUE THREAD

**Issue by clustersnake** [bootstrap-vue/bootstrap-vue#5582]
### b-modal component centers my screen after opening from a @row-click event in vue-tabulator

It happens only in chrome family browser, I tested in firefox developer edition and the page doesn't scroll. I tried to apply the static prop, lazy, centered and nothing worked. By the way, launching the modal from a button placed outside the table doesn't change the screen position, I mean, it works just fine.
### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.3.1
- Vue: 2.6.11
- vue-tabulator: 1.2.2

**Environment:**

- OS: Windows 8.1 32 bits
- Browser: Opera, Brave, Edge
- Version: latest

### Screens

![image](https://user-images.githubusercontent.com/16407149/87621474-e08bdd00-c6ee-11ea-8c41-47233d9b27f4.png)
![image](https://user-images.githubusercontent.com/16407149/87621563-0dd88b00-c6ef-11ea-82b2-e82cac627e35.png)

**Comment by jackmu95** [comment]
@clustersnake Can you please create a minimal reproduction of the issue in a CodeSandbox or CodePen?

I altered the [Complete example ](https://bootstrap-vue.org/docs/components/table#complete-example) of the table docs a bit to use the `row-clicked` event and was unable to reproduce the issue.

**Comment by clustersnake** [comment]
@jackmu95 thanks!, I'll create the example, by the way, the issue is with [vue-tabulator](https://github.com/angeliski/vue-tabulator) not the b-table

**Comment by clustersnake** [comment]
@jackmu95 I created the [example](https://codesandbox.io/s/bootstrap-vue-4k89l?file=/src/components/HelloWorld.vue). In this page the reset is done only when clicking in the firs row, not the last one but in my local it always resets the vertical position

**Comment by clustersnake** [comment]
@jackmu95 I just tested the vue-tabulator plugin in quasar framework and I have the same issue, please excuse me for bothering you. I'm closing this issue because it's not a Bootstrap-vue issue
