### ISSUE TITLE
Better customization for popover

### ISSUE THREAD

**Issue by paglias** [bootstrap-vue/bootstrap-vue#559]
I would like to be able to:

1. apply a class to the popover element
2. have something similar to `:popover-style` that styles the `popover-content` div because right not it's impossible to style it without applying the change to all the popovers that use the `popover-content` class. I want to style the popover-content div of a specific popover

Thanks!

**Comment by tmorehouse** [comment]
Popovers  (and tooltips) are going to be making a major makeover in bootstrap V4.beta.1 release when they remove tether.js and replace it with popper.js.

So it probably would be best to wait until the major changes are done at twbs bootstrap.

**Comment by paglias** [comment]
@tmorehouse makes sense, I'll wait for it

**Comment by tronjs** [comment]
Hi, correct me if I wrong, but did we have this feature in the latest release (2.0.0-rc11)? I just checked and did not see the thing about this.

**Comment by soylomass** [comment]
Any news about this?

**Comment by guilhermeaiolfi** [comment]
Missing that feature too.

**Comment by tmorehouse** [comment]
Its on the roadmap.... see issue #2173

**Comment by jacobg** [comment]
There's a `custom-class` property on the popover element on version 2.1.0
