### ISSUE TITLE
Need to open b-form-select dropdown from function:

### ISSUE THREAD

**Issue by jeraldsiby** [bootstrap-vue/bootstrap-vue#5591]
I tried different ways to trigger the click event from a function. But I could not find anything online.
Last, I was able to trigger the focus function using a reference property:
My Code:
<b-form-select id="ratio" ref="ratioList" @change="onChange()" v-on:focus.native="focusIn" class="dateTextInput" v-model="showCreated" :options="createdSelect">
            </b-form-select>

I tried>>>this.$refs.ratioList.focus();   WORKED!!!
but, I need something like >>this.$refs.ratioList.click(); which does not work
It says click function is not defined!
Any suggestions???

**Comment by Hiws** [comment]
Why do you need to open it from a method?

**Comment by jeraldsiby** [comment]
I have added arrow icon to open the drop down of b-form-select. So, I need to open the drop down on the icon click. I am not sure if it needs to be a click event that needs to be triggered. Any suggestions?
focus function helps to get the focus in control but the drop down still remain closed.

**Comment by Hiws** [comment]
Based on answers i found, there's no way to programmatically open a select.
So you'll have to find another solution, like using `b-dropdown`
