### ISSUE TITLE
Question: avatar text font-size with calc()? Possible to eliminate?

### ISSUE THREAD

**Issue by mmilano** [bootstrap-vue/bootstrap-vue#5592]
When the avatar component is used, and text is specified e.g. initials

```
<b-avatar rounded text="DF"></b-avatar>
```
the resulting <span> element gets inline `font-size` css:
```
<span class="b-avatar-text" style="font-size: calc(1em);"><span>DF</span></span>
```

Questions:
1. Why the seemingly redundant second <span></span> around the text itself, inside the .b-avatar-text?
2. Is there a way to completely disable the creation of the inline css? Is that method of implementation necessary as a design decision (on the part of the library)?

Not only do I wish to not have the inline-css (as principle), I am already styling the text with custom css. 
On a page with many avatars, the overhead is undesirable.

In general, this seems like it would be better addressed by styles in the scss.

(For that matter, the inline css on the `.b-avatar` element is equally undesirable).

- inquiring.

**Comment by jackmu95** [comment]
Maybe it would be a good idea to apply classes for the `sm` and `lg` sizes to `<b-avatar>` and make them configurable via SCSS variables. By default (`:size="null"`), no size class would be applied and a `width` and `height` of `2.5em` would be set via CSS.

The `.b-avatar-text` class would apply a `font-size: 40%;`.

When the user defines a size as number or with a unit we would apply the CSS inline styles as done currently.

**Comment by mmilano** [comment]
In general shape, your proposal sounds good!

As I use BsVue more, I notice that the inline styles are used in a number of places, components. 
Perhaps it is possible to consider a more general behavior across the library that would be something like this ?:

* When the size is defined as number or with a unit, apply the CSS inline styles as done currently.
* if the size is defined as boolean false e.g. `:size=false`, no inline size styles are output. CSS rules would control styling entirely.

From there, the existing SCSS variables and definitions can be used to control appearance, either accepting the defaults or via custom overrides.
