### ISSUE TITLE
[b-form-select] if options are too long, the scrollable would be extended

### ISSUE THREAD

**Issue by hey0wing** [bootstrap-vue/bootstrap-vue#5595]
### Describe the bug

if options are too long, the scroll bar would be extended and drop down would be wider than select box

![Capture1](https://user-images.githubusercontent.com/23263986/88029380-823a8080-cb6c-11ea-8303-dcadd514beec.JPG)
![Capture](https://user-images.githubusercontent.com/23263986/88029386-84044400-cb6c-11ea-9a89-26b2809770e8.JPG)

### Expected behavior

The scroll bar would not be extended, and the whole drop down box should be same size as select box

### Codes

`<b-form-group label="Action">`
`     <b-form-select :options="actionOptions" v-model="query.action"/>`
`  </b-form-group>`
...
`actionOptions () {`
       ` return [`
   `       { text: 'All', value: '' },`
    `      { text: 'Create', value: 'Create' },`
     `     { text: 'Delete', value: 'Delete' },`
      `    { text: 'Update', value: 'Update' },`
       `   { text: 'Move', value: 'Move' },`
        `  { text: 'Set profile', value: 'Set profile' },`
`...`
 `       ]`
  `    }`

### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.1.3
- Vue: 2.5.17

**Environment:**

- Device: desktop
- OS: win10
- Browser: Chrome

**Comment by Hiws** [comment]
Bootstrap-Vue `v2.14.0` requires a minimum of Bootstrap `v4.3.1` and Vue `2.6`. So i would recommend you look to upgrade both of those to see if that solves the issue.

Though, i don't think it will since `<b-form-select>` is a simple wrapper for a native `<select>`.
So try using a normal `<select>` to see if the problem still exists, if it does. I don't think there's much that can be done, since selects aren't very customizable.

**Comment by hey0wing** [comment]
The problem still exist if I use `<select>`  ...
```
        <select v-model="query.action">
          <option v-for="option in actionOptions" :key="option.value" value="option.value">{{option.value}}</option>
        </select>
```

![Capture2](https://user-images.githubusercontent.com/23263986/88246711-e2950380-cccd-11ea-99d1-456d8d958338.JPG)

 I don't think that updating versions would help though

**Comment by Hiws** [comment]
Think this boils down to a browser issue, and not something that can be fixed.
