### ISSUE TITLE
v-b-tooltip css style is not applied when used it in b-dropdown

### ISSUE THREAD

**Issue by augustparkjy** [bootstrap-vue/bootstrap-vue#5599]
### Describe the bug
when I use v-b-tooltip in b-dropdown and hover on button, v-b-tooltip css style is not applied. 
strangely, when I add a component (b-dropdown using v-b-tooltip in it) and mouse hover on button of the added component. the bug is still represented to  that but, when I hover on the first button of v-b-tooltip in b-dropdown, v-b-tooltip css style is applied to the first button.

### Expected behavior
v-b-tooltip css style is applied to each button in b-dropdown.

### Versions

**Libraries:**

- BootstrapVue: 2.0.4
- Bootstrap: 4.3.1
- Vue: 2.6.11

**Environment:**

- Device: Mac 
- OS: Catalina
- Browser: Chrome
- Version: 84

### Code
`<b-dropdown>
          <b-dropdown-form>
            <b-row>
              <b-col>
                <b-button
                  v-b-tooltip
                  title="btn1 tooltip">
                  btn1
                </b-button>
              </b-col>
              <b-col>
                <b-button
                  v-b-tooltip
                  title="btn2 tooltip">
                  btn2
                </b-button>
              </b-col>
            </b-row>
          </b-dropdown-form>
        </b-dropdown>`

**Comment by jackmu95** [comment]
@augustparkjy I've created a CodeSandbox with your exact markup and I'am unable to reproduce your issue.
Can you please provide an live example with more detailed information on how trigger the issue.
https://codesandbox.io/s/sleepy-sanderson-vby4i?file=/App.vue

<img width="338" alt="Bildschirmfoto 2020-07-22 um 17 08 07" src="https://user-images.githubusercontent.com/2737132/88193721-47a11880-cc3e-11ea-8521-0dfb3efd7219.png">
<img width="260" alt="Bildschirmfoto 2020-07-22 um 17 08 15" src="https://user-images.githubusercontent.com/2737132/88193724-4839af00-cc3e-11ea-9c07-5d7f4be9a384.png">

**Comment by Hiws** [comment]
> BootstrapVue: 2.0.4

Your version of Bootstrap-Vue is also quite old, so it might help if you upgraded to the latest version.
