### ISSUE TITLE
Modal is cut off at the top of screen

### ISSUE THREAD

**Issue by henron1** [bootstrap-vue/bootstrap-vue#5600]
When the modal renders it seems to be stuck to the top of the screen and overflowing into it a bit. I've seemed to try all fo the solutions on SO and within these issues pages and nothing seems to work. I've tried overriding the styles and was curious if anyone had experienced this or had a fix.

**Comment by henron1** [comment]
<img width="744" alt="Screen Shot 2020-07-23 at 9 55 34 AM" src="https://user-images.githubusercontent.com/40742091/88295699-c3957200-cccb-11ea-9155-d24b3d333d84.png">

**Comment by henron1** [comment]
gotten through that error and on to another! Now the style comes through using modal-class, but only when I removed my scoped from my style tag. I really need this in there, is there a way to access those styles within the scoped tag? I've tried /deep/ and it has not worked @tmorehouse

**Comment by Hiws** [comment]
Is the issue that your top navbar (from the looks of it), is going over the modal?

**Comment by henron1** [comment]
Found a fix, thank you! /deep/ wasn't working for a few hours and I decided to restart my machine and everything magically works. Go figure, it's a dev's life I guess.
