### ISSUE TITLE
如何引入单个组件

### ISSUE THREAD

**Issue by crtxr1998** [bootstrap-vue/bootstrap-vue#5608]
### Versions

**Libraries:**

- BootstrapVue: 2.1.15

**Comment by jackmu95** [comment]
> 如何引入单个组件 (How to introduce a single component)
@crtxr1998 Please describe a bit more precisely what your issue/question is.

**Comment by PeterlitsZo** [comment]
If you compile your vue project, I think it will only add the component that you use.

By the way, please use English but not Chinese or ask your question with both just because there are many people in community is hard to communicate by Chinese. Thanks.

Is my words about compiling right?
