### ISSUE TITLE
Drag & Drop directory to b-form-file input is limited to 100 files

### ISSUE THREAD

**Issue by Tiiinky** [bootstrap-vue/bootstrap-vue#5615]
### Describe the bug

I am using a file input like this:

`<b-form-file
          id="idDirectoryDrop"
          directory
          multiple
          v-model="droppedDirectory"
          browse-text="Select directory"
          placeholder="Drag & Drop a directory here"
          :file-name-formatter="formatNames"
        ></b-form-file>
`

Selecting a directory via Browse works as expected, but if you drop a directory with 100+ files inside, it will only give you 100 files in the v-model as an array.

### Expected behavior

Same as when browsing for a directory, when dropped, the array should contain all files

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.4.1
- Vue: 2.6.10

**Environment:**

- Device: MacBook
- Browser: Chrome

**Comment by Hiws** [comment]
Just putting this here for future reference, for the person who wants to fix the issue.

Currently files are being read using `readEntries` on a DirectoryReader.
This method only returns a maximum of 100 entries. To get all files you simply run the method again until it stops returning files.

Reference along with a solution:
<https://stackoverflow.com/a/53058574/8397974>
