### ISSUE TITLE
List Group Page Error

### ISSUE THREAD

**Issue by chandlerwilcox88** [bootstrap-vue/bootstrap-vue#5617]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs/components/list-group

### Additional context or description

Provide any additional details here as needed.

![Screen Shot 2020-07-28 at 4 44 27 PM](https://user-images.githubusercontent.com/7296169/88740359-c5a76880-d0f1-11ea-9497-712d4cd6cd89.png)

**Comment by Hiws** [comment]
A new version of the docs have just been released, so refresh your page and if that doesn't work. Clear your cache.
