### ISSUE TITLE
[dropdown-item] How to use as router-link

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#562]
I had updated deps for my project and got an trouble to make b-dropdown-item work as router-link. 
If I add `link` param, then it works as usual link, if i add `to`, then it make `href=#` and doesn't redirect to target url.
How it's supposed to work as router-view?

**Comment by alexsasharegan** [comment]
I'll have a look at the way dropdown items and breadcrumbs deal with this. Are you talking about v0.16.1, or @latest from master branch?

**Comment by mosinve** [comment]
latest master.
I\ve made some debigging and found, that b-dropdown-item.$router isn't assigned somehow...

**Comment by mosinve** [comment]
So, maybe it isn't a lib issue, but my config

**Comment by alexsasharegan** [comment]
Ah, since it does the `vm.$router` detection, that could be it. Keep me posted!

**Comment by alexsasharegan** [comment]
So the `<b-dropdown-item>` shouldn't accept a `link` prop. As far as I know it, `link` is only used in the breadcrumb component (and there it's sort of a convenience prop alias). You can always get docs on the latest props by running the `npm run docs-dev` and heading to the local site on [localhost:3000](http://localhost:3000) (and I think `npm run docs-gen` does the same, but not in watch mode).

**Comment by tmorehouse** [comment]
I think, if you set 'to' object, but leave 'href' blank it should work as a router link (I might be wrong on that though)

**Comment by alexsasharegan** [comment]
Yeah, but it will also require the `$router` to be available on the vue instance.

**Comment by tmorehouse** [comment]
I think when you install vue-router plug in,  it adds a $router prop to all vm instances

**Comment by alexsasharegan** [comment]
Indeed!

**Comment by mosinve** [comment]
Yeah, it adds a $router usually ) but it seems i have unusual case))) 
Today i'll keep to dig this case ))

**Comment by alexsasharegan** [comment]
When all else fails, you could always give it the old `rm -R node_modules && npm install`

**Comment by mosinve** [comment]
okay, i make it work. But now i have another question.
The reason of topic issue was that i tried to use master as linked module (`yarn link`) and do something wrong in `webpack.config`. When I copy `dist `folder to `node_modules/bootstrap-vue`  all works correct

**Comment by mosinve** [comment]
Better to start new issue i think)

**Comment by alexsasharegan** [comment]
Do you think you needed to run the build script on your linked master repo first?

**Comment by alexsasharegan** [comment]
Interesting. It should be a simple symbolic link, but something obviously isn't working. I wonder if you would have to uninstall BV and then link it.
