### ISSUE TITLE
Babel Errors in nuxt generate 2.14

### ISSUE THREAD

**Issue by minyou9** [bootstrap-vue/bootstrap-vue#5627]
### Describe the bug

I updated my nuxt project to the latest release which is 2.14. I then use nuxt generate to build the project. While nuxt is building the project, it gives this error

`[BABEL] Note: The code generator has deoptimised the styling of \node_modules\bootstrap-vue\src\icons\icons.js as it exceeds the max of 500KB.`

### Steps to reproduce the bug

1. Update the project to 2.14
2. Use nuxt generate to build project
3. It will display the error when compiling on the Client

### Expected behavior

Should not have any errors 

### Versions

**Libraries:**

- BootstrapVue: 2.16.0
- Bootstrap: 4.5.0
- Nuxt: 2.14.0

**Comment by mangrove108** [comment]
same here

**Comment by jackmu95** [comment]
This is not an error, it is just a note (`[BABEL] Note: ...`) from Babel's [`compact` option](https://babeljs.io/docs/en/options#compact) option.

Since the `icons.js` file is quite big (> 500KB), all optional newlines and whitespace will be omitted.
When you wan't to get rid of the note, set the compact option to either `true` or `false`,

**Comment by mangrove108** [comment]
cough cough, now i seperated the icons in a seperate icons file, removed the module with compact option true/false, i works but still i got this error message:
`remote:  ERROR  [BABEL] Note: The code generator has deoptimised the styling of /tmp/build_25e67058/node_modules/bootstrap-vue/src/icons/icons.js as it exceeds the max of 500KB.`

what am i missing ? Thanks

**Comment by TooColline** [comment]
@jackmu95 How do you set this on nuxt.config?

**Comment by mangrove108** [comment]
everything works, i import the specific icons i want to use, within a plugin, the plugin is registered in nuxt.config., no other settup, but still i got the error, whats the point in loading only specific icons if the babel loader still gives a warning about exceeding the file size ? no idea

**Comment by jackmu95** [comment]
The warning will show up independently wether you import/register all or just some of the icons.
Relevant for the note is the source file (`icons.js`) and that stays the same.

Please take a look at the [Nuxt.js documentation](https://nuxtjs.org/api/configuration-build/#babel) for the `babel` build property on how to configure it properly.

**Comment by mangrove108** [comment]
ah ok got it now, compact: false increases memory size so i went with true.

My Nuxt.config.js file
` /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
    },
    // npx nuxt build -a
    //analyze: true,
    transpile: [
      ({ isClient }) => isClient && "vee-validate/dist/rules"
    ],
    babel: {
      compact: true
    }
  },`

Thanks for the help!

**Comment by minyou9** [comment]
@jackmu95 @mangrove108 thank you so much for the help. I set the babel compact to true and the error warning is now gone

**Comment by amdp** [comment]
Hi, in the docs it is said the icons shouldn't be loaded by default, but I get that error the same, both if I set 

```
bootstrapVue: {
    icons: false  
}
```

and if I set no bootstrapVue property and just load the module.
Do you know why?

**Comment by mangrove108** [comment]
[BootstrapVue](https://bootstrap-vue.org/docs/icons)

> Usage
BootstrapVue icons are not automatically installed when using BootstrapVue in your project, you must explicitly include them.

I ll use them like so:
// nuxt.config.js
```
modules: [
    // Doc: https://bootstrap-vue.js.org
    'bootstrap-vue/nuxt',
]
```
// icons.js in plugin folder
`import Vue from 'vue'
import { 
    BootstrapVue, 
    BIcon, 
    BIconInfoSquare, 
    BIconInfoSquareFill,
    BIconPencilSquare, 
    BIconEnvelope, 
    BIconEnvelopeFill, 
    BIconSearch, 
    BIconHouseFill, 
    BIconThreeDotsVertical, 
    BIconThreeDots,
    BIconChatSquareTextFill, 
    BIconChatSquareFill,
    BIconClockFill,
    BIconEyeFill,
    BIconChatFill,
    BIconTagFill,
    BIconCalendar2Fill,
    BIconCartFill,
    BIconCart,
    BIconCardText,
    BIconCursorFill,
    BIconCursor,
    BIconShieldShaded,
    BIconPersonPlus,
    BIconPersonPlusFill,
    BIconBoxArrowInRight,
    BIconArrowLeftShort,
    BIconPersonFill,
    BIconShare,
    BIconShareFill

} from 'bootstrap-vue'

Vue.use(BootstrapVue)
Vue.component('BIcon', BIcon)
Vue.component('BIconPencilSquare', BIconPencilSquare)
Vue.component('BIconInfoSquare', BIconInfoSquare)
Vue.component('BIconInfoSquareFill', BIconInfoSquareFill),
Vue.component('BIconEnvelope', BIconEnvelope)
Vue.component('BIconEnvelopeFill', BIconEnvelopeFill)
Vue.component('BIconSearch', BIconSearch)
Vue.component('BIconHouseFill', BIconHouseFill)
Vue.component('BIconThreeDotsVertical', BIconThreeDotsVertical)
Vue.component('BIconThreeDots', BIconThreeDots)
Vue.component('BIconChatSquareFill', BIconChatSquareFill)
Vue.component('BIconChatSquareTextFill', BIconChatSquareTextFill)
Vue.component('BIconChatFill', BIconChatFill)
Vue.component('BIconClockFill', BIconClockFill)
Vue.component('BIconEyeFill', BIconEyeFill)
Vue.component('BIconTagFill', BIconTagFill)
Vue.component('BIconCalendar2Fill', BIconCalendar2Fill)
Vue.component('BIconCartFill', BIconCartFill)
Vue.component('BIconCart', BIconCart)
Vue.component('BIconCursorFill', BIconCursorFill)
Vue.component('BIconCursor', BIconCursor)
Vue.component('BIconShieldShaded', BIconShieldShaded)
Vue.component('BIconCardText', BIconCardText)
Vue.component('BIconPersonPlus', BIconPersonPlus)
Vue.component('BIconPersonFill', BIconPersonFill)
Vue.component('BIconPersonPlusFill', BIconPersonPlusFill)
Vue.component('BIconBoxArrowInRight', BIconBoxArrowInRight)
Vue.component('BIconArrowLeftShort', BIconArrowLeftShort)
Vue.component('BIconShare', BIconShare)
Vue.component('BIconShareFill', BIconShareFill)
`

**Comment by Petercopter** [comment]
Same problem as @amdp. I haven't enabled the icons at all, and I'm seeing the build error. All I did was add `bootstrap-vue/nuxt` to `modules`

**Comment by Kasonz** [comment]
> Same problem as @amdp. I haven't enabled the icons at all, and I'm seeing the build error. All I did was add `bootstrap-vue/nuxt` to `modules`

Same issue  - nuxt.config.js

**Comment by ahmadrezaei** [comment]
If you want to remove icons plugin from your nuxt app remove icons component and directive from global components and just add components you need, for example:

`module.exports = {
  modules: ['bootstrap-vue/nuxt'],
  bootstrapVue: {
    icons: false,
    components: ['BContainer', 'BRow', 'BCol', 'BFormInput', 'BButton', 'BTable', 'BModal'], // not include BootstrapVueIcons component
    directives: ['VBModal', 'VBPopover', 'VBTooltip', 'VBScrollspy']
  }
}`

**Comment by galaxyblur** [comment]
I am not using any bootstrap icons in my Nuxt project, yet I get this Babel error. Is the icons package being bundled into my app? I can set compact:true as demonstrated above, but is this a red flag that something unexpected is happening?

**Comment by hassan-jahan** [comment]
I confirm `icons.js` is included in the bundle whether you set` icons:false` or not.  

Check out by: `yarn run build -a`

**Comment by jackmu95** [comment]
@hassan-jahan I re-checked several config combinations and for me it is all working as expected.
If you can come up with a minimal reproduction feel free to raise a new issue.

To make this clear for all again here; the Babel note about the `icons.js` file is shown all the time when using the `bootstrap-vue/nuxt` module. But that doesn't mean that the icons are included in the production bundle.

**Comment by hassan-jahan** [comment]
@jackmu95 I'm not worried about that note itself but the actual bundle size.

Please check it out here:
https://github.com/hassan-jahan/nuxt-vue-bootstrap-starter

This is a bare Nuxt project created by `yarn create nuxt-app` Try `yarn run build -a` and uncomment nuxt.config.js

**Comment by jackmu95** [comment]
@hassan-jahan I checked out your example project and it works as it should.
As our documentation states [here](https://bootstrap-vue.org/docs#icons) are icons only opt-in and not included by default.

Bundle size with no `bootstrapVue` Nuxt.js config:
<img width="809" alt="Bildschirmfoto 2020-11-08 um 12 53 43" src="https://user-images.githubusercontent.com/2737132/98464290-24d14a80-21c2-11eb-9113-7f0d90f35f7b.png">

Bundle size with `icons: true` in `bootstrapVue` Nuxt.js config:
<img width="1155" alt="Bildschirmfoto 2020-11-08 um 12 55 08" src="https://user-images.githubusercontent.com/2737132/98464316-50543500-21c2-11eb-9c22-2a488569fa0a.png">

**Comment by hassan-jahan** [comment]
Thanks @jackmu9 You're right. 

It seems we include a small part of icons.js when icons:false which is not a problem.

**Comment by khanghh** [comment]
any solution ?

**Comment by hqMoura** [comment]
This problem is still happening with me as well. Anyone managed to fix it?

**Comment by wokalek** [comment]
Same

**Comment by wokalek** [comment]
> It seems we include a small part of icons.js when icons:false which is not a problem.
it IS problem.

**Comment by rutcreate** [comment]
Same here. Any workaround for this?

**Comment by arcs-** [comment]
This is still an issue, please reopen it

**Comment by esaesa** [comment]
This is still an issue. Just after including the Nuxt module without any usage.
```
 modules: [
    // https://go.nuxtjs.dev/bootstrap

    'bootstrap-vue/nuxt',
  ],
  bootstrapVue: {
    icons: false,
    componentPlugins: [],
    directivePlugins: [],
    components: [],
    directives: [],
  },
```
![image](https://user-images.githubusercontent.com/5354709/111920532-32fc7500-8a98-11eb-945c-c5aec184e4a7.png)

**Comment by phil-w** [comment]
Same problem here, although not using nuxt. Can't get rid of those damned icons however I try. Anyone?

**Comment by mangrove108** [comment]
@phil-w although not using nuxt ???
Here everything ok 😀

**Comment by esaesa** [comment]
For my case, I found the case. 
If bootstrap-vue is imported in Nuxt but is not used in any vue component template then the tree handshaking will not omit the unused parts.

**Comment by alijaya** [comment]
so what is the accepted work around?

**Comment by phil-w** [comment]
The problem is in Bootstrap-Vue.
I forced webpack 5 to explicitly not load the stuff I wasn't using (I'm transpiling it explicitly):
```
  'bootstrap-vue$': 'bootstrap-vue/src/index.js',
 // #1173: Stub out large unused Bootstrap-Vue icons file.
 [path.resolve(__dirname, '../node_modules/bootstrap-vue/src/icons/icons.js')]: false,
 [path.resolve(__dirname, '../node_modules/bootstrap-vue/src/icons/plugin.js')]: false,
```
That leaves with no icons at all, however, even if you import those you want.
However you can efficiently include just those same icons which you actually use without Boostrap Vue.

**Comment by fahmiegerton** [comment]
> The problem is in Bootstrap-Vue.
> I forced webpack 5 to explicitly not load the stuff I wasn't using (I'm transpiling it explicitly):
> 
> ```
>   'bootstrap-vue$': 'bootstrap-vue/src/index.js',
>  // #1173: Stub out large unused Bootstrap-Vue icons file.
>  [path.resolve(__dirname, '../node_modules/bootstrap-vue/src/icons/icons.js')]: false,
>  [path.resolve(__dirname, '../node_modules/bootstrap-vue/src/icons/plugin.js')]: false,
> ```
> 
> That leaves with no icons at all, however, even if you import those you want.
> However you can efficiently include just those same icons which you actually use without Boostrap Vue.

Where I put this please ? I'm not so familiar with webpack.

**Comment by PixsaOJ** [comment]
Reopen, still an issue !

**Comment by shinguweb96** [comment]
Bump, still a big issue

**Comment by piyushdolar** [comment]
I'm using bootstrap-vue and nuxt
I've solved problem by using,

`// Build Configuration: https://go.nuxtjs.dev/config-build
    build: {
      babel: {
	      compact: true
      }
  }`

**Comment by PixsaOJ** [comment]
`build: { babel: { compact: true } }`
and
```JavaScript
modules: [
    [
     'bootstrap-vue/nuxt',
         {
             icons: false
         }
    ],
    ...
```

Seems to work. Just make sure you have the latest packages.

**Comment by petertorelli** [comment]
@PixsaOJ the problem is the final bundle size is huge even if no icons are used. `babel: compact` just hides the warning. I removed bootstrap-vue and just linked in the bootstrap CSS and JS, and it shaves of ~500KB from the production build.

**Comment by PixsaOJ** [comment]
@rutcreate nuxt ^2.15.6, bootstrap: ^4.6.0, bootstrap-vue: ^4.6.0

**Comment by devzom** [comment]
> The problem is in Bootstrap-Vue. I forced webpack 5 to explicitly not load the stuff I wasn't using (I'm transpiling it explicitly):
> 
> ```
>   'bootstrap-vue$': 'bootstrap-vue/src/index.js',
>  // #1173: Stub out large unused Bootstrap-Vue icons file.
>  [path.resolve(__dirname, '../node_modules/bootstrap-vue/src/icons/icons.js')]: false,
>  [path.resolve(__dirname, '../node_modules/bootstrap-vue/src/icons/plugin.js')]: false,
> ```
> 
> That leaves with no icons at all, however, even if you import those you want. However you can efficiently include just those same icons which you actually use without Boostrap Vue.

How exactly have You added it? I quess into nuxt.config build property, but what's the implementations looks like?

**Comment by duc2019** [comment]
I resolved this issue by patch icons.

The steps are download this repository, remove unused icons, generate icons.js, and copy icons.js to node_modules.

``` shell
mkdir node_modules/_tmp
cd node_modules/_tmp
curl -L https://github.com/bootstrap-vue/bootstrap-vue/archive/refs/tags/v2.21.2.tar.gz -o bootstrap-vue.tar.gz
tar -xzf bootstrap-vue.tar.gz
cd bootstrap-vue-2.21.2
npm install --also=dev
mv node_modules/bootstrap-icons/icons node_modules/bootstrap-icons/icons_old
cd node_modules/bootstrap-icons/icons_old
mkdir -p ../icons
mv calendar.svg calendar-fill.svg chevron-bar-left.svg chevron-double-left.svg \
  chevron-up.svg chevron-down.svg chevron-left.svg chevron-right.svg circle-fill.svg \
  clock.svg clock-fill.svg dash.svg person-fill.svg plus.svg star.svg star-fill.svg \
  star-half.svg x.svg ./icons
cd ../../..
sh scripts/build.sh
cp src/icons/icons.js src/icons/plugin.js src/icons/icons.d.ts src/icons/package.json ../../bootstrap-vue/src/icons/
```

Icons listed in above are used by internal components of bootstrap-vue, if you need more icons include them to the command.

After optimize the bundle size is reduced about 500kb.

And I think this issue deserve to reopen, include 500kb unused resources in production app is really bad, even most frontend developers wont give a sh't of performance.

**Comment by luaz** [comment]
I believe the icons tree-shaking works most of the time, except under certain circumstances. For example, I found that if I include  `SkeletonPlugin`, the icons tree-shaking would fail, so I import `BSkeleton` component only and it works.

The following is my configuration using Nuxt.

```javascript
module.exports = {
  modules: ['bootstrap-vue/nuxt'],
  bootstrapVue: {
    components: ['BSkeleton', 'BIconSearch'],
    componentPlugins: [
      'NavbarPlugin', 
      'LayoutPlugin', 
      'ButtonPlugin', 
      // 'SkeletonPlugin' 
    ]
  }
}
```
Source: https://code.luasoftware.com/tutorials/vuejs/bootstrapvue-icons-import-specific-icon-only/

**Comment by ericchienvu** [comment]
I get same error : as it exceeds the max of 500KB. . I followed the instructions but it still doesn't work
