### ISSUE TITLE
Allow colspan and rowspan for <b-table>

### ISSUE THREAD

**Issue by v5s4k9** [bootstrap-vue/bootstrap-vue#5640]
Is it possible to add colspan and rowspan for b-table?

Even though b-table-simple is providing the colspan and rowspan feature we were in short of implementing sorting,pagination through b-table-simple.

It will be really helpful if you guys added this feature in the next release.

**Comment by jackmu95** [comment]
https://github.com/bootstrap-vue/bootstrap-vue/issues/4442#issuecomment-559833256
