### ISSUE TITLE
[collapsible] Transition styles not being added

### ISSUE THREAD

**Issue by fourpixels** [bootstrap-vue/bootstrap-vue#565]
I don't know what happened and when, but in master the transition classes of the collapsible are not being added at all. My guess is because javascript transitions are used and no class is added in side, but I'm not sure.

**Comment by fourpixels** [comment]
If I use 

```js
import {  bCollapse } from 'bootstrap-vue/lib/components';
export default {
  components: {
    bCollapse
  }
}
```
then the animation is present, but this prevents me from making a build (see #564). Behavior should be the same on both usages.

**Comment by alexsasharegan** [comment]
Now that #564 is resolved for you, is this still an issue?

**Comment by tmorehouse** [comment]
@fourpixels When I run a collapse in Chrome, and monitor via the console, I can see the c;lasses being added during the transition.

**Comment by tmorehouse** [comment]
Collapsible uses javascript transitions currently, and doesn't add in the `.collapsing` or `.collapse` classes.  Currently only the `.show` class is used.

**Comment by fourpixels** [comment]
Any news on that?

**Comment by tmorehouse** [comment]
NO changes to modal transition classes yet.

Are you relying on the intermediate transition classes for any styling?

**Comment by fourpixels** [comment]
Uhm, I guess so :) What other options I have? Sorry, haven't checked it recently..
