### ISSUE TITLE
 I cannot install the dependency. (404)

### ISSUE THREAD

**Issue by Oscaraag** [bootstrap-vue/bootstrap-vue#5650]
### Describe the bug

Hello, recently I am trying to install the dependency for a project and when installing with npm it throws a 404 error, I tried with npm and with Vue CLI, obtaining the same result, it says that it does not exist, I attach tests.

![image](https://user-images.githubusercontent.com/67101968/90039685-fa402600-dc94-11ea-8663-3862f9ec5d30.png)

Please Help. 👍

**Comment by jackmu95** [comment]
`vue-cli-plugin-bootstrap-vue` is not maintained by `boostrap-vue`.

**Comment by Hiws** [comment]
You can follow [these steps](https://bootstrap-vue.org/docs#using-module-bundlers) on the getting started page, to set it up yourself.
Doesn't require much work.

**Comment by Oscaraag** [comment]
Thanks for the support.
