### ISSUE TITLE
Close button in search is not working if used as a separate component

### ISSUE THREAD

**Issue by DebaPrasad14** [bootstrap-vue/bootstrap-vue#5652]
Hi, I have made a component of search form, When I use this component as standalone then close button in search is working fine but when I use this component in parent component then close is not workng. when I am saying close button I mean the close icon shown in below image

Here is my [codepen](https://codepen.io/kkdas202/pen/BaKjmZX?editors=1011)
![image](https://user-images.githubusercontent.com/30753467/90161438-bf331500-ddb0-11ea-80ad-ec52e463b7ad.png)

**Comment by Hiws** [comment]
What do you mean with `close` button?


Sidenote, don't use `.trim` on `v-model` as it isn't properly supported on custom components.
Instead use the `trim prop`
`<b-input v-model.trim="text"> ` -> `<b-input trim v-model="text">`

**Comment by DebaPrasad14** [comment]
@Hiws thank you so much for your suggestion regarding trim, Definitely i will keep that in mind. And i have updated mu previous comment plz check.

**Comment by Hiws** [comment]
If you use `<input type="search">` does it then work?

**Comment by DebaPrasad14** [comment]
NO, used that but no success.  
I did like `<Search @keyup.enter.native="findTextOccurances($event.target.value)"  />`

**Comment by Hiws** [comment]
I don't see the relation between that code and the close button not working.
Can you create a full reproduction that shows the problem?

**Comment by DebaPrasad14** [comment]
@Hiws plz find [codepen](https://codepen.io/kkdas202/pen/BaKjmZX?editors=1011).

**Comment by Hiws** [comment]
Since it doesn't work with a native `<input>` element, i don't think there's anything we can do to change this behavior.
Most likely a browser bug, if i had to guess.

You could try asking for help on the Vue discord server.
<https://discord.gg/vue>

**Comment by DebaPrasad14** [comment]
okay, thanks
