### ISSUE TITLE
Safari: Linked Avatars scale on hover bug

### ISSUE THREAD

**Issue by robinwolf** [bootstrap-vue/bootstrap-vue#5655]
You have to use a Safari browser. You can see the bug also on the Bootstrap-Vue page if you hover the linked avatar cat list entry:
https://bootstrap-vue.org/docs/components/avatar#button

Problem:
If an avatar image is a link, than it will be added a nice little transition on the image to scale up a bit:
`b-avatar.btn:not(:disabled):not(.disabled):hover .b-avatar-img img, .b-avatar[href]:not(:disabled):not(.disabled):hover .b-avatar-img img {
-webkit-transform: scale(1.15);
transform: scale(1.15);
}`

Unfortunately this animation will cause a back and forth between a round and not round border-radius on Safari browsers.

Is there any work around or bugfix for that?

**Comment by jackmu95** [comment]
Closed by #5675.

**Comment by robinwolf** [comment]
Thank you for your efforts, @jackmu95 Jacob!
Besten Dank 👍
