### ISSUE TITLE
Modal target other than document.

### ISSUE THREAD

**Issue by bkbillma** [bootstrap-vue/bootstrap-vue#5656]
### Is your feature request related to a problem? Please describe...

I am bundling a vue project into a web component.  I want all css/js self contained.  But when a modal is opened, it is appended to the document (outside of my web component) so the css is not applied.

### Describe the solution you'd like

Allow an option to pass which element to append to.

### Describe alternatives you've considered

I've considered listening to $root bv show and moving it myself but I imagine this will cause issues.  I've considered making a bundler to include the needed css outside of my web component but I don't like that idea.

**Comment by Hiws** [comment]
You could use the `static` prop, and it will be rendered where it's placed in the document.
<https://bootstrap-vue.org/docs/components/modal#lazy-loading-and-static-modals>

**Comment by bkbillma** [comment]
> You could use the `static` prop, and it will be rendered where it's placed in the document.
> https://bootstrap-vue.org/docs/components/modal#lazy-loading-and-static-modals

Thanks, that seems to have done it.  I did actually successfully move it in the dom previously but didn't love that solution.  Oddly clicking out of the modal isn't closing it in this formation (same code all runs not as a web component in our full site and closes fine there).

Now to go and see if bvToast supports something similar.

**Comment by Hiws** [comment]
While I don't think it's possible to do with `$bvToast`, you can create your own `toasts on demand`, by using something like Vuex or an Event bus combined with the `<b-toast>` component and `static` prop which does the same as on `<b-modal>`

Very rough example:
<https://codepen.io/Hiws/pen/YzyeREa>

**Comment by bkbillma** [comment]
The static prop does not fully work inside of a web component because .modal-open is still applied to the body rather than a target element (like the root element of the web component).

Without .modal-open some sytles are missing and you can't close the modal by clicking out of it.

**Comment by bkbillma** [comment]
That said, this might be a bootstrap request first then bootstrap vue...

**Comment by bkbillma** [comment]
Going to reclose this and I opened the ticket with bootstrap instead.

https://github.com/twbs/bootstrap/issues/31509
