### ISSUE TITLE
Table cell template for multiple fields

### ISSUE THREAD

**Issue by ianef** [bootstrap-vue/bootstrap-vue#5660]
I would like to be able to specify several fields in a cell template. For large tables with many columns I am frequently adding a lot of duplicated templates with just the field name changed, or adding formatter field attributes to reduce code, the latter helps but it is disconnected from the table and I do not like creating markup using strings which makes it less readable.

I would like to be able to define one template for several table fields as follows:
```
<template v-slot:cell(field1, field2, field3...)="data">
    <my-field-markup>{{ data.value }}</my-field-markup>
</template>
```

As I previously stated, formatter functions can be used to reduce template code but it does not provide a clean way to define markup for fields. I prefer to use formatter functions for simple transformations such as date and numeric formatting.

Being able to define a template for use in multiple fields would reduce the code size of some of my components enormously.

**Comment by Hiws** [comment]
You can use a `v-for` to define a template for multiple fields.

```html
<template v-for="field in ['field1', 'field2', 'field3']" v-slot:[`cell(${field})`]="{ value }">
  <my-field-markup>{{ data.value }}</my-field-markup>
</template>
```

**Comment by ianef** [comment]
Excellent @Hiws, I'm not sure why I didn't think or that! Hoorah for v-for, an amazing feature of Vue.

**Comment by ianef** [comment]
Actually I'm going to re-open this. Although the v-for loop does work, the syntax of it is quite messy particularly with the template literals, it's not an obvious and intuitive way of making this work. I can already hear the mumbling of contributors saying 'If you can make is work with native JS then why do we need this', well the syntax of my suggestion is simple and extremely readable in comparison.

**Comment by Hiws** [comment]
`v-slot` is a Vue directive, and not something we have control over.
So your suggestion for that is more suited for the [Vue repo](https://github.com/vuejs/vue/issues), and not here as we can't really do anything about it.
