### ISSUE TITLE
b-form-radio-group not acting properly when applying change event

### ISSUE THREAD

**Issue by malohtie** [bootstrap-vue/bootstrap-vue#5664]
### Describe the bug

when changing selected value using code it doesn't update the checked value in radio button if we select the nearest radio button but work if third o fourth element was selected before

### Steps to reproduce the bug

1. the first element is checked 
2. click on second radio button 
3. click back to the first element it wont update to the second radio button

### Versions

**Libraries:**

- BootstrapVue: latest
- Bootstrap: latest
- Vue: latest

### Demo link

https://jsfiddle.net/0w83b21m/3/

**Comment by Hiws** [comment]
You need to use `$nextTick` for something like this, to ensure data has been updated before you change it.

https://jsfiddle.net/rtnzdcf6/
