### ISSUE TITLE
Closing keyboard crash safari

### ISSUE THREAD

**Issue by puschie286** [bootstrap-vue/bootstrap-vue#5667]
### Describe the bug

When you are on a required input (on mobile/safari) and try to submit the empty input a tooltip is shown - if you try to close the keyboard with „done“ the browser crash 

### Steps to reproduce the bug

( IPhone 7 Plus / Safari )
0. create an example form with an input group and mark this input as required
1. Click on the input so the keyboard open
2. Click on the submit button so the tooltip is shown
3. Click a few times on „Done“ to close the keyboard
4. Click the login button again
5. Safari crash/close

### Expected behavior

Keyboard should close

### Versions

**Libraries:**

- BootstrapVue: 2.16.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- Device: iPhone 7 Plus
- OS: iOS 13.6
- Browser: Safari
- Version: [e.g. 70]

### Demo link

https://jsfiddle.net/u7ro2msd/

### Additional context

The tooltip has wrong offset
![61F68017-51D2-46A4-9B04-C86BB2E26050](https://user-images.githubusercontent.com/2429036/90637038-bf596780-e22b-11ea-96ca-52be4a0bc14a.jpeg)

**Comment by puschie286** [comment]
https://jsfiddle.net/u7ro2msd/

**Comment by Hiws** [comment]
Can you test it with a normal `<input>` and `<input class="form-control">` elements to see if the behavior is the same?

**Comment by puschie286** [comment]
you mean like this https://jsfiddle.net/3kzw8m2r/

**Comment by Hiws** [comment]
That's still `<b-form-input>`, and not a native `<input>`

**Comment by puschie286** [comment]
sry - forget to press save on jsfiddle
changed to nativ input, but same result

**Comment by Hiws** [comment]
Just for good measure, can you test this one too?
<https://jsfiddle.net/0uth9847/>

If this one still crashes, it must be a browser bug.

**Comment by puschie286** [comment]
yes still crash - i will report it to apple, thanks for clearify
