### ISSUE TITLE
Yarn link & webpack 2 & windows

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#568]
Is there a true working recipe to set up webpack2 to work with yarn-linked modules under windows?

**Comment by alexsasharegan** [comment]
Do you think there is any flag about following symbolic links in the windows node environment?

**Comment by mosinve** [comment]
I dont know.... if i just add yarn linked module to my project without mods to webpack.config -  i got an  errors.

**Comment by alexsasharegan** [comment]
So I haven't tried this yet myself, but it looks like this is a two step process: run `yarn link` inside your local copy of master, then run `yarn link bootstrap-vue` inside your app project. Is this how you tried this? https://yarnpkg.com/lang/en/docs/cli/link/

**Comment by mosinve** [comment]
yeah, this part is clear like a day ))

**Comment by alexsasharegan** [comment]
Okay. I'll have to give this a go from my Mac and see if this is a windows thing or not.

**Comment by alexsasharegan** [comment]
This is looking like a yarn issue. See https://github.com/yarnpkg/yarn/issues/1297 and a possible resolution https://github.com/yarnpkg/yarn/pull/3359. What version of yarn are you running?

**Comment by mosinve** [comment]
0.22. i'll try to use actual version.

BTW, the error i've got:

> ERROR in ../bootstrap-vue/node_modules/babel-runtime/core-js/symbol/iterator.js
> Module build failed: TypeError: D:/Dev/bootstrap-vue/node_modules/babel-runtime/core-js/symbol/iterator.js: Property value of ObjectProperty expected node to be of a type ["Expression","Pattern","RestElement"] but instead got null
>     at Object.validate (D:\Dev\reestrius_spa\node_modules\babel-types\lib\definitions\index.js:109:13)
>     at Object.validate (D:\Dev\reestrius_spa\node_modules\babel-types\lib\index.js:505:9)
>     at NodePath._replaceWith (D:\Dev\reestrius_spa\node_modules\babel-traverse\lib\path\replacement.js:176:7)
>     at NodePath._remove (D:\Dev\reestrius_spa\node_modules\babel-traverse\lib\path\removal.js:58:10)
>     at NodePath.remove (D:\Dev\reestrius_spa\node_modules\babel-traverse\lib\path\removal.js:30:8)
>     at PluginPass.CallExpression (D:\Dev\bootstrap-vue\node_modules\babel-plugin-transform-es2015-modules-amd\lib\index.js:42:12)
>     at NodePath._call (D:\Dev\reestrius_spa\node_modules\babel-traverse\lib\path\context.js:76:18)
>     at NodePath.call (D:\Dev\reestrius_spa\node_modules\babel-traverse\lib\path\context.js:48:17)
>     at NodePath.visit (D:\Dev\reestrius_spa\node_modules\babel-traverse\lib\path\context.js:105:12)
>     at TraversalContext.visitQueue (D:\Dev\reestrius_spa\node_modules\babel-traverse\lib\context.js:150:16)
>  @ ../bootstrap-vue/node_modules/babel-runtime/helpers/typeof.js 3:4-115
>  @ ../bootstrap-vue/dist/bootstrap-vue.esm.js
>  @ ./src/main.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by mosinve** [comment]
Updated yarn - error gone.

**Comment by alexsasharegan** [comment]
Does that mean it's finally up and running?

**Comment by mosinve** [comment]
errr.... 
I have another issues with current release
When i run dev, build successful, but at browser i get:
> Uncaught SyntaxError: Unexpected token :
>     at Object.<anonymous> (app.js:2594)
>     at __webpack_require__ (app.js:660)
>     at fn (app.js:86)
>     at eval (eval at <anonymous> (app.js:2137), <anonymous>:13:72)
>     at Object.<anonymous> (app.js:2137)
>     at __webpack_require__ (app.js:660)
>     at fn (app.js:86)
>     at Object.<anonymous> (app.js:3977)
>     at __webpack_require__ (app.js:660)
>     at app.js:709

`Object.<anonymous> (app.js:2594)` - is Tether chunk

When I try to build prod, it fails with error:

> ERROR in static/js/vendor.ec31bc6067c9f6bbcc83.js from UglifyJs
> Unexpected token punc «:», expected punc «,» [./~/bootstrap-vue/dist/bootstrap-vue.esm.js:2,2932][static/js/vendor.ec31bc6067c9f6bbcc83.js:33212,3119]

My webpack.config.js babel part is:

            {
                test: /\.js$/,
                loader: 'babel-loader',
                include: [resolve('src'), resolve('test'), path.resolve(__dirname, 'node_modules/bootstrap-vue')],
            },

linked @master works well....

**Comment by mosinve** [comment]
If i import `bootstrap-vue/lib` then at prod build i get:

> ERROR in static/js/vendor.127b670e9c8c32fe1aec.js from UglifyJs
> Unexpected token: punc (() [./~/bootstrap-vue/lib/mixins/form.js:3,0][static/js/vendor.127b670e9c8c32fe1aec.js:16701,18]

**Comment by tmorehouse** [comment]
THis in master, or v0.17.1

**Comment by mosinve** [comment]
v0.17.1

**Comment by mosinve** [comment]
Master works well

**Comment by tmorehouse** [comment]
So does the latest master work?

**Comment by mosinve** [comment]
Yeah...  it works ...

**Comment by tmorehouse** [comment]
OK, that is a good sign. I think v0.18.0 will be released soon.

**Comment by mosinve** [comment]
I hope)

**Comment by mosinve** [comment]
I think theres problem not in library itself, but in build tools config... 
When was uglify-harmony was switched to uglify-es at BV?

**Comment by mosinve** [comment]
Whew....  more detailed study of package.config.js showed that was installed BV 0.16 not latest npm build... 0.17.1 seems to work.

**Comment by mosinve** [comment]
maybe someone knows...  is there some more automatic way of updating deps at yarn or npm?

**Comment by mosinve** [comment]
npm install -g npm-check-updates

**Comment by alexsasharegan** [comment]
Yarn has a cool `yarn upgrade-interactive` that I use a lot.

**Comment by mosinve** [comment]
Yep, thats cool feature)) Thanks a lot  :)

2017-07-03 8:34 GMT+03:00 Alex Regan <notifications@github.com>:
