### ISSUE TITLE
table toggleDetail outside

### ISSUE THREAD

**Issue by yoyoys** [bootstrap-vue/bootstrap-vue#5686]
### Is your feature request related to a problem? Please describe...

Currently `toggleDetail` function is only accessible to `v-slot:cell`, but if you want to bind event like `row-dblclicked`, to support dblclick toggle, it can't be afford.

### Describe the solution you'd like

Add a global event like `bv::toggle-detail::table` or good ref to do this.

### Describe alternatives you've considered

For now add `_showDetails` is only way to implement this, but it has too much work.

### Additional context

[Table - row-details-support ](https://bootstrap-vue.org/docs/components/table#row-details-support)

**Comment by Hiws** [comment]
You mention using `_showDetails` and that it's too much work.
But i don't quite see how.

It only takes a few lines to implement your own function to toggle details

<https://codepen.io/Hiws/pen/vYGgzjj>
