### ISSUE TITLE
Message box advanced usage

### ISSUE THREAD

**Issue by farshadfahimi** [bootstrap-vue/bootstrap-vue#5687]
I read the documentation about the `Message box` but some times the user need to change the footer items

for example in the message box footer I want to change the position of `cancel` and `ok` buttons. but there is noting about it.

I need to know is it possible to do this or not

**Comment by Hiws** [comment]
The footer utilizes flex, meaning you can use Bootstrap's [Flex Utilities](https://getbootstrap.com/docs/4.5/utilities/flex/) to customize the position of the footer buttons, by passing the utility classes to `footerClass`.

```js
this.$bvModal.msgBoxConfirm('Some Message', {
  footerClass: 'flex-row-reverse'
})
```
