### ISSUE TITLE
Possibility to attach element to top of b-table

### ISSUE THREAD

**Issue by sebastian-raubach** [bootstrap-vue/bootstrap-vue#5689]
### Is your feature request related to a problem? Please describe...

I'm trying to show a dot icon that is absolutely positioned above a relative position table. For this to work, the dot has to be a direct child of the `<table>` element. However, there doesn't appear to be a slot that can be used for this and if I simply place my component inside the `<b-table>` it doesn't show up at all.

### Describe the solution you'd like

Either a slot for "beginning of body" or some other way to place an element there.

### Describe alternatives you've considered

Using a simple table, but that'd mean I'd have to implement all the functionality that the actual `b-table` offers.

**Comment by Hiws** [comment]
I'm 100% sure what it is you're trying to do, but here's 2 ways of doing what i *think* you're trying to do.

https://codepen.io/Hiws/pen/VwaPELG

**Comment by sebastian-raubach** [comment]
Sorry if I didn't explain it properly. Say I want to position an icon at 30% table width and 70% table height. This is total width and height, even if the table scrolls, which makes me think I have to position it inside the table body?

**Comment by Hiws** [comment]
The second example in the codepen should do that i think.

**Comment by sebastian-raubach** [comment]
Yes, I think you're right. Thank you!
