### ISSUE TITLE
<b-button variant="foo"> uses original bootstrap color, instead of variable override.

### ISSUE THREAD

**Issue by JU12000** [bootstrap-vue/bootstrap-vue#5691]
### Describe the bug

`<b-button>` variant does not inherit colors from the `$theme-colors` bootstrap scss variables like it is supposed to.

### Steps to reproduce the bug

1. Create a fresh project
2. Create `theme.scss` and override `$theme-colors` per [documentation](https://bootstrap-vue.org/docs/reference/theming) e.g.
```
$theme-colors: (
  primary: #2D3047;
);
```
3. In the template html, create `<b-button variant="primary">Foo</b-button>`
4. Observe that the color of the button is not `#2D3047` but instead `#007BFF`

### Expected behavior

When creating a `<b-button>` with a variant and `$theme-colors` overridden, the variant of `<b-button>` should reflect the new `$theme-colors` color, not the original bootstrap color.

### Versions

**Libraries:**

- BootstrapVue: 2.12.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Desktop
- OS: Windows 10 LTSC
- Browser: Firefox
- Version: 79

**Comment by Hiws** [comment]
Did you check the DOM to see if `btn-primary` is applied to the rendered `<button>`?
If it is correctly applied, there's most likely something wrong with your SCSS not being compiled correctly.

**Comment by JU12000** [comment]
Yes, the DOM correctly applies the `btn-primary` class to the `<button>`.
My `theme.scss` file:
```
$theme-colors: (
  primary: #2D3047,
  success: #0FBD72,
  danger: #AE2029,
  light: #F6F5F3,
  dark: #23201B,
);

@import '~bootstrap/scss/bootstrap.scss';
@import '~bootstrap-vue/src/index.scss';

html body {
  background-color: var(--light);
  color: var(--dark);
}
```

I can also confirm that calling `var(--light)` in the `html body` rule works, and this is being imported into my `main.js` like so:
```
import { BootstrapVue, IconsPlugin } from 'bootstrap-vue'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
import '../scss/theme.scss'
```

So I'm not sure how the SCSS would be incorrectly compiling this.

**Comment by Hiws** [comment]
You are importing both bootstrap `CSS` and `SCSS`.
You should only import one or the other.

**Comment by JU12000** [comment]
Hmm, yes. It seems I can't read...

Thank you.

**Comment by JU12000** [comment]
Sorry to re-open this, but I noticed something else strange.

Importing just the scss now means tha the `.btn-primary` class is correct.
However, in the DOM the `.btn-primary` class with the correct colors is being overwritten by a `.btn-primary[data-v-7ba5bd90]` class with the old colors.

Any idea why this is?

**Comment by Hiws** [comment]
Are you importing anything into a scoped style tag? `<style scoped>`

**Comment by JU12000** [comment]
Thank you, removing the scoped style worked. I was misunderstanding how scoped styles worked, but that's the fault of the vue documentation, or maybe my reading comprehension.

Thank you for your help.

**Comment by Hiws** [comment]
> Thank you, removing the scoped style worked. I was misunderstanding how scoped styles worked, but that's the fault of the vue documentation, or maybe my reading comprehension.
> 
> Thank you for your help.

You shouldn't import Bootstrap into your components in the first place, especially not since you're importing it (from the looks) in your apps entry point.
If you Bootstrap into your components it be compiled into your app multiple times increasing the size of your bundle.

If you're importing it into your component to access your `SCSS` variables, you can do it in another way.

If you're using `Vue-CLI`, you can try and follow this:
<https://stackoverflow.com/a/60953077/8397974>

**Comment by JU12000** [comment]
That's a good tip, but it prevents me from being able to use @extend directives in `<style lang="scss">` tags.

Any ideas for this? All I've seen is to `@import "bootstrap"` at the top of the tag.

**Comment by Hiws** [comment]
I've never used **@extend**, so can't say for sure.
But you can refer to the link if you only need `mixins`, `functions` and `variables` in your SFC's.
