### ISSUE TITLE
<b-form-checkbox> change event payload isn't an array when v-model is bound to an array

### ISSUE THREAD

**Issue by zcoop98** [bootstrap-vue/bootstrap-vue#5697]
### Describe the bug

The `<b-form-checkbox>` `change` event payload is not an array when the `v-model` of the checkbox is bound to an array, even though it appears it should be. The documentation explicitly states that when a checkbox's `v-model` is bound to multiple checkboxes, the event payload for `change` should be an array.

I've observed this behavior regardless of whether the multiple checkboxes are individual components or a single one bound to an options array.

### Steps to reproduce the bug

[JSFiddle Link](https://jsfiddle.net/1n4pb3sg/)

1. Create multiple checkboxes such that they're bound to the same "selected" array
2. Click a checkbox and observe the `change` and `input` events for the action (displayed and logged to console in fiddle)
3. Observe that even though the `v-model` is bound to an array, the `change` event is only a single value (or `null`)

### Expected behavior

From [the documentation for b-form-checkbox](https://bootstrap-vue.org/docs/components/form-checkbox#comp-ref-b-form-checkbox-events): 
> * Event: 
>    * `change`
> * Arguments:
>   * `checked` - Value of checkbox(es). When bound to multiple checkboxes, value will be an array.
> * Description:
>   * Emitted when selected value(s) is changed due to user interaction

Based on the arguments line "When bound to multiple checkboxes, value will be an array," I'm expecting the change event to contain the array of selected values from the `v-model`, just like `input` provides.

### Versions

**Libraries:**

- BootstrapVue: 2.11.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

Also tested this on the Bootstrap-Vue website itself, and got identical results, so this applies to the versions running on there too.

**Environment:**

- Device: Windows
- OS: Windows 10
- Browser: Chrome
- Version: 84.0.4147.135

### Demo link

As above, [JSFiddle Link](https://jsfiddle.net/1n4pb3sg/)

### Additional context

The _exact_ same language is used on the page to describe the `input` event, word for word, and `input` behaves exactly as expected according to the language used.

My use case involves rendering checkboxes in the `cell(x)` slot of a `b-table`, where checkboxes in multiple rows of the table are bound to the same array. Using `@change` to trigger my handler function doesn't work for me, since the `change` event doesn't provide the full values array, while `input` does. I would use `input`, but toggling one checkbox triggers the `input` event for _all_ visible checkboxes in the table, firing my handler for each, which is undesirable. 

I tried calling my handler on `change` with the `v-model` bound array directly (eg. `@change="handler(selectedArray)"`), but the change event fires *before* `v-model` has been updated, leaving me with stale data in my handler.

Let me know if I can clarify anything, or if I'm just misunderstanding something!

**Comment by Hiws** [comment]
I'm not sure whether this is a problem with the docs or with the code, will have to look into that.
But regarding your use-case, maybe a watcher is what you need.

It will run when your `selected` array changes, and should only do it once.


<https://jsfiddle.net/L5as30oy/1/>

**Comment by zcoop98** [comment]
Alrighty 👍

As for the workaround, I don't believe a watcher will work in this case for now, since the selected arrays (plural for multiple tables) are actually nested within another array in my case:

![image](https://user-images.githubusercontent.com/8434006/91321532-55d5dd80-e784-11ea-875b-6783af93741e.png)

This is why I'm trying to use the event as described, since the `input` event payload contains the contents of that nested array directly. I don't *think* I can watch/ detect changes in the nested array without `/deep/` watching the entire parent array.
