### ISSUE TITLE
navbar not displayed properly

### ISSUE THREAD

**Issue by maple3142** [bootstrap-vue/bootstrap-vue#570]
I use the example in [here](https://bootstrap-vue.github.io/docs/components/navbar), but it doesn't displayed properly.
![image](http://i.imgur.com/BXfHYXd.jpg)

src/main.js
```javascript
import Vue from 'vue';
import BootstrapVue from 'bootstrap-vue';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';
import '../index.html';/* index.html hot reload */
Vue.use(BootstrapVue);

var app=new Vue({
	el: '#navbar'
});
```
index.html
```html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>vue bootstrap</title>
</head>
<body>
  <div id="navbar">
    <b-navbar toggleable type="inverse" variant="success">
      <!-- same as example-->
    </b-navbar>
  </div>
  <script src="dist/bundle.js"></script>
</body>
</html>
```

**Comment by Scalpel78** [comment]
I'm seeing the same behavior in my project.

**Comment by tmorehouse** [comment]
Make sure the bootstrap-vue.css is being loaded after bootstrap.css

**Comment by Scalpel78** [comment]
In my main.js I've got these two lines

      import 'bootstrap/dist/css/bootstrap.css'
      import 'bootstrap-vue/dist/bootstrap-vue.css'

Will the order of these two lines also control the loading order?

**Comment by tmorehouse** [comment]
Depending on the bundler (and version of bundler) you are using, they may not.

Check out issue #422

**Comment by Scalpel78** [comment]
Thanks for the tips. It's not working yet, but I'll keep trying.

It would be nice if the documentation had an example on how to include bootstrap-vue to the project generated by 

      vue init webpack my-project

**Comment by tmorehouse** [comment]
Yeah, there is another similar issue on that topic (#145) which has been open for a while.

If you do find any answers/solutions, please post them here or one of the related issues.

**Comment by tmorehouse** [comment]
@maple3142  @Scalpel78 

Release v0.18.0 is now available. Try it out and see if you still have this issue or if you run into any other issues.
