### ISSUE TITLE
b-table item tdAttr support

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#5704]
### Is your feature request related to a problem? Please describe...

`tdAttr` works fine for `b-table` fields (column definition)
https://codesandbox.io/s/k1ov2w2463?file=/src/App.vue

We also need to set custom attributes for each td item cell (record data), and have the result as
```<td title='custom title' data-id='customid'>...</td>```

### Describe the solution you'd like

when defining a cell, accept the special property `tdAttr` (or `_tdAttr`), which will set the items as attributes on `td` element, exactly like it works for fields.

### Describe alternatives you've considered

custom renderer which adds a `span` with desired attrs. All `td`s will have a `span` in them though, which won't even represent the whole cell. We need to be able to attach events to `td`s and recognize which cell was clicked by custom data attributes.

**Comment by Hiws** [comment]
This is already possible by passing a function to `tdAttr`. The function is passed the that cells `value`, `key` and `item`.
You can read more in the `tdAttr` description:
<https://bootstrap-vue.org/docs/components/table#field-definition-reference>

Example:
https://codepen.io/Hiws/pen/poyPwRr

**Comment by mariusa** [comment]
Ah, thanks Hiws! I thought that has effect only on 'fields', but I see it working now on items too. Thanks!
