### ISSUE TITLE
Make focus management in sidebar optional

### ISSUE THREAD

**Issue by andrei-gheorghiu** [bootstrap-vue/bootstrap-vue#5707]
First off, a huge thank you for the time and effort you put into developing this lib. It's impressive, to say the least.

### Is your feature request related to a problem? Please describe...

I'm currently developing an app where I have very specific accessibility needs for people with disabilities. The sidebar is unusable, because of its "accessibility". It steals the focus in cases where this is detrimental for the experience of people using screen readers and/or for people with impaired movement/typing ability. 

While for many apps the default behavior is useful, I believe you should allow developers (and UX designers) to decide when to use that behavior and when not to, by providing a config option to disable focus management altogether for a sidebar. Enforcing accessibility can actually be quite disabling and detrimental to accessibility.

The only option I currently have is to clone your component and remove focus management. I doubt that's how you meant your library to be used.

### Describe the solution you'd like

Just provide a custom prop to disable focus management altogether.
_________

As a side-note, even if you do add this feature in, it probably won't be shipped in time for my current app, So I'll have to poke around in source code anyway. 
If there's nothing I don't understand, I might PR this feature. If, of course, you welcome it. But I don't want to promise anything before I look at the code.

Again, big thank you. Keep up the good work!

**Comment by jackmu95** [comment]
`BModal` supports a `noEnforceFocus` property to give the user control over the auto-focus behavior.
We should support this on the `BSidebar` component as well.
