### ISSUE TITLE
Animated icons aren't animated

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#5712]
Note: this is not a request to implement animation, if not supported by Bootstrap.
`<b-spinner>` works great, I personally don't need other animation.

### Describe the bug

https://bootstrap-vue.org/docs/icons/#animated-icons

None of the icons there are animated.

### Steps to reproduce the bug

`<b-icon-arrow-clockwise animation="spin-pulse"></b-icon-arrow-clockwise>`

### Expected behavior

Animated / rotating icon

### Versions

**Libraries:**

- BootstrapVue: 2.16.0
- Bootstrap: 4.5.x
- Vue: 2.x.x

**Environment:**

- Device: Laptop 
- OS: Fedora
- Browser:  Chrome
- Version: 85

**Comment by Hiws** [comment]
Works fine for me on Chrome 85, Windows.

Do you have `reduced motion` enabled?

**Comment by mariusa** [comment]
Hmm, I do have in my linux desktop a setting to disable animations. Probably this is influencing. Thanks for confirming!

**Comment by mariusa** [comment]
Note: b-spinner works fine and hopefully will never be influenced by `reduced motion`
