### ISSUE TITLE
How can I remove `icons.js` from the project

### ISSUE THREAD

**Issue by evestorm** [bootstrap-vue/bootstrap-vue#5713]
![image](https://user-images.githubusercontent.com/18142851/91673823-8644bf80-eb68-11ea-87d7-92328819a6cf.png)

I found that `icons.js` occupies a large part of the resources. Is there any way to not load this file?
Because I want to reduce the size of the package as much as possible

P.S. I tried to use some components in the form of Vue plugins, but I found it would still be loaded:

```js
import { LayoutPlugin } from "bootstrap-vue";
Vue.use(LayoutPlugin);
```

Hope you guys can answer my confusion.

**Comment by Hiws** [comment]
`icons.js` should only be imported if you import the `IconsPlugin`.
Are you sure you don't have that anywhere?

I tried creating a vue-cli project, and importing the single plugin you listed.
```js
import { LayoutPlugin } from "bootstrap-vue";
Vue.use(LayoutPlugin);
```
and this was the result after building the project.
![chrome_7jSYoFIlVw](https://user-images.githubusercontent.com/7057431/91700010-767fa800-eb75-11ea-8e11-171ba27b5d19.png)


Could you provide a full list of what you're importing?

**Comment by evestorm** [comment]
Thank you for your patient reply!

I tried to recreate a pure vue-cli3 project. Below are all dependencies and imported files in my project:

> package.json

```json
{
  "name": "bootstrap-vue-demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "analyzer": "use_analyzer=true npm run serve"
  },
  "dependencies": {
    "bootstrap": "^4.5.2",
    "bootstrap-vue": "^2.16.0",
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.5.0",
    "@vue/cli-service": "^4.5.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11",
    "webpack-bundle-analyzer": "^3.8.0"
  }
}
```

> vue.config.js

```js
const webpack = require("webpack");
const path = require("path");

module.exports = {
	publicPath: "/",
	outputDir: "dist",
	assetsDir: "",
	productionSourceMap: false,
	filenameHashing: true,
	chainWebpack: (config) => {
		config
			.plugin("webpack-bundle-analyzer")
			.use(require("webpack-bundle-analyzer").BundleAnalyzerPlugin);
	},
};
```

> main.js

```js
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'


import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-vue/dist/bootstrap-vue.css";

import { LayoutPlugin } from "bootstrap-vue";

// Install BootstrapVue
Vue.use(LayoutPlugin);

Vue.config.productionTip = false

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app')

```

But the previous problems will still occur:

![image](https://user-images.githubusercontent.com/18142851/91707929-20315a00-ebb3-11ea-9105-3112877d0d02.png)

Looking forward to your reply!

**Comment by Hiws** [comment]
`"analyzer": "use_analyzer=true npm run serve"`

`npm run serve` launches a development environment without any tree shaking or minification.
You should only analyse a production build.

You can do that by using the following script `"build:report": "vue-cli-service build --report",`.
This will build your project into the `dist` folder, and generate a `report.html` file.

Here's the steps i did when trying to reproduce it (i used `yarn`, but `npm` should be the same result).

#### cmd
```bash
# @vue/cli 4.5.4
vue create project-name
# I picked standard vue 2 settings, nothing custom.
cd project-name
yarn add bootstrap bootstrap-vue
```

#### package.json (added the script i mentioned above, everything else is default)
```
{
  "name": "bootstrap-vue-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "build:report": "vue-cli-service build --report",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "bootstrap": "^4.5.2",
    "bootstrap-vue": "^2.16.0",
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  }
}
```

#### main.js
```js
import Vue from 'vue'
import App from './App.vue'
import { LayoutPlugin } from "bootstrap-vue";

import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-vue/dist/bootstrap-vue.css";

Vue.use(LayoutPlugin)

Vue.config.productionTip = false

new Vue({
  render: h => h(App),
}).$mount('#app')
```

#### App.vue (testing to ensure the LayoutPlugin is installed correctly)
```html
<template>
  <div id="app">
    <b-container>
      <b-row>
        <b-col>
          Col 1
        </b-col>
        <b-col>
          Col 2
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>
```

#### cmd
```bash
yarn build:report
./dist/report.html
```

**Comment by evestorm** [comment]
Thank you so much for your help i really appreciate it!

**Comment by phil-w** [comment]
I'm having this same problem, with a large system now under **Webpack 5** for some time. I  build directly from bootstrap-vue/src so I don't include what I don't use. via `'bootstrap-vue$': 'bootstrap-vue/src/index.js'` and I don't use the "IconsPlugin", but I pull in individual icons now and then. I have this massive icons.js lump in the middle of my common files, where it should not be.

I stuck a "Webpack IgnorePlugin" in my build to try to suppress icons.js with it. I made it log stuff so I can see that the "resource" name is "/icons/plugin", and it's being pulled in by "context" E:\... \node_modules\bootstrap-vue\src. I can suppress it, but then my program fails to run with the error that it's missing... this icons.js file I don't use.

Sure enough, if I look in bootstrap-vue/src/index.js, the file I'm aliasing to as above, there is:

```
// Webpack 4 has optimization difficulties with re-export of re-exports,
// so we import the components individually here for better tree shaking
//
// Webpack v5 fixes the optimizations with re-export of re-exports so this
// can be reverted back to `export * from './table'` when Webpack v5 is released
// See: https://github.com/webpack/webpack/pull/9203 (available in Webpack v5.0.0-alpha.15)

// -- Export Icon components and IconPlugin/BootstrapVueIcons ---
// export * from './icons'
export { IconsPlugin, BootstrapVueIcons } from './icons/plugin'
export { BIcon } from './icons/icon'
export { BIconstack } from './icons/iconstack'
// This re-export is only a single level deep, which
// Webpack 4 (usually) handles correctly when tree shaking
export * from './icons/icons'
```

None of this has changed recently in your repo, although the comments there look like they predate Webpack 5.

I probably missed something. So far, I can "ignore" the icons.js thing but the result crashes at runtime as it can't find the damned thing. I will try to "stub it out" with some other Webpack 5 plugin, as I reckon I can write a stub which is smaller than 100k zipped! 

Anyone got any ideas on this please?

**Comment by phil-w** [comment]
Well I stubbed it out with a Webpack 5 alias of "false", which gets that massive glob of icons out of my production build. 
![1173](https://user-images.githubusercontent.com/4639007/111974369-3ffc8100-8af7-11eb-8797-98896876978f.jpg)

I don't know how it gets in, but that's a quick hack to stop it happening at least.

**Comment by rozman50** [comment]
I did a very ugly hack, which gets rid of icons in build for production process.

I'm using bootstrap-vue@2.21.1 and bootstrap@4.6.0 and webpack 4

Bootstrap-vue internally uses its icons in few packages: (maybe I forgot to list some)
```
esm\components\calendar\calendar.js
esm\components\form-btn-label-control\bv-form-btn-label-control.js
esm\components\form-datepicker\form-datepicker.js
esm\components\form-rating\form-rating.js
esm\components\form-spinbutton\form-spinbutton.js
esm\components\form-timepicker\form-timepicker.js
esm\components\sidebar\sidebar.js
esm\components\time\time.js
src\components\avatar\avatar.js
```

I tried removing icons.js completely, but this breaks build as bootstrap-vue wants those icons for internal components, but they are gone.

All SVGs for icons (around 1200 icons, ~600kb) are written in **bootstrap-vue\esm\icons\icons.js**, so before production build I run bash script with regex, that deletes all lines (so icon definitions), except for those used internally.

Those icons are: 
```
BIconCalendar
BIconCalendarFill
BIconChevronBarLeft
BIconChevronDoubleLeft
BIconChevronDown
BIconChevronLeft
BIconChevronUp
BIconCircleFill
BIconClock
BIconClockFill
BIconDash
BIconPlus
BIconStar
BIconStarFill
BIconStarHalf
BIconX
```

Bash script:
**remove-icons-from-bootstrap-vue.sh**
```
# Regex explanation
# '15,$' - ignore first 15 lines and go until end
# '\bBIconCalendar\b' - \b in front and back -> Word must match completely, __BIconCalendar, BIconCalendar__, __BIconCalendar__ would not match
# \bBIconCalendar\b\|\bBIconCalendarFill\b - pipe (' | ') -> OR (match BIConCalendar or BBIconCalendarFill)
# !d - (at the end) - delete line that matches criteria
sed -i -e '15,${/\bBIconCalendar\b\|\bBIconCalendarFill\b\|\bBIconChevronBarLeft\b\|\bBIconChevronDoubleLeft\b\|\bBIconChevronDown\b\|\bBIconChevronLeft\b\|\bBIconChevronUp\b\|\bBIconCircleFill\b\|\bBIconClock\b\|\bBIconClockFill\b\|\bBIconDash\b\|\BIconPersonFill\b\|\bBIconPlus\b\|\bBIconStar\b\|\bBIconStarFill\b\|\bBIconStarHalf\b\|\bBIconX\b/!d}' node_modules/bootstrap-vue/esm/icons/icons.js

# removing icons from plugin.js is just for silencing WARNING 
# ex. "export 'BIconXCircleFill' was not found in './icons'
# functionality for removing icons and reducing size is in icons.js
#
# !!! WARNING !!!
# this regex isn't working completely, as it sometimes cuts in the middle of file
# from line 60 to 630 is working safely, but it's not deleting all lines that contains icons
# that's why I'm not executing this script 
# sed -i -e '60,630{/\bBIconCalendar\b\|\bBIconCalendarFill\b\|\bBIconChevronBarLeft\b\|\bBIconChevronDoubleLeft\b\|\bBIconChevronDown\b\|\bBIconChevronLeft\b\|\bBIconChevronUp\b\|\bBIconCircleFill\b\|\bBIconClock\b\|\bBIconClockFill\b\|\bBIconDash\b\|\BIconPersonFill\b\|\bBIconPlus\b\|\bBIconStar\b\|\bBIconStarFill\b\|\bBIconStarHalf\b\|\bBIconX\b/!d}' node_modules/bootstrap-vue/esm/icons/plugin.js
```

And then in **vue.config.js** I'm executing script on production build with package **webpack-shell-plugin-next** [Github URL to package](https://github.com/s00d/webpack-shell-plugin-next). (Note that webpack 4 needs 1.* and webpack 5 needs 2.*)

**vue.config.js**
```
const WebpackShellPluginNext = require('webpack-shell-plugin-next')

// if it's a production build, then remove icons,
// otherwise execute empty function
const removeIconsOnProductionBuild = (process.env.NODE_ENV === 'production')
  ? new WebpackShellPluginNext({
    onBuildStart: {
      scripts: [
        'echo "--- DELETING icons FROM bootstrap-vue icons.js ---"',
        'bash remove-icons-from-bootstrap-vue.sh'
      ],
      blocking: true,
      parallel: false
    }
  }) : () => {}

module.exports = {
    ...
  configureWebpack: {
    plugins: [
      // bootstrap-vue adds icons.js, which is 600kb after being bundled (for production), even though, icons aren't used anywhere.
      // on production build, regex command is executed on 'node_modules/bootstrap-vue/esm/icons/icons.js', where icons are defined,
      // which removes all icons expect few, that are used internally by bootstrap in calendar, time, avatar,...
      removeIconsOnProductionBuild
    ]
  }
  ...
}

```

Two reports generated, one with bash script that removes icons and another that doesn't. 

![report_no_icons](https://user-images.githubusercontent.com/6508668/147910123-15f89edd-efa3-40c4-a334-69f772ce1637.png)

![report_with_icons](https://user-images.githubusercontent.com/6508668/147910128-8c2d0796-a166-4f80-b05c-0b59fcad45db.png)

**Comment by luaz** [comment]
I believe it the icons tree-shaking works most of the time, except under certain circumstances. For example, I found that if I include  `SkeletonPlugin`, the icons tree-shaking would fail, so I import `BSkeleton` component only and it works.

The following is my configuration using Nuxt.

```javascript
module.exports = {
  modules: ['bootstrap-vue/nuxt'],
  bootstrapVue: {
    components: ['BSkeleton', 'BIconSearch'],
    componentPlugins: [
      'NavbarPlugin', 
      'LayoutPlugin', 
      'ButtonPlugin', 
      // 'SkeletonPlugin'
    ]
  }
}
```
Source: https://code.luasoftware.com/tutorials/vuejs/bootstrapvue-icons-import-specific-icon-only/
