### ISSUE TITLE
Typescript + Vue 3 support

### ISSUE THREAD

**Issue by Fazendaaa** [bootstrap-vue/bootstrap-vue#5718]
### Steps to reproduce the bug

1. Clone the [NDSProject/front](https://github.com/NDSProject/front) project
2. Run: `make` -- runs `docker-compose up --build` under the hood
3. In [this](https://github.com/NDSProject/front/blob/866121909bd49e077f4a99cad73f414946deb134/src/main.ts#L2) line it's where the following error occurs:
```shell
 warning  in ./node_modules/bootstrap-vue/src/utils/vue.js

"export 'default' (imported as 'Vue') was not found in 'vue'
```

### Expected behavior

I would like to integrate bootstrap-vue with typescript after following [this](https://youtu.be/4deVCNJq3qc) tutorial; however, I'm stuck at the beginning because the described error occurs

### Versions

**Libraries:**

- BootstrapVue: 2.16.0
- Bootstrap: 4.5.2
- Vue: 3.0.0-0

**Environment:**

- Device: Docker-Linux
- OS: Alpine
- Browser: Chrome
- Version: Version 85.0.4183.83 (Official Build) (64-bit)

### Additional context

I ran the same basic idea in Vue 2 and works just fine. Is there a way to "Jerry Rig" so it could work in Vue 3?

**Comment by Hiws** [comment]
BootstrapVue does not support Vue 3 yet.
You can check this Issue for more information: https://github.com/bootstrap-vue/bootstrap-vue/issues/5196
