### ISSUE TITLE
bootstrap-vue table should keep selected item if data refreshes

### ISSUE THREAD

**Issue by xmatthias** [bootstrap-vue/bootstrap-vue#5721]
### Is your feature request related to a problem? Please describe...

When using the boostrap-vue table component a refresh of the underlying data will automatically unselect any previously selected row on every refresh.
This might be OK if the whole data changes, but it's possible that only one row is added (or removed) - or nothing changed at all - so the prior selection should still be valid.

Keeping "selected" state on the item itself does not seem reasonable - assuming the source of the data is a webservice (which obviously doesn't need / want to know which row we're looking at in detail).

### Describe the solution you'd like

Selection is kept based on a key field provided (most likely based on the field defined as `primary-key`, and only unselected if this item disappeared.

### Describe alternatives you've considered

I've tried to watch the item getter, but this is event fires "too early", so using `this.$refs.table.selectRow()` does have no effect, as the refresh happens afterwards.

the `@row-selected` event does fire in this case - however it doesn't seem to contain information if the selection/deselection was done by a user, or if it's been deselected by the data refresh.

`@refreshed` does not seem to fire at all if `:items="data"` is used as datasource.

**Comment by Hiws** [comment]
I don't think this is something we can implement.

Tmorehouse explains it pretty well here why the select state is managed as it is
https://github.com/bootstrap-vue/bootstrap-vue/issues/5297

**Comment by xmatthias** [comment]
Not really, no. 
That issue is mostly a maintainer complaining about the complexity of the component, without providing any alternatives other than "don't use my library if you need this".

Keep in mind, i'm not talking about sorting, nor about pagination - it is a simple backend refresh of the data.

Since b-table does support primary-key, this should be easy to implement (obviously under the constraint that primary key must be used).
What other use does primary-key have - if not to determine uniqueness (which will then allow to easily keep track of selected state).
