### ISSUE TITLE
Navbar - close the menu when clicking on a link

### ISSUE THREAD

**Issue by happilymarrieddad** [bootstrap-vue/bootstrap-vue#573]
Hey guys, I was wondering how to close the menu when clicking on an item in a navbar. Here is my current code.

```
b-navbar(toggleable=true,toggle-breakpoint="sm",type='inverse',variant='custom',fixed='top')
    b-nav-toggle(target='nav_collapse')

    b-collapse#nav_collapse(is-nav)

      //- Left Side
      b-nav(is-nav-bar)
        b-link.navbar-brand(to='/')
          img(:src='$root.customer_image_src || "/static/images/fusionware.png"',style='height:28px;')
        
        b-nav-item(to='/') Dashboard

      //- Right Side
      b-nav.ml-auto(is-nav-bar)
        b-nav-item-dropdown(text='Settings',right-alignment=true)
          b-dropdown-item(to='/clients') Clients

        b-nav-item-dropdown(:text='$root.username',right-alignment=true)
          b-dropdown-item(to='/profile') Profile
          hr
          b-dropdown-item(to='/session/destroy') Logout
```

**Comment by tmorehouse** [comment]
This should be addressed in the next release, as router-links currently do not propagate click events upwards.

**Comment by happilymarrieddad** [comment]
hey man do you know about how long that will be?

**Comment by tmorehouse** [comment]
We're hoping this week.

**Comment by happilymarrieddad** [comment]
Thanks so much man. I'm looking forward to it!

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)

**Comment by EdwardBiton** [comment]
I was literally looking for the nav bar not hidding when clicked and found this and saw your comment that this issue is fixed and released just about 2 hours ago. Did an update with v.0.17.0 and worked perfectly. Thanks

**Comment by tmorehouse** [comment]
@EdwardBiton Glad it is working for you!

If you run into any issues with the latest release, please open an issue.

**Comment by happilymarrieddad** [comment]
Thanks!

**Comment by tranghaviet** [comment]
My navbar also not closing when go to another path when my navbar is not re-render because I using `keep-alive`
```
<keep-alive>
      <component :is="navBarType"></component>
    </keep-alive>
```
E.g: navbar not close when I click `Foo`
```
<b-nav-item to="/foo" active>Foo</b-nav-item>
```

How can I deal with this?
(sorry for my english)
