### ISSUE TITLE
When using e-tabs, when there are too many e-tabs, the e-tab will wrap automatically, which is very ugly. Scrolling mode is recommended

### ISSUE THREAD

**Issue by 80477286** [bootstrap-vue/bootstrap-vue#5735]
### Describe the bug

When there are too many tabs, it will be changed automatically, which is very ugly. It is recommended to use the scrolling mode

### Steps to reproduce the bug

1. create b-tabs
2. Create 50 e-tab
3. tab will wrap automatically

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
You can use utility classes to make the nav overflow with a scrollbar instead of wrapping.

```html
<b-tabs nav-class="flex-nowrap overflow-auto">
  <b-tab title-item-class="mb-0 text-nowrap">
    <!-- Content -->
  </b-tab>
</b-tabs>
```

You can also check out this #5206 issue, for another workaround.

**Comment by 80477286** [comment]
Maybe I didn't describe it clearly. I hope it's the effect



发件人: Hiws
发送时间: 2020年9月4日 17:56
收件人: bootstrap-vue/bootstrap-vue
抄送: 80477286; Author
主题: Re: [bootstrap-vue/bootstrap-vue] When using e-tabs, when there aretoo many e-tabs, the e-tab will wrap automatically, which is very ugly.Scrolling mode is recommended (#5735)

You can use utility classes to make the nav overflow with a scrollbar instead of wrapping.
<b-tabs nav-class="flex-nowrap overflow-auto">
  <b-tab title-item-class="mb-0 text-nowrap">
    
  </b-tab>
</b-tabs>
You can also check out this #5206 issue, for another workaround.

**Comment by 80477286** [comment]
Maybe I didn't describe it clearly. I hope it's the effect（The scroll arrows are on the left and right）
 < [tab1][tab2][tab1][tab...] >
