### ISSUE TITLE
custom css classes dont work on icons only direct styling

### ISSUE THREAD

**Issue by faithfulojebiyi** [bootstrap-vue/bootstrap-vue#5736]
custom css does not work on b-icons

`<div class="h2 mb-0">
      <b-icon icon="battery-full"></b-icon>
    </div>`

`<style lang= "scss>
.b-icon{
  color: #7952b3;
  size: 50px;
}
</style>`

1. Go to [...]
2. Click on [...]
3. Scroll down to [...]

### Expected behavior

i was hoping the color and size would change but nothing happened

### Versions

**Libraries:**
- BootstrapIcons
- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Comment by Hiws** [comment]
I just tested it in a fresh `vue-cli` project, and looks to be working as expected.

You also have a typo in your CSS.
It should be `font-size`, instead of `size`.

Inspect the DOM to see if anything is overwriting the styles you're trying to apply.

**Comment by faithfulojebiyi** [comment]
> I just tested it in a fresh `vue-cli` project, and looks to be working as expected.
> 
> You also have a typo in your CSS.
> It should be `font-size`, instead of `size`.
> 
> Inspect the DOM to see if anything is overwriting the styles you're trying to apply.

I'll check that but is the color applying

**Comment by Hiws** [comment]
Yes, both the color and font-size changes.

**Comment by faithfulojebiyi** [comment]
Before I close the issue I'd try it on a fresh project again. Please can you also try the code on BV's playground. The effects don't work there and I thought it would

**Comment by Hiws** [comment]
The playground doesn't have a field for CSS.
But exporting it to codepen and adding it there also works.

https://codepen.io/Hiws/pen/PoNEPyx

**Comment by faithfulojebiyi** [comment]
I've been able to fix my vue project. 
I had to set up vue.config.js and my .postcssrc.js file properly everything works fine now.
Then I didn't have autoprefixer installed. Thanks for letting me figure it was from my end and not a bug 🐛. I'm grateful. 🚀
