### ISSUE TITLE
File upload dialogue is not getting opened onclick of dropdown item

### ISSUE THREAD

**Issue by DebaPrasad14** [bootstrap-vue/bootstrap-vue#5740]
### Describe the bug

I have a dropdown having one dropdown item which on click doesn't open the file dialogue box.

### Expected behavior

On click of the dropdown item, it should open a file upload dialogue.

### Versions

**Libraries:**

- BootstrapVue: 2.11.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- Device: [ Dell Pc ]
- OS: [Ubuntu 20.04]
- Browser: [Chrome]

### Demo link

code pen- https://codepen.io/kkdas202/pen/zYqPXdp?editors=1010

**Comment by Hiws** [comment]
It's because you're placing it inside `<b-dropdown-item>`.
Try and use `<b-dropdown-item-button>` instead.

https://codepen.io/Hiws/pen/bGpabBR

**Comment by DebaPrasad14** [comment]
yes, @Hiws, I was trying to get it done by dropdown-items but then finally ended up doing with dropdown-item-button.
