### ISSUE TITLE
Disable autocapitalize on B-Form-Tag for first tag entries on mobile devices

### ISSUE THREAD

**Issue by dosstx** [bootstrap-vue/bootstrap-vue#5741]
### Is your feature request related to a problem? Please describe...

On mobile devices, when user inputs a Form Tag, the mobile device will start the first letter of the tag as uppercase. This is the default behavior for mobile devices (iOS, not sure about others). BootstrapVue will alert the user that his entry is invalid, and there is some help text below that can be placed with more information about the character requirements, but it takes a lot of "thinking" on the user's part and is easy to miss. Anyone that has tried to "un-uppercase" their text on a phone knows that it is not easy trying to fix (fat fingers have to go back and undo the uppercase letter). 

### Describe the solution you'd like

BootstrapVue provides a prop or similar function where this uppercase on first entry can be turned off. 

### Describe alternatives you've considered

I tried to add `autocapitalize="off"` to b-form-tag but that did not work.

**Comment by Hiws** [comment]
Since `autocapitalize` is an input attribute, try passing it to the tags input via the `input-attrs` prop.

`<b-tags :input-attrs="{ 'autocapitalize': 'off' }"`

**Comment by dosstx** [comment]
Thanks! That worked perfectly. The only exception was that ESLINT removed the `'` quotes from `autocapitalize`. We can close this now.
