### ISSUE TITLE
Bootstrap Vue overwrites Vee Validate config classes

### ISSUE THREAD

**Issue by sts-ryan-holton** [bootstrap-vue/bootstrap-vue#5742]
### Describe the bug

When using Bootstrap Vue 2.16.0 alongside Vee Validate 3.3.9, the Vee Validate options config for setting classes for validation seems to be overwritten by Bootstrap Vue's validation in terms of the classes being added. For example, I've turned off adding the `is-valid` class for valid inputs, but Bootstrap Vue seems to still be adding it

### Steps to reproduce the bug

- I believe none is needed for this particular issue as it can be clearly displayed via my code below:

I'm also using Nuxt JS, so a plugin is loaded for the client with my Vee Validate config:

**plugins/vee-validate.js**

```javascript
import Vue from 'vue'
import { ValidationProvider, ValidationObserver, extend, configure } from 'vee-validate'
import * as rules from 'vee-validate/dist/rules'

const config = {
  mode: 'lazy',
  classes: {
    valid: '', // I don't want classes added for valid inputs
    invalid: 'is-invalid'
  }
}

configure(config)

Object.keys(rules).forEach(rule => {
  extend(rule, rules[rule])
})

// Register it globally
Vue.component("validation-observer", ValidationObserver)
Vue.component('ValidationProvider', ValidationProvider)
```

An example of implementing my form..

**pages/login.vue**

```html
<b-card>
  <validation-observer v-slot="{ handleSubmit }">
    <b-form @submit.stop.prevent="handleSubmit(attemptLogin)">
      <validation-observer :key="1">
        <ValidationProvider
          name="Email"
          rules="required|email|max:190"
          v-slot="validationContext"
        >
          <b-form-group id="email-input-group" label="Email" label-for="email">
            <b-form-input
              id="email"
              v-model="login.email"
              type="text"
              placeholder="e.g: name@workplace.com"
              :state="getValidationState(validationContext)"
              aria-describedby="email-live-feedback"
              size="lg"
            ></b-form-input>
            <b-form-invalid-feedback id="email-live-feedback">
              {{ validationContext.errors[0] }}
            </b-form-invalid-feedback>
          </b-form-group>
        </ValidationProvider>
        <ValidationProvider
          name="Password"
          rules="required|min:8"
          v-slot="validationContext"
        >
          <b-form-group id="password-input-group" label="Your Password" label-for="password">
            <b-form-input
              id="password"
              v-model="login.password"
              type="password"
              placeholder="Your password"
              :state="getValidationState(validationContext)"
              aria-describedby="password-live-feedback"
              size="lg"
            ></b-form-input>
            <b-form-invalid-feedback id="password-live-feedback">
              {{ validationContext.errors[0] }}
            </b-form-invalid-feedback>
          </b-form-group>
        </ValidationProvider>
        <b-button :disabled="isLoggingIn" block pill variant="primary" size="lg" type="submit" class="mt-3">
          <b v-if="!isLoggingIn">Log In</b>
          <b-spinner v-else small label="Logging in..."></b-spinner>
        </b-button>
        <b-alert show :variant="messages.type" class="mt-3 mb-0" v-if="messages.hasMessage" dismissible>{{ messages.msg }}</b-alert>
      </validation-observer>

    </b-form>
  </validation-observer>
</b-card>
```

### Expected behavior

Bootstrap Vue shouldn't be overwriting my Vee Validate config

### Versions

**Libraries:**

- BootstrapVue: 2.16.0
- Bootstrap: 4.5.2
- Vue: 2.6.11
- Nuxt: 2.14.4

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version: Latest

### Additional context

Maybe I'm just missing a setting?

**Comment by Hiws** [comment]
I wouldn't really say it's "overwriting" the config.

Bootstrap-Vue adds the `is-valid` class, when the `state` is true, and the `is-invalid` class when the `state` is false.
These classes are what gives the input its styling.

If you don't want the input styled when the input is valid, set the `state` to `null` instead of true.
Alternatively, if `VeeValidate` is adding these classes by itself, you could simply not use the `state` prop on your input at all.

**Comment by sts-ryan-holton** [comment]
@Hiws Unfortunately your suggestion doesn't achieve the correct result. The method for retreiving the validation state is as follows:

```js
getValidationState ({ dirty, validated, valid = null }) {
  return dirty || validated ? valid : null;
}
```

If I set `:state="true"` on an input then it appears Bootstrap Vue adds the `is-valid` class, which as I've stated I've turned off via the Vee Validate config so do not wish for this class to be added at all. If I set it to **false** then the input is permanently invalid which for UI reasons isn't great. And setting it to **null** means that as I start typing `is-valid` the class is added, which isn't what I need.

I do not want and valid class added when a user is typing, thus why I've also modified the `mode`

```js
const config = {
  mode: 'lazy',
  classes: {
    valid: '',
    invalid: 'is-invalid'
  }
}
```

**Comment by Hiws** [comment]
> If I set :state="true" on an input then it appears Bootstrap Vue adds the is-valid class, which as I've stated I've turned off via the Vee Validate config

I still don't get what a VeeValidate config has to do with BootstrapVue.
BootstrapVue doesn't know about VeeValidate, so it doesn't care what you've configured there.

> @Hiws Unfortunately your suggestion doesn't achieve the correct result. The method for retreiving the validation state is as follows.
If it is as follows, then wouldn't it be quite simple to change the method to return `null` instead of `true`?

> And setting it to `null` means that as I start typing `is-valid` the class is added, which isn't what I need.
Not sure where you got that from. `:state="null"` will add no classes. `:state="false"` will add `is-invalid` and `:state="true"` will add the `is-valid` class.

**Comment by sts-ryan-holton** [comment]
@Hiws The solution I found was to do the following...

1. Change `v-slot="validationContext"` -> `v-slot="{ errors, classes }"`
2. Remove the `state` prop entirely and add `:class="classes"`
3. Don't use `{{ validationContext.errors[0] }}` for errors, now using `{{ errors[0] }}`

And in doing this I get the desired result. `is-valid` isn't added at all on **any** of the inputs (meaning my Vee Validate config is working perfectly) and `is-invalid` is added to those that are invalid. Also, the Vee Validate `mode` is now working correctly as well.

I'm sure other users are experiencing similar issues, so this should help them 👍
