### ISSUE TITLE
I think I found a bug when I using v-b-popover

### ISSUE THREAD

**Issue by Charlie50503** [bootstrap-vue/bootstrap-vue#5747]
### Describe the bug

when i use 
`
<span v-b-popover.hover.bottom="somethingText">
	test
</span>
`
in my component and i need to use beforeDestroy hook
beforeDestroy was be called how i added v-b-popover times

### Versions

**Libraries:**

- BootstrapVue: 2.16.0
- Bootstrap: 4.5.2
- Vue: 2.6.11
-vue-router: 3.2.0

**Environment:**

- Device: Thinkpad
- OS: Window 10
- Browser: Chrome
- Version: 85

### Demo link

[demo](https://charlie50503.github.io/testpopover-demo/#/)
[code](https://github.com/Charlie50503/testpopover)

**Comment by jackmu95** [comment]
@Charlie50503 I've created a CodeSandbox that confirms the bug:
https://codesandbox.io/s/stupefied-solomon-89zlk

**Comment by Charlie50503** [comment]
Thanks
