### ISSUE TITLE
I can't use custom themes correctly

### ISSUE THREAD

**Issue by TuiMao233** [bootstrap-vue/bootstrap-vue#5756]
~~~scss
// Include Bootstrap and BootstrapVue SCSS files
@import '~bootstrap/scss/bootstrap.scss';
@import '~bootstrap-vue/src/index.scss';

 error  in ./src/custom.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Incompatible units rem and px.
    ╷
724 │ $nav-link-height:                   $font-size-base * $line-height-base + $nav-link-padding-y * 2 !default;
    │                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\_bootstrap@4.5.2@bootstrap\scss\_variables.scss 724:37  @import
  node_modules\_bootstrap@4.5.2@bootstrap\scss\bootstrap.scss 9:9      @import
~~~

**Comment by jackmu95** [comment]
@TuiMao233 Seems like you've set the value of the `$nav-link-height` variable to a value in `px` (e.g. `20px`) in your `custom.scss` file.

Pixel values are not supported for this variable. Please use a `rem` value (e.g. `2rem`) isntead.

**Comment by TuiMao233** [comment]
No, I mean, as long as I indicate the official style, there will be such an error, and after solving this error, there are still many such errors, which makes me unable to use custom themes at all

**Comment by jackmu95** [comment]
I was wrong, either `$font-size-base`, `$line-height-base` or `$nav-link-padding-y` was set as a pixel value.
This is overall the themes fault. It has to support the variable value/unit types Bootstrap requires.

**Comment by TuiMao233** [comment]
So how should I make my custom theme reflect, I did not find an effective solution, my environment is typescript3.9.3, vue2.6.11, bootstrap4.3.1, bootstrap-vue2.1.0.

**Comment by TuiMao233** [comment]
I solved it, as long as it doesn't use the sass and sass-loader version that comes with the vue-cli build, I manually installed sass and sass-loader after rebuilding, and then the problem was solved.
