### ISSUE TITLE
Generate inertia-link using b-link

### ISSUE THREAD

**Issue by IP-Developer** [bootstrap-vue/bootstrap-vue#5759]
### Is your feature request related to a problem? Please describe...

Currently it is not possible to generate an `inertia-link` using the `b-link` (and all related) components.

### Describe the solution you'd like

The ability to generate links based on any route components, not just the ones based on `vue-router`

### Describe alternatives you've considered

The only solution now is to generate links via `inertia-link` component and manually apply all necessary bootstrap classes.

### Additional context

I'm just trying to make InertiaJS and BoostrapVue work together :)

**Comment by Hiws** [comment]
You should already be able to do this using the `router-component-name` prop.
https://bootstrap-vue.org/docs/components/link#third-party-rounter-links

However, this might not work directly since it looks like `inertia-link` doesn't use the `to` prop.
You could however create a wrapper component around `inertia-link`, which maps `to`, to `href`. and then define your own wrapper component in `router-component-name`.

**Comment by IP-Developer** [comment]
@Hiws it doesn't work. Here's what I've done:

Created and registered globally a `link-wrapper` component:
```
<template>
    <inertia-link :href="to"></inertia-link>
</template>

<script>
export default
{
    name: "LinkWrapper",
    props: ['to'],
    created()
    {
        console.log('link created');
    }
}
</script>
```

Defined it in `router-component-name` on `b-link`:
`<b-link to="/test-page" router-component-name="link-wrapper">Test page</b-link>`

And it doesn't use the wrapper at all:
![image](https://user-images.githubusercontent.com/2005081/92987240-6054de80-f4c9-11ea-8d97-3a3ba182d59d.png)

**Comment by Hiws** [comment]
What version of Bootstrap-Vue are you running?
`router-component-name` was added in `v2.15.0`

**Comment by IP-Developer** [comment]
@Hiws I'm using `v2.16.0`. I recreated your example and it doesn't work.
![image](https://user-images.githubusercontent.com/2005081/93013398-d2ecb980-f5b0-11ea-90de-8c6591784af7.png)
![image](https://user-images.githubusercontent.com/2005081/93013405-daac5e00-f5b0-11ea-9413-ebcf0d449571.png)
![image](https://user-images.githubusercontent.com/2005081/93013416-fa438680-f5b0-11ea-9940-6ab6ce67afb4.png)

**Comment by jackmu95** [comment]
@IP-Developer In order to support custom `<b-link>` components with `router-component-name` we currently check for the `$router` property on the instance and fallback to a regular anchor tag (`a`) when router support wasn't detected.

That is your problem. Since you are using [inertia](https://inertiajs.com/) which don't requires `<vue-router>`.

**Comment by IP-Developer** [comment]
@jackmu95 in this case I think this should be marked as a feature request.

**Comment by lazabogdan** [comment]
Just bumped into this as well. The solution seems very simple though. Not sure if it has other implications, however in the 30 seconds I tested this with a pretty complex UI, it seems that inertia does intercept all links.

**RouterLink.vue**

```html
<template>
  <inertia-link :href="to">
    <slot />
  </inertia-link>
</template>

<script>
  export default {
    props: ['to']
  }
</script>
```

**app.js**

```js
import RouterLink from './RouterLink'
Vue.component('RouterLink', RouterLink)
Vue.prototype.$router = 'fake'
```

**Comment by makroxyz** [comment]
> Just bumped into this as well. The solution seems very simple though. Not sure if it has other implications, however in the 30 seconds I tested this with a pretty complex UI, it seems that inertia does intercept all links.
> 
> **RouterLink.vue**
> 
> ```
> <template>
>   <inertia-link :href="to">
>     <slot />
>   </inertia-link>
> </template>
> 
> <script>
>   export default {
>     props: ['to']
>   }
> </script>
> ```
> 
> **app.js**
> 
> ```js
> import RouterLink from './RouterLink'
> Vue.component('RouterLink', RouterLink)
> Vue.prototype.$router = 'fake'
> ```

this works fine but when used on b-pagination-nav it can't set the active page... 'cos of missing router
Is there any workaround??
