### ISSUE TITLE
In some WeChat/QQ mobile browsers, the date selection is not displayed correctly

### ISSUE THREAD

**Issue by TuiMao233** [bootstrap-vue/bootstrap-vue#5766]
### Describe the bug

In some WeChat/QQ mobile browsers, the date selection is not displayed correctly

![image](https://user-images.githubusercontent.com/49724027/92990842-278d2780-f512-11ea-9ee5-31eb88f0f963.png)

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Comment by jackmu95** [comment]
@TuiMao233 Which device and OS was that on?

**Comment by TuiMao233** [comment]
Phone system：MIUI 10.3.10
Phone model：Redmi Note 7 Pro
WeChat version：7.0.18

**Comment by jackmu95** [comment]
@TuiMao233 Are you able to reproduce the same issue in the default MIUI web browser?
Do you have access to another Android device with WeChat to make sure it's an issue with the WeChat browser/webview.
