### ISSUE TITLE
Table filter not working

### ISSUE THREAD

**Issue by kurtwielder** [bootstrap-vue/bootstrap-vue#5775]
Since version 2.17.0, table filter has stopped working, which can be viewed on the examples/demo page: https://bootstrap-vue.org/docs/components/table **Complete example** section.

**Comment by Hiws** [comment]
Looks like there might be a problem with `filter-included-fields`, where it's not filtering on all fields when you pass an empty array.
If you pass it a `null` value or leave out the prob all together it looks to work as intended.
