### ISSUE TITLE
Modal padding-right bug

### ISSUE THREAD

**Issue by TheAndroidGuy** [bootstrap-vue/bootstrap-vue#5776]
In the latest v2.17.0 there is problem with modals.
When you open the modal it sets `padding-right: 17px;` to the `body`, but when you close the modal, the padding is not removed.

![padding](https://user-images.githubusercontent.com/17319245/93273005-131d8900-f7b7-11ea-97b4-ea88edd038e0.png)

To reproduce the issue go to the [Modals ](https://bootstrap-vue.org/docs/components/modal#modals)page.

Tested in all major browsers, the problem persists.

**Comment by Hiws** [comment]
This issue should already have been fixed in a recent PR.
It should be fixed with the next release.

**Comment by jackmu95** [comment]
Closed by #5771.
