### ISSUE TITLE
Size XS - make it available for things like table/pagination

### ISSUE THREAD

**Issue by happilymarrieddad** [bootstrap-vue/bootstrap-vue#578]
Hey Guys,

Is there a way to get the buttons/tables/pagination smaller? Thanks!

- Nick

**Comment by tmorehouse** [comment]
The new pagination updated (available in master, and soon in release v0.17.0) support changing the button sizes.

See PR #528

**Comment by tmorehouse** [comment]
Bootstrap-vue supports the sizes available in the native bootstrap V4.alpha.6 components.

**Comment by happilymarrieddad** [comment]
Ok cool. Here is an example of the problem I'm having. Sorry man I know you said this is fixed and I'm excited about it but I just wanted to put here an example. I hope this is ok. It's really more for me to make sure that I'm understanding what you are saying. Thanks!

![selection_271](https://user-images.githubusercontent.com/6416323/27703750-add34e8e-5cc5-11e7-8cbb-338e51d60a63.png)
![selection_272](https://user-images.githubusercontent.com/6416323/27703757-b0c0bc3a-5cc5-11e7-90c1-1a51bdc632b5.png)
![selection_273](https://user-images.githubusercontent.com/6416323/27703760-b3ccded6-5cc5-11e7-8684-95250262bb4e.png)

**Comment by tmorehouse** [comment]
Bootstrap v4.alpha.6 only supports `lg`, default, and `sm` button sized in button groups: http://v4-alpha.getbootstrap.com/components/button-group/#sizing

**Comment by tmorehouse** [comment]
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) .

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)

**Comment by happilymarrieddad** [comment]
thanks!
