### ISSUE TITLE
b-form-input type="number" allows any character in Firefox

### ISSUE THREAD

**Issue by Nilaik** [bootstrap-vue/bootstrap-vue#5781]
### Describe the bug

When using a b-form-input in Firefox 80.0.1 (64-Bit, Windows) you can enter any type of character.

### Steps to reproduce the bug

1. Go to in firefox [https://bootstrap-vue.org/docs/components/form-input#comp-ref-b-form-input-props]
2. Enter some text in the number input field

![grafik](https://user-images.githubusercontent.com/6548690/93317028-3a9f4080-f80d-11ea-97fe-e97687ebcd69.png)

### Expected behavior

The expected behavior can be reproduced with Chrome 85.0.4183.102 (64-Bit, Windows). Where only numbers, comma and decimal points are allowed. All other characters are supressed.

### Versions

**Libraries:**

- BootstrapVue: 2.17.0 (Online Documentation)

**Environment:**

- Device: Lenovo Laptop
- OS: Windows 10
- Browser: Firefox
- Version: 80.0.1

**Comment by Hiws** [comment]
`<b-form-input>` is a wrapper around the native `<input>` element.
Meaning that the behavior of each type is left up to the browser.

I just tested a normal `<input type="number" />`, and it works the same as expected.
So this is either a Browser Bug, or just how Firefox wants to implement their number input.

**Comment by Nilaik** [comment]
Thank you for the quick answer. I also found this bug report for Firefox: [https://bugzilla.mozilla.org/show_bug.cgi?id=1398528] Seems like Firefox will not change the behavior any time soon.
