### ISSUE TITLE
Memory leak with several items in b-table 

### ISSUE THREAD

**Issue by chumager** [bootstrap-vue/bootstrap-vue#5784]
### Describe the bug

Hi, After a couple of years working with your module I started havieng memleaks when the user ask for several items (100) in a dynamically generated b-table, so I started doing some memory snapshot to compare.

At first I start with 5 items with pagination and the behavior worked as expected.
![image](https://user-images.githubusercontent.com/775491/93347112-17739180-f80b-11ea-9134-6c9e21e0d51f.png)

Later I did the same test but with 100 items, and got this.

![image](https://user-images.githubusercontent.com/775491/93347279-42f67c00-f80b-11ea-93e0-06e3cd39fb38.png)

After the second pagination I got this kind of error (all depends on how much components with inner component the slot have, in some tables is at second page in others in third) **Uncaught RangeError: Maximum call stack size exceeded** and after that I get this error for every operation so the only way to keep working is to refresh the page.

For instance I don't know if the error is mine, vue.js, bootstrap-vue or chrome (in FF it doesn't happens).

Could be a GC error? maybe the GC is too slow in chrome so in between paginations the GC doesn't release all the memory, components or DOM and the V8 crashes without knowing why and throws this error.

### Steps to reproduce the bug
I can give you an account to test in my QA site if you want, but I think it's more like memleak, because if my clients work with few data they never get this error.

### Expected behavior

If the problem it's not yours then nothing, in case it's yours a way to avoid this behavior...

### Versions

**Libraries:**

- BootstrapVue: 2.17
- Bootstrap: 4.5.2
- Vue: 2.6.12
**Environment:**

- Device: Asus ROG
- OS: Debian Buster
- Browser: Chrome
- Version: 85.0.4183.102 but it's happening months ago.

### Demo link

As I said before I can give you an account in my QA if you like.

### Additional context

As in my snapshots It seems the bootstrap-vue it's behaving well but I need to clarify.

**Comment by jackmu95** [comment]
@chumager Is this a new issue with BootstrapVue v2.17.0 or did you have the same issue with previous versions as well?

**Comment by chumager** [comment]
Hi, @jackmu95 I tried until v2.15 or v2.14 because I use the icons, and it's the same problem.

I think the problem is I use a lot o components with subcomponents, so for example no matter if a item is a string I've a component who checks if it's in the grid, in the detail or as input, other component who loads automatically the component needed, and maybe the CG from chrome is too slow to delete the DOM, in vuejs is normal to wrap every template because the template tag only support one root tag, so in between all the component and subcomponents you get a lot o divs just for wrapping, I think that could be the problem but I'm not sure, the only thing for certain is this ain't happens with FF.

**Comment by chumager** [comment]
Hi, I could replicate the error with a very simple components
views/memLeak.vue
```vue
<template>
  <div>
    <b-row no-gutters>
      <b-col>
        <b-row no-gutters>
          <b-col>
            <b-table :per-page="perPage" :items="items" :fields="fields" :current-page="currentPage" ref="table">
              <template v-for="field in fields" #[`cell(${field.key})`]>
                <component :is="'memLeak'" :key="Math.random()" />
              </template>
            </b-table>
          </b-col>
        </b-row>
        <b-row no-gutters class="justify-content-md-center text-center" v-noprint>
          <b-col>
            <b-pagination
              align="center"
              :total-rows="totalRows"
              :per-page="perPage"
              v-model="currentPage"
              class="my-0"
              pills
              limit="7"
              hide-ellipsis
              first-number
              last-number
              hide-goto-end-buttons
            />
          </b-col>
          <b-col class="center-text">
            Registros por página:
            <b-form-select v-model="perPage" size="sm" :options="perPageOptions" style="max-width: 5em" />
          </b-col>
        </b-row>
      </b-col>
    </b-row>
  </div>
</template>

<script>
import memLeak from "../components/memLeak";
export default {
  components: {
    memLeak
  },
  data() {
    return {
      perPage: 10,
      perPageOptions: [10, 1000, 2000, 5000],
      currentPage: 1,
      totalRows: 1000000,
      fields: [
        {
          label: "llave1",
          key: "key1"
        },
        {
          label: "llave2",
          key: "key2"
        },
        {
          label: "llave3",
          key: "key3"
        }
      ]
    };
  },
  methods: {
    items() {
      const data = [...Array(this.perPage).keys()].map(() => ({key1: Math.random(), key2: "test", key3: new Date()}));
      return data;
    }
  }
};
</script>
```
components/memLeak.vue
```vue
<template>
  <span v-html="localValue" />
</template>
<script>
export default {
  data() {
    return {
      localValue: Math.random()
    };
  }
};
</script>
```
If you change the registers per page to 1000 and move to the second page you will get the error, at least it happens to my inside my app.

Regards.
