### ISSUE TITLE
Module not found: Error: Can't resolve 'bootstrap-vue/es/components'

### ISSUE THREAD

**Issue by woodchuck00** [bootstrap-vue/bootstrap-vue#5785]
I am trying to upgrade from to 2.0.0-rc.14" to v2.17.0
after running ```npm install vue bootstrap-vue bootstrap``` I am getting the following error on build.

```ERROR in ./resources/assets/js/app.js
Module not found: Error: Can't resolve 'bootstrap-vue/es/components' in 'D:\Users\T\workspace\eco-channels\resources\assets\js'
 @ ./resources/assets/js/app.js 15:0-55
 @ multi ./resources/assets/js/app.js```

The console says I can fix this by: To install them, you can run: npm install --save bootstrap-vue/es/components bootstrap-vue/es/components/modal/modal bootstrap-vue/es/components/spinner/spinner
but I get this on run 
```npm ERR! code ENOLOCAL
npm ERR! Could not install from "bootstrap-vue\es\components" as it does not contain a package.json file.```

I am running on Windows Server 2008 on cmder/Git for Windows

**Comment by Hiws** [comment]
Since you're upgrading from the `rc` release, you should go over the `2.0.0` changelog.
<https://bootstrap-vue.org/docs/reference/changelog#migration-guide-v200>

Which has a migration guide and a list of the breaking changes.
One of which is this note
> Removal of the deprecated /es build directory. Users should now be using the new simplified import syntax introduced in v2.0.0-rc.22. Users should be importing the top-level named exports instead.

**Comment by woodchuck00** [comment]
Thanks, that was the solution.
