### ISSUE TITLE
Table with dropdown inside.

### ISSUE THREAD

**Issue by montepjones** [bootstrap-vue/bootstrap-vue#579]
I am not sure if it the way I am doing it or it is just a bug. I am trying to use a dropdown inside a table and update the value based on the value of the dropdown. I have everything working as expected. Expect that when I change the dropdown the value does not change. Even though I can get the dropdowns to start at the correct place with different values. 
here is a jsfiddle
https://jsfiddle.net/montepjones/pqpzps16/7/

**Comment by tmorehouse** [comment]
You should treat `items` with in the table as read only. (i.e. the scoped slot)..

You would need to modify your source table items, which would then trigger a change on b-table to react to the new data.

**Comment by tmorehouse** [comment]
@montepjones Try the following:

```html
<b-table striped hover :items="items" :fields="fields"
        v-model="shownData"
        :current-page="currentPage" :per-page="perPage" :filter="filter"
>
  <template slot="name" scope="item">
      {{item.value.first}} {{item.value.last}}
  </template>
  <template slot="isActive" scope="item">
    <b-form-select v-model="shownData[item.index].isActive" :options="options">
    </b-form-select>
  </template>
```

```js
new Vue({
  el: '#app',
  data: {
    selected: 'a',
    shownData: [],
    options: [ .... ],
    items: [ ... ],
    fields: { ... },
    currentPage: 1,
    perPage: 5,
    filter: null
  },
  methods: {
    details(item) {
      alert(JSON.stringify(item));
    }
  }
});
```

v-model is tied to b-tables displayed items, and made available to your app via the `shownData` data property.

`shownData` will have only the rows of displayed data in the table (indexed from 0, same value as item.index in your scoped slot).

See https://jsfiddle.net/bootstrapvue/pqpzps16/9/ for an example

**Comment by montepjones** [comment]
Awesome much apprecited

**Comment by tmorehouse** [comment]
@montepjones So does this solution work the way you need it to?
