### ISSUE TITLE
Headers that are not sortable are clickable and reset sorting

### ISSUE THREAD

**Issue by fermaud** [bootstrap-vue/bootstrap-vue#5792]
### Steps to reproduce the bug

Create a table with headers and click on non sortable header. Sorting is restarted

### Expected behavior

It should not be clickage or at least we could set it up.

### Versions

**Libraries:**

- BootstrapVue: 2.15
- Bootstrap: 4.5
- Vue: 2.6

- Device: Computer
- OS: Ubuntu 20
- Browser: Chrome

**Comment by Hiws** [comment]
This feature can be disabled by adding the `no-sort-reset` prop to `<b-table>`.

**Comment by fermaud** [comment]
Thank you !
