### ISSUE TITLE
Navbar don't collapse when focus is set on input in page

### ISSUE THREAD

**Issue by ochiers** [bootstrap-vue/bootstrap-vue#5795]
### Describe the bug

After click on burger menu to open the toggle navbar.
When I click in input of my page, the navbar doesn't collapse.

### Steps to reproduce the bug

```html
<b-navbar toggleable="md" type="dark" class="jh-navbar" role="navigation" :key="$route.path">
    <b-navbar-toggle
      right
      class="jh-navbar-toggler"
      href="javascript:void(0);"
      data-toggle="collapse"
      data-target="#header-tabs"
      target="header-tabs"
      aria-expanded="false"
      aria-label="Toggle navigation"
      toggleable="true">
        <font-awesome-icon icon="bars" />
    </b-navbar-toggle>
    <b-collapse is-nav id="header-tabs">
        <b-navbar-nav>
            <b-nav-item to="/" exact>
                <span class="text-nowrap">
                    <font-awesome-icon icon="home" />
                    <span v-text="$t('global.menu.home')">Home</span>
                </span>
            </b-nav-item>
[...]
```

1. Open navbar by click on burger menu
2. Set focus on an input in page
3. See that the navbar doesn't collapse

### Expected behavior

The navbar is collapse after click in page/out of the menu.

### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- Device: PC, mobile...
- OS: windows, android, iOs
- Browser: Chrome, Firefox

**Comment by Hiws** [comment]
I'm pretty sure this is normal Bootstrap behavior and working as expected.
Though, we could maybe consider it as a feature.


However, I'm a little confused about your code snippet
```html
<b-navbar-toggle
  right
  class="jh-navbar-toggler"
  href="javascript:void(0);"
  data-toggle="collapse"
  data-target="#header-tabs"
  target="header-tabs"
  aria-expanded="false"
  aria-label="Toggle navigation"
  toggleable="true">
    <font-awesome-icon icon="bars" />
</b-navbar-toggle>
```

It looks like you're trying to mix normal Bootstrap and BootstrapVue, which you shouldn't do.
You don't need all the `data-*` attrbutes. 
The `aria-*` attributes are also applied automatically by BootstrapVue so you don't need to apply those manually either.

**Comment by ochiers** [comment]
You have right, I've been confused when I search solution.
I let some mistakes in my snippet, we can delete `data-*` attributes.
