### ISSUE TITLE
Error in bootstrap-vue/src/index.scss

### ISSUE THREAD

**Issue by phlegx** [bootstrap-vue/bootstrap-vue#5797]
### Describe the bug

Cannot use bootstrap-vue in my vue project.

### Steps to reproduce the bug

1) Serve the app.

```
error  in ./node_modules/bootstrap-vue/src/index.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.

   ╷
11 │ $b-custom-control-indicator-size-lg: $custom-control-indicator-size * 1.25 !default;
   │                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/bootstrap-vue/src/_variables.scss 11:38  @import
```

### Expected behavior

Compile scss without errors.

### Versions

**Libraries:**

- BootstrapVue: 2.17.1
- Bootstrap: 4.5.2
- Vue: 2.6.12

### Additional context

My main.js file:

```
import Vue from 'vue'
...
import '@/assets/css/plugins/bootstrap/config.scss'
import 'bootstrap/scss/bootstrap.scss'
import 'bootstrap-vue/src/index.scss'
...
```

**Comment by Hiws** [comment]
As described on the Getting Started page, you need to import `bootstrap/scss/bootstrap.scss` and `bootstrap-vue/src/index.scss` into a single `scss` file, and then import this single file your `main.js`.

https://bootstrap-vue.org/docs#using-module-bundlers
>Place all of the SCSS @imports into a single SCSS file, and import that single file into your project. Importing individual SCSS files into your project will not share variable values and functions between files by default.

**Comment by phlegx** [comment]
Thank you Dude!

**Comment by AbrahamBrookes** [comment]
I landed here on the exact same error, after some mussing around I found out that I had installed bootstrap v5 instead of the (current, supported) v4. Just, you know, check for that as well.

**Comment by kbala97** [comment]
> As described on the Getting Started page, you need to import `bootstrap/scss/bootstrap.scss` and `bootstrap-vue/src/index.scss` into a single `scss` file, and then import this single file your `main.js`.
> 
> https://bootstrap-vue.org/docs#using-module-bundlers
> 
> > Place all of the SCSS @imports into a single SCSS file, and import that single file into your project. Importing individual SCSS files into your project will not share variable values and functions between files by default.

This is what worked for me. Thank you!!

**Comment by arudovwen** [comment]
> I landed here on the exact same error, after some mussing around I found out that I had installed bootstrap v5 instead of the (current, supported) v4. Just, you know, check for that as well.

This worked for me, also had installed v5 of bootstrap, changing it to 4 solved it

**Comment by Hiws** [comment]
I figure multiple people will land on this because doing `npm install bootstrap` will now install `Bootstrap 5` by default given that it released out of beta a few days ago.
So to solve this run `npm install bootstrap@4.5.3` instead, to specifically install the latest version of Bootstrap that BootstrapVue supports.

**Comment by hoangnguyen-xenia** [comment]
> I figure multiple people will land on this because doing `npm install bootstrap` will now install `Bootstrap 5` by default given that it released out of beta a few days ago.
> So to solve this run `npm install bootstrap@4.5.3` instead, to specifically install the latest version of Bootstrap that BootstrapVue supports.

Thank you a lot!

**Comment by braankoo** [comment]
> I landed here on the exact same error, after some mussing around I found out that I had installed bootstrap v5 instead of the (current, supported) v4. Just, you know, check for that as well.

tnx man you saved me here :)

**Comment by denykp** [comment]
> As described on the Getting Started page, you need to import `bootstrap/scss/bootstrap.scss` and `bootstrap-vue/src/index.scss` into a single `scss` file, and then import this single file your `main.js`.
> 
> https://bootstrap-vue.org/docs#using-module-bundlers
> 
> > Place all of the SCSS @imports into a single SCSS file, and import that single file into your project. Importing individual SCSS files into your project will not share variable values and functions between files by default.

does anyone know why this trick is not working on `Boostrap 5`.?

**Comment by MannyDiera** [comment]
My issue was using Vue 2 with Bootstrap 5 as others have mentioned. Downgrading to Bootstrap v4 solved the problem. Thanks!

**Comment by fracampit** [comment]
There's seems to be nothing I can do to get this to work. I keep getting the same error:

```
 error  in ./src/assets/css/app.scss

Syntax Error: SassError: Undefined variable.
   ╷
11 │ $b-custom-control-indicator-size-lg: $custom-control-indicator-size * 1.25 !default;
   │                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  ..\..\node_modules\bootstrap-vue\src\_variables.scss 11:38  @import
  ..\..\node_modules\bootstrap-vue\src\index.scss 7:9         @import
  src\assets\css\app.scss 7:9                                 root stylesheet


 @ ./src/assets/css/app.scss 4:14-232 15:3-20:5 16:22-240
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.36:5002&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
```
  "dependencies": {
    "bootstrap": "^4.5.3",
    "core-js": "^3.6.5",
    "jest": "^27.4.5",
    "jest-editor-support": "^30.0.2",
    "sass-loader": "^10.1.1",
    "vue": "^2.6.11",
    "vue-carousel": "^0.18.0"
  }
```
My main.js:
```
import Vue from 'vue'
import App from './App.vue'
import { BootstrapVue, IconsPlugin, LayoutPlugin  } from 'bootstrap-vue'

import './assets/css/fullscroll.css'
import './assets/css/app.scss'

Vue.config.productionTip = false

// Make BootstrapVue available throughout your project
Vue.use(BootstrapVue)
// Optionally install the BootstrapVue icon/layout components plugin
Vue.use(IconsPlugin)
Vue.use(LayoutPlugin)

new Vue({
    render: h => h(App)
}).$mount('#app')
```
My app.scss:
```
// Define variable defaults
$body-bg: #000;
$body-color: #111;

// Then import Bootstrap an BootstrapVue SCSS files (order is important)
@import '../../node_modules/bootstrap/scss/bootstrap.scss';
@import '../../node_modules/bootstrap-vue/src/index.scss';
```
am I missing something?

**Comment by tiararmdni18** [comment]
aku ga tau juga mas, ini jg sama nih masalahnya, klo udah ada yg jawab info masseh

**Comment by becem-alt** [comment]
> I landed here on the exact same error, after some mussing around I found out that I had installed bootstrap v5 instead of the (current, supported) v4. Just, you know, check for that as well.

same problem,thank you <3

**Comment by ktscript** [comment]
to anyone who has encountered this problem, you need to connect style variables directly from bootstrap vue to solve it.

@import "~bootstrap-vue/node_modules/bootstrap/scss/bootstrap.scss";
@import '~bootstrap-vue/src/index.scss';

**Comment by moundre** [comment]
> à tous ceux qui ont rencontré ce problème, vous devez connecter les variables de style directement à partir de la vue bootstrap pour le résoudre.
> 
> @import"~bootstrap-vue/node_modules/bootstrap/scss/bootstrap.scss" ; @import'~bootstrap-vue/src/index.scss';

Merci

**Comment by LordDashMe** [comment]
> npm install bootstrap@4.5.3

Thanks dude!

**Comment by cuonghuynh** [comment]
> npm install bootstrap@4.5.3

Thanks!

**Comment by LangGerr** [comment]
I have this problem too. My primary step to solve this is to check the Vue version. Here is my config.
 "dependencies": {
    "bootstrap": "^4.5.3",
    "bootstrap-vue": "^2.23.1",
    "core-js": "^3.8.3",
    "vue": "^2.6.12",
    "vue-router": "^3.5.1",
    "vuex": "^3.6.2"
  },
and the vue-cli is 2.x.x

**Comment by Samuel-silva** [comment]
> I figure multiple people will land on this because doing `npm install bootstrap` will now install `Bootstrap 5` by default given that it released out of beta a few days ago. So to solve this run `npm install bootstrap@4.5.3` instead, to specifically install the latest version of Bootstrap that BootstrapVue supports.

I install last version 4 (currently bootstrap@4.6.2). It's work for me. Thanks
