### ISSUE TITLE
b-form-tags "add" button invisible block focus on input

### ISSUE THREAD

**Issue by ochiers** [bootstrap-vue/bootstrap-vue#5799]
### Describe the bug

On mobile when the "add" button is invisible and click on this, you don't have focus on b-form-tags, your keyboard doesn't appear.

### Steps to reproduce the bug

1. Go to [b-form-tags](https://bootstrap-vue.org/docs/components/form-tags#b-form-tag-helper-component)
2. Go to "Tag creation using separators" section
3. Add a first tag
4. Click out of the input and lost focus
5. Click where the "add" button must be display. You don't get focus on input

### Expected behavior

Click anywhere and get focus on the field, get your keyboard

### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- Device: Mobile
- OS: Android
- Browser: Chrome

### Demo link

https://bootstrap-vue.org/docs/components/form-tags#b-form-tag-helper-component

**Comment by jackmu95** [comment]
I can't confirm this behavior on iOS with Chrome or Safari.
@Hiws Do you have a Android Device to be able to confirm this?

**Comment by Hiws** [comment]
I can't produce it on Chrome Android either.
