### ISSUE TITLE
[proposal] Add a full basic example to introduce components

### ISSUE THREAD

**Issue by wsw70** [bootstrap-vue/bootstrap-vue#580]
I believe it would be great to add in the "Quick start" section one example of a full application using `bootstrap-vue`. This would be particularly useful to those who are not used to Vue components and for whom it could not be obvious how to consume an event from a component.

A basic example showing how `click` (found in the `Event` section of the `<b-button>` component's documentation) could be used to modify data in the Vue instance:

(HTML)
```
<div id="root">
  <b-button v-on:click="counter += 1">hello</b-button>
  {{counter}}
</div>
```

(JS)
```
new Vue ({
  el: "#root",
  data: {
    counter: 0
  }
})
```

**Comment by tmorehouse** [comment]
This is a great idea.

**Comment by tmorehouse** [comment]
The new release (which should be out tonight), has extended documentation with examples for many components now.

We would probably need to determine a basic app that takes advantage of various bootstrap-vue components, but not be too complex.

**Comment by wsw70** [comment]
@tmorehouse Thank you. This proposal actually arose from my own problem when I discovered `bootstrap-vue`, thought "fantastic!" and then spent some time to understand how to actually use the tags :)

Anyway - thanks a lot for the great work.

**Comment by alexsasharegan** [comment]
@wsw70, how would feel about getting this PR started? It's fresh in your mind, so you're perspective would be awesome! You can even leave placeholders or pseudo-code that we can contribute to if you're still not 100% on how to throw up some app examples.

**Comment by jackmu95** [comment]
@tmorehouse Is this still needed with the current state of the docs?

**Comment by tmorehouse** [comment]
It probably isn't needed as each component has a decent example (or examples) now.
