### ISSUE TITLE
b-table width problem when inside d-flex justify-content-between

### ISSUE THREAD

**Issue by arthurmcgregor** [bootstrap-vue/bootstrap-vue#5802]
### Describe the bug

I have a `<b-table />` and `<b-button />` inside a `<div class="d-flex justify-content-between">`. The table is extending the full width of the div, overlapping with the button.

### Steps to reproduce the bug
[![Edit practical-silence-4otyx](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-silence-4otyx?fontsize=14&hidenavigation=1&theme=dark)

### Expected behavior

I expect the table width to reduce to make space for the button, similar to how a w-100 button will size appropriately (shown in sandbox).

This used to work for us in our production environment about 4 months ago. I tried rolling back the bootstrap and bootstrap-vue versions but didn't find a working combination.

### Versions

**Libraries:**

- BootstrapVue: 2.17.1
- Bootstrap: 4.5.2
- Vue: 2.6.12

**Environment:**

- Device: Desktop
- OS: Windows
- Browser: Chrome / Firefox 
- Version: 85 / 80

**Comment by jackmu95** [comment]
@arthurmcgregor I'am not sure what changed the behavior since we didn't had any `<b-table>` SCSS/CSS changes in the last few months. But you would anyway be better off wrapping the table in a `<div>` with the `flex-grow-1` utility class applied:

https://codesandbox.io/s/quizzical-germain-82dqx

**Comment by arthurmcgregor** [comment]
Great thanks! That solves the problem
