### ISSUE TITLE
Support transition duration on b-collapse

### ISSUE THREAD

**Issue by lexicalunit** [bootstrap-vue/bootstrap-vue#5803]
### Is your feature request related to a problem? Please describe...

Currently the `b-collapse` component eats any props a user passes to it: https://github.com/bootstrap-vue/bootstrap-vue/blob/master/src/components/collapse/collapse.js#L245

Whereas the `bv-collapse` utility component seems to pass them along nicely: https://github.com/bootstrap-vue/bootstrap-vue/blob/master/src/utils/bv-collapse.js#L74

This means that some of the functionality of Vue's `transition` element isn't available to users of `b-collapse`. For example, there's no way to change the `duration` property, which is new in versions 2.2.0+ of Vue: https://vuejs.org/v2/guide/transitions.html#Explicit-Transition-Durations

### Describe the solution you'd like

Allow properties to flow from `b-collapse` through `bv-collapse` and ultimately to `transition`. Or at the very least add support for the `duration` property alone.

**Comment by Hiws** [comment]
If it's a global change you're looking to make, you can customize the `$transition-collapse` SCSS variable to increase the size of the transition.

Example:
`$transition-collapse: height 2s ease;`

**Comment by lexicalunit** [comment]
Nice workaround @Hiws!  It won't help in my specific case though. But I'm sure others could use it.
