### ISSUE TITLE
Carousel shows transparent parts when scrolling too fast

### ISSUE THREAD

**Issue by guyguy2001** [bootstrap-vue/bootstrap-vue#5810]
### Describe the bug

When sliding too fast to the right and then to the left (sometimes only in the other direction), a big transparent region appears.
![image](https://user-images.githubusercontent.com/6932278/93604519-25254480-f9ce-11ea-89aa-be4ece45744c.png)
![image](https://user-images.githubusercontent.com/6932278/93604551-2f474300-f9ce-11ea-959b-f587fcd9b672.png)

### Steps to reproduce the bug

Go to https://bootstrap-vue.org/docs/components/carousel
Scroll to the first carousel.
Move to the 3rd slide. Then, click on the 2nd slide button, and _before it finished sliding_, click on the 3rd slide button.
On our website (github.com/eternagame/eternagame.org), it seems like it happens in the other direction - To produce it there, I need to click on the 3rd button and click on the 2nd button while it is still sliding to the right.

### Versions

**Libraries:**

On eterna:
- BootstrapVue: 2.6.11
- Bootstrap: 4.5.0
- Vue: 2.15.0

On the bootstrap-vue documentation:
I'm not sure about the versions used in the docs; As of filing this issue, the master of this repo is on 2f00167, and dev is on f018beb, but I haven't built the docs locally.

**Environment:**

- Device: Windows PC
- OS: Windows 10 19041.508
- Browser: Chrome
- Version: 85

### Demo link

I haven't made my own demo, as it is reproducible on the [documentation page](https://bootstrap-vue.org/docs/components/carousel).
If needed I'll add one and edit the issue.

### Additional context

Video example: 
https://drive.google.com/file/d/16USTsuqA9O7nr3A802t4oTwU1pE08ZUc/view?usp=drivesdk

**Comment by Hiws** [comment]
Could you confirm whether or not the issue is fixed here: 
<https://bootstrap-vue-git-fork-hiws-b-carousel-fix-slide-glitching.bootstrap-vue.vercel.app/docs/components/carousel#carousel>

You can also install it locally by using the following url:
`npm install https://pkg.csb.dev/bootstrap-vue/bootstrap-vue/commit/76500af6/bootstrap-vue`
