### ISSUE TITLE
Toast not work after deploy

### ISSUE THREAD

**Issue by soroka41** [bootstrap-vue/bootstrap-vue#5813]
"bootstrap": "^4.5.2",
    "bootstrap-vue": "^2.16.0",
    "core-js": "^3.6.5",
    "nuxt": "^2.14.5"

Tost not work after deploy in prodactiov ssr and not ssr nuxt 
Development this is good
toast() {
      this.$bvToast.toast(`Toast with action link`, {
        href: "#foo",
        title: "Example"
      });
    }
In pdod not work

**Comment by AutoAwesome** [comment]
I have the same issue. Works fine on dev. But does nothing on prod. Prints nothing to the dev-console.

**Comment by AhmadOf** [comment]
I have same issue here an in Hot reload module it is working fine but not for production at all and there is no error shown in console.

**Comment by jackmu95** [comment]
Can someone please create a minimal reproduction of the issue on CodeSandbox or a project that I can check out locally.

**Comment by AutoAwesome** [comment]
This is odd. I just tried to create a minimal example for you, but in my example it works just fine.

Going to tinker further with the example. In meantime we used another lib on top of bootstrap-vue to show toasts.

**Comment by AutoAwesome** [comment]
So... Toast started to work for me. Also on production. I haven't changed anything I am aware of. :smile: I guess for me this issue is solved as I cannot reproduce it anymore.
