### ISSUE TITLE
Form datepicker - October is missing

### ISSUE THREAD

**Issue by guillaume-guerdoux** [bootstrap-vue/bootstrap-vue#5818]
### Describe the bug

Hello,

When using bootstrap form-datepicker (on safari or firefox), I discovered that the October month was missing for the years before 1995. It passes automatically to November

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.org/docs/components/form-datepicker
2. Click on the calendar input 
3. Choose a year before 1995 and position your date on September month
4. Click on the next arrow
4. See error (it passes from September to November)

### Expected behavior

Have the October month

### Versions

**Libraries:**

- BootstrapVue: 2.15.0

**Environment:**

- Device: All
- OS: Ubuntu / Windows / Mac OS
- Browser: Safari

**Comment by Hiws** [comment]
I can't reproduce this in Chrome 85, IE11, Firefox 80 or Chromium Edge 85. 
All on Windows 10.

 @jackmu95 Can you test this on Safari?
