### ISSUE TITLE
Semantical error on Modal page

### ISSUE THREAD

**Issue by Jaykju** [bootstrap-vue/bootstrap-vue#5822]
### Documentation issue

- [x] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs/components/modal#prevent-closing

### Additional context or description

The *Note* text below the code sample includes:

> Event hide is always emitted, even if ok, cancel, and close are **emitted**.

I think it should be

> Event hide is always emitted, even if ok, cancel, and close are **omitted**.

**Comment by jackmu95** [comment]
@Jaykju This is not a typo. The text is intended like this.
