### ISSUE TITLE
:variant

### ISSUE THREAD

**Issue by fr1k** [bootstrap-vue/bootstrap-vue#5823]
when I set the variant parameter like this:
:variant="{ 'dark': item.done }"
"item.done" its true or false, write this:
"Invalid prop: type check failed for prop "variant". Expected String with value "[object Object]", got Object ".
But there must be a String.

**Comment by Hiws** [comment]
Variant doesn't support that syntax.

You can do this instead.
`:variant="item.done ? 'dark' : null"`
