### ISSUE TITLE
Hamburger menu does not close after loading a new route

### ISSUE THREAD

**Issue by sowinski** [bootstrap-vue/bootstrap-vue#5827]
Hi,

I am not sure if this is a bug or a feature.

If someone opens on a mobile device the hamburger menu and click on a link to change the route then my hamburg menu does not close. 

Of course, I could write some code to close it after the route has been loaded but I think I am doing something wrong and it should close out of the box. Is my assumption correct?

Thank you

**Comment by Hiws** [comment]
Default behavior should cause the that the navigation collapses after changing route.
Could you provide some more information about your code, or a reproduction?

Tested it locally, with the below code and it closed as expected.
```html
<b-navbar type="dark" variant="dark" toggleable>
  <b-navbar-brand href="#">NavBar</b-navbar-brand>
  <b-navbar-toggle target="navbar-collapse"></b-navbar-toggle>

  <b-collapse id="navbar-collapse" is-nav>
    <b-navbar-nav>
      <b-nav-item to="/">Home</b-nav-item>
      <b-nav-item to="/about">About</b-nav-item>
    </b-navbar-nav>
  </b-collapse>
</b-navbar>
```
![dCab3d7nsD](https://user-images.githubusercontent.com/7057431/94125406-96de1200-fe56-11ea-93d1-cb1cfea85225.gif)

**Comment by TheAndroidGuy** [comment]
I am having the same issue.
It works properly on desktop but it is inconsistent on mobile devices.

**Comment by Hiws** [comment]
Any specific devices/browsers you have issue with?
and can you provide a reproduction that shows the issue, since I can't reproduce it on Chrome, Android.

**Comment by TheAndroidGuy** [comment]
@Hiws it probably requires complex example (routes and more components).
I tried on simple example it works properly.
I tried more "complex" [example ](https://jsfiddle.net/ok9qrvsc/5/)but still cannot reproduce the issue.

**Comment by sowinski** [comment]
@Hiws 

Thank you. 

Because <b-nav-item> do not support slots, I started build my own component which looks like that.

 ```
 <li
    v-if="show_item"
    :key="item.id"
    :class="{ 'hide-above-tablet': item.display_type == 3 }"
    class="nav-item"
  >
    <b-link
      :href="item.href"
      :to="item.to"
      :class="{ 'btn btn-primary btn-block': item.item_type == 1 }"
    >
      {{ item.name }}
    </b-link>
    <span v-if="count" class="notification bookingrqstcnt">
      {{ count }}
    </span>
  </li>
```
Using <b-link> do not close the menu.

Any idea what I could do?

**Comment by sowinski** [comment]
I just replaced my li tag with a b-nav-item tag and just added my span tag in between without any problems. not sure why I did it so complicated at the beginning....

```
  <b-nav-item
    v-if="show_item"
    :key="item.id"
    :class="{
      'hide-above-tablet': item.display_type == 3,
      'btn btn-primary btn-block': item.item_type == 1
    }"
    class="nav-item"
    :href="item.href"
    :to="item.to"
  >
    {{ item.name }}
    <span
    >
      {{ count }}
    </span>
  </b-nav-item>
```

Thank you
