### ISSUE TITLE
Overlay b-card footer issue

### ISSUE THREAD

**Issue by abspen1** [bootstrap-vue/bootstrap-vue#5828]
### Describe the bug

When you add a footer to a card that is using overlay, everything shows as you would expect. However, any links/buttons in the footer do not register as clickable.

### Steps to reproduce the bug
```bash
<template>
  <div>
    <b-card
      overlay
      img-src="https://picsum.photos/900/250/?image=3"
      img-alt="Card Image"
      text-variant="white"
      title="Image Overlay"
      sub-title="Subtitle"
      footer-tag="footer"
    >
      <b-card-text>
        Some quick example text to build on the card and make up the bulk of the
        card's content.
      </b-card-text>
      <template v-slot:footer>
        <b-button
          size="md"
          href="https://github.com/bootstrap-vue/bootstrap-vue"
        >
          bootstrap-vue GitHub
        </b-button>
        <a
          class="float-right"
          href="https://github.com/bootstrap-vue/bootstrap-vue"
          >bootstrap-vue GitHub</a
        >
      </template>
    </b-card>
  </div>
</template>
```

1. Copy the code above
2. Paste into your Vue environment
3. Try to click on the button/link

### Expected behavior

I expected to be able to use buttons/links in the footer of an overlay image card. I noticed in the docs footers aren't supported with left/right align. "Note headers and footers are not supported when images are left or right aligned. You may find the Horizontal Card Layout example to be more flexible when creating a responsive horizontal card." But didn't find anything about support with overlay images. This could be because the footer shows up as expected, the only issue I have experienced with it is the buttons/links.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.3.1
- Vue: 2.6.11

**Environment:**

- Device: [Mac]
- OS: [macOS Mojave]
- Browser: [Chrome]
- Version: [85.0.4183.102]

### Demo png
![Screen Shot 2020-09-23 at 12 05 56 PM](https://user-images.githubusercontent.com/57128609/94060459-dba37380-fd98-11ea-8c2b-445099b7b28f.png)

### Additional Info

This might be an easy fix and an oversight by myself. Thanks in advance!

**Comment by Hiws** [comment]
Yeah, that's not intended.
Will look at see if there's an easy fix.

Here's a workaround for now.
```html
<b-card text-variant="white" no-body>
  <div class="position-relative">
    <b-card-img src="https://picsum.photos/900/250/?image=3" top></b-card-img>
    <b-card-body class="card-img-overlay">
      <b-card-title>
        Image Overlay
      </b-card-title>
      <b-card-sub-title>
        Subtitle
      </b-card-sub-title>
      Some quick example text to build on the card and make up the bulk of the card's content.
    </b-card-body>
  </div>
  <b-card-footer>
    <b-btn @click="alert('Hello')">
      Click me
    </b-btn>
  </b-card-footer>
</b-card>
```

<https://codepen.io/Hiws/pen/NWNoqOa>
