### ISSUE TITLE
Overlay blur broken

### ISSUE THREAD

**Issue by TheAndroidGuy** [bootstrap-vue/bootstrap-vue#5829]
The overlay blur is not working.

### Steps to reproduce the bug

1. Go to [Overlay](https://dev.bootstrap-vue.org/docs/components/overlay#overlay-backdrop-color)
2. Change blur
3. The blur is not working in Chrome, Firefox
4. The blur **is** working in Microsoft Edge 85

### Versions
v2.17.3

**Libraries:**

- BootstrapVue: 2.17.3
- Bootstrap: 4.5.2
- Vue: 2.6.12

**Comment by Hiws** [comment]
Given that it works in Firefox (by enabling `backdrop-filter` in `about:config`) and Chromium Edge, i believe it's a Chrome specific browser bug.

**Comment by Hiws** [comment]
Looks like it's problem in Chrome when combining `opacity` and `backdrop-filter: blur`.
<https://bugs.chromium.org/p/chromium/issues/detail?id=1129838>

**Comment by jackmu95** [comment]
The Blur is working for me with Chrome 86 on macOS.

**Comment by TheAndroidGuy** [comment]
Not working for me with Chrome 86 on Windows.
