### ISSUE TITLE
Cherry Pick is not working properly

### ISSUE THREAD

**Issue by vsirghii** [bootstrap-vue/bootstrap-vue#5832]
Hello,
I'm trying to use Bootstrap-vue individual components (Table in my case) instead of the whole framework. According to your docs all I have to do is:
```
import TablePlugin from "bootstrap-vue"
Vue.use(TablePlugin)
```
and then down the code I use only `<b-table>` element of the Bootstrap-vue framework.

This works perfectly fine, but it increases my bundle with extra ~500 KB. As I understand, it means I'm getting too much from Bootstrap-vue. Because if I do instead the following:
```
import BootstrapVue from "bootstrap-vue"
Vue.use(BootstrapVue)
```
the result is the same: table works fine and the bundle size is the same.
I'm not sure what is 'TablePlagin' here if it makes no difference with the 'BootstrapVue'?

Trying the following: 
`import {Table} from 'bootstrap-vue/esm/components'`
throws an error that it can not find Table component.

What I'm doing wrong here? The ultimate goal is to pick up the Table component only to my vuejs project.

**Comment by jackmu95** [comment]
Please see the [Importing as a Vue.js plugin](https://bootstrap-vue.org/docs/components/table#importing-as-a-plugin) section for each component on how to import the plugin correctly.

Here is a CodeSandbox with only the `<b-table>` plugin in use:
https://codesandbox.io/s/jolly-dust-x2krh

**Comment by vsirghii** [comment]
Got it, thanks!
It appears I was missing curly brackets in my statement:
Instead of `import TablePlugin from "bootstrap-vue"` I had to do `import { TablePlugin } from "bootstrap-vue"`
such a small detail and such a big difference.
