### ISSUE TITLE
Toasts no-auto-hide and no-close-button example

### ISSUE THREAD

**Issue by marcgauch** [bootstrap-vue/bootstrap-vue#5837]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs/components/toast#accessibility-tips
>When setting prop no-auto-hide to true, you must have a close button to allow users to dismiss the toast. If you have also set prop no-close-button to true, you must provide your own close button or dismiss the toast by some other means. Toasts have a tab index of 0 so that they can be reached by keyboard-only users.

### Additional context or description
Using
```this.$bvToast.toast('TEXT', { title: 'TITLE', noAutoHide: true, noCloseButton: true })```
what are the own possibilities to close the toast?

```
const vNodesMsg = this.$createElement(
  'b-button',
  {
    on: {
      click: () => {
        // What to write here?
      }
    }
  },
  ['CLOSE']
)

this.$bvToast.toast([vNodesMsg], { title: 'TITLE', noAutoHide: true, noCloseButton: true })
```

Could this make it in to the documentation please?

**Comment by Hiws** [comment]
Provide your toast with a unique `id`, and utilize the `this.$bvToast.hide(yourId)` method to hide the toast again.

https://codepen.io/Hiws/pen/QWNPpPL
