### ISSUE TITLE
Allow for `treeShake` to be set by the user in the nuxt module

### ISSUE THREAD

**Issue by samturrell** [bootstrap-vue/bootstrap-vue#5851]
### Is your feature request related to a problem? Please describe...

I'm building a module which lazy loads specific components. This sometimes means that the `components` option is either not set or an empty array.

According to the code, if this value is empty, `treeShake` is always set to false, and the entirety of `bootstrap-vue` is loaded.

### Describe the solution you'd like

I'd like to be able to pass `treeShake: true' in the nuxt module config.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by samturrell** [comment]
@jackmu95 any thoughts on this?

**Comment by jackmu95** [comment]
@samturrell Can you please share a minimal example of what you are doing with the module so I can test the public `treeShake` option.

You can just fork our Nuxt.js starter template on CodeSandbox:
https://codesandbox.io/s/bootstrapvue-nuxtjs-starter-project-xblbj

**Comment by samturrell** [comment]
> @samturrell Can you please share a minimal example of what you are doing with the module so I can test the public `treeShake` option.
> 
> You can just fork our Nuxt.js starter template on CodeSandbox:
> [codesandbox.io/s/bootstrapvue-nuxtjs-starter-project-xblbj](https://codesandbox.io/s/bootstrapvue-nuxtjs-starter-project-xblbj)

Hi @jackmu95 - in the following example, `BButton` and `BAlert` should not be loaded because the `components` array is empty. https://codesandbox.io/s/priceless-almeida-sqzsf

**Comment by samturrell** [comment]
To provide further context of why this is important for my use case, in our default project template we want to provide the bootstrap-vue components config as empty to encourage the practice of only pulling in what's needed for the project, rather than all components being loaded by default. 

Currently if we set that as empty it will pull in every component regardless and will not have the desired effect of enforcing this best practice.
