### ISSUE TITLE
erratic behaviour on custom table header

### ISSUE THREAD

**Issue by PierBover** [bootstrap-vue/bootstrap-vue#586]
When using this:
```
<template slot="HEAD_selected" scope="data">
	<input type="checkbox" v-model="allSelected">
	{{allSelectedCheckbox}}
</template>
```
The checkbox won't change. If I move the checkbox outside of the table it works fine.

It seems the problem is related to the column sorting. I have disabled it for that column but I still get an erratic behaviour as you can see here. Don't mind the hand cursor, I have enabled it for the table with CSS.

![2017-06-30 01_16_53](https://user-images.githubusercontent.com/226483/27723282-e840f91a-5d31-11e7-8c14-4fa0df3f8444.gif)

**Comment by tmorehouse** [comment]
Ah, you need to add a `@click.stop` handler on your checkbox to stop the regular header-click event from happening.

```html
<input type="checkbox" @click.stop="toggleSelected" v-model="allSelected">
```

Take a look at this fiddle for an example: https://jsfiddle.net/dyzs5txk/

What is happening is that the click of a non-sortable header clears the sort, so you need to stop propagation from your checkbox upwards to the header cell.

**Comment by alexsasharegan** [comment]
@tmorehouse, so the modifiers work on custom events too? I wasn't sure about that on #588

**Comment by tmorehouse** [comment]
It appears to work on native checkboxes (which I have used in the fiddle). You might need to use the `.native` modifier on the customer checkbox.

**Comment by alexsasharegan** [comment]
<img width="632" alt="screen shot 2017-06-30 at 6 07 09 am" src="https://user-images.githubusercontent.com/16269252/27736770-75489480-5d5a-11e7-8d47-875560ce8947.png">

**Comment by PierBover** [comment]
Thanks for the example @tmorehouse !

I?m guessing this is expected behaviour then?

**Comment by tmorehouse** [comment]
Yeah, somewhat, as each header cell has an onclick handler for sorting and notification.

**Comment by tmorehouse** [comment]
The example is a prototype of `b-table`.  I'll be making an updated fiddle for the docs which includes the new features, which will include an example using checkboxes.

**Comment by PierBover** [comment]
It's working now.

`<input type="checkbox" @click.stop="toggleAllSelected" v-model="allSelected">`

The thing is I don't really need the method `toggleAllSelected` since `allSelected` is a computed property with get/set, so it's an empty method now.

```
allSelected: {
	get () {
		return this.selectedOrders.length === this.filteredOrders.length;
	},
	set (newValue) {
		if (newValue) this.selectAllOrders();
		else this.unselectAllOrders();
	}
}
```

Is there any other way I can solve this without resorting to an empty method?

**Comment by PierBover** [comment]
This did it

`@click.stop=""`

:D

**Comment by alexsasharegan** [comment]
@PierBover, I believe you can even get as terse as `@click.stop`

**Comment by PierBover** [comment]
I guess I should close this.

The example should be on the docs though.

**Comment by tmorehouse** [comment]
I'll update the table docs to mention using `@ckick.stop` on controls within the header/footer custom slots
