### ISSUE TITLE
How to clear old toasts before showing a new toast?

### ISSUE THREAD

**Issue by prempopatia** [bootstrap-vue/bootstrap-vue#5868]
### Is your feature request related to a problem? Please describe...

When toast is triggered for more then 1 times, it is just starts to add toast (irrespective of what user has specified as prepend/append)

### Describe the solution you'd like

There should be some solution which only allows to open 1 toast only / or user defined number of times only. If new one is triggered than old one should be removed or hidden.

### Describe alternatives you've considered

Till now i havent came to any alternatives.

### Additional context

To be precise, Toast is shown multiple times if toast is triggered before closing delay of previous toast.

**Comment by prempopatia** [comment]
Any update on above request?

**Comment by jakedolan** [comment]
I was looking for this ability with the case of reporting errors that may happen in quick succession and only want to report the last error.

For others looking for an easy workaround for limiting messages of a single type, you can use the id property and close instances of it prior to creating the next. 
```
this.$bvToast.hide(toastId);
this.$bvToast.toast(message, { id: toastId });
``` 

Doesn't replace the need for the FR above, but at least it may handle a use case.
