### ISSUE TITLE
b-pagination-nav: Next page button skips a page

### ISSUE THREAD

**Issue by Zhythero** [bootstrap-vue/bootstrap-vue#5870]
**Describe the bug**
When the next button of a `b-pagination-nav` is clicked, a page is skipped (acts like been double clicked)
This happens when using `use-router` and `value` (not `v-model`) props

**Versions**
Libraries:

BootstrapVue: 2.17.3
Bootstrap: 4.3.1
Vue: 2.6.3

Device: Windows PC
Browser: Chrome
Version: 86.0.4240.75 (Official Build) (64-bit)
Demo link
Replicated in the Online Playground and exported to [Codesanbox](https://codesandbox.io/s/zen-cohen-qdrj1?file=/App.vue)

EDIT: Followed issue format

**Comment by jackmu95** [comment]
The problem is that you provide a computed `value` prop based on `this.$route.params.page`.

You need to use `v-model` instead:
https://codesandbox.io/s/intelligent-engelbart-vyir7?file=/App.vue

**Comment by Zhythero** [comment]
I see.  So we need to initiate a value to a data, then let pagination handle it after. Thanks!
