### ISSUE TITLE
Sidebar with v-model and backdrop gives prop mutation warning

### ISSUE THREAD

**Issue by jd-0001** [bootstrap-vue/bootstrap-vue#5873]
### Describe the bug

I am using sidebar component for my complex app where I have button in one component and sidebar in third component and second component SFC contains root(the data property I pass as prop)

### Steps to reproduce the bug

1. Go to [Sandbox](https://codesandbox.io/s/bsv-sidebar-issue-k83ew)
2. Click on Open SIdebar
3. Click on backdrop to close it
4. See error in console

### Expected behavior

I already added sync modifier and also tried `hidden` event from sidebar but all of them gives prop mutation error

### Versions

**Libraries:**

- BootstrapVue: 2.17.3
- Bootstrap: 4.5.2
- Vue: 2.6.12

**Environment:**

Code Sandbox

### Demo link

Please check reproduction step link

### Additional context

Also If I use the hide method from scoped slots it gives the same warning

**Comment by jackmu95** [comment]
The problem is is not the `<b-sidebar>` component - it's the way you try to pass down/sync the `active` value.

See this modified example:
https://codesandbox.io/s/bsv-sidebar-issue-forked-7dnu2

**Comment by jd-0001** [comment]
Certainly, I have missed this in the API of Vue. Thanks for letting me know about the existence of a `model`.
