### ISSUE TITLE
how to do nested menus in dropdown

### ISSUE THREAD

**Issue by DebaPrasad14** [bootstrap-vue/bootstrap-vue#5877]
I am working on a feature where nested dropdown is required but I couldn't find a way to achieve that using bootstrap. so is there any way we can achieve that nested dropdown? Thanks in advance, can anyone help me out here as I need this on an urgent basis.

**Comment by Hiws** [comment]
Multilevel dropdowns are supported (yet), see https://github.com/bootstrap-vue/bootstrap-vue/issues/3435.

There are ways to hack it, like shown on this stackoverflow question.
<https://stackoverflow.com/questions/63357651/bootstrap-vue-multi-level-drop-down>
