### ISSUE TITLE
b-form submit.prevent doesn't work

### ISSUE THREAD

**Issue by yordis** [bootstrap-vue/bootstrap-vue#588]
I have this
```
  <b-form v-on:submit.prevent="onSubmit" class="col-sm-12 col-md-6">
     ....
     <b-button type="submit" variant="primary">Register</b-button>
  </b-form>
```
and the `onSubmit` method is not being called and it works with regular `form` tag

**Comment by mosinve** [comment]
Why you use prevent modifier? Did you try without it?

**Comment by yordis** [comment]
@mosinve what do you mean?

**Comment by yordis** [comment]
@alexsasharegan it does work. Could you send me some info about that `native` thing? Also is there anyway to avoid this? I don't want to be paying attention to those details if possible

**Comment by alexsasharegan** [comment]
So I'm not sure if we can provide the same event binding modifiers on custom components that vue does on native elements. Ultimately, we can save code size by not attempting to manually re-emit all native events on a given vue component. I personally don't think the `v-on:event.native` modifier gets a big enough mention in the docs. It's going to become very important as component libraries become more popular in vue.

## Resources
- [v-on API reference](https://vuejs.org/v2/api/#v-on)
- [v-on with custom components (you may need to scroll up a tad](https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components)
- [vue issue #3253](https://github.com/vuejs/vue/issues/3253#issuecomment-254018976)

**Comment by alexsasharegan** [comment]
I may open a PR on vue to better document this very necessary feature.

**Comment by alexsasharegan** [comment]
Follow the issue at vue [#6003](https://github.com/vuejs/vue/issues/6003)

**Comment by tmorehouse** [comment]
I was working on a form.vue component the other day until I realized we had one (but wasn't in the docs).

The mockup I had originally included Vue handlers  for submit and additional props for setting action, method and encoding.

We could add a few tweaks to the `b-form` to propagate a vue component "submit" event, based on the presence (or lack there of) of action, etc.

**Comment by alexsasharegan** [comment]
I'm worried that it may be more trouble than it's worth because the modifiers likely won't function on the inline binding syntax.

**Comment by alexsasharegan** [comment]
P.S. Here's possibly the issue that initiated the `.native` modifier: https://github.com/vuejs/vue/issues/2942

**Comment by alexsasharegan** [comment]
https://github.com/vuejs/vue/issues/2942

**Comment by alexsasharegan** [comment]
The issue has been moved to the website repo: https://github.com/vuejs/vuejs.org/issues/979

**Comment by meyt** [comment]
in my case form submit event works if you have not form input more than one! 
this sample works fine:
https://jsfiddle.net/j08b7c4o/23/
```html
<b-form v-on:submit.prevent="alert('SUBMIT')">
    <b-form-input v-model="text" type="text"></b-form-input>
</b-form>
```

but this is not:
https://jsfiddle.net/j08b7c4o/22/
```html
<b-form v-on:submit.prevent="alert('SUBMIT')">
    <b-form-input v-model="text" type="text"></b-form-input>
    <b-form-input v-model="text2" type="text"></b-form-input>
</b-form>
```

**Comment by tmorehouse** [comment]
PR #636 should address this issue and allow you to just use `@click="onSumnit($evemt)"` and in your `onSubmit` handler you can do a `preventDefault()` and `.stopPropagation()` on the event to stop the form from being submitted.

**Comment by mosinve** [comment]
But why to add code to mimic Vue original behavior?
If someone goint to write with Vue - he must be ready to read Vue docs

**Comment by tmorehouse** [comment]
True... but since it is a component, some people expect it to emit the events, this is just a convenience method.  Users can still work with `.native`.

The new documentation (for v0.18.0) has a little note at the bottom of each component page that reminds users of the `.native` modifier, with  link to the Vue docs.

**Comment by Overdrivr** [comment]
If like me, it's the third time you face weird behavior with your forms (for instance, using `v-on:submit.native.prevent="onSubmit"` still does not prevent redirection if you press enter), the only correct way to make forms is:

```
<b-form @submit.prevent>
   <b-button type="submit"></b-button>
</b-form>
```

As far as I've tried, any other technique causes unwanted redirections (either by pressing the button or pressing Enter)
