### ISSUE TITLE
Not working for IE

### ISSUE THREAD

**Issue by ngoclx** [bootstrap-vue/bootstrap-vue#5893]
The "form" elements like b-form-checkbox, b-pagination, etc don't work on IE.
The website uses bootstrap-vue with gridsome.

### Steps to reproduce the bug
http://sydneyhealthpartners.org.au/news

### Versions
**Libraries:**
    "bootstrap-vue": "^2.16.0",
    "bootstrap": "^4.5.2",
    "gridsome": "^0.7.0",

**Comment by ngoclx** [comment]
![image](https://user-images.githubusercontent.com/4980223/95882798-519d6800-0da4-11eb-90e6-07ced629b85e.png)

Pls check the attached image. The site doesn't react to any click to checkbox/pagination. I tried to add babel-polyfill but not 100% sure if it works.

**Comment by Hiws** [comment]
That's a polyfill issue, so you will have to configure your project to do that.

The browser support section has a small section about adding it, but it might be different for Gridsome.
<https://bootstrap-vue.org/docs#js>

Alternatively you can try <https://polyfill.io/>, which from my experience is easier to set up.

**Comment by ngoclx** [comment]
I even tried to put both babel polyfill and polyfill.io but it is still not good.

![image](https://user-images.githubusercontent.com/4980223/95931222-be3f5380-0df2-11eb-8b2d-0901f429636e.png)

**Comment by ngoclx** [comment]
Sorry guys, it was actually a bug from flexsearch plugin of gridsome. I'll be closing this tiket!
