### ISSUE TITLE
add variant to the b-form-checkbox-group with switches style

### ISSUE THREAD

**Issue by farshadfahimi** [bootstrap-vue/bootstrap-vue#5900]
this is good Idea to have variant in the checkbox with switches style like below

```vue
<b-form-checkbox-group
        v-model="selected"
        :options="options"
        variant="danger"
        switches
      ></b-form-checkbox-group>
```
and if you are agree with that is it possible to do it my self and create a merge request?

**Comment by jackmu95** [comment]
@farshadfahimi Feel free to submit a PR :)
