### ISSUE TITLE
b-dropdown is not rendering any css class

### ISSUE THREAD

**Issue by aakashbashyal21** [bootstrap-vue/bootstrap-vue#5903]
I am using bootstrap-vue to add `<b-dropdown>` components, but the button doesn't have an effect on adding any CSS class.

Is this some bug with the **b-dropdown** component or I am doing something wrong while adding a class?

```
<b-dropdown button-class="btn btn-danger d-flex align-items-center mr-2 justify-content-center rounded-circle btn-circle" no-caret>
    <template v-slot:button-content>
            <i class="fas fa-cog fa-lg"></i>
          </template>
    <b-dropdown-item href="#">An item</b-dropdown-item>
    <b-dropdown-item href="#">Another item</b-dropdown-item>
  </b-dropdown>
```
https://jsfiddle.net/abashyal21/gq253y61/3/

**Comment by jackmu95** [comment]
@aakashbashyal21 You are using the wrong prop.
Make sure to use the `toggle-class` prop for `<b-dropdown>`.

**Comment by aakashbashyal21** [comment]
Thank you that worked!
