### ISSUE TITLE
Is it possible to get the filtered items in a <b-table>?

### ISSUE THREAD

**Issue by wsw70** [bootstrap-vue/bootstrap-vue#591]
I built a `<b-table>` with a `:filter` option, it works.

Is it possible to retrieve a list of the filtered elements? (what I actually would like to do is to show the table via a `<v-if>` only if there are more than one filtered elements)

**Comment by tmorehouse** [comment]
Yes,

you can v-bind a variable to b-table.  This variable will contain the visible items in the table.  It will be limited to the page size though.

See section **v-model Binding** in the new docs https://bootstrap-vue.js.org/docs/components/table

**Comment by wsw70** [comment]
Thank you. This is exactly what I was looking for but I cannot get the reactivity part. I have an input and a table liked to that input:

```
<div>
  <b-form-input v-model="incident.ImpactedArea"></b-form-input>
  <b-table :items="impactedAreas" :fields="{area:{}}" :filter="incident.ImpactedArea" :small="true" v-model="ImpactedAreasDisplayed" v-if="ImpactedAreasDisplayed.length != 1"></b-table>
</div>
```

The idea behind this code is that `ImpactedAreas`  is computed (several items) and the filtering is done based on the content of the input (bound to `incident.ImpactedArea`). This filtering works fine when I type into the input, the table reflects the filtered elements.

I then wanted to display the table only when there are several or zero filtered elements. `ImpactedAreasDisplayed` initially has the right content (one element) but when I modify the input content, `ImpactedAreasDisplayed` does not change (despite the fact that there are more filtered elements), and therefore the chooser (table) does not appear.

To clarify: without the `v-if` I get the table initially filtered (the input exists by default) - to one element. Modifying this input alters the table (filtering). This is OK as well. It is just the `v-model` variable which does not get updated (even though its initial value is OK)

**Comment by wsw70** [comment]
OK, I found the problem.

I am not sure why, but the `v-if` impacts the `v-model` variable. When using `v-show` instead I get the expected effect.

**Comment by tmorehouse** [comment]
`v-if` removes the component and it's reactivity, so the `v-bind` content will not change, until it is re-enabled.
