### ISSUE TITLE
b-modal bounces left right when used with toggleable areas that make it bigger than the vertical viewport

### ISSUE THREAD

**Issue by mircone** [bootstrap-vue/bootstrap-vue#5913]
Hey guys, I'm building a modal with toggleable areas. When the modal gets bigger than the viewport on the right side the scrollbar appears. Directly after this padding-left is applied. That causes that the modal first jumps to the left and then beacause of the padding-left back in position.

Is there a way to prevent that bouncy movement? It feels like there is a transition or something on it. My current solution is to permanently applie the scroll bar with "overflow-y: scroll" and unset the padding with "padding-left: unset". 

Kind regards.

**Comment by jackmu95** [comment]
@mircone Can you please provide a minimal demo of what exactly you want to archive and what the issue is.

**Comment by mircone** [comment]
Sure, I created a fiddle with it:
https://jsfiddle.net/mircone/7w5x6yde/

When you open the modal and click one or two of the collapse buttons (depending on your viewport size) you will see the modal bouncing left right when the collapse goes over the view port. It would be nice if the modal would stay in middle of the view without that movement.

**Comment by jackmu95** [comment]
@mircone Can you please provide the following environment information.
I can't reproduce the issue in Chrome on macOS.

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

**Comment by mircone** [comment]
Environment:

    Device: [Windows PC]
    OS: [Windows 10]
    Browser: [Chrome]
    Version: [Version 86.0.4240.111 (Offizieller Build) (64-Bit)]

**Comment by jackmu95** [comment]
@Hiws Can you confirm the described behavior on Windows?

**Comment by Hiws** [comment]
@jackmu95 Yes, I think I see the issue.
You can see in the below gif that the modal is first pushed left, and then back to the right shortly after.
![kYRbWWXXKj](https://user-images.githubusercontent.com/7057431/97868673-67051280-1d10-11eb-8a78-bf4580d4d7db.gif)


This happens because the scrollbar first appears, pushing it left, and then shortly after a `padding-left: 17px` is added to the 2nd outer modal element, pushing it back to the right.

**Comment by jackmu95** [comment]
@Hiws Thanks for the video.
This doesn't happen on macOS.

**Comment by mircone** [comment]
> 
> 
> @jackmu95 Yes, I think I see the issue.
> You can see in the below gif that the modal is first pushed left, and then back to the right shortly after.
> ![kYRbWWXXKj](https://user-images.githubusercontent.com/7057431/97868673-67051280-1d10-11eb-8a78-bf4580d4d7db.gif)
> 
> This happens because the scrollbar first appears, pushing it left, and then shortly after a `padding-left: 17px` is added to the 2nd outer modal element, pushing it back to the right.
> The opposite happens when the scrollbar disappears.

With which tool did you create the gif @Hiws? I was on the way to provide one to, but endet with a gif of 20mb via MiniTool MovieMaker.

**Comment by Hiws** [comment]
> With which tool did you create the gif @Hiws? I was on the way to provide one to, but endet with a gif of 20mb via MiniTool MovieMaker.

I use ShareX.

**Comment by andrei-gheorghiu** [comment]
A simple workaround for this issue: 

    .modal-body {
      max-height: calc(100vh - 195px);
      overflow-y: auto;
    }
