### ISSUE TITLE
Question: Adding prop in <b-table> scope

### ISSUE THREAD

**Issue by jinniw43805** [bootstrap-vue/bootstrap-vue#5915]
Is any possible we can have other props in b-table scoped slot?

I checked the document for [scoped slot in b-table](https://bootstrap-vue.org/docs/components/table#comp-ref-b-table-slots), but not able to use the additional prop in some other scoped slot

For example: 

The cell({key} slot has following props:

- index

- item

- value

- **_unformatted_**

What if we want to have the **_unformatted_** prop in row-details scoped slot? The unformatted prop isn't defined in row-details.

Is possible we can do that?

Thanks

**Comment by jinniw43805** [comment]
Sorry I forget to put the question label on this question

**Comment by Hiws** [comment]
There's no such prob because the `row-details` slot isn't for a specific field. So there's no `value` or `unformatted` value to fetch.
Instead access the field/property you need directly from the `item`, which you can find in the slot scope.

**Comment by jinniw43805** [comment]
Thank you
