### ISSUE TITLE
Tooltips no template

### ISSUE THREAD

**Issue by stroggfaer** [bootstrap-vue/bootstrap-vue#5919]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://getbootstrap.com/docs/4.0/components/tooltips/

### Additional context or description

Problem parameter not working: template

![image](https://user-images.githubusercontent.com/13553206/96362759-cb917080-1159-11eb-88c2-51d38868b136.png)

**Comment by jackmu95** [comment]
@stroggfaer You are referring to the Bootstrap documentation and not the BootstrapVue docs.
