### ISSUE TITLE
Router links in history mode completely broken since v2.18.0

### ISSUE THREAD

**Issue by essenmitsosse** [bootstrap-vue/bootstrap-vue#5927]
### Describe the bug

Since upgrading to v2.18.0 router links in history mode seem to be completely broken, since they don't generate the correct HTML anymore — the href-attribute is just "#" no matter what the router link target is. Clicking the links still works though.

### Steps to reproduce the bug

- activate history mode for router

```vue
<p><router-link :to="{ name: 'Home' }">Router Link</router-link></p>
<p><b-link :to="{ name: 'Home' }">Bootstrap Link</b-link></p>
```

The produced HTML:
```html
<p><a href="/" aria-current="page" class="router-link-exact-active router-link-active">Router Link</a></p>
<p><a href="#" aria-current="page" class="router-link-exact-active router-link-active" target="_self">Bootstrap Link</a></p>
```

### Expected behavior

The router link should also produce `href="/"` (and did so in version prior to v2.18.0*

### Versions

**Libraries:**

- BootstrapVue: 2.18.0
- Bootstrap: 4.5.3
- Vue: 2.6.11
- Vue Router: 3.4.7 (also tested with 3.3.0, same result)

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Chrome
- Version: 86

### Demo link

[Reproduction link](https://github.com/essenmitsosse/bootstrap-vue-router-bug) — Fresh Vue CLI installation

**Comment by Locksam** [comment]
Same. 
After 2.18.0 all `<b-link :to={name:  RouteName}>` generate `<a href="#">`
`<router-link>` works fine.

**Comment by U3R1YXJ0** [comment]
Confirmed with my application too. The bug effects all components that utilize router-link, including b-dropdown-item where 'to' field is specified.

**Comment by bruceCzK** [comment]
Yes, also the `<base>` tag is been ignored.
For example, if you have `<base href="/dashboard/">` in head, `<router-link to="/">` produces `<a href="/">` instead of `<a href="/dashboard/">`

**Comment by jaylittle** [comment]
Holy Hell - I just banged my head on this for the last hour wondering what I broke and got the bright idea that it might be this library and lo and behold here you are.  Thank you all so much for verifying to me that I haven't completely lost my marbles yet!

**Comment by Hiws** [comment]
`v2.18.1` which was released yesterday should've resolved the issue, can any of you confirm if that is the case?

**Comment by johnkarpn** [comment]
Yes, the fixes solved the problem, thank you!
