### ISSUE TITLE
Contrary to the docs, registering b-avatar icon to local component does not allow it to appear in the avatar

### ISSUE THREAD

**Issue by bbugh** [bootstrap-vue/bootstrap-vue#5937]
### Describe the bug

The [documentation](https://bootstrap-vue.org/docs/components/avatar/#icon-content) (under Icon Content -> Notes) states: 

> When providing a BootstrapVue icon name, you must ensure that you have registered the corresponding icon component (**either locally to your component/page**, or globally), if not using the full BootstrapVueIcons plugin.

The bold part does not seem to be the case. When registering an icon with `components: { BIconBuilding }` in the component where `b-avatar icon="building"` is used, no icon appears.

It does works when using `Vue.component('BIconBuilding', BIconBuilding)`

Based on what I understand about Vue component registration, I think that it may be that the docs here are incorrect.

### Steps to reproduce the bug

1. Create a component that contains a b-avatar
2. Set an icon to b-avatar that is not registered
3. Import the icon and add it to the `components` section.
4. Observe that the icon does not appear

### Expected behavior

Either the icon shows up as described in the docs when locally registered, or the docs change to specify that they must be globally registered with `Vue.component`.

### Versions

**Libraries:**

- BootstrapVue: 2.16.0
- Bootstrap: 4.5.2
- Vue: 2.6.12

**Environment:**

- Browser: any

### Demo

<details><summary>Code Example</summary>

```vue
<template>
  <!-- does not show an icon -->
  <b-avatar
    :src="photo"
    icon="building" />
</template>

<script>
import { BIconBuilding } from 'bootstrap-vue'

export default {
  components: {
    BIconBuilding
  }
}
</script>
```
</details>

### Additional context

Documentation link: https://bootstrap-vue.org/docs/components/avatar/#icon-content (under Notes)

**Comment by jackmu95** [comment]
@bbugh @Hiws I've looked further into this and the problem is how `<b-icon>` looks up local components.
It assumes they are registered on the `$parent`.

Since `<b-avatar>` uses `<b-icon>`, `<b-icon>`'s parent is `<b-avatar>` and not the component where you use `<b-avatar>` where the icon component is registered.
https://codesandbox.io/s/interesting-khorana-jjck2?file=/App.vue

I will look into wether we can look up registered icon components further up the tree.

**Comment by bbugh** [comment]
I upgrade to the new version, it works great. Thanks for such a fast fix!
