### ISSUE TITLE
Request: feedback size for fieldset

### ISSUE THREAD

**Issue by PierBover** [bootstrap-vue/bootstrap-vue#594]
There is a label size, but not a feedback size.

It would be more consistent with the API and be helpful for making error messages smaller.

I could do a PR for this if it would be accepted.

**Comment by tmorehouse** [comment]
label-size applies only when the fieldset is set to horizontal (inline with the control).

Are you referring to the text size, or the width of the feedback area?

**Comment by PierBover** [comment]
Oh ok I assumed it worked on either case and it was the text size.

I was referring to the text size which now I'm guessing it would be better to simply style with CSS.

**Comment by PierBover** [comment]
OTOH maybe it would be a good idea to be able to pass a CSS class to both the label and feedback for easier styling.

**Comment by tmorehouse** [comment]
Feedback supports HTML markup:

```html
<b-form-fieldset description="Enter your name."
                 state="danger"
                 feedback="<small>This is my feedback!</small>"
>
    <b-form-input v-model="name"></b-form-input>
</b-form-fieldset>
````

**Comment by PierBover** [comment]
Noice!

**Comment by tmorehouse** [comment]
I'm going to create a PR for adding named slots for `b-form-fieldset`, to allow easier usage.

**Comment by tmorehouse** [comment]
Maybe to prevent confusion `label-size` should be called `label-width` or `label-cols`. We could deprecate the use of `label-size`
