### ISSUE TITLE
Simple show or hide column.

### ISSUE THREAD

**Issue by enix-app** [bootstrap-vue/bootstrap-vue#5942]
There are no simple ways to show/hide a specific column.

I think the solution possible to add field property like this:

```js
let fields = [
  {
    key: 'last_name',
    sortable: true,
  },
  {
    key: 'first_name',
    sortable: false,
    // I found this solution, but.... 
    thClass: 'd-none',
    tdClass: 'd-none'
  },
  {
    key: 'age',
    label: 'Person age',
    // that's what I mean.
    hidden: true,
  }
]
```

I just change the ``hidden`` props value, then Bootstrap-Vue table do with that.

Other way I've found, just remove specific item. But, more tricky to save the item props if we want to show it again.

Or set in as table property as my imagine:

```vue
<b-table
  :hide-columns.sync="['age']"
/>
```

Finally, I can play it with BootstrapVue-checkbox ``<b-checkbox-group>``.

Thank you.

**Comment by Hiws** [comment]
You can also use a computed property in combination with a boolean on your fields.
<https://github.com/bootstrap-vue/bootstrap-vue/issues/5315#issuecomment-625075845>

**Comment by enix-app** [comment]
Looks easy, thank you.
