### ISSUE TITLE
Keep alive for toast

### ISSUE THREAD

**Issue by adholland** [bootstrap-vue/bootstrap-vue#5949]
### Describe the issue

I would like to know how I could keep a toast alive. The toast I have created has an auto-hide-delay set, as I'd like the user to not have a close it by default. However it is hard to gauge how long to set the toast for as its to show progress, so there have been times when the toast has disappeared before the progress has completed.

What I'd like is that once the progress is at 100% then the delay is initiated. I know this is something that isn't currently available, just wondering if there was some simple code that would provide this feature. Thanks for any help/guidance.

**Comment by Hiws** [comment]
I think your best bet would be to set `no-auto-hide` on the toast and then handle hiding the toast yourself once the progress is finished.´

```js
async doTask() {
  showToast();

  await someTask();

  setTimeout(() => {
    hideToast()
  }, someDelay)
}
```

**Comment by adholland** [comment]
@Hiws Thanks for the help. I should have thought of that - but much appreciated.
