### ISSUE TITLE
modal event.cancel() in catch doesn't work

### ISSUE THREAD

**Issue by PierBover** [bootstrap-vue/bootstrap-vue#595]
So I have a try/catch and when I do `event.cancel()` on the catch, it is ignored.

```
async submit (event) {
	try {
		await this.$validator.validateAll();
	} catch (error) {
		console.log(error);
		console.log(event);
		return event.cancel();
	}
}
```

**Comment by alexsasharegan** [comment]
I'm not sure if the control flow allows for an async cancel. I think what you'll need to do is cancel up top in your submit handler, then manually close the modal on either success/failure or both.

**Comment by tmorehouse** [comment]
Which event are you binding to?

Modal's `event.cancel()` will only work with `@ok=`, `@cancel=` and `@hide=`. bindings.

**Comment by PierBover** [comment]
I'm using `@ok`.

Thanks for the idea @alexsasharegan 👍

**Comment by alexsasharegan** [comment]
Cheers! 🍻 Let us know how it works! Might be something worth documenting.

**Comment by PierBover** [comment]
It works as expected :)

🍻

**Comment by alexsasharegan** [comment]
Awesome! I'm going to close this and open a docs issue to explain using cancel in async flow. I think it's in the lib's best interest to leave that logic to the integrator rather than forward the extra code size to everyone.
