### ISSUE TITLE
TimePicker more than 23 hours

### ISSUE THREAD

**Issue by Samtronic** [bootstrap-vue/bootstrap-vue#5950]
Is it possible to set the hours more than 23. I use the timepicker to know the number of working hours.

Thanks
Steven

**Comment by Hiws** [comment]
This is not possible, and not quite what the timepicker component is meant for.

Perhaps `<b-form-spinbutton>` is more of what you need.
<https://bootstrap-vue.org/docs/components/form-spinbutton#min-max-and-step>

**Comment by Samtronic** [comment]
Thank you for the link I will use this component.
