### ISSUE TITLE
Automatic tree shaking support

### ISSUE THREAD

**Issue by wenfangdu** [bootstrap-vue/bootstrap-vue#5954]
Currently, bootstrap-vue supports manual tree shaking, automatic tree shaking support like [this one](https://vuetifyjs.com/en/features/treeshaking) would be nice.

**Comment by Hiws** [comment]
This is currently not something we support, but someone has made a 3rd party loader which aims to do this.
<https://www.npmjs.com/package/bootstrap-vue-loader>
