### ISSUE TITLE
Is there any way to show message on hover of disabled dates in form date picker?

### ISSUE THREAD

**Issue by DebaPrasad14** [bootstrap-vue/bootstrap-vue#5955]
I am using bootstrap-vue quite sometime but couldn't find a way to add some message on the disabled dates on hover over them in form date picker. Even there is no documentation if we can do. 
Can anyone suggest any way we can do that?
I want something like below image.
![image](https://user-images.githubusercontent.com/30753467/96956110-e9255800-1514-11eb-8f71-67bbc5f667a0.png)

@vizo  @mathlet0x @jackmu95 @tmorehouse @pi0 @alexsasharegan @mosinve

**Comment by DebaPrasad14** [comment]
@vizo @mathlet0x @jackmu95 @tmorehouse @pi0 @alexsasharegan @mosinve is there any update ?

**Comment by jackmu95** [comment]
@DabeDotCom First of all, please stop pinging multiple users here directly.
We see the issues and handle them when we have time.

What you want to do is currently not possible.
It would require a slot for the day.

**Comment by DebaPrasad14** [comment]
Hey, @jackmu95 I tagged as no one responded last 3 days. And I asked if it is achievable in the current version or not, it's so simple, I didn't ask to do it now.
Anyway thanks.
