### ISSUE TITLE
Enhancement: More settings for BModal

### ISSUE THREAD

**Issue by vincentdh** [bootstrap-vue/bootstrap-vue#5958]
### Is your feature request related to a problem? Please describe...

Lots of BModal props are not globally configurable with the settings.  This result in lots of repeating code if, in example, you don't want the modal to be closed on backdrop click in your application.

### Describe the solution you'd like

Add the following properties to the BModal Settings:
* centered
* scrollable
* button-size
* no-stacking
* no-fade
* no-close-on-backdrop
* no-close-on-esc
* title-class
* header-class
* modal-class
* dialog-class
* content-class
* body-class
* footer-class
* hide-header
* hide-footer
* hide-header-close
* hide-backdrop
* ok-only
* ok-disabled
* cancel-disabled

### Describe alternatives you've considered

Create a custom modal that just call the BModal with the prefered default settings.

**Comment by jackmu95** [comment]
@vincentdh The problem with adding all those additional props to the global config is that it boats the bundle quite a bit since the default config can't be minified.

We have to rethink the global settings implementation in BootstrapVue v3 anyway, so I would put this on hold for that.
