### ISSUE TITLE
Vertical alignment in b-card for button

### ISSUE THREAD

**Issue by pouyakondori** [bootstrap-vue/bootstrap-vue#5960]
Hello, for vertical aligning in cards like the [image](https://i.stack.imgur.com/IGN7K.png), these lines should work: 
Add `d-flex` to `.card-body`
Add `flex-column` to `.card-body`
Add `mt-auto` to `.btn nested` in `.card-body`

but these classes, don't work in bootstrap-vue. Is there any way to make the button vertically aligned in the footer of each card?

**Comment by Hiws** [comment]
I'm not sure what you mean with it not working.
As the classes and placement works as you say it should.
<https://codepen.io/Hiws/pen/JjKEZKg>

You will need to post your code if it still doesn't work.

**Comment by pouyakondori** [comment]
Thank you. It was needed to add : `body-class="d-flex flex-column"` in `b-card` .
Solved.
