### ISSUE TITLE
b-avatar doesn't always maintain fixed width with long cell content

### ISSUE THREAD

**Issue by bbugh** [bootstrap-vue/bootstrap-vue#5962]
### Describe the bug

In a table cell (possibly other things), the avatar can be squished if the flex content is too long.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/438465/97057415-c3b63f80-1550-11eb-81d7-b260769647df.png">

### Steps to reproduce the bug

Not sure of all the reproduction steps, but a BAvatar + text inside of a flex element can squash the avatar. (see [demo](https://codesandbox.io/s/bootstrapvue-starter-project-forked-om4y6?file=/App.vue:108-344))

### Expected behavior

The avatar should maintain the size regardless of the other content. 

### Versions

**Libraries:**

- BootstrapVue: 2.18.1
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Firefox, Chromium
- Version: 81.0.2, 86.0.4240.99

### Demo link

https://codesandbox.io/s/bootstrapvue-starter-project-forked-om4y6?file=/App.vue:108-344

**Comment by bbugh** [comment]
@talkor thanks for the fix in `flex`. This isn't working in `grid` display contexts when the avatar would overflow a `display: grid`. Example:

<img width="107" alt="image" src="https://user-images.githubusercontent.com/438465/98391606-78099880-201c-11eb-8607-63bc33ad482e.png">

@jackmu95 can you reopen this or should I make a new issue?

It seems like using `min-width/height` and `max-width/height` would ensure that the avatar stays the same size even in an overflow situation.

**Comment by jackmu95** [comment]
@bbugh Adding a `min-width: 0` to the `<b-avatar>` should fix the issue.
Would you mind creating a new issue with a new example?
