### ISSUE TITLE
[form-fieldset] Add label, description, and feedback slots

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#597]
Currently feedback, label, and description need to be passed as props.  Having named slots would be handy

**Comment by LarBearrr** [comment]
@tmorehouse Would it be possible to move the location of the description for the parent form group? 
![image](https://user-images.githubusercontent.com/28734844/51640608-8ced6880-1f29-11e9-9910-e56360ebfceb.png)
```
<b-card bg-variant="light" class="mb-3">
                <b-form-group horizontal breakpoint="lg" label="Personal Information" label-size="lg" label-class="font-weight-bold pt-0" class="mb-0">
                    <template slot="description">General user information...</template>
                    <b-form-group label="First name" label-class="text-sm-right" label-for="first_name">
                        <b-form-input id="first_name"></b-form-input>
                    </b-form-group>
                    <b-form-group label="Last name" label-class="text-sm-right" label-for="last_name">
                        <b-form-input id="last_name"></b-form-input>
                    </b-form-group>
                </b-form-group>
            </b-card>
```

**Comment by tmorehouse** [comment]
So move it to under the label? Hmmm.. that could be an option that could be added for positioning. When the form switches to stacked it would still appear under the label though. Would that be ok?

**Comment by LarBearrr** [comment]
I think it makes more sense to move the description under the label, at least for the parent form group. I couldn't figure out how to do that on my own after looking at the source. Given that the parent is still a `<b-form-group>` I wasn't sure if it would affect the child elements as well. Perhaps it would be more beneficial to create a new component, say `b-form-section` that would act as a grouping element for child form groups/elements. 

As to your question about the placement when stacked, having it under the label would be fine.
