### ISSUE TITLE
BSV v3 Suggestions

### ISSUE THREAD

**Issue by jd-0001** [bootstrap-vue/bootstrap-vue#5970]
### Is your feature request related to a problem? Please describe...

As the library is rewriting I like to give some suggestions which can help in the development process:

* Ability to get setting developer set in BootstrapVue settings [i.e. What is default variant for button]
* Ability to use custom transition/animations [i.e. As I already opened an issue: #5415 ]
* Update variant color at runtime (This can be achieved using CSS vars but if BS5 don't support this I guess BSV can't support it as well, right?)
* Directive or something to show/hide items based on the breakpoint. [Quasar example: `$q.screen.lt.md`]
* More flexibility in using custom icons in components

### Describe the solution you'd like

Right now I am making PR for features I like to add to BSV but as new v3 will be in TypeScript I won't be able to provide PR till I learn TS so I created this issue.

### Describe alternatives you've considered

Overriding and creating custom things but those are not practical and efficient.

### Additional context

I suggest the team keep this issue open as other people can add their suggestions if they like till we get the official release of v3.

**Comment by jackmu95** [comment]
@jd-0001 BootstrapVue v3 will not be a complete rewrite, this will happen with v4 next year.
With v3 we concentrate to bring Vue 3 support to BootstrapVue with as little breaking changes as possible.

**Comment by jd-0001** [comment]
Thanks for clarification @jackmu95. Shall I keep this open then?

**Comment by jackmu95** [comment]
@jd-0001 I would prefer if we close this now and start over when v3 is released.
