### ISSUE TITLE
B-table click-outside event handler 

### ISSUE THREAD

**Issue by kswizzlek** [bootstrap-vue/bootstrap-vue#5973]
I have been looking for a good way to handle events when you click outside a selected row. Currently when I select a row in b-table I create inputs to modify the content of the row. What I want to do is when I click outside the row I can save and validate the information inside the row.

**Comment by jackmu95** [comment]
Isn't it possible to do that on the `blur` vent of the input?

**Comment by kswizzlek** [comment]
I have multiple inputs in the row. I could save each one individually on the blur event. I ended up adding a vue v-off-click directive for the btable - https://stackoverflow.com/questions/36170425/detect-click-outside-element and then adding logic in the row click for when a row is already selected save before changing the selected row.
