### ISSUE TITLE
Navbar : Unclickable specific b-nav-item(s).

### ISSUE THREAD

**Issue by simonalarie** [bootstrap-vue/bootstrap-vue#5982]
### Describe the bug

When I use a basic **navbar menu** comporting let's say, four items, including a dropdown :

```
<b-collapse id="nav-collapse" is-nav>
      <b-navbar-nav>
        <b-nav-item href="https://bootstrap-vue.org/">Link-1</b-nav-item>
        <b-nav-item href="https://bootstrap-vue.org/">Link-2</b-nav-item>
        <b-nav-item-dropdown text="Dropdown" right>
            <b-dropdown-item href="https://bootstrap-vue.org/">Sublink-1</b-dropdown-item>
            <b-dropdown-item href="https://bootstrap-vue.org/">Sublink-2</b-dropdown-item>
            <b-dropdown-item href="https://bootstrap-vue.org/">Sublink-3</b-dropdown-item>
        </b-nav-item-dropdown>
        <b-nav-item href="https://bootstrap-vue.org/">Link-3</b-nav-item>
        
      </b-navbar-nav>
    </b-collapse>
```
Any subsequent link (nav-item) to an **opened dropdown** is getting non-fonctional.

### Steps to reproduce the bug
1. Open the dropdown menu item
2. Move to the next link (nav-item) located outside of opened dropdown (here Link-3).
3. Click item.
4. Watch the dropdown close (like a normal click outside behavior) but, link is getting nowhere.

### Expected behavior

Expected to work like other nav-items located **before** an opened dropdown (Link-1, Link-2).

### Versions

**Libraries:**

- BootstrapVue: 2.18+
- Bootstrap: 4
- Vue: 2

**Environment:**

All mobile devices + Chrome Dev mobile emulation. Menu works fine on desktop while not in collapsed mode (burger menu).

### Visual info:

![image](https://user-images.githubusercontent.com/38366582/97628500-2ac96d80-1a03-11eb-9791-46a496084366.png)

**Comment by jackmu95** [comment]
@simonalarie Could you please create a minimal live demo of the issue?

**Comment by simonalarie** [comment]
@jackmu95 

Thanks for your ideas. 

https://jsfiddle.net/SiMMA/jt61r4gw/
