### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export - form-input.value

### ISSUE THREAD

**Issue by DutchNeon** [bootstrap-vue/bootstrap-vue#60]
Related to `Vue 2.1.x`

When trying to import the form-input.vue

`import FormInput from 'bootstrap-vue/components/form-input.vue`

 the page fails to load and causes an error

```
helpers.js?fc5f:4 
Uncaught SyntaxError: Unexpected token export
    at Object.<anonymous> (app.js:912)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:864), <anonymous>:7:16)
    at Object.<anonymous> (app.js:864)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:1032), <anonymous>:5:19)
    at Object.<anonymous> (app.js:1032)
    at __webpack_require__ (app.js:556)
```

This seems to be case with more components. Components like Alert and Button work fine though.

`import Button from 'bootstrap-vue/components/button.vue` etc

**Comment by acoard** [comment]
What was the fix for this problem / why was this closed?  I'm running into it myself.

I'm using the [vue-cli webpack](https://github.com/vuejs-templates/webpack) template.

My .bashrc is where it should be - the project root and it has the es2015 transform.

The problem only  happens when importing components that are importing other components.

Thanks!

**Comment by DutchNeon** [comment]
I found out it was kind of the same problem as #56, so I closed it myself.
 Haven't bothered trying the adviced solution by importing the entire version of Bootstrap-Vue. Will try tomorrow to see what happens.

**Comment by acoard** [comment]
Appreciate the response (so speedy!)

Unfortunately that proposed solution does not work for me.  The first line, the import, throws a similar error.  I've attached a screenshot.  The only difference is it errors out on a different line, but fundamentally it's the same type of error (getting the browser to run eval on ES6 code).

![image](https://cloud.githubusercontent.com/assets/4187478/22044008/4f465650-dcc7-11e6-9100-e412e0f4a70e.png)

**Comment by pi0** [comment]
@acoard There is also a compiled version that you can use  just:
```js
import BootstrapVue from 'bootstrap-vue/build/bootstrap-vue.common`
```
