### ISSUE TITLE
select the Checkbox/Radio when click on the gap between the Label and the Checkbox/Radio

### ISSUE THREAD

**Issue by magical-l** [bootstrap-vue/bootstrap-vue#6007]
When the b-form-checkbox(or the b-form-radio) rendered, there is a gap between the `<input type=checkbox>` and the `<label>`for it.
If we click on the gap, nothing will happen.
Can we make that 'gap' as a part of the `<label>`, so that we can have a wider space to select the `<input>`?

**Comment by jackmu95** [comment]
This issue/question is related to Bootstrap directly since BootstrapVue uses their styles directly.

**Comment by Hiws** [comment]
Doesn't look like this is something they're going to change. 
<https://github.com/twbs/bootstrap/issues/30535>
