### ISSUE TITLE
modal-backdrop slot content z-index problem

### ISSUE THREAD

**Issue by mehmetpolat** [bootstrap-vue/bootstrap-vue#6023]
Hi

I'm using the modal-backdrop slot for the modal, but I have a z-index problem with the items I add to the content 

how can i handle it?

`<b-modal
      centered
      hide-header
      hide-footer
      no-close-on-backdrop
      id="modal-1"
      title="BootstrapVue"
    >
      <div class="test text-danger">Ahmet</div>
      <p class="my-4">Hello from modal!</p>
      <div slot="modal-title">asdsd</div>
      <template #modal-backdrop>
        <h1 class="text-danger">content</h1>
      </template>
    </b-modal>`

https://www.loom.com/share/bdc78bc2e7e843ebb48014804c07cc35

**Comment by Hiws** [comment]
I don't quite understand the issue you're having.
Could you describe what the issue is, and what you're trying to do?
