### ISSUE TITLE
bootstrap-vue@2.18.1

### ISSUE THREAD

**Issue by yasirhantoush** [bootstrap-vue/bootstrap-vue#6024]
### Describe the bug

using b-input-group from examples does not work on the specified version,
it showsinvalid undefined

<div>
  
  <b-input-group size="lg" prepend="$" append=".00">
    <b-form-input></b-form-input>
  </b-input-group>

  
  <b-input-group class="mt-3">
    <template #append>
      <b-input-group-text><strong class="text-danger">!</strong></b-input-group-text>
    </template>
    <b-form-input></b-form-input>
  </b-input-group>

  
  <b-input-group prepend="Username" class="mt-3">
    <b-form-input></b-form-input>
    <b-input-group-append>
      <b-button variant="outline-success">Button</b-button>
      <b-button variant="info">Button</b-button>
    </b-input-group-append>
  </b-input-group>
</div>

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.org/docs/components/input-group
2. Try any sample

### Versions

**Libraries:**

- BootstrapVue: 2.18.1
- Bootstrap: 4.5.3
- Vue: 2.6.10

**Environment:**

- Device: Windows
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: Obera
- Version: 72.0.3815.186

**Comment by jackmu95** [comment]
@yasirhantoush I can't confirm what you describe on Opera v72 on macOS Mojave.
Can you please share a screenshot with the error and create a demo on CodeSandbox or CodePen?

<img width="1502" alt="Bildschirmfoto 2020-11-08 um 10 01 35" src="https://user-images.githubusercontent.com/2737132/98461094-bed8c900-21a9-11eb-91bd-3c8d6c0ab5e2.png">
