### ISSUE TITLE
Please provide an example of appending a  `.dropdown-menu` to `body` (to allow overflowing a scrollable parent).

### ISSUE THREAD

**Issue by andrei-gheorghiu** [bootstrap-vue/bootstrap-vue#6030]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs/components/dropdown#advanced-popperjs-configuration

### Additional context or description

I've been trying to append the `.dropdown-menu` to `body` element to allow it to overflow a parent with `overflow:hidden` without any success. I tried to use both `boundary` and `:popper-opts`. 

In `boundary` I tried to pass 
 - `'window'`,
 - `'viewport'` 
 - a `body` reference: `computed: { body: () => document.body }`. 
 - also tried `computed: { appRef: () => document.querySelector('#app') }`. 

I also tried to peak into source code to see what `popper-opts` expects (as Popper.js documentation is too cryptic for me), but wasn't able to pinpoint it into the bootstrap-vue package.

Is there an example anywhere of how this could be achieved?

**Comment by jackmu95** [comment]
@andrei-gheorghiu Please take a look at the [boundary constraints](https://bootstrap-vue.org/docs/components/dropdown#boundary-constraint) section of the `<b-dropdown>` docs.

**Comment by andrei-gheorghiu** [comment]
I have read the documentation prior to opening the issue. 

Using the current documentation I wasn't able to make it work (and I do read carefully). Probably the weakest point of your documentation is sending to Popper.js docs, which are cryptic. And by that I mean: from your documentation and the entire website found at the link, it is by no means obvious what `popper-opts` expects. 

If you want me to, I can close this issue, as I used a workaround: Replaced `<b-dd>` with `<v-popover>` and styled the popover to look like a dropdown menu. Which is hardly a fix of the reported issue, but it's a viable solution for my initial problem. And might be for others as well.

**Comment by cdauth** [comment]
I have just come across the same problem and understood that all ancestor elements of the dropdown until the scrollable parent need to have `position: static` in order to work. In my case I had a dropdown inside a `b-input-group`, which as `position: relative` set by default, and had to override those styles using CSS (adding the `position-static` class would also have worked).

The documentation already mentions the fact that the dropdown itself will adjust its `position`, but it would indeed be nice if it also mentioned that one has to manually adjust the `position` of its ancestors.

**Comment by cdauth** [comment]
Another solution that I found that seems to work much better is to set `:popper-opts="{ positionFixed: true }"` on the dropdown element.

**Comment by cdauth** [comment]
I think it would be nice for this to be fixed, either by introducing a positioning mechanism that works universally or by at least documenting a workaround. Dropdown positioning is quite painful at the moment.

**Comment by mvanderlee** [comment]
Well, having just come across this I think the solution would be to ensure that the actual dropdown is added to the body element instead. i.e.: how Angular Material's select component works. 

There just isn't a good way to get this working as it's currently implemented.

**Comment by yourboyblue** [comment]
In case this helps anyone else, the best combination of options I've found is:

```
<b-dropdown boundary="window" :popper-opts="{ positionFixed: true, modifiers: { offset: '100%' } }">
  ...
</b-dropdown>
```

For my use case of a dropdown as a child of a `<b-table responsive />` component, I get the same behavior as a dropdown contained in a non-responsive table. Your required offset option value will depend on your desired menu positioning: https://popper.js.org/docs/v1/#modifiersoffset
