### ISSUE TITLE
b-calendar display only months

### ISSUE THREAD

**Issue by chumager** [bootstrap-vue/bootstrap-vue#6034]
### Is your feature request related to a problem? Please describe...
Feature

Almost all my front end uses bootstrap-vue components, for now I use another datepicker for this reasons.
Be able to pick only months.
Can choose date and time in one component.

I want to change to bootstrap-vue datepicker to decrease maintenance and have a more coherent UI, but for that I need to be able to pick only months in the component
### Describe the solution you'd like
to have a prop that let the component change it's UI to only show months instead full calendar.

I can manage to show/hide the b-timepicker component when needed, but I need to be able to only show months when the user must select only a month from a year. 
### Describe alternatives you've considered
Now I use https://www.npmjs.com/package/vue2-datepicker, but can't use visual validation and even passing bootstrap classes it looks differente from rest of inputs.

### Additional context
for now it seems the only solution is to use date-disabled-fn to disable all the days but first or last, even though it's not an elegant solution.

![image](https://user-images.githubusercontent.com/775491/98686716-a6061a00-2347-11eb-9a9f-bf7f3f0ac69d.png)
![image](https://user-images.githubusercontent.com/775491/98686757-b28a7280-2347-11eb-9bfa-3178b43cfa18.png)

**Comment by Riiiad** [comment]
Is it OK if I work on this Feature Request. I need this function in the near future and will implement it on a project.

**Comment by SergejsZerins** [comment]
Probably our calendar should support this feature "minViewMode: 1" from datepicker - https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#minviewmode
