### ISSUE TITLE
Add class selector to b-avatar img tag for custom images in default slot instead of using element selector

### ISSUE THREAD

**Issue by bbugh** [bootstrap-vue/bootstrap-vue#6035]
### Is your feature request related to a problem? Please describe...

We need to override b-avatar's `img` tag to add a `loading="lazy"`. Unfortunately, the `img` css in bootstrap-vue uses an element selector as `.b-avatar-img img` rather than a unique class for the image tag, so we have to duplicate the css code.

### Describe the solution you'd like

It would be preferable for it to be a class selector rather than an element selector. Then we could override the image exactly how it works in bootstrap-vue.

```html
  <b-avatar ...>
    <template v-if="src" #default>
      <img :src="src" class="copied-from-b-avatar-img"> <!-- current -->
      <img :src="src" class="b-avatar-img-element"> <!-- preferred  -->
    </template>
```

### Describe alternatives you've considered

We currently have to copy the code from `.b-avatar-img img` to our system, which isn't ideal or future proof.

**Comment by bbugh** [comment]
I'm happy to PR this if acceptable. For backwards compatibility, I imagine a change like this:

```diff
diff --git a/src/components/avatar/_avatar.scss b/src/components/avatar/_avatar.scss
index 47e4befd..aacdc99f 100644
--- a/src/components/avatar/_avatar.scss
+++ b/src/components/avatar/_avatar.scss
@@ -79,7 +79,8 @@
     max-width: 100%;
   }

-  .b-avatar-img img {
+  .b-avatar-img img,
+  .b-avatar-img-element {
     width: 100%;
     height: 100%;
     max-height: auto;
```

I don't love the name `b-avatar-img-element` but unfortunately `b-avatar-img` is used for the wrapping element instead of the `img`.

Could also do something like:

```diff
-  .b-avatar-img img {
+  .b-avatar-img img,
+  .b-avatar-custom .b-avatar-custom-img {
```

**Comment by Hiws** [comment]
You could just wrap the `<img>` in a `<span>` with the class `b-avatar-img`.
Should give the same result, except that there'll be an additional span in the DOM.

```html
<b-avatar>
  <template v-if="src" #default>
    <span class="b-avatar-img">
      <img loading="lazy" :src="src">
    </span>
  </template>
</b-avatar>
```

**Comment by bbugh** [comment]
Yes, but in the case of `.b-avatar-custom .b-avatar-img img` it's duplicating the outer wrapping code which we can't guarantee won't break in the future and isn't much different than the current workaround we're doing.

One alternative to the proposed change is to allow for specifying the wrapper code, instead of defaulting to `b-avatar-custom`, we could specify `content-class` (or something) which would default to `b-avatar-custom` if one is not specified.

**Comment by ameft** [comment]
@bbugh were you able to override b-avatar's img tag adding loading="lazy" without losing the text fallback behavior? Using your hints and those of @Hiws I was able to "inject" the lazy loading behavior in the images but I lost the text fallback in the process.
Sorry if the question is slightly off-topic.

**Comment by bbugh** [comment]
@ameft I am not sure. I don't use bootstrap-vue anymore, so I am not sure what the state of it is.
