### ISSUE TITLE
all of thead-class,table-class,thead-tr-class can't work for custom css class for header

### ISSUE THREAD

**Issue by ryosukemitake** [bootstrap-vue/bootstrap-vue#6038]
### Describe the bug

as the demo image shows below, I can change the font size for body, but not header even if I use thead-class,table-class,thead-tr-class in b-table as the doc writes.

### Steps to reproduce the bug

package.json
```
  "dependencies": {
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/pwa": "^3.0.0-0",
    "bootstrap-vue": "^2.15.0",
    "chart.js": "^2.9.4",
    "chartjs-plugin-zoom": "^0.7.7",
    "node-sass": "^4.11.0",
    "nuxt": "^2.0.0",
    "sass-loader": "^7.1.0",
    "vue-chartjs": "^3.5.1",
    "vue-template-compiler": "^2.6.11",
    "vue2-transitions": "^0.3.0"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^2.0.0",
    "@nuxtjs/eslint-module": "^1.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^6.1.0",
    "eslint-plugin-nuxt": ">=0.4.2",
    "vue-cli-plugin-i18n": "^0.5.1"
  }
```

```
<b-table
  show-empty
  striped
  hover
  fixed
  table-class = "table-font-size"
  thead-class = "thead-font-size"
  thead-tr-classclass = "thead-font-size"
  :items="rankingList"
  :fields="fields"
  :sort-by.sync="sortBy"
  :sort-desc.sync="sortDesc"
  :sort-direction="sortDirection"
>
```

```
<style>
.table-font-size{
  font-size: 10px;
}
.thead-font-size{
  font-size: 10px;
}
</style>
```

### Expected behavior

expected to adapt css class to header

### Versions

**Libraries:**

- BootstrapVue: 2.1.5
- nuxt: 2.0.0

**Environment:**

- Device: Mac
- OS: Mac Catalina
- Browser: Chrome
- Version: 79

### Demo link
<img width="280" alt="スクリーンショット 2020-11-10 0 53 58" src="https://user-images.githubusercontent.com/55892311/98822753-8e787f80-2474-11eb-82ab-47d5db02c100.png">

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
I can't reproduce the problem, can you provide a simple reproduction the problem?

Working example:
<https://codesandbox.io/s/brave-hooks-65nor?file=/App.vue>

**Comment by ryosukemitake** [comment]
<img width="984" alt="スクリーンショット 2020-11-11 23 44 02" src="https://user-images.githubusercontent.com/55892311/98825414-ca611400-2477-11eb-8086-9e53f9c04bd6.png">

I copied the example into my code, and the the font size are different in header and body.
I use templet  which use bootstrap. it might be a reason.
I'm gonna check it. thanks

**Comment by ryosukemitake** [comment]
sorry I solved the issue by myself. as i mentioned above, the scss of the templete was the reason. I changed that and it did work! 
thansk
