### ISSUE TITLE
change icons with postfix 'fll' to 'fill'

### ISSUE THREAD

**Issue by magical-l** [bootstrap-vue/bootstrap-vue#6039]
there are some icons with a postfix 'fll' in their names, such as 'patch-check-fll', 'patch-exclamation-fll', 'patch-minus-fll', 'patch-plus-fll', 'patch-question-fll', while other icons using 'fill'.
why they are not in the same form?
could we change the 'fll' postfix to 'fill' for normalization?

**Comment by Hiws** [comment]
We're getting the icons (and names) from the Bootstrap Icons package, as you'll have to open an issue over there.

<https://github.com/twbs/icons>

**Comment by magical-l** [comment]
oh, I see there is already an issue: [https://github.com/twbs/icons/issues/379](https://github.com/twbs/icons/issues/379)

**Comment by Hiws** [comment]
> oh, I see there is already an issue: [twbs/icons#379](https://github.com/twbs/icons/issues/379)

Looks like these have been fixed in the `1.2.2` icons release, and will be included in BootstrapVue in the next release (no eta).
<https://github.com/twbs/icons/pull/586>
