### ISSUE TITLE
actions slot not displayed

### ISSUE THREAD

**Issue by nicolas15000** [bootstrap-vue/bootstrap-vue#6046]
### Documentation issue

This is my bootstrap vue table :

```
 <b-table :items="holidays " @row-clicked="updateItem">
    <template v-slot:cell(actions)="row">
        <b-button>
            <i class="fe fe-eye"></i>
        </b-button>
    </template>
</b-table>
```

No actions column is displayed, no button is displayed, template is not working .

This is my holidays data format :

`Array [ {"id":1,"blabla":"blabla"..etc ...}, {…} ]`

The table is correctly displayed, but no button nor actions column is visible. Do I have to create an "actions" sql column to make it work ?

This is my bootstrap vue version :` "bootstrap-vue": "^2.19.0"`

**Comment by Hiws** [comment]
I've answered your question on StackOverflow.
<https://stackoverflow.com/questions/64848505/b-table-v-slot-actions-not-displaying-anything/64854698#64854698>

But in short, if you want to have a column that doesn't exist in your data, you will need to use the `fields` prop, and define your columns.
