### ISSUE TITLE
Table scroll event

### ISSUE THREAD

**Issue by Ilyas23** [bootstrap-vue/bootstrap-vue#6047]
Dear developers, please add the scroll event to the table. I want to be able to load rows when scrolling. Without b-pagination

**Comment by Hiws** [comment]
If you're using the `sticky-header` prop. You can add `@scroll.native` to `<b-table>` to get a scroll event.

**Comment by Ilyas23** [comment]
> 
> 
> If you're using the `sticky-header` prop. You can add `@scroll.native` to `<b-table>` to get a scroll event.

Thank you very much! It didn't occur to me to put .native everything works! Then please write at this point
