### ISSUE TITLE
b-input changes v-model from null to empty string on blur

### ISSUE THREAD

**Issue by lucianobosco** [bootstrap-vue/bootstrap-vue#6078]
### Describe the bug

By hydrating a b-input v-model with a null value and blurring the input with no changes, the object property is changed from `null` to an empty string `""`. This happens only the first time when the input is hydrated. If you hydrate it again with no page refresh, it works as expected.

### Steps to reproduce the bug

1. Hydrate the `<b-input>` with a `null` value for the `v-model`
2. Focus the input
3. Blur the input with no changes at all
4. See how the property is changed from `null` to `""`

### Expected behavior

The object property must still as `null`

### Versions

**Libraries:**

- BootstrapVue: ~2.19.0
- Bootstrap: ~4.4.1
- Vue: ^2.6.12

**Environment:**

- Device: Desktop
- OS: Ubuntu 18
- Browser: Chrome
- Version: 86.0.4240.198 (Official Build) (64-bit)

### Additional context

This is causing an issue with some 3rd party validators like vee-validate, where a `pristine` flag is set to `false` because changes were detected on the object (from `null` to `""`).

**Comment by jackmu95** [comment]
@lucianobosco Can you create a minimal reproduction fo the issue on CodePen or CodeSanbox?

**Comment by lucianobosco** [comment]
@jackmu95 Hope it helps!
Please note that the issue happens the first time (on mounted) and when hydrating a null `description` after having a non `null` description already hydrated.

https://codepen.io/lucianobosco/pen/xxOvJWv

**Comment by jackmu95** [comment]
@lucianobosco Can you please confirm that this CodeSanbox with the changes of the linked PR applied solves the issue:
https://codesandbox.io/s/bootstrapvue-starter-project-forked-kf5vp?file=/App.vue

**Comment by lucianobosco** [comment]
@jackmu95 thanks! This is working as expected.
Will this fix be included in the next release?

**Comment by jackmu95** [comment]
@lucianobosco Yeah :)
