### ISSUE TITLE
Warning state in <b-form-input> does not change the form input

### ISSUE THREAD

**Issue by wsw70** [bootstrap-vue/bootstrap-vue#608]
Shouldn't the `warning` state  modify the visual part of an input form (an orange background for instance, or something like that)?

Tested on the following code (also a [CodePen](https://codepen.io/WoJWoJ/pen/WOMRZv)) : 
```
<div id="root">
  <b-form-input v-model="myform" :state="mystate"></b-form-input>
</div>
```

```
new Vue ({
  el: "#root",
  data: {
    myform: "",
    mystate: "warning"
  }
})
```

**Comment by tmorehouse** [comment]
Hmmm it should reflect the state setting.  Let me check the latest code.

**Comment by tmorehouse** [comment]
Are you using the latest (v0.17.1) or the master?

**Comment by wsw70** [comment]
I included the files according to the documentation:

```
<!-- Add this to <head> -->
<link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap@next/dist/css/bootstrap.min.css"/>
<link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.css"/>

<!-- Add this after vue.js -->
<script src="//unpkg.com/babel-polyfill@latest/dist/polyfill.min.js"></script>
<script src="//unpkg.com/tether@latest/dist/js/tether.min.js"></script>
<script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>

```

**Comment by tmorehouse** [comment]
Hmmm this appears to be a "bug" (or feature) in bootstrap CSS now.

It looks like the state is only applied when the parent container element has class `.has-warning`

http://v4-alpha.getbootstrap.com/components/forms/#validation

**Comment by tmorehouse** [comment]
from the Bootstrap docs:

> To use, add `.has-warning`, `.has-danger`, or `.has-success` to the parent element. Any `.col-form-label`, `.form-control`, or custom form element will receive the validation styles.

**Comment by tmorehouse** [comment]
If you wrap your input in a `b-form-fieldset` it should work.

**Comment by tmorehouse** [comment]
It appears that the class added to the input (i.e. `.form-control-warning`) will apply the state icon to the input, only if the parent element (i.e. `form-fieldset`) has the state class applied  (i.e. `.has-warning`).

It looks like we will have to update the docs to reflect this change

**Comment by wsw70** [comment]
Yes, it indeed works after wrapping the input with `<b-form-fieldset class="has-warning">`.

Thank you very much for your help.

**Comment by tmorehouse** [comment]
You can also do this:
```html
<b-form-fieldset state="warning">
```

**Comment by tmorehouse** [comment]
For release v0.18.0 (coming out very soon), we'll have clearer documentation on this, with examples.
