### ISSUE TITLE
b-link should support go attribute

### ISSUE THREAD

**Issue by drowhunter** [bootstrap-vue/bootstrap-vue#6085]
This is more of a feature request

router supports `$router.go(-n/n )`  to programattically navigate back and forward in the history
documented here
https://router.vuejs.org/guide/essentials/navigation.html#router-go-n

it seems like a miss that i can't do this 

```
<b-link go="-1">Go Back</b-link>
```

**Comment by jackmu95** [comment]
`go()` is a method of the router instance and not a prop of `<router-link>`.
