### ISSUE TITLE
b-form-timepicker with  card no correctly working?

### ISSUE THREAD

**Issue by djshox** [bootstrap-vue/bootstrap-vue#6090]

**Comment by djshox** [comment]
![Uploading 1.jpg…]()

**Comment by djshox** [comment]
![1](https://user-images.githubusercontent.com/38517932/100229429-09966700-2f46-11eb-9660-81aea8bc9909.jpg)

**Comment by jackmu95** [comment]
@djshox Can you please create a live demo with a minimal reproduction of the issue on CodeSandbox or Codepen.
