### ISSUE TITLE
b-form-tags required prop not working

### ISSUE THREAD

**Issue by damirbogd** [bootstrap-vue/bootstrap-vue#6094]
### Describe the bug

Forms gets submitted even though b-form-tags required and initial value is empty array
### Steps to reproduce the bug

1. Go to [CodeSandbox](https://codesandbox.io/s/s1fet)
2. Click on Submit button and see the **Please fill in this field** message
3. Fill in first input and click on Submit button again 
4. See error. Forms gets submitted even though b-form-tags required and not filled in

### Expected behavior

Trigger **Please fill in this field** message if b-form-tags prop required set to true and value is empty

### Versions

**Libraries:**

- BootstrapVue: 2.18.1
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Mac 
- OS: macOS Catalina
- Browser: Chrome
- Version: 87.0.4280.67 (Official Build) (x86_64)

### Demo link

[CodeSandbox](https://codesandbox.io/s/s1fet)

### Additional context

I have tried setting **form** and **input-type** prop and it didn't help. Also, I have tried specifying different initial values in b-form-tags v-model such as null, undefined, empty array, empty string.

**Comment by jackmu95** [comment]
@damirbogd The problem here ist that the native value of the `<input>` element ist always empty, no matter what tags the `<b-form-tags>` component currently has.

We could set the value of the native `<input>` to some sort of normalized string value based on the tags.
