### ISSUE TITLE
components are not registered with nuxt when it uses typescript

### ISSUE THREAD

**Issue by syffs** [bootstrap-vue/bootstrap-vue#6098]
### Steps to reproduce the bug

just look at the console in sandbox

### Expected behavior

components should be registered and work properly

### Versions

**Libraries:**

- BootstrapVue: 2.19.0

### Demo link

https://codesandbox.io/s/bootstrap-vue-nuxt-ts-tcddc

**Comment by jackmu95** [comment]
The problem is the `"exclude": ["node_modules"]` in your `tsconfig.json`.
