### ISSUE TITLE
v-model broken on b-input

### ISSUE THREAD

**Issue by arthurorbica** [bootstrap-vue/bootstrap-vue#6112]
### Describe the bug

v-model no longer works on b-input. I cannot enter any text into the input.

### Steps to reproduce the bug

[![Edit cool-haze-wqjnv](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-haze-wqjnv?fontsize=14&hidenavigation=1&theme=dark)

Try to enter text into the input but nothing will show up

### Expected behavior

Can enter text into the input

### Versions

**Libraries:**

- BootstrapVue: 2.20.0
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Windows PC
- Browser: Chrome
- Version: 87

### Demo link

See above

### Additional context

Seems to be a problem in 2.20. Reverting to 2.19 fixes the problem. Suspect related to https://github.com/bootstrap-vue/bootstrap-vue/pull/6084

**Comment by scenaristeur** [comment]
same for me
