### ISSUE TITLE
Native HTML5 tooltip appear on the disabled button

### ISSUE THREAD

**Issue by damirbogd** [bootstrap-vue/bootstrap-vue#6114]
### Describe the bug

Using v-b-tooltip with b-button results in unexpected behaviour. Native HTML5 tooltip will appear on the disabled b-button.

### Steps to reproduce the bug

1. Go to [CodeSandbox](https://codesandbox.io/s/e76lj)
2. Hover over the first button and notice that Native HTML5 tooltip will appear
3. Hover over the second button and check that Native HTML5 tooltip won't appear if there is ***to*** prop specified

### Expected behavior

Native HTML5 tooltip should not appear on the button (possibly other elements as well) when the state disabled set to true

### Versions

**Libraries:**

- BootstrapVue: 2.20.0
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Chrome
- Version: 87.0.4280.67 (Official Build) (x86_64)

### Demo link

[CodeSandbox](https://codesandbox.io/s/e76lj)

### Additional context

Interesting to see that it works correctly with buttons that have ***to*** prop specified

**Comment by jackmu95** [comment]
When a `href` or `to` prop is used on `<b-button>`, a anchor with button styles is render instead of a button element.
Chrome shows the `title` as native tooltip for `disabled` buttons but not for anchors.

**Comment by damirbogd** [comment]
thanks @jackmu95 for clarifying that!

for anyone else stumbling upon the same thing, probably going to include something like this in order to fix that

```
button:disabled {
  pointer-events: none;
}
```
