### ISSUE TITLE
tables question: can table header be turned off entirely?

### ISSUE THREAD

**Issue by mmilano** [bootstrap-vue/bootstrap-vue#6130]
Having gone through the docs and issues, i cant seem to find a clear answer.

Is it possible to render a <b-table> without any header row at all?

I have a design that would like to use the table to display a list of items in a custom format
with filter capability,
but do not want the regular column header row; the list will be topped with a custom element.

**Comment by Hiws** [comment]
You can add `thead-tr-class="d-none"` to hide the entire header.

**Comment by mmilano** [comment]
well, yes, i could have that not display.
to revise for more specificity: is it possible to not have the header generate/render at all?

**Comment by Hiws** [comment]
I don't think there's any way to completely stop the header from rendering. At least to my knowledge.

**Comment by mmilano** [comment]
ah. that is too bad. thanks.

**Comment by mmilano** [comment]
a followup question, tangentially related: 
is it possible to render the entire table row as a custom slot?

**Comment by DM2489** [comment]
@mmilano Not that I am aware of.

Perhaps you should consider using `BTableSimple`. You will lose a lot of the functionality that `BTable` and `BTableLite` come with. but that's the price you pay for complete control.

See https://bootstrap-vue.org/docs/components/table#comp-ref-b-table-slots for more info on `BTableLite`.

**Comment by mmilano** [comment]
thanks!
