### ISSUE TITLE
When click on calendar in dropdown it closes

### ISSUE THREAD

**Issue by AkhmedovSH** [bootstrap-vue/bootstrap-vue#6131]
### Describe the bug
I have 2 popups 1 dropdown and 1 calendar in dropdown like on image
![image](https://user-images.githubusercontent.com/24861395/101136933-da5fb400-362f-11eb-9707-7e9b0a2fee55.png)

and when i choose date in calendar my dropdown closes

### Expected behavior

Wanna not close my dropdown. I am thinking maybe add some props clickOutsideClose: false and i can change it to true if i need

### Versions

**Libraries:**

- BootstrapVue: 2.16.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**
- Browser: [Chrome]
calendar this plugin vue2-datepicker

**Comment by jackmu95** [comment]
@AkhmedovSH Can you please create a minimal reproduction of the issue on CodeSandbox or CodePen.

**Comment by AkhmedovSH** [comment]
> @AkhmedovSH Can you please create a minimal reproduction of the issue on CodeSandbox or CodePen.

https://codesandbox.io/s/goofy-sunset-1jm0d?file=/src/main.js

**Comment by Hiws** [comment]
It's happening because the datepicker you're using is appended to `<body>` by default, meaning that clicking inside the popup will count as clicking "outside" of the dropdown.
You can set the `append-to-body` prop on `<date-picker>` to false, to fix the issue.

<https://codesandbox.io/s/ecstatic-chaplygin-mttc3?file=/src/App.vue>

**Comment by AkhmedovSH** [comment]
> It's happening because the datepicker you're using is appended to `<body>` by default, meaning that clicking inside the popup will count as clicking "outside" of the dropdown.
> You can set the `append-to-body` prop on `<date-picker>` to false, to fix the issue.
> 
> https://codesandbox.io/s/ecstatic-chaplygin-mttc3?file=/src/App.vue

Thanks man
