### ISSUE TITLE
Many things are missing

### ISSUE THREAD

**Issue by lucapu88** [bootstrap-vue/bootstrap-vue#6133]
For now I have found three:

- date picker component that does not give the possibility of multiple selection of dates.
- timepicker component does not give the possibility to write timetables by hand instead of having to click every time.
- component card does not give the possibility to insert an image with src path of my local, but only web link! and to be able to insert an image from my local folders you need to use another b-img component which in practice cancels the usefulness of b-card.

It is right that people know this before using this library, so that they do not end up with the same problem as me!

**Comment by jackmu95** [comment]
@lucapu88 The `<b-card>` component handles relative ("local") images properly when you configure you project correctly.

We have a comprehensive guide in the documentation for that:
https://dev.bootstrap-vue.org/docs/reference/images

Here is an example project on CodeSandbox:
https://codesandbox.io/s/bootstrapvue-relative-images-sqfvu

**Comment by lucapu88** [comment]
> @lucapu88 The `<b-card>` component handles relative ("local") images properly when you configure you project correctly.
> 
> We have a comprehensive guide in the documentation for that:
> https://dev.bootstrap-vue.org/docs/reference/images
> 
> Here is an example project on CodeSandbox:
> https://codesandbox.io/s/bootstrapvue-relative-images-sqfvu

ok thanks for the solution. Your colleague @Hiws  was unable to answer me on discord and even banned me for no good reason accusing me of saying things that were not true! I said a sentence in the dialect of my language that he interpreted in his own way ...
So I give you some advice, hire competent moderators, because it's absurd that I write to you on discord and your moderators can't answer, and they even have the courage to answer "I don't know" .... but what answer is this? be competent or don't answer. Or am I wrong?
Meanwhile, I can no longer ask for clarification on your discord page because I was unfairly banned!

**Comment by Hiws** [comment]
I think you're misunderstanding a few things here.

> hire competent moderators

Firstly, the work I do for this project and helping people is completely unpaid, and I do it because i want to.

> and they even have the courage to answer "I don't know".... but what answer is this? be competent or don't answer.

I attempted to help you by linking you the relevant documentation, which is the same solution as Jackmu has implemented in the example. Since that didn't work, I said i didn't know, because i didn't know why it wasn't working in your project.
Would you much prefer someone simply ignored you instead of attempting to assist you?

> even banned me for no good reason accusing me of saying things that were not true! I said a sentence in the dialect of my 
language that he interpreted in his own way...

Based on some research, the dialect you speak of is part of the `Neapolitan` language. I had someone familiar with that dialect translate it for me, and once I saw that translation I did indeed ban you.
While the translation might not have been 100% correct. I very much doubt it could be misinterpreted in such a vulgar way, as to what was translated for me.


You can continue making feature requests and asking questions here, so i suggest you drop your case and move on.

**Comment by lucapu88** [comment]
> I think you're misunderstanding a few things here.
> 
> > hire competent moderators
> 
> Firstly, the work I do for this project and helping people is completely unpaid, and I do it because i want to. I was never hired or asked to help with the project, it's simply something I chose to do, and after awhile the team invited me to join as a contributer.
> 
> > and they even have the courage to answer "I don't know".... but what answer is this? be competent or don't answer.
> 
> I attempted to help you by linking you the relevant documentation, which is the same solution as Jackmu has implemented in the example. Since that didn't work, I said i didn't know, because i didn't know why it wasn't working in your project.
> Would you much prefer someone simply ignored you instead of attempting to assist you?
> 
> > even banned me for no good reason accusing me of saying things that were not true! I said a sentence in the dialect of my
> > language that he interpreted in his own way...
> 
> Based on some research, the dialect you speak of is part of the `Neapolitan` language. I had someone familiar with that dialect translate it for me, and once I saw that translation I did indeed ban you.
> While the translation might not have been 100% correct. I very much doubt it could be misinterpreted in such a vulgar way, as to what was translated for me.
> 
> You can continue making feature requests and asking questions here, so i suggest you drop your case and move on.

unfortunately I'm not Neapolitan, so:
1. you have completely wrong search.
2. change people from whom you inquire because that person who translated you translated wrongly.
3. in practice you banned me without being sure of what I wrote more informing you at random.
4. I'd rather you don't answer if you don't know, instead of saying "I don't know".
5. I will have to open a lot of requests (sometimes even apparently stupid) on this page, when you have a dedicated discord channel and you would avoid a lot of reports on github .... It seems a little intelligent thing to me.

Ok as you like, at every little bullshit I will open a request on github, even if the answer is equivalent to a simple "yes" or "no".
Thanks!
And anyway the dialects change a lot, they are not all the same, and this thing that you associated me directly with a Neapolitan without informing you offends me.
You do the moderator's work for free and you do it badly, very badly indeed!
Good day

**Comment by Hiws** [comment]
Feel free to use the new `Discussions` section on GitHub if you feel like your problem isn't important enough for an Issue.

**Comment by lucapu88** [comment]
> Feel free to use the new `Discussions` section on GitHub if you feel like your problem isn't important enough for an Issue.

no I like it here, there are competent people who know how to answer instead of saying "I don't know".
You can go back to doing your "job" (badly done) on discord. You can keep banning people unfairly, without informing yourself, totally random.
When you see my name with the thousand questions that I will ask here, you can also not answer. Thank you and good day.
What a nice assistance......................................................

**Comment by Hiws** [comment]
I do apologize if I've gotten your sentence translated incorrectly.
Would you mind telling me which dialect it is that you speak, and also translating "vafammok a mamt" for me, so that I can understand what you actually said?

**Comment by lucapu88** [comment]
> I do apologize if I've gotten your sentence translated incorrectly.
> Would you mind telling me which dialect it is that you speak, and also translating "vafammok a mamt" for me, so that I can understand what you actually said?

look you're the wrong person. I didn't say these things, so kindly delete this statement from you or I'll legally do so! let's end the conversation here. I don't want to have anything to do with people like you anymore.

**Comment by jackmu95** [comment]
I will close this issue and this heated discussion.
It is a duplicate anyway.
