### ISSUE TITLE
Form checkbox fails to load with strict Content Security Policy

### ISSUE THREAD

**Issue by ccsaposs** [bootstrap-vue/bootstrap-vue#6136]
### Describe the bug

With a Content Security Policy (CSP) of `img-src 'self'`, the checkmark in the form checkbox fails to load on Chrome for Android.

### Steps to reproduce the bug

1. On Chrome from Android, go to https://5fcae2e0faed132d6cd76761--vom-qr-codes.netlify.app/create/
2. Click on one of the checkboxes
3. The checkbox turns blue but no checkmark shows up
4. If you check the console, you'll see this error:
![Screenshot](https://user-images.githubusercontent.com/32380359/101227036-5c110b00-364b-11eb-9fc0-1b0799d97016.png)

### Expected behavior

The checkbox should turn blue **and** a checkmark should show up

### Versions

**Libraries:**

- BootstrapVue: 2.20.1
- Bootstrap: 4.5.2
- Vue: 2.6.12

**Environment:**

- Device: Pixel 3
- OS: Android 11
- Browser: Chrome
- Version: 86

**Comment by DM2489** [comment]
This isn't really anything to do with Bootstrap-Vue, it's a CSP definition problem.

`'self'`
> Refers to the origin from which the protected document is being served, including the same URL scheme and port number.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src

`data` does not fit this policy definition.

You need to something like: `img-src: 'self' data:;` in your CSP policy.

**Comment by ccsaposs** [comment]
Is it possible to use bootstrap-vue without putting `data:` into the img-src of my CSP?  I don't want to allow arbitrary images to load.

**Comment by DM2489** [comment]
Looking at the source code, it uses `data:` to draw the ticks in the checkboxes.

You can either enable `data:` in your CSP, or you can use the `plain` prop on the checkbox to use the native HTML elements.

If you chose to use the `plain` prop, be aware that there may be other components that also use `data:`.

**Comment by ccsaposs** [comment]
Nevermind--it looks like this is a [bootstrap issue](https://github.com/twbs/bootstrap/issues/25394) and not a bootstrap-vue issue.

Thank you for your help.
