### ISSUE TITLE
"b-form-checkbox-group buttons" remove error when v-model is a String. Support single selection mode

### ISSUE THREAD

**Issue by chefjuanpi** [bootstrap-vue/bootstrap-vue#6137]
### Describe the bug

Hi, I try to do use "b-form-checkbox-group buttons" on single selection mode, 

I need to set multiple options, one option selected by default, and the visitors can select only one at a time, and need to select one of the options, it can't be empty.

testing I realize if I initialize v-model variable as a string containing one of the values of the options, the "b-form-checkbox-group buttons" work just I need, single selection mode, and send the right data on submit, it's really nice and easy to understand for the customers.

The Issue is the error msg on the console "[Vue warn]: Invalid prop: type check failed for prop "checked". Expected Array, got String with value ...." it populates console at no stop.

I think to have the option of single selection mode on the " b-form-checkbox-group buttons" it's not a bug, it's a nice improvement.

### Steps to reproduce the bug
use b-form-checkbox-group:

```
<template>
  <b-form-checkbox-group v-model="favorite" :options='fruits' button-variant='success' name="favorite-fruit" buttons></b-form-checkbox-group>
</template>
<script>
export default {
  data() {
    return {
      favorite: 'kiwy',
      fruits: [
        { text: 'Banana', value: 'banana' },
        { text: 'Kiwy', value: 'kiwy' },
        { text: 'Orange', value: 'orange' },
      ],
    }
  }

...
}
</script>

```

you will see It works like a charm, you can only select one option at a time.
At the same time, the console receives no stop this error msg: "Vue warn]: Invalid prop: type check failed for prop "checked". Expected Array, got String with value ..." there appears the string value of v-model.

### Expected behavior
The Single selection mode on b-form-checkbox-group using Buttons be officially supported, and update on the guide and the errors  alerts on console disappear

### Versions
2.20.1

**Libraries:**
no extras

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**
- Device: [e.g. Mac or iPhone X] pc, mobile and safari navigators
- OS: [e.g. macOS Mojave or iOS 12] Multiples, I test on mac, windows, IOS
- Browser: [e.g. Chrome] chrome and safari
- Version: [e.g. 70] chrome 86

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
Checkboxes are designed to allow multiple selections. 
That's why it expects an array as a model.

If you only want to allow the user to select a single value, you should use radio buttons.
Which are designed to allow only one to be selected within a group.

Basically, replace `<b-form-checkbox-group>` with `<b-form-radio-group>` and it should work as you want.
```html
<b-form-radio-group v-model="favorite" :options='fruits' button-variant='success' name="favorite-fruit" buttons></b-form-radio-group>
```

**Comment by chefjuanpi** [comment]
ohh i understand
