### ISSUE TITLE
Invalid prop check in form datepicker

### ISSUE THREAD

**Issue by fessacchiotto** [bootstrap-vue/bootstrap-vue#6138]
The 'value' of the v-model in the datepicker component is initialized as:

`{ 
     form.data_registrazione: null 
}`

and then it is set as `Date`:

`this.form.data_registrazione = DateTime.fromISO(response.data.data_registrazione).toJSDate()`

This is the template:

``` js
        <b-form-datepicker 
          v-model="form.data_registrazione" 
          locale="it-IT" 
          start-weekday=1 
          hide-header 
          value-as-date 
          :date-format-options="{ year: 'numeric', month: 'numeric', day: 'numeric' }" 
          placeholder="Data operazione..." 
          ref="data_registrazione" 
          :disabled="setDisabledStatus('data_registrazione')"
        />
```

As soon as I mount the component containing the template above, I get the following warning:

``` 
[Vue warn]: Invalid prop: type check failed for prop "value". Expected String with value "Tue Dec 01 2020 00:00:00 GMT+0100 (Central European Standard Time)", got Date 

found in

---> <BVFormBtnLabelControl>
       <BFormDatepicker>
         <BFormGroup>
           <ValidationProvider>
             <DatiRegistrazione>
               <BTab>
                 <ValidationObserver>
                   <BTabs>
                     <ValidationObserver>
                       <Registrazione> at src/components/registrazione/Registrazione.vue
                         <App> at src/App.vue
                           <Root>
```
Any hints on how to get rid of it?

Many thanks in advance.

**Comment by jackmu95** [comment]
@fessacchiotto Can you please create a minimal reproduction of the issue on CodeSanbox.

This would help a lot to see if #6141 also fixes this.

**Comment by monprin** [comment]
Having the same issue after upgrading from v2.16.0 -> v2.20.1

I did come up with a fairly minimal Sandbox here: https://codesandbox.io/s/musing-mirzakhani-c69vn?file=/src/App.vue

This issue *seems* to be when swapping out the variable in some way. In the sandbox I have a button to toggle between two date vars (a simplification of a workflow I use in my app), and when toggling from the `null` to the `new Date()` it reliably fires the error in question.

Let me know if there is anything else I can do to help with diagnosis.

**Comment by monprin** [comment]
For added context, based on rudimentary backtracking through versions, the issue seems to have been introduced between v2.18.1 and v2.19.0.

**Comment by jackmu95** [comment]
@monprin Thanks for the example and the further investigation.
I will look into it and it will be fixed with the next release.
