### ISSUE TITLE
Icon in Table is invisible

### ISSUE THREAD

**Issue by Stephan811D** [bootstrap-vue/bootstrap-vue#6142]
Hi,

I created a table which should display an icon in a field. 

This is the code where i push the data into the items-field:
`this.items.push({ name:'Status:', value: '<span style="color:red">offline</span><b-icon icon="circle-fill"></b-icon>'}); 
`

That is the table code:
    
    <b-table borderless responsive thead-class="d-none" small :items="items">
      <template #cell(value)="data">
        <div v-html="data.value"></div>
      </template>
    </b-table>

This is the dom in the browser:

![Bildschirmfoto 2020-12-06 um 23 59 01](https://user-images.githubusercontent.com/37579239/101295631-16a53700-381f-11eb-9d06-48a03c928728.png)

But the icon is not visible:
![Bildschirmfoto 2020-12-07 um 00 00 11](https://user-images.githubusercontent.com/37579239/101295657-35a3c900-381f-11eb-9fca-071f075f846a.png)

Did i miss something or is that a bug?

**Comment by Hiws** [comment]
`v-html` only supports native HTML elements. 
You can't use it with custom components such as `<b-icon>`
