### ISSUE TITLE
data-toggle="buttons" doesn't work ; standard Bootstrap not supported?

### ISSUE THREAD

**Issue by Alsciende** [bootstrap-vue/bootstrap-vue#615]
My app successfully included bootstrap-vue and used `<b-pagination>`. I then went on to use a `data-toggle="'buttons"` button group from the standard Bootstrap4 toolset. The style was there, but the behavior was not. Apparently the javascript that decorates `data-toggle` elements is not active. I couldn't find a note about this in the documentation of bootstrap-vue, so I'm asking here: can I use this library in my application and expect the "standard" Bootstrap 4 features, or am I restricted to the components implemented by the library? If the former, why didn't my `data-toggle` register and how can I fix it? Thanks for your time.

**Comment by alexsasharegan** [comment]
Would you mind linking to bootstrap doc page around this? I'm trying to find the `data-toggle` explanation with regards to pagination to see how BV implements this.

BV doesn't require jQuery, so javascript features have been reimplemented using Vue. As far as I know, BV has nearly 100% feature parity to javascript behaviors.

**Comment by Alsciende** [comment]
Oh, sure, sorry: https://v4-alpha.getbootstrap.com/components/buttons/#toggle-states

**Comment by tmorehouse** [comment]
In Vue.js, things work differently with reactivity, as compared to jQuery

BootstrapVue uses Bootstrap's CSS, but not their javascript.  BootstrapVue has a``v-b-toggle` directive for toggling content with the `collapse` component, and a `v-b-modal` toggler that is used by the `modal` component.

**Comment by tmorehouse** [comment]
The toggle tae for  button might be something we can add to the base `b-button` component, allowing you to set a "pressed" state

**Comment by Alsciende** [comment]
As you can see from the doc, `data-toggle="buttons"` is not for `button` elements, actually. It's for other kinds of elements, like `label`, to give them button-style toggling. It's very useful with `radio` inputs, since the result is a set of exclusive buttons. Maybe BV has another way of implementing this?

**Comment by tmorehouse** [comment]
For the _Checkbox and radio buttons_ concept, we might need to add a new component for that or make a few tweaks/options for radio (to make it button style).  For checkbox, we would need to probably create a new wrapper component to handle the series of checkboxes, or alter the current form-checkbox implementation to take an options list like form-radio does.

**Comment by tmorehouse** [comment]
The following PR's have been opened:
- #729  Support button style checkboxes
- #728  Support button style radio buttons
- #715 Support for "pressed" state (merged into master)

**Comment by tmorehouse** [comment]
Note that using `data-toggle="xxxx"` features on non-components will not work, as Bootstrap-Vue only uses bootstrap V4's CSS for styling, and **not it's `bootstrap.js` library**.  (see Bootstrap-Vue docs https://bootstrap-vue.js.org/docs/ section **Migrating a project already using Bootstrap**)
