### ISSUE TITLE
Button render issue in b-card-footer inside b-collapse with float-right set

### ISSUE THREAD

**Issue by Flawe** [bootstrap-vue/bootstrap-vue#6155]
### Describe the bug

When placing a b-button inside a b-card-footer that's inside a b-collapse, and the button has class="float-right" set, there seems to be a minor rendering issue where the card footer is split in half horizontally.

### Steps to reproduce the bug

1. See demo link below

### Expected behavior

Card footer should render the same as when button does not have class="float-right" set.

### Versions

**Libraries:**

- BootstrapVue: 2.19.0
- Bootstrap: 4.5.3
- Nuxt: 2.14.7

**Environment:**

- Device: Mac
- OS: Catalina
- Browser: Chrome and Safari

### Demo link

https://jsfiddle.net/0r7vd1sb/

**Comment by Hiws** [comment]
Elements with `float` doesn't take up any space, which is why you're seeing the behavior you are.
You should generally avoid using float, as there are better ways now.

If you just want to align the button to the right, you can add `text-right` to `<b-card-footer>`.

**Comment by Flawe** [comment]
@Hiws, excellent, thank you! I also noticed that `clearfix` on `<b-card-footer>` did the trick, but I like your solution better.
