### ISSUE TITLE
Adding content outside modal available slots

### ISSUE THREAD

**Issue by alexrafael10** [bootstrap-vue/bootstrap-vue#6160]
Sorry if I butchered the issue template, more than a "Feature Request" this is a small question. My bad if this is not the place. 

### Is your feature request related to a problem? Please describe...

I would like to find a way to add code outside of the available slots, i.e. between the modal header and the modal body. So far i can't find a way of doing that, maybe is not possible because of the bootstrap modal specification or something, but just in case there is one, asking :D 

Thanks in advance.

**Comment by DM2489** [comment]
I'm not entirely sure what you mean. Could you provide a loose design of the intended layout?

**Comment by alexrafael10** [comment]
We have the header, body, and footer slots, right?

![image](https://user-images.githubusercontent.com/21692735/102610865-aba40c00-410c-11eb-9cc6-3685649c6411.png)

And this is rendered something like:

![image](https://user-images.githubusercontent.com/21692735/102610948-d3936f80-410c-11eb-86e5-c8476e2f232f.png)

My question is if there was any way of adding something lets say between the `modal-header` and the `modal-body`:

![image](https://user-images.githubusercontent.com/21692735/102611154-2836ea80-410d-11eb-882b-03480c411eb6.png)

It's a weird requirement, I know, but was wondering if it was possible somehow.

**Comment by DM2489** [comment]
But, why? There is the the modal-body slot, which you can use you insert anything into.

**Comment by kingschnulli** [comment]
Would be nice to have some more slots, was struggeling to get a full screen modal in mobile and having slots to modify all parts would be helpful. This couldn't be done with css as vh shifts on android mobile when the on screen keyboard appears.
