### ISSUE TITLE
[dropdowns] Rename slot on nav-item-dropdown

### ISSUE THREAD

**Issue by yordis** [bootstrap-vue/bootstrap-vue#617]
I would suggest to change `text` slot name to `trigger` on https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/nav-item-dropdown.vue#L15

If I put an image inside only, like an avatar, then it will be no longer a `text` and like another use cases ... so I think that `trigger` will make more sense

**Comment by tmorehouse** [comment]
This would be a breaking change, so it might be a good candidate change for when BS V4.beta.` comes out.

**Comment by yordis** [comment]
@tmorehouse it's better to do it now that the project is constantly updating that wait until more people use it and it's hard for them to switch, talking from my own experience

**Comment by yordis** [comment]
@tmorehouse I would say over here as well https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/dropdown.vue#L14

**Comment by tmorehouse** [comment]
@pi0, what do you think about changing the slot name from `text` to `trigger`? (this would need to be done in all the dropdown variants).

It might be possible to deprecate the slot `text` using a condition test for the slot name in `this.$slots['slotname']` and use v-if to render the slot.

**Comment by tmorehouse** [comment]
Although trigger is still wrapped inside a button element, so it might be better to be called `trigger-content` or `button-content`, or similar. as some people might assume it is a replacement for the trigger button as a whole.

**Comment by tmorehouse** [comment]
PR #627 addresses this issue, by adding the new slot `button-content`, while retaining support for the deprecated slot `text`

**Comment by tmorehouse** [comment]
@yordis 

Release v0.18..0 is now available (latest), and there is a new slot named `button-content` that deprecates the old slot `text`
