### ISSUE TITLE
Make b-table items name capitalization optional

### ISSUE THREAD

**Issue by krzysztofjeziorny** [bootstrap-vue/bootstrap-vue#6170]
As [documented](https://bootstrap-vue.org/docs/components/table#items-record-data), field names are automatically "humanized".

In some projects it is desired to see the exact name of the key instead of the converted name.

**Comment by Hiws** [comment]
A simple workaround to this could be to utilize the `head()` slot to display the non-humanized property name.
```html
<b-table ...>
  <template #head()="{ column }">
    {{ column }}
  </template>
</b-table>
```

**Comment by TravellerSam** [comment]
Thanks for the workaround, @Hiws! I had it working with

```vue
<template #head()="scope">
    {{ scope.column }}
</template>
```
