### ISSUE TITLE
Add range of values of props to the Documentation

### ISSUE THREAD

**Issue by yordis** [bootstrap-vue/bootstrap-vue#618]
I notice that you define the `Default Value`  of a property but I can't know what is the permitted list of values that I could use in the components.

**Comment by tmorehouse** [comment]
@yordis Check out our newer documentation, which has expanded information about many of the components. https://bootstrap-vue.js.org/

As well, there are a few new document pages available in the master at https://github.com/bootstrap-vue/bootstrap-vue/tree/master/docs/components, which will be available in release v0.18.0 which is coming out shortly (which will apper at https://bootstrap-vue.js.org/ when released)

Are there any particular components you are looking at that needs clarification?

**Comment by yordis** [comment]
> Are there any particular components you are looking at that needs clarification?

@tmorehouse I was looking at the `navbar` which have a bunch of components on it. But I am fine with it, too much time with Bootstrap 😄 I will figure it out

**Comment by tmorehouse** [comment]
We should hopefully have some extended documentation for `b-navbar` in the very near future.

**Comment by tmorehouse** [comment]
The new documentation will have a _live example_ playground that you can play with the examples given.

**Comment by yordis** [comment]
@tmorehouse I checked the button documentation and I have some feedbacks.

1. Add `Properties` in the description the same way we have `Events`
2. Because there is a `properties` text but it's too small and it's attach to the table, either, move the table content up and then list the properties description down or move the text instead.
3. Wouldn't be better if we add all the posible properties in the table as well?

I think for the documentation is really worth to check how Polymer people structure and/or document the elements.

**Comment by tmorehouse** [comment]
The props tables at the bottom (below the green `<component>` tag) are automatically generated by inspecting the component itself, and are not written in the meta.json like the events are (as we can't pull out the events automatically from the component), so it might be a bit harder to find a way to add a description to that props table or get a list of possible options (as majy of these options are based on bootstrap CSS classes, of which you can implement your own (i.e. the `.has-*` and `.btn<variant>` classes.  So they are not always set in stone.

But we will see about moving the main component table upwards, although we have had other ask for more textual content explaining the use of each property, along with the current default available values based on Bootstrap CSS.

**Comment by yordis** [comment]
@tmorehouse we could drive the whole documentation throw comments on the components, I think it will be really good to actually study what Polymer team did there.

**Comment by tmorehouse** [comment]
Take a look at the [docs/nuxt](https://github.com/bootstrap-vue/bootstrap-vue/tree/master/docs/nuxt) cs directory to see how the online documentation is automatically generated.  Maybe after inspection you might have an idea of how to improve it? (we actually use BootstrapVue to and Nuxt to generate the pages).

We are always open to suggestion/PR's on how to improve the documentation code.  If you have an idea on how to help (we are only a few team members), open a PR with some nifty code.

**Comment by jmjf** [comment]
Having a description for props would help. The docs are helpful, but I sometimes end up reading the code to (try to) figure out what a prop does or hacking around with it until I figure it out.

**Approach 1**
Taking ideas from [propdoc](https://github.com/propellant/doctor) without adopting the package, add metadata attributes to each prop and add them to the template. Namespace the attributes (`b_description`) to reduce risk of conflict with future Vue releases. That may add overhead to the component.

**Approach 2**
Add a props array to the JSON file with objects like:
```JSON
"props": [
  { "prop": "propname",
    "range": "range of values if applicable", 
    "description": "short description"
  }
]
```
Then add code to the docs to matching props from `props_items()` with the JSON file. That approach avoids adding size to the component, but adds work to build code and JSON.

Other ideas? Or does one of those make sense from the BSV team's perspective?

**Comment by tmorehouse** [comment]
We are contemplating adding a metadata property in each component's doc meta.json file, which would be keyed by prop name, and contain the possible values for that particular prop on that component, as well as a possible brief description.

The extra meta.json object would only have props that need additional information.
