### ISSUE TITLE
b-table: highlight row on focus with arrow keys

### ISSUE THREAD

**Issue by mungra** [bootstrap-vue/bootstrap-vue#6182]
Is there a way to highlight rows when using the arrow keys. something similar to the hover event? 

_Originally posted by @mungra in https://github.com/bootstrap-vue/bootstrap-vue/issues/2869#issuecomment-742732155_

**Comment by emfluenceindia** [comment]
Most probably there is no inbuilt solution available for this yet. In my opinion, we need to write our own Keydown handlers.
However, by doing this, we would lose the mouse click control. so, to keep that behaviour alive as well, we need to have a Click event listener call the Keydown triggers from there.

**Comment by Hiws** [comment]
> Is there a way to highlight rows when using the arrow keys. something similar to the hover event?
> 
> _Originally posted by @mungra in [#2869 (comment)](https://github.com/bootstrap-vue/bootstrap-vue/issues/2869#issuecomment-742732155)_

What is it you're trying to accomplish?
