### ISSUE TITLE
TimePicker ability to write instead of clicking

### ISSUE THREAD

**Issue by lucapu88** [bootstrap-vue/bootstrap-vue#6188]
https://bootstrap-vue.org/docs/components/form-timepicker#form-timepicker

is it possible to write the time instead of clicking every time?
it's a really uncomfortable thing and creates a very low user experience

**Comment by jackmu95** [comment]
@lucapu88 What you wan't is that the highlighted text is a input instead?

![Bildschirmfoto 2020-12-14 um 11 35 31](https://user-images.githubusercontent.com/2737132/102071366-aab76580-3e00-11eb-89ef-24ce9bee6ca8.png)

**Comment by lucapu88** [comment]
> @lucapu88 What you wan't is that the highlighted text is a input instead?
> 
> ![Bildschirmfoto 2020-12-14 um 11 35 31](https://user-images.githubusercontent.com/2737132/102071366-aab76580-3e00-11eb-89ef-24ce9bee6ca8.png)

No. I want to be able to write the time instead of clicking on the arrow until I reach the desired time ... it would be more convenient to write an hour

**Comment by lucapu88** [comment]
![Schermata da 2020-12-15 16-06-18](https://user-images.githubusercontent.com/56302007/102236652-0b739a80-3ef4-11eb-93d0-255a2e135e26.png)
this was what i was looking for... thanks for the help. I'll have to customize it quite a bit but it could go....
in the photo there is a syntax error that caused me problems when I copied the code and it took me a while to understand where it was.

**Comment by jackmu95** [comment]
@lucapu88 The example markup was fixed with #6206 and will become live with the next patch release.

**Comment by lucapu88** [comment]
> @lucapu88 The example markup was fixed with #6206 and will become live with the next patch release.

great! if I can give you some advice make sure that the user cannot write letters but only numbers ... currently if I write "foo" within the time he accepts it, it should only accept numbers and a valid time format.
