### ISSUE TITLE
[form-checkbox] Should be able to provide options array

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#620]
It would be nice to be able to (optionally) pass an `options` array or object, and have a series of checkboxes created, similar to how `b-form-radio` works

**Comment by alexsasharegan** [comment]
Would that make the v-model implementation work? I remember helping PR something to allow arrays as the bound value.

**Comment by tmorehouse** [comment]
Yeah, it would make the v-model work "correctly" I would think, since Vue will create an array of values for checkboxes with the same name (or bound to the same variable).

**Comment by tmorehouse** [comment]
Trying to figure a way top keep current functionality (if you want a single checkbox) and still handle the options array.

A localValue variable (in data) would be used to handle the list of checked items (via v-model on the actual checks), and a v-model to pass the value(s) back to the parent component.

It would be similar to radio in ways.

**Comment by tmorehouse** [comment]
Maybe a new component called `<b-form-checkboxes>` to add this feature rather than mucking with the existing `<b-form-checkbox>` component might be best.

**Comment by tmorehouse** [comment]
PR #994 should address this issue
