### ISSUE TITLE
Card groups have cards with missing styles

### ISSUE THREAD

**Issue by mvind** [bootstrap-vue/bootstrap-vue#6207]
### Describe the bug

Card group in column formation produces cards with missing styling. 

### Steps to reproduce the bug
[See pictures here](https://imgur.com/a/OJS2BbO)

My code follows the documentation pretty spot on. I create a cardgroup using a loop: 
```javascript
<b-card-group columns v-if="gotData">
		     <deckthumbnail
          v-for="deck in results"
          :deck="deck"
          :loading="false"
          :key="deck.deck_id"
          :ref="'deck_' + deck.deck_id"
        />
</b-card-group> 
```
where ``deckthumbnail`` is 
```javascript
<template>
  <div @click="press">
    <b-card no-body class="shadow deck-result">
      <b-card-header header-bg-variant="white">
        <div v-if="loading">
          <b-skeleton></b-skeleton>
        </div>
        <div v-else id="header">
          {{ deck.deck_name }}
        </div>
      </b-card-header>

      <!-- mount preview editor here  -->
      <b-card-body body-bg-variant="white">
        <div v-if="loading">
          <b-skeleton></b-skeleton>
        </div>
        <div v-else>
          {{ deck.description }}
        </div>
        <!-- <editor-content class="editor__content" :editor="editor"/> -->
        <!-- <cardpreview :card="card" ref="preview" /> -->
      </b-card-body>

      <b-card-footer footer-bg-variant="white">
        <div id="footer">
          <div v-if="loading">
            <b-skeleton></b-skeleton>
          </div>
        </div>
      </b-card-footer>
    </b-card>
  </div>
</template>

```

### Expected behavior
I expect that all the cards in the card group have the same styling. 

### Versions

**Libraries:**

- "bootstrap-vue": "^2.20.1"
- "bootstrap": "^4.5.2",
- "vue": "^2.6.12",

**Environment:**

- Device: Mac
- OS: Mac OS
- Browser: Chrome
- Version 87.0.4280.88

**Comment by jackmu95** [comment]
@mvind Can you please create a minimal reproduction of the issue on CodeSandbox or CodePen.

**Comment by mvind** [comment]
@jackmu95 sure, do you have a template to a codepen?

**Comment by jackmu95** [comment]
@mvind For sure, but you can just create one from the "Playground":
https://codepen.io/pen?&editors=101

**Comment by mvind** [comment]
I have tried and failed to replicate the bug in a codepen environment. Anyways after some experimenting I found that if I simply remove all ``class`` attributes in the ``<b-card>`` I don't get any missing styles anymore. 

I will just remove all class styling and close this issue for now.
