### ISSUE TITLE
[form-select] Cannot set value when return-object="true"

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#621]
It appears that one cannot set the v-model value when `return-object` is `true`.

https://jsfiddle.net/bootstrapvue/osty8mc8/

`localvalue` (inside `b-form-select`) expects to be the `value` field of the option(s), but the watcher for `value`, blindly passes the v-model value to `localvalue`, which is not what should be expected.

Does anyone actually use the `return-object` feature?  Trying to get it to work on a two-way v-model might be a bit of code overhead,

When not in `return-object` mode, it is also possible to programmatically select a `disabled` option (which should not be allowed)

**Comment by jmjf** [comment]
I was trying to use it a few minutes ago and discovered this problem.

My quick workaround was to put the value in another data item and write a computed to set the object.

```javascript
data () {
  objectToSet: {}
  selectedId: -1
  listOfObjects: [ ... ]
}

computed: {
  setObjectToSet () {
    if (this.selectedId > -1) {
      this.objectToSet = this.listOfObjects.find((item) => {
        return item.id = this.selectedId
      }
    }
  }
}
```

Or it could be a computed setter or a watcher. I'll end up moving my form controls into components, though, so this will become an `$emit()` to the parent and `objectToSet` will go away. (Debating whether to leave `$emit()` in a computed, move it to a watcher, or an onchange method.)

**Comment by tmorehouse** [comment]
After working on the `form-select` code in another PR, the return object stuff adds a lot of overhead code.

It might be better to remove this option (`return-object`) as the object it returns is the massaged object (by the `form-options.js` mixin), which is not the same object that is originally passed to the `options` prop.

One option for replacement is to emit a separate event with the selected option object, separate from the value v-model uses (which would just be the string value of the option..

**Comment by jmjf** [comment]
I ended up with something like the code below, which sounds similar to what you describe. This solution works, seems simple, and is probably best left to the developer. The component's default input event works fine for simple types, but for objects, this seems reasonable and gets me an object back in v-model. The options array is a computed property, so can be customized as needed.

```html
<b-form-select 
  v-model="optionId"
  :options="options"
  text-field="shortName"
  value-field="id"
  @input="inputSelect" 
>
</b-form-select>
```
```javascript
methods: {
  inputSelect () {
    this.$emit('input', this.options.find(item => item.id === this.optionId))
  }
}
```

**Comment by r4fx** [comment]
above solution doesn't work for me,
i still can't get the value

**Comment by tmorehouse** [comment]
What you might need to do is not set `return-object` (I think we will be deprecating it in a later release),

And then maintain an object keyed by the `value` string in your app, and then lookup the object based on the `value`

**Comment by tmorehouse** [comment]
PR #994 Will address this issue, and no longer needs the `return-object` prop.

**Comment by omarjebari** [comment]
I would just use vue-select then apply the same css classes that vue-bootstrap applies.
vue-select easily handles objects so i dont know why <b-form-select> can't.
