### ISSUE TITLE
Input time with 15 minutes step

### ISSUE THREAD

**Issue by lucapu88** [bootstrap-vue/bootstrap-vue#6218]
I have this input time component and I would like the minutes to be marked in steps of 15... currently as I wrote it doesn't work... is there a solution?

```
<b-form-input
     minutes-step="15"
    type="time" >
</b-form-input>
```

**Comment by Hiws** [comment]
You can specify how much it should step using the `step` attribute.
You need to provide the step in seconds. So 15 minutes would be 900 seconds.

Reference: https://html.spec.whatwg.org/multipage/input.html#time-state-(type=time)
