### ISSUE TITLE
Version 2.21.0 seems to have broken the click event on <b-badge>

### ISSUE THREAD

**Issue by CarnivalBen** [bootstrap-vue/bootstrap-vue#6219]
Since v2.21.0, adding a click event to a **&lt;b-badge&gt;** component no longer works.

Example:
```
<div id="app">
  <b-badge style="cursor: pointer;" @click="clickme">Test</b-badge>
</div>
```

```
new Vue({
  el: "#app",
  methods: {
    clickme() {
      console.log("CLICKED!");
    }
  }
});
```

If I click the badge, nothing gets written to the console.

If I downgrade to **bootstrap-vue v2.20.1** then the same code would output "CLICKED!" as expected.

If I modify the badge to use @click.native, this also seems to fix it.

**Environment:**
- bootstrap 4.5.3
- vue 2.6.12
- bootstrap-vue 2.21.0

Demo: [https://jsfiddle.net/bg100/0qmsgyoL/5/](https://jsfiddle.net/bg100/0qmsgyoL/5/)

**Comment by Hiws** [comment]
Thanks for the report. 

It's probably related to this issue: https://github.com/bootstrap-vue/bootstrap-vue/issues/6209
Which has been fixed in: https://github.com/bootstrap-vue/bootstrap-vue/pull/6217

The patch `2.21.1` patch should hopefully release at some point today.
