### ISSUE TITLE
[form-select] `text-field` property doesn't work when the values is an object

### ISSUE THREAD

**Issue by hydraheim** [bootstrap-vue/bootstrap-vue#622]
Here's a fiddle: https://jsfiddle.net/7m4oa0ed/3/

In short, the "text-field" property is not picked up, but the "value-field" works (as you can see if you inspect the select.

Docs reference: https://bootstrap-vue.js.org/docs/components/form-select

**Comment by tmorehouse** [comment]
I think I see the issue.

You are using the object format for specifying your options, rather than a plain array of objects.  I think the component code is missing  the checks when this type of object is encountered.

**Comment by tmorehouse** [comment]
@hydraheim this fix PR has been merged into master and should be available in the next release (v0.18.0) coming soon.

**Comment by tmorehouse** [comment]
@hydraheim 

Release v0.18..0 is now available (latest), and this issue *should* be resolved.
