### ISSUE TITLE
Toast fading too quick no matter the options.

### ISSUE THREAD

**Issue by ikkysleepy** [bootstrap-vue/bootstrap-vue#6230]
### Describe the bug

Toast appears or fades too quick, and no auto hide does nothing

### Steps to reproduce the bug

`        <b-button @click="makeToast()">Show Toast</b-button>
`
```
  makeToast(append = false) {
      this.$bvToast.toast(`This is toast test`, {
        title: 'BootstrapVue Toast',
        autoHideDelay: 15000,
        appendToast: append
      })
    },
```

### Expected behavior

Fades with the auto hide delay options. I tried no auto hide but it does not work either.

### Versions

**Libraries:**

- BootstrapVue: 2.21.1
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Mac
- OS:Big Sur
- Browser: Firefox / Safari
- Version: Latest

### Additional context
 This is in Laravel PHP with vue. I had similar problems with the popover fading too quick, but it has been fixed now. Is there any global way to slow down the delay ?

**Comment by Hiws** [comment]
If I post your code onto the docs playground, it works as expected.
Are you able to create a minimal reproduction?

**Comment by ikkysleepy** [comment]
This has to do with the version of bootstrap. It needs a specific version to work well.

**Comment by JonMagon** [comment]
> This has to do with the version of bootstrap. It needs a specific version to work well.

I have the same issue, could you tell which _specific version_ is needed?

**Comment by Hiws** [comment]
> > This has to do with the version of bootstrap. It needs a specific version to work well.
> 
> I have the same issue, could you tell which _specific version_ is needed?

If you're having issues.
I'm just gonna guess that you have Bootstrap 5 installed instead of Bootstrap 4.
