### ISSUE TITLE
HTML5 Microdata API support

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#624]
As I could not find any references yet, are there any plans to support the [HTML5 Microdata API](http://www.w3.org/TR/microdata/)? It would be nice if we could say something like `<b-breadcrump :items="items" microdata/>` to add all relevant itemprop's etc. 

One possible complication could be that html markup should be different in some cases. E.g. if you look at the [ListItem](https://schema.org/ListItem#itemlist-1) example you would at least need an extra `<span>` within the `<a>`. So if you want to support this maybe it would be better to automatically generate an `json-ld` object, but this could introduce a slight overhead because ids/urls need to be repeated.

**Comment by tmorehouse** [comment]
IF you use the attribute variant of microdata, you can provide those attributes directly on the component, as the attributes would appear on the root element rendered by the components, such as:
- itemscope 
- itemtype="http://schema.org/Person"
- itemprop="name"

etc.

**Comment by pimlie** [comment]
Unfortunately that is only a partial solution, the full example for a breadcrump looks as follow:
```html
<ol itemscope itemtype="http://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem">
    <a itemprop="item" href="https://example.com/dresses">
    <span itemprop="name">Dresses</span></a>
    <meta itemprop="position" content="1" />
  </li>
  <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem">
    <a itemprop="item" href="https://example.com/dresses/real">
    <span itemprop="name">Real Dresses</span></a>
    <meta itemprop="position" content="2" />
  </li>
</ol>
```
So all the items within the breadcrump should also have the correct itemprop's and it seems you can't access those at the moment.

For a full overview, the corresponding `json-ld` looks as follows:
```html
<script type="application/ld+json">
{
 "@context": "http://schema.org",
 "@type": "BreadcrumbList",
 "itemListElement":
 [
  {
   "@type": "ListItem",
   "position": 1,
   "item":
   {
    "@id": "https://example.com/dresses",
    "name": "Dresses"
    }
  },
  {
   "@type": "ListItem",
  "position": 2,
  "item":
   {
     "@id": "https://example.com/dresses/real",
     "name": "Real Dresses"
   }
  }
 ]
}
</script>
```

**Comment by tmorehouse** [comment]
Ah,  you need to be able to add microdata to the inner elements of a component.

I think the only current solution would be to generate HTML markup directly for your breadcrumbs.

**Comment by tmorehouse** [comment]
Breadcrumbs, in v1.0.0.beta.5 of bootstrap now support building your own breadcrumb inner elements (using new vue functional sub-components, so you could build your own breadcrumb using these components and place your microdata there.
