### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by hussainfrotan** [bootstrap-vue/bootstrap-vue#6240]
Although there is no RTL support for bootstrap itself yet, but it is extremely appreciated if you add RTL support to bootstrap-vue.
I have been waiting for this from months ago and have no choice but to go for other vue frameworks like vuetify if this feature is not added.

**Comment by Hiws** [comment]
Bootstrap 5 is adding RTL support, so it doesn't make sense for us to support it separately.

Once BootstrapVue switches from Bootstrap 4 to 5, we should be adding in RTL support as well, by utilizing the Bootstrap implementation.
