### ISSUE TITLE
Timepicker should have the possibility to provide input fields

### ISSUE THREAD

**Issue by simonfunk** [bootstrap-vue/bootstrap-vue#6245]
Hi

Actually, it is only possible through clicking on the errors to input the time.
Regarding accessibility, it would be way more better to have there input fields.

That would be great to have that as an option.

**Comment by jackmu95** [comment]
Closed in favor of #6188.

**Comment by simonfunk** [comment]
Why do you close this? This is NOT the same like #6188.

**Comment by jackmu95** [comment]
But it is what I mean in my comment: https://github.com/bootstrap-vue/bootstrap-vue/issues/6188#issuecomment-744349070

Or isn't it?

**Comment by simonfunk** [comment]
Yeah it is, but then lucapu88 answered with:"No. I want to be able to write the time instead of clicking on the arrow until I reach the desired time ... it would be more convenient to write an hour". So the open issue doesn't care about my problem now, i cares about the input field on button-only mode.
