### ISSUE TITLE
Modal Activator Slot

### ISSUE THREAD

**Issue by lgullestrup** [bootstrap-vue/bootstrap-vue#6253]
### Is your feature request related to a problem? Please describe...

Modals can't currently be self sufficient. They always require external trigger to open, or interact with, while this isn't a breaking problem, it can lead to difficult to read code.
This is a feature inspired by Vuetifiy's 'dialog' component.

### Describe the solution you'd like

Add an activator slot to the modal. The slot would have a listener passed through to it which can be bound to the element (typically a button) within the activator slot. 
ie: 
```
<template v-slot:activator="{on}">
    <b-btn v-on="on">Open Modal</b-btn>
</template>
```

The activator would be rendered where ever the modal has been defined in the template.

### Describe alternatives you've considered

Wrote a wrapper component, which takes and renders an activator slot, and also renders a BModal, and passes the slots, properties and listeners into the modal component. This add an extra layer in the virtual dom, but gets the intended results. 

Other solutions include wrapping the component in a div and binding a button outside the modal.
ie:
```
<div>
    <b-modal v-model="visible"></b-modal>
    <b-btn @click="this.visible = !this.visible">Open Modal<b-btn>
</div>
```

### Additional context

Ultimately, this would be a QOL feature, that would allow modals to be an independent component.

**Comment by DM2489** [comment]
One thing to consider if this is implemented is how this will efficiently use the same component for multiple 'activators' (imagine having a sign-up button in more than one place on the page that opens a registration modal.

You would want to re-use the single component instance and not be creating seperate ones for each button.

**Comment by lgullestrup** [comment]
@DM2489 This feature wouldn't stop you doing that. the activator slot would be as optional. If its used, then it is rendered.

This doesn't stop you from handling the visibility of same modal through events. or through using the v-model binding.
