### ISSUE TITLE
On modal open => execute function

### ISSUE THREAD

**Issue by CrixuAMG** [bootstrap-vue/bootstrap-vue#626]
Is there any simple way of achieving this?
Basically, I want to get data from an api whenever the modal is opened (not just the first time).
I did see that it emits events, but in my opinion `atOpen: getData` or something like that would improve functionality.
Same thing would go for closing the modal.

**Comment by mosinve** [comment]
Why you don't like events? Modal's event behavior allow to make your use case.

**Comment by mosinve** [comment]
`<modal @shown=getData>`

**Comment by alexsasharegan** [comment]
Are you saying you would rather use a prop that specifies a callback than attach a listener callback?

You can get your desired functionality like so:
```html
<b-modal
  @shown="getData"
  @hidden="onHidden"
>
</b-modal>
```

**Comment by CrixuAMG** [comment]
I'm new to Vue, I have to admit. I'm more used to PHP, where you would just attach a function callback.
I was looking for a simple way to attach functionality to opening/closing a modal, so I consider this issue closed. Thanks for the help guys!

**Comment by mosinve** [comment]
Here's the same function callback attach...seem nothing hard to me
