### ISSUE TITLE
Stacked table in modal window

### ISSUE THREAD

**Issue by ddzobov** [bootstrap-vue/bootstrap-vue#6261]
### Describe the bug

Table with stacked attribute overflows modal window without scrolling

### Steps to reproduce the bug

1. Create b-modal window with size="xl"
2. Create inside modal body b-table with stacked="md"
3. Create long row, which overflows modal body
4. See that b-table have no horizontal scrolling

### Expected behavior

Horizontal scrolling like without stacked attribute

### Versions

**Libraries:**

- BootstrapVue: 2.21.1
- Vue: 2.6.12

**Environment:**

- Device: Macbook Pro 15" 2018
- OS: macOS Big Sur 11.1
- Browser: Safari
- Version: 14.0.2

**Example:**
[CodeSandBox](https://codesandbox.io/s/flamboyant-chebyshev-vjhng?file=/App.vue)

**Comment by jackmu95** [comment]
@ddzobov Can you please create minimal reproduction of the issue on CodeSandbox or CodePen.

**Comment by ddzobov** [comment]
> @ddzobov Can you please create minimal reproduction of the issue on CodeSandbox or CodePen.

Added to description

**Comment by jackmu95** [comment]
Currently it is not possible to use the `responsive` and `stacked` props together.
When the `stacked` prop is set, the `responsive` wrapper isn't applied.

I need to look a bit further into wether we could just allow both props to work together.

In the meantime you should be able to work around the issue by just adding the `<div class="table-responsive">...</div>` wrapper yourself when using the `stacked` prop.
When you have any issues doing so, let me know.

**Comment by ddzobov** [comment]
Workaround works for me, thank you. Will wait for fix in next versions.
