### ISSUE TITLE
How to achieve loading effect without clearing data?

### ISSUE THREAD

**Issue by wenfangdu** [bootstrap-vue/bootstrap-vue#6267]
Currently, when loading data, previous data will be cleared, causes container height shrinking, is there a way to achieve loading effect without clearing previous data, so that the container size stays the same?
![bootstrap-vue-table](https://user-images.githubusercontent.com/28700378/103275159-7e096d80-49fe-11eb-9ed6-1251b24d941a.gif)

**Comment by jackmu95** [comment]
This is currently not possible.

We could think about showing the busy indicator as an overlay over the content to prevent the height jumps.

**Comment by wenfangdu** [comment]
@jackmu95 Could https://github.com/bootstrap-vue/bootstrap-vue/discussions/6242 also be considered a feature to be added?

**Comment by jackmu95** [comment]
@wenfangdu Yeah. I accidentally converted it to a discussion to soon.
Could you please close the discussion and open a new issue about it.

I have to further look into wether this is an issue with the current implementation or a new feature.

**Comment by wenfangdu** [comment]
@jackmu95 Didn't find the entry to close it, I opened here https://github.com/bootstrap-vue/bootstrap-vue/issues/6268.

**Comment by jackmu95** [comment]
@wenfangdu Thanks, I've deleted it.

**Comment by ddzobov** [comment]
> This is currently not possible.
> 
> We could think about showing the busy indicator as an overlay over the content to prevent the height jumps.

Any updates there?
