### ISSUE TITLE
How to achieve sticky thead-top

### ISSUE THREAD

**Issue by wenfangdu** [bootstrap-vue/bootstrap-vue#6268]
Currently I can only do sticky header, how to make the `thead-top` slot sticky as well?
![bootstrap-vue-table](https://user-images.githubusercontent.com/28700378/103322979-9cfa1500-4a7b-11eb-85c3-a3516d8024de.gif)

**Comment by DM2489** [comment]
You can't apply `sticky` to the `thead-top` slot because it is a `<tr>` and this is not supported by most web browsers.

Instead, you will need to apply `position: sticky;` to each of the columns within the row.

**Comment by wenfangdu** [comment]
@DM2489 Thanks, with your suggestion, I achieved sticky `thead-top`. Here's the working code, where `.v-th` is my custom class for `th` in `thead-top`.
```html
<style lang="scss">
.data-transfer-status-table
  .b-table-sticky-header
  > .table.b-table
  > thead
  > tr
  > th:not(.v-th) {
  top: 32px;
}
</style>
```
![bootstrap-vue-table](https://user-images.githubusercontent.com/28700378/103324580-1d704400-4a83-11eb-894b-9cd1015a629a.gif)
