### ISSUE TITLE
b-dropdown-header is producing accessibility error in the AXE browser plugin

### ISSUE THREAD

**Issue by sudo-may** [bootstrap-vue/bootstrap-vue#6273]
### Describe the bug

In the [dropdown component](https://bootstrap-vue.org/docs/components/dropdown) when using ``b-dropdown-header`` the ``role`` attribute for that header is producing accessibility error in the AXE browser plugin.

Here is a snapshot of AXE plugin when running it against the code found in https://codesandbox.io/s/wizardly-proskuriakova-1qprq?file=/src/components/VueBComponent.vue

![image](https://user-images.githubusercontent.com/51749745/103365533-4813ca00-4a8e-11eb-8e10-3ea645e9c342.png)

My best understanding is that AXE suggests that the ``role`` is redundant to the implicit meaning of the ``header`` tag. Perhaps a solution could be to simply remove the ``role`` element from the ``header`` tag?

### Steps to reproduce the bug

1. Install [AXE Browser plugin](https://www.deque.com/axe/browser-extensions); supports FF, Chrome and Edge
2. Navigate to code [CodeSandbox example](https://codesandbox.io/s/wizardly-proskuriakova-1qprq?file=/src/components/VueBComponent.vue) taken from this of Headers and accessibility section of [Bootstrap-vue dropdown component](https://bootstrap-vue.org/docs/components/dropdown)
3. Click on "Open in a new Window" Icon 
![image](https://user-images.githubusercontent.com/51749745/103020005-b8ae6a00-4515-11eb-88b7-fad663931366.png) on top right
4. Open Dev tools, click on AXE tab and Analyze
5. Look for ``ARIA role must be appropriate for the element`` accessibility error

### Expected behavior

Do not generate  ``role`` element from the ``header`` tag

### Versions

**Libraries:**

- BootstrapVue: 2.21.1
- Bootstrap: 4.5.3
- Vue: 2.6.11

**Environment:**
- Browser: Chrome, FF

### Demo link

https://codesandbox.io/s/wizardly-proskuriakova-1qprq?file=/src/components/VueBComponent.vue

**Comment by jackmu95** [comment]
Closes by #6274.
