### ISSUE TITLE
check input slot in table doesn't work properly

### ISSUE THREAD

**Issue by morteza-mortezai** [bootstrap-vue/bootstrap-vue#6279]
### Describe the bug

i am using <b-table> component and sloted a checkBox in a column , and i used v-model to for checkbox to connect it to data property , and check box doesn't work correctly 
### Steps to reproduce the bug

1.use <b-table> component
2. connect table to data<b-table :items="items" :fields="fields" >
3. slot a check box in on column of it
4. run your project
4. check/uncheck checkbox input
5. see input is checked but data is false

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#
![Untitled](https://user-images.githubusercontent.com/75200938/103461065-8c25f980-4d30-11eb-8010-b58fa5736382.jpg)

https://user-images.githubusercontent.com/75200938/103461114-11111300-4d31-11eb-83bf-e2f2f1d9a817.mp4

**Comment by Hiws** [comment]
Vue is trying to re-use the DOM, since you haven't unique provided a key.
You need to use the `primary-key` prop, and provide it the name of a field with a unique value per row, this should solve the issue.

https://codepen.io/Hiws/pen/NWRYdxr
