### ISSUE TITLE
[form-file] "Choose File" does not trigger a file selector

### ISSUE THREAD

**Issue by yhosun** [bootstrap-vue/bootstrap-vue#628]
version: 1.7.1

https://jsfiddle.net/pi0/3dw5djb1/?utm_source=website&utm_medium=embed&utm_campaign=3dw5djb1

In the JSFiddle, clicking "Choose File" button does not trigger a file selector any more while it does when the input "No File Chosen" is clicked.

**Comment by tmorehouse** [comment]
This should be fixed in the master, as the class `form-control` was inadvertently placed on the custom-file input, which shifted the position of the opaque native file input.

Currently, Clicking the leftmost side of the custom file-input still works for opening the file browser.

**Comment by tmorehouse** [comment]
@yhosun 

Release v0.18.0 is now available and this issue *should* be fixed.

**Comment by yhosun** [comment]
@tmorehouse Thanks for looking into it quickly!  There is still a remaining issue when the width of `b-form-file` is set in CSS and I logged a new issue #644.
