### ISSUE TITLE
avoid adding css class(es) which already exist to the generated html elements

### ISSUE THREAD

**Issue by magical-l** [bootstrap-vue/bootstrap-vue#6284]
### Is your feature request related to a problem? Please describe...

if there are some classes already in the tag, for example '&lt;b-card class="card"&gt;&lt;/b-card&gt;', then when we look at the HTML element in the final page, the &lt;div&gt; maybe with two 'card' in the class prop, as '&lt;div class="card card"&gt;&lt;/div&gt;'.

### Describe the solution you'd like

I think we could avoid adding those duplicate classes to the HTML elements.

### Describe alternatives you've considered

what about check if there is already one when going to add a class to the HTML elements?

**Comment by jackmu95** [comment]
@magical-l Can you please provide a live example of what you exactly mean on CodeSandbox or CodePen?

**Comment by magical-l** [comment]
@jackmu95 sorry, my mistake, forgot to escape the HTML when copied them, so that the codes were disappeared.
now I updated the comment and fixed the codes in it. is it enough?

**Comment by magical-l** [comment]
@jackmu95 
for example, we have the code like this:
```
<main>
<b-card title="A card" class="card"></b-card>
</main>
<script>
  new Vue({data:{},el:'main'});
</script>
```

then when we check the code generated by BootstrapVue in the final HTML, that would be like this:
```
<div class="card card">
    <div class="card-body">
        <h4 class="card-title">A card</h4><!---->
    </div>
</div>
```

we will see there are two 'card' in the class attribute. that's what I mean.

**Comment by jackmu95** [comment]
@magical-l All BootstrapVue components apply the required Bootstrap classes by themselves.
We don't check the user supplied ones if they are already applied and I don't see the overhead is worth doing it in the future.

For your example, just remove the `card` class and you are fine :)
