### ISSUE TITLE
[Question] How to achieve tree component?

### ISSUE THREAD

**Issue by wenfangdu** [bootstrap-vue/bootstrap-vue#6289]
Like [this one](https://element.eleme.cn/#/en-US/component/tree):
![image](https://user-images.githubusercontent.com/28700378/103745666-d9f57700-503a-11eb-8dcb-b109b54d08d2.png)

**Comment by andrei-gheorghiu** [comment]
Bootstrap CSS does not include a tree view widget, which means such a component is outside BootstrapVue's scope. However, using a combination of form elements, list items and utility spacer classes, one could be created without much effort.

You might find [these examples](https://jonmiles.github.io/bootstrap-treeview/) helpful in achieving it.
