### ISSUE TITLE
pagination button will hide the drop-down box

### ISSUE THREAD

**Issue by thelostword** [bootstrap-vue/bootstrap-vue#6292]
```
<b-nav-item-dropdown id="dropdown-1" text="Projects" ref="dropdown" hover left variant="light">
            <b-dropdown-item class="px-2">list</b-dropdown-item>
            <div class="pagination mt-2">
                <b-pagination
                    v-if="total > limit"
                    v-model="currentPage"
                    :total-rows="total"
                    :per-page="limit"
                    aria-controls="my-table"
                ></b-pagination>
                <span role="menuitem" aria-label="Go to last page" aria-controls="my-table" aria-disabled="true" class="page-link">will hold dropdown</span>
            </div>
        </b-nav-item-dropdown>
```

**Comment by Hiws** [comment]
I'm not quite sure I see what the issue is here.
Could you describe it in a bit more depth?

**Comment by thelostword** [comment]
<img width="532" alt="Snipaste_2021-01-07_15-01-02" src="https://user-images.githubusercontent.com/41263837/103862751-a0844080-50fa-11eb-99ef-53cd64bcfcad.png">

**Comment by 959666690** [comment]
There is a paging bar in the drop-down menu. Clicking the paging button will hide the drop-down menu, which is not what I want @Hiws

**Comment by Hiws** [comment]
From what I can see it's because `<b-pagination>` is doing some stuff with the focus.
But looks like adding `@click.stop` to the `<div class="pagination">` element fixes the issue.

**Comment by thelostword** [comment]
bug demo for drop-down
[https://github.com/thelostword/pagination-bug-demo](url)
@Hiws

**Comment by jf908** [comment]
Encountered this issue today. Adding `@click.native.stop` as a workaround to `<b-pagination>` did fix the problem.
