### ISSUE TITLE
(Question) How can i use modal?

### ISSUE THREAD

**Issue by qwexvf** [bootstrap-vue/bootstrap-vue#63]
Hi, How can i use modal?

**Comment by ethanclevenger91** [comment]
It's not completely implemented yet, there seems to be a small bug. I was
hoping to put in a PR sooner than later

**Comment by jgog** [comment]
I got it to work using the following code:

```vue
<template>
<div id="app">
        <b-button @click="toggleModal">
            Click Me!
        </b-button>
    <b-modal ref="modal">
        <div slot="modal-body" class="modal-body">...</div>
    </b-modal>
</div>
</template>

<script>
export default {
    mounted() {
        console.log('welcome!')
    },
    methods: {
        toggleModal() {
            this.$refs.modal.show();
        }
    }
}
</script>
```

**Comment by qwexvf** [comment]
@jgog @ethanclevenger91 Thanks a lot!
this project is awesome <3

**Comment by riker09** [comment]
@ethanclevenger91 Hello Ethan, do you have any news on the modal implementation? I'm currently fiddling around a bit with Vue + Bootstrap and would like to use the Modal component. What I noticed, is that the CSS class "show" is not set. Instead, a CSS class "in" is set. Hope this helps.

**Comment by riker09** [comment]
@ethanclevenger91 I've provided a PR #81 to address this issue. Please have a look.

**Comment by mosinve** [comment]
Got worked by changing modal's created method to:
```
 created() {
        const hub = this.$root;
        hub.$on('show::modal', id => id === this.id && this.show()).bind(this);
        hub.$on('hide::modal', id => id === this.id && this.hide()).bing(this);
    },
```
and the emitter method of opener:
```
    openObjects() {
                this.$root.$emit('show::modal', 'modaldlg');
            }
```

**Comment by riker09** [comment]
@mosinve Looks like a typo in the second bind line: 
<pre>
...hide()).bin<b>g</b>(this)
</pre>

probably should be

<pre>
...hide()).bin<b>d</b>(this)
</pre>

**Comment by pi0** [comment]
Thanks @riker09 for mentioning that. I'm working on modal so it may be my mistake. I will be all better soon :)

**Comment by mosinve** [comment]
Yep, thanks @riker09 - it was my typo. In working app all correct and works

**Comment by mosinve** [comment]
Seems, that impossible to use modal in "Option 2: import individual components". 
> [Vue warn]: Unknown custom element: <b-btn> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
> (found in <BModal> at D:\Dev\reestrius_spa\node_modules\bootstrap-vue\components\modal.vue)
