### ISSUE TITLE
Right-padding added to body when modals are closed

### ISSUE THREAD

**Issue by ebrawer** [bootstrap-vue/bootstrap-vue#6303]
### Describe the bug

When a modal is closed/hidden, a CSS style of `padding-right: 15px;` is permanently added to body.

### Steps to reproduce the bug

1. Open a modal
2. Close it
3. Body will have right padding

### Expected behavior

This padding should not be added.

### Versions

**Libraries:**

- BootstrapVue: 2.17.0
- Bootstrap: 4.5.2
- Vue: 2.6.12

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Chrome
- Version: 87

**Comment by jackmu95** [comment]
@ebrawer Can you please create a minimal reproduction of the issue on CodeSandbox or CodePen.

**Comment by Hiws** [comment]
This was a bug in a previous version, that has been fixed.
Please update BootstrapVue and see if the issue persists.

**Comment by bartversluijs** [comment]
I can confirm this behaviour with v2.17.0. This only happened when the modal opened when the page was scrollable.
Updated to v2.21.1 and the issue disappeared. So this issue can probably be closed.

**Comment by erdalAlacali** [comment]
We are using the 3.2.38 Version, and having still this issue, is there any knowing new issue case for that? Thanks
