### ISSUE TITLE
TypeError during importing Bootstrap-vue component to Jest test

### ISSUE THREAD

**Issue by WooCash9311** [bootstrap-vue/bootstrap-vue#6304]
### Describe the bug

Hey, I've wrapped `BFormRadioGroup` and `BFormCheckbox` with my custom components. 

e.g. `RadioInput.vue`:
```
<template>
  <abc
    :label="label"
    data-input-type="radio"
  >
    <b-form-radio-group
      :id="id"
      v-model="currentValue"
      :name="id"
      :options="convertSelectOptions"
      :stacked="convertDisplayStyle"
      :disabled="disabled"
      class="radio-input"
      @input="updateInput()"
      @click="propagateOnClick()"
    ></b-form-radio-group>
  </abc>
</template>
```
and I want to write some unit tests in Jest (with typescript).

My simple Jest test to check if my custom component has `BFormRadioGroup` in template:
```
import { BFormRadioGroup } from 'bootstrap-vue';
[...]
it('is wrapped by BFormRadioGroup', () => {
    expect(wrapper.findComponent(BFormRadioGroup).exists())
      .toBe(true);
  });
```

After run test I'm getting error:
```
TypeError: Vue__default.default.extend is not a function

      14 | import { BFormRadioGroup } from 'bootstrap-vue';
      15 | ^

      at Object.extend (node_modules/bootstrap-vue/dist/bootstrap-vue.common.js:1998:50)
      at Object.<anonymous> (tests/unit/modules/shared/components/form/RadioInput.spec.ts:14:1)
```

I think there is a problem with importing anything from `bootstrap-vue`, because it doesn't even run the test.

Maybe do you have some idea what could be wrong? :)

Greetings,
Lucas

### Versions

**Libraries:**

- BootstrapVue: 2.21.0
- Bootstrap: 4.5.3
- Vue: 2.6.12
- Jest: 23.0.0

**Environment:**

- Device: Linux
- OS: Mint

**Comment by Wittmaxi** [comment]
The same happened to me/us. Downgrading Bootstrap to ` "bootstrap-vue": "2.17.3",` as a quick fix did the trick!

**Comment by WooCash9311** [comment]
@Wittmaxi nice, thanks for answer! :)

@Hiws @jackmu95 I don't want to downgrade `bootstrap-vue` to `2.17.3` version, maybe can you take a look with this bug/issue in next release? :)

**Comment by jackmu95** [comment]
@WooCash9311 @Wittmaxi Can you please create a minimal reproduction of the issue on CodeSandbox.
Without that it is really hard for me to reproduce the issue.

**Comment by andrei-gheorghiu** [comment]
I had this issue recently and I had a hard time repro-ing it in codesandbox. 
If you fail to repro it, please share the contents of your: 
- `package.json`
- `babel.config.js`
- `jest.config.js`
- `tsconfig.ts`
