### ISSUE TITLE
Submit event not work on b-form (multiple inputs)

### ISSUE THREAD

**Issue by meyt** [bootstrap-vue/bootstrap-vue#631]
Referenced to issue #588, in my case form submit event works if you have not form input more than one!
this sample works fine:
https://jsfiddle.net/j08b7c4o/23/

<b-form v-on:submit.prevent="alert('SUBMIT')">
    <b-form-input v-model="text" type="text"></b-form-input>
</b-form>
but this is not:
https://jsfiddle.net/j08b7c4o/22/

<b-form v-on:submit.prevent="alert('SUBMIT')">
    <b-form-input v-model="text" type="text"></b-form-input>
    <b-form-input v-model="text2" type="text"></b-form-input>
</b-form>

**Comment by tmorehouse** [comment]
That is a browser dependant issue.  Most browsers will submit a form when you press enter on the *only* text input in the form. If a form has multiple text inputs, pressing enter on any input will *not* submit the form.

See this example with **native** browser forms: https://jsfiddle.net/bootstrapvue/j08b7c4o/26/

**Comment by stojy** [comment]
is there a (simple) workaround for this browser specific behaviour?
