### ISSUE TITLE
Clickable Progress bar

### ISSUE THREAD

**Issue by fdabek1** [bootstrap-vue/bootstrap-vue#6313]
### Is your feature request related to a problem? Please describe...

I am trying to make the multiple bars of my progress bars clickable, but currently that function does not work.

### Describe the solution you'd like

Pass the click events up.

### Describe alternatives you've considered

Manually specifying the <div> elements rather than using BootstrapVue components.

### Additional context

Currently trying something like this:

```javascript
<template>
    <b-progress class="mt-2" :max="max" height="2rem">
        <b-progress-bar :value="value * (2.5 / 10)" variant="success" @click="clicked"></b-progress-bar>
        <b-progress-bar :value="value * (2.5 / 10)" variant="warning"></b-progress-bar>
        <b-progress-bar :value="value * (1.5 / 10)" variant="danger"></b-progress-bar>
    </b-progress>
</template>

<script>
export default {
    name: "ex",
    data() {
        return {
            value: 45,
            max: 100
        }
    },
    methods: {
        clicked() {
            console.log('clicked');
        }
    }
}
</script>
```

**Comment by Hiws** [comment]
You can use the `native` modifier on your click event, to get it to trigger.

```html
<b-progress-bar :value="value * (2.5 / 10)" variant="success" @click.native="clicked"></b-progress-bar>
```
