### ISSUE TITLE
Parts of the bootstrap vue component render as undefined

### ISSUE THREAD

**Issue by arberpolis** [bootstrap-vue/bootstrap-vue#6318]
### Describe the bug
Part of the html inside the bootstrap vue component renders as undefined
![image](https://user-images.githubusercontent.com/1976636/104706594-9aeeb200-571b-11eb-8c06-faf647888270.png)
![image](https://user-images.githubusercontent.com/1976636/104706650-acd05500-571b-11eb-9d8c-40c949b2ced3.png)

### Steps to reproduce the bug
Register bootstrap vue as a vue plugin object in the main script of the application.
Create a component with b-jumbotron.
Add an interpolated variable inside a p tag

### Expected behavior
The component should have rendered the content of the interpolated variable (string)

### Versions

**Libraries:**

- BootstrapVue: 2.20.1
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Lenovo
- OS: Windows 10 20H2 (Vue server and code running on WSL Ubuntu 2004)
- Browser: Chrome
- Version: 87.0.4280.141

**Comment by jackmu95** [comment]
@arberpolis Can you please create a minimal reproduction of the issue on CodeSandbox or CodePen.
