### ISSUE TITLE
toggle pressed only one button in a group buttons

### ISSUE THREAD

**Issue by lucapu88** [bootstrap-vue/bootstrap-vue#6319]
https://bootstrap-vue.org/docs/components/button#pressed-state-and-toggling

I have a group of buttons and I would like to toggle but pressed true must only be on one... that is, if I click on a button, only that button must be highlighted, while the others do not, so when clicked on the button it becomes `pressed = true `and if there is another `pressed = true `it becomes false

**Comment by Hiws** [comment]
Looks like you've gotten an answer on StackOverflow.
So I'm going to close this issue.

<https://stackoverflow.com/a/65739430/8397974>

```html
<b-button
   v-for="(btn, idx) in buttons"
   :key="idx"
   :pressed.sync="btn.state"
   variant="primary"
   @click="onPress(idx)"
></b-button>
```

```js
methods: {
  onPress(i) {
    this.buttons.forEach((b, index) => b.state = i === index)
  }
}
```
