### ISSUE TITLE
[modal] option to set a width

### ISSUE THREAD

**Issue by yhosun** [bootstrap-vue/bootstrap-vue#632]
This is an enhancement request.

There is `size` option (i.e. `sm`, `md`) for the modal component, but it would be great if there is an option to set the exact width / max-width.  For example,  `<b-modal :width=400></b-modal>` so that the modal width would not be no more than 400px.

Thank you.

**Comment by tmorehouse** [comment]
Bootstrap-vue tries to follow the Bootstrap V4 standard CSS, and hence we only offer the standard Bootstrap modal sizes.

You can, however, place a class on `<b-modal>`, which will get applied to modal's root element (`div.modal`), and then target the `.modal-dialog` to set the width

**HTML:**
```html
<b-modal class="my-modal" ...>
   Modal Content
</b-modal>
```

**CSS:**
```css
div.modal.my-modal .modal-dialog {
  width: 400px; !important;
}
```

**Comment by tmorehouse** [comment]
You could also make your own custom sizes in CSS:

**HTML:**
```html
<b-modal size="400" ...>
   Modal Content
</b-modal>
```

**CSS:**
```css
div.modal .modal-dialog.modal-400 {
  width: 400px; !important;
}
```

note that `modal-` gets tacked onto the front of the size you pass.

**Comment by MonkeyPengc** [comment]
This doesn't work for me, what's the div.modal in CSS?

**Comment by priteshkadiwala** [comment]
This did not work for me. Could you please suggest other ways?

**Comment by vacolane** [comment]
I am sorry but it doesnt work for me........ can you help me?

**html:**
    ```
<b-modal class="myModalProjet" ref="modalProjet" hide-footer :title="rowProjet.libelle">
      <consulter-projet :value="rowProjet"></consulter-projet>
    </b-modal>
```
**css**
```
div.modal.myModalProjet .modal-dialog {
  width: 90% !important;
}
```

**Comment by Ota-kun** [comment]
For me, I tried almost everything there possibly is (many many hours..) to get a custom width working in b-modal element (not max-width). The correct solution for me was that I added text "has-modal-card" inside <b-modal> like this:

`<b-modal :active.sync="isModalActive" :canCancel="['escape']" class="modal-active" has-modal-card>`
 
...and used "style="width: auto" inside the div element that had modal-card class in it like this:

`<div class="modal-card is-large" style="width: auto">`

Without the "has-modal-card" it just left the width of the modal same with horizontal scroll in it. Before my correct solution I figured that I could override CSS class .modal-content with the width I want but it affected every modal that I had and I didn't want that. I tried making my own custom classes, etc. Basically every way that you can use when overriding 3rd party libraries with one exception.

**Comment by tmorehouse** [comment]
Create a new modal-[size] class like `modal-huge`, and then create custom CSS to set width (note Bootstrap V4 uses max-width on all modal sizes based on media queries, so you may need to target a certain screen with)

```css
.modal .modal-huge {
  max-width: 2000px;
}
```

and use that size on b-modal:

```html
<b-modal size="huge" ... >
</b-modal>
```

The `size` prop just adds a class on the modal-dialog element `modal-xxx` where `xxx` is the text passed to the `size` prop (i.e. `huge` is converted to `modal-huge`).  So modal isn't limiting you to specific sizes, it is only limited by what CSS classes exist.

**Comment by YuryKorovko** [comment]
@tmorehouse related to your above answer I'd like to ask should I use **modal-class** or just **class** of b-modal component ? Cause any of your answers don't work for me :(

**Comment by pablocattaneo** [comment]
I solved the problem using @tmorehouse appoach, to use this approach you have to notice that the css have to be write a css in a global css, and that is the cons , but it works. It would be great if you can add the feature that @YuryKorovko asks, I think that it is a more elegant a reusble way to solve the problem.

**Comment by YuryKorovko** [comment]
Related to the @tmorehouse answer with suggestion to create your own size (huge e.g)
You should place the following CSS **globally** :
@media (min-width: 992px) {
  .modal .modal-huge {
    max-width: 90% !important;
    width: 90% !important;;
  }
}
Thanks @pablocattaneo as well , only after I placed my Css globally it started to work.

**Comment by isaiahfisher** [comment]
Sorry to resurrect a dead issue, but I am looking to accomplish this same type of change but with height. My goal is to make the modal take about 60% of the screen centered. The problem I am running into is that I cannot seem to get the modal height to react to my changes. I tried implementing my own .modal-huge class but all that changed was the width. Is it possible to adjust the height for this element?
