### ISSUE TITLE
b-form-datepicker: cannot set value to null

### ISSUE THREAD

**Issue by mmillican** [bootstrap-vue/bootstrap-vue#6322]
### Describe the bug

Similar to #5114, If a date has already been selected (or provided from an existing value in the model), you cannot set the value to `null`. 

I have also tried setting the reset value via `reset-value="null"` and `:reset-value="null"`.

### Steps to reproduce the bug

1. Set the value of the model to a valid date, via the UI or an initial value
2. Try to clear the value using the `reset` method
3. Check value

### Expected behavior

Should set to `null` or have an option to set the 'empty' value

### Versions

**Libraries:**

- BootstrapVue: ^2.15.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- Device: PC
- OS:  Windows 10
- Browser: Firefox

**Comment by jackmu95** [comment]
@mmillican I've looked a bit into this and the current behavior is correct.
The [`v-model` section in the docs](https://bootstrap-vue.org/docs/components/form-datepicker#v-model-return-value) describes the behavior quite detailed.

You can check if the value is empty by checking for an empty string and normalize that to `null` if you need to yourself.
