### ISSUE TITLE
[b-input-group] Size attribute is never used

### ISSUE THREAD

**Issue by hydraheim** [bootstrap-vue/bootstrap-vue#633]
JSfiddle: https://jsfiddle.net/8av0hoo7/

In short: The attribute size is never utilized in the rendered output, as can be seen when inspecting the jsfiddle output.

Docs: https://bootstrap-vue.js.org/docs/components/input-group

**Comment by tmorehouse** [comment]
Size refers to the bootstrap size (`lg,) `sm`), not the input character limit. (number).

https://jsfiddle.net/bootstrapvue/8av0hoo7/1/

https://github.com/bootstrap-vue/bootstrap-vue/tree/master/docs/components/input-group
