### ISSUE TITLE
[suggestion] Move the code example to the top of each documentation page

### ISSUE THREAD

**Issue by hydraheim** [bootstrap-vue/bootstrap-vue#634]
Some doc pages have a lot of text ([button doc is one example](https://bootstrap-vue.js.org/docs/components/button) before you get to the actual example code. 

To scroll past walls of text to get to the actual code is "tedious" for those who want to get started quickly or use the docs as regular reference.  A suggestion is to move the example code to the very top and the details below. Below is a crude example of the proposed layout.

![t1cnkat](https://user-images.githubusercontent.com/29726093/27822440-e5da3fa2-60a5-11e7-9ade-6b9029599283.png)

**Comment by tmorehouse** [comment]
Check out the latest docs available at https://github.com/bootstrap-vue/bootstrap-vue/tree/master/docs/components which will be available in next release v0.18.0

Components will have "live" examples at the top, and throughout the document.

**Comment by tmorehouse** [comment]
@hydraheim 

Latest release v0.18.0 is now available. Check out the new docs website.
