### ISSUE TITLE
b-img-lazy: specifying blank-src breaks laziness

### ISSUE THREAD

**Issue by bezumkin** [bootstrap-vue/bootstrap-vue#6340]
### Describe the bug

When I specify my own placeholder for lazy image in `blank-src` parameter, image stops to be lazy.

If I remove this parameter, image works as it should, with automatically generated placeholder.

### Steps to reproduce the bug

Just put a `<b-img-lazy src="..." blank-src="..." />` outside viewport and look into dev tools.

![Screenshot 2021-01-21 at 12 11 55](https://user-images.githubusercontent.com/1257284/105282905-eef90b00-5be1-11eb-8ce5-c1607c2d8d25.png)

### Expected behavior

Image should be lazy with my own placeholder

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.12

**Environment:**

- Device: Mac
- OS: Big Sur
- Browser: Firefox
- Version: 84.0.2

### Demo link

https://codesandbox.io/s/blazing-meadow-17tys?file=/App.vue

**Comment by jackmu95** [comment]
Closes by #6302.
