### ISSUE TITLE
Prop doesn't update for components inside b-modal

### ISSUE THREAD

**Issue by Rubas22** [bootstrap-vue/bootstrap-vue#6350]
### Describe the bug
I have something like this in myComponent:
```
<b-modal>
     <childComponent  :newPropValue="propValue" >
     </childComponent>
</b-modal>
```
The propValue also comes as a prop from the father of myComponent. The problem is that if the modal is open and the propValue is updated the newPropValue in childComponent doesn't update. Once I close the modal and re-open it, the newPropValue updates.  

Why is that? What can I do to fix it?

**Comment by Hiws** [comment]
Can you provide more code, or a minimal reproduction of the issue?

Since I can't seem to reproduce the issue you're having.
<https://codepen.io/Hiws/pen/vYXwaZV>
