### ISSUE TITLE
Tables - Pagination widget does not update when filter applied to a table

### ISSUE THREAD

**Issue by mikebski** [bootstrap-vue/bootstrap-vue#6351]
### Is your feature request related to a problem? Please describe...

When I add a filter and pagination to the table the pagination does not update to reflect the filtered dataset. For example, if I have 100 items 10 per page, I have 10 pages. If I apply a text filter that limits my results to 20 items, I would expect 2 pages but still have 10 pages listed in the pagination widget.

### Describe the solution you'd like

When I add a filter to a paginated table, I would like the pagination widget to update the page count and navigation to reflect the dataset with the filter applied.

### Describe alternatives you've considered

Hide the pagination if there is a filter applied.

**Comment by Hiws** [comment]
`<b-pagination>` pages are dependent on `per-page` and `total-rows` props to calculate how many pages there should be rendered. So you need to manually update the `total-rows` prop when your table is filtered.
You can use the `@filtered` event on `<b-table>` to retrieve the amount of rows after filtering.

You can see a example of this in the complete example on the table docs.
<https://bootstrap-vue.org/docs/components/table#complete-example>
