### ISSUE TITLE
Unable to use bootstrap-vue plugin

### ISSUE THREAD

**Issue by koshaapatel** [bootstrap-vue/bootstrap-vue#6379]
### The build is getting broken when I try to use bootstrap-vue as plugin

1. main.js is as followed:
import './plugins/bootstrap-vue'
import { createApp } from 'vue'
import App from './App.vue'
createApp(App).mount('#app')

2.  bootstrap-vue.js is as followed:
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
Vue.use(BootstrapVue)

### VERSIONS:
"bootstrap": "^4.6.0",
"bootstrap-vue": "^2.21.2",
"core-js": "^3.6.5",
"vue": "^3.0.5"

### ERROR:
 WARNING  Compiled with 2 warnings                                                                                                                        12:02:20 AM
 warning  in ./src/plugins/bootstrap-vue.js

"export 'default' (imported as 'Vue') was not found in 'vue'

 warning  in ./node_modules/bootstrap-vue/esm/vue.js

"export 'default' (reexported as 'Vue') was not found in 'vue'

**Comment by Dreathorian** [comment]
jep, same here. just tried that today. did a clean install of vue cli/service, cd to project, called vue add bootstrap-vue, npm run serve, nothing is shown in the browser. same 2 warnings.

**Comment by Dreathorian** [comment]
looks like its just incompatible with vue 3. try to create a vue 2 project and add bootrstrap-vue there. it should work ;-)
