### ISSUE TITLE
[docs] "Edit this page" link broken

### ISSUE THREAD

**Issue by jimt** [bootstrap-vue/bootstrap-vue#639]
The **Edit this page** link is broken on https://bootstrap-vue.js.org/docs/setup/

**Comment by alexsasharegan** [comment]
Looks like a concatenated path gone south. Chances are the trailing slash varies based on how you get to a page. Maybe we can normalize the path with a trim slashes. Just gotta find where the logic for this is.

**Comment by tmorehouse** [comment]
This is an oddball case.  The edit this page link is based on teh URL path, and then prepends the github URL.  For SETUP.md, there is no /docs/setup/README.md (at GitHub), but rather a file called /docs/SETUP.md

Maybe the bit of code that generates the edit this page button/link needs to do a `v-if` to test if it is /docs/setup, and if so link to just /docs/SETUP.md

**Comment by tmorehouse** [comment]
PR #641 *should* fix this.
