### ISSUE TITLE
Provide type (range, toggle, etc) or click event as second param for row-selected

### ISSUE THREAD

**Issue by lucasprograms** [bootstrap-vue/bootstrap-vue#6396]
### Is your feature request related to a problem? Please describe...

I have a large table. As it scrolls down it loads more rows, and sheds those at the top. The selection of rows is tracked elsewhere, so that when the user scrolls back up and reloads the rows, the previously selected rows are still selected.

When a user scrolls down, they might "unload" a row that is selected, i.e., remove it from the table. If they make a new selection, the rows that are provided to the "row-selected" callback will not include the "unloaded" row. There is no way to tell if the selection is additive "shift/ctrl", or should remove all the "unloaded & selected" rows. 

### Describe the solution you'd like

Provide a second argument to the row-selected callback, describing either the click event, or the type of row select (shift, single, etc).

### Describe alternatives you've considered

Add a listener on row-click event, and store the last row click event in state. Look at it when processing row-select event to determine what kind of row-select it is. This works, but seems a little flaky and potentially prone to error.

**Comment by TheNewSound** [comment]
I agree with the feature request.

Note however, in the meantime, you can track keypresses yourself and use them in your event to determine a shift or ctrl click.
