### ISSUE TITLE
Shift click in range table does not always work as expected

### ISSUE THREAD

**Issue by lucasprograms** [bootstrap-vue/bootstrap-vue#6397]
### Describe the bug

Shift click row does not work as expected after de-selecting row with ctrl click.

### Steps to reproduce the bug

1. Go to row-select demo here: https://bootstrap-vue.org/docs/components/table#row-select-support
2. Change "Selection Mode" dropdown to "range"
3. Click the second row
4. Ctrl-click the first row
5. Ctrl-click the second row
6. Shift-click the bottom row

### Expected behavior
All rows are selected

### Actual behavior
Bottom row is selected

### Versions

**Libraries:**

- BootstrapVue: 2.21.2

**Environment:**

- Device: desktop computer
- OS: Ubuntu 20
- Browser: Chromium
- Version: Latest

**Comment by andrei-gheorghiu** [comment]
Correct link above is: https://bootstrap-vue.org/docs/components/table#row-select-support

**Comment by lucasprograms** [comment]
@andrei-gheorghiu thank you - updated

**Comment by dchinu97** [comment]
@jackmu95 Seems like an interesting good first issue to work on, can you please assign it to me?

**Comment by ochowei** [comment]
I have a suggestion about this issue and passed `yarn test`, but not sure it comes up to your expectations:
replace the line [234](https://github.com/bootstrap-vue/bootstrap-vue/blob/3d7f4c7075201c0efe49237503caf51f403ce587/src/components/table/helpers/mixin-selectable.js#L234) with:
```
if (selected) this.selectedLastRow = index
```

**Comment by ochowei** [comment]
I have a suggestion about this issue and passed `yarn test`, but not sure it comes up to your expectations:
replace the line [234](https://github.com/bootstrap-vue/bootstrap-vue/blob/3d7f4c7075201c0efe49237503caf51f403ce587/src/components/table/helpers/mixin-selectable.js#L234) with:
```
if (selected) this.selectedLastRow = index
```
