### ISSUE TITLE
Factor `.b-skeleton-animate-wave` `background` property to a SASS variable

### ISSUE THREAD

**Issue by JonathanGuberman** [bootstrap-vue/bootstrap-vue#6398]
### Is your feature request related to a problem? Please describe...

The default `.b-skeleton-animate-wave` `background` property doesn't look right in my custom theme, so I need to override the CSS with custom CSS.

### Describe the solution you'd like

I'd like to factor this out into a SASS variable or variables (e.g., `$b-skeleton-animate-wave-background` and/or `$b-skeleton-animate-wave-background-color`.

### Describe alternatives you've considered

It's possible to override this property, which is my workaround, but considering that `$b-skeleton-background-color` is already a variable, I think it makes sense for this to be one, too.

### Additional context

I am able and willing to make a pull request for this, but I'm not sure whether it should be a variable for the whole gradient: 
```scss
$b-skeleton-animate-wave-background: linear-gradient(90deg, transparent, hsla(0, 0%, 100%, 0.4), transparent) !default;
```
or just for the colour:
```scss
$b-skeleton-animate-wave-color: hsla(0, 0%, 100%, 0.4) !default;
```
or for both
```scss
$b-skeleton-animate-wave-color: hsla(0, 0%, 100%, 0.4) !default;
$b-skeleton-animate-wave-background: linear-gradient(90deg, transparent, $b-skeleton-animate-wave-color, transparent) !default;
```

**Comment by jackmu95** [comment]
@JonathanGuberman I would prefer to go with two variables.
Feel free to create a PR :)
