### ISSUE TITLE
type="number" doesn't seem to be supported?

### ISSUE THREAD

**Issue by samanthaming** [bootstrap-vue/bootstrap-vue#64]
It seems like input with type **number** is supported.

Looks like it's due to the following *bootstrap-vue/components/form-input.vue*?

```javascript 
props: {
            value: {
                type: String,
                default: null
            },
```

For example, here's what I have
```javascript 
<b-form-input v-model="pPrice"
      type="number"
      label="Product Price"
 />

data () {
  return {
    pPrice: 0
  }
}
```

The error message I got
![screen shot 2017-01-07 at 8 33 06 pm](https://cloud.githubusercontent.com/assets/16507205/21747334/ee0c9e86-d518-11e6-9b74-b4749879afbb.png)

**Comment by pi0** [comment]
@samanthaming Thanks. will be fixed soon

**Comment by mathlet0x** [comment]
@samanthaming you should try ;) : 

`
<b-form-input v-model="pPrice"
      type="Number"
      label="Product Price"
 />
`

**Comment by pi0** [comment]
@mathlet0x Is it safe to close this issue ?

**Comment by mathlet0x** [comment]
Sure :)

**Comment by riker09** [comment]
I think the error still exists in v0.6.0. Am I missing something? Here's my code:

```
<template>
    [...]
    <b-form-input v-model.number="user.balance" type="Number" />
    [...]
</template>

<script>
export default {
  name: 'user-edit',
  props: {
    user: {
      type: Object,
      default: function () {
        return {
          user: {
            name: 'User',
            balance: 123
          }
        }
      }
    }
  }
}
</script>
```

**Comment by riker09** [comment]
After some more time with Vue.js I think this is because the value passed to the component is actually a Number, but the input field requires a String. In my opinion the component should do the necessary casting itself.

**Comment by riker09** [comment]
@pi0 Could the formatter be used for this? It should do type safe comparision, though. Currently the formatted value is never used, when, for example the Number 5 is compared to the casted String '5'

**Comment by riker09** [comment]
Nevermind my last comment. I'm still very new to Vue.js and learning. You've set a prop constraint in the component `form-input`, that is why I'm seeing this error in the console whenever I pass a Number. :man_facepalming:

**Comment by riker09** [comment]
According to the Vue docs multiple types should be possible. I'm preparing a PR. :smiley:

**Comment by pi0** [comment]
@riker09 So fast reactions :)) Thanks mate

**Comment by riker09** [comment]
I'm sick at home, so I got a little spare time at my hands. And I'm really diggin Vue.js. Now, when I can help some Open Source projects this really makes my day. :smile:
