### ISSUE TITLE
After migration from bootstrap 4, dropdown menu dont work

### ISSUE THREAD

**Issue by narnikgamarnikus** [bootstrap-vue/bootstrap-vue#642]
I fully followed your recommendations on migration, but at the same time, the dropdown menu on mobile devices does not work.
Everything else works as it should, but the native bootstrap menu does not work.

But I do not see any errors. The listener is not assigned to the button, as seen from the debugger.

**Comment by tmorehouse** [comment]
What mobile device are you using? is it one of the supported devices specified by bootstrap V4?

**Comment by tmorehouse** [comment]
http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#mobile-devices

And depending on the browser in use on the device you may need the bael polyfill, or js-polyfill to support ES6 native object prototypes.

**Comment by tmorehouse** [comment]
Also are you migrating from native Bootstrap V4 over to Bootstrap-Vue?, and if so, are you using the `<b-dropdown>` component, or using your original dropdown HTML markup?   BootstrapVue works with the Bootstrap V4 CSS, but you must use the various BootstrapVue components to render the HTML.

Could you provide a sample of your page markup for your dropdown menus?

**Comment by narnikgamarnikus** [comment]
I use the standard HTML markup.
I also using a polyfill,
I checked on the old android, but for the first time I noticed the problem, I check in a desktop browser, having resulted in the screen resolution for mobile rendering.

**Comment by tmorehouse** [comment]
Standard markup as in plain bootstrap HTML, or plain markup as in using the `<b-dropdown>` component?

If using the plain Bootstrap HTML it will not work with Bootstrap-Vue.  Bootstrap vue is not a drop-in replacement for Bootstrap's `bootstrap.js`.  You must use the component markup specified in the Bootstrap-Vue [documentation](https://bootstrap-vue.js.org/docs/components/dropdown).
