### ISSUE TITLE
Form input file in Mi browser

### ISSUE THREAD

**Issue by ghostforpy** [bootstrap-vue/bootstrap-vue#6422]
Form-file in Mi browser v.12.7.5-go open camera, can't download file.

**Comment by Hiws** [comment]
Can you provide some more information about the issue?

**Comment by ghostforpy** [comment]
I use <b-form-file> in my vue app for upload file. When i test it on google chrome desktop, google chrome mobile, yandex browser mobile, it open file manager to choose file and works ok. But when i test it on mi browser mobile v.12.7.5-go, it open camera and i can't choose file for upload.![Screenshot_2021-02-14-10-50-25-091_android.png](https://user-images.githubusercontent.com/59663498/107871436-8b958c80-6eb2-11eb-94e6-dd71955ac2b0.png)![Screenshot_2021-02-14-10-50-52-232_android.png](https://user-images.githubusercontent.com/59663498/107871441-8fc1aa00-6eb2-11eb-8d2a-ca6d79284c16.png)

**Comment by Hiws** [comment]
Have you tried using a normal `<input type="file" />` and see what results you get?

**Comment by ghostforpy** [comment]
Simple input file works well.![Screenshot_2021-02-14-13-53-34-279_android.png](https://user-images.githubusercontent.com/59663498/107874685-2babdf80-6ecc-11eb-9a53-670b236ba0eb.png)
