### ISSUE TITLE
b-table, b-paginate and vuex dont work together

### ISSUE THREAD

**Issue by omarjebari** [bootstrap-vue/bootstrap-vue#6426]
### Describe the bug

I'm using b-table and b-paginate to display a list of items which are being stored in vuex. The data displays fine for the first page but if i click on any of the pagination links i get an empty list. If i then click back on page 1 (in the pagination links) the table loads fine.
Looking in the Network tab as i click the pagination links shows the request/response data is consistent and the vuex store is being updated. The Vue Inspector  shows that the b-table rows only get populated when the page 1 is being loaded for some reason.
Note: If i replace the use of b-table with an ordinary html table tag then it works fine. Code samples are below.

### Steps to reproduce the bug

B-Table Code Sample:

```
<b-table
    id="my-table"
    :items="paginatedList"
    :per-page="perPage"
    :current-page="currentPage"
    small
></b-table>

<b-pagination
                v-model="currentPage"
                :total-rows="totalCount"
                :per-page="perPage"
                class="mt-4"
                @page-click="navigate"
                @change="handlePageChange"
            >
                <template #first-text><span class="text-success">First</span></template>
                <template #prev-text><span class="text-danger">Prev</span></template>
                <template #next-text><span class="text-warning">Next</span></template>
                <template #last-text><span class="text-info">Last</span></template>
                <template #page="{ page, active }">
                    <b v-if="active">{{ page }}</b>
                    <i v-else>{{ page }}</i>
                </template>
            </b-pagination>

computed: {
        ...mapState({
            paginatedList: state => state.store.list,
        }),
}
```

etc

Table Code Sample

```
<table class="table">
    <thead>
        <tr>
            <th>name</th>
            <th>telephone</th>
            <th>address</th>
        </tr>
    </thead>
    <tbody>
        <tr v-for="item in paginatedList">
            <td>{{ item.name }}</td>
            <td>{{ item.tel }}</td>
            <td>{{ item.address }}</td>
        </tr>
    </tbody>
</table>
```

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.12
- Vuex: 3.6.0

**Environment:**

- Device: Mac
- OS: iOS 10.15.7
- Browser: Chrome
- Version: 87

**Comment by Hiws** [comment]
Is your computed property `paginatedList` only return the items for the current page, or is it returning items for multiple pages?

**Comment by omarjebari** [comment]
That works - thx!
