### ISSUE TITLE
Add property "sheet" to modal

### ISSUE THREAD

**Issue by bddexter** [bootstrap-vue/bootstrap-vue#6427]
Hi,

It would be nice if the `<b-modal>` component gets a property called `sheet` which makes the modal stick to the bottom and slides in from the bottom (I got this form our friends a vuetify).

I already achieved this with the following `css`:

```
.modal .modal-sheet {
    min-width: 100%;
    bottom: 0;
    position: fixed;
    margin: 0;
    max-height: 90%;
}

.modal.fade .modal-dialog {
    transform: translate3d(0, 100%, 0);
}

.modal.show .modal-dialog {
    transform: translate3d(0, 0, 0);
}
```

Thanks in advance

**Comment by Hiws** [comment]
There's currently two open PR's on Bootstrap, that is looking to add drawers/sidebars to Bootstrap. The first one is only left/right, however the second one also has an option to open from the bottom, and probably top too.
https://github.com/twbs/bootstrap/pull/31285
https://github.com/twbs/bootstrap/pull/29017

Bottom example:
<https://deploy-preview-29017--twbs-bootstrap.netlify.app/docs/5.0/components/offcanvas/#position>

I think it's best if we wait for these to get merged.

**Comment by bddexter** [comment]
@Hiws Thanks. Couldn't agree more :).
