### ISSUE TITLE
table sorting problem .

### ISSUE THREAD

**Issue by zuichune** [bootstrap-vue/bootstrap-vue#643]
Hi,
My code is as follows
   fields: {
                name: {
                    label: 'name'
                },
                no: {
                    label: 'no',
                    sortable:true
                }
            },
I want to sort 'no', but clicking on the name turns into a default sort?

**Comment by tmorehouse** [comment]
Is `no` a real field in your data array, or a virtual computed (formatted) column?

**Comment by zuichune** [comment]
I'm using custom data rendering

**Comment by tmorehouse** [comment]
So is their an actual field in your data array called `no`, or are you rending it from data from other columns?

**Comment by tmorehouse** [comment]
Built in sorting only works on columns that exist in hte supplied items array.

**Comment by zuichune** [comment]
The code is like this: 
fields: {
                name: {
                    label: 'name',
                },
                no: {
                    label: 'no',
                    sortable:true,
                },
            },
            items: [
                {
                    name: 'chen' ,
                    no: '123',
                },
                {
                    name: 'abc' ,
                    no: '321'
                },
                {
                    name:  'def' ,
                    no: '222'
                },
            ]
Why do you click name to default to the initial value?

**Comment by tmorehouse** [comment]
The table starts out in an unknown sort state, as it is not aware of the original order of your data.  Clicking a sortable header once will sort in one direction, then clicking it again will sort in the other, clicking an unsortable column header will revert the data back to the original order the items were provided in.

Also, your numbers are quotes strings, so they will sort alphabetically rather than numerically (i.e. 1, 10, 11, 12, 2, 20, 21, 22, etc)

**Comment by tmorehouse** [comment]
If you click on the name column header it will sort that column, if you click it again it will sort that column in the opposite order.  Clicking on another column header clears out sorting on the other column and sorts by that column only.  The data, using the built in sort, can only sort on a single column at a time.

**Comment by zuichune** [comment]
I see. Thank you very much.
