### ISSUE TITLE
b-table Column select support

### ISSUE THREAD

**Issue by Tadeu17** [bootstrap-vue/bootstrap-vue#6437]
### Is your feature request related to a problem? Please describe...

You provide a very interesting row select, like the select-mode single, multi, range. (b-table)

### Describe the solution you'd like

Having the possibilty to select the columns on click, in same fashion as you already do with rows

### Describe alternatives you've considered

in the scoped slotes data providade, add information about the row and column to which that very cell belongs to. so that we know in which column we are to make for example the range select mode

### Additional context

In my case, I'm just trying to do a column select, that on click selects one column, ctrl+click selects another column, shift-click selects a range of columns.

**Comment by Tadeu17** [comment]
Related to ticket: #4140

**Comment by TheNewSound** [comment]
Possible to achieve this outside of bootstrapVue, by custom field slots in your table, then apply a 'selected' style to those cells.
