### ISSUE TITLE
Additional info in head scoped slot

### ISSUE THREAD

**Issue by Tadeu17** [bootstrap-vue/bootstrap-vue#6438]
### Is your feature request related to a problem? Please describe...

I want to know the column to which the head cell I'm editing in the scoped slots belongs to

### Describe the solution you'd like

in the returned scoped slots, you already provide, for instance, the column property. Add ass well, for instance, columnIndex

**Comment by Hiws** [comment]
If you're using the `fields` prop, you could create a method to find the index of the column.

The below snippet will show the columnIndex and the label.
```html
<template #head()="{ label, column }">
  {{ fields.map(({ key }) => key).indexOf(column) }} - {{ label }}
</template>
```
<https://codepen.io/Hiws/pen/wvogYxg>

If you're not using the `fields` prop, and rely on the auto generated fields based on your items, you can use the below snippet.
```
<template #head()="{ label, column }">
  {{ Object.keys(items[0]).indexOf(column) }} - {{ label }}
</template>
```
<https://codepen.io/Hiws/pen/VwmPEGZ>

**Comment by Tadeu17** [comment]
@Hiws thanks. It definitely is a workaround, I didn't have time to address this yet but that's what I'd do.
Still feel like this is a simple think that might be handy quite some times and possibly easy to implement.

Also, looking at this as I'm trying to add column selection with a behavior similar to what we can do with the rows, and for this I need to know the columns

Thank you
