### ISSUE TITLE
Invalid prop: type check failed for prop "max". Expected String, Date, got Date

### ISSUE THREAD

**Issue by felipesuri** [bootstrap-vue/bootstrap-vue#6439]
### Describe the bug

I follow steps on [Form DatePicker docs](https://bootstrap-vue.org/docs/components/form-datepicker#disabling-dates) for disabling days, but on :max and :min return an error on console:

_[Vue warn]: Invalid prop: type check failed for prop "max". Expected String, Date, got Date_ 

### My code

```js
<template>
  <b-form-row class="form-wrapper">
      <b-form-datepicker
        :inline="true"
        :min="minDate"
        :max="maxDate"
        id="date-from"
        v-model="form.from"
        placeholder="Data"
        locale="pt-BR"
        :date-format-options="{
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
        }"
      />
      
      <b-form-datepicker
        :inline="true"
        id="date-to"
        :min="minDate"
        :max="maxDate"
        v-model="form.to"
        placeholder="Data"
        locale="pt-BR"
        :date-format-options="{
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
        }"
      />
  </b-form-row>
</template>

<script>
export default {
  data() {
    const now = new Date()
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())

    const minDate = new Date(today)

    const maxDate = new Date(today)
    maxDate.setFullYear(maxDate.getFullYear() + 3)

    return {
      minDate,
      maxDate,
    }
  },
}
</script>
```
---

- BootstrapVue: 2.17.3
- Bootstrap: 4.5.2

**Comment by Hiws** [comment]
Looks like you're a few versions behind.
Can you try updating to the latest version to see if the issue persists?

**Comment by felipesuri** [comment]
@Hiws I updated to this version: "bootstrap-vue": "^2.21.2", but the error persist.

**Comment by Hiws** [comment]
> @Hiws I updated to this version: "bootstrap-vue": "^2.21.2", but the error persist.

Which version of Vue are you using?

**Comment by felipesuri** [comment]
@Hiws I'm using NuxtJS 2.14.16

**Comment by travis5491811** [comment]
Any update on this? I have the same issue. Passing `new Date()` for max throws the same error.

**Comment by travis5491811** [comment]
The docs are wrong. Change `:max="new Date()"` to `:max="new Date().toISOString()"`. They don't show converting to iso string in docs example but it will throw error if you don't.

**Comment by felipesuri** [comment]
@travis5491811 Transform date in `toISOString()` solved my problem.
