### ISSUE TITLE
Get multiple b-modal dynamically created with different IDs but in Depend on data in filed in table

### ISSUE THREAD

**Issue by halols** [bootstrap-vue/bootstrap-vue#6440]
<table class="table mt-3 table-bordered">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">Payment Date</th>
                    <th scope="col">Value</th>
                    <th scope="col">Payment Status</th>
                    <th scope="col">Payment Method</th>

                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                   <tr v-if="empty"><td colspan="7"> No Data </td></tr>
                  <tr v-else v-for="item in filteredMethod" v-bind:Key="item.StudentID">
                    <td>{{item.PaymentDate}}</td>

                    <td>{{item.Amount}}</td>

                    <td>{{item.PaymentStatus}}</td>
                    <td>{{item.PaymentMethod}}</td>
                    <td>
                      
                      <b-button variant="primary" 
                        @click="openmodel()" id="show-modal">View Details</b-button
                      >

              

                    </td>
                  </tr>
             
                </tbody>
              </table>
 <b-modal id="Bank" title="Bank Details" :show="showModal" name="Bank">
                        <table class="table mt-3 table-bordered">
                          <thead class="thead-light">
                            <tr>
                              <th scope="col">Recipt Number</th>
                              <th scope="col">Bank Name</th>
                              <th scope="col">Bank Branch</th>
                              <th scope="col">Deposit Date</th>
                            </tr>
                          </thead>

                          <tbody>
                            <tr v-if="empty"><td colspan="4"> No Data </td></tr>
                            <tr v-else v-for="item in actionsAdvanced" v-bind:Key="item.StudentID">
                              <td>{{item.ReceiptNumber}}</td>

                              <td>{{item.Bank}}</td>
                              <td>{{item.BankBranch}}</td>

                              <td>{{item.Bank_DepositDate}}</td>
                            </tr>
                          </tbody>
                        </table>
                      </b-modal>

<b-modal id="Cash" title="Cash Details" name="Cash">
                        <table class="table mt-3 table-bordered">
                          <thead class="thead-light">
                            <tr>
                              <th scope="col">Recipt Number</th>
                              <th scope="col">save box</th>
                            </tr>
                          </thead>

                          <tbody>
                              <tr v-if="empty"><td colspan="2"> No Data </td></tr>
                            <tr v-else v-for="item in actionsAdvanced" v-bind:Key="item.StudentID">
                              <td>{{item.ReceiptNumber}}</td>

                              <td>{{item.savebox}}</td>
                            </tr>
                          </tbody>
                        </table>
                      </b-modal>

<b-modal id="Cheque" title="Check Details" >
                        <table class="table mt-3 table-bordered">
                          <thead class="thead-light">
                            <tr>
                              <th scope="col">Recipt Number</th>
                              <th scope="col">Bank Name</th>
                              <th scope="col">Bank Branch</th>
                              <th scope="col">DueDate</th>
                              <th scope="col">Check Number</th>
                            </tr>
                          </thead>

                          <tbody>
                            <tr v-if="empty"><td colspan="2"> No Data </td></tr>
                            <tr v-else v-for="item in actionsAdvanced" v-bind:Key="item.StudentID">
                              <td>{{item.ReceiptNumber}}</td>

                              <td>{{item.Bank}}</td>
                              <td>{{item.BankBranch}}</td>

                              <td>{{item.DueDate}}</td>
                              <td>{{item.CheckNumber}}</td>
                            </tr>
                          </tbody>
                        </table>
                      </b-modal>

  <b-modal id="Transfer" title="Transfer Details" >
                        <table class="table mt-3 table-bordered">
                          <thead class="thead-light">
                            <tr>
                              <th scope="col">Recipt Number</th>
                              <th scope="col">Swift Code</th>
                              <th scope="col">Transfer date</th>
                           
                            </tr>
                          </thead>

                          <tbody>
                             <tr v-if="empty"><td colspan="2"> No Data </td></tr>
                            <tr v-else v-for="item in actionsAdvanced" v-bind:Key="item.StudentID">
                              <td>{{item.ReceiptNumber}}</td>

                              <td>{{item.SwiftCode}}</td>
                              <td>{{item.Transferdate}}</td>

                          
                            </tr>
                          </tbody>
                        </table>
                      </b-modal>       

<script>
import FinancialData from "../../components/Financial/FinancialData.vue";
import studentData from '../../services/student/studentDataServices';
export default {
     components: {
      FinancialData,
  
  },
  
  name: "CashReceipt ",
  data() {
    return {
      selected: null,
      show: true,
      AccountDetails:'',
      StudentTransactions:'',
      actionsAdvanced:'',
      search:'',
      model:'',
      name:'',
      isHidden: false,
      options: [
          { value: null, text: 'Select Method' },
          { value: 'Cash', text: 'Cash' },
          { value: 'Bank', text: 'Bank' },
          { value: 'Cheque', text: 'Cheque' },
          { value: 'Transfer', text: 'Transfer' },

     ],
     
    };
  },
  computed:{
           currenUser(){
            return  this.$store.state.auth.user
          },
          filteredMethod: function(){
          return this.StudentTransactions.filter((item) =>{
          return item.PaymentMethod.match(this.search);
         
});
},
         openmodel: function(item){
           this.showModal.show()
          return this.StudentTransactions.filter((item) =>{
          return item.PaymentMethod.match(this.id);
          
         
});
}

       },
},
</script>

**Comment by Hiws** [comment]
Can you fix the formatting of your post, it's unreadable.
