### ISSUE TITLE
Equal icons

### ISSUE THREAD

**Issue by pauloklaus** [bootstrap-vue/bootstrap-vue#6446]
### The bug

I use some arrow icons, and in the last update I noticed that some icons were the same.

The pairs point to the same icon as a circle:

arrow-right-circle and arrow-right-square
arrow-left-circle and arrow-left-square
arrow-down-circle and arrow-down-square
arrow-down-left-circle and arrow-down-left-square
arrow-down-right-circle and arrow-down-right-square
arrow-up-circle and arrow-up-square
arrow-up-left-circle and arrow-up-left-square
arrow-up-right-circle and arrow-up-right-square

This doesn't just happen in the documentation. In my project, the square and unfilled icons are all circles.

### Version

- BootstrapVue: 2.21.2

**Comment by Hiws** [comment]
This looks to already be fixed on the dev branch, probably due to using a newer version of Bootstrap Icons.

You can check it here.
<https://dev.bootstrap-vue.org/docs/icons#icons-1>
