### ISSUE TITLE
b-form-file, bug when uploading multiple files one-by-one

### ISSUE THREAD

**Issue by Titoineis** [bootstrap-vue/bootstrap-vue#6448]
### Describe the bug

I'm using b-form-file to upload files on my server but when I want to add multiple files on-by-one, it is resetting all previous uploaded files.

### Steps to reproduce the bug

1. Create a b-form-file component
2. Add multiple files one-by-one (by selecting one file then going back onto the file input and selecting another)

### Expected behavior

I expect the file input to keep the previous uploaded files

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Computer
- OS: Windows 10
- Browser: Chrome
- Version: 88.0.4324.150

**Comment by Hiws** [comment]
This is expected behavior as that's how `<input type="file" multiple />` works.
If you want to keep the previously selected files, you could save them in an array as they're chosen.

**Comment by Titoineis** [comment]
Ok, thanks for the answer, that's what I did.
