### ISSUE TITLE
Vue table added class on newly created div before table tag

### ISSUE THREAD

**Issue by varun761** [bootstrap-vue/bootstrap-vue#6449]
### Describe the bug

There is a new div component inserted before the table with the class name that defined in b-table tag along with 'table-responsive' class . That happens on responsive table which make it scroll .

### Expected behavior

The class that mentioned in the tag should be added to the b-table tag not the other div.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.12

**Environment:**

- Device: Mac or Windows
- OS: mac and windows
- Browser: Chrome and mozilla
- Version: [e.g. 70]

### Additional context

This doesn't happen on all the systems. This is a exception. 
![download (1)](https://user-images.githubusercontent.com/15170824/108219544-d8e85700-715b-11eb-8ac0-f381470c1921.png)
![download (2)](https://user-images.githubusercontent.com/15170824/108380841-3ef0df00-722d-11eb-827a-39b29289a961.png)

**Comment by Hiws** [comment]
Not quite sure what the problem is you're describing.
Maybe it would help if you provided some of your markup.

**Comment by varun761** [comment]
I updated the two screen shots. Can you please review .
The only issue is that it make it scrollbale .

**Comment by Hiws** [comment]
> I updated the two screen shots. Can you please review .
> The only issue is that it make it scrollbale .

Could you include your markup aswell, so i can see how you define `<b-table>`.

**Comment by varun761** [comment]
I am using responsive prop on both 
<b-table hover responsive striped
              :items="allTransactions"
              :fields="fieldValues"
              :filter="transaction_filter"
              :per-page="TransactionPerPage"
              :current-page="TransactionCurrentPage"
              stacked="lg"
              select-mode="multi"
              :emptyText="$t(translationPath + 'table.no_data')"
              @filtered="onFilteredTransactionAccounts"
              @row-hovered="rowHoveredHandler"
              @row-unhovered="rowUnHoveredHandler"
              :tbody-tr-class="rowClass"
              :busy="busyState"
              ref="transactionTableView"
              class="spirecta-import-step3-table" show-empty>

**Comment by Hiws** [comment]
If you can create a reproduction of the issue i can take a look, but based on the code you've provided it should work, and it does work if i paste it into the docs playground.
