### ISSUE TITLE
I want to add a notification function on the b-table.

### ISSUE THREAD

**Issue by applelogintest** [bootstrap-vue/bootstrap-vue#6453]
### Is your feature request related to a problem? Please describe...

I used #top-row with v-for on the b-table, but it didn't work

### Describe the solution you'd like

I would like to use multiple #top-rows on the b-table.
I want to use the announcement function on the notice board.

### Describe alternatives you've considered

If we use #top-row for v-for, it'll be possible.

**Comment by Hiws** [comment]
You can't have multiple of the same slots.
Instead just place your content in the same slot, and loop through it in there.

https://codepen.io/Hiws/pen/rNWYOxM

**Comment by applelogintest** [comment]
Thank you. Your solution was helpful.

But exactly what I said was that 5 of the table lists were fixed with top.

I think there is a misunderstanding because I am using a translator because I am not good at English. :(

Thank you again!
