### ISSUE TITLE
b-table sort-compare function returns invalid result on chrome browser

### ISSUE THREAD

**Issue by bsienn** [bootstrap-vue/bootstrap-vue#6458]
### Describe the bug

I'm using custom sorting using sort-compare and passing function to it using the demo code from docs.
Everything works fine on firefox but not in chrome.
What happens is first 2 params to the functions `aRow` & `bRow`  are getting swapped in chrome.

So aRow shows 1st column in firefox but 2nd in chrome, thus the comparison operation gets invalid.

### Steps to reproduce the bug
1) Open the demo link mentioned below.
2) Try clicking sort button on the `current price`.
3) Check console log and 1st element of array printed and its content.
4) Repeat above steps on chrome and firefox to see the difference.
I've added a small check that, if the value is zero then always put those records at the end of the result after sort.

Attached screenshot for reference
![Capture](https://user-images.githubusercontent.com/3149876/108596157-0a079800-73a5-11eb-9a5a-1f4660344acb.PNG)

### Expected behavior

Same sorting on all browsers using sort-compare

### Versions

**Libraries:**

- BootstrapVue: 2
- Bootstrap: 4
- Vue: 4

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Chrome, Firefox
- Version: latest

### Demo link

[codesandbox.](https://codesandbox.io/s/lucid-dew-hun6x?file=/src/App.vue)

### Additional context

Please look at the console log, it shows that aRow & bRow values get swapped in chrome but works as expected in firefox

**Comment by TheNewSound** [comment]
This is not a bug? Chrome uses a different .sort() algorithm under the hood, but as you can see, the resulting value is 1 in chrome and -1 in firefox. The order of the parameters does not matter, as long as the outcome is consistent, and it IS consistent.

The issue you are having is not from the sorting function.

**Comment by bsienn** [comment]
Thanks for you reply. Yes sorry I should have mentioned that as well. I modified the code to meet my requirement. That is why I use custom compare method.

IMHO, Problem is not my condition. Problem is why would the parameters aRow have bRow result swap on chrome?
In firefox aRow have 1 and bRow have 0
In chrom aRow have 0 and bRow have 1

this is causing problem for me. Can you please guide me on this if possible

**Comment by TheNewSound** [comment]
Its because YOUR compare function introduced an order dependency of your function calls:
```javascript
      if (bRow["current_price"] === 0.0) {
        return sortDesc ? 1 : -1;
      }
```
Look at that function, you only check bRow, while bRow / aRow can be different on a different browser, but also depending on your initial ordering. You violate constraints by only checking bRow in a sorting function.

**Comment by bsienn** [comment]
I see, I think I get your point. so the parameters are not guaranteed to be in order.
so i have to check for both values if they are == 0.0 in my condition.

I think you solved my issue.

**Comment by bsienn** [comment]
Thanks to TheNewSound, his help sent me right track and at the end I'd to use my custom sorting by disabling the local sort.
Sorry for making this a bug report.
