### ISSUE TITLE
Accessibility: can't set title on b-form-datepicker's button

### ISSUE THREAD

**Issue by steffchep** [bootstrap-vue/bootstrap-vue#6462]
### Describe the bug

I've looked in the docs, but found no attribute that allows me to set a title on this button:
![bootstrap-button](https://user-images.githubusercontent.com/10571670/108676099-003a7d80-74e8-11eb-9d41-df7603458a0b.jpg)

Axe Accessibility Tools give a slap o the wrist for "no discernible text on button"

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.org/docs/components/form-datepicker
2. Hover over the calendar icon (or use screen reader. or an accessibility analyzer)
3. no title on the button.

### Expected behavior

Be able to set a title for the button and/or offer a default value, as for the other non-text buttons in the component (i.e. "next year", "next month" etc.

### Versions

**Libraries:**

Seen on current BootstrapVue website.

**Environment:**

Not relevant to bug

**More Info**

I can set a title on the entire element, however, this gets placed on the wrapper, not the button in question, and does not help with the above accessibility message

**Comment by apavelm** [comment]
We faced the same:
Here is a link with recommendations: https://dequeuniversity.com/rules/axe/4.1/button-name

my implementation:
` <b-form-datepicker id="datePicker"
                             today-button
                             close-button
                             locale="en"
                             v-model="selectedDate"
                             :start-weekday="'1'"
                             :date-format-options="{ year: 'numeric', month: 'long', day: '2-digit' }">
  </b-form-datepicker>`

**Comment by steffchep** [comment]
So much for " complete with extensive and automated WAI-ARIA accessibility markup"
