### ISSUE TITLE
b-carousel with different slide interval

### ISSUE THREAD

**Issue by bimalraj91** [bootstrap-vue/bootstrap-vue#6463]
is there a  way  to set different slide intervals in b-carousel vue.js

**Comment by Hiws** [comment]
You can dynamically change the `interval` prop on `<b-carousel>` to change the interval.

Here's a quick example.
<https://codepen.io/Hiws/pen/eYBeNqJ>

**Comment by bimalraj91** [comment]
> 
> 
> You can dynamically change the `interval` prop on `<b-carousel>` to change the interval.
> 
> Here's a quick example.
> https://codepen.io/Hiws/pen/eYBeNqJ

Its worked Thak You.....
