### ISSUE TITLE
b-form-radio-group state changing is not working from v2.21

### ISSUE THREAD

**Issue by hoquangthaiholy** [bootstrap-vue/bootstrap-vue#6464]
When I change back to v2.20.1. Everything is okay

**Comment by Hiws** [comment]
Could you provide an example of the code you're using, or a reproduction?

**Comment by hoquangthaiholy** [comment]
Sorry, I forgot. This is my code. It's working when I downgrade to v2.20.x

`$v` is validation object from vuelidate package
<img width="655" alt="Screen Shot 2021-02-23 at 16 18 35" src="https://user-images.githubusercontent.com/614264/108817516-f7829e00-75f2-11eb-929c-ffa2a309dcb3.png">

**Comment by Hiws** [comment]
Looks to work correctly for me in the latest version.

When `Male` is selected there's no `aria-invalid` on the root tag, but when `Female` or `Intersex` is chosen, it adds `aria-invalid="true"` to the tag as i would expect.
<https://codepen.io/Hiws/pen/oNYobzO>

If you could provide some more information, or preferably a reproduction It would be easier to help.

**Comment by hoquangthaiholy** [comment]
Ah, it's not working when the radio group stated is false.

**Comment by Hiws** [comment]
Just tested it on the docs, looks to be fixed on the current dev branch.
So the next release should fix the issue.


You can try the following code on the docs playground and compare the difference between [latest version](https://bootstrap-vue.org/play) and the [dev branch](https://dev.bootstrap-vue.org/play)
```html
<b-radio-group v-model="selectedGender" :state="selectedGender === '1'">
  <b-radio value="1">Male</b-radio>
  <b-radio value="2">Female</b-radio>
  <b-radio value="3">Intersex</b-radio>
</b-radio-group>
```

```js
{
  data() {
    return {
      selectedGender: null
    }
  }
}
```
