### ISSUE TITLE
Make bootstrap vue modal's root changeable

### ISSUE THREAD

**Issue by shash7** [bootstrap-vue/bootstrap-vue#6469]
Not sure if there's already a way to to this but I want to mount the bootstrap vue modal to a particular div instead of body.

---

Use case: I'm changing my webapp to a webcomponent so it can run easily inside other contexts. However, everything works fine except modals since they mount to the body rather than inside the webcomponent's root.

**Comment by Hiws** [comment]
Have you tried using the `static` prop, to render the modal where it's placed in the document?

**Comment by hafdon** [comment]
This from component reference:

https://bootstrap-vue.org/docs/components/modal

Modals can be rendered *in-place* in the document (i.e. where the
<b-modal> component
is placed in the document) by setting the static prop to true. Note that
the content of the modal will be rendered in the DOM even if the modal is
not visible/shown when static is true. To make static modals lazy rendered,
also set the lazy prop to true. The modal will then appear in the document
*only* when it is visible. Note, when in static mode, placement of the
<b-modal> component *may affect layout* of your document and the modal.

The lazy prop will have no effect if the prop static is not true (non-static
modals will *always* be lazily rendered).

**Comment by shash7** [comment]
Ah that works perfectly. Thanks guys!
