### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'Object.assign(i("href","to"),{href:{type:O.href.type},to:{type:O.to.type}})')

### ISSUE THREAD

**Issue by esmsnt** [bootstrap-vue/bootstrap-vue#647]
Thanks again for this great project!

I, and perhaps others, use the prerender-spa-plugin to statically render some of our SPA for search indexing.  The plugin uses PhantomJS to perform the pre-render which doesn't seem to support much if any ES2015+.

Previously in 0.17.0 + 0.17.1 I was also hitting #587 which you fixed in #589 in 0.18.0.  Thanks for that :)

I can polyfill PhantomJS to get around this but since I saw you fix the usage of includes in #589 I thought I would bring this to your attention so you can fix it or transpile it as you see fit.

The error is from the minified file but I think it is used on omitLinkProps in breadcrumb, bBtn, badge and listGroupItem.

**Comment by alexsasharegan** [comment]
Could you provide some info on what component you were trying to render? And any props you were passing along. Thank you!

**Comment by alexsasharegan** [comment]
I believe we've found all the Array.prototype.includes and switched them over to an es5 compat helper function.

**Comment by esmsnt** [comment]
This was on my privacy policy page which is nearly completely static, the only components rendered from bootstrap-vue are the header.  b-navbar, b-nav-toggle, b-nav, b-link, b-collapse.  I included a filtered snippet of the header below.

`<b-navbar toggleable type="inverse" variant="primary" fixed="top">
  <b-nav-toggle target="nav_collapse"></b-nav-toggle>
  <div id="nav-inner-container" class="container">
    <b-link :to="{ name: 'Public'}">
      <icon class="navbar-brand" name="address-book-o" scale="2.5" flip="horizontal"></icon>
    </b-link>
    <b-link id="navbar-brand-text" class="navbar-brand" :to="{ name: 'Public'}">
      <span>Title</span>
    </b-link>
  
    <b-collapse is-nav id="nav_collapse">
  
    <b-nav is-nav-bar>
        <b-nav-item href="/#trynow" >Try</b-nav-item>
    </b-nav>
  
    <b-nav is-nav-bar class="ml-auto">
        <b-nav-item right :to="{ name: 'Login'}">
        Login
        </b-nav-item>
    </b-nav>
  
    </b-collapse>
  </div>
</b-navbar>`

Today, this also lead me to problem with the prerender-spa-plugin which should include core-js polyfills, there is an issue with the path that prerender-spa-plugin uses to inject core-js.  This works around the problem in case anyone else runs into this.  https://github.com/chrisvfritz/prerender-spa-plugin/pull/54

**Comment by esmsnt** [comment]
Great!  Thanks for your help!

**Comment by alexsasharegan** [comment]
Did your issue already get resolved? Was it the prerender plugin? Our es5 helper functions are in v0.18.0, so I want to make sure there aren't any stragglers that need to conform to es5.

**Comment by esmsnt** [comment]
Sorry about that, I misread your earlier comment.

The issue is present in 0.18.0.  The polyfill (when working) in prerender plugin covers the issue.  It looks like Object.assign is still present in 0.18.0, Array.prototype.includes appears fixed in 0.18.0.

**Comment by tmorehouse** [comment]
Object.assign is used in many places for merging options/props.  So a js-pollyfill (or ES6.js polyfill) would be needed for IE 11 support.

**Comment by tmorehouse** [comment]
Array.prototype.includes is a newer standard that has very limited browser support (so we have "rolled" our own includes helper.

**Comment by alexsasharegan** [comment]
I was afraid it was `Object.assign`. I could be wrong, but I don't believe we intend to polyfill es5 features (Vue itself relies on various es5 features). We do intend to cover es2015 features since they don't have full adoption and platform support yet. es5 polyfills would bloat the size of the library and possibly duplicate polyfills in your own app, so like Troy said, best to find your own polyfill solution. This will let you polyfill just what you need, rather than BV making a catch-all decision on what polyfills should be included.

**Comment by esmsnt** [comment]
Sounds good, Thanks again for an excellent project you have here.

**Comment by tmorehouse** [comment]
I think just a single Object Assign polyfill would fix most issues.

You could conditionally add this in the`< head>`  (via IE conditional comments) or just include it always:

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill

```js
if (typeof Object.assign != 'function') {
  Object.assign = function(target, varArgs) { // .length of function is 2
    'use strict';
    if (target == null) { // TypeError if undefined or null
      throw new TypeError('Cannot convert undefined or null to object');
    }
    var to = Object(target);
    for (var index = 1; index < arguments.length; index++) {
      var nextSource = arguments[index];
      if (nextSource != null) { // Skip over if undefined or null
        for (var nextKey in nextSource) {
          // Avoid bugs when hasOwnProperty is shadowed
          if (Object.prototype.hasOwnProperty.call(nextSource, nextKey)) {
            to[nextKey] = nextSource[nextKey];
          }
        }
      }
    }
    return to;
  };
}
```

The side of the above code can be reduced by minification
