### ISSUE TITLE
router-link generated cause warning from vue-router

### ISSUE THREAD

**Issue by dtgeorge** [bootstrap-vue/bootstrap-vue#6471]
After update vue-router from 3.1.5 to 3.5.1 got warning in console:

`[vue-router] <router-link>'s tag prop is deprecated and has been removed in Vue Router 4. Use the v-slot API to remove this warning: https://next.router.vuejs.org/guide/migration/#rem`

`b-nav-item` (at least) with property "to" cause `router-link` generation. As far as I see vue router is preparing for the switching to new version (4 I guess) and produce such warnings.

### Steps to reproduce the bug

Create b-navbar with b-nav-item with property "to" used.
Example:
`<b-nav-item  to="/Orders" >Link Text</b-nav-item>`

### Expected behavior

Now warnings in console

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Vue: 2.6.12
- Vue Router: 3.5.1

**Comment by deni5n** [comment]
hi, does anyone know what is the state of this issue?

**Comment by strixy** [comment]
[This issue in vue-router](https://github.com/vuejs/vue-router/issues/3459) suggests that it was "already fixed and released", but the warning persists in the latest release (v3.5.1) which has the same release date as the post. I'm not sure what to make of it.

**Comment by DavidRogersDev** [comment]
Just confirming that this issue is still manifesting in 2.21.2

**Comment by XpamAmAdEuS** [comment]
Not a bug in Router its just warnning.
https://next.router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link.
In order to remove warnning blink must be updated.

**Comment by strixy** [comment]
Thanks @XpamAmAdEuS 

> In order to remove warnning blink must be updated.

Does this issue count towards updating b-link or is a new issue required?

**Comment by Kayoshi-dev** [comment]
Also happens when using the b-pagination-nav component !

**Comment by daomtthuan** [comment]
I have an obsessive compulsion, so I don't feel okay with things that aren't perfect even though I know it's just a warning, not an error. Sorry! 
Hopefully there will be no more warnings at version 2.21.3
Have you followed this docs? https://next.router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link

**Comment by caugner** [comment]
I guess these would need to be replaced and/or moved to an inner element:

https://github.com/bootstrap-vue/bootstrap-vue/blob/1d59417df6869e2b04c651f6caeed9474cf14a84/src/components/link/link.js#L32

https://github.com/bootstrap-vue/bootstrap-vue/blob/1d59417df6869e2b04c651f6caeed9474cf14a84/src/components/link/link.js#L36

See: https://next.router.vuejs.org/guide/migration/#removal-of-append-prop-in-router-link

> ### Removal of `event` and `tag` props in `<router-link>`
> 
> Both `event`, and `tag` props have been removed from `<router-link>`. You can use the `v-slot` API to fully customize `<router-link>`:
> 
> ```html
> replace
> <router-link to="/about" tag="span" event="dblclick">About Us</router-link>
> with
> <router-link to="/about" custom v-slot="{ navigate }">
>   <span @click="navigate" @keypress.enter="navigate" role="link">About Us</span>
> </router-link>
> ```
> 
> **Reason**: These props were often used together to use something different from an `<a>` tag but were introduced before the `v-slot` API and are not used enough to justify adding to the bundle size for everybody.

**Comment by caugner** [comment]
**Duplicate** of #6373.

The issue was fixed by #6374 and will appear in the next minor version (2.22.0). That PR resolves the warnings for most users, except those that actually use the `event` and `tag` props on `BLink` and similar components.

**Comment by TapeGhad** [comment]
@caugner Same problem with b-navbar-brand

**Comment by ayadiMohamedAmine** [comment]
Same problem with b-breadcrumb-item

**Comment by nmourtoncomte** [comment]
same here

**Comment by davebeesley** [comment]
I am seeing this issue in my codebase which utilises bootstrap vue.

Can somebody confirm this has been fixed, so I can rule out bootstrap vue as the cause?

It is in one of my dependencies, as I can't find tag or event used in any router links in the main codebase

**Comment by gmw-web** [comment]
@davebeesley , this should be fixed by #6374 , but it is not yet released in a new (minor) version of Bootstrap Vue (e.g. v2.22.0). 

You can't believe your luck, because word came out that a new release can be expected soon.... see #6872 for more context about that.

**Comment by davebeesley** [comment]
Brilliant, thank you for the update @gmw-web 

I am so close to having no npm vulnerabilities or deprecation warnings on a legacy codebase I have inherited :)
