### ISSUE TITLE
Upgrade icons to latest version

### ISSUE THREAD

**Issue by jonalxh** [bootstrap-vue/bootstrap-vue#6472]
### Is your feature request related to a problem? Please describe...
Not really a problem, but when trying to use the same icons of bootstrap official documentation you can see that icons are not the same.

Current version of bootstrap icons is 1.4.0  and you are using v1.2.2, a lot of icons have been added and improved in latest versions.

Are you planing to update to latest version? There are several icons I want to start using in my code, now I'm using two icon fonts to supply my needs.

**Comment by Hiws** [comment]
Bootstrap Icons `1.3.0` has already been added to the next release, and version `1.4.0` should probably make it as well to the next release of BootstrapVue.

**Comment by neuromask** [comment]
There is icon v1.7.0 already, please make update to the latest version before release. Thanks
