### ISSUE TITLE
When row is both selected and de-selected, a 2px (i think) black border appears around row. I have tried to find a way to override this behavior using css but I cannot for the life of me find the right selector to make this happen.

### ISSUE THREAD

**Issue by jwahl** [bootstrap-vue/bootstrap-vue#6475]
this is the css that I use to make the selected row different color which works perfectley.

```
tr.b-table-row-selected td{
  background: #3ea541 !important;
    color: white !important;
    border:1px solid #3ea541 !important;
}
```

I thought I could just do something like this:

```
tr.b-table-row-selected{border:0 !important;}

```

But nothing I try seems to get rid of that thick-ish black border once a row has been selected.  Any ideas?

Thank you!

**Comment by ddweber** [comment]
Are you speaking about the outline which appears around a row when it is selectable and **has focus**?
Then you could remove it by:

`tr.b-table-row-selected:focus {
    outline: 0;
}`
