### ISSUE TITLE
b-tab v-model triggered unexpectedly

### ISSUE THREAD

**Issue by arthurmcgregor** [bootstrap-vue/bootstrap-vue#6479]
### Describe the bug

I am trying to add a + button to dynamically add a new tab, similar to [this example](https://bootstrap-vue.org/docs/components/tabs#tabs) from the docs. I want to extend the example so that when a new tab is added, the new tab becomes the active tab. I am trying to update the tabIndex using the v-model, but something keeps changing the v-model back to a different value.

### Steps to reproduce the bug

1. Open [demo](https://codesandbox.io/s/white-tdd-sj9ms?file=/App.vue:685-828)
2. Click the add button
3. A new tab is added ✔️ 
4. Tab 'c' becomes the active tab ❌ 

### Expected behavior

When the new tab button is pushed, I expect the new tab to become the active tab.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Laptop
- OS: Window 10
- Browser: Firefox v96, Chrome v88

### Demo link

As above: https://codesandbox.io/s/white-tdd-sj9ms?file=/App.vue:685-828

### Additional context

I added some console.log statements with a watcher on tabIndex to try and see what is going on.
- When the tab array is updated, the tabIndex changes from 0 to 1 (no idea why!)
- Then my code updates the tab index to 3, successfully
- Then something changes it to 2 (no idea why!)

![image](https://user-images.githubusercontent.com/24260476/110039791-a159eb80-7da6-11eb-9c51-fc4568967b45.png)

If I remove the tab array update, then I still get the change from 0 to 1, and then back from 1 to 0. No change in the UI

```js
    async addTab(){
      this.tabs.push('new')
      console.log('updated this.tabs')
      // await this.$nextTick()
      // this.tabIndex = this.tabs.length - 1
      // console.log('updated tabIndex to', this.tabs.length - 1)
    }
```

![image](https://user-images.githubusercontent.com/24260476/110040028-01509200-7da7-11eb-8d9b-d85322732b85.png)

**Comment by Hiws** [comment]
The issue is most likely that the `<b-tab>` hasn't been rendered yet, to `<b-tabs>` doesn't know it exists and will adjust the `v-model` down to the last element it knowns of.
You can use `setTimeout` to allow the tab to render before setting tabindex.

```js
addTab() {
  this.tabs.push("new");
  setTimeout(() => {
    this.tabIndex = this.tabs.length - 1;
  })
}
```

**Comment by arthurmcgregor** [comment]
Hmmm thanks Hiws - that does fix things but doesn't feel the the "right" solution!?!

Why didn't `await this.$nextTick()` work?

**Comment by Hiws** [comment]
As mentioned, I believe the issue is the way `<b-tabs>` detect how many `<b-tab>` it has as children.
Using `$nextTick` doesn't allow the `<b-tab>` to render in the DOM, while `setTimeout` does.

I'm mostly guessing here, so it might not be the correct reason.
You can also try giving [this](https://www.hesselinkwebdesign.nl/2019/nexttick-vs-settimeout-in-vue/) a read to better understand the difference.

**Comment by arthurmcgregor** [comment]
Hmm thanks for the explanation and link to read. Learnt some stuff!

I suspect your guess is correct and that it has to do with the comment on this [line](https://github.com/bootstrap-vue/bootstrap-vue/blob/1d59417df6869e2b04c651f6caeed9474cf14a84/src/components/tabs/tabs.js#L362) in the b-tabs `getTabs()` method.

>We rely on the DOM when mounted to get the "true" order of the `<b-tab>` children

which might explain why the b-tabs can't find the new tabs until the render has been complete.

Closing because valid workaround. Thanks again @Hiws
