### ISSUE TITLE
Blank page with vue 3

### ISSUE THREAD

**Issue by Mrbeyond** [bootstrap-vue/bootstrap-vue#6482]
### Describe the bug

"export 'default' (reexported as 'Vue') was not found in 'vue' is showed in run command and the app only shows blank page.
The code block for implementation is shown  below.

import { BootstrapVue, BootstrapVueIcons } from 'bootstrap-vue'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'

createApp(App)
  .use(BootstrapVue)
  .use(BootstrapVueIcons)
  .use(store)
  .use(router)
  .mount('#app')

**Comment by Hiws** [comment]
BootstrapVue does not yet support Vue 3 as per this issue https://github.com/bootstrap-vue/bootstrap-vue/issues/5196
