### ISSUE TITLE
b-form-input type number accepts character 'e', 'E'

### ISSUE THREAD

**Issue by Ajility97** [bootstrap-vue/bootstrap-vue#6484]
### Describe the bug
![chrome-capture (1)](https://user-images.githubusercontent.com/68575573/110214239-b5b6ea80-7e71-11eb-9dd1-91eebe483cc0.gif)

### Steps to reproduce the bug
1. Go to [BootStrap Vue Form Input Demo](https://bootstrap-vue.org/docs/components/form-input)
2. Scroll down to Input Type
3. In the Type number textbox type the character 'e'
4. Notice that no other character is accepted except 'e' (case insensitive)

### Expected behavior
Input type `number` should reject all letters, including 'e' and 'E'

**Comment by Hiws** [comment]
`<b-form-input type="number">` renders a `<input type="number">` so all validation and behavior of the input is left up to the browser. In chrome `e` is allowed because of scientific notation. In FireFox all characters are allowed and the input is only validated on submit.
