### ISSUE TITLE
b-subnav for vertical nav

### ISSUE THREAD

**Issue by zhaojh329** [bootstrap-vue/bootstrap-vue#6485]
![image](https://user-images.githubusercontent.com/28673295/110240371-8e9e0d00-7f86-11eb-91bd-a85b11c67d24.png)

This picture is pretty much illustrative.
A nest nav menu and support accordion mode.

**Comment by Hiws** [comment]
Could you please describe what this issue is about?

**Comment by zhaojh329** [comment]
> Could you please describe what this issue is about?

This picture is pretty much illustrative.
A nest nav menu and support accordion mode.

**Comment by Hiws** [comment]
You can use `<b-collapse>` for a dropdown like navigation inside `<b-nav vertical>`.
