### ISSUE TITLE
Import single component

### ISSUE THREAD

**Issue by akaNightmare** [bootstrap-vue/bootstrap-vue#649]
I want to use collapse component, is it possible and do not load all BootstrapVue?

**Comment by tmorehouse** [comment]
Yes it is possible.

See https://bootstrap-vue.js.org/docs/setup

**Comment by 3nuc** [comment]
As per the [documentation](https://bootstrap-vue.js.org/docs/components/collapse/) tmorehouse's answer should now be:
```
import bCollapse from 'bootstrap-vue/es/components/collapse/collapse'
import bToggle from 'bootstrap-vue/es/directives/toggle/toggle'

//also this, I'm a noob so I had trouble figuring this out
export default {
  directives: { bToggle },
  components: { bCollapse },
}
```
