### ISSUE TITLE
Progress bar animation isn't working

### ISSUE THREAD

**Issue by laurisstepanovs** [bootstrap-vue/bootstrap-vue#6490]
### Describe the bug

Bug with progress bar animation it is broken
![image](https://user-images.githubusercontent.com/33573735/110707902-a1247a80-8202-11eb-8161-f49f227bc8dd.png)

### Steps to reproduce the bug

I just included the progress bar as it is shown in your demo.
https://bootstrap-vue.org/docs/components/progress

### Expected behavior

Progressbar animation must work the same as it is shown in the demo.
https://bootstrap-vue.org/docs/components/progress

### Versions

**Libraries:**

- BootstrapVue: ^4.6.0
- Bootstrap: ^2.21.2
- Vue: ^3.3.0

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome, Safari

**Comment by Hiws** [comment]
Have you disabled animation on your machine?
Please check whether other animations on the docs are disabled as well.

Such as fade animation when a modal opens https://bootstrap-vue.org/docs/components/modal#modals
or the animation when opening/closing a collapse https://bootstrap-vue.org/docs/components/collapse

**Comment by laurisstepanovs** [comment]
No, it is enabled on my machine. Other animations are working fine and on your demo page progress bar animation is working as well. Issue only exists then I am trying to use animated progress bar locally I am making everything the same as it is shown in the example.

```
<b-progress :value="value" :max="max" show-progress animated></b-progress>
```

**Comment by Hiws** [comment]
Well, there's a few issues with your "versions" section.
It looks like you might've swapped the versions of Bootstrap and BootstrapVue. 
BootstrapVue also doesn't support Bootstrap `4.6.0`, so that could maybe be the issue.

Also Vue `3.3.0` doesn't exist, and BootstrapVue doesn't support Vue 3 either, so not sure what that's referring to.

**Comment by laurisstepanovs** [comment]
Oh sorry, wrong versions 
My actual versions are:
"vue": ^2.6.11
"bootstrap": "^4.5.0",
"bootstrap-vue": "^2.13.0",

**Comment by Hiws** [comment]
Best suggestion i can make without a reproduction is to update Bootstrap to `4.5.3` and BootstrapVue to `2.21.2`.
If that doesn't work, inspect the element in your App and compare it to the one on the Docs.

**Comment by laurisstepanovs** [comment]
Sorry for the late reply.
Yes this issue was not related to the bootstrap-vue version.
Just some of my classes overrided bootstrap classes and for progress bar the background was set to no-repeat.
Already fixed it.
Thanks!
