### ISSUE TITLE
Access to the items array in thead-top slot

### ISSUE THREAD

**Issue by futureshock2038** [bootstrap-vue/bootstrap-vue#6497]
I see from the documentation that the custom-foot slot has access to the Items array, but the custom header slot does not. Is there anyway to get access to the Items array so that I can place a badge in the thead-top slot to display the total number of rows being displayed in the table after the itemsProvider has finished its work?

Any help or guidance is much appreciated.

**Comment by Hiws** [comment]
In your provider function you could set a property in `data` with amount of rows, and then use that property in your `thead-top` slot. 
That would probably be the easiest solution.

**Comment by futureshock2038** [comment]
@Hiws thanks, I swore I tried this before and the table didn't render so I was thinking that inside of the promise that I could not set data, but of course that makes sense.

Thanks for the help.
