### ISSUE TITLE
Cursor jumping on b-textarea with async v-model assignment

### ISSUE THREAD

**Issue by bLind17** [bootstrap-vue/bootstrap-vue#6499]
### Behaviour:
When setting a v-model value with whitespace at the end in an async function on a textarea that has the trim-prop set to true,
the cursor will jump when manually typing in that textarea.

Since this sounds rather complicated, I have created a minimal fiddle to demonstrated my findings here: https://jsfiddle.net/3kovygu9/

### Expected behaviour:
Cursor position should not change when typing.

**Comment by rahulmotwani1996** [comment]
@bLind17  When setting trim property to true the initial data must also be trimmed for whitespaces, for the first time when you type after setting the text from the async method it will remove the newline and space character which trigger the last character at the end of the line so next time the cursor is focus on the last line. try with text which are trimmed before sending it to the component.

**Comment by bLind17** [comment]
Ok, that kind of makes sense.
What's stopping us, however, to trim the text on an async set when it has trailing whitespaces?
