### ISSUE TITLE
Table+Pagination + Filter don't work

### ISSUE THREAD

**Issue by itielshwartz** [bootstrap-vue/bootstrap-vue#650]
You can see it on the docs:
https://bootstrap-vue.js.org/docs/components/table/ has a bug with pagination + filter
-> when doing a filter the number of pages doesn't change.
this happens because when using the filter on the table the actual `items` won't change  -> causing a wrong number of pages.

I found the source of it:
```
                items = items.slice();

                // Apply local filter
                if (filter && !this.providerFiltering) {
                    if (filter instanceof Function) {
                        items = items.filter(filter);
                    } else {
                        let regex;
                        if (filter instanceof RegExp) {
                            regex = filter;
                        } else {
                            regex = new RegExp('.*' + filter + '.*', 'ig');
                        }
                        items = items.filter(item => {
                            const test = regex.test(recToString(item));
                            regex.lastIndex = 0;
                            return test;
                        });
                    }
                }
```

The table inner filter dosn't effect the real items,
Sadly im still new to Vue (and front end) so not sure how to fix...

**Comment by tmorehouse** [comment]
Since pagination controls are one-way props **into**  `<b-table>`, unfortunately it can't update the number of pages in the parent component context.

I have been contemplating creating a new event to emit that returns the number of pages and current page number) when filter is applied, and deactivated.

**Comment by tmorehouse** [comment]
We don't alter (mutate) the original items, as that wouldnt be nice to your parent component.  So we make a shallow copy of the array and manipulate that.

**Comment by itielshwartz** [comment]
@tmorehouse can't the table expose the new items? so we can just use it from outside?
just add it as another data field (shallowCopyItems), and make the shallow copy change the data.shallowCopyItems? 

Sorry can't help more.

**Comment by tmorehouse** [comment]
Vue 2.x only allows a single two-way prop (the v-model), which is currently bound to the value (the currently displayed items).  All other props are one-way (top down).  See http://vuejs.org/v2/guide/migration.html#twoWay-Prop-Option-removed

The only other way to communicate upwards is via emitting events.

**Comment by mosinve** [comment]
It's strange, as i fixed this long ago... 
the reason of bug IMHO, here https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/table.vue#L381
emitted filtered and paged data instead only filtered.

**Comment by tmorehouse** [comment]
@mosinve table `value` (`v-model`) is now only the displayed records (after pagination), as when a row-clicked event occurs it provides the index within the displayed items only.  Maybe we could emit another event that provides the filtered list (if filtered is run local in the b-table.)  It could be emitted just after filtering happens, or it could wait until the end of the _items computed prop to emit it.

**Comment by rdgout** [comment]
@tmorehouse 
FYI 2 way prop option has been brought back since VueJS 2.3.
See here for more information: [.sync modifier](https://vuejs.org/v2/guide/components.html#sync-Modifier)

**Comment by tmorehouse** [comment]
Yeah, I noticed that a while ago.

This might be something we consider in a future release, specifically for props that flow only upwards from the component to the parent.

**Comment by itielshwartz** [comment]
Hi @tmorehouse any estimation when 0.19? 
Would like to have it before deploying my new site.

**Comment by tmorehouse** [comment]
I am not positive on the release date for 0.19.0.  I will check with the @dev team
