### ISSUE TITLE
<b-img-lazy> src promise support (eg. async src)

### ISSUE THREAD

**Issue by patrickpissurno** [bootstrap-vue/bootstrap-vue#6503]
### Is your feature request related to a problem? Please describe...

My images are hosted on AWS S3 and are private, so to access them I have to issue signed urls (and they expire quickly in order to protect sensitive data). I'm currently using `<b-img>` and pre-issuing signed urls for all images, but this is bad for performance because all images are loaded (even when they're not displayed).

It'd be way better to use `<b-img-lazy>` to lazily load those images, but here's the catch: those signed urls are short-lived. So they might expire before the image is to be shown and that would result in a failure.

I tried passing a promise to the `<b-img-lazy>`'s `src` prop, just to find out that it isn't supported at the moment.

### Describe the solution you'd like

It'd be really nice and useful if the `<b-img-lazy>`'s `src` prop supported promises.

### Describe alternatives you've considered

If the `src` prop can't support promises for some reason, any other prop (eg. `src-async`) would do it.

### Additional context

Before opening this issue I looked up for similar issues and found out this one (#1755) that is related (but as it turns out, the feature never got implemented).

Thank you!

**Comment by rahulmotwani1996** [comment]
You can use ref and set the property src when you get response from the backend.
