### ISSUE TITLE
Conflict between @row-clicked and template cell @click

### ISSUE THREAD

**Issue by alexsonnay** [bootstrap-vue/bootstrap-vue#6506]
### Describe the bug

When you have a @row-clicked event and a template cell @click event : both are firing on click of the template cell @click event.

### Steps to reproduce the bug

```
<b-table
      striped
      hover
      :items="items"
      :fields="fields"
      @row-clicked="showDetails"
    >
     <template #cell(actions)="row">    
        <span v-b-tooltip.hover title="Remove">
          <font-awesome-icon
            icon="trash"
            size="lg"
            @click="remove(row.item)"
          />
        </span>            
      </template>
</b-table>

```

Any idea how to prevent @row-clicked from being fired when template cell @click event is fired ?

**Comment by Hiws** [comment]
Try using the `.stop` modifier on your cell click event.
`@click.stop="remove(row.item)"`
