### ISSUE TITLE
How clear the datepicker field after choosing a date?

### ISSUE THREAD

**Issue by AtousaDarabi** [bootstrap-vue/bootstrap-vue#6512]
I'm using datepicker.
Unfortunately of I select a date there is no way to  make it clear.
How can I make it clear?

**Comment by Hiws** [comment]
You have two options.
Either bind a property to `<b-datepicker>`'s v-model, and then use JavaScript to reset the value of said property.
The other option is to use the `reset-button` prop, which adds a `reset` button to the datepicker popup which clears the selected date when clicked by default.

```html
<b-input-group>
  <b-datepicker v-model="date" reset-button></b-datepicker>
  <template #prepend>
    <b-btn @click="date = ''">Clear</b-btn>
  </template>
</b-input-group>
```
