### ISSUE TITLE
b dropdown item error

### ISSUE THREAD

**Issue by alipunisher7** [bootstrap-vue/bootstrap-vue#6516]
I get these warnings when I'm using b-dropdown-item with 'to' property in nuxtjs 
[vue-router] <router-link>'s tag prop is deprecated and has been removed in Vue Router 4
[vue-router] <router-link>'s event prop is deprecated and has been removed in Vue Router 4
actualy I'm not using any tag or event prop !

**Comment by Hiws** [comment]
You might not be using those props, but internally `<b-dropdown-item>` does as it renders a `<nuxt-link>` (which is a `<router-link>` internally IIRC) when using the `to` prop.

So we'd have to update our components which render links to use what ever new API `vue-router` 4 utilizes.
