### ISSUE TITLE
Message box input press `Enter` to confirm

### ISSUE THREAD

**Issue by wenfangdu** [bootstrap-vue/bootstrap-vue#6518]
Vue: `v2.6.12`  
BootstrapVue: `v2.21.2`

Instead of manually clicking `OK`, how to press `Enter` to confirm?

```js
let text
this.$bvModal.msgBoxConfirm(<input vModel={text} />)
```

![image](https://user-images.githubusercontent.com/28700378/112244619-7c141b00-8c8a-11eb-9bde-0156984eaac3.png)

**Comment by adsonvinicius** [comment]
Just put a keyup event on textbox if  keycode == enter (13) then trigger the OK button and close the modal.

**Comment by wenfangdu** [comment]
@adsonvinicius How to _"trigger the OK button and close the modal"_?

**Comment by adsonvinicius** [comment]
In fact you don't have to simulate the OK button (although it's possible), but do whatever it does _(eg. saveData())_, then close.

_`Message Boxes are an extension of the <b-modal> component, and hence support the majority of <b-modal> props (using camelCase format), with the exception of the following props: lazy, static, busy, visible, noStacking, okOnly, okDisabled, and cancelDisabled.`_

```
this.$bvModal.msgBoxOk('Data was submitted successfully', {
          title: 'Confirmation',
          size: 'sm',
          buttonSize: 'sm',
          ref:'my-modal',
          okVariant: 'success',
          headerClass: 'p-2 border-bottom-0',
          footerClass: 'p-2 border-top-0',
          centered: true
});
```

So `onkeyup` event attached to textbox you do: t_his.$refs['my-modal'].hide();

**Comment by Hiws** [comment]
You can supply an `id` in the `options` object, and then use `this.$bvModal.hide('my-modal-id')` inside a `keyup` event, which looks for the press of the `Enter` key.
You can then call a separate method which handles your logic and hide your modal.

### Example
https://codepen.io/Hiws/pen/ExZVExB

**Comment by wenfangdu** [comment]
@adsonvinicius @Hiws Thank you all, I've figured it out:
```js
const modalId = 'modalId'

const ok = () => this.$bvModal.hide(modalId)

let text

this.$bvModal.msgBoxConfirm(<input vModel={text} vOn:keyup_enter={ok} />, {
  id: modalId,
})
```

**Comment by wenfangdu** [comment]
@Hiws Also, how to disable closing on clicking `OK`?

**Comment by Hiws** [comment]
> @Hiws Also, how to prevent closing on clicking `OK` when using message boxes?

Listen for the hide event on root. `this.$root.$on("bv::modal::hide", someMethod);`
When the method is called it's passed a bvEvent parameter, which you can call `preventDefault()` on if you dont want to hide the modal. It also includes the ID of the modal which was closed, and which trigger was used.

Here's a rough example.
https://codepen.io/Hiws/pen/QWdjojm
