### ISSUE TITLE
分页时,不是试用表格，里面显示图片文字怎么做

### ISSUE THREAD

**Issue by 2447382228** [bootstrap-vue/bootstrap-vue#6520]
### Is your feature request related to a problem? Please describe...

A clear and concise description of what the problem is.

**Comment by Hiws** [comment]
Could you provide an English translation of the issue?
As the Google Translated version doesn't make much sense to me.

**Comment by 2447382228** [comment]
那这个要怎么实现尼

**Comment by wenfangdu** [comment]
@Hiws Doesn't make sense for native Chinese either
@2447382228 请使用英语详细描述问题

**Comment by 2447382228** [comment]
How can I click the Pagination button and display the content with pictures and text instead of the content in the form of table

**Comment by Hiws** [comment]
If i understand your question correctly. You want to use `<b-pagination>` for content that isn't `<b-table>`.
You can try looking at this example: https://codepen.io/Hiws/pen/OJXwvMm

如果我正确理解您的问题。 您想将 `<b-pagination>` 用作不是 `<b-table>` 的内容。
您可以尝试查看以下示例：https://codepen.io/Hiws/pen/OJXwvMm

**Comment by Hiws** [comment]
@wenfangdu 
Thanks for the assist, appreciate it

**Comment by 2447382228** [comment]
非常感谢大佬的帮助

**Comment by 2447382228** [comment]
> @wenfangdu
> 谢谢您的协助，不胜感激



> 如果我正确理解您的问题。您想使用非`<b-pagination>`的内容`<b-table>`。
> 您可以尝试查看以下示例：[https](https://codepen.io/Hiws/pen/OJXwvMm) : [//codepen.io/Hiws/pen/OJXwvMm](https://codepen.io/Hiws/pen/OJXwvMm)
> 
> 如果我正确理解您的问题。您想将`<b-pagination>`采用不是`<b-table>`的内容。
> 您可以尝试查看以下示例：[https](https://codepen.io/Hiws/pen/OJXwvMm) : //codepen.io/Hiws/pen/OJXwvMm[](https://codepen.io/Hiws/pen/OJXwvMm)

我想在请教你一个问题，我想在b-card里面的:img-src给图片加样式，这个怎么做尼
