### ISSUE TITLE
b-tags required attribute not rendered to input

### ISSUE THREAD

**Issue by ddzobov** [bootstrap-vue/bootstrap-vue#6524]
`
<b-form-tags :value="value" :placeholder="placeholder" tag-variant="primary" separator=" " remove-on-delete @input="input" :required="required"></b-form-tags>
`

When required set to "true", rendered input don't have a required attribute:
`<input value="" type="text" placeholder="Введите теги через enter или пробел" class="b-form-tags-input w-100 flex-grow-1 p-0 m-0 bg-transparent border-0" id="__BVID__406___input__" style="outline: 0px; min-width: 5rem;">`

bootstrap-vue 2.21.2

**Comment by Hiws** [comment]
The `name` prop is required when using the `required` prop.
For example: `<b-form-tags v-model="value" name="tags" required></b-form-tags>`

This doesn't look like it's mentioned on the docs, so we should update the docs with this information to make it more clear.
