### ISSUE TITLE
b-form-select - Select an option and ability to see different Selectedname/text when selected

### ISSUE THREAD

**Issue by adacapo21** [bootstrap-vue/bootstrap-vue#6529]
Hello team!

I have one question. When we select a choice from a select then normally it is appeared the selected name of the Dropdown. 
Is it possible for us, when an option is selected {{ SelectedName }} to be appeared in the main box like: 
'Sorted by: SelectedName' and when we re-open the dropdown options to be appeared like the way it was before {{ SelectedName }} in the options. 

What we have now this for example:
```
<template>
  <div>
    <b-form-select v-model="SelectedName" :options="options"></b-form-select>
    <div class="mt-3">Selected: <strong>{{ SelectedName }}</strong></div>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        SelectedName : null,
        options: [
          { value: null, text: 'Please select an option' },
          { value: 'name', text: 'This is First option' },
          { value: 'date one', text: 'Selected Option' },
          { value: 'date two', text: 'This is an option with object value' },
        ]
      }
    }
  }
</script>
```

What I want is when an option is selected to be appeared like this: 
![image-20201216-102937 (2)](https://user-images.githubusercontent.com/9395707/112745101-9281e580-8fae-11eb-86f9-85f419e00efa.png)

How this can be possible?

**Comment by Hiws** [comment]
I don't believe this is possible with a native `<select>` (which `<b-form-select>` is).
You could instead use `<b-dropdown>` to accomplish what you want.

```html
<b-dropdown>
  <template #button-content>
    Sorted by: {{ selectedName ? selectedName.text : 'None' }}
  </template>
  <b-dropdown-item v-for="option in options" @click="selectedName = option">
    {{ option.text }}
  </b-dropdown-item>
</b-dropdown>
```

**Comment by adacapo21** [comment]
Hello Hiws! 

In that case is it possible to use this dropdown to sort a table? 
If for example replace b-form-select with dropdown?
PS: This is pretty much related to this code you have written in a previous issue. 
[Check Here](https://codepen.io/Hiws/pen/WNRrdEB)

Thanks again.

**Comment by Hiws** [comment]
Yes.

<https://codepen.io/Hiws/pen/dyNXwXM>

**Comment by adacapo21** [comment]
Thanks a lot again, Hiws!
