### ISSUE TITLE
Eslint config

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#653]
Just thought, why BV project haven't an eslint config? 
If there is some mean reasons for this?
If not, i create one at my fork and ready to make a PR :)

**Comment by mosinve** [comment]
Also, there was claims about .editorconfig.js, which could be usefull to set up the same enviroment for all involved people

**Comment by alexsasharegan** [comment]
I could be wrong, but I think there are a couple plugins required to get eslint running in a vue environment.

# Dev Dependencies
```json
{
    "eslint": "^4.1.1",
    "eslint-plugin-html": "^3.0.0",
    "eslint-plugin-vue": "^2.1.0",
}
```

# Eslint Config
```json
{
    "root": true,
    "env": {
        "browser": true,
        "node": true
    },
    "plugins": [
        "vue",
        "html"
    ],
    "settings": {
        "html/html-extensions": [
            ".html",
            ".vue"
        ]
    },
    "parserOptions": {
        "ecmaVersion": 2017,
        "sourceType": "module",
        "ecmaFeatures": {
            "impliedStrict": true,
            "experimentalObjectRestSpread": true,
            "jsx": true // just in case?
        }
    },
    "globals": {
        "Tether": true,
        "Promise": true
    }
}
```

**Comment by mosinve** [comment]
Yep, plugins are already at `package.json`:
```
    "eslint-config-vue": "^2.0.2",
    "eslint-plugin-html": "^3.0.0",
    "eslint-plugin-vue": "^2.1.0",
```
need to add Eslint self

As for me, i have installed ESlint and plugins globally, and use PHPStorm's ability to run ESLint checks

**Comment by alexsasharegan** [comment]
The storm! That ide will configure so much for you it's crazy. I just enjoy using VSCode as a change of pace (and it's just brighter and happier to me). I storm it up when I'm PHP though.

Anyways, 👍 for this.

**Comment by mosinve** [comment]
Created PR #654 
Feel free to check .eslint.config.js to add/remove rules. Currently it has many rules enabled))

**Comment by alexsasharegan** [comment]
Since this is merged, I'm going to go ahead and close this.
