### ISSUE TITLE
no-wheel form-input bug (unable to preventDefault inside passive event listener)

### ISSUE THREAD

**Issue by nick4414** [bootstrap-vue/bootstrap-vue#6531]
### Describe the bug

If I have an **b-form-input** and add the property **no-wheel** to it and I try to scroll when the input is focussed, I get this error in the browser console:

```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
stopEvent @ app.js:52144
stopWheel @ app.js:15778
```

Example code to reproduce the issue is:

` <b-form-input placeholder="XXX" type="number" v-model="XXX" no-wheel required/>`

### Versions

**Libraries:**

- BootstrapVue: 2.21
- Bootstrap: 4.5.0
- Vue: 2.6.12

**Environment:**

- Device: Laptop
- OS: Windows
- Browser: Chrome
- Version: 89

**Comment by monas** [comment]
Saw the same issue, but took a while to figure out what is casing this. Then just tried to edit live dox page and got this one
![image](https://user-images.githubusercontent.com/3097553/113240382-489e4580-92b5-11eb-8a4a-cfd4e19ca9d7.png)

**Comment by nick4414** [comment]
Hey, thanks for your answer. So did you figure out what is causing this and how to solve the issue ?

**Comment by monas** [comment]
@nick4414 at the moment I just stopped using no-wheel at all. I have taken a quick look into the source 
![image](https://user-images.githubusercontent.com/3097553/113467242-7d8fd100-944a-11eb-9287-d1c4addca321.png)
I am not an expert on using wheel event but it looks little bit strange that this event is caught on document. I would try to use that event on input field itself if that is possible. Now on mouse wheel blurs the input and I think it shouldn't. Unfortunately I am too busy to dig deeper ant test this out :( But I would start here.

**Comment by nick4414** [comment]
I found a workaround in #1872.
`<b-form-input type="number" @mousewheel.native="$event.preventDefault()"/>`

Unfortunately it still doesn't really solve the issue with "no-wheel", but works for now.
