### ISSUE TITLE
bootstrap-vue <b-form-datepicker> custom date format 

### ISSUE THREAD

**Issue by edijsci** [bootstrap-vue/bootstrap-vue#6538]
Hi!
I use <b-form-datepicker> form in my project
with :date-format-options="{ year: 'numeric', month: 'numeric', day: 'numeric' }".
Date field displays format in yyyy.MM.dd, is there possible to change date format to dd.MM.yyyy?

**Comment by Hiws** [comment]
You could use the `da` locale which would display `5.4.2021` for the 5th of April, 2021.

**Comment by tghelere** [comment]
> You could use the `da` locale which would display `5.4.2021` for the 5th of April, 2021.

what do you mean by "da"?

**Comment by Hiws** [comment]
> what do you mean by "da"?

It's one of the locales you can pass to the `locale` prop.
<https://bootstrap-vue.org/docs/components/form-datepicker#internationalization>
