### ISSUE TITLE
Radio and Checkbox Elements v-model Triggers Computed Property Setter

### ISSUE THREAD

**Issue by ryannmedina** [bootstrap-vue/bootstrap-vue#6539]
We're using a checkbox (or radio) form inputs and binding the v-model value to a computed property. The value is passed as prop. We also use a a setter to update that value in the store. After everything is mounted the prop gets updated (via api), which in turn updates the computed property. The problem is when the computed property getter is updated, the setter is triggered.  
  
Here's a simple example:   
```javascript
export default Vue.component("example", {
   template: `
      <div>    
         <b-form-checkbox v-model="value">Label Text</b-form-checkbox>	
      </div>
   `,
   props: ['props'],
   computed: {
      value: { 
         get: function () { return this.props.value; },
         set: function (val) {
            this.$store.dispatch('updateValueInStore', val);
         }
      }
   }
});
```
  
In this case if the `props.value` is updated by the parent the computed property is triggered and then the computed setter is triggered.  
  
I also put together a simple Vue Cli environment/example to mimic the behavior here: [https://github.com/ryannmedina/vue-bootstrap-test](https://github.com/ryannmedina/vue-bootstrap-test). This includes a text input, which works as expected.

**Comment by rahulmotwani1996** [comment]
Instead of using computed property as prop you can Watch the property, or directly attaching the store value using mapState can also solve the issue. using get / set will cause the issue whenever the value will get updated

**Comment by ryannmedina** [comment]
Thanks for the idea @rahulmotwani1996! We ended up just using plain HTML checkboxes/radio buttons for the time being. They work as expected.

**Comment by belluzj** [comment]
I have the same issue, with version 2.21.2.

**Comment by andreassoegaard** [comment]
Same issue. Version 2.21.2 as well
