### ISSUE TITLE
Tool tip gets stuck on disabled button

### ISSUE THREAD

**Issue by jamesmudd** [bootstrap-vue/bootstrap-vue#6540]
### Describe the bug

If you have a button with a tool tip , if clicking the button disabled it the tool tip becomes stuck.

### Steps to reproduce the bug

1. Go to https://codepen.io/jamesmudd/pen/KKaypPK?editors=1111
2. Click on the "undo" button with tooltip
3. The button becomes disabled with a stuck tooltip

### Expected behaviour

The tooltip should close as normal

### Versions

**Libraries:**

- BootstrapVue: 2.21.1
- Vue: 2.6.11

**Environment:**

- Device: PC
- OS: Linux
- Browser: Chrome + Firefox
- Version: Latest

### Demo link

https://codepen.io/jamesmudd/pen/KKaypPK?editors=1111

**Comment by Hiws** [comment]
Refer to this section as to why this is happening
https://bootstrap-vue.org/docs/directives/tooltip/#disabled-elements

Here's the workaround
https://codepen.io/Hiws/pen/gOgXagP

**Comment by jamesmudd** [comment]
Ok thanks for the workaround. My understanding of that is when you want a tooltip on a disabled element. I don't really i'm happy for the tooltip to be shown only when the button is active? The bug here is the existing tool tip is never closed?

**Comment by jamesmudd** [comment]
In addition the workaround isn't very nice in button groups e.g. https://codepen.io/jamesmudd/pen/BapmoxR?editors=1011

**Comment by Hiws** [comment]
You would have to manually hide the tooltip then, when you disable your button.
<https://codepen.io/Hiws/pen/gOgXagP>

**Comment by jamesmudd** [comment]
Yes this approach works. Thanks
