### ISSUE TITLE
The Documentation Website is very different from the vibes when opening the bootstrap v5 docs website.

### ISSUE THREAD

**Issue by BroJenuel** [bootstrap-vue/bootstrap-vue#6542]
I think it's a good idea to follow default styles from the bootstrap website.. looking at the website it's very different, the header colors and etc. Look at the images below.

![image](https://user-images.githubusercontent.com/31676163/114259400-3e402200-9a00-11eb-8bfe-b6f1a04d15c4.png)
![image](https://user-images.githubusercontent.com/31676163/114259408-45ffc680-9a00-11eb-9e47-b8bb8e90c981.png)

this is when users look at components,
![image](https://user-images.githubusercontent.com/31676163/114259427-721b4780-9a00-11eb-95ef-3bd75d5354cc.png)
![image](https://user-images.githubusercontent.com/31676163/114259432-78112880-9a00-11eb-9f30-4e36f8c8872b.png)

**Comment by Hiws** [comment]
That's a fair point.
The current docs were styled after the Bootstrap v4 docs, which you can see here: https://getbootstrap.com/docs/4.4/getting-started/introduction/ and haven't been updated to fit the v5 theme as of yet.
I think it would make better sense to update the docs, when we ship bootstrap v5 support
