### ISSUE TITLE
b-carousel-slide img on nuxt

### ISSUE THREAD

**Issue by maulayyacyber** [bootstrap-vue/bootstrap-vue#6543]
i have problem when showing image on `b-carousel-slide` on nuxt js, this code i used :

```
<template>
  <div>
    <b-container class="mt-3">
      <b-carousel id="carousel-fade" style="text-shadow: 0px 0px 2px #000" fade indicators img-width="1024"
        img-height="300">
        <b-carousel-slide v-for="slide in sliders" :key="slider.id" :img-src="slider.image"></b-carousel-slide>
      </b-carousel>
    </b-container>
  </div>
</template>

<script>
  export default {
      async asyncData({ $axios }) {

      //fetching slider
      const sliders = await $axios.$get('/api/public/sliders')

      return {
        sliders
      }
    }
    
  }
</script>
```

thanks very much

**Comment by Hiws** [comment]
> i have problem when showing image

What is the problem actual problem?

Only thing i can see is that you've typed `v-fo` and not `v-for`.

**Comment by maulayyacyber** [comment]
Hi @Hiws im sory for the example code typo, my problem when i use `:img-src=` and dont show the image, when i use `img-src` the image showing success, but i dont use slider.image` on `img-src`

understand my quertion ? 

thanks very much

**Comment by Hiws** [comment]
Is `slider.image` a full path, or a relative path?

**Comment by maulayyacyber** [comment]
hai @Hiws my image is full path from api response

**Comment by Hiws** [comment]
and are you sure `slider.image` prints out the correct information?
Have you tried inspecting the dom to see what's rendered in the DOM?

or just doing this to check the data.
```html
<pre>{{ slider }}</pre>
```

**Comment by maulayyacyber** [comment]
Yah my response correct, problem when print the `slider.image` on attribute `img-src`, mybe the `slider.image` has read as variable.

if i use `:img-src` same issue to, please help me about this
