### ISSUE TITLE
When using b-overlay with no-wrap in b-modal the modal body is not visible

### ISSUE THREAD

**Issue by kalitk0** [bootstrap-vue/bootstrap-vue#6544]
### Describe the bug

When using b-overlay with no-wrap in b-modal the modal body is not visible

### Steps to reproduce the bug

1. Go to https://codesandbox.io/s/friendly-worker-evcyd
2. Click on "Open Modal"
3. See error

### Expected behavior

To see the modal body

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 3.0.11

**Environment:**

- Device: Mac
- OS: macOS Big Sur 11.2.3
- Browser: Chrome
- Version: 89.0.4389.114

### Demo link

https://codesandbox.io/s/friendly-worker-evcyd

**Comment by Hiws** [comment]
I've answered your question on stackoverflow.
<https://stackoverflow.com/a/67043447/8397974>
