### ISSUE TITLE
selectRow() not working

### ISSUE THREAD

**Issue by Osolemio44** [bootstrap-vue/bootstrap-vue#6546]
### Describe the bug
![image](https://user-images.githubusercontent.com/55595063/114540368-b94e4600-9c55-11eb-8060-8b9c64ffd998.png)

I have 2 tables. the first one is showing data depending on the "select" that is above.
 When you select some rows in the first table and hit the save button, it saves those rows in the table on the right.
 What I want to achieve is that when I change the "select" above and take out the new list, it marks the rows from the left table  as selected that are already in the right table. I have followed the example that you have in the documentation but it does not work. It doesn't give me any kind of error, it just ignores it

### Steps to reproduce the bug

1. change the "select"from above

### Expected behavior

have rows in the table on the left marked as selected when they are duplicated in the table on the right

### Versions

**Libraries:**

- "bootstrap-vue": "^2.21.2",
- "vue": "^2.6.12",

**Environment:**

- Device: [PC]
- OS: [Windows 10 pro]
- Browser: [Chrome]
- Version: [89.0.4389.114]

### Demo link
code of the "select" that populate the table:

```
              <b-input-group size="sm" prepend="Periodo" class="m-2">
                <b-form-select
                  id="grfPeriodo"
                  text="Elegir periodo"
                  v-model="grfPeriodos.selected"
                  :options="grfPeriodos.options"
                  @change="periodoAcciones()"
                ></b-form-select>
              </b-input-group>
```
code of the left table: 

```
 <b-table
              id="grfAnaSelector"
              ref="grfTblSelector"
              :items="grfTableSelec.tableConf.items"
              :fields="grfTableSelec.tableConf.fields"
              selectable
              select-mode="range"
              hover
              small
              @row-selected="onRowSelectedTableSelect"
            ></b-table>
```
code of the method that is suposed to mark as selected the rows:

```
periodoAcciones() {
      this.filterAnalogs();
     
      if (this.grfTableSelec.tableConf.items.length > 0) {
        this.grfTableSelec.tableConf.items.forEach((senial, index, array) => { // grfTableSelec is the table from the left
         
          let alreadySelected = this.grfTableGrafica.tableConf.items.some(    // grfTableGrafica is the table from the right
            (grafSenial) =>
              grafSenial.uuidAnalogin == senial.uuidAnalogin &&
              grafSenial.period == senial.period
          );

         
          if (alreadySelected) {
            
            this.$refs.grfTblSelector.selectRow(index);  // <=+++ doesnt work but dont give any error
           //  this.$refs.grfTblSelector.selectAllRows(); // doesn't work either
            
          }
        });
      }
      
    },
```

full code of the component component :[https://jsfiddle.net/pepe333/42nd8bqk/2/]( https://jsfiddle.net/pepe333/42nd8bqk/2/ )
full code of the module's component: [https://jsfiddle.net/pepe333/5rnoaduh/1/](https://jsfiddle.net/pepe333/5rnoaduh/1/)
full code of my javascript tools file : [https://jsfiddle.net/pepe333/18g3zmuL/](https://jsfiddle.net/pepe333/18g3zmuL/)
data sample: [https://jsfiddle.net/pepe333/48n7zyw2/2/](https://jsfiddle.net/pepe333/48n7zyw2/2/)

**Comment by Hiws** [comment]
I can take a look at it if you create a simplified reproduction of the issue.
