### ISSUE TITLE
[docs, playground] Examples don't load in IE11

### ISSUE THREAD

**Issue by hydraheim** [bootstrap-vue/bootstrap-vue#655]
The playground for checking components live does not work at all in IE 11 (tested): https://bootstrap-vue.js.org/play/ . Same applies for all the doc pages, the examples will not load.

The spesific error is:

```
SCRIPT5: No access.
File: github-btn.html, Line: 1, Column: 1
```

This seems to relate to [no access and CORS](https://docs.microsoft.com/en-us/scripting/javascript/misc/access-is-denied) in IE11. This could be fixed by updating the request to accept CORS or using JSONP.

**Comment by mosinve** [comment]
I have another error: "'Promise' is undefined"
It seems, docs site needed Promise Polyfill, such as https://babeljs.io/docs/usage/polyfill/

**Comment by mosinve** [comment]
access denied is for file github-btn.html - which isn't critical for working state of docs website

**Comment by tmorehouse** [comment]
This error is related to the web workers proces (caching).  I see it in chrome as well, but it doesn't affect the usage of the site.

The actual issue, is related to some of hte features in IE 11 (missing many of the `Object.*` and `Array.*` methods.  PR #658 may address this issue by providing some helper functions for missing methods in IE 11
