### ISSUE TITLE
using sort-icon-left, right sort icons still present

### ISSUE THREAD

**Issue by sasproul** [bootstrap-vue/bootstrap-vue#6551]
### Describe the bug

see attached
sort icons are present on the left and right side
I feel like my bootstrap.css and bootstrap-vue.css files might be the issue but i cant find any updates on the web

### Steps to reproduce the bug

see vue script attached

once introducing sort-icon-left expect the right hand sort icons to go away

### Versions

**Libraries:**
main.js
import { BootstrapVue, IconsPlugin } from 'bootstrap-vue';
// Bootstrap vue imports, Import Bootstrap an BootstrapVue CSS files (order is important)
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'

Vue.use(BootstrapVue);
Vue.use(IconsPlugin);

"bootstrap": "^4.4.1",
"bootstrap-vue": "^2.13.0",
 "vue": "^2.6.12",

**Environment:**
Google Chrome is up to date Version 90.0.4430.72 (Official Build) (64-bit)

![sortLeftIconIssue](https://user-images.githubusercontent.com/43613685/114913408-c5b5d880-9de6-11eb-881e-2fdf70e9c6de.png)

[sampletable.txt](https://github.com/bootstrap-vue/bootstrap-vue/files/6320107/sampletable.txt)

**Comment by Hiws** [comment]
Hard to say without a reproduction.
But both your Bootstrap and BootstrapVue versions aren't up to date.
Try updating both. Bootstrap to `4.5.3` and BootstrapVue to `2.21.1`.

**Comment by sasproul** [comment]
Hi there
see attached for image
I just updated to Vue.js 2.6.12, Bootstrap 4.6.0 and Bootstrap Vue 2.21.2
and I still have the problem where, if I add 'sort icon left' and make the
column sortable, the sort icon appears on both the left and the right side,
and clicking on either sort icon not only sorts the column but both icons
behave the same, except that the right icon looks different than the left
icon.  I do not have poppers or portal vue installed and I didnt see that
was a dependency?
Please advise

Stacey
<b-table
          responsive
          sticky-header
          head-variant="dark"
          striped
          hover
          selectable
          :items="taskList"
          :fields="fields"
           sort-icon-left
          style="font-size: 10px"
          @row-clicked="expandAdditionalInfo"
        >
fields: [
        // pick which headers we wantto show in the table on the gui
        {
          key: "goal",
          label: "Goal",
           sortable: true,
        },
        {
          key: "assignee",
          label: "Assigned To",
        //  sortable: true,
        },
        {
          key: "trackId",
          label: "Target",
        //  sortable: true,
        },
        {
          key: "ruleId",
          label: "Rule ID",
        //     sortable: true,
        },
        {
          key: "value",
          label: "Value",
         //  sortable: true,
        },
        {
          key: "state",
          label: "Status",
        //  sortable: true,
          _showDetails: false,
        },

**Comment by Hiws** [comment]
I don't see any images attached.
I'm not sure GitHub can pick them up when replying to an email. 
Try going to the Issue instead and writing a reply there, you should be able to add an image then.

Here's how it looks if i use your code on the docs playground:
![chrome_YToYDpjAEN](https://user-images.githubusercontent.com/7057431/116068729-d7bb3500-a68a-11eb-80a5-7ff0e5f4f740.png)

As i suggested before, inspect the table in your browser using your browsers dev tools, to see where the extra icons are coming from. As they are generated using CSS.

BootstrapVue hasn't been updated for Bootstrap 4.6.0, so you might experience some issues if you use that version. (though this one is probably not one of them)

**Comment by sasproul** [comment]
thanks for the email reply, see image that wouldnt send in email 
![sortIssue](https://user-images.githubusercontent.com/43613685/116071519-9f4c3480-a653-11eb-8f3e-950c52cf7f78.png)
attached to this comment

**Comment by sasproul** [comment]
something about sort icon left 'after'  How eaxctly do i get rid of that?

![sort-icon-left-after](https://user-images.githubusercontent.com/43613685/116072049-3dd89580-a654-11eb-9621-c2ac9f975af7.png)

**Comment by sasproul** [comment]
![Uploading sort-icon-left.png…]()

**Comment by sasproul** [comment]
![sort-icon-left](https://user-images.githubusercontent.com/43613685/116072343-90b24d00-a654-11eb-85b1-44db3f6aebb7.png)

**Comment by sasproul** [comment]
thanks, i just uploaded some images.  How do I get rid of that extra css?

**Comment by Hiws** [comment]
My best guess would be you either have some custom CSS which is adding that icon, or you're importing an older version of BootstrapVue which utilized ::before/::after to add the icon instead of as a background image as the newer version does.

You'll have to inspect the element and check where the `::after` CSS is coming from.

**Comment by sasproul** [comment]
I have no custom css in the project
package.json:
"vue": "^2.6.12",
"bootstrap": "^4.6.0",
"bootstrap-vue": "^2.21.2",

I do not have poppers nor portal vue since the documentation seemed to indicate I didn't need it.

see attached for html that is generated, the correct class definition is there.  If I click on the arrow to the left or right of the column header it drops me at that same th row html
![html](https://user-images.githubusercontent.com/43613685/116081422-daecfb80-a65f-11eb-9c6c-550b57b96cea.png)
 column header for goal
 
this is what I am seeing for the css

.table.b-table > thead > tr > [aria-sort="descending"]:after, .table.b-table > tfoot > tr > [aria-sort="descending"]:after {
    content: "\f0dd";
}
<style>
.table.b-table > thead > tr > [aria-sort="ascending"]:after, .table.b-table > tfoot > tr > [aria-sort="ascending"]:after, .table.b-table > thead > tr > [aria-sort="descending"]:after, .table.b-table > tfoot > tr > [aria-sort="descending"]:after {
    opacity: 1;
}
<style>
.table.b-table > thead > tr > [aria-sort]:after, .table.b-table > tfoot > tr > [aria-sort]:after {
    content: "\f0dc";
    font-family: "FontAwesome";
    display: block;
    position: absolute;
    top: 0px;
    bottom: 0px;
    right: 0px;
    font-size: 0.6rem;
    height: 0.8rem;
    opacity: 0.3;
    margin: auto;
    vertical-align: middle;
}
<style>
*, *::before, *::after {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

**Comment by sasproul** [comment]
see attached....Interstingly enough, when I copied in the sort icon alignment example and ran it, I didnt see any left arrow placement.  
 <b-table
      :items="items"
      :fields="fields"
      :sort-by.sync="sortBy"
      :sort-desc.sync="sortDesc"
      sort-icon-left
      responsive="sm"
    ></b-table>
![exampleLeftSort](https://user-images.githubusercontent.com/43613685/116083998-ebeb3c00-a662-11eb-8714-e0b5bb64d187.png)

**Comment by Hiws** [comment]
I don't know your project, or how it's setup. So not sure what else i can do, as I'm out of suggestions.
You'll have to look through your project to see where the extra icons are coming from, as i suspect it's something to do with your setup.

Here's the table SCSS files which generates the CSS for the table icons.
https://github.com/bootstrap-vue/bootstrap-vue/blob/v2.21.2/src/components/table/_table.scss
The only mention of `::after` and `::before` i can see looks to be in relation to the `stacked` mode. 

If you can create a reproduction of the issue, i can take another look.

**Comment by sasproul** [comment]
Thanks, I understand it's difficult to troubleshoot an issue when you cant reproduce it.  I found the file _table.scss
see attached, are these dates really correct?  1985?
![scssFiles](https://user-images.githubusercontent.com/43613685/116090637-b433c280-a669-11eb-983e-ecbf640bc5a5.png)

**Comment by sasproul** [comment]
okay, so the entire area to the left and right of the label on the column is is sensitive for sorting.  If you go to the Sort icon alignment example on the bootstrap vue example page and click to the left and right of the arrow you can sort.  So my issue is really that the right icon isn't being removed when I add the sort-icon-left tag

**Comment by sasproul** [comment]
this ended up being the result of another having changed our local style guide that altered the way sticky-header was working
