### ISSUE TITLE
Custom icon for divider in Breadcrumbs instead of default slash

### ISSUE THREAD

**Issue by ManasMadrecha** [bootstrap-vue/bootstrap-vue#6554]
### Is your feature request related to a problem? Please describe...

I am using Nuxt with Content module.

Currently, I did not find any option to change `/` present inside Breadcrumbs components to some other text or icon.

### Describe the solution you'd like

- To be able to add custom icons or text or emojis like in Vuetify. Basically, add anything to the divider using slot.

**Comment by Hiws** [comment]
The current breadcrumb dividers are controlled via CSS.
The default divider can be configured by changing the `$breadcrumb-divider` SCSS variable.
<https://github.com/twbs/bootstrap/blob/a716fb03f965dc0846df479e14388b1b4b93d7ce/scss/_variables.scss#L1065>

Or you can overwrite it with normal CSS.

I'll keep the issue open as a feature request for a potential slot, but the above solution is the current way of changing it.
