### ISSUE TITLE
B-tab mounted precedes destroyed for each b-tab except the last one

### ISSUE THREAD

**Issue by vgerasimova** [bootstrap-vue/bootstrap-vue#6555]
I have tab control with dinamically generated tabs. I am using it in VUE application.
`<b-card >
		<b-tabs>
			<b-tab v-for="wf in workflows">
                             <MyComponent :key="'xxx_' + wf.id" />
                        </b-tab>
		</b-tabs>
	</b-card>`
When I open more than one tabs, for example 4, the following happens when navigating between the tabs.
When navigating between the tabs from index 0 to index 3(to the bigger index), MyComponent.destroyed for the currentTab is called first,  and then MyComponent.mounted for the next tab that is selected. 
The other way around, when navigating from last to the first, MyComponent.mounted for the next tab that is being selected is called first and then MyComponent.destroyed for the currentTab.

**Comment by Hiws** [comment]
It looks like you are correct *if* you use the `lazy` prop on `<b-tabs>`.
However, in your code i don't see the `lazy` prop being used.
Here's an example showing the problem when the  `lazy` prop is present.
<https://codepen.io/Hiws/pen/xxgQxpN>

Could you provide a reproduction of the issue?
Might also help if you describe *why* this is an issue for you.

**Comment by vgerasimova** [comment]
I am using lazy indeed. Just didn't put it in the example. I didn't expect it to be the issue
My component is complicated Canvas, that has a diagram in and has to listen for $root events. When the destroy comes after the mounted, $root.off deletes all hooks. However I just found that i can attach with $root.on i a vue.nextTick, so it goes after the destroy. Just seems to me as a hack.

**Comment by Hiws** [comment]
Indeed if you run `$off` with no arguments given, it will remove **all** listeners, however you can provide arguments to only remove specific events, like the one registered specifically in the component that is being destroyed.

<https://vuejs.org/v2/api/#vm-off>
> If both event and callback are given, remove the listener for that specific callback only.
