### ISSUE TITLE
The library is no longer maintained.

### ISSUE THREAD

**Issue by Hiws** [bootstrap-vue/bootstrap-vue#6557]
Hello everyone, figured it was time to give an update.

### General update

As most people have probably noticed, the project has not received any updates or PR merges in the past couple of months.

So i figured it was about time to say, that the project currently has no active maintainers left.
I had hoped they would announce something, but sadly it appears i have to do it. 
As I don't feel it's fair to keep the users of BootstrapVue waiting any longer for updates/features that aren't coming.

### The team

The project was originally started by @pi0, however it was later taken over @tmorehouse. So that pi0 could focus entirely on Nuxt. @jackmu95 later joined tmorehouse.
Sadly however, tmorehouse disappeared last year due to personal reasons which left jackmu95 alone to maintain the project (with the help of your alls contributions, so thanks for those).
However, with the recent project aiming to add Vue 3 support while also handling PRs/Issues, personal life and work it appears he ended up being burned out. Which is completely understandable.

Which now means that the project has no active maintainters left. 
 
### What's the future for the project?
Honestly I'm not sure. 
The best case would of course be that either the old maintainers return, or new ones step up to continue the project.
Alternatively, there's talk about creating a new project which is being discussed over at this issue: https://github.com/bootstrap-vue/bootstrap-vue/issues/6556

------

Of course, I've taken the liberty to talk on behalf of the core team, however given the silence I feel i had to.
If any of the core team wish to add a comment or an update, they're more than welcome.
But for now i would consider the project *dead*.

And sorry for the less than optimal post, but I've never been good at writing up stuff like this 😄

**Comment by ghenry** [comment]
This is a shame as we're a sponsor too https://github.com/bootstrap-vue/bootstrap-vue#sponsors

**Comment by ghenry** [comment]
I miss seeing emails from github notifications with the names:

Troy Morehouse 
Jacob Müller

**Comment by jackmu95** [comment]
Sorry for my absence in the last few weeks.
There is/was a lot going on in my private/work life and I had to take a break from BootstrapVue.

@Hiws did a great job in the meantime managing the community!

BootstrapVue is still maintained and I will start with contributions in the next few days.
I will also give an update on Vue 3 and Bootstrap 5 support, but there will not be concrete ETAs for when they will happen.
