### ISSUE TITLE
Jumbotron not reacting to resize breakpoints

### ISSUE THREAD

**Issue by stitch** [bootstrap-vue/bootstrap-vue#6563]
### Describe the bug

A jumbotron title goes outside of the screen on mobile devices, while in bootstrap it just scales.

### Steps to reproduce the bug

Resize your window on: https://bootstrap-vue.org/docs/components/jumbotron
Example:
![image](https://user-images.githubusercontent.com/333846/115770523-1dd37880-a3ad-11eb-8a58-5e3736c114f6.png)

### Expected behavior

Resize your window on:
https://www.w3schools.com/bootstrap/bootstrap_jumbotron_header.asp

See the title getting smaller:
![image](https://user-images.githubusercontent.com/333846/115770634-3ba0dd80-a3ad-11eb-9148-3030734fe614.png)

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.12

**Environment:**

- Device: Mac
- OS: Mac OS Big Sur
- Browser: Firefox
- Version: 88.0

**Comment by Hiws** [comment]
The ones on the actual Bootstrap docs does the same.
<https://getbootstrap.com/docs/4.5/components/jumbotron/>

Also, the W3 link utilizes Bootstrap 3, not Bootstrap 4.

**Comment by stitch** [comment]
> Looks like the ones on the actual Bootstrap docs does the same.
> https://getbootstrap.com/docs/4.5/components/jumbotron/
> 
> Also, the W3 link utilizes Bootstrap 3, not Bootstrap 4.

And as such bootstrap-vue will follow. This issue is thus in the wrong repo.
