### ISSUE TITLE
Tooltip hover different from Bootstrap (Hovering over the tooltip keeps the tooltip open)

### ISSUE THREAD

**Issue by martijnhartlief** [bootstrap-vue/bootstrap-vue#6564]
### Describe the bug

Hovering over the tooltip keeps the tooltip open, the original bootstrap closes the tooltip as soon as you move out of the element that triggered it, even if you hover over the tooltip itself. BootstrapVue keeps the tooltip open.

### Steps to reproduce the bug

Compare the example page for the tooltip and the behavior for the tooltip on hover is different

Original: https://getbootstrap.com/docs/4.6/components/tooltips/#examples
BootstrapVue: https://bootstrap-vue.org/docs/components/tooltip

### Expected behavior

Close the tooltip even if you hover out of the element while hovering over the tooltip.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.11

**Environment:**

- Device: PC
- OS: Ubuntu 20.04.2
- Browser: Chrome
- Version: 89.0.4389.114

### Demo link

https://bootstrap-vue.org/docs/components/tooltip

### Additional context

The bug occurs in the documentation examples and real projects

**Comment by Hiws** [comment]
You need to use the `noninteractive` prop to restore the Bootstrap default behavior.
<https://bootstrap-vue.org/docs/components/tooltip#noninteractive-tooltips>

**Comment by martijnhartlief** [comment]
Imho that should be the default, but sure.

**Comment by Hiws** [comment]
You can set it as default using the BootstrapVue configuration.
<https://bootstrap-vue.org/docs/reference/settings#default-configuration>

**Comment by ddweber** [comment]
@Hiws Does this approach also work for directive usage like 'v-b-tooltip'?
