### ISSUE TITLE
b-form-input disabled

### ISSUE THREAD

**Issue by happilymarrieddad** [bootstrap-vue/bootstrap-vue#657]
Hey Guys, 

Is there a way to pass in disabled? I need a way to dynamically disabled a form input. Something like this
```
b-form-input(v-model='name',:disabled='!ready')
```

I hope that makes sense. Thanks!

**Comment by tmorehouse** [comment]
Yes, `<b-form-input>` accepts the disabled prop. The value it binds to must be a Boolean `true` or `false`.

https://bootstrap-vue.js.org/docs/components/form-input

```js
b-form-input(v-model='name',:disabled='!Boolean(ready)')
```

The value must be truthy/falsey in the following sense:
- Falsey: `null`, `false`, `undefined`
- Truthy: `true`

**Comment by happilymarrieddad** [comment]
Ok, thanks!

**Comment by happilymarrieddad** [comment]
I works when I wrap it in the Boolean() func

**Comment by tmorehouse** [comment]
Here is the official Vue.js documentation on this:

https://vuejs.org/v2/guide/migration.html#Truthiness-Falsiness-with-v-bind-changed
