### ISSUE TITLE
Tables - Pagination jumps to first page when trying to show details in filtered state

### ISSUE THREAD

**Issue by HendrikSchmidt** [bootstrap-vue/bootstrap-vue#6571]
### Describe the bug

When working with a filtered table, the pagination will jump back to the first page when clicking on `Show Details` of a row on a different page.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.org/docs/components/table#complete-example
2. Filter table with `e`
3. Go to second page
3. Click on `Show details` of a row
4. Be sent back to first page

### Expected behavior

The table should stay on the same page and show the row details.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2

**Environment:**

- Device: MacBook Pro
- OS: macOS Big Sur
- Browser: Chrome
- Version: 90

**Comment by Dedock** [comment]
It's expected result
It happens because we added handler `onFiltered`  or `filtered` event of table
Also, we have to do it to render proper pagination

**Comment by HendrikSchmidt** [comment]
I disagree: As a user, this isn't the expected result for me. If I click to see row details, I want to see them instead of being taken back to the first page. I understand that there might be a technical reason for it at the moment, but it honestly feels like a bug.
