### ISSUE TITLE
BOverlap Component: Possibility to choose to use the spinner

### ISSUE THREAD

**Issue by fech-dev** [bootstrap-vue/bootstrap-vue#6572]
### Is your feature request related to a problem? Please describe...
In the overlap component, insert the option to use or not the spinner.
For example, using it as a backdrop (like modal) 
when you have a sliding sidebar, sometimes the spinner is not necessary.

### Describe the solution you'd like
Make it configurable with a prop like use-spinner with values true/false
```vue
<template>
  <b-overlap use-spinner="false"></b-overlap>
</template>
```
or
```vue
<template>
  <b-overlap no-spinner></b-overlap>
</template>
```

**Comment by Hiws** [comment]
You can set the `spinner-type` prop to `null` or an empty string, or even just `true` as in the example below.

```html
<b-overlay show spinner-type>
  <b-card>
    Hello World
  </b-card>
</b-overlay>  
```

**Comment by fech-dev** [comment]
> You can set the `spinner-type` prop to `null` or an empty string, or even just `true` as in the example below.
> 
> ```
> <b-overlay show spinner-type>
>   <b-card>
>     Hello World
>   </b-card>
> </b-overlay>  
> ```
> 
> Also, if you're using `<b-sidebar>` it has a `backdrop` prop, which adds a backdrop when the sidebar is open.
> https://bootstrap-vue.org/docs/components/sidebar#backdrop

ok, thanks a lot!
