### ISSUE TITLE
Muliple select support in dropdown menu

### ISSUE THREAD

**Issue by adacapo21** [bootstrap-vue/bootstrap-vue#6575]
Hello team! 

Is there any possiblie way to add multiple support in a dropdown menu?
I would like to choose multiple options in a dropdown menu and the menu to close when I click outside the menu.

`
<b-input-group class="ml-2">

              <template #prepend>
                <b-dropdown text="Filtres" class="filtres filter-archive" variant="outline-secondary">
                  <b-dropdown-item @click="changeFilterState('isActive')">
                    <div class="d-flex align-items-center">
                      <span class="filter_group_box" aria-hidden="true">
                        <span v-if="filterCriteria.isActive" class="checked_selectAllDoc"></span>
                      </span>
                      Actif
                    </div>
                  </b-dropdown-item>
                  <b-dropdown-item @click="changeFilterState('isArchived')">
                    <div class="d-flex align-items-center">
                      <span class="filter_group_box" aria-hidden="true">
                        <span v-if="filterCriteria.isArchived" class="checked_selectAllDoc"></span>
                      </span>
                      Archivé
                    </div>
                  </b-dropdown-item>
                  <b-dropdown-divider></b-dropdown-divider>
                  <b-dropdown-item @click="changeFilterState('isTagged')">
                    <div class="d-flex align-items-center">
                      <span class="filter_group_box" aria-hidden="true">
                        <span v-if="filterCriteria.isTagged" class="checked_selectAllDoc"></span>
                      </span>
                      Avec Tag
                    </div>
                  </b-dropdown-item>
                 </b-dropdown>
              </template>
 </b-input-group>`

For example I want to select ' Activ' and 'Avec Tag' at the same time, and avoiding the closure of the menu when the first option is chosen!
I saw that there is a similar case scenario for select! Could you help please? #

**Comment by Hiws** [comment]
One option would be to not use the `<b-dropdown-item>` or `<b-dropdown-button>` components, and instead create the default item markup yourself, as these wont close then dropdown when clicked.
```html
<b-dropdown>
  <li role="presentation">
    <button role="menuitem" target="_self" class="dropdown-item">
      	This wont close when clicked.
    </button>
  </li>
</b-dropdown>
```

**Comment by adacapo21** [comment]
As far as I see, this helps us ot create a list of items that can be selected inside the dropdown menu, but on the other side it prevents the dropdown menu to close when we click outside the dropdown menu. Is there something that we can add here?

**Comment by Hiws** [comment]
> As far as I see, this helps us ot create a list of items that can be selected inside the dropdown menu, but on the other side it prevents the dropdown menu to close when we click outside the dropdown menu. Is there something that we can add here?

It should still close when you click outside of the dorpdown
