### ISSUE TITLE
When table sort order is changed selection is cleared

### ISSUE THREAD

**Issue by jamesmudd** [bootstrap-vue/bootstrap-vue#6576]
### Describe the bug

You are using the table with both selection and sorting enabled. If you select some items then change the sort order the selection is cleared

### Steps to reproduce the bug

1. Go to https://codepen.io/jamesmudd/pen/eYgobMV?editors=1011
2. Select a row or multiple rows
3. Change the sort order by clicking a header
4. The selection is lost (`onRowSelected` is called with empty array)

### Expected behavior

The selection remains independent of sorting (maybe filtering also)

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Vue: 2.6.11

**Environment:**

- Device: Desktop
- OS: Linux
- Browser: Chrome/Firefox
- Version: latest

### Demo link

 https://codepen.io/jamesmudd/pen/eYgobMV?editors=1011

### Additional context

This was found trying to implement a select all toggle in the header of a `selected` column. Even though the `selected` column has `sortable: false` (which removes the pointer cursor making the header look un-clickable) clicking it actually removes the sort. I think this should be changed so clicking headers of `sortable: false` columns does nothing. A accept this makes clearing sorting tricky though....

**Comment by Hiws** [comment]
> This was found trying to implement a select all toggle in the header of a selected column. Even though the selected column has sortable: false (which removes the pointer cursor making the header look un-clickable) clicking it actually removes the sort. I think this should be changed so clicking headers of sortable: false columns does nothing. A accept this makes clearing sorting tricky though....

When sorting is enabled, clicking a `non-sortable` header will reset the sorting. This is the default behavior.
The prop `no-sort-reset` can be used to disabled this behavior.
This is described in the first paragraph here: <https://bootstrap-vue.org/docs/components/table#sorting>

------

The behavior of selections being cleared on sorting is also intended behavior.
><https://bootstrap-vue.org/docs/components/table#row-select-support> (under `row select notes`) 
Sorting, filtering, or paginating the table will clear the active selection. The row-selected event will be emitted with an empty array ([]) if needed.

If you want the selection to persist across all of these, I'd recommend building up your own selection system.
This can be fairly easily done by adding a property to each item which will determine whether the row is selected or not.

Here's a quick example.
<https://codepen.io/Hiws/pen/LYxvaOz>

**Comment by jamesmudd** [comment]
Thanks for the help! Yes `no-sort-reset` is what I needed. Read the docs lots of times but somehow missed it. Thanks for the advice on implementing more complex selection behaviour not what I need yet but might soon! Thanks again.
