### ISSUE TITLE
Custom height collapsible navbar not transitioning properly

### ISSUE THREAD

**Issue by HoldYourWaffle** [bootstrap-vue/bootstrap-vue#6580]
### Describe the bug
When `.navbar-collapse` is given a `height`, the transition makes a jump between "content height" and "given height".

### Steps to reproduce the bug

1. Go to [this CodeSandbox](https://codesandbox.io/s/bootstrap-vue-fullscreen-collapsible-navbar-pz7gn?file=/App.vue)
2. Click on the navbar toggle
3. Observe jumpy behavior

### Expected behavior
A smooth transition from "hidden" to "given height".

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: desktop and phone
- OS: Windows and Android
- Browser: Firefox and Chrome
- Version: latest

### Demo link
[CodeSandbox](https://codesandbox.io/s/bootstrap-vue-fullscreen-collapsible-navbar-pz7gn?file=/App.vue)

### Additional context
I have absolutely no experience with bootstrap-vue's internals, but this behavior seems to be caused by this area:
https://github.com/bootstrap-vue/bootstrap-vue/blob/60c66ea566cd12d7580cebe33569e90622f6a0cf/src/components/collapse/helpers/bv-collapse.js#L17-L36

Replacing line 22 with `removeStyle(el, 'height')` and removing line 31 seems to fix the issue, but I have no idea what further impact this could have. Interestingly, if line 31 is removed line 33 can be removed as well.

**Comment by Hiws** [comment]
You're currently given the collapse default height, instead of one only when it's in the "opened" state.

If you instead target `.navbar-collapse.show`, your transition should be smooth.
https://codesandbox.io/s/bootstrap-vue-fullscreen-collapsible-navbar-forked-de84y

**Comment by HoldYourWaffle** [comment]
Yup that works, thank you so much!

The required `!important` makes me wonder though, aren't `onEnter`/`onLeave` still technically setting the wrong height?
Wouldn't it be better if they correctly handled the "given" value instead of having to forcibly override it?

**Comment by Hiws** [comment]
They're not setting the "wrong" height.
Collapses will open based on their content's height, which is what it's doing.
Since you want something else, you need to overwrite it.

At least that's how i see it.

**Comment by HoldYourWaffle** [comment]
But why should they open specifically to the height of their content?
I'd say it makes more sense to have them open to "their height", i.e. you're collapsing the whole element, not just the contents.

**Comment by HoldYourWaffle** [comment]
@Hiws any further opinions on this?
I encountered this oddity again today, and I can only say that it feels a little backwards and un-intuitive.

**Comment by Hiws** [comment]
Nope.
And since there's currently no one maintaining the project it's unlikely that it'll be fixed any time soon, if ever.
