### ISSUE TITLE
First slide, Second Slide and Third Slide

### ISSUE THREAD

**Issue by ochowei** [bootstrap-vue/bootstrap-vue#6593]
### Documentation issue

- [x] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/carousel/README.md#crossfade-animation

### Additional context or description
```
    <b-carousel-slide
      caption="First slide"
      img-src="https://picsum.photos/1024/480/?image=10"
    ></b-carousel-slide>
    <b-carousel-slide
      caption="Second Slide"
      img-src="https://picsum.photos/1024/480/?image=12"
    ></b-carousel-slide>
    <b-carousel-slide
      caption="Third Slide"
      img-src="https://picsum.photos/1024/480/?image=22"
    ></b-carousel-slide>
```

The string of caption,  First slide, uses lowercase on the word 'slide', but the others use uppercase 'Slide'.
Is this a typo?

**Comment by Hiws** [comment]
Yep, looks like a typo.
Feel free to open a PR 😄
