### ISSUE TITLE
[form-select] - No onchange event. 

### ISSUE THREAD

**Issue by happilymarrieddad** [bootstrap-vue/bootstrap-vue#660]
Hey guys,

Is there a way you could add a change event on the form-select like you have on the form-input? Also, could you add blur and focus. Thanks!

- Nick

**Comment by tmorehouse** [comment]
As a quick workaround, you should be able to do this:

```html
<b-form-select :options="myOptions" 
                @change.native="myChange"
                @blur.native="myBlur"
                @focus.native="myfocus"
></b-form-select>
```
```js
methods: {
   myChange(evt) {
       let val = evt.target.value
       // do something with val
   }
}
```

But note that `<select>` doesn't work like <input>, which fires an input event for every character entered.   and only the native change event is fired when a user makes a selection.  In the case of the component `<b-form-select>`, this event gets `$emit`ed as `input` to update the `v-model`.  You can hook into `@input="..."` to get the value as the first argument to the event (which will be massaged by the component)

**Comment by happilymarrieddad** [comment]
That works for me. Thanks!

**Comment by alexsasharegan** [comment]
You can always access the native dom events on a Vue component's root element by adding the `.native` modifier.

**Comment by alexsasharegan** [comment]
Oh, Troy beat me to it!

**Comment by alexsasharegan** [comment]
@happilymarrieddad, is this solved for you? Should we close this?

**Comment by happilymarrieddad** [comment]
Yea, thanks!

**Comment by UtkarshMishr** [comment]
@tmorehouse  

Thank You!!
 you saved my day!!

**Comment by choihwan2** [comment]
Thank You!! finally fix problem!
