### ISSUE TITLE
Is there a way to include a file that has been pushed (using javascript's push()) in b-form-file v-model?

### ISSUE THREAD

**Issue by LaurenzMelo** [bootstrap-vue/bootstrap-vue#6617]
I'm new to bootstrap-vue and I'm currently making a feature wherein the user will take a picture of them using their webcam and then they should be able to upload it. 

I'm almost done with that feature, the only thing I'm left with is that after the user took a picture, it will then be converted from base64 to file type, then I will use the push function to push the webcam image file to the v-model="files_webcam" (this is the holder of the files). Then, the b-form-file doesn't output the name of the files where I just use push function manually (instead of using the browse button of b-form-file)

The variable files_webcam contains the file that I pushed into it but it doesn't reflect on the b-form-file (it still says "No file chosen"). How can I output the file name under b-form-file of the file I pushed?

![Screenshot from 2021-05-13 19-27-53](https://user-images.githubusercontent.com/32416423/118119718-6537ac80-b421-11eb-940d-8c27e080c5b8.png)

**Comment by Hiws** [comment]
This is not possible due to security reasons.
https://github.com/bootstrap-vue/bootstrap-vue/issues/4557#issuecomment-571685616
