### ISSUE TITLE
Dropdown divider withing List of dropdown Items

### ISSUE THREAD

**Issue by adacapo21** [bootstrap-vue/bootstrap-vue#6620]
Hello team! How can it be possible, to put a dropdown-divider within every option/item of the dropdown list?

` <b-dropdown-item v-for="option in customOptions" :key="option.text" @click="selectedSort = option">
                {{ option.text }}
  </b-dropdown-item>
  <b-dropdown-divider></b-dropdown-divider>
`

when customOptions are for example like:

customOptions : [{
          text: 'Item 1 Text',
          value: 'Item 1 Value'
}, {
          text: 'Item 2 Text',
          value: 'Item 2 Value'
    },{
          text: 'Item 3 Text',
          value: 'Item 3 Value' }]

I would like to have something like:

Item 1 Text 
----------------
Item 2 Text
----------------
Item 3 Text
----------------
Item 4 Text
----------------
etc...

**Comment by Hiws** [comment]
You could add your `v-for` to a `<template>` instead.
```html
<b-dropdown>
  <template v-for="option in options">
    <b-dropdown-item :key="option.text">
      {{ option.text }}
    </b-dropdown-item>
    <b-dropdown-divider :key="option.text" />
  </template>
</b-dropdown>
```

Or instead of using `<b-dropdown-divider>`, you could use the border [utility classes](https://getbootstrap.com/docs/4.5/utilities/borders/#border) and add a bottom border for each element.
```html
<b-dropdown>
  <b-dropdown-item
    v-for="option in options"
    :key="option.text"
    link-class="border-bottom py-2"
  >
    {{ option.text }}
  </b-dropdown-item>
</b-dropdown>
```

**Comment by adacapo21** [comment]
<b-dropdown>
  <template v-for="option in options">
    <b-dropdown-item :key="option.text  + '-label'">
      {{ option.text }}
    </b-dropdown-item>
    <b-dropdown-divider :key="option.text" />
  </template>
</b-dropdown>

This is probably the correct way, otherwise we will have a duplicate warning:
[Vue warn]: Duplicate keys detected: x. This may cause an update error

Thanks Hiws,
Angelos
