### ISSUE TITLE
Console Warning on Rendering <b-table >

### ISSUE THREAD

**Issue by kaariwedoms** [bootstrap-vue/bootstrap-vue#6627]
Hi,
This is my source code of my component file

<template>

<div>
    <b-table striped hover :items="items"></b-table>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, toRefs, computed, onMounted , PropType ,  ref} from 'vue'

export default defineComponent({
  name: "New",

  data () {
 
  return {
        items: [
          { age: 40, first_name: 'Dickerson', last_name: 'Macdonald' },
          { age: 21, first_name: 'Larsen', last_name: 'Shaw' },
          { age: 89, first_name: 'Geneva', last_name: 'Wilson' },
          { age: 38, first_name: 'Jami', last_name: 'Carney' }
        ]
      }
    
  },

 computed: {
    todos() {
       return this.$store.getters.getTodos;
    }
  }

  
});
</script>

<style>
.list {
  text-align: left;
  max-width: 750px;
  margin: auto;
}

p{
font-size:26px;
color:red;
margin-top: 25px;
}
</style>

//Main.ts 
import { createApp } from "vue";
import Vue from 'vue'
import App from "@/App.vue";
import { BootstrapVue, BootstrapVueIcons } from 'bootstrap-vue'
import "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import 'bootstrap-vue/dist/bootstrap-vue.css'
import router from "@/router";
import {store} from '@/store'
import '@/assets/index.css'

createApp(App).use(store).use(router).mount("#app");

I am getting console error while rendering components and the component is not rendered in the view pls give a workaround

pls find the reference image
![image](https://user-images.githubusercontent.com/8941091/119159817-41a1e100-ba75-11eb-8a4e-c75fb59f8580.png)

**Comment by Hiws** [comment]
> import { createApp } from "vue";

Looks like you're using Vue 3, which BootstrapVue doesn't support yet.
You can subscribe to the following issue to stay updated: https://github.com/bootstrap-vue/bootstrap-vue/issues/5196
