### ISSUE TITLE
POPOVER Out side click - not working

### ISSUE THREAD

**Issue by Aadriya** [bootstrap-vue/bootstrap-vue#6632]
A popover has the trigger focus click it's not working properly while clicking on outside. 
I added the confirmation as   triggers="focus click blur" on the popover property

**Comment by Hiws** [comment]
That's because of the `click` trigger requiring you to click the element to close it.

Maybe just using `focus` trigger would achieve the result you're looking for?

**Comment by Aadriya** [comment]
> That's because of the `click` trigger requiring you to click the element to close it.
> 
> Maybe just using the `focus` trigger would achieve the result you're looking for?

Need click trigger action also.I want any where in webpage clicking need to hide the popover

**Comment by Hiws** [comment]
> > That's because of the `click` trigger requiring you to click the element to close it.
> > Maybe just using the `focus` trigger would achieve the result you're looking for?
> 
> Need click trigger action also.I want any where in webpage clicking need to hide the popover

Why do you specifically need the `click` trigger in your use-case?

**Comment by Aadriya** [comment]
> > > That's because of the `click` trigger requiring you to click the element to close it.
> > > Maybe just using the `focus` trigger would achieve the result you're looking for?
> > 
> > 
> > Need click trigger action also.I want any where in webpage clicking need to hide the popover
> 
> Why do you specifically need the `click` trigger in your use-case?

Yes

**Comment by Hiws** [comment]
Sorry, not really sure what to do with that reply.

**Comment by Aadriya** [comment]
> Sorry, not really sure what to do with that reply.

Sorry.In popup view I set a link . So I need to click that link also

**Comment by bettysteger** [comment]
@Aadriya `click blur` is the thing you need, see https://bootstrap-vue.org/docs/directives/popover#dismiss-on-next-click-self-dismissing
