### ISSUE TITLE
What is going on?

### ISSUE THREAD

**Issue by 332lfgb6** [bootstrap-vue/bootstrap-vue#6633]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.
https://bootstrap-vue.org/docs/components/breadcrumb

### Additional context or description

Provide any additional details here as needed.
![image](https://user-images.githubusercontent.com/51245335/119750273-88effd80-becb-11eb-9dac-9cdf12ea3845.png)

**Comment by Hiws** [comment]
Looks fine on my end.
Have you tried refreshing your cache?

**Comment by 332lfgb6** [comment]
> Looks fine on my end.
> Have you tried refreshing your cache?

When I go to https://bootstrap-vue.org/docs/components/badge, the console reported a mistake.
![image](https://user-images.githubusercontent.com/51245335/119786124-71803700-bf02-11eb-97fe-010bef7c34d7.png)
When I go to https://bootstrap-vue.org/ and https://bootstrap-vue.org/docs, the console did not report any errors.
![image](https://user-images.githubusercontent.com/51245335/119785654-fcacfd00-bf01-11eb-9973-a6683446eeef.png)
There is nothing in the local storage
![image](https://user-images.githubusercontent.com/51245335/119785873-38e05d80-bf02-11eb-8dd3-dd106a6b54dd.png)

**Comment by 332lfgb6** [comment]
> Looks fine on my end.
> Have you tried refreshing your cache?

Turn on the VPN, I can normally visit your website,

**Comment by Hiws** [comment]
No, but your browser might've cached an older version of the site and it's trying to access chunks which no longer exists because they've been updated.
Which is why I asked whether you've tried clearing your cache.

This can typically be done by pressing one of the following hotkeys (on windows anyways) Ctrl+F, Shift+F5 or Ctrl+Shift+R.

**Comment by 332lfgb6** [comment]
> No, but your browser might've cached an older version of the site and it's trying to access chunks which no longer exists because they've been updated.
> Which is why I asked whether you've tried clearing your cache.
> 
> This can typically be done by pressing one of the following hotkeys (on windows anyways) Ctrl+F, Shift+F5 or Ctrl+Shift+R.

I tried all three, and it didn't work.
![image](https://user-images.githubusercontent.com/51245335/119792108-033e7300-bf08-11eb-9c83-c67f5e065b9b.png)

**Comment by 332lfgb6** [comment]
I guess it has to do with the deployment environment and the CDN, I'm a foreigner after all, lol

**Comment by Hiws** [comment]
That might be the case, though it *should* work. But there has been DNS and other issues with certain countries before.
If you access https://bootstrap-vue.org/_nuxt/ad4486d.modern.js directly, do you get a file, or a 404 error?

Do you have any extensions in your browser? Could be worth a try to disable them to see if that works.

If all else fails, you can download the repo here on GitHub and run the docs locally (or upload them to your own hosting).

**Comment by 332lfgb6** [comment]
> That might be the case, though it _should_ work. But there has been DNS and other issues with certain countries before.
> If you access https://bootstrap-vue.org/_nuxt/ad4486d.modern.js directly, do you get a file, or a 404 error?
> 
> Do you have any extensions in your browser? Could be worth a try to disable them to see if that works.
> 
> If all else fails, you can download the repo here on GitHub and run the docs locally (or upload them to your own hosting).

How do I run local documents? I didn't learn NUXT.

**Comment by Hiws** [comment]
Clone the repo.
Run `yarn install` and if you don't have yarn, use `npm install`.

After that run `yarn docs-dev`/`npm run docs-dev` if you want to run it locally. Then open the URL shown in your console once it's ready.

If you want to generate the static files, run `yarn docs-gen`/`npm run docs-gen`. This will generate a `docs-dist` folder, containing the static files, which you can upload the hosting service of your choice.

Just be aware that the `dev` branch isn't the same as the current docs, but the next unreleased version.
So instead clone the repo on the tag `v2.21.2`: <https://github.com/bootstrap-vue/bootstrap-vue/tree/v2.21.2>
