### ISSUE TITLE
Long dropdown only scrolls a very small bit at a time in IE11

### ISSUE THREAD

**Issue by xaviarnl** [bootstrap-vue/bootstrap-vue#6634]
### Describe the bug

I have a dropdown with a list with quite a lot of values. I therefore have limited the length of it with a max-height, and set overflow to auto. In Chrome this results in a vertical scrollbar on the dropdown, and you can scroll with the scrollbar just fine.

In IE11, when I pull on the handle of the scrollbar, it only moves like 5 pixels, and then stops. I have to release the mouse button, and then I am able to move the handle a few pixels again.
Clicking just above or below the handle scrolls the dropdown list just fine.

I tried creating a [codepen](https://codepen.io/bjornhermans/pen/OJpjvXB?editors=0100) and a jsfiddle, but could not get it to work in IE11 (on codepen you have to pay for it to work in IE11). So you cannot use these to reproduce the problem yourself.

I am using Bootstrap-vue 2.21.2, Bootstrap 4.3.1, and Vue 2.6.12.

**Comment by Hiws** [comment]
Looks like stackblitz can be ran in IE11 (the direct link, not the editor)

Code: <https://stackblitz.com/edit/bs-vue-dropdown-ie11?file=index.html>
Preview: https://bs-vue-dropdown-ie11.stackblitz.io/

**Comment by Hiws** [comment]
Just tested it using a normal Bootstrap dropdown, and the same issue appears to happen.
So it appears to be an upstream isuse.

**Comment by xaviarnl** [comment]
@Hiws: You are totally correct! It is a Bootstrap problem: see [issue 26936](https://github.com/twbs/bootstrap/issues/26936).
