### ISSUE TITLE
b-form-select tag not displaying proper style

### ISSUE THREAD

**Issue by guillempp** [bootstrap-vue/bootstrap-vue#6646]
When using b-form-select as directed: 
```html
<b-form-select
      v-model="selectedOption"
      :options="optionsArray"
></b-form-select>
```
The result is shown like the default form on all browsers, but when adding the plain prop, a closer resemblance to the regular b-form-select style is displayed with the dropdown icon missing. The resulting HTML has a select with the proper options and class="custom-select".
Anybody knows if this behavior is due to the update to Vue 3 or anybody else having the same problem?

**Comment by Hiws** [comment]
Which versions of `BootstrapVue`, `Vue` and `Bootstrap` are you using?

**Comment by guillempp** [comment]
Vue: 2.6.13
BootstrapVue: 2.21.2
Bootstrap: 5.0.1

**Comment by Hiws** [comment]
> Bootstrap: 5.0.1

BootstrapVue doesn't support Bootstrap 5 (yet).
I suspect that would be the issue.

The recommend version is Bootstrap `4.5.3`.

You can subscribe to the following issue for updates: <https://github.com/bootstrap-vue/bootstrap-vue/issues/5507>

**Comment by guillempp** [comment]
Solved Thanks!
