### ISSUE TITLE
Include dist in github?

### ISSUE THREAD

**Issue by DavidRueter** [bootstrap-vue/bootstrap-vue#665]
Most javascript projects seem to include the dist folder in the github repository.  This makes it easy to download a .zip, and pull out a local copy of the files in dist without having to perform a build.

I know the build does update https://unpkg.com/bootstrap-vue/dist, but it would be nice to have the dist folder included in the .zip file downloaded from github.

(Some of us have automated workflows that pull down and unzip dist automatically.  With dist missing from the repository, we need to manually download and update local copies of the dist files.)

**Comment by pi0** [comment]
Hi @DavidRueter. Would you please describe more about your use case that if strictly needing downloads from github? If you just need a zip for your workflow, can use some URL like this:

https://registry.yarnpkg.com/bootstrap-vue/-/bootstrap-vue-0.18.0.tgz

**Comment by mredman** [comment]
+1 : It would be handy to see a "dist" folder where we can just get the js and css to use.

**Comment by blackflash** [comment]
Hi Guys, could you add the dist/ folder please? Will be great to have it here! Thanks
