### ISSUE TITLE
<b-table> empty columns on custom templates

### ISSUE THREAD

**Issue by johnkarpn** [bootstrap-vue/bootstrap-vue#6651]
### Describe the bug

If you use a custom template for a column and it contains some tags, and if the first tag has the v-if condition is false, then the content will not be displayed.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.13

![изображение](https://user-images.githubusercontent.com/5538918/120788960-a0695f00-c539-11eb-920b-3a3be946721b.png)
![изображение](https://user-images.githubusercontent.com/5538918/120789035-b70fb600-c539-11eb-9884-ceddc99dcc89.png)

But if you specify something at the beginning, for example, & nbsp; or <template>< / template>, then it works
![изображение](https://user-images.githubusercontent.com/5538918/120789094-cbec4980-c539-11eb-943c-e41ee89a62d8.png)
![изображение](https://user-images.githubusercontent.com/5538918/120789117-d4dd1b00-c539-11eb-85d5-01bfbe4c4842.png)

**Comment by Hiws** [comment]
I believe this is an issue with the new version of Vue `2.6.13`
See issue: <https://github.com/vuejs/vue/issues/12102>
