### ISSUE TITLE
Include css like External style sheets, but not like Embedded styles.

### ISSUE THREAD

**Issue by peektoseen** [bootstrap-vue/bootstrap-vue#6652]
Hi all! 
I develop web site on nuxt.js and try use bootstrap-vue module.
What I do: 
```
$ mkdir nuxttest
$ cd nuxttest
$ yarn create nuxt-app test
$ cd test/
$ yarn add bootstrap-vue
```

After that - edit /nuxt.config.js, and add **bootstrap-vue/nuxt** in modules section:
```
  modules: [
    "bootstrap-vue/nuxt"
  ],
```  

```
$ yarn build
$ yarn start
```

And open in browser (chrome) source code of page. I see, that bootstrap styles included embedded (like <style>...</style>). 
I want **connect bootstrap styles like file** in `<link rel="stylesheet" ... >` how can i make it?

**Comment by Hiws** [comment]
They should only be included under a `<style>` tag, when running the development server.
If you run a production build/server they should be added as `<link href="...">`.

**Comment by Hiws** [comment]
Nevermind, looks like the default behavior is putting it in style tags.
You have to adjust this behavior in nuxt.

Setting `extractCSS` under the build property to `true` should give the behavior you're looking for.

<https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#extractcss>

**Comment by peektoseen** [comment]
@Hiws , thank you for answer. But this don't work. 
I try run as production and try add nuxt.config.js:

```
  build: {
    extractCSS: true
  }
```

**Comment by Hiws** [comment]
I don't know enough about Nuxt to give you an answer.
But check the version as perhaps it's something new, or something has changed.

But overall this seems more like a Nuxt question, than a BootstrapVue question.
So try asking on their GitHub or perhaps their Discord.

**Comment by peektoseen** [comment]
This is an nuxt.js issue, that should be fixed  https://github.com/nuxt/nuxt.js/issues/8569
