### ISSUE TITLE
b-table keep expanded rows open on table reload

### ISSUE THREAD

**Issue by sasproul** [bootstrap-vue/bootstrap-vue#6653]
### Describe the bug

This isnt a bug, table is working corrrectly.  Was wondering if you could tell me how to keep expanded rows open on table reload.  currently using javascript setInterval() to fetch new data every 2 seconds.  Any expanded rows reset to collapsed on fetch.  

I've saved off user selected expanded rows and, on reload, check the array to see if the row id (my guid) has been saved as expanded.  If I see the guid I have tried setting these 3 variables to true to keep the row expanded
 row.item.detailsShowing = true;
     row.rowSelected = true;
     row._showDetails = true;

and nothing keeps the row expanded

### Expected behavior
I'm hoping to get some insight as to how to keep the user selected expanded rows open on table reload.
Google revealed no pages to help

### Versions

**Libraries:**
 "bootstrap-vue": "^2.21.2",
 "bootstrap": "^4.6.0",
"vue": "^2.6.12",

**Environment:**

chrome

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
As you said you're already doing, keep the state of opened rows somewhere else.
Then map it back either after you fetch your data, or create a computed property which does it for you.

Wanted to try out Faker so the codepen contains a bit more stuff than needed, but hope it makes sense :)
I save the `uuid` (id) of each row in a separate object (`expanded_rows`), and then set `_showDetails` on each object in a computed property based on the `expanded_rows` object.
<https://codepen.io/Hiws/pen/zYZapGM>
