### ISSUE TITLE
TypeError: _vue__WEBPACK_IMPORTED_MODULE_0__.Vue is undefined

### ISSUE THREAD

**Issue by alikleitcr7** [bootstrap-vue/bootstrap-vue#6657]
I'm using typescript with vue 3, I tried installing bootstrap-vue as documented [Here](https://bootstrap-vue.org/docs#vue-cli-3). 

My code:
```ts
import Vue,{ createApp } from 'vue'
import App from './App.vue'
import router from './router'
import { BootstrapVue, BootstrapVueIcons } from 'bootstrap-vue'

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'

Vue.use(BootstrapVue)
Vue.use(BootstrapVueIcons)

createApp(App)
    .use(router)
    .mount('#app')
```

I got an error: 
> Property 'use' does not exist on type 'typeof import("<project-dir>/node_modules/vue/dist/vue")'

I tired `.use` after `.use(router)`, 
```ts
createApp(App)
    .use(router)
    .use(BootstrapVue)
    .mount('#app')
```
then I got: 
> Argument of type 'BootstrapVuePlugin' is not assignable to parameter of type 'Plugin_2'.

I then added a file  `/src/desc.d.ts` with the following: 
```ts
declare module 'bootstrap-vue'
```

That removed the compile-time error, and I was able to run the app, however, I got the following in the console:
>Uncaught TypeError: _vue__WEBPACK_IMPORTED_MODULE_0__.Vue is undefined

I installed the library using: `npm install bootstrap-vue`

Nothing seemed to work for me, then I tried the plugin `vue-cli-plugin`, then got this error `_vue__WEBPACK_IMPORTED_MODULE_0__.Vue `, and failed to compile error:
```txt
./node_modules/portal-vue/dist/portal-vue.common.js
Module build failed: Error: ENOENT: no such file or directory, open '<project-dir>\node_modules\portal-vue\dist\portal-vue.common.js'
```

**dependencies:**
```json
  "dependencies": {
    "@types/bootstrap": "^5.0.16",
    "@types/history": "^4.7.8",
    "@types/js-cookie": "^2.2.6",
    "axios": "^0.21.1",
    "bootstrap-vue": "^2.21.2",
    "core-js": "^3.6.5",
    "js-cookie": "^2.2.1",
    "vue": "^3.1.1",
    "vue-router": "^4.0.0-0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "jquery": "^3.6.0",
    "node-sass": "^4.12.0",
    "popper.js": "^1.16.1",
    "sass-loader": "^8.0.2",
    "typescript": "~4.1.5"
  }
```

**Comment by Hiws** [comment]
> I'm using typescript with vue 3
BootstrapVue doesn't support Vue 3
