### ISSUE TITLE
Form textarea state icons

### ISSUE THREAD

**Issue by JeffCharron** [bootstrap-vue/bootstrap-vue#6659]
### Describe the bug

b-form-textarea state icons appear behind scroll bar

### Steps to reproduce the bug

When I set the state prop to true or false on a b-form-textarea, the green check mark or red x shows behind the textarea's scroll bar.

### Expected behavior

the icon appears a little to the left so it is fully visible

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.14

**Environment:**

Mac OS Big Sur 11.4
Chrome 91.0.4472.77

### Demo link

![Screen Shot 2021-06-14 at 12 39 10 PM](https://user-images.githubusercontent.com/71276695/121928886-9e0fbd80-cd0e-11eb-832a-4c795426ffda.png)
![Screen Shot 2021-06-14 at 12 39 21 PM](https://user-images.githubusercontent.com/71276695/121928901-a1a34480-cd0e-11eb-9387-1563370cfe3c.png)

**Comment by Hiws** [comment]
This is an upstream issue with Bootstrap.
See: https://github.com/bootstrap-vue/bootstrap-vue/issues/4781
