### ISSUE TITLE
b-icon not showing inside b-form-select-option

### ISSUE THREAD

**Issue by VasilijeBursac** [bootstrap-vue/bootstrap-vue#6662]
### Describe the bug

When I try to nest `b-icon` inside `b-form-select-option`, the icon is not showing up.

### Steps to reproduce the bug

Just nest `b-icon` inside `b-form-select-option`. 
For example: 
```
<b-select class="search-category-select">
        <b-form-select-option>
            <b-icon icon="exclamation-circle-fill" variant="success"></b-icon>
        </b-form-select-option>
</b-select >
```

### Expected behavior

The icon should appear inside the option of the form select.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Windows Laptop
- Windows 10
- Browser: Chrome
- Version: 91.0.4472.101 (Official Build) (64-bit)

**Comment by Hiws** [comment]
`<b-form-select-option>` or `<option>`  tags can only contain plain text, which is why the icon is not showing up.

**Comment by VasilijeBursac** [comment]
> `<b-form-select-option>` or `<option>` tags can only contain plain text, which is why the icon is not showing up.

Oh, didn't know that... Thank you for answer!
