### ISSUE TITLE
Template for custom data rendering with nested keys

### ISSUE THREAD

**Issue by marcianos** [bootstrap-vue/bootstrap-vue#6663]
### Is your feature request related to a problem? Please describe...

I have a b-table component with item provider function. The provider function returns the items and a "fields" array:
``` javascript
fields: [
          { key: "id", label: "user id", sortable: true },
          { key: "attributes.name", label: "user name", sortable: true },
          { key: "attributes.createdAt", label: "created at", sortable: true },
          { key: "attributes.permissions", label: "permissions", sortable: true },
        ],
```
The keys of the table are often nested.

Now I would like to create a template for custom data rendering. I tried something like this:
``` html
<!-- A custom formatted column -->
      <template #cell(attributes.permissions)="data">
        <b-badge variant="primary" class="mr-3" v-for="permission in data.attributes.permissions" :key="permission">
          {{ permission }}
        </b-badge>
      </template>
```
But this does not work. I got the error message:
``` javascript
 [vue/valid-v-slot]
'v-slot' directive doesn't support any modifier.eslint-plugin-vue
```

### Describe the solution you'd like

Is there a possibility that nested keys work with templates for custom data rendering?

### Describe alternatives you've considered

I also tried something like this which also does not work:
``` html
<template v-slot:[`attributes.permissions`]="{ data }">
  <b-badge variant="primary" class="mr-3" v-for="permission in data.attributes.permissions" :key="permission">
   {{ permission }}
  </b-badge>
</template>
```

**Comment by Hiws** [comment]
What you've written is valid. (except the alternative as you're missing `cell()` around your property path)
However your linter is throwing a warning, and not an error. Which can stop your project from compiling.
You'll need to configure your linter to allow modifiers in `v-slot`, check the following links as to how.

<https://eslint.vuejs.org/rules/valid-v-slot.html#vue-valid-v-slot>
<https://eslint.vuejs.org/rules/valid-v-slot.html#options>

**Comment by marcianos** [comment]
> What you've written is valid. (except the alternative as you're missing `cell()` around your property path)
> However your linter is throwing a warning, and not an error. Which can stop your project from compiling.
> You'll need to configure your linter to allow modifiers in `v-slot`, check the following links as to how.
> 
> https://eslint.vuejs.org/rules/valid-v-slot.html#vue-valid-v-slot
> https://eslint.vuejs.org/rules/valid-v-slot.html#options

Ah thank you! I did not recognize that this is valid. Now I changed as you mentioned the package.json eslintConfig entry to:
``` json
"eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {
      "vue/valid-v-slot": "off"
    }
  },
```
With this changes, the code with ...#cell(attributes.permissions) compiles. But in the specific vue file I still got the same error message. Do I need to make any further changes to remove the error message?

Originally, I planned to use the rule you suggested:
``` json

{
  "vue/valid-v-slot": ["error", {
    "allowModifiers": false
  }]
}
```

But "This rule was introduced in eslint-plugin-vue v7.0.0".  In my package.json I have:
``` json
"devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "^4.5.11",
    "@vue/cli-service": "^4.5.13",
    "autoprefixer": "^9.8.6",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "node-sass": "^5.0.0",
    "postcss": "^7.0.35",
    "vue-template-compiler": "^2.6.11"
  },
```
Can you give me a hint what is the best way to update the eslint modules? Thank you very much! :smile:

**Comment by Hiws** [comment]
`"allowModifiers": false` would have to be set to `true`, since you *want* to use "modifiers" in the slot.

I think you should be able to run `npm update eslint-plugin-vue` to get the latest version without any issues.

*Unrelated sidenote*
It also looks like your `@vue/cli` plugin versions aren't in-sync with eachother, which I think they're meant to be.
So might be worth running `vue upgrade` in your project.

**Comment by marcianos** [comment]
Thank you! But with the `npm update eslint-plugin-vue` command has unfortunately no effect. I only got the message that packages are `up to date` You have an other hint for me?

Thanks for your sidenote! I will check this as well.
