### ISSUE TITLE
Tooltip is immediately hidden after being shown

### ISSUE THREAD

**Issue by tratnayake** [bootstrap-vue/bootstrap-vue#6664]
### Describe the bug

All my tooltips are immediately hidden after being shown. Looking through the Vue dev console appears to show that there is immediately a hide operation emitted by `<Root>` after the show event. (There also appears to be 2 shows and hides happening)

![tooltip_bug](https://user-images.githubusercontent.com/4359032/122135870-3a60bf80-cdf6-11eb-9977-7853c30310ea.gif)

### Steps to reproduce the bug

Unfortunately I cannot demo this bug as it's on an internal system.

### Expected behavior

The tooltip to stay visible until I move my mouse away.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.6

**Environment:**

- Device: Mac
- OS: 10.15.7 `Catalina`
- Browser: Chrome
- Version: `89.0.4389.128`

### Demo link

N/A :(

### Additional context

Things I've tried

* Originally tried to add tooltip on a `<b-badge></b-badge>` element
* Switched to adding onto a button as per the `vue-bootstrap` documentation.

```
<b-button v-b-tooltip.hover title="Tooltip directive content">
  Hover Me
</b-button> 
```

* Bumped Booststrap-vue version to the the most recent one: 2.0.4 -> 2.21.2

**Comment by Hiws** [comment]
> Unfortunately I cannot demo this bug as it's on an internal system.

You can try creating a minimal reproduction on a codepen or similar page. 

However, I'd check to make sure you've added both Bootstrap and BootstrapVue CSS to your project.
You can also try downgrading Bootstrap to `4.5.3`, as that is the latest supported version (though i doubt it's the issue, but worth a try).

**Comment by JonMagon** [comment]
> > However, I'd check to make sure you've added both Bootstrap and BootstrapVue CSS to your project.
> 
> This was it 🤦🏽‍♂️ (Though I'm wondering how the heck things were working all this time without the css ¯_(ツ)_/¯ )
> 
> Thanks @Hiws !

Omg, I had the same problem for a couple of months, there are several similar issues here and this is the first one solved
