### ISSUE TITLE
b-form-radio-group doesn't update value for validation

### ISSUE THREAD

**Issue by greg-vstorm** [bootstrap-vue/bootstrap-vue#6666]
### Describe the bug

I think is something wrong with `b-form-radio-group` component because I notice problems with validation using vee-validate and vuelidate. Model is updated on field change, but validation libraries don't see this updated state.

### Steps to reproduce the bug

1. Go to https://codesandbox.io/s/magical-buck-1j0sl?file=/App.vue
2. Click on Submit button
3. Both fields have validation errors, type something in the Name field and select any gender
4. See error: name field now is correct, gender field is still invalid. Same if you fill the form, click submit, gender is invalid.

### Expected behavior

When the radio is selected (and value in the model) validation should be ok.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.5.3
- Vue: 2.6.12
- vee-validate: 3.4.9
- vuelidate: 0.7.6

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version: 91

### Demo link

The problem when using vee-validate:
https://codesandbox.io/s/magical-buck-1j0sl?file=/App.vue

With vuelidate doesn't work as expected too:
https://codesandbox.io/s/bootstrapvue-vuelidate-example-forked-72mrq?file=/App.vue

### Additional context

Tested with bootstrap-versions from 2.16 to latest, same problems when using vee-validate. 

Is a little better when using up to v2.20.1 and vuelidate, but the latest versions do not work as expected.

**Comment by Hiws** [comment]
Looks like it's cause by you using the `default` scoped slot on `<b-form-group>`.
If you remove `v-slot="{ ariaDescribedby }"` it, your validation works again.

**Comment by greg-vstorm** [comment]
> Looks like it's cause by you using the `default` scoped slot on `<b-form-group>`.
> If you remove `v-slot="{ ariaDescribedby }"` from it, your validation works again.

Works fine, thank you, not tried this.
I will close this issue and make a note in Discussions for the future.
