### ISSUE TITLE
table merge fields

### ISSUE THREAD

**Issue by wormen** [bootstrap-vue/bootstrap-vue#667]
How can I combine several cells?
I saw no examples and descriptions in the documentation

example, what I need

![2017-07-07_20-09-53](https://user-images.githubusercontent.com/8462339/27953758-5803fd82-6350-11e7-99d8-951ea1e0eed3.jpg)

**Comment by tmorehouse** [comment]
Currently `<b-table>` is designed  for standard record based data, which can be sorted. paginated, and filtered (and looped through using Vue.js `v-for="record in records"` manner for rendering). 

What you are looking for would need custom logic for being able to apply rowspans, either based on the raw data (repeated precious/next cells in same column), or nested data structure in the items data.

If your need is just for presentation (and no local pagination, sorting or filtering), for now I think your best  bet is to render the BS v4 tables manually in a custom component.

This might be something we can look at possible in later release.

**Comment by wormen** [comment]
I understood
thanks

**Comment by tmorehouse** [comment]
We may need to add in a new option that allows b-table to check for repeated row cell values (based only on unformatted values), although it will break row-clicked events (as a cell when clicked will trigger the row-clicked/hover/etc events for the row that the cell first paars in.

This would need to be a new field config parameter (enabled on a per field bass) that would allow row-spanning for a value, and would need to "look ahead" in the table rows to see how many rows to span, slowing down rendering.

Its not high priority at the moment, but may be something we can add in the future.

**Comment by rasponline** [comment]
Any guess when this feature will be available? desperately looking for this...

**Comment by tmorehouse** [comment]
Merged fields will most likely never be part of `b-table`, as computationally this would add considerable weight to the component (needing to look ahead, back, and left to right, in the resultant items array during render, and also would be an issue when visually stacking tables on small screens).

If you are wanting to display static data with merged cells, I would suggest generating the plain HTML table markup and add the base Bootstrap V4.x table styles (i.e. class `.table`, and any other table style classes such as `.table-striped`, etc, as needed)
