### ISSUE TITLE
Missing custom-select style if latest bootstrap is used

### ISSUE THREAD

**Issue by camicase82** [bootstrap-vue/bootstrap-vue#6671]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Describe the bug

When working with CDNs and not using any packager, the style for b-form-select component is missing

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.org/docs/reference/starter-templates and copy the code
2. Add a <b-form-select :options="options"></b-form-select> element
3. Open the page
4. Check the custom-select on the select tag, the styles are missing, but when seeing the component on the samples pages, the style is there

![stylesIssue](https://user-images.githubusercontent.com/8999046/122479487-c575bd00-cf90-11eb-8f5e-33d38fed963c.png)

5. Check that the loaded bootstrap is 5, instead of the supported one

### Expected behavior

Update the documentation to use 
https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css
instead of
https://unpkg.com/bootstrap/dist/css/bootstrap.min.css

**Comment by Hiws** [comment]
I have a PR open which should solve this issue.
https://github.com/bootstrap-vue/bootstrap-vue/pull/6623
