### ISSUE TITLE
Possibility to change message or title with $bvToast

### ISSUE THREAD

**Issue by atcha** [bootstrap-vue/bootstrap-vue#6677]
### Is your feature request related to a problem? Please describe...

Currently i'm forced to hide my toast and then use .toast every time i have to add content to a single toast

### Describe the solution you'd like

Should it be possible to add a method like 
`this.$bvToast.addContent(
  'toastid', 
  {
    message,
    title
  })`

or another to modify a toast without recreating it ?
Or maybe is it already possible and i did'nt find how to do it :).

Thanks for your answers and all your work on this lib.

**Comment by Hiws** [comment]
You can use the `<b-toast>` component.
<https://bootstrap-vue.org/docs/components/toast#b-toast-component>
