### ISSUE TITLE
[proposal] always add tag or level property for headers

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#668]
For seo purposes it is recommended that when using headers from h1 to h6 they follow the degree of importance on your webpage. Currently it seems that bootstrap-vue is mostly using the header levels from the bootstrap v4 examples, but often this is not what you need.

It would be nice if bootstrap-vue gives the possibility to easily change those header level. E.g. for a modal I have I would like to use a h4 and not a h5. But currently it's quite cumbersome to do this as you need to replace the whole modal-header with close button, emit hide events, add prop for hideHeaderClose etc. Quite a bit of work for only changing to a h4 ;)

**Comment by tmorehouse** [comment]
Modals are typically not visible initially,so the modal header tag wouldn't affect SEO normally (only if the modal is initially shown on page load via SSR).

But this might be a nice feature for `<b-modal>` to add a prop `heading-tag` which defaults to `h5` (the bootstrap example default)

**Comment by tmorehouse** [comment]
List of elements with heading tags (h4, h5, h6, etc) that could have new props for setting the tags:
 - [ ] `b-card`
 - [ ] `bcarousel-slide`
 - [x] `b-dropdown-header` _Currently supported_
 - [ ] `b-jumbotron`
 - [ ] `b-modal`
 - [ ] `b-popover`

**Comment by alexsasharegan** [comment]
PR #646 has addressed this for the card component.

**Comment by tmorehouse** [comment]
We should probably pick a common naming convention for the props, such as heading-tag, header-tag, subtitle-tag, etc.

**Comment by alexsasharegan** [comment]
Definitely! `*-tag` and it's camel-cased versions in code.

https://github.com/alexsasharegan/bootstrap-vue/blob/feat/functional-components/lib/components/card.js#L45-L60

**Comment by pimlie** [comment]
Maybe this would be better for a seperate issue, but it would be nice if we could easily give tabs a header tag as well. Tabs are also often used as navigation elements and therefore should be giving a header tag for seo purposes. E.g. think of a product page with specification and review tabs where the tabs are just part of the structure of the page.

I tried setting `headHtml` for tabs but that was not working as I lost the event triggers and could not switch tabs anymore

**Comment by tmorehouse** [comment]
PR #696 addresses adding support for setting tags on:
 - b-card`
 - b-carousel-slide`
 - b-dropdown-header` _Currently supported_
 - b-jumbotron`
 - b-modal`
 - b-popover`
