### ISSUE TITLE
BFormCheckbox treats 1 as false

### ISSUE THREAD

**Issue by caugner** [bootstrap-vue/bootstrap-vue#6683]
### Describe the bug

BFormCheckbox treats `1` (integer one) as `false`.

In our case, we use MySQL as a backend, which doesn't have a `BOOLEAN` data type, so booleans are stored as integers. In one instance we forgot to cast the integer to a boolean, which caused a bug, because the checkbox wasn't properly set.

### Steps to reproduce the bug

```vue
<b-form-checkbox :checked="1" />
```

### Expected behavior

The checkbox should be checked.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.14

**Environment:**

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 91 (Nightly)

### Demo link

https://codesandbox.io/s/bformcheckbox-with-checked1-rzpq8

### Additional context

(None.)

**Comment by Hiws** [comment]
That's because `checked` is the property used for the `v-model`.
It will compare the value passed to `checked` to the `value` prop.
If they match the checkbox will appear checked.

The exception to this would be when passing `true` specifically to the `checked` property.
Not sure I'd say it's a bug.

In your case you could just parse your value to a boolean. This could be done by doing `:checked="!!1"`.

**Comment by caugner** [comment]
> Not sure I'd say it's a bug.

Strictly speaking, it's not a bug. You could say that `BFormCheckbox` only accepts booleans and treats everything else as `false`.

However, in practice this seems to be an unnecessary pitfall (as it doesn't emit any warning), and it behaves adverse to what is usually considered a true-ish value.

**Comment by caugner** [comment]
Another argument for improving the behavior would be that `<input type="checkbox" />` also treats `1` as `true`:

![grafik](https://user-images.githubusercontent.com/495429/124166627-5ffef180-daa3-11eb-9d1e-62572cb8576a.png)

**Comment by Hiws** [comment]
To be fair, a native input treats any "truthty" value as checked.

![xA3N5q0 1](https://user-images.githubusercontent.com/7057431/124167212-14991300-daa4-11eb-834d-1e4f79226afd.png)

**Comment by caugner** [comment]
> To be fair, a native input treats any "truthty" value as checked.

Which is not an argument against treating at least `1` as truthy, and `0` as falsy. 😉 

Since all boils down to the implementation of `looseEqual` (see #6684), I would say intuitively that 1 and true as well as 0 and false are definitely loosely equal. After all, 1.0 and "1" are also loosely equal according to the current implementation.

At the end of the day, it's a question of keeping or removing this pitfall. I fell into it, and other users probably have and will, too. 🤷
