### ISSUE TITLE
b-form-file in a cycle

### ISSUE THREAD

**Issue by intellimedhu** [bootstrap-vue/bootstrap-vue#6689]
Have an unexpected behavior when combining `b-form-file` with `v-for`

repro:

1. add some `b-form-file` with a `plus` button (`multiple` option is not suitable for BL):
![image](https://user-images.githubusercontent.com/65296389/124884683-ce2b4300-dfd2-11eb-90a7-83c0db79b181.png)
![image](https://user-images.githubusercontent.com/65296389/124884761-e13e1300-dfd2-11eb-8fbb-905a0d2ab1e2.png)

2. choose a file for the **3rd one**: 
![image](https://user-images.githubusercontent.com/65296389/124884876-ffa40e80-dfd2-11eb-9291-8bf720c28e48.png)

3. delete the **second one**: 
![image](https://user-images.githubusercontent.com/65296389/124884961-10ed1b00-dfd3-11eb-9111-2c291f8becdb.png)

**4. after deletion the previously 3rd item doesn't have the binding, but in the code it has the selected file (I guess only the label not updating)**
![image](https://user-images.githubusercontent.com/65296389/124885107-39751500-dfd3-11eb-9c02-effdbd7efaf7.png)

in code, i have a list of object like this:
```
files: [{
   file: {...}, // this is binded, `null` by default
}]
```

markup:
```
<div v-for="(x, index) in files" :key="index">
   ...
  <b-form-file :id="`file-${index}`" v-model="x.file"></b-form-file>
   ...
</div>
```

deletion is made by `array.splice(index, 1)`

Any idea how to solve?

**Comment by Hiws** [comment]
> :key="index"
 
 This is likely because you're using the `index` as a `key` which should always be avoided if possible as it can cause re-render issues when adding/deleting/moving elements.

**Comment by intellimedhu** [comment]
It works!
Thanks for the quick reply!
