### ISSUE TITLE
b-modal in a document level full screen mode

### ISSUE THREAD

**Issue by shidcordero** [bootstrap-vue/bootstrap-vue#6690]
### Describe the bug
I want to show my modal in a document level because I have a full screen mode and the modal was not visible if full screen mode was enabled. 
![bug 1](https://user-images.githubusercontent.com/26376208/124901310-77465d80-e014-11eb-95cf-312aa57c06b7.gif)

I already tried to add `static` prop but this destroys my layout. Is there a way to specify in b-modal where the parent I would like to add the modal?

**Comment by Hiws** [comment]
I'm guessing the "fullscreen" mode has a higher `z-index` than your modal.
I would start by checking that.

**Comment by shidcordero** [comment]
@Hiws checked the z-index and the modal has the default of 1050, the container where I trigger the fullscreen mode has no z-index set. Tried it also to set 1 and the modal still not visible

**Comment by Hiws** [comment]
How does the `fullscreen mode` work?

**Comment by shidcordero** [comment]
here's the code for the fullscreen mode

```
 onFullScreenClick()` {
      const element = this.$refs['drawflow-container'].parentElement

      if (!document.fullscreenElement) {
        if (element.requestFullscreen) {
          element.requestFullscreen().then(() => (this.isFullScreen = true))
        }
      } else if (document.exitFullscreen) {
        document.exitFullscreen()
        this.isFullScreen = false
      }
    }

```

basically this code gets the encircled part and make it as fullscreen.
![image](https://user-images.githubusercontent.com/26376208/124904175-4f0c2e00-e017-11eb-9371-68fc6929ec3e.png)

**Comment by shidcordero** [comment]
So I've seen this issue pretty similar to this one https://github.com/angular-ui/bootstrap/pull/4200 and in the angular-ui bootstrap they finally made it a go. can we do the same here?

**Comment by Hiws** [comment]
I'm guessing the modal isn't located inside the div you are fullscreening?
Since if it was, the `static` prop should make it work as you want based on the codepen below..

https://codepen.io/Hiws/pen/OJmXMXR

**Comment by shidcordero** [comment]
@Hiws nice, I'll take a look on portal-vue as it seems it is the solution to this problem. will let you know

**Comment by shidcordero** [comment]
closing this issue. solve using portal-vue as suggested
