### ISSUE TITLE
Update Bootstrap CSS CDN link to be v4 Specific in [Getting started > Browser] Docs Section

### ISSUE THREAD

**Issue by zcoop98** [bootstrap-vue/bootstrap-vue#6696]
### Documentation issue

The Bootstrap CSS CDN reference in the `<link>` element needs to be updated to refer specifically to Bootstrap v4 in the *Getting started > Browser* page section. 

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs#browser

### Additional context or description

The unpkg.com CDN link in the Browser import example currently refers to the Bootstrap package generically, without a version number.
This means that, [since Bootstrap's v5.0.0 release May 5th](https://github.com/twbs/bootstrap/releases/tag/v5.0.0), the `<link>` using `//unpkg.com/bootstrap/dist/css/bootstrap.min.css` now imports Bootstrap *v5* CSS, which Bootstrap-Vue isn't compatible with yet (via #5507).

The link needs to be updated to `//unpkg.com/bootstrap@4/dist/css/bootstrap.min.css`, which will point to the latest v4 release.

**Comment by Hiws** [comment]
I have a PR open which should solve this issue.
#6623

**Comment by jpmeijers** [comment]
I'm also affected by this. I was following the steps in the docs to install bootstrap into my Vue2 project, but the example navbar didn't work. Turns out npm installed bootstrap 5, not 4 as expected.

> npm install vue bootstrap bootstrap-vue

Should therefore be changed to be bootstrap 4 specific.
