### ISSUE TITLE
@load.native does not work for b-img-lazy

### ISSUE THREAD

**Issue by tlyau62** [bootstrap-vue/bootstrap-vue#6700]
### Describe the bug

@load.native does not work for b-img-lazy and same as @load

### Expected behavior

For @load.native, the component should emit such event after the image is loaded.
This should be same as the @load.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2

**Comment by Hiws** [comment]
Based on this codepen: https://codepen.io/Hiws/pen/QWvGEOe
It looks to be working on my end. 
Latest Chrome, Windows 10.

It shows the alert once on page load, which would be the `<img>` tag loading the placeholder, and then once more, once you scroll down the page to where the image is and the actual image is loaded in,

**Comment by tlyau62** [comment]
> Based on this codepen: https://codepen.io/Hiws/pen/QWvGEOe
> It looks to be working on my end.
> Latest Chrome, Windows 10.
> 
> It shows the alert once on page load, which would be the `<img>` tag loading the placeholder, and then once more, once you scroll down the page to where the image is and the actual image is loaded in,
> 
> Could you provide a reproduction?

Thanks for the reply.
In the example, the @load.native is triggered twice. It is triggered before the image is loaded.
I tried on chrome with throttling Fast 3G profile.

**Comment by tlyau62** [comment]
the problem is related to the late/async binding on the 'src' attribute,
looks like there is an initial value on the 'src' attribute,
this causes the first @load.native is triggered.

**Comment by Hiws** [comment]
Yes, that's the behavior i mentioned would happen in my reply.

**Comment by tlyau62** [comment]
but I guess the alert should not be shown since the image has not been loaded?

**Comment by tlyau62** [comment]
i see, thanks for the clarification
