### ISSUE TITLE
Add a changeable selection for page size to a pagination

### ISSUE THREAD

**Issue by Agnes12180** [bootstrap-vue/bootstrap-vue#6701]
Hi,
I want to add a selection to a pagination in order to change count  for per page. I just packaged my own component by using BPagination, but it dosn't work, the content for each page doesn't be updated when change to a new page. If I put the code after the BTable, it works. I wonder if it's a problem to the table ids. I have no idea how to link table id  to the pagination ariaControls.
Here is my component.
![image](https://user-images.githubusercontent.com/66258155/125377513-b6cbcb80-e3bf-11eb-9169-d65fcaa380f7.png)
Here is my table. 
![image](https://user-images.githubusercontent.com/66258155/125377626-dfec5c00-e3bf-11eb-8ef9-056c20ff0506.png)

I use [table] as an id to a BTable and as a prop ariaControls and put it into my component, it's invalid， but if I do below change, it works.
![image](https://user-images.githubusercontent.com/66258155/125378130-cbf52a00-e3c0-11eb-8cfd-ac58187bb0d7.png)

I don't know if there is already such function in BPagination, so I code it by myself. This function looks like below picture.
![image](https://user-images.githubusercontent.com/66258155/125379161-9b15f480-e3c2-11eb-9b2f-0c27c017d272.png)

Could you please take a look? Thanks in advance.

**Comment by Hiws** [comment]
I don't you changing `perPage` anywhere, which is what controls how many items are shown per page.

**Comment by Agnes12180** [comment]
> I don't see you changing `perPage` anywhere, which is what controls how many items are shown per page.

sorry, I didn't put the whole code. Selected is for changing per page.
![image](https://user-images.githubusercontent.com/66258155/125413026-e1afe287-4256-43e2-83b3-7b2b87f17c89.png)

**Comment by Hiws** [comment]
and what are you doing with that emitted data in the parent?

**Comment by Hiws** [comment]
Yes. But your `<b-page>` component has a `@pageChange` event.
What are you doing in that method?

It might also be a lot easier if you created a reproduction of what you currently have in a codesandbox/codepen.

**Comment by Agnes12180** [comment]
> Yes. But your `<b-page>` component has a `@pageChange` event.
> What are you doing in that method?
> 
> It might also be a lot easier if you created a reproduction of what you currently have in a codesandbox/codepen.

Hiya,
I put my demo in a codesandbox.
https://codesandbox.io/embed/dreamy-elgamal-lmb8y?fontsize=14&hidenavigation=1&theme=dark
I used my page component for the first table and used original bpagination for the second one.

Meanwhile, I find another problem, it said the pagination would control the table by linking the id, I use different ids for each table, why both of them change after I select a different page.

**Comment by Hiws** [comment]
Looks like i misunderstood what your issue was.

You can fix your issue by adding `@change="pageChange"` to `<b-pagination>` inside your component.

**Comment by Agnes12180** [comment]
> https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier

It works!!! THANK YOU so much!
