### ISSUE TITLE
b-form-radio-group does not arrange elements inline

### ISSUE THREAD

**Issue by jetacpp** [bootstrap-vue/bootstrap-vue#6702]
### Describe the bug

According to the documentation, b-form-radio-group should arrange elements inline. I tried with the online docs live editor and it worked as expected, however, outside of that editor, the elements were stacked and not inline. Please see codesanbox demo.

### Versions

**Libraries:**
    "bootstrap": "5.0.2",
    "bootstrap-vue": "2.21.2",
    "vue": "^2.6.11",

**Environment:**
Chrome: 91.0

### Demo link

https://codesandbox.io/s/aged-morning-h1dhc

**Comment by Hiws** [comment]
> "bootstrap": "5.0.2",

BootstrapVue doesn't support Bootstrap 5. Use version `4.5.3` instead.

Related: https://github.com/bootstrap-vue/bootstrap-vue/issues/5507

**Comment by jetacpp** [comment]
Thank you, the older version indeed solved the mistery
