### ISSUE TITLE
Cant have responsive slides without background images

### ISSUE THREAD

**Issue by christopheSeeka** [bootstrap-vue/bootstrap-vue#6704]
Hello,

i don't understand why the carousel force us to use a background image? 
I just want a simple carousel of html content, without any image like i would do with the original bootstrap carousel. 
Here if i don't put any background or use img-blank, if i don't set a fixed height i don't have anything displayed... Im probably missing something?

Thanks in advance

**Comment by Hiws** [comment]
You can place w/e content you want in the `img` slot (even if it's not an image) on `<b-carousel-slide>`.

```html
<b-carousel-slide v-for="i in 5">
  <template #img>
    <!-- Place your HTML here -->
  </template>
</b-carousel-slide>
```

**Comment by christopheSeeka** [comment]
Awesome, thank you it works.
