### ISSUE TITLE
v-b-hover with variable input

### ISSUE THREAD

**Issue by naletups** [bootstrap-vue/bootstrap-vue#6706]
Does the `v-b-hover` directive provide a convenient way of passing not only true/false, but also a custom parameter? If you have multiple elements on your page, it can become quite tedious and resource intensive to create a large set of handlers.

For the time being, I resorted back to using the event hooks directly on all the elements, similar to as the directive: `@mouseenter="onHover(0) @mouseleave="onUnhover(0)` and so on (see also comments at end of https://github.com/bootstrap-vue/bootstrap-vue/pull/4771 for more use cases)

**Comment by Hiws** [comment]
I guess you could create an inline function.
`v-b-hover="v => onHover(v, 'some other value')"`
