### ISSUE TITLE
<b-form-input> bind prop value does not update on the second time

### ISSUE THREAD

**Issue by ITBDarky** [bootstrap-vue/bootstrap-vue#6711]
### Describe the bug

I am currently implementing a child component that bind parent's year[] array value.

Other than that it also updates parent's year[] array with `<b-form-input>` during on change event when certain condition is met.

But the after second on change update event occur, the `vModelValue` and `localValue` of the related `<b-form-input>` stop updating.

### Steps to reproduce the bug

1. Update the 'to' value lower than 'from' value 
2. The 'to' `<b-from-input>` update with the corrected value
3. Update the 'to' value to lower than the 'from' value again
4. 'to' `<b-form-input>` value text stop updating

### Expected behavior

The `vModelValue` and `localValue` of 'to' <b-form-input>' should always sync with the binded value.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Vue: 2.6.14

### Demo link

Equivalent example as below:

https://jsfiddle.net/darkyduckduck/ybdx6043/58/

Stackoverflow question:

https://stackoverflow.com/questions/68478332/b-form-input-bind-value-does-not-update-on-the-second-time

### Additional context

Sample code

Parent.vue
```html
<template>
  <child :year="year" @update="update">
</template>
```
``` javascript
<script>
// Import child component here

export default {
  name: 'Parent',
  components: {
    Child,
  },
  data: () => ({
    year: [100, null],
  }),
  methods: {
    update(newYear) {
      this.year = newYear;
    },
  },
</script>
```

Child.vue
```html
<template>
  <div>
    From <b-input :value="year[0]" />
    To <b-input :value="year[1]" @change="update" />
  </div>
</template>
```
```javascript
<script>
export default {
  name: 'Child',
  props: {
    year: {
      type: Array,
      required: true,
    }
  },
  methods: {
    update(yearToVal) {
      const [yearFrom] = this.year;
      let newYear = [...this.year];
      
      if (yearToVal < yearFrom) {
        /* Both of this update end up the same */
        // newYear[1] = yearFrom;
        this.$set(newYear, 1 , yearFrom);
      }
      this.$emit('update', newYear);
    },
  },
};
</script>
```

**Comment by Hiws** [comment]
This isn't really an issue with BootstrapVue but more of a Vue issue.
As the behavior is present with a native `<input>` as well.

The issue you're having is that you're setting it to the same value as it already has, which means Vue wont do anything.
The first time you update the parent value you set it from `[100, null]` to `[100, 100]`, and on the second time you're updating it from `[100, 100]` to `[100, 100]` which isn't really a change, so Vue will ignore it.


In the below codepen you can try typing `1`, and the input should change to `100`, but if you change the value to under 100 again it wont do anything as `max` is already set to 100.
<https://codepen.io/Hiws/pen/vYmWyOm>

**Comment by ITBDarky** [comment]
Thanks @Hiws. Now I know what is happening. I will close the issue now.
