### ISSUE TITLE
Bootstrap vue support to Vue JS @3.*

### ISSUE THREAD

**Issue by hi2binay** [bootstrap-vue/bootstrap-vue#6712]
Bootstrap vue is not working with Vue JS 3.*, please help me on working of it with vue js 3.

**Comment by Hiws** [comment]
Duplicate of https://github.com/bootstrap-vue/bootstrap-vue/issues/5196

**Comment by juanchos2018** [comment]
ya han usado Bootstrap vue con vue 3 ?
