### ISSUE TITLE
How trigger collapse hide on vue-bootstrap?

### ISSUE THREAD

**Issue by AtousaDarabi** [bootstrap-vue/bootstrap-vue#6719]
### Discussed in https://github.com/bootstrap-vue/bootstrap-vue/discussions/6718

<div type='discussions-op-text'>

<sup>Originally posted by **AtousaDarabi** July 29, 2021</sup>
In some cases like window resize, I need to call collapse be closed.
I can't trigger hide function of collapse in my methods function in vue.
How can I make it?</div>

**Comment by TitanFighter** [comment]
You can control the state of collapse via `visible` prop -> https://bootstrap-vue.org/docs/components/collapse

In your case it should be something like:

```
  <b-collapse id="collapse-3" :visible="isShown">
    <b-card>I should start open!</b-card>
  </b-collapse>
```

and

```
<script>
...
data () {
  return {
    isShown: false
  }
}
...
</script>
```
