### ISSUE TITLE
Adding a tooltip to a  b-dropdown-item-button results in 2 duplicate tooltips

### ISSUE THREAD

**Issue by xaviarnl** [bootstrap-vue/bootstrap-vue#6720]
### Describe the bug

When you add a tooltip to a dropdown-item-button, two tooltips are being rendered. This does not happen on other elements.
For example, if you have this code (taken from the documentation examples):

```
<template>
  <div>
    <b-dropdown id="dropdown-form" text="Dropdown with form" ref="dropdown" class="m-2">      
      <b-dropdown-item-button v-b-tooltip.hover="{ placement: 'top' }" title="I am a tooltip">New around here? Sign up</b-dropdown-item-button>
      <b-dropdown-item-button>Forgot Password?</b-dropdown-item-button>
    </b-dropdown>
  </div>
</template>
```

This results in 2 tooltips being rendered. A free-floating one, and one in the position as specified via the tooltip settings:
![image](https://user-images.githubusercontent.com/17512042/127493277-2e1a2f27-dfa0-4741-83bc-e4ae4b152ff3.png)

I would expect there to be only one tooltip: the one set via "v-b-tooltip".

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.3.1
- Vue: 2.6.12

**Environment:**

- Device: Windows PC
- OS: Windows 10
- Browser: Chrome, 92.0

**Comment by Hiws** [comment]
That's because the `title` is being passed on to the `<button>` element, while the tooltip is being shown on the wrapping `<li>`.
Causing two tooltips to be shown.
You can get around this by specifying the title inside the directive.
`v-b-tooltip.hover="{ placement: 'top', title: 'I am a tooltip' }"`
