### ISSUE TITLE
b-form-tags delete icon is shown twice on a tag

### ISSUE THREAD

**Issue by claubel** [bootstrap-vue/bootstrap-vue#6725]
### Describe the bug

The delete icon on a tag is shown twice on a tag. 
Even when stripping the <b-form-tags> element to its bear minimum, this situation still occurs.
I added the plugin through `Vue.use(FormTagsPlugin);`

### Steps to reproduce the bug

```
<template>
 <div>
  <b-form-tags
    v-model="value"
    remove-on-delete
    tag-pills
    tag-variant="info"
    input-id="custom-category-select" />
 </div>
</template>
```
![Screenshot 2021-08-02 at 12 09 52 PM](https://user-images.githubusercontent.com/88174595/127803210-7a73a84a-6fbf-4c2a-a970-efbd51a6bd27.png)

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.4.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS BigSur
- Browser: Chrome & Firefox

**Comment by Hiws** [comment]
What do you see if you inspect the tag in your browser?
The rendered structure of a tag should be something like this.
```html
<li>
  <span>Text for the tag</span>
  <button>×</button>
</li>
```

**Comment by claubel** [comment]
![Screenshot 2021-08-03 at 1 57 32 PM](https://user-images.githubusercontent.com/88174595/127965350-7196cda4-a812-4dd3-9dc9-ab50136f925b.png)

The structure seems to be the same.

**Comment by Hiws** [comment]
I suspect the other `x` is coming from CSS then, you'll have to inspect the elements and check the CSS.

**Comment by claubel** [comment]
Thank you, I had not thought of that.
I found a custom class which added a text-shadow to the `x`.
