### ISSUE TITLE
How use text input as a dropdown button in bootstrap-vue?

### ISSUE THREAD

**Issue by AtousaDarabi** [bootstrap-vue/bootstrap-vue#6733]
### Is your feature request related to a problem? Please describe...

A clear and concise description of what the problem is.

**Comment by AtousaDarabi** [comment]
I want to make a select search box. When click on input the dropdown opens and can type on input and filter it in dropdown. I used Input as a dropdown button. But seems dropdown makes it read-only.

<b-dropdown id="dropdown-1" text="Dropdown Button" class="m-md-2">
    <template #button-content>
      <b-form-group
          id="input-group-1"
          label="Email address:"
          label-for="input-1"
          description="We'll never share your email with anyone else."
        >
          <b-form-input
            id="input-1"
            v-model="form.email"
            type="email"
            placeholder="Enter email"
            required
          ></b-form-input>
        </b-form-group>
    </template>
    <b-dropdown-item>First Action</b-dropdown-item>
    <b-dropdown-item>Second Action</b-dropdown-item>
    <b-dropdown-item>Third Action</b-dropdown-item>
    <b-dropdown-divider></b-dropdown-divider>
    <b-dropdown-item active>Active action</b-dropdown-item>
    <b-dropdown-item disabled>Disabled action</b-dropdown-item>
  </b-dropdown>

**Comment by Hiws** [comment]
You can't do that.
As you're placing an input inside a button, which goes against the HTML 5 spec.

You'll have to find another solution.
You could also look into 3rd party solutions like <https://vue-select.org/>
