### ISSUE TITLE
Add name attribute to b-breadcrumb-item

### ISSUE THREAD

**Issue by imanmalekian31** [bootstrap-vue/bootstrap-vue#6737]
When I used the lighthouse to check measurements of accessibility, it gets a warning about "Links do not have a discernible name" and refers to breadcrumb links that don't have a name attribute.
I want you to add this prop to the breadcrumb component.
Thanks.

**Comment by Hiws** [comment]
I don't think the warning is talking about an actual `name` attribute.
At least based on [this](https://stackoverflow.com/a/51715544/8397974)  answer, it instead requires a `aria-label` when a link does not contain any text content. 
Which i would guess your breadcrumbs don't.

However, the problem remains the same as neither is possible.
I think the logical fix here would be to provide at `link-attrs` prop on `<b-breadcrumb-item>` which passes attributes on to the generated link. Similar to how `<b-nav-item>` does it.
