### ISSUE TITLE
b-drowdown split-class doesn't work

### ISSUE THREAD

**Issue by ihorbond** [bootstrap-vue/bootstrap-vue#6738]
### Describe the bug

Adding a split-class option to b-dropdown doesn't add the specified class to the classList of the element 

```
<b-dropdown 
    size="sm"
    menu-class="dd-menu"
    split-class="dd-split"
    variant="outline-info">
    <b-dd-item link-class="space-blue">Ascending</b-dd-item>
    <b-dd-item link-class="space-blue">Descending</b-dd-item>
</b-dropdown>
```

### Steps to reproduce the bug
Add <b-dropdown /> with split-class option set to your custom css class

### Expected behavior

CSS class specified in split-class option should be applied to the html element.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 3.#.#

**Environment:**

- Device: Lenovo ThinkPad
- OS: Windows 10
- Browser: [FF dev edition, Chrome]
- Version: [91.0b9, 92.x]

### Demo link

https://codesandbox.io/s/affectionate-ives-17rdh?file=/src/components/HelloWorld.vue

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
From the [split-class](https://bootstrap-vue.org/docs/components/dropdown#comp-ref-b-dropdown-props) description
> CSS class (or classes) to add to the split button

And the split mode requires you to set the `split` prop to true.

**Comment by ihorbond** [comment]
@Hiws thanks, you are right. Actually, I just realized that what I needed was toggle-class.
