### ISSUE TITLE
Bootstrap Vue Toast disapears immediately on Vue plugin

### ISSUE THREAD

**Issue by kicozaninetti** [bootstrap-vue/bootstrap-vue#6742]
Hello folks.

I want to fire toasts on event add and event remove. I have a plugin managing these events. When I fire the toasts they just blink, disappears immediately.

I have tried changing the scope from this.$bvToast.toast to this.$root.$bvToast.toast but still the same error.

My plugin is like this:

/plugins/user-actions.js

`
export default {

  install(Vue, options) {

    Vue.prototype.$addUserTalk = function (talk) {
[...]
      this.$root.$bvToast.toast('Added event '+talk.title, {
        title: 'Added event',
        autoHideDelay: 50000,
        variant: "success",
        appendToast: false
      })
    }

    Vue.prototype.$removeUserTalk = function (talkId) {

[...]

      this.$root.$bvToast.toast('The event '+talkTitle+' was removed', {
        title: 'Event removed',
        autoHideDelay: 50000,
        variant: "danger",
        appendToast: false
      })

    }

  }
}
`

This is how I call the function from the Component:

`
      addUserTalk(talk) {
        this.$addUserTalk(talk);
        this.$emit('update:selectTalk', talk);
      }
      deleteEvent(e) {
        this.$removeUserTalk(e.id);
        this.getTalks();
      }
`

**Comment by Hiws** [comment]
Have you imported both `Bootstrap` and `BootstrapVue` CSS?
Also, which version of Bootstrap do you have installed?

**Comment by kicozaninetti** [comment]
Bootstrap v5.1.0

On main.js:

import { BootstrapVue, IconsPlugin } from 'bootstrap-vue'
import UserActions from './plugins/user-actions.js'

// Import Bootstrap an BootstrapVue CSS files (order is important)
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'

// Make BootstrapVue available throughout your project
Vue.use(BootstrapVue)

// Optionally install the BootstrapVue icon components plugin
Vue.use(IconsPlugin)

// User Functions
Vue.use(UserActions);
