### ISSUE TITLE
BFormInput debounce on @input event

### ISSUE THREAD

**Issue by lsdch** [bootstrap-vue/bootstrap-vue#6744]
### Is your feature request related to a problem? Please describe...

I use a `b-input` component to trigger an API call on `@input` event with a search term. I need debouncing to minimize the number of requests sent to the API : the problem is the `debounce` prop doesn't seem to apply to events. I cannot use `v-model` in this particular case, as the data source is nested and we need to rely on `vm.$set()` method to maintain reactivity.

### Describe the solution you'd like

Apply debouncing to `@input` events.

### Describe alternatives you've considered

Of course it is possible to listen to `@change` events, but that isn't the most satisfying solution for this use-case.

**Comment by Hiws** [comment]
Use the `@update` event.
That's the event which is used to update the `v-model.`

**Comment by lsdch** [comment]
Thank you ! Much to learn I still have.
