### ISSUE TITLE
How can I get the target page number clicked by the pagination component？

### ISSUE THREAD

**Issue by jixiang0537** [bootstrap-vue/bootstrap-vue#6745]
How can I get the target page number clicked by the pagination component？

**Comment by lichaozhy** [comment]
Use `v-model`,
```html
<b-pagination
      v-model="currentPage"
      :total-rows="rows"
      :per-page="perPage"
      aria-controls="my-table"
></b-pagination>
```
https://bootstrap-vue.org/docs/components/pagination

**Comment by jixiang0537** [comment]
Thank you. This code can get the current page number, but I want to get the number of the currently clicked button. Maybe there's something wrong with my code.
` <b-pagination
                    v-model="currentPage"
                    :total-rows="rows"
                    :per-page="perPage"
                    first-number
                    last-number
                    @page-click="test(currentPage)"
></b-pagination>`

**Comment by Hiws** [comment]
> Thank you. This code can get the current page number, but I want to get the number of the currently clicked button. Maybe there's something wrong with my code.
> ` <b-pagination
> v-model="currentPage"
> :total-rows="rows"
> :per-page="perPage"
> first-number
> last-number
> @page-click="test(currentPage)"
> 
> > `

Yes, that's wrong.
You're overwriting the default arguments from the `@page-click` event by passing in your own.

```html
<b-pagination @page-click="onPageClick" />

onPageClick(event, page) {
  console.log("Clicked page", page);
}
```

**Comment by jixiang0537** [comment]
Thank you. Your reply perfectly solved the problem I encountered. I didn't find an answer to this question in the document. Thank you again for your help.
