### ISSUE TITLE
Multiple ShowDetails

### ISSUE THREAD

**Issue by sawagroupdeveloper** [bootstrap-vue/bootstrap-vue#6750]
Show Multiple ShowDetails ?

**Comment by Hiws** [comment]
Could you provide a bit more information about what you want?

**Comment by sawagroupdeveloper** [comment]
i have a contact information and address information and more details
i added 3 field contact_details, address_details, more_details
They are all different from each other

**Comment by Hiws** [comment]
You can't.
There's only one `row-details` slot.
You can instead use a `v-if` and `v-else` to determine which information should be shown.
