### ISSUE TITLE
https://bootstrap-vue.org/    Cannot access

### ISSUE THREAD

**Issue by gang0713** [bootstrap-vue/bootstrap-vue#6757]
https://bootstrap-vue.org/    Cannot access

**Comment by Hiws** [comment]
Some people have issues accessing the docs for some reason.
Usually from specific parts of the world, if it doesn't come back online for you, you can instead run the docs locally or upload them to your host of choice.

Here's some instructions on how to do so
<https://github.com/bootstrap-vue/bootstrap-vue/issues/6633#issuecomment-849486998>
