### ISSUE TITLE
[button-toolbar] Event delegation

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#676]
Have a look at the event listeners here: https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/button-toolbar.vue#L6-L13

Maybe we can listen once to all keydown events and delegate from within the listener. Seems like it would be less memory to use one listener rather than eight.

**Comment by tmorehouse** [comment]
Yeah, could look at one event, (Or maybe two) and then look at the key that is pressed and make a determination. Although the modifiers on the `@keydown` and nice and clear as to what is going on.

**Comment by alexsasharegan** [comment]
Yeah, the semantic value is great (and Vue may normalize key codes), but I'm thinking that we can err on the side of performance as a library. I'm partial to switch statements in cases like this since they tend to be more easy to reason about than conditionals.

**Comment by tmorehouse** [comment]
Yeah, we just might need to normalize the keycode parameter based on browser.

**Comment by tmorehouse** [comment]
I'll fiddle with this on Sunday when I get back home.

**Comment by alexsasharegan** [comment]
Maybe this is too micro optimized. Check out this forum post: https://forum.vuejs.org/t/is-event-delegation-necessary/3701/3
