### ISSUE TITLE
Docs: <b-tabs> - please provide example code for property "value"

### ISSUE THREAD

**Issue by udos** [bootstrap-vue/bootstrap-vue#6761]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [X] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs/components/tabs#comp-ref-b-tabs-props

### Additional context or description

could you please add an example which explains the use of property "value" -> probably I'm just to blind to see/figure it out :|

**Comment by sidneygijzen** [comment]
An example of using the `value` property is provided on that page under heading ["External controls using v-model"](https://bootstrap-vue.org/docs/components/tabs#external-controls-using-v-model). A more general explanation of the concept is provided under the heading ["Programmatically activating and deactivating tabs"](https://bootstrap-vue.org/docs/components/tabs#programmatically-activating-and-deactivating-tabs).

Does that provide the info you're looking for?
