### ISSUE TITLE
Language bug using props

### ISSUE THREAD

**Issue by CutiePie94** [bootstrap-vue/bootstrap-vue#6766]
### Describe the bug

Hello! I changed my date-picker to language 'de' but the props are still in english. Is there a way to change these too?

### Steps to reproduce the bug

````
  <b-form-datepicker
    id="datepicker-buttons"
    today-button
    reset-button
    close-button
    locale="de"
    v-model="absonderungsDate"
    :start-weekday=1
  ></b-form-datepicker>
````
<img width="202" alt="date" src="https://user-images.githubusercontent.com/58289178/132031922-15c8b2f7-cbca-4c61-b809-7946fd159c05.PNG">

**Comment by Hiws** [comment]
The `locale` prop only controls the language for the calendar itself.

For the buttons and other text you'll have to change those using the various props, like `label-nav`, `label-help`, ect..
<https://bootstrap-vue.org/docs/components/form-datepicker#comp-ref-b-form-datepicker>

**Comment by CutiePie94** [comment]
Thank you very much!
