### ISSUE TITLE
<b-table> breaks layout constraints defined by row, col

### ISSUE THREAD

**Issue by reviewingcode** [bootstrap-vue/bootstrap-vue#6767]
### Describe the bug

`<b-table>` with too many columns (enough to activate horizontal scroll) breaks the grid (row, col) and forces a 2 column layout into single column layout.

### Steps to reproduce the bug

1. Here's a minimal reproduction of the issue [jsfiddle](https://jsfiddle.net/e5196mcf/).
2. The issue is visible at `md` size screen for me.

### Expected behavior

It should be a single row, 2 column layout at `md` size, but instead it shifts to a single column, 2 row layout.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.14

**Environment:**

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: Version 93.0.4577.63 (Official Build) (64-bit)

### Demo link

https://jsfiddle.net/e5196mcf/

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
That's not really an issue with the table, and more so how flex works with large content that can't be wrapped. (like a table).

Youhave to specifically disallow wrapping using the `flex-nowrap` utility class.
<>

**Comment by Hiws** [comment]
That's not really and issue with the table, and more of an issue of how flex works, with content that it can't nicely break up (like a table).

You can get around this by specifically disallowing wrapping, using the `flex-nowrap` utility class.
<https://jsfiddle.net/20g1jubL/>

**Comment by reviewingcode** [comment]
@Hiws Thanks for your reply.

The solution kinda works, but unfortunately it breaks the layout below `md` screen size for me (as I have a bit different grid setup than in the above fiddle). 
I was able to isolate the issue to the prop `no-gutters` on `b-row`. Though it also happens if I delete that prop and instead reduce the padding by using class `px-0` or padding styles.

Here's an up to date [fiddle](https://jsfiddle.net/reviewingcode/cbfeLr6h/31/) which very closely matches with my local setup.

I'm also a bit confused about why does this happen, as I was under the impression that the grid setup by row, col is enforced on all children. Unless of-course a child overwrites the CSS. So is that the case here with table?

Just a note, I have also tried this with Bootstrap v4.6.0. Same issue on both.

**Comment by Hiws** [comment]
You'll need to add some col definition on the col that contains the table.
`col-12` for mobile so it occupies the entire row, and then `md` to overwrite that for desktop, and let it occupy the remaining available space.

You'll also need to add `class="overflow-auto"`, to allow the col to scroll instead of having the table overflowing.
Depending on whether you want to entire col to scroll, or just the table. 
You can add back the `responsive` prop on the table, if you only want that to be scrolling, instead of the entire col. (you'll still need `overflow-auto` on the col).

<https://jsfiddle.net/kgvrtfe5/>

**Comment by reviewingcode** [comment]
This is perfect! Issue solved.

That `md` prop to overwrite `cols` for desktop is a bit of magic for me though. 😄 Didn't know I could do that as I thought it always accepts a value. Probably need to pay more attention to docs.

Thanks for your help 👍
