### ISSUE TITLE
Creating modals on the fly

### ISSUE THREAD

**Issue by robcresswell** [bootstrap-vue/bootstrap-vue#677]
Sorry for the vague header. I'm coming from an Angular 1.x background and learning Vue. UI-Bootstrap had a rather nice way of generating modals (https://angular-ui.github.io/bootstrap/#!#modal) so that you didn't have to pre-define the modal and then show/hide it; rather, you would create the modal element and then show it, and when closing, destroy it. This is useful, for example, when there might be the potential for nested modals and you don't want to have to keep defining them.

Is there a neat way to do this in Vue?

**Comment by tmorehouse** [comment]
Currently each modal is inserted into your doc via the b-modal component. Dynamically generating document fragments and inserting them in the document somewhere is no d of frowned upon in vue, as document content should be rendered by components or app markup. 

The issue is removing the inserted nodes when the parent component goes put of scope and is removed from the page (all these stranded nodes chew up dom and memory space).

Typically one would create a component that contains a few modals that you would send content to (via state management or via emitted events), and then the modal would emit back to the calling component when it closes..

You can also place a modal in wherever you need one, and v-if it in and out of the document as you need it.

**Comment by mosinve** [comment]
Vue has the ability to create components on-fly. I think I can try to do this as an extra-component functional.

**Comment by robcresswell** [comment]
The example in my head is using modals as table row actions, or with nested modals. Clearly you don't want to create a modal fragment per row action ahead of time; so it'd be more practical to have a "dead" modal just sitting in your markup until it gets used. That just... bothers me a little, I guess :) Similarly, each modal would have to contain *another* modal if you wanted to launch one action from within another.

**Comment by alexsasharegan** [comment]
@robcresswell, the sequence of modals scenario really intrigues me. I've run into that with various tos acceptance flows, and stubbing out modal shells is far from optimal in that scenario.

I haven't used Vue to create disposable, sequenceable components yet. I don't feel like this is something well defined yet in the community (best practices, patterns, etc). I'm sure we can figure something out though!

**Comment by robcresswell** [comment]
Its not an uncommon pattern. You might be working on a longer workflow (say, 3 steps) in a modal workflow, and as part of that, want to pop open a smaller one over that to generate something.

The cleanest way I could see with the current design would be to have each modal template contain a sort of "sub modal" template. That way, one can always be launched. And then your base view always has a modal template in the tree, hidden. Personally, I think this is an ugly pattern, just leaving nodes sat there hidden.

My ideal solution, I think, would be to insert the modal when its required. I wonder if this might cause performance issues with rendering though (like a couple of dropped frames)

**Comment by tmorehouse** [comment]
THe only issue with dynamically inserting content that is elsewhere in the document, is ensured removal of the elements/nodes that are not under direct control of Vue.

Definitely possible though.

**Comment by tmorehouse** [comment]
Vue really doesn't have a mechanism for injecting components on the fly (except maybe with vue-router and the like).

You can use the `<component :is="[component or tag name]"></component>`, which has to be placed somewhere in the doc, and controlled by changin the `:is="..."` part on the fly.

In `b-table` docs example we do you a single modal to display the content of each row when `details` clicked.

**Comment by robcresswell** [comment]
I've checked the table docs, and it still has some pretty big restrictions around its usage. Even in your example, the modal knows what its going to be displaying ahead of time.

One suggestion, which might make things slightly easier, would be to have a whole `modal-body` or `modal-content` slot; at least that way, the entire modal contents could be replaced by a `<router-view />` element so child routes can render to them, without the table component having to hard-code any knowledge of the content that the modal displays.

**Comment by robcresswell** [comment]
Also I know you're keen to keep the bug count down, but it'd be nice if you'd let me respond before closing it 😄 I'm just trying to provide feedback to help improve on a generally great library.

**Comment by robcresswell** [comment]
I think I figured out what I wanted to do; having a `<router-view />` in the table page and the modal component (visible by default) in a child route seems to let me make progress.

**Comment by mosinve** [comment]
@robcresswell also, you can check this example https://jsfiddle.net/cihkem/r7y5ydpq/, maybe it will work for you somehow

**Comment by robcresswell** [comment]
I'll take a look; thanks again for the feedback / help.
