### ISSUE TITLE
Cant update package

### ISSUE THREAD

**Issue by wanderguzman** [bootstrap-vue/bootstrap-vue#678]
im currently stucked on 0.16.1  I tried to update/reinstall the npm package but its not getting updated. Im trying to get the 0.18.0.

**Comment by alexsasharegan** [comment]
@wanderguzman, can you give us some details on the following:

- What package manager are you working with?
- What upgrade command are you running?
- What is the output?

**Comment by wanderguzman** [comment]
I have a project that is using the version 0.16.1 . when i run the command: npm install bootstrap-vue or npm update bootstrap-vue it doesnt install the new version as it says the version updated/installed is still 0.16.1

**Comment by alexsasharegan** [comment]
Chances are this is a semver restriction. Since v0.18 is a minor version bump, npm might not be upgrading your dependency. Try this:

```sh
npm rm bootstrap-vue && npm i  -P bootstrap-vue
```

P.S. I'm running npm v5.1.0

**Comment by alexsasharegan** [comment]
Have you tried uninstalling and re-installing yet, @wanderguzman ?

**Comment by wanderguzman** [comment]
Yes I tried by running npm uninstall and the command you sent me but still I can't get the latest version

**Comment by alexsasharegan** [comment]
Paste in your `package.json` contents, if you don't mind. I'll have another look.

**Comment by wanderguzman** [comment]
After uninstalling updating npm and cleaning cache it started to work.

**Comment by alexsasharegan** [comment]
Awesome! Those bugs are such a pain.
