### ISSUE TITLE
Checkbox shows as checked when checked prop is false

### ISSUE THREAD

**Issue by pager1** [bootstrap-vue/bootstrap-vue#6788]
### Describe the bug

A `b-form-checkbox` checkbox is incorrectly showing that it is checked when using the `checked` prop (instead of `v-model`) and the value of the prop is `false` and the checkbox was previously in an `indeterminate` state.

### Steps to reproduce the bug

1. Go to https://codepen.io/pager1/pen/abwaMad
2. Select some of the sub-checkboxes inside a category but not all of them (e.g only 'a' and 'b' in 'letters')
3. Click on the indeterminate checkbox for the category, which should uncheck the whole category
4. See that the sub-checkboxes are correctly unchecked, the category checkbox is incorrectly checked, and the following message appears in the console to confirm the expected checked state of the category
    > Category 'letters' should be unchecked
5. Click the category checkbox again and see that it stays checked (which is now correct), and the following message appears in the console to confirm the expected checked state of the category
    > Category 'letters' should be checked

### Expected behavior

When clicking the indeterminate checkbox for a partially selected category of checkboxes, all checkboxes for the category should become unchecked (including the indeterminate checkbox) as they all have a value of `false` for the prop `checked`.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Vue: 2.6.12

**Environment:**

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 92.0

### Demo link

https://codepen.io/pager1/pen/abwaMad

### Additional context

N/A

**Comment by gmw-web** [comment]
duplicate of #6648
