### ISSUE TITLE
Bootstrap modal does not show. Is hidden due to incorrect opacity

### ISSUE THREAD

**Issue by martijnhiemstra** [bootstrap-vue/bootstrap-vue#679]
I am using vue2 with bootstrap and I can't get the modal to show. I have discovered that there is an error in the styling. I don't know if it's bootstrap or vue styling that is casuing this. To get the modal to show I need to update my css with this:

.modal-open .modal-backdrop {
  opacity: 0.6 !important;
}

.modal-open .modal {
  opacity: 0.9 !important;
}

Also the top is completely off. I can't see the header of the modal so I also need to update the top of the modal. All in all there are some css issues with the Modal.

My dependancies in packages.json looks like this:

"dependencies":  {
    "axios": "^0.16.2",
    "bootstrap": "^3.3.7",
    "bootstrap-vue": "^0.18.0",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
    "vue": "^2.3.4",
    "vue-awesome": "^2.3.1",
    "vue-resource": "^1.3.4",
    "vue-router": "^2.7.0"
  },

**Comment by alexsasharegan** [comment]
Bootstrap-Vue is intended for use with the latest Bootstrap (v4 alpha). You can include it from this library at `"bootstrap-vue/dist/bootstrap-vue.css"` or update your dependency 

```sh
npm i bootstrap@4.0.0-alpha.6
```

**Comment by martijnhiemstra** [comment]
Even though I'm completely against using a alpha version I tried that version just to see if that works. Unfortunately the styling in 4.0.0-alpha.6 is completely messed up. Colors not looking like before. Tables looking weird, not huge things just not ready for production.

**Comment by alexsasharegan** [comment]
I'm using alpha in production on multiple sites without anything _"messed up"_. Are you addressing personal taste, or actual broken css?

There is a Bootstrap 3 for Vue library available (https://yuche.github.io/vue-strap/), but the project is still on Vue `1.x`.

**Comment by alexsasharegan** [comment]
Feel free to keep the conversation going, but as this is just an issue with dependency resolution, I'm going to close this.
