### ISSUE TITLE
[toggle directive] Root listener cleanup

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#680]
We've had issues with using `$root` listeners before (https://github.com/bootstrap-vue/bootstrap-vue/issues/569), since the listener is not cleaned up by vue when the instance is destroyed. Chances are we could run into trouble with this directive listener: https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/directives/toggle.js#L20-L24

**Comment by alexsasharegan** [comment]
I'm not sure how easy it is to unbind the listener, because it is generated with scope on the `el`

**Comment by tmorehouse** [comment]
Might be able to do this on the `unbind` stage, as vnode is provided on unbind.

Would may also need to address the `_taget` bindings as well, although they are bound of the element.

**Comment by tmorehouse** [comment]
Hmm, it might be harder for toggle, as there is no `this` context to reference a handler specific to this element.

If we make a common handler function (outside of the export), then we loose the uniqueness of the handler that is associated with that particular element when trying to unbind the $root.on (it would end up removing all handlers associated the the event).

**Comment by alexsasharegan** [comment]
Exactly. The closure scoping is what really makes this messy. Can't save a reference because it has to be generated at binding time.

**Comment by tmorehouse** [comment]
The only way might be to create a n array of bindings, and somehow key it based on the node instance.

**Comment by alexsasharegan** [comment]
Yeah, I was thinking the same with a uniquely keyed dictionary, but either way, how to store the index/key of the handler? Maybe using a data attribute on the element?

**Comment by mosinve** [comment]
maybe it's a time to stop using $root as event bus? and implement standalone event bus. @tmorehouse, remember, that we discuss?

**Comment by alexsasharegan** [comment]
```js
import { create } from "../utils/object"
import { uid } from "../utils"
const inBrowser = typeof window !== "undefined"

import target from "./_target"
const listen_types = { click: true }

let cache = create(null)

export default {
    bind(el, binding, vnode) {
        const targets = target(vnode, binding, listen_types, ({ targets, vnode }) => {
            targets.forEach(target => {
                vnode.context.$root.$emit("collapse::toggle", target)
            })
        })

        if (inBrowser && vnode.context && targets.length > 0) {
            const _uid = uid()
            el.setAttribute("aria-controls", targets.join(" "))
            el.setAttribute("aria-expanded", "false")
            el.dataset.vBToggleId = _uid

            cache[_uid] = function toggleDirectiveHandler(id, state) {
                if (targets.indexOf(id) !== -1) {
                    el.setAttribute("aria-expanded", state ? "true" : "false")
                }
            }

            vnode.context.$root.$on("collapse::toggle::state", cache[_uid])
        }
    },

    unbind(el, binding, vnode) {
        vnode.context.$root.$off("collapse::toggle::state", cache[el.dataset.vBToggleId])
    }
}
```

**Comment by mosinve** [comment]
i wonder if the same can be done with weakMap or weakSet?

**Comment by alexsasharegan** [comment]
Totally! But that would add another polyfill.

**Comment by tmorehouse** [comment]
Event bus would be nice as well, although would need to be injected into all components, and would change how users use emitting on $root to trigger events.

**Comment by alexsasharegan** [comment]
There is an inject API now. https://vuejs.org/v2/api/#provide-inject

**Comment by mosinve** [comment]
Event bus may be assigned to Vue.prototype.eventbus at bootstrap-vue install function.

**Comment by alexsasharegan** [comment]
Would we need to namespace our own bus?

**Comment by tmorehouse** [comment]
yeah, we probably should to avoid coflicts

**Comment by tmorehouse** [comment]
What about placing a private property on the root vnode element? which would contain a reference to the listeners, or can we add a new piece of data in the component during bind? (i.e. `__BV__root_listeners` which would be an array of root listener events and code reference?  maybe the same prop the `listenOnRoot` mixin uses?
