### ISSUE TITLE
Modal closes always on ok button

### ISSUE THREAD

**Issue by martijnhiemstra** [bootstrap-vue/bootstrap-vue#681]
I have a modal and I have everything working except that when I click on the OK button the modal dissapears. I want to keep the modal open if there are errors in the supplied data.

My modal looks like this:
`
<b-modal id="editModal" :title="editModalTitle" @ok="saveData" @close="clearData" hide-header-close>
`

I have tried returning false in saveData(e) { return false; } however that doesn't work

**Comment by alexsasharegan** [comment]
Check out the docs on the `modal` component under **Prevent Closing**: https://bootstrap-vue.js.org/docs/components/modal#prevent-closing

You should be able to call `e.cancel()` in the `@ok` handler. Keep in mind that this is done synchronously, so any async stuff will require cancelling synchronously, and then manually closing in the async callback logic.

**Comment by martijnhiemstra** [comment]
Fantastisc. Works like a charm. Been a long day so I missed that part in the docs.

**Comment by alexsasharegan** [comment]
No worries! Just wanted to make sure I passed along the resources. Always good to leave a link for posterity :wink:

**Comment by chamra** [comment]
I have tried this but I get an error `evt.preventDefault is not a function`

**Comment by AlfredoDaAs** [comment]
Not working for me, not even with a simple handleOk(e) { e.preventDefault() }

**Comment by jonalxh** [comment]
@chamra Try with the following:

```
// In your template section
<b-modal @ok="validate"></b-modal>

// In your methods (script) section
validate(evt) {
   evt.preventDefault() // It will prevent modal dismiss
}
```

**Comment by fmmattioni** [comment]
Simply `@ok.prevent` does the trick:

```js
<b-modal @ok.prevent="foo"></b-modal>
```
