### ISSUE TITLE
How do I get rid of [Vue warn]: Invalid prop: type check failed for prop "value".

### ISSUE THREAD

**Issue by Dhaxor** [bootstrap-vue/bootstrap-vue#6816]
I have a <b-form-file/> that throws warning of  [Vue warn]: Invalid prop: type check failed for prop "value". Expected Array, File, got String with value 'test.jpg'. The issue is because I'm passing a value of string to a file input and I really  need to do that without the warnings.

**Comment by Hiws** [comment]
<https://bootstrap-vue.org/docs/components/form-file#clearing-the-file-selection>
> **With inputs of type file, normally the v-model is uni-directional (meaning you cannot pre-set the selected files)**. However, you can clear the file input's selected files by setting the v-model to either null (for single mode) or an empty array [] (for multiple/directory mode).

I assume your `imagePreview` variable has a pre-defined string value?

**Comment by Dhaxor** [comment]
> 
> 
> https://bootstrap-vue.org/docs/components/form-file#clearing-the-file-selection
> 
> > **With inputs of type file, normally the v-model is uni-directional (meaning you cannot pre-set the selected files)**. However, you can clear the file input's selected files by setting the v-model to either null (for single mode) or an empty array [] (for multiple/directory mode).
> 
> I assume your `imagePreview` variable has a pre-defined string value?

Yes

**Comment by Dhaxor** [comment]
Wow. So no walk around that?
