### ISSUE TITLE
[dropdown] menu closes and re-opens after click on item

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#683]
I have the following dropdown (in a larger template, but I dont think that matters):
```
<b-nav-item-dropdown text="Tags">
  <b-dropdown-item to="/tag">Tags</b-dropdown-item>
</b-nav-item-dropdown>
```

When I click on the dropdown-item I expect the dropdown menu to close and stay closed, but actually it only closes for a brief moment and then opens again. See below for the event output, am I missing something or is this an unwanted feature?

![image](https://user-images.githubusercontent.com/1067403/28091840-a7c622b6-6691-11e7-8783-de65dcd77ed0.png)

**Comment by alexsasharegan** [comment]
This may be linked to #569 . I'll check back later if I have any info.

**Comment by tmorehouse** [comment]
Would this be if you use local routing (on browser) to switch from one page and then to another which also has a dropdown used as navigation?

**Comment by pimlie** [comment]
@tmorehouse, the dropdown is part of my default layout in a nuxt project. So navigating happens indeed in the browser only through vue-router.

**Comment by tmorehouse** [comment]
OK, so it might be related to possible "leftover" listeners.

**Comment by alexsasharegan** [comment]
I feel pretty confident that the fix we used for #569 will clear this up. I'm not entirely sure I can replicate the bug on my end though.

**Comment by pimlie** [comment]
never mind :blush:

It seems this project was still yarn linked to my bootstrap-vue dev folder which _was_ on the master branch but not rebuilded. Noticed this as I wanted to add some debug info but the issue was immediately gone after I ran yarn watch. Sorry!

**Comment by alexsasharegan** [comment]
Thanks for the update! I think we may still sweep other root listeners into the clean up mixin.
