### ISSUE TITLE
Replace Sass division with multiplication and custom divide() function

### ISSUE THREAD

**Issue by lagset** [bootstrap-vue/bootstrap-vue#6830]
### Describe the bug

For sass versions greater 1.32.13 [this breaking change](https://sass-lang.com/documentation/breaking-changes/slash-div) applies to some bootstrap-vue .scss files.

This results in deprecation warnings blocking compilation when using sass > 1.32.13.

[This PR](https://github.com/twbs/bootstrap/pull/34571) resolves the issues in bootstrap v.4.6.1, released a couple of days ago. Do you plan to fix this for bootstrap-vue as well?

**Comment by jonybekov** [comment]
I need this PR released asap

**Comment by digEmAll** [comment]
Yes, same problem here
