### ISSUE TITLE
reponsive not working

### ISSUE THREAD

**Issue by Dhaxor** [bootstrap-vue/bootstrap-vue#6831]
For some reason the responsive prop does not work for my table.

                ```<b-table
			id="table-transition-example"
			:busy.sync="isLoading"
			responsive
			:items="fetchData"
			:fields="fields"
			:current-page="currentPage"
			:per-page="perPage"
			striped
			small
			:head-variant="'dark'"
		>
		</b-table>```

That's an example of my code

**Comment by sidneygijzen** [comment]
Hi! Thanks for the report. 

Is this still an issue? If so, can you please provide some more information by filling out [the bug report template](https://github.com/bootstrap-vue/bootstrap-vue/blob/4222833b5d74e5a38c1ded814cc3a550c743dce1/.github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md). 

Thanks :slightly_smiling_face:
