### ISSUE TITLE
Typo in "Theming Bootstrap" documentation section

### ISSUE THREAD

**Issue by austin-dudzik** [bootstrap-vue/bootstrap-vue#6833]
### Documentation issue

- [x] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs#theming-bootstrap

### Additional context or description

Typo in the Bootstrap SCSS customization code block comment in the "Theming Bootstrap" section of the BootstrapVue documentation (see screenshot)

"Then import Bootstrap an BootstrapVue SCSS files (order is important)"

should be....

"Then import Bootstrap and BootstrapVue SCSS files (order is important)"

![image](https://user-images.githubusercontent.com/65981261/140594285-41880dd3-66c3-4722-b6d0-4c30ebe92c0a.png)

**Comment by Hiws** [comment]
There's an open PR which fixes this: https://github.com/bootstrap-vue/bootstrap-vue/pull/6698
