### ISSUE TITLE
Is there any way to align the icon next to the column name while using the b-table ?

### ISSUE THREAD

**Issue by rajmondburgaj** [bootstrap-vue/bootstrap-vue#6838]
I checked the documentation but I could not find any useful example or if this is doable.
Basically below is what I want to achieve..

![image](https://user-images.githubusercontent.com/7545874/141382484-5a154301-a32f-4482-8e46-1bd8dc052385.png)

and this is what I have:

![image](https://user-images.githubusercontent.com/7545874/141382532-baf8efbf-50b4-49c6-ac24-088a0ad5e26a.png)

Is there any quick way to align those sorting icons next to the column name ?

Below is the code:

```
      <b-table
        v-cloak
        :key="'id'"
        :busy="$fetchState.pending"
        :fields="fields"
        :items="configurationContexts"
        :filter="filter"
        hover
        borderless
        :filter-included-fields="['name']"
        show-empty
        thead-tr-class="h5"
      >
     </b-table>
````

**Comment by Hiws** [comment]
See: https://github.com/bootstrap-vue/bootstrap-vue/issues/5847

**Comment by rajmondburgaj** [comment]
> 
> 
> See: #5847

Hi @Hiws , thanks a lot for the information, will close the ticket now, would be nice if a simple example using this approach is also documented because a lot of people I guess want to align the icon that way.
