### ISSUE TITLE
tdClass function doesn't run when b-table is in b-collapse tag

### ISSUE THREAD

**Issue by npltr62** [bootstrap-vue/bootstrap-vue#6849]
All in the title 
my tdClass function not rendered when i use table in accordion component.
here is a [fiddle](https://jsfiddle.net/npltr62/fhurpbtq/16/)

**Comment by Hiws** [comment]
Yeah, the "method detection" when passing the method name as a string is a bit funky at times.

I'd suggest you pass the method reference directly instead. 
That should solve your issue.
`tdClass: this.ipr_class`

<https://jsfiddle.net/j0wxoake/>

**Comment by npltr62** [comment]
@Hiws yes it's working 
thank's for your help
