### ISSUE TITLE
Support for Bootstrap 5?

### ISSUE THREAD

**Issue by nicksterious** [bootstrap-vue/bootstrap-vue#6852]
With all the new phones and phablets released recently, Bootstrap 5 is becoming a necessity.

Any plans to bump Bootstrap to v5+?

Cheers 
N

**Comment by Hiws** [comment]
I'd suggest you check the pinned issues: https://github.com/bootstrap-vue/bootstrap-vue/issues/5507

However, the library is currently not being maintained.
So i wouldn't wait around for it.
