### ISSUE TITLE
Bootstrap-vue current state of life

### ISSUE THREAD

**Issue by Ericlm** [bootstrap-vue/bootstrap-vue#6853]
When looking at the number of opened issues and PR, and the very low activity on commits, I was wondering if Bootstrap-vue still actively maintained ?

**Comment by Hiws** [comment]
It is not.

**Comment by Ericlm** [comment]
Okay, very efficient answer 😅 But too sad.

**Comment by sowinski** [comment]
Is there an alternative framework for vue? (like bootstrap vue?)

**Comment by Ericlm** [comment]
@sowinski, you can use [Vuetify](https://vuetifyjs.com/en/), [Quasar](https://quasar.dev), or [Buefy](https://buefy.org) for example.

**Comment by Jogai** [comment]
> Is there an alternative framework for vue? (like bootstrap vue?)

There is [bootstrap-vue-3](https://github.com/cdmoro/bootstrap-vue-3), but personally I'm using [primevue](https://github.com/primefaces/primevue/). Primevue is backed by a company and while the vue3 version has the most development they're still maintaining the vue2 version.

Anyway, I think its best if this is more clearly communicated in the repo

**Comment by mrholek** [comment]
> Is there an alternative framework for vue? (like bootstrap vue?)

Self promotion warning :)

We create our own Bootstrap 5 components library for Vue 3 https://github.com/coreui/coreui-vue

**Comment by Hiws** [comment]
> Self promotion warning :)

Once in a thread is fine 😉

**Comment by literakl** [comment]
That is very sad. So many users, stars and even sponsors (budget 20 178,05 $), I have hoped this will live long and well.

**Comment by vladimirjegorov** [comment]
Is there any background on what has happened (why it was abandoned) and future plans?

**Comment by xanf** [comment]
Status update for everyone: https://github.com/bootstrap-vue/bootstrap-vue/issues/6872

I invite everyone to join discussion there :)
