### ISSUE TITLE
Modal on table

### ISSUE THREAD

**Issue by Soraia55** [bootstrap-vue/bootstrap-vue#686]
Hi there! 

I'm facing two problems that I can't seem to solve by my self. 
So, I have this [fiddle](https://jsfiddle.net/g6vk8sqa/)  that has a table and when a row is clicked the rowClicked method is called. 
The first problem is that when I click on 'details' button it is supposed to open a modal but since I'm also clicking on a row the event @row-clicked also gets triggered but in this case, I only want the modal to open. So, is there a way to solve this? 

The second problem I'm facing is that if I copy and paste that fiddle to my computer, the modal in this case never opens, it only shows the grey background of the modal. But I've used it outside tables and works fine, these are my dependencies: 

`"dependencies": {
    "axios": "^0.15.3",
    "bootstrap": "^4.0.0-alpha.6",
    "bootstrap-vue": "^0.18.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "jquery": "^3.2.1",
    "postcss-load-config": "1.2.0",
    "postcss-loader": "1.3.3",
    "url-loader": "^0.5.8",
    "vue": "^2.3.4"
  },
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-preset-latest": "^6.0.0",
    "bootstrap-loader": "^2.0.0",
    "cross-env": "^3.0.0",
    "css-loader": "^0.25.0",
    "file-loader": "^0.9.0",
    "style-loader": "^0.15.0",
    "vue-loader": "^11.1.4",
    "vue-router": "^2.3.0",
    "vue-template-compiler": "^2.3.4",
    "webpack": "^2.2.0",
    "webpack-dev-server": "^2.2.0"
  }`

**Comment by tmorehouse** [comment]
For your details button, use `@click.stop="myDetailsHandler"`.  This will stop the event from bubbling up and triggering `row-clicked`


The second issue you are having is due to the order of hte CSS imports.  There is another issue open (or might be closed) on this with a solution.

**Comment by alexsasharegan** [comment]
As an additional note, you may have to use `click.native.stop`, as I'm not sure if the event modifiers work on the vue click event the button component triggers. Try it first without, but if the event still bubbles up, add the `.native` in before stop.

**Comment by tmorehouse** [comment]
I believe the `@click.stop` should work (as it worked on some checkboxes I have placed into tables before).

**Comment by Soraia55** [comment]
Hi! 
I didn't need `@click.native.stop`, it worked fine just with `@click.stop`. I've also solved the second part of my problem finding the issue @tmorehouse mentioned.

Thanks!
