### ISSUE TITLE
Dynamic Slots for raw html table outputs

### ISSUE THREAD

**Issue by tertek** [bootstrap-vue/bootstrap-vue#6861]
I need to set all cells of a table to raw HTML dynamically.
The docs are suggesting to use:

    <b-table :items="items">
      <template #cell(html)="data">
        <span v-html="data.value"></span>
      </template>
    </b-table>

Where `html` is the static name of the item to be rendered in raw HTML. 

I have tried something like this which is failing since I cannot think of the correct syntax for  [Dynamic Slot Names](https://vuejs.org/v2/guide/components-slots.html#Dynamic-Slot-Names):

    <b-table :items="items">
            <template v-for="item in items" v-slot:cell([item])="data">
              <span :key="item.value" v-html="data.value"></span>
            </template>
    </b-table>

What exactly is #cell(xxx)? How can I pass this dynamically so that all items get rendered as raw html?

**Comment by Hiws** [comment]
Use the `cell()` slot, which is the fallback slot for all cells.
```html
<b-table :items="items">
  <template #cell()="{ value }">
    <span v-html="value"></span>
  </template>
</b-table>
```

> You can use the default fall-back scoped slot 'cell()' to format any cells that do not have an explicit scoped slot provided.
<https://bootstrap-vue.org/docs/components/table#scoped-field-slots>

**Comment by tertek** [comment]
Perfect!
