### ISSUE TITLE
BPaginationNav - access to the original click event to stop navigation

### ISSUE THREAD

**Issue by nullday0** [bootstrap-vue/bootstrap-vue#6864]
It seems like there is no access to the original event in `BPaginationNav`. 
Ref: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/pagination-nav/pagination-nav.js#L121

Why would I need that? I would like to use `BPaginationNav` just to generate `<a>` with proper `href`s for SEO purposes. But I want to handle all the navigation myself. So, if I just call `bvEvent.preventDefault()` it doesn't prevent the original click on the link element. It just prevents component from executing its further logic. Even if I click on active page it doesn't require `preventDefault` to stop the logic, but navigation happens anyway. So, in my case the navigation happens all the time after the click, either with `use-router` or without. And I would like to prevent this navigation and handle it with my own logic in the parent component.

I was thinking about solving this issue with `BPagination` component, but I cannot inject `<a>` inside the page button because it's always wrapped in `<button>` so it becomes non-semantic.

Is there any way I can achieve my goal without modifying the original `BPaginationNav` component or watching`$route` globally? Thanks.

**Comment by nullday0** [comment]
Here is a possible solution if you really need to implement what I described above:
```
import { BPaginationNav } from 'bootstrap-vue'
const BPaginationNav2 = BPaginationNav.extend({
  methods: {
    onClick (event, pageNumber) {
      this.$emit('page-click2', event, pageNumber)
      // BPaginationNav.options.methods.onClick.call(this, event, pageNumber)
    }
  }
})
```

**Comment by jonathan-rvezy** [comment]
Opened this PR https://github.com/bootstrap-vue/bootstrap-vue/pull/6943
