### ISSUE TITLE
b-form-input @update event returns empty string

### ISSUE THREAD

**Issue by alexdohm** [bootstrap-vue/bootstrap-vue#6868]
### Describe the bug

I have a form that uses b-form-input to input a number. If a user inputs a number "1.", the update event returns an empty string. On my friends computer, "1." returned the correct string, but "1," returns an empty string. 

### Steps to reproduce the bug

See pen below

### Expected behavior

@update returns "1" instead of an empty string

### Versions

**Libraries:**

- BootstrapVue: 2.12.2
- Vue: 2.6.14

**Environment:**

- Device: Mac
- OS: macOS Monterey
- Browser: Chrome
- Version: 96

### Demo link

https://codepen.io/teknopup/pen/MWEbMXe

**Comment by Hiws** [comment]
> On my friends computer

What environment is your friend testing this on?
I'd suspect this is different browser behavior.

**Comment by alexdohm** [comment]
he tried it on firefox, i tried this on chrome. i also tested on safari, and "1," returns a blank string, while "1." does not

**Comment by xanf** [comment]
@alexdohm feels like different locale settings?
