### ISSUE TITLE
Tab wont active

### ISSUE THREAD

**Issue by mifas** [bootstrap-vue/bootstrap-vue#687]
I've set `active` property to the second tab, but when page load, its always choosing first one

https://jsfiddle.net/y13jszkq/

**Comment by alexsasharegan** [comment]
Just tinkering with this, it seems that there's some link with the `v-model`. It might be necessary for the tab wrapper to have access to a tab index data property so it can know which tab is active.

**Comment by tmorehouse** [comment]
`<b-tabs>` is supposed to traverse the containing list of `<b-tab>` components and check their active state, and set the first active one found as active (and clear the rest)..

I think the last fix to prevent two tabs from being in the `active` state might have affected this.

**Comment by tmorehouse** [comment]
@mifas 

Quick workaround before the PR make it into the next release.

```html
<b-tabs :value="null">
  <b-tab title="Login">Login</b-tab>
  <b-tab title="Singup" active>Signup</b-tab>
</b-tabs>
```

Setting the current tab value to `null` will force it to look for the first `<b-tab>` with the `active` prop set.

**Comment by mifas** [comment]
@tmorehouse Thanks for the update, Fiddle is working as expected.
