### ISSUE TITLE
b-form-textarea debounce should fire event

### ISSUE THREAD

**Issue by DavidRueter** [bootstrap-vue/bootstrap-vue#6882]
Problem:  Implementing auto-save of textarea content:  events fire only when the user navigates to a new field, and there is no built-in way to handle auto-save while editing the text area.

Proposed solution:  When debounce is set and the value has changed, fire an event at the end of the debounce interval.  This event could be an existing event (such as @change or @input), or a new event such as @debounce or other.

Alternatives:  I have implemented a solution using @keyup.  But for this to be robust, I had to implement my own debounce logic--which seems redundant.  It would be better if b-form-textarea simply raised the event at the end of the debounce interval.

**Comment by Hiws** [comment]
What you want already exists. It's the `@update` event, as that's what is used to update the `v-model`.

**Comment by DavidRueter** [comment]
In my testing @update event seems to fire only when the user moves from the text area (i.e. on blur).
