### ISSUE TITLE
b-link doesn't show textContent or innerHTML or innerText when used with refs in vue

### ISSUE THREAD

**Issue by SagarVishal** [bootstrap-vue/bootstrap-vue#6891]
I am unable to get textContent from b-link and change it. If I try the same with <a> or <div> it works fine.

### Steps to reproduce the bug

```
<b-link
 :ref="index"
 v-b-toggle="`${index}`"
 @click="changeText(index)"
>View More</b-link>

changeText(index) {
 console.log(this.$refs[index][0].textContent); // undefined
}
```

### Expected behavior

To get value View More.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.6.0
- Vue: 2.6.14

**Comment by Hiws** [comment]
You shouldn't be changing `textContent` directly.

You should instead change some state, and have your DOM change based on that state.
This can be done in various ways.

A very simple example of this could be something like this:
```html
<b-link @click="isOpen = !isOpen">
  {{ isOpen ? "View Less" : "View More" }}
</b-link>
```

**Comment by Vishalsag** [comment]
> You shouldn't be changing `textContent` directly, or any other form of direct DOM manipulation.
> 
> You should instead change some state, and have your DOM change based on that state. This can be done in various ways.
> 
> A very simple example of this could be something like this:
> 
> ```
> <b-link @click="isOpen = !isOpen">
>   {{ isOpen ? "View Less" : "View More" }}
> </b-link>
> ```

True, but in my case I am using it inside dynamic table and I just want to change text of one particular rows' div.
If i change the isOpen to false it will consider false for all the rows and change the text to "View less" for all rows.

**Comment by Hiws** [comment]
If your items inside the row contain a unique identifier (like an `id`), then you can use that to create an object with key-value pairs, which should be pretty easy. 

The other option is to store the `isOpen` directly on the item object itself.
