### ISSUE TITLE
tbody-tr-class doesn't accept other classes than succes/info/danger etc ?

### ISSUE THREAD

**Issue by yassbeno** [bootstrap-vue/bootstrap-vue#6898]
Hello, 
like my title describes, i would like to pass custom class to my table rows : 
![image](https://user-images.githubusercontent.com/40161273/149961065-e0552364-0264-4d4c-9862-6690402b1b40.png)
![image](https://user-images.githubusercontent.com/40161273/149961111-d01cdb30-15a7-4c0c-b340-1e5921bdb387.png)

The class does not apply (or seems to be not recognized)  : 
![image](https://user-images.githubusercontent.com/40161273/149960328-11b34fcf-e35b-4168-936f-7d3285a67746.png)
my row's color does not change .. 
![image](https://user-images.githubusercontent.com/40161273/149960655-4a3f577a-c6cd-48b8-968e-81f3f1cafb89.png)

Any idea on this ? 
thanks advancely !

**Comment by Hiws** [comment]
That's because you're using `<style scoped>`, trying to style child components.
To do that you need to use [deep selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors)
