### ISSUE TITLE
custom styling for bootstrap vue

### ISSUE THREAD

**Issue by oukrims** [bootstrap-vue/bootstrap-vue#690]
How can style the bootstrap vue is there any less or sass file that can play with

**Comment by mosinve** [comment]
Bootstrap-vue (BV) uses bootstrap css file. you can get Bootstrap scss, customize, build and import it as dependency to your BV project

**Comment by aleksandrmelnyk** [comment]
hi guys,

in case someone face this issue, here is solution which worked for me:

1. setup bootstrap-vue as described in the getting started, but DO NOT import the css styles
2. instead create a folder, like src/assets/scss and put there:
src/assets/scss/_bootstrap-variable-override.scss (same as _custom.scss, here you override variables)
src/assets/scss/app.scss with following content:
```
@import "bootstrap-variable-override";
@import "~bootstrap/scss/bootstrap.scss";
```

3. in App.vue inject it as following:
```
<style lang="scss">

  @import './assets/scss/app.scss';
</style>
```

apart from that make sure to install with --save-dev: node-sass, sass-loader

and that's it, you can customize bs4 right in the vue project.

**Comment by liquidvisual** [comment]
While this does work, I've found including Bootstrap significantly slows down compile times. Has anyone else found this?

**Comment by tmorehouse** [comment]
Compiling bootstrap V4 CSS SASS does take time.

You should still include the `bootstrap-vue.css` file (<4kbytes) to get the stylings needed by Bootstrap-Vue (i.e. b-table sorting styles, b-form-file drag-n-drop styles, and a few temporary Bootstrap v4 fixes such as invalid/valid feedback when used with form-groups, centered-modal - which wont be available until Bootstrap V4.beta.3, etc)

**Comment by liquidvisual** [comment]
I'm coming from a previous Grunt.js project where Bootstrap was included in the same way except the hot reloading / browsersync (?) was basically always instant. It seems Bootstrap chokes a bit in this Webpack setup - I'm not sure how to speed it up?

**Comment by tmorehouse** [comment]
Dev mode or production mode?

**Comment by liquidvisual** [comment]
Dev mode

**Comment by tmorehouse** [comment]
Dev mode is always slower due to the webpack bundling, and how you have your code splitting done up (i.e. webpack chunk names).

**Comment by liquidvisual** [comment]
It's just a bit jarring coming from a previous build script that had virtually no latency. Having to wait up to 5 seconds for a color change feels so painful. Have people simply gotten used to dealing with those compile times in Webpack?

**Comment by classikd** [comment]
@tmorehouse Shouldn't the bootstrap-vue.css file be also .scss ? What about the breakpoints value within it for example ? If i change breakpoints variables in my bootstrap config i'm afraid they won't match anymore
