### ISSUE TITLE
Toast disappears immediately with Bootstrap v5

### ISSUE THREAD

**Issue by vdvibhu20** [bootstrap-vue/bootstrap-vue#6906]
### Describe the bug

I use 
```
this.$bvToast.toast(`Something went wrong. Please try again`, {
     title: 'Error',
     variant: 'danger'
})
```
to create a toast. It appears but is removed immediately

This happens with bootstrap **v5** and works fine with **v4**

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 5.1.3
- Vue: 2.6.11

**Comment by Hiws** [comment]
BootstrapVue does not support Bootstrap 5. 

See: https://github.com/bootstrap-vue/bootstrap-vue/issues/5507 and https://github.com/bootstrap-vue/bootstrap-vue/issues/6872 for more info.
