### ISSUE TITLE
Vue__default.default.extend is not a function

### ISSUE THREAD

**Issue by brb72** [bootstrap-vue/bootstrap-vue#6912]
Suddenly started getting this error in the past couple days, I suspect there's an incompatibility somewhere between the various dependent scripts due to a new version. 

`Error: Vue__default.default.extend is not a function
    at bootstrap-vue.js:1666
    at bootstrap-vue.js:14
    at bootstrap-vue.js:15`

This causes the site to entirely fail and displays nothing but a white screen on Opera, Chrome, etc.

We're trying to rollback to specific older versions of each of the following scripts in hopes of isolating the problem.

------------------------------

JS Script Stack:
    <script src="//unpkg.com/vue"></script>
    <script src="//unpkg.com/vuex"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.10/lodash.min.js"></script>
    <script src="//unpkg.com/vuex-persist@2.2.0/dist/umd/index.js"></script>
    <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>
    <script src="//unpkg.com/babel-polyfill@latest/dist/polyfill.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.js"></script>

**Comment by Hiws** [comment]
> //unpkg.com/vue

The issue is this part.
You're using an unspecified version of Vue. Yesterday Vue 3 was moved to the main channel, which means you're you pulling in Vue 3 instead of Vue 2.

Use `//unpkg.com/vue@2.6.12` instead

**Comment by brb72** [comment]
Indeed you are correct, however we then also got an issue with the Vuex script, so we had to fix that one as well.

For any others who run into this issue, here's our functional JS stack as of this comment:

    <script src="//unpkg.com/vue@2.6.14/dist/vue.js"></script>
    <script src="//unpkg.com/vuex@3.6.2/dist/vuex.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.10/lodash.min.js"></script>
    <script src="//unpkg.com/vuex-persist@2.2.0/dist/umd/index.js"></script>
    <script src="//unpkg.com/bootstrap-vue@2.21.2/dist/bootstrap-vue.js"></script>
    <script src="//unpkg.com/babel-polyfill@6.5.0/dist/polyfill.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.js"></script>
