### ISSUE TITLE
Install command now installs Bootstrap 5 as default, breaking many features

### ISSUE THREAD

**Issue by slothentic** [bootstrap-vue/bootstrap-vue#6914]
### Documentation issue

This command
```
npm install vue bootstrap bootstrap-vue
```

Now install this version of Bootstrap: 
```
"bootstrap": "^5.1.3"
```

This breaks many things. New users are likely to be very confused as well, as many things in the documentation do not apply, and will not work as expected.

Most likely something just changed over on Bootstrap's end, but it impacts this project so wanted to mention it.

**Comment by Hiws** [comment]
This has been the case for about 8 months now.

**Comment by slothentic** [comment]
@Hiws My bad, wasn't aware, wanted to make sure it was on the radar, threw me for a loop.

This library is dead? Last commit was 18 days ago, seems like she's alive and kicking 🚀

**Comment by z1haze** [comment]
well, considering bs 5 officially entered release status in may of 2021, and this library still fails to support it .. id find a new library.
