### ISSUE TITLE
Enabling outline variants on b-badge

### ISSUE THREAD

**Issue by Ericlm** [bootstrap-vue/bootstrap-vue#6923]
The `b-badge` component supports all basic variants of bootstrap (primary, secondary...), but I think it would be great to also be able to have outline variants for badges, like `b-button` does.

**Comment by Hiws** [comment]
Bootstrap doesn't have any outline CSS for badges natively, so not sure it would make sense to support it.
However you can easily do this yourself using utility classes.
```html
<b-badge variant="transparent" class="text-primary border border-primary">Badge</b-badge>
```

**Comment by Ericlm** [comment]
Thank you for your help ! I'll do that.
