### ISSUE TITLE
Bootstrap-Vue version 3 witch VueJS-3 support, when will be available?

### ISSUE THREAD

**Issue by Bahramudin** [bootstrap-vue/bootstrap-vue#6925]
Bootstrap-Vue version 3 with VueJS-3 support, when will be available?
 we are waiting for a long time, I hope to be available as soon as possible.
Thanks!

**Comment by Hiws** [comment]
Refer to: https://github.com/bootstrap-vue/bootstrap-vue/issues/5196 and https://github.com/bootstrap-vue/bootstrap-vue/issues/6872 for more information on Vue 3 support.
