### ISSUE TITLE
[collapse] v-html on b-collapse not working icw SSR

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#694]
At the moment you cannot use the following code in combination with SSR as it will throw a bailing hydration message but after rerender collapse has no content `<b-collapse id="collapse1" v-html="my_var_html"></b-collapse>`

You also cannot use a `template` tag for this, you have to use another div (or p but my html has block elements):
`<b-collapse id="collapse1"><div v-html="my_var_html"></div></b-collapse>`

Although the workaround is fine, it would be nice if v-html (or similar property) would work directly on b-collapse.

**Comment by tmorehouse** [comment]
This is most likely due to issues with v-html on vue components, and overwriting the sub elements within the component itself.
