### ISSUE TITLE
SassError: Undefined variable. trying to customize bootstrap variables

### ISSUE THREAD

**Issue by Thiwer** [bootstrap-vue/bootstrap-vue#6959]
I am trying to customize the bootstrap variables as indicated in the documentation, but I am receiving an error regarding the lack of variables.

![image](https://user-images.githubusercontent.com/8019967/163792686-a0645f51-89df-4386-86ca-9ca2c993a8f7.png)

### package.json

![image](https://user-images.githubusercontent.com/8019967/163792274-af836edb-a03a-4531-a4a8-02a73bd128b9.png)

### main.js

![image](https://user-images.githubusercontent.com/8019967/163792030-e075784b-c63c-4e16-8479-b7a3143f0ae6.png)

### index.scss

![image](https://user-images.githubusercontent.com/8019967/163792425-b970601f-4f35-4a12-8707-9d76a4e2f906.png)

### variables.scss

![image](https://user-images.githubusercontent.com/8019967/163792561-ec370419-343d-429d-a884-20456140e926.png)

I have followed all the steps in the documentation (https://bootstrap-vue.org/docs/reference/theming#sass-variable-defaults) and other internet links with a similar error, and I have not been able to get past this error.

Thanks in advance for the help

**Comment by xanf** [comment]
@Thiwer while I'm investigating an issue, could you please try with `bootstrap-vue@2.21.0` (previous version). This might be a regression we've introduced

**Comment by xanf** [comment]
Closing this issue as resolved. Feel free to reopen if the problem persists
