### ISSUE TITLE
[form-input] Example formatter not working

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#697]
Looks like the formatter might be broken. Test the example in the doc page here: https://bootstrap-vue.js.org/docs/components/form-input

**Comment by tmorehouse** [comment]
Try the new master example.

All inputs were previously v-modeled to the same variable.  I have since separated thm

**Comment by alexsasharegan** [comment]
Awesome, that fixes the wonkiness!
