### ISSUE TITLE
Icons stacking not working when importing specific icons

### ISSUE THREAD

**Issue by Ovab** [bootstrap-vue/bootstrap-vue#6976]
### Describe the bug

When I only import the icons I need instead of the whole component plugin my icons stacks don't seem to work.
Nuxt module

### Steps to reproduce the bug

1. Import bootstrapVue Nuxt module
2. Import a few icons in components
3. make icon stack
4. Icons are stacked next to each other

### Expected behavior

I expect to see an icon stack 

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Vue: 2.6.14
- Nuxt bridge

**Environment:**

- Browser: Google Chrome
- Version: Chrome 101

### Additional context

If I import the component plugin by itself all the icons get loaded in leading to huge blocks of unused code and big script evaluation time see my config below

`  
bootstrapVue: {
    bootstrapCSS: false,

    bootstrapVueCSS: true,
    
    components:
      ['BIcon','BIconCircleFill', 'BIconTwitter', 'BIconFacebook', 'BIconLinkedin', 'BIconHeartFill','BIconPeopleFill',
        'BIconChatLeftTextFill', 'BIconHandThumbsUp', 'BIconHandThumbsDown', 'BIconShareFill', 'BIconSearch',
        'BIconCartFill', 'BIconList', 'BIconArrowLeft', 'BIconMoon', 'BIconSun', 'BIconEnvelopeFill', 'BIconPersonFill',
        'BIconPersonCircle', 'BIconInfo', 'BIconSliders']
  },
`

**Comment by Hiws** [comment]
What does your code look like?

**Comment by Ovab** [comment]
Thanks for the reply, those classes are from tailwindCSS, I hope that's not the problem
It's pretty simple:

`     <div class="flex flex-col mt-2 group">
              <span class="group-hover:scale-125 transition ease-in-out duration-30 text-center">
                    <b-iconstack scale="1.7">
                      <b-icon class="dark:text-dark-artikel-sidebar-sharing-passiveColor" icon="circle-fill"></b-icon>
                      <b-icon class="text-white" scale="0.65" icon="hand-thumbs-down"></b-icon>
                  </b-iconstack>
              </span>
      <p class="text-sm select-none">Dislike</p>
    </div>`

**Comment by Hiws** [comment]
You're using `<b-iconstack>`, but i don't see you importing it anywhere.

**Comment by Ovab** [comment]
I see, didn't know I also had to import that, thank you
