### ISSUE TITLE
Can I get a Toast command and call it in the JS file?

### ISSUE THREAD

**Issue by sws797** [bootstrap-vue/bootstrap-vue#6981]
Every time I switch routes, I need to check whether the user information is complete.

So it's my `router.js`

```
...
const router = new VueRouter({ routes ]);

router.beforeEach((to, from, next) =>{
  const token = getToken();
  if (token && !$store.state.logged.id) {
    // show toast
  }
});

export default router;
```

### Describe the solution you'd like

I hope it can be used like this in any `.js` file:
```
import { TheToast } from 'bootstrap-vue';

TheToast.toast(toastOptions);
```

### Additional context

Just like Message, MessageBox in Element-ui
https://element.eleme.cn/2.15/#/en-US/component/message#local-import
https://element.eleme.cn/2.15/#/en-US/component/message-box#local-import

**Comment by Chapaev17** [comment]
```
window.$nuxt.$bvToast.toast(text, {
      // eslint-disable-next-line unicorn/numeric-separators-style
      autoHideDelay: 10000,
      title,
      variant: 'warning',
      solid: true,
    })
```

**Comment by sws797** [comment]
@Chapaev17 Thank you, I'll try it later.
It seems to bind Vue to windows, how do you do this?(I'm using vue-cli4 to create vue2 project)

**Comment by Chapaev17** [comment]
Looks like vue cli doesn't add variables to windows. Nuxt does this and I use:
```
    window.$nuxt.$bvToast.toast(text, {
      title,
    })
```
You can use in any js file :
```
import Vue from 'vue'

const vue = new Vue()
vue.$bvToast.toast("Your text", {
      title: "Your title",
    })
```
As far as I know, this will not work when switching to vui 3, since it will not be possible to add something to Vue.prototype.
Therefore, you'd better create `watch` for router in your main component:
```
watch:{
    $route (to, from){
        const token = getToken();
        if (token && !this.$store.state.logged.id) {
           this.$bvToast.toast("Your text", {
            title: "Your title",
          })
        }
    }
} 
```

**Comment by sws797** [comment]
@Chapaev17 Thank you, I refer to your method call successfully. This is my `router.js`
```
import Vue from "vue";
import VueRouter from "vue-router";
import { ToastPlugin } from "bootstrap-vue";

Vue.use(VueRouter);

const routes = [xxx];

Vue.use(ToastPlugin);                         // <-----------
const vue = new Vue();                      // <-----------

router.beforeEach((to, from, next) => {
  vue.$bvToast.toast("Your text", {
    title: "Your title",
  });
  next();
}};
```
