### ISSUE TITLE
Cannot type white space in input inside dynamic tabs title

### ISSUE THREAD

**Issue by ibam-voxel** [bootstrap-vue/bootstrap-vue#6987]
### Describe the bug

Cannot give white space in input

### Steps to reproduce the bug

1. Go to [link](https://codesandbox.io/s/great-sunset-rbl79h?file=/src/components/HelloWorld.vue)
2. Click on input
3. type anything must with whitespace
4. you can see cannot add white space in input

### Expected behavior

I expect when typing "Test A" output must be "Type A" not "TypeA"

### Versions

**Libraries:**

- BootstrapVue: 2.0.0
- Bootstrap: 4.1.3
- Vue: 2.6.

**Environment:**

- Device: Dekstop
- OS: Windows
- Browser: Chrome
- Version: 102.0.5005.63 (Official Build) (64-bit)

### Demo link
[link](https://codesandbox.io/s/great-sunset-rbl79h?file=/src/components/HelloWorld.vue)

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
That's because `space` is used to select a tab for accessibility reasons.
If you want to prevent this behavior when the input is focused, you can add `@keydown.space.stop` to your input.

**Comment by ibam-voxel** [comment]
thx it's worked for me
