### ISSUE TITLE
[Table] How should look like sort provider function?

### ISSUE THREAD

**Issue by lavezzi1** [bootstrap-vue/bootstrap-vue#699]
Hello,

My function looks like:
```
sortProvider(ctx) {
        this.isBusy = true;
        const promise = fetch(`http://localhost:3000/photos?_sort=${ctx.sortBy}&_order=${ctx.sortDesc ? 'asc' : 'desc'}`);

        return promise
          .then((data) => {
            this.totalPhotos = parseInt(data.headers.get('X-Total-Count'), 10);
            return data.json();
          })
          .then((data) => {
            this.isBusy = false;
            return data;
          });
      },
```
The function works perfect I get sorted data, but table does not reflect to data change.

**Comment by tmorehouse** [comment]
Are you setting this function as the "items" prop in your `<b-table>`?

```html
<b-table :items="sortProvider" :busy="isBusy" ...>
```

Is your table showing data initially, when no sort has been selected?

**Comment by tmorehouse** [comment]
Does the data from `data.json()` also match your fields definition?

Is the table showing any data, or just not updating when you click a column for sorting?

**Comment by lavezzi1** [comment]
@tmorehouse 

> Are you setting this function as the "items" prop in your <b-table>?
No, I have this for `:items` provider function:
```
myProvider(ctx) {
        this.isBusy = true;
        const promise = fetch(`http://localhost:3000/photos?_page=${ctx.currentPage}&_limit=${ctx.perPage}`);

        return promise
          .then((data) => {
            this.totalPhotos = parseInt(data.headers.get('X-Total-Count'), 10);
            return data.json();
          })
          .then((data) => {
            this.isBusy = false;
            return data;
          });
      },
```
And I use sort-changed event to handle sorting like `@sort-changed="sortProvider"`

> Is your table showing data initially, when no sort has been selected?
Yes.

**Comment by lavezzi1** [comment]
> Does the data from data.json() also match your fields definition?
Is the table showing any data, or just not updating when you click a column for sorting?

It shows initially but not updated on sorting.

**Comment by tmorehouse** [comment]
The `sort-changed` is just a notification event that the sorting has changed/cleared. It doesn't receive the sort data or callback or promise. `sort-changed` is only needed when you are returning an array (or setting an array) via the :`items` prop.

The provider function assigned to `:items` will be called when the sorting changes (as long as `no-provider-sorting` is not set.

The `ctx` object provided to the `:items` provider function includes the `sortBy` and `sortDesc`.

So do this:

```html
<b-table :items="myProvider"></b-table>
```
```js
myProvider() {
  this.isBusy = true;
  let url = `http://localhost:3000/photos?_page=${ctx.currentPage}&_limit=${ctx.perPage}`;
  if (ctx.sortBy) {
    url = `${url}&_sort=${ctx.sortBy}&_order=${ctx.sortDesc ? 'desc' : 'asc'}`;
  }
  return fetch(url)
    .then((data) => {
      this.totalPhotos = parseInt(data.headers.get('X-Total-Count'), 10);
      return data.json();
    })
    .then((data) => {
      this.isBusy = false;
      return data;
    });
}
```

**Comment by lavezzi1** [comment]
@tmorehouse ok, thank you, it works. But when I start sorting it shows all data, seems like table ignore perPage prop.

**Comment by tmorehouse** [comment]
When you are providing the data via a provider function, you are responsible for sorting, paging, and filtering (unless you have the respective `no-provider-*` props set).

Your items provider function should return only the page of data (based on perPage and pageSize values provided in the `ctx` object).

If you are returning all the data (un-paged), then you can set the `no-provider-paging` prop, and `<b-table>` will handle the paging.

**Comment by lavezzi1** [comment]
@tmorehouse but with `:no-provider-paging="true"` pagination doesn't work.

**Comment by tmorehouse** [comment]
By default your provider function should send only the page of data to `<b-table>` (i.e. page size)., unless you disable provider-paging.

For provider function (and app) is responsible for paging (slicing the data,), and controlling the pagination control (if you are using one).

**Comment by tmorehouse** [comment]
You must decide who is going to slice the data into the appropriate page... your external provider function, or b-table.

**Comment by tmorehouse** [comment]
Example:

```html
Per Page:
<b-form-select :options="[5, 10, 15]"
               v-model="perPage"
></b-form-select>
<br>
<b-pagination :total-rows="totalPhotos"
              :per-page="perPage"
              v-model="currentPage"
></b-pagination>
<br>
<b-table :items="myProvider"
         :fields="fields"
         :current-page="currentPage"
         :per-page="perPage"
></b-table>
```

App definition:
```js
{
  data: {
    totalPhotos: 0,
    perPage: 5,,
    currentPage: 1,
    fields: {
      // Your fields definition
    }
  },
  methods: {
    myProvider(ctx) {
      this.isBusy = true;
      let url = `http://localhost:3000/photos?_page=${ctx.currentPage}&_limit=${ctx.perPage}`;
      if (ctx.sortBy) {
        url = `${url}&_sort=${ctx.sortBy}&_order=${ctx.sortDesc ? 'desc' : 'asc'}`;
      }
      return fetch(url)
        .then((data) => {
          this.totalPhotos = parseInt(data.headers.get('X-Total-Count'), 10);
          this.isBusy = false;
          return data.json();
        });
    }
  }
}
```

**Comment by lavezzi1** [comment]
Thanks!

**Comment by celorodovalho** [comment]
Exactly the same example above, gives me:
```
Invalid prop: type check failed for prop "items". Expected Array, Function, got Promise 
```

@tmorehouse  can you help me?

**Comment by tmorehouse** [comment]
@celorodovalho It sounds like you are calling the provider function and returning it's response to the `items` prop, rather than passing the reference to the provider function.

Without seeing your code, It is hard to tell.
