### ISSUE TITLE
Modal window does not work (v0.18.0)

### ISSUE THREAD

**Issue by DjOli** [bootstrap-vue/bootstrap-vue#702]
RE the closed issue: https://github.com/bootstrap-vue/bootstrap-vue/issues/276

I have recently discovered this is still an issue with bootstrap-vue V0.18.0. The grey overlay is present, but modal itself is not. My project makes use of bootstrap.scss for bootstrap styling. Can confirm `.modal {
  display: block;
}` works around the problem.

**Comment by tmorehouse** [comment]
Are you importing the full bootstrap-vue library or just individual components?

Also what bundler/rollup are you using?

Similar issue #515, dealing with CSS not being loaded correctly.

Some bundlers do not handle the scoped CSS correctly.

**Comment by tmorehouse** [comment]
THe current documentation site is running with v0.18.0, and modals are working fine there: https://bootstrap-vue.js.org/docs/components/modal

**Comment by alexsasharegan** [comment]
I dug into the dist last week, and I saw the scoped css being generated (`.modal[data-v=<hash>`). This could be an issue with the order things are imported. Any code samples of how your build process is setup would be helpful!

**Comment by DjOli** [comment]
Please forgive me for my lack of real information, this is all quite new to me so I will do my best to answer questions.

I believe I am importing the entire bootstrap-vue library.
```
import BootstrapVue from 'bootstrap-vue'
Vue.use(BootstrapVue)
```

The project is being put together using webpack. I'm fairly unfamiliar with it and its configuration has mostly been from a vue.js scaffold. Taking a stab in the dark, i'd say i'm using css-loader.

I've tried adding the style specifically to the project (index.html after loading all other styles):
```
<link href="node_modules/bootstrap-vue/dist/bootstrap-vue.css" rel="stylesheet">
```

I'm happy to provide code samples but am not entirely sure what might be useful. I'll keep trying to make some sense of the build process.

Thanks for the help!

**Comment by DjOli** [comment]
Was a mistake on my part, I wasn't including the bootstrap-vue.css file correctly. Thanks for all the help, closing the issue.

**Comment by amigoge** [comment]
Hi,I have similar problem.I use webpack-3.5.6 to manage those lib i use include the bootstrap-vue.
But i always get an TypeError: $(...).modal  is not a function.
I've try override the .modal{display:block;},yeah the error is gone and the modal is not working anymore.
help me please.

**Comment by tmorehouse** [comment]
@amigoge what version or Bootstrap-Vue are you using?  v1.0.0.beta.7? or the alpha version 0.23.0?

I am unsure where you are seeing `$(...).modal` as that looks like a jQuery call, and we do not use jQuery in the library.

**Comment by amigoge** [comment]
@tmorehouse  well ,it's 1.0.0-beta.7
and the error It's shown when my component emit the event that parent provide to open the modal.
any crue?

**Comment by tmorehouse** [comment]
Could you provide a sample of your code?

**Comment by amigoge** [comment]
@tmorehouse here is my project
https://github.com/amigoge/test-merchants
when you run the project it's work until you click the card.

**Comment by tmorehouse** [comment]
Based on your code, you are generating the modal by hand (as plain HTML). https://github.com/amigoge/test-merchants/blob/master/views/index.ejs

You need to render your modal using teh `b-modal>` component. Please refer to the documentation at: https://bootstrap-vue.js.org/docs/components/modal

All Bootstrap-Vue components are VueJS components.  BootstrapVue cannot control manually generated HTML components.

**Comment by amigoge** [comment]
@tmorehouse  
ok,I got it.
It seems use the bootstrap-vue i have to use all the component of the bootstrap-vue provide.

I should read the doc first,thanks!!
