### ISSUE TITLE
b-card problem: h4 is displayed when using title into b-card-body balise

### ISSUE THREAD

**Issue by ntorquet** [bootstrap-vue/bootstrap-vue#7038]
Hi!
Thank you for this great library!

When using the b-card-body balise, a 'h4' text is displayed at the top of the card body (under the title)

### Here an example of the code

```
<b-card title="a title">
  <b-card-body>
    Some text
  </b-card-body>
</b-card>
```

### The result:

![Capture](https://user-images.githubusercontent.com/42234278/186899640-52d688d1-54e8-482d-8856-7f0e31c3c2e5.PNG)

### Expected behavior

The 'h4' should not be displayed.

### Versions

**Libraries:**

- BootstrapVue: 8.15.0
- Vue: 3

**Comment by Hiws** [comment]
> BootstrapVue: 8.15.0

Are you from the future? The latest relerase of BootstrapVue is `2.22.0`

> Vue: 3

BootstrapVue doesn't support Vue 3.

**Comment by ntorquet** [comment]
Oups sorry, I am using BootstrapVue3 (v 8.15.0), I made a mistake.
