### ISSUE TITLE
Navbar - don't show until ready

### ISSUE THREAD

**Issue by alexardalich** [bootstrap-vue/bootstrap-vue#704]
Sorry if something similar has been asked before, haven't been able to find anything.

Is there a trick to not show the navbar until it's ready?

I'm finding when clicking through the site, the navbar will show all menu items with drops downs along the top of the page until the JS and styling hits and it draws itself proper which is jarring to the end user.

Something I'm missing in displaying a page with Vuejs components in general, I'm sure.

Thanks

**Comment by tmorehouse** [comment]
If you are not using Server Side Rendering (SSR) which pre-renders content before being sent to the client,, then you can can used the VueJS directive `v-cloak` on the components (or app) that you want "hidden" until rendered.

See the VueJS docs at https://vuejs.org/v2/api/#v-cloak

**Comment by tmorehouse** [comment]
Also, ensure that the CSS is being loaded before any of your javascript

**Comment by alexardalich** [comment]
Ah, got it.

Sure I have read/seen v-cloak before... didn't click for me.

Thanks for teaching me a little Vue :)
