### ISSUE TITLE
Invalid Link to Vue Library in Getting Started Guide

### ISSUE THREAD

**Issue by nils-christian** [bootstrap-vue/bootstrap-vue#7043]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs#browser

### Additional context or description

Hi, 

You are refering in your getting started guide to

`<script src="https://unpkg.com/vue@latest/dist/vue.min.js"></script>`

When using this link, a 404 is returned: "Cannot find "/dist/vue.min.js" in vue@3.2.39"

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue/bootstrap-vue/pull/6623
