### ISSUE TITLE
Sticky Navbar - Nav Item Dropdown scrolls to top

### ISSUE THREAD

**Issue by SRichner** [bootstrap-vue/bootstrap-vue#705]
When using a sticky navbar in combination with a large (scrollable) content, clicking on a nav-item-dropdown will cause the page to scroll to the top.
 
I have the following code:

```html
<div id="app">
  <b-navbar toggleable variant="success" type="light" sticky>
    <b-nav-toggle target="nav_collapse"></b-nav-toggle>
    <b-collapse is-nav id="nav_collapse">
      <b-nav is-nav-bar class="ml-auto">
        <b-nav-item-dropdown right>
          <template slot="button-content">
            <span>Foo</span>
          </template>
          <b-dropdown-item>Bar</b-dropdown-item>
        </b-nav-item-dropdown>
      </b-nav>
    </b-collapse>
  </b-navbar>
</div>
```

Whenever any Nav Item is clicked (here Foo), it scrolls to the top of the page.
I recreated the issue [in this JSFiddle](https://jsfiddle.net/7fwzwmgv/1/) and the behaviour is the same.

Not sure whether I'm using it the wrong way or it really is a bug and have not yet found a fix/workaround. Any help would be appreciated :)

**Comment by tmorehouse** [comment]
This is probably because the nav items are rendered as links with an href of `#` (which the default action of `href="#"` causes a page to scroll to the top).

If you nav-items are to be actions, then add `@click.stop` handlers on them (if they are to run a method), or set the href prop to a page URL.

**Comment by tmorehouse** [comment]
Also, make sure you load your CSS files first, then vue, then tether and then bootstrap-vue

**Comment by SRichner** [comment]
@tmorehouse Thanks for your reply!

That makes sense, but what about the `button-content` slot, which should simply be a toggle for the actual dropdown menu? 
With a [modified example](https://jsfiddle.net/7fwzwmgv/3/) from the documentation (using `text="Lang"` and not the slot), when clicking the "Lang" navigation item, the dropdown is being toggled and the page scrolls to top.

Is there a way to prevent that slot from being rendered as a link?

**Comment by tmorehouse** [comment]
Ah, let me check the code for nav-dropdown-item, to make sure it is issuing a `preventDevault()` on the click event (it should be but might have slipped through).

**Comment by tmorehouse** [comment]
@SRichner Which version of the library are you using? Latest v0.18.0?

I just created a fiddle (although using `fixed="top"` instead of `sticky` (Note that position: sticky, used for .sticky-top, isn’t fully supported in every browser.), and clicking a link doesn't cause the page to scroll up.

https://jsfiddle.net/srfarugh/

**Comment by SRichner** [comment]
@tmorehouse I'm using the latest (0.18.0) version.

Using `fixed="top"` fixed the scrolling issue. I will be using that instead of `sticky`.

Thanks! 👍

**Comment by tmorehouse** [comment]
Cool...

I still have the PR branch available if it is needed.  I'll test the fiddle with content above ht navbar (non-fixed position), and see fi the scrolling still happens.  If it does, then I'll re-open the PR and merge.

**Comment by tmorehouse** [comment]
I just tested with content above the navbar (and removed `fixed="top"), and on chrome the screen isn't scrolling as expected.

Which browser are you using?

**Comment by tmorehouse** [comment]
The type/positioning of the navbar should't affect any of the click handlers (which usually prevent `href="`#"` from scrolling to the top.  So this is a bizarre issue.

**Comment by SRichner** [comment]
Using Chrome Version 59.0.3071.115 (Official Build) (64-bit), it does not work as expected (scrolls).
Works on Safari and Firefox though (macOS).

**Comment by tmorehouse** [comment]
Interesting.

If you use a non-sticky and non-fixed navbar, (and place some content above it), does it exhibit the

Any warnings or errors appear in the console? same issue?

**Comment by SRichner** [comment]
With [this](https://jsfiddle.net/srfarugh/5/) (non-sticky and non-fixed with content above), it does not scroll to the top and I'm not getting any warnings/errors.

**Comment by tmorehouse** [comment]
I just tried setting sticky in both chrome and firefox.  Firefox support sticky mode.

But neither are jumping to the top when I click on a navbar links.

**Comment by tmorehouse** [comment]
Might be a browser issue with sticky
