### ISSUE TITLE
BTable never hides the busy indicator when using provider function

### ISSUE THREAD

**Issue by diyan-gochev-at-ft-dot-com** [bootstrap-vue/bootstrap-vue#7058]
### Describe the bug

BTable never hides the busy indicator when using provider function

### Steps to reproduce the bug

1. Create BTable
2. Set provider function
3. Load fake data with Promise and setTimeout
4. Loader never hides.

### Expected behavior

After loading the data, the busy indicator should be hidden.

### Versions

**Libraries:**

    "bootstrap": "^5.2.0",
    "bootstrap-vue-3": "^0.3.11",

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version 106.0.5249.91 (Official Build) (64-bit)

### Demo link

https://replit.com/@DiyanGochev1/BootstrapVueTableWithProvider#index.html

**Comment by Hiws** [comment]
> bootstrap-vue-3

You're on the wrong GitHub.
`bootstrap-vue-3` isn't the same library as `bootstrap-vue`

https://github.com/cdmoro/bootstrap-vue-3/issues
