### ISSUE TITLE
All toasts throwing error in vue3-compat-build

### ISSUE THREAD

**Issue by derweise** [bootstrap-vue/bootstrap-vue#7065]
Almost all toasts are throwing errors in

https://bootstrap-vue-3.netlify.app/vue3/

Can you have a check on this?

@xanf

**Comment by xanf** [comment]
@derweise This should be fixed in latest build (not able to update netlify right now)

**Comment by derweise** [comment]
@xanf, thanks. How can I use the latest build?

**Comment by derweise** [comment]
Since yesterday I have been using now:

"bootstrap-vue": "^2.23.1",

Now the toast appears but disappears again within milliseconds.
