### ISSUE TITLE
Help with Vue 3 compat

### ISSUE THREAD

**Issue by cmora-pe** [bootstrap-vue/bootstrap-vue#7086]
Hi guays,
is there some docs on how to use BV with Vue 3 and compat library?

I have to start a project almost immediately, and it's required to be in Vue 3 so it would be great if I can start using BV from the begining.

KR

**Comment by TomSmith27** [comment]
There is this section on the site https://bootstrap-vue.org/vue3

**Comment by cmora-pe** [comment]
@TomSmith27 Thanks!
