### ISSUE TITLE
Switches Variant

### ISSUE THREAD

**Issue by Catyell2** [bootstrap-vue/bootstrap-vue#7101]
### Describe the bug

When using the `switches` prop in combination with the `button-variant` prop no change is occurring in the style of the switch button.  

### Steps to reproduce the bug

1) Create environment to run attached code in. (Note: attached code is mostly ripped form the documentation found at https://bootstrap-vue.org/docs/components/form-checkbox#switch-style-checkboxes)
 
2) Swap out 'danger' for other approved variants such as 'info' as further evidence

### Expected behavior

Switches change from using `primary` color options to `danger` color options.

### Versions

**Libraries:**

- BootstrapVue: ^2.21.2
- Bootstrap: ~4.3.1
- Vue: 2.6.14

**Environment:**

- Device: Lenovo Yoga 710 (Unimportant)
- OS: Windows 10
- Browser: Firefox
- Version: Firefox 107.0.1, Windows 22H2

### Demo link

```
<template>
  <div>
      <b-form-checkbox-group
        v-model="selected"
        :options="options"
        :aria-describedby="ariaDescribedby"
        button-variant="danger"
        switches
      ></b-form-checkbox-group>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        selected: [], // Must be an array reference!
        options: [
          { text: 'Red', value: 'red' },
          { text: 'Green', value: 'green' },
          { text: 'Yellow (disabled)', value: 'yellow', disabled: true },
          { text: 'Blue', value: 'blue' }
        ]
      }
    }
  }
</script>
```

### Additional context

The functionality of this does appear to work for buttons specifically however as a prop for the whole of form-group-checkbox it doesn't appear to work for other options. 
If this could be fixed to change styles or documented that these don't apply, that is all I request.

**Comment by MJGTwo** [comment]
this is an intended behavior. inside of the section [Component Reference](https://bootstrap-vue.org/docs/components/form-checkbox#component-reference) it defines `button-variant` as "Specifies the Bootstrap contextual color theme variant the apply to the **button style** checkboxes" (emphasis mine). nowhere in the documentation does it state that one can pass a variant color to a `<b-form-check-group>` tag while also passing the `switches` prop. 

to produce a group of buttons that can be toggled on or off like the example above (but not switches), one could write the following:

```typescript
<template>
  <div>
    <b-form-checkbox-group
      v-model="selected"
      :options="options"
      :aria-describedby="ariaDescribedby"
      buttons
      button-variant="danger"
      size="lg"
      name="buttons-2"
    ></b-form-checkbox-group>
  </div>
</template>

<script>
export default {
  data() {
    return {
      selected: [], // Must be an array reference!
      options: [
        { text: "Red", value: "red" },
        { text: "Green", value: "green" },
        { text: "Yellow (disabled)", value: "yellow", disabled: true },
        { text: "Blue", value: "blue" },
      ],
    };
  },
};
</script>
````

a working demo can be found here: https://codesandbox.io/s/sleepy-keller-un9t2h?file=/src/components/ButtonSwitchDemo.vue

**Comment by Catyell2** [comment]
Thank you for pointing this out and creating an example of toggling color buttons.  I must have had my wires crossed when I read that and assumed buttons were just talking about the 'clickable' section regardless of the passed prop (switches are the button or check-boxes are the button). However since this is intentional and very specific to button (true buttons) then there really isn't an issue.
