### ISSUE TITLE
Bootstrap Dropdown tabindex

### ISSUE THREAD

**Issue by cpgb85** [bootstrap-vue/bootstrap-vue#7106]
When using the <b-dropdown> component, i try to specify a tabindex, and it applies it to the parent div  instead of the dropdown arrow which needs to be clicked.  

I know this is a long shot to get help seeing this isn't maintained anymore.

**Comment by Hiws** [comment]
The answer is using the `toggle-attrs` prop which exists to add attributes to the toggle `<button>`

**Comment by cpgb85** [comment]
thank you.  What about the b-form-datepicker?
