### ISSUE TITLE
How use export data to set a property of objects

### ISSUE THREAD

**Issue by klaveren** [bootstrap-vue/bootstrap-vue#711]
I know this is a stupid question, any way, how I can use variables to setup a property of objects from data exports?

Something like this:
```
<template>
<b-card 
    header="{{ VAR1 }}"
    class="mb-2"
    title="{{ VAR2}}"
    sub-title="{{ VAR3 }}"
    show-footer>
    <small slot="footer" class="text-muted">
        Last updated 3 mins ago
    </small>
    </b-card>
</template>
<script>
export default {
    data() {
        return {
            VAR1: "TEXT1",
            VAR2: "TEXT2",
            VAR3: "TEXT3"
        }
    }
}
</script>
```

**Comment by tmorehouse** [comment]
You can't us mustache (`{{ ... }}` inside property bindings.

Do this instead:

```html
<template>
<b-card 
    :header="VAR1"
    class="mb-2"
    :title="VAR2"
    :sub-title="VAR3"
    show-footer>
    <small slot="footer" class="text-muted">
        Last updated 3 mins ago
    </small>
    </b-card>
</template>
```
 
note the `:` in front of the property names (shorthand for `v-bind:`), which instructs Vue to interpret the contents of the property as a javascript variable or command.

**Comment by klaveren** [comment]
Sorry for the question, I'm starting with Vue, and I completely forgot about v-binds. 
Thank you so much.

**Comment by tmorehouse** [comment]
In older versions of Vue it was possible to use mustache inside props (I think), but that has long since been deprecated.

**Comment by tmorehouse** [comment]
If you are searching for examples on the net,, make sure the examples you look at are using version 2.x of Vue.
