### ISSUE TITLE
Hide method for collaose

### ISSUE THREAD

**Issue by sts-ryan-holton** [bootstrap-vue/bootstrap-vue#7115]
Hello, I'd like to be able hide a collapse by it's collapse ID without toggling it. It seems that `this.$root.$emit(`bv::toggle::collapse`, `children-${currentItem.id}`)` would close the collapse if it's open, or open it if it's closed.

I tried changing the `collapse` to `hide` in the first argument but this didn't make any impact.

**Comment by fredsal** [comment]
That is not a bug or an issue, use discussions section for this kind of topics
