### ISSUE TITLE
@input event of VFormInput is being fired when element/Input box looses focus

### ISSUE THREAD

**Issue by ssg-financial-com** [bootstrap-vue/bootstrap-vue#7127]
### Steps to reproduce the bug

1. Input a number or text in input field
2. Click somewhere else on the screen so that focus goes off from input field
3. @input event is again called when focus from input field goes off

### Expected behavior

When focus from input field goes off, it should not fire input event

**Comment by Hiws** [comment]
Can you provide a reproduction, as I see no issues here:
<https://codepen.io/Hiws/pen/rNZePQj>
