### ISSUE TITLE
b-table row details: match parent cell width

### ISSUE THREAD

**Issue by JoshuaRobertson** [bootstrap-vue/bootstrap-vue#7129]
### Is your feature request related to a problem? Please describe...

My table displays user related data with an option to `toggleDetails` and display additional account specific data below each row. Currently the data displayed in `row details` isn't aligned with the parent cells above (see screenshots below).

### Describe the solution you'd like

It would be useful to control how the `row details` are injected into the table, such as replacing the wrapper element which is currently a `td` that sets a defined `colspan`. 

Is there a way to align the child cells with the parent row? I appreciate there isn't a direct _child > sibling_ relationship between the two.

### Describe alternatives you've considered

I've tried the following related issues but they don't produce the desired result.

- https://github.com/bootstrap-vue/bootstrap-vue/issues/2889
- https://github.com/bootstrap-vue/bootstrap-vue/issues/4135
- https://github.com/bootstrap-vue/bootstrap-vue/issues/5161

### Additional context

**Attempt 1**
Using a `tr` tag to output the data.

```html
<template #row-details="row">
  <tr v-for="(entry, index) in row.item.account">
    <td></td>
    <td>
      {{ entry.account }}
    </td>
    <td>
      {{ entry.revenue }}
    </td>
    <td>
      {{ entry.commission }}
    </td>
    <td>
      {{ entry.profit }}
    </td>
    <td>
      {{ entry.sessions }}
    </td>
    <td>
      {{ entry.submits }}
    </td>
    <td>
      {{ entry.leads }}
    </td>
  </tr>
</template>
```

![Screenshot 2023-03-03 at 11 29 53](https://user-images.githubusercontent.com/25368786/222714816-26c7bae7-02e2-4333-af5f-63cb29622de7.png)

**Attempt 2**
Using a `table` with `tbody` and `tr` tags to output the data.

```html
<template #row-details="row">
  <table>
    <tbody>
      <tr v-for="(entry, index) in row.item.account">
        <td></td>
        <td>
          {{ entry.account }}
        </td>
        <td>
          {{ entry.revenue }}
        </td>
        <td>
          {{ entry.commission }}
        </td>
        <td>
          {{ entry.profit }}
        </td>
        <td>
          {{ entry.sessions }}
        </td>
        <td>
          {{ entry.submits }}
        </td>
        <td>
          {{ entry.leads }}
        </td>
      </tr>
    </tbody>
  </table>
</template>
```

![Screenshot 2023-03-03 at 11 51 10](https://user-images.githubusercontent.com/25368786/222715268-807b08c8-476e-4580-ba65-67391655e8f5.png)

**Comment by Hiws** [comment]
> Is there a way to align the child cells with the parent row? 

If you give the cells in both tables the same width, they should align.

**Comment by JoshuaRobertson** [comment]
Thanks @Hiws, I considered that initially but there is a difference despite setting the width on each cell. Adding the following:

```css
.table td {
  width: 200px;
}
```

Produces this:

![Screenshot 2023-03-03 at 14 04 58](https://user-images.githubusercontent.com/25368786/222740092-a8fa3876-e0db-4a2f-84af-fbeac8def25b.png)

I don't have any custom CSS that might be affecting the table. Is there a way to remove the `td role="cell"` that is used within the `row details` template?

**Comment by Hiws** [comment]
Here's a quick example that gets pretty close.
<https://codepen.io/Hiws/pen/xxadzwj>

(Some minor difference with the cell borders)

**Comment by JoshuaRobertson** [comment]
Ah excellent, thanks @Hiws that helps a lot. Appreciate the help.
