### ISSUE TITLE
Navbar help

### ISSUE THREAD

**Issue by johnfercher** [bootstrap-vue/bootstrap-vue#713]
I copy and paste the Navbar example from https://bootstrap-vue.js.org/docs/components/navbar, but I'm getting the bug below.

![bug-bootstrap-vue](https://user-images.githubusercontent.com/4752636/28390633-37dc8ece-6cb1-11e7-97b5-d8d280586b6e.png)

**Comment by johnfercher** [comment]
I'm already using bootstrap-vue 0.18.0, like mentioned in #570.

**Comment by tmorehouse** [comment]
Bootstrap-Vue uses Bootstrap Version 4.alpha.6 CSS.  The example above is from Bootstrap V3, which sues a vastly different CSS.

With Bootstrap-Vue, you use custom Vue components to create the elements fro you.  plain Bootstrap V4 HTML will not work with Bootstrap-Vue.

https://bootstrap-vue.js.org/docs/components/navbar

**Comment by tmorehouse** [comment]
Ensure that you are loading both the bootstrtap.css ans bootstrap-vue.css (in that order), and that you are loading all the required JS files in the correct sequence.

If using a bundle and are importing the css and components, check out https://github.com/bootstrap-vue/bootstrap-vue/blob/master/docs/SETUP.md for updated docs.

**Comment by tmorehouse** [comment]
I see you have also opened a similar issue under the Vue-Strap project (which is BootStrap 3 and Vue 1.x based, and separate from Bootstrap-Vue project): https://github.com/yuche/vue-strap/issues/503

**Comment by johnfercher** [comment]
I'm not using Vue-Strap anymore.  Here is my import.

```javascript
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue/dist/bootstrap-vue.esm';
import App from './App'
import VueResource from 'vue-resource'
import VueRouter from 'vue-router'
import router from './router'

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
```

I'm using vue-cli, I have installed just like presented in: https://github.com/bootstrap-vue/bootstrap-vue/blob/master/docs/SETUP.md

**Comment by tmorehouse** [comment]
Which version of Bootstrap Vue are you using?

**Comment by johnfercher** [comment]
I'm using the version: 0.18.0

**Comment by alexsasharegan** [comment]
What are the chances you have a github repo up we can investigate? It's easier to dig around, double check structure, and reproduce the bug.

**Comment by johnfercher** [comment]
Others information 
OS: Ubuntu 16.04
NPM: 5.03
Node: v8.1.3

**Comment by johnfercher** [comment]
I'm creating the repository.

**Comment by alexsasharegan** [comment]
If you don't have a repo available, which cli template are you using? I'll try and run through the steps to recreate the issue—unless you would be so awesome as to create a bare-bones repo of the bug 😄 !

**Comment by johnfercher** [comment]
I've created a new project and now it's working perfectly. I'll re-create my steps if find the reason of the bug, I let you know.

Thanks.

**Comment by alexsasharegan** [comment]
Well that's maddening!

**Comment by alexsasharegan** [comment]
If you figure it out, feel free to share and close this so posterity can find another solution to the great bundling dilemma that plagues our JS community 😉

**Comment by johnfercher** [comment]
Sorry, I couldn't get the same error again.
