### ISSUE TITLE
Would like a Pinterest icon

### ISSUE THREAD

**Issue by cliffordh** [bootstrap-vue/bootstrap-vue#7135]
### Is your feature request related to a problem? Please describe...
NO

A clear and concise description of what the problem is.
Social icons for Facebook, Twitter, Whatsapp, etc. exist but not Pinterest.

### Describe the solution you'd like
Pinterest is currently supported in https://icons.getbootstrap.com/ which is linked from Bootstrap Vue.

Update Bootstrap Vue, including v2.x to include support for newest icons.

### Describe alternatives you've considered
n/a

**Comment by Hiws** [comment]
I'd suggest you look into another package for icons.
Like <https://github.com/antfu/unplugin-icons>

As this project isn't being maintained.
