### ISSUE TITLE
.card-deck css is missing from Bootstrap Vue

### ISSUE THREAD

**Issue by caseytrombley** [bootstrap-vue/bootstrap-vue#7141]
### Describe the bug

There are no styles defined for .card-deck using Bootstrap Vue ^2.22.0

### Steps to reproduce the bug

Try using the Card Group component with 'deck' as described in the Bootstrap Vue docs.
There are no css styles for this, all the cards wind up just stacking vertically and not aligning as a grid as shown in the documentation

### Expected behavior

There should be css as seen in the BV docs page. You can inspect the examples on the Bootstrap Vue docs and see the .card-deck styles there.

### Versions
^2.22.0

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

<img width="602" alt="image" src="https://user-images.githubusercontent.com/472921/229961777-c4dee9a8-2a9b-4c70-9c86-82c5723e5194.png">

Example from Bootstrap Vue docs:
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/472921/229961987-0c5df2f8-c088-411a-a4b8-b4a30319984d.png">

**Comment by Hiws** [comment]
The `card-deck` class is a Bootstrap class. Not something specific to BootstrapVue.
So you're likely using the wrong version of Bootstrap in your project.

**Comment by caseytrombley** [comment]
Nope, you're assuming the wrong thing. I definitely have the right bootstrap version in the project. Everything else works as expected. Please don't blow this off and close the issue without investigating
