### ISSUE TITLE
.card-deck class is missing from Bootstrap Vue version 2.23.0

### ISSUE THREAD

**Issue by caseytrombley** [bootstrap-vue/bootstrap-vue#7142]
### Describe the bug

I opened this bug yesterday but it got closed prematurely without anyone fixing the bug.

Please see: https://github.com/bootstrap-vue/bootstrap-vue/issues/7141

### Steps to reproduce the bug

Use <card-group deck> component, see that the .card-deck class has no styles associated with it.

### Expected behavior

See how other Bootstrap classes are working, see .card is fine:
![image](https://user-images.githubusercontent.com/472921/230099191-734b076c-530c-4369-95ba-2b7af4218515.png)

BUT .card-deck does not have any Bootstrap css for it, please look:
![image](https://user-images.githubusercontent.com/472921/230099706-5d535dff-b645-4e6e-b99b-e5561105a046.png)

### Versions

**Libraries:**

- BootstrapVue: ^2.23.0
- Bootstrap: ^5.3.0-alpha3
- Vue: 2.6.12

**Environment:**

- Browser: Chrome

**Comment by Hiws** [comment]
As mentioned in the previous issue you made. You're using the wrong version of Bootstrap.
BootstrapVue is built for Bootstrap 4, while you're using Bootstrap 5.
