### ISSUE TITLE
Badge variant css not included with Bootstrap Vue

### ISSUE THREAD

**Issue by caseytrombley** [bootstrap-vue/bootstrap-vue#7148]
### Describe the bug

Noticing that the Badge component does not render the css for variant and pill

### Steps to reproduce the bug

<img width="1756" alt="Screen Shot 2023-04-30 at 10 20 36 PM" src="https://user-images.githubusercontent.com/472921/235392706-b160714e-b2c2-4119-80a8-5fa00b7b6add.png">

Use <b-badge> component with variant prop, see that only the base .badge style is applied.

### Expected behavior

Should display with variants as shown in Vue Bootstrap documentation.

### Versions

**Libraries:**

- BootstrapVue: 2.6.11
- Bootstrap: 5.3.0-alpha3
- Vue: 2.23.0

**Environment:**

- Browser: All

**Comment by Hiws** [comment]
As mentioned in the previous two issues you've opened, BootstrapVue is made for **Bootstrap 4**, so it will not work as intended with Bootstrap 5.
