### ISSUE TITLE
Cannot configure  bootstrap-vue in Nuxt JS 3 app

### ISSUE THREAD

**Issue by suneethdev** [bootstrap-vue/bootstrap-vue#7152]
### Describe the bug

My Nuxt js version is **3.5.0** and I tried to install and configure bootstrap-vue in my app following the documentation. 
While running the app, I receive this error.
**Cannot start nuxt: Cannot read properties of undefined (reading 'hook')**

Here is my nuxt app configuration.
`export default defineNuxtConfig({
    modules: ['bootstrap-vue/nuxt']
})
`
bootstrap-vue version: 2.23.1
nuxt version: 3.5.0

**Comment by Hiws** [comment]
BootstrapVue doesn't support Vue 3 natively. Only via `vue/compat`, so i'll doubt you will have any luck getting it to work with Nuxt 3.
I'd suggest taking a look at `bootstrap-vue-next` instead.

**Comment by suneethdev** [comment]
> BootstrapVue doesn't support Vue 3 natively. Only via `vue/compat`, so i'll doubt you will have any luck getting it to work with Nuxt 3. I'd suggest taking a look at `bootstrap-vue-next` instead.

Thanks @Hiws :)

**Comment by jasonsrogers** [comment]
@suneethdev were you able to get `bootstrap-vue-next` working properly with nuxt 3? 

(I'm picking up somebody else's project and looking at updating libraries)
