### ISSUE TITLE
Nav dropdown menu "right" positioning doesn't work 

### ISSUE THREAD

**Issue by caseytrombley** [bootstrap-vue/bootstrap-vue#7157]
### Describe the bug

Following your documentation on the navbar dropdown menu, it seems that the 'right' position prop (or any position prop) does not work. The css class is applied, but there is not styling that actually positions the dropdown menu correctly. see screenshot.

### Versions

**Libraries:**

- BootstrapVue: 2.22.0
- Bootstrap: 5.2.1
- Vue: 2.7.10

**Environment:**

- MacOS
- Chrome

<img width="2165" alt="image" src="https://github.com/bootstrap-vue/bootstrap-vue/assets/472921/6d6ef848-222f-4cae-9d5d-aa6b63f617ba">

**Comment by caseytrombley** [comment]
This was closed without a solution?

**Comment by Hiws** [comment]
Because you don't bother reading my replies to your other issues.
