### ISSUE TITLE
Examples on how to implement filters

### ISSUE THREAD

**Issue by matefreire** [bootstrap-vue/bootstrap-vue#7159]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs/components/table#built-in-filtering

### Additional context or description

Hello, I would like to request some additional information and examples regarding filtering. Specifically, I am interested in understanding how to apply filters to manipulate and format data effectively.

I have been working with Bootstrap Vue and I am aware of the v-b-model directive for two-way data binding. However, I would like to learn more about how to use filters in combination with Bootstrap Vue to achieve specific formatting requirements without modifying the underlying data model.

Could you kindly provide more detailed explanations and examples on how to implement filters in Bootstrap Vue? I am particularly interested in understanding how to format values, such as adding prefixes or suffixes, applying decimal places, or separating thousands with commas.

**Comment by Hiws** [comment]
Not sure what you specifically want.
Sounds like you just want to format your data visually, which is more of a Vue question.
Which you would do by creating a method, and using it where you want to display the formatted data.

`{{ formatData(data) }}`
