### ISSUE TITLE
handling Punctuation in sorting

### ISSUE THREAD

**Issue by ssg-financial-com** [bootstrap-vue/bootstrap-vue#7166]
### Steps to reproduce the bug

1. Enable default sorting in BTable
2. pass prop as i.e  sort-compare-options="{ ignorePunctuation: true }"
3. Click on sorting icon to sort the column with punctuation '-'
4. The punctuation '-' is shown at the top.

See screenshot below from your website where one column first_name has '-' and with sorting enabled in ascending. The '-' is shown at top. with sort-compare-options="{ ignorePunctuation: true }"
![image](https://github.com/bootstrap-vue/bootstrap-vue/assets/104846817/485a5623-8440-4420-9dfe-ad1991dcbe60)

### Expected behavior

The punctuation '-' should be shown at last 

### Versions

**Libraries:**

- BootstrapVue: 2.23.0
- Vue: 2.7.#

**Comment by Hiws** [comment]
The table uses [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare), for these options. 
So the behavior is dependent on that.

Which you can test with the following:
```js
const names = ['Larsen', '-', 'Geneva', 'Jami'];

names.sort((a, b) => a.localeCompare(b, undefined, { ignorePunctuation: true }));

console.log(names);
```

If you want to sort it differently, you'll have to make your own custom sort routine.

**Comment by ssg-financial-com** [comment]
Thanks
