### ISSUE TITLE
[b-alert] Dismissible alerts cannot be resused

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#718]
So I'm trying so use a single alert component in a parent vue component. Children pass up messages, and the parent resets the content and `show` value on the alert. I can't get the alert to re-show because the `show` value in the parent isn't updated when using the countdown. I try updating the show value with the dismiss countdown event, but that doesn't work after I dismiss an alert.

https://jsfiddle.net/alexsasharegan/zrdur2cp/

- Try dropping a msg into the input, letting it self-dismiss. All good.
- Now try the other btn. Should be good.
- Now fire a btn and dismiss. Should close.
- Now fire another btn. DOA

**Comment by mosinve** [comment]
`bootstrapVue.prototype.Alert()`

**Comment by tmorehouse** [comment]
@mosinve that is a cool idea!

**Comment by alexsasharegan** [comment]
Weird, it seems to be working now...

**Comment by mosinve** [comment]
it breaks only if

- Try dropping a msg into the input, letting it self-dismiss. All good.
- Now try the other btn. Should be good.
- Now fire a **GREEN** btn and dismiss. Should close. (for X times)
- Now fire a **RED** btn and dismiss. Should close.
- Now fire **GREEN** btn. DOA

**Comment by alexsasharegan** [comment]
I have a suspicion this is related to using a number countdown in conjunction with early dismissal. Also, I don't think I like that the dismiss countdown doesn't accept a `value < 2`. That should be up to the dev to decide that's a silly time.

**Comment by alexsasharegan** [comment]
Using `v-model` here seems to make much more sense. `show` is copied to a closure-scoped variable `dismissCountDown`, but as the countdown is decremented, `show` remains unchanged.

**Comment by TonBits** [comment]
Able to replicate this on the main documentation page using Chrome

https://bootstrap-vue.js.org/docs/components/alert/

Steps to replicate easily
1.) Click on the "Show alert with count-down timer" button
2.) Click the X mark quickly (less than a second after clicking the button above)
3.) Clicking the button again will not display the alert anymore.

This has something to do with the timing with the dismiss countdown timer.

**Comment by alexsasharegan** [comment]
@TonBits If you have the time, have a look at PR #721. Try pulling the branch down, run `yarn docs-dev`, and visit the docs page on [127.0.0.1:3000](http://127.0.0.1:3000). You'll notice my note in the PR. I'm curious how much that change would affect you and other users.

**Comment by tmorehouse** [comment]
This issue has been "fixed" in v0.20.2 by removing the close button on auto-dissmising alerts.

**Comment by tmorehouse** [comment]
PR's #897 (0.x dev branch) and #898 (1.x branch) should address this.

The main root cause was actually the demo not listening to `@dismissed` and resetting the countdown value to 0.  What was happening is that `dismissCountDown` didn't change when `dimissed` was called before the first second elapsed, So the `dismissCountDown` var still had a value that was the same as it was originally (the initial countdown value).  So trying to set `show` to this value again never triggered the `show` watcher.

But these PRs also will emit a dismiss countdown event with value of 0 when dismissed is called as well, as a just in case.

**Comment by kostia7alania** [comment]
test
