### ISSUE TITLE
Sortable does not show

### ISSUE THREAD

**Issue by Tini79** [bootstrap-vue/bootstrap-vue#7184]
I got this issue when applying sortable as true, the sortable button does not appear on th.
<img width="218" alt="image" src="https://github.com/bootstrap-vue/bootstrap-vue/assets/97665722/242650fc-68ec-4c1a-9dbf-7fc6b2e1e2ea">

**Comment by Hiws** [comment]
Ensure you're using a supported version of Bootstrap, and that you're including BootstrapVue's CSS.
