### ISSUE TITLE
Checkbox not updating when used in table header slot.

### ISSUE THREAD

**Issue by DjOli** [bootstrap-vue/bootstrap-vue#719]
I have been attempting to add a 3 state (true, false, intermediate) checkbox to the header of a table which ties in with each rows individual checkboxes. I am able to calculate and update the state of the checkbox and render it as I would like using a calculated function with getter and setter, however the checkbox within the header doesn't render correctly. I have tried simplifying the checkbox within the header and found that it still doesn't work. Here's some example code:

```
<b-table :items="items" :fields="fields" :filter="filter">
  <template slot="HEAD_selected" scope="data">
    <input type="checkbox" v-model="allSelected"> {{allSelected}}
  </template>
  <template slot="selected" scope="entry">
    <input type="checkbox" v-model="allSelected">
  </template>
</b-table>
```

In this example, the table contains a column for 'selected' The header contains a checkbox bound to 'allSelected' along with an output of the 'allSelected' variable, and each row also has a checkbox bound to 'allSelected'. Clicking the header checkbox updates the 'allSelected' variable, and the checkbox in every row updates accordingly, however the checkbox in the header remains unchanged. Clicking the checkbox again does nothing, as if the checkbox itself is still in its previous state. Clicking any of the checkboxes in the rows updates all checkboxes including the one in the header. 

I have tried this with a standard checkbox, like the example above, and using the Bootstrap Vue b-form-checkbox.

**Comment by tmorehouse** [comment]
When checkboxes are bound to the same v-mode, they typically return an array to the v-model, with a value for each checked checkbox.

You probably need two variables, one for the check all, and one for the rows.

Check out this fiddle which is using checkboxes for select individual and select all...

https://jsfiddle.net/bootstrapvue/js5dqnjv/

**Comment by DjOli** [comment]
Thanks for the help.

I didn't actually have multiple checkboxes bound to the same variable, instead the select all checkbox in the header was bound to a computed variable with a getter and setter, which returns 1 of 3 states (true, false, intermediate) based on the number of individually selected items.

Your suggestion wasn't exactly what I had planned, however I played around with it and found that what actually fixed the problem was adding @click.stop="foo". Take the following for example:

```
<b-table :items="items" :fields="fields" :filter="filter">
  <template slot="HEAD_selected" scope="data">
    <input type="checkbox" v-model="allSelected">
    <input type="checkbox" @click.stop="toggleSelected" v-model="allSelected">
  </template>
</b-table>
```

The top checkbox doesn't respond correctly when clicking, despite the allSelected value updating correctly (which you can see via the second checkbox or just by observing the underlying variable). The bottom checkbox reacts as expected. I would also like to point out that the toggleSelected function does nothing, so simply having the @click.stop bound addresses the issue. I believe this may still be an issue with tables, or specifically table headers, as the first checkbox implementation works as one would expect when put anywhere else on the page.

**Comment by tmorehouse** [comment]
Headers (and footers) have a click handler on them for setting and clearing the sort direction.  

When placing "actionable" items (i.e. buttons, inputs, links, etc) in the header (or footer) will need to use the `@click.stop` notation to prevent the sort from changing (or clearing).

For actionable items in the data rows, they should also use `@click.stop`, as normally clicking on a row will fire the `row-clicked` event.

In the 3example fiddle... toggle Selected is actually not a good name for the method, as it either selects all or none of the items.  Selecting all the items, then clicking and removing one of the check in the row clears the select all checkbox.  manually checking all the row checkboxes will set the select all checkbox, etc. So the method **is** actually doing something.

In the original question above, you show the header slot and data slot using the same `v-model` binding (to `allSelected`), which is why I suggested tying them to different bindings.

**Comment by DjOli** [comment]
No worries, your explanation makes sense and explains the solution. The original question was simply trying to prove a point on the bug I was experiencing, sorry for the confusion.

It may be worth explaining this in the documentation (https://bootstrap-vue.js.org/docs/components/table) for making use of the table head slot as this requirement is not well documented.

**Comment by tmorehouse** [comment]
I have added a few extra bits in the slots documentation to note about using `@click.stop` handlers on inputs, buttons and links.

https://github.com/bootstrap-vue/bootstrap-vue/blob/master/docs/components/table/README.md

**Comment by DjOli** [comment]
Excellent! Thanks for all the help.

**Comment by tmorehouse** [comment]
As an aside, I have modified `<b-form-checkbox>` in PR #720 to support tri-state checkboxes (both in custom and plain mode checkboxes)

**Comment by happilymarrieddad** [comment]
@tmorehouse  Hmm, I seem to be experiencing this same issue. I click and it highlights for a second and then disappears.

![selection_094](https://user-images.githubusercontent.com/6416323/32579887-113449e6-c4a0-11e7-9d80-66ed4dff8795.png)
![selection_095](https://user-images.githubusercontent.com/6416323/32579891-146f08c6-c4a0-11e7-8369-07addcc62c24.png)

**Comment by voidm4p** [comment]
Here is a working example, based on the other one: https://jsfiddle.net/js5dqnjv/3/

**Comment by truongntoan** [comment]
https://jsfiddle.net/js5dqnjv/75/
Fix check on header select all or deselect all base on this one  https://jsfiddle.net/js5dqnjv/3/
toggleSelected() {
      	this.allSelected = !this.allSelected; //add this line
        this.checkedItems = this.allSelected ? this.tableValues : [];
      },

**Comment by slidenerd** [comment]
highly related to this issue, I am trying to put a split button dropdown list inside a table header which looks like this. When I click the left part of the button I would like to sort the items while clicking the right part of the button, I wanted to open the menu. Following the above code, I added@click.native.stop but I dont see it getting fired, in normal JS I would simply call stop propagation, am I missing something here, thanks for your suggestion in advance

![image](https://user-images.githubusercontent.com/5139030/49335949-38f78f00-f61e-11e8-9fd0-19ae0be9687f.png)

    <b-table :fields="columnDefinitions" :items="rows">
      <template slot="HEAD_name" slot-scope="data">
        <div class="btn-group d-flex" @click.native.stop="toggleSelected">
          <button type="button" class="btn btn-light w-100 btn-sort">
            <i class="fa fa-sort-up"></i>
            <span>{{data.label}}</span>
          </button>
          <button
            type="button"
            class="btn btn-light dropdown-toggle dropdown-toggle-split"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <i class="fa fa-filter"></i>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu dropdown-menu-right">
            <form class="px-4 py-3">
              <div class="form-group">
                <select class="custom-select filter-options">
                  <option value="1" selected>Above</option>
                  <option value="-1">Below</option>
                  <option value="0">Equal</option>
                  <option value="2">Between</option>
                </select>
              </div>
              <div class="form-group filter-min-container">
                <label for="min" class="sr-only">Min</label>
                <input type="text" class="form-control filter-min" placeholder="10">
              </div>
            </form>
          </ul>
        </div>
      </template>

      <template slot="alert" slot-scope="data">
        <b-button variant="outline-danger">
          <i class="fa fa-bell"></i>
        </b-button>
      </template>
    </b-table>

**Comment by slidenerd** [comment]
**Issue Fixed**
Thank you
I added this block of code after following the documentation to do @click.stop. Only problem now is that multiple dropdowns remain open, I ll see if I can find something about it
```

    details(item, index, clickedElement) {
      let parent = clickedElement.parentElement;
      let parentClassList = parent.classList;
      if (parentClassList.contains("show")) {
        parentClassList.remove("show");
      } else {
        parentClassList.add("show");
      }

      let expanded = clickedElement.getAttribute("aria-expanded") === "true";
      clickedElement.setAttribute("aria-expanded", !expanded);

      let menu = parent.querySelector("ul.dropdown-menu");
      let menuClassList = menu.classList;
      if (menuClassList.contains("show")) {
        menuClassList.remove("show");
      } else {
        menuClassList.add("show");
      }
    }
```

**Comment by tmorehouse** [comment]
This might be fixed in the lastest `dev` branch.

**Comment by impowski** [comment]
@tmorehouse Please fix this one, I checked today the `dev` branch and it doesn't work like expected, still all events from are suppressed.

**Comment by impowski** [comment]
@tmorehouse 

Table:
```
    <b-table
      :sort-by:sync="sortBy"
      :sort-desc:sync="sortDesc"
      :items="items"
      :fields="fields"
      striped
      hover
    >
      <template
        v-for="field in fields"
        slot-scope="data"
        :slot="`HEAD_${field.key}`"
      >
        <filter-select
          :label="data.label"
          :key="field.key"
        />
      </template>
    </b-table>
```

FilterSelect:
```
  <b-dropdown
    variant="link"
    toggle-class="orders__header--btn"
    no-caret
  >
    <template slot="button-content">
      {{ label }}
      <i class="fa fa-sort"/>
    </template>
    <b-dropdown-item-button>Ascending</b-dropdown-item-button>
    <b-dropdown-item-button>Descending</b-dropdown-item-button>
    <b-dropdown-divider/>
    <b-dropdown-item
      v-for="option in options"
      :key="`option_${option.value}`"
    >
      <b-checkbox
        v-model="selected"
        :value="option.value"
        @click.native.stop
      >{{ option.label }}</b-checkbox>
    </b-dropdown-item>
  </b-dropdown>
```

**Comment by impowski** [comment]
@tmorehouse Currently I'm trying to implement this in production and it's just seems impossible to me

**Comment by tmorehouse** [comment]
So it is the checkbox inside of `b-dropdown` that you are having issues with?

The `dev` branch is currently not available on NPM. (we are looking into providing an `@next` version though).

Hoping to have the new release published before I head out on vacation Monday (for 3 weeks).

**Comment by impowski** [comment]
@tmorehouse Yeah, it is. I know that I can just use `input` and everything will work but anyway.

**Comment by LarBearrr** [comment]
Not sure what I'm missing but I'm having a really hard time implementing this functionality. 

Following @truongntoan's [fiddle](https://jsfiddle.net/js5dqnjv/75/) is working, however I cannot use the <b-form-checkbox> component instead of a standard checkbox input. Also, is there a way to work around the slot-scope attribute? I don't want to have to display a label or something in the header, I just want the checkbox.

**Comment by LarBearrr** [comment]
Thanks @tmorehouse. I've got it working with an empty label for the column. However, this presents an issue when displaying a list of the columns to allow for custom show/hide. 

I'm passing my field definitions from my Laravel controller:

```
'fields' => [
            'actions' => [
                'label' => ''
            ],
            'name' => [
                'label' => 'Full name',
                'sortable' => true,
                'sortDirection' => 'asc'
            ],
            'email' => [
                'label' => 'Email',
                'sortable' => true,
            ],
            'created_at' => [
                'label' => 'Created at',
                'sortable' => 'true'
            ],
            'setup' => [
                'label' => ''
            ]
        ]
```

So my component looks like:
```
<b-table striped hover :items="data" :fields="columns" :sort-by="sortBy" :filter="filter" v-model="tableValues">
            <template slot="HEAD_actions" slot-scope="actions">
                {{actions.label}}
                <input type="checkbox" @click.stop="toggleSelected" v-model="allSelected">
            </template>
            <template slot="actions" slot-scope="item">
                <input type="checkbox" name="checked" :key="item.index" :value="item.item" @click.stop v-model="checkedItems">
            </template>
            <template slot="HEAD_setup" slot-scope="setup">
                {{setup.label}}
                <i class="fa fa-list ml-auto" @click.stop="showSetup"></i>
            </template>
        </b-table>
```

You'll notice I have another slot for a "setup" button which I would like to display a modal that will allow the user to select which columns the wish to display:

```
<!-- List setup modal -->
        <b-modal id="setupModal" title="List setup" ok-only>
            <p>Use checkboxes to select columns you want to see in the list. You can change position of columns by dragging them up or down.</p>
            <b-form-group>
                <b-form-checkbox-group stacked v-model="selected" :options="columns" />
            </b-form-group>
            <label>Records per page</label>
            <p>Select the number of records per page to display. Please note that high number of records on a single page can reduce performance.</p>
            <b-form-select v-model="recordsPerPage" class="mb-3">
                <option :value="recordsPerPage">{{recordsPerPage}}</option>
                <option value="40">40</option>
            </b-form-select>
        </b-modal>
```
This is my result:
![image](https://user-images.githubusercontent.com/28734844/51558419-065f5b00-1e45-11e9-9471-94fbd936263c.png)

You can see that the `actions` and `setup` columns are outputted as part of the checkbox group because the exist in the field definition. Also, I would like to be able to show the field label and not the field name (eg. name => Full name). 

I though about using a `v-for` with the b-checkbox component, however they are displayed inline. 

Do you have any thoughts?

**Comment by mauriciojsola** [comment]
Hi, why the checkboxes are no longer rendering as "checkboxes"?
I have the same issue when using code like this:

```
<template slot="ProductSelection" slot-scope="row">
              <b-form-checkbox
                v-model="row.IsSelected"
                @input="onPreviewClick($event, row.index, row.item)"
              ></b-form-checkbox>
            </template>
```

https://jsfiddle.net/js5dqnjv/75/

Thanks!

![vue-ckeckbox not rendeing](https://user-images.githubusercontent.com/1199946/91087884-8c4a1600-e627-11ea-89cf-5c56be758ab7.png)

**Comment by artwiney** [comment]
getting the same issue as above. guessing some kind of js error but not seeing one.

**Comment by pm-erman** [comment]
same issu here, cannot see any checkboxes.

**Comment by superzjn** [comment]
`      <b-table hover
               :key="tableKey"
               :items="portfolios"
               ref="portfoliosTable"
               :fields="fields"
               :sort-by.sync="sortBy"
               :sort-desc.sync="sortDesc"
               :small="true"
               :responsive="true"
               :sticky-header="true"
               :tbody-tr-class="rowError"
               :selectable="selectable"
               `@row-selected="onRowSelected">`
        <template #head(header_name)="header_name">
          <mds-checkbox v-if="editable" :disabled="!selectable" hidden-label
                        @change="selectAllPortfolios($event)" style="padding-right: 10px" />
          {{ key.label }}
        </template>...
`

Code above works for. Adding a checkbox to the table header
