### ISSUE TITLE
 b-form-radio-group Issue : Not able to Get the Id and Text on v-model for b-form-radio-group

### ISSUE THREAD

**Issue by qadirfarooq** [bootstrap-vue/bootstrap-vue#7195]
### Describe the bug

i am trying to get the id and text both at the same time on the v-model of the b-form-radio-group. there are only two options on the b-form-radio-group to display and set the value. see below. what i am looking for is my v-model should return id and text both.
1. text-field="text"   2. value-field="id" 

 <b-form-radio-group stacked size="md" aria-invalid="false"   @change="radiochange($event)" v-model="Selected" :options="Plans"   text-field="text" value-field="id" name="Criteria-radio"></b-form-radio-group>

### Steps to reproduce the bug

i am using VueJs. when i bind my array using html 5 the v-model gave me " { id: "P", text: "Profit" }". but  when i am using BootstrapVue and setting the value-field="id" the results are only the id field (which make sense b/c we are binding id only). 

 how i can combine the id and text to produce " { id: "P", text: "Profit" }" 

 
1.  Data element : Array 
2. Plans :[  { id: "S", text: "Sale"},
        { id: "P", text: "Profit" },
        { id: "E", text: "End" },
        { id: "F", text: "Others" },
         ],
         Selected:''
 

### Expected behavior
html code: 
 <b-form-radio-group stacked size="md" aria-invalid="false"   @change="radiochange($event)" v-model="Selected" :options="Plans"   text-field="text" value-field="id" name="Criteria-radio"></b-form-radio-group>

Result : {{Selected}}

Result should be :  { id: "P", text: "Profit" } NOT "P" 

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue:3 .#.#

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: [e.g. macOS Mojave or iOS 12]
- Browser: [e.g. Chrome]
- Version: [e.g. 70]

**Comment by Hiws** [comment]
If you want the object itself, then don't use the `options` prop, and instead generate the radio buttons yourself.

```html
<b-form-radio-group stacked size="md" aria-invalid="false" v-model="selected">
  <b-form-radio v-for="plan in plans" :value="plan">
    {{ plan.text }}
  </b-form-radio>
</b-form-radio-group>
```

**Comment by qadirfarooq** [comment]
perfect.. Appreciate. I thought I could only use what bootstrap -vue
offers.
