### ISSUE TITLE
Documentation layout its broken

### ISSUE THREAD

**Issue by strikermdd** [bootstrap-vue/bootstrap-vue#72]
Hi, accessing the documentation, you see its all broken. Any changes that makes that?

All layout its broken and design elements missing.

**Comment by pi0** [comment]
oh that's 4.0.0-alpha.6 it seems flex build is not included anymore ! 
` Can't resolve './../node_modules/bootstrap/dist/css/bootstrap-flex.css' in 'C:\opt\code\bootstrap-vue\.nuxt'`
