### ISSUE TITLE
Text spacing is not adapting for the menu items in the "Default" combo box in column options pane.

### ISSUE THREAD

**Issue by msftedad** [bootstrap-vue/bootstrap-vue#7206]
### Describe the bug

Text spacing is not adapting for the menu items in the "Default" combo box in column options pane.

### Steps to reproduce the bug

1. Open the above URL " [Aspect | Components | BootstrapVue (bootstrap-vue.org)](https://bootstrap-vue.org/docs/components/aspect) ".
2. Navigate to the "aspect ratio" dropdown. 
3. Observe the issue
![222150](https://github.com/bootstrap-vue/bootstrap-vue/assets/93735775/f66c39ac-5af9-4ac5-9ad1-e72fe63deab7)

### Actual behavior

Text spacing is not adapting for the menu items in the "Default" combo box in column options pane.

### Expected behavior

Text spacing should be adapt for all the menu items in the "default" combo box in column options pane.
### Versions

**Libraries:**

- BootstrapVue: ^2.22.0
- Bootstrap: 4.6.1
- Vue: ^2.6.10

**Environment:**

- Device: [e.g. Mac or iPhone X]
- OS: Windows 11 23H2 ((OS Build 26052.1000)
- Browser: Edge
- Version: 123.0.2380.1 (Official build) stable app, dev channel (64-bit)

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
If you're talking about the options in the `Aspect Ratio` `<select>` then that's just how browsers work.
