### ISSUE TITLE
Text spacing is not adapting for the menu items in the "Selected" combo box.

### ISSUE THREAD

**Issue by msftedad** [bootstrap-vue/bootstrap-vue#7208]
### Describe the bug

Text spacing is not adapting for the menu items in the "Selected" combo box.

### Steps to reproduce the bug

1. open the URL "https://vuejs.org/guide/essentials/forms.html#select".
2. Navigate to the Selected dropdowns.
3. Observe the issue.

### Actual behavior

Text spacing is not adapting for the menu items in the "Selected" combo box.
![Selected Combo box](https://github.com/bootstrap-vue/bootstrap-vue/assets/93735775/02f17355-ef45-444b-bae8-af7be2c1b1b5)

### Expected behavior

Text spacing should be adapt for all the menu items in the "Selected" combo box.

### Versions

**Libraries:**

- BootstrapVue: ^2.22.0
- Bootstrap: 4.6.1
- Vue: ^2.6.10

**Environment:**

- Device: Window
- OS: Windows 11 24H2 ((OS Build 26100.1)
- Browser: Edge
- Version: 125.0.2535.6

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
Please stop opening issues. This isn't a bug. It's browser behavior.
Styling `<option>` on a `<select>` is severely limited, and out of our control.
