### ISSUE TITLE
Text spacing is not adapting for the menu items in the "Aspect ratio" combo box.

### ISSUE THREAD

**Issue by msftedad** [bootstrap-vue/bootstrap-vue#7209]
### Describe the bug

Text spacing is not adapting for the menu items in the "Aspect ratio" combo box.

### Steps to reproduce the bug

1. Open the URL "[Aspect | Components | BootstrapVue (bootstrap-vue.org)](https://bootstrap-vue.org/docs/components/aspect).
2. Navigate to the Aspect ratio combo box
3. Observe the issue.
![Text Spacing_Aspect ratio](https://github.com/bootstrap-vue/bootstrap-vue/assets/93735775/dc040ad8-544d-4bfe-a3ff-8ec8adaf9710)

### Expected behavior

Text spacing should be adapt for all the menu items in the "Aspect Ratio" combo box.

### Versions

**Libraries:**

- BootstrapVue: ^2.22.0
- Bootstrap: 4.6.1
- Vue: ^2.6.10

**Environment:**

- Device: Window
- OS: 24H2 ((OS Build 26100.1)
- Browser: Edge
- Version:  125.0.2535.6 

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Add any other context about the bug here.

**Comment by Hiws** [comment]
Please stop opening issues. This isn't a bug. It's browser behavior.
Styling `<option>` on a `<select>` is severely limited, and out of our control.
