### ISSUE TITLE
Text spacing is not adapting to the "switch to dark color theme" tooltip.

### ISSUE THREAD

**Issue by msftedad** [bootstrap-vue/bootstrap-vue#7212]
### Describe the bug

Text spacing is not adapting to the "switch to dark color theme" tooltip.

### Steps to reproduce the bug

1. Open URL BootstrapVue (bootstrap-vue.org)
2. Navigate to the "GitHub, twitter, discord and open collective" button tooltips in banner region.
3. Apply text spacing and observe the issue.

[Text Spacing is not adopted.webm](https://github.com/bootstrap-vue/bootstrap-vue/assets/93735775/1cff382c-e088-4238-bb52-f0257b10b8de)

### Expected behavior

Text spacing should be adapt for all the "GitHub, twitter, discord and open collective" tooltip.

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.23.0

**Environment:**

- Device: windows
- OS:23H2 ((OS Build 22631.3737)
- Browser: Edge
- Version: 126.0.2592.87 (Official build) (64-bit)

### Demo link

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

You can also export markup from the [Online Playground](https://bootstrap-vue.org/play) to _CodePen_, _CodeSandbox_ or _JSFiddle_.

### Additional context

Add any other context about the bug here.

Open URL [BootstrapVue (bootstrap-vue.org)](https://bootstrap-vue.org/)
navigate to the "GitHub, twitter, discord and open collective" button tooltips in banner region.
Apply text spacing and observe the issue.

**Comment by Hiws** [comment]
Those are browser native tooltips.
