### ISSUE TITLE
Expand or scroll collapse up

### ISSUE THREAD

**Issue by klaveren** [bootstrap-vue/bootstrap-vue#722]
I would like to know if there is any property to set up scrolling from the content of a collapse up. By default it works down, and I need it up.

Grateful

**Comment by tmorehouse** [comment]
Not offhand.

Currently collapse provides only the current Bootstrap V4 collapse characteristics (which shrinks the height of the collapse via transition).

YOu might be able to use some of the Bootstrap Helper classes to align your content to the bottom of the collapse container. http://v4-alpha.getbootstrap.com/utilities/vertical-align/

But it might require a few extra wrappers on your content.

Note that collapse always uses `display:block` during transition, and while it is open.

**Comment by tmorehouse** [comment]
If you're just looking for a collapse that opens above the trigger element, then you can just place your trigger  button (or element) below you collapsable content.

**Comment by tmorehouse** [comment]
Here is an example of a collapse that expands up above a toggle button: https://jsfiddle.net/bootstrapvue/pjtxzhb3/
