### ISSUE TITLE
Bootstrap-vue toast isn't showing but appears in body

### ISSUE THREAD

**Issue by SyntaxXeror** [bootstrap-vue/bootstrap-vue#7223]
I'm trying to use the Toast component imported as the ToastPlugin.

Firstly, I must mention that I have two other Views in my app where ToastPlugin works with no problem (They are TypeScript components).
This component I'm struggling with is JavaScript, and before you guys say I should then just convert my component to TypeScript... I have already tried that and it made no difference. I also tried to use the toast in another TypeScript component and it also didn't work.

First I had a lot of issues even getting my app to read the property saying `TypeError: Cannot read property '$bvToast' of undefined`, then I found a solution for this problem in issue #6454.

My problem now is that I see the element of `<div id="b-toaster-top-center" class="b-toaster b-toaster-top-center">` appear in my body but I see nothing in my app. If I hover the element in the body it shows in the bottom left corner that the element should be down there:
![image](https://github.com/user-attachments/assets/8295a167-8567-4d03-9137-f6822e4a8ea1)

Here is my code for the `notificationToast.js` export function that I have made:

```js
import Vue from "vue";
import { ToastPlugin } from "bootstrap-vue";
Vue.use(ToastPlugin);

export function notificationToast(message, title, toaster, variant) {
    console.log("notificationToast");
    this.$bvToast.toast(message, {
        title: title,
        autoHideDelay: 5000,
        toaster: toaster,
        variant: variant,
        solid: true,
    });
}
```

The `console.log("notificationToast")` is displayed on my console output therefore I know that the function is working, and again, I see the HTML element appear in the body.

notificationToast is imported to my View and used on an event listener to catch a modal saying emitting that its form is successfully submitted:

```js
import { notificationToast } from "@/js/Exports/NotificationToast.js";

export default {
    methods:{
        notificationToast,
    }
    mounted() {
        this.bus.$on(BusEvents.FormSubmitted, () => {
            /* Some other functionality */
            this.notificationToast("Form is successful", "Success", "b-toaster-top-center", "success");
        });
    }
}
```

I will gladly provide more information if needed.
Any help is appreciated!

---

#### Libraries:

- BootstrapVue: ^2.23.0
- Bootstrap: ^4.4.1
- Vue: ^2.6.12

**Comment by Hiws** [comment]
Have you imported BootstrapVue's CSS in your app?

**Comment by SyntaxXeror** [comment]
It's always the simplest solutions that cause the greatest frustration... I feel dumb 🤡
