### ISSUE TITLE
`b-modal` not working within `v-for`

### ISSUE THREAD

**Issue by mismith** [bootstrap-vue/bootstrap-vue#723]
If I remove an item from an array being rendered in a `v-for` loop, the modal-triggering button in the item _after_ the removed item no longer works.

Check the fiddle/instructions here to see: https://jsfiddle.net/mismith/g2zd3v6a/5/

I suspect this has to do with some clever Vue internal recycling of elements or some event listeners not being handled properly? Anyone have a fix or workaround?

**Comment by alexsasharegan** [comment]
Real quick probably answer: you need to key your elements or vue will reuse elements that were removed. Event listeners will get weird. 

Check out vue documentation: https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key
Check out the changes: https://jsfiddle.net/alexsasharegan/g2zd3v6a/6/

**Comment by mismith** [comment]
Doh! You're totally right, I forgot to add the `key` prop.

For future reference, fixed: https://jsfiddle.net/mismith/g2zd3v6a/7/

**Comment by alexsasharegan** [comment]
Just ran into this yesterday with `v-if`s. Easy to forget!
