### ISSUE TITLE
Help: Using images in carousel

### ISSUE THREAD

**Issue by johnfercher** [bootstrap-vue/bootstrap-vue#727]
How may I use images from my project in img tag of b-carousel-slide? I'm trying to define **img="~@/assets/img/thumbnails/01.jpg"**, but it doesn't works.

```html
<div class="container-fluid">
  <div class="container">

    <b-carousel controls indicators :interval="7000" background="#ABABAB" height="300px">
      <!-- Text slides -->
      <b-carousel-slide height="300px" caption="First slide" text="Nulla vitae elit libero, a pharetra augue mollis interdum." img="~@/assets/img/thumbnails/01.jpg">
      </b-carousel-slide>

    </b-carousel>

  </div>
</div>
```

**Comment by alexsasharegan** [comment]
This looks like more of a webpack integration question. That path looks a webpack alias that only webpack can resolve. Am I close? What exactly is that path?

**Comment by mosinve** [comment]
as i know, usually, `~` is not needed before alias, except if your path is in linux home dir....

**Comment by johnfercher** [comment]
I have tried **~**, **~@**, **@** but without success. I initiated the project with **vue init webpack project_name**. 

In my index.html, I can load images using.
```html
<link rel="icon" href="/assets/img/logo.jpg">
```

And in a component.vue, I can load images using 
```html
<img src="~@/assets/img/logo.jpg" class="img-fluid rounded-circle">
```

I can't load the same image in the carousel.

**Comment by tmorehouse** [comment]
If you can find a solution to your issue, please post it here.

**Comment by johnfercher** [comment]
Basically I moved all the images to static folder and it worked.

**Comment by pedroskakum** [comment]
The "~@" works fine outside of carousel, but in carousel, i have the same problem

**Comment by tmorehouse** [comment]
This might be due to when the URL is converted to the final URL.  Since this is being passed as a string to the carousel slide.

Maybe we need to make a slot for the carousel image.

**Comment by pedroskakum** [comment]
Ok, meanwhile I'm using the images used in the carousel in the "/ static" folder. Thanks

**Comment by tmorehouse** [comment]
Yeah, I think this is because the string is not directly tied to an img src attribute, and the builder sees it as a variable.

**Comment by johnfercher** [comment]
Is possible resolve this issue? I mean, every place in Vue and Vue-Bootstrap I can use images from assets folder, just in Carousel this happens.

**Comment by tmorehouse** [comment]
I am guessing `cards` would also have this same issue, since you are passing a string var to the component to specify the image source.

As an experiment... make a simple component like this:

```html
<!-- test.vue component -->
<template>
  <div><img :src="src"/></div>
</template>
<script>
export default {
  props: {
    src: { type: String, default: null }
  }
};
</script>
```

And then use the component:

```html
<test src="...."></test>
```

and I bet you will have the same issue

**Comment by tmorehouse** [comment]
I know this is an old issue, but here is a solution.  In your vue-loader config options, you need to instruct it to know which props are available to be transformed via the `transformToRequire` option of `vue-loader`:

```js
transformToRequire: {
  img: 'src',
  image: 'xlink:href',
  'b-img': 'src',
  'b-img-lazy': ['src', 'blank-src'],
  'b-card': 'img-src',
  'b-card-img': 'img-src',
  'b-carousel-slide': 'img-src',
  'b-embed': 'src'
}
```
