### ISSUE TITLE
Popover console warnings

### ISSUE THREAD

**Issue by wanxe** [bootstrap-vue/bootstrap-vue#735]
When using the popover component and hovering the mouse, the console displays the following error:

`[Vue warn]: Error in beforeDestroy hook: "TypeError: this.$data._trigger.className.replace is not a function"
found in
---> <BPopover>`

**Comment by tmorehouse** [comment]
Hmmm I wonder if this should be using `.classList.add/.classList.remove`?

**Comment by mosinve** [comment]
i think it goes from `lib/mixins/popover.js, line 203`
```
        destroyTether() {
            if (this.$data._tether && !this.showState) {
                this.$data._tether.destroy();
                this.$data._tether = null;
                const regx = new RegExp('(^|[^-]\\b)(' + TETHER_CLASS_PREFIX + '\\S*)', 'g');
here ---->    this.$data._trigger.className = this.$data._trigger.className.replace(regx, '');
            }
        },
```

**Comment by tmorehouse** [comment]
Ah, it is using the `String.prototype.replace` and if this.$data._trigger is possibly undefined (or not a string).

**Comment by mosinve** [comment]
Yep, at least it needs undef check here...

**Comment by tmorehouse** [comment]
If for some reason the default slot content changes (or gets emptied) before `destroyTether()` gets called, then, `thi.$data._trigger` could be null/undefined, or the element may not exist.
