### ISSUE TITLE
Field properties tdClass and class not recognized when style uses scoped option.

### ISSUE THREAD

**Issue by egomolka** [bootstrap-vue/bootstrap-vue#736]
Hi:
Thanks for creating a nice set of components.

I am on Vue 2.3.4/Bootstrap-Vue 0.18.0.
I have been modifying the table look with tdClass, class, and thStyle. I found that my class and tdClass values were ignored as long as I specified <style scoped> in my Vue file. Everything works fine once I remove the "scoped" option.

**Comment by tmorehouse** [comment]
In this case for these extra classes, scoping will most likely not work (currently), as scoped CSS gets modified with a `[v-xxxxxx]` attribute.
