### ISSUE TITLE
Tab's "title" prop clashes with HTML attribute

### ISSUE THREAD

**Issue by epicyclist** [bootstrap-vue/bootstrap-vue#740]
`<b-tab>`'s title prop prevents the use of the actual title attribute.

If I attempt to wrap `<b-tab>` in `<div title="Tooltip">` or `<b-tooltip>` the results are:

1. I see no tabs.
1. This warning shows in the console: `[Vue warn]: Avoid adding reactive properties to a Vue instance or its root $data at runtime - declare it upfront in the data option.`

**Libraries**
- **bootstrap-vue** &mdash; 0.18.0
- **vue** &mdash; Tried both 2.3.3 and 2.4.2

**Comment by tmorehouse** [comment]
As a workaround, to get a title attribute on the content, you can wrap the _content_ of your `<b-tab>` in a div which has the title attribute added.

OR are you looking to get the title attribute on the tab's tab button?

**Comment by epicyclist** [comment]
I didn't consider title accepting HTML; this is working. Thanks!

**Comment by tmorehouse** [comment]
Yep... it accepts static HTML, but not dynamic stuff like components.
