### ISSUE TITLE
Carousel Navigation - Help

### ISSUE THREAD

**Issue by kaankucukx** [bootstrap-vue/bootstrap-vue#743]
Hello ı have been trying to navigate carousel from outside of .carousel-indicatiors.

since in bootstraps code i can make it with defining "data-to-slide" atr. 

https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_carousel&stacked=h
`      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    `

I couldnt make it work for bootstrap-vue. i tried to define all aria labels on extrenal <li aria-*> but no navigation happening.

I have a seperate/secondary navigation on my page apart from carousel but needs to navigate carousel slider too.

This navigation outside of the div of `#carousel` and have to navigate carousel slides as indicators.

I am using bundler, tried vue-webpack-simple and advanced so far for compat. issues bu no help so far.

**Comment by tmorehouse** [comment]
The aria labels are for labelling the controls for sight impaired users that are using a screen reader to describe the page layout and controls.

Currently carousel doesn't provide a `v-model` binding for setting the current slide.

You can get around this and control the next and previous side by setting a `ref="myCarousel"` attribute on `<b-carousel ref="mycarousel">`  nd then calling the `next()` and `previous()` methods on that ref:

```js
// Goto next slide
 this.$refs.myCarousel.next();
// Goto previous slide
 this.$refs.myCarousel.prev();
```

**Comment by kaankucukx** [comment]
@tmorehouse Hello, thank you for ur guidance

Instead of going back and forward i need to slide to exact slide "index(n)". I m digging in to source code but yet i cant find any solution.

To demonstrate what i need,think of a site navigation bar menus, `@click = navigate to index(n) of the slide` would be perfect :) 🥇

**Comment by tmorehouse** [comment]
Try this:

`this.$refs.myCarousel.index = n`

where n is the slide you want to go to.

Note if the carousel is in the middle sliding when you specify the new index, it will not slide to that slide.

**Comment by mosinve** [comment]
is it possible to know current carousel state (i.e. if it in transition state)?

**Comment by tmorehouse** [comment]
There is a private property `.isSliding` which should be treated as read only.

**Comment by mosinve** [comment]
So, one can check it by `this.$refs.myCarousel.isSliding`?

**Comment by tmorehouse** [comment]
Yup.

**Comment by kaankucukx** [comment]
@tmorehouse Thanks for your help, i got what i need at the moment. by this i can compete my app.

Thank you! 🥇
