### ISSUE TITLE
Tabs and table not same height?

### ISSUE THREAD

**Issue by CrixuAMG** [bootstrap-vue/bootstrap-vue#748]
I've place a b-table and b-tabs next to each other, starting at the same height.
However, the bottoms of the table header and tabs aren't at the same.
I was wondering if this choice was made on purpose, and why :)

**Comment by tmorehouse** [comment]
Have you tried this with plain Bootstrap V4 tabs and table?

Bootstrap-Vue uses the standard Bootstrap V4.alpha CSS, so the heights should be the same as defined by Bootstrap V4.alpha CSS

**Comment by tmorehouse** [comment]
Using plain Bootstrap CSS and HTML markup:

![image](https://user-images.githubusercontent.com/2781561/28721431-b3dc3818-7386-11e7-9eb7-bad20fe62035.png)


Tables header is slightly taller than navs (tabs variant)

**Comment by CrixuAMG** [comment]
[Image](http://imgur.com/a/c1YAJ)
This is what I see, I'll just add some css to fix it :)
