### ISSUE TITLE
Table responsive option adds the wrong class to the element

### ISSUE THREAD

**Issue by robinandeer** [bootstrap-vue/bootstrap-vue#749]
When the `responsive` option is set on the `<b-table>` component, it adds a class of `.table-responsive` to the HTML (notice the period `.` in the beginning)

![screen shot 2017-07-28 at 16 24 34](https://user-images.githubusercontent.com/1220232/28721616-44df4e16-73b1-11e7-8b0f-9fe38cbfc40c.png)

Therefore the class doesn't do anything. I will open a small PR if I have time, otherwise I'm sure you will be able to correct it super fast 😉

**Comment by tmorehouse** [comment]
This has already been fixed in the latest master, and will be available when v0.19.0 is released.

**Comment by alexsasharegan** [comment]
P.S. I've had trouble with the usage of `.table-responsive`. It's my understanding that the css works best when applied to a wrapper element on the table itself.

**Comment by tmorehouse** [comment]
In BS3, the `table-responsive` had to be applied to a wrapper element. in BS4 it can be applid directly to the `<table>` element.

There is a slight bug in table-responsive  in BS4: https://github.com/twbs/bootstrap/issues/23124
