### ISSUE TITLE
Nuxt.js & Custom UI Kit Import

### ISSUE THREAD

**Issue by ImTheDeveloper** [bootstrap-vue/bootstrap-vue#751]
Hi,

When trying to use a custom UI Kit with SCSS files I'm noticing that the rendering is causing the original bootstrap.css files to take over, instead of the new kit scss files.

My config with bootstrap-vue in nuxt.config.js is:

```
  modules: [['@nuxtjs/bootstrap-vue', {css: false}], '@nuxtjs/axios'],
  plugins: [{src: '~/plugins/vue2-google-maps.js', ssr: false}],
  css: ['~/assets/now-ui-kit.scss', 'bootstrap/dist/css/bootstrap.css']
}
```

I have set the css: false property and I am importing in the css as part of the build. Any ideas why the render is defaulting back to original bootstrap? I'm not getting any build errors, in fact on reload I do see some of the new ui kit showing up and then disappearing.

**Comment by ImTheDeveloper** [comment]
Actually after further investigation it seems to be how I'm using bootstrap-vue library.

Placing a simple ``` <button class="btn btn-default">Default</button> ``` gives me the correct UI kit button:
![image](https://user-images.githubusercontent.com/1431348/28753302-ac29e534-752a-11e7-8781-362f6ab0f242.png)

Using the button component ```        <b-button size="md">Submit</b-button> ``` renders as:
![image](https://user-images.githubusercontent.com/1431348/28753306-c9304100-752a-11e7-81c0-d1ace232b963.png)


Any way for me to just default the styles for the components in bootstrap-vue to use my UI kit ?

**Comment by mosinve** [comment]
have you tried to remove BS4 stylesheet from nuxt.config?

**Comment by ImTheDeveloper** [comment]
I get some quite crazy outputs when I remove that:

![image](https://user-images.githubusercontent.com/1431348/28753340-e14eefec-752b-11e7-8931-19193d27ba1b.png)

**Comment by mosinve** [comment]
hehe) funny... and can you post `<style> ` part from your resulting html page in case you load BS4 css?

**Comment by mosinve** [comment]
Honestly i haven't used UI styles other than BS4 with BV.... but theoretically all should work well... need to the case needs a debug at least at browser console...

**Comment by ImTheDeveloper** [comment]
https://pastebin.com/bd6zghXw <-- With me removing BS4 (it appears to still be in there though ?!!)

**Comment by tmorehouse** [comment]
When using `b-form-input`, you don't need to add `class="form-control"` as it is automatically added. 

And for grouping an input and a button together you should use the `b-input-group` component.

**Comment by ImTheDeveloper** [comment]
I have got this working now with the following config:

```
 modules: [['@nuxtjs/bootstrap-vue', {css: true}], '@nuxtjs/axios'],
  plugins: [{src: '~/plugins/vue2-google-maps.js', ssr: false}],
  css: [{src: '~/assets/now-ui-kit.scss', lang: 'scss'}]
```

For some reason during build time I sometimes get an error saying:

```
 ERROR  Failed to compile with 1 errors                                                                                                    21:21:10

This dependency was not found:

* bootstrap.css in ./~/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&in
dex=0!./.nuxt/App.vue

To install it, you can run: npm install --save bootstrap.css
Build completed in 5.414s
``
However, this does not happen every time:

```
 ERROR  Failed to compile with 1 errors                                                                                                    21:21:10

This dependency was not found:

* bootstrap.css in ./~/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&in
dex=0!./.nuxt/App.vue

To install it, you can run: npm install --save bootstrap.css
Build completed in 5.414s



 ERROR  Failed to compile with 1 errors                                                                                                    21:21:13

This dependency was not found:

* @/node_modules/bootstrap/dist/css/bootstrap.css in ./~/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./~/vue-loa
der/lib/selector.js?type=script&index=0!./.nuxt/App.vue

To install it, you can run: npm install --save @/node_modules/bootstrap/dist/css/bootstrap.css
Build completed in 8.122s



 DONE  Compiled successfully in 8122ms                                                                                                     21:21:16

> Open http://127.0.0.1:3000

Build completed in 8.186s
```

Between those 3 builds all I've done is change some text on a button. No reason for it to fail 2 times and then run fine.

**Comment by ImTheDeveloper** [comment]
I'm happy to close this off. I think the build issue is a local environment problem as I do not hit the error on my other machine.

For anyone wishing to see the answer to my original question:

1.  Import the relevant SCSS, Font and mixins files into your Nuxt Assets folder
2. Install vue-bootstrap using the nuxt community modules
3. Nuxt config.js should have the following items added:

```
 modules: [['@nuxtjs/bootstrap-vue', { css: true }], '@nuxtjs/axios'],
  css: [{ src: '~/assets/now-ui-kit.scss', lang: 'scss' }]
```
