### ISSUE TITLE
Modal Title Height Not Proper

### ISSUE THREAD

**Issue by hnviradiya9** [bootstrap-vue/bootstrap-vue#753]
Checkout below link. Click on **Launch Demo Modal**. Height of Title is not proper.

https://bootstrap-vue.js.org/docs/components/modal

Below Bootstrap Height seems proper. Click on **Launch Demo Modal**

https://v4-alpha.getbootstrap.com/components/modal/

**Comment by tmorehouse** [comment]
This is due to the docs site CSS overriding some of the regular bootstrap V4.alpha CSS.

You probably won't see this '_issue_ in your own application unless you have also overridden some of the CSS.

**Comment by tmorehouse** [comment]
I have created PR #755 which should fix this issue with the live examples in the documentation site.
