### ISSUE TITLE
inheritAttrs

### ISSUE THREAD

**Issue by outluch** [bootstrap-vue/bootstrap-vue#754]
Want to add class="xxxx" on root of b-tabs. New vue 2.4.2 release notes:
New component option: inheritAttrs. Turns off the default behavior where
parent scope non-prop bindings are automatically inherited on component root
as attributes.

**Comment by alexsasharegan** [comment]
Adding a class to `b-tabs` will add it to that component's root element. `inheritAttrs` is only used to turn off that behavior when wrapping components in other components (HOC pattern) and proxying the attrs/listeners down. 

Give it a try as is, and if you're not getting the results expected, paste in some code so we can see what the desired effect is.

**Comment by outluch** [comment]
```
    <b-tabs class="ttttt">
      <b-tab title="first" active>
        I'm the first fading tab
      </b-tab>
      <b-tab title="second">
        I'm the second tab content
      </b-tab>
      <b-tab title="disabled" disabled>
        <b-card>I'm the card in tab</b-card>
      </b-tab>
    </b-tabs>
```
I expect output html to begin with: `<ul role="tablist" tabindex="0" aria-setsize="3" aria-posinset="1" class="nav nav-tabs ttttt">` 
But get that without class `ttttt`

**Comment by alexsasharegan** [comment]
Okay, I got it now. `<b-tabs>` has a couple wrapping elements, so you're looking for a way to add custom classes to the inner `<ul>`. 

If you need to apply some css, I would recommend using some nested selectors. Given your above component html, the structure would be as follows:

```css
. ttttt > div > ul.nav {}
```

You can review the internal component html here: https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/tabs.vue

**Comment by tmorehouse** [comment]
We'll probably be taking advantage of this new Vue feature in v1.0.0
