### ISSUE TITLE
Dropdown shown and hidden event problem

### ISSUE THREAD

**Issue by men232** [bootstrap-vue/bootstrap-vue#757]
Hi, i have some problem with handling "shown" and "hidden" event.
Please, can you help me, what i do wrong?

https://jsfiddle.net/3bet9ynt/

**Comment by tmorehouse** [comment]
This appears to be a case mis-documentation.  The `shown` and `hidden` events were only being emitted on $root.

I have created a PR to emit hte shown and hidden events

**Comment by men232** [comment]
I see that issue is fixed, thx 👍
