### ISSUE TITLE
Errors in Popover documentation

### ISSUE THREAD

**Issue by SirLamer** [bootstrap-vue/bootstrap-vue#76]
The Popover documentation is exposed within the Readme.md links. It does not render correctly.

https://bootstrap-vue.github.io/docs/components/popover/

I wrote this, but as mentioned at the time I was unable to get Nuxt to run in my development environment so I was unable to test. The whole thing was written blind. Since I can't test I am reluctant to write a PR to correct the errors, however if I could get Nuxt working then I'd be happy to correct this and add to the nav bar in the documentation.

These issues were discussed here: https://github.com/bootstrap-vue/bootstrap-vue/pull/67

Also, while I'm here, and since I know it's nice to see your hard work being put to use, I have published a simple "click confirm" component which depends on Bootstrap Vue and Popover. Thanks!
https://github.com/SirLamer/click-confirm

**Comment by pi0** [comment]
@SirLamer I'm closing this one as it is resolved :)) (Fresh docs will be published soon)
