### ISSUE TITLE
BCarousel infinite loop

### ISSUE THREAD

**Issue by Ruplahlava** [bootstrap-vue/bootstrap-vue#764]
Hello,
one small thing - when i click carousel control arrows quickly, im getting this warning from vue (in development):

> You may have an infinite update loop in watcher with expression "index"
> found in
> 
> ---> \<BCarousel>
>        \<TransitionGroup>
> ...

When you do that in production build, whole tab freezes (chrome,ff)
Tried that in your example carousel in documentation and it did the same thing...

**Comment by tmorehouse** [comment]
Yeah, the `<b-carousel>` component is a bit buggy (hence why we have labeled it as unstable).

I've noticed the same issues in chrome with the tab freezing when controls are clicked in quick succession.

Carousel needs an overhaul for sure.

**Comment by Ruplahlava** [comment]
Thank you for the quick fix! :)

**Comment by tmorehouse** [comment]
Carousel should be quite stable now.  It has one minor bug which prevents it from cycling to the first slide when it reaches that last slide, but that should be fixed shortly (it is available in the new `dev` branch).
