### ISSUE TITLE
How to change <b-tabs> background-color?

### ISSUE THREAD

**Issue by bolt12** [bootstrap-vue/bootstrap-vue#766]
I want to change the background color, deactivate borders and other things of an active tab item but i dont know how to do it

**Comment by tmorehouse** [comment]
Are you referring to the tabs (across the top) or the tabbed content?

For the tabs across the top you can target with custom CSS and place a custom class on `<b-tabs>` component.

**Comment by bolt12** [comment]
I'm talking about the tabbed content i think

As you can see in the image, i want the active tab to be tha same color as the background of the tabbed content!
![Image of Yaktocat](https://i.imgur.com/hzhd6jh.png)

**Comment by tmorehouse** [comment]
The active tab will have the class `active` applied (in which the styling is controlled by the default Bootstrap V4 CSS.

You can place a custom class ie `<b-tabs class="mytabs">` and then target the active tab via custom CSS:

```css
.tabs.mytabs .nav-tabs .nav-link.active {
  background-color: #aabbcc;
}
```

**Comment by bolt12** [comment]
I dont seem to get it working :(

**Comment by mosinve** [comment]
You can create gist example of your html, then it will be easier to help you.

**Comment by tmorehouse** [comment]
Changed are coming to Bootstrap-Vue in the new v1.0.0.beta release.

Closing this issue for now, as there are CSS stylesheet workaround that can be used to target elements based on class names.

Beta docs: https://bootstrap-vue.now.sh/

**Comment by uwejan** [comment]
am Trying change the background color for all my tabs title only, how that can be achieved?
