### ISSUE TITLE
How change css style of a <b-card>

### ISSUE THREAD

**Issue by klaveren** [bootstrap-vue/bootstrap-vue#767]
#I need to customize the header, title, subtitle of a < b-card >, however I am not able to find information on which class the component uses to make the changes. Could someone help me with this information?

Grateful.

**Comment by tmorehouse** [comment]
For the card in general, use the `variant` prop to change the card to on of the standard bootstrap colors (`primary`, `success`, `info`, `outline-warning`, `outline-danger`, `outline-primary`, `outline-success`, `outline-info`, `outline-warning`, `outline-danger`)

When using one of the darker backgrounds set teh `inverse` prop to lighten the text.

You can also apply the variants to the header or footer with `header-variant` and `footer-variant` props respectively.

The header an footer also allow you to add a class (or classes) to them by setting `header-class` and `footer-class` props.  The class can be a string or array of strings.

**Comment by klaveren** [comment]
Dude, it worked perfectly like you said.
Every day that passes my love increases this project. thank you.

**Comment by tmorehouse** [comment]
As an aside, you can create your own variant classes `card-*` (where * is your variant name), and then use that in your `variant` prop (just omit the `card-` portion when referring to the variant)

**Comment by klaveren** [comment]
@tmorehouse 
Sorry to ask, what's wrong with my code? Or maybe I misunderstood.

`<b-card 
class="mb-2"
header-variant="card_header"
footer-variant="card_footer"
 title-variant="card_title"
:header="card.header"
:title="card.itens.title"
:sub-title="card.subheader"
show-footer
>< / b-card >
<style>
.card_title {
    font-size: 1.2em;
    font-shadow: 2px 2px #ccc;
},
.card_header {
    font-shadow: 2px 2px #ccc;
},
.card_footer {
    color: #000;
    font-shadow: 2px 2px #ccc;
},
</style>`

**Comment by tmorehouse** [comment]
Variants will have `card-` prepended to them for the css class name.

So change your css 

```css
.card-card_header: {...}
.card-card_title: {...}
.card-card_footer: {...}
```

**Comment by tmorehouse** [comment]
So try it this way:
```html
<b-card class="mb-2"
        header-variant="card_header"
        footer-variant="card_footer"
        title-variant="card_title"
        :header="card.header"
        :title="card.items.title"
        :sub-title="card.subheader"
        show-footer
></b-card >
<style>
.card-card_title {
    font-size: 1.2em;
    font-shadow: 2px 2px #ccc;
}
.card-card_header {
    font-shadow: 2px 2px #00ff00;
}
.card-card_footer {
    color: #000;
    font-shadow: 2px 2px #FFAAFF;
}
</style>
```

**Comment by klaveren** [comment]
@tmorehouse not work for me. 
the only way is if I pass the value in inside a one html component like div, and set the class of this component. 

like this:
card.title: '<div class="card-title>TITLE</div>"'

I read the documentation and i'm try change all possibilities header-variant and header-class, but don't changed any thing.

**Comment by tmorehouse** [comment]
Did you try the example just above? note that when using the variants, you **must** add the text 'card-' in front of the variant name when defining the CSS class.  When referencing the  custom variant, do not include the `card-` part of the class name.

Also make sure you are using v0.18.0 of BootstrapVue

**Comment by klaveren** [comment]
yes i'm using "bootstrap-vue": "^0.18.0"

please look this:

```
                    <b-card 
                        header-variant="card_header" 
                        footer-class="card_footer" 
                        title-class="card_title" 
                        :header="card.header" 
                        :title="card.titulo" 
                        :sub-title="card.descricao"
                        show-footer
                    >
                        <small slot="footer" class="text-muted">
                            <b-btn @click="" :variant="card.variant" block>{{ card.btn_comprar }}</b-btn>  
                        </small>
                    </b-card>
<style>
.card-card_title {
    font-size: 2em;
    font-weight: 500;
    text-shadow: 2px 2px #333;
},
.card-card_header {
    font-size: 2em;
    font-weight: 500;
    text-shadow: 2px 2px #333;
},
.card-card_footer {
    font-size: 2em;
    font-weight: 500;
    text-shadow: 2px 2px #333;
},
<style>

```

what you think?
thank you.

**Comment by tmorehouse** [comment]
You might need to add `!important` after each CSS value, as it might be a CSS specificity issue.

**Comment by tmorehouse** [comment]
You can also use the `header-class` and `footer`class` to apply a specific class or set of classes (array), to apply classes that do not follow the `.card-` naming convention.

**Comment by tmorehouse** [comment]
Also, check in your browser dev tools/inspector to see if the classes are indeed being applied to your headers/footers

**Comment by tmorehouse** [comment]
Boostrap-Vue V1.0.0.beta will have additional features for controlling b-cards using the new background and border variants (which can be applied to the header and footer sections).

Now new sub component are being introduced as well so you can bui9ld your cards the y way you like as well.

Keep an eye on the new V1.0.0.beta docs site at https://bootstrap-vue.now.sh/ for updated documentation

**Comment by klaveren** [comment]
@tmorehouse 

Maybe we could think of the flexibility to create components with a little more recurrence, could have tags like <b-card-title> </ b-card-title>
<B-card-body> </ b-card-body>
<B-card-footer> </ b-card-footer>
Which would be quite similar to the Vuetify components. JUST OPINION OF A LEARNER =)

**Comment by tmorehouse** [comment]
Check the latest v1.0.0.beta.5 docs.

We have all new sub components for cards: https://bootstrap-vue.js.org/docs/components/card

Note there are a few mistakes in some of the examples which have been corrected in the `dev` branch docs (https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/docs/components/card/README.md) which will be available in v1.0.0.beta.6 release

**Comment by klaveren** [comment]
Dude, this is really incredible. I'm using a little vutify to test, in a few days I'll be back. Thanks for everything.

**Comment by tmorehouse** [comment]
We have been adding modular functional compnents to most complex regular components, to allow for better customization.

Card is one example, and progress is another.

**Comment by VasilijeBursac** [comment]
> Variants will have `card-` prepended to them for the css class name.
> 
> So change your css
> 
> ```css
> .card-card_header: {...}
> .card-card_title: {...}
> .card-card_footer: {...}
> ```
> 
> But leave your variant props as is (no `card-` prepended)

Does this work for `b-tabs card`, too? I have tried it, but it doesn't seem to work...
