### ISSUE TITLE
Tooltip default animation does not match upstream bootstrap

### ISSUE THREAD

**Issue by robcresswell** [bootstrap-vue/bootstrap-vue#771]
Tooltips currently have some kind of fade and slide animation attached to them, which is an invention of bootstrap-vue. It doesn't really make sense or look good having a sliding tooltip when its supposed to be attached to a specific location. I think the library should just implement tooltips as Bootstrap upstream has.

**Comment by tmorehouse** [comment]
Tool tips have know issues in BootstrapVue due to the hide and show mechanisms used to trigger Vue transition blocks.

Bootstrap V4 is currently replacing the tether.js library with popper.js, which will require a complete re-write of the BootsrapVue popovers and tooltips.

**Comment by robcresswell** [comment]
Ah, I'm sorry, I had no idea about that. I'll close this; thanks for taking the time to respond.

**Comment by tmorehouse** [comment]
Yeah, so expect a few major changes in a while.
