### ISSUE TITLE
Build failing with 0.18

### ISSUE THREAD

**Issue by paglias** [bootstrap-vue/bootstrap-vue#775]
Hi, I just upgraded from 0.16 to 0.18 and my webpack build started failing with this error

```
ERROR in ./~/bootstrap-vue/lib/mixins/dropdown.js
Module build failed: SyntaxError: Unexpected token (101:8)

   99 |     },
  100 |     methods: {
> 101 |         ...clickOut.methods,
      |         ^
  102 |         noop() {
  103 |             // Do nothing event handler (used in visible watch)
  104 |         },

 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/bootstrap-vue/lib/components/dropdown.vue 7:16-45
 @ ./~/bootstrap-vue/lib/components/dropdown.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./website/client/components/tasks/user.vue
```
My webpack was already configured to use babel on boostrap-vue code with 
```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          path.join(projectRoot, 'test'),
          path.join(projectRoot, 'website'),
          path.join(projectRoot, 'node_modules', 'bootstrap-vue'),
        ],
        options: {
          cacheDirectory: true,
        },
      },
```

But for some reason the trick isn't working anymore with 0.18. I'm on node 6.9.2

**Comment by mosinve** [comment]
It's an object spread,  to transpile it by babel uoy should use plug-in https://babeljs.io/docs/plugins/transform-object-rest-spread/

**Comment by alexsasharegan** [comment]
I believe the object spread may be a stage-2 plugin. Not sure exactly, but I don't think it is part of the std es2015 babel plugin. Try adding... what @mosinve  said above! 😄

**Comment by paglias** [comment]
Thanks a lot! I checked twice because I was sure to have the `transform-object-rest-spread` plugin and indeed I had it but it was only used for one folder and not for node_modules.
