### ISSUE TITLE
Add sort and / or filter for table

### ISSUE THREAD

**Issue by coffenbacher** [bootstrap-vue/bootstrap-vue#78]
It would be really cool to have sorting and / or filtering for the table component. The pagination is already great. I'm new to Vue but since I'm planning to use many tables in my next project, I'll probably have to figure something out for this!

**Comment by pi0** [comment]
@coffenbacher You can now try out modern tables 😎 (Thanks for your suggestion) [Docs](https://bootstrap-vue.github.io/docs/components/tables/)
