### ISSUE TITLE
Table Documentation Page is broken. 

### ISSUE THREAD

**Issue by kalvenschraut** [bootstrap-vue/bootstrap-vue#784]
Within the past hour or so the table document page is outputting 
"Whoops!
resetDetails is not defined as an error message." 
Link: https://bootstrap-vue.js.org/docs/components/table
ScreenShot 
![bootstrap-vue](https://user-images.githubusercontent.com/30308012/29141889-aa772fce-7d15-11e7-95b2-8bf7232ba46e.png)

**Comment by tmorehouse** [comment]
We're working on it...  should be fixed in a bit.

**Comment by tmorehouse** [comment]
Fix is available in `dev` branch and should be available in the next release.
