### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by czachandrew** [bootstrap-vue/bootstrap-vue#788]
![screen shot 2017-08-09 at 4 49 47 pm](https://user-images.githubusercontent.com/3537992/29145451-d0ab4bbe-7d22-11e7-89c5-26cd66042c28.png)

Getting this error when trying to access the tables section of the Docs...

**Comment by tmorehouse** [comment]
Yep.  Duplicate issue https://github.com/bootstrap-vue/bootstrap-vue/issues/784

Will be fixed shortly.
