### ISSUE TITLE
Tabs broken, not clickable anymore

### ISSUE THREAD

**Issue by Susheng** [bootstrap-vue/bootstrap-vue#789]
Tabs broken, not clickable anymore, including the example in the official site.
It happened a couple of hours ago and it is still broken now.

**Comment by tmorehouse** [comment]
Thanks for reporting this.

Hmm, this might be due to the new implementation of the `b-link` component.

**Comment by tmorehouse** [comment]
I was mistaken, this is not an issue with `b-link`, but another issue related to active tab list.
