### ISSUE TITLE
Why do form components come with class row?

### ISSUE THREAD

**Issue by coffenbacher** [bootstrap-vue/bootstrap-vue#79]
The default class is "form-group row" for components like b-form-input. The negative margin on the "row" throws off my layout - is there a reason it's included? In most bootstrap examples, I don't see people using "row" with the form-group. For now, is there a way to suppress that class?

Thanks!

**Comment by pi0** [comment]
@coffenbacher Sorry for long delay. problem should be fixed now. feel free to reOpen this issue :)
