### ISSUE TITLE
Multiselect form component

### ISSUE THREAD

**Issue by chevoldavis** [bootstrap-vue/bootstrap-vue#793]
I am getting the following error when I select a value:
 <select multiple v-model="localValue"> expects an Array value for its binding, but got Undefined

This appears to be coming from the source as my v-model isn't localValue, can you please help? Thanks

**Comment by mosinve** [comment]
Please, post an example of your code.

**Comment by tmorehouse** [comment]
Could you provide a sample of your code?

**Comment by chevoldavis** [comment]
Sorry, I was using version 0.18 upgrading to 0.19 fixed my issue. Thanks for the fast reply!

**Comment by tmorehouse** [comment]
Note that v0.19 has a few bugs in it with some other components. v0.19.1 should be out soon which will address the issues.

**Comment by chevoldavis** [comment]
Ok cool, thanks for the heads up. I will keep my eye out for v0.19.1, my code isn't in production yet so its all good. I appreciate all the work you have done on this, thanks again!
