### ISSUE TITLE
Form Input Textarea not working

### ISSUE THREAD

**Issue by studnitz** [bootstrap-vue/bootstrap-vue#795]
Currently the textarea prop is not working properly, perhaps https://github.com/bootstrap-vue/bootstrap-vue/commit/cb44652f2e49b6399bd12cb31b1575f94922b666 fixes this? 

[The Form Input document](https://bootstrap-vue.js.org/docs/components/form-input/) shows it well, as no multiline textarea is rendered.

**Comment by alexsasharegan** [comment]
I'm almost certain that commit does fix this issue. Hopefully we will have a patch release out soon. I've personally copied that commit's changes into my production copy of the lib, and recompiled. Not sure if that's a big ask, or if you would prefer to hold on `v0.18.0` until a patch is released.

**Comment by tmorehouse** [comment]
PR #785 definitely fixes this issue.

**Comment by studnitz** [comment]
I just reverted to `v0.18.0` and I'm happy to wait until a patch is released, just wanted to inform in the case that #785 wasn't the fix for that. :)
