### ISSUE TITLE
How to provide options for b-form-select in the HTML

### ISSUE THREAD

**Issue by jeff-h** [bootstrap-vue/bootstrap-vue#796]
I'd like to hardcode the options for a b-form-select field (well actually, have Laravel spit them out into the markup), but can't work out how. I want something like this in my HTML:

```
<b-form-select options="something"></b-form-select>
```

I'm don't need to use Vue to provide the model in this particular form; I just want to use the nice succinct bootstrap-vue markup instead of the verbose raw bootstrap equivalent.

What should go in place of `something` above? I've tried hardcoding a Javascript array and object, and neither work:

```
<b-form-select options="{ a: 'one', b: 'two' }"></b-form-select>
<b-form-select options="[ {a: 'one'}, {b: 'two'} ]"></b-form-select>
```

I'm assuming it can't be hardcoded, and needs to be passed as a data or computed property from a parent Vue instance. Since I don't have one, I can't work out how to provide a javascript object for the options eg

```
<b-form-select :options="myVariableContainingAnObject"></b-form-select>
```

Can someone help me?

**Comment by tmorehouse** [comment]
JavaScript array objects will work, just make sure you are v-binding them with  a `:` (other wise they are treated as a string literal, not a JavaScript array or object):

```html
<b-form-select :options="[ 'one', 'two']"></b-form-select>
<b-form-select :options="[ {a: 'one'}, {b: 'two'} ]"></b-form-select>
<b-form-select :options="{ a: 'one', b: 'two' }"></b-form-select>
```

**Comment by jeff-h** [comment]
Man, so close! :) Thanks for your help.
