### ISSUE TITLE
several components on the page

### ISSUE THREAD

**Issue by wormen** [bootstrap-vue/bootstrap-vue#80]
tell me what is wrong
not rendered components

registration takes place so
```js
import 'bootstrap/dist/css/bootstrap.min.css'
import BootstrapVue from "bootstrap-vue"
Vue.use(BootstrapVue)
```

connect components
```js
import {bNav, bBtn, bNavbar, bNavItem, bForm} from "bootstrap-vue"

    export default {
        components: {
            bNav,
            bBtn,
            bForm,
            bNavbar,
            bNavItem
        }
    }
```

and I get

![23-01-2017 23-28-17](https://cloud.githubusercontent.com/assets/8462339/22207764/c151b61c-e1c3-11e6-978f-c57ed192168c.jpg)

**Comment by SirLamer** [comment]
The info here is incomplete, my guess is the issue is external to what we can see from your examples.
