### ISSUE TITLE
b-nav-item-dropdown: Unexpected behavior on click events

### ISSUE THREAD

**Issue by sigmoidbigfoot** [bootstrap-vue/bootstrap-vue#807]
Clicking outside of an open nav-item-dropdown causes the selected item to be highlighted in blue:

![dropdown gif](http://i.imgur.com/gYi14Ax.gif).

Clicking on a different item causes selected item to be highlighted in blue as well:

![dropdown gif 2](http://i.imgur.com/Wi1dkd6.gif)

**Comment by tmorehouse** [comment]
Which version of Bootstrap-Vue are you using? are you also using router links in the dropdown or just regular links?

**Comment by sigmoidbigfoot** [comment]
Sorry, this is version 0.20.1, and these are router links (b-dropdown-item elements with the to='' property).

**Comment by tmorehouse** [comment]
So the blue highlight should be the 'active-class' applied by vue-router.

This might be a conflict with the active (focused/highlighted) item and vue-router's active-class (which defaults to `active`)

**Comment by tmorehouse** [comment]
There is a PR in the `1.x` branch that may address this issue (PR #823 )

I'll see if I can rebase an also apply to the `dev` branch

**Comment by tmorehouse** [comment]
PR #825 may address this issue in the `dev` branch

**Comment by tmorehouse** [comment]
Try the latest releases

**Comment by sigmoidbigfoot** [comment]
The issue appears to be resolved for me with  0.22.1.

**Comment by tmorehouse** [comment]
Good to hear.
