### ISSUE TITLE
Bootstrap 4-beta: Navbar displays wrong

### ISSUE THREAD

**Issue by hydraheim** [bootstrap-vue/bootstrap-vue#812]
Bootstrap 4 has hit beta. It seems several components in Bootstrap Vue are affected. For example, the Navbar.

Bootstrap 4-beta:
JSFiddle: https://jsfiddle.net/o9b17p2d/1/
![bilde](https://user-images.githubusercontent.com/29726093/29205666-9fd0ca48-7e7e-11e7-986a-7f12a350ac86.png)

Compared to how it looks on alpha-6:
JSFiddle: https://jsfiddle.net/jxo2yhvw/1/
![bilde](https://user-images.githubusercontent.com/29726093/29205640-79319d9a-7e7e-11e7-8682-111c08ac7a83.png)

**Comment by tmorehouse** [comment]
We are actively working on a new version that will be supporting the numerous changes to the V4.beta CSS.

**Comment by tmorehouse** [comment]
For the current release of Bootstrap-Vue, ((v0.20.1) you need to use the V4.alpha.6 CSS as shown in hte getting started / setup sections of the documentation.

V4.beta CSS is definitely a breaking change

**Comment by tmorehouse** [comment]
@hydraheim you can check Bootstrap-Vue v1.0.0.beta docs at https://bootstrap-vue.now.sh/docs/components/navbar
