### ISSUE TITLE
Weird Close buttons on modals

### ISSUE THREAD

**Issue by meldsza** [bootstrap-vue/bootstrap-vue#818]
![Modal](https://user-images.githubusercontent.com/16931090/29241759-4bf67cfe-7f9d-11e7-8bd0-08e0f97a07bf.PNG)

```html
<b-modal id="launch-game" title="Select Soldier" @ok="alert('Launched')" ok-title="Launch Game">
          <form @submit.stop.prevent="submit">
            <select>
              <option>Melroy</option>
	   </select>
          </form>
        </b-modal>
```
The modal's close button looks wierd `Ã—`
I am using the latest bootstrap-vue via the unpkg cdn

Browser: Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**Comment by tmorehouse** [comment]
The close button uses the HTML entity `&times;` to render the `X`.

This looks like the font the you may be using on your page is missing that character,  or your page might not be using `charset=utf-8`

**Comment by tmorehouse** [comment]
Does your HTML have `<meta charset="utf-8">` in the `<head>` section?

**Comment by meldsza** [comment]
I guess not
