### ISSUE TITLE
Toggled shows (from true->false or false->true) in Alerts are not working

### ISSUE THREAD

**Issue by DutchNeon** [bootstrap-vue/bootstrap-vue#82]
When toggling an alert with a boolean from false to true, alerts are not triggered to show. This does work fine when though when they are set at the start. Just not when switched.

This applies to the Bootstrap-vue docs example too!

Sidenote: Probably not Bootstrap-vue related but the newest versions break my Axios usage too. Guessing it's due the Vue version that comes with the latest Bootstrap-vue versions.

**Comment by pi0** [comment]
@DutchNeon  Thanks. Strange problem seems was from `fade in` class in BS Alpha6 which hides alerts! It should now be resolved :)
