### ISSUE TITLE
Textarea does not display the prefilled model

### ISSUE THREAD

**Issue by Hoogkamer** [bootstrap-vue/bootstrap-vue#833]
The content of the model is not added to textarea.

Example:
https://bootstrap-vue.js.org/docs/components/form-input
prefill the text3, then still in the textarea nothing is visible.

**Comment by mosinve** [comment]
hi thanx for report. It seems that it's Vue bug. We will workaround this soon.

**Comment by pi0** [comment]
vuejs/vue#6361
