### ISSUE TITLE
demo data for components

### ISSUE THREAD

**Issue by wormen** [bootstrap-vue/bootstrap-vue#84]
could add to the documentation demo data?
example, how they should look like for the components:
- bTable
- bFormSelect
etc

It is not clear how to use some components

**Comment by pi0** [comment]
@wormen This issue is a little old now and we have more complete demos for this components. (users can use view page source button). Closing but feel free re-open this issue later.

**Comment by wormen** [comment]
@pi0 nothing has changed in the document and there is no demo data
described only component of the fields
