### ISSUE TITLE
How to disable local sorting?

### ISSUE THREAD

**Issue by akaNightmare** [bootstrap-vue/bootstrap-vue#841]
Hello, 

I need only sort label and sort direction, but no local sorting. Is it possible to do that?

Thanks.

**Comment by tmorehouse** [comment]
Use a provider function for your items (which could just return an array of items), and then by default provider-sorting will be enabled.

You can also provide a dummy function reference to the sort routine which just always returns `0` which will have  similar effect.

**Comment by akaNightmare** [comment]
@tmorehouse could you please provide some example?

**Comment by tmorehouse** [comment]
```html
<b-table :sort-compare="()=> 0"></b-table>
```
Thw above function `() => 0` returns 0. Could also be written as `function(){ return 0;}`

**Comment by akaNightmare** [comment]
@tmorehouse thank you.
