### ISSUE TITLE
<b-table> doesn't call items provider function

### ISSUE THREAD

**Issue by acelot** [bootstrap-vue/bootstrap-vue#852]
I'v tried this feature on both versions (0.20.2 and 1.0.0-beta.3).

`SomeComponent.vue`
```
<template>
  <b-table :items="itemsProvider" ...>
    ... omitted ...
  </b-table>
</template>

<script>
 export default {
    data () {
      return {
        fields: {
          ...
        }
      }
    },
    methods: {
      itemsProvider (context) {
        console.log(context)
      }
    }
  }
</script>
```

When I open a page there is nothing appears in the console.

**Comment by acelot** [comment]
Finally! I solved my issue! Items provider doesn't work when `busy` prop is true.
Example:
https://www.webpackbin.com/bins/-Kri7aMutvIsZPXS0TCz

Try set `isBusy` to `true` in data.

**Comment by tmorehouse** [comment]
That is true.  busy should only be set once your provider *starts* running, and cleared when your provider finishes and returns (either a promise, callback or provides the items table).

b-table looks at busy and prevents certain things from happening (like calling provider update a second time while one is currently running, preventing click events from propagating, etc.)

**Comment by acelot** [comment]
@tmorehouse Maybe it should be reflected in the documentation?

**Comment by tmorehouse** [comment]
True, we will have the documentation updated.

The examples show it after the provider has started running.

We are working on a PR that will auto set/clear busy when a provider function is provided.

**Comment by johanbaaij** [comment]
@tmorehouse couldn't find anything else about this, but is it correct that the provider gets called twice?
You can see it in the webpackbin that @acelot posted: https://www.webpackbin.com/bins/-Kri7aMutvIsZPXS0TCz

The second time I can see a localSortBy in the callstack.

**Comment by tmorehouse** [comment]
Since the results of the items sent by the provider are not cached (since b-table has no clue if the source data has changed), it gets called any time b-table needs to retrieve information about the data from the provider.

**Comment by gleyendeker** [comment]
Hello @tmorehouse , I'm having the same "call twice" issue. Whe I reload the page, the items provider is called 2 times.  Then when I paginate, or chenge the sort column or sort order it is called just once. Is that ok? Regards

**Comment by tmorehouse** [comment]
It can happen, depending on what is going on inside of b-table at the time.

The provider function will be called on `mount()`, and may get called again depending on if any of the props have changed, or internal data may have changed.

There is currently a new PR that is optimizing a few things in b-table (to improve performance in most cases, and a few bug-like issues).  The new tweaks should only trigger provider updates when necessary.
