### ISSUE TITLE
Card Component is not looks well 

### ISSUE THREAD

**Issue by wangzexi** [bootstrap-vue/bootstrap-vue#853]
I've tried Card with variant property in Playground, that's ok.
But in Vue new project, variant property is useless:

![wx20170815-190825](https://user-images.githubusercontent.com/13242100/29313559-4695bec6-81ed-11e7-9ffb-d5b3020a8392.png)

```html
<template>
  <div class="container">
    <b-card variant="primary" class="mb-3 text-center">
      <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </b-card>

    <b-card variant="outline-primary" class="mb-3 text-center">
      <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </b-card>

    <b-card inverse title="Card Title" style="background-color:#333; border-color:#333;">
      <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
      <b-button href="#" variant="primary">Go somewhere</b-button>
    </b-card>

    <b-alert show>
        Default Alert
    </b-alert>

    <b-alert variant="success" show>
        Success Alert
    </b-alert>
  </div>
</template>
```

**Comment by mosinve** [comment]
What version of BS4 do you use? Try to update it up to beta release

**Comment by tmorehouse** [comment]
The v0.22 release of BootstrapVue requires Bootstrap V4.0.0.alpha.6 CSS, while BootsrapVue V1.0.0.beta requires Boostrap V4.0.0.beta CSS.  there are many breaking changes to Bootstrap's CSS between their alpha and beta versions.

**Comment by tmorehouse** [comment]
BootstrapVue v1.0.0.beta is still in development, as w address many of the breaking changes.

Monitor issue #747 as we address the changes, and also check out he v1.0.0.beta docs at https://bootstrap-vue.now.sh/

**Comment by wangzexi** [comment]
I just follow [Quick start](https://bootstrap-vue.js.org/docs/setup)

`npm i --save bootstrap-vue`

```javascript
// main.js
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
import BootstrapVue from 'bootstrap-vue'
```

There is something to notice:
In `node_modules/bootstrap-vue/package.json`:
```json
"dependencies": {
    "bootstrap": "^4.0.0-alpha.6",
```
but in `node_modules/bootstrap/package.json`:
```json
"version": "4.0.0-beta"
```
It looks like the dependency of BootstrapVue is not at right version.
I guess the caret(`^4.0.0-alpha.6`) cause the problem.

By the way, all my old project looks broken, after reinstall packages (not upgrade, just delete `node_modules` folder and perform `npm i`)

**Comment by tmorehouse** [comment]
PR #856 addresses the dependency issue

**Comment by wangzexi** [comment]
Thanks a lot! 🎉

**Comment by tmorehouse** [comment]
For now, until the `dev` branch is published into `master`, you will need to manually edit the dependency.

Not that V1.0.0.beta of BootstrapVue has many breaking changes (and features) to address Boostrap V4.0.0.beta
