### ISSUE TITLE
After upgrade, styles totally broken

### ISSUE THREAD

**Issue by aleksandrmelnyk** [bootstrap-vue/bootstrap-vue#854]
Hi There,

I integrated bs styles as described here https://github.com/bootstrap-vue/bootstrap-vue/issues/690.
But today after upgrade (0.20 and bs4-beta) styles looks broken. For example there is no $brand-primary variable.
Any ideas what could it be? This is how bs4 changed?

thanks.

**Comment by mosinve** [comment]
You shouldn't use BS4-beta with BV 0.20... I'd suggest either BS4-alpha with BV 0.20, or BS4-beta with BV 0.22

**Comment by aleksandrmelnyk** [comment]
Yep, thanks. But styles still looks clunky even with latest bv. That's perhaps new bootstrap changes (

**Comment by aleksandrmelnyk** [comment]
OK, sorry, my fault. Styles broken because bs4 beta changed some classes, eg card-block now card-body, bg-faded now bg-light etc.
