### ISSUE TITLE
[b-form-input] Restrictive type setting

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#858]
Value type is set to `String`, where Vue let's you use other primitives reliably (stringifies in the dom only).

![image](https://user-images.githubusercontent.com/16269252/29326009-b77f4624-819e-11e7-9749-8019f79b074e.png)
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/form-input.vue#L122-L125

**Comment by tmorehouse** [comment]
So probably need to allow [String, Number, Date]

**Comment by tmorehouse** [comment]
Will need to update this in both `dev` and `1.x` branches.
