### ISSUE TITLE
pagination is not properly restored after clearing a table filter

### ISSUE THREAD

**Issue by zunayed** [bootstrap-vue/bootstrap-vue#859]
https://bootstrap-vue.js.org/docs/components/table/

steps to reproduce

1. search for a term that reduces the number of items in the table so only one pagination page is clickable
2. delete search term from filter box

the pagination originally had 3 pages but after the filter stays at 1

**Comment by tmorehouse** [comment]
This is now fixed in the `dev` and `1.x` branches, and should be available soon.

**Comment by tmorehouse** [comment]
Now available in both latest releases.
