### ISSUE TITLE
Neither the docs or the README state to include bootstrap CSS

### ISSUE THREAD

**Issue by OmgImAlexis** [bootstrap-vue/bootstrap-vue#86]
The README use to state that the CSS was needed for this to work but it looks like it was taken out at some stage. The docs are also missing anything about CSS on the getting started page.

**Comment by pi0** [comment]
Hello @OmgImAlexis Problem was that new BS had broken alert component. it is now visible again in Getting started page :)

**Comment by OmgImAlexis** [comment]
Fixed but the grammar may need fixing.
> With both methods, you have to add bootstrap stylesheets to everything working fine!

**Comment by pi0** [comment]
@OmgImAlexis Oh, but i didn't get the grammar problem. It should be better if you open a PR fixing that typo :) Thanks

**Comment by OmgImAlexis** [comment]
Replace it with this. The second half of the quote I posted doesn't make any sense at all.

"With both methods, you will still need to include Bootstrap's CSS."

**Comment by pi0** [comment]
@OmgImAlexis Thanks for your help :)
