### ISSUE TITLE
[b-tabs] setting first tab to active not working

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#868]
Probably a regression from #687

If you set the first tab explicitly as active, the tab is _not_ shown on load although the correct index is set. See https://jsfiddle.net/25jwyoqu/1/

**Comment by tmorehouse** [comment]
Have you been abl;e to confirm if this is till the case in v1.0.0.beta as well?

**Comment by tmorehouse** [comment]
Just played with your fiddle.. and can see that it does have issue, but only with first tab.

**Comment by pimlie** [comment]
Unfortunately I have not found the time yet to test v1.0.0-beta. 

Actually I took the fiddle from issue #687 and only moved the active property from the second to the first tab .

The workaround for now is to just not set the first tab as active, as it is the first tab it is active by default and then it works!

**Comment by tmorehouse** [comment]
The code for both c0.22.x and v1.0.0.beta.3 should be almost identical.

I'll take a look at this later today.

**Comment by pimlie** [comment]
@tmorehouse  Thanks, i noticed that removing all active properties as workaround messes up server side rendering as no tab content is generated on ssr at all. That missing content is quite an issue for search engines..

**Comment by tmorehouse** [comment]
Content should be rendered based on the 'lazy' prop not being set (and just hidden)

**Comment by tmorehouse** [comment]
This is fixed now in V1.0.0.beta.5 https://bootstrap-vue.js.org/docs/components/tabs
