### ISSUE TITLE
[b-alert] Setting a timeout shouldn't hide dismiss on alerts

### ISSUE THREAD

**Issue by robcresswell** [bootstrap-vue/bootstrap-vue#869]
It's a pretty common design to have alerts that automatically dismiss after a short period (say 5 seconds) but allow users to dismiss them earlier when read. Implicitly hiding that behaviour makes it impossible to do this.

**Comment by tmorehouse** [comment]
There currently is a weird bug that sometimes occurs that prevents the alert from being re-opened when the dismiss button is present (see issue #718). So the current workaround is the hide the button to prevent the issue.

Once we figure out the root cause, we will bring the button back.

**Comment by robcresswell** [comment]
Ahh, glad to hear it. Would you prefer I closed this, or leave it open as reference?

**Comment by tmorehouse** [comment]
Leave it open, as we have the other issue closed for now.

**Comment by tmorehouse** [comment]
PR's #897 (0.x dev branch) and #898 (1.x branch) should address this (and the original "bug")

**Comment by tmorehouse** [comment]
fixed
