### ISSUE TITLE
It would be useful to have a named slot for the close icon on alerts

### ISSUE THREAD

**Issue by robcresswell** [bootstrap-vue/bootstrap-vue#870]
Many UIs have their own icon sets, which may well include a "cross" or "remove" icon; it would be useful to have a named slot wrap the alerts clode icon, so it could be replaced.

https://github.com/bootstrap-vue/bootstrap-vue/blob/293a232663d3802012e244ae825c01b69d9815d5/lib/components/alert.vue#L15

**Comment by tmorehouse** [comment]
This will be available in the next beta release of BootstrpVue 1.x (PR #898)

**Comment by robcresswell** [comment]
Awesome. Thanks for addressing these issues so fast!

**Comment by tmorehouse** [comment]
Available now in 1.0.0.beta.6
