### ISSUE TITLE
Using Vue.Draggable with a bootstrap-vue table

### ISSUE THREAD

**Issue by rymate1234** [bootstrap-vue/bootstrap-vue#873]
Hi, 

I'm currently using the bootstrap-vue table element, and want to use the [Vue.Draggable](https://github.com/SortableJS/Vue.Draggable) library to add drag and drop item moving and reordering.

However, it appears that you need to use a standard vue v-for loop to use the library, which is as far as I can tell abstracted away in order for filtering and pagination to work

Is there a way to do this without manually constructing a table and losing the filtering and pagination?

**Comment by tmorehouse** [comment]
I Don't think there is a way to directly add that library with `b-table`.  You could roll your own b-table, or take the current b-table code and make a new component that has the dragable features.

**Comment by boriskogan81** [comment]
+1

**Comment by SebastienDenooz** [comment]
+1

**Comment by tmorehouse** [comment]
the latest `dev` branch now allows you to specify a primary column key that uniquely identify a table row.  The primary-key column must be unique across all of your data in the items array.  This value (string or number) will be used as the `:key` value on the rendered `<tr>`.  A transition object can be passed to b-table now, for defining list-transitions on the `<tbody>`  (the `<tbody>` becomes the root element of the transition group.

**Comment by Checkerbeule** [comment]
Hey people. I also have a problem with vue.draggable and b-table. I can't make my code work.
Here ist a code snippet:

<draggable v-model="listA" draggable=".tr">
  <b-table hover :items="listA" primary-key="id" tbody-transition-props="transProps"></b-table     </draggable>

what is the problem here?
Im looking forward for your help!

**Comment by tmorehouse** [comment]
@Checkerbeule Vue-Dragable expects the transition element to be a direct child of the draggable component.

Try using <b-table-simple>, which allows you to structure the table directly.

**Comment by Checkerbeule** [comment]
@tmorehouse thanks a lot!
It ist working with `<b-table-simple>` .

**Comment by Tywele** [comment]
@Checkerbeule Could you post a fiddle of your solution with `<b-table-simple>`? I'm having some trouble wrapping my head around it.

**Comment by euoia** [comment]
In case anyone else comes across this thread, I made a codepen showing `b-table-simple` working with `Vue.draggable`.
https://codepen.io/picklebone/project/editor/ZnGkaa#
