### ISSUE TITLE
how can contribute developing bootstrap-vue

### ISSUE THREAD

**Issue by oukrims** [bootstrap-vue/bootstrap-vue#874]
I'm an experienced vue developer and want to help developing bootstrap-vue

**Comment by tmorehouse** [comment]
Join our slack community, and also create issues and open pull requests via GitHub

**Comment by oukrims** [comment]
where can I get slack invite

**Comment by tmorehouse** [comment]
Slack community link can be found at https://github.com/bootstrap-vue/bootstrap-vue (in the README.md)

**Comment by oukrims** [comment]
I need invitation

**Comment by mosinve** [comment]
Check your email, please

**Comment by oukrims** [comment]
well received thanks
