### ISSUE TITLE
images on carousel get squeezed (distorted)

### ISSUE THREAD

**Issue by pedroskakum** [bootstrap-vue/bootstrap-vue#876]
Hi, I'm implementing a carousel, on my fullHD monitor, the images were perfect, but if I change the size of the screen, or go to my notebook, the images are distorted, apparently what happens is that the width decreases And the height remains unchanged, I'm wondering if this should be the standard behavior, if someone has a fix for it, I'm using this component because I just think the idea is to write less code, thank you right away.

**Comment by tmorehouse** [comment]
If you have images in your carousel that are all the same dimension (on all slides), then do not use the `height` prop on the `carousel-slide` and `carousel` components.

Carousel images are responsive.  (using the `img-fluid` class).  Setting a height will explicitly override the `height: auto;` CSS (while width is still `width:100%`.  This is what causes the distortion.

**Comment by pedroskakum** [comment]
thanks a lot for help :1st_place_medal: 

how i do fix?

i dont use anything of height and width, i have a default component

i also have try width and height auto in carousel and carousel slide but not work

**Comment by tmorehouse** [comment]
Could you provide a bit of sample code, and also which version of BootstrapVue are you using?

**Comment by pedroskakum** [comment]
sure

http://imgur.com/a/yVVIx

composer.json
```
    "@websanova/vue-auth": "^2.16.1-beta",
    "axios": "^0.16.2",
    "bootstrap": "4.0.0-alpha.6",
    "bootstrap-vue": "^0.22.0",
    "vue": "^2.3.3",
    "vue-axios": "^2.0.2",
    "vue-router": "^2.6.0"
```

my carousel:
```
    <!-- Carrossel -->
    <b-carousel id="carousel1" controls indicators background="#ababab" :interval="4000" v-model="slide" @slide="onSlide" @slid="onSlid">
      <b-carousel-slide class="carousel-slide" img="/static/banners/01.png"></b-carousel-slide>
      <b-carousel-slide class="carousel-slide" img="/static/banners/02.png"></b-carousel-slide>
      <b-carousel-slide class="carousel-slide" img="/static/banners/03.png"></b-carousel-slide>
    </b-carousel>
```

my script:
```
<script>
export default {
  data () {
    return {
      slide: 0,
      sliding: null
    }
  },
  methods: {
    onSlide (slide) {
      this.sliding = true
    },
    onSlid (slide) {
      this.sliding = false
    }
  }
}
</script>
```

**Comment by tmorehouse** [comment]
It looks like your carousel is being sized to be 100% x 100% of the viewport, based on your screen shot.

Playing with carousel in the docs and jsfiddle (and resizing the browser, and changing screen orientation in a mobile browser) , I am unable to reproduce your issue.
