### ISSUE TITLE
Parsing error in dropdown.js mixin

### ISSUE THREAD

**Issue by robcresswell** [bootstrap-vue/bootstrap-vue#884]
Hey, I've got a parsing error that I think is due to the spread operator at https://github.com/bootstrap-vue/bootstrap-vue/blob/d3e8eac87306153581681a17ce274a794059b30b/lib/mixins/dropdown.js#L110

Do I need some babel preset to work around this?

**Comment by mosinve** [comment]
Hi! Yes you do. Check issue #775

**Comment by robcresswell** [comment]
Awesome. Is this documented? I'm sure I've just missed it, but if not it really should be, if only to save you guys having to keep closing an identical issue :)

**Comment by mosinve** [comment]
hey, it's just es6 related well-known thing... maybe we should add an "es6 and JS proposals for dummies" book to docs too? ;)

**Comment by robcresswell** [comment]
I don't think there's any harm in adding a note that says "we use spread operators in this component that require transpiling". It's only "well-known" to a small subset of developers who are actively investigating non-standard future JS.

**Comment by alexsasharegan** [comment]
The library bundler (rollup with bublé) _should_ be transpiling all this to `Object.assign`. Are you plucking components individually? I think the distinction is that plucking components from the lib requires adding it to your build process

**Comment by robcresswell** [comment]
Yup, I've been using them individually. It's a great library, I just don't have any need to import everything. All I'm suggesting is a small note so that others in my position don't also open issues to figure it out.

**Comment by alexsasharegan** [comment]
Yeah, I want to make some time to write medium post around this workflow. Especially with webpack, there are a few gotchas to getting the setup right.

**Comment by tmorehouse** [comment]
I've changed how the clickout methods are imported into dropdown.js.  Next release will have this addressed.
