### ISSUE TITLE
Dropdowns doesn't work

### ISSUE THREAD

**Issue by TFLingbo** [bootstrap-vue/bootstrap-vue#90]
https://bootstrap-vue.github.io/docs/components/dropdowns

Dropdown menu doesn't toggle in the example.

**Comment by pi0** [comment]
@TFLingbo Actually it was on my plan fixing that as it was broken after new BS version...  :) So keeping this ticket open until fix

**Comment by javiercbk** [comment]
I might be submiting a PR for this issue today.

**Comment by javiercbk** [comment]
Submitted [PR](https://github.com/bootstrap-vue/bootstrap-vue/pull/94)
