### ISSUE TITLE
[b-tab] force tab content of non active tab to be renderer on ssr

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#904]
I am using bootstrap-vue in combination with nuxt for server side rendering. On my page I have two tabs, both include important `http://schema.org/` data tags which should be included on server side rendering so search engines will see that information. Currently the first tab is set as active and only the content for this tab is rendered during ssr (well, not really true due to  #868)

If I set both tabs to `active` the html for both tabs is rendered actually, but in my browser no tab content is shown (and the second/last tab is selected, but without tab content showing). Is there a way I can force the second tab-content to be included in ssr while only one tab is really active?

**Comment by wanxe** [comment]
Try to overwrite with:
```
.fade.active {
   opacity: 1;
}
```
Bootstrap 4 by default sets .fade with opacity: 0

**Comment by tmorehouse** [comment]
The latest fixes in the 1.x branch should address this issue and render the tabs (if the lazy prop is not set), but only one tab should have active set (the others should have display:none)

**Comment by tmorehouse** [comment]
This is now available in both the alpha and beta releases of Bootstrap Vue
