### ISSUE TITLE
b-tabs active property hiding content

### ISSUE THREAD

**Issue by nc-csl** [bootstrap-vue/bootstrap-vue#911]
Hi. 
When I use the b-tabs component and add the "active" property, the content of the tab is not displayed. When removing the active property, content is shown again.

**Comment by mosinve** [comment]
Please provide an example or description of steps to reproduce this issue

**Comment by mosinve** [comment]
You can change active state of tabs by pass index to v-model

**Comment by tmorehouse** [comment]
Is this also happening in V1.0.0.beta.5?

**Comment by mosinve** [comment]
Yep, quick fix is to set show: true at declaration

**Comment by mosinve** [comment]
This fixed in both alpha & beta branches. Will be avalable in next releases.

**Comment by tmorehouse** [comment]
Should now fixed in v1.0.0.beta.6 release.

**Comment by nc-csl** [comment]
Thank you for confirming the bug and for a solution!
