### ISSUE TITLE
Autodismissing alert is broken

### ISSUE THREAD

**Issue by dmolineus** [bootstrap-vue/bootstrap-vue#915]
Autodismissing the alert doesn't work anymore. I thinks it's broken since https://github.com/bootstrap-vue/bootstrap-vue/commit/eccd63e81f77387f8e570f4a6fd723c7aff9ce44#diff-ed90d1c53663119dade8e7e1cddcd3d8R111 where `this.dismiss` is called instead of `this.dismiss()`

**Comment by mosinve** [comment]
Thanks for reporting. Fixed in dev branch.

**Comment by tmorehouse** [comment]
This is now fixed in latest v1.0.0.beta.6
