### ISSUE TITLE
How to place an icon next to tab title

### ISSUE THREAD

**Issue by wstam88** [bootstrap-vue/bootstrap-vue#917]
I would like to know if there's a way to place an icon next to the tab titles? Cant seem to find any documentation about it.

I tried using headHtml but that doesn't make my tab titles reactive to click events.

Thanks in advance

**Comment by mosinve** [comment]
you just can do like this
```
<b-tab title='first <i class="fa fa-user"></i>' active>
    I'm the first fading tab
  </b-tab>
```

**Comment by wstam88** [comment]
Thanks @mosinve !! Didn't crossed my mind to try it that way :)

**Comment by holoverse** [comment]
This doesnt work anymore.  Is there another way to do it now??

**Comment by markko1-pro** [comment]
Yep, please see this: 
https://bootstrap-vue.js.org/docs/components/tabs/#add-custom-content-to-tab-title

**Comment by soichih** [comment]
I've tried `<template slot="title">` but it didn't work. Neither did head-html. 

Did anyone get this to work?

**Comment by emanuelmutschlechner** [comment]
@deansteen @soichih slots work fine. check my example down below

https://codesandbox.io/s/6z0o4jw73k

**Comment by soichih** [comment]
I've upgraded to rc9 and now it works! Thanks!

**Comment by tuansong** [comment]
Hi @soichih,
what is the rc9? and how do I update it ( Sorry I'm new with vue js )

**Comment by emanuelmutschlechner** [comment]
@tuansong rc9 is a release candidate from five months ago. The exact version is `2.0.0-rc.7`

Check the [version overview](https://www.npmjs.com/package/bootstrap-vue)

You're fine if you have `latest` as version in your `package.json`
