### ISSUE TITLE
[form-textarea] initial content not being set from v-model

### ISSUE THREAD

**Issue by AdrianBathurst** [bootstrap-vue/bootstrap-vue#918]
b-form-textarea is not pre-populating the textarea with the v-model data.

```
<b-form-group label="Biography">
    <b-form-textarea v-model="Bio.Content" rows="5"></b-form-textarea>
    Bio.Content: {{Bio.Content}}
</b-form-group>
```
On load, the textarea is empty, but the line `Bio.Content: {{Bio.Content}}` is populated. Edit the textarea, and the v-model updates ok.

**Comment by tmorehouse** [comment]
Which version of BS-Vue are you using?  V1.0.0.beta.5 appears to be working if you place an initial value in the v-model: https://bootstrap-vue.js.org/docs/components/form-textarea

**Comment by AdrianBathurst** [comment]
I'm pulling from `//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js`, so is v1.0.0.beta.5.

I have a number of input fields on a form, all fields pre-populate with data from the v-model except textareas.

Before this new version, I was using `<b-form-input textarea ...` which did pre-populate the area from v-model.

**Comment by AdrianBathurst** [comment]
I've just tested adding the `Bio.Content` v-model to a `b-form-input` and it does pre-populate that field. `b-form-textarea` next to it does not.

**Comment by tmorehouse** [comment]
Found the issued, and fixed with commit https://github.com/bootstrap-vue/bootstrap-vue/commit/aeb11be9e26903263f95d5c28948561f5e7753a8, and should be available in the next release v1.0.0.beta.6

**Comment by tmorehouse** [comment]
This should be fixed in v1.0.0.beta.6

**Comment by tcitworld** [comment]
I'm having the issue again with v1.1.0.

**Comment by tmorehouse** [comment]
@tcitworld could you open a new issue?

**Comment by catDaisuke** [comment]
I also had problem.
when I re:install bootstrap-vue ,I solved this problem. Thank u
