### ISSUE TITLE
Nav dropdown is broken?

### ISSUE THREAD

**Issue by CrixuAMG** [bootstrap-vue/bootstrap-vue#919]
It doesn't open anymore (didn't change it after updating to v0.23.0) and getting this error in the console:

```
vendor-vue.js:3816 [Vue warn]: Invalid handler for event "click": got undefined

found in

---> <BDropdownItem>
       <BNavItemDropdown>
         <BNav>
```

**Comment by tmorehouse** [comment]
This appears to be working in the documentation sites.  What is your markup look like?

**Comment by CrixuAMG** [comment]
Here's the template:
```
                    <div class="col-md-6 col-lg-9">
                        <div class="float-right">
                            <b-nav>
                                <b-nav-item-dropdown :right-alignment="true">
                                    <!-- Using text slot -->
                                    <template slot="text">
                                        <span class="user">
                                            <span class="image profile-image small img-circle">
                                                <img :src="photo" class="img-fluid "/>
                                            </span>
                                            {{ username }}
                                        </span>
                                    </template>

                                    <b-dropdown-item active-class="profile-active" exact @click="goProfile">
                                        Profile
                                    </b-dropdown-item>
                                    <b-dropdown-divider></b-dropdown-divider>
                                    <b-dropdown-item active-class="logout-active" exact @click="goLogout">
                                        Logout
                                    </b-dropdown-item>
                                </b-nav-item-dropdown>

                            </b-nav>
                        </div>
                    </div>
```

I've also noticed that since upgrading Bootstrap-Vue to the newer version that the css is changed.
For example, <a>'s used to be black, as defined in our css, now they are using the color `#007bff`. I've changed this back to black and inspected the bootstrap.min.css, but the color is not used anywhere. 
Using `cmd-shift-f` in phpstorm for the color `#007bff` yields no results as well.

Maybe these issues are related?

**Comment by tmorehouse** [comment]
If you are using v0.23.0 use the bootstrap v4.alpha.6 bootstrap.css, Do **not** use the bootstrap v4.0.0.beta.1 bootstrap.css as there are major CSS changes with bootstrap V4.beta release.

If you want to use v4.beta.1 bootstrap CSS, use the 4.1.0.0.beta.5 Bootstarp-Vue branch

**Comment by CrixuAMG** [comment]
I switched to the `4.0.0-alpha.6` version of Bootstrap, and that fixed the css.
The dropdown, however, is still not functioning.

**Comment by CrixuAMG** [comment]
I've just fixed it by completely removing bootstrap and reinstalling it, that somehow fixed it. 
Thanks for helping @tmorehouse!
