### ISSUE TITLE
<b-form-textarea> won't update content when parent value changes

### ISSUE THREAD

**Issue by soichih** [bootstrap-vue/bootstrap-vue#922]
I have following in the form

` <b-form-textarea v-model="selected.desc"></b-form-textarea>`

The `selected` object gets changed when user select from a list with different .desc parameter, but `<b-form-textarea>` doesn't seem to be watching for the value change made in parent.

**Comment by tmorehouse** [comment]
Which version of Bootstrap Vue are you using?  Make sure you are using version 1.0.0.beta.5

**Comment by soichih** [comment]
Yes, I am using 1.0.0.beta.5.

**Comment by tmorehouse** [comment]
Found the issue.  Fixed by commit https://github.com/bootstrap-vue/bootstrap-vue/commit/aeb11be9e26903263f95d5c28948561f5e7753a8 and will be available in release v1.0.0.beta.6

**Comment by tmorehouse** [comment]
Should be fixed in v1.0.0.beta.6

**Comment by soichih** [comment]
Thanks. I just updated to beta.6 and the issue  went away.
