### ISSUE TITLE
Build size

### ISSUE THREAD

**Issue by Ruplahlava** [bootstrap-vue/bootstrap-vue#925]
Hello,
this is a question.
So bootstrap-vue has a dependency vue - so in production build there is vue bundled twice?
Even when i am using the same version? Can i do something about it?

Thanks

**Comment by mosinve** [comment]
Why twice? 
 If you build by webpack or rollup, they handles all dependencies in order to shink build size

**Comment by tmorehouse** [comment]
Or if using the CDN version of BootStrap-Vue, Vue must be loaded before loading Bootstrap-Vue

**Comment by Ruplahlava** [comment]
Built with webpack, and the size of boostrap-vue is 28.22Kb now - probably my bad.
When i was writing it i have noticed that my prod build got bigger a lot - first report told me that it was something around 56 Kb for bootstrap-vue - so i have assumed that it is somehow packed with vue.

Happened after bumping up version from 0.17 to 0.18 (corporate stuff, yay) then running build.
Fixed by removing node_modules and installing it again
