### ISSUE TITLE
The moda is under the navigation bar

### ISSUE THREAD

**Issue by zhangwei900808** [bootstrap-vue/bootstrap-vue#926]
![image](https://user-images.githubusercontent.com/4385154/29706067-1de27e6a-89b3-11e7-9bbf-8c6e89919cbd.png)

**Comment by tmorehouse** [comment]
Make sure you are including the correct version of Bootstrap.CSS depending on the version of Bootstrap-Vue.

Bootstrap's CSS defines the Z-Indez of the modal compared to navbar.

**Comment by zhangwei900808** [comment]
yes I had used the "bootstrap-vue": "^1.0.0-beta.5"
```
import BootstrapVue from 'bootstrap-vue'
import 'bootstrap-vue/dist/bootstrap-vue.css'
import 'bootstrap/dist/css/bootstrap.css'
```

and I set the navbar fixed="top",if I remove the fixed="top" it's worked!

**Comment by tmorehouse** [comment]
It might be a bug in Bootstrap V4.0.0.beta.1 CSS files (there are lots of open issues with it at twbs/bootstrap), which should be addressed when BootstrapV4.0.0.0.beta.2 is released.

**Comment by zhangwei900808** [comment]
Ok,thanks a lot
