### ISSUE TITLE
modal component has a problem

### ISSUE THREAD

**Issue by zhangwei900808** [bootstrap-vue/bootstrap-vue#927]
when I click the delete button in table and the modal is showed and the data is update,but When I click the same button cant show it then I close the modal and click again it's worked ,why?
```
"bootstrap-vue": "^1.0.0-beta.5",
```
```
<template>
    <div class="container contact-list-container">
        <div class="row row-bottom">
            <div class="col-auto">
                <b-button variant="primary" @click="addContact">添加</b-button>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <b-table 
                    striped 
                    hover 
                    bordered
                    show-empty
                    responsive
                    :items="contacts"
                    :fields="fields">
                    <template slot="actions" scope="row">
                        <b-btn size="sm" @click.stop="updateContact(row.item)" variant="success">编辑</b-btn>
                        <b-btn size="sm" @click.stop="showDeleteModal(row.item)" variant="danger">删除</b-btn>
                    </template>
                </b-table>
            </div>
        </div>

       <b-modal id="delModal"
                 ref="delModal"
                 title="提示"
                 ok-title="确定"
                 close-title="取消"
                 @ok="deleteContact">
            <p>您确定要删除 “{{deleteModal.name}}“ 的基本信息吗？</p>
        </b-modal>
    </div>
</template>

<script>
import { mapState,mapActions } from 'vuex'

export default {
  data() {
    return{
        deleteModal:{
            id:0,
            name:''
        },
        fields: {
            index:{label:'#'},
            fullName: { label: '姓名'},
            email: { label: '邮箱' },
            description: { label: '简介' },
            actions:  { label: '操作',class:'text-center' }
        },
        sortBy: null,
        sortDesc: false,
        filter: null,
        modalDetails: { index:'', data:'' }
    }
  },
  computed:{
    ...mapState({
        contacts:state=>state.ContactList.contacts
    })
  },
  created(){
      this.getContacts();
  },
  methods: {
      ...mapActions([
        'getContacts',
        'deleteContactById'
    ]),
    showDeleteModal(contact){
        this.deleteModal.id=contact.id;
        this.deleteModal.name=`${contact.first_name}${contact.last_name}`
        this.$refs.delModal.show();
    },
    addContact(){
        this.$router.push('/contactsManage/addContact')
    },
    updateContact(item){
        console.log('item:')
        console.log(item)
        this.$router.push(`/contactsManage/editContact/${item.id}`)
    },
    deleteContact(){
        this.$refs.delModal.hide();
        this.deleteContactById({
            id:this.deleteModal.id,
            success:()=>{
                this.getContacts();
            }
        })
    }
  }
}
</script>

<style lang="less">
    #delModal{
        .modal-dialog {
            top:100px;
        }
    }
    .contact-list-container{
        .row-bottom{
            margin-bottom:15px;
        }
    }
</style>
```
![image](https://user-images.githubusercontent.com/4385154/29708936-1cb4da6a-89bd-11e7-8069-008632503ffe.png)

### first click
![image](https://user-images.githubusercontent.com/4385154/29708586-b6baa380-89bb-11e7-8df1-a018e4edb31c.png)

### second click
![image](https://user-images.githubusercontent.com/4385154/29708596-c1423fb6-89bb-11e7-9af7-b04cc135e731.png)

### third click
![image](https://user-images.githubusercontent.com/4385154/29708603-ca2290a4-89bb-11e7-9039-3b77bf79a203.png)

**Comment by zhangwei900808** [comment]
I found the reason
![image](https://user-images.githubusercontent.com/4385154/29738060-3c61715e-8a4c-11e7-9ca0-789f8ad0194f.png)
the dom must have class="show" when I set the class it's worked。so why I click the button the show class not add the dom?

**Comment by alexsasharegan** [comment]
This almost sounds like your modal is being triggered twice. How are you triggering the modal open?

**Comment by zhangwei900808** [comment]
I had a method to solve it ,you can see it
```
<b-modal id="delModal"
                 v-model="deleteModal.show"
                 :class="{'delModal':deleteModal.showClass}"
                 title="提示"
                 ok-title="确定"
                 close-title="取消"
                 @ok="deleteContact"
                 no-close-on-backdrop>
            <p>您确定要删除 “{{deleteModal.name}}“ 的联系人信息吗？</p>
        </b-modal>
```

```
showDeleteModal(){
        this.deleteModal.show = true;
        this.deleteModal.showClass = true;
    },
hideDeleteModal(){
                this.deleteModal.show = false;
                this.deleteModal.showClass = false;
}
```

```
.delModal{
            #delModal{
                opacity: 1;
            }
        }
```

**Comment by zhangwei900808** [comment]
@alexsasharegan twice? I see see

**Comment by zhangwei900808** [comment]
I guess when my b-table items is update the b-btn render twice?

**Comment by alexsasharegan** [comment]
You shouldn't need that class `.delModal`. Maybe start by removing the class and see if your problem persists. Also, it's unnecessary when using `v-model` to set the value to false, since that will be triggered automatically by user interactions.

**Comment by elBarkey** [comment]
Same problem here.
I don't have any custom class like @zhangwei900808  did.
Modal open triggered by `this.$refs.myModal.show()` or by v-model has same behavior.
If the modal closed/hidden manually by  triggering v-model  changes or method `this.$refs.myModal.hide()`, the next modal open will only show the unclosable backdrop while the modal div itself doesn't have `show` class.
Otherwise if the modal close triggered by backdrop click or close button. next modal open has no problem.

**Comment by mosinve** [comment]
Hi, check out this snippet please https://jsfiddle.net/cihkem/7xv8r3t7/. Is it fit your use case?

**Comment by mosinve** [comment]
@elBarkey , are you using modal at b-table's slot, too ?

**Comment by elBarkey** [comment]
Yes i am.
I have no time to dig in the b-modal source code.
So my temporary fix is manually call `this.$refs.myModal.is_visible = true` after changing v-model state, or after `$refs.myModal.show()` method.

**Comment by mosinve** [comment]
Checkout example I posted earlier, please.

**Comment by elBarkey** [comment]
Your example is working perfectly.
But the problem is persist in my situation.
The only missing thing from your example is mapped vuex state.
Is it possible that mapped vuex state triggers this behavior?

**Comment by alexsasharegan** [comment]
What do you mean by Vuex state triggers? If you need Vuex state to control v-model, you can use a two way computed property: 

```js
{
  computed: {
    modalShow: {
      get(){
        return this.$store.state.modalShow
      },
      set(show){
        this.$store.commit(UPDATE_MODAL_SHOW, Boolean(show))
      }
    }
  }
}
```
