### ISSUE TITLE
b-form-group label-cols creates class col-sm-undefined  instead of col-sm-4

### ISSUE THREAD

**Issue by r03** [bootstrap-vue/bootstrap-vue#928]
It seems that the label-cols property on b-form-group is not working correct.
The result has class col-sm-undefined  instead of col-sm-4.
I think this is a bug or am I doing something wrong here?

```
<div class="container-fluid">
    <div class="form-row">
      <div class="col">
        <b-form-group class="row" label="Name:" horizontal :label-cols="4">
          <b-form-input 
            :readonly="readonly"            
            plaintext
            v-model="employee.name">
          </b-form-input>
        </b-form-group>      
      </div>
    </div>
  </div>
```

**Comment by mosinve** [comment]
Hi , @r03 which version of BV/BS do you use?

**Comment by r03** [comment]
I installed it with npm:  "bootstrap-vue": "^1.0.0-beta.5"
Bootstrap-vue has a dependency on "bootstrap": "^4.0.0-beta"

**Comment by mosinve** [comment]
It strange then, please have a look at this fiddle https://jsfiddle.net/cjafkr7z/

**Comment by r03** [comment]
Sorry, it was my mistake. I did an upgrade with npm, but didn't restart the webpack dev server. 
Now it just works.
