### ISSUE TITLE
Use CSS File

### ISSUE THREAD

**Issue by MarkSky** [bootstrap-vue/bootstrap-vue#930]
After I used:
`import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';`
I found them were in <head></head>, and display like 
`<style>...</style><style>...</style>` from chrome developer tools.
Could them display like `<link href="styles/bootstrap.css" rel="stylesheet" />`?
How should I do?

**Comment by mosinve** [comment]
It's project bundler related.  You should setup it to extract css and save
it in an external file and then include it in main project's html file.

26 авг. 2017 г. 12:12 пользователь "Mark" <notifications@github.com>
написал:

**Comment by alexsasharegan** [comment]
Yeah, like @mosinve said, this is a build tool related thing. If you're using webpack, you can use the [extractText plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) to pull those style blocks into a dedicated CSS file. What you're seeing is the style loader at work.

**Comment by MarkSky** [comment]
So I have to use the Extract Text Plugin to let the two style files become css files in the web folder,
and I can set `<link href="styles/bootstrap.css" rel="stylesheet" />` in html to use the files.
Thanks.

**Comment by alexsasharegan** [comment]
Let us know if you have any more questions, @MarkSky ! Closing as this appears resolved.

**Comment by MarkSky** [comment]
I have solve my question. Thanks.
