### ISSUE TITLE
Component state in slot doesn't change when paging/sorting/filtering

### ISSUE THREAD

**Issue by jpkleemans** [bootstrap-vue/bootstrap-vue#931]
I have the following (products) table:

```vue
<b-table :fields="fields"
         :items="findAllProducts"
         :current-page="currentPage"
         :per-page="perPage"
         :filter="filter"
         :sort-by.sync="sortBy"
         :sort-desc.sync="sortDesc">

  <template slot="price" scope="data">
    <price-editable :product="data.item"></price-editable>
  </template>

</b-table>
```

`findAllProducts` is a provider function that does an http request based on the current page/sort/filter. `price-editable` is a custom component that renders an inline editable price field.

Now, when I do paging/sorting/filtering, the state (`data`) inside the `price-editable` component stays the same. It doesn't re-render, but keeps the state of the 'previous' row.

**How can I force to re-render a component inside a slot when paging/sorting/filtering?**

**Comment by mosinve** [comment]
did you try to debug `data`, by placing `{{data.item}}` in slot instead your component?

**Comment by jpkleemans** [comment]
@mosinve Yes, that data will update. Also, the props passed to the component are updated (`:product="data.item"`), only the internal state isn't.

**Comment by jpkleemans** [comment]
Say, I have the following internal state in my `price-editable` component:

```js
data () {
  return {
    isEditing: false
  }
}
methods: {
  edit () {
    this.isEditing = true
  }
}
```

When I call `edit()`, `isEditing` will become `true`. When I then for example go to the next page (paginate), `isEditing` will stay `true` for that **row**, even though it is a new **product**.

**Comment by mosinve** [comment]
But data() is the inner state of your component,  which is doesn't depend on any external environment unless you tell to do it

**Comment by mosinve** [comment]
And to have product data inside your component,  you must declare props object:
Props: {
Product: null
}

**Comment by jpkleemans** [comment]
I know, but I would like that the table creates a **new instance** of the component for every **new row**. So when paging/sorting/filtering, it re-renders the component, because it represents a new row. Is that possible?

**Comment by mosinve** [comment]
You can define watch over your product prop,  and in case it changes,  reset internal state of your component

**Comment by alexsasharegan** [comment]
Vue is really intelligent about reusing components for performance. Usually a new key would trigger a new component. Maybe try to add a key on your custom component based on your item id or something unique in your record.

**Comment by mosinve** [comment]
Isn't there any warnings in console?  Maybe try to add :key attribute to your component definition inside slot?

**Comment by alexsasharegan** [comment]
@mosinve, I don't think there will be any warnings because `key` is not required here. What it should do is tell Vue that each `price-editable` component is unique (by id), and render a new component like @jpkleemans is expecting.

**Comment by jpkleemans** [comment]
@alexsasharegan @mosinve Thanks! Adding the `:key="data.item.id"` prop solved my problem. Really the kind of solution I was hoping for!
