### ISSUE TITLE
[form-checkbox] How can I change the background color

### ISSUE THREAD

**Issue by Sparki2002** [bootstrap-vue/bootstrap-vue#937]
Hi, how can I change the blue checkbox background color via vue? (I would like to choose a bootstrap color)

**Comment by tmorehouse** [comment]
The checkbox is generated by Bootstrap V4.beta CSS (it is an embedded SVG icon).

You would need to override the bootstrap.css (embedded base 64 encoded SVG). see https://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios-1
