### ISSUE TITLE
<b-tabs> glitch with active

### ISSUE THREAD

**Issue by zahramajd** [bootstrap-vue/bootstrap-vue#938]
Hi. Currently, there is a bug with `active` attribute which the first view of the tab is empty. But changing back to the same tab makes it visible. I think this problem is happening because of recent transition changes in tabs.

```vue
<b-tabs>
	<b-tab active title="A">Apple</b-tab>
  	<b-tab title="B">Peach</b-tab>
</b-tabs>
```

**Comment by tmorehouse** [comment]
There is a PR that has been merged into the dev branch which should fix this issue.

**Comment by pi0** [comment]
Should be fixed with beta.6 (#912)
