### ISSUE TITLE
Where's the usage docs?

### ISSUE THREAD

**Issue by muhajirframe** [bootstrap-vue/bootstrap-vue#944]

**Comment by muhajirframe** [comment]
Hi, thanks for this great project.
But I can't find the docs. I know there's a documentation on how to install it https://bootstrap-vue.js.org/docs . But how do i use it?

**Comment by mosinve** [comment]
There is a left navbar with links pages describing the usage of components.
![image](https://user-images.githubusercontent.com/20986566/29831267-bfb3dd2a-8d0e-11e7-8415-ed23784424c2.png)

**Comment by muhajirframe** [comment]
Ah, I am sorry. I was browsing with my phone, and can't see that. Perhaps we can't make it not hidden on small screen? Maybe put it at the bottom?

**Comment by mosinve** [comment]
Probably, it's a bug in docs. Thanks for report. :)

**Comment by muhajirframe** [comment]
Okay, good works btw 😊. Shall we close this issue?

**Comment by mosinve** [comment]
We will close, when problem will be fixed ;)
