### ISSUE TITLE
have problems with installing bootstap-vue

### ISSUE THREAD

**Issue by Ben171** [bootstrap-vue/bootstrap-vue#949]
Hi guys, hope someone can help me

i followed the intructions from the docs;

that is my main.js file:

import Vue from 'vue'
import App from './App.vue'
import BootstrapVue from 'bootstrap-vue'
import '../node_modules/bootstrap/dist/css/bootstrap.css'
import '../node_modules/bootstrap-vue/dist/bootstrap-vue.css'

Vue.use(BootstrapVue);

new Vue({
  el: '#app',
  render: h => h(App)
})

when running the dev server (npm run dev) I get the following error: ERROR in ./~/bootstrap-vue/dist/bootstrap-vue.css
Module parse failed: C:\Users\Benjamin\Desktop\theProject\my-project\node_modules\bootstrap-vue\dist\bootstrap-vue.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .b-dropdown .dropdown-item:focus:not(.active),.b-dropdown .dropdown-item:hover:not(.active){box-shadow:inset 0 0 400px 110px rgba(0,0,0,.09)}.b-dropdown .dropdown-item:active{box-shadow:initial}.b-form-group.form-group.is-invalid .invalid-feedback{display:block!important}.custom-file-control[data-v-c68bd5f8]{overflow:hidden}.custom-file-control[data-v-c68bd5f8]{overflow:hidden}.custom-file-control.dragging[data-v-c68bd5f8]{overflow:hidden;filter:blur(3px)}.custom-file-control[data-v-c68bd5f8]::after{content:attr(data-selected)}.custom-file-control[data-v-c68bd5f8]::before{content:attr(data-choose)}.custom-file .drop-here[data-v-c68bd5f8]{position:absolute;left:0;right:0;top:0;bottom:0;background-color:rgba(0,0,0,.5);border-radius:3px;z-index:99999;display:flex;justify-content:center;align-items:center}.custom-file .drop-here[data-v-c68bd5f8]::before{color:#fff;content:attr(data-drop)}.hidden[data-v-1b4cbb68]{opacity:0!important}.modal[data-v-1b4cbb68]{display:block}.b-nav-dropdown .dropdown-item:focus:not(.active),.b-nav-dropdown .dropdown-item:hover:not(.active){box-shadow:inset 0 0 400px 110px rgba(0,0,0,.09)}.b-nav-dropdown .dropdown-item:active{box-shadow:initial}.page-item[data-v-2792960b]{-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}.page-item.disabled[data-v-2792960b]{cursor:not-allowed;opacity:.65}.page-item[data-v-20c4e761]{-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}.page-item.disabled[data-v-20c4e761]{cursor:not-allowed;opacity:.65}table.b-table>tfoot>tr>.sorting,table.b-table>thead>tr>.sorting{padding-right:30px;cursor:pointer;position:relative}table.b-table tfoot>tr>.sorting:after,table.b-table tfoot>tr>.sorting:before,table.b-table thead>tr>.sorting:after,table.b-table thead>tr>.sorting:before{position:absolute;bottom:.9em;display:block;opacity:.3}table.b-table.table-sm>tfoot>tr>.sorting:after,table.b-table.table-sm>tfoot>tr>.sorting:before,table.b-table.table-sm>thead>tr>.sorting:after,table.b-table.table-sm>thead>tr>.sorting:before{bottom:.45em}table.b-table>tfoot>tr>.sorting:before,table.b-table>thead>tr>.sorting:before{right:1em;content:"\2191"}table.b-table>tfoot>tr>.sorting:after,table.b-table>thead>tr>.sorting:after{right:.5em;content:"\2193"}table.b-table>tfoot>tr>.sorting_asc:after,table.b-table>tfoot>tr>.sorting_desc:before,table.b-table>thead>tr>.sorting_asc:after,table.b-table>thead>tr>.sorting_desc:before{opacity:1}table.b-table[aria-busy=false]{opacity:1}table.b-table[aria-busy=true]{opacity:.6}.tooltip{display:block;transition:all .3s}
 @ ./src/main.js 5:0-62
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

ERROR in ./~/bootstrap/dist/css/bootstrap.css
Module parse failed: C:\Users\Benjamin\Desktop\theProject\my-project\node_modules\bootstrap\dist\css\bootstrap.css Unexpected character '@' (7:0)
You may need an appropriate loader to handle this file type.
|  * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
|  */
| @media print {
|   *,
|   *::before,
 @ ./src/main.js 4:0-58
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

----------

that is my package.json file:

{
  "name": "my-project",
  "description": "A Vue.js project",
  "version": "1.0.0",
  "author": "",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "dependencies": {
    "bootstrap-vue": "^1.0.0-beta.5",
    "style-loader": "^0.18.2",
    "vue": "^2.3.3"
  },
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-preset-env": "^1.5.1",
    "cross-env": "^3.0.0",
    "css-loader": "^0.25.0",
    "file-loader": "^0.9.0",
    "node-sass": "^4.5.0",
    "sass-loader": "^5.0.1",
    "vue-loader": "^12.1.0",
    "vue-template-compiler": "^2.3.3",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5"
  }
}

**Comment by tmorehouse** [comment]
Try importing Bootstrap-Vue before you import your app:
```js
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'
import App from './App.vue'
import '../node_modules/bootstrap/dist/css/bootstrap.css'
import '../node_modules/bootstrap-vue/dist/bootstrap-vue.css'
```

**Comment by alexsasharegan** [comment]
Looks like you'll need to configure the webpack style loader. Check out the plugin documentation here: https://github.com/webpack-contrib/style-loader.

Also, here is the webpack 2 documentation of that: https://webpack.js.org/guides/asset-management/#loading-css

**Comment by mosinve** [comment]
Please provide your `webpack.config.js`

**Comment by Ben171** [comment]
var path = require('path')
var webpack = require('webpack')

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/',
    filename: 'build.js'
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            // Since sass-loader (weirdly) has SCSS as its default parse mode, we map
            // the "scss" and "sass" values for the lang attribute to the right configs here.
            // other preprocessors should work out of the box, no loader config like this necessary.
            'scss': 'vue-style-loader!css-loader!sass-loader',
            'sass': 'vue-style-loader!css-loader!sass-loader?indentedSyntax'
          }
          // other vue-loader options go here
        }
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      }
    ]
  },
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    }
  },
  devServer: {
    historyApiFallback: true,
    noInfo: true
  },
  performance: {
    hints: false
  },
  devtool: '#eval-source-map'
}

if (process.env.NODE_ENV === 'production') {
  module.exports.devtool = '#source-map'
  // http://vue-loader.vuejs.org/en/workflow/production.html
  module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false
      }
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  ])
}

**Comment by Ben171** [comment]
can you show me what to change in the webpack-config. I think i need to somehow include the style-loader.

**Comment by tmorehouse** [comment]
I'm not a webpack expert, but you can check https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/build/webpack.config.js

**Comment by mosinve** [comment]
You have to add following lines to `rules `section:

```
            {test: /\.scss?$/, loaders: ['style-loader', 'css-loader', 'sass-loader']},
            {test: /\.css?$/, loaders: ['style-loader', 'css-loader', 'sass-loader']},
```
