### ISSUE TITLE
CDN not working

### ISSUE THREAD

**Issue by knopkem** [bootstrap-vue/bootstrap-vue#95]
The doc mentions this cdn which doesn't seem to be available anymore
<script src="https://unpkg.com/bootstrap-vue/dist/bootstrap-vue.js"></script>

**Comment by pi0** [comment]
@knopkem New builds publish correctly to `dist` and it should work fine now :) Unfortunately it was renamed to `build` for a while...

**Comment by knopkem** [comment]
thanks, works now.
