### ISSUE TITLE
Right align doesn't works for `b-nav-item-dropdown`

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#952]
1. Open: https://bootstrap-vue.js.org/docs/components/nav
2. Scroll to "Dropdown support"
3. Click on the "Dropdown" item

The dropdown opens but is left aligned.
The console shows also an error:
> TypeError: Cannot read property '$el' of undefined

**Comment by tmorehouse** [comment]
This was due to BootstrapV4 beta.1 having changed how dropdowns were positioned.  This should noe be fixed in release v1.0.0.beta.6 of BootsrapVue

**Comment by tmorehouse** [comment]
Hmm, it appears to work in `b-navbar`, but not in `b-nav`.

I will investigate the tests where it check to see if the dropdown is in a nav and/or navbar.

**Comment by tmorehouse** [comment]
This actually appears to be an issue with Bootstrap CSS https://github.com/twbs/bootstrap/issues/23553

In `<b-navbar>`, the alignment works correctly, but if just in a `<b-nav>` it doesn't work correctly.

**Comment by tmorehouse** [comment]
PR #962 should get rid if the `TypeError: Cannot read property '$el' of undefined` error.

**Comment by tmorehouse** [comment]
Fixed in latest release v1.0.0.beta.7

**Comment by jackmu95** [comment]
@tmorehouse Thanks :)
