### ISSUE TITLE
[table] Provide objects as records

### ISSUE THREAD

**Issue by admax81** [bootstrap-vue/bootstrap-vue#953]
I give an array of objects as records for the table, and up to version 1.0.0-beta.5 I could use the methods of these objects.

for example in template
`
<template slot="name" scope="item">
    <div @blur="saveName($event, item)" v-html="item.value" :contenteditable="true"></div>
</template>
`

And add function to methods:
`
savePortName: function(evt, item) {
    item.item.name = $(evt.target).text();
    item.item.save();
},
`

This works fine until 1.0.0-beta.6 update, but now i get error: item.item.save() is not a function

**Comment by alexsasharegan** [comment]
I can't speak to whether or not this adjustment can be made to b-tabs, but there are workarounds. You could use the id of the item to search through your items array and find the object with methods available.

```js
this.items.find( i => i.id === item.id )
```

**Comment by admax81** [comment]
The question is not about the b-tabs question about b-table, and in version 1.0.0-beta.5 it worked, whether I now need to rework all the tables or the possibility of using the functions of objects transferred as an items in the table will come back?

**Comment by alexsasharegan** [comment]
Sorry, that auto-corrected from my phone.

**Comment by mosinve** [comment]
@admax81 , i suspect this was a side-effect not feature.  In current release we simplified usage of b-table, and one of changes was to get a non-reactive copy of items inside table. I suspect, that this was BC for our use case.

**Comment by mosinve** [comment]
As @alexsasharegan said, you should rely on your source data as `source of truth`.

**Comment by admax81** [comment]
I believe that copying the table is done to optimize the speed of working with tables. But, now the tables work more slowly :(

**Comment by tmorehouse** [comment]
Copying the table data is to prevent modifications made by `b-table` from affecting your original record data.  Normally arrays and the contents are copied by reference, and any modification to sorting and record content would also affect your original reference to the table, hence the need to copy the data before altering it.
