### ISSUE TITLE
[tooltip] block native title 

### ISSUE THREAD

**Issue by admax81** [bootstrap-vue/bootstrap-vue#955]
For example in docs page: https://bootstrap-vue.js.org/docs/components/tooltip
`<b-btn v-b-tooltip title="Online!" variant="outline-success">Live chat</b-btn>`

If you hover the button and hold for a while, then will also display a native tooltip. Because button have a title attribute.
You should remove title attribute after hover button or use v-b-content="Text" to define content of tooltip.

**Comment by tmorehouse** [comment]
There is code that should do this in the tooltip base class object, but maybe it is not getting called at the tight time.
