### ISSUE TITLE
[tooltip] Cannot set property 'animation' of undefined at ToolTip.fixTransition

### ISSUE THREAD

**Issue by admax81** [bootstrap-vue/bootstrap-vue#956]
Cannot set property 'animation' of undefined at ToolTip.fixTransition
I'm getting this error in the console. Along with this error, a tooltip appears in the top left corner, which doesn't disappear any more.

**Comment by mosinve** [comment]
transition for tooltip duration set on 300ms.... if you move mouse faster, then you get unpredictable effects :)

**Comment by admax81** [comment]
So, what i need to do to stop it? :)

**Comment by mosinve** [comment]
As one of possible workarounds - slower move mouse ;)

**Comment by mosinve** [comment]
It's a joke of cause, we will look into this problem

**Comment by tmorehouse** [comment]
PR #960 should address this issue.

**Comment by admax81** [comment]
Is not. I'm not getting error anymore, but a tooltip appears in the top left corner, which doesn't disappear any more. :) Second part of bug still work...

**Comment by tmorehouse** [comment]
There have been additional tweaks made to tooltips and popovers to prevent leftover "stranded" divs when doing fast hover/hoverout over the trigger element.

It will be available in the forthcoming release.
