### ISSUE TITLE
[dropdown] @click event

### ISSUE THREAD

**Issue by admax81** [bootstrap-vue/bootstrap-vue#957]
On this page https://bootstrap-vue.js.org/docs/components/dropdown
<b-dropdown> have click event, but it doesn't work.

For example:
```html
<template>
  <b-dropdown size="sm"
              variant="link"
              :text="item.value"
              @click.native="console.log('click native')"
              @click="console.log('click')">
    <b-dropdown-item @click="setUnconfigured(item)">Unconfigured</b-dropdown-item>
    <b-dropdown-item @click="setInternal(item)">Internal</b-dropdown-item>
    <b-dropdown-item @click="setAccess(item)">Access</b-dropdown-item>
    <b-dropdown-item @click="setTrunk(item)">Trunk</b-dropdown-item>
  </b-dropdown>
</template>
```

when I click on the button, I do not receive a message ('click' or 'click native') to the console.

I need to prevent edit another items when some of item has errors, so i need to prevent it here, when button clicked.

**Comment by alexsasharegan** [comment]
The problem is that Vue's template syntax tries to run those methods on the component instance. Since they exist as globals, Vue can't resolve those methods.

I believe the dropdown items use our link component under the hood. This supports a `disabled` property that will kill the default action.

**Comment by tmorehouse** [comment]
You can disabled individual dropdown items (via `disabled` prop on `<b-dropdown-item>`), or the whole dropdown by setting `disabled` on `<b-dropdown>`

**Comment by admax81** [comment]
Yes, I did using the disabled, thank you. But apparently the click event needs to be removed from the documentation, since it is not supported.

**Comment by tmorehouse** [comment]
As mentioned in the documentation, the `click` event is **only** emitted when the dropdown is in "split" mode, and emitted when the split button receives  click.  Clicking a button that toggles the menu emits  `show` or `shown`  events, but not `click`.

See https://bootstrap-vue.js.org/docs/components/dropdown And scroll down to "Split Button Support"
