### ISSUE TITLE
import bootstrap-vue in every component?

### ISSUE THREAD

**Issue by Ben171** [bootstrap-vue/bootstrap-vue#958]
what should i do to use bootstap in a component?

**Comment by mosinve** [comment]
You should import BV once, at main `.js` file of your project. And then `Vue.use()` it. 
This is described at documentation website https://bootstrap-vue.js.org/docs

**Comment by Ben171** [comment]
can I use bootstrap-vue with vuejs 2?

**Comment by tmorehouse** [comment]
Bootstrap-Vue requires Vue v2.3.4 or better.
