### ISSUE TITLE
class is existed but css isn't existed

### ISSUE THREAD

**Issue by DreamColl** [bootstrap-vue/bootstrap-vue#96]
when I use vue-cil and bootstrap-vue
```
<template lang="pug">
    b-form-input(type="Number")
</template>
```
will be
```
<input type="Number" id="6Uj1J" class="form-control form-control-undefined">
```
but css isn't existed

[Source Code Download](https://github.com/DreamColl/TRPG-dice)
npm run dev
http://localhost:9999/#/test

**Comment by pi0** [comment]
@DreamColl As is mentioned in docs, you have to manually include CSS files :)
