### ISSUE TITLE
Custom Field Prop

### ISSUE THREAD

**Issue by SergioReis97** [bootstrap-vue/bootstrap-vue#961]
Trying to use the b-table component, made a component that takes my custom props like actions and stuff and everything works fine. 
Problem, server-side data, trying to use a property of an object in the row, for exemple

```
//Let's pretend this is one of the rows that comes from serverside
{posts:[".",".."],profile:{UseMe:"yay"}};
```

What I'm trying to do is to print "yay" into a column so in fields prop I need to find a way into passing "profile.UseMe"

Maybe arrowfunctions of some sort, for example 
```
fields: {
   customProp: (rowData) => { return rowData.profile.UseMe},
   ...
}
```

**Comment by tmorehouse** [comment]
Check out the latest v1.0.0.beta.6 docs for using custom formatter functions (defined in fields) and custom format slots.

**Comment by tmorehouse** [comment]
Currently, custom formatter only work for fields with actual values.  Although tou could create a custom formatter for field `profile`, that plucks the 'UseMe' property from the value.

Or you would need to create a named scoped slot for your field, which does receive a copy of the full row record data.

**Comment by mosinve** [comment]
Custom formatter function will work with object, you can set one, define it as formatter for profile field and inside function return profile.useme

**Comment by SergioReis97** [comment]
Trying to make it  work with custom formatter 
```
fields: {
   id: { label: 'ID', sortable: true, 'class': 'text-center', formatter:'fullName'},
   actions: { label: 'Actions' }
}
.
.
.
fullName(value) {
   console.log(`${value}`)
   return `${value.profile.UseMe}`
 }
```
Not my main goal but i'm guessing usage would be like that (already on v1.0.0.beta.6)

**Comment by mosinve** [comment]
not exactly, value is the field value, so it should be 
```
 fullName(value) {
   console.log(`${value}`)
   return `${value.UseMe}`
 }
```

**Comment by SergioReis97** [comment]
Using that function and 
`id: { label: 'ID', sortable: true, 'class': 'text-center', formatter: 'fullName' },`
returns same error, console.log outputs undefined

**Comment by mosinve** [comment]
Have you checked docs or fiddle?

**Comment by SergioReis97** [comment]
Changing the label to profile
`profile: { label: 'ID', sortable: true, 'class': 'text-center', formatter: 'fullName' },`
and with that method **DOES** work as intended. But that does bring a "Problem" i guess. Everytime i need a custom formatter it is needed to add a function to get that prop, anyway of sending an aditional parameter to the formatter so it is easy to get dynamic props? so instead of wanting to use UseMe i want to use UseMe2 , instead of new function change parameter.

Other idea is passing either a string with function name or an actual arrow function that allows to make the custom function defining the fields.
I can try and help ou once i get some free time.

**Comment by SergioReis97** [comment]
#976
