### ISSUE TITLE
some components from bootstap-vue do not work for me?

### ISSUE THREAD

**Issue by Ben171** [bootstrap-vue/bootstrap-vue#966]
- for example the form component:

i get the following error message:

[HMR] Waiting for update signal from WDS...
vue.esm.js?65d7:479 [Vue warn]: The "data" option should be a function that returns a per-instance value in component definitions.
warn @ vue.esm.js?65d7:479
vue.esm.js?65d7:7873 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.esm.js?65d7:7883 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
client?23da:64 [WDS] Hot Module Replacement enabled.
vue.esm.js?65d7:479 [Vue warn]: The "data" option should be a function that returns a per-instance value in component definitions.
warn @ vue.esm.js?65d7:479
vue.esm.js?65d7:479 [Vue warn]: Property or method "form" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Form> at C:\Users\Benjamin\Desktop\WebsiteProje

**Comment by tmorehouse** [comment]
Which version of Bootstrap-Vue are you using, and could you provide sample code of your project?

It sounds like you are creating a cusom component which has data sett to an object, not a function. here is how it should look for a component:

```js
export default {
  data() {
    return {
      foo: null,
      bar: true
    }
};
```

**Comment by Ben171** [comment]
`


`

**Comment by Ben171** [comment]
no it is not a custom component. it is a component from bootstap-vue: https://bootstrap-vue.js.org/docs/components/form

**Comment by alexsasharegan** [comment]
The bootstrap-vue form component doesn't utilize any data. The error is coming from another component.
