### ISSUE TITLE
[Question] Why is jQuery downloaded as a dependency?

### ISSUE THREAD

**Issue by hydraheim** [bootstrap-vue/bootstrap-vue#975]
Looking at the result of `npm install bootstrap-vue`, there is apparently a jQuery dependency downloaded as well. 

![bilde](https://user-images.githubusercontent.com/29726093/29912111-c7127e96-8e30-11e7-890e-fddd005dec04.png)

The docs, however, state that _**bootstrap-vue do not**_ require this library.

![bilde](https://user-images.githubusercontent.com/29726093/29912180-0fe4543c-8e31-11e7-8f22-49db4569ac47.png)

There is some illogic going on here. Either the docs or the library itself is wrong upon its dependencies. So which one is it?

**Comment by alexsasharegan** [comment]
Because bootstrap-vue had a dependency on Bootstrap, Bootstrap triggers the jQuery download. Have a look at Bootstrap 4 package.json.

**Comment by tmorehouse** [comment]
Th reason that this is there is to appease Bootstrap, install.  It's specified as an external dependency, but ins't used by Bootstrap-Vue, not included in any final build bundles.

It it there just to make the download of Bootstrap V4 happy.  And hopefully we can remove it once they move from beta to mainline.

**Comment by alexsasharegan** [comment]
@asafyish yes, but check here: https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L69-L72

**Comment by alexsasharegan** [comment]
If anyone has anymore questions here, feel free to ask. Closing since this is a bootstrap `package.json` side-effect, but does not effect the final distribution.

**Comment by pi0** [comment]
I think it would be better to add deps back in `bootstrap-vue@2.0.0`.Still final release of `bootstrap@4.0.0` needs jquery as a peer dep !!

**Comment by ghenry** [comment]
On 23 Jan 2018 08:15, "Pooya Parsa" <notifications@github.com> wrote:

I think it would be better to add deps back in bootstrap-vue@2.0.0.Still
final release of bootstrap@4.0.0 needs jquery as a peer dep !!


Does this mean that users of bootstrap vue will have to pull in jquery?

**Comment by pi0** [comment]
@ghenry Yes. It will be installed when installing `bootstrap-vue` to prevent NPM/Yarn warnings about peer deps. Comparing to the huge size of `node_modules` in projects jquery/bootstrap are really tiny.

Another reason to including back `bootstrap` and its dependencies is that even if `bootstrap-vue` doesn't depend on any specific version of `bootstrap` still there are some implicit dependencies on bootstrap version (Minor versions may introduce some problems). hence if we require a specific version, major of our users will be safe by sticking to the recommended version.

I'm still open to reverting it back if there is any concern to not including it.

**Comment by ghenry** [comment]
Thanks. Does that mean we'll actually be using jquery?

**Comment by pi0** [comment]
@ghenry No no we don't :)) This is just because of BS bad packaging which explicitly requires jquery. I will add some notes to the documentation to clarify this.

**Comment by ghenry** [comment]
Phew!!! I was about to go mental AND START SHOUTING :-)
