### ISSUE TITLE
Table feature suggestion - ability to reference all table data from within the table

### ISSUE THREAD

**Issue by egomolka** [bootstrap-vue/bootstrap-vue#981]
Hi:
Thanks for creating a nice set of components.

I am making heavy use of the "b-table" component, and find it very useful.
I have complex editable tables with inter-dependencies between the contents of different rows. I can successfully save individual rows, but given the inter-dependent nature of the data, I would love to have a "save all" button and save all the database rows to the database.
I don't see a way to do a "save all", because I can't figure out how to reference all of the data at once. I can't access the "items" object directly, and if I just try to save the objects that are passed to "items", they don't have the changes that were made to the table rows.
Hopefully I am just missing the right way to do this. If not, I'd like to nominate this as a very useful feature.

**Comment by tmorehouse** [comment]
You can use the `v-model` feature of table to get the currently displayed  rows (which are a copy of the filtered, sorted and then paginated subset of rows)... only visible rows are returned via the v-model.

**Comment by egomolka** [comment]
Looks like that gives me what I need.
Thanks for the tip!

**Comment by tmorehouse** [comment]
Let us know if that works for you.

**Comment by egomolka** [comment]
I have that approach working. Thanks very much for the fast response.

**Comment by tmorehouse** [comment]
Excellent.
