### ISSUE TITLE
Modal `close-title` slot is not working

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#982]
The `close-title` slot for the modal component is not working.
I looked in the source code of the component and the slot is named `modal-cancel` instead of `close-title`.

**Comment by tmorehouse** [comment]
thanks for finding that... we'll update the docs accordingly

**Comment by tmorehouse** [comment]
Fixed in commit https://github.com/bootstrap-vue/bootstrap-vue/commit/a8772ac385568d299599a55940436e67f1c1354b and should be available in next release docs

**Comment by tmorehouse** [comment]
This has been fixed in the latest published docs online.
