### ISSUE TITLE
Feature request: pass a component to display in the Popover

### ISSUE THREAD

**Issue by Alsciende** [bootstrap-vue/bootstrap-vue#986]
It would be really useful (at least to me) to be able to specify a Vue component to display inside the popover (when using the directive).

````
<span v-b-popover.hover="popoverConfig">{{ user.username }}</span>

...

data() {
    return {
        popoverConfig: {
            props: {
                user: this.user,
            },
            component: {
                name: 'profile-component',
                props: ['user'],
                template: `
                    <b-card :title="user.username" :img-src="user.avatar" img-top>
                        <p class="card-text">{{ user.bio }}</p>
                    </b-card>
                `
            }
        }
    } 
}
````

Inside the popover, this can be implemented with something like:

````
<component :is="b-popover.component" v-bind="b-popover.props"></component>
````

This feature would greatly enhance the popover component, making it able to display absolutely anything, encouraging modularization of code reuse.

**Comment by tmorehouse** [comment]
Currently, this can be done with the popover component (`<b-popover>`), although not using component template config.

This might be possible, but would require the use of render function (or possibly template compiler) inside of the `tooltip.js` class.

Since render functions only generate `vnode` elements (and not real elements), the template compiler build of Vue.JS would be required for your project.  So, we might have to find a way to check if the compiler version of Vue is available.  This would definitely add overhead and size to the BootstrapVue library though.

We'll keep this in mind for sure, as it is a nifty idea.

**Comment by Alsciende** [comment]
In my case, the popover component is not a solution, because I have hundreds of potential targets, and I don't want to generate hundreds of hidden popovers.

Regarding the necessity of render functions : BV is already doing something similar with $refs.content: BV gets the innerHTML of $refs.content and injects it into the PopOver. Isn't it possible to add a hidden template in `<body>`, change its content according to the `component` and `props` arguments to the directive, and inject its innerHTML into the PopOver.

**Comment by tmorehouse** [comment]
When provided with a string template that has components inside, teh Vue.JS template compiler is needed.

With the component version, vue.js is doing the gruntwork pre-compiling your popover content in the app for us (inside  the hidden b-popover component), and we just do a DOM transfer into the popover.

When providing a string template that contains components (and not just plain HTML), using innerHTML grabs the raw content.  Injecting this into the popover content will not provide what you are expecting and the content will not be interactive (as it will be a static copy of the template string).  This is why we created the `<b-popover>` component to complement the directive version.

VueJS will not compile templates on the fly by default, not unless you load the compiler version of Vue into your app.  https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

Note, you can pass an element reference to popover as the 'content', and it will append this element into the content of the popover content container.

**Comment by Alsciende** [comment]
> Note, you can pass an element reference to popover as the 'content', and it will append this element into the content of the popover content container.

Sorry, I can't seem to find documentation for this in the docs. Give you please give me an example?

**Comment by Alsciende** [comment]
> When provided with a string template that has components inside, the Vue.JS template compiler is needed.

What if it's not a string template with a component inside, but a component? Then it should be possible to store it in the data of b-popover and use it with `:is`. Then there's no need for a compiler, is there? I'm no expert, just asking the question.

**Comment by tmorehouse** [comment]
If you have reference to the root element of the component (it needs to be rendered **first**), you can pass that reference to that root element as the `content` parameter of the config options of v-b-popover.

Note popover and tooltip are basically a direct port from the official Bootstrap V4 source code (with tweaks to make it work with Vue).  The options are documented here: https://getbootstrap.com/docs/4.0/components/popovers/#options
.

**Comment by tmorehouse** [comment]
In either case, the component must be rendered first into an actual element.  Popover code only takes basic HTML, a string, or an element reference.

**Comment by tmorehouse** [comment]
You also have to note that the tooltip/popover template (layout of the tooltip/popover) is taken out of the document (DOM) when the tooltip/popover is hidden.  , which is why in the component version, we transfer teh DOM back to the original hidden b-popover (or b-tooltip) container element... otherwise Vue can become unhappy when the renders components are not where it expects them to be.

You also have to not that the Vue library that most use is the compact production version, which doesn't contain the client side compiler, so we cannot assume the compile is available.

**Comment by tmorehouse** [comment]
Also, Vuedals, while not documented as so, requires the full client template compiler build of Vue.

Here is their fiddle updated to use the run-time (production) version of Vue: https://jsfiddle.net/7h4tpouz/

You'll notice that it does not work.

**Comment by Alsciende** [comment]
I found a solution by using a function as value for `v-b-popover`. It does exactly as what I need: https://jsfiddle.net/7h4tpouz/3/.

Thank you for your help. I think this feature request can be closed.

**Comment by tmorehouse** [comment]
Note that while this method works for trigger a single `hover` (rr `focus`, but not both), it may not work for `click` properly.

Your best (safest) bet would be to generate an HTML string with the appropriate HTML markup for a card, which has your content interpolated into the HTML string template, or use `document.elementCreate(...)`, `Element.appendChild`, etc to generate a DOM structure to pass to `v-b-popover`
