### ISSUE TITLE
Contextual input states not handling the feedback message correctly for "Valid" states

### ISSUE THREAD

**Issue by hydraheim** [bootstrap-vue/bootstrap-vue#989]
It seems that when using form-input and defaulting to "valid" instead of "null" when the input validation goes through, the feedback message will still show. 

See the images below:

**State "valid"**
Here, if there is at least 1 character, validation will pass. However, as easily observed, the feedback message still shows the user that something is wrong when there isn't.

![bootstrap-vue-state-error-1](https://user-images.githubusercontent.com/29726093/30024942-695de26a-9176-11e7-9606-2dcfcc107e1e.png)

**On valid, set state to "null"**
Here the state is set to "null" when validation passes. As easily observed, no feedback message is shown.

![bootstrap-vue-state-error-2](https://user-images.githubusercontent.com/29726093/30024944-6a9d96b6-9176-11e7-9d02-85010946161b.png)

Is this intended? From what the docs outline, quote:

> 'valid' is ideal for situations when you have per-field validation throughout a form and want to encourage a user through the rest of the fields.

However, it would not be very encouraging for a user to be shown feedback-errors when there in fact are none.

Docs: https://bootstrap-vue.js.org/docs/components/form-input#contextual-states

**Comment by tmorehouse** [comment]
This is actually a bug in the Bootstrap V4.beta.1 CSS (and BS v4.beata.1 has numerous issues with their new validation css). 

The feedback issue when the form is valid should be addressed in their Bootstrap V4.beta.2 release. 
https://github.com/twbs/bootstrap/issues/23372
https://github.com/bootstrap-vue/bootstrap-vue/issues/747

**Comment by tmorehouse** [comment]
This has been resolved in Bootstrap V4-beta.2 CSS which was released a few days ago.

This will be addressed in Bootstrap-Vue v1.0.0-beta.10.
