### ISSUE TITLE
Dynamic Tabs issue

### ISSUE THREAD

**Issue by weblee** [bootstrap-vue/bootstrap-vue#990]
Hey folks..  Im not sure if this is a tab issue or maybe just the way Vue works and I am missing something.

I am trying to set up a set of dynamic tabs.. But when I click the add button the tab does not appear. But the minute I update something else on page it then shows. I have created a fiddle as an example.

https://jsfiddle.net/0ax660z1/3/

If you click add Spanish first... then just write some text in the input field you will see what I mean.

Hope someone can advise.

**Comment by mosinve** [comment]
Check this https://jsfiddle.net/cihkem/huah1Lr8/
And read docs about Reactivity in Vue https://vuejs.org/v2/guide/reactivity.html

**Comment by alexsasharegan** [comment]
Adding object properties on the fly is one of the reactivity limitations of Vue. Reactivity is enabled by _initializing_ a data property using `Object.defineProperty`. If you change the structure after initialization, you need to use vue's `$set` method. In this case, however, you should probably be using an array: https://jsfiddle.net/r8uwwd2b/

**Comment by tmorehouse** [comment]
Another option is to use `Object.assign({}, ... , ...)` to return a **new** value for tabs:

https://jsfiddle.net/9y067ytz/

This will ensure reactivity because the reference that `tabs` contains changes.

**Comment by weblee** [comment]
Thank you all for you very helpful comments and instructions...  Learning every day !
