### ISSUE TITLE
[Docs] Search field on documentation page is disabled

### ISSUE THREAD

**Issue by RMoisiuk** [bootstrap-vue/bootstrap-vue#992]
Search field on documentation page is disabled.

**Comment by mosinve** [comment]
Hi, it's not bug, it's feature ;)

**Comment by alexsasharegan** [comment]
I think Algolia search is our planned integration, but we haven't found the time to add it yet.

**Comment by tmorehouse** [comment]
The search now works when you run the docs in dev mode locally, and should be working in the next release v1.0.0.beta.10 when it comes out.
