### ISSUE TITLE
Carousel not good for chrome 

### ISSUE THREAD

**Issue by AlanGuo** [bootstrap-vue/bootstrap-vue#993]
I added a demo Carousel for test and find that not good for chrome, howerver the official demo is good.
so I run into the code and find the different, I don't know why , maybe lost something to do, but I really need help.

the offical demo below.
![image](https://user-images.githubusercontent.com/727863/30075715-390f4660-92a9-11e7-9a02-4b26925c11a8.png)

the dist/bootstrap-vue.esm.js code locally installed by npm.
![image](https://user-images.githubusercontent.com/727863/30075736-474076be-92a9-11e7-89d0-58eda303dbab.png)

the red line is the key, why doesn't the locally code have the red line?

**Comment by tmorehouse** [comment]
Which version of Bootstrap-Vue are you using? the alpha branch or the beta branch?

**Comment by AlanGuo** [comment]
![image](https://user-images.githubusercontent.com/727863/30076332-176ed4e2-92ab-11e7-8eba-7097b8b2228f.png)
the latest  Bootstrap V4.beta

**Comment by tmorehouse** [comment]
It looks like that code may have been optimized out during transpilation/rollup.  It is needed to force a reflow of the slide when the classes change

**Comment by AlanGuo** [comment]
@tmorehouse so you will handle this ?

**Comment by tmorehouse** [comment]
Are you building this dist yourself, or using the dist packages via `unpkg.com` ?

**Comment by tmorehouse** [comment]
And could you describe the issue you are seeing with how carousel is working/not-working?

**Comment by AlanGuo** [comment]
no ,I am not building this dist myself,  just npm i  bootstrap-vue@1.0.0-beta.7 and @nuxtjs/bootstrap-vue

**Comment by AlanGuo** [comment]
![jietu20170906-101129](https://user-images.githubusercontent.com/727863/30091478-5bae22ca-92ec-11e7-8790-9659e0b797fc.gif)

**Comment by tmorehouse** [comment]
This should be fixed in the next release.
