### ISSUE TITLE
[b-col] Add custom breakpoint

### ISSUE THREAD

**Issue by jezperp** [bootstrap-vue/bootstrap-vue#997]
Hi! I would like to add a custom breakpoint option (xxl). I've added the breakpoint correctly in my Sass variables file, now I only need BootstrapVue to properly generate this new breakpoint.

Usage:
`<b-col sm="6" md="4" lg="3" xl="2" xxl="1"></b-col>`

Is this possible to do without changing core files? Or maybe add as a new feature?

**Comment by tmorehouse** [comment]
The core `b-col` component defines the props for each breakpoint.  So adding a custom breakpoint would need to alter the code.

You can however, ass custom classes to the `b-col` component, just like one would do when using plain HTML and bootstrap classes.

**Comment by alexsasharegan** [comment]
The column layout component uses a lot of looping to generate and parse all the props. I'm not entirely sure it would be worth the extra overhead to add custom breakpoints, but we'll take a look.

I agree with @tmorehouse, you're best option is to just add your own class on top:
```html
<b-col sm="6" md="4" lg="3" xl="2" class="col-xxl-1"></b-col>
```

**Comment by m-demydiuk** [comment]
Hi, is there any progress with adding custom breakpoints? It would be great to have xxl breakpoint say at 1400px

**Comment by tmorehouse** [comment]
@m-demydiuk 

it has been available for quite some time now.

You need to update your SASS variables (https://bootstrap-vue.js.org/docs/reference/theming), and then instruct BootstrapVue as to the breakpoints names (https://bootstrap-vue.js.org/docs/misc/settings)

**Comment by lichaozhy** [comment]
```scss
$grid-breakpoints: (
	xs: 0,
	sm: 576px,
	md: 768px,
	lg: 992px,
	xl: 1200px,
	xxl: 1600px
);

$container-max-widths: (
	sm: 540px,
	md: 720px,
	lg: 960px,
	xl: 1140px,
	xxl: 1560px
) !default;

@import '~bootstrap/scss/bootstrap.scss';
@import '~bootstrap-vue/src/index.scss';
```
You may set all size values like the code above.
