### ISSUE TITLE
Tooltip is 'undefined' in popover.js

### ISSUE THREAD

**Issue by milenon** [bootstrap-vue/bootstrap-vue#998]
I'm running my project with Webpack, using bootstrap-vue@1.0.0-beta.7 and in my vue files I'm directly importing only the components I need like this:

`    import Popover from 'bootstrap-vue/lib/components/popover.vue';`
	
And I have the error that Tooltip is 'undefined' in popover.js.

I think this is due to circular dependency because in popover.js we are importing Tooltip from the index.js where we are importing the Popover again. 
And we have the same issue in tooltip.js where we are importing 
`import { BvEvent } from './';`

I think that for files residing in the same folder we should go with straight imports:
```
import ToolTip from './tooltip';
import BvEvent from './BvEvent';
```

**Comment by tmorehouse** [comment]
This will be available in the next release v1.0.0.beta.8
